### ISSUE TITLE
TVNow Videoplayer doesn't like Adblocker

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#1]
### Describe the issue

If you try to watch videos on tvnow with an adblocker enabled, the content is replaced with a warning
that they detected an adblocker in use and you can't get the video to play.
### One or more specific URLs where the issue occurs

http://www.tvnow.de/rtl/stern-tv/list/aktuell/thema-ua-keyless-go-systeme/player
http://www.tvnow.de/ntv/n-tv-dokumentation/list/aktuell/border-patrol-einsatz-an-der-grenze-4/player
### Screenshot(s)

![tvnow-ab](https://cloud.githubusercontent.com/assets/17909/14241736/592badc6-fa4d-11e5-80e1-2e41dd29de70.JPG)
### Your settings
- Browser/version: FF45
- uBlock Origin version: 1.6.7rc2

**Comment by yoshimo** [comment]
Either that happens or if i do not attempt to mess with the defaults, i get ads about razors between the chapters from
http://591379ee8808f864af52cafe4a1a7ba9d48c08f6.10.damoh.tvnow.de/crossdomain.xml
which seems to be related to http://www.schneevonmorgen.com/ and is also used on golem.de

**Comment by Recol** [comment]
Personally, i've had a look at the look at the logger for this.  The .XML file seems to make sure that in order for the content to be played, the browser must be connected to the ad-domains. If a connection is not established then the ad-block popup will appear. Since it's embedded inside the player, i cannot find a way to bypass it either. 

![](http://i.imgur.com/Ji7OH07.png)
All of the ad-servers require a HTTPS connection aswell, and the hosting domain does not. If you ask me, that seems fishy.

**Comment by Hrxn** [comment]
Fishy? Do you think that tvnow.de is a dubious site somehow?

**Comment by gorhill** [comment]
The site uses Flash applet, which is a proprietary blob, which means the site turns one's browser into a proprietary device. Maybe there is a solution, but I personally do not intend to spend an inordinate amount of time on issues which arise from the use of proprietary blobs. This is the nice aspect of uAssets, anybody who feel like solving any specific issue can pitch in.

**Comment by yoshimo** [comment]
Someone got around video ads on golem.de by grabbing the video url and feeding it into the html5 player of the browser.
https://greasyfork.org/de/scripts/1195-html5-video-f%C3%BCr-golem-de
Is Ublocks replace function powerfull enough to do that trick ?

**Comment by gorhill** [comment]
? Is Ublocks replace function powerfull enough to do that trick ?

I don't see any issue with video playback on golem.de -- so long as one disable Flash plugin, which is the recommended solution, no need for a user script.

**Comment by yoshimo** [comment]
gorhill, both sites use the same stupid advertising company, tvnow is flash only, golem just recently added the html5 player.
So what people did in the past was ditching flash and ripping out the correct video urls and feed them directly into the browser player.
So i showed how it was done on golem to allow more experienced people to adapt the solution to tvnow.

**Comment by okiehsch** [comment]
Same issue as https://github.com/uBlockOrigin/uAssets/issues/621. This issue is over a year old so I
will close this one.

**Comment by Raavizz** [comment]
> @yoshimo  : stupid advertising company

Stop your drama / insulting / bad words.
