### ISSUE TITLE
Interstetial double click ad appearing 

### ISSUE THREAD

**Issue by castor-troy** [uBlockOrigin/uAssets#10]
### Describe the issue

Interstetial ad of doubleclick appearing though its blocked in ublock
### One or more specific URLs where the issue occurs

http://www.firstpost.com
### Screenshot in which the issue can be seen

![1](https://cloud.githubusercontent.com/assets/3329844/14417028/f3637970-ffcd-11e5-9d0c-02f87c6d59c0.png)
![2](https://cloud.githubusercontent.com/assets/3329844/14417036/1125b946-ffce-11e5-92fa-b52fbe41c43f.png)
![3](https://cloud.githubusercontent.com/assets/3329844/14417039/187b35c2-ffce-11e5-827b-d0a1d3000673.png)
### Steps for anyone to reproduce the issue

The first time we visit the site firstpost.com, it shows an interstetial ad. I doesnt happen in the same session again, but if you close the browser and reopen it, the ad comes. I blocked doubleclick universally using ublock origin.
### Your settings
- Browser/version: Firefox 45.0.1
- uBlock Origin version: uBlock Origin 1.6.8
##### Your filter lists

![4](https://cloud.githubusercontent.com/assets/3329844/14417066/9335a3ce-ffce-11e5-80d7-4ba96b34f8c8.png)
##### Your custom filters (if any)

....
....
     \* doubleclick.net \* block
....
....

**Comment by IDKwhattoputhere** [comment]
The ad is not loaded from Doubleclick servers. I don't know why you think it is. Using [**the element picker**](https://github.com/gorhill/uBlock/wiki/Element-picker) you can easily see that it's loaded from `firstpost.in`.
This filter will hide it: `firstpost.com##a[href^=" http://pubads.g.doubleclick.net/"]`

**Comment by gorhill** [comment]
This is the inline script code which causes the issue:

    if ( !FPgetcookieForDFP('FP_PreInter_v4') )
    {
        window.location = "http://www.firstpost.com/promo/ncdex-int-new.html";
    }

The site is using a cookie to decide whether to redirect to the ad page. Clearing the cookies for the site allows to easily reproduce the issue.

A scriptlet will probably take care of the issue, but I want to give some thoughts about whether I can address this in a generic way given that the cookie approach is used by other sites too.

**Comment by Recol** [comment]
Perhaps by clearing the specific cookie_s_ which are related to this site on a refresh-basis. A whitelist could be built up, or better yet, allow people to contribute URL's which use this approach to show advertisements.

**Comment by MarkTheFucker** [comment]
Block 3rd party data and cookies and it wont happen
