### ISSUE TITLE
NSFW gelbooru.com broken

### ISSUE THREAD

**Issue by Vestamitts** [uBlockOrigin/uAssets#100]
### URL(s) where the issue occurs

Front page: `http://gelbooru.com/`
Index page: `http://gelbooru.com/index.php?page=post&s=list&tags=dummytag`
WebM: `http://gelbooru.com/index.php?page=post&s=view&id=3301900`

### Describe the issue

A number of filters included in AdGuard and Fanboy+EasyList Merged cause the front page (first link) to not load at all, and the search function on the index page (second link) to be hidden. WebM playback on the site is also broken.

In addition, there are some unblocked ads that occasionally appear in the sidebar on the index page. This ad does not frequently appear.

### Screenshot(s)

How the index page should look with ads blocked:
![fireshot screen capture 003 - image list _ dummytag i gelbooru - gelbooru_com_index_php_page post s list tags dummytag](https://cloud.githubusercontent.com/assets/20970916/17589885/f67aceec-5f8b-11e6-9624-671da825fd35.png)

How the index page looks with the problem:
![fireshot screen capture 004 - image list _ dummytag i gelbooru - gelbooru_com_index_php_page post s list tags dummytag](https://cloud.githubusercontent.com/assets/20970916/17589888/f991ffec-5f8b-11e6-97ce-cbf923216f6b.png)

Note that on index pages with no results, the sidebar ad does not seem to display.

### Versions

- Browser/version: Pale Moon 26.3.3
- uBlock Origin version: 1.8.5b2, also tested with 1.8.4

### Settings
- Turned off "Show the number of blocked requests on the icon"
- Turned on "I am an advanced user"
- Turned on "Prevent WebRTC from leaking local IP addresses"
- Subscribed to a number of the included lists, and added AdGuard English ('https://adguard.com/en/filter-rules.html?id=14')

### Notes

To fix the main page not loading:
`gelbooru.com#@#[style^="background:"]`

To fix the search box on  both the front page and index page:
`gelbooru.com#@#center > div[style]`
As far as I can tell the above two changes do not seem to have any side effects other than fixing the problem.

To fix webm playback:
`gelbooru.com#@#center > div[style*="overflow:"]`
However this also causes a number of otherwise blocked ads to be displayed at the bottom of the index page.

To block the ads unblocked by fixing WebM playback:
`gelbooru.com##center > div[style*="width:1000px; overflow:hidden"]`

I have not had any success getting the sidebar ad blocked on the index page. I have not been able to figure out what triggers it to load, it does not appear most of the time.

**Comment by gorhill** [comment]
> A number of filters included in AdGuard and Fanboy+EasyList Merged cause the front page

This should be reported to AdGuard and EasyList maintainers. Adding filters in uBO to fix problematic filters somewhere else is not optimal.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=31945

**Comment by gorhill** [comment]
Fixed as per thread: <https://forums.lanik.us/viewtopic.php?p=100296#p100296>.
