### ISSUE TITLE
revouninstaller.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10004]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.revouninstaller.com/`
`https://www.revouninstaller.com/revo-uninstaller-free-download/`

### Describe the issue

Self-promo at first visit - with locked scroll, need big monitor for dectect locked scroll or -Zoom to 50-70%.

fyi @ryanbr / @Khrin / @montza / @smed79 

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/133326129-b7c48f00-0172-4985-82c2-07f890489667.png)

Or wait to start autumn/fall or winter?

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Settings

- Enabled uBO annoyances.

### Notes

On Firefox almost at all works html filtering (html filtering may no works then we first open about:config page and then any page - see https://github.com/uBlockOrigin/uBlock-issues/issues/1636#issuecomment-901803803):

```
revouninstaller.com##^#popupModal.promo, .modal-backdrop
```

For support chrome needed is convert to scriptlet/ `:style()` filter:

`revouninstaller.com##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`

to unlock scrolling or close as wonfix all this issue. I tested `:remove()` and works too late (scroll is locking after few seconds without pop-up..., in my private tests `:remove()` have ~10% chance to not load `modal-open` plugin to lock scroll on any page).

**Comment by uBlock-user** [comment]
> with locked scroll

Don't see any locked scroll

**Comment by krystian3w** [comment]
Try zoom at 50% or in devtools  found `.modal-open` if pop-up are visible.

Small right is fake due bug with position image at center.

**Comment by ExtremelyCool** [comment]
> > with locked scroll
> 
> Don't see any locked scroll
@uBlock-user I think the locked scroll can be encountered with the annoyance.

**Comment by krystian3w** [comment]
On small screen possible see fake scroll for pop-up only, not for body/html.

**Comment by ExtremelyCool** [comment]
> 
> I can try save to zip but @mapx- like close issue after I sent zip-s.

zip with what exactly?

**Comment by krystian3w** [comment]
For html source the I see pop-up, then possible unpack to "localhost" and create filter like:

`localhost##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`

**Comment by uBlock-user** [comment]
I can scroll just fine, zooming doesn't block scroll bar itself.

**Comment by krystian3w** [comment]
So we have diffrenct html codes at page, mark as won't fix?

**Comment by uBlock-user** [comment]
Lets wait for others to reproduce locked scroll issue...

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/133341285-7d2b3fb6-2a4d-4b39-ac3e-7ea7956876f9.png)

**Comment by krystian3w** [comment]
[Page have English version - Revo Uninstaller Pro.zip](https://github.com/uBlockOrigin/uAssets/files/7165427/Page.have.English.version.-.Revo.Uninstaller.Pro.zip)  - I publish zip to allow close this as malformed by my env.

**Comment by yourduskquibbles** [comment]
I can reproduce first page load of `https://www.revouninstaller.com/revo-uninstaller-free-download/`

![revou](https://user-images.githubusercontent.com/22258847/133441195-a346a5c8-22c9-4cf6-abba-6d6df9ab9a7a.png)

**Comment by krystian3w** [comment]
But a Little diffrent, maybe  better wait to Hallowen pop-up edition.

**Comment by uBlock-user** [comment]
@yourduskquibbles Without zooming down manually to 30 % ?

**Comment by yourduskquibbles** [comment]
Yes at 100% zoom it pops up.

I think just adding these would fix it?
`revouninstaller.com###popupModal, .modal-backdrop`
`revouninstaller.com##body.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`

**Comment by krystian3w** [comment]
No, uBo annoyances should be detect when pop-up malformed scroll.

**Comment by uBlock-user** [comment]
Yeah those work as expected, go ahead add it then.

**Comment by yourduskquibbles** [comment]
I added to uBO Annoyances - I think it solves issue but maybe I am misunderstanding what @krystian3w is seeing. With `revouninstaller.com##body.modal-open:style(overflow: auto !important; padding-right: 0 !important;)` I don't have any scrolling issues tested at full screen 100% zoom and 30% zoom and tiny width 100% zoom and 30% zoom on a 16x10 monitor

**Comment by krystian3w** [comment]
I mean page rare load pop-up when CSS isn't need.

**Comment by yourduskquibbles** [comment]
@krystian3w Are you saying modal filters without a companion setting CSS overflow filter almost never happens on any site? (I agree with that...) 

Or is your issue not fixed on `revouninstaller.com`? I'm not following translation if you are saying there is still some issue after those filters I added

**Comment by krystian3w** [comment]
I see two problems:

- uAssets cut pop-up where site sometime not lock scroll - maybe better add `.modal-open` to first line too...
- for logged users break all other modal open pop-ups - then better add `.promo`, html filtering and scriptlet for Chromiu&Safari env.
