### ISSUE TITLE
Reddit ads not properly being blocked

### ISSUE THREAD

**Issue by z11h** [uBlockOrigin/uAssets#10008]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.reddit.com/r/PS5restock/
https://www.reddit.com/
https://www.reddit.com/r/apple
```

### Describe the issue

sponsored posts on reddit still showing up.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/11602629/133389633-9a6e114d-c4b3-420f-bdff-0c1f87c38a79.png)

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Chrome 96

### Settings

none

**Comment by gwarser** [comment]
Can you reproduce on Chrome stable?

**Comment by Mennaruuk** [comment]
I cannot reproduce the issue on Firefox 92.0, Brave 1.29.81, and Chrome 93.0.4577.82.
