### ISSUE TITLE
easeus.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10019]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.easeus.com/ios-tips/mac-keeps-restarting.html`

### Describe the issue

Annoyance: Sale overlay.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/133662357-42d67ef5-93a1-4772-87aa-82de06b34aa6.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

N/A

**Comment by uBlock-user** [comment]
```
easeus.com##.float_banner
easeus.com##[class^=pop_]
```

Self promos, should be reported to Fanboy Annoyances list.
