### ISSUE TITLE
inews detects adblocker in use, blocks access to site.

### ISSUE THREAD

**Issue by RedactedCode** [uBlockOrigin/uAssets#10018]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`inews.co.uk`

### Describe the issue

inews detects that an adblocker is in use & pops a large notice in screen centre telling you to disable the blocker.

the notice can't be dismissed.

the notice can't be blocked as an element without making the site unreadable.

### Screenshot(s)

![2021 09 16_10 11 33_inews co uk_967ff612a465n](https://user-images.githubusercontent.com/31665276/133588205-fa33f3c1-a965-44c0-b0ec-9efd6c4efa35.png)

### uBlock Origin version

1.37.2

### Browser name and version

Vivaldi 4.2.2406.44 (Linux 64-bit) [Chrome/93.0.4577.83 ]

### Settings

![2021 09 16_10 38 36_cjpalhdlnbpafiamejdnhcphjbkeiagm_9bbc84aeb6cdn](https://user-images.githubusercontent.com/31665276/133589230-11f87ac0-c6ac-4e98-8c37-74f3bc7179a1.png)
![2021 09 16_10 38 02_cjpalhdlnbpafiamejdnhcphjbkeiagm_8a00a8794dfbn](https://user-images.githubusercontent.com/31665276/133589233-7a8c0048-57fc-41fc-906a-4b50f293ed85.png)

**Comment by okiehsch** [comment]
Already fixed on my end, I can only reproduce if I disable the `uBO-filters` list.
Your screenshot does not show if you have that list enabled or not.

**Comment by RedactedCode** [comment]
I can't see any filter called "uBO-filters" ?

**Comment by okiehsch** [comment]
It's the the first one in the "built in" section. 
"uBlock filters"

**Comment by uBlock-user** [comment]
Reset to default settings + disable all other extensions extensions installed.
