### ISSUE TITLE
Add antivirustoolext.com to the list

### ISSUE THREAD

**Issue by Pryx** [uBlockOrigin/uAssets#1001]
### URL(s) where the issue occurs

http://antivirustoolext.com/ff/

### Describe the issue
Tries to look like firefox updater site, trying to get you to install extension even going to full screen mode. Very annoying.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/5222912/34019612-196c4efe-e130-11e7-9e83-1f02ba5efb5f.png)

Hope this is the right place to write 🙂

**Comment by okiehsch** [comment]
Well, how did you end up at that site.

**Comment by Pryx** [comment]
Was just about to edit that as I thought it would be useful. The page on which it happens is https://hdeuropix.com - it has a lot of ads that open like this, most of which uBlock eliminates :) Added my own rule in the meantime, just thought it would be useful for others

**Comment by okiehsch** [comment]
I tried `https://hdeuropix.com/tvseries/the-office-online/the-office-season-9-hd-with-subtitles europix`

Adding
````
hdeuropix.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)
````
kills the redirection on my end.

**Comment by jspenguin2017** [comment]
I got another report here: https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-351823110
`http://tooladblockerext.com/ff/?_subid=20k3d7e46d044svolcd&_token=uuid_20k3d7e46d044svolcd_20k3d7e46d044svolcd5a32d6f6f38d84.59487681`

**Comment by okiehsch** [comment]
@jspenguin2017 I can also add `||tooladblockerext.com^` but I think disabling the source of the redirect, if possible, is the better fix, as they can change their redirection chains easily enough.

**Comment by jspenguin2017** [comment]
I agree, still should block the malware serving domain as a fallback though.

**Comment by Siarl** [comment]
Thanks!

**Comment by gotitbro** [comment]
@jspenguin2017 These spammers or malvertisers auto register such domains en masse, most of these aren't even maintained after the initial domain registration. They just keep skipping domains.

The above domain for example was registered recently for a one year period (as most such domains are) through **internetbs.net** which is a known spammer haven https://www.whois.com/whois/tooladblockerext.com.

Such domains shouldn't be added to lists but, as rightly said by @okiehsch, the source redirecting to such domains should be blocked or nulled (the source might be a compromised ad network or a malware network itself).

**Comment by jspenguin2017** [comment]
I am aware that they register domains in mass and they discard them pretty quick, but I don't see how can you clean up the source that does the redirection neither.
