### ISSUE TITLE
newpct.com ADS [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1002]
URL(s) where the issue occurs

http://www.newpct.com/descargar-pelicula/valerian-y-la-ciudad-de-los-mil-planetas/blurayrip-ac3-5-1/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
the page redirects me to another page of misleading advertising

**Comment by xDarkARG** [comment]
here is a clone page or sister page @mapx-  
the page redirects me to another page of misleading advertising

http://newpct1.com/descargar/conoces-a-joe-black-bluray-rip-ac3-2-0-espaa-a-ol-castellano/blurayrip/

**Comment by mapx-** [comment]
I get no new popup / redirecting (the site is already managed by ublock filters)

**Comment by KiLL4FuNK** [comment]
@mapx- clon ads Pop-up `http://descargas2020.com/`
