### ISSUE TITLE
calendar.google.com

### ISSUE THREAD

**Issue by taoufik07** [uBlockOrigin/uAssets#10020]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://calendar.google.com/calendar/u/0/r/week/2021/12/3`

### Describe the issue

A blank space appears on the right 

### Screenshot(s)

<img width="1177" alt="Screenshot 2021-09-17 at 15 47 12" src="https://user-images.githubusercontent.com/22898667/133793601-9e0136b7-01e4-40fe-8752-9072102b5155.png">

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

<img width="651" alt="Screenshot 2021-09-17 at 15 51 10" src="https://user-images.githubusercontent.com/22898667/133793996-60fd1e23-6062-4d6d-957e-5ce7eb934956.png">
<img width="651" alt="Screenshot 2021-09-17 at 15 51 49" src="https://user-images.githubusercontent.com/22898667/133794011-53835860-f4d0-4450-ba84-43dbd8e5e323.png">
<img width="651" alt="Screenshot 2021-09-17 at 15 51 10" src="https://user-images.githubusercontent.com/22898667/133794017-438282e3-75a9-42b2-be15-70c281b601db.png">

### Notes

Adding `width: 100%` to the body solves it

**Comment by uBlock-user** [comment]
> A blank space appears on the right

You're not on default settings/lists, test on default settings/lists.
