### ISSUE TITLE
[Anti-copy] blog.csdn.net

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10038]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.csdn.net/qq_26884501/article/details/108142928`

### Describe the issue

Code block prohibits copying and requires user login

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/133919999-20cecb0b-4a77-447e-96e7-09289c1cb60a.png)

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

_No need_

**Comment by shenzhiming88** [comment]
@okiehsch Hello!
It is best to add `blog.csdn.net##.hljs-button.signin` again, this is to ask the user to log in and then copy the button, do not use `blog.csdn.net##.hljs-button` is to be able to display the copy button after the user logs in
Login buttom
![image](https://user-images.githubusercontent.com/66902050/133920967-25eadbfa-1258-4bfe-b3d9-e3da10d694a4.png)

Copy buttom
![image](https://user-images.githubusercontent.com/66902050/133921001-5ebdb931-3bf0-44a6-94db-9f6c975243ce.png)

**Comment by okiehsch** [comment]
If I add
`blog.csdn.net##.hljs-button.signin`
how do users who want to signin do that?

**Comment by shenzhiming88** [comment]
@okiehsch This is the normal login button
![image](https://user-images.githubusercontent.com/66902050/133922959-614bea7c-4c05-4e8a-9167-0706523c4bcd.png)

**Comment by shenzhiming88** [comment]
@okiehsch This seems to have expired, please check it, thank you

**Comment by okiehsch** [comment]
What do you mean by "expired"?

**Comment by shenzhiming88** [comment]
@okiehsch 
Yes, it still works on that site, but not on this one
`https://blog.csdn.net/qq_33242126/article/details/103277019`
![image](https://user-images.githubusercontent.com/66902050/135439496-1ddff644-b60c-4026-82fb-a1f73eec3442.png)

**Comment by okiehsch** [comment]
````
blog.csdn.net##.hljs:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
````
works for that site, let me know if other pages still don't work with that filter.

**Comment by uBlock-user** [comment]
`blog.csdn.net##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)`

will future-proof this site.

**Comment by okiehsch** [comment]
I know that's why I asked about other sites. If more then two filters are needed we will simply use a style filter for the complete site.

**Comment by shenzhiming88** [comment]
I can't find another site at the moment. If so, I will raise it again under that issue. Thank you very much!

**Comment by shenzhiming88** [comment]
@okiehsch `https://blog.csdn.net/qqLiSi/article/details/86766592`
This page doesn't seem to be able to select the code area again. Please check, thanks!
