### ISSUE TITLE
cda-hd.cc

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10039]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://cda-hd.cc/53545/w-labiryncie-into-the-labyrinth-luomo-del-labirinto-2019-online/`

### Describe the issue

- ad before start origin video ("pre-roll ad 5 second") similar to https://github.com/uBlockOrigin/uAssets/issues/8957 - fyi @majkiit (and maybe fyi: @trollzbozowy @adblock-filters, @easylistpolish)

I reported here because page has:

- **blocked right click on whole elements**

### Screenshot(s)

For ads:

![obraz](https://user-images.githubusercontent.com/35370833/133935279-98d6d604-89c7-4515-87db-7b7e69946694.png)

Anti-right click may no need any screen for javascript (to aprove how blocked is that action).

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Settings

- enabled: uBo Annoyances

**Comment by krystian3w** [comment]
@Yuki2718 / @uBlock-user right click on blue background is still blocked, no possible repair without broke page/CloudFlare anti-both hCaptcha?

**Comment by uBlock-user** [comment]
> right click on blue background or links are still blocked

on the player ?

**Comment by krystian3w** [comment]
No, on header:

![obraz](https://user-images.githubusercontent.com/35370833/133936777-652bfd92-c6ff-4a12-8534-d7a3ff405313.png)

Or left background empty place:

![obraz](https://user-images.githubusercontent.com/35370833/133936824-6ed442b4-7c05-4a39-997e-cbc25cba5501.png)


same url as first post:

```
https://cda-hd.cc/53545/w-labiryncie-into-the-labyrinth-luomo-del-labirinto-2019-online/?__cf_chl_managed_tk__=pmd_Ar2drmirOb3SUGBZp1k7xemWHOXCaEDoXZrvJMTvFns-1632071549-0-gqNtZGzNAxCjcnBszRER
https://cda-hd.cc/53545/w-labiryncie-into-the-labyrinth-luomo-del-labirinto-2019-online/
```

**Comment by krystian3w** [comment]
Maybe we have diffrent domain with crap JS file to block mouse events - ten maybe needed is regex instead paste many domains.

**Comment by uBlock-user** [comment]
@krystian3w `cda-hd.cc,hqq.to##+js(set, document.oncontextmenu, null)` ?

**Comment by krystian3w** [comment]
Works on my link, but now I have frozen page into iframe at `cda-hd.cc` - preload buffering was bugged.

`hqq.to` demo found on Google?
