### ISSUE TITLE
bank-zone.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10032]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bank-zone.com`

### Describe the issue

Ad on top left.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/133896184-4f8c5cd3-74e7-41c0-b153-d313f4924c71.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`bank-zone.com##.stream-item-top`

**Comment by uBlock-user** [comment]
Report to https://github.com/easylist/listear/issues
