### ISSUE TITLE
[NSFW] ihpc.info

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10036]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `ihpc.info`

### Describe the issue

Ads

### uBlock Origin version

1.37.3rc3

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

### Notes

![1](https://user-images.githubusercontent.com/75935068/133897287-251ef3e6-e869-44a2-8bdf-3d018d3da836.png)

**Comment by okiehsch** [comment]
The site is empty on my end.

**Comment by uBlock-user** [comment]
Unblocked ads, report to EasyList.
