### ISSUE TITLE
elamwal.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10031]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.elamwal.com`

### Describe the issue

Several ads (in the form of photos) around the page's top.

### Screenshot(s)
With ads:
![image](https://user-images.githubusercontent.com/52135169/133895722-324dbdc5-8f90-4879-a181-ccfdfdd6f518.png)

Without ads:
![image](https://user-images.githubusercontent.com/52135169/133895794-a0246f98-1066-474f-88e2-ca7adab9a43e.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`||elamwal.com/bnr/`

**Comment by uBlock-user** [comment]
Report to https://github.com/easylist/listear/issues
