### ISSUE TITLE
alnaharegypt.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10030]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`alnaharegypt.com`

### Describe the issue

Ads on sides.

### Screenshot(s)
With ads:
![image](https://user-images.githubusercontent.com/52135169/133895604-abe5f35f-587f-4777-8c36-3c226aee2ebf.png)

Without ads:
![image](https://user-images.githubusercontent.com/52135169/133895836-9d12af45-6c9a-4438-be42-e8e46119107b.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`||alnaharegypt.com/bnr/`

**Comment by uBlock-user** [comment]
Report to https://github.com/easylist/listear/issues
