### ISSUE TITLE
[NSFW] indiansexwhores.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10035]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `http://www.indiansexwhores.com/`

### Describe the issue

Ads

### uBlock Origin version

1.37.3rc3

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

### Notes

![1](https://user-images.githubusercontent.com/75935068/133897126-2e96125d-16e7-476d-b60e-ee527d2510da.png)

**Comment by okiehsch** [comment]
Declined. Porn farm imo.

**Comment by uBlock-user** [comment]
We could still fix the ExoLoader ads, or do we ignore it ?

**Comment by okiehsch** [comment]
If you agree that it is a porn farm, we ignore it.

**Comment by uBlock-user** [comment]
Yeah it's a porn farm, only some videos are hosted on the site.

For ExoLoader crap, OP can use - `indiansexwhores.com##+js(acis, document.write)`
