### ISSUE TITLE
[NSFW] onlylesbiantube.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10044]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `http://onlylesbiantube.com/`

### Describe the issue

Ads.

### uBlock Origin version

1.37.3rc3

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

### Notes

![1](https://user-images.githubusercontent.com/75935068/133987313-810da45f-1ef8-4c49-b4fe-053aedd1d9fa.png)

**Comment by felix-22** [comment]
ADS fixed, but still multiple AD annoying placeholders everywhere, 
can be fixed by this example filter: `onlylesbiantube.com##iframe:upward(.thumb)`, example:

<details not-open>
<summary>screenshoot 1</summary>



![11](https://user-images.githubusercontent.com/75935068/134025457-691ca756-bf73-435a-a702-edb2b3ce5218.png)
</details>

and the bottom ADS placeholders as well, 
can be fixed by this example filter: `onlylesbiantube.com##.hor_bs`, example:


<details not-open>
<summary>screenshoot 2</summary>



![22](https://user-images.githubusercontent.com/75935068/134025879-463410a2-c14b-4922-acb8-daaa65b7e5fb.png)

</details>

**Comment by okiehsch** [comment]
No, I will add your filter suggestions.
