### ISSUE TITLE
blogpascher.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10040]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

French - maybe origin:

`https://blogpascher.com/tutoriel-wordpress/comment-surveiller-lactivite-de-votre-blog-wordpress`
`https://blogpascher.com/wordpress-2/comment-creer-un-blog-wordpress-en-30-minutes`

English version (machine translation?):

`https://en.blogpascher.com/tutoriel-wordpress/comment-surveiller-lactivite-de-votre-blog-wordpress`
`https://en.blogpascher.com/wordpress-2/comment-creer-un-blog-wordpress-en-30-minutes`

regional Polish (machine translation?):

`https://pl.blogpascher.com/wordpress-tutorial/jak-aktywno%C5%9B%C4%87-monitora-your-blog-wordpress`
Second link have error with loading on network level (maybe translation no accepted by human moderator)

### Describe the issue

Annoyance redirect to:

`https://www.elegantthemes.com/gallery/divi/`
or
```
https://themeforest.net/popular_item/by_category?category=wordpress&irgwc=1&clickid=yo0yESxvRxyIT5ZTiRyvgWxDUkBQfIWn4RQu0g0&iradid=275988&irpid=470642&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1
```

after few minutes - IMO no need click anywhere

---

pop-up with locking scroll, visible few second before page can generate redirections

### Screenshot(s)

Pop-up:

![obraz](https://user-images.githubusercontent.com/35370833/133942374-f54b22fe-5023-44f7-83b5-f8d3380e699e.png)

fyi @smed79

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Settings

- enabled uBo Annoyances

### Notes

May need copy smed79 filters, because page have translations into many other languages - in footer possible found widget to change languages.

**Comment by krystian3w** [comment]
For pop-up maybe works:

`blogpascher.com##html.om-position-popup body:style(overflow: hidden !important;)`
`blogpascher.com##.CampaignType--fullscreen.Campaign.trenton-campaign`

no tested how works after fake login in this wordpress.

**Comment by smed79** [comment]
@krystian3w Should be fixed in **ABP filters** ([Adblock Plus anti-circumvention filter list](https://github.com/abp-filters/abp-filters-anti-cv)).

@wizmak @manuel-martinez-dev FYI.

**Comment by krystian3w** [comment]
But self promo should be moved into Fanboy list.
