### ISSUE TITLE
Video disabled in cnet.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10046]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cnet.com/videos/inspiration4-mission-wildest-dreams-rerelease/`

### Describe the issue

Video is blocked and cannot load in the site.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/133989160-679197d3-9d50-4f40-a8ce-bf636688ae54.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

No change

### Notes

Whitelisting ima3.js script allows the video to play
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=cnet.com`

**Comment by felix-22** [comment]
A note: with AdGuard Base Filter enabled the issue is fixed, as they added the following exception: `@@||imasdk.googleapis.com^$domain=cnet.com`
