### ISSUE TITLE
Anti-adblock in readytechflip.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10041]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.deadtoonsindia.net/?e045eb9a24=QkxxdXExS2lrT21GZVhZcVhrZ0NIMzZqS05aeU9KT09QdzY0QnQ0a3B3UnRKSTF3VmQzQVlxWVp2N25ndkI3NjVaOEt4QmZMVzZudGNLb1laclIwcUE9PQ==`

### Describe the issue

After going to that link, it's redirected to `readytechflip.com` site, which triggers the anti-adblock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/133984847-a25b33ae-d7f1-40b4-9081-d23d0a9869f9.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

No change.

### Notes

Adding this filter helps bypass the anti-adblock
`readytechflip.com##+js(aeld, DOMContentLoaded, AdBlocker)`

**Comment by huyszn** [comment]
The `readytechflip.com` detects again but the `deadtoonsindia.net` shortener domain is parked.
