### ISSUE TITLE
incorrectly blocking oK programming language

### ISSUE THREAD

**Issue by equaa** [uBlockOrigin/uAssets#10049]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://johnearnest.github.io/ok/index.html`
`https://johnearnest.github.io/ok/oK.js` blocked URL

### Describe the issue

the repl (linked above) and anything else referencing the ok programming language interpreter are blocked.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox ESR 78

### Settings

.

### Notes

appears to be caused by the rule from #9963: https://github.com/uBlockOrigin/uAssets/blob/70c7efcb2e0cebdd501d795bb214c8b6d294424e/filters/filters-2021.txt#L5348

**Comment by uBlock-user** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
Removed as the rule is for porn farm (exo ads scripts).
