### ISSUE TITLE
[NSFW] youpornru.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10052]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.youpornru.com/`

### Describe the issue

Ads. 

(the site has much js code and random classes, so not sure whether it can be fixed in RuADlist)

### uBlock Origin version

1.37.3rc3

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base filter
- RuAdlist

### Notes

![333](https://user-images.githubusercontent.com/75935068/134160158-da8194f8-e0f5-4603-8f5c-0e82b0afd73a.png)

**Comment by felix-22** [comment]
Ads on mainpage fixed, but still ads on video subpages, example: NFSW 
`https://www.youpornru.com/watch/16055434/stepmom-is-stuck-and-stepson-fucked-and-cum-in-mouth/`

**Comment by felix-22** [comment]
.

**Comment by uBlock-user** [comment]
> but still ads on video subpages,

where ??? I don't see any.

**Comment by felix-22** [comment]
Any video subpage, the ads are on the right side of the video:

<details not-open>
<summary>NSFW screenshoot (I've blurred the ads intentionally):</summary>


![xxx](https://user-images.githubusercontent.com/75935068/134178780-5da50c9b-f3f6-472d-b0fc-76350c4b7470.png)

</details>

**Comment by felix-22** [comment]
Any video subpage, the ads are on the right side of the video:

<details not-open>
<summary>NSFW screenshoot (I've blurred the ads intentionally):</summary>


![xxx](https://user-images.githubusercontent.com/75935068/134178780-5da50c9b-f3f6-472d-b0fc-76350c4b7470.png)

</details>

**Comment by felix-22** [comment]
> Besure to test on default settings/lists with all other extensions disabled.

Yeah, I already made sure 10 times, but the ads are still here.

**Comment by felix-22** [comment]
Could you try to update all filter lists? I could swear when for the first time I checked in Opera I had no ads until I updated all filter lists..seems like a paradox, I know, but that's what happened...

**Comment by felix-22** [comment]
Nope, it always was and still is disabled, have ads in Firefox as well anyway.

**Comment by spirillen** [comment]
>>>>>>>>>> See screendump and fix https://github.com/easylist/easylist/pull/9183

**Comment by uBlock-user** [comment]
Does it work if you manually add the filters in my filters ?

**Comment by felix-22** [comment]
Nope, still ads.

**Comment by uBlock-user** [comment]
Reset uBO to default settings and then update any/all the default lists that need updating, should fix any uBO configuration issue/s.

**Comment by felix-22** [comment]
I have just reset on bot Firefox and Opera and still ads are here.

**Comment by mapx-** [comment]
try

```
||youpornru.com^$csp=img-src *
youpornru.com##[id^="new_zone_"]
```

**Comment by Yuki2718** [comment]
> 
> Works on my end.

So you can reproduce? Actually I don't see any ads.

**Comment by okiehsch** [comment]
I can reproduce the ads and the anti adblock annoyance with chromium only.
Both are fixed with your filter on my end.

**Comment by uBlock-user** [comment]
We already have `you-porn.com,youporn.com,youporngay.com##+js(set, page_params.holiday_promo, true)`, so should it as well ?

**Comment by okiehsch** [comment]
Adding the scriptlet is preferable imo.
