### ISSUE TITLE
surfline.com

### ISSUE THREAD

**Issue by SugnaB** [uBlockOrigin/uAssets#10053]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.surfline.com/`

### Describe the issue

Ad block detection, and ads every 15seconds of watching a live stream of any beach. 

### Screenshot(s)

![Capturar](https://user-images.githubusercontent.com/29881038/134279691-97917aca-3409-45cd-8fe0-8e87a84ddfaa.PNG)

### uBlock Origin version

1.37.2

### Browser name and version

Brave V1.29.81

### Settings

N/A.

### Notes

When watching a live stream, every 15 or 30seconds an ad will pop up for 15-30 seconds. This also happens as well as the pop up.

**Comment by okiehsch** [comment]
> When watching a live stream, every 15 or 30seconds an ad will pop up for 15-30 seconds.

The ads are blocked what I see is
![image](https://user-images.githubusercontent.com/16838044/134297274-d96e69c5-6a69-45bf-b4bf-ca2860a6dc07.png)

After the timer runs out the video continues without ads on my end.
