### ISSUE TITLE
detected on these sites:

### ISSUE THREAD

**Issue by Arnozzle** [uBlockOrigin/uAssets#10055]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.fcinternews.it/
https://www.milanworld.net/

```

### Describe the issue

ad blocker detection appears

### uBlock Origin version

1.38

### Browser name and version

chrome Version 94.0.4606.54

### Settings

none

**Comment by uBlock-user** [comment]
can't repro any `https://www.fcinternews.it/` existing filter works as expected.
