### ISSUE TITLE
[NSFW]pornhits.com-videos don't load

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#10064]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pornhits.com/video/112818/kendra-spade-keiran-lee-bush-is-better-19-1-2019/`

### Describe the issue

The video is not loading with default filters enabled.

### uBlock Origin version

1.38

### Browser name and version

Firefox 91.0.2

### Settings

Default settings

**Comment by uBlock-user** [comment]
Broken by `/holly7.$script,1p`

@Yuki2718

**Comment by Yuki2718** [comment]
This is the first time I see FP by these TXXX network scripts. I wonder if this is this site only or affects other sites as well.

**Comment by JobcenterTycoon** [comment]
The Video not working `https://inporn.com/video/102333/selena-love-and-mia-kay/` broken by `/holly7.$script,1p` too
