### ISSUE TITLE
1001tracklists.com adblock warning message and ads

### ISSUE THREAD

**Issue by tommy8372** [uBlockOrigin/uAssets#10074]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://www.1001tracklists.com/dj/oliverheldens/index.html`

### Describe the issue

When you click on any tracklist it shows warning message to disable adblock. Happens like every 30 minutes and first time you visit the page. Sometimes there are ads on top and right hand side at specific tracklist.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/155648/134781527-251f77fb-e018-44da-af7c-9da1f0785ac3.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0.1

### Settings

added filter lists: uBlock, AdGuard, Fanboy filter annoyances; CZE, SVK: EasyList

### Notes

The site seems to be active against blocking content as the adblock message and ads keep re-appearing after a while when fix is provided.

**Comment by uBlock-user** [comment]
@tommy8372 Do not parse the links.
