### ISSUE TITLE
rtl.be

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1007]
### URL(s) where the issue occurs

`http://www.rtl.be/info/regions/flandre/les-militaires-s-arretent-au-drive-in-d-un-fast-food-apres-le-defile-du-21-juillet-une-commande-assez-particuliere-video--938315.aspx`

### Describe the issue

Anti-adblock / Video doesn't play. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34066443-fccfa542-e1cb-11e7-8f69-530e4c4fd3bd.png)

With this rule: `@@rtl.be/videos/player/vp4_webanalytics.js`

![image](https://user-images.githubusercontent.com/7283682/34066458-203fced0-e1cc-11e7-8a9f-e5a65ed367c8.png)

### Versions

- Browser/version: Firefox 57.0.1
- uBlock Origin version: 1.14.22

### Settings

All defaults. 

### Notes

Related: https://github.com/jspenguin2017/uBlockProtector/issues/421

My old solution which broke: https://github.com/jspenguin2017/uBlockProtector/commit/1b3ca2807ad4a2018c8f4271c3875a4f40c157cb

**Comment by okiehsch** [comment]
I don't think this is an anti-adblock issue, the rule 
`||videoplaza.tv^$third-party,script` is just to broad in my opinion.

````
@@||rtl.be/videos/player/vp4_webanalytics.js$script,first-party
@@||videoplaza.tv/*/pulse-sdk-html5/*$script,domain=rtl.be
````
works on my end and I don't see any pre-roll ads.

**Comment by jspenguin2017** [comment]
Alright, fix as you see fit.

**Comment by okiehsch** [comment]
That sounds like you do not agree? 
A redirection will not work  as far as I can see 
`||videoplaza.tv^$third-party,xmlhttprequest` prevents the pre-roll ads.

**Comment by jspenguin2017** [comment]
No, that's not what I meant, I'm just leaving this to you. 
I want to dissolve most part of Nano Defender in uAssets and Nano Filters so more people can benefit from it.

**Comment by okiehsch** [comment]
OK, understood.
