### ISSUE TITLE
[NSFW] scam/phishing pages (rare marked a malicious)

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10075]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

found by @iam-py-test and YouTube community

 `[NSFW]`

```
https://lady-datings-here.com/?u=m7qpte0&o=ftakh0p&t=S1
https://your-dreams-girls2.com/?u=m7qpte0&o=ftakh0p&t=S1
https://profit-worlds2u.life/?u=m7qpte0&o=ftakh0p&t=S1
https://yourbest-dating33.life/?u=m7qpte0&o=ftakh0p&t=S1
https://bestdatinglocal1.com/?u=m7qpte0&o=ftakh0p&t=S1&x=3
https://sexcontact-store1.com/?u=m7qpte0&o=ftakh0p&t=S1
https://superdatenow3.com/?u=m7qpte0&o=ftakh0p&t=S1
https://findlocalgirlnow.com/?u=m7qpte0&o=ftakh0p&t=S1
https://vip-lady-dreams.com/?u=m7qpte0&o=ftakh0p&t=S1
https://getviplocals1.com/?u=m7qpte0&o=ftakh0p&t=S1
https://global-dates-here.com/?u=m7qpte0&o=ftakh0p&t=S1
https://new-lady-here12.com/?u=m7qpte0&o=ftakh0p&t=S1
https://topgirls-here.com/?u=m7qpte0&o=ftakh0p&t=S1
https://hook-ups-here2.com/?u=m7qpte0&o=ftakh0p&t=S1
https://topgirls-here1.com/?u=m7qpte0&o=ftakh0p&t=S1
```

`[/NSFW]`

### Describe the issue

Scam about S​​​e​​​x​​​B​​​a​​​d​​​o​​​o / resize p​​​e​​​n​​​n​​​i​​​s / fake bitcon pages

maybe similar to Gargul issues: https://github.com/uBlockOrigin/uAssets/issues/10072 (yeah felix are Gargul - multi account).

If no report porn scam here, so I need official comment in this issue too.

### Screenshot(s)

`[NSFW]`

`https://user-images.githubusercontent.com/35370833/134781725-aa44b16d-ccc7-4d9a-be6f-e4cf4a90d92f.png`
`https://user-images.githubusercontent.com/35370833/134781749-886f3dd4-3e85-48ff-8b2a-ad60896dce66.png`

`[/NSFW]`

---

scam about bitcoin:

![obraz](https://user-images.githubusercontent.com/35370833/134781882-7146670b-7a40-420f-a69d-ffbba71e75ba.png)

![obraz](https://user-images.githubusercontent.com/35370833/134781822-343d53b1-505a-48fa-b761-130bafb781dc.png)

opens:
`https://sexcontact-store1.com/web/`
`https://evi-vest.club/u/eb821adc91a54e18ad3a?click_id=a7616a7c-bf13-46b6-af9c-daeeb14dd2f7&aff_id=l84275`
`https://www.the-crypto-genius.net/lp?k=qeaa8&i=3pol&utm=c9fe760c-2cac-463b-bc97-1b6fbdfe6a30&utm2=l84275`

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Settings

N/A

### Notes

Most in screenshot section

**Comment by iam-py-test** [comment]
@krystian3w maybe do mass submission to uAssets, AdGuard, or [BlockListProject](https://github.com/blocklistproject/lists)

**Comment by JobcenterTycoon** [comment]
They changing the domains often. With a reverse IP lookup on `5.101.45.*` i get tons of these porn scam domains

**Comment by iam-py-test** [comment]
> 
> 
> They changing the domains often. With a reverse IP lookup on `5.101.45.*` i get tons of these porn scam domains

If you think the whole IP is bad, maybe someone could write a Python/Sh script to reverse DNS it and print the domains
