### ISSUE TITLE
ff14angler.com

### ISSUE THREAD

**Issue by steponmepls** [uBlockOrigin/uAssets#10076]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://en.ff14angler.com/fish/29`

### Describe the issue

Adblock detection and content dynamically loaded if no adblock is found

### uBlock Origin version

1.38.0

### Browser name and version

Google Chrome 94.0.4606.61 (Official Build) (32-bit)

### Settings

It's a clean Chrome install using default uBlock Origin settings

### Notes

The functions loading the actual content of the page, once the ads iframes are found and loaded, are set in place in the website core making disabling javascript impossible to use as workaround. It appears a preliminary content string is saved within a container and then fed to a php script to load the actual content if no adblock is detected (or at least this is my understanding of how this system works). The string is too long for me to paste it here but it looks like this:
```javascript
<!-- 
var contents = "Ox0OyM8MKDxcgtLK9Uoez8VSphTnOycZ5XZJkL6T0JlC3LJ23opS11zCqFzQ8mZL1GsIjM6DrqB8w9nvrXWvz9Be8ZikJ6RdWbl/sfh5AC+mL93lrnM4V2HJnZi0ixszy.."
```
The main functions are in `https://en.ff14angler.com/angler.min.js` and there are specific functions such as `check_adsense()` or `activate_contents()` inside.

Content is also hidden by default in the HEAD of the document, toggled on demand
```css
#contents,$sidebar {
display: none;
}
```

**Comment by JobcenterTycoon** [comment]
Anti adb is back

**Comment by JobcenterTycoon** [comment]
Anti ad block is back

**Comment by Yuki2718** [comment]
@AdamWr

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by steponmepls** [comment]
Anti adblock is up once again, both on Firefox and Chrome

**Comment by JobcenterTycoon** [comment]
```
ff14angler.com#@#ins.adsbygoogle,iframe[id^="aswift_"]:style(height:1px!important;)
ff14angler.com##ins.adsbygoogle,iframe[id^="aswift_"]:style(opacity:0 !important; pointer-events: none !important)
```

**Comment by steponmepls** [comment]
Anti adblock appears to be up again both on Chrome and Firefox

**Comment by Yuki2718** [comment]
@steponmepls I can't reproduce, test with default settings.

**Comment by steponmepls** [comment]
I just tired resetting default settings on a dummy Chrome install. Also tried enabling Annoyances repos for uBlock and AdGuard and same results for all three cases. The chrome version is `Version 99.0.4844.74 (Official Build) (64-bit)`

**Comment by Yuki2718** [comment]
Also make sure u don't have any other blocker nor blocking on other layer e.g. blocking DNS.

**Comment by steponmepls** [comment]
I just tested on a different machine and the filter works as usual there. I just now remembered I recently added entries to my hosts file and there are probably some google addresses that if blocked altogether will cause the website to not show its content anyway. I removed every entry from the hosts file and now it works again on my own device as well. Sorry for the false alarm

**Comment by steponmepls** [comment]
A new anti-adblock appears to be up

![image](https://user-images.githubusercontent.com/63500907/219766894-d49c8a38-d154-49ad-bc23-571ee0fb8b6c.png)
