### ISSUE TITLE
cookie overlay/popup blocked

### ISSUE THREAD

**Issue by BartHuismanKM** [uBlockOrigin/uAssets#10078]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

gall.nl

### Describe the issue

this popup gets blocked while its needed to get some parts, such as google maps, working : 
![image](https://user-images.githubusercontent.com/53225006/134823683-75585faa-87b4-42e4-8e43-4b4c2c982717.png)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/53225006/134823687-a9f973c3-053c-4af7-9be9-306cc9a712dc.png)

### uBlock Origin version

1.37.2

### Browser name and version

chrome 93.0.4577.82

### Settings

none

**Comment by ExtremelyCool** [comment]
Hi! Do you have any filters / filter lists enabled that are designed to hide and/or block cookie banners?
I took a screenshot of **My filters** in my uBO config on Google Chrome and edited it to indicate were to look.
![my filters - Google Chrome uBO config](https://user-images.githubusercontent.com/90566652/134824490-f8731dc8-8551-46af-aedc-d2ec2891e6a4.png)

**Comment by ExtremelyCool** [comment]
Hi! Do you have any filters / filter lists enabled that are designed to hide and/or block cookie banners?
I took a screenshot of **My filters** in my uBO config on Google Chrome and edited it to indicate were to look if you're willing to.
![my filters - Google Chrome uBO config](https://user-images.githubusercontent.com/90566652/134824490-f8731dc8-8551-46af-aedc-d2ec2891e6a4.png)

**Comment by ExtremelyCool** [comment]
Also, if this is caused by EasyList Cookie or Fanboy's Annoyance you can report it to the EasyList team either:
- In https://github.com/easylist/easylist
- In `https://forums.lanik.us/`
And if the issue is caused by AdGuard Annoyances you can report to the AdGuard team in https://github.com/AdguardTeam/AdguardFilters ; I'm not sure if you can report AdGuard filter issues encountered while using uBO on `https://reports.adguard.com/en/new_issue.html`.

**Comment by ExtremelyCool** [comment]
Also, if this is caused by EasyList Cookie or Fanboy's Annoyance you can report it to the EasyList team either:
- In https://github.com/easylist/easylist
- In `https://forums.lanik.us/`

And if the issue is caused by AdGuard Annoyances you can report to the AdGuard team in https://github.com/AdguardTeam/AdguardFilters ; I'm not sure if you can report AdGuard filter issues encountered while using uBO on `https://reports.adguard.com/en/new_issue.html`.

**Comment by BartHuismanKM** [comment]
@ExtremelyCool  is think mine's is default? 
![image](https://user-images.githubusercontent.com/53225006/134824732-264c5369-543b-42ba-8d52-479db6063422.png)

**Comment by ExtremelyCool** [comment]
@BartHuismanKM Is there any issue on `https://www.gall.nl/` on your side?

**Comment by BartHuismanKM** [comment]
@ExtremelyCool yeah, the cookie popup is not shown, so you have no clue where to accept the cookies whenb you want to show google maps

**Comment by BartHuismanKM** [comment]
@okiehsch why closing?

**Comment by okiehsch** [comment]
I closed it via a commit.
`okiehsch closed this in 345ab74 2 minutes ago`

In a few minutes update the `uBO-unbreak` list, the popup will show up after that.
Alternatively add
`@@||googletagmanager.com/gtm.js$script,domain=gall.nl`
to your filter list.

**Comment by BartHuismanKM** [comment]
@okiehsch  ah ok, sorry, didnt know how this was working. its okay when just put the blocker off, and i also allready left the website in this case. 
The reason i added this issue was not to just solve this for this particular site, but to make ublock not recognising these cookie popups at all sites as ads anymore ;) looking at your line its only solved for this site now?

**Comment by uBlock-user** [comment]
> these cookie popups at all sites as ads anymore

what other sites ?

**Comment by okiehsch** [comment]
The popup should not be dependent on the `googletagmanager.com/gtm.js` being loaded.
It's a site specific issue, so there is no global solution.

**Comment by uBlock-user** [comment]
Site is integrating GDPR with GTM, nothing to do with ads. Blocking GTM is to stop GA and their data collection.

**Comment by BartHuismanKM** [comment]
> > these cookie popups at all sites as ads anymore
> 
> what other sites ?

i dont know based on what rules this popup was determined as add, so i dont know where else this could happen, but a div with clearly stating cookie-overlay and cookie-popup doesn't sound as divs that has to be blocked?

**Comment by BartHuismanKM** [comment]
> Site is integrating GDPR with GTM, nothing to do with ads. Blocking GTM is to stop GA and their data collection.

gtm is allreay blocked as long as you don't agree to the popup. now i wasn't able to make choises in the popup as it wasn't shown?

**Comment by uBlock-user** [comment]
> but a div with clearly stating cookie-overlay and cookie-popup doesn't sound as divs that has to be blocked?

uBO doesn't block cookie popups in default settings, as said before this site specific issue because we block GTM.
