### ISSUE TITLE
[NSFW] hairy-ocean.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10072]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://hairy-ocean.com/`

### Describe the issue

Nasty AD placeholder like described here: https://github.com/easylist/easylist/issues/9193#issuecomment-925587103, can be hidden simply with `hairy-ocean.com##.bannerlisst`, but it has been declined to be fixed In EasyList for no reason / unknown reasons.

### Screenshot(s)

`https://user-images.githubusercontent.com/75935068/134473010-2037ab62-5f91-4e19-b47f-7218f43a2e16.png`

### uBlock Origin version

1.37.3rc3 / 1.38.1b1

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

**Comment by uBlock-user** [comment]
> Sites found to be porn-farms or part of porn-farms will not be addressed in uAssets.

**Comment by felix-22** [comment]
Oops, indeed, I didn't notice that this is a garbage porn site.
