### ISSUE TITLE
[NSFW] b-time.site

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10086]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `https://b-time.site/PwM6n59N?external_id=iyi5pj8jnsy9ipgf5xx0&creative_id=404670&campaign_id=184610&publisher_id=DZC74GM7ON&utm_campaign=mb&utm_source=ht&utm_medium=pl_pop&utm_term=ht_pl_pop_win_sz_4022`

### Describe the issue

A badware site reported already in https://github.com/uBlockOrigin/uAssets/commit/56da93d9c59b2f351f2fc40c3e3a1cd1e8f1e227#commitcomment-57163165, why hidden as off-topic instead of being fixed and added to uBO Badware risks? I'm not responsible for the off-topic of other users, but my comment contained a valid report.

### Screenshot(s)

![](https://user-images.githubusercontent.com/75935068/135046609-d554a5c5-2103-4c0f-839c-9700b736ac1b.png)

### uBlock Origin version

1.37.3rc3

### Browser name and version

FF 92 / O 78

### Settings

- uBO Badware risks

### Notes

https://github.com/uBlockOrigin/uAssets/commit/56da93d9c59b2f351f2fc40c3e3a1cd1e8f1e227#commitcomment-57163165

**Comment by uBlock-user** [comment]
> why hidden as off-topic instead of being fixed and added to uBO Badware risks?

Sounded like a discussion to me, hence closed and locked.
