### ISSUE TITLE
watashiwasugoidesu.com

### ISSUE THREAD

**Issue by Slasar41** [uBlockOrigin/uAssets#10089]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.watashiwasugoidesu.com/fake-saint-of-the-year-ss4a/`

### Describe the issue

Antiadblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/28888646/135176895-3cb7fcc2-3072-4ee6-8f05-f39e8a0c80ca.png)

### uBlock Origin version

1.38.0

### Browser name and version

Microsoft Edge 94.0.992.31

### Settings

Default

**Comment by ExtremelyCool** [comment]
Hi @Slasar41! Does visiting the URL you provided in this issue with:
```
@@||watashiwasugoidesu.com^$ghide
watashiwasugoidesu.com##.watas-adlabel
watashiwasugoidesu.com##.watas-bottom-vi
```
saved in in **My filters** in the settings of uBO create any problems on your side?
