### ISSUE TITLE
bikeradar.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1008]
### URL(s) where the issue occurs

`http://www.bikeradar.com/`

### Describe the issue

Anti-adblock overlay

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34066657-6c73e180-e1cf-11e7-9bc3-fd358b9ec688.png)

### Versions

- Browser/version: ff57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

related: https://github.com/jspenguin2017/uBlockProtector/issues/759

**Comment by okiehsch** [comment]
I can't reproduce the overlay with Chrome or Firefox, but the site uses sourcepoint, so something
like `bikeradar.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)` could work
on your end.

**Comment by jspenguin2017** [comment]
Yea, looks good. I can reliably reproduce it every single time though, could be geo-related.

**Comment by okiehsch** [comment]
If people can reliably reproduce I will add a fix.

**Comment by okiehsch** [comment]
OK, I found the reason I could not reproduce, 
`bikeradar.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)` was actually part of my 
own filter list, I can't remember when I added it 😆
