### ISSUE TITLE
Ads spaces arent removed on myabandonware.com

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#10083]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Ads spaces arent removed. This ISN'T a browser problem since it also happens with firefox.

### A specific URL where the issue occurs

`https://www.myabandonware.com/browse/name/D/page/8/`

### Steps to Reproduce

1 - Go here `https://www.myabandonware.com/browse/name/D/page/8/
`
2 - The ads spaces on right side arent removed even while there are specific entries for this site on easylist.

### Expected behavior

No ads spaces should be seen.

### Actual behavior

Ads spaces are still there.

### uBlock Origin version

1.38.b2

### Browser name and version

Waterfox Classic 2021-8

### Operating System and version

Windows 7

**Comment by Felipefpl** [comment]
Thank you for fixing the issue but the site evaded what you did and now the ads spaces in the right side are back again.

https://www.myabandonware.com/game/legend-of-the-silver-talisman-cf1

**Comment by uBlock-user** [comment]
> but the site evaded what you did and now the ads spaces in the right side are back again.

Works fine, don't see any ad spaces, test on default settings + all other extensions disabled.

**Comment by Felipefpl** [comment]
> Works fine, don't see any ad spaces, test on default settings + all other extensions disabled.

Tried again after i deleted the previous installation and installed 1.38.2, now it works, thanks for checking this. :)
