### ISSUE TITLE
voxfilmeonline.biz cdn issue

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#10084]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voxfilmeonline.biz/antichrist-2009-online-subtitrat/`

### Describe the issue

There is a message on Server 1 after I press the play buttom: "Can't connect to the stats server wss.analyticacdn.com , try to disable Adblock and refresh page". 

### uBlock Origin version

1.38

### Browser name and version

Firefox 91.0.1

### Settings

Default settings

**Comment by mapx-** [comment]
already fixed, update uBlock filters – Unbreak list
