### ISSUE TITLE
Ad block detected on ww1.orientalwrestlingentertainment.com/

### ISSUE THREAD

**Issue by benedek20** [uBlockOrigin/uAssets#10088]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://ww1.orientalwrestlingentertainment.com/`

### Describe the issue

The website says:
Ad block detected
Please disable your ad blocker and reload the page. 

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

-

**Comment by uBlock-user** [comment]
Dead site, parked domain.
