### ISSUE TITLE
[Anti-adblock] https://link1s.com/unfxIbsH (NSFW)

### ISSUE THREAD

**Issue by s0ry0** [uBlockOrigin/uAssets#10085]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://link1s.com/unfxIbsH` (NSFW)

### Describe the issue

There is an anti-adblock on that page that detects uBO.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/32915843/135034656-495e8e6a-74fb-47f7-9e5e-9340be3a8e9e.png)

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome Version 93.0.4577.82 (Official Build) (64-bit)

### Settings

I have not made any changes to uBO's default settings.

**Comment by s0ry0** [comment]
Could you add `pennbookcenter.com` to the filter list also because `https://link1s.com/unfxIbsH` also redirects to `pennbookcenter.com`? The anti-adblock still appears on my browser even though I have reset it and updated the filter list. Have you tested it by going to the link?

**Comment by mapx-** [comment]
pennbookcenter it's already fixed in our lists, click "purge all caches" then click "update now"

**Comment by stephenhawk8054** [comment]
I think the site `link1s.net` has new domains now: `dreamcheeky.com,fidlarmusic.com,rezence.com` that have not got boosted timer yet. You might need to refresh multiple times, it redirects to each (old and new) domain randomly.

URL:
`https://link1s.net/1lbLR`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/150462567-2902ea38-2358-4f82-b280-e5fe45f3042a.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79450
  cosmetic: 41916
  scriptlet: 19206
  html: 625
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4360-4, 38m
  default: 
    ublock-filters: 30787-31, 38m
    ublock-badware: 3743-1, 38m
    ublock-privacy: 191-0, 38m
    ublock-abuse: 76-0, 38m
    ublock-unbreak: 1698-0, 38m
    easylist: 63179-591, 38m
    easyprivacy: 26642-480, 38m
    urlhaus-1: 8099-0, 38m
    plowe-0: 3682-2, 38m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 184 ms (selfie)
popupPanel: 
  blocked: 13
```
</details>

Proposed filter:

`dreamcheeky.com,fidlarmusic.com,rezence.com##+js(nano-sib, counter, 2000)`
