### ISSUE TITLE
mic.com

### ISSUE THREAD

**Issue by ExtremelyCool** [uBlockOrigin/uAssets#10081]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.mic.com/p/is-recycling-worth-it-67097705`

### Describe the issue

different color of the highlighting of selected items

### uBlock Origin version

1.38.0

### Browser name and version

Google Chrome 94.0.4606.61 (Official Build) (64-bit)

### Settings

.

**Comment by mapx-** [comment]
provide steps to reproduce

**Comment by uBlock-user** [comment]
`mic.com##*::selection:style(background-color:#338FFF!important)` ?
