### ISSUE TITLE
freereceivesms.com

### ISSUE THREAD

**Issue by KarmaMod** [uBlockOrigin/uAssets#10091]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.freereceivesms.com/en/cn/`

### Describe the issue

Adblock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/88159598/135241382-ade4be9f-f5ce-42b8-b0b7-599c91a934d2.png)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 94.0.4606.61

### Settings

No changes

**Comment by krystian3w** [comment]
update #10091 fix #11804
