### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#10099]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.google.com/search?q=amazon`

### Describe the issue

When searching for `amazon` on Firefox for Android (Fenix) on Google, there are search result advertisements.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox for Android (Fenix) 92.1.1

### Settings

- Default

### Notes

I found out the filter at https://github.com/uBlockOrigin/uAssets/blob/aeb5e789a4fdf8155599874706835279f12258a2/filters/filters.txt#L99-L101 does not work when in a mobile device (`!env_mobile`). Why is this the case?

**Comment by uBlock-user** [comment]
> Why is this the case?

Because `!env_mobile` addition of  `!` stands for negation.

**Comment by YoshiTabletopGamer** [comment]
I know `!env_mobile` does not include mobile. This filter `google.*##a[href*="/aclk?"][data-al]:upward(2)` would block the search result ads on Firefox for Android (Fenix) if the pre-parsing directive weren't there.

**Comment by YoshiTabletopGamer** [comment]
Thank you @uBlock-user, I have updated my uBO filter lists and it's working 👍

**Comment by Yuki2718** [comment]
Sorry, I actually meant `!#if env_mobile `, was mistake.
