### ISSUE TITLE
add an exception on xunta.es/dog and xunta.gal/dog

### ISSUE THREAD

**Issue by mgacc0** [uBlockOrigin/uAssets#10093]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.xunta.gal/dog/Publicados/2001/20010625/Anuncio899A_es.html`

### Describe the issue

The URL `https://www.xunta.gal/dog` and `https://www.xunta.gal/dog` correspond to the government gazette of the region of Galicia (in Spain).
They are wrongly affected by the rule:
###anuncio

In Spanish "anuncio" means ad, but also means announcement. And the content of this web is official announcements by the regional government.

An analogous issue has been reported a year ago to EasyList Spanish and they added an exception:
https://forums.lanik.us/viewtopic.php?f=103&t=45457&sid=33d6511312c404fccf9b8298de59bd01

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7735126/135333208-cf067501-bcc1-4848-b3d9-8d6a258f82d8.png)
![image](https://user-images.githubusercontent.com/7735126/135333323-47fab030-e761-4bde-bb56-5f564daffb3c.png)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 93

### Settings

No changes.

**Comment by uBlock-user** [comment]
`xunta.es` is completely 404, so `xunta.gal` fixed.
