### ISSUE TITLE
uploaduj.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1009]
### URL(s) where the issue occurs

`https://uploaduj.net/download/izabela-trojanowska-wszystko-czego-dzis-chce-www-djoles-pl-mp3-mp3-2017/`

### Describe the issue

Anti-adblock, this is definitely way more complicated than just hidding that notice. 

Adguard's commits: 
https://github.com/AdguardTeam/AdguardFilters/commit/b06a77e06a6287c87799ed1e34a0f6b120da0e39
https://github.com/AdguardTeam/AdguardFilters/commit/ed0298520eead1c55295fdaec3957f11e5d4c266

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34067098-9ec33294-e1d9-11e7-9de0-6fb2b4d7aea1.png)

### Versions

- Browser/version: ff 57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

Adguard whitelisted like 5 ads servers, it's probably pretty advanced anti-adblock, maybe add to Unbreak? 

Related: https://github.com/jspenguin2017/uBlockProtector/issues/729
Adguard: https://github.com/AdguardTeam/AdguardFilters/issues/8106

**Comment by okiehsch** [comment]
Well, it does not work even if I disable uBO, I still get the message `Nie znaleziono pliku!`
which apparently means file not found.

**Comment by jspenguin2017** [comment]
Yea, it does that for me too... But how come Adguard reached to a solution...

**Comment by okiehsch** [comment]
OK, I can not play the song with  uBO disables but I can click the Download button, which I can't with
uBO enabled.
`uploaduj.net##script:inject(setTimeout-defuser.js, _this.blockAlert, 3000)` removes the adblock alert, but it reappears and still blocks the download.

**Comment by jspenguin2017** [comment]
I have noted down a suspicious script a couple weeks back: https://github.com/jspenguin2017/uBlockProtector/issues/729#issuecomment-348503860
It seems to be reading some token from ads servers. That might be why Adguard whitelisted all those domains.

**Comment by jspenguin2017** [comment]
This part, it's reading some key from somewhere and submitting a form. 
```js
            $dPoint.on('click', function(e) {
                e.preventDefault();
                var hashV = $dForm.find('#download_hash').val();

                if (hashV.length >= 20) {
                    $dForm.submit();
                } else {
                    _this.blockAlert();
                }
            });
```

**Comment by okiehsch** [comment]
Yeah, I actually tried `uploaduj.net##script:inject(abort-on-property-read.js, Unet.DPoint)`, but that makes the download button unresponsive.

**Comment by jspenguin2017** [comment]
Alright, I guess I have to trace it deeper. 

I have another pretty big "quest" for you, there is this URL shortening system that **always** serve a bait script from `first-party.com/js/ads.js`, there are like 60 of them: 
https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFilters/NanoBase.txt#L7
A lot of test links are here: https://github.com/jspenguin2017/uBlockProtector/issues/183 others are scattered around in Nano Defender and AAK repo. 
I don't know if you want to just trust me on this or you want to actually reproduce yourself. 

The solution in Nano Filters does not work on uBO as it uses Nano's extended resources.

**Comment by okiehsch** [comment]
OK, forget what I said above about being able to download the file, I actually am in a loop,
after clicking download i get a download starts in a few seconds message, but nothing happens and the same is true if I try adguards exception filters.

**Comment by okiehsch** [comment]
Regarding your "quest", if I am not mistaken
`example.com##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)`
works for all of them.

**Comment by jspenguin2017** [comment]
OK, then maybe test 10 of them from 183 and paste the domains?

**Comment by okiehsch** [comment]
A few off them are already part of uBO-filters, `urle.co` for eample so just copy/paste will not work and I really try to reproduce before I add a filter, nothing to do about trust, I would say the same to gorhill.

`https://publicwww.com/websites/%22%3C%21%5BCDATA%5B+%2A%2F+var+app_vars%22/` all of these sites have the same issue and the same fix, so there is no need for me to test them manually.

**Comment by okiehsch** [comment]
I will add them in the course of the weekend, time permitting.

**Comment by okiehsch** [comment]
> Good job on recently progress in uAssets, a pretty big spike in activity in the past few days, well done.

Thanks to mapx- in large part.

**Comment by jspenguin2017** [comment]
Eh, wow, OK. 3000 results... that'll be painful... 

It also has a 5 seconds timer which displeases me, I have a scriptlet in Nano to deal with it, gimme a quick ping when you commit, I'll synchronize the timer bypassing filter.

**Comment by mapx-** [comment]
classic filters 
```
@@||goldbachpoland.bbelements.com*$script,domain=uploaduj.net
uploaduj.net##.gba-ad-respo
@@||googletagmanager.com/gtm.js$script,domain=uploaduj.net
```

**Comment by okiehsch** [comment]
Can you download a file with these filters? I still only get the "Download will start within a few seconds"
message.

**Comment by mapx-** [comment]
sure, mp3 download (tested above link)

**Comment by okiehsch** [comment]
Well, I can't download and the player won't work either.

**Comment by mapx-** [comment]
it works in FF / chrome for me .. did you remove the `setTimeout-defuser.js` filter ?

**Comment by okiehsch** [comment]
Yes, it does not work with uBO disabled on my end, I get the download message and after a few seconds
the page just reloads and I can click the download button again.
Chrome and Firefox, same issue.

**Comment by okiehsch** [comment]
Your fix is similar to the one adguard uses, so probably somthing with my setup just does not work with that site, you can add your filters, I don't see a workable solution with extended filter syntax right now.

**Comment by mapx-** [comment]
What if you try using some vpn / tunneling to reach that site ?

**Comment by jspenguin2017** [comment]
Shouldn't it be `^` instead of `*`?

**Comment by jspenguin2017** [comment]
@okiehsch I guess the first 3 pages would be good enough, for the rest probably no one will ever go there. 
If we are to scan all 3000, we got to have a bot to do that overnight.

**Comment by okiehsch** [comment]
@jspenguin2017 I tested some random domains from your list and 
`example.com##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)` does indeed work for all of them, but some changed their names or simply do not exist anymore, so I will have to check **all** of them.
This will take longer than I expected and I do not know when I will commit, hopefully tomorrow, just a heads up.

`link-cash.com` now uses `linkkch.com`,  `ecut.io` now redirects to `curs.io`, `cut-egy.ml` does not
exist anymore, etc.

**Comment by okiehsch** [comment]
OK, I tested your list 
````
123link.io,3rabshort.com,adbilty.me,adbull.me,adlinkme.com,admove.co,adshort.co,adshort.im,adshorte.com,adsurl.xyz,arpa7com.com,bit-url.com,clik.pw,coin.mg,coinb.ink,coinlink.us,curs.io,cut-earn.com,cut-egy.ml,cut-urls.com,cut-win.com,cutearn.com,cuturlink.com,cutwi.in,cutwin.com,ecut.io,egy-links.com,igram.im,infinityurl.co,l2s.io,link-cash.com,linkkawy.com,linksh.top,lkcash.net,meulink.tk,onlinebee.in,ourl.io,psl.io,qe.pe,shorteurl.com,shortzero.com,teqani-plus.com,tmearn.com,tui.click,url.gem-flash.com,urle.co,veneapp.com,xess.pro,linkatk.net,gram.im,eg4link.com##script:inject(nano-make-bait-element.js, #test-block)
````

The result

````
123link.co,adbull.me,adshorte.com,bit-url.com,coin.mg,coinb.ink,curs.io,cut-win.com,cutearn.com,cuturlink.com,cutwi.in,cutwin.com,eg4link.com,egy-links.com,infinityurl.co,linkatk.net,linkkawy.com,linkkch.com,lyon.kim,meulink.tk,ourl.io,psl.io,shortzero.com,teqani-plus.com,url.gem-flash.com,veneapp.com##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)
123link.co##script:inject(abort-on-property-read.js, jQuery.adblock)
cuturlink.com##script:inject(abort-on-property-write.js, Fingerprint2)
meulink.tk##script:inject(bab-defuser.js)
````

**Comment by jspenguin2017** [comment]
OK, (just so I don't need to write a script to process it), did you add any new domain?

**Comment by jspenguin2017** [comment]
There are a couple renames hey? Well, I guess I have to write a script after all...

**Comment by okiehsch** [comment]
I only used renames, no domain that wasn't "originally" on your list.

**Comment by jspenguin2017** [comment]
OK, for Nano, I removed the solution then union-ed the 3 gigantic array of domains...

**Comment by jspenguin2017** [comment]
Well done on scanning over those domains, it must been lots of work. 👍

**Comment by okiehsch** [comment]
Thanks, it was :wink: .
The `cuturlink.com` issue was something I have never seen with `Admaven`, so it was educational.
