### ISSUE TITLE
tugaflix.com needs defusing

### ISSUE THREAD

**Issue by SW1FT** [uBlockOrigin/uAssets#101]
### URL(s) where the issue occurs

http://tugaflix.net/Episodio?E=5499022 (happens on any episode or film I try to watch, this is just an example)

### Describe the issue

You probably need to make an account, but after that when you try to watch an episode you're presented with a "turn off adblock" warning.

### Screenshot(s)

![tugaflix](https://cloud.githubusercontent.com/assets/6627739/17605676/8c9573be-6013-11e6-999a-776f52d2bd08.PNG)

### Versions

- Browser/version: Firefox Developer Edition 50.0a2
- uBlock Origin version: 1.8.5b2

### Settings

- Any changes to the filter lists I am using have nothing to do with this issue, however if needed I can provide them.

### Notes

The adblock detection method they are using is via http://tugaflix.net/tema/blockadblock.js.
Also, they created a div called videobplayer_XX (XX is a random value) with http://tugaflix.net/tema/player.png and hide the actual video player div called videoplayer_XX (XX is the same random value).

**Comment by gorhill** [comment]
I suggest you use the no-popups switch for that site.

**Comment by SW1FT** [comment]
Thanks for the fix. Also can you add the same filter for tugaflix.com? They have a .net and a .com domain, but it's the same website.

**Comment by SW1FT** [comment]
Something happened and now I can't watch any episode with uBO enabled, only with it disabled. Can you look on it? @gorhill

**Comment by gorhill** [comment]
Hmm I tried it and it worked fine, then I purge all the caches and forced an update and now it no longer work. need to investigate.

**Comment by gorhill** [comment]
Disable cosmetic filtering for now, this seems to work. No time to look further for now, maybe tomorrow.

**Comment by SW1FT** [comment]
Ok, thanks for the quick response.

**Comment by SW1FT** [comment]
@gorhill I think they've updated the blockadblock.js script and uBO is no longer defusing it. Can you look into it again? Thanks.

**Comment by SW1FT** [comment]
@gorhill Sorry to bother again, but the "turn off adblock" overlay is still showing with this new fix.

**Comment by gorhill** [comment]
You are using 1.9.7bx?

**Comment by gorhill** [comment]
There was a regression bug in 1.9.7b1-b2 (the scriptlet wasn't being injected), fixed in 1.9.7b3.
