### ISSUE TITLE
fedex login doesn't work with default ublock on firefox, chromium and edge (with ublock and only ublock)

### ISSUE THREAD

**Issue by G2G2G2G** [uBlockOrigin/uAssets#10103]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.fedex.com/en-us/home.html`

`https://www.fedex.com/en-us/shipping/ship-manager.html`  (click the orange ship now button and it brings you to a different login, same credentials same result) 

### Describe the issue

I have tested this thoroughly on several computers, my entire office stopped working with fedex 2 days ago because of this, the solution was just to turn off ublock entirely on the fedex domain, refresh the page, and login works fine.

When you do try to login it either says wrong password or gets a 403 error (which is very weird) thought it was their server for the first day

### uBlock Origin version

1.38.0

### Browser name and version

edge, firefox, chromium, many versions all same result (mostly updated)

### Settings

none

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a77ca2ce139f3401540fab142f206e6c2bb6be2e

force update ublock filters list.
