### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#10102]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.reddit.com/r/uBlockOrigin/comments/pqmy4w/ublock_origin_138_announcement_thread/`

### Describe the issue

Reddit "promoted" ads aren't being blocked on Firefox for Android (Fenix). 

I was able to reproduce this on Firefox for Windows 92.0.1 on a private window with [Responsive Design Mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) with this Firefox for Android (Fenix) user agent `Mozilla/5.0 (Android 11; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0`.

### Screenshot(s)

![](https://user-images.githubusercontent.com/88633614/135510612-8dc8bced-bba7-4c55-a489-0b7ec7e665ac.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox for Android (Fenix) 92.1.1

### Settings

- Default

**Comment by uBlock-user** [comment]
> I was able to reproduce this on Firefox for Windows 92.0.1 on a private window with Responsive Design Mode with this Firefox for Android (Fenix) user agent Mozilla/5.0 (Android 11; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0.

Don't see that ad, disable `Ignore generic cosmetic filters` on Fenix and try again.

**Comment by YoshiTabletopGamer** [comment]
I had to refresh the webpage a few times on a normal window to get another ad. This is the DOM for the ad (I replaced seemingly random characters with `randomcharacters`)
```
<article class="randomcharacters" id="randomcharacters" style="z-index: 1;">
	<div class="randomcharacters">
		<a href="/user/VisionMarine/" class="randomcharacters">
			<div class="randomcharacters randomcharacters" style="background-image: url(&quot;https://styles.redditmedia.com/randomcharacters/styles/profileIcon_randomcharacters.jpg?width=256&amp;height=256&amp;crop=256:256,smart&amp;s=randomcharacters&quot;);"/>
			<div class="randomcharacters">Promoted</div>
			<div class="randomcharacters">u/VisionMarine<span class="randomcharacters">
					<span class="randomcharacters"/>2d</span>
			</div>
		</a>
		<div class="randomcharacters randomcharacters icon icon-seashells"/>
		<div class="DropdownModalWrapper"/>
	</div>
	<div class="randomcharacters">
		<div class="randomcharacters randomcharacters randomcharacters">
			<a class="PostHeader__post-title-line " href="https://alb.reddit.com/randomcharacters" target="_blank" rel="nofollow noopener sponsored">"No matter how deep is an ocean, a boat always floats at the top." - Listed on Nasdaq stock market | Symbol: $VMAR</a>
			<a href="/user/VisionMarine/comments/pwnx29/no_matter_how_deep_is_an_ocean_a_boat_always/" class="randomcharacters">
				<span class="randomcharacters">Join the conversation</span>
			</a>
		</div>
		<div class="PostContent size-compact">
			<a class="PostContent__image-link " href="https://alb.reddit.com/randomcharacters" target="_blank" rel="nofollow noopener sponsored">
				<div class="">
					<img alt="u/VisionMarine - &quot;No matter how deep is an ocean, a boat always floats at the top.&quot; - Listed on Nasdaq stock market | Symbol: $VMAR" class="PostContent__img" src="https://b.thumbs.redditmedia.com/randomcharacters.jpg"/>
				</a>
			</div>
		</div>
		<div class="adLinkBar randomcharacters ">
			<div class="adLinkBar__captionDomainContainer">
				<div class="adLinkBar__domainContainer">
					<a href="https://alb.reddit.com/randomcharacters" target="_blank" rel="nofollow noopener sponsored">forbes.com</a>
				</div>
			</div>
			<a class="callToAction adLinkBar__callToAction" target="_blank" href="https://alb.reddit.com/randomcharacters" rel="nofollow noopener sponsored">Learn More</a>
		</div>
	</article>
```

**Comment by YoshiTabletopGamer** [comment]
I had already disabled `Ignore generic cosmetic filters`

**Comment by uBlock-user** [comment]
I was able to reproduce, `reddit.com##.adLinkBar:upward(article[style="z-index: 1;"])` works ?

**Comment by YoshiTabletopGamer** [comment]
Yes, it works.

**Comment by uBlock-user** [comment]
For the most of the time, `reddit.com#?#article.Post:-abp-has(a[rel="nofollow noopener sponsored"])` present in EasyList works and the ad gets blocked, but sometimes the css structure seems to be changing and that's when a new filter is needed.

**Comment by YoshiTabletopGamer** [comment]
Thank you, @uBlock-user 👍

**Comment by stephenhawk8054** [comment]
I observed that when I opened a reddit page the first time in Private Window of Firefox Android, the `promoted` post is still there until I refreshed one more time. Not sure what's wrong.

URL: `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/`

<details><summary>Screenshot</summary>

![Capture+_2021-12-08-10-07-24](https://user-images.githubusercontent.com/66517106/145142680-dd8b45e0-7037-4cda-8c0d-a5a56058466e.png)

</details>

<details><summary>Logger - Screenshot</summary>

![Capture+_2021-12-08-10-18-54](https://user-images.githubusercontent.com/66517106/145142802-ddf36099-8492-4a00-81fa-b5ec08f5e913.png)

</details>

<details><summary>Logger output (with refreshed once again)</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +12 | ##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/account/sso/one_tap/?experiment_mweb_sso_login_link=enabled&mobile_ui=on&shreddit=true` |
| +12 | ##+js(no-fetch-if, url:/^https:\/\/www\.reddit\.com$/ method:post) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/account/sso/one_tap/?experiment_mweb_sso_login_link=enabled&mobile_ui=on&shreddit=true` |
| +11 | \|\|alb.reddit.com^ | -- | `www.reddit.com` | 1 | image | `https://alb.reddit.com/i.gif?z=gAAAAABhsCQHgUNsh00r67PID9Wm4aPGdcBDdH1FDeM_nZh4bB4Lq7O4BN54FUVBLmtxlVtpOOmMssWDqubErWhQxdfdZGtQzT9WCulLhlm7NID1FSt7BS_EZAOK7q8M1arFanDoR8s88E9xuAmpNMZqqh4kzXYtXqQ3DKEpQ43T2IO3jYzmMFQXg3E1b-0CZ3_oD5xtAKlY&r=0&g=0&i=1638933510684&t=1638933510684&o=0&q=0&h=0&w=408&sh=884&sw=408` |
| +11 | ##.openx |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +11 | ##.googad |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +11 | ##.adsense-ad |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +11 | no-csp-reports: * true | -- | `www.reddit.com` | 3 | csp_report | `https://reddit.report-uri.com/r/t/csp/reportOnly` |
| +11 | no-csp-reports: * true | -- | `www.reddit.com` | 3 | csp_report | `https://reddit.report-uri.com/r/t/csp/reportOnly` |
| +11 | ##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +11 | ##+js(no-fetch-if, url:/^https:\/\/www\.reddit\.com$/ method:post) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +10 | \|\|alb.reddit.com^ | -- | `www.reddit.com` | 1 | image | `https://alb.reddit.com/i.gif?z=gAAAAABhsCP_8vnoylsL9ar6DDUAsNyoptPxuRP7B4ZpmAny6tzXDD2l3k2dRGxMMrwid5fRwd8L5emWNMZNh-yXUwCOMItdsdIR2xZUyHszAZItIfw7WA3Azn4v0AtpA6L8GLeqVC1buD6Hy-hzWsIaR9M5fBmjtzCci3cTX9lDblQMxLKF9-1BRN8jbiYxuvit0cFZGAMSjaXebv3pt0bVeKeRDqDrzw5UykjzKUQwA2JlvsSN3SCOWiv7sHs2D7UrZ2aEuHnXGPePVShWhMLAHjHl_1oasRkWw6JY_45G-rVlf8AMokLpT4euPsyJiw5OVSu7-e6yWRU9oExRi00TcBaD9aIiJF1jda4ctUCzGNhoD6bg9BnpKjgCglHVsp_5KtAYBadtlpuawGyDK4VVj1PoRWOvi3cN0xmrjdC8uYhFIUcuw_wtH765F72UILpM3_yhej2O9zSNOO7bb390x55Nq9uu41xvdgK22WUsRcRUxgAjNz0QwhFm5bcyrDOVWo918pEUnfvZG9eu4IfxsTxdXhEGnJCM3qAt5pfMOOgCDs_i5KuzZPpk1KznCFhxr4Vx7JAtLq5f36u5RytUtIWqKVmxLm-Z-LtqZJCrO5yifL_ms5OHJEHxT-i8AGc7pWWxrVyuIeWE8sA2ECt1VeoPuy2FSQXQ39jP7PYh3T7sbPfXv_fBOdwm5f0EdQiaafzgu_Dn3xulDbNlR_bUNabflU5GHL5OBuNNv2kWFrFF1BWmks41Uwhb9U3meodd3BhfK6mtHUZY4Ifr5adPWtstUzIwI594hcDTj_3KQ6rmO-zSPSRloHP3Zw9WHrUzQmBeHbAA3HPn9ILKKf6oXsgRxFFgJ0LUoqg-yVF7NRcSeU6StVIrXtGZ7E0gUyebOU92KNKA9sQEJDoCZSbaQnElJNv6yus-eXXv0MK1Da619ou7fXR94jPE2Yt5deLL80ZCNxA-gZi6kzjQXj7cRzSvTcXvXHFEHGIrHM-4vGWK45Hd_GibKstsBCNU03DAcZjb-LOzlYoYNPpDwvgNbiH19RhdOeo3wV_1aEhCBRVQtaBvTjZF_hy23elCqOSyXb7-D0gzN8FKefGG0rxAn7QyyvatstSk1WseW4yEhq1ceFW5CsFZkHFxfFq6Fz2fmddN9Q2-ur_wpT2uV6Pu6r9HmMyZGA%3D%3D&r=3&g=1&i=1638933501959&t=1638933509036&o=1&q=1&h=194&w=408&sh=884&sw=408&va=1&vb=0&vc=0&vd=0&ve=0&vg=1&vh=0&vj=0&vi=0&vo=0&vs=0&vt=0&vu=0&vv=0&vx=0&vw=0&vq=0&vr=0&vy=0&vz=0&xa=0&xb=0` |
| +4 | \|\|alb.reddit.com^ | -- | `www.reddit.com` | 1 | image | `https://alb.reddit.com/i.gif?z=gAAAAABhsCP_ktRMpjjmj8zEkhZwEqvVCFRPylm1sIaMUKKBV8UIoPbX-Gd-0fe8gXl8fEYSz5_pAGqoCORs-r7bCm72wELou0oTUmp1WHpLVEfgeuu7EaTqgzB8TCKUrkuZShpxxJqCX_FwYHI52DU-xh0e0U0z4xazz0cLe2-CvC5YttlLc4-L3FzQZMBjdvmFhvt3aP4mtev78BPGaMeTMpQHAdVARlCS9q6tNRb5-F9pMzAG6FE35SOlCP4bN0q2lg3wTNwD5NghpcVm9xKr6wW8pnZBB5lG2hH8Cj_0YSKd1mfAUldZt73-x-7Pa74i08-_fmaH1lrSA3eScEWtoxsgIG3_X-zeYCB12RULK9u4jau0xw4v3MzpQ5ETNDUd4Rv4yjhAqp98KTlIrahEGtWbDso4nWG3zD0T1keobcXRLoRME1SJXhaiVjjrefwM6L6L56yt5j_9imFrLvQeDyT8NNFCjqerTLRROdzvI53dx81ruuwIGy6j85pp0CUJ28KzM76NnnHzS_W1W-tQs7FNWHBRyPqASDm8WcXsVwl2a5veXz0F272dn6XAzSfSeJsCp8dAuJBJ2YtXlXwl3s0LoyepdfkrHsHAnb1zSb-kvVvLJ0599lc-6rK4ppcIzpMVFwrzo9noOIS8noIpC1I2hiM3yZafD5crsLDb_06v4z4n5iQ4ffTDclS-bTgCaxbJRDbKQVNX91KUR7OWZ7hZ2kEhoc3Jck0Ex80Mrxoopf1Cs-mKMB3tcR1ggtcddwp1_xPOFFKPzPslpPfDTcA1btQA4ztnsjIn_uiDzfDnPy4jQgtvl-OFFMZLDiFmGYyF8vrASjKuR-jMqkPTEk2PKFePFhYOweZDLBVmTf4s0MZpal58Ed66UwZ3I8h3F0eX7c-vGXxAr8yKU5ca2R033s8LRLuI0BYYXEjlFQLLMytwQ8-LW8X6uHNBU1ixPhXjPzQPmaNGgjFIzZhwj1evwgPwZq4oSBqyydur8gIBw6nl7td-mwzFJ3PQPI4WoNLIbpYkcwug294ObJIRYOgriTZYMOv1ACF30NALii-mtNCTEkTskFyvBBHkUTJd1SC9u215Swfob2rEaH4biwvt452i-SB81QBZovEZJnygSpy79QX0C-osH3_d1pn800Gj35NLwnjWeWPIhq-2qBcD6LUvhg%3D%3D&r=2&g=1&i=1638933501959&t=1638933502988&o=1&q=1&h=194&w=408&sh=884&sw=408&va=1&vb=0&vc=0&vd=0&ve=0&vg=1&vh=0&vj=0&vi=0&vo=0&vs=0&vt=0&vu=0&vv=0&vx=0&vw=0&vq=0&vr=0&vy=0&vz=0&xa=0&xb=0` |
| +4 | \|\|alb.reddit.com^ | -- | `www.reddit.com` | 1 | image | `https://alb.reddit.com/i.gif?z=gAAAAABhsCP_Wk2GIgM6I3-ezzCZ3KUMW3aK8u53_4VEIpYhVCyEorYYWQGET_AS74Sh0zRzOWDA6TwttrKx4VBX9b8WpH3hRlNK05IAwfWJBVNsFmjP4uB0_4XFIDawKxleaSH74RrlEA9lArj5DyFsTv29LUAyF98BnzIq4Tqv6ExJdX-q7iShe9DFQPqzKVhcbWOsCXj8BMlxOJfZGwL_dXKHxuKCgU2bkRTeQwitHFubQibDHchpGS79GW3Uc33Qg--vIyRMldvXPg_dXoEByGrBsoq1Dk5sBIGRTwc0M_W3Eo5whQjok6fb9XyW9BzxH7dGjvCXqUkjY0CWQjR3ZMWgfPOEXHMn46Gj33ihMCgR49V6ZCIraTYNAMEu2qYXg050J9xikINncpyiSsVGqpTH1Ou2a2Q_LJFkgbnJAbgzuGmamZZNr_OU45wEdLKGzGtIVgG-j59CfpS3cEaMYdNM-bIgT6y9F25yURhDCspojVj7TVD1yQmEFr5BgnzdK8EUS3j6lQciyXf_dc3zc9SjDjasv_U64Ks5_tFBp5FzD9_iylEnkh7LpzdYpy0FxJbh10b-LmM5D7hIsAKHoyYioy7QVY-i2ZZ_6CWfvKhSNGeJ57RZ0CjZFGmr0zz54ucV6-1JmvDN2zrTcfZ-Unof5TzwClrK49VIHwfRIK4l3zMwD7Fh-Nnqd9xzeBptEl2eng10HJh5wjnDJbqV7wBnzJhyA_d18ffBqJkvT2u2fkLbIHZwvVgsqQQwdkgtOjxvDBNJ8711OkRUwkcP2X6mC5JyMMA7YC4SAVN1zbFyO1CHQbcjcYG_9DENfDXIYQcY-NqMmBg4ThbuHNT5Y-9aIeXsnKLX8sEDRngmGvaiQBcfIJUqT9e-tHma9Ks4Si81FOZxas3ZxJAcEELmbz3c4gfv9b0iawr3yXgE8OJHKeY-ETA8BVdvy6KQPf_laXRlFKoCe6Oep6F8Gn7sWxSXlaqhwUCPlgjkfiQPX1TQGy5NlIztlzK-4TadoYhQBA3s-oxxewFITj12Y1esyFyh8hvNXDpMJYUTubGH_9yqwOioCamAQUpt3SUaYWcYPaKQr91KTmQmR24dC7HBr_iIIpbQrbOOfo3EQDQ1SyfLexeWbjvjwfD36nXsNQ80H-jydhebNuylwZ5XAlYxH2J5MN-zfQ%3D%3D&r=1&g=0&i=1638933501959&t=1638933502964&o=0&q=0&h=194&w=408&sh=884&sw=408&va=1&vb=0&vc=0&vd=0&ve=0&vg=1&vh=0&vj=0&vi=0&vo=0&vs=0&vt=0&vu=0&vv=0&vx=0&vw=0&vq=0&vr=0&vy=0&vz=0&xa=0&xb=0` |
| +3 | \|\|alb.reddit.com^ | -- | `www.reddit.com` | 1 | image | `https://alb.reddit.com/i.gif?z=gAAAAABhsCP_WDEPpH21cpnDbNwBlC__BGKjl02AEEstYzEQABVrorR7mKdC__9BUa9BTJqb0Oss0H0wD7TCaiy7WKjgXSpIzTArOjeivnzc59H3HEa_ACPtB0RuDutPNbqu50QRXCUQA8nrMV20DFGRBJsl4tZwETfGShuJcJpa5QSU6rEyHFHFa3Et3F64khspH5o7LU0DbOPzyIMmyf06O96JHHBsfbIrJt8zGFa2fmQ69ER087NEB7vWqhjyCMWQsRQ8FlXmgyDdp2DXV1aL6xn2OSZxAu3YGEg13KZfNWPNPkEF_6-vqBZXBLKGSWFNeGEGQNASeG3QtfB_O5NP8Z-ALPZAmuwKAz4YeS1cgBOMNrTQFFkH13A7ExbJAenoiJeBJFwzEDLjpw5O_vG2PkPOsLPtN6aev-oXfrM9r-1tLkhRdOQGMdwo08zipSQUZYQCXx89SrgBRlbjtkdv5LwUOlGSsBLdSjv8L3T4sTjjEi83PKeha93VSVsqTuhL5o14R1hNMOcakI6LJpUM95QkhGk4P8Uh1WhX3aNzFoSgU-FMqkpBHellB68UN-OrcnRASvX2zUG_De6AINjm9lSa-uEATNxDhTONDxE7AnOIiciu4JnWXrl0ZCIBRs7t2PJgFaqLoT4Kt4dM93iV2nXGjmC5hrzbNckSPAiqteV4kuqyAq2P36hfZMxtEOADQxPM1ytB__tLJxcgTWNOWMde5BcGe9Y1lGQYNTOhHDMvZz1eM2HPLG3XG_YiNUohAW5FV3EpM1EXLnP_2gg2SNemmCGIDHhROoBnB88FYh25Zl2cgoQVPBzGeCq01YTDjR8saey2Ojsvp6MyY915Wc1J3RLRyW-AM9af91hOncWYfUCPmvXpMruyMsfXZpwytB7bzqWrw-xrcIxx0hFxq8Yxta8fK-5uW0Dq8lDAvmh0rBK-j7Xiu4JQNbv5t1XkVKqTesrli175uBnXV-e8uJP2rHvPfD0CtQ6hlXEQ1SI_VSN2gjG1a4z-kDJnnpRflhlCS-lVd0RQ-VWF4dqS6VzM3U1UJUL1ia0VLFgHtKA0XODuu37ttvRjTTc_7JLnaL3u1UfL3gUW75QLLVlGnezkqXI4D_YANzgiKMEP-_yYLNcNFW_f7e_ntMCfNhne77zQCRv3oqVq_LxwC_vDyjuqL9qw0Q%3D%3D&r=0&g=0&i=1638933501959&t=1638933501959&o=0&q=0&h=194&w=408&sh=884&sw=408&va=1&vb=0&vc=0&vd=0&ve=0&vg=0&vh=0&vj=0&vi=0&vo=0&vs=0&vt=0&vu=0&vv=0&vx=0&vw=0&vq=0&vr=0&vy=0&vz=0&xa=0&xb=0` |
| +3 | ##.openx |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +3 | ##.googad |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +3 | ##.adsense-ad |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +2 | no-csp-reports: * true | -- | `www.reddit.com` | 3 | csp_report | `https://reddit.report-uri.com/r/t/csp/reportOnly` |
| +2 | no-csp-reports: * true | -- | `www.reddit.com` | 3 | csp_report | `https://reddit.report-uri.com/r/t/csp/reportOnly` |
| +2 | ##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
| +2 | ##+js(no-fetch-if, url:/^https:\/\/www\.reddit\.com$/ method:post) |  | `www.reddit.com` |  | dom | `https://www.reddit.com/r/uBlockOrigin/comments/nura67/ubo_on_ios_soon/` |
</details>

Video: `https://streamable.com/zmubmw`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.39.2
Firefox Mobile: 94
filterset (summary): 
  network: 80109
  cosmetic: 44748
  scriptlet: 16301
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30538-42, 12m
    ublock-badware: 3543-1, 12m
    ublock-privacy: 184-0, 12m
    ublock-abuse: 72-0, 12m
    ublock-unbreak: 1722-0, 12m
    adguard-mobile: 7035-156, 12m
    easylist: 61351-675, 12m
    easyprivacy: 26467-483, 12m
    urlhaus-1: 8656-0, 12m
    plowe-0: 3698-3, 12m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 894
  launchFromSelfie: false
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
test
`reddit.com##shreddit-comments-page-ad`

@Yuki2718  for `AdGuard Mobile Ads` ?

**Comment by stephenhawk8054** [comment]
Yup, I confirm it works now. Not sure why it disappears after refreshing without that filter. Looks like it's generated from the script similar to this:
`https://www.redditstatic.com/shreddit/en-US/content-6bfd13c0.js`

In that script there's also a `comments-page-ad-video` id, I think it might be applied to videos somewhere too. Btw, in the `view-source`, I see that at the end there's a section that looks like preparing for an anti-adblock with bait classes in the future.

```html
<div id="adblock-test" class="ad adsense-ad googad gemini-ad openx"></div>
```
