### ISSUE TITLE
1001tracklist.com anti adblock

### ISSUE THREAD

**Issue by Vozf** [uBlockOrigin/uAssets#10111]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.1001tracklists.com/

### Describe the issue

Site hides all the info and show a warning that adblock is incompatible.

### uBlock Origin version

uBlock Origin 1.38.0

### Browser name and version

chrome

### Settings

-

**Comment by uBlock-user** [comment]
fixed yesterday, force update ublock filters list.

**Comment by Vozf** [comment]
Works like charm. Thanks
