### ISSUE TITLE
[NSFW] hentai-tube.me (farm)

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10116]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

- NSFW `https://hentai-tube.me/` 
- or any of it's 400+ subdomains for ex. NSFW  `https://gmb.hentai-tube.me/`

### Describe the issue

Farm of numerous badware fake porn-blogs, consists of 1 main domain + over 400 subdomains, they can be found and encountered in Google search, visiting such blog and clicking any link redirects to badware websites like "Scam about S​​​e​​​x​​​B​​​a​​​d​​​o​​​o" previoulsy mentioned here https://github.com/uBlockOrigin/uAssets/issues/10075, most of the badware sites you landing on, being redirected by such blog, is already blocked in uBO Badware Risks by regex solutions, but still some times it can redirect you to some badware site that isn't blocked in uBO Badware Risks., so it's worth to block it, especially given a fact the solution is simply: `||hentai-tube.me^$doc` will block all the scum including over 400+ subdomains.

### uBlock Origin version

1.38.1b2

### Browser name and version

FF 92.0.1 / O 78

### Settings

- n/a

**Comment by felix-22** [comment]
https://github.com/uBlockOrigin/uAssets/issues/10116#issuecomment-938604840

**Comment by Yuki2718** [comment]
Can't access them.

**Comment by Yuki2718** [comment]
IDK where you got that, but looks to be something can be added to EL as generic block as used in iframe too.
@ryanbr @Khrin `http://sexhimmel.com/` for example.
