### ISSUE TITLE
mitele.es

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1012]
### URL(s) where the issue occurs

`http://www.mitele.es/`

### Describe the issue

Redirects to `http://www.mitele.es/estaticos/adBlock`. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34072620-bb61dc8e-e247-11e7-8da1-f36237d47c1b.png)

### Versions

- Browser/version: ff 57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

Related: https://github.com/jspenguin2017/uBlockProtector/issues/682

Fix for https://github.com/uBlockOrigin/uAssets/issues/616 broke.

**Comment by mapx-** [comment]
it seems working
`@@||mdsrwdassets-a.akamaihd.net^$xmlhttprequest,script,other,domain=mitele.es`

**Comment by jspenguin2017** [comment]
Yea, but videos don't play: `http://www.mitele.es/programas-tv/socialite/5a35193e8bd4e57b2a8b4644/player`

**Comment by mapx-** [comment]
- in FF broken even disabling uBo 
- in chrome seems working adding also `@@||analytics.edgesuite.net/js/csma.js$script,domain=mitele.es`

**Comment by jspenguin2017** [comment]
For FF might need to disable tracking protection.

**Comment by mapx-** [comment]
Nothing works in FF.

**Comment by jspenguin2017** [comment]
If I disable uBO and FF's tracking protection, it works (but has tons of ads): 
![image](https://user-images.githubusercontent.com/7283682/34073071-35ee8b44-e24f-11e7-8de0-aae57e4a247e.png)

**Comment by mapx-** [comment]
Those 2 filters are working in chrome for you ?

**Comment by mapx-** [comment]
using 
```
@@||analytics.edgesuite.net/js/csma.js$script,domain=mitele.es
@@||mdsrwdassets-a.akamaihd.net^$xmlhttprequest,script,other,domain=mitele.es
@@||mitele.es^$generichide
```

is working fine in the old FF 55

**Comment by okiehsch** [comment]
The video `http://www.mitele.es/programas-tv/socialite/5a35193e8bd4e57b2a8b4644/player` plays with Chrome and Firefox 57 on my end.

**Comment by mapx-** [comment]
using the filters above ? other ?
in FF 58.0b11 (64-bit) does not work (for me), even disabling uBo, disabling tracking protection

**Comment by okiehsch** [comment]
````
@@||analytics.edgesuite.net/js/csma.js$script,domain=mitele.es
@@||mdsrwdassets-a.akamaihd.net^$xmlhttprequest,script,other,domain=mitele.es
````
the `generichide` hide filter is already part of uBlock-filters.

**Comment by jspenguin2017** [comment]
Broke: `http://www.mitele.es/directo/telecinco`
