### ISSUE TITLE
Blank ads space in trueachievements.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10128]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.trueachievements.com/`

### Describe the issue

There's a blank ads space.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135784338-17f32f80-635c-408c-9f36-603669fb89cb.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0.1

### Settings

No change

### Notes

Adding this helps hide the blank space

`trueachievements.com##.nn_player_w`

**Comment by przemo20** [comment]
Hi. It seems like there have been some changes to the website, and once again it shows leftover ad boxes with uBO enabled.

Example webpage: `https://www.trueachievements.com/game/Left-4-Dead-2/achievements`

https://github.com/user-attachments/assets/a9e6224b-c26a-43ed-9c15-b4c2fe92b830
https://github.com/user-attachments/assets/8df4189e-062c-4ddf-8a70-2a0ef8873ff0

Elements with the ad boxes?
- `##.pw_player_w`
- `##div.dyn-lb`


### Troubleshooting information
```
uBlock Origin: 1.68.0
Firefox: 146
filterset (summary):
 network: 161626
 cosmetic: 42051
 scriptlet: 24184
 html: 2750
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 42329-69, now
  ublock-badware: 11026-32, now
  ublock-privacy: 3552-2, now
  ublock-unbreak: 2778-1, now
  ublock-quick-fixes: 411-34, now
  easylist: 84452-149, now
  easyprivacy: 55003-31, now
  urlhaus-1: 29020-6, now
  plowe-0: 3485-987, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 497 ms
 maxAssetCacheWait: 228 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  trueachievements.com: 2
  cloudflareinsights.com: 2
  intergi.com: 1
  intergient.com: 3
 extended:
  ##.lb_holder
  ##.ad-wrap
  ##.ad-wrap:not(#google_ads_iframe_checktag)
  ##+js(set-constant, HTMLScriptElement.prototype.onerror, undefin…
```
