### ISSUE TITLE
baike.baidu.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10123]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://baike.baidu.com/item/%E5%BE%AE%E8%BD%AF/124767`

### Describe the issue

The page will automatically play the video.
It's not the video itself that I hate, it's the act of autoplaying it. Most of the time, I don't watch the video, but the video loads automatically and consumes traffic.

### Screenshot(s)

![2021-10-03_23-12-20](https://user-images.githubusercontent.com/66902050/135760352-2fb644c7-b0cb-4bd3-88bd-0525e0b4da97.gif)

### uBlock Origin version

v1.38.0

### Browser name and version

Microsoft Edge 94.0.992.31 (64-bit)

### Settings

_No need_

**Comment by uBlock-user** [comment]
There's no autoplay blocking functionality in uBO. 

You can try some alternatives.

**Comment by krystian3w** [comment]
@dimisa-ruadlist may helps? He stops many autoplay videos on ru/ua pages.

**Comment by krystian3w** [comment]
Also Edge Chromium have these option out of the box:

`edge://settings/content/mediaAutoplay`
