### ISSUE TITLE
uwatchfree.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10126]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.uwatchfree.pl/2021/10/homegrown-the-counter-terror-dilemma-2016-full-movie/`

### Describe the issue

Ads open in pop-up, also sometimes I see anti-adblock in player.

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/135767971-14f47f83-fac5-4ab9-957c-49be54d38261.png)

### uBlock Origin version

1.38.1b2

### Browser name and version

Firefox 93

### Settings

- enabled uBO annoyances

### Notes

Page no have Polonization yet, maybe only found cheap domain and may no add Polish into inteferace and videos with Polish dubbing/subtitles(captions) in future.

**Comment by spirillen** [comment]
NO this happens on several other spyware sites within the adult category, but only on spooky low value sites

**Comment by krystian3w** [comment]
So ban domain in own projcet - I do not use it (read harder `settings` section).

Also uAssets like repair page 1 by 1 instead run one global filter to repair almost all free VoD.

**Comment by okiehsch** [comment]
@krystian3w I don't see a popup on my end, can you post the logger output of your popup, i.e. what domain triggers it.

**Comment by krystian3w** [comment]
click into player try opens:

`https://thurag.com/prod/redirect.html?lu=https%3A%2F%2Fartisany.net%2Fz%2Fbase.php%3Fc%3D109%26key%3D5eab62c2fdb32ede347e336e367eb303%26zone%3D3246503%26clkid%3D16332899640785122055169446779626875%26ban%3D23321454`
`https://www.spartoo.pl/tanie-buty.php?track_id=adcash`

**Comment by okiehsch** [comment]
The "thurag" request s blocked on my end, are you sure your filter list is up to date?

**Comment by okiehsch** [comment]
`/script/su.js$script,3p`
was added yesterday and blocks it for me.

**Comment by krystian3w** [comment]
Blocked by scriptlet or simple:

`thurag.com$popup,popunder`

?

**Comment by okiehsch** [comment]
See my post above yours.

**Comment by krystian3w** [comment]
But still I see crap bar:

![obraz](https://user-images.githubusercontent.com/35370833/135769081-c7b30f81-d8d2-4c40-8ddc-76211ff8c6f8.png)

**Comment by uBlock-user** [comment]
force update all the default lists.

**Comment by okiehsch** [comment]
Is `wss://wss.analyticacdn.com` blocked if you look at your logger?

**Comment by krystian3w** [comment]
By regional recommend project but MajkIT and Olegwukr is very busy in 2021.

**Comment by krystian3w** [comment]
If regional no fix in 48h maybe needed is add:

`|||wss.analyticacdn.com:^$badfilter` for POL region.

**Comment by okiehsch** [comment]
Sure, let me know if they don't reply in a timely manner.

**Comment by krystian3w** [comment]
Still not fixed by Oleg hands and he repair other page 2 days ago:

https://github.com/olegwukr/polish-privacy-filters/commit/83b4f977b34cece7d7f9e7bf37c77f31086c28ca

Or MajkiIT tests delete all line instead repair in `anti-adblock-suplement.txt`
