### ISSUE TITLE
Sponsored blank space in psycom.net

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10135]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.psycom.net/quiz-results/?qid=4_3`

### Describe the issue

There's a sponsored blank space in the middle of the page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135949728-5cd9bd87-6d79-45ab-bd14-5dbfb5231351.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

This filter helps it

`www.psycom.net##center`

**Comment by uBlock-user** [comment]
Report to EasyList -- https://github.com/easylist/easylist/issues

**Comment by ryanbr** [comment]
Quiz's are self promos
