### ISSUE TITLE
Blank ads spaces in distractify.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10137]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.distractify.com/p/does-lucifer-become-god`

### Describe the issue

There are blank ads spaces left in the page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135951528-18748f51-464c-4544-a60d-37912d6b8cd4.png)

### uBlock Origin version

1.38.0

### Browser name and version

Edge Chromium 94.0.992.38

### Settings

No change

### Notes

This filter helps it

`www.distractify.com##.ad-title:upward(1)`

**Comment by uBlock-user** [comment]
```
distractify.com##.gXgoom.sc-1ugiigr-0
distractify.com##div.jRAIxB.sc-1o6mqs2-0
```

Works fine.

**Comment by uBlock-user** [comment]
@ryanbr
