### ISSUE TITLE
Blank banners in islamicfinder.org

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10136]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.islamicfinder.org/`

### Describe the issue

There are blank ads banner on the right of the page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135950843-3fe565ba-2b76-4927-b757-9bd1061a05da.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

This filter helps it

`islamicfinder.org##.full.columns.medium-4.large-4.pr-hide`

**Comment by uBlock-user** [comment]
`islamicfinder.org##div.pad-xs.box.columns.large-12` works fine, report to EasyList -- https://github.com/easylist/easylist/issues
