### ISSUE TITLE
handelsblatt.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#10133]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.handelsblatt.com`

### Describe the issue

Anti Adblock

### Screenshot(s)

<img width="562" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/135909940-75f0af6d-c4f9-45a6-aac0-15785df7be6e.PNG">

### uBlock Origin version

1.38.2

### Browser name and version

Firefox Developer

### Settings

- Enabled uBlock filters – Annoyances

**Comment by mapx-** [comment]
maybe `handelsblatt.com##+js(no-xhr-if, /^/)`

**Comment by JobcenterTycoon** [comment]
No it breaks login

**Comment by okiehsch** [comment]
For  chromium it's easy,
`*$xhr,redirect-rule=nooptext,domain=handelsblatt.com`
works fine.

**Comment by mapx-** [comment]
try
`handelsblatt.com##+js(no-xhr-if, /simple|controller/)`

**Comment by okiehsch** [comment]
That's much better, the other filter broke some graphics too.
I can't test if the login works though.

**Comment by JobcenterTycoon** [comment]
Im tested and it works

**Comment by mapx-** [comment]
idk if possible for a scriptlet but it would be very useful to have in this case the same behaviour as for `redirect-rule`

**Comment by uBlock-user** [comment]
> if possible for a scriptlet but it would be very useful to have in this case the same behaviour as for redirect-rule

Partially in essense, scriptlet sets resource load status to `200`, while `redirect-rule` loads an empty `xhr`, both avoid `onerror` event to be fired and avoiding the anti-adblock.

**Comment by mapx-** [comment]
> same behaviour as for redirect-rule

meaning `redirect-rule` is acting only for blocked requests

**Comment by uBlock-user** [comment]
> is acting only for blocked requests

Doubt that's possible in JS. You would have to detect and collect all blocked requests somewhere and then apply for them individually.

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back
