### ISSUE TITLE
1001tracklists.com - buttons not working

### ISSUE THREAD

**Issue by BCFFF** [uBlockOrigin/uAssets#10134]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://www.1001tracklists.com/create/tracklist.php#edit`

### Describe the issue

When uBlock filters it is turned on buttons in create / edit tracklist page not working. Can't save, clear, cancel. 

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/32641928/135914138-8cf79455-7f1d-4785-8e40-99d28c6b224d.png)
![obraz](https://user-images.githubusercontent.com/32641928/135914233-c3bae5b1-aa42-4ed7-a298-d12290af4fd3.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Settings

others lists like AdGuard, easylist etc

**Comment by uBlock-user** [comment]
```
1001tracklists.com#@#.in.fade.modal.messagePaneDiv
1001tracklists.com#@##overlay
```

Add those filters and report back.

**Comment by BCFFF** [comment]
@uBlock-user working good with those filters
