### ISSUE TITLE
Sponsored banner on top of freepik.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10139]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.freepik.com/search?dates=any&format=search&page=1&query=cashew+nut&selection=1&sort=popular&type=vector`

### Describe the issue

There's a sponsored banner from Adobe on top of the page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135954518-9ecbbf1c-2700-4454-bc20-46345faa1c61.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

This filter helps

`freepik.com##.spr-plc`

**Comment by uBlock-user** [comment]
> This filter helps

> freepik.com##.spr-plc

Blockable by EasyList, report at https://github.com/easylist/easylist/issues
