### ISSUE TITLE
bet365 ads in aiscore.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10138]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.aiscore.com/`

### Describe the issue

There are bet365 ads banners.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/135953593-be34acad-6e18-4fce-9386-92ef8b6e7a9d.png)

### uBlock Origin version

1.38.2

### Browser name and version

Firefox 92.0.1

### Settings

No change

### Notes

These filters help

`||aiscore.com/_nuxt/img/banner_bet365.*.png`
`aiscore.com###app > div[class="w100 flex justify-center"][style^="height:"]`

**Comment by uBlock-user** [comment]
> ||aiscore.com/_nuxt/img/banner_bet365.*.png
> aiscore.com###app > div[class="w100 flex justify-center"][style^="height:"]

Report to EasyList at https://github.com/easylist/easylist/issues
