### ISSUE TITLE
google.com (Google Shopping Ads)

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#10132]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.google.com/search?q=smartphone&tbm=shop`

### Describe the issue

There are ads on the Shopping section of Google search. (I highlighted the ads with a red rectangle on the screenshot below) (The language of the text on the screenshot is Brazilian Portuguese)

### Screenshot(s)

![](https://user-images.githubusercontent.com/88633614/135906143-98c926e2-87cf-4137-8f1e-f0211799356c.png)

### uBlock Origin version

1.38.2

### Browser name and version

Firefox 92.0.1

### Settings

- Default

**Comment by uBlock-user** [comment]
Google Shopping page itself is an ad entirely blocking it will break the intended purpose of the page.

**Comment by YoshiTabletopGamer** [comment]
If so, what is the discussion [here](https://github.com/uBlockOrigin/uAssets/commit/54500340d8f17b0b4ca901816745dd80d505fe30#commitcomment-56321944) about?

**Comment by YoshiTabletopGamer** [comment]
I argue that the part in the screenshot 

![](https://user-images.githubusercontent.com/88633614/135917132-fcedff0e-255f-45a3-9406-2ac95438fef0.png)

that is not highlighted in red are not ads.

If the products I did not highlight with a red rectangle are also advertisements, how would they fit the [EasyList policy](https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html)? (Relevant parts in bold)

> the definition of an advert as "the promotion of third party content in return for goods or services".

> "... in return for goods or services"
>     An important question that has been raised is whether an advert requires the exchange of money, to which I would respond that it is not an essential element. **Money may be one of the goods supplied, but there may also be services provided in return.** Therefore a link to, say, a web host would be removed if this is a sponsored link required as a provision of service, but not if the description is merely factual, as this would not be promotion.

Google says that for the part I did not highlight with a red rectangle (Relevant parts in bold)

> Unless otherwise indicated, items are ranked based on relevance, including your search terms and other Google activity. Learn more about managing how your experience is personalised. Some ads data, including your and other users’ interactions with ads, is used to improve the quality of the results. **Google is not compensated for clicks into these results.** 

@uBlock-user

**Comment by uBlock-user** [comment]
> that is not highlighted in red are not ads.

They all pass through `google.com/aclk?` they're all product ads. You can may believe and argue differently but that doesn't change the fact that buyers click on those links to buy products via google and blocking anything on that page is blocking functionality fo that page. 

That page is cosmetically exempted in uBO and in EasyList too. Same for Bing's shopping page.

**Comment by uBlock-user** [comment]
> that is not highlighted in red are not ads.

They all pass through `google.com/aclk?` they're all product ads. You may believe and argue differently but that doesn't change the fact that buyers click on those links to buy products via google and blocking anything on that page is blocking functionality fo that page. 

That page is cosmetically exempted in uBO and in EasyList too. Same for Bing's shopping page.

**Comment by YoshiTabletopGamer** [comment]
How is this any different from blocking Amazon Sponsored Ads, for example? 

buyers click on those links to buy products via **amazon** and blocking anything on that page is blocking functionality for that page.
 
I do understand your opinion, however.

**Comment by uBlock-user** [comment]
> buyers click on those links to buy products via amazon and blocking anything on that page is blocking functionality for that page.

I don't see any reports of users trying to click on those links and failing to do so.

> I do understand your opinion, however.

Not an opinion, this is based on reports of users unable to see products ads in order to buy. 

Just search for google shopping in the search widget of this tracker and you will see multiple reports of breakage.

**Comment by YoshiTabletopGamer** [comment]
I know breakage of webpages is a problem, but I was talking about things like this
![](https://user-images.githubusercontent.com/88633614/135922749-9e1bbbab-af3e-456b-950c-f73f50e2af2e.png)

As you can see, this Amazon search result page has Sponsored results when searching for `smartphone` on the Amazon website, and that is blocked by `##.AdHolder` in EasyList

**Comment by uBlock-user** [comment]
Ask EasyList about this, I don't think they can be compared with Google. Google doesn't sell anything, neither search gets broken on Amazon with that filter unlike on Google Shopping.

**Comment by YoshiTabletopGamer** [comment]
So the difficulty is getting a filter that doesn't break things?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/9694
https://github.com/uBlockOrigin/uAssets/issues/9600
https://github.com/uBlockOrigin/uAssets/issues/9597#issuecomment-881785627

**Comment by YoshiTabletopGamer** [comment]
> 
> 
> #9694 #9600 [#9597 (comment)](https://github.com/uBlockOrigin/uAssets/issues/9597#issuecomment-881785627)

Yeah, the breakage is pretty bad.

**Comment by uBlock-user** [comment]
Amazon's products and amazon's product ads are distinguishable, unlike Google/Bing shopping pages.

**Comment by YoshiTabletopGamer** [comment]
Hey, @uBlock-user. I have found out that the Adguard Base filterlist has a working filter for this issue
`google.*##div[eid][data-async-context] > .sh-sr__shop-result-group[data-hveid]:has(> div[class] > div[class] > .sh-sp__plain)` at https://github.com/AdguardTeam/AdguardFilters/blob/d3bc94a4673d058be55ec3f9a5d59dbfaf137a4b/EnglishFilter/sections/css_extended.txt#L441-L442. 

Could you consider its inclusion?

**Comment by YoshiTabletopGamer** [comment]
It looks like Adguard added that filter to Adguard Base here https://github.com/AdguardTeam/AdguardFilters/commit/8b6052854ae6367baf70369025fa5f431b40c124

**Comment by uBlock-user** [comment]
> Could you consider its inclusion?

Did you test it on the google shopping page ?

**Comment by YoshiTabletopGamer** [comment]
Yes, and there's no breakage.

**Comment by YoshiTabletopGamer** [comment]
Apparently, that one works for Firefox only?

**Comment by YoshiTabletopGamer** [comment]
Google changed the layout, not working anymore.

**Comment by YoshiTabletopGamer** [comment]
The `div[eid][data-async-context]` part makes it not work, because there's no `div` with `eid` attribute anymore.

**Comment by uBlock-user** [comment]
Let AdGuard team know about it, so they can correct the filter.

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/5caf338ac413936864539d53e5509e31148285c3
Google certainly changed the layout and I think we can and should fix those "Ads" in shopping pages even though the whole page is ad. Having revisited past issues, on my end these filters work without breakage:
```
www.google.*##*:not([class^="sh-sr__shop-result-group"]) #kp-wp-tab-overview g-dropdown-menu:upward(#kp-wp-tab-overview > div):has(a[href*="/aclk?"][href$="adurl="])
www.google.*##.sh-sr__shop-result-group[data-hveid] .sh-sp__btn:matches-css(font-size: 13px):upward(.sh-sr__shop-result-group):has(a[href^="/aclk"][href$="adurl="])
www.google.*##c-wiz div[data-hveid] > div > div > ul:has(> li[style="max-width:200px;"] > div > div[data-hveid] > a[href*="/aclk"]):upward(3)
```
`google.*#?#div[eid][data-async-context] > .sh-sr__shop-result-group[data-hveid]:has(> div[class] > div[class] > .sh-sp__plain)` by AG is not obsolete, it targets different ads than the new filter added to Base. My filters cover both. `:matches-path` seems not to be mandatory, but we can use it if breakage is reported.

**Comment by uBlock-user** [comment]
> Having revisited past issues, on my end these filters work without breakage:

Okay, add them.

**Comment by uBlock-user** [comment]
but do not remove  

```
www.google.*##:not(:matches-path(/^/search\?.*tbm=shop|^/shopping/)) a[href*="/aclk?"][data-al]:upward(2)
www.google.*##[href^="https://www.googleadservices.com/pagead/aclk?"][href$="adurl="]:upward(3)
```

We need to take wait and watch approach here.

**Comment by Yuki2718** [comment]
It's no urgent. I'm struggling to reproduce `www.google.*##c-wiz div[data-hveid] > div > div > ul:has(> li[style="max-width:200px;"] > div > div[data-hveid] > a[href*="/aclk"]):upward(3)` - shown on only one Firefox profie when searched for `マスク` on shopping, but can not reproduce on any other profiles with the exact URL, or even on the same profile with new window. My concern is the tag name `c-wiz` may not be stable.

**Comment by Yuki2718** [comment]
`www.google.*##:not(:matches-path(/^/search\?.*tbm=shop|^/shopping/)) a[href*="/aclk?"][data-al]:upward(2)` should not be removed, was typo and I meant `www.google.*##:not(:matches-path(/^/search\?.*tbm=shop|^/shopping/)) *:not([class^="sh-sr__shop-result-group"]) [href^="/aclk"][href$="adurl="]:upward(3)`.

**Comment by uBlock-user** [comment]
I meant for both existing `matches-path()` filters untill we know for sure, so we don't have do another back-and-forth for google shopping pages again.

**Comment by Yuki2718** [comment]
I understand, and added only filters that specifically targets Ads in shopping pages. They should only complement the current filters which targets other pages.
