### ISSUE TITLE
maxstream.video

### ISSUE THREAD

**Issue by vayra1** [uBlockOrigin/uAssets#10144]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://maxstream.video/ne37hqtqzh5q`

### Describe the issue

An anti adblock is in place not only preventing from accessing the content of the website with cosmetic filters but also disabling keypresses that would otherwise let you open the console and help debug the issues. Generic hide alone isn't enough anymore.

### uBlock Origin version

uBlock Origin 1.38.2

### Browser name and version

Firefox 92.0.1

### Settings

Default settings from a new profile

### Notes

Clicking on a browser menu while being on the website and pressing f12 will let you open the developer tools as intended meaning the script needs window focus for it to intercept key presses.

This appears to be the content of the inline script preventing debugging:
```javascript
window.onload = function () {
   document.addEventListener("contextmenu", function (e) {
       e.preventDefault();
   }, false);
   document.addEventListener("keydown", function (e) {

       if (e.ctrlKey && e.shiftKey && e.keyCode == 73) {
           disabledEvent(e);
       }
  
       if (e.ctrlKey && e.shiftKey && e.keyCode == 74) {
           disabledEvent(e);
       }
     
       if (e.keyCode == 83 && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
           disabledEvent(e);
       }
  
       if (e.ctrlKey && e.keyCode == 85) {
           disabledEvent(e);
       }

       if (event.keyCode == 123) {
           disabledEvent(e);
       }
   }, false);
   function disabledEvent(e) {
       if (e.stopPropagation) {
           e.stopPropagation();
       } else if (window.event) {
           window.event.cancelBubble = true;
       }
       e.preventDefault();
       return false;
   }
}
document.oncontextmenu = document.body.oncontextmenu = function() {return false;}
```

The actual content of interest of the page is hidden with the use of multiple nested `display:none !important`. I am not sure if generic hide should be able to intercept these attempts to hide the content of the page but I know fore sure it worked yesterday and now it doesn't anymore so maybe this combined `display:none` + `float` is an attempt to circumvent generic hide.

The DOM structure looks like this and by manually removing `display` and `float` rules the content shows and plays without issues:
```html
<div id="container">
	..
	<div id="ad_topslot">
		<div style="float:right">..</div>
		<div id="dvdvdv" style="">
			<div id="t3t3t3" style="display:none">
				<script>..</script>
				<div id="t5t5t5" style="display: none">
					<div id="content" class="left">..</div>
					<div id="video-content" class="left">
						.. video in here ..
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<script>..</script>
		<script>..</script>
		..
		<script>..</script>
	</div>
</div>
```

**Comment by uBlock-user** [comment]
fixed in https://github.com/uBlockOrigin/uAssets/commit/34fa16ab2779f2784e5ce23d7141d0b6a7b82efb

**Comment by vayra1** [comment]
Should I be able to receive these fixes by emptying cache and reloading filters or I'm supposed to add them manually? Also thank you

**Comment by mapx-** [comment]
wait 5-10 min then update your lists
