### ISSUE TITLE
olx.ro

### ISSUE THREAD

**Issue by ThinksHeIsCool** [uBlockOrigin/uAssets#10146]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.olx.ro/`

### Describe the issue

I reproduced what has been described in https://github.com/tcptomato/ROad-Block/issues/109 even without having 'ROU: Romanian Ad (ROad) Block List Light' enabled on my side.

### uBlock Origin version

1.38.2

### Browser name and version

Google Chrome 94.0.4606.61 (Official Build) (64-bit)

### Settings

.

**Comment by uBlock-user** [comment]
> I reproduced what has been described

reproduced what ? Explain in detail.

**Comment by uBlock-user** [comment]
I only see the issue if I activate the regional list, which can be fixed with `@@tracking/ninja.js$script,domain=olx.ro,badfilter`

**Comment by mapx-** [comment]
other fixes:

`@@||google-analytics.com/analytics.js$script,domain=olx.ro`

or uBO-specific:
`*$script,domain=olx.ro,redirect-rule=noopjs`
