### ISSUE TITLE
Anti-adblock in bowfile.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10148]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bowfile.com/Y56#!/dMDEApK6nQq`

### Describe the issue

Anti-adblock screen appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/136134590-5f2c70d7-efea-4f73-94cf-ec499f91898a.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

Redirect the blocked script helps bypass it

`||d26adrx9c3n0mq.cloudfront.net^$script,redirect=noopjs,domain=bowfile.com`

**Comment by stephenhawk8054** [comment]
Another anti-adblock appears.

URL: `https://bowfile.com/1MR0`

Looks like blocking this link causes the anti-adblock:
`https://d26adrx9c3n0mq.cloudfront.net/?xrdad=939462`

Proposed filter:

`||d26adrx9c3n0mq.cloudfront.net^$xhr,redirect-rule=nooptext,domain=bowfile.com`

**Comment by playonevideo** [comment]
If you enter the homepage and press the "Upload" button for the first two times, it tries to open a popup.
