### ISSUE TITLE
mangoporn.net ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1014]
URL(s) where the issue occurs

https://mangoporn.net/movies/penocchio/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by in4u** [comment]
There's a popup on clicking/playing videos.

**Comment by in4u** [comment]
Ads in the sidebar, above/below video, above page footer, etc.
