### ISSUE TITLE
Incorrect blocking in betterads.org

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10154]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.betterads.org/research/`

### Describe the issue

One of the images is blocked incorrectly.

### Screenshot(s)

- Expectation:
![image](https://user-images.githubusercontent.com/66517106/136311052-461fe692-35aa-49e7-9a68-4a2dc32cb53c.png)

- Issue:
![image](https://user-images.githubusercontent.com/66517106/136310980-a16e4a73-9eb6-477f-a988-f1a908851378.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

It is caused by the filter `-web-ad-`.

Whitelisting the filter helps:
`@@-web-ad-$image,domain=www.betterads.org`

**Comment by mapx-** [comment]
@ryanbr
