### ISSUE TITLE
rocket-league.com unusable with uBlock Origin

### ISSUE THREAD

**Issue by soulmist7** [uBlockOrigin/uAssets#10151]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://rocket-league.com/chat/ [username]`
`https://rocket-league.com/trading`

### Describe the issue

rocket-league.com website seems to have some advanced coding that is preventing selective blocking of items on their site. I cannot successfully use element zapper to zap ads for their premium service without having those ads return upon page refresh. Chat functionality on there site also breaks when uBlock Origin is enabled. It seems as though the only option to create chat messages is to disable uBlock Origin.

### uBlock Origin version

1.38.2

### Browser name and version

Brave Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)

### Settings

![Screen Shot 2021-10-06 at 10 12 15 AM](https://user-images.githubusercontent.com/78063217/136220188-40d8d590-12cc-4a39-a8df-564ffaae99b0.png)
![Screen Shot 2021-10-06 at 10 11 42 AM](https://user-images.githubusercontent.com/78063217/136220199-fefc22cd-8d3f-4dc6-9071-d8570f44186a.png)

### Notes

I am simply trying to get a usable version of the site working while using adblockers.

**Comment by uBlock-user** [comment]
You have activated many non-default lists, test on default settings/lists only.
