### ISSUE TITLE
https://guides.magicgameworld.com/ issues

### ISSUE THREAD

**Issue by shnaps** [uBlockOrigin/uAssets#10168]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://guides.magicgameworld.com`

### Describe the issue

Similar to https://github.com/uBlockOrigin/uAssets/issues/9824 issue,  latest ublock, latest ublock filters (contains the previous fix). 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/18357973/136681911-49e1e574-59e9-4995-81ee-0bedc7e47e99.png)

### uBlock Origin version

1.38.2

### Browser name and version

94.0b3

### Settings

All default

**Comment by uBlock-user** [comment]
> contains the previous fix

The previous fix still works as expected. Test on default settings/lists with all other extensions disabled.

**Comment by shnaps** [comment]
@uBlock-user seems like you are right, one of scripts inside tapermonkey is interfering with ublock. Closing the issue.
