### ISSUE TITLE
HDSPORT.BIZ anti-adblock

### ISSUE THREAD

**Issue by eplayerclick** [uBlockOrigin/uAssets#10164]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile
- [X] uBO with default lists/settings

### URL(s) where the issue occurs

`hdsport.biz`

### Describe the issue

Hello. On hdsport.biz, some assets are served from include.canale.live, including some streams, but because that domain is blocked by ublock, those are being blocked as well. 

### uBlock Origin version

1.38.0

### Browser name and version

edge Version 94.0.992.38 (Official build) (64-bit)

### Settings

None

**Comment by uBlock-user** [comment]
@okiehsch

**Comment by uBlock-user** [comment]
Tried few streams,  I don't see any breakage .whatsoever

> they use multiple servers to serve their streams

Unless you share the dynamic link, there's nothing actionable here.

**Comment by uBlock-user** [comment]
`include.canale.live` serves scripts that generates popups, hence was blocked.

**Comment by eplayerclick** [comment]
![image](https://user-images.githubusercontent.com/90185126/136652204-55e65dcf-18a6-45f5-94f8-8c63d4ea41a0.png)

**Comment by uBlock-user** [comment]
Anti-adblock, not related to the filter added at all, happens without it too...
