### ISSUE TITLE
[NSFW] Group of badware domains .pw (130 sites)

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10162]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

[NSFW] 130 sites:

<details>
  <summary>Badware domains .pw (RAW subdomains)</summary>

  ```
apo.owonrinredfish.pw
avb.sp101starrcast.pw
avb.xextomaki.pw
bam.atan2itiyathok.pw
bds.chambersburgpevec.pw
bkc.cupsdl2vpn.pw
blj.koktelmusilimse.pw
bun.registrationsepayslip.pw
cfj.broomlicaones.pw
cfj.uwehamon.pw
dlr.kacurrelaisopentyl.pw
dyf.blundersgform.pw
dym.counsellorkrepsinio.pw
dym.inventormarjorie.pw
emr.decapitadacennet.pw
emz.parathyroidectomyjazztube.pw
fde.emeraldsmashetani.pw
feedbackip09.online
feedbackip09.pw
fgl.demodulatorzercher.pw
fgl.hardibackerastronic.pw
fkn.ipfirezilizobakia.pw
foe.4e87ona18ho029.pw
foj.ecosmartreference.pw
frq.onowucloudplayer.pw
gdk.s1005cineform.pw
gfxtra.unblocksite.pw
ggm.scv3020bil.pw
gsf.unlobedeconomice.pw
hjy.1356fader.pw
hkt.quiplashmagknight.pw
hoe.nelderunruled.pw
hxh.pilmicofzf.pw
hyx.ladygreyhound932049.pw
hyx.seeduwatcm.pw
ilz.arcelikbhagavate.pw
iqy.collectiblesestradas.pw
isg.pysparkmiscarriage.pw
izl.misheardbackwards.pw
izn.indeedinstances.pw
izn.woesnastexo.pw
jcf.venezolanaolmuyor.pw
jcz.jawtrackhedar.pw
jzt.dhyanakaew.pw
kit.derivaracuosas.pw
kok.aparteamarula.pw
kul.jahanwelders.pw
kyg.nestuntie.pw
lkb.dedieuchildlike.pw
lzu.hamtramckkomz.pw
mat.parkers3021.pw
mcm.bolly4uguilty.pw
mcm.flambeurudshiin.pw
mfb.roopifreeing.pw
msm.palgacapmonster.pw
nrb.4matictrilug.pw
nrb.mazyapenuma.pw
ntc.se16hsamle.pw
nuk.mccraneysrd.pw
nzd.isimlerichennal.pw
nzq.podoljechibi.pw
ode.bundlereleaserehomed.pw
ofm.d25501kapk4now.pw
onn.alibitissa.pw
org-4.enittus.pw
otr.gamipressbannerbomb.pw
oxc.catoolsjaisi.pw
oxr.heapymountebank.pw
ozp.baligbp742.pw
pab.bazookaromer.pw
ppe.mediamonkeyaperitive.pw
ppk.mantelsheba.pw
ptr.crayolaevoo.pw
pyf.improvvisazioneidentifies.pw
qan.lepsitheophylline.pw
qrv.cimmerianprebiotic.pw
qrv.nativedropboxagentp1693.pw
rad.edulasticescritura.pw
rfj.minifigchusliya.pw
rfj.pvwacalyx.pw
rqy.estrichkarde.pw
rr.handbook-college.pw
sht.wr720nbeleren.pw
sst.saqartveloshinovatel.pw
sst.simona80073701.pw
sxl.skalesyarda.pw
tjm.rsxtrandafiri.pw
tkj.scaredhvlp.pw
topwp.pw
tth.balacerareal.pw
tzl.611lpc2148.pw
ufz.assisipanni.pw
ugq.mathcalsoundstation.pw
uia.ponponponwyckoff.pw
ulh.awhileadmintoolkit.pw
ulx.moubimuthh.pw
vql.fahrradbanjiran.pw
vqn.scrabblekecoa.pw
vqn.terminatedindo4dpool.pw
vrz.azkasoftban.pw
wae.gnaliesener.pw
wao.raisesstink.pw
wfg.enrollahami.pw
wfg.hansekapra.pw
wfv.coronectomypanchayati.pw
wfv.lseanaa.pw
wmy.zadaredh.pw
wuh.aproveitasinga.pw
xee.tirandovoador.pw
xga.surjectivedtla.pw
xgh.maonoozi.pw
xiz.fitrhifiman.pw
xkx.provisioningpkce.pw
xkz.kiduxsosmed.pw
xlu.cerkesipka.pw
xlu.qytetsesap.pw
xoz.nandanvankakamega.pw
xsy.harumsejahtera.pw
xwc.stampabileparivaar.pw
yew.obemarietta.pw
ysy.angiospermsincentives.pw
ytc.quickloadsuhagraat.pw
yxs.empresarialcameradar.pw
yxs.referatynuggets.pw
z3.practice-success.pw
zab.wurthbhagavat.pw
zbw.pilvedezazaremote.pw
zig.4282beatniks.pw
zql.synapsismichat.pw
zrh.gumastadccd.pw
  ```
</details>

<details>
  <summary>Badware domains .pw (uBO format ready - domains)</summary>
  
  ```
||1356fader.pw^$doc
||4282beatniks.pw^$doc
||4e87ona18ho029.pw^$doc
||4matictrilug.pw^$doc
||611lpc2148.pw^$doc
||alibitissa.pw^$doc
||angiospermsincentives.pw^$doc
||aparteamarula.pw^$doc
||aproveitasinga.pw^$doc
||arcelikbhagavate.pw^$doc
||assisipanni.pw^$doc
||atan2itiyathok.pw^$doc
||awhileadmintoolkit.pw^$doc
||azkasoftban.pw^$doc
||balacerareal.pw^$doc
||baligbp742.pw^$doc
||bazookaromer.pw^$doc
||blundersgform.pw^$doc
||bolly4uguilty.pw^$doc
||broomlicaones.pw^$doc
||bundlereleaserehomed.pw^$doc
||catoolsjaisi.pw^$doc
||cerkesipka.pw^$doc
||chambersburgpevec.pw^$doc
||cimmerianprebiotic.pw^$doc
||collectiblesestradas.pw^$doc
||coronectomypanchayati.pw^$doc
||counsellorkrepsinio.pw^$doc
||crayolaevoo.pw^$doc
||cupsdl2vpn.pw^$doc
||d25501kapk4now.pw^$doc
||decapitadacennet.pw^$doc
||dedieuchildlike.pw^$doc
||demodulatorzercher.pw^$doc
||derivaracuosas.pw^$doc
||dhyanakaew.pw^$doc
||ecosmartreference.pw^$doc
||edulasticescritura.pw^$doc
||emeraldsmashetani.pw^$doc
||empresarialcameradar.pw^$doc
||enittus.pw^$doc
||enrollahami.pw^$doc
||estrichkarde.pw^$doc
||fahrradbanjiran.pw^$doc
||feedbackip09.online^$doc
||feedbackip09.pw^$doc
||fitrhifiman.pw^$doc
||flambeurudshiin.pw^$doc
||gamipressbannerbomb.pw^$doc
||gnaliesener.pw^$doc
||gumastadccd.pw^$doc
||hamtramckkomz.pw^$doc
||handbook-college.pw^$doc
||hansekapra.pw^$doc
||hardibackerastronic.pw^$doc
||harumsejahtera.pw^$doc
||heapymountebank.pw^$doc
||improvvisazioneidentifies.pw^$doc
||indeedinstances.pw^$doc
||inventormarjorie.pw^$doc
||ipfirezilizobakia.pw^$doc
||isimlerichennal.pw^$doc
||jahanwelders.pw^$doc
||jawtrackhedar.pw^$doc
||kacurrelaisopentyl.pw^$doc
||kiduxsosmed.pw^$doc
||koktelmusilimse.pw^$doc
||ladygreyhound932049.pw^$doc
||lepsitheophylline.pw^$doc
||lseanaa.pw^$doc
||mantelsheba.pw^$doc
||maonoozi.pw^$doc
||mathcalsoundstation.pw^$doc
||mazyapenuma.pw^$doc
||mccraneysrd.pw^$doc
||mediamonkeyaperitive.pw^$doc
||minifigchusliya.pw^$doc
||misheardbackwards.pw^$doc
||moubimuthh.pw^$doc
||nandanvankakamega.pw^$doc
||nativedropboxagentp1693.pw^$doc
||nelderunruled.pw^$doc
||nestuntie.pw^$doc
||obemarietta.pw^$doc
||onowucloudplayer.pw^$doc
||owonrinredfish.pw^$doc
||palgacapmonster.pw^$doc
||parathyroidectomyjazztube.pw^$doc
||parkers3021.pw^$doc
||pilmicofzf.pw^$doc
||pilvedezazaremote.pw^$doc
||podoljechibi.pw^$doc
||ponponponwyckoff.pw^$doc
||practice-success.pw^$doc
||provisioningpkce.pw^$doc
||pvwacalyx.pw^$doc
||pysparkmiscarriage.pw^$doc
||quickloadsuhagraat.pw^$doc
||quiplashmagknight.pw^$doc
||qytetsesap.pw^$doc
||raisesstink.pw^$doc
||referatynuggets.pw^$doc
||registrationsepayslip.pw^$doc
||roopifreeing.pw^$doc
||rsxtrandafiri.pw^$doc
||s1005cineform.pw^$doc
||saqartveloshinovatel.pw^$doc
||scaredhvlp.pw^$doc
||scrabblekecoa.pw^$doc
||scv3020bil.pw^$doc
||se16hsamle.pw^$doc
||seeduwatcm.pw^$doc
||simona80073701.pw^$doc
||skalesyarda.pw^$doc
||sp101starrcast.pw^$doc
||stampabileparivaar.pw^$doc
||surjectivedtla.pw^$doc
||synapsismichat.pw^$doc
||terminatedindo4dpool.pw^$doc
||tirandovoador.pw^$doc
||topwp.pw^$doc
||unblocksite.pw^$doc
||unlobedeconomice.pw^$doc
||uwehamon.pw^$doc
||venezolanaolmuyor.pw^$doc
||woesnastexo.pw^$doc
||wr720nbeleren.pw^$doc
||wurthbhagavat.pw^$doc
||xextomaki.pw^$doc
||zadaredh.pw^$doc
  ```
  
</details>

### Describe the issue

- badware domains found in Google search, which redirect to other badware domains, which (the other) might be or not, blocked in uBO Badware Risks already
- some of their main domains might be not loading, but subdomains are active
- sometimes some domains might fail to load, but other time they load fine, example: one day many of them have been returning some 502/503 Gate Errors, and loading fine only 1 out of 10 times, but the other day (today) they are all loading fine, which means that regardless of a fact they sometimes are unavailable, they are alive and should be blocked
- another thing, I've found the following 2: `qan.lepsitheophylline.pw` + `vrz.azkasoftban.pw` to be Non-existent domains, but their main domains are alive: `lepsitheophylline.pw` + `azkasoftban.pw` despite they don't seem to be hosting a badware website/redirection anymore, but  who knows whether they are hosting other active subdomains or not, so I'm not sure whether we should block the two mentioned or not, decide yourself
- another thing I've noticed is that uBO Badware Risks contains no .pw domains at the moment, maybe it's just a coincidence (I'm not counting the one added few days ago https://github.com/uBlockOrigin/uAssets/commit/1f9935df248e27dbd73144af8e2ac49956768ee2)

### Screenshot(s)

An  example where being redirected to:

![111](https://user-images.githubusercontent.com/75935068/136551304-fce3258a-5081-419a-878e-1fefb7ce421b.png)

### uBlock Origin version

1.38.1b2

### Browser name and version

FF 92 / O 78

### Settings

-

**Comment by iam-py-test** [comment]
I tried visiting on of those domains in a VM. 
All the domains in the redirects/Network requests (filtered to remove legitimate domains):
```
eztv.unblocksite.pw
choupsee.com
ecma.abdittoan.com
accompliceexpressingpug.com
phicmune.net
ezimg.ch
abdittoan.com
atjigglypuffor.com
inpagepush.com
matomo.hellohi.me
venetrigni.com
cdn.itskiddoan.club
dozubatan.com
starvationdefence.com
my.rtmark.net
cdn.barscreative1.com
interstitial-07.com
cdn.sb4you1.com
offerimage.com
viralsparks.io
rox.neptuntrack.com
installcurrentoverlythefile.vip
forflygonom.com
spamhouse-checker.com
altynamoan.com
kimoangel.info
expandspin.digital
siphair.quest
defendconsume.work
omnatuor.com
e2ertt.com
notificationblocker.com
profewide-luxellow.icu
```

**Comment by Yuki2718** [comment]
On my end only some of the domain in the report redirects to `https://1.portalisimmo.com/go/haztomrxmu5dgnjqgu?sub1=old`, but do nothing.

**Comment by felix-22** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/10075#issue-1007162431 : Scam about S​​​e​​​x​​​B​​​a​​​d​​​o​​​o

One more `https://moneymake02.online/?u=d4e8kwf&o=vm7ewuv&t=e-dat2m`

<hr>

Also I've found some suspicious site, not sure but it tries to access localhost: `http://sx.nazari.org/`

**Comment by Yuki2718** [comment]
> Also I've found some suspicious site, not sure but it tries to access localhost: http://sx.nazari.org/

I can't access.

**Comment by felix-22** [comment]
> I can't access.

Neither do I at the moment.
<hr>

Meanwhile I've another scum:

> https://github.com/uBlockOrigin/uAssets/issues/10075#issue-1007162431 : fake bitcon pages

`https://bitcoinevolutionsite.club/u/ddf45fe902dfd75c9ad2?click_id=50e331b8-e8a9-4377-a9de-b01edcbe2718&aff_id=l84275`

**Comment by felix-22** [comment]
> > Yuki2718 : I can't access.
> 
> felix-22 : Yeah, neither do I at the moment.

The site is back now.

**Comment by Yuki2718** [comment]
> The site is back now.

Still I can't.

**Comment by felix-22** [comment]
> Yuki2718 : https://github.com/uBlockOrigin/uAssets/issues/10162#issuecomment-957947475 :
> > felix-22 :  The site is back now.
> 
> Still I can't.

Yeah, the site seems to be occasionally or permanently unnaccessible for some users.
Anyway it has turned out it's already blocked in Dan Pollock’s hosts file as mentioned here: 
`https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-958186113` which is a hosts list included in uBO, so I guess there is no need to duplicate it into uBO Badware.

**Comment by felix-22** [comment]
I've visited `designbee.biz` from legitimate Google search and have landed at bunch of scum sites:

Logger output (doc):

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 |  |  | pieprzyc.com | 1 | doc | `https://pieprzyc.com/lp/pre-jar-int-nak-red/?s1=aterra_PL&s2=PL_DSK_POP&s3=15987044&tracking_id=0086cd399fb8006b96a09b1fe2b55042` |
| +1 |  |  | pottercosign.com | 1 | doc | `https://pottercosign.com/igiirj327?shu=dc79ae0d8e7c72f4026d702f021563eee382460f0157da3d08ecc5adead688e081f9be614e52d0bd8f8bd42a00390f87ef592def33088e4755c149e75745a3d50d063dec576b876712e1cd0fd02fb47691f160348088bde3aaa487bcfe440b&pst=1635956869&rmtc=t&uuid=&pii=&in=false&key=23d86b65fc459dac7c5a83a8fab67935&refer=https%3A%2F%2Fwww.google.pl%2F` |
| +0 |  |  | pottercosign.com | 1 | doc | `https://pottercosign.com/igiirj327?key=23d86b65fc459dac7c5a83a8fab67935` |
| +0 |  |  | 37.1.209.213 | 1 | doc | `http://37.1.209.213/xD252Hx3?host=designbee.biz/&mark=03112021_ALEXk10Biz_1kk_hesh_noSUB&keyword=adblock%20plus%20firefox&template=&se_referrer=https%3A%2F%2Fwww.google.pl%2F` |
| +0 |  |  | designbee.biz | 1 | doc | `http://designbee.biz/9jTN` |
