### ISSUE TITLE
vqporn.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1016]
URL(s) where the issue occurs

https://www.vqporn.com/videos/5218/bang-real-teens-jade-amber-takes-us-on-a-tour-of-pink-pussy-in-porn-debut/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
ads @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by dumbusernameidk** [comment]
popup when pressing play on video player. `vqporn.com##+js(addEventListener-defuser.js, /^(?:load|click)$/, popMagic)` works.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
