### ISSUE TITLE
Featured Videos

### ISSUE THREAD

**Issue by online-stuff** [uBlockOrigin/uAssets#10167]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://fable.fandom.com/wiki/Necropolis`

### Describe the issue

Trying to block 'Featured Videos'..

fandom.com is bad for them, along with some news sites..

X the video when the page loads, scroll down and the video comes back, having to close it again.

There are posts from years ago with suggestions on blocking them but either never worked or don't work anymore.

### uBlock Origin version

Latest

### Browser name and version

Firefox Latest and 68.11.0

### Settings

Enabled all filters except the non-English ones.

### Notes

There are posts from years ago (2017) with suggestions of custom rules for 'featured videos' but they either never worked or don't work anymore.

**Comment by uBlock-user** [comment]
> Enabled all filters except the non-English ones.

Test ond efault settings/lists.

**Comment by uBlock-user** [comment]
@online-stuff Disable **_Ignore generic cosmetic filters_**  on Android Firefox.

**Comment by uBlock-user** [comment]
You will need to investigate why it only appears for you.
