### ISSUE TITLE
Anti-adblock in vtvcab.vn

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10172]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.vtvcab.vn/video/play/the-gioi-phep-thuat-cua-sophia-2-thegioiphepthuatcuasophia/tap-1.html`

### Describe the issue

Anti-adblock on video player

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/136698136-3d49080c-05d0-4c7a-a3e8-e0f8aad79446.png)

### uBlock Origin version

1.38.2

### Browser name and version

Ungoogled Chromium 94.0.4606.71

### Settings

No change

### Notes

Proposed filter:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vtvcab.vn`

**Comment by mapx-** [comment]
yeah, it's ok, I was able to test using a vn proxy
