### ISSUE TITLE
farm(s)

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#10181]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://onemacusa.com/P5kdwWywAlCWm4heDAOfNhVUKEDZBiDwokIBRIRiWXs/?cid=616362d943ce580001b00123&sid=14882770`

### Describe the issue

seems to be part of a notification-allowance farm

### Screenshot(s)

![Screenshot 2021-10-10 180336](https://user-images.githubusercontent.com/92271206/136714468-ff9c0831-a57e-4fef-968f-2348d0a39604.png)

### uBlock Origin version

1.38.2

### Browser name and version

Google Chrome

### Settings

.

**Comment by ThinksHeIsCool** [comment]
Could `http://nbryb.com/` be blocked?

**Comment by ThinksHeIsCool** [comment]
Could `https://www.rogueleader.org/` be blocked?

**Comment by ThinksHeIsCool** [comment]
https://user-images.githubusercontent.com/92271206/136714713-63c367be-2ba4-4747-acb9-0ef2ea0ee990.mp4

**Comment by ghajini** [comment]
Original URL where it occurs?

**Comment by ThinksHeIsCool** [comment]
@mapx- it's possible that these URLs (the ones given in this GitHub issue) aren't connected with eachoter; I found most of them after looking for such webpages on the internet.

**Comment by Yuki2718** [comment]
They look referrer so you'll be redirected to the push scam only if nativated through search engine.
