### ISSUE TITLE
img.imgdone.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1019]
URL(s) where the issue occurs

http://img.imgdone.com/image/pQ91i

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS

`http://imgdone.com/image/ETXSP`
