### ISSUE TITLE
antiadblocking issue

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#102]
![screenshot 1](https://cloud.githubusercontent.com/assets/20338483/17643147/99b1a74a-6115-11e6-936e-562b4216f781.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/20338483/17643240/b870d0e0-6118-11e6-8a75-19a9f210de8a.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/20338483/17643241/b88ba2b2-6118-11e6-9824-643c6c43dc32.png)

### Describe the issue
websites said to block disable adblocking extension

### One or more specific URLs where the issue occurs
http://www.businesstoday.in/magazine/corporate/corporate-tax-disputes-continue-to-rise/story/235876.html

http://aajtak.intoday.in/story/modis-minister-jitender-singh-says-will-unfurl-tricolour-in-pok-1-882672.html

http://indiatoday.intoday.in/olympics2016/story/rio-olympics-2016-live-india-at-rio-day-8/1/739765.html
### Steps for anyone to reproduce the issue

1. go to businesstoday.in or  aajtak.intoday.in or  indiatoday.intoday.in
1. click any news
1. will say your adblocker is on
tried https://github.com/reek/anti-adblock-killer steps but not worked
### Your settings

- Browser/version: chrome Version 52.0.2743.116 m (64-bit)

- uBlock Origin version: 1.8.4

##### Your filter lists
default filter lists + youtube pure video experience

##### Your custom filters (if any)
tried https://github.com/reek/anti-adblock-killer steps but not worked

notes-

tried scripts on easylist forum but that breaked site functionality(specially with businesstoday.in)
same with above mentioned sites
only solution i found is to block javascript which breaks other site functionality....

**Comment by ghajini** [comment]
i have great expectation from this developer..abp sucks

**Comment by harshanvn** [comment]
Here is the filter i crafted through element picker, it seems the site functionality is working fine..

`www.businesstoday.in###adbocker_alt

intoday.in###adbocker_alt
`

**Comment by gorhill** [comment]
Thanks @harshanvn, I will add these to uBO's filters.

**Comment by ghajini** [comment]
also video play not working
http://aajtak.intoday.in/video/top-news-till-evening-of-13th-august-2016-1-882671.html

video play for 2 seconds then blank page appears

**Comment by gorhill** [comment]
Force an update of _uBlock filters_.

**Comment by ghajini** [comment]
need to block zedo ads globally...it just make page unresponsive and page loads slowly
check this with zedo ads enabled and disabled 
http://indiatoday.intoday.in/story/mohenjo-daro-movie-review-hrithik-roshan-ashutosh-gowariker-pooja-hegde/1/738889.html
after blocking zedo ads(axp.zedo.com and zedo domains) page loads quickly

thankx @gorhill

**Comment by gorhill** [comment]
> need to block zedo ads globally

Well, looks like `zedoads.com` and `pagead2.googlesyndication.com` are whitelisted in EasyList. Sigh. 

EasyList fixes to accommodate ABP's limitations can definitely be a liability to uBO users.

At which point a blocker can still be called a blocker when their solution around anti-blocker schemes is to actually do what the site is asking, i.e. letting 3rd-party advertizers' scripts load in the browser.

I will add two block filters with the `important` option to counter these exception filters.

**Comment by ghajini** [comment]
can't read comments.. when i click on comment, nothing happens(comments not shown)
http://www.businesstoday.in/sectors/telecom/bsnl-extends-free-roaming-service-by-1-year/story/233861.html#comment

**Comment by ghajini** [comment]
@gorhill  stopped working.again shows warning of antiadblocking
http://indiatoday.intoday.in/story/raghuram-rajan-public-sector-banks-salary-suggestions/1/741763.html

![screenshot 4](https://cloud.githubusercontent.com/assets/20338483/17708817/3a9f53be-6404-11e6-880f-a368741e2bd7.png)

**Comment by ghajini** [comment]
why this is happening.........can i use @@||intoday.in/*ad$script

**Comment by Tmp341** [comment]
Here are my filters: 

> uBlock filters‎ 
uBlock filters – Badware risks‎
uBlock filters – Privacy‎ 
uBlock filters – Unbreak‎ 
EasyList‎
Peter Lowe’s Ad server list
EasyPrivacy
Malware Domain List‎
Malware domains
Fanboy’s Annoyance List‎
TUR: Adguard Turkish Filter‎

I didn't see that warning. 
[Screen](http://prnt.sc/c75g6p)

**Comment by ghajini** [comment]
http://www.businesstoday.in/current/economy-politics/urjit-patel-all-set-to-replace-raghuram-rajan-as-rbi-governor/story/236295.html

not working...
![screenshot 20](https://cloud.githubusercontent.com/assets/20338483/17835488/22f68b20-678c-11e6-8f0e-8fcc586ea431.png)

**Comment by Tmp341** [comment]
It wasn't working first, but after updating the fixed filter, it's working now.
