### ISSUE TITLE
imgpeak.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1022]
URL(s) where the issue occurs

http://imgpeak.com/img-58696a6642f07.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
close 
https://github.com/uBlockOrigin/uAssets/commit/79729b917394fb89ed35a00e3ba4db422cc55fca
