### ISSUE TITLE
epn.bz [anti-adblock] [tracker?]

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#10233]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://epn.bz`
`https://epn.bz/en/`

### Describe the issue

anti-adblock (permanent)

### Screenshot(s)

![3](https://user-images.githubusercontent.com/75935068/137596509-fc066417-666d-4cec-b24c-8139404ae7de.png)

### uBlock Origin version

1.38.7b3

### Browser name and version

FF 93 / O 78

### Settings

+ uBO Annoyances

**Comment by felix-22** [comment]
Fasle alert, I have not realised it's a russian website with EN lang alternative, it's fixed with `RUS: RU AdList` enabled.

**Comment by felix-22** [comment]
Hmm, since EN lang is set automatically for non-RU users, an non-RU user might be unaware it's a russian site and he can be unaware to enable `RUS: RU AdList`, so I'm confused whether it should be fixed separately for non-RU users?

**Comment by okiehsch** [comment]
> by the way isn't it an ad/tracking server which should be just blocked 

Don't know if they use that domain for tracking purposes, if they do
`||epn.bz^$3p`
is a valid filter for `EasyPrivacy`.

**Comment by felix-22** [comment]
OK, I've called ryanbr & khirin then, to determine it.

**Comment by ryanbr** [comment]
Is there a sample page using `epn.bz` ?

**Comment by felix-22** [comment]
I'm not sure, that's why I called you, so that you could check it out for yourself:
- https://publicwww.com/websites/%22epn.bz%22/
- https://epn.bz/en/partners/ali/rules

From domains that are not hidden I've only found `https://ali.pub/` but it only uses stylesheets as third-party.
