### ISSUE TITLE
goplay.be anti adb

### ISSUE THREAD

**Issue by FRS597** [uBlockOrigin/uAssets#10232]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.goplay.be/video/temptation-island-love-or-leave/temptation-island-love-or-leave-s13/temptation-island-love-or-leave-s13-aflevering-9#autoplay`

### Describe the issue

The website pops up a message saying that I need to disable my adblocker to see the website. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/31478150/137596088-c5b73485-acd5-4b32-a672-2fe7aa93f9ae.png)

### Configuration

Ok.

**Comment by ThinksHeIsCool** [comment]
should ``@@||goplay.be^$ghide` be added to filter.txt?

**Comment by krystian3w** [comment]
Due ossible generate lefovers and disable many filters from "Fanboy Annoyances" (so can back social buttons).
