### ISSUE TITLE
games.chicagotribune.com and 15 other similar domains (16 total)

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1024]
### URL(s) where the issue occurs

`http://games.chicagotribune.com/games/daily-crossword/`

others: 
```js
if (a.domCmp(["games.nydailynews.com", "games.express.co.uk", "puzzles.independent.co.uk", "games.orlandosentinel.com",
    "puzzles.standard.co.uk", "games.parade.com", "games.baltimoresun.com", "games.mcall.com", "games.somersetlive.co.uk",
    "games.sun-sentinel.com", "games.reviewjournal.com", "games.dailypress.com", "puzzles.bestforpuzzles.com",
    "games.sandiegouniontribune.com", "games.charlotteobserver.com", "games.chicagotribune.com"])) {
    a.readOnly("Adv_ab", false);
}
```

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34076051-899cf38c-e297-11e7-9c19-21992fbdde50.png)

Reproduction: Enter the domain, then click Play Now (or a similar button). 
![image](https://user-images.githubusercontent.com/7283682/34076055-982f85a4-e297-11e7-9c4e-6319e46e0398.png)

Expected (this but without ads): 
![image](https://user-images.githubusercontent.com/7283682/34076089-29a721cc-e298-11e7-8169-66802a76119d.png)

Require Flash. 

### Versions

- Browser/version: ff 57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

My solution `a.readOnly("Adv_ab", false);` may or may not work.

**Comment by okiehsch** [comment]
With Chrome
````
nydailynews.com,standard.co.uk##script:inject(set-constant.js, Adv_ab, 0)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=standard.co.uk|nydailynews.com
````
With Firefox I also have to add
````
@@||amsarkadium-a.akamaihd.net/assets/*/advertisements.js$script,domain=nydailynews.com|standard.co.uk
````

**Comment by jspenguin2017** [comment]
AFAIK it only affect the `game.` subdomain.

**Comment by okiehsch** [comment]
There are some `puzzles.` subdomains but I get your point.

**Comment by okiehsch** [comment]
````
games.nydailynews.com,games.express.co.uk,puzzles.independent.co.uk,games.orlandosentinel.com,puzzles.standard.co.uk,games.parade.com,games.baltimoresun.com,games.mcall.com,games.somersetlive.co.uk,games.sun-sentinel.com,games.reviewjournal.com,games.dailypress.com,puzzles.bestforpuzzles.com,games.sandiegouniontribune.com,games.charlotteobserver.com,games.chicagotribune.com##script:inject(set-constant.js, Adv_ab, 0)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=games.nydailynews.com|games.express.co.uk|puzzles.independent.co.uk|games.orlandosentinel.com|puzzles.standard.co.uk|games.parade.com|games.baltimoresun.com|games.mcall.com|games.somersetlive.co.uk|games.sun-sentinel.com|games.reviewjournal.com|games.dailypress.com|puzzles.bestforpuzzles.com|games.sandiegouniontribune.com|games.charlotteobserver.com|games.chicagotribune.com
@@||amsarkadium-a.akamaihd.net/assets/*/advertisements.js$script,domain=games.nydailynews.com|games.express.co.uk|puzzles.independent.co.uk|games.orlandosentinel.com|puzzles.standard.co.uk|games.parade.com|games.baltimoresun.com|games.mcall.com|games.somersetlive.co.uk|games.sun-sentinel.com|games.reviewjournal.com|games.dailypress.com|puzzles.bestforpuzzles.com|games.sandiegouniontribune.com|games.charlotteobserver.com|games.chicagotribune.com
````
still have to test if it works for all sites, will do later.

**Comment by okiehsch** [comment]
@jspenguin2017 I tested all domains and it works with all of them, except `games.mcall.com` and `games.chicagotribune.com`.

````
games.mcall.com,games.chicagotribune.com##script:inject(set-constant.js, Adv_ab, 0)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=games.mcall.com|games.chicagotribune.com
@@||amsarkadium-a.akamaihd.net/assets/*/advertisements.js$script,domain=games.mcall.com|games.chicagotribune.com
````
The games never load, I have no clue why, maybe you can take a look.
Example:
 `http://games.mcall.com/games/sudoku`
 `games.chicagotribune.com/games/sudoku`

**Comment by jspenguin2017** [comment]
It does load if I white list... What have you tried so far? 
![image](https://user-images.githubusercontent.com/7283682/34085141-194186d6-e349-11e7-808a-97873a8a4f16.png)

**Comment by okiehsch** [comment]
Well, yes but the fix works for all other sites and I don't see any difference and actually
`http://games.chicagotribune.com/games/sudoku/` **does** load, but it takes a good 2 minutes on my end,  
so adding the site to the fix is pointless.

**Comment by okiehsch** [comment]
![unbenannt](https://user-images.githubusercontent.com/16838044/34085204-fefe378a-e38c-11e7-99e1-8fea043f7d16.PNG)

If you load any of the `games.` sudoku site you will reproduce the screenshot, in all cases except
`games.chicagotribune.com` and `games.mcall.com` the "advertisement" banner disappears after a few seconds and the game starts, with `games.chicagotribune.com` this happen after a few minutes.

**Comment by jspenguin2017** [comment]
Hum, OK, probably a timer somewhere... I'll see if I can boost it.

**Comment by okiehsch** [comment]
OK, if I whitelist `http://games.chicagotribune.com/games/sudoku/` the game will start **after** a 2 min
video ad plays on my end, so it appears this is still happening in the background before the game starts
after the fix is applied.

**Comment by jspenguin2017** [comment]
Looks like it depend on how long the ads is, my last visit (with white list), the ads is like 3 seconds. 
Sounds like a timer that needs to be boosted.

**Comment by okiehsch** [comment]
Yes, but I checked the other sites, they all have 1 or 2 minute video ads and still the games load after a few seconds, only `chicagotribune.com` acts differently.

**Comment by okiehsch** [comment]
I found a solution.

````
@@||games.mcall.com/*/video-prebid.html$subdocument,first-party
@@||amsarkadium-a.akamaihd.net/*/prebid*.js$script,domain=games.chicagotribune.com|games.mcall.com
@@||games.chicagotribune.com/*/video-prebid.html$subdocument,first-party
````
These two domains are the only ones with `prebid`-requests, so allowing them, fixes the issue, redirects
won't work.

**Comment by KiLL4FuNK** [comment]
Anti-adblock

**Comment by huyszn** [comment]
More domains that have Adblocker detection. Also, it looked like `games.parade.com` was removed between updates?:

```
gamelab.com
games.insp.com
games.parade.com
games.denverpost.com
games.heraldsun.com
games.dallasnews.com
games.newsobserver.com
games.theadvocate.com
games.sacbee.com
games.puzzlebaron.com
games.gameshownetwork.com
games.pressdemocrat.com
puzzles.centralmaine.com
games.kentucky.com
games.sltrib.com
games.greatergood.com
puzzles.pressherald.com
games.abqjournal.com
games.amny.com
arcade.buzzrtv.com
philly.arkadiumarena.com
juegos.elnuevoherald.com
games.everythingzoomer.com
arcade.lemonde.fr
games.springfieldnewssun.com
games.macon.com
games.boston.com
puzzles.centralmaine.com
games.thenewstribune.com
games.kansas.com
games.kansascity.com
games.sanluisobispo.com
arena.gamesforthebrain.com
games.thestar.com
games.fresnobee.com
games.sacbee.com
games.puzzles.ca
```

You have to wait 30 seconds for ads before you play and ad leftovers:
`games.ajc.com`
