### ISSUE TITLE
egybest.org issues

### ISSUE THREAD

**Issue by mimo2004moh** [uBlockOrigin/uAssets#10255]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.egybest.org/movie/ahmed-noterdame-2021`

### Describe the issue

When ublock enabled, the download link not work properly,  and keep opened the same tab every time.
And when disabled, work fine and download tab open normally (vidstream)

### Screenshot(s)

https://user-images.githubusercontent.com/53051408/137935519-7cc2e079-713d-4587-af89-63fe760f9d4c.png
https://user-images.githubusercontent.com/53051408/137935525-751e78dd-37c8-402c-bde5-97645dbba810.png

### Configuration

ublock origin default

**Comment by lain566** [comment]
> [85a05bb](https://github.com/uBlockOrigin/uAssets/commit/85a05bb7364965ccbc4d7869e71ad47f8ec99ea9)

If you disable that filter, the anti-adblock message will appear again.

**Comment by uBlock-user** [comment]
So site is broken ?

**Comment by BasimShadow** [comment]
i have same problem.and i knew what filter is causing that problem.
filter "uBlock filters" when it is enabled, you can't open pop-up (vidstream) to make download.and when it is disabled, all pop-ups appear (vidstream & ads).How can we solve it?

**Comment by Dark-Yox** [comment]
Use the logger to detect which filter is causing your issue and white list it.

**Comment by BasimShadow** [comment]
that filter cause the problem.and if i close it,all ads will appear

**Comment by jsteave** [comment]
having the same issue[.](https://ittutoria.net/)

**Comment by jsteave** [comment]
you[ ](https://helmetadviser.com/best-ventilated-motorcycle-helmet/)are using any VPN for this?

**Comment by jsteave** [comment]
my answer is also the same your site has changed, even if you disable the filter, the buttons will still not work, tested with Firefox

**Comment by mapx-** [comment]
I cannot find an egy page with the issues above
