### ISSUE TITLE
uBlock Origin Stopping Media From Loading on voe.sx

### ISSUE THREAD

**Issue by TheCoderJT** [uBlockOrigin/uAssets#10259]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voe.sx`

### Describe the issue

When I uncheck the first select box under built-in filters **uBlock filters** in the settings, the video will load on the website. However if i check the **uBlock filters** box,  uBlock Origin is blocking the video from loading.

I can't link to the actual video page unfortunately, but its a basic html page with a video player that loads a video. they use their own video player and it looks like there is a bunch of cloudflare scripts that execute when loading the page. Maybe in your uBlock filters list its blocking that...idk 

### Screenshot(s)

![uBlockUnchecked](https://user-images.githubusercontent.com/13303466/138048692-f73407d6-cbc1-4c8a-8979-c8e0043661f0.png)
![uBlockFiltersChecked](https://user-images.githubusercontent.com/13303466/138048697-bbb749c7-82e6-46c5-84e0-4e267d205554.png)

### Notes

I unchecked all the filters one by one and found that every other filter box seems to not block the video only the first filter under the built-in section of the settings stops the video from loading......

### Configuration

not sure what to put here

**Comment by uBlock-user** [comment]
> I can't link to the actual video page unfortunately, but its a basic html page with a video player that loads a video. 

Without that, an investigation cannot occur.

**Comment by uBlock-user** [comment]
tested at `https://voe.sx/2xk9tk38gs4s` works fine.

@TheCoderJT Test on default settings/lists with all other extensions disabled.

**Comment by TheCoderJT** [comment]
> 
> 
> > TheCoderJT :
> > ### Prerequisites
> > ### I tried to reproduce the issue when...
> > ```
> > * [x]  uBO with default lists/settings
> > ```
> 
> Really? [#10238 (comment)](https://github.com/uBlockOrigin/uAssets/issues/10238#issuecomment-945119659) It's your additional filter lists you manually enabled triggering breakage, specifically this one: AdGuard Base, with this list enabled I can reproduce:
> 
>     * the breakage, on Firefox (but not on Opera)
> 
>     * the odd repair: leaving AdGuard Base enabled + disabling uBlock Filters instead, fixes the breakage

I'm on firefox and I have every filter box checked except ublock filters once i check ublock filters all the videos on from voe won't load.

**Comment by TheCoderJT** [comment]
> 
> 
> > I have every filter box checked except ublock filters once i check ublock filters
> 
> Stick to default settings/lists.

But you all don't understand the videos load even with all the boxes checked except ublock filters box? so that means there is something wrong with that filter list.

**Comment by okiehsch** [comment]
> I'm on firefox and I have every filter box checked except ublock filters once i check ublock filters all the videos on from voe won't load.

If you uncheck `Adguard Base` instead of ublock filters it should work too.

**Comment by TheCoderJT** [comment]
> 
> 
> > I'm on firefox and I have every filter box checked except ublock filters once i check ublock filters all the videos on from voe won't load.
> 
> If you uncheck `Adguard Base` instead of ublock filters it should work too.

So your saying uncheck adguard and check ublock filters?

**Comment by felix-22** [comment]
There is many `+js` filters in both AG and uBO filters, most likely they interfere with each other:
![eee](https://user-images.githubusercontent.com/75935068/138059741-3dff1800-5ea7-42da-bf0b-dad7ad31b347.png)

<tr>

> TheCoderJT  :  I'm on firefox and I have every filter box checked except ublock filters

Then why did you marked?:
> ### I tried to reproduce the issue when...
>     * [x]  uBO with default lists/settings

**Comment by okiehsch** [comment]
> Disabling that filter unleashes about:blank popups

With Adguard Base enabled?

**Comment by TheCoderJT** [comment]
> 
> 
> It is definitely the aost filter. Adding `voe.sx#@#+js(aost, EventTarget.prototype.addEventListener, stackDepth:3)` fixes the breakage on my end. I am not going to try to find out what filter in Adguard causes the breakage with both lists enabled. Bottom line we don't fix such issues, i.e. issue with a none default setup.
> 
> @TheCoderJT If you want to keep your setup add `voe.sx#@#+js(aost, EventTarget.prototype.addEventListener, stackDepth:3)` to your filter list.

That worked! thanks this is exactly what i was looking for and sorry if i make the wrong ticket just didn't know which one to create.

**Comment by gorhill** [comment]
> sorry if i make the wrong ticket just didn't know which one to create.

> - [x]  uBO with default lists/settings

Be sure you answer truthfully next time, we are all volunteers here and misleading people with bad information waste a lot of the volunteers' contributed free time.
