### ISSUE TITLE
crackle.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1025]
### URL(s) where the issue occurs

`https://www.crackle.com/just-go-with-it/2504129`

### Describe the issue

Video does not load. I have a partial working solution: 
```
@@||crackle.com/vendor/AdManager.js$script,first-party
@@||secure-dcr.imrworldwide.com/novms/js/$script,domain=crackle.com
```
However, the video gets stuck again when going to next video (See https://github.com/jspenguin2017/uBlockProtector/issues/622#issuecomment-346904369 )
When one video finishes, it should switch to next one automatically, but it gets stuck instead. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34076157-008c00c6-e29a-11e7-94ca-2bf627dbab8f.png)

### Versions

- Browser/version: ff 57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

Related: https://github.com/jspenguin2017/uBlockProtector/issues/622

**Comment by mapx-** [comment]
"page not found"

**Comment by jspenguin2017** [comment]
It "works" for me (I have Nano Defender activated), maybe Geo Lock? 
![image](https://user-images.githubusercontent.com/7283682/34132258-3960f4a6-e40c-11e7-99a1-6766bbf00ace.png)

**Comment by mapx-** [comment]
what if you replace the second filter by
`@@||imrworldwide.com/novms/js/$script,domain=crackle.com`

**Comment by jspenguin2017** [comment]
Nope, still stuck when auto-switching to next video.

**Comment by gorhill** [comment]
How about:

    ||fwlive.crackle.com/ad/$script,redirect=noopjs,domain=crackle.com

**Comment by jspenguin2017** [comment]
Nope. 
I guess I should try `a.dynamicServer` as lain566 suggested.

**Comment by jspenguin2017** [comment]
Website obsolete.

**Comment by Mennaruuk** [comment]
Crackle back at it:
![image](https://user-images.githubusercontent.com/52135169/107113496-4aa3d500-682d-11eb-8445-caac1093e406.png)
None of the filters above worked. Also, is it sonycrackle.com or crackle.com?

**Comment by mapx-** [comment]
Tested a random video: `https://www.crackle.com/watch/6997` no issues on my end

**Comment by Mennaruuk** [comment]
So do default settings work with crackle.com? Or do I need to check a particular filter list?

**Comment by lain566** [comment]
I can reproduce anti-adblock, this filter works for me
`@@||crackle.com^$cname`

@Mennaruuk Does this work for you?

**Comment by Mennaruuk** [comment]
Works like a lucky charm, thank you!!
