### ISSUE TITLE
Filters not being applied on https://www.buzzfeed.com/

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#1026]
`https://www.buzzfeed.com/chrisgeidner/the-trump-campaign-claims-a-federal-office-illegally-turned`

### Describe the issue

The following; ###mod-newsletter-signup-1 and ###mod-newsletter-signup-2 filters in Easylist aren't being applied, its like it had a $generichide element (which it doesn't).

Manually adding; works fine. But should be taken care of in exisitng filters

buzzfeed.com###mod-newsletter-signup-2
buzzfeed.com###mod-newsletter-signup-1

Trying to block the blue Newsletter div elements (right, and bottom).

Using Easylist, Easyprivacy, Annoyances.

ABP hides the elements without issue.

**Comment by mapx-** [comment]
It seems only the generic `div rules` has this behaviour. 
Tested a couple of other pages, no issues.
@gorhill

**Comment by gorhill** [comment]
Duplicate of <https://github.com/gorhill/uBlock/issues/1885>.

**Comment by ryanbr** [comment]
Okay, made a specific filter for uBo.

https://github.com/easylist/easylist/commit/1edfbfd478761268d49fe449661c27b81b4278da

**Comment by gotitbro** [comment]
@ryanbr Interesting you added a filter specific to uBO in EasyList. From what I have known EasyList has always been ABP focused.

**Comment by SMed79** [comment]
> EasyList has always been ABP focused

Not sure... https://github.com/easylist/easylist/commit/2c64810cf29493560a33cb

**Comment by gotitbro** [comment]
@SMed79 So what is the position here then. No uBO specific filter syntax have been added to EasyList but ABP ones have like `:-abp-has`.

And taking into account other blockers only uBO related filters have been added to EasyList. Looks like EasyList still only follows the ABP filter syntax but for some reason uBO filters are also being added @ryanbr.
