### ISSUE TITLE
Try to remove ads from this page

### ISSUE THREAD

**Issue by lol33214** [uBlockOrigin/uAssets#1027]
video.gjirafa.com in videos and in site also

**Comment by mapx-** [comment]
test these filters

```
||gjirafa.com/api/media/VideoR/*.mp4$media,redirect=noopmp3-0.1s
gjirafa.com##iframe
```

**Comment by gotitbro** [comment]
@mapx- The filters don't work the ads still get loaded.

Is there any Albanian filter list or lists that cover south east Europe Siberia, Croatia etc.?

**Comment by Hrxn** [comment]
Siberia?

**Comment by mapx-** [comment]
```
||gjirafa.com/api/media/VideoR/*.mp4$media,redirect=noopmp3-0.1s
gjirafa.com##iframe
||gjirafa.com/api/media/VideoR/$xmlhttprequest
gjirafa.com##[id^=an-holder]
```

**Comment by mapx-** [comment]
test in FF version >= 57 (for video ads)

`gjirafa.com##^script:has-text(urls)`

**Comment by elbasan** [comment]
`gjirafa.com##iframe` seems to block google captcha, I can't login

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/dw12ku/gjirafa_video_ads/

**Comment by okiehsch** [comment]
`video.gjirafa.com##+js(json-prune, 0)`
but I am not sure if that breaks something.

**Comment by uBlock-user** [comment]
Where did you find the json file ?

**Comment by mapx-** [comment]
(reddit) OP  deleted the thread

**Comment by uBlock-user** [comment]
@mapx- url -- `https://video.gjirafa.com/schengen-visa-36-lulemall`
