### ISSUE TITLE
happy-hack.ru

### ISSUE THREAD

**Issue by zummuz** [uBlockOrigin/uAssets#103]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://happy-hack.ru/

### Describe the issue

Users with adblockers are blocked on the site. They persistently change triggering script name in the way it would be blocked by a generic network rule.
There were 8 exclusion rules in two weeks (https://hg.adblockplus.org/ruadlist/)

### Screenshot(s)
Default lists +  RUS: BitBlock +  RUS: RU AdList:
![screenshot from 2016-08-13 12-22-51](https://cloud.githubusercontent.com/assets/13698274/17644442/86addf4a-618f-11e6-89c6-c3453ecea488.png)

Default lists +  RUS: BitBlock +  RUS: RU AdList +  RUS: Adguard Russian Filter:
![screenshot from 2016-08-13 19-58-37](https://cloud.githubusercontent.com/assets/13698274/17644508/df85dfcc-6190-11e6-9b5e-3d6f0053ec0d.png)

### Versions

- Browser/version: chromium 51.0.2704.79
- uBlock Origin version: 1.8.4

### Settings

- default + russian lists

### Notes

`happy-hack.ru##table[id^='blockblock']` (they change last bits of id)
`happy-hack.ru###blockblockY1:style(visibility:visible !important; display:block !important)` (doesn't seem like they change that span's id)
I reckon the site's admins monitor RU Adlist, so the filters above are fine if are placed in the uBlock's list. Or the nodes can be specified with xpath() and has() at once so it would be harder to avoid?
Now its `http://happy-hack.ru/1/Teaser.js` request that triggers the blockage

**Comment by gorhill** [comment]
Does the following work without bad side-effects?

    happy-hack.ru##script:inject(noeval.js)

**Comment by zummuz** [comment]
Hm, it doesn't work for me, does nothing

**Comment by gorhill** [comment]
Is cosmetic filtering disabled one way or another (including through `generichide`)?

**Comment by zummuz** [comment]
I don't understand your question. There is a rule `happy-hack.ru##[id^="aswift_"]` in the logger
Do you use RU Adlist for the test? Without it the site works.

**Comment by gorhill** [comment]
No I was not using RU Adlist, since I could reproduce the issue. 

There is `@@||happy-hack.ru^$elemhide` in RU Adlist. This is issue <https://github.com/gorhill/uBlock/issues/1891>.

This is quite a bad issue, as it prevents uBO from injecting its anti-block code wherever `elemhide` or `generichide` is used, or wherever someone disable cosmetic filtering for a site. Might account for why some users still report being blocked on Wired.

I have the fix currently, I am intensively just code reviewing all the changes.

Meanwhile, maybe try `happy-hack.ru##body > *:matches-css(position: fixed;)`. This one fixes the symptom, while the script injection one fixes the disease.

**Comment by gorhill** [comment]
Ok, blocking `http://happy-hack.ru/1/Teaser.js` causes `happy-hack.ru##script:inject(noeval.js)` to not work. Try this:

    happy-hack.ru##script:inject(noeval.js)
    @@||happy-hack.ru/1/Teaser.js$script,first-party
    ||pagead2.googlesyndication.com^$script,important,domain=happy-hack.ru
    ||google.com/ads/popudner/banner.jpg$image,important,domain=happy-hack.ru

I added block filters to bypass RU Adlist exception filters for `google.com` and `googlesyndication.com`.

**Comment by zummuz** [comment]
To ensure nothing affects it, I've reseted uBlock, additionally checked only RUS Adlist, added
`happy-hack.ru##body > *:matches-css(position: fixed;)`
`happy-hack.ru##script:inject(noeval.js)`
and still the same - page is blocked

**Comment by gorhill** [comment]
Try [what I posted here](https://github.com/uBlockOrigin/uAssets/issues/103#issuecomment-239636876).

**Comment by zummuz** [comment]
Yes, [this](https://github.com/uBlockOrigin/uAssets/issues/103#issuecomment-239636876) works fine

**Comment by zummuz** [comment]
Okay, the site has changed the trigger to `http://500tv.ru/1/popunder.js` and it doesn't work again.   
I have checked the previous filters from RU Adlist - the trigger has been loaded form `7-link.ru` before they started to use their own domain, so they also change from where the script is loading.  
Looks like suggested filters still work:
`happy-hack.ru##table[id^='blockblock']`
` happy-hack.ru###blockblockY1:style(visibility:visible !important; display:block !important)`

**Comment by zummuz** [comment]
Hi
The site has changed `#blockblockY1` to `#blockblockL9`, maybe they found out there are special filters in uBlock, because they haven't changed it for at least 3 weeks (idk about earlier).

For now
`happy-hack.ru###blockblockY1:style(visibility:visible !important; display:block !important)`
can be swapped with
`happy-hack.ru##span[id^='blockblock']:style(visibility:visible !important; display:block !important)`
to see if its spontaneous change of the id's postfix, or if they are going to avoid the blockage

**Comment by KiLL4FuNK** [comment]
`https://happy-hack.ru/book/14941-5-knig-dlya-nachinayuschego-hakera.html`

Anti-Adblock

**Comment by mapx-** [comment]
it's ok with ruadlist (even without, but ugly page)
