### ISSUE TITLE
cnbc.com

### ISSUE THREAD

**Issue by Sal2134** [uBlockOrigin/uAssets#10300]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cnbc.com/`

### Describe the issue

I made no changes in uBO but the ticker at the top of cnbc.com showing quotes for indexes stopped working yesterday in firefox and chrome with uBO activated and it works fine with uBO off. 

### Notes

Turned uBO on and off

### Configuration

What config?

**Comment by stephenhawk8054** [comment]
Scroll down to `CNBC TV` section, the `Watch Live` section doesn't appear.

URL:
`https://www.cnbc.com/world/?region=world`

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148710565-cc3aed8a-e6fe-4cbb-b259-88bb9f3f7a4a.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148710583-757e8a7e-8417-4be7-8d69-85f658b433fb.png)

</details>

<details>
<summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77652
  cosmetic: 40417
  scriptlet: 16388
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-143, 30m
    ublock-badware: 3662-1, 30m
    ublock-privacy: 183-0, 30m
    ublock-abuse: 76-0, 30m
    ublock-unbreak: 1726-0, 30m
    easylist: 62809-459, 30m
    easyprivacy: 26611-490, 30m
    urlhaus-1: 6904-0, 30m
    plowe-0: 3685-2, 30m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 249 ms (selfie)
popupPanel: 
  blocked: 33
```
</details>

Proposed filter:

`@@||mparticle.com/js/v2/*/mparticle.js$script,domain=cnbc.com`

**Comment by mapx-** [comment]
@ryanbr
