### ISSUE TITLE
freeapkgame.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1030]
URL(s) where the issue occurs

http://www.freeapkgame.net/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5198976e1dc9c62306719108d2345e7d402ccb43

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
