### ISSUE TITLE
uskip.me [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1031]
URL(s) where the issue occurs

http://uskip.me/MxEPAA

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up @mapx-

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by KiLL4FuNK** [comment]
Fake Button
