### ISSUE TITLE
uploadbank.com [Anti-Adblock]

### ISSUE THREAD

**Issue by SSS-mode** [uBlockOrigin/uAssets#10336]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.uploadbank.com/3g556t4qtwf5`

### Describe the issue

It has a newly updated Anti-Adblocker v1.23, and makes the old filter (I tried both default and with annoyance filter).
Brave's own adblocker is off and without other extensions.

### uBlock Origin version

1.38.6

### Browser name and version

Brave 1.31.87

### Settings

Nothing changed

**Comment by ghajini** [comment]
Firefox desktop stable/Firefox android stable, 
ublock origin 1.39

Antiadblock
`https://www.uploadbank.com/wdxx40hx9g0e`

ref link `moviesbaba.life`
this work
`uploadbank.com#@#.AdSense`

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/issues/10336#issuecomment-986253008
@gorhill This must be bug - a specific-generic filter `*##.AdSense` (mobile only) is not disabled by `@@||uploadbank.com^$ghide`

**Comment by Yuki2718** [comment]
Now I'll remove `*##.AdSense`. In most cases it only hides very small placeholder.

**Comment by ghajini** [comment]
> This must be bug - a specific-generic filter `*##.AdSense` (mobile only) is not disabled by `@@||uploadbank.com^$ghide`
 makes sense

**Comment by uBlock-user** [comment]
No need to rmeove that filter, `uploadbank.com##+js(acis, decodeURIComponent, return"%")` works fine.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/023bae909adf62eb3871a2bb227fc6cc75566325

**Comment by Yuki2718** [comment]
> No need to remove that filter,

I expect this to be bait on other sites too, so probably its detriment outweighs.
