### ISSUE TITLE
Blank space in photopea.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10337]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.photopea.com/`

### Describe the issue

There's a blank vertical space at the right side of web page. It's used just for ads. Hope there would be a way to optimize the whole page for it.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/139178281-8e5d4e1e-a992-43c7-8211-4eeccfe21f5b.png)

![image](https://user-images.githubusercontent.com/66517106/139178317-938a0963-cb3c-4848-ad0a-e0a54cfe292d.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

No change

**Comment by MasterKia** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13094#issuecomment-1120129347
