### ISSUE TITLE
animeunity detects ublock-origin

### ISSUE THREAD

**Issue by Mass1milian0** [uBlockOrigin/uAssets#10341]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`www.animeunity.tv`
any anime, but a quick example can be seen here:
`https://www.animeunity.tv/anime/3257-demon-slayer-kimetsu-no-yaiba-entertainment-district-arc/54386`

### Describe the issue

Streaming says: disable your adblock to continue watching the stream, probably this isn't the first time happening, as far as i saw, animeunity has a reputation for anti-adblockers

### Screenshot(s)

![Immagine 2021-10-28 234715](https://user-images.githubusercontent.com/20503622/139346604-23ffe092-48d9-48e7-b240-dd80e3c53097.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

a LOT, but mainly:
added nanodefender
enabled some third party filter for italian websites and spanish

and not much else

### Notes

i've noticed that when ublock is disabled this html elements appear
![immagine](https://user-images.githubusercontent.com/20503622/139346855-75b13d8f-0185-4471-8100-81528c538232.png)
but they disappear once ublock is turned on again, i suspect they are the culprits of the detections

**Comment by LikesHisComputer** [comment]
Should `||nsqedcmktda.top^` be added?

@mapx- @ryanbr

**Comment by ShinyFabio** [comment]
That filter doesn't work for me. 
Chrome 96.0.4664.110
Ublock with default settings 1.39.2

**Comment by gorhill** [comment]
Works fine here. Are your filter lists up to date? Are you using another blocker beside uBO? Other extensions? (for example some VPN extensions integrate a blocker)

**Comment by ShinyFabio** [comment]
Now it works, I don't know why. Was not enough close and reopen chrome? Did I have to restart windows?
