### ISSUE TITLE
http://ww7.shounen-ai.net/ detects adblock

### ISSUE THREAD

**Issue by Poofey** [uBlockOrigin/uAssets#10359]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
http://ww7.shounen-ai.net/
http://starrysky.shounen-ai.net/

```
### Describe the issue

Opening the link will just display 'Ad block detected, please disable your ad blocker and reload the page'.

### uBlock Origin version

1.38.6 and 1.38.7b11

### Browser name and version

Version 95.0.4638.69 (Official Build) (64-bit)

### Settings

I have these rules but they make no difference with or without 
no-large-media: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop

**Comment by uBlock-user** [comment]
Dead site, parked domain.

**Comment by krystian3w** [comment]
Possible test in my filters pane:

`/px.gif?$image,redirect-rule=1x1.gif`

as nobody add in `unbreak.txt` these:

`/px.gif?$image,redirect-rule=1x1.gif,bafiler`

or

`/px.gif?$image,redirect-rule=none:99`
