### ISSUE TITLE
whatfontis.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#10364]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.whatfontis.com/?s2c`

### Describe the issue

Anti Adblock banner (after i uploaded the image)

### Screenshot(s)

<img width="518" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/139596283-9291a458-dba2-43ca-8b21-a37f0d224275.PNG">

### uBlock Origin version

1.38.6

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock Origin Annoyances

**Comment by okiehsch** [comment]
It's already fixed in annoyances. 
I will move that filter to the main list.

**Comment by uBlock-user** [comment]
> Enabled uBlock Origin Annoyances


I can't reproduce with that list Enabled.

**Comment by JobcenterTycoon** [comment]
@okiehsch not needed, annoyances was disabled i don’t know why

**Comment by okiehsch** [comment]
Isn't that more than an annoyance? 
I first thought the site was blocked completely until I noticed that I can scroll down.
![image](https://user-images.githubusercontent.com/16838044/139597072-9689d97f-9e16-4546-b5f4-0684339b0fd5.png)

**Comment by JobcenterTycoon** [comment]
Its only a annoyance i tested it

**Comment by okiehsch** [comment]
OK.
