### ISSUE TITLE
Anti-adblock in asianbookie.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10366]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.asianbookie.com/`

### Describe the issue

Anti-adblock overlay after a few seconds

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/139608525-4d282ccd-180e-42a4-8966-6087ab7c4c01.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

No change

### Notes

Proposed filter:

`asianbookie.com##+js(acis, document.getElementById, displayMessage)`

**Comment by Mennaruuk** [comment]
I can reproduce.

**Comment by stephenhawk8054** [comment]
Another site with the same anti-adblock script.

URL: `https://cotravinh.blogspot.com/`

![image](https://user-images.githubusercontent.com/66517106/143667433-971b121a-033e-4d86-9027-90b602046bb2.png)

Page loads a bit slow, so you might need to refresh multiple times. An anti-adblock appears after page loaded.

Proposed filter:

`cotravinh.blogspot.com##+js(acis, document.addEventListener, nextFunction)`
