### ISSUE TITLE
new.lewd.ninja

### ISSUE THREAD

**Issue by sapebo1696** [uBlockOrigin/uAssets#10362]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `https://new.lewd.ninja`

### Describe the issue

Any links section on any game for example says adblock detected

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

- none

**Comment by uBlock-user** [comment]
force update ublock filters list, fixed few days ago.
