### ISSUE TITLE
Oyster search suggestions/dropdowns not working

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#10365]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.oyster.com/`

### Describe the issue

When you type a location in the search box, there are no suggestions. Also, when you try to pick a date/number of rooms/guests, no drop-down menu shows up. This effectively means you can't search for hotels.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

N/A

**Comment by mapx-** [comment]
add
`@@||oyster.com/wp-content/plugins/smartertravel-shared/assets/js/tracking.min.js$script,1p`

@ryanbr
