### ISSUE TITLE
chiaanime.co [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1037]
URL(s) where the issue occurs

http://chiaanime.co/Watch/169688/rwby-volume-5-201-amp/episode-10

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
add also
`||bidgears.com^`

**Comment by KiLL4FuNK** [comment]
ads @mapx-
