### ISSUE TITLE
data.amplitude.com and many other *.amplitude.com sites are being blocked when running uBlock

### ISSUE THREAD

**Issue by rctbusk** [uBlockOrigin/uAssets#10388]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`analytics.amplitude.com`
`data.amplitude.com`
`discourse.amplitude.com`

### Describe the issue

In an attempt to block our tracking apis, uBlock is also blocking now our main products and our websites are not working. Hoping to get an exception added so that our customers can still use our products and have ublock enabled.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/47338314/140229800-696e722c-4549-4c5a-bcb3-78d5c16a6652.png)

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Chrome - 95.0.4638.69

### Settings

None

### Notes

Looks like this is coming from an all encompassing rule in Pete Lowe's Ad Server and Tracking list -  `amplitude.com`.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951814995

New policy to counter redirection based tracking. Webpages of advertising or tracking companies will stay strict blocked. If you need to access these pages you can whitelist them.
