### ISSUE TITLE
romaniatv.net

### ISSUE THREAD

**Issue by agam3r** [uBlockOrigin/uAssets#10382]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.romaniatv.net/jandarmeria-bucuresti-a-aplicat-40-de-sanctiuni-in-valoare-de-50-000-de-lei-pentru-participantii-la-protestul-anti-vaccinare-din-piata-universitatii_5929588.html`

### Describe the issue

anti adb

### uBlock Origin version

1.38.6

### Browser name and version

Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)

### Settings

.

**Comment by LikesHisComputer** [comment]
should there be a global addressing?

encountered similar anti adb on `https://www.stirilekanald.ro/afacerile-la-sate-atrag-bani-europeni-20186641`

**Comment by BottledSoda** [comment]
Similar antiadb reported on https://github.com/uBlockOrigin/uAssets/issues/11501

**Comment by sugarfreesweetener** [comment]
@mapx- Should filter be moved to `road-block lite`?

**Comment by mapx-** [comment]
https://github.com/tcptomato/ROad-Block/commit/0a8e39281db8a8e907255e7cdcbaea8406347d12

**Comment by pilis1** [comment]
I notice that if uBO is on, on the website, there are blank spaces that remain from the ads that were blocked.

![Image](https://github.com/user-attachments/assets/06aa74f9-fc68-4bd1-bffd-6af2196d2fa4)

When turning uBO off, the spaces get filled with ads:

![Image](https://github.com/user-attachments/assets/8db8231b-b0a2-4fbe-b160-70794be389af)

I did test this on the following link: https://www.romaniatv.net/un-supermarket-lidl-risca-sa-fie-inchis-ce-nereguli-au-gasit-autoritatile-in-magazinul-retailerului-german_8909464.html

**Comment by mapx-** [comment]
updated the romanian list
https://github.com/tcptomato/ROad-Block/commit/e7f9c3fbf5f7f47c9e138e1e6d15f8e9cd944525
