### ISSUE TITLE
mediafax.ro

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#10386]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.mediafax.ro/`

### Describe the issue

ad

### Screenshot(s)

![image](https://user-images.githubusercontent.com/93623745/140179923-41443dc7-b422-44c4-8765-4c914fbaa11b.png)

### uBlock Origin version

1.38.6

### Browser name and version

Google Chrome 95.0.4638.69 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/93623745/140180015-063a1c0d-4767-4524-9a5a-a20fbcf18210.png)

**Comment by felix-22** [comment]
There is already a thread for `mediafax.ro`: https://github.com/uBlockOrigin/uAssets/issues/9345

**Comment by mapx-** [comment]
report here
https://github.com/tcptomato/ROad-Block

**Comment by advertblocker** [comment]
`https://mediafax.ro/` => anti-copy (ctrl + c => ctrl + v)

**Comment by mapx-** [comment]
it's working fine FF / chrome

**Comment by advertblocker** [comment]
drag accross some text, copy, then see what was actually copied

**Comment by advertblocker** [comment]
```
mediafax.ro##+js(aeld, copy)
```
