### ISSUE TITLE
mangatail.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1038]
URL(s) where the issue occurs

http://www.mangatail.com/chapter/duke-death-and-his-black-maid-1

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
Alternative fix https://forums.lanik.us/viewtopic.php?f=62&t=39378
