### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1039]
### URL(s) where the issue occurs
`https://player.pl/programy-online/milionerzy-odcinki,5045/odcinek-113,S02E113,86695`

### Describe the issue

I can't play the movie, because uBlock is detected.

### Screenshot(s)

![screenshot_20171217_174953](https://user-images.githubusercontent.com/19818572/34081780-d0348a6a-e352-11e7-9d4c-5823048711d8.png)

### Versions

- Browser/version: Waterfox 56.0 (Firefox 56.0.2)
- uBlock Origin version: 1.14.22

### Settings

- https://gist.github.com/hawkeye116477/32fb4ffe0e43b8295282662485cfec18

**Comment by mapx-** [comment]
test these filters
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.pl
@@||tvn.adocean.pl/ad.xml?$xmlhttprequest,domain=player.pl
@@/TVN-Adserver/*.mp4$xmlhttprequest,domain=player.pl
@@||s1-player5.cdntvn.pl/adscript.js$xmlhttprequest,domain=player.pl
```

**Comment by hawkeye116477** [comment]
@mapx- Unfortunately still not work.

**Comment by mapx-** [comment]
I slightly modified the filters above, try again.

**Comment by hawkeye116477** [comment]
@mapx- Thanks, now works correct :smile: .
