### ISSUE TITLE
moviesjoy.to

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10393]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://moviesjoy.to/watch-movie/army-of-thieves-73678.4741057`

### Describe the issue

Manga ad under the video.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140261857-ba9785ed-a5c6-4095-bd54-8e40cb462645.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

N/A

### Notes

Thank you very much.

I propose:

`moviesjoy.to###gift-middle`

**Comment by uBlock-user** [comment]
Report this site at https://github.com/easylist/easylist/issues

@ryanbr
