### ISSUE TITLE
kwro.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10390]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://kwro.com`

### Describe the issue

Site detects content blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140260531-49971e30-36fa-4053-b248-222638b37cfa.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 93.0

### Settings

N/A

### Notes

Thanks

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/07c64cdd25ac13c950242d32200996da3f6848f2
