### ISSUE TITLE
eurosport.de

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#10395]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.eurosport.de/fussball/champions-league/2021-2022/borussia-dortmund-harter-herbst-bvb-gegen-leipzig-bayern-sporting-wolfsburg-ohne-haaland_sto8614100/story.shtml`

### Describe the issue

ads on the right side

### Screenshot(s)

![Screenshot 2021-11-04 at 13-39-35 BVB Borussia Dortmund droht nach der Niederlage gegen Ajax Amsterdam ein harter Herbst](https://user-images.githubusercontent.com/81616288/140316142-2ac2257e-8ae8-40d5-b564-0a6d9ee9859e.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0 (64-Bit)

### Settings

no change

**Comment by felix-22** [comment]
With AdGuard Base Filter enabled the ads are gone, the AdGuard filter is: `eurosport.*##.AdPlacementContainer`, since it doesn't require uBO enhanced syntax, should be reported to [EasyList Germany tracker](https://github.com/easylist/easylistgermany/issues) instead.

**Comment by mapx-** [comment]
`eurosport.*##.AdPlacementContainer`

@ryanbr
