### ISSUE TITLE
Anti-adblock in threezly.com, truyenbanquyen.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10397]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://threezly.com/
https://truyenbanquyen.com
```

### Describe the issue

Anti-adblock message after the page loaded

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/140454619-45f0bcd1-22f1-4a37-9a60-bf2c5dde6a3a.png)

![image](https://user-images.githubusercontent.com/66517106/140455433-21ee985b-bcc1-44ff-88c4-94561693933b.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

Both websites use the same inline script for anti-adblock. If I block this function:

`threezly.com,truyenbanquyen.com##+js(set, ai_run_scripts, noopFunc)`

then the anti-adblock disappears, but the `load more` function in `threezly` seems broken.

**Comment by felix-22** [comment]
Several more:
`freshiptv.com`
`mobiletrip.net`
`freeiphone.fr`
`ibooks.to`

**Comment by stephenhawk8054** [comment]
Another website with the same anti-adblock: `https://konosubamanga.com/`

![image](https://user-images.githubusercontent.com/66517106/140682481-e97fb8f1-7ba9-4eb9-9429-1efc55e78799.png)

After removing the previous filter and add new one from the commit, it works

```
konosubamanga.com#@#+js(aopw, ai_front)
konosubamanga.com##+js(acis, decodeURIComponent, ai_)
```

However, wait about 30 seconds and a new anti-adblock appears

![image](https://user-images.githubusercontent.com/66517106/140682881-a6fcb6cb-82d0-405f-a590-f5b7a4e8a7ae.png)

An `eval` inline script causes it. Proposed filter:

`konosubamanga.com##+js(noeval)`

**Comment by stephenhawk8054** [comment]
Another website with the same anti-adblock:
`https://www.wikirise.com/en/hma-pro-vpn-5-1-259-0-crack-with-license-key-free-download/`

![image](https://user-images.githubusercontent.com/66517106/141663702-86f20f9a-00f2-4dea-8bba-04fb71099941.png)

Proposed filter:

`wikirise.com##+js(acis, decodeURIComponent, ai_)`

**Comment by stephenhawk8054** [comment]
Another site with the same anti-adblock.
`https://mobitool.net/`

![image](https://user-images.githubusercontent.com/66517106/142597254-28fe36db-65f2-4ffc-b6b6-6973705d5ee6.png)

Proposed filter:

`mobitool.net##+js(acis, decodeURIComponent, ai_)`

**Comment by stephenhawk8054** [comment]
Another site with the same anti-adblock script, although it looks a bit different visually:
`https://thecustomrom.com/`

![image](https://user-images.githubusercontent.com/66517106/142723143-6dc17d2f-b633-42a5-9069-9c00c88e9a71.png)

Proposed filter:

`thecustomrom.com##+js(acis, decodeURIComponent, ai_)`

**Comment by stephenhawk8054** [comment]
Another site with the same anti-adblock script:

URL: `https://udemydl.com/2021/11/27/free-84-99-the-empathy-principle-emotional-intelligence-eiq-2/`

![image](https://user-images.githubusercontent.com/66517106/143665581-353ba4b3-9500-41da-98dc-0492c7011d47.png)

Also, there are ads inside the site and a script calling `googlesyndication` every 100ms. Proposed filters:

```
udemydl.com##+js(acis, decodeURIComponent, ai_)
udemydl.com##+js(aopr, Request)
udemydl.com##.lazyimages
udemydl.com##[href^="https://s.click.aliexpress.com"]
udemydl.com##.masonry_grid_fullwidth
||udemydl.com/wp-content/plugins/ad-inserter/*$1p
```
