### ISSUE TITLE
streamarmy.co.uk

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1040]
### URL(s) where the issue occurs

`streamarmy.co.uk`

### Describe the issue
Anti-adblock.
https://github.com/MajkiIT/polish-ads-filter/issues/5135

### Screenshot(s)

![screenshot_20171217_202239](https://user-images.githubusercontent.com/19818572/34082944-0f0a29f6-e368-11e7-9162-55eca577ed47.png)

### Versions

- Browser/version: Waterfox 56.0 / Firefox 56.0.2
- uBlock Origin version: 1.14.22

### Settings

- https://gist.github.com/hawkeye116477/32fb4ffe0e43b8295282662485cfec18

**Comment by SMed79** [comment]
`||streamarmy.co.uk/paycheck.js`

**Comment by gzenio22** [comment]
@SMed79  This reg not working on my ubo 

https://gist.github.com/gzenio22/d89ddc20ad5be08a5309c3af2a5f6ca0

**Comment by hawkeye116477** [comment]
@gzenio22 `@@||streamarmy.co.uk^$generichide`, this was added to uBlock filters, should be working, just update it :smile:.

**Comment by gzenio22** [comment]
Thenkyou @hawkeye116477

**Comment by SMed79** [comment]
@gzenio22 
> This reg not working on my ubo

* https://i.imgur.com/tFxGl4V.mp4
