### ISSUE TITLE
[NSFW] Popup in sexphimhd.net

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10404]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sexphimhd.net/`

### Describe the issue

After the page loaded, click anywhere on the page a few times, a popup appears

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

Looks like an inline script causes it. Proposed filter:

`sexphimhd.net##+js(aopr, D4zz)`

**Comment by stephenhawk8054** [comment]
I think the popup still appears in new Private Window/Incognito session even with the new filter

![image](https://user-images.githubusercontent.com/66517106/140628967-357541ac-b9d0-4880-b446-92f05adad42d.png)

**Comment by stephenhawk8054** [comment]
I think it's solved on homepage, but it still appears on video link.

Process:

1. Go to `https://sexphimhd.net/` in Private Window/Incognito,
2. Click on any videos, now it doesn't show popup any more,
3. But when on the video link, click on video player area, it still shows popup.

![image](https://user-images.githubusercontent.com/66517106/140642137-b54bd60e-343f-4f32-8a0a-919322d9413b.png)

**Comment by mapx-** [comment]
even disabling uBO I get 
**play.playnm.xyz refused to connect.**
