### ISSUE TITLE
Ads in lrepacks.net

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10419]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://lrepacks.net/repaki-sistemnyh-programm/101-wise-care-365-amp-portable.html`

### Describe the issue

Ads at the top right. Sometimes there's also popup when clicking on page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/140687027-a601a321-65f3-464e-82ec-7ecbb4694bc9.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change.

### Notes

Proposed filter:

`||wxrkyfymf.xyz^`

**Comment by uBlock-user** [comment]
Subscribe to russian regional list.
