### ISSUE TITLE
NSFW https://nhentai.net/ (popup)

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#10416]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nhentai.net/`
all nhentai link

### Describe the issue

i don't know this is from when... but previously when i go to this sites... no popup at all...
but few days ago... popup still appear.... 

Tested booth on chrome-firefox pc
and firefox android

all of that three shown popup...
maybe someone can check it

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest and Firefox

### Settings

-

### Notes

on chrome, the popup not always shown, but random... sometimes it appear, and sometimes it not...
maybe if you click/visit the sites 10x...
they appear like... 1-4 times... or less... 
but on firefox mobile... it's appear most of the time... (i already update the addons though)

**Comment by uBlock-user** [comment]
fixed yesterday, force update ublock filters list.
