### ISSUE TITLE
Issue with the "Eni gas e luce" website

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#10412]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://enigaseluce.com/`

### Describe the issue

I could not complete the registration to the website (thus activating my supply) because the website was reporting errors (probably due to blocked JS) and in certain sections it did not allow to show buttons for supply activation.

### Screenshot(s)

I cannot attach screenshots due to the sensitive information present.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No changes.

### Notes

By disabling uBlock Origin, the registration was completed successfully and the missed buttons appeared.

**Comment by uBlock-user** [comment]
> because the website was reporting errors (probably due to blocked JS) and in certain sections it did not allow to show buttons for supply activation.

I see no errors and buttons work as expected. Test on default settings/lists + all other extensions disabled.

**Comment by mapx-** [comment]
No errors on my side, I normally registered a (fake) account

**Comment by fabriziobagala** [comment]
If you try to make a new electricity supply (not a website registration) you will see that at a certain point in the procedure it is no longer possible to continue.

Unfortunately you can only see these problems if you make a real supply ☹️

**Comment by mapx-** [comment]
You should try a new one - if possible - and report here what's blocked (see in the uBO's logger )

**Comment by mapx-** [comment]
for example on this page:
`https://enigaseluce.com/offerta/casa/nuova-fornitura/luce`

I need this exception:

`@@||service.maxymiser.net^$script,domain=enigaseluce.com`

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
@fabriziobagala did you get other broken pages ? look into the browser's history

**Comment by fabriziobagala** [comment]
@mapx- another link is the following https://enigaseluce.com/attivazioni/index.html... after the three dots there is sensitive information

**Comment by mapx-** [comment]
- provide the whole link changing the sensitive info with fake ones
- I guess it's the same issue (I see the exceptions in the logger), what was broken ? a similar box (like that above) too ?

**Comment by fabriziobagala** [comment]
- I cannot remove sensitive data because you would be redirected to a page that does not exist
- The issue in the other page does not concern boxes that do not work but buttons that do not appear
