### ISSUE TITLE
Text only links

### ISSUE THREAD

**Issue by jcubic** [uBlockOrigin/uAssets#10417]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tatromaniak.pl/aktualnosci/kurtka-kurtce-nierowna-jak-wybrac-przeciwdeszczowa-kurtke-ktora-sprawdzi-sie-w-gorach/`

### Describe the issue

If there are advertising links like `this is <a href="ad">something important</a>` the text is not visible because it seems that the extension just use `display: none !important`.

I was supposed to report here since it works fine If I disable the extension for this page. But most likely is the core issue with uBlock.

### Screenshot(s)

![uBlock_02](https://user-images.githubusercontent.com/280241/140654545-4c163d5a-74c8-45f6-b220-28bc84106d35.png)
![uBlock_01](https://user-images.githubusercontent.com/280241/140654548-8c8411a6-ea65-4ff2-8dea-e8194b1a2331.png)

The text is in Polish but the inline text is missing, so you can't read the article.

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Chrome 95.0.4638.54 on Fedora GNU/Linux

### Settings

default settings, I didn't change anything.

**Comment by uBlock-user** [comment]
Ad text blocked by `pl##a[href*="://converti.se/click/"]` in Polish regional list.

@gorhill Should we bother ?

**Comment by gwarser** [comment]
@krystian3w ?

**Comment by gorhill** [comment]
Can't they just remove the `href` attribute?

**Comment by uBlock-user** [comment]
@MajkiIT

**Comment by jcubic** [comment]
Why not `a[href*="://converti.se/click/"] img` and maybe iframe and objects, create a list of things that need to be hidden but not text. There can be other cases where there is an ad link with text.

**Comment by uBlock-user** [comment]
> Why not a[href*="://converti.se/click/"] img and maybe iframe and objects, create a list of things that need to be hidden but not text.

You should report this to the Polish list, so they're made aware of this.

**Comment by jcubic** [comment]
But where is CSS selector defined? Can you point me where to report this? I have no idea what "Polish list" is. Please provide a link.

**Comment by uBlock-user** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by krystian3w** [comment]
Andybody can create PR for MajkiIT, becasue is still busy in real life.

**Comment by gorhill** [comment]
Closing as a filter issue, not to be reported here.

**Comment by gorhill** [comment]
Duh, I thought I was on uBlock-issues.

**Comment by gorhill** [comment]
> But where is CSS selector defined?

The filter is in "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda", click on the eye icon beside it to see the content of the list and search for "converti.se/click".

**Comment by jcubic** [comment]
Thanks, if you can close the issue unless you want to wait for resolving upstream.

**Comment by krystian3w** [comment]
Fixed: https://github.com/MajkiIT/polish-ads-filter/commit/c69b87ed0de7afd2d546ba43e65ba8b30ff3f9b4#diff-eab2aaf469314f57267f6f71855a766738837ca60234d6105317854abe61152cR244
