### ISSUE TITLE
Facebook sponsored stories using ::after { content:"Gesponsert" }

### ISSUE THREAD

**Issue by djkrose** [uBlockOrigin/uAssets#1042]
### URL(s) where the issue occurs

https://www.facebook.com/
Logged in, Language = German

### Describe the issue

Facebook sponsored stories reappear as if uBlock Origin was deactivated.

### Screenshot(s)

![Sponsored](https://abload.de/img/2017-12-1809_51_29-faa2s7e.png)

### Versions

- Browser/version: Google Chrome v63
- uBlock Origin version: 1.14.22

### Filter lists active:

- All uBlock filters
- EasyList
- EasyList Germany

### Notes

Facebook started to conceal their sponsored story tag ("Gesponsert" in German) by putting it into css using `::after { content:"Gesponsert" }`. This defeats current filters that use contains() and alike.

![Code](https://abload.de/img/2017-12-1809_57_26-fanusya.png)

### Suggested Fix

Works for me:
```
www.facebook.com##div[role="article"]:if(a:matches-css-after(content:"Gesponsert"))
```

Probably needs more languages to fit all.
Or should this better be reported to EasyList German? Are they accepting uBlock-specific filter syntax?

**Comment by mapx-** [comment]
Does work for you:
`facebook.com##[id^="hyperfeed_story_id_"]:if([id^="feed_subtitle_"] a[href]:matches-css-after(content:/Gesponsort/))`

?

**Comment by djkrose** [comment]
You got a typo there. Correct: Gespons**e**rt with "e", not "o".
If fixed then yes, it works for me.

**Comment by djkrose** [comment]
I just saw I had the typo too at some places. Fixed it in the original issue.

**Comment by gorhill** [comment]
I merged the new filter with the existing one:
https://github.com/uBlockOrigin/uAssets/commit/538dfb690db7ccdaf090b65e115a38f8a89520d2

Is the older procedural filter still needed?

    facebook.com##div[id^="hyperfeed_story_id_"]:if(a:has-text(/Chartered|Sponsored/))

These procedural filters are expensive, the lesser the better.

**Comment by djkrose** [comment]
At least for my facebook feed I don't see :has-text(..) applying anymore.
Vote for removal.
