### ISSUE TITLE
Review edit not working on play.google.com

### ISSUE THREAD

**Issue by momala454** [uBlockOrigin/uAssets#10423]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://play.google.com/store/apps/details?id=com.zynga.farmville3`

### Describe the issue

Leave a review on the app.
Then click on the edit button of your review.
An hidden recatcha is blocked and prevent the edit form to appear

### Screenshot(s)

![image](https://user-images.githubusercontent.com/83005/140739647-dc253f72-22c4-4951-a3cf-3d49af72a6f8.png)

### uBlock Origin version

1.38.6

### Browser name and version

firefox 94.0.1

### Settings

i have also easylist cookie installed and ublock filters annoyances

**Comment by uBlock-user** [comment]
Happens after I disable uBO too, site issue with Firefox.

**Comment by uBlock-user** [comment]
Works fine on Chrome.

**Comment by momala454** [comment]
strange, it worked after i whitelisted the website, but now it doesn't work anymore

**Comment by uBlock-user** [comment]
Site is not compatible with Firefox.
