### ISSUE TITLE
Incorrect block in 247sports.com?

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10429]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://247sports.com/college/washington/Article/Washington-Huskies-UW-Football-Dawgman-Radio-Luke-Mounger-Jack-McCauley-interns-have-their-say-on-the-2020-season-152621690/`

### Describe the issue

There are videos blocked at the top of each page, and an ad placeholder at the right.

### Screenshot(s)

- Not blocked:

![image](https://user-images.githubusercontent.com/66517106/140851167-c3844e39-24ac-4fde-af10-ba3c1750b470.png)

- Blocked:

![image](https://user-images.githubusercontent.com/66517106/140851188-e0be7658-f6f0-4a9c-9f32-e802c53b7272.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

I'm not sure if the video is a tracker and we can remove placeholders or it can be unblocked.

- Unblocked:

```
@@||tags.tiqcdn.com/utag/cbsi/247sportssite/prod/*$script,domain=247sports.com
@@||api.ipify.org/?format=json$xhr,domain=247sports.com
@@||imasdk.googleapis.com/js/sdkloader/ima3*$script,domain=247sports.com
@@||cbsi.demdex.net/dest5.html$subdocument,domain=247sports.com
```

- Remove placeholders:

```
247sports.com##.article-list__list-item--ad
247sports.com##.embedVideo
```

**Comment by uBlock-user** [comment]
@ryanbr
