### ISSUE TITLE
mega.nz doesn't load

### ISSUE THREAD

**Issue by thany** [uBlockOrigin/uAssets#10427]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [ ] uBO is the only extension
- [ ] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

As stated hereafter, this is super difficult. Mega does a lot with custom offline storage that's hard to get rid of. Maybe WASM also keeps things cached in some kind of custom way.

### URL(s) where the issue occurs

`https://mega.nz`

### Describe the issue

Problem should reproduce even with a free account.

I had to add mega.nz to the trusted sites in order to get it to work. Funny thing is that after removing it, even with cache disabled, it keeps working. But I remember something about api from mega.io was being blocked. I'm also still seeing a lot of cross-origin policy errors, which I cannot believe a professional site like mega.nz would leave them in.

### Screenshot(s)

I wish I could, this is hard to reproduce on demand on my system.

### uBlock Origin version

latest

### Browser name and version

Firefox latest

### Settings

All filter lists checked except custom lists. I don't think anything else is relevant.

**Comment by uBlock-user** [comment]
>All filter lists checked except custom lists. I don't think anything else is relevant.

Reset default settings/lists + disable all other extensions.

**Comment by uBlock-user** [comment]
>All filter lists checked except custom lists. I don't think anything else is relevant.

Reset to default settings/lists + disable all other extensions.

**Comment by mapx-** [comment]
I was able to reproduce the issue only once in firefox getting no blocked item

**Comment by uBlock-user** [comment]
`https://mega.nz` redirects to `https://mega.io` so unless the redirection gets stopped, site loads fine.
