### ISSUE TITLE
[NSFW] New Redirecting Annoyance

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#1043]
**### URL(s) where the issue occurs**

`https://yourporn.sexy/*
`

**### Describe the issue**

This site has script which redirects every now and then (according to cookies state AFAIK). Its behavior is the same as the one I reported before here: #870.

In this case, the buggering site is:

`c75b9ac5103e5d125b8.com`

And an "about:blank" pop-up opens up as well.

### Screenshot(s)

[Will post them if needed]

### Versions

Browser/version: [SRWare Iron 61.0.3200]
uBlock Origin version: [1.14.20]

### Settings

No changes but updating the default filters' list.

### Notes

I already tried the methods mentioned in the other thread, but most of them don't work; and in this case, even the "defuser" related one seems to be not working neither.

Thanks.

**Comment by mapx-** [comment]
The old filters still working for me

**Comment by elsy04** [comment]
Could you please specify which ones exactly?

Although I already reported this very same annoyance before, it wasn't for the domain mentioned in this issue; and even when I tried to adapt the filters for this case, they don't work. Maybe I'm doing something wrong.

Thanks.

**Comment by okiehsch** [comment]
Your issue should already be fixed by `yourporn.sexy##script:inject(noeval.js)`, it is on my end and apparently also on mapx-'s end.
I get no popups unless I disable `noeval.js`.
Íf you load `https://yourporn.sexy` and open your Firefox console there should be some output logged
if `noeval.js` has been applied, for example my log:
![logt](https://user-images.githubusercontent.com/16838044/34133779-ff735d4c-e456-11e7-8156-9fd436015d13.PNG)

Can you check your console and if there is a "Document tried to eval" entry post the screenshot`.

**Comment by okiehsch** [comment]
> Although I already reported this very same annoyance before, it wasn't for the domain mentioned in this issue

Actually it was exactly the same domain `https://yourporn.sexy`
https://github.com/uBlockOrigin/uAssets/issues/870
https://github.com/uBlockOrigin/uAssets/issues/1043

**Comment by elsy04** [comment]
I'm sorry. I just realized the problem is actually happening in Chrome (SRWare Iron 61.0.3200), since there is no problems using Firefox v52.5.2 ESR with similar settings, but these filters:

```
yourporn.sexy##script:inject(abort-current-inline-script.js, parseInt, tabunder)
yourporn.sexy##script:inject(popads-dummy.js)

```
With Chrome, using that filter you mentioned and this one:

`yourporn.sexy##script:inject(abort-on-property-write.js, Fingerprint2)
`
The problems shows up.

And regarding the issue being already reported, I was talking about the specific domain mentioned here (c75...) is not the same one as the one in #870's issue (bfc7...); although maybe the same filter should still fix it.

Thanks.

**Comment by okiehsch** [comment]
Well, it is the same with Chrome on my end `yourporn.sexy##script:inject(noeval.js)` fixes the popups and
I get no popups unless I disable `noeval.js`.
Íf you load https://yourporn.sexy and open your **Chrome** console there should be some output logged
if noeval.js has been applied, for example my log:
![image](https://user-images.githubusercontent.com/16838044/34141440-8afd79c2-e481-11e7-8f86-2ec77909e5df.png)

Can you check your console and if there is a "Document tried to eval" entry post the screenshot`.
I only need the first few lines.

**Comment by elsy04** [comment]
Well, I just realized I was inadvertently allowing (green block) the main domain, so putting it back to default mode finally make the filters work as due.

![region](https://user-images.githubusercontent.com/13046351/34151425-ec59ca1a-e489-11e7-9a94-16a7e075c04b.png)

Thanks for your help.
