### ISSUE TITLE
Unieuro.it does not load the cookie panel

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#10434]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.unieuro.it/online/`

### Describe the issue

It is not possible to select the cookies to be used (therefore also the functional ones) because it is not possible to see the panel

### Screenshot(s)

uBlock Origin Log

![immagine](https://user-images.githubusercontent.com/62190484/140885098-87843d93-d956-4af7-be84-417891271cab.png)

Missing panel

![immagine](https://user-images.githubusercontent.com/62190484/140885177-8ec86b96-3113-4ff9-a047-38c883107e55.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No default settings have been changed

### Notes

Disabling uBlock Origin, the website works correctly

**Comment by mapx-** [comment]
test

`@@||googletagmanager.com/gtm.js$script,domain=unieuro.it`

@ryanbr

**Comment by fabriziobagala** [comment]
Seems to work properly
