### ISSUE TITLE
toptechtalk.xyz [link shortener] [broken]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#10438]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ezlinks.io/aSnLR`

### Describe the issue

Cannot continue on the site due to an issue with the filters preventing the button from appearing. I can only continue on the site if I completely disable the add-on I have also tried whitelisting stuff but cannot seem to get it to work.

### uBlock Origin version

1.38.6

### Browser name and version

Chrome v95

### Settings

Default

**Comment by uBlock-user** [comment]
There's no button to continue even after disabling uBO, if you literally click on the ad, you get redirected to some random page, you never reach your destination, this is a site issue.
