### ISSUE TITLE
[NSFW] Ads at the bottom of video player in megaxh.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10431]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://megaxh.com/embed/12409483?xh_proxy=1`

### Describe the issue

There's an ad at the bottom of video player after playing a few seconds (or after clicking pause).

### Screenshot(s)

[NSFW screenshot](https://i.ibb.co/WGvLm7C/image.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

**Comment by uBlock-user** [comment]
```
||collector.megaxh.com^
megaxh.com##.xplayer-banner-bottom
megaxh.com##.xplayer-button.join
megaxh.com##a.tab:nth-of-type(1)
```

@ryanbr

**Comment by stephenhawk8054** [comment]
There's a popup in the site now. Open a new Private Window/Incognito session, click on any video, a popup appears

URL: `https://megaxh.com`

Proposed filter: 

`megaxh.com##+js(nowoif)`

**Comment by stephenhawk8054** [comment]
Another popup and there are other ads placeholders in mobile now.

URL:
`https://megaxh.com`

1. Open in new Private Window/Incognito session
2. Click on any video links at the top, it opens the video in new tab and the current tab redirects to `http://tsyndicate.com/api/v1/direct` blocked site.

It's caused by this inline script in `view-source`:

```js
window['wio-xpopunder'] = {
	"url": "http:\/\/tsyndicate.com\/api\/v1\/direct\/4cc0709d75bc4ce89eaf7fd4438962cc61dc0e5d15f59205e847d2a7aea106d71db256bb?spot=4cc0709d75bc4ce89eaf7fd4438962cc61dc0e5d15f59205e847d2a7aea106d71db256bb&subid_1=&subid_2=&subid_3=&subid_4=&abt=&xhid=&categories=",
	"cookieName": "popSeen",
	"includeFilter": "role-pop",
	"cookieExpires": 1
}
```

<details>
<summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 79071
  cosmetic: 45827
  scriptlet: 16418
  html: 619
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30760-43, 2m
    ublock-badware: 3662-1, 2m
    ublock-privacy: 183-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1732-0, 2m
    adguard-mobile: 7057-157, 2m
    easylist: 62812-709, 2m
    easyprivacy: 26613-489, 2m
    urlhaus-1: 6904-0, 2m
    plowe-0: 3685-2, 2m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 927 ms
popupPanel: 
  blocked: 7
```
</details>

Proposed filters:

```
megaxh.com##+js(set, window.wio-xpopunder.includeFilter, '')
megaxh.com##.wio-xspot-container
megaxh.com##.big-thumb-block
```
