### ISSUE TITLE
[NSFW] Anti-adblock and popup in clk.asia

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10439]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://clk.asia/smSR`

### Describe the issue

1. Wait about 30 seconds, an anti-adblock appears.
2. When clicking on the button, a popup appears.
3. After clicking the button, the next domains can be `imperialstudy.com` or `skincarie.com`, both have the same anti-adblock as `clk.asia`.
4. After continuing, it goes back to `clk.asia` domain, clicking on the button triggers a popup again.

### Screenshot(s)

- `clk.asia`
![image](https://user-images.githubusercontent.com/66517106/141045719-715b1702-6f86-4001-a49b-41459eeef599.png)

- `imperialstudy.com`
![image](https://user-images.githubusercontent.com/66517106/141045824-daa07050-7332-47fb-8b1c-718643de10ed.png)

- `skincarie.com`
![image](https://user-images.githubusercontent.com/66517106/141045942-4ca0c826-61b4-45d1-9a52-dfd67a875c6d.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

There's also an ad frame above the button. Proposed filters:

```
clk.asia,imperialstudy.com,skincarie.com##+js(nobab)
clk.asia##+js(ra, onClick, button)
clk.asia##+js(nowoif)
||clk.asia/ads/*$subdocument,1p
||clk.asia/clkadtrue.php$subdocument,1p
```

**Comment by ghajini** [comment]
```
||clk.asia/sw.js$script,1p
||condolencespicturesquetracks.com^
clk.*,imperialstudy.com,skincarie.com##+js(nosiif, visibility, 1000)
clk.asia##+js(nowoif)
||clk.asia/ads/*$frame
```
