### ISSUE TITLE
Euronics.it does not load the cookie panel

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#10433]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.euronics.it/`

### Describe the issue

It is not possible to select the cookies to be used (therefore also the functional ones) because it is not possible to see the panel

### Screenshot(s)

uBlock Origin Log

![immagine](https://user-images.githubusercontent.com/62190484/140882372-7c0b0728-c1d2-4975-b04c-19b197e361ac.png)

Missing panel

![immagine](https://user-images.githubusercontent.com/62190484/140882567-a1900859-8dc1-46cd-b486-b6da8d64ed7d.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No default settings have been changed

### Notes

Disabling uBlock Origin, the website works correctly

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=euronics.it
@@||quantcast.mgr.consensu.org^*/cmp2.js$script,domain=euronics.it
```

@ryanbr

**Comment by fabriziobagala** [comment]
Yes, now you can see the panel and accept cookies
