### ISSUE TITLE
Ads left overs on rebelnews.com

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#10437]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.rebelnews.com/professor_forced_to_undergo_mental_health_evaluation`

### Describe the issue

Ads leftovers in article.

### uBlock Origin version

1.38.6

### Browser name and version

FireFox 94.0.1

### Settings

- EasyDutch
- block 3p-frames

### Notes

```
rebelnews.com##.rn-sidebar-ad
rebelnews.com##.rn-article-ad
```
Solved problem

**Comment by uBlock-user** [comment]
Report to https://github.com/easylist/easylist/issues
