### ISSUE TITLE
enigaseluce.com does not load the cookie panel

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#10435]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://enigaseluce.com/`

### Describe the issue

It is not possible to select the cookies to be used (therefore also the functional ones) because it is not possible to see the panel

### Screenshot(s)

uBlock Origin Log

![immagine](https://user-images.githubusercontent.com/62190484/140886976-4a6728f9-6ccc-4ea4-b64b-d437f228f60b.png)

Missing panel

![immagine](https://user-images.githubusercontent.com/62190484/140887017-8394d957-fd6f-402b-b607-99a3f377c59e.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No default settings have been changed

### Notes

Disabling uBlock Origin, the website works correctly

**Comment by uBlock-user** [comment]
Same as other, report to https://github.com/easylist/easylist/issues

**Comment by mapx-** [comment]
test

```
@@||cdn.trustcommander.net/privacy$script,domain=enigaseluce.com
@@||cdn.trustcommander.net/privacy/*/privacy_v2_hook_1.js$script,domain=cdn.trustcommander.net
```

@ryanbr

**Comment by fabriziobagala** [comment]
> Same as other, report to https://github.com/easylist/easylist/issues

I have not found the bug you are referring to, but it is a problem that does not allow the website to work properly.

**Comment by fabriziobagala** [comment]
@mapx- seems to work properly

**Comment by uBlock-user** [comment]
> I have not found the bug you are referring to

Yes, open a new issue there, fixes will get added in EasyPrivacy.
