### ISSUE TITLE
Anti-adblock in sum.vn

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10436]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sum.vn/`

### Describe the issue

After the page loaded, wait about 30 seconds, then anti-adblock appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/140924515-dad02b0d-3950-45b6-b5f7-b112a5984563.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

The anti-adblock is in the script link:

`https://sum.vn/static/js/hungnh.js`

Proposed filter:

`||sum.vn/static/js/hungnh.js$script,1p`

**Comment by uBlock-user** [comment]
Did you activate VIE: ABPVN List ?

**Comment by stephenhawk8054** [comment]
> 
> 
> Did you activate VIE: ABPVN List ?

Nope, I'm using default filter lists.

![image](https://user-images.githubusercontent.com/66517106/140927906-8dcd1a11-ba03-43cf-be77-9e3689f26092.png)

But looks like it is caused by Firefox Tracking Prevention, my bad.

**Comment by hoang-rio** [comment]
This issue does not happend with ABPVN List enabled

<details>
<title>Screenshoot</title>
![Screenshot_20211109-210001.png](https://user-images.githubusercontent.com/11514638/140937514-b238d33f-c374-4a02-bb78-c630755feb8e.png)
</detail>
