### ISSUE TITLE
pewresearch.org breakage

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#10441]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pewresearch.org/politics/quiz/political-typology/`

### Describe the issue

Quiz breaks (cannot progress) after question 3

### uBlock Origin version

1.38.6

### Browser name and version

Firefox nightly

### Settings

n/a

### Notes

```
Uncaught ReferenceError: ga is not defined
    handleNextButton
    onClick
 ```

fixes:
`pewresearch.org##+js(set, ga, noopFunc)`

or

`@@||googletagmanager.com/gtm.js$script,domain=www.pewresearch.org`

(When GTM is blocked, the GA script is never requested)

**Comment by uBlock-user** [comment]
> 1.38.6

Can't reproduce with the dev build, `ga` is properly defined and quiz progresses.

**Comment by felix-22** [comment]
- neither can I, I've tried on FF / FF Nightly & uBO 1.38.6 / uBO 1.38.7b19
- by the way, there has been some fix in uBO: 
https://github.com/uBlockOrigin/uBlock-issues/issues/1807
I don't know whether it's related or not

**Comment by felix-22** [comment]
- neither can I, I've tried on FF / FF Nightly & uBO 1.38.6 / uBO 1.38.7b19
- by the way, there has been some fix in uBO: 
https://github.com/uBlockOrigin/uBlock-issues/issues/1807

**Comment by uBlock-user** [comment]
Shouldn't happen in the  stable build either, `gtm.js` stock resource also already has `ga` defined.
