### ISSUE TITLE
nu.nl advertisements/advertorials

### ISSUE THREAD

**Issue by Siarl** [uBlockOrigin/uAssets#1044]
### URL(s) where the issue occurs
https://www.nu.nl/ 
https://www.nu.nl/tech

etc...

### Describe the issue

nu.nl is a Dutch news site. They feature sponsored articles advertising products. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9255132/34103475-1bfce5ce-e3ed-11e7-93d0-39148704b483.png)
![image](https://user-images.githubusercontent.com/9255132/34103752-309f6b5e-e3ee-11e7-919a-57c9588b3553.png)

('gesponsord door' means sponsored by)

### Versions

- FF 58.0b11 (64-bit) windows
- uBlock Origin v1.14.22

### Settings

- Regional blacklist enabled on top of standard lists

### Notes

These advertisements have a "branded" class name. The articles are hosted in the /advertorial directory:

https://www.nu.nl/advertorial/advertorial-mini/5047622/zo-maak-je-auto-veilig-kinderen.html

https://www.nu.nl/advertorial/advertorial-huawei/5030684/nieuwste-smartphone-denkt-jou.html

**Comment by mapx-** [comment]
already hidden by `NLD: EasyList Dutch`

**Comment by Siarl** [comment]
Doesn't seem to work for me then. I have EasyList Dutch enabled and up to date. I'll block it locally

**Comment by mapx-** [comment]
the filter which should work
`nu.nl##a[href*="/advertorial-"]`

Did you disable the cosmetic filtering for that site ?
