### ISSUE TITLE
UBO Not Working On Soap2Day Sites

### ISSUE THREAD

**Issue by npn225** [uBlockOrigin/uAssets#10445]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Videos on the `https://soapgate.org/` sites do not play video when the EasyList filter list is enabled on uBO!

### A specific URL where the issue occurs

`https://s2dfree.de/MczozMjoiMTE5NTB8fDY4LjE5OS4xMTguNzF8fDE2MzY2MDUyNzkiOw.html`

### Steps to Reproduce

1. Enable uBO with its default settings (make sure EasyList filter list is checked in the dashboard)
2. Go to the webpage linked above
3. Hit the play button on the video on the webpage

### Expected behavior

Expected behavior is for the video to play

### Actual behavior

This message is shown instead of the video playing: 

> This video file cannot be played.
> (Error Code: 102630) 

### Configuration

Browser: Brave Browser 95.1.31.91 & Mozilla Firefox 94.0
OS: Linux Mint 20.2

**Comment by uBlock-user** [comment]
force update EasyList.

**Comment by npn225** [comment]
> force update EasyList.

But EasyList is already updated to latest version and the problem still persists on both browsers.

**Comment by uBlock-user** [comment]
I can't reproduce after force updating EasyList.

**Comment by npn225** [comment]
Thanks anyway!

**Comment by felix-22** [comment]
- I can't reproduce either (on both Firefox and Opera)
- however I can reproduce the error, but only between videos (while switching to another video), but it quickly dissappears and does not prevent video from playing play, so not an issue:
https://user-images.githubusercontent.com/75935068/141284475-71ee75de-159e-4675-b889-51fa4dd49b38.gif

- also related: https://github.com/bogachenko/fuckfuckadblock/issues/238

**Comment by npn225** [comment]
I've found the solution here: https://github.com/bogachenko/fuckfuckadblock/issues/238#issuecomment-966527850

Thanks for the assistance and apologies for wasting everyone's time.
