### ISSUE TITLE
Various Discord scam links

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#10442]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://discord.com/` (Various servers at random time intervals)

### Describe the issue

It has dawned on me gradually over the past 2 months that humans are perfectly willing to click on obvious Discord Nitro spam malware links in Discord servers. Thus I see there's a pretty big market for adding anti-spam-link entries to Badware Risks.

I propose:
```
||discordapp.cam^$all
||discordap.$all
||airdrop-discord.ru^$all
||discord*.gift^$all
||discord*.gifts^$all
||discord-app.net^$all
||discord-give.$all
||discord-nitro-gift.$all
||discord-nitro.$all
||discord-nitros.$all
||discord-spooky.$all
||discord.foundation^$all
||discordgift.$all
||discordnitro-steam.$all
||discordnitro.space^$all
||discordxgift.$all
||discordxnitro.$all
||free-discordnitro.$all
||freediscordnitro.$all
||gift-discord.$all
||giftsdiscord.$all
||giiveaway-discord.$all
||steam-discords.$all
||disordgift.$all
||com-nitro.$all
||discocrd-nitro.$all
||discorcd-nitro.$all
||discorclnitro.$all
||discrodnitro.$all
||nitro*.gift^$all
||nitro*.gifts^$all
||steamcommunity-nitro.$all
||steamgiftnitro.$all
```

### Screenshot(s)

N/A

### uBlock Origin version

1.38.7b16

### Browser name and version

Chrome 95.0.4638.69 x64

### Settings

N/A

### Notes

The Nitro spam problem has become an actual epidemic on Discord, and stories of users clicking on those links have most likely reached the low 6-digits by now.

**Comment by Vukkyy** [comment]
Note that `||discord*.gift^$all` is triggering on the official discord.gift domain as well, which is a redirect to discord.com/gifts/GiftID.
![Issue in action](https://i.imgur.com/gnyVYne.gif)

**Comment by dieser-niko** [comment]
Found this list here, this one actually covered all of the discord scam links I personally gathered:
[https://github.com/DevSpen/links/blob/master/src/links.txt](https://github.com/DevSpen/links/blob/master/src/links.txt)

**Comment by DandelionSprout** [comment]
It's 2,256 entries would likely need heavy wildcard-compression by me before I could propose to add them to, but thanks in advance.
