### ISSUE TITLE
Anti-Adblock on mytoolz.net

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#10465]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mytoolz.net`

### Describe the issue

When using adblock mytoolz.net displays a popup that says "Please disable your adblock."

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 94.0.4606.114

### Settings

- Added all default filters except for language filters
- My filters:

<details>
||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech

- Trusted sites:

about-scheme
# chrome-extension-scheme
chrome-scheme
edge-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
wyciwyg-scheme
0redirc.com
123movies.com
4g27x3fk.optimalworkshop.com
a-ads.com
account.jetbrains.com
account.venmo.com
ad4game.com
adbl0ck.com
adcash.com
adhall.com
admedia.com
admin.advertise.com
adonly.com
adservice.io
adshnk.com
adshrink.it
adstargets.com
adsvert.com
adversal.com
adx1.com
affiliate-program.amazon.com
ambassador.surveytime.io
analytics.google.com
app.any.run
app.coinmiles.io
app.crisp.chat
app.cryptotab.farm
app.getmoocash.com
app.guard.io
app.reklaimyours.com
app.screencastify.com
applock.top
apprefaculty.pro
apps.royalbank.com
authorize.kobo.com
bankingbux.com
beta.publishers.adsterra.com
betteradsystem.com
bitland.pro
bux.dev
cellxpert.com
cint.insightexpressai.com
console.paperspace.com
cr-brands.net
cryptobrowser.site
dash.cloudflare.com
dash.getastra.com
dash.teams.cloudflare.com
dashboard.fingerprintjs.com
diabasewoodhouse.xyz
dig.ps-di.com
digitalflare.io
discord.com
donotpay.com
eds.ca.matchbox.maruhub.com
en.netaffiliation.com
evadav.com
freerobuxnow.netlify.app
gamebassadors.net
getfiles.co
go.getastra.com
go.libertex.com
go.stormgain.com
goggle.proasdf.com
googleads.github.io
guard.io
howsliferightnow.com
id.subway.com
imonomy.com
instabayi.com
intellipopup.com
intl.cloud.tencent.com
invitation.codes
jsfiddle.net
jump.ogtrk.net
lifeinstride.com
live.browserstack.com
members.cpabuild.com
members.ogads.com
mgcash.com
mytrafficvalue.com
nomobileads.com
now.gg
opinion.yunosurveys.com
order.subway.com
ozzyfakeid.com
panelistconsent.google.com
partners.stackcommerce.com
platform.33across.com
platform.io
pointclicktrack.com
prebid.org
pro.moat.com
prod.uhrs.playmsn.com
propellerads.com
ps.opinionetwork.com
publisher.adsmain.com
publishers.adsterra.com
putlocker.one
rblx.land
rbxexchange.com
rbxshop.net
reachnetwork.pro
ref.mgid.com
register.silverscreen.cc
registrace.seznam.cz
researchonmobile.com
reward.tremendous.com
s.cint.com
s.getastra.com
secure.hulu.com
secure.redirect.com
securely-send.com
securityscan.getastra.com
shoppy.gg
shorte.st
smallpdf.com
smartyads.com
spectrumsurveys.com
store.steampowered.com
superpay.me
survey-api.com
survey.saysoforgood.com
surveys.eliteopinio.com
surveys.ipsosinteractive.com
surveys.sample-cube.com
sw.cint.com
take.yunosurveys.com
takipcikrali.com
theoremreach.com
tracking.ogmobi.com
trafficg.com
trckapp.com
trk.sportsalerts.club
trk301.com
unlck.com
user.hilltopads.com
v3.rtrack.live
vancouverrestores.vonigo.com
vectordash.com
vendors.paddle.com
vidox.net
viral782.com
vln.easysurveys.net
voluum.com
wbidder.online
wbidr.com
wboptim.online
web.archive.org
web.bitlabs.ai
web.peanutlabs.com
whitemobi.com
windowsdefender.site
wordpress.com
workplace.clickworker.com
wss.pollfish.com
www.acer.com
www.advertise.com
www.adworkmedia.com
www.beermoneyforum.com
www.binance.com
www.buybitcoinworldwide.com
www.casinorewards.com
www.checkout51.com
www.citizengoods.com
www.comscore.com
www.cpalead.com
www.dontpayfull.com
www.dosh.com
www.easyhits4u.com
www.getastra.com
www.getmoocash.com
www.grammarly.com
www.gridgaming.io
www.harrispollonline.com
www.idle-empire.com
www.insightexpress.com
www.jobsnearme.online
www.komoona.com
www.leadboltapps.com
www.leovegasaffiliates.com
www.myadcash.com
www.okayfreedom.com
www.okex.com
www.paypal.com
www.peanutlabs.com
www.reviews.co.uk
www.rewardsaffiliates.com
www.sample-cube.com
www.screencastify.com
www.shrink-service.it
www.skillwise.com
www.smaato.com
www.soundtrap.com
www.subway.com
www.superpay.me
www.tradingview.com
www.trellian.com
www.vans.ca
www.vans.com
x.bluestacks.com
yourezads.com
ys.cint.com
yuumari.com
</details>

### Notes

Adding these filters:

mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech

Stops the anti-adblock message.

**Comment by iam-py-test** [comment]
> Adding these filters:
> 
> mytoolz.net##.ndcyidc
> mytoolz.net###adblock_abdoutech

Those filters hide the anti-adblock. `@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net` seems to get rid of it
