### ISSUE TITLE
Popup in miraculous.to

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10460]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://miraculous.to/en/watch?s=4&e=16`

### Describe the issue

Click on play button, a popup appears.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

Proposed filter:

`miraculous.to##+js(acis, JSON.parse, break;case $.)`

**Comment by Zelda189** [comment]
Anti right click, anti ctrl-u `(animatedshows.to only)`, anti devtools etc. is here on `https://animatedshows.to/videos/watchv?e=1_5&lang=en&ssid=0x02` and `https://miraculous.to/en/watch?s=4&e=09`

Proposed filter:

`animatedshows.to,miraculous.to##+js(aopr, debugchange)`
`animatedshows.to,miraculous.to##+js(ra, oncontextmenu, body)`
`miraculous.to##+js(aeld, contextmenu, preventDefault)`
`animatedshows.to##+js(aeld, /^(?:keyup|keydown)$/)`

**Comment by Zelda189** [comment]
Incomplete fix for anti ctrl-u, `console.clear` and `console.log` script on `https://hub.miraculous.to/watch?s=4&e=09&lang=en`

Proposed filter:

```
hub.miraculous.to##+js(aeld, /^(?:keyup|keydown)$/)
hub.miraculous.to##+js(set, console.clear, noopFunc)
hub.miraculous.to##+js(set, console.log, noopFunc)
```
