### ISSUE TITLE
forum.gocmod.com: detection

### ISSUE THREAD

**Issue by DiAnTTA** [uBlockOrigin/uAssets#10477]
### URL address of the web page

`https://forum.gocmod.com/forums/`

### Category

detection

### Describe the issue

A pop-up says I'm blocking ads on their site.

### Screenshot(s)

![Kiwi_browser](https://user-images.githubusercontent.com/74956696/141691444-5b2d8f35-d202-466b-9460-4bd846a9532a.png)

### Configuration

```yaml
uBlock Origin: 1.38.7b25
Chromium Mobile: 95
filterset (summary): 
  network: 80146
  cosmetic: 45352
  scriptlet: 16283
  html: 0
listset (total-discarded, last updated): 
  default: 
VIE-1: 2040-0, 10m
adguard-mobile: 6905-17, 10m
easylist: 60560-216, 5m
easyprivacy: 25497-21, 3m
plowe-0: 3685-647, 1m
ublock-abuse: 67-0, 1m
ublock-badware: 3362-55, 1m
ublock-filters: 29696-123, 1m
ublock-privacy: 185-2, 1m
ublock-unbreak: 1692-39, 1m
urlhaus-1: 9356-0, 1m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]

```

**Comment by gorhill** [comment]
@hoang-rio could add the filter to his list -- I see that it supports uBO-specific syntax.
