### ISSUE TITLE
filmehdon.ucoz.com

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#10489]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://filmehdon.ucoz.com/load/aventura/the_christmas_chronicles_cronicile_craciunului_2018/3-1-0-2193`

### Describe the issue

Pop up appear on the right side of the page.

### uBlock Origin version

1.38

### Browser name and version

Firefox 94

### Settings

Default filter lists.

**Comment by mapx-** [comment]
> Pop up appear on the right side of the page

clicking on right side or you mean some annoyance ? screenshot ?

**Comment by IEnjoyDrinkingGoodWater** [comment]
video player?

also, does the webpage break uBO's popup panel?

**Comment by IEnjoyDrinkingGoodWater** [comment]
a video player?

**Comment by gemoshi07** [comment]
> > Pop up appear on the right side of the page
> 
> clicking on right side or you mean some annoyance ? screenshot ?
![screen](https://user-images.githubusercontent.com/86512304/142060239-5ceb3478-1953-456c-a149-d7702e0202ef.jpg)
The ads appear on the right side, I don't need to click on it. Sorry for late reply.

**Comment by mapx-** [comment]
yeah, using a romanian vpn I'm able to get that ad

add
`filmehdon.ucoz.com##.vmainadsdvcl`

or

`||sportrecs.com/redirect/embed/$frame,domain=filmehdon.ucoz.com`

However, it's a simple / classic ad to be fixed in easylist or [romanian list](https://github.com/tcptomato/ROad-Block/issues) (but the maintainer is not very active)

@ryanbr
