### ISSUE TITLE
pollunit.com ads

### ISSUE THREAD

**Issue by mchangrh** [uBlockOrigin/uAssets#10480]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pollunit.com/polls/m6y_7gycdn3fjxvuavqvya`

### Describe the issue

Ads and link for "premium account" for removing ads is present

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 95.0.4638.69

### Settings

- 

### Notes

Creating issue to link with PR

Could not be submitted to easylist since it requires :has and href filtering

generic blocks will break carousel on homepage

**Comment by uBlock-user** [comment]
```
pollunit.com##.carousel-ad
pollunit.com##.owl-drag.owl-loaded.owl-carousel
pollunit.com##a[href$="?feature=ads"]
```

@ryanbr

**Comment by mchangrh** [comment]
> ```
> pollunit.com##.carousel-ad
> pollunit.com##.owl-drag.owl-loaded.owl-carousel
> pollunit.com##a[href$="?feature=ads"]
> ```
> 
> @/ ryanbr

This breaks the main site: see the header `Latest posts` (second from the bottom)

`https://pollunit.com/en`

**Comment by mapx-** [comment]
so, the correct filters are (from your PR)

```
pollunit.com##.btn[href$="?feature=ads"]
pollunit.com##.owl-carousel:has(.carousel-ad)
```

still to be added to EL

**Comment by uBlock-user** [comment]
EasyList supports `:-abp-has`
