### ISSUE TITLE
Anti-Adblock notice when using Paraphraser.io

### ISSUE THREAD

**Issue by yokoffing** [uBlockOrigin/uAssets#10488]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

See https://github.com/easylist/easylist/issues/9724

Also happens with `https://paraphrasetool.com/`, though it worked about two times before the anti-adblock appeared.

### A specific URL where the issue occurs

`https://www.paraphraser.io/`

### Steps to Reproduce

1. Type in box
2. Click `Paraphrase Now`
3. Anti-adblock appears

### Expected behavior

to work

### Actual behavior

anti-adblock

### uBlock Origin version

uBlock Origin 1.38.6 (stable)

### Browser name and version

Firefox Dev 95.0b6

### Operating System and version

Windows 10

**Comment by stephenhawk8054** [comment]
Anti-adblock in `paraphraser.io` again.

1. Put any paragraph in text box
2. Solve the captcha and click on `Paraphrase Now`, an anti-adblock overlay appears.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/150054523-82661d4e-12ad-4e59-9b8a-872d7321d191.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78075
  cosmetic: 40553
  scriptlet: 16431
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30757-30, now
    ublock-badware: 3728-1, now
    ublock-privacy: 187-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1694-0, now
    easylist: 63126-587, now
    easyprivacy: 26635-480, now
    urlhaus-1: 7040-0, now
    plowe-0: 3682-2, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 801 ms
popupPanel: 
  blocked: 4
```
</details>

Not sure why `##+js(set, detectadsbocker, false)` can't work. Proposed filters:

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=paraphraser.io
paraphraser.io##.adsenbox
paraphraser.io##body > .justify-content-center
```
