### ISSUE TITLE
AETV

### ISSUE THREAD

**Issue by OverlordQ** [uBlockOrigin/uAssets#1048]
### URL(s) where the issue occurs

`http://www.aetv.com/shows/intervention/season-1/episode-5`

### Describe the issue

Ads show pre and during playback.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome Version 64.0.3282.24 
- uBlock Origin version:  v1.14.22

### Settings

- Default

### Notes

Enabled Lists:

- ublock filters
- ublock privacy
- ublock resource abuse
- ublock unbreak

**Comment by mapx-** [comment]
I get no video ad (using US tunneling shell )

**Comment by xqk94524** [comment]
![screenshot-2017-12-27 watch sara full episode - intervention a e](https://user-images.githubusercontent.com/34273204/34385356-95cd1dda-eaf8-11e7-8fde-b0d69e1018f0.png)
I get this
