### ISSUE TITLE
hepsiburada.com

### ISSUE THREAD

**Issue by furt555nv** [uBlockOrigin/uAssets#10490]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.hepsiburada.com/lego-brickheadz-40436-lucky-cat-p-HBV00000T5F9K`

### Describe the issue

The site will break if the canonical list is enabled.

### Screenshot(s)

<details>
 <summary>Screenshot</summary>
 
![940fp9h](https://user-images.githubusercontent.com/89068379/141831475-5b6640a0-cc8c-4f84-a8ca-934ac7fd311b.png)

</details>

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

Privacy

- [x] Disable pre-fetching
- [x] Disable hyperlink auditing
- [x] Block CSP reports
- [x] Uncloak canonical names

Filters

```
AdGuard Base
EasyList
AdGuard Tracking Protection
AdGuard URL Tracking Protection
AdGuard Social Media
AdGuard Annoyances
AdGuard Turkish 
```

**Comment by gorhill** [comment]
You disabled uBlock filters?

**Comment by furt555nv** [comment]
> 
> 
> You disabled uBlock filters?

Yes
Feel free to close if you can't reproduce it.

**Comment by gorhill** [comment]
uBlock filters are key to uBO properly blocking, we do not support such non-standard selection of lists. Try again with all _"uBlock filters"_ lists enabled.

**Comment by uBlock-user** [comment]
> if you can't reproduce it.

Fixes are not added if it's not reproduced on default lists.

**Comment by furt555nv** [comment]
> 
> 
> uBlock filters are key to uBO properly blocking, we do not support such non-standard selection of lists. Try again with all _"uBlock filters"_ lists enabled in the _"Built-in"_ section.

OK I got it. Site loads fine with uBo filters.
Thanks for your help
