### ISSUE TITLE
Anti-adblock in wouterplanet.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10495]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.wouterplanet.com/videos/funny-tapes1`

### Describe the issue

Wait about 30 seconds, an anti-adblock screen appears. Also there's an ads placeholder at the bottom

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/141891415-958aaf5a-345f-48bb-9095-a69aca921db9.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

Proposed filters:

```
wouterplanet.com##+js(acis, setTimeout, break; else)
wouterplanet.com##div.panel-primary.panel:nth-of-type(3)
```

**Comment by stephenhawk8054** [comment]
Anti-adblock again, I can't get around it unless I whitelist `static.getclicky.com` script:

```
@@||wouterplanet.com^$ghide
@@||static.getclicky.com/js$script,domain=wouterplanet.com
wouterplanet.com#@#+js(abort-current-script, setTimeout, 'visibility')
```

Anyone has better solutions?

**Comment by mapx-** [comment]
try this
`wouterplanet.com##+js(nostif, Ads)`

**Comment by stephenhawk8054** [comment]
Ah right, confirm that works 👍

**Comment by woeterman94** [comment]
Perhaps you could stop circumventing our warning messages? There is a reason why we show them.

**Comment by mapx-** [comment]
you could use a dismissible warning message so we could move the filter in our annoyances list (not enabled by default)

**Comment by woeterman94** [comment]
We deliberately chose not to show our website to people who use an adblocker. I don't understand why you guys keep trying to circumvent this.

**Comment by mapx-** [comment]
"We" are an adblocker, is so difficult to understand it ?

**Comment by okiehsch** [comment]
This is the repo of an "adblocker", so it's not surprising that we circumvent an **anti-adblock** message, no?

**Comment by woeterman94** [comment]
> This is the repo of an "adblocker", so it's not surprising that we circumvent an **anti-adblock** message, no?

I thought the purpose of an adblocker was to block ads. Not to circumvent systems detecting an adblocker? o_0

**Comment by mapx-** [comment]
read here https://github.com/uBlockOrigin/uAssets/blob/master/README.md

We are fixing:

Issues involving

ad-reinsertion
anti-adblock
contextmenu blockage
copy/cut/paste blockage
popups/popunders
site breakage
video ads

**Comment by okiehsch** [comment]
> I thought the purpose of an adblocker was to block ads.

I put the "adblocker" in quotes because as you can see in https://github.com/gorhill/uBlock/blob/master/README.md it's not considered to be an adblocker. 
In our readme we are quite open what we block or cirumvent and what we don't.
For exmple we don't circumvent paywalls or GDPR messages.

**Comment by woeterman94** [comment]
> Quoting your email:
> 
> > If people want to use an adblocker that's their choice... But it is also our choice not to display our website to people who block our ads.
> > We work very hard on our website and ads are our way to gain a small revenue that can help to keep the website online. That's why we deliberately don't display our website to people who use an ad blocking script.
> 
> Following the logic, it should be user's choice to use a blocker that can circumvent anti-adblock wall, end of the story. All of us have been working hard on this project without getting a penny.

Choosing to block ads and choosing to circumvent a system that displays a message when you block ads are two different things.

 You choose to block ads -> The owner chooses he doesn't want users who blocks ads -> You try to circumvent that system. 

I think something is clearly wrong with that last one. It's like someone doesn't want you to do something and yet you keep finding ways to do it.
