### ISSUE TITLE
Entire webhost 'users.skynet.be' is blocked

### ISSUE THREAD

**Issue by Wouter93** [uBlockOrigin/uAssets#105]
### URL(s) where the issue occurs

```
http://gabyberger.be/
http://users.skynet.be
```

### Describe the issue

users.skynet.be is a widely used webhost in Belgium, provided by the ISP 'Proximus' (which is used by  ~30% of the population in Belgium)
Because 'users.skynet.be' is blocked, none of the websites that use this webhost seem to work.

### Versions

- Browser/version: Google Chrome 52.0.2743.116 m (64-bit)
- uBlock Origin version: 1.8.4

**Comment by gwarser** [comment]
It's not. Use log to check why it is blocked for you.
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by Wouter93** [comment]
[http://i.imgur.com/zYze2E1.png](http://i.imgur.com/zYze2E1.png)
[http://i.imgur.com/vMG9akL.png](http://i.imgur.com/vMG9akL.png)
[http://i.imgur.com/FCX9Se1.png](http://i.imgur.com/FCX9Se1.png)

**Comment by gorhill** [comment]
Ok, given I can't find `skynet.net` in EasyList, EasyPrivacy, Peter Lowe's, I will add an exception filter `@@||users.skynet.net^` -- until malwaredomains.com fix this on their side.

**Comment by gorhill** [comment]
This will need to be reported and fixes on `malwaredomains.com`. Workaround for people inconvenienced by this is to disable that filter list.

**Comment by gorhill** [comment]
I sent an email to the list maintainer, you may want to do the same:

http://www.malwaredomains.com/?page_id=13

**Comment by gorhill** [comment]
Maintainer wrote back to confirm the entry was removed from the list.
