### ISSUE TITLE
pcworld.es - Ads

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#10501]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pcworld.es/articulos/wearables/oferta-fitbit-black-friday-3810597/`

### Describe the issue

Ads in video and below the page

i dont know why in `pcworld.com`  I cant reproduce ads

### Screenshot(s)

Below the page ads

https://user-images.githubusercontent.com/33556647/142066439-8f3e534d-2d7a-4d7a-aa5e-3c359af77b3d.PNG

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 96.0

### Settings

https://user-images.githubusercontent.com/33556647/142066021-04bb8bce-26b1-48b7-a7b0-d3f07332cc7d.PNG

**Comment by mapx-** [comment]
I get no video ad

**Comment by PIZZA90** [comment]
with you filters solved the video ads!

```
pcworld.es##+js(nostif, .call(null), 10)
pcworld.es##.stickyAdWrapper
```

the ads is in any video, example in main page: `https://www.pcworld.es/`

**Comment by PIZZA90** [comment]
good work

**Comment by PIZZA90** [comment]
is random videos.. when refresh the page, the videos change...

but is weird.. when i scroll down in main page the video disappear.

**Comment by PIZZA90** [comment]
break now... scroll full down and go up for the video of any post ... (break)

```
https://www.pcworld.es/articulos/smartphones/samsung-galaxy-unpacked-3782360/
https://www.pcworld.es/articulos/software/windows-11-3806610/
https://www.pcworld.es/mejores-productos/software/mejores-addons-kodi-3673052/
```

**Comment by PIZZA90** [comment]
true... this happening for a long time, the `.com` version (english) no problem 🤔 its ok..
