### ISSUE TITLE
hire.jobscore.com incorrect blocking

### ISSUE THREAD

**Issue by fedevegili** [uBlockOrigin/uAssets#10504]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```https://hire.jobscore.com/beta/null?&http_referer=%2Fbeta%2Femployer%2Fcandidate%2Flist```

### Describe the issue

AJAX request to the backend is being blocked by uBlock origin. Our customers are having problems using our system while using the extension.

Looks like ```http_referer``` query parameter is triggering the ad-blocker, however, we use it on many pages internally.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6809993/142280178-eec30b7b-6561-491f-aa80-d437b4a9e1e1.png)

### uBlock Origin version

1.38.6

### Browser name and version

Google Chrome 96.0.4664.45

### Settings

- None

### Notes

Looks like ```http_referer``` query parameter is triggering the ad-blocker, however, we use it on many pages internally.

**Comment by mapx-** [comment]
EasyPrivacy issue @ryanbr 

```
&http_referer=$xmlhttprequest,domain=~facebook.com,badfilter
&http_referer=$xmlhttprequest,domain=~facebook.com|~jobscore.com
```

**Comment by ryanbr** [comment]
How do I test this ? @fedevegili

**Comment by mapx-** [comment]
go to the link he posted, you'll get an error 

![image](https://user-images.githubusercontent.com/10303732/142284153-0114064e-7983-430e-ba40-87412150b411.png)

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/142284219-0dc9db5b-7840-44c9-9631-7349ac8085d3.png)

**Comment by ryanbr** [comment]
Taking the `&http_referer=` would fix it, but then adding any EP filter into the url would cause issues.   
https://hire.jobscore.com/beta/null?&pageReferrer=2Fbeta%2Femployer%2Fcandidate%2Flist

Trying to replicate the issue here, the steps, rather than just the direct link.

**Comment by mapx-** [comment]
@fedevegili could you provide the steps to reproduce the issue ? I guess a test account is needed too.

**Comment by ryanbr** [comment]
Free to DM via twitter @fedevegili   on https://twitter.com/fanboynz with details to replicate it

**Comment by fedevegili** [comment]
> @fedevegili could you provide the steps to reproduce the issue ? I guess a test account is needed too.

Sure I can! These steps are for a testing environment, hope it is not a problem.

Steps to reproduce:
1. Go to https://hire-staging-sierra.jobscore.com/login
2. Login with: ```ublock@origin.com``` / ```ublock1!```
3. Go to https://hire-staging-sierra.jobscore.com/beta/employer/candidate/list
4. Click on the "action" button in any row, then "Start Interview" (![screenshot](https://i.imgur.com/0NtGHQv.png))
5. The error will happen (![screenshot](https://i.imgur.com/xBEM41s.png))

**Comment by ryanbr** [comment]
`https://hire-staging-sierra.jobscore.com/employer/interviews/new?candidate_card_id=dHVM1HDEvd4Oz4q9wbByui&http_referer=%2Fbeta%2Femployer%2Fcandidate%2Flist&job_id=c9tK7CokKr64r-dIMc0b1-&template_id` full url being blocked
