### ISSUE TITLE
nightfallnews.com bypass

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#10514]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [x] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nightfallnews.com`

### Describe the issue

Nightfall News stops users from preceeding with the slideshow when Google banners don't show. [Click Here](https://nightfallnews.com/error/120)

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 94.0.4606.114

### Settings

<details>
My rules:
||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 https://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 https://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 https://pagespeed.web.dev
pagespeed.web.dev##.glAfi

</details>

**Comment by mapx-** [comment]
> Nightfall News stops users from preceeding with the slideshow when Google banners don't show

Example page ?
