### ISSUE TITLE
Anti-adblock in letsmakeiteasy.tech

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10512]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://letsmakeiteasy.tech/`

### Describe the issue

Wait about 30-60 seconds, an anti-adblock overlay appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/142598166-2d6de80b-d5bc-4c61-9a3b-cce4112553bb.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

**Comment by mapx-** [comment]
The site seems to be broken, even disabling completely uBO I get anti adb
However, a cosmetic filter will be ok ..

`letsmakeiteasy.tech###quads-myModal`

**Comment by okiehsch** [comment]
> The site seems to be broken 

The page load is very slow on my end, I suspect that they check if the ads are loaded in a certain time frame and if they aren't the anti adblock triggers.

**Comment by mapx-** [comment]
Even without uBO it's the same behaviour on my end

**Comment by okiehsch** [comment]
That's what I meant, the ads are loading very slowly even if I disable uBO, so that's a possible explanation for the site blocking everyone.
