### ISSUE TITLE
[NSFW] Ads and incorrect refreshing in xxxbule.com

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10510]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://www.xxxbule.com/sex-clips/best-porn-free-streaming/`

### Describe the issue

There are ads at the right side and at the bottom. Also clicking refresh triggers popup and redirects to a different URL.

### Screenshot(s)

[NSFW Screenshot 1](https://i.ibb.co/m0M0T6w/image.png)
[NSFW Screenshot 2](https://i.ibb.co/19Sb9BG/image.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

There are also some suspicious `xhr` and `script` links.

Proposed filters:

```
||xxxbule.com/xb/xb.js$script,1p
||xxxbule.com/ain.php$xhr,1p
xxxbule.com##.style75
xxxbule.com##center
xxxbule.com##+js(set, popit, false)
```

**Comment by Yuki2718** [comment]
It was fixed and then the fix was removed: https://github.com/uBlockOrigin/uAssets/commit/a3769193958f063451c07cefff19d84727c125a3 We don't fix porn farm.
(Also reported to AG: https://github.com/AdguardTeam/AdguardFilters/issues/100499)

**Comment by mapx-** [comment]
still working, no redirections, no popups using

`||xxxbule.com^$csp=script-src`

**Comment by Yuki2718** [comment]
> 
> `||xxxbule.com^$csp=script-src`

Where's this filter? I don't see in default lists. Regional?

**Comment by mapx-** [comment]
no no meaning it can be added even blocking all scripts and the site still working

**Comment by Yuki2718** [comment]
Ah, got it. You'll see I added (and removed) `*$inline-script,domain=xxxbule.com` in past as scriptlet had race condition. Anyway, I don't fix this but if you think it's okay to fix, go ahead.

**Comment by mapx-** [comment]
I guess is much better to have such a filter otherwise 99% of users will get lots of crap

**Comment by Yuki2718** [comment]
I personally agree, but you know the internal discussion.

**Comment by Yuki2718** [comment]
Maybe one csp or inline-script fitler to add domain only is not bad, I guess.

**Comment by mapx-** [comment]
This 1 it's also a .. normal site, real videos, we just cut off all the crap using a "brutal" filter
