### ISSUE TITLE
Disable Adblock splash at vipbox.lc

### ISSUE THREAD

**Issue by MPA2003** [uBlockOrigin/uAssets#10525]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Video keeps going out with a text to remove adblock.
`https://www.vipbox.lc/ufc-fight-night-prelims-1-live`

uBlock Origin 1.38.6
Version 96.0.4664.45 (Official Build) (32-bit)

My current filter:
```
! 2021-08-22 https://www.youtube.com
www.youtube.com##.ytp-ce-covering-overlay

! 2021-08-29 https://www.nytimes.com
www.nytimes.com##.css-1xkts56
www.nytimes.com##.css-1n69xkm
www.nytimes.com###gateway-content

! 2021-09-08 https://www.youtube.com
www.youtube.com##.ytp-ce-element-show.ytp-ce-size-853.ytp-ce-top-right-quad.ytp-ce-video.ytp-ce-element > .ytp-ce-element-shadow
www.youtube.com##.ytp-ce-size-853.ytp-ce-top-right-quad.ytp-ce-element-show.ytp-ce-video.ytp-ce-element > .ytp-ce-covering-shadow-top
||i.ytimg.com/vi/JH_KAxZQeDM/maxresdefault.jpg$image
||i.ytimg.com/vi/JH_KAxZQeDM/maxresdefault.jpg$image
www.youtube.com##.ytp-ce-size-853.ytp-ce-top-left-quad.ytp-ce-element-show.ytp-ce-video.ytp-ce-element > .ytp-ce-element-shadow
||i.ytimg.com/vi_webp/STlM13qzrcY/maxresdefault.webp$image
www.youtube.com##.ytp-ce-size-853.ytp-ce-top-left-quad.ytp-ce-element-show.ytp-ce-video.ytp-ce-element > .ytp-ce-covering-shadow-top
||i.ytimg.com/vi_webp/STlM13qzrcY/maxresdefault.webp$image
||i.ytimg.com/vi/JH_KAxZQeDM/maxresdefault.jpg$image

! 2021-09-28 https://www.youtube.com
www.youtube.com##.ytp-ce-covering-image
www.youtube.com##.ytp-ce-element-show.ytp-ce-size-853.ytp-ce-top-left-quad.ytp-ce-video.ytp-ce-element
```

### A specific URL where the issue occurs

`https://www.vipbox.lc/ufc-fight-night-prelims-1-live`

### Steps to Reproduce

1. accessed with Ublock on
2. accessed with ublock off
3. accessed after updating ublock

### Expected behavior

Expected to watch streamed sports videos. 

### Actual behavior

video plays momentarily then shuts off with a text asking to disable adblock

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Chrome Version 96.0.4664.45 (Official Build) (32-bit)

### Operating System and version

Window 11

**Comment by mapx-** [comment]
remove all your custom filters for vipbox, use only the default lists and test again after updating all lists

**Comment by MPA2003** [comment]
> 

I don't see anything for vipbox in my filters?  Anyway I updated all lists and tested.  Still the same result.

**Comment by mapx-** [comment]
testing a live channel and it's all fine on my side

`https://www.vipbox.lc/tennis-channel-1-live`

**Comment by mapx-** [comment]
You should tell me exactly what server you are using

**Comment by MPA2003** [comment]
> You should tell me exactly what server you are using

I don't use a server. I am using a PC to connect to the internet. 

This is what I am seeing:  `https://ibb.co/gVHbxgv`

**Comment by mapx-** [comment]
Are you using some other blocking extension ? Keep only uBO and test again

**Comment by MPA2003** [comment]
> 

I use Poper Blocker for pop ups. I'll remove and retest standby.

**Comment by MPA2003** [comment]
Okay. I found the problem.  Windscribe VPN has it's own brand of anti-tracking, adblocking, pop blocking features that are on, even when you aren't connected to the VPN. smh.

I unclicked everything and everything is perfect now.   Much thanks.

**Comment by gorhill** [comment]
>  Windscribe VPN has it's own brand of anti-tracking, adblocking, pop blocking features

It's not their own brand, they are using a dated version of uBlock Origin, see <https://twitter.com/gorhill/status/1409911991154757634>.

**Comment by iam-py-test** [comment]
> > 
> 
> I use Poper Blocker for pop ups. I'll remove and retest standby.

@MPA2003 that extension is known to be malicious. It is recommended you remove it

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/101335
@yegors You're putting unnecessary burden on us filter author. Don't you mind?

**Comment by felix-22** [comment]
> iam-py-test : https://github.com/uBlockOrigin/uAssets/issues/10525#issuecomment-977836995 :+1: 
> >
> > MPA2003 : I use Poper Blocker for pop ups. I'll remove and retest standby.
> 
> @ MPA2003 that extension is known to be malicious. It is recommended you remove it

You confused Popup Blocker with Popup Blocker Pro, only the latter one is malicious.
It's like confusing uBlock Origin with uBlock.

**Comment by iam-py-test** [comment]
> > iam-py-test : [#10525 (comment)](https://github.com/uBlockOrigin/uAssets/issues/10525#issuecomment-977836995) 👍
> > > MPA2003 : I use Poper Blocker for pop ups. I'll remove and retest standby.
> > 
> > 
> > @ MPA2003 that extension is known to be malicious. It is recommended you remove it
> 
> You confused Popup Blocker with Popup Blocker Pro, only the latter one is malicious. It's like confusing uBlock Origin with uBlock.

I was just repeating a comment from internal discussion

**Comment by gorhill** [comment]
> You confused Popup Blocker with Popup Blocker Pro, only the latter one is malicious.

This [Poper Blocker](https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche/related) extension sends browser history to `api2.poperblocker.com` when you agree to the "Block overlay" feature -- I am pretty sure in the past it was doing this silently, I might have tweeted about this, and they have been forced to disclose as per better enforced CWS rules. I would never suggest someone to install and use this, the reason they give to do so makes no sense.

**Comment by felix-22** [comment]
Well, it's still available in the Google Chrome Store, I didn't know that even such popular extensions (2 000 000+) can't be trusted these days anymore, maybe we can't trust the whole Google, given they still keep such extension available. Compared to other extensions: Nano Defender which was quickly removed from all stores after it went malicious, I don't get point why Google keep other malicious extensions: Popup Blocker unremoved then.

**Comment by gorhill** [comment]
As said, it's opt-in now, they have a privacy policy -- and it's not because they comply with Google's requirements that they should be trusted when the provided rationale to record browsing history makes no sense. Extensions doing that sort of things are the opposite of what uBO stands for. Whoever is free to install it, and we are free to warn about this here given what uBO stands for.

**Comment by iam-py-test** [comment]
Maybe if enough regular people learn about this & start fighting back, these people will stop

**Comment by felix-22** [comment]
Well, if "the provided rationale to record browsing history makes no sense." Google should not allow such policy and such extension, unless Google doesn't care about third-party policies and it's users. Reading comments of Popup Blocker, so many positive opinions, and couldn't find negative, so many users unaware and uncle Google see no issue.

**Comment by gorhill** [comment]
Ok, we disagree on a topic, this happens.

Locking issue because no point keeping it ongoing.
