### ISSUE TITLE
dropgalaxy.in

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#10522]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dropgalaxy.in/tmq142h4u0sk`

### Describe the issue

The website detects the adblock after the timer expires and I click on "Create download link" button.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/142736378-a2230b5b-b12f-4235-b750-27a56a9589ef.png)

### uBlock Origin version

1.38.6

### Browser name and version

Chrome  96.xx

### Settings

No changes have been made. The settings are default ones.

**Comment by blazesprings** [comment]
Now the behavior is different.
When you go the above link, it redirects to dropgalaxy.in and when the timer  starts, redirects back to the
old link (above one).

**Comment by JobcenterTycoon** [comment]
I get redirected to `techyneed.com`, after waiting 15 seconds i can download

**Comment by gorhill** [comment]
So apparently this can be reproduced with a VPN server in India or Portugal: <https://www.reddit.com/r/uBlockOrigin/comments/rtrhcb/ubo_detected_on_httpsdropgalaxyin6n4db8pgl08b/> (I haven't tried yet).
