### ISSUE TITLE
informaxonline.com

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#10524]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://informaxonline.com/dl/api.php?info=aHR0cHM6Ly9saW5rLmFkc2xpbmtmbHkub25saW5lL05QaEZ5dkI=`

### Describe the issue

1. Goto superonleech.biz CBOX
2. Generate a download link
3. When you click the download button, it  redirects to informaxonline  page (above). There you see the anti adblock
message.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/142749647-e790ffa2-f24b-49f8-b000-e133b6abcd9d.png)

### uBlock Origin version

Ublock Origin 1.38.6

### Browser name and version

Chrome 96.xx

### Settings

No changes

**Comment by dumbusernameidk** [comment]
anti-adblock, not allowed to use context menus, no dev tools, etc.

`informaxonline.com##+js(noeval)` worked for me.
