### ISSUE TITLE
Fingerprint script in go4hosting.com?

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10520]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://go4hosting.com/`

### Describe the issue

There's a suspicious script link that I'm not sure if it's a script for browser fingerprinting or not.

`https://js.stripe.com/v3/fingerprinted/js/m-outer-639174098ea8fe7fede6fa654790e8ec.js`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/142727672-779e7aca-972a-4397-86e1-26435f63bd14.png)

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

If it's a script for fingerprinting, should we block it globally or not?

`||stripe.com/v*/fingerprinted/js/*$script`

**Comment by gorhill** [comment]
> should we block it globally or not?

If you make the case this breaks no sites anywhere, it could be blocked as third-party.

**Comment by JobcenterTycoon** [comment]
There are already issues about this
`https://github.com/easylist/easylist/issues?q=stripe`
But blocking causes breakage thats why no filter got added

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Blocking stripe can cause issues, which is why it's not blocked

**Comment by stephenhawk8054** [comment]
Ah I see, tks for your info.

**Comment by uBlock-user** [comment]
Script calls `m.stripe.network/inner.html`, Add `||m.stripe.network^`

**Comment by gorhill** [comment]
Note that not all fingerprinting's purpose is to track people, it's also often use as a security measure. For example, a site might want to know if you are logging in from a known device, as logging in from a never-seen-before device could be deemed suspicious and special security steps might be required in such case. There are also services which may want to save preferences on a per-device basis.
