### ISSUE TITLE
tw-goldenwinner-57.com: ads

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uAssets#10536]
### URL address of the web page

`https://www.tw-goldenwinner-57.com/`

### Category

ads

### Describe the issue

The entire site is an ad destination site, as discussed in https://github.com/uBlockOrigin/uBlock-issues/issues/1829 .

### Configuration

```yaml
uBlock Origin: 1.38.7rc1
Chromium: 98
filterset (summary): 
  network: 77867
  cosmetic: 39213
  scriptlet: 16210
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 60949-6, 27m
    easyprivacy: 26278-20, 25m
    plowe-0: 3698-808, 23m
    ublock-abuse: 67-0, 19m
    ublock-badware: 3420-56, 14m
    ublock-filters: 29740-113, 12m
    ublock-privacy: 186-3, 10m
    ublock-unbreak: 1690-38, 8m
    urlhaus-1: 8448-0, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2904
  launchFromSelfie: false

```

**Comment by iam-py-test** [comment]
This is a scam website:
![image](https://user-images.githubusercontent.com/84232764/142873089-cd07c382-b2a1-4cee-bb31-d3c4372ba20d.png)

**Comment by jidanni** [comment]
Thanks.
Actually it is asking for your city, phone number and birth date in the image above.

(By the way, at first I thought the two other windows you show were relevant, but after looking at them a long time,
it seems they are just part of an uncropped total desktop screenshot. Maybe crop them out next time. Thanks.)

**Comment by iam-py-test** [comment]
> Thanks. Actually it is asking for your city, phone number and birth date in the image above.
> 
> (By the way, at first I thought the two other windows you show were relevant, but after looking at them a long time, it seems they are just part of an uncropped total desktop screenshot. Maybe crop them out next time. Thanks.)

I realized that as soon as I translated it. The other Windows were part of something else I was doing on that VM; I just forgot to crop it/enlarge the scam site
