### ISSUE TITLE
Popup in cricstream.me

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10533]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://cricstream.me/`

### Describe the issue

Click on `World Cup Stream` button, a popup appears.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

No change

### Notes

Proposed filter:

`cricstream.me##+js(acis, JSON.parse, break;case $.)`

**Comment by No-ADS** [comment]
`https://cricstream.me/sri-lanka-vs-west-indies-live/stream-1`

<details>

![2021-11-22_081249](https://user-images.githubusercontent.com/94611448/142809592-642699f8-28f0-4e38-a560-6e24deacc7b2.png)
<summary>Screen</summary>
</details>

**Comment by No-ADS** [comment]
@mapx- 
<details>

![2021-11-22_081249](https://user-images.githubusercontent.com/94611448/142809592-642699f8-28f0-4e38-a560-6e24deacc7b2.png)
<summary>Screen</summary>
</details> ?

**Comment by mapx-** [comment]
These sites have often used that cosmetic filter (as bait) to fight back, so I prefer not adding it. Just click X.
