### ISSUE TITLE
NightFallNews.com Error 120

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#10538]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [x] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nightfallnews.com/?ref_id=c14cb872&extra_data=&new=true&banner_id=10`

### Describe the issue

Go through the slideshows. On slideshow 5, when you click the "next" button, it redirects you to an error page `https://nightfallnews.com/error/120` 

### Screenshot(s)

![nightfallnews](https://user-images.githubusercontent.com/62780210/142901990-9f475568-3e7c-4e9e-ad82-83332199ee1b.png)

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 94.0.4606.114

### Settings

My filters:

<details>
||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 https://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 https://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 https://pagespeed.web.dev
pagespeed.web.dev##.glAfi

! 2021-11-20 https://cointiply.arkadiumarena.com
cointiply.arkadiumarena.com##.AdBlocker__header___3haT115M
cointiply.arkadiumarena.com##.AdBlocker__title___3KRapx8e
cointiply.arkadiumarena.com##.AdBlocker__text___2OgB4Aol
cointiply.arkadiumarena.com##.AdBlocker__instructions___wQxCyHYS

||linksynergy.com
</details>

Trusted sites:
<details>
about-scheme
# chrome-extension-scheme
chrome-scheme
edge-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
wyciwyg-scheme
0redirc.com
123movies.com
4g27x3fk.optimalworkshop.com
a-ads.com
account.jetbrains.com
account.venmo.com
ad-maven.com
ad4game.com
adbl0ck.com
adcash.com
adcash.myadcash.com
adclerks.com
adhall.com
admanmedia.com
admedia.com
admin.advertise.com
adonly.com
adservice.io
adshnk.com
adshop.infolinks.com
adshrink.it
adstargets.com
adsvert.com
adversal.com
adx1.com
affiliate-program.amazon.com
ambassador.surveytime.io
analytics.google.com
app.any.run
app.coinmiles.io
app.crisp.chat
app.cryptotab.farm
app.getmoocash.com
app.guard.io
app.lambdatest.com
app.reklaimyours.com
app.screencastify.com
app.trk12.com
applock.top
apprefaculty.pro
apps.royalbank.com
authorize.kobo.com
axonix.com
bankingbux.com
beta.publishers.adsterra.com
betteradsystem.com
bitland.pro
bits.re
bux.dev
cellxpert.com
cint.insightexpressai.com
cleanrb.art
clickpapa.com
clipchamp.com
coinpot.in
console.paperspace.com
cr-brands.net
cryptobrowser.site
cryptocoinsad.com
dash.cloudflare.com
dash.getastra.com
dash.teams.cloudflare.com
dashboard.blomp.com
dashboard.fingerprintjs.com
diabasewoodhouse.xyz
dig.ps-di.com
digitalflare.io
discord.com
donotpay.com
eds.ca.matchbox.maruhub.com
en.netaffiliation.com
evadav.com
freerobuxnow.netlify.app
gadsbee.com
gamebassadors.net
getfiles.co
go.getastra.com
go.libertex.com
go.stormgain.com
goggle.proasdf.com
googleads.github.io
guard.io
howsliferightnow.com
hyperbeam.com
id.subway.com
imonomy.com
in-appadvertising.com
instabayi.com
intellipopup.com
intl.cloud.tencent.com
invitation.codes
invited.tv
jsfiddle.net
jump.ogtrk.net
lifeinstride.com
live.browserstack.com
lnk.parts
members.cpabuild.com
members.ogads.com
mgcash.com
mytrafficvalue.com
neverinstall.com
nomobileads.com
now.gg
opinion.yunosurveys.com
order.subway.com
ozzyfakeid.com
panelistconsent.google.com
partners.house
partners.stackcommerce.com
phoenixads.co.in
platform.33across.com
platform.engageya.com
platform.io
platform.sharethis.com
pointclicktrack.com
popbounty.com
popmyads.com
popunder.net
popundertotal.com
prebid.org
pro.moat.com
prod.uhrs.playmsn.com
propellerads.com
ps.opinionetwork.com
ptc.cointiply.com
publisher.adsmain.com
publishers.adsterra.com
putlocker.one
rblx.land
rbxexchange.com
rbxshop.net
reachnetwork.pro
ref.mgid.com
register.silverscreen.cc
registrace.seznam.cz
researchonmobile.com
reward.tremendous.com
s.cint.com
s.getastra.com
secure.hulu.com
secure.redirect.com
securely-send.com
securityscan.getastra.com
shoppy.gg
shorte.st
smallpdf.com
smartyads.com
spectrumsurveys.com
store.steampowered.com
superpay.me
survey-api.com
survey.saysoforgood.com
surveyquest.netlify.app
surveys.eliteopinio.com
surveys.gobranded.com
surveys.ipsosinteractive.com
surveys.sample-cube.com
sw.cint.com
take.yunosurveys.com
takipcikrali.com
theoremreach.com
tracking.ogmobi.com
trafficg.com
trckapp.com
trk.contentquestclub.com
trk.hamster-nest.com
trk.sportsalerts.club
trk301.com
unlck.com
user.hilltopads.com
v3.rtrack.live
vancouverrestores.vonigo.com
vectordash.com
vendors.paddle.com
vidox.net
viral782.com
visitweb.com
vln.easysurveys.net
voluum.com
wbidder.online
wbidr.com
wboptim.online
web.archive.org
web.bitlabs.ai
web.peanutlabs.com
whitemobi.com
windowsdefender.site
wordpress.com
workplace.clickworker.com
wss.pollfish.com
www.acer.com
www.adveric.net
www.advertise.com
www.adworkmedia.com
www.apple.com
www.beermoneyforum.com
www.binance.com
www.blomp.com
www.buybitcoinworldwide.com
www.casinorewards.com
www.checkout51.com
www.citizengoods.com
www.comscore.com
www.cpalead.com
www.dontpayfull.com
www.dosh.com
www.easyhits4u.com
www.emodoinc.com
www.engageya.com
www.getastra.com
www.getmoocash.com
www.grammarly.com
www.gridgaming.io
www.harrispollonline.com
www.hometesterclub.com
www.idle-empire.com
www.infolinks.com
www.insightexpress.com
www.jobsnearme.online
www.komoona.com
www.leadboltapps.com
www.leovegasaffiliates.com
www.minecraft.net
www.myadcash.com
www.okayfreedom.com
www.okex.com
www.opinionoutpost.ca
www.opinionoutpost.com
www.pao4.com
www.paypal.com
www.peanutlabs.com
www.reviews.co.uk
www.rewardsaffiliates.com
www.rotate4all.com
www.sample-cube.com
www.screencastify.com
www.shrink-service.it
www.skillwise.com
www.smaato.com
www.soundtrap.com
www.star-clicks.com
www.subway.com
www.superpay.me
www.terabox.com
www.thezumiezstash.ca
www.tradingview.com
www.trellian.com
www.veriff.com
x.bluestacks.com
yourezads.com
ys.cint.com
yuumari.com
</details>

### Notes

It's very annoying as you have to wait for the countdown timer when adblock is disabled. Clearly the site is intended for advertising, not news, purposes. Their ads are aggresive and there's too many banners and native ads.

**Comment by uBlock-user** [comment]
Redirection is server-sided, blocking the redirection via `##^responseheader(location)` leaves an empty page.
