### ISSUE TITLE
Cdn static io plugins cause image stuck in circle loading gif

### ISSUE THREAD

**Issue by ikhoeyZX** [uBlockOrigin/uAssets#10546]
### URL address of the web page

all manga from this server, 

for example:

`https://www.lianscans.my.id/the-office-lady-who-took-in-a-wild-shota-chapter-12-bahasa-indonesia/`

### Category

.

### Describe the issue

when load page, web page show loading circle (with data still transfering) but after webpage finish load all data, loading circle not gone (it's should gone and show picture behind it), force disable JS can fix it *BUT* it will cause stuck in popup if read *ehm* 18+ manga

### Screenshot(s)

with JS enable:

![Screenshot_20211123-213525](https://user-images.githubusercontent.com/79812109/143033753-dd7d5778-dedb-4067-bc3d-e918175219f4.png)

when JS are disabled :
![Screenshot_20211123-213658](https://user-images.githubusercontent.com/79812109/143034179-dc075084-a830-4e2c-ae62-05222925bb68.png)

### Configuration

.

**Comment by uBlock-user** [comment]
Images load fine for me but I have to wait few seconds, this is a site design issue.

**Comment by iam-py-test** [comment]
This site is blocked as malware for me.

**Comment by krystian3w** [comment]
Try with disabled regional lists like Indonesia/Malaysia.
