### ISSUE TITLE
Disappearing search results on nytimes.com/search

### ISSUE THREAD

**Issue by pythoncoder42** [uBlockOrigin/uAssets#10545]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nytimes.com`

### Describe the issue

When using the "uBlock filters" list on nytimes.com, search results do not appear. The following filter seems to be causing the search results to be hidden:

nytimes.com##[data-testid="StandardAd"]:upward(div[class])

This filter may be useful on other pages, but it should be disabled on the page nytimes.com/search .

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

Added this custom filter to fix the problem:

nytimes.com#@#[data-testid="StandardAd"]:upward(div[class])

I am not sure whether disabling it on the entire site causes ads to be shown.

**Comment by uBlock-user** [comment]
> I am not sure whether disabling it on the entire site causes ads to be shown.

Brings back ad placeholder on the homepage

**Comment by pythoncoder42** [comment]
Adding this filter should fix that problem:

www.nytimes.com##.e1xxpj0j0

Here are all my other custom filters for nytimes.com:

```
! Ads blocked but box still appears
! 1/29/2019 https://www.nytimes.com
www.nytimes.com##div.pz-ad-box.pz-section-filled
www.nytimes.com###xwd-ad-top
www.nytimes.com###xwd-ad-bottom
! 1/30/2019 https://www.nytimes.com
www.nytimes.com##[class^=Ad-]

! snip

! 2021-02-26 https://www.nytimes.com
www.nytimes.com##[id^=story-ad-]
```

**Comment by uBlock-user** [comment]
We have `:matches-path` will use that.

**Comment by Yuki2718** [comment]
@uBlock-user Just making more specific seems to be enough.

**Comment by uBlock-user** [comment]
Sure, if you say so, I avoided making it specific because there was a breakage report before too due to this filter in EL.

**Comment by Yuki2718** [comment]
An alternative fix is just to remove `@@||nytimes.com^*/adslot-$script,xhr,badfilter` which I added only because I don't like allowing this only for PH.

**Comment by uBlock-user** [comment]
Lets wait and see if there's another breakage report any time soon.
