### ISSUE TITLE
Invalid filter

### ISSUE THREAD

**Issue by realodix** [uBlockOrigin/uAssets#1054]
### Screenshot(s)

![cats](https://user-images.githubusercontent.com/1314456/34196761-0e27d2e2-e596-11e7-921f-63ab7f401dbb.jpg)

### Versions

- Browser/version: FF 58
- uBlock Origin version: 1.14.22

**Comment by okiehsch** [comment]
The network filter was a typo fixed with https://github.com/uBlockOrigin/uAssets/commit/42a2b5c116119ed89df94a4c8717a426213273ae
The cosmetic filters are Chrome specific filters and invalid with Firefox, so uBO rejects them.
See https://github.com/uBlockOrigin/uAssets/issues/505

**Comment by garry-ut99** [comment]
```
17:49:41​Invalid extended filter in ublock-filters: financerites.*##p:has-text([ad_)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: masterduelmeta.com##:xpath(//*[contains(text(),"adblock")]):upward(3)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: akvi.icu##:xpath(//*[contains(text(),"Disable")])​​​​​​
17:49:41​Invalid extended filter in ublock-filters: trakt.tv##:xpath(//*[(text()='Advertisement')]/..)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: trakt.tv##:xpath('//*[(text()='Advertisement')]/..')
17:49:41​Invalid extended filter in ublock-filters: sports24.*##:xpath(//*[contains(text(),"Watch HD")])​​​​​​
17:49:41​Invalid extended filter in ublock-filters: washingtonpost.com##:xpath(//*[(text()='AD')]/..)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: washingtonpost.com##:xpath('//*[(text()='AD')]/..')​​​​​​
17:49:41​Invalid extended filter in ublock-filters: ebay.*##.s-item:has-text(Sponsored):xpath(//*[string-length(@aria-labelledby) = 8]):upward(.s-item)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: t-online.de##^script:has-text(toscr')​​​​​​
17:49:41​Invalid extended filter in ublock-filters: ettv.*##:xpath(//*[contains(text(),"VPN")]):upward(2)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: 1337x.*,x1337x.*,1337x.unblock2.xyz,1337x.unblocked.*,1337x.unblockit.*##:xpath(//*[contains(text(),"Hide your IP")]/..)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: spankwire.com##:xpath(//*[contains(text(),"Advertisement")]):upward(1)​​​​​​
17:49:41​Invalid extended filter in ublock-filters: primewire.*##:xpath(//*[contains(text(),"Sponsored")]):upward(2)
```

Some unescaped filters are missing their escaped copies.
Also some escaped copies seem to be inproperly escaped:
`17:49:41​Invalid extended filter in ublock-filters: trakt.tv##:xpath('//*[(text()='Advertisement')]/..')` 
`17:49:41​Invalid extended filter in ublock-filters: washingtonpost.com##:xpath('//*[(text()='AD')]/..')​​​​​​`
https://github.com/uBlockOrigin/uBlock-issues/issues/2400#issuecomment-1344424479
https://github.com/gorhill/uBlock/commit/a71b71e4c8a2037fc68970bc8912a76732edaade

**Comment by garry-ut99** [comment]
I've found another bunch of escaped copies which no longer work due recent uBO change that has made them not-working again, see **UPDATE** part  of the comment above.
