### ISSUE TITLE
Anti-AdBlock: 9anime.to and fmovies.to

### ISSUE THREAD

**Issue by SjoerdPennings** [uBlockOrigin/uAssets#10547]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`9anime.to`
`fmovies.to`

### Describe the issue

The site is inaccessible, only showing a black screen with the text `AdBlock breaks it!`

### uBlock Origin version

Latest

### Browser name and version

Chrome (Latest)

### Settings

Default Settings

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/64ba61d66c34a79c0890f5dbe78047c9bd40ff65

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/381ddc90c857b302b5b99c964985b81587c063f7
