### ISSUE TITLE
Filters applied to query params

### ISSUE THREAD

**Issue by Robbilie** [uBlockOrigin/uAssets#1055]
### URL(s) where the issue occurs

`https://br.inyour.space/?s=4064&b=7873080&e=150&t=uvb`  
Url that is blocked:
`https://esi.tech.ccp.is/v1/characters/names/?user_agent=br.inyour.space+%28Lucia+Denniard%29&character_ids=616832201`

### Describe the issue

```
Static filter .space^$third-party found in:
uBlock filters – Resource abuse
```
The user_agent param triggers that filter, its a webapi queried from br.inyour.space which gets the user_agent passed to.

### Versions

- Browser/version: Version 62.0.3202.94 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.14.22

### Settings

- AAK-Cont Filter For uBlock Origin

### Notes

Opened the logger to find out what was blocking the url.

**Comment by gorhill** [comment]
Not sure You are not providing a URL where the issue can be reproduced, nothing is blocked when I try your URL above.

**Comment by Robbilie** [comment]
there, updated it…

**Comment by okiehsch** [comment]
The bad filter `.space^$third-party` introduced with https://github.com/uBlockOrigin/uAssets/commit/83d6a99cc5c1f38bb644e1b390ef48316544a3f5#diff-04acddb39c958962e830b71881e4416bR108 was fixed with https://github.com/uBlockOrigin/uAssets/commit/ae96dfbc48eb0cbd7fa180a4d66bb388b759456d

**Comment by gorhill** [comment]
Furthermore, shouldn't filters such as `.cf^` or `.space^` really be `||cf^` and `||space^`, to avoid more false positives?

**Comment by Robbilie** [comment]
right, after purging and refreshing the caches it works now :)

**Comment by okiehsch** [comment]
These filters were copied from `EasyPrivacy` https://github.com/uBlockOrigin/uAssets/commit/33f5f2e52141cde32cbfa5800f96d2e3a9ef182c#commitcomment-26348339, so you would have to "`badfilter`them and then add the better changed version.
