### ISSUE TITLE
thebridge.in: ads

### ISSUE THREAD

**Issue by throwayo** [uBlockOrigin/uAssets#10552]
### URL address of the web page

`https://thebridge.in/`

### Category

1. ads OR
2. overlay

### Describe the issue

When visiting the site a overlay covers the page which has timeout of 5 seconds where the ad is displayed. When using UBO the ad isn't visible but the page is blank for 5 seconds. When UBO is disabled, the ad is seen for the 5 seconds.
I have also attached a screenshot for better clarity

### Screenshot(s)

1. UBO enabled
![image](https://user-images.githubusercontent.com/94930742/143092043-b81098f5-8a7e-4339-af2b-1bac75997db6.png)

2. UBO disabled
![image](https://user-images.githubusercontent.com/94930742/143092822-06315a77-e4ec-47c3-ad37-046231d38ada.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 95
filterset (summary): 
  network: 79183
  cosmetic: 39203
  scriptlet: 16081
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30188-28, 1m
    ublock-badware: 3430-1, 1m
    ublock-privacy: 183-0, 1m
    ublock-abuse: 70-0, 1m
    ublock-unbreak: 1701-0, 1m
    easylist: 60994-541, 1m
    easyprivacy: 26306-474, 1m
    urlhaus-1: 9687-0, 1m
    plowe-0: 3699-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1809
  launchFromSelfie: false
```
</details>

**Comment by uBlock-user** [comment]
`thebridge.in##.roadblocker-ad-content-wrap`

@ryanbr
