### ISSUE TITLE
Adblock breaks it! error

### ISSUE THREAD

**Issue by Ryuji12** [uBlockOrigin/uAssets#10560]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

After visiting fmovies.to and waiting several seconds. The page layout disappears and Adblock breaks it appears.

### A specific URL where the issue occurs

fmovies.to

### Steps to Reproduce

visit fmovies.to
wait 5-10 secs
witness the issue

### Expected behavior

Prior to 1.39,  by using the dev cycle versions everything worked correctly

### Actual behavior

Page is broken

### Configuration

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 387970
  cosmetic: 111176
  scriptlet: 32033
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter.txt: 236233-0, 19h.25m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.19h.37m
    adguard-annoyance: 47653-147, 1d.19h.37m
    adguard-generic: 61614-665, 1d.19h.37m
    adguard-spyware: 25107-705, 1d.19h.37m
    adguard-spyware-url: 388-12, 1d.19h.37m
    curben-phishing: 23952-23, 1m
    curben-pup: 371-0, 1m
    dpollock-0: 16965-222, 1d.19h.37m
    ublock-annoyances: 4298-177, 1d.19h.37m
  default: 
    easylist: 60964-1021, 1d.19h.37m
    easyprivacy: 26279-10836, 1d.19h.37m
    plowe-0: 3699-1279, 1d.19h.37m
    ublock-abuse: 70-0, 1d.19h.37m
    ublock-badware: 3421-182, 1d.19h.37m
    ublock-filters: 29744-3140, 1d.19h.37m
    ublock-privacy: 186-24, 1d.19h.37m
    ublock-unbreak: 1690-103, 1d.19h.37m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 37 redacted]
hostRuleset: 
  added: [array of 1456 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  dynamicFilteringEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  cloudStorageCompression: false
supportStats: 
  launchToReadiness: 2843
  launchFromSelfie: false
```

**Comment by mapx-** [comment]
update your lists
