### ISSUE TITLE
tufutbolpro.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1056]
URL(s) where the issue occurs

http://www.tufutbolpro.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
`http://www.tufutbolpro.com/espn-2/`

ADS

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
