### ISSUE TITLE
Breaking QuestionPro for Customers

### ISSUE THREAD

**Issue by zolingonsalves** [uBlockOrigin/uAssets#10561]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://internalcommunicationssurvey.questionpro.com.au/`

### Describe the issue

QuestionPro uses a CDN to deliver static content like JS, CSS & media files from its CDN url which is cdn.questionpro.com 

Ublock seems to be blocking the cdn url. 

questionpro.com.au & cdn.questionpro.com are both owned by QuestionPro 

Please add a filter to avoid cdn.questionpro.com from getting blocked

### Screenshot(s)

https://www.screencast.com/t/o9iBKWzyd4E

### uBlock Origin version

1.38.6

### Browser name and version

Version 95.0.4638.69 (Official Build) (x86_64)

### Settings

Surveys are answered by QuestionPro customers, it is not feasible to ask every customer to make changes to the ublock settings to answer surveys.

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2f2474eae057fcec1c54ef995fc6df1a49feceaf
