### ISSUE TITLE
cutwin.com [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1057]
URL(s) where the issue occurs

https://cutwin.com/AAqlPAMV

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by xDarkARG** [comment]
Anti-Adblock It is a clone page @mapx-

`http://cut-w.in/AAqlPAMV`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://ctui.in/lDvf`

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by ghajini** [comment]
`https://cutwin.com/Mi7nR5j`

`||cutwin.com/sw.js$first-party`
