### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by 9Skrip** [uBlockOrigin/uAssets#10574]
### URL address of the web page

`https://open.spotify.com/playlist/743KiTHCKqKZEmdTzsCtjp`

### Category

breakage

### Describe the issue

After an Ad is blocked doesn't continue playing. Remains silent with an ad in the left corner. Playing can be only continued after page reload. Happens Randomly it can be 10 songs without the problem or 3.
All filters updated

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 91
filterset (summary): 
  network: 107639
  cosmetic: 75775
  scriptlet: 18073
  html: 599
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblockext.tpl: 1603-28, 32m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29835-276, 33m
    https://raw.githubusercontent.com/pafnuty/onlineConsultantBlocker/master/online-consultant.txt: 65-3, 32m
    RUS-0: 39951-3848, 32m
  default: 
    ublock-filters: 30144-125, 32m
    ublock-badware: 3440-1, 32m
    ublock-privacy: 183-0, 32m
    ublock-abuse: 70-0, 32m
    ublock-unbreak: 1701-0, 32m
    easylist: 60906-453, 3d.6h.46m
    easyprivacy: 26311-492, 32m
    urlhaus-1: 9538-0, 32m
    plowe-0: 3699-29, 32m
filterset (user): [array of 83 redacted]
trustedset: 
  added: [array of 27 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
  triggered: 
    no-cosmetic-filtering: open.spotify.com true
hostRuleset: 
  added: [array of 11 redacted]
urlRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 10597
  launchFromSelfie: true
```
</details>

**Comment by 9Skrip** [comment]
Made a log of the problem

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BWGyA_nmeYab2IY2hmLAP54mu0A2oj_eJRgAAABABILyu-R44AVjyoLmvgwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vqQJLRJzZ08yyPsACAuACAOoCGC82NDY1MDUyL3dlYi9kZXNrdG9wX3dlYvgC_NEekAOEB5gD0AWoAwHQBJBO4AQB0gUGEM-QxoAVkAYBoAYj2AYBqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAeAHC9IIBwiAYRABGB_YCAKACgWYCwHQFQGAFwE&sigh=-lPq-h1Zw_A&label=part2viewed&ad_mt=[AD_MT]` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BWGyA_nmeYab2IY2hmLAP54mu0A2oj_eJRgAAABABILyu-R44AVjyoLmvgwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vqQJLRJzZ08yyPsACAuACAOoCGC82NDY1MDUyL3dlYi9kZXNrdG9wX3dlYvgC_NEekAOEB5gD0AWoAwHQBJBO4AQB0gUGEM-QxoAVkAYBoAYj2AYBqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAeAHC9IIBwiAYRABGB_YCAKACgWYCwHQFQGAFwE&sigh=-lPq-h1Zw_A&label=vast_creativeview&ad_mt=[AD_MT]` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsveWMaZBQftdnVqz5wteHQ6zt8MAcvEJWT73H_THKEUNAXGXj1PIsRsoP3ZXlbaM0KpxnfLTshmJhZnq3kXpyPucHqwXbY0pmTn9Wzb3YIL1iuPbYWfE_Kn_2ZS15DDdqAMJ2vVOYyEMAFXFfi5WTB-odwNhRnEpHf1XggWV5SXB62q5JaRq0u4cccgvRm07pquOvnXXF11_oiYUB5z3EnHTLFjDjRDoj2MUPGr8Ai0Wge-m8Z8gHSGd5-mInLX6YfacHttVPwIJf7DO4ZxbRjJpnGOf9me9xCN1sl07aWci2KsnxEmuWpotmbtw4vJEk2H8kwNYPEYwQ&sai=AMfl-YSpGpPS4a-qe-jnRJhyqAljzmVDWxDJsTNUF3ZihTJlM91IvFulO-8m6ozO3kY3NIkjk0kn0sj0tNgU1L_BgaFG-pGBysz2levQgihma3Km_KxIirg&sig=Cg0ArKJSzMzlp9TvP45IEAE&uach_m=[UACH]&adurl=` |
| +1678 | noopmp3-0.1s | << | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/58e81dc468bd6b25685e01124435cdf6747cd7c0?1637863210_P7EeRlLtDhWssQlgPm8t7Qibxs8ln8KYnr98dFUzuaw=` |
| +1678 | \|\|scdn.co/audio/$media,redirect-rule=noopmp3-0.1s,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/58e81dc468bd6b25685e01124435cdf6747cd7c0?1637863210_P7EeRlLtDhWssQlgPm8t7Qibxs8ln8KYnr98dFUzuaw=` |
| +1678 | \|\|scdn.co/audio/$media,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/58e81dc468bd6b25685e01124435cdf6747cd7c0?1637863210_P7EeRlLtDhWssQlgPm8t7Qibxs8ln8KYnr98dFUzuaw=` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://ad.doubleclick.net/ddm/trackimp/N301002.4086549C3SPOTIFY/B26636137.317021512;dc_trk_aid=509625867;dc_trk_cid=159451361;ord=1760179607;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=;gdpr_consent=;ltd=?` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BkjTx_nmeYa_rII2hmLAP54mu0A3LxfONRgAAABABILyu-R44AVjDhuy6gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAKSEakCS0Sc2dPMsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhCy08DSFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=EG6ApLtBOJA&label=part2viewed&ad_mt=[AD_MT]` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjstvMMd4k9MByPqTCqKgCFn320V5GCS_AjnuLBxl4R3gdzuAU_Yvmo58nsqoQkfX8AjPOJl4amM9AtbSSZMdgorhVGsBkDVQ8SOz5CT3hspyIS_pITEA7Wc2lUWl2lwG2cOWCFQguqHYKVFkOFgW8s-Z_KFo-Q0_URbvgnR-o5AK1sbfB8j92uz7MLTvgsys4Qy6--aF60M-nbK4xxUnCOE3BOCU-HC1j7JbH3j4GfOL22ekvzKEW730rNuQ4ChP2cVELe5lWEpCyYyq3bJDb0a3evV8cSzbhRlUxir28utMb2_wDD2kWCPuu5DYo22JF9flMNwmWXhpMxGVCw&sai=AMfl-YT0DFnDGQDitvRdIsSf2YwrHbVbXS_S3htqyG4ZWqK4By-efQuU_l5Oj5qkCIL3y_EyRnGfS3U2IgW5YxnGxXbPP3U0yGzRJHsIkJac61izfJCsOqc&sig=Cg0ArKJSzI7DTi_xC7luEAE&uach_m=[UACH]&adurl=` |
| +1678 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BkjTx_nmeYa_rII2hmLAP54mu0A3LxfONRgAAABABILyu-R44AVjDhuy6gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAKSEakCS0Sc2dPMsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhCy08DSFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=EG6ApLtBOJA&label=vast_creativeview&ad_mt=[AD_MT]` |
| +1678 | noopmp3-0.1s | << | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637863210_lEYc-KiqtRnu4GQmkvTjCr--Vqu4whJ4tiAGZ9jAMLY=` |
| +1678 | \|\|scdn.co/audio/$media,redirect-rule=noopmp3-0.1s,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637863210_lEYc-KiqtRnu4GQmkvTjCr--Vqu4whJ4tiAGZ9jAMLY=` |
| +1678 | \|\|scdn.co/audio/$media,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637863210_lEYc-KiqtRnu4GQmkvTjCr--Vqu4whJ4tiAGZ9jAMLY=` |
| +903 | \|\|paypal.com/xoplatform/logger/api/logger | -- | `www.paypal.com` | 0,1 | beacon | `https://www.paypal.com/xoplatform/logger/api/logger` |
| +902 | \|\|paypal.com/xoplatform/logger/api/logger | -- | `www.audionebula.ca` | 0,3 | xhr | `https://www.paypal.com/xoplatform/logger/api/logger` |
| +902 | \|\|paypal.com/xoplatform/logger/api/logger | -- | `www.paypal.com` | 0,1 | xhr | `https://www.paypal.com/xoplatform/logger/api/logger` |
| +902 | /counter.cgi? | -- | `www.paypal.com` | 0,1 | image | `https://b.stats.paypal.com/v2/counter.cgi?p=uid_6fc19b45d2_mtc6ndy6mza&s=SMART_PAYMENT_BUTTONS` |
| +900 | /tagmanager/pptm. | -- | `www.audionebula.ca` | 0,3 | script | `https://www.paypal.com/tagmanager/pptm.js?id=www.audionebula.ca&t=xo&v=5.0.271&source=payments_sdk&client_id=AYmHaQeNTBng7k-uuEgJpGJ47rul9GEqSsgVHhd69xAZ7ZtN1wejr5wBWOMbRbhQXPNVlmRy13KF17s3&vault=false` |
| +738 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://ad.doubleclick.net/ddm/trackimp/N994946.159072SPOTIFY/B26815426.320784508;dc_trk_aid=513265963;dc_trk_cid=161627398;ord=282916496;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=;gdpr_consent=;ltd=?` |
| +738 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BeMQ8BHeeYbbaMbO0nsEPw6ie6A-9s-GNRgAAABABILyu-R44AViYiOa8gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAK9BKkCXC1H2_TRsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhDipIHdFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=RfXdIygxlCw&label=part2viewed&ad_mt=[AD_MT]` |
| +738 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjst52MYyJPaub0uQ5MtqCWbrfE0BB5Bw9vFQqFGl0Jmyt__6sDIujfkPVhRQPQhTCHZXL7rjice7GUdU0o84NtsZCZmN0mWULEiFPOo9_0XzpyX4NrL5DhJBNMcDdQOf82rEQ3ffuzSL3Kq0YSkpeVn0h0wfUnaHVj3PtKmOW6OXCEcSUVFpyLVeFJrtRLpvoDp2UMbdHa3F08R-CVzF9sz-g-GjfNQ97Bujdw5jzFYABW0alXDMcqe4HetkgoHsbosJt7j-MbHQYJxdq00CaxXRB64U77FpVrpXdbSTBaAMcNYU9GMQQyoMWPAQ95XO0sL2GqwlNHBLiUZLdw&sai=AMfl-YRbtYCb8c-l-YStjUbn-97GSf6nzd5r8CaoH8BuKzxhRaR-k-sIScMAnN9Q915hB0asZ7hE1h_0F8vAtr2aKrKZ3wYbD3JAjErw0LokOhXJmYuMmQk&sig=Cg0ArKJSzFULvIgZFHDpEAE&uach_m=[UACH]&adurl=` |
| +738 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BeMQ8BHeeYbbaMbO0nsEPw6ie6A-9s-GNRgAAABABILyu-R44AViYiOa8gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAK9BKkCXC1H2_TRsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhDipIHdFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=RfXdIygxlCw&label=vast_creativeview&ad_mt=[AD_MT]` |
| +738 | noopmp3-0.1s | << | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/bc3b15187f5551575b25097190b7e0d719a523dd?1637862270_v7zQY_1G7G-ksMQS0qdW4TgUMmox5ZLKuO4pz-d35gs=` |
| +738 | \|\|scdn.co/audio/$media,redirect-rule=noopmp3-0.1s,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/bc3b15187f5551575b25097190b7e0d719a523dd?1637862270_v7zQY_1G7G-ksMQS0qdW4TgUMmox5ZLKuO4pz-d35gs=` |
| +738 | \|\|scdn.co/audio/$media,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/bc3b15187f5551575b25097190b7e0d719a523dd?1637862270_v7zQY_1G7G-ksMQS0qdW4TgUMmox5ZLKuO4pz-d35gs=` |
| +737 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BpxSWBHeeYYnqMLO0nsEPw6ie6A_LxfONRgAAABABILyu-R44AVjDhuy6gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAKYEakCXC1H2_TRsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhCy08DSFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=5eRwXHDZu7w&label=part2viewed&ad_mt=[AD_MT]` |
| +737 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://ad.doubleclick.net/ddm/trackimp/N301002.4086549C3SPOTIFY/B26636137.317021512;dc_trk_aid=509625867;dc_trk_cid=159451361;ord=1117538484;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=;gdpr_consent=;ltd=?` |
| +737 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjstjAwEph8rnLXctXeev-xXqt0jXtU0YbzhveztQRZqz6rv3uKNOEPkLAvNTI4gvvvYEhXZgthWtkgn6MuVoSTkZFDObfzonqogMNqKfYaptGOo-iauU4DeQkooHEeXzZ8kSiB87qfgXMdlB59DH6tbgClXvm_fXPWZta9GnmWRJ4s7MV7_9_nfrPaIeKerkAZWSmjei6nJdKJsJQ8ue-6uCVpB8v3zsbRdWx_-Rq80kMi8aPKzDc5fAHUhScmjHFvNMfUoasmSKYBGHrNFFIb-9pVFfqZpWgkQ6gDKcpHY5o-aAQA3999U48bmhcrm4VK1Aq-TK6w5WpIWVFg&sai=AMfl-YRj7BeVq0SSnEuaOL452G2NWCnQO6Q3hJ4Yfl4W2JQni7Wn0gY7MOLx0y7sh9K7TJfU0OMoE46oSluWbVSqSTFzbT7jU8JUGwNDVfUZbLPi4_BTx5A&sig=Cg0ArKJSzKr4tbgOwPzxEAE&uach_m=[UACH]&adurl=` |
| +737 | \|\|doubleclick.net^ | -- | open.spotify.com | 3 | xhr | `https://pubads.g.doubleclick.net/pagead/interaction/?ai=BpxSWBHeeYYnqMLO0nsEPw6ie6A_LxfONRgAAABABILyu-R44AVjDhuy6gwRghJXshdwdsgEPd3d3LnNwb3RpZnkuY29tugEJZ2ZwX2ltYWdlyAEF2gEYaHR0cHM6Ly93d3cuc3BvdGlmeS5jb20vmAKYEakCXC1H2_TRsj7AAgLgAgDqAhgvNjQ2NTA1Mi93ZWIvZGVza3RvcF93ZWL4AvzRHpADhAeYA9AFqAMB0ASQTuAEAdIFBhCy08DSFZAGAaAGI9gGAagH89EbqAeW2BuoB6qbsQKoB9-fsQLYBwHgBwvSCAcIgGEQARgf2AgCgAoFmAsB0BUBgBcB&sigh=5eRwXHDZu7w&label=vast_creativeview&ad_mt=[AD_MT]` |
| +737 | noopmp3-0.1s | << | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637862270_wRXp3zo2QfrXxHkjYx-I_Y_vOTpgJF9DVJQWMzxVGsM=` |
| +737 | \|\|scdn.co/audio/$media,redirect-rule=noopmp3-0.1s,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637862270_wRXp3zo2QfrXxHkjYx-I_Y_vOTpgJF9DVJQWMzxVGsM=` |
| +737 | \|\|scdn.co/audio/$media,domain=open.spotify.com | -- | open.spotify.com | 3 | media | `https://audio-fa.scdn.co/audio/1e6e68159b865bb702f9dd31d36db52bf51f1267?1637862270_wRXp3zo2QfrXxHkjYx-I_Y_vOTpgJF9DVJQWMzxVGsM=` |
| +0 | \|\|sentry.io^$3p | -- | open.spotify.com | 3 | beacon | `https://sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7` |
</details>

**Comment by uBlock-user** [comment]
Site issue, known to happen sometimes and sometimes doesn't.

**Comment by okiehsch** [comment]
You can allow the ad to run on your end by adding
`@@||scdn.co/audio/$media,domain=open.spotify.com`

**Comment by 9Skrip** [comment]
I know but the whole point of uBlock is lost than

**Comment by Sammeeey** [comment]
> After an Ad is blocked doesn't continue playing. Remains silent with an ad in the left corner. Playing can be only continued after page reload. Happens Randomly it can be 10 songs without the problem or 3. All filters updated

Well described👌
I have the same annoying issue - some ads (not all) have been skipped by uBlockOrigin automatically.
For some ads only the audio got blocked, but not the image.
Earlier these ones could be skipped by pressing the space key.
Skipping with the space key is not possible anymore (as described by @9Skrip) for the image-not-blocked ads, so that we are forced to reload the page (without knowing at which song Spotify got interrupted☹).

Furtunately I found a workaround - similar to pressing the space key earlier (see previous paragrah).

## Workaround
![skip_image-not-blocked_ad](https://user-images.githubusercontent.com/49591562/164645857-2fd203c7-83ba-4fbf-8a4d-9d29ae1dc3be.png)

https://user-images.githubusercontent.com/49591562/164639079-454ca741-0140-403e-a7a7-25bfe62e0a2d.mp4
