### ISSUE TITLE
fmovies.to: detection

### ISSUE THREAD

**Issue by AngelosNaoumis** [uBlockOrigin/uAssets#10587]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I did not open more than three (3) issues today
- [X] I verified that the issue has not already been reported
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fmovies.to/home`

### Category

detection

### Describe the issue

Simple it detects i have ad blocker

### Configuration

```yaml
uBlock Origin: 1.38.7rc2
Chromium: 97
filterset (summary): 
  network: 155380
  cosmetic: 161118
  scriptlet: 50528
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 26929-23, 20h.37m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 4m
    GRC-0: 1002-0, 6m
    adguard-annoyance: 47653-204, 2d.2h.56m
    adguard-generic: 61615-1536, 2d.2h.52m
    adguard-spyware: 25107-705, 2d.2h.54m
    adguard-spyware-url: 388-12, 2d.2h.58m
    block-lan: 43-0, 29d.13h.40m
    dpollock-0: 16965-224, 4d.7h.32m
    fanboy-annoyance: 58868-2841, 5d.5m
    fanboy-cookiemonster: 20348-20348, 5d.3m
    mvps-0: 8730-1814, 4d.7h.34m
    ublock-annoyances: 4298-316, 2d.3h
  default: 
    easylist: 60965-1027, 2d.2h.50m
    easyprivacy: 26279-10836, 2d.2h.48m
    plowe-0: 3686-1452, 7d.8h.51m
    ublock-abuse: 67-1, 2d.2h.46m
    ublock-badware: 3420-182, 2d.2h.44m
    ublock-filters: 29744-6066, 2d.2h.42m
    ublock-privacy: 186-31, 2d.2h.40m
    ublock-unbreak: 1690-107, 2d.2h.38m
    urlhaus-1: 9687-0, 20h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 28 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2204
  launchFromSelfie: true

```

**Comment by uBlock-user** [comment]
> I verified that the issue has not already been reported

[No you didn't.](https://github.com/uBlockOrigin/uAssets/issues/10547)
