### ISSUE TITLE
adwhi.tk [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1058]
URL(s) where the issue occurs

http://adwhi.tk/vqnn

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
`function startcount() in fuckadblock.js`

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters @mapx-
