### ISSUE TITLE
graphicsmob.com: nuisance

### ISSUE THREAD

**Issue by chirag127** [uBlockOrigin/uAssets#10581]
### URL address of the web page

`https://graphicsmob.com/is-graphic-design-a-dying-career-the-rise-of-diy/`

### Category

nuisance

### Screenshot(s)

![image](https://user-images.githubusercontent.com/76880977/143281839-7b23e409-f81d-4bdd-8691-1807eb760190.png)

### Configuration

```yaml
uBlock Origin: 1.38.7rc2
Chromium: 96
filterset (summary): 
  network: 79669
  cosmetic: 115114
  scriptlet: 32705
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/118_optimized.txt: 12935-0, 38m
    https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt: 25168-75, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/AD.txt: 43-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/AL.txt: 12-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/APWL.txt: 23-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/C.txt: 149-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/D.txt: 48-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/E.txt: 92-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/F.txt: 7-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/GD.txt: 4-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/H.txt: 112-1, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/N.txt: 551-2, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/NF.txt: 20-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/O.txt: 23-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/P.txt: 169-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/S.txt: 1-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/SR.txt: 11-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/T.txt: 68-2, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/W.txt: 7-0, 38m
    https://raw.githubusercontent.com/chirag127/adblock/master/YT.txt: 38-0, 38m
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1874-7, 38m
    https://raw.githubusercontent.com/lutoma/nocomments/master/abp.txt: 149-2, 38m
    https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-anticomments.txt: 53-5, 38m
    adguard-annoyance: 47736-1913, 39m
    adguard-generic: 61601-767, 40m
    adguard-social: 14708-1743, 39m
    adguard-spyware: 25148-6471, 39m
    adguard-spyware-url: 390-32, 39m
    ublock-annoyances: 4306-179, 39m
  default: 
    easyprivacy: 26311-17795, 33m
    plowe-0: 3699-512, 33m
    ublock-abuse: 70-0, 41m
    ublock-badware: 3436-130, 40m
    ublock-filters: 29590-3075, 40m
    ublock-privacy: 187-31, 40m
    ublock-unbreak: 1690-94, 40m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
  triggered: 
    no-csp-reports: * true
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1215
  launchFromSelfie: false

```

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets#readme
"
If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

- ad-reinsertion
- anti-adblock
- contextmenu blockage
- copy/cut/paste blockage
- popups/popunders
- site breakage
- video ads
will always be fixed in uAssets even if they don't require extended syntax.
"

This issue and most of the others you opened can be fixed in EasyList or an annoyance list.

**Comment by chirag127** [comment]
Well it's not a advertisement

**Comment by uBlock-user** [comment]
> Well it's not a advertisement

Same rule for annoyances too. You have literally spammed uAssets now.

**Comment by okiehsch** [comment]
The annoyance list of uAssets has the same readme. 😉

**Comment by chirag127** [comment]
> The annoyance list of uAssets has the same readme. 😉

Ah seems like I didn't even seen that in which repository I'm making the issues the report issue button in uBlock origin pre build made it super easy to make issues.

**Comment by gorhill** [comment]
@chirag127 Please for the time being hold onto submitting issues. I didn't expect that the report features would be used in such a manner and this is burdening the volunteers. Maybe it was a bad idea after all to integrate such feature, it seems maybe we just can't have nice things.

**Comment by gorhill** [comment]
Ok here is one this: issues for which default lists are removed will be closed as invlaid immediately without further discussion/comment.

**Comment by felix-22** [comment]
It's a good feature, not the feature is a problem here, but a single person (`chirag127`) bombarding multiple repositories:
- a half ~400 out of ~800 currently open issues on AdGuard tracker are by him: 
https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+author%3Achirag127
not mentioning the other ~2400 closed...Wow

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Only one (minor) addition from orginal site.   https://github.com/easylist/easylist/commit/348f8d0e50630e96010fafde481d2d17378ee0f3
