### ISSUE TITLE
Wheel of Fortune from freebitco.in is blocked

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#10585]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bq11v59f.r.us-east-1.awstrack.me/L0/https:%2F%2Ffreebitco.in%2Fstatic%2Fhtml%2Fwof_new%2Findex.html%3Fu=46380041%26t=c8eQ4r8pdZmpLRFyWV94ZNhr0sDkDTYT%26utm_medium=email/1/0100017d534ac09b-7fae2dde-4a27-44ae-ab95-44e652c3e14c-000000/7LAizSUWHZi6IzVaL0rDm3EzjVM=245`

### Describe the issue

Gets block by Pete Lowe List (`||awstrack.me^`) but should redirect to `https://freebitco.in/static/html/wof_new/index.html?u=46380041&t=c8eQ4r8pdZmpLRFyWV94ZNhr0sDkDTYT`

### Configuration

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 67268
  cosmetic: 39978
  scriptlet: 16088
  html: 596
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    NLD-0: null
  added: 
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt: 1722-0, 2d.3h.1m
  default: 
    ublock-filters: 30297-65, 2d.3h.2m
    ublock-privacy: 182-0, 2d.3h.2m
    ublock-unbreak: 1701-12, 2d.3h.1m
    easylist: 60950-489, 2d.3h.1m
    easyprivacy: 26278-474, 2d.3h.1m
    plowe-0: 3698-1, 2d.3h.1m
filterset (user): [array of 279 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 155 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  dynamicFilteringEnabled: true
  largeMediaSize: 100
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}}
  autoUpdateAssetFetchPeriod: 1
  autoUpdateDelayAfterLaunch: 3
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#000092 00001/#2A2A2A
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
  uiPopupConfig: scrollbar-width: thin !important;
supportStats: 
  launchToReadiness: 2431
  launchFromSelfie: true
```

**Comment by uBlock-user** [comment]
@gorhill Should we bother ?

**Comment by BPower0036** [comment]
Good to know the following rule works for me `@@||awstrack.me/*/https:%2F%2Ffreebitco.in%2Fstatic%2Fhtml%2Fwof_new%2Findex.html*`

**Comment by BPower0036** [comment]
@uBlock-user Thanks for rolling the wheel🤔

**Comment by gorhill** [comment]
> Should we bother ?

No. There is no details of where that reported link come from.

**Comment by uBlock-user** [comment]
@BPower0036 policy change at https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951814995

**Comment by BPower0036** [comment]
I didn't know that policy chance.
But to gave answer to @gorhill the link came from a mail they send regularly
![afbeelding](https://user-images.githubusercontent.com/80090789/143305056-75aee797-60be-4abb-9443-4079ccc78ed2.png)

**Comment by gorhill** [comment]
These emails typically come with tracker links, uBO's purpose is not to allow those trackers to operate silently by bypassing user consent, it's to serve user interests first, and uBO let you decide what to do on the strict-blocked page.

**Comment by PIZZA90** [comment]
I had to reset my password of `ubisoft.com` and all links in the emails of `ubisoft` for rest the password is using `awstrack.me`
blocked the redirections

**Comment by mapx-** [comment]
add as custom filter

`||awstrack.me^$badfilter`
