### ISSUE TITLE
https://givingassistant.org/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#10583]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://givingassistant.org/`

### Describe the issue

Images don't load. Cannot type in the search box.

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 96

### Settings

N/A

### Notes

```
@@||givingassistant.org/Advertisers/*
@@||cdn.segment.com^$domain=givingassistant.org
```

**Comment by mapx-** [comment]
```
@@||givingassistant.org/Advertisers/$image,xhr,1p
@@||cdn.segment.com^$script,xhr,domain=givingassistant.org
```

**Comment by mapx-** [comment]
@ryanbr
