### ISSUE TITLE
conteudo.mepoupenaweb.com.br RD Station Scripts incorrect blocking

### ISSUE THREAD

**Issue by tiagotor** [uBlockOrigin/uAssets#10582]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://conteudo.mepoupenaweb.com.br/autonomos
https://conteudo.mepoupenaweb.com.br/cadastro-newsletter-20211025203110
```

Files Blocked:
```
https://cidades.rdstation.com.br/api/cidades/
https://d335luupugsy2.cloudfront.net/js/traffic-source-cookie/stable/traffic-source-cookie.min.js
https://d335luupugsy2.cloudfront.net/js/lead-tracking/stable/lead-tracking.min.js
https://d335luupugsy2.cloudfront.net/js/lead-tracking/stable/plugins/jquery.cookie.v1.4.1.min.js
https://d335luupugsy2.cloudfront.net/js/lead-tracking/stable/plugins/math.uuid.v1.4.min.js
https://d335luupugsy2.cloudfront.net/js/sauron-analytics/stable/sp.js
https://www.rdstation.com.br/api/1.2/conversions.json
https://popups.rdstation.com.br/popup/show.json
https://forms.rdstation.com.br
```

### Describe the issue

We are a Marketing and Sales Platform (like Hubspot) where our clients hire our service to make Landing Pages, Popups and Forms.

These Assets work from Scripts that run on the page, such as API Submissions (https://www.rdstation.com.br/api/1.2/conversions.json) or even APIS queries (https://cidades.rdstation.com.br/api/cidades/) that are being blocked, and generating problems for our customers.

To reproduce this problem, simply register in the form present on the page and check that when you submit, an error will be displayed. You can also check in the console that the links are blocked by uBlock.

### Screenshot(s)

![ublock2](https://user-images.githubusercontent.com/48798653/143290101-1de1f250-bc09-47ff-bcfa-28657e986b2d.PNG)
![ublock1](https://user-images.githubusercontent.com/48798653/143290111-627fe803-6551-48c7-aae2-5538e4ce50ca.PNG)

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 96.0.4664.45

### Settings

no-large-media: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop

**Comment by okiehsch** [comment]
Does
`@@||rdstation.com.br^$xhr,domain=conteudo.mepoupenaweb.com.br`
fix the breakage for you?

**Comment by tiagotor** [comment]
Hey! I think if you can whitelist` rdstation.com.br` and our Cloudfront Bucket `https://d335luupugsy2.cloudfront.net` it fix for all our customers.

**Comment by uBlock-user** [comment]
> you can whitelist

There's no whitelisting policy, we only add exceptions for site breakage.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by tiagotor** [comment]
No problem. You cad add an exceptions for this 2 URLS? `rdstation.com.br` and `https://d335luupugsy2.cloudfront.net`?

**Comment by iam-py-test** [comment]
> No problem. You cad add an exceptions for this 2 URLS? `rdstation.com.br` and `https://d335luupugsy2.cloudfront.net`?
> Because Forms and conversions / API requests are being blocked because of this, as I said (there are 35,000 customers worldwide).

A fix will probably be added to Easylist.

**Comment by mapx-** [comment]
> To reproduce this problem, simply register in the form present on the page and check that when you submit, an error will be displayed

just provide a test account

**Comment by ryanbr** [comment]
Comes from https://github.com/easylist/easylist/issues/1762   This isn't a recent commit, 2018. And suddenly its an issue?

**Comment by tiagotor** [comment]
> just provide a test account

Just to check, you need a RD Station Test Account do reproduce this scenario?

**Comment by tiagotor** [comment]
> Comes from [easylist/easylist#1762](https://github.com/easylist/easylist/issues/1762) This isn't a recent commit, 2018. And suddenly its an issue?

Yes. Because there is some scripts that are in our Cloudfront that got blocked. In addition, as mentioned, there are still links/apis referring to rdstation.com.br that are being blocked.

**Comment by mapx-** [comment]
@tiagotor  I don't know what I need:

- my test email `axis.trivia@gmail.com`
- **provide all the steps to reproduce your issues** (links, what to check, what to click etc)

**Comment by tiagotor** [comment]
> https://conteudo.mepoupenaweb.com.br/cadastro-newsletter-20211025203110

Step By Step:

1. Access https://conteudo.mepoupenaweb.com.br/autonomos
2. Press F12 (Browser Console)
3. You can see all of our RD Station Scripts (Cloudfront https://d335luupugsy2.cloudfront.net/) Got blocked by uBlock
4. Continue and Fill the Form
5. When you try to fill the field "Cidade", you will got an Error, because the endpoint https://cidades.rdstation.com.br/api/cidades/ got blocked by uBlock (you can see that in F12 Browser Console)


Other Scenario:

- Access https://conteudo.mepoupenaweb.com.br/cadastro-newsletter-20211025203110
- Fill The entire Form
- Open your console Broswer (F12) and Click on "Quero Indicar"
- You can see an error into the screen. Press OK and you can see the Page Request to https://www.rdstation.com.br/api/1.2/conversions.json got blocked by uBlock.

**Comment by iam-py-test** [comment]
> @mapx- Step By Step:
> 
>     * Access https://conteudo.mepoupenaweb.com.br/autonomos
> 
>     * Press F12 (Browser Console)
> 
>     * You can see all of our RD Station Scripts (Cloudfront https://d335luupugsy2.cloudfront.net/) Got blocked by uBlock
> 
>     * Continue and Fill the Form
> 
>     * When you try to fill the field "Cidade", you will got an Error, because the endpoint https://cidades.rdstation.com.br/api/cidades/ got blocked by uBlock (you can see that in F12 Browser Console)
> 
> 
> Other Scenario:
> 
>     * Access https://conteudo.mepoupenaweb.com.br/cadastro-newsletter-20211025203110
> 
>     * Fill The entire Form
> 
>     * Open your console Broswer (F12) and Click on "Quero Indicar"
> 
>     * You can see an error into the screen. Press OK and you can see the Page Request to https://www.rdstation.com.br/api/1.2/conversions.json got blocked by uBlock.

The following rules fix the issue for me:
```
@@||cidades.rdstation.com.br/api/cidades/?term=*&state_acronym=*$xhr,domain=conteudo.mepoupenaweb.com.br
@@||rdstation.com.br/api/1.2/conversions.json$xhr,domain=conteudo.mepoupenaweb.com.br
```

**Comment by gorhill** [comment]
Given this affects only one site for now, probably best to just use:

    @@||rdstation.com.br/api/$xhr,domain=conteudo.mepoupenaweb.com.br

**Comment by tiagotor** [comment]
@iam-py-test this problem occurs with all our 35.000 Customers. There a way to fix that more generalized, like, without the customer domain?  (just rdstation.com.br, i.e.).

Other link examples that have the same problem:

https://conteudo.afinz.com.br/fatura-digital
https://lp.institutoembelleze.com/treinamento-comercial-premio-transformacao
http://q48emagrecimento.rds.land/teste-form-guru

@gorhill it affects all our customers website.

**Comment by iam-py-test** [comment]
> @iam-py-test this problem occurs with all our 35.000 Customers. There a way to fix that more generalized, like, without the customer domain? (just rdstation.com.br, i.e.).
> 
> Other link examples that have the same problem:
> 
> https://conteudo.afinz.com.br/fatura-digital https://lp.institutoembelleze.com/treinamento-comercial-premio-transformacao http://q48emagrecimento.rds.land/teste-form-guru
> 
> @gorhill it affects all our customers website.

I was just sharing the results from my investigation, the rules probably will change
Do/can you only use a certain directory on that server, so a tracking server doesn't have to be globally unblocked?

**Comment by gorhill** [comment]
You state yourself you are a marketing platform and you are here to ask that a server from your marketing platform be broadly whitelisted -- don't you see that this really does not look good when understanding that uBO's purpose is to serve user interests, not the marketing platform used by a site?

Ultimately, why are the site of your customers not failing graciously when they can't access your marketing platform's servers? As @ryanbr pointed out, why is this suddenly an issue now after the block filter has been added more than three years ago?

**Comment by tiagotor** [comment]
> > @iam-py-test this problem occurs with all our 35.000 Customers. There a way to fix that more generalized, like, without the customer domain? (just rdstation.com.br, i.e.).
> > Other link examples that have the same problem:
> > https://conteudo.afinz.com.br/fatura-digital https://lp.institutoembelleze.com/treinamento-comercial-premio-transformacao http://q48emagrecimento.rds.land/teste-form-guru
> > @gorhill it affects all our customers website.
> 
> I was just sharing the results from my investigation, the rules probably will change Do/can you only use a certain directory on that server, so a tracking server doesn't have to be globally unblocked?

Got it.

Our endpoints:

```
https://cidades.rdstation.com.br
https://forms.rdstation.com.br
https://www.rdstation.com.br/api/
https://d335luupugsy2.cloudfront.net/js/lead-tracking
https://d335luupugsy2.cloudfront.net/js/sauron-analytics/
https://event-api.rdstation.com.br/v2/conversions.json
https://popups.rdstation.com.br/popup/show.json
```

@gorhill i really understand your point.

We have records of this problem with our customers since 2018, and recently we have been receiving a larger number of complaints from our customers, so we came here for information.

There was a case a while ago (4 years ago) reported by Hubspot - https://status.hubspot.com/incidents/67mrmp6h4414 - a tool that has the same purpose as ours, and from what can be seen in the records of the mentioned page, they contacted you, and the exception was made.

I am not asking you to release all endpoints, if that is the case, because as I said, I agree with the points made, but there are 3 endpoints that if not released, make the page/requests from our clients' Leads (people who register on the page with real data, and register because they want to - they are not forced to) break:

```
https://cidades.rdstation.com.br/
https://www.rdstation.com.br/api/
https://event-api.rdstation.com.br/v2/
```

With this, we guarantee that the pages will work correctly, and we also guarantee the privacy of the user who uses uBlock, in not being trackeado, if he doesn't want to.

**Comment by iam-py-test** [comment]
> https://d335luupugsy2.cloudfront.net/js/sauron-analytics/
> https://d335luupugsy2.cloudfront.net/js/lead-tracking

These look like tracking servers... If their not being used for tracking, I'd recommend you rename them

**Comment by tiagotor** [comment]
> > https://d335luupugsy2.cloudfront.net/js/sauron-analytics/
> > https://d335luupugsy2.cloudfront.net/js/lead-tracking
> 
> These look like tracking servers... If their not being used for tracking, I'd recommend you rename them

It is. And that's why i've said that if you guys dont want to make a exception for this specific links, that is OK. But, for the other 3 ones that i have discribed above, it would be necessary.

**Comment by mapx-** [comment]
Where do you need `https://event-api.rdstation.com.br/v2/`   ?

from my tests I need only

`@@||rdstation.com.br^*api/$xhr`

**Comment by ryanbr** [comment]
Did consider just blocking "d335luupugsy2.cloudfront.net" but held off to be specific. If we see any tracking, or any reports of tracking further measures will be taken.
