### ISSUE TITLE
fmovies.to: detection

### ISSUE THREAD

**Issue by keldan19** [uBlockOrigin/uAssets#10588]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I did not open more than three (3) issues today
- [X] I verified that the issue has not already been reported
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fmovies.to/`

### Category

detection

### Describe the issue

site says "Adblock breaks it"

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 79027
  cosmetic: 39305
  scriptlet: 16187
  html: 572
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30306-95, 2d.20h.35m
    ublock-badware: 3424-1, 2d.20h.33m
    ublock-privacy: 183-0, 1d.6h.28m
    ublock-abuse: 67-0, 2d.16h.22m
    ublock-unbreak: 1701-0, 2d.20h.31m
    easylist: 60919-453, 2d.20h.29m
    easyprivacy: 26270-483, 2d.20h.27m
    urlhaus-1: 9540-0, 17h.5m
    plowe-0: 3689-3, 4d.3h.46m
filterset (user): [array of 140 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 434
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
> [x]  I verified that the issue has not already been reported

The issue has already been reported and fixed, your _"uBlock filters"_ is nearly 3-day old.

The issue template warns:

> To avoid burdening volunteers with invalid, duplicate, or just too many issues, disrespecting these steps may result in your account being blocked on this repo.

**Comment by krystian3w** [comment]
Or this is broken by poor custom list / filter.

```yaml
ublock-filters: 30306-95, 2d.20h.35m
```

All CDN-s can not serve outdated file.
