### ISSUE TITLE
driveup.in: detection

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#10597]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://driveup.in/rcd/?id=eW1oWFNvUXlYV1pPTHA5U2IxcjhKUT09&code=200&gd=MENmcTlFOE1QeXBpNmloRFFhYm16dWRzeXdTbmdiRlpyZ3YxdHZCT1dUWHhnd1VxN0NWZ1ljOElyYk9qajVXOA==&nm=QW5uYWF0dGhlLjIwMjEuSGluZGktVGFtaWwuNDgwcC5XRUItREwueDI2NC1Cb2xseWZsaWNrLnRlY2gubWt2`

`https://driveup.in/files/1520599287`

ref link `https://bollyflick.tech/annaatthe-2021-web-dl-dual-audio-hindi-dd5-1-tamil-1080p-720p-480p-x264-hd-full-movie/`

### Category

detection

### Describe the issue

antiadblock

### Screenshot(s)

https://user-images.githubusercontent.com/20338483/143430575-046f72f2-c6fa-4a22-89a0-9a75eddde6c3.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 80633
  cosmetic: 44514
  scriptlet: 16162
  html: 613
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30244-115, 16h.22m
    ublock-badware: 3440-9, 16h.22m
    ublock-privacy: 183-0, 16h.22m
    ublock-abuse: 70-0, 16h.22m
    ublock-unbreak: 1706-0, 16h.22m
    adguard-mobile: 6989-156, 16h.22m
    easylist: 61064-699, 16h.22m
    easyprivacy: 26311-482, 16h.22m
    urlhaus-1: 9538-0, 16h.22m
    plowe-0: 3699-3, 16h.22m
filterset (user): [array of 224 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  updateAssetBypassBrowserCache: true
supportStats: 
  launchToReadiness: 1037
  launchFromSelfie: true
```
</details>

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13121#issue-1228789512

**Comment by stephenhawk8054** [comment]
@ghajini Does this one work for you in Opera? I can open the link in Firefox but for some reason it tells me it expires with Opera

`driveup.in##+js(acis, Object, break;case $.)`

**Comment by ghajini** [comment]
Link given in description=`
https://driveup.in/file/831740603`
they protect actual link thatswhy expires error

so now that filter i tried b4, i do not get to work `direct download` button

**Comment by stephenhawk8054** [comment]
> Link in description=
> 
> `https://driveup.in/file/831740603` they protect actual link thatswhy expires error
> 
> so now that filter i tried b4, i do not get to work `direct download` button

How about this?

`driveup.in##+js(acis, navigator, break;case $.)`

I can download normally with this one.

**Comment by ghajini** [comment]
yes that work
