### ISSUE TITLE
“ISL: Icelandic ABP List” looks like a no longer maintained filters list.

### ISSUE THREAD

**Issue by Piter432** [uBlockOrigin/uAssets#1060]
### URL(s) where the issue occurs

uBO Dashboard > 3rd party filters > Regions & languages > ISL: Icelandic ABP List

### Describe the issue

I'm trying to update this filters list, but uBO show there was network error which prevents to update this filters list.

### Versions

- Browser/version: Google chrome 63 32-bit (63.0.3239.108)
- uBlock Origin version: 1.14.22

**Comment by mapx-** [comment]
No issue here, however the list is outdated:
`Last updated 19 Desember/December 2016`

**Comment by mapx-** [comment]
Can you see this page ?
http://adblock.gardar.net/is.abp.txt

**Comment by Piter432** [comment]
Hmm, strange. It updated fine now. Maybe server overloaded for a while or something?
