### ISSUE TITLE
freecourse.tech: detection

### ISSUE THREAD

**Issue by chirag127** [uBlockOrigin/uAssets#10604]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists ([here is how to do this](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://freecourse.tech/`

### Category

detection

### Describe the issue

I did a completely fresh ubo installation  and disabled all other extensions too.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/76880977/143484107-4cfc8999-c3a4-4755-bb87-5a5226a31d48.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.38.7rc4
Chromium: 96
filterset (summary): 
  network: 77502
  cosmetic: 39179
  scriptlet: 16179
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 60746-451, never
    easyprivacy: 25518-214, never
    plowe-0: 3689-3, never
    ublock-abuse: 67-0, never
    ublock-badware: 3395-1, never
    ublock-filters: 29675-108, never
    ublock-privacy: 186-0, never
    ublock-unbreak: 1690-0, never
    urlhaus-1: 8813-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1488
  launchFromSelfie: false
```
</details>

**Comment by gorhill** [comment]
This works for me:

    *$object,redirect-rule=empty,domain=freecourse.tech
    @@||freecourse.tech^$ghide

**Comment by gorhill** [comment]
I doubt we should care about this site, it looks like a [content farm](https://en.wikipedia.org/wiki/Content_farm), we are just going to unduly bloat the lists.

**Comment by gorhill** [comment]
Closing as `wontfix`. If more report concerning this site surface in the future, suggesting actual people visit that site, it can be reconsidered.

**Comment by uBlock-user** [comment]
Looks like a wordpress blog as per `https://freecourse.tech/2021/11/25/modern-javascript-from-the-beginning/`

**Comment by okiehsch** [comment]
We have fixed many similar sites, just search for `freecourse` in `uBO-filters` and you get 34 hits....

**Comment by okiehsch** [comment]
I am not saying we should fix it, btw, it's just hard to differentiate between sites we should fix and sites we shouldn't imo.

**Comment by okiehsch** [comment]
The site uses a generic anti adblock script, we use
`freecourse.tech##+js(acis, decodeURIComponent, ai_)`
for that script.

**Comment by gorhill** [comment]
The way I see it is that people should report issues on sites they genuinely visit, we should not have to deal with issues found in some automated, programmatic ways because this makes it doubtful that those sites are really visited by actual human being.

The reporting history of @chirag127 is that he was never a contributor before yesterday, and suddenly 19 issues were opened in one day (before we had to put a stop on this), all the while he has opened an average of over 13/day on AdGuard repo for 7 seven months straight. Given this sort of history, I can't help but be suspicious that the issues he reports are from genuinely visiting the sites.

**Comment by chirag127** [comment]
> was never a contributor before yesterday

Well I have contributed before even made a pull request for a redirected url.

**Comment by JobcenterTycoon** [comment]
Different tools say the site has ~ 700 visitors per Month

**Comment by chirag127** [comment]
> Different tools say the site has ~ 700 visitors per Month

I also checked it . Well I'm fine if get the user filter.

Thank you. I'm closing the issue.
