### ISSUE TITLE
tumi.com: breakage

### ISSUE THREAD

**Issue by kerabite** [uBlockOrigin/uAssets#10606]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists ([here is how to do this](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.tumi.com/c/accessories/wallets-cardcases/`

### Category

breakage

### Describe the issue

The store items do not load with uBO, but do load without uBO

### Screenshot(s)

with uBO:
https://user-images.githubusercontent.com/10791585/143497663-6f8345bd-087f-4bea-9360-375202c45dce.png

without uBO:
https://user-images.githubusercontent.com/10791585/143497684-e28175ef-27c0-4aeb-8848-d0a136e3d484.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 107983
  cosmetic: 160463
  scriptlet: 31378
  html: 607
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 294-0, 1h.5m
    adguard-generic: 61642-4442, 1h.11m
    adguard-annoyance: 47817-3351, 1h.13m
    fanboy-annoyance: 58973-294, 1h.28m
    ublock-annoyances: 4319-5, 1h.15m
  default: 
    ublock-filters: 30165-30, 1h.9m
    ublock-badware: 3440-1, 1h.7m
    ublock-privacy: 184-0, 1h.26m
    ublock-abuse: 70-0, 1h.24m
    ublock-unbreak: 1705-0, 1h.22m
    easylist: 61109-548, 1h.20m
    easyprivacy: 26327-472, 1h.18m
    urlhaus-1: 10020-0, 1h.3m
    plowe-0: 3685-3, 10d.13h.56m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1430
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
`@@||api.rfksrv.com/search-rec/$xhr,domain=tumi.com`

EP issue @ryanbr

**Comment by gorhill** [comment]
Need:

    @@||api.rfksrv.com^$xhr,domain=tumi.com
