### ISSUE TITLE
Anti-adblock - https://karanpc.com

### ISSUE THREAD

**Issue by Sopor** [uBlockOrigin/uAssets#10609]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://karanpc.com/windows/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/5789283/143559651-f3bddeea-f525-43e8-a186-d724ae8076b0.png)

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Settings

uBO

**Comment by Sopor** [comment]
It was working for some hours but now i get the same anti-adblock again :(

**Comment by Sopor** [comment]
That was funny... Even the https://blockadblock.com has an anti-adblocker 😄

**Comment by uBlock-user** [comment]
> It was working for some hours but now i get the same anti-adblock again :(

Filter works on  default configuration + no other extensions enabled, so test on that.

**Comment by Sopor** [comment]
@uBlock-user I seems that @okiehsch commit fixed it 👍 

Thanks!

**Comment by uBlock-user** [comment]
> I seems that @okiehsch commit fixed it 

that commit only hides ad placeholders, not anti-adblock.

**Comment by Sopor** [comment]
It is working now. I only did an update on the block lists.

**Comment by Sopor** [comment]
It seems that this site has got a new anti-adblock 😔

![image](https://user-images.githubusercontent.com/5789283/197395996-e2e0b588-9e06-49da-b0f9-90662505bb1f.png)
