### ISSUE TITLE
9anime.id: detection

### ISSUE THREAD

**Issue by Fariq99** [uBlockOrigin/uAssets#10603]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://9anime.id/home`

### Category

detection

### Describe the issue

this website detect i using adblock and ask me to unblock it

### Screenshot(s)

![Screenshot_20211126-004525_Firefox Beta](https://user-images.githubusercontent.com/49706147/143478461-108cc064-47d5-4372-8028-27ccca142b1f.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 95
filterset (summary): 
  network: 80393
  cosmetic: 20983
  scriptlet: 16225
  html: 600
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-1, 9d.6h.17m
  default: 
    ublock-filters: 30356-190, 4d.2h.35m
    ublock-badware: 3419-2, 4d.2h.37m
    ublock-privacy: 183-1, 12h.14m
    ublock-abuse: 67-0, 4d.2h.39m
    ublock-unbreak: 1706-0, 22h.53m
    adguard-mobile: 6990-172, 12h.16m
    easylist: 60918-23996, 4d.2h.42m
    easyprivacy: 26268-479, 4d.2h.33m
    urlhaus-1: 9532-0, 22h.51m
    plowe-0: 3685-3, 11d.14h.40m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4423
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
> I verified that the issue has not already been reported (use this button to find out)

and yet here is one -- https://github.com/uBlockOrigin/uAssets/issues/10547

**Comment by gorhill** [comment]
The _"Find similar reports"_ searched for `9anime.id`, so it would not show issues for `9anime.to`. Maybe the search should return the domain name without the TLD part.

The first sentence in the template though is:

> Force an update of your filter lists. 

Had OP done this, this would have solved his issue, his _"uBlock filters"_ list is over 4-day old.

**Comment by uBlock-user** [comment]
He could have still search for `9anime,` like you said before -- those checkboxes are just ignored, no real effort is being made.
