### ISSUE TITLE
weszlo.com: breakage

### ISSUE THREAD

**Issue by t0mciu** [uBlockOrigin/uAssets#10614]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than three (3) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists ([here is how to do this](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://weszlo.com/2021/11/24/zlota-pilka-robert-lewandowski-czy-leo-messi/`
`https://weszlo.com/2021/11/26/wywiad-mioduskiego-czyli-tonacy-chwyta-sie-kilku-brzytw-jednoczesnie/`

### Category

breakage

### Describe the issue

See Secrenshots

### Screenshot(s)

![we1](https://user-images.githubusercontent.com/20790170/143595874-890ff435-83a8-4078-9231-aae32cfc8963.png)
![we2](https://user-images.githubusercontent.com/20790170/143595899-fa62dcce-54c6-42e5-96c9-1099baed61af.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 78
filterset (summary): 
  network: 81841
  cosmetic: 47741
  scriptlet: 16642
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 479-0, 1d.23h.6m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 1d.23h.4m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2641-1, 120d.21h.39m
    https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 0-0, 34m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 32m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30288-58, 4d.53m
    ublock-badware: 3424-1, 4d.51m
    ublock-privacy: 182-0, 4d.49m
    ublock-abuse: 67-0, 4d.47m
    ublock-unbreak: 1701-2, 4d.45m
    easylist: 60949-174, 4d.43m
    easyprivacy: 26278-54, 4d.41m
    plowe-0: 3695-811, 26m
    POL-0: 7679-54, 1d.23h.10m
    POL-2: 1276-58, 1d.23h.12m
    urlhaus-1: 9538-0, 1d.23h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 730
  launchFromSelfie: false
```
</details>

**Comment by gorhill** [comment]
The detection occurs only when using _"POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda"_, POL filter list maintainers should look into this one -- not sure who to cc.

**Comment by gorhill** [comment]
Sidenote: you shouldn't be using NanoFilters or NanoAdblocker resources (I suspect this is what your `userResourcesLocation` points to), these are unmaintained, and uBO had always been able to defuse anti-blockers, see <https://www.reddit.com/r/uBlockOrigin/comments/jd1cy3/nano_adblock_ublocko_fork_getting_shut_down_will/g950gde/>.

**Comment by felix-22** [comment]
@t0mciu  I see your nickname is a polish name, preffered reporting to polish repository: https://github.com/MajkiIT/polish-ads-filter/issues
  
> gorhill : not sure who to cc.

@olegwukr @MajkiIT

**Comment by AroKol78** [comment]
from "AdGuard Base"
`weszlo.com##+js(abort-on-property-write.js, adquestoConfig)`

**Comment by felix-22** [comment]
Yes, with AdGuard Base enabled, the anti-adblock is fixed.
