### ISSUE TITLE
Crhoy video issues

### ISSUE THREAD

**Issue by milotic** [uBlockOrigin/uAssets#10618]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
```

https://www.crhoy.com/nacionales/video-alvarado-y-mendez-mata-reciben-insultos-en-inspeccion-vial/
https://www.crhoy.com/nacionales/video-lo-detienen-tras-rescatarlo-de-guindo-de-50-metros/
```

### Describe the issue

Hi, the newspaper website block the play button on videos if ublock is ON, turning off ublock force a video ad before the real video

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Firefox 94

### Settings

ublock origin default

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/0d535ed1496a4aa35565fb51cd582eb0c2fadb77

**Comment by mapx-** [comment]
@ryanbr

**Comment by gorhill** [comment]
Looks like a high traffic site, we should fix it in Unbreak until fixed in EasyList.
