### ISSUE TITLE
UBO broken  in chrome browsers under certain conditions

### ISSUE THREAD

**Issue by asianmusicguy** [uBlockOrigin/uAssets#10619]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`help.funimation.com`

### Describe the issue

 have tested help.funimation.com it is unable to read the accept Language header and instead redirect's to `https://www.funimation.com/out-of-territory/`
specifically in chrome based browsers with UBO installed and configured a certain way

thus making the support page unreachable unless directly accessed by adding the proper language  as follows

`https://help.funimation.com/hc/en-us`

I have tested the follow browsers

Edge

Firefox stable

Librewolf (privacy focused fork of Firefox https://librewolf-community.gitlab.io)

non chrome based browsers function as expected so i strongly believe that chrome and chromium based browsers may have a bug in relations to  handling and or transmission of accept headers  and this could affect other sites as well

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Vivaldi 4.4

### Settings

AdGuard Annoyances on
Fanboy annoyces ON
Adguard base on
Ublock annoyces on 
Ad guard tracking protection on
ad guard URL block filter on

### Notes

have had this configuration for years with no past problems

**Comment by uBlock-user** [comment]
Test on default settings/lists, we do not fix it's not reproducable on default settings/lists.

**Comment by uBlock-user** [comment]
`help.funimation.com` redirects me to `https://help.funimation.com/hc/en-us`

**Comment by asianmusicguy** [comment]
try with my settings above if im right and you do not fix it unless under default then where do i report this

**Comment by uBlock-user** [comment]
> then where do i report this

to the list causing your issue. I don't get sent to `https://www.funimation.com/out-of-territory/`

Sounds more of a geographical issue.

**Comment by asianmusicguy** [comment]
its not as its only on chrome basses and only with ublock installed its also not a list issue as firefox is not effected with the same configuration set

**Comment by uBlock-user** [comment]
> have tested help.funimation.com it is unable to read the accept Language header and instead redirect's to 

Sounds like a site issue, nothing from uBO side can cause this.

**Comment by asianmusicguy** [comment]
I am telling you there is a issue  related to how UBO is handling certain filter configurations on ALL chrome based browser and only chrome based browsers

**Comment by uBlock-user** [comment]
@gorhill can you reproduce ?

**Comment by gorhill** [comment]
Yes, the problematic filter is `||cloudflare.com/cdn-cgi/trace$xmlhttprequest,3p,redirect-rule=noop.txt` in _"uBlock filters -- Unbreak"_.

https://help.funimation.com/

**Comment by uBlock-user** [comment]
Should we remove the filter itself or create a redirection exception ?

**Comment by gorhill** [comment]
We can replace the filter with the following one for now:

    ||cloudflare.com/cdn-cgi/trace$xmlhttprequest,3p,redirect-rule=noop.txt,domain=~funimation.com

I don't know why the redirect-rule was added -- possibly to lower breakage -- so let's keep it but exclude that domain for now.

**Comment by uBlock-user** [comment]
> I don't know why the redirect-rule was added  -- possibly to lower breakage --

It as your suggestion on the filter I added previously when I fixed another case with `##+js(no-xhr-if)`
