### ISSUE TITLE
Criteria/Policy for Inclusion of Filters

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#1061]
A lot of filters have been added to the uBO filter lists in the past few months and activity has also significantly increased. 

While I highly appreciate the work of the contributors, filters have been added for websites which I believe will not benefit the majority of uBO users and will only populate the list. The uBO list also does not follow any specific language like most other filter lists and filters have been added for many different language websites.

I have also been told in the past that filters for leftover ad elements will not specifically be added to the list as they will only serve to populate it but there is no official word about this.

There have been some technical disagreements over filter creation and while understanding has been reached among contributors it hasn't been documented.

Taking these points into account there should be a policy or criterion for including filters for websites into the uBO list to address such questions.

**Comment by anewuser** [comment]
Why do you care about the number of filters? Provide evidence that the current number of filters "populating the list" has any negative impact for users, or open threads for specific filters that are demonstratively problematic.

**Comment by gotitbro** [comment]
@anewuser I am only asking that there be a policy for addressing filter issues like EasyList has https://easylist.to/pages/policy.html.

**Comment by gotitbro** [comment]
@mapx- Why has this been closed? This is a valid point discussion.

**Comment by klaksoner** [comment]
> The uBO list also does not follow any specific language

Easylist too
https://github.com/easylist/easylist/commit/5ea5ea6e24fb015df5b917cd34be8c7ae9a6e60d
https://github.com/easylist/easylist/commit/f42e65058ed5e5050e55d388b249b9d50d372f0e
https://github.com/easylist/easylist/commit/16a23c9922b85153f400c0e93113ca62903363a7
https://github.com/easylist/easylist/commit/5c0679db0f3dcb4977557b681aa49ebeb18fb231
