### ISSUE TITLE
natureetdecouvertes.com: breakage

### ISSUE THREAD

**Issue by mattiasdrp** [uBlockOrigin/uAssets#10615]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists ([here is how to do this](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.natureetdecouvertes.com/idee-cadeau/bebe-enfant`

### Category

breakage

### Describe the issue

When loading this page for the first time, no image appear. If I then go in the "age" selector and select 0-3 for example, the images load. When going back to all ages, the image are now loaded (I know it comes from Ublock because when I disable it the images are loaded)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/5543639/143615091-bf6f0600-2e61-431b-b149-ffdce105cd09.png)
![image](https://user-images.githubusercontent.com/5543639/143615116-45be3d30-816c-4177-9533-14cfa26313b2.png)
![image](https://user-images.githubusercontent.com/5543639/143615153-93778c8d-004b-471b-8d07-4cf4ca3d7883.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 95
filterset (summary): 
  network: 93583
  cosmetic: 48311
  scriptlet: 16214
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30295-27, never
    ublock-badware: 3425-1, never
    ublock-privacy: 182-0, never
    ublock-abuse: 67-0, never
    ublock-unbreak: 1701-0, never
    easylist: 60746-629, never
    easyprivacy: 25518-215, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-3, never
    FRA-0: 25889-555, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1243
  launchFromSelfie: false
```
</details>

**Comment by gorhill** [comment]
This fixes the issue for me:

    ||natureetdecouvertes.com^$1p,image,redirect-rule=2x2.png

**Comment by mattiasdrp** [comment]
Thanks ;-)

**Comment by mapx-** [comment]
However, @ryanbr should fix the issue on EP side too

`@@||natureetdecouvertes.com^$image,1p`

so, we''ll just add a `badfilter` filter to keep our filter

**Comment by uBlock-user** [comment]
> @@||natureetdecouvertes.com^$image,1p

That will allow first-party pixel and beacon tracking to occur, hence the redirection filter.

**Comment by gorhill** [comment]
I don't think badfiltering is worth it, it's a case of 1st-party pixel image, and our filter is still useful in case the site change the filter targeted by the bait image.

**Comment by uBlock-user** [comment]
No need to add anything, EP is doing its job, site design is the issue blocking pixel and beacon tracking shouldn't break site like that.

**Comment by mapx-** [comment]
I said: **if EP will add an exception we should add a badfilter for that exception.**

**Comment by uBlock-user** [comment]
There's nothing to fix for ryanbr, no site images are blocked.

**Comment by mapx-** [comment]
yes, the images are blocked, if you cannot reproduce it's another issue. Why on earth was that filter added ?

**Comment by uBlock-user** [comment]
>  the images are blocked

Which specifically ?

> Why on earth was that filter added ?

Which filter ?

**Comment by uBlock-user** [comment]
>  if you cannot reproduce

I can reproduce the issue, but the issue is caused by blocked pixel and beacon tracking filter, so it should not be whitelisted, thats the point.

**Comment by mapx-** [comment]
lol, so you finally understood. 

It's a breakage and it should be fixed.

**Comment by uBlock-user** [comment]
> It's a breakage and it should be fixed.

Caused by the bad site design, also upto @ryanbr if he wants to, I would personaly suggest not to.

**Comment by gorhill** [comment]
> I would personaly suggest not to.

**Comment by gorhill** [comment]
> I would personaly suggest not to.

When EasyPrivacy breaks a site, this has to be fixed for the sake of all blockers using EasyPrivacy.

**Comment by uBlock-user** [comment]
> this has to be fixed for the sake of all blockers using EasyPrivacy.

Sure, on that principle.
