### ISSUE TITLE
Adblock Detected when used https://anydebrid.com/

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#10616]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://anydebrid.com/premium-link-generator/uploadhaven.com`

### Describe the issue

anti adblock appear when we about to download from there...

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

### Notes

You can test this link for example from it
`https://uploadhaven.com/download/1256ce138801b4b49b5319240db15be8`

**Comment by gorhill** [comment]
There are multiple channels for both Chrome and uBO, so just saying "latest" is not helpful. Just disclose the version number to save time.

**Comment by Dhanamerdeka** [comment]
> There are multiple channels for both Chrome and uBO, so just saying "latest" is not helpful. Just disclose the version number to save time.

because everytime i about to report something... i checked wheter my chrome/ublock had update or not...
so after all updated.... i tested it again... and if the problem still occur... i report like this....

on my previous issue... also i put lastest chrome and ub because it easier to me....
but if u insist well
1.38.6 for ub
and 96.0.4664.45  for chrome

**Comment by gorhill** [comment]
When I navigate to your link, I get a form called _"Uploadhaven premium link generator"_, there is no link to download anything.

**Comment by mapx-** [comment]
put in
`https://uploadhaven.com/download/1256ce138801b4b49b5319240db15be8`

**Comment by gorhill** [comment]
With that URL I get _"Hotlink protection active. Download from original site"_, no anti blocker on my side.

**Comment by mapx-** [comment]
I get immediately (even using `example.com`) 

![image](https://user-images.githubusercontent.com/10303732/143619844-921fb84c-a559-4a90-9d19-96a72fada1a0.png)

(chrome)

**Comment by Dhanamerdeka** [comment]
> I get immediately (even using `example.com`)
> 
> ![image](https://user-images.githubusercontent.com/10303732/143619844-921fb84c-a559-4a90-9d19-96a72fada1a0.png)
> 
> (chrome)

yeah that's my point....
i hope ub team can solve this....

**Comment by gorhill** [comment]
It works after I allowed `juicyads.com`, so we might have to create an exception..

**Comment by mapx-** [comment]
it's all here ...
`https://anydebrid.com/assets/js/bunddlev6.min.js`

**Comment by uBlock-user** [comment]
`@@||adserver.juicyads.com/js/$script,domain=anydebrid.com`, no alternative to exceptions ?

**Comment by uBlock-user** [comment]
Came close with `##+js(aost, Promise, stackDepth:3)` but breaks the button too.

**Comment by Dhanamerdeka** [comment]
> `https://uploadhaven.com/download/1256ce138801b4b49b5319240db15be8`

After testing this... it seems working good
any other feedback?

tested on https://anydebrid.com/

**Comment by mapx-** [comment]
`nostif, \x` => eternal loading

**Comment by Dhanamerdeka** [comment]
![image](https://user-images.githubusercontent.com/29838157/143620346-f314421a-cc30-4359-80ce-30a17c6083cc.png)
Previous solution works... no ads appear... maybe we should push this on official filter list....
after had other's improvement....

**Comment by gorhill** [comment]
This works for me, without allowing `juicyads.com`:

    *$script,redirect-rule=noopjs,domain=anydebrid.com,badfilter
    ||adserver.juicyads.com/js/jads.js$script,redirect-rule=noop.js,domain=anydebrid.com

The site checks that requests which should fail (because resource does not exist) are actually not failing, i.e. it detects uBO's redirect-rule filters specifically.
