### ISSUE TITLE
mg.superesportes.com.br: ads

### ISSUE THREAD

**Issue by Hellements** [uBlockOrigin/uAssets#10626]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.mg.superesportes.com.br/`

### Category

ads

### Describe the issue

The site is showing two ads (at the beginning and end of the page).

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 81133
  cosmetic: 41688
  scriptlet: 16236
  html: 598
listset (total-discarded, last updated): 
  added: 
    spa-1: 4141-53, 2d.23h.43m
  default: 
    ublock-filters: 30136-27, 3d.3h.14m
    ublock-badware: 3440-1, 3d.3h.11m
    ublock-privacy: 183-0, 3d.3h.9m
    ublock-abuse: 70-0, 3d.3h.7m
    ublock-unbreak: 1701-0, 3d.3h.5m
    easylist: 60991-586, 3d.3h.3m
    easyprivacy: 26309-489, 3d.2h.39m
    urlhaus-1: 10291-0, 9h.23m
    plowe-0: 3699-3, 3d.2h.8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 271
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
```
mg.superesportes.com.br##.se-publicidade-rasgado-1-container
mg.superesportes.com.br##.se-publicidade-rasgado-1-top
```

@Alex-302

**Comment by felix-22** [comment]
Also maybe @jabonsolo @felippesantos46 ([EasyList Portuguese](https://github.com/easylist/easylistportuguese/issues))
(Yes - I know EasyList Portuguese isn't in uBO but I think it can be worth to let them know)

**Comment by Yuki2718** [comment]
I only see placeholder and not ads, nevertheless fixed.

**Comment by felippesantos46** [comment]
@felix-22 I could also just see placeholders, on the other hand the issue was fixed https://github.com/easylist/easylistportuguese/commit/74220d94723966d96d13471e6f349d579e92ef65

**Comment by felix-22** [comment]
Ok. I only pinged/informed about OP's report, so:
- I'm not sure whether OP saw ads or placeholders, but given a fact 3 users in this thread (including me) saw placeholders only, I guess OP too
- I think OP expressed himself vaguely / ambiguously / unclear / by a thought abbreviation, he should say the site is showing placeholders and not ads
