### ISSUE TITLE
samehadaku.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1062]
URL(s) where the issue occurs

https://www.samehadaku.net/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
`@@||samehadaku.net^*/advertisement.js$script,~third-party`
or
`samehadaku.net##script:inject(abort-on-property-write.js, adBlock)`
