### ISSUE TITLE
baike.baidu.com: privacy

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10622]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://baike.baidu.com/item/%E5%86%85%E8%B4%A8%E7%BD%91/601571`

### Category

privacy

### Describe the issue

This domain is most likely used for tracking and is included in many Chinese privacy lists.
```
||cstm.baidu.com^
```
`https://github.com/privacy-protection-tools/anti-AD/blob/5963788fd10ce935fb057e6db425cde3a6c6f2d9/anti-ad-easylist.txt#L6158`
`https://github.com/Crystal-RainSlide/AdditionalFiltersCN/blob/cf717b1f4db11b7d220be6d6c2e157a48915b908/CN/DC.txt#L42`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/143665906-e7c3c415-7897-41f9-a3a3-e7ad8dda81b1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 105452
  cosmetic: 101924
  scriptlet: 18961
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1433-0, 15h.52m
    fanboy-annoyance: 58985-150, 15h.52m
    ublock-annoyances: 4311-128, 15h.52m
  default: 
    CHN-0: 26730-86, 15h.52m
    easylist: 61152-11, 15h.52m
    easyprivacy: 26336-43, 15h.52m
    plowe-0: 3699-811, 15h.52m
    ublock-abuse: 74-0, 15h.43m
    ublock-badware: 3451-58, 15h.51m
    ublock-filters: 29635-161, 15h.50m
    ublock-privacy: 187-9, 15h.35m
    ublock-unbreak: 1695-42, 15h.49m
    urlhaus-1: 10291-0, 15h.49m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 679
  launchFromSelfie: true
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr
