### ISSUE TITLE
gankrin.org: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10623]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://gankrin.org/how-to-distribute-ship-python-modules-to-other-nodes-in-pyspark/`

### Category

ads

### Describe the issue

There are ads placeholders in the site. Proposed filters:

```
gankrin.org##[id^="custom_html"]
gankrin.org##.code-block
gankrin.org##p:not(:has-text(/[a-z]/))
```

### Screenshot(s)

<details>

![image](https://user-images.githubusercontent.com/66517106/143665990-d0155e69-e60e-4e9f-b11d-700a7a3c9dfb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 79864
  cosmetic: 39263
  scriptlet: 16086
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30218-27, 1m
    ublock-badware: 3465-1, 1m
    ublock-privacy: 183-0, 1m
    ublock-abuse: 74-0, 1m
    ublock-unbreak: 1709-0, 1m
    easylist: 61173-544, 1m
    easyprivacy: 26342-473, 1m
    urlhaus-1: 10146-0, 1m
    plowe-0: 3695-3, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 437
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
```
gankrin.org##.widget_custom_html:has(.adsbygoogle)
gankrin.org##.code-block:has(.adsbygoogle)
```
@ryanbr

**Comment by iam-py-test** [comment]
Can't the _to be fixed by EL / EP / FA_ label be removed after it's fixed?
