### ISSUE TITLE
live.lequipe.fr: breakage

### ISSUE THREAD

**Issue by joelthelion** [uBlockOrigin/uAssets#10628]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://live.lequipe.fr/lachainelequipe/`

### Category

breakage

### Describe the issue

Video doesn't play with uBO enabled. It does when I disable it.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 95
filterset (summary): 
  network: 98671
  cosmetic: 73926
  scriptlet: 26571
  html: 598
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 19m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    adguard-generic: 61685-4387, 3h.47m
    adguard-mobile: 7005-156, 3h.49m
  default: 
    ublock-filters: 30189-40, 3h.45m
    ublock-badware: 3465-1, 3h.43m
    ublock-privacy: 183-0, 3h.41m
    ublock-abuse: 70-0, 3h.57m
    ublock-unbreak: 1709-0, 3h.55m
    easylist: 61173-668, 3h.53m
    easyprivacy: 26342-480, 3h.51m
    plowe-0: 3695-3, 3h.59m
    urlhaus-1: 10146-0, 3h.39m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 459
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
test

```
@@||live.lequipe.fr/thirdparty/prebid.js$xhr,1p
@@||accounts.google.com/gsi/client$script,domain=live.lequipe.fr
```

@ryanbr  for prebid
@Yuki2718 for french adguard / base list, the seond one is blocked by some bad regex

**Comment by felix-22** [comment]
> mapx- : `$xhr`

For me (Firefox) the video works only after changing to `$script`, I don't see any `xhr` in Logger anyway.

**Comment by mapx-** [comment]
I added `script` too after testing in FF

**Comment by felix-22** [comment]
By the way, in Opera the video breakage doesn't occur for me at all, only in Firefox.

**Comment by iam-py-test** [comment]
I can reproduce in M$ Edge:
![image](https://user-images.githubusercontent.com/84232764/143687429-a4b506ae-3e50-4b03-94f4-583c2e9ef0ae.png)
Your filters fix the issue, but I can not continue because it is paywalled. 
However, it does seem to be GeoLocked to France. It refused to load with my ip or even from Ireland. 
It's almost like this website doesn't want people to use it

**Comment by felix-22** [comment]
Yeah, it's geolocked to France, but the breakage causes black screen in th video player, and after applying the fix, it shows GeoLock message, which most likely means the video works fine, and  there is no breakage anymore, only GeoLock.
