### ISSUE TITLE
[nsfw] bdsmlr.com: breakage

### ISSUE THREAD

**Issue by 0x729000** [uBlockOrigin/uAssets#10621]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://bdsmlr.com/login`

### Category

breakage

### Describe the issue

Login elements are blocked, unable to log in.

If uBO is disabled, user logs in, then re-enables - the rules are fine.

### Screenshot(s)

https://user-images.githubusercontent.com/92766418/143665604-98020ea3-9c69-41e2-a292-ef270a75fa75.png
https://user-images.githubusercontent.com/92766418/143665605-bcd149e2-275b-4b0e-819c-13f0cce2a841.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80169
  cosmetic: 39233
  scriptlet: 16063
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30143-27, 2d.7h.42m
    ublock-badware: 3440-1, 2d.7h.40m
    ublock-privacy: 182-0, 1d.2h.20m
    ublock-abuse: 70-0, 1d.2h.18m
    ublock-unbreak: 1709-0, 3h.59m
    easylist: 61173-163, 3h.57m
    easyprivacy: 26341-45, 3h.55m
    urlhaus-1: 10514-0, 3h.53m
    plowe-0: 3685-812, 13d.1h.12m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 615
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
`bdsmlr.com#@#.ads-container`

@ryanbr
