### ISSUE TITLE
nlab.itmedia.co.jp: breakage

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#10629]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://nlab.itmedia.co.jp/nl/spv/`

### Category

breakage

### Describe the issue

When you tap the header (hamburger menu, crown, search, and config icons) of their mobile sites, nothing will happens.

~~~
!#if env_mobile
||scdn.cxense.com/cx.js$script,redirect=noop.js,domain=nlab.itmedia.co.jp
!#endif
~~~

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 82207
  cosmetic: 25201
  scriptlet: 16242
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30325-192, now
    ublock-badware: 3472-2, now
    ublock-privacy: 183-1, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1714-0, now
    adguard-mobile: 7009-181, now
    easylist: 61192-24050, now
    easyprivacy: 26369-503, now
    urlhaus-1: 10146-0, now
    plowe-0: 3695-3, now
    JPN-1: 5284-133, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 373
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
yes, I'm able to reproduce the issue @Yuki2718
