### ISSUE TITLE
calendrier.com: ads

### ISSUE THREAD

**Issue by casualkitten1** [uBlockOrigin/uAssets#10637]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.calendrier.com/`

### Category

ads

### Describe the issue

There's an ad at the top of the screen. (file link : https://www.calendrier.com/images/promo/saveur.jpg)

### Screenshot(s)

<img width="880" alt="image" src="https://user-images.githubusercontent.com/49318780/143719656-ad0d9da7-f28e-436a-a072-7ecf5bb7b6b8.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 103570
  cosmetic: 44418
  scriptlet: 18938
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 58992-30299, now
    fanboy-cookiemonster: 20423-20423, now
    ublock-annoyances: 4315-132, now
  default: 
    FRA-0: 25891-3208, 1m
    easylist: 61197-23464, now
    easyprivacy: 26370-346, now
    plowe-0: 3697-820, now
    ublock-abuse: 74-1, now
    ublock-badware: 3468-66, now
    ublock-filters: 29678-458, now
    ublock-privacy: 189-9, now
    ublock-unbreak: 1698-41, now
    urlhaus-1: 10388-0, now
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3267
  launchFromSelfie: false
```
</details>

**Comment by okiehsch** [comment]
`calendrier.com##.promo_link`

**Comment by gorhill** [comment]
Should be fixed in AdGuard France, cc @Yuki2718.

**Comment by Yuki2718** [comment]
Is this ad and not self-promo? IOW `www.calendrier.com` and `www.initiatives-chocolats.fr` are different entities?

**Comment by mapx-** [comment]
I see no connection between them, even the contact details are completely different

**Comment by Yuki2718** [comment]
Okay, will fix in French list.
