### ISSUE TITLE
bilibili.com: privacy

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10630]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.bilibili.com/`

### Category

privacy

### Describe the issue

`cm.bilibili.com` looks like a domain used to track. Blocking it won't cause any problem.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/143682660-39791c1c-fe5c-4d7a-9adf-736f965a0807.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 122965
  cosmetic: 102026
  scriptlet: 18968
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://anti-ad.net/easylist.txt: 46565-2, 30m
    https://cdn.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule/rule.txt: 1164-66, never
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1433-0, 1d.2h.12m
    fanboy-annoyance: 58985-227, 1d.2h.12m
    ublock-annoyances: 4311-128, 1d.2h.12m
  default: 
    CHN-0: 26730-5761, 1d.2h.12m
    easylist: 61152-14570, 1d.2h.12m
    easyprivacy: 26336-8987, 1d.2h.12m
    plowe-0: 3699-1571, 1d.2h.12m
    ublock-abuse: 74-5, 1d.2h.3m
    ublock-badware: 3451-63, 1d.2h.10m
    ublock-filters: 29635-164, 1d.2h.9m
    ublock-privacy: 187-15, 1d.1h.55m
    ublock-unbreak: 1695-42, 1d.2h.9m
    urlhaus-1: 10291-2, 1d.2h.9m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 699
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
```
||hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js^$script
||hdslb.com/bfs/static/jinkela/long/js/sentry^$script
```

@shenzhiming88 any breakages with those filters ?

**Comment by shenzhiming88** [comment]
@uBlock-user 
`||hdslb.com/bfs/static/jinkela/long/js/sentry^$script` cuases homepage broken. Another rule is fine.
And what about `cm.bilibili.com`? I think it should be blocked too. Thanks!

**Comment by shenzhiming88** [comment]
@ryanbr

**Comment by xiongbear0** [comment]
It seems that `||hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js^$script` cause the page connot load the comment section.

**Comment by uBlock-user** [comment]
@xiongbear0 force update ublock privacy list

**Comment by gorhill** [comment]
Related: <https://linustechtips.com/topic/1400319-cmbilibili-blocked-whats-bad-about-a-tracker-and-why-does-this-one-get-blocked/>

**Comment by shenzhiming88** [comment]
@gorhill use `||cm.bilibili.com/cm/api/$xhr` instead?
