### ISSUE TITLE
forums.tomsguide.com: ads

### ISSUE THREAD

**Issue by shippaishi** [uBlockOrigin/uAssets#10638]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://forums.tomsguide.com/threads/laptop-screen-goes-black-but-when-i-move-it.453343/`

### Category

ads

### Describe the issue

a video ad shows up in the middle of the thread that I was trying to read

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 79640
  cosmetic: 39212
  scriptlet: 16168
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30285-28, 3d.15h.2m
    ublock-badware: 3430-1, 3d.14h.54m
    ublock-privacy: 183-0, 3d.19h.4m
    ublock-abuse: 70-0, 3d.15h
    ublock-unbreak: 1705-0, 2d.15h.50m
    easylist: 60991-538, 3d.14h.58m
    easyprivacy: 26309-474, 3d.14h.56m
    urlhaus-1: 10146-0, 19h.7m
    plowe-0: 3689-3, 7d.17h.25m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 374
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
`forums.tomsguide.com###video_ad`

@ryanbr
