### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Cubsfanryan** [uBlockOrigin/uAssets#10639]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.twitch.tv/tsm_imperialhal`

### Category

ads

### Describe the issue

There are pre roll ads. 

### Configuration

<details>

```yaml
uBlock Origin: 1.39.1b0
Firefox: 94
filterset (summary): 
  network: 80155
  cosmetic: 39280
  scriptlet: 16094
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30232-28, 1m
    ublock-badware: 3472-1, 1m
    ublock-privacy: 185-0, 1m
    ublock-abuse: 74-0, 1m
    ublock-unbreak: 1709-0, 1m
    easylist: 61197-545, 1m
    easyprivacy: 26370-473, 1m
    urlhaus-1: 10388-0, 1m
    plowe-0: 3697-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 820
  launchFromSelfie: false
```
</details>

**Comment by gorhill** [comment]
>  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)

<https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22twitch.tv%22+in%3Atitle>.
