### ISSUE TITLE
meduza.io: leftover

### ISSUE THREAD

**Issue by No-ADS** [uBlockOrigin/uAssets#10632]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://meduza.io/news/2021/11/26/rossiya-ogranichit-v-ezd-iz-gonkonga-i-stran-yuga-afriki-iz-za-novogo-shtamma-koronavirusa`

### Category

leftover

### Describe the issue

`#@#[id^="div-gpt-ad"]`
Why did you add this?

### Screenshot(s)

<details>

![2021-11-27_162538](https://user-images.githubusercontent.com/94611448/143685521-4dc56a1e-5d84-432a-b0a1-c1f8eb8f095a.png)
<summary>Screen</summary>
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.1b0
Chromium: 96
filterset (summary): 
  network: 99724
  cosmetic: 79816
  scriptlet: 20387
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 20423-19, now
    ublock-annoyances: 4315-120, now
  default: 
    RUS-0: 39985-9, 1m
    easylist: 61192-22, 1m
    easyprivacy: 26369-113, 1m
    plowe-0: 3695-814, 1m
    ublock-abuse: 74-1, 1m
    ublock-badware: 3468-58, 1m
    ublock-filters: 29675-160, 1m
    ublock-privacy: 187-1, 1m
    ublock-unbreak: 1698-39, 1m
    urlhaus-1: 10388-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3608
  launchFromSelfie: false
```
</details>

**Comment by uBlock-user** [comment]
> Why did you add this?

To defuse google contributor anti-adblock

**Comment by gorhill** [comment]
Should this be taken care in RUS list?

**Comment by uBlock-user** [comment]
RUS list doesn't have `#@#[id^="div-gpt-ad"]`, we do.

**Comment by gorhill** [comment]
I don't see `#@#[id^="div-gpt-ad"]` causing the issue on this site, there are still placeholders when I use `##[id^="div-gpt-ad"][id^="div-gpt-ad"]`.

**Comment by uBlock-user** [comment]
The placeholder OP's reporting is present due to `#@#[id^="div-gpt-ad"]`

**Comment by gorhill** [comment]
Ok, my bad, I was testing without RUS. Once I enable RUS, I see only that one placeholder, and in my opinon it hsould be fixed with:

    meduza.io##[id^="div-gpt-ad"][id^="div-gpt-ad"]

To make it clear we are countering the exception filter. I don't see the need for the other cosmetic filters you added.

**Comment by No-ADS** [comment]
@dimisa-RUAdList

**Comment by uBlock-user** [comment]
> Ok, my bad, I was testing without RUS

Likewise, I too thought I had RUS enabled, removed the other placeholder filters I added.

**Comment by dimisa-RUAdList** [comment]
Maybe better ? >
del: `meduza.io##[id^="div-gpt-ad"][id^="div-gpt-ad"]`, `*##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important)`

add: `*##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important;margin:0!important;padding:0 !important)`

**Comment by gorhill** [comment]
I think it's a good idea, we should try it -- the point of the filter was to reduce visibility without using `display: none`, so removing the margin/padding makes sense.
