### ISSUE TITLE
zwei-euro.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#10636]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.zwei-euro.com/uebersicht/`

### Describe the issue

Anti Adblock (only annoyance)

### Screenshot(s)

<img width="700" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/143700912-d642f740-5952-4cad-8727-31f4f6a38992.PNG">

### uBlock Origin version

1.39.0

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

### Notes

Filter suggestion: 
`zwei-euro.com##+js(nostif, Delay)`

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by JobcenterTycoon** [comment]
clear browser data because they set a local storage object
