### ISSUE TITLE
cli.im: privacy

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10646]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://cli.im/`

### Category

privacy

### Describe the issue

```
https://static.clewm.net/public/cli_analytics.js
https://cli.im/Api/ClickLog/click?callback=jQuery19104854899495474805_1638113270553&sec=152003&_=1638113270554
```

I think these are used to track. So please deal with them. Thanks!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 105708
  cosmetic: 101924
  scriptlet: 18961
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1471-0, 1d.2h.16m
    fanboy-annoyance: 58985-150, 2d.4h.34m
    ublock-annoyances: 4311-128, 2d.4h.33m
  default: 
    CHN-0: 26730-86, 2d.4h.34m
    easylist: 61152-11, 2d.4h.34m
    easyprivacy: 26376-43, 36m
    plowe-0: 3699-811, 2d.4h.33m
    ublock-abuse: 74-0, 2d.4h.24m
    ublock-badware: 3451-58, 2d.4h.32m
    ublock-filters: 29635-161, 2d.4h.31m
    ublock-privacy: 189-9, 27m
    ublock-unbreak: 1695-42, 2d.4h.30m
    urlhaus-1: 10468-0, 37m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 514
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
@ryanbr
