### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by Sakurakouji-Runa** [uBlockOrigin/uAssets#10641]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.bilibili.com/video/BV1JX4y157Lp`

and any other video

### Category

breakage

### Describe the issue

Comments section not showing up

### Screenshot(s)

uBO on
![Snipaste_2021-11-28_11-05-08](https://user-images.githubusercontent.com/46081776/143727293-6dea1a04-574b-4d69-b697-67f1f6086f87.png)

uBO off
![Snipaste_2021-11-28_11-05-50](https://user-images.githubusercontent.com/46081776/143727303-d915fc08-c9fb-4e10-a435-07ffe3b18418.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 96538
  cosmetic: 49119
  scriptlet: 16228
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 26766-86, 1h.20m
    easylist: 61173-11, 19h.3m
    easyprivacy: 26335-43, 1d.20h.20m
    plowe-0: 3698-811, 6d.1h
    ublock-abuse: 74-0, 1h.29m
    ublock-badware: 3451-58, 1d.20h.18m
    ublock-filters: 29678-140, 1h.23m
    ublock-privacy: 189-1, 1h.31m
    ublock-unbreak: 1698-39, 1h.27m
    urlhaus-1: 10146-0, 1h.18m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [empty]
  triggered: 
    no-csp-reports: * true
modifiedUserSettings: 
  firewallPaneMinimized: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 825
  launchFromSelfie: false
```
</details>

**Comment by stephenhawk8054** [comment]
Have you forced update the filter lists and disabled custom filter lists as written in Prerequisites

```
- I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")
- I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
```

because I see that your Peter Lowe filter list was updated 6 days ago and you are using 8 custom filters + 3 sites set as trusted.

**Comment by Sakurakouji-Runa** [comment]
I reinstalled uBO, but this issue still exists.

**Comment by byzod** [comment]
I can reproduce this bug
It's worth noting that even dynamic rules `www.bilibili.com * * noop` (allow everything on bilibili) is not working, only when `www.bilibili.com` was added to the whitelist can make the comment section visible

I doubt that bilibili is checking adblocker

**Comment by Sakurakouji-Runa** [comment]
Could you force an update of filter lists, then try again?
As I see it, uBO works properly now.

**Comment by Sakurakouji-Runa** [comment]
> I can reproduce this bug on `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0` It's worth noting that even dynamic rules `www.bilibili.com * * noop` (allow everything on bilibili) is not working, only when `www.bilibili.com` was added to the whitelist can make the comment section visible
> 
> I doubt that bilibili is checking adblocker

Could you force an update of filter lists, then try again?
As I see it, uBO works properly now.
