### ISSUE TITLE
ilbianconero.com: breakage

### ISSUE THREAD

**Issue by pietro63** [uBlockOrigin/uAssets#10643]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.ilbianconero.com/`

### Category

breakage

### Describe the issue

In all the page the scroll up and down is blocked, itàs not possible scroll up or down the page so only a portion is visible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 85306
  cosmetic: 46181
  scriptlet: 16067
  html: 598
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 7h.4m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30164-33, 2d.21h.27m
    ublock-badware: 3440-1, 2d.21h.17m
    ublock-privacy: 184-0, 2d.21h.19m
    ublock-abuse: 70-0, 2d.21h.21m
    ublock-unbreak: 1706-0, 2d.21h.15m
    easylist: 61109-546, 2d.21h.25m
    easyprivacy: 26327-476, 2d.21h.23m
    plowe-0: 3689-3, 7d.8h.33m
    ITA-0: 12523-1, 18h.35m
    urlhaus-1: 10146-0, 18h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 191 redacted]
switchRuleset: 
  added: [array of 41 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 790
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
Force an update of _"uBlock filters -- Unbreak"_  in a few minutes.

**Comment by mapx-** [comment]
@ryanbr  
EP issue
`@@||quantcast.mgr.consensu.org/tcfv2/cmp2.js$script,domain=ilbianconero.com`

**Comment by gorhill** [comment]
I tried to refuse consent and the page was still broken.

**Comment by mapx-** [comment]
yes, because it's P Lowe's issue too

```
@@||tags.tiqcdn.com/utag/rcsmedia/calciomercato/prod/utag.$script,domain=ilbianconero.com
@@||quantcast.mgr.consensu.org/tcfv2/cmp2.js$script,domain=ilbianconero.com
```

However, using you filter the cookies consent it's gone and some videos could be broken ,for example the auto playing one on any page (I know  could be considered an ad but who knows if other legit video still broken ? )

**Comment by gorhill** [comment]
So let's keep our filter instead ow excepting more 3rd parties -- allowing these kind of defeat the purpose of refusing consent. EP can always fix the consent dialog.

**Comment by okiehsch** [comment]
It's a GDPR modal of a european site, chances are if you block it some functionality is broken.

**Comment by gorhill** [comment]
The video which does not play is the same video on all articles I checked, so probably not legit.

**Comment by gorhill** [comment]
The video which plays on every article has its own article, in which it plays fine without `tiqcdn`: <https://www.ilbianconero.com/a/chirico-juve-atalanta-solito-copione-interpreti-senza-idee-e-nes-45388> -- I am guessing legit videos are Youtube-based and work fine.

**Comment by okiehsch** [comment]
Seem to be mostly instagram and twitter based, I found a few, those will still play even without a GDPR modal.
I wonder about the comments but they don't work on my end no matter what.

**Comment by gorhill** [comment]
Note that the repeated video is held in a `.adv` div.

**Comment by okiehsch** [comment]
https://www.ilbianconero.com/a/juve-atalanta-le-pagelle-dei-giornali-morata-horror-stecca-anche-72667

it states there are 6 comments but I don't see any, even if I disable uBO.
Probably a site issue.

**Comment by gorhill** [comment]
> I wonder about the comments

I see the comments fine on my side, they are facebook-based.
