### ISSUE TITLE
tvhai.org: nuisance

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10640]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://tvhai.org/xem-phim-hawkeye-mat-dieu-hau-541840`

### Category

nuisance

### Describe the issue

I think this is just a dev tools annoyance issue. With this site, when I open the dev tools, the video player just stops loading or starting (white blank player).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66517106/143726983-13ed0034-176b-4115-bc26-9e7805866194.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 81315
  cosmetic: 41754
  scriptlet: 18867
  html: 606
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4325-6, now
    VIE-1: 2094-10, now
  default: 
    ublock-filters: 30232-27, now
    ublock-badware: 3472-1, now
    ublock-privacy: 185-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1709-0, now
    easylist: 61197-585, now
    easyprivacy: 26372-477, now
    urlhaus-1: 10443-0, now
    plowe-0: 3697-3, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 272
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
however, at least on my side the `nosiif` filter does not in chrome (even seeing the code in console)

![image](https://user-images.githubusercontent.com/10303732/143732901-86ad6ecc-097b-4d23-99ed-e2599cb620c0.png)

**Comment by uBlock-user** [comment]
That's strange, working for me on Chrome 96

**Comment by hoang-rio** [comment]
ABPVN has rule process this site but it recently change domain. I will update it to new domain

**Comment by uBlock-user** [comment]
> also anti-adblock should be fixed

filter present in VIE list.

**Comment by uBlock-user** [comment]
> the nuisance issue happens on tvhai.co too, can't play video with console opened:

could you provide iframe url ?

**Comment by stephenhawk8054** [comment]
> > the nuisance issue happens on tvhai.co too, can't play video with console opened:
> 
> could you provide iframe url ?

I think the embed has this structure:
`https://tvhai.co/embed/?url=https://short.ink/Hx8xAGaZ0`

And I think inside that embed is this iframe:
`https://short.ink/Hx8xAGaZ0`

![image](https://user-images.githubusercontent.com/66517106/143866763-d4d11f4a-b87f-47f1-b0df-72e49d5fa915.png)

I think there's also a fast popup when clicking on the video player with that `short.ink` link

![image](https://user-images.githubusercontent.com/66517106/143866908-0976a582-4b24-4a42-95c7-f47491ce35c8.png)

**Comment by uBlock-user** [comment]
Avoid opening the iframe in a new tab, they can detect that too. Anyways, it's hydrax -- https://github.com/uBlockOrigin/uAssets/commit/23b8938667d057ea6afe3265fe3a920d5787ff47

**Comment by stephenhawk8054** [comment]
> Avoid opening the iframe in a new tab, they can detect that too. Anyways, it's hydrax -- [23b8938](https://github.com/uBlockOrigin/uAssets/commit/23b8938667d057ea6afe3265fe3a920d5787ff47)

Yup, confirm I can open the dev tools now :thumbsup:

**Comment by stephenhawk8054** [comment]
Not sure if I should open a new issue or continue here. This site has 2 ways of dev tools restriction.

URL: `https://phimgii.net/xem-phim/giai-cuu-guy-free-guy-tap-1-server-1/`

The iframe has the structure:
```
https://play.gotphim.com/public/index.html?id=619da5d0095baf9b6aa52f90&subs=&lang=vietnam&ads=https://toolpg.com/demo.xml&v=1638240144&logo=https://phimgii.net/player/dk.jpg&link=https%3A%2F%2Fdk802.com%2F%3FinviteCode%3D34195598%26regAgentJumpFlag%3D0
```

Proposed filter:

`gotphim.com##+js(acis, navigator, devtoolsDetector)`

---------------------

When I switch to `Hydrax` server, there are other scripts for dev tools:

```
https://public.gostream.video/js/devtools-detector/devtools-detector.js
https://public.gostream.video/js/devtools-detector/promise-polyfill.js
```

I'm not sure if it's ok to block it globally. Proposed filter:

`||public.gostream.video/js/devtools-detector/*$script`

Firefox 94.0.2, ublock 1.39.0 default + VIE: ABPVN List
