### ISSUE TITLE
mgtv.com: nuisance

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10644]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.mgtv.com/`

### Category

nuisance

### Describe the issue

When I open the page, a transparent mask layer appears. I can't determine which filter list this is caused by.
This filler is helpful.
```
##.m-agreement-mask
```
Please deal with it. Thanks!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66902050/143773187-11faa155-651a-4a0c-a77e-1ee61c6024a7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 105708
  cosmetic: 101924
  scriptlet: 18961
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1471-0, 1d.1h.41m
    fanboy-annoyance: 58985-150, 2d.3h.58m
    ublock-annoyances: 4311-128, 2d.3h.58m
  default: 
    CHN-0: 26730-86, 2d.3h.58m
    easylist: 61152-11, 2d.3h.58m
    easyprivacy: 26376-43, 1m
    plowe-0: 3699-811, 2d.3h.58m
    ublock-abuse: 74-0, 2d.3h.49m
    ublock-badware: 3451-58, 2d.3h.57m
    ublock-filters: 29635-161, 2d.3h.56m
    ublock-privacy: 189-9, 2m
    ublock-unbreak: 1695-42, 2d.3h.55m
    urlhaus-1: 10468-0, 2m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 514
  launchFromSelfie: true
```
</details>

**Comment by shenzhiming88** [comment]
I found that `fanboy-annoyance` caused this problem.

**Comment by iam-py-test** [comment]
It must be that the cookie banner is only partially blocked 
@ryanbr

**Comment by iam-py-test** [comment]
Opened https://github.com/easylist/easylist/pull/9881
