### ISSUE TITLE
oceanofdownload.com 

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#1065]
URL(s) where the issue occurs

https://www.oceanofdownload.com/
Describe the issue

ADS/pop-ups from random sites
![screenshot_2017-12-21-17-34-46-155_org mozilla firefox](https://user-images.githubusercontent.com/20338483/34256497-8ebdc47c-e64d-11e7-86cc-f22b4df034da.png)

Versions

Browser/version: Firefox for Android 57.0.1 stable
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
Pop-ups are still produced 
Firefox Android 1.14.22

**Comment by mapx-** [comment]
Could you test on desktop too ?

**Comment by ghajini** [comment]
Sorry i don't have access to desktop now😢

**Comment by mapx-** [comment]
hmm I cannot test on android, let's wait @okiehsch if will find something else

**Comment by okiehsch** [comment]
I do not have any mobile devices running android, but I can reproduce with Chrome and Firefox.

`oceanofdownload.com##script:inject(abort-current-inline-script.js, atob, tabunder)`
fixes the issue on my end.

**Comment by ghajini** [comment]
domain dead, can remove filters
