### ISSUE TITLE
yoyofilmeys.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10654]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yoyofilmeys.com/فيلم-ابو-علي-كامل-hd`

### Describe the issue

Clicking _Watch Now_ button on the left leads to a popup.

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Settings

N/A

### Notes

N/A

**Comment by felix-22** [comment]
- the same on `yoyofilmeys.online`: `https://yoyofilmeys.online/فيلم-ابو-علي-كامل-hd`
