### ISSUE TITLE
CC/Subtitle broken on Youtube

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#10659]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

youtube.com

### Describe the issue

this things is weird....
first time i realize it like... some day/week ago
that when i play some video with CC (subtitle) on... and i realize one things....
The font (style) of the subtitle is big....
i mean BIG

my youtube setting... already costum so they will show 50% fontsize...
but everytime i play new video with cc on... the fontsize now turned into 100%

i think first this is problem from youtube itself....
but today... i don't belive if youtube didn't fix it yet... so i turned off all of my extension to see wheter the problem still occur or not.

AND YEAH, when Ublock turned on and then i CTRL + F5... the fontsize of the subtitle turned 100% everytime i load the page...
and when Ublock turned off, the fontsize comeback to 50% like what i setting it before....

Any fix for this issue?
Sorry for my bad english

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

### Notes

(https://www.youtube.com/watch?v=Fz4fAhxzuLE)

**Comment by gorhill** [comment]
Provide an exact URL of a video which you say has CC broken by uBO.

**Comment by Dhanamerdeka** [comment]
> Provide an exact URL of a video which you say has CC broken by uBO.

ah yeah sorry i forget it
https://www.youtube.com/watch?v=Fz4fAhxzuLE

well it's all video on my side.... all video that had CC (without style) they will automatically use 100% fontsize.... even after i setting previous video with another size

**Comment by gorhill** [comment]
Youtube keeps forgetting about the CC font size when logging out/in even without uBO.

**Comment by gorhill** [comment]
Closing as not a uBO issue since this happens without uBO.

**Comment by Dhanamerdeka** [comment]
> Closing as not a uBO issue since this happens without uBO.

wait what?
this appear when using UB
but when UB disabled... the CC works....

usually, after i setting the font size... they will remain same after i reload... exit chrome, etc... but some week ago (or days)
the font didn't load previous setting....

but after ublock disabled... they do....
the font load previous setting

**Comment by gorhill** [comment]
> usually, after i setting the font size... they will remain same after i reload... exit chrome, etc...

They didn't on my side when uBO is disable in `about:extensions` and with no other extension.

**Comment by Dhanamerdeka** [comment]
> They didn't on my side when uBO is disable in `about:extensions` and with no other extension.

wait...
they didn't? you mean the font will change to default 100% or you mean they will read previous setting?

on my side... along time ago until it broke... the font will read previous setting... and i always set it 50% since 100% is too big for my eyes....

but few days ago (or some week) this turned into 100% everytime i change video, reload etc....
after i disable all extension.... the youtube works like before... 
they read previous setting that i made (50%)
but when Ublock enabled... it turned 100%

that's why i report the issue here....
does that correct? 


sorry for my bad english

**Comment by gwarser** [comment]
@Dhanamerdeka font changes to 100% on second reload when uBO is disabled in addon manager.

**Comment by krystian3w** [comment]
I Agree problem is inside page, not in filters, you must wait for fix by @Google / @youtube hands or found `.user.js` solution - I don't recommend change size by CSS if you can't resize property rectangle.
