### ISSUE TITLE
luotphim.net: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10651]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://luotphim.net/xem-phim-bo/deep-insanity-the-lost-child-tap-7/`

### Category

ads

### Describe the issue

There's a video ad playing about 5 seconds on the player before a button to skip ads and go to actual video appears at the bottom right.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/143803338-16059655-9c9b-40e6-9ba8-c2d261ee07b3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80868
  cosmetic: 40480
  scriptlet: 16129
  html: 598
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2094-2, now
  default: 
    ublock-filters: 30252-127, now
    ublock-badware: 3478-1, now
    ublock-privacy: 184-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1709-0, now
    easylist: 61228-482, now
    easyprivacy: 26378-485, now
    urlhaus-1: 10229-0, now
    plowe-0: 3697-3, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 425
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
- it seems the real servers are the last 2
@hoang-rio

**Comment by hoang-rio** [comment]
> - it seems the real servers are the last 2
> @hoang-rio

I not sure to understand what you mean

**Comment by mapx-** [comment]
I mean ZB / HY

![image](https://user-images.githubusercontent.com/10303732/143816096-af639c32-7c59-48a3-ad2d-cbc295e19340.png)

However, the filters @uBlock-user added don't seem fixing anything

**Comment by mapx-** [comment]
same here:
`https://luotphimzz.com/xem-phim-bo/thuong-men-victor-tap-1/`

**Comment by mapx-** [comment]
add directly
`luotphimzz.com##.bigger.fakeplayer`

**Comment by mapx-** [comment]
add also
```
luotphim.cc##.adsphim-popup-center
luotphim.cc##.bigger.fakeplayer
```

**Comment by uBlock-user** [comment]
> added don't seem fixing anything

Don't fix what ?

The ad  video media is loaded through that server.

**Comment by uBlock-user** [comment]
`https://luotphimzz.com/wp-content/uploads/2021/10/sd66.mp4`

That's an ad video, shouldn't have removed my filters @mapx-

**Comment by mapx-** [comment]
- as you can see it's the classic fake video
- your "fix" does not fix anything, still other useless videos / waiting => the real fix is removing the fake stuff

**Comment by uBlock-user** [comment]
Secondly, I don't see any video ads loading when those filters are blocked except for some fakeplayer placeholder, so they're working.

**Comment by uBlock-user** [comment]
> as you can see it's the classic fake video

It's used as an ad video from a third-party server, should be blocked

**Comment by mapx-** [comment]
No, it's not a 3rd party crap, it's a normal page itself.

**Comment by uBlock-user** [comment]
> still other useless videos / waiting => the real fix is removing the fake stuff

That a placeholder and blocking it will confuse some people, so left it that way

> it's VIE stuff the maintainer can add the filters in his list

Sure if that's there it;s going.

**Comment by uBlock-user** [comment]
> No, it's not a 3rd party crap, it's a normal page itself.

https://luotphimzz.com/wp-content/uploads/2021/10/sd66.mp4 is third-party ad-video, nothing "normal" about it.

**Comment by hoang-rio** [comment]
I can by pass this video ads by normal way so I use my user script to by pass this: https://greasyfork.org/vi/scripts/9099-abpvn-adsblock

**Comment by mapx-** [comment]
You don't need it if you add the fake filters

**Comment by uBlock-user** [comment]
We do block video-ads regardless of whether they need uBO syntax or not.

**Comment by uBlock-user** [comment]
@mapx- Connection request to https://luotphimzz.com/wp-content/uploads/2021/10/sd66.mp4 still occurs @mapx-

**Comment by uBlock-user** [comment]
@mapx- Connection request to https://luotphimzz.com/wp-content/uploads/2021/10/sd66.mp4 still occurs

**Comment by mapx-** [comment]
@uBlock-user you cannot distinguish between legit and ad videos. You blocked whatever video from that page.
Let's stop this spam discussion.

**Comment by uBlock-user** [comment]
> you cannot distinguish between legit and ad videos. 

How so ? That video is absolutely spam, if you think it is not, justify why it is not.

**Comment by mapx-** [comment]
Still still still: the difference between THAT and ALL

**Comment by uBlock-user** [comment]
Also `https://luotphimzz.com` is used on to deliver ad-banners on `luotphim.net` incase you didn't notice yet.

**Comment by uBlock-user** [comment]
> ALL

Still -- show evidence of any legit videos.

**Comment by mapx-** [comment]
VIE already blocked any such ad video, so you should correctly test a page.

**Comment by uBlock-user** [comment]
`https://luotphimzz.com/wp-content/uploads/2021/10/sd66.mp4` is not blocked and I still see it load and appear.

**Comment by hoang-rio** [comment]
@mapx- @uBlock-user About domain `luotphimzz.com` i can comfirm this domain only serve video ads. Most of no copyright film site use third-party video player to save their bandwith. I will add `||luotphimzz.com/wp-content/uploads/$media` to **ABPVN List** like the way i add `||luotphim.cc/wp-content/uploads/$media` to block ads video on this site

**Comment by felix-22** [comment]
@hoang-rio, there is some overlay left on `luotphim.vip` which makes the whole site unaccessible, can be fixed by `luotphim.vip##.adsphim-popup-center:`



<details>
<summary>screenshoot</summary>

![uuu](https://user-images.githubusercontent.com/75935068/143850647-1bf539c4-8335-464e-b3d2-e91fbb1918be.png)

</details>

**Comment by hoang-rio** [comment]
This site use multiple domain. I will add this rule to ABPVN List
