### ISSUE TITLE
truyenfull.vn: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10652]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://truyenfull.vn/`

### Category

ads

### Describe the issue

After the page finishes loading, scroll down to the bottom for the ads resources to load.

In the page, there are some ads images with the URL matches `.net/ads/` (they are already hidden by generic cosmetic filters from EasyList but we can see the resources not blocked in the logger). However, when another regional filter list has the filter `.net/ads/`, it cannot block these URLs due to `.net/ads/$badfilter` in `Unbreak` filter list.

That filter is added due to this problem in Nano repo:
`https://github.com/NanoMeow/QuickReports/issues/4172`
to solve the anti-adblock in this site:
`https://www.kentonline.co.uk/whitstable/news/experts-stunned-by-weather-phenomenon-over-kent-228963/`

However, when I checked that `kentonline.co.uk` links (as well as other links from that website), it no longer has `.net/ads/` URLs, so I wonder if this `badfilter` is obsolete or not.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/143805304-5a6cd093-22e1-4d41-8611-f9c3770b1785.png)

![image](https://user-images.githubusercontent.com/66517106/143805596-ed97ce9a-8ff3-446e-8e56-3a732df92b24.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80018
  cosmetic: 39312
  scriptlet: 16104
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30252-27, 13m
    ublock-badware: 3478-1, 13m
    ublock-privacy: 184-0, 13m
    ublock-abuse: 74-0, 13m
    ublock-unbreak: 1709-0, 13m
    easylist: 61228-545, 13m
    easyprivacy: 26378-474, 13m
    urlhaus-1: 10229-0, 13m
    plowe-0: 3697-3, 13m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 425
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
already fixed in the regional list

![image](https://user-images.githubusercontent.com/10303732/143815718-7a9d67e8-86c5-4a66-ba6f-cc48cbdf02c7.png)

**Comment by stephenhawk8054** [comment]
Yeah, I reported the domain `iads.staticscdn.net` so it's already fixed. It's just I'm wondering about the filter `.net/ads/$badfilter` as would it be needed any more? Since I'm afraid it might get conflicts with the filter `.net/ads/` in ABPVN and looks like the site `kentonline.co.uk` doesn't need that `badfilter` anymore. Or are there any cases similar to that issue?

**Comment by mapx-** [comment]
`.net/ads/` is a classic bait

if some specific page => the list will add a domain-specific `.net/ads/` filter

**Comment by stephenhawk8054** [comment]
I see, tks for the info.
