### ISSUE TITLE
manga4life.com: nuisance

### ISSUE THREAD

**Issue by TeaAndCupcakes** [uBlockOrigin/uAssets#10667]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://manga4life.com/manga/Shingeki-No-Kyojin`

### Category

nuisance

### Describe the issue

can't read the manga or subscribe to it. Used to work before. Now only works when i turn off uBO. This is the same with all the manga on manga4life
![image](https://user-images.githubusercontent.com/95249688/143934688-9fbd5b72-c287-4c36-bc93-40057c1ded4f.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80315
  cosmetic: 39319
  scriptlet: 16113
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30279-27, now
    ublock-badware: 3495-1, now
    ublock-privacy: 183-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1707-0, now
    easylist: 61277-164, now
    easyprivacy: 26387-45, now
    urlhaus-1: 10443-0, 20h.20m
    plowe-0: 3697-813, 1d.2h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 739
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
Page renders fine here. Maybe caused by another extension or modified browser settings?

**Comment by Alphamen16** [comment]
I can help here. @TeaAndCupcakes the issue is probably !jsdelivr.map.fastly.net! which you need to allow in order for it to work.

Using the allow rule is generally a bad principle but in this case if you use the noop function, it still doesn't work.

**Comment by u-RraaLL** [comment]
*$script,3p,denyallow=cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com|hcaptcha.com|jsdelivr.net|recaptcha.net,domain=manga4life.com

Breaks it.

**Comment by Alphamen16** [comment]
> ```
> *$script,3p,denyallow=cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com|hcaptcha.com|jsdelivr.net|recaptcha.net,domain=manga4life.com
> ```
> 
> Breaks it.


A few days ago i had the issue the OP is describing, but i just went to the website and the allow rule i created is no longer necessary. Site is loading just fine now. Weird?

**Comment by uBlock-user** [comment]
Do a cache free reload of the site and the breakage should return.

**Comment by Alphamen16** [comment]
> Do a cache free reload of the site and the breakage should return.

Yeah that's probably it. Anyway thanks for the fix :)

**Comment by gorhill** [comment]
> the issue is probably "jsdelivr.map.fastly.net"

On my side the script is fetched from `https://cdn.jsdelivr.net.cdn.cloudflare.net/`, hence why I couldn't reproduce.
