### ISSUE TITLE
YouTube is no longer blocking ads before a video

### ISSUE THREAD

**Issue by DevWannabe-dot** [uBlockOrigin/uAssets#10666]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

YouTube is no longer blocking video ads

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=mgK6B_o4Z64

### Steps to Reproduce

1. Browse and open a video (preferrably from search or new tab)

### Expected behavior

You are vulnerable to getting an advertisement, even if not always.

### Actual behavior

I got a stupid advertisement with an Adblocker enable, this feels so stupid

### uBlock Origin version

uBlock Origin 1.39.0

### Browser name and version

Mozilla Firefox 94.0.2 (64-bit)

### Operating System and version

Microsoft Windows 10 Pro version 21H1

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gwarser** [comment]
@DevWannabe-dot not a bot. Duplicate because it says _ALL_ youtube issues and has ~500 comments about different issues.

**Comment by DevWannabe-dot** [comment]
Smart method. If I face the issue any father ll go there, thanks to both of u!

**Comment by gorhill** [comment]
Also, you have other extensions enabled in there, you should disable them all and try Youtube with only uBO (force a reload of Youtube once you disable other extensions) -- other extensions can interfere negatively with uBO.

**Comment by gorhill** [comment]
> Anti-Adblock Killer

This has been unmaintained for years, better remove this -- the corresponding AAK list is blacklisted in uBO because people erroneously think it does something why due to its unmaintained status it just creates issues. uBO needs to inject custom scriptlets in Youtube pages and Tampermonkey user scripts can interfere negatively.

**Comment by iam-py-test** [comment]
> @mapx- I don't know if it's pointless to say that because you might be a bot, but this is not a duplicate of the issue you mentioned. The subject had an issue with playback, while in my case the ads are being shown normally

@mapx- is not a bot, their a person.
> Smart method. If I face the issue any father ll go there, thanks to both of u!

Please check for other issues _before_ opening a new one. A simple search for _youtube.com_ brings up that issue, or just looking at the current open issues. This would save both you and us a lot of time. It is even listed in the template (which you checked):
>  I performed a cursory search of the issue tracker to avoid opening a duplicate issue

Please read over the template as well before checking the boxes

> Anti-Adblock Killer

uBlock Origin already disables Anti-Adblock, no need for an unmaintained userscript

Speaking of bots, maybe what uAssets/uBlock-issues needs is a bot, which can auto-classify issues (i.e. mark issues in uBlock-issues which clearly are filterlist issues as such)

**Comment by DevWannabe-dot** [comment]
Alright, thanks everyone for the heads up and sorry for the confusion, I'll be watching some Rick Rubin videos and will report if any ad sneaks over
