### ISSUE TITLE
Incorrect blocking of Live365

### ISSUE THREAD

**Issue by TheKigen** [uBlockOrigin/uAssets#10661]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://live365.com`

### Describe the issue

The annoyances list incorrectly includes:
```
! https://forums.lanik.us/viewtopic.php?f=62&t=41150
||api.live365.com/geocheck
```

By blocking this it prevents the user from being able to listen to Live365 audio streams.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Settings

- Select uBlock Origin Annoyances list.

### Notes

Disclosure: I work for Live365.  But this is something I am submitting on my own time since I use uBlock Origin.

The geocheck that is being blocked is to ensure that Live365 is licensed by the performance right organizations in the country the listener is located before allowing them to listen to the stream.  By blocking the geocheck, the audio player assumes they are not in a licensed country.

This block is at:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L291

**Comment by felix-22** [comment]
Also big ad placeholders `https://live365.com/listen` :

![yyyy](https://user-images.githubusercontent.com/75935068/143897625-b5aa7dca-090f-4d4d-b6ef-79d8edf8aac3.png)

**Comment by felix-22** [comment]
Also big ad placeholders `https://live365.com/listen` : @ryanbr

<details>
<summary>screenshoot</summary>

![yyyy](https://user-images.githubusercontent.com/75935068/143897625-b5aa7dca-090f-4d4d-b6ef-79d8edf8aac3.png)

</details>
