### ISSUE TITLE
cw.com.tw: breakage

### ISSUE THREAD

**Issue by dkaoster** [uBlockOrigin/uAssets#10672]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.cw.com.tw/`

### Category

breakage

### Describe the issue

uBlock Origin removes the entire homepage content for Commonwealth Magazine (天下雜誌), one of the top finance magazines in Taiwan.

Specifically, it looks like there is an article tag by `<article class="adActive">` that causes everything within that tag to be hidden, when the class only seems to be specifying that advertisements are active on the page.

Thank you for the support!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2021-11-30 at 9 58 52 PM" src="https://user-images.githubusercontent.com/3477162/144061338-63fd58b2-15c0-48c9-9230-b10ebbce0d67.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80173
  cosmetic: 39260
  scriptlet: 16071
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30189-27, 3d.9h.11m
    ublock-badware: 3465-1, 3d.9h.8m
    ublock-privacy: 183-0, 3d.9h.21m
    ublock-abuse: 74-0, 3d.9h.19m
    ublock-unbreak: 1707-0, 3d.9h.17m
    easylist: 61173-544, 3d.9h.15m
    easyprivacy: 26342-473, 3d.9h.13m
    urlhaus-1: 10468-0, 21h.45m
    plowe-0: 3695-3, 3d.9h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2237
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
The problematic filter is `##.adActive` from EasyList.

cc @ryanbr

**Comment by uBlock-user** [comment]
Fix is present in AdGuard Chinese.
