### ISSUE TITLE
m.iqiyi.com: detection

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10674]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://m.iqiyi.com/v_qb5dpogj0o.html`

### Category

detection

### Describe the issue

When using uBO on the phone, the video does not play and prompts to turn off the ad blocking plugin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_20211130_231442](https://user-images.githubusercontent.com/66902050/144075555-713d5250-a145-4687-b904-6d6b63981994.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 68
filterset (summary): 
  network: 106308
  cosmetic: 52607
  scriptlet: 18984
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1488-0, 2m
    fanboy-annoyance: 58992-30456, 2d.23h.49m
    ublock-annoyances: 4339-8, 22h.29m
  default: 
    ublock-filters: 30241-213, 22h.23m
    ublock-badware: 3440-2, 22h.20m
    ublock-privacy: 185-1, 2d.6h.4m
    ublock-abuse: 74-0, 2d.23h.52m
    ublock-unbreak: 1706-0, 3d.11h.59m
    adguard-mobile: 7009-172, 22h.27m
    easylist: 61173-24036, 3d.11h.57m
    easyprivacy: 26372-480, 2d.7h.51m
    urlhaus-1: 9592-0, 22h.17m
    plowe-0: 3690-3, 11d.23h.35m
    CHN-0: 26806-1079, 22h.25m
filterset (user): [empty]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: 
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3732
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/144143082-6f3e3716-c682-49cb-90fa-3bcc822867bb.png)

**Comment by gorhill** [comment]
I get same result as @mapx-.

**Comment by uBlock-user** [comment]
I used Chinese VPN and the site tells me to watch the video on their site app.

**Comment by JobcenterTycoon** [comment]
I get a error to. I tried another video but can play it without anti adblock warning

**Comment by gorhill** [comment]
I see OP is using an obsolete version of Firefox for Android -- should try with a more recent version.

**Comment by shenzhiming88** [comment]
> I get a error too.

If uBO is turned off, will the video still play properly? I use mobile view on my computer and I don't find ads; but it still doesn't play on my phone, and I am able to play it normally after turning off uBO.

> I see OP is using an obsolete version of Firefox for Android -- should try with a more recent version.

Yes, maybe I need to update it.

**Comment by shenzhiming88** [comment]
@gorhill @Yuki2718 
After the update, I still get the same results. I think you may need to use a VPN for mainland China, not Hong Kong, Macau or Taiwan. this site offers different content in different regions.
![Screenshot_2021-12-04-01-37-33-769_org mozilla firefox](https://user-images.githubusercontent.com/66902050/144648032-112f9883-1b2a-4850-8e34-8c4407a8d94a.jpg)

**Comment by Yuki2718** [comment]
> After the update, I still get the same results. I think you may need to use a VPN for mainland China, not Hong Kong, Macau or Taiwan. this site offers different content in different regions.

Are you sure `t7z.cupid.iqiyi.com` is not blocked on all layers on your network? It's allowed only on Mobile filters so e.g. AGDNS still blocks it. If not, post SS of the logger please.

**Comment by shenzhiming88** [comment]
> > After the update, I still get the same results. I think you may need to use a VPN for mainland China, not Hong Kong, Macau or Taiwan. this site offers different content in different regions.
> 
> Are you sure `t7z.cupid.iqiyi.com` is not blocked on all layers on your network? It's allowed only on Mobile filters so e.g. AGDNS still blocks it. If not, post SS of the logger please.

I'll try it again tomorrow on my computer.
For some reason, even though I turned off the ad filter, used the mobile network, and was able to access that domain properly, the video still wouldn't play.
