### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by YaSillyGit** [uBlockOrigin/uAssets#10678]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.amazon.com/s?i=digital-text&rh=n%3A133140011%2Cp_27%3Acharles+river+editors&s=price-asc-rank&language=en_US&linkCode=sl2&linkId=ae443cedd5a34eaa29dbc33667a8b20b&qid=1554747426&tag=charlesrivermain-20&unfiltered=1&ref=nav_custrec_signin`

### Category

ads

### Describe the issue

Tall sponsored ads appear as frames at the left of search results. I have tried to pick and zap and have added items to my block list, but they still appear. I then deleted all items from my My Filters and refreshed the page. One ad disappeared, but another showed up farther down the page. Since I'm no good at this, will you tell me how to block them, please?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 152744
  cosmetic: 107383
  scriptlet: 32013
  html: 606
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-136, 23h.51m
    https://www.fanboy.co.nz/enhancedstats.txt: 2993-44, 3d.12h.53m
    adguard-generic: 61695-4826, 3d.12h.54m
    adguard-spyware: 25161-1144, 3d.12h.54m
    adguard-annoyance: 47876-3584, 3d.12h.54m
    fanboy-annoyance: 58984-37979, 3d.12h.54m
    fanboy-cookiemonster: 20418-12904, 3d.12h.54m
    ublock-annoyances: 4324-15, 3d.12h.54m
    dpollock-0: 16967-1959, 3d.12h.54m
    mvps-0: 8730-468, 3d.12h.53m
  default: 
    ublock-filters: 30229-215, 3d.12h.54m
    ublock-badware: 3472-6, 3d.12h.54m
    ublock-privacy: 183-1, 3d.12h.54m
    ublock-abuse: 74-0, 3d.12h.54m
    ublock-unbreak: 1709-1, 3d.12h.54m
    easylist: 61173-23543, 3d.12h.54m
    easyprivacy: 26342-11212, 3d.12h.54m
    urlhaus-1: 10040-0, 23h.49m
    plowe-0: 3695-377, 3d.12h.53m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  collapseBlocked: false
  firewallPaneMinimized: false
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6619
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
You checked _"Ignore generic cosmetic filters"_, this is not supposed to be checked on desktop version of Firefox.

**Comment by YaSillyGit** [comment]
Thank you!
I had it checked because the info pop up says to enable it for less powerful devices as it reduces CPU and memory usage. Perhaps the Firefox warning should be included in the pop up?

**Comment by gorhill** [comment]
> the info pop up says to enable it for less powerful devices as it reduces CPU and memory usage

Of course at the cost of losing generic cosmetic filtering. If you disable generic cosmetic filtering, then it's not for the list maintainers to fix the consequences of such customization, this becomes a support issue in which case you should ask for support at <https://www.reddit.com/r/uBlockOrigin/>, no here since this won't be fixed in filter lists.
