### ISSUE TITLE
http://www.comando-filmes.org/

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#1067]
http://www.comando-filmes.org/
this site have a anti-adblock script, there's some way to remove it?

**Comment by gorhill** [comment]
Does this work?

    @@||comando-filmes.org^$generichide

**Comment by mapx-** [comment]
still anti adblock

try
```
@@||comando-filmes.org^$generichide
comando-filmes.org##body:style(background: none !important)
comando-filmes.org##script:inject(abort-current-inline-script.js, window.document.getElementById)
comando-filmes.org##[id^=bsa]
||goo.gl/$subdocument,domain=comando-filmes.org
comando-filmes.org###floatLayer2
comando-filmes.org##a[href^="https://goo.gl/"]
```

**Comment by xqk94524** [comment]
not yet, do you have any documents that I can study to be able to collaborate?

**Comment by mapx-** [comment]
Did you test last filters ?

browser ? (version)
uBo version ?

**Comment by xqk94524** [comment]
yes works, but also breaks the page

Firefox 57.0.2
Ublock Origin 1.14.22

**Comment by xqk94524** [comment]
`comando-filmes.org##body:style(background: none !important)`
this line isn't necessary.

I can't scroll the page

**Comment by mapx-** [comment]
add also
`.cf^$third-party`

**Comment by mapx-** [comment]
@okiehsch 

`.cf^$third-party,websocket`  does not work (perhaps it works only for websockets)
`.cf^$third-party` is working for the site above

**Comment by xqk94524** [comment]
` .cf^$third-party`
yes, it works perfectly
thanks, Ublock Origin is the best!

**Comment by gorhill** [comment]
For me just these work (scrolling fixed):

    @@||comando-filmes.org^$generichide
    comando-filmes.org##.check
    comando-filmes.org##body:style(background: none !important; overflow: auto !important;)

**Comment by mapx-** [comment]
@gorhill, is the .cf script blocked for you ?

**Comment by xqk94524** [comment]
`@@||comando-filmes.org^$generichide
comando-filmes.org##.check
comando-filmes.org##body:style(overflow: auto !important;)
`
works

the background is part of the site, yes I know is horrible, but is part

**Comment by xqk94524** [comment]
`@@||comando-filmes.org^$generichide
comando-filmes.org##.check
comando-filmes.org##body:style(overflow: auto !important;)
||goo.gl/$subdocument,domain=comando-filmes.org`

this is enough

**Comment by gorhill** [comment]
> is the .cf script blocked for you ?

No. The filter `.cf^$third-party,websocket` means only 3rd-party websocket requests will be blocked.

When I implemented this, I am pretty sure it aligned with ABP's implementation. I will have to dig through ABP's commit log to find out whether they changed the semantic of I understood wrong the first time.

**Comment by okiehsch** [comment]
`.cf^$third-party` will block **all** requests from the whole top level domain, so that is a bad idea.

````
@@||comando-filmes.org^$generichide
||comandofilmes.cf^$script,domain=comando-filmes.org
||goo.gl/$subdocument,domain=comando-filmes.org
comando-filmes.org##.check
comando-filmes.org##body:style(background: none !important; overflow: auto !important;)
````

**Comment by mapx-** [comment]
`comando-filmes.org##a[href^="https://goo.gl/"]` too to remove the fake buttons on the page

Weird thing is your filters (gorhill/ okiehch) are working only in chrome for me

**Comment by gorhill** [comment]
@mapx- By the way, avoid prefixing with `window`:

    comando-filmes.org##script:inject(abort-current-inline-script.js, window.document.getElementById)

`window` is always implicit, this means uBO will look for a property `window.window.document.getElementById` with filter above.

**Comment by mapx-** [comment]
hmm, I see in the logger (firefox)
`Static filter comando-filmes.org##script:inject(abort-current-inline-script.js, window.document.getElementById)`

**Comment by gorhill** [comment]
Need this with Firefox:

    ||imgur.com^$image,redirect=2x2-transparent.png,domain=comando-filmes.org

**Comment by gorhill** [comment]
>  I see in the logger (firefox)

Yes, the scriptlet is injected, but it will fail when it execute after being injected.

**Comment by mapx-** [comment]
weird, so what I see in the logger (for the injected filters) is not the real execution

**Comment by gorhill** [comment]
There is no way for uBO to know whether the execution does what it's supposed to do or not. It just injects the scriptlet as told to.

**Comment by mapx-** [comment]
these are working in FF / chrome
```
@@||comando-filmes.org^$generichide
||comandofilmes.cf^$script,domain=comando-filmes.org
||goo.gl/$subdocument,domain=comando-filmes.org
comando-filmes.org##.check
comando-filmes.org##body:style(background: none !important; overflow: auto !important;)
@@.jpg#$image,domain=comando-filmes.org
comando-filmes.org##a[href^="https://goo.gl/"]
```

**Comment by okiehsch** [comment]
I need a different filter with Firefox.

`@@||comando-filmes.org/wp-content/*/Utorrent.jpg$image,first-party`

**Comment by mapx-** [comment]
it's the classic anti adb `generichide + .gif# or .png# or .jpg#`
