### ISSUE TITLE
canarias7.es: detection

### ISSUE THREAD

**Issue by timonoj** [uBlockOrigin/uAssets#10683]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.canarias7.es/opinion/morgan/humor-morgan-miercoles-20211201000900-nt.html`

### Category

detection

### Describe the issue

Page detects an adblocker and prompts to disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/10449143/144215553-53fedb62-c124-467d-99cb-d4cb6d2d0a41.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 84177
  cosmetic: 39576
  scriptlet: 35230
  html: 599
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 26935-25, 20h.8m
  default: 
    ublock-filters: 30228-3239, 3d.20h.5m
    ublock-badware: 3455-1, 3d.20h.3m
    ublock-privacy: 183-0, 3d.20h.1m
    ublock-abuse: 74-0, 3d.19h.59m
    ublock-unbreak: 1709-0, 3d.19h.57m
    easylist: 61192-551, 3d.19h.55m
    easyprivacy: 26369-472, 3d.19h.53m
    urlhaus-1: 10185-0, 20h.6m
    plowe-0: 3689-3, 10d.5h.42m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1508
  launchFromSelfie: true
```
</details>

**Comment by okiehsch** [comment]
Fixed in the regional list.
![image](https://user-images.githubusercontent.com/16838044/144219800-3642ef7c-5309-4aa0-8121-9fcf21d251e4.png)
