### ISSUE TITLE
marketscreener.com: nuisance

### ISSUE THREAD

**Issue by MichaelUray** [uBlockOrigin/uAssets#10682]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.marketscreener.com/quote/stock/ALIBABA-GROUP-HOLDING-LIM-17916677/financials/`

### Category

nuisance

### Describe the issue

It overlaps the website content with advertisements and it tries to force you to register or login when you spend some time on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2021-12-01_08-58-36](https://user-images.githubusercontent.com/25169478/144194956-4dfd4738-1a84-4d42-b33e-272365bce09e.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 79746
  cosmetic: 39329
  scriptlet: 16108
  html: 598
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30260-28, 1d.4h.59m
    ublock-badware: 3472-1, 3d.18h.27m
    ublock-privacy: 183-0, 3d.18h.33m
    ublock-abuse: 74-0, 3d.18h.35m
    ublock-unbreak: 1709-0, 3d.18h.29m
    easylist: 61278-545, 1d.9h.1m
    easyprivacy: 26369-472, 3d.18h.31m
    plowe-0: 3695-3, 4d.16h.30m
    urlhaus-1: 9915-0, 11h.44m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 41 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 198
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
See if enabling AdGuard Annoyances help. You need to enable Annoyances list to get rid of such nuisances.

**Comment by MichaelUray** [comment]
I tried it with these 3 annoyances filter, but it did not help.
- AdGuard Annoyances
- Fanboy’s Annoyance
- uBlock filters – Annoyances

**Comment by gorhill** [comment]
I haven't been able to reproduce with default lists.Does this work?

    marketscreener.com##[id^="dPub"]

**Comment by gorhill** [comment]
Does this work?

    marketscreener.com##[id^="dPub"]
