### ISSUE TITLE
[nsfw] xvedios.info: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#10688]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://xvedios.info/fucked-realtor-s-mouth-and-doggystyle-with-big-tits-52801867.html#`

### Category

popups

### Describe the issue

popup tabs everytime when clicked on videos

when clicked back in browser, redirects to ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 81361
  cosmetic: 44681
  scriptlet: 16222
  html: 613
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30398-129, 10h.8m
    ublock-badware: 3494-9, 10h.8m
    ublock-privacy: 183-0, 10h.8m
    ublock-abuse: 74-0, 10h.8m
    ublock-unbreak: 1714-0, 10h.8m
    adguard-mobile: 7013-156, 10h.8m
    easylist: 61320-703, 10h.8m
    easyprivacy: 26397-481, 10h.8m
    urlhaus-1: 9870-0, 10h.8m
    plowe-0: 3697-3, 10h.8m
filterset (user): [array of 272 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 424
  launchFromSelfie: true
```
</details>

**Comment by JobcenterTycoon** [comment]
There is FingerprintJS tracking too

**Comment by ghajini** [comment]
yes

**Comment by mapx-** [comment]
test

```
xvedios.info##+js(ra, onclick, [onclick*="open"])
xvedios.info##+js(set, history.pushState, noopFunc)
xvedios.info##+js(aopw, onpopstate)
```

**Comment by ghajini** [comment]
still when clicked back there is this
![Screenshot_20211202-010549-290](https://user-images.githubusercontent.com/20338483/144301923-dd70ce3e-58d1-49d5-a536-30a781f965cf.png)

**Comment by mapx-** [comment]
`xvedios.info##^script:has-text(onpopstate)`

**Comment by JobcenterTycoon** [comment]
Works for me
