### ISSUE TITLE
https://noticias.gospelmais.com.br/

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#1068]
`https://noticias.gospelmais.com.br/`
submit this rules, for prevent anti-adblock
`noticias.gospelmais.com.br##.blocker-overlay`
`noticias.gospelmais.com.br##.blocker-notice`

**Comment by SMed79** [comment]
`||gospelmais.com.br/wp-content/themes/*/js/customscript.js`
