### ISSUE TITLE
online.jimmyjohns.com: breakage

### ISSUE THREAD

**Issue by dianacoz** [uBlockOrigin/uAssets#10689]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://online.jimmyjohns.com/login`

### Category

breakage

### Describe the issue

Whenever I go to check out, I have to go through a test to prove I'm not a robot.  The site told me that it was likely the result of an ad-blocker or cookie tracker in use on the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/95365507/144260905-9c3e9560-b9ef-4142-92fb-f59da629f88b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 80095
  cosmetic: 39328
  scriptlet: 16119
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30298-28, 21h.18m
    ublock-badware: 3494-1, 21h.16m
    ublock-privacy: 182-0, 21h.29m
    ublock-abuse: 74-0, 21h.27m
    ublock-unbreak: 1707-0, 21h.25m
    easylist: 61304-546, 21h.23m
    easyprivacy: 26396-473, 21h.21m
    urlhaus-1: 10185-0, 1d.1h.36m
    plowe-0: 3697-3, 2d.2h.23m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2224
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
It's [PerimeterX crap](https://github.com/uBlockOrigin/uAssets/issues/6558)

@ryanbr
