### ISSUE TITLE
Chinese `360` "Private" Search Engine: `Wuzhuiso`

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#10690]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.wuzhuiso.com/?src=v2ex`
`https://www.wuzhuiso.com/help/policy.html?src=v2ex`
`https://www.wuzhuiso.com/s?q=test&a=image&src=tab_www&fr=none`

### Describe the issue

tracking parameters

```
||wuzhuiso.com^$queryprune=src
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/75058881/144289911-c6672899-d6ef-48b1-8913-31b78677437f.png)

![image](https://user-images.githubusercontent.com/75058881/144290411-2c12e8ef-df7f-48c6-bbd7-3cdf39524632.png)

### uBlock Origin version

n/a

### Browser name and version

n/a

### Settings

n/a

**Comment by c2xusnpq6** [comment]
https://github.com/easylist/easylist/issues/9913

**Comment by c2xusnpq6** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/101790

**Comment by c2xusnpq6** [comment]
```
||improving.wuzhuiso.com^
/sou/home.gif
```

![image](https://user-images.githubusercontent.com/75058881/144292290-3d76588a-e5ee-49bb-9669-81c2d151e911.png)

**Comment by iam-py-test** [comment]
uBlock Origin's default filters do not address tracking params. However, there is a list that does: https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt

**Comment by uBlock-user** [comment]
```
||improving.wuzhuiso.com^
/sou/home.gif
```

Are you suggesting to add these ?

**Comment by c2xusnpq6** [comment]
> ```
> ||improving.wuzhuiso.com^
> /sou/home.gif
> ```
> 
> Are you suggesting to add these ?
> 
> --
> 
> `improving.wuzhuiso.com` is blocked by EP and the second one never appears.

https://www.wuzhuiso.com/s?ie=utf-8&fr=none&q=test
https://www.wuzhuiso.com/s?ie=utf-8&fr=none&q=ip
https://www.wuzhuiso.com/s?ie=utf-8&fr=none&q=testing

**Comment by c2xusnpq6** [comment]
> Are you suggesting to add these ?

Yes.

```
||improving.wuzhuiso.com^
||wuzhuiso.com^$queryprune=src
```
