### ISSUE TITLE
themoviesboss.org: detection

### ISSUE THREAD

**Issue by fuzzyfox123** [uBlockOrigin/uAssets#10699]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://themoviesboss.org/`

### Category

detection

### Describe the issue

the site detects uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.postimg.cc/ZnVKXYgw/Screenshot-2021-12-02-20-46-45-39-9c7ad408470e52983cc8816adf9ff347.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 168312
  cosmetic: 178751
  scriptlet: 32097
  html: 610
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61939-4549, now
    adguard-spyware: 25298-1096, now
    adguard-spyware-url: 394-1, now
    block-lan: 44-0, now
    curben-phishing: 23091-5, now
    curben-pup: 372-0, now
    adguard-annoyance: 48063-4156, now
    adguard-social: 14791-18, now
    fanboy-thirdparty_social: 69-0, now
    fanboy-annoyance: 59043-43841, now
    fanboy-cookiemonster: 20442-120, now
    fanboy-social: 23216-1080, now
    ublock-annoyances: 4347-4, now
    dpollock-0: 16978-1775, now
    mvps-0: 8730-377, now
  default: 
    ublock-filters: 30436-62, now
    ublock-badware: 3512-1, now
    ublock-privacy: 187-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1716-0, now
    adguard-mobile: 7016-190, now
    easylist: 61360-952, now
    easyprivacy: 26407-11244, now
    urlhaus-1: 8190-0, now
    plowe-0: 3700-3, now
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  autoUpdate: false
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  uiTheme: dark
supportStats: 
  launchToReadiness: 15732
  launchFromSelfie: false
```
</details>

**Comment by gorhill** [comment]
There is a long delay before the detection is triggered, this seems to work if you can confirm:

    @@||themoviesboss.org^$ghide

**Comment by fuzzyfox123** [comment]
> There is a long delay before the detection is triggered, this seems to work if you can confirm:
> 
> ```
> @@||themoviesboss.org^$ghide
> ```

yeah, it works.
