### ISSUE TITLE
ansa.it: nuisance

### ISSUE THREAD

**Issue by Lascax** [uBlockOrigin/uAssets#10696]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.ansa.it/sito/notizie/tecnologia/internet_social/2021/12/01/facebook-rimuove-rete-no-vax-in-italiamolestie-e-squadrismo_9ad14979-1e9b-4b38-9f40-583724495b5f.html`

### Category

nuisance

### Describe the issue

<https://i.imgur.com/rqdGCu6.png>

As seen on the screenshot at the link, there is an overlay to the news article that obscures it.
It looks like the website allows only 30 articles per 30 days period, then the overlay gets on it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 85328
  cosmetic: 46271
  scriptlet: 16112
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30270-27, 1d.23h.19m
    ublock-badware: 3495-1, 1d.23h.17m
    ublock-privacy: 183-0, 1d.23h.15m
    ublock-abuse: 74-0, 1d.23h.13m
    ublock-unbreak: 1707-0, 1d.23h.11m
    easylist: 61300-549, 1d.23h.8m
    easyprivacy: 26396-476, 1d.23h.6m
    urlhaus-1: 9870-0, 12h.30m
    plowe-0: 3697-3, 4d.15h.12m
    ITA-0: 12526-6, 12h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1202
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
paywall, we didn't block it
