### ISSUE TITLE
thethaiger.com: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#10695]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://thethaiger.com/`

### Category

ads

### Describe the issue

Ad banner at the top of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 142104
  cosmetic: 148196
  scriptlet: 31921
  html: 607
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1494-0, 18h.53m
    https://www.i-dont-care-about-cookies.eu/abp/: 24119-3, 20h.3m
    adguard-generic: 61695-4452, 4d.4h.37m
    adguard-spyware: 25302-759, 18h.43m
    adguard-spyware-url: 394-67, 18h.53m
    block-lan: 44-0, 18h.43m
    adguard-annoyance: 47880-2881, 3d.23h.19m
    adguard-social: 14739-13, 3d.23h.19m
    ublock-annoyances: 4325-6, 3d.23h.19m
    NOR-0: 2580-4, 14h.37m
    curben-phishing: 23134-4, 18h.43m
    curben-pup: 373-0, 18h.43m
  default: 
    ublock-filters: 30229-37, 4d.4h.47m
    ublock-badware: 3472-1, 4d.4h.45m
    ublock-privacy: 183-0, 4d.4h.43m
    ublock-abuse: 74-0, 4d.4h.41m
    ublock-unbreak: 1709-0, 4d.4h.39m
    easylist: 61199-584, 4d.4h.35m
    easyprivacy: 26372-11068, 4d.4h.33m
    urlhaus-1: 9870-4, 14h.39m
    plowe-0: 3697-3, 3d.7h.13m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1882
  launchFromSelfie: false
```
</details>

**Comment by okiehsch** [comment]
You mean the Covid-19 insurance banner?

**Comment by gorhill** [comment]
This is for [EasyList Thailand](https://github.com/easylist-thailand/easylist-thailand) -- the banner also appear in the Thai version of the site. cc @gluons

**Comment by okiehsch** [comment]
Looks like self advertisment in any case.
![image](https://user-images.githubusercontent.com/16838044/144427446-b45c6be1-3a26-430d-8f82-15ddc6c87d07.png)
