### ISSUE TITLE
blacklibrary.com: breakage

### ISSUE THREAD

**Issue by sudonikgr** [uBlockOrigin/uAssets#10693]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.blacklibrary.com/`

### Category

breakage

### Describe the issue

It looks like everything is darkened and nothing is clickable. It's because of a front-row cookie notice (with an 'accept' button) that disables everything in the back but it's also hidden by uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![BL](https://user-images.githubusercontent.com/46679913/144405178-f2ce2d76-6a9a-49a5-9de1-6e29a091ecc5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 110852
  cosmetic: 92742
  scriptlet: 18870
  html: 606
listset (total-discarded, last updated): 
  added: 
    block-lan: 44-0, 58m
    fanboy-annoyance: 59032-174, 1d.19h.6m
    fanboy-cookiemonster: 20441-20435, never
    ublock-annoyances: 4328-129, 49m
    dpollock-0: 16978-416, 50m
    mvps-0: 8730-1739, 52m
    GRC-0: 1002-7, 18h.14m
  default: 
    ublock-filters: 30246-27, 3d.18h.59m
    ublock-badware: 3472-1, 3d.18h.57m
    ublock-privacy: 185-0, 3d.18h.55m
    ublock-abuse: 74-0, 3d.18h.53m
    ublock-unbreak: 1709-0, 3d.18h.51m
    easylist: 61259-164, 2d.22h.58m
    easyprivacy: 26386-45, 2d.22h.56m
    urlhaus-1: 10185-0, 18h.12m
    plowe-0: 3699-1415, 7d.7m
filterset (user): [empty]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 679
  launchFromSelfie: true
```
</details>

**Comment by okiehsch** [comment]
Caused by the `fanboy-annoyance` list.
````
blacklibrary.com#@#.cookiesmessage
blacklibrary.com#@##acceptcookiesWrapper
````
@ryanbr
