### ISSUE TITLE
suspilne.media: uBlock incorrectly cut the video player window

### ISSUE THREAD

**Issue by system-exe** [uBlockOrigin/uAssets#10694]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://suspilne.media/page/149-sports-online-page/`

### Category

breakage

### Describe the issue

uBlock incorrectly cut the video player window 
![Безымянный](https://user-images.githubusercontent.com/48893047/144416208-f734f984-e3c1-4cc3-9855-0b6beef6a109.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Безымянный](https://user-images.githubusercontent.com/48893047/144416389-4fa2e74b-99a8-428f-aecf-e4db54eac3c1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Chromium: 96
filterset (summary): 
  network: 98103
  cosmetic: 61074
  scriptlet: 17915
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 479-0, 28d.22h.58m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2641-1, 20d.43m
  default: 
    RUS-0: 40067-25, 10h.32m
    easylist: 61215-41, 3d.13h.34m
    easyprivacy: 26376-118, 3d.13h.32m
    plowe-0: 3699-814, 9d.19h.1m
    ublock-abuse: 74-1, 3d.13h.30m
    ublock-badware: 3468-58, 3d.13h.28m
    ublock-filters: 29698-192, 3d.13h.23m
    ublock-privacy: 188-1, 3d.12h.52m
    ublock-unbreak: 1697-38, 3d.12h.50m
    urlhaus-1: 8953-0, 10h.30m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [empty]
  triggered: 
    no-csp-reports: * true
hostRuleset: 
  added: [array of 33 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1769
  launchFromSelfie: true
```
</details>

**Comment by dportvine** [comment]
`https://suspilne.media/news/schedule/tv/`

This scriplet `cosmonova-broadcast.tv##+js(set-constant, amodule.data, emptyArr)` breaks the player.

<details>
<summary>Screen</summary>

https://github.com/user-attachments/assets/7def11c3-0cdd-420b-b41a-e78d0ebf89b3

</details>

**Comment by stephenhawk8054** [comment]
It's really hard to test for me because the video plays randomly on my side regardless of with the filter or not.

You can try

```adb
cosmonova-broadcast.tv##+js(rpnt, script, '/\{"items":[^\n]+,"midRollInterval":\d+},/', '{"items":[],"midRollInterval":0},')
```

but this site is so random for me I can't decide. If the above filter doesn't work then something's wrong with the site.

**Comment by mapx-** [comment]
- on the first test - using a kiev ip - I was able to run correctly the video without any new filter (and without ukr filter list)
- any new test failed (video does not load)

**Comment by dportvine** [comment]
> cosmonova-broadcast.tv##+js(rpnt, script, '/\{"items":[^\n]+,"midRollInterval":\d+},/', '{"items":[],"midRollInterval":0},')

That didn’t help. In that case, I’ll ask you to remove this rule `cosmonova-broadcast.tv##+js(set-constant, amodule.data, emptyArr)`

Before the broadcast starts, a 15-second video will be played, this is a self-promotion.
