### ISSUE TITLE
simpleflying.com: ads

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#10692]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://simpleflying.com/concorde-vs-tupolev-tu-144/`

### Category

ads

### Describe the issue

Ads leftover on top of article `##.simpl-1-display-ad-below-post-title`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![afbeelding](https://user-images.githubusercontent.com/80090789/144391131-48fab6aa-ce1c-4cd7-889b-ad06c1d3266e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 67794
  cosmetic: 40186
  scriptlet: 16047
  html: 598
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    NLD-0: null
  added: 
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt: 1839-0, 3h.47m
  default: 
    ublock-filters: 30326-64, 3h.47m
    ublock-privacy: 187-0, 3h.47m
    ublock-unbreak: 1708-12, 3h.47m
    easylist: 61357-491, 3h.47m
    easyprivacy: 26407-475, 3h.47m
    plowe-0: 3700-1, 3h.47m
filterset (user): [array of 282 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1018 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  dynamicFilteringEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 10
  autoUpdateDelayAfterLaunch: 60
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#000092 00001/#2A2A2A
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  launchToReadiness: 2940
  launchFromSelfie: true
```
</details>

**Comment by okiehsch** [comment]
@ryanbr

**Comment by BPower0036** [comment]
Good to know there are more leftovers more downwards in the article.

**Comment by okiehsch** [comment]
We don't add filters for sites that don't need extended syntax as stated in our readme.

**Comment by BPower0036** [comment]
Yea, my comment was more for @ryanbr if he sees this
