### ISSUE TITLE
q.gs 

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#107]
![fc857714-665d-11e6-8666-08d75024f26f](https://cloud.githubusercontent.com/assets/20338483/17821049/37e5b76a-666d-11e6-8e66-fda74deec310.png)

### URL(s) where the issue occurs

http://q.gs/AHm4n

https://adf.ly/672863/gow1ps2

### Describe the issue
Going to site advices to block adblock

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Google chrome 52
- uBlock Origin version: 1.8.4

### Settings
 uBO's default settings+adblock warning removal+antiadblock killer

### Notes

This site actively blocking adblock so even if solution emerges to this site,site will block..
So pls keep thread at developing stage not solved....

**Comment by ghajini** [comment]
@gorhill

**Comment by gorhill** [comment]
Unable to reproduce.

**Comment by Tmp341** [comment]
Those urls are very aggressive about adblocking extensions.

**Comment by ghajini** [comment]
https://www.dropbox.com/s/omhmu5yj5x3usfw/ublock%20bug.webm?dl=0

https://www.dropbox.com/s/wp11qntcp0p3ckk/list.webm?dl=0

https://www.dropbox.com/s/zhhd98vvneeq2th/Untitled%20Screencast.webm?dl=0

**Comment by gwarser** [comment]
Here:
`http://ay.gy/672863/gow1ps2`
![fly1](https://cloud.githubusercontent.com/assets/886325/17830373/d17f6266-66c9-11e6-8c29-25a9a736b05e.png)

This helps:
`@@||s1-adfly.com/show.php$subdocument,domain=ay.gy`

**Comment by ghajini** [comment]
also in firefox not working.........
![screenshot 9](https://cloud.githubusercontent.com/assets/20338483/17830731/2344f57a-66f2-11e6-89f8-b8398dddc25a.png)

**Comment by ghajini** [comment]
many indian news sites like those block adblock not working with firefox

**Comment by gwarser** [comment]
I cannot reproduce. Try logger https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by ghajini** [comment]
![screenshot 10](https://cloud.githubusercontent.com/assets/20338483/17830879/b62dc632-66f7-11e6-8c1e-99b211ac5468.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/20338483/17830880/b62e878e-66f7-11e6-9646-aba321d4d6d2.png)

**Comment by gorhill** [comment]
Do you have Tracking Protection enabled in Firefox?

**Comment by ghajini** [comment]
tracking protection disabled

**Comment by gorhill** [comment]
There is nothign I can do then, as said, I can't reproduce on my side -- so I can't investigate.

I get the blocker warning on Chrome, but I just click _Continue_ and all work fine.

**Comment by gorhill** [comment]
> This helps:
> @@||s1-adfly.com/show.php$subdocument,domain=ay.gy

Yes, seems to work, I will add it. Thanks.

**Comment by gorhill** [comment]
Actually, a redirect also works, so no need to download that frame:

    ||s1-adfly.com/show.php?url=$subdocument,redirect=noopframe,domain=ay.gy

**Comment by ghajini** [comment]
what about http://q.gs/AHm4n

**Comment by gorhill** [comment]
> what about http://q.gs/AHm4n

Works fine -- with or without Reek's, with or without clearing cookies.

**Comment by ghajini** [comment]
https://www.dropbox.com/s/2z0klxtrr8q45ra/VID_20160820_182246.3gp?dl=0

**Comment by IDKwhattoputhere** [comment]
@ghajini Use [ShareX](https://github.com/ShareX/ShareX) to film/shoot the screen. Much easier.
Also, can you post a screenshot of the logger since it works fine here?

**Comment by gorhill** [comment]
> webroot filtering extension

Now you disclose this?

**Comment by gorhill** [comment]
If I enabled Tracking Protection in Nightly, I get exactly 7 network requests blocked, and the same page as in your screenshot:

https://cloud.githubusercontent.com/assets/20338483/17830879/b62dc632-66f7-11e6-8c1e-99b211ac5468.png

**Comment by ghajini** [comment]
yes b4 revealing this i test myself by blocking webroot filtering extension,,yes i forget to mension that sorry....

you can see here with webroot filtering extension disabled 
https://www.dropbox.com/s/x0y5ylulkrvsmda/2016-08-20_19-26-01.mp4?dl=0

**Comment by gorhill** [comment]
At this point it is for you @ghajini to find out what is blocking network requests before they reach uBO -- this is an issue specific on your side, that is why nobody else can reproduce so far (except as noted when I enable Tracking Protection in Firefox).

**Comment by ghajini** [comment]
now with webroot filtering extension enabled
https://www.dropbox.com/s/n4x6g2vcx9fu5mz/2016-08-20_19-36-02.mp4?dl=0
its one and same 
with webroot i got notice that of to disable ublock

and without webroot counter time not working i.e skip button not displaying........

so even after its obivious that firefox ublock not works somewhere

**Comment by IDKwhattoputhere** [comment]
I doubt he can fix it if he can't reproduce. If you've tried `Fanboy’s Enhanced Tracking List` there's still [AdsBypasser](https://greasyfork.org/scripts/4881-adsbypasser) (or [AdsBypasserLite](https://greasyfork.org/scripts/4882-adsbypasserlite)) which I think is worth a try if you find yourself on such sites often.

**Comment by ghajini** [comment]
I can see issue is with ublock firefox extension with or without webroot....
It is certain that ublock not blocking ads and antiadblock scripts completely in firefox...
I already showed videos of proof

Chrome works fine...

Yes sure gorhill understands this...

**Comment by gorhill** [comment]
> Yes sure gorhill understands this...

I understand that something else on your side is blocking network requests before they reach uBO -- you confirmed this by showing that only 7 network requests reach uBO. Find what it is. If it's not webroot, then something else. The amazing thing is that Tracking Protection causes the exact same symptom. Frankly I think this is your issue. If so, just say so. In any case, if this thread keep going on with only unproductive "please fix gorhill", I will lock it.

**Comment by ghajini** [comment]
I just check below settings where no antivirus obiviously present
Android os
Firefox 48 with ublock origin 1.8.4

Still same issue

Than

**Comment by gorhill** [comment]
Originally you reported having the issue with Chrome (which I could not reproduce on my side). Now somehow you do not have this issue with Chrome anymore. What did you do to resolve the issue with Chrome?

**Comment by gorhill** [comment]
Did you uncheck _"uBlock filters"_ and _"uBlock filters -- Unbreak"_?

**Comment by ghajini** [comment]
Your fix 107 worked with chrome
||s1-adfly.com/show.php?url=$subdocument,redirect=noopframe,domain=ay.gy

Firefox not worked

**Comment by gorhill** [comment]
The fix was for this screenshot, which you posted before the fix existed ![](https://cloud.githubusercontent.com/assets/886325/17830373/d17f6266-66c9-11e6-8c29-25a9a736b05e.png)

Not for ![](https://cloud.githubusercontent.com/assets/20338483/17821049/37e5b76a-666d-11e6-8e66-fda74deec310.png)

How did you solve this?
![](https://cloud.githubusercontent.com/assets/20338483/17821049/37e5b76a-666d-11e6-8e66-fda74deec310.png)

**Comment by ghajini** [comment]
Yes issue is back on chrome after clearing cookies.....
Issue on both chrome and firefox for q.gs/AHm4n

**Comment by ghajini** [comment]
check on your side if by clearing cookies , if adblock removal warning is produced or not

**Comment by gorhill** [comment]
What is the extension to the left of uBO?

**Comment by ghajini** [comment]
webroot filtering extension........can i disable it

**Comment by gwarser** [comment]
![webr](https://cloud.githubusercontent.com/assets/886325/17832850/ed125602-670d-11e6-9a50-1000d58813bb.png)

Is this related to this webroot thingy? Can you disable this?

**Comment by ghajini** [comment]
webroot nothing to do with this ...i just stopped protection of webroot to see effect
https://www.dropbox.com/s/cokfz9xkvebu4bp/Untitled%20Screencast%20%281%29.webm?dl=0

**Comment by gorhill** [comment]
Find out what the dev console of the page says (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>i</kbd>):

![a](https://cloud.githubusercontent.com/assets/585534/17832906/382ea8ba-66dd-11e6-9464-597fb1a8ab7b.png)

**Comment by ghajini** [comment]
![screenshot 17](https://cloud.githubusercontent.com/assets/20338483/17832938/c36b6274-672d-11e6-85eb-a033756d5a94.png)

**Comment by gorhill** [comment]
I don't get these syntax errors, even if I remove _"uBlock filters -- Unbreak"_ to get that screen.

**Comment by gorhill** [comment]
Can you click on `amvn.js:1` to see its content?

**Comment by ghajini** [comment]
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/dot/?dpid=1&dpruleid=3&cat=107&ttl=0&groupname=-&policyname=-&username=-&userip=43.242.209.125&connectionip=127.0.0.1&nsphostname=Policy07-Mumbai&protocol=policyprocessor&dplanguage=-&url=http%3a%2f%2fstatic%2eadf%2ely%2fstatic%2fjs%2famvn%2ejs" width="100%" height="100%" frameborder=0></iframe><script>var iframe = document.getElementsByTagName("iframe")[0]; setIframe(); window.onresize = function(){ setIframe(); }; function setIframe(){ iframe.style.width = window.innerWidth+'px'; iframe.style.height = window.innerHeight+'px'; }; </script>

**Comment by ghajini** [comment]
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/dot/?dpid=1&dpruleid=3&cat=107&ttl=0&groupname=-&policyname=-&username=-&userip=43.242.209.125&connectionip=127.0.0.1&nsphostname=Policy07-Mumbai&protocol=policyprocessor&dplanguage=-&url=http%3a%2f%2fstatic%2eadf%2ely%2fstatic%2fjs%2famvn%2ejs" width="100%" height="100%" frameborder=0></iframe><script>var iframe = document.getElementsByTagName("iframe")[0]; setIframe(); window.onresize = function(){ setIframe(); }; function setIframe(){ iframe.style.width = window.innerWidth+'px'; iframe.style.height = window.innerHeight+'px'; }; </script>

**Comment by ghajini** [comment]
it is converting to some short text after pasting here in github, 
how can i show you?

**Comment by gorhill** [comment]
Surround the text with triple backticks

    ```

**Comment by ghajini** [comment]
```
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/dot/?dpid=1&dpruleid=3&cat=107&ttl=0&groupname=-&policyname=-&username=-&userip=43.242.209.125&connectionip=127.0.0.1&nsphostname=Policy07-Mumbai&protocol=policyprocessor&dplanguage=-&url=http%3a%2f%2fstatic%2eadf%2ely%2fstatic%2fjs%2famvn%2ejs" width="100%" height="100%" frameborder=0></iframe><script>var iframe = document.getElementsByTagName("iframe")[0]; setIframe(); window.onresize = function(){ setIframe(); }; function setIframe(){ iframe.style.width = window.innerWidth+'px'; iframe.style.height = window.innerHeight+'px'; }; </script> ```

**Comment by gorhill** [comment]
Reading more about `eval`, it could be an issue in the scriptlet injected by uBO. As per documentation, eval() can return something and uBO's scriptlet always returns nothing. I iwll update the scriptlet and you will be able to see if this help.

Purge cache for `uBlock filters` then force an update.

**Comment by gorhill** [comment]
Purge cache for uBlock filters then force an update.

**Comment by ghajini** [comment]
same warning again

**Comment by gorhill** [comment]
Same errors in the console?

**Comment by gorhill** [comment]
The URL in the frame is:

    http://www.airtel.in/dot/?dpid=1&dpruleid=3&cat=107&ttl=0&groupname=-&policyname=-&username=-&userip=43.242.209.125&connectionip=127.0.0.1&nsphostname=Policy07-Mumbai&protocol=policyprocessor&dplanguage=-&url=http://static.adf.ly/static/js/amvn.js

Notice that `http://static.adf.ly/static/js/amvn.js` is in there.

I am wondering if your ISP is preventing you from downloading some of the scripts on this page.

**Comment by ghajini** [comment]
how to overcome this

disabling ublock,webroot still says "you have advert blocking ectension enabled'' 
funny

after series of reloading i can bypass q.qs to original url

thanx for help...its might be my side problem

**Comment by IDKwhattoputhere** [comment]
If you want you can try changing your DNS IPs to two from [OpenNIC](https://www.opennicproject.org/) which has no censorship.

**Comment by Tmp341** [comment]
@ghajini Can you share which extensions and uBO filters and also (if you're using) which greasemonkey scripts you're using?

**Comment by ghajini** [comment]
http://q.gs/CYuvS

antiadblock notice again

**Comment by mapx-** [comment]
```
@@||ay.gy/static/js/advert.js$script,domain=q.gs
q.gs#@##bottomAd
q.gs#@##bottom
@@||s1-adfly.com/$domain=q.gs
```

**Comment by okiehsch** [comment]
Does 
`q.gs#@##bottomAd`
`q.gs#@##bottom`
`||s1-adfly.com/show.php?url=$subdocument,redirect=noopframe,domain=q.gs`
work?

**Comment by mapx-** [comment]
No, does not work.

**Comment by okiehsch** [comment]
Right I forgot `ay.gy/static/js/advert.js`, unfortunately that redirect doesn't work on my end.
`||s1-adfly.com/show.php?url=$important,subdocument,redirect=noopframe,domain=q.gs`
`q.gs#@##bottomAd`
`q.gs#@##bottom`
`@@||ay.gy/static/js/advert.js$script,domain=q.gs`
should work but is not ideal.

**Comment by ghajini** [comment]
@gorhill 
thanx for nice extension....
In reference to ur comment about my isp circumvention,
i tried changing dns or tried vpn
i can still produce issue
![screenshot 119](https://cloud.githubusercontent.com/assets/20338483/22626577/b18d9b16-ebd6-11e6-813d-d610de873311.png)

**Comment by ghajini** [comment]
@gorhill 
i see adguard skipping counter page and directly navigates to detination page...
if you bring that feature to us,it will be good......
