### ISSUE TITLE
explosm.net: breakage

### ISSUE THREAD

**Issue by My-Random-Thoughts** [uBlockOrigin/uAssets#10700]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://explosm.net/`

### Category

breakage

### Describe the issue

Videos do not load, comics are fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 155895
  cosmetic: 179361
  scriptlet: 32063
  html: 606
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 0-0, never
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 1d.23h.3m
    https://www.fanboy.co.nz/enhancedstats.txt: 2993-10, 1d.23h.1m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-5, 1d.16h.43m
    adguard-generic: 61553-4527, 8d.21h.24m
    adguard-mobile: 6985-224, 8d.21h.26m
    adguard-spyware: 25167-1136, 4d.20h.8m
    adguard-annoyance: 47691-4188, 8d.19h.18m
    adguard-social: 14703-40, 8d.19h.16m
    fanboy-thirdparty_social: 68-0, 1d.51m
    fanboy-annoyance: 59039-43855, 1d.53m
    fanboy-cookiemonster: 20441-121, 1d.49m
    fanboy-social: 23216-1081, 2h.7m
    ublock-annoyances: 4328-9, 2h.9m
    dpollock-0: 16967-1951, 4d.51m
    mvps-0: 8730-398, 4d.53m
  default: 
    ublock-filters: 30307-99, 16h.59m
    ublock-badware: 3512-1, 16h.57m
    ublock-privacy: 187-0, 5h.59m
    ublock-abuse: 74-0, 5h.57m
    ublock-unbreak: 1708-1, 5h.55m
    easylist: 61360-1013, 2h.13m
    easyprivacy: 26407-11212, 2h.11m
    urlhaus-1: 10361-0, 23h.39m
    plowe-0: 3689-1800, 11d.3h.45m
filterset (user): [array of 302 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 33 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  dynamicFilteringEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 504
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
Caused by `||player.avplayer.com^$3p` in EasyList. cc @ryanbr

**Comment by ryanbr** [comment]
avplayer.com is used on many sites as way to inject slideshow invideo ads, first case of a proper video I've seen from them
