### ISSUE TITLE
f1stream.me: detection

### ISSUE THREAD

**Issue by hamzaRiz** [uBlockOrigin/uAssets#10705]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://f1stream.me/sky-sports-f1-sky-f1-live/stream-1`

### Category

detection

### Describe the issue

Black screen over the video player with a message at the bottom saying

"kindly remove/disable adblock, and reload the page"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211202-152235-540](https://user-images.githubusercontent.com/66832981/144519275-a794530d-e8f4-42cd-a269-f26ddea693bc.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium Mobile: 96
filterset (summary): 
  network: 83827
  cosmetic: 62232
  scriptlet: 21106
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48072-1661, now
    ublock-annoyances: 4338-153, now
  default: 
    adguard-mobile: 7016-34, 1m
    easylist: 61372-23596, now
    easyprivacy: 26410-117, now
    plowe-0: 3700-900, now
    ublock-abuse: 74-0, now
    ublock-badware: 3508-60, now
    ublock-filters: 29884-589, now
    ublock-privacy: 193-2, now
    ublock-unbreak: 1705-40, now
    urlhaus-1: 8190-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3785
  launchFromSelfie: false
popupPanel: 
  blocked: 7
```
</details>

**Comment by hamzaRiz** [comment]
![IMG_20211202_201007_116](https://user-images.githubusercontent.com/66832981/144519650-b062c38e-b306-4248-a111-9de61f4cead5.jpg)
![IMG_20211202_201013_705](https://user-images.githubusercontent.com/66832981/144519652-914c929a-4061-460e-b3cf-fefe035b8290.jpg)
![IMG_20211202_201010_836](https://user-images.githubusercontent.com/66832981/144519655-35e39baf-45c6-4452-b32c-4773ae950604.jpg)

**Comment by mapx-** [comment]
I get anti adb even disabling uBO

**Comment by ghajini** [comment]
`@@||f1stream.me^$ghide`
work
