### ISSUE TITLE
fengxiangba.com: breakage

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10702]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://fengxiangba.com/anzhuoguojibanfirefoxxiazai.html`

### Category

breakage

### Describe the issue

The body of the article is hidden.
Since I'm using my phone, I can't be sure which filter is causing this one problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 68
filterset (summary): 
  network: 105851
  cosmetic: 107279
  scriptlet: 18984
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1494-0, 27m
    fanboy-annoyance: 58992-312, 5d.1h.35m
    ublock-annoyances: 4339-5, 3d.15m
  default: 
    ublock-filters: 30241-63, 3d.9m
    ublock-badware: 3440-1, 3d.6m
    ublock-privacy: 184-0, 2d.49m
    ublock-abuse: 74-0, 1h.57m
    ublock-unbreak: 1714-0, 2h.2m
    adguard-mobile: 7009-156, 3d.13m
    easylist: 61360-680, 2h
    easyprivacy: 26407-481, 1h.55m
    urlhaus-1: 8953-0, 1h.53m
    plowe-0: 3698-3, 1d.34m
    CHN-0: 26806-138, 3d.11m
filterset (user): [empty]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: 
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4274
  launchFromSelfie: true
```
</details>

**Comment by gorhill** [comment]
Caused by `##.category-share` in Fanboy Annoyances, cc @ryanbr
