### ISSUE TITLE
uploadhaven.com: popups

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#10703]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://uploadhaven.com/download/b7093a035cf5ba681f88ada162e44d40`

hotlink protection may be active, if you can't open the link, please ask I'll give you the original link to open it from

### Category

popups

### Describe the issue

popups and tabunders open whenever you click anywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 140278
  cosmetic: 52962
  scriptlet: 29935
  html: 608
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblockerLab/NanoContrib/master/dist/placeholder-buster.txt: 1263-0, 122d.22h.23m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-141, 2d.2h.27m
    adguard-generic: 61883-4828, 1d.12h.32m
    adguard-spyware: 25293-1109, 1d.23h.31m
    ublock-annoyances: 4348-11, 4h.58m
    dpollock-0: 16966-1808, 6d.13h.11m
    mvps-0: 8730-378, 7d.10h.36m
  default: 
    ublock-filters: 30357-211, 2d.13h
    ublock-badware: 3512-2, 5h
    ublock-privacy: 183-1, 1d.12h.38m
    ublock-abuse: 74-0, 1d.23h.38m
    ublock-unbreak: 1714-0, 13h.50m
    adguard-mobile: 7013-208, 1d.12h.47m
    easylist: 61320-24388, 1d.12h.45m
    easyprivacy: 26396-11237, 1d.23h.36m
    urlhaus-1: 8190-0, 4h.56m
    plowe-0: 3698-3, 10d.5h.3m
filterset (user): [array of 85 redacted]
trustedset: 
  added: [array of 30 redacted]
switchRuleset: 
  removed: 
    no-csp-reports: * true
hostRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  launchToReadiness: 4338
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
Redirects to `https://uploadhaven.com/error`

**Comment by JobcenterTycoon** [comment]
Try `https://uploadhaven.com/download/68192cb6b6e845a9b65aecb81ad7148c`

**Comment by uBlock-user** [comment]
Also https://github.com/uBlockOrigin/uAssets/commit/2f43d9ca78af273c8387344f514a45f04d4bee0a

It's not unstable. Works as expected. No third-party crap getting loaded either.

**Comment by okiehsch** [comment]
I added
`uploadhaven.com##+js(set, globalThis, null)`
We already have a filter for that site, so disabling the inline-script causing the requests, seems preferable.

**Comment by uBlock-user** [comment]
Setting `globalThis` to `null` could break some site functionality, so avoided that.

**Comment by okiehsch** [comment]
Sure, but it's a simple 1click hosting site and I can still download. 
The only other functionality is uploading but that needs an account to test.

**Comment by uBlock-user** [comment]
Added a safer alternative, and it isn't just for this site, so should be used elsewhere this inline-script is used.

**Comment by okiehsch** [comment]
> Safer alternative

Thanks, thats better.

**Comment by okiehsch** [comment]
> so should be used elsewhere this inline-script is used.

Agreed, you can replace all `##+js(set, globalThis, null)` with your filter.

**Comment by okiehsch** [comment]
Or I can do it of you want.

**Comment by uBlock-user** [comment]
`this`, `globalThis` are global javascript objects and not site-specific JS code, so using set on them should always be avoided as much as possible.

**Comment by okiehsch** [comment]
Hm, seems not all `##+js(set, globalThis, null)` can be replaced.
Can you test `ceesty.com/q4hK55`.

**Comment by uBlock-user** [comment]
>  Can you test ceesty.com/q4hK55.

Redirects me to `https://clkmein.com/JkUX361a92362c1524JCzFmx0ZBU57k?r=` which is 404

**Comment by okiehsch** [comment]
Hm. That's the only domain I checked, that does not work with the replaced filter, I will leave it alon for now and change the rest.
