### ISSUE TITLE
autofaucet.dutchycorp.space: detection

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#10701]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://autofaucet.dutchycorp.space/adblock.php`

### Category

detection

### Describe the issue

Detects uBO when logged in...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 79634
  cosmetic: 21109
  scriptlet: 16210
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30436-193, 58m
    ublock-badware: 3512-2, 58m
    ublock-privacy: 187-1, 58m
    ublock-abuse: 74-0, 58m
    ublock-unbreak: 1716-0, 58m
    adguard-mobile: 7016-172, 58m
    easylist: 61360-24043, 58m
    easyprivacy: 26407-481, 58m
    urlhaus-1: 8190-0, 58m
    plowe-0: 3700-3, 58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1523
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
> Detects uBO when logged in...

I don't get redirected to that url upon logging in.

**Comment by datoshkr** [comment]
When already logged in, it detects uBO on https://autofaucet.dutchycorp.space/roll.php and redirects to https://autofaucet.dutchycorp.space/adblock.php

![Screenshot_20211202-193247_Firefox.jpg](https://user-images.githubusercontent.com/79659024/144458174-eee95e80-03ed-4386-a314-7073044f05ae.jpg)
