### ISSUE TITLE
songs.pk

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#1070]
Popups are served on `https://songs.pk`.

**Error URL:** `https://songs.pk/`

_**Note:** Using 1.14.22 on Chrome 63 with the default filters and settings._

**Comment by okiehsch** [comment]
Does 
`songs.pk##script:inject(popads-dummy.js)`
fix all popups?

**Comment by mapx-** [comment]
or
`songs.pk##script:inject(abort-on-property-read.js, popns)` ?

**Comment by okiehsch** [comment]
That is basically the same, see
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L1376-L1383

**Comment by gotitbro** [comment]
@okiehsch @mapx- Both filters block the popups. The popups are caused by `evenexcite.com` probably a PopAds domain.

@SMed79 You had a PopAds domain list can't seem to find it now.

**Comment by SMed79** [comment]
@gotitbro https://github.com//antipopads/blob/master/popads.txt
