### ISSUE TITLE
munsifdaily.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10710]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://munsifdaily.com`

### Describe the issue

Site detects content blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/144548312-57cf7c47-9945-4fb9-bfd0-2449f06bdbfc.png)

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Settings

N/A

### Notes

N/A

**Comment by ghajini** [comment]
Force update your Ublock-filters to include

`*##div.adsbygoogle.Ad-Container.sidebar-ad:style(display:block !important)`

fixed as a part of https://github.com/uBlockOrigin/uAssets/commit/f8b29b406468c9a1b2c904b46023aad7516d735d
