### ISSUE TITLE
loot.tv: breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#10717]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://loot.tv/video/672682`

### Category

breakage

### Describe the issue

video doesn't appear when ublock origin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 79524
  cosmetic: 44708
  scriptlet: 16246
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30456-141, 2h.16m
    ublock-badware: 3512-21, 2h.15m
    ublock-privacy: 189-0, 2h.15m
    ublock-abuse: 74-0, 2h.15m
    ublock-unbreak: 1716-0, 2h.15m
    adguard-mobile: 7017-156, 2h.15m
    easylist: 61373-705, 2h.15m
    easyprivacy: 26411-482, 2h.15m
    urlhaus-1: 7947-0, 2h.15m
    plowe-0: 3700-3, 2h.15m
filterset (user): [array of 280 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 557
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

```
@@||cd.connatix.com/connatix.player.js$script,domain=loot.tv
@@||cds.connatix.com/*/connatix.player.dc.js$script,domain=loot.tv
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=loot.tv
```

first 2 filters to unbreak the video

**Comment by garry-ut99** [comment]
Broken again by EasyList, this works: `@@||cds.connatix.com/p/*/elements.ui.*.js$script,domain=loot.tv`
I decided to report here because the previous breakage still not fixed in EasyList, only in uBO.

**Comment by garry-ut99** [comment]
https://github.com/easylist/easylist/commit/eb93d558bbd286785529df92e540cfba9cb051b2 - has been fixed by EasyList.
