### ISSUE TITLE
romania.bz: detection

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#10715]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://romania.bz/`

### Category

detection

### Describe the issue

Detects uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211203-104531_Firefox](https://user-images.githubusercontent.com/79659024/144557846-a99fa647-195f-4f81-86c8-d28dfb152e5f.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 79410
  cosmetic: 21113
  scriptlet: 16212
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30442-193, 1h.33m
    ublock-badware: 3512-2, 1h.33m
    ublock-privacy: 189-1, 1h.33m
    ublock-abuse: 74-0, 1h.33m
    ublock-unbreak: 1716-0, 1h.33m
    adguard-mobile: 7017-172, 1h.33m
    easylist: 61373-24043, 1h.33m
    easyprivacy: 26411-482, 1h.33m
    urlhaus-1: 7947-0, 1h.33m
    plowe-0: 3700-3, 1h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1342
  launchFromSelfie: false
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue, see if works:

`@@||romania.bz^$ghide`

**Comment by ghajini** [comment]
Provide the url from where you get the link

**Comment by datoshkr** [comment]
ghide not works. Website not detects uBO when visiting directly, it detects uBO when I visit from https://autofaucet.dutchycorp.space/extend_claim_count_wall_nu_link_per_click_version.php?username=EC-UserId-569145&id=64

**Comment by datoshkr** [comment]
Needs account

**Comment by uBlock-user** [comment]
> https://autofaucet.dutchycorp.space/extend_claim_count_wall_nu_link_per_click_version.php?username=EC-UserId-569145&id=64

wrong data is reported by site.

**Comment by mapx-** [comment]
@datoshkr @ghajini created an account but you should tell us what to do on that page to get the anti adb, step by step

**Comment by datoshkr** [comment]
First, login on https://autofaucet.dutchycorp.space

Go to "Shortlinks Wall" page (https://autofaucet.dutchycorp.space/shortlinks-wall.php)

Find shortlink with name "SkyUrl" and click "CLAIM" button, romania.bz website will be opened, wait 10-15 seconds and you will see "Adblock Detected" popup...


Also, uBO detected on few more shortlink from autofaucet.dutchycorp.space

**Comment by mapx-** [comment]
these should work

```
romania.bz##+js(no-fetch-if, ads)
romania.bz##+js(aeld, , ads)
romania.bz##+js(nano-sib)
*$script,redirect-rule=noopjs,domain=romania.bz
romania.bz##.ays-pb-modals
```

**Comment by datoshkr** [comment]
> First, login on 
> `https://autofaucet.dutchycorp.space`
> 
> Go to "Shortlinks Wall" page 
> `https://autofaucet.dutchycorp.space/shortlinks-wall.php`
> 
> Find shortlink with name "SkyUrl" and click "CLAIM" button, romania.bz website will be opened, wait 10-15 seconds and you will see "Adblock Detected" popup...
> 
> 
> Also, uBO detected on few more shortlink from autofaucet.dutchycorp.space

Same for "URLpay" (alertcrypto.eu) shortlink

**Comment by datoshkr** [comment]
Not works for "alertcrypto.eu", website still detects uBO.

![Screenshot_20211204-173522_Firefox.jpg](https://user-images.githubusercontent.com/79659024/144711536-29e254d3-5ea3-4a4d-9e42-7252107123a4.jpg)

**Comment by mapx-** [comment]
add and report back

`alertcrypto.eu##+js(no-fetch-if, ads)`

**Comment by datoshkr** [comment]
> add and report back
> 
> `alertcrypto.eu##+js(no-fetch-if, ads)`
> 

It works :)

**Comment by BottledSoda** [comment]
Is there anything active from the domains?
