### ISSUE TITLE
store.filmyzilla-in.xyz: detection

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#10714]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://store.filmyzilla-in.xyz/lZy0vFG8`

### Category

detection

### Describe the issue

Detects uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211203-094003_Firefox](https://user-images.githubusercontent.com/79659024/144551561-9a7dfd8c-88f2-4edd-a8bd-448bfbb7a5c8.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 94
filterset (summary): 
  network: 79410
  cosmetic: 21113
  scriptlet: 16212
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30442-193, 27m
    ublock-badware: 3512-2, 27m
    ublock-privacy: 189-1, 27m
    ublock-abuse: 74-0, 27m
    ublock-unbreak: 1716-0, 27m
    adguard-mobile: 7017-172, 27m
    easylist: 61373-24043, 27m
    easyprivacy: 26411-482, 27m
    urlhaus-1: 7947-0, 27m
    plowe-0: 3700-3, 27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1342
  launchFromSelfie: false
```
</details>

**Comment by BottledSoda** [comment]
`https://dz4link.com/001PW` - in case URL doesn't work, and if there are filters addressing anything `dz4link. com`-related, I think moving moving filters for this issue to those could be good.
