### ISSUE TITLE
vrcmods.com: detection

### ISSUE THREAD

**Issue by StishStash** [uBlockOrigin/uAssets#10711]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://vrcmods.com/`

### Category

detection

### Describe the issue

Website detects an adblocker, even though I did everything above.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 85139
  cosmetic: 15826
  scriptlet: 16181
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-136, 2m
    fanboy-thirdparty_social: 68-1, 2m
  default: 
    easylist: 61373-23390, 2m
    easyprivacy: 26411-17, 2m
    plowe-0: 3700-811, 2m
    ublock-abuse: 74-0, 2m
    ublock-badware: 3508-64, 2m
    ublock-filters: 29789-269, 2m
    ublock-privacy: 193-3, 2m
    ublock-unbreak: 1699-38, 2m
    urlhaus-1: 7947-0, 2m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 956
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by S0dV** [comment]
`https://vrcmods.com/` - antiadb
encountered after seeing `https://github.com/AdguardTeam/AdguardFilters/issues/110169`
