### ISSUE TITLE
etsy.com: breakage

### ISSUE THREAD

**Issue by anterendulic** [uBlockOrigin/uAssets#10718]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not open more than five (5) issues today, or I am a long time contributor to this repo

### URL address of the web page

`https://www.etsy.com/listing/970498333/mechanical-keyboard-display-stand`

### Category

breakage

### Describe the issue

When I open an item and it has some photos posted by user in the reviews ("Photos from reviews" section), and I click any of those images, the image doesn't open. I get 2 errors in the uBO logger each time I click one of those images.

Example of errors from the logger:
--1st error:
Filter||etsy.com/bcn/beacon
Filter listEasyPrivacy 
Contextwww.etsy.com
Partyness(1) etsy.com ⇒ etsy.com
Typebeacon
URLhttps://www.etsy.com/bcn/beacon

--2nd error:
Filter?log_performance_metrics
Filter listEasyPrivacy 
Contextwww.etsy.com
Partyness(1) etsy.com ⇒ etsy.com
Typexhr
URLhttps://www.etsy.com/api/v3/ajax/bespoke/public/neu/specs/customer_photos_modal?log_performance_metrics=false&specs%5Bcustomer_photos_modal%5D%5B%5D=AppreciationPhotos_ApiSpecs_ReviewContentModal&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Blisting_id%5D=970498333&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bshop_id%5D=28088559&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Blisting_only%5D=false&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bshould_lazy_load_images%5D=false&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Boverlay_id%5D=customer-photo-overlay-carousel&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bexclude_listing_photos%5D=false&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bis_sold_out_listing%5D=false&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bis_own_listing%5D=false&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bshould_show_variations_overlay%5D=true&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bcategory_path%5D%5B%5D=825&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bcategory_path%5D%5B%5D=850&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bcategory_path%5D%5B%5D=853&specs%5Bcustomer_photos_modal%5D%5B1%5D%5Bcategory_path%5D%5B%5D=1896

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 77949
  cosmetic: 39359
  scriptlet: 16146
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30365-28, 4m
    ublock-badware: 3512-1, 4m
    ublock-privacy: 184-0, 1d.15h.37m
    ublock-abuse: 74-0, 1d.15h.35m
    ublock-unbreak: 1708-0, 1d.15h.41m
    easylist: 61354-544, 1d.15h.39m
    easyprivacy: 26397-473, 1d.19h.43m
    plowe-0: 3700-3, 19h.3m
    urlhaus-1: 7947-0, 2h.47m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 281
  launchFromSelfie: true
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||etsy.com/api/*/ajax/*$xhr,1p`

**Comment by gorhill** [comment]
@anterendulic 

> I get 2 errors in the uBO logger

To be clear, these are not "errors", these are entries uBO blocked as per filter lists -- except for cases of false positive such as the one you report here, the blocking is by design, they are not "errors".

**Comment by Yuki2718** [comment]
> @@||etsy.com/api/*/ajax/*$xhr,1p

Or just to remove
```
/public/statsd
?log_performance_metrics
```
as apparently only seen here.

**Comment by anterendulic** [comment]
> 

I added this to my filters and now it's working. Not sure what it does exactly. Can you explain?

@gorhill Makes sense.

**Comment by okiehsch** [comment]
> Not sure what it does exactly. Can you explain?

Blocking those requests causes the breakage you experienced, my filter allows them.

**Comment by ryanbr** [comment]
The page loaded fine. `@@||etsy.com/api//ajax/$xhr,1p` is an overkill, not good for privacy either.

**Comment by Yuki2718** [comment]
> The page loaded fine. 

I doubt you have read the OP's description. But well, what is actually causing the issue is `?log_performance_metrics`.

**Comment by mapx-** [comment]
needing only

`@@||etsy.com/api/*/ajax/bespoke/public/neu/specs/*_photos_modal$xhr,1p`

@ryanbr
