### ISSUE TITLE
skidrowcodex.net: popups

### ISSUE THREAD

**Issue by mirko8054** [uBlockOrigin/uAssets#10724]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.skidrowcodex.net/`

### Category

popups

### Describe the issue

It just opens some random ads when clicking a link

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 83596
  cosmetic: 46300
  scriptlet: 16179
  html: 0
listset (total-discarded, last updated): 
  default: 
    ITA-0: 12526-0, 4h.38m
    easylist: 61360-9, 1d.11h.10m
    easyprivacy: 26407-19, 1d.11h.8m
    plowe-0: 3699-810, 8d.10h.53m
    ublock-abuse: 74-0, 1d.11h.6m
    ublock-badware: 3508-59, 1d.11h.4m
    ublock-filters: 29783-123, 1d.11h.1m
    ublock-privacy: 191-1, 1d.10h.59m
    ublock-unbreak: 1697-38, 1d.10h.57m
    urlhaus-1: 8032-0, 4h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1548
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
Because of `skidrowcodex.net##+js(aeld, /^(DOMContentLoaded|load)$/, addEventListener)` (uBlock filters – Annoyances) autosearch does not work: https://i.imgur.com/aMjsbXC.jpg
