### ISSUE TITLE
smartdroid.de: breakage

### ISSUE THREAD

**Issue by dfriday** [uBlockOrigin/uAssets#10727]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.smartdroid.de/`

### Category

breakage

### Describe the issue

Refreshing loop on homepage.
"The form submission is invalid" on articles.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium Mobile: 96
filterset (summary): 
  network: 81391
  cosmetic: 23626
  scriptlet: 16238
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 4951-368, 9h.56m
    adguard-mobile: 7013-37, 2d.20h.50m
    easylist: 61345-23558, 2d.20h.48m
    easyprivacy: 26397-37, 2d.20h.46m
    plowe-0: 3699-899, 10d.14h.35m
    ublock-abuse: 74-0, 2d.20h.44m
    ublock-badware: 3508-60, 2d.20h.22m
    ublock-filters: 29865-293, 2d.20h.26m
    ublock-privacy: 187-2, 2d.20h.20m
    ublock-unbreak: 1703-39, 2d.20h.24m
    urlhaus-1: 7947-0, 9h.54m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1159
  launchFromSelfie: true
popupPanel: 
  blocked: 2
  no-scripting: true
```
</details>

**Comment by mapx-** [comment]
- Chromium Mobile => what mobile browser is this (accepting the extensions) ?
- `no-scripting: true` did you test keeping all the default settings ON ?

**Comment by uBlock-user** [comment]
Test on default settings/lists + all other extensions disabled.

**Comment by dfriday** [comment]
Problem seems to be related to used Kiwi browser not ublock.
Works on Firefox.
