### ISSUE TITLE
go.fire-link.net: detection

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#10729]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://go.fire-link.net/tInl`

### Category

detection

### Describe the issue

Detects uBO, but not when visiting directly, it detects uBO when visiting from `https://autofaucet.dutchycorp.space/shortlinks-wall.php` with shortlink. Account required

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211204-163018_Firefox](https://user-images.githubusercontent.com/79659024/144709467-40d84a19-e00b-4f1a-a462-7faa97837423.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox Mobile: 94
filterset (summary): 
  network: 79535
  cosmetic: 21126
  scriptlet: 16227
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30480-193, 26m
    ublock-badware: 3536-2, 26m
    ublock-privacy: 193-1, 26m
    ublock-abuse: 74-0, 26m
    ublock-unbreak: 1719-0, 26m
    adguard-mobile: 7022-172, 26m
    easylist: 61078-24048, 26m
    easyprivacy: 26427-482, 26m
    urlhaus-1: 8315-0, 26m
    plowe-0: 3695-3, 26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1505
  launchFromSelfie: true
popupPanel: 
  blocked: 73
```
</details>

**Comment by okiehsch** [comment]
No need to open new issues for all sites that include `https://autofaucet.dutchycorp.space/shortlinks-wall.php`.
Just add new domains in one issue thread.

**Comment by datoshkr** [comment]
yofaurls.com also detects uBO

![Screenshot_20211204-174232_Firefox.jpg](https://user-images.githubusercontent.com/79659024/144711744-e735fe2a-89e4-46a6-9a4f-0d51b5348e6b.jpg)

**Comment by mapx-** [comment]
provide complete link

**Comment by datoshkr** [comment]
> provide complete link

https://www.yofaurls.com/QJLg

**Comment by datoshkr** [comment]
https://wplink.online/wz3IdvZ also detects uBO

![OnPaste 20211205-192200](https://user-images.githubusercontent.com/79659024/144752742-43b38e62-2fba-42db-9a00-64c3b2635c48.png)

**Comment by datoshkr** [comment]
`https://coin-free.com/` also detects uBO when visiting from `https://autofaucet.dutchycorp.space/shortlinks-wall.php`

![OnPaste 20211212-125819](https://user-images.githubusercontent.com/79659024/145713426-b82aab9c-4657-4bba-b4eb-13d71cedee6d.png)

**Comment by mapx-** [comment]
have I ask you again to provide the indications to get to that site ?

**Comment by datoshkr** [comment]
> have I ask you again to provide the indications to get to that site ?

Login on `https://autofaucet.dutchycorp.space/`, go to `https://autofaucet.dutchycorp.space/shortlinks-wall.php`, find `DashF` shortlink, click `CLAIM` button, you will redirect that site.

**Comment by datoshkr** [comment]
Website still detects uBO.

**Comment by mapx-** [comment]
update & test again

**Comment by datoshkr** [comment]
> update & test again

works... :)

**Comment by datoshkr** [comment]
@mapx- Also this website detects uBO

'http://www.softairbay.com/shortSAB/u0xbFF4AeKS'

![Screenshot_20211215-165617_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146190771-d91ba041-a6e7-4f2c-ae3f-df3aa9c503fd.jpg)

**Comment by datoshkr** [comment]
> @mapx- Also this website detects uBO
> 
> 'http://www.softairbay.com/shortSAB/u0xbFF4AeKS'
> 
> ![Screenshot_20211215-165617_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146190771-d91ba041-a6e7-4f2c-ae3f-df3aa9c503fd.jpg)

'SoftAir' shortlink from 'https://autofaucet.dutchycorp.space/shortlinks-wall.php'

**Comment by datoshkr** [comment]
This website too

`https://o.ovlinks.com/9Yybk`

![Screenshot_20211215-173953_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146197084-9163935b-c09f-4848-a83e-7408acf8d21a.jpg)

**Comment by datoshkr** [comment]
One more

`https://ccsl.xyz/UsxgUTlbE`

![Screenshot_20211215-184703_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146208084-fa7dab69-67af-469e-9bb1-3bcfbb102ffb.jpg)

**Comment by datoshkr** [comment]
One more

`techmart4u.in`

![Screenshot_20211216-011215_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146265948-1a2c4425-73e2-4820-8e6c-7dd4447e3d34.jpg)

**Comment by mapx-** [comment]
It's the last time I asked you to provide the necessary info.

**Comment by datoshkr** [comment]
> It's the last time I'm asking you to provide the necessary info. 

Sorry, please do not judge me, so far I have not been able to fully explain...

Website is shortlink from `https://autofaucet.dutchycorp.space/shortlinks-wall.php`, with name `URLf`.

If you find shortlink with name `URLf` on `https://autofaucet.dutchycorp.space/shortlinks-wall.php` and click `CLAIM` button, you will redirected to `https://techmart4u.in/` and you will see "Adblock Detected" popup after few seconds.

`techmart4u.in##+js(nobab)` or/and `@@||techmart4u.in^$ghide` not works with my testing...

**Comment by datoshkr** [comment]
@mapx- Not works :(

**Comment by mapx-** [comment]
test again after updating the lists

**Comment by datoshkr** [comment]
> test again after updating the lists

Works. Thank you :)

**Comment by datoshkr** [comment]
`DZ4` shortlink from `autofaucet.dutchycorp.space/shortlinks-wall.php` also detects uBO.

Full URL `https://stores.filmyzilla-in.xyz/6Z6f`

`@@||stores.filmyzilla-in.xyz^$ghide` works, can you add it to uBO list?

![Screenshot_20211217-090004_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146491563-cba7b21b-8b52-4751-b50a-f3467979464e.jpg)

**Comment by datoshkr** [comment]
Also, `https://www.lootlinks.xyz/cPoL` detects uBO.

![Screenshot_20211217-150616_Firefox.jpg](https://user-images.githubusercontent.com/79659024/146535675-0e4929bb-ee33-4ca1-9691-b3ccbad3f1d3.jpg)

`lootlinks.xyz##+js(nobab)` works.

**Comment by datoshkr** [comment]
> `DZ4` shortlink from `autofaucet.dutchycorp.space/shortlinks-wall.php` also detects uBO.
> 
> Full URL `https://stores.filmyzilla-in.xyz/6Z6f`
> 
> `@@||stores.filmyzilla-in.xyz^$ghide` works, can you add it to uBO list?
> 
> https://user-images.githubusercontent.com/79659024/146491563-cba7b21b-8b52-4751-b50a-f3467979464e.jpg

Website detects uBO when I have enabled `FIN: Adblock List for Finland`, when I disable it website works fine. I see `##div[class=ad-banner]` filter from `FIN: Adblock List for Finland` in logger, it is possible to fix this without disabling `FIN: Adblock List for Finland` ?

![20211224-172914](https://user-images.githubusercontent.com/79659024/147356088-14ed9bf1-eae6-4840-9a31-4da530cdf4ac.png)
