### ISSUE TITLE
midomi.com: breakage

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#10731]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.midomi.com`

### Describe the issue

This website offers a tool to search for music by playing a sound online.

1) When I go to the website and click on the search button (the big yellow circle), it says "listening" but when I play the sound for it to record, nothing happens.

2) Then when I click on "Cancel", nothing happens (indicating that the functionality is broken)

3) and when I click on the search button again, the website shows "undefined: An unexpected error has occurred".

### Screenshot(s)

![1](https://user-images.githubusercontent.com/17685483/144711263-25fdf692-ede9-4dc4-a3b8-2ba570c97026.png)
![2](https://user-images.githubusercontent.com/17685483/144711264-c8336066-6542-45a0-a143-a874408004ec.png)
![3](https://user-images.githubusercontent.com/17685483/144711265-5264c807-353a-4620-93f5-b92c3f03ac75.png)

### Notes

> When I disable uBO on that webpage, the issue is gone.
>> I tried to find the root of this issue using the logger tool and I found out that the **uBlock filters – Privacy** filterlist is causing this and when I disable that specific filterlist, the issue is gone but I couldn't diagnose it further.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78071
  cosmetic: 39359
  scriptlet: 16192
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61059-6, 4h.50m
    easyprivacy: 26427-17, 4h.50m
    plowe-0: 3695-810, 4h.50m
    ublock-abuse: 74-0, 4h.52m
    ublock-badware: 3532-63, 4h.52m
    ublock-filters: 29819-119, 4h.51m
    ublock-privacy: 197-2, 16m
    ublock-unbreak: 1702-38, 4h.51m
    urlhaus-1: 8315-0, 4h.49m
filterset (user): [array of 17 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 239
  launchFromSelfie: true
```
</details>

**Comment by uBlock-user** [comment]
Add `@@||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js,domain=midomi.com` to my filters and report back.

**Comment by mapx-** [comment]
@ryanbr

**Comment by MasterKia** [comment]
> Add `@@||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js,domain=midomi.com` to my filters and report back.

This seems to have fixed the issue.

**Comment by uBlock-user** [comment]
@gorhill `gtm.js` needs to be updated, the error dumped in the console -- 

`Uncaught TypeError: can't access property "get", ga.getAll()[0] is undefined`

**Comment by gorhill** [comment]
The site does not check whether the result of `getAll()` is an empty array, not sure the issue is with uBO's neutered scriptlet. I would need to see more cases of similar breakage before risking changing the scriptlet, which could lead to even more breakage.

**Comment by AdamWr** [comment]
I'm not sure, but I think that it looks similar to this issue - https://github.com/AdguardTeam/Scriptlets/issues/160#issuecomment-962500405

**Comment by gorhill** [comment]
Ok, I could try a fix and see what comes out of this from those using dev build. Thinking a bit more about this, `getByName()` already always return a fake `Tracker` regardless of the argument, so it might make sense to return at least one fake `Tracker` from `getAll()` regardless.
