### ISSUE TITLE
technopat.net: ads

### ISSUE THREAD

**Issue by MuhammetEminCakir** [uBlockOrigin/uAssets#10735]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.technopat.net/2021/12/04/13-nesil-raptor-lake-cpu-ilk-kez-testte-gorundu/`

### Category

ads

### Describe the issue

Ads are not exist but ad's URL exist and clickeble
![Screenshot 2021-12-05 at 03-01-40 13 Nesil Raptor Lake İşlemci ilk Kez Testte Göründü](https://user-images.githubusercontent.com/64583157/144728403-d996585d-2a5d-42d5-86be-3c5ad8795211.png)
![Screenshot 2021-12-05 at 03-02-43 Arctis 7+ Plus Siyah Multi-platform Wireless Kablosuz 7 1 Usb-c Gaming Oyuncu Kulaklık](https://user-images.githubusercontent.com/64583157/144728420-9532efe1-00a3-4d3c-83f5-620bba0123b8.png)
.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 80370
  cosmetic: 45914
  scriptlet: 16514
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30360-41, 1d.9h.51m
    ublock-badware: 3512-1, 1d.9h.49m
    ublock-privacy: 189-0, 1d.9h.47m
    ublock-abuse: 74-0, 1d.9h.45m
    ublock-unbreak: 1711-0, 1d.9h.43m
    easylist: 61407-557, 1d.9h.41m
    easyprivacy: 26412-479, 1d.9h.39m
    urlhaus-1: 8315-0, 4h.29m
    plowe-0: 3695-3, 1d.9h.34m
    TUR-0: 9009-57, 1d.10h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 314
  launchFromSelfie: true
popupPanel: 
  blocked: 19
```
</details>

**Comment by LikesHisComputer** [comment]
I encountered a popup.

Is `technopat.net##+js(set, td_ad_background_click_link, '')` a good filter?

**Comment by mapx-** [comment]
this should work:

`technopat.net##+js(nowoif)`

**Comment by Yuki2718** [comment]
Hm, it seems `technopat.net##+js(set, td_ad_background_click_link, '')` is still working but I somehow added to Base and not to Turkish filter. Will move.
