### ISSUE TITLE
http://www.piratefilmeshd.org/

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#1073]
`http://www.piratefilmeshd.org/`
`||goo.gl/nZCz7B`
malvertisement

**Comment by mapx-** [comment]
add
`###floatLayer2`

**Comment by xqk94524** [comment]
![screenshot-2017-12-21 pirate filmes hd - filmes torrent bluray 1080p 720p baixar filmes](https://user-images.githubusercontent.com/34273204/34274761-79c15e58-e670-11e7-8cc6-2be9443252b8.png)

I was saying about the yellow bar, it request for install a fake version of adobe flash

**Comment by mapx-** [comment]
yeah, the filter above is working.

Another classic filter
`||goo.gl^$subdocument,domain=piratefilmeshd.org`

**Comment by xqk94524** [comment]
I think, it can be block globally, as it is a malware link
