### ISSUE TITLE
listen.klove.com: breakage

### ISSUE THREAD

**Issue by krazzdav** [uBlockOrigin/uAssets#10737]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://listen.klove.com/`

### Category

breakage

### Describe the issue

unable to Play the stream; after pressing the play button it just clocks with an infinite circle like it is starting. It does play when ublock is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!-- drag-and-drop screenshot here --
![Stream Issue](https://user-images.githubusercontent.com/95554902/144731307-366b0100-b19b-4ec8-ad58-519d57e734d5.JPG)
>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77966
  cosmetic: 39351
  scriptlet: 16181
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61372-6, 2d.46m
    easyprivacy: 26410-17, 2d.44m
    plowe-0: 3699-809, 10d.17h.57m
    ublock-abuse: 74-0, 2d.42m
    ublock-badware: 3508-59, 2d.40m
    ublock-filters: 29789-118, 2d.38m
    ublock-privacy: 191-1, 2d.36m
    ublock-unbreak: 1699-38, 2d.34m
    urlhaus-1: 7947-0, 21h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 268
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by LikesHisComputer** [comment]
Is `@@||tags.tiqcdn.com/utag/emf/kl/prod/utag.js$script,domain=listen.klove.com` a good filter?

For uBO team: Would exempting `listen.klove.com` from `||tags.tiqcdn.com/utag/*/prod/utag.js$script,redirect-rule=noopjs` (`ubreak filter`) be a good idea?

**Comment by krazzdav** [comment]
> Is `@@||tags.tiqcdn.com/utag/emf/kl/prod/utag.js$script,domain=listen.klove.com` a good filter?
> 
> For uBO team: Would exempting `listen.klove.com` from `||tags.tiqcdn.com/utag/*/prod/utag.js$script,redirect-rule=noopjs` (`ubreak filter`) be a good idea?

added the suggested filter and it does work. Thank you for figuring it out (y)

**Comment by LikesHisComputer** [comment]
> Thank you for figuring it out (y)

You're welcome and thanks for confirming!
