### ISSUE TITLE
filecr.com: detection

### ISSUE THREAD

**Issue by furkankolsuz** [uBlockOrigin/uAssets#10734]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://filecr.com/windows/internet-download-manager/?id=5887558786`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 95
filterset (summary): 
  network: 80021
  cosmetic: 45918
  scriptlet: 16564
  html: 0
listset (total-discarded, last updated): 
  default: 
    TUR-0: 9009-56, 3h.45m
    easylist: 61078-17, 3h.40m
    easyprivacy: 26427-22, 3h.38m
    plowe-0: 3695-811, 3h.36m
    ublock-abuse: 74-0, 3h.31m
    ublock-badware: 3532-63, 3h.27m
    ublock-filters: 29824-133, 3h.25m
    ublock-privacy: 197-2, 3h.23m
    ublock-unbreak: 1702-38, 3h.21m
    urlhaus-1: 8250-0, 3h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 556
  launchFromSelfie: true
popupPanel: 
  blocked: 10
```
</details>

**Comment by Yuki2718** [comment]
What Chromium do you use? It's likely someting like borwser's contents blocker is interferring tho you checked "I am not using another content blocker along uBO".
@gorhill Is it possible to include more info about browser? Chromium is so diverse that this info alone is not very helpful.

**Comment by MasterKia** [comment]
Although the issue _is not reproducible_ by default filterlists, add `@@||filecr.com/wp-content/plugins/deblocker/js/ads.js$script,1p` to **my filters** and report back.
