### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by Anon-0101** [uBlockOrigin/uAssets#10733]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://aternos.org/`

### Category

detection

### Describe the issue

Ublock can't bypass anti-adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/87794399/144716549-16f39029-c5e9-4d7a-911c-7a9aec2b2325.png)
![image](https://user-images.githubusercontent.com/87794399/144716563-c749fe19-ba1f-4a2a-affa-c7e74ede188a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78073
  cosmetic: 39360
  scriptlet: 16147
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30361-27, 5h.52m
    ublock-badware: 3536-1, 5h.50m
    ublock-privacy: 193-0, 5h.48m
    ublock-abuse: 74-0, 5h.46m
    ublock-unbreak: 1713-0, 5h.44m
    easylist: 61061-549, 5h.42m
    easyprivacy: 26427-475, 5h.40m
    urlhaus-1: 8315-0, 1h.38m
    plowe-0: 3697-3, 4d.6h.18m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1456
  launchFromSelfie: true
popupPanel: 
  blocked: 26
```
</details>

**Comment by uBlock-user** [comment]
```
aternos.org##+js(aost, atob, stackDepth:1)
aternos.org##span[style*="opacity: 0"]
```

That will get rid of the overlay, but Start button will not work on its own.

**Comment by Anon-0101** [comment]
What do I do about start button then?

**Comment by uBlock-user** [comment]
Need to run `$('#start').each(function() { this._ready = true; });` in the console tab after opening dev tools via F12.

**Comment by Anon-0101** [comment]
oh thanks

**Comment by RandomVersion** [comment]
> ```
> aternos.org##+js(aost, atob, stackDepth:1)
> aternos.org##span[style*="opacity: 0"]
> ```
> 
> That will get rid of the overlay, but Start button will not work on its own.

The overlay is still there.

**Comment by uBlock-user** [comment]
```
aternos.org##+js(set, atob, noopFunc)
aternos.org##span[style*="opacity:  0"]
```
Updated fix.

**Comment by RandomVersion** [comment]
Thanks!

**Comment by RandomVersion** [comment]
The overlay is gone but some buttons cant be clicked such as restart server but the sidebar can be clicked.

**Comment by uBlock-user** [comment]
try as instructed in https://github.com/uBlockOrigin/uAssets/issues/10733#issuecomment-987729825

**Comment by RandomVersion** [comment]
uhh the overlay is back?

**Comment by uBlock-user** [comment]
Yep, the admin is watching us.

**Comment by Yuki2718** [comment]
> Need to run `$('#start').each(function() { this._ready = true; });` in the console tab after opening dev tools via F12.

We need aternos-defuser.js?

**Comment by uBlock-user** [comment]
@Yuki2718 upto to @gorhill

**Comment by DumbGameMaker** [comment]
maybe block the URL `data:text/javascript;base64,ICAgIChmdW5jdGlvbigpeyAgICAgICAgdmF...` (very long, find it in f12 under debugger > (no domain) > copy source uri)
