### ISSUE TITLE
schs.schoolloop.com: ads

### ISSUE THREAD

**Issue by VasGamez** [uBlockOrigin/uAssets#10739]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://schs.schoolloop.com/portal/student_home`

### Category

ads

### Describe the issue

Didn't remove the add

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/87151671/144732449-cd6e08a8-b5bd-4006-b744-51a68d1d7986.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 77683
  cosmetic: 39189
  scriptlet: 16117
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30283-28, never
    ublock-badware: 3494-1, never
    ublock-privacy: 183-0, never
    ublock-abuse: 74-0, never
    ublock-unbreak: 1707-0, never
    easylist: 60746-530, never
    easyprivacy: 25518-212, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 303
  launchFromSelfie: false
popupPanel: 
  blocked: 1
```
</details>

**Comment by LikesHisComputer** [comment]
Do you have the `Fanboy's Annoyance` filter list enabled?

**Comment by mapx-** [comment]
`never` updated ?
