### ISSUE TITLE
linkshrink.net [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1074]
URL(s) where the issue occurs

http://linkshrink.net/70irAL#

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
Pop-ups again 
Linkshrink.net/9bxhn#

Using Firefox 59

**Comment by mapx-** [comment]
`Link does not exist.`

**Comment by ghajini** [comment]
`http://linkshrink.net/7I14Wo#`
Click on `continue`

Firefox 59

**Comment by mapx-** [comment]
`||linkshrink.net^$popunder`

**Comment by ghajini** [comment]
that easylist filter opens popunders in new window .....

how to prevent this script from executing at all

> `</script><script>document.getElementById("btd").onclick = function(){window.open(revC("NU1MeTA="), '_blank');document.location.href = "http://ads.linkshrink.net/dp4j";}</script>`

**Comment by ghajini** [comment]
Ads are back
`http://linkshrink.net/7Lot3I#`
Clicking on `continue` leads to popups
Firefox Android 64/ublock origin 1.17.4.....

**Comment by mapx-** [comment]
On my side (Desktop) the popups are closed by 
`||linkshrink.net^$popunder`

**Comment by ghajini** [comment]
Original tab is closed and new tab(with ads) opened
![screenshot_2019-01-18-23-42-42-591_org mozilla firefox](https://user-images.githubusercontent.com/20338483/51404961-da925b80-1b4c-11e9-8d9f-6af70a7f132e.png)

**Comment by ghajini** [comment]
View page sourceon my side
`https://anotepad.com/notes/8e9xbg`

**Comment by mapx-** [comment]
test
```
linkshrink.net##+js(abort-on-property-read.js, result)
*$popup,domain=linkshrink.net,3p
```

**Comment by mapx-** [comment]
for android is served a different page, so you could try directly
```
!#if env_mobile
linkshrink.net##+js(abort-on-property-read.js, open)
linkshrink.net##+js(abort-on-property-read.js, result)
*$popup,domain=linkshrink.net,3p
!#endif
```

**Comment by mapx-** [comment]
Did you test the last filters ?

**Comment by ghajini** [comment]
Your last set of filters work....
this also works good 

linkshrink.net##+js(window.open-defuser.js)

**Comment by mapx-** [comment]
yep, open-defuser is blocking the click on desktop, so we need conditioning it by env_mobile
