### ISSUE TITLE
streamtape.com: breakage

### ISSUE THREAD

**Issue by headcreep** [uBlockOrigin/uAssets#10749]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://streamtape.com/v/VoYDgQpYDGUKJ99/UFC.on.ESPN.31.Font.vs.Aldo.Prelims.WEB-DL.H264-FBB.mp4?af_v=1638690299087`

### Category

breakage

### Describe the issue

video file fails to stream

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78292
  cosmetic: 39351
  scriptlet: 16180
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61371-6, 2d.15h.3m
    easyprivacy: 26407-17, 2d.15h.3m
    plowe-0: 3629-735, never
    ublock-abuse: 74-0, 2d.15h.2m
    ublock-badware: 3508-59, 2d.15h.2m
    ublock-filters: 29788-119, 2d.15h.2m
    ublock-privacy: 191-1, 2d.15h.2m
    ublock-unbreak: 1699-38, 2d.15h.2m
    urlhaus-1: 8276-0, 5h.59m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 551
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by ghajini** [comment]
click multiples times on play button with default settings

**Comment by headcreep** [comment]
doesn't work

**Comment by xfisbest** [comment]
i got same issue, streamtape doesnt work with ublock, while i tried another adblock and it worked. Might be a filter issue..

**Comment by gorhill** [comment]
No breakage with default settings and up to date lists and uBO as the only extensions.

**Comment by xfisbest** [comment]
> No breakage with default settings and up to date lists and uBO as the only blocker.

i am also using uBO only all other extensions are disabled. but still not work, tried clearing cache and etc.. but uBO got issues

**Comment by uBlock-user** [comment]
Reset to default settings and then try again. The issue is on your end, you will need to investigate why this happens.

**Comment by xfisbest** [comment]
> Reset to default settings and then try again. The issue is on your end, you will need to investigate why this happens.

Found the issue, disabling vpn application.

**Comment by gorhill** [comment]
> i tried another adblock and it worked.

> Found the issue, disabling vpn application.

**Comment by xfisbest** [comment]
> > i tried another adblock and it worked.
> 
> > Found the issue, disabling vpn application.

That might sound weird but yea that is really what happened. Only a specific adblocker was able to play video most of the popular ones were also unable to play video  the only fix for popular ones was disabling vpn.
