### ISSUE TITLE
persianhive.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10740]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://persianhive.com/homepage`

### Describe the issue

Site detects content blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/144733596-9cf8145f-a143-4502-86ac-0e689fb4a1aa.png)

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Settings

N/A

### Notes

N/A

**Comment by LikesHisComputer** [comment]
Is `persianhive.com##+js(no-xhr-if, adsbygoogle)` a good filter?

**Comment by Mennaruuk** [comment]
> Is `persianhive.com##+js(no-xhr-if, adsbygoogle)` a good filter?

It works! Thank you.
