### ISSUE TITLE
[nsfw] 22pixx.xyz: breakage

### ISSUE THREAD

**Issue by iHaired** [uBlockOrigin/uAssets#10757]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://22pixx.xyz/x-o/2021/12/05/61acc3a8208cb.jpeg.html`

### Category

breakage

### Describe the issue

No preview with UBO enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 127370
  cosmetic: 174349
  scriptlet: 32114
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1289-0, 1d.48m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29950-101, 1d.23h.46m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter.txt: 24-0, 3d.3h.54m
    https://www.i-dont-care-about-cookies.eu/abp/: 24119-3, 4h.56m
    adguard-generic: 61995-879, 1d.23h.44m
    adguard-spyware: 25293-914, 1d.23h.48m
    adguard-spyware-url: 397-20, 1d.50m
    block-lan: 44-0, 29d.12h.23m
    fanboy-annoyance: 59030-8483, 5d.2h.16m
    fanboy-cookiemonster: 20436-20436, 5d.2h.14m
    ublock-annoyances: 4318-165, 1d.4h.52m
  default: 
    RUS-0: 40089-3752, 8h.58m
    easylist: 61408-925, 1d.23h.42m
    ublock-abuse: 74-2, 1d.23h.40m
    ublock-badware: 3508-186, 1d.23h.38m
    ublock-filters: 29803-2907, 1d.23h.36m
    ublock-privacy: 193-29, 1d.23h.34m
    ublock-unbreak: 1699-101, 1d.23h.32m
    urlhaus-1: 8276-0, 12h.1m
filterset (user): [array of 968 redacted]
trustedset: 
  added: [array of 911 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 31 redacted]
hostRuleset: 
  added: [array of 206 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  dynamicFilteringEnabled: true
  firewallPaneMinimized: false
  prefetchingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  uiTheme: dark
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 496
  launchFromSelfie: true
popupPanel: 
  blocked: 14
```
</details>

**Comment by iam-py-test** [comment]
Can not reproduce the issue with updated filters with clean install of uBo on a VM. 
I would strongly recommend you avoid this website as my firewall kept blocking requests to malware domains originating from that website
