### ISSUE TITLE
[nsfw] camstreams.tv: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#10758]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://camstreams.tv/videos/225040/alicialusty-3/`

### Category

ads

### Describe the issue

ads at the beginning of the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Webaufnahme_5-12-2021_16827_camstreams tv](https://user-images.githubusercontent.com/81616288/144752256-2e50abf6-62ed-4613-b321-5d69fe277c0d.jpeg)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 80032
  cosmetic: 42268
  scriptlet: 16221
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 4951-0, 4h.8m
    easylist: 61123-12, 4h.8m
    easyprivacy: 26434-28, 4h.8m
    plowe-0: 3696-812, 4h.8m
    ublock-abuse: 72-0, 4h.8m
    ublock-badware: 3509-59, 4h.8m
    ublock-filters: 29788-131, 4h.8m
    ublock-privacy: 192-2, 4h.8m
    ublock-unbreak: 1704-39, 4h.8m
    urlhaus-1: 8276-0, 4h.8m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 8248
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by No-ADS** [comment]
<details>

![1](https://user-images.githubusercontent.com/94611448/144803865-4953dc33-c545-45c5-bce6-da37267ba065.gif)
<summary>Screen</summary>
</details>
