### ISSUE TITLE
[suggestion] create a anti-feature list

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#1075]
https://github.com/uBlockOrigin/uAssets/issues/1069

this block was put in the annoyance list, but annoyance is most for cookie banners and social buttons

a anti-feature list it could be a different set of block, just for things how limit and restrict navigation and violate user rights.

**Comment by jspenguin2017** [comment]
I have a filter designed to deal with things like that: https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFilters/NanoAnnoyance.txt
