### ISSUE TITLE
indiatoday.in: ads

### ISSUE THREAD

**Issue by blogmangit** [uBlockOrigin/uAssets#10750]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.indiatoday.in/amp/technology/news/story/if-you-have-used-zoom-between-2016-and-2021-you-are-eligible-to-get-rs-1874-from-the-company-1883728-2021-12-03`

### Category

ads

### Describe the issue

empty spaces are present in the webpage specially on mobile amp pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium Mobile: 96
filterset (summary): 
  network: 85450
  cosmetic: 117790
  scriptlet: 21130
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48105-141, 21h.15m
    adguard-social: 14810-770, 21h.15m
    fanboy-cookiemonster: 20445-2234, 21h.15m
    ublock-annoyances: 4338-250, 21h.15m
  default: 
    adguard-mobile: 7022-18, 22h
    easylist: 61061-217, 21h.58m
    easyprivacy: 26427-119, 21h.58m
    plowe-0: 3695-900, 21h.58m
    ublock-abuse: 74-0, 21h.58m
    ublock-badware: 3532-63, 21h.58m
    ublock-filters: 29917-449, 21h.58m
    ublock-privacy: 197-4, 21h.58m
    ublock-unbreak: 1708-41, 21h.58m
    urlhaus-1: 8315-0, 21h.58m
filterset (user): [array of 75 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1317
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
I see no such leftovers, screenshot ?

**Comment by blogmangit** [comment]
sorry my bad I wrongfully reported issue from wrong page closing this issue now. Sorry guys very much.
