### ISSUE TITLE
peoplesphere.be: ads

### ISSUE THREAD

**Issue by draxaris1010** [uBlockOrigin/uAssets#10754]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://peoplesphere.be/`

### Category

ads

### Describe the issue

I still see ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 81150
  cosmetic: 54853
  scriptlet: 18892
  html: 608
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4328-5, 2d.21h.3m
    adguard-social: 14791-13, 2d.21h.15m
    adguard-spyware-url: 394-1, 2d.21h.1m
  default: 
    ublock-filters: 30338-33, 2d.21h.9m
    ublock-badware: 3512-1, 2d.22h.11m
    ublock-privacy: 187-0, 2d.21h.7m
    ublock-abuse: 74-0, 2d.21h.5m
    ublock-unbreak: 1710-0, 2d.21h.17m
    easylist: 61360-547, 2d.21h.13m
    easyprivacy: 26407-475, 2d.21h.11m
    plowe-0: 3698-3, 3d.17h.52m
    urlhaus-1: 9915-0, 19h.1m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
hostRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5510
  launchFromSelfie: true
popupPanel: 
  blocked: 10
```
</details>

**Comment by gorhill** [comment]
Subscribe to _"NLD: EasyList Dutch"_ in _"Filter lists"_ pane under _"Regions, languages"_ section.

**Comment by BPower0036** [comment]
@draxaris1010 or subscribe to _"[EasyDutch](https://github.com/BPower0036/AdBlockFilters/)"_
