### ISSUE TITLE
ndtv.com: ads

### ISSUE THREAD

**Issue by blogmangit** [uBlockOrigin/uAssets#10755]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.ndtv.com/entertainment/money-heist-season-5-volume-2-review-the-series-does-not-let-you-take-your-eyes-off-the-screen-for-a-second-4-stars-2636701/amp/1`

### Category

ads

### Describe the issue

Blank spaces & jio widget ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/mc5JsSU.jpeg
https://i.imgur.com/pymG0Qd.jpeg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium Mobile: 96
filterset (summary): 
  network: 79618
  cosmetic: 44678
  scriptlet: 16292
  html: 0
listset (total-discarded, last updated): 
  default: 
    adguard-mobile: 7023-16, 13m
    easylist: 61123-179, 13m
    easyprivacy: 26434-26, 13m
    plowe-0: 3696-900, 13m
    ublock-abuse: 72-0, 13m
    ublock-badware: 3509-59, 12m
    ublock-filters: 29883-136, 12m
    ublock-privacy: 192-2, 12m
    ublock-unbreak: 1710-38, 12m
    urlhaus-1: 8445-0, 12m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 926
  launchFromSelfie: true
popupPanel: 
  blocked: 34
```
</details>

**Comment by mapx-** [comment]
test

```
ndtv.com##.inline.ads
ndtv.com##.tbl-wrp:has(.i-amphtml-fill-content)
```

**Comment by blogmangit** [comment]
> test
> 
> ```
> ndtv.com##.inline.ads
> ndtv.com##.tbl-wrp:has(.i-amphtml-fill-content)
> ```
> 

thanks man it's working just tell me one thing that you can find this on your PC or laptop right  ? but never on mobile because no browser on mobile supports dev tool except kiwi browser & that too is useless because it open a separate tab for the site.

**Comment by mapx-** [comment]
I used the picker to get the cosmetic filter (in BlueStacks)
