### ISSUE TITLE
hindustantimes.com: ads

### ISSUE THREAD

**Issue by blogmangit** [uBlockOrigin/uAssets#10751]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.hindustantimes.com/lifestyle/health/lesserknown-habits-of-depressed-people-they-hide-from-the-world-101638623469728-amp.html`

### Category

ads

### Describe the issue

Blank spaces & ads leftover. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/gallery/tUZFsVp

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox Mobile: 96
filterset (summary): 
  network: 79443
  cosmetic: 44674
  scriptlet: 16252
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30436-43, 25m
    ublock-badware: 3513-1, 25m
    ublock-privacy: 188-0, 25m
    ublock-abuse: 72-0, 24m
    ublock-unbreak: 1721-0, 24m
    adguard-mobile: 7023-156, 25m
    easylist: 61115-670, 24m
    easyprivacy: 26434-483, 24m
    urlhaus-1: 8276-0, 24m
    plowe-0: 3696-3, 24m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2663
  launchFromSelfie: false
popupPanel: 
  blocked: 8
```
</details>

**Comment by uBlock-user** [comment]
Did you disable _Ignore generic cosmetic filters_ on Firefox Mobile ?

**Comment by mapx-** [comment]
Leftovers on desktop too.

@blogmangit 

test
```
hindustantimes.com##.new_ads_unit
hindustantimes.com##.i-amphtml-unresolved
hindustantimes.com##.top250Ad
hindustantimes.com##.amp-push-notification
hindustantimes.com##[amp-access^="NOT"]
```

@ryanbr 
@Yuki2718

**Comment by blogmangit** [comment]
> Leftovers on desktop too.
> 
> @blogmangit 
> 
> test
> ```
> hindustantimes.com##.new_ads_unit
> hindustantimes.com##.i-amphtml-unresolved
> hindustantimes.com##.top250Ad
> hindustantimes.com##.amp-push-notification
> hindustantimes.com##[amp-access^="NOT"]
> ```
> 
> @ryanbr 
> @Yuki2718 
> 

Thanks a lot man I understood everything except the last line

hindustantimes.com##[amp-access^="NOT"]

can u elaborate  the [amp-access^="NOT"] part please ?

**Comment by mapx-** [comment]
> ^="NOT" means starts with NOT right ?

exactly

**Comment by blogmangit** [comment]
> > ^="NOT" means starts with NOT right ?
> 
> exactly

then what is [amp-access] part I am curious about that part sorry I m newbie here .

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/144746201-bd93734b-6b33-4859-b2dd-dc939024a131.png)

**Comment by blogmangit** [comment]
> ![image](https://user-images.githubusercontent.com/10303732/144746201-bd93734b-6b33-4859-b2dd-dc939024a131.png)
> 

that's the dom inspector right actually I cannot get that because I m on firefox mobile with ublock extension

**Comment by gorhill** [comment]
See <https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors>.

**Comment by Yuki2718** [comment]
@mapx- I'll wait for Ryan's fix.
