### ISSUE TITLE
[nsfw] filma24.gg: ads

### ISSUE THREAD

**Issue by TrOJA1000** [uBlockOrigin/uAssets#10762]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.filma24.gg/`

### Category

ads

### Describe the issue

When I'm click anywhere on the website I start to hear the sound of ads and constantly open others popups on clicking inside of player or movies photo. 
Please uBlockOrigin team fix this issue. Thanks for your excellent work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details

>
https://user-images.githubusercontent.com/95584326/144757937-aa3c7d81-fafb-4c17-87a8-f05f30524476.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 141643
  cosmetic: 169878
  scriptlet: 33790
  html: 607
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    plowe-0: null
  added: 
    https://austinhuang.me/0131-block-list/list.txt: 98-0, 1d.21h.53m
    https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 19h.5m
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1957-7, 19h.7m
    https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2641-20, 1d.21h.47m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-2043, 19h.3m
    https://www.fanboy.co.nz/enhancedstats.txt: 2993-1963, 1d.21h.49m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 19h.9m
    adguard-generic: 61942-4158, 3d.18h.17m
    adguard-mobile: 7015-70, 3d.18h.15m
    adguard-spyware: 25263-1027, 19h.17m
    adguard-annoyance: 48112-3769, 19h.13m
    adguard-social: 14790-40, 3d.18h.33m
    fanboy-thirdparty_social: 68-0, 6d.20h.9m
    fanboy-annoyance: 59001-44225, 6d.20h.5m
    fanboy-cookiemonster: 20425-121, 6d.20h.7m
    fanboy-social: 23215-1083, 3d.18h.31m
    ublock-annoyances: 4327-11, 3d.18h.29m
    dpollock-0: 16968-1487, 3d.23h.27m
    mvps-0: 8730-3, 10d.14h.37m
    RUS-0: 40090-540, 19h.11m
  default: 
    ublock-filters: 30307-123, 3d.18h.27m
    ublock-badware: 3512-1, 3d.18h.25m
    ublock-privacy: 183-0, 3d.18h.23m
    ublock-abuse: 74-0, 3d.18h.21m
    ublock-unbreak: 1709-4, 3d.18h.19m
    easyprivacy: 26427-10925, 19h.15m
    urlhaus-1: 8250-0, 19h.1m
filterset (user): [array of 102 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 49 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1418
  launchFromSelfie: true
popupPanel: 
  blocked: 30
  no-popups: true
```
</details>

**Comment by mapx-** [comment]
You should reset uBO to the default settings then update all your lists.

You have a list from ABP completely useless. I guess many other which could trigger various conflicts.

**Comment by mapx-** [comment]
You already opened an issue for the same site (already fixed)
https://github.com/uBlockOrigin/uAssets/issues/10761

**Comment by TrOJA1000** [comment]
Okay, I will do that. Thanks sir.
