### ISSUE TITLE
[nsfw] machotube.tv: ads

### ISSUE THREAD

**Issue by swt1025** [uBlockOrigin/uAssets#10767]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.machotube.tv/movies/1195358/cole-cash-and-max-summerfield`

### Category

ads

### Describe the issue

blank advertisement box re pops up every refresh no matter what you do to zap it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

`https://user-images.githubusercontent.com/41227980/144763301-15a4f702-19ec-499c-ae95-61193cc6ae91.png`
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 153820
  cosmetic: 142226
  scriptlet: 32141
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48115-141, 3m
    adguard-generic: 62006-666, 3m
    adguard-social: 14812-770, 3m
    adguard-spyware: 25263-683, 3m
    adguard-spyware-url: 397-12, 3m
    block-lan: 44-0, 3m
    curben-phishing: 22180-0, 3m
    curben-pup: 373-0, 3m
    dpollock-0: 16978-187, 2m
    fanboy-cookiemonster: 20450-2234, 3m
    fanboy-thirdparty_social: 69-3, 3m
    ublock-annoyances: 4318-276, 3m
  default: 
    easylist: 61144-1027, 2m
    easyprivacy: 26436-10909, 2m
    plowe-0: 3696-1283, 2m
    ublock-abuse: 72-0, 2m
    ublock-badware: 3509-180, 2m
    ublock-filters: 29850-3185, 2m
    ublock-privacy: 191-29, 2m
    ublock-unbreak: 1704-106, 2m
    urlhaus-1: 8445-5, 2m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1449
  launchFromSelfie: false
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
add

```
machotube.tv##.ae-player__itv-spot
machotube.tv##.ae-player__itv
machotube.tv##.b-randoms-col
```

@ryanbr
