### ISSUE TITLE
onlinebanking.usbank.com: breakage

### ISSUE THREAD

**Issue by brij1234** [uBlockOrigin/uAssets#10763]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://onlinebanking.usbank.com/TUX/public/index.html`

### Category

breakage

### Describe the issue

Broken website with ublock enabled. Works when I disable it. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211205-131511](https://user-images.githubusercontent.com/9251787/144758421-7bdb65cc-bba1-42b7-8440-68ac164e1363.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox Mobile: 94
filterset (summary): 
  network: 79205
  cosmetic: 21122
  scriptlet: 16217
  html: 603
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30462-193, 1d.15h.7m
    ublock-badware: 3512-2, 1d.15h.5m
    ublock-privacy: 193-1, 1d.15h.3m
    ublock-abuse: 74-0, 1d.15h.1m
    ublock-unbreak: 1719-0, 1d.14h.59m
    adguard-mobile: 7022-172, 1d.15h.16m
    easylist: 61059-24047, 1d.14h.57m
    easyprivacy: 26427-482, 1d.14h.55m
    urlhaus-1: 8032-0, 12h.15m
    plowe-0: 3695-3, 1d.14h.50m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 387
  launchFromSelfie: true
popupPanel: 
  blocked: 8
```
</details>

**Comment by mapx-** [comment]
Difficult to test without an account.

However, at a first glance ..test this exception:

`@@||onlinebanking.usbank.com/TUX/public/libs/adobe/appmeasurement.js$1p`

**Comment by brij1234** [comment]
> Difficult to test without an account.
> 
> However, at a first glance ..test this exception:
> 
> `@@||onlinebanking.usbank.com/TUX/public/libs/adobe/appmeasurement.js$1p`

Yep that works!

**Comment by mapx-** [comment]
@ryanbr

**Comment by LikesHisComputer** [comment]
It looks like this issue can be closed.
