### ISSUE TITLE
heise.de: nuisance

### ISSUE THREAD

**Issue by lazios** [uBlockOrigin/uAssets#10766]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.heise.de/`

### Category

nuisance

### Describe the issue

Cookie Popup: "heise online mit Werbung und Cookies nutzen" appears and isn't blocked.

![image](https://user-images.githubusercontent.com/92884195/144759908-8ee4330b-e4f5-4def-8290-d9134db1a8ce.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 650611
  cosmetic: 181826
  scriptlet: 32210
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 38m
    https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts: 138792-92, 38m
    https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt: 409528-8979, 38m
    adguard-annoyance: 48115-150, 38m
    adguard-generic: 62006-960, 38m
    adguard-mobile: 7028-599, 38m
    adguard-social: 14812-773, 38m
    adguard-spyware: 25263-13424, 38m
    adguard-spyware-url: 397-12, 38m
    block-lan: 44-0, 38m
    dpollock-0: 16978-16973, 38m
    fanboy-annoyance: 59047-3921, 38m
    fanboy-cookiemonster: 20446-20446, 38m
    fanboy-social: 23213-23213, 38m
    fanboy-thirdparty_social: 69-21, 38m
    mvps-0: 8730-8730, 38m
    ublock-annoyances: 4318-287, 38m
  default: 
    DEU-0: 4951-2, 38m
    easylist: 61142-1918, 38m
    easyprivacy: 26434-12653, 38m
    plowe-0: 3696-3692, 38m
    ublock-abuse: 72-0, 38m
    ublock-badware: 3509-207, 38m
    ublock-filters: 29847-3220, 38m
    ublock-privacy: 191-37, 38m
    ublock-unbreak: 1704-109, 38m
    urlhaus-1: 8445-791, 38m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 762
  launchFromSelfie: true
popupPanel: 
  blocked: 7
```
</details>

**Comment by LikesHisComputer** [comment]
@ryanbr

**Comment by okiehsch** [comment]
It's a GDPR modal, if you block it it will break videos on the site.
To block add
`||cmp.heise.de/wrapperMessagingWithoutDetection.js$script,1p`

Site with broken video functionality.
`https://www.heise.de/meinung/Star-Trek-Discovery-Die-vierte-Staffel-muss-man-sich-nicht-antun-6284754.html`
Scroll down you should see a video right above "Dialoge zum Fremdschämen".

**Comment by No-ADS** [comment]
> Site with broken video functionality.
> `https://www.heise.de/meinung/Star-Trek-Discovery-Die-vierte-Staffel-muss-man-sich-nicht-antun-6284754.html`
> Scroll down, you should see a video right above "Dialoge zum Fremdschämen".

Works for me
`heise.de##[id^="sp_message_container_"]:remove()`
`heise.de##+js(ra, data-consentmanagement)`

**Comment by Yuki2718** [comment]
On AG it's already fixed by a script filter, so probably I won't fix in AG Annoyance.

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/96137
