### ISSUE TITLE
valadoc.org: breakage

### ISSUE THREAD

**Issue by laurinneff** [uBlockOrigin/uAssets#10764]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://valadoc.org/libadwaita-1/Adw.html`

### Category

breakage

### Describe the issue

If you click any link other than the ones in the navbar, `Packages`, or `libadwaita-1`, you get an error because uBlock Origin is blocking the request. I'm guessing this is because of the `ad` in `libadwaita`.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78136
  cosmetic: 39362
  scriptlet: 16173
  html: 599
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30326-30, 16h.9m
    ublock-badware: 3513-1, 16h.7m
    ublock-privacy: 193-0, 16h.5m
    ublock-abuse: 74-0, 16h.3m
    ublock-unbreak: 1714-0, 16h.1m
    easylist: 61077-547, 15h.59m
    easyprivacy: 26433-474, 15h.57m
    urlhaus-1: 8445-0, 3h.55m
    plowe-0: 3697-3, 6d.22h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 812
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by gorhill** [comment]
It's because of the filter `/adw.$domain=~adw.be|~adw.olsztyn.pl|~adw.org|~adw.org.pl` in EasyList -- this needs to be fixed in EasyList.

cc @ryanbr

**Comment by LikesHisComputer** [comment]
It looks like this issue can be closed.
