### ISSUE TITLE
mconverter.eu: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#10779]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://mconverter.eu/`

### Category

detection

### Describe the issue

Page show anti-adblock section and limit convert tries form free ten to only two (or this is poor paywall).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![MConverter](https://user-images.githubusercontent.com/35370833/144915403-c6f84b88-afb3-4150-85f7-66d94d258947.png)

![obraz](https://user-images.githubusercontent.com/35370833/144915520-a96d8c32-f756-425a-bf7c-db15bd1881f1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 174966
  cosmetic: 122220
  scriptlet: 19350
  html: 872
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24119-143, 21h.54m
    adguard-spyware-url: 395-1, 3d.23h
    block-lan: 44-0, 8d.1h.35m
    fanboy-social: 23213-21, 3d.22h.56m
    ublock-annoyances: 4328-7, 3d.22h.54m
  default: 
    ublock-filters: 30345-75, 3d.23h.12m
    ublock-badware: 3512-1, 3d.23h.10m
    ublock-privacy: 187-0, 3d.23h.8m
    ublock-abuse: 74-0, 3d.23h.6m
    ublock-unbreak: 1710-0, 3d.23h.4m
    easylist: 61371-592, 3d.23h.2m
    easyprivacy: 26407-476, 3d.22h.58m
    urlhaus-1: 8674-0, 48m
    plowe-0: 3697-3, 8d.1h.35m
    POL-0: 7680-32, 47m
    POL-2: 1276-9, 21h.51m
filterset (user): [array of 117 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: null
  extensionUpdateForceReload: true
  filterAuthorMode: true
  popupPanelLockedSections: 32
  strictBlockingBypassDuration: 30
  uiTheme: light
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 1072
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by iam-py-test** [comment]
Wait, are you using Firefox?
Try disabling Tracking Protection on that site, clearing your cookies, and reloading - that got rid of it

**Comment by krystian3w** [comment]
For my works click in Blue power button: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button

Also my Firefox 🛡️ now block only fingerpints.

**Comment by iam-py-test** [comment]
> For my works (helps) click in Blue power button: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button
> 
> Also my Firefox 🛡️ now block only fingerpints (1-2 years).

Mine is set to Strict, however, even when set to the normal mode, I still can reproduce.

**Comment by krystian3w** [comment]
Maybe page is broken due pity track detection whole content blockers (DNS/VPN/HOSTS/addons).

For my is only scary text:

> get more 8 converts after disable adblocking

> (or 2 if you block ads)

Then this is not soft anti-adblock to fix only in `annoyances.txt`

**Comment by iam-py-test** [comment]
`mconverter.eu#@#.adsbygoogle` seems to fix the issue

**Comment by krystian3w** [comment]
@olegwukr try check these - may need disable too:

`##[id^="aswift_"]` 
`##iframe[id^="google_ads_frame"]`


(use in Pole list) - both are is used to hide if `##.adsbygoogle` fails.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13518
