### ISSUE TITLE
docer.pl: breakage

### ISSUE THREAD

**Issue by walti0** [uBlockOrigin/uAssets#10775]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [x] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://docer.pl/doc/e5s8sx` 
`https://doci.pl/marcin/muzykoterapia-jako-element-wspomagajcy-rozwj-psychofizyczny-dzieci-w-klasie-integracyj+fe885x`

### Category

breakage

### Describe the issue

When ublock working i cant download any file on both sites(links to random files not to home page to be easier to you), download button just don't react I tested on adguard and it works fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 95
filterset (summary): 
  network: 141230
  cosmetic: 228669
  scriptlet: 50610
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt: 42713-16, 21h.13m
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt: 127545-18255, 21h.14m
    https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt: 20785-52, 1d.31m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 26983-38, 1d.27m
    https://www.i-dont-care-about-cookies.eu/abp/: 24119-144, 1d.35m
    adguard-annoyance: 48115-2117, 1d.46m
    adguard-generic: 62006-47558, 1d.44m
    adguard-social: 14812-771, 1d.50m
    fanboy-annoyance: 59047-11372, 1d.1h.7m
    fanboy-cookiemonster: 20446-20446, 1d.1h.10m
    fanboy-social: 23213-23213, 1d.48m
    fanboy-thirdparty_social: 68-21, 1d.59m
    ublock-annoyances: 4318-322, 1d.52m
  default: 
    POL-0: 7675-213, 1d.25m
    POL-2: 1273-149, 1d.33m
    easylist: 61142-61112, 1d.42m
    easyprivacy: 26434-3098, 1d.40m
    plowe-0: 3697-1618, 7d.1h.28m
    ublock-abuse: 72-1, 1d.37m
    ublock-badware: 3509-183, 1d.1h.3m
    ublock-filters: 29809-6611, 1d.1h.1m
    ublock-privacy: 190-18, 1d.57m
    ublock-unbreak: 1703-99, 1d.54m
    urlhaus-1: 8445-0, 1d.29m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 693
  launchFromSelfie: true
popupPanel: 
  blocked: 14
```
</details>

**Comment by krystian3w** [comment]
@majkiit / @olegwukr

**Comment by krystian3w** [comment]
In AG may works by AdamWr hotfix added into AdGuard Base.

**Comment by mapx-** [comment]
@gorhill

**Comment by gwarser** [comment]
On `docer` download work for me on Chrome stable default lists.
