### ISSUE TITLE
canale.live: detection

### ISSUE THREAD

**Issue by andreineaga** [uBlockOrigin/uAssets#10770]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://canale.live/`

### Category

detection

### Describe the issue

pop-up anti adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.0
Firefox Mobile: 92
filterset (summary): 
  network: 83277
  cosmetic: 27486
  scriptlet: 16259
  html: 603
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 20404-12784, 2d.5h.33m
  default: 
    ublock-filters: 30468-201, 2d.5h.31m
    ublock-badware: 3499-2, 6d.5h.54m
    ublock-privacy: 183-1, 6d.5h.51m
    ublock-abuse: 74-0, 6d.5h.42m
    ublock-unbreak: 1706-0, 6d.5h.48m
    adguard-mobile: 7009-173, 6d.5h.33m
    easylist: 61277-24040, 6d.5h.38m
    easyprivacy: 26387-495, 6d.5h.35m
    urlhaus-1: 10040-0, 6d.1h.27m
    plowe-0: 3699-3, 12d.8h.38m
    ROU-1: 753-27, 6d.5h.30m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1668
  launchFromSelfie: false
```
</details>

**Comment by MasterKia** [comment]
Add these to **my filters** and report back:
```
@@||cdn.casamireasa.biz/deploys/www/delivery/loader.gif$image,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/js/footer.js$script,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/prog.css?id=now,next,more&v6$stylesheet,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/js/core.js$script,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/js/libs/jquery-3.5.1.min.js$script,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/css/reset.min.css$stylesheet,domain=canale.live
@@||cdn.casamireasa.biz/deploys/www/delivery/css/style.min.css$stylesheet,domain=canale.live
@@||canale.live/reclama/css/fonts.min.css$stylesheet,1p
@@||canale.live/reclama/fonts/share.woff$font,1p
@@||canale.live/player-tv/live/reclama/*.css$stylesheet,1p
@@||canale.live/reclama/ftv/?id=*$subdocument,1p

canale.live##+js(set, isBlocked, false)
canale.live##+js(set, google_tag_data, true)
@@||eplayer.click/reclama/ads.js?ad=ads$script,domain=canale.live
```

**Comment by LikesHisComputer** [comment]
channels don't seem to be working
