### ISSUE TITLE
indianexpress.com: breakage

### ISSUE THREAD

**Issue by onibon007** [uBlockOrigin/uAssets#10778]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://indianexpress.com/article/trending/trending-in-india/mutton-or-me-husband-asks-wife-to-make-a-choice-7652408/lite/`

### Category

breakage

### Describe the issue

The article is missing after the first paragraph when ublock is on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium Mobile: 96
filterset (summary): 
  network: 79896
  cosmetic: 21149
  scriptlet: 16313
  html: 0
listset (total-discarded, last updated): 
  default: 
    adguard-mobile: 7023-32, 1d.11h.4m
    easylist: 61142-23555, 1d.1h.18m
    easyprivacy: 26437-26, 10h.34m
    plowe-0: 3695-899, 2d.3h.26m
    ublock-abuse: 72-0, 11h.4m
    ublock-badware: 3509-60, 11h.7m
    ublock-filters: 29951-290, 21m
    ublock-privacy: 191-2, 9h.38m
    ublock-unbreak: 1710-38, 19m
    urlhaus-1: 8674-0, 17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1602
  launchFromSelfie: false
popupPanel: 
  blocked: 8
```
</details>

**Comment by gorhill** [comment]
Looks like the site needs `https://cdn.ampproject.org/v0/amp-geo-0.1.js`, which is blocked by EasyPrivacy's `/amp-geo-` cc @ryanbr

**Comment by krystian3w** [comment]
So unbreak no longer added falback to reduce breakage?

**Comment by ryanbr** [comment]
Filter was removed in an unrelated commit

**Comment by onibon007** [comment]
works great, thank you!
