### ISSUE TITLE
anti adblock

### ISSUE THREAD

**Issue by sikari0** [uBlockOrigin/uAssets#1077]
### URL(s) where the issue occurs

http://leetgram.com/
http://abliker.com/
http://fbfriendrequest.com/
http://igzoom.com/
http://www.devliker.com/
http://www.devliker.net/
http://www.kpliker.com/
http://www.likesgroup.com/
https://www.igflash.com/

### Describe the issue

anti adblock

### Screenshot(s)

![](http://i.imgur.com/Tgae2US.png)

### Versions

- Browser/version: chrome v63
- uBlock Origin version: v1.14.22

### Settings

- default settings

**Comment by okiehsch** [comment]
Can not reproduce with `http://www.devliker.com`, fixed all other domains.
