### ISSUE TITLE
Chinese `bilibili.com` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#10776]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bilibili.com/video/BV1zq4y1z7mR` --> `web-player-tracker.biliapi.net`

```
||web-player-tracker.biliapi.net^
```

### Describe the issue

`https://www.bilibili.com/video/BV1zq4y1z7mR` --> `web-player-tracker.biliapi.net`

```
||web-player-tracker.biliapi.net^
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/75058881/144896147-89231d4f-3fd4-44cc-a9d2-d58e749da56f.png)

### uBlock Origin version

n/a

### Browser name and version

edge latest beta ver

### Settings

n/a

**Comment by mapx-** [comment]
it could be added to EasyPrivacy, right ?

@ryanbr

**Comment by Yuki2718** [comment]
It's not tracker.
