### ISSUE TITLE
coinpayu.com: detection

### ISSUE THREAD

**Issue by LikesHisComputer** [uBlockOrigin/uAssets#10781]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.coinpayu.com/dashboard`

### Category

detection

### Describe the issue

anti adb
an account may be required in order to reproduce the anti adb

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78626
  cosmetic: 39394
  scriptlet: 16245
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61286-6, 1h
    easyprivacy: 26444-17, 1h
    plowe-0: 3697-811, 1h
    ublock-abuse: 72-0, 1h
    ublock-badware: 3539-60, 1h
    ublock-filters: 29858-126, 1h
    ublock-privacy: 192-1, 1h
    ublock-unbreak: 1705-38, 1h
    urlhaus-1: 8674-0, 1h
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 488
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by LikesHisComputer** [comment]
Is `coinpayu.com#@#.ad-link` a good filter?

**Comment by mapx-** [comment]
test case ?

**Comment by LikesHisComputer** [comment]
> test case ?

- an account:
```
username: q3m1jx+13nigx4pqofn4@sharklasers.com
password: parola
```
- logging in
- being redirected to `https://www.coinpayu.com/dashboard`
---

![image](https://user-images.githubusercontent.com/95556652/145661602-d23a3f7a-277b-43e0-a523-8b439a8d5d4c.png)

**Comment by mapx-** [comment]
no issue on my end
