### ISSUE TITLE
myaccount.coxbusiness.com: breakage

### ISSUE THREAD

**Issue by jwdsail** [uBlockOrigin/uAssets#10780]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://myaccount.coxbusiness.com/cbma/unauth/login`

### Category

breakage

### Describe the issue

The "Sign In" button is non-functional when uBlock Origin is active for the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 80261
  cosmetic: 39319
  scriptlet: 16112
  html: 598
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30270-28, 6d.9h.56m
    ublock-badware: 3494-1, 6d.9h.54m
    ublock-privacy: 188-0, 7m
    ublock-abuse: 72-0, 5m
    ublock-unbreak: 1707-0, 6d.9h.58m
    easylist: 61299-545, 6d.9h.52m
    easyprivacy: 26396-473, 6d.9h.50m
    plowe-0: 3700-3, 4d.18h.15m
    urlhaus-1: 10361-0, 5d.7h.24m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2832
  launchFromSelfie: false
popupPanel: 
  blocked: 4
```
</details>

**Comment by gorhill** [comment]
Looks like it's caused by EasyPrivacy's `/newrelic.js` which blocks `https://webcdn.coxbusiness.com/R136/assets/newrelic/newrelic.js`.

cc @ryanbr
