### ISSUE TITLE
Prevent meta refresh sites

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10788]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://legendas.dev/vivarium-2020/`
`https://www.novsport.com/news3211711_1003.html`
`https://www.telesintese.com.br/`

### Describe the issue

These sites have `meta[http-equiv="refresh"]` issue which are solved on Firefox by the filter:

`##^meta[http-equiv="refresh"]`

but since it's not working on chromium, I think we can use `refresh-defuser` for them.

### Screenshot(s)

- `legendas.dev`

![image](https://user-images.githubusercontent.com/66517106/144955431-4361fa24-65b0-47b6-9da8-77fff333d00d.png)

- `novsport.com`

![image](https://user-images.githubusercontent.com/66517106/144955475-af09564e-d37a-4438-a2d3-97716490c803.png)

- `telesintese.com.br`

![image](https://user-images.githubusercontent.com/66517106/144955547-a069221a-2272-4e00-9168-e651af02b2b3.png)

### uBlock Origin version

1.39.2

### Browser name and version

Ungoogled Chromium 96.0.4664.45

### Settings

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78560
  cosmetic: 39411
  scriptlet: 16247
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61311-6, 1m
    easyprivacy: 26456-17, 1m
    plowe-0: 3697-811, 1m
    ublock-abuse: 72-0, 1m
    ublock-badware: 3539-60, 1m
    ublock-filters: 29860-127, 1m
    ublock-privacy: 192-5, 1m
    ublock-unbreak: 1705-38, 1m
    urlhaus-1: 8593-0, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 272
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

### Notes

Proposed filter:

`legendas.dev,novsport.com,telesintese.com.br##+js(refresh-defuser)`

**Comment by uBlock-user** [comment]
@gorhill Seems the exceptor widget in the logger UI doesn't work on HTML filters in the dev build.

STR -- 

1) Browse to `https://www.naturalblaze.com/` in a new tab and open the logger in another.
2) Click on `^script:has-text(/==undefined.*"body".*"body"/)` filter to summon netFilteringDialog box and then click on the exceptor widget
3) Notice filter doesn't get disabled(no strikethrough line over the filter), nothing happens.

**Comment by gorhill** [comment]
Unexpectedly, Firefox adds backslashes to the filter text when accessed through `textContent`:

    /==undefined.*\"body\".*\"body\"/)

As a result uBO can't find that filter. I verified with Chromium and same behavior, quotes in the original text is prepended with backslashes.

**Comment by uBlock-user** [comment]
It's not specific to that filter only, I discovered it here on this case with `##^meta[http-equiv="refresh"]` first.

**Comment by gorhill** [comment]
Ok I don't know why there is a backslashes added, the debugger makes this difficult to spot, this will need more lengthy investigation, and issue should be opened for this.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1861
