### ISSUE TITLE
go.netfile.cc: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10789]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://go.netfile.cc/bFDPjYSUDSb`

### Category

breakage

### Describe the issue

Open link in new Private Window/Incognito. The captcha doesn't display.

Looks like it's caused by this filter in `ublock unbreak`:

```
://ads.$domain=~ads.ac.uk|~ads.adstream.com.ro|~ads.allegro.pl|~ads.am|~ads.amazon|~ads.apple.com|~ads.atmosphere.copernicus.eu|~ads.bestprints.biz|~ads.bigbom.com|~ads.bikepump.com|~ads.brave.com|~ads.buscaempresas.co|~ads.cableidp.jp|~ads.colombiaonline.com|~ads.comeon.com|~ads.cvut.cz|~ads.d2c.ne.jp|~ads.dev.int.revelian.com|~ads.dollartree.com|~ads.elcarado.com|~ads.gambinoslot.com|~ads.google.com|~ads.gree.net|~ads.harvard.edu|~ads.instacart.com|~ads.jiosaavn.com|~ads.kaipoke.biz|~ads.kazakh-zerno.net|~ads.lapalingo.com|~ads.listonic.com|~ads.lordlucky.com|~ads.lviv.ua|~ads.magalu.com|~ads.mba|~ads.microsoft.com|~ads.midwayusa.com|~ads.mobilebet.com|~ads.msstate.edu|~ads.mst.dk|~ads.nc|~ads.nimses.com|~ads.nipr.ac.jp|~ads.odesbuild.com|~ads.olx.pl|~ads.pinterest.com|~ads.quasaraffiliates.com|~ads.red|~ads.route.cc|~ads.safi-gmbh.ch|~ads.selfip.com|~ads.sk|~ads.snapchat.com|~ads.socialtheater.com|~ads.spotify.com|~ads.studyplus.co.jp|~ads.taboola.com|~ads.tiktok.com|~ads.toplayaffiliates.com|~ads.typepad.jp|~ads.viksaffiliates.com|~ads.watson.ch|~ads.xtribeapp.com|~ads.yahoosmallbusiness.com|~badassembly.com|~caravansforsale.co.uk|~fusac.fr|~memo2.nl|~reempresa.org|~satmetrix.com|~seriouswheels.com
```

Whitelisting that filter fixes the issue:

`@@||ads.vidoomy.com^$script,domain=go.netfile.cc`

### Screenshot(s)

<details>
<summary>Screenshot(s) - Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/144959232-0f7ead6e-7d80-4dea-868f-b839b027facd.png)

</details>

<details>
<summary>Screenshot(s) - Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/144959208-4377ea2b-bb0d-4670-b09b-80a5ff2da606.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78562
  cosmetic: 39412
  scriptlet: 16207
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30417-30, 5m
    ublock-badware: 3543-1, 5m
    ublock-privacy: 188-0, 5m
    ublock-abuse: 72-0, 5m
    ublock-unbreak: 1716-0, 5m
    easylist: 61311-552, 5m
    easyprivacy: 26456-478, 5m
    urlhaus-1: 8593-0, 5m
    plowe-0: 3697-3, 5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 275
  launchFromSelfie: true
popupPanel: 
  blocked: 26
```
</details>

**Comment by uBlock-user** [comment]
No breakage spotted, the Recaptcha widget appears as expected.
