### ISSUE TITLE
satoshitron.top

### ISSUE THREAD

**Issue by LikesHisComputer** [uBlockOrigin/uAssets#10785]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://satoshitron.top/links`

### Describe the issue

bab anti adb

### uBlock Origin version

1.39.2

### Browser name and version

Google Chrome 96.0.4664.45 (Official Build) (64-bit)

### Settings

.

**Comment by mapx-** [comment]
specific link ? account ?

**Comment by LikesHisComputer** [comment]
> specific link ?

`https://satoshitron.top/links`

> account ?

Could you create one with a temporary email address?

**Comment by iam-py-test** [comment]
This is a weird website:
![image](https://user-images.githubusercontent.com/84232764/145073729-83c40c1f-8eac-4158-a83d-d5ea43f107de.png)
Almost feels like a scam

**Comment by gorhill** [comment]
Is this some sort of phishing site? The only working links in there are register/login.

**Comment by iam-py-test** [comment]
> Is this some sort of phishing site? The only working links in there are register/login.

...probably:
- fake emails
- homepage looks like a scam
- doesn't validate emails or passwords (god@god.god isn't even a valid email)
- only working links are login and register

**Comment by iam-py-test** [comment]
Also uses an insain number of CAPTCAs

**Comment by iam-py-test** [comment]
Maybe should go to badware? @LikesHisComputer opinion?

**Comment by iam-py-test** [comment]
Ok, this is sus. It redirects me to `exey.io` which pretends to be `exe.io`, which is a link shortener.

**Comment by LikesHisComputer** [comment]
> Ok, this is sus. It redirects me to `exey.io` which pretends to be `exe.io`, which is a link shortener: ![image](https://user-images.githubusercontent.com/84232764/145075838-525f4494-d9d3-4b58-b13c-99916d5a1630.png)
> 
> So - I think this is some kind of scam?
> 
> There does seem to be some BAB but who knows if even that is legit

Are you sure exey.io is not owned by exe.io?

**Comment by LikesHisComputer** [comment]
> DDG-ing "satoshitron" shows that it's full of such sites out there, so I say we should declined to address whatever is supposed to be addressed in this report, and I would like to know why @LikesHisComputer is reporting this as something to address.

anti adb

**Comment by LikesHisComputer** [comment]
I'll create another account, brb

**Comment by LikesHisComputer** [comment]
![image](https://user-images.githubusercontent.com/95556652/145080294-8fad724d-99ee-4203-9708-e625f5ac56b5.png)

**Comment by LikesHisComputer** [comment]
If you want an account:
```
username: gelemal458@sinagalore.com
password: parola
```

**Comment by gorhill** [comment]
This seems a scam site, with many others like this also -- what is there after you login? How did you even found and register for such sammy-looking site?

**Comment by gorhill** [comment]
> If you want an account:

As is often the case, this works:

    @@||satoshitron.top^$ghide

**Comment by LikesHisComputer** [comment]
> This seems a scam site, with many others like this also -- what is there after you login?

some sort 'make money' thing I think or 'faucet' thing




> How did you even found and register for such sammy-looking site?

I saw an issue with a 'faucet' with URL monetizers; I wanted to find URL monetizers and also take a look at 'faucets' or whatever

**Comment by gorhill** [comment]
Ok anyway, the `ghide` filter works, we can just add this.

**Comment by LikesHisComputer** [comment]
@ryanbr Could you add `||download-files.ml^` to EasyList?
