### ISSUE TITLE
anti adblock on digimode.ga

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1078]
### URL(s) where the issue occurs

`http://digimode.ga/`

### Describe the issue

Homepage change to a simple page while uBO is on, as shown in the first screenshot. Second screenshot shows webpage while uBO is off and how the website looks like.

### Screenshot(s)

uBO:ON>`https://imgur.com/a/MbNym`
uBO:OFF>`https://imgur.com/a/DAz7O`

### Versions

- Browser/version: Chrome 63.0.3239.84 (Official Build) (64-bit)
- uBlock Origin version: v1.14.22

### Notes

Be careful. The website runs mining scripts on some of its pages and may slow down you system, or even cause freezing issues, like the following page: `http://digimode.ga/%D9%82%D9%88%DB%8C+%D8%AA%D8%B1%DB%8C%D9%86+%D8%B3%D8%A7%DB%8C%D8%AA+%D8%B3%D8%B1%DA%AF%D8%B1%D9%85%DB%8C/`

**Comment by okiehsch** [comment]
Does
`@@||digimode.ga^$generichide`
work for you?

**Comment by nimasaj** [comment]
Yes, Thanks okiehsch

**Comment by nimasaj** [comment]
Is the issue coming from the following script?
`http://dl.20script.ir/img/website.js`

**Comment by okiehsch** [comment]
I can't tell you, the site freezes my tab even if I block everything bar the root document.
I can't look at the source code, that actually crashes the tab, but my logger shows

![unbenannt](https://user-images.githubusercontent.com/16838044/34282462-b9484a5a-e6c5-11e7-82b1-99ba86b913de.PNG)

These blocked dom-entries looked suspicious to me, they are often used as bait elements, so
`@@||digimode.ga^$generichide` was just a guess on my part ;).

**Comment by nimasaj** [comment]
I found it. Website content are being loaded from the following address:
`http://digimode.ga/upload/top.jpg`
have a look in this way:
`view-source:http://digimode.ga/upload/top.jpg`
