### ISSUE TITLE
overtone.co: breakage

### ISSUE THREAD

**Issue by jicklet** [uBlockOrigin/uAssets#10786]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://overtone.co/`

### Category

breakage

### Describe the issue

Nothing on the site is clickable while the extension is enabled. Everything looks fine, but clicking does nothing. Once disabled, the site functions again. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78246
  cosmetic: 39345
  scriptlet: 16131
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30326-27, 4d.20h.2m
    ublock-badware: 3512-1, 4d.20h
    ublock-privacy: 183-0, 4d.19h.58m
    ublock-abuse: 74-0, 4d.19h.56m
    ublock-unbreak: 1708-0, 4d.19h.53m
    easylist: 61357-535, 4d.19h.51m
    easyprivacy: 26407-483, 4d.19h.49m
    urlhaus-1: 8250-0, 2d.4h.24m
    plowe-0: 3700-3, 4d.20h.6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 636
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by LikesHisComputer** [comment]
Is `@@||cloudmaestro.com^$script,domain=overtone.co` a good filter?

**Comment by jicklet** [comment]
That worked! Thanks :) 

    On Monday, December 6, 2021, 04:47:03 PM PST, LikesHisComputer ***@***.***> wrote:  
 
 


Is @@||cloudmaestro.com^$script,domain=overtone.co a good filter?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mapx-** [comment]
@ryanbr
