### ISSUE TITLE
reit-tirement.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10797]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.reit-tirement.com/2021/11/sreits-fundamental-review-28-november.html`

### Category

detection

### Describe the issue

Anti-adblock.

Proposed filter:

`reit-tirement.com##+js(nosiif, visibility, 1000)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/145026541-a49bac39-2dc6-4888-87ea-f810c9f4743f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78573
  cosmetic: 39422
  scriptlet: 16222
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30432-30, 1h.47m
    ublock-badware: 3543-1, 1h.47m
    ublock-privacy: 188-0, 1h.47m
    ublock-abuse: 72-0, 1h.47m
    ublock-unbreak: 1716-0, 1h.47m
    easylist: 61322-552, 1h.47m
    easyprivacy: 26463-478, 1h.47m
    urlhaus-1: 8593-0, 1h.47m
    plowe-0: 3697-3, 1h.46m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 267
  launchFromSelfie: true
popupPanel: 
  blocked: 15
```
</details>

**Comment by Yuki2718** [comment]
@stephenhawk8054 
Old bab (search `babasbmsgx` in script) => `$ghide` unless it unhides too many annoyances/social widgets
Bab 4.2b (search `4.2b`) => `##+js(nostif, visibility, 1000)`

**Comment by Yuki2718** [comment]
@uBlock-user Hmm,, worked on my side but will check again.

**Comment by uBlock-user** [comment]
I see the anti-adblock notice within seconds.

**Comment by Yuki2718** [comment]
You're right, the reason I didn't see was the generic filters I've added, sorry.

**Comment by okiehsch** [comment]
I only add `##+js(nosiif, visibility, 1000)` filters after I have checked that `ghide` does not work on my end.

**Comment by Yuki2718** [comment]
Yeah, it was totally my bad. I even confused with another bab site opened in a tab with view-source: at the time. Sorry to @stephenhawk8054 too.
