### ISSUE TITLE
mistore.jp: breakage

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#10790]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.mistore.jp/store/nihombashi/event_calendar/italia/201904.html`

### Category

breakage

### Describe the issue

See **Screenshot(s)**
```
/advertise/*$domain=~legl.co,badfilter
/advertise/*$domain=~legl.co|~mistore.jp
```

### Screenshot(s)

<details>
<summary>Actual</summary>

![Screenshot1](https://user-images.githubusercontent.com/82331005/144964974-0813de4e-7442-4fa0-bb9d-125320b0f305.png)
</details>
<details>
<summary>Expected</summary>

![Screenshot2](https://user-images.githubusercontent.com/82331005/144964188-e80984f7-6642-4156-a205-1811eb80418c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 79454
  cosmetic: 43721
  scriptlet: 16289
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30417-31, now
    ublock-badware: 3543-1, now
    ublock-privacy: 188-0, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1716-0, now
    easylist: 61319-635, now
    easyprivacy: 26459-501, now
    urlhaus-1: 8593-0, now
    plowe-0: 3697-3, now
    JPN-1: 5393-14, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 136
  launchFromSelfie: true
popupPanel: 
  blocked: 41
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
