### ISSUE TITLE
'postimees.ee: detection

### ISSUE THREAD

**Issue by Saltyc0der** [uBlockOrigin/uAssets#10796]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://raamatud.postimees.ee/7401445/lugu-erilisest-omblejannast-kes-tahtis-kgb-haardest-valja-rabeleda`

### Category

detection

### Describe the issue

scrolling gets disabled on website and there will be a popup on the bottom of the screen

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78560
  cosmetic: 39409
  scriptlet: 16242
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61307-6, 9h.39m
    easyprivacy: 26452-17, 9h.37m
    plowe-0: 3700-810, 4d.12h.6m
    ublock-abuse: 72-0, 9h.35m
    ublock-badware: 3539-60, 9h.33m
    ublock-filters: 29856-127, 9h.30m
    ublock-privacy: 191-5, 9h.28m
    ublock-unbreak: 1707-38, 9h.26m
    urlhaus-1: 8593-0, 5h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 177
  launchFromSelfie: true
popupPanel: 
  blocked: 7
```
</details>

**Comment by uBlock-user** [comment]
fixed in EST: Eesti saitidele kohandatud filter regional list, activate that.

**Comment by okiehsch** [comment]
No need, I can reproduce and will add a fix referenced in this thread.

**Comment by RomanSolomatin** [comment]
This site is displaying blackened transparent foreground.

**Comment by mapx-** [comment]
add

```
raamatud.postimees.ee##.tp-modal
raamatud.postimees.ee##.tp-active.tp-backdrop
```

then you have to accept the cookies
