### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Hariharan-710** [uBlockOrigin/uAssets#10794]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=pHNJhs5MhZ4`

### Category

ads

### Describe the issue

saw skippable ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78293
  cosmetic: 39352
  scriptlet: 16181
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61373-6, 3d.22h.37m
    easyprivacy: 26411-17, 3d.22h.35m
    plowe-0: 3697-810, 7d.21h.32m
    ublock-abuse: 74-0, 3d.22h.33m
    ublock-badware: 3508-59, 3d.22h.31m
    ublock-filters: 29789-118, 3d.22h.29m
    ublock-privacy: 191-1, 3d.22h.27m
    ublock-unbreak: 1699-38, 3d.22h.24m
    urlhaus-1: 8276-0, 1d
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 18609
  launchFromSelfie: true
popupPanel: 
  blocked: 107
```
</details>

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gwarser** [comment]
> ```yaml
>   launchToReadiness: 18609
> ```

18 seconds to uBO launch? Did you opened YT just after launching Chrome or restored previous session with YT page opened? uBO most likely was not ready.

**Comment by gorhill** [comment]
I think its best to respond here, this would be off topic for the other thread.

Over 18s for default lists and with a memory selfie is really not normal -- and as @gwarser pointed out, surely the reason why you got Youtube ads.

Questions:
- Are you launching from a hard disk (as opposed to from a solid-state disk
- Do you have other extensions, and if so how many?
- Do you have some sort of antivirus?
