### ISSUE TITLE
blastingnews.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1079]
### URL(s) where the issue occurs

`http://it.blastingnews.com/tv-gossip/2017/12/video/due-ex-del-gf-vip-stanno-per-naufragare-sullisola-004762587.html`

### Describe the issue

Video does not play

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34284560-25c85764-e690-11e7-854d-9fed290c57bd.png)

Expected: 
![image](https://user-images.githubusercontent.com/7283682/34284583-568bffae-e690-11e7-80ed-0f88e247ba35.png)

### Versions

- Browser/version: ff57.0.1
- uBlock Origin version: 1.14.22

### Settings

All default

### Notes

Related: https://github.com/jspenguin2017/uBlockProtector/issues/769

**Comment by mapx-** [comment]
working here
```
@@||googletagservices.com/tag/js/gpt.js$script,domain=blastingnews.com
||google-analytics.com/analytics.js$script,redirect=noopjs,domain=blastingnews.com
@@||securepubads.g.doubleclick.net/$script,domain=blastingnews.com
```

**Comment by LukePoke** [comment]
@mapx- Però in quest'altra notizia (presa a caso) non funziona lo stesso. Come mai? è diverso per ogni notizia?

http://it.blastingnews.com/cronaca/2017/10/viareggio-video-hot-di-una-mamma-finisce-sulla-chat-whatsapp-sbagliata-002087743.html

Non è un sito che frequento, ma raramente mi capita di andarci e vorrei che in quelle poche volte che ci vado andasse il player. Sarebbe utile anche a chi lo visita assiduamente.

**Comment by mapx-** [comment]
prova ancora
```
@@||googletagservices.com/tag/js/gpt.js$script,domain=blastingnews.com
||google-analytics.com/analytics.js$script,redirect=noopjs,domain=blastingnews.com
@@||securepubads.g.doubleclick.net/$script,domain=blastingnews.com
@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=blastingnews.com
```

@Khrin

**Comment by LukePoke** [comment]
Ora sì, grazie!

**Comment by LukePoke** [comment]
@Khrin Se non è un problema potresti passare sul forum di Easylist e aggiungere le altre cose delle mie discussioni?
