### ISSUE TITLE
wetteronline.de

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#108]
### URL(s) where the issue occurs

Main:
`http://www.wetteronline.de/`
Typical location-specific example:
`http://www.wetteronline.de/wetter/frankfurt-am-main`

### Describe the issue

Ads. Lots of Ads. All over the place.

### Screenshot(s)

One obvious example:
![ex1](https://cloud.githubusercontent.com/assets/12064918/17910217/388e0b18-6988-11e6-87d4-e327ca293d77.jpg)

### Versions

- Browser/version: Firefox 48.0.1 (Build for x64), Chrome 52.0.2743.116 (64-bit)
- uBlock Origin version: 1.8.4
- OS: Windows 10 x64 (Version 1607 'Anniversary Update')

### Settings

- Tested with clean profiles and uBO default settings.
- Filter lists: All defaults + Easylist DEU.

### Notes
 
Also tried the filters listed here: [EasyList Germany topic for wetteronline.de](https://forums.lanik.us/viewtopic.php?p=99533#p99533)

And some other filters suggested in this thread, but no different result.

To be honest, I was quite surprised to see this, I assumed that _wetteronline.de_, being one of the bigger sites, would be covered by EasyList Germany.

Apparently not, but I guess that leaves us a good test case.

The adds are inserted by some script, after the actual page has been loaded and displayed completely. For some reasons, I don't get these ads all the time, for example when visiting the main page directly. But if I go to a location based page (as in the example), the ads appear. Going then back to main now also has ads.

What I found from the markup so far: Randomized `id` attributes for the `div` elements containing the ads, but the structural hierarchy should be the same. Although other `id` and/or `class` attributes of parent elements etc. seem to be randomized as well.

Oh, and many unblocked scripts:
![2](https://cloud.githubusercontent.com/assets/12064918/17911055/21e12982-698c-11e6-859d-d5338fba00f4.jpg)

(Just a partial list)

**Comment by TonyTough** [comment]
With the optional List "Anti-Adblock Killer Reek" the ads are filtered out.

**Comment by Hrxn** [comment]
I thought this list is only to be used in conjunction with the "Anti-Adblock Killer" userscript for Greasemonkey/Tampermonkey?

**Comment by gorhill** [comment]
I am not getting these ads -- without Reek's. Possibly I need to go through a `.de` VPN?

**Comment by TonyTough** [comment]
> I thought this list is only to be used in conjunction with the "Anti-Adblock Killer" userscript for Greasemonkey/Tampermonkey?

The filter list works without the userscript, the userscript has additional filters.
