### ISSUE TITLE
meteofrance.com: ads

### ISSUE THREAD

**Issue by maximevdl** [uBlockOrigin/uAssets#10805]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://meteofrance.com/previsions-meteo-france/paris/75000`

### Category

ads

### Describe the issue

yellow banner ad on the upper side of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/CnATfxm.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.3b4
Firefox: 94
filterset (summary): 
  network: 102327
  cosmetic: 101466
  scriptlet: 19038
  html: 606
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 399-1, now
    fanboy-annoyance: 59075-306, now
    ublock-annoyances: 4327-4, now
  default: 
    ublock-filters: 30435-30, now
    ublock-badware: 3543-1, now
    ublock-privacy: 184-0, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1716-0, now
    easylist: 61345-678, now
    easyprivacy: 26463-475, now
    urlhaus-1: 8444-0, now
    plowe-0: 3698-3, now
    FRA-0: 25974-549, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 363
  launchFromSelfie: false
popupPanel: 
  blocked: 3
```
</details>

**Comment by okiehsch** [comment]
`meteofrance.com##[href*="https://www.ardoiz.com/"]`
@AdamWr for Adguard France.

**Comment by AdamWr** [comment]
Added, thank you.
