### ISSUE TITLE
visibleoffers.com: breakage

### ISSUE THREAD

**Issue by BionicBison05** [uBlockOrigin/uAssets#10800]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.visibleoffers.com/`

### Category

breakage

### Describe the issue

Page is completely blank when uBO is enabled and functions as intended once disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1286" alt="Screen Shot 2021-12-07 at 9 31 58 AM" src="https://user-images.githubusercontent.com/93722725/145048014-25c43743-f03d-4a67-97fa-d21e18a8fd77.png">
<img width="1286" alt="Screen Shot 2021-12-07 at 9 32 57 AM" src="https://user-images.githubusercontent.com/93722725/145048136-6a87ac27-e6a3-445f-99f4-f7e4a4f4e44e.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 97
filterset (summary): 
  network: 82378
  cosmetic: 80886
  scriptlet: 18408
  html: 598
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48184-584, 10m
  default: 
    ublock-filters: 30435-29, 11m
    ublock-badware: 3543-1, 11m
    ublock-privacy: 188-0, 11m
    ublock-abuse: 72-0, 11m
    ublock-unbreak: 1716-0, 11m
    easylist: 61322-171, 11m
    easyprivacy: 26463-49, 11m
    urlhaus-1: 8444-0, 11m
    plowe-0: 3698-815, 10m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 193
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by LikesHisComputer** [comment]
@uBlock-user Is there any data collection involved with `https://www.visibleoffers.com/js/third-party/angulartics-google-analytics/dist/angulartics-ga.min.js`? If yes, could it be stopped with scriptlet(s) while having the page whitelisted on `visibileoffers.com`?

**Comment by uBlock-user** [comment]
> Is there any data collection involved with

No, it's a wrapper from GA, script is first-party and no data collection happens.

**Comment by uBlock-user** [comment]
@ryanbr `@@||visibleoffers.com/js/third-party/angulartics-google-analytics/dist/angulartics-ga.min.js$script,~third-party`
