### ISSUE TITLE
Detected on goduke.com

### ISSUE THREAD

**Issue by tempissue** [uBlockOrigin/uAssets#10809]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://goduke.com`

### Describe the issue

Page is detecting adblock with a big popup

### Screenshot(s)

<img width="1685" alt="Screen Shot 2021-12-07 at 12 33 00 PM" src="https://user-images.githubusercontent.com/32878098/145078064-8b20c62c-71f9-4b74-91d4-a7b13f647eff.png">

### uBlock Origin version

1.39.2

### Browser name and version

Chrome 96

### Settings

None

**Comment by gorhill** [comment]
This seems to work in both Chromium/Firefox:

    goduke.com##+js(no-xhr-if, /analytics|livestats/)
