### ISSUE TITLE
nl.motorsport.com: ads

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#10801]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://nl.motorsport.com/f1/news/jeroen-bleekemolen-terugblik-gp-saudi-arabie-verstappen-hamilton/6857490/`

### Category

ads

### Describe the issue

Leftover on top of article

(also tested with `ignoreGenericCosmeticFilters` disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 67766
  cosmetic: 24921
  scriptlet: 16138
  html: 596
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    NLD-0: null
  added: 
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/Others/General%20Hide: 8197-1, 7h.21m
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt: 1862-0, 7h.21m
  default: 
    ublock-filters: 30432-220, 7h.21m
    ublock-privacy: 188-1, 7h.21m
    ublock-unbreak: 1716-12, 7h.21m
    easylist: 61321-23884, 7h.21m
    easyprivacy: 26461-479, 7h.21m
    plowe-0: 3697-1, 7h.21m
filterset (user): [array of 283 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1025 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  dynamicFilteringEnabled: true
  ignoreGenericCosmeticFilters: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 10
  autoUpdateDelayAfterLaunch: 60
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#000092 00001/#2A2A2A
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  launchToReadiness: 3814
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by gorhill** [comment]
This needs to be fixed in _"NLD: EasyList Dutch"_.
