### ISSUE TITLE
richardvigilantebooks.com: ads

### ISSUE THREAD

**Issue by sixtimeseven** [uBlockOrigin/uAssets#10814]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://richardvigilantebooks.com/how-do-you-declare-a-boolean-array-in-c/`

### Category

ads

### Describe the issue

gif ads in multiple locations on website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2021-12-07 202600](https://user-images.githubusercontent.com/49248356/145143132-e3619e91-b184-4d1f-8fad-13a98031b5c8.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 109806
  cosmetic: 126258
  scriptlet: 31703
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 4h.4m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 4d.29m
    adguard-generic: 62147-4489, 1d.3h.59m
    adguard-annoyance: 48163-1532, 1d.3h.57m
    adguard-social: 14834-38, 1d.3h.55m
    fanboy-thirdparty_social: 69-0, 4d.21h.27m
    ublock-annoyances: 4327-8, 1d.3h.53m
  default: 
    ublock-filters: 30413-71, 1d.4h.13m
    ublock-badware: 3543-1, 1d.4h.11m
    ublock-privacy: 188-0, 1d.4h.9m
    ublock-abuse: 72-0, 1d.4h.7m
    ublock-unbreak: 1715-1, 1d.4h.5m
    easylist: 61287-575, 1d.4h.3m
    easyprivacy: 26446-518, 1d.4h.1m
    urlhaus-1: 8656-0, 17m
    plowe-0: 3695-5, 3d.20h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 40 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 365
  launchFromSelfie: true
popupPanel: 
  blocked: 13
```
</details>

**Comment by mapx-** [comment]
add (to be reported at easylist repository)
`richardvigilantebooks.com##a[href^="https://rebrand.ly/"]`

@ryanbr
