### ISSUE TITLE
fbstream.tv: breakage

### ISSUE THREAD

**Issue by galenyip** [uBlockOrigin/uAssets#10822]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fbstream.tv/live/stream/sky-sports-f1-fb-1/`

### Category

breakage

### Describe the issue

The site will show "kindly remove/disable adblock, and reload the page." when uBO is enabled and not able to function.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77683
  cosmetic: 39189
  scriptlet: 16117
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30283-107, never
    ublock-badware: 3494-1, never
    ublock-privacy: 183-0, never
    ublock-abuse: 74-0, never
    ublock-unbreak: 1707-0, never
    easylist: 60746-79, never
    easyprivacy: 25518-27, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-560, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1659
  launchFromSelfie: false
popupPanel: 
  blocked: 9
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce any issue.

> - [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Did you?

**Comment by ghajini** [comment]
i can reproduce
this work
`@@||fbstream.tv^$ghide`

**Comment by mapx-** [comment]
> i can reproduce this work `@@||fbstream.tv^$ghide`

android ?

**Comment by iam-py-test** [comment]
I can not reproduce, however, I do get this:
![image](https://user-images.githubusercontent.com/84232764/145250559-e97cc70e-6722-4d8e-9080-829eeb24aedb.png)
@DandelionSprout might want to look into unblocking `pl.allsportsflix.top`, no idea if it is legit but the sites redirects me to it. Has one detection on VT too

**Comment by mapx-** [comment]
yes, android

**Comment by ghajini** [comment]
> > i can reproduce this work `@@||fbstream.tv^$ghide`
> 
> android ?

yep android
