### ISSUE TITLE
w.cima4u.ws: popups

### ISSUE THREAD

**Issue by MeDVL73** [uBlockOrigin/uAssets#10829]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://w.cima4u.ws/v73/`

### Category

popups

### Describe the issue

10 pop ads to this link: https://w.cima4u.ws/wp-content/themes/YourColor/components/packs/%23footer/yourcolor.png 
is i want to click on search box

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78403
  cosmetic: 39361
  scriptlet: 16213
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61142-6, 3d.9h.27m
    easyprivacy: 26434-17, 3d.9h.25m
    plowe-0: 3697-810, 10d.10h.49m
    ublock-abuse: 72-0, 3d.5h.16m
    ublock-badware: 3509-59, 3d.5h.14m
    ublock-filters: 29771-123, 3d.5h.12m
    ublock-privacy: 190-2, 3d.5h.10m
    ublock-unbreak: 1704-38, 3d.5h.8m
    urlhaus-1: 8656-0, 6h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 249
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by LikesHisComputer** [comment]
```
##[href*="//agacelebir.com"]
||fwlrdkhh.xyz^
```

@ryanbr

**Comment by MeDVL73** [comment]
how can i use it ?

**Comment by LikesHisComputer** [comment]
@MeDVL73 By adding:
```
cima4u.ws##+js(acis, JSON.parse, break;case $.)
##[href*="//agacelebir.com"]
||fwlrdkhh.xyz^
```
to **My filters** in uBO.

**Comment by MeDVL73** [comment]
> @MeDVL73 By adding:
> 
> ```
> cima4u.ws##+js(acis, JSON.parse, break;case $.)
> ##[href*="//agacelebir.com"]
> ||fwlrdkhh.xyz^
> ```
> 
> to **My filters** in uBO.

**Comment by MeDVL73** [comment]
thank u it worked
