### ISSUE TITLE
pfps.gg: detection

### ISSUE THREAD

**Issue by vSpeakr** [uBlockOrigin/uAssets#10824]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://pfps.gg/`

### Category

detection

### Describe the issue

When clicking load more, the site tells you "Please disable anti-adblock/anti-tracking scripts to continue using this website".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_zP3xWLlVct](https://user-images.githubusercontent.com/71159832/145254250-85f1c1d6-1354-4cc4-b5c3-9f7443614ff6.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78389
  cosmetic: 92893
  scriptlet: 16255
  html: 0
listset (total-discarded, last updated): 
  removed: 
    spa-1: null
    urlhaus-1: null
  added: 
    fanboy-annoyance: 59044-146, 2h.15m
  default: 
    easylist: 61078-6, 3d.23h.4m
    easyprivacy: 26427-17, 3d.23h.4m
    plowe-0: 3700-810, 6d.12h.32m
    spa-0: 3422-17, 2h.15m
    ublock-abuse: 74-0, 3d.23h.4m
    ublock-badware: 3509-59, 3d.23h.4m
    ublock-filters: 29771-167, 3d.23h.4m
    ublock-privacy: 190-10, 3d.23h.4m
    ublock-unbreak: 1703-42, 3d.23h.4m
filterset (user): [array of 41 redacted]
trustedset: 
  added: [array of 98 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  autoUpdate: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 31115
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by gorhill** [comment]
>     launchToReadiness: 31115
>     launchFromSelfie: true

This is not normal. This is what I get on my side using Chromium 96 and uBO 1.39.2:

>     launchToReadiness: 177
>     launchFromSelfie: true

It seems for some people, the browser is unduly delaying uBO's time-to-readiness -- I will open an issue to collate these unexpected figures in one place, this needs to be investigated.

**Comment by gwarser** [comment]
> ```yaml
> popupPanel: 
>   blocked: 0
> ```


> ```yaml
> trustedset: 
>   added: [array of 98 redacted]
> ```


I'm also wondering if OP has uBO enabled on this page... No - reporting will be disabled in this case.

But maybe he is using some fork with native blocker? I see 2 blocked on my side.

> ```yaml
> Chromium: 96
> ```

**Comment by gorhill** [comment]
> But maybe he is using some Chrome fork with native blocker?

@vSpeakr What specific browser are you using?

**Comment by vSpeakr** [comment]
> > But maybe he is using some Chrome fork with native blocker?
> 
> @vSpeakr What specific browser are you using?

Google Chrome 96.0.4664.93 64-bits.

**Comment by gorhill** [comment]
I cannot reproduce an anti-blocker. Given how long it took time for uBO to be ready on your side, can you reload the page and see if the anti-blocker still kick in?
