### ISSUE TITLE
[NSFW] thedoujin.com

### ISSUE THREAD

**Issue by supas** [uBlockOrigin/uAssets#1082]
### URL(s) where the issue occurs

`thedoujin.com`

### Describe the issue

Ads

### Screenshot(s)

https://kek.gg/i/5RwQRF.png

### Versions

- Browser/version: 63.0.3239.108
- uBlock Origin version: 1.14.22

### Settings

- default settings

**Comment by mapx-** [comment]
update `ublock filters`, do ou still see the ads ?

**Comment by lain566** [comment]
Yes I can still see it

**Comment by lain566** [comment]
It's works
`http://thedoujin.com/bload.php`

**Comment by mapx-** [comment]
- still don't see such php
- could you upload the php file (on pastebin for example) so I could see it ?

**Comment by lain566** [comment]
This also works
`thedoujin.com##script:inject(abort-on-property-read.js, ExoLoader.addZone)`

I can't see it neither

**Comment by lain566** [comment]
Ok, I can no longer reproduce it, I had a race condition. 

@mapx- 
Go to `thedoujin.com`
Delete the cookies from thedoujin.com and refresh the page
The banner will be displayed

Can you reproduce it?

**Comment by mapx-** [comment]
only disabling the `Exoloader filter` I get the ads.

**Comment by lain566** [comment]
You're right, this issue it's fixed.
