### ISSUE TITLE
fffmovies.wtf: popups

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10832]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [x] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://fffmovies.wtf/movies2/`

### Category

popups

### Describe the issue

Click on any movies' thumbnails below, a popup appears.

Proposed filter:

`fffmovies.wtf##+js(acis, JSON.parse, break;case $.)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77821
  cosmetic: 39474
  scriptlet: 16198
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30381-30, 29m
    ublock-badware: 3564-1, 29m
    ublock-privacy: 185-0, 29m
    ublock-abuse: 72-0, 29m
    ublock-unbreak: 1716-0, 29m
    easylist: 61404-556, 29m
    easyprivacy: 26477-475, 29m
    urlhaus-1: 7803-0, 29m
    plowe-0: 3698-3, 29m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 266
  launchFromSelfie: true
popupPanel: 
  blocked: 33
```
</details>

**Comment by LikesHisComputer** [comment]
@ryanbr another case for `##[href*="//agacelebir.com"]`
