### ISSUE TITLE
bbs.pcbeta.com: ads

### ISSUE THREAD

**Issue by nowaction** [uBlockOrigin/uAssets#10833]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://bbs.pcbeta.com/forum.php?mod=forumdisplay&fid=548&filter=author&orderby=dateline`

### Category

ads

### Describe the issue

创建规则拦截后，刷新后仍存在广告残余（没有广告内容，有3个广告框）

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 86
filterset (summary): 
  network: 94361
  cosmetic: 49267
  scriptlet: 16343
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 26669-86, 1d.21h.13m
    easylist: 61320-12, 1d.21h.11m
    easyprivacy: 26460-43, 1d.21h.9m
    plowe-0: 3700-812, 5d.23h.54m
    ublock-abuse: 72-0, 1d.21h.7m
    ublock-badware: 3539-60, 1d.21h.5m
    ublock-filters: 29854-147, 1d.21h.3m
    ublock-privacy: 192-5, 1d.21h.1m
    ublock-unbreak: 1704-39, 1d.20h.59m
    urlhaus-1: 7803-0, 12m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 899
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by LikesHisComputer** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
I don't see ads but see anti-adb, will fix in Chinese filters. @mapx- If I'm not wrong and if you and I are seeing the same, they appears to be not ad.

**Comment by Yuki2718** [comment]
@nowaction Can you please post screenshot(s) of ads?

**Comment by Yuki2718** [comment]
Hmm, anti-adb should have been fixed by https://github.com/AdguardTeam/AdguardFilters/issues/101079 but somehow the aost filter is not present on uBO version of Chinese filters.

**Comment by mapx-** [comment]
without `pcbeta.com##div:matches-css(width: /980px/)`
I get these empty PH

![image](https://user-images.githubusercontent.com/10303732/145427921-3bb6fef0-6e4a-403d-be2b-6e2241dd6559.png)

**Comment by Yuki2718** [comment]
@mapx- Okay, apparently we see differnt staff - maybe geo-dependent:

![pcbeta](https://user-images.githubusercontent.com/58900598/145431820-89f9cc0b-ba8d-4d6c-8f83-8a96b42228ad.png)

I don't see PH but is there other way to hide them?

**Comment by mapx-** [comment]
test

`pcbeta.com##div:matches-css(width: /980px/):not(#pgt):not(.pgs)`

**Comment by mapx-** [comment]
nvm, your fix kills the PH

**Comment by slavaleleka** [comment]
@Yuki2718 we have not released scriptlets with `abort-on-stack-trace`, that's why it's unavailable yet

**Comment by Yuki2718** [comment]
> we have not released scriptlets with `abort-on-stack-trace`, that's why it's unavailable yet

Got it, thank you for answering!

**Comment by Heporis** [comment]
> nvm, your fix kills the PH

the picture can't popup
caused by the list CHN: AdGuard Chinese (中文)

**Comment by Yuki2718** [comment]
I can't access the site even with Hong Kong VPN now.
