### ISSUE TITLE
beachcam.meo.pt: breakage

### ISSUE THREAD

**Issue by methane4** [uBlockOrigin/uAssets#10837]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://beachcam.meo.pt/`

### Category

breakage

### Describe the issue

On the beachcam.meo.pt website cameras dont load when ublock origin is active(Screenshot 1), after disabling it for that page a privacy consent to data processing is shown(Screenshot 2), which can be denied using "Não Aceito", the player loads and an add is shown before the camera feed starts(Screenshot 4). (Even after answering the privacy consent with ublock disabled and enabling it again to try the player does not show (Screenshot 3) )

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2021-12-09 19-10-54](https://user-images.githubusercontent.com/46012160/145462244-d30f28de-d8ed-49a3-b4eb-56caecad51d3.png)

![Screenshot from 2021-12-09 19-11-10](https://user-images.githubusercontent.com/46012160/145462263-b0fb3736-d757-4cb7-b489-d4eadea4496e.png)

![Screenshot from 2021-12-09 19-12-49](https://user-images.githubusercontent.com/46012160/145462283-3ab25f3c-f491-40cc-a77b-97cfd77c19f2.png)

![Screenshot from 2021-12-09 19-12-56](https://user-images.githubusercontent.com/46012160/145462306-ecb7ecc5-76d9-4e02-8137-8c72ff636f73.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 102764
  cosmetic: 134266
  scriptlet: 21836
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48198-141, 2d.2h.31m
    adguard-spyware: 20559-720, 2d.2h.29m
    adguard-spyware-url: 399-1, 15h.28m
    fanboy-annoyance: 59067-2804, 2d.16h.46m
    fanboy-cookiemonster: 20459-20459, 2d.16h.44m
    fanboy-thirdparty_social: 69-20, 2d.16h.42m
    spa-1: 4187-81, 2d.2h.23m
    ublock-annoyances: 4318-252, 2d.2h.19m
  default: 
    easylist: 61345-75, 2d.2h.27m
    easyprivacy: 26463-7743, 2d.2h.25m
    plowe-0: 3695-859, 6d.5h.24m
    ublock-abuse: 72-0, 2d.2h.21m
    ublock-badware: 3539-60, 2d.2h.17m
    ublock-filters: 29859-494, 2d.2h.15m
    ublock-privacy: 191-32, 2d.2h.13m
    ublock-unbreak: 1705-54, 2d.2h.11m
    urlhaus-1: 8656-0, 23h.30m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 436
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by okiehsch** [comment]
You checked the box `I verified that the issue still occurs without custom filter lists`.
My filter fixed the issue with a default setup,

**Comment by mapx-** [comment]
add also

`@@||quantcast.mgr.consensu.org/choice/*/choice.js$script,domain=beachcam.meo.pt`

FA issue @ryanbr

**Comment by okiehsch** [comment]
That's not enough on my end using Chromium. Clicking "Aceito" does not work.

**Comment by okiehsch** [comment]
`@@||quantcast.mgr.consensu.org^$xhr,domain=beachcam.meo.pt`

**Comment by mapx-** [comment]
yes, I tested for video stuff after accepting, so 2 exceptions to add @ryanbr

**Comment by methane4** [comment]
> You checked the box `I verified that the issue still occurs without custom filter lists`. My filter fixed the issue with a default setup,

I had tested on a browser i thought was on default setup apologies, it works on the default setup i just confirmed. However if you know what to whitelist on my case please share.

**Comment by mapx-** [comment]
Add & test again

`@@||quantcast.mgr.consensu.org^$xhr,script,domain=beachcam.meo.pt`
