### ISSUE TITLE
nha.chotot.com: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10847]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://nha.chotot.com/`

### Category

breakage

### Describe the issue

There are 2 sections in the page that cannot be loaded. The links are normal first-party links. You might need a Vietnam VPN to access.

Proposed filters:

```
@@||securepubads.g.doubleclick.net/gpt/*$script,domain=nha.chotot.com
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=nha.chotot.com
@@||googletagservices.com/tag/js/gpt.js$script,domain=nha.chotot.com
```

### Screenshot(s)

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/145507827-de91fa98-893c-4c9f-affd-4fa310d08168.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/145507988-9533a198-7849-4872-8ec5-6de46cb44147.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78838
  cosmetic: 40872
  scriptlet: 16243
  html: 595
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2192-2, 56m
  default: 
    ublock-filters: 30400-36, 13m
    ublock-badware: 3564-1, 13m
    ublock-privacy: 185-0, 13m
    ublock-abuse: 72-0, 13m
    ublock-unbreak: 1717-0, 13m
    easylist: 61565-591, 15m
    easyprivacy: 26478-479, 13m
    urlhaus-1: 7938-0, 13m
    plowe-0: 3697-3, 13m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 250
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
maybe it should be better to be fixed directly in VIE list

there is also a banner to be removed:

```
nha.chotot.com##[class^="Desktop__LoadingSlider"]
nha.chotot.com##[class^="Home__WrapperBanner"]
```

@hoang-rio

**Comment by hoang-rio** [comment]
> maybe it should be better to be fixed directly in VIE list
> 
> there is also a banner to be removed:
> 
> ```
> nha.chotot.com##[class^="Home__WrapperBanner"]
> ```
> 
> @hoang-rio

Is this rule related to this issue?

**Comment by mapx-** [comment]
not to this issue but it's a large banner not hidden at the top:

![image](https://user-images.githubusercontent.com/10303732/145579622-f930c0cd-d75d-4477-84c1-07603bf423be.png)

**Comment by stephenhawk8054** [comment]
I've forced update the filters but I think the 2 sections are still missing.

**Comment by mapx-** [comment]
@hoang-rio still to be fixed (see @stephenhawk8054  exceptions above)

**Comment by hoang-rio** [comment]
@mapx- EL and ABPVN 2 section is loadable so i just hide top banner

**Comment by stephenhawk8054** [comment]
@mapx- Oh sorry, I just checked again and I think that the problem is not about whitelisting those domains. I see that there's an exception filter in `ublock filters` (maybe because of bait script for anti-adblock sites).

`@@/js/prebid-ads.js$script`

which whitelisted this script:

`https://static.chotot.com/storage/default_scripts/gpt.js`

But for some reasons in this case, blocking it makes the site to display those 2 sections normally without the need to allowing any scripts or defusing xhr.

`||static.chotot.com/storage/js/prebid-ads.js$script,important`

The above filter is used when I disabled the added exceptions:

```
nha.chotot.com#@#+js(no-xhr-if, /^/)
@@||securepubads.g.doubleclick.net/gpt/$script,domain=nha.chotot.com,badfilter
@@||googletagservices.com/tag/js/gpt.js$script,domain=nha.chotot.com,badfilter
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | googletagmanager.com/gtm.js | << | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js | -- | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | \|\|googletagmanager.com^ | -- | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | ##[class^="Home__WrapperBanner"] |  | nha.chotot.com |  | dom | `https://nha.chotot.com/` |
| +1 | googletagmanager.com/gtm.js | << | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js | -- | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | \|\|googletagmanager.com^ | -- | nha.chotot.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-NZKHXF7` |
| +1 | googletagservices.com/gpt.js | << | nha.chotot.com | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +1 | \|\|googletagservices.com/tag/js/gpt.js$script,redirect-rule=googletagservices.com/gpt.js | -- | nha.chotot.com | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +1 | \|\|googletagservices.com^ | -- | nha.chotot.com | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +0 | #@#+js(no-xhr-if, /^/) |  | nha.chotot.com |  | dom | `https://nha.chotot.com/` |
| +0 | \|\|static.chotot.com/storage/js/prebid-ads.js$script,important | -- | nha.chotot.com | 1 | script | `https://static.chotot.com/storage/js/prebid-ads.js` |

</details>
