### ISSUE TITLE
extremereportbot.com: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10846]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://extremereportbot.com/main/`

### Category

ads

### Describe the issue

Ads placeholders because of `ghide`.

Proposed filter:

`extremereportbot.com##.adsbygoogle`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/145502112-84e7608e-423d-4694-9eb2-120817b92144.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77966
  cosmetic: 39631
  scriptlet: 16214
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30400-29, 23m
    ublock-badware: 3564-3, 23m
    ublock-privacy: 185-1, 23m
    ublock-abuse: 72-0, 23m
    ublock-unbreak: 1717-0, 23m
    easylist: 61565-554, 23m
    easyprivacy: 26478-476, 23m
    urlhaus-1: 7938-0, 23m
    plowe-0: 3697-0, 23m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 250
  launchFromSelfie: true
popupPanel: 
  blocked: 17
```
</details>

**Comment by okiehsch** [comment]
That will trigger an anti adblock message. We have not bothered trying different style filters because the site will counter almost immediately,
