### ISSUE TITLE
ar.kairosweb.com: ads

### ISSUE THREAD

**Issue by Efexer** [uBlockOrigin/uAssets#10842]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://ar.kairosweb.com/`

### Category

ads

### Describe the issue

Site is plagued with ads. Pop-up ads on site load (while travelling through the site) severely disrupts the browsing experience.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/60304787/145498472-d6195616-92d9-44ec-8e3e-830ce67aadf6.png)
![image](https://user-images.githubusercontent.com/60304787/145498500-18f5c6a6-961a-43d8-a8cd-dfb6e2128f4a.png)
![image](https://user-images.githubusercontent.com/60304787/145498546-3fb1f712-e046-4f14-9167-5d0f6380d0c3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77649
  cosmetic: 39395
  scriptlet: 16204
  html: 601
listset (total-discarded, last updated): 
  added: 
    https://www.coolshop.co.uk/product/don-one-lifestyle-tws120-black-in-ear-true-wireless-stereo-earbuds-with-charging-case/235AS7/?retailAttributionToken=ChM1OTEyOTM2MDQyNjAyNDQwOTgwEA0aI2Nvb2wtLS1yZWNfcmVjb21tZW5kZV8xNjI1MTM0MTA5NDY5Ihxjb29sdWstLS1yZWNvbW1lbmRlZC1mb3IteW91KAA: 0-0, never
  default: 
    ublock-filters: 30414-29, 3d.4h.37m
    ublock-badware: 3513-1, 3d.4h.35m
    ublock-privacy: 187-0, 3d.4h.33m
    ublock-abuse: 72-0, 3d.4h.31m
    ublock-unbreak: 1716-0, 3d.4h.29m
    easylist: 61286-551, 3d.4h.27m
    easyprivacy: 26444-475, 3d.4h.25m
    urlhaus-1: 7725-0, 8h.22m
    plowe-0: 3698-3, 2d.6h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5306
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
1. subscribe spanish lists
2. 2. add these filters:

```
ar.kairosweb.com##[href*="banner"]
||ar.kairosweb.com/*.gif$image
ar.kairosweb.com##.navbar [target="_blank"]
```

@Yuki2718  - for the spanish adguard ?

**Comment by Yuki2718** [comment]
Hmm, apparently the popup is also ad.

**Comment by Efexer** [comment]
Beautiful, thanks! <3
