### ISSUE TITLE
animelek.me: popups

### ISSUE THREAD

**Issue by MeDVL73** [uBlockOrigin/uAssets#10844]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://animelek.me/`

### Category

popups

### Describe the issue

i think there is some hiden ads on this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77956
  cosmetic: 39474
  scriptlet: 16239
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61405-7, 1d.9m
    easyprivacy: 26477-17, 1d.9m
    plowe-0: 3698-811, 1d.9m
    ublock-abuse: 72-0, 1d.9m
    ublock-badware: 3560-61, 1d.9m
    ublock-filters: 29830-128, 1d.9m
    ublock-privacy: 189-2, 1d.9m
    ublock-unbreak: 1705-39, 1d.9m
    urlhaus-1: 7938-0, 5m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 172
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by LikesHisComputer** [comment]
`||eqsstvfotd.com^`
@ryanbr

**Comment by LikesHisComputer** [comment]
@ryanbr `||eqsstvfotd.com^`

**Comment by MeDVL73** [comment]
is that a filter ?

**Comment by MeDVL73** [comment]
thank u bro i really appriciate it can i add it manualy ?

**Comment by LikesHisComputer** [comment]
> thank u bro i really appriciate it can i add it manualy ?

yeah
