### ISSUE TITLE
distrowatch.org: ads

### ISSUE THREAD

**Issue by jspx-projects** [uBlockOrigin/uAssets#10848]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://distrowatch.org/`

### Category

ads

### Describe the issue

adds of company 3cx cannot be removed without removing part of the content as well. Easy to verify by just loading distrowatch.org

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77821
  cosmetic: 39601
  scriptlet: 16211
  html: 595
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.10h.33m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30398-30, 16h.15m
    ublock-badware: 3564-1, 16h.13m
    ublock-privacy: 185-0, 16h.11m
    ublock-abuse: 72-0, 16h.9m
    ublock-unbreak: 1716-0, 16h.7m
    easylist: 61406-554, 16h.5m
    easyprivacy: 26478-475, 16h.3m
    plowe-0: 3697-3, 2d.20h.3m
    urlhaus-1: 7803-0, 16h.1m
filterset (user): [array of 126 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 293
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
test for breakage

```
distrowatch.org##[href*="3cx"]:upward(tbody)
distrowatch.org##[href^="https://pbxinaflash.com/"]
```

**Comment by gorhill** [comment]
@jspx-projects Please remove those two lists from your listset (click trask icon, apply changes):

- https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt
- https://mirror.cedia.org.ec/malwaredomains/justdomains

These lists no longer exist, and they might cause undue delays when uBO try to fetch them.
