### ISSUE TITLE
mihanfile.net timer

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#10849]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mihanfile.net/5ee83a071e439bc8?_t=English`

### Describe the issue

The website has a **201 seconds** countdown timer.

### Notes

`mihanfile.net##+js(set, seconds, 0)` sets the timer to 0 but when I click on "Download now" it doesn't work.
I don't think it's a server-side timer because this code that manages the timer can be found in the client-side code:
```
<script>

    var milisec = 0;
    var seconds = 201;

    function display()
    {
        $('.btn-free-element').hide();
        $('.download-timer').show();
        if (seconds == 0)
        {
            $('.download-timer').html("<a class='btn btn-secondary btn-lg btn-block' href='https://mihanfile.net/5ee83a071e439bc8?pt=U2tSR1YxZGtPVlZNZVdWR2F6ZDJaSFl4Um1OWWR6MDlPa3NrR05RdENLNnhaZldZK29mL1JVUT0%3D'>download now</a>");
        }
        else
        {
            $('.download-timer-seconds').html(seconds);
        }
        seconds--;
    }

    $(document).ready(function() {
        display();
        $('.download-timer-seconds').html(201);
        countdownTimer = setInterval('display()', 1000);
    });

</script>
```

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77697
  cosmetic: 39419
  scriptlet: 16242
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61320-6, 3d.4h.21m
    easyprivacy: 26460-17, 3d.3h.14m
    plowe-0: 3697-811, 2d.22h.53m
    ublock-abuse: 72-0, 2d.22h.49m
    ublock-badware: 3539-60, 2d.22h.45m
    ublock-filters: 29856-127, 2d.22h.43m
    ublock-privacy: 191-5, 2d.22h.41m
    ublock-unbreak: 1705-38, 2d.22h.38m
    urlhaus-1: 7725-0, 1h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 548
  launchFromSelfie: false
```
</details>

**Comment by okiehsch** [comment]
>  this code that manages the timer can be found in the client-side code:

That's always the case. The timer is validated server-side. If you add your filter or
`mihanfile.net##+js(nano-sib)`
The download will work after 201 seconds even though you boosted it, or changed it to 0, on the client side.

**Comment by MasterKia** [comment]
What does the "external" label mean?

Similar **timer** issues that has been solved and _didn't get_ the "external" label:
https://github.com/uBlockOrigin/uAssets/issues/10613
https://github.com/uBlockOrigin/uAssets/issues/9686
https://github.com/uBlockOrigin/uAssets/issues/8622
https://github.com/uBlockOrigin/uAssets/issues/8606#issuecomment-957843113
https://github.com/uBlockOrigin/uAssets/issues/8494

**Comment by mapx-** [comment]
- read again @okiehsch explanation
- external in this case means it's not something uBO can do (server side)
