### ISSUE TITLE
alfabeta.net: ads

### ISSUE THREAD

**Issue by Efexer** [uBlockOrigin/uAssets#10843]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.alfabeta.net/home/`

### Category

ads

### Describe the issue

Site plagued with ads, with ad pop-ups when clicking on certain links that disrupt browsing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/60304787/145499062-f86c8a09-9f2c-42f1-b6ea-23de88db5d7a.png)
![image](https://user-images.githubusercontent.com/60304787/145499103-38103ba8-35bf-48f7-976a-1b4c8b4670b5.png)
![image](https://user-images.githubusercontent.com/60304787/145499141-b29c19e3-dae3-406f-b2c5-4d2d54de8d92.png)
![image](https://user-images.githubusercontent.com/60304787/145499160-e2d88401-016b-4936-a436-48e1d9897a8e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77966
  cosmetic: 39631
  scriptlet: 16214
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30400-30, 8m
    ublock-badware: 3564-1, 8m
    ublock-privacy: 185-0, 8m
    ublock-abuse: 72-0, 8m
    ublock-unbreak: 1717-0, 8m
    easylist: 61565-554, 8m
    easyprivacy: 26478-475, 8m
    urlhaus-1: 7938-0, 8m
    plowe-0: 3697-3, 8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5306
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
add

```
alfabeta.net###banner_flotante
alfabeta.net###flotante
alfabeta.net##.publimg
```

@Yuki2718  spanish adguard list ?
