### ISSUE TITLE
[nsfw] scrolller.com: ads

### ISSUE THREAD

**Issue by BruhMomient** [uBlockOrigin/uAssets#10850]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://scrolller.com/`

### Category

ads

### Describe the issue

Ads interspersed with display images appearing on website
Just need to be added to filters I wager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 116846
  cosmetic: 94810
  scriptlet: 18951
  html: 598
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 23844-10702, never
    adguard-spyware-url: 399-1, never
    adguard-annoyance: 48335-1387, never
    adguard-social: 14878-18, never
    curben-phishing: 21399-5, never
    curben-pup: 389-2, never
  default: 
    ublock-filters: 30442-30, 2d.12h.20m
    ublock-badware: 3543-1, 2d.12h.18m
    ublock-privacy: 188-0, 2d.12h.16m
    ublock-abuse: 72-0, 2d.12h.13m
    ublock-unbreak: 1715-0, 2d.12h.11m
    easylist: 61349-552, 2d.12h.9m
    easyprivacy: 26464-477, 2d.12h.7m
    urlhaus-1: 7803-0, 22h.39m
    plowe-0: 3700-3, 8d.8h.31m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 312
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

**Comment by gorhill** [comment]
Try:

    scrolller.com##.native-ad-item-panel:upward(.vertical-view__item)
