### ISSUE TITLE
cars.mitula.ae: breakage

### ISSUE THREAD

**Issue by Ealdor-Nash** [uBlockOrigin/uAssets#10856]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://cars.mitula.ae/searchC/q-nissan-gtr?req_sgmt=REVTS1RPUDtTRU87U0VSUDs=`

### Category

breakage

### Describe the issue

Blocks elements that aren't ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/80765430/145585211-8466c65e-bf43-4b2c-8988-89eae1d66185.png)

![image](https://user-images.githubusercontent.com/80765430/145585305-e3858752-83c6-4c7a-b57d-1f774ae82477.png)

</details>

With uBlock on and off, clearly showing the issue

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 77733
  cosmetic: 39643
  scriptlet: 16210
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30398-29, 2h.1m
    ublock-badware: 3564-1, 1h.59m
    ublock-privacy: 187-0, 1h.57m
    ublock-abuse: 72-0, 1h.55m
    ublock-unbreak: 1718-0, 1h.53m
    easylist: 61593-555, 1h.51m
    easyprivacy: 26438-475, 3d.22h.44m
    urlhaus-1: 7725-0, 3h.44m
    plowe-0: 3696-3, 4d.18h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 398
  launchFromSelfie: false
popupPanel: 
  blocked: 9
```
</details>

**Comment by gorhill** [comment]
Caused by `##.adsList` from EasyList. cc @ryanbr, @Khrin
