### ISSUE TITLE
habilitant2012.pl: breakage

### ISSUE THREAD

**Issue by 1a1aiana** [uBlockOrigin/uAssets#10862]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://habilitant2012.pl/przyszlosc-bloga-2/`

### Category

breakage

### Describe the issue

When I open the page it works fine. But when I open another tab, and then return to this page, scrolling with arrow keys on the keyboard stops working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 81011
  cosmetic: 46984
  scriptlet: 16416
  html: 606
listset (total-discarded, last updated): 
  added: 
    https://adblock.fanimani.pl/fanimani-whitelist.txt: 1572-8, 1h.13m
    fanboy-thirdparty_social: 69-0, 1h.12m
  default: 
    ublock-filters: 30400-72, 1h.9m
    ublock-badware: 3564-1, 1h.7m
    ublock-privacy: 185-0, 55m
    ublock-abuse: 72-0, 53m
    ublock-unbreak: 1717-0, 51m
    easylist: 61623-570, 49m
    easyprivacy: 26478-475, 47m
    urlhaus-1: 7938-0, 45m
    plowe-0: 3687-3, 43m
    POL-0: 7752-26, 1h.18m
    POL-2: 1276-9, 1h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1867
  launchFromSelfie: false
popupPanel: 
  blocked: 12
```
</details>

**Comment by iam-py-test** [comment]
> `https://adblock.fanimani.pl/fanimani-whitelist.txt`

That list doesn't seem to use valid syntax:
`@@http://fanimani.pl/*^$document`?
Also, I think it is trying to allowlist using ABP's `@@$document` which isn't supported for a good reason

**Comment by Yuki2718** [comment]
On uBO `@@$document` only disables strict-blocking.

**Comment by 1a1aiana** [comment]
Thanks. I tested the page previously with the list removed, but the issue seemed to persist. Now I turned it off again, cleared the uBlock cache, restarted Firefox and it is fixed.
