### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by hebhaphop** [uBlockOrigin/uAssets#10863]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/watch?v=jRiYrl0RUhA`

### Category

breakage

### Describe the issue

youtube video isnt playing with ublock running. if i disable it, I get the ads and the video starts. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78009
  cosmetic: 39628
  scriptlet: 16269
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61593-7, never
    easyprivacy: 26467-18, never
    plowe-0: 3697-809, never
    ublock-abuse: 72-0, never
    ublock-badware: 3560-61, never
    ublock-filters: 29888-128, never
    ublock-privacy: 188-1, never
    ublock-unbreak: 1704-39, never
    urlhaus-1: 7938-0, never
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 25 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  dynamicFilteringEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 451
  launchFromSelfie: true
popupPanel: 
  blocked: 34
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gwarser** [comment]
Something wrong with your lists - they never be updated. Try purging and updating?
