### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by amuhav** [uBlockOrigin/uAssets#10869]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Describe the issue

ads, or "promoted pins" are no longer being detected/hidden. Only started happening within the last few days, I think.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77681
  cosmetic: 39188
  scriptlet: 16157
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 60746-451, never
    easyprivacy: 25518-212, never
    plowe-0: 3689-3, never
    ublock-abuse: 74-0, never
    ublock-badware: 3490-1, never
    ublock-filters: 29729-107, never
    ublock-privacy: 187-0, never
    ublock-unbreak: 1696-0, never
    urlhaus-1: 8813-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 808
  launchFromSelfie: false
popupPanel: 
  blocked: 3
```
</details>

**Comment by gorhill** [comment]
Possibly related to #10803.
