### ISSUE TITLE
adweek.com breakage

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#10867]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.adweek.com/agencies/new-data-shows-what-marketers-are-looking-for-with-media-agency-relationships/`

### Describe the issue

The **recommended articles** section is empty.

### Screenshot(s)

![Break22](https://user-images.githubusercontent.com/17685483/145672062-36e1027f-840f-4ff6-b175-9d9175666298.png)

### Notes

The `||connatix.com^$script,third-party` filter from the [EasyList](https://easylist.to/easylist/easylist.txt) causes this issue and this seems to fix it:
```
@@||cds.connatix.com/p/*/connatix.playspace.js$script,domain=adweek.com
@@||cd.connatix.com/connatix.playspace.js$script,domain=adweek.com
||adweek.com$removeparam=traffic_source
```

The last one is because the **recommended articles** section has a `?traffic_source=Connatix` at the end of it's URLs for tracking.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77996
  cosmetic: 39673
  scriptlet: 16265
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61637-7, 42m
    easyprivacy: 26483-17, 1m
    plowe-0: 3687-809, 1m
    ublock-abuse: 72-0, 1m
    ublock-badware: 3565-61, 1m
    ublock-filters: 29877-128, 1m
    ublock-privacy: 189-2, 1m
    ublock-unbreak: 1708-39, 1m
    urlhaus-1: 7922-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 358
  launchFromSelfie: false
```
</details>

**Comment by Yuki2718** [comment]
I don't see recommended articles even with connatix fully allowed by dynamic-allow.

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by MasterKia** [comment]
The **recommended articles** section is broken again.

Proposed filters:
```
@@||cds.connatix.com/p/*/connatix.playspace.css$stylesheet,domain=adweek.com
@@||capi.connatix.com/core/story?v=*$xhr,domain=adweek.com
@@||img.connatix.com^$image,domain=adweek.com
@@||vid.connatix.com^$xhr,domain=adweek.com
```

**Comment by MasterKia** [comment]
> Those are ads

It's _not_ ads, it's just some articles from the __website itself__.

[EasyList readme](https://github.com/easylist/easylist#easylist):
`First-party ads (that don't link, or passthrough to 3rd-party sites) won't be targeted directly.`

![image](https://user-images.githubusercontent.com/17685483/165301513-98b5b49d-9ef7-42e1-9c8c-4edfb5c06074.png)

**Comment by ryanbr** [comment]
connatix is third-party.

**Comment by ryanbr** [comment]
If a site needs to load connatix scripts to then create a link to their own site, they're doing it wrong.

**Comment by MasterKia** [comment]
Fair enough.

Anyway, this breakage has already been addressed in the _uBlock filters - Unbreak_ before (https://github.com/uBlockOrigin/uAssets/commit/6b09789c9d07b2aa7a482f6763222d8741248200).
So I guess it's up to the uAssets maintainers to decide and fix it again.
