### ISSUE TITLE
https://www.thisoldhouse.com/ Displays Cookie Acceptance Popup

### ISSUE THREAD

**Issue by q1800** [uBlockOrigin/uAssets#10861]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.thisoldhouse.com/

### Describe the issue

Recently, this website has started showing a Cookie Acceptance Popup at the bottom of the screen.

### Screenshot(s)

![thisoldhouse-cookie-popup](https://user-images.githubusercontent.com/95879668/145614153-e604029a-319b-437d-b481-1b6983bd787d.png)

### uBlock Origin version

1.39.3b7

### Browser name and version

Firefox Nightly 97.0a1 (20211210091034)

### Settings

N/A

**Comment by iam-py-test** [comment]
@q1800 uBlock Origin doesn't handle cookie consent, but @easylist does in Easylist Cookie. Try enabling it & seeing if it goes away

**Comment by gorhill** [comment]
Try:

    thisoldhouse.com##.m-privacy-options

Should be added to EasyList Cookies

cc @ryanbr, @Khrin

**Comment by q1800** [comment]
My apologies for opening this in the wrong repo or filter list authors github.

@iam-py-test I have enabled this filter list.

@gorhill I have added this to the My Filters pane and it works!

I look forward to this being in the EasyList Cookies in the future. 👍

Thank you for your kindness and quick responses!

**Comment by iam-py-test** [comment]
> My apologies for opening this in the wrong repo or filter list authors github.

That's ok - just be sure to report cookie related issues to https://github.com/easylist/easylist. As first issue reports go, you did pretty well.
> @iam-py-test I have enabled this filter list.
> 
> @gorhill I have added this to the My Filters pane and it works!
> 
> I look forward to this being in the EasyList Cookies in the future. 👍

Opened PR https://github.com/easylist/easylist/pull/10002
> Thank you for your kindness and quick responses!

**Comment by iam-py-test** [comment]
This issue now can be closed
