### ISSUE TITLE
sso.rumba.pk12ls.com: breakage

### ISSUE THREAD

**Issue by parkerj-cinnaminson** [uBlockOrigin/uAssets#10860]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://sso.rumba.pk12ls.com/`

### Category

breakage

### Describe the issue

When attempting to login the process hangs with uBO enabled.  Disabling uBO resolves this issue.  While understanding that not all urls should necessarily be whitelisted, below is the whitelisting guide from Pearson for this product:
https://support.savvas.com/s/article/What-URL-s-need-to-be-whitelisted-for-Pearson-SuccessNet-SuccessNet-Plus-and-Pearson-Realize

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77681
  cosmetic: 39188
  scriptlet: 16157
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 60746-451, never
    easyprivacy: 25518-212, never
    plowe-0: 3689-3, never
    ublock-abuse: 74-0, never
    ublock-badware: 3490-1, never
    ublock-filters: 29729-107, never
    ublock-privacy: 187-0, never
    ublock-unbreak: 1696-0, never
    urlhaus-1: 8813-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1173
  launchFromSelfie: false
popupPanel: 
  blocked: 1
```
</details>

**Comment by gorhill** [comment]
Does it work if you add the filter below?

    /google-analytics.$~image,badfilter

**Comment by mapx-** [comment]
@parkerj-cinnaminson  ? feedback ?

**Comment by parkerj-cinnaminson** [comment]
Very sorry for the delayed response.  We are a school district and closed
over the weekend.  I tested this today and it does appear to resolve the
issue for me.  I will confirm with a few of our teaching staff that also
encounter the issue to be certain that corrects the issue consistently.


Jason A. Parker
Technology Department
Cinnaminson Township Public Schools

**Comment by mapx-** [comment]
@ryanbr 

```
/google-analytics.$~image,badfilter
/google-analytics.$~image,domain=~rumba.pk12ls.com
```

**Comment by gorhill** [comment]
`/google-analytics.$badfilter` was already badfiltered in uBO, I just updated to `/google-analytics.$~image,badfilter` -- I wasn't aware the filter had changed in EP.

**Comment by mapx-** [comment]
ah, ok, however it would be better for other adblockers too

**Comment by iam-py-test** [comment]
@parkerj-cinnaminson same issue as https://github.com/uBlockOrigin/uAssets/issues/10946#issuecomment-996846427
You might want to edit your comments
