### ISSUE TITLE
[nsfw] nhentai.net: breakage

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [uBlockOrigin/uAssets#10873]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://nhentai.net/`

### Category

breakage

### Describe the issue

Buttons – tags are one example – are not operational, so navigation is solely possible by invoking new tabs.

### Screenshot(s)

This section is not relevant.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox Mobile: 94
filterset (summary): 
  network: 79874
  cosmetic: 21424
  scriptlet: 16252
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30522-197, 17h.6m
    ublock-badware: 3494-2, never
    ublock-privacy: 185-1, 45m
    ublock-abuse: 72-0, 16h.46m
    ublock-unbreak: 1724-0, 16h.44m
    adguard-mobile: 7005-172, 17h.15m
    easylist: 61624-24082, 16h.42m
    easyprivacy: 26478-483, 16h.40m
    urlhaus-1: 8445-0, 16h.38m
    plowe-0: 3687-3, 16h.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 736
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by uBlock-user** [comment]
> Buttons – tags are one example – are not operational, 

Explain what that is and how it doesn't work.

**Comment by gorhill** [comment]
Couldn't also reproduce an issue, clicking on a tag navigate to another page.

**Comment by mapx-** [comment]
`Firefox Mobile: 94`

on mobile, however I cannot reproduce using BlueStacks emulator

**Comment by Yuki2718** [comment]
Not reproduced on real Android as well, so added the label.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
The browser is “http://f-droid.org/en/packages/org.mozilla.fennec_fdroid”.

**Comment by gwarser** [comment]
I see no difference in navigation with or wihout uBO on Firefox Nightly and on Fennec. 

Select tags from menu then random tag and then choosing today/week/all time.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Sorry to bother you, but this is still (although very consistently inconsistently) occurring.

I reckon that it might be Fennec's fault, but I'm not certain, so if any of you are able to confirm (if you use Fennec) I'll be glad.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/10873#issuecomment-1199436422

This no longer occurs, although I'm using https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en_GB instead. If I ever try Fennec and this occurs again, then it's a fault of Fennec's.
