### ISSUE TITLE
eva.vn: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10878]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://eva.vn/`

### Category

ads

### Describe the issue

There are ads placeholders in the page. I have tested with only `EasyList` and `VIE: ABPVN List` and all the placeholders are hidden correctly (for small `Advertisement` placeholders you have to wait about 5s for it to collapse) so I don't think it's the problem of either of them.

I also tested with

`eva.vn##[id^="div-gpt-ad"][id^="div-gpt-ad"]`

but the placeholders only collapse after waiting about 5s (similar to the previous test).

Proposed filter:

`eva.vn##[id^="bnBAER"]`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![3](https://user-images.githubusercontent.com/66517106/145697750-71c04f4a-527b-4847-89b5-45fe45e8c7f3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78791
  cosmetic: 40922
  scriptlet: 16259
  html: 595
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2207-2, 53m
  default: 
    ublock-filters: 30431-134, 9m
    ublock-badware: 3569-1, 9m
    ublock-privacy: 185-0, 9m
    ublock-abuse: 72-0, 9m
    ublock-unbreak: 1724-0, 9m
    easylist: 61638-494, 53m
    easyprivacy: 26484-478, 11m
    urlhaus-1: 7830-0, 9m
    plowe-0: 3687-3, 9m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 203
  launchFromSelfie: true
popupPanel: 
  blocked: 15
```
</details>

**Comment by stephenhawk8054** [comment]
@hoang-rio Sorry for pinging you, could it be fixed in ABPVN?

**Comment by hoang-rio** [comment]
I can not reproduce in EasyList and ABPVN List so i dont know how to fix

**Comment by stephenhawk8054** [comment]
@Yuki2718 I guess the problem is not related to EasyList nor ABPVN List?

**Comment by Yuki2718** [comment]
@hoang-rio I can reproduce with EL + ABPNV alone. As I said in Slack and as described by @stephenhawk8054 , PH is temporal - may be a seconds depending on environment. The site collapses empty divs but for some reason occasionary fails to do so may leave permanent PH.

**Comment by hoang-rio** [comment]
> @hoang-rio I can reproduce with EL + ABPNV alone. As I said in Slack and as described by @stephenhawk8054 , PH is temporal - may be a second depending on environment. The site collapses empty divs but for some reason occasionary fails to do, so may leave permanent PH.

Currently i only have Android phone and i can not reprocedue. I will check with my PC when posible

**Comment by Yuki2718** [comment]
`eva.vn##section[id^="bnBAER_"]` or
```
eva.vn##.banrpstn
eva.vn##.banr-Rt
```

**Comment by hoang-rio** [comment]
@Yuki2718 Thanks. I will add this to ABPVN
