### ISSUE TITLE
aylink.info: detection

### ISSUE THREAD

**Issue by Raskeep** [uBlockOrigin/uAssets#10877]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://aylink.info/6TUcJ`

### Category

detection

### Describe the issue

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 80753
  cosmetic: 43770
  scriptlet: 16410
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61382-6, 3d.6h.16m
    easyprivacy: 26473-17, 3d.6h.14m
    plowe-0: 3698-811, 4d.2h.27m
    spa-0: 3462-20, 1d.1h.52m
    spa-1: 4200-160, 3d.6h.19m
    ublock-abuse: 72-0, 3d.6h.12m
    ublock-badware: 3560-61, 2d.2h
    ublock-filters: 29798-187, 3d.6h.10m
    ublock-privacy: 189-2, 3d.6h.8m
    ublock-unbreak: 1705-41, 3d.6h.6m
    urlhaus-1: 7847-0, 1d.1h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 944
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by MasterKia** [comment]
Add these to **my filters** and report back:
```
aylink.info#@#.ad-banner
aylink.info#@##ad-banner
```
