### ISSUE TITLE
filmisub.com: detection

### ISSUE THREAD

**Issue by strunz983** [uBlockOrigin/uAssets#10876]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://filmisub.com/`

### Describe the issue

Hi need help with this web site when i want to watch a some movies get this
how i can remove this
Thank you

### Screenshot(s)

![ublock](https://user-images.githubusercontent.com/42872580/145693292-4beb9381-2ab8-4791-b176-7eb99d0d794c.jpg)

### uBlock Origin version

uBlock Origin 1.39.2

### Browser name and version

Mozilla Firefox 95.0

### Settings

i install
Filters by hant0508 
AakList (Anti-Adblock Killer)
oxguy3's adblocking filters
RU AdList: Counters
RuAdList+EasyList
spiri-list Adblock
spiri-list Adblock Anti Adblock Beta

**Comment by MasterKia** [comment]
> i install
> Filters by hant0508
> AakList (Anti-Adblock Killer)
> oxguy3's adblocking filters
> RU AdList: Counters
> RuAdList+EasyList
> spiri-list Adblock
> spiri-list Adblock Anti Adblock Beta

I can't reproduce the issue on Chromium, Please try with uBO's **default filterlists** and report back.
Also the [Aaklist](https://github.com/reek/anti-adblock-killer) hasn't been updated for 5 years so you had better remove it.

**Comment by Yuki2718** [comment]
@strunz983 Test
```
filmisub.com##+js(set, noAdBlock, true)
filmisub.com##+js(set, adsNotBlocked, true)
filmisub.com##+js(set, detis, noopFunc)
```

**Comment by Yuki2718** [comment]
@strunz983 If you report next time, please provide the exact URL you have problem(s) and how to reproduce the issue. Otherwise we assume just visiting the URL is enough to reproduce.

**Comment by CDS2022** [comment]
https://filmisub.com/filmi/ekshani/6711-ladron-que-roba-a-ladron-da-oberesh-kradec-2007.html

Click the play button on the video. Ublock/Adblock warnings come right up.

When they implemented it first: I was able to fix it with the following rule, which no longer works.

! 2021-04-04 https://filmisub.com
@@||filmisub.com/templates/filmisub/js/fuckadblock.min.js$script,1p

I guess they refactored something, but hopefully, my previous rule can give some pointers? My javascript sucks so it's a pain finding what I need in these minimised files... 

HTML for the adblock detection mentions classes "jquery-rulesadi_img", not sure if this is helpfull.

**Comment by Yuki2718** [comment]
> Will these be merged into the normal rulelists?

They're added to uBlock filters. But since its update interval is 4 days, you'll need to force-update filter lists to get them immidiately. Filter lists > Purge all caches > Update now to force-update all lists, or click the clock icon to force-update specific list.

**Comment by CDS2022** [comment]
Seems they brought it back and obfuscated it even more.

**Comment by FanOfRootBeer** [comment]
dead site?
