### ISSUE TITLE
enchambered.com: breakage

### ISSUE THREAD

**Issue by Janybanny** [uBlockOrigin/uAssets#10874]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.enchambered.com/puzzles/alone-together/player1/`

### Category

breakage

### Describe the issue

The page gets suck on the loading screen of the online escape room (see screenshot). Happens both on Edge and Firefox. Doesn't happen wiht uBlockOrigin disabled.

The exact same happens with https://www.enchambered.com/puzzles/alone-together/player2/, but that should be the exact same issue, so I didn't report it twice.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211211_165728](https://user-images.githubusercontent.com/62150940/145683037-a2ae739a-4fdf-4cae-81ad-2297abdbf5a7.png)
 
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77949
  cosmetic: 39476
  scriptlet: 16238
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61405-7, 2d.15h.50m
    easyprivacy: 26477-17, 2d.15h.48m
    plowe-0: 3695-810, 6d.17h.47m
    ublock-abuse: 72-0, 2d.15h.46m
    ublock-badware: 3560-61, 2d.15h.44m
    ublock-filters: 29830-128, 2d.15h.42m
    ublock-privacy: 189-2, 2d.15h.40m
    ublock-unbreak: 1704-39, 2d.15h.38m
    urlhaus-1: 7938-0, 14h.50m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 169
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr @Khrin
