### ISSUE TITLE
discoveryplus.com: ads, breakage

### ISSUE THREAD

**Issue by nicolosesta** [uBlockOrigin/uAssets#10870]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-5-puntata-24-del-10-dicembre-2021`

### Category

ads

### Describe the issue

Since discoveryplus updated it's web site, Ublock can't detect and avoid commercials anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 83454
  cosmetic: 46776
  scriptlet: 16238
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ITA-0: 12573-0, 18h.8m
    easylist: 61410-10, 2d.6h.57m
    easyprivacy: 26477-19, 2d.6h.17m
    plowe-0: 3697-811, 1d.19h.54m
    ublock-abuse: 72-0, 2d.6h.15m
    ublock-badware: 3549-61, 2d.6h.13m
    ublock-filters: 29830-133, 2d.6h.10m
    ublock-privacy: 189-2, 2d.6h.8m
    ublock-unbreak: 1704-39, 2d.6h.6m
    urlhaus-1: 7847-0, 18h.6m
filterset (user): [array of 361 redacted]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 275
  launchFromSelfie: true
popupPanel: 
  blocked: 203
```
</details>

**Comment by Yuki2718** [comment]
Apparently the CM is included in playlist - don't know if it's removable.

**Comment by Yuki2718** [comment]
@ryanbr Maybe
```
||discoveryplus.com/events/
||h264.io/*/trackers/$xhr,domain=discoveryplus.com
```
?

**Comment by Yuki2718** [comment]
@mapx- Can you take a look? If I understand correctly, this - the first commercials in the video - is SSAI and can't be fixed.

**Comment by gorhill** [comment]
> is SSAI and can't be fixed.

I have added filters to fix SSAI on a few sites recently, `9now.com.au`. `threenow.co.nz, and a local one here, so it can be fixed if they expose `ad_config` in URL, you can `removeparam` it and this might work.
`

**Comment by Yuki2718** [comment]
These are the playlist URL (fetch): `https://dplus-it-prod-vod.akamaized.net/ssai/dep5-c1/v1/playlist/dash/1d40627e-b474-47d2-909c-a5c441810293/hdntl=exp=1639325298~acl=/ssai/dep5-c1/v1/playlist/dash/1d40627e-b474-47d2-909c-a5c441810293/*~data=hdntl~hmac=ed82434a2ff46b439d73a006d6e77ba6c3d62607634aaf42eb9744214a5f1c29/76125971-7952-57ab-a93a-a96e1111a68e.mpd?correlationId=YU6gMZZh6Y&ctx=CghkcGx1c19pdBIxVVNFUklEOmRwbGF5OmNlYzJlZmMwLTc4NjctNGI2YS05MDYxLTliOGQ4MWJiZDc2YhokZjk1ODI0OTUtNGI2My00NjNjLWE3ZGQtMzhmODY0YjY5OTM4IiQxZDQwNjI3ZS1iNDc0LTQ3ZDItOTA5Yy1hNWM0NDE4MTAyOTMqJDc2MTI1OTcxLTc5NTItNTdhYi1hOTNhLWE5NmUxMTExYTY4ZTILODQuMTcuNTkuNzg6Tk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2Ojk1LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTUuMEIMCLHM140GEJrznMMDSAM=`
`https://dplus-it-prod-vod.akamaized.net/ssai/dep1-c1/v1/playlist/dash/f7c23a6d-9a34-483d-a64e-d90893510acb/hdntl=exp=1639325828~acl=/ssai/dep1-c1/v1/playlist/dash/f7c23a6d-9a34-483d-a64e-d90893510acb/*~data=hdntl~hmac=c0ebd1d5c13d198121c6042b9e53ee2e53ecb98844dd11a4220fa3422d1e825f/76125971-7952-57ab-a93a-a96e1111a68e.mpd?ctx=CghkcGx1c19pdBIxVVNFUklEOmRwbGF5OjllOWVkNzU3LTQ4MjItNDg3OC1iNjNjLTM0MGQ4ZTMyYTgwMxokZGVhNjdiOTQtMTU5Zi00MmRmLTkxMmQtN2QyNjRkOWFhZDdmIiRmN2MyM2E2ZC05YTM0LTQ4M2QtYTY0ZS1kOTA4OTM1MTBhY2IqJDc2MTI1OTcxLTc5NTItNTdhYi1hOTNhLWE5NmUxMTExYTY4ZTILODQuMTcuNTkuNzg6Tk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2Ojk1LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvOTUuMEIMCMTQ140GEN_OiYcCSAM=`

Removing `cxt` breaks while `correlationID` has no effect. Not sure if something different can be targeted. Tried json-prune, no-fetch-if, and redirect as well but either don't work or break video.

**Comment by Yuki2718** [comment]
`/ads/banner_ad.js` is probably a bait but allowing this also is irrelevant.

**Comment by mapx-** [comment]
I tried as well but ... nothing

for example this js is full of SSAI inside
`https://www.discoveryplus.com/9-4eb1be15068c36c30c42.js`

**Comment by manuelvita96** [comment]
With premium account there is no ads, so maybe this information is passed in some way after login. If someone have a premium account and can help with this...

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1905

**Comment by mapx-** [comment]
> stephenhawk8054 => I access https://www.discoveryplus.com/it then scroll down to Disponibili per tutti section then click on the videos there -> They play fine for me.

**Comment by mapx-** [comment]
@stephenhawk8054 

well, I can reproduce the issue (FF / chrome), testing on this video from the section "disponibili" (il bello del mattone):
`https://www.discoveryplus.com/it/video/il-bello-del-mattone/stagione-2-vita-di-condominio`

I get 
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/cd364128-dbae-4318-9a78-4332a1b1e279)


If I click "esci" and then choose the same video, now I can watch it normally. (could be because the site "thinks" you already watched the ads)

It seems this filter is breaking it:

`discoveryplus.*##+js(xml-prune, xpath(//*[name()="MPD"][.//*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4')]]/@mediaPresentationDuration | //*[name()="Period"][./*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4')]]), , .mpd)`

**Comment by mapx-** [comment]
- first time xml-prune is rmeoving 13 items (all periods !)
- second time only 10 items

**Comment by mapx-** [comment]
I tried 

`discoveryplus.*##+js(xml-prune, xpath(//*[name()="Period"][starts-with(@duration,"PT15")][./*[name()="BaseURL"]] | //*[name()="Period"][starts-with(@duration,"PT30")][./*[name()="BaseURL"]] ), , .mpd, log, 1)`

but ... extract nothing (even if `http://xpather.com/` told me identifying 6 items)

**Comment by stephenhawk8054** [comment]
@mapx- I can't access my PC to check it right now but you can use this site, it has similar xpath test like uBO. If it can extracts fine, then it would be fine in uBO too

https://extendsclass.com/xpath-tester.html

**Comment by stephenhawk8054** [comment]
@mapx- Oh, did you escape `,` yet?

**Comment by mapx-** [comment]
hmm, right, escaping , works .. but I still get ads (I thought to block the items of 15s / 30s)

**Comment by stephenhawk8054** [comment]
@mapx- Hmm... It's hard for me to reproduce > 10 `dash_clear_fmp4 `. I tried many times but it's always 10 of them (less than number of `Period`).

If you can reproduce > 10, can you share the XML content?

**Comment by mapx-** [comment]
This morning seems to work:

- I whitelisted your `xml-prune` filter
- added:
    discoveryplus.*##+js(xml-prune, xpath(//*[name()="Period"][starts-with(@duration\,"PT15")][./*[name()="BaseURL"]] | //*[name()="Period"][starts-with(@duration\,"PT30")][./*[name()="BaseURL"]] ), , .mpd, log, 1)

2 xml - 2 different episodes:
- x1 => 12 `Period`, 12 `dash_clear_fmp4`
- x2 => 24 `Period`, 24 `dash_clear_fmp4` => 15 filtered out (9 PT15 + 6 PT30)

https://www.mediafire.com/folder/x3flem7k484c4/tech

**Comment by mapx-** [comment]
@MilosBranko

add & test (see if the breakage is gone and the ads too)

    discoveryplus.*#@#+js(xml-prune, xpath(//*[name()="MPD"][.//*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4')]]/@mediaPresentationDuration | //*[name()="Period"][./*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4')]]), , .mpd)
    discoveryplus.*##+js(xml-prune, xpath(//*[name()="Period"][starts-with(@duration\,"PT15")][./*[name()="BaseURL"]] | //*[name()="Period"][starts-with(@duration\,"PT30")][./*[name()="BaseURL"]] ), , .mpd, log, 1)

**Comment by mapx-** [comment]
it seems ok, working without that error
