### ISSUE TITLE
tf1.fr: breakage

### ISSUE THREAD

**Issue by maximevdl** [uBlockOrigin/uAssets#10872]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-deuxieme-partie-du-10-decembre-2021-10477648.html`

### Category

breakage

### Describe the issue

When you want to watch a replay on the site it says on the video player :
"Pour regarder l’ensemble des Replay, Stream et le direct, vous devez accepter les cookies."
which translates to : "To watch all Replay, Stream and Live, you must accept cookies."

When you click on "Modifier vos choix" (Edit your choices)
They force you to click on "Modifier et tout accepter" (Edit and accept all) to be able to watch replays.
But then you get a red message on the bottom of the page stating : 
"Nous ne parvenons pas à mettre à jour vos consentements, veuillez vérifier que vous n'avez pas un bloqueur de publicité et réessayez"
which translates to : "We are unable to update your consents, please check that you do not have an ad blocker and try again"

It leaves us with no way to watch the replay while UBO is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tf1](https://user-images.githubusercontent.com/33755812/145680963-cf29c7dd-a788-4673-aa89-75c10d6c8659.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 93952
  cosmetic: 48796
  scriptlet: 16274
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30429-204, now
    ublock-badware: 3569-1, now
    ublock-privacy: 185-0, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1720-0, now
    easylist: 61639-678, now
    easyprivacy: 26484-475, now
    urlhaus-1: 7779-0, now
    plowe-0: 3687-3, now
    FRA-0: 25976-372, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 363
  launchFromSelfie: false
popupPanel: 
  blocked: 8
```
</details>

**Comment by mapx-** [comment]
test

`@@||cdn.trustcommander.net/privacy/$script,domain=tf1.fr`

**Comment by maximevdl** [comment]
It seems to have solved the problem. Thank you!

**Comment by mapx-** [comment]
@ryanbr
