### ISSUE TITLE
cheatermad.com: detection

### ISSUE THREAD

**Issue by HEJiNi** [uBlockOrigin/uAssets#10884]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://cheatermad.com/`

### Category

detection

### Describe the issue

Detects Ublock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78550
  cosmetic: 40383
  scriptlet: 16256
  html: 0
listset (total-discarded, last updated): 
  added: 
    IRN-0: 1311-0, 1d.16h.48m
  default: 
    easylist: 61612-10, 1d.17h.1m
    easyprivacy: 26478-17, 1d.16h.59m
    plowe-0: 3697-811, 5d.17h.43m
    ublock-abuse: 72-0, 1d.16h.57m
    ublock-badware: 3565-61, 1d.16h.55m
    ublock-filters: 29849-130, 1d.16h.53m
    ublock-privacy: 189-2, 1d.16h.51m
    ublock-unbreak: 1707-39, 1d.16h.46m
    urlhaus-1: 7922-0, 19h.1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 200
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

**Comment by MasterKia** [comment]
Add `cheatermad.com##+js(set, adblock.check, noopFunc)`  to **my filters** and report back.
