### ISSUE TITLE
usatoday.com: nuisance

### ISSUE THREAD

**Issue by NylaTheWolf** [uBlockOrigin/uAssets#10881]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.usatoday.com/story/tech/columnist/komando/2013/05/17/google-maps-duckduckgo-web-history/2155759/`

### Category

nuisance

### Describe the issue

I went to a USA Today article only to encounter an overlay asking me to subscribe and a video ad in the corner of the screen. The video seems to have been automatically paused but it's still there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2112112348_firefox](https://user-images.githubusercontent.com/41797151/145700710-f5882c19-0c8e-467c-8da4-ee26052e87fa.png)
![2112112347_firefox](https://user-images.githubusercontent.com/41797151/145700709-9696d036-cb67-4908-9125-3eaea846669f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 135638
  cosmetic: 144407
  scriptlet: 21091
  html: 608
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1551-0, 23h
    adguard-spyware-url: 399-67, 1d.3h.29m
    adguard-annoyance: 48359-4109, 1d.3h.15m
    adguard-social: 14894-1081, 1d.3h.13m
    fanboy-thirdparty_social: 69-0, 23h.4m
    fanboy-annoyance: 59048-84, 23h.2m
    ublock-annoyances: 4327-127, 1d.3h.10m
    dpollock-0: 16978-1920, 6d.7h.22m
    mvps-0: 8730-464, 10d.2h.10m
    curben-phishing: 21410-5, 1d.3h.8m
    curben-pup: 0-0, 1d.3h.6m
  default: 
    ublock-filters: 30409-157, 1d.3h.31m
    ublock-badware: 3569-1, 1d.3h.27m
    ublock-privacy: 187-0, 1d.3h.25m
    ublock-abuse: 72-0, 1d.3h.23m
    ublock-unbreak: 1718-0, 1d.3h.21m
    easylist: 61627-77, 1d.3h.19m
    easyprivacy: 26480-945, 1d.3h.17m
    urlhaus-1: 7779-0, 4h.3m
    plowe-0: 3687-373, 1d.3h.33m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7500
  launchFromSelfie: true
popupPanel: 
  blocked: 41
```
</details>

**Comment by mapx-** [comment]
I get no "subscribe stuff"

for the right side video add

```
usatoday.com##.tealplayer-ad-container
usatoday.com##.gnt_em_vp__tavp
```

@ryanbr

**Comment by stephenhawk8054** [comment]
I tested with this link

`https://sportsbookwire.usatoday.com/2022/05/05/bet-slippin-podcast-nba-conference-semifinals-game-3-betting-previews/`

But still can't hear audio ads on both Firefox and Chromium. Are there any special steps to reproduce?

**Comment by PIZZA90** [comment]
is random test whit CTRL+F5 a few times in the same post.. and press the play button in every refresh...

**Comment by mapx-** [comment]
test this filter

`||exchange.remixd.com/vast/`
