### ISSUE TITLE
Stressless.com - Broken functions (uBlock filters - Privacy)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#10898]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.stressless.com/`

### Affected site:
`https://www.stressless.com/`

### Issue:
Broken functions.

### Example:
`https://shop.stressless.com/en/c/recliners/`

Try to click on one of the products..
Nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **uBlock filters - Privacy**

### Problem rules:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js`
`||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js`
`||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js`
(The former rule for uBO's main branch / the two latter ones for uBO Legacy)

### Possible fix:
`@@||googletagmanager.com/gtm.js$domain=stressless.com`
`@@||google-analytics.com/analytics.js$domain=stressless.com`
(uBO's main branch only needs the first one / uBO Legacy needs both)

### Other problem filters:
* **AdGuard Tracking Protection filter** https://github.com/AdguardTeam/AdguardFilters/issues/103018/
`||googletagmanager.com/gtm.js?$third-party`
`||googletagmanager.com/gtm.js?$third-party,script,redirect=google-analytics_ga.js,domain=~corsair.com|~olx.*|~simon.com|~bethesda.net`

* ~~**EasyPrivacy** https://github.com/easylist/easylist/issues/10037/~~ _(FIXED)_
~~`/gtm.js`
`.google-analytics.com/`
`||google-analytics.com^$third-party`
`||googletagmanager.com^`~~

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`google-analytics.com`
`googletagmanager.com`
`www.google-analytics.com`
`www.googletagmanager.com`

* **MVPS HOSTS**
`google-analytics.com`
`www.google-analytics.com`

* **Peter Lowe's Ad and tracking server list**
`googletagmanager.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Chromium [ungoogled] v96.0.4664.93-r929512 / Pale Moon v29.4.2.1 (x64)
* Adblock Extension/version: uBlock Origin v1.39.2 / uBlock Origin v1.16.4.30 (XUL)

### uBlock Origin version

v1.39.2 / v1.16.4.30 (XUL)

### Browser name and version

Chromium [ungoogled] v96.0.4664.93-r929512 / Pale Moon v29.4.2.1 (x64)

### Settings

--

**Comment by uBlock-user** [comment]
> Try to click on one of the products..

"Products" at the top ? or an actual product. Either way works fine in Chrome and Firefox.

**Comment by THEtomaso** [comment]
> "Products" at the top ? or an actual product ?

Actual products.

--

> Either way works fine in Chrome and Firefox.

Probably location-depended then.
@DandelionSprout: Could you confirm this?

**Comment by uBlock-user** [comment]
> Actual products.

Example ?

**Comment by THEtomaso** [comment]
> Example ?

I've already included an example link, in my first post.

**Comment by uBlock-user** [comment]
No, I meant example of a product that I should click to reproduce the breakage you're experiencing.

**Comment by THEtomaso** [comment]
Any of the chairs.

**Comment by uBlock-user** [comment]
I clicked on "Stressless® Mayfair" and I'm sent to `https://shop.stressless.com/en/c/Recliners/mayfair`

**Comment by uBlock-user** [comment]
Did you try on Chrome instead of Ungoogled Chromium ? It's an experimental browser and is known to harbour breakages.

**Comment by THEtomaso** [comment]
No, but as I mentioned in my first post; the issue occurs with Pale Moon too.

**Comment by gorhill** [comment]
I cannot reproduce an issue with stable Chromium. If we can't reproduce with supported browsers, we won't add a filter in default lists.

**Comment by THEtomaso** [comment]
Let's wait and see if it's location-dependent, rather than browser-dependent.

**Comment by gorhill** [comment]
I also couldn't reproduce using an ITA VPN server.

**Comment by THEtomaso** [comment]
Still, I'd like to see what DandelionSprout has to say about it.
If it's a Pale Moon / Chromium-ungoogled -ony issue, that would be a first for me.

**Comment by iam-py-test** [comment]
I can reproduce in Mozilla Firefox - might just be my config though

**Comment by uBlock-user** [comment]
> might just be my config though

Not on default lists ?

**Comment by iam-py-test** [comment]
> > might just be my config though
> 
> Not on default lists ?

Let me test...

**Comment by mapx-** [comment]
well, real issue but you have to go to norvegian version:

go here:
`https://shop.stressless.com/nb-no/lenestoler/stressless-mayfair/p/000000000001731015`

click an item

(FF / chrome)
I used a norwegian vpn

**Comment by gorhill** [comment]
Still not able to reproduce an issue on my side with NO VPN, everything I click does work.

**Comment by uBlock-user** [comment]
No issues, clicked on two items at the end with Norwegian IP address and both opened in new tabs.

**Comment by THEtomaso** [comment]
> For those who can reproduce, does preventing the redirect rule filter works?

Yes, I've already pointed this out, in my first post.

Update:
Instead of whitelisting GA and GTM, blocking this script also allows the product pages to open for me, when clicked:
`https://shop.stressless.com/wro/all_responsive.js`
..although, as a side-effect, all of the product details fails to load!
Perhaps the script could be manipulated with some type of `##+js` rule?

**Comment by mapx-** [comment]
mmhmm, steps:

- FF, no vpn
- go to `https://www.stressless.com/nb-no/inspirasjon/stue`
- clear all cookies / other data
- ctrl + F5
- click one of these items:

![image](https://user-images.githubusercontent.com/10303732/145867466-9fe4faf1-19b4-43bd-b32d-3f3ddfc942dd.png)
- nothing happens
- reload the page => the items are clickable now

Someone can reproduce it ?
`redirect-rule=none` does not help

**Comment by THEtomaso** [comment]
> reload the page => the items are clickable now

Simply reloading doesn't fix it for me.

**Comment by mapx-** [comment]
and more (tested in FF):
adding the exception:
`@@||googletagmanager.com/gtm.js$domain=stressless.com`

does not fix the issue

**Comment by THEtomaso** [comment]
> does not fix the issue

In FF, perhaps you need that other whitelisting that I included in my first post too?

**Comment by mapx-** [comment]
well ... even disabling uBO, I get the same behaviour, so ... site issue.

**Comment by THEtomaso** [comment]
At my end, adding the two whitelistings, which I suggested in my first post, fixes the issue completely (no reload needed)!

**Comment by okiehsch** [comment]
>  Without them, the products can't be clicked, even if I reload the page a bunch of times!

Reloading fixes the issue on my end.

> even disabling uBO, I get the same behaviour

Using chromium disabling uBO fixes the issue for me.

**Comment by okiehsch** [comment]
`@@||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js,domain=stressless.com`
fixes the issue on my end.

**Comment by THEtomaso** [comment]
Even in uBO's main branch, that rule doesn't fix the issue at my end.

**Comment by THEtomaso** [comment]
Unless someone can come up with a clever `##+js` rule, to manipulate this script:
`https://shop.stressless.com/wro/all_responsive.js`
..this currently seems to be the best solution (however undesired as it might be):
```
@@||googletagmanager.com/gtm.js$domain=stressless.com
@@||google-analytics.com/analytics.js$domain=stressless.com
```
