### ISSUE TITLE
pumpkin.care: breakage

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#10890]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.pumpkin.care/plan-selection/c9fdb31f-7500-47f8-b6e8-220894f297d5`

### Category

breakage

### Describe the issue

You get a "Ruh Roh!" message when trying to view the plan details. It is due to the `||lr-ingest.io^$3p` rule from EasyPrivacy. I was able to fix it locally by adding this custom rule: `@@||cdn.lr-ingest.io/logger.min.js$script,domain=www.pumpkin.care`

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 77784
  cosmetic: 39611
  scriptlet: 16202
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30413-128, 2d.22h.43m
    ublock-badware: 3564-1, 2d.22h.51m
    ublock-privacy: 185-0, 2d.22h.45m
    ublock-abuse: 72-0, 2d.22h.55m
    ublock-unbreak: 1717-0, 2d.22h.49m
    easylist: 61565-456, 2d.22h.53m
    easyprivacy: 26478-475, 2d.22h.47m
    urlhaus-1: 7727-0, 1h.48m
    plowe-0: 3687-3, 39m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2648
  launchFromSelfie: true
popupPanel: 
  blocked: 14
```
</details>

**Comment by mapx-** [comment]
@ryanbr
