### ISSUE TITLE
sakarnewz.com: detection

### ISSUE THREAD

**Issue by xRIN1** [uBlockOrigin/uAssets#10896]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://sakarnewz.com/`

### Category

detection

### Describe the issue

detects the adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78016
  cosmetic: 39687
  scriptlet: 16349
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61728-7, 1m
    easyprivacy: 26486-17, 1m
    plowe-0: 3696-810, 7d.4h.13m
    ublock-abuse: 81-0, 1m
    ublock-badware: 3570-61, 1m
    ublock-filters: 29965-131, 1m
    ublock-privacy: 189-2, 1m
    ublock-unbreak: 1715-39, 1m
    urlhaus-1: 7830-0, 22h
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 145 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 389
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by sugarfreesweetener** [comment]
`sakarnewz.com##+js(nostif, show)`
