### ISSUE TITLE
uBlock blocks embedded videos and music on Facebook

### ISSUE THREAD

**Issue by n-o-o-b** [uBlockOrigin/uAssets#109]
### URL(s) where the issue occurs

https://www.facebook.com/DanceTunnel (example of page with embedded Bandcamp track)
https://www.facebook.com/LongLiveSouthbank (example of page with embedded Vimeo video. There is also an embedded YouTube video four posts below)
https://www.facebook.com/youtube/?fref=ts (example of page with embedded YouTube videos; not included in screenshots)

### Describe the issue

uBlock Origin is blocking videos from YouTube and Vimeo and tracks from Bandcamp embedded in Facebook posts, after they are clicked on. I'm sure other similar services are also being blocked but these are the only ones I have encountered personally.

### Screenshot(s)

Please see original closed issue at gorhill/uBlock

### Versions

- Browser/version: 48.0.2
- uBlock Origin version: 1.8.4

### Settings

All default settings, except I've unticked "Show the number of blocked requests on the icon".

### Notes
...

**Comment by n-o-o-b** [comment]
I originally posted this in gorhill/uBlock but was told it belongs here.

The first person who commented on the issue solved it for me by telling me to add a filter to 'My filters', for which I am grateful.

I'm not trying to annoy anyone by re-posting this here, I just want to ask: isn't uBlock supposed to not block these kinds of things by default? I know it's as simple as adding a filter, but shouldn't everything work properly and not be broken by default? I have just tried using ABP on the same Facebook pages and I realise it has the same problem. If EasyPrivacy is responsible for this, then could anyone explain the reasoning behind these embedded videos being blocked? Or is it just an unintended bug? The reason I am asking is because I feel that users (who like to use Facebook) who don't have advanced knowledge or don't know where to enquire will simply be put off using these extensions when they realise this part of Facebook is not working properly.

I would have liked to simply post this as comments on my original issue but I was blocked from commenting further. The reason I am posting this here is because I would like a response,  I would greatly appreciate it if this issue was not closed without responding.

**Comment by jjohns71** [comment]
Might be helpful for someone down the road, so posting the fix on this thread as well.

Comment that fixed issue that OP is referencing: https://github.com/gorhill/uBlock/issues/1933#issuecomment-242368677

Filter to add to 'My filters':

> @@||staticxx.facebook.com/common/referer_frame.php$subdocument,domain=www.facebook.com

**Comment by gorhill** [comment]
Issue is with EasyPrivacy, but given [it's taking long to fix](https://forums.lanik.us/viewtopic.php?f=62&t=32147&p=101283), I added a temporary fix in a5417d5698f0aaec93bec48d9a1990dde8e4970f, until fix is added to EasyPrivacy.

**Comment by n-o-o-b** [comment]
@gorhill So will I need to remove the filter that I added to 'My filters' when there is a permanent fix?

How do I force an update of that? I'm assuming that's what I need to do to get your temporary update? Do I still need to do this now that I've added a the filter the guy on my original issue suggested?

Sorry for all the questions, I'm just trying to make sense of this.

**Comment by gorhill** [comment]
You can remove the filter once you have the updated filter list.

To force the update of a specific filter list, click the _purge cache_ button aside it, then click the _Update now_ button.

**Comment by n-o-o-b** [comment]
I've updated the filter list and removed the filter I added and it works, thank you very much for your help. It is very frustrating when your issue is closed without any response or the ability to ask further questions, so thanks for responding to this one.

**Comment by gorhill** [comment]
> It is very frustrating when your issue is closed without any response

It's very time-consuming to have to deal with invalid issues, even more so if I have to explain each time why by merely repeating what is already stated in CONTRIBUTING. Earlier today I added to CONTRIBUTING:

> Given the amount of [invalid issues](https://github.com/gorhill/uBlock/issues?q=is%3Aissue+label%3Ainvalid+is%3Aclosed) being opened, I have no choice but to resort to such a drastic measure.

As the maintainer of this project, that is the step I have been forced to take in order to keep the project manageable.
