### ISSUE TITLE
new-rutor.org: breakage

### ISSUE THREAD

**Issue by feijoaaa** [uBlockOrigin/uAssets#10900]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://new-rutor.org/`

### Category

breakage

### Describe the issue

/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 95820
  cosmetic: 36038
  scriptlet: 17787
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40380-826, 12h.57m
    easylist: 61638-23426, 1d.16h.8m
    easyprivacy: 26484-114, 1d.16h.6m
    plowe-0: 3700-814, 11d.14h.57m
    ublock-abuse: 72-1, 1d.16h.4m
    ublock-badware: 3565-62, 1d.16h.2m
    ublock-filters: 29867-312, 1d.16h
    ublock-privacy: 189-3, 1d.15h.57m
    ublock-unbreak: 1713-39, 1d.15h.55m
    urlhaus-1: 7817-0, 25m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 667
  launchFromSelfie: true
popupPanel: 
  blocked: 10
  no-cosmetic-filtering: true
```
</details>

**Comment by mapx-** [comment]
add

`new-rutor.org#@#:not(obhod-adblocka)`

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
It should be so. This is a fake tracker that promotes malicious software. 

True rutor trackers addresses: `http://rutor.info/`, `http://rutor.is/`, etc.

**Comment by mapx-** [comment]
ah, ok , closing
