### ISSUE TITLE
form on gab.money wouldn't load

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#10908]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gab.money/pre-app?` *when you click on "continue"*

### Describe the issue

The form wouldn't load because of the rule `||frog.wix.com^$ping` in EasyPrivacy

The rule I propose is: `@@||frog.wix.com/bt$ping,domain=gab.money`

### uBlock Origin version

1.39.2

### Browser name and version

MS Edge, v96

### Settings

```
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 66675
  cosmetic: 41528
  scriptlet: 16339
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/r/fanboy-complete.txt: 91241-93, 5h.14m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1780-3, 5h.14m
  default: 
    ublock-filters: 29993-186, 5h.4m
    ublock-unbreak: 1705-47, 5h.2m
filterset (user): [array of 147 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  launchToReadiness: 24815
  launchFromSelfie: false
```

**Comment by gorhill** [comment]
The form loads fine with default settings/lists.

> - [X] uBO with default lists/settings
> - [X] using a new, unmodified browser profile

Did you **really** test with default settings/lists?

**Comment by iam-py-test** [comment]
No issue even not on default settings. Try disabling other extensions like NoScript or those ones added by your antivirus, and check to see if you are using DNS or HOSTs level blocking

**Comment by JohnyP36** [comment]
I'm sorry for burdening you. It had to do with a bad internet connection, which caused it not to load immediately and correctly.
