### ISSUE TITLE
Current filters not work

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#10903]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
pendujatt.net  -- can't repro --
123moviesfree4u.com -- can't repro -- 
https://w.123moviesla.site/red-notice-2021/?id=player1 -- can't repro -- 
afilmyhouse.blogspot.com -- fixed -- 
allmovieshub.pw -- can't repro --
attvideo.com -- can't repro --
filmyzillafilmywap.co.in -- can't repro --
foreverwallpapers.com -- can't repro -- 
gtrmovies.com -- fixed --
https://hitmovies4u.com/movies/bob-biswas-2021/watching.html/  -- fixed -- 
yify.stream -- can't repro --
daddylive.click from http://www.live7v.com/c/field-hockey/asian-champions-trophy/14-12-2021/south-korea-vs-india/1/
filmypur.org
https://pirlotv.mx/canal-36.php -- can't repro --
mob.livecricket.is
https://linksmore.xyz/view/2tHeYhTAcR -- can't repro --
```

### Describe the issue

popup ads

### uBlock Origin version

1.39.2

### Browser name and version

firefox/firefox a/ opera browser stable

### Settings

Default

### Notes

html filters work for firefox
iam looking for filters working on all browsers

**Comment by okiehsch** [comment]
I only checked the first two domains and there are no popups on my end using Chromium or Firefox.
````
pendujatt.net
123moviesfree4u.com
`````

**Comment by mapx-** [comment]
no issue with `linksmore`

**Comment by okiehsch** [comment]
Some are using older versions of the script.

**Comment by okiehsch** [comment]
I checked all domains and indicated in the first post if I can reproduce or if the site was fixed.
I can't connect to 
`http://www.live7v.com/c/field-hockey/asian-champions-trophy/14-12-2021/south-korea-vs-india/1/`
and 
`filmypur.org`.

**Comment by ghajini** [comment]
Except for filmypur.org(which is 404 not found error) and pendujatt.net, i can reproduce all

so please add

```
123moviesfree4u.com,123moviesla.*,afilmyhouse.blogspot.com,allmovieshub.*,attvideo.com,daddylive.*,filmyzillafilmywap.*,foreverwallpapers.com,gtrmovies.com,hitmovies4u.com,linksmore.xyz,livecricket.*,pirlotv.*,yify.*##^script:has-text(break;case $.)
```

note there are some tld changes in websites wrt filters in ublock origin

**Comment by ghajini** [comment]
i will make PR for some others
