### ISSUE TITLE
seznam.cz: ads

### ISSUE THREAD

**Issue by JanecekPetr** [uBlockOrigin/uAssets#10904]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Describe the issue

This probably should go to the "CZE, SVK: EasyList Czech and Slovak" which I have enabled and up-to-date.

The seznam.cz site has been showing a medium-sized ad for a week now, both when logged out and logged in, both in 2-column layout (default) and 3-column layout.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1746404/145991606-287f5860-9552-43cc-9d26-ffe3b327ffc6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78081
  cosmetic: 40013
  scriptlet: 16537
  html: 595
listset (total-discarded, last updated): 
  added: 
    CZE-0: 772-0, 16h.25m
  default: 
    ublock-filters: 30517-32, 1d.52m
    ublock-badware: 3574-1, 1d.50m
    ublock-privacy: 185-1, 1d.48m
    ublock-abuse: 81-0, 1d.46m
    ublock-unbreak: 1715-0, 16h.27m
    easylist: 61726-557, 1d.54m
    easyprivacy: 26486-480, 1d.44m
    urlhaus-1: 7704-0, 16h.23m
    plowe-0: 3687-2, 3d.19h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1067
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
@addisr

**Comment by Pavel-71** [comment]
Mám stejné problémy

**Comment by mapx-** [comment]
@Pavel-71 

what about

```
||seznam.cz/$frame,1p
seznam.cz##+js(nostif, 0x)
@@||seznam.cz^$ghide,badfilter
```

**Comment by Pavel-71** [comment]
This works thank you

so 25. 3. 2023 v 16:36 odesílatel mapx ***@***.***> napsal:
