### ISSUE TITLE
myanimelist.net: ads

### ISSUE THREAD

**Issue by along02** [uBlockOrigin/uAssets#10905]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://myanimelist.net/`

### Category

ads

### Describe the issue

There are ads on the top and sidebars. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/21041802/146013743-9c646818-719a-400f-8d30-67fd9bd84487.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 81660
  cosmetic: 81633
  scriptlet: 18642
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 84-0, 2m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 307-0, 2m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 13-13, 2m
    adguard-annoyance: 48390-144, 2m
  default: 
    easylist: 61761-46, 2m
    easyprivacy: 26495-109, 2m
    plowe-0: 3690-810, 2m
    ublock-abuse: 81-0, 2m
    ublock-badware: 3570-61, 2m
    ublock-filters: 29993-415, 2m
    ublock-privacy: 188-7, 2m
    ublock-unbreak: 1716-41, 2m
    urlhaus-1: 7432-0, 2m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 115056
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
```
myanimelist.net##.ad-sticky-wrapper
myanimelist.net##.pda_top
```

@ryanbr
