### ISSUE TITLE
titantv.com: nuisance

### ISSUE THREAD

**Issue by Ocelotsden** [uBlockOrigin/uAssets#10914]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.titantv.com/default.aspx`

### Category

nuisance

### Describe the issue

Opens video player and plays video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77889
  cosmetic: 39676
  scriptlet: 16263
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61630-7, 3d.15h.54m
    easyprivacy: 26480-17, 3d.15h.52m
    plowe-0: 3698-810, 6d.47m
    ublock-abuse: 72-0, 3d.15h.50m
    ublock-badware: 3565-61, 3d.15h.48m
    ublock-filters: 29882-130, 3d.15h.46m
    ublock-privacy: 189-2, 3d.15h.44m
    ublock-unbreak: 1704-39, 3d.15h.41m
    urlhaus-1: 7817-0, 22h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 607
  launchFromSelfie: true
popupPanel: 
  blocked: 68
```
</details>

**Comment by ghajini** [comment]
If you mean stopping autoplay of video
https://github.com/uBlockOrigin/uAssets/issues/59#issuecomment-223708422
