### ISSUE TITLE
stoic.ai tracking

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#10918]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://stoic.ai/main?`

### Describe the issue

I see many requests from `anti-adblock.herokuapp.com`. It loads many stuff like google tag manager.

I also see a 1x1 pixel coming from `https://www.google.ie/pagead/1p-user-list/...` with display solution, color depth, java on/off, plugins, a few IDs and the actual URL in the image url

It also has `d.a.t.a.u.n.l.o.c.k.e.r` but there is already a seperate issue https://github.com/uBlockOrigin/uAssets/issues/9932

### uBlock Origin version

1.39.2

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

### Notes

`herokuapp.com` has real content, only `anti-adblock.herokuapp.com` seems suspect

**Comment by uBlock-user** [comment]
> I also see a 1x1 pixel coming from

Blocked when added `||anti-adblock.herokuapp.com^`

**Comment by mapx-** [comment]
@ryanbr

**Comment by JobcenterTycoon** [comment]
ryanbr know this for 8 days already but no filter got added

**Comment by JobcenterTycoon** [comment]
@uBlock-user the filter `stoic.ai##+js(acis, Math.floor, Number.MAX_SAFE_INTEGER)` works on `stoic.ai` but not on `app.stoic.ai`

**Comment by uBlock-user** [comment]
@JobcenterTycoon `||cdn.cindicator.com/$script,3p` is there for that.

**Comment by JobcenterTycoon** [comment]
@uBlock-user 
Only for `app.stoic.ai` but on the main site `stoic.ai` there is no request from `cdn.cindicator.com` its all inline

**Comment by uBlock-user** [comment]
filter updated

**Comment by RinatGumarov** [comment]
This filter also brakes app.stoic.ai

**Comment by mapx-** [comment]
What is broken ? provide test account or a screenshot with all blocked items in the logger

**Comment by uBlock-user** [comment]
> This filter also brakes

what is broken ?

**Comment by RinatGumarov** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8749592/151113642-b21df489-49d4-4892-9f8d-ce0f696b0b39.png">

**Comment by JobcenterTycoon** [comment]
What about `data-saver-cindi.herokuapp.com`? Their repaired it and it fires much tracking crap again
