### ISSUE TITLE
spanishdict.com: detection

### ISSUE THREAD

**Issue by 0xCUB3** [uBlockOrigin/uAssets#10917]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.spanishdict.com/`

### Category

detection

### Describe the issue

uBlock origin gets detected by the site and a popup shows up that says I have 5 pages remaining. When that count goes to 0, the popup comes up and completely blocks me from the website until I turn off uBlock Origin. This is super annoying, I don't want to deal with the site's stupid ads. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78608
  cosmetic: 39705
  scriptlet: 16309
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30526-30, 1h.27m
    ublock-badware: 3513-1, 1h.25m
    ublock-privacy: 179-0, 1h.22m
    ublock-abuse: 81-0, 1h.20m
    ublock-unbreak: 1727-0, 1h.18m
    easylist: 61777-558, 1h.16m
    easyprivacy: 26495-476, 1h.14m
    urlhaus-1: 8445-0, 1h.12m
    plowe-0: 3690-3, 1h.10m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1925
  launchFromSelfie: false
popupPanel: 
  blocked: 16
```
</details>

**Comment by uBlock-user** [comment]
Subscribe to uBlock Annoyances list.

**Comment by aspultyy** [comment]
how can i subscribe it?

**Comment by mapx-** [comment]
> how can i subscribe it?

go into dashboard, filter lists, Annoyances lists section, select uBlock filters- Annoyances

![image](https://user-images.githubusercontent.com/10303732/152571226-5129089a-2516-40fc-96a2-729fb9ecf875.png)

**Comment by aspultyy** [comment]
I dont have any option like that. I am using edge windows 11- ublock

**Comment by mapx-** [comment]
Did you open the dashboard ?

**Comment by aspultyy** [comment]
![image](https://user-images.githubusercontent.com/99034708/152572145-5a6da351-54c3-4b3f-b275-10997cde570d.png)

Yes, unfortunatelly there is no option like "annoyances" on my filters ublock idk why.

**Comment by mapx-** [comment]
You cannot translate ? "elementos molestos" open it

**Comment by aspultyy** [comment]
I just saw from you and installed adguard. It works perfect right now! I was trying to enter spanishdict. 
Thank you

**Comment by PerfectSalad** [comment]
anti-adb
