### ISSUE TITLE
myaccount.amfam.com: breakage

### ISSUE THREAD

**Issue by intrinsnik** [uBlockOrigin/uAssets#10920]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://myaccount.amfam.com/login`

### Category

breakage

### Describe the issue

The site uses Optimizely for feature toggles. uBlock blocks optimizely which in turn blocks recaptcha on the site disabling the login. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77599
  cosmetic: 39691
  scriptlet: 16340
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61728-7, 1d.11h.31m
    easyprivacy: 26486-17, 1d.11h.29m
    plowe-0: 3696-810, 10d.2h.17m
    ublock-abuse: 72-0, 1d.11h.27m
    ublock-badware: 3560-61, 1d.11h.25m
    ublock-filters: 29975-131, 1d.7h.21m
    ublock-privacy: 191-6, 1d.7h.19m
    ublock-unbreak: 1704-39, 1d.7h.17m
    urlhaus-1: 7432-0, 9h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1205
  launchFromSelfie: true
popupPanel: 
  blocked: 20
```
</details>

**Comment by mapx-** [comment]
@ryanbr
