### ISSUE TITLE
ecolabb2c.b2clogin.com: breakage

### ISSUE THREAD

**Issue by melissajsolano** [uBlockOrigin/uAssets#10928]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://ecolabb2c.b2clogin.com/ecolabb2c.onmicrosoft.com/B2C_1A_Connect_SAML_SignIn/samlp/sso/login?SAMLRequest=fZNdc6IwFIb%2FCpN7kEBByxQ7iJX6QUXApdsbBjACKyRKAhZ%2FfSmus%2B1eNDPnIjkf75vMk4fH97LgGlTRnGAdQEEEHMIJ2eU41cHWn%2FEj8Dh%2BoFFZHDWjZhl20alGlHFdH6Zan9BBXWGNRDSnGo5KRDWWaJ5hrzRJELVjRRhJSAE4g1JUsU7IJJjWJao8VDV5grbuSgcZY0eqDQYJwRglTEBdSxQLCSkHBUlz%2FEiJLorTO0fsV%2BZEKuCmnZMcR6w3f5tw7YylROii7%2B2n%2FDsmuMyTilCyZ31mIpkhNELzqhx%2BOg%2B9PMVzPOjvN6CUXE0Abj7VQSiZRrdelfXQK4g9Nc7%2Fx2daTbettMzLSRp7ZHrhZTOYL9NNhgKHlnYbBO3BUJPmdZ7TJbZtt55Vm6ONXgLrwOCKqLvLfv4a7RTZHUm%2BHa63YrORX7Zm2iqB5a9j9vQEAwZ558%2FS4MX9aFTBcs0sJDt3m5FybrcBWszL1dS00mzYqMya7ibntF0y%2BcDHalwsdiqV8KQZvtnw0trQfb%2Ffu5Be6oO6SGmYnmBKntOXYX0p1nbgVcXqQsuTOFGsXFxIanNWHdE1pUPGMnlFTvz90wzJBQuOb9YMPtu%2F0033WpTWaI4pizDTgSRKkIcSDxUfKpp8p8mSMBTlN8A5fxmZ5PhK3k9Axdciqj37vsM7a88H3K8bwV0BuPKq9eLVF1B%2FHhvd6ATj7yTdiCxbgUYFontSJegTnIfBF53xdff9l4w%2FAA%3D%3D&RelayState=%2Fs%2F&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=ApAdmtE7Ulff5CZDwXGETbVfOncqgF4%2Fd01WZ%2B%2F4wJy4VdtSFvLX1wi%2BIdjbtQbIS91BVxk3Dxgm51t1NQpjFnB7ayRgZT%2FW0JVLmOLB%2FRpZdLvsZ%2FLZMunfFPxvq1mU3lweAj8Icw5tj1fguC299CG6wzE5VS1LuZhyQkr7KPHhoNGX%2BBTqTlGGpFuHxlSlupuLtDZrumGmoGbru%2F%2Bgm8zgxRjCCABRIxz680UxEcW4lhgBN2bfj0CUrtTL4nSe1hRi1%2BToEbqZ5id8a2EBJMUYWcw8tjjRSwFykZB2uWuYsKDAoBucNfcnl949hLfyPnTAopmBhuofSebz7e1mrwL8ikdqnlQk3DGnJ033s%2F3seUjoRi9lZpxdgqiSRWMj6WjkQX3wFyLhVARCiE%2FqY4vQxDR4PBMQL6UmVwWehzD6OOb%2F5dJ5kETmAtzzYjm2vUAlaxmmd1AR%2BOb0VW2XO2dMfq%2F8BOHQcEMq3v7Dit%2BCAHjlIhH5qxWbyReHjVnsgRyIMsX3W5O%2B9pejxjQaf6wGAOu9nmuOnQnBQW5hq%2BnKozHXqg0o9AWA1czqdH8NlsEq4bA4h9RwLnykFpS8DqgQBsGoA601Ce%2FFzuTd%2BRtVicBagqngnPyOsE5pQM0T2mtIDNipK0hgVjdTaX4A%2Fa2HEk3rd9gz2wsV1Jjc4aI%3D`

### Category

breakage

### Describe the issue

Unable to access password page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77667
  cosmetic: 39692
  scriptlet: 16349
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61748-8, 1d.21h.30m
    easyprivacy: 26496-17, 18h.59m
    plowe-0: 3697-810, 8d.21h.13m
    ublock-abuse: 81-0, 1d.21h.32m
    ublock-badware: 3570-61, 1d.21h.34m
    ublock-filters: 29975-131, 1d.21h.36m
    ublock-privacy: 188-7, 19h.1m
    ublock-unbreak: 1704-39, 19h.3m
    urlhaus-1: 7463-0, 1h.23m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 755
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
with / without uBO enabled I get the same error with the link above

![image](https://user-images.githubusercontent.com/10303732/146219185-5767c956-93fc-416b-b540-e5bd7eda7f36.png)

Provide the real steps / links to get the breakage
