### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by Kotaless** [uBlockOrigin/uAssets#10924]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.investing.com/crypto/bitcoin/btc-usd`

### Category

detection

### Describe the issue

It detects the blocker and doesn't let me pass it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/9118532/146156279-931b04c3-926d-437f-96a7-8eecc431c4fc.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 51751
  cosmetic: 100245
  scriptlet: 19574
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt: 517-0, 7m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-9, 5m
    TUR-0: 9046-57, 3d.16h.15m
    fanboy-annoyance: 59044-167, 6d.17h.43m
    ublock-annoyances: 4319-140, 3d.16h.17m
  default: 
    easylist: 61639-40, 3d.16h.30m
    ublock-abuse: 72-0, 3d.16h.28m
    ublock-badware: 3565-59, 3d.16h.25m
    ublock-filters: 29983-174, 2m
    ublock-privacy: 189-8, 3d.16h.21m
    ublock-unbreak: 1715-18, 2m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 390
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by uBlock-user** [comment]
Test on default lists/settings and with all other extensions disabled.

**Comment by Kotaless** [comment]
> Test on default lists/settings and with all other extensions disabled.

It still detecting.

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77783
  cosmetic: 39716
  scriptlet: 16342
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61779-8, now
    easyprivacy: 26496-17, now
    plowe-0: 3690-809, now
    ublock-abuse: 81-0, now
    ublock-badware: 3569-61, now
    ublock-filters: 29983-132, now
    ublock-privacy: 187-2, now
    ublock-unbreak: 1715-39, now
    urlhaus-1: 7553-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1018
  launchFromSelfie: false
popupPanel: 
  blocked: 3
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end using Chromium I can only reproduce if I disable `ublock-filters`.

**Comment by MasterKia** [comment]
I can reproduce with non-default filterlists and this rule disables the anti-adblock warning for me: 
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=www.investing.com`

```
checkAdBlocker: function() {
        return e.prev = 0, e.abrupt("return", fetch(new Request("https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js", {
            method: "HEAD",
            mode: "no-cors",
            cache: "no-cache"
        })).then((function() {
            return t = !1
        })).catch((function() {
            return t = !0
        })));
```

**Comment by mapx-** [comment]
test

`investing.com##+js(no-fetch-if, ads)`

**Comment by Kotaless** [comment]
Seems like Edge's "Tracking prevention (Strict)" intervines with uBO. It's fine when I disable it.
Is it possible to use both of them or should I just disable tracking prevention?

**Comment by Kotaless** [comment]
> test
> 
> `investing.com##+js(no-fetch-if, ads)`

This works even with "Tracking prevention (Strict)". Thank you!

**Comment by mapx-** [comment]
`investing.com##+js(set-constant, google_ad_status, 1)` seems to be useless now

**Comment by uBlock-user** [comment]
> Seems like Edge's "Tracking prevention (Strict)" intervines with uBO.

Built-in adblockers should be disabled.

**Comment by okiehsch** [comment]
> investing.com##+js(set-constant, google_ad_status, 1) seems to be useless now

It's not useless, it prevents the antui adblock message on my end.

**Comment by mapx-** [comment]
I get no anti adb on my side, maybe I should test on some us ip

**Comment by okiehsch** [comment]
My bad you are actually right, I thought the rule still worked because I could reproduce the anti adblock message if I disabled `uBO-filters`.
I assumed that meant that `investing.com##+js(set-constant, google_ad_status, 1)` was fixing it but  it's
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,xhr,redirect-rule=googlesyndication_adsbygoogle.js:5`
that fixes the anti adblock message.
I will remove `investing.com##+js(set-constant, google_ad_status, 1)`

**Comment by Yuki2718** [comment]
If that's not needed thx to redirect, what if redirect doesn't work? We fixed some issues happens only on InPrivate window where Firefox ETP interfere with redirect.

**Comment by Yuki2718** [comment]
Well, but at least I don't see anti-adb with ETP enabled.

**Comment by okiehsch** [comment]
> what if redirect doesn't work?

 `investing.com##+js(set-constant, google_ad_status, 1)` does not work in that case.

**Comment by Kotaless** [comment]
> > what if redirect doesn't work?
> 
> `investing.com##+js(set-constant, google_ad_status, 1)` does not work in that case.

I'm getting anti-adblock message again. 
I believe removing this filter caused it. It's fine if I manually add this filter. Could you check this out again?

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by Kotaless** [comment]
Weird. Guess I've to keep the filter. Thanks anyway.

**Comment by okiehsch** [comment]
Today I can reproduce... 
I added 
`investing.com##+js(set, google_ad_status, 1)`
again.
