### ISSUE TITLE
radio.yandex.ru: breakage

### ISSUE THREAD

**Issue by YuichiKazunori** [uBlockOrigin/uAssets#10925]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://radio.yandex.ru/`

### Category

breakage

### Describe the issue

audio music. Stop music, when Ublock ON

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 96441
  cosmetic: 60677
  scriptlet: 17798
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40406-9, 20h.18m
    easylist: 61639-23, 3d.14h.54m
    easyprivacy: 26484-114, 3d.14h.52m
    plowe-0: 3690-814, 16h.16m
    ublock-abuse: 72-1, 3d.14h.50m
    ublock-badware: 3565-61, 3d.14h.48m
    ublock-filters: 29878-160, 3d.14h.45m
    ublock-privacy: 189-2, 3d.14h.43m
    ublock-unbreak: 1708-39, 3d.14h.41m
    urlhaus-1: 8445-0, 11h.52m
filterset (user): [array of 247 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1521
  launchFromSelfie: true
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
I listened to the radio for several hours, but I could not repeat this problem.
