### ISSUE TITLE
arpal.regione.puglia.it: nuisance

### ISSUE THREAD

**Issue by DonPicciotto** [uBlockOrigin/uAssets#10932]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://arpal.regione.puglia.it/capgrptv/zf/index.php/bandi-di-concorso/index/dettaglio/concorsi/scaduti/bando/7`

### Category

nuisance

### Describe the issue

I can scroll the page only after using the element zapper mode to remove the semi-transparent cookie overlay, but the page is stuck if I remove it with the element picker mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 159683
  cosmetic: 185169
  scriptlet: 32349
  html: 605
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1553-0, 1d.13h.25m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 1d.13h.27m
    https://www.fanboy.co.nz/enhancedstats.txt: 2993-10, 4d.34m
    adguard-generic: 62134-4640, 4d.20m
    adguard-spyware: 23845-927, 4d.13m
    adguard-annoyance: 48383-4177, 2d.13h.29m
    adguard-social: 14894-39, 4d.7m
    fanboy-thirdparty_social: 68-0, 7d.7h.51m
    fanboy-annoyance: 59044-43833, 7d.7h.49m
    fanboy-cookiemonster: 20462-137, 7d.7h.47m
    fanboy-social: 23177-1084, 4d.5m
    ublock-annoyances: 4327-8, 4d.2m
    dpollock-0: 16948-1823, 3d.5h.8m
    mvps-0: 8730-380, 3d.5h.18m
    ITA-0: 12615-35, 6h.45m
    ITA-1: 5007-209, 2d.13h.33m
    adguard-spyware-url: 400-67, 4d
    block-lan: 44-0, 3d.5h.6m
  default: 
    ublock-filters: 30431-98, 4d.31m
    ublock-badware: 3543-1, 4d.29m
    ublock-privacy: 185-0, 4d.27m
    ublock-abuse: 72-0, 4d.25m
    ublock-unbreak: 1715-1, 4d.23m
    easylist: 61639-973, 4d.16m
    easyprivacy: 26484-10775, 4d.11m
    urlhaus-1: 7553-0, 12h.1m
    plowe-0: 3700-5, 12d.13h.25m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 290 redacted]
hostRuleset: 
  added: [array of 753 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  suspendTabsUntilReady: yes
supportStats: 
  launchToReadiness: 1000
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
add & test

`regione.puglia.it#@##cookie-bar`

@ryanbr

**Comment by DonPicciotto** [comment]
Works, after clicking refuse/accept cookies

15 dic 2021, 23:59 da ***@***.***:
