### ISSUE TITLE
loot.tv Anti-Adblock

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#10931]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://loot.tv/video/671756`

### Describe the issue

The video won't play and a message displays, "Please disable your Adblocker to start earning rewards!"

### uBlock Origin version

1.39.2

### Browser name and version

Chrome 97.0.4692.44

### Settings

My filters:

<details>

```
||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 https://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 https://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 https://pagespeed.web.dev
pagespeed.web.dev##.glAfi

! 2021-11-20 https://cointiply.arkadiumarena.com
cointiply.arkadiumarena.com##.AdBlocker__header___3haT115M
cointiply.arkadiumarena.com##.AdBlocker__title___3KRapx8e
cointiply.arkadiumarena.com##.AdBlocker__text___2OgB4Aol
cointiply.arkadiumarena.com##.AdBlocker__instructions___wQxCyHYS

||linksynergy.com

! 2021-11-23 https://cheatersoul.com
cheatersoul.com###quads-myModal

! 2021-11-23 https://www.react2424.com
www.react2424.com##.col-lg-4.col-md-4.col-sm-12.col-xs-12
www.react2424.com##.biewtyWrap3

! 2021-11-23 https://www.breaking-n.com
www.breaking-n.com##.biewtyWrap3

! 2021-11-26 https://myviptuto.com
myviptuto.com##.code-block-2.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-2.code-block > .ad-info
myviptuto.com##.code-block-9.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-9.code-block > .ad-info

||cbtb.clickbank.net^
||hop.clickbank.net^
||cbstatic.net^

@@||pay.clickbank.net
@@||filter.clickbank.net
@@||ssl.clickbank.net

$removeparam=hop

||powerinbox.com^
||jeeng.com^

! 2021-12-01 https://zeoob.com
zeoob.com##.vertical-align-center.modal-dialog > .modal-content > .modal-body
zeoob.com###ads_blocker_modal
zeoob.com###edit_modal

||ads.roblox.com^$important
||adconfiguration.roblox.com^
##.game-card-native-ad
||roblox.com^$removeparam=gameSearchSessionInfo
||roblox.com^$removeparam=isAd
||roblox.com^$removeparam=numberOfLoadedTiles
||roblox.com^$removeparam=page
||roblox.com^$removeparam=placeId
||roblox.com^$removeparam=position
||roblox.com^$removeparam=data
||roblox.com/userads/redirect?data=$document

$removeparam=cid
$removeparam=uid
$removeparam=sid
$removeparam=gid
$removeparam=rid
$removeparam=aid
$removeparam=pid
$removeparam=aff
$removeparam=ref
$removeparam=r

www.roblox.com##.game-tile.game-card:has(.game-card-container > .game-card-link > .game-card-native-ad)

! 2021-12-10 https://ide.codingblocks.com
ide.codingblocks.com##promotion-banner

||video-change.digital^
||tiktok-flow.com^
||tiktok-labs.com^
||tiktok-gw.com^
||cmp.jobs^
```

</details>

**Comment by SilkArt** [comment]
An account is required...

**Comment by SilkArt** [comment]
The issue has been fixed by me, whitelist connatix.com by using:
`@@||connatix.com$domain=loot.tv`. Video still plays, anti-adblock warning gone, and no ads.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by SilkArt** [comment]
To remove anti-adblock message, use `loot.tv##._54aOX1SZ60Vf1FbfUQ4fQ`.

**Comment by SilkArt** [comment]
Still can't earn points!

**Comment by iam-py-test** [comment]
@SilkArt can you put the _my filters_ section in ``` so it is not autolinked

**Comment by SilkArt** [comment]
OK

**Comment by SilkArt** [comment]
So like this `||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 https://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 https://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 https://pagespeed.web.dev
pagespeed.web.dev##.glAfi

! 2021-11-20 https://cointiply.arkadiumarena.com
cointiply.arkadiumarena.com##.AdBlocker__header___3haT115M
cointiply.arkadiumarena.com##.AdBlocker__title___3KRapx8e
cointiply.arkadiumarena.com##.AdBlocker__text___2OgB4Aol
cointiply.arkadiumarena.com##.AdBlocker__instructions___wQxCyHYS

||linksynergy.com

! 2021-11-23 https://cheatersoul.com
cheatersoul.com###quads-myModal

! 2021-11-23 https://www.react2424.com
www.react2424.com##.col-lg-4.col-md-4.col-sm-12.col-xs-12
www.react2424.com##.biewtyWrap3

! 2021-11-23 https://www.breaking-n.com
www.breaking-n.com##.biewtyWrap3

! 2021-11-26 https://myviptuto.com
myviptuto.com##.code-block-2.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-2.code-block > .ad-info
myviptuto.com##.code-block-9.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-9.code-block > .ad-info

||cbtb.clickbank.net^
||hop.clickbank.net^
||cbstatic.net^

@@||pay.clickbank.net
@@||filter.clickbank.net
@@||ssl.clickbank.net

$removeparam=hop

||powerinbox.com^
||jeeng.com^

! 2021-12-01 https://zeoob.com
zeoob.com##.vertical-align-center.modal-dialog > .modal-content > .modal-body
zeoob.com###ads_blocker_modal
zeoob.com###edit_modal

||ads.roblox.com^$important
||adconfiguration.roblox.com^
##.game-card-native-ad
||roblox.com^$removeparam=gameSearchSessionInfo
||roblox.com^$removeparam=isAd
||roblox.com^$removeparam=numberOfLoadedTiles
||roblox.com^$removeparam=page
||roblox.com^$removeparam=placeId
||roblox.com^$removeparam=position
||roblox.com^$removeparam=data
||roblox.com/userads/redirect?data=$document

$removeparam=cid
$removeparam=uid
$removeparam=sid
$removeparam=gid
$removeparam=rid
$removeparam=aid
$removeparam=pid
$removeparam=aff
$removeparam=ref
$removeparam=r

www.roblox.com##.game-tile.game-card:has(.game-card-container > .game-card-link > .game-card-native-ad)

! 2021-12-10 https://ide.codingblocks.com
ide.codingblocks.com##promotion-banner

||video-change.digital^
||tiktok-flow.com^
||tiktok-labs.com^
||tiktok-gw.com^
||cmp.jobs^

! 2021-12-16 https://loot.tv
loot.tv##._54aOX1SZ60Vf1FbfUQ4fQ
@@||connatix.com$domain=loot.tv`

**Comment by SilkArt** [comment]
`||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 https://tutubox.io
tutubox.io##.popup

! 2021-11-10 https://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 https://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 https://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 https://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 https://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 https://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 https://pagespeed.web.dev
pagespeed.web.dev##.glAfi

! 2021-11-20 https://cointiply.arkadiumarena.com
cointiply.arkadiumarena.com##.AdBlocker__header___3haT115M
cointiply.arkadiumarena.com##.AdBlocker__title___3KRapx8e
cointiply.arkadiumarena.com##.AdBlocker__text___2OgB4Aol
cointiply.arkadiumarena.com##.AdBlocker__instructions___wQxCyHYS

||linksynergy.com

! 2021-11-23 https://cheatersoul.com
cheatersoul.com###quads-myModal

! 2021-11-23 https://www.react2424.com
www.react2424.com##.col-lg-4.col-md-4.col-sm-12.col-xs-12
www.react2424.com##.biewtyWrap3

! 2021-11-23 https://www.breaking-n.com
www.breaking-n.com##.biewtyWrap3

! 2021-11-26 https://myviptuto.com
myviptuto.com##.code-block-2.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-2.code-block > .ad-info
myviptuto.com##.code-block-9.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-9.code-block > .ad-info

||cbtb.clickbank.net^
||hop.clickbank.net^
||cbstatic.net^

@@||pay.clickbank.net
@@||filter.clickbank.net
@@||ssl.clickbank.net

$removeparam=hop

||powerinbox.com^
||jeeng.com^

! 2021-12-01 https://zeoob.com
zeoob.com##.vertical-align-center.modal-dialog > .modal-content > .modal-body
zeoob.com###ads_blocker_modal
zeoob.com###edit_modal

||ads.roblox.com^$important
||adconfiguration.roblox.com^
##.game-card-native-ad
||roblox.com^$removeparam=gameSearchSessionInfo
||roblox.com^$removeparam=isAd
||roblox.com^$removeparam=numberOfLoadedTiles
||roblox.com^$removeparam=page
||roblox.com^$removeparam=placeId
||roblox.com^$removeparam=position
||roblox.com^$removeparam=data
||roblox.com/userads/redirect?data=$document

$removeparam=cid
$removeparam=uid
$removeparam=sid
$removeparam=gid
$removeparam=rid
$removeparam=aid
$removeparam=pid
$removeparam=aff
$removeparam=ref
$removeparam=r

www.roblox.com##.game-tile.game-card:has(.game-card-container > .game-card-link > .game-card-native-ad)

! 2021-12-10 https://ide.codingblocks.com
ide.codingblocks.com##promotion-banner

||video-change.digital^
||tiktok-flow.com^
||tiktok-labs.com^
||tiktok-gw.com^
||cmp.jobs^

! 2021-12-16 https://loot.tv
loot.tv##._54aOX1SZ60Vf1FbfUQ4fQ
@@||connatix.com$domain=loot.tv`

**Comment by SilkArt** [comment]
||your-surveys.com^$badfilter
||adfoc.us^$badfilter
||moat.com^$badfilter
||goggle.com^$badfilter
||jump.ogtrk.net^$badfilter
||ext.track-click.tk^$badfilter
||gratisvps.net^$badfilter
||cpa-optimizer.online^
||free-coupons.network^
||breaking-news.one^

! 2021-11-10 hxxps://tutubox.io
tutubox.io##.popup

! 2021-11-10 hxxps://app.app-valley.vip
app.app-valley.vip##.notification-item > .item-content

##iframe:nth-of-type(3)

! 2021-11-10 hxxps://www.idropnews.com
www.idropnews.com###the-post-content > .content-main

! 2021-11-12 hxxps://www.thebharatexpressnews.com
www.thebharatexpressnews.com##section > div > div > ins

! 2021-11-14 hxxps://mytoolz.net
mytoolz.net##.ndcyidc
mytoolz.net###adblock_abdoutech
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/m202109080101/show_ads_impl_fy2019.js$domain=mytoolz.net

! 2021-11-15 hxxps://checkout.minecraft.net
checkout.minecraft.net##.popup-overlay

||addthis.com^$badfilter
||s7.addthis.com^$badfilter

! 2021-11-17 hxxps://pernambuconoticias.com.br
pernambuconoticias.com.br##.brave_popup__step__overlay--closable.brave_popup__step__overlay
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content > .brave_popup__step__elements
pernambuconoticias.com.br##.has_autoClose.has_overlay_close.has_overlay.closeButtonPosition_inside_right.brave_popup__step--boxed.closeButton_icon.position_center.brave_popup__step__desktop.brave_popup__step > .brave_popup__step__inner > .brave_popupSections__wrap > .brave_popupMargin__wrap > .brave_popup__step__popup > .brave_popup__step__content

||prodmp.ru^
||pxksnymto.ru^
||qdb6gd3nth.ru^
||prokazan.ru/advert

! 2021-11-17 hxxps://pagespeed.web.dev
pagespeed.web.dev##.glAfi

! 2021-11-20 hxxps://cointiply.arkadiumarena.com
cointiply.arkadiumarena.com##.AdBlocker__header___3haT115M
cointiply.arkadiumarena.com##.AdBlocker__title___3KRapx8e
cointiply.arkadiumarena.com##.AdBlocker__text___2OgB4Aol
cointiply.arkadiumarena.com##.AdBlocker__instructions___wQxCyHYS

||linksynergy.com

! 2021-11-23 hxxps://cheatersoul.com
cheatersoul.com###quads-myModal

! 2021-11-23 hxxps://www.react2424.com
www.react2424.com##.col-lg-4.col-md-4.col-sm-12.col-xs-12
www.react2424.com##.biewtyWrap3

! 2021-11-23 hxxps://www.breaking-n.com
www.breaking-n.com##.biewtyWrap3

! 2021-11-26 hxxps://myviptuto.com
myviptuto.com##.code-block-2.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-2.code-block > .ad-info
myviptuto.com##.code-block-9.code-block > .ad-info > .m-0.p-0.mbutton-list
myviptuto.com##.code-block-9.code-block > .ad-info

||cbtb.clickbank.net^
||hop.clickbank.net^
||cbstatic.net^

@@||pay.clickbank.net
@@||filter.clickbank.net
@@||ssl.clickbank.net

$removeparam=hop

||powerinbox.com^
||jeeng.com^

! 2021-12-01 hxxps://zeoob.com
zeoob.com##.vertical-align-center.modal-dialog > .modal-content > .modal-body
zeoob.com###ads_blocker_modal
zeoob.com###edit_modal

||ads.roblox.com^$important
||adconfiguration.roblox.com^
##.game-card-native-ad
||roblox.com^$removeparam=gameSearchSessionInfo
||roblox.com^$removeparam=isAd
||roblox.com^$removeparam=numberOfLoadedTiles
||roblox.com^$removeparam=page
||roblox.com^$removeparam=placeId
||roblox.com^$removeparam=position
||roblox.com^$removeparam=data
||roblox.com/userads/redirect?data=$document

$removeparam=cid
$removeparam=uid
$removeparam=sid
$removeparam=gid
$removeparam=rid
$removeparam=aid
$removeparam=pid
$removeparam=aff
$removeparam=ref
$removeparam=r

roblox.com##.game-tile.game-card:has(.game-card-container > .game-card-link > .game-card-native-ad)

! 2021-12-10 hxxps://ide.codingblocks.com
ide.codingblocks.com##promotion-banner

||video-change.digital^
||tiktok-flow.com^
||tiktok-labs.com^
||tiktok-gw.com^
||cmp.jobs^

! 2021-12-16 hxxps://loot.tv
loot.tv##._54aOX1SZ60Vf1FbfUQ4fQ
@@||connatix.com$domain=loot.tv

**Comment by MasterKia** [comment]
> The issue has been fixed by me, whitelist connatix.com by using: `@@||connatix.com$domain=loot.tv`. Video still plays and no ads.

Similar to https://github.com/uBlockOrigin/uAssets/issues/10867#issue-1077488123

**Comment by SilkArt** [comment]
I'll just use hxxps instead of https just like they do in malware research.

**Comment by SilkArt** [comment]
Need to find way to BLOCK ADS and earn POINTS.

**Comment by MasterKia** [comment]
> How do I stop the autolinking??? I tried to put ``` but it didn't work.

\```
Filters
\```

**Comment by MasterKia** [comment]
> How do I stop the autolinking??? I tried to put ``` but it didn't work.

\<details>
\<summary>My filters\</summary>
\```
PUT FILTERS HERE
\```
\</details>

**Comment by iam-py-test** [comment]
> > How do I stop the autolinking??? I tried to put ``` but it didn't work.
> 
> <details> <summary>My filters</summary> ``` PUT FILTERS HERE ``` </details>

That doesn't work...
Did you put ``` on both ends?
