### ISSUE TITLE
ephimmoi.net: popups and breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10936]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://ephimmoi.net/venom-2-doi-mat-tu-thu/`

### Category

popups and breakage

### Describe the issue

This is a video streaming website. Click on the red button `Xem phim`, a popup appears in new tab.

Proposed filter:

`ephimmoi.net##+js(acis, $, isMobileIntro)`

At the next page after clicking that button:
`https://ephimmoi.net/xem-phim/venom-2-doi-mat-tu-thu-tap-1-server-1/`

video player cannot play due to this filter in `EasyList`

`||nazarickol.com^`

I think this domain is one of the `Hydrax` domains to play the videos, so hard block the whole domain can cause breakages in other video streaming sites.

These are the filters related to `Hydrax` server in `ublock filters`

<details>

```
! https://github.com/NanoMeow/QuickReports/issues/3311
@@||iamcdn.net/players/*ads$script,domain=playhydrax.com
||iamcdn.net/players/ads.watch.min.js$script,domain=playhydrax.com,important
||iamcdn.net/players/playera.dmins.js$script,domain=playhydrax.com
||iamcdn.net/players/player*.*mins.js$script,domain=hydracdn.*|redirect-ads.com|nazarickol.com|freeplayervideo.com
||iamcdn.net/players/playhydraxs.min.js$script,domain=redirect-ads.com|nazarickol.com|freeplayervideo.com
hydracdn.*##+js(acis, String.fromCharCode, /btoa|break/)
hydracdn.*,hydrax.net,playhydrax.com##+js(aopr, AaDetector)
hydracdn.*,hydrax.net,playhydrax.com##+js(nostif, debugger)
playhydrax.com##+js(nosiif, _0x)
hydracdn.*,hydrax.net,playhydrax.com##+js(nowoif, /^/, 2)
redirect-ads.com,nazarickol.com,freeplayervideo.com##+js(set, detectAdBlockAll, noopFunc)
*$image,redirect-rule=32x32.png,domain=redirect-ads.com|nazarickol.com|freeplayervideo.com
redirect-ads.com,nazarickol.com,freeplayervideo.com##+js(set, console.clear, undefined)
redirect-ads.com,nazarickol.com,freeplayervideo.com##+js(ra, style, #over)
redirect-ads.com,nazarickol.com,freeplayervideo.com###playback-fake
redirect-ads.com,nazarickol.com,freeplayervideo.com##+js(nowoif, /^/, 1)
playhydrax.com,hydracdn.*,hydrax.net##div#over:remove()
@@||hydracdn.*^$ghide
@@||hydrax.net^$ghide
@@||playhydrax.com^$ghide
jav.guru##.aligncenter
jav.guru##.alignnone
```

</details>

### Screenshot(s)

<details>
<summary>Blank video player due to blocked</summary>

![image](https://user-images.githubusercontent.com/66517106/146313503-e861c17e-53ea-4ff1-a828-78db276879a8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78571
  cosmetic: 41037
  scriptlet: 16349
  html: 607
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2282-9, 1m
  default: 
    ublock-filters: 30569-30, 1m
    ublock-badware: 3573-1, 1m
    ublock-privacy: 184-0, 1m
    ublock-abuse: 81-0, 1m
    ublock-unbreak: 1733-0, 1m
    easylist: 61827-588, 1m
    easyprivacy: 26499-488, 1m
    urlhaus-1: 7394-0, 1m
    plowe-0: 3690-3, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 412
  launchFromSelfie: false
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
```
ephimmoi.net##+js(acis, $, open)
ephimmoi.net##.popUpBannerBox
```

@hoang-rio

**Comment by mapx-** [comment]
fixed by @ryanbr 
https://github.com/easylist/easylist/commit/1ac9ef5cb679d5eab14cba5a2af9cdcf0477588f
