### ISSUE TITLE
Block Outsider Intrusion into LAN  Youtube Spam

### ISSUE THREAD

**Issue by tyrel68** [uBlockOrigin/uAssets#10930]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com

### Describe the issue

[ublockLocalintrusionspam.txt](https://github.com/uBlockOrigin/uAssets/files/7721445/ublockLocalintrusionspam.txt)

The Block Outsider Intrusion into LAN filter spams an error forever

```
Filter ||[::]^$3p,domain=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local
Filter list Block Outsider Intrusion into LAN 
Context behind-the-scene
Partyness (0,3) behind-the-scene ⇒ [::]
Type xhr
URL https://[::]/
```

### uBlock Origin version

uBlock Origin 1.39.2

### Browser name and version

Firefox 95.0

### Settings

[my-ublock-backup_2021-12-15_13.19.33.txt](https://github.com/uBlockOrigin/uAssets/files/7721465/my-ublock-backup_2021-12-15_13.19.33.txt)

Main thing i did to was increase ublock to medium and blocked fonts and cosmetic filter by default 

### Notes

Something I noticed is even if I disable Ublock the logger still says its blocking this

**Comment by gorhill** [comment]
Filter lists don't "spam", this just means something happening on your Youtube page is causing a filter in the _"Block Outsider Intrusion into LAN"_ to be triggered, you will have to investigate the issue on your side.

**Comment by gorhill** [comment]
By the way, the fact that you selected so many filter lists suggest that you might have as well misconfigured your Firefox, so I suggest you investigate changes you made to `about:config` and also whether another extension is causing this.

**Comment by iam-py-test** [comment]
Just by the way, `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt` is redundant with `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList` installed. 
And `https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt` is unmaintained and has been removed from uBo's default lists

**Comment by tyrel68** [comment]
Thanks for the info and sorry for bothering you with a non issue
