### ISSUE TITLE
phimdinhcao.com: nuisance

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10938]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.phimdinhcao.com/phim-mai-am-gia-dinh-501-600/tap-501.html`

### Category

nuisance

### Describe the issue

Just an annoyance. Can't right click or press `Ctrl + U` to open `view-source`.

Proposed filter:

`phimdinhcao.com##+js(acis, oncontextmenu, keydown)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78570
  cosmetic: 41049
  scriptlet: 16355
  html: 607
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2288-2, 3m
  default: 
    ublock-filters: 30578-38, 3m
    ublock-badware: 3573-1, 3m
    ublock-privacy: 184-0, 3m
    ublock-abuse: 81-0, 3m
    ublock-unbreak: 1733-0, 3m
    easylist: 61827-597, 3m
    easyprivacy: 26501-478, 3m
    urlhaus-1: 7394-0, 3m
    plowe-0: 3690-3, 3m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 607
  launchFromSelfie: false
popupPanel: 
  blocked: 25
```
</details>

**Comment by stephenhawk8054** [comment]
Another nuisance. Pressing `F12` to open dev tools makes the video stops playing and throwing error.

URL: 
`https://www.phimdinhcao.com/phim-mai-am-gia-dinh-301-400/tap-335.html`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/148041502-38495482-5309-4a90-baf8-dd3eda2b1dcc.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 79414
  cosmetic: 42932
  scriptlet: 19166
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4362-4, 7m
    VIE-1: 2345-2, 27m
  default: 
    ublock-filters: 30609-37, 4h.36m
    ublock-badware: 3652-1, 4h.36m
    ublock-privacy: 182-0, 4h.36m
    ublock-abuse: 76-0, 4h.36m
    ublock-unbreak: 1720-0, 4h.36m
    easylist: 62576-618, 4h.36m
    easyprivacy: 26599-484, 4h.36m
    urlhaus-1: 7628-0, 4h.36m
    plowe-0: 3682-2, 4h.36m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 206 ms (selfie)
popupPanel: 
  blocked: 23
```

</details>

The detection code is in the script:
`https://iamcdn.net/players/playhydrax.min.js`

Proposed filter:

`phimdinhcao.com##+js(aopr, devtoolsDetector)`

**Comment by mapx-** [comment]
@hoang-rio

**Comment by hoang-rio** [comment]
> @hoang-rio

Thanks for mention but this nuisance is not support by ABPVN List. ABPVN currently only support Advertisment and Anti Adblock
