### ISSUE TITLE
intel.com: breakage

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#10934]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.intel.com/content/www/us/en/search.html?ws=text`

### Category

breakage

### Describe the issue

When ublock is enabled, the feedback button does not work.
(An error message will be displayed.)
Allowing researchintel.com appears to work fine. (See second screenshot)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし1](https://user-images.githubusercontent.com/86018494/146306082-d2188b28-9cb4-48e1-afff-433bf14ff874.png)
![image](https://user-images.githubusercontent.com/86018494/146306465-1bff9f0f-2259-4d7f-9c36-182ffbc0551f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77668
  cosmetic: 39761
  scriptlet: 16359
  html: 0
listset (total-discarded, last updated): 
  removed: 
    JPN-1: null
  default: 
    easylist: 61827-8, 2m
    easyprivacy: 26499-17, 2m
    plowe-0: 3690-810, 2m
    ublock-abuse: 81-0, 2m
    ublock-badware: 3569-61, 2m
    ublock-filters: 30006-132, 2m
    ublock-privacy: 188-2, 2m
    ublock-unbreak: 1722-39, 2m
    urlhaus-1: 7394-0, 2m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1376
  launchFromSelfie: false
popupPanel: 
  blocked: 40
```
</details>

**Comment by mapx-** [comment]
it seems only this 1 working fine:

`@@||researchintel.com/survey/*/httppost/feedback.asp$xhr,domain=intel.com`

@ryanbr
