### ISSUE TITLE
nytimes.com: breakage

### ISSUE THREAD

**Issue by dballing** [uBlockOrigin/uAssets#10949]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.nytimes.com/live/2021/12/16/nyregion/ghislaine-maxwell-trial`

### Category

breakage

### Describe the issue

page is blank

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77582
  cosmetic: 39687
  scriptlet: 16301
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30508-131, 3d.3h.42m
    ublock-badware: 3574-1, 3d.3h.40m
    ublock-privacy: 185-0, 3d.3h.38m
    ublock-abuse: 81-0, 3d.3h.36m
    ublock-unbreak: 1723-0, 3d.3h.34m
    easylist: 61731-449, 3d.3h.32m
    easyprivacy: 26487-484, 3d.3h.30m
    urlhaus-1: 7394-0, 16h.48m
    plowe-0: 3697-3, 10d.8h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 191
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
disable all other addons and test again
