### ISSUE TITLE
vscode.bernardsbooty.com: breakage

### ISSUE THREAD

**Issue by blckassassin** [uBlockOrigin/uAssets#10945]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://vscode.bernardsbooty.com/`

### Category

breakage

### Describe the issue

I have a custom dns for my home server called **bernardsbooty.com**.  I created several subdomains to access various docker containers on my server such as Plex, Nextcloud, and VS Code.  Other subdomains work correctly except for my VS Code subdomain.  When I try to access it I receive the error:

`An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/35352539/146419627-e4be4af5-e87c-4f8e-bb97-2bc9090b3745.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77562
  cosmetic: 39683
  scriptlet: 16301
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30508-30, 3d.12h.44m
    ublock-badware: 3569-1, 3d.12h.42m
    ublock-privacy: 185-0, 3d.12h.39m
    ublock-abuse: 81-0, 3d.12h.37m
    ublock-unbreak: 1723-0, 3d.12h.35m
    easylist: 61721-556, 3d.12h.33m
    easyprivacy: 26486-476, 3d.12h.31m
    urlhaus-1: 7394-0, 16h.4m
    plowe-0: 3687-3, 3d.12h.27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 694
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by gorhill** [comment]
Use the logger to find out what is being blocked. Once you find this out, just create an exception filter, I doubt solutions for non-public issue will go into a public list.

**Comment by blckassassin** [comment]
> Use the logger to find out what is being blocked. Once you find this out, just create an exception filter, I doubt solutions for non-public issue will go into a public list.

I was able to do that thank you.  This fixed the problem.  I never had problems before so I wasn't aware of this solution.
