### ISSUE TITLE
support.microsoft.com: breakage

### ISSUE THREAD

**Issue by ragdollfun** [uBlockOrigin/uAssets#10940]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://support.microsoft.com/fr-fr/windows/contenu-de-cette-mise-%C3%A0-jour-93c5c27c-f96e-43c2-a08e-5812d92f220d?ocid=wusettings`

### Category

breakage

### Describe the issue

The website's UI elements are non-functional

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/68953298/146374266-fb4866a3-fb91-4733-917e-427cd8de1335.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77617
  cosmetic: 39687
  scriptlet: 16301
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30508-30, 2d.21h.9m
    ublock-badware: 3543-1, 2d.21h.7m
    ublock-privacy: 185-0, 2d.21h.5m
    ublock-abuse: 81-0, 2d.21h.3m
    ublock-unbreak: 1723-0, 2d.21h.1m
    easylist: 61728-557, 2d.20h.59m
    easyprivacy: 26486-476, 2d.20h.57m
    urlhaus-1: 7463-0, 17h.58m
    plowe-0: 3697-3, 6d.19h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3755
  launchFromSelfie: true
popupPanel: 
  blocked: 23
```
</details>

**Comment by yourduskquibbles** [comment]
I am unable to reproduce. Are you using VPN or DNS block list?

**Comment by iam-py-test** [comment]
Check your [HOSTs file](https://en.wikipedia.org/wiki/Hosts_(file)) and antivirus as well. And try disabling all other browser extensions and builtin browser tracking protection.
Does it occur when you disable uBlock Origin?
