### ISSUE TITLE
Benchmark Universe

### ISSUE THREAD

**Issue by parkerj-cinnaminson** [uBlockOrigin/uAssets#10946]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`cinnaminson.benchmarkuniverse.com`

### Describe the issue

At the benchmark site you click the "Sign in with Google" and the site fails to load fully (just spins their progress logo).  Disabling uBlock resolves the problem.  As the page failure requires login I've attached the log from the page load.  Thank you for your help!  Based on the log I expect that this is a generic issue that applies to their login for all Google-based education customers.  I can provide additional tests/logs as needed.
[Benchmark logs for UBlock.txt](https://github.com/uBlockOrigin/uAssets/files/7729823/Benchmark.logs.for.UBlock.txt)

### Notes

We have tested the site on multiple devices and with multiple users.  Consistently disabling uBlock resolves the issue.  If we clear the cache and re-enable uBlock the issue returns.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78661
  cosmetic: 39710
  scriptlet: 16333
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61777-8, 2d.27m
    easyprivacy: 26495-17, 2d.25m
    plowe-0: 3687-809, 6d.1h.40m
    ublock-abuse: 72-0, 2d.23m
    ublock-badware: 3570-61, 2d.21m
    ublock-filters: 29982-132, 2d.19m
    ublock-privacy: 183-2, 2d.17m
    ublock-unbreak: 1704-39, 2d.15m
    urlhaus-1: 8445-0, 1d.10m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1223
  launchFromSelfie: true
```
</details>

**Comment by mapx-** [comment]
Still getting the error after disabling uBO

**Comment by gorhill** [comment]
I was able to login with my Google account with default settings/lists.

**Comment by mapx-** [comment]
getting this error

![image](https://user-images.githubusercontent.com/10303732/146442687-0c5df693-2c61-4cb3-940d-153f13ff2da8.png)

**Comment by gorhill** [comment]
This is just a account not found error, my understanding is that OP does not reach this.

**Comment by parkerj-cinnaminson** [comment]
That is correct. We get a spinning progress indicator that never stops with
uBO on.  With uBO disabled it continues to their interface following
login.  I completely understand this is problematic to troubleshoot because
of this.

Jason A. Parker
Technology Department
Cinnaminson Township Public Schools

**Comment by parkerj-cinnaminson** [comment]
To clarify, we do not get the account not found error in any of those
circumstances

Jason A. Parker
Technology Department
Cinnaminson Township Public Schools

**Comment by okiehsch** [comment]
Looking at your logs my best guess is that the redirection  of  `cloudflare.com/cdn-cgi/trace` causes your issue.
 I don't see that request on my end, so it's really just a guess.
You can try disabling that redirection by adding
````
@@||cloudflare.com/cdn-cgi/trace$xhr,redirect-rule=noop.txt,domain=cinnaminson.benchmarkuniverse.com
````
to your filter list.

**Comment by iam-py-test** [comment]
@parkerj-cinnaminson just by the way, your comments have your full name and other details

**Comment by parkerj-cinnaminson** [comment]
Thanks for the comment update.

So we were able to do further testing.  That filter fixed it for us, but all users of benchmark in other districts were seeing the same issue.  Modifying it to:
`@@||cloudflare.com/cdn-cgi/trace$xhr,redirect-rule=noop.txt,domain=benchmarkuniverse.com`
and putting it in one of your correction filters would address this for all benchmark users (it's an education platform, so I believe this would be a safe add)  Is that possible?  Thank you!
