### ISSUE TITLE
tingfm.com: detection

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10953]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://tingfm.com/radio/119`

### Category

detection

### Describe the issue

The page detected an ad filter and prompted.

> You have been detected blocking ads
> 
> TingFM will stop the service for users who blocked ads (including those who blocked before and temporarily canceled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66902050/146483842-e1726f85-e2b3-4946-943b-25d31b4744b4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 101703
  cosmetic: 102751
  scriptlet: 19204
  html: 615
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 59077-301, 29m
    ublock-annoyances: 4335-4, 29m
  default: 
    ublock-filters: 30587-52, 29m
    ublock-badware: 3573-1, 29m
    ublock-privacy: 184-0, 29m
    ublock-abuse: 81-0, 29m
    ublock-unbreak: 1733-0, 28m
    easylist: 62004-570, 28m
    easyprivacy: 26502-475, 28m
    urlhaus-1: 7269-0, 28m
    plowe-0: 3690-3, 28m
    CHN-0: 26904-115, 29m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4657
  launchFromSelfie: false
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
`tingfm.com##+js(nostif, ad)`

@Yuki2718  CHN list ?

**Comment by shenzhiming88** [comment]
@mapx-
```
tingfm.com#%#//scriptlet("prevent-setTimeout", "adblock")
```
UBO does not seem to support this syntax, so you may still need to add filters to list

**Comment by gorhill** [comment]
AdGuard converts that syntax to uBO's one, so that filter will be present in AdGuard Chinese used by uBO -- I just checked and it's already in there, just force an update of the list.

**Comment by shenzhiming88** [comment]
> AdGuard converts that syntax to uBO's one, so that filter will be present in AdGuard Chinese used by uBO -- I just checked and it's already in there, just force an update of the list.

Ok, I simply assumed that the syntax was different and therefore not applicable. Sorry.
