### ISSUE TITLE
meteoetradar.com: breakage

### ISSUE THREAD

**Issue by edel79** [uBlockOrigin/uAssets#10958]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.meteoetradar.com/carte-meteo`

### Category

breakage

### Describe the issue

Page is blank. Root element seems to be blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 91
filterset (summary): 
  network: 93815
  cosmetic: 48782
  scriptlet: 16306
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26058-23, 4d.2h.22m
    easylist: 61726-156, 4d.2h.20m
    easyprivacy: 26486-346, 4d.2h.18m
    plowe-0: 3687-818, 5d.11h.45m
    ublock-abuse: 81-1, 4d.2h.16m
    ublock-badware: 3570-69, 4d.2h.14m
    ublock-filters: 29871-300, 4d.2h.28m
    ublock-privacy: 189-2, 4d.2h.26m
    ublock-unbreak: 1712-39, 4d.2h.24m
    urlhaus-1: 7463-0, 1d.46m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 291
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
@ryanbr for EL

```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=meteoetradar.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=meteoetradar.com
@@||securepubads.g.doubleclick.net/pagead/ppub_config$xhr,domain=meteoetradar.com
@@||securepubads.g.doubleclick.net/gampad/ads?$xhr,domain=meteoetradar.com
```
