### ISSUE TITLE
gfycat.com: breakage

### ISSUE THREAD

**Issue by Diggason** [uBlockOrigin/uAssets#10959]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://gfycat.com/`

### Category

breakage

### Describe the issue

Gfycat doesn't load when ublock is enabled on chrome, it sits there stuck in an infinite loading loop and for some reason it kinda slows down the browser while doing so? Not much but it doesn't close immediately when I middle click it which is weird.

Gfycat works in incognito mode and when ublock origins is disabled. I cannot watch the gif when its integrated on a website but if I disable ublock on that website it does work. 

I tried opening gfycat on a different browser (brave) and it worked just fine, with the same extensions as I have on chrome. I did try to disable everything but ublock and it still didn't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77577
  cosmetic: 39911
  scriptlet: 16378
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62005-8, 2m
    easyprivacy: 26503-17, 2m
    plowe-0: 3691-810, 2m
    ublock-abuse: 81-0, 2m
    ublock-badware: 3569-61, 2m
    ublock-filters: 30040-132, 2m
    ublock-privacy: 188-2, 2m
    ublock-unbreak: 1723-39, 2m
    urlhaus-1: 7269-0, 2m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 406
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
Also cannot reproduce on Chromium.

**Comment by gorhill** [comment]
Unable to reproduce. You have 10 custom filters, did you verify that your own filters are not causing your issue?

**Comment by Diggason** [comment]
> Unable to reproduce. You have 10 custom filters, did you verify that your own filters are not causing your issue?

Yes, my filters are not causing the issue.

**Comment by gorhill** [comment]
Since we can't reproduce, you will have to investigate on your side what is causing the issue, could be other extensions or something else specific to your system. Use the logger to find out what uBO is blocking, and if nothing is unduly blocked, you will have to investigate elsewhere than in uBO.

**Comment by Diggason** [comment]
![gnsgrs](https://user-images.githubusercontent.com/96296055/146558356-40e54f88-0820-4689-9f7c-c1e3a2db1ed0.jpg)
So I'm not sure if I did it correctly but this is the results:

**Comment by gorhill** [comment]
In your opening comment, you say that the issue occurs at:

    https://gfycat.com/

In the screenshot of the logger, you seem to load a specific URL. Please provide that URL, we need to try to reproduce **exactly** the issue as you experience it.

**Comment by gorhill** [comment]
Also, on my side I get tons of requests to `https://thumbs.gfycat.com/`, I see none of this in your screenshot -- so it's as if your browser is not firing those requests.

**Comment by Diggason** [comment]
![fesafae](https://user-images.githubusercontent.com/96296055/146561347-7293a304-770b-4b9e-8e48-6d9995d08323.jpg)

Just to be clear gfycat doesn't work for any URL.

For reference here I am doing the same test but using Brave: 
![sdfweww](https://user-images.githubusercontent.com/96296055/146561756-74097baf-1474-4404-9fb5-14bfa1067992.jpg)


> Also, on my side I get tons of requests to https://thumbs.gfycat.com/, I see none of this in your screenshot -- so it's as if your browser is not firing those requests.

How would I go about asking chrome to fire a request?

**Comment by gorhill** [comment]
If uBO's logger is not reporting requests to `thumbs.gfycat.com`, it's because the browser is not firing them, or (unlikely) is not reporting them to uBO. So something outside uBO is causing your issue. An example of something which could cause this is that a CSP for that site is preventing the browser from fetching images from `thumbs.gfycat.com` -- look at what the browser console for that `gfycat` page is reporting.

**Comment by Diggason** [comment]
Ok once again I'm not sure I did it right but this was the result:
![gma,ofa](https://user-images.githubusercontent.com/96296055/146563387-a26e9786-5303-494f-b610-7d129fea8413.jpg)
The upper result is coinbase wallet extension, the bottom one I have no idea.

**Comment by gorhill** [comment]
Do you see network requests to `thumbs.gfycat.com` in the Network pane in the page's dev tools?

**Comment by Diggason** [comment]
I see a request to gfycat.com but not to thumbs.gfycat.com. However I had an issue reported and opened it and this is what it said:
![efwafawe](https://user-images.githubusercontent.com/96296055/146565581-8ff05057-1cf8-442d-aaf4-1a18648f3d0f.jpg)

**Comment by gorhill** [comment]
Can you show me the same pane with uBO disabled? (leave the issue out, it's just an inconsequential warning, unrelated to your issue).

**Comment by gorhill** [comment]
Ok, as soon as I add that _"Coinbase Wallet"_ extension, the site `https://gfycat.com/` starts to be broken, CPU usage to the ceiling, fans spinning wildly.

**Comment by iam-py-test** [comment]
> Ok, as soon as I add that _"Coinbase Wallet"_ extension, the site `https://gfycat.com/` starts to be broken, CPU usage to the ceiling, fans spinning wildly.

What is that extension supposed to do?
It sounds like some kind-of malware or at least broken

**Comment by Diggason** [comment]
Ok well it seems like the coinbase wallet was causing all the issues, removed it and ubo now works with gfycat. My bad for causing such a ruckus.

**Comment by gorhill** [comment]
Looks like this uBO filter is interfering:

    gfycat.com##+js(acis, Math, ='\x)

**Comment by iam-py-test** [comment]
I guess it was removed, but it used to be that the form asked if you could reproduce with all other extensions disabled

**Comment by gorhill** [comment]
I don't know what this _"Coinbase Wallet"_ extension does, but it injects a 6MB minified inline script in every page visited from a content script function named `injectWalletLinkProvider`  -- you won't be able to see the inline script tag in the DOM because it's removed immediately, but the code does run.

As per extension description in CWS, not sure why it needs to inject such gigantic inline sript into every visited page -- its behavior does not seem to match its published purpose.

**Comment by iam-py-test** [comment]
> I don't know what this _"Coinbase Wallet"_ extension does, but it injects a 6MB minified inline script in every page visited from a content script function named `injectWalletLinkProvider` -- you won't be able to see the inline script tag in the DOM because it's removed immediately, but the code does run.
> 
> As per extension description in CWS, not sure why it needs to inject such gigantic inline sript into every visited page -- its behavior does not seem to match its published purpose.

So it's malware or it's hacked

**Comment by iam-py-test** [comment]
For those curious, the source code: [2.5.6_0.zip](https://github.com/uBlockOrigin/uAssets/files/7736371/2.5.6_0.zip)

**Comment by iam-py-test** [comment]
@gorhill maybe there should be a new checkbox for other extensions in the issue report?

**Comment by gorhill** [comment]
I want to keep the checkboxes to a minimum otherwise I suspect it's seen as a chore and people end up checking the boxes untruthfully. In general I do not expect other extensions to intefere negatively, except for other blockers. In the rare case where a non-blocker extension interfere, we will ask if we can't reproduce, and [here I did ask](https://github.com/uBlockOrigin/uAssets/issues/10959#issuecomment-996752334) _"... you will have to investigate on your side what is causing the issue, could be other extensions ..."_.

**Comment by Diggason** [comment]
> I don't know what this _"Coinbase Wallet"_ extension does

It's a wallet for storing crypto. I'm using something else now and hadn't thought to remove it until now.
