### ISSUE TITLE
mha.fi: privacy

### ISSUE THREAD

**Issue by androidkotlindev** [uBlockOrigin/uAssets#10961]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://mha.fi/`

### Category

privacy

### Describe the issue

Connects to api.cdn.mha.fi/latest.js, and after that the script loads api.cdn.mha.fi/simple.gif (one pixel image) which sends information to simpleanalytics.com.

I think a potential fix for this would maybe be blocking api.cdn.mha.fi. (And yes, I know that simpleanalytics.com respects privacy, but i think it's still good to block analytics.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 94
filterset (summary): 
  network: 77397
  cosmetic: 40043
  scriptlet: 16380
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62028-8, 3m
    easyprivacy: 26503-17, 3m
    plowe-0: 3691-810, 3m
    ublock-abuse: 81-0, 3m
    ublock-badware: 3569-61, 3m
    ublock-filters: 30185-132, 3m
    ublock-privacy: 188-2, 3m
    ublock-unbreak: 1727-39, 3m
    urlhaus-1: 7061-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3289
  launchFromSelfie: false
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by androidkotlindev** [comment]
"FIN: Adblock List for Finland" filter list does **not** fix this issue.

**Comment by krystian3w** [comment]
I suppose @peace2000 no like block privacy in ad regiona list.

**Comment by peace2000** [comment]
Finnish list handles ads, not privacy stuff - which belongs to EP.

**Comment by krystian3w** [comment]
`theel0ja` still alive? No have commits on account and private page generate error 503?

**Comment by peace2000** [comment]
Haven't heard of him since March 2020.

**Comment by datanomi** [comment]
Wanted to add to this even though it's closed now, simpleanalytics doesn't track you if you have Do Not Track Enabled.
![gqhc6](https://user-images.githubusercontent.com/76632422/146824642-fb9bce1d-496f-4d3c-8bf4-c9d4816a2e56.png)

**Comment by krystian3w** [comment]
uBo no enable this option also may generate new fingerprint.

**Comment by iam-py-test** [comment]
> Wanted to add to this even though it's closed now, simpleanalytics doesn't track you if you have Do Not Track Enabled. ![gqhc6](https://user-images.githubusercontent.com/76632422/146824642-fb9bce1d-496f-4d3c-8bf4-c9d4816a2e56.png)

80-90% of users don't even have DNT enabled. uBo is designed to protect all users against all tracking. 
It is analytics regardless of if it respects DNT or not - besides, the site owner probably can disable that...

**Comment by bluelhf** [comment]
> > Wanted to add to this even though it's closed now, simpleanalytics doesn't track you if you have Do Not Track Enabled. ![gqhc6](https://user-images.githubusercontent.com/76632422/146824642-fb9bce1d-496f-4d3c-8bf4-c9d4816a2e56.png)
> 
> 80-90% of users don't even have DNT enabled. (I don't because it only makes me more identifiable, which @krystian3w already said) uBo is designed to protect all users against all tracking. It is analytics regardless of if it respects DNT or not - besides, the site owner probably can disable that...

@datanomi is the site owner

**Comment by datanomi** [comment]
> > > Wanted to add to this even though it's closed now, simpleanalytics doesn't track you if you have Do Not Track Enabled. ![gqhc6](https://user-images.githubusercontent.com/76632422/146824642-fb9bce1d-496f-4d3c-8bf4-c9d4816a2e56.png)
> > 
> > 
> > 80-90% of users don't even have DNT enabled. (I don't because it only makes me more identifiable, which @krystian3w already said) uBo is designed to protect all users against all tracking. It is analytics regardless of if it respects DNT or not - besides, the site owner probably can disable that...
> 
> @datanomi is the site owner

Alright alright, I will remove the analytics from my site, they didn't gather much data anyway.

**Comment by androidkotlindev** [comment]
There's still a script from jsdelivr.net, could you copy it locally?

**Comment by datanomi** [comment]
> There's still a script from jsdelivr.net, could you copy it locally?

Yup, done that also.

**Comment by uBlock-user** [comment]
It's blocked in EasyPrivacy and always has, unconditionally, according to their policy, this is not up for debate.
