### ISSUE TITLE
[nsfw] login.i-ready.com: detection

### ISSUE THREAD

**Issue by Naxmix** [uBlockOrigin/uAssets#10962]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://login.i-ready.com/`

### Category

detection

### Describe the issue

Cant do reading

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78617
  cosmetic: 39706
  scriptlet: 16341
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61777-8, 3d.45m
    easyprivacy: 26495-17, 3d.43m
    plowe-0: 3690-809, 3d.41m
    ublock-abuse: 81-0, 3d.37m
    ublock-badware: 3509-61, 3d.33m
    ublock-filters: 29980-132, 3d.31m
    ublock-privacy: 183-2, 3d.29m
    ublock-unbreak: 1716-39, 3d.27m
    urlhaus-1: 8445-0, 22m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5695
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by Naxmix** [comment]
HI

**Comment by iam-py-test** [comment]
I can not reproduce. Do you have to login?

**Comment by iam-py-test** [comment]
@Naxmix please provide more details
