### ISSUE TITLE
turkanime.co: ads

### ISSUE THREAD

**Issue by Darktowertr** [uBlockOrigin/uAssets#10963]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.turkanime.co/`

### Category

ads

### Describe the issue

The site has changed its domain name. Cosmetic filters and redirect links in the footer are not blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 148207
  cosmetic: 95750
  scriptlet: 28018
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 62158-665, now
    adguard-spyware: 24612-556, now
    adguard-spyware-url: 402-12, now
    block-lan: 44-0, now
    curben-phishing: 13584-0, now
    curben-pup: 387-0, now
    dpollock-0: 16947-172, now
    fanboy-cookiemonster: 20484-14, now
    fanboy-thirdparty_social: 68-0, now
    mvps-0: 8730-1817, now
  default: 
    TUR-0: 9427-97, now
    easylist: 62030-1018, now
    easyprivacy: 26503-10668, now
    plowe-0: 3691-1453, now
    ublock-abuse: 81-0, now
    ublock-badware: 3569-192, now
    ublock-filters: 30183-2938, now
    ublock-privacy: 188-25, now
    ublock-unbreak: 1727-108, now
    urlhaus-1: 7061-6, now
filterset (user): [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 555
  launchFromSelfie: true
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
> redirect links in the footer 

Which ones ?

**Comment by Darktowertr** [comment]
#.AltkisimMenu.col-xs-9
