### ISSUE TITLE
agilent.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#10960]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.agilent.com/cs/agilent/en-us/globaloptout/form`

### Describe the issue

Unsubscribe element blocked.

### uBlock Origin version

1.39.2

### Browser name and version

Chrome 96

### Settings

Default

### Notes

`@@||explore.agilent.com/GlobalOptOut$subdocument,domain=agilent.com`

**Comment by mapx-** [comment]
@ryanbr  EP issue
