### ISSUE TITLE
putme.ga js script removal from filter list [NSFW]

### ISSUE THREAD

**Issue by MandoCoding** [uBlockOrigin/uAssets#10974]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://forum.sexy-egirls.com/` [NSFW]

### Describe the issue

The addition of javascript filters from putme.ga (issue 10929, lines 35451+ in the filter list) means that the upload images button on the `https://forum.sexy-egirls.com/` [NSFW] forum is blocked from display. This prevents users from uploading images without disabling ublock origin or customising their filters.
Can you please remove this addition from your filter list or make amends such that the upload images script is not filtered.
The specific script that needs to be removed from the filter list is the putme.ga usage of the chevereto popup upload plugin, more info can be found here: `https://v3-docs.chevereto.com/features/integrations/pup.html#how-it-works` [SFW]

### Screenshot(s)

Without ublock origin:
![Without ublock origin](https://user-images.githubusercontent.com/88238944/146651353-09097682-19e3-4ac4-a50a-4726cda9c73d.JPG)
With ublock origin:
![With ublock origin](https://user-images.githubusercontent.com/88238944/146651361-4027712d-f4e7-4063-9de0-47cc28f4a92d.JPG)

As seen the 'upload images' button disappears when ublock is enabled

### uBlock Origin version

1.39.2

### Browser name and version

Chrome 96.0.4664.110 

### Settings

None

**Comment by MandoCoding** [comment]
Hi, 

Thanks for the fast response but unfortunately you have misinterpreted the request. I would like for ublock origin to not filter putme.ga/sdk/pup.js
I want that script to be allowed to function so that people can use the uploads images button
or put simply, please remove the line which has putme.ga/sdk/pup.js on it

**Comment by MandoCoding** [comment]
You could add "forum.admiregirls.com##+js(acis, $, test)" instead rather than a separate site not linked to putme.ga

**Comment by uBlock-user** [comment]
> forum.admiregirls.com##+js(acis, $, test)

That's for anti-adblock, not popups, this popup that's created is for `putme.ga` login ?

**Comment by MandoCoding** [comment]
The problem is that by implementing a block of putme.ga you have broken functionality on `https://forum.sexy-egirls.com/` when attempting to solve an issue on another unrelated site `https://forum.admiregirls.com/`

**Comment by uBlock-user** [comment]
@MandoCoding You didn't answer my question, answer the question I asked in https://github.com/uBlockOrigin/uAssets/issues/10974#issuecomment-997259973

**Comment by MandoCoding** [comment]
yes, the pop-up that is created is for `putme.ga` login which is required to upload images. The details of the popup are covered here `https://v3-docs.chevereto.com/features/integrations/pup.html#how-it-works` and it is not spam or malicious

The other issue https://github.com/uBlockOrigin/uAssets/issues/10929 appears to be an anti-adblock issue and not a pop-up issue but I have not looked into it

**Comment by uBlock-user** [comment]
> appears to be an anti-adblock issue and not a pop-up issue but I have not looked into it

When we fix something, everything that needs blocking also gets blocked specifically popups.

**Comment by MandoCoding** [comment]
Understood, thank you for your help and very fast response. 
In hindsight I could have been more clear in stating that the `putme.ga` pop-up is required and not malicious/spam in my initial issue report.
