### ISSUE TITLE
rohlik.cz: breakage

### ISSUE THREAD

**Issue by Werkov** [uBlockOrigin/uAssets#10971]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.rohlik.cz/vitejte`

### Category

breakage

### Describe the issue

The login button ("Přihlásit") won't respond to clicks.

![Screenshot 2021-12-18 at 17-23-14 Online supermarket Rohlik cz — nejrychlejší doručení ve městě](https://user-images.githubusercontent.com/630751/146648234-feb632ff-c362-449d-b62e-811396515286.png)

When I disable the uBO, a `<div>` pops up with the login form. I noticed that there's no `onClick` event handler with uBO enabled (but there is one when it's disabled).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 89823
  cosmetic: 109104
  scriptlet: 16694
  html: 607
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 1d.18h.14m
    adguard-social: 15024-37, 2d.18h.15m
    fanboy-annoyance: 59045-23350, 8d.18h.50m
    fanboy-social: 23162-1064, 2d.18h.13m
    CZE-0: 772-0, 7h.40m
    DEU-0: 4974-3, 7h.38m
  default: 
    ublock-filters: 30563-80, 2d.18h.11m
    ublock-badware: 3573-1, 2d.18h.23m
    ublock-privacy: 184-0, 2d.18h.9m
    ublock-abuse: 81-0, 2d.18h.21m
    ublock-unbreak: 1715-1, 2d.18h.25m
    easylist: 61824-582, 2d.18h.19m
    easyprivacy: 26496-538, 2d.18h.17m
    urlhaus-1: 7938-0, 7h.36m
    plowe-0: 3697-4, 11d.17h.49m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 25 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 683
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr `@@||rohlik.cz/_next/static/chunks/iconEmail.$script,domain=rohlik.cz` for Annoyance.

**Comment by gorhill** [comment]
Caused by `/iconemail.` in Fanboy's Annoyance.

**Comment by Yuki2718** [comment]
@Werkov BTW You don't need Fanboy Social as Fanboy Annoyance includes it.

**Comment by krystian3w** [comment]
Maybe often disable FA, then for short test need FS.
