### ISSUE TITLE
dalmatinskiportal.hr: ads

### ISSUE THREAD

**Issue by IvoKvesic** [uBlockOrigin/uAssets#10973]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://dalmatinskiportal.hr/naslovnica`

### Category

ads

### Describe the issue

The page has plenty of ads. Disabled or engaged the uBlock filter, the situation is the same.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/18115348/146651436-859ee063-2e0c-41bf-adcd-e8b9b497a587.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78659
  cosmetic: 39707
  scriptlet: 16358
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61777-8, 4d.24m
    easyprivacy: 26495-17, 4d.22m
    plowe-0: 3687-809, 5d.4h.53m
    ublock-abuse: 81-0, 4d.20m
    ublock-badware: 3570-61, 4d.18m
    ublock-filters: 29993-132, 4d.16m
    ublock-privacy: 183-2, 4d.14m
    ublock-unbreak: 1704-39, 4d.12m
    urlhaus-1: 8445-0, 3h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 49 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 196
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
add

```
dalmatinskiportal.hr##.popup-baner
dalmatinskiportal.hr##.ad-click-banner
dalmatinskiportal.hr##.banner
```

@ryanbr

**Comment by IvoKvesic** [comment]
Thanks a lot!
