### ISSUE TITLE
placeholder not being removed after ad is being blocked

### ISSUE THREAD

**Issue by codafi21** [uBlockOrigin/uAssets#10970]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.windowscentral.com/msedgeredirect-can-work-around-microsofts-block-forces-you-use-edge`

### Describe the issue

the 1 specific placeholder aint being removed.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/93474348/146645599-3dd6b27c-86bc-433a-81fc-720b5818c3c7.png)

### uBlock Origin version

1.39.2

### Browser name and version

ms edge 96.0.1054.62 

### Settings

no change

### Notes

other pages on windowscentral.com also has this problem

**Comment by mapx-** [comment]
add
`windowscentral.com##.article-body__suppl_content--taboola-mid-article`

@ryanbr
