### ISSUE TITLE
androidacy.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10983]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.androidacy.com/`

### Category

detection

### Describe the issue

Open in new Private Window/Incognito session, wait about 10s, an anti-adblock appears. Refreshing the site will make it disappear tho.

Proposed filter:

`androidacy.com##+js(acis, String.fromCharCode, _0x)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/146664414-09f23b5e-61c6-487a-8b45-7d322e0a1d99.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77609
  cosmetic: 40074
  scriptlet: 16347
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30764-133, 1h.19m
    ublock-badware: 3575-1, 1h.19m
    ublock-privacy: 185-0, 1h.19m
    ublock-abuse: 81-0, 1h.19m
    ublock-unbreak: 1739-0, 1h.19m
    easylist: 62071-449, 2h.23m
    easyprivacy: 26520-489, 1h.19m
    urlhaus-1: 7217-0, 1h.19m
    plowe-0: 3709-3, 1h.19m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 651
  launchFromSelfie: false
popupPanel: 
  blocked: 8
```
</details>

**Comment by stephenhawk8054** [comment]
Another detection. After the page finishes loading, wait about 10s, an anti-adblock overlay appears and can only be closed after waiting 5s countdown.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/150050902-42ee53a1-8369-4678-a3ae-4a1c6f24847e.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78330
  cosmetic: 41873
  scriptlet: 19206
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4368-4, 1m
  default: 
    ublock-filters: 30757-31, 1m
    ublock-badware: 3728-1, 1m
    ublock-privacy: 187-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1694-0, 1m
    easylist: 63126-591, 1m
    easyprivacy: 26635-480, 1m
    urlhaus-1: 7040-0, 1m
    plowe-0: 3682-2, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 801 ms
popupPanel: 
  blocked: 8
```
</details>

Proposed filter:

`*$xhr,redirect-rule=nooptext,domain=androidacy.com`

or

`androidacy.com##+js(no-fetch-if, method:HEAD)`

**Comment by cyberboh** [comment]
@mapx- pls update filter, can not copy page

**Comment by FanOfRootBeer** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/160881
anti-adblock if proceeding as if downloading
