### ISSUE TITLE
wenku.baidu.com: anti-copy

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#10986]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://wenku.baidu.com/link?url=JFrZLtxjd90S2BwU5akCbwa1cd8uBQGH1rH27quW3TlE1PRwmshrchkjdwKQs5BKKu1tjmUxmTKEJCzIZHXBrZXqQOcbYimbsJE8kN_MlhGyGuD1xzqNTtq2jsknd2-HuF7IL9hmreNBRhbreFEZQ_`

### Category

[unknown]

### Describe the issue

Copying is disabled on this page. When using the right mouse click, the selected text will be unchecked; using the shortcut key will pop up a window to indicate that copying is prohibited. Please deal with it. Thanks!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66902050/146665256-9ac5166f-9a36-420e-a6fd-25216781e462.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 103212
  cosmetic: 102599
  scriptlet: 19235
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1565-0, 1d.2h.33m
    block-lan: 44-0, 3h.9m
    fanboy-annoyance: 59086-151, 20h.25m
    ublock-annoyances: 4325-127, 3d.13h.52m
  default: 
    CHN-0: 26918-86, 1d.14h.27m
    easylist: 61797-15, 3d.13h.45m
    easyprivacy: 26496-43, 3d.13h.43m
    plowe-0: 3690-811, 2d.14h.4m
    ublock-abuse: 81-0, 2d.13h.41m
    ublock-badware: 3569-61, 2d.14h.4m
    ublock-filters: 30018-173, 2d.14h.4m
    ublock-privacy: 188-10, 3d.13h.41m
    ublock-unbreak: 1717-43, 3d.13h.47m
    urlhaus-1: 7217-0, 21m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 559
  launchFromSelfie: true
popupPanel: 
  blocked: 88
```
</details>

**Comment by Yuki2718** [comment]
Not exactly anti-copy.

**Comment by shenzhiming88** [comment]
@Yuki2718 How? If I use a shortcut key, or the copy button to make a copy, then a popup will appear and prohibit the copy.

**Comment by Yuki2718** [comment]
In any case those "texts" are actually canvas...

**Comment by Yuki2718** [comment]
Right-click can be recovered by `wenku.baidu.com##+js(aeld, contextmenu, eventContextMenu)`. Popup can be blocked by `wenku.baidu.com##+js(aeld, keydown, event.dispatch.apply)`. But you can't copy as those texts are not texts.

**Comment by Yuki2718** [comment]
Okay this: `wenku.baidu.com##+js(acis, pageData)` but kinda breaks page layout.

**Comment by shenzhiming88** [comment]
> Right-click can be recovered by wenku.baidu.com##+js(aeld, contextmenu, eventContextMenu).

Still can't seem to restore the right click.

**Comment by Yuki2718** [comment]
> Still can't seem to restore the right click. More precisely, when the text is selected, right-clicking does not work.

I can.

**Comment by shenzhiming88** [comment]
> `||hm.baidu.com/hm.js` is better.

Yes, you are right.
And I found this in EasyPrivacy.
```
||hm.baidu.com^$third-party
```
I don't know why this domain is not blockedfor the first party

**Comment by Yuki2718** [comment]
> ||hm.baidu.com^$third-party
> ```
> 
> I don't know why this domain is not blocked in the first party.

@ryanbr Maybe remove `$third-party`?

**Comment by shenzhiming88** [comment]
I think you can add these filters first.
```
wenku.baidu.com##+js(aeld, keydown, event.dispatch.apply)
||hm.baidu.com/hm.js
```
Thank you for checking

**Comment by Yuki2718** [comment]
`wenku.baidu.com##+js(aeld, contextmenu, eventContextMenu)` is also needed.

**Comment by shenzhiming88** [comment]
But strangely enough, even when I add these three filters, the right-click menu still does not appear. If I use the menu key on my keyboard, there is no option to copy. It can only be copied via the mini-menu that comes with `Microsoft Edge`.
![2021-12-19_15-26-44](https://user-images.githubusercontent.com/66902050/146667298-7df976df-13cd-4864-9dda-84f619b6c842.gif)

**Comment by Yuki2718** [comment]
You're right, can reproduce on Chromium. I was testing on Firefox. BTW apparently `click.hm.baidu.com` is click-through tracker, e.g.

**Comment by Yuki2718** [comment]
Maybe change to `wenku.baidu.com##+js(aeld, /contextmenu|dragstart|keydown/, event.dispatch.apply)`. But bad news is the effect of `||hm.baidu.com/hm.js` appears to be temporal, reload without clearing cache and then again text goes canvas.

**Comment by shenzhiming88** [comment]
Aha, Baidu uses many methods to prevent content from being copied. But at least, this filter works for me.
![image](https://user-images.githubusercontent.com/66902050/146667503-646de267-c19d-4e3a-b8d7-799efafcd645.png)
