### ISSUE TITLE
hiveworkscomics.com: breakage

### ISSUE THREAD

**Issue by z1nho** [uBlockOrigin/uAssets#10980]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://hiveworkscomics.com/`

### Category

breakage

### Describe the issue

Website's main page fails to load its preview image tiles with default ruleset.

Fixed with permission rule allowing images from the required webserver folder:

@@||hiveworkscomics.com/frontboxes/*$image,1p

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Broken (default):
![broken](https://user-images.githubusercontent.com/2530953/146663149-7e5472cb-aa58-44e5-8479-7f941d4fc3c6.png)

Fixed (with custom filter):
![fixed](https://user-images.githubusercontent.com/2530953/146663165-77317ccf-65bc-4183-b3f9-71c3b3694538.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78772
  cosmetic: 40069
  scriptlet: 16346
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30763-133, 6h.47m
    ublock-badware: 3543-1, 6h.49m
    ublock-privacy: 184-0, 6h.45m
    ublock-abuse: 81-0, 6h.57m
    ublock-unbreak: 1738-0, 6h.55m
    easylist: 62060-449, 6h.53m
    easyprivacy: 26508-484, 6h.51m
    urlhaus-1: 8445-0, 6h.43m
    plowe-0: 3691-3, 2h.39m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 225
  launchFromSelfie: true
popupPanel: 
  blocked: 263
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
