### ISSUE TITLE
prmovies.xyz

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#10981]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://prmovies.xyz/freddie-mercury-the-final-act`

### Describe the issue

So this site is weird. It shows a popup upon first clicking on the video player. However, the video won't really play until you do something. That is, you need to click on a play button placed randomly on the player. If it isn't clicked, the player actually checks for that and will tell you to do it right.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/146663435-61f1afc4-a0cb-453a-9c0c-2dced4dd219e.png)

### uBlock Origin version

1.39.2

### Browser name and version

Firefox 95.0

### Settings

N/A

### Notes

Same with this site:
`https://movies7.pro/watch-antlers-2021-online-free`

**Comment by okiehsch** [comment]
> Same with this site:

It's not the same issue.
`https://movies7.pro/watch-antlers-2021-online-free`
`movies7.pro##+js(disable-newtab-links)`

**Comment by okiehsch** [comment]
Does 
`player.m4ufree.cam##+js(aopr, open)`
work for you for your primary issue?

**Comment by mapx-** [comment]
@okiehsch 

does this work for you ?

`m4ufree.cam##+js(aopr, BetterJsPop)`

working too:
`||player.m4ufree.cam/js/script-2.12.5.js$script,1p`

**Comment by ghajini** [comment]
```
player.m4ufree.cam##+js(nowoif)
||player.m4ufree.cam/cdn-cgi/trace$xhr,domain=player.m4ufree.cam
||waaw.to/cdn-cgi/trace$xhr,1p
```

**Comment by okiehsch** [comment]
> does this work for you ?
`m4ufree.cam##+js(aopr, BetterJsPop)`

Yes, but the site uses different video embed sites, for example
`https://prmovies.xyz/traffic/` uses `uwatchfree.cyou` and there are more, we ill have to add them over time.

**Comment by ghajini** [comment]
@okiehsch such sites aka waaw like get added to filters over here and they change alot

`https://github.com/uBlockOrigin/uAssets/issues/7702`
