### ISSUE TITLE
Adobe Fonts `primer.typekit.net` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#10998]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://theinitium.com/article/20210225-hongkong-cable-tv-china-desk-feature/` --> `POST` `https://primer.typekit.net/primer/******************`

### Describe the issue

`https://theinitium.com/article/20210225-hongkong-cable-tv-china-desk-feature/` --> `POST` `https://primer.typekit.net/primer/******************`

```
||primer.typekit.net^
```

![image](https://user-images.githubusercontent.com/75058881/146687058-a4413dba-4576-4c16-9c98-3e6248170f10.png)

### uBlock Origin version

n/a

### Browser name and version

n/a

### Settings

n/a

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Is this safe, `||use.typekit.net^$xmlhttprequest` ?
