### ISSUE TITLE
ilgeniodellostreaming.wf: popups

### ISSUE THREAD

**Issue by Indil** [uBlockOrigin/uAssets#10994]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://ilgeniodellostreaming.wf/episodi/the-witcher-2x3-sub-ita/`

### Category

popups

### Describe the issue

After few secs of been refreshing the page, it opens random potential risk/ads webpages... like crypto, ads ones etc...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/12199376/146675710-4d63283d-872e-4e98-bd04-99a1acdbfbbf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 20219
  cosmetic: 12940
  scriptlet: 16281
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ITA-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
  added: 
    adguard-mobile: 7011-16, 20h.11m
  default: 
    ublock-abuse: 81-0, 20h.5m
    ublock-badware: 3569-1, 20h.2m
    ublock-filters: 29871-41, 20h
    ublock-privacy: 189-0, 20h.7m
    ublock-unbreak: 1704-0, 20h.9m
    urlhaus-1: 7087-0, 15h.58m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 19245
  launchFromSelfie: true
popupPanel: 
  blocked: 2
  no-popups: true
```
</details>

**Comment by gorhill** [comment]
> - [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)

You actually removed default filter lists from your configuration, we do not support the removal of default filter lists:

```
removed: 
    ITA-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
```

**Comment by gorhill** [comment]
There is a clear warning at the top of the report page:

> To avoid burdening VOLUNTEERS with invalid or duplicate reports, disrespecting these steps WILL result in your account being blocked on this repo (temporarily, then permanently with repeated disregard for the template).
