### ISSUE TITLE
vecernji.hr: breakage

### ISSUE THREAD

**Issue by dariom007** [uBlockOrigin/uAssets#10991]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.vecernji.hr/vijesti/primijetili-da-se-nesto-mice-ispod-drvene-kucice-imali-su-sto-vidjeti-kada-su-je-podigli-1547964`

### Category

breakage

### Describe the issue

Ad Guard Annoyances filter is causing the video breakage on some sites. I deactivated all the filters and then activated one after the other until i came to the Ad Guard Annoyances filter which caused the video breakage. EasyList Cookie is causing the video breakage too. URL site i am referring too is just an example, there are more sites where video breakage is happening. I hope You can do something about that. Thanks!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![With uBlock Origin on](https://user-images.githubusercontent.com/96373232/146672445-e0be5070-be19-4136-9f33-d3c6f7152e74.JPG)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 85411
  cosmetic: 114630
  scriptlet: 18381
  html: 598
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48529-3533, 9m
    adguard-social: 15071-18, 9m
    fanboy-cookiemonster: 20492-18, 9m
    DEU-0: 4976-2, never
  default: 
    ublock-filters: 30283-35, never
    ublock-badware: 3494-1, never
    ublock-privacy: 183-1, never
    ublock-abuse: 74-0, never
    ublock-unbreak: 1707-0, never
    easylist: 60746-577, never
    easyprivacy: 25518-228, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-2, never
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
  blockingProfiles: 11111/#F00 11011/#C0F 11001/#00F 00001
  cloudStorageCompression: false
supportStats: 
  launchToReadiness: 316
  launchFromSelfie: true
popupPanel: 
  blocked: 25
```
</details>

**Comment by okiehsch** [comment]
We only fix breakage that happens with a default setup.
Adguard Annoyances and EasyList Cookie are not enabled by default.
`@@||sdk.privacy-center.org^$script,domain=vecernji.hr`
will fix the video on your end.

**Comment by gorhill** [comment]
@Yuki2718, `||privacy-center.org^$3p` in AdGuard Annoyances is causing the issue. This fixes it:

    @@||sdk.privacy-center.org^$3p,script,domain=vecernji.hr

**Comment by gorhill** [comment]
Same issue for EasyList Cookie, cc @ryanbr
