### ISSUE TITLE
`googleads.github.io` ads

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#10999]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js`
`https://googleads.github.io/`

### Describe the issue

`http://cablenews.i-cable.com/ci/news/article/37/781903` --> `https://googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js`

```
https://googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js
https://googleads.github.io/videojs-ima/dist/videojs.ima.js
```

```
||googleads.github.io^
or
||googleads.github.io^$third-party
```

### uBlock Origin version

n/a

### Browser name and version

n/a

### Settings

n/a

**Comment by uBlock-user** [comment]
@AdamWR

**Comment by Nojuuu** [comment]
@uBlock-user 

https://github.com/easylist/easylist/commit/187f6b990f8de42fd23ff6fd3831408a7e84eedc
