### ISSUE TITLE
yle.fi: privacy

### ISSUE THREAD

**Issue by androidkotlindev** [uBlockOrigin/uAssets#10993]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://yle.fi/news`

### Category

privacy

### Describe the issue

There are some analytics requests that are not blocked:
- dax.yle.fi/yya/event
- dax.yle.fi/yle/ylenews/s

This could be fixed by blocking dax.yle.fi
I would also recommend blocking tag-manager.yle.fi because it blocks all other analytics requests than dax.yle.fi/yya/event

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 94
filterset (summary): 
  network: 77610
  cosmetic: 40074
  scriptlet: 16388
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62073-8, 2h.29m
    easyprivacy: 26522-17, 2h.29m
    plowe-0: 3709-815, 2h.29m
    ublock-abuse: 81-0, 2h.29m
    ublock-badware: 3571-61, 2h.29m
    ublock-filters: 30201-133, 2h.29m
    ublock-privacy: 189-2, 2h.29m
    ublock-unbreak: 1728-39, 2h.29m
    urlhaus-1: 7217-0, 2h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3262
  launchFromSelfie: false
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
@ryanbr
