### ISSUE TITLE
Chinese `www.zhihu.com` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#10995]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.zhihu.com/question/265309145/answer/294683314` --> `https://www.zhihu.com/search?q=%E5%9B%9B%E5%B0%8F%E9%BE%99&search_source=Entity&hybrid_search_source=Entity&hybrid_search_extra=%7B%22sourceType%22%3A%22answer%22%2C%22sourceId%22%3A296590860%7D`

```
||zhihu.com^$removeparam=search_source
||zhihu.com^$removeparam=hybrid_search_source
||zhihu.com^$removeparam=hybrid_search_extra
```

### Describe the issue

Chinese `www.zhihu.com` tracker

### uBlock Origin version

n/a

### Browser name and version

chrome n/a

### Settings

n/a

**Comment by c2xusnpq6** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/103755

**Comment by shenzhiming88** [comment]
They do not handle trace parameters
Other filter lists can be used, such as `https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt`
CC @iam-py-test

**Comment by iam-py-test** [comment]
@shenzhiming88 thank you for alerting me
@c2xusnpq6 I have added it to that list in https://github.com/DandelionSprout/adfilt/commit/9f1f9cb56399de631cc798f0a7e29cdd8c24bac3. Next time you find tracking parameters, you can report them at https://github.com/DandelionSprout/adfilt/discussions/163

**Comment by c2xusnpq6** [comment]
> They do not handle trace parameters

https://github.com/uBlockOrigin/uAssets/commit/944938cbafa1b2c370447e8e99bb7cfcb3a67599 @shenzhiming88 👀

**Comment by shenzhiming88** [comment]
> > They do not handle trace parameters
> 
> [944938c](https://github.com/uBlockOrigin/uAssets/commit/944938cbafa1b2c370447e8e99bb7cfcb3a67599) @shenzhiming88 👀

This is strange, they didn't seem to deal with this issue before
https://github.com/uBlockOrigin/uAssets/pull/10010

> There is no list in uBO to deal with query parameters, it's best to submit to currently existing lists with that purpose, so as to not further burden filter list maintainers here.

**Comment by iam-py-test** [comment]
@mapx- opinion?

**Comment by loop0day** [comment]
Hi, something breaks after enabling these rules, I can't search by keyword now, but if I disable these rules, everything goes well.

![1](https://user-images.githubusercontent.com/34915817/146748947-5e9237fc-8fb8-42ca-90bb-2c57aa4c84d2.png)
![2](https://user-images.githubusercontent.com/34915817/146748962-69812cbe-255e-49fa-b5ba-eae0a020f9d6.png)
![3](https://user-images.githubusercontent.com/34915817/146748975-dac7a07e-cef4-43a0-bba0-1e7b952b3a77.png)
![4](https://user-images.githubusercontent.com/34915817/146748981-eaa78cde-fc2a-4de3-a37f-9083c1cbac12.png)

**Comment by iam-py-test** [comment]
@loop0day please show a screenshot of the logger

**Comment by iam-py-test** [comment]
Problem filter is `||zhihu.com^$removeparam=search_source`. Removed in https://github.com/DandelionSprout/adfilt/commit/93631922ca5ef7bb36897272d66910d4e11143e2.

**Comment by loop0day** [comment]
@iam-py-test 
![1](https://user-images.githubusercontent.com/34915817/146766840-b0f1556a-928a-4cf3-8e08-9742832333ed.png)
![2](https://user-images.githubusercontent.com/34915817/146767470-d2f03d26-623f-4160-b375-373ab0de0d00.png)
![3](https://user-images.githubusercontent.com/34915817/146767473-b6109d96-73ec-4860-bec0-e8f39ff4c67c.png)

**Comment by iam-py-test** [comment]
Thanks, but I was able to repro on my end.

**Comment by shenzhiming88** [comment]
@mapx- So, now the privacy list handles redundant parameters?
