### ISSUE TITLE
game24h.vn: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#10996]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://game24h.vn/game-hay-nhat/pikachu-c131g1285b15.html`

### Category

breakage

### Describe the issue

Click on the button in the game player, game cannot start and the game player becomes a white placeholder.

The situation is similar to `atozmath` issue: https://github.com/uBlockOrigin/uAssets/issues/10815#issuecomment-993219649

Proposed filters:

```
game24h.vn#@#.adsbyvli
@@||services.vlitag.com/adv1/*$script,domain=game24h.vn
@@||tag.vlitag.com/v1/*$script,domain=game24h.vn
@@||assets.vlitag.com/prebid/default/*$script,domain=game24h.vn
||assets.vlitag.com/plugins/*$script,redirect=noopjs,domain=game24h.vn
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=noopjs,domain=game24h.vn
game24h.vn##+js(set, window.vlipbChunk, noopFunc)
game24h.vn##+js(no-xhr-if, vliplatform)
game24h.vn##+js(aost, Object.assign, bidsBackHandler)
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/146678391-ad732410-ff66-459d-bd9d-f72c9d92d876.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78562
  cosmetic: 41359
  scriptlet: 16385
  html: 608
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2316-2, 4h.5m
  default: 
    ublock-filters: 30769-38, 1h.16m
    ublock-badware: 3580-1, 1h.16m
    ublock-privacy: 185-0, 1h.16m
    ublock-abuse: 81-0, 1h.16m
    ublock-unbreak: 1740-0, 1h.16m
    easylist: 62039-599, 4h.5m
    easyprivacy: 26522-483, 1h.16m
    urlhaus-1: 7248-0, 1h.16m
    plowe-0: 3709-3, 1h.16m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 429
  launchFromSelfie: false
popupPanel: 
  blocked: 27
```
</details>

**Comment by gorhill** [comment]
||assets.vlitag.com/plugins/*$script,redirect=noopjs,domain=game24h.vn
    ||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=noopjs,domain=game24h.vn

Could be replaced with:

    *$script,redirect-rule=noopjs,domain=game24h.vn

**Comment by mapx-** [comment]
@hoang-rio
