### ISSUE TITLE
red-by-sfr.fr: breakage

### ISSUE THREAD

**Issue by RouxAntoine** [uBlockOrigin/uAssets#10990]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.red-by-sfr.fr/mon-espace-client/redirect.html?D=AMAR`

### Category

breakage

### Describe the issue

French phone operator SFR, use ublock origin breakage to mask and force user to opt-in extra cost on mobile subscription.
The reported page use redirect and without following redirect the option is by default not opt-out

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 93542
  cosmetic: 49007
  scriptlet: 16259
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30427-204, 1d.6h.2m
    ublock-badware: 3564-1, 1d.2h.13m
    ublock-privacy: 184-0, 1d.1h.43m
    ublock-abuse: 72-0, 1d.1h.41m
    ublock-unbreak: 1717-0, 1d.1h.39m
    easylist: 62036-704, 1d.1h.37m
    easyprivacy: 26507-475, 1d.1h.35m
    urlhaus-1: 7087-0, 15h.41m
    plowe-0: 3697-3, 12d.16h.14m
    FRA-0: 26066-372, 1d.10h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4657
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by RouxAntoine** [comment]
with this rule : 

```
! 2021-12-19 https://www.red-by-sfr.fr
@@||www.sfr.fr/eTagP/ck.jsp?MLS~Mjg5Ojk7ODk2OA%3D%3D~99$script,domain=www.red-by-sfr.fr
```

the redirection and website process work properly

**Comment by gorhill** [comment]
With your URL, I am redirected to a login page. Not sure to understand what you are reporting exactly -- we can't add filter for cases we can't reproduce.

**Comment by RouxAntoine** [comment]
Oh yes this required account to reproduce. Do you want some capture screen ?

**Comment by gorhill** [comment]
> `@@||www.sfr.fr/eTagP/ck.jsp?*$script,domain=www.red-by-sfr.fr`

What block rule is being overridden by this exception filter?

**Comment by RouxAntoine** [comment]
Does this answer the question ?

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/5455181/146677076-8e0ac07b-4aa9-4cdd-a0ae-b9715af2f695.png">

**Comment by RouxAntoine** [comment]
Does this answer the question ?

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/5455181/146677168-5e51a4b1-6f1b-448b-a11b-f63a523f9fd3.png">

**Comment by gorhill** [comment]
Does this work?

    ||www.sfr.fr^$1p,script,redirect-rule=noop.js

**Comment by RouxAntoine** [comment]
I don't really understand this filter rule but this one (the corrected) works :)

**Comment by gorhill** [comment]
It redirects the blocked script to a local, empty JS file. This means the site could change the bait script and it would still be defused by uBO. I can't reproduce the issue but what you reported is fine by me to add a filter in uBlock filters.

**Comment by RouxAntoine** [comment]
okay thanks
