### ISSUE TITLE
Ads on finanzen.net

### ISSUE THREAD

**Issue by curiosity-seeker** [uBlockOrigin/uAssets#110]
### URL(s) where the issue occurs

`http://www.finanzen.net/`

### Describe the issue

There are 2 ads below the top and at the right side of that page, sometimes only one of them appears.

### Screenshot(s)
![finanzennet](https://cloud.githubusercontent.com/assets/14075215/18003867/cb5d5d0e-6b90-11e6-95b3-f3b993ae05d1.jpeg)

### Versions

- Browser/version: Firefox 48.0.1 with e10s enabled (browser.tabs.remote.autostart = true,
browser.tabs.remote.force-enable = true, dom.ipc.processCount = 8)
- uBlock Origin version: 1.8.5rc3

### Settings

- uBlock filters
- uBlock filters Badware
- uBlock filters Privacy
- uBlock filters Unbreak
- Adblock Warning Removal List
- Anti-Adblock Killer reek
- Spam 404
- Fanboy's Ultimate List
- Easylist Germany 
- Prebake
- http://www.antipubfirefox.org/antipub/antipubfirefox-adblocklist-current-expanded.txt
- https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt
- https://adguard.com/en/filter-rules.html?id=3
- https://adguard.com/en/filter-rules.html?id=2
- https://adguard.com/en/filter-rules.html?id=6
- https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt

... and all hosts files in uMatrix.

### Notes
I've added the filters suggested on https://forums.lanik.us/viewtopic.php?f=90&t=32159&p=100829&hilit=finanzen.net#p100829:
```
finanzen.net###bs_abstand
||assets3.finanzen.net^$xmlhttprequest
```
With the Element Picker I created the following rules:
```
! 26.8.2016, 12:32:04 http://www.finanzen.net/
www.finanzen.net###sas_3650
www.finanzen.net###sas_5419_ibanner
www.finanzen.net###Ads_BA_SKY
www.finanzen.net###werbungR
www.finanzen.net###sas_5419_ibanner
www.finanzen.net###sas_5419_bannerCont
www.finanzen.net###sas_5419_i5045911
www.finanzen.net###sas_5419
www.finanzen.net###flashbuehne
```
But the ads are coming back ...

**Comment by gorhill** [comment]
Unable to reproduce -- using default settings + EasyList Germany.

**Comment by gorhill** [comment]
Ok, I saw that there were exception filters for that site:

![a](https://cloud.githubusercontent.com/assets/585534/18005731/d72b8ba0-6b69-11e6-9693-998eb6f7b393.png)

Using another blocking extension (uMatrix) probably work against these exception filters: I get the ads if I override these exception filters by dynamically blocking `smartadserver.com` and `sascdn.com`.

**Comment by gorhill** [comment]
You will have to whitelist `smartadserver.com` and `sascdn.com` in uMatrix in order for the exception filters in Easylist DEU to do their job.

**Comment by gorhill** [comment]
Actually, there is a scriptlet in _uBlock filters_ which was created for `finanzen.ch` a long time ago:

    finanzen.ch##script:contains(/^\s*function\s+UABPInject/)

I see that `finanzen.ch` is related to `finanzen.net`, and the scriptlet for `finanzen.ch` no longer works. So it's probably a matter of updating the scriptlet for `finanzen.ch`, and also injecting it into `finanzen.net`.

**Comment by curiosity-seeker** [comment]
> You will have to whitelist smartadserver.com and sascdn.com in uMatrix in order for the exception filters in Easylist DEU to do their job.

I did that and it _seems_ to work (the appearance of those ads is not always consistent) . Thank you very much! I understand that you'll probably update that scriptlet as a better solution.

BTW, very interesting discussion with the AdGuard and ABP developers. It's good to see that there is some collaboration.

**Comment by gorhill** [comment]
I committed a better fix, you no longer need to whitelist `smartadserver` and `sascdn`.

**Comment by curiosity-seeker** [comment]
I tried it and, yes, it works! gorhill, you're unbelievable :-) Thanks again!

**Comment by curiosity-seeker** [comment]
Unfortunately, the ads on finanzen.net are back:
![finanzen net](https://cloud.githubusercontent.com/assets/14075215/18474649/5ee4ab64-79c3-11e6-99a5-28719677ca6c.png)

I'm using uBlock Origin 1.9.7b1 with the same filterlists as in the first post above. All of them are updated.

**Comment by gorhill** [comment]
I don't see that ad. I do see it if I toggle off the per-site cosmetic filtering switch.

**Comment by gorhill** [comment]
For the other square ad, try `finanzen.net##[id^="sas_"]:style(height: 3px !important)`.

**Comment by curiosity-seeker** [comment]
> I don't see that ad. I do see it if I toggle off the per-site cosmetic filtering switch.

That switch is not toggled off. But now after opening that site again, I cannot see those ads at the top and the right side, either. Strange! I will report if they come back.

> For the other square ad, try finanzen.net##[id^="sas_"]:style(height: 1px !important).

Thanks a lot! That fixed it, indeed!
