### ISSUE TITLE
uBlock blocking Iugu payment gateway from authenticating captcha

### ISSUE THREAD

**Issue by RafaelLVX** [uBlockOrigin/uAssets#11000]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```https://kaptcha.iugu.com/collect/sdk?m=100042```

### Describe the issue

Iugu Payment Gateway fetches data from that kaptcha.iugu.com address I wrote above (the "m" parameter will vary from site to site). When uBlock blocks that fetch, it breaks legitimate Iugu functionality. Without that, it's impossible to use Iugu's API: our site needs to explicitly lock the user out, tell him/her to disable uBlock and refresh the page, thanks to this false positive.

To reproduce the issue, just try to fetch the content of ```https://kaptcha.iugu.com/collect/sdk?m=100042``` over GET on a browser with uBlock on and then off. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/909214/146691464-7ff4c28d-acfd-43b1-8645-67c5b3c2e4ce.png)

### uBlock Origin version

1.39.2

### Browser name and version

MS Edge 96

### Settings

I added this to "my filters" tab: 

||cdn.userleap.com/shim.js$script,domain=app.roll20.net
||www.google-analytics.com/analytics.js$script,domain=app.roll20.net

agora.folha.uol.com.br##.rs_skip.toolbar.c-tools-share--bordered-md.c-tools-share

**Comment by mapx-** [comment]
@ryanbr  this seems to be the EP filter 

`/collect/sdk?`

**Comment by ryanbr** [comment]
Looking at the original commit; https://github.com/easylist/easylist/commit/1d971f41a65f9542fe1878df32d94058d832bad4  and the same script https://kaptcha.iugu.com/collect/sdk?m=100042  https://pastebin.com/raw/dZT5ZwaJ

Allowing the script, launches 2 new network items. An empty iframe `https://ssl.kaptcha.com/logo.htm?m=171456&s=33786c11c23f43aba8e0a00e8818ce1d1`

And `https://ssl.kaptcha.com/collect/kasupport` support xml. 

I see no issues keeping this blocked.

**Comment by uBlock-user** [comment]
> Iugu Payment Gateway fetches data from

url for this payment gateway ?

**Comment by gorhill** [comment]
The suggested filters point at `app.roll20.net`, but this requires logging in.

**Comment by RafaelLVX** [comment]
> The suggested filters point at `app.roll20.net`, but this requires logging in.

For clarification, I don't think roll20 filters are related to this issue, I only listed them because they were in my test case and the issue trackers asked for all my custom settings.

**Comment by RafaelLVX** [comment]
> > Iugu Payment Gateway fetches data from
> 
> url for this payment gateway ?

www.iugu.com

**Comment by RafaelLVX** [comment]
> Looking at the original commit; [easylist/easylist@1d971f4](https://github.com/easylist/easylist/commit/1d971f41a65f9542fe1878df32d94058d832bad4) and the same script https://kaptcha.iugu.com/collect/sdk?m=100042 and simplified https://pastebin.com/raw/dZT5ZwaJ
> 
> Allowing the script, launches 2 new network items. An empty iframe `https://ssl.kaptcha.com/logo.htm?m=171456&s=33786c11c23f43aba8e0a00e8818ce1d1`
> 
> And `https://ssl.kaptcha.com/collect/kasupport` support xml.
> 
> I see no issues keeping this blocked.

Iugu apparently runs some sort of captcha upon fetching that endpoint, using that 'm' parameter as some sort of sequential token, which clears and allows use of its API. Blocking this fetch breaks the functionality of safely tokenizing credit card data inserted by an user.
