### ISSUE TITLE
washingtonpost.com: breakage

### ISSUE THREAD

**Issue by Borisgoodenough** [uBlockOrigin/uAssets#11007]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.washingtonpost.com/?reload=true`

### Category

breakage

### Describe the issue

When uBO is enabled, it sometimes blocks actual news stories, leaving spaces on the page. Screenshots show page with uBO enabled and same page with uBO disabled. This same breakage also occurs on other pages of the site, and with all content in their Travel Tips "By the Way" section; see: `https://www.washingtonpost.com/travel/tips/omicron-holiday-travel-health-experts/`

In all cases, disabling uBO restores the missing articles.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/96425682/146772491-5565a054-83cd-44bd-aee4-9ecd35a407da.png)
![image](https://user-images.githubusercontent.com/96425682/146772649-c1715e1f-19c4-4580-8e0f-4c1c13093420.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77877
  cosmetic: 40089
  scriptlet: 16336
  html: 608
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30764-31, 1d.9h.46m
    ublock-badware: 3580-1, 1d.25m
    ublock-privacy: 187-0, 1d.23h.46m
    ublock-unbreak: 1738-0, 1d.23h.44m
    easylist: 62049-559, 1d.23h.48m
    easyprivacy: 26522-484, 20h.13m
    plowe-0: 3698-3, 12d.16h.11m
    ublock-abuse: 72-0, 1d.13h.50m
    urlhaus-1: 7500-0, 28m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 76 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 710
  launchFromSelfie: true
popupPanel: 
  blocked: 11
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce. You have a lot of custom filters, have you tried without these?
