### ISSUE TITLE
anydebrid.com [Anti-Adblock]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#11004]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://anydebrid.com/`

### Describe the issue

after putting in a link and pressing the 'get link' button you get a 'please disable adblocker' page.

### uBlock Origin version

1.39.2

### Browser name and version

Chrome v96

### Settings

Default

### Notes

any link works for the site.

**Comment by dumbusernameidk** [comment]
anti-adblock again.

**Comment by stephenhawk8054** [comment]
Anti-adblock again.

Proposed filter:

`||adserver.juicyads.com/js/fib.js$script,redirect-rule=noopjs,domain=anydebrid.com`

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by JobcenterTycoon** [comment]
Anti adb is back

**Comment by dumbusernameidk** [comment]
anti-adblock is back

**Comment by JobcenterTycoon** [comment]
@Yuki2718 maybe its a case for the quick list

**Comment by dumbusernameidk** [comment]
anti-adblock again.

**Comment by JobcenterTycoon** [comment]
Works fine for me with updated filter lists

**Comment by okiehsch** [comment]
Can't reproduce.

**Comment by dumbusernameidk** [comment]
clear cookies/cache try again. 

`https://i.gyazo.com/cfcc1b2d28e586f7ab9e75ec0945691c.png`  logger
`https://i.gyazo.com/b50635b3700cc9499316a25179f53a0f.png` anti-adblock

**Comment by MasterKia** [comment]
I can't reproduce on Firefox.
Make sure you enable the quick fixes list and update it.

**Comment by JobcenterTycoon** [comment]
@Yuki2718 `||googleads.g.doubleclick.net/pagead/ads$frame,removeparam=/^(?:correlator|f[cr-w]|p[e-sv]|[abdeg-or-x])/` triggers the anti adblock on `hotdebrid.com`  and `hotdebrid.com` (tested on Firefox)

For me `anydebrid.com,hotdebrid.com##+js(set, abSkip, true)` is enough to get past the check without whitelisting the iFrame.

Im wondering how websites can check what is inside the iFrame. As far i know iFrames are a blackbox for security reasons

**Comment by JobcenterTycoon** [comment]
@MasterKia to repdroduce you need to enter a valid Link (i tested with `https://dgdrive.xyz/pzqfgs6egklj`)

**Comment by MasterKia** [comment]
Oh ok, the OP said "any link works for the site." so I entered random links.
