### ISSUE TITLE
bloomberg.com: breakage

### ISSUE THREAD

**Issue by darchon7** [uBlockOrigin/uAssets#11006]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.bloomberg.com/live/us?sref=gjdFocFO`

### Category

breakage

### Describe the issue

tv feed isn't showing. only see a blank screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 95
filterset (summary): 
  network: 78796
  cosmetic: 40048
  scriptlet: 16391
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62054-8, 3h.14m
    easyprivacy: 26530-17, 3h.12m
    plowe-0: 3687-809, 9d.1h.20m
    ublock-abuse: 81-0, 3h.10m
    ublock-badware: 3539-61, 3h.8m
    ublock-filters: 30200-133, 3h.6m
    ublock-privacy: 191-11, 3h.4m
    ublock-unbreak: 1729-39, 3h.2m
    urlhaus-1: 8445-0, 3h
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 660
  launchFromSelfie: true
popupPanel: 
  blocked: 278
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce with default settings/lists and no custom filters. You will have to investigate on your side whether something else than uBO is causing your issue, and whether your custom filter is causing the issue.

**Comment by darchon7** [comment]
strange the issue seemed to have gone away today.
