### ISSUE TITLE
plotaroute.com: breakage

### ISSUE THREAD

**Issue by Tighbu** [uBlockOrigin/uAssets#11003]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.plotaroute.com/map/1770232`

### Category

breakage

### Describe the issue

When in Editing mode of plotting a route on plotaroute.com, the 'Share' button does not pop up the link-sharing window if the adblocker is enabled.
Also there is a bar on the right of the screen that is labelled 'Advertisment' but is otherwise blank

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Plotaroute adblock errors](https://user-images.githubusercontent.com/2057912/146696222-8292c957-599b-424e-b42f-340bd56a9a53.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77842
  cosmetic: 39857
  scriptlet: 16214
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30413-29, 2d.23h.14m
    ublock-badware: 3573-1, 2d.23h.16m
    ublock-privacy: 184-0, 2d.23h.25m
    ublock-abuse: 81-0, 11h.54m
    ublock-unbreak: 1734-0, 2d.23h.19m
    easylist: 62004-558, 2d.23h.21m
    easyprivacy: 26502-476, 2d.23h.23m
    plowe-0: 3698-3, 10d.19h.7m
    urlhaus-1: 7540-0, 11h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 915
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
add & test (first 2 filters for right side stuff)

```
plotaroute.com###RightPanelAds
plotaroute.com###AdPanelRight
@@||addthis.com/js/*/addthis_widget.js$script,domain=plotaroute.com
||addthis.com^$important,3p,domain=~amd.com|~missingkids.com|~missingkids.org|~sainsburys.jobs|~schonmagazine.com|~sitecore.com,badfilter
||addthis.com^$important,3p,domain=~amd.com|~missingkids.com|~missingkids.org|~sainsburys.jobs|~schonmagazine.com|~sitecore.com|~plotaroute.com
```

**Comment by Tighbu** [comment]
Thanks. 
The 'Share' button seems to work fine now. The ad panel on the right hand side is still there but is blank white now. Maybe it's just not possible to collapse that and make the map fill the whole screen.

**Comment by mapx-** [comment]
test again

**Comment by Tighbu** [comment]
Works! The ad panel is gone and the map now fills the screen. Thanks!
