### ISSUE TITLE
express.co.uk: nuisance

### ISSUE THREAD

**Issue by Jimbo-Jim** [uBlockOrigin/uAssets#11001]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.express.co.uk/life-style/science-technology/1532380/Virgin-Media-upgrade-gig1-BT-Sky-broadband`

### Category

nuisance

### Describe the issue

Cookie banner covers bottom third of screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77661
  cosmetic: 40044
  scriptlet: 16354
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30765-31, 6m
    ublock-badware: 3580-1, 6m
    ublock-privacy: 188-0, 6m
    ublock-abuse: 81-0, 6m
    ublock-unbreak: 1740-0, 6m
    easylist: 62051-560, 5m
    easyprivacy: 26528-480, 5m
    urlhaus-1: 7248-0, 5m
    plowe-0: 3709-3, 5m
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 507
  launchFromSelfie: false
popupPanel: 
  blocked: 26
```
</details>

**Comment by gorhill** [comment]
Did you try with Easylist Cookie?

**Comment by mapx-** [comment]
fixed by Fanboy’s Annoyance
