### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by devrob20** [uBlockOrigin/uAssets#11009]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.investing.com/`

### Category

detection

### Describe the issue

body overflow needs to be set to visible or scrollbars dont show

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77951
  cosmetic: 40052
  scriptlet: 16394
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62054-8, 2h.23m
    easyprivacy: 26531-17, 2h.23m
    plowe-0: 3709-815, 2h.23m
    ublock-abuse: 81-0, 2h.23m
    ublock-badware: 3611-61, 2h.23m
    ublock-filters: 30207-133, 2h.23m
    ublock-privacy: 192-2, 2h.23m
    ublock-unbreak: 1729-39, 2h.23m
    urlhaus-1: 7500-0, 2h.23m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 709
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by gorhill** [comment]
How does this detection look like? Provide screenshots. What steps are needed to reproduce it?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/146780654-2cf91517-6b61-4b19-ac28-80db7373c202.png)
