### ISSUE TITLE
newspaper CRhoy.com videos again

### ISSUE THREAD

**Issue by milotic** [uBlockOrigin/uAssets#11013]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.crhoy.com/nacionales/video-asaltan-a-13-personas-en-almacen-y-los-detienen-tras-causar-choque-en-heredia/`

### Describe the issue

hi again the main newspaper of our country, bricked the videos if ublock is ON
turning off ublock, play the video load first a video ads to show the real video

24 days ago was fixed: https://github.com/uBlockOrigin/uAssets/issues/10618

### uBlock Origin version

1.39.2

### Browser name and version

firefox 95

### Settings

none

**Comment by gorhill** [comment]
Video plays fine after waiting a few seconds, so unable to reproduce.

**Comment by milotic** [comment]
![Captura de pantalla 2021-12-20 153727](https://user-images.githubusercontent.com/1099848/146836000-395b4940-3f96-48fe-942d-10f37a7dfc30.png)
this show with ublock UP
