### ISSUE TITLE
movieku, melongmovie

### ISSUE THREAD

**Issue by Slasar41** [uBlockOrigin/uAssets#11019]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://107.152.39.187/`
`http://167.99.31.48/`

### Describe the issue

Antiadblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/28888646/146892056-50d7752e-5d49-45f8-a9db-9ecbb0b6d5d8.png)
![image](https://user-images.githubusercontent.com/28888646/146892067-f57ba8fb-af4e-42f1-99fe-aa6972b5262f.png)

### uBlock Origin version

1.39.2

### Browser name and version

Microsoft Edge 96.0.1054.62

### Settings

Default

**Comment by uBlock-user** [comment]
> Microsoft Edge 96.0.1054.62

Disable edge's built-in blocker and try again.

**Comment by Slasar41** [comment]
For some reason there's no disable adblock page anymore even though uBlock is still active and Edge's protection turn on/off.

**Comment by Slasar41** [comment]
Wait, it has come back even with Edge's protection turn off. You need to select a movie first.
Example: `https://107.152.39.187/series/monsters-at-work-2021/`
![image](https://user-images.githubusercontent.com/28888646/146898481-75239f69-d58b-4b76-965a-bcef1ce74ec8.png)

**Comment by uBlock-user** [comment]
force update ublock filters list

**Comment by Slasar41** [comment]
Still the same, I just did clear all cache and update now.

**Comment by uBlock-user** [comment]
Need to keep Edge's blocker off btw.

**Comment by Slasar41** [comment]
Looks like the issue only happen on InPrivate tab.
Thanks.
