### ISSUE TITLE
kedronparkhotel.com.au: breakage

### ISSUE THREAD

**Issue by callmejon** [uBlockOrigin/uAssets#11014]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.kedronparkhotel.com.au/menus`

### Category

breakage

### Describe the issue

the menu PDF does not show when ublock enabled. disable ublock will list the menu pdf.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 126587
  cosmetic: 85074
  scriptlet: 27686
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 10d.9h.44m
    CHN-0: 26936-86, 2d.12h.20m
    adguard-generic: 62159-696, 2d.12h.28m
    adguard-mobile: 7011-66, 2d.12h.26m
    adguard-spyware: 24613-573, 2d.12h.24m
  default: 
    easylist: 62045-1340, 2d.12h.18m
    easyprivacy: 26530-10632, 15h.53m
    plowe-0: 3687-964, 7d.12h.8m
    ublock-abuse: 81-0, 2d.12h.34m
    ublock-badware: 3509-180, 2d.12h.32m
    ublock-filters: 30192-2939, 2d.12h.22m
    ublock-privacy: 188-25, 2d.12h.30m
    ublock-unbreak: 1727-106, 2d.12h.36m
    urlhaus-1: 7938-0, 21m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    chrome-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1800
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=kedronparkhotel.com.au`

**Comment by mapx-** [comment]
@ryanbr
