### ISSUE TITLE
stream.directv.com: breakage

### ISSUE THREAD

**Issue by burtpolson** [uBlockOrigin/uAssets#11027]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://stream.directv.com/watchnow`

### Category

breakage

### Describe the issue

The video will not load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 79408
  cosmetic: 40036
  scriptlet: 16359
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30640-31, 15h.38m
    ublock-badware: 3620-1, 15h.36m
    ublock-privacy: 185-0, 15h.34m
    ublock-abuse: 81-0, 15h.32m
    ublock-unbreak: 1740-0, 15h.29m
    easylist: 62118-564, 15h.27m
    easyprivacy: 26539-486, 15h.25m
    urlhaus-1: 9011-0, 15h.23m
    plowe-0: 3710-3, 15h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1078
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
Open the logger, go to some stream just to catch the issue, select in the logger only the blocked items, post here the screenshots with those elements

**Comment by burtpolson** [comment]
I was able to get the stream to work. I had changed to Firefox browser and
did not realize it was blocking. Thank you and sorry for your troubles.

Burt
