### ISSUE TITLE
championat.com: breakage

### ISSUE THREAD

**Issue by rust173** [uBlockOrigin/uAssets#11020]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.championat.com/auto/`

### Category

breakage

### Describe the issue

page formatting gets lost

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 95889
  cosmetic: 60839
  scriptlet: 17920
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40450-9, 21h.27m
    easylist: 62054-24, 21h.27m
    easyprivacy: 26531-114, 21h.27m
    plowe-0: 3709-820, 21h.27m
    ublock-abuse: 81-1, 21h.27m
    ublock-badware: 3611-61, 21h.27m
    ublock-filters: 30207-165, 21h.27m
    ublock-privacy: 192-2, 21h.27m
    ublock-unbreak: 1729-39, 21h.27m
    urlhaus-1: 7500-0, 21h.27m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1377
  launchFromSelfie: true
popupPanel: 
  blocked: 18
```
</details>

**Comment by dimisa-RUAdList** [comment]
Perhaps the breakdowns are associated with some kind of user rules. I don't see any breakdowns there, only unblocked ads. This is one of the domains "Rambler Group" and to block ads you need to connect the filter Counters: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links
