### ISSUE TITLE
getrevue.co: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#11025]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.getrevue.co/profile/richardbarrow/issues/full-details-about-suspension-of-test-and-go-947139?via=twitter-card-webview&client=DesktopWeb&element=issue-card`

### Category

nuisance

### Describe the issue

Has a popup at the bottom when scrolling down on the site asking you to sign up to the newsletter. If manually trying to block this window it break the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 131654
  cosmetic: 149899
  scriptlet: 32338
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1566-0, 1d.2h.32m
    https://www.i-dont-care-about-cookies.eu/abp/: 24123-5, 1d.14h.38m
    adguard-generic: 62159-4516, 2d.18h.59m
    adguard-spyware: 24612-708, 3d.15h.3m
    adguard-spyware-url: 402-68, 3d.15h.3m
    block-lan: 44-0, 8d.21h.7m
    adguard-annoyance: 48528-2890, 2d.14h.49m
    adguard-social: 15067-14, 2d.14h.51m
    ublock-annoyances: 4337-5, 2d.14h.53m
    NOR-0: 2619-4, 13h.52m
    curben-phishing: 13303-4, 1h.46m
    curben-pup: 388-0, 1h.48m
  default: 
    ublock-filters: 30409-39, 2d.19h.9m
    ublock-badware: 3573-1, 2d.19h.7m
    ublock-privacy: 184-0, 2d.19h.5m
    ublock-abuse: 72-0, 2d.19h.3m
    ublock-unbreak: 1738-0, 2d.19h.1m
    easylist: 62060-592, 2d.18h.57m
    easyprivacy: 26508-10873, 2d.18h.55m
    urlhaus-1: 9011-4, 13h.55m
    plowe-0: 3687-3, 9d.9h.16m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 970
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
use `Fanboy’s Annoyance` list
