### ISSUE TITLE
animetake27.stream: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11037]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://animetake27.stream/view/6813564959/`

### Category

ads

### Describe the issue

Ads placeholders due to `ghide`.

Proposed filter:

`animetake27.*##.gads`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/147091791-fc8a33f1-7c1d-4b51-bf97-7d0cfe5594bf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78345
  cosmetic: 40053
  scriptlet: 16375
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30668-30, 1h.57m
    ublock-badware: 3620-1, 1h.57m
    ublock-privacy: 188-0, 1h.57m
    ublock-abuse: 81-0, 1h.57m
    ublock-unbreak: 1738-0, 1h.57m
    easylist: 62146-564, 2h.52m
    easyprivacy: 26545-483, 2h.52m
    urlhaus-1: 7907-0, 1h.57m
    plowe-0: 3717-3, 1h.57m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 654
  launchFromSelfie: false
popupPanel: 
  blocked: 13
```
</details>

**Comment by Yuki2718** [comment]
Probably these exception are no more needed, but I can't access the site.
