### ISSUE TITLE
dagelijksekost.een.be: breakage

### ISSUE THREAD

**Issue by zeveroare** [uBlockOrigin/uAssets#11039]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://dagelijksekost.een.be/gerechten/risotto-van-gerst-met-asperges-venkel-en-gerookte-zalm`

### Category

breakage

### Describe the issue

The video can't be played, there is no play button. Works when I disable ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78254
  cosmetic: 40064
  scriptlet: 16337
  html: 608
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.6h.31m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30756-30, 3d.18h.28m
    ublock-badware: 3575-1, 3d.18h.26m
    ublock-privacy: 184-0, 3d.18h.23m
    ublock-abuse: 81-0, 3d.18h.21m
    ublock-unbreak: 1716-0, 3d.18h.19m
    easylist: 62060-559, 3d.18h.17m
    easyprivacy: 26508-476, 3d.18h.30m
    plowe-0: 3690-3, 6d.23h.25m
    urlhaus-1: 7908-0, 2m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 383
  launchFromSelfie: true
popupPanel: 
  blocked: 19
```
</details>

**Comment by gorhill** [comment]
I don't see a video at the link you provided, neither when I disable uBO.

**Comment by zeveroare** [comment]
When you scroll down, the picture should switch to one with a play button,
top right. That's the video.
It shows up for me when I disable ublock. Also when I use chrome, where I
don't have ublock installed.

**Comment by gorhill** [comment]
I can't see any video, with or without uBO, on either Firefox or Chromium. Please provide a screenshot.

**Comment by mapx-** [comment]
I can reproduce the issue.

@zeveroare , test these filters:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=dagelijksekost.een.be
@@||shared.mediahuis.be/ka-ching/prebid.js$script,domain=dagelijksekost.een.be
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=dagelijksekost.een.be
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=dagelijksekost.een.be
@@||assets.adobedtm.com/*-source.min.js$script,domain=dagelijksekost.een.be
```

@ryanbr

**Comment by zeveroare** [comment]
I will try the filters. Let me add some screenshots first. (I'm guessing it is geoblocked
![ublock enabled](https://user-images.githubusercontent.com/15368257/147136807-e3a57002-aaf6-4ee8-96fb-58a270466266.png)
![ublock disabled](https://user-images.githubusercontent.com/15368257/147136854-cc99d0bb-1a24-447f-967c-35fb38b9e7e7.png)
)

**Comment by zeveroare** [comment]
> I can reproduce the issue.
> 
> @zeveroare , test these filters:
> 
> ```
> @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=dagelijksekost.een.be
> @@||shared.mediahuis.be/ka-ching/prebid.js$script,domain=dagelijksekost.een.be
> @@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=dagelijksekost.een.be
> @@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=dagelijksekost.een.be
> @@||assets.adobedtm.com/*-source.min.js$script,domain=dagelijksekost.een.be
> ```
> 
> @ryanbr

Perfect, these work. Thanks!
