### ISSUE TITLE
zoominfo.com: breakage

### ISSUE THREAD

**Issue by alexolog** [uBlockOrigin/uAssets#11031]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

for example
`https://www.zoominfo.com/p/Sergey-Brin/3133965445`

### Category

breakage

### Describe the issue

When trying to access a zoominfo link that points to a specific profile (for example I used `https://www.zoominfo.com/p/Sergey-Brin/3133965445`), the page flashes briefly and then the browser shows an empty page with the url changes to `https://www.zoominfo.com/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/2112513/147015006-32bfbf8d-b70a-41ac-9220-08423c27be70.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 96
filterset (summary): 
  network: 77683
  cosmetic: 39189
  scriptlet: 16117
  html: 598
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30283-28, never
    ublock-badware: 3494-1, never
    ublock-privacy: 183-0, never
    ublock-abuse: 74-0, never
    ublock-unbreak: 1707-0, never
    easylist: 60746-530, never
    easyprivacy: 25518-212, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 911
  launchFromSelfie: false
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||collector-pxosx7m0dx.px-client.net/b/g$xhr,domain=zoominfo.com
@@||zoominfo.com/p/amplitude-js.$script,1p
```

EP issue @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c8ecd2ad9821950bed2d8dbc58a88af387311a22 all is needed
