### ISSUE TITLE
[NSFW] thelittleslush.com

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#11047]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://thelittleslush.com/hottest-pornstars-right-now/`

### Describe the issue

Pop-up appear when I open the link.

### uBlock Origin version

1.39.2

### Browser name and version

FIrefox 95

### Settings

Default settings

**Comment by mapx-** [comment]
add

`thelittleslush.com##.snppopup`

@ryanbr
