### ISSUE TITLE
rus-ege.sdamgia.ru/problem?id=242: breakage

### ISSUE THREAD

**Issue by Anonymous87549236** [uBlockOrigin/uAssets#11046]
### Prerequisites

- [ ] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://rus-ege.sdamgia.ru/problem?id=242`

### Category

breakage

### Describe the issue

If combined with
https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb
https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom
and https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg
this happens ...
Should be ...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/70477515/147259196-454d414c-9ed2-47c4-b6cb-3ee179dd18ed.png)
![image](https://user-images.githubusercontent.com/70477515/147259315-ddab6a92-2727-4da7-b83d-49400c64fbbd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 96177
  cosmetic: 60910
  scriptlet: 17933
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40524-9, 1h.55m
    easylist: 62201-24, 2h.44m
    easyprivacy: 26545-114, 2h.42m
    plowe-0: 3690-816, 6d.10h.50m
    ublock-abuse: 72-1, 2h.5m
    ublock-badware: 3629-65, 2h.3m
    ublock-filters: 30112-169, 2h.1m
    ublock-privacy: 191-11, 1h.59m
    ublock-unbreak: 1704-39, 1h.57m
    urlhaus-1: 7784-0, 1h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 228
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
Use only uBO + default lists + specific RuAdlist other lists
