### ISSUE TITLE
en.ff14angler.com: breakage

### ISSUE THREAD

**Issue by MattMellies** [uBlockOrigin/uAssets#11040]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://en.ff14angler.com/fish/446`

### Category

breakage

### Describe the issue

They disable most elements when using ad blockers, as mentioned in their footer text "When ad blocking, only mobile version with limited version is available."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With Adblock:
![image](https://user-images.githubusercontent.com/17054372/147129540-f21199c0-de73-4168-b3ae-2d8d755b1f2a.png)

Without:
![image](https://user-images.githubusercontent.com/17054372/147129615-2b5ee7ec-4a13-431c-9222-bba1aa490e75.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78013
  cosmetic: 40063
  scriptlet: 16391
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62080-8, 1d.19h.46m
    easyprivacy: 26531-17, 1d.19h.44m
    plowe-0: 3687-809, 9d.19h.24m
    ublock-abuse: 81-0, 1d.15h.36m
    ublock-badware: 3611-61, 1d.19h.48m
    ublock-filters: 30200-135, 2d.7h.52m
    ublock-privacy: 192-2, 1d.19h.42m
    ublock-unbreak: 1704-39, 1d.19h.40m
    urlhaus-1: 7576-0, 19h.34m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 383
  launchFromSelfie: true
popupPanel: 
  blocked: 150
```
</details>

**Comment by mapx-** [comment]
chrome => even disabling uBO the page is not loaded correctly
FF => ok

**Comment by krystian3w** [comment]
So webmaster bug, no PaleMoon/Basilisk so ony fans can repair in custom list or user script.

**Comment by Yuki2718** [comment]
> chrome => even disabling uBO the page is not loaded correctly FF => ok

Same
