### ISSUE TITLE
mackungfu.org [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1104]
URL(s) where the issue occurs

http://www.mackungfu.org/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by garry-ut99** [comment]
(no AA for me with `ghide` off) Ad placeholders caused by `ghide` from "uBlock filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217939312-9bce17b4-a404-486b-8c02-1e0a46464e63.png)
