### ISSUE TITLE
Chinese `bilibili` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#11051]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bilibili.com/video/BV1R34y1R7ps/`

### Describe the issue
`
https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440`

You can check the streaming viewer numbers for the same video at this URL:
`https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440`

`https://api.bilibili.com/x/player/online/total?aid={video's aid ID}&cid={video's cid ID}&bvid={video's bvid ID}&ts={what part of the video you are watching at the moment}`

It will automatically refresh every few seconds, and no `Cookie` is needed to get the content, so...~

```
||api.bilibili.com/x/player/online/total$removeparam=ts
||api.bilibili.com/x/player/online/total$cookie
```

### uBlock Origin version

n/a

### Browser name and version

n/a

### Settings

n/a

**Comment by c2xusnpq6** [comment]
One more, https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://upos-hz-mirrorakam.akamaized.net/upgcxcode/76/95/452019576/452019576-1-30080.m4s?hdnts=exp=1640301325~hmac=502507765248beb5fa12c923763fc9a1643307b6a6b24de274d8f6a8cffbe956&mid=1108298144&bvc=vod&orderid=0,1&agrr=0&bw=328804&logo=80000000

```
||akamaized.$removeparam=uparams
||akamaized.$removeparam=upsig
||akamaized.$removeparam=platform
||akamaized.$removeparam=trid
||akamaized.$removeparam=oi
||akamaized.$removeparam=os
||akamaized.$removeparam=gen
||akamaized.$removeparam=deadline
||akamaized.$removeparam=nbs
||akamaized.$removeparam=uipk
||akamaized.$removeparam=e

or

upgcxcode$removeparam=uparams
upgcxcode$removeparam=upsig
upgcxcode$removeparam=platform
upgcxcode$removeparam=trid
upgcxcode$removeparam=oi
upgcxcode$removeparam=os
upgcxcode$removeparam=gen
upgcxcode$removeparam=deadline
upgcxcode$removeparam=nbs
upgcxcode$removeparam=uipk
upgcxcode$removeparam=e
```

**Comment by krystian3w** [comment]
block `$cookie` when was added to uBo?

**Comment by c2xusnpq6** [comment]
> block `$cookie` when was added to uBo?

So what should I do?...🤔

**Comment by krystian3w** [comment]
May need block in Firefox premissions of page:

https://support.mozilla.org/en-US/kb/firefox-page-info-window#w_set-cookies

but can break whole `api.bilibili.com`.

Chrome may need use addon like Edit This Cookie https://chrome.google.com/webstore/detail/edit-this-cookie/fngmhnnpilhplaeedifhccceomclgfbg if names are stable.

**Comment by c2xusnpq6** [comment]
> May need block in Firefox premissions of page:
> 
> https://support.mozilla.org/en-US/kb/firefox-page-info-window#w_set-cookies
> 
> but can break whole `api.bilibili.com`.
> 
> Chrome may need use addon like Edit This Cookie https://chrome.google.com/webstore/detail/edit-this-cookie/fngmhnnpilhplaeedifhccceomclgfbg if names are stable.

I mean.. via uBlock, not another blocker or extension...

**Comment by krystian3w** [comment]
I suppose no possible persuade uBo Volunteers to implement `$cookie` if this scriplet works too late:

https://github.com/gorhill/uBlock/wiki/Resources-Library#cookie-removerjs-

**Comment by shenzhiming88** [comment]
@iam-py-test

**Comment by shenzhiming88** [comment]
In fact, I've added some filters for `Bilibili` to the `Actual Legitimate URL Shortener Tool` list that may be helpful in preventing tracking.
```
! https://github.com/uBlockOrigin/uAssets/pull/10010
||bilibili.com^$removeparam=/^current/
||bilibili.com^$removeparam=/^from/
||bilibili.com^$removeparam=/^network/
||bilibili.com^$removeparam=/^playurl/
||bilibili.com^$removeparam=/^share_/
||bilibili.com^$removeparam=accept_quality
||bilibili.com^$removeparam=bbid
||bilibili.com^$removeparam=broadcast_type
||bilibili.com^$removeparam=bsource
||bilibili.com^$removeparam=hotRank
||bilibili.com^$removeparam=p2p_type
||bilibili.com^$removeparam=platform_network_status
||bilibili.com^$removeparam=quality_description
||bilibili.com^$removeparam=referfrom
||bilibili.com^$removeparam=seid
||bilibili.com^$removeparam=spm_id_from
||bilibili.com^$removeparam=tdsourcetag
||bilibili.com^$removeparam=timestamp
||bilibili.com^$removeparam=unique_k
! https://manga.bilibili.com/detail/mc25717?refer_from=bili_main_nav
||bilibili.com^$removeparam=refer_from
! https://show.bilibili.com/platform/home.html?msource=pc_web
||bilibili.com^$removeparam=msource
! https://github.com/DandelionSprout/adfilt/pull/355
! https://github.com/the1812/Bilibili-Evolved/issues/974
||bilibili.com/bangumi$removeparam=theme
! https://github.com/DandelionSprout/adfilt/pull/354
! https://github.com/the1812/Bilibili-Evolved/issues/913
||bilibili.com/audio/au*?$removeparam=type
||bilibili.com/audio/mycollection?$removeparam=type
! https://github.com/DandelionSprout/adfilt/pull/353
! https://github.com/the1812/Bilibili-Evolved/issues/1574
^p=1^$removeparam=p,domain=bilibili.com
^t=0^$removeparam=t,domain=bilibili.com
```

**Comment by iam-py-test** [comment]
@c2xusnpq6 try using https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt
@shenzhiming88 Sorry I didn't respond earlier. I was out walking and planned on fixing it after I returned, but you beat me too it. Thanks

**Comment by shenzhiming88** [comment]
@c2xusnpq6 These filters cause the video to not play - https://github.com/DandelionSprout/adfilt/pull/430
![image](https://user-images.githubusercontent.com/66902050/147398417-9c158be7-1de8-4372-8def-28f40f821c45.png)

**Comment by krystian3w** [comment]
So closed as not stock troubles. Pulls goes only to thrid party project instead file `privacy.txt`.
