### ISSUE TITLE
Unblock has stopped working

### ISSUE THREAD

**Issue by zabobay** [uBlockOrigin/uAssets#11056]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.tabsbook.ru/express-panel/`

### Describe the issue

Unblock has stopped working. Previously, it required one entry, its own filter, to remove one window with ads on this site. Then three. Now even ten doesn't help.

### Screenshot(s)

![Screenshot_20211224_194518](https://user-images.githubusercontent.com/48959454/147365335-cac1e933-fdb9-4004-aae8-670379479b07.png)
![Screenshot_20211224_194932](https://user-images.githubusercontent.com/48959454/147365480-dd211c9b-a938-4cce-9d36-d8ad58742f3b.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 94
filterset (summary): 
  network: 96243
  cosmetic: 36473
  scriptlet: 17948
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40528-828, 15m
    easylist: 62236-23449, 15m
    easyprivacy: 26545-114, 15m
    plowe-0: 3715-823, 15m
    ublock-abuse: 81-1, 15m
    ublock-badware: 3629-65, 15m
    ublock-filters: 30124-385, 15m
    ublock-privacy: 192-3, 15m
    ublock-unbreak: 1735-39, 15m
    urlhaus-1: 7769-0, 15m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 12567
  launchFromSelfie: false
```
</details>

**Comment by dimisa-RUAdList** [comment]
Your screenshot has no ads. What exactly are you trying to block?

**Comment by gwarser** [comment]
@zabobay try Ctrl+F5 the image is loaded from cache.

**Comment by gorhill** [comment]
Something missing in the troubleshooting information is whether _"My filters"_ is disabled as a list -- this could also be the explanation.

**Comment by iam-py-test** [comment]
Why is _Filterlist (user)_ say 2 but the screenshot clearly shows more than two filters? Am I missing something?
Besides, I don't see anything like that which is shown in the OP's screenshot, with or without uBo:
![image](https://user-images.githubusercontent.com/84232764/147392670-e5703bae-faaf-4912-8e3d-08987dba0b5d.png)
Just a paywall...

**Comment by gwarser** [comment]
http://www.tabsbook.ru/fstorage/backgrounds/12/82/7/1282718eb5b530bca82deae43e1b8a3f_1820_1024.jpg ?
