### ISSUE TITLE
app.cryptotrader.tax: breakage

### ISSUE THREAD

**Issue by Herohtar** [uBlockOrigin/uAssets#11052]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://app.cryptotrader.tax/`

### Category

breakage

### Describe the issue

Live Chat support widget ([Intercom](https://www.intercom.com/)) is blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78103
  cosmetic: 39860
  scriptlet: 16207
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30409-30, 3d.17h.50m
    ublock-badware: 3543-1, 3d.17h.48m
    ublock-privacy: 188-0, 3d.17h.46m
    ublock-abuse: 72-0, 3d.17h.44m
    ublock-unbreak: 1715-0, 3d.17h.42m
    easylist: 62054-559, 3d.17h.40m
    easyprivacy: 26530-476, 3d.17h.38m
    urlhaus-1: 7784-0, 5h.57m
    plowe-0: 3691-3, 4d.22h.5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 347
  launchFromSelfie: true
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
add & test

```
@@||cdn.segment.com/next-integrations/integrations/intercom/*/intercom.dynamic.js.gz$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/analytics.js/v1/*/analytics.min.js$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/v1/projects/*/settings$xhr,domain=app.cryptotrader.tax
@@||cdn.segment.com/analytics-next/bundles/$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/next-integrations/integrations/mixpanel/*/mixpanel.dynamic.js.gz$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/next-integrations/integrations/vendor/commons.$script,domain=app.cryptotrader.tax
```

**Comment by ryanbr** [comment]
From some existing fixes in easyprivacy_allowlist.txt and modified for this domain,

```
@@||cdn.segment.com/analytics-next/$domain=app.cryptotrader.tax
@@||cdn.segment.com/analytics.js/$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/v1/projects/$domain=app.cryptotrader.tax
```

**Comment by mapx-** [comment]
other 2 filters are necessary:

```
@@||cdn.segment.com/analytics-next/$domain=app.cryptotrader.tax
@@||cdn.segment.com/analytics.js/$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/v1/projects/$domain=app.cryptotrader.tax
@@||cdn.segment.com/next-integrations/integrations/vendor/commons.$script,domain=app.cryptotrader.tax
@@||cdn.segment.com/next-integrations/integrations/intercom/*/intercom.dynamic.js.gz$script,domain=app.cryptotrader.tax
```
