### ISSUE TITLE
news.tvb.com: breakage

### ISSUE THREAD

**Issue by galenyip** [uBlockOrigin/uAssets#11053]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://news.tvb.com/live/inews`

### Category

breakage

### Describe the issue

The page will not work properly when uBO is enabled, e.g. the video player on the page is not working.

### Screenshot(s)

the video player on the page is not working.
<details>

<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/12710987/147343125-e402fa89-b433-4fdf-aee4-d315531a52df.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77388
  cosmetic: 40039
  scriptlet: 16351
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30639-30, 2d.19h.36m
    ublock-badware: 3513-1, 2d.16h.51m
    ublock-privacy: 188-0, 2d.19h.34m
    ublock-abuse: 72-0, 2d.19h.32m
    ublock-unbreak: 1734-0, 2d.19h.30m
    easylist: 62126-563, 2d.19h.28m
    easyprivacy: 26542-480, 2d.19h.26m
    urlhaus-1: 7087-0, 20h.42m
    plowe-0: 3710-3, 2d.16h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 792
  launchFromSelfie: false
popupPanel: 
  blocked: 13
```
</details>

**Comment by mapx-** [comment]
add

`@@||tvb.com^$css,xhr,script,1p`

@Yuki2718  could you fix it in AG CHN list ?

**Comment by Yuki2718** [comment]
@mapx- It seems already fixed.

**Comment by Yuki2718** [comment]
@galenyip Enable AdGuard Chinese filters under Regions, languages.
