### ISSUE TITLE
investor.postimees.ee: breakage

### ISSUE THREAD

**Issue by misantroop** [uBlockOrigin/uAssets#11063]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://investor.postimees.ee/7415127/rimi-omanik-plaanib-borsilt-lahkuda`

### Category

breakage

### Describe the issue

When cosmetic filtering is enabled, scrolling does not work. Using this with Bypass Paywalls but enabling, disabling it has no effect. With Bypass Paywalls is enabled and uBlock without cosmetic filtering enabled, site works as expected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78748
  cosmetic: 39942
  scriptlet: 16216
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30409-30, 3d.5h.7m
    ublock-badware: 3620-1, 3d.5h.11m
    ublock-privacy: 187-0, 2d.13h.13m
    ublock-abuse: 81-0, 2d.13h.17m
    ublock-unbreak: 1738-0, 2d.13h.15m
    easylist: 62194-564, 2d.13h.19m
    easyprivacy: 26545-489, 3d.5h.9m
    plowe-0: 3710-3, 3d.19h.6m
    urlhaus-1: 8214-0, 1h.51m
filterset (user): [array of 44 redacted]
trustedset: 
  added: [array of 53 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1806
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by uBlock-user** [comment]
Test on default lists/settings in uBO.

**Comment by mapx-** [comment]
add

`postimees.ee#@#.ad01`

@ryanbr
