### ISSUE TITLE
mail.ukr.net: nuisance

### ISSUE THREAD

**Issue by passsssha** [uBlockOrigin/uAssets#11064]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://mail.ukr.net/desktop`

### Category

nuisance

### Describe the issue

1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 96285
  cosmetic: 60911
  scriptlet: 17906
  html: 610
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30602-29, 2d.16h.26m
    ublock-badware: 3633-1, 23h.54m
    ublock-privacy: 180-0, 23h.53m
    ublock-abuse: 81-0, 23h.52m
    ublock-unbreak: 1689-0, 23h.51m
    easylist: 62182-579, 2d.16h.30m
    easyprivacy: 26545-29, 2d.16h.28m
    urlhaus-1: 7994-0, 21h.29m
    plowe-0: 3688-450, 10d.22h.9m
    RUS-0: 40527-144, 1d.21h.51m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2725 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by dimisa-RUAdList** [comment]
There is a [CSP-bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) in the Firefox browser, due to which some rules may not work. To solve this problem need [Scriptlet-doctor](https://github.com/JustOff/scriptlet-doctor/releases) (for FF95: scriptlet-doctor-quantum).

It is also advisable to subscribe to [Counters](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
