### ISSUE TITLE
hotstar.com: breakage

### ISSUE THREAD

**Issue by Thilak-Rox** [uBlockOrigin/uAssets#11061]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.hotstar.com/in/tv/bigg-boss/14455/day-82-in-the-house/1260076768`

### Category

breakage

### Describe the issue

never had this issue but now it doesnt play while ublock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78480
  cosmetic: 40096
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62236-8, 21h.58m
    easyprivacy: 26545-17, 21h.56m
    plowe-0: 3717-818, 21h.54m
    ublock-abuse: 81-0, 21h.50m
    ublock-badware: 3629-65, 21h.46m
    ublock-filters: 30119-137, 21h.40m
    ublock-privacy: 192-2, 21h.38m
    ublock-unbreak: 1704-39, 21h.36m
    urlhaus-1: 7994-0, 21h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 745
  launchFromSelfie: true
popupPanel: 
  blocked: 171
```
</details>

**Comment by mapx-** [comment]
test

`@@||secure-media.hotstarext.com/web-messages/core/*.json$xhr,domain=hotstar.com`
