### ISSUE TITLE
Myabandonware now has ads' spaces

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#11062]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The ads' spaces in the site above now are back.

### A specific URL where the issue occurs

`https://www.myabandonware.com/browse/theme/action-rpg-3a/`

### Steps to Reproduce

1 - Enter the site above.

2 - See the ads' spaces.

### Expected behavior

See the ads's spaces removed.

### Actual behavior

Ads' spaces are in the site, this didnt happen before this version.

### Configuration

uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 79495
  cosmetic: 42666
  scriptlet: 16560
  html: 609
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30615-69, 1m
    ublock-badware: 3633-1, 1m
    ublock-privacy: 180-0, 1m
    ublock-abuse: 81-0, 1m
    ublock-unbreak: 1719-0, 1m
    easylist: 62236-618, 1m
    easyprivacy: 26545-497, 1m
    urlhaus-1: 7769-0, 1m
    plowe-0: 3715-3, 1m
    spa-1: 4186-14, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 16291 ms

**Comment by uBlock-user** [comment]
force update ublock filters lists in a while.

**Comment by Felipefpl** [comment]
Actually before i posted i updated the lists several times to see if this removed the spaces, it didnt work. But now it does, thank you for fixing it.

**Comment by Felipefpl** [comment]
Sorry, i have to bring this back, latest beta of ublock broke this again, now the ads's spaces are back, i updated the lists but it didnt work.

**Comment by gorhill** [comment]
Nothing to do with the latest beta of uBO, just the site which changes it's markup to work around blockers. Try:

    myabandonware.com##.e1226

**Comment by Felipefpl** [comment]
I see, thank you for your help gorhill, that did the trick. :)

**Comment by gorhill** [comment]
Maybe more resilient:

    myabandonware.com##.items > .item[id]:not(.itemListGame)

**Comment by AroKol78** [comment]
the numbers are very short-lived

see my solution https://github.com/easylist/easylist/issues/9044#issuecomment-999792899

**Comment by Felipefpl** [comment]
> Maybe more resilient:
> 
> ```
> myabandonware.com##.items > .item[id]:not(.itemListGame)
> ```

gorhill - Strange, tested this fix and it didnt work, the previous one still works.

AroKol78 - thank you for your help with this too. :)

**Comment by gorhill** [comment]
> see my solution

When these are put in a list in widespread use, the site maintainers will work around them as well.

> tested this fix and it didnt work

They all work fine, all part of _"uBlock filters"_, I just tested. You may have custom filters or other custom settings which interfere.

**Comment by Felipefpl** [comment]
> They all work fine, all parts of _"uBlock filters"_, I just tested. You may have custom filters or other custom settings which interfere.

No custom settings, i updated the lists and it worked. Thank you for fixin this. :)
