### ISSUE TITLE
dmktokenguide.com: breakage

### ISSUE THREAD

**Issue by litebright** [uBlockOrigin/uAssets#11068]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.dmktokenguide.com/`

### Category

breakage

### Describe the issue

page icons are not visible for navigation

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78591
  cosmetic: 40089
  scriptlet: 16371
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30604-29, 1d.21h.53m
    ublock-badware: 3633-1, 1d.21h.52m
    ublock-privacy: 179-0, 1d.21h.51m
    ublock-abuse: 81-0, 1d.21h.50m
    ublock-unbreak: 1690-0, 1d.21h.49m
    easylist: 62236-569, 1d.21h.48m
    easyprivacy: 26545-493, 1d.21h.47m
    urlhaus-1: 8214-0, 18h.34m
    plowe-0: 3717-3, 1d.21h.44m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 245 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
keep only uBO enabled, disable all other addons and test again
