### ISSUE TITLE
[nsfw] jobs.teleperformance.pt: popups

### ISSUE THREAD

**Issue by rx8boss** [uBlockOrigin/uAssets#11072]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://jobs.teleperformance.pt/work-in-portugal/jobs/job-offer/abroad-relocation-germanspeaker-generic-lisbon?ref=90070000`

### Category

popups

### Describe the issue

jobs.teleperformance.pt

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 80567
  cosmetic: 43031
  scriptlet: 16379
  html: 610
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30604-29, 1h.40m
    ublock-badware: 3633-1, 1d.1h.54m
    ublock-privacy: 180-0, 1d.1h.53m
    ublock-abuse: 81-0, 1d.1h.24m
    ublock-unbreak: 1719-0, 23h.7m
    easylist: 62253-574, 23h.6m
    easyprivacy: 26548-487, 23h.5m
    urlhaus-1: 8147-0, 5h.32m
    plowe-0: 3687-3, 12d.18h.43m
    DEU-0: 4985-10, 5h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 757 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
What popup are you talking about ? screenshot ?
