### ISSUE TITLE
petsathome.com: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11078]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.petsathome.com/shop/en/pets/pets-at-home-catnip-and-crinkle-carrot-or-parsnip-assorted-cat-toy`

### Category

breakage

### Describe the issue

1. Open the site in new Private Window/Incognito session. 
2. Scroll down and scroll up again.
3. Click on `Add for Delivery`
4. Expect: an overlay is opened at the right side to display what's inside the basket.
Issue: the overlay doesn't appear

Proposed filter:

`@@||googletagmanager.com/gtm.js$script,domain=petsathome.com`

### Screenshot(s)

<details>
<summary>Expect</summary>

![image](https://i.imgur.com/Ac7iIJB.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/147409040-ba4d96c0-c25b-4541-b1e9-f556180ac983.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78576
  cosmetic: 40111
  scriptlet: 16390
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30633-137, 24m
    ublock-badware: 3633-1, 24m
    ublock-privacy: 181-0, 24m
    ublock-abuse: 81-0, 24m
    ublock-unbreak: 1719-0, 24m
    easylist: 62259-453, 59m
    easyprivacy: 26552-492, 24m
    urlhaus-1: 8147-0, 24m
    plowe-0: 3716-3, 24m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 688 ms
popupPanel: 
  blocked: 10
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
