### ISSUE TITLE
[nsfw] clint.be: breakage

### ISSUE THREAD

**Issue by Maiskolf** [uBlockOrigin/uAssets#11079]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.clint.be/entertainment/david-uit-blijven-slapen-heeft-goesting-ik-denk-dat-ik-wegkwijl-wanneer-ik-jou-in-lingerie-zie/`

### Category

breakage

### Describe the issue

Video player on this website does not respond with uBO enabled (can't press the play button). I reported one video as example, but this is true for all videos on the website (note: some videos contain NSFW content)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Video player](https://user-images.githubusercontent.com/96501433/147413327-8d645527-d093-4290-8bb8-87e27cea0953.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78945
  cosmetic: 41009
  scriptlet: 16431
  html: 0
listset (total-discarded, last updated): 
  added: 
    NLD-0: 1194-0, now
  default: 
    easylist: 62259-8, now
    easyprivacy: 26552-17, now
    plowe-0: 3679-816, now
    ublock-abuse: 81-0, now
    ublock-badware: 3629-65, now
    ublock-filters: 30138-137, now
    ublock-privacy: 193-2, now
    ublock-unbreak: 1735-39, now
    urlhaus-1: 8152-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 36 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 253
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
add 

`@@||quantcast.mgr.consensu.org/tcfv2/cmp2.js$script,domain=clint.be`

@ryanbr

**Comment by Maiskolf** [comment]
I can confirm that works! Tested on multiple videos / web pages.
