### ISSUE TITLE
nfl.com: breakage

### ISSUE THREAD

**Issue by tinzarian** [uBlockOrigin/uAssets#11083]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.nfl.com/scores/`

### Category

breakage

### Describe the issue

The main part of the page doesn't load, there is only an empty space

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78294
  cosmetic: 40081
  scriptlet: 16373
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30603-137, 3d.9h.38m
    ublock-badware: 3633-1, 3d.9h.36m
    ublock-privacy: 179-0, 3d.5h.30m
    ublock-abuse: 81-0, 3d.9h.44m
    ublock-unbreak: 1712-0, 3d.9h.42m
    easylist: 62201-461, 3d.9h.40m
    easyprivacy: 26545-485, 3d.9h.34m
    urlhaus-1: 7938-0, 4h.52m
    plowe-0: 3690-3, 12d.1h.36m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 331 ms (selfie)
popupPanel: 
  blocked: 27
```
</details>

**Comment by mapx-** [comment]
add

`@@||quantcast.mgr.consensu.org/tcfv2/cmp2.js$script,domain=nfl.com`

**Comment by mapx-** [comment]
@ryanbr

**Comment by tinzarian** [comment]
Yes, works, thanks.

**Comment by stephenhawk8054** [comment]
I think the scores banner at the top of the page is hidden. Should it be blocked or not?

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148710052-3ca2f900-fefe-4b25-b0e3-d6c47478c993.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148710065-d7310601-a29a-457c-90a7-a313b21dd047.png)

</details>

<details>
<summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77652
  cosmetic: 40417
  scriptlet: 16388
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-30, 16m
    ublock-badware: 3662-1, 16m
    ublock-privacy: 183-0, 16m
    ublock-abuse: 76-0, 16m
    ublock-unbreak: 1726-0, 16m
    easylist: 62809-581, 16m
    easyprivacy: 26611-481, 16m
    urlhaus-1: 6904-0, 16m
    plowe-0: 3685-2, 16m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 249 ms (selfie)
popupPanel: 
  blocked: 26
```
</details>

Proposed filters:

```
nfl.com#@#.nfl-c-strip
nfl.com##[class$="adblock"]
```
