### ISSUE TITLE
2114.com: ads

### ISSUE THREAD

**Issue by sunwendai** [uBlockOrigin/uAssets#11087]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.2114.com/tags-68494/`

### Category

ads

### Describe the issue

11

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 95673
  cosmetic: 50017
  scriptlet: 16506
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 27083-86, 1d.23h.31m
    easylist: 62201-16, 3d.15h.50m
    easyprivacy: 26548-43, 1d.23h.29m
    plowe-0: 3716-820, 1d.3h.25m
    ublock-abuse: 72-0, 2d.15h.45m
    ublock-badware: 3629-65, 2d.15h.43m
    ublock-filters: 30119-158, 2d.15h.41m
    ublock-privacy: 192-2, 2d.15h.39m
    ublock-unbreak: 1733-40, 2d.15h.37m
    urlhaus-1: 8264-0, 3h.19m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 535
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
add

`||2114.com/api.php?a=get_adv$xhr,1p`

**Comment by mapx-** [comment]
@Yuki2718
