### ISSUE TITLE
firstpost.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11082]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.firstpost.com/health/indias-omicron-tally-at-422-6987-covid-19-infections-162-deaths-registered-in-24-hours-10236211.html`

### Describe the issue

They fake a few article tags and put ads inside. The tags are part of the text thats why i reported here

### Screenshot(s)

<img width="329" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/147418133-b5bdc403-a625-48fc-9a05-c67bbc575838.PNG">
<img width="934" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/147418163-58897ef9-0a95-474b-8796-1cfcd7ee129e.PNG">

### uBlock Origin version

1.40.0

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

**Comment by mapx-** [comment]
test

```
firstpost.com##+js(ra, href, [href*="utm_source"])
firstpost.com##+js(ra, src, [src*=".gif"])
```

**Comment by gorhill** [comment]
Using `.t-out-span` to avoid false positive helps:

    firstpost.com##+js(ra, href, .t-out-span [href*="utm_source"])
    firstpost.com##+js(ra, src, .t-out-span [src*=".gif"])

**Comment by JobcenterTycoon** [comment]
Not fully working on the "next story" tab are still links with ads inside.

to reproduce: open `https://www.firstpost.com/category/health` click on any article, scroll down to "next story" (inside the yellow line) and there are these links

**Comment by mapx-** [comment]
```
firstpost.com##+js(ra, href, .t-out-span [href*="utm_source", stay])
firstpost.com##+js(ra, src, .t-out-span [src*=".gif"], stay)
```
