### ISSUE TITLE
[nsfw] es.pornhub.com: detection

### ISSUE THREAD

**Issue by Hank1667** [uBlockOrigin/uAssets#11086]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [ ] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://es.pornhub.com/view_video.php?viewkey=ph5d14088dcc63b`

### Category

detection

### Describe the issue

PORNHUB is pag Porn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 86
filterset (summary): 
  network: 81970
  cosmetic: 44334
  scriptlet: 16438
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62257-8, 44m
    easyprivacy: 26550-17, 22h.49m
    plowe-0: 3691-811, 8d.10h.1m
    spa-0: 3548-21, 22h.41m
    spa-1: 4216-149, 22h.53m
    ublock-abuse: 81-0, 22h.47m
    ublock-badware: 3629-65, 22h.45m
    ublock-filters: 29850-191, 22h.58m
    ublock-privacy: 193-2, 22h.51m
    ublock-unbreak: 1735-41, 22h.55m
    urlhaus-1: 8445-0, 22h.43m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 25 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2624
  launchFromSelfie: true
popupPanel: 
  blocked: 28
  no-cosmetic-filtering: true
  no-remote-fonts: true
```
</details>

**Comment by gorhill** [comment]
> - [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
> - [ ] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
> - [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

These are mandatory steps, not optional. We won't address unreproducable issues which have not been first validate through these steps.
