### ISSUE TITLE
1090ys2.com: detection

### ISSUE THREAD

**Issue by malihome** [uBlockOrigin/uAssets#11088]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://1090ys2.com/show/78769.html`

### Category

detection

### Describe the issue

1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 95584
  cosmetic: 50033
  scriptlet: 16516
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 27081-86, 2d.32m
    easylist: 62253-16, 2d.36m
    easyprivacy: 26548-43, 2d.30m
    plowe-0: 3691-813, 9d.13h.35m
    ublock-abuse: 81-0, 2d.28m
    ublock-badware: 3629-65, 2d.34m
    ublock-filters: 30124-158, 2d.12h.36m
    ublock-privacy: 192-2, 2d.41m
    ublock-unbreak: 1735-40, 2d.38m
    urlhaus-1: 8152-0, 17h.14m
filterset (user): [array of 15 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 327
  launchFromSelfie: true
popupPanel: 
  blocked: 8
```
</details>

**Comment by mapx-** [comment]
add

`1090ys2.com##+js(aopr, adBlockDetected)`

@Yuki2718

**Comment by Yuki2718** [comment]
I can't access the site, where did you accessed the site from?

**Comment by mapx-** [comment]
HG vpn

**Comment by Yuki2718** [comment]
> HK vpn

Thx reproduced, but your filter should be kept in uBlock filters as the fix goes to Base in AG's classification (common scriptlet fix always goes to Base).
