### ISSUE TITLE
tagesanzeiger.ch: breakage

### ISSUE THREAD

**Issue by herrnici** [uBlockOrigin/uAssets#11081]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.tagesanzeiger.ch/`

### Category

breakage

### Describe the issue

The entire site content fails to show. Only a footer is displayed.

### Screenshot(s)

No screenshots attached (it's literally just blank).

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 80527
  cosmetic: 42852
  scriptlet: 16220
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30352-38, 3d.7h.42m
    ublock-badware: 3543-1, 3d.7h.40m
    ublock-privacy: 177-0, 3d.7h.51m
    ublock-abuse: 81-0, 3d.7h.48m
    ublock-unbreak: 1689-0, 3d.7h.38m
    easylist: 62201-569, 3d.7h.46m
    easyprivacy: 26543-499, 3d.7h.44m
    urlhaus-1: 8168-0, 23h.21m
    plowe-0: 3716-3, 6h.57m
    DEU-0: 4985-2, 23h.23m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1383 ms
popupPanel: 
  blocked: 9
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce. Verify that the filter you added is not causing this.

**Comment by herrnici** [comment]
Sorry for this, I had failed to correctly reset the (unwittingly modified) filter list. Closed.
