### ISSUE TITLE
reddit.com: detection

### ISSUE THREAD

**Issue by Sukikyo** [uBlockOrigin/uAssets#11085]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.reddit.com/`

### Category

detection

### Describe the issue

reddit's adblock detection is triggering preventine access to the homepage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78487
  cosmetic: 40081
  scriptlet: 16374
  html: 608
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30609-30, 3d.7h.10m
    ublock-badware: 3633-1, 3d.7h.8m
    ublock-privacy: 180-0, 3d.7h.21m
    ublock-abuse: 81-0, 3d.7h.19m
    ublock-unbreak: 1689-0, 3d.7h.17m
    easylist: 62201-568, 3d.7h.15m
    easyprivacy: 26545-475, 3d.7h.13m
    urlhaus-1: 8147-0, 6h.58m
    plowe-0: 3687-3, 12d.16h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 484 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
I use reddit and never saw an anti adblock ...

**Comment by gorhill** [comment]
Please post a screenshot of the web page.

**Comment by iam-py-test** [comment]
Also can not reproduce:
<details>
<img src="https://user-images.githubusercontent.com/84232764/147492023-f6e1d292-bbd3-4c25-9984-eb1252deadff.png">
</details>

Can you check to see if your [DNS](https://wikipedia.org/wiki/DNS) and [HOSTs file](https://en.wikipedia.org/wiki/Hosts_(file)) are default, and you have no other browser extensions (even antivirus extensions can interfere)
