### ISSUE TITLE
autofaucet.dutchycorp.space: breakage

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#11099]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://autofaucet.dutchycorp.space/login.php`

### Category

breakage

### Describe the issue

I can't login on `https://autofaucet.dutchycorp.space/login.php` when uBO is enabled on Firefox for android. When I enter my email, password and 2FA code, it stucks to loading. I can login without uBO. I see only `www.googletagmanager.com` is blocked with uBO...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20211228-115137_Firefox](https://user-images.githubusercontent.com/79659024/147543816-f706f4f8-f4ae-4639-8ffa-b5f80ac0a2b9.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 79725
  cosmetic: 21839
  scriptlet: 16421
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30749-268, 3m
    ublock-badware: 3635-1, 3m
    ublock-privacy: 181-1, 3m
    ublock-abuse: 81-0, 3m
    ublock-unbreak: 1727-0, 3m
    adguard-mobile: 7015-170, 3m
    easylist: 62308-24121, 3m
    easyprivacy: 26558-489, 3m
    urlhaus-1: 7867-0, 3m
    plowe-0: 3679-3, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3736 ms
popupPanel: 
  blocked: 4
```
</details>

**Comment by datoshkr** [comment]
> I can login without uBO.

* When uBO disabled from Firefox addon manager.

If uBO enabled and `autofaucet.dutchycorp.space` is added to uBO's Trusted sites list, I still can't login...

**Comment by mapx-** [comment]
No issue on my end (it does not ask for `2FA code`)

**Comment by datoshkr** [comment]
> No issue on my end (it does not ask for `2FA code`)

It not asks 2FA if you don't enable it yourself in account settings

**Comment by mapx-** [comment]
open the logger, try again the login, see in the logger what is blocked put here the screenshot

**Comment by datoshkr** [comment]
> open the logger, try again the login, see in the logger what is blocked put here the screenshot

I don't know how to open logger on mobile with latest version of uBO, now I see "Report an issue on this website" button instead "Logger".

![20211228_222847.jpg](https://user-images.githubusercontent.com/79659024/147596092-d5b0c1f0-2a74-4291-8b83-06ad5f9beca1.jpg)

**Comment by gorhill** [comment]
See <https://github.com/uBlockOrigin/uBlock-issues/discussions/1879>.
