### ISSUE TITLE
pushbullet.com: breakage

### ISSUE THREAD

**Issue by miellaby** [uBlockOrigin/uAssets#11092]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.pushbullet.com/`

### Category

breakage

### Describe the issue

uBO prevents the **pushbullet firefox extension** user to log in.

Login occurs on a tab opened at www.pushbullet.com ; I guess that the extension tries to synchronize itself with the web site and fails.

Pushbullet documentation says to disable the ad blocker and indeed it makes the login process working.

I also suspect uBO to break metadata synchronization between the extension and the web site, because the information displayed by the extension was outdated to begin with (that's why I tried to logout and login at first).

Recommanded fix: www.pushbullet.com should be whitelisted.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 94515
  cosmetic: 49255
  scriptlet: 16435
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30717-205, 2m
    ublock-badware: 3635-1, 2m
    ublock-privacy: 189-0, 2m
    ublock-abuse: 81-0, 2m
    ublock-unbreak: 1749-0, 2m
    easylist: 62257-721, 2m
    easyprivacy: 26554-481, 2m
    urlhaus-1: 7860-0, 2m
    plowe-0: 3679-3, 2m
    FRA-0: 26069-369, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 430
  launchFromSelfie: true
popupPanel: 
  blocked: 1
```
</details>

**Comment by gorhill** [comment]
What does [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) report blocking when you try to log in?

**Comment by gorhill** [comment]
I signed in with my Google Account and had no issue, only `google-analytics.com` shows as being blocked. I used only default lists, with FRA one.

**Comment by miellaby** [comment]
Hi @gorhill I tried again with default filters and now it works. Weird. My bad.

**Comment by iam-py-test** [comment]
> Hi @gorhill I tried again with default filters and now it works. Weird. My bad.

You are supposed to test on default lists _before_ reporting an issue:
> - [X]  I have no custom filter lists, or I verified that the issue still occurs without custom filter lists

Try going through each of your old filterlists, enabling them one-by-one, and checking between each. Once you find the list responsible, report the issue to the maintainer of that list.
