### ISSUE TITLE
cocomanga.com: detection

### ISSUE THREAD

**Issue by ghyeng** [uBlockOrigin/uAssets#11090]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.cocomanga.com/19571/1/267.html`

### Category

detection

### Describe the issue

This is a manga website.
When uBlock enabled, the page will eventually display the text "浏览器屏蔽了重要元件无法加载页面，请确保没有开启任何小插件，影响页面加载！ 实在不行请更换浏览器！ 推荐 Chrome。 有网友反馈nod32 之类的杀软也会屏蔽一些东西" in a blank page a few seconds after loading the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 79028
  cosmetic: 41431
  scriptlet: 19190
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4341-7, 24m
  default: 
    easylist: 62257-8, 24m
    easyprivacy: 26554-17, 24m
    plowe-0: 3679-816, 24m
    ublock-abuse: 81-0, 24m
    ublock-badware: 3631-65, 24m
    ublock-filters: 30148-138, 24m
    ublock-privacy: 193-2, 24m
    ublock-unbreak: 1738-39, 24m
    urlhaus-1: 8264-0, 24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3308
  launchFromSelfie: true
popupPanel: 
  blocked: 17
```
</details>

**Comment by uBlock-user** [comment]
Subscribe to AdGuard Chinese.
