### ISSUE TITLE
eevblog.com: ads

### ISSUE THREAD

**Issue by gernn** [uBlockOrigin/uAssets#11094]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.eevblog.com/forum/rf-microwave/problems-at-arrl/`

### Category

ads

### Describe the issue

JLC PCB and Keysight ads both show up. The JLC ad has a consistent animation that's difficult to look at.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/24256884/147499707-69cf9e02-e92c-46c5-b3e4-99d5f2d6c2ce.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78583
  cosmetic: 40099
  scriptlet: 16369
  html: 609
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30620-30, 2d.12h.34m
    ublock-badware: 3633-1, 2d.12h.32m
    ublock-privacy: 180-0, 2d.12h.30m
    ublock-abuse: 72-0, 2d.12h.28m
    ublock-unbreak: 1717-0, 2d.12h.25m
    easylist: 62253-569, 2d.12h.23m
    easyprivacy: 26548-483, 2d.12h.21m
    urlhaus-1: 8152-0, 17h.34m
    plowe-0: 3717-3, 5d.12h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1208 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by gorhill** [comment]
I would go with this given the images are 1p:

    eevblog.com##a[target] > img:upward(a)
