### ISSUE TITLE
es.wallapop.com: breakage

### ISSUE THREAD

**Issue by gitbobbed** [uBlockOrigin/uAssets#11091]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://es.wallapop.com/`

### Category

breakage

### Describe the issue

Login screen gets filtered out by ublock Origin (see attached video - FYI, 'Regístrate o Inicia Sessión' = 'Register or Log in'). That's the button I keep trying to press and nothing happens with uBO on but works with it off.

https://user-images.githubusercontent.com/33555741/147468719-5ba0c2fb-f85e-4c00-b2ff-05b976bbd44a.mov

I have the Annoyances filters that come listed in uBO turned on, but that's the only change from default. No custom filter lists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 90016
  cosmetic: 145813
  scriptlet: 21314
  html: 620
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48648-4097, 18h.50m
    adguard-social: 15267-18, 18h.50m
    fanboy-thirdparty_social: 68-0, 18h.50m
    fanboy-annoyance: 59267-43976, 18h.50m
    fanboy-cookiemonster: 20670-121, 18h.50m
    fanboy-social: 23145-1080, 18h.50m
    ublock-annoyances: 4349-4, 18h.50m
  default: 
    ublock-filters: 30643-42, 18h.50m
    ublock-badware: 3635-1, 18h.50m
    ublock-privacy: 181-0, 18h.50m
    ublock-abuse: 81-0, 18h.50m
    ublock-unbreak: 1719-0, 18h.50m
    easylist: 62259-576, 18h.50m
    easyprivacy: 26552-487, 18h.50m
    urlhaus-1: 8152-0, 18h.50m
    plowe-0: 3679-3, 18h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 400 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by uBlock-user** [comment]
`@@||googleoptimize.com/optimize.js$script,domain=wallapop.com`

@ryanbr
