### ISSUE TITLE
[nsfw] cambro.tv: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11096]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.cambro.tv/200335/2strangers-chaturbate-xxx-camwhores-webcam-porn-video/`

### Category

ads

### Describe the issue

cambro showing ads before a video starts

### Screenshot(s)

https://user-images.githubusercontent.com/81616288/147508016-59e9a28a-33d0-4bc6-bb7f-ac6365275cf5.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 80321
  cosmetic: 43072
  scriptlet: 16391
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30647-145, 3h.9m
    ublock-badware: 3635-1, 3h.9m
    ublock-privacy: 181-0, 3h.9m
    ublock-abuse: 81-0, 3h.9m
    ublock-unbreak: 1721-0, 3h.9m
    easylist: 62306-468, 3h.9m
    easyprivacy: 26555-492, 3h.9m
    urlhaus-1: 7860-0, 3h.9m
    plowe-0: 3679-3, 3h.9m
    DEU-0: 4988-2, 3h.9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 741 ms (selfie)
popupPanel: 
  blocked: 14
```
</details>

**Comment by dumbusernameidk** [comment]
made a filter long ago for this site try:

`cambro.tv##+js(aopr, ptInitFakePromoPlayer)`
