### ISSUE TITLE
[Anti-AdBlock] blockadblock.com

### ISSUE THREAD

**Issue by AhsanEjazC** [uBlockOrigin/uAssets#1109]
### URL(s) where the issue occurs

blockadblock.com
### Versions

- Browser/version: Chrome latest stable
- uBlock Origin version: latest

### Settings

- Default filters on easy mode

### Notes

Makes a request to multiple servers as a bait.

**Comment by SMed79** [comment]
https://github.com/gorhill/uBlock/issues/1271#issuecomment-182831923
