### ISSUE TITLE
Toptal.com full screen recuritment modal

### ISSUE THREAD

**Issue by cyberjacob** [uBlockOrigin/uAssets#111]
### URL(s) where the issue occurs

`https://www.toptal.com/python/an-introduction-to-mocking-in-python`

### Describe the issue

After visiting the website for a short while a full screen modal appears advertising a recruitment company. There is no X button, and this can only be closed by clicking a small piece of text at the bottom.

### Screenshot(s)

Closed it twice and can't get it to show up again now :(

### Versions

- Browser/version: FireFox 48.0.2
- uBlock Origin version: 1.8.4

### Settings

- Enabled additional filter sets

### Notes

Fix ready to be merged

**Comment by gorhill** [comment]
That is not an ad, it's self-promotion.
