### ISSUE TITLE
blim.com: ads

### ISSUE THREAD

**Issue by Squishey** [uBlockOrigin/uAssets#11100]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.blim.com/asset/34644/player` or any other blim.com content

### Category

ads

### Describe the issue

Not blocking ANY ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 81601
  cosmetic: 44508
  scriptlet: 16600
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62253-8, 3d.6h.43m
    easyprivacy: 26548-17, 3d.6h.41m
    plowe-0: 3690-811, 11d.12h.33m
    spa-0: 3548-21, 1d.9h.20m
    spa-1: 4216-149, 3d.6h.45m
    ublock-abuse: 81-0, 3d.6h.15m
    ublock-badware: 3629-65, 3d.5h.33m
    ublock-filters: 30127-196, 3d.5h.23m
    ublock-privacy: 192-2, 3d.5h.21m
    ublock-unbreak: 1733-41, 3d.5h.4m
    urlhaus-1: 8152-0, 1d.9h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 207
  launchFromSelfie: true
popupPanel: 
  blocked: 10
```
</details>

**Comment by mapx-** [comment]
without an account we can't help you
