### ISSUE TITLE
kcra.com: breakage

### ISSUE THREAD

**Issue by bug-zapper** [uBlockOrigin/uAssets#11107]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.kcra.com/nowcast`

### Category

breakage

### Describe the issue

While attempting to stream a pre-recorded Nowcast, the video stops after 36 seconds. Workaround is to press pause and play, which resumes playback until 1:46. Lather, rinse, repeat until video concludes. Seems like there's a keep-alive check of some kind happening and uBlock is preventing the response, but I'm not sure.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78325
  cosmetic: 39976
  scriptlet: 16268
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 62308-8, 17h.22m
    easyprivacy: 26556-17, 17h.20m
    plowe-0: 3679-816, 1d.19h.27m
    ublock-abuse: 72-0, 17h.32m
    ublock-badware: 3631-65, 17h.30m
    ublock-filters: 29880-134, 17h.28m
    ublock-privacy: 193-2, 17h.26m
    ublock-unbreak: 1738-39, 17h.24m
    urlhaus-1: 7737-0, 46m
filterset (user): [empty]
trustedset: 
  added: [array of 46 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1605
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

**Comment by bug-zapper** [comment]
KCRA is owned by Hearst, so any of the 31 Hearst-owned TV stations (major network affiliates like NBC, which deliver local news) will suffer this same problem. Happens with Chrome and Firefox that I've tested.

**Comment by gorhill** [comment]
Unable to reproduce any issue. Did you see if the issue also occurs without uBO?

**Comment by bug-zapper** [comment]
> Unable to reproduce any issue. Did you see if the issue also occurs without uBO?

The issue does not occur when uBO is turned off. The player plays, and the broadcast is bombarded with ads for the local car dealership.

**Comment by gorhill** [comment]
Never mind, the issue occurred at ~46:12, i.e. over two minutes after start of video -- I was checking for around 36 seconds after start.

**Comment by gorhill** [comment]
Does this make the issue go away on your side?

    kcra.com#@#+js(nostif, (), 500)

**Comment by bug-zapper** [comment]
It does! Before adding this to the My Filters list, you could see a certain amount of content had been downloaded but once the playhead reached that point, frozen. Now, you can see more content being downloaded in advance as the playhead gets closer to the end of whatever was previously downloaded. Thank you for the amazingly fast response.

**Comment by gorhill** [comment]
We might need to revisit <https://github.com/uBlockOrigin/uAssets/issues/5119>, it does not look like `##+js(nostif, (), 500)` is needed anymore on `kcra.com` and maybe all the other sites as well.

**Comment by bug-zapper** [comment]
Since I'm not a developer, I'll leave the smart stuff to the smarties. Thanks again, and grateful to contribute to such a great piece of software.
