### ISSUE TITLE
[anti-adblock] mirole.com

### ISSUE THREAD

**Issue by AhsanEjazC** [uBlockOrigin/uAssets#1110]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://mirole.com
### Describe the issue

Does not allow content access

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome latest stable
- uBlock Origin version: latest

### Settings

- Default on medum mode

**Comment by AhsanEjazC** [comment]
Does not work, the message still pops up.

**Comment by mapx-** [comment]
- anti adblock message ?
- Did you update "ublock filters" ? Did you by chance disable "ublok filters" ?
- Do you see the new filter in the logger ?
`mirole.com##script:inject(bab-defuser.js)`

**Comment by AhsanEjazC** [comment]
Yes, the antiadblock message pops up again, it is BlockAdBlock or something.

**Comment by mapx-** [comment]
Please answer all my questions.
uBo version ?

I get no warning message anymore but the site is geo-blocked
`This website is not avaliable in your region.`

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
