### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by EnsKrgL** [uBlockOrigin/uAssets#11106]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

It shows ads just when started the video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 162100
  cosmetic: 191053
  scriptlet: 33009
  html: 0
listset (total-discarded, last updated): 
  added: 
    DEU-0: 4988-0, 3m
    adguard-annoyance: 48773-149, 3m
    adguard-generic: 62344-679, 3m
    adguard-mobile: 7033-51, 3m
    adguard-social: 15313-776, 3m
    adguard-spyware: 24774-863, 3m
    adguard-spyware-url: 406-12, 3m
    block-lan: 44-0, 3m
    curben-phishing: 13180-0, 3m
    curben-pup: 380-0, 3m
    dpollock-0: 16948-262, 3m
    fanboy-annoyance: 59542-3941, 3m
    fanboy-cookiemonster: 20939-20939, 3m
    fanboy-social: 23147-23147, 3m
    fanboy-thirdparty_social: 69-21, 3m
    mvps-0: 8730-1832, 3m
    ublock-annoyances: 4341-289, 3m
  default: 
    TUR-0: 9356-87, 3m
    easylist: 62338-1246, 3m
    easyprivacy: 26558-10681, 3m
    plowe-0: 3678-1497, 3m
    ublock-abuse: 81-0, 3m
    ublock-badware: 3631-205, 3m
    ublock-filters: 30163-3259, 3m
    ublock-privacy: 193-34, 3m
    ublock-unbreak: 1738-112, 3m
    urlhaus-1: 7737-5, 3m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 611
  launchFromSelfie: true
popupPanel: 
  blocked: 159
```
</details>

**Comment by gorhill** [comment]
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate, <https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+youtube.com>
