### ISSUE TITLE
svd.se: breakage

### ISSUE THREAD

**Issue by skraepgh** [uBlockOrigin/uAssets#11101]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.svd.se/`

### Category

breakage

### Describe the issue

Login button is disabled with uBO enabled. Works if extension is disabled and page reloaded.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 80353
  cosmetic: 42233
  scriptlet: 16464
  html: 656
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30334-29, 1h.25m
    ublock-badware: 3635-1, 1h.24m
    ublock-privacy: 181-0, 1h.23m
    ublock-abuse: 81-0, 1d.17h.6m
    ublock-unbreak: 1689-0, 1h.29m
    easylist: 62308-184, 1h.28m
    easyprivacy: 26558-46, 1h.27m
    urlhaus-1: 8445-0, 1h.22m
    plowe-0: 3679-819, 1h.30m
    SWE-1: 4014-16, 1h.26m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 200 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by okiehsch** [comment]
@lassekongo83 
`www.svd.se#@#+js(aopr, navigator.sendBeacon)`
fixes the issue.

**Comment by skraepgh** [comment]
Thanks, that worked perfectly! Will this thread be notified when it's added to the regional list, so I can remove the custom rule?

**Comment by okiehsch** [comment]
Yes. We will close the thread after it has been added to the regional list.

**Comment by skraepgh** [comment]
Thanks a lot!!
