### ISSUE TITLE
caremark.com: breakage

### ISSUE THREAD

**Issue by vdibiase** [uBlockOrigin/uAssets#11108]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.caremark.com/wps/PA_FAST/AltAuthProxy/`

### Category

breakage

### Describe the issue

Unable to select the 'sign-in' button on the site to move forward to the signed-in page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78318
  cosmetic: 40118
  scriptlet: 16425
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62259-8, 2d.2h.21m
    easyprivacy: 26552-17, 2d.2h.18m
    plowe-0: 3709-815, 8d.2h.1m
    ublock-abuse: 81-0, 2d.2h.16m
    ublock-badware: 3560-64, 2d.2h.14m
    ublock-filters: 30147-137, 2d.2h.12m
    ublock-privacy: 189-7, 2d.2h.10m
    ublock-unbreak: 1735-39, 2d.2h.8m
    urlhaus-1: 7860-0, 23h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 957
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
test

`||caremark.com/tnadstlinj.js$badfilter`

**Comment by mapx-** [comment]
@ryanbr
