### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by Anon-0101** [uBlockOrigin/uAssets#11104]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [x] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://aternos.org/software/modpacks/`

### Category

detection

### Describe the issue

Site detects ublock origin 
multiple issues before have been reported, but site is still buggy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/87794399/147587212-3578bd0b-2498-420a-b818-5a5cd8e431ad.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78136
  cosmetic: 40109
  scriptlet: 16418
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62259-8, 2d.5h.40m
    easyprivacy: 26552-17, 2d.5h.38m
    plowe-0: 3716-818, 2d.5h.34m
    ublock-abuse: 81-0, 2d.5h.30m
    ublock-badware: 3509-64, 2d.5h.26m
    ublock-filters: 30115-137, 2d.5h.24m
    ublock-privacy: 191-11, 2d.4h.49m
    ublock-unbreak: 1735-39, 2d.4h.47m
    urlhaus-1: 7737-0, 2h.1m
filterset (user): [array of 7 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1060
  launchFromSelfie: true
popupPanel: 
  blocked: 3
```
</details>

**Comment by gorhill** [comment]
Duplicate, <https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+aternos.org>.
