### ISSUE TITLE
knowyourmeme.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#1111]
A sticky banner ad/ ad toolbar is displayed on pages on `http://knowyourmeme.com`.

**SS:** https://i.imgur.com/rIdqHge.png
**Error URL:** http://knowyourmeme.com/memes/expanding-brain

This has been confirmed as an ad by the site editors themselves:

> Hey guys, as some of you have correctly guessed, the toolbar at the bottom is a native promotional toolbar that just rolled out as part of our new partnership with the Complex ad network.

`http://knowyourmeme.com/forums/report-problems/topics/51958/page/1#forum_post_897350`

**Comment by mapx-** [comment]
already covered by fanboy's annoyances
`||toolbar.complex.com^$third-party`

**Comment by gotitbro** [comment]
@mapx- Shouldn't it be in EasyList? Its an ad after all.

**Comment by mapx-** [comment]
You should ask fanboy here:
https://github.com/ryanbr/fanboy-adblock/issues

**Comment by gotitbro** [comment]
@ryanbr Can the filter be moved to EasyList?
