### ISSUE TITLE
yonelabo.com: ads

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#11118]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://yonelabo.com/`

### Category

ads

### Describe the issue

AdGuard enabled: soft anti-adblock (FUD against adblockers) https://github.com/AdguardTeam/AdguardFilters/issues/94239
uBlock Origin enabled: ad leftover thanks to surrogates redirect

We should hide the element in uBlock filters, or annoyances?
~~~
yonelabo.com###nankafix
~~~

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

#### uBlock Origin enabled:
![Screenshot](https://user-images.githubusercontent.com/82331005/147644306-be9f7fee-31c6-4a46-88de-786c0c1a1c1b.png)

#### AdGuard enabled:
![Screenshot](https://user-images.githubusercontent.com/82331005/147645596-3c65e016-0cfc-4d3e-8b06-f2bd44b362e8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 79272
  cosmetic: 44684
  scriptlet: 16449
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30633-32, now
    ublock-badware: 3635-1, now
    ublock-privacy: 181-0, now
    ublock-abuse: 81-0, now
    ublock-unbreak: 1724-0, now
    easylist: 62346-652, now
    easyprivacy: 26560-504, now
    urlhaus-1: 7899-0, now
    plowe-0: 3679-3, now
    JPN-1: 5631-14, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 949 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
Disabling the redirect and then add a filter to Annoyances will be too much, I'll just add to main list.

**Comment by uBlock-user** [comment]
> Disabling the redirect

redirect defuses the anti-adb msg and is not the cause. That placeholder is there to stay whether you have uBO enabled or not.
