### ISSUE TITLE
dic.pixiv.net: breakage

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#11119]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://dic.pixiv.net/a/a`

### Category

breakage

### Describe the issue

The accordion menus will not expand on mobile devices.
~~~
!#if env_mobile
@@||browser.sentry-cdn.com^*/bundle.min.js$domain=dic.pixiv.net
!#endif
~~~

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 80528
  cosmetic: 26320
  scriptlet: 16478
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30732-270, now
    ublock-badware: 3635-1, now
    ublock-privacy: 181-1, now
    ublock-abuse: 81-0, now
    ublock-unbreak: 1723-0, now
    adguard-mobile: 7016-179, now
    easylist: 62348-24145, now
    easyprivacy: 26566-512, now
    urlhaus-1: 7743-0, now
    plowe-0: 3681-3, now
    JPN-1: 5632-139, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2554 ms
popupPanel: 
  blocked: 26
```
</details>

**Comment by mapx-** [comment]
What exactly does not work ?

**Comment by hirorpt** [comment]
### Screenshot(s)

<details>
<summary>Default filter lists</summary>

![Screenshot1](https://user-images.githubusercontent.com/82331005/147747311-f01da92a-c1a9-4860-9600-b86954d95ae6.png)
</details>

<details>
<summary>Default filter lists + the filter I suggested</summary>

![Screenshot2](https://user-images.githubusercontent.com/82331005/147747315-6ebe5311-790f-4168-8020-2fdb5f27715c.png)
</details>

### Additional description
The highlighted element in the screenshot above cannot be clicked, etc.

**Comment by mapx-** [comment]
yeah, needing that exception @Yuki2718

**Comment by hirorpt** [comment]
@ryanbr
> @@||browser.sentry-cdn.com^$domain=dic.pixiv.net

The exception filter is no longer needed. You can delete it.
