### ISSUE TITLE
metoffice.gov.uk: nuisance

### ISSUE THREAD

**Issue by xanda-escuyer** [uBlockOrigin/uAssets#11110]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.metoffice.gov.uk/weather/forecast/gcwfhf1w0`

### Category

nuisance

### Describe the issue

Ads etc are filtered but in so doing there is a banner of empty space at the top of the page.
Haven't seen this elsewhere.
Zooming and mode switching to full screen have no effect.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot-www metoffice gov uk-2021 12 28-21_30_32](https://user-images.githubusercontent.com/15840995/147608993-e7d27721-eb96-44f8-b3c4-ae486f288f52.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78313
  cosmetic: 40148
  scriptlet: 16433
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62342-8, 3h.39m
    easyprivacy: 26558-17, 3h.39m
    plowe-0: 3679-816, 3h.39m
    ublock-abuse: 81-0, 3h.39m
    ublock-badware: 3631-65, 3h.38m
    ublock-filters: 30163-137, 3h.38m
    ublock-privacy: 193-2, 3h.38m
    ublock-unbreak: 1738-39, 3h.38m
    urlhaus-1: 7737-0, 3h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 41 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1179
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by gorhill** [comment]
Enable _Fanboy Annoyance_ in _Annoyances_ in _Fitler lists_ pane.

**Comment by gorhill** [comment]
Actually, my mistake, _EasyList Cookie_ alone is sufficient (it's included in _Fanboy Annoyance_).

**Comment by xanda-escuyer** [comment]
Thanking you Good Sir - all done.
