### ISSUE TITLE
vungoctuan.vn: detection

### ISSUE THREAD

**Issue by hieuckdev** [uBlockOrigin/uAssets#11111]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://vungoctuan.vn/sua-loi-srttrail-txt-bsod-tren-windows-10-7105.html`

### Category

detection

### Describe the issue

I didn't watch, they blocked right-clicks and made us turn off ad blocking

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ảnh chụp màn hình 2021-12-29 055144](https://user-images.githubusercontent.com/95690928/147612925-3f4abd1d-ee58-4dbd-bfe9-3b3809d36fdd.png)

</details>
https://imgur.com/a/r2mPI9P

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 86
filterset (summary): 
  network: 31124
  cosmetic: 63310
  scriptlet: 26971
  html: 0
listset (total-discarded, last updated): 
  removed: 
    VIE-1: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
    urlhaus-1: null
  added: 
    adguard-generic: 62323-862, 2d.11h.47m
    adguard-mobile: 7024-63, 3d.9h.46m
    fanboy-cookiemonster: 20748-11, 21h.49m
  default: 
    ublock-filters: 30147-2868, 16h.33m
filterset (user): [array of 461 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 569
  launchFromSelfie: true
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
```
vungoctuan.vn##+js(no-xhr-if, ads)
vungoctuan.vn##+js(acis, document.write, snow)
```

The second to kill the cpu-intensive snow crap

@hoang-rio

**Comment by hoang-rio** [comment]
I see no detection in my phone. Is it only happend in desktop

**Comment by mapx-** [comment]
Tested on desktop
