### ISSUE TITLE
ffxiv.gamerescape.com: ads

### ISSUE THREAD

**Issue by skullriot** [uBlockOrigin/uAssets#11112]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://ffxiv.gamerescape.com/wiki/Arrhidaeus_Master_Key`

### Category

ads

### Describe the issue

leftover ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 119872
  cosmetic: 120895
  scriptlet: 32521
  html: 617
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8h.40m
    adguard-generic: 61412-4916, 3d.16h.56m
    adguard-spyware: 24567-848, 3d.16h.56m
    adguard-annoyance: 48643-4271, 3d.16h.56m
    adguard-social: 15264-1073, 3d.16h.56m
    fanboy-annoyance: 59299-40161, 3d.16h.56m
    fanboy-social: 23180-14036, 3d.16h.56m
    ublock-annoyances: 4349-8, 3d.16h.56m
    adguard-spyware-url: 404-2, 3d.16h.56m
  default: 
    ublock-filters: 30625-247, 3d.16h.56m
    ublock-badware: 3633-1, 3d.16h.56m
    ublock-privacy: 180-1, 3d.16h.56m
    ublock-abuse: 81-0, 3d.16h.56m
    ublock-unbreak: 1719-0, 3d.16h.56m
    easylist: 62254-24028, 3d.16h.56m
    easyprivacy: 26549-10854, 3d.16h.56m
    urlhaus-1: 8656-0, 8h.41m
    plowe-0: 3715-3, 3d.16h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 229 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
- remove `anti-adblock-killer`, outdated and provoking issues
- leftovers => provide screenshot
