### ISSUE TITLE
techradar.com: breakage

### ISSUE THREAD

**Issue by gizzalucy** [uBlockOrigin/uAssets#11117]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.techradar.com/amp/news/wake-up-its-time-to-play-oblivion-again`

### Category

breakage

### Describe the issue

The whole page has a semitransparent overlay which disappears when ubo is off, replaced with a "confirm cookies" selection box. I'm in the UK, which has strict cookie laws.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 96
filterset (summary): 
  network: 80366
  cosmetic: 21703
  scriptlet: 16257
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30467-195, 4d.7h
    ublock-badware: 3633-1, 1d.12h
    ublock-privacy: 180-1, 4d.6h.58m
    ublock-abuse: 72-0, 1d.21h.44m
    ublock-unbreak: 1725-0, 4d.6h.59m
    adguard-mobile: 7014-171, 1d.11h.59m
    easylist: 62253-24114, 4d.7h.1m
    easyprivacy: 26548-492, 4d.6h.57m
    plowe-0: 3715-3, 4d.7h.2m
    urlhaus-1: 8445-0, 1d.21h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 583 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
![image](https://user-images.githubusercontent.com/16838044/147642410-972c0c25-8854-477f-97ae-5aecad9d1f55.png)
