### ISSUE TITLE
bing.com tracking parameter

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#11116]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bing.com/?toWww=1&redig=99b3a3714445792cb209abef919bb129`

### Describe the issue

How to get rid of the parameter following .com/?

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 95.0.2

### Settings

N/A

### Notes

N/A

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.

**Comment by krystian3w** [comment]
Test

bing.com$removeparam=toWww
bing.cpm$removeparam=redig


If no works then bing uses JavaScript "replace()" to modify url without "document" network requests. Rather both mark as slow filters.

**Comment by iam-py-test** [comment]
@krystian3w does filters are probably not going to work.
```
||bing.com^$removeparam=toWww
||bing.com^$removeparam=redig
```

**Comment by krystian3w** [comment]
uBo itself should add `||` and ^``
