### ISSUE TITLE
premid.app: detection

### ISSUE THREAD

**Issue by christianavi** [uBlockOrigin/uAssets#11113]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://premid.app/downloads`

### Category

detection

### Describe the issue

It detects adblockers and is trying to be cute about it by prompting multiple times to disable adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43099141/147628091-dab402b9-02f1-4f7c-8bac-464079d54156.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 98
filterset (summary): 
  network: 79440
  cosmetic: 54824
  scriptlet: 16428
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-social: 15285-12, 1d.10h.47m
    curben-pup: 376-0, 22h.38m
    fanboy-thirdparty_social: 69-3, 5d.11h.41m
  default: 
    easylist: 62306-11, 1d.11h.2m
    easyprivacy: 26555-19, 1d.11h
    plowe-0: 3717-818, 5d.12h.54m
    ublock-abuse: 81-0, 1d.10h.58m
    ublock-badware: 3631-65, 1d.10h.55m
    ublock-filters: 30148-140, 1d.10h.53m
    ublock-privacy: 193-4, 1d.10h.51m
    ublock-unbreak: 1704-39, 1d.10h.49m
    urlhaus-1: 7867-0, 22h.40m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1004
  launchFromSelfie: true
popupPanel: 
  blocked: 4
```
</details>

**Comment by llacb47** [comment]
Test `premid.app#@#.adsbygoogle`

**Comment by uBlock-user** [comment]
re-fastened the timer, no anti-adb though.
