### ISSUE TITLE
workandmoney.com: ads

### ISSUE THREAD

**Issue by DiscoJL** [uBlockOrigin/uAssets#11124]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.workandmoney.com/s/best-online-multiplayer-games-b10104c07ab94136`

### Category

ads

### Describe the issue

Video player (vjs) loads and plays ads. Seems like it is hard to block based on URL reference.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ubo](https://user-images.githubusercontent.com/96836210/147683626-dbeba35a-8029-49b9-ba6c-a3aea2205f56.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 99990
  cosmetic: 118638
  scriptlet: 30138
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt: 1260-1, 20h.11m
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1873-0, 3d.10h.27m
    adguard-generic: 61426-4516, 2d.14h.3m
    adguard-mobile: 7006-155, 3d.10h.31m
    adguard-annoyance: 48645-1083, 3d.10h.30m
  default: 
    ublock-filters: 30623-51, 3d.10h.28m
    ublock-badware: 3513-1, 2d.14h.8m
    ublock-privacy: 181-1, 2d.14h.7m
    ublock-abuse: 72-0, 3d.10h.29m
    ublock-unbreak: 1689-0, 2d.14h.6m
    easylist: 62257-702, 2d.14h.5m
    easyprivacy: 26553-493, 2d.14h.4m
    plowe-0: 3717-4, 6d.14h.31m
    urlhaus-1: 7737-0, 20h.10m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 174 ms (selfie)
popupPanel: 
  blocked: 25
```
</details>

**Comment by gorhill** [comment]
Caused by

    @@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=workandmoney.com

In _"AdGuard Base"_ list. Report to AdGuard filter issue tracker: <https://github.com/AdguardTeam/AdguardFilters/issues>.
