### ISSUE TITLE
mycanal.fr

### ISSUE THREAD

**Issue by Slowerzs** [uBlockOrigin/uAssets#1112]
### URL(s) where the issue occurs

`https://www.mycanal.fr/divertissement/au-tableau-paddington-les-guignols-l-integrale-du-18-12/p/1474375`

### Describe the issue

Video blocked with an adblocker

### Versions

- Browser: Chrome
- uBlock Origin version: Nano Adblocker 1.0.0.20

### Settings

- I have Nano defender enabled
### Notes
I helped to fix for canalplus.fr but apparently they changed their website, but I still have a fix : 
1) Get the video ID : for example, in `https://www.mycanal.fr/divertissement/au-tableau-paddington-les-guignols-l-integrale-du-18-12/p/1474375`  the ID is 1474375
2) Get the video URL : go to `http://service.canal-plus.com/video/rest/getVideos/cplus/ID`, so for the same example it would be `http://service.canal-plus.com/video/rest/getVideos/cplus/1474392`.
3) Get the URL : In < MEDIA > < VIDEO > we have the actual URL for several qualities : in the example I would take : 
`http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1712/18/1191785_77_1500k.mp4`
3) Add the parameter to access the video : add ?secret=pqzerjlsmdkjfoiuerhsdlfknaes to be able to see the video. So the final URL would be : 
`http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1712/18/1191785_77_1500k.mp4?secret=pqzerjlsmdkjfoiuerhsdlfknaes`

**Comment by M3T4LL1C4** [comment]
@@v.fwmrm.net/$xmlhttprequest,domain=www.mycanal.fr
unblocks the video for me

**Comment by mapx-** [comment]
`@@||v.fwmrm.net/ad/*vpaid=on$xmlhttprequest,domain=mycanal.fr`

@SMed79
