### ISSUE TITLE
Blocking the IPv6 "Unspecified Address" ([::]) breaks latest NoScript (11.2.13) and other extensions.

### ISSUE THREAD

**Issue by hackademix** [uBlockOrigin/uAssets#11128]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://mozilla.org

### Describe the issue

The [LAN intrusion blocking filter](https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt) contains several references to **[::]**, which is the [IPv6 Unspecified Address](https://www.rfc-editor.org/rfc/rfc4291.html#section-2.5.2).

This is [breaking latest NoScript](https://forums.informaction.com/viewtopic.php?p=104769#p104769) and other extensions relying on the NoScript Commons Library, such as FSF's jShelter, which use this address as a [placeholder endpoint to implement synchronous messages](https://github.com/hackademix/nscl/blob/main/common/SyncMessage.js#L24) for content script early configuration purposes.

Since this is not meant to be used by any node, either LAN or not, is there any reason not to have it blocked by the filter?
Thanks.

### uBlock Origin version

Any

### Browser name and version

Mozilla Firefox 96.0b8

### Settings

Allowing _Filter Lists>Privacy>Block Outsider Intrusion into LAN_

**Comment by gwarser** [comment]
With NoScript you should probably not use the lists because NS is by itself blocking local connections https://noscript.net/faq#qa3_9

If you really need, you can add exception for your specific `[::]` connection by

    @@[::]:yourport/and path

or even badfilter this one filter:

    ||[::]^$3p,domain=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter

**Comment by gwarser** [comment]
Apparently `behind-the-scene https://[::]/nscl/moz-extension:// xmlhttprequest allow` is working[^working], so maybe exception like this will work too:

    @@|https://[::]/nscl/moz-extension://$xhr,domain=behind-the-scene



[^working]: https://forums.informaction.com/viewtopic.php?p=104772#p104772

**Comment by hackademix** [comment]
> BTW [this address is redirecting to `localhost`](https://github.com/WICG/private-network-access/issues/24), so it's rather not completely safe for random add-ons or libraries to use it freely:
> 
> ![image](https://user-images.githubusercontent.com/886325/147695519-96c16378-cc86-4212-914c-67963b12e433.png)

You're right about Chromium, in facts we use file://[::] there, while Firefox correctly threats it as unreachable.

Anyway, I'm thinking to switch the placeholder endpoint to [ff00::], which is a reserved multicast which should be invalid anyway in a HTTP request content (and is regarded as such by both browsers).

**Comment by gwarser** [comment]
> You're right about Chromium, in facts we use file://[::] there, while Firefox correctly threats it as unreachable.

Screenshot is from Firefox.

**Comment by hackademix** [comment]
Thank you, [fixed](https://github.com/hackademix/nscl/commit/3dea24a67007b06e0750ee54f5a851f235348e4b) in [NoScript 11.2.14rc1](https://noscript.net/getit#devel):

v 11.2.14rc1
============================================================
x [nscl] Updated SyncMessage fixes conflict with other
content blockers (thanks gwarser, barbaz and Baraoic)

**Comment by gwarser** [comment]
@hackademix turns out `[ff00::]` get through webRequest API https://www.reddit.com/r/uBlockOrigin/comments/sn5x6t/new_connection_out_of_nowhere/

**Comment by gwarser** [comment]
>something wrong with 1.46.0...1.47.0, maybe '• rewrite static filtering parser',
and noscript's xhr from uassets/11128 is losing its 'context: behind-the-scene',
so

>     @@|https://[ff00::]/nscl/moz-extension:/../syncMessage/$xhr,domain=behind-the-scene

>doesn't work

***

Was

![Screenshot_20230216_111808](https://user-images.githubusercontent.com/886325/219337646-b0559be0-7f9f-4a46-b030-615da8379f01.png)

is

![image](https://user-images.githubusercontent.com/886325/219337379-640415fa-6483-47e7-91ab-58737edc7332.png)


Probably because of https://github.com/gorhill/uBlock/commit/6fd58c9c9b53a5d88042809f5576c70e3f6ac512


I see no issue on my side. Maybe because it's on Linux.
