### ISSUE TITLE
mydealz.de: breakage

### ISSUE THREAD

**Issue by duracotton** [uBlockOrigin/uAssets#11122]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.mydealz.de/`

### Category

breakage

### Describe the issue

As a logged in user the notification icon on the top menu bar is not opening anymore when uBlock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/25416153/147680842-d07094a9-c627-4871-a50b-60b69121c264.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 185528
  cosmetic: 261139
  scriptlet: 35030
  html: 630
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/chromium/filters/14.txt: 46115-3941, 2d.21h.49m
    https://filters.adtidy.org/extension/chromium/filters/2.txt: 109335-108430, 2d.21h.46m
    https://filters.adtidy.org/extension/chromium/filters/3.txt: 23727-840, 2d.21h.44m
    https://filters.adtidy.org/extension/chromium/filters/4.txt: 15253-44, 2d.21h.40m
    https://filters.adtidy.org/extension/chromium/filters/6.txt: 9424-141, 2d.21h.30m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29809-274, 2d.21h.26m
    https://mirror1.malwaredomains.com/files/immortal_domains.txt: 3196-0, 379d.16h.8m
    https://raw.github.com/liamja/Prebake/master/obtrusive.txt: 1072-3, 2d.22h.15m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt: 588-1, 3h.32m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-7, 19h.50m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1034-0, 2d.22h.11m
    https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt: 1072-1072, 2d.22h.13m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-10, 3h.37m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-39, 2d.17h
    https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-0, 2d.16h.58m
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt: 34-0, 2d.17h.2m
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-24, 2d.16h.56m
    https://www.fanboy.co.nz/fanboy-cookiemonster.txt: 20742-365, 1d.23h.4m
    https://www.i-dont-care-about-cookies.eu/abp/: 24127-8306, 2d.21h.22m
    adguard-generic: 61424-5550, 2d.22h.5m
    [14 lists not shown]: [too many]
  default: 
    ublock-filters: 30643-365, 2d.21h.28m
    ublock-badware: 3635-1, 2d.21h.32m
    ublock-privacy: 177-0, 2d.21h.38m
    ublock-abuse: 81-4, 2d.21h.24m
    ublock-unbreak: 1719-4, 2d.22h.7m
    easylist: 62259-1251, 2d.22h.3m
    easyprivacy: 26552-11252, 2d.21h.59m
    plowe-0: 3709-1794, 9d.3h.43m
    DEU-0: 4992-4985, 3h.35m
    urlhaus-1: 7737-0, 3h.34m
filterset (user): [array of 73 redacted]
trustedset: 
  added: [array of 442 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 14683 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by gorhill** [comment]
Did you find out if the issue also exists with only default lists?

**Comment by duracotton** [comment]
Oh sorry, I skipped the part of the prerequisites.
The faulty filter is "Fanboy’s Annoyance". I guess I have to contact the author then?

In this case the ticket can be closed.

Thanks!
