### ISSUE TITLE
forebears.io: breakage

### ISSUE THREAD

**Issue by kashmirix** [uBlockOrigin/uAssets#11123]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://forebears.io/`

### Category

breakage

### Describe the issue

Breaks page layout.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![aaaaaaaaaa](https://user-images.githubusercontent.com/10689737/147681372-97b5a109-e9c7-486c-a107-42b27c32c965.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 135852
  cosmetic: 175224
  scriptlet: 32759
  html: 0
listset (total-discarded, last updated): 
  added: 
    POL-0: 7764-8, 8h.39m
    POL-2: 1273-10, 2d.2h.45m
    adguard-annoyance: 48784-148, 4h.22m
    adguard-generic: 62350-910, 4h.14m
    adguard-mobile: 7034-52, 4h.20m
    adguard-spyware: 24784-849, 4h.16m
    adguard-spyware-url: 406-12, 4h.18m
    curben-phishing: 13087-0, 8h.41m
    curben-pup: 380-0, 18h.2m
    fanboy-annoyance: 59267-2872, 2d.19h.54m
    ublock-annoyances: 4345-291, 4h.24m
  default: 
    easylist: 62259-1024, 3d.3m
    easyprivacy: 26552-10613, 3d.1m
    plowe-0: 3715-977, 4d.15h.14m
    ublock-abuse: 81-0, 4h.35m
    ublock-badware: 3509-186, 4h.32m
    ublock-filters: 30135-3271, 4h.30m
    ublock-privacy: 193-34, 4h.28m
    ublock-unbreak: 1734-111, 4h.26m
    urlhaus-1: 7737-4, 8h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 536
  launchFromSelfie: true
popupPanel: 
  blocked: 13
```
</details>

**Comment by gorhill** [comment]
Broken by _Fanboy's Annoyance_'s `/assets/fb.`.

Fixed with `@@||forebears.io/assets/*$1p`.

**Comment by gorhill** [comment]
cc @ryanbr
