### ISSUE TITLE
mail.yandex.ru: ads

### ISSUE THREAD

**Issue by MrDevil131** [uBlockOrigin/uAssets#11137]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Describe the issue

ads are visible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://user-images.githubusercontent.com/73957930/147747845-8ab245b5-d945-495e-a0da-8fe2a91677bf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 100
filterset (summary): 
  network: 96167
  cosmetic: 61041
  scriptlet: 17936
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40564-9, 2d.6h.6m
    easylist: 62348-24, 19h.3m
    easyprivacy: 26566-114, 19h.1m
    plowe-0: 3715-823, 5d.15h.36m
    ublock-abuse: 81-1, 18h.59m
    ublock-badware: 3509-64, 18h.57m
    ublock-filters: 30139-169, 18h.55m
    ublock-privacy: 193-2, 18h.53m
    ublock-unbreak: 1704-39, 18h.51m
    urlhaus-1: 7743-0, 18h.49m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 418
  launchFromSelfie: true
popupPanel: 
  blocked: 40
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
To block ads on Yandex domains, need to use filter [Counters](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

See also: https://github.com/uBlockOrigin/uAssets/issues/7830
