### ISSUE TITLE
yandex.ru: breakage

### ISSUE THREAD

**Issue by trueTrueman** [uBlockOrigin/uAssets#11135]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://yandex.ru/`

### Category

breakage

### Describe the issue

There's a problem with blocking the ad in search suggestions on yandex.ru
So, normally, without an ad adblocker, Yandex shows you a relevant ad when you type in a keyword
![Screenshot_854](https://user-images.githubusercontent.com/53678740/147726413-9c354002-9ff8-4a49-91b8-61008eabf625.png)

After turning on uBO, the ad doesn't show up anymore, however it's not blocked completely, functionally it's still there meaning that if you press Down Arrow, it actually selects it, though it's not visible, and if you press Enter, it opens the advertised website.
In this example I only typed "леруа", the rest is autofilled suggestion from the ad when you select it.
![Screenshot_855](https://user-images.githubusercontent.com/53678740/147726578-76d70125-7d9a-49d5-afdf-c39ca78b4910.png)

That also causes inconvenience because you don't see the ad and don't expect it to be there and when you want to quickly autocomplete your request by pressing Down Arrow and expect it to select the first suggestion, after you hit Enter it suddenly opens the ad instead of performing the search. I hope you understand what I mean.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_855](https://user-images.githubusercontent.com/53678740/147726786-b336ed20-1990-4258-9d05-39667cbfbeb7.png)
![Screenshot_854](https://user-images.githubusercontent.com/53678740/147726788-1874b9cd-be04-4b5b-bc27-771a3e76c1c1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 104199
  cosmetic: 114074
  scriptlet: 20735
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1d.1h.42m
    fanboy-annoyance: 59144-180, 6d.15h.49m
    ublock-annoyances: 4345-130, 6h.4m
  default: 
    RUS-0: 40600-9, 1h.56m
    easylist: 62355-24, 6h.6m
    easyprivacy: 26569-114, 6h.2m
    plowe-0: 3681-821, 1h.58m
    ublock-abuse: 81-1, 2d.5h.1m
    ublock-badware: 3509-64, 2d.4h.59m
    ublock-filters: 30146-188, 2d.5h.7m
    ublock-privacy: 191-20, 2d.5h.5m
    ublock-unbreak: 1704-42, 2d.5h.3m
    urlhaus-1: 8445-0, 1d.1h.44m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 72 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 835
  launchFromSelfie: true
popupPanel: 
  blocked: 25
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/f987f59859910f3275019044fcee694bf3bde390

Discussion with the Yandex developer - [here](https://github.com/easylist/ruadlist/issues/27).
