### ISSUE TITLE
filecrypt.co: detection

### ISSUE THREAD

**Issue by ener445** [uBlockOrigin/uAssets#11131]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://filecrypt.co/Container/F90FDAB8C7.html`

### Category

detection

### Describe the issue

site keep asking to 
"Please disable AdBlock (cutcaptcha.com/.net)"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 80542
  cosmetic: 41408
  scriptlet: 16518
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 479-0, 6m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 3d.10h.29m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2641-1, 145d.3h.30m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 7h.49m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 4d.13h.30m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 62259-27, 3d.7h.39m
    easyprivacy: 26559-23, 1d.1h.14m
    plowe-0: 3690-811, 12d.15h.48m
    ublock-abuse: 72-0, 2d.15h.21m
    ublock-badware: 3570-64, 3d.7h.41m
    ublock-filters: 29856-162, 2d.15h.19m
    ublock-privacy: 193-2, 2d.15h.17m
    ublock-unbreak: 1738-39, 2d.10h.36m
    urlhaus-1: 8445-0, 7h.47m
filterset (user): [array of 242 redacted]
trustedset: 
  added: [array of 26 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  dynamicFilteringEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 505
  launchFromSelfie: false
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- remove these lists (provoking issues, no longer maintained)

![image](https://user-images.githubusercontent.com/10303732/147730610-1eda0f21-bb93-4de2-a5bb-07da3bb38fe0.png)
- disable other extensions
- test again
