### ISSUE TITLE
finanzen.net: popups

### ISSUE THREAD

**Issue by 1234k850i** [uBlockOrigin/uAssets#11136]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.finanzen.net/aktien/havn_life_sciences-aktie`

### Category

popups 
Cookies

### Describe the issue

Cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 82356
  cosmetic: 24285
  scriptlet: 16251
  html: 602
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30449-204, 3d.15h.35m
    ublock-badware: 3633-1, 3d.15h.34m
    ublock-privacy: 181-1, 3d.15h.33m
    ublock-abuse: 81-0, 3d.15h.32m
    ublock-unbreak: 1695-0, 3d.15h.31m
    adguard-mobile: 7012-176, 3d.15h.36m
    easylist: 62259-24120, 3d.15h.30m
    easyprivacy: 26552-495, 3d.15h.29m
    urlhaus-1: 8445-0, 19h.49m
    plowe-0: 3691-3, 11d.18h.56m
    DEU-0: 4992-370, 16h.45m
filterset (user): [array of 25 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 989 ms (selfie)
popupPanel: 
  blocked: 15
```
</details>

**Comment by mapx-** [comment]
popups ? are you talking about cookies / gdpr box ? => we are not adding filters for that case

**Comment by okiehsch** [comment]
The gdpr modal can be removed by enabling the  Fanboy Annoyance list or add
`||scripts.finanzen.net/js/cmp/cmp.min.js$script,1p`
to your filter list, you will have to load the site bypassing the cache in both cases one time.
