### ISSUE TITLE
consent.yahoo.com: nuisance

### ISSUE THREAD

**Issue by gitbobbed** [uBlockOrigin/uAssets#11133]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_81308508-9bbf-46a4-8ec8-406b0cb6ce70`

### Category

nuisance

### Describe the issue

Crappy Yahoo cookie overlay seems to be unblockable =/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33555741/147717252-6b446c81-5551-4041-a74c-bc4078cd366a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 89625
  cosmetic: 145968
  scriptlet: 21307
  html: 621
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48688-4089, now
    adguard-social: 15323-14, now
    fanboy-annoyance: 62184-4256, 18m
    ublock-annoyances: 4354-4, now
  default: 
    ublock-filters: 30639-34, 19m
    ublock-badware: 3652-1, 18m
    ublock-privacy: 181-0, 18m
    ublock-abuse: 81-0, 18m
    ublock-unbreak: 1717-0, 18m
    easylist: 62362-574, 18m
    easyprivacy: 26569-483, 18m
    urlhaus-1: 7695-0, 18m
    plowe-0: 3681-3, 18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 290 ms (selfie)
popupPanel: 
  blocked: 34
```
</details>

**Comment by uBlock-user** [comment]
GDPR, we don't block those modals.

**Comment by krystian3w** [comment]
Cookie wall.
