### ISSUE TITLE
zee5.com: privacy

### ISSUE THREAD

**Issue by vtryp** [uBlockOrigin/uAssets#11138]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.zee5.com/hi/movies/details/antim-the-final-truth/0-0-1z562203`

### Category

privacy

### Describe the issue

Problem playing content, possible external display detected. video is not playing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/96876412/147759823-7d71d7eb-8cb2-40a4-9f17-10acecd9e228.png

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78446
  cosmetic: 41471
  scriptlet: 19170
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4346-7, 2h.48m
  default: 
    easylist: 62348-8, 1d.47m
    easyprivacy: 26566-17, 1d.45m
    plowe-0: 3679-816, 2d.21h.51m
    ublock-abuse: 81-0, 1d.43m
    ublock-badware: 3509-64, 1d.41m
    ublock-filters: 30135-138, 1d.39m
    ublock-privacy: 189-7, 1d.37m
    ublock-unbreak: 1734-39, 1d.35m
    urlhaus-1: 7737-0, 1d.33m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 780
  launchFromSelfie: true
popupPanel: 
  blocked: 39
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce, video plays fine on my side. You have custom filters, did you verify that these are not the cause?

**Comment by mapx-** [comment]
Turn OFF any other extension, test again

**Comment by Yuki2718** [comment]
Can you play the video if you turn uBO off?

**Comment by GimmeDemJigglypuffs** [comment]
Issue has resumed after months of having no problems. Any free content (except for movie trailers) doesn't play as long as uBO is active. If I disable uBO, the media on the website plays. I'm able to watch the content using Brave browser with its built-in adblocking without any problem (no extensions). In the presence of uBO on Firefox, the player loads, but the media doesn't (screenshots below). 

I've used these versions to test:
Firefox version: 109, Brave version: [Version 1.47.171 Chromium: 109.0.5414.87]

The URL I used to test: 
https://www.zee5.com/movies/details/white-haired-devil-lady/0-0-1z5233998

Additional information:
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 120285
  cosmetic: 205398
  scriptlet: 34021
  html: 851
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.9h.47m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 8491-0, 247d.25m
    adguard-generic: 67787-4203, 2d.7h.8m
    adguard-mobile: 8699-179, 2d.7h.10m
    adguard-annoyance: 62653-618, 2d.7h.7m
    fanboy-annoyance: 86336-5207, 2d.13m
  default: 
    user-filters: 25-0, never
    ublock-filters: 32488-38, 2d.7h.5m
    ublock-badware: 4329-0, 2d.7h.9m
    ublock-privacy: 304-0, 7d.5h.21m
    ublock-abuse: 77-0, 7d.5h.22m
    ublock-unbreak: 1937-0, 2d.7h.6m
    easylist: 62312-1553, 1d.10h
    easyprivacy: 30950-1856, 6h.48m
    plowe-0: 3666-2, 5d.9h.44m
    urlhaus-1: 6900-2410, 54m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5120 ms (selfie)
  maxAssetCacheWait: 454 ms


(Screenshot 1) On Firefox with uBO - content fails to load:
![Untitled](https://user-images.githubusercontent.com/123256589/213875380-2e3d5760-98c6-436d-b9da-2ab9b5ace346.jpg)


(Screenshot 2) Same URL on Brave produces no problem:
![Untitled](https://user-images.githubusercontent.com/123256589/213875662-5a17109f-2153-4d1e-bd67-ddc401d3e64f.jpg)

**Comment by mapx-** [comment]
You link seems to be broken

I tested the above link
`https://www.zee5.com/hi/movies/details/antim-the-final-truth/0-0-1z562203`

and it's ok

Do I need an account ?

However, you should test using a defauplt setup.
See also:

- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by ghajini** [comment]
all ok on my end
