### ISSUE TITLE
podcasty.seznam.cz: breakage

### ISSUE THREAD

**Issue by nr1jack** [uBlockOrigin/uAssets#11144]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://podcasty.seznam.cz/podcast/osobnost-plus/konvalinka-omikron-je-dramaticky-nakazlivy-je-potreba-zkratit-karanteny-nebo-se-zeme-zastavi-48875`

### Category

breakage

### Describe the issue

missing podcast

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obrazek](https://user-images.githubusercontent.com/37784391/147792108-149999e2-247b-49bf-949f-46da61dc6ffa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 97
filterset (summary): 
  network: 78530
  cosmetic: 40483
  scriptlet: 16616
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-29, 2d.3h.21m
    ublock-badware: 3543-1, 2d.3h.18m
    ublock-privacy: 181-0, 2d.3h.16m
    ublock-abuse: 72-0, 2d.3h.14m
    ublock-unbreak: 1721-0, 2d.3h.12m
    easylist: 62342-569, 2d.3h.10m
    easyprivacy: 26558-487, 2d.3h.8m
    urlhaus-1: 7938-0, 23h.41m
    plowe-0: 3679-3, 2d.3h.27m
    CZE-0: 776-0, 23h.39m
filterset (user): [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4122 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by krystian3w** [comment]
Regional list cannot fix this in 3 days?

**Comment by mapx-** [comment]
add

`@@||browser.sentry-cdn.com/*/bundle.min.js$script,domain=podcasty.seznam.cz`

EP issue, @ryanbr

**Comment by krystian3w** [comment]
Why  can not EasyList 🇨🇿 and 🇸🇰 no test this and his hands report to EL?

**Comment by mapx-** [comment]
> Why can not EasyList 🇨🇿 and 🇸🇰 test this and his hands report to EP?

it's EasyPrivacy
