### ISSUE TITLE
elixx.xyz: popups

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#11143]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://elixx.xyz/porto.html?sport=soccer`

### Category

popups

### Describe the issue

When you press the video player an about:blank pop-up shows up

Possible solution: `elixx.xyz##+js(acis, String.fromCharCode, break;case)` or any variant of this, possibly using Math or JSON.Parse

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 78333
  cosmetic: 41522
  scriptlet: 19164
  html: 628
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4354-4, 3h.20m
  default: 
    ublock-filters: 30647-32, 3h.20m
    ublock-badware: 3657-1, 3h.20m
    ublock-privacy: 181-0, 3h.20m
    ublock-abuse: 81-0, 3h.20m
    ublock-unbreak: 1717-0, 3h.20m
    easylist: 62414-575, 3h.20m
    easyprivacy: 26574-482, 3h.20m
    urlhaus-1: 7533-0, 3h.20m
    plowe-0: 3681-3, 3h.20m
filterset (user): [array of 51 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 137 redacted]
hostRuleset: 
  added: [array of 385 redacted]
urlRuleset: 
  added: [array of 104 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 573 ms (selfie)
popupPanel: 
  blocked: 25
```
</details>

**Comment by Alphamen16** [comment]
@mapx- maybe if you try to load into the site using a private window? It's not too much of a nuisance anyway, i can probably find the right filter to stop it but if it could be a general rule in the UBO filters, all the better

**Comment by okiehsch** [comment]
Does adding 
`elixx.xyz##^script:has-text(0x3)`
to your filter list work for you?

**Comment by uBlock-user** [comment]
```
elixx.*##+js(acis, addEventListener, -0x)
||ktaueavyp.com^
||kkygdqoncvwdq.com^
```

for complete solution.

`||elixx.*/popcash.js^` for added measure.

**Comment by okiehsch** [comment]
It's Firefox only, so no need for `##+js(acis, addEventListener, -0x)` imo.
`elixx.*##+js(aopw, _pop) already disables it for chromium browsers.

**Comment by uBlock-user** [comment]
The issue is not present in Chromium ?

**Comment by okiehsch** [comment]
No, like I said `elixx.*##+js(aopw, _pop)` already fixes it.
The `ktaueavyp.com` and `kkygdqoncvwdq.com` requests are not present in chromium umless you disable `elixx.*##+js(aopw, _pop)`.

**Comment by uBlock-user** [comment]
> The ktaueavyp.com and kkygdqoncvwdq.com requests 

Blocking those domains so third-party popups can be avoided elsewhere.

**Comment by Alphamen16** [comment]
Thanks guys, the fix @okiehsch suggested worked. I had actually tried that filter before but using the word "blank" instead of "0x3" and it failed. Why was that if that word is used in the script, can you guys tell me?

Anyway, happy new year everyone, thanks again!

**Comment by gorhill** [comment]
`blank` should work as well, if you show us the exact filter you tried, we will be able to tell you why it didn't work.

**Comment by okiehsch** [comment]
No, I was stumped by the same thing, I can still reproduce with Firefox, 
`elixx.xyz##^script:has-text(blank)`
does not work at `https://elixx.xyz/porto.html?sport=soccer` for me.
`elixx.xyz##^script:has-text(0x3)` works.

**Comment by okiehsch** [comment]
The filter I first tried was `elixx.xyz##^script:has-text(_0x)` and that does not work either.

**Comment by gorhill** [comment]
Unexpected, I am going to investigate.

**Comment by Alphamen16** [comment]
@gorhill 

just to double down and make sure it's not a singularity, what @okiehsch said was exactly what i experienced. Don't know why but i'm very curious to see if we can work it out :)

**Comment by okiehsch** [comment]
Both filter are correctly applied according to the logger.
![image](https://user-images.githubusercontent.com/16838044/147828179-e5ad8ebe-3a6c-4a56-b34a-0b0e2975b0f4.png)

As you can see with `elixx.xyz##^script:has-text(_0x)` the `ktaueavyp.com` and `kkygdqoncvwdq.cmom` are still present.
with ``elixx.xyz##^script:has-text(_0x)` they are gone as expected.

**Comment by gorhill** [comment]
I just checked and `elixx.xyz##^script:has-text(blank)` works fine, it's reported in the logger, stepping into the code shows the script node is removed, and looking at `view-source:https://elixx.xyz/porto.html?sport=soccer` confirms the script node is gone.

**Comment by okiehsch** [comment]
>  looking at view-source:https://elixx.xyz/porto.html?sport=soccer confirms the script node is gone.

I agree the script is gone here too but the `ktaueavyp.com` and `kkygdqoncvwdq.com` requests are still theres.

**Comment by gorhill** [comment]
Well on my side I see a suspicious script included at the end which may be the cause, `//terribledeliberate.com/82/db/e4/82dbe4493f9a49aa204a97bf85fd2cc6.js`.

**Comment by okiehsch** [comment]
That's blocked look at my logger screenshot.

**Comment by gorhill** [comment]
Note that yesterday when I tried to reproduce, I did succeed on the first try, but after this I was not able to reproduce anymore, despite clearing cookies etc. So maybe there is more than one code path for the popup's code, and actually `elixx.xyz##^script:has-text(blank)` does work for one path, but not for the other(s).

**Comment by Alphamen16** [comment]
that's probably it then, because `_0x ` doesn't fix the issue either but `0x ` or in this case `0x3 ` does work, meaning that it's common to all paths right?

**Comment by okiehsch** [comment]
> . So maybe there is more than one code path for the popup's code, and actually elixx.xyz##^script:has-text(blank) does work for one path, but not for the other(s).

Would that not contradict the finding that in `view-source:https://elixx.xyz/porto.html?sport=soccer` the popup script is gone and the `ktaueavyp.com` are still there? 
If they used a differeent code path we should still see some inline-script that triggers those requests but there is nothing,
And I blocked all third and first party scripts on the site to narrow it down.
Those requests are caused by the inline-script.

**Comment by gorhill** [comment]
I can reproduce well enough now when I use the "Clear data..." feature in Firefox settings -- this also get rid of cached content. I after a couple of try, it does seem that `ktaueavyp.com` shows up with `:has-text(blank)`, but not `:has-text(0x)`.

I think it's because the site loads a 1p frame, `view-source:https://elixx.xyz/aw/porto.php`, and the filter `:has-text(blank)` does not filter anything in that frame, but `:has-text(0x)` does.

**Comment by uBlock-user** [comment]
> and the filter :has-text(blank) does not filter anything in that frame

It should, the same inline-script is present at `https://elixx.xyz/aw/porto.php`

**Comment by gorhill** [comment]
> the same inline-script is present

<details><summary>Not on my side</summary>

```js
/*<![CDATA[/* */
(function(){var c83e93cc81b9a1f85097dbde10829460="EQcWq3XBEIbDVJQE687R4FzDq7-DxA1wXWI2R8MR28SvQrZC2ruDQGI4K2MzdY60d_a4zTqaXqESmJi0ZQ6YzHdDkA";var a=['dsO6K8O3w6jCmcOBOMOmEBjCgcKXBA7Dj2EYw5BHwrcJwq7CsDcrwo7Cvg==','ZyPDn13Dq14=','w5UeJcKmwqDDgcOkbcOTw4bClcO1w6zCk3vDomIhTSzClcOF','w4PCsnlXRzIjw5s=','w6tQJyI=','N8OOwpE=','w5vDksK+QcOc','VsO1B8KVfCpqwow=','w7AZZsOjw4BAwro=','w69FRsK6w73Du3/Cq8K0cHDCjg==','w4vCucOjGw==','w5LDrgVPw77DmDTCr8OoSljDqQ==','w5lJJhDDvBI=','UQ5sw47DssK5Tw==','w4nDiMKzSsO2w7I=','VAVlw4HDvsK4VMKoLw==','w7nCucOvLQ5pacKMwoTCrmVywq5BwpwdQFbDh8Ke','CW0fw4LCr8KSwpM5w5XCgw==','w7rDr8O4BwY0NMKdwoLCtCFBwrlxw5MZYljDn8KfwoIow7N6YsOrwpttw6DDkjIOw5V2QcKOw5nDtnTDhMKAw5gywps=','WsOkFcKEenwxw7PCs3EVH8KX','w54bGcK8OF5lfA==','wq9NMg==','RQR6w5rDqcKxXsKvLxJwSsK2bg==','dy5DVcOEH8KhMXvDixjDgg==','DnsawonCoMKIwqk/w5DCgsKbw7rCuMKLBlw6wo5pJcOyEmFUwol5CCdpw4jDocK7wp7CvTYqAsOIwrJswrM+FA==','dzLDgkfDqGXCuX3Cq8KeBw==','w6hJRMK+w6LDvA==','w5dZWsOeSMOowpLDksK8w7EDwpQ/QlI=','w5XDuQxPw7PDvxTCt8O6QljDqRA='];(function(b,c){var d=function(g){while(--g){b['push'](b['shift']());}};d(++c);}(a,0xa9));var b=function(c,d){c=c-0x0;var e=a[c];if(b['dfwIJG']===undefined){(function(){var h;try{var j=Function('return\x20(function()\x20'+'{}.constructor(\x22return\x20this\x22)(\x20)'+');');h=j();}catch(k){h=window;}var i='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';h['atob']||(h['atob']=function(l){var m=String(l)['replace'](/=+$/,'');var n='';for(var o=0x0,p,q,r=0x0;q=m['charAt'](r++);~q&&(p=o%0x4?p*0x40+q:q,o++%0x4)?n+=String['fromCharCode'](0xff&p>>(-0x2*o&0x6)):0x0){q=i['indexOf'](q);}return n;});}());var g=function(h,l){var m=[],n=0x0,o,p='',q='';h=atob(h);for(var t=0x0,u=h['length'];t<u;t++){q+='%'+('00'+h['charCodeAt'](t)['toString'](0x10))['slice'](-0x2);}h=decodeURIComponent(q);var r;for(r=0x0;r<0x100;r++){m[r]=r;}for(r=0x0;r<0x100;r++){n=(n+m[r]+l['charCodeAt'](r%l['length']))%0x100;o=m[r];m[r]=m[n];m[n]=o;}r=0x0;n=0x0;for(var v=0x0;v<h['length'];v++){r=(r+0x1)%0x100;n=(n+m[r])%0x100;o=m[r];m[r]=m[n];m[n]=o;p+=String['fromCharCode'](h['charCodeAt'](v)^m[(m[r]+m[n])%0x100]);}return p;};b['ylotgO']=g;b['KBTmxq']={};b['dfwIJG']=!![];}var f=b['KBTmxq'][c];if(f===undefined){if(b['AshJvI']===undefined){b['AshJvI']=!![];}e=b['ylotgO'](e,d);b['KBTmxq'][c]=e;}else{e=f;}return e;};var j=window;j[b('0x9','7NXb')]=[[b('0x13','t(78'),0x44f8af],[b('0x11','7NXb'),0.001],[b('0x1b','PSCm'),b('0x1a','XR0$')],[b('0x10','6$d^'),0x0],[b('0x12','PSCm'),![]],[b('0x18','7TnE'),0x0],[b('0xe','G)ls'),!0x0]];var g=[b('0x0',')w]r'),b('0x17','#Hg)'),b('0x7','H]$n'),b('0x5','g!#K')],n=0x0,c,d=function(){if(!g[n])return;c=j[b('0x19','JSWa')][b('0x4','6$d^')](b('0x6','iH4C'));c[b('0xf','lSjX')]=b('0x3','(J*@');c[b('0xb','t(78')]=!0x0;var f=j[b('0x8','U^et')][b('0x15','#Hg)')](b('0x2','G)ls'))[0x0];c[b('0xa','o3xd')]=b('0xc','7TnE')+g[n];c[b('0x1','iH4C')]=b('0x14','PSCm');c[b('0xd','XR0$')]=function(){n++;d();};f[b('0x16',')w]r')][b('0x1c','Xl2K')](c,f);};d();})();
/*]]>/* */
```
</details>

**Comment by okiehsch** [comment]
Makes sense, with that inline-script `blank` and `_0x` won't work but `0x3` does

**Comment by uBlock-user** [comment]
Hmmm, they must be serving alternative versions of script then.

**Comment by Alphamen16** [comment]
I agree, that seems to explain the issue. This is super interesting.

By the way, the filter that was applied to the UBO filter list has 0x3 but perhaps 0x would be the preferable one? Unless it breaks other things needed for the site to work (unllikely)

**Comment by okiehsch** [comment]
I used `0x3` instead of `0x` to lessen the likelyhood of site breakage.
As long as it works it's fine imo.
