### ISSUE TITLE
zhangxinxu.com: detection

### ISSUE THREAD

**Issue by teatube** [uBlockOrigin/uAssets#11148]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.zhangxinxu.com/wordpress/2015/11/diff-word-break-break-all-word-wrap-break-word/`

### Category

detection

### Describe the issue

show an ad when ublock opens

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 95108
  cosmetic: 50169
  scriptlet: 16457
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-29, 4h.3m
    ublock-badware: 3658-1, 4h.7m
    ublock-privacy: 181-0, 4h.9m
    ublock-abuse: 72-0, 4h.8m
    ublock-unbreak: 1689-0, 4h.4m
    easylist: 62433-580, 4h.2m
    easyprivacy: 26573-482, 4h.10m
    urlhaus-1: 7612-0, 4h.1m
    plowe-0: 3679-3, 4d.8h.9m
    CHN-0: 27184-134, 4h.6m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 468 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
```
zhangxinxu.com#@#.sldebar_out + *,style[id] + a[class]
zhangxinxu.com##.sldebar_out + *,style[id] + a[class]:style(height: 1px !important)
```

@Yuki2718

**Comment by uBlock-user** [comment]
checks for `display:` property, `zhangxinxu.com##.sldebar_out + *,style[id] + a[class]:style(height: 0px !important)` will do.

**Comment by Yuki2718** [comment]
On my end `##style[id] + a[class]` has no hit.
