### ISSUE TITLE
cocomanga.com Anti-Adblock

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#11140]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.cocomanga.com/

### Describe the issue

Example: `https://www.cocomanga.com/16465/1/153.html`

On loading pages, after a while, content is removed with a message:

> 浏览器屏蔽了重要元件无法加载页面，请确保没有开启任何小插件，影响页面加载！ 实在不行请更换浏览器！ 推荐 Chrome。 有网友反馈nod32 之类的杀软也会屏蔽一些东西

Google translate:

> The browser blocks important components and cannot load the page. Please make sure that no small plug-ins are turned on, which will affect the page loading! If it doesn't work, please change your browser! Recommend Chrome. Some netizens reported that anti-virus like nod32 will also block some things 

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 97.0a1

### Settings

default settings

**Comment by okiehsch** [comment]
> Google translate:
The browser blocks important components and cannot load the page. 

Well, is some site functionality blocked?
 I don't speak the language, so hard for me to tell.

**Comment by Yuki2718** [comment]
@okiehsch Do you see the anti-adb with Chinese filters enabled? I see only disabled.

**Comment by Yuki2718** [comment]
@erosman Test with AdGuard Chinese enabled.

**Comment by okiehsch** [comment]
I did not check Adguard Chinese my bad, that filter can be removed.
The break-case filter is needed on my end.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11095

**Comment by erosman** [comment]
Does it require additional filters to be enabled?
What is AdGuard Chinese?
I only see 
- AdGuard Annoyances
- AdGuard Social Media

**Comment by Yuki2718** [comment]
> Does it require additional filters to be enabled? What is AdGuard Chinese? I only see

AG Chinese is under Regions, languages. Since this is a Chinese site, users are expected to have it enabled.

**Comment by erosman** [comment]
I have reported this site multiple times before and every time the fix was done in the main filters.

**Comment by Yuki2718** [comment]
> I have reported this site multiple times before and every time the fix was done in the main filters.

I guess that was before we replace our Chinese filters with the AG one which can use extended syntax.

**Comment by uBlock-user** [comment]
> I have reported this site multiple times before

That's when the site wasn't fixed in AG Chinese list. We don't add filters if the site is fixed in the regional list.
