### ISSUE TITLE
9gag.com: How to block "sponsored" content without breaking the webpage

### ISSUE THREAD

**Issue by Heralda** [uBlockOrigin/uAssets#11142]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://9gag.com/`

### Category

ads

### Describe the issue

This site has a sidebar on the right side of the screen, with links to sponsored posts. If you use the "pick" tool to block the entire sidebar, and then try to open some user's profile, the webpage will start reloading itself ad-infinitum using up tonnes of system resources.

But... if you add the following to your filters, the sidebar's sponsored content gets blocked without making the browser unstable.
9gag.com###sidebar-content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/10226418/147782973-b9bfafc1-7152-4c1a-9d52-abf3b37e1f97.png

https://user-images.githubusercontent.com/10226418/147783030-4d9d01d8-ed28-421b-8db0-a30a44f05cc4.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78272
  cosmetic: 40008
  scriptlet: 16204
  html: 596
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30308-29, 1d.6h.46m
    ublock-badware: 3635-1, 1d.6h.45m
    ublock-privacy: 181-0, 1d.6h.44m
    ublock-abuse: 81-0, 1d.6h.43m
    ublock-unbreak: 1689-0, 1d.6h.42m
    easylist: 62348-564, 1d.6h.41m
    easyprivacy: 26566-484, 1d.6h.40m
    urlhaus-1: 7743-0, 21h.15m
    plowe-0: 3717-3, 7d.16h.53m
filterset (user): [array of 38 redacted]
trustedset: 
  added: [array of 89 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 237 ms (selfie)
popupPanel: 
  blocked: 43
```
</details>

**Comment by krystian3w** [comment]
Better asking on reddit.com if you don't report simple block for EasyList (trouble then no needed is use scriptlets and ExtendedCss/procedural cosmetic filters).

**Comment by krystian3w** [comment]
Maybe these hide better and no froze page:

    9gag.*###sidebar section > h4:has-text(Feature):upward(1)

**Comment by u-RraaLL** [comment]
The problematic filter seems to be `.sticky`. There's no problem when hiding either `#sidebar` or `#sidebar-content`.

> IMO this ads no worth block in "uBo Annoyances" or stock "filters.txt".

No, I don't think it is. In fact, is "featured" even the same thing as "sponsored"?

The actual ad is already blocked, only its label remains.

**Comment by uBlock-user** [comment]
Featured posts are site's own posts, not ads.
