### ISSUE TITLE
[nsfw] pnrtscr.com: fullscreen popup

### ISSUE THREAD

**Issue by PipoCrazy** [uBlockOrigin/uAssets#11147]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://pnrtscr.com/`

### Category

popups

### Describe the issue

Jumpscare on accept.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Chromium: 96
filterset (summary): 
  network: 81824
  cosmetic: 44542
  scriptlet: 16589
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.9h.13m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 62310-8, 3d.6h.42m
    easyprivacy: 26556-17, 3d.6h.40m
    plowe-0: 3715-818, 6d.6h.57m
    spa-0: 3567-21, 2h.55m
    spa-1: 4171-159, 3d.4h.52m
    ublock-abuse: 81-0, 2d.5h.59m
    ublock-badware: 3631-65, 3d.4h.50m
    ublock-filters: 30060-196, 2d.6h.19m
    ublock-privacy: 184-2, 2d.6h.17m
    ublock-unbreak: 1712-41, 2d.4h.36m
    urlhaus-1: 8445-0, 2h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 449 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
```
Abusing users' trust in cookie ...
https://github.com/mathhulk/pnrtscr.com
```

`||pnrtscr.com/video.mp4$media,1p`
or
`||pnrtscr.com^$csp=script-src *`

**Comment by mapx-** [comment]
@gorhill using "click to block all popups .." does not help for this API

**Comment by krystian3w** [comment]
Page have csp bug without enabled uBo.

**Comment by gorhill** [comment]
This is not a popup, and we don't have filters to prevent sites from using full screen, and the `popup` filters/rules should never be used for this purpose, that would be unexpected behavior.

**Comment by gorhill** [comment]
By the way, Dan Pollock's list has a section for "shock sites", so this could be reported to the maintainer of that list.
