### ISSUE TITLE
Create a new filter list to block content farms

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#11154]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://yuanmacha.com/15258469165.html`

### Describe the issue

These pages are content farms which are worthless and a waste of time (for more information, see - `https://en.wikipedia.org/wiki/Content_farm`). Therefore, I think it would be better to add such sites to uBlock filters - Annoyances, or create a separate filter list to block them. Thanks!

### uBlock Origin version

v1.38.4

### Browser name and version

Microsoft Edge 95.0.1020.44 (64-bit)

### Settings

_No need_

**Comment by gorhill** [comment]
The way this work is that instead of asking us to create a new filter list, you actually create a new filter list, and if eventually the demand is high for such list, we might consider including it in stock filter lists.
