### ISSUE TITLE
microcenter.com: breakage

### ISSUE THREAD

**Issue by FriendlyStuart** [uBlockOrigin/uAssets#11158]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.microcenter.com/`

### Category

breakage

### Describe the issue

Not sure if falls under the "breakage" category but uBlock disables the online chat tech support functionality. It not only hides the quick access icon that's on the bottom left of any different but also on the help center (https://www.microcenter.com/site/customer-support/help-center.aspx) or any page with a link to open the online chat tech support when clicking on "chat with a live person" link will not work till uBlock is disabled 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![dnw](https://user-images.githubusercontent.com/96928908/147841723-aa0192bf-ef74-493a-9e8e-397f69f987f5.PNG)
![missing](https://user-images.githubusercontent.com/96928908/147841724-b207b8ce-4fdc-4c00-8365-24a6d48202ba.PNG)
![there](https://user-images.githubusercontent.com/96928908/147841726-baa8e3d3-4eab-4a78-9ee5-7c97fba35dc6.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Chromium: 96
filterset (summary): 
  network: 79193
  cosmetic: 39979
  scriptlet: 16258
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62373-8, 1d.20h.16m
    easyprivacy: 26568-17, 1d.20h.14m
    plowe-0: 3679-816, 3d.6h.6m
    ublock-abuse: 81-0, 1d.20h.12m
    ublock-badware: 3631-65, 1d.20h.10m
    ublock-filters: 29776-132, 1d.20h.8m
    ublock-privacy: 184-3, 1d.20h.6m
    ublock-unbreak: 1706-39, 1d.20h.4m
    urlhaus-1: 8656-0, 20h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3786 ms
popupPanel: 
  blocked: 8
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
`@@||googletagmanager.com/gtm.js$script,domain=microcenter.com´
