### ISSUE TITLE
watch.plex.tv: breakage

### ISSUE THREAD

**Issue by MoiPadilla** [uBlockOrigin/uAssets#11159]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://watch.plex.tv/movie/secretary`

### Category

breakage

### Describe the issue

Player reproduces only audio in classic version, and does not load with the page's beta version (which some users suggested as a workaround to ad-blocking breaking the page).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77981
  cosmetic: 39645
  scriptlet: 16205
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 61633-7, 20d.20h.52m
    easyprivacy: 26483-17, 20d.20h.42m
    plowe-0: 3687-809, 20d.20h.32m
    ublock-abuse: 72-0, 20d.20h.28m
    ublock-badware: 3565-61, 20d.20h.24m
    ublock-filters: 29782-128, 20d.20h.22m
    ublock-privacy: 189-2, 20d.20h.20m
    ublock-unbreak: 1704-39, 20d.20h.18m
    urlhaus-1: 7922-0, 20d.20h.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 137
  launchFromSelfie: true
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
tested on freemovie

`https://watch.plex.tv/movie/sherlock-jr`

working:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=watch.plex.tv`

**Comment by mapx-** [comment]
@ryanbr
