### ISSUE TITLE
Three scam/malicious domains 

### ISSUE THREAD

**Issue by D4v1dH03** [uBlockOrigin/uAssets#11157]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://sideload.net
https://stcverify.com
https://verify.stc.tools
```

### Describe the issue

Those three domains are scam sites and either:
1. Does survey scam
2. Trick users into downloading unwanted software/another extension

They deliberately use infinite loop debugger statement to prevent debugging and obfuscate their JS code.
And are not blocked by the uBlock default badware risk list

### Screenshot(s)

<img width="1440" alt="Screenshot 2021-12-31 at 13 41 37" src="https://user-images.githubusercontent.com/81270448/147839554-2de2542d-245c-4930-8b3f-ccc930dd05ed.png">

<img width="1440" alt="Screenshot 2021-12-31 at 13 41 59" src="https://user-images.githubusercontent.com/81270448/147839553-964f9d13-6146-45fb-81fd-e3984c36611b.png">

<img width="1440" alt="Screenshot 2021-12-31 at 13 42 15" src="https://user-images.githubusercontent.com/81270448/147839556-6eec40ee-c057-4564-a9ff-2c376764cf21.png">

### uBlock Origin version

1.40.2

### Browser name and version

Brave Nightly 1.36.9 (Chromium: 97.0.4692.56 (Official Build) nightly (arm64))

### Settings

None

### Notes

Also reproduces while Brave shields is disabled and ONLY uBlock Origin enabled

**Comment by Volker-Weissmann** [comment]
https://stctools.com is 404 on my machine

**Comment by D4v1dH03** [comment]
> https://stctools.com is 404 on my machine

Sorry made a typo. It is `stcverify.com`

**Comment by Volker-Weissmann** [comment]
Ok, my PR should fix it

**Comment by mapx-** [comment]
@ryanbr

**Comment by iam-py-test** [comment]
Maybe add `1980s.click` as these redirect domains seem to be reused.
![image](https://user-images.githubusercontent.com/84232764/147880149-e469a4be-5cca-4ad5-bb86-1a8a14417784.png)

**Comment by krystian3w** [comment]
@curbengh maybe worth for default url-hause list?

**Comment by Volker-Weissmann** [comment]
> 1980s.click

Done

**Comment by D4v1dH03** [comment]
As well as `0x41414141.net` where all malicious scripts are served

**Comment by iam-py-test** [comment]
Thanks @D4v1dH03. I'v added them to my lists

**Comment by D4v1dH03** [comment]
another one : sideload[.]cc
