### ISSUE TITLE
realgfporn.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1115]
URL(s) where the issue occurs

https://www.realgfporn.com/videos/hot-gf-was-made-for-sex-215797.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
