### ISSUE TITLE
myabandonware.com - another case

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#11153]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.myabandonware.com/game/the-house-of-the-dead-bed`

### Describe the issue

Two spaces, one above the yellow download button and the other that is above the blue download buttons arent removed. This happens in every page where there are games to download, not only the page reported.

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 95

### Settings

The settings are ok.

**Comment by gorhill** [comment]
These can be fixed in EasyList if they agree this is something to fix:

    myabandonware.com##[id*="myabandonware_"][id$="tf"]

cc @ryanbr, @Khrin

**Comment by uBlock-user** [comment]
We already have filters for this site, so we should add the filters for this case too

**Comment by okiehsch** [comment]
>We already have filters for this site, so we should add the filters for this case too

Yes. 
If we for example fix a site because of an anti adblock issue we do fix all ad related issues for that site, including placeholders.

**Comment by gorhill** [comment]
Hmm you're right, so the issue here should just have been added to the already existing issue.

**Comment by okiehsch** [comment]
If EasyList adds your suggested filter it's redundant for uBlock users and we don't add it.

**Comment by gorhill** [comment]
@Felipefpl I am going to ask you to respect this:

> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

You should have just added to the other issue, not open a new issue for this.

**Comment by Felipefpl** [comment]
> @Felipefpl I am going to ask you to respect this:
> 
> > * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
> 
> You had already opened [three similar issues before](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+myabandonware.com). You should have just added to the other issue (which you opened yourself), not open a new issue for this.

Sorry for that, i'll post only in this thread from now on.

Found more ads' spaces in the site here https://www.myabandonware.com/game/ and here above the mac download https://www.myabandonware.com/game/3-d-ultra-pinball-creep-night-3fh

**Comment by AroKol78** [comment]
to the last comment
use my old filter
`##div[id$="CBM"]`
and my new
`##div[class$="-1"]`
`##div[class$="-2"]`
`##div[class$="-3"]`

**Comment by gorhill** [comment]
The site changes the class/id constantly it appears, something possibly more resilient:

    myabandonware.com##script:has-text(slotId):upward(div)

**Comment by AroKol78** [comment]
does not work on `/game/`

**Comment by gorhill** [comment]
myabandonware.com##script:has-text(enabled_slots):upward(div)

**Comment by mapx-** [comment]
`myabandonware.com##div:matches-css-after(content:/Ads/)`

**Comment by AroKol78** [comment]
`https://www.myabandonware.com/game/`
👍 `##div:matches-css-after(content:/Ads/)`

`https://www.myabandonware.com/game/3-d-ultra-pinball-creep-night-3fh`
both work 👍 `##script:has-text(enabled_slots):upward(div)` or 👍 `##script:has-text(slotId):upward(div)`

**Comment by Felipefpl** [comment]
> `https://www.myabandonware.com/game/` 👍 `##div:matches-css-after(content:/Ads/)`
> 
> `https://www.myabandonware.com/game/3-d-ultra-pinball-creep-night-3fh` both work 👍 `##script:has-text(enabled_slots):upward(div)` or 👍 `##script:has-text(slotId):upward(div)`

This was added on easylist or fanboy?

**Comment by AroKol78** [comment]
has not been added anywhere yet (can be added to "My filters")

**Comment by Felipefpl** [comment]
> has not been added anywhere yet (can be added to "My filters")

I see, thanks for your help and for the help of everyone involved.

**Comment by Felipefpl** [comment]
I got a strange situation here, i thought ublock was blocking the download button of this game (i didnt see the msg where the game wasnt available then) - i disabled ublock to see if i could see the download button but after i did this the browser got frozen, it doesnt happen if ublock is not installed, link below:

https://www.myabandonware.com/game/the-summoning-1it

**Comment by AroKol78** [comment]
`....com/game/elvira-ii-the-jaws-of-cerberus-2md` (empty space on the right)
working (from `easylist/easylist/issues/9044#issuecomment-999792899`)
`....com##div[id$="ST"]`
`....com##div[id$="SB"]`
`....com##div[id$="STD"]`

disable unnecessary ad loading (info `easylist/easylist/issues/7053#issuecomment-766722098`)
`||....com/media/img/wgm/`
`||....com/media/img/gog/`
`||....com/media/img/pwn/`

**Comment by Felipefpl** [comment]
The Amiga/Atari ST sections below have ads spaces that arent removed by the existing rules:

https://www.myabandonware.com/game/prince-of-persia-pd

**Comment by Felipefpl** [comment]
New ads were put recently in the page that arent blocked:

https://www.myabandonware.com/game/requiem-final-ihx

**Comment by AroKol78** [comment]
the restoration helped me `myabandonware.com##[href^="/visual/"]` (https://github.com/uBlockOrigin/uAssets/commit/bcb6f23ecbd8081a1d708bcbf2a6bd42ed99a7d6)

**Comment by Felipefpl** [comment]
Thanks for fixing this mapx. Also thanks to all who helped too.

**Comment by Felipefpl** [comment]
Hi, i'm replying to this because easylist stopped removing the ads' spaces (ads are blocked) and also with the hope someone will take a look at this.

**Comment by BlocksAds** [comment]
`myabandonware.com##[align="center"]:has-text(freestar.config.)`

**Comment by Felipefpl** [comment]
Oops, i should have mentioned there are several spaces in the middle/right side of the site. My bad. Here is an example:

https://www.myabandonware.com/game/the-house-of-the-dead-bed

**Comment by BlocksAds** [comment]
Do you mean somewhere around there? 
https://user-images.githubusercontent.com/122573224/212427141-be50d826-1984-480e-819c-16f5f7c05a89.png

Otherwise I saw some spaces that were hidden (after waiting for some time on the web page) using `myabandonware.com##[align="center"]:has-text(freestar.config.)`

**Comment by Felipefpl** [comment]
I mean rectangle ads seen in the middle of the page and below, only with ublock disabled you can see how many of them exist.

**Comment by stephenhawk8054** [comment]
Maybe these?

```adb
myabandonware.com##.metas > div a[href^="/visual/"]:upward(.metas > div)
myabandonware.com##.metas > div script:has-text(freestar):upward(.metas > div)
myabandonware.com##.menu > div script:has-text(freestar):upward(.menu > div)
myabandonware.com##.menu.needScreens + div script:has-text(freestar):upward(.menu.needScreens + div)
myabandonware.com###download > div script:has-text(freestar):upward(#download > div)
myabandonware.com###h > div script:has-text(freestar):upward(#h > div)
```
