### ISSUE TITLE
starbucks.com: breakage

### ISSUE THREAD

**Issue by crisp5** [uBlockOrigin/uAssets#11156]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.starbucks.com/menu`

### Category

breakage

### Describe the issue

Opening Starbucks menu results in empty screen. If I leave the page open for about 90 seconds, the site displays "Whoops, something went wrong". If akamaiedge.net, maps.googleapis.com, and gstatic.com are graylisted, store selection works as expected, but menu remains blank. 
3rd-party, 3rd-party scripts, and 3rd-party frames are redlisted, but problem persists if they are graylisted. Problem is "solved" if I disable uBlock on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 132109
  cosmetic: 163016
  scriptlet: 32535
  html: 624
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61480-4624, 14m
    adguard-spyware: 24662-908, 13m
    adguard-spyware-url: 419-3, 13m
    block-lan: 44-0, 13m
    curben-phishing: 13238-4, 13m
    curben-pup: 382-0, 13m
    adguard-annoyance: 48756-3387, 13m
    fanboy-annoyance: 62132-24032, 13m
    fanboy-cookiemonster: 21048-123, 13m
    ublock-annoyances: 4357-4, 13m
  default: 
    ublock-filters: 30655-41, 14m
    ublock-badware: 3658-1, 14m
    ublock-privacy: 183-0, 14m
    ublock-abuse: 81-0, 14m
    ublock-unbreak: 1717-0, 14m
    easylist: 62447-611, 13m
    easyprivacy: 26576-10830, 13m
    urlhaus-1: 7516-0, 13m
    plowe-0: 3679-2, 13m
filterset (user): [empty]
hostRuleset: 
  added: [array of 88 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 832 ms (selfie)
popupPanel: 
  blocked: 270
```
</details>

**Comment by gorhill** [comment]
EasyPrivacy's `/optimizely.$domain=~optimizely.com` is causing the issue, this fixes it:

    @@||starbucks.com/app-assets/optimizely.$script,1p

cc @ryanbr, @Khrin
