### ISSUE TITLE
[nsfw] student.edgenuity.com: breakage

### ISSUE THREAD

**Issue by edgenuitydude** [uBlockOrigin/uAssets#11169]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://student.edgenuity.com/enrollment/e7fcb58b-1d74-4c7a-a228-51aa2d4d7a82/coursemap`

### Category

breakage

### Describe the issue

I am writing to you about a problem me and my mum have run into a couple times lately. The website Edgenuity will let me sign in but it will go straight to a blank screen sometimes showing up an error message on the screen or even the code line for the website itself. I have brought this issue up with the school's principal, Mrs.Debes (school counselor), and the computer guy that also works for the school. Both me and many others are very confused and would very much appreciate your help. I hope you had an amazing Christmas and new years.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 70733
  cosmetic: 40025
  scriptlet: 16245
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://gist.githubusercontent.com/thuddleston/d0e2dcf4c1f70905be6b3ab372985764/raw/39ffd350083088c6f5a57f29efc803c041263fa4/gistfile1.txt: 8-0, 23m
  default: 
    easylist: 62453-8, 19m
    easyprivacy: 26577-17, 17m
    plowe-0: 3715-818, 8d.2h.23m
    ublock-abuse: 72-0, 15m
    ublock-badware: 3659-65, 13m
    ublock-filters: 29853-133, 11m
    ublock-privacy: 191-12, 9m
    ublock-unbreak: 1704-39, 7m
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2334
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by gorhill** [comment]
I won't be able to reproduce if I can't log in.

I see nothing blocked on the login page. Blank page could be caused by a cosmetic filter, see if this makes a difference:

    ||edgenuity.com^$ehide

If this does not work, remove the filter and instead try:

    @@||googletagmanager.com/gtm.js^$script,domain=edgenuity.com

**Comment by mapx-** [comment]
@edgenuitydude 

if gorhill's filters don't work, open the logger, reproduce again the issue then take a screenshot of all blocked requests in the logger and post it here
