### ISSUE TITLE
reddit.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#11165]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.reddit.com/r/pihole/comments/rtrq5e/adorama_keeps_popping_up_verify_you_are_human_and/`

### Category

ads

### Describe the issue

Leftover ads about american express and leftover apple ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/69532417/147862065-626f6dc3-310a-400b-adca-1d5fa9ff3df6.png)
![image](https://user-images.githubusercontent.com/69532417/147862105-92eb4bd9-97ce-4f20-9b13-dd0f16438904.png)

</details>

Leftover ads from american express

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Chromium: 96
filterset (summary): 
  network: 103793
  cosmetic: 136338
  scriptlet: 32598
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
  added: 
    adguard-annoyance: 48759-145, 3h.6m
    adguard-generic: 61487-666, 3h.6m
    adguard-mobile: 7028-45, 3h.6m
    adguard-spyware: 24662-848, 3h.6m
    adguard-spyware-url: 419-12, 3h.6m
    block-lan: 44-0, 3h.6m
    curben-phishing: 12490-0, 3h.6m
    curben-pup: 379-0, 3h.6m
    fanboy-annoyance: 62128-5667, 3h.6m
    fanboy-cookiemonster: 21033-21033, 3h.6m
    ublock-annoyances: 4348-286, 3h.6m
  default: 
    easyprivacy: 26577-10600, 3h.6m
    plowe-0: 3681-661, 3h.6m
    ublock-abuse: 81-0, 3h.6m
    ublock-badware: 3659-150, 3h.6m
    ublock-filters: 30087-3166, 3h.6m
    ublock-privacy: 186-35, 3h.6m
    ublock-unbreak: 1708-98, 3h.6m
    urlhaus-1: 7496-4, 3h.6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2077 ms
popupPanel: 
  blocked: 17
```
</details>

**Comment by gorhill** [comment]
> - [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)

>     listset (total-discarded, last updated): 
>       removed: 
>         easylist: null
