### ISSUE TITLE
Blocking crypto mining in worker threads

### ISSUE THREAD

**Issue by emilfihlman** [uBlockOrigin/uAssets#1116]
### URL(s) where the issue occurs

http://123watchfree.co/episode/the-big-empty-6746132/watching.html

### Describe the issue

It seems the site is mining in the background using worker threads but ublock is not blocking them.

### Screenshot(s)

https://emil.fi/jako/kuvat/2017-12-26_03-22-23_7vgwh7mD.png

### Versions

- Browser/version: 63.0.3239.84
- uBlock Origin version: uBlock Origin 1.14.22

### Notes

Streaming a video from the given site results in extremely high cpu usage. Naming of functions suggests crypto mining.

**Comment by mapx-** [comment]
try
```
||uspostly.info^$websocket
$subdocument,domain=flowyourvideo.com
||opertures.com^
```

**Comment by okiehsch** [comment]
The mining is triggered by the `admaven` inline-script in the embedded `flowyourvideo` iframe, as far as I can see, so `flowyourvideo.com##script:inject(abort-on-property-write.js, Fingerprint2)` should fix the issue.

**Comment by gotitbro** [comment]
@okiehsch So `admaven` are the ones doing the mining? Aren't they an ad network.

**Comment by okiehsch** [comment]
The site does the mining `admaven` just enables it and gets a cut, just like they enable sites to display ads or popups.
