### ISSUE TITLE
golem.de: nuisance

### ISSUE THREAD

**Issue by Volker-Weissmann** [uBlockOrigin/uAssets#11167]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.golem.de/`

### Category

nuisance

### Describe the issue

golem.de shows a cookie banner, even if all lists are enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot from 2022-01-02 00-28-56](https://user-images.githubusercontent.com/39418860/147862235-dfc60167-3db5-4947-8ab1-4de7b2d9d25d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 137686
  cosmetic: 185049
  scriptlet: 32650
  html: 620
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-12, 4d.10h.15m
    ublock-annoyances: 4353-8, 2d.21h.15m
    adguard-generic: 61463-4701, 2d.21h.17m
    adguard-mobile: 7019-161, 2d.21h.18m
    adguard-spyware: 24651-937, 2d.21h.16m
    adguard-annoyance: 48688-4189, 2d.21h.14m
    adguard-social: 15323-42, 2d.21h.13m
    fanboy-thirdparty_social: 69-0, 10h.53m
    fanboy-annoyance: 59302-44005, 7d.2h.13m
    fanboy-cookiemonster: 20670-122, 7d.2h.14m
    fanboy-social: 23136-1086, 1d.7h.27m
    DEU-0: 5087-3, 1d.2h
    adguard-spyware-url: 419-2, 1d.7h.25m
    curben-phishing: 13238-4, 1d.2h.3m
    curben-pup: 382-0, 1d.2h.2m
  default: 
    ublock-filters: 30631-102, 2d.21h.11m
    ublock-badware: 3635-3, 2d.21h.6m
    ublock-privacy: 181-2, 2d.21h.5m
    ublock-abuse: 81-0, 2d.21h.4m
    ublock-unbreak: 1717-0, 2d.21h.9m
    easylist: 62361-756, 2d.21h.8m
    easyprivacy: 26569-10888, 2d.21h.12m
    plowe-0: 3717-0, 9d.12h
    urlhaus-1: 7516-0, 1d.2h.1m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 681 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
Server side cookie banner can't be blocked without breakage.

**Comment by mapx-** [comment]
gdpr too

**Comment by Volker-Weissmann** [comment]
> Server side cookie banner can't be blocked without breakage.

How can I see if a cookie banner done server side or client side?

I suspect that https://www.derstandard.de is the same

**Comment by iam-py-test** [comment]
Well, technically, the banner is on the client side, but the server checks if you agreed so it can not be bypassed

**Comment by Volker-Weissmann** [comment]
How can I see if the server checks if one agreed?

**Comment by iam-py-test** [comment]
> How can I see if the server checks if one agreed?

As far as I know, mainly guessing.
Just for your information, it sets this cookie:
![image](https://user-images.githubusercontent.com/84232764/147877532-4acce174-f770-4e0c-a031-3ee5b099dc7c.png)
So maybe if you set the cookie you _could_ bypass it, but probably not

**Comment by uBlock-user** [comment]
It's GDPR, both have it and we don't block these.

**Comment by Volker-Weissmann** [comment]
> It's GDPR, both have it and we don't block these.

The adguard-annoyance filter list does block GDPR popups.

**Comment by Volker-Weissmann** [comment]
> > How can I see if the server checks if one agreed?
> 
> As far as I know, mainly guessing. Just for your information, it sets this cookie: ![image](https://user-images.githubusercontent.com/84232764/147877532-4acce174-f770-4e0c-a031-3ee5b099dc7c.png) So maybe if you set the cookie you _could_ bypass it, but probably not

Thank you

**Comment by uBlock-user** [comment]
> The adguard-annoyance filter list does block GDPR popups.

and there is no site breakage ?

**Comment by iam-py-test** [comment]
> > The adguard-annoyance filter list does block GDPR popups.
> 
> and there is no site breakage ?

Probably just the simple client side ones

**Comment by okiehsch** [comment]
The site checks if the cookie `golem_consent20` is set, we don't support the ability to set cookies for security reasons.

**Comment by iam-py-test** [comment]
I wasn't able to bypass it even when setting cookies via DevTools...
Maybe case like `https://github[.]com/iam-py-test/my_filters_001/issues/65`

**Comment by uBlock-user** [comment]
@Volker-Weissmann I don't see any filter for GDPR popup for golem.de in AdGuard Annoyances.

**Comment by okiehsch** [comment]
````
cmp-cdn.golem.de#%#AG_onLoad(function(){if(window.location.href.includes("consentUUID")){var g=new MutationObserver(function(){var b=document.querySelector('button[title^="Zustimmen"]');b&&(g.disconnect(),b.click())});g.observe(document,{childList:!0,subtree:!0});setTimeout(function(){g.disconnect()},1E4)}});
````

**Comment by iam-py-test** [comment]
So could be done in a custom scriptlet @Volker-Weissmann

**Comment by uBlock-user** [comment]
`b.click()` They're clicking the GDPR modal for you, okay. Auto-clicking scriptlet was also declined by gorhill.

**Comment by gorhill** [comment]
Maybe once we have the concept of trusted lists, I will allow AdGuard inline scriptlets to be executed. _Maybe_.

**Comment by JobcenterTycoon** [comment]
would be so nice

**Comment by uBlock-user** [comment]
> AdGuard inline scriptlets

as site specific raw javascripts like AdGuard adds ?

**Comment by iam-py-test** [comment]
> `b.click()` They're clicking the GDPR modal for you, okay. Auto-clicking scriptlet was also declined by gorhill.

But still can be done by custom scriptlets for those who really want it

**Comment by uBlock-user** [comment]
> But still can be done by custom scriptlets for those who really want it

I know I made one myself, but I'm not lazy enough to rely on it, so removed it from my custom scriptlet collection.

**Comment by Volker-Weissmann** [comment]
> @Volker-Weissmann I don't see any filter for GDPR popup for golem.de in AdGuard Annoyances.

Not for golem.de, but for other sites.

**Comment by Volker-Weissmann** [comment]
> ```
> cmp-cdn.golem.de#%#AG_onLoad(function(){if(window.location.href.includes("consentUUID")){var g=new MutationObserver(function(){var b=document.querySelector('button[title^="Zustimmen"]');b&&(g.disconnect(),b.click())});g.observe(document,{childList:!0,subtree:!0});setTimeout(function(){g.disconnect()},1E4)}});
> ```
> 
> That looks like a filter that could target it, only works with Adguard.

But then you gave away your right to privacy. This is the opposite of what I want. If given the choice between given away my data or not reading an article, I would choose the latter and add the site to uBlacklist.

**Comment by iam-py-test** [comment]
> But then you gave away your right to privacy.

Not necessarily. uBo and AG block all the tracking they can. But it's your choice to use the site 
You always can visit in Tor Browser and agree there if you want to only use it for one thing

**Comment by uBlock-user** [comment]
> But then you gave away your right to privacy. 

You're allowing some first-party cookies, you can still block third-party cookies.

**Comment by JobcenterTycoon** [comment]
Thats why other addons got developed like cookie auto delete

**Comment by iam-py-test** [comment]
Though most browsers allow easy removal of cookies too

**Comment by Volker-Weissmann** [comment]
> Not necessarily. uBo and AG block all the tracking they can. 

Yes, but "all they can" is the problem here.

> But it's your choice to use the site

If ublock origin clicks on the agree button, I would not know that this site has an unskippable GDPR banner.

If you ever choose to add auto-button-clickers, please make a seperate list for them or a way to disable them.

**Comment by iam-py-test** [comment]
> If you ever choose to add auto-button-clickers, please make a seperate list for them or a way to disable them.

That is why @gorhill doesn't add it.
Why not just continue on your own if you don't want to bypass it? Hiding/bypassing it is auto-agreeing anyway; most sites auto-agree just by visiting their website.

**Comment by Volker-Weissmann** [comment]
> > If you ever choose to add auto-button-clickers, please make a seperate list for them or a way to disable them.
> 
> That is why @gorhill doesn't add it. 

?

> Why not just continue on your own if you don't want to bypass it? 

?

> Hiding/bypassing it is auto-agreeing anyway; most sites auto-agree just by visiting their website.

GDPR law saws otherwise.

**Comment by JobcenterTycoon** [comment]
raw javascript support is useful for other issues too like hard to bypass anti adblock banners. But it seems to be hard to create these raw javascripts too

**Comment by Volker-Weissmann** [comment]
> Adguard only accept cookie banners and not select the best privacy option because its way more complex to select the best privacy option

That is not a good thing.

**Comment by iam-py-test** [comment]
> That is not a good thing.

Well, it's a choice between auto-agreeing and losing some privacy, or having to manually agree and not losing that privacy

**Comment by JobcenterTycoon** [comment]
Its a cat and mouse play. After cookie banner got blocked more and more sites use server side cookie banner. A few auto accept scripts wich select only the best privacy settings stopped working after the website developer slightly changed the cookie banner code

**Comment by okiehsch** [comment]
> But then you gave away your right to privacy. This is the opposite of what I want. If given the choice between given away my data or not reading an article, I would choose the latter and add the site to uBlacklist.

It's in their annoance list, most users are just sick and tired of mindlessy clicking through GDPR popups every day and want that annoyance to stop, they don't care about privacy and most of the tracking you agree if you simply click OK is blocked anyway.

**Comment by Volker-Weissmann** [comment]
> Well, it's a choice between auto-agreeing and losing some privacy, or having to manually agree and not losing that privacy

If I see a banner that is not blocked by ublock, I usually leave the site and possibly put them on ublacklist. There are more than enough sites that do not have this problem.

**Comment by Volker-Weissmann** [comment]
> > But then you gave away your right to privacy. This is the opposite of what I want. If given the choice between given away my data or not reading an article, I would choose the latter and add the site to uBlacklist.
> 
> It's in their annoyance list, most users are just sick and tired of mindlessy clicking through GDPR popups every day and want that annoyance to stop, they don't care about privacy and most of the tracking you agree if you simply click OK is blocked anyway.

I understand why one would want that, but please put that on a seperate list.

**Comment by okiehsch** [comment]
> but please put that on a seperate list.

You misunderstand, it's in the annoyance list of Adguard a different extension than uBlock.

**Comment by okiehsch** [comment]
> If I see a banner that is not blocked by ublock, I usually leave the site and possibly put them on ublacklist.

So you have blocked most of the web? Atleast the european portion of it?

**Comment by Volker-Weissmann** [comment]
> > but please put that on a seperate list.
> 
> I think you misunderstand, it's in the annoyance list of Adguard a different extension than uBlock.

You mean this list? I have it enabled in ublock origin ("Filter lists" -> "Annoyances" -> "Adguard Annoyances")

https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/annoyances.txt

**Comment by iam-py-test** [comment]
> You mean this list? I have it enabled in ublock origin ("Filter lists" -> "Annoyances" -> "Adguard Annoyances")

However, the auto-clicking isn't part of that list as uBo doesn't support it

**Comment by okiehsch** [comment]
Yes, but the filter in question is not supported by uBO.
It only works with Adguard.

**Comment by Volker-Weissmann** [comment]
> > If I see a banner that is not blocked by ublock, I usually leave the site and possibly put them on ublacklist.
> 
> So you have blocked most of the web? Atleast the european part of it?

No? E.g. out of the [5 biggest german newspapers](https://de.wikipedia.org/wiki/Liste_deutscher_Zeitungen), only 1 shows a banner (with uBO and most filter lists enabled):

https://www.bild.de/
https://www.sueddeutsche.de/
https://www.waz.de/
https://www.faz.net/aktuell/

https://rp-online.de

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/147881589-e62ff382-868a-446a-ac00-a3cfeb0d2b75.png)

They all have GDPR modals, they are legally obligated to do so.

**Comment by JobcenterTycoon** [comment]
I get GDPR on `bild.de`, `rp-online.de` and `faz.net` with enabled annoyance lists.

**Comment by Volker-Weissmann** [comment]
> ![image](https://user-images.githubusercontent.com/16838044/147881589-e62ff382-868a-446a-ac00-a3cfeb0d2b75.png)
> 
> They all have GDPR modals, they are legally obligated to do so.

I only get this popup if I disable ublock origin. My configuration:

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 136947
  cosmetic: 185215
  scriptlet: 32654
  html: 625
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 16h.37m
    ublock-annoyances: 4359-8, 16h.37m
    adguard-generic: 61489-4700, 16h.37m
    adguard-mobile: 7028-161, 16h.37m
    adguard-spyware: 24662-937, 16h.37m
    adguard-annoyance: 48762-4178, 2h
    adguard-social: 15330-42, 16h.37m
    fanboy-thirdparty_social: 69-0, 16h.37m
    fanboy-annoyance: 59297-44356, 16h.37m
    fanboy-cookiemonster: 21016-124, 16h.37m
    fanboy-social: 23136-1086, 16h.37m
    DEU-0: 5087-3, 16h.37m
    adguard-spyware-url: 419-3, 16h.37m
    curben-phishing: 12490-4, 16h.37m
    curben-pup: 379-0, 16h.37m
  default: 
    ublock-filters: 30604-102, 16h.37m
    ublock-badware: 3663-1, 16h.37m
    ublock-privacy: 183-0, 16h.37m
    ublock-abuse: 81-0, 16h.37m
    ublock-unbreak: 1719-1, 16h.37m
    easylist: 62453-760, 16h.37m
    easyprivacy: 26577-10885, 16h.37m
    plowe-0: 3682-3, 16h.37m
    urlhaus-1: 7496-0, 16h.37m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1104 ms (selfie)
popupPanel: 
  blocked: 7
```

**Comment by okiehsch** [comment]
All I wanted to say is that basically every german site has a  GDPR modal of which some are circumvented by annoyance and anti cookie lists.
I don't see any privacy issue if one decides to click accept instead of removing the modal.
If you click accept the sites try to connect to various ad and tracking servers, which are blocked by default in uBO.
