### ISSUE TITLE
[nsfw] pornzog.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11166]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://pornzog.com/video/14550093/aubree-ice-in-lovemaking-with-security-officer/`

### Category

ads

### Describe the issue

there are ads on the right

### Screenshot(s)

https://user-images.githubusercontent.com/81616288/147862217-dd14d6e0-ea6d-4da4-b65d-5b0e1e4a2f1a.jpeg

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Chromium: 96
filterset (summary): 
  network: 80096
  cosmetic: 43239
  scriptlet: 16414
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5087-0, 10h.54m
    easylist: 62453-14, 10h.54m
    easyprivacy: 26577-28, 10h.54m
    plowe-0: 3679-817, 10h.54m
    ublock-abuse: 81-0, 10h.54m
    ublock-badware: 3654-64, 10h.54m
    ublock-filters: 30080-147, 10h.54m
    ublock-privacy: 186-3, 10h.54m
    ublock-unbreak: 1707-40, 10h.54m
    urlhaus-1: 7502-0, 10h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1677 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
@ryanbr
