### ISSUE TITLE
seznam.cz: ads

### ISSUE THREAD

**Issue by Ghost-Miner** [uBlockOrigin/uAssets#11162]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Describe the issue

Ads still apeear and when i try to remove them using the select tool it selects/highlights the background image instead.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78454
  cosmetic: 40542
  scriptlet: 16597
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30649-30, 1d.1h.15m
    ublock-badware: 3658-1, 1d.1h.14m
    ublock-privacy: 181-0, 1d.1h.13m
    ublock-abuse: 72-0, 1d.1h.12m
    ublock-unbreak: 1717-0, 1d.1h.11m
    easylist: 62441-573, 1d.1h.10m
    easyprivacy: 26576-486, 1d.1h.9m
    urlhaus-1: 7695-0, 18h.13m
    plowe-0: 3679-3, 5d.1h.9m
    CZE-0: 776-0, 22h.14m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3234 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
screenshot ? (with the ads)
