### ISSUE TITLE
animespirit.tv: breakage

### ISSUE THREAD

**Issue by nazar108** [uBlockOrigin/uAssets#11175]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`http://animespirit.tv/1476-van-pis-sub.html`

### Category

breakage

### Describe the issue

Can watch videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 96566
  cosmetic: 61006
  scriptlet: 17963
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40612-160, never
    easylist: 62254-462, never
    easyprivacy: 26549-483, never
    plowe-0: 3715-3, never
    ublock-abuse: 81-0, never
    ublock-badware: 3629-1, never
    ublock-filters: 30064-137, never
    ublock-privacy: 184-0, never
    ublock-unbreak: 1708-0, never
    urlhaus-1: 8168-0, never
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2047 ms
popupPanel: 
  blocked: 12
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce, video works fine here.

**Comment by JobcenterTycoon** [comment]
For me too (with or without enabled RUS list) it just loads a bit longer

**Comment by gorhill** [comment]
> just loads a bit longer

Yes, same.

@nazar108 Did you truthfully answer the prerequisite steps -- they are key to avoid issues caused by misconfiguration on your side? I see you have custom filters, did you try without them?
