### ISSUE TITLE
cloudgame.douyu.com: breakage

### ISSUE THREAD

**Issue by Mishasama** [uBlockOrigin/uAssets#11170]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://cloudgame.douyu.com/play/11925/2`

### Category

breakage

#### Account Required
**You can't test it without having a verified account.** I may already show what's rules that affect this problem in the screenshots.

It's a WebRTC based cloud PC platform.
These web pages need WebRTC to functionally. It can't work without WebRTC.
Maybe we should add a whitelist just for the hostname 'cloudgame.douyu.com'

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/54498172/147865904-2066ee6f-fd15-4246-b58d-bde798fd893e.png)
![image](https://user-images.githubusercontent.com/54498172/147865906-511de4b9-0742-4061-8463-0ed3bd709d1d.png)
![image](https://user-images.githubusercontent.com/54498172/147866108-8de2fcd5-1502-4725-81cd-cff0b422e8b1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 95
filterset (summary): 
  network: 97298
  cosmetic: 57164
  scriptlet: 19380
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/easylistchina.txt: 25106-16, 9m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt: 1895-2, 9m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt: 63-63, 9m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 9m
    CHN-0: 27226-25145, 9m
    ublock-annoyances: 4351-8, 9m
  default: 
    JPN-1: 5655-12, 9m
    easylist: 62454-494, 9m
    easyprivacy: 26578-92, 9m
    plowe-0: 3682-825, 9m
    ublock-abuse: 81-0, 9m
    ublock-badware: 3659-65, 9m
    ublock-filters: 30104-171, 9m
    ublock-privacy: 195-4, 9m
    ublock-unbreak: 1736-44, 8m
    urlhaus-1: 7618-0, 8m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 6 redacted]
urlRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  dynamicFilteringEnabled: true
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7808
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@shenzhiming88 take a look .. maybe we should remove your filters

**Comment by shenzhiming88** [comment]
> @shenzhiming88 take a look .. maybe we should remove your filters

https://github.com/uBlockOrigin/uAssets/pull/11163

**Comment by mapx-** [comment]
@Mishasama update your lists see if it's ok now

**Comment by shenzhiming88** [comment]
> @Mishasama update your lists see if it's ok now

Rule updates may be delayed, it is better to let him add custom rules.

**Comment by Mishasama** [comment]
> @Mishasama update your lists see if it's ok now

OK, it works now. THX

**Comment by gorhill** [comment]
@Mishasama you can remove Reek's Anti Adblock Killer, it's not maintained for years and as you can see it's blacklisted in uBO, no filters from it are allowed.
