### ISSUE TITLE
douyu.com: breakage

### ISSUE THREAD

**Issue by q784324074** [uBlockOrigin/uAssets#11172]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.douyu.com/48699`

### Category

breakage

### Describe the issue

没有播放器插件 => No player plug-in

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/51526503/147872033-4b869f4b-ea94-42db-afa5-ff0ad4f7f60c.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Chromium: 96
filterset (summary): 
  network: 95150
  cosmetic: 50201
  scriptlet: 16512
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 7m
  default: 
    CHN-0: 27206-86, 20h.12m
    easylist: 62453-413, 20h.10m
    easyprivacy: 26577-43, 20h.8m
    plowe-0: 3682-819, 8m
    ublock-abuse: 81-0, 20h.6m
    ublock-badware: 3654-64, 20h.4m
    ublock-filters: 30080-158, 20h.2m
    ublock-privacy: 186-3, 19h.58m
    ublock-unbreak: 1707-40, 20h
    urlhaus-1: 7496-0, 19h.56m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 481 ms (selfie)
popupPanel: 
  blocked: 55
```
</details>

**Comment by mapx-** [comment]
update **now** all your lists, test again
