### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by blackwing12344** [uBlockOrigin/uAssets#11178]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://aternos.org/servers/`

### Category

detection

### Describe the issue

it only starts dectecting once you have a server

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77929
  cosmetic: 40225
  scriptlet: 16375
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30654-30, 23h.34m
    ublock-badware: 3513-1, 23h.33m
    ublock-privacy: 183-0, 23h.32m
    ublock-abuse: 81-0, 23h.31m
    ublock-unbreak: 1719-0, 23h.30m
    easylist: 62453-571, 23h.29m
    easyprivacy: 26577-481, 23h.28m
    urlhaus-1: 7516-0, 23h.27m
    plowe-0: 3679-2, 23h.26m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1033 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by gorhill** [comment]
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate: <https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+aternos.org>
