### ISSUE TITLE
dosgamezone.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11174]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dosgamezone.com/game/color-revolution-7493.html`

### Describe the issue

When i try to download a game i get only a small text file in a .zip with anti adblock notice

The in browser game says it "Your browser is preventing Color Revolution from loading. This is usually caused by ad blockers." but its not working on firefox with disabled adblock either (blank screen). I not tested on chrome

### Screenshot(s)

<img width="538" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/147876029-44ebb7b2-4820-47fa-adae-ee46cd88cac1.PNG">
<img width="373" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/147876418-6f071a6b-be79-4d91-87d7-557618a3a856.PNG">

### uBlock Origin version

1.40.2

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances 

### Notes

They checking `dosgamezone.com/ads/banner1.gif` for both (in browser game & download)

**Comment by gorhill** [comment]
I wasn't able to reproduce -- tried twice, I could download the game (while not logged in).

**Comment by mapx-** [comment]
working filter:
`@@||dosgamezone.com^$image,1p`

The redirection does not work:
`*$image,redirect-rule=1x1.gif,domain=dosgamezone.com`
