### ISSUE TITLE
nearbyme.io: popups

### ISSUE THREAD

**Issue by gokiberk** [uBlockOrigin/uAssets#11176]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://m.nearbyme.io/search/

### Category

popups

### Describe the issue

This website appears as a result of malware wiseresults.xyz and it keeps redirecting to nearbyme.io webpage when you search in your browser.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78592
  cosmetic: 40107
  scriptlet: 16392
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-30, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-0, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1719-0, never
    easylist: 62254-569, never
    easyprivacy: 26549-483, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 340 ms
popupPanel: 
  blocked: 6
```
</details>

**Comment by gorhill** [comment]
I don't understand what you are reporting.

> it keeps redirecting to nearbyme.io webpage

The site you report is `https://m.nearbyme.io/search/`, so you are saying `https://m.nearbyme.io/search/` redirects you to itself? You need to better explain what is the issue.

**Comment by iam-py-test** [comment]
> This website appears as a result of malware wiseresults.xyz

How do you know that?

**Comment by gokiberk** [comment]
When I search something on my browser using google as a search engine, this website lists the results instead of google.com and searching is made through the website wiseresults.xyz. I was wondering if there is a way to block redirecting to those pages.

**Comment by iam-py-test** [comment]
> When I search something on my browser using google as a search engine, this website lists the results instead of google.com and searching is made through the website wiseresults.xyz. I was wondering if there is a way to block redirecting to those pages.

You need to reset your search engine back to Google:
![image](https://user-images.githubusercontent.com/84232764/147881617-b67dc41e-6be9-4c88-826c-cc7eeba72b76.png)

**Comment by iam-py-test** [comment]
Wait, how can you be redirected through that domain?? It doesn't exist (anymore):
![image](https://user-images.githubusercontent.com/84232764/147881794-93454b64-d0b6-4c2b-9a7e-6719e8afe527.png)

**Comment by iam-py-test** [comment]
Hmm... `https://www.pcrisk.com/removal-guides/20964-nearbyme-io-redirect`
Might be helpful, but **ignore the download buttons**

**Comment by gokiberk** [comment]
Thank you for suggesting that, I believe there is something unintentionally installed on my computer which causes this problem. It didn’t appear on mozilla at first, started with safari. Then it appeared when I started using mozilla.

**Comment by iam-py-test** [comment]
So you are on MacOS...
Sounds like adware. Not much uBo can do
I found this but I don't know if it's helpful. `https://www.howtogeek.com/223116/how-to-remove-malware-and-adware-from-your-mac/`

**Comment by gokiberk** [comment]
I thought uBo could fight back to this. Thanks again.

**Comment by iam-py-test** [comment]
> I thought uBo could fight back to this. Thanks again.

It's an app on your device. You need some kind-of antimalware utility to remove it. All uBo can do is show a warning before you visit the search site

**Comment by gorhill** [comment]
At most uBO would maybe fight the symptoms, you need a cure, i.e. remove the malware from your system.

**Comment by iam-py-test** [comment]
Add to uBo badware + link here?

**Comment by gokiberk** [comment]
You are right, even a cure would help a lot until I find the permanent solution. Many thanks.

**Comment by iam-py-test** [comment]
> You are right, even a cure would help a lot until I find the permanent solution. Many thanks.

Check out `https://www.howtogeek.com/223116/how-to-remove-malware-and-adware-from-your-mac/`. I have used Malwarebytes on Windows and it's good (on Windows anyway)
