### ISSUE TITLE
dailybuzz.nl: breakage

### ISSUE THREAD

**Issue by jpplaisier** [uBlockOrigin/uAssets#11179]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://dailybuzz.nl/buzz/politiehond-leeft-zich-ook-uit-op-demonstrant-in-amsterdam.html`

### Category

breakage

### Describe the issue

Video not loading unless uBlock is disabled. Probably something with cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78427
  cosmetic: 40217
  scriptlet: 16404
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62457-8, 5h.39m
    easyprivacy: 26580-17, 5h.37m
    plowe-0: 3679-816, 6d.4h.28m
    ublock-abuse: 81-0, 4d.3h.45m
    ublock-badware: 3509-64, 4d.3h.49m
    ublock-filters: 30135-139, 4d.3h.51m
    ublock-privacy: 193-3, 4d.3h.47m
    ublock-unbreak: 1705-39, 5h.41m
    urlhaus-1: 7938-0, 5h.35m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 362
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
add
`@@||massariuscdn.com/pubs/dailybuzz/dailybuzz_hb_setup.js$script,domain=dailybuzz.nl`

@ryanbr

**Comment by JohnyP36** [comment]
Also solved in EasyList Dutch: 
https://github.com/JohnyP36/Personal-List/commit/8545e045065ab764ab84d63ab4e091001fddd196 and https://github.com/JohnyP36/Personal-List/commit/65a9c20b8fcf1e8176b627377771cfbee8bb74a2
