### ISSUE TITLE
[NSFW] reddit.tube ad

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#11171]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.reddit.tube/video/c4bbf0fa3e659e9a8bfb1b8268133c08ba9e4dfa`

### Describe the issue

There is an ad posted on the screenshot below.

### Screenshot(s)

![screen](https://user-images.githubusercontent.com/86512304/147871031-622c943b-bfb8-4350-b317-a6c7d660b47f.jpg)

### uBlock Origin version

1.40.2

### Browser name and version

FIrefox 95

### Settings

Default settings

**Comment by mapx-** [comment]
@ryanbr
