### ISSUE TITLE
423down.com: detection

### ISSUE THREAD

**Issue by prajna0** [uBlockOrigin/uAssets#11187]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.423down.com/`

### Category

detection

### Describe the issue

![20220104155347](https://user-images.githubusercontent.com/11697277/148026836-d3d82923-f999-4499-a413-b089273a79e6.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 94393
  cosmetic: 51496
  scriptlet: 16564
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://cdn.jsdelivr.net/gh/cjx82630/cjxlist@master/cjx-annoyance.txt: 1895-2, 19m
    https://cdn.jsdelivr.net/gh/cjx82630/cjxlist@master/cjxlist.txt: 516-3, 19m
    https://cdn.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/mv.txt: 194-3, 19m
    https://cdn.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/rule.txt: 1166-17, 19m
  default: 
    CHN-0: 27246-134, 20m
    easylist: 62576-433, 20m
    easyprivacy: 26599-75, 19m
    ublock-abuse: 76-0, 19m
    ublock-badware: 3648-64, 19m
    ublock-filters: 30035-174, 19m
    ublock-privacy: 185-3, 19m
    ublock-unbreak: 1710-41, 19m
    urlhaus-1: 7628-0, 19m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 383 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by uBlock-user** [comment]
> Do you have an account?

 No, I can repro without it.
