### ISSUE TITLE
This website keeps blocking me

### ISSUE THREAD

**Issue by bufce2010** [uBlockOrigin/uAssets#11182]
### Prerequisites

- [x] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://race.egybest.world/movie/men-in-black-international-2019/`

### Describe the issue

This website keeps blocking me for using ad block. even in incognito mode with no extensions.

`https://race.egybest.world/movie/men-in-black-international-2019/`

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 86
filterset (summary): 
  network: 260502
  cosmetic: 217158
  scriptlet: 35899
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://curben.gitlab.io/malware-filter/phishing-filter.txt: 11849-0, 4h.53m
    https://curben.gitlab.io/malware-filter/pup-filter.txt: 379-0, 4h.58m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-137, 1d.5h.10m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-217, 8d.5h
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-44, 1d.5h.54m
    BGR-0: 1116-19, 1d.5h.52m
    CHN-0: 27236-1065, 32m
    CZE-0: 775-40, 4h.59m
    DEU-0: 5087-369, 4h.55m
    EST-0: 444-13, 5h.2m
    FIN-0: 1502-76, 44m
    FRA-0: 26046-3283, 33m
    GRC-0: 1002-19, 1d.5h.7m
    HUN-0: 2128-45, 5h.3m
    IDN-0: 9007-3638, 45m
    IRN-0: 1340-72, 28m
    ISL-0: 193-2, 1d.5h.56m
    ISR-0: 1616-9, 4h.54m
    ITA-0: 12716-450, 4h.51m
    ITA-1: 5005-134, 4d.6h.4m
    [34 lists not shown]: [too many]
  default: 
    easylist: 62500-25231, 27m
    easyprivacy: 26590-11130, 26m
    plowe-0: 3678-1536, 6d.2h
    ublock-abuse: 76-65, 25m
    ublock-badware: 3648-230, 24m
    ublock-filters: 30034-3778, 23m
    ublock-privacy: 180-72, 22m
    ublock-unbreak: 1678-118, 21m
    urlhaus-1: 7563-9, 4h.48m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 30 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: true
  largeMediaSize: 1024
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1163 ms (selfie)
```
</details>

**Comment by gwarser** [comment]
5 click on player works in Firefox and Chrome 96

**Comment by gorhill** [comment]
Works fine with default lists/settings.

**Comment by gorhill** [comment]
> - [X] uBO with default lists/settings

> [34 lists not shown]: [too many]

Did you truthfully perform the prerequisite steps as asked?

**Comment by bufce2010** [comment]
> > * [x]  uBO with default lists/settings
> 
> > [34 lists not shown]: [too many]
> 
> Did you truthfully perform the prerequisite steps as asked?
Not this one:  [uBO with default lists/settings.] 
I'll reset it when I get back home. Sorry 😊

**Comment by gorhill** [comment]
> Not this one: [uBO with default lists/settings.]

There is a warning about this above the prerequisite steps:

> To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disrespecting these steps **WILL** result in your account being blocked on this repo (temporarily, then permanently with repeated disregard for the template).
