### ISSUE TITLE
airgunsofarizona.com: breakage

### ISSUE THREAD

**Issue by skullriot** [uBlockOrigin/uAssets#11180]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.airgunsofarizona.com/scope-mounts/brocock-picatinny-dual-side-rail-adapter/`

### Category

breakage

### Describe the issue

blocks item images

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 119018
  cosmetic: 121044
  scriptlet: 32404
  html: 609
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 20h.49m
    adguard-generic: 61489-4887, 2h.15m
    adguard-spyware: 24662-929, 2h.13m
    adguard-annoyance: 48762-4306, 2h.11m
    adguard-social: 15330-1070, 2h.10m
    fanboy-annoyance: 59299-40130, 8d.10h.35m
    fanboy-social: 23136-14022, 2h.9m
    ublock-annoyances: 4359-7, 2h.8m
    adguard-spyware-url: 419-3, 2h.7m
  default: 
    ublock-filters: 30338-191, 2h.20m
    ublock-badware: 3663-1, 2h.19m
    ublock-privacy: 183-1, 2h.18m
    ublock-abuse: 76-0, 2h.17m
    ublock-unbreak: 1719-0, 2h.16m
    easylist: 62457-24071, 2h.14m
    easyprivacy: 26580-10831, 2h.12m
    urlhaus-1: 7516-0, 20h.50m
    plowe-0: 3715-3, 8d.10h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 245 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by mapx-** [comment]
add

`@@||airgunsofarizona.com/content/vendors/jquery/cookies/cookies.js$script,1p`

FA annoyances  @ryanbr
