### ISSUE TITLE
cnn.com: breakage

### ISSUE THREAD

**Issue by jgardynik** [uBlockOrigin/uAssets#11194]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cnn.com/business`

### Category

breakage

### Describe the issue

The entire first news section is being hidden by the adblocker. It's inside the .zn-business-zone-1 container.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78291
  cosmetic: 40225
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62452-8, 3d.12h.47m
    easyprivacy: 26580-17, 2d.4h.43m
    plowe-0: 3682-817, 1d.8h.30m
    ublock-abuse: 81-0, 3d.12h.49m
    ublock-badware: 3659-64, 2d.4h.35m
    ublock-filters: 30155-139, 2d.4h.41m
    ublock-privacy: 191-12, 2d.4h.39m
    ublock-unbreak: 1736-39, 2d.4h.37m
    urlhaus-1: 7628-0, 4h.26m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 29 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  dynamicFilteringEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 152
  launchFromSelfie: true
popupPanel: 
  blocked: 38
```
</details>

**Comment by mapx-** [comment]
add

`cnn.com#@#.zn__containers:has(a[href^="https://www.fool.com/"])`

@ryanbr

**Comment by jgardynik** [comment]
That fixes it, but I have to ask: is it the filter being overzealous about blocking parent containers, or is there a problem with a specific list that needs updated? It seems to be something in Easylist, so should I report it to them as well?

**Comment by mapx-** [comment]
EL maintainer - as you see above - has been notified

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/07cb08b2b7cec89996486d4c789a158987c9f30f
