### ISSUE TITLE
clubhouse.golftec.com: breakage

### ISSUE THREAD

**Issue by maxclark** [uBlockOrigin/uAssets#11191]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://clubhouse.golftec.com/`

### Category

breakage

### Describe the issue

Website does not load when the plugin is active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1727" alt="Screen Shot 2022-01-04 at 9 07 50 AM" src="https://user-images.githubusercontent.com/44366/148079609-03ed0500-8ee4-4d81-80af-5b73a1c7efef.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 78267
  cosmetic: 40225
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62453-8, 2d.15h.37m
    easyprivacy: 26577-17, 2d.15h.35m
    plowe-0: 3682-817, 2d.15h.43m
    ublock-abuse: 81-0, 2d.15h.33m
    ublock-badware: 3659-64, 2d.15h.31m
    ublock-filters: 30155-139, 2d.15h.29m
    ublock-privacy: 195-3, 2d.14h.36m
    ublock-unbreak: 1704-39, 2d.14h.34m
    urlhaus-1: 7628-0, 11h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1049
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by gorhill** [comment]
The website loaded fine on my side. Did you verify whether it was a site issue, i.e. did you with uBO disabled?

**Comment by maxclark** [comment]
It must be something else I'm doing. I'll dig into this more and re-report.

**Comment by JohnyP36** [comment]
I too had/have no problem loading this site.

**Comment by uBlock-user** [comment]
Redirects to `https://clubhouse.golftec.com/login`
