### ISSUE TITLE
Calculator-Online.net shows adblocker error

### ISSUE THREAD

**Issue by fffelix-jan** [uBlockOrigin/uAssets#11193]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://calculator-online.net/ones-complement-calculator/`

### Describe the issue

The website pops up a message asking you to disable the ad blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/38475999/148109630-401d7bdf-0239-4f07-b76c-d423b84a345f.png)

### uBlock Origin version

1.40.4

### Browser name and version

Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### Settings

N/A

**Comment by gorhill** [comment]
This works:

    calculator-online.net##+js(nostif, main_ads_con)
