### ISSUE TITLE
scmp.com: nuisance

### ISSUE THREAD

**Issue by Ciarlini34** [uBlockOrigin/uAssets#11197]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.scmp.com/yp/discover/lifestyle/features/article/3056589/are-paper-straws-really-better-environment-plastic`

### Category

nuisance

### Describe the issue

Paywall blocking the content of the page asking to disable the Adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/34046233/148140249-3ff08f24-c41f-4504-b919-a158b5d1763c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 79486
  cosmetic: 42801
  scriptlet: 16535
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30614-29, 1d.11h.46m
    ublock-badware: 3652-1, 1d.11h.45m
    ublock-privacy: 183-0, 1d.11h.39m
    ublock-abuse: 72-0, 1d.11h.40m
    ublock-unbreak: 1691-0, 1d.11h.43m
    easylist: 62500-624, 1d.11h.42m
    easyprivacy: 26590-495, 1d.11h.41m
    urlhaus-1: 7628-0, 11h.32m
    plowe-0: 3679-2, 8d.11h.8m
    spa-1: 4173-52, 1d.11h.44m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 351 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by iam-py-test** [comment]
I can not reproduce in Mozilla Firefox or Google Chrome:
![image](https://user-images.githubusercontent.com/84232764/148140537-8440b68c-120e-49d8-9a2f-126c353669df.png)
Please disable any other adblockers and reset uBo to default settings, and then retest

**Comment by Ciarlini34** [comment]
> I can not reproduce in Mozilla Firefox or Google Chrome: ![image](https://user-images.githubusercontent.com/84232764/148140537-8440b68c-120e-49d8-9a2f-126c353669df.png) Please disable any other adblockers and reset uBo to default settings, and then retest Edit: I can only repro on my host system weirdly Edit 2: I think it's caused by Firefox's tracking protection Edit 3: Reset to default settings on my host system. Now can't repro. I think it was caused by a conflict between AG Base and uBo filters

Do you still need me to repro? I did already reset uBo, and uninstalled all other adblockers before submitting the ticket.

**Comment by iam-py-test** [comment]
Like I said, I can't repro on default settings. You have custom filters, try disabling those.
Also check your DNS server and HOSTs file, either of those could be causing the issue.

**Comment by Ciarlini34** [comment]
> Like I said, I can't repro on default settings. You have custom filters, try disabling those. Also check your DNS server and HOSTs file, either of those could be causing the issue. Also clear cache/cookies

Changing DNS did it. I don't know why; I can't reproduce anymore either. 
Thanks for the help, anyway.
