### ISSUE TITLE
fotofilter.de: detection

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11195]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fotofilter.de/`

### Category

detection

### Describe the issue

site detects ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2131231](https://user-images.githubusercontent.com/81616288/148118504-e4de4ddd-2c80-4286-95e9-ba940a0a410f.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 80494
  cosmetic: 43311
  scriptlet: 16402
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 426-1, 6h.11m
  default: 
    DEU-0: 5115-0, 6h.11m
    easylist: 62581-15, 6h.11m
    easyprivacy: 26599-28, 6h.11m
    plowe-0: 3682-818, 6h.11m
    ublock-abuse: 76-0, 6h.11m
    ublock-badware: 3648-65, 6h.11m
    ublock-filters: 30041-148, 6h.11m
    ublock-privacy: 185-4, 6h.11m
    ublock-unbreak: 1710-41, 6h.11m
    urlhaus-1: 7408-0, 6h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6248 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by gorhill** [comment]
This works:

    @@||fotofilter.de^$ghide
