### ISSUE TITLE
Wrong identification of our content (coverpage) 

### ISSUE THREAD

**Issue by margauxcleo** [uBlockOrigin/uAssets#11190]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Hello,
We are providing a website for the Canard PC Magazine. The main goal is to provide a digital version of their magazines to their customers.
We are having a problem with the homepage. One of our section / image is considered as a "visual nuisance", therefore our users cannot see it, and follow the link to go to the publication page. We don't understand and accept this decision.
The same image is available on another page of the website, and there is no problem. Furthemore, we have a beta website, which has the exact same images and links on the homepage, and it is not considered as "visual nuisance". Here is the link to our beta website: https://kiosque-canardpc-beta.immanens.com/home . 
We think this may be a bug. Could you please reconsider ? 
Thank you. 
Best Regards,
Margaux Vitez 
Project Manager at Immanens 

![Homepage - CanardPC Website (beta)](https://user-images.githubusercontent.com/50700047/148049371-a6338ca5-0614-4710-b79b-f59742d1f8b3.png)
![Homepage - CanardPC Website (production)](https://user-images.githubusercontent.com/50700047/148049379-91cbf940-f389-4e98-a2e9-0a6ffd100fb5.png)
![Magazine Page - CanardPC Website (production)](https://user-images.githubusercontent.com/50700047/148049381-fd8313f8-1637-4e71-ba7a-84566839aefc.png)

### A specific URL where the issue occurs

https://kiosque.canardpc.com/home

### Steps to Reproduce

1. Go to https://kiosque.canardpc.com/home
2. You can see that the cover page of the magazine "Canard PC Hors-Série" is disabled by your plugin. 
3. Turn off the aesthetic filtering 
4. Clic on the cover (magazine with the video game Doom)
5. As you can see, there is no problem on this page: https://kiosque.canardpc.com/detail/publication/468?issue_id=77147. 

### Expected behavior

We need our users to see all the cover pages of the homepage. In order to, you need to NOT consider one of our cover page as a "visual nuisance".
This is really important for our user experience. If they cannot see the cover page, they cannot go on the magazine page and access to the reading of their magazine(s).

### Actual behavior

When a user load the homepage, one of the cover page is missing. He cannot access to all our content.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 94197
  cosmetic: 49415
  scriptlet: 16440
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26050-23, 2h.51m
    easylist: 62576-174, 2h.50m
    easyprivacy: 26599-343, 2h.49m
    plowe-0: 3681-824, 4d.17h.21m
    ublock-abuse: 72-1, 2h.48m
    ublock-badware: 3560-72, 2h.46m
    ublock-filters: 30032-312, 2h.45m
    ublock-privacy: 185-3, 2h.44m
    ublock-unbreak: 1709-39, 2h.43m
    urlhaus-1: 7568-0, 1d.2h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1627 ms (selfie)
```
</details>

**Comment by okiehsch** [comment]
@Alex-302

`kiosque.canardpc.com#@#.pub468`

**Comment by AdamWr** [comment]
Added, filters update should be available in 1-2 hours.

**Comment by margauxcleo** [comment]
Hello,
We still have the problem on the website. We have a new image, but still, you are blocking the all section.
Could you please do something about it ?

**Comment by uBlock-user** [comment]
@margauxcleo force update Adguard FRA: AdGuard Français list in uBO.

**Comment by margauxcleo** [comment]
@uBlock-user what do you mean by "force update FRA" ? Our clients are using the extension they want, and most of them re using uBlock.
We uBlock to allow our section.

**Comment by uBlock-user** [comment]
> Our clients are using the extension they want, and most of them re using uBlock.

Tell your clients to force update FRA: AdGuard Français list or add `kiosque.canardpc.com#@#.pub468`

**Comment by margauxcleo** [comment]
Ok. How can they force update FRA ? Where is it in the settings ? Thank you for your help.

**Comment by mapx-** [comment]
click "Purge all caches" - https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches 
then click "Update now" - https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by margauxcleo** [comment]
Great, thanks. 
Could you explain to me why the section was blocked ?

**Comment by uBlock-user** [comment]
Due to presense of `.pub468` class in one of the divs(use dev tools to inspect the site source), removal of this class will not cause such blockage to occur in the first place.

`https://kiosque-canardpc-beta.immanens.com/home` doesn't have this class and as a result this issue didn't occur there.

**Comment by okiehsch** [comment]
> what do you mean by "force update FRA" ?  Our clients are using the extension they want, and most of them re using uBlock.

The list also auto-updates every 4 days so everybody will get the fix in the next few days even if they don't force an update.
