### ISSUE TITLE
anime-loads.org: breakage

### ISSUE THREAD

**Issue by Kokujou** [uBlockOrigin/uAssets#11196]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.anime-loads.org/jdownloader-cnl?red=a6aaf837ae2291b4898244cb63b1c717`

### Category

breakage

### Describe the issue

this site tries to communicate with the JDownloader to add a certain amount of links to it. this connection is not working anymore when combined with uBlock, which is a huge issue

anime-loads.org has tons of adverts and popups. disabling uBlock results in tons of spams and popups

if the given speicfic URL does not work do the following steps:
1. go to anime-loads.org
2. pick an anime
3. go to the download section 
4. pick "click & load"
5. fill the captcha
6. start your JDownloader
7. select any host
8. a new tab will appear. after a while it should become red stating that it was not able to connect to JDownloader

NOTE: it might need you to register. so i will try to provide additional information so you don't need to actually visit the page

List of blocked content:
```
anime-loads.org
www.anime-loads.org
127.0.0.1
hwcdn.net
cds.s5x3j6q5.hwcdn.net
code.jquery.com
jquery.com
code.jquery.com
usfinf.net
cdn.usfinf.net
```

### Screenshot(s)

<details>
<summary>uBlock popup on the questioned page</summary>

![grafik](https://user-images.githubusercontent.com/13001250/148138659-cd2bf404-c828-402b-9715-212f4ee0e35b.png)

</details>

<details>
<summary>uBlock popup on the questioned page</summary>
![grafik](https://user-images.githubusercontent.com/13001250/148138727-24cb59b0-32b0-4768-9fca-b3331e32d4f4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 129436
  cosmetic: 184734
  scriptlet: 32547
  html: 624
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.10h.6m
    adguard-generic: 61489-4651, 2d.14h.27m
    adguard-mobile: 7028-161, 2d.14h.26m
    adguard-spyware: 24662-929, 2d.14h.24m
    adguard-spyware-url: 419-3, 2d.14h.23m
    block-lan: 44-0, 5d.5h.16m
    adguard-annoyance: 48762-4147, 2d.14h.21m
    adguard-social: 15330-20, 2d.14h.20m
    fanboy-thirdparty_social: 68-0, 2h.9m
    fanboy-annoyance: 62674-47681, 2h.8m
    fanboy-cookiemonster: 21266-124, 2h.7m
    fanboy-social: 23136-1083, 2d.14h.19m
    ublock-annoyances: 4357-4, 2d.14h.18m
  default: 
    ublock-filters: 30608-64, 2d.14h.34m
    ublock-badware: 3663-5, 2d.14h.32m
    ublock-privacy: 183-0, 2d.14h.31m
    ublock-abuse: 81-0, 2d.14h.30m
    ublock-unbreak: 1719-0, 2d.14h.28m
    easylist: 62457-767, 2d.14h.25m
    easyprivacy: 26580-10848, 2d.14h.22m
    urlhaus-1: 7408-0, 2h.6m
    plowe-0: 3682-3, 1d.6h.4m
    DEU-0: 5136-2, 2h.5m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 25 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 247 ms (selfie)
popupPanel: 
  blocked: 19
```
</details>

**Comment by mapx-** [comment]
Keep ON only the default lists, test then again

**Comment by Kokujou** [comment]
okay... i just did a complete reset and it works... i'm so sorry, i guess now i need to file an issue with the specific filter list which was causing the problem... i'm incredibly sorry i was sure i ticked no additional lists, but my memory must've been wrong.

**Comment by uBlock-user** [comment]
> I have no custom filter lists, or I verified that the issue still occurs without custom filter lists

You certainly did not do that, otherwise the issue would have resolved itself before you having to report here.

**Comment by gwarser** [comment]
Likely caused by "Block Outsider Intrusion into LAN" list. JDownloader doc: https://jdownloader.org/knowledge/wiki/glossary/cnl2

Check if adding this will work:

    @@||127.0.0.1:9666$domain=anime-loads.org

It will need to be added for each website using this feature.
