### ISSUE TITLE
appsmodz.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11199]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.appsmodz.com/2021/11/0.html?m=1#?o=f75bd512899107f055ce3aa16990098ed4a6ff07c5acb23c4d847d5959c2c0221b26b9d7f4038e4921ebd59cf6e6365eb7812ee536a8e1627c8eea110a9bf8d533b25e0114c4760772ac4ccf5b0f0bf6075ce02d6dd069fd`

### Category

detection

### Describe the issue

1. Wait until 100% and click on button `Get Link`
2. Wait for the button `Go to Link` and click on it
3. At the next page, an anti-adblock overlay appears

Proposed filters:

```
appsmodz.com##+js(no-xhr-if, googlesyndication)
appsmodz.com##.sticky-ads
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/148203852-454de205-e93d-447b-91b4-4593496ad0a3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77892
  cosmetic: 40300
  scriptlet: 16366
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30621-30, 1h.42m
    ublock-badware: 3652-1, 1h.42m
    ublock-privacy: 182-0, 1h.42m
    ublock-abuse: 76-0, 1h.42m
    ublock-unbreak: 1721-0, 1h.42m
    easylist: 62630-579, 1h.42m
    easyprivacy: 26597-481, 1h.42m
    urlhaus-1: 7251-0, 1h.42m
    plowe-0: 3683-2, 1h.42m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 660 ms
popupPanel: 
  blocked: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Same situation with the site `apkowner.org`

URL:
`https://apkowner.org/vidmate-video-downloader/`

Proposed filter:

`apkowner.org##+js(no-xhr-if, googlesyndication)`

**Comment by GodDeepak** [comment]
Why can't you support the site with Ads? You fucking worms.
