### ISSUE TITLE
https://www.shopfirstlinebenefits.com/Default

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#11207]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.shopfirstlinebenefits.com/Default`

### Describe the issue

Chat broken

### uBlock Origin version

1.40.4

### Browser name and version

Chrome 96

### Settings

Default

### Notes

`@@||chat.conveyhs.com/ChatAdapter/clickstream/clickStream.js$script,domain=shopfirstlinebenefits.com`

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Don't have a login to test, so no action.

**Comment by terrorist96** [comment]
@ryanbr Can be tested without login.

![image](https://user-images.githubusercontent.com/12802056/148420872-d3f61542-da64-4559-8e44-b319ae818bad.png)

**Comment by mapx-** [comment]
fixed by EL
https://github.com/easylist/easylist/commit/801582dd87a1697bdc87129a41bd08f97dc208eb
