### ISSUE TITLE
NSFW shyav.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1120]
URL(s) where the issue occurs

http://shyav.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xqk94524** [comment]
please, mark NSFW for those sites

**Comment by xqk94524** [comment]
`shyav.com##script:inject(set-constant.js, blockAdBlock, true)`
try

**Comment by xqk94524** [comment]
`shyav.com##script:inject(bab-defuser.js)`
please, returns if it works for you.
