### ISSUE TITLE
[nsfw] history.com: ads

### ISSUE THREAD

**Issue by Acoles005** [uBlockOrigin/uAssets#11205]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.history.com/`

### Category

ads

### Describe the issue

Wont allow students to watch any sources of videos for them to watch the video.

![Screenshot 2022-01-05 2 54 22 PM](https://user-images.githubusercontent.com/97193569/148280489-741a5c19-8c7d-42ea-a53f-401c32729e26.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-01-05 2 54 22 PM](https://user-images.githubusercontent.com/97193569/148280530-5192db1d-0e57-4c52-8e51-ba5abc6c5a12.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 79065
  cosmetic: 40233
  scriptlet: 16390
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62493-8, 2d.16h.30m
    easyprivacy: 26589-17, 2d.16h.29m
    plowe-0: 3683-817, 15m
    ublock-abuse: 72-0, 2d.16h.28m
    ublock-badware: 3509-63, 2d.16h.27m
    ublock-filters: 30036-140, 2d.16h.26m
    ublock-privacy: 182-12, 2d.16h.25m
    ublock-unbreak: 1708-39, 2d.16h.24m
    urlhaus-1: 8656-0, 13m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5500 ms
popupPanel: 
  blocked: 10
```
</details>

**Comment by Acoles005** [comment]
Plz change this

**Comment by gwarser** [comment]
https://www.history.com/topics/folklore/history-of-witches

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/148285086-dbcb9968-4276-4e56-8dd0-fe80463b9bd0.png)

**Comment by AntiAdvert** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134655
