### ISSUE TITLE
toptal.com: ads

### ISSUE THREAD

**Issue by mattalexx** [uBlockOrigin/uAssets#11209]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.toptal.com/developers/gitignore`

### Category

ads

### Describe the issue

There is a scrolling ad bar at the bottom of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://i.imgur.com/yG5bAzT.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 79397
  cosmetic: 40119
  scriptlet: 16211
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 16h.2m
  default: 
    easylist: 62652-9, 4h
    easyprivacy: 26601-17, 3h.58m
    plowe-0: 3716-818, 10d.22h.41m
    ublock-abuse: 76-0, 3h.56m
    ublock-badware: 3648-65, 3h.54m
    ublock-filters: 29782-133, 3h.52m
    ublock-privacy: 191-12, 3h.50m
    ublock-unbreak: 1738-39, 3h.48m
    urlhaus-1: 8445-0, 20h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 309
  launchFromSelfie: true
popupPanel: 
  blocked: 2
```
</details>

**Comment by mattalexx** [comment]
FYI, that screenshot was using a new Ungoogled Chromium profile, which is different from the browser I used to file this issue.

**Comment by mapx-** [comment]
self promotion
