### ISSUE TITLE
noviello.it: detection

### ISSUE THREAD

**Issue by Yuukiiro** [uBlockOrigin/uAssets#11204]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://noviello.it/es/como-hacer-operaciones-matematicas-con-javascript/`

### Category

detection

### Describe the issue

Shows popup when detects the adblck.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 80757
  cosmetic: 44614
  scriptlet: 16584
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62457-8, 3d.55m
    easyprivacy: 26597-18, 10h.8m
    plowe-0: 3715-818, 11d.6h.9m
    spa-0: 3570-21, 1d.56m
    spa-1: 4173-159, 10h.15m
    ublock-abuse: 76-0, 10h.9m
    ublock-badware: 3539-64, 10h.12m
    ublock-filters: 30046-197, 10h.13m
    ublock-privacy: 182-12, 10h.11m
    ublock-unbreak: 1678-41, 10h.7m
    urlhaus-1: 7408-0, 1d.57m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3161 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by mapx-** [comment]
Are you using brave browser ? if the shields are ON for this site you'll get anti adb stuff
@Yuki2718

**Comment by uBlock-user** [comment]
To reproduce just enable ITA: ABP X Files. bait is `.adsbox`

**Comment by okiehsch** [comment]
` ITA: ABP X Files` is not enabled by default for users with an italian locale.

**Comment by uBlock-user** [comment]
So only EasyList Italy ? @gorhill

**Comment by okiehsch** [comment]
> So only EasyList Italy

Yes.

**Comment by okiehsch** [comment]
> So only EasyList Italy

Yes. 

![image](https://user-images.githubusercontent.com/16838044/148360558-cef0c95b-3209-41d9-9e81-c17c2cb6bad9.png)

**Comment by Yuki2718** [comment]
I don't see anti-adb even with `.adsbox` blocked and instead see bab only if Brave Shield enabled as suggested by @mapx- . This may be con-argument for removing specific bab filters as `noviello.it##+js(nosiif, visibility, 1000)` blocks that even with Shield enabled, tho keeping it enabled is ofc bad idea.

**Comment by Yuki2718** [comment]
But in any case generic `##.adsbox` is bad filter, already removed from all AG lists: https://github.com/AdguardTeam/AdguardFilters/commit/d1c0942f4a058dc651fc9f1847c7217817ea2b87 So I'll add `#@#.adsbox`.

**Comment by okiehsch** [comment]
Why? The filter is in a non default list.
 I am sure there are many lists out there with "bad filters". 
We can't "fix" all of those in our lists.

**Comment by uBlock-user** [comment]
@Yuki2718 --
![Capture](https://user-images.githubusercontent.com/21290713/148362927-1c428287-4d9a-4a2c-9160-a8d0d3b2aaf6.PNG)

That's how it looks like.

**Comment by okiehsch** [comment]
I am in favour of removing `ITA: ABP X Files` from the regional list.
As far as I can see it's the only one in there that's not enabled by default.

**Comment by uBlock-user** [comment]
We shouldn't bother with non-default lists. That's not under our purview. I'm rather curious as to why it's not enabled by default like we have for SPA and POL locales.

**Comment by Yuki2718** [comment]
@uBlock-user Oh, I missed that.

**Comment by Yuki2718** [comment]
> Why? The filter is in a non default list. I am sure there are many lists out there with "bad filters". We can't "fix" all of those in our lists.

You're right. I'll revert the commit.

**Comment by okiehsch** [comment]
> like we have for SPA and POL locales.

For the spanish lists, one of them is spanish and portuguese.
For the polish lists, one of them deals with anti adblock issues specifically, the other one refuses to fix those.

**Comment by uBlock-user** [comment]
Has @gorhill stated that anywhere before ?

**Comment by okiehsch** [comment]
> stated that anywhere before ?

What exactly?
If you mean the polish lists, I remember the discussion when the main polish list started to refuse fixing anti adblock issues and the second list was created because of that.

**Comment by uBlock-user** [comment]
> What exactly?

The specific reasons you mentioned in https://github.com/uBlockOrigin/uAssets/issues/11204#issuecomment-1006421972

**Comment by okiehsch** [comment]
I think he was involved in the reasons for the polish ones as I said above.
If I remember correctly the two spanish lists were always enabled by default, so the reason I gave is just a guess on my part.

**Comment by uBlock-user** [comment]
I don't see how ITA: ABP X Files complements EL list like the SPA and POL lists do. So removal is not a bad idea.

**Comment by gorhill** [comment]
I'm going to remove ABP X Files, I see filters that are unrelated to ITA sites in there -- I probably added this list in the very early days when I was less strict about which lists were added.

**Comment by gioxx** [comment]
So, a list that has been around since the dawn of time and is very much used in Italy, is removed because there is a filter that does not work properly, all without even pinging me that in a few seconds I could have eliminated that filter remedying the problem.
It seems to me that the reasoning does not make a fold.

**Comment by gorhill** [comment]
_"ABP X Files"_ was the only regional list left not being enabled by default -- I removed many such lists in the past to ensure that the section is used only for lists which are enabled by default in any of country/language.

**Comment by gioxx** [comment]
Don't worry @gorhill, I can understand your argument but don't agree with it for the very reasons stated above. I still strongly support the choice of uBlock for any X Files user and will do so again in the future, I will simply point out via documentation / official X Files website that it will now need to be added manually or go through filterlists.com.

**Comment by BPower0036** [comment]
> > stated that anywhere before ?
> 
> What exactly? If you mean the polish lists, I remember the discussion when the main polish list started to refuse fixing anti adblock issues and the second list was created because of that.

As EasyList Dutch is also refusing to fix anti-adblock (see: https://github.com/easylist/easylistdutch/pull/11#issuecomment-818864565; https://github.com/easylist/easylistdutch/issues/30#issuecomment-1011180477)
and [EasyDutch](https://github.com/BPower0036/AdBlockFilters) does fix it and is specific for uBlock
maybe you(@gorhill) could add it as Dutch default?

**Comment by gorhill** [comment]
> EasyList Dutch is also refusing to fix anti-adblock

Maintainer could add `!#include ...` directives to load the rules for uBO, ABP will ignore this.

**Comment by JohnyP36** [comment]
> Ok I see, you are the maintainer of EasyDutch. So if I understand correctly, you mirror EasyList Dutch, but further include filters for uBO's syntax. From what I see in the repo, this seems like a good move to replace EasyList Dutch with EasyDutch. @mapx, @okiehsch, @uBlock-user etc any thoughts?
> 
> When I enable both EasyList Dutch and EasyDutch, I see ~700 filters rejected as duplicate in EasyDutch, while there are 1230 filters in EasyList Dutch. Why the discrepancy?

An important reason for this is that EasyList Dutch contain a bunch outdated rules. 
Also EasyList Dutch and EasyDutch blocks elements on a different way. 
Example: 
https://github.com/JohnyP36/Personal-List/commit/9b62d78aa92c603c3eafb397cf404a80c897f6a0 : `meerdangewenst.nl##[class*="footer-section"]:has(.sponsoren)` 
versus EasyList Dutch https://github.com/easylist/easylistdutch/commit/7626f32f6bdad35c749713e4d5b495a3b1cb13c0#diff-0582a3da4495ad4b284040b5cd6a21085b67befc5d5fa6dedf71acf692e12d7cR407 : `meerdangewenst.nl##.tg-site-footer-section-1`
I guess this makes the difference of ~500.

##### Btw, I also have a mirror of EasyList Dutch, but EasyDutch is run by my brother.

**Comment by uBlock-user** [comment]
>  @uBlock-user etc any thoughts?

Sure, if you feel like giving him a second chance after https://github.com/gorhill/uBlock/commit/9e394aa02b9451466fa7f1cca3f7ef9ee2d3d40b

**Comment by JohnyP36** [comment]
> > @uBlock-user etc any thoughts?
> 
> Sure, if you feel like giving him a second chance after [gorhill/uBlock@9e394aa](https://github.com/gorhill/uBlock/commit/9e394aa02b9451466fa7f1cca3f7ef9ee2d3d40b)

[You could use my list. Wich is almost the same](https://github.com/JohnyP36/Personal-List/blob/main/Personal%20List%20(uBo).txt) 
My repo is: https://github.com/JohnyP36/Personal-List

**Comment by uBlock-user** [comment]
@JohnyP36 You also run a public list for NLD locale ?

**Comment by JohnyP36** [comment]
> @JohnyP36 You also run a public list for NLD locale ?

Yes

**Comment by BPower0036** [comment]
> > EasyList Dutch is also refusing to fix anti-adblock
> 
> Maintainer could add `!#include ...` directives to load the filters for uBO, ABP will ignore this.
> 
> Ok I see, you are the maintainer of EasyDutch. So if I understand correctly, you mirror EasyList Dutch, but further include filters for uBO's syntax. From what I see in the repo, this seems like a good move to replace EasyList Dutch with EasyDutch. @mapx, @okiehsch, @uBlock-user etc any thoughts?
> 
> When I enable both EasyList Dutch and EasyDutch, I see ~700 filters rejected as duplicate in EasyDutch, while there are 1230 filters in EasyList Dutch. Why the discrepancy?

To add to @JohnyP36 reaction: there are a lot of general filterrules in EasyList Dutch which I deleted, because i could never reproduce anymore.

> > @uBlock-user etc any thoughts?
> 
> Sure, if you feel like giving him a second chance after [gorhill/uBlock@9e394aa](https://github.com/gorhill/uBlock/commit/9e394aa02b9451466fa7f1cca3f7ef9ee2d3d40b)

Yes, I would be nice if you give me a second change. 
I promise you I'm not going break your trust anymore

**Comment by BPower0036** [comment]
> @JohnyP36 You also run a public list for NLD locale ?

Yes, he does.
But my list [EasyDutch](https://github.com/BPower0036/AdBlockFilters/) is spesific for uBlock Origin with standard lists enabled. While @JohnyP36 list is not and support also Adguard.

**Comment by JohnyP36** [comment]
> > @JohnyP36 You also run a public list for NLD locale ?
> 
> Yes, he does. But my list [EasyDutch](https://github.com/BPower0036/AdBlockFilters/) is spesific for uBlock Origin with standard lists enabled. While @JohnyP36 list is not and support also Adguard.

Partly true, Adguard recognizes uBlock syntax. 
But my rules are according the uBlock syntax rules.

**Comment by Yuki2718** [comment]
> To give some examples: `$3p` vs `$third-party` `$xhr` vs `$xmlhttprequest` `$1p` vs `$first-party` And thing like this: `#?#.text-center:-abp-contains(advert)` in stead of `##.text-center:has(advert)`

These are no problem.

**Comment by mapx-** [comment]
It would be an advantage for all of us to replace `EasyList Dutch` by @BPower0036 list. 
You could (@BPower0036 @JohnyP36 ) collaborate to keep / maintain just one single list.

**Comment by BPower0036** [comment]
@mapx- To say the truth, I made my list first. But somehow @JohnyP36 also wanted a list for himself.
But we can collaborate, that is very easy since we are brothers and live in one house

**Comment by BPower0036** [comment]
@gorhill Since i can't comment on [your commit](https://github.com/gorhill/uBlock/commit/61966254cd7042f06e8f8e5a3e9d000cfb575c5c).

Can you use as contentURL https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt
as I (we) now use `gh-pages`?

**Comment by BPower0036** [comment]
@gorhill 
As I see that the `LTU` and `NOR` lists has `cdnURLs` can you also add cdnURLs to EasyDutch list, or some of them?
Our cdnURLs are:
 - https://combinatronics.io/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt
 - https://cdn.statically.io/gh/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt
 - https://cdn.jsdelivr.net/gh/EasyDutch-uBO/EasyDutch@gh-pages/EasyDutch.txt
 - https://gitlab.com/BPower0036/EasyDutch/-/raw/gh-pages/EasyDutch.txt
 - https://cdn.statically.io/gl/BPower0036/EasyDutch/raw/gh-pages/EasyDutch.txt

**Comment by gorhill** [comment]
Done: <https://github.com/gorhill/uBlock/commit/3af9cd2b71c5acabc4b86ec30b9a4eb3a8ef8265>

**Comment by BPower0036** [comment]
@gorhill I don't know if `https://github.com/uBlockOrigin/uBlock-issues/issues/` is the correct place to ask.

But here are the new CDN's, because I made `https://easydutch-ubo.github.io/EasyDutchCDN/`
```
https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt
https://easydutch-ubo.github.io/EasyDutchCDN/EasyDutch.txt
https://cdn.statically.io/gh/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt
https://cdn.jsdelivr.net/gh/EasyDutch-uBO/EasyDutch@gh-pages/EasyDutch.txt
https://cdn.statically.io/gh/EasyDutch-uBO/EasyDutchCDN/main/EasyDutch.txt
https://cdn.jsdelivr.net/gh/EasyDutch-uBO/EasyDutchCDN@main/EasyDutch.txt
```
