### ISSUE TITLE
[nsfw] south-plus.net: ads

### ISSUE THREAD

**Issue by loveqianool** [uBlockOrigin/uAssets#11208]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.south-plus.net/`

### Category

ads

### Describe the issue

ads Screenshot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-01-06 121007](https://user-images.githubusercontent.com/739497/148326874-73290229-41f5-459e-ae07-6beb929ef13a.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 95487
  cosmetic: 50174
  scriptlet: 16495
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 27233-87, 3d.17h.50m
    easylist: 62457-16, 3d.17h.48m
    easyprivacy: 26580-43, 3d.18h.2m
    plowe-0: 3715-820, 11d.21h.5m
    ublock-abuse: 81-0, 3d.18h
    ublock-badware: 3659-66, 3d.17h.58m
    ublock-filters: 30104-159, 3d.17h.56m
    ublock-privacy: 195-3, 3d.17h.54m
    ublock-unbreak: 1704-40, 3d.17h.52m
    urlhaus-1: 7804-0, 3m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 43 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1193
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
`south-plus.net##[onclick*="'ad'"]`

@Yuki2718
