### ISSUE TITLE
track.shipstation.com: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11201]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://track.shipstation.com/f/r/c/trQUQYvSda0izFiOeWVMww%3D%3D`

### Category

breakage

### Describe the issue

Page loads without showing order cell to fill out.

Proposed filter:

`||track.shipstation.com/collections/trackingEvents.js$script,redirect-rule=noopjs,1p`

### Screenshot(s)

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148215212-784c3010-313a-44bd-b290-0d32ac06d34d.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148215265-dc5d7b7d-4b1f-4138-ae94-1a6fa6e85394.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77892
  cosmetic: 40300
  scriptlet: 16366
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30621-143, 3h.10m
    ublock-badware: 3652-1, 3h.10m
    ublock-privacy: 182-0, 3h.10m
    ublock-abuse: 76-0, 3h.10m
    ublock-unbreak: 1721-0, 3h.10m
    easylist: 62630-466, 3h.10m
    easyprivacy: 26597-481, 3h.10m
    urlhaus-1: 7251-0, 3h.10m
    plowe-0: 3683-2, 3h.10m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 660 ms
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr
