### ISSUE TITLE
lavanguardia.com: detection

### ISSUE THREAD

**Issue by gitbobbed** [uBlockOrigin/uAssets#11202]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lavanguardia.com/vida/20211221/7945082/abierta-vacunacion-tercera-dosis-55-59-anos-catalunya.html`

### Category

detection

### Describe the issue

Asks to disable ad blocker in order to access content. (Disabling javascript entirely removes the warning, but couldn't verify whether that breaks other parts of the site).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox: 95
filterset (summary): 
  network: 92950
  cosmetic: 150905
  scriptlet: 21494
  html: 624
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48798-4100, 23h.40m
    adguard-social: 15333-17, 23h.37m
    fanboy-thirdparty_social: 68-0, 23h.38m
    fanboy-annoyance: 62674-47676, 23h.35m
    fanboy-cookiemonster: 21266-125, 23h.36m
    fanboy-social: 23138-1083, 23h.39m
    ublock-annoyances: 4362-4, 23h.41m
  default: 
    ublock-filters: 30618-101, 23h.51m
    ublock-badware: 3652-1, 23h.50m
    ublock-privacy: 182-0, 19h.17m
    ublock-abuse: 76-0, 23h.47m
    ublock-unbreak: 1720-0, 23h.46m
    easylist: 62610-651, 23h.45m
    easyprivacy: 26598-505, 23h.44m
    urlhaus-1: 7938-0, 23h.43m
    plowe-0: 3715-2, 11d.17m
    spa-0: 3570-2, 23h.52m
    spa-1: 4173-98, 23h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 636 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by gorhill** [comment]
I can reproduce.

**Comment by gorhill** [comment]
This works:

    lavanguardia.com##.ev-open-modal-paywall-ADB_DETECTION
    lavanguardia.com##body:style(overflow:auto!important;position:initial!important)

**Comment by mapx-** [comment]
or
`||rsc.lavanguardia.com/js/godo-didomix$script,domain=1p`

**Comment by gorhill** [comment]
`||rsc.lavanguardia.com/js/godo-didomix$script,domain=1p` does not work on my side.

**Comment by gorhill** [comment]
So we need to fix this in our list since neither EasyList or AdGuard block these hard walls be default?

**Comment by mapx-** [comment]
I guess so .. 

another working filter

`lavanguardia.com##+js(no-xhr-if, notifier)`

**Comment by gorhill** [comment]
Your network filter is best solution imo, I will let you add it

**Comment by PIZZA90** [comment]
whit the filter: `||rsc.lavanguardia.com/js/godo-didomix$script,1p` 
this issue: `https://github.com/uBlockOrigin/uAssets/issues/7961` is back

**Comment by PIZZA90** [comment]
And also the login button to access the site is broken (marked whit red arrow)

`https://www.lavanguardia.com/vida/20211221/7945082/abierta-vacunacion-tercera-dosis-55-59-anos-catalunya.html`

![Captura333](https://user-images.githubusercontent.com/33556647/151717245-4438e88a-8de9-496b-84b4-fed2a0663e63.PNG)

**Comment by mapx-** [comment]
@PIZZA90 is this one better ?

`lavanguardia.com##+js(no-xhr-if, notifier)`

**Comment by PIZZA90** [comment]
I dont know.. because i cant reproduce AntiAdblock in this site, but I see that you do reproduce it.. At least I see it in the comments of this post 🤔

**Comment by mapx-** [comment]
add & check for breakages

```
||rsc.lavanguardia.com/js/godo-didomix$script,1p,badfilter
lavanguardia.com##+js(no-xhr-if, notifier)
```

**Comment by PIZZA90** [comment]
works well.. but this message of the below image no is a AntiAdblock, that forces you to register to continue reading

![Captura455](https://user-images.githubusercontent.com/33556647/151718044-fbda6f72-92f4-4b18-88ab-4d8c9181614e.PNG)

but if is blocked much better

really i dont know how the AntiAdblock looks

**Comment by mapx-** [comment]
the anti adb is looking like this

![image](https://user-images.githubusercontent.com/10303732/151718178-7790da8e-c736-49f5-aa53-8de7d55083ad.png)

**Comment by PIZZA90** [comment]
okok.. i cant reproduce anyways

```
||rsc.lavanguardia.com/js/godo-didomix$script,1p,badfilter
lavanguardia.com##+js(no-xhr-if, notifier)
```

this filters much better

**Comment by PIZZA90** [comment]
fix this filter:  `lavanguardia.com#@#+js(abort-on-property-read, adsCfg)`

no loading videos for example here:
`https://www.lavanguardia.com/vida/20220114/7980770/roenlared-anorexia-nerviosa-amor-toxico-mujeres-viajeras-renfe-brl.html`

Whitelisting that filter the video load:
`lavanguardia.com#@#+js(abort-on-property-read, adsCfg)`

**Comment by PIZZA90** [comment]
hi, updating a bit this site.. video no works

**URL**: 
`https://www.lavanguardia.com/politica/20220302/8093092/sanchez-anuncia-espana-entregara-resistencia-ucraniana-material-militar-ofensivo.html`


**Filter working**: 
`@@||sb.scorecardresearch.com/internal-c2/default/streamingtag_plugin_jwplayer.js$script,domain=lavanguardia.com`

Maybe need fix in any list here?

![Captura21312](https://user-images.githubusercontent.com/33556647/156386035-aea90428-0f9b-4c43-afbd-3066322e18ac.PNG)

In picture:

- Easyprivacy **Withelisted**
- Peter Lowe’s Ad and tracking server list **Blocked**

**Comment by mapx-** [comment]
update your lists, both scorecardresearch are whitelist by easyprivacy list

**Comment by PIZZA90** [comment]
are you sure? I check again but not working

example in the video of this post: `https://www.lavanguardia.com/politica/20220308/8107262/europa-interesa-sur.html`

**Comment by mapx-** [comment]
ok, needing

`@@||sb.scorecardresearch.com/internal*/streamingtag_plugin_jwplayer.js$script,domain=lavanguardia.com`

**Comment by mapx-** [comment]
@ryanbr EP issue
