### ISSUE TITLE
konsumentverket.se: breakage

### ISSUE THREAD

**Issue by rojona** [uBlockOrigin/uAssets#11214]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.konsumentverket.se/for-konsument/anmal-till-konsumentverket/anmalan/`

### Category

breakage

### Describe the issue

The website reports that it encountered a script error when clicking the submit button to send a form with text fields filled in. Firefox also crashed once before when doing the same thing. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 96
filterset (summary): 
  network: 81691
  cosmetic: 23880
  scriptlet: 16655
  html: 668
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30750-271, 3h.42m
    ublock-badware: 3652-1, 3h.41m
    ublock-privacy: 179-1, 3h.40m
    ublock-abuse: 76-0, 3h.39m
    ublock-unbreak: 1729-0, 3h.38m
    adguard-mobile: 7040-173, 19m
    easylist: 62686-24210, 21m
    easyprivacy: 26604-502, 20m
    urlhaus-1: 8145-0, 3h.37m
    plowe-0: 3682-2, 4d.16h.16m
    SWE-1: 3981-329, 3h.43m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 885 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/148438927-32750cad-1626-4eef-805a-15a9b71eb3c2.png)

Maybe it's a mobile only issue.

**Comment by mapx-** [comment]
Disable any other addon in FF, test again

**Comment by mapx-** [comment]
@lassekongo83

**Comment by lassekongo83** [comment]
Can't reproduce on desktop. Unable to test on a phone.

**Comment by mapx-** [comment]
I get no crash / error:

![image](https://user-images.githubusercontent.com/10303732/148637643-7f70ac45-aa77-4e80-92eb-a1a3d42f4901.png)
