### ISSUE TITLE
bravotv.com: breakage

### ISSUE THREAD

**Issue by Timoise** [uBlockOrigin/uAssets#11217]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bravotv.com/the-real-housewives-of-orange-county/season-16/episode-1/fancy-pants-is-back`

### Category

breakage

### Describe the issue

The episode will not load if ad block is enabled. As soon as I turn off the ad block via the big power button for that page, and refresh, it will then begin loading an ad for that video/episode.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 77796
  cosmetic: 40228
  scriptlet: 16418
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62467-8, 4d.1h.21m
    easyprivacy: 26582-17, 4d.1h.23m
    plowe-0: 3683-817, 1d.23h.41m
    ublock-abuse: 76-0, 1d.3h.36m
    ublock-badware: 3648-65, 2d.22h.48m
    ublock-filters: 30151-138, 1d.3h.38m
    ublock-privacy: 191-12, 4d.1h.25m
    ublock-unbreak: 1704-39, 2d.22h.50m
    urlhaus-1: 7179-0, 1d.7h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 590
  launchFromSelfie: true
popupPanel: 
  blocked: 33
```
</details>

**Comment by mapx-** [comment]
open uBO logger, try again to load / see an episode, select in the logger only the blocked items and post here the screenshot(s) with those elements

**Comment by Timoise** [comment]
<img width="956" alt="BRAVOTVScreenshot1" src="https://user-images.githubusercontent.com/40238653/148612105-21bd9e74-a1e8-46cb-9ec6-39d5ba21a0f0.png">
<img width="947" alt="BravoTVScreenshot2" src="https://user-images.githubusercontent.com/40238653/148612116-42302af7-c52d-40bf-933c-cee9e07bf686.png">
<img width="951" alt="BRAVOTVScreenshot3" src="https://user-images.githubusercontent.com/40238653/148612125-06bdb04f-0481-4dce-aaab-5a6c0d4c1657.png">

**Comment by mapx-** [comment]
try 

```
@@||api.parsely.com^$xhr,domain=bravotv.com
@@||cdn.parsely.com^$script,domain=bravotv.com
@@||assets.adobedtm.com/extensions/*/AppMeasurement.$script,domain=bravotv.com
@@||jssdkcdns.mparticle.com/js/*/mparticle.js$script,domain=bravotv.com
```

**Comment by Timoise** [comment]
Just added those 4 lines of code to My Filters, but the same issue persists. Thank you for your help.

**Comment by Timoise** [comment]
For additional context, this is how the screen looks when ad block is enabled. I am already signed in, it is just stuck on this "Sign In with you provider" screen and is unclickable. If ad block is turned off and I refresh, this goes away and the episode starts to load, with an ad playing before the episode.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/40238653/148616948-f65dc77e-6a11-4abd-824c-dd0fd1adadd7.png">

**Comment by mapx-** [comment]
add also

`@@||assets.adobedtm.com/extensions/*/AppMeasurement$script,domain=bravotv.com`

if does work keep only this filter and see id still works

**Comment by Timoise** [comment]
That worked! Thank you so much.

**Comment by mapx-** [comment]
@ryanbr
