### ISSUE TITLE
zmovs.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1121]
URL(s) where the issue occurs

http://zmovs.com/video/PJPZeXRZ/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xqk94524** [comment]
use 

> Adguard Base Filters

works for me

**Comment by xqk94524** [comment]
![screenshot-2017-12-26 charming buxomy undergraduate roxy raye gets her tight ass fucked](https://user-images.githubusercontent.com/34273204/34359736-01903570-ea31-11e7-95af-e5aec9324c29.png)
