### ISSUE TITLE
services.wyze.com: breakage

### ISSUE THREAD

**Issue by portnoy** [uBlockOrigin/uAssets#11216]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://services.wyze.com/user/login`

### Category

breakage

### Describe the issue

![Screen Shot 2022-01-06 at 5 24 50 PM](https://user-images.githubusercontent.com/2074722/148476151-c5e70ece-8f78-4359-8fc1-daf973e70837.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78711
  cosmetic: 40252
  scriptlet: 16354
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30609-29, 3d.2h.44m
    ublock-badware: 3652-1, 3d.2h.43m
    ublock-privacy: 177-0, 3d.2h.42m
    ublock-abuse: 76-0, 3d.2h.41m
    ublock-unbreak: 1689-0, 3d.2h.40m
    easylist: 62549-195, 3d.2h.39m
    easyprivacy: 26594-51, 3d.2h.38m
    urlhaus-1: 8145-0, 1h.9m
    plowe-0: 3682-819, 3d.2h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 22923 ms
popupPanel: 
  blocked: 4
```
</details>

**Comment by gorhill** [comment]
Caused by EasyPrivacy's `||kaptcha.com^$3p`.

Solution:

    @@||ssl.kaptcha.com^$script,domain=wyze.com

cc @ryanbr, @Khrin
