### ISSUE TITLE
ytmp3.cc: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11212]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ytmp3.cc/uu100cc/`

### Category

breakage

### Describe the issue

Paste any youtube link to the box, an error occurs with the message:
```
An error occurred (message: empty input youtube url or country).

Please try to convert another video by click here.
```

Proposed filter:

`@@||ads-website.ytsservice.com/ads/address/country$xhr,domain=ytmp3.cc`

### Screenshot(s)

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148384283-7b9fb867-e01a-4d16-8e44-3ece59243631.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148384209-2deebb0b-8f15-470f-a379-484f97228509.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78483
  cosmetic: 40312
  scriptlet: 16386
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30654-30, 1h.7m
    ublock-badware: 3652-1, 1h.7m
    ublock-privacy: 182-0, 1h.7m
    ublock-abuse: 76-0, 1h.7m
    ublock-unbreak: 1723-0, 1h.7m
    easylist: 62657-579, 1h.7m
    easyprivacy: 26604-482, 1h.7m
    urlhaus-1: 7804-0, 1h.7m
    plowe-0: 3685-2, 1h.7m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 223 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by iam-py-test** [comment]
Problem is that with your filter is then there are ads:
![image](https://user-images.githubusercontent.com/84232764/148398152-d8590836-bb0b-43ad-a649-5655526330da.png)

**Comment by iam-py-test** [comment]
I found these filters fixed it:
```
ytmp3.cc##.a-inner:has(img[src*="cdn3.trafficad-biz.com/images/theme/210928_e3.jpg"])
||cdn3.trafficad-biz.com/images/theme/210928_e3.jpg^
```

**Comment by stephenhawk8054** [comment]
Hmmm... Weird, I don't see any ads or `trafficad-biz` domain when I tested it.

**Comment by uBlock-user** [comment]
> Problem is that with your filter is then there are ads:

I see no ads.

**Comment by ghajini** [comment]
youtube embed blocked by denyallow filter

try to enter any youtube video eg `https://www.youtube.com/watch?v=zkFZWqB4zic` at this website `ytmp3.cc`
& click play,nothing happens

& `ytmp3.*##+js(nowoif)` causing these buttons 
https://user-images.githubusercontent.com/20338483/154790821-dba7d809-8e63-4192-99f3-ac90038612f7.png

not work

so i don't see why it's required?
```
ytmp3.cc##+js(acis, Math, [$.)
ytmp3.cc##+js(acis, JSON.parse, [$.)
ytmp3.cc##+js(nowoif)
```
