### ISSUE TITLE
bingotingo.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11218]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bingotingo.com/how-to-use-kenba/`

### Category

detection

### Describe the issue

Wait about 10s after loaded, an anti-adblock overlay appears.

Proposed filter:

`bingotingo.com##+js(no-xhr-if, googlesyndication)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/148492837-6c410f28-478d-4738-b025-2eaa33c09a69.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78844
  cosmetic: 40319
  scriptlet: 16386
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30653-30, 4m
    ublock-badware: 3652-1, 4m
    ublock-privacy: 183-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1723-0, 4m
    easylist: 62693-581, 4m
    easyprivacy: 26606-482, 4m
    urlhaus-1: 8136-0, 3m
    plowe-0: 3685-2, 3m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 276 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by huyszn** [comment]
The site displays an "Adblock Enabled" overlay after 2 seconds (https://github.com/uBlockOrigin/uAssets/assets/46979193/1d8d2d27-9448-497c-a5a8-2bd4ecfbde25).

The filter `bingotingo.com##+js(rmnt, script, mdp)` seems to remove this overlay.
