### ISSUE TITLE
[nsfw] meijutt.tv: ads

### ISSUE THREAD

**Issue by yyk123** [uBlockOrigin/uAssets#11211]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.meijutt.tv/video/26974-1-6.html`

### Category

ads

### Describe the issue

can not  block gif ads

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 78370
  cosmetic: 40262
  scriptlet: 16396
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62484-8, 3d.10h.4m
    easyprivacy: 26589-17, 3d.10h.2m
    plowe-0: 3682-817, 3d.48m
    ublock-abuse: 76-0, 3d.10h
    ublock-badware: 3644-65, 3d.9h.57m
    ublock-filters: 30037-138, 3d.9h.55m
    ublock-privacy: 186-3, 3d.9h.53m
    ublock-unbreak: 1708-39, 3d.9h.51m
    urlhaus-1: 7804-0, 1h.35m
filterset (user): [array of 59 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 175 ms (selfie)
popupPanel: 
  blocked: 12
  no-scripting: false
```
</details>

**Comment by JobcenterTycoon** [comment]
Activate `CHN: AdGuard Chinese (中文)`
