### ISSUE TITLE
beta.crunchyroll.com: ads

### ISSUE THREAD

**Issue by Ventispurr** [uBlockOrigin/uAssets#11213]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://beta.crunchyroll.com/`

### Category

ads

### Describe the issue

Use to block all ADs on this website, until the new update on January 4th.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 73703
  cosmetic: 35777
  scriptlet: 7002
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62590-9, 1d.22h.50m
    easyprivacy: 26598-17, 1d.22h.49m
    plowe-0: 3683-817, 1d.6h.17m
    ublock-abuse: 72-0, 1d.22h.48m
    ublock-badware: 3648-65, 1d.13h.21m
    ublock-filters: 11960-30, 1d.12h.31m
    ublock-privacy: 185-3, 21h.7m
    ublock-unbreak: 1678-39, 21h.6m
    urlhaus-1: 7179-0, 21h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 249 ms (selfie)
popupPanel: 
  blocked: 21
```
</details>

**Comment by iam-py-test** [comment]
@Ventispurr please preform _all_ the preissue items **BEFORE** opening an issue
