### ISSUE TITLE
riteaid.com: breakage

### ISSUE THREAD

**Issue by radheyshah** [uBlockOrigin/uAssets#11226]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.riteaid.com/shop/promotions`

### Category

breakage

### Describe the issue

Nothing loads up with uBlock origin installed. Also the search on RiteAid's website won't work with default settings. If I disable uBlock origin, the search results show fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78449
  cosmetic: 40132
  scriptlet: 16184
  html: 596
listset (total-discarded, last updated): 
  added: 
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 266-4, 18h.43m
  default: 
    ublock-filters: 30274-29, 10h.35m
    ublock-badware: 3652-1, 3d.4h.2m
    ublock-privacy: 183-0, 10h.39m
    ublock-abuse: 76-0, 10h.40m
    ublock-unbreak: 1723-0, 10h.37m
    easylist: 62694-572, 10h.41m
    easyprivacy: 26606-484, 10h.38m
    plowe-0: 3716-2, 12d.14h.33m
    urlhaus-1: 7408-0, 18h.42m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 47 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4055 ms
popupPanel: 
  blocked: 12
```
</details>

**Comment by uBlock-user** [comment]
@@||rfksrv.com/rfk/js/*/init.js$script,domain=riteaid.com
