### ISSUE TITLE
Doesn't block an ad on youtube

### ISSUE THREAD

**Issue by ynsnf** [uBlockOrigin/uAssets#11228]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [ ] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com/

### Describe the issue

Doesn't block ad at the beginning of the video. I tried two different videos after this, and one of which had the same issue. It was a grammarly ad as shown in the screenshot.

### Screenshot(s)

![ad](https://user-images.githubusercontent.com/95400016/148634924-95b72f5a-7e0d-4384-9263-31285435f7e2.png)

### uBlock Origin version

uBlock Origin 1.40.4

### Browser name and version

Chromium Version 89.0.4389.128 (Official Build) snap 

### Settings

NA

**Comment by MasterKia** [comment]
> [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

"**avoid opening a duplicate issue**"
https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by MasterKia** [comment]
> * I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

> "**avoid opening a duplicate issue**"
#7636

**Comment by MasterKia** [comment]
> * I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue


"**avoid opening a duplicate issue**"
#7636

**Comment by gwarser** [comment]
@ynsnf what you did before this ad appeared?
