### ISSUE TITLE
picturelol.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1122]
URL(s) where the issue occurs

http://picturelol.com/t7c6hym3eea9/0.jpg

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xqk94524** [comment]
use

> Adguard Base Filters
