### ISSUE TITLE
seriouseats.com: breakage

### ISSUE THREAD

**Issue by kevinTenenbaum** [uBlockOrigin/uAssets#11222]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.seriouseats.com/sous-vide-glazed-carrots-recipe`

### Category

breakage

### Describe the issue

Recipes at the bottom of the page disappear in all Serious Eats articles when uBlock is turned on. they work normally when it is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 79060
  cosmetic: 40208
  scriptlet: 16396
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 266-4, 2d.13h.5m
  default: 
    easylist: 62457-8, 4d.17h.59m
    easyprivacy: 26580-17, 4d.18h.7m
    plowe-0: 3679-816, 11d.12h.45m
    ublock-abuse: 76-0, 4d.18h.5m
    ublock-badware: 3648-65, 23h.17m
    ublock-filters: 30112-138, 4d.18h.3m
    ublock-privacy: 195-3, 4d.18h.1m
    ublock-unbreak: 1740-39, 23h.15m
    urlhaus-1: 8145-0, 23h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3302
  launchFromSelfie: true
popupPanel: 
  blocked: 6
```
</details>

**Comment by gorhill** [comment]
I could not reproduce the issue with default filter lists. I could reproduce an issue with the custom list you added:

```yaml
listset (total-discarded, last updated): 
  added: 
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 266-4, 2d.13h.5m
```

You stated:

> To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disrespecting these steps **WILL** result in your account being blocked on this repo (temporarily, then permanently with repeated disregard for the template).
> ...
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> ...
> - [X] I did not answer truthfully to **all** the above checkpoints
