### ISSUE TITLE
Block with `advertisement` on www.howtogeek.com

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#11229]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.howtogeek.com/775869/critical-stats-every-pc-gamer-should-monitor/`

### Describe the issue

Between the text of the article are three grey boxes with the text `advertisement`. 
To block those I propose the rule: 
```
howtogeek.com##article > * > div[style]:has-text(/advert/i)
``` 

### Screenshot(s)

<summary>
<details>

![image](https://user-images.githubusercontent.com/81161435/148638844-7627b36e-7674-4819-ae39-56e3f91324e4.png)

</details>
</summary>

### uBlock Origin version

1.39.2 (This is the newest version in MS Edge)

### Browser name and version

MS Edge v.96

### Settings

<summary>
<details>

```
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 67246
  cosmetic: 42313
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/r/fanboy-complete.txt: 92378-93, 2h.26m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1926-3, 2h.26m
  default: 
    ublock-filters: 30162-208, 2h.17m
    ublock-unbreak: 1705-47, 2h.14m
filterset (user): [array of 147 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  launchToReadiness: 21998
  launchFromSelfie: false
```
</details>
</summary>

**Comment by mapx-** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
Use `##[data-nosnippet="data-nosnippet"]:has(.future_inline_clone_target)` so it can be added to EL.

**Comment by gorhill** [comment]
EasyList's `howtogeek.com##[data-nosnippet="data-nosnippet"]` is already blocking this.

**Comment by JohnyP36** [comment]
> Use `##[data-nosnippet="data-nosnippet"]:has(.future_inline_clone_target)` so it can be added to EL.

Or should it be `howtogeek.com##[data-nosnippet="data-nosnippet"]:has(.future_inline_clone_target)`?
So with `howtogeek.com` before the actual rule.
