### ISSUE TITLE
kuronime.tv: detection

### ISSUE THREAD

**Issue by Wahidin0** [uBlockOrigin/uAssets#11223]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kuronime.tv/`

### Category

detection

### Describe the issue

![Screenshot_20220107-220614_Firefox](https://user-images.githubusercontent.com/97299540/148563187-7d7821b6-b92b-4c22-bab0-13361a449b5f.jpg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 237794
  cosmetic: 283658
  scriptlet: 35789
  html: 715
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61535-5869, 3d.3h.13m
    adguard-spyware: 24520-1094, 3d.3h.13m
    adguard-spyware-url: 426-3, 3d.3h.14m
    block-lan: 44-0, 8h.41m
    curben-phishing: 11070-4, 1d.31m
    curben-pup: 385-0, 3h.33m
    adguard-annoyance: 48794-4471, 3d.3h.13m
    adguard-social: 15340-29, 3d.3h.14m
    fanboy-thirdparty_social: 68-0, 2d.7h.10m
    fanboy-annoyance: 62678-47730, 2d.7h.10m
    fanboy-cookiemonster: 21268-197, 2d.7h.10m
    fanboy-social: 23138-1088, 3d.3h.13m
    ublock-annoyances: 4382-8, 3d.3h.13m
    dpollock-0: 16948-1928, 8h.41m
    mvps-0: 8730-368, 8h.41m
    ara-0: 2330-0, 2d.5h.8m
    BGR-0: 1116-11, 1d.8h.22m
    CHN-0: 27257-168, 3d.3h.14m
    CZE-0: 778-0, 1d.31m
    DEU-0: 5159-4, 3h.33m
    [28 lists not shown]: [too many]
  default: 
    ublock-filters: 30713-436, 3d.3h.13m
    ublock-badware: 3652-1, 3d.3h.13m
    ublock-privacy: 182-0, 3d.3h.13m
    ublock-abuse: 76-0, 3d.3h.13m
    ublock-unbreak: 1727-0, 3d.3h.13m
    adguard-mobile: 7028-217, 3d.3h.14m
    easylist: 62581-1529, 3d.3h.13m
    easyprivacy: 26599-11125, 3d.3h.13m
    urlhaus-1: 8145-4, 1d.31m
    plowe-0: 3679-2, 11d.9h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1076 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by gorhill** [comment]
I get:

> Error 1020 Ray ID: 6c9e2bea3e0cca57 • 2022-01-07 15:20:41 UTC
> Access denied

When I try to navigate to `https://kuronime.tv/`.

**Comment by iam-py-test** [comment]
>  Access denied

I get the same thing both with + without VPN. Probably just a broken DDOS protection...

**Comment by mapx-** [comment]
Indonesia vpn

**Comment by Wahidin0** [comment]
iya pakai vpn indonesia atau malaysia
