### ISSUE TITLE
okdiario.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#11224]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://okdiario.com/espana/delirio-psoe-tudanca-dice-que-quien-tiene-que-dimitir-disparates-garzon-pp-8383975
https://okdiario.com/espana/alberto-garzon-pedro-sanchez-avala-informe-que-critica-modelo-carnico-espanol-como-peligro-salud-publica-8384225
```

### Describe the issue

I cant click in comments, and big **Ad places** maybe is causing the problem

### uBlock Origin version

1.40.4

### Browser name and version

Chrome - 97.0

### Settings

Default

**Comment by mapx-** [comment]
> I cant click in comments

meaning you don't see the comments after clicking that section ? I'm able to see them

**Comment by PIZZA90** [comment]
is break this site...

i cant click.. something in overlay.. i cant click in the blue "menu footer" neither

![Captura1](https://user-images.githubusercontent.com/33556647/148604675-d07231ef-2cca-4644-af7f-c9d0295cf36d.PNG)

**Comment by PIZZA90** [comment]
im sorry... i have `AdGuard Annoyances` active 
i dont know if is default list

**Comment by PIZZA90** [comment]
🤣🤣 maybe i turn ON for test this site: `https://github.com/uBlockOrigin/uAssets/issues/9448`

my bad

**Comment by mapx-** [comment]
```
@@||sdk.privacy-center.org/*/loader.js?target=okdiario.com$script,domain=okdiario.com
@@||sdk.privacy-center.org/sdk.$script,domain=okdiario.com
```
