### ISSUE TITLE
sohu.com: ads

### ISSUE THREAD

**Issue by Sucgz** [uBlockOrigin/uAssets#11234]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sohu.com/a/194959356_594016`

### Category

ads

### Describe the issue

There are ads on the right side of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 95844
  cosmetic: 50332
  scriptlet: 16497
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 2d.19h.33m
  default: 
    CHN-0: 27272-87, 3d.16h.8m
    easylist: 62658-414, 2d.15h.45m
    easyprivacy: 26597-43, 3d.20h.10m
    plowe-0: 3679-818, 7d.23h.7m
    ublock-abuse: 72-0, 2d.15h.47m
    ublock-badware: 3509-63, 2d.2h.5m
    ublock-filters: 30046-162, 3d.20h.11m
    ublock-privacy: 185-3, 2d.15h.48m
    ublock-unbreak: 1678-40, 2d.15h.49m
    urlhaus-1: 8136-0, 13h.3m
filterset (user): [array of 122 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 561 ms (selfie)
popupPanel: 
  blocked: 47
```
</details>

**Comment by Sucgz** [comment]
![NB(07@C4QCF2881GN E_%ZG](https://user-images.githubusercontent.com/31009504/148670586-2a0cafaf-cf62-4a01-98f6-41182694e905.png)

**Comment by gorhill** [comment]
Also unable to reproduce. In the DOM, I see something blocked in that area by AdGuard's:

    sohu.com##.hot-article > div.pic-txt[data-spm-content*="_saletype="]

I see you have 122 custom filters, did you really try without these?

**Comment by Sucgz** [comment]
可以过滤，但是这些广告数量太多了，手动建立很麻烦....
