### ISSUE TITLE
docero.com.br: detection

### ISSUE THREAD

**Issue by RENANZG** [uBlockOrigin/uAssets#11230]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://docero.com.br/doc/sn50c1v`

### Category

detection
 

### Describe the issue

This site (docero.com.br) is very good for downloading books, but it has very heavy advertisements. Blocker is being detected then I can't download, I need help.

Example: `https://docero.com.br/doc/8e5se55`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![sshot-2022-01-08-08-44-47](https://user-images.githubusercontent.com/53377291/148643279-b9a329e0-5774-40e0-8571-a490fc6a64f8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 78673
  cosmetic: 40313
  scriptlet: 16401
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62608-9, 3d.17h.46m
    easyprivacy: 26595-17, 3d.13h.45m
    plowe-0: 3679-816, 11d.19h.19m
    ublock-abuse: 76-0, 3d.13h.44m
    ublock-badware: 3560-64, 3d.13h.43m
    ublock-filters: 30041-143, 3d.13h.41m
    ublock-privacy: 185-3, 3d.13h.40m
    ublock-unbreak: 1710-39, 3d.13h.39m
    urlhaus-1: 8136-0, 19h.22m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5578 ms (selfie)
popupPanel: 
  blocked: 50
```
</details>

**Comment by gorhill** [comment]
Neither of the web pages you are mentioning can be loaded:

> This docero.com.br page can’t be found
> No webpage was found for the web address:
> `https://docero.com.br/doc/8e5se55`
> 
> HTTP ERROR 404

**Comment by mapx-** [comment]
I'm able to get the page.

@RENANZG enable the list bellow and test again:

spa, por: AdGuard Spanish/Portuguese

**Comment by RENANZG** [comment]
Thanks a lot!


spa, por: AdGuard Spanish/Portuguese solved my problem














Em 08/01/2022 às 04:03, Raymond Hill ***@***.***> escreveu:



Neither of the web pages you are mentioning can be loaded:


This docero.com.br page can’t be found
No webpage was found for the web address:
https://docero.com.br/doc/8e5se55

HTTP ERROR 404

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>
