### ISSUE TITLE
linkedin.com: space removed unnecessarily

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#11236]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.linkedin.com/feed/`

### Describe the issue

A space has been removed between the header and the body of the page for no reason. There is no ad in this removed space.

### Screenshot(s)

With uBlock Origin

![With uBlock Origin](https://user-images.githubusercontent.com/62190484/148677255-15a7ee9e-c5fe-4555-84e5-428282429b1a.jpg)

Without uBlock Origin

![Without uBlock Origin](https://user-images.githubusercontent.com/62190484/148677267-d90765bf-cf33-4e63-a637-47866c2ca409.jpg)

Log of requests

![Log of requests](https://user-images.githubusercontent.com/62190484/148677405-11f942ac-5d58-489e-b7e9-34967b8d0be6.jpg)

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 95.0.2

### Settings

No changes.

### Notes

No notes.

**Comment by mapx-** [comment]
`linkedin.com#@#.scaffold-layout__ad`

@ryanbr

**Comment by uBlock-user** [comment]
Hides a ad placeholder, so not hidden unnecessarily. You don't see the ad itself because it's blocked.

**Comment by fabriziobagala** [comment]
> `linkedin.com#@#.scaffold-layout__ad`
> 
> @ryanbr

Works 👍

**Comment by ryanbr** [comment]
Is it actually causing any issues? why even report.

**Comment by fabriziobagala** [comment]
> Is it actually causing any issues? why even report.

@ryanbr The only issue is brought about in the page layout. The purpose of an adblock is to block advertising while keeping the layout of a page unchanged. Unfortunately on this website the layout is changed. Using the filter specified by @mapx- , you can correctly display the page layout while keeping the ad blocked.

**Comment by fabriziobagala** [comment]
> Hides a ad placeholder, so not hidden unnecessarily. You don't see the ad itself because it's blocked.

@uBlock-user You are right. Hiding a placeholder that contains an ad is correct. Unfortunately, in this case, the placeholder is part of the page layout. Using the filter specified by @mapx- , you will see that the ad is blocked but the layout is displayed correctly.

**Comment by uBlock-user** [comment]
> Unfortunately, in this case, the placeholder is part of the page layout. 

It's not, it's an ad placeholder, when you block ads, you block placeholders too and sometimes that changes site layout. That's just it.
