### ISSUE TITLE
[uBO Legacy] OCSP breakage

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#11231]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

All HTTPS sites?

### Describe the issue

easylist/easylist@16c0c853300ea4c49213a47c4b22b5fa9837611c and easylist/easylist@ec763daf61c31e335a8bbea93e0712abeb343174 was recently added to EasyPrivacy to block all pings but it seems like uBO Legacy interprets `$ping` as `$other`. XUL extensions can still intercept all network requests in the browser so all OCSP requests are blocked for users who removed `behind-the-scene` from the default whitelist (which I do for various reasons). All Firefox browsers (legacy or not) still do not send pings by default and users can disable all ping-related prefs via `about:config` anyway. I therefore propose adding `$ping,domain=~hey.com,badfilter` to the legacy list.

### uBlock Origin version

uBlock Origin 1.16.4.30

### Browser name and version

N/A

### Settings

N/A

**Comment by uBlock-user** [comment]
> who removed behind-the-scene from the default whitelist

We don't add filters for users who veer off default settings of uBO.
