### ISSUE TITLE
online-fix.me: detection

### ISSUE THREAD

**Issue by vanya890** [uBlockOrigin/uAssets#11239]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://online-fix.me/games/survival/16328-project-winter-po-seti.html`

### Category

detection

### Describe the issue

detection the uBO (Ссылка на скачивание недоступна. Отключите Adblоck) 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19227465/148680292-6f363eba-628d-4bb4-9a91-86c71aa7fc73.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 94
filterset (summary): 
  network: 96832
  cosmetic: 61398
  scriptlet: 18005
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40773-9, 52m
    easylist: 62775-26, 1d.17h.51m
    easyprivacy: 26605-113, 1d.13h.50m
    plowe-0: 3679-821, 8d.2h.36m
    ublock-abuse: 76-1, 1d.13h.49m
    ublock-badware: 3648-67, 1d.13h.48m
    ublock-filters: 30085-175, 1d.13h.47m
    ublock-privacy: 186-3, 1d.13h.46m
    ublock-unbreak: 1712-39, 1d.13h.45m
    urlhaus-1: 8136-0, 20h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 401 ms (selfie)
popupPanel: 
  blocked: 24
```
</details>

**Comment by dimisa-RUAdList** [comment]
This site reacts very quickly to changes in the rules, so the problem is solved in the filter [Counters](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
