### ISSUE TITLE
delfi.lt: ads

### ISSUE THREAD

**Issue by deksnys** [uBlockOrigin/uAssets#11243]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.delfi.lt/`

### Category

ads

### Describe the issue

Within the fold(top part), there is huge banner and similar banner on the right side panel. After manually  selecting and blocking these elements, they disappear, but once page is reloaded they appear again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="950" alt="2022-01-09 17_55_48-DELFI Žinios - Pagrindinis naujienų portalas Lietuvoje - Brave" src="https://user-images.githubusercontent.com/30952573/148690009-99c97121-b6cc-4713-a5f7-09d750401e86.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 77468
  cosmetic: 40401
  scriptlet: 16423
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62790-9, 1d.2h.51m
    easyprivacy: 26605-17, 1d.2h.50m
    plowe-0: 3681-816, 9d.23h.23m
    ublock-abuse: 76-0, 1d.2h.49m
    ublock-badware: 3648-67, 1d.2h.48m
    ublock-filters: 30079-143, 1d.2h.47m
    ublock-privacy: 186-3, 1d.2h.46m
    ublock-unbreak: 1678-39, 1d.2h.45m
    urlhaus-1: 6782-0, 1d.2h.44m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 206 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
Enable `LTU: EasyList Lithuania`
