### ISSUE TITLE
[nsfw] jizzoncam.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11247]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jizzoncam.com/videos/27721/salmaroze-cam-video-chat-290921/`

### Category

ads

### Describe the issue

there are ads on the right

### Screenshot(s)

<details>
https://user-images.githubusercontent.com/81616288/148711777-f06b8e66-8ff0-45e5-bbbc-e5147beb804b.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 79717
  cosmetic: 43510
  scriptlet: 16388
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-151, 2h.22m
    ublock-badware: 3662-1, 2h.21m
    ublock-privacy: 183-0, 2h.21m
    ublock-abuse: 76-0, 2h.21m
    ublock-unbreak: 1726-0, 2h.21m
    easylist: 62807-465, 2h.21m
    easyprivacy: 26611-501, 2h.21m
    urlhaus-1: 6904-0, 2h.21m
    plowe-0: 3685-2, 2h.21m
    DEU-0: 5187-2, 2h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2417 ms
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
add

`jizzoncam.com##[href^="http://trafficare.net/"]`

@ryanbr
