### ISSUE TITLE
[nsfw] pornfelix.com: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11241]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pornfelix.com/videos/cassie-courtland-and-marley-moore-bang-the-lesbian-way-756/`

### Category

ads

### Describe the issue

Open site in new Private Window/Incognito session. There are ads banners on the site due to this base64 variable:

```
var vpSpecial = 'PGlmcmFtZSBkYXRhLXNpemU9IjMwMHgyNTAiIHNyYz0iLy9hZHMuZXhvY2xpY2suY29tL2lmcmFtZS5waHA/aWR6b25lPTIyODExMDkmc2l6ZT0zMDB4MjUwIiB3aWR0aD0iMzAwIiBoZWlnaHQ9IjI1MCIgc2Nyb2xsaW5nPSJubyIgbWFyZ2lud2lkdGg9IjAiIG1hcmdpbmhlaWdodD0iMCIgZnJhbWVib3JkZXI9IjAiPjwvaWZyYW1lPg==';
```

in `view-source`, which is

```
<iframe data-size="300x250" src="//ads.exoclick.com/iframe.php?idzone=2281109&size=300x250" width="300" height="250" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
```

Same situation for the site `pornblade.com`.

Proposed filter:

`pornblade.com,pornfelix.com##+js(aopr, vpSpecial)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77636
  cosmetic: 40410
  scriptlet: 16388
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30656-29, 2h.5m
    ublock-badware: 3652-1, 2h.5m
    ublock-privacy: 183-0, 2h.5m
    ublock-abuse: 76-0, 2h.5m
    ublock-unbreak: 1725-0, 2h.5m
    easylist: 62804-581, 2h.5m
    easyprivacy: 26607-482, 2h.5m
    urlhaus-1: 6904-0, 2h.5m
    plowe-0: 3685-2, 2h.5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 305 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
pornblade.com is already fixed: 

`||pornblade.com^$xmlhttprequest,1p`
