### ISSUE TITLE
the-scorpions.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11249]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.the-scorpions.com/`

### Category

detection

### Describe the issue

Page loads quite slow to me until anti-adblock appears.

1. Open in new Private Window/Incognito session
2. Wait until a cookie banner appears -> Click on `Disable cookie`
3. Wait until this banner appears

<details>
<summary>Banner</summary>

![image](https://user-images.githubusercontent.com/66517106/148713697-eb0ab9ea-b5b3-42c6-ae32-7bcf0dce8313.png)

</details>

4. Shortly after that, an anti-adblock overlay appears

Proposed filter:

`the-scorpions.com##+js(acis, decodeURIComponent, ai_)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/148713751-8dd20ef3-dc04-4398-bba0-7f74bf57d5d4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77652
  cosmetic: 40417
  scriptlet: 16388
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-30, 1h.34m
    ublock-badware: 3662-1, 1h.33m
    ublock-privacy: 183-0, 1h.33m
    ublock-abuse: 76-0, 1h.33m
    ublock-unbreak: 1726-0, 1h.33m
    easylist: 62809-581, 1h.33m
    easyprivacy: 26611-481, 1h.33m
    urlhaus-1: 6904-0, 1h.33m
    plowe-0: 3685-2, 1h.33m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 249 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue, existent filter still works

**Comment by uBlock-user** [comment]
Susbcribe to uBlock Annoyances list.
