### ISSUE TITLE
heise.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11244]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.heise.de/`

### Describe the issue

website is hidden because of the filter `##[data-ad-unit]` in EasyList

### Screenshot(s)

<img width="236" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/148691750-5edd8ef6-d86d-49f0-ab17-e26b6f1cb080.PNG">

### uBlock Origin version

uBlock Origin 1.40.2

### Browser name and version

firefox developer

### Settings

- Enabled uBlock filters – Annoyances

### Notes

Its a high traffic site thats why i report here i not know how fast the EasyList contributer react

@ryanbr

**Comment by gorhill** [comment]
`##[data-ad-unit]` was [added 15 hours ago](https://github.com/easylist/easylist/commit/35a5b654be6e6ccb510b83edcf764164c1004851#diff-ffb6ddda6ff333afce3b529e39bc0ce6ebebf81db67ff3ed19ee0b2b0caf3f0d), so this probably means a good amount of users are having that filter and suffering the breakage by now.

**Comment by ygoe** [comment]
What does that mean, closed? This will not be changed and heise.de can never be used with uBlock again? I don't understand. When I open that page, it's all empty. Disabling uBlock resolves the issue.

**Comment by gorhill** [comment]
> I don't understand

It means a counter filter has been added to _"uBlock filters -- Unbreak"_ (until it is fixed in EasyList), force an update of that list.

**Comment by JobcenterTycoon** [comment]
@ygoe force update the filter lists (click on the uBO logo -> filter lists -> purge all cache -> update now)

**Comment by ygoe** [comment]
Thank you, works now. Wow, that unbreak filter list is long!
