### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by elanski** [uBlockOrigin/uAssets#11240]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vk.com/feed`

### Category

breakage

### Describe the issue

не грузится вк

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 136940
  cosmetic: 202532
  scriptlet: 34213
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48823-438, 3d.7h.1m
    adguard-generic: 61588-881, 3d.3h
    adguard-mobile: 7035-65, 3d.2h.57m
    adguard-social: 15348-785, 3d.2h.55m
    adguard-spyware: 24525-693, 3d.7h.5m
    fanboy-annoyance: 62511-7009, 6d.19h.5m
    fanboy-cookiemonster: 21152-21152, 6d.19h.6m
    fanboy-social: 23142-23136, 3d.2h.54m
    fanboy-thirdparty_social: 68-21, 6d.19h.4m
    ublock-annoyances: 4355-291, 3d.7h.4m
  default: 
    RUS-0: 40768-10, 19h.32m
    easylist: 62656-1043, 3d.2h.56m
    easyprivacy: 26603-10702, 3d.2h.59m
    plowe-0: 3681-974, 10d.19h.13m
    ublock-abuse: 76-1, 3d.2h.53m
    ublock-badware: 3509-186, 3d.7h.2m
    ublock-filters: 30079-3277, 3d.2h.58m
    ublock-privacy: 182-39, 2d.6h.59m
    ublock-unbreak: 1712-109, 3d.7h.3m
    urlhaus-1: 6763-0, 23h.42m
filterset (user): [array of 150 redacted]
trustedset: 
  added: [array of 54 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 999 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
There are too many filters. Try to use only those included by default. Better yet, use [these guidelines](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=3#1).

**Comment by elanski** [comment]
отключил все фильтры вк не грузит полностью на хроме

**Comment by uBlock-user** [comment]
Reset to default settings/lists + all other extensions disabled.

**Comment by dimisa-RUAdList** [comment]
If the problem is reproducible with the filters disabled, then the problem is not with the filters.
