### ISSUE TITLE
Dailyvoice.com Antiadblock and Email popups

### ISSUE THREAD

**Issue by Snuffy2** [uBlockOrigin/uAssets#11242]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dailyvoice.com/new-jersey/northernhighlands/`

### Describe the issue

Two  different popups:
1. Anti-adblock popup
2.  Email newsletter popup

Sometimes doesn't show on the first load but refreshing once or twice or scrolling will make it show.

### Screenshot(s)

<img width="1382" alt="2022-01-09_10-49-13 823" src="https://user-images.githubusercontent.com/6526076/148689860-78371052-e7f0-46f5-823b-c1712006450c.png">
<img width="1379" alt="2022-01-09_10-50-51 928" src="https://user-images.githubusercontent.com/6526076/148689865-aa52ae76-4bd1-4036-990b-90058fb4d1f8.png">

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 95.0.2

### Settings

- Enabled advanced mode

**Comment by gorhill** [comment]
This works:

    dailyvoice.com##+js(no-fetch-if, doubleclick)

**Comment by gorhill** [comment]
For the newsletter annoyance, enable _"Fanboy Annoyance"_ list.
