### ISSUE TITLE
as.com: breakage

### ISSUE THREAD

**Issue by gimco** [uBlockOrigin/uAssets#11246]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://as.com/`

### Category

breakage

### Describe the issue

Videos don't load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 96
filterset (summary): 
  network: 82925
  cosmetic: 25966
  scriptlet: 16604
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30732-361, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-1, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1725-0, never
    adguard-mobile: 7047-321, never
    easylist: 62254-23888, never
    easyprivacy: 26549-28, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-458, never
    spa-0: 3579-341, never
    spa-1: 4173-175, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3904 ms
popupPanel: 
  blocked: 17
```
</details>

**Comment by mapx-** [comment]
tested on mobile

`https://as.com/futbol/2022/01/09/primera/1641713808_028174.html`

no issue on my end

**Comment by PIZZA90** [comment]
maybe in random videos:

`https://as.com/baloncesto/2022/01/09/acb/1641735582_276937.html?omnil=resrelrecomv`

**Comment by mapx-** [comment]
in the widget there is no (new) video even disabling uBO

**Comment by mapx-** [comment]
@gimco provide specific page link where you get the issue

**Comment by gimco** [comment]
The problem exists in Firefox Android. I checked for example the next page https://as.com/tenis/2022/01/10/open_australia/1641793393_836807.html

In firefox on desktop works fine, but the same page on Firefox Android the video don't load

**Comment by mapx-** [comment]
@gimco 
test
`@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=as.com`

**Comment by gimco** [comment]
Works! Thanks very much!
