### ISSUE TITLE
windowscentral.com: breakage

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11251]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.windowscentral.com/make-microsoft-teams-edge-and-powerpoint-pop-pantones-purple-color-year`

### Category

breakage

### Describe the issue

Links to images/themes in the box are hidden incorrectly?

Proposed filters:

```
windowscentral.com#@#.no-amazon
windowscentral.com##.article-body__suppl_content--taboola-mid-article
```

### Screenshot(s)

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148770393-af942880-a7c9-4b6e-a4b6-d762f6db9d97.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148770341-eab0a1d9-4e44-4756-a74b-cc1149f59bff.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77656
  cosmetic: 40435
  scriptlet: 16393
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30675-30, 4m
    ublock-badware: 3662-1, 4m
    ublock-privacy: 183-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1727-0, 4m
    easylist: 62817-581, 4m
    easyprivacy: 26613-481, 4m
    urlhaus-1: 6904-0, 4m
    plowe-0: 3684-2, 4m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 618 ms
popupPanel: 
  blocked: 26
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
