### ISSUE TITLE
search.naver.com: breakage

### ISSUE THREAD

**Issue by SnorlaxH** [uBlockOrigin/uAssets#11250]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://search.naver.com/`

### Category

breakage

### Describe the issue

adblock block some script so search result or page function not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/13658586/148719080-649dce85-3ce4-43be-9f83-81dd45e9611b.png

https://user-images.githubusercontent.com/13658586/148719137-2d065cf4-d2ca-4100-b109-d8eaf81ac818.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 79492
  cosmetic: 46579
  scriptlet: 16428
  html: 0
listset (total-discarded, last updated): 
  default: 
    KOR-1: 8040-0, 4h.9m
    easylist: 62809-17, 4h.8m
    easyprivacy: 26611-21, 4h.7m
    plowe-0: 3683-819, 4d.19h.41m
    ublock-abuse: 76-0, 4h.6m
    ublock-badware: 3648-67, 4h.5m
    ublock-filters: 30084-145, 4h.4m
    ublock-privacy: 186-3, 4h.3m
    ublock-unbreak: 1714-39, 4h.1m
    urlhaus-1: 6904-0, 4h
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6859 ms
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
What exactly is missing ?
Provide exact steps to reproduce the issue

**Comment by SnorlaxH** [comment]
https://ssl.pstatic.net/sstatic/sdyn.js?f=/au/pc/_nx/jindo_1.5.3_171116.js+/search/js/nhn.Component.js+/search/js/jindo.Component.1.1.0.js+/search/js/jindo.component.library_120927.js+/au/s/pc/_common/jindo/jindo.Rolling_140526.js+/fe/sfe/_common/pc/nhn.common_211014_a.js+/au/pc/_nx/2021/nx_jquery_0806.js+/fe/meerkat/logger/sfe/naver.common.meerkat.logger.sfePc.js+/au/pc/naver_autocomplete/naver.common.atcmp.naver_web_210408.js&o=search
