### ISSUE TITLE
heise.de: breakage

### ISSUE THREAD

**Issue by helmar74** [uBlockOrigin/uAssets#11254]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.heise.de/`

### Category

breakage

### Describe the issue

Site is completly empty, when ublock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 79601
  cosmetic: 43513
  scriptlet: 16428
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5192-0, 20m
    easylist: 62804-15, 1d.3h.46m
    easyprivacy: 26616-28, 2h.17m
    plowe-0: 3681-817, 10d.23h.22m
    ublock-abuse: 76-0, 2h.19m
    ublock-badware: 3658-67, 2h.18m
    ublock-filters: 30087-151, 2d.59m
    ublock-privacy: 186-3, 2d.5h.1m
    ublock-unbreak: 1678-40, 2d.5h
    urlhaus-1: 6826-0, 2h.16m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1078 ms (selfie)
popupPanel: 
  blocked: 15
  no-cosmetic-filtering: true
```
</details>

**Comment by mapx-** [comment]
It was fixed in Easylist. Just update all your lists.
