### ISSUE TITLE
Current simplywall.st filter causes page to lock up / scrolling stops

### ISSUE THREAD

**Issue by jmvm-nz** [uBlockOrigin/uAssets#11256]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://simplywall.st/stocks/us/tech/nasdaq-aapl/apple`

### Describe the issue

Using default filters from UBlock Annoyances List
Occurs on all Pages detailing a stock.
Page prevents scrolling approximately half way through the page
Multiple browsers including latest Chrome, FF and Opera

### uBlock Origin version

1.40.4

### Browser name and version

Chrome v96

### Settings

Enabled UBlock Annoyances list which contains filters for simplywall.st

### Notes

Have looked at the source code, unsure what cause is. 
When the default : simplywall.st##+js(nosiif, location.reload)  is removed the page seems to refresh/reload at this point.

**Comment by gwarser** [comment]
simplywall.st##body:style(overflow:auto!important)

**Comment by jmvm-nz** [comment]
Worked ! Thanks :)

**Comment by mapx-** [comment]
it works .. but the various paragraphs on page are broken without logging in.

**Comment by stephenhawk8054** [comment]
Can you test these?

```adb
||simplywall.st/backend/flags/proxy/client/metrics$1p
simplywall.st##+js(aeld, scroll, setTimeout)
```

**Comment by HumBerTofGonCalVes** [comment]
> Worked ! Thanks :)

@jmvm-nz, Could you please tell, step by step how you do it?

**Comment by SSlinky** [comment]
> ```
>  simplywall.st##body:style(overflow:auto!important)
> ```

For anyone looking at this today, I had to add `simplywall.st##body:style(overflow-y:auto!important)`

**Comment by stephenhawk8054** [comment]
@SSlinky Do these work?

```adb
||simplywall.st/backend/flags/proxy/client/metrics$1p
simplywall.st##+js(aeld, scroll, /setTimeout|GuestRegistrationModal|addEventProcessor/)
```

**Comment by SSlinky** [comment]
@stephenhawk8054  They do! I can now scroll freely. I've also added `simplywall.st##[data-cy-id="careers-upsell"]:style(display:none !important)` which can pop up if you're playing around. I wasn't able to get the side menu links working though. Adding `simplywall.st###root:style(filter:none !important)` filter to prevent the blur doesn't help as they don't seem to actually navigate anywhere. Assume the JS that fires when you're logged in actually scrolls you directly to that part of the page.

Thanks for your help.

**Comment by Procyon-b** [comment]
@SSlinky for the side menu, add this filter:
`simplywall.st##+js(aeld, click, , elements, #root)`
The same issue just popped up on reddit.

**Comment by robdevops** [comment]
Any working filters for 2025?

**Comment by lexmozli** [comment]
> Any working filters for 2025?

```
||simplywall.st/backend/flags/proxy/client/metrics$1p
simplywall.st##[data-cy-id="careers-upsell"]:style(display:none !important)
simplywall.st###root:style(filter:none !important)
simplywall.st##+js(set, scrollY, 1)
simplywall.st##+js(aeld, click, , elements, #root)
simplywall.st##+js(aeld, scroll)
```

I've added these which are basically a mashup of everything suggested here, more or less.
It seems to work for me.

**Comment by ghost** [comment]
There are some ad leftovers on `https://simplywall.st/stocks/us/media/nasdaq-wbd/warner-bros-discovery/news/has-warner-bros-discovery-risen-too-far-after-its-major-stre`

https://github.com/user-attachments/assets/f6aa2709-1853-4715-a33b-e7fb9e2814ae

**Comment by mapx-** [comment]
```adb
simplywall.st###sws-ad-slot
```

report at easylist

**Comment by andiwunder** [comment]
Any updates? Still having this pop up on ubolite safari iOS upon scroll. Added all the codes above and removed element but no luck. 

Link: https://simplywall.st/stocks/us/diversified-financials/nyse-klar/klarna-group/valuation

<details>

<img width="1170" height="2362" alt="Image" src="https://github.com/user-attachments/assets/0dbe102a-2afc-4d65-be4a-0e61d4ef4613" />

</details>
