### ISSUE TITLE
quora.com: ads

### ISSUE THREAD

**Issue by Friendlyx3** [uBlockOrigin/uAssets#11253]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.quora.com/`

### Category

ads

### Describe the issue

I receive sponsored ads when browsing the website via Firefox on an android phone. 
![Screenshot_20220110-114854_Firefox](https://user-images.githubusercontent.com/97465124/148805145-8d955623-868b-46b3-b0a2-99a6f2a3b556.jpg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 79132
  cosmetic: 22147
  scriptlet: 16422
  html: 619
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30795-269, 1m
    ublock-badware: 3703-1, 1m
    ublock-privacy: 183-1, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1733-0, 1m
    adguard-mobile: 7060-173, now
    easylist: 62832-24226, now
    easyprivacy: 26616-489, now
    urlhaus-1: 6904-0, now
    plowe-0: 3684-2, now
filterset (user): [array of 42 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2425 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
I've tried (lots of scrolling) no ad / sponsored on my end

**Comment by gorhill** [comment]
@Friendlyx3 You have 42 custom filters, did you verify that it does occur without your filters?

**Comment by Friendlyx3** [comment]
> @Friendlyx3 You have 42 custom filters, did you verify that it does occur without your filters?

I tried that and currently I've just reset all settings just to make sure something didn't get corrupted. Facebook for instance before and after settings reset is still adless but quora still has the sponsored and sponsored by ads :/

**Comment by Friendlyx3** [comment]
> I've tried (lots of scrolling) no ad / sponsored on my end

Maybe it's where I'm logged in on quora?

**Comment by mapx-** [comment]
Could be. US ?

**Comment by Friendlyx3** [comment]
> I've tried (lots of scrolling) no ad / sponsored on my end

Maybe it's where I'm logged in on quora? 

> Could be. US ?

Yeah. Logging out doesn't allow me to even use quora

**Comment by PIZZA90** [comment]
```
quora.com##span:has-text(Ad)
quora.com##span:has-text(Sponsored)
quora.com##span:has-text(Promoted)
```

**Comment by uBlock-user** [comment]
try `quora.com##[data-nosnippet="true"]` @Friendlyx3

**Comment by Friendlyx3** [comment]
> 

That did it!

**Comment by PIZZA90** [comment]
about quora emails, it is not possible remove the ads inside the emails? or is it another story 

example of a email:
![Captura11](https://user-images.githubusercontent.com/33556647/151047344-d3a7d2ee-411e-4c78-ab32-acaba0b314b9.PNG)
