### ISSUE TITLE
[nsfw] javmost.xyz: ads

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#11257]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.javmost.xyz/RBD-568/`

### Category

ads

### Describe the issue

ad placeholder above player

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 96
filterset (summary): 
  network: 169053
  cosmetic: 186552
  scriptlet: 34338
  html: 645
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1373-0, 1d.5h.30m
    https://www.i-dont-care-about-cookies.eu/abp/: 24140-8379, 1d.13h.55m
    adguard-generic: 61647-4829, 3h.46m
    adguard-spyware: 24537-1241, 1d.12h.2m
    adguard-spyware-url: 433-12, 1d.14h.19m
    block-lan: 44-0, 9h.53m
    adguard-annoyance: 48866-4469, 1d.14h.20m
    adguard-social: 15365-21, 1d.11h.55m
    fanboy-thirdparty_social: 68-0, 7d.7h.47m
    fanboy-cookiemonster: 21262-124, 7d.7h.48m
    ublock-annoyances: 4386-4, 1d.14h.21m
    dpollock-0: 16948-1754, 8d.6h.8m
    mvps-0: 8730-363, 8d.6h.9m
    RUS-0: 40789-277, 1d.5h.31m
    curben-phishing: 11815-3, 12h.42m
    curben-pup: 376-0, 12h.41m
  default: 
    ublock-filters: 30754-70, 1d.12h.1m
    ublock-badware: 3513-1, 1d.11h.56m
    ublock-privacy: 183-1, 2d.2h.49m
    ublock-abuse: 76-0, 1d.12h
    ublock-unbreak: 1695-6, 1d.11h.58m
    adguard-mobile: 7047-198, 1d.17h.34m
    easylist: 62804-999, 1d.11h.57m
    easyprivacy: 26616-11135, 3h.45m
    urlhaus-1: 7003-0, 12h.40m
    plowe-0: 3685-8, 12h.43m
filterset (user): [array of 517 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  blockingProfiles: 11111/#F00 11011/#C0F 11001/#00F 00001
  cloudStorageCompression: false
  filterAuthorMode: true
supportStats: 
  launchToReadiness: 754 ms (selfie)
popupPanel: 
  blocked: 14
```
</details>

**Comment by mapx-** [comment]
@ryanbr
