### ISSUE TITLE
Site doesn't show anything at all

### ISSUE THREAD

**Issue by sneakyx** [uBlockOrigin/uAssets#11252]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.heise.de/

### Describe the issue

The site doesn't show anything at all. The page stays blank.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 79583
  cosmetic: 43508
  scriptlet: 16387
  html: 616
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.23h.55m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30663-38, 4h.34m
    ublock-badware: 3543-1, 3d.18h.19m
    ublock-privacy: 177-0, 1d.5h.12m
    ublock-unbreak: 1723-0, 1d.5h.10m
    easylist: 62801-585, 1d.5h.9m
    easyprivacy: 26607-497, 1d.5h.8m
    plowe-0: 3685-2, 2d.20h.57m
    DEU-0: 5187-2, 19h.19m
    ublock-abuse: 76-0, 1d.5h.7m
    urlhaus-1: 6904-0, 19h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 251 ms (selfie)
```
</details>

**Comment by uBlock-user** [comment]
force update EasyList.

**Comment by sneakyx** [comment]
Works, thank You. Didn't know that the filters aren't self-updating.  Whoever finds finds this by a google search:  The correct way to update is described in the other ticket: https://github.com/uBlockOrigin/uAssets/issues/11244#issuecomment-1008352077

**Comment by okiehsch** [comment]
> Didn't know that the filters aren't self-updating. 

The filter lists are all auto updating, the intervall depends on the list.
In this case the list is auto updating every 4 days.
![image](https://user-images.githubusercontent.com/16838044/149098606-c4be26a7-fae2-4fbe-94dd-d9f14a87a111.png)

**Comment by sneakyx** [comment]
This is what I meant.
But if someone finds this page by googleling the problem, I just wanted to refer directly to the solution.
