### ISSUE TITLE
jzrputtbut.net [ADS] [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1125]
URL(s) where the issue occurs

http://www.jzrputtbut.net/6ptm

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
a traffic appears that every time you enter shows you annoying pages you could leave it blank @mapx-

**Comment by xDarkARG** [comment]
a traffic appears that every time you enter shows you annoying pages you could leave it blank @mapx-

**Comment by xDarkARG** [comment]
a traffic appears that every time you enter shows you annoying pages you could leave it blank @mapx- @okiehsch

![](https://i.imgur.com/cZp1aRo.png)

**Comment by xDarkARG** [comment]
ADS @mapx-

**Comment by KiLL4FuNK** [comment]
ADS @mapx-

**Comment by KiLL4FuNK** [comment]
@mapx- linkbucks new domain ?

`http://www.zbqhfbetlmni.net/4e454e1d`

**Comment by KiLL4FuNK** [comment]
@mapx-
![](https://i.imgur.com/N4noDrf.png)

**Comment by KiLL4FuNK** [comment]
@mapx-
http://www.mmwgopsoyfhzk.net/BHVRn
