### ISSUE TITLE
webcam-hd.com: breakage

### ISSUE THREAD

**Issue by PILLOWPET** [uBlockOrigin/uAssets#11262]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.webcam-hd.com/lesarcs/grizzly`

### Category

breakage

### Describe the issue

The webcams are not loading due to an error in the AngularJS execution. 

The issue disappears when disabling ubo.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/1775302/148913948-991764f9-920a-4e47-b639-df6127450556.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77631
  cosmetic: 40397
  scriptlet: 16389
  html: 616
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 20h.42m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30657-30, 2d.12h.19m
    ublock-badware: 3652-1, 2d.12h.18m
    ublock-privacy: 183-0, 2d.12h.20m
    ublock-abuse: 76-0, 2d.12h.17m
    ublock-unbreak: 1723-0, 2d.12h.14m
    easylist: 62790-581, 2d.12h.16m
    easyprivacy: 26605-481, 2d.12h.15m
    plowe-0: 3684-2, 20h.19m
    urlhaus-1: 6904-0, 20h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1030 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
