### ISSUE TITLE
shortelink.co [ADS] [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1126]
URL(s) where the issue occurs

http://shortelink.co/Yt5c

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@mapx- Pop-up

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
