### ISSUE TITLE
scoresaber.com: ads

### ISSUE THREAD

**Issue by ASPJulien** [uBlockOrigin/uAssets#11265]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://scoresaber.com/leaderboard/95222`

### Category

ads

### Describe the issue

On every https://scoresaber.com/leaderboard/ page, there is an Amazon Music ad for the music even tho it doesn't exist on AMusic.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/49618271/148962793-991b4473-d906-4461-84f8-41fea9289195.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 93864
  cosmetic: 49285
  scriptlet: 16304
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26087-23, 3d.22h.21m
    easylist: 62694-178, 3d.22h.20m
    easyprivacy: 26606-343, 3d.22h.19m
    plowe-0: 3682-825, 9d.2h.56m
    ublock-abuse: 72-1, 3d.22h.18m
    ublock-badware: 3648-75, 3d.22h.17m
    ublock-filters: 29794-306, 3d.22h.16m
    ublock-privacy: 186-3, 3d.22h.15m
    ublock-unbreak: 1712-39, 3d.18h.14m
    urlhaus-1: 6950-0, 21h.48m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 220 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by gorhill** [comment]
This works:

    /showads/adunit.

cc @ryanbr, @Khrin
