### ISSUE TITLE
evernote.com: breakage

### ISSUE THREAD

**Issue by peterv1988** [uBlockOrigin/uAssets#11267]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.evernote.com/Home.action?login=true`

### Category

breakage

### Describe the issue

When logging in with Firefox 95.0.2 and just uBlock enabled, logging into `www.evernote.com` web-interface shows a message that 'something in your browser is blocking functioning of evernote, to use evernote you can use old version: `https://www.evernote.com/Home.action?switchingBack=true&IonVersion=10.28.3`'

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77967
  cosmetic: 41356
  scriptlet: 16389
  html: 616
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.2h.44m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    NLD-0: 1230-0, 4h.14m
  default: 
    ublock-filters: 30663-29, 1d.7h.38m
    ublock-badware: 3662-1, 1d.7h.37m
    ublock-privacy: 183-0, 1d.7h.43m
    ublock-abuse: 76-0, 1d.7h.42m
    ublock-unbreak: 1726-0, 1d.7h.41m
    easylist: 62812-581, 1d.7h.40m
    easyprivacy: 26613-482, 1d.7h.39m
    plowe-0: 3679-2, 10d.3h.31m
    urlhaus-1: 6916-0, 4h.15m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 38 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2645 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by LanikSJ** [comment]
I have an account and I wasn't able to reproduce this in Firefox 96 with uBO 1.40.2.

**Comment by gorhill** [comment]
@peterv1988 You have custom filters, did you really verify that your own filters are not causing the issue?
