### ISSUE TITLE
heise.de: breakage

### ISSUE THREAD

**Issue by DEtrees95** [uBlockOrigin/uAssets#11260]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.heise.de/`

### Category

breakage

### Describe the issue

not working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 79746
  cosmetic: 43509
  scriptlet: 16427
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5192-0, 8h.28m
    easylist: 62804-15, 1d.9h.14m
    easyprivacy: 26607-28, 1d.9h.12m
    plowe-0: 3679-817, 12d.16h.22m
    ublock-abuse: 76-0, 1d.9h.10m
    ublock-badware: 3648-67, 1d.9h.8m
    ublock-filters: 30158-151, 1d.9h.6m
    ublock-privacy: 195-3, 1d.9h.4m
    ublock-unbreak: 1742-40, 1d.9h.2m
    urlhaus-1: 6847-0, 8h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 191
  launchFromSelfie: true
popupPanel: 
  blocked: 25
```
</details>

**Comment by mapx-** [comment]
Update your lists. The issue was fixed.
