### ISSUE TITLE
https://www.rulesofcheaters.net/

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#11261]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.rulesofcheaters.net/`

### Describe the issue

anti adblock appear

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29838157/148908556-1817a321-edfd-4e98-a6e4-58cc7283ef06.png)

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by uBlock-user** [comment]
Already fixed with generic fixes, test on default settings/lists + all other extensions disabled.

**Comment by Dhanamerdeka** [comment]
> Already fixed with generic fixes, test on default settings/lists + all other extensions disabled.

ah ok i will check it again on second laptop... i hope it will works....
thanks
