### ISSUE TITLE
[nsfw] xcamgirlblog.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11266]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xcamgirlblog.com/`

### Category

ads

### Describe the issue

ads on the top

### Screenshot(s)

<details>
https://user-images.githubusercontent.com/81616288/148977394-daa530d5-932a-4b95-abe2-2603e63014e4.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 96
filterset (summary): 
  network: 79795
  cosmetic: 43562
  scriptlet: 16397
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30705-37, 4m
    ublock-badware: 3703-1, 3m
    ublock-privacy: 183-0, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1727-0, 3m
    easylist: 62859-588, 3m
    easyprivacy: 26616-493, 3m
    urlhaus-1: 6896-0, 3m
    plowe-0: 3684-2, 3m
    DEU-0: 5192-2, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 718 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
@ryanbr
