### ISSUE TITLE
Ad Icon from font awesome blocked

### ISSUE THREAD

**Issue by anthony0030** [uBlockOrigin/uAssets#11264]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The ad Icon from Font Awesome is blocked

### A specific URL where the issue occurs

https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=ad&s=solid&m=free

### Steps to Reproduce

1. Open any site with Font Awesome that uses the ad icon

### Expected behavior

Ad icon is displayed

### Actual behavior

Ad icon is hidden

### uBlock Origin version

1.40.4

### Browser name and version

Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### Operating System and version

macOS Monterey Version 12.1

**Comment by gorhill** [comment]
> - [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))

@anthony0030 Please next time ready _carefully_ what is asked in the prerequisite steps.

**Comment by anthony0030** [comment]
Thanks for the super quick response. I misunderstood the question.

I found the solution for my case.


Just add ```#@#.fa-ad``` to the ```My Filters``` setting
