### ISSUE TITLE
Add discqrdapp.com to Filter

### ISSUE THREAD

**Issue by PhilippBleimund** [uBlockOrigin/uAssets#11269]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://discqrdapp.com/newyears
https://discqrdapp.com
```

### Describe the issue

This is a obvious fake side to steal Steam and Discord Passwords.
`https://www.scam-detector.com/validator/discqrdapp-com-review/`

### uBlock Origin version

1.40.4

### Browser name and version

Chrome 96.0.4664.110

### Settings

All default

**Comment by iam-py-test** [comment]
I can confirm that this is indeed a phishing website
More verification: `https://scammer.info/t/discord-nitro-scam-23/87273`

**Comment by Yuki2718** [comment]
Hmm, I can't access the site (without the filter).
