### ISSUE TITLE
https://www.baku365.com detecting ublock

### ISSUE THREAD

**Issue by zavrb** [uBlockOrigin/uAssets#11263]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.baku365.com`

### Describe the issue

uBlock is being detected on the `https://www.baku365.com`. Only resolution is to block java script

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 95646
  cosmetic: 36890
  scriptlet: 17966
  html: 620
listset (total-discarded, last updated): 
  added: 
    RUS-0: 40801-984, 1d.1h.59m
  default: 
    ublock-filters: 30659-256, 1d.2h.2m
    ublock-badware: 3652-1, 1d.2h.1m
    ublock-privacy: 183-1, 1d.2h.8m
    ublock-abuse: 76-0, 1d.2h.7m
    ublock-unbreak: 1726-0, 1d.2h.5m
    easylist: 62814-24099, 1d.2h.4m
    easyprivacy: 26612-481, 1d.2h.3m
    urlhaus-1: 6916-0, 31m
    plowe-0: 3684-2, 8h.7m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1135 ms (selfie)
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce. You have custom filters, did you test without them?

**Comment by zavrb** [comment]
please find my config
![list1](https://user-images.githubusercontent.com/97509509/148935907-eaa1faf6-ee8f-4ce8-8bfd-153f609dde58.jpg)

![list2](https://user-images.githubusercontent.com/97509509/148935944-bc8ca2a0-5992-4946-8c14-86360ced2e07.jpg)

message itself
![adblock](https://user-images.githubusercontent.com/97509509/148936031-bd9372e7-9fe0-4970-b747-bc6afc6689f2.jpg)

**Comment by iam-py-test** [comment]
@zavrb go into the Third Party filters tab, uncheck _My filters_

**Comment by gorhill** [comment]
Your config is present in the opening comment, and it does not match the screenshot you posted. It appears you disabled some of your `baku365.com` custom filters, and removed two more filters before taking the screenshot.

**Comment by gorhill** [comment]
> - [X] uBO with default lists/settings

@zavrb Please next time answer truthfully the steps asked from you out of respect for volunteers who donate their time here.

**Comment by zavrb** [comment]
yes. you are right after removal of custom filters - no message occurred so far 
thank you

**Comment by iam-py-test** [comment]
> yes. you are right after removal of custom filters - no message occurred so far thank you

You should test on default settings BEFORE opening an issue

**Comment by dmitryportvine** [comment]
<details>
<summary>Screen</summary>

![2022-01-11_141225](https://user-images.githubusercontent.com/97522612/148941245-29c9a061-f52d-472e-8f82-9ff0c404c5e8.png)
</details>

`https://content.invisioncic.com/f282848/javascript_adblockdetector/front_front_abagent.js.gz`

`||invisioncic.com/*adblockdetector/$script`

**Comment by iam-py-test** [comment]
@dmitryportvine are you saying you can reproduce?
That script probably is a antiadblock trap

**Comment by zavrb** [comment]
> ||invisioncic.com/*adblockdetector/$script

thank you. Checked together with my custom filters on android firefox browser. So far no warning message

**Comment by dmitryportvine** [comment]
> are you saying you can reproduce?

Yes.
<details>
<summary>Screen</summary>

![1](https://user-images.githubusercontent.com/97522612/148942808-15065070-286f-4819-9bee-033586161dc2.gif)
</details>

**Comment by iam-py-test** [comment]
I still can't.
There are ads though
![image](https://user-images.githubusercontent.com/84232764/148943077-e312c388-5442-4953-a1bb-ed40739edf0a.png)

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/a95c033b89e52e2bbf673f4dccae17a05c266575

@zavrb 
Deactivate the item "Ignore Generic Cosmetic Filters".
Activate the item "RUS: RU AdList"
Update filters (after 15 minutes).

**Comment by zavrb** [comment]
> Fix: [easylist/ruadlist@a95c033](https://github.com/easylist/ruadlist/commit/a95c033b89e52e2bbf673f4dccae17a05c266575)
> 
> @zavrb Deactivate the item "Ignore Generic Cosmetic Filters". Activate the item "RUS: RU AdList" Update filters (after 15 minutes).

already activate. thank you

**Comment by iam-py-test** [comment]
@zavrb after forcing a filter update, is the issue resolved?

**Comment by zavrb** [comment]
so far no issues
