### ISSUE TITLE
canberratimes.com.au: nuisance

### ISSUE THREAD

**Issue by usernameabcdef** [uBlockOrigin/uAssets#11273]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.canberratimes.com.au/`

### Category

nuisance

### Describe the issue

a modal window for adblocker whitelist request

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-01-12 102606](https://user-images.githubusercontent.com/97565322/149037422-94353fb7-9d1b-4141-8831-7ae0c201eeb9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 77744
  cosmetic: 40466
  scriptlet: 16437
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62885-9, 1h.10m
    easyprivacy: 26616-17, 1h.10m
    plowe-0: 3684-817, 1h.10m
    ublock-abuse: 76-0, 1h.10m
    ublock-badware: 3699-67, 1h.10m
    ublock-filters: 30131-144, 1h.10m
    ublock-privacy: 186-3, 1h.10m
    ublock-unbreak: 1716-39, 1h.10m
    urlhaus-1: 6896-0, 1h.10m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 464 ms
popupPanel: 
  blocked: 16
```
</details>

**Comment by peace2000** [comment]
I can repro with defaults @uBlock-user 

uBO 1.40.8, Firefox 95.0.2

Disabling cosmetics doesn't help.

**Comment by peace2000** [comment]
What other browser addons you have?

**Comment by gorhill** [comment]
> - [X] I did not answer truthfully to **all** the above checkpoints

Please go through the steps again and check them truthfully, they are there to ensure that the issue is not something else specific on your side.

**Comment by gorhill** [comment]
I can reproduce that sort of anti-blocker message if when I block `piano.io`, but there is no filter in default filter lists which blocks this domain -- so possibly something else on your side is blocking this.

**Comment by usernameabcdef** [comment]
> What other browser addons you have?
> 
> I was able to reproduce but the issue went away when I disabled Bypass paywalls addon. It seems that you have the same addon in your screenshot.

yes it went away when i disabled Bypass paywalls addon, but the same combination works fine in firefox - is this a chrome specific issue? Thank you.

**Comment by uBlock-user** [comment]
If piano.io is blocked by any addon, this will happen.
