### ISSUE TITLE
gplinks.co

### ISSUE THREAD

**Issue by gosndka** [uBlockOrigin/uAssets#11278]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://gplinks.co/dPEhX4Sk`

### Describe the issue

After opening, the site redirects to mynewsmedia.co link.
Click on OPEN - Continue, it redirects to another mynewsmedia.co link.
Click on OPEN - Continue again, nothing happens. The site cannot continue
The OPEN button becomes unresponsive.

### uBlock Origin version

1.40.2

### Browser name and version

Firefox 96.0

### Settings

No changes its default

**Comment by WaterIsH2O** [comment]
`https://mynewsmedia.co/tech/the-best-vpn-service-2021/` => Brave check after following the steps


@ryanbr

**Comment by WaterIsH2O** [comment]
`https://mynewsmedia.co/tech/Linkpage/ads_stats_controller.php` 

@ryanbr

**Comment by WaterIsH2O** [comment]
seems to check for click before showing the clickable thing to continue at one point

**Comment by okiehsch** [comment]
Hm, not sure how to fix it. Our filter causes the issue, so I will remove it.

**Comment by WaterIsH2O** [comment]
@okiehsch I think ABP has an action simulation snippet.

**Comment by WaterIsH2O** [comment]
@gorhill does uBO have something that could be implemented like https://github.com/abp-filters/abp-filters-anti-cv/commit/246d6ae5358b5da6ec14c06c6169582e77ac20f6 seems to have been?

**Comment by gorhill** [comment]
> ` https://mynewsmedia.co/tech/Linkpage/ads_stats_controller.php`

Why is that site reported in this thread? That site is a content farm with a grand total of 15 articles copy-pasted from legitimate site, we really shouldn't bother to deal with such obscure scammy sites.

**Comment by okiehsch** [comment]
The domain - mynewsmedia - is used by `gplinks` for their link shortener.

**Comment by WaterIsH2O** [comment]
> Why is that site reported in this thread? That site is a content farm with a grand total of 15 articles copy-pasted from legitimate sites, we really shouldn't bother to deal with such obscure scammy sites, and even less so having these reported in an unrelated thread.

@gorhill I thought it may have been tracking. To understand context, you may need to follow OP's steps.

**Comment by WaterIsH2O** [comment]
could using nostif scriptlet work if a certain parameter was used?

**Comment by gorhill** [comment]
My bad I missed the reference in STR.

After I click the first "OPEN - continue", nothing happens on my side.

**Comment by WaterIsH2O** [comment]
> After I click the first "OPEN - continue", nothing happens on my side.

I thought that was the problem.

**Comment by okiehsch** [comment]
Have you updated uBO-filters? I removed a filter that caused the issue half an hour ago.

**Comment by WaterIsH2O** [comment]
@okiehsch possibly unhidden popup due to removed filter

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/149218647-ff44198f-7d75-45d1-9a0d-477a5450e065.png)


If you click the modal that was hidden by our filter you will get a popup.
The issue is that the download does not start unless you click it.

**Comment by WaterIsH2O** [comment]
@okiehsch it has href to some adserver-looking domain though

**Comment by okiehsch** [comment]
I can add `mynewsmedia.co##+js(disable-newtab-links)` to disable the popup.

**Comment by WaterIsH2O** [comment]
(off-topic, did you recieve a notification from me - I tried mentioning you in https://github.com/AdguardTeam/AdguardFilters/issues/106511)

**Comment by okiehsch** [comment]
Yes.

**Comment by ghajini** [comment]
ping @lain566 since he has fixed such case back then
https://github.com/uBlockOrigin/uAssets/issues/4520#issuecomment-764845003

**Comment by mild787** [comment]
`https://gplinks.co/SvRD/?vid=175770713`
this site need update filter, now condition 
![image](https://github.com/uBlockOrigin/uAssets/assets/121563747/e5faa9b2-ef45-4355-ac5b-bc794ce10a90)
any idea for reproduce this?

**Comment by mild787** [comment]
@JobcenterTycoon can u help me for this issue. thanks
