### ISSUE TITLE
lesoir.be: detection

### ISSUE THREAD

**Issue by Favorlive** [uBlockOrigin/uAssets#11271]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lesoir.be/`

### Category

detection

### Describe the issue

connexion non-possible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 93745
  cosmetic: 49544
  scriptlet: 16435
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30653-29, 3d.20h.1m
    ublock-badware: 3652-1, 3d.20h
    ublock-privacy: 183-0, 3d.19h.58m
    ublock-abuse: 76-0, 3d.19h.57m
    ublock-unbreak: 1723-0, 3d.19h.56m
    easylist: 62779-200, 3d.19h.47m
    easyprivacy: 26603-816, 3d.20h.2m
    urlhaus-1: 6896-0, 10h.42m
    plowe-0: 3682-374, 8d.6h.13m
    FRA-0: 26087-384, 3d.20h.3m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 561 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by iam-py-test** [comment]
Can not reproduce. You have custom filter(s). Try disabling them and any other adblockers/adblocking DNS

**Comment by mapx-** [comment]
There is some (cname) breakage => home page => see left column **Le fil info** 

`@@||dscksd.akamaiedge.net^$script,domain=lesoir.be`

**Comment by Yuki2718** [comment]
Well, detection was not reproduced. Fixed breakage.
