### ISSUE TITLE
imgur.com: ads

### ISSUE THREAD

**Issue by yonyon23** [uBlockOrigin/uAssets#11277]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/gallery/BdJFX6p`

### Category

ads

### Describe the issue

A new type of posts called "promoted" that are just ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/Mhi27rL.mp4
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 77783
  cosmetic: 40430
  scriptlet: 16428
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62858-9, 20h.31m
    easyprivacy: 26616-17, 20h.32m
    plowe-0: 3682-817, 9d.13h.10m
    ublock-abuse: 76-0, 20h.30m
    ublock-badware: 3658-67, 20h.29m
    ublock-filters: 30088-144, 20h.27m
    ublock-privacy: 186-3, 20h.33m
    ublock-unbreak: 1715-39, 20h.28m
    urlhaus-1: 7003-0, 1d.52m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 390 ms (selfie)
popupPanel: 
  blocked: 27
```
</details>

**Comment by uBlock-user** [comment]
> https://imgur.com/gallery/BdJFX6p

How did you navigate to that page ?

**Comment by MasterKia** [comment]
> [x] I did not answer truthfully to **all** the above checkpoints

**Comment by MasterKia** [comment]
> * [x]  I did not answer truthfully to **all** the above checkpoints

**Comment by yonyon23** [comment]
It came up when browsing with the "next" button from a different post

**Comment by WaterIsH2O** [comment]
maybe a scriptlet should be used... maybe setting `show_ads` to false would work

**Comment by uBlock-user** [comment]
> It came up when browsing with the "next" button from a different post

So randomised ?

**Comment by WaterIsH2O** [comment]
@uBlock-user try with IPs from high advertising costs countries if you haven't.

**Comment by uBlock-user** [comment]
@WaterIsH2O Provide STR if you can.

**Comment by WaterIsH2O** [comment]
> @WaterIsH2O Provide STR if you can.

well I thought for a second I reproduced once just by clicking on `Next` or the right arrow idk
