### ISSUE TITLE
EasyPrivacy now block ALL CALLS to sendBeacon

### ISSUE THREAD

**Issue by alex-jitbit** [uBlockOrigin/uAssets#11272]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

ANY

### Describe the issue

EasyPrivacy now blocks ALL pings via this rule: `*$ping,domain=~hey.com` even on websites that are not `hey.com`

REPRODUCABLE ON ANY WEBSITE, EVEN `localhost`

JS code that runs on `beforeunload` and executes `navigator.sendBeacon` is now blocked by uOrigin!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/33555768/149031550-09315c3b-ac1a-474e-bbbe-40bcf4b97525.png)

### uBlock Origin version

1.39.2

### Browser name and version

MS Edge 97.0.1072.55

### Settings

none

**Comment by gorhill** [comment]
You need to report to EasyPrivacy: <https://github.com/easylist/easylist/issues>. In any case, you need to make the case this causes an issue -- and when you make the case, please provide a URL as asked, transcribing from the screenshot is really tedious -- along with a description of the breakage.

**Comment by iam-py-test** [comment]
> EasyPrivacy now blocks ALL pings via this rule: *$ping,domain=~hey.com even on websites that are not hey.com

That means that pings will be blocked on all websites **except** hey[.]com. Please read the docs

**Comment by ryanbr** [comment]
We limited it too $third-party @alex-jitbit

**Comment by ryanbr** [comment]
Just update the lists

**Comment by alex-jitbit** [comment]
So, are you saying that uBlock Origin now blocks all pings altogether by default? Except for hey.com?

How nice.

PS. I haven't provided the URL because it's a private one. But our app does have 100s of thousands of users, and this bug affects them all.

**Comment by alex-jitbit** [comment]
@ryanbr I can confirm that updating the lists helped. Thanks.

**Comment by iam-py-test** [comment]
@alex-jitbit what breakage was there?

**Comment by alex-jitbit** [comment]
@iam-py-test `sendBeacon` during window `beforeunload` was blocked on ANY website.

Meaning half of the internet just broke ;)

This, for example, is used by many websocket libraries (socket-io, SignalR) to send a "disconnect" event
