### ISSUE TITLE
plagiarismdetector.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11288]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://plagiarismdetector.net/de`
edit: `https://searchenginereports.net/plagiarism-checker` has it too

### Describe the issue

ad reinstertion

### Screenshot(s)

<img width="604" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/149222023-e5d1eda8-ec36-4f55-a622-a787f9367220.PNG">

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

### Notes

Filter suggestion:
`plagiarismdetector.net##+js(set, canRunAds, false)`
`*$image,redirect-rule=2x2.png,domain=searchenginereports.net`

**Comment by WaterIsH2O** [comment]
@AdamWr

**Comment by JobcenterTycoon** [comment]
Ads on `searchenginereports.net` are back

**Comment by mapx-** [comment]
Do you still see ads without that filter ?

**Comment by JobcenterTycoon** [comment]
Only one on the right side

**Comment by mapx-** [comment]
does this work ?

`searchenginereports.net##+js(ra, class, [data-name*="|"], stay)`

**Comment by JobcenterTycoon** [comment]
yes
