### ISSUE TITLE
seootools.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11287]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.seootools.com`

### Describe the issue

Adblock detected

### Screenshot(s)

<img width="468" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/149220690-59e0aa46-191e-4804-9a34-764ece53df12.PNG">

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

**Comment by WaterIsH2O** [comment]
`seootools.com#@#.banner_ad`
