### ISSUE TITLE
clash.ninja: breakage

### ISSUE THREAD

**Issue by CallMeChin** [uBlockOrigin/uAssets#11284]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.clash.ninja/my-account/notification-settings`

### Category

breakage

### Describe the issue

notification doesn't seem to work with ublock origin on
i tried to use the advanced user thingy to overwrite some of the rules, doesn't seem to overwrite anything? I am not sure how to use it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/77185235/149182222-30255f3c-592d-4608-9268-49aa7c9a7c5b.png)
![image](https://user-images.githubusercontent.com/77185235/149182551-aca0fd37-5bba-4a0a-88d7-67ffb49e660f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 78999
  cosmetic: 40422
  scriptlet: 16427
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62813-9, 2d.13h.29m
    easyprivacy: 26619-17, 11h.49m
    plowe-0: 3685-817, 3d.15h.29m
    ublock-abuse: 76-0, 11h.47m
    ublock-badware: 3699-67, 7h.42m
    ublock-filters: 30159-143, 2d.13h.31m
    ublock-privacy: 195-3, 7h.45m
    ublock-unbreak: 1744-39, 1d.10h.2m
    urlhaus-1: 8097-0, 3h.40m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 34 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1211
  launchFromSelfie: true
popupPanel: 
  blocked: 4
  no-cosmetic-filtering: true
```
</details>

**Comment by gorhill** [comment]
> - [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

> i tried to use the advanced user thingy to overwrite some of the rules, doesn't seem to overwrite anything? I am not sure how to use it

Did you really try without your custom filters and rules?

**Comment by mapx-** [comment]
open uBO logger, reproduce again the issue, select in the logger only the blocked items and post here the screenshot(s) with those elements

**Comment by WaterIsH2O** [comment]
an account is required for this to be reproduced btw

**Comment by CallMeChin** [comment]
> > * [x]  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
> 
> > i tried to use the advanced user thingy to overwrite some of the rules, doesn't seem to overwrite anything? I am not sure how to use it
> 
> > ```
> > filterset (user): [array of 2 redacted]
> > hostRuleset: 
> >   added: [array of 34 redacted]
> > ```
> 
> Did you really try without your custom filters and rules?

i didn't have custom rule at first then i got this problem, tried messing with the rules, didn't really work for me. probably just me not knowing how to use the advanced user function though.

![image](https://user-images.githubusercontent.com/77185235/149262144-42488200-98a0-4560-99d1-83b3c9d94582.png)

**Comment by mapx-** [comment]
add

```
@@||cdn.onesignal.com/sdks/$script,domain=clash.ninja
@@||onesignal.com/api/$script,domain=clash.ninja
```

@ryanbr  EP issue

**Comment by CallMeChin** [comment]
how is the noop supposed to work :joy:

**Comment by uBlock-user** [comment]
> how is the noop supposed to work

`noop` only disables dynamic filtering, static filters still apply. Wiki explains it all.
