### ISSUE TITLE
seriouseats.com: breakage

### ISSUE THREAD

**Issue by MDawg957** [uBlockOrigin/uAssets#11285]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.seriouseats.com/gemelli-with-asparagus-ricotta-arugula-and-lemon-zest-recipe`

### Category

breakage

### Describe the issue

The recipe disappears when you scroll the page.  Turning off uBlock allows it to work again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 96
filterset (summary): 
  network: 79311
  cosmetic: 41806
  scriptlet: 19178
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4373-4, now
  default: 
    ublock-filters: 30715-30, now
    ublock-badware: 3708-1, now
    ublock-privacy: 183-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1728-0, now
    easylist: 62920-586, now
    easyprivacy: 26620-482, now
    plowe-0: 3684-2, now
    urlhaus-1: 8163-0, now
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1178 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by gorhill** [comment]
> - [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

I can't reproduce, and your blocked count is lower than what I get on my side. I see you have two custom filters, did you really try without these filters?

**Comment by mapx-** [comment]
Also, disable all other extensions and do test using only uBO

**Comment by MDawg957** [comment]
> > * [x]  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
> 
> I can't reproduce, and your blocked count is lower than what I get on my side. I see you have two custom filters, did you really try without these filters?

Turns out I missed EasyList, which looks like it's causing the problems with this.  My apologies.

**Comment by gorhill** [comment]
What do you mean by "missed EasyList"?

**Comment by MDawg957** [comment]
> What do you mean by "missed EasyList"?

I forgot I had it enabled still in uBlock Origin and didn't turn it off first to check.

**Comment by gorhill** [comment]
I could not reproduce with default lists, which includes EasyList, you shouldn't have the issue with EasyList enabled.

**Comment by MDawg957** [comment]
> I could not reproduce with default lists, which includes EasyList, you shouldn't have the issue with EasyList enabled.

I messed around with it more and cutting off EasyList worked, but I looked at what could be causing it besides that since you said it wasn't causing the problem and it turned out I had Enhanced Tracking Protection set to custom with it blocking a number of things.  I switched it back to standard and reloaded the page came up properly.

**Comment by Enekk** [comment]
I am also experiencing this issue, it seems related to an element coming from Cloud Flare:
`https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194` (at least on the page https://www.seriouseats.com/all-american-beef-stew-recipe).

**Comment by mapx-** [comment]
@emagnuson85 provide your details: op system (android / windows / linux), filters enabled.

**Test using only the default settings.** (and no custom filters for this site)

**Comment by uBlock-user** [comment]
> I believe this issue should be reopened.

and do what ? Nobody on the team can reproduce. You should investigate why its specifically happening for you and also take some preliminary steps like reset uBO to default lists/settings + disable all other extensions and then try to reproduce the issue again.

**Comment by uBlock-user** [comment]
> As an additional step, I blocked www.relish.com, which seems to be what provides the script from cloudflareinsights, as a custom filter in My Filters, and the page no longer went blank when scrolling.

@ryanbr

**Comment by Enekk** [comment]
I can confirm that, yes, the scripts being provided to cloudflareinsights were coming from Relish and that blocking relish.com fixes the Serious Eats site.

**Comment by mapx-** [comment]
added to unbreak list

`||relish.com^$domain=seriouseats.com`
