### ISSUE TITLE
filma24.bz: ads

### ISSUE THREAD

**Issue by WhisperInTheDark** [uBlockOrigin/uAssets#11286]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.filma24.bz/`

### Category

ads

### Describe the issue

This website has ads and popups that go through the ublock origin filters.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 95
filterset (summary): 
  network: 78880
  cosmetic: 40425
  scriptlet: 16386
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30659-30, 2d.3h.3m
    ublock-badware: 3703-1, 2d.3h.2m
    ublock-privacy: 183-0, 2d.3h.1m
    ublock-abuse: 76-0, 2d.3h
    ublock-unbreak: 1689-0, 2d.2h.58m
    easylist: 62832-582, 2d.2h.57m
    easyprivacy: 26616-481, 2d.2h.56m
    urlhaus-1: 8106-0, 29m
    plowe-0: 3684-2, 2d.2h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5336 ms
popupPanel: 
  blocked: 21
```
</details>

**Comment by WaterIsH2O** [comment]
to be addressed by regional filter?

**Comment by okiehsch** [comment]
We don't have an albanian regional list in our setup.

**Comment by WaterIsH2O** [comment]
`https://www.filma24.bz/caught-in-time-2020-filma-me-titra-shqip/` => autoplay ad hidden btw

**Comment by okiehsch** [comment]
It's a youtube embed.
`||youtube.com/s/player/*$script,domain=filma24.bz`

**Comment by DandelionSprout** [comment]
I remember I was actively banking on and promoting the addition of https://raw.githubusercontent.com/AnXh3L0/blocklist/master/albanian-easylist-addition/Albania.txt into AdGuard and later uBO. There was just one problem: It had completely non-existent maintenance from its owners after January 2020.

**Comment by iam-py-test** [comment]
It has almost no commits?
https://github.com/AnXh3L0/blocklist/commits/master

**Comment by DandelionSprout** [comment]
>It has almost no commits?

Exactly.

**Comment by AnXh3L0** [comment]
Hello everyone, the reason why I didn't do any maintenance is because most of these Albanian websites use the same WordPress theme and basically the same classes/id-s to show ads, so blocking them becomes pretty easy. I will hopefully block some of my time to dedicate on making this list official and maintain it in the long run.

**Comment by uBlock-user** [comment]
fix is present in the regional list.
