### ISSUE TITLE
mozilla.org: breakage

### ISSUE THREAD

**Issue by androidkotlindev** [uBlockOrigin/uAssets#11283]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mozilla.org/en-US/firefox/browsers/mobile/`

### Category

breakage

### Describe the issue

When trying to download any of the mobile browsers, the domain adjust.com is blocked by Pete Lowe's server list

Steps to reproduce:

1. Try to download Firefox for Android, for iOS or Firefox Focus.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 95
filterset (summary): 
  network: 78592
  cosmetic: 40107
  scriptlet: 16392
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-137, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-0, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1719-0, never
    easylist: 62254-99, never
    easyprivacy: 26549-28, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-821, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4897 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
`adjust.com`:

> The analytics platform marketers trust

Just bypass temporarily or use the magnifier in the document-blocked page to navigate directly to the Play store.
