### ISSUE TITLE
radiotimes.com: breakage

### ISSUE THREAD

**Issue by DavidBE-UK** [uBlockOrigin/uAssets#11291]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.radiotimes.com/programme/b-ux0f99/rules-of-the-game-season-1/?episode=b-21lxna`

### Category

breakage

### Describe the issue

As of a couple of days ago, ALL specific programme pages on the Radio Times website have broken in Firefox - they load correctly but at the last moment as the loading completes they go completely blank. Note, this is ONLY the specific programme episode pages - the rets of the site works fine. This is with Firefox 96.0 and the previous version, and uBlock Origin 1.40.8 and the previous version. I have never changed and settings in uBlock Origiin from the default. Turning off uBlock Origin, these pages load fine. They also load OK if in uBlock Origin I turn off JavaScript in uBO. They ALSO load OK if uBlock Origin is back to default but I turn off the EasyPrivacy list (with JavaScript back on in uBO. I note that radiotimes.com is in the EasyPrivacy list, but don't understand the entry

Note that I have no problem with the radiotimes.com programme pages in Edge, with uBO 1.39.2, completely default settings, with the EasyPrivacy list on, and it does contain the radiotimes.com entry, so I rahter think this is a Firefox uBO, or uBO 1.40 problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 52954
  cosmetic: 40480
  scriptlet: 16407
  html: 616
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
  default: 
    ublock-filters: 30729-143, 6m
    ublock-badware: 3708-1, 6m
    ublock-privacy: 183-0, 6m
    ublock-abuse: 76-0, 6m
    ublock-unbreak: 1727-0, 1d.2h.13m
    easylist: 62914-459, 6m
    plowe-0: 3684-2, 52m
    urlhaus-1: 8163-0, 52m
filterset (user): [empty]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
  removed: 
    no-csp-reports: * true
modifiedUserSettings: 
  cnameUncloakEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4071 ms
popupPanel: 
  blocked: 9
```
</details>

**Comment by gorhill** [comment]
Seems to be caused by EasyList's `/static/advertising/*`.

cc @ryanbr, @Khrin

**Comment by DavidBE-UK** [comment]
Thanks, that seems to work.

**Comment by DavidBE-UK** [comment]
The problem has appeared again today, even though that filter is still in place.

**Comment by gorhill** [comment]
Unable to reproduce when using default settings and up to date lists. Post troubleshooting information from Support pane.

**Comment by DavidBE-UK** [comment]
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79060
  cosmetic: 40482
  scriptlet: 16407
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30729-144, 22h.55m
    ublock-badware: 3708-1, 22h.55m
    ublock-privacy: 183-0, 22h.55m
    ublock-abuse: 76-0, 22h.55m
    ublock-unbreak: 1727-0, 2d.1h.2m
    easylist: 62914-459, 22h.55m
    easyprivacy: 26622-489, now
    plowe-0: 3684-2, 23h.41m
    urlhaus-1: 8163-0, 23h.41m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
  removed: 
    no-csp-reports: * true
modifiedUserSettings: 
  cnameUncloakEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 701 ms (selfie)

As yesterday before adding the suggested filter above, other pages on radiotimes.com are fine, but specific programme pages visibly load, then just as it's finished loading the page goes completely blank. As yesterday, if I turn off the EasyPrivacy list the problem disappears. However, the fact that there's no such problem in Edge still makes me wonder if this is an issue with Firefox uBO or 1.40 uBO rather than the EasyPrivacy list per se.

**Comment by gorhill** [comment]
The fix was in EasyList, it's the list you need to update.

**Comment by DavidBE-UK** [comment]
I did update the list as soon as the problem re-occurred.

**Comment by DavidBE-UK** [comment]
And again. 'Last update: a minute ago' Programme pages load then immediately go blank, with or without the filter suggested yesterday.

**Comment by DavidBE-UK** [comment]
Please read my last - I just updated it again (now 4 minutes ago). Re-appeared problem still there.

**Comment by gorhill** [comment]
Well, in the end, if we can't reproduce, we can't fix. I tried the original URL you posted and I see no issue, while yesterday I could reproduce the issue. Please provide output of logger after you filter logger content for _blocked_ and _allowed_ entries.

**Comment by DavidBE-UK** [comment]
Oh, and it;s turning off EasyPrivacy, not EasyList, that lets it work.

**Comment by DavidBE-UK** [comment]
(Different page, but I get the same on every programme page)

Blocked:

+5
fuckadblock.js-3.2.0
<<
www.radiotimes.com
3
script
https://www.npttech.com/advertising.js

+5
||npttech.com/advertising.js$script,important,redirect-rule=fuckadblock.js-3.2.0
--
www.radiotimes.com
3
script
https://www.npttech.com/advertising.js

+5
||npttech.com^
--
www.radiotimes.com
3
script
https://www.npttech.com/advertising.js

+4
||ntv.io^$3p,domain=~teslarati.com
--
www.radiotimes.com
3
script
https://s.ntv.io/serve/load.js

+4
googletagmanager.com/gtm.js
<<
www.radiotimes.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K86F9FM

+4
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js
--
www.radiotimes.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K86F9FM

+4
||googletagmanager.com^
--
www.radiotimes.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K86F9FM

+3
/p.gif?
--
www.radiotimes.com
3
image
https://p.typekit.net/p.gif?s=1&k=fer7rij&ht=tk&h=www.radiotimes.com&f=14032.14033.14034.14035.14038.14039&a=532973&js=1.20.0&app=typekit&e=js&_=1642112275971

+2
##+js(abort-on-property-read, _sp_._networkListenerData)
www.radiotimes.com
dom
https://www.radiotimes.com/programme/b-u0403i/a-discovery-of-witches-season-3/?episode=b-tmmr29

+1
||permutive.com^
--
www.radiotimes.com
3
script
https://cdn.permutive.com/99db7a95-b06a-4ea9-857c-f73ba0a25c19-web.js

+1
||geni.us/snippet.min.js
--
www.radiotimes.com
3
script
https://cdn.geni.us/snippet.min.js

+1
||datadoghq-browser-agent.com^$3p
--
www.radiotimes.com
3
script
https://www.datadoghq-browser-agent.com/datadog-logs-v3.js

+1
||speedcurve.com^$3p
--
www.radiotimes.com
3
script
https://cdn.speedcurve.com/js/lux.js?id=430481854

+1
##+js(abort-on-property-read, _sp_._networkListenerData)
www.radiotimes.com
dom
https://www.radiotimes.com/programme/b-u0403i/a-discovery-of-witches-season-3/?episode=b-tmmr29

+1
||permutive.com^
--
www.radiotimes.com
3
script
https://cdn.permutive.com/99db7a95-b06a-4ea9-857c-f73ba0a25c19-web.js

+1
||geni.us/snippet.min.js
--
www.radiotimes.com
3
script
https://cdn.geni.us/snippet.min.js

+1
||speedcurve.com^$3p
--
www.radiotimes.com
3
script
https://cdn.speedcurve.com/js/lux.js?id=430481854

+1
googletagservices_gpt.js
<<
www.radiotimes.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+1
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js
--
www.radiotimes.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+1
||doubleclick.net^
--
www.radiotimes.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+0
https://www.radiotimes.com/programme/b-u0403i/a-discovery-of-witches-season-3/?episode=b-tmmr29

Allowed;

+2
@@||quantcast.mgr.consensu.org^*tcfv2*cmp2.js?referer=$script
++
www.radiotimes.com
3
script
https://quantcast.mgr.consensu.org/tcfv2/cmp2.js?referer=www.radiotimes.com/

+1
@@||radiotimes.com/static/advertising/$script,1p
++
www.radiotimes.com
1
script
https://www.radiotimes.com/static/advertising/adManager-505bf845fa0347f2166c.js

+0
https://www.radiotimes.com/programme/b-u0403i/a-discovery-of-witches-season-3/?episode=b-tmmr29


I did compare the contents between Firefox (with the problem) and Edge (without) last night, and noticed a few differences - uBO in Firefox blocking some things uBO didn't ... but I'm still not understanding how to change block to allow and vice versa for particular entries in the uBO dropdown pane.

**Comment by gorhill** [comment]
Somebody else who can reproduce will have to take over, I can't reproduce the original issue.

**Comment by gorhill** [comment]
Are you using Firefox's Enhanced Tracking Protection beyond default Standard mode?

**Comment by DavidBE-UK** [comment]
No I'm not. (Sorry for delay, I'm disabled and can only do internet conversations for short periods.)

And I come back again to the fact that this is only happening in desktop (Windoes 10) Firefox. It is not happening in Chrome; it is not happening in Edge. It is not happening even in Android Firefox. Surely they are all using the same EasyPrivacy list? Does this not point to a problem in uBO for Firefox rather than in the list?

**Comment by uBlock-user** [comment]
Reset uBO to default settings/lists and then test with all other extensions disabled.

**Comment by dmitryportvine** [comment]
@DavidBE-UK 
add & try again
`@@||www.datadoghq-browser-agent.com/datadog-logs-v3.js$script,domain=www.radiotimes.com`
<details>

```yaml
uBlock Origin: 1.40.9b0
Firefox: 96
filterset (summary): 
  network: 94573
  cosmetic: 106272
  scriptlet: 20918
  html: 643
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 29663-246, 1m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1378-0, 1m
    fanboy-cookiemonster: 21511-121, 1m
    ublock-annoyances: 4373-4, 1m
    RUS-0: 40862-298, 1m
  default: 
    user-filters: 1-0, never
    ublock-filters: 30747-51, 1m
    ublock-badware: 3723-1, 1m
    ublock-privacy: 186-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1733-6, 1m
    easylist: 62943-240, 1m
    easyprivacy: 26624-328, 8m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateDelayAfterLaunch: 60
  autoUpdatePeriod: 1
  filterAuthorMode: true
  uiFlavor: classic
supportStats: 
  allReadyAfter: 698 ms (selfie)
popupPanel: null
```
</details>
