### ISSUE TITLE
murf.ai: ads

### ISSUE THREAD

**Issue by Rispiderz** [uBlockOrigin/uAssets#11295]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://murf.ai/pricing`

### Category

ads pricing Plans

### Describe the issue

Pricing Plans 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 96
filterset (summary): 
  network: 84448
  cosmetic: 47528
  scriptlet: 16426
  html: 0
listset (total-discarded, last updated): 
  default: 
    ITA-0: 12722-0, 21h.58m
    easylist: 62804-13, 3d.4h.33m
    easyprivacy: 26607-19, 3d.4h.32m
    plowe-0: 3683-818, 7d.5h.15m
    ublock-abuse: 76-0, 3d.4h.31m
    ublock-badware: 3648-67, 3d.4h.30m
    ublock-filters: 30084-150, 3d.4h.29m
    ublock-privacy: 180-8, 3d.4h.28m
    ublock-unbreak: 1714-39, 3d.4h.26m
    urlhaus-1: 8135-0, 21h.57m
filterset (user): [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 17162 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
What ads are you talking about ? screenshot ?

**Comment by gorhill** [comment]
This makes no sense, these are pricing plans for using the site's services, not "ads".
