### ISSUE TITLE
n0where.net background advertising link

### ISSUE THREAD

**Issue by cyberjacob** [uBlockOrigin/uAssets#113]
### URL(s) where the issue occurs

`https://n0where.net/xsscrapy-xss-spider/`

### Describe the issue

White background around the page is an advert. No image, just clicking anywhere on the white page background opens an advert link (highlighted red in screenshot)

### Screenshot(s)

![2016-08-26 14_38_01-xsscrapy - xss sqli spider](https://cloud.githubusercontent.com/assets/161093/18007227/0e954f32-6b9b-11e6-9877-f2ee7d33e3fa.png)

### Versions

- Browser/version: FireFox 48.0.2
- uBlock Origin version: 1.8.4

### Settings

- Enabled additional filter sets

### Notes

Fix ready to be merged

**Comment by gorhill** [comment]
There is nothing special about the required filtering, a plain cosmtic filter works, report to EasyList maintainers please: `n0where.net##.background-ad` => <https://forums.lanik.us/viewforum.php?f=62>.
