### ISSUE TITLE
watch.travelchannel.com: ads

### ISSUE THREAD

**Issue by cameron-adrian** [uBlockOrigin/uAssets#11302]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watch.travelchannel.com/video/anthony-bourdain-no-reservations-travel-channel/nicaragua`

### Category

ads

### Describe the issue

Travel channel appears to have updated their website last night or this morning, including a different video player, seems to play full sets of ads (~2.5 mins) as one video, element zapper doesn't remove the ad so I think it's just playing instead of the video rather than on top of it? They appear at the expected times based on the cuts in the show. Happens on all episodes, I haven't tested any other shows though.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/52980873/149264020-860aff3e-aed4-46c3-9194-b77a9ace5843.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78695
  cosmetic: 40409
  scriptlet: 16385
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30657-29, 4d.33m
    ublock-badware: 3513-1, 4d.32m
    ublock-privacy: 183-0, 4d.31m
    ublock-abuse: 72-0, 4d.30m
    ublock-unbreak: 1723-0, 4d.28m
    easylist: 62801-579, 4d.27m
    easyprivacy: 26607-482, 4d.26m
    urlhaus-1: 8106-0, 12h.34m
    plowe-0: 3683-2, 7d.7h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 730 ms
popupPanel: 
  blocked: 37
```
</details>

**Comment by mapx-** [comment]
needing account and us ip (not vpn)

**Comment by mapx-** [comment]
I was able to reproduce the ads on a free episode
`https://watch.travelchannel.com/video/ghost-adventures-travel-channel/horror-in-biggs`

I get uplink requests which are SSAI specific

![image](https://user-images.githubusercontent.com/10303732/150183250-0f24d174-398d-46e3-ae3b-79ea3d4e4d1a.png)
