### ISSUE TITLE
Blocked payment with "klarna" (on adidas.com)

### ISSUE THREAD

**Issue by mariusrueve** [uBlockOrigin/uAssets#11308]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I tried paying with klarna on adidas.com (don't know if its specific for this site) but nothing happend. After disabling uBO I was able to use this payment method. 

### A specific URL where the issue occurs

`www.adidas.de/payment/`

### Steps to Reproduce

1. Try buying an item on this site
2. Proceed to payment methods
3. Select klarna

### Expected behavior

Popup window where you enter your birthdate and phone number in order to confirm your identity

### Actual behavior

No popup window, ongoing loading symbol

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 95
filterset (summary): 
  network: 78267
  cosmetic: 40438
  scriptlet: 16394
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30674-30, 2d.13h.49m
    ublock-badware: 3703-1, 2d.13h.47m
    ublock-privacy: 183-0, 2d.13h.46m
    ublock-abuse: 76-0, 2d.13h.45m
    ublock-unbreak: 1726-0, 2d.13h.44m
    easylist: 62882-582, 2d.13h.51m
    easyprivacy: 26616-481, 2d.13h.50m
    urlhaus-1: 7413-0, 18m
    plowe-0: 3685-2, 6d.16h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 700 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
test this filter

`@@||tags.tiqcdn.com^$script,domain=adidas.*`

**Comment by mariusrueve** [comment]
The filter fixed the issue for me. Everything work fine now! 👍🏼

**Comment by krystian3w** [comment]
Possible reproduction on nike.com / puma.com or rebook.com?

**Comment by mapx-** [comment]
If you can test them and report back

**Comment by krystian3w** [comment]
I can't speak in German, so must check @okiehsch

**Comment by okiehsch** [comment]
Why do you need to speak german to test?
`https://www.nike.com/pl/`
`https://eu.puma.com/pl/pl/home`
`https://www.reebok.pl/`

I don't have an account.

**Comment by mapx-** [comment]
@okiehsch I see `tags.tiqcdn.com` is not blocked by EP (but only by P.Lowe list), we have a lot of exceptions, an idea would be badfilter that filter, what do you think ?

**Comment by okiehsch** [comment]
> an idea would be badfilter that filter

Adguard does not block it in their privacy lists either, so it is something worth considering and I would be in favour.
@gorhill we have more than thirty filters fixing breakage caused by the filter in the `unbreak` list, what do you think?

**Comment by uBlock-user** [comment]
If it's only one script, could we have a redirect resource added @gorhill ?

**Comment by gorhill** [comment]
I don't mind this being badfiltered if it's constantly causing breakage.

Maybe eventually would be worth investigating a shim script for this -- I checked at [Firefox's repo](https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/data/shims.js) and they don't have one either as of now.

**Comment by Yuki2718** [comment]
> 
> Adguard does not block it in their privacy lists either, so it is something worth considering and I would be in favour. 

AG blocks `||tags.tiqcdn.com/utag/*/utag.v.js` and which I came accross at `https://sitecheck.sucuri.net/`.

**Comment by yokoffing** [comment]
> worth investigating a shim script for this

I agree! A shim would be great for `tags.tiqcdn.com`
