### ISSUE TITLE
[nsfw] share.myfreecams.com: privacy

### ISSUE THREAD

**Issue by GamerSyo** [uBlockOrigin/uAssets#11300]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://share.myfreecams.com/?`

### Category

privacy

### Describe the issue

wired web site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 96085
  cosmetic: 50425
  scriptlet: 16530
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 27378-87, 2d.9h.6m
    easylist: 62851-17, 2d.9h.3m
    easyprivacy: 26616-43, 2d.9h.2m
    plowe-0: 3684-819, 2d.1h.19m
    ublock-abuse: 76-0, 2d.8h.59m
    ublock-badware: 3648-67, 2d.8h.57m
    ublock-filters: 30105-163, 2d.8h.56m
    ublock-privacy: 186-3, 2d.8h.55m
    ublock-unbreak: 1716-40, 2d.8h.53m
    urlhaus-1: 8163-0, 15h.37m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 13678 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
what's the issue ?
