### ISSUE TITLE
privatenewz.com: detection

### ISSUE THREAD

**Issue by prono69** [uBlockOrigin/uAssets#11309]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://privatenewz.com/`

### Category

detection

### Describe the issue

This site is showing that I have an ad blocker and i need to disable that.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20220114-182345](https://user-images.githubusercontent.com/55076817/149518511-05b7fc0e-cb2d-406a-8664-0393044e9e10.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium Mobile: 98
filterset (summary): 
  network: 141435
  cosmetic: 100219
  scriptlet: 51366
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 27114-198, 28m
    adguard-annoyance: 48926-1724, 3d.5h.48m
    adguard-generic: 61647-1910, 3d.5h.47m
    adguard-spyware: 25045-769, 3d.5h.45m
    dpollock-0: 16948-263, 10d.20h.59m
    fanboy-cookiemonster: 21463-13744, 2d.23h.46m
    mvps-0: 8730-1830, 10d.20h.59m
    ublock-annoyances: 4383-318, 2d.6h.27m
  default: 
    adguard-mobile: 7061-65, 3d.5h.46m
    easylist: 62859-24733, 2d.19h.29m
    easyprivacy: 26616-10799, 2d.19h.28m
    plowe-0: 3682-1497, 11d.5h.35m
    ublock-abuse: 76-1, 2d.6h.28m
    ublock-badware: 3699-210, 2d.6h.26m
    ublock-filters: 30225-6376, 2d.6h.24m
    ublock-privacy: 186-30, 2d.6h.23m
    ublock-unbreak: 1722-112, 2d.6h.22m
    urlhaus-1: 7395-0, 19h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 18465 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by uBlock-user** [comment]
> Chromium Mobile: 98

How did you install uBO on Chrome Mobile ?

**Comment by uBlock-user** [comment]
Kiwi issue. Kiwi browser also detects and disables uBO selectively, so avoid it.

**Comment by gorhill** [comment]
Also I cannot reproduce when using mobile emulator in Chromium along with the `+mobile` flavor modifier, and neither on Firefox for Android using default settings/lists.

**Comment by mapx-** [comment]
The filter fixing the issue was added 2 days ago, so @prono69 just update your lists

**Comment by gorhill** [comment]
> The filter fixing the issue was added 2 days ago

So I just wasted a good amount of time trying to reproduce because OP couldn't bother answering truthfully.

> To avoid burdening **VOLUNTEERS** with invalid or duplicate reports, disrespecting these steps **WILL** result in your account being blocked on this repo (temporarily, then permanently with repeated disregard for the template).
> 
> ### Prerequisites 

> - [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
