### ISSUE TITLE
donanimhaber.com: ads

### ISSUE THREAD

**Issue by ddhelmet** [uBlockOrigin/uAssets#11304]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.donanimhaber.com/`

### Category

ads

### Describe the issue

background image ad thingy still in the background and when you click accidentally ad opens. also ad on the top of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/25013377/149312491-dcc393cc-7ffc-48d6-9d3d-82074a4d1b7e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78323
  cosmetic: 40486
  scriptlet: 16407
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30729-29, 55m
    ublock-badware: 3708-1, 54m
    ublock-privacy: 183-0, 53m
    ublock-abuse: 76-0, 52m
    ublock-unbreak: 1728-0, 51m
    easylist: 62917-582, 49m
    easyprivacy: 26622-482, 48m
    urlhaus-1: 7417-0, 47m
    plowe-0: 3684-2, 46m
filterset (user): [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1664 ms
popupPanel: 
  blocked: 10
```
</details>

**Comment by okiehsch** [comment]
It's fixed in the regional list. Enable `AdGuard Turkish`.
