### ISSUE TITLE
ingenio-rx.com: breakage

### ISSUE THREAD

**Issue by ildeleaf** [uBlockOrigin/uAssets#11319]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ingenio-rx.com/login/?locale=en_US`

### Category

breakage

### Describe the issue

site folds in on itself when attempting to use member login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78052
  cosmetic: 40445
  scriptlet: 16395
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30682-29, 3d.6h.52m
    ublock-badware: 3662-1, 3d.6h.51m
    ublock-privacy: 183-0, 3d.6h.50m
    ublock-abuse: 76-0, 3d.6h.49m
    ublock-unbreak: 1727-0, 3d.6h.48m
    easylist: 62882-582, 3d.6h.47m
    easyprivacy: 26616-482, 3d.6h.46m
    urlhaus-1: 7239-0, 6h.40m
    plowe-0: 3684-2, 3d.6h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1309 ms
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
@ildeleaf Do we need an account to get the issue or even with a random one the issue is reproducible ?
Explain better the issue (adding some screenshot too)

**Comment by ildeleaf** [comment]
Apologies, it looks like it was an issue on their end.
