### ISSUE TITLE
videoredaktor.ru: detection

### ISSUE THREAD

**Issue by maksim029** [uBlockOrigin/uAssets#11315]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://videoredaktor.ru/a/obrezat-video`

### Category

detection

### Describe the issue

This website video-editor detects uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/97759793/149573326-59fb9266-2a7b-4ef6-866e-58b90cce14d2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 94
filterset (summary): 
  network: 65504
  cosmetic: 68
  scriptlet: 17703
  html: 613
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
    easyprivacy: null
  default: 
    ublock-filters: 30620-7332, 10d.1h.38m
    ublock-abuse: 76-0, 10d.1h.37m
    easylist: 62608-32485, 10d.1h.37m
    urlhaus-1: 7408-0, 10d.1h.37m
    plowe-0: 3683-372, 10d.1h.37m
    RUS-0: 40658-21010, 10d.1h.37m
filterset (user): [array of 92 redacted]
modifiedUserSettings: 
  autoUpdate: false
  cnameUncloakEnabled: false
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2225 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>
![изображение](https://user-images.githubusercontent.com/97759793/149574239-ab197a52-7ed2-43ab-b5e1-414d5942ef52.png)

**Comment by dmitryportvine** [comment]
Unable to reproduce.
<details>

```yaml
uBlock Origin: 1.40.9b1
Firefox: 96
filterset (summary): 
  network: 94634
  cosmetic: 106283
  scriptlet: 20924
  html: 643
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 29669-246, 2m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1378-0, 2m
    fanboy-cookiemonster: 21511-121, 2m
    ublock-annoyances: 4378-4, 2m
    RUS-0: 40872-299, 2m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30752-51, 2m
    ublock-badware: 3723-1, 2m
    ublock-privacy: 187-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1733-6, 2m
    easylist: 62997-241, 2m
    easyprivacy: 26624-328, 2m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateDelayAfterLaunch: 60
  autoUpdatePeriod: 1
  filterAuthorMode: true
  uiFlavor: classic
supportStats: 
  allReadyAfter: 1735 ms
  maxAssetCacheWait: 881 ms
popupPanel: null
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/149583934-1a69034f-09de-4a03-9869-69fc9d8a6556.png)

it's not true, you removed 4 default lists

**Comment by dimisa-RUAdList** [comment]
The problem reproduces when trying to add a video file: https://i.imgur.com/x8NVAJU.jpg

Resolved with: `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=videoredaktor.ru`
Or: `videoredaktor.ru##+js(abort-on-property-read, _aaa_load)`

Fix: https://github.com/easylist/ruadlist/commit/b2505c1e227f4abe029f3a7ba284248fd844517d
