### ISSUE TITLE
mi.tigo.com.co: breakage

### ISSUE THREAD

**Issue by joartgotv** [uBlockOrigin/uAssets#11313]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mi.tigo.com.co/ingresar`

### Category

breakage

### Describe the issue

The hole page doesn't appear when the addon is on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78345
  cosmetic: 40714
  scriptlet: 16397
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30707-30, 1d.18h.45m
    ublock-badware: 3708-1, 1d.18h.43m
    ublock-privacy: 183-0, 1d.18h.42m
    ublock-abuse: 76-0, 1d.18h.41m
    ublock-unbreak: 1728-0, 1d.18h.39m
    easylist: 62920-582, 1d.18h.38m
    easyprivacy: 26620-481, 1d.18h.37m
    urlhaus-1: 7356-0, 20h.57m
    plowe-0: 3682-2, 10d.21h.34m
filterset (user): [array of 356 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6537 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by okiehsch** [comment]
`@@||tigo.com.co/plugins/cordova-plugin-fingerprint-aio/*/Fingerprint.js$script,1p`
@ryanbr
