### ISSUE TITLE
youinvest.co.uk: breakage

### ISSUE THREAD

**Issue by nashsibanda** [uBlockOrigin/uAssets#11312]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youinvest.co.uk/`

### Category

breakage

### Describe the issue

The "do you accept cookies" modal that pops up on first accessing the site is hidden, but the rest of the site is darkened and unusable. I need to disable uBO to accept/reject cookies before I can use the rest of the site.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 153148
  cosmetic: 188167
  scriptlet: 33000
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 3m
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 1d.16h.9m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 2m
    JPN-1: 5732-6, 19h.31m
    adguard-annoyance: 49056-192, 19h.20m
    adguard-generic: 61863-736, 19h.19m
    adguard-mobile: 7078-57, 19h.28m
    adguard-social: 15448-798, 19h.27m
    adguard-spyware: 25080-782, 19h.29m
    dpollock-0: 16948-309, 4d.8h.20m
    fanboy-annoyance: 59687-3966, 6d.16h.56m
    fanboy-cookiemonster: 21376-21376, 6d.16h.55m
    fanboy-social: 23147-23142, 19h.21m
    fanboy-thirdparty_social: 68-21, 6d.16h.57m
    mvps-0: 8730-1834, 4d.21h.10m
    ublock-annoyances: 4363-293, 19h.17m
  default: 
    easylist: 62917-1361, 19h.26m
    easyprivacy: 26622-10860, 19h.25m
    plowe-0: 3685-1499, 6d.16h.58m
    ublock-abuse: 76-0, 19h.24m
    ublock-badware: 3704-214, 19h.23m
    ublock-filters: 30138-3298, 19h.30m
    ublock-privacy: 187-37, 19h.22m
    ublock-unbreak: 1716-113, 19h.16m
    urlhaus-1: 7413-0, 3h.15m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 14747 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by uBlock-user** [comment]
Caused by `###cookie-modal` in Fanboy Annoyances List.

@ryanbr
