### ISSUE TITLE
warezcrack.net: popups

### ISSUE THREAD

**Issue by Rajdave69** [uBlockOrigin/uAssets#11310]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://warezcrack.net/`

### Category

popups

### Describe the issue

this is a scam/useless website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 78412
  cosmetic: 40542
  scriptlet: 16435
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 5d.21h.45m
  default: 
    easylist: 62897-9, 1d.21h.38m
    easyprivacy: 26619-17, 1d.21h.37m
    plowe-0: 3683-817, 8d.6h.3m
    ublock-abuse: 76-0, 1d.21h.41m
    ublock-badware: 3699-67, 2d.2h.18m
    ublock-filters: 30130-144, 1d.21h.42m
    ublock-privacy: 186-3, 2d.2h.17m
    ublock-unbreak: 1716-39, 1d.21h.39m
    urlhaus-1: 7484-0, 7h.59m
filterset (user): [array of 73 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 172 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Yes i know these sites ... there are over 100 of them https://github.com/blocklistproject/Lists/issues/588

**Comment by mapx-** [comment]
You could prepare a PR to add to our badware list

**Comment by JobcenterTycoon** [comment]
Do you mean me? All domains?

**Comment by mapx-** [comment]
If still an issue and if you want to add them to our list
