### ISSUE TITLE
index.hr: ads

### ISSUE THREAD

**Issue by zorandekic** [uBlockOrigin/uAssets#11311]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.index.hr/vijesti/clanak/kina-proslu-godinu-zakljucila-s-rekordnim-trgovinskim-viskom/2332529.aspx?index_ref=naslovnica_vijesti_najnovije_d`

### Category

ads

### Describe the issue

There are ads leftovers as displayed here in a screenshot:

![image](https://user-images.githubusercontent.com/76431976/149537145-a21197c2-891a-4014-8cc6-8c7b6b3be836.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78195
  cosmetic: 40457
  scriptlet: 16432
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 9m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 62832-9, 3d.21h.52m
    easyprivacy: 26616-17, 3d.21h.51m
    plowe-0: 3683-817, 9d.8h.28m
    ublock-abuse: 76-0, 3d.21h.49m
    ublock-badware: 3699-67, 3d.21h.48m
    ublock-filters: 30123-144, 3d.21h.47m
    ublock-privacy: 186-3, 3d.21h.46m
    ublock-unbreak: 1715-39, 3d.21h.45m
    urlhaus-1: 7395-0, 16h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 78 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 205 ms (selfie)
popupPanel: 
  blocked: 21
  no-cosmetic-filtering: true
```
</details>

**Comment by gorhill** [comment]
This works:

    index.hr##[data-css-class="dfp-inarticle"]

**Comment by mapx-** [comment]
@ryanbr
