### ISSUE TITLE
[nsfw] vr-system98622.com: popups

### ISSUE THREAD

**Issue by DEtrees95** [uBlockOrigin/uAssets#11318]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vr-system98622.com/4LRIEJWYN3`

### Category

phishing

### Describe the issue

its no officiel bank website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 80522
  cosmetic: 43590
  scriptlet: 16435
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5214-0, 20h.36m
    easylist: 62895-15, 2d.23h
    easyprivacy: 26619-28, 2d.23h
    plowe-0: 3684-818, 2d.23h
    ublock-abuse: 76-0, 2d.22h.59m
    ublock-badware: 3699-67, 2d.22h.58m
    ublock-filters: 30205-152, 2d.22h.57m
    ublock-privacy: 195-3, 2d.22h.57m
    ublock-unbreak: 1744-40, 2d.22h.56m
    urlhaus-1: 7484-0, 20h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 219
  launchFromSelfie: true
popupPanel: 
  blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
Firefox => blocked by GSB
Edge => 404 Not Found

**Comment by Yuki2718** [comment]
@DEtrees95 Is the site still accessible to you? If so, which country/region you accessed from?

**Comment by dmitryportvine** [comment]
<details>
<summary>Screenshot(s)</summary>

![2022-01-15_111033](https://user-images.githubusercontent.com/97522612/149616431-542bacfc-42ef-4522-9dcf-2f593ed0fb38.png)
![2022-01-15_111040](https://user-images.githubusercontent.com/97522612/149616433-76e4a02d-866b-476e-a887-8f4a336f8421.png)
</details>
