### ISSUE TITLE
wellnessincentives.com: breakage

### ISSUE THREAD

**Issue by Kyep** [uBlockOrigin/uAssets#11317]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wellnessincentives.com/`

### Category

breakage

### Describe the issue

Attempting to log in with valid credentials prompts for captcha, then gives error "A system error has occurred. Please try again later."
This happens every time you attempt to log in with ublock enabled.
Disabling ublock fixes the issue and lets you log in normally. Usually without a captcha.
This issue is repeatable in both Chrome and Firefox.
If I had to guess, I would say the problem is blocking kaptcha.com, which may be part of their login captcha system.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![wellnessincentives-dot-com](https://user-images.githubusercontent.com/16434066/149600904-85cb754a-857b-4384-a169-591064dd8934.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78466
  cosmetic: 40508
  scriptlet: 16462
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63002-9, 3m
    easyprivacy: 26625-17, 3m
    plowe-0: 3682-816, 3m
    ublock-abuse: 76-0, 3m
    ublock-badware: 3719-67, 3m
    ublock-filters: 30177-145, 3m
    ublock-privacy: 190-3, 3m
    ublock-unbreak: 1722-39, 3m
    urlhaus-1: 7484-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 251 ms
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
I get the system error even disabling uBO.
I used some random credentials (I don't get user / pass non existent but directly "system error")
