### ISSUE TITLE
9anime.to: breakage

### ISSUE THREAD

**Issue by Abhigaruji** [uBlockOrigin/uAssets#11323]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.to/watch/yashahime-princess-half-demon-the-second-act.86mq/ep-15`

### Category

breakage

### Describe the issue

The Disqus coment section is not showing.
I disabled unblock and checked then it's working .
What's the fix for this?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 95
filterset (summary): 
  network: 214217
  cosmetic: 189452
  scriptlet: 25199
  html: 715
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5359-244, 3h.24m
    adguard-spyware: 25091-1243, 3h.26m
    adguard-spyware-url: 440-3, 3h.26m
    block-lan: 44-0, 3h.26m
    curben-phishing: 9581-4, 3h.26m
    curben-pup: 388-0, 3h.26m
    adguard-annoyance: 49106-4628, 3h.26m
    adguard-social: 15480-1084, 3h.26m
    fanboy-thirdparty_social: 68-1, 3h.26m
    fanboy-annoyance: 63108-52074, 3h.26m
    fanboy-cookiemonster: 21516-13000, 3h.26m
    fanboy-social: 23148-14048, 3h.26m
    ublock-annoyances: 4398-11, 3h.26m
    dpollock-0: 10347-578, 3h.26m
    mvps-0: 8730-1526, 3h.26m
    ara-0: 2330-244, 3h.26m
    BGR-0: 1116-19, 3h.26m
    CHN-0: 27488-1152, 3h.26m
    CZE-0: 778-40, 3h.26m
    DEU-0: 5238-374, 3h.26m
    [27 lists not shown]: [too many]
  default: 
    ublock-filters: 30856-652, 3h.27m
    ublock-badware: 3723-1, 3h.27m
    ublock-privacy: 187-1, 3h.27m
    ublock-abuse: 76-0, 3h.26m
    ublock-unbreak: 1739-0, 3h.26m
    adguard-mobile: 7082-259, 3h.26m
    easylist: 63005-24934, 3h.26m
    easyprivacy: 26626-11217, 3h.26m
    urlhaus-1: 7275-4, 3h.26m
    plowe-0: 3682-2, 3h.26m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 15 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1474 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by mapx-** [comment]
bad filter in `IDN, MYS: ABPindo` triggering cname filter

add

`||d231vab146qzfb.cloudfront.net^$badfilter`

**Comment by mapx-** [comment]
@gmarcher

why that filter in IDN ?

**Comment by gmarcher** [comment]
thanks for the report, fixed

**Comment by Abhigaruji** [comment]
Thanks @gmarcher now it's working.
