### ISSUE TITLE
primeos.in: ads

### ISSUE THREAD

**Issue by PhoenixOnARoof** [uBlockOrigin/uAssets#11320]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.primeos.in/`

### Category

ads

### Describe the issue

Across the whole site, the main site, the forums, the blog, everywhere. There is a popup ad that takes up a very large portion of the page and you have to wait to click it away. There is also a banner ad across the bottom. There is also some ads as part of the content on the home page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_hCogXMgmbq](https://user-images.githubusercontent.com/11891199/149614730-6c68c2c8-9abb-4423-a767-398e5f40dd1d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78276
  cosmetic: 40482
  scriptlet: 16398
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30713-29, 2d.21h.14m
    ublock-badware: 3703-1, 2d.21h.20m
    ublock-privacy: 183-0, 2d.21h.19m
    ublock-abuse: 76-0, 2d.21h.18m
    ublock-unbreak: 1727-0, 2d.21h.17m
    easylist: 62897-573, 2d.21h.16m
    easyprivacy: 26619-491, 2d.21h.15m
    urlhaus-1: 7413-0, 21h.7m
    plowe-0: 3684-2, 3d.22h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 227 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by mapx-** [comment]
add

```
primeos.in##.elementor-popup-modal
primeos.in##body:style(overflow: auto !important;)
||amazonaws.com/release/redirect-link?event_name=AFFILIATE_AD_VIEWED
```

@ryanbr

**Comment by Yuki2718** [comment]
@mapx- Maybe we should directly fix? These seem to be ads but EL doesn't use `:style()`.

**Comment by mapx-** [comment]
@ryanbr  has a uBO section in his FA list, then it's also `amazonaws` crap to be added in EL, but you are right .. we could add at least the first 2 in our annoyances list

**Comment by mapx-** [comment]
@ArgX11 screenshot ? page link where are the ads ?
