### ISSUE TITLE
creativecow.net: ads

### ISSUE THREAD

**Issue by GRPSCL** [uBlockOrigin/uAssets#11327]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://creativecow.net/forums/thread/fade-out-offset-not-working-on-one-clip/`

### Category

ads

### Describe the issue

I'm seeing an ad on the right of the website ; looks like it's a direct link to the company making the product the ad is for, which explains why uBlock didn't pick up on it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss](https://user-images.githubusercontent.com/96879644/149641894-64d1e2ea-1839-40b1-a43c-c0d54dc9c580.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 95
filterset (summary): 
  network: 78291
  cosmetic: 40533
  scriptlet: 16414
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30740-29, 1d.6h.47m
    ublock-badware: 3723-1, 1d.6h.46m
    ublock-privacy: 187-0, 1d.2h.42m
    ublock-abuse: 76-0, 1d.6h.44m
    ublock-unbreak: 1732-0, 1d.6h.43m
    easylist: 62997-582, 1d.6h.48m
    easyprivacy: 26623-481, 2d.1h.5m
    plowe-0: 3682-2, 12d.22h.59m
    urlhaus-1: 7306-0, 8h.34m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1563 ms
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
add

`creativecow.net##.cowtracks-widget.widget`

@ryanbr
