### ISSUE TITLE
elpais.com: privacy

### ISSUE THREAD

**Issue by SWhitefox** [uBlockOrigin/uAssets#11326]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://elpais.com/sociedad/2022-01-15/el-exito-de-las-vacunas-contra-omicron-los-vacunados-tienen-cinco-veces-menos-probabilidad-de-ingresar-en-un-hospital.html`

### Category

privacy

### Describe the issue

The page detects when you are browsing in private mode (tested with Firefox Android) and then it hides its content, blocks the scrolling, and forces you to signup or login (paywallIncognitoLayer).

In normal mode it tries to force you to accept tracking cookies.

It happens in any article, linked that one as an example.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 95
filterset (summary): 
  network: 82562
  cosmetic: 26324
  scriptlet: 16613
  html: 619
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30812-328, 1d.18h.2m
    ublock-badware: 3708-1, 1d.18h.1m
    ublock-privacy: 184-1, 1d.18h
    ublock-abuse: 76-0, 1d.14h.30m
    ublock-unbreak: 1738-0, 1d.14h.28m
    adguard-mobile: 7080-173, 1d.18h.3m
    easylist: 62940-24291, 1d.14h.27m
    easyprivacy: 26624-505, 1d.14h.26m
    urlhaus-1: 7306-0, 15h.56m
    plowe-0: 3684-2, 4d.13h.1m
    spa-0: 3629-220, 15h.57m
    spa-1: 4181-177, 1d.18h.4m
filterset (user): [array of 8 redacted]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 372 ms (selfie)
popupPanel: 
  blocked: 22
```
</details>

**Comment by mapx-** [comment]
- for normal navigation enable `Fanboy’s Annoyance` list
- for private window add & test:

`elpais.com##+js(nostif, run)`

**Comment by SWhitefox** [comment]
> * for normal navigation enable `Fanboy’s Annoyance` list
> 
>     * for private mode add & test:
> 
> 
> `elpais.com##+js(nostif, run)`

It did work, thank you!
