### ISSUE TITLE
mail.tm detection

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#11330]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mail.tm`

### Describe the issue

Soft anti-adblock

### Screenshot(s)

* uBO on:
![image](https://user-images.githubusercontent.com/17685483/149647885-2de80561-0816-4dfc-81bc-59622122d550.png)

* uBO off:
![image](https://user-images.githubusercontent.com/17685483/149647904-49dcc09b-13c8-45d7-8806-ddbf22c1f981.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79461
  cosmetic: 40521
  scriptlet: 16467
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63009-9, now
    easyprivacy: 26626-17, now
    plowe-0: 3682-816, now
    ublock-abuse: 76-0, now
    ublock-badware: 3724-67, now
    ublock-filters: 30189-145, now
    ublock-privacy: 190-3, now
    ublock-unbreak: 1723-39, now
    urlhaus-1: 8471-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 147 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
to be tested

`mail.tm##+js(nostif, init())`

**Comment by uBlock-user** [comment]
That could break something in the future, this is a placeholder, so should go with -- 
`mail.tm##.dark\:border-gray-700.border-gray-200.border-r-0.border-l-0`

**Comment by MasterKia** [comment]
> this is a placeholder

Well they would still detect adblock so it would be a matter of time before they change the soft anti-adb into a hard one (or maybe not).

**Comment by uBlock-user** [comment]
> Well they would still detect adblock

That would happen regardless of any filter you add.

**Comment by MasterKia** [comment]
> That would happen regardless of any filter you add.

Doesn't the `mail.tm##+js(nostif, init())` filter (suggested by @mapx-) stop the detection from happening? (_for now_)

**Comment by uBlock-user** [comment]
> Doesn't the mail.tm##+js(nostif, init()) filter

For now, my response was towards your argument -- "it would be a matter of time before they change the soft anti-adb into a hard one"

**Comment by mapx-** [comment]
> > That would happen regardless of any filter you add.
> 
> Doesn't the `mail.tm##+js(nostif, init())` filter (suggested by @mapx-) stop the detection from happening? (_for now_)

Does it work for you ?
Does it break some functionality ?

**Comment by MasterKia** [comment]
> Does it work for you ? 

Yes
> Does it break some functionality ?

As far as I tested, no.

**Comment by MasterKia** [comment]
I'll report back if it breaks any functionality in the future.

**Comment by MasterKia** [comment]
The nag is back.
