### ISSUE TITLE
youmath.it: detection

### ISSUE THREAD

**Issue by PeksonK** [uBlockOrigin/uAssets#11337]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youmath.it/lezioni/analisi-due/equazioni-differenziali.html`

### Category

detection

### Describe the issue

the website reveals the adblock and i can't do anything but disable it xd

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Cattura](https://user-images.githubusercontent.com/45921868/149683506-57fdeeb7-acf7-40b0-b464-662c4311345e.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 84681
  cosmetic: 47587
  scriptlet: 16434
  html: 0
listset (total-discarded, last updated): 
  default: 
    ITA-0: 12723-0, 6h.14m
    easylist: 62917-13, 3d.12h.2m
    easyprivacy: 26622-19, 3d.12h.1m
    plowe-0: 3683-817, 11d.1h.51m
    ublock-abuse: 76-0, 3d.12h
    ublock-badware: 3704-67, 3d.11h.58m
    ublock-filters: 30132-151, 3d.11h.57m
    ublock-privacy: 186-3, 3d.5h.3m
    ublock-unbreak: 1716-39, 3d.5h.2m
    urlhaus-1: 8198-0, 6h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 267 ms (selfie)
popupPanel: 
  blocked: 8
  no-scripting: true
```
</details>

**Comment by uBlock-user** [comment]
Existing fix still works, test on default settings/lists.

**Comment by JobcenterTycoon** [comment]
I can reproduce tested on FF, They check

```
youmath.it/media/-adspot-/sadasds.js
securepubads.g.doubleclick.net/tag/js/gpt.js
```

**Comment by uBlock-user** [comment]
@JobcenterTycoon `youmath.it##+js(acis, document.getElementById, _0x)`
 is the fix.

**Comment by PeksonK** [comment]
How does that work?

**Comment by uBlock-user** [comment]
I already added it few days ago, force update uBlock filters if you haven't yet.

**Comment by JobcenterTycoon** [comment]
I still get anti adb

**Comment by PeksonK** [comment]
Same, how do i force update the filters?

**Comment by JobcenterTycoon** [comment]
Click on the uBO logo -> menu (gearwheel) -> filter list -> purge all cache -> update now

**Comment by PeksonK** [comment]
Yeah same

**Comment by PeksonK** [comment]
i tried importing the fix but it ignores it

**Comment by uBlock-user** [comment]
@JobcenterTycoon `youmath.it##+js(aost, document.getElementById, inlineScript)` works ?

**Comment by PeksonK** [comment]
not for me

**Comment by okiehsch** [comment]
The existing fix works fine on my end using Firefox.

**Comment by JobcenterTycoon** [comment]
@uBlock-user not working

**Comment by uBlock-user** [comment]
@PeksonK because you're doing it wrong, you don't import, you add it to my filters. Anyways, I don't get any anti-adb. 

@JobcenterTycoon Perhaps you're suffering from race condition.

**Comment by okiehsch** [comment]
I can reproduce using chromium though, hm.

**Comment by uBlock-user** [comment]
@okiehsch `youmath.it##+js(aost, document.getElementById, inlineScript)` works ?

**Comment by okiehsch** [comment]
No.

**Comment by PeksonK** [comment]
i did import it..

**Comment by okiehsch** [comment]
`youmath.it##+js(nostif, adblocker)`
works on my end using chromium.

**Comment by uBlock-user** [comment]
I am going with `@@||youmath.it/$script,1p`, admin is changing baits every now and then.

**Comment by okiehsch** [comment]
Well, my filter is independent of any bait script, but fine by me.

**Comment by JobcenterTycoon** [comment]
@okiehsch works for me (i not checked for breakage i not speak this language)

**Comment by PeksonK** [comment]
youmath.it##+js(nostif, adblocker)
this one works for me

**Comment by uBlock-user** [comment]
@okiehsch `youmath.it##+js(nostif, offsetHeight)` works ?

**Comment by okiehsch** [comment]
Yes.

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by JobcenterTycoon** [comment]
Still get anti adb after accepting cookies

**Comment by JobcenterTycoon** [comment]
re adding `youmath.it##+js(nostif, offsetHeight)` works for me

**Comment by JobcenterTycoon** [comment]
Anti select annoyance is back

**Comment by mapx-** [comment]
working in FF but not in chrome

**Comment by mapx-** [comment]
seems working `youmath.it##+js(aopw, document.onmousedown)`
