### ISSUE TITLE
speedtest.net: breakage

### ISSUE THREAD

**Issue by abinlatheef** [uBlockOrigin/uAssets#11332]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.speedtest.net/`

### Category

breakage

### Describe the issue

The contents of the page get aligned to the left side when ublock is enabled. Not a big problem, but a bit bad aesthetically. It used to work before (1 or 2 months before I guess). I wish we could fix that.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79404
  cosmetic: 40520
  scriptlet: 16428
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30764-30, 1h.21m
    ublock-badware: 3728-1, 1h.19m
    ublock-privacy: 186-0, 1h.18m
    ublock-abuse: 76-0, 1h.17m
    ublock-unbreak: 1727-0, 3d.3h.35m
    easylist: 63007-583, 1h.23m
    easyprivacy: 26626-480, 1h.22m
    urlhaus-1: 8415-0, 14h.29m
    plowe-0: 3682-2, 14h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 506 ms
popupPanel: 
  blocked: 9
```
</details>

**Comment by uBlock-user** [comment]
Consequences of blocking ad/ad placeholders.

**Comment by abinlatheef** [comment]
But I tried using Adblock Plus and there is no problem there.

**Comment by uBlock-user** [comment]
Should be there, changes in the layout appear because of speedtest.net##.pure-u-custom-ad-skyscraper which is present in EasyList which is only used by ABP, so you investigate why doesn't it happen with ABP.

**Comment by abinlatheef** [comment]
ublock shows like how ABP does, when cosmetic filtering is disabled for that site. Don't ABP have cosmetic filtering?

**Comment by uBlock-user** [comment]
> Don't ABP have cosmetic filtering?

I don't know, uBO is doing its job as expected, while ABP is not. Ask the devs of ABP.

**Comment by mapx-** [comment]
It's the same layout in ABP using the default filters.

Just add 

`speedtest.net#@#.pure-u-custom-ad-skyscraper`

**Comment by abinlatheef** [comment]
Wow. It worked. Thanks.
What did we do here?

**Comment by mapx-** [comment]
"We" could only ask @ryanbr to review that filter if still necessary for whatever reason

**Comment by abinlatheef** [comment]
Sorry, didn't understand what you said.

**Comment by mapx-** [comment]
meaning I've notified EL maintainer if he could remove that filter / review it

**Comment by gorhill** [comment]
> I tried using Adblock Plus and there is no problem there.

The filter was added [not that long ago](https://github.com/easylist/easylist/commit/c3eecfb1306957c447642b1268e5479c97a2bf56#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2), so if ABP had not updated its lists since then, it would not have the issue. Using up to date lists is key, ABP has the same exact issue with up to date list.

**Comment by abinlatheef** [comment]
Ohh. Thanks for the info @gorhill and @mapx- . 🌹🎕🎕
