### ISSUE TITLE
adorebeauty.com.au: nuisance

### ISSUE THREAD

**Issue by meuphs** [uBlockOrigin/uAssets#11331]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.adorebeauty.com.au/the-ordinary.html`

### Category

nuisance

### Describe the issue

Even after blocking pop up elements on page they still appear when refreshed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 78409
  cosmetic: 40553
  scriptlet: 16463
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 19h.4m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 63005-9, 19h.8m
    easyprivacy: 26626-17, 19h.7m
    plowe-0: 3682-816, 1h.4m
    ublock-abuse: 76-0, 19h.6m
    ublock-badware: 3719-67, 19h.11m
    ublock-filters: 30184-145, 1h.3m
    ublock-privacy: 189-3, 19h.10m
    ublock-unbreak: 1722-39, 19h.9m
    urlhaus-1: 7306-0, 19h.3m
filterset (user): [array of 42 redacted]
trustedset: 
  added: [array of 55 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2034 ms (selfie)
popupPanel: 
  blocked: 72
  no-popups: true
```
</details>

**Comment by mapx-** [comment]
What popups ? screenshot ?

Try removing these lists (first one full of exceptions, the others empty)
```
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 19h.4m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
```
