### ISSUE TITLE
inbenta.io customer service problems (found at knab.nl)

### ISSUE THREAD

**Issue by skinkie** [uBlockOrigin/uAssets#11334]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://knab.nl/` internal customer support.

inbenta-km-sdk.js?v=1.1.1.133:1 POST https://api-gce3.inbenta.io/prod/km/v1/tracking/events net::ERR_BLOCKED_BY_CLIENT

### Describe the issue

Customer service help pages don't function because the XMLHttpRequest is blocked.

### uBlock Origin version

1.40.8

### Browser name and version

Version 97.0.4692.71

### Settings

None.

**Comment by mapx-** [comment]
I guess an account is necessary and the steps to reproduce the issue.

or open the logger, reproduce the issue, go back in the logger, **select only the blocked items**, post them here as screenshot

**Comment by skinkie** [comment]
![image](https://user-images.githubusercontent.com/502394/149749743-c2ca6b6c-57c5-488f-b1ad-a06ca11fc2cc.png)

@mapx- is this what you requested?

**Comment by mapx-** [comment]
add & test

`@@||inbenta.io/prod/*/tracking/events$xhr,domain=knab.nl`

**Comment by skinkie** [comment]
Then we get; Access to XMLHttpRequest at 'https://api.inbenta.io/v1/auth' from origin 'https://persoonlijk.knab.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.inbenta.io/v1/auth:1

**Comment by mapx-** [comment]
provide logger screenshot again: **only blocked items**

![image](https://user-images.githubusercontent.com/10303732/149754263-68c71537-cdc3-4248-9b46-37045bdcd9f5.png)

**Comment by skinkie** [comment]
After doing the procedure again (but with a different tab) and the first rule applied, I don't have an issue any more.

**Comment by uBlock-user** [comment]
> Then we get; Access to XMLHttpRequest at 'https://api.inbenta.io/v1/auth' from origin 'https://persoonlijk.knab.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.inbenta.io/v1/auth:1

Site issue, set a proper CORS header.

**Comment by skinkie** [comment]
> > Then we get; Access to XMLHttpRequest at 'https://api.inbenta.io/v1/auth' from origin 'https://persoonlijk.knab.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> > api.inbenta.io/v1/auth:1
> 
> Site issue, set a proper CORS header.

Not the owner.

**Comment by mapx-** [comment]
well, you are saying it's ok now

@ryanbr

**Comment by skinkie** [comment]
> well, you are saying it's ok now

As a _user_ of both the site and ublock origin.

**Comment by ryanbr** [comment]
Login?
