### ISSUE TITLE
timesofindia.com: detection

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [uBlockOrigin/uAssets#11338]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.timesofindia.com/city/chennai/for-better-or-for-metaverse-couple-in-tamil-nadu-weds-in-vr/articleshow/88925935.cms`

### Category

detection

### Describe the issue

I opened a link shared with me and then the website started to not show content saying I'm using an adblocker and it detects unlock origin very well. Please give a solution for this issue asap.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20220117-060417_Firefox](https://user-images.githubusercontent.com/78001660/149684568-76fb1f8f-e738-45af-bacd-111ee3b01976.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 96
filterset (summary): 
  network: 80526
  cosmetic: 22146
  scriptlet: 16446
  html: 620
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30831-267, 7h.6m
    ublock-badware: 3728-1, 7h.5m
    ublock-privacy: 183-1, 3d.20h.35m
    ublock-abuse: 76-0, 3d.20h.34m
    ublock-unbreak: 1734-0, 3d.20h.33m
    adguard-mobile: 7083-173, 7h.8m
    easylist: 62917-24236, 3d.20h.32m
    easyprivacy: 26622-490, 3d.19h.57m
    urlhaus-1: 8198-0, 7h.4m
    plowe-0: 3684-2, 2d.22h.13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 354 ms (selfie)
popupPanel: 
  blocked: 26
```
</details>

**Comment by sudeepg95** [comment]
Can confirm issue for most pages in the website.
Tried adding ```timesofindia.com##script:inject(indiatimes.com.js)``` to custom filters, doesn't seem to work either. 
Any help would be appreciated. 
Thanks! 

Sample url: https://m.timesofindia.com/coronavirus

**Comment by sudeepg95** [comment]
Fix works beautifully. 
Thank you!

**Comment by uBlock-user** [comment]
> timesofindia.com##script:inject(indiatimes.com.js)

Invalid syntax, deprecated years ago!

**Comment by Midnightmadwalk-coder** [comment]
> > timesofindia.com##script:inject(indiatimes.com.js)
> 
> Invalid syntax, deprecated years ago!

Wait what just happened?

**Comment by gwarser** [comment]
@Midnightmadwalk-coder issue is fixed - update uBlock filters list.

**Comment by Midnightmadwalk-coder** [comment]
How to do that update on Firefox for Android?

**Comment by gwarser** [comment]
Go to [uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [Filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) -> click on the clock icon at the end of filter list name -> click on "Update now" on top.

Alternatively click on "Purge all caches" -> "Update now"
