### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#11341]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://work.ink/en/l/v/4znUMh`

### Describe the issue

Hard anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/17685483/149707916-8bfb4753-77f1-4b57-9949-7e797f2e7821.png)

### Notes

Related:
https://github.com/uBlockOrigin/uAssets/issues/7273#issuecomment-967775766

Even when the anti-adb warning doesn't appear, this message appears:
![image](https://user-images.githubusercontent.com/17685483/149708262-c3df36b7-f802-4e90-860f-331242a9b3ba.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79461
  cosmetic: 40521
  scriptlet: 16467
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63009-9, 23h.31m
    easyprivacy: 26626-17, 23h.31m
    plowe-0: 3682-816, 23h.31m
    ublock-abuse: 76-0, 23h.31m
    ublock-badware: 3724-67, 23h.31m
    ublock-filters: 30189-145, 23h.31m
    ublock-privacy: 190-3, 23h.31m
    ublock-unbreak: 1723-39, 23h.31m
    urlhaus-1: 8471-0, 23h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 130 ms (selfie)
```
</details>

**Comment by propagandism** [comment]
`work.ink` => search for a game => click on an item => wait => anti-adblock notice
