### ISSUE TITLE
skaitv.gr: breakage

### ISSUE THREAD

**Issue by JackBlack4** [uBlockOrigin/uAssets#11348]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.skaitv.gr/live`

### Category

breakage

### Describe the issue

It doesn't play the stream.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79702
  cosmetic: 41026
  scriptlet: 16458
  html: 0
listset (total-discarded, last updated): 
  default: 
    GRC-0: 1002-0, 23h.30m
    easylist: 62917-12, 4d.6h.22m
    easyprivacy: 26627-17, 12h.22m
    plowe-0: 3682-817, 12h.24m
    ublock-abuse: 76-0, 2h.10m
    ublock-badware: 3724-67, 8h.20m
    ublock-filters: 30159-145, 2h.9m
    ublock-privacy: 186-3, 4d.6h.25m
    ublock-unbreak: 1723-39, 1h.22m
    urlhaus-1: 8337-0, 12h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 26 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 395 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
add 
`@@||extreme-ip-lookup.com/json/$xhr,domain=skaitv.gr`

@ryan EP issue

**Comment by mapx-** [comment]
(tested using greek ip vpn)
