### ISSUE TITLE
[nsfw] bunkr.is: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#11346]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bunkr.is/a/uctg89XM`

### Category

ads

### Describe the issue

ads on the top

### Screenshot(s)

<details>
https://user-images.githubusercontent.com/81616288/149799302-1d19d840-8572-4b42-9c7a-ff0513c8ed8b.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 81530
  cosmetic: 43662
  scriptlet: 16419
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30734-37, 3h.21m
    ublock-badware: 3728-1, 3h.21m
    ublock-privacy: 187-0, 3h.21m
    ublock-abuse: 76-0, 3h.21m
    ublock-unbreak: 1693-0, 3h.21m
    easylist: 63067-593, 3h.21m
    easyprivacy: 26627-492, 3h.21m
    urlhaus-1: 8471-0, 3h.21m
    plowe-0: 3682-2, 3h.21m
    DEU-0: 5238-2, 3h.21m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1434 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`||i.pixl.is/*.gif$image,domain=bunkr.is`

@ryanbr

**Comment by i8cczshd** [comment]
still not fixed ...
