### ISSUE TITLE
juegosflash.dibujos.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1134]
URL(s) where the issue occurs

http://juegosflash.dibujos.net/habilidad/la-florista.html

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
no anti adb here, but needing this filter to play the game
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=juegosflash.dibujos.net`

@monzta @Khrin

**Comment by KiLL4FuNK** [comment]
you can not play
