### ISSUE TITLE
clockks.com: detection

### ISSUE THREAD

**Issue by deltlpha** [uBlockOrigin/uAssets#11342]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://clockks.com/lock/?utm_source=Google&utm_medium=Organic&utm_campaign=Search&e=1120439&h=wohsamrahslipakeht`

### Category

detection

### Describe the issue

This website detects adblocker and asks to disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-01-17 at 5 16 40 pm](https://user-images.githubusercontent.com/97869932/149717513-2a7b482b-3d2a-475f-ab72-a2a0e00d7977.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79494
  cosmetic: 40539
  scriptlet: 16463
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 17h.57m
  default: 
    easylist: 63047-9, 17h.57m
    easyprivacy: 26627-17, 17h.57m
    plowe-0: 3682-816, 17h.57m
    ublock-abuse: 76-0, 17h.57m
    ublock-badware: 3724-67, 17h.57m
    ublock-filters: 30175-148, 17h.57m
    ublock-privacy: 190-3, 17h.57m
    ublock-unbreak: 1723-39, 17h.57m
    urlhaus-1: 8415-0, 17h.57m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1086 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Can’t reproduce too the generic anti BAB filters works well for me

**Comment by mapx-** [comment]
@deltlpha disable all other extensions and test again
