### ISSUE TITLE
[nsfw] coinlegend.ltd: [unknown]

### ISSUE THREAD

**Issue by Sh4d0w-R00t** [uBlockOrigin/uAssets#11343]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.coinlegend.ltd/`

### Category

cryptocurrency trading

### Describe the issue

not safe to trade on this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79188
  cosmetic: 40519
  scriptlet: 16425
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30760-29, 1d.23h.25m
    ublock-badware: 3723-1, 1d.23h.24m
    ublock-privacy: 187-0, 1d.23h.23m
    ublock-abuse: 76-0, 1d.23h.22m
    ublock-unbreak: 1733-0, 1d.23h.20m
    easylist: 63006-583, 1d.23h.19m
    easyprivacy: 26626-481, 1d.3h.50m
    urlhaus-1: 8198-0, 16h.40m
    plowe-0: 3682-2, 1d.18h.44m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5908 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by monsterssniper** [comment]
fuck me emoboy hey emoboy

**Comment by uBlock-user** [comment]
> not safe to trade on this website

Why would that be ? Explain and elaborate on that.
