### ISSUE TITLE
aepos.ap.gov.in: ads

### ISSUE THREAD

**Issue by ravikumarjujare** [uBlockOrigin/uAssets#11355]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aepos.ap.gov.in/ePos/SRC_Trans_Int.jsp`

### Category

Banner

### Describe the issue

I used to remove banners (yellow background) for compacting UI of the page. Now it doesn't work anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 88
filterset (summary): 
  network: 78145
  cosmetic: 40536
  scriptlet: 16417
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30734-30, 1d.7h.31m
    ublock-badware: 3728-1, 1d.7h.30m
    ublock-privacy: 187-0, 1d.7h.29m
    ublock-abuse: 76-0, 1d.7h.28m
    ublock-unbreak: 1732-0, 1d.7h.27m
    easylist: 63046-586, 1d.7h.26m
    easyprivacy: 26627-480, 1d.7h.25m
    urlhaus-1: 7135-0, 9h.42m
    plowe-0: 3685-2, 9d.12h.40m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 639 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
> Firefox: 88 

You should update your FF (now version 96)

> Now it doesn't work anymore

What does not work ?

However, we cannot help, gov account required

**Comment by ravikumarjujare** [comment]
![before_removing_banner](https://user-images.githubusercontent.com/78495055/149927323-3b8c99f1-ee62-4439-a3bd-50a92c77d555.png)
![picking_banner_using_element_picker](https://user-images.githubusercontent.com/78495055/149927338-81b38acb-bf27-47b6-8950-4fefe38aa27e.png)
![after_removing_banner](https://user-images.githubusercontent.com/78495055/149927349-020a010e-1d04-4e66-bf77-3028e949b16a.png)

Thanks for responding so quickly. I appreciate how this work is being done voluntarily.

This website does not need login (at least for the part that is being used as public reports).

Due to lack of screen space while working with big reports, we used to remove the big yellow banner using "element picker mode". It used to create some rule internally (when we pick it). I had seen the rule, but don't remember the exact rule.

Recently (last two months), something seem to have changed. Either the website changed the syntax of it's html or the way javascript works OR the newer version of uBlock Origin has changed something internally while picking the element, we are not able to pick the banner anymore (I lean towards the former, that, something in the website has changed).

I don't want to trouble you to provide us with syntax of a rule for picking the banner. If that is the case, feel free to close this ticket. The gist is that we are not able to pick the banner anymore. Something has changed in last 2 months.

Thanks in advance.

**Comment by uBlock-user** [comment]
What do you want to block ? Take a picture and highlight it.

**Comment by mapx-** [comment]
working very well, try this filter:

`aepos.ap.gov.in##.row1.wrapper`

if you want to have right click enabled on page add also:

```
aepos.ap.gov.in##+js(ra, oncontextmenu)
aepos.ap.gov.in##+js(acis, $, contextmenu)
```

**Comment by uBlock-user** [comment]
> Recently (last two months), something seem to have changed. Either the website changed the syntax of it's html or the way javascript works OR the newer version of uBlock Origin has changed something internally while picking the element, we are not able to pick the banner anymore (I lean towards the former, that, something in the website has changed).

Check if cosmetic filtering is disabled, use the logger to investigate.

**Comment by ravikumarjujare** [comment]
Both code snippets worked perfectly.
Thank you very much.

**Comment by ravikumarjujare** [comment]
Feedback: Checked. Cosmetic filtering was not disabled.
