### ISSUE TITLE
tn.nova.cz: detection

### ISSUE THREAD

**Issue by uzivatel457** [uBlockOrigin/uAssets#11357]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tn.nova.cz/tnlive`

### Category

detection

### Describe the issue

video can not be played, ublock detected
"Video nelze přehrát, protože máte aktivní AdBlock."

their script of detection:  
function adBlockEnabledBodyTest() {
        return new Promise(resolve => {
            var AdStatus;
            var iframe = document.createElement('iframe');
            var randomNum = Math.floor(Math.random() * (10000 - 123 + 1)) + 123;
            var protocol = window.location.protocol;
            var host = window.location.host;

            iframe.src = "".concat(protocol, "//" + host + "/adblocker" + '/').concat(randomNum, "/ads.html");
            iframe.height = "1px";
            iframe.width = "1px";
            iframe.id = 'some-ad';

            function getRequest(iframe, success, error) {
                var xhr = new XMLHttpRequest();
                xhr.open("GET", iframe.src);

                xhr.onreadystatechange = function() {
                    if (xhr.readyState == 4) {
                        if (xhr.status == 200) {
                            success(xhr.responseText);
                        } else {
                            error(xhr, xhr.status);
                        }
                    }
                };
                xhr.send();
            }

            getRequest(iframe, function(response) {
                document.body.appendChild(iframe);
            }, function(xhr, status) {
                if (status === 0) {
                    document.body.appendChild(iframe);
                }
            });

            var promise = new Promise(function(resolve, reject) {
                setTimeout(function() {
                    var someAd = document.getElementById('some-ad');
                    if (someAd === null || someAd.style.display == "none" || someAd.style.display == "hidden" || someAd.style.visibility == "hidden" || someAd.offsetHeight === 0) {
                        AdStatus = true;
                    } else {
                        AdStatus = false;
                    }
                    return resolve(AdStatus);
                }, 1000);
            });

            promise.then(function(done) {
                return resolve(done);
            });
        });
    }

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78593
  cosmetic: 40107
  scriptlet: 16392
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-137, 1d.4h.45m
    ublock-badware: 3633-1, 1d.4h.44m
    ublock-privacy: 181-0, 1d.4h.43m
    ublock-abuse: 81-0, 1d.4h.42m
    ublock-unbreak: 1719-0, 1d.4h.41m
    easylist: 62254-99, 1d.4h.40m
    easyprivacy: 26549-28, 1d.4h.39m
    urlhaus-1: 8168-0, 4h.7m
    plowe-0: 3715-821, 1d.4h.46m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3762 ms
popupPanel: 
  blocked: 101
```
</details>

**Comment by uBlock-user** [comment]
Hid two placeholders and unbroke video player, no anti-adblock seen.

**Comment by Procyon-b** [comment]
I see the message "_Video nelze přehrát, protože máte aktivní AdBlock._" in the video player. But it's solved once I subscribe to the regional list "_CZE, SVK: EasyList Czech and Slovak_"
