### ISSUE TITLE
720pizle.vip: ads

### ISSUE THREAD

**Issue by cemalkz** [uBlockOrigin/uAssets#11356]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://720pizle.vip/izle/altyazi/eternals.html`
`https://sezonlukdizi1.com/`

### Category

ads

### Describe the issue

the site has all the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 95
filterset (summary): 
  network: 78592
  cosmetic: 40107
  scriptlet: 16392
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-137, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-0, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1719-0, never
    easylist: 62254-453, never
    easyprivacy: 26549-492, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-3, never
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 309 ms
popupPanel: 
  blocked: 8
```
</details>

**Comment by cemalkz** [comment]
![resim](https://user-images.githubusercontent.com/26414265/149908187-a11ef64e-0e28-44fb-b247-d89924a24395.png)

screenshot

**Comment by okiehsch** [comment]
It's fixed in the regional list, enable `AdGuard Turkish`.
![image](https://user-images.githubusercontent.com/16838044/149909586-b4495c39-7d25-49ad-8b27-ec21bc997f66.png)

**Comment by okiehsch** [comment]
`https://sezonlukdizi1.com` has a popup.

**Comment by okiehsch** [comment]
@AdamWr possible fix.
````
sezonlukdizi1.com##+js(nowoif)
||acxdyn.com^$3p
````

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
