### ISSUE TITLE
zive.cz: detection

### ISSUE THREAD

**Issue by uzivatel457** [uBlockOrigin/uAssets#11358]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zive.cz/`

### Category

detection

### Describe the issue

ublock detected  >  pop up about disable ublock
script
const gd = function(){
	var s = ["r","e","k","l","a","m"];
	var modal = String(".sbAS3sCQcE {position:fixed;z-index:20000000;align-items:center;height:100%;left:0;overflow-x:auto;top:0;display:flex;justify-content:center;width:100%;background: rgba(0,0,0,0.75)!important;}.bK8JSIaOEz {height:100%;left:0;position:fixed;top:0;width:100%;z-index:-1;}.OLUSpZ6xrZ {width:700px;background:#fff;border:none;border-radius:0.5em;}.OLUSpZ6xrZ > div {padding:1rem 1.5rem;}.OLUSpZ6xrZ p {font-size: 1.1em}.iA0vxvcJe8 {display:block;height:33px;width:62px;background:transparent url(https://www.zive.cz/_rev2015/img/logo.png) no-repeat 50% 50%;background-size:contain;margin:8px auto 16px;}.KnhVejYgQs {font-size:21px;line-height:30px;font-weight:400;margin-bottom:15px;}.KnhVejYgQs b {font-weight:700;}.jrj0EKHDfL {padding:10px 30px;font-size:16px;font-weight:700;text-decoration:none;color:#fff!important;background:#d00000;margin:15px 10px 10px;display:inline-block;border-radius:3px;}.QTQlSuafAx {background:#424242}.ILdhewo5wZ {background:#e8e8e8;color:#868686!important;}.jN7Iik0tsR {display:inline-block}[--]<div class='fs-os sbAS3sCQcE'><div class='bK8JSIaOEz'></div><div class='OLUSpZ6xrZ'><div><div class='iA0vxvcJe8'><span></span></div><div class='KnhVejYgQs'>Jsme rádi, že čtete Živě. Abyste měli co číst, musíme články napsat, a s tím je dost práce. <b>Budeme rádi, když naši práci oceníte a&nbsp;nastavíte pro tento web výjimku v adblocku</b>. <br/><br/>Nebo si objednejte <b>předplatné Živě bez 00</b> a&nbsp;s&nbsp;prémiovými články navíc.</div><div class='jN7Iik0tsR'><a href='https://www.zive.cz/clanky/jak-na-zive-vypnout-blokovani-00/sc-3-a-204317/default.aspx' title='Povolit 00u' class='jrj0EKHDfL QTQlSuafAx'>Povolit 00u</a><a href='javascript:void(0)' onclick='$(\".sbAS3sCQcE\").hide()' title='Zatím zavřít' class='jrj0EKHDfL ILdhewo5wZ'>Zatím zavřít</a><a href='https://www.zive.cz/premium/sc-1628/?fromblock' title='Živě bez 00' class='jrj0EKHDfL'>Živě bez 00</a><p>Jestli už máte předplatné, <strong><a style='color:red' href='https://klub.ikiosek.cz/Login.aspx?backSite=www.zive.cz&systemid=zive&servicename=Živě&redirect=https%3a%2f%2fwww.zive.cz%2findex.aspx%3frefsub%3d1' title='přihlaste se'>přihlaste se</a></strong></p></div></div></div></div>").split("[--]");

	if( !$("body > .r" + "k" + "l" + "m").is(":visible") || window.zl != "1" || window.gt != "1" ) {
		if( ( $(".ar-inquiry-holder").length>0 || document.location.pathname=="/" || document.location.pathname=="/default.aspx" ) && String($.cookie('brbq'))!="1" ) {
			$('head').append('<style type="text/css">' + modal[0] + '</style>');
			var o = $(modal[1].replace(/00/igm, s.join("")));
			var f =["Klik Povolit 00u", "Klik Zatím zavřít", "Klik Živě bez 00"];
			o.insertAfter($("form:last"));
			o.find("div > a").each(function(index, item){
				$(this).on("click", function(){
					dataLayer.push({'event':'ga.event','eCategory':"Navigace",'eAction':"Výzva při blokování " + s.join(""),'eLabel':f[index].replace("00", s.join("")),'eValue': 1});
					$.cookie('brbq', '1', { 'expires': 1, 'path': '/', 'domain': 'zive.cz' });
				});
				if(index==1){
					var bf = new Array("none", "left", "right");
					$(this).css({"float":bf[Math.floor(Math.random() * bf.length)]});
				}	
			});
			dataLayer.push({'event':'ga.event','eCategory':"Navigace",'eAction':"Výzva při blokování " + s.join(""),'eLabel':"Zobrazení",'eValue': 1});
		}
	}else  {
		if( String($.cookie('brbq')) == '1' ){
			if( $(".ar-inquiry-holder").length>0 || document.location.pathname=="/" || document.location.pathname=="/default.aspx" ) {
		 		$.cookie('brbq', null);
				dataLayer.push({'event':'ga.event','eCategory':"Navigace",'eAction':"Výzva při blokování " + s.join(""),'eLabel':"WhiteList",'eValue': 1});
			}
		}
	}
};
document.addEventListener("DOMContentLoaded", function(event) { 
  gd();
});

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78593
  cosmetic: 40107
  scriptlet: 16392
  html: 612
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30635-137, 1d.4h.52m
    ublock-badware: 3633-1, 1d.4h.51m
    ublock-privacy: 181-0, 1d.4h.50m
    ublock-abuse: 81-0, 1d.4h.49m
    ublock-unbreak: 1719-0, 1d.4h.48m
    easylist: 62254-99, 1d.4h.47m
    easyprivacy: 26549-28, 1d.4h.46m
    urlhaus-1: 8168-0, 4h.13m
    plowe-0: 3715-821, 1d.4h.53m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3762 ms
popupPanel: 
  blocked: 23
```
</details>

**Comment by uBlock-user** [comment]
Subscribe to regional list.
