### ISSUE TITLE
einthusan.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by kickstand03** [uBlockOrigin/uAssets#11351]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://einthusan.tv/`

### Describe the issue

`https://einthusan.tv/movie/browse/?lang=hindi` redirects to `https://einthusan.tv/adblocker/`
(Anti-Adblock)

### Screenshot(s)

![Untitled](https://user-images.githubusercontent.com/73573729/149851712-af5d59db-508c-45fc-8b94-21380b731915.png)

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Firefox Browser 96.0.1 (64-bit)

### Settings

```
@@||ib.adnxs.com^$xhr
@@||imasdk.googleapis.com^$script,domain=einthusan.ca|einthusan.com|einthusan.tv
@@||einthusan.tv^$generichide
@@||einthusan.ca^$generichide
@@||ads.adaptv.advertising.com^$xmlhttprequest,domain=imasdk.googleapis.com
@@||video-ads.rubiconproject.com/$xmlhttprequest,domain=imasdk.googleapis.com
@@||einthusan.tv/prebid.js
@@||einthusan.tv/prebid.js$script,first-part
@@einthusan*$xmlhttprequest,domain=imasdk.googleapis.com
! 10/28/2020 einthusan.tv
! https://github.com/uBlockOrigin/uAssets/issues/8099
einthusan.*##+js(nostif, AdBlocker, 1000)
@@||einthusan.*/prebid.js$script,1p
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=einthusan.*
@@||googletagmanager.com/gtm.js$xhr,domain=einthusan.tv
@@||springserve.com/vast/*einthusan$xhr,domain=imasdk.googleapis.com
einthusan.*##.adspace-lb
einthusan.*##.adspace-lr
@@||d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js$script,domain=einthusan.tv
```

### Notes

Just happened recently. Was working fine for quite some time. Also tried purging and updating. Same result.

**Comment by gorhill** [comment]
Please post the troubleshooting information at the bottom of the Support pane.

**Comment by kickstand03** [comment]
Tried with clear "my filters", still same result. 
Tried by disabling all other extensions except uBlockOrigin, still same result. 
Going to https://einthusan.tv/intro/ does NOT cause the Anti-Adblock. But clicking on anything to go further does cause the Anti-Adblock again.

**Comment by kickstand03** [comment]
Can you send me your settings and custom rules for the site then?

**Comment by mapx-** [comment]
```
uBO is the only extension
uBO with default lists/settings
```

**Comment by gorhill** [comment]
Closing due inability to reproduce and unwillingness of OP to disclose troubleshooting information.

**Comment by kickstand03** [comment]
Thanks for closing I fixed it myself.

**Comment by horus-t** [comment]
@kickstand03 Im having the exact problem it had stopped working for me too. How did you fix this?

**Comment by kickstand03** [comment]
> @kickstand03 Im having the exact problem it had stopped working for me too. How did you fix this?

 @horus-t Send me an email here: kickstand03@live.com

**Comment by mapx-** [comment]
update uBO lists
