### ISSUE TITLE
n-tv.de: breakage

### ISSUE THREAD

**Issue by OlsenT** [uBlockOrigin/uAssets#11368]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.n-tv.de/mediathek/videos/wetter/Milder-Mittwoch-treibt-Regenwolken-durch-den-Norden-article23066975.html`

### Category

breakage

### Describe the issue

no videos are playing at ntv.de at all.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 79659
  cosmetic: 43523
  scriptlet: 16427
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5192-0, 8d.1h.58m
    easylist: 62852-15, 8d.2h.5m
    easyprivacy: 26616-28, 8d.2h.4m
    plowe-0: 3682-818, 16d.3h.2m
    ublock-abuse: 76-0, 8d.2h.3m
    ublock-badware: 3648-67, 8d.2h.2m
    ublock-filters: 30084-152, 8d.2h.1m
    ublock-privacy: 186-3, 8d.2h
    ublock-unbreak: 1715-40, 8d.1h.59m
    urlhaus-1: 6826-0, 8d.1h.57m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 390 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by mapx-** [comment]
```
@@||bilder-a.akamaihd.net/ip/js/ipdvdc/ipdvdc.min.js$script,domain=n-tv.de
@@||technical-service.net^$xhr,domain=n-tv.de
```

@ryanbr

**Comment by OlsenT** [comment]
> ```
> @@||bilder-a.akamaihd.net/ip/js/ipdvdc/ipdvdc.min.js$script,domain=n-tv.de
> @@||technical-service.net^$xhr,domain=n-tv.de
> ```
> 
> @ryanbr

works, thx !!

**Comment by Martin511** [comment]
> > ```
> > @@||bilder-a.akamaihd.net/ip/js/ipdvdc/ipdvdc.min.js$script,domain=n-tv.de
> > @@||technical-service.net^$xhr,domain=n-tv.de
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @ryanbr
> 
> works, thx !!

Hello, where do I have to put in the two lines? 
I don´t understand how to make it work. Is there any documentation?

**Comment by Martin511** [comment]
Thank you, I did this but without success.
There are still no videos at all on n-tv.de.
I also searched in the wiki but did not find any solution...

**Comment by okiehsch** [comment]
What's your setup?
It works fine on my end using chromium or firefox, example link
`https://www.n-tv.de/mediathek/videos/wetter/Milder-Mittwoch-treibt-Regenwolken-durch-den-Norden-article23066975.html`
the video plays without issue for me.

**Comment by mapx-** [comment]
works fine for me too, example link:
`https://www.n-tv.de/mediathek/magazine/fruehstart/SPD-Aussenpolitiker-Aus-fuer-Nord-Stream-2-im-Kriegsfall-article23114752.html`

**Comment by Martin511** [comment]
Ok, unfortunately not in my case...
Do I have to fill in these two lines somewhere?
@@||bilder-a.akamaihd.net/ip/js/ipdvdc/ipdvdc.min.js$script,domain=n-tv.de
@@||technical-service.net^$xhr,domain=n-tv.de

**Comment by uBlock-user** [comment]
Test on default lists/settings + all other extensions disabled.

**Comment by uBlock-user** [comment]
Reset uBO to default settings via Settings pane.

**Comment by Martin511** [comment]
Yes, I did.
Still the same...

**Comment by uBlock-user** [comment]
You need to start investigating why it's not working for you.

**Comment by Martin511** [comment]
Sorry, I forgot to update the lists that need updating after setting back to default.
This was the reason.
Now it works.
Thank you for helping me.

Regards
Martin

**Comment by mapx-** [comment]
@Martin511 what video did you test ?

**Comment by Martin511** [comment]
The live stream and all other videos.
