### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by SummerSinger** [uBlockOrigin/uAssets#11365]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/chat/u/0/`

### Category

breakage

### Describe the issue

Hello,

The main pane in Google Chat does not seem to load. i.e. I'm able to see the contacts and chat groups panel on the left of the page, but the central pane where a chat  happens and chat history is usually displayed remains blank. All other functionality on the page appears to work, *except* for the settings button, which would also typically load in the central pane. This is why I believe there is a problem where the contents of the central pane is being blocked.

Firefox 96.0.1 (64-bit)
UB 1.40.8

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78114
  cosmetic: 40536
  scriptlet: 16420
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30740-30, 23h.46m
    ublock-badware: 3728-1, 23h.45m
    ublock-privacy: 187-0, 23h.43m
    ublock-abuse: 76-0, 23h.42m
    ublock-unbreak: 1693-0, 23h.41m
    easylist: 63067-587, 23h.40m
    easyprivacy: 26627-480, 23h.39m
    urlhaus-1: 7135-0, 23h.38m
    plowe-0: 3685-2, 8d.17h.28m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2052 ms (selfie)
popupPanel: 
  blocked: 28
```
</details>

**Comment by mapx-** [comment]
I get normally the central chat space (+ talking history), the right settings button is working too

Disable all other addons and test again
