### ISSUE TITLE
GoComics.com

### ISSUE THREAD

**Issue by TheMegamind** [uBlockOrigin/uAssets#1136]
Replace the bracketed [...] placeholders with your own information.

### URL

`http://www.gocomics.com/luann?ct=v&cti=16xxxxx` (or similar individual comic page). 

I have masked the last five digits as it is an account number reference.  As noted below, I see the behavior only when logged into my free account and begin browsing my favorite comics.  

### Describe the issue

Issue occurs when you are signed into a free (non-premium account) and start browsing comics.  It does not occur on every comic or page.  The pop-up below (or another variation of it) appears frequently but semi-randomly while browsing. 

Occurs on both Chrome & Firefox 

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
![gocomics 1](https://user-images.githubusercontent.com/12296628/34445844-5cee56de-ec8b-11e7-86fc-822e173ee03a.jpg)
![gocomics 2](https://user-images.githubusercontent.com/12296628/34445845-5d09531c-ec8b-11e7-96f7-d0972e8b4ef2.png)

### Versions

- Browser/version: Firefox 57.0.3, Chrome 63.0.3239.84
- uBlock Origin version: v1.14.22

### Settings

- No changes 

### Notes

None

**Comment by okiehsch** [comment]
I do not have an account, but the site uses sourcepoint, so does 
`gocomics.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`
work for you?

**Comment by TheMegamind** [comment]
Possibly, but adding that filter to uBlock also breaks the site by removing the blue banner (directly above the pop-ups) that allows users to navigate quickly through their chosen comics.

**Comment by okiehsch** [comment]
How do I get that blue banner, I am now a proud free (non-premium account) member and added a bunch of comics to my account, but I do not see any banner.

![unnt](https://user-images.githubusercontent.com/16838044/34446616-d31dfef8-ecdc-11e7-99c7-0b8228902262.JPG)

I obviously have **not** added my proposed filter.

**Comment by TheMegamind** [comment]
When you sign in click on My Comics, then Comics I Follow, then select the first one on your list.  The blue navigation should appear directly above the comic.  My screen looks like yours only when the filter you suggested is enabled.

**Comment by okiehsch** [comment]
Thanks, now I see the banner.

**Comment by okiehsch** [comment]
Quite tricky, I don't see how to disable the detection script without breaking that banner, anyway

````
@@||gocomics.com^$generichide
gocomics.com##.ad-leaderboard-container
`````
works on my end.

**Comment by TheMegamind** [comment]
Seems to work here as well, but I'll keep an eye on it.  Thanks!!
