### ISSUE TITLE
Werbung wird eingeblendet

### ISSUE THREAD

**Issue by Mungshai** [uBlockOrigin/uAssets#11366]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

lablue.de

### Describe the issue

All advertising will be displayed 

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Firefox 96.0.1 (64-Bit)

### Settings

no Changes

**Comment by JobcenterTycoon** [comment]
Muss man sich da anmelden um die Werbung zu sehen? ich sehe keine

**Comment by okiehsch** [comment]
> Muss man sich da anmelden um die Werbung zu sehen?

Probably.

**Comment by JobcenterTycoon** [comment]
Ok i can see ads with a account wait

its ad reinsertion `@@||lablue.de^$ghide` works

**Comment by okiehsch** [comment]
Any blank placeholders caused by the `ghide` filter?

**Comment by JobcenterTycoon** [comment]
Im not see any

**Comment by okiehsch** [comment]
Ok, thx.

**Comment by Mungshai** [comment]
Ich bin dann dort angemeldet, ja, dann sehe ich oben, rechts und in der
mitte drin werbung.

Am Di., 18. Jan. 2022 um 20:12 Uhr schrieb okiehsch <
***@***.***>:
