### ISSUE TITLE
olx.com.lb: breakage

### ISSUE THREAD

**Issue by moehoss123** [uBlockOrigin/uAssets#11367]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.olx.com.lb/en/`

### Category

breakage

### Describe the issue

clicking on a category, then clicking on a subcategory (one of the blue links) on the website does nothing when ublock is turned on. works fine when ublock is off.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78065
  cosmetic: 40551
  scriptlet: 16469
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63125-9, 25m
    easyprivacy: 26633-17, 24m
    plowe-0: 3682-816, 23m
    ublock-abuse: 76-0, 21m
    ublock-badware: 3724-67, 19m
    ublock-filters: 30181-149, 18m
    ublock-privacy: 190-3, 17m
    ublock-unbreak: 1682-39, 16m
    urlhaus-1: 7040-0, 15m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 540 ms
popupPanel: 
  blocked: 27
```
</details>

**Comment by mapx-** [comment]
add

`@@||sdk-01.moengage.com^$xhr,domain=olx.com.lb`

@ryanbr
