### ISSUE TITLE
fangraphs.com: detection

### ISSUE THREAD

**Issue by cyb3rguy1776** [uBlockOrigin/uAssets#11371]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fangraphs.com/`

### Category

detection

### Describe the issue

When using the website, the following pop-up appears on every page, covering the site:

Support FanGraphs
Become a Member
The reason you're seeing our Membership ask each time you navigate to a new page is because you are using an ad blocker. FanGraphs isn't free to operate and we hope you won't take us for granted.
Please consider becoming a FanGraphs Member. All the great work that you've come to rely on is made possible by Member support, including analysis, stats, projections, RosterResource, prospect coverage and podcasts.
Membership starts at $0.07 a day. ($0.16 for Ad Free)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 78160
  cosmetic: 40531
  scriptlet: 16462
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63047-9, 2d.10h.40m
    easyprivacy: 26627-17, 2d.10h.38m
    plowe-0: 3682-816, 58m
    ublock-abuse: 76-0, 2d.10h.36m
    ublock-badware: 3719-67, 3d.6h.4m
    ublock-filters: 30252-148, 3d.6h.2m
    ublock-privacy: 200-3, 3d.6h
    ublock-unbreak: 1750-39, 3d.5h.58m
    urlhaus-1: 7040-0, 56m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 826
  launchFromSelfie: true
popupPanel: 
  blocked: 3
  no-large-media: true
  no-popups: true
```
</details>

**Comment by Procyon-b** [comment]
I can reproduce your problem. Try these filters:
```
fangraphs.com##+js(set,ezstandalone.enabled,true)
fangraphs.com###ra-membership-push-top
```
One to prevent the dialog, and the other to hide the text message at the top of the page.

**Comment by okiehsch** [comment]
> hide the text message at the top of the page.

I  can't reproduce that part, I can reproduce the popup.

**Comment by Procyon-b** [comment]
@okiehsch 
At the top of the articles I see this: (hidden by the 2nd filter)
 

![fangraphs-msg](https://user-images.githubusercontent.com/40043075/150187778-7783a197-50f0-41c1-afa8-9499a8f8e442.png)

**Comment by okiehsch** [comment]
I can reproduce, but we don't block that, it is independent of any adblock usage, every visitor will see that.

**Comment by Procyon-b** [comment]
I was mainly replying to OP. I agree with you that everything can't be included in the lists.

**Comment by uBlock-user** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/11371#issuecomment-1016725628

Annoyance, should go in any third-party annoyances list.
