### ISSUE TITLE
webkinznewz.ganzworld.com

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#11374]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://webkinznewz.ganzworld.com/announcements/webkinz-desktop-app-is-available-now/`

### Describe the issue

Three placeholders, the topmost of them with a very large border.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/150055344-f79ad7da-f072-414e-be6b-bbed71dc8bf2.png)

### uBlock Origin version

1.40.9b1

### Browser name and version

Vivaldi 5.0.2497.38 x64

### Settings

Stock settings, was reset to default settings.

### Notes

I propose:
```
||webkinznewz.ganzworld.com/wp-content/themes/wkn/images/bg-leaderboard-ad.png^$image
webkinznewz.ganzworld.com###sidebar-area li[id^=text-]
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by DandelionSprout** [comment]
I know that both AdGuard Filters and EasyList (especially the former) have had large backlogs recently, so I presumed it'd go faster to report things to uAssets instead. 😅
