### ISSUE TITLE
gumtree.com.au: breakage

### ISSUE THREAD

**Issue by ianthedoyle** [uBlockOrigin/uAssets#11372]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gumtree.com.au/`

### Category

breakage

### Describe the issue

The search bar disappears when navigating away from the home page. See screenshots.

Note this is a *very* hevily trafficked site in Australia and there are *a lot* of advertisements.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1280" alt="Screen Shot 2022-01-19 at 12 57 38 pm" src="https://user-images.githubusercontent.com/12164494/150049265-296488d0-31a1-481f-a9a9-be2d1d0bccdd.png">
<img width="1280" alt="Screen Shot 2022-01-19 at 12 57 23 pm" src="https://user-images.githubusercontent.com/12164494/150049279-1b9e46e5-bc9d-4f93-9074-905980052047.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78363
  cosmetic: 40541
  scriptlet: 16424
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30743-29, 17h.5m
    ublock-badware: 3728-1, 17h.4m
    ublock-privacy: 187-0, 17h.3m
    ublock-abuse: 76-0, 17h.1m
    ublock-unbreak: 1694-0, 17h
    easylist: 63105-588, 16h.59m
    easyprivacy: 26632-481, 16h.58m
    urlhaus-1: 7346-0, 16h.57m
    plowe-0: 3684-2, 6d.2h
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 138 ms (selfie)
popupPanel: 
  blocked: 15
```
</details>

**Comment by mapx-** [comment]
test

`gumtree.com.au#@#.header--is-new-sticky-behaviour`

@ryanbr
