### ISSUE TITLE
A few issues with known solution

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#1137]
Here are a few rules, all tested on latest Chrome + Nano on default. 
I won't use the template this time since it'll be way too long and doesn't really help. The comment before each rule gives enough info. 

```
# https://github.com/NanoAdblocker/NanoFilters/issues/6
@@||anime-loads.org^$generichide

# Anti-adblock, test: https://kissanime.co/Anime/Just-Because-.85121/Episode-012?id=141742
@@||kissanime.co/js/ads.js$script,first-party

# https://github.com/jspenguin2017/uBlockProtector/issues/776
liquipedia.net##script:inject(abort-on-property-read.js, adonis)

# https://github.com/reek/anti-adblock-killer/issues/3825
globalrph.com##script:inject(bab-defuser.js)

# https://github.com/jspenguin2017/uBlockProtector/issues/742
@@||egarwolin.pl/static/js/ads.js$script,first-party

# https://www.reddit.com/r/uBlockOrigin/comments/7imqbx/firefox_quantum_working_antiadblockkiller/
libgen.io##script:inject(setTimeout-defuser.js, ad blocking)

# https://github.com/jspenguin2017/uBlockProtector/issues/755
onlinemschool.com##script:inject(abort-on-property-read.js, oms.ads_detect)
onlinemschool.com###oms_left_block

# https://github.com/jspenguin2017/uBlockProtector/issues/769
ilgeniodellostreaming.org###playerads
```

**Comment by okiehsch** [comment]
- egarwolin.pl is fixed in `POL: polskie filtry do Adblocka i uBlocka`, which is part of the default setup for polish users.

- `ilgeniodellostreaming.org###playerads` is already part of uBlock filters.

- `libgen.io` is just an annoyance as far as I can see, so I added the filter to `uBlock-annoyances`

**Comment by jspenguin2017** [comment]
The fix for `egarwolin.pl` blocks an element with random ID, I don't think it'll last.

**Comment by okiehsch** [comment]
24 days and couning :). https://github.com/MajkiIT/polish-ads-filter/issues/4765
