### ISSUE TITLE
https://drivelinks.me/ or https://noticiascripto.site/ anti-adblock issue

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#11378]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

1.`https://www.peliculasgd.net/raya-ultimo-dragon-2021-mx-bdremux-2160p-4k-latino-googledrive/ `
when i copy the spesific link it forwards to google.com. Click to Enlaces Públicos button that forwards to this site:
2.`https://drivelinks.me/` than you click "haz clic aqui" button, this forwards you to this cancer site: 
3.`https://noticiascripto.site/`

### Describe the issue

If you go to the first link and select public link (Enlaces Públicos) it forwards to this site: `https://drivelinks.me/` this site wants you to go to this site "noticiascripto.site" and wants you make a spesific google search, click the first result, wait for 30 sec, in the end you get the link at"`https://drivelinks.me/`" tab . When using Adguard DNS(what i normaly use) this site is not letting you to get what you want. I switched to Yandex DNS, disabled uBo in this condition everything works well. I have the Spa/Por, fckfckadblock filters enabled doesn't work unfortunately. Obviously this is so annoying. I don't know if this could be fixed.

### uBlock Origin version

1.40.8

### Browser name and version

Google Chrome v97.0.4692.71 x64

### Settings

Added fckfckadblock filter
Enabled Turkish,Spanish,Portuguise regional filters
Enabled uB and Adguard Annoyances filters

**Comment by Yuki2718** [comment]
Ha, missed the same issue was open.

**Comment by garry-ut99** [comment]
(no AA for me with `ghide` off) Ad placeholders caused by `ghide` from "uBlock Filters": main page: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218262847-10bb71dd-ce6e-4d2f-a440-908828143b8c.png) subpage: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218262944-c526669c-0b6e-4458-a5ff-7e9b01886deb.png) (subpage: `https://noticiascripto.site/las-criptomonedas-digitales-la-razon-de-ser-explicada-en-conceptos-basicos/` )
