### ISSUE TITLE
shazoo.ru: breakage

### ISSUE THREAD

**Issue by InqWhiteCrow** [uBlockOrigin/uAssets#11377]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shazoo.ru/`

### Category

breakage

### Describe the issue

A site with an uBlock on ultrawide monitors cuts colors. White stripes appear on the sides of the site. If you disable the uBlock - everything is OK

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 96346
  cosmetic: 61534
  scriptlet: 18038
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40798-9, 17h.1m
    easylist: 63006-27, 3d.12h.27m
    easyprivacy: 26626-113, 3d.12h.26m
    plowe-0: 3685-822, 12d.17h.56m
    ublock-abuse: 76-1, 3d.12h.25m
    ublock-badware: 3724-67, 3d.12h.24m
    ublock-filters: 30190-177, 3d.12h.23m
    ublock-privacy: 190-3, 3d.12h.22m
    ublock-unbreak: 1722-39, 3d.12h.21m
    urlhaus-1: 7346-0, 21h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 414 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
@InqWhiteCrow 
It appears from your configuration that you have not [updated the filters](https://forums.lanik.us/viewtopic.php?f=102&t=22786).
