### ISSUE TITLE
sourceforge.net

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#11373]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sourceforge.net/projects/extremetuxracer/files/releases/0.8.1/`

### Describe the issue

Ads disguised as *"Other Useful Business Software"*. Despite that section's header title, the ads go out to external websites, and not to other `Sourceforge` projects as one could've mistakenly expected.

### Screenshot(s)

https://user-images.githubusercontent.com/22780683/150054143-e86c3763-cc59-4727-81fd-885d57b225ee.png

### uBlock Origin version

1.40.9b1

### Browser name and version

Vivaldi 5.0.2497.38 x64

### Settings

Stock settings, was reset to default settings.

### Notes

I propose `sourceforge.net##.project-body > section[id]`

**Comment by Daxy7** [comment]
@mapx- ADs in URLs
```
https://sourceforge.net/projects/extremetuxracer/postdownload
https://sourceforge.net/projects/extremetuxracer/files/latest/download
```
```
! invalid
sourceforge.net#@#.project-body > section[id]
! 
sourceforge.net###mirror
sourceforge.net###nels
sourceforge.net##.sterling
```
