### ISSUE TITLE
useast-www.securly.com: detection

### ISSUE THREAD

**Issue by nm44910** [uBlockOrigin/uAssets#11381]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://useast-www.securly.com/blocked?reason=domainblockedforuser&categoryid=4096&policyid=5&i2n=3984465837&url=ZWNvc2lhLm9yZy8=&ssl=true`

### Category

detection

### Describe the issue

why is it blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78585
  cosmetic: 40106
  scriptlet: 16431
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62254-462, never
    easyprivacy: 26549-483, never
    plowe-0: 3715-3, never
    ublock-abuse: 81-0, never
    ublock-badware: 3629-1, never
    ublock-filters: 30064-137, never
    ublock-privacy: 184-0, never
    ublock-unbreak: 1708-0, never
    urlhaus-1: 8168-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3085 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by uBlock-user** [comment]
> why is it blocked

What is blocked ?

**Comment by mapx-** [comment]
if you go with `https://useast-www.securly.com` an account is required

**Comment by gwarser** [comment]
`ecosia.org/` is encoded in query. Works fine here.

**Comment by uBlock-user** [comment]
> securly.com/blocked?reason=domainblockedforuser

Sounds like website itself is blocking the url

**Comment by uBlock-user** [comment]
https://www.securly.com/filter
