### ISSUE TITLE
Problem with the yandex.mail website 

### ISSUE THREAD

**Issue by Prono76** [uBlockOrigin/uAssets#11389]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://mail.yandex.ru/?uid=22287768#inbox
![ScreenShot_20220119212403](https://user-images.githubusercontent.com/98077108/150284192-2701c8e9-fade-4e8f-80ed-8c1d44408e4a.png)

### Describe the issue

When activating the extension in the yandex browser, when visiting the yandex.mail page, the indication of the "previous message" button disappears, while the "next" button remains active.
![ScreenShot_20220119212403](https://user-images.githubusercontent.com/98077108/150284219-3be1bfe1-cf44-4d51-be71-92c23bf8f9bc.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 97150
  cosmetic: 62091
  scriptlet: 18036
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40807-9, 1d.15h.45m
    easylist: 63049-27, 2d.21h.3m
    easyprivacy: 26627-113, 2d.16h.59m
    plowe-0: 3684-821, 7d.20h.14m
    ublock-abuse: 76-1, 2d.21h.4m
    ublock-badware: 3724-67, 1h.8m
    ublock-filters: 30181-180, 2d.21h.5m
    ublock-privacy: 190-3, 2d.21h.2m
    ublock-unbreak: 1683-39, 21h.28m
    urlhaus-1: 8152-0, 1h.7m
filterset (user): [array of 577 redacted]
trustedset: 
  added: [array of 45 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2689 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@Prono76 
Please take a [screenshot of the logger](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=8#1).

**Comment by Prono76** [comment]
> @Prono76 Пожалуйста, сделайте [снимок экрана регистратора](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=8#1).

![лог ублока 1](https://user-images.githubusercontent.com/98077108/150293689-0591c39f-f97d-44f7-a530-a786edea92ee.jpg)

**Comment by dimisa-RUAdList** [comment]
Judging by the screenshot of the logger, you yourself have hidden these elements. Go to the uBO control panel, go to the "My filters" tab and delete the rules for Yandex there.

Yandex browser is a problematic browser. Read more [here](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=13#1) (last paragraph). Required [uBlock Origin development build](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii). Will also need to subscribe to the Counters filter: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

Direct link to subscribe to [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)
