### ISSUE TITLE
infojobs.com.br: detection

### ISSUE THREAD

**Issue by flaviofujita** [uBlockOrigin/uAssets#11384]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.infojobs.com.br`

### Category

detection

### Describe the issue

Blocker is detected in the entire website. Redirects to: https://www.infojobs.com.br/nopublicity.aspx

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79090
  cosmetic: 40533
  scriptlet: 16456
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 63044-9, 2d.21h.9m
    easyprivacy: 26627-17, 2d.21h.8m
    plowe-0: 3682-816, 2d.17h.1m
    ublock-abuse: 76-0, 2d.21h.10m
    ublock-badware: 3724-67, 2d.21h.4m
    ublock-filters: 30158-148, 2d.21h.6m
    ublock-privacy: 190-3, 2d.21h.3m
    ublock-unbreak: 1722-39, 2d.21h.5m
    urlhaus-1: 8093-0, 30m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 540 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by uBlock-user** [comment]
Subscribe to regional list.
