### ISSUE TITLE
northjersey.com: nuisance (All USAtoday sites)

### ISSUE THREAD

**Issue by Snuffy2** [uBlockOrigin/uAssets#11396]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.northjersey.com/story/news/coronavirus/2022/01/20/murphy-nj-mask-mandate-lift-covid-numbers-fall/6591186001/`

### Category

nuisance

### Describe the issue

On northjersey.com and various other usatoday.com sites, there is a Subscribe pop-up. It generally appears when you move the mouse to the top of the screen after reading an article. It doesn't show on every article or every time.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SNAG-0000](https://user-images.githubusercontent.com/6526076/150403945-a1b09012-2b83-4cf9-a9b9-206b7f747c02.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 92
filterset (summary): 
  network: 86562
  cosmetic: 96607
  scriptlet: 19222
  html: 624
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 0-0, never
    fanboy-annoyance: 60029-353, 10m
    ublock-annoyances: 4360-7, 10m
  default: 
    ublock-filters: 30771-31, 4h.49m
    ublock-badware: 3728-1, 4h.48m
    ublock-privacy: 187-0, 4h.47m
    ublock-abuse: 76-0, 4h.46m
    ublock-unbreak: 1698-0, 4h.45m
    easylist: 63179-589, 4h.44m
    easyprivacy: 26642-490, 4h.43m
    urlhaus-1: 8099-0, 4h.42m
    plowe-0: 3682-2, 4h.54m
filterset (user): [array of 1072 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3498 ms (selfie)
popupPanel: 
  blocked: 39
```
</details>

**Comment by Snuffy2** [comment]
https://github.com/uBlockOrigin/uAssets/issues/10881 looks similar

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Unable to reproduce.

**Comment by Snuffy2** [comment]
What can I do to provide more info? It is occurring routinely for me.

**Comment by mapx-** [comment]
Use element picker and see what filters are suggested (post them here)

**Comment by Snuffy2** [comment]
![SNAG-0006](https://user-images.githubusercontent.com/6526076/150548869-767066d3-cc32-4b3a-99e7-da622edcaff9.png)

**Comment by mapx-** [comment]
test

`northjersey.com###gnt_mol_oy.gnt_mol_oy`

**Comment by mapx-** [comment]
add also and test again

`northjersey.com##body:style(overflow:auto!important)`

**Comment by Snuffy2** [comment]
Still can scroll or click on links.

**Comment by mapx-** [comment]
Try disable the 2 annoyances lists (breaking the video on my end) and test again

**Comment by mapx-** [comment]
and you should update your firefox (now version 96)

**Comment by Snuffy2** [comment]
Disabled the 3 Annoyance lists. The 2 filters continue to block the subscribe popup and the dimming but prevents scrolling and clicking.
Long story, but upgrading Firefox on this computer is manual. I'll update it when I am able to run updates again.
Thank you for your assistance on this. It is much appreciated.

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 92
filterset (summary): 
  network: 79389
  cosmetic: 42801
  scriptlet: 16442
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30794-31, 59m
    ublock-badware: 3748-1, 59m
    ublock-privacy: 191-0, 59m
    ublock-abuse: 76-0, 59m
    ublock-unbreak: 1699-0, 59m
    easylist: 63179-594, 59m
    easyprivacy: 26642-481, 59m
    urlhaus-1: 8274-0, 59m
    plowe-0: 3676-2, 59m
filterset (user): [array of 1080 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1533 ms (selfie)
popupPanel: 
  blocked: 33
```
</details>

**Comment by Procyon-b** [comment]
Can you try this filter:
```
northjersey.com##html:style(overflow-y:scroll !important;)
```

**Comment by Snuffy2** [comment]
Using:
`northjersey.com###gnt_mol_oy.gnt_mol_oy
northjersey.com##html:style(overflow-y:scroll !important;)`

It hides the popup and allows scrolling, but links still don't work. Getting there .....

**Comment by Procyon-b** [comment]
What if you use this
```
northjersey.com##.gnt_mol_oy
! instead of
! northjersey.com###gnt_mol_oy.gnt_mol_oy
```

**Comment by Snuffy2** [comment]
Using:
`northjersey.com##.gnt_mol_oy`
`northjersey.com##html:style(overflow-y:scroll !important;)`

Same outcome. It hides the popup and allows scrolling, but links still don't work.

**Comment by Procyon-b** [comment]
Here is a weird thing. I can reproduce your popup (using a US proxy) only when I disable ublock for the site.
Can you do one last check. Go to the "_Filter lists_" pane and uncheck "_My filters_". I want to rule out one of your filters as the culprit.

**Comment by Snuffy2** [comment]
Yep, even with my filters disabled it still appears.

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 92
filterset (summary): 
  network: 79626
  cosmetic: 41920
  scriptlet: 19219
  html: 625
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 0-0, never
    ublock-annoyances: 4364-5, 1h.55m
  default: 
    ublock-filters: 30803-29, 1h.55m
    ublock-badware: 3748-1, 1h.55m
    ublock-privacy: 191-0, 1h.55m
    ublock-abuse: 76-0, 1h.55m
    ublock-unbreak: 1697-0, 1h.55m
    easylist: 63179-591, 1h.55m
    easyprivacy: 26642-481, 1h.55m
    urlhaus-1: 8274-0, 1h.55m
    plowe-0: 3676-2, 1h.55m
filterset (user): [array of 1068 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1533 ms (selfie)
popupPanel: 
  blocked: 34
```
</details>

**Comment by Procyon-b** [comment]
These filters should work not (don't forget to re-enable you filters)
```
northjersey.com##.gnt_mol_oy
northjersey.com##html:style(overflow-y:scroll !important;pointer-events: unset !important;user-select: unset !important;)
```

**Comment by mapx-** [comment]
I'm able to reproduce the issue only on mobile and your filters are working fine @Procyon-b

**Comment by Procyon-b** [comment]
I'm reproducing only with uBO disabled (and reenabled as soon as the popup appears).
I really wonder what is different with his config.

**Comment by mapx-** [comment]
same filters for `usatoday`

**Comment by Procyon-b** [comment]
When I see all the scripts/ads/whatever that these sites load, and how it overloads my small computer when I open the dev console, I'm really glad to use ublock.

**Comment by Snuffy2** [comment]
I won't be back to the computer I was having the issue on until next week but it seems to work on a different computer. I'll try the filters on Firefox 92 and then upgrade to Firefox 96 trying with or without the new filter to see the effects. Thanks for all of your help.

**Comment by Procyon-b** [comment]
@mapx- has added the filters to the list "_uBlock filters – Annoyances_". Just refresh the list.
