### ISSUE TITLE
world4.eu: detection

### ISSUE THREAD

**Issue by Stoltverd** [uBlockOrigin/uAssets#11397]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://world4.eu/`

### Category

detection

### Describe the issue

The site is detecting UBlock and disabling left click, so even by choosing elements and filtering them, the site is impossible to navigate.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79226
  cosmetic: 40543
  scriptlet: 16458
  html: 0
listset (total-discarded, last updated): 
  removed: 
    spa-0: null
    spa-1: null
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1h.23m
  default: 
    easylist: 63067-9, 3d.5h.21m
    easyprivacy: 26627-17, 3d.5h.20m
    plowe-0: 3685-816, 11d.20h.4m
    ublock-abuse: 76-0, 3d.5h.19m
    ublock-badware: 3724-67, 3d.5h.17m
    ublock-filters: 30159-149, 3d.5h.16m
    ublock-privacy: 190-3, 3d.5h.15m
    ublock-unbreak: 1723-39, 3d.5h.14m
    urlhaus-1: 8093-0, 21h.17m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 4008 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances` it will filter annoyances like right click issues
