### ISSUE TITLE
ng.cengage.com: breakage

### ISSUE THREAD

**Issue by 7echLife** [uBlockOrigin/uAssets#11398]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ng.cengage.com/static/nb/ui/evo/index.html?deploymentId=595311191155805360274363352&eISBN=9780357108307&id=1365479120&snapshotId=2722031`

### Category

breakage

### Describe the issue

Mindtap (Part of Cengage) will not load my assignment correctly. It will infinitely load. At first, I thought zn71fwlbg6f6nsujt-cengage.siteintercept.qualtrics.com will fix the issue but it's more than that. The only way for the page to work is by turning uBO off. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/54084841/150429668-db0825f8-38a2-4501-993b-87143312e517.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 119528
  cosmetic: 132522
  scriptlet: 51465
  html: 624
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 27117-62, now
    adguard-generic: 61928-5190, 3d.21h.19m
    adguard-spyware: 25632-831, 13m
    adguard-annoyance: 49108-3067, 3d.21h.15m
    fanboy-thirdparty_social: 69-0, 7d.3h.3m
    fanboy-cookiemonster: 21506-126, 7d.3h.2m
    ublock-annoyances: 4379-4, 3d.21h.14m
    adguard-spyware-url: 450-3, 13m
    block-lan: 44-0, 13m
  default: 
    ublock-filters: 30754-3266, 3d.21h.24m
    ublock-badware: 3728-1, 3d.21h.23m
    ublock-privacy: 187-0, 3d.21h.22m
    ublock-abuse: 76-0, 3d.21h.21m
    ublock-unbreak: 1734-0, 3d.21h.20m
    easylist: 63179-634, 21m
    easyprivacy: 26642-10880, 13m
    urlhaus-1: 8152-0, now
    plowe-0: 3682-2, 3d.3h.39m
filterset (user): [array of 18 redacted]
trustedset: 
  removed: 
    about-scheme
hostRuleset: 
  added: [array of 226 redacted]
urlRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  uiTheme: dark
supportStats: 
  launchToReadiness: 282 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by mapx-** [comment]
I guess an account is required. Could you provide a test account and describe the steps to get the issue ?

**Comment by 7echLife** [comment]
I'm afraid I can't do that. It's associated with my school account and I had to pay for the e-textbook. So the steps are, you go to one of the labs and click on it. Wait for the lab assignment to load forever.

**Comment by mapx-** [comment]
Open the uBO logger, reproduce again the issue, go to the logger, **select only the blocked requests** / items in the logger then post here a screenshot with that content

**Comment by 7echLife** [comment]
![image](https://user-images.githubusercontent.com/54084841/150431119-1778f50a-f905-4e4f-a670-dc03ef38d25c.png)

Here you go. I noticed the /ruxitagentjs_ is also there. I believe someone else had an issue with cengage and ruxitagentjs was mentioned but was for Fanboy's filters.

**Comment by mapx-** [comment]
test this filter

`@@||ng.cengage.com/static/nb/ui/evo/ruxitagentjs_$script,1p`

**Comment by 7echLife** [comment]
I will try it when I get home

**Comment by gorhill** [comment]
If this does not work, you could also try:

    @@||delmarlearning.com^$1p,script

When I navigate to `delmarlearning.com`, I am redirected to `cengage.ca`, so these appear related. I do see many `delmarlearning.com` scripts being blocked by generic filters, so it could be the issue.

**Comment by 7echLife** [comment]
Quick question where do I put these filters?

**Comment by iam-py-test** [comment]
> Quick question where do I put these filters?

The My Filters tab on the uBlock Origin dashboard

**Comment by 7echLife** [comment]
Okay thanks, will give results soon.

**Comment by 7echLife** [comment]
> @@||delmarlearning.com^$1p,script

This one worked. Thank you for not only solving this problem, but also creating this amazing content spectrum blocker.

**Comment by gorhill** [comment]
cc @ryanbr

**Comment by ryanbr** [comment]
Which filter is causing the issue? `@@||delmarlearning.com^$1p,script` is too generic.
