### ISSUE TITLE
resources.intenseschool.com advert modal

### ISSUE THREAD

**Issue by cyberjacob** [uBlockOrigin/uAssets#114]
### URL(s) where the issue occurs

`http://resources.intenseschool.com/vpn-on-the-cisco-asa-vpn-traffic-filtering/`

### Describe the issue

Full-screen modal advertising CCNA training.

### Screenshot(s)

![2016-08-26 14_35_23-vpn on the cisco asa_ vpn traffic filtering - intense school](https://cloud.githubusercontent.com/assets/161093/18007088/7cef7472-6b9a-11e6-8d5c-8a7ea3e38d50.png)

### Versions

- Browser/version: FireFox 48.0.2
- uBlock Origin version: 1.8.4

### Settings

- Enabled additional filter sets

### Notes

Fix ready to be merged

**Comment by gorhill** [comment]
Again, a plain cosmetic filter can take care of this, report to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=62>.

**Comment by cyberjacob** [comment]
Apologies, I was under the impression from the README ("The goal of this repository is to receive all the reports for the need of new filters") that this was the appropriate place to report (and submit filter rules for) adverts.

**Comment by gorhill** [comment]
Yes, it is indeed to receive reports of filter issues -- but it does not mean I will agree that whatever filters is needed should go in _uBlock filters_ -- which is mostly dedicated for filters only supported by uBO's extended syntax. Plain filters are best added to EasyList, they benefit everybody using EasyList, not just uBO users.
