### ISSUE TITLE
cuevana2.io: breakage

### ISSUE THREAD

**Issue by bountyduck** [uBlockOrigin/uAssets#11408]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cuevana2.io/episodio/2-01-trying-to-get-to-heaven-before-they-close-the-door/`

### Category

breakage

### Describe the issue

Whenever trying to play a video, blocking the Fingerprintjs library stops the video from loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 101203
  cosmetic: 134672
  scriptlet: 21444
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 49308-148, 6h.14m
    adguard-spyware-url: 450-1, 6h.14m
    block-lan: 44-0, 6h.14m
    curben-phishing: 10137-0, 6h.14m
    curben-pup: 391-0, 6h.14m
    fanboy-annoyance: 60029-2833, 6h.14m
    fanboy-thirdparty_social: 69-20, 6h.14m
    ublock-annoyances: 4351-257, 6h.14m
  default: 
    easylist: 63179-49, 6h.14m
    easyprivacy: 26642-109, 6h.14m
    plowe-0: 3682-817, 6h.14m
    ublock-abuse: 76-0, 6h.14m
    ublock-badware: 3739-67, 6h.14m
    ublock-filters: 30211-458, 6h.14m
    ublock-privacy: 194-12, 6h.14m
    ublock-unbreak: 1687-45, 6h.14m
    urlhaus-1: 8099-4, 6h.14m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 611 ms
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
`@@||cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js$script,domain=cuevana2.io`

EP issue @ryanbr

**Comment by uBlock-user** [comment]
`https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/fingerprint2.js` needs to be updated.

**Comment by gorhill** [comment]
> needs to be updated

FP3 has a different API than FP2, this needs a new shim.

**Comment by uBlock-user** [comment]
Isn't FP2 deprecated by FP3 ?

**Comment by gorhill** [comment]
Usage of FP2 does not automatically disappear from websites all over the world because there is a new iteration of the library.
