### ISSUE TITLE
shorteet.com: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11406]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shorteet.com/vEym4NiE`

### Category

ads

### Describe the issue

After solving captcha, go to the next page and there are ads banners. Click anywhere and a popup occurs, and countdown stops when switching tabs/softwares. The destination URL is `https://www.google.com`

Proposed filters:

```
||garysero.xyz^
shorteet.com##+js(set, blurred, false)
shorteet.com##+js(set, window.open, undefined)
shorteet.com##.banner
```

Not sure why `##+js(nowoif)` can't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/150476430-d141991b-426f-44c4-8f35-62d868d94cb6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79450
  cosmetic: 41916
  scriptlet: 19206
  html: 625
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4360-4, 45m
  default: 
    ublock-filters: 30787-30, 45m
    ublock-badware: 3743-1, 45m
    ublock-privacy: 191-0, 45m
    ublock-abuse: 76-0, 45m
    ublock-unbreak: 1698-0, 45m
    easylist: 63179-591, 45m
    easyprivacy: 26642-481, 45m
    urlhaus-1: 8099-0, 45m
    plowe-0: 3682-2, 45m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 269 ms (selfie)
popupPanel: 
  blocked: 23
```
</details>

**Comment by ghajini** [comment]
`shorteet.com##+js(set, blurred, false)`
doesn't work
iam in another tab,  still timer is paused
iam on firefox android stable ubo 1.40.8

**Comment by Yuki2718** [comment]
@ghajini Android? Working on my end (PC).

**Comment by ghajini** [comment]
perhaps android
