### ISSUE TITLE
hdrezka.cm: breakage

### ISSUE THREAD

**Issue by AlfoMora** [uBlockOrigin/uAssets#11409]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdrezka.cm/`

### Category

breakage

### Describe the issue

Blocks the secure domain jsdelivr.net

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 173877
  cosmetic: 189897
  scriptlet: 34448
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 6h.30m
    adguard-annoyance: 49308-443, 6h.33m
    adguard-generic: 61077-885, 6h.44m
    adguard-mobile: 7128-66, 6h.43m
    adguard-spyware: 25632-834, 6h.42m
    adguard-spyware-url: 450-12, 6h.41m
    block-lan: 44-0, 9d.6h.59m
    curben-phishing: 10137-0, 2h.28m
    curben-pup: 391-0, 2h.27m
    dpollock-0: 10346-265, 9d.7h
    fanboy-annoyance: 63102-6173, 6d.22h.35m
    fanboy-cookiemonster: 21511-21511, 6d.22h.34m
    mvps-0: 8730-1758, 9d.7h.1m
    ublock-annoyances: 4351-294, 6h.32m
  default: 
    RUS-0: 40810-10, 6h.31m
    easylist: 63179-1291, 6h.40m
    easyprivacy: 26642-10771, 6h.39m
    plowe-0: 3681-1497, 1d.11h.2m
    ublock-abuse: 76-1, 6h.38m
    ublock-badware: 3739-214, 6h.37m
    ublock-filters: 30211-3326, 6h.36m
    ublock-privacy: 190-38, 6h.35m
    ublock-unbreak: 1687-111, 6h.34m
    urlhaus-1: 8274-4, 2h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 753 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
and the breakage is ... ?

**Comment by justperson622** [comment]
Plays ads in the video player window before watching a movie. Previously, everything worked without ads.

**Comment by uBlock-user** [comment]
Redirects to `rezka.ag`

**Comment by uBlock-user** [comment]
tested at `https://rezka.ag/films/horror/46017-poslednee-chto-videla-meri-2021.html` with RU Adlist enabled

No ads or breakage of any kind. Video plays as expected.

**Comment by dimisa-RUAdList** [comment]
Based on the configuration data, the filters have not been updated: `RUS-0: 40810-10, 6h.31m`

@AlfoMora 
Please take a [screenshot of the logger](https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=8#1).

**Comment by justperson622** [comment]
> Redirects to `rezka.ag`

You need to enter the site through the button of the social network VK. Then there will be no redirect. The ad before the video continues to play. 
![Снимок](https://user-images.githubusercontent.com/59394061/150630411-fef96ca6-d8a9-4ba0-93c9-27855fc8a71d.PNG)
