### ISSUE TITLE
cooleffect.org: breakage

### ISSUE THREAD

**Issue by cliffspradlin** [uBlockOrigin/uAssets#11405]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cooleffect.org/`

### Category

breakage

### Describe the issue

only the header and footer of the site appears. the main content only loads if I disable uBlock Origin.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 91
filterset (summary): 
  network: 82451
  cosmetic: 66873
  scriptlet: 16461
  html: 616
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 21696-12, 10h.54m
    KOR-1: 8059-3, 4d.6h.36m
  default: 
    ublock-filters: 30734-39, 3d.1h.37m
    ublock-badware: 3728-1, 3d.1h.36m
    ublock-privacy: 187-0, 3d.1h.17m
    ublock-abuse: 76-0, 3d.1h.16m
    ublock-unbreak: 1693-0, 3d.1h.15m
    easylist: 63105-597, 3d.1h.14m
    easyprivacy: 26632-486, 3d.1h.13m
    urlhaus-1: 8099-0, 10h.53m
    plowe-0: 3682-2, 5d.13h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 861 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by mapx-** [comment]
add

`cooleffect.org#@#.ce-banner`

`EasyList Cookie` issue @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/01c6a3f6ad6dc34dda3d944f40a701dcca2a0197
