### ISSUE TITLE
tomsguide.com: ads

### ISSUE THREAD

**Issue by ReaLJohnBaker** [uBlockOrigin/uAssets#11404]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tomsguide.com/uk/news/facebook-and-instagram-will-reportedly-become-major-nft-marketplaces`

### Category

ads

### Describe the issue

deals-ads-sponsored
Idk how to upload screenshots in-case you cant see it here's the link 
https://user-images.githubusercontent.com/62249282/150459119-18ed941f-e7e5-4209-bfcb-406bf318646e.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!-- drag-and-drop scr
https://user-images.githubusercontent.com/62249282/150459119-18ed941f-e7e5-4209-bfcb-406bf318646e.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Unknown: 0
filterset (summary): 
  network: 97204
  cosmetic: 61636
  scriptlet: 18050
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 40810-9, 19m
  default: 
    easylist: 63179-27, 18m
    easyprivacy: 26642-113, 18m
    plowe-0: 3682-821, 18m
    ublock-abuse: 76-1, 18m
    ublock-badware: 3739-67, 18m
    ublock-filters: 30211-181, 18m
    ublock-privacy: 194-3, 18m
    ublock-unbreak: 1687-39, 18m
    urlhaus-1: 8099-0, 18m
filterset (user): [array of 21 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 611 ms
popupPanel: 
  blocked: 20
```
</details>
![2](https://user-images.githubusercontent.com/62249282/150459229-c0e92c0f-bf30-4b6b-93e1-d482444d22bf.png)

**Comment by mapx-** [comment]
@ryanbr
