### ISSUE TITLE
finance.yahoo.com: nuisance

### ISSUE THREAD

**Issue by TheUnixDude** [uBlockOrigin/uAssets#11401]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://finance.yahoo.com/`

### Category

nuisance

### Describe the issue

There is a pop-over "hover" ad for their finance tools. The zapper and element picker are both unable to select it for filtering.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/14986657/150453614-8e23f109-955b-4b68-9335-f96dd3ba1260.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79349
  cosmetic: 82863
  scriptlet: 16454
  html: 616
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42483-109, 1d.14h.43m
  default: 
    ublock-filters: 30775-30, 6h.57m
    ublock-badware: 3733-1, 6h.56m
    ublock-privacy: 191-0, 6h.54m
    ublock-abuse: 76-0, 6h.53m
    ublock-unbreak: 1698-0, 6h.52m
    easylist: 63179-587, 6h.51m
    easyprivacy: 26642-480, 6h.50m
    urlhaus-1: 8152-0, 18h.58m
    plowe-0: 3681-2, 1d.2h.59m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 38 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 423 ms (selfie)
popupPanel: 
  blocked: 152
```
</details>

**Comment by mapx-** [comment]
add

`finance.yahoo.com##.wafer-img`

@ryanbr
