### ISSUE TITLE
all-gay-video.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1140]
URL(s) where the issue occurs

http://all-gay-video.com/video/31980/sexy-boy-waxing-his-rod-in-the

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
add as custom filters
```
||all-gay-video.com/*.gif$image
all-gay-video.com##.my-header-right
about:blank$popup,domain=all-gay-video.com
```
