### ISSUE TITLE
diepresse.com: breakage

### ISSUE THREAD

**Issue by Del3000** [uBlockOrigin/uAssets#11400]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.diepresse.com/6086651/der-bitcoin-auf-talfahrt-was-um-himmels-willen-ist-da-los`

### Category

breakage

### Describe the issue

The plugin to play the podcast does not load / is not displayed / is blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 92029
  cosmetic: 136351
  scriptlet: 18762
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 49220-150, 1d.20h.28m
    fanboy-annoyance: 63108-6092, 5d.23h.29m
    fanboy-cookiemonster: 21511-21511, 6d.5h.23m
    fanboy-thirdparty_social: 68-20, 6d.5h.21m
  default: 
    DEU-0: 5261-0, 20h.20m
    easylist: 63126-53, 1d.20h.41m
    easyprivacy: 26635-120, 1d.20h.39m
    plowe-0: 3682-818, 5d.23h.33m
    ublock-abuse: 76-0, 1d.20h.37m
    ublock-badware: 3724-67, 1d.20h.34m
    ublock-filters: 30190-466, 1d.20h.30m
    ublock-privacy: 190-11, 1d.20h.32m
    ublock-unbreak: 1683-45, 1d.20h.43m
    urlhaus-1: 8152-0, 20h.22m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 63 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 17591 ms
popupPanel: 
  blocked: 2
```
</details>

**Comment by Procyon-b** [comment]
This is caused by the lists ("_Fanboy’s Annoyance_", "_AdGuard Annoyances_", and perhaps "_fanboy-thirdparty_social_") hiding the cookie consent. Without cookies you can't access the full resources.
Add this filter to display the GDPR dialog:
```
@@||privacymanager.io^$3p,domain=www.diepresse.com
```

**Comment by mapx-** [comment]
FA & AA maintainers have been notified
