### ISSUE TITLE
nexusmods.com: nuisance

### ISSUE THREAD

**Issue by TRIPSLORD** [uBlockOrigin/uAssets#11403]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nexusmods.com/witcher3/mods/1555?tab=files&file_id=16221`

### Category

nuisance

### Describe the issue

Trying to block an element gives ||www.nexusmods.com/assets/images/default/bg_default.jpg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Making selection
![image](https://user-images.githubusercontent.com/98132413/150458580-5cfb3256-68ee-4aad-a055-37f930b1fb82.png)
Selection made
![image](https://user-images.githubusercontent.com/98132413/150458637-bb40f971-5361-4bf8-9692-134c8d337359.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79182
  cosmetic: 40639
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 3h.17m
    easyprivacy: 26642-17, 3h.16m
    plowe-0: 3684-816, 7d.22h.15m
    ublock-abuse: 76-0, 3h.19m
    ublock-badware: 3739-67, 3h.21m
    ublock-filters: 30193-149, 22h
    ublock-privacy: 190-3, 3h.20m
    ublock-unbreak: 1683-39, 3h.18m
    urlhaus-1: 8099-0, 3h.15m
filterset (user): [array of 58 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 162 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by uBlock-user** [comment]
Pick the first one from cosmetic filters list. By default network filters are suggested now first.
