### ISSUE TITLE
Embedded imagebb breaking?

### ISSUE THREAD

**Issue by T3sl4co1l** [uBlockOrigin/uAssets#11402]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.eevblog.com/forum/projects/mclk-signal-how-bad-is-it/`

### Category

breakage

### Describe the issue

ibb.co embedded images not showing while the "uBlock filters" list is enabled.  They show as normal with it disabled.  Also, they show immediately when the "disable cosmetic filters" button is pressed.  I don't see any lines offhand that would cause this filtering though, and the elements aren't highlighted in the logger? (I might be misunderstanding how to read it, though.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 79224
  cosmetic: 40584
  scriptlet: 16470
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63125-9, 2d.3h.3m
    easyprivacy: 26635-17, 2d.3h.2m
    plowe-0: 3682-816, 2d.16h.33m
    ublock-abuse: 76-0, 2d.3h.1m
    ublock-badware: 3724-67, 2d.3h
    ublock-filters: 30182-149, 2d.2h.59m
    ublock-privacy: 190-3, 2d.2h.58m
    ublock-unbreak: 1683-39, 2d.2h.57m
    urlhaus-1: 8152-0, 19h.33m
filterset (user): [array of 79 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 430 ms (selfie)
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
```
</details>

**Comment by Procyon-b** [comment]
Caused by this filter #11094
Try adding these filters:
```
eevblog.com#@#a[target] > img:upward(a)
eevblog.com##a[target]:not(.bbc_link) > img:upward(a)
```
