### ISSUE TITLE
elespectador.com: breakage

### ISSUE THREAD

**Issue by dangarciahe** [uBlockOrigin/uAssets#11414]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.elespectador.com/colombia/medellin/absolvieron-a-musico-felipe-munoz-en-caso-de-en-caso-de-aborto-no-consentido/`

### Category

breakage

### Describe the issue

ElEspectador.com has been acting strange lately, sometimes not loading the page at all, sometimes just the first few articles. Today all articles seemed to load correctly, but when you open any of them the page is just blank :)
When fully turning off uBlock, page loads correctly. When turned on, it doesn't. I tried to manually check what was preventing this, but was unable to do that (this may be an error from my side, since I'm only getting 2 buttons on the dynamic filtering: Gray and red, not the green one)
![git](https://user-images.githubusercontent.com/54967248/150567887-d4f3c46c-b04b-4e1e-ab10-f1d87070e6c3.png)

On the photo you can see how the article doesn't load at all, and how I'm only seeing the gray and the red button, not the green one. Tried restoring default options for this last thing without sucess

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 97
filterset (summary): 
  network: 147618
  cosmetic: 184006
  scriptlet: 32912
  html: 624
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 2d.20h.11m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 1d.18h.34m
    adguard-generic: 61952-4778, 3d.10h.41m
    adguard-mobile: 7084-217, 3d.10h.40m
    adguard-spyware: 25619-1160, 3d.10h.38m
    adguard-annoyance: 49174-4219, 3d.10h.36m
    adguard-social: 15538-41, 2d.2h.41m
    fanboy-thirdparty_social: 69-0, 4d.13h.53m
    fanboy-annoyance: 59860-44885, 4d.13h.52m
    fanboy-cookiemonster: 21530-122, 4d.13h.51m
    fanboy-social: 23149-1085, 2d.2h.40m
    ublock-annoyances: 4368-8, 2d.2h.39m
    dpollock-0: 10346-512, 1d.18h.36m
    mvps-0: 8730-1500, 1d.18h.35m
    adguard-spyware-url: 448-3, 2d.2h.38m
    block-lan: 44-0, 4d.9h.49m
  default: 
    ublock-filters: 30734-101, 3d.10h.47m
    ublock-badware: 3728-1, 3d.10h.46m
    ublock-privacy: 187-0, 3d.10h.45m
    ublock-abuse: 76-0, 3d.10h.44m
    ublock-unbreak: 1692-1, 3d.10h.42m
    easylist: 63105-1021, 3d.10h.39m
    easyprivacy: 26632-11106, 3d.10h.37m
    urlhaus-1: 8099-0, 20h.57m
    plowe-0: 3685-4, 11d.23h.27m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 13 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5221 ms (selfie)
popupPanel: 
  blocked: 14
```
</details>

**Comment by uBlock-user** [comment]
`||prebid.elespectador.com^$script,redirect-rule=googletagservices_gpt.js,1p` works.

**Comment by dangarciahe** [comment]
> `||prebid.elespectador.com^$script,redirect-rule=googletagservices_gpt.js,1p` works.

Excuse my ignorance, but does that mean you are not able to reproduce it?

**Comment by uBlock-user** [comment]
>  you are not able to reproduce it?

No, I can reproduce, that's the filter to unbreak the site.

**Comment by dangarciahe** [comment]
Got it, thank you.

**Comment by uBlock-user** [comment]
@okiehsch Should we add the redirection filter or allow prebid crap to load ?
