### ISSUE TITLE
philips.co.uk: breakage

### ISSUE THREAD

**Issue by MonoTech1** [uBlockOrigin/uAssets#11410]
### Prerequisites

- [x] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.philips.co.uk/c-p/279M1RV_00/momentum-4k-hdr-display-with-ambiglow/support`

### Describe the issue

Page won't fully load with uBlock Origin, work when disabled for the website

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.1

### Settings

No changes

**Comment by mapx-** [comment]
Are you really using `default lists/settings` ?

What exactly is broken ?

**Comment by MonoTech1** [comment]
Sorry, the website seems to be broken. Yesterday when I tried it could only load the informations about the product with uBlock disabled - now it doesn't load anything at all...

Will reopen if I can reproduce
