### ISSUE TITLE
speedtest.net: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#11416]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.speedtest.net/`

### Category

ads

### Describe the issue

There is a blank area on the side. There are ad leftovers

### Screenshot(s)

![Screen Shot 2022-01-21 at 11 27 06 AM](https://user-images.githubusercontent.com/69532417/150588451-f3d32edb-71d4-4413-a483-fb94fcde26eb.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 118436
  cosmetic: 169814
  scriptlet: 32867
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    adguard-annoyance: 49206-148, 3d.1h.11m
    adguard-generic: 61997-671, 3d.1h.11m
    adguard-mobile: 7086-48, 3d.1h.11m
    adguard-spyware: 25623-774, 3d.1h.11m
    fanboy-annoyance: 63179-6182, 3d.1h.11m
    fanboy-thirdparty_social: 68-20, 3d.1h.11m
    ublock-annoyances: 4359-292, 3d.1h.11m
  default: 
    easylist: 63125-1049, 3d.1h.11m
    easyprivacy: 26633-10665, 3d.1h.11m
    ublock-abuse: 76-0, 3d.1h.11m
    ublock-badware: 3724-207, 3d.1h.11m
    ublock-filters: 30181-3293, 3d.1h.11m
    ublock-privacy: 190-36, 3d.1h.11m
    ublock-unbreak: 1683-109, 3d.1h.11m
    urlhaus-1: 7598-0, 2h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 719 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by Procyon-b** [comment]
The left and right "ad skyscrapers" are hidden. The content is limited to 760px width, that's why it's not using the whole space.

**Comment by gwarser** [comment]
www.speedtest.net##.pure-u-custom-speedtest:style(width:unset!important;)
	  www.speedtest.net##.speedtest-container.main-row:style(width:unset!important;)

**Comment by mapx-** [comment]
or

`speedtest.net#@#.pure-u-custom-ad-skyscraper`

?

**Comment by jimmysofat6864** [comment]
@mapx- @gwarser Any chance these changes will be added into ublock filters or easy list any time soon?

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11332

**Comment by mapx-** [comment]
added
