### ISSUE TITLE
School site doesn't work with uBlock Origin (my.hrw.com)

### ISSUE THREAD

**Issue by Tommy2678** [uBlockOrigin/uAssets#11417]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://my.hrw.com/`

### Describe the issue

Nothing will load whilst uBlock Origin is on. I have to turn it off and then it starts working again. If you could have it turn off everything by default on this website it'd be great, it is a hassle to turn off and on again, especially when recommended to other people in my school, and I doubt they'd know what's happening.

### Screenshot(s)

https://user-images.githubusercontent.com/76851779/150594697-26bcd61e-d4f1-4cf7-87e4-356154765db2.png
https://user-images.githubusercontent.com/76851779/150594705-165398fe-5595-4a44-b69e-8ae6d9fb9d43.png

### uBlock Origin version

1.40.8

### Browser name and version

Edge, (97.0.1072.69) and Chrome, (97.0.4692.99)

### Settings

- Switched off completely

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go into the logger and post here a screenshot containing **only the blocked items** you see there (you can select only the blocked items in the search box)

**Comment by krystian3w** [comment]
Also for schools possible add pages in "trusted" section by policies.

https://deployhappiness.com/deploying-ublock-origin-for-chrome-and-configuring-a-whitelist/ - similar in the past wrote gorhill in uBlock-issues repo.

**Comment by Tommy2678** [comment]
![image](https://user-images.githubusercontent.com/76851779/150667986-630c0a13-94fd-436f-af33-cf62cdbb5b4e.png)


> Use only the default settings, open the logger, reproduce the issue, go into the logger and post here a screenshot containing **only the blocked items** you see there (you can select only the blocked items in the search box)

![image](https://user-images.githubusercontent.com/76851779/150667986-630c0a13-94fd-436f-af33-cf62cdbb5b4e.png)

**Comment by Tommy2678** [comment]
sorry if i did it wrong, i'm pretty much a noob.

**Comment by krystian3w** [comment]
So bug is in `no-floc` or in EasyPrivacy.

**Comment by mapx-** [comment]
test his filter

`@@||my.hrw.com^$script,1p`

**Comment by Yuki2718** [comment]
>  i'm pretty much a noob.

Add the filter [suggested](https://github.com/uBlockOrigin/uAssets/issues/11417#issuecomment-1019431848) by @mapx- to My filters, Apply changed, then reload the page and see if the problem has gone or passists. If it didn't work, remove the rule and instead add `@@||adobedtm.com^*/satelliteLib-$script,domain=my.hrw.com` and follow the same steps.

**Comment by krystian3w** [comment]
On last step disable no-floc scriptlet:

`my.hrw.com#@#+js(no-floc)`

For fix scriptlet may needed is log form devtools or demo accout to reproduce problem in free time.

**Comment by uBlock-user** [comment]
FloC scriptlet removed now, so that filter is not needed, force update to sync with the new change.

**Comment by mapx-** [comment]
@Tommy2678 did you test the filters above ?

**Comment by krystian3w** [comment]
Maybe died but why not reported to school IT teacher.
