### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by Nikita45tg** [uBlockOrigin/uAssets#11415]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rezka.ag/series/comedy/25677-amerikanskiy-vandal-2017.html`

### Category

ads

### Describe the issue

Реклама 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 97163
  cosmetic: 61596
  scriptlet: 18038
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40808-9, 1d.2h.23m
    easylist: 63179-27, 4h.14m
    easyprivacy: 26632-113, 3d.58m
    plowe-0: 3684-821, 10d.2m
    ublock-abuse: 76-1, 3d.57m
    ublock-badware: 3724-67, 3d.56m
    ublock-filters: 30172-180, 3d.55m
    ublock-privacy: 190-3, 3d.54m
    ublock-unbreak: 1682-39, 3d.53m
    urlhaus-1: 8099-0, 1d.2h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 26267 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by dimisa-RUAdList** [comment]
Based on the configuration data, the filters have not been updated: `RUS-0: 40808-9, 1d.2h.23m`

**Comment by RedFoxTrue** [comment]
> Based on the configuration data, the filters have not been updated: `RUS-0: 40808-9, 1d.2h.23m`

I also see ads on this site

**Comment by dimisa-RUAdList** [comment]
@RedFoxTrue 
In what configuration?

**Comment by RedFoxTrue** [comment]
@dimisa-RUAdList what you mean? 

windows 10, Firefox 96.0.2

**Comment by dimisa-RUAdList** [comment]
Neither Windows nor Firefox block ads on their own. To block ads, you need to use an ad blocker.

**Comment by RedFoxTrue** [comment]
@dimisa-RUAdList lol dude i use uBlock Origin and that's why I'm here. 
i just telling you: on this https://rezka.ag/series/comedy/1814-ofis-2005.html site i see ads when start player and all

**Comment by dimisa-RUAdList** [comment]
@RedFoxTrue
https://i.imgur.com/4P8LcYK.jpg

**Comment by RedFoxTrue** [comment]
@dimisa-RUAdList thanks it worked

**Comment by IgnatMiller** [comment]
Ads before all videos are still there. Forcing update of filter lists doesn't help. Brave & Windows 10 (all up to date).

**Comment by mapx-** [comment]
adding `RUS: RU AdList` is removing video ads on my side

**Comment by dimisa-RUAdList** [comment]
@IgnatMiller 
Link and configuration required.
