### ISSUE TITLE
Blaklader sites - Broken (uBlock filters - Privacy)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#11422]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

blaklader.*

### Affected sites:
```
https://www.blaklader.at/
https://www.blaklader.be/
https://www.blaklader.ca/
https://www.blaklader.com/
https://www.blaklader.cz/
https://www.blaklader.de/
https://www.blaklader.dk/
https://www.blaklader.ee/
https://www.blaklader.es/
https://www.blaklader.fi/
https://www.blaklader.fr/
https://www.blaklader.ie/
https://www.blaklader.it/
https://www.blaklader.nl/
https://www.blaklader.no/
https://www.blaklader.pl/
https://www.blaklader.se/
https://www.blaklader.uk/
```

### Issue:
Some elements are hidden, until the cookie terms have been accepted.
However, the cookie terms can't be accepted, because they're blocked!

### Examples:
```
https://www.blaklader.ca/en/
https://www.blaklader.com/en/
```

### Screenshot:

![filterissue-blaklader](https://user-images.githubusercontent.com/9382674/150605300-77fa3bad-253d-4261-9a4e-a47e29b5f1a9.jpg)

### Problem filter:
* **uBlock filters - Privacy**

### Problem rule:
`||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js`

### Possible fix (uBO Legacy compatible):
`@@||googletagmanager.com/gtm.js$domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk`

### Note:
The issue seems to be partially browser-dependent.
More info here:
https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1018916867

### Other problem filters:
* **AdGuard Annoyances filter** / **AdGuard Tracking Protection filter** https://github.com/AdguardTeam/AdguardFilters/issues/107716/
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`
`||googletagmanager.com/gtm.js$third-party`

* **EasyList Cookie List** / **Fanboy's Annoyance List** / **EasyPrivacy** https://github.com/easylist/easylist/issues/10565/
`##.optanon-show-settings`
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`
`/gtm.js`
`||googletagmanager.com^`

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* **I don't care about cookies** _(NOTIFIED)_
`~msn.com,~eurogamer.net,~rtlxl.nl,~zdf.de,~crfashionbook.com,~rockpapershotgun.com,~zdnet.com,~mensjournal.com,~cbsnews.com,~cbslocal.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~kruidvat.be,~trekpleister.nl,~tvn24.pl,~popsugar.co.uk,~rte.ie,~tunein.com,~oe24.at,~sika.com,~merkurmarkt.at,~boomerang-tv.pl,~cnbc.com,~1001spiele.de,~dhl.de,~sport.pl,~reisetopia.de,~mtvuutiset.fi,~billa.at,~aerztezeitung.de,~okazii.ro###onetrust-consent-sdk`

* **Peter Lowe's Ad and tracking server list**
`googletagmanager.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### uBlock Origin version

v1.16.4.30 (XUL)

### Browser name and version

Pale Moon v29.4.4 (x64)

### Settings

-

**Comment by krystian3w** [comment]
Maybe possible repair resource if page no need something really not standard.

**Comment by krystian3w** [comment]
Also order  before footer of page:

![obraz](https://user-images.githubusercontent.com/35370833/150607938-56dbd7e3-2178-4d45-8cc1-802191617663.png)

(after middle part of homepage).

**Comment by Procyon-b** [comment]
As far as I've seen, `googletagmanager.com` is not at fault here. I don't use the cookies list, and I can see the cookie dialog if I disable the extension handling it. Then I can accept the cookies and the site work correctly.
Just add a filter to allow `cookielaw.org` for `blakader.*`

**Comment by THEtomaso** [comment]
> As far as I've seen, `googletagmanager.com` is not at fault here.

Try with Pale Moon / uBO Legacy

**Comment by uBlock-user** [comment]
Cannot reproduce with Firefox and Chrome, issue specific to uBO Legacy  builds ?

**Comment by THEtomaso** [comment]
> issue specific to uBO Legacy builds ?

Perhaps.
In uBO Legacy, the redirect rule for `gtm.js` actually points to a different script all together!

In uBO:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js`

In uBO Legacy:
`||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js`

**Comment by uBlock-user** [comment]
> ||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js

There's no such filter in uBO Privacy list.

**Comment by THEtomaso** [comment]
> There's no such filter in uBO Privacy list.

Yes there is.
You simply don't see it, because the rule is modified by uBO Legacy's syntax converter:
https://github.com/gorhill/uBlock-for-firefox-legacy/commit/6d1c0c095bfaa639438643056708bcb572ff267d

**Comment by uBlock-user** [comment]
> because the rule is modified

If that was the case it would happen for non-legacy builds too. redirect-rule doesn't internally change scripts. 

@gorhill

**Comment by uBlock-user** [comment]
Could you try -- 

```
||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js,badfilter
||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js,important
```

and report back if breakage still occurs for you ?

**Comment by THEtomaso** [comment]
> Could you try --

I already did that, before filing my report.

**Comment by uBlock-user** [comment]
@THEtomaso and which filter does the logger report ?

**Comment by THEtomaso** [comment]
The one that I've listed as the "**Problem rule**" in my first post.

**Comment by uBlock-user** [comment]
Looks like an issue with legacy build itself, did you report this to @JustOff in legacy tracker about this ?

**Comment by THEtomaso** [comment]
This shows how the rule is different in uBO Legacy (which it probably needs to be):

**In uBO:**

![filterissue-blaklader-2](https://user-images.githubusercontent.com/9382674/150633210-d027f37a-6102-494f-9070-e0ed9fb6680e.jpg)

**In uBO Legacy:**

![filterissue-blaklader-3](https://user-images.githubusercontent.com/9382674/150633239-0bcf5639-984c-452c-b4ba-725ed7c700a6.jpg)

**Comment by THEtomaso** [comment]
> did you report this to JustOff in legacy tracker about this ?

No, but I was just about to give him a ping now, but you beat me to it! :)

**Comment by uBlock-user** [comment]
Regardless, I suggest you filea formal bug report there anyway.

**Comment by THEtomaso** [comment]
> I suggest you file a formal bug report there anyway.

This needs to be investigated first, I think:
https://github.com/gorhill/uBlock-for-firefox-legacy/pull/321#issuecomment-1019137155

**Comment by gorhill** [comment]
Could be simply because work has been done in the GA shim ([see](https://github.com/gorhill/uBlock/commits/master/src/web_accessible_resources/google-analytics_analytics.js)) which has not been reflected in the legacy build ([see](https://github.com/gorhill/uBlock-for-firefox-legacy/commits/master/assets/resources)).

**Comment by THEtomaso** [comment]
Until uBO Legacy's scriptlets have been updated, perhaps this fix (which I suggested in my first post) could be added to uBO's Legacy filter?:
```
@@||googletagmanager.com/gtm.js$domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
```
..or even better, this one (which fixes the issues caused by the other filters too):
```
blaklader.*#@#.optanon-show-settings
blaklader.*#@##onetrust-banner-sdk
blaklader.*#@##onetrust-consent-sdk
blaklader.*#@##to-the-top
@@||cookielaw.org^$third-party,domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
@@||googletagmanager.com/gtm.js$domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
```

**Comment by mapx-** [comment]
`googletagmanager` filter was added 8 hours ago
https://github.com/uBlockOrigin/uAssets/commit/c0c725d5123ccc39b1b0a517bafa4c5c9d8641ad

**Comment by uBlock-user** [comment]
> (which fixes the issues caused by the other filters too):

We don't fix issues caused by _**non-default**_ filter lists.

**Comment by krystian3w** [comment]
But repair pages then palemoon have other logic to implement CSS specifications.

**Comment by JustOff** [comment]
Perhaps I missed something, but I see an [absolutely identical issue](https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1018907705) using both Firefox, Chrome and Pale Moon. It is observed in a clean profile with default settings until the cookies are accepted that it is impossible when mentioned GA filter is on.

**Comment by uBlock-user** [comment]
> when mentioned GA filter is on.

That filter is only present at compile time in legacy builds, see - https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1019130785

**Comment by JustOff** [comment]
I'm talking about `||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js` from `uBlock Privacy` and the **latest** `Firefox` and `Chrome`. I see the both browsers have the same problem: cookies accept dialog is missed, part of the site is disabled.

**Comment by uBlock-user** [comment]
on which site ?

**Comment by JustOff** [comment]
https://www.blaklader.ca/en/

In fact this problem is observed when at least one of the `uBlock Privacy`[1], `EasyPrivacy`[2] or `Peter Lowe’s Ad and tracking server list`[3] filters is enabled (and all of them are default filters):

`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js` - [1]
`||googletagmanager.com^` - [2],[3]

**Comment by THEtomaso** [comment]
> https://github.com/uBlockOrigin/uAssets/commit/ade0362bedde3ff73b1d3f4c139ebc0c79efb88a

So, why only fix the `.ca`, `.com` and `.uk` domains?
Their sites are all built the same way.
The issue is simply less obvious on the other domains, since they don't have the same elements on the front page.

**Comment by uBlock-user** [comment]
> So, why only fix the .ca, .com and .uk domains?

Had to use a VPN to reproduce and still can't reproduce on euro domains.

**Comment by JustOff** [comment]
Thanks, and now, given the issue is confirmed as global, it probably no longer makes sense in the legacy-specific fix (https://github.com/uBlockOrigin/uAssets/commit/c0c725d5123ccc39b1b0a517bafa4c5c9d8641ad)?

**Comment by uBlock-user** [comment]
@okiehsch can you reproduce on any euro domains ?

**Comment by okiehsch** [comment]
No.

**Comment by okiehsch** [comment]
> The issue is simply less obvious on the other domains, since they don't have the same elements on the front page.

Let's take `https://www.blaklader.no/nb`, can you point me to the breakage?

**Comment by okiehsch** [comment]
I tried numerous EU domains using chromium and firefox and I can click the cookie accept modal on all of them.

**Comment by mapx-** [comment]
Tested IT, ES, .. no breakage.

**Comment by THEtomaso** [comment]
OK, so I guess the rest of the domains really are affected by a uBO Legacy -only issue then.

**Comment by JustOff** [comment]
I see no problems with the EU domains with uBO Legacy and Pale Moon either, so I intend to consider this issue resolved.

**Comment by uBlock-user** [comment]
@JustOff The issue with the GA filter still exists and uBO legacy is not caught up with uBO as pointed out in https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1019246955

**Comment by JustOff** [comment]
Updating the scriptlets is a completely separate task that I well aware of, and I hope I can make it in a reasonable time or someone else interested in supporting uBO legacy will help. But as regards the problem with Blaklader sites, an outdated GA shim is not the cause of it, and everything was already fixed by adding an exception to the Unbreak filter.
