### ISSUE TITLE
liveivi.com: ads

### ISSUE THREAD

**Issue by oystto** [uBlockOrigin/uAssets#11427]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://liveivi.com/series/realtv/46015-ya-tebe-ne-veryu-2021.html`

### Category

ads

### Describe the issue

ads in video, when you try to play video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 96675
  cosmetic: 61592
  scriptlet: 18045
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40810-9, 1d.4h.38m
    easylist: 63128-27, 2d.22h.32m
    easyprivacy: 26637-113, 2d.22h.31m
    plowe-0: 3682-821, 3d.22h.20m
    ublock-abuse: 76-1, 2d.22h.30m
    ublock-badware: 3724-67, 2d.22h.29m
    ublock-filters: 30197-181, 2d.22h.35m
    ublock-privacy: 190-3, 2d.22h.34m
    ublock-unbreak: 1683-39, 2d.22h.33m
    urlhaus-1: 7623-0, 27m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 17346 ms
popupPanel: 
  blocked: 8
```
</details>

**Comment by dimisa-RUAdList** [comment]
Based on the configuration data, the filters have not been updated: `RUS-0: 40810-9, 1d.4h.38m`

How to update filters: `https://forums.lanik.us/viewtopic.php?f=102&t=22786`
