### ISSUE TITLE
manga4life.com: ads

### ISSUE THREAD

**Issue by notstay23** [uBlockOrigin/uAssets#11423]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manga4life.com/read-online/Overgeared-chapter-1.html`

### Category

ads

### Describe the issue

a popup box would showup in the corner of the screen 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/98194290/150615509-9d465ead-0d8c-4a7b-a565-3c5dec7fd5b8.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 79149
  cosmetic: 40571
  scriptlet: 16457
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63173-9, 2d.3h.31m
    easyprivacy: 26637-17, 2d.3h.30m
    plowe-0: 3684-816, 8d.1h.28m
    ublock-abuse: 76-0, 2d.3h.33m
    ublock-badware: 3724-67, 2d.19h.33m
    ublock-filters: 30160-150, 2d.19h.34m
    ublock-privacy: 190-3, 2d.19h.32m
    ublock-unbreak: 1683-39, 2d.3h.32m
    urlhaus-1: 8099-0, 1d.10m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7621 ms
popupPanel: 
  blocked: 14
  no-popups: true
```
</details>

**Comment by Procyon-b** [comment]
I don't have the same ad as you, but this filter hides it:
```
manga4life.com##body~iframe
```
