### ISSUE TITLE
go.discovery.com: ads

### ISSUE THREAD

**Issue by gazardiel15** [uBlockOrigin/uAssets#11420]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://go.discovery.com/video/battlebots-discovery-atve-us/ducks-dragons-killer-snakes`

### Category

ads

### Describe the issue

the website apparently updated their player, and now ad breaks are back. They aren't incorporated into the video and you can't fast-forward through them. Previously, ads were blocked on this site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79174
  cosmetic: 40589
  scriptlet: 16436
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30778-29, 1d.19h.37m
    ublock-badware: 3733-1, 1d.19h.39m
    ublock-privacy: 187-0, 1d.19h.38m
    ublock-abuse: 76-0, 1d.19h.36m
    ublock-unbreak: 1694-0, 1d.19h.41m
    easylist: 63177-587, 1d.19h.40m
    easyprivacy: 26637-481, 1d.19h.42m
    plowe-0: 3684-2, 10d.23h
    urlhaus-1: 8099-0, 19h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2744 ms (selfie)
popupPanel: 
  blocked: 73
```
</details>

**Comment by mapx-** [comment]
`SSAI - uplynk` requests

https://github.com/uBlockOrigin/uAssets/issues/1905

**Comment by krystian3w** [comment]
@[mapx-](https://github.com/mapx-) mapx- added the[ SSAI ](https://github.com/uBlockOrigin/uAssets/labels/SSAI)label [on 7 Apr 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1562292997)
@[jspenguin2017](https://github.com/jspenguin2017) [jspenguin2017](https://github.com/jspenguin2017) mentioned this issue on 9 May 2018
[Ads] cwtv.com NanoAdblocker/NanoFilters#25
Closed
@jspenguin2017 jspenguin2017 mentioned this issue on 3 Jun 2018
nbc.com #2409
Closed
@[okiehsch](https://github.com/okiehsch) okiehsch changed the title Cwtv video ads Websites using SSAI (server side ad injection) [on 3 Jun 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1659832690)
This was referenced on 3 Jun 2018
Viceland Video Ads #1541
Closed
uBO on Chrome not blocking fox.com #772
Closed
abc7.com #794
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 22 Jul 2018
[Anti-adblock] investigationdiscovery.com #2966
Closed
@[SkeletalDemise](https://github.com/SkeletalDemise) SkeletalDemise mentioned this issue on 22 Jul 2018
anti Adblocker on discovery.com sciencechannel.com #2931
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 2 Sep 2018
Ads Loading gorhill/uBO-Extra#76
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 15 Sep 2018
Ads while watching shows on FOX #3486
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 27 Oct 2018
Midroll Ads Aren't being blocked CityTV.com #3847
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 17 Nov 2018
rediff.com | Tracking #4138
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 23 Nov 2018
Fails to Block Ads on The CW - http://thecwtv.com #4179
Closed
@[stoically](https://github.com/stoically) stoically mentioned this issue on 20 Mar 2019
ALL twitch.tv issues #5184
Open
@[okiehsch](https://github.com/okiehsch) okiehsch mentioned this issue on 11 Jun 2019
https://www.brighteon.com/ #5803
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 17 Jun 2019
discovery.com videos not working easylist/easylist#3636
Closed
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment from [prateekrastogi](https://github.com/prateekrastogi) [on 26 Jan 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-2979959103)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user added the[ can't fix ](https://github.com/uBlockOrigin/uAssets/labels/can%27t%20fix)label [on 17 Jun 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-3453347081)
@[nebchan](https://github.com/nebchan) nebchan mentioned this issue on 29 Sep 2020
Twitch TV now injecting ads #7968
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 1 Nov 2020
Add queryprune filters to deal with SSAI #8131
Merged
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 16 Aug 2021
pluto.tv: Ads not being blocked #9764
Closed
6 tasks
@[subby2006](https://github.com/subby2006) subby2006 mentioned this issue on 1 Sep 2021
sbs.com.au ondemand has a new player and it detects ublock #7836
Closed
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 20 Jan
@uBlock-user
[update](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-394129540
[eb9148f](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a)
This was referenced on 21 Jan
go.tlc.com: ads #11419
Closed
go.discovery.com: ads #11420
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/ac8860312f726292bd3e7c2f34a82f6d20614dbe [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035560189)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user reopened this [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035564682)
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 9 Feb
@uBlock-user
[append](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-1033865488
[fe89b1b](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 17 Feb
discovery plus italy showing ads #11772
Closed
6 tasks
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment [on 9 Mar](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6207603084)
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 25 Mar
hulu.com: ads #12407
Closed
8 tasks
This was referenced on 27 Mar
philo.com: ads #12469
Closed
player.stv.tv: ads #12513
Closed
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 Apr
mech-plus.com: ads #12589
Closed
8 tasks
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 May
amc.com: ads #13065
Closed
8 tasks
This was referenced on 4 Jul
primevideo.com: ads #13906
Closed
animalplanet.com: ads #13969
Closed
tvbanywherena.com: video ads #13978
Closed
This was referenced 23 days ago
vix.com: ads #14213
Closed
discoveryplus.com: ads #10870
Closed
discoveryplus.com: ads #14365
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue 6 days ago
go.tlc.com: ads #14451
Closed
8 tasks
@[MasterKia](https://github.com/MasterKia) MasterKia mentioned this issue 5 days ago
primevideo.com: ads #14512
