### ISSUE TITLE
mzamin.com: ads

### ISSUE THREAD

**Issue by abidulkamal** [uBlockOrigin/uAssets#11426]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://m.mzamin.com/`

### Category

ads

### Describe the issue

There are still leftover ads which are not being detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 94
filterset (summary): 
  network: 82208
  cosmetic: 43278
  scriptlet: 16521
  html: 620
listset (total-discarded, last updated): 
  added: 
    adguard-social: 15525-1073, 3d.20h.59m
    fanboy-cookiemonster: 21558-12884, 3d.21h
  default: 
    ublock-filters: 30900-277, 5h.32m
    ublock-badware: 3728-1, 3d.14h.17m
    ublock-privacy: 191-1, 19h.28m
    ublock-abuse: 76-0, 13h.39m
    ublock-unbreak: 1700-0, 3d.20h.58m
    adguard-mobile: 7130-173, 13h.27m
    easylist: 63179-24284, 3h.34m
    easyprivacy: 26642-492, 13h.28m
    urlhaus-1: 7623-0, 3h.32m
    plowe-0: 3685-2, 12d.23h.59m
filterset (user): [array of 32 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 487 ms (selfie)
popupPanel: 
  blocked: 22
  no-cosmetic-filtering: true
```
</details>

**Comment by mapx-** [comment]
Which ads ? screenshot ?

@ghajini can you help here ?

**Comment by abidulkamal** [comment]
These. I've blocked them again using zipper mode. But after couple of days,
they start showing again, even when the ublock is on.

Also thanks for your quick response.

**Comment by ghajini** [comment]
banner ads
`||mzamin.com/advert/*$image`

these are

**Comment by mapx-** [comment]
@Yuki2718

**Comment by ghajini** [comment]
```
||mzamin.com/advert/
||adfinix.com^$3p
```

**Comment by Yuki2718** [comment]
But ad server should be added to EL. @ryanbr

**Comment by ghajini** [comment]
He will not add these to easylist due to nonenglish sites or whatever the reason

**Comment by ghajini** [comment]
@abidulkamal update in a while &report in back

**Comment by Yuki2718** [comment]
Certainly `adfinix.com` seems to be used mostly on Hindi sites: `https://publicwww.com/websites/%22adfinix.com%22/`. And I see this on desktop too, in that case it must be in Base than Mobile. So I'll move the rule and also add to uBlock filters.
