### ISSUE TITLE
tarjetarojatv.net [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1143]
URL(s) where the issue occurs

http://www.tarjetarojatv.net/fox-sports.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@mapx-

anti adblock
`http://www.tarjetarojatv.net/bein-liga.html`

anti adblock
http://maxdeportv.net/?canal=19a96

anti adblock
http://zonasports.es/live.php?id=11#1-11


ADS
http://www.tarjetarojaonline.tv/canal-33.php#

ADS
http://extremotv.info/en-vivo/canal-1.php

ADS
http://pasiondeportiva.me/live96/pasiondeportiva4.php#

ADS
http://live2all.net/basketball/2376884/valencia-vs-fenerbahce-live/

**Comment by mapx-** [comment]
for anti adb add as custom filters:
```
*.png#$image,redirect=2x2-transparent.png,domain=zonasports.es
@@||zonasports.es^$generichide
*.gif#$image,redirect=1x1-transparent.gif,domain=maxdeportv.net
@@||maxdeportv.net^$generichide
maxdeportv.net###wmpu
||earnco.in^$subdocument
||max-deportv.com/arriba2.html$subdocument
*.jpg#$image,redirect=2x2-transparent.png,domain=lacasadeltikitaka.club
@@||tarjetarojatv.net^$generichide
```

**Comment by KiLL4FuNK** [comment]
Pop-up

`http://tarjetarojatv.club/foxsports-2.php`
