### ISSUE TITLE
derivative-calculator.net: ads

### ISSUE THREAD

**Issue by along02** [uBlockOrigin/uAssets#11437]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.derivative-calculator.net/`

### Category

ads

### Describe the issue

Shows an ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/21041802/150663247-9b8819fe-f8e4-4aac-abd8-3d09e7d2106f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 81862
  cosmetic: 83467
  scriptlet: 18860
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 84-0, 1d.13h.49m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 341-0, 7h.55m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 15-15, 4d.19h
    adguard-annoyance: 49379-149, 8h.3m
  default: 
    easylist: 63179-47, 8h.2m
    easyprivacy: 26642-109, 8h.1m
    plowe-0: 3682-817, 4d.19h
    ublock-abuse: 76-0, 8h
    ublock-badware: 3775-67, 7h.59m
    ublock-filters: 30229-451, 7h.58m
    ublock-privacy: 194-3, 7h.57m
    ublock-unbreak: 1685-41, 7h.56m
    urlhaus-1: 6753-0, 7h.54m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 18199 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by along02** [comment]
If you've closed the ad before, it remembers your preference. Could be similar to this issue https://github.com/uBlockOrigin/uAssets/issues/11328.

**Comment by uBlock-user** [comment]
I don't have close anything, EasyList blocks it with the generic filters.
