### ISSUE TITLE
uschovna.cz: breakage

### ISSUE THREAD

**Issue by luketeam5** [uBlockOrigin/uAssets#11435]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.uschovna.cz/vyzvednout-zasilku`

### Category

breakage

### Describe the issue

The looks normal for a few seconds and when it finishes loading it completely breaks.

You can enable English here: 
![image](https://user-images.githubusercontent.com/40070133/150659743-617c5e4c-2cc8-4e15-a9cc-ba0916b4eee8.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/40070133/150659722-d26c4502-07bb-42c3-a473-e456eb3b5b92.png)
![image](https://user-images.githubusercontent.com/40070133/150659725-748f9602-b2ed-408d-84c8-b1c41180de13.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78094
  cosmetic: 40935
  scriptlet: 16706
  html: 0
listset (total-discarded, last updated): 
  default: 
    CZE-0: 776-0, 33m
    easylist: 63179-10, 40m
    easyprivacy: 26642-22, 39m
    plowe-0: 3682-816, 7d.8h.23m
    ublock-abuse: 76-0, 38m
    ublock-badware: 3775-67, 37m
    ublock-filters: 30228-149, 36m
    ublock-privacy: 194-3, 35m
    ublock-unbreak: 1683-39, 34m
    urlhaus-1: 6753-0, 32m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 53593 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by Procyon-b** [comment]
It's a problem with a filter in the CZE regional list.
Try this filter:
```
@@||cz.mrezadosa.com^$xhr,domain=uschovna.cz
```

**Comment by mapx-** [comment]
and to kill the popup

`uschovna.cz##.branding:upward([target="_blank"])`
