### ISSUE TITLE
dizipal133.com: breakage

### ISSUE THREAD

**Issue by MahirMammadli** [uBlockOrigin/uAssets#11433]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizipal133.com/bolum/konusanlar-1x1-izle/`

### Category

breakage

### Describe the issue

Cannot watch the video when UBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2022-01-23 002420](https://user-images.githubusercontent.com/46172136/150654321-ee3aa59d-c710-4b51-bd5a-3a47a90338cf.png)
![Screenshot 2022-01-23 002457](https://user-images.githubusercontent.com/46172136/150654325-81bef6e4-23a8-4d2f-87b6-3c9f484c04a8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 88064
  cosmetic: 101214
  scriptlet: 19671
  html: 0
listset (total-discarded, last updated): 
  added: 
    TUR-0: 9127-90, 29m
    fanboy-annoyance: 63365-3452, 29m
    ublock-annoyances: 4365-127, 29m
  default: 
    easylist: 63179-20, 29m
    easyprivacy: 26642-22, 29m
    plowe-0: 3676-817, 29m
    ublock-abuse: 76-0, 29m
    ublock-badware: 3775-67, 29m
    ublock-filters: 30224-184, 29m
    ublock-privacy: 194-11, 29m
    ublock-unbreak: 1685-42, 29m
    urlhaus-1: 7623-0, 29m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 935 ms
popupPanel: 
  blocked: 4
```
</details>

**Comment by uBlock-user** [comment]
Caused by Fanboy Annoyances list.

@ryanbr

**Comment by gwarser** [comment]
Another example :

`https://dizipal142.com/film/kovan-2/`
`https://p4jxn.xyz/js/devtools-detector.js`
