### ISSUE TITLE
kinofen.net: detection

### ISSUE THREAD

**Issue by Hyperi0s** [uBlockOrigin/uAssets#11432]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kinofen.net/`

### Category

detection

### Describe the issue

UBO get detected but that web site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/7887634/150651490-97bf411c-c5e9-49df-899d-454ab3cedbde.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 228882
  cosmetic: 282323
  scriptlet: 36110
  html: 711
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61124-5912, 19m
    adguard-mobile: 7131-239, 19m
    adguard-spyware: 25636-1230, 25m
    adguard-spyware-url: 450-3, 25m
    block-lan: 44-0, 25m
    curben-phishing: 8627-4, 25m
    curben-pup: 392-0, 25m
    adguard-annoyance: 49368-4512, 25m
    adguard-social: 15614-28, 25m
    fanboy-thirdparty_social: 69-0, 25m
    fanboy-annoyance: 60063-45087, 25m
    fanboy-cookiemonster: 21720-183, 25m
    fanboy-social: 23149-1089, 25m
    ublock-annoyances: 4374-11, 25m
    dpollock-0: 10346-514, 25m
    mvps-0: 8730-1507, 25m
    ara-0: 2330-0, 13m
    BGR-0: 1116-11, 25m
    CHN-0: 27644-167, 13m
    CZE-0: 777-0, 13m
    [29 lists not shown]: [too many]
  default: 
    ublock-filters: 30775-475, 3d.1h.7m
    ublock-badware: 3728-1, 3d.1h.6m
    ublock-privacy: 187-0, 3d.1h.4m
    ublock-abuse: 76-0, 3d.1h.3m
    ublock-unbreak: 1697-0, 3d.1h.2m
    easylist: 63152-1348, 3d.1h.1m
    easyprivacy: 26637-11129, 3d.1h
    urlhaus-1: 7623-4, 26m
    plowe-0: 3682-2, 2d.2h.14m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3720 ms (selfie)
popupPanel: 
  blocked: 14
```
</details>

**Comment by uBlock-user** [comment]
>  [29 lists not shown]: [too many]

Go back to default lists/settings, you enabled way too many lists.

**Comment by mapx-** [comment]
You have to play a video:

`https://kinofen.net/filmi/3706-race-to-witch-mountain-planinata-na-veschicite-2009.html`

working

```
kinofen.net##+js(set, noAdBlock, true)
kinofen.net##+js(no-fetch-if, adskeeper)
```

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/065d4dc92449b2e622faef6924f8105c47dbd7ff

**Comment by playonevideo** [comment]
On `https://kinofen.cc/los-tigres-tigrite/` if you click the play button, a box (with probably an ad blocked) appears, with a red button underneath. If you click the red button, it opens a new tab:

https://github.com/user-attachments/assets/eb603cd8-fccc-4895-bf1f-24500a6918d2" />
https://github.com/user-attachments/assets/b7128786-9ec2-4cc5-8d61-f1dcc73a2768" />

**Comment by mapx-** [comment]
```adb
kinofen.cc###popup-wrapper
```

@dimisa-RUAdList

**Comment by playonevideo** [comment]
The site is Bulgarian, not Russian.

**Comment by dimisa-RUAdList** [comment]
Oops! This is actually a Bulgarian site.
