### ISSUE TITLE
mail.ukr.net: ads

### ISSUE THREAD

**Issue by TiRums** [uBlockOrigin/uAssets#11430]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.ukr.net/desktop`

### Category

ads

### Describe the issue

add in up of page, 3 blocks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ibb.co/tsDq3v3
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 96709
  cosmetic: 61620
  scriptlet: 18021
  html: 621
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30803-149, 12h.57m
    ublock-badware: 3748-1, 12h.57m
    ublock-privacy: 191-0, 12h.57m
    ublock-abuse: 76-0, 12h.57m
    ublock-unbreak: 1694-0, 12h.57m
    easylist: 63179-459, 12h.57m
    easyprivacy: 26642-489, 12h.57m
    urlhaus-1: 7598-0, 12h.57m
    plowe-0: 3676-2, 12h.57m
    RUS-0: 40816-161, 12h.57m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 389 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by dimisa-RUAdList** [comment]
This is a known [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027).

Use [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor).
