### ISSUE TITLE
titulky.com: detection

### ISSUE THREAD

**Issue by peekaa** [uBlockOrigin/uAssets#11439]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.titulky.com/`

### Category

detection

### Describe the issue

detect ublock with warning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78059
  cosmetic: 40931
  scriptlet: 16668
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30787-149, 1d.12h.28m
    ublock-badware: 3748-1, 1d.12h.26m
    ublock-privacy: 191-0, 1d.12h.25m
    ublock-abuse: 76-0, 1d.12h.24m
    ublock-unbreak: 1698-0, 1d.12h.23m
    easylist: 63179-87, 1d.12h.30m
    easyprivacy: 26642-494, 1d.12h.29m
    plowe-0: 3676-374, 1d.12h.34m
    CZE-0: 777-1, 10h.47m
    urlhaus-1: 6753-0, 10h.46m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 162 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 490 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by bt4ibwem8** [comment]
i think this issue should be re-opened
