### ISSUE TITLE
cvs.com: breakage

### ISSUE THREAD

**Issue by Fices1989** [uBlockOrigin/uAssets#11431]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cvs.com/account/login/`

### Category

breakage

### Describe the issue

CVS.com requires Google analytics to sign in.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78694
  cosmetic: 40589
  scriptlet: 16477
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63178-9, 2d.9h.14m
    easyprivacy: 26641-17, 2d.9h.13m
    plowe-0: 3685-816, 12d.14h.31m
    ublock-abuse: 76-0, 2d.9h.12m
    ublock-badware: 3729-67, 2d.9h.11m
    ublock-filters: 30204-149, 2d.9h.10m
    ublock-privacy: 190-3, 2d.9h.9m
    ublock-unbreak: 1683-39, 2d.9h.8m
    urlhaus-1: 7623-0, 4h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1075 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by uBlock-user** [comment]
> requires Google analytics to sign in

No network request for GA is fired.

**Comment by Procyon-b** [comment]
Using a US proxy, I've created an account, then logged out and logged in again. No problem at all.
And as @uBlock-user wrote, there is no request made to GA.
