### ISSUE TITLE
pn.cgchotbox.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#11438]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pn.cgchotbox.com/?p=39`

### Category

detection

### Describe the issue

Adblock detector

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Screenshot_20220123-101204940](https://user-images.githubusercontent.com/19517680/150663360-258e4589-87f4-4849-8340-a88b404c712a.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium Mobile: 98
filterset (summary): 
  network: 25755
  cosmetic: 58387
  scriptlet: 22242
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1815-9, 2d.1h.31m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 5976-930, 2d.1h.37m
    IDN-0: 9026-3754, 2d.1h.32m
    adguard-annoyance: 49308-1692, 2d.1h.39m
    ublock-annoyances: 4371-161, 2d.14h.9m
  default: 
    adguard-mobile: 7128-45, 2d.1h.38m
    ublock-abuse: 76-0, 2d.1h.36m
    ublock-badware: 3724-4, 2d.1h.35m
    ublock-filters: 30305-657, 2d.1h.34m
    ublock-privacy: 194-1, 2d.1h.33m
    ublock-unbreak: 1729-3, 2d.1h.30m
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1248 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by uBlock-user** [comment]
> Chromium Mobile: 98

How did you install uBO on Chromium 98 ?

**Comment by krystian3w** [comment]
Maybe in Yandex/Kiwi or Ungoogled Chromium.

**Comment by 3xploiton3** [comment]
> > Chromium Mobile: 98
> 
> How did you install uBO on Chromium 98 ?

chrome dev
![image](https://user-images.githubusercontent.com/19517680/150714454-1798adb0-bf35-44df-84fd-c4ffb2d2680d.png)

**Comment by 3xploiton3** [comment]
> > Chromium Mobile: 98
> 
> How did you install uBO on Chromium 98 ?

kiwi browser 
https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en&gl=US

**Comment by uBlock-user** [comment]
Kiwi issue. Kiwi browser also detects and disables uBO selectively, so avoid it.[1]

[1] - https://github.com/kiwibrowser/src/blob/ad4fdb6d6e87d5587e4d9b54c6f159ffa055b67d/extensions/renderer/extension_injection_host.cc#L56
