### ISSUE TITLE
hdrezka.tv: ads

### ISSUE THREAD

**Issue by stfn-ko** [uBlockOrigin/uAssets#11448]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://hdrezka.tv/animation/adventures/36447-ataka-titanov-tv-4-2020.html`

### Category

ads

### Describe the issue

shows video ad when you push the start button. used to block this content before and now it does not for some reason.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 97
filterset (summary): 
  network: 77856
  cosmetic: 40607
  scriptlet: 16477
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 10h.22m
    easyprivacy: 26642-17, 10h.23m
    plowe-0: 3682-816, 8d.5h.37m
    ublock-abuse: 76-0, 10h.20m
    ublock-badware: 3744-67, 6h.17m
    ublock-filters: 30231-149, 10h.21m
    ublock-privacy: 194-3, 6h.16m
    ublock-unbreak: 1687-39, 10h.18m
    urlhaus-1: 6753-0, 1d.1h.40m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 345 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by Procyon-b** [comment]
Subscribe to the regional list "_RUS: RU AdList_"
