### ISSUE TITLE
mesrecettesfaciles.fr: nuisance

### ISSUE THREAD

**Issue by Laurence861** [uBlockOrigin/uAssets#11447]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mesrecettesfaciles.fr/recipe/quiche-aux-carottes-poireaux-et-4-epices?diaporama=9113`

### Category

nuisance

### Describe the issue

Bonjour,
Une fenêtre s'affiche et est compliqué à enlever car le bouton skip n'apparait pas tout de suite : "ajouter mes recettes faciles à Chrome" 
Je n'ai pas répondu honnêtement à tous les points de contrôle ci-dessus car je ne comprends pas tout...
Merci

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/98281149/150693427-a5ec6876-9d10-4dd0-a55d-822cbeb94866.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 93999
  cosmetic: 49763
  scriptlet: 16529
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26133-23, 3d.7h.57m
    easylist: 63179-186, 3d.7h.58m
    easyprivacy: 26642-342, 3d.7h.59m
    plowe-0: 3682-824, 7d.9h.21m
    ublock-abuse: 76-1, 2d.11h.44m
    ublock-badware: 3739-75, 2d.11h.43m
    ublock-filters: 30215-323, 2d.11h.42m
    ublock-privacy: 194-3, 2d.11h.41m
    ublock-unbreak: 1687-39, 2d.11h.45m
    urlhaus-1: 6753-0, 19h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 60 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 588 ms (selfie)
popupPanel: 
  blocked: 27
```
</details>

**Comment by krystian3w** [comment]
HTML5 Pop-up have unlocked scroll so can by blocked by Fanboy Annoyances.

Is diffrence between javascript pop-up opened as Window.

**Comment by mapx-** [comment]
I cannot reproduce the issue, I get no such window / "popup"

just 2 placeholders 

```
mesrecettesfaciles.fr###banniere-haute
mesrecettesfaciles.fr##.col:has(ins.adsbygoogle)
```

**Comment by Procyon-b** [comment]
Tu peux aussi essayer de bloquer ce script:
```
||cdnfiles.azurewebsites.net/cuisine-recettes$script,domain=mesrecettesfaciles.fr
```

**Comment by Laurence861** [comment]
Merci à tous !
En fait, j'ai testé et bloqué : cdnfiles.azurewebsites.net et c'est bon !
Je vous remercie beaucoup de votre aide !
@+

**Comment by Procyon-b** [comment]
Parfait
