### ISSUE TITLE
mathb-ege.sdamgia.ru: ads

### ISSUE THREAD

**Issue by nakigoe** [uBlockOrigin/uAssets#11440]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mathb-ege.sdamgia.ru/`

### Category

ads

### Describe the issue

and this site detects ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled-1](https://user-images.githubusercontent.com/35993388/150670059-5927a489-f59c-41cc-93c2-dabb61351d26.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77857
  cosmetic: 40616
  scriptlet: 16485
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 16h.34m
    easyprivacy: 26642-17, 16h.33m
    plowe-0: 3682-816, 5d.13h.40m
    ublock-abuse: 76-0, 16h.32m
    ublock-badware: 3744-67, 16h.39m
    ublock-filters: 30229-149, 16h.37m
    ublock-privacy: 194-3, 16h.36m
    ublock-unbreak: 1687-39, 16h.35m
    urlhaus-1: 6753-0, 12h.8m
filterset (user): [array of 25 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1038 ms (selfie)
popupPanel: 
  blocked: 22
```
</details>

**Comment by mapx-** [comment]
enable the regional list `RUS: RU AdList`
