### ISSUE TITLE
babymodz.com: detection

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11443]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cutt.ly/jIUDGqg`

### Category

detection

### Describe the issue

1. Page redirects to `babymodz.com`, anti-adblock appears.
2. The captcha is hidden by the filter `##.adsbygoogle`
3. There's a countdown timer at next redirection.
4. At the final redirection page `apkadmin.com`, another countdown timer appears

Proposed filters:

```
babymodz.com#@#.adsbygoogle
babymodz.com##+js(no-fetch-if, googlesyndication)
babymodz.com##+js(nano-sib, timer, , 0.02)
apkadmin.com##+js(nano-stb, tick, , 0.02)
```

### Screenshot(s)

<details>
<summary>Anti-adblock</summary>

![image](https://user-images.githubusercontent.com/66517106/150680543-50590a0d-1a52-4de2-b5bc-93cf3014fea8.png)

</details>

<details>
<summary>Captcha is hidden</summary>

![image](https://user-images.githubusercontent.com/66517106/150680575-d1a9aa4a-f223-43c2-9203-ebae00f7508b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 77936
  cosmetic: 40608
  scriptlet: 16438
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30805-30, 22m
    ublock-badware: 3784-1, 22m
    ublock-privacy: 191-0, 22m
    ublock-abuse: 76-0, 22m
    ublock-unbreak: 1698-0, 22m
    easylist: 63179-587, 22m
    easyprivacy: 26642-480, 21m
    urlhaus-1: 6797-0, 21m
    plowe-0: 3676-2, 21m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 440 ms
popupPanel: 
  blocked: 20
```
</details>

**Comment by stephenhawk8054** [comment]
Same situation for the site `mad.gplpalace.one`

URL:
`https://mad.gplpalace.one/?go=c4681073`

Proposed filter:

```
mad.gplpalace.one##+js(no-fetch-if, googlesyndication)
mad.gplpalace.one##+js(nano-sib, timer, , 0.02)
```

**Comment by uBlock-user** [comment]
> The captcha is hidden by the filter ##.adsbygoogle

Where ?

**Comment by uBlock-user** [comment]
> The captcha is hidden by the filter `##.adsbygoogle`


@stephenhawk8054 `babymodz.com##.g-recaptcha:style(margin-top:55px !important)`

**Comment by Yuki2718** [comment]
> `mad.gplpalace.one##+js(nano-sib, timer, , 0.02)`

BTW we generally omit default values: `mad.gplpalace.one##+js(nano-sib, timer, , 0.02)` => `mad.gplpalace.one##+js(nano-sib, timer)`

**Comment by stephenhawk8054** [comment]
> > `mad.gplpalace.one##+js(nano-sib, timer, , 0.02)`
> 
> BTW we generally omit default values: `mad.gplpalace.one##+js(nano-sib, timer, , 0.02)` => `mad.gplpalace.one##+js(nano-sib, timer)`

Oh I see, tks for your info. I thought default value of last argument is 0.05. Anyways, I think the `cutt.ly` link redirects to this `apkadmin.com` link:
`https://apkadmin.com/fy4rqc02hzee/GAMING_MODE_-_GAME_BOOSTER_PRO_V1.9.0___40_PRO__41_.apk.html`

in which the timer can also be boosted by:

`apkadmin.com##+js(nano-stb, tick)`

**Comment by Yuki2718** [comment]
> I thought default value of last argument is 0.05.

Whoops, you're right. My bad.

> apkadmin.com##+js(nano-stb, tick)

Doesn't work on my end.
