### ISSUE TITLE
hisense.co.uk: breakage

### ISSUE THREAD

**Issue by greentrancer** [uBlockOrigin/uAssets#11445]
### Prerequisites

- [ ] I did not answer truthfully to **all** the above checkpoints
- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)

### URL address of the web page

`https://hisense.co.uk/soundbars/all-soundbars/`

### Category

breakage

### Describe the issue

The page seems to be loading forever with uBlock switched on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-01-23_15-17-30](https://user-images.githubusercontent.com/5639078/150685479-a8ece3b8-c028-47a8-b741-5541cf9f607b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78253
  cosmetic: 40893
  scriptlet: 16440
  html: 616
listset (total-discarded, last updated): 
  added: 
    ROU-1: 753-22, 1d.14h.26m
  default: 
    ublock-filters: 30778-30, 2d.13h.56m
    ublock-badware: 3743-1, 2d.13h.55m
    ublock-privacy: 191-0, 2d.13h.54m
    ublock-abuse: 76-0, 2d.13h.53m
    ublock-unbreak: 1696-0, 2d.13h.51m
    easylist: 63179-593, 2d.13h.50m
    easyprivacy: 26642-494, 2d.13h.49m
    urlhaus-1: 6753-0, 23h.41m
    plowe-0: 3684-2, 10d.21h.45m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3467 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
`@@||analytics-static.ugc.bazaarvoice.com^$script,domain=hisense.co.uk`

@ryanbr

**Comment by krystian3w** [comment]
Geo locked, no have any `bazaarvoice.com` in logger.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8dd3351a44ef0aa5b261cb22f491b244bda1afcc

**Comment by krystian3w** [comment]
Reporter not enabled EasyList Cookie or FA, so can still reproduce issue.
