### ISSUE TITLE
donanimhaber.com: breakage

### ISSUE THREAD

**Issue by ganayem** [uBlockOrigin/uAssets#11446]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.donanimhaber.com/`

### Category

breakage

### Describe the issue

Videos are blank. There is only sound.
When Ublock Origin disabled, no video problem.
Thanks

### Screenshot(s)

<details>
<summary>Screens

hot(s)</summary>

![capture](https://user-images.githubusercontent.com/37334504/150691257-bbb9e98a-c08f-4000-a118-85fda8ca73d0.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79836
  cosmetic: 47264
  scriptlet: 16845
  html: 617
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 4d.8h.1m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30785-29, 2d.21h.39m
    ublock-badware: 3743-1, 2d.21h.37m
    ublock-privacy: 191-0, 1d.9h.20m
    ublock-abuse: 76-0, 1d.9h.19m
    ublock-unbreak: 1694-0, 1d.9h.18m
    easylist: 63179-598, 1d.9h.17m
    easyprivacy: 26642-486, 1d.3h.18m
    plowe-0: 3681-2, 4d.3h.7m
    TUR-0: 9127-104, 1d.9h.16m
    urlhaus-1: 6797-0, 7h.14m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 311 ms (selfie)
popupPanel: 
  blocked: 42
```
</details>

**Comment by Procyon-b** [comment]
Which video in particular?
I've seen 2, one embedded from yt, and this one:
 `https://www.donanimhaber.com/7000-tl-lik-elektrikli-scooter-cybersoul-x3-pro-yu-denedik--144184`
I can see both.

**Comment by mapx-** [comment]
The video in your screenshot is ok, visible

`https://www.donanimhaber.com/philips-in-21-9-luk-ultra-genis-ekranli-monitoru-test-masamizda--143828`

Disable all other addons and test again

**Comment by ganayem** [comment]
Have disabled all other extensions no changes.
But when I disable cosmetic filtering option in UBlock settings I can see
the video.
Thanks for your interest.

mapx- ***@***.***>, 23 Oca 2022 Paz, 21:30 tarihinde şunu
yazdı:

**Comment by Procyon-b** [comment]
You have 22 user filters. Maybe it's one of them.

**Comment by ganayem** [comment]
You are right!
Just disabled user filters and problem solved.
Thank you. I wish you happy new year.

Marc Boucher ***@***.***>, 24 Oca 2022 Pzt, 00:05 tarihinde
şunu yazdı:
