### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by lao-mang** [uBlockOrigin/uAssets#11451]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

не создать фильтр. при выборе элемента в блок кнопка создать не активна.  английский не зна. только русский

### A specific URL where the issue occurs

yandex.ru

### Steps to Reproduce

ищем видео в дзене и ждем рекламу. далее правый клик и заблокоровать. и тут кнопка в всплывшем меню не активна. но ранее работала

### Expected behavior

блок рекламы

### Actual behavior

нет действия

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 86
filterset (summary): 
  network: 95673
  cosmetic: 61626
  scriptlet: 18054
  html: 0
listset (total-discarded, last updated): 
  default: 
    RUS-0: 40834-9, 14h.49m
    easylist: 63179-27, 2d.16h.14m
    easyprivacy: 26642-113, 2d.16h.13m
    plowe-0: 3676-821, 2d.16h.12m
    ublock-abuse: 76-1, 2d.16h.10m
    ublock-badware: 3739-67, 2d.16h.8m
    ublock-filters: 30208-181, 2d.16h.7m
    ublock-privacy: 194-3, 2d.16h.6m
    ublock-unbreak: 1685-39, 2d.16h.5m
    urlhaus-1: 6565-0, 14h.48m
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7365 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11137#issuecomment-1002997373

**Comment by dimisa-RUAdList** [comment]
@lao-mang 
GitHub only uses English, so it would be better if you describe the problem here: `https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&glp#lt`

`На гитхабе используется только английский язык, поэтому будет лучше, если вы опишите проблему здесь: https://forum.ru-board.com/topic.cgi?forum=5&topic=50761&glp#lt`
