### ISSUE TITLE
[NSFW] gelbooru.com

### ISSUE THREAD

**Issue by supas** [uBlockOrigin/uAssets#1145]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=list&tags=all`
`https://gelbooru.com/index.php?page=post&s=view&id=3007965`

### Describe the issue

Ads

### Screenshot(s)

https://kek.gg/i/MrWQ3.png
https://kek.gg/i/KfmqJ.png

### Versions

- Browser/version: 63.0.3239.108
- uBlock Origin version: 1.14.22

### Settings

- default settings

**Comment by gorhill** [comment]
Seems to be caused by `@@||gelbooru.com^$first-party,script`, I can't remember why this was added.

Does `@@||gelbooru.com^$first-party,script,badfilter` work, and if so does it break anything on the site?

**Comment by gorhill** [comment]
Well whatever the outcome, that filter had to go, so I removed it. There are still ads left though, a banner at the top, this still need to be investigated.

**Comment by nimasaj** [comment]
Do these help?
```
gelbooru.com##div[style^="max-width: 728px; overflow: hidden;"]
gelbooru.com##img[src*="gelbooru.com/bluet.php"]
```

**Comment by mapx-** [comment]
updating easylist, these filters seems working fine:
```
|https://$script,domain=gelbooru.com,badfilter
gelbooru.com##script:inject(abort-on-property-read.js, fuckingnormieswryyyyyy)
```

**Comment by okiehsch** [comment]
The removal of the exception filter has broken the thumbnail preview function, so atleast adding
`|https://$script,domain=gelbooru.com,badfilter` is neccessary.

`gelbooru.com##script:inject(abort-on-property-read.js, fuckingnormieswryyyyyy)`
works, you could also add
````
gelbooru.com##a[href^="https://media.r18.com/"]
gelbooru.com##a[href^="https://gelbooru.com/redirect.php"]
````

**Comment by okiehsch** [comment]
I will add the filters, because the first reports of people panicking because they can't see any thumbnail previews have surfaced :).
