### ISSUE TITLE
profit.ro: breakage

### ISSUE THREAD

**Issue by valenting** [uBlockOrigin/uAssets#11450]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.profit.ro/povesti-cu-profit/farma/al-treilea-de-caz-de-infectare-covid-la-jucatori-participanti-la-australian-open-alyson-van-uytvanck-nr-55-mondial-testata-pozitiv-dupa-ce-a-jucat-in-turneu-20567894`

### Category

breakage

### Describe the issue

content flashes on screen then quickly disappears. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1454649/150776563-321a9ec8-777a-491b-a9be-8cbd4331a4d2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 98
filterset (summary): 
  network: 77731
  cosmetic: 40626
  scriptlet: 16434
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30817-30, 8h.21m
    ublock-badware: 3805-1, 8h.20m
    ublock-privacy: 191-0, 8h.19m
    ublock-abuse: 76-0, 8h.18m
    ublock-unbreak: 1699-0, 8h.17m
    easylist: 63179-586, 8h.16m
    easyprivacy: 26642-480, 8h.15m
    urlhaus-1: 6565-0, 20h.22m
    plowe-0: 3682-2, 8d.12h.27m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 850 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
@ryanbr EP issue

**Comment by stephenhawk8054** [comment]
I think this can be fixed by

```adb
profit.ro##.zc_top_mobil:style(display: block !important;)
```

without the need to allow the scripts.
