### ISSUE TITLE
anti adb https://www.arcai.com/

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#11452]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.arcai.com/netCut/s/`

### Describe the issue

Can someone fix this?
The issue is when we about to block or limit something, we need to disable adblock (atlest the ads shown)

when ublock on.. we can't turn anything wheter on or off...

And keep in mind... that **the site can only be used when the app bellow is installed**

`https://arcai.com/download/netcut.exe`

the adblock notification will only shown few minutes after we scan or change setting on first few minutes.
so... umm does this possible to be bypassed on ublock also? or no...?

last time i use netcut is when i on highschool... now i used it again... it seems that they now use browser only to setting something and forcing the users to see the ads to using the services.... so i really wonder is this type of sites can by bypassed by ublock or not...

Thanks... let me know if someone need more info
and sorry for my bad explanation and bad english XD

### Screenshot(s)

https://user-images.githubusercontent.com/29838157/150781933-90580767-e2f3-4d77-a6d8-444d19432522.png

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by mapx-** [comment]
It would be difficult to find help to fix the issue because of the app that needs to be installed, so probably you should whitelist that site.

**Comment by Dhanamerdeka** [comment]
> It would be difficult to find help to fix the issue because of the app that needs to be installed, so probably you should whitelist that site.

ahh ok understand
thanks btw :)

**Comment by uBlock-user** [comment]
```
arcai.com#@#.adsbox
arcai.com##+js(set, canRunAds, true)
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_*.js$domain=arcai.com
```

@Dhanamerdeka add those and test

**Comment by Dhanamerdeka** [comment]
> doubleclick

thanks :) i will test when i back home soon
