### ISSUE TITLE
sephora.com: breakage

### ISSUE THREAD

**Issue by sheilamporter** [uBlockOrigin/uAssets#11458]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sephora.com/profile/MyAccount`

### Category

breakage

### Describe the issue

Page contents do not load on many personalized/account-based pages when uBlock Origin is enabled. The header/footer/sidebars/titles/etc all load, but the actual contents are missing. Disabling uBlock Origin and refreshing the page fixes the issue.

Additionally, when trying to log in to my account when uBlock Origin is enabled and the "Keep me signed in" checkbox is on, nothing seems to happen. I need to either disable uBlock Origin or uncheck "Keep me signed in" and then I can log in successfully.

Here is a list of all the pages I personally found issues with, but I wouldn't be surprised if they are more, and I'm assuming (hoping) they all share the same root cause.

```
* https://www.sephora.com/profile/MyAccount
* https://www.sephora.com/profile/MyAccount/Orders
* https://www.sephora.com/profile/MyAccount/Subscriptions
* https://www.sephora.com/profile/MyAccount/Addresses
* https://www.sephora.com/profile/MyAccount/PaymentMethods
* https://www.sephora.com/profile/MyAccount/EmailPostal
* https://www.sephora.com/happening/reservations
```

Thank you!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

"Account Information" page with uBlock Origin **enabled**
![Screen Shot 2022-01-24 at 4 42 38 PM](https://user-images.githubusercontent.com/1117949/150869800-e3ecaab7-ca36-4533-b14d-0fcdf5141bff.png)

"Account Information" page with uBlock Origin **disabled** (personal info censored with purple rectangles)
![Screen Shot 2022-01-24 at 4 44 31 PM](https://user-images.githubusercontent.com/1117949/150870149-d4643663-59a6-4ec7-95ba-5e407a655a82.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 78151
  cosmetic: 40672
  scriptlet: 16440
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30829-30, 1m
    ublock-badware: 3805-1, 1m
    ublock-privacy: 192-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1705-0, 1m
    easylist: 63358-591, 1m
    easyprivacy: 26659-480, 1m
    urlhaus-1: 6832-0, 1m
    plowe-0: 3678-2, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 121235 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by mapx-** [comment]
test this filter

`@@||sephora.com/js/ufe/isomorphic/thirdparty/fp.min.js$script,1p`
