### ISSUE TITLE
[NSFW] websites with ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#11453]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://thotshub.tv/second/`

`https://only4leaked.com/onlyfans/profile/unavips`

### Describe the issue

On thotshub.tv, there is a notification (with a girl that want to chat) after I enter the website.

On only4leaked, when I press on "Download Leaked Files" I need to complete one task. Maybe somehow can be bypassed this task.

### Screenshot(s)

For thotshub
![screen](https://user-images.githubusercontent.com/86512304/150784854-54afca96-52c8-428e-b4cd-da22927545dd.jpg)

For only4leaked
![screen02](https://user-images.githubusercontent.com/86512304/150784878-9aea0d5a-8ce5-465a-ad49-6d2eff3b51b6.jpg)

### uBlock Origin version

1.40.8

### Browser name and version

FIrefox 96.0.2

### Settings

Default settings uBlock

**Comment by mapx-** [comment]
- for the first add:
`||dating-universe.top^$3p`

@ryanbr
