### ISSUE TITLE
apc-pli.com: breakage

### ISSUE THREAD

**Issue by cjohnsto-nz** [uBlockOrigin/uAssets#11454]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.apc-pli.com/apc-tracking-v2.html?id=BGYA191106`

### Category

breakage

### Describe the issue

Courier tracking. No ads as far as I can see. Does not work with adblock enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77921
  cosmetic: 40596
  scriptlet: 16477
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 3d.9h.43m
    easyprivacy: 26642-17, 3d.9h.42m
    plowe-0: 3684-816, 11d.10h.13m
    ublock-abuse: 76-0, 3d.9h.40m
    ublock-badware: 3739-67, 3d.9h.39m
    ublock-filters: 30211-149, 3d.9h.37m
    ublock-privacy: 194-3, 3d.9h.38m
    ublock-unbreak: 1685-39, 3d.9h.36m
    urlhaus-1: 6832-0, 2h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 213 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
Does this filter works ?

`@@||apc-pli.com/api/tracking/$xhr,1p`

**Comment by uBlock-user** [comment]
@ryanbr
