### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by NikaOokami** [uBlockOrigin/uAssets#11457]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.deezer.com/`

### Category

breakage

### Describe the issue

The player stops after one track (instead of playing a audio ad) and don't works after that. I had to refresh the page, but once again, after one track, the crash is back ... I think it's happening when a ad is supposed to begin, the Ublock stop it but don't let the next track begin. And it is impossible to move to the next track, even by clicking. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 94359
  cosmetic: 49836
  scriptlet: 16524
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26092-23, 52m
    easylist: 63349-70, 49m
    easyprivacy: 26659-342, 48m
    plowe-0: 3678-824, 46m
    ublock-abuse: 76-1, 44m
    ublock-badware: 3801-77, 42m
    ublock-filters: 30243-325, 41m
    ublock-privacy: 194-3, 40m
    ublock-unbreak: 1694-39, 39m
    urlhaus-1: 6832-0, 38m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1198 ms
popupPanel: 
  blocked: 8
```
</details>

**Comment by Procyon-b** [comment]
Désolé, so far I'm unable to reproduce you problem. Tracks are played one after another.
Are you using other ad-blocking extensions? Or userscripts?
There is also the possibility that I potentially receive less ads (I'm in Europe) and haven't fell in the trap yet.

**Comment by mapx-** [comment]
I was able to reproduce the issue, maybe a little more when I used a us ip

@NikaOokami : add these filters and test

```
@@||ced.sascdn.com/tag/400/smart.js$script,domain=deezer.com
@@||smartadserver.com/400/call$xhr,domain=deezer.com
```

**Comment by someboodyh** [comment]
blabla yeah yeah, i am very fine

**Comment by mapx-** [comment]
maybe some change on their side, today I can listen only a preview on any song (30 seconds) even disabling uBO

**Comment by NikaOokami** [comment]
Hello everyone, thank you for your answers =)

@Procyon-b : No other ad-blocking extensions, or userscripts, I had another ad blocker before and it worked very well until yesterday (now it doen't block anything on deezer). I deleted it and thanks to a friend's advice I use only Ublock Origin now. Then, this is very new for me and I didn't add any script.

But ....

@mapx- : I tried your filters, clean my cache and restart google chrome and after some tracks it seems to be working well =)  I had a strange issue once, a track restart when I cliked on the deezer tab but nothing very annoying (And it happened just once, when deezer was playing the first track of the "flow" list). The media controls of deezer works well too, I can skip the tracks now ! 

Indeed It seems deezer do something against ad blockers, but the scripts seems to be working well for me for now =) I'll try again still a little longer and I'll back to you for a feedback. 

Thank you very much to all of you 👍  :

**Comment by NikaOokami** [comment]
![cats](https://user-images.githubusercontent.com/98355643/151001111-a63a62bc-3c7c-410b-befb-13b6b1d6e224.jpg)

A little update for this. "requested content cannot be loaded" (I was listening the "flow" list on deezer and it's happened after some 45 min, something like this). After cliking "retry" It works again. Just a little issue, but once again, it is not very annoying. 

It's ok for me =)

**Comment by garry-ut99** [comment]
There is another breakage: an error occurs when trying to listen to "RMC Info Talk Sport" radio.
Responsible filter: `||adswizz.com^$3p` from EasyList & uBO Unbreak
Example fix: `@@||nextregie-cloudfront.streaming.adswizz.com^$3p,media,domain=deezer.com`

![Schowek26](https://user-images.githubusercontent.com/72945564/214966727-38f79def-4a75-4c7e-8b7c-9c6111eb6203.png)

![hhhhh](https://user-images.githubusercontent.com/72945564/214967218-d0e4b190-a1a2-46d5-a080-058ff79a490b.png)

**Comment by morrinson** [comment]
Hello, over the the past few days, uBlock has been preventing tracks from playing on Deezer.
Sometimes a song can be played (after a random number of page refresh) but player gets stuck afterward.

With latest Firefox.

**Comment by stephenhawk8054** [comment]
@morrinson Can you test this filter:

```adb
deezer.com##+js(trusted-json-edit, ..ads_audio=false)
```

Go to uBO's settings > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > **Turn on `Allow custom filters requiring trust`** > ✓ Apply changes > Open new tab and test again.

**Comment by morrinson** [comment]
Thanks for the reply.
The problem disappeared after deleting all the related cookies, so I cannot reproduced it right now. But I'll test this filter as soon as it gets back an will let you know.
