### ISSUE TITLE
woolworths.co.za: breakage

### ISSUE THREAD

**Issue by MichaelDuivestein** [uBlockOrigin/uAssets#11456]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.woolworths.co.za/`

### Category

breakage

### Describe the issue

Site starts to load, then crashes (blank page). Personally tested on Firefox and Chrome on Linux and Mac. 

Had other people around ZA verify that it wasn't working on their machines when uBlock was enabled and worked when uBlock was disabled.

Given that it was replicated by multiple people, I skipped the following step:
`I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules *`

Console stacktrace:
```
Uncaught (in promise) TypeError: window.dataLayer[b] is undefined
    n https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:3
    l https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:6
    c https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:6
    ue https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:13
    c https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:3
    n https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:3
    r https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:58
    dispatch https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:6
    tagPromotionImpressions https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:1
    r https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:58
    f https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:6
    value https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:1
    t https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:1
    pn https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    ur https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Ls https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:36
    to https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Jr https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    zr https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Ur https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Po https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Io https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Vr https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    Io https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:28
    render https://www.woolworths.co.za/assets/7065488ef011a5796552.vendor.js?v=0.0.1:36
    <anonymous> https://www.woolworths.co.za/assets/a92856fad47141de5cac.js?v=0.0.1:3

```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 77924
  cosmetic: 40768
  scriptlet: 16447
  html: 617
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    ublock-filters: 30803-30, 1d.4h.20m
    ublock-badware: 3748-1, 1d.4h.23m
    ublock-privacy: 191-0, 1d.4h.21m
    ublock-abuse: 76-0, 1d.4h.19m
    ublock-unbreak: 1695-0, 1d.4h.18m
    easylist: 63179-587, 1d.6h.53m
    easyprivacy: 26642-480, 1d.4h.24m
    plowe-0: 3684-2, 11d.6h.14m
    urlhaus-1: 6797-0, 1d.4h.17m
filterset (user): [array of 195 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2073 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by uBlock-user** [comment]
@gorhill
