### ISSUE TITLE
[nsfw] rockmods.net: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#11461]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rockmods.net/2019/12/MXPlayer.html?m=1`

### Category

detection

### Describe the issue

Adblock detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Uploading Screenshot_20220125-163135488.jpg…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium Mobile: 98
filterset (summary): 
  network: 25834
  cosmetic: 58527
  scriptlet: 22266
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1821-9, 5h.34m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 5995-952, 5h.41m
    IDN-0: 9030-3754, 5h.35m
    adguard-annoyance: 49446-1694, 5h.43m
    ublock-annoyances: 4385-167, 16h.16m
  default: 
    adguard-mobile: 7136-45, 5h.42m
    ublock-abuse: 76-0, 5h.40m
    ublock-badware: 3801-4, 5h.39m
    ublock-filters: 30349-660, 5h.37m
    ublock-privacy: 195-1, 5h.36m
    ublock-unbreak: 1694-3, 5h.32m
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1847 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by uBlock-user** [comment]
Links are being changed though with inline js - `rockmods.net##+js(acis, String.prototype.charCodeAt, protected_links)`
