### ISSUE TITLE
repubblica.it: ads

### ISSUE THREAD

**Issue by Nemomnis** [uBlockOrigin/uAssets#11468]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.repubblica.it/`

### Category

ads

### Describe the issue

The "MyMovies" banner pops up every time the page is refreshed, no matter the inclusion of the specific filters in uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78439
  cosmetic: 40625
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ITA-0: null
  default: 
    easylist: 63179-9, 3d.2h.16m
    easyprivacy: 26642-17, 3d.2h.17m
    plowe-0: 3681-816, 6d.17h.53m
    ublock-abuse: 76-0, 1d.17h.50m
    ublock-badware: 3801-67, 1d.21h.53m
    ublock-filters: 30245-148, 1d.21h.52m
    ublock-privacy: 194-3, 3d.2h.19m
    ublock-unbreak: 1687-39, 3d.2h.18m
    urlhaus-1: 7282-0, 21h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 810 ms (selfie)
popupPanel: 
  blocked: 51
```
</details>

**Comment by mapx-** [comment]
enable again the regional list
`ITA: EasyList Italy`
