### ISSUE TITLE
paidcoursesforfree.com: breakage

### ISSUE THREAD

**Issue by pmg1991** [uBlockOrigin/uAssets#11463]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://paidcoursesforfree.com/spring-boot-e-commerce-ultimate-course/`

### Category

breakage

### Describe the issue

Content not showing , Ublock is removing content with ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ublock enabled
![image](https://user-images.githubusercontent.com/34839986/150975700-f070f2f7-f4bc-4309-9b7b-2f5b0f6c8347.png)

with ublock disabled

![image](https://user-images.githubusercontent.com/34839986/150975842-0ac5c601-9d01-4efa-9077-53fa15c7927e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 78156
  cosmetic: 40684
  scriptlet: 16481
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63364-9, 1m
    easyprivacy: 26666-17, 1m
    plowe-0: 3679-816, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 3801-69, 1m
    ublock-filters: 30258-151, now
    ublock-privacy: 197-3, now
    ublock-unbreak: 1695-39, now
    urlhaus-1: 6832-0, now
filterset (user): [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 380 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
````
paidcoursesforfree.com#@#.bsac
paidcoursesforfree.com#@#.bsac-container
````
