### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by Dpit33** [uBlockOrigin/uAssets#11460]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.deezer.com/`

### Category

breakage

### Describe the issue

Previously sound ads were correctly blocked and songs continued correctly

From now on, the songs do not follow one another. we can no longer use deezer

good luck

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 94153
  cosmetic: 49807
  scriptlet: 16489
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30824-205, 19h.39m
    ublock-badware: 3733-1, 3d.20h.54m
    ublock-privacy: 191-0, 19h.40m
    ublock-unbreak: 1696-0, 23h.46m
    easylist: 63179-641, 19h.41m
    easyprivacy: 26642-480, 23h.44m
    plowe-0: 3682-2, 6d.19h.1m
    FRA-0: 26092-365, 23h.45m
    ublock-abuse: 76-0, 19h.42m
    urlhaus-1: 6832-0, 23h.43m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 9499 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/11457

test the filters in that thread:
https://github.com/uBlockOrigin/uAssets/issues/11457#issuecomment-1020575905
