### ISSUE TITLE
manga1001.com: detection

### ISSUE THREAD

**Issue by whocares1** [uBlockOrigin/uAssets#11465]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manga1001.com/%e3%80%90%e7%ac%ac37%e8%a9%b1%e3%80%91%e9%99%b0%e3%81%ae%e5%ae%9f%e5%8a%9b%e8%80%85%e3%81%ab%e3%81%aa%e3%82%8a%e3%81%9f%e3%81%8f%e3%81%a6%ef%bc%81-raw/`

### Category

detection

### Describe the issue

I'm not a expert in the subject, but from what I could tell from inspecting the element, it detects a block on realsrv.com, and every image after the first page is replaced with a loading image. 
But the actual pages are still there, only moved to a different location "data-src", as opposed to "src"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 227188
  cosmetic: 180764
  scriptlet: 34126
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.14m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 3d.3h.42m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5357-12, 3d.3h.42m
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-14, 3d.3h.42m
    ALB-0: 254-0, 1d.13m
    BGR-0: 1116-11, 3d.3h.44m
    CHN-0: 27642-88, 3d.3h.44m
    CZE-0: 776-0, 1d.12m
    DEU-0: 5280-1, 1d.11m
    EST-0: 444-5, 1d.10m
    FIN-0: 1512-1, 3d.3h.43m
    FRA-0: 26092-76, 3d.3h.43m
    GRC-0: 1002-3, 1d.18m
    HUN-0: 2164-12, 1d.9m
    IDN-0: 9027-29, 3d.3h.43m
    IRN-0: 1340-7, 3d.3h.43m
    ISL-0: 193-1, 3d.3h.43m
    ISR-0: 1616-4, 1d.8m
    ITA-0: 12735-96, 1d.7m
    JPN-1: 5789-16, 3d.3h.43m
    [25 lists not shown]: [too many]
  default: 
    easylist: 63179-2031, 3d.3h.42m
    easyprivacy: 26642-11099, 3d.3h.42m
    plowe-0: 3676-1534, 3d.3h.42m
    ublock-abuse: 76-65, 3d.3h.42m
    ublock-badware: 3744-232, 3d.3h.42m
    ublock-filters: 30236-3384, 3d.3h.42m
    ublock-privacy: 194-64, 3d.3h.42m
    ublock-unbreak: 1684-126, 3d.3h.42m
    urlhaus-1: 6585-6, 1d
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 9 redacted]
hostRuleset: 
  added: [array of 210 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5008 ms (selfie)
popupPanel: 
  blocked: 8
  no-popups: true
```
</details>

**Comment by uBlock-user** [comment]
Test on default lists/settings.

**Comment by whocares1** [comment]
oh. 
I don't know what happened, but it works now.
sorry for the trouble.
