### ISSUE TITLE
beta.crunchyroll.com: breakage

### ISSUE THREAD

**Issue by Rashify** [uBlockOrigin/uAssets#11467]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://beta.crunchyroll.com/`

### Category

breakage

### Describe the issue

The website is all black when uBock Origin is on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<![image](https://user-images.githubusercontent.com/98277317/151115795-4e4269f8-3d7b-4022-a1b6-c0419aa98c30.png)>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 150541
  cosmetic: 127774
  scriptlet: 32931
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 49500-1675, 1m
    adguard-generic: 61276-1039, 1m
    adguard-mobile: 7138-65, 1m
    adguard-social: 15654-1835, 1m
    adguard-spyware: 28230-892, 1m
    adguard-spyware-url: 454-12, 1m
    block-lan: 44-0, 1m
    curben-phishing: 9043-0, 1m
    curben-pup: 397-0, 1m
    dpollock-0: 10346-237, 1m
    fanboy-annoyance: 63560-35832, 1m
    fanboy-cookiemonster: 21895-21895, 1m
    fanboy-social: 23160-23160, 1m
    fanboy-thirdparty_social: 68-21, 1m
    mvps-0: 8730-1754, 1m
    ublock-annoyances: 4365-299, 1m
  default: 
    easylist: 63409-24834, 1m
    easyprivacy: 26668-10688, 1m
    plowe-0: 3679-1493, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 3801-214, 1m
    ublock-filters: 30268-3547, 1m
    ublock-privacy: 196-38, 1m
    ublock-unbreak: 1696-109, 1m
    urlhaus-1: 7417-4, 1m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 828 ms (selfie)
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
```
</details>

**Comment by uBlock-user** [comment]
Test on default lists/settings.

**Comment by Kuchiha** [comment]
Hello, 
Add this rule in your personal filters :
`@@||c.evidon.com/sitenotice/evidon-sitenotice-tag.js$script,domain=beta.crunchyroll.com`
