### ISSUE TITLE
genesis.malwarebytes.com: privacy

### ISSUE THREAD

**Issue by toineenzo** [uBlockOrigin/uAssets#11466]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

The following domain should be blocked in default privacy lists as it collects your ip/address and gives it a JSON for fingerprint: `https://genesis.malwarebytes.com/api/v1/wai.gif`

### Category

privacy

### Describe the issue

The link ("https://genesis.malwarebytes.com/api/v1/wai.gif") should be blocked as it loads sneakily on all webpages on malwarebytes which links a json fingerprint to your pc which can be used for tracking.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Schermafbeelding 2022-01-26 055920](https://user-images.githubusercontent.com/4921397/151106512-f526c610-f28a-49d1-b4ea-8dee5f171ec3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 122871
  cosmetic: 76389
  scriptlet: 27423
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61190-664, 1d.13h.39m
    adguard-mobile: 7134-46, 1d.13h.40m
    block-lan: 44-0, 6d.3h.49m
    curben-phishing: 8854-0, 12h.14m
    curben-pup: 392-0, 8h.13m
    dpollock-0: 10346-103, 6d.3h.47m
    mvps-0: 8730-1682, 6d.3h.48m
  default: 
    NLD-0: 2057-12, 12h.15m
    easylist: 63312-1211, 1d.13h.43m
    easyprivacy: 26659-269, 1d.13h.42m
    plowe-0: 3681-1457, 6d.12h.6m
    ublock-abuse: 76-0, 1d.13h.41m
    ublock-badware: 3801-211, 1d.13h.37m
    ublock-filters: 30229-3052, 1d.13h.36m
    ublock-privacy: 194-4, 1d.13h.35m
    ublock-unbreak: 1693-107, 1d.13h.34m
    urlhaus-1: 7282-4, 12h.13m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 511 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
