### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by lucellent** [uBlockOrigin/uAssets#11474]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/feed/explore`

### Category

breakage

### Describe the issue

For some reason, since a few days I cannot see any videos on the Explore page. Only when I disable uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77747
  cosmetic: 40637
  scriptlet: 16473
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 3d.10h.47m
    easyprivacy: 26642-17, 3d.10h.48m
    plowe-0: 3681-816, 6d.14h.40m
    ublock-abuse: 76-0, 1d.36m
    ublock-badware: 3801-67, 1d.35m
    ublock-filters: 30243-148, 1d.34m
    ublock-privacy: 195-3, 1d.33m
    ublock-unbreak: 1694-39, 1d.32m
    urlhaus-1: 6585-0, 1d.31m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 223 ms (selfie)
popupPanel: 
  blocked: 10
```
</details>

**Comment by gwarser** [comment]
Do you have `###dismissible` in My filters? Or maybe something else related to YT?

**Comment by lucellent** [comment]
That's odd. I usually do have some YT related stuff but I tried disabling them prior to posting this issue, and it didn't work. Now I disabled them again and seems that the explore videos are back...
They are filters to remove filler stuff when searching for videos (anything not related to the search)

Not sure if it would help at all, but here they are

youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/Related to your search/i))
youtube.com##ytd-shelf-renderer:has-text(/People also watched/)
youtube.com###contents > ytd-shelf-renderer:has-text(/For you/)
youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/Watch again/i))
youtube.com##ytd-horizontal-card-list-renderer.ytd-item-section-renderer.style-scope:has(span:has-text(/Searches related to/i))
youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/Learn while you're at home/i))
youtube.com##ytd-horizontal-card-list-renderer.ytd-item-section-renderer.style-scope
youtube.com###secondary > .ytd-two-column-search-results-renderer
youtube.com###contents > .ytd-secondary-search-container-renderer.style-scope
youtube.com##ytd-shelf-renderer:has-text(/Previously watched/)
