### ISSUE TITLE
[nsfw] javtiful.com: detection

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11479]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://javtiful.com/video/8263/jul-381-plump-tight-clothes-sex-with-the-wife-of-the-boss-who-unconsciously-provokes-me`

### Category

detection

### Describe the issue

adblock detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Uploading image.png…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 66895
  cosmetic: 94095
  scriptlet: 33659
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1815-9, 3d.22h.31m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6005-3, 3d.22h.31m
    IDN-0: 9027-206, 3d.22h.32m
    adguard-annoyance: 49378-169, 3d.22h.31m
    adguard-generic: 61134-820, 3d.22h.31m
    adguard-mobile: 7131-57, 3d.22h.31m
    adguard-spyware: 25636-779, 3d.22h.31m
    ublock-annoyances: 4365-190, 3d.22h.31m
  default: 
    ublock-abuse: 76-0, 3d.22h.31m
    ublock-badware: 3780-150, 3d.22h.31m
    ublock-filters: 30229-3291, 3d.22h.31m
    ublock-privacy: 194-27, 3d.22h.31m
    ublock-unbreak: 1687-86, 3d.22h.31m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
  suspendTabsUntilReady: false
supportStats: 
  launchToReadiness: 967 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
no detection, I added a filter killing some popups

https://github.com/uBlockOrigin/uAssets/commit/5f8922ace60c3d68aeab413e8b41badd9ee042b3

Test using the default settings
