### ISSUE TITLE
Ads warning on Flightradar24.com

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1147]
### URL(s) where the issue occurs

`https://www.flightradar24.com`

### Describe the issue

Bottom right panel is giving a warning regarding Adblocker

### Versions

- Browser/version: Chrome 63
- uBlock Origin version: v1.14.22

### Notes
it could be gone by following rule, but I'd like to know if there is a way to block it using script:inject(...).
`www.flightradar24.com##*[id="responsiveBottomPanel"]`

This part of the page source/inline script:

```
dispatcher.userFeatures = {"map.tracking.live":"enabled","map.data.ads-b":"enabled","map.data.mlat":"enabled","map.data.faa":"enabled","map.data.satellite":"enabled","map.data.flarm":"enabled","map.info.flight":"limited","map.info.aircraft":"limited","history.playback.global.days":7,"history.flight.days":7,"map.info.airport.onground.hours":1,"map.labels.rows":1,"map.filters.max":1,"map.data.delaystats":"enabled","adverts":"enabled","map.timeout.mins":30,"map.info.airport.arrivals":"enabled","map.info.airport.departures":"enabled","map.layer.waypoints":"enabled","map.search":"enabled","map.status.flight":"enabled","map.layer.weather.volcano":"enabled","map.view.multi":"enabled","user.fleets.max":3,"map.view.delay":"enabled","history.aircraft.days":7,"map.info.aircraft.registration":"enabled","map.info.aircraft.type":"enabled","map.info.aircraft.code":"enabled","history.playback.flight.days":7,"history.playback.days":7,"map.info.flight.ground-speed":"enabled","map.info.flight.calibrated-altitude":"enabled","map.info.flight.track":"enabled","map.info.flight.position":"enabled","map.view.fleet.onground":1,"user.fleets.max.aircraft":1000,"map.view.3d.basic":3};
--
  | dispatcher.adverts = {"dfp":{"map_banner":false,"plane_info":false,"map_square":false}};  var timeServer = 1514726220000;
  |  
  | timeLocal = new Date();
  | var millDiff = timeLocal - timeServer;
  |  
  | function timeTick() {
  | timeLocal = new Date();
  | timeLocal.setMilliseconds(timeLocal.getMilliseconds() - millDiff);
```

Thanks
Happy new year

**Comment by nimasaj** [comment]
@mapx- Could you please explain where `googletag` is coming from in the following rule?
`flightradar24.com##script:inject(abort-on-property-write.js, googletag)`

**Comment by mapx-** [comment]
see `https://www.flightradar24.com/static/js/business.js`

**Comment by gorhill** [comment]
@mapx- `googletag` is already neutered by the redirect to local `googletagservices.com/gpt.js` on that page. Given this, is your scriptlet really needed?

**Comment by mapx-** [comment]
- disable "ublock filters", refresh the page => the warning message wil be loaded
- add `flightradar24.com##script:inject(abort-on-property-write.js, googletag)` => you'll see only the placeholder
- the cosmetic filter is only to remove the placeholder (where first were displayed the regular ads)
