### ISSUE TITLE
gopractice.ru: breakage

### ISSUE THREAD

**Issue by lib-lab** [uBlockOrigin/uAssets#11472]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gopractice.ru/unit-economics/`

### Category

breakage

### Describe the issue

blocked subscription form 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 96664
  cosmetic: 61697
  scriptlet: 18023
  html: 621
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30803-30, 3d.21h.16m
    ublock-badware: 3805-1, 1d.2h.3m
    ublock-privacy: 194-0, 1d.2h.2m
    ublock-abuse: 76-0, 1d.2h.1m
    ublock-unbreak: 1705-0, 1d.2h
    easylist: 63403-592, 21h.25m
    easyprivacy: 26670-481, 6h.23m
    urlhaus-1: 7282-0, 1d.1h.59m
    plowe-0: 3676-2, 3d.21h.17m
    RUS-0: 40847-161, 1d.20h.52m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3418 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

maybe you could replace 

`||sumo.com^$third-party`

with 
`||sumo.com/api/event`
