### ISSUE TITLE
infyspringboard.onwingspan.com: breakage

### ISSUE THREAD

**Issue by Ritesh-C07** [uBlockOrigin/uAssets#11471]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://infyspringboard.onwingspan.com/en/app/setup/home/minor-check?ref=%2Fpage%2Fhome`

### Category

breakage

### Describe the issue

it is showing This service is not available in your country

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78417
  cosmetic: 40605
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63179-9, 4d.2h.44m
    easyprivacy: 26642-17, 4d.2h.43m
    plowe-0: 3682-816, 8d.2h.44m
    ublock-abuse: 76-0, 4d.2h.42m
    ublock-badware: 3780-67, 3d.4h.32m
    ublock-filters: 30230-149, 3d.4h.31m
    ublock-privacy: 194-3, 3d.4h.30m
    ublock-unbreak: 1684-39, 3d.4h.28m
    urlhaus-1: 7282-0, 20h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 222 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by uBlock-user** [comment]
`@@||cloudflare.com/cdn-cgi/trace$xhr,domain=infyspringboard.onwingspan.com`

@ryanbr
