### ISSUE TITLE
bestdizi.com: ads

### ISSUE THREAD

**Issue by HakkiFarukErdemir** [uBlockOrigin/uAssets#11486]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bestdizi.com/dizietiket/i-bought-boyfriend-with-loan-izle`

### Category

ads

### Describe the issue

not blocking ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 98
filterset (summary): 
  network: 80415
  cosmetic: 47060
  scriptlet: 16753
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30802-42, 4d.1h.41m
    ublock-badware: 3779-1, 4d.1h.30m
    ublock-privacy: 191-0, 4d.1h.29m
    ublock-abuse: 76-0, 3d.23h.59m
    ublock-unbreak: 1698-0, 3d.23h.58m
    easylist: 63179-598, 3d.23h.57m
    easyprivacy: 26642-485, 3d.23h.56m
    urlhaus-1: 7417-0, 1d.1h.33m
    plowe-0: 3682-2, 12d.5h.1m
    TUR-0: 8741-91, 2d.16h.30m
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 558 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
`bestdizi.com##.nhreklam`

turkish list

@Yuki2718

**Comment by Yuki2718** [comment]
Hmm, I don't see unblocked ads if Turkish list is enabled.

**Comment by urvbcn88** [comment]
If you don't block ads on Non-English Language sites, place a warning on uBlock Origin.

for instance:
This reporting tool should only be used for English sites.

or something like that:
You can only report English sites with this reporting tool.

This provides less workload for filter developers.

**Comment by uBlock-user** [comment]
@urvbcn88 Regional lists take care of that. If they don't then we add it. So it's not black and white as you think.
