### ISSUE TITLE
streamlare.com: nuisance

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11485]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamlare.com/e/BWwyJnLEgBDMbPaN`

### Category

nuisance

### Describe the issue

Video player stops and shows `The media could not be loaded...` when opening dev tools.

Proposed filter:

`streamlare.com##+js(set, console.clear, undefined)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66517106/151366232-e019ad90-fe36-4e1c-8d8c-d8e5477ebdd2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78698
  cosmetic: 42102
  scriptlet: 19221
  html: 625
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4375-4, now
  default: 
    ublock-filters: 30861-31, now
    ublock-badware: 3820-1, now
    ublock-privacy: 193-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1697-0, now
    easylist: 63545-599, now
    easyprivacy: 26677-480, now
    urlhaus-1: 6993-0, now
    plowe-0: 3679-2, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 689 ms
popupPanel: 
  blocked: 3
```
</details>

**Comment by ghajini** [comment]
`https://streamlare.com/e/RWwM7lM8ZPPzZKbo`

popups ,filters need to revised

**Comment by ghajini** [comment]
does the video play for you @okiehsch with the fix https://github.com/uBlockOrigin/uAssets/commit/70dd8dfd49438ab660bfe2db24dcc14dd8cbe666
(because i tried nowoif already)

**Comment by mapx-** [comment]
Does not play in chrome

**Comment by ghajini** [comment]
On my end even firefox A. also video was unable to play

**Comment by mapx-** [comment]
Test

`streamlare.com##+js(aopr, open)`

**Comment by ghajini** [comment]
that work on firefox a
haven't tested on chrome

secondly did you reproduce this issue in chrome?
https://github.com/uBlockOrigin/uBlock-issues/issues/1912

link for test `https://atishmkv.life/antim-the-final-truth-2021-zee5-web-dl-hindi-dd2-0-1080p-720p-480p/`

**Comment by mapx-** [comment]
gorhill already added a commit for that issue, does it still happen on your side ?

**Comment by ghajini** [comment]
yes on chrome, that 10sec interval,he said not going to fix

**Comment by mapx-** [comment]
You should post the steps again for chrome (what exactly to click etc), I get a different page ( `oxl.one` )

**Comment by okiehsch** [comment]
> does the video play for you @okiehsch with the fix

My bad, was in a rush and did not properly test

**Comment by uBlock-user** [comment]
It's only a matter of adding an exception -- `##+js(nowoif, !string)`
