### ISSUE TITLE
[nsfw] www2.javdock.com: ads

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11482]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www2.javdock.com/video/rctd-068/`

### Category

ads

### Describe the issue

ads button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/56762704/151329529-dcb5e5c6-b04e-4fad-960a-b05f5ace269e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 78689
  cosmetic: 40772
  scriptlet: 16486
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63545-9, 27m
    easyprivacy: 26677-17, 27m
    plowe-0: 3679-817, 27m
    ublock-abuse: 77-0, 27m
    ublock-badware: 3816-69, 27m
    ublock-filters: 30284-155, 27m
    ublock-privacy: 195-2, 27m
    ublock-unbreak: 1686-39, 27m
    urlhaus-1: 7247-0, 27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 950 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
add

`video.javdock.com##.video-container`

@Yuki2718 
@ryanbr

**Comment by Yuki2718** [comment]
Looks to be an English site so I'll leave to @ryanbr
