### ISSUE TITLE
denofgeek.com: detection

### ISSUE THREAD

**Issue by devansh2447** [uBlockOrigin/uAssets#11483]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.denofgeek.com/tv/star-wars-the-book-of-boba-fett-episode-5-review/`

### Category

detection

### Describe the issue

detects uBlock, shows popup asking to allow the site to show ads
i suspect the popup is loaded from here:
https://d3fkv551xkjrmm.cloudfront.net/js/messaging.js
(im not sure though)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/98523837/151342224-f253533d-82de-43e3-9398-00e5e04c9aa0.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78358
  cosmetic: 40686
  scriptlet: 16442
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30832-29, 2d.25m
    ublock-badware: 3805-1, 2d.23m
    ublock-privacy: 191-0, 2d.22m
    ublock-abuse: 76-0, 1d.2h.54m
    ublock-unbreak: 1705-0, 1d.2h.53m
    easylist: 63409-592, 1d.2h.52m
    easyprivacy: 26668-482, 1d.2h.51m
    urlhaus-1: 6993-0, 2h.6m
    plowe-0: 3679-2, 23h.51m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 579 ms (selfie)
popupPanel: 
  blocked: 26
```
</details>

**Comment by okiehsch** [comment]
It's fixed in the `uBO-annoyance` list, if you don't want to enable that list you can add
`||d3fkv551xkjrmm.cloudfront.net/js/detection.js$script,domain=denofgeek.com`
to your personal filter list.

**Comment by devansh2447** [comment]
thanks
