### ISSUE TITLE
fullhdfilmizlesene.pw: ads

### ISSUE THREAD

**Issue by weinbaum** [uBlockOrigin/uAssets#11487]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fullhdfilmizlesene.pw/`

### Category

ads

### Describe the issue

Ad in background.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss](https://user-images.githubusercontent.com/98059187/151410213-1e27fc6a-af74-4209-90fe-4d76659a0c2c.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 80218
  cosmetic: 47330
  scriptlet: 16885
  html: 0
listset (total-discarded, last updated): 
  default: 
    TUR-0: 9132-90, 3d.4m
    easylist: 63315-20, 3d.3m
    easyprivacy: 26659-22, 3d.2m
    plowe-0: 3682-817, 7d.1h.6m
    ublock-abuse: 76-0, 3d.1m
    ublock-badware: 3801-67, 3d
    ublock-filters: 30255-163, 2d.23h.59m
    ublock-privacy: 194-3, 2d.23h.58m
    ublock-unbreak: 1688-39, 2d.23h.57m
    urlhaus-1: 6993-0, 8h.25m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 229 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
`fullhdfilmizlesene.pw##.psk`

@Yuki2718

**Comment by uBlock-user** [comment]
`||i.imgz.me/rrk/psk/binancepsx.jpg^$image`

@AdamWr

**Comment by uBlock-user** [comment]
`||i.imgz.me/rrk/psk/binancepsx.jpg^$image`

@AdamWr
