### ISSUE TITLE
[nsfw] dmhy.gate.flag.moe: ads

### ISSUE THREAD

**Issue by tasty0tomato** [uBlockOrigin/uAssets#11481]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dmhy.gate.flag.moe/`

### Category

ads

### Describe the issue

Some adds are blocked but there is still one.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/48764449/151324696-0a821c16-11a1-414b-a4a1-595f97860143.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 89667
  cosmetic: 73759
  scriptlet: 16577
  html: 0
listset (total-discarded, last updated): 
  removed: 
    JPN-1: null
    urlhaus-1: null
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24275-3, 20h.29m
    CHN-0: 27665-88, 3d.21h.38m
  default: 
    easylist: 63179-18, 3d.21h.37m
    easyprivacy: 26642-45, 3d.21h.36m
    plowe-0: 3676-818, 3d.4h.24m
    ublock-abuse: 76-0, 3d.21h.35m
    ublock-badware: 3780-67, 3d.21h.33m
    ublock-filters: 30230-168, 3d.21h.32m
    ublock-privacy: 194-3, 3d.21h.31m
    ublock-unbreak: 1684-40, 3d.21h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 445 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
add:
`dmhy.gate.flag.moe##[src*=".gif"]:not([style]):not([alt]):upward([href]:not([style]))`

@Yuki2718

**Comment by tasty0tomato** [comment]
Thanks for maintaining this wonderful project. @mapx-

**Comment by mapx-** [comment]
> Thanks for maintaining this wonderful project. @mapx-

thanks extended to all volunteers investing their spare time in it

**Comment by Yuki2718** [comment]
@mapx- Doesn't `dmhy.gate.flag.moe##a[href^="https://7segu.taobao.com?"]` work on your side?

**Comment by mapx-** [comment]
yeah, but I wanted something more generic

**Comment by Yuki2718** [comment]
Okay, let's see if the rule added lasts long or not.

**Comment by tasty0tomato** [comment]
It works. Thanks a lot!
