### ISSUE TITLE
foxnews.com: detection

### ISSUE THREAD

**Issue by David21891** [uBlockOrigin/uAssets#11494]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.foxnews.com/`

### Category

detection

### Describe the issue

A banner blocks much of the screen with dialog about turning off my filter to access Fox News.

![image](https://user-images.githubusercontent.com/98595959/151554587-49bbe6b2-d55f-4190-b2a7-53723154ee8a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 74923
  cosmetic: 36398
  scriptlet: 7419
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.23h.32m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    easylist: 63575-9, 11h.44m
    easyprivacy: 26677-17, 11h.43m
    plowe-0: 3682-817, 12d.10h.57m
    ublock-abuse: 77-0, 11h.42m
    ublock-badware: 3816-69, 11h.41m
    ublock-filters: 12956-36, 11h.39m
    ublock-privacy: 194-2, 11h.38m
    ublock-unbreak: 1686-39, 11h.37m
    urlhaus-1: 7189-0, 23h.24m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 65 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 510 ms (selfie)
popupPanel: 
  blocked: 38
```
</details>

**Comment by uBlock-user** [comment]
Test on default settings/lists + all other extensions disabled. Generic filter for GFC still works.
