### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by weinbaum** [uBlockOrigin/uAssets#11496]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/instagram/following/`

### Category

breakage

### Describe the issue

If I don't turn off the **Fanboy's Annoyances**, following and followers menus do not open.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![insta](https://user-images.githubusercontent.com/98059187/151594806-ccfee599-0950-4ace-a783-90477179f1aa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 87889
  cosmetic: 100177
  scriptlet: 16864
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 63615-3484, 19m
  default: 
    TUR-0: 8753-90, 1m
    easylist: 63629-20, 1m
    easyprivacy: 26677-22, 1m
    plowe-0: 3682-818, 8d.1h.21m
    ublock-abuse: 77-0, 1m
    ublock-badware: 3831-69, 1m
    ublock-filters: 30307-188, 1m
    ublock-privacy: 194-10, 1m
    ublock-unbreak: 1686-42, 1m
    urlhaus-1: 7364-0, 8h.34m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 270 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
