### ISSUE TITLE
nintendolife.com: breakage

### ISSUE THREAD

**Issue by nodren** [uBlockOrigin/uAssets#11499]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nintendolife.com/news/2022/01/poll-pokemon-legends-arceus-is-out-today-on-switch-are-you-getting-it`

### Category

breakage

### Describe the issue

Polls on this site fail to work with unlock enabled. They work fine with it disabled.

Link is to a specific article with a poll however any article on this site containing a poll breaks in the same way 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 96
filterset (summary): 
  network: 80346
  cosmetic: 22418
  scriptlet: 16485
  html: 620
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30977-252, 1m
    ublock-badware: 3835-1, 1m
    ublock-privacy: 193-1, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1703-0, 1m
    adguard-mobile: 7149-187, 1m
    easylist: 63631-24332, 1m
    easyprivacy: 26678-489, 1m
    urlhaus-1: 7364-0, 1m
    plowe-0: 3679-2, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 611 ms (selfie)
popupPanel: 
  blocked: 17
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||static.nintendolife.com/themes/base/javascript/fingerprint.js$script,1p
```

**Comment by BottledSoda** [comment]
Caused by EasyPrivacy.
@ryanbr Could you address this?

**Comment by nodren** [comment]
That filter did solve the problem from what I could tell no ads showed up either

**Comment by uBlock-user** [comment]
`nintendolife.com##+js(ra, name, input[name="fingerprint"])` works and prevents having to run the fingerprinting script and in turn prevent the site from collecting the fingerprint.

@okiehsch Should we bother to fix it in here to or have ryanbr whitelist the fingerprinting script ?

**Comment by okiehsch** [comment]
If it works we can fix it and overrule the exception.

**Comment by uBlock-user** [comment]
Seems if you don't allow it to collect the fingerprint, it will throw an alter -- _Sorry, you must be logged in to vote._
