### ISSUE TITLE
https://announce.zerotier.com/en

### ISSUE THREAD

**Issue by RDiSa** [uBlockOrigin/uAssets#11495]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://announce.zerotier.com/en`

### Describe the issue

Page partially loaded

### Notes

Disabling uBlock the page load correctly

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 418136
  cosmetic: 93525
  scriptlet: 18706
  html: 617
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/: 353761-25857, 56m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5359-5, 2d.1h.10m
    adguard-annoyance: 49489-597, 2d.23h.40m
  default: 
    ublock-filters: 30832-43, 2d.23h.45m
    ublock-badware: 3805-1, 2d.23h.44m
    ublock-privacy: 194-36, 2d.23h.39m
    ublock-abuse: 76-65, 2d.23h.43m
    ublock-unbreak: 1705-0, 2d.23h.37m
    easylist: 63403-703, 2d.23h.42m
    easyprivacy: 26666-496, 2d.23h.41m
    plowe-0: 3682-55, 11d.22h.25m
    ITA-0: 12770-32, 57m
    urlhaus-1: 7252-0, 58m
filterset (user): [array of 36 redacted]
trustedset: 
  added: [array of 39 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 310 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
adguard annoyances issue => **you didn't test using the default list** 

add
`@@||app.getbeamer.com^$css,script,domain=announce.zerotier.com`

@Yuki2718
