### ISSUE TITLE
delfi.lv: detection

### ISSUE THREAD

**Issue by mmezulis** [uBlockOrigin/uAssets#11493]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.delfi.lv/sports/news/3-puslaiks/briedis-turpina-medit-polu-un-velta-vinam-repa-dziesmu-trakuma-iesaistas-ari-zauerlands.d?id=53997618`

### Category

detection

### Describe the issue

All news articles on `delfi.lv` trigger a non-closable modal that asks to disable adblock or subscribe to Delfi Plus.
`delfi.lv` itself does not trigger this, only clicking specific articles.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Here are three screenshots from randomly taken articles in delfi.lv that after a few seconds detect adblock.

Links are:

```
https://www.delfi.lv/sports/news/3-puslaiks/briedis-turpina-medit-polu-un-velta-vinam-repa-dziesmu-trakuma-iesaistas-ari-zauerlands.d?id=53997618

https://www.delfi.lv/laika-zinas/raksti/nedelas-nogale-gaidama-jauna-vetra-un-sniegputenis-kurzeme-bridina-par-pludiem.d?id=53997304

https://www.delfi.lv/news/national/politics/ceturtdien-latvija-atklati-8682-covid-19-inficesanas-gadijumi-devini-mirusie.d?id=53995146
```

![image](https://user-images.githubusercontent.com/55508076/151548199-dbeb6316-17e6-4ce5-b615-2b09e1d5772b.png)
![image](https://user-images.githubusercontent.com/55508076/151548263-6dcf0ebc-f9c2-439e-9c8d-0073ed3899e6.png)
![image](https://user-images.githubusercontent.com/55508076/151548326-49337388-bc8f-4e92-95f2-01ebdc40c2ea.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78566
  cosmetic: 40694
  scriptlet: 16493
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63410-9, 1d.20h.56m
    easyprivacy: 26670-17, 1d.20h.55m
    plowe-0: 3682-817, 9d.20h.37m
    ublock-abuse: 76-0, 1d.20h.54m
    ublock-badware: 3801-69, 1d.20h.52m
    ublock-filters: 30287-152, 1d.20h.51m
    ublock-privacy: 197-3, 1d.20h.58m
    ublock-unbreak: 1696-39, 1d.20h.57m
    urlhaus-1: 7189-0, 16h.28m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 433 ms (selfie)
popupPanel: 
  blocked: 18
```
</details>

**Comment by mapx-** [comment]
@mmezulis maybe you have some other blocking extension ?

![image](https://user-images.githubusercontent.com/10303732/151556076-17f50649-96c1-4538-89b2-1715f116e668.png)

**Comment by uBlock-user** [comment]
You also have not enabled the regional list.

**Comment by mapx-** [comment]
Did you touch the dynamic filters ?

![image](https://user-images.githubusercontent.com/10303732/151561317-141b524e-b0ff-4206-ade3-6ac7ce4ef7b5.png)

**Comment by mmezulis** [comment]
@mapx- 
Could you please elaborate what are dynamic filters? I only use the zapping tool to remove the uncloseable modals in some pages. The rest I have not modified. This is that same section you have shown.

![image](https://user-images.githubusercontent.com/55508076/151563397-41473bcb-a92b-4e8d-8de6-a0d873ebbcc0.png)



@uBlock-user 
Is this the regional list you meant? If so, I enabled it, purged, updated and the popup still appears.

![image](https://user-images.githubusercontent.com/55508076/151563085-c7505739-8b76-4b9c-8983-db3de28d37a4.png)

**Comment by mapx-** [comment]
does this filter help ?

`delfi.lv##+js(nostif, , 300)`

**Comment by mmezulis** [comment]
@mapx- 
`delfi.lv##+js(nostif, , 300)` did not fix this, however `delfi.lv##+js(nostif, , 5000)` appears to have solved this. I assume the number parameter is some sort of timeout?

**Comment by okiehsch** [comment]
Yes, but it is a bit to generic for my liking, it aborts all timeout calls with that parameter.
I see two calls with that parameter in the source.
Does 
`delfi.lv##+js(nostif, check, 5000)`
work for you?

**Comment by mapx-** [comment]
if you add nostif with no parameter uBO will show you in console all `setTimeout`

log:
`delfi.lv##+js(nostif)`

and indeed you'll see in console this 1:

`uBO: setTimeout("function(){w.__protected__.init().catch((function(){}))}", 5000)`

so, if your filter is working keep it in your "my filters"
or even

`delfi.lv##+js(nostif, __protected__)`

You could also report the fact to `LVA: Latvian List` => https://notabug.org/latvian-list/adblock-latvian

**Comment by okiehsch** [comment]
@mapx- the latvian list seems not very active to me, it's an anti adblock issue, so I would be in favour of fixing it in uBO-filters.

**Comment by mapx-** [comment]
@okiehsch even if I cannot reproduce it ?

**Comment by okiehsch** [comment]
I can't reproduce it either and without the screenshots I would agree with you but those screenshots prove that the issue exists imo.
Unless the OP photoshopped them. 😁

**Comment by mapx-** [comment]
Let's take some more steps:

@mmezulis , could you check with some other your countryman if he/she can reproduce the same issue ? 

(I tested using a LV ip too, but I guess delfi is important enough to chdck if it's vpn or not)

**Comment by iam-py-test** [comment]
> I can't reproduce it either and without the screenshots I would agree with you but those screenshots prove that the issue exists imo.

I can't repro either.
Maybe OP has DNS or HOSTs adblocking? @mmezulis reset your DNS server and HOSTs file or test from another device with uBo installed. Do you see it if you disable uBlock Origin? What if you disable uBo and install AdGuard? Does that trigger it

**Comment by mmezulis** [comment]
Thanks y'all for trying to resolve this.
Here is what I have tried:

- Connecting to my work VPN, also located in Latvia, unlikely to be in some VPN list. Did not resolve the issue, after a few seconds the popup still appeared.
- Connecting to a mobile hotspot instead of my home network. Did not work either.
- Disabling uBlock Origin made the popup not appear, however there were ads. Lots of them :D
- Disabling uBlock Origin and enabling AdGuard AdBlocker with the following configuration did resolve the issue. I tried multiple articles, waited at least 10 seconds and no popup appeared. ![image](https://user-images.githubusercontent.com/55508076/151613210-395ac497-e167-4d80-b934-6a655a3017d7.png)

Also only uncommented lines in my Hosts file were these but they shouldn't conflict with anything.
```# Work related
127.0.0.1 web-backend web-frontend
# Added by Docker Desktop
192.168.0.156 host.docker.internal
192.168.0.156 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Another person from the same city, also on Windows 10 and Chrome with uBlock Origin was able to confirm that this also happens to them.
![image](https://user-images.githubusercontent.com/55508076/151614681-7fd4e485-7342-412e-a590-22d3e6e14e4a.png)

And I'm sorry this has caused such a headache, I promise I have better things to do than photoshopping fake popups on news sites :)

**Comment by mapx-** [comment]
I added the filter to our list

**Comment by iam-py-test** [comment]
Thanks @mmezulis
