### ISSUE TITLE
gamepro.de: breakage

### ISSUE THREAD

**Issue by Seraangel** [uBlockOrigin/uAssets#11497]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gamepro.de/artikel/horizon-forbidden-west-ps5-exklusiv-features,3377227.html`

### Category

breakage

### Describe the issue

When you scroll down to the video-image and click on it, the video player isn't loading. Or the video-placeholder isn't replaced with the player. My guess some script which does it get's blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 81006
  cosmetic: 43984
  scriptlet: 16495
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5327-0, 52m
    easylist: 63629-15, 52m
    easyprivacy: 26677-28, 52m
    plowe-0: 3679-818, 52m
    ublock-abuse: 77-0, 52m
    ublock-badware: 3831-69, 52m
    ublock-filters: 30307-163, 52m
    ublock-privacy: 194-2, 52m
    ublock-unbreak: 1686-40, 52m
    urlhaus-1: 7364-0, 52m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 687 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by mapx-** [comment]
test

```
@@||cdn.lib.getjad.io^$script,domain=gamepro.de
@@||doubleclick.net^$script,domain=gamepro.de
```

**Comment by okiehsch** [comment]
Does not work for me.
````
@@||cdn.lib.getjad.io/library/*Gamepro$script,domain=gamepro.de
@@||securepubads.g.doubleclick.net/gpt/pubads_impl$script,domain=gamepro.de
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=gamepro.de
@@||securepubads.g.doubleclick.net/pagead/ppub_config?ippd=www.gamepro.de$xhr,domain=gamepro.de
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=gamepro.de
````
works with a slight delay on my end.

**Comment by mapx-** [comment]
(tested in chrome)

**Comment by Seraangel** [comment]
This was fast ;-)

@mapx- It doesn't worked for me.

@okiehsch that worked with some long delay like you said.

Same company, but it works with ublock and loads faster. Maybe there does already exists a better fix? Just the other domain needs to be added?
e.g. https://www.gamestar.de/videos/eso-high-isle-trailer-zum-neuen-addon-entfuehrt-in-bisher-nie-gezeigten-ort-auf-der-karte,104540.html

**Comment by Procyon-b** [comment]
A variation of @mapx- filters works for me:
```
@@||cdn.lib.getjad.io^$script,domain=gamepro.de
@@||doubleclick.net^$script,xhr,domain=gamepro.de
```

**Comment by okiehsch** [comment]
@Procyon-b well that's in essence the same as my filters but it allows even more requests.

@Seraangel No, the fix for gamestar is basically the same than my fix above. I don't know why the delay happens on gamepro.

**Comment by Procyon-b** [comment]
@okiehsch you're correct. It let one more entity pass.

**Comment by mapx-** [comment]
@khrin @monzta
