### ISSUE TITLE
playstation.com

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1150]
### URL(s) where the issue occurs

https://www.playstation.com/pl-pl/games/crash-bandicoot-n-sane-trilogy-ps4/

### Describe the issue

Popup.

### Screenshot(s)
![screenshot_20180101_182147](https://user-images.githubusercontent.com/19818572/34469500-aaa0f3f4-ef20-11e7-9438-12f975446ac9.png)

### Versions

- Browser/version: Vivaldi 1.13.1008.40 (Chromium/62.0.3202.97)
- uBlock Origin version: 1.14.22

### Settings

- https://gist.github.com/hawkeye116477/8d261cbd7ff19ebd07d4303781bd2ea2

### Notes

I tried to block popup with rule `playstation.com##.pdc-popup`, but this rule blocks displaying photos in popup (section „Filmiki i obrazki") too. Then I tried another rules:
```
playstation.com###cboxLoadedContent:has(.signedout)
playstation.com###cboxOverlay
```
These rules works almost perfectly, however then there is a leftover after the popup.

**Comment by okiehsch** [comment]
Does
`playstation.com##script:inject(abort-current-inline-script.js, $, PDC.PopupManager)`
work for you?

**Comment by hawkeye116477** [comment]
@okiehsch Thanks, works perfectly :smile:
