### ISSUE TITLE
gcertificationcourse.com: detection

### ISSUE THREAD

**Issue by Mchar7** [uBlockOrigin/uAssets#11500]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gcertificationcourse.com/`

### Category

detection

### Describe the issue

Site detects uBlock Origin and blocks content through an inline script `https://www.gcertificationcourse.com/wp-content/plugins/deblocker/js/ads.min.js`

Looks like [this Wordpress plugin](https://1.envato.market/deblocker).

See: `https://ibug.io/blog/2020/08/work-against-wordpress-deblocker/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 98915
  cosmetic: 109528
  scriptlet: 19252
  html: 625
listset (total-discarded, last updated): 
  added: 
  default: 
    ublock-filters: 30878-31, 1h.44m
    ublock-badware: 3820-1, 1h.45m
    ublock-privacy: 193-0, now
    ublock-abuse: 77-0, 1h.46m
    ublock-unbreak: 1697-0, 1h.42m
    easylist: 63631-599, 1h.43m
    easyprivacy: 26678-482, 1h.3m
    urlhaus-1: 7252-0, 1h.41m
    plowe-0: 3682-2, 12d.18h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2250 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
gcertificationcourse.com##+js(no-xhr-if, adsbygoogle.js)
```

**Comment by Mchar7** [comment]
> `gcertificationcourse.com##+js(no-xhr-if, adsbygoogle.js)`

Yep, ad detection is gone.

Though there is quite a bit of bright space left over. That's not really a problem though.

![image](https://user-images.githubusercontent.com/34781916/151639830-4eb9e82f-47b3-444d-a89e-e00758bea40c.png)

**Comment by iam-py-test** [comment]
Try the following filters for the placeholders:
```
gcertificationcourse.com##[id*="PAds_"]
gcertificationcourse.com##[id*="PAds-"]
```
Please put these in your My Filters tab

**Comment by Mchar7** [comment]
Is there any way to block the adblock detection for any site using this "DeBlocker" plugin or is it only possible to add it to a list for each site that uses it?

I don't really care to access this site in particular, it is just the only one I have seen to detect uBlock Origin.

**Comment by uBlock-user** [comment]
> he adblock detection for any site using this "DeBlocker" plugin

Would require us to run the scriptlet as a generic filter which is not going to happen or add allow an XHR as third-party request from `googlesyndication` ad-server to load.

**Comment by Mchar7** [comment]
> > he adblock detection for any site using this "DeBlocker" plugin
> 
> Would require us to run the scriptlet as a generic filter which is not going to happen or add allow an XHR as third-party request from `googlesyndication` ad-server to load.
> 
> @Mchar7 There's no permanent fix if that's what you're asking. The developer(of the anti-adblock script) keeps an eye on this repo to see what we're doing and then circumvents it by updating his script if a generic filter were to be added.

Makes sense. I was a bit mistaken with how uBO handles everything, sorry.
