### ISSUE TITLE
9am.ro (anti adb)

### ISSUE THREAD

**Issue by BottledSoda** [uBlockOrigin/uAssets#11501]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.9am.ro/stiri/Sanatate/354802/Scapa-de-kilogramele-in-plus-in-doar-doua-zile-Dieta-magica-care-te-ajuta-sa-ajungi-la-corpul-mult-visat.html`

### Describe the issue

antiadb (seemingly similar to antiadb found while browsing on `romaniatv .net` & `stirilekanald .ro`)

### uBlock Origin version

1.40.8

### Browser name and version

Google Chrome

### Settings

.

**Comment by Procyon-b** [comment]
Try:
```
@@||imasdk.googleapis.com^$script
```

**Comment by Procyon-b** [comment]
@mapx-  You know the funny thing. The reason I didn't put `,domain=9am.ro` in my reply is that, yesterday when I tried, chrome and uBO refused to match the rule with any 'domain='. In the logger there was an empty "Context identifier" for that request and a few others. Today (fresh reboot) everything is fine.
Still, I've seen weirder things in my life with browsers...

**Comment by mapx-** [comment]
I wondered why that filter, who knows .. some cache issue

**Comment by BottledSoda** [comment]
@Procyon-b what browser?

**Comment by BottledSoda** [comment]
> ,domain=9am.ro

so how did it look?

**Comment by BottledSoda** [comment]
Similar-looking anti adb on `https://www.wowbiz.ro/exclusiv-dan-negru-vorbeste-despre-cea-mai-buna-lectie-pe-care-le-o-preda-studentilor-de-la-jurnalism-m-au-contaminat-multi-mentori-20197838`

---

Could someone try to help with hiding/addressing spaces on `https://wowbiz.ro` -- would scriptlets be optimal for this?

**Comment by Procyon-b** [comment]
> @Procyon-b what browser?

Chrome. Not the latest version (I always keep one on the side to compare when something in the code I write breaks)
But today it's ok (in all chrome versions).

**Comment by mapx-** [comment]
> hiding/addressing spaces on https://wowbiz.ro

.. where are those spaces ?

**Comment by BottledSoda** [comment]
an example can be observed on `https://ibb.co/ZzyMgMx`

**Comment by mapx-** [comment]
maybe

`wowbiz.ro##.container > .container > div:first-child`

however does not worth, could break something on other pages
