### ISSUE TITLE
bigbtc.win: detection

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#11503]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bigbtc.win/`

### Category

detection

### Describe the issue

Anti-adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 98
filterset (summary): 
  network: 99623
  cosmetic: 65252
  scriptlet: 27613
  html: 620
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24288-13337, 3h.16m
    adguard-generic: 61399-5097, 3h.7m
  default: 
    ublock-filters: 30977-325, 3h.17m
    ublock-badware: 3835-1, 3h.17m
    ublock-privacy: 193-1, 3h.17m
    ublock-abuse: 77-0, 3h.17m
    ublock-unbreak: 1703-0, 3h.17m
    adguard-mobile: 7149-173, 3h.17m
    easylist: 62449-24476, 3h.17m
    easyprivacy: 26678-504, 3h.17m
    urlhaus-1: 7252-0, 3h.17m
    plowe-0: 3679-2, 3h.17m
    spa-0: 3719-219, 3h.17m
    spa-1: 4203-177, 3h.16m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  uiFlavor: -
supportStats: 
  launchToReadiness: 2125 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by garry-ut99** [comment]
Anti-adblock is back: 
![](https://user-images.githubusercontent.com/72945564/212556908-b3b21edc-7a2f-481f-90f7-0fb6ed5c1368.png)

**Comment by mild787** [comment]
hi, for this site `bigbtc.win` need update filter, condition now detection. thanks
![image](https://github.com/uBlockOrigin/uAssets/assets/121563747/1108ba84-807d-4516-8af1-2937b3a28f9f)

**Comment by mild787** [comment]
thanks

**Comment by mild787** [comment]
need help again for reproduce site `bigbtc.win` detection again now.

**Comment by p0008874** [comment]
<img width="1185" height="227" alt="Image" src="https://github.com/user-attachments/assets/6a427803-5cfa-4a59-a4ff-5099f68a5d8d" />
