### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by enilson4** [uBlockOrigin/uAssets#11507]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

This blocker consistently blocked ads on Twitch until about 3 months ago.  Now I see ads all the time at the normal cadence of Twitch ads.  Not much detail to get into other than ads are appearing when they previously didn't.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77529
  cosmetic: 40776
  scriptlet: 16495
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62449-9, 18h.32m
    easyprivacy: 26678-18, 18h.32m
    plowe-0: 3679-817, 18h.32m
    ublock-abuse: 77-0, 18h.32m
    ublock-badware: 3831-68, 18h.32m
    ublock-filters: 30308-250, 18h.32m
    ublock-privacy: 194-2, 18h.32m
    ublock-unbreak: 1686-39, 18h.32m
    urlhaus-1: 7252-0, 18h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 183 ms (selfie)
popupPanel: 
  blocked: 95
```
</details>

**Comment by BottledSoda** [comment]
Have you tried adding **AdGuard Extra**?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22twitch.tv%22+in%3Atitle
