### ISSUE TITLE
sony.jp: breakage

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#11508]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sony.jp/bravia/update/`

### Category

breakage

### Describe the issue

Update information is not displayed.
(Oddly enough, if I reload the page a few times, the site sometimes comes back up fine)
After trying a few things on my own, I found out that the following filter is the cause
`/utag.sync.`
After adding the following filter to My Filters, the site now displays 100% correctly
`@@||tags.tiqcdn.com/utag/sony-marketing/main/prod/utag.sync.js$script,domain=www.sony.jp`

EDIT:Fixed accidental enclosing of filters in double quotation marks.
### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし1](https://user-images.githubusercontent.com/86018494/151684393-1900846e-083f-452c-ae9a-6ba8485c01fc.png)
![タイトルなし](https://user-images.githubusercontent.com/86018494/151684394-b26b5bd2-a692-4ec5-a65d-94d65ea22b3f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78279
  cosmetic: 45486
  scriptlet: 16569
  html: 0
listset (total-discarded, last updated): 
  default: 
    JPN-1: 5830-6, 2m
    easylist: 62448-92, 2m
    easyprivacy: 26679-41, 2m
    plowe-0: 3679-823, 2m
    ublock-abuse: 77-0, 2m
    ublock-badware: 3831-68, 2m
    ublock-filters: 30171-127, 2m
    ublock-privacy: 194-2, 2m
    ublock-unbreak: 1692-42, 2m
    urlhaus-1: 7085-0, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 950 ms
popupPanel: 
  blocked: 99
```
</details>

**Comment by mapx-** [comment]
@ryanbr  EP issue
