### ISSUE TITLE
vezionline.net adblock detected

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#11512]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vezionline.net/creed-ii-2018.html`

### Describe the issue

On "Server 1" after I play the video, pop-up with adblock detected appear.

### uBlock Origin version

1.40.8

### Browser name and version

FIrefox 96.0.3

### Settings

Default settings

**Comment by mapx-** [comment]
it seems the alert window is present even disabling uBO

![image](https://user-images.githubusercontent.com/10303732/151691929-b8e6c3b0-e5f6-4c61-bebe-f8e0655f54e4.png)

**Comment by uBlock-user** [comment]
> [404]

Site issue
