### ISSUE TITLE
marmiton.org: breakage

### ISSUE THREAD

**Issue by squid-f** [uBlockOrigin/uAssets#11514]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.marmiton.org/`

### Category

breakage

### Describe the issue

The top part of the page to connect to the user account is not displayed when ubloc is activated.
Deactivating ublock leads to get it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 93732
  cosmetic: 49968
  scriptlet: 16507
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30873-206, 1h.34m
    ublock-badware: 3835-2, 1h.33m
    ublock-privacy: 193-1, 1h.32m
    ublock-abuse: 77-0, 1h.31m
    ublock-unbreak: 1703-0, 1h.30m
    easylist: 62448-747, 1h.29m
    easyprivacy: 26679-804, 1h.28m
    urlhaus-1: 7175-0, 23h.33m
    plowe-0: 3679-0, 11m
    FRA-0: 26162-41, 1h.35m
filterset (user): [empty]
switchRuleset: 
  removed: 
    no-csp-reports: * true
modifiedUserSettings: 
  cnameUncloakEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1870 ms (selfie)
popupPanel: 
  blocked: 10
```
</details>

**Comment by mapx-** [comment]
add 
`marmiton.org#@#div[data-ad-sticky-follow]`

@Yuki2718
