### ISSUE TITLE
re.two.re: detection

### ISSUE THREAD

**Issue by bufce2010** [uBlockOrigin/uAssets#11513]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://re.two.re/link/92176`

### Category

detection

### Describe the issue

Hello,
I hope you are well and healthy,

I get two warning messages as if there are two Anti-Adblock.

I've tried the following:
Disabled the other pop-up blocker then cleared browser cache and restarted it.
Reset uBO and updated filters.
Removed & re-added uBO then updated filters.

PS: I didn't get the chance to say sorry about previous old post as I didn't follow Prerequisites, and thanks for not banning me.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Akwam](https://user-images.githubusercontent.com/50169186/151694130-926fdfa7-0864-4434-8237-0a64178ac130.png)
![Akwam-2](https://user-images.githubusercontent.com/50169186/151694136-7d4fe782-fe98-4e26-9822-f82d9cc2ad54.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 86
filterset (summary): 
  network: 77364
  cosmetic: 40769
  scriptlet: 16491
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62448-9, now
    easyprivacy: 26679-18, now
    plowe-0: 3679-817, now
    ublock-abuse: 77-0, now
    ublock-badware: 3831-68, now
    ublock-filters: 30168-125, now
    ublock-privacy: 194-2, now
    ublock-unbreak: 1692-39, now
    urlhaus-1: 7085-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2971 ms
popupPanel: 
  blocked: 5
```
</details>

**Comment by okiehsch** [comment]
> I get two warning messages as if there are two Anti-Adblock.

Saw this after the fix, I only get one.
I can see BlockAdblock in the source, so I will add another filter dealing with it.

**Comment by uBlock-user** [comment]
don't see any BAB notice, generic filters working fine.

**Comment by bufce2010** [comment]
> > I get two warning messages as if there are two Anti-Adblock.
> 
> Saw this after the fix, I only get one. I can see BlockAdblock in the source, so I will add another filter dealing with it.
I've uploaded a video for it:
https://youtu.be/cRWUyJjmxYE

**Comment by uBlock-user** [comment]
@bufce2010 Disable any other extensions that are enabled.

**Comment by bufce2010** [comment]
> don't see any BAB notice, generic filters working fine.

Are generic filters the same as default ones?
here is a recording for added filters: https://youtu.be/kehbvsASPNk


> @bufce2010 Disable any other extensions that are enabled.

I've disabled everything even password manager and Jdownloader extensions,
there is nothing except uBO

**Comment by uBlock-user** [comment]
You will have to investigate further with the help of the logger and gather all `dom` listings from the logger. Besure to have uBO on default settings/lists.

**Comment by bufce2010** [comment]
> You will have to investigate further with the help of the logger and gather all `dom` listings from the logger. Besure to have uBO on default settings/lists.

Any specific settings for the 'dom' report?  list/table , plain/markdown
should I post it here in a comment or editthe post?

**Comment by uBlock-user** [comment]
In the logger, use the filter widget and filter 'dom', so all cosmetic filters inserted will appear listed alongside scriptlet injections.

**Comment by bufce2010** [comment]
> In the logger, use the filter widget and filter 'dom', so all cosmetic filters inserted will appear listed alongside scriptlet injections.


I hope I understood you correctly:

`<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +349 | @@\|\|github.com^$generichide | ++ | github.com | 1 | generichide | `https://github.com/uBlockOrigin/uAssets/issues/11513` |
| +190 | @@\|\|github.com^$generichide | ++ | github.com | 1 | generichide | `https://github.com/uBlockOrigin/uAssets/issues/11513` |
| +1 | @@\|\|github.com^$generichide | ++ | github.com | 1 | generichide | `https://github.com/uBlockOrigin/uAssets/issues/11513` |
| +1 | ##+js(no-floc) |  | github.com |  | dom | `https://github.com/uBlockOrigin/uAssets/issues/11513` |
</details>
`

**Comment by okiehsch** [comment]
I already added a fix for the BlockAdBlock issue, have you upated your filter list?
It should work fine after that.

**Comment by bufce2010** [comment]
I don't know what happened, but I did one more reset and updated filter and the anti-adblock disappeared.

**Comment by bufce2010** [comment]
> I already added a fix for the BlockAdBlock issue, have you upated your filter list? It should work fine after that.

Great, I've just did.
Thanks :)

**Comment by Yuki2718** [comment]
> don't see any BAB notice, generic filters working fine.

Neither, see I with nosiif disabled. @okiehsch Is the filter needed?

**Comment by okiehsch** [comment]
I added it because the OP has a default setup, his/her filters are up to date and the screenshot and the video proofs that the issue exists.
Seeing as you are not the only one questioning me doing it I will remove it.

**Comment by okiehsch** [comment]
@bufce2010 you can add
`re.two.re##+js(nosiif, visibility, 1000)`
to your filter list.

**Comment by Yuki2718** [comment]
I'm not necessarily against that. @bufce2010 Do you possibly have ads blocked on router, hosts file, or any other layer on your network?

**Comment by bufce2010** [comment]
> `re.two.re##+js(nosiif, visibility, 1000)`

Alright

> I'm not necessarily against that. @bufce2010 Do you possibly have ads blocked on router, hosts file, or any other layer on your network? Or does your Chromium browser have contents blocking built into it (e.g. Vivaldi, Brave)?

Non of blockers you mentioned exists,
I use "Cent Browser" maybe it has an adblocker in it's options.

**Comment by bufce2010** [comment]
@Yuki2718
Those are ad settings I found:

![Settings-2](https://user-images.githubusercontent.com/50169186/151699131-eff99363-5d18-4558-a3d8-57df0e96e941.png)

![Settings-1](https://user-images.githubusercontent.com/50169186/151699137-1f468122-760e-479f-96f5-34d52f417fcc.png)

**Comment by Yuki2718** [comment]
@bufce2010 Thank you, it seems not contents blocker and the same as Chrome. Do you still get the anti-adb if `re.two.re##+js(nosiif, visibility, 1000)` is not added? Make sure force-update uBlock filters in Filter lists pane (Purge all caches => Update now)

**Comment by bufce2010** [comment]
> @bufce2010 Thank you, it seems not contents blocker and the same as Chrome. Do you still get the anti-adb if `re.two.re##+js(nosiif, visibility, 1000)` is not added? Make sure force-update uBlock filters in Filter lists pane (Purge all caches => Update now)


No, I don't get any, neither  `re.two.re##+js(nosiif, visibility, 1000)`  is added nor not

**Comment by Yuki2718** [comment]
Thank you for confirming!

**Comment by bufce2010** [comment]
Thanks You!

**Comment by uBlock-user** [comment]
Cent browser issue if it still happens.

**Comment by bufce2010** [comment]
> Cent browser issue if it still happens.

It doesn't for me.
I've just made a couple of resets for uBO, then cleared browser cache and rebooted it. and finally updated default filter.
