### ISSUE TITLE
oreo.com: breakage

### ISSUE THREAD

**Issue by asherperlmuter** [uBlockOrigin/uAssets#11519]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.oreo.com/oreoid-1`

### Category

breakage

### Describe the issue

Missing half of the page, when you click thing it does nothing. With uBlock off, everything functions as normal.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43358608/151721487-397e4404-e0df-45f9-9ba4-6912c1af6bde.png)
![image](https://user-images.githubusercontent.com/43358608/151721508-9b91ee59-b702-43d4-bcd1-454fdcf4399b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 81796
  cosmetic: 61986
  scriptlet: 16599
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 8h.20m
    ISR-0: 1616-0, 10h.6m
    fanboy-cookiemonster: 21916-16, 10h.8m
  default: 
    easylist: 63582-9, 2d.9h.32m
    easyprivacy: 26677-19, 2d.9h.28m
    plowe-0: 3681-817, 11d.7h.57m
    ublock-abuse: 77-0, 2d.9h.26m
    ublock-badware: 3816-69, 2d.9h.25m
    ublock-filters: 30292-162, 2d.9h.31m
    ublock-privacy: 194-2, 2d.9h.24m
    ublock-unbreak: 1686-40, 2d.9h.29m
    urlhaus-1: 8013-0, 10h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 293 ms (selfie)
popupPanel: 
  blocked: 10
```
</details>

**Comment by mapx-** [comment]
add

`oreo.com#@#.cookie-container`

EL Cookie @ryanbr
