### ISSUE TITLE
Unable to display contents that are NOT advertisements

### ISSUE THREAD

**Issue by TakahiroIKEGAWA** [uBlockOrigin/uAssets#11524]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://hassiweb-programming.blogspot.com/2020/03/docker-x11-gui.html`

### Describe the issue

When open URL(s) where the issue occurs, cannot see any content at the page.

### Screenshot(s)
**actual**
![actual](https://user-images.githubusercontent.com/59414810/151817933-3d9979f3-3b1c-45c8-8ad7-cc9105c6a10a.png)
**expected**
![expected](https://user-images.githubusercontent.com/59414810/151817940-1c444a96-f3bf-402f-a883-38cabf663eab.png)

### uBlock Origin version

1.40.8

### Browser name and version

Chrome  97.0.4692.99

### Settings

nothing

### Notes

If change class name from `page_body vertical-ads` to `page_body vertical-ads-changed` with a below element, can see contents correctly.

`/html/body/div[2]/div[3]`

**actual-with-DevTools**
![actual-with-DevTools](https://user-images.githubusercontent.com/59414810/151819198-ba89a0ad-12f6-43c6-9c61-366bd201cfca.png)
**expected-with-DevTools**
![expected-with-DevTools](https://user-images.githubusercontent.com/59414810/151819207-fc28b713-a6e4-4248-87c0-239274e33726.png)

**Comment by uBlock-user** [comment]
`hassiweb-programming.blogspot.com#@#.vertical-ads`

@ryanbr
