### ISSUE TITLE
[nsfw] javhd.today: ads

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11526]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://javhd.today/15263/rct-925-studio-rocket-the-cum-swallowing-game-try-to-guess-which-shot-of-cum-belongs-to-your-boyfrie/`

### Category

ads

### Describe the issue

ads button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 81440
  cosmetic: 138312
  scriptlet: 22273
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1824-9, 5h.12m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6012-3, 5h.12m
    adguard-annoyance: 49738-169, 5h.12m
    fanboy-annoyance: 60327-2849, 5h.12m
    ublock-annoyances: 4375-270, 5h.12m
  default: 
    easylist: 62497-1245, 5h.12m
    easyprivacy: 26685-110, 5h.12m
    ublock-abuse: 77-0, 5h.12m
    ublock-badware: 3831-67, 5h.12m
    ublock-filters: 30164-539, 5h.12m
    ublock-privacy: 194-9, 5h.12m
    ublock-unbreak: 1692-44, 5h.12m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 750 ms (selfie)
popupPanel: 
  blocked: 24
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
javhd.today###previewBox
```

**Comment by mapx-** [comment]
other ads on avgle player

```
avgle.com###player_3x2_container_inner
avgle.com###aoverlay
```

@Yuki2718 @ryanbr

**Comment by Yuki2718** [comment]
> other ads on avgle player

It seems they're already addressed in JPF but probably should be added to EL.

**Comment by Bug-Cache** [comment]
annoyance new tab

![Image](https://github.com/user-attachments/assets/5d74f10f-3e7a-410d-b529-77396c4f8e90)

**Comment by mapx-** [comment]
provide an example page and what to click to get that popup
