### ISSUE TITLE
Unable to block ads and pop-ups

### ISSUE THREAD

**Issue by TheMercenary333** [uBlockOrigin/uAssets#11523]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://pahe.li/
https://4pda.to
https://mail.yandex.com
https://hqporner.com
```

### Describe the issue

Ublock Origin does not provide blocking for ads on these websites. Pahe.li redirects the site to another site. The Yandex mail site contains constantly changing ads. 4pda contains ads within the site. Hqporner site has an ad hold on video starters.

### Screenshot(s)

![1](https://user-images.githubusercontent.com/74915480/151804764-118b11c3-4b44-4438-96f4-0287140d762c.PNG)

### uBlock Origin version

1.40.8

### Browser name and version

Opera 83.0.4254.27 and Edge 97.0.1072.76

### Settings

Nothing changed. Just default settings.

**Comment by mapx-** [comment]
for 
```
https://4pda.to
https://mail.yandex.com
```

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
To block ads on Yandex domains, need to use filter [Counters](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

**Add**
Direct link to subscribe to [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

`4pda.to` also belong to recidivist domains, so the rules for it are also contained in the Counters.
