### ISSUE TITLE
[nsfw] vjav.me: ads

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11521]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vjav.me/9213/sdmu-724-competition-for-a-prize-of-1-million-yen-latest-couple-game-couple-counterattack-sleep/`

### Category

ads

### Describe the issue

ads button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/56762704/151778283-f9e2f091-cdcc-4d97-b8df-d0bdc48c8458.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 81442
  cosmetic: 138236
  scriptlet: 22269
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1821-9, 3d.19h.45m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6000-3, 3d.19h.45m
    adguard-annoyance: 49731-169, 20m
    fanboy-annoyance: 60272-2849, 4d.1h.10m
    ublock-annoyances: 4375-270, 21m
  default: 
    easylist: 62497-1243, 29m
    easyprivacy: 26685-110, 28m
    ublock-abuse: 77-0, 27m
    ublock-badware: 3831-67, 25m
    ublock-filters: 30164-539, 24m
    ublock-privacy: 194-9, 23m
    ublock-unbreak: 1692-44, 22m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 706 ms (selfie)
popupPanel: 
  blocked: 20
```
</details>

**Comment by mapx-** [comment]
add

`vjav.me###closeButton`

@ryanbr
