### ISSUE TITLE
einthusan.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1152]
URL(s) where the issue occurs

https://einthusan.tv/adblocker/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
Can't reproduce, I am not redirected to `https://einthusan.tv/adblocker/` and can use the site without issue.

Example link: `https://einthusan.tv/movie/watch/2Qnx/?lang=hindi`

**Comment by mapx-** [comment]
2 weeks ago it was reported another issue: when you click to pause the movie then it wont start again (clicking play button)

these filters permit to click again play:
```
@@*einthusan*$xmlhttprequest,domain=imasdk.googleapis.com
@@||imasdk.googleapis.com/js/sdkloader/loader.js$script,domain=einthusan.tv
@@||redir.adap.tv/redir/javascript/lightintegration.js
@@||einthusan.tv^$generichide
```

**Comment by okiehsch** [comment]
That, I can reproduce.

**Comment by okiehsch** [comment]
I only need to add
`@@||ads.adaptv.advertising.com/*einthusan.tv*$xmlhttprequest,domain=imasdk.googleapis.com`
to fix that isssue though.

**Comment by okiehsch** [comment]
@xDarkARG do you have a specific link that redirects you to `https://einthusan.tv/adblocker/`?

**Comment by xDarkARG** [comment]
video review  @okiehsch  @mapx-

https://streamable.com/s/9zobu/waowio

**Comment by okiehsch** [comment]
Thanks for the feedback, I followed the steps in your video, but I never get redirected, tried with different browsers with the same result, maybe mapx- or somebody else can reproduce.

**Comment by mapx-** [comment]
me neither ... probably xDarkARG enabled some other blocking extension

**Comment by xDarkARG** [comment]
I already solved the problem I reinstalled the extension and de-popped the Pop up blocker and it does not show anymore @okiehsch @mapx-



it could be that the page detected this extension as a blocker that's why it came out
`https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche?hl=es`
