### ISSUE TITLE
csgo.steamanalyst.com: ads

### ISSUE THREAD

**Issue by jathoms** [uBlockOrigin/uAssets#11529]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://csgo.steamanalyst.com/id/308129714/Fracture%20Case`

### Category

ads

### Describe the issue

Ads still shown on website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 79733
  cosmetic: 40767
  scriptlet: 16481
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63572-9, 3d.22h.37m
    easyprivacy: 26677-17, 3d.22h.36m
    plowe-0: 3679-817, 23h.55m
    ublock-abuse: 77-0, 3d.22h.39m
    ublock-badware: 3816-69, 3d.22h.41m
    ublock-filters: 30266-153, 3d.22h.42m
    ublock-privacy: 195-2, 3d.22h.40m
    ublock-unbreak: 1686-39, 3d.22h.38m
    urlhaus-1: 8270-0, 7h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 288 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by BottledSoda** [comment]
@ryanbr
