### ISSUE TITLE
livetv.video: detection

### ISSUE THREAD

**Issue by 72pinkush** [uBlockOrigin/uAssets#11534]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://livetv.video/`

### Category

detection

### Describe the issue

The website detects uBlock Origin and doesn't allow access. Everything works fine when uBlock Origin is off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.9b7
Chromium: 95
filterset (summary): 
  network: 78594
  cosmetic: 40828
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62544-9, now
    easyprivacy: 26691-18, now
    plowe-0: 3680-817, now
    ublock-abuse: 77-0, now
    ublock-badware: 3831-70, now
    ublock-filters: 30176-146, now
    ublock-privacy: 194-2, now
    ublock-unbreak: 1694-39, now
    urlhaus-1: 8270-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1797 ms
  maxAssetCacheWait: 244 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    livetv.video: 1
    groundedreason.com: 1
    laidwhenadmiring.com: 1
    videocdn.click: 1
```
</details>

**Comment by okiehsch** [comment]
I can reproduce
`https://livetv.video/stream.php?id=eurosport-1`
![image](https://user-images.githubusercontent.com/16838044/151952494-f75861c5-5bb4-4eca-a751-48903e073a4e.png)

**Comment by 72pinkush** [comment]
nevermind I'm dumb, just scroll down. The website only loads an extra bit for detecting ublock but doesn't block access.

**Comment by okiehsch** [comment]
It's still an issue we will fix in uBO-filters, because just like you and me many users will think that access has been blocked entirely.

**Comment by uBlock-user** [comment]
@okiehsch bait -- `videocdn.click/reclama/ads.js`

**Comment by okiehsch** [comment]
I know I already have a working fix
`livetv.video##+js(set, canRunAds, true)`

**Comment by uBlock-user** [comment]
Btw the video still plays, you have scroll down though.

**Comment by okiehsch** [comment]
Yes. Still it's more than an annoyance in my opinion.

**Comment by uBlock-user** [comment]
We should start using `canrunads.js` redirect resource once dev goes stable.

**Comment by okiehsch** [comment]
Yes.

**Comment by the-poor-gamer-124** [comment]
Go to paid sites if you do not like free sites`s policies
