### ISSUE TITLE
skidrowcrack.com [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1153]
URL(s) where the issue occurs

http://www.skidrowcrack.com/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
No popup here !!

test
`skidrowcrack.com##script:inject(popads.net.js)`

**Comment by okiehsch** [comment]
`skidrowcrack.com##script:inject(nowebrtc.js)` actually, the popads popups are already disabled by `EasyList`.

**Comment by SMed79** [comment]
I updated my filters. Thx.
