### ISSUE TITLE
[nsfw] pinayvids.com: nuisance

### ISSUE THREAD

**Issue by Norvelas** [uBlockOrigin/uAssets#11530]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pinayvids.com/`

### Category

nuisance

### Describe the issue

Has an overlay the stops access from site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78819
  cosmetic: 40768
  scriptlet: 16491
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62448-9, 2d.2h.51m
    easyprivacy: 26679-18, 2d.2h.50m
    plowe-0: 3679-817, 2d.2h.49m
    ublock-abuse: 77-0, 2d.2h.47m
    ublock-badware: 3831-68, 2d.2h.45m
    ublock-filters: 30294-249, 2d.2h.44m
    ublock-privacy: 194-2, 2d.2h.43m
    ublock-unbreak: 1692-41, 2d.2h.42m
    urlhaus-1: 8539-0, 20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 299 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by mapx-** [comment]
update your lists, already fixed
