### ISSUE TITLE
[nsfw] f2.app.edmentum.com: breakage

### ISSUE THREAD

**Issue by Domhashacks** [uBlockOrigin/uAssets#11536]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://f2.app.edmentum.com/assessments-delivery/ua/mt/launch/49548240/45508687/aHR0cHM6Ly9mMi5hcHAuZWRtZW50dW0uY29tL2xlYXJuZXItdWkvc2Vjb25kYXJ5L3VzZXItYXNzaWdubWVudC80OTU0ODI0MC9sYXVuY2hwYWQvNDU1MDg2ODQ%3d`

### Category

breakage

### Describe the issue

wont let me geto on stuff

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 77725
  cosmetic: 40827
  scriptlet: 16484
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62544-9, 40m
    easyprivacy: 26691-18, 39m
    plowe-0: 3676-817, 9d.21h.21m
    ublock-abuse: 77-0, 38m
    ublock-badware: 3831-70, 37m
    ublock-filters: 30178-146, 36m
    ublock-privacy: 194-2, 35m
    ublock-unbreak: 1692-39, 34m
    urlhaus-1: 7406-0, 33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1932 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by okiehsch** [comment]
You would need to provide us with your logger output, or simply whitelist the site.
https://github.com/gorhill/uBlock/wiki/The-logger
https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites
