### ISSUE TITLE
rudaw.net: breakage

### ISSUE THREAD

**Issue by reyis4402** [uBlockOrigin/uAssets#11533]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rudaw.net/`

### Category

News

### Describe the issue

Visit mobile view of website and scroll sideways. second pass won't open

### Screenshot(s)

![Screenshot_20220201-111708_Mull](https://user-images.githubusercontent.com/60405617/151934931-80c1441e-0568-41de-9f9c-72d841319e67.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 96
filterset (summary): 
  network: 151375
  cosmetic: 183389
  scriptlet: 32943
  html: 628
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61397-4810, 3d.14h.24m
    adguard-spyware: 28256-1254, 3d.14h.23m
    adguard-spyware-url: 456-3, 3d.15h.44m
    block-lan: 44-0, 7d.16h.51m
    curben-phishing: 8900-3, 11h.44m
    adguard-annoyance: 49701-4230, 3d.14h.58m
    adguard-social: 15689-21, 3d.15h.43m
    fanboy-thirdparty_social: 69-0, 7d.16h.51m
    fanboy-annoyance: 60120-45115, 7d.16h.51m
    fanboy-cookiemonster: 21765-129, 7d.16h.51m
    fanboy-social: 23161-1085, 3d.15h.45m
    ublock-annoyances: 4395-4, 3d.14h.21m
    dpollock-0: 10346-532, 7d.16h.51m
    mvps-0: 8730-1519, 7d.16h.51m
  default: 
    ublock-filters: 30964-50, 3d.14h.20m
    ublock-badware: 3835-1, 3d.14h.19m
    ublock-privacy: 193-0, 3d.14h.18m
    ublock-abuse: 77-0, 3d.14h.17m
    ublock-unbreak: 1703-0, 3d.14h.16m
    adguard-mobile: 7149-18, 3d.16h.10m
    easylist: 63629-1007, 3d.13h.54m
    easyprivacy: 26677-11035, 3d.13h.53m
    urlhaus-1: 8539-0, 11h.43m
    plowe-0: 3678-141, 7d.16h.50m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1700 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by RumpleThump** [comment]
@ryanbr 

`/pixel.gif?` ~> **EasyPrivacy**
<details>
<summary>Screenshot(s)</summary>

![2022-02-01_093346](https://user-images.githubusercontent.com/98751006/151941545-b2156072-2034-4c72-ab6d-9c8e21b4eaab.png)
</details>
