### ISSUE TITLE
classcentral.com: ads

### ISSUE THREAD

**Issue by KasimirRomer** [uBlockOrigin/uAssets#11538]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.classcentral.com/`

### Category

ads

### Describe the issue

When selecting a subject or a university on the classcentral site, a list of all courses appears. In this list, some of the entries are ads, only shown with a little "Ad" sign in the top right corner. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![classcentral ad](https://user-images.githubusercontent.com/47687775/152046604-4f1a9782-3154-4d49-ae47-628bab09020a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78885
  cosmetic: 40823
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
  default: 
    easylist: 62537-9, 1d.53m
    easyprivacy: 26677-18, 3d.23h.8m
    plowe-0: 3676-817, 11d.1m
    ublock-abuse: 77-0, 1d.54m
    ublock-badware: 3831-70, 1d.52m
    ublock-filters: 30176-146, 13h
    ublock-privacy: 194-2, 1d.56m
    ublock-unbreak: 1692-39, 1d.55m
    urlhaus-1: 8583-0, 10h.12m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 189 ms (selfie)
popupPanel: 
  blocked: 5
```
</details>

**Comment by BottledSoda** [comment]
@ryanbr

**Comment by mapx-** [comment]
`classcentral.com##li:has(iframe)`
