### ISSUE TITLE
layrite.com: breakage

### ISSUE THREAD

**Issue by kwalbright** [uBlockOrigin/uAssets#11539]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://layrite.com/collections/wash/products/daily-shampoo`

### Category

breakage

### Describe the issue

The Add to Cart button won't show up on this one item. It works on the other items. There is just a loading animation forever. I turned uBO off and reloaded, and it displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/53408516/152083570-d52262cf-0478-454b-9925-315503fea0cd.png)
![image](https://user-images.githubusercontent.com/53408516/152083603-50d543ac-ebba-4eb1-81d4-16e40a14ad82.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78907
  cosmetic: 40829
  scriptlet: 16444
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30750-27, 1d.4m
    ublock-badware: 3835-1, 1d.3m
    ublock-privacy: 193-0, 1d.2m
    ublock-abuse: 77-0, 1d.1m
    ublock-unbreak: 1704-0, 1d
    easylist: 62542-591, 23h.59m
    easyprivacy: 26691-480, 23h.58m
    urlhaus-1: 8583-0, 23h.57m
    plowe-0: 3676-2, 10d.20h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 952 ms (selfie)
popupPanel: 
  blocked: 41
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||google-analytics.com/analytics.js$domain=layrite.com,script,redirect-rule=google-analytics.com/analytics.js
```

**Comment by BottledSoda** [comment]
@ryanbr

**Comment by Procyon-b** [comment]
@BottledSoda @ryanbr 
This is an ublock issue only. It's caused by the redirect rule that uBO uses to defuse that script.
What the filter I propose is doing is it "cancels" the redirect rule only for that domain. The original script is still blocked, but the page doesn't fail.
I can use the $bafilter because it will cancel the redirect-rule for all domain, and you can add a $domain= to a $badfilter if it's not part of the original filter. Using an @@ rule with the redirect seems to achived the desired effect.

**Comment by BottledSoda** [comment]
I think you're right!
