### ISSUE TITLE
[nsfw] manhwaid.org: ads

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11542]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manhwaid.org/manga/learning-the-hard-way/chapter-1/?style=paged`

### Category

ads

### Describe the issue

empty space / frame

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/56762704/152113810-24895407-eb43-4f01-bca9-7daf3325697f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 99
filterset (summary): 
  network: 81481
  cosmetic: 138396
  scriptlet: 22250
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1824-9, 1d.47m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6012-3, 1d.47m
    adguard-annoyance: 49761-169, 1d.47m
    fanboy-annoyance: 60340-2849, 1d.47m
    ublock-annoyances: 4375-270, 1d.47m
  default: 
    easylist: 62544-1245, 1d.47m
    easyprivacy: 26691-110, 1d.47m
    ublock-abuse: 77-0, 1d.47m
    ublock-badware: 3831-69, 1d.47m
    ublock-filters: 30176-539, 1d.47m
    ublock-privacy: 194-9, 1d.47m
    ublock-unbreak: 1693-44, 1d.47m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1019 ms (selfie)
popupPanel: 
  blocked: 11
```
</details>

**Comment by uBlock-user** [comment]
```
manhwaid.org##div.c-top-sidebar.c-sidebar[style=" padding:50px 5px ; "]
manhwaid.org##div.wp-manga.c-top-sidebar.c-sidebar[style=""]
```
