### ISSUE TITLE
fullhdfilmizlesene.pw: ads

### ISSUE THREAD

**Issue by sahin41** [uBlockOrigin/uAssets#11549]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fullhdfilmizlesene.pw/`

### Category

ads

### Describe the issue

Hello;

This website show me ads. Please fix it.
Best regarts.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2022-02-02 at 20-57-40 FullHDFilmizlesene pw Full HD Film İzleme Keyfinin Tadını Çıkarın](https://user-images.githubusercontent.com/72725048/152210925-39e89a54-8927-4c74-b149-dbe1bbde5240.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79878
  cosmetic: 47315
  scriptlet: 16774
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30754-39, 4m
    ublock-badware: 3835-1, 4m
    ublock-privacy: 193-0, 4m
    ublock-abuse: 77-0, 4m
    ublock-unbreak: 1706-0, 4m
    easylist: 62750-604, 4m
    easyprivacy: 26693-485, 4m
    urlhaus-1: 7496-0, 4m
    plowe-0: 3680-2, 4m
    TUR-0: 8773-91, 5m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 339 ms
popupPanel: 
  blocked: 2
```
</details>

**Comment by BottledSoda** [comment]
to be fix by an AdGuard team member / contribuitor in AdGuard Turkish


@Yuki2718

**Comment by Procyon-b** [comment]
Try this filter:
```
fullhdfilmizlesene.pw##body>.psk
```

**Comment by uBlock-user** [comment]
@AdamWr

**Comment by BottledSoda** [comment]
Seems like this issue can be closed
