### ISSUE TITLE
allstreaming.online: detection

### ISSUE THREAD

**Issue by cmxkqmoyrp** [uBlockOrigin/uAssets#11547]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://allstreaming.online/`

### Category

detection

### Describe the issue

Anti adblock script Immediately after clicking the link

### Screenshot(s)

![Screenshot_20220202-183620_Firefox](https://user-images.githubusercontent.com/98906591/152207696-787da16e-e3c7-411f-a0ef-02cad3984314.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 97
filterset (summary): 
  network: 80013
  cosmetic: 21948
  scriptlet: 16421
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30732-361, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-1, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1725-0, never
    adguard-mobile: 7163-321, never
    easylist: 62254-23888, never
    easyprivacy: 26549-28, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-458, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5866 ms
popupPanel: 
  blocked: 17
```
</details>

**Comment by BottledSoda** [comment]
`allstreaming.online##+js(no-xhr-if, adsbygoogle)`

**Comment by PerfectSalad** [comment]
`.fake_player`-containing code
