### ISSUE TITLE
findbolig.nu: breakage

### ISSUE THREAD

**Issue by freyacodes** [uBlockOrigin/uAssets#11546]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.findbolig.nu/ledigeboliger/liste.aspx?&showrented=1&showyouth=1&showlimitedperiod=1&showunlimitedperiod=1&showOpenDay=0`

### Category

breakage

### Describe the issue

uBlockOrigin blocks the addresses and images of these housing listings

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlockOrigin:

![image](https://user-images.githubusercontent.com/2582617/152168311-faad808e-12d9-4e71-9f5a-2c85175db18c.png)

Without:

![image](https://user-images.githubusercontent.com/2582617/152168407-65e81fed-785d-4b97-948b-ea1a2a5832bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 89
filterset (summary): 
  network: 77676
  cosmetic: 40783
  scriptlet: 16457
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30884-30, 3d.21h.42m
    ublock-badware: 3820-1, 3d.21h.43m
    ublock-privacy: 193-0, 3d.21h.41m
    ublock-abuse: 77-0, 3d.21h.39m
    ublock-unbreak: 1697-0, 3d.21h.38m
    easylist: 62448-690, 3d.21h.37m
    easyprivacy: 26679-480, 3d.21h.36m
    urlhaus-1: 7406-0, 15h.48m
    plowe-0: 3679-2, 7d.19h.4m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 944 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Looks danish to me.
@DandelionSprout 
`findbolig.nu#@#.advertLink`

**Comment by okiehsch** [comment]
@freyacodes you can add the filter I posted above to your filter list or wait until it's fixed in the regional danish list and enable it.
![image](https://user-images.githubusercontent.com/16838044/152170422-9bd732ba-9209-4bee-b3ad-7fdacc6fb232.png)

**Comment by DandelionSprout** [comment]
It is indeed Danish. Give me 4min to look through the situation.
