### ISSUE TITLE
gamekult.com : breakage

### ISSUE THREAD

**Issue by noisegratte** [uBlockOrigin/uAssets#11544]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gamekult.com`

### Describe the issue

Header doesn't work as expected on scroll and the website's logo is not displayed anymore

### Screenshot(s)

Without filter :

![image](https://user-images.githubusercontent.com/371864/152140135-5aae2a51-7e44-463d-ac0c-bb496c300d19.png)

With filter :

![image](https://user-images.githubusercontent.com/371864/152140240-a1822ee0-24bf-4aa3-999b-7732f54b6c7c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 94164
  cosmetic: 50030
  scriptlet: 16494
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30750-199, now
    ublock-badware: 3835-1, now
    ublock-privacy: 193-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1705-0, now
    easylist: 62719-671, now
    easyprivacy: 26693-480, now
    urlhaus-1: 7406-0, now
    plowe-0: 3680-2, now
    FRA-0: 26164-365, now
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 233 ms (selfie)

```
</details>

**Comment by uBlock-user** [comment]
@AdamWr
