### ISSUE TITLE
Twitch.tv volume slider filtered by cosmetic filtering

### ISSUE THREAD

**Issue by kareemserry** [uBlockOrigin/uAssets#11553]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.twitch.tv/chess
https://www.twitch.tv/mongraal
```

### Describe the issue

In the lower left section of a twitch stream there is a pause/mute button. Usually hovering over the mute button shows a volume slider but it seems that cosmetic filtering is removing it.

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Firefox 96.0.3 (64-bit)

### Settings

no changes

**Comment by uBlock-user** [comment]
Test on default settings/lists + all other extensions disabled.
