### ISSUE TITLE
scan-manga.com: nuisance

### ISSUE THREAD

**Issue by Dugur32** [uBlockOrigin/uAssets#11557]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.scan-manga.com/lecture-en-ligne/The-Lazy-Prince-Becomes-a-Genius-Chapitre-39-FR_222582.html`

### Category

nuisance

### Describe the issue

![Capture d’écran 2022-02-02 210503](https://user-images.githubusercontent.com/98802501/152228782-e9ecd8e3-f4d4-459d-a3f1-06df930eecfd.png) : with

![Capture d’écran 2022-02-02 210702](https://user-images.githubusercontent.com/98802501/152229075-adf98da3-9969-4802-917b-c3de362b021b.png) : without

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 94335
  cosmetic: 50033
  scriptlet: 16534
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26168-23, 5h.56m
    easylist: 62719-100, 5h.55m
    easyprivacy: 26693-343, 6h.2m
    plowe-0: 3679-825, 5d.2h.23m
    ublock-abuse: 77-1, 6h.1m
    ublock-badware: 3831-78, 6h
    ublock-filters: 30178-306, 5h.59m
    ublock-privacy: 194-2, 5h.58m
    ublock-unbreak: 1694-39, 5h.57m
    urlhaus-1: 7582-0, 5h.54m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 179 ms (selfie)
popupPanel: 
  blocked: 10
```
</details>

**Comment by Dugur32** [comment]
this is the same for the whole site

**Comment by okiehsch** [comment]
@adamwr `scan-manga.com#@#.top_body` fixes the issue on my end.

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by Dugur32** [comment]
ok thanks
