### ISSUE TITLE
rossmann.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#11550]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.rossmann.de/de/tier-winston-nature-mit-ente-und-huhn/p/4305615592855`

### Describe the issue

I can't write reviews

### Screenshot(s)

<img width="571" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/152212301-721f3763-8e8f-4862-852a-55c516223be0.PNG">

### uBlock Origin version

1.40.8

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances 

### Notes

Whitelisting `mpsnare.iesnare.com/snare.js` works for me

**Comment by uBlock-user** [comment]
`||mpsnare.iesnare.com/snare.js^$script,redirect-rule=noopjs,domain=rossmann.de` works ?

**Comment by JobcenterTycoon** [comment]
I already tested it it not works (button for puplish is broken with this)
