### ISSUE TITLE
www.comandotorrents.com

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#1155]
www.comandotorrents.com

`www.comandotorrents.com###box`

check box

**Comment by nimasaj** [comment]
I didn't find any issues with this website, though you could apply the following rule as a cosmetic filter.
`##a[href*="/ads?"]`

please explain the issue thoroughly with pictures.

**Comment by SMed79** [comment]
@mapx- you have missed the ad video (iframe).
```
/ad/play1.
/ad/View3.
.us/ad/*
.com/ad1/*
```
* http\://portalgames.us/ad/View3.js?nocache
* http\://www.bludvfilmes.com/ad1/View.js?nocache

for easyprivacy ~
```
/JqueryEtracker.
.iframetracker/*
.iframetracker.
```

@ryanbr fyi.

**Comment by mapx-** [comment]
all of those items going in easylist / easyprivacy, this is only annoyances list

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a31bfaa85fccef2fc37227399447243ddc4a55f7

I believe blocking /jquery.iframetracker.min.js would cause fp's

**Comment by xqk94524** [comment]
this filter is also needed 
`www.comandotorrents.com###modal`

**Comment by mapx-** [comment]
it was added in fanboy's annoyances list
