### ISSUE TITLE
[nsfw] shouchaobao.com: ads

### ISSUE THREAD

**Issue by LiQVQ** [uBlockOrigin/uAssets#11563]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.shouchaobao.com/jingdiansongdu/8281.html`

### Category

ads

### Describe the issue

使用后仍有广告

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 96398
  cosmetic: 50925
  scriptlet: 16590
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 27796-89, 1d.21h.16m
    easylist: 62783-19, 1h.7m
    easyprivacy: 26695-44, 1h.11m
    plowe-0: 3680-819, 22m
    ublock-abuse: 81-0, never
    ublock-badware: 3629-68, never
    ublock-filters: 30184-167, 1h.9m
    ublock-privacy: 184-3, never
    ublock-unbreak: 1694-40, 1h.8m
    urlhaus-1: 8575-0, 21h.14m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1784 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by mapx-** [comment]
`||fafa.tuku.com^$domain=shouchaobao.com`

@Yuki2718
