### ISSUE TITLE
theguardian.com: breakage

### ISSUE THREAD

**Issue by alas-he** [uBlockOrigin/uAssets#11564]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theguardian.com/`

### Category

breakage

### Describe the issue

Page jumps to top after loading every page. Doesn't do this on desktop, only mobile. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 96
filterset (summary): 
  network: 81375
  cosmetic: 104903
  scriptlet: 21423
  html: 627
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    adguard-annoyance: 49761-1501, 2d.11h.57m
    adguard-social: 15699-18, 3d.6h.54m
    fanboy-thirdparty_social: 69-0, 5h.15m
    ublock-annoyances: 4398-4, 3d.6h.53m
  default: 
    ublock-filters: 30857-45, 5h.13m
    ublock-badware: 3835-1, 1d.13h.41m
    ublock-privacy: 193-0, 3d.6h.52m
    ublock-abuse: 77-0, 1d.13h.40m
    ublock-unbreak: 1713-0, 5h.14m
    adguard-mobile: 7163-18, 5h.12m
    easylist: 62497-407, 3d.6h.49m
    easyprivacy: 26691-38, 1d.22h.53m
    urlhaus-1: 7496-0, 1d.2h.12m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6728 ms (selfie)
popupPanel: 
  blocked: 29
```
</details>

**Comment by mapx-** [comment]
> Page jumps to top after loading every page

When you load a new page (click a new article) it seems normal to be at the top ?!
Provide more details on how to reproduce the issue

**Comment by BottledSoda** [comment]
@mapx- Did you test on mobile?

**Comment by gwarser** [comment]
It jumps to top after going back to home after reading any article.

**Comment by mapx-** [comment]
Adguard annoyances has already this filter

`@@||cdn.privacy-mgmt.com/consent/`

![image](https://user-images.githubusercontent.com/10303732/152418940-200452e2-8c47-4fe3-8ddd-7b2accfab843.png)

**Comment by alas-he** [comment]
Can be reproduced by starting to scroll the page before it completes loading, and then it will jump back to top.  Or by following a link to an anchor part way down a page, it will then jump to the top. 

I've tested without annoyances filters, it still jumps to top but also shows overlay panel. Issue is only on mobile,  desktop seems to work fine.

**Comment by mapx-** [comment]
Still cannot reproduce your issue.

**Comment by alas-he** [comment]
Perhaps with link like this one to mid page anchor? https://www.theguardian.com/australia-news/live/2022/feb/04/australia-live-news-updates-scott-morrison-coronavirus-omicron-weather-nsw-victoria-queensland-western-australia?filterKeyEvents=false&page=with:block-61fc44038f08df1d7f09008f#block-61fc44038f08df1d7f09008f

**Comment by mapx-** [comment]
No jump to the top, tested on real android and using BlueStacks Android Emulator too

**Comment by alas-he** [comment]
OK I've now tried uninstalling uBO, reinstalling and then activating the same list of filters as previously used. And now the issue is no longer occurring. I'm not sure what caused it, but I guess this can now be closed. :)
