### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1157]
Problem solved.

**Comment by mapx-** [comment]
I'm able to reproduce the issue only using chrome (and the polish list)

test this filter (working for me)
`komputerswiat.pl#@#.adsense`

However, you should update firefox to the last 57 (FF 56 is buggy)

**Comment by hawkeye116477** [comment]
Problem already solved, but thanks :smile:.
