### ISSUE TITLE
shoppingcart.aliexpress.com: breakage

### ISSUE THREAD

**Issue by ccondrup** [uBlockOrigin/uAssets#11572]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shoppingcart.aliexpress.com/shopcart/shopcartDetail.htm`

### Category

breakage

### Describe the issue

From ali shopping cart, clicking "move to wishlist" has failed the last few weeks. I only noticed today that Network log says "Blocked by uBO". Kudos to you for the great service! I hope this is sufficient info:

The response from the 200 OK GET is
 `__zoro_request_3({"ec":3,"em":"csrf token error","data":{}})`

Then, the POST url that fails (I modified var values):
 `https://retcode-us-west-1.arms.aliyuncs.com/r.png?t=api&times=1&page=en_shopCartPage&tag=&release=&environment=prod&api=%2F%2Fmy.aliexpress.com%2Fwishlist%2Fadd_to_wish_list_new.htm&success=1&time=267&code=SUCCESS&msg=&traceId=&pv_id=s3kt7z1X29f02ht0htLsk&domain=&sr=1760x1100&vp=1760x457&ct=&uid=qOkhRzp67fds0922das&sid=84209dssdgt8hm&pid=f1f11112w%40d612222a2&_v=1.8.30&sampling=1&dl=https%3A%2F%2Fshoppingcart.aliexpress.com%2Fshopcart%2FshopcartDetail.htm&z=kd83333hw&post_res=`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ali1](https://user-images.githubusercontent.com/84788/152416661-a37829fb-ce13-4603-b81b-6b90aa2cdac5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78156
  cosmetic: 40861
  scriptlet: 16450
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30755-27, 25m
    ublock-badware: 3835-1, 25m
    ublock-privacy: 193-0, 25m
    ublock-abuse: 77-0, 25m
    ublock-unbreak: 1707-0, 25m
    easylist: 62801-595, 25m
    easyprivacy: 26695-480, 25m
    plowe-0: 3680-2, 25m
    urlhaus-1: 7599-0, 25m
filterset (user): [empty]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 696 ms (selfie)
popupPanel: 
  blocked: 91
```
</details>

**Comment by Procyon-b** [comment]
For me, adding an item to the shopping cart works. But the counter on the shopping cart icon is not updated.

**Comment by mapx-** [comment]
I tried to add to the wish list disabling completely uBO, I get an error:

`Oops! The item wasn't added due to network errors. Try again later. 3`

**Comment by Procyon-b** [comment]
Maybe different pages due to geolocation. I know I had to click "us version" to switch from the localized version.
