### ISSUE TITLE
ppss.kr

### ISSUE THREAD

**Issue by smbslt3** [uBlockOrigin/uAssets#11577]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ppss.kr/`

### Describe the issue

In every articles at `ppss.kr` likes `https://ppss.kr/archives/250792?fbclid=IwAR02WFjHFPvO2AqDgVB7ztGpNgOkkz8-LCKoVocy1nPFnEvCSy37W4XPHz8` , the image of article filtered with ads

### uBlock Origin version

1.40.8

### Browser name and version

Chrome, 97

### Settings

- Everything default 
- only active `uBlock filters`

**Comment by Procyon-b** [comment]
Try this filter:
```
||ppss.kr^$badfilter,csp=script-src *
```

**Comment by mapx-** [comment]
They are rewriting all uBO scriptlets so needing some protection

something more classic but not fixing all ads

```
||ppss.kr^$csp=script-src *,badfilter
ppss.kr#@#+js(aost, XMLHttpRequest.prototype.send, /th:\d+\s+[a-zA-Z]\d\/<@[^\t]+\t\s[a-zA-Z]\d@|th:\d+\s+in[a-zA-Z\d:;]+\t\s[a-zA-Z]\d\si/)
ppss.kr#@#.custom-html-widget.textwidget
ppss.kr##.custom-html-widget.textwidget:style(height: 50px; width: 50px;)
ppss.kr##[href^="https://3o3.co.kr/"]
ppss.kr##[href*="adtouch"]
ppss.kr##[href^="https://myssing.com/"]
ppss.kr##[href^="https://www1.president.go.kr/"]
ppss.kr##[href="http://www.allla.co.kr/"]
```

**Comment by mapx-** [comment]
@gorhill

**Comment by uBlock-user** [comment]
> They are rewriting all uBO scriptlets

https://github.com/uBlockOrigin/uBlock-issues/issues/1741

**Comment by JobcenterTycoon** [comment]
@smbslt3 try my filters from these comments it hides all ads on ppss, ygosu and inven without breakage on my end:

https://github.com/AdguardTeam/AdGuardExtra/issues/294#issuecomment-1022524626
https://github.com/AdguardTeam/AdGuardExtra/issues/294#issuecomment-1022529565

its a cat and mouse play they self breaking their website if the script detects adblocking

**Comment by smbslt3** [comment]
I'm sorry to say that I have applied all @Procyon-b , @mapx-  and @JobcenterTycoon 's suggestions, but they are not work well.

When I (re)load the pages(in ppss.kr), the images are shown and ads are blocked, it seems work. 
But after 1~3 seconds, the images are blocked and one of the ads are shown.

**Comment by JobcenterTycoon** [comment]
For me it works perfectly (To cover the other non protected ads enable KOR: YousList) even with this list enabled i get no breakage

**Comment by JobcenterTycoon** [comment]
I wonder why its marked with `can’t fix` its still fixable with classic filter

**Comment by mapx-** [comment]
is it already fixed in korean list ?
if not just propose a PR
