### ISSUE TITLE
rutracker-org.appspot.com: breakage => fake mirror

### ISSUE THREAD

**Issue by Falcordog** [uBlockOrigin/uAssets#11574]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rutracker-org.appspot.com/forum/viewforum.php?f=1027`

### Category

breakage

### Describe the issue

Opens white page.
No point attaching screenshot.
Disabling uBo opens the page normally (inc ads)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 483546
  cosmetic: 229998
  scriptlet: 53390
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/: 347554-0, 19h.3m
    https://raw.githack.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 27118-21, 19h.2m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1709-0, 18h.59m
    https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt: 14-0, 4d.17h.40m
    https://www.i-dont-care-about-cookies.eu/abp/: 24288-14, 2d.17h.9m
    CHN-0: 27793-6161, 2d.17h.11m
    ISR-0: 1617-16, 19h.1m
    RUS-0: 41122-1096, 4h.25m
    adguard-annoyance: 49761-1999, 2d.17h.20m
    adguard-generic: 61443-3167, 2d.17h.19m
    adguard-mobile: 7157-799, 2d.17h.23m
    adguard-social: 15714-785, 2d.17h.22m
    adguard-spyware: 25859-9996, 2d.17h.21m
    adguard-spyware-url: 456-82, 2d.17h.24m
    block-lan: 44-0, 3d.21h.37m
    curben-phishing: 9609-392, 19h
    fanboy-annoyance: 63616-15068, 5d.21h.34m
    fanboy-cookiemonster: 22087-22007, 1m
    fanboy-social: 23162-23161, 2d.17h.10m
    fanboy-thirdparty_social: 68-21, 5d.21h.33m
    [1 lists not shown]: [too many]
  default: 
    easylist: 62544-13623, 2d.17h.17m
    easyprivacy: 26691-13252, 2d.17h.16m
    plowe-0: 3680-3335, 1d.23h.13m
    ublock-abuse: 77-5, 2d.17h.15m
    ublock-badware: 3831-731, 2d.17h.14m
    ublock-filters: 30177-6423, 8h.26m
    ublock-privacy: 194-63, 2d.17h.13m
    ublock-unbreak: 1693-111, 2d.17h.12m
    urlhaus-1: 7599-1231, 19h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 732 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by Procyon-b** [comment]
The filter that hides the page is in the RUS list: `rutracker-org.appspot.com##*`
Then there is a filter that block the stylesheet:  `/userads/*` in easylist
Add these filters to solve your issue:
```
rutracker-org.appspot.com#@#*
@@||cn919.chickenkiller.com^$css,domain=rutracker-org.appspot.com
```

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is a fake mirror created for the purpose of stealing accounts.

**Comment by Procyon-b** [comment]
@dimisa-RUAdList I was suspecting something bad when I saw your general filter.

**Comment by uBlock-user** [comment]
@dimisa-RUAdList So why don't you block the entire site ? The current filter is not ideal and only causes confusion.
