### ISSUE TITLE
reshade.me: breakage

### ISSUE THREAD

**Issue by CeeJayDK** [uBlockOrigin/uAssets#11575]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://reshade.me/forum`

### Category

breakage

### Describe the issue

It's not possible to login as a user when Ublock is enabled.

I believe the reason is the cookie acceptance banner is blocked, and if the cookie is not set one cannot log in.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/3244252/152445657-24f637f1-bb25-405a-a88a-d94a51cbd532.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 96836
  cosmetic: 96940
  scriptlet: 30187
  html: 625
listset (total-discarded, last updated): 
  added: 
    https://adblock.dk/block.csv: 870-5, 22h.15m
    https://www.i-dont-care-about-cookies.eu/abp/: 24312-3, 6h.54m
    ublock-annoyances: 4378-4, 3d.20h.30m
    adguard-generic: 61404-4734, 3d.20h.25m
    NOR-0: 2654-15, 22h.16m
  default: 
    ublock-filters: 30745-30, 3d.20h.34m
    ublock-badware: 3835-1, 3d.20h.33m
    ublock-privacy: 193-0, 3d.20h.26m
    ublock-abuse: 77-0, 3d.20h.32m
    ublock-unbreak: 1703-0, 3d.20h.29m
    easylist: 62497-594, 3d.20h.28m
    easyprivacy: 26685-482, 3d.20h.27m
    plowe-0: 3680-2, 3d.1h.14m
    urlhaus-1: 7582-4, 22h.14m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 39 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1888 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by Procyon-b** [comment]
Try these filters to unhide the cookie dialog:
```
reshade.me#@#.activebar-container
@@/media/plg_system_eprivacy$domain=reshade.me
```

**Comment by CeeJayDK** [comment]
Yes, that works.
Thank you.

**Comment by Procyon-b** [comment]
I assume yes. When I reload the page after accepting the cookies, I don't see the dialog anymore.

**Comment by BottledSoda** [comment]
@kiboke

**Comment by mapx-** [comment]
Breakage using either `adguard annoyances` or `fanboy's annoyances`

**Comment by kiboke** [comment]
@BottledSoda thanks, it will be fixed in IDCAC!
