### ISSUE TITLE
amazon.de: breakage

### ISSUE THREAD

**Issue by kreil** [uBlockOrigin/uAssets#11579]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.de/cpe/executions?startWidgetContextId=690151101`

### Category

breakage

### Describe the issue

When payment on amazon requires "3d" card verification, one is redirected to a widget by cardinal commerce, this displays a flicker code for a card reader. When the correct TAN is entered, the page should proceed to complete the purchase. Instead, it goes into an endless loop asking to log into your amazon account again. uBlock shows "Blocked on this page 155 (30%)".
Testing the page on a different browser without uBlock resolves the problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 80175
  cosmetic: 44072
  scriptlet: 16488
  html: 0
listset (total-discarded, last updated): 
  added: 
    DEU-0: 5332-0, 6h.23m
  default: 
    easylist: 62802-15, 6h.28m
    easyprivacy: 26694-29, 6h.27m
    plowe-0: 3679-818, 4d.6h.48m
    ublock-abuse: 77-0, 6h.26m
    ublock-badware: 3831-72, 6h.25m
    ublock-filters: 30181-156, 6h.24m
    ublock-privacy: 194-2, 6h.30m
    ublock-unbreak: 1696-40, 6h.29m
    urlhaus-1: 7530-0, 6h.22m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 643 ms (selfie)
popupPanel: 
  blocked: 137
```
</details>

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go into the logger and post here a screenshot containing only the blocked items you see there (you can select only the blocked items in the search box)
