### ISSUE TITLE
yourcountdown.to: ads

### ISSUE THREAD

**Issue by casualkitten1** [uBlockOrigin/uAssets#11573]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yourcountdown.to/dying-light-2`

### Category

ads

### Describe the issue

Ads can be seen at the top and the bottom of the page.

`https://www.awin1.com/cread.php?awinmid=1465&awinaffid=78426&clickref=yct-adsense-fallback`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/49318780/152436867-1838cb9b-4e0c-4e36-835e-f007265ba41a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 104879
  cosmetic: 143519
  scriptlet: 18855
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 49751-171, 3d.5h.50m
    fanboy-annoyance: 60328-2861, 3d.7m
  default: 
    FRA-0: 26164-23, 3d.6h
    easylist: 62503-130, 3d.5h.58m
    easyprivacy: 26685-434, 3d.5h.57m
    plowe-0: 3676-826, 12d.19m
    ublock-abuse: 77-1, 3d.5h.56m
    ublock-badware: 3831-76, 3d.5h.55m
    ublock-filters: 30171-629, 3d.5h.54m
    ublock-privacy: 194-10, 3d.5h.53m
    ublock-unbreak: 1692-44, 3d.5h.51m
    urlhaus-1: 7582-0, 1d.1h.49m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 807 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
yourcountdown.to##.adsense-fallback
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
I get only a PH at the top

`yourcountdown.to##.adsbygoogle`

**Comment by Procyon-b** [comment]
@mapx- I see the same ad as OP (there are 2 on the page) and your filter doesn't hide them.

![uBO-GH-assets-issue](https://user-images.githubusercontent.com/40043075/152441993-1d2aa37d-39a1-4548-ba1c-b4f3e1fa3a90.png)

**Comment by mapx-** [comment]
It's really weird, if I accept all cookies then the ads disappear.
If I use adguad annoyances I get the ads.

**Comment by Procyon-b** [comment]
> If I use adguad annoyances I get the ads.

If often forget that I have "I don't care about cookies" extension enabled. For this site it hides the dialog. Accepting the dialog switches to the other layout.
