### ISSUE TITLE
oremikids.com: breakage

### ISSUE THREAD

**Issue by dare102000** [uBlockOrigin/uAssets#11578]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://oremikids.com/`

### Category

breakage

### Describe the issue

email field at the bottom of the webpage disappears

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 146828
  cosmetic: 185060
  scriptlet: 33115
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 23m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 1d.10h.27m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 20h.54m
    adguard-annoyance: 49854-194, 1d.1h.43m
    adguard-generic: 61530-729, 1d.37m
    adguard-mobile: 7163-49, 1d.3h.27m
    adguard-social: 15755-796, 1d.3h.26m
    adguard-spyware: 25870-604, 1d.3h.25m
    dpollock-0: 10346-255, 5d.7h.29m
    fanboy-annoyance: 63816-7343, 20h.57m
    fanboy-cookiemonster: 22082-22082, 20h.56m
    fanboy-social: 23152-23150, 1d.3h.20m
    fanboy-thirdparty_social: 68-21, 20h.58m
    mvps-0: 8730-1758, 4d.23h.4m
    ublock-annoyances: 4375-300, 1d.36m
  default: 
    easylist: 62769-1358, 1d.3h.22m
    easyprivacy: 26693-10685, 1d.3h.21m
    plowe-0: 3679-1493, 6d.7h.33m
    ublock-abuse: 77-0, 1d.1h.40m
    ublock-badware: 3831-233, 1d.21h.10m
    ublock-filters: 30186-3321, 1d.35m
    ublock-privacy: 194-36, 1d.10h.25m
    ublock-unbreak: 1696-109, 1d.3h.19m
    urlhaus-1: 7599-0, 20h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 3129 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by Procyon-b** [comment]
It's caused by a filter in "_Fanboy's annoyances_"
add this filter:
```
oremikids.com#@#.newsletter-section:not(html):not(body)
```

Question: why have you selected all the stock filter lists ?

**Comment by mapx-** [comment]
@ryanbr
