### ISSUE TITLE
dlpsgame.org ads redirect

### ISSUE THREAD

**Issue by dkpeld** [uBlockOrigin/uAssets#11582]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

dlpsgame.org

### Describe the issue

Hello, this site has a redirect to the site with advertising, if you click anywhere, then with some probability it will first redirect to the site xdqsuypmch.com which later redirects to any other site with ads. You can get this simply by going to the site and clicking anywhere on the site, perhaps after a successful response, it waits 1-2 minutes and again can redirect to that site. I solved it with a rule `||xdqsuypmch.com^$popup` and it didn't show up for me anymore. I think this should be added to the general list, thanks.

### uBlock Origin version

uBlock Origin 1.40.8

### Browser name and version

Google Chrome 78.0.3904.108 

### Settings

||xdqsuypmch.com^$popup

**Comment by uBlock-user** [comment]
`dlpsgame.org##+js(abort-current-script, String.fromCharCode, break;case)` still works.
