### ISSUE TITLE
msci.com Constituents stuck on loading

### ISSUE THREAD

**Issue by tobbi** [uBlockOrigin/uAssets#11583]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.msci.com/constituents`

### Describe the issue

The select field "Select An Index Name:" is stuck on "Loading..." when using uBlock Origin.

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.3

### Settings

none

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by okiehsch** [comment]
@uBlock-user can you reproduce?

**Comment by uBlock-user** [comment]
I can if I remove all cookies and do a cache-free reload of the page.

**Comment by uBlock-user** [comment]
`@@||snap.licdn.com/li.lms-analytics/insight.min.js^$script,domain=msci.com` should fix it.

**Comment by uBlock-user** [comment]
@okiehsch Does the filter I posted work consistently ?

**Comment by okiehsch** [comment]
Yes.
