### ISSUE TITLE
No images on retrogames.cc

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#11588]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.retrogames.cc/

### Describe the issue

When ublock is enabled i cant see the images of the games in the site, this doesnt happen when ublock is disabled.

I made a search and didnt see any issue related to this site.

### Notes

Tested this on firefox/waterfox, the same problem happens in both.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.9rc0
Firefox: 96
filterset (summary): 
  network: 74911
  cosmetic: 94006
  scriptlet: 16499
  html: 615
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 60486-54, 4m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30756-48, 4m
    ublock-badware: 3835-1, 4m
    ublock-privacy: 193-0, 4m
    ublock-abuse: 77-0, 4m
    ublock-unbreak: 1710-0, 4m
    easylist: 62829-248, 4m
    easyprivacy: 26696-119, 4m
filterset (user): [empty]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6227 ms
  maxAssetCacheWait: 1223 ms
```
</details>

**Comment by uBlock-user** [comment]
Broken by Fanboy Annoyances list. @ryanbr

**Comment by Felipefpl** [comment]
Thanks for the tip, reported it here https://github.com/ryanbr/fanboy-adblock/issues/1509

**Comment by BottledSoda** [comment]
> Thanks for the tip, reported it here https://github.com/ryanbr/fanboy-adblock/issues/1509

Fanboy's Annoyances is maintained on https://github.com/easylist/easylist afaik

**Comment by Felipefpl** [comment]
BottledSoda - I see, thanks for the tip, i posted there.
