### ISSUE TITLE
sololearn.com: breakage

### ISSUE THREAD

**Issue by spaceKelan** [uBlockOrigin/uAssets#11580]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sololearn.com/learning/1158/4657/11934/1`

### Category

breakage

### Describe the issue

The comment functionality requires an account on the website itself. They are important to understand the lectures better.

**without** uBO I do see the comment section
![image](https://user-images.githubusercontent.com/51329415/152505311-551e7b02-237b-4da7-bbc1-ef368f3a806a.png)

with uBO I do not see the comment section 
![image](https://user-images.githubusercontent.com/51329415/152505882-756cd1ae-19c6-4fdf-9e9c-11222af49ff1.png)

### Screenshot(s)

<details>
<summary>Screenshots</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78139
  cosmetic: 40857
  scriptlet: 16444
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30746-27, 1d.29m
    ublock-badware: 3835-1, 1d.27m
    ublock-privacy: 193-0, 1d.26m
    ublock-abuse: 77-0, 1d.25m
    ublock-unbreak: 1705-0, 1d.24m
    easylist: 62783-593, 1d.23m
    easyprivacy: 26695-480, 1d.22m
    urlhaus-1: 7599-0, 1d.21m
    plowe-0: 3680-2, 1d.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 701 ms (selfie)
popupPanel: 
  blocked: 8
```
</details>

**Comment by okiehsch** [comment]
Wait a few minutes then update the `uBO-unbreak` list, should work fine after that.

**Comment by spaceKelan** [comment]
I just tried it, it works like a charm! Thank you!
