### ISSUE TITLE
meczyki.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1158]
### URL(s) where the issue occurs

`meczyki.pl`

### Describe the issue

Web-push notifications.

### Screenshot(s)

![screenshot_20180103_155613](https://user-images.githubusercontent.com/19818572/34525326-cb9915c6-f09e-11e7-83e6-5e6ce58cac7d.png)

### Versions

- Browser/version: Waterfox 56.0.1 / Firefox 56.0.2
- uBlock Origin version: 1.14.22

### Settings

- https://gist.github.com/hawkeye116477/32fb4ffe0e43b8295282662485cfec18

### Notes

I tried `||meczyki.pl/assets/js-compress/*$script`, but then some elements of the page are broken.

**Comment by mapx-** [comment]
try
`meczyki.pl##script:inject(abort-on-property-read.js, Notification.requestPermission)`

**Comment by hawkeye116477** [comment]
@mapx- It works, thanks :smile:.

**Comment by mapx-** [comment]
Could you report the issue at the polish list repository (to be added in the polish list)?

**Comment by hawkeye116477** [comment]
@mapx- I will add this to Polish Annoyance Filters.
