### ISSUE TITLE
mgronline.com: breakage

### ISSUE THREAD

**Issue by Norarit-Sae** [uBlockOrigin/uAssets#11589]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mgronline.com/japan/detail/9640000119771`

### Category

breakage

### Describe the issue

I read mgronline.com, a Thai news website. EasyList has blocked contents at the end of the webpage while AdGuard Base does not block them.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<br />
With EasyList
<img width="960" alt="WithEasyList" src="https://user-images.githubusercontent.com/32593810/152569240-97840333-e916-407d-9bf6-9d98c47c2021.PNG"><br />
<br />
Without EasyList
<img width="960" alt="WithoutEasyList" src="https://user-images.githubusercontent.com/32593810/152569555-8134b4cf-4d9a-41e9-818d-3d18c4cc376d.PNG">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 56591
  cosmetic: 45757
  scriptlet: 27458
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-unbreak: null
    urlhaus-1: null
  added: 
    https://downloads.vivaldi.com/lists/vivaldi/partners-current.txt: 8-0, 1d.13h.31m
    adguard-generic: 61624-1028, 2m
  default: 
    easylist: 62829-24456, 2m
    ublock-abuse: 77-0, 1d.13h.33m
    ublock-badware: 3831-228, 1d.13h.34m
    ublock-filters: 30186-3177, 1d.13h.29m
    ublock-privacy: 194-3, 1d.13h.28m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 54 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  collapseBlocked: false
  colorBlindFriendly: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 188 ms (selfie)
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
add back the important default lists (especially easyprivacy, ublock-unbreak) and test again

**Comment by okiehsch** [comment]
Looks like an Adguard issue to me.
`mgronline.com#@#.hotelscombine`
works on my end.

**Comment by uBlock-user** [comment]
Do not disable default lists when you report on this issue tracker.
