### ISSUE TITLE
The extension not working on the website - www.the-ken.com

### ISSUE THREAD

**Issue by paywallremove** [uBlockOrigin/uAssets#11585]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

'https://the-ken.com/story/why-cars24-is-the-only-used-car-on-the-unicorn-track/?searchTerm=cars24'
'https://themorningcontext.com/internet/what-should-urban-company-do'

### Describe the issue

Paywall is not getting removed on the following 2 websites

1- the-ken.com
2- https://themorningcontext.com/

### Screenshot(s)

<img width="1186" alt="Screenshot 2022-02-04 at 6 43 01 PM" src="https://user-images.githubusercontent.com/99026072/152535051-18505493-42ab-4c57-b9a1-faa4a934478a.png">
<img width="1216" alt="Screenshot 2022-02-04 at 6 43 14 PM" src="https://user-images.githubusercontent.com/99026072/152535073-d9cb2826-379c-446e-8fa1-0f36db3e7732.png">

### uBlock Origin version

Version 1.40.8 Updated January 12, 2022

### Browser name and version

Google Chrome, Version 97.0.4692.99 (Official Build) (arm64)

### Settings

- Tried clearing all cookies and cache
- Opened the URL in incognito mode

### Notes

- Tried clearing all cookies and cache
- Opened the URL in incognito mode

**Comment by uBlock-user** [comment]
We don't fix paywalls. Ask somewhere else.

**Comment by paywallremove** [comment]
Good evening, got it. Where can I ask? I'm new here.

**Comment by uBlock-user** [comment]
Use reddit - `https://www.reddit.com/r/uBlockOrigin/`

**Comment by iam-py-test** [comment]
> Good evening, got it. Where can I ask? I'm new here.

Please read the issue requirements **before** submitting it. The issue template clearly states that support questions should be asked on Reddit

**Comment by paywallremove** [comment]
Understood, thanks for replying.
