### ISSUE TITLE
myaccount.depositprotection.com: breakage

### ISSUE THREAD

**Issue by petemounce** [uBlockOrigin/uAssets#11584]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myaccount.depositprotection.com/`

### Category

breakage

### Describe the issue

The site uses jsnlog.js to do logging. This is blocked by uBlock Origin on this site (I've verified via UB's log window).

This causes the stacktrace:

```
myaccount.depositprotection.com/:47 GET https://myaccount.depositprotection.com/Scripts/lib/jsnlog/jsnlog.min.js net::ERR_BLOCKED_BY_CLIENT
logging.js:9 Uncaught ReferenceError: JL is not defined
    at Object.log (logging.js:9:1)
    at Object.start (app.js:88:1)
    at main.js:160:1
    at main (config-wrap-start-default.js:307:1)
    at callDep (config-wrap-start-default.js:167:1)
    at main (config-wrap-start-default.js:298:1)
    at config-wrap-start-default.js:376:1
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78176
  cosmetic: 40861
  scriptlet: 16488
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62819-9, 14h.26m
    easyprivacy: 26694-18, 14h.25m
    plowe-0: 3679-817, 6d.9h.6m
    ublock-abuse: 77-0, 14h.24m
    ublock-badware: 3831-72, 14h.23m
    ublock-filters: 30181-148, 14h.22m
    ublock-privacy: 194-2, 14h.21m
    ublock-unbreak: 1696-39, 14h.19m
    urlhaus-1: 7611-0, 10h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2925 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by petemounce** [comment]
(I'm able to work around the breakage by disabling UB temporarily)

**Comment by uBlock-user** [comment]
@petemounce Use `@@||myaccount.depositprotection.com/Scripts/lib/jsnlog/jsnlog.min.js^$script,1p`
