### ISSUE TITLE
twitter.com: nuisance

### ISSUE THREAD

**Issue by RudderDuck** [uBlockOrigin/uAssets#11594]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/IkNet`

### Category

nuisance

### Describe the issue

Twitter shows black login popup window and disables scrolling (time/scroll dependent?). I can remove the popup window but the scroll lock remains taking effect after a while.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78053
  cosmetic: 40849
  scriptlet: 16444
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30750-27, 2d.19m
    ublock-badware: 3835-1, 2d.18m
    ublock-privacy: 193-0, 2d.17m
    ublock-abuse: 77-0, 2d.16m
    ublock-unbreak: 1706-0, 2d.15m
    easylist: 62753-594, 2d.14m
    easyprivacy: 26693-480, 2d.13m
    urlhaus-1: 7530-0, 23h.4m
    plowe-0: 3679-2, 8d.10h.28m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 324 ms (selfie)
popupPanel: 
  blocked: 27
```
</details>

**Comment by uBlock-user** [comment]
```
twitter.com##.r-g6jmlv.r-ipm5af.r-1xcajam.r-xr3zp9.r-1pjcn9w.r-1777fci.r-1pi2tsx.r-18u37iz.r-1kihuf0.r-1awozwy.css-1dbjc4n,.r-ipm5af.r-zchlnj.r-1xcajam.r-1d2f490.r-1p0dtai.r-11z020y.css-1dbjc4n,.r-qo02w8.r-l5o3uw.css-1dbjc4n
twitter.com##html:style(overflow:auto !important)
```

works ?

**Comment by RudderDuck** [comment]
Yes, superb! I'm assuming I could have found that code myself and added it to the issue?

**Comment by gorhill** [comment]
Some undesirable side effects: https://twitter.com/consoleSkunk/status/1490384799915130880

**Comment by uBlock-user** [comment]
@gorhill Any way to fix it or shall I remove the filter ?

**Comment by gorhill** [comment]
Sorry I don't have an opinion, I didn't look into the whole issue, I just put the link here for a heads up.

I will try to see what the original issue is.

**Comment by resulin** [comment]
@uBlock-user 

I've been running this filter (source https://teddit.net/r/uBlockOrigin/comments/sew1rn/comment/hv99m7j )

```
twitter.com##div#layers div[data-testid="sheetDialog"]:upward(div[role="group"][tabindex="0"])
twitter.com##html:style(overflow: auto !important;)
```

and didn't notice any breakage after 2 days of intensive usage (the only problem with the filter is that the nuisance appears for ~1 sec and then gets removed).

**Comment by resulin** [comment]
> @resulin Did you test with a twitter account ?

Only tested without a twitter account (I don't have one so I can't test).

**Comment by resulin** [comment]
@uBlock-user said:
> @resulin Did you test with a twitter account ?

Others tested and it does lead to some breakage: https://github.com/easylist/easylist/issues/10739#issuecomment-1041406015

In the meantime can you re-open this issue since the underlying problem is still not solved.
