### ISSUE TITLE
mgronline.com: breakage

### ISSUE THREAD

**Issue by Norarit-Sae** [uBlockOrigin/uAssets#11592]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mgronline.com/japan/detail/9640000119771`

### Category

breakage

### Describe the issue

I have reset to default settings. Some content is still missing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock
![image](https://user-images.githubusercontent.com/32593810/152577741-460e784b-e7d3-4184-a2b5-59831bbf7ef3.png)

Without uBlock
![image](https://user-images.githubusercontent.com/32593810/152579338-57ec9651-8ed1-4c5d-9dc9-dcd9a0f5c983.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 78202
  cosmetic: 40885
  scriptlet: 16489
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62850-9, now
    easyprivacy: 26696-18, now
    plowe-0: 3677-817, now
    ublock-abuse: 77-0, now
    ublock-badware: 3841-72, now
    ublock-filters: 30188-148, now
    ublock-privacy: 194-2, now
    ublock-unbreak: 1699-39, now
    urlhaus-1: 7611-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 910 ms
popupPanel: 
  blocked: 11
```
</details>

**Comment by mapx-** [comment]
add & test

```
@@||ads.imprezzer.com/js/imprezzer2.min.js$script,domain=mgronline.com
@@||ads.imprezzer.com/js/multisize_responsive.js$script,domain=mgronline.com
@@||ads.imprezzer.com/js/multisize_bottompage_responsive.js$script,domain=mgronline.com
@@||ads.imprezzer.com/js/imprezzer_vip2.js$script,domain=mgronline.com
```

@ryanbr

**Comment by Norarit-Sae** [comment]
Thank you very much. It works.

**Comment by ryanbr** [comment]
Needs to be more specific, not seeing issues and also allows a sidebar ad when adding this.

**Comment by mapx-** [comment]
@ryanbr The ad you see on the right side is already present even without the exceptions
![image](https://user-images.githubusercontent.com/10303732/152633075-dfdb1cda-4b4b-4a05-ab1c-b9cf95ae6145.png)

Adding the exceptions unbreaks the page

all this part is missing
![image](https://user-images.githubusercontent.com/10303732/152633121-d698b6cf-0346-4450-b05d-d2e904b35e35.png)

for the ad just add too
`mgronline.com##[href^="https://www.hotelscombined.co.th/"]`
