### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by clintold** [uBlockOrigin/uAssets#11596]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/blastpremier`

### Category

ads

### Describe the issue

Ads that interrupt the streams arent being blocked. these have been previously blocked by uBLock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 77760
  cosmetic: 40832
  scriptlet: 16450
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30757-27, 20h.3m
    ublock-badware: 3835-1, 19h.22m
    ublock-privacy: 193-0, 19h.21m
    ublock-abuse: 77-0, 19h.20m
    ublock-unbreak: 1703-0, 3d.22h.33m
    easylist: 62539-590, 3d.22h.32m
    easyprivacy: 26686-480, 3d.22h.31m
    urlhaus-1: 7445-0, 4h.29m
    plowe-0: 3676-2, 11d.21h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 216 ms (selfie)
popupPanel: 
  blocked: 376
```
</details>

**Comment by BottledSoda** [comment]
Try **[AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra)**.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22twitch.tv%22+in%3Atitle
