### ISSUE TITLE
aeriagames.com: breakage

### ISSUE THREAD

**Issue by outfrost** [uBlockOrigin/uAssets#11593]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.aeriagames.com/`

### Category

breakage

### Describe the issue

While uBO is active for the site, clicking "Settings" in the GDPR consent modal does nothing and leaves the modal open. With uBO inactive, clicking "Settings" opens a different, detailed consent modal properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/18421230/152590928-a6909e85-213a-4e6d-82a3-a6fac434e3d5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78025
  cosmetic: 40869
  scriptlet: 16454
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30752-27, 6h.35m
    ublock-badware: 3835-1, 6h.34m
    ublock-privacy: 193-0, 6h.33m
    ublock-abuse: 77-0, 6h.32m
    ublock-unbreak: 1707-0, 6h.31m
    easylist: 62829-596, 6h.30m
    easyprivacy: 26696-480, 6h.29m
    urlhaus-1: 7445-0, 6h.28m
    plowe-0: 3680-2, 4d.3h.14m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 209 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
Does this work for you ?

`@@||googletagmanager.com/gtm.js$script,domain=aeriagames.com`

@ryanbr

**Comment by okiehsch** [comment]
Disabling the redirection works on my end, no need to allow the request.

**Comment by Procyon-b** [comment]
Like @okiehsch wrote:
```
@@||googletagmanager.com/gtm.js$domain=aeriagames.com,script,redirect-rule=googletagmanager.com/gtm.js
```

**Comment by outfrost** [comment]
Can confirm it works. Thanks!
