### ISSUE TITLE
pornhd.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1159]
URL(s) where the issue occurs

    https://www.pornhd.com/videos/40100/layna-catches-cadence-sucking-cock-hd-porn-video

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by gorhill** [comment]
Please do no use live links, prefix with four spaces to ensure the link is rendered as text only. Could be why some issues were removed from the tracker. I edited your comment.

**Comment by spodermenpls** [comment]
@okiehsch The site opens a popup to the site `https://jsmentry.com/pu/?psid=ed_prnhd&target=rttr&utm_medium=partner&utm_source=pornhd&category=girl` once you click on the "Enter" button on the pre-start page. Would you be so kind to add a new filter for that thing?

**Comment by KiLL4FuNK** [comment]
ADS
