### ISSUE TITLE
A filter may be replacing images and converting them to vertical lines

### ISSUE THREAD

**Issue by GitHub-mnm** [uBlockOrigin/uAssets#11609]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`linkedin.com`

`https://www.carousell.com.hk/p/can-t-upload-photos-1137558288/?t-id=nLKrHHH18p_1644053299557&t-referrer_request_id=oHwEuzMn_cjRuSdY&t-tap_index=0`

### Describe the issue

This is a recent issue. It used to work well before. It seems that a filter may be replacing images and converting them into vertical lines on some websites.

 This problem has occured when editing photos in Linkedin - the correct images flashes on the screen and then the image suddenly is replaced with vertical lines.

On Carousell, the images are replaced by vertical lines.

### Screenshot(s)

![vertical lines](https://user-images.githubusercontent.com/55236952/152636769-58ef954c-9d5a-4895-8147-18e5bbabeeb7.png)

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.3

### Settings

- Hide placeholders of blocked elements
- Show the number of blocked requests on the icon
- Make use of context menu where appropriate
- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 
- Block CSP reports 
- Uncloak canonical names

### Notes

I've tried:
- other browsers including MacOS - Safari. Same problem.
- editing the image. exporting the photo from JPG to PNG (in case it was the image). Same problem
- viewing the images on other devices incl. Android. same problem.
- searching online to see if there are any other reported issues similar.

**Comment by uBlock-user** [comment]
> On Carousell, the images are replaced by vertical lines.

Happens without uBO too. Site issue.

**Comment by uBlock-user** [comment]
There's no "replace" functionality in uBO to do any replacing of images.

**Comment by gwarser** [comment]
This looks like fingerprinting protection by `privacy.resistFingerprinting`.

**Comment by uBlock-user** [comment]
@gwarser Happens in Chrome too, so I don't think so.

**Comment by Procyon-b** [comment]
They are images from the site itself.
```
https://media.karousell.com/media/photos/products/2022/1/17/ladies_blouse_embroidery_img_0_1642421482_9e83ca38
https://media.karousell.com/media/photos/products/2022/1/17/ladies_blouse_embroidery_img_0_1642421696_58f1b476_progressive
https://media.karousell.com/media/photos/products/2022/1/17/ladies_blouse_embroidery_img_0_1642426804_3da8a9dc_progressive
```

**Comment by mapx-** [comment]
yes, it's only a page illustrating the issue for so me user ("cant upload ...")

Any other page is working fine
`https://www.carousell.com.hk/p/six-6-seater-rattan-outdoor-table-set-incl-cover-1141575398/?t-id=DCl_Azl0rs_1644055371050&t-referrer_browse_type=categories&t-referrer_category_id=5407&t-referrer_request_id=GdT7W5oxBeoj-STZ&t-referrer_sort_by=popular&t-tap_index=1`

Linkedin => I tried uploading and editing a photo, no issue

**Comment by Procyon-b** [comment]
OK, I though he had issues with the carousell site too.
