### ISSUE TITLE
fmovies.to: popups

### ISSUE THREAD

**Issue by Punallion** [uBlockOrigin/uAssets#11602]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/movie/taken-3-1rqx/1-full`

### Category

popups

### Describe the issue

When clicking play (mycloud server) mallicious popups open
```

https://juicy-protector.com/natifico_pm_nl.php?deep_id=sdvksodpv&click_id=2tm4g71c90iq&_subid=2tm4g71c90iq&_token=uuid_2tm4g71c90iq_2tm4g71c90iq61fdd643895068.82111932

http://xu2.com/script/s2iurl.php?stamat=m%7C%2C%2CgiP643O6oGU3Bf9GH0dEdHP3xP.c46%2CZ-Fni8xfrbbdppFbglft_Fbi-K47cMUlhUCauZJhJpCJilU6sM3ctkEevi45y_1r3rSWKs6eNoVPtbqKTx_edSrGnsxFi5tLk8Os_mXcsy6R4hPUF1u0xEGEihncNTatQNV4o_crFXjhAaRXyoQQarOMHpQFP3Qx-dT7yW6rJztuS3_3Ti7JoEMhc8Fa5QHaMG-xUzzxwM5_LxxZyC9M17GvX5EP9QRXxNy1bpBmscfbcNzb_QgVDGvxOExqOLMK0xSm49F4mhhjkdfEqu5YGHk_eD2eFADQmNb2cmk2KtSPunD-sknDfXjjSlZdse8YqmDUE7nxucg_N9jmVVc2WaQIyPZwAkxHCrWgYieDnHVBXTi4KAomEP9z1aZxE9YSiD53Vm6WYWpX1-0mItTQaiAdFfU5PO1b3DcIo7BWXDpuIfbRdDy3gDt7tMJkNO73&csid=4122955&s1=380314_118533&md=0

http://sterilecute.com/t6k419ij?key=0f22c1fd609f13cb7947c8cabfe1a90d&submetric=16713626

https://www.onlinecasinoground.nl/

https://mbest.aliexpress.com/?UTABTest=aliabtest225490_291075&tt=CPS_NORMAL&aff_platform=portals-tool&OLP=1081300308_f_group1&o_s_id=1081300308
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 98
filterset (summary): 
  network: 229398
  cosmetic: 217256
  scriptlet: 36162
  html: 714
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61615-6292, 2m
    adguard-spyware: 25887-1063, 2m
    adguard-spyware-url: 479-3, 2m
    block-lan: 44-0, 2m
    curben-phishing: 9409-3, 2m
    curben-pup: 411-0, 2m
    adguard-annoyance: 49922-4681, 2m
    adguard-social: 15775-1625, 2m
    fanboy-annoyance: 60486-49400, 2m
    fanboy-cookiemonster: 22088-13302, 2m
    fanboy-social: 23152-13500, 2m
    ublock-annoyances: 4405-11, 2m
    dpollock-0: 10346-515, 2m
    mvps-0: 8730-1504, 2m
    ara-0: 2333-244, 2m
    BGR-0: 1116-19, 2m
    CHN-0: 27845-1169, 2m
    CZE-0: 779-40, 2m
    DEU-0: 5332-375, 2m
    EST-0: 445-10, 2m
    [26 lists not shown]: [too many]
  default: 
    ublock-filters: 30851-629, 3h.23m
    ublock-badware: 3845-1, 3h.22m
    ublock-privacy: 193-1, 3h.21m
    ublock-abuse: 77-0, 3h.20m
    ublock-unbreak: 1713-0, 3h.18m
    adguard-mobile: 7166-256, 3h.28m
    easylist: 62904-24895, 3h.17m
    easyprivacy: 26697-11048, 3h.16m
    urlhaus-1: 7445-4, 3h.15m
    plowe-0: 3677-2, 3h.14m
    NLD-0: 1238-44, 3h.28m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1419 ms (selfie)
popupPanel: 
  blocked: 19
```
</details>

**Comment by uBlock-user** [comment]
You're not on default lists/settings. Revert back to default list/settings and try again.

**Comment by Punallion** [comment]
> You're not on default lists/settings. Revert back to default list/settings and try again.

Thanks for the reply, but I tried that, same results, 2 different firefox versions on 2 different devices, the popups are not always activated, try reloading the page, I don't know how to get rid of it, that is why I tried activating more filters.

Maybe its injected into the player I don't know.

Everywhere else I'm very much adfree.

**Comment by uBlock-user** [comment]
>try reloading the page,

Still can't repro. Existing filters for popups work.

Disable any other extensions you have enabled too.

**Comment by mapx-** [comment]
You have to try on mobile, I can reproduce it.

**Comment by uBlock-user** [comment]
Tried on mobile too, no popups still.

**Comment by uBlock-user** [comment]
Tried on Responsive design mode, no change.

**Comment by mapx-** [comment]
@Punallion test this filter

`mcloud.to##[target="_blank"][style]:upward([style])`

**Comment by Punallion** [comment]
I disabled all other extensions (bitwarden and darkreader) still the same, even after restarting firefox and yes this on phone and tablet.

**Comment by Punallion** [comment]
> @Punallion test this filter
> 
> `mcloud.to##[target="_blank"][style]:upward([style])`

I'll try thnx.
