### ISSUE TITLE
mailshub.in: ads

### ISSUE THREAD

**Issue by 0x6900** [uBlockOrigin/uAssets#11608]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://mailshub.in/wiz/index.php/lists/dx872sdnyq0a0/confirm-unsubscribe/er616owmoz30e/so546963v7f5f`

### Category

ads

### Describe the issue

Ads leftovers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78013
  cosmetic: 40942
  scriptlet: 16480
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62829-10, 20h.45m
    easyprivacy: 26696-18, 20h.44m
    plowe-0: 3679-817, 9d.15h.8m
    ublock-abuse: 77-0, 20h.43m
    ublock-badware: 3831-72, 20h.42m
    ublock-filters: 30170-148, 20h.41m
    ublock-privacy: 194-2, 20h.40m
    ublock-unbreak: 1699-39, 20h.39m
    urlhaus-1: 7445-0, 16h.38m
filterset (user): [array of 73 redacted]
trustedset: 
  added: [array of 24 redacted]
hostRuleset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 852 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by mapx-** [comment]
add

`mailshub.in##[href^="https://www.amazon.in/"]`

@ryanbr
