### ISSUE TITLE
exey.app: detection

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#11605]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://exey.app/RccJm`

### Category

detection

### Describe the issue

"Desactive Adblock para continuar con la página de destino. "

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 157400
  cosmetic: 195417
  scriptlet: 52137
  html: 623
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 27118-23, 4h.19m
    adguard-generic: 61615-5526, 4h.19m
    adguard-mobile: 7166-217, 4h.19m
    adguard-spyware: 25887-989, 4h.19m
    adguard-annoyance: 49922-4290, 4h.19m
    adguard-social: 15775-1073, 4h.19m
    fanboy-thirdparty_social: 69-0, 4h.19m
    fanboy-annoyance: 60486-45431, 4h.19m
    fanboy-cookiemonster: 22088-129, 4h.19m
    fanboy-social: 23152-30, 4h.19m
    ublock-annoyances: 4385-42, 4h.19m
    dpollock-0: 10346-494, 4h.19m
    mvps-0: 8730-1496, 4h.19m
    TUR-0: 8788-144, 4h.19m
    adguard-spyware-url: 479-3, 4h.19m
    block-lan: 44-0, 4h.19m
    curben-phishing: 9285-3, 4h.19m
    curben-pup: 408-0, 4h.19m
  default: 
    ublock-filters: 30763-3317, 4h.19m
    ublock-badware: 3845-1, 4h.19m
    ublock-privacy: 193-0, 4h.19m
    ublock-abuse: 77-0, 4h.19m
    ublock-unbreak: 1711-0, 4h.19m
    easylist: 62904-1098, 4h.19m
    easyprivacy: 26697-10999, 4h.19m
    urlhaus-1: 7611-0, 4h.19m
    plowe-0: 3679-2, 4h.19m
    spa-0: 3744-3, 4h.19m
    spa-1: 4209-107, 4h.19m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 272 ms (selfie)
popupPanel: 
  blocked: 16
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
exey.app##+js(acis, disableItToContinue)
```

**Comment by BottledSoda** [comment]
for anti-out-of-focus:
`exey.app##+js(set, blurred, false)`

**Comment by PerfectSalad** [comment]
anti-adb

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=exey.io
```
