### ISSUE TITLE
sexu.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1161]
URL(s) where the issue occurs

`http://sexu.com/2540300/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by in4u** [comment]
There's a popup on clicking/playing videos.

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO

ADS
