### ISSUE TITLE
orteil.dashnet.org: ads

### ISSUE THREAD

**Issue by androidkotlindev** [uBlockOrigin/uAssets#11616]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://orteil.dashnet.org/cookieclicker/`

### Category

ads

### Describe the issue

Above the store title, there is a "Sponsored link" text.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 94
filterset (summary): 
  network: 78229
  cosmetic: 40890
  scriptlet: 16490
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62910-9, 2h.57m
    easyprivacy: 26703-18, 2h.56m
    plowe-0: 3679-817, 2h.55m
    ublock-abuse: 77-0, 2h.53m
    ublock-badware: 3841-72, 2h.50m
    ublock-filters: 30189-149, 2h.25m
    ublock-privacy: 194-2, 2h.24m
    ublock-unbreak: 1700-39, 2h.23m
    urlhaus-1: 7574-0, 2h.22m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 894 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
orteil.dashnet.org###smallSupport
```
Open ublock dashboard, go to the "_My filters_" tab, and in a new line, paste the filter above. Then click "_Apply changes_". Reload the webpage.

**Comment by mapx-** [comment]
@ryanbr
