### ISSUE TITLE
forum.thresholdx.net: detection

### ISSUE THREAD

**Issue by bceez** [uBlockOrigin/uAssets#11615]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forum.thresholdx.net/files/file/1298-boeing-737ng-series/`

### Category

detection

### Describe the issue

Anti-adblock script

### Screenshot(s)

![Screenshot_20220205-184153_Firefox](https://user-images.githubusercontent.com/99037750/152652825-314813b8-443b-491c-b916-df64bd2a6ee0.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 97
filterset (summary): 
  network: 79904
  cosmetic: 23877
  scriptlet: 19258
  html: 625
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4411-7, now
  default: 
    ublock-filters: 30856-265, now
    ublock-badware: 3845-1, now
    ublock-privacy: 193-1, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1722-0, now
    adguard-mobile: 7169-173, now
    easylist: 62910-24364, now
    easyprivacy: 26703-488, now
    urlhaus-1: 7555-0, now
    plowe-0: 3679-2, now
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5305 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by BottledSoda** [comment]
`/javascript_adblockdetector`

**Comment by TheSystemGuy1337** [comment]
This issue is still present and this one appears to have been unresolved since 2022. I've attempted to add `javascript_adblockdetector` to my filterlists which did not resolve the issue.
