### ISSUE TITLE
t-online.de: breakage

### ISSUE THREAD

**Issue by Jo1972** [uBlockOrigin/uAssets#11610]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.t-online.de/`

### Category

breakage

### Describe the issue

The most images, of the second half of the page, adressed "https://bilder.t-online.de/..." will be blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 133051
  cosmetic: 188321
  scriptlet: 33071
  html: 624
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 3d.25m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 19m
    adguard-generic: 61529-4829, 2d.16h.33m
    adguard-mobile: 7163-31, 2d.16h.32m
    adguard-spyware: 25869-679, 2d.16h.31m
    adguard-annoyance: 49847-4277, 2d.16h.30m
    adguard-social: 15753-43, 2d.14h.47m
    fanboy-thirdparty_social: 69-0, 1d.19h.38m
    fanboy-annoyance: 60486-45440, 12h.16m
    fanboy-cookiemonster: 22088-132, 12h.15m
    fanboy-social: 23152-1091, 2d.14h.45m
    ublock-annoyances: 4384-9, 2d.14h.46m
    adguard-spyware-url: 459-3, 2d.14h.48m
  default: 
    ublock-filters: 30747-65, 2d.16h.28m
    ublock-badware: 3835-5, 2d.14h.49m
    ublock-privacy: 193-0, 1d.13m
    ublock-abuse: 77-0, 2d.22h.25m
    ublock-unbreak: 1705-1, 2d.22h.23m
    easylist: 62719-790, 2d.22h.22m
    easyprivacy: 26693-10851, 2d.16h.34m
    urlhaus-1: 7555-0, 17m
    plowe-0: 3680-143, 3d.26m
    DEU-0: 5332-18, 18m
filterset (user): [array of 88 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 17 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2474 ms (selfie)
popupPanel: 
  blocked: 19
```
</details>

**Comment by Jo1972** [comment]
If uBO is disabled, the imgaes are all exists.

**Comment by okiehsch** [comment]
Does not happen with a default setup.
You have a highly customized setup. Open the logger and type `bilder.t-online` in the box like you see in my screenshot.
![image](https://user-images.githubusercontent.com/16838044/152639808-3a8f6b0c-f5c2-4bab-aa65-d9f6c4454612.png)


What do you see on your end?

**Comment by Jo1972** [comment]
Does this help?

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | ##img[width="920"][usemap^="#immap"] |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##div[id^="T-"][oncontextmenu="return false"] |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##div[class^="Tsshopst"] |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | `##a[href^="https://count.shopping.t-online.de/RE?ID="]` |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##.Tgbox--anz |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ###vmsky |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ###Tgb-88799072 |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ###Tcontboxi > .Tgbox--anz |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ###Tcontboxi + #Tgboxf |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##+js(set-constant, CustomEvent, noopFunc) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##+js(set-constant, abp, false) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +1 | ##+js(set-constant, CustomEvent, noopFunc) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/widgets/finance/search/` |
| +1 | ##+js(set-constant, abp, false) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/widgets/finance/search/` |
| +1 | @@\|\|t-online.de^$generichide | ++ | `www.t-online.de` | 1 | generichide | `https://www.t-online.de/` |
| +1 | @@\|\|t-online.de^$generichide | ++ | `www.t-online.de` | 1 | generichide | `https://www.t-online.de/widgets/finance/search/` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/kFzWAjlZn3F_oLjDpfFZ5/_ssgManifest.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/kFzWAjlZn3F_oLjDpfFZ5/_ssgManifest.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/kFzWAjlZn3F_oLjDpfFZ5/_buildManifest.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/kFzWAjlZn3F_oLjDpfFZ5/_buildManifest.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/pages/widgets/finance/search-9defc47a15daed7c27dd.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/pages/widgets/finance/search-9defc47a15daed7c27dd.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/1033-088fca972f2704083fa6.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/1033-088fca972f2704083fa6.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/pages/_app-a0dc314526d2f4e6e5fd.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/pages/_app-a0dc314526d2f4e6e5fd.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/main-029ffa17cf32cdd78ddf.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/main-029ffa17cf32cdd78ddf.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/framework-121b96742ffa9aba18d9.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/framework-121b96742ffa9aba18d9.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/webpack-dcd61dcaa3ebbc1f7159.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/chunks/webpack-dcd61dcaa3ebbc1f7159.js` |
| +1 |  |  | `www.t-online.de` | 3 | css | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/css/63c0e243abba63c68ac5.css` |
| +1 |  |  | `www.t-online.de` | 3 | css | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/css/63c0e243abba63c68ac5.css` |
| +1 |  |  | `www.t-online.de` | 3 | css | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/_next/static/css/c08ff26628e093b99c49.css` |
| +1 |  |  | `www.t-online.de` | 3 | css | `https://fin-statics-prod.dcp.stroeerws.de/_next/static/css/c08ff26628e093b99c49.css` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://www.t-online.de/favicon-32x32.png` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://www.t-online.de/apple-touch-icon.png` |
| +1 | google-analytics.com/analytics.js | << | `www.t-online.de` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js | -- | `www.t-online.de` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js,domain=~olx.* | -- | `www.t-online.de` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | `www.t-online.de` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/89/14/23/34/id_89142334/tid_da/co2neutral.png` |
| +1 | ##+js(set-constant, CustomEvent, noopFunc) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/-/id_62530634/tid_tsr_iframe_loginbox/index` |
| +1 | ##+js(set-constant, abp, false) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/-/id_62530634/tid_tsr_iframe_loginbox/index` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/47/57/78/id_91475778/tid_da//index.png` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/59/41/38/id_91594138/tid_da/index.gif` |
| +1 | `www.t-online.de img.toi.de * block` | -- | `www.t-online.de` | 3 | image | `https://img.toi.de/t.gif` |
| +1 | `www.t-online.de img.toi.de * block` | -- | `www.t-online.de` | 3 | image | `https://img.toi.de/ladeblume.gif` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/88/12/45/22/id_88124522/tid_da/index.png` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://www.t-online.de/rl09/static/imgs/t.gif` |
| +1 | @@\|\|googletagmanager.com/gtm.js$domain=t-online.de | ++ | `www.t-online.de` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-P9FVTRJ` |
| +1 |  |  | `www.t-online.de` | 3 | xhr | `https://login.stroeerdp.de/` | `aliasURL=https://login.t-online.de/getUserData.json?ts=6892785450145579` |
| +1 |  |  | `www.t-online.de` | 1 | xhr | `https://login.t-online.de/getUserData.json?ts=6892785450145579` |
| +1 | @@\|\|t-online.de^$generichide | ++ | `www.t-online.de` | 1 | generichide | `https://www.t-online.de/-/id_62530634/tid_tsr_iframe_loginbox/index` |
| +1 | \|\|taboola.com^$3p | -- | `www.t-online.de` | 3 | script | `https://c2.taboola.com/nr/t-online/newsroom.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/fin-rt-db4ba77ad23831f8a6410a82175636ec.min.js` |
| +1 |  |  | `www.t-online.de` | 3 | script | `https://fin-statics-prod.dcp.stroeerws.de/fin-rt-db4ba77ad23831f8a6410a82175636ec.min.js` |
| +1 |  |  | `www.t-online.de` | 1 | frame | `https://www.t-online.de/widgets/finance/search/` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/82/86/45/74/id_82864574/tid_da/index.png` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/82/86/45/74/id_82864678/tid_da/index.png` |
| +1 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/60/92/08/id_91609208/610_80/tid_da/index.jpg` |
| +1 | `www.t-online.de img.toi.de * block` | -- | `www.t-online.de` | 3 | image | `https://img.toi.de/t.gif` |
| +1 |  |  | `www.t-online.de` | 1 | script | `https://stats.t-online.de/rl13-home-async-unkrit-js-20/id_84796970/tid_js/index_ts7184641162.js` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/57/84/60/id_91578460/300_80/tid_da/die-besten-bodenstaubsauger-von-bosch-miele-und-co-im-ueberblick-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/90/36/86/12/id_90368612/300_80/tid_da/trick-die-einkerbungen-am-rand-fallen-nur-bei-naeherem-hinsehen-auf-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/60/64/74/id_91606474/300_80/tid_da/gebratener-rosenkohl-das-gericht-ist-in-wenigen-minuten-zubereitet-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/25/67/26/id_91256726/300_80/tid_da/aelterer-mann-bekommt-blutdruck-gemessen-symbolbild-krankheitszeiten-in-denen-sie-arbeitsunfaehig-waren-koennen-fuer-die-rente-mitzaehlen-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/61/03/34/id_91610334/300_80/tid_da/ex-kanzler-gerhard-schroeder-bei-einem-wirtschaftsforum-archivbild-er-ist-in-die-kritik-wegen-seiner-naehe-zu-russland-gekommen-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/60/88/66/id_91608866/300_80/tid_da/reisende-in-kopenhagen-das-land-hat-alle-corona-massnahmen-aufgehoben-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/60/94/92/id_91609492/300_80/tid_da/olaf-scholz-erst-die-sinkenden-zahlen-dann-die-lockerungsdebatte-findet-der-bundeskanzler-nur-wie-weit-kommt-er-damit-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/60/88/52/id_91608852/300_80/tid_da/deutsche-sportler-bei-der-eroeffnungsfeier-der-olympischen-spiele-in-peking-.jpg` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/61/19/68/id_91611968/300_80/tid_da/katharina-althaus-die-deutsche-skispringerin-zaehlt-zu-den-medaillen-hoffnungen-.jpg` |
| +0 |  |  | `www.t-online.de` | 3 | script | `https://coronabox.engagement-prod.stroeerws.de/legacy-coronadata/startseite/coronadata.js` |
| +0 |  |  | `www.t-online.de` | 3 | image | `https://coronabox.engagement-prod.stroeerws.de/startseite.png` |
| +0 |  |  | `www.t-online.de` | 1 | frame | `https://www.t-online.de/-/id_62530634/tid_tsr_iframe_loginbox/index` |
| +0 | `www.t-online.de img.toi.de * block` | -- | `www.t-online.de` | 3 | image | `https://img.toi.de/t.gif` |
| +0 | \|\|speedcurve.com^$3p | -- | `www.t-online.de` | 3 | script | `https://cdn.speedcurve.com/js/lux.js?id=97918735` |
| +0 | /adex.js | -- | `www.t-online.de` | 1 | script | `https://stats.t-online.de/js/ads/adex.js` |
| +0 |  |  | `www.t-online.de` | 1 | css | `https://www.t-online.de/region/id_86545120/tid_css/regio-schaufenster-sib-css.css` |
| +0 | \|\|stats.t-online.de/include-ivw-agof-szmng-js/ | -- | `www.t-online.de` | 1 | script | `https://stats.t-online.de/include-ivw-agof-szmng-js/id_85433946/tid_js/index_ts585433946.js` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://stats.t-online.de/rl13-home-async-unkrit-js/id_84796970/tid_js/index_ts1370050.js` |
| +0 | @@\|\|googletagmanager.com/gtm.js$domain=t-online.de | ++ | `www.t-online.de` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-P9FVTRJ` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://pur.t-online.de/now.js` |
| +0 | ##+js(set-constant, CustomEvent, noopFunc) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +0 | ##+js(set-constant, abp, false) |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +0 | \|\|privacy-mgmt.com^$3p,domain=~11freunde.de\|~ad.nl\|~autobild.de\|~bike-bild.de\|~bild.de\|~boerse-online.de\|~bold.dk\|~businessinsider.de\|~bz-berlin.de\|~caramia.de\|~clever-tanken.de\|~computerbild.de\|~derstandard.at\|~dilbert.com\|~edelblech.de\|~ekstrabladet.dk\|~faz.net\|~finanzen.at\|~finanzen.ch\|~finanzen.net\|~fitbook.de\|~gentside.com\|~gentside.de\|~giga.de\|~gofeminin.de\|~heise.de\|~idealo.at\|~idealo.co.uk\|~idealo.de\|~idealo.es\|~idealo.fr\|~idealo.it\|~immonet.de\|~insider.com\|~kombi.de\|~manager-magazin.de\|~maxisciences.com\|~meinestadt.de\|~metal-hammer.de\|~musikexpress.de\|~myhomebook.de\|~n24.de\|~noizz.de\|~ohmymag.com\|~onmeda.de\|~politico.eu\|~rollingstone.de\|~spiegel.de\|~sport1.de\|~sportbild.de\|~stylebook.de\|~techbook.de\|~telegraph.co.uk\|~testbild.de\|~transfermarkt.at\|~transfermarkt.ch\|~transfermarkt.co.uk\|~transfermarkt.com\|~transfermarkt.com.tr\|~transfermarkt.de\|~transfermarkt.fr\|~transfermarkt.it\|~transfermarkt.nl\|~transfermarkt.pl\|~transfermarkt.pt\|~transfermarkt.us\|~travelbook.de\|~tvspielfilm.de\|~utopia.de\|~vip.de\|~vtm.begmt.com\|~welt.de\|~wieistmeineip.at\|~wieistmeineip.ch\|~wieistmeineip.de\|~zuio.tv | -- | `www.t-online.de` | 3 | script | `https://cdn-375.privacy-mgmt.com/` | `aliasURL=https://consent.t-online.de/wrapperMessagingWithoutDetection.js` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://consent.t-online.de/wrapperMessagingWithoutDetection.js` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/widgets-master.0d971b4485672ba375944dbeb9560d19.css` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://fin-statics-prod.dcp.stroeerws.de/widgets-master.0d971b4485672ba375944dbeb9560d19.css` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/embeds/t-fin-stream.eeab523ff66e1f2f4f3e.css` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://fin-statics-prod.dcp.stroeerws.de/embeds/t-fin-stream.eeab523ff66e1f2f4f3e.css` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://d1gantrzgfqtto.cloudfront.net/` | `aliasURL=https://fin-statics-prod.dcp.stroeerws.de/embeds/932.91c85023773d5b2281e4.css` |
| +0 |  |  | `www.t-online.de` | 3 | css | `https://fin-statics-prod.dcp.stroeerws.de/embeds/932.91c85023773d5b2281e4.css` |
| +0 |  |  | `www.t-online.de` | 1 | css | `https://www.t-online.de/-/id_86545120/tid_css/index` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/61/22/46/id_91612246/300_80/tid_da/denise-herrmann-am-boden-die-deutsche-biathletin-hatte-mit-den-bedingungen-zu-kaempfen-.jpg` |
| +0 | `www.t-online.de img.toi.de * block` | -- | `www.t-online.de` | 3 | image | `https://img.toi.de/t.gif` |
| +0 | \|\|speedcurve.com^$3p | -- | `www.t-online.de` | 3 | script | `https://cdn.speedcurve.com/js/lux.js?id=97918735` |
| +0 | /adex.js | -- | `www.t-online.de` | 1 | script | `https://stats.t-online.de/js/ads/adex.js` |
| +0 | \|\|stats.t-online.de/include-ivw-agof-szmng-js/ | -- | `www.t-online.de` | 1 | script | `https://stats.t-online.de/include-ivw-agof-szmng-js/id_85433946/tid_js/index_ts585433946.js` |
| +0 | \|\|privacy-mgmt.com^$3p,domain=~11freunde.de\|~ad.nl\|~autobild.de\|~bike-bild.de\|~bild.de\|~boerse-online.de\|~bold.dk\|~businessinsider.de\|~bz-berlin.de\|~caramia.de\|~clever-tanken.de\|~computerbild.de\|~derstandard.at\|~dilbert.com\|~edelblech.de\|~ekstrabladet.dk\|~faz.net\|~finanzen.at\|~finanzen.ch\|~finanzen.net\|~fitbook.de\|~gentside.com\|~gentside.de\|~giga.de\|~gofeminin.de\|~heise.de\|~idealo.at\|~idealo.co.uk\|~idealo.de\|~idealo.es\|~idealo.fr\|~idealo.it\|~immonet.de\|~insider.com\|~kombi.de\|~manager-magazin.de\|~maxisciences.com\|~meinestadt.de\|~metal-hammer.de\|~musikexpress.de\|~myhomebook.de\|~n24.de\|~noizz.de\|~ohmymag.com\|~onmeda.de\|~politico.eu\|~rollingstone.de\|~spiegel.de\|~sport1.de\|~sportbild.de\|~stylebook.de\|~techbook.de\|~telegraph.co.uk\|~testbild.de\|~transfermarkt.at\|~transfermarkt.ch\|~transfermarkt.co.uk\|~transfermarkt.com\|~transfermarkt.com.tr\|~transfermarkt.de\|~transfermarkt.fr\|~transfermarkt.it\|~transfermarkt.nl\|~transfermarkt.pl\|~transfermarkt.pt\|~transfermarkt.us\|~travelbook.de\|~tvspielfilm.de\|~utopia.de\|~vip.de\|~vtm.begmt.com\|~welt.de\|~wieistmeineip.at\|~wieistmeineip.ch\|~wieistmeineip.de\|~zuio.tv | -- | `www.t-online.de` | 3 | script | `https://cdn-375.privacy-mgmt.com/` | `aliasURL=https://consent.t-online.de/wrapperMessagingWithoutDetection.js` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://consent.t-online.de/wrapperMessagingWithoutDetection.js` |
| +0 | \|\|iocnt.net^$3p | -- | `www.t-online.de` | 3 | script | `https://relay-client-c04.iocnt.net/` | `aliasURL=https://data-501446ac98.t-online.de/iomm/latest/bootstrap/loader.js` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://data-501446ac98.t-online.de/iomm/latest/bootstrap/loader.js` |
| +0 | \|\|iocnt.net^$3p | -- | `www.t-online.de` | 3 | script | `https://relay-client-c04.iocnt.net/` | `aliasURL=https://data-501446ac98.t-online.de/iomm/latest/manager/base/es6/bundle.js` |
| +0 |  |  | `www.t-online.de` | 1 | script | `https://data-501446ac98.t-online.de/iomm/latest/manager/base/es6/bundle.js` |
| +0 |  |  | `www.t-online.de` | 1 | image | `https://bilder.t-online.de/b/91/61/04/62/id_91610462/610_80/tid_da/vor-der-eroeffnungsfeier-treffen-sich-xi-und-putin-zu-einem-gipfel-dabei-haben-die-praesidenten-gemeinsame-vorstellungen-in-der-sicherheitspolitik-formuliert-.jpg` |
| +0 | @@\|\|t-online.de^$generichide | ++ | `www.t-online.de` | 1 | generichide | `https://www.t-online.de/` |
| +0 | ##^script:has-text(toscr') |  | `www.t-online.de` |  | dom | `https://www.t-online.de/` |
| +0 |  |  | `www.t-online.de` | 1 | doc | `https://www.t-online.de/` |
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings and don't touch it then.

**Comment by Jo1972** [comment]
^This is not the solution of tthe problem.

So if I want that, I could unintall uBO and all problems are solved :)

**Comment by okiehsch** [comment]
`www.t-online.de img.toi.de * block` 

You are using dynamic filtering, why have you added that rule?

**Comment by Jo1972** [comment]
Because of security issue.

**Comment by okiehsch** [comment]
> Because of security issue.

Welches Sicherheitsproblem könnte das sein?

**Comment by mapx-** [comment]
remove that dynamic filter and add
`||img.toi.de^$image,domain=t-online.de,redirect=1x1.gif`

**Comment by okiehsch** [comment]
That will work even if he does not remove it.

**Comment by mapx-** [comment]
yes, but is superfluous

**Comment by okiehsch** [comment]
> is superfluous

Like most of his setup. 😉 
It's no security issue at all and I am wondering how he get's that idea.

**Comment by mapx-** [comment]
I guess he is thinking about some tracking pixel.

**Comment by Jo1972** [comment]
So could you please decide?

BTW: It's not serious, to mock users publicly. If you don't want to help, don't.

**Comment by mapx-** [comment]
> 

You should read the comments. Just add the filter above.

**Comment by okiehsch** [comment]
I am not mocking you, I am asking why you blocked it, it's decidedly not a security issue, I even asked you in german in case something is lost in translation.
If you add
`||img.toi.de^$image,domain=t-online.de,redirect=1x1.gif`
to your filter list the the pictures should show up fine on your end.

**Comment by Jo1972** [comment]
Okay, thank you.

But honestly, which "dynamic filter" do you mean?

**Comment by okiehsch** [comment]
You blocked `img.toi.de` using a dynamic filter, it's all explained in the wiki.
 https://github.com/gorhill/uBlock/wiki/Dynamic-filtering

Before you can use dynamic filtering you have to check that you are an "Advanced User"
![image](https://user-images.githubusercontent.com/16838044/152641277-7e924581-3903-4796-a152-2b8179f58f32.png)

As you can see it states "required reading", which you have not done, it's there because if a user does not know what he/she does it can lead to a bad user experience.

I am not saying that to mock you, just as a matter of fact.

**Comment by Jo1972** [comment]
Thank you.

For that I have untick the _"Adv. User" Tab_ right now to avoid another issue like that.

**Comment by uBlock-user** [comment]
> ^This is not the solution of tthe problem.

It is a solution to the problem created by your customized setup. We don't fix issues created by non-default filter lists/dynamic rules.
