### ISSUE TITLE
ohli24.net: ads

### ISSUE THREAD

**Issue by zsdr12** [uBlockOrigin/uAssets#11614]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ohli24.net/`

### Category

ads

### Describe the issue

top of the site(ads)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 80074
  cosmetic: 47082
  scriptlet: 16455
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30769-29, 5h.18m
    ublock-badware: 3835-1, 5h.17m
    ublock-privacy: 193-0, 5h.16m
    ublock-abuse: 77-0, 5h.15m
    ublock-unbreak: 1711-0, 5h.13m
    easylist: 62907-602, 5h.12m
    easyprivacy: 26701-484, 5h.11m
    urlhaus-1: 7555-0, 5h.10m
    plowe-0: 3679-2, 5h.9m
    KOR-1: 8074-3, 6h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 639 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by mapx-** [comment]
add
`ohli24.net##.at-title:has([href*="affiliates"])`

@yous

**Comment by mapx-** [comment]
for other Korean ads report directly here:
https://github.com/yous/YousList/issues
