### ISSUE TITLE
pussyspace.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1162]
URL(s) where the issue occurs

`https://www.pussyspace.com/vid-2136734-beauty-huge-tits-slut-webcam-squirt-session.-my-live-webcam-show-camsgram.com/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS


`https://www.pussyspace.com/vid-2688677-girlfriend-passionately-sucking-and-licking-the-tip-of-a-big-dick/`
