### ISSUE TITLE
supremacy1914.de: ads

### ISSUE THREAD

**Issue by SuperBanane** [uBlockOrigin/uAssets#11620]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.supremacy1914.de/game.php?L=1&bust=1`

### Category

ads

### Describe the issue

Show ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Unbenannt](https://user-images.githubusercontent.com/65513416/152660828-62c5c5bc-ce5c-472f-9fbe-70560d19a6fc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 80680
  cosmetic: 43317
  scriptlet: 16431
  html: 0
listset (total-discarded, last updated): 
  default: 
    DEU-0: 5332-13, never
    easylist: 62254-468, never
    easyprivacy: 26549-483, never
    plowe-0: 3715-3, never
    ublock-abuse: 81-0, never
    ublock-badware: 3629-1, never
    ublock-filters: 30064-145, never
    ublock-privacy: 184-0, never
    ublock-unbreak: 1708-0, never
    urlhaus-1: 8168-0, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 979 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by Procyon-b** [comment]
I see that the filter lists have not been updated. Can you "_Clear all caches_" and "_Update now_", then try the website again.

**Comment by krystian3w** [comment]
Also lie about check list points.
