### ISSUE TITLE
r10.net: ads

### ISSUE THREAD

**Issue by Lucitrash-vCoder** [uBlockOrigin/uAssets#11627]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.r10.net/`

### Category

ads

### Describe the issue

I can still see the ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/71299590/152669412-8fc9025a-fd43-4817-ac1c-3844c7bf93df.png

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 78205
  cosmetic: 40910
  scriptlet: 16477
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62940-9, 16m
    easyprivacy: 26707-18, 15m
    plowe-0: 3679-817, 14m
    ublock-abuse: 77-0, 12m
    ublock-badware: 3841-72, 10m
    ublock-filters: 30171-149, 9m
    ublock-privacy: 194-2, 8m
    ublock-unbreak: 1705-39, 7m
    urlhaus-1: 7536-0, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 605 ms
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
`||cdn.r10.net/*.webp$image`

turkish list @Yuki2718
