### ISSUE TITLE
logikfx.com: ads

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11625]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.logikfx.com/post/bollinger-bands-strategy-explained`

### Category

ads

### Describe the issue

Due to the complicated attributes, I can't find a good ABP-syntax to report to EL besides `upward` in ubo, so I reported here.

- There are ads placeholders and left-over `Advertisements` texts. Proposed filters:
```
logikfx.com##span:has-text(Advertisement)
logikfx.com##span:has-text(Advertisement):upward(section)
```
- Wait about 30s - 1 min, notices of `Widget Didn't Load` appear at the top blank banner and the right side panes (green blocks in screenshot), looks like due to `wix.com` services blocked. Proposed filter:
```
logikfx.com##.wix-blog-print-in-full-width > div:not([class^="wix-blog"]) > div[style]
```
- Also there are blank placeholders between the paragraphs along the article (orange blocks in screenshot). Proposed filter
```
logikfx.com##[data-hook="HtmlComponent"]
```

### Screenshot(s)

<details>
<summary>Warning - Long screenshot</summary>

![1](https://user-images.githubusercontent.com/66517106/152664718-4c879172-8c51-49a0-b7a0-02d41dd647d6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78224
  cosmetic: 40889
  scriptlet: 16437
  html: 614
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30746-27, 39m
    ublock-badware: 3845-1, 39m
    ublock-privacy: 193-0, 39m
    ublock-abuse: 77-0, 39m
    ublock-unbreak: 1716-0, 39m
    easylist: 62910-596, 39m
    easyprivacy: 26703-480, 39m
    urlhaus-1: 7555-0, 39m
    plowe-0: 3679-2, 39m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 606 ms
popupPanel: 
  blocked: 57
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
logikfx.com##[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._3d64y,[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._1Q9if,[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._2JOHk, iframe._2xvJT
```

If you want to see what are the target without hiding them, use this filter instead:
```
logikfx.com##[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._3d64y,[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._1Q9if,[data-mesh-id="Containereitq9inlineContent-gridContainer"] > ._2JOHk, iframe._2xvJT:style(outline: 6px solid red !important;opacity: 0.4;)
```
This will outline all of them with a 6px-wide red line.

**Comment by stephenhawk8054** [comment]
@Yuki2718 I think the placeholders containing the class `.adsbygoogle` in a 3rd-party iframe `usrfiles.com` are still there

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/152668632-1680c2e6-da4f-4c2d-a228-5695d8c6939c.png)

</details>

The 3rd-party frame URL looks like this:
```
https://339c7652-e8ff-4299-834a-6be7fc7355c1.usrfiles.com/html/db9376e69cfa487ea0fa0b912ae51a4f_v1.html
```

I think we can block and hide them?

```
||usrfiles.com/html/*$subdocument,domain=logikfx.com
logikfx.com##[data-hook="HtmlComponent"]:upward([id^="viewer"])
```

**Comment by Yuki2718** [comment]
@stephenhawk8054 I think I already addressed in https://github.com/uBlockOrigin/uAssets/commit/f96be660bbe9b0a2b5e16c680a2f7e4984052290

**Comment by stephenhawk8054** [comment]
@Yuki2718 Oh I see, I confirm it works now 👍
