### ISSUE TITLE
myflixer.id: popups

### ISSUE THREAD

**Issue by harrisxmal** [uBlockOrigin/uAssets#11621]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myflixer.id/home`

### Category

popups

### Describe the issue

popups still occuring

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78108
  cosmetic: 40859
  scriptlet: 16485
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62783-9, 2d.5h.14m
    easyprivacy: 26695-18, 2d.5h.11m
    plowe-0: 3679-817, 26m
    ublock-abuse: 77-0, 2d.5h.12m
    ublock-badware: 3831-70, 2d.5h.16m
    ublock-filters: 30178-148, 2d.5h.17m
    ublock-privacy: 194-2, 2d.5h.15m
    ublock-unbreak: 1696-39, 2d.5h.13m
    urlhaus-1: 7574-0, 25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6481 ms (selfie)
popupPanel: 
  blocked: 12
```
</details>

**Comment by Procyon-b** [comment]
_Clear all cache_ and _update_ the lists.
I can't reproduce and there are 2 filters for this in _ublock-filters_.
