### ISSUE TITLE
whathifi.com: ad placeholders

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#11624]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.whathifi.com/`
`https://forums.whathifi.com/threads/best-smart-speakers-the-best-voice-assistant-speakers.111294/`

### Describe the issue

Ad placeholders because of generichide filter in uBlock filters – Annoyances:
https://github.com/easylist/easylist/issues/10735

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.3

### Settings

-

**Comment by Procyon-b** [comment]
Try this filter:
```
www.whathifi.com##.ad-unit,.sponsored-post
```
