### ISSUE TITLE
krale.shop: breakage

### ISSUE THREAD

**Issue by JesperKuipers** [uBlockOrigin/uAssets#11639]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.krale.shop/nl/bb-s-valken-accelerate-bio-white-fles-2500-st/`

### Category

breakage

### Describe the issue

Add to shopping cart button is disabled when uBO is on, works fine when uBO is off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

when uBO on:
![image](https://user-images.githubusercontent.com/44586411/152794149-ab22f1ea-4497-4880-b131-9dc3c7d9721c.png)

when uBO off: 
![image](https://user-images.githubusercontent.com/44586411/152794321-2c12e545-e396-4ac7-91ce-0412804461fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78734
  cosmetic: 42226
  scriptlet: 16498
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1h.36m
    NLD-0: 2067-12, 1h.38m
  default: 
    easylist: 62827-10, 3d.3h.21m
    easyprivacy: 26696-18, 3d.3h.20m
    plowe-0: 3679-817, 1h.40m
    ublock-abuse: 77-0, 3d.3h.19m
    ublock-badware: 3831-72, 3d.3h.18m
    ublock-filters: 30180-192, 3d.3h.17m
    ublock-privacy: 194-2, 3d.3h.16m
    ublock-unbreak: 1696-53, 3d.3h.15m
    urlhaus-1: 7424-0, 1h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 137 ms (selfie)
popupPanel: 
  blocked: 21
```
</details>

**Comment by JesperKuipers** [comment]
Also this is shown in the logger with default settings
![image](https://user-images.githubusercontent.com/44586411/152794922-b4ed219f-bdf1-4fd0-ad51-546e8ea95d97.png)

**Comment by mapx-** [comment]
add
`@@||krale.shop/static/*_GoogleTagManager/$script,1p`

EP issue @ryanbr

**Comment by mapx-** [comment]
No, I just notified EasyPrivacy maintainer

**Comment by iam-py-test** [comment]
@JesperKuipers you might want to remove `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt` from your filterlists.
All it seems to do is allow a ton of trackers, ads, and all kinds of shady stuff.
