### ISSUE TITLE
meijerphoto.com: breakage

### ISSUE THREAD

**Issue by Miyelsh** [uBlockOrigin/uAssets#11632]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.meijerphoto.com/Ordering/Cart.aspx`

### Category

breakage

### Describe the issue

Clicking "Proceed to Checkout" does nothing until uBlock is disabled for the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/9065860/152693509-93999bc8-9e8d-49a2-bfdd-3e8f91c90a46.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 77995
  cosmetic: 40880
  scriptlet: 16448
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30754-27, 2d.1h.3m
    ublock-badware: 3835-1, 2d.1h.2m
    ublock-privacy: 193-0, 2d.59m
    ublock-abuse: 77-0, 23m
    ublock-unbreak: 1710-0, 2d.1h.1m
    easylist: 62829-595, 2d.1h
    easyprivacy: 26696-480, 2d.1h.5m
    plowe-0: 3679-2, 6d.20h.35m
    urlhaus-1: 7422-0, 21m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 38 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 760 ms
popupPanel: 
  blocked: 5
```
</details>

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go into the logger and post here a **screenshot containing only the blocked items** you see there 
(you can select only the blocked items in the search box)
