### ISSUE TITLE
movies2watch.tv: popups

### ISSUE THREAD

**Issue by wawazaza** [uBlockOrigin/uAssets#11633]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://movies2watch.tv/`

### Category

popups

### Describe the issue

pops up 3 or more tabs for ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 96
filterset (summary): 
  network: 79969
  cosmetic: 47332
  scriptlet: 16809
  html: 0
listset (total-discarded, last updated): 
  default: 
    TUR-0: 8779-90, 3d.8h.10m
    easylist: 62783-20, 3d.8h.9m
    easyprivacy: 26695-23, 3d.8h.8m
    plowe-0: 3680-818, 4d.12h.13m
    ublock-abuse: 77-0, 3d.8h.7m
    ublock-badware: 3831-70, 3d.8h.5m
    ublock-filters: 30176-161, 3d.8h.4m
    ublock-privacy: 194-2, 3d.8h.3m
    ublock-unbreak: 1696-39, 3d.8h.2m
    urlhaus-1: 7574-0, 23h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 242 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
movies2watch.tv##+js(aeld, mousedown)
```

Open ublock dashboard, go to the "_My filters_" tab, paste the line above in an empty line, click "_Apply changes_"

**Comment by Procyon-b** [comment]
@mapx- 
weird I didn't see your fix until a few moments ago.

**Comment by wawazaza** [comment]
thanks for the quick help xo

Marc Boucher ***@***.***>, 6 Şub 2022 Paz, 21:08 tarihinde
şunu yazdı:
