### ISSUE TITLE
planetatvonlinehd.com [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1163]
URL(s) where the issue occurs

`http://www.planetatvonlinehd.com/the-walking-dead-8x06-latino/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS

`https://www.planetatvonlinehd.com/the-walking-dead-8x16-latino/`

**Comment by KiLL4FuNK** [comment]
Opcion 2 Anti-Adblock + Pop-up

`https://www.planetatvonlinehd.com/dragon-ball-super-capitulo-68-latino/`

**Comment by mapx-** [comment]
I had to remove a filter added above (the player was broken - due to `atob=> noopFunc` filter ) for ads.

I get no ads even removing it. Could you test again ?

**Comment by KiLL4FuNK** [comment]
everything works perfect
