### ISSUE TITLE
[NSFW] popMagic sites

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11635]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://allcelebs.club/`
`https://www.finevids.xxx/`
`https://gifcandy.net/`
`https://www.pornwatchers.com/`
`https://xnxx.party/`

### Describe the issue

There are many sites with the same `popMagic` script where clicking any links will trigger a popup. I think it's better to report in one thread. These are not farm sites (redirecting to other sites) if I'm not mistaken.

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.1

### Settings

No change

### Notes

Proposed filters:

```
allcelebs.club,finevids.xxx,gifcandy.net,pornwatchers.com,xnxx.party##+js(acis, document.querySelectorAll, popMagic)

```

**Comment by stephenhawk8054** [comment]
More sites:

`http://chopris.com`
`https://faptube.com/`
`https://www.xsportshd.com/`

Also when clicking on any categories below in `xsportshd` site, there's a GIF ad banner at the top at next page

Proposed filters:

```
chopris.com,faptube.com,xsportshd.com##+js(acis, document.querySelectorAll, popMagic)
||xsportshd.com/bet.gif$image
```

**Comment by mapx-** [comment]
@stephenhawk8054 
Could you prepare directly PR for your future contributions ? Thx.

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Could you prepare directly PR for your future contributions ? Thx.

Ok, I'll try PR next times 👍
