### ISSUE TITLE
ancient-civilizations.com: nuisance

### ISSUE THREAD

**Issue by JacksonChen666** [uBlockOrigin/uAssets#11638]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ancient-civilizations.com/ancient-egyptian-civilization/`

### Category

nuisance

### Describe the issue

Website contains subscribe boxes on the side, and a subscribe prompt that prevents scrolling.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-02-07 at 11-11-59 Ancient Egyptian Civilization](https://user-images.githubusercontent.com/50755746/152768322-e85aa893-ed98-4b11-87e8-7b85a87a342f.png)
![Screenshot 2022-02-07 at 11-12-10 Ancient Egyptian Civilization](https://user-images.githubusercontent.com/50755746/152768339-14627801-4eb1-4c45-a78a-5a1f4b14e5e9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 122623
  cosmetic: 114460
  scriptlet: 32918
  html: 624
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61480-3715, 5d.13h.14m
    adguard-spyware: 25862-580, 5d.19h.44m
    adguard-spyware-url: 458-14, 5d.19h.34m
    block-lan: 44-0, 2d.23h.28m
    adguard-annoyance: 49793-658, 5d.19h.36m
    fanboy-thirdparty_social: 68-0, 5d.16m
    ublock-annoyances: 4384-185, 5d.19h.35m
    curben-phishing: 9248-3, 2d.23h.26m
  default: 
    ublock-filters: 30753-27, 3d.19h.3m
    ublock-badware: 3835-1, 5d.20h.5m
    ublock-privacy: 193-0, 5d.20h.4m
    ublock-abuse: 77-0, 5d.20h.3m
    ublock-unbreak: 1703-0, 5d.20h.2m
    easylist: 62544-1014, 5d.19h.45m
    easyprivacy: 26691-10532, 5d.19h.43m
    urlhaus-1: 7611-0, 2d.23h.27m
    plowe-0: 3676-883, 14d.1h.35m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 355 ms (selfie)
popupPanel: 
  blocked: 4
```
</details>

**Comment by JacksonChen666** [comment]
i just realized a category for popups could work, or should've been that instead.

**Comment by mapx-** [comment]
Add `Fanboy’s Annoyance` and see if works for you

**Comment by JacksonChen666** [comment]
@mapx- default settings, checked `Fanboy's Annoyance`, applied and purged then refreshed all.

result is, no popups (tried long enough) and the subscribe box on the side is also gone (but filled with empty space). no problems here after enabling `Fanboy's Annoyance`.

**Comment by JacksonChen666** [comment]
wait, nevermind, let me test further

**Comment by JacksonChen666** [comment]
ok, i don't think there's a problem any more. no popups with filter.
