### ISSUE TITLE
element zapping mode does not work in mobile firefox

### ISSUE THREAD

**Issue by antymat** [uBlockOrigin/uAssets#11634]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

No, I do not want to waste my time copying from mobile. What you filled was rubbish. 

### Category

[unknown]

### Describe the issue

The zapper does not zap. I zap, swipe right twice, the element is still there. 
Whoever thought "swiping right twice" is a good method of closing element zapper, should swap his head with his arse back - the previous swap did not work. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 114896
  cosmetic: 160311
  scriptlet: 22196
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.8h.25m
    DEU-0: 5332-0, 8h.16m
    POL-0: 7758-8, 8h.15m
    POL-2: 1273-13, 1d.8h.26m
    adguard-annoyance: 49922-156, 1d.12h.39m
    adguard-social: 15775-771, 1d.12h.38m
    adguard-spyware: 25887-572, 1d.12h.37m
    adguard-spyware-url: 479-1, 1d.12h.36m
    block-lan: 44-0, 5d.5h.59m
    fanboy-annoyance: 60509-3943, 8h.19m
    fanboy-cookiemonster: 22102-22102, 8h.18m
    fanboy-social: 23152-23152, 1d.12h.33m
    fanboy-thirdparty_social: 69-21, 8h.17m
    ublock-annoyances: 4376-266, 1d.12h.31m
  default: 
    easylist: 62904-117, 1d.12h.35m
    easyprivacy: 26699-10484, 1d.12h.34m
    plowe-0: 3679-882, 1d.21m
    ublock-abuse: 77-0, 1d.12h.32m
    ublock-badware: 3831-76, 1d.12h.30m
    ublock-filters: 30181-525, 1d.12h.29m
    ublock-privacy: 194-37, 1d.12h.28m
    ublock-unbreak: 1699-58, 1d.12h.27m
    urlhaus-1: 7536-0, 8h.14m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 295 ms (selfie)
popupPanel: 
  blocked: 9
```
</details>

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-zapper#on-touch-screen-devices

> On touch screen devices:
> 
>    - tap once to select element
>    - tap highlighted element to remove it
>    - swipe right to remove incorrect highlighting
>    - swipe right to exit element-zapper mode

**Comment by krystian3w** [comment]
Touch actions works on PC with touch monitors or tablets with Windows ARM?

**Comment by gwarser** [comment]
@krystian3w no idea.

**Comment by antymat** [comment]
Mobile firefox, not a regular one. On Android. 
Still, if this abomination of a user interface migrated to the PC too, I would not mention it. It's shameful.
