### ISSUE TITLE
[nsfw] ghadir-group.com: [unknown]

### ISSUE THREAD

**Issue by amin65a** [uBlockOrigin/uAssets#11636]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ghadir-group.com/`

### Category

vulna

### Describe the issue

attack 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 154644
  cosmetic: 142074
  scriptlet: 33924
  html: 0
listset (total-discarded, last updated): 
  added: 
    BGR-0: 0-0, never
    CHN-0: 27870-1097, 41m
    CZE-0: 778-40, 41m
    DEU-0: 5332-371, 41m
    EST-0: 0-0, never
    FIN-0: 1517-75, 41m
    JPN-1: 5852-133, 41m
    RUS-0: 0-0, never
    THA-0: 981-3, 39m
    TUR-0: 8793-249, 41m
    VIE-1: 2282-31, 41m
    adguard-annoyance: 49944-1696, 41m
    adguard-generic: 61624-1175, 41m
    adguard-mobile: 7196-102, 41m
    adguard-social: 15775-1848, 41m
    adguard-spyware: 25889-660, 41m
    adguard-spyware-url: 480-12, 41m
    ara-0: 0-0, never
    block-lan: 44-0, 41m
    curben-phishing: 9565-0, 40m
    [10 lists not shown]: [too many]
  default: 
    easylist: 62978-24811, 25m
    easyprivacy: 26717-10641, 23m
    plowe-0: 3715-981, never
    ublock-abuse: 77-0, 40m
    ublock-badware: 3749-228, 40m
    ublock-filters: 30195-3581, 39m
    ublock-privacy: 194-38, 39m
    ublock-unbreak: 1705-112, 39m
    urlhaus-1: 7424-3, 39m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 7 redacted]
hostRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  colorBlindFriendly: true
  ignoreGenericCosmeticFilters: true
  largeMediaSize: 5
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 754 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
```
</details>

**Comment by mapx-** [comment]
Try explaining what is this about. Details, examples ?
