### ISSUE TITLE
etsy.com: Ads in search results

### ISSUE THREAD

**Issue by Snarp** [uBlockOrigin/uAssets#11646]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.etsy.com/search`

### Describe the issue

Deceptive advertisements appear among search results. They can be distinguished from legitimate results only by a pale-gray label saying "Ad by Etsy seller" where the vendor's name would ordinarily be.

### Screenshot(s)

![Screenshot from 2022-02-07 20-55-58](https://user-images.githubusercontent.com/18204600/152905992-05dbb804-c03c-4550-ae75-1e03df3b398c.jpg)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 96.0 (64-bit)

### Settings

- None

### Notes

Etsy's search results treat advertisements as the default and legitimate results as a subclass thereof. All results contain the text "Ad by Etsy seller" and "Ad from Etsy seller" (set to `display: none` in legitimate listings) in order to break `:has-text()` filters. Ads can be most easily distinguished because legitimate results contain certain added child elements, some child elements contain added properties, etc.

Suggested filters:

- `etsy.com##div[data-search-results-region] li:not(:has([data-appears-component-name="search2_organic_listings_group"]))`
- `etsy.com##div[data-search-results-region] li:not(:has(a.listing-link[href*="organic_search_click"]))`

**Comment by GreenBeard** [comment]
@stephenhawk8054 This filter no longer appears to work. I was wondering if you could change it to `www.etsy.com##.wt-grid>li:has(.wt-text-caption>*:has-text(/^Ad by .*$/):not(:matches-css(display: none)))`. I'm not sure how to make it more efficient without sacrificing robustness :/

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 This filter no longer appears to work. I was wondering if you could change it to `www.etsy.com##.wt-grid>li:has(.wt-text-caption>*:has-text(/^Ad by .*$/):not(:matches-css(display: none)))`. I'm not sure how to make it more efficient without sacrificing robustness :/

Does this work for you?

`etsy.com##.listing-link[href*="ref=listing_grid"]:upward(li)`

**Comment by GreenBeard** [comment]
Yeah, that seems to work for me
