### ISSUE TITLE
my.babbel.com: breakage

### ISSUE THREAD

**Issue by andryandrew** [uBlockOrigin/uAssets#11649]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.babbel.com/dashboard`

### Category

breakage

### Describe the issue

When uBlock is active, completing a review unit does not update the "review counter", which keeps track of how many exercises are done during the week.
Using the logger, I saw that some pings were blocked right at the completion of each exercise:

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +20 | *$ping,3p | -- | my.babbel.com | 3 | ping | `https://api.babbel.io/gamma/v1/events` |
| +10 | *$ping,3p | -- | my.babbel.com | 3 | ping | `https://api.babbel.io/gamma/v1/events` |
| +0 | *$ping,3p | -- | my.babbel.com | 3 | ping | `https://api.babbel.io/gamma/v1/events` |

coming from EasyPrivacy.

After adding a rule to allow them to pass:
`@@||api.babbel.io/gamma/v1/events$ping,domain=my.babbel.com`
everything works normally.

Unfortunately, testing this requires a Babbel subscription: I am available to further debug if needed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 78388
  cosmetic: 41002
  scriptlet: 16386
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63106-9, 26m
    easyprivacy: 26545-119, 26m
    plowe-0: 3679-807, 26m
    ublock-abuse: 77-0, 26m
    ublock-badware: 3738-71, 26m
    ublock-filters: 30181-150, 26m
    ublock-privacy: 194-2, 26m
    ublock-unbreak: 1704-39, 26m
    urlhaus-1: 7900-0, 26m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 340 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
