### ISSUE TITLE
crab.fit: breakage

### ISSUE THREAD

**Issue by GRA0007** [uBlockOrigin/uAssets#11645]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crab.fit/h0ney-h1est-378910`

### Category

breakage

### Describe the issue

The API of https://crab.fit requests a page like so: `https://api-dot-crabfit.uc.r.appspot.com/event/h0ney-h1est-378910` to get event data. As of a few days ago, a new rule was added `||appspot.com/event` that prevents the API from loading. The site does not contain any ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/8862273/152904615-ab32c8b6-bc9a-4969-acd3-45a77b96b1c9.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/8862273/152904651-6ff285db-c2f4-473a-9994-cbfa3bf9d1dd.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 78466
  cosmetic: 40892
  scriptlet: 16488
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62827-9, 3d.15h.55m
    easyprivacy: 26696-18, 3d.15h.53m
    plowe-0: 3679-817, 9d.13h.50m
    ublock-abuse: 77-0, 3d.15h.54m
    ublock-badware: 3831-72, 3d.15h.52m
    ublock-filters: 30183-148, 3d.15h.50m
    ublock-privacy: 194-2, 3d.15h.47m
    ublock-unbreak: 1696-39, 3d.15h.51m
    urlhaus-1: 7900-0, 12h.32m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 204 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
