### ISSUE TITLE
20minutes.fr: detection

### ISSUE THREAD

**Issue by kwenkwenuuuuu** [uBlockOrigin/uAssets#11641]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.20minutes.fr/`

### Category

detection

### Describe the issue

Popup with Adblock detected hides page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 93
filterset (summary): 
  network: 95740
  cosmetic: 28595
  scriptlet: 16435
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30846-425, 1d.6h.18m
    ublock-badware: 3753-0, 1d.6h.4m
    ublock-privacy: 193-1, 10h.49m
    ublock-abuse: 77-0, 10h.47m
    ublock-unbreak: 1722-0, 10h.48m
    adguard-mobile: 7196-169, 10h.44m
    easylist: 62978-24440, 10h.45m
    easyprivacy: 26717-488, 10h.46m
    urlhaus-1: 7536-0, 1d.6h.3m
    plowe-0: 3679-2, 11d.28m
    FRA-0: 26017-3614, 1d.9h.32m
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1624 ms (selfie)
popupPanel: 
  blocked: 13
```
</details>

**Comment by Procyon-b** [comment]
It could be one of your "user filters". Go to the "_Filter lists_" ("_Liste des filtres_") tab and uncheck "_My filters_" ("_Mes filtres_"), then click "_Apply Changes_" ("_Appliquer_").
Reload the webpage.
Don't forget to re-enable "My filters", and, if it fixed the detection, try to find the filter that caused it.

**Comment by PoRtv1ne** [comment]
![2022-02-08_201946](https://user-images.githubusercontent.com/99283919/153051055-9f1ac74c-20e3-4c0c-a50b-463f31876e3e.png)
![2022-02-08_202000](https://user-images.githubusercontent.com/99283919/153051058-abafd683-d93e-4698-b0c8-2bb9e6b620d4.png)
![2022-02-08_201921](https://user-images.githubusercontent.com/99283919/153051060-25e0d078-4345-4595-a731-0a380ce87eaa.png)

**Comment by mapx-** [comment]
Did you add the french list ?

![image](https://user-images.githubusercontent.com/10303732/153051750-049544d3-b29c-4101-abdd-b985df77a1d5.png)

**Comment by Procyon-b** [comment]
Apparently it's part of his configuration

**Comment by mapx-** [comment]
I responded to `PoRtv1ne` .. which now seems to have been deleted his profile

**Comment by Procyon-b** [comment]
@mapx- I've seen my error, and deleted my comment before your reply. Sorry.

**Comment by Procyon-b** [comment]
> which now seems to have been deleted his profile

"Deleted user" is his fullname.

**Comment by iam-py-test** [comment]
> "Deleted user" is his fullname.
> Are you sure that its a real deleted user?

@ghost is just a placeholder for deleted accounts
