### ISSUE TITLE
Browser-addons.com ads & FingerprintJS pro fingerprinting

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#11659]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

	  https://browser-addons.com/jurassic-world-evolution/
	  https://fingerprintjs.com/demo/

### Describe the issue

Please block `ladnet.co`, I blocked it and the ads disappeared! Also please block `fpaux.net`, it performs fingerprinting on your browser!

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 97.0.4692.99

### Settings

My filters:

	  ! 2021-10-21 https://pixlr.com
	  pixlr.com##[src="/dad/slot/"]
	  pixlr.com###slot
	  
	  ||fpaux.net^
	  
	  ||ladnet.co^

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Didn't see   ||fpaux.net^

**Comment by uBlock-user** [comment]
@ryanbr I see it at `https://fingerprintjs.com/demo/`

**Comment by JobcenterTycoon** [comment]
@ryanbr there is a new domain now `fpaxu.net`
