### ISSUE TITLE
toggo.de: breakage

### ISSUE THREAD

**Issue by tweiske** [uBlockOrigin/uAssets#11654]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.toggo.de/die-nektons`

### Category

breakage

### Describe the issue

Website is completely white (empty). Disabling ublock makes the website appear normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox nektons](https://user-images.githubusercontent.com/77881236/152991382-98351a32-e5a0-43a9-8d0e-1ad8378a172f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 80483
  cosmetic: 44214
  scriptlet: 16355
  html: 614
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30762-35, 9m
    ublock-badware: 3742-0, 3m
    ublock-privacy: 193-0, 6m
    ublock-abuse: 77-0, 8m
    ublock-unbreak: 1707-0, 7m
    easylist: 63106-603, 11m
    easyprivacy: 26545-582, 5m
    urlhaus-1: 7900-0, 20h.16m
    plowe-0: 3679-2, 3d.10h.22m
    DEU-0: 5332-2, 20h.15m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1338 ms
popupPanel: 
  blocked: 16
```
</details>

**Comment by uBlock-user** [comment]
```
@@||toggo.de/static/js/sourcepoint.js^$script,1p
@@||bilder-a.akamaihd.net/ip/js/ipdvdc/ipdvdc.min.js^$script,domain=toggo.de
```

@ryanbr
