### ISSUE TITLE
vier.be

### ISSUE THREAD

**Issue by SeiryuuEU** [uBlockOrigin/uAssets#1165]
### URL(s) where the issue occurs

`https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-seizoen-15/de-slimste-mens-ter-wereld-seizoen-15-aflevering-40-finale`

### Describe the issue

Anti-adblock prevents the video from being viewed unless you turn off the extension. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/35082357/34543660-595af756-f0e2-11e7-831c-055bcd8cd474.png)
Translation: "It appears your adblocker is still enabled." 

### Versions

- Browser/version: Chrome 63.0.3239.84
- uBlock Origin version: v1.14.22

### Settings

- Adblock Warning Removal List enabled
- Nano defender filters enabled

### Notes

Sign in is required.
With the adblocker enabled you only hear the audio track.

**Comment by mapx-** [comment]
Could you test:
`vier.be##script:inject(abort-on-property-write.js, _sp_)`

**Comment by SeiryuuEU** [comment]
Works like a charm! Thank you very much. :-)
