### ISSUE TITLE
cyberkrafttraining.com: nuisance

### ISSUE THREAD

**Issue by jflattery** [uBlockOrigin/uAssets#11658]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cyberkrafttraining.com/2021/08/17/the-ports-and-protocols-you-need-to-know-for-the-sy0-601-security-exam/`

### Category

nuisance

### Describe the issue

Selecting text and right clicking is blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 89917
  cosmetic: 136105
  scriptlet: 21425
  html: 622
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 49928-699, 2d.23h.11m
    fanboy-annoyance: 64090-6425, 23h.7m
    ublock-annoyances: 4385-4, 2d.23h.10m
  default: 
    ublock-filters: 30757-28, 2d.23h.19m
    ublock-badware: 3845-1, 2d.23h.17m
    ublock-privacy: 193-0, 2d.23h.16m
    ublock-abuse: 77-0, 2d.23h.15m
    ublock-unbreak: 1707-0, 2d.23h.14m
    easylist: 62910-650, 2d.23h.13m
    easyprivacy: 26703-480, 2d.23h.12m
    urlhaus-1: 8213-0, 15h.6m
    plowe-0: 3680-2, 5d.22h.39m
filterset (user): [array of 25 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 566 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by jflattery** [comment]
Thanks!

**Comment by jflattery** [comment]
The site also breaks printing. Should that be a new issue? @mapx-

**Comment by mapx-** [comment]
I'll take a look at it
