### ISSUE TITLE
clever.com: breakage

### ISSUE THREAD

**Issue by Cameron123456789101** [uBlockOrigin/uAssets#11663]
### Prerequisites

- [ ] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://clever.com/in/hampton/student/portal`

### Category

breakaget

### Describe the issue

ufdewsdfg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
bh

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78151
  cosmetic: 41000
  scriptlet: 16372
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63127-9, 3h.18m
    easyprivacy: 26545-120, 3h.17m
    plowe-0: 3677-807, 4d.3h.27m
    ublock-abuse: 77-0, 3h.16m
    ublock-badware: 3738-71, 3h.15m
    ublock-filters: 30162-150, 3h.14m
    ublock-privacy: 194-2, 3h.13m
    ublock-unbreak: 1705-39, 3h.12m
    urlhaus-1: 7648-0, 3h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6327 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>jjj

**Comment by Cameron123456789101** [comment]
35557

**Comment by iam-py-test** [comment]
Redirects to a signin page. Can you specify what breakage occurs?

**Comment by uBlock-user** [comment]
> ufdewsdfg

Closing as invalid.
