### ISSUE TITLE
solarmoviez.ru

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1166]
### URL(s) where the issue occurs

`https://solarmoviez.ru/solar.html`
`https://solarmoviez.ru/movie/the-greatest-showman-23205/1175621-7/watching.html`

### Describe the issue

Netflix ad

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/34545895-1dd9ceba-f0be-11e7-8f2a-84af6ce973a5.png)
![image](https://user-images.githubusercontent.com/12802056/34545948-9beb7722-f0be-11e7-96cb-7dc093fe1cfb.png)

### Versions

- Browser/version: Chrome 63
- uBlock Origin version: 1.14.22

### Settings

Default

**Comment by okiehsch** [comment]
`||imgur.com^$image,domain=solarmoviez.ru`

**Comment by terrorist96** [comment]
That works, but for the one within the video, this still appears:
![image](https://user-images.githubusercontent.com/12802056/34546501-39365882-f0c2-11e7-81ef-d0b115daf527.png)

**Comment by okiehsch** [comment]
Hm, I don't get any within the video, even if I do not add
`||imgur.com^$image,domain=solarmoviez.ru`.

![aufzezren](https://user-images.githubusercontent.com/16838044/34547054-98becfd8-f0f8-11e7-80e2-5ccb42ac026c.JPG)

**Comment by terrorist96** [comment]
I just tried on a test account with only uBO and got the netflix ad in the video. Could it be IP based? Can you try from a US IP?

**Comment by okiehsch** [comment]
Same result, can you use the picker to identify the element?

**Comment by terrorist96** [comment]
###overlay-solarplugin
###timer-close
###timer-text

**Comment by okiehsch** [comment]
Well does 
`solarmoviez.ru###overlay-solarplugin` work or does it hide too much?

**Comment by terrorist96** [comment]
That works. Thanks!

**Comment by terrorist96** [comment]
I get an unblocked popup when clicking on the homepage.
e.g. `http://35.193.89.147/OTIxMzAxMTUyNTk0LzkyMTMwMzM0OTc2OS8wd21ncm5rd3ho`
