### ISSUE TITLE
3voor12.vpro.nl: breakage

### ISSUE THREAD

**Issue by murb** [uBlockOrigin/uAssets#11669]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://3voor12.vpro.nl/speel~WO_VPRO_15584494~interpol-live-at-best-kept-secret-2019~.html`

### Category

breakage

### Describe the issue

the NPO hosted video's should be visible; 3voor12 is a VPRO initiative which is part of npo.nl (dutch public broadcaster)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78493
  cosmetic: 40935
  scriptlet: 16343
  html: 614
listset (total-discarded, last updated): 
  removed: 
    NLD-0: null
  default: 
    ublock-filters: 30741-27, 2d.1h.56m
    ublock-badware: 3742-0, 2d.1h.55m
    ublock-privacy: 193-0, 2d.1h.54m
    ublock-abuse: 77-0, 2d.1h.53m
    ublock-unbreak: 1715-0, 2d.1h.57m
    easylist: 62979-597, 2d.1h.52m
    easyprivacy: 26718-480, 2d.1h.51m
    urlhaus-1: 7801-0, 8h.32m
    plowe-0: 3679-2, 4d.8h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 156 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by okiehsch** [comment]
@ryanbr broken by `EasyPrivacy` filter `/streamsense.min.js`
`@@||3voor12.vpro.nl/*/vpro-mediaplayer/*$script,1p`
works on my end.

**Comment by murb** [comment]
thanks @okiehsch, applied it locally and fixes the problem indeed.

**Comment by ryanbr** [comment]
Getting a 503 error message, whats the full vpro-mediaplayer url ?

**Comment by murb** [comment]
https://3voor12.vpro.nl/.resources/vpro/themes/vpronl/js/jspm_packages/npm/vpro-frontend-module@1.0.15/vpro-mediaplayer/js/lib/streamsense.min.js ... this indeed triggers scorecardresearch.com requests, but these are blocked by Peter Lowe’s Ad and tracking server list.

It is very disappointing that this Dutch public broadcaster is creating such a mess online.
