### ISSUE TITLE
atv.at: ads

### ISSUE THREAD

**Issue by kendlbat** [uBlockOrigin/uAssets#11665]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.atv.at/tv/die-finanzpolizei/staffel-03/episode-02/staffel-03-folge-02-die-finanzpolizei`

### Category

ads

### Describe the issue

Ads are still showing even after multiple attempts at creating filters.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78564
  cosmetic: 40888
  scriptlet: 16439
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30743-27, 3d.14h.39m
    ublock-badware: 3845-1, 3d.14h.38m
    ublock-privacy: 193-0, 3d.14h.37m
    ublock-abuse: 77-0, 3d.14h.36m
    ublock-unbreak: 1711-0, 3d.14h.35m
    easylist: 62910-595, 3d.14h.34m
    easyprivacy: 26703-480, 3d.14h.33m
    urlhaus-1: 7900-0, 1d.10h.44m
    plowe-0: 3679-2, 3d.14h.31m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1435 ms (selfie)
popupPanel: 
  blocked: 42
```
</details>

**Comment by okiehsch** [comment]
Does adding
````
*&expires$media,redirect=noopmp3-0.1s,domain=atv.at
||zomap.de/*&expires=$script,domain=atv.at
````
to your filter lists work for you?

**Comment by kendlbat** [comment]
It appears it does! Thank you very much!
