### ISSUE TITLE
dw1yv7zga8.questionpro.eu: breakage

### ISSUE THREAD

**Issue by cweiske** [uBlockOrigin/uAssets#11668]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dw1yv7zga8.questionpro.eu/`

### Category

breakage

### Describe the issue

When ublock origin is enabled, the page is completely white with only a small orange line on the top.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-02-09_1](https://user-images.githubusercontent.com/59036/153240785-8c16fb09-dcb1-4a4e-9220-03844d08018a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 80391
  cosmetic: 44232
  scriptlet: 16348
  html: 614
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30753-27, 1d.3h.32m
    ublock-badware: 3742-0, 1d.3h.31m
    ublock-privacy: 193-0, 1d.3h.30m
    ublock-abuse: 77-0, 1d.3h.29m
    ublock-unbreak: 1716-0, 1d.3h.28m
    easylist: 63106-603, 1d.3h.27m
    easyprivacy: 26545-582, 1d.3h.26m
    urlhaus-1: 7801-0, 4h.5m
    plowe-0: 3679-2, 9d.9h.24m
    DEU-0: 5335-10, 4h.6m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 22 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1973 ms (selfie)
popupPanel: 
  blocked: 2
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/2f96b4d1f091fef5c210c2c460b5b53805f0d8f1
