### ISSUE TITLE
gogoanimes.to: breakage

### ISSUE THREAD

**Issue by justin5790** [uBlockOrigin/uAssets#11662]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gogoanimes.to/anime-list-B`

### Category

Posted this on reddit and they told me to post here since they couldn't find the issue.
Basically with ublock enabled the page won't load. just keeps loading infinitely forever.

### Describe the issue

Posted this on reddit and they told me to post here since they couldn't find the issue.
Basically with ublock enabled the page won't load. just keeps loading infinitely forever.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78725
  cosmetic: 41012
  scriptlet: 16399
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63126-9, 6h.51m
    easyprivacy: 26545-120, 6h.51m
    plowe-0: 3679-807, 6h.51m
    ublock-abuse: 77-0, 6h.51m
    ublock-badware: 3738-71, 6h.51m
    ublock-filters: 30206-150, 6h.51m
    ublock-privacy: 197-2, 6h.51m
    ublock-unbreak: 1705-39, 6h.51m
    urlhaus-1: 8213-0, 6h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 843 ms (selfie)
popupPanel: 
  blocked: 0
```
</details>

**Comment by gwarser** [comment]
Configuration looks fine.

![obraz](https://user-images.githubusercontent.com/886325/153102011-56f9a91b-ab8d-4d25-9c89-e2349fb396e1.png)

**Comment by justin5790** [comment]
> 

i just tried it in firefox and it works.... just not in chrome

**Comment by uBlock-user** [comment]
Disable all other extensions on Chrome and try again.

**Comment by gorhill** [comment]
> - [X] I did not answer truthfully to **all** the above checkpoints

Please go through all the steps again and answer truthfully, they are there to ensure that the issue is not on your side -- for example to rule out that another extension is negatively interfering, etc.
