### ISSUE TITLE
inbox.lv: detection

### ISSUE THREAD

**Issue by bceez** [uBlockOrigin/uAssets#11671]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.inbox.lv/`

### Category

detection

### Describe the issue

Anti-adblock script

### Screenshot(s)

![Screenshot_20220209-182731_Firefox Beta](https://user-images.githubusercontent.com/99037750/153257337-9f821767-e069-47e9-b773-a9090b6596a9.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 97
filterset (summary): 
  network: 79760
  cosmetic: 22679
  scriptlet: 16400
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30891-264, 2m
    ublock-badware: 3751-0, 2m
    ublock-privacy: 196-1, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1722-0, 2m
    adguard-mobile: 7207-169, 2m
    easylist: 63136-24383, 2m
    easyprivacy: 26547-579, 2m
    urlhaus-1: 7801-0, 2m
    plowe-0: 3679-2, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6117 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by okiehsch** [comment]
Already fixed in `uBO-annoyances` you can enable that list or add
````
*$script,redirect-rule=noopjs,domain=inbox.lv
````
to your filter list.
