### ISSUE TITLE
mittelhessen.de: detection

### ISSUE THREAD

**Issue by PanzergrenadierBBC** [uBlockOrigin/uAssets#11677]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mittelhessen.de/`

### Category

detection

### Describe the issue

Since yesterday (9th of februrary 2022) the site is using an addblcok detector which is recognizing ublock Origin.
I'm not sure which new script is the reason for it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/99392236/153369783-d92102f9-c667-497d-891b-b1e8f101a1dc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 97
filterset (summary): 
  network: 93522
  cosmetic: 44482
  scriptlet: 16904
  html: 613
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 25919-654, now
    adguard-spyware-url: 481-3, now
  default: 
    ublock-filters: 30793-38, 8m
    ublock-badware: 3751-0, 8m
    ublock-privacy: 196-0, 7m
    ublock-abuse: 77-0, 7m
    ublock-unbreak: 1715-0, 7m
    easylist: 63178-636, 7m
    easyprivacy: 26546-12201, 7m
    urlhaus-1: 7537-0, 7m
    plowe-0: 3679-2, 7m
    DEU-0: 5342-2, 7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1451 ms
popupPanel: 
  blocked: 11
```
</details>

**Comment by garry-ut99** [comment]
(still AA for me with `ghide` off) Many big ad placeholders caused by `ghide` from "uBlock Filters":  [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218127593-3fda35c2-831f-468e-b575-6cf5138fe5a4.png)
