### ISSUE TITLE
Forces TV guide

### ISSUE THREAD

**Issue by JohnVeness** [uBlockOrigin/uAssets#11673]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.forces.net/forces-tv`

### Describe the issue

Near the bottom, between the row of buttons that starts "Today", then (currently) "Thu 10 Feb", "Fri 11 Feb" etc. is supposed to be a TV guide, i.e. listings of what's on this TV channel. With uBO enabled with default settings/lists, this is hidden.

### Screenshot(s)

With uBO disabled, there is a TV guide:
![image](https://user-images.githubusercontent.com/2512915/153268370-04e509a2-351a-4ce5-b57c-2be71d9c1520.png)

With uBO enabled, TV guide is hidden:
![image](https://user-images.githubusercontent.com/2512915/153268472-d0b838ae-12ee-4270-aebd-1c64b89010fb.png)

### Notes

Sorry, I have not done any further troubleshooting, other than confirming this happens in a brand-new Firefox profile with only uBO installed.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78885
  cosmetic: 41017
  scriptlet: 16348
  html: 614
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.8h.35m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 7799-0, 5h.4m
  default: 
    ublock-filters: 30753-27, 1d.8h.45m
    ublock-badware: 3742-0, 1d.8h.43m
    ublock-privacy: 193-0, 1d.8h.42m
    ublock-abuse: 77-0, 1d.8h.41m
    ublock-unbreak: 1715-0, 1d.8h.40m
    easylist: 63107-215, 1d.8h.39m
    easyprivacy: 26545-146, 1d.8h.38m
    urlhaus-1: 7537-6945, 5h.3m
    plowe-0: 3679-809, 1d.8h.36m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 11199 ms (selfie)
```
</details>

**Comment by mapx-** [comment]
add
`@@||cdn.bidder.dev/clients/*/Forces/script.js$script,domain=forces.net`

EL issue @ryanbr
