### ISSUE TITLE
manga.hiseku.com: detection

### ISSUE THREAD

**Issue by moch1oka** [uBlockOrigin/uAssets#11687]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manga.hiseku.com/manga/otonari-no-tenshi-sama/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/52909100/153533952-7c9161a3-e293-41dc-8603-c5e7d7216aa6.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/52909100/153533971-7ed7a519-eead-4b9e-8d8a-6daf98bba846.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 155291
  cosmetic: 185933
  scriptlet: 33029
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.23h.8m
    adguard-annoyance: 50105-153, 1d.9m
    adguard-generic: 61724-723, 23h.11m
    adguard-mobile: 7207-48, 1d.13h.9m
    adguard-social: 15777-775, 1d.13h.6m
    adguard-spyware: 25912-601, 1d.13h.5m
    adguard-spyware-url: 481-12, 1d.13h.7m
    curben-phishing: 10021-0, 22h.53m
    curben-pup: 412-0, 14h.5m
    dpollock-0: 10346-258, 5d.22h.55m
    fanboy-annoyance: 63837-7342, 6d.1h.48m
    fanboy-cookiemonster: 22088-22088, 6d.1h.49m
    fanboy-social: 23155-23146, 1d.13h.8m
    mvps-0: 8730-1724, 5d.22h.56m
    ublock-annoyances: 4389-296, 2d.1h.35m
  default: 
    VIE-1: 2267-0, 22h.48m
    easylist: 63106-1403, 2d.23h
    easyprivacy: 26547-12039, 1d.13h.4m
    plowe-0: 3679-1491, 3d.21h.58m
    ublock-abuse: 77-0, 1d.11m
    ublock-badware: 3747-234, 1d.10m
    ublock-filters: 30211-3320, 1d.7m
    ublock-privacy: 197-38, 1d.8m
    ublock-unbreak: 1705-111, 1d.6m
    urlhaus-1: 7264-4, 22h.49m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 824 ms (selfie)
popupPanel: 
  blocked: 7
```
</details>

**Comment by Procyon-b** [comment]
Try theses filters:
```
manga.hiseku.com##body>div[class*="-blackout"], body>div[class*="-wrapper"]
manga.hiseku.com##.wrap:style(filter: none !important)
```
