### ISSUE TITLE
gentwo.com: breakage (Strapi CMS default API request false positive)

### ISSUE THREAD

**Issue by maninak** [uBlockOrigin/uAssets#11682]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gentwo.com/pulse/blog/`

### Category

breakage

### Describe the issue

A legitimate, functional, non-privacy-invading request `https://cms.gentwo.com/pulses/count?type=Insights&type=Press+Release&type=Generic&publishedDate_null=false` is being blocked. This is 100% a false positive.

:warning:  **The request itself is [part of the default API of the popular CMS Strapi](https://docs-v3.strapi.io/developer-docs/latest/developer-resources/content-api/content-api.html#count-entries).** :warning:

More details:

![image](https://user-images.githubusercontent.com/7542054/153447627-788964d7-82e9-4132-88c8-a8f59ba6da3f.png)

**Reproduction steps:**

0. use chrome and uBlock origin (cannot be reproduced on Firefox + uBlock origin!)
1. got to `https://www.gentwo.com`
2. click "pulse" form the main nav
3. click "blog" from the sub-nav

**Expected behavior**

- All content is visible

**Actual behavior**

- blog post cards are not rendered
    
![image](https://user-images.githubusercontent.com/7542054/153446872-07e59f8b-f3b0-4524-a3d8-c8dbd8cdaff1.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78585
  cosmetic: 40106
  scriptlet: 16431
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 62254-462, never
    easyprivacy: 26549-483, never
    plowe-0: 3715-3, never
    ublock-abuse: 81-0, never
    ublock-badware: 3629-1, never
    ublock-filters: 30064-137, never
    ublock-privacy: 184-0, never
    ublock-unbreak: 1708-0, never
    urlhaus-1: 8168-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1378 ms
popupPanel: 
  blocked: 6
```
</details>

**Comment by mapx-** [comment]
`@@||cms.gentwo.com/pulses/$xhr,1p`

@ryanbr EP issue
