### ISSUE TITLE
quillbot.com: broken

### ISSUE THREAD

**Issue by evildevils** [uBlockOrigin/uAssets#11688]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://quillbot.com/`

### Describe the issue

I tried to disable uBlock Origin on quillbot.com completely followed by a few guidelines.

I clicked the large blue power button to turn off uBlock Origin for the site; however, this website kept breaking.

None of the buttons on this website doesn't work.

Please help me to fix this issue.

uBlock Origin version

1.40.8
Browser name and version

Firefox, 96.0.3
Settings

Everything default
only active uBlock filters

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 93445
  cosmetic: 0
  scriptlet: 16432
  html: 607
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-unbreak: null
  added: 
    CHN-0: 27904-10223, 23h.5m
    JPN-1: 5876-4829, 23h.4m
    KOR-1: 8093-6218, 23h.3m
  default: 
    ublock-filters: 30787-7414, 23h.8m
    easylist: 63178-33563, 23h.7m
    easyprivacy: 26546-574, 23h.6m
    urlhaus-1: 7264-0, 23h.2m
    plowe-0: 3679-0, 4d.23h.13m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 344 ms (selfie)
```
</details>

**Comment by uBlock-user** [comment]
> however, this website kept breaking.

What is broken ? Take a snapshot and highlight the breakage.

**Comment by evildevils** [comment]
Okay, 
First of all, the screen as requested,
![issue](https://user-images.githubusercontent.com/9406098/153543777-a4e08c9a-1b31-4c70-898e-8b193ddc2162.PNG)
those circled buttons are not responding.

And, I will try enabling "these" you just mentioned right now, then I will leave what's changing the next.

**Comment by evildevils** [comment]
> Okay, First of all, the screen as requested, ![issue](https://user-images.githubusercontent.com/9406098/153543777-a4e08c9a-1b31-4c70-898e-8b193ddc2162.PNG) those circled buttons are not responding.
> 
> And, I will try enabling "these" you just mentioned right now, then I will leave what's changing the next.

**Comment by evildevils** [comment]
Yep, still not working :(

**Comment by evildevils** [comment]
> Test on default settings/lists + all other extensions disabled

okay, give me a sec

**Comment by evildevils** [comment]
Still not working yet

**Comment by evildevils** [comment]
> Still not working yet

uBlock Origin: 1.41.2
Firefox: 97
filterset (summary): 
  network: 78720
  cosmetic: 40264
  scriptlet: 16343
  html: 614
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30741-113, never
    ublock-badware: 3742-0, never
    ublock-privacy: 193-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1715-0, never
    easylist: 62254-99, never
    easyprivacy: 26549-27, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-820, never
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1488 ms
  maxAssetCacheWait: 17 ms

**Comment by evildevils** [comment]
> > Still not working yet
> 
> uBlock Origin: 1.41.2 Firefox: 97 filterset (summary): network: 78720 cosmetic: 40264 scriptlet: 16343 html: 614 listset (total-discarded, last updated): default: user-filters: 0-0, never ublock-filters: 30741-113, never ublock-badware: 3742-0, never ublock-privacy: 193-0, never ublock-abuse: 77-0, never ublock-unbreak: 1715-0, never easylist: 62254-99, never easyprivacy: 26549-27, never urlhaus-1: 8168-0, never plowe-0: 3715-820, never filterset (user): [empty] trustedset: added: [array of 1 redacted] modifiedUserSettings: [none] modifiedHiddenSettings: [none] supportStats: allReadyAfter: 1488 ms maxAssetCacheWait: 17 ms

**Comment by mapx-** [comment]
update all your filter lists - click "purge all caches", click "update now"

**Comment by evildevils** [comment]
> I did, and it doesn't help at all :(

**Comment by uBlock-user** [comment]
Does it happen logged in or logged out ?

**Comment by mapx-** [comment]
> Does it happen logged in or logged out?

meaning => are you using an account on that site ?

**Comment by evildevils** [comment]
> > Does it happen logged in or logged out?
> 
> meaning => are you using an account on that site ?

AH, yes, I am totally!

**Comment by uBlock-user** [comment]
The snapshot you posted doesn't match with the buttons that appears when someone is not logged in. So someone with an account needs to investigate in order to see if it's reproduceable or not.

**Comment by evildevils** [comment]
> 

Because the screenshot I took was taken from my vertical monitor set. Here is another shot from a 'normal' monitor set
![111](https://user-images.githubusercontent.com/9406098/153562440-811a2cd3-62ab-4b32-bc77-5bb3ace0ae01.PNG)
.

**Comment by evildevils** [comment]
> > 
> 
> Because the screenshot I took was taken from my vertical monitor set. Here is another shot from a 'normal' monitor set ![111](https://user-images.githubusercontent.com/9406098/153562440-811a2cd3-62ab-4b32-bc77-5bb3ace0ae01.PNG) .

**Comment by mapx-** [comment]
I created an account, the buttons are working fine on my side.
