### ISSUE TITLE
kinopoisk.ru: detection

### ISSUE THREAD

**Issue by bceez** [uBlockOrigin/uAssets#11684]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kinopoisk.ru/`

### Category

detection

### Describe the issue

Anti adblock script on the bottom of the page

### Screenshot(s)

![Screenshot_20220210-183806_Firefox](https://user-images.githubusercontent.com/99037750/153464800-d1c25ff8-f983-43d5-80bd-cca41d19de9f.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox Mobile: 97
filterset (summary): 
  network: 79539
  cosmetic: 24039
  scriptlet: 19188
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4422-7, 2m
  default: 
    ublock-filters: 30882-387, 2m
    ublock-badware: 3754-0, 2m
    ublock-privacy: 196-1, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1722-0, 2m
    adguard-mobile: 7209-169, 2m
    easylist: 63209-24260, 2m
    easyprivacy: 26548-590, 2m
    urlhaus-1: 7264-0, 2m
    plowe-0: 3679-2, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 7234 ms (selfie)
popupPanel: 
  blocked: 41
```
</details>

**Comment by mapx-** [comment]
It's a russian site:

subscribe to `RUS: RU AdList`

and `Counters list`, see here:
https://forums.lanik.us/viewtopic.php?t=22512&sid=9e7046074e4e73471e9554eb7921ea2b
