### ISSUE TITLE
spott.ai blocked without any reason

### ISSUE THREAD

**Issue by DimiF4W** [uBlockOrigin/uAssets#11683]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

spott.ai

### Category

Wrong domain blocked

### Describe the issue

Spott is a company making content interactive and doesnt provide ads. At this time Spott is blocked everywhere, even the website and all content on domain spott.ai. Can you please remove this filter?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-02-10 at 18 27 40](https://user-images.githubusercontent.com/68825357/153462761-7e3a4a0e-5439-42d1-a56b-6b448fd53318.png)

</details>

### Configuration

||spott.ai^

**Comment by mapx-** [comment]
@DimiF4W other (third-party) breakage ? (not your own site)

**Comment by DimiF4W** [comment]
spott is not an ad server, it puts interactivity above videos/images

**Comment by uBlock-user** [comment]
> spott is not an ad server

https://github.com/uBlockOrigin/uAssets/issues/11038 contradicts your statements.

**Comment by mapx-** [comment]
@DimiF4W I asked you to provide legitimate use of spott.ai

**Comment by mapx-** [comment]
> zeb.be

You have to provide more details where / how is used spott, for now I get no spott.ai request

**Comment by okiehsch** [comment]
`https://www.zeb.be/nl/valentijn-heren`

**Comment by uBlock-user** [comment]
and whats is broken there ? Not seeing any breakage.

**Comment by mapx-** [comment]
> `https://www.zeb.be/nl/valentijn-heren`

ok, so in this case it's a very legitimate use of spott.ai
I propose to block only its use as ad (meaning on vtm.be where it was originally created)

What do you think @okiehsch ?

**Comment by okiehsch** [comment]
Allow the spott.ai requests and you will see.

**Comment by uBlock-user** [comment]
I did, don't see the difference, what do you see on your end ?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/153487182-1e2327f2-b07e-4391-aefc-78bda92c9f0f.png)
That is missing and it may be useful to users shopping on that site.

@uBlock-user can you give me the linkm or point me to for the video ads?

**Comment by uBlock-user** [comment]
> can you give me the link or point me to a link for the video ads?

`https://vtm.be/vtmgo/afspelen/efb17e615-92b5-41ac-a649-6413ae067592`

@okiehsch Given one site, we can restrict it via `$domain`

**Comment by uBlock-user** [comment]
That's what I said in https://github.com/uBlockOrigin/uAssets/issues/11683#issuecomment-1035438882

**Comment by okiehsch** [comment]
> What do you think @okiehsch ?

@mapx- 
I am not sure.
I don't see an issue on `moncler.com` and checked a few other sites I found via `publicwww`.

Now I have not found any sites using it for ads either other than the one mentioned here.

**Comment by okiehsch** [comment]
`||spott.ai^$domain=vtm.be`

Yes, that's the best solution for now imo.

**Comment by uBlock-user** [comment]
@okiehsch Can you link to to the image you posted ?

**Comment by mapx-** [comment]
> @okiehsch Can you link to the webpage from the image you posted ?

`https://images.spott.ai/resize?quality=50&width=555&url=https%3A%2F%2Fimages.spott.ai%2FINTERACTIVE_MEDIA%2F95acdacf-f9b7-4df5-bd30-e007353788b6`

**Comment by uBlock-user** [comment]
No I meant the page on `zeb.be`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/63089680317939dbee650347d28be764c3285c8a

**Comment by DimiF4W** [comment]
This is an example on Moncler:
https://www.moncler.com/en-be/men/outerwear/jackets/ostafa-jacket-black-G20971A0001257316999.html
