### ISSUE TITLE
verliga.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1169]
URL(s) where the issue occurs

`http://verliga.net/verliga-6.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
I skipped the anti adblock

**Comment by xDarkARG** [comment]
I skipped the anti adblock  @mapx-

**Comment by mapx-** [comment]
What do you mean ?

**Comment by xDarkARG** [comment]
that I still get the message anti adblock

**Comment by xDarkARG** [comment]
that I still get the message anti adblock @mapx-
