### ISSUE TITLE
backinthegame.myshopify.com broken

### ISSUE THREAD

**Issue by MathieuJDS** [uBlockOrigin/uAssets#11690]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://backinthegame.myshopify.com/products/product-example-1`

### Describe the issue

WideBundle is a Shopify App that displays bundles on a store.

Unfortunately, the domain "widebundle.com" is blocked for no reason so the app doesn't appear at all

### Screenshot(s)

With uBlock enabled:

<img width="471" alt="Product Example 1 – backinthegame 2022-02-11 12-31-14" src="https://user-images.githubusercontent.com/32767485/153584335-9cbb667b-fdc9-432e-bb4b-20f3b0ceac57.png">

With uBlock disabled:

![image](https://user-images.githubusercontent.com/32767485/153584418-dd7e3e9d-c159-4c84-8f10-2ba0e157f3d6.png)

### uBlock Origin version

1.41.2

### Browser name and version

Chrome Version 98.0.4758.80

### Settings

No change

**Comment by uBlock-user** [comment]
`@@||widebundle.com/scripttag.php?shop=$script,domain=backinthegame.myshopify.com`

@ryanbr
