### ISSUE TITLE
f-droid.org: breakage

### ISSUE THREAD

**Issue by Zilor** [uBlockOrigin/uAssets#11692]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://f-droid.org/de/packages/org.totschnig.myexpenses/`

### Category

breakage

### Describe the issue

uBlock Origin filters the Advertising antifeature icon (svg) on F-Droid.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
The Anti-Features list with the filtered icon

![f_droid_missing_icon](https://user-images.githubusercontent.com/1292318/153602154-5565252e-9d0e-497f-a6d4-b58609dedcee.png)

The icon without uBlock Origin
![f_droid_with_icon](https://user-images.githubusercontent.com/1292318/153598457-66a3cf5e-19ff-40a4-847a-41ef8218edff.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 91
filterset (summary): 
  network: 79697
  cosmetic: 44269
  scriptlet: 16372
  html: 614
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30772-35, now
    ublock-badware: 3754-0, now
    ublock-privacy: 196-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1719-0, now
    easylist: 63223-590, now
    easyprivacy: 26548-581, now
    urlhaus-1: 7013-0, now
    plowe-0: 3673-2, now
    DEU-0: 5342-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 472 ms
  maxAssetCacheWait: 443 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    f-droid.org: 1
```
</details>

**Comment by uBlock-user** [comment]
`@@||f-droid.org/assets/Ads_$image,1p`

@ryanbr
