### ISSUE TITLE
crunchyscan.fr: detection

### ISSUE THREAD

**Issue by Dugur32** [uBlockOrigin/uAssets#11698]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crunchyscan.fr/`

### Category

detection

### Describe the issue

![Capture d’écran 2022-02-11 205245](https://user-images.githubusercontent.com/98802501/153660192-70666792-5f3d-4560-b02c-b35f5d3d64ad.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 93582
  cosmetic: 50269
  scriptlet: 16459
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 26037-25, 3h
    easylist: 63224-44, 2h.59m
    easyprivacy: 26548-445, 2h.58m
    plowe-0: 3677-815, 7d.2h.37m
    ublock-abuse: 77-1, 2h.57m
    ublock-badware: 3747-78, 2h.56m
    ublock-filters: 30197-295, 2h.54m
    ublock-privacy: 197-2, 2h.53m
    ublock-unbreak: 1708-39, 2h.52m
    urlhaus-1: 6837-0, 2h.51m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 180 ms (selfie)
popupPanel: 
  blocked: 18
```
</details>

**Comment by Dugur32** [comment]
it is written :
it seems that the ad-box is activated.
Please disable Adblock to access the landing page

**Comment by Dugur32** [comment]
it still doesn't work

**Comment by uBlock-user** [comment]
Did you update the list first ?

**Comment by Dugur32** [comment]
HEHE

**Comment by Dugur32** [comment]
its walk
