### ISSUE TITLE
wpdeveloper.com: nuisance

### ISSUE THREAD

**Issue by patricktokeeffe** [uBlockOrigin/uAssets#11699]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wpdeveloper.com/embed-google-sheet-in-wordpress/`

### Category

nuisance

### Describe the issue

Site uses "NotificationX" plugin to show a new pop-up every 3-5 seconds. 

https://wordpress.org/plugins/notificationx/ 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1348834/153671345-351e3c4a-bfe0-47b0-bd6f-fab458577a8f.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 77811
  cosmetic: 41065
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63250-9, 1m
    easyprivacy: 26548-120, 1m
    plowe-0: 3673-805, 1m
    ublock-abuse: 77-0, 1m
    ublock-badware: 3930-74, 1m
    ublock-filters: 30217-137, 1m
    ublock-privacy: 197-2, 1m
    ublock-unbreak: 1709-39, 1m
    urlhaus-1: 7013-0, 1m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 205612 ms
popupPanel: 
  blocked: 6
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||wpdeveloper.com/wp-content/cache/min/1/wp-content/plugins/notificationx/$script,1p
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by patricktokeeffe** [comment]
I had better luck using these instead
```
wpdeveloper.com###notificationx-frontend-root
wpdeveloper.com##.crisp-client
```
