### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by solxr** [uBlockOrigin/uAssets#11700]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/`

### Category

breakage

### Describe the issue

Ublock does not show anything when clicking on an image and blocks scrolling.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

    
![Wn4cMIVEDn](https://user-images.githubusercontent.com/71159832/153681885-3cd611a0-44fc-40c4-afe3-adbc3b8b65b8.png)
(See URL)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79571
  cosmetic: 96502
  scriptlet: 16453
  html: 0
listset (total-discarded, last updated): 
  removed: 
    spa-1: null
    ublock-abuse: null
    urlhaus-1: null
  added: 
    fanboy-annoyance: 64325-3665, 51m
  default: 
    user-filters: 0-0, never
    easylist: 63250-9, 51m
    easyprivacy: 26548-120, 51m
    plowe-0: 3673-805, 51m
    spa-0: 3763-26, 51m
    ublock-badware: 3930-74, 51m
    ublock-filters: 30218-179, 51m
    ublock-privacy: 197-10, 51m
    ublock-unbreak: 1709-42, 51m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 328 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 61
  blockedDetails: 
    twitter.com: 60
    google-analytics.com: 1
```
</details>

**Comment by S0dV** [comment]
> from fanboy-annoyance

@ryanbr

**Comment by solxr** [comment]
Fixed, thank you!
