### ISSUE TITLE
defaultfreeshort.in

### ISSUE THREAD

**Issue by KarmaMod** [uBlockOrigin/uAssets#11708]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://defaultfreeshort.in/T3SO8`

### Describe the issue

Too long waiting time. Request for boosts if possible

Link above will redirect to `https://wondervelocity.com/how-to-download-covid-19-vaccine-certificate/`

### uBlock Origin version

1.41.2

### Browser name and version

Chrome Version 98.0.4758.82 (Official version) (64-bit)

### Settings

Everything is default

**Comment by S0dV** [comment]
![image](https://user-images.githubusercontent.com/99371238/153728316-fba87793-53a0-49da-ae99-6bc01ad0944f.png)

**Comment by mapx-** [comment]
no anti adb on my side

**Comment by S0dV** [comment]
> no anti adb on my side

it's not obvious if you don't try to advance towards getting to the next URL

**Comment by Yuki2718** [comment]
No anti-adb on my end. Addressed popup overlay on the first page, but the second page's can't be hidden to reach next page.
