### ISSUE TITLE
filters-2021 blocking href links

### ISSUE THREAD

**Issue by DeltaWingX** [uBlockOrigin/uAssets#11707]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://elitepvpers.com`

### Describe the issue

Blocks links and images of forum content

```
elitepvpers.com##[href="https://proofcore.io/"]
elitepvpers.com##[href="https://www.aimexcheats.com/"]
```

### uBlock Origin version

Latest

### Browser name and version

Version 98.0.4758.82 (64-Bit)

### Settings

Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0fc41010c07b91230a8e92046f9e535d5ed1b761

**Comment by JobcenterTycoon** [comment]
I actually not removed these 2 filters
