### ISSUE TITLE
[nsfw] xvideos.com: ads

### ISSUE THREAD

**Issue by AriaMoradi** [uBlockOrigin/uAssets#11701]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.xvideos.com/shemale/2`
`https://www.xvideos.com/gay/1`

### Category

ads

### Describe the issue

Shows xvideos' native live cam ads on this page, they are blocked on other pages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8719233/153686556-8ab396a6-be54-47d6-8cbd-963aaf730bd2.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 77741
  cosmetic: 41002
  scriptlet: 16388
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63126-9, 3d.4h.36m
    easyprivacy: 26547-120, 2d.1h.45m
    plowe-0: 3680-807, 9d.10h.30m
    ublock-abuse: 77-0, 3d.4h.33m
    ublock-badware: 3738-71, 3d.4h.30m
    ublock-filters: 30181-150, 3d.4h.31m
    ublock-privacy: 197-2, 3d.4h.34m
    ublock-unbreak: 1704-39, 3d.4h.35m
    urlhaus-1: 7231-0, 1d.8m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1548 ms (selfie)
popupPanel: 
  blocked: 1
```
</details>

**Comment by mapx-** [comment]
> `native live cam ads` 

- it should be self promo and as a result not blocked
- a page where are blocked ?

**Comment by uBlock-user** [comment]
Not just self-promos, cross-site self promo ads and we have blocked them before.

**Comment by mapx-** [comment]
`cams.xvideos.com` are self promo

**Comment by uBlock-user** [comment]
`https://cams.xvideos.com/?model=ella-claire` redirects to `https://www.xvideos-cams.com/?model=ella-claire` in certain regions, those are cross-site promos

**Comment by mapx-** [comment]
It's the same site in the end and cams are not ads.

**Comment by uBlock-user** [comment]
previous discussion - https://github.com/uBlockOrigin/uAssets/issues/9611
