### ISSUE TITLE
tumblr.com: ads

### ISSUE THREAD

**Issue by bogkingdom** [uBlockOrigin/uAssets#11703]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tumblr.com/dashboard`

### Category

ads

### Describe the issue

An ad for NFT buffalo wings (really) is visible at the top of the Tumblr dashboard and is even proving resistant to my attempts to eyedropper-block it.

![Screen Shot 2022-02-11 at 9 29 16 PM](https://user-images.githubusercontent.com/10662223/153698281-fe2d86d1-2951-4e4f-826e-0bcecc580754.jpg)
.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 98
filterset (summary): 
  network: 77622
  cosmetic: 41024
  scriptlet: 16386
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, never
  default: 
    easylist: 63106-9, 3d.22h.5m
    easyprivacy: 26545-119, 3d.22h.4m
    plowe-0: 3680-807, 7d.18h.12m
    ublock-abuse: 77-0, 3d.22h.3m
    ublock-badware: 3738-71, 3d.22h.1m
    ublock-filters: 30181-150, 3d.22h
    ublock-privacy: 194-2, 3d.21h.59m
    ublock-unbreak: 1704-39, 3d.21h.58m
    urlhaus-1: 7013-0, 22h.15m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 33 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 557 ms (selfie)
popupPanel: 
  blocked: 15
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`tumblr.com##a[href^="https://www.bonecoin.com/"]`
