### ISSUE TITLE
easyjet.com: breakage

### ISSUE THREAD

**Issue by AndreaTorti-01** [uBlockOrigin/uAssets#11715]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.easyjet.com/it/`

### Category

breakage

### Describe the issue

The website just breaks and I cannot book a flight, if I disable uBlock it works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 98
filterset (summary): 
  network: 91121
  cosmetic: 102969
  scriptlet: 19187
  html: 622
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 60812-287, 1d.14h.40m
    ublock-annoyances: 4404-5, 1d.14h.40m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30790-27, 1d.14h.39m
    ublock-badware: 3934-3, 1d.14h.39m
    ublock-privacy: 196-0, 1d.14h.39m
    ublock-abuse: 77-0, 1d.14h.39m
    ublock-unbreak: 1720-0, 1d.14h.39m
    easylist: 63253-610, 1d.14h.39m
    easyprivacy: 26548-572, 1d.14h.39m
    urlhaus-1: 7320-0, 14m
    plowe-0: 3673-2, 1d.14h.39m
    ITA-0: 12842-8, 15m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 274 ms (selfie)
  maxAssetCacheWait: 233 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    easyjet.com: 13
    akamaihd.net: 1
    ensighten.com: 2
    google-analytics.com: 1
    googleoptimize.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
In which moment does it break ? Provide exact details on how to reproduce the issue.

**Comment by AndreaTorti-01** [comment]
> In which moment does it break ? Provide exact details on how to reproduce the issue.

It sometimes breaks the entire website (like, the right panel where you choose the flight based on price) when trying to search for a flight, or this part works and then breaks when selecting luggage weight/during payment. It's kinda random

**Comment by krystian3w** [comment]
So EL or Peter Lowe block load cookie bar?

**Comment by krystian3w** [comment]
Test:

`@@||nexus.ensighten.com/easyjet/it/Bootstrap.js$script,domain=www.easyjet.com`

**Comment by uBlock-user** [comment]
> The default uBlock filters are blocking the cookies notice, it's not an additional filter


There's no cookie blocking filter in default lists in uBO.

**Comment by krystian3w** [comment]
Cookies can by loaded from blocked file bootstrap.js.

**Comment by okiehsch** [comment]
I can reproduce the blocked GDPR modal by `Peter Lowe’s` list. The mentioned filter works on my end.
`@@||nexus.ensighten.com/easyjet/*/Bootstrap.js$script,domain=easyjet.com`
