### ISSUE TITLE
euro-times.org: ads

### ISSUE THREAD

**Issue by jackywongboy** [uBlockOrigin/uAssets#11712]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://euro-times.org/n/appledaily/?lpkey=162744117472353679&uclick=twfy7vb4&uclickhash=twfy7vb4-twfy7vb4-vr-vr-bl-16-oj-f2efdc`

### Category

ads

### Describe the issue

ads pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 94891
  cosmetic: 51098
  scriptlet: 16510
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 27893-89, 3d.20h.8m
    easylist: 63133-19, 3d.20h.7m
    easyprivacy: 26547-146, 3d.20h.6m
    plowe-0: 3677-809, 8d.19h.20m
    ublock-abuse: 77-0, 3d.20h.5m
    ublock-badware: 3739-71, 3d.20h.3m
    ublock-filters: 30222-168, 3d.20h.2m
    ublock-privacy: 197-2, 3d.20h.1m
    ublock-unbreak: 1705-40, 3d.20h
    urlhaus-1: 6805-0, 1d.21m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 928 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    outbrain.com: 1
```
</details>

**Comment by krystian3w** [comment]
Blank page - empty body tag.
