### ISSUE TITLE
weather.com anti-adblock message

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#1171]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://weather.com/

### Describe the issue

when navigating to weather.com anti-adblock message pops up.

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/22258847/34583133-69d46a2a-f18e-11e7-9b1a-e5c049767df6.PNG)

### Versions

- Browser/version: Chrome/Firefox
- uBlock Origin version: 1.14.23b12

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

The div name that creates the modal seems to be randomized so a better filter than just a cosmetic filter that I would typically add to my [filterlist](https://github.com/yourduskquibbles/webannoyances) will need to be crafted.

**Comment by okiehsch** [comment]
`weather.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`
works on my end, does that work for you without breaking anything?

**Comment by yourduskquibbles** [comment]
I tested the filter and it seems to remove the message, but while testing when I clicked around on the site and go to a news article, it seems like I can no longer enter in a city/zip code at the top of the screen in the "Show me the weather" black bar.

For example, try opening [this article linked from the main page](https://weather.com/news/news/2018-01-04-winter-storm-grayson-northeast-snow-impacts-new-york-boston) and see if you can recreate the behavior I am experiencing above.

Not sure if it is helpful/useful for future documentation but I also found this [reddit discussion](https://www.reddit.com/r/uBlockOrigin/comments/7nvaro/tired_of_weathercom_asking_you_to_disable_ublock/) relating to this issue.


I definitely agree with your comment after editing that it is more of an annoyance at this point that pops up every 2 or 3 page refreshes than a site breaking anti-adblock implementation.

**Comment by yourduskquibbles** [comment]
After further investigation of your filter on a firefox test profile with only uBlock and default filters installed I'm not sure if the behavior I describe is due to your filter. 

I tested the [article](https://weather.com/news/news/2018-01-04-winter-storm-grayson-northeast-snow-impacts-new-york-boston) I linked above with and without the filter and the page seems to "hang" for about 2 minutes and then unfreeze and the city / zip code bar is able to take user input both with/without the filter. I'm thinking the behavior I described may just be server side coding issue.

**Comment by okiehsch** [comment]
`https://weather.com/news/news/2018-01-04-winter-storm-grayson-northeast-snow-impacts-new-york-boston` is broken even without the filter on my end.

**Comment by okiehsch** [comment]
OK, I will add `weather.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`
to `uBlock-annoyances`.

**Comment by yourduskquibbles** [comment]
Thanks!
