### ISSUE TITLE
tvcom.cz: breakage

### ISSUE THREAD

**Issue by Norarit-Sae** [uBlockOrigin/uAssets#11729]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tvcom.cz/Zapas/Sport-Florbal/Soutez-Superliga-florbalu/Cast-Zakladni-cast/Pohlavi-Muzi/Sezona-2021-2022/201995-FBC-BRZDY.CZ-Ceska-Lipa-TJ-Sokol-Kralovske-Vinohrady.htm`

### Category

breakage

### Describe the issue

tvcom.cz does not show videos with EasyPrivacy turned on. I tested with turning EasyPrivacy on and off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With Easylist
<img width="960" alt="tvcomWithUBlock" src="https://user-images.githubusercontent.com/32593810/153907629-b65c0924-91f4-4152-a14c-76217aa3a295.PNG">

<img width="960" alt="tvcomWithoutUBlock" src="https://user-images.githubusercontent.com/32593810/153907661-a1c0fe6c-6b35-4dd2-a374-343a2047b017.PNG">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79045
  cosmetic: 40905
  scriptlet: 16384
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    THA-0: 981-4, never
    easylist: 62254-462, never
    easyprivacy: 26549-482, never
    plowe-0: 3715-2, never
    ublock-abuse: 77-0, never
    ublock-badware: 3738-0, never
    ublock-filters: 30169-113, never
    ublock-privacy: 194-0, never
    ublock-unbreak: 1704-0, never
    urlhaus-1: 8168-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 940 ms
  maxAssetCacheWait: 7 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    bbelements.com: 3
    cra.cz: 2
    facebook.net: 1
    gemius.pl: 1
    googleadservices.com: 1
    google-analytics.com: 1
    imedia.cz: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||tvcom-static.ssl.cdn.cra.cz/*/videojs.ga.js$script,domain=tvcom.cz`

EP issue @ryanbr
