### ISSUE TITLE
Remove app.yield.app from blocked web-pages

### ISSUE THREAD

**Issue by andreimko** [uBlockOrigin/uAssets#11721]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://app.yield.app/`

### Describe the issue

uBlock Origin blocking any pop-up or link containing *.yield.app , app.yield.app link.

As you can see our website is pretty legitimate, you can track our metrics in Similarweb or just in general use our platform.

Please remove *.yield.app , app.yield.app from your filtering list

### Screenshot(s)

![unknown](https://user-images.githubusercontent.com/92753844/153796318-956d7dd9-4e74-408b-ac94-a1f2bc317116.png)

### uBlock Origin version

1.41.2

### Browser name and version

Firefox 97

### Settings

- No, changes default setup

### Notes

Remove from any filtering *.yield.app , app.yield.app , yield.app from blocking.

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
@andreimko provide the steps to reproduce the issue

**Comment by andreimko** [comment]
@mapx- 

1. Go to https://app.yield.app/
2. Register
3. Login
4. Press on triangle on top right corner, press Support

Support link should be opened in the new tab, but uOrigin will block this call and won't allow opening anything.

**Comment by mapx-** [comment]
Did you update your lists before testing ?

**Comment by andreimko** [comment]
Yes. What list you use, easyList?

**Comment by mapx-** [comment]
The default lists meaning EL too.

The current filter in EL is blocking only third-party stuff
`||yield.app^$popup,third-party`

The popups are not blocked

![image](https://user-images.githubusercontent.com/10303732/153813493-8a461430-fbc8-4b9e-99af-486bd42a3f1a.png)

**Comment by andreimko** [comment]
@mapx- we just have been removed fully from EL, like every mention of yield.app, third-party, *.yield.app, app.yield.app everything was removed. They confirmed on 07/02/2022

Hello,

we apologize for the delayed response and for issues we might have caused.

The problem has been fixed. 

Thanks, 
Elisa 
ABP Support Team 
eyeo GmbH

Lichtstraße 25

50852 Cologne, Germany

Web: [www.eyeo.com · www.adblockplus.org Social](http://www.eyeo.xn--com%20%20www-vua.adblockplus.org%20social/) Media: Facebook / Twitter / Instagram

VAT-ID: DE279292414

District Court Cologne: HRB 735085

Managing Directors: Till Faida, Felix Dahlke & Steffen Kiedel

So how uOrigin still blocks us?

**Comment by mapx-** [comment]
> Did you update your lists before testing ?

click "purge all caches, click "update now"

**Comment by uBlock-user** [comment]
> press Support

Clicking on Support opens `https://support.yield.app/hc/en-us` in a new tab. I see no issue.

**Comment by andreimko** [comment]
Thnks. Also double checked, all fine now.
