### ISSUE TITLE
Getting video ads on videos for CityTv.com

### ISSUE THREAD

**Issue by w4tadrag** [uBlockOrigin/uAssets#1173]
### URL(s) where the issue occurs
`https://www.citytv.com/toronto/?video=5678096161001`

### Describe the issue
I guess recently the `https://www.citytv.com/` updated their website and I am getting video ads on the videos.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/32439406/34597038-3cb29020-f1b2-11e7-9e55-4321887ebd88.png)

### Versions

- Browser/version: Chrome Version 63.0.3239.132
- uBlock Origin version: 1.14.22

### Settings
I checked marked all the boxes on 3rd party filters.

**Comment by TheEnhas** [comment]
I wish there was a guide for what code to look for to block, or really **any** documentation at all for script:inject. Because as it is now only a handful of people really know what they're doing when it comes to defusing anti-adblockers.

**Comment by TheEnhas** [comment]
Is this using a Twitch-like system to deliver ads (it looks that way, going by the logger)? If so then it might be problematic to try and stop them.

**Comment by OpenBSD-Neurotik** [comment]
`
!custom tracker, blocker, analytics
||static.rogersdigitalmedia.com/web_footers/libs/common_footer.s_code.js$script,important

!privacy invaders:
/detectizr.$script,important


! Ads:
/sticky_ad_footer.js
/rdm-ad-
/adchoices.
||doubleclick.net^$important
||adservice.google.com/adsid/integrator.js?$script,important


! Trackers:
||p.typekit.net^
||metrics.brightcove.com^
||utility.rogersmedia.com^
||cdn.optimizely.com^
||adobedtm.com^*/satellitelib-*$script,important
||adobedtm.com^*/s-code-$script,important

!Cosmetics:
www.citytv.com##.widget_ad-widget
www.citytv.com##.adv_leaderboard
www.citytv.com ##.ad_bigbox
www.citytv.com##.rdm-daac-notice-template
www.citytv.com##.text_ads
www.citytv.com##.text_ad
www.citytv.com##.textAd
www.citytv.com##.text-ads
www.citytv.com##.text-ad-links
www.citytv.com##.text-ad
www.citytv.com##.pub_728x90
www.citytv.com##.pub_300x250m
www.citytv.com##.pub_300x250
! maybe this one as well: www.citytv.com##.rdm-brightcove-videojs-iframe

!Allow:
@@||2mdn.net/instream/html5/ima3.js$domain=~citytv.com
@@||imasdk.googleapis.com/js/core/bridge*.html$domain=~citytv.com
`

**Comment by w4tadrag** [comment]
@OpenBSD-Neurotik I copied this to my filter section. It didn't work :(

**Comment by TheEnhas** [comment]
Not only are the ads still unblockable (SSAI), but now if you have an ad-blocker enabled the video will sometimes hang indefinitely after an ad ends to force you to disable it entirely.
