### ISSUE TITLE
[NSFW] hdporn.mobi

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#11730]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://www.hdporn.mobi/video/96895/`

### Describe the issue

The I click on the video, a pop-up appear.

### uBlock Origin version

1.41.2

### Browser name and version

FIrefox 97

### Settings

Default settings

**Comment by Procyon-b** [comment]
Try this filter:
```
supersextube.pro##.ad
```
