### ISSUE TITLE
[nsfw] h-flash.com: popups

### ISSUE THREAD

**Issue by Onii-Chan6969** [uBlockOrigin/uAssets#11733]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://h-flash.com/`

### Category

popups

### Describe the issue

Everytime i click anything it opens tabs for 

aliascagesboxer.com
gkcrbj.com
www.mutigue.com
openoverlycurrentthefile.vip

Ublock already blocks some of the ads it uses but there may be even more i didnt get

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77986
  cosmetic: 41076
  scriptlet: 16413
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 15h.41m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 5-0, never
    easylist: 63281-9, 2d.4h.35m
    easyprivacy: 26549-120, 2d.4h.42m
    plowe-0: 3680-807, 11d.12h.51m
    ublock-abuse: 77-0, 2d.4h.39m
    ublock-badware: 3738-71, 2d.4h.38m
    ublock-filters: 30218-137, 2d.4h.37m
    ublock-privacy: 197-2, 2d.4h.40m
    ublock-unbreak: 1708-39, 2d.4h.36m
    urlhaus-1: 7360-0, 16h.33m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 887 ms (selfie)
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    h-flash.com: 1
    cloudflareinsights.com: 1
    google-analytics.com: 1
    juicyads.com: 2
    venetrigni.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
h-flash.com##+js(aeld, click, setTimeout)
```
