### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Drachenkonig** [uBlockOrigin/uAssets#11731]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.youtube.com/`

### Category

ads

### Describe the issue

It shows ads every time I open my browser and navigate to the site, forcing me to purge and force update my filter lists every time I browse the site. Once the purge cycle/update is done, it no longer shows ads, but if I close my browser, it'll let them through again until I do another purge cycle. Injection ads are still blocked without the force update, but not ad video links.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox Mobile: 68
filterset (summary): 
  network: 140594
  cosmetic: 184809
  scriptlet: 33068
  html: 626
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61818-4813, 1h.58m
    adguard-spyware: 25681-1053, 1h.58m
    adguard-spyware-url: 481-3, 1h.58m
    block-lan: 44-0, 1h.58m
    curben-phishing: 10636-3, 1h.58m
    curben-pup: 404-0, 1h.58m
    adguard-annoyance: 50247-4197, 1h.58m
    adguard-social: 15795-1076, 1h.58m
    fanboy-thirdparty_social: 69-0, 1h.58m
    fanboy-annoyance: 60340-45257, 1h.57m
    fanboy-cookiemonster: 21900-122, 1h.57m
    fanboy-social: 23165-30, 1h.57m
    ublock-annoyances: 4424-4, 1h.57m
    mvps-0: 8730-349, 1h.57m
  default: 
    user-filters: 1-0, never
    ublock-filters: 30913-55, 1h.59m
    ublock-badware: 3944-3, 1h.58m
    ublock-privacy: 199-0, 1h.58m
    ublock-abuse: 77-0, 1h.58m
    ublock-unbreak: 1733-0, 1h.58m
    adguard-mobile: 7229-189, 1h.58m
    easylist: 63376-843, 1h.58m
    easyprivacy: 26556-11514, 1h.58m
    urlhaus-1: 7360-0, 1h.58m
    plowe-0: 3673-2, 1h.57m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10100 ms (selfie)
  maxAssetCacheWait: 2525 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    youtube.com: 2
    doubleclick.net: 2
```
</details>

**Comment by ghajini** [comment]
you are using firefox mobile 68 which is very outdated  browser,update to recent 97 version

secondly you are on non-default settings, reset to default settings & report back

**Comment by uBlock-user** [comment]
Report at https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gototheskinny** [comment]
You can use Kiwi Browser on Android if you want to use extensions. It's much better than Firefox 68. Highly recommended. It works well too.
