### ISSUE TITLE
viefaucet.com: detection

### ISSUE THREAD

**Issue by bardakkardan** [uBlockOrigin/uAssets#11732]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://viefaucet.com/app/wait`
`https://viefaucet.com/app/faucet`

### Category

detection

### Describe the issue

uBlockOrigin gets detected by the mentioned site.
You might be able to solve this.

Thank you.

bardak kardan

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Untitled](https://user-images.githubusercontent.com/99692732/153954051-b7283858-ebde-45bc-a126-5d7dcc3ee582.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78252
  cosmetic: 41119
  scriptlet: 16437
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63376-9, 33m
    easyprivacy: 26556-120, 33m
    plowe-0: 3673-805, 33m
    ublock-abuse: 77-0, 33m
    ublock-badware: 3940-76, 33m
    ublock-filters: 30250-138, 33m
    ublock-privacy: 201-2, 33m
    ublock-unbreak: 1716-39, 33m
    urlhaus-1: 7360-0, 33m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 43 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 991 ms (selfie)
  maxAssetCacheWait: 350 ms
popupPanel: 
  blocked: 310
  no-cosmetic-filtering: true
  blockedDetails: 
    viefaucet.com: 270
    a-ads.com: 5
    adnetasia.com: 1
    arc.io: 1
    bmcdn2.com: 1
    coinzillatag.com: 20
    cryptocoinsad.com: 1
    dogemoonad.space: 1
    franecki.net: 1
    google-analytics.com: 2
    googletagmanager.com: 3
    hotjar.com: 1
    surfe.pro: 3
```
</details>

**Comment by bardakkardan** [comment]
![Untitled](https://user-images.githubusercontent.com/99692732/153955091-9acd708e-a6b0-4545-af28-fbe8f1235e3a.png)

**Comment by Procyon-b** [comment]
Try this filter:
```
||coinzillatag.com^$script,redirect=noopjs,domain=viefaucet.com
```

**Comment by iam-py-test** [comment]
@bardakkardan you have AdGuard installed. Uninstall it and clear your browser cache

**Comment by Procyon-b** [comment]
@iam-py-test I don"t have another adblocker and I can reproduce the detection. You have to register and then click on the "Faucet" item in the left menu.

**Comment by iam-py-test** [comment]
But the OP still does have AG installed, that will cause problems regardless of if this was caused by it

**Comment by uBlock-user** [comment]
@Procyon-b looks like an annoyance ?

**Comment by bardakkardan** [comment]
> Try this filter:
> 
> ```
> ||coinzillatag.com^$script,redirect=noopjs,domain=viefaucet.com
> ```

It works. I do not see that annoying warning anymore.
I didn't uninstall AG though. It is disabled on that page already.

Thank you all.
