### ISSUE TITLE
[nsfw] hentai-for.net: nuisance

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#11740]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hentai-for.net/3301-himitsu-no-kichi-akatsuki.html`

### Category

nuisance

### Describe the issue

After website loading, press play button and wait for video to play. Pressing `F12` to open dev tools stops the video and makes it black; there's a text over the player: `Dont open Developer Tools`.

Proposed filter:

`hqq.tv##+js(set, console.clear, undefined)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 97
filterset (summary): 
  network: 78522
  cosmetic: 42657
  scriptlet: 19168
  html: 623
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4406-4, 34m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30791-28, 34m
    ublock-badware: 3944-3, 34m
    ublock-privacy: 200-0, 34m
    ublock-abuse: 77-0, 34m
    ublock-unbreak: 1727-0, 34m
    easylist: 63587-592, 34m
    easyprivacy: 26560-570, 34m
    urlhaus-1: 7360-0, 34m
    plowe-0: 3673-2, 34m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  uiAccentCustom: true
  uiAccentCustom0: #00ff00
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 281 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    apprefaculty.pro: 1
    bowerywill.com: 2
    buyseoblog.com: 1
    condolencessumcomics.com: 2
    easyads28.mobi: 1
    exoclick.com: 4
    exosrv.com: 4
    haes.tech: 3
    jads.co: 3
    qfjherc.com: 1
    realsrv.com: 3
    rusenov.com: 1
    tagbom.com: 1
    yadro.ru: 2
    yandex.ru: 4
    yomeno.xyz: 1
```
</details>

**Comment by uBlock-user** [comment]
Can you open a PR about this ?
