### ISSUE TITLE
uBlock can't block ad at http://kaztorka.org

### ISSUE THREAD

**Issue by inDigazzZ** [uBlockOrigin/uAssets#1174]
#### Describe the issue
There's iFrame ##body > iframe which doesn't disappear after blocking.

#### One or more specific URLs where the issue occurs
http://kaztorka.org

#### Screenshot in which the issue can be seen
https://imgur.com/a/MLF9G

#### Steps for anyone to reproduce the issue
Open http://kaztorka.org (problem that you have to use Kazakhstan's proxy)
Try to block ad

#### Your settings
Windows 10 Insider Preview 17063:
Opera Develore/51.0.2809.0:
uBlock Origin version/1.14.22:

#### Your filter lists
Default filter lists +
AakList (Anti-Adblock Killer)​​​​​​
Basic tracking list by Disconnect​​​​​
NoCoin Filter List​​​​​
RU AdList: BitBlock

#### Your custom filters (if any)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0466fad197575fbef7d7a8749572fd018c17378e
