### ISSUE TITLE
znanija.com: detection

### ISSUE THREAD

**Issue by krevnekak** [uBlockOrigin/uAssets#11742]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://znanija.com/`

### Category

detection

### Describe the issue

The answer is hiding if uBlock enable

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 95406
  cosmetic: 62622
  scriptlet: 18001
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41406-9, 17h.12m
    easylist: 63281-21, 2d.17h.43m
    easyprivacy: 26549-215, 2d.17h.42m
    plowe-0: 3673-810, 2d.17h.46m
    ublock-abuse: 77-1, 2d.17h.41m
    ublock-badware: 3930-74, 2d.17h.37m
    ublock-filters: 30218-170, 2d.17h.40m
    ublock-privacy: 197-2, 2d.17h.39m
    ublock-unbreak: 1708-39, 2d.17h.38m
    urlhaus-1: 6525-0, 13h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1340 ms (selfie)
  maxAssetCacheWait: 160 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    znanija.com: 3
    amazon-adsystem.com: 1
    btloader.com: 1
    datadome.co: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    pubmatic.com: 2
    sentry-cdn.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
znanija.com#@#+js(abort-on-property-read, localStorage)
```

I don't know if this will cause problems elsewhere.

**Comment by mapx-** [comment]
Do we need to remove all these filters ?

```
brainly.*,eodev.com,znanija.com##+js(aeld, message, data.slice)
brainly.*,eodev.com,znanija.com##+js(nostif, trigger, 0)
eodev.com,znanija.com##+js(aopr, localStorage)
@@*$ghide,domain=brainly.*|eodev.com|znanija.com
```

and add
`##+js(json-prune, tiers.TIER_ANY)` for all these domains ?

**Comment by dimisa-RUAdList** [comment]
No, it seems the rule `##+js(json-prune, tiers.TIER_ANY)` is not a universal solution. Need to check each of these domains separately:
```
https://brainly.com/
https://brainly.pl/
https://brainly.lat/
https://eodev.com/
https://brainly.in/
https://brainly.com.br/
https://brainly.ro/
https://brainly.ph/
https://brainly.lat/
https://nosdevoirs.fr/
https://brainly.co.id/
```

**Comment by uBlock-user** [comment]
> Need to check each of these domains separately:

Why not just add a filter for the znanija.com as per the issue here ?

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/0c56a3efd952e0c5c01565976a28026ba93ac760

**Comment by dimisa-RUAdList** [comment]
Del please:
```
znanija.com##+js(aeld, message, data.slice)
znanija.com##+js(nostif, trigger, 0)
znanija.com##+js(aopr, localStorage)
@@*$ghide,domain=znanija.com
znanija.com##.js-scroll-to-unlock-section.brn-kodiak-answer-redesigned__unlock
```
