### ISSUE TITLE
live.dragaoconnect.net: detection

### ISSUE THREAD

**Issue by mrtonimendes** [uBlockOrigin/uAssets#11746]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://live.dragaoconnect.net/view.php?id=325`

### Category

detection

### Describe the issue

it blocks the use of the website because of ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 97
filterset (summary): 
  network: 77338
  cosmetic: 41062
  scriptlet: 16375
  html: 614
listset (total-discarded, last updated): 
  removed: 
    spa-1: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 30790-27, 3d.10h.36m
    ublock-badware: 3934-3, 3d.10h.35m
    ublock-privacy: 196-0, 3d.10h.34m
    ublock-abuse: 77-0, 3d.10h.33m
    ublock-unbreak: 1720-0, 3d.10h.32m
    easylist: 63262-585, 3d.10h.31m
    easyprivacy: 26548-571, 3d.10h.30m
    urlhaus-1: 6525-0, 1d.1h.7m
    plowe-0: 3680-2, 11d.21h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 301 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    advertica-cdn2.com: 1
    bidvertiser.com: 2
    cdn-server.top: 2
    iclickcdn.com: 1
    pppbr.com: 2
    upgulpinon.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||pppbr.com/slider.php$script,domain=live.dragaoconnect.net
```
