### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by HeriRoqueTello** [uBlockOrigin/uAssets#11747]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

It's been two weeks since I've been seeing ads on the Twitch page in the channels. It is not only 1 ad, it is at least 5 ads in a row, it seems that the extension does not work on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/48292798/154141973-e322344b-301c-41c5-8762-7b90a565e9e6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 80374
  cosmetic: 45615
  scriptlet: 16608
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63300-9, 2d.5h.43m
    easyprivacy: 26556-120, 2d.5h.42m
    plowe-0: 3673-805, 2d.5h.41m
    spa-0: 3763-27, 32m
    spa-1: 4217-161, 2d.5h.46m
    ublock-abuse: 77-0, 2d.5h.39m
    ublock-badware: 3932-74, 2d.5h.37m
    ublock-filters: 30232-195, 2d.5h.36m
    ublock-privacy: 200-2, 2d.5h.35m
    ublock-unbreak: 1715-40, 2d.5h.34m
    urlhaus-1: 6524-0, 31m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 69468 ms (selfie)
  maxAssetCacheWait: 636 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 8
    doubleverify.com: 2
    google-analytics.com: 1
    imrworldwide.com: 1
    scorecardresearch.com: 34
    sentry.io: 2
```
</details>

**Comment by uBlock-user** [comment]
> - [X]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22twitch.tv%22+in%3Atitle
