### ISSUE TITLE
cloudwise-sso.appspot.com false positive

### ISSUE THREAD

**Issue by RandyCW** [uBlockOrigin/uAssets#11758]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

cloudwise-sso.appspot.com

### Describe the issue

Our SSO page gets blocked by Ublock Origin on Chromebooks.
This is a false positive, please unblock this.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/99804049/154253611-02d46031-defa-4ed1-9880-f62d892d1e4a.png)

### uBlock Origin version

uBlock Origin 1.41.2

### Browser name and version

Chrome Versie 98.0.4758.102

### Settings

none, it's all default.

**Comment by uBlock-user** [comment]
There's no filter in uBO blocking this site. Disable all other extensions and try again.

**Comment by mapx-** [comment]
maybe you get some blocking when you are already logged in:

Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)
