### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Ralthazoth** [uBlockOrigin/uAssets#11752]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=BBUuJpK7xlc`

### Category

ads

### Describe the issue

When starting Mozilla Firefox (97.0 64 bit) with session restore on, ads are displayed
The only changes I have made to this browser is configuring a few settings like disabling third party cookies in the settings menu.
This is not independent of youtube being a tab in the previous sessions. It works with any website. It also seems like other extensions, including greasemonkey for at least one site is not properly working before pageload.
All extensions appear to be working properly after refreshing the page manually.
The page is live before refreshing, and so is the youtube video, playing ads.
Apologies if this is a duplicate or known issue.
Thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 97
filterset (summary): 
  network: 102666
  cosmetic: 150052
  scriptlet: 21938
  html: 622
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 25683-831, 1d.18h.6m
    adguard-spyware-url: 481-3, 1d.18h.6m
    block-lan: 44-0, 1d.18h.6m
    adguard-annoyance: 50333-3438, never
    adguard-social: 15796-1846, never
    fanboy-thirdparty_social: 68-0, 1d.18h.6m
    fanboy-annoyance: 63944-48827, 1d.18h.6m
    fanboy-cookiemonster: 21900-13, 1d.18h.6m
    fanboy-social: 23165-30, 1d.18h.6m
    ublock-annoyances: 4411-128, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 30809-38, 2d.17h.32m
    ublock-badware: 3936-3, 2d.17h.31m
    ublock-privacy: 199-0, 2d.17h.30m
    ublock-abuse: 77-0, 2d.17h.29m
    ublock-unbreak: 1726-0, 2d.17h.28m
    easylist: 63300-620, 2d.17h.27m
    easyprivacy: 26556-11385, 2d.17h.26m
    urlhaus-1: 6498-0, 5h.25m
    plowe-0: 3673-2, 2d.17h.24m
filterset (user): [empty]
hostRuleset: 
  added: [array of 65 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 300 ms (selfie)
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    youtube.com: 7
    doubleclick.net: 2
    google.com: 1
    googlevideo.com: 3
    ytimg.com: 1
```
</details>

**Comment by gwarser** [comment]
Is this reproducible? Or maybe happened only once when uBO updated itself?

Did you have this issue in previous uBO version?

**Comment by uBlock-user** [comment]
Test on default lists/settings + all other extensions disabled.
