### ISSUE TITLE
comicsands.com: breakage

### ISSUE THREAD

**Issue by akhepcat** [uBlockOrigin/uAssets#11750]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.comicsands.com/eric-trump-freudian-slip-durham-2656675357.html`

### Category

breakage

### Describe the issue

a/v content does not display, such as embedded twitter videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77425
  cosmetic: 41329
  scriptlet: 16430
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 63587-9, 13h.1m
    easyprivacy: 26560-120, 13h
    plowe-0: 3679-807, 10d.23h.11m
    ublock-abuse: 77-0, 12h.59m
    ublock-badware: 3940-76, 12h.58m
    ublock-filters: 30244-141, 12h.56m
    ublock-privacy: 201-2, 12h.55m
    ublock-unbreak: 1716-39, 12h.54m
    urlhaus-1: 6524-0, 53m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 42 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 276 ms (selfie)
  maxAssetCacheWait: 212 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    adthrive.com: 1
    datadoghq.com: 1
    ex.co: 1
    facebook.net: 1
    googletagmanager.com: 2
    powerad.ai: 1
    rbl.ms: 6
    scorecardresearch.com: 1
    spot.im: 5
    unpkg.com: 1
```
</details>

**Comment by uBlock-user** [comment]
Disable all other extensions and test on default settings/lists.
