### ISSUE TITLE
myanimelist.net: ads

### ISSUE THREAD

**Issue by joel0duf** [uBlockOrigin/uAssets#11751]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myanimelist.net/`

### Category

ads

### Describe the issue

There are ads on the top and sidebars.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/75927731/154173811-457e58c4-93d0-43be-87d6-51ef2a5d0d40.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 94915
  cosmetic: 49495
  scriptlet: 16432
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 26073-43, never
    easylist: 62254-481, never
    easyprivacy: 26549-806, never
    plowe-0: 3715-2, never
    ublock-abuse: 77-0, never
    ublock-badware: 3738-0, never
    ublock-filters: 30169-271, never
    ublock-privacy: 194-0, never
    ublock-unbreak: 1704-0, never
    urlhaus-1: 8168-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1565 ms
  maxAssetCacheWait: 12 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    quantserve.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
myanimelist.net##div[class*="pda-tla-"]
```

**Comment by PIZZV** [comment]
https://forums.lanik.us/viewtopic.php?t=47309

**Comment by PIZZV** [comment]
> [x] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by uBlock-user** [comment]
@ryanbr
