### ISSUE TITLE
EST: Eesti saitidele kohandatud filter (adblock.ee) places cookies in browser.

### ISSUE THREAD

**Issue by ph00lt0** [uBlockOrigin/uAssets#11756]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

adblock.ee

### Describe the issue

Requesting the https://adblock.ee/list.php blocklists puts PHPSESSID and uid cookies in the browser. This seems very unnecessary. Why would we need a session for a list to exist?

### uBlock Origin version

1.41.2

### Browser name and version

Firefox Browser 97.0 (64-bit)

### Settings

Enable the EST: Eesti saitidele kohandatud filter list

**Comment by uBlock-user** [comment]
EasyList's server used to insert their cookie too in the past. uBO doesn't block cookies.

**Comment by uBlock-user** [comment]
@gorhill

**Comment by ph00lt0** [comment]
That's simply not true. This is in fact the only list among the lists, listed in uBO that does so. Creating sessions for users requesting lists is completely unnecessary. In PHP session_start also really doesn't need to be in place in order to accomplish this. I believe this list should not be included into uBO.

**Comment by uBlock-user** [comment]
> That's simply not true.

EasyList used to do this in the past, whether you believe it or not. Contacting the site admin is the only correct course of action and questioning him.

**Comment by uBlock-user** [comment]
> That's simply not true.

EasyList used to do this in the past, whether you believe it or not. Contacting the site admin and questioning him is the only correct course of action.

**Comment by ph00lt0** [comment]
I was referring to you saying "Every website to which a browser connects inserts a cookie" - not about the past of EasyList.
