### ISSUE TITLE
nu.nl: breakage

### ISSUE THREAD

**Issue by rwssmacos** [uBlockOrigin/uAssets#11759]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nu.nl/`

### Category

breakage, also detects uBlock.

### Describe the issue

Shows only a white webpage (content) - when uBlock is turned off the webpage shows all content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Firefox: 97
filterset (summary): 
  network: 150962
  cosmetic: 189632
  scriptlet: 33061
  html: 626
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61934-4846, 6m
    adguard-mobile: 7232-153, 6m
    adguard-spyware: 25691-1124, 6m
    adguard-spyware-url: 488-3, 6m
    block-lan: 44-0, 6m
    adguard-annoyance: 50351-4200, 6m
    adguard-social: 15805-1078, 6m
    fanboy-thirdparty_social: 69-0, 6m
    fanboy-annoyance: 60311-45225, 6m
    fanboy-cookiemonster: 21867-122, 6m
    fanboy-social: 23166-30, 6m
    ublock-annoyances: 4413-8, 6m
    dpollock-0: 10345-529, 6m
    mvps-0: 8730-1517, 6m
    DEU-0: 5342-10, 6m
    curben-phishing: 10629-3, 6m
    curben-pup: 411-0, 6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30773-112, 6m
    ublock-badware: 3969-3, 6m
    ublock-privacy: 201-0, 6m
    ublock-abuse: 77-0, 6m
    ublock-unbreak: 1727-0, 6m
    easylist: 63637-1010, 6m
    easyprivacy: 26560-11564, 6m
    urlhaus-1: 6498-0, 6m
    plowe-0: 3675-2, 6m
    NLD-0: 2089-29, 6m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 6403 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2338 ms (selfie)
  maxAssetCacheWait: 965 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    privacy-mgmt.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Even with all stock lists enabled like you (it's a bad idea) I can still see the page, and no detection.
You have 6403 rules. Check them.

**Comment by mapx-** [comment]
Strange issue: 
First I got a blurred page then (on the second reload) a blank page (FF / chrome) using the default settings.
I deleted cookies / cache and the page loaded normally.

**Comment by okiehsch** [comment]
With a default setup the site works fine on my end.
You use a highly customised setup we only issues with a default setup.

**Comment by Procyon-b** [comment]
"Blurred" could be caused by the cookie dialog (redirect to `dpgmedia.nl`). I've retested on another computer. No pb with FF and chrome

**Comment by Procyon-b** [comment]
> Don't know how to get a "blurred" page.

I get this usually from sites that redirect to another domain to set their cookies (GDPR dialog). They usually set a copy of the landing page as a backgound to the dialog and add a blur effect (and sometimes a zoom out). I'm using IDCAC and the dialogs are hidden but redirect and the blur are still visible while waiting for the final redirect.
I don't know if this is part of rwssmacos problem, but mapx- saw a blur and that's the only blur I can see.

**Comment by JohnyP36** [comment]
As maintainer of the Dutch filterlist I also could not reproduce this issue. 
And since you are using this list (enabled by default) I think the problem lays somewhere else.
