### ISSUE TITLE
la7.it: breakage

### ISSUE THREAD

**Issue by kartola** [uBlockOrigin/uAssets#11764]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.la7.it/dirette-tv`

### Category

breakage

### Describe the issue

video doesn't start anymore

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 83029
  cosmetic: 48518
  scriptlet: 16397
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 12822-0, 2h.45m
    easylist: 63636-13, 8h.17m
    easyprivacy: 26560-122, 8h.16m
    plowe-0: 3673-806, 4d.7h.11m
    ublock-abuse: 77-0, 8h.15m
    ublock-badware: 3965-76, 8h.14m
    ublock-filters: 30192-145, 8h.20m
    ublock-privacy: 202-2, 8h.21m
    ublock-unbreak: 1716-39, 8h.18m
    urlhaus-1: 6457-0, 2h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 553 ms (selfie)
  maxAssetCacheWait: 377 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adsafeprotected.com: 1
    amazon-adsystem.com: 1
    google-analytics.com: 1
    iltrovatore.it: 1
    imrworldwide.com: 2
    permutive.app: 1
    rcsmetrics.it: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||static.adsafeprotected.com/iasPET.1.js$script,domain=la7.it
@@||secure-it.imrworldwide.com/v60.js$script,domain=la7.it
```

@khrin @ryanbr
