### ISSUE TITLE
level.travel: breakage

### ISSUE THREAD

**Issue by jt3k** [uBlockOrigin/uAssets#11763]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://level.travel/search/Moscow-RU-to-Any-AE-departure-02.03.2022-for-7-nights-2-adults-0-kids-1..5-stars`

### Category

breakage

### Describe the issue

I can't get a list of resorts. it's just empty. 
when i disable uBlock the site works correctly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1261240/154328086-fbb5c675-9eb6-4985-b38d-bef74cbdfd09.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 95484
  cosmetic: 62887
  scriptlet: 17987
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41416-9, 3h.26m
    easylist: 63637-21, 3h.23m
    easyprivacy: 26560-215, 3h.22m
    plowe-0: 3675-810, 3h.21m
    ublock-abuse: 77-1, 3h.19m
    ublock-badware: 3965-76, 3h.17m
    ublock-filters: 30192-171, 3h.16m
    ublock-privacy: 201-2, 3h.15m
    ublock-unbreak: 1716-39, 3h.14m
    urlhaus-1: 6457-0, 3h.13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2554 ms
  maxAssetCacheWait: 279 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    level.travel: 1
    doubleclick.net: 1
    facebook.net: 1
    flocktory.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    newrelic.com: 1
    yandex.ru: 1
```
</details>

**Comment by okiehsch** [comment]
Hm, weird 
`@@||cdn.level.travel/tracker/tracker.js$script,1p`
works on my end but I have to reload twice before it does,

**Comment by mapx-** [comment]
testing in chrome I need

```
@@||cdn.level.travel/tracker/tracker.js$script,1p
@@||googletagmanager.com/gtm.js$script,domain=level.travel
```

**Comment by mapx-** [comment]
@ryanbr EP issue

**Comment by mapx-** [comment]
tested in FF, same as for chrome I need both filters

**Comment by Procyon-b** [comment]
I've played a bit with the site and I've noticed that after removing all the filters for it, it still worked. But it fails again when site's data are deleted.
Apparently nothing breaks as long as there is a LocalStorage key `ccx-uuid` . Empty is enough. No need for filters when this key exists. The key is set by `cdn.level.travel/tracker/tracker.`

**Comment by okiehsch** [comment]
Same on my end, I only need to allow `cdn.level.travel/tracker/tracker`.

**Comment by uBlock-user** [comment]
Cached resources will keep the site unbroken.

**Comment by okiehsch** [comment]
Yes, the "same" in my reply meant I see exactly what you described in your comment.

**Comment by Procyon-b** [comment]
@uBlock-user  No cached resources here. I opened the site, refreshed it a few times. Always broken. I add the LocalStorage key and a reload displays a fully loaded site.

**Comment by uBlock-user** [comment]
Key must related to resource initialisation then.

**Comment by uBlock-user** [comment]
> but I have to reload twice before it does,

`@@||cdn.level.travel/tracker/tracker.js$script,1p` + a cache free reload of the page works in one attempt.
