### ISSUE TITLE
www2.movies7.to: popups

### ISSUE THREAD

**Issue by sadaqs** [uBlockOrigin/uAssets#11765]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www2.movies7.to/series/south-park-mjoyz/10-9`

### Category

popups

### Describe the issue

The website opens a random extra tab sometimes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77348
  cosmetic: 41088
  scriptlet: 16430
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63300-9, 3d.1h.37m
    easyprivacy: 26556-120, 3d.17h.41m
    plowe-0: 3673-805, 3d.1h.39m
    ublock-abuse: 77-0, 2d.13h.34m
    ublock-badware: 3940-74, 2d.13h.33m
    ublock-filters: 30250-138, 2d.13h.32m
    ublock-privacy: 197-2, 2d.13h.31m
    ublock-unbreak: 1715-39, 2d.9h.30m
    urlhaus-1: 6498-0, 15h.45m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1247 ms (selfie)
  maxAssetCacheWait: 240 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    addthis.com: 1
    amung.us: 1
    denetsuk.com: 1
    disqus.com: 2
    google-analytics.com: 4
    jomtingi.net: 5
    mcloud.to: 14
    rndskittytor.com: 1
    ugroocuw.net: 2
    zap.buzz: 4
```
</details>

**Comment by Rokeugon** [comment]
Site is again opening new browser windows this time at random and it cycles through many sites trying to spread NSFW or malicious stuff from twitter to facebook, also seen something related to whatsapp and telegram. 

How to reproduce = When you RMB anywhere on the site and then click back onto the site to get rid of popout menu it will force display a new small window.

**Comment by mapx-** [comment]
@Rokeugon does this work ?

`movies7.to##+js(nowoif)`

**Comment by Rokeugon** [comment]
> @Rokeugon does this work ?
> 
> `movies7.to##+js(nowoif)`

Can validate. no longer getting forced new window popups.
