### ISSUE TITLE
flashx.tv [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1176]
URL(s) where the issue occurs

`https://www.flashx.tv/957520df9cd652a6f8b5ade7ee756462.jsp`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
Your link leads to a "file not found" site with a fake video player.
![fake](https://user-images.githubusercontent.com/16838044/34628122-8c456f34-f263-11e7-9e7c-cc8ebd61da17.JPG)

I would need a live link to really test the site.

**Comment by xDarkARG** [comment]
@okiehsch
`https://flashx.tv/aqzt69ue6tdd.html`

**Comment by okiehsch** [comment]
Thx.

**Comment by KiLL4FuNK** [comment]
@mapx-

Anti-Adblock `https://www.flashx.sx/412cf00c43b86ad23f1ebeada91a7ef2.jsp`

`

**Comment by lain566** [comment]
There are ads

`http://www.flashx.tv/cqykhx90eu3h.html`
`https://www.flashx.pw/`

![f9398c8f-ca3e-4a8e-b13f-cd7b1cd7bb85](https://user-images.githubusercontent.com/27441315/53738464-8e4a7300-3e8f-11e9-8440-c80590a145d1.png)

![92219ae8-15b5-4384-a9b2-7b1fc8785fba](https://user-images.githubusercontent.com/27441315/53738508-aae6ab00-3e8f-11e9-8f8c-80e0cad71289.png)

**Comment by ghajini** [comment]
`https://www.flashx.tv/b9jmey1c7fcv.html`

download blocked 
can i add
`||fastcontentdelivery.com^$badfilter`

alongwith
`flashx.net##+js(acis, Math, XMLHttpRequest)`

**Comment by mapx-** [comment]
go ahead if it's working for you
