### ISSUE TITLE
faucetpot.me: detection

### ISSUE THREAD

**Issue by bardakkardan** [uBlockOrigin/uAssets#11768]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://faucetpot.me/`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://user-images.githubusercontent.com/99692732/154412981-c9d0325e-5b9b-4548-b5da-1e020e04f26c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77393
  cosmetic: 41119
  scriptlet: 16437
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-2, never
    easylist: 63376-9, 2d.8h.26m
    easyprivacy: 26556-120, 2d.8h.26m
    plowe-0: 3673-805, 2d.8h.26m
    ublock-abuse: 77-0, 2d.8h.26m
    ublock-badware: 3940-76, 2d.8h.26m
    ublock-filters: 30250-138, 2d.8h.26m
    ublock-privacy: 201-2, 2d.8h.26m
    ublock-unbreak: 1716-39, 2d.8h.26m
    urlhaus-1: 6498-0, 23h.8m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 48 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 968 ms (selfie)
  maxAssetCacheWait: 242 ms
popupPanel: 
  blocked: 14
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  blockedDetails: 
    1bit.ly: 1
    a-ads.com: 2
    adhitzads.com: 2
    adoto.net: 1
    arc.io: 1
    bitcoadz.io: 1
    cryptocoinsad.com: 1
    googletagmanager.com: 1
    trustpilot.com: 1
    unitraffic.ru: 1
    webminepool.com: 1
    webtrafic.ru: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||googletagmanager.com^$script,redirect=noopjs,domain=faucetpot.me
```

**Comment by bardakkardan** [comment]
It works thank you very much.
