### ISSUE TITLE
ikea.com: breakage

### ISSUE THREAD

**Issue by A-wolf** [uBlockOrigin/uAssets#11777]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ikea.com/se/sv/customer-service/contact-us/`

### Category

breakage

### Describe the issue

Then enabled does this remove clickable chat buttons to contact support. I apologize for the Swedish in the images but i provided examples with screenshots of what happens below 

With plugin on
![image](https://user-images.githubusercontent.com/33517791/154508467-9ee261ba-0b20-4ab6-afc1-4675ae0995cc.png)
Without plugin off 
![image](https://user-images.githubusercontent.com/33517791/154507656-0e084433-7659-4dc2-a486-1456d098850a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.1b0
Chromium: 98
filterset (summary): 
  network: 77437
  cosmetic: 41336
  scriptlet: 16404
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63670-9, 17h.14m
    easyprivacy: 26561-120, 17h.13m
    plowe-0: 3673-805, 4d.21h.29m
    ublock-abuse: 77-0, 17h.12m
    ublock-badware: 3965-76, 17h.11m
    ublock-filters: 30199-139, 17h.10m
    ublock-privacy: 202-2, 17h.9m
    ublock-unbreak: 1716-39, 17h.8m
    urlhaus-1: 6457-0, 9h.7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2258 ms (selfie)
  maxAssetCacheWait: 1130 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    ikea.com: 1
    adform.net: 1
    byside.com: 2
    facebook.net: 1
    go-mpulse.net: 1
    googletagmanager.com: 1
    hotjar.com: 1
    optimizely.com: 1
    techlab-cdn.com: 5
```
</details>

**Comment by mapx-** [comment]
add 
`@@||byce1.byside.com/agent/byside_webcare_ce1.js$script,domain=ikea.com`

EP issue @ryanbr
