### ISSUE TITLE
github.com: ads

### ISSUE THREAD

**Issue by JohnDohe** [uBlockOrigin/uAssets#11776]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://github.com/`

### Category

ads

### Describe the issue

![Screen Shot 2022-02-17 at 9 03 26 AM](https://user-images.githubusercontent.com/6155106/154498672-2b09e425-4759-4191-8590-1f5a5a67e91c.png)

I am unable to block the above popup-banner that appears across the entire bottom of the page.

I can use element zapper to get rid of it.

But element picker cannot do anything to block or remove it.

Thank you!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screen Shot 2022-02-17 at 9 03 26 AM](https://user-images.githubusercontent.com/6155106/154499126-1ffaf5dc-f788-4967-b7bc-0899158e4121.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Firefox: 97
filterset (summary): 
  network: 77474
  cosmetic: 41388
  scriptlet: 16366
  html: 617
listset (total-discarded, last updated): 
  default: 
    user-filters: 70-24, never
    ublock-filters: 30779-27, 5h.37m
    ublock-badware: 3969-3, 5h.36m
    ublock-privacy: 201-0, 5h.35m
    ublock-abuse: 77-0, 5h.34m
    ublock-unbreak: 1727-0, 5h.33m
    easylist: 63694-589, 5h.32m
    easyprivacy: 26563-571, 5h.31m
    urlhaus-1: 6457-0, 13h.38m
    plowe-0: 3679-2, 7d.3h.19m
filterset (user): [array of 70 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6002 ms (selfie)
  maxAssetCacheWait: 4804 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    github.com: 1
```
</details>

**Comment by uBlock-user** [comment]
GitHub doesn't have ads. Either you have an extension inserting that ad or your infected with malware. Something for you to investigate.
