### ISSUE TITLE
eurosport.fr: breakage

### ISSUE THREAD

**Issue by pokemaster974** [uBlockOrigin/uAssets#11773]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.eurosport.fr/formule-1/romain-grosjean-s-affiche-en-superman-sur-twitter-et-instagram-apres-son-terrible-accident_sto8014927/story.shtml`

### Category

breakage

### Describe the issue

I can only see social frames if I desactivate aesthetic filtering on uBlock

I have this filters on my filters to block the ad :
> www.eurosport.fr##.items-center.clear-both.flex-col.flex.text-center.AdContainer.AdPlacementBannerSponsorship.AdContainer--standalone
> www.eurosport.fr##div.items-center.clear-both.flex-col.flex.text-center.AdContainer.AdPlacementMPU.AdContainer--standalone:nth-of-type(2)
> www.eurosport.fr##div.items-center.clear-both.flex-col.flex.text-center.AdContainer.AdPlacementMPU.AdContainer--standalone:nth-of-type(4)

If I desactivate the aesthetic filtering it will show me the Twitter frame but also the ad frames, even with my personal filters.
If I activate the aesthetic filtering, I won't see nor the Twitter frame, nor the ad frames.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Firefox: 97
filterset (summary): 
  network: 164782
  cosmetic: 210533
  scriptlet: 33218
  html: 623
listset (total-discarded, last updated): 
  added: 
    https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 6498-0, 14h.51m
    https://easylist-downloads.adblockplus.org/fanboy-social.txt: 23221-30, 308d.1h.13m
    https://easylist-downloads.adblockplus.org/liste_fr.txt: 23407-63, 14h.47m
    https://filters.adtidy.org/extension/ublock/filters/11.txt: 7229-158, 2d.2h.2m
    https://filters.adtidy.org/extension/ublock/filters/14.txt: 50271-4313, 2d.2h.4m
    https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt: 61839-5253, 2d.2h.6m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 25683-1174, 2d.2h.23m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 2d.1h.36m
    https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/filterlist/facebook/FacebookZuckestionKiller.txt: 998-0, 2d.1h.38m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt: 77-0, 2d.2h.25m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 5d.2h.2m
    https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 1d.2h.40m
    https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 21936-125, 1d.11h.24m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 5d.2h
    https://www.fanboy.co.nz/r/fanboy-ultimate.txt: 152110-152068, 1d.11h.22m
    https://www.i-dont-care-about-cookies.eu/abp/: 24361-8697, 14h.53m
    ublock-annoyances: 4404-8, 2d.1h.54m
    adguard-generic: 61839-61839, 2d.2h.10m
    adguard-mobile: 7229-7229, 2d.2h.8m
    adguard-spyware: 25683-25683, 2d.1h.58m
    [8 lists not shown]: [too many]
  default: 
    user-filters: 129-0, never
    ublock-filters: 30822-254, 2d.2h.21m
    ublock-badware: 3944-7, 2d.2h.19m
    ublock-privacy: 199-0, 2d.2h.17m
    ublock-abuse: 77-77, 2d.2h.14m
    ublock-unbreak: 1727-1, 2d.2h.12m
    easylist: 63587-1115, 2d.2h
    easyprivacy: 26558-11891, 2d.1h.56m
    plowe-0: 3679-1803, 10d.10h.47m
    FRA-0: 26073-22715, 2d.12h.30m
    urlhaus-1: 6457-6085, 14h.49m
filterset (user): [array of 129 redacted]
trustedset: 
  added: [array of 85 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 64 redacted]
hostRuleset: 
  added: [array of 105 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  selfieAfter: 11
supportStats: 
  allReadyAfter: 1634 ms (selfie)
  maxAssetCacheWait: 1224 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    beop.io: 2
    doubleclick.net: 1
    eurosport.com: 1
    go-mpulse.net: 2
    hubvisor.io: 1
    newrelic.com: 1
    twitter.com: 6
```
</details>

**Comment by mapx-** [comment]
Test using **ONLY** the default settings / lists

**Comment by pokemaster974** [comment]
Sorry, it was an issue with Fanboy’s Annoyance & Fanboy’s Social  lists.

I close the issue.
Thanks !

**Comment by ryanbr** [comment]
Looks fine here, checked video playback also

**Comment by pokemaster974** [comment]
> Looks fine here, checked video playback also

Hi, thanks for your reply.

I screen the same page twice. Only difference is activating (With.png) and desactivating (Without) of Fanboy’s Annoyance & Fanboy’s Social lists. No other changes. Just refresh after checking/unchecking the 2 lists.

![With](https://user-images.githubusercontent.com/28442699/154491832-aadbd065-0acf-4ab7-ade6-d0c88e32b392.png)

![Without](https://user-images.githubusercontent.com/28442699/154491537-729e2d92-aca1-4ee1-983a-d3442721531e.png)

**Comment by mapx-** [comment]
add & test

`eurosport.fr#@#.twitter-tweet`
