### ISSUE TITLE
demo2.drivetrain.ai: breakage

### ISSUE THREAD

**Issue by dt-pulkit** [uBlockOrigin/uAssets#11770]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://demo2.drivetrain.ai/explore/metrics.Temp_Cohort__Jan__22_?f=&planId=6`

### Category

breakage

### Describe the issue

The filter `/metrics/metrics$domain=~spatineo.com` is incorrectly blocking our webpage.
Please find attached the screenshot that shows the details of the same

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/91958790/154417264-bd472f98-4819-4956-bb81-9af62c17951b.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77449
  cosmetic: 41331
  scriptlet: 16397
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63634-9, 20h.2m
    easyprivacy: 26560-120, 20h.1m
    plowe-0: 3675-805, 20h
    ublock-abuse: 77-0, 19h.58m
    ublock-badware: 3965-76, 19h.55m
    ublock-filters: 30192-138, 19h.54m
    ublock-privacy: 202-2, 19h.52m
    ublock-unbreak: 1716-39, 19h.51m
    urlhaus-1: 6498-0, 19h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1736 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    drivetrain.ai: 4
    launchdarkly.com: 4
    mixpanel.com: 17
    sentry.io: 2
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
