### ISSUE TITLE
thevideo.ch [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1177]
URL(s) where the issue occurs

`https://thevideo.ch/ci37uf1x73q6`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
`https://thevideo.website/ci37uf1x73q6`   changes domains to @mapx-
