### ISSUE TITLE
flightradar24.com: breakage

### ISSUE THREAD

**Issue by Chouffy** [uBlockOrigin/uAssets#11787]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.flightradar24.com/airport/jfk`

### Category

breakage

### Describe the issue

**Steps to reproduce:**
1. Load `https://www.flightradar24.com/airport/jfk`
2. Check the sidebar to press of of the side bar button, like Arrivals or Departures

**Actual situation**
The sidebar is shifted to the bottom and has an empty space on top.
This makes pressing side bar buttons impossible, except if zommed out a lot.
This empty space is probably due to the top banner, which isn't showed when uBlock is activated.

**Wished situation**
The sidebar is at the top, and buttons are accessible.
This is the case when the top banner has been closed, even if uBlock is re-activated.

### Screenshot(s)

<details>

<summary>Step 1 - Load the side with uBlock: Side bar is shifted to the bottom, resulting in inaccessible buttons</summary>

![image](https://user-images.githubusercontent.com/9288966/154648822-ae8d9b2f-d389-4550-a018-118878a8afba.png)

<summary>Step 2 - Reload with uBlock disabled = Consent prompt + top banner</summary>

![image](https://user-images.githubusercontent.com/9288966/154648338-3c483d9c-c343-4127-a551-20984ab4eadb.png)

<summary>Step 3 - Consent prompt answered, but still top banner -> sidebar bottom blocked</summary>

![image](https://user-images.githubusercontent.com/9288966/154648555-7079f850-9141-4562-8043-d34637af16d9.png)

<summary>Step 4 - Top banner closed -> sidebar bottom available 😊</summary>

![image](https://user-images.githubusercontent.com/9288966/154648636-ead1553d-6e5e-4bd8-9dfc-c40f99e5e4f2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Firefox: 97
filterset (summary): 
  network: 128413
  cosmetic: 138081
  scriptlet: 30402
  html: 618
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 61990-5130, 9m
    adguard-spyware: 25696-828, 9m
    adguard-annoyance: 50396-1438, 9m
    adguard-social: 15826-17, 9m
    FRA-0: 26069-540, 9m
    adguard-spyware-url: 489-3, 9m
  default: 
    user-filters: 30-0, never
    ublock-filters: 30806-32, 9m
    ublock-badware: 3989-3, 9m
    ublock-privacy: 202-0, 9m
    ublock-abuse: 77-0, 9m
    ublock-unbreak: 1726-0, 9m
    easylist: 63745-679, 9m
    easyprivacy: 26576-11387, 9m
    plowe-0: 3677-2, 9m
    urlhaus-1: 6510-0, 9m
filterset (user): [array of 30 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 557 ms (selfie)
  maxAssetCacheWait: 576 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
I've tested with the same lists and I don't have a problem. You have 30 user filters; check if it's not caused by one of them.
