### ISSUE TITLE
coinlink.co

### ISSUE THREAD

**Issue by onmyouji** [uBlockOrigin/uAssets#1178]
### URL(s) where the issue occurs

`http://coinlink.co/CRAF1WJQ`

### Describe the issue

Anti adblock message.

### Screenshot(s)

![coinlink co_craf1wjq 1](https://user-images.githubusercontent.com/8424198/34637453-d96fd20a-f2e9-11e7-96f0-9f576a705e2d.png)

### Versions

- Browser/version: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- uBlock Origin version: v1.14.22

### Settings

Default settings. 
I also run uBlock Origin Extra + uMatrix + Nano Defender + Privacy Badger

### Screenshot of Developer Tools

![clipboard 3](https://user-images.githubusercontent.com/8424198/34637534-597af6e0-f2eb-11e7-8cdd-c79514a8a187.png)

**Comment by KiLL4FuNK** [comment]
Bad Request
