### ISSUE TITLE
yabancidizi.pro ads

### ISSUE THREAD

**Issue by tmobilyalari** [uBlockOrigin/uAssets#11781]
### Prerequisites

- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yabancidizi.pro/dizi/peaky-blinders-izle-1/sezon-1/bolum-1`

### Describe the issue

More ads is already here not blocked this but i m select to ads with tool

### Screenshot(s)

![image](https://user-images.githubusercontent.com/96266724/154569871-43780ab1-b1f9-4d9a-bab5-98d46a2fe05b.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79223
  cosmetic: 47640
  scriptlet: 16757
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 14-6, never
    TUR-0: 8560-78, 1m
    easylist: 63634-25, 1d.11h.5m
    easyprivacy: 26556-125, 3d.3h.37m
    plowe-0: 3679-808, 8d.5h.39m
    ublock-abuse: 77-0, 3d.3h.36m
    ublock-badware: 3940-76, 3d.3h.35m
    ublock-filters: 30251-152, 3d.3h.40m
    ublock-privacy: 200-2, 3d.3h.39m
    ublock-unbreak: 1716-39, 3d.3h.38m
    urlhaus-1: 6457-0, 10h.11m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 46 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 186 ms (selfie)
  maxAssetCacheWait: 143 ms
```
</details>

**Comment by Procyon-b** [comment]
I don't see the ads with the TUR regional list enabled (like you).
Verify that you haven't disable cosmetic filtering. In the "_Filter lists_" tab, "_Parse and enforce cosmetic filters_" must be enabled. And in ublock's popup window the cosmetic filtering icon should not be crossed. (see: https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering)
