### ISSUE TITLE
allhorror.com: detection

### ISSUE THREAD

**Issue by git-101-collab** [uBlockOrigin/uAssets#11785]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.allhorror.com/movies/dracula`

### Category

detection

### Describe the issue

Annoying anti-adblock banners, reloading the page a few times makes them go away for a while, but then they come back again.

Blocking `https://www.allhorror.com/public/frontend/js/waldo-ad-custom.js?var=1.06` and/or `https://www.allhorror.com/public/frontend/images/waldo-ads-placeholders/*.jpg` solves the issue for me.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83709703/154590481-483a42e6-09f1-4862-9a37-c5993305094d.png)
![image](https://user-images.githubusercontent.com/83709703/154580292-f3c4225a-0052-4e11-9623-2d5a12daaf7d.png)
![image](https://user-images.githubusercontent.com/83709703/154588079-f64a81d1-608a-40b8-87ea-4af1c958b73e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.5b2
Firefox: 97
filterset (summary): 
  network: 144284
  cosmetic: 137213
  scriptlet: 21950
  html: 626
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 33038-798, now
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1746-0, now
    adguard-spyware: 25696-845, now
    adguard-spyware-url: 489-75, now
    block-lan: 44-0, now
    curben-phishing: 10671-2, now
    curben-pup: 402-0, now
    adguard-annoyance: 50395-3446, now
    fanboy-annoyance: 64051-4000, now
    ublock-annoyances: 4415-4, now
  default: 
    user-filters: 40-0, never
    ublock-filters: 30802-189, now
    ublock-badware: 3989-3, now
    ublock-privacy: 202-2, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1727-0, now
    easylist: 63745-3422, now
    easyprivacy: 26574-11393, now
    urlhaus-1: 6457-0, now
    plowe-0: 3675-2, now
filterset (user): [array of 39 redacted]
switchRuleset: 
  added: [array of 59 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 58 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 800 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    aweber.com: 3
    clarity.ms: 1
    google-analytics.com: 1
    onesignal.com: 2
    thisiswaldo.com: 2
    youtube.com: 1
```
</details>

**Comment by Procyon-b** [comment]
This filter works:
```
allhorror.com##.ad-placeholder-wrapper
```
