### ISSUE TITLE
[Question] Adding archived (.txt file) filters list or filters lists to uBO.

### ISSUE THREAD

**Issue by Piter432** [uBlockOrigin/uAssets#118]
How I can add to the uBlock Origin archived filters list or filters lists? Archived I mean saved in .txt file when discovered that the filters list will not be accessible forever or for while.

I guess that “file://folder_path/my-archived-filters-list.txt” (or “file:///[...]”) should work, but I'm not sure that is uBO support adding custom filters lists like this.

**Comment by IDKwhattoputhere** [comment]
This isn't a filter-related issue but a question about the way uBO handles local filter list files. That said, have you tried adding the list using `file:///`? It works here with Firefox.
![](https://cloud.githubusercontent.com/assets/16030872/18036866/3806c404-6d76-11e6-8085-734509b47d4d.png)

**Comment by gorhill** [comment]
If you have a custom install of uBO -- not from the Chrome store or Opera store -- you can modify `manifest.json`: add ` `"file:///*",` in the `"permissions"` array, restart the extension. You will be able to use `file:///[...]` URL for custom filter lists. Be sure the option _"Allow access to file URLs"_ is check for uBO in the _Extensions_ page.

**Comment by Piter432** [comment]
I've asked here, because I wasn't sure whether that this topic could be “closed, marked as _invalid_” and limited to uBO's GitHub repository collaborators at uBO's GitHub repository by @gorhill. Especially that @gorhill **sharpened** some rules about making new topic in Issues section of uBO's GH repository (see CONTRIBUTING.md file there).

However, I tried both in Chrome and Firefox (both installed from their store) and the .txt file list on local drive doesn't appear in the “Custom” group/section. Interesting thing is that I also tried what I do with background in downloaded files list page of Chrono Download Manager (I'm using image from local drive as background image in the downloaded files list page of Chrono DM) – this method also doesn't work.

**Comment by Piter432** [comment]
> If you have a custom install of uBO -- not from the Chrome store or Opera store -- you can modify manifest.json: add "file:///*",in the"permissions"array, restart the extension. You will be able to usefile:///[...]` URL for custom filter lists. Be sure the option "Allow access to file URLs" is check for uBO in the Extensions page.

I could do that, but... I'm lazy man, he, he :P

**Comment by gorhill** [comment]
> I could do that, but... I'm lazy man, he, he :P

I don't plan to add `file:///` for now. This would trigger a new permission warning for Chrome/Opera and worried people all over the place about the new permission.

**Comment by Piter432** [comment]
> I don't plan to add file:/// for now. This would trigger a new permission warning for Chrome/Opera and worried people all over the place about the new permission.

K, k. I understood :wink: I don't force you to add this now, just asking about this, because why not :stuck_out_tongue_winking_eye:

**Comment by Piter432** [comment]
Okay. Because the feature is already added (and I already solved my problem with adding the filters list from local drive), I'm closing the topic. You can also lock & limit this topic to collaborators if you want to do so, @gorhill :slightly_smiling_face:
