### ISSUE TITLE
whattomine.com: breakage

### ISSUE THREAD

**Issue by ctp9** [uBlockOrigin/uAssets#11805]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://whattomine.com/`
`https://whattomine.com/coins`
`https://whattomine.com/asic`

### Describe the issue

The main tables that you see on each of the listed pages tend to break and lose half of their rows when uBlock is enabled. I am not sure which filter list(s) are causing the breakage or how to find out.

Instead of 3 rows of blue buttons - only 2 rows are shown with uBlock enabled.

### uBlock Origin version

1.41.6

### Browser name and version

Firefox Developer Edition 98.0b6 (64-bit)

### Settings

- Hide placeholders of blocked elements
- Show the number of blocked requests on the icon
- Make use of context menu where appropriate
- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 
- Block CSP reports 
- Uncloak canonical names 

### Notes

At the moment I have only tried side-by-side comparison with uBlock enabled vs. disabled. Like I said, I am not sure how to determine which filter list(s) in particular might be the culprit(s). Once you explain to me how to check for that, I'll let you know the list(s) in question.

**Comment by mapx-** [comment]
Are you really using only the default filter lists ?
No other blocking addons ?

**Comment by ctp9** [comment]
> Are you really using only the default filter lists ?
> No other blocking addons ?

Is this something that I should list in the "Settings" section of the above template? Maybe I misunderstood what was being asked of me.

**Comment by mapx-** [comment]
go into dashboard, click `support` tab, go to last section - `Troubleshooting Information`, post here its content

**Comment by ctp9** [comment]
Oh that's nice - it's all listed in Troubleshooting Information:

`uBlock Origin: 1.41.6`
`Firefox: 98`
`filterset (summary): `
`  network: 446494`
`  cosmetic: 125515`
`  scriptlet: 30860`
`  html: 626`
`listset (total-discarded, last updated): `
`  removed:`
`    easyprivacy: null`
`  added:`
`    https://abp.oisd.nl/: 361771-35114, 23h.27m`
`    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1746-0, 23h.26m`
`    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 1d.3h.31m`
`    adguard-generic: 61990-5598, 1d.3h.37m`
`    adguard-spyware: 25696-831, 1d.3h.35m`
`    adguard-spyware-url: 489-75, 1d.3h.34m`
`    block-lan: 44-0, 2d.7h.28m`
`    curben-phishing: 11080-3, 23h.29m`
`    curben-pup: 405-0, 23h.28m`
`    fanboy-annoyance: 63991-3938, 4d.7h.40m`
`    ublock-annoyances: 4414-4, 1d.3h.32m`
`  default:`
`    user-filters: 229-7, never`
`    ublock-filters: 30799-28, 1d.5h.29m`
`    ublock-badware: 3969-3, 1d.3h.41m`
`    ublock-privacy: 202-2, 1d.3h.40m`
`    ublock-abuse: 77-0, 1d.3h.39m`
`    ublock-unbreak: 1726-0, 1d.3h.38m`
`    easylist: 63745-625, 1d.3h.36m`
`    urlhaus-1: 6604-0, 23h.30m`
`    plowe-0: 3670-3, 7h.24m`
`filterset (user): [array of 229 redacted]`
`trustedset:`
`  added: [array of 8 redacted]`
`  removed:`
`    edge-scheme`
`modifiedUserSettings: [none]`
`modifiedHiddenSettings: [none]`
`supportStats:`
`  allReadyAfter: 493 ms (selfie)`
`  maxAssetCacheWait: 366 ms`

**Comment by mapx-** [comment]
You said you are using `uBO with default lists/settings` => false (you are using other lists, you disabled important lists like Easyprivacy etc)

- save your current configuration (backup it)
- reset uBO to default settings
- click "purge all caches", click "update now"
- disable any other addon in firefox
- test again

**Comment by ctp9** [comment]
Found the issue after testing with a blank configuration and not being able to reproduce either.

The issue was in my own filters (`"My filters"`) that I created many years ago and forgot about. The website changed and therefore breakage started occurring. I will close this issue. Thank you for the recommendation on EasyPrivacy - not sure why that particular one was disabled.
