### ISSUE TITLE
ccleaner.com: breakage

### ISSUE THREAD

**Issue by mossy-isme** [uBlockOrigin/uAssets#11809]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ccleaner.com/ccleaner/chat-services`

### Category

breakage

### Describe the issue

Upon accessing the Premium Tech Support Live website for Piriform, a chat button should show bottom left upon loading the website, however, when enabling UBlock Origin, the chat button is hidden from view and removed. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![CCleaner UBlock Origin Bug Enabled](https://user-images.githubusercontent.com/100048599/154820046-61bb4c98-7f72-4e56-bd10-27c3b9e05fc0.png)

![CCleaner UBlock Origin Bug](https://user-images.githubusercontent.com/100048599/154820047-f0589fbf-a8bd-49b1-a0db-6382d2017cbf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78488
  cosmetic: 41378
  scriptlet: 16440
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    easylist: 63782-9, 15m
    easyprivacy: 26579-122, 15m
    plowe-0: 3670-803, 14m
    ublock-abuse: 77-0, 14m
    ublock-badware: 4002-76, 14m
    ublock-filters: 30250-140, 14m
    ublock-privacy: 198-2, 14m
    ublock-unbreak: 1716-39, 14m
    urlhaus-1: 7371-0, 14m
filterset (user): [array of 5 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 984 ms
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 4
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    cookielaw.org: 1
    google-analytics.com: 1
    google.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=ccleaner.com`

@ryanbr
