### ISSUE TITLE
parts.hp.com: breakage

### ISSUE THREAD

**Issue by TechyShishy** [uBlockOrigin/uAssets#11802]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://parts.hp.com/hppartsIGSO/CountryChoice.aspx`

### Category

breakage

### Describe the issue

https://parts.hp.com/ has an internal redirect to this page which it apparently uses to send you to the appropriate region page for their parts store.  While I'd prefer to manually select my region, since the body content of the page is this (whitespace reflowed for readability), it basically presents an empty white page with nothing to do:

```xhtml
<body>
    <form name="ccMain" method="post" action="./CountryChoice.aspx" id="ccMain">
        <div>
            <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJMTk4NzQ5NzMxD2QWAgIDD2QWAgIBD2QWAgIHDxYCHgRUZXh0BU88c2NyaXB0IHNyYz0naHR0cHM6Ly9nZW9sb2NhdGlvbi1kYi5jb20vanNvbnAnIHR5cGU9J3RleHQvamF2YXNjcmlwdCc+PC9zY3JpcHQ+ZGQYUdCnpgfLfkEMbf1m7Pv16qVWAg==" />
        </div>
        <div>
            <input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="F1E870CA" />
        </div>
        <input name="hdn_loc_cc" type="hidden" id="hdn_loc_cc" />
        <input type="submit" name="btnDoPostback" value="" id="btnDoPostback" style="display: none;" />
        <script type="text/javascript">
            function callback(data) {
                document.getElementById('hdn_loc_cc').value = data.country_code;
                var btn = document.getElementById("btnDoPostback");
                btn.click();  
            }
        </script>
        <script src='https://geolocation-db.com/jsonp' type='text/javascript'></script>
    </form>
</body>
```

If possible, it would be valuable to raise the issue with HP as well, since allowing passive geolocation isn't necessarily desirable.  On the other hand, uBlockOrigin shouldn't break the site entirely.

Something to note is that this occurs only when the `hpparts_cc` cookie is unset on the `parts.hp.com` domain.  Once that cookie is set, that page gets bypassed by their servers' processing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![DevTools showing the blocked jsonp request](https://user-images.githubusercontent.com/848519/154759697-1824bc29-56f7-4deb-b6ae-5b1722f57eae.png)

I didn't include a screenshot of the page itself, since an empty DOM produces a blank white page, and that's not a useful screenshot.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78351
  cosmetic: 41333
  scriptlet: 16437
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 63622-9, 3d.1h.2m
    easyprivacy: 26560-120, 3d.1h.3m
    plowe-0: 3679-807, 11d.19h.51m
    ublock-abuse: 77-0, 3d.1h.1m
    ublock-badware: 3940-76, 3d.59m
    ublock-filters: 30250-141, 3d.58m
    ublock-privacy: 201-2, 3d.1h.5m
    ublock-unbreak: 1716-39, 3d.1h.4m
    urlhaus-1: 7423-0, 1h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2462 ms (selfie)
  maxAssetCacheWait: 1237 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    geolocation-db.com: 1
```
</details>

**Comment by okiehsch** [comment]
> would be valuable to raise the issue with HP as well, since allowing passive geolocation isn't necessarily desirable.

I highly doubt they care, they set it up that way because they think it's the most convenient way for their users to reach the proper region version of their site imo,

**Comment by TechyShishy** [comment]
I don't disagree, but it's an accessibility issue.  It would be best imho if their page did what it currently does, but had a fallback link selection for region in the event that javascript is disabled or their geoip script breaks for whatever reason.  Just my $0.02.
