### ISSUE TITLE
Ads on fandom.com mobile sites

### ISSUE THREAD

**Issue by huupoke12** [uBlockOrigin/uAssets#11803]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dontstarve.fandom.com/wiki/Fire`

### Describe the issue

1. Open the above link.
2. Open responsive design mode. On Firefox, use `Ctrl+Shift+M` or click Hamburger menu on the top-right => `More tools => Responsive Design Mode`.
3. Choose a mobile profile (I have tested with "Galaxy Note 20 Linux" and "iPhone 11 Pro iOS 14.6").
4. Click on the lock icon on the address bar => `Clear cookies and site data`.
5. Refresh the page (`F5`).
6. The ads is shown.

### Screenshot(s)

![Screenshot_2022-02-19_10-02-29](https://user-images.githubusercontent.com/16283764/154783665-09b35c80-75e5-44f5-9154-91e2c74f6b4f.png)
![Screenshot_2022-02-19_10-02-23](https://user-images.githubusercontent.com/16283764/154783668-3a0e82d0-7d69-466f-835b-aac16e09f52b.png)

### uBlock Origin version

1.41.6

### Browser name and version

Firefox ESR 91.6.0 (64-bit)

### Settings

- Filter lists => Purge all caches => Update now

**Comment by Procyon-b** [comment]
Which filter list are you using?
Can you post the "_Troubleshooting Information_" in the "_Support_" tab in ublock's dashboard?

**Comment by huupoke12** [comment]
```
uBlock Origin: 1.41.6
Firefox: 91
filterset (summary): 
  network: 78532
  cosmetic: 41372
  scriptlet: 16394
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30818-27, 2h.11m
    ublock-badware: 3994-3, 2h.11m
    ublock-privacy: 202-0, 2h.11m
    ublock-abuse: 77-0, 2h.11m
    ublock-unbreak: 1728-0, 2h.11m
    easylist: 63773-589, 2h.11m
    easyprivacy: 26578-571, 2h.11m
    urlhaus-1: 7423-0, 2h.11m
    plowe-0: 3670-2, 2h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2143 ms (selfie)
  maxAssetCacheWait: 189 ms
```

**Comment by mapx-** [comment]
needing us ip

test

`fandom.com###article-featured-video-container`

@ryanbr

**Comment by mapx-** [comment]
@Yuki2718 it could be added to `AdGuard Mobile Ads`

**Comment by Yuki2718** [comment]
Will remove once added to EL.
