### ISSUE TITLE
pushsquare.com: detection

### ISSUE THREAD

**Issue by Duka67** [uBlockOrigin/uAssets#11815]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pushsquare.com/`

### Category

detection

### Describe the issue

Hi. I've tried to use the picker tool on this website many times but uBO is still detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78422
  cosmetic: 41487
  scriptlet: 16425
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 142-9, never
    easylist: 63744-9, 1d.21h.3m
    easyprivacy: 26576-122, 1d.21h.2m
    plowe-0: 3673-804, 5d.21h.52m
    ublock-abuse: 77-0, 1d.21h.1m
    ublock-badware: 3985-76, 1d.21h
    ublock-filters: 30228-140, 1d.20h.59m
    ublock-privacy: 203-2, 1d.20h.58m
    ublock-unbreak: 1716-39, 1d.20h.56m
    urlhaus-1: 7344-0, 10h.40m
filterset (user): [array of 142 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms
  maxAssetCacheWait: 200 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    pushsquare.com: 6
    amazon-adsystem.com: 1
    doubleclick.net: 4
    google-analytics.com: 1
    parsely.com: 1
    pbstck.com: 1
    scorecardresearch.com: 1
    summerhamster.com: 1
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce, can you post a screenshot ?

**Comment by Duka67** [comment]
Wow, fast response, thanks. I'm unable to until later. If I go back to the
website during the day the pop-up doesn't appear. It will have to be a bit
later or more likely tomorrow. Would this is ok? I'll reply to your email
when it does it for me again.

**Comment by okiehsch** [comment]
> I'll reply to your email when it does it for me again.

Just responding in this issue thread is fine.
 I can see that the site uses sourcepoint to check for an adblocker but I can't reproduce an anti adblock message. A screenshot would clarify if what you see is indeed caused by sourcepoint or not.

**Comment by Duka67** [comment]
![FireShot Capture 157 - Push Square - PS5, PS4, PS4 Pro, PlayStation VR, PS Vita   Retro, New_ - www pushsquare com](https://user-images.githubusercontent.com/99655352/154933772-d233e602-5684-4fe8-8013-ef8ff83a19ec.jpg)

**Comment by okiehsch** [comment]
Adding
`pushsquare.com##+js(aopr, _sp_._networkListenerData)`
to your filter list should disable it.

It's a dismissable anti adblock issue, i.e. you can click "continue bllocking ads" and the modal should not appear again until your next brwoser seesion.
We fix those kind of issues in `uBO-annoyances` and that list is not enabled by default.

**Comment by Duka67** [comment]
Many thanks. Keep up the great work. Enjoy the rest of your day.
