### ISSUE TITLE
basic-tutorials.de: ads

### ISSUE THREAD

**Issue by dvcons** [uBlockOrigin/uAssets#11819]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://basic-tutorials.de/`

### Category

ads

### Describe the issue

There are several ads all over the page.

Tested on Firefox and Edge.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 78412
  cosmetic: 56622
  scriptlet: 16405
  html: 617
listset (total-discarded, last updated): 
  added: 
    adguard-social: 15846-14, 2h.23m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30829-142, 2h.29m
    ublock-badware: 3994-3, 2h.22m
    ublock-privacy: 202-0, 2h.26m
    ublock-abuse: 77-0, 2h.28m
    ublock-unbreak: 1727-0, 2h.25m
    easylist: 63789-464, 2h.27m
    easyprivacy: 26597-585, 2h.24m
    urlhaus-1: 6687-0, 10h.30m
    plowe-0: 3673-2, 5d.13h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1991 ms (selfie)
  maxAssetCacheWait: 1469 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    amazon-adsystem.com: 1
    digidip.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    taboola.com: 1
    vgwort.de: 1
```
</details>

**Comment by Procyon-b** [comment]
Subscribe to the "_DEU: EasyList Germany_" regional list and try again.

**Comment by dvcons** [comment]
Thanks for the answer.

I tried your suggestions on Firefox and Edge (both up-to-date on Win10). Sadly it didn't help:

![Screenshot 2022-02-21 025437](https://user-images.githubusercontent.com/63475015/154877326-84be9e42-1ffe-4a79-9fd3-a234886d86c0.jpg)

I've now checked on another device (Firefox, Win 11) without "_DEU: EasyList Germany_" or that custom filter, and weirdly there are no ads to be seen here.

I was on that same site only 2 days ago and there were no ads, so I'm now suspecting there is some issue on my device. I'll do some more troubleshooting myself and see if I can fix it somehow.

**Comment by Procyon-b** [comment]
Can you verify that when viewing this site, ublock's icon is red (and not gray). When opening the popup, the power button should be blue: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button

**Comment by mapx-** [comment]
test

`basic-tutorials.de##+js(aopr, advanced_ads_ready)`

**Comment by okiehsch** [comment]
> [These guys](https://republicbrief.com/scotus-se-to-deliver-game-changing-ruling-on-gun-control/) seem to be using the same ads-placement software

The ads I see are from a different company, does
`republicbrief.com##+js(aost, Math.random, /injectedScript.*inlineScript/)`
work for you without breaking anything?

**Comment by okiehsch** [comment]
The ads you see are caused by a different script, it's the obfuscated one at the end of the source.
![image](https://user-images.githubusercontent.com/16838044/171254160-78cf13ce-1856-423d-bda9-7b5104904411.png)
