### ISSUE TITLE
PCGamesN text cut off on top

### ISSUE THREAD

**Issue by joebagadonuts188** [uBlockOrigin/uAssets#11812]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pcgamesn.com/cyberpunk-2077/player-count-february-2022`

### Describe the issue

The text is cut off at the top. If I block the following filter, it fixes the issue.

`pcgamesn.com##html > body:style(padding-top:0px !important)`

### uBlock Origin version

uBlock Origin 1.41.2

### Browser name and version

Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Settings

- I blocked the filter by adding it my filters as `pcgamesn.com#@#html > body:style(padding-top:0px !important)`

**Comment by uBlock-user** [comment]
> The text is cut off at the top. 

I don't see any text getting cut. Take a snapshot and share it here.
