### ISSUE TITLE
slhgfdsir.com: ads

### ISSUE THREAD

**Issue by trreseet** [uBlockOrigin/uAssets#11811]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slhgfdsir.com/1/3601325/?var=4755510&ab2r=0&prfrev=false`

### Category

ads

### Describe the issue

you can see the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 97
filterset (summary): 
  network: 78376
  cosmetic: 41115
  scriptlet: 16415
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63376-9, 4d.20h.50m
    easyprivacy: 26576-120, 1d.3h.23m
    plowe-0: 3673-805, 4d.20h.52m
    ublock-abuse: 77-0, 1d.4h.18m
    ublock-badware: 3985-76, 1d.4h.17m
    ublock-filters: 30216-135, 1d.3h.22m
    ublock-privacy: 203-2, 1d.3h.25m
    ublock-unbreak: 1716-39, 1d.3h.24m
    urlhaus-1: 7423-0, 1d.3h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4711 ms (selfie)
  maxAssetCacheWait: 2561 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    gearbest.com: 1
```
</details>

**Comment by mapx-** [comment]
provide the real page from where you arrived to this slhgfdsir page
