### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by NotAllowedUsername** [uBlockOrigin/uAssets#11814]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropgalaxy.com/jloyipqfwsgz`

### Category

detection

### Describe the issue

Adblocker detected ✋. Click on this link and try to download this . 

### Screenshot(s)

![Screenshot_2022-02-20-12-05-34-78_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/100062555/154831818-9b00c1d6-4252-460a-aaff-d51b0bca258a.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium Mobile: 98
filterset (summary): 
  network: 231979
  cosmetic: 218930
  scriptlet: 36405
  html: 0
listset (total-discarded, last updated): 
  added: 
    ALB-0: 261-6, 22h.19m
    BGR-0: 1116-19, 22h.18m
    CHN-0: 27939-1094, 22h.18m
    CZE-0: 780-40, 22h.18m
    DEU-0: 5343-371, 22h.18m
    EST-0: 445-10, 22h.18m
    FIN-0: 1533-75, 22h.18m
    FRA-0: 26072-3299, 22h.18m
    GRC-0: 1002-19, 22h.18m
    HUN-0: 2167-43, 22h.18m
    IDN-0: 9074-3641, 22h.18m
    IRN-0: 1340-72, 22h.18m
    ISL-0: 193-2, 22h.18m
    ISR-0: 1614-7, 22h.18m
    ITA-0: 12838-461, 22h.18m
    JPN-1: 5943-136, 22h.18m
    KOR-1: 8113-609, 22h.18m
    LTU-0: 1183-16, 22h.18m
    LVA-0: 393-4, 22h.17m
    NLD-0: 2088-19, 22h.17m
    [28 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    adguard-mobile: 7234-147, 22h.17m
    easylist: 63776-25127, 22h.17m
    easyprivacy: 26578-11617, 22h.17m
    plowe-0: 3670-1513, 22h.16m
    ublock-abuse: 77-2, 22h.16m
    ublock-badware: 3990-265, 22h.16m
    ublock-filters: 30345-3896, 22h.16m
    ublock-privacy: 198-40, 22h.16m
    ublock-unbreak: 1722-139, 22h.16m
    urlhaus-1: 7423-4, 22h.16m
filterset (user): [empty]
modifiedUserSettings: 
  uiTheme: light
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3896 ms (selfie)
  maxAssetCacheWait: 2306 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Update the filter lists it got fixed yesterday (uBlock Origin logo -> gears -> filter lists -> purge all cache -> update now) i get no anti adb

**Comment by JobcenterTycoon** [comment]
I get anti right click and anti F keys too
