### ISSUE TITLE
hayu.com: breakage

### ISSUE THREAD

**Issue by Massaar** [uBlockOrigin/uAssets#11817]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hayu.com/show/episode/29544488326`

### Category

breakage

### Describe the issue

This is a sitewide issue on any videos that can generate captions. With the ad blocker enabled, it auto generates captions over the videos, and when you turn them on manually, there are then two sets of captions. The auto generated captions from having the adblocker on will also be displayed over any that are hard subbed in the video ie: foreign language translations or hard to hear moments.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 111600
  cosmetic: 79085
  scriptlet: 31068
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 2d.15h.21m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 202d.13h.40m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 12-0, 393d.12h.45m
    adguard-generic: 62076-751, 15h.50m
    adguard-mobile: 7234-44, 1d.11h.31m
    adguard-spyware: 25711-676, 1d.11h.33m
    ublock-annoyances: 4405-227, 1d.11h.29m
  default: 
    user-filters: 180-12, never
    easylist: 63782-1078, 15h.52m
    easyprivacy: 26579-11130, 15h.51m
    plowe-0: 3675-964, 4d.1h.11m
    ublock-abuse: 77-0, 1d.11h.30m
    ublock-badware: 3990-246, 15h.54m
    ublock-filters: 30237-3055, 15h.53m
    ublock-privacy: 203-34, 1d.11h.32m
    ublock-unbreak: 1715-104, 1d.11h.34m
    urlhaus-1: 7344-0, 15h.49m
filterset (user): [array of 182 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1775 ms (selfie)
  maxAssetCacheWait: 983 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    hayu.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    litix.io: 1
    newrelic.com: 1
    omtrdc.net: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
We don't have an account, so is unfixable on our side.
You should see what list is causing the issue then what filter (use the logger to identify the various blocked items).
