### ISSUE TITLE
anilibria.tv: breakage

### ISSUE THREAD

**Issue by JAKill02** [uBlockOrigin/uAssets#11824]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.anilibria.tv/release/platinum-end.html`

### Category

breakage

### Describe the issue

completely breaks the appearance of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 86
filterset (summary): 
  network: 95921
  cosmetic: 63037
  scriptlet: 18031
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 119-6, never
    RUS-0: 41445-9, 5m
    easylist: 63806-21, 5m
    easyprivacy: 26606-221, 4m
    plowe-0: 3670-810, 6m
    ublock-abuse: 77-1, 4m
    ublock-badware: 4018-76, 4m
    ublock-filters: 30245-173, 4m
    ublock-privacy: 199-2, 6m
    ublock-unbreak: 1715-39, 6m
    urlhaus-1: 6641-0, 6m
filterset (user): [array of 130 redacted]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 101 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 48143 ms (selfie)
  maxAssetCacheWait: 726 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    digitalcaramel.com: 1
    googletagmanager.com: 1
    jsdelivr.net: 2
    mail.ru: 1
    static.anilibria.tv: 3
    utarget.ru: 1
    yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
Update your browser, test disabling all other extensions

**Comment by Procyon-b** [comment]
@mapx- I've tried with an old browser (chrome 70) and I don't see any problem.

@JAKill02 you have 130 user filters. Try without them. Go to the "_Filter lists_" tab and uncheck "_My filters_", click "_Apply changes_". Reload the website. If it's fixed, re-enable "_My filters_" and check them one by one.
Also look at ublock's popup window on the site's tab to see if you have disabled some elements (you have 101 rules)

**Comment by dimisa-RUAdList** [comment]
@gorhill 
For some reason, the `third-party` option is too strict on this site. Try adding `||static.anilibria.tv^$third-party` and open `https://www.anilibria.tv/`. The site will be broken, and the following will be in the logger: https://i.imgur.com/bxJyDuC.jpg

The problem is observed in Chromium-versions 1.41.2 - 1.41.7b1 downloaded from here: https://github.com/gorhill/uBlock/releases and also in version 1.41.7.0 downloaded from here: `https://chrome.google.com /webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii`

**Comment by gorhill** [comment]
From what I see so far, `*.tv` seems to be deemed a Public Suffix. I don't know why as I can't find an entry in the official PSL, need to investigate more.

**Comment by gwarser** [comment]
WTF? I was able to repro so I started bisecting lower and lower versions and then it stopped and I cannot reproduce anymore.

**Comment by gorhill** [comment]
This looks like this might be a lengthy investigation -- for now maybe just use `||static.anilibria.tv^$domain=~anilibria.tv`.

**Comment by gorhill** [comment]
@gwarser Are you using a new uBO install for each bisect to be sure the selfie is not being used every time?

**Comment by gwarser** [comment]
Ok, it breaks again after copy-pasting the URL from above message into new Chrome tab. Previously I did modified the filter in My filters by removing, saving and adding back characters and saving again, then force-reloading the tab.

**Comment by dimisa-RUAdList** [comment]
In fact, to fix the break, I had to edit the rule against disposable adservers, removing `anilibria.tv` from the list of target domains: https://github.com/easylist/ruadlist/commit/53d39cb6349f86a1517498fda943fc37910508e1

**Comment by gwarser** [comment]
1.18 was fine, 1.19 - fine, back to 1.20.0 and it's fine ;D

**Comment by gorhill** [comment]
> had to edit the rule against disposable adservers

But I didn't use RUAdList.

Furthermore, when I add tests [to PSL library](https://github.com/gorhill/publicsuffixlist.js/blob/master/docs/test.html), all passes:

    checkPublicSuffix('www.anilibria.tv', 'anilibria.tv');
    checkPublicSuffix('static.anilibria.tv', 'anilibria.tv');

So I have no clue what is going on.

**Comment by gwarser** [comment]
Introduced in https://github.com/gorhill/uBlock/commit/4da340384ae0697d3083523d95253a3506b0aecf

**Comment by gorhill** [comment]
> when I add tests [to PSL library](https://github.com/gorhill/publicsuffixlist.js/blob/master/docs/test.html), all passes

All tests pass with the bundled PSL. When I replace the bundled list with the latest one from PSL dot org, the two tests fail.

**Comment by gwarser** [comment]
> // newGTLDs
> 
> // List of new gTLDs imported from https://www.icann.org/resources/registries/gtlds/v2/gtlds.json on 2022-02-18T15:13:38Z
> // This list is auto-generated, don't edit it manually.
> // aaa : 2015-02-26 American Automobile Association, Inc.
> aaa
>...

**Comment by gorhill** [comment]
I think the flaw in the code is that it's not ready to deal with related PSL entries which are spread throughout the list. `tv` is such one case.

**Comment by gwarser** [comment]
https://github.com/publicsuffix/list/commits/master/public_suffix_list.dat

**Comment by gorhill** [comment]
Ok I found the issue. It's very unlikely to be triggered, but it can happen, and it did happen eventually as shown here.
