### ISSUE TITLE
gamerafter.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#11820]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gamerafter.com/sorry-there-was-a-problem-with-your-request/`

### Category

nuisance

### Describe the issue

footer banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/154888769-95f46ecc-66af-464e-8f9c-6b1314559d91.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 100
filterset (summary): 
  network: 67576
  cosmetic: 95710
  scriptlet: 33890
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1833-9, 1h.21m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6055-3, 1h.19m
    IDN-0: 9084-216, 1h.32m
    adguard-annoyance: 50433-175, 1h.30m
    adguard-generic: 62040-826, 1h.27m
    adguard-mobile: 7235-54, 1h.25m
    adguard-spyware: 25734-774, 1h.23m
    ublock-annoyances: 4403-188, 1h.15m
  default: 
    user-filters: 9-0, never
    ublock-abuse: 77-0, 1h.17m
    ublock-badware: 4018-193, 1h.13m
    ublock-filters: 30251-3333, 1h.11m
    ublock-privacy: 199-30, 1h.9m
    ublock-unbreak: 1719-91, 1h.7m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 879 ms (selfie)
  maxAssetCacheWait: 580 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    gamerafter.com: 8
    doubleclick.net: 3
    ezodn.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
`gamerafter.com##.ez-video-wrap`

@ryanbr
