### ISSUE TITLE
ect.se.com - breakage

### ISSUE THREAD

**Issue by jefm-semco** [uBlockOrigin/uAssets#11822]
### Prerequisites

- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ect.se.com/cbt/app/index.html?Lang=en-GB&Regulation=EuropeCenelec`

### Describe the issue

website being blocked, just a blank page is showing

### Notes

disable ublock and whitelist the URL at uBlock Origin. I have plenty of users accessing the page block site `https://ect.se.com/cbt/app/index.html?Lang=en-GB&Regulation=EuropeCenelec`
Is there a way to whitelist this at uBlock Origin ?

### Configuration

.<details>
```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77732
  cosmetic: 41389
  scriptlet: 16439
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63803-9, 1h.12m
    easyprivacy: 26606-122, 1h.11m
    plowe-0: 3670-803, 1h.10m
    ublock-abuse: 77-0, 1h.8m
    ublock-badware: 3940-76, 1h.6m
    ublock-filters: 30251-141, 1h.5m
    ublock-privacy: 201-2, 1h.4m
    ublock-unbreak: 1716-39, 1h.3m
    urlhaus-1: 6641-0, 1h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1688 ms
  maxAssetCacheWait: 176 ms
```
</details>

**Comment by mapx-** [comment]
`@@||ect.se.com/cbt/app/js/util/angularytics.min.js$script,1p`

EP issue @ryanbr

**Comment by jefm-semco** [comment]
![page not loading](https://user-images.githubusercontent.com/100128929/155078778-30a31c1e-0efb-46e3-8021-377dd313e148.JPG)
please see attached file for reference

**Comment by mapx-** [comment]
The filter above should work, did you test it ?
We are waiting EP maintainer to add the fix in the list

**Comment by uBlock-user** [comment]
Disable Edge's built-in adblocker after adding the filter.

**Comment by jefm-semco** [comment]
> 
I just added it to Filter, and it worked. But I have a lot users. It will be very tedious to add it per workstation.

**Comment by mapx-** [comment]
It was added to the official list (easyprivacy), just ask all of the users to update the filter lists or wait: in 3-4 days all the lists will be automatically updated

**Comment by jefm-semco** [comment]
Will do monitor between 3-4 days.

Thank you
