### ISSUE TITLE
Share Buttons on Multiple Websites

### ISSUE THREAD

**Issue by bkrucarci** [uBlockOrigin/uAssets#11827]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Share Buttons
Website    : https://www.sabah.com.tr/spor/futbol/2022/02/21/fenerbahce-diego-rossiyi-kapa-bildirdi
Screenshot : https://imgur.com/lPvCnah.png
+
Website    : https://www.hurriyet.com.tr/dunya/son-dakika-putinden-canli-yayinda-cok-kritik-aciklama-42008515
Screenshot : https://i.imgur.com/c98GtUI.png
+
Website    : https://analizmerkezi.com/cia-mossadin-turkiyeye-kurdugu-daes-bagdadi-tuzagi-nasil-bozuldu-ozel-haber/57428/
Screenshot : https://i.imgur.com/hjxpelu.png
+
Website    : https://onedio.com/haber/28-subat-hangi-burc-20-subat-ile-20-mart-arasinda-doganlarin-burc-ozellikleri-nelerdir-1047524
Screenshot : https://i.imgur.com/pLD016P.png
+
Website    : https://www.odatv4.com/dunya/rusya-dan-olum-listesi-yaniti-230450
Screenshot : https://i.imgur.com/mRdPelV.png
+
Website    : https://www.gazetevatan.com/calisma-hayati/memur/memur-ve-emekli-milyonlarin-bekledigi-duzenlemede-yeni-gelisme-maaslara-ve-ikramiyelere-zam-mayista-2021943
Screenshot : https://i.imgur.com/ZY9kmgV.png
+
Website    : https://www.f5haber.com/gundem/gelin-ile-damadin-cevresinde-drift-yapan-surucuye-9-bin-125-lira-ceza-6178629
Screenshot : https://i.imgur.com/yoBkVkF.png
+
Website    : https://www.karar.com/ekonomi-haberleri/ato-baskani-esnafa-yapilan-elektrikte-indirimli-tarife-tacirlere-de-1652693
Screenshot : https://i.imgur.com/hpc2T69.png
+
Website    : https://www.fotomac.com.tr/fenerbahce/2022/02/21/spor-haberleri-fenerbahcenin-yildizi-mesut-ozilden-arda-guler-paylasimi-gelecegin-10-numarasi
Screenshot : https://i.imgur.com/A8DFX7F.png
+
Website    : https://www.internetspor.com/mesut-ozil-fenerbahceden-ayriliyor-iste-yeni-adresi-foto-galerisi-2010432.htm
Screenshot : https://i.imgur.com/US0JpGA.png

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 108555
  cosmetic: 119280
  scriptlet: 31204
  html: 625
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    curben-phishing: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 265-0, 46m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/AntiAstrologyList.txt: 362-0, 46m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/AntiPrayerTimesList.txt: 102-0, 46m
    adguard-generic: 62100-4778, 47m
    adguard-spyware: 25715-776, 47m
    fanboy-thirdparty_social: 69-0, 47m
    fanboy-cookiemonster: 22269-132, 46m
    fanboy-social: 23168-31, 46m
    ublock-annoyances: 4415-43, 46m
    TUR-0: 8549-89, 46m
  default: 
    user-filters: 83-0, never
    ublock-filters: 30825-27, 47m
    ublock-badware: 4022-3, 47m
    ublock-privacy: 198-0, 47m
    ublock-abuse: 77-0, 47m
    ublock-unbreak: 1726-0, 47m
    easylist: 63806-285, 47m
    adguard-spyware-url: 489-3, 47m
    easyprivacy: 26606-10571, 47m
    LegitimateURLShortener: 1749-76, 46m
filterset (user): [array of 86 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  uiAccentCustom: true
  uiAccentCustom0: #008080
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1467 ms
  maxAssetCacheWait: 641 ms
```
</details>

**Comment by uBlock-user** [comment]
Report any of the Annoyances list. uBO doesn't maintain a social list.
