### ISSUE TITLE
dropbox.com: breakage

### ISSUE THREAD

**Issue by Lepuus** [uBlockOrigin/uAssets#11826]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dropbox.com/`

### Category

breakage

### Describe the issue

The upload progress bar is not displayed with uBO enabled when I upload a file on it. I only have it when the upload is finished.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

What I should have: 
![image](https://user-images.githubusercontent.com/81618271/154976780-85855118-171e-49f3-9584-abf5585674ac.png)

What I juste have:
![image](https://user-images.githubusercontent.com/81618271/154976925-202f089f-2fbf-410c-87f4-e5f3d380639b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 95570
  cosmetic: 71026
  scriptlet: 16494
  html: 617
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 21959-16, 3d.23h.29m
    FRA-0: 26126-367, 50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30821-193, 57m
    ublock-badware: 4022-3, 56m
    ublock-privacy: 198-0, 55m
    ublock-abuse: 77-0, 54m
    ublock-unbreak: 1730-0, 53m
    easylist: 63806-651, 52m
    easyprivacy: 26606-573, 51m
    urlhaus-1: 6687-0, 14h.12m
    plowe-0: 3679-2, 10d.12h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6940 ms (selfie)
  maxAssetCacheWait: 611 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    dropbox.com: 15
```
</details>

**Comment by mapx-** [comment]
add

`dropbox.com#@#.dig-Snackbar`

@ryanbr

**Comment by ryanbr** [comment]
Has been removed. Force an update.
