### ISSUE TITLE
xxvids.net ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1183]
URL(s) where the issue occurs

`http://xxvids.net/video/reality-kings-pure18-lovely-melons/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
