### ISSUE TITLE
bfmtv.com: breakage

### ISSUE THREAD

**Issue by raphpitt** [uBlockOrigin/uAssets#11836]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bfmtv.com/economie/replay-emissions/culture-geek/culture-geek-la-technologie-au-service-de-la-medecine-par-frederic-simottel-22-02_VN-202202220035.html`

### Category

breakage

### Describe the issue

The video is not displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/34160362/155114091-ea277fae-4036-4166-85ae-72a6e015d454.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79677
  cosmetic: 67069
  scriptlet: 28079
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 15h.29m
    adguard-generic: 62004-1135, 3d.20h.20m
    adguard-spyware: 25711-698, 3d.2h.24m
    fanboy-cookiemonster: 21849-14, 8d.13h.34m
  default: 
    user-filters: 30-0, never
    ublock-filters: 30226-3046, 3d.20h.22m
    urlhaus-1: 6641-0, 1d.1m
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 69 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1306 ms (selfie)
  maxAssetCacheWait: 546 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    privacy-center.org: 1
    xiti.com: 1
```
</details>

**Comment by okiehsch** [comment]
Caused by your custom setup.
Specifically
`||privacy-center.org^$third-party` 
in `fanboy-cookiemonster`
We don't deal with issues caused by non default lists.

**Comment by mapx-** [comment]
add

`@@||sdk.privacy-center.org^$script,domain=bfmtv.com`

@ryanbr
