### ISSUE TITLE
guancha.cn: breakage

### ISSUE THREAD

**Issue by sanmaodo** [uBlockOrigin/uAssets#11834]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.guancha.cn/`

### Category

breakage

### Describe the issue

Can't log into account.
Can't create comment.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 95622
  cosmetic: 51410
  scriptlet: 16541
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 27945-87, 24m
    easylist: 63868-11, 46m
    easyprivacy: 26608-148, 44m
    plowe-0: 3670-805, 42m
    ublock-abuse: 77-0, 37m
    ublock-badware: 4019-76, 32m
    ublock-filters: 30251-161, 30m
    ublock-privacy: 199-2, 27m
    ublock-unbreak: 1715-40, 26m
    urlhaus-1: 6704-0, 25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1457 ms
  maxAssetCacheWait: 789 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    guancha.cn: 1
    admaster.com.cn: 1
    baidu.com: 1
    qq.com: 4
```
</details>

**Comment by mapx-** [comment]
> Can't log into account.

Explain what's wrong: do you get the login window (clicking log in register button) ? other ?

**Comment by sanmaodo** [comment]
Yes, you can see the full interface, but it won't respond after clicking.

**Comment by mapx-** [comment]
clicking what ? exactly which button. SMS button ? social buttons ? log in button ?

does this filter help ?
`@@||guancha.cn/js/sensorsdata.min.js$script,1p`
