### ISSUE TITLE
odysee.com: breakage

### ISSUE THREAD

**Issue by hearthburst** [uBlockOrigin/uAssets#11838]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://odysee.com/`

### Category

breakage

### Describe the issue

when ublock is activated, the videos previews don't load, nether the background for that matter,
strangly the user's pictures load randomly (some load normaly, other don't load at all),
the links to the videos work fine, so the site kinda work, but the previews don't and it's frustrating.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/49098041/155122888-4986af4e-28ea-4379-bd4f-260b27320792.png)

![image](https://user-images.githubusercontent.com/49098041/155123381-9e02a04c-ce8b-4bd4-a235-84fe447539a4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 93894
  cosmetic: 50595
  scriptlet: 16438
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30809-27, 3d.17h.10m
    ublock-badware: 3994-3, 3d.17h.9m
    ublock-privacy: 202-0, 3d.17h.8m
    ublock-abuse: 77-0, 3d.17h.7m
    ublock-unbreak: 1727-0, 3d.17h.6m
    easylist: 63746-645, 3d.17h.5m
    easyprivacy: 26576-570, 3d.17h.4m
    urlhaus-1: 6641-0, 23h.49m
    plowe-0: 3673-2, 10d.17h.14m
    FRA-0: 26071-525, 3d.17h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 313 ms (selfie)
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
it should work

`||vanwa.tech^$3p,badfilter`

@Yuki2718 (french list)

**Comment by Yuki2718** [comment]
@smed79

**Comment by smed79** [comment]
https://github.com/easylist/listefr/commit/2f59c8150c36ea9abf59bc76e94ad30226415ea5
