### ISSUE TITLE
thingiverse.com: detection

### ISSUE THREAD

**Issue by cepedajtmx** [uBlockOrigin/uAssets#11830]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thingiverse.com/thing:3131931/files`

### Category

detection

### Describe the issue

Asking to disable adblocker.

### Screenshot(s)

![disableadblocker](https://user-images.githubusercontent.com/100177860/155053775-19dd65d4-23e1-4e51-ad2c-79bdfd7995df.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Firefox: 97
filterset (summary): 
  network: 80768
  cosmetic: 45926
  scriptlet: 16583
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30818-85, 3d.2h.20m
    ublock-badware: 3994-3, 3d.2h.27m
    ublock-privacy: 202-0, 3d.2h.26m
    ublock-abuse: 77-0, 3d.2h.25m
    ublock-unbreak: 1727-0, 3d.2h.24m
    easylist: 63773-653, 3d.2h.23m
    easyprivacy: 26578-599, 3d.2h.22m
    plowe-0: 3673-2, 6d.16h.17m
    spa-0: 3783-1, 19h.17m
    spa-1: 4235-102, 3d.2h.21m
    urlhaus-1: 6641-0, 19h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2179 ms (selfie)
  maxAssetCacheWait: 360 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    thingiverse.com: 2
    amazon-adsystem.com: 2
    datadoghq-browser-agent.com: 1
    doubleclick.net: 2
    googletagmanager.com: 2
    uptime.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||doubleclick.net^$xhr,redirect-rule=noop.txt,domain=thingiverse.com
```

**Comment by travipross** [comment]
I'm also unable to access thingiverse while ublock origin is enabled.

**Comment by uBlock-user** [comment]
force update ublock filters list or wait for the auto-update to kick in.

**Comment by travipross** [comment]
> force update ublock filters list or wait for the auto-update to kick in.

This resolved the issue for me
