### ISSUE TITLE
cocomanga.com: detection

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#11839]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cocomanga.com/12202/1/1983.html`

### Category

detection

### Describe the issue

As per screenshot

Previous issue was closed as already done but it does not appear in `https://filters.adtidy.org/extension/ublock/filters/224.txt`

:pushpin:  **Please allow comment after closing an issue to prevent creation of additional issues when further discussion is required.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cocomanga](https://user-images.githubusercontent.com/6458876/155125492-bc4d2cca-f6a3-4f23-8cf2-14fec1ad20a9.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 99
filterset (summary): 
  network: 95869
  cosmetic: 52528
  scriptlet: 19305
  html: 625
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 3m
    ublock-annoyances: 4421-4, 3m
    CHN-0: 27926-91, 3m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30838-46, 3m
    ublock-badware: 4023-3, 3m
    ublock-privacy: 198-0, 3m
    ublock-abuse: 77-0, 3m
    ublock-unbreak: 1726-0, 3m
    easylist: 63654-599, 3m
    easyprivacy: 26609-595, 3m
    urlhaus-1: 6613-0, 3m
    plowe-0: 3670-2, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1082 ms (selfie)
  maxAssetCacheWait: 715 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    cocomanga.com: 2
    bdstatic.com: 1
    cnzz.com: 1
    couplestupidity.com: 1
    exdynsrv.com: 5
```
</details>

**Comment by uBlock-user** [comment]
@erosman Did you try commenting at https://github.com/uBlockOrigin/uAssets/issues/11837 ?

It's not locked.

**Comment by uBlock-user** [comment]
It does -- `cocomanga.com,ohmanhua.com,onemanhua.com##+js(no-setTimeout-if, checkSiteNormalLoad)`

**Comment by okiehsch** [comment]
> Please allow comment after closing an issue to prevent creation of additional issues when further discussion is required.

You can still comment after we close an issue, you can't reopen it if it was closed by a maintainer but you can still comment.

**Comment by erosman** [comment]
> It does -- cocomanga.com,ohmanhua.com,onemanhua.com##+js(no-setTimeout-if, checkSiteNormalLoad)

That is not the rule referred to in https://github.com/uBlockOrigin/uAssets/issues/11837#issuecomment-1047659196

**Comment by uBlock-user** [comment]
> That is not the rule referred to in

`nostif` is an short-hand alias to `no-setTimeout-if`

**Comment by erosman** [comment]
> nostif is an short-hand alias to no-setTimeout-if

I see... I didnt know... thanks :+1:
