### ISSUE TITLE
oisd.nl: breakage

### ISSUE THREAD

**Issue by sjhgvr** [uBlockOrigin/uAssets#11833]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://oisd.nl/excludes.php?w=adzerk.net`

### Category

breakage

### Describe the issue

Links are being removed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

What it looks like with uBlock Enabled: https://i.imgur.com/o4dQrIZ.png
What it should look like: https://i.imgur.com/qHVeCso.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 41938
  cosmetic: 41388
  scriptlet: 16440
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  default: 
    easylist: 63806-9, 12h.51m
    ublock-abuse: 77-0, 12h.50m
    ublock-badware: 4008-75, 12h.49m
    ublock-filters: 30251-141, 12h.48m
    ublock-privacy: 199-1, 12h.47m
    ublock-unbreak: 1715-12, 12h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 47 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 296 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by uBlock-user** [comment]
@ryanbr
