### ISSUE TITLE
triplem.com.au: breakage

### ISSUE THREAD

**Issue by goofyhsk** [uBlockOrigin/uAssets#11835]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [x] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.triplem.com.au/adelaide`

### Category

breakage

### Describe the issue

Site is a radio stream;

During play a video ad auto plays, then stream resumes
With ublock enabled the video ad is blocked -- but the stream does not resume

triplem.com.au ⇒ adswizz.com

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 73721
  cosmetic: 36679
  scriptlet: 6628
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63858-9, 10h.8m
    easyprivacy: 26606-122, 10h.7m
    plowe-0: 3670-803, 10h.6m
    ublock-abuse: 77-0, 10h.4m
    ublock-badware: 4019-76, 10h.2m
    ublock-filters: 11491-32, 10h.1m
    ublock-privacy: 199-2, 10h
    ublock-unbreak: 1715-39, 9h.58m
    urlhaus-1: 6613-0, 9h.57m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1645 ms
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    adswizz.com: 9
    cloudflare.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    krxd.net: 1
    rubiconproject.com: 1
    sensic.net: 1
    split.io: 8
```
</details>

**Comment by mapx-** [comment]
What Chromium browser are you using ? brave, edge, chrome ? Did you disable the built-in blocker ?

I noted a strange thing: `ublock-filters: 11491-32, 10h.1m` => that list should have more than 30,000 records, just try updating it

**Comment by mapx-** [comment]
if still in trouble test this filter

`@@||cdn.adswizz.com/adswizz/js/SynchroClient*.js$script,domain=triplem.com.au`

**Comment by goofyhsk** [comment]
> What Chromium browser are you using ? brave, edge, chrome ? Did you disable the built-in blocker ?
> 
> I noted a strange thing: `ublock-filters: 11491-32, 10h.1m` => that list should have more than 30,000 records, just try updating it

Ugh, my bad, initially installed ubo on laptop - this issue is on desktop, I assumed it updated automatically
Chrome, Windows10

Confirmed issue still with updated lists
Trying that exception now
- Exception didn't fix it


uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79163
  cosmetic: 41184
  scriptlet: 16450
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63759-9, 1d.5h.5m
    easyprivacy: 26610-122, 1d.5h.4m
    plowe-0: 3670-803, 1d.5h.3m
    ublock-abuse: 77-0, 1d.5h.1m
    ublock-badware: 4019-83, 1d.4h.59m
    ublock-filters: 30263-151, 1d.4h.58m
    ublock-privacy: 199-2, 1d.4h.57m
    ublock-unbreak: 1715-39, 1d.4h.55m
    urlhaus-1: 7845-0, 1h.6m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 611 ms (selfie)
  maxAssetCacheWait: 225 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    adswizz.com: 16
    cloudflare.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    krxd.net: 1
    rubiconproject.com: 1
    sensic.net: 1
    split.io: 8

**Comment by goofyhsk** [comment]
I've added

@@||delivery-cdn-cf.adswizz.com/sca_newenco/$xmlhttprequest,domain=www.triplem.com.au

Seems to have fixed

**Comment by mapx-** [comment]
I was able to reproduce the interruption using an AUS IP .. but with the exception above do you get ads ?

**Comment by uBlock-user** [comment]
Instead of an exception, go with `##+js(no-xhr-if)` and/or `##+js(no-fetch-if)` ?

**Comment by mapx-** [comment]
It's a live stream, even catching those xhr .. what could happen ?

**Comment by mapx-** [comment]
@goofyhsk could you test this filter 
`triplem.com.au##+js(no-xhr-if, adswizz)`

**Comment by Fudger83** [comment]
I removed the other exceptions and added 
triplem.com.au##+js(no-xhr-if, adswizz)

The stream did pause, but did resume by itself after x amount

**Comment by goofyhsk** [comment]
I removed the other exceptions and added
triplem.com.au##+js(no-xhr-if, adswizz)

The stream did pause (audio stopped, stop button changed to play), but did resume by itself after x amount

**Comment by mapx-** [comment]
So, we could add the `no-xhr-if` filter or do you prefer listen those audio ads ?

**Comment by mapx-** [comment]
@ryanbr you could add the exception for other adblockers

`@@||delivery-cdn-cf.adswizz.com/sca_newenco/$xmlhttprequest,domain=triplem.com.au`
