### ISSUE TITLE
[nsfw] fyptt.to: ads

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11848]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fyptt.to/5682/tiktok-thot-wants-a-dick-for-her-birthday/`

### Category

ads

### Describe the issue

Ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220223-000337808 (1)](https://user-images.githubusercontent.com/56762704/155181802-45f8fd7e-1348-44f4-ae17-aef01b33b944.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium Mobile: 98
filterset (summary): 
  network: 61807
  cosmetic: 90478
  scriptlet: 22313
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1833-9, 1d.23h.42m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6055-963, 1d.23h.32m
    IDN-0: 9084-3772, 1d.23h.44m
    adguard-annoyance: 50428-1701, 1d.23h.31m
    fanboy-annoyance: 60289-32027, 8d.16h.14m
    ublock-annoyances: 4433-283, 1d.23h.40m
  default: 
    user-filters: 6-0, never
    adguard-mobile: 7235-41, 1d.23h.43m
    easylist: 63782-25135, 3d.1h.29m
    ublock-abuse: 77-0, 1d.23h.41m
    ublock-badware: 4008-75, 1d.23h.38m
    ublock-filters: 30347-803, 1d.23h.37m
    ublock-privacy: 199-9, 1d.23h.36m
    ublock-unbreak: 1722-20, 1d.23h.35m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1721 ms (selfie)
  maxAssetCacheWait: 642 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    jwpcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
- You should enable back at least easyprivacy list
- add

```
fyptt.to##.bottom-post-ad-space
fyptt.to##.top-post-ad
```

@ryanbr @Yuki2718
