### ISSUE TITLE
fakeporn.tv [Anti-Adblock] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1184]
URL(s) where the issue occurs

`https://www.fakeporn.tv/inked-babe-with-big-boobs-mila-milan-fucked-in-fake-taxi.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by okiehsch** [comment]
All I see is a broken site.
