### ISSUE TITLE
Issues with pop-ups with ads on a specific site

### ISSUE THREAD

**Issue by Tabithar** [uBlockOrigin/uAssets#11841]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tenies-online.best`

### Describe the issue

when i try to click on page always pop ups shows up with ads ..!!

### uBlock Origin version

1.41.6

### Browser name and version

Firefox browser 97.0.1 (64-bit)

### Settings

always on default everything

### Notes

i have tried to block pop-ups for this site from the menu its works only for one time after i re-open the browser setting is lost

**Comment by ghajini** [comment]
@mapx- 
popups here
`https://tenies-online.best/load/2-1-0-35490`

player2 ,tubeload.co 
`https://tubeload.co/e/3tutlhtjzsra/`
