### ISSUE TITLE
dez.ro

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#11852]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.dez.ro/dezmembrez-audi-a6-c6-3-0-diesel-quattro--7412696.html`

### Describe the issue

The images cannot be seen, as I attached on the screenshot below.

### Screenshot(s)

With uBlock:
![screen03](https://user-images.githubusercontent.com/79897301/155207971-0cbe2f00-2b8f-496e-9375-282892a73c78.jpg)

WIthout uBlock:
![screen04](https://user-images.githubusercontent.com/79897301/155207996-2d90c3f8-4bbb-4d7b-be32-77dbcbdac822.jpg)

### uBlock Origin version

1.41.8

### Browser name and version

FIrefox 97

### Settings

Default settings

**Comment by uBlock-user** [comment]
`dez.ro#@##ad-carousel`

@ryanbr

**Comment by mapx-** [comment]
@andreewmat  report the issues for romanian sites only here:
https://github.com/tcptomato/ROad-Block/issues
