### ISSUE TITLE
binance charts do not load when ublock is activated

### ISSUE THREAD

**Issue by mmeaht** [uBlockOrigin/uAssets#11855]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.binance.com/en/trade/BTC_USDT`

### Describe the issue

hello, ublock is blocking binance charts, i can't load the charts when ublock is activated...
error message: "Something is wrong with the chart"
`https://www.binance.com/en/trade/BTC_USDT`

### Screenshot(s)

![2022-02-22 215014](https://user-images.githubusercontent.com/100249812/155249486-d15f4cd6-c25b-48eb-8ef2-408100a2a371.jpg)

### uBlock Origin version

latest

### Browser name and version

brave/edge

### Settings

already tried to whitelist binance, the rest is default...

**Comment by Procyon-b** [comment]
It works for me. Can you post the content of "_Troubleshooting Information_" in the "_Support_" tab in ublock's dashboard?
