### ISSUE TITLE
streamingfast.io

### ISSUE THREAD

**Issue by errows** [uBlockOrigin/uAssets#11853]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://streamingfast.io`

### Describe the issue

This site could be risky
Advanced Security blocked access to http://streamingfast.io/
This site might compromise your device or contain high-risk content.

To avoid these risks, we recommend avoiding this site.

### uBlock Origin version

uBlock Origin 1.41.2

### Browser name and version

Chrome 98.0.4758.80

### Settings

none

**Comment by errows** [comment]
any guidance on what's invalid?
thanks

**Comment by uBlock-user** [comment]
Whats the issue ?

**Comment by errows** [comment]
Sorry 'bout that - you're 100% right - my provider was. Thanks for the help
