### ISSUE TITLE
primewire.vc - redirect issue for chromecast full screen only

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#11854]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

There have been changes how to report issues on github. Mr. Raymond Hill was kind enough
to respond to my initial report on this issue but used language in his response that I do not understand.
If this issue is again being reported in the wrong area, please don't just close the issue without providing 
a link for where I should report the issue. I am doing my best to follow the rules and I certainly hope
this report is in the correct space.

I did confirm that the issues does not exist when ubo is turned off.
ubo ver: 1.41.2
Chrome ver: 98.0.4758.102
osx ver: El Capitan 10.11.2

EXAMPLE:
Visit `https://www.primewire.vc/tv/1406668/watch-judy-justice-season-1-episode-53`
Choose VERSION 1 hyperlink on the page which opens up the link you want to show
Cast this page via chromecast to a TV
When the FULLSCREEN or double arrow option is selected after casting, website is redirected to GOOGLE home page.

Can anyone help me with this issue?

Thank you.
AD

### Describe the issue

EXAMPLE:
Visit `https://www.primewire.vc/tv/1406668/watch-judy-justice-season-1-episode-53`
Choose VERSION 1 hyperlink on the page which opens up the link you want to show
Cast this page via chromecast to a TV
When the FULLSCREEN or double arrow option is selected after casting, website is redirected to GOOGLE home page.

### uBlock Origin version

ubo ver: 1.41.2  

### Browser name and version

Chrome ver: 98.0.4758.102

### Settings

No changes

### Notes

osx ver: El Capitan 10.11.2

**Comment by gorhill** [comment]
You are making this difficult for volunteers -- there is no troubleshooting information in your report. I _already_ pointed out to you to use [the _"Report an issue on this website"_ button in the popup panel](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website) while on the website, this will automatically create a report filled with all the proper information.

**Comment by okiehsch** [comment]
> Choose VERSION 1 hyperlink on the page which opens up the link you want to show
Cast this page via chromecast to a TV...
osx ver: El Capitan 10.11.2`....

I can tell you that I can't reproduce on my PC running Windows or Linux.

**Comment by aldiener58** [comment]
Thank you for letting me know.
