### ISSUE TITLE
theverge.com: nuisance

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#11860]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theverge.com/2022/2/22/22945940/google-dark-mode-pitch-black-search`

### Category

nuisance

### Describe the issue

Empty space

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220223-183004348 (1)](https://user-images.githubusercontent.com/56762704/155311416-e2619ffe-a50a-4a04-9642-87cf4c78bb11.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium Mobile: 98
filterset (summary): 
  network: 61817
  cosmetic: 90813
  scriptlet: 22317
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus_adult.txt: 1833-9, 2d.18h.8m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6055-963, 2d.17h.59m
    IDN-0: 9084-3772, 2d.18h.10m
    adguard-annoyance: 50428-1701, 2d.17h.58m
    fanboy-annoyance: 60808-32197, 7h.36m
    ublock-annoyances: 4433-283, 2d.18h.6m
  default: 
    user-filters: 6-0, never
    adguard-mobile: 7235-41, 2d.18h.9m
    easylist: 63782-25135, 3d.19h.56m
    ublock-abuse: 77-0, 2d.18h.7m
    ublock-badware: 4008-75, 2d.18h.5m
    ublock-filters: 30347-803, 2d.18h.4m
    ublock-privacy: 199-9, 2d.18h.3m
    ublock-unbreak: 1722-20, 2d.18h.1m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4260 ms (selfie)
  maxAssetCacheWait: 3016 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    linkedin.com: 1
    moatads.com: 1
    outbrain.com: 1
    twitter.com: 1
    voxmedia.com: 1
```
</details>

**Comment by okiehsch** [comment]
We don't fix empty ad spaces here.

**Comment by uBlock-user** [comment]
Report to EasyList.
