### ISSUE TITLE
[nsfw] sport.galera.bet: popups

### ISSUE THREAD

**Issue by Ro0h** [uBlockOrigin/uAssets#11867]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sport.galera.bet/ndbgenericft1?btag=620109_l145865_nId1130_peyJ2aXNpdG9yX2lkIjoiNTIwNDE3MzQ4ODY4NjU3NDkyIn0=&AFFAGG`

### Category

popups

### Describe the issue

site opens automatically when I'm browsing and clicking on another page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 80002
  cosmetic: 43792
  scriptlet: 16639
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-1, never
    easylist: 63761-9, 14h.39m
    easyprivacy: 26610-122, 14h.34m
    plowe-0: 3673-804, 10d.13h.32m
    spa-1: 4240-77, 14h.40m
    ublock-abuse: 77-0, 2d.13h.41m
    ublock-badware: 4018-83, 2d.13h.40m
    ublock-filters: 30263-191, 14h.38m
    ublock-privacy: 199-2, 14h.37m
    ublock-unbreak: 1715-40, 14h.35m
    urlhaus-1: 7356-0, 1d.1h.38m
filterset (user): [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 370 ms (selfie)
  maxAssetCacheWait: 230 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by Ro0h** [comment]
site opens automatically when I'm browsing and clicking on another page.

**Comment by mapx-** [comment]
> clicking on another page

which page ?

**Comment by Ro0h** [comment]
Sorry if the communication is poor.
I don't speak English and I'm using translation tools
the page that we Brazilians use a lot is this one
https://futemax.gratis/
but whenever we need to adjust the volume or change the channel, enter a
new page in the advertisements tab like this
https://www.gearbest.com/promotion-bestseller-special-1308.html?lkid=45687009&cid=520467136528012221

https://futemax.gratis/

*Atenciosamente,*



*Rodrigo da Silva*





Tel.

Cel. 55 15 997911982




Em qua., 23 de fev. de 2022 às 15:48, mapx- ***@***.***>
escreveu:

**Comment by mapx-** [comment]
fixed in `uBlock filters` list, just update your lists
