### ISSUE TITLE
autofaucet.dutchycorp.space

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#11864]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
```

https://autofaucet.dutchycorp.space/coin_roll.php
https://autofaucet.dutchycorp.space/roll.php
```

### Describe the issue

on the above two pages, after entering the captcha, when you click on the BOOSTED ROLL button, a video should appear for you to watch and receive further rewards in coins ..... Please edit the filters for these two pages correctly, thanks in advance 

### uBlock Origin version

uBlock Origin 1.41.7b1

### Browser name and version

Firefox 97.0.1(64bit)

### Settings

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt

**Comment by mapx-** [comment]
@lyubomyrhv 
test
`*$subdocument,denyallow=facebook.com|google.com|hcaptcha.com|youtube.com|jungleofferwall.com,domain=dutchycorp.*,badfilter`

**Comment by lyubomyrhv** [comment]
https://cdn.playerserve.com/v1/log/js/1?id=1645638563354.1245&type=LOADED&placementId=fnCEbQYgYUgHLOrWvqxj1meGZH5whgILKE9puZ_X7jxghrMsc6PL&tagId=vVC8NvNNq4AQnCszqjaxjfaea0KvQNNM_3IkKb1gYGfmbDio5AhO&vtId=gvBmp-Qav53WQ6aKKZvJhuAagoLwYhCZuYC0PTo321Y2eFluDy35&message=&u=https%3A%2F%2Fautofaucet.dutchycorp.space%2Fcoin_roll.php&t=34644&v=102.1&width=1506&z=p%3Apl%3Bv%3Arewarded%3Bc%3Avast%3Bt%3Avideo%3B&r=0.4604733894615983

**Comment by lyubomyrhv** [comment]
I added cdn.playerserve.com to the code:
*$subdocument,denyallow=facebook.com|google.com|hcaptcha.com|youtube.com|jungleofferwall.com|cdn.playerserve.com,domain=dutchycorp.*,badfilter

But it did not help

**Comment by mapx-** [comment]
`@@||cdn.stat-rock.com/player.js$script,domain=autofaucet.dutchycorp.space`

should work

**Comment by lyubomyrhv** [comment]
thank you for the quick solution:)

**Comment by lyubomyrhv** [comment]
ok

**Comment by lyubomyrhv** [comment]
please take another look this site detects uBlock
https://www.softairbay.com

**Comment by mapx-** [comment]
I guess I need an account to get the anti adb, right ?
