### ISSUE TITLE
thedailywtf.com: breakage

### ISSUE THREAD

**Issue by kitswas** [uBlockOrigin/uAssets#11862]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [x] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://thedailywtf.com/articles/in-the-fullness-of-time`

### Category

breakage

### Describe the issue

An image is missing. 
Others have also mentioned this in the comments.

> Argle (unregistered) [2022-02-18](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1#comment-555850)
> [Reply](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1?parent=555850#comment-form)
> 
> The "advertisement" that I submitted was an image of a clearly marked advertisement that in turn was just obfuscated Javascript. It looks like I'm going to have to submit today's "Error'd" to Error'd. How meta is that?
>
> -----
>
> [Doodpants](https://what.thedailywtf.com/user/doodpants) (nodebb) [2022-02-18](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1#comment-555851)
> [Reply](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1?parent=555851#comment-form)
> 
> I can confirm that the first item is an ad, because it didn't show up until I disabled my ad blocker.
>
> -----
>
> Argle (unregistered) [in reply to Argle](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1#comment-555850) [2022-02-18](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1#comment-555852)
> [Reply](https://thedailywtf.com/articles/comments/in-the-fullness-of-time/1?parent=555852#comment-form)
> 
> Good grief! You're right. I submitted it as an image.It never dawned on me that my ad blocker would actually analyze an image that I created by screen capture.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![With uBlock on](https://user-images.githubusercontent.com/90329875/155323479-cad64408-6a29-404a-8f02-18fe1dc43147.png)

![With uBlock off](https://user-images.githubusercontent.com/90329875/155323667-ec7b29d7-9449-4ddb-a5e4-a7652010fd30.png)

![Comments](https://user-images.githubusercontent.com/90329875/155324137-002b07d4-f1e0-4d60-bcf3-d9c145bf6ef8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 78597
  cosmetic: 41197
  scriptlet: 16410
  html: 617
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30854-27, 22h.17m
    ublock-badware: 4023-3, 22h.16m
    ublock-privacy: 198-0, 22h.21m
    ublock-abuse: 77-0, 22h.20m
    ublock-unbreak: 1726-0, 22h.19m
    easylist: 63654-594, 22h.18m
    easyprivacy: 26609-570, 22h.22m
    urlhaus-1: 7356-0, 22h.15m
    plowe-0: 3675-2, 7d.6h.12m
filterset (user): [empty]
trustedset: 
  added: [array of 24 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2161 ms (selfie)
  maxAssetCacheWait: 1499 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
`@@||thedailywtf.com/images/*-advertisement.png$image,1p`
@ryanbr
