### ISSUE TITLE
AdBlock detection on prepostseo.com

### ISSUE THREAD

**Issue by feliciakri** [uBlockOrigin/uAssets#11868]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.prepostseo.com/calc/paypal-fee-calculator`

### Describe the issue

Click on `Calculate Fee` button, "Adblocker Detected" appears.

### Screenshot(s)

![Screenshot from 2022-02-24 01-49-26](https://user-images.githubusercontent.com/8079082/155387171-206ba559-01db-4f3f-9d59-251be0615ca8.png)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0

### Settings

None

### Notes

Looked up issue #10422, the site seem to already circumvented that fix.

## Steps I tried

**1. Element Picker**
Adding `www.prepostseo.com##.bg-dark` filter. The pop up disappears but the fee still doesn't show up. Clicking the button doesn't execute anything.
**2. Inline JS filtering**
I looked up the source code and the adblock detection seems to be triggered by an inline javascript `loadAdBlocker`. 

Followed the wiki for [inline script filtering](https://github.com/uBlockOrigin/uBlock-issues/wiki/Inline-script-tag-filtering).
Both of these filters cannot block the inline script:
`www.prepostseo.com/##^script:has-text(loadAdBlocker)`
`www.prepostseo.com/##^script:has-text(loadAdBlocker):remove()`

Followed the wiki for [static filter syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection).
This filter seems to work and shows the proper calculation:
`prepostseo.com##+js(acis, loadAdBlocker)`

![Screenshot from 2022-02-24 02-26-35](https://user-images.githubusercontent.com/8079082/155393271-c0073066-6690-4cc3-867f-16779dfe59a6.png)

**Comment by mapx-** [comment]
correct filter for firefox:

`prepostseo.com##^script:has-text(loadAdBlocker)`
