### ISSUE TITLE
coolors.co: ads

### ISSUE THREAD

**Issue by sbluca** [uBlockOrigin/uAssets#11869]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://coolors.co/`

### Category

ads

### Describe the issue

go to the palette generator. there are  at least 3 ads which cannot be hidden.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="585" alt="image" src="https://user-images.githubusercontent.com/89536510/155395364-69fcbe7c-b996-4a0f-a528-2c4b94a4ad5b.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/89536510/155395391-737ed6b5-aa77-4454-9307-3a5d4bb44a57.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/89536510/155395434-da74814c-cefa-4ab7-8114-4a85a211c13f.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 78481
  cosmetic: 41379
  scriptlet: 16400
  html: 617
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30824-27, 3d.14h.57m
    ublock-badware: 4006-3, 3d.14h.56m
    ublock-privacy: 202-0, 3d.14h.55m
    ublock-abuse: 77-0, 3d.14h.54m
    ublock-unbreak: 1727-0, 3d.14h.53m
    easylist: 63781-589, 3d.14h.52m
    easyprivacy: 26580-570, 3d.14h.50m
    urlhaus-1: 7356-0, 1d.55m
    plowe-0: 3670-2, 2d.19h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1296 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    buysellads.net: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add
```
coolors.co###header-cad
coolors.co###sticky-cad
```

or
`coolors.co##[href*="/ads/"]`

@ryanbr
