### ISSUE TITLE
vandal.elespanol.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#11874]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vandal.elespanol.com/analisis/videojuegos`

### Describe the issue

The number of blocks on this site in a matter of seconds does not seem normal

### uBlock Origin version

1.41.4

### Browser name and version

Chrome - 98.0.4

### Settings

![filt](https://user-images.githubusercontent.com/33556647/155423155-dfe8d9a5-362b-4cd3-b4a5-a9c15493aebf.PNG)

**Comment by Procyon-b** [comment]
In the regional list "_spa, por_" there are 2 exceptions that allow script from `sunmedia.tv` to load. They are the source of the problem.
You can try this filter to cancel this exception:
```
||sunmedia.tv^$important,domain=vandal.elespanol.com
```
Tell us if it breaks something on the site.

**Comment by PIZZA90** [comment]
Works OK

`Tell us if it breaks something on the site.`

only the footer video, maybe it is the cause of the problem..  look a Ad

**Comment by Procyon-b** [comment]
Use this filter instead:
```
||static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js*analisis*$important,script,domain=vandal.elespanol.com
```

**Comment by PIZZA90** [comment]
Perefect with that filter!

**Comment by PIZZA90** [comment]
but.. is working in *analisis* only

![2](https://user-images.githubusercontent.com/33556647/155427505-254993ee-2d6d-45e5-8413-ccea32d18a2c.PNG)

**Comment by Procyon-b** [comment]
Go it. Use this instead:
```
||static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js*videojuegos*$important,script,domain=vandal.elespanol.com
```

**Comment by PIZZA90** [comment]
😆😆😂😆😆😂

okok.. understood

**Comment by mapx-** [comment]
```
||static.sunmedia.tv/integrations/$script,domain=vandal.elespanol.com,important
vandal.elespanol.com##.cblanco.acenter.container > .row > .span12
```

@Yuki2718

**Comment by Procyon-b** [comment]
I've verified on more pages. Try this:
```
/static\.sunmedia\.tv/AdBlockDetection/adblockDetector\.min\.js.*(analisis|videojuegos|guias|foro)/$important,script,domain=vandal.elespanol.com
```

**Comment by Procyon-b** [comment]
@mapx- I'm trying to allow the vid at the bottom on the given url. It works if the `adblockDetector` is allowed when `iframevideo` is part of the url.

**Comment by PIZZA90** [comment]
just out of curiosity.. you can't access the **spa,por** list and remove the filters???

**Comment by Procyon-b** [comment]
I'm stupid (trying to use `important` instead of badfiltering). 
This is the final solution:
```
@@||static.sunmedia.tv/adblockdetection/adblockdetector.min.js^$badfilter,domain=vandal.elespanol.com
@@||static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js*iframevideo*$script,domain=vandal.elespanol.com
```

**Comment by Procyon-b** [comment]
@PIZZA90 In my last solution (shame on me not trying this first), I'm cancelling the filter in `spa,por ` and only allowing what displays the vid.

**Comment by PIZZA90** [comment]
**Procyon-b**

are you trolling me? out of curiousity

Because i have a own List of blocked users

**Comment by Procyon-b** [comment]
> are you trolling me? out of curiousity

Not at all. Maybe a misunderstanding. I mean that I can't modify the `spa,por` list. I can propose a pull request but it can be ignored. And it takes time for the user (you) to verify that it works.
I'm here and on reddit to help if I can. That's my way to participate in common goal.

**Comment by mapx-** [comment]
@Procyon-b it seem working your last filters if we consider the bottom video a normal one and not an add.

@Yuki2718 is able to add the filters to the regional list

**Comment by Yuki2718** [comment]
> if we consider the bottom video a normal one and not an add.

Which is it? Unbreak also has `@@||static.sunmedia.tv/integrations/$script,domain=api.gooru.live|elespanol.com|periodistadigital.tv`.

**Comment by Procyon-b** [comment]
Yes it's `Vídeo del momento` .
If `@@||static.sunmedia.tv/integrations/$script` isn't there, `static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js` isn't called, and the bottom video can't play. My first filter was an attempt to ignore the 2 exception filters. It worked but the video didn't show. I don't know why the exceptions where added. Maybe because of an anti-adblock function. But now the site works without them. If we disregard the bottom video, all pages with videos show them correctly.
We have 2 solutions: ditch the exceptions or limit the adblocker one to this `adblockDetector.min.js*iframevideo*$script`

**Comment by Yuki2718** [comment]
But is not playing on my side even with blocker disabled for whatever reason. Since I can't determin, am pinging @AdamWr

**Comment by PIZZA90** [comment]
similar footer page videos in other sites

```
https://www.3djuegos.com/
https://www.millenium.gg/
```

maybe is not ads.. I dont know

**Comment by Procyon-b** [comment]
This site is really badly designed. Without ublock, the video doesn't show (only a gray placeholder) and the page never stops loading the same frames and scripts.
As an old habit, I'm always running `task manager` minimized (+ `resource monitor`). I can see that the process is taking 100% cpu.

While writing this, and after 3-4min, the video finally shows up.

**Comment by AdamWr** [comment]
Okay, I have changed `@@||static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js^$domain=vandal.elespanol.com` to `@@||static.sunmedia.tv/AdBlockDetection/adblockDetector.min.js*iframevideo$domain=vandal.elespanol.com`
