### ISSUE TITLE
meteoblue.com: detection

### ISSUE THREAD

**Issue by p-p-s** [uBlockOrigin/uAssets#11871]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.meteoblue.com/de/user/account/index`

### Category

detection

### Describe the issue

Blures the actual content and puts a square in the center of the window asking to switch of the ad blocker or purchase a service.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 78986
  cosmetic: 41389
  scriptlet: 16440
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63803-9, 2d.11h.54m
    easyprivacy: 26606-122, 2d.11h.56m
    plowe-0: 3670-803, 1d.9m
    ublock-abuse: 77-0, 12h.7m
    ublock-badware: 4018-76, 2d.11h.59m
    ublock-filters: 30251-141, 2d.11h.58m
    ublock-privacy: 199-2, 2d.11h.55m
    ublock-unbreak: 1716-39, 2d.11h.57m
    urlhaus-1: 7819-0, 6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13960 ms
  maxAssetCacheWait: 6711 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    meteoblue.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Subscibe to the "_uBlock filters – Annoyances_" list in the "_Filter lists_" tab, under "_Annoyances_"

**Comment by Paredroi** [comment]
This fix has worked for some time now, but unfortunately, even though I have checked all the boxes in the section,

![grafik](https://github.com/uBlockOrigin/uAssets/assets/131969002/a7e429ca-bbfe-477a-bd8a-9f31df65b9c5)

the error has recently returned:

![grafik](https://github.com/uBlockOrigin/uAssets/assets/131969002/01e96de3-a5d8-48f5-8c0b-b2090f32ec57)

Link:
https://www.meteoblue.com/de/wetter/woche/berlin_deutschland_2950159

**Comment by stephenhawk8054** [comment]
You are ticking on `EasyList - Annoyances` lists.

The above comment said tick on `uBlock filters – Annoyances` list only.

**Comment by Paredroi** [comment]
My mistake, sorry!
Strangely enough, it's working again today. Hm, maybe it was just a faulty update of some list.
