### ISSUE TITLE
gearbest.com: ads

### ISSUE THREAD

**Issue by GoggieRene** [uBlockOrigin/uAssets#11873]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gearbest.com/promotion-bestseller-special-1308.html?lkid=45687009&cid=520481674442842818`

### Category

ads

### Describe the issue

I chose ublock because it filtered this ad particularly at first. After a few days, this ad is getting through again. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://user-images.githubusercontent.com/100321522/155421876-b9e58d68-4dff-43f0-9c63-3a77c2379404.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 79219
  cosmetic: 41218
  scriptlet: 16433
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 30873-27, 1m
    ublock-badware: 4029-3, 1m
    ublock-privacy: 198-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1727-0, 1m
    easylist: 63813-226, 1m
    easyprivacy: 26610-149, 1m
    urlhaus-1: 7845-0, 1m
    plowe-0: 3672-806, 1m
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2360 ms (selfie)
  maxAssetCacheWait: 586 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    gearbest.com: 1
    1talking.net: 1
    googletagmanager.com: 1
    logsss.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
gearbest.com##.goodsFloor
```

**Comment by GoggieRene** [comment]
Hey thanks, could you tell me how I am supposed to "try" your suggested filter? It's my first time.

**Comment by Procyon-b** [comment]
Open ublock's dashboard (click ublock's icon, then click the "gears" icon), in the dashboard, go to the "_My filters_" tab and paste the filter above in an empty line, then click "_Apply changes_". Reload the webpage to check.

**Comment by mapx-** [comment]
@ryanbr
