### ISSUE TITLE
modagamers.com: detection

### ISSUE THREAD

**Issue by Leonardo23092003** [uBlockOrigin/uAssets#11872]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://modagamers.com/`

### Category

detection

### Describe the issue

Detecta el Ad-block 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2022-02-23 193901](https://user-images.githubusercontent.com/100314291/155421225-11f2dde3-0584-4ae4-b991-b39fcd4728e2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 81971
  cosmetic: 45937
  scriptlet: 16628
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 63781-9, 3d.22h.36m
    easyprivacy: 26579-122, 3d.22h.35m
    plowe-0: 3670-803, 3d.22h.38m
    spa-0: 3792-29, 32m
    spa-1: 4240-165, 1d.2h.19m
    ublock-abuse: 77-0, 3d.22h.34m
    ublock-badware: 4008-76, 3d.22h.33m
    ublock-filters: 30250-198, 3d.22h.31m
    ublock-privacy: 203-2, 3d.22h.30m
    ublock-unbreak: 1716-40, 3d.22h.29m
    urlhaus-1: 7819-0, 31m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 318 ms (selfie)
  maxAssetCacheWait: 205 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    modagamers.com: 1
    adskeeper.com: 2
    arc.io: 1
    datadome.co: 1
    facebook.com: 2
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    onesignal.com: 1
    patreon.com: 2
    vlitag.com: 1
    wp.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||modagamers.com/wp-content/plugins/fgmjhu-hacvzsq/$script,1p
```

**Comment by Leonardo23092003** [comment]
thx

**Comment by Leonardo23092003** [comment]
Funciono por un rato , pero ya lo volvio a detectar

**Comment by mapx-** [comment]
home page, specific page / video ?

**Comment by Leonardo23092003** [comment]
https://modagamers.com/episodios/peak-of-true-martial-arts-episodio-20-sub-espanol/

**Comment by mapx-** [comment]
Still working fine on my side FF / chrome.

**Comment by Procyon-b** [comment]
I was waiting for your follow-up. Site is ok for me too. Tested on 2 computers.
