### ISSUE TITLE
thingiverse.com: breakage

### ISSUE THREAD

**Issue by sprasava** [uBlockOrigin/uAssets#11877]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thingiverse.com/`

### Category

breakage

### Describe the issue

If adblock is on the page (almost) loads, but then immediately goes to the error page. Can't find which part is the problem in the logger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/59937028/155476306-990cd4c4-cf88-45fe-b2f9-16d4aea9a21e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79198
  cosmetic: 41222
  scriptlet: 16473
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63834-9, 16m
    easyprivacy: 26617-122, 16m
    plowe-0: 3672-804, 16m
    ublock-abuse: 77-0, 16m
    ublock-badware: 4025-83, 16m
    ublock-filters: 30299-154, 16m
    ublock-privacy: 199-2, 16m
    ublock-unbreak: 1716-39, 16m
    urlhaus-1: 7819-0, 16m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 34 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 294 ms (selfie)
  maxAssetCacheWait: 621 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    thingiverse.com: 1
    amazon-adsystem.com: 1
    googletagmanager.com: 2
    uptime.com: 1
```
</details>

**Comment by uBlock-user** [comment]
Repro'd with Chromium.

**Comment by dalward** [comment]
I have the same issue

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79076
  cosmetic: 41184
  scriptlet: 16451
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63681-9, 2d.2h.50m
    easyprivacy: 26609-122, 2d.2h.49m
    plowe-0: 3670-803, 2d.2h.57m
    ublock-abuse: 77-0, 2d.2h.52m
    ublock-badware: 4019-76, 2d.2h.54m
    ublock-filters: 30266-144, 2d.2h.56m
    ublock-privacy: 199-2, 2d.2h.53m
    ublock-unbreak: 1719-39, 2d.2h.51m
    urlhaus-1: 7819-0, 23h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 73 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2922 ms
  maxAssetCacheWait: 1667 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    thingiverse.com: 1
    amazon-adsystem.com: 1
    doubleclick.net: 2
    google-analytics.com: 1


    googletagmanager.com: 2
    uptime.com: 1
```
</details>

![Screenshot at Feb 24 13-57-09](https://user-images.githubusercontent.com/8324588/155614418-96c6e342-fabe-48fd-94af-e823474b14da.png)

**Comment by dalward** [comment]
Purge and updating filter lists fixed this issue
