### ISSUE TITLE
cults3d.com: ads

### ISSUE THREAD

**Issue by sprasava** [uBlockOrigin/uAssets#11876]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cults3d.com/en`

### Category

ads

### Describe the issue

Residual ad banners. Says add in lower left corner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/59937028/155474294-cff096f6-9248-4eb2-8128-84543cb6840f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79086
  cosmetic: 41186
  scriptlet: 16450
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63691-9, 1d.7h.40m
    easyprivacy: 26609-122, 1d.7h.46m
    plowe-0: 3675-804, 6d.13h.22m
    ublock-abuse: 77-0, 1d.7h.45m
    ublock-badware: 4019-76, 1d.7h.44m
    ublock-filters: 30263-144, 1d.7h.43m
    ublock-privacy: 199-2, 1d.7h.42m
    ublock-unbreak: 1719-39, 1d.7h.41m
    urlhaus-1: 7819-0, 8h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 34 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 294 ms (selfie)
  maxAssetCacheWait: 621 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    cults3d.com: 1
    carbonads.com: 8
    google-analytics.com: 8
    googlesyndication.com: 3
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
add

`cults3d.com##div.grid-cell:has-text(/AD •/i)`

@ryanbr
