### ISSUE TITLE
anilibria.tv: breakage

### ISSUE THREAD

**Issue by kraev-sv** [uBlockOrigin/uAssets#11870]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.anilibria.tv/`

### Category

breakage

### Describe the issue

Раньше на странице убиралась лишняя реклама и различный ролики перед просмотром.
Теперь внешний вид при включенном ublock  похож на хрен знает что.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 97088
  cosmetic: 62983
  scriptlet: 18033
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41476-9, 1d.15h.1m
    easylist: 63789-21, 3d.55m
    easyprivacy: 26597-217, 3d.54m
    plowe-0: 3673-809, 8d.15h.2m
    ublock-abuse: 77-1, 2d.11h.38m
    ublock-badware: 4018-76, 2d.8h.16m
    ublock-filters: 30251-172, 2d.7h.29m
    ublock-privacy: 199-2, 2d.7h.28m
    ublock-unbreak: 1719-39, 2d.7h.27m
    urlhaus-1: 7845-0, 12h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms (selfie)
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    digitalcaramel.com: 1
    googletagmanager.com: 1
    jsdelivr.net: 1
    static.anilibria.tv: 2
    utarget.ru: 1
    yandex.ru: 3
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2002

**Comment by dimisa-RUAdList** [comment]
> ```yaml
>     RUS-0: 41476-9, 1d.15h.1m
> ```
Fix: https://github.com/easylist/ruadlist/commit/53d39cb6349f86a1517498fda943fc37910508e1
