### ISSUE TITLE
White space on techradar.com

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#11881]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`techradar.com`
example: `https://www.techradar.com/news/chrome-is-making-it-easier-to-remember-passwords-and-sensitive-information`

### Describe the issue

As you can see in the screenshot above the article is a big white space. 

I propose:  
```
techradar.com##.dfp-leaderboard-container
```

### Screenshot(s)

<details> <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/81161435/155535597-a254d2c7-92f8-4bd9-aada-1d2c41973ff0.png)

</details>

### uBlock Origin version

1.41.2

### Browser name and version

MS Edge 98

### Settings

<details><summary> Troubleshoot Information</summary>

```
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 67331
  cosmetic: 43185
  scriptlet: 16536
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2995-10, 6h.55m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1953-0, 6h.55m
  default: 
    user-filters: 213-0, never
    ublock-filters: 30271-90, 6h.50m
    ublock-unbreak: 1715-10, 6h.49m
    easylist: 63834-164, 6h.48m
    easyprivacy: 26617-193, 6h.47m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  uiAccentCustom: true
  uiAccentCustom0: #312a65
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 15468 ms
  maxAssetCacheWait: 1587 ms
```

</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/155537856-cce63e32-6335-468c-bd84-d29aba89204d.png)

As you can see that whitespace is already covered by an EasyList filter on my end.

**Comment by uBlock-user** [comment]
> * [X] uBO with default lists/settings

Doesn't happen on default settings/lists.

**Comment by JohnyP36** [comment]
I solved it: 

It's because of `Fanboy's Enhanced Tracking`

![image](https://user-images.githubusercontent.com/81161435/155540488-ad5a8beb-103c-4d67-8998-4fc74d879ebb.png)
