### ISSUE TITLE
thingiverse.com: detection

### ISSUE THREAD

**Issue by BasTossings** [uBlockOrigin/uAssets#11888]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thingiverse.com/`

### Category

detection

### Describe the issue

Site does not load at all with uBlock origin enabled. It just displays `Something went wrong.`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79983
  cosmetic: 42551
  scriptlet: 16463
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 9-0, never
    NLD-0: 2083-12, 1d.13h.7m
    easylist: 63766-10, 1d.13h.6m
    easyprivacy: 26610-122, 1d.13h.8m
    plowe-0: 3670-803, 1d.13h.14m
    ublock-abuse: 77-0, 1d.13h.11m
    ublock-badware: 4019-83, 1d.13h.9m
    ublock-filters: 30260-195, 1d.13h.12m
    ublock-privacy: 199-2, 1d.13h.10m
    ublock-unbreak: 1715-53, 1d.13h.5m
    urlhaus-1: 8023-1, 5h.46m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 128 ms (selfie)
  maxAssetCacheWait: 73 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    thingiverse.com: 1
    amazon-adsystem.com: 1
    datadoghq.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 2
    uptime.com: 1
```
</details>

**Comment by gwarser** [comment]
Purge and update filter lists.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11877

**Comment by Nicras** [comment]
Hello, 

I purged and updated filter lists which makes thingiverse accessible again but when trying to download a file it asks to disable adblocker.
