### ISSUE TITLE
pathfinderwrathoftherighteous.wiki.fextralife.com: nuisance

### ISSUE THREAD

**Issue by Sevrin** [uBlockOrigin/uAssets#11883]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pathfinderwrathoftherighteous.wiki.fextralife.com/Endings`

### Category

nuisance

### Describe the issue

An embedded twitch streaming video always plays and can't be removed. Using the element zapper removes it once but if you refresh the page it's back. It'll stream on every page you have open, so if you have 5 tabs? that's 5 streams open. This is across the entire wiki and probably Fextralife's other wikis. They say you can remove the auto streaming if you pay them money. Which means they know people hate it. Assholes.
Please do something about this. Thanks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.6
Firefox: 97
filterset (summary): 
  network: 79377
  cosmetic: 41223
  scriptlet: 16429
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30866-27, 11h.20m
    ublock-badware: 4029-3, 11h.21m
    ublock-privacy: 198-0, 11h.25m
    ublock-abuse: 77-0, 2d.15h.47m
    ublock-unbreak: 1726-0, 11h.23m
    easylist: 63833-610, 11h.24m
    easyprivacy: 26616-128, 11h.22m
    urlhaus-1: 8000-1, 11h.19m
    plowe-0: 3670-444, 3d.14h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 266 ms (selfie)
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    addthis.com: 1
    cloudflareinsights.com: 3
    countess.twitch.tv: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    enthusiastgaming.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    imrworldwide.com: 1
    scorecardresearch.com: 2
```
</details>

**Comment by Sevrin** [comment]
Also I just wanna say, while this doesn't fit super well with the valid filter list, it is malicious action against the sites users. If you have to pay to remove a "feature" it's malicious.

**Comment by mapx-** [comment]
@ryanbr

**Comment by Sevrin** [comment]
This was closed without being fixed?

**Comment by uBlock-user** [comment]
This is an Annoyance and to be fixed in Fanboy's Annoyances list as this doesn't require uBO syntax.
