### ISSUE TITLE
xgirls.webcam [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#11886]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

xgirls.webcam

### Describe the issue

popups when pressing play on videos.

### uBlock Origin version

1.41.4

### Browser name and version

Chrome v98

### Settings

Default

**Comment by Procyon-b** [comment]
Try this filter:
```
xgirls.webcam###kt_player>a[target="_blank"]
```

**Comment by Procyon-b** [comment]
@mapx- you forgot the hostname in the filter.

**Comment by mapx-** [comment]
No, because I found other cases, so it's ok generic (they modified `flashvars` randomly so the classic `##+js(set, flashvars.popunder_url, '')` does not work anymore on some pages)

**Comment by Yuki2718** [comment]
@gorhill Is `###kt_player>a[target="_blank"]` still high-generic as in https://github.com/gorhill/uBlock/issues/909#issuecomment-154053169 and may be discarded by https://github.com/uBlockOrigin/uBlock-issues/discussions/1998 ?

**Comment by uBlock-user** [comment]
> ##+js(set, flashvars.popunder_url, '')

So try `##+js(nowoif)` ?

**Comment by uBlock-user** [comment]
`jizzoncam.com##+js(nowoif)` works.

**Comment by Yuki2718** [comment]
If a generic cosmetic filter works fine, I prefer this. Only concern is it may be discarded in future.

**Comment by gorhill** [comment]
> `###kt_player>a[target="_blank"]` still high-generic

No it's not -- it has `#kt_player` in it, which makes it a lowly generic.

**Comment by gorhill** [comment]
By the way, I personally would prefer we surround combinators with spaces, i.e.

    ###kt_player > a[target="_blank"]

This visually makes it easier to spot that it is a lowly generic, and also makes it easier to create search expression to find specific cosmetic filters such as complex ones, or lowly generic ones when I try to analyze content of lists.

**Comment by Yuki2718** [comment]
@gorhill Done https://github.com/uBlockOrigin/uAssets/commit/bb90f17b3a7a13cae12c30879d38188afe6ba588
