### ISSUE TITLE
streamingcommunity.site: detection

### ISSUE THREAD

**Issue by zizzooo** [uBlockOrigin/uAssets#11892]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamingcommunity.site/watch/4314`

### Category

detection

### Describe the issue

ubo is detected

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 156792
  cosmetic: 193093
  scriptlet: 33238
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50404-156, 5m
    adguard-generic: 61928-693, 5m
    adguard-mobile: 7255-45, 5m
    adguard-social: 15905-777, 5m
    adguard-spyware: 25687-1001, 5m
    adguard-spyware-url: 491-12, 5m
    block-lan: 44-0, 5m
    curben-phishing: 11351-0, 4m
    curben-pup: 397-0, 4m
    dpollock-0: 10346-224, 4m
    fanboy-annoyance: 65050-7953, 4m
    fanboy-cookiemonster: 22573-22573, 4m
    fanboy-social: 23173-23173, 4m
    fanboy-thirdparty_social: 68-21, 4m
    mvps-0: 8730-1719, 4m
    ublock-annoyances: 4410-292, 4m
  default: 
    user-filters: 0-0, never
    ITA-0: 12840-0, 2h.30m
    easylist: 63880-1212, 2h.30m
    easyprivacy: 26618-10682, 2h.30m
    plowe-0: 3673-1487, 2h.30m
    ublock-abuse: 77-0, 2h.30m
    ublock-badware: 4025-258, 2h.30m
    ublock-filters: 30301-3395, 2h.30m
    ublock-privacy: 200-40, 2h.30m
    ublock-unbreak: 1718-113, 7m
    urlhaus-1: 8000-6, 2h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1224 ms
  maxAssetCacheWait: 720 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
||googletagmanager.com^$xhr,domain=streamingcommunity.site,redirect-rule=noop.js
```

**Comment by uBlock-user** [comment]
@Procyon-b Does that even work for you ?

**Comment by uBlock-user** [comment]
@Procyon-b CORS violation won't allow to load `noop.js` on Firefox. Works fine on Chrome.

**Comment by uBlock-user** [comment]
@gorhill Can something be done about this to avoid CORS violation on Firefox ?

**Comment by gwarser** [comment]
`no-xhr-if`?

**Comment by mapx-** [comment]
It does not work

**Comment by mapx-** [comment]
only the exception
`@@||googletagmanager.com/gtag/js$xhr,domain=streamingcommunity.site`

**Comment by uBlock-user** [comment]
@gwarser player won't initialise for some reason.
