### ISSUE TITLE
welt.de: breakage

### ISSUE THREAD

**Issue by Isolator70** [uBlockOrigin/uAssets#11894]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.welt.de/politik/deutschland/article237135657/Ex-Nato-General-zu-Ukraine-Konflikt-Bundeswehr-nicht-in-der-Lage-Deutschland-zu-verteidigen.html`

### Category

breakage

### Describe the issue

Video will not start with uBlockOrigin active. The loading/activation "donut" is rotating endless, the "play" button remains inactive. If uBlockOrigin is deactivated and page was reloaded, it will become playable instantly.
As far as I remember, this is NOT a permanent issue, but can be observed since some days.
I have also installed DDGPrivacy essentials, but it makes no difference if I deactivate it - video is still broken.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 81514
  cosmetic: 44597
  scriptlet: 16404
  html: 617
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30839-36, 2d.19h.1m
    ublock-badware: 4029-3, 19h.48m
    ublock-privacy: 198-0, 19h.44m
    ublock-abuse: 77-0, 19h.47m
    ublock-unbreak: 1728-0, 19h.46m
    easylist: 63846-616, 19h.49m
    easyprivacy: 26616-581, 19h.45m
    plowe-0: 3673-2, 11d.3h.15m
    DEU-0: 5499-2, 14h.28m
    urlhaus-1: 8023-1, 14h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1063 ms (selfie)
  maxAssetCacheWait: 736 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    adnxs.com: 1
    asadcdn.com: 2
    ioam.de: 1
    iocnt.net: 1
    nmrodam.com: 1
    vgwort.de: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
`welt.de##+js(abort-on-property-read, funkotron.config.switches.StickyVideoRewrite)` is the breaking filter and need to be replaced
