### ISSUE TITLE
putlockers.li: ads

### ISSUE THREAD

**Issue by DIW79** [uBlockOrigin/uAssets#11890]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://putlockers.li/tv-show/1883-2021_T3hISkQwMm84UFE9/S01E01/watch.html`

### Category

ads

### Describe the issue

Simply: when using uBlock Origin on this page I still receive popup ads in the top right corner of the page. There is a "x" icon on the left of these and you can close them manually, but they still appear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-02-24 at 23 19 33](https://user-images.githubusercontent.com/36888993/155623962-74f31aaa-aec0-4493-b9b5-6e39095d0875.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79280
  cosmetic: 41195
  scriptlet: 16381
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63880-9, 7m
    easyprivacy: 26618-121, 6m
    plowe-0: 3673-804, 5m
    ublock-abuse: 77-0, 3m
    ublock-badware: 3738-76, never
    ublock-filters: 30169-163, never
    ublock-privacy: 194-2, never
    ublock-unbreak: 1704-39, never
    urlhaus-1: 8168-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2019 ms
  maxAssetCacheWait: 1045 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
putlockers.li##+js(acis, JSON.parse, atob)
```

**Comment by DIW79** [comment]
@Procyon-b Hi again :) I wish I had visited here before now to say thank you for your help earlier in the year.
However, the issue has morphed somewhat: now putlockers.li opens a new tab with their advertising content in it whenever you select a movie to play.

@mapx- do I need to open a new issue for this? If so I will delete this and open a new one. Apologies if I've caused any annoyance.

**Comment by mapx-** [comment]
Today it was added a fix for pp sites, update the lists and test again

**Comment by DIW79** [comment]
Thanks @mapx-
