### ISSUE TITLE
serasaexperian.com.br: breakage

### ISSUE THREAD

**Issue by asdcarvalho** [uBlockOrigin/uAssets#11895]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.serasaexperian.com.br/`

### Category

breakage

### Describe the issue

When clicking the "Entrar" button that should open a login popup, nothing happens. With uBlock Origin off, it works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 80651
  cosmetic: 43807
  scriptlet: 16635
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63767-9, 1d.23h.45m
    easyprivacy: 26609-122, 1d.23h.44m
    plowe-0: 3670-803, 1d.23h.54m
    spa-1: 4241-77, 1d.23h.46m
    ublock-abuse: 77-0, 1d.23h.43m
    ublock-badware: 4019-83, 1d.13h.28m
    ublock-filters: 30278-191, 1d.23h.48m
    ublock-privacy: 199-2, 1d.23h.49m
    ublock-unbreak: 1715-40, 1d.23h.47m
    urlhaus-1: 8000-1, 23h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 310 ms (selfie)
  maxAssetCacheWait: 176 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    serasaexperian.com.br: 1
    adobedtm.com: 2
    demdex.net: 1
    facebook.net: 1
    globalsiteanalytics.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 3
    ipify.org: 1
    licdn.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||serasaexperian.com.br/dist/scripts/fingerprint2.js$script,1p`

EP issue @ryanbr
