### ISSUE TITLE
Facebook filters do not work on www.facebookcorewwwi.onion/

### ISSUE THREAD

**Issue by mark-otaris** [uBlockOrigin/uAssets#119]
### URL(s) where the issue occurs

https://www.facebookcorewwwi.onion/, news feed and most pages.
### Describe the issue

Facebook runs a Tor hidden service at https://www.facebookcorewwwi.onion/. The [two filters](https://github.com/uBlockOrigin/uAssets/blob/1400295a9b3ddd01ece852617e2e1afdc7af160c/filters/filters.txt#L591) targeting the Facebook website in `filters/filters.txt` have `facebook.com` hardcoded, so they do not work when the hidden service is used.
### Screenshot(s)

![People You May Know box, with names customized and images removed](https://clbin.com/nYCSZR.png)
### Versions
- Browser/version: Firefox 48.0.1
- uBlock Origin version: 1.9.2
### Settings
- Advanced mode, blocking most third party requests, no custom filters that should target facebookcorewwwi.onion.
### Notes

The filters are simple cosmetic filters, so making them apply on www.facebookcorewwwi.onion should be sufficient.

**Comment by lewisje** [comment]
Maybe using the `facebookcorewwwi.onion` domain instead would be better.

**Comment by gorhill** [comment]
Can you confirm these work?

    facebook.com,facebookcorewwwi.onion###stream_pagelet div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)
    facebook.com,facebookcorewwwi.onion##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//h6//span/text()="People You May Know"])

**Comment by mark-otaris** [comment]
They work for the People You May Know box. I don't have sponsored posts to check if the other filter works, though it is unlikely it doesn't.
