### ISSUE TITLE
GMail (mail.google.com): breakage

### ISSUE THREAD

**Issue by balent** [uBlockOrigin/uAssets#11906]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://mail.google.com/mail/u/0/

### Describe the issue

When I open any email the content is missing.

### Screenshot(s)

![GmailScreenshot](https://user-images.githubusercontent.com/802386/155795746-d12615ad-4a31-41e2-be62-94c15a5b278a.png)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0.1 

### Settings

No changes.

### Notes

If I disable the `ublock filters` then I can see the content of the email again.

**Comment by gbeaudoin78** [comment]
Thanks you Robert for reporting the problem with such details, I was about to fill a similar issue because I have the same issue and I'm in Canada as well. The hostname mail.google.com currently resolve to 172.217.13.101 and 2607:f8b0:4020:804::2005 for me.

**Comment by singularity2022** [comment]
have the same issue, help!

**Comment by mapx-** [comment]
It was fixed, update all filter lists

**Comment by singularity2022** [comment]
yay it's working now. thank you!

**Comment by nekromoff** [comment]
I have updated all filter lists, still pending breakage for Unbreak filter.

**Comment by troubageoff** [comment]
Même problème pour moi. Une façon de le régler ? Merci d'avance...

**Comment by mapx-** [comment]
update all filter lists

**Comment by Photon89** [comment]
Thanks, updating the filter lists helped! I wonder, what is the default auto update interval? I had the issue for half a day before I decided to file a bug report (but found this one instead).

**Comment by slowtokyo** [comment]
Note you may have to `uBlock settings => Filter lists => click purge all caches => update now` in order to force update the filter lists.

**Comment by uBlock-user** [comment]
> what is the default auto update interval

! Expires: 4 days

for uBlock filters list.

**Comment by gwarser** [comment]
[uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [Filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) -> click on the clock icon at the end of "uBlock filters" list name -> click on "Update now" on top.

Alternatively click on "Purge all caches" -> "Update now"

https://user-images.githubusercontent.com/886325/156082973-4b1ba8f2-5c40-4a5b-aafc-dfb5ba353c13.mp4

**Comment by SharpFolf** [comment]
Updating filter lists worked! Thank you :)

**Comment by u-RraaLL** [comment]
Weird thing is I was only affected today. Not sure how this happened 5 days after the fix, when the list updates every 4 days.
