### ISSUE TITLE
Not blocking ads.

### ISSUE THREAD

**Issue by ZekePolarisBSH** [uBlockOrigin/uAssets#11908]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

All sites I go to.

### Describe the issue

Already explained but found out that you guys don't support users from there.

### uBlock Origin version

Latest, stays up to date as I said before.

### Browser name and version

Latest, stays up to date as I said before.

### Settings

Nothing? I keep the settings the same.

### Notes

It happens every time so Idk what to do.

**Comment by uBlock-user** [comment]
Reset uBO to default settings and disable all other extensions.

**Comment by iam-py-test** [comment]
Specific URLs? Screenshots?
Try going to somewhere which never has ads (i.e. https://example.com) and if you see ads, you have some malware on your device
