### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Kingismail33** [uBlockOrigin/uAssets#11911]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=tvZRSrf7rfs`

### Category

REKLAM

### Describe the issue

bir videoyu açtığım zaman ilk önce reklam çıkıyor
ardından bir daha çıkmıyor fakat ilk açtığımda da reklam çıkmasın istiyorum efendim. teşekkürler...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 81234
  cosmetic: 47463
  scriptlet: 16782
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8559-78, 3d.13h.15m
    easylist: 63681-25, 3d.13h.14m
    easyprivacy: 26609-127, 3d.13h.13m
    plowe-0: 3673-805, 12d.13h.16m
    ublock-abuse: 77-0, 3d.13h.21m
    ublock-badware: 4019-76, 3d.13h.20m
    ublock-filters: 30263-155, 3d.13h.19m
    ublock-privacy: 199-2, 3d.13h.18m
    ublock-unbreak: 1719-39, 3d.13h.16m
    urlhaus-1: 8141-1, 22h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4267 ms (selfie)
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 355
  blockedDetails: 
    youtube.com: 299
    doubleclick.net: 11
    google.com: 2
    google.com.tr: 1
    googleadservices.com: 2
    googlesyndication.com: 30
    googlevideo.com: 10
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
