### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by Led371** [uBlockOrigin/uAssets#11916]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

Emails are unable to be read when uBlock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 80349
  cosmetic: 41275
  scriptlet: 16510
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1034-0, 1d.13h.57m
  default: 
    user-filters: 9-1, never
    easylist: 63961-18, 2h.21m
    easyprivacy: 26621-447, 15h.12m
    plowe-0: 3673-805, 1d.9h.56m
    ublock-abuse: 77-4, 15h.14m
    ublock-badware: 4025-83, 15h.11m
    ublock-filters: 30335-158, 2h.20m
    ublock-privacy: 202-2, 15h.15m
    ublock-unbreak: 1718-39, 15h.13m
    urlhaus-1: 8190-1, 15h.10m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms (selfie)
  maxAssetCacheWait: 84 ms
popupPanel: 
  blocked: 415
  blockedDetails: 
    google.com: 406
    googleusercontent.com: 9
```
</details>

**Comment by gwarser** [comment]
Go to uBO Dashboard -> Filter lists -> Purge all caches -> Update now.
