### ISSUE TITLE
poczta.interia.pl: breakage

### ISSUE THREAD

**Issue by genuinejanbar** [uBlockOrigin/uAssets#11912]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poczta.interia.pl/`

### Category

breakage

### Describe the issue

When I click "Pokaż obrazki" then all that empty places should show images but it's not working now. A couple of weeks ago it WAS working. So, it looks like an update makes something wrong, or now it can be set in a settings section but I don't know where exactly... . So, anyone who wants to look into that problem should make a new account on https://poczta.interia.pl and get any newsletter with images and next try to unblock images by clicking "Pokaż obrazki".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 80988
  cosmetic: 48631
  scriptlet: 16639
  html: 629
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-0, never
    ublock-filters: 30884-33, 17h.9m
    ublock-badware: 4029-3, 17h.7m
    ublock-privacy: 199-0, 17h.6m
    ublock-abuse: 77-0, 17h.5m
    ublock-unbreak: 1729-0, 17h.4m
    easylist: 63931-229, 17h.3m
    easyprivacy: 26620-149, 17h.2m
    urlhaus-1: 8141-1, 13h.1m
    plowe-0: 3674-806, 10d.20h
    POL-0: 7777-49, 13h
    POL-2: 1276-46, 2m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8368 ms (selfie)
  maxAssetCacheWait: 2451 ms
popupPanel: 
  blocked: 32
  no-cosmetic-filtering: true
  blockedDetails: 
    interia.pl: 20
    gemius.pl: 1
    google-analytics.com: 1
    hub.com.pl: 6
    iplsc.com: 4
```
</details>

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by genuinejanbar** [comment]
![obraz](https://user-images.githubusercontent.com/100475706/155891001-e80579e4-b67f-4f9a-96e9-998102c9472a.png)
 That happened when I clicked "Pokaż obrazki" in your mail.

**Comment by genuinejanbar** [comment]
Here is all that link: https://iwa.hit.interia.pl/1/hit.t?vid=075d2891-67c0-44a0-8af8-333e9b7f6d81&p=1645979414107&t=event&sh=poczta.interia.pl&dt=Poczta%20w%20Interii%20(9)&dp=%2Fnext%2F%3Fuid%3D9498daf11f004e41%23%2Ffolder%2F1%2Fmessage%2F101514&dh=poczta.interia.pl&dl=https%3A%2F%2Fpoczta.interia.pl%2Fnext%2F%3Fuid%3D9498daf11f004e41%23%2Ffolder%2F1%2Fmessage%2F101514&dr=&de=UTF-8&df=0&bt=-60&br=1366x768&bo=24&bd=1&bv=1366x643&bc=1&bl=pl&bj=0&bf=0.0.0&bs=&bp=&bw=&v=1.1.127&cv=gen_sUID%3D0&ec=ec0%3Dnext%26ec1%3Dodebrane%26ec2%3DOtwarty_mail%26ec3%3Dklik%26ec4%3DPokaz_obrazki&we=30afc08afe443d1eddab224b39a5a240f43482c3&mt=1645979469588

**Comment by mapx-** [comment]
`||hit.interia.pl^`

EP issue @ryanbr
