### ISSUE TITLE
[nsfw] www1-sonicolors.com: privacy

### ISSUE THREAD

**Issue by jaykeizz** [uBlockOrigin/uAssets#11925]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www1-sonicolors.com/download/`

### Category

privacy

### Describe the issue

fishing website 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79498
  cosmetic: 41267
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63945-9, 21h.13m
    easyprivacy: 26624-122, 21h.12m
    plowe-0: 3673-805, 21h.11m
    ublock-abuse: 77-0, 21h.8m
    ublock-badware: 3863-83, 21h.6m
    ublock-filters: 30324-161, 21h.5m
    ublock-privacy: 202-2, 21h.4m
    ublock-unbreak: 1718-39, 18h.34m
    urlhaus-1: 8190-1, 18h.33m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms (selfie)
  maxAssetCacheWait: 312 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
What's the issue ?

**Comment by JobcenterTycoon** [comment]
Looks like he mean its a fake site

`v1-sonicolors.com`
`www1-sonicolors.com`

but on VT only 2 programs flag the file. The file coming from `https://www5.s4-download-games.com/sn/Sonic%20Colors%20Ultimate.zip`
