### ISSUE TITLE
ingles.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#11920]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.ingles.com/`

`https://www.ingles.com/guia/vocabulario-del-aeropuerto`

### Describe the issue

Anti adblocker

### uBlock Origin version

1.41.4

### Browser name and version

Chrome - 98.0.4

### Settings

![filt](https://user-images.githubusercontent.com/33556647/155859151-7cf3e8fa-02cf-46c1-af84-5aa8f7859a67.PNG)

**Comment by PIZZA90** [comment]
also: `https://www.spanishdict.com/guide/family-tree-in-spanish`

**Comment by PerfectSalad** [comment]
Is there a working view limiter for ad-blocking-detected users?
