### ISSUE TITLE
ww1.123watchmovies.co: popups

### ISSUE THREAD

**Issue by aple1** [uBlockOrigin/uAssets#11924]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ww1.123watchmovies.co/episode/euphoria-season-2-episode-6/`

### Category

popups

### Describe the issue

Every time I click any part of the website page after more than about 10 seconds between each click, it will attempt to open another tab or window.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79605
  cosmetic: 41238
  scriptlet: 16472
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63880-9, 2d.6h.36m
    easyprivacy: 26618-121, 2d.6h.35m
    plowe-0: 3673-804, 1d.21h.16m
    ublock-abuse: 77-0, 2d.6h.34m
    ublock-badware: 4025-83, 2d.6h.29m
    ublock-filters: 30301-155, 2d.6h.32m
    ublock-privacy: 200-2, 2d.6h.31m
    ublock-unbreak: 1718-39, 2d.6h.30m
    urlhaus-1: 8190-1, 22h.27m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11689 ms (selfie)
  maxAssetCacheWait: 5382 ms
popupPanel: 
  blocked: 65
  blockedDetails: 
    adsco.re: 3
    barscreative1.com: 2
    blockadsnot.com: 1
    chooxaur.com: 1
    clarity.ms: 4
    crwdcntrl.net: 2
    dismantlepenantiterrorist.com: 4
    dnhfi5nn2dt67.cloudfront.net: 1
    dood.la: 1
    dozubatan.com: 13
    fadingamendable.com: 2
    histats.com: 1
    ndollarhe.com: 7
    pawnoutletprimary.com: 1
    predictiondexchange.com: 1
    s-onetag.com: 2
    sweetskojiki.com: 1
    tacticmarshannouncing.com: 2
    toglooman.com: 2
    vcbnmnb.xyz: 1
    venetrigni.com: 2
    vrsshsdaa.com: 1
    waisheph.com: 9
    whsrdsweq.com: 1
```
</details>

**Comment by mapx-** [comment]
no popups, only broken player

`@@||gomoplayer.com/embed-$frame,domain=gomo.to`

EL maintainer notified @ryanbr

**Comment by mapx-** [comment]
breakage fixed https://github.com/easylist/easylist/commit/0ed9c738af58368b4f08b3866ed7e267170d0d31
