### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by esponapule** [uBlockOrigin/uAssets#11923]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

Breaks the window (see screenshot)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="576" alt="MCkHTUr9LM" src="https://user-images.githubusercontent.com/3163504/155861775-aa921c15-b98d-4bd0-bfd6-2c97fc208444.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 71831
  cosmetic: 41269
  scriptlet: 16456
  html: 619
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30906-157, 2h.57m
    ublock-badware: 4029-3, 2h.56m
    ublock-privacy: 202-0, 2h.55m
    ublock-abuse: 77-0, 2h.54m
    ublock-unbreak: 1729-0, 2h.53m
    easylist: 63961-470, 2h.52m
    easyprivacy: 26626-583, 2h.51m
    urlhaus-1: 344-0, 6h.58m
    plowe-0: 3670-2, 3d.19h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2146 ms (selfie)
  maxAssetCacheWait: 1014 ms
popupPanel: 
  blocked: 99
  blockedDetails: 
    google.com: 99
```
</details>

**Comment by Procyon-b** [comment]
Open ublock's dashboard, go to the "_Filter lists_" tab, click "_Purge all caches_" then "_Update now_".
Then try gmail again.

**Comment by gekitsuu** [comment]
This fixed it for me, thanks!

**Comment by esponapule** [comment]
YES! This worked. Great advice. Thanks!
