### ISSUE TITLE
fujirumors.com: breakage

### ISSUE THREAD

**Issue by Inazumaa** [uBlockOrigin/uAssets#11928]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fujirumors.com/fujifilms-biggest-mistake-northrup-medium-format-distraction-and-lack-of-fast-aps-c-zooms-to-compete-with-full-frame/`

### Category

breakage

### Describe the issue

Disqus comment section doesn't load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 71885
  cosmetic: 41237
  scriptlet: 16471
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1h.50m
  default: 
    user-filters: 0-0, never
    easylist: 63882-9, 2d.3h.14m
    easyprivacy: 26626-121, 16h.25m
    plowe-0: 3673-804, 2d.3h.18m
    ublock-abuse: 77-0, 16h.26m
    ublock-badware: 4025-83, 2d.3h.17m
    ublock-filters: 30298-155, 2d.3h.16m
    ublock-privacy: 200-2, 2d.3h.15m
    ublock-unbreak: 1718-39, 2d.3h.13m
    urlhaus-1: 344-0, 16h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 754 ms (selfie)
  maxAssetCacheWait: 569 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    3lift.com: 1
    aaxads.com: 1
    amazon-adsystem.com: 1
    datafeedfile.com: 1
    disqus.com: 3
    doubleclick.net: 5
    facebook.com: 3
    getclicky.com: 1
    googlesyndication.com: 1
    instagram.com: 1
    onesignal.com: 1
    paypal.com: 1
    pinterest.com: 1
    pub.network: 1
    quantcount.com: 1
    twitter.com: 1
    youtube.com: 8
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/16838044/155880199-c3dfded0-259d-492d-ae9e-d5b4e6a4703a.png)
