### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Kingismail33** [uBlockOrigin/uAssets#11929]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=uFOd4bFfax8&list=PLi3NShXPcFajxnc3ULCE3-FcgPRvHMIVD`

### Category

REKLAM !

### Describe the issue

HELP ME PLS DONT REKLAM !

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 73502
  cosmetic: 47578
  scriptlet: 16835
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8568-78, 57m
    easylist: 63967-25, 56m
    easyprivacy: 26626-127, 55m
    plowe-0: 3673-806, 1h.4m
    ublock-abuse: 72-0, 1h.2m
    ublock-badware: 3863-83, 1h.1m
    ublock-filters: 30362-168, 1h
    ublock-privacy: 202-2, 59m
    ublock-unbreak: 1718-39, 58m
    urlhaus-1: 344-0, 21h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17330 ms (selfie)
  maxAssetCacheWait: 2800 ms
popupPanel: 
  blocked: 123
  blockedDetails: 
    youtube.com: 101
    doubleclick.net: 3
    google.com: 2
    googlesyndication.com: 11
    googlevideo.com: 6
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by krystian3w** [comment]
Maybe again big selfie:

```yaml
supportStats: 
  allReadyAfter: 17330 ms (selfie)
  maxAssetCacheWait: 2800 ms
```
