### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by agamsol** [uBlockOrigin/uAssets#11938]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

Problem at: `https://mail.google.com/mail/u/0/`

### Category

breakage

### While oBO is enabled a white screen shows in the mail and it cuts some elements with it

When oBO is enabled it happens and when I disable it it doesn't happen..
Broken page while trying to view a mail sent by others (Image Below)

### Screenshot(s)

<details>
<summary>1 Screenshot</summary>

![chrome_2RivB2bVBb](https://user-images.githubusercontent.com/43265196/155891761-cd48bb96-d5a6-4238-990f-8c770425ee3d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 71809
  cosmetic: 41257
  scriptlet: 16499
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63931-9, 1d.20h.20m
    easyprivacy: 26620-122, 1d.20h.19m
    plowe-0: 3670-803, 6d.14h.1m
    ublock-abuse: 77-0, 1d.20h.18m
    ublock-badware: 4025-83, 1d.20h.17m
    ublock-filters: 30347-157, 1d.20h.16m
    ublock-privacy: 200-2, 1d.20h.15m
    ublock-unbreak: 1718-39, 1d.20h.14m
    urlhaus-1: 344-0, 18h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1578 ms (selfie)
  maxAssetCacheWait: 81 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    google.com: 25
```
</details>

**Comment by mapx-** [comment]
You don't =>  `I forced an update of my filter lists`

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906
