### ISSUE TITLE
lost-ark.maxroll.gg: breakage

### ISSUE THREAD

**Issue by revilei** [uBlockOrigin/uAssets#11932]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lost-ark.maxroll.gg/category/build-guides`

### Category

breakage

### Describe the issue

i cant use " select a class" or "filter an activity" with ublock on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de Tela (3)](https://user-images.githubusercontent.com/100521726/155885386-1ae6fd2e-89a6-4c20-aed3-ea6d257fbd20.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 76990
  cosmetic: 20112
  scriptlet: 16693
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63969-23520, 2m
    easyprivacy: 26628-122, 2m
    plowe-0: 3673-805, 2m
    spa-1: 4244-137, 2m
    ublock-abuse: 72-0, 2m
    ublock-badware: 3893-84, 2m
    ublock-filters: 30359-418, 2m
    ublock-privacy: 202-3, 2m
    ublock-unbreak: 1718-40, 2m
    urlhaus-1: 4319-0, 2m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3238 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cloudflareinsights.com: 1
    googletagmanager.com: 1
    nitropay.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
`@@||player.anyclip.com$script,domain=maxroll.gg` works for me

**Comment by JobcenterTycoon** [comment]
```
@@||player.anyclip.com$script,domain=maxroll.gg
@@||s.nitropay.com$script,domain=maxroll.gg
```

works for me

**Comment by okiehsch** [comment]
> i cant use " select a class" or "filter an activity" with ublock on

I can't reproduce and I see no difference if I add the suggested filters.

**Comment by revilei** [comment]
worked for me @JobcenterTycoon

**Comment by Procyon-b** [comment]
I can reproduce the issue.
I usually set ublock to ignore generic cosmetic filters, and I immediately had the issue. While changing the settings the page started to work correctly. That's when I discovered that adding a site-specific cosmetic filter (from the generic filters) solves the issue.
Without that filter, a `click` event listener isn't added to the elements `div.filter-item`.

@revilei try this filter:
```
lost-ark.maxroll.gg###videoad
```

**Comment by okiehsch** [comment]
`###videoad`
is already part of `EasyList`.
![image](https://user-images.githubusercontent.com/16838044/155891816-3d021cea-0606-4d40-ba02-86abe8c2c8ea.png)

**Comment by okiehsch** [comment]
> I usually set ublock to ignore generic cosmetic filters, and I immediately had the issue. While changing the settings the page started to work correctly.

OK, now I understand.

**Comment by Procyon-b** [comment]
> is already part of `EasyList`.

as a generic cosmetic filter. It is not used if the option is disabled. And I can reproduce OP problem in that situation.

**Comment by mapx-** [comment]
`ignoreGenericCosmeticFilters: true`

**Comment by revilei** [comment]
Thanks a million! all for the assistence, I (really) appreciate it.

**Comment by uBlock-user** [comment]
>  ignoreGenericCosmeticFilters: true

Stick to default settings.
