### ISSUE TITLE
windowscmd.com: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#11937]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://windowscmd.com/cleanmgr/`

### Category

detection

### Describe the issue

IMA SDK can't be loaded - in video at right sidebar or in right down corner after scroll.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![obraz](https://user-images.githubusercontent.com/35370833/155891781-18ec17bd-2e65-44ea-a922-8222ae920520.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 194295
  cosmetic: 102228
  scriptlet: 19703
  html: 892
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 108850-164, 1d.15h.56m
    adguard-spyware-url: 491-3, 2d.22h.29m
    block-lan: 44-0, 2d.22h.36m
    fanboy-social: 23173-22, 2d.22h.27m
    ublock-annoyances: 4419-6, 2d.22h.26m
  default: 
    user-filters: 185-0, never
    ublock-filters: 30878-74, 2d.22h.35m
    ublock-badware: 4029-3, 2d.22h.34m
    ublock-privacy: 198-0, 2d.22h.33m
    ublock-abuse: 77-0, 2d.22h.32m
    ublock-unbreak: 1727-0, 2d.22h.31m
    easylist: 63879-632, 2d.22h.30m
    easyprivacy: 26616-575, 2d.22h.28m
    urlhaus-1: 6682-0, 2h.11m
    plowe-0: 3673-2, 20h.52m
    POL-0: 7777-34, 2h.10m
    POL-2: 1276-12, 1d.15h.59m
filterset (user): [array of 151 redacted]
trustedset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: null
  extensionUpdateForceReload: true
  filterAuthorMode: true
  popupPanelLockedSections: 32
  strictBlockingBypassDuration: 30
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 2745 ms (selfie)
  maxAssetCacheWait: 1472 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    googlesyndication.com: 3
    gstatic.com: 1
    imasdk.googleapis.com: 1
    nxedge.io: 6
```
</details>

**Comment by krystian3w** [comment]
IMO we can add:

`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=windowscmd.com,redirect-rule=noopjs`

**Comment by okiehsch** [comment]
Can you play the video with that filter?

**Comment by krystian3w** [comment]
With this:

https://addons.mozilla.org/firefox/addon/playback-speed/ - I click play in that addon and plays.

**Comment by okiehsch** [comment]
Well, we can't add filters that need an extra extension to work properly. 😉 
I will add an exception.
