### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by nubzles** [uBlockOrigin/uAssets#11930]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

There is a bug when opening Gmail, can't see messages on email. The email showed blank. Please fix this.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-02-27 203037](https://user-images.githubusercontent.com/64540800/155884441-d875909d-6708-401b-bfed-6738c9d7b4cf.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 75748
  cosmetic: 41264
  scriptlet: 16499
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    easylist: 63894-9, 1d.19h.6m
    easyprivacy: 26620-122, 1d.19h.7m
    plowe-0: 3670-803, 5d.21m
    ublock-abuse: 77-0, 1d.19h.10m
    ublock-badware: 4025-83, 1d.19h.8m
    ublock-filters: 30347-156, 1d.19h.5m
    ublock-privacy: 199-2, 2d.10h.6m
    ublock-unbreak: 1718-39, 1d.19h.9m
    urlhaus-1: 4319-0, 12h.4m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 393 ms (selfie)
  maxAssetCacheWait: 227 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by nubzles** [comment]
I just click the eye icon to disable cosmetic filtering and all done. Thank you.

![image](https://user-images.githubusercontent.com/64540800/155884553-27d934cc-d418-4e7a-b2cb-fc18b0267e87.png)

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906
