### ISSUE TITLE
hersfelder-zeitung.de: detection

### ISSUE THREAD

**Issue by Feuerswut** [uBlockOrigin/uAssets#11936]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hersfelder-zeitung.de/politik/ukraine-konflikt-russland-proteste-festnahmen-krieg-wladimir-putin-prominente-opposition-zr-91374943.html`

### Category

detection

### Describe the issue

detects uBlock in player

did not verify other requests containing this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 75202
  cosmetic: 26143
  scriptlet: 16495
  html: 622
listset (total-discarded, last updated): 
  added: 
    DEU-0: 5504-376, 1d.50m
  default: 
    user-filters: 3-1, never
    ublock-filters: 31035-273, 8h.40m
    ublock-badware: 3867-3, 8h.42m
    ublock-privacy: 199-1, 8h.39m
    ublock-abuse: 77-0, 8h.38m
    ublock-unbreak: 1735-0, 8h.37m
    adguard-mobile: 7268-175, 8h.41m
    easylist: 63964-24258, 8h.36m
    easyprivacy: 26626-590, 8h.35m
    urlhaus-1: 344-0, 1d.51m
    plowe-0: 3673-2, 1d.17h.55m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1074 ms (selfie)
  maxAssetCacheWait: 905 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    cdntrf.com: 2
    d1miwkthq39xj8.cloudfront.net: 1
    d2wu036mkcz52n.cloudfront.net: 2
    duckduckgo.com: 1
    glomex.com: 5
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    ioam.de: 2
    ippen.space: 1
    k5a.io: 1
    lp4.io: 2
    outbrain.com: 1
    pushwoosh.com: 1
    vgwort.de: 2
```
</details>

**Comment by okiehsch** [comment]
Maybe a mobile only issue, I can't reproduce on the desktop.

**Comment by krystian3w** [comment]
But nice fix if this is not webmaster bug.

IMO possible instal Android in VirtualBox or in vMware Player.

**Comment by krystian3w** [comment]
@Yuki2718 bug may generate default list "AdGuard Mobile".

**Comment by Yuki2718** [comment]
> bug may generate default list "AdGuard Mobile".

I don't see any problem on emulated Android.
