### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by Skucuksahin** [uBlockOrigin/uAssets#11939]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

when clikc mail there is nothing only little white page 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 73668
  cosmetic: 47582
  scriptlet: 16830
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-1, never
    TUR-0: 8568-78, 9h.3m
    easylist: 63965-25, 9h.4m
    easyprivacy: 26626-127, 9h.2m
    plowe-0: 3673-805, 12d.21h.52m
    ublock-abuse: 77-0, 9h.1m
    ublock-badware: 4025-83, 2d.2h.16m
    ublock-filters: 30351-168, 9h
    ublock-privacy: 200-2, 2d.2h.15m
    ublock-unbreak: 1715-39, 2d.2h.14m
    urlhaus-1: 344-0, 23h.20m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 555 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 6
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906
