### ISSUE TITLE
vidup.me [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1193]
URL(s) where the issue occurs

`http://vidup.me/63st0djkdsyh`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try with the following ones:
```
||pqowedazx.bid*
||adscpm.net/adsxml.php*
||35.188.59.75^$popup
```

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=130319#p130319
