### ISSUE TITLE
talktalk.co.uk: breakage

### ISSUE THREAD

**Issue by 1Mark** [uBlockOrigin/uAssets#11934]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.talktalk.co.uk/my/billsandpayments`

### Category

breakage

### Describe the issue

The main body of the page doesn't load. When I disabled uBlock Origin, it did load. I used the documentation here (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules) 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-02-27 14_37_07-Window](https://user-images.githubusercontent.com/15360245/155887138-aded9dee-291d-4a5f-b200-6a3b9f09cad1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 71702
  cosmetic: 41203
  scriptlet: 16468
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63803-9, 3d.16h.34m
    easyprivacy: 26609-122, 3d.16h.41m
    plowe-0: 3670-803, 7d.14h.35m
    ublock-abuse: 77-0, 3d.16h.40m
    ublock-badware: 4025-83, 3d.16h.39m
    ublock-filters: 30291-151, 3d.16h.38m
    ublock-privacy: 199-2, 3d.16h.36m
    ublock-unbreak: 1715-39, 3d.16h.35m
    urlhaus-1: 344-0, 21h.34m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 561 ms (selfie)
  maxAssetCacheWait: 213 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    appdynamics.com: 1
    googletagmanager.com: 1
    optimizely.com: 1
    sentry.io: 3
    unpkg.com: 1
```
</details>

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by 1Mark** [comment]
![image](https://user-images.githubusercontent.com/15360245/156841386-b1082dcc-5d0f-4d9a-917b-1fe36bc77465.png)


> Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there
> (you can select only the blocked items in the search box)

Thanks for this! Are you able to add this to the new issue hints, please?

**Comment by mapx-** [comment]
test these filters

```
@@||cdn-pci.optimizely.com/public/*/my_account_snippet.js$script,domain=talktalk.co.uk
@@||cdn.appdynamics.com/adrum$script,domain=talktalk.co.uk
@@||unpkg.com/@optimizely/optimizely-sdk$script,domain=talktalk.co.uk
```

1 by 1, in combination of 2, if nothing works all 3

**Comment by 1Mark** [comment]
`@@||unpkg.com/@optimizely/optimizely-sdk$script,domain=talktalk.co.uk`

**Comment by mapx-** [comment]
@ryanbr

**Comment by Procyon-b** [comment]
@1Mark does this filter also works ?
```
||unpkg.com/@optimizely/optimizely-sdk$script,domain=talktalk.co.uk,redirect-rule=noop.js
```
comment out the `@@` rule

**Comment by 1Mark** [comment]
> @1Mark does this filter also works ?
> 
> ```
> ||unpkg.com/@optimizely/optimizely-sdk$script,domain=talktalk.co.uk,redirect-rule=noop.js
> ```
> 
> comment out the `@@` rule

No it doesn't work.
