### ISSUE TITLE
systemed.fr: detection

### ISSUE THREAD

**Issue by franckbcom** [uBlockOrigin/uAssets#11949]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.systemed.fr/chauffage-central/comment-bien-installer-chaudiere-granules,13908.html?utm_source=newsletter_edito&utm_medium=email&utm_campaign=1222`

### Category

detection

### Describe the issue

Ublock detected. The site displays a blocking window because Ublock has been detected 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 96813
  cosmetic: 29053
  scriptlet: 16482
  html: 620
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-1, never
    ublock-filters: 30922-413, 1d.15h.53m
    ublock-badware: 4029-3, 3d.23h.50m
    ublock-privacy: 198-1, 3d.23h.54m
    ublock-abuse: 77-0, 3d.23h.52m
    ublock-unbreak: 1732-0, 1d.15h.51m
    adguard-mobile: 7251-169, 3d.23h.53m
    easylist: 63806-24476, 6d.19h.17m
    easyprivacy: 26617-578, 3d.23h.51m
    urlhaus-1: 8000-1, 3d.23h.48m
    plowe-0: 3670-2, 6d.19h.19m
    FRA-0: 26119-3613, 3d.23h.49m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1300 ms (selfie)
  maxAssetCacheWait: 433 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    systemed.fr: 4
    beop.io: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    kolplay.com: 7
    opti-digital.com: 2
    sddan.com: 1
    taboola.com: 1
    viously.com: 12
```
</details>

**Comment by okiehsch** [comment]
@AdamWr for `AdGuard Français`
`systemed.fr##+js(aopw, dtctAB)`

**Comment by AdamWr** [comment]
Added, thank you.
Filters update should be available in 1-2 hours.
