### ISSUE TITLE
[nsfw] vimm.net: privacy

### ISSUE THREAD

**Issue by Proshell12** [uBlockOrigin/uAssets#11941]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vimm.net/vault/18140`

### Category

privacy

### Describe the issue

Im not access this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 72987
  cosmetic: 43903
  scriptlet: 16693
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63965-9, 9h.36m
    easyprivacy: 26626-122, 9h.35m
    plowe-0: 3673-804, 2d.8h.59m
    spa-1: 4244-77, 9h.37m
    ublock-abuse: 72-0, 9h.43m
    ublock-badware: 3863-83, 9h.42m
    ublock-filters: 30362-196, 9h.41m
    ublock-privacy: 202-2, 9h.39m
    ublock-unbreak: 1718-40, 9h.38m
    urlhaus-1: 344-0, 23h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google.com: 3
```
</details>

**Comment by iam-py-test** [comment]
I can reproduce the anti-adblock in Mozilla Firefox
You have to click the download button to see it

**Comment by uBlock-user** [comment]
@iam-py-test Did you subscribe to uBlock Annoyances list ? There's a filter for it.

**Comment by iam-py-test** [comment]
No, default settings
