### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by Kryofenix** [uBlockOrigin/uAssets#11943]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

The email content does not show when ublock origin is enabled. This is only for one of my accounts, not all of them!

The inbox works properly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![2022-02-27 20_32_51-Window](https://user-images.githubusercontent.com/5210014/155896981-50ebe09b-ff0d-464b-9683-d74d00136cfa.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 94220
  cosmetic: 50521
  scriptlet: 16513
  html: 619
listset (total-discarded, last updated): 
  added: 
    FRA-0: 26135-366, 1d.4h.54m
  default: 
    user-filters: 1-0, never
    ublock-filters: 30926-186, 1d.4h.48m
    ublock-badware: 3867-3, 1d.4h.55m
    ublock-privacy: 202-0, 1d.4h.53m
    ublock-abuse: 77-0, 1d.4h.52m
    ublock-unbreak: 1729-0, 1d.4h.51m
    easylist: 63961-682, 1d.4h.50m
    easyprivacy: 26626-570, 1d.4h.49m
    urlhaus-1: 6682-0, 4m
    plowe-0: 3675-2, 9d.21h.45m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 403 ms
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 6
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906
