### ISSUE TITLE
*uBlock Unbreak* breakes Gmail completely: Gmail email content completely blocked out

### ISSUE THREAD

**Issue by nekromoff** [uBlockOrigin/uAssets#11942]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://mail.google.com/mail/u/0/#inbox/

### Describe the issue

Email content completely blocked out (removed)

![image](https://user-images.githubusercontent.com/8550349/155896690-eec7ce47-6d44-44eb-a499-ca748673017c.png)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8550349/155896691-bb49c196-d73e-4368-8de0-c36c0dac1ed8.png)

![image](https://user-images.githubusercontent.com/8550349/155896725-e9ce9705-4dc9-417c-b514-02b0d8180dc1.png)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 96.0

### Settings

Turning off uBlock Unbreak brings Gmail content back

### Notes

Turning off uBlock Unbreak brings Gmail content back

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906
