### ISSUE TITLE
twitch.tv: breakage

### ISSUE THREAD

**Issue by mochizuki-8** [uBlockOrigin/uAssets#11946]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/moderator/lewina_`

### Category

breakage

### Describe the issue

I can watch twitch.tv perfectly fine but if I go into moderator mode since this evening suddenly I get a semi crash? I can still hear the streamer audio but screen has a giant chrome ghost logo.

Tried to reload with the tracker open and it says filter list uBlock filters has banned the dom?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66710174/155920476-e0033813-2a54-490f-9b5c-4f69bd34390d.png)
![image](https://user-images.githubusercontent.com/66710174/155920849-d0932a4b-3ab6-4127-9dd2-add662272627.png)
![image](https://user-images.githubusercontent.com/66710174/155920867-4881787f-172e-4c2b-b9f3-0a3d81d5b10f.png)
![image](https://user-images.githubusercontent.com/66710174/155920884-8dee5865-3a3e-4865-9fa2-e5ac1ad66f2d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 96
filterset (summary): 
  network: 113427
  cosmetic: 47900
  scriptlet: 31930
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 273-0, 1d.10h.16m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/AntiAstrologyList.txt: 364-0, 1d.10h.15m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/AntiPrayerTimesList.txt: 102-0, 4d.11h.23m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/AntiPreacherList.txt: 1568-0, 4d.11h.23m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/Dandelion Sprout's Anti-Religion List.txt: 2034-2034, 4d.11h.24m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/TabloidRemover-MastodonCategoryForImports.csv: 93-0, 4d.11h.25m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive lists/Twitter De-Politificator.txt: 484-0, 8h.37m
    https://raw.githubusercontent.com/MassMove/AttackVectors/master/LocalJournals/fake-local-journals-list.txt: 1083-0, 4d.11h.25m
    https://raw.githubusercontent.com/acnapyx/paywall-remover/master/paywall-remover-list.txt: 2529-73, 4d.11h.27m
    https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt: 48695-12, 4d.11h.23m
    https://raw.githubusercontent.com/rimu/no-qanon/master/etc_hosts.txt: 5206-118, 4d.11h.25m
    JPN-1: 5949-25, 12h.48m
    adguard-generic: 61988-975, 12h.47m
    adguard-spyware: 25698-5955, 12h.46m
    adguard-spyware-url: 491-12, 12h.45m
    fanboy-thirdparty_social: 68-0, 4d.12h.56m
    ublock-annoyances: 4410-79, 12h.43m
  default: 
    user-filters: 5-0, never
    plowe-0: 3672-1571, 4d.12h.56m
    ublock-abuse: 72-3, 12h.44m
    ublock-badware: 3863-240, 12h.42m
    ublock-filters: 30362-3034, 12h.41m
    ublock-privacy: 202-35, 12h.40m
    ublock-unbreak: 1718-90, 12h.39m
    urlhaus-1: 6682-1, 12h.38m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 206 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 19
  no-cosmetic-filtering: true
  blockedDetails: 
    amazon-adsystem.com: 2
    countess.twitch.tv: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 3
    scorecardresearch.com: 4
    sentry.io: 3
    twitchcdn.net: 5
```
</details>

**Comment by uBlock-user** [comment]
Test on default lists/settings. Also re-enable EasyList/EasyPrivacy which you disabled.
