### ISSUE TITLE
exxen.com - AdGuard Base Filter Brakes Website Only with uBlock Origin

### ISSUE THREAD

**Issue by bkrucarci** [uBlockOrigin/uAssets#11945]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.exxen.com/tr/watch-serie/ilginc-bazi-olaylar-10-bolum/39139`

### Describe the issue

You already see my filters. With the same filters enabled on AdGuard extension website works OK.
With the same filters enabled on uBlock Origin, the video player does not play!

I checked the blocked contents one by one to play video and then I discovered that AdGuard base filter rule causes the problem on the video player.

The rule _**does NOT**_ brake the video player with AdGuard extension.
The rule **_does_** brake the video player with uBlock Origin.

Related rule which breaks the video player in AdGuard Base Filter.
**exxen.com##+js(nofab)**

After I added the fix rule to my filters then video plays
**exxen.com#@#+js(nofab)**

### Screenshot(s)

![Screenshot_014542_2022-02-28](https://user-images.githubusercontent.com/15933805/155903272-52878c0b-e8ce-496d-a88a-bb23221d24c9.png)
![Screenshot_014510_2022-02-28](https://user-images.githubusercontent.com/15933805/155903275-7307adc1-86c7-4d65-944b-eb00dfff8f48.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 90050
  cosmetic: 137243
  scriptlet: 33540
  html: 632
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 290-0, 6m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive%20lists/AntiAstrologyList.txt: 366-0, 6m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive%20lists/AntiPrayerTimesList.txt: 106-0, 6m
    adguard-generic: 62005-4599, 3m
    adguard-spyware: 25699-945, 7m
    adguard-spyware-url: 491-3, 7m
    adguard-annoyance: 50390-1520, 7m
    adguard-social: 15922-20, 7m
    fanboy-thirdparty_social: 69-0, 7m
    ublock-annoyances: 4419-42, 6m
    TUR-0: 8569-78, 7m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30888-44, 5m
    ublock-badware: 3903-3, 5m
    ublock-privacy: 208-0, 5m
    ublock-abuse: 72-0, 5m
    ublock-unbreak: 1729-0, 5m
    easylist: 63978-289, 5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  uiAccentCustom0: #8080ff
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 833 ms (selfie)
  maxAssetCacheWait: 869 ms
```
</details>

**Comment by iam-py-test** [comment]
Issue specific to non-default settings.
Also, an account is required
Probably it breaks only in uBo because there are different filters enabled in uBo than in AG and because AG supports different types of scriptlets
> - [X]  uBO with default lists/settings

This is not valid. Please read over the checkboxes before checking them, uAssets is only for issues with default config or uBlock Annoyances.

**Comment by bkrucarci** [comment]
> Issue specific to non-default settings. Also, an account is required Probably it breaks only in uBo because there are different filters enabled in uBo than in AG and because AG supports different types of scriptlets Also, running uBo alongside AdGuard will always cause problems. Pick one (remove the other) and stick with the default settings
> 
> > * [x]   uBO with default lists/settings
> 
> This is not valid. Please read over the checkboxes before checking them, uAssets is only for issues with default config or uBlock Annoyances.

Ok,, thanks. So it is useless for me to reporting these sites. I always use custom settings with uBO.
Anyway, thanks for help.

**Comment by iam-py-test** [comment]
@bkrucarci the uAssets repo is just for issues with uBo default settings. You can use the Reddit uBlockOrigin area or other GH repos dedicated to general uBo questions/support (i.e. https://github.com/DandelionSprout/adfilt/issues/63)
I do not make the rules here, I am just a person who helps around

**Comment by bkrucarci** [comment]
> @bkrucarci the uAssets repo is just for issues with uBo default settings. You can use the Reddit uBlockOrigin area or other GH repos dedicated to general uBo questions/support (i.e. [DandelionSprout/adfilt#63](https://github.com/DandelionSprout/adfilt/issues/63)) I do not make the rules here, I am just a person who helps around

I see you mate. You helped me before 👍🏻 Thanks for being around.
I can solve problems on my own. Just trying to solve this problem for the others users maybe because if I report it to AdGuard, they will reply "Use AdGuard ext. instead?" but problem is different.

**Comment by bkrucarci** [comment]
@iam-py-test Hi,
Can we add the rule to uBlock - Unbreak list?
**exxen.com#@#+js(nofab)**
I checked uBlock - Unbreak list and you guys added some unbreak rules in this filter to fix Peter Lowe's List fixfor example.

AdGuard filter devs said [here](https://github.com/AdguardTeam/AdguardFilters/pull/111783)
> As far as I understand, it works fine with AdGuard, but doesn't with uBlock. If so, I would prefer to exclude this rule from filters for uBlock than remove it.

What do you think about it?

**Comment by AdamWr** [comment]
I suppose, that this issue may be related to this - https://github.com/AdguardTeam/Scriptlets/issues/104
I don't have account to check it, but it looks like that on `exxen.com` (`https://wasset.exxen.com/js/lib/rmp.min.js`) `options.set`/`options.get` is used.
So, maybe it could be fixed in `nofab` uBlock script?

**Comment by okiehsch** [comment]
@bkrucarci 
If we add `exxen.com#@#+js(nofab)` you can still use the site without issue?

**Comment by bkrucarci** [comment]
> @bkrucarci If we add `exxen.com#@#+js(nofab)` you can still use the site without issue?

When I add this rule the video player works normally. If you add this rule to related uBlock filter it's gonna solve my problem.

**Comment by uBlock-user** [comment]
We don't add fixes for non-default lists.

**Comment by okiehsch** [comment]
Ok. I asked because usually `+js(nofab)` has been added to fix some anti adblock message that blocks access to a site.

@uBlock-user `Adguard Turkish` is a default regional list for users with a turkish locale.
Adguard says they would prefer we add an exception because the problem does not occur for Adguard users.

**Comment by uBlock-user** [comment]
@okiehsch is the filter present in AdGuard Turkish or AdGuard Base ?

**Comment by okiehsch** [comment]
Ups, my bad.
@AdamWr why is it in Adguard Base? It's a turkish site.

**Comment by bkrucarci** [comment]
@uBlock-user @okiehsch it's in AdGuard Base filter

**Comment by uBlock-user** [comment]
Yep, you mentioned AdGuard Base in the issue title too.

**Comment by okiehsch** [comment]
@bkrucarci yes, sorry I got confused.
As @uBlock-user says we don't add filters for issues with non default lists.

**Comment by bkrucarci** [comment]
@uBlock-user @okiehsch ,
if @AdamWr move the rule to AdGuard Turkish filter? Then, do you need to fix the problem?

**Comment by uBlock-user** [comment]
@bkrucarci Add the exception filter to my Filters.

**Comment by okiehsch** [comment]
> if @AdamWr move the rule to AdGuard Turkish filter? Then, do you need to fix the problem?

Yes.

**Comment by uBlock-user** [comment]
> if @AdamWr move the rule 

Will he do that ?

**Comment by AdamWr** [comment]
For popular anti-adblock scripts (like blockadblock, fuckadblock, antiblock.org and other similar) we are adding rules to Base filter.
I didn't say that I will not fix it, I just don't want to remove this rule for AdGuard users, because it's still a valid rule. I will just add a "hint" to exclude it from rules for uBlock.

**Comment by uBlock-user** [comment]
> because uBO can be a "tool" for using AdGuard filters

General advise is stick to defaults lists. By enabling non-default lists, you also risk site breakage and then it becomes user's responsibility to tend to such issues like this one.
