### ISSUE TITLE
zen.yandex.ru: [unknown]

### ISSUE THREAD

**Issue by euganis** [uBlockOrigin/uAssets#11940]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.zen.yandex.ru/media/zmegor/nagliadnyi-vred-ot-protiajnyh-tochilok-6217d269f195ce4d56517e10`

### Category

[unknown]

### Describe the issue

Blank screen

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 94
filterset (summary): 
  network: 95332
  cosmetic: 43913
  scriptlet: 18056
  html: 625
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30980-271, 1d.11h.3m
    ublock-badware: 4029-3, 1d.11h.4m
    ublock-privacy: 198-1, 1d.11h.2m
    ublock-abuse: 77-0, 1d.11h.1m
    ublock-unbreak: 1732-0, 1d.11h
    adguard-mobile: 7268-169, 20h.34m
    easylist: 63961-24248, 20h.28m
    easyprivacy: 26626-579, 20h.25m
    urlhaus-1: 4319-0, 8h.28m
    plowe-0: 3673-2, 20h.35m
    RUS-0: 41548-1017, 8h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 708 ms (selfie)
  maxAssetCacheWait: 353 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    yandex.ru: 21
```
</details>

**Comment by dimisa-RUAdList** [comment]
Whatever user agent I install, I can't switch to the mobile version of the site `https://m.zen.yandex.ru/`. In all cases, there is a redirect to `https://zen.yandex.ru/`.

With the default settings on the standard version of the site, the problem is not reproduced.

**Comment by mapx-** [comment]
No issue on mobile.
