### ISSUE TITLE
watchers.to [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1194]
URL(s) where the issue occurs

`http://watchers.to/c96wf0u46xse.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `||35.188.59.75^$popup`

**Comment by SMed79** [comment]
`watchers.to##script:inject(nowebrtc.js)`

**Comment by okiehsch** [comment]
> try ||35.188.59.75^$popup

@nimasaj see my comment https://github.com/uBlockOrigin/uAssets/commit/16ea13af9899bc5abd8410276a40655e8e250f12#commitcomment-26398559
