### ISSUE TITLE
uBlock Origin is preventing gmail from loading email contents now...

### ISSUE THREAD

**Issue by MelchiorGaspar** [uBlockOrigin/uAssets#11947]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://mail.google.com/mail/u/0/#inbox

### Describe the issue

as stated in the title, uBlock Origin v1.41.6 and now updated to v1.41.8 just a few minutes ago..
uBlock Origin is now blocking email contents some how... it could be changes Google made to gmail... not sure.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1712842/155927710-d5d03f36-67f9-42c7-8cf5-d8bb06ea4343.png)

### uBlock Origin version

1.41.6 and now 1.41.8

### Browser name and version

Firefox v97.0.1

### Settings

none

### Notes

I found disabling uBlock Origin and reloading gmail fixes the issue and the email contents loads fine..
and having loaded gmail and an older version of uBlock Origin (v1.32.4) in Waterfox classic v2022.01 gmail loads emails fine.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906

**Comment by MelchiorGaspar** [comment]
Ooh.. so it was already reported lol
I checked the recent opened list but didn't check the closed list..

**Comment by uBlock-user** [comment]
> so it was already reported 

not just reported, fixed two days ago. Just force update ublock filters list.

**Comment by MelchiorGaspar** [comment]
I just read about that in  #11906 
so yeah I did the force update a second ago and its working now. 
thx for the info.
