### ISSUE TITLE
qosa.pearsonclinical.com: breakage

### ISSUE THREAD

**Issue by parkerj-cinnaminson** [uBlockOrigin/uAssets#11959]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://qosa.pearsonclinical.com/qosa-a2/1519a163-dece-4850-8969-60fa4d84a5b2`

### Category

breakage

### Describe the issue

When launching this site (the link provided is a demo/sample evaluation we've setup, the guid at the end is unique to each test session, but the issue is consistent across all tests under pearsonclinical.com) there is a loading ring that comes up and will not clear until uBlock is disabled for the page.  I will keep this demo open for you to also have access to replicate the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock issue](https://user-images.githubusercontent.com/95932563/156024545-4e368ff2-e44a-4463-8738-696da419f518.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 78004
  cosmetic: 41287
  scriptlet: 16505
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63961-9, 1d.18h.26m
    easyprivacy: 26626-122, 1d.18h.25m
    plowe-0: 3674-804, 12d.23h.46m
    ublock-abuse: 77-0, 1d.18h.24m
    ublock-badware: 3863-83, 1d.18h.23m
    ublock-filters: 30362-157, 1d.18h.22m
    ublock-privacy: 202-2, 1d.18h.21m
    ublock-unbreak: 1718-39, 1d.18h.19m
    urlhaus-1: 6682-0, 18h.17m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2660 ms (selfie)
  maxAssetCacheWait: 2143 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe it's enough

`pearsonclinical.com##.aligner`

**Comment by parkerj-cinnaminson** [comment]
That appears to do the job!  Truly appreciate the assistance!
