### ISSUE TITLE
monitor.firefox.com: breakage

### ISSUE THREAD

**Issue by eriwaaaa** [uBlockOrigin/uAssets#11954]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://monitor.firefox.com/user/dashboard`

### Category

breakage

### Describe the issue

HELP

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79805
  cosmetic: 41310
  scriptlet: 16466
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30934-30, never
    ublock-badware: 3903-3, 2m
    ublock-privacy: 208-0, 2m
    ublock-abuse: 72-0, 2m
    ublock-unbreak: 1729-0, 2m
    easylist: 63996-616, 2m
    easyprivacy: 26629-571, 2m
    urlhaus-1: 8437-0, 2m
    plowe-0: 3673-2, 2m
filterset (user): [empty]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1946 ms
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    firefox.com: 5
```
</details>

**Comment by mapx-** [comment]
> Describe the issue
> HELP

describe the issue if you want to be helped
