### ISSUE TITLE
admin.memberspace.com: breakage

### ISSUE THREAD

**Issue by nathangilchrist** [uBlockOrigin/uAssets#11955]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://admin.memberspace.com/sites/…`

### Category

breakage

### Describe the issue

When clicking on `View members details` and then on `Member Pages`, having uBlock Origin activated will not display the data as it does for the `Events` and `Content Links` pages. A working animation continues to show with no change or update.

This change seemed to occur only a matter of weeks ago.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 78066
  cosmetic: 41238
  scriptlet: 16473
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63854-9, 3d.16h.27m
    easyprivacy: 26616-121, 3d.16h.26m
    plowe-0: 3673-804, 3d.16h.25m
    ublock-abuse: 77-0, 3d.16h.23m
    ublock-badware: 4019-83, 3d.16h.21m
    ublock-filters: 30303-154, 3d.16h.20m
    ublock-privacy: 199-2, 3d.16h.19m
    ublock-unbreak: 1717-39, 3d.16h.18m
    urlhaus-1: 6682-0, 12h.16m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1177 ms
  maxAssetCacheWait: 235 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    memberspace.com: 1
```
</details>

**Comment by mapx-** [comment]
- needing account
- Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by nathangilchrist** [comment]
![image](https://user-images.githubusercontent.com/7089117/156046972-6913aa33-2661-42d0-bbc2-9d036f33869b.png)
![image](https://user-images.githubusercontent.com/7089117/156047010-892db554-29f5-4ebb-9be2-57840a323957.png)
![image](https://user-images.githubusercontent.com/7089117/156047028-2bac9f59-7886-4dc4-ba5e-ed63b299275e.png)

**Comment by mapx-** [comment]
does this exception work for you ?

`@@||admin.memberspace.com/sites/*/analytics/views$xhr,1p`

@ryanbr

**Comment by nathangilchrist** [comment]
That solved it! 👏
