### ISSUE TITLE
estream.to [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1195]
URL(s) where the issue occurs

`https://estream.to/afp3f1zdyp5q.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try with the following ones:
```
||adskeeper.co.*
||oclaserver.com*
```

or use the following list:
`https://raw.githubusercontent.com/nimasaj/uBO_Filterlist/master/BLF.txt`

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=130417#p130417

**Comment by nimasaj** [comment]
@SMed79, generic filters help avoiding a larger filter list and less impact on memory, and in case of false positive it could be either edited or exceptions added. Regarding those white-list domains, it's based on their activity field and to avoid raising issues. For example bank portals that having Adblock on running on their website might cause unintentional issues. But I agree that I can remove some domains from that list.

**Comment by SMed79** [comment]
@nimasaj I do not agree. It is not up to the maintainer of the list to make the decision to disable my adblock on a website.

PS: _Sorry for the noise_.

**Comment by nimasaj** [comment]
@SMed79, you're right. I removed them. Thanks.

**Comment by SMed79** [comment]
@nimasaj Now, the users who subscribe to your list still have the control to disable their adblocker where they want :smiley_cat:
