### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by Kintar** [uBlockOrigin/uAssets#11957]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

Content inside some emails is blocked.  This has been reported in multiple tickets, and claims to be fixed with filter updates, but I have updated my filters as of 09:26 Central Time on 2022-02-28, and the issue is still occurring.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot](https://imgur.com/a/VnwQ0aB)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79761
  cosmetic: 41270
  scriptlet: 16456
  html: 619
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30906-27, 1d.20h.55m
    ublock-badware: 3867-3, 1d.20h.54m
    ublock-privacy: 202-0, 1d.20h.53m
    ublock-abuse: 77-0, 1d.20h.52m
    ublock-unbreak: 1729-0, 1d.20h.51m
    easylist: 63961-600, 1d.20h.50m
    easyprivacy: 26626-583, 1d.20h.49m
    urlhaus-1: 8437-0, now
    plowe-0: 3670-2, 6d.18h.23m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 490 ms (selfie)
  maxAssetCacheWait: 176 ms
popupPanel: 
  blocked: 39
  blockedDetails: 
    google.com: 39
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906
