### ISSUE TITLE
Gmail email contents blocked by cosmetic filtering

### ISSUE THREAD

**Issue by JVB-Tesla** [uBlockOrigin/uAssets#11966]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

gmail.com

### Describe the issue

As of a few days ago, emails in gmail are not loading. The main email listing page will load, but the contents of emails can not be viewed when they are opened. This is corrected by disabling cosmetic filtering.

I expected this to have been reported, but did not see it in the issue tracker.

This thread also describes the issue and was created 3 days ago.

https://support.google.com/mail/thread/152314025/emails-are-not-opening?hl=en

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 79902
  cosmetic: 41250
  scriptlet: 16496
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63931-9, 2d.22h.12m
    easyprivacy: 26620-122, 2d.22h.10m
    plowe-0: 3673-805, 1h.37m
    ublock-abuse: 77-0, 2d.22h.11m
    ublock-badware: 4025-83, 2d.22h.9m
    ublock-filters: 30335-157, 2d.22h.15m
    ublock-privacy: 202-2, 2d.22h.14m
    ublock-unbreak: 1718-39, 2d.22h.13m
    urlhaus-1: 8437-0, 13h.7m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 694 ms (selfie)
  maxAssetCacheWait: 1328 ms
```
</details>

**Comment by mapx-** [comment]
update your filter lists, already fixed

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906

**Comment by okiehsch** [comment]
The amount of duplicate gmail issues in the last few days has to be some sort of record.....

![image](https://user-images.githubusercontent.com/16838044/156048558-f0657f47-9b61-40dc-ae4c-cc556457b84a.png)

**Comment by uBlock-user** [comment]
I don't see that many if I search for gmail.

**Comment by okiehsch** [comment]
`mail.google.com` is the same thing and as you can see in the screenshot I searched for "mail"

**Comment by uBlock-user** [comment]
"mail" is very generic and results in many many non-gmail related issues.

**Comment by gwarser** [comment]
> I don't see that many if I search for gmail.

They will say "gmail" only when someone typed this. The domain has only `mail` and `google` in it.

BTW it can be that over 500k users downloaded this bad update.

**Comment by uBlock-user** [comment]
> They will say "gmail" only when someone typed this.

Actually, I have linked the original which contains "gmail", to all the duplicate threads, so those which do not have "gmail" anywhere in the body will still appear if you search for gmail ;)
