### ISSUE TITLE
surfline.com: detection

### ISSUE THREAD

**Issue by Yoddy2k22** [uBlockOrigin/uAssets#11965]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.surfline.com/`

### Category

detection

### Describe the issue

Surfline used to get ads blocked but now is detecting ubo. I don't have a time frame when it started again but within the past week or 2 weeks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79601
  cosmetic: 42551
  scriptlet: 16698
  html: 619
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 23h.43m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 210d.23h.28m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30883-67, 2d.10h.49m
    ublock-badware: 4029-3, 1d.23h.51m
    ublock-privacy: 202-0, 1d.23h.50m
    ublock-abuse: 77-0, 1d.23h.49m
    ublock-unbreak: 1729-2, 2d.16h.24m
    easylist: 63961-628, 1d.23h.48m
    easyprivacy: 26626-575, 1d.23h.47m
    urlhaus-1: 6682-0, 23h.42m
    plowe-0: 3673-3, 19h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 196 ms (selfie)
  maxAssetCacheWait: 80 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    surfline.com: 1
    cdn-surfline.com: 1
    cloudflareinsights.com: 2
    googletagservices.com: 1
    htlbid.com: 2
    jwpcdn.com: 1
    segment.com: 1
    zendesk.com: 1
```
</details>

**Comment by dafonso** [comment]
Seems like this effectively breaks surfline report webpages.

Example: https://www.surfline.com/surf-report/carcavelos/5842041f4e65fad6a7708bc0

Panel with the report details does not load.

Can you please revert this?
