### ISSUE TITLE
webcheats.com.br [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1196]
URL(s) where the issue occurs

`http://www.webcheats.com.br/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by llacb47** [comment]
I can reproduce in firefox.
Anti-adblock script: `https://www.webcheats.com.br/uploads/set_resources_3/6554b6be8c0d829a8bf63ae0c82cf121_zozEabb204.js`

Add `||webcheats.com.br/uploads/set_resources_3/6554b6be8c0d829a8bf63ae0c82cf121_zozEabb204.js$script`
or `webcheats.com.br##+js(setTimeout-defuser.js,test,0)`

**Comment by llacb47** [comment]
@okiehsch reopen please

**Comment by okiehsch** [comment]
There is no need to reopen, I

**Comment by okiehsch** [comment]
I don't think there is a need to reopen issues if I will just close them a short time later anyway.
You have already pointed to a working fix, so no point in asking me to reopen.
For the record, me reopening was a misclick on my part. :wink:

**Comment by llacb47** [comment]
Ah, sorry.

**Comment by okiehsch** [comment]
No problem.
