### ISSUE TITLE
1337x ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#11963]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://1337x.to/popular-games`

### Describe the issue

There some ads with "Hide your IP" on the top of the page and on the bottom. Also those ads appear on every torrent too.

### Screenshot(s)

![screen03](https://user-images.githubusercontent.com/86512304/156035570-9d5f1768-7eb0-490f-809b-254a5577c413.jpg)
![screen04](https://user-images.githubusercontent.com/86512304/156035575-47324738-b9fa-4c83-96be-2137549b5731.jpg)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0.1

### Settings

Default settings

**Comment by SeriousHoax** [comment]
@uBlock-user @mapx- - Hello! The ads are back. The previous fix doesn't work anymore.

**Comment by uBlock-user** [comment]
`1337x.to##a[style="text-decoration:none; border-bottom:none; color:none;"]`
