### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by Valnjes** [uBlockOrigin/uAssets#11979]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

When I open any email the content is missing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Broken](https://user-images.githubusercontent.com/57059002/156174427-4b835033-dc3f-4512-bb3a-3b199fb6c7d4.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 91
filterset (summary): 
  network: 79929
  cosmetic: 41278
  scriptlet: 16461
  html: 619
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-1, never
    ublock-filters: 30922-27, 2d.10h.8m
    ublock-badware: 4029-3, 2d.10h.7m
    ublock-privacy: 202-0, 2d.10h.5m
    ublock-abuse: 77-0, 2d.10h.1m
    ublock-unbreak: 1729-0, 2d.10h.4m
    easylist: 63961-601, 2d.10h.3m
    easyprivacy: 26626-584, 2d.10h.2m
    plowe-0: 3673-2, 21h.57m
    urlhaus-1: 8437-0, 9h.56m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 452 ms (selfie)
  maxAssetCacheWait: 281 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    google.com: 18
```
</details>

**Comment by okiehsch** [comment]
My comment here https://github.com/uBlockOrigin/uAssets/issues/11978#issuecomment-1055424669 applies to you too.

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906
