### ISSUE TITLE
magesy.be [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1197]
URL(s) where the issue occurs

`https://magesy.be/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `magesy.be###adblockplus`

**Comment by KiLL4FuNK** [comment]
`http://majesy.com/` Anti-Adblock

**Comment by KiLL4FuNK** [comment]
http://majesy.com/ Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
http://magesy.eu/         Anti-Adblock @mapx-
http://majesy.com/

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

https://magesy.be/
http://magesy.eu/
http://majesy.com/
http://magesy.pw/
http://www.magesy.audio/

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

`http://majesy.com/`

**Comment by mapx-** [comment]
I get no anti adb FF / chome
You should reset uBo to the default setup

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://mage.si/u3V7`

`http://majesy.com/samples/vikings-expansion-metal-cinematic-toolkit-v1-1-kontakt-synthic4te.html#more-131232`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

http://mage.si/u3V7

http://majesy.com/samples/vikings-expansion-metal-cinematic-toolkit-v1-1-kontakt-synthic4te.html#more-131232

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

``http://magesy.eu/`
`http://majesy.com/``

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://magesy.pw/download/7664-absolute-beginners-guide-fls-tutorial-synthic4te.html`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://majesy.com/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

http://magesy.eu/
http://majesy.com/
http://magesy.pw/

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://magesy.pw/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://majesy.com/`
`http://magesy.eu/`


Anti-Adblock

`https://www.magesypro.com/gowler-music-essential-hi-hats-and-cymbals-wav-free/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
which one ? provide link

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://majesy.com/`
`http://magesy.eu/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://majesy.com/`
`http://magesy.eu/`

**Comment by Ouack23** [comment]
Hello, I am using uBlock Origin and nanoDefender  and i cannot access the following sites due to

Anti-Adblock

`https://majesy.com/
https://magesy.eu/
https://magesy.fr/`

**Comment by mapx-** [comment]
wait 5-10 min, update your lists and test again

**Comment by JobcenterTycoon** [comment]
This site disabled rightclick

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by KiLL4FuNK** [comment]
`https://magesy.blog/`
`https://majesy.org/`

**Comment by JobcenterTycoon** [comment]
i still get anti adblock on all sites

**Comment by mapx-** [comment]
no anti adb on my side FF / chrome, @okiehsch do you get any ?

**Comment by okiehsch** [comment]
Yes, using Chromium and Chrome I get an anti adb message.
I can't reproduce with Firefox.

**Comment by okiehsch** [comment]
`@@||lacuevadeguns.com/forum/*$image,domain=magesy.*`
works for me.

**Comment by JobcenterTycoon** [comment]
hmm i need this filter for majesy too. `@@||lacuevadeguns.com/forum/*$image,domain=magesy.*|majesy.*` is needed

**Comment by mapx-** [comment]
@JobcenterTycoon  test these filters

```
*$image,redirect-rule=2x2.png,domain=magesy.blog|magesy.eu|majesy.com,badfilter
*$image,redirect-rule=1x1.gif,domain=majesy.org|magesy.pw|magesy.fr,badfilter
magesy.*#@#+js(abort-on-stack-trace, Math.floor, onload)
majesy.*#@#+js(abort-on-stack-trace, Math.floor, onload)
magesy.*,majesy.*##+js(aost, onload, inlineScript, 2)
```

**Comment by JobcenterTycoon** [comment]
works perfect

**Comment by KiLL4FuNK** [comment]
`http://beelink.in/42938/Bad-Dreams-One-Shot-Pack-WAV/`
`https://mage.si/1V6K`

**Comment by JobcenterTycoon** [comment]
Anti Adblock on `https://lacuevadeguns.com` looks like its one of the magesy sites

**Comment by JobcenterTycoon** [comment]
Anti Adblock back on `https://magesy.blog/`

**Comment by JobcenterTycoon** [comment]
Anti Adblock back on `https://majesy.org/`

**Comment by JobcenterTycoon** [comment]
I get anti adblock on ` https://mage.si/1V6K`

**Comment by IThinkIAmCool** [comment]
> `https://mage.si/1V6K`

ads

**Comment by Ouack23** [comment]
Anti-adblock `https://magesy.blog/`

**Comment by JobcenterTycoon** [comment]
`*$object,redirect=noop.js,domain=magesy.blog`

**Comment by felix-22** [comment]
`magesypro.pro`

<details>
<summary>screenshoot 1</summary>

![1](https://user-images.githubusercontent.com/75935068/143830670-6d038434-59cf-4af5-90dd-2ac54b192f4c.png)

</details>

<hr>

`magesypro.club`

<details>
<summary>screenshoot 2</summary>

![2](https://user-images.githubusercontent.com/75935068/143830770-48b564d9-131d-45a8-8fbf-b292dbac8508.png)

</details>

<hr>

`magesypro.blog` (2x)

<details>
<summary>screenshoot 3</summary>

![2 (2)](https://user-images.githubusercontent.com/75935068/143831281-3f77074b-d6a8-4bbb-bcce-16897da02c44.png)

</details>

<details>
<summary>screenshoot 4</summary>

![2 (1)](https://user-images.githubusercontent.com/75935068/143831290-9424463c-5631-4ec4-a8e1-971957945a9a.png)

</details>

**Comment by JobcenterTycoon** [comment]
Anti Adblock on `magesypro.pro`

**Comment by JobcenterTycoon** [comment]
There is a anti adblock on `https://mage.si/1V6K`
