### ISSUE TITLE
google.com: irrelevant ads being shown on google 

### ISSUE THREAD

**Issue by devqueue** [uBlockOrigin/uAssets#11972]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=Basic+mechanism+of+a+Semiconductor+based+sensor&rlz=1C1BNSD_enSA970SA970&oq=ba&aqs=chrome.0.69i59l2j69i57j69i59j0i67j69i60l3.875j0j7&sourceid=chrome&ie=UTF-8`

### Category

ads

### Describe the issue

I'm seeing these irrelevant ads as search results. I am not sure  why is this happening. but I am guessing there is some JavaScript that's injecting html divs into the dom. I suppose its some sort of malware on my end. But I was expecting it to be be blocked by UBO and i wanted to see it marked red in the logs. Can someone please help me figure this out

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (83)](https://user-images.githubusercontent.com/55657198/156106426-1b31eef2-ca03-4d1f-ab7d-7712f445d416.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79785
  cosmetic: 41364
  scriptlet: 16491
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64097-9, 7m
    easyprivacy: 26631-122, 7m
    plowe-0: 3673-805, 7m
    ublock-abuse: 72-0, 7m
    ublock-badware: 3899-84, 7m
    ublock-filters: 30278-157, 7m
    ublock-privacy: 204-2, 7m
    ublock-unbreak: 1720-39, 7m
    urlhaus-1: 8437-0, 7m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 263 ms (selfie)
  maxAssetCacheWait: 314 ms
```
</details>

**Comment by uBlock-user** [comment]
> Can someone please help me figure this out

Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).
