### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by spitsnaugle** [uBlockOrigin/uAssets#11983]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/?shva=1`

### Category

breakage

### Describe the issue

Ublock removes email reader window after loads.
On macbook pro, in chrome, no other adblock installed. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1610" alt="Screen Shot 2022-03-01 at 10 02 06 AM" src="https://user-images.githubusercontent.com/69528597/156193346-79da70ca-ac0e-425a-8b81-a110685be9bd.png">
<img width="1644" alt="Screen Shot 2022-03-01 at 10 01 53 AM" src="https://user-images.githubusercontent.com/69528597/156193357-533190b9-a23c-47aa-bdf7-4480062ecf3b.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79740
  cosmetic: 41250
  scriptlet: 16496
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63931-9, 3d.16h.28m
    easyprivacy: 26620-122, 3d.16h.24m
    plowe-0: 3673-805, 3d.15h.31m
    ublock-abuse: 77-0, 3d.13h.22m
    ublock-badware: 3863-83, 3d.13h.3m
    ublock-filters: 30335-157, 3d.10h.33m
    ublock-privacy: 202-2, 3d.10h.24m
    ublock-unbreak: 1718-39, 3d.8h.23m
    urlhaus-1: 8437-0, 9h.49m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3634 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 107
  no-cosmetic-filtering: true
  blockedDetails: 
    google.com: 104
    googleusercontent.com: 3
```
</details>

**Comment by spitsnaugle** [comment]
realized duplicate posting, issues still remains though.

**Comment by uBlock-user** [comment]
> issues still remains though.

Did you refresh the page ?

**Comment by spitsnaugle** [comment]
Just updated lists, now works, I just switched from adblock to Ublock a week ago, this is a bit new. Sorry.

**Comment by okiehsch** [comment]
No problem
