### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by joshuahighley** [uBlockOrigin/uAssets#11982]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

Body of emails not appearing when uBlock Origin is active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79784
  cosmetic: 41371
  scriptlet: 16446
  html: 624
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30840-27, 1m
    ublock-badware: 3903-3, 1m
    ublock-privacy: 208-0, 1m
    ublock-abuse: 72-0, 1m
    ublock-unbreak: 1731-0, 1m
    easylist: 64100-615, 1m
    easyprivacy: 26634-571, 1m
    urlhaus-1: 8437-0, 1m
    plowe-0: 3673-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1199 ms (selfie)
  maxAssetCacheWait: 139 ms
popupPanel: 
  blocked: 76
  blockedDetails: 
    google.com: 76
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906

**Comment by okiehsch** [comment]
Hm, the filters are up to date according to the configuration.

**Comment by uBlock-user** [comment]
user also has to refresh the page and not open another mail first.
