### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by ggutierrezdieck** [uBlockOrigin/uAssets#11984]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

Gmail emails fail to load when Ublock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79878
  cosmetic: 41257
  scriptlet: 16460
  html: 619
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30922-27, 3d.21h.4m
    ublock-badware: 4034-3, 3d.21h.9m
    ublock-privacy: 202-0, 3d.21h.8m
    ublock-abuse: 77-0, 3d.21h.3m
    ublock-unbreak: 1726-0, 3d.21h.7m
    easylist: 63894-613, 3d.21h.6m
    easyprivacy: 26620-571, 3d.21h.5m
    urlhaus-1: 8437-0, 1d.38m
    plowe-0: 3673-2, 1d.39m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 193 ms (selfie)
  maxAssetCacheWait: 72 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 2
```
</details>

**Comment by uBlock-user** [comment]
#11906
