### ISSUE TITLE
feedbin.com: breakage

### ISSUE THREAD

**Issue by thomas-goerlich** [uBlockOrigin/uAssets#11989]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://feedbin.com/`

### Category

breakage

### Describe the issue

If i add a new rss feed on feedbin.com the buttons for cancel/add at the bottom of the dialog are not visible (see screenshots). I can see that uBlock blocks three elements on the side and if i disable it, it works fine.

Be ware that you need an account on feedbin.com and - as far as i know - there are no free accounts.

The affected html looks as follows if that helps:
![grafik](https://user-images.githubusercontent.com/1237975/156216174-06eee477-302f-41a7-b850-036cc120476a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

This is how it looks with uBlock enabled
![firefox_N1mIRUjAZF](https://user-images.githubusercontent.com/1237975/156209893-4ed0fbdf-b54a-4be4-9c82-b08b4dfb9390.png)

This is how it looks with uBlock disabled (see cancel/add area at the bottom)
![firefox_1Zncxv2pjW](https://user-images.githubusercontent.com/1237975/156209938-e34e80be-452f-4df3-8496-119bf62a2c36.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 91066
  cosmetic: 100327
  scriptlet: 19393
  html: 626
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 5d.17m
    ublock-annoyances: 4419-8, 3d.5h.47m
    fanboy-thirdparty_social: 69-0, 6d.7h.27m
    fanboy-annoyance: 60776-45649, 6d.19h.3m
    fanboy-cookiemonster: 22326-126, 6d.19h.4m
    fanboy-social: 23179-33, 3d.5h.49m
  default: 
    user-filters: 3-0, never
    ublock-filters: 30933-82, 3d.5h.52m
    ublock-badware: 3867-3, 3d.5h.50m
    ublock-privacy: 198-0, 3d.5h.48m
    ublock-abuse: 72-0, 2d.6h.25m
    ublock-unbreak: 1729-1, 3d.1h.44m
    easylist: 63950-641, 3d.5h.54m
    easyprivacy: 26624-628, 3d.5h.53m
    plowe-0: 3673-3, 1d.5h.20m
    DEU-0: 5505-3, 1d.1h.19m
    urlhaus-1: 8437-0, 21h.18m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 511 ms (selfie)
  maxAssetCacheWait: 331 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
maybe is working:

`feedbin.com#@#.subscribe-footer`

due to FA (fanboy-annoyance)

@ryanbr

**Comment by thomas-goerlich** [comment]
This does work if i add it to my filters, thanks!
