### ISSUE TITLE
corneey.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1199]
URL(s) where the issue occurs

`http://corneey.com/wsZcsX`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `@@||corneey.com^$generichide`
It seems the rule could be applied on the following domains as well:

```
corneey.com
sh.st
ceesty.com
destyy.com
festyy.com
gestyy.com
clkmein.com
viid.me
cllkme.com
```

**Comment by ghajini** [comment]
`http://gestyy.com/eeFud6`
& all similar sites
Popup ads

This work & covered for all domains

`corneey.com,sh.st,ceesty.com,destyy.com,festyy.com,gestyy.com,clkmein.com,cllkme.com##+js(acis, Math, zfgloaded)`
