### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by PFotosintesis** [uBlockOrigin/uAssets#11990]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/`

### Category

breakage

### Describe the issue

Today I entered my gmail to see what they had sent me. Upon entering everything is fine until you hit the mail where nothing appears. Precisely this is solved when uBlock is deactivated.

As you can see in the images with the uBlock activated it does not load the mail, but when it is deactivated it loads perfectly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![P1](https://user-images.githubusercontent.com/100715413/156220134-9dc0fc72-8448-438a-af64-09afd89ac04c.png)
![p2](https://user-images.githubusercontent.com/100715413/156220141-6a33476b-4596-4ceb-ac50-5985e4030570.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 82641
  cosmetic: 45826
  scriptlet: 16683
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63960-9, 2d.10h.54m
    easyprivacy: 26626-122, 2d.10h.53m
    plowe-0: 3670-803, 9d.11h.48m
    spa-0: 3796-29, 15h.54m
    spa-1: 4244-165, 2d.10h.55m
    ublock-abuse: 72-0, 2d.10h.52m
    ublock-badware: 3863-83, 2d.10h.51m
    ublock-filters: 30331-215, 2d.10h.50m
    ublock-privacy: 202-2, 2d.10h.49m
    ublock-unbreak: 1718-40, 2d.10h.48m
    urlhaus-1: 8296-1, 15h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  uiTheme: dark
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 491 ms (selfie)
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 6
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

You didn't.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11906

**Comment by iam-py-test** [comment]
@PFotosintesis please:
- Only test on up-to-date filterlists
- Check for duplicate issues
Those checkboxes are there for a reason, please don't ignore them and just check them all
