### ISSUE TITLE
Vidéo PUB not blocked by UBO

### ISSUE THREAD

**Issue by absynteZero** [uBlockOrigin/uAssets#12]
Vidéo pub not blocked by UblockOrigin in advanced setting and minimal configuration

Url: <http://www.d8.tv/pid5323-d8-live.html#>

My settings:

www.d8.tv * image noop
www.d8.tv akamaihd.net * noop
www.d8.tv d8.tv * noop
www.d8.tv ec2-52-29-187-219.eu-central-1.compute.amazonaws.com * noop
www.d8.tv fr-canalplus.cdn.videoplaza.tv * noop
www.d8.tv fr-canalplus.videoplaza.tv * noop
www.d8.tv instantshare.d8.tv * noop
www.d8.tv media.canal-plus.com * noop
www.d8.tv media.canal-plus.com.s0.frz.io * noop
www.d8.tv media.canal-plus.com.s1.frz.io * noop
www.d8.tv player.canalplus.fr * noop
www.d8.tv service.canal-plus.com * noop
www.d8.tv videoplaza.tv * noop
www.d8.tv www.d8.tv * noop

my lists

<http://www.noelshack.com/2016-14-1460064364-captureublock.png>

- Browser/version: Firefox x64 45.0.1
- uBlock Origin version: 1.6.8

**Comment by absynteZero** [comment]
solved by experimental filter

**Comment by absynteZero** [comment]
solved by blocking "images" ..... (??)

**Comment by IDKwhattoputhere** [comment]
Can't reproduce. Even tried a french VPN.

**Comment by gorhill** [comment]
Can't reproduce either.
