### ISSUE TITLE
free-torrents.org websockets

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#120]
### URL(s) where the issue occurs

http://free-torrents.org/

### Describe the issue

Background ads on that website, appear a few seconds after full page load. According to logger, uBO consider website's websockets as clear (blocking only websocket from marketgid, but skipping websockets from free-torrents.org - [scr1](http://i.imgur.com/UGQunX2.jpg) and [scr2](http://i.imgur.com/Vuroxfm.jpg)) when actually they aren't.

### Screenshot(s)

[Website with uBO+its default filter lists](http://i.imgur.com/Kxyhpew.jpg)

[Website with uBO+its default filter lists+RUS: Adguard Russian Filter+RUS: BitBlock List+RUS: RU AdList](http://i.imgur.com/mholm4w.jpg)

### Versions

- Browser/version: Cyberfox 48.0.2, Firefox 49.0b7
- uBlock Origin version: 1.9.2

### Settings

Default settings

Filter lists:
uBlock filters
uBlock filters – Badware risks‎
uBlock filters – Privacy‎
uBlock filters – Unbreak‎
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList
EasyPrivacy‎
Malvertising filter list by Disconnect‎
RUS: Adguard Russian Filter
RUS: BitBlock List
RUS: RU AdList

### Notes

Same browsers + ABP 2.7.3,  Adblock Warning Removal List‎, RU AdList+EasyList - [all is ok](http://i.imgur.com/oWkvLZA.jpg) (because of `|wss://free-torrents.org/`).
Thanks to @dimisa-RUAdList, he advised a working filter `||free-torrents.org^$websocket`, which blocking all the site's websockets well.

**Comment by TheFinalCut83** [comment]
Many thanks!

**Comment by gorhill** [comment]
Actually, I am confused... `|wss://free-torrents.org/` is being matched by uBO, and the websocket connection is reported as being blocked. The page displays fine with no ads without the new filter I just added.

**Comment by gorhill** [comment]
Did you ensure you RUAdlist was up to date with uBO? The filter `|wss://free-torrents.org/` was added 15 hours ago: <https://hg.adblockplus.org/ruadlist/rev/d277c4ba858c>.

**Comment by gorhill** [comment]
Ugh, never mind, was testing on Chromium. Things occur differently on Firefox. Need more coffee.

**Comment by dimisa-RUAdList** [comment]
http://free-torrents.pw/
`||free-torrents.pw^$websocket`

**Comment by gorhill** [comment]
Thanks. I need to find out why `*$websocket,domain=free-torrents.org` did not work as expected.
