### ISSUE TITLE
ceesty.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1200]
URL(s) where the issue occurs

`http://ceesty.com/wsnVoW`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `@@||ceesty.com^$generichide
`

**Comment by SMed79** [comment]
```
ceesty.com
clkme.me
clkmein.com
cllkme.com
corneey.com
destyy.com
festyy.com
gestyy.com
sh.st
shorte.st
skiip.me
skipp.io
viid.me
wiid.me
```

**Comment by KiLL4FuNK** [comment]
http://festyy.com/wIegdr @mapx-  Anti-Adblock

**Comment by mapx-** [comment]
I get no issue

**Comment by KiLL4FuNK** [comment]
`http://ceesty.com/wLyvvp`

Anti-Adblock

**Comment by mapx-** [comment]
I get it randomly (only chrome), could you test
`ceesty.com##+js(set-constant.js, adsBlockerDetector, noopFunc)`
or
`@@||ceesty.com^*ad$image,first-party`

**Comment by KiLL4FuNK** [comment]
It works perfect

`ceesty.com##+js(set-constant.js, adsBlockerDetector, noopFunc)`
