### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by Reymen06** [uBlockOrigin/uAssets#12006]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/amp/s/www.hurriyet.com.tr/amp/gundem/kiev-sokak-catismasina-hazirlaniyor-barikatlar-kuruldu-42014470`

### Category

breakage

### Describe the issue

Video won't open with uBlock enabled 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 153859
  cosmetic: 137253
  scriptlet: 33579
  html: 634
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 62077-5097, 6h.18m
    adguard-spyware: 26398-1192, 6h.18m
    curben-phishing: 11484-2, 6h.18m
    curben-pup: 387-0, 6h.18m
    adguard-annoyance: 50471-4357, 6h.18m
    adguard-social: 15948-1624, 6h.18m
    fanboy-thirdparty_social: 68-1, 6h.18m
    fanboy-annoyance: 66237-55072, 6h.18m
    fanboy-cookiemonster: 23326-13828, 6h.18m
    fanboy-social: 23184-13515, 6h.18m
    ublock-annoyances: 4437-7, 6h.18m
    dpollock-0: 10347-489, 6h.18m
    mvps-0: 8730-1497, 6h.18m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30900-290, 6h.18m
    ublock-badware: 3903-3, 6h.18m
    ublock-privacy: 208-1, 6h.18m
    ublock-abuse: 72-0, 6h.18m
    ublock-unbreak: 1737-0, 6h.18m
    adguard-mobile: 7280-229, 6h.21m
    easylist: 64083-24557, 6h.18m
    easyprivacy: 26634-11076, 6h.18m
    urlhaus-1: 8437-0, 6h.18m
    plowe-0: 3673-2, 6h.18m
    TUR-0: 8590-256, 6h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 592 ms (selfie)
  maxAssetCacheWait: 379 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    google.com: 12
    ampproject.org: 8
    csp.withgoogle.com: 1
    us-central1-amp-error-reporting.cloudfunctions.net: 1
```
</details>

**Comment by mapx-** [comment]
google ? it will land here:

`https://www.hurriyet.com.tr/gundem/kiev-sokak-catismasina-hazirlaniyor-barikatlar-kuruldu-42014470`

no breakage on my end desktop / mobile

**Comment by uBlock-user** [comment]
> - [X] I did not answer truthfully to **all** the above checkpoints

He certainly did not.

**Comment by ghajini** [comment]
amp page is triggered ,it's triggered only when slow network speed

**Comment by mapx-** [comment]
@Reymen06 if you still can reproduce the issue:

Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by JobcenterTycoon** [comment]
@ghajini firefox can simulate slow internet connection and a smartphone screen. I did both but the video still working fine

**Comment by bandaid** [comment]
It is reproducible. It is not a slow internet connection.
