### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by PrismG1** [uBlockOrigin/uAssets#12016]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Describe the issue

In tweet containing video, Only video doesn't show up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![novideo](https://user-images.githubusercontent.com/100815867/156481314-4bdbe486-2ee3-4b25-93e4-31fe4e34a05a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 81277
  cosmetic: 47564
  scriptlet: 16430
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30807-29, 10h.1m
    ublock-badware: 3903-3, 10h
    ublock-privacy: 208-0, 9h.59m
    ublock-abuse: 72-0, 9h.58m
    ublock-unbreak: 1731-0, 9h.56m
    easylist: 64087-621, 9h.55m
    easyprivacy: 26634-575, 9h.54m
    urlhaus-1: 8025-1, 9h.53m
    plowe-0: 3673-2, 2d.21h.46m
    KOR-1: 8142-3, 10h.2m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 11
  no-cosmetic-filtering: true
  no-popups: true
  blockedDetails: 
    twitter.com: 6
    app.link: 1
    branch.io: 3
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
no breakage on my end. Disable any other addon and test again.

![image](https://user-images.githubusercontent.com/10303732/156503053-3fa2d8fa-5a2b-4d27-8ac2-74b7cd641130.png)

**Comment by PrismG1** [comment]
I reinstalled uBlock and somehow it solved, Thanks!
