### ISSUE TITLE
act.wemove.eu: breakage

### ISSUE THREAD

**Issue by genuinejanbar** [uBlockOrigin/uAssets#12015]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://act.wemove.eu/campaigns/2981?utm_campaign=20220302_EN_box&utm_medium=email&utm_source=civimail-43801`

### Category

[unknown]

### Describe the issue

Hi all,
when I filled a form on that site and click send I get info: "Sorry, it seems a network error prevented the form from loading completely. Please refresh the page and try again." Whenever I try to send it again I've got the same text again. uBlock is switched off on that site, but something is not working and of course, it WAS working a couple of weeks ago.

Best regards,
Janusz.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 81200
  cosmetic: 48687
  scriptlet: 16652
  html: 635
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-0, never
    ublock-filters: 30848-27, 23h.25m
    ublock-badware: 3903-3, 19h.23m
    ublock-privacy: 208-0, 19h.22m
    ublock-abuse: 72-0, 19h.21m
    ublock-unbreak: 1731-0, 19h.19m
    easylist: 64063-619, 19h.18m
    easyprivacy: 26634-584, 19h.17m
    urlhaus-1: 8437-0, 2h.50m
    plowe-0: 3673-2, 2d.37m
    POL-0: 7777-33, 2h.49m
    POL-2: 1276-46, 2h.51m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9780 ms (selfie)
  maxAssetCacheWait: 2035 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
No issue on my end signing the petition
Did you disable Enhanced Tracking Protection in firefox ?

**Comment by genuinejanbar** [comment]
I use only standart option, not enhanced not my own. Maybe I should an exclusions set for that domens?Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: [unknown] (Issue #12015)Data: 2022-03-02 20:56Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
No issue on my end signing the petition
Did you disable Enhanced Tracking Protection in firefox ?

**Comment by genuinejanbar** [comment]
Well it wasn't true. I have had that option on but I set it now off for that site and set off a uBlock and nothing changed...Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: [unknown] (Issue #12015)Data: 2022-03-02 20:56Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
No issue on my end signing the petition
Did you disable Enhanced Tracking Protection in firefox ?

**Comment by mapx-** [comment]
Disable any other addon, test again

**Comment by genuinejanbar** [comment]
Why you closed it so fast?Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: breakage (Issue #12015)Data: 2022-03-04 18:50Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
Closed #12015.

**Comment by genuinejanbar** [comment]
Ok, ok - we just here in Poland almost 600 000 refugees have to care so, not so many time to provide that kind of feedback..., but in the couple of minutes I'll do it!Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: breakage (Issue #12015)Data: 2022-03-04 19:07Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
Provide feedback

**Comment by genuinejanbar** [comment]
Now that site act.wemove.eu works properly but previously closed case is not solved. Function "Pokaz obrazki" on poczta.interia.pl site still not works. Only uBlock Origin is working now but not on that sites.Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: breakage (Issue #12015)Data: 2022-03-04 20:00Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
Reopened #12015.

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by genuinejanbar** [comment]
![Wemove uBlock zrzut ekranu 2022-03-05 173431](https://user-images.githubusercontent.com/100475706/156892236-fcd62beb-8e66-4e1a-a8f6-f79f5473d989.png)
And I get the same text: Sorry, it seems a network error prevented the form from loading completely. Please refresh the page and try again.

**Comment by genuinejanbar** [comment]
Now with uBlock OFF on that site
![Wemove uBlock is OFF Zrzut ekranu 2022-03-05 174812](https://user-images.githubusercontent.com/100475706/156892510-d42ef160-a3a1-432d-b435-b22496d4830a.png)
and get the same text as up

**Comment by mapx-** [comment]
Are you saying you get the same error even disabling uBO ? In this case it's something on your side.

**Comment by genuinejanbar** [comment]
Only on THAT site...

**Comment by mapx-** [comment]
Could be some antivirus software or rules at router level blocking some requests or even your provider.
As I told you no issue on my end.

**Comment by genuinejanbar** [comment]
With Opera browser I have not that kind of problems and why that whitelisted doc is blocked? I think that doc contains formular from that site act.wemove.eu.Temat: Re: [uBlockOrigin/uAssets] act.wemove.eu: breakage (Issue #12015)Data: 2022-03-05 18:29Nadawca: "mapx-" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 
Could be some antivirus software or rules at router level blocking some requests or even your provider.
As I told you no issue on my end.
