### ISSUE TITLE
festyy.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1201]
URL(s) where the issue occurs

`http://festyy.com/wa16Tr`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `@@||festyy.com^$generichide`
It seems the rules could apply on the following domains as well:

```
corneey.com
sh.st
ceesty.com
destyy.com
festyy.com
gestyy.com
clkmein.com
viid.me
cllkme.com
```
