### ISSUE TITLE
kreiszeitung.de: breakage

### ISSUE THREAD

**Issue by hinzke** [uBlockOrigin/uAssets#12019]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kreiszeitung.de/lokales/verden/thedinghausen-ort50200/`

### Category

breakage

### Describe the issue

You cannot click the first teased article

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 81463
  cosmetic: 44678
  scriptlet: 16433
  html: 624
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30813-27, 1d.16h.25m
    ublock-badware: 3903-3, 1d.16h.24m
    ublock-privacy: 208-0, 1d.16h.30m
    ublock-abuse: 72-0, 1d.16h.27m
    ublock-unbreak: 1731-0, 1d.16h.26m
    easylist: 64063-608, 1d.16h.29m
    easyprivacy: 26634-595, 1d.16h.28m
    urlhaus-1: 7991-0, 4h.54m
    plowe-0: 3673-2, 3d.19h.54m
    DEU-0: 5510-11, 4h.55m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 155 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1119 ms (selfie)
  maxAssetCacheWait: 184 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    cdntrf.com: 1
    d2wu036mkcz52n.cloudfront.net: 1
    googletagmanager.com: 1
    ioam.de: 2
    ippen.space: 1
    k5a.io: 2
    lp4.io: 1
```
</details>

**Comment by okiehsch** [comment]
> You cannot click the first teased article

Not sure what you mean by "teased" article but I can click all articles without issue as far as I can see.

**Comment by bandaid** [comment]
He means clicking on the article thumbnail link. All stories/articles work for me though

**Comment by hinzke** [comment]
Why closed, the first Article is not clickable

**Comment by okiehsch** [comment]
You mean the "Neue Tempoanzeige" article?

It's clickable on my end.

**Comment by hinzke** [comment]
yes. the first article with the grey background
