### ISSUE TITLE
toy-people.com: ads

### ISSUE THREAD

**Issue by a77841s** [uBlockOrigin/uAssets#12023]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.toy-people.com/?p=67790`

### Category

ads

### Describe the issue

white block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium Mobile: 98
filterset (summary): 
  network: 104171
  cosmetic: 115104
  scriptlet: 18921
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50510-164, 21h.12m
    adguard-social: 16003-785, 21m
    adguard-spyware-url: 491-1, 21h.11m
  default: 
    user-filters: 2-0, never
    CHN-0: 28065-87, 21h.15m
    adguard-mobile: 7285-38, 21h.15m
    easylist: 64094-231, 21h.14m
    easyprivacy: 26639-250, 21h.14m
    plowe-0: 3673-896, 21h.14m
    ublock-abuse: 72-0, 21h.14m
    ublock-badware: 3899-85, 21h.14m
    ublock-filters: 30350-514, 21h.14m
    ublock-privacy: 204-5, 21h.14m
    ublock-unbreak: 1726-45, 21h.14m
    urlhaus-1: 8437-0, 21h.14m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 585 ms (selfie)
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 53
  blockedDetails: 
    toy-people.com: 13
    d31qbv1cthcecs.cloudfront.net: 1
    doubleclick.net: 7
    facebook.com: 3
    google-analytics.com: 1
    googlesyndication.com: 4
    onesignal.com: 1
    twitter.com: 16
    youtube.com: 7
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
toy-people.com##[class*="rightAd_"]
toy-people.com##[id^="toy_home_"]:empty
```

**Comment by mapx-** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
Notified EL China author, as the issue doesn't require extended syntax.
