### ISSUE TITLE
timer function of duckduckgo not working

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#12026]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://duckduckgo.com/?q=timer&t=raspberrypi&ia=answer`

### Describe the issue

there is a timer function in duckduckgo, it rings and shakes without ublock origin if it reaches zero, with it it dose nothing but count to zero which makes it useless 

### Screenshot(s)

cant capture this behavior with just one image, but if you insist:

![Screenshot_2022-03-03_19-16-00](https://user-images.githubusercontent.com/45161625/156626756-12627d2f-2cf7-447e-b977-df505aac6ace.png)

### Notes

just test it, type in "timer" in duckduckgo search, set it to 1 minute and wait, it will do nothing if it reaches 0, then switch ublock off for that domain reload the page and try it again, you will hear a chime and see that the timer area is shaking a bit...

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79508
  cosmetic: 41288
  scriptlet: 16499
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63961-9, 17h.49m
    easyprivacy: 26626-122, 17h.48m
    plowe-0: 3670-803, 7d.21h.49m
    ublock-abuse: 77-0, 17h.47m
    ublock-badware: 3863-83, 17h.46m
    ublock-filters: 30357-157, 17h.45m
    ublock-privacy: 202-2, 17h.44m
    ublock-unbreak: 1718-39, 17h.43m
    urlhaus-1: 8190-1, 17h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1396 ms (selfie)
  maxAssetCacheWait: 652 ms
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by uBlock-user** [comment]
Rings and shakes as expected. Test on default settings/lists + all other extensions disabled.

**Comment by JobcenterTycoon** [comment]
Works fine for me too

**Comment by bandaid** [comment]
Works fine for me too, is it to shake monitor?
