### ISSUE TITLE
[nsfw] classroom.google.com: privacy

### ISSUE THREAD

**Issue by bfine04** [uBlockOrigin/uAssets#12029]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://classroom.google.com/c/MzgzMTA1OTgyMjQw`

### Category

privacy

### Describe the issue

it has my full name on it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 96
filterset (summary): 
  network: 79242
  cosmetic: 41363
  scriptlet: 16467
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64097-9, 2d.9h.44m
    easyprivacy: 26634-122, 2d.9h.43m
    plowe-0: 3675-805, 22m
    ublock-abuse: 72-0, 2d.9h.42m
    ublock-badware: 3924-84, 19m
    ublock-filters: 30214-155, 18m
    ublock-privacy: 204-2, 17m
    ublock-unbreak: 1720-39, 16m
    urlhaus-1: 7901-0, 8m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7800 ms (selfie)
  maxAssetCacheWait: 3604 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    google.com: 18
```
</details>

**Comment by bandaid** [comment]
uBO has nothing to do with Google policies.
