### ISSUE TITLE
incredibox.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1202]
URL(s) where the issue occurs

`http://www.incredibox.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try the following ones:
```
incredibox.com##body > div:nth-of-type(6)
incredibox.com##body > div:nth-of-type(5)
```
