### ISSUE TITLE
twitch.tv: breakage

### ISSUE THREAD

**Issue by smith330** [uBlockOrigin/uAssets#12027]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/codes_rousseau`

### Category

breakage

### Describe the issue

L'extension quizkit ne s'affiche pas 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 132137
  cosmetic: 183489
  scriptlet: 33485
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 3h.59m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 4h.3m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 27d.6h.33m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 4h.1m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 0-0, never
    adguard-annoyance: 50559-203, 4h.5m
    adguard-generic: 62117-1253, 4h.56m
    adguard-mobile: 7286-46, 5h
    adguard-spyware: 26410-847, 4h.58m
    block-lan: 44-0, 1h.59m
    fanboy-annoyance: 61663-2913, 2d.2h.24m
    ublock-annoyances: 4372-470, 5h.2m
  default: 
    user-filters: 28-9, never
    FRA-0: 25974-35, 5h.4m
    easylist: 64133-1092, 4h.54m
    easyprivacy: 26642-10964, 4h.52m
    plowe-0: 3673-974, 2d.2h.28m
    ublock-abuse: 72-1, 4h.50m
    ublock-badware: 3899-260, 4h.48m
    ublock-filters: 30264-3540, 4h.46m
    ublock-privacy: 204-39, 4h.44m
    ublock-unbreak: 1720-111, 4h.7m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 14 redacted]
hostRuleset: 
  added: [array of 1266 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  collapseBlocked: false
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  blockingProfiles: 11111/#F00 11011/#C0F 11001/#00F 00001
  selfieAfter: 3
supportStats: 
  allReadyAfter: 20086 ms (selfie)
  maxAssetCacheWait: 4614 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    amazon-adsystem.com: 3
    amplitude.com: 1
    imrworldwide.com: 1
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
1. test using only the default setup, then add 1 by 1 the other lists and see which one provoking the issue
2. Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)
