### ISSUE TITLE
9anime.to: nuisance

### ISSUE THREAD

**Issue by Duqz557** [uBlockOrigin/uAssets#12021]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.to/watch/naruto-shippuden.qv3/ep-369`

### Category

nuisance

### Describe the issue

There is a popup. Tried blocking the element but it only blocks the whole screen instead.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/100856569/156590688-11d2cf96-986c-49df-8995-98df08e90dd7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79735
  cosmetic: 41288
  scriptlet: 16499
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63969-9, 3d.22h.11m
    easyprivacy: 26628-122, 3d.22h.10m
    plowe-0: 3673-805, 3d.22h.9m
    ublock-abuse: 77-0, 3d.22h.7m
    ublock-badware: 3863-83, 3d.22h.5m
    ublock-filters: 30325-157, 3d.22h.4m
    ublock-privacy: 202-2, 3d.22h.3m
    ublock-unbreak: 1718-39, 3d.22h.2m
    urlhaus-1: 8437-0, 13h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 815 ms (selfie)
  maxAssetCacheWait: 377 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    9anime.to: 1
    addresseepaper.com: 1
    addthis.com: 1
    amung.us: 1
    disqus.com: 1
    fastestvolcano.com: 1
    pawnoutletprimary.com: 3
    venetrigni.com: 1
    viglink.com: 2
    zap.buzz: 9
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5009627225e05698097d5f275207a5c664446e1b

force update ublock filters list.
