### ISSUE TITLE
welt.de: breakage

### ISSUE THREAD

**Issue by FSC69** [uBlockOrigin/uAssets#12032]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.welt.de/politik/ausland/video237296515/Ukraine-Krieg-Russland-zeigt-Anzeichen-eines-zerfallenden-Imperiums.html`

### Category

breakage

### Describe the issue

Videos are disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 82002
  cosmetic: 44700
  scriptlet: 16467
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5510-0, 3m
    easylist: 64183-16, 3m
    easyprivacy: 26642-133, 3m
    plowe-0: 3675-806, 3m
    ublock-abuse: 72-0, 3m
    ublock-badware: 3924-85, 3m
    ublock-filters: 30214-177, 3m
    ublock-privacy: 204-2, 3m
    ublock-unbreak: 1720-40, 3m
    urlhaus-1: 8437-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1053 ms (selfie)
  maxAssetCacheWait: 840 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    asadcdn.com: 2
    nmrodam.com: 2
    privacy-mgmt.com: 1
```
</details>

**Comment by mapx-** [comment]
Working fine on my side (using german ip)
- needing german ip
- don't block the cookie stuff

**Comment by okiehsch** [comment]
I have to click play twice for the video to start but it plays without issue on my end too.
