### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by 404StrauberNotfound** [uBlockOrigin/uAssets#12038]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=F157geaXp_w`

### Category

ads

### Describe the issue

Ads are loading and playing as they normally would without Ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_NksRYBRNUp](https://user-images.githubusercontent.com/71330729/156761709-18d13a10-7c54-4b8f-9df4-1b558d482cf0.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79883
  cosmetic: 41320
  scriptlet: 16490
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64164-10, 17h.59m
    easyprivacy: 26629-122, 3d.19h.3m
    plowe-0: 3673-805, 6d.17h.47m
    ublock-abuse: 72-0, 3d.19h.2m
    ublock-badware: 3893-85, 3d.19h.1m
    ublock-filters: 30276-157, 3d.19h
    ublock-privacy: 204-2, 3d.18h.59m
    ublock-unbreak: 1718-39, 3d.18h.58m
    urlhaus-1: 8437-0, 22h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 725 ms (selfie)
  maxAssetCacheWait: 501 ms
popupPanel: 
  blocked: 117
  blockedDetails: 
    youtube.com: 88
    doubleclick.net: 7
    google.co.uk: 1
    google.com: 2
    googleadservices.com: 1
    googlesyndication.com: 15
    googlevideo.com: 3
```
</details>

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
