### ISSUE TITLE
faselhd.top: detection / video broken

### ISSUE THREAD

**Issue by alooool** [uBlockOrigin/uAssets#12033]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.faselhd.top/episodes/%d9%85%d8%b3%d9%84%d8%b3%d9%84-euphoria-%d8%a7%d9%84%d9%85%d9%88%d8%b3%d9%85-%d8%a7%d9%84%d8%ab%d8%a7%d9%86%d9%8a-%d8%a7%d9%84%d8%ad%d9%84%d9%82%d8%a9-4`

### Category

this website descover ublock when i play the video

### Describe the issue

when i play the video it tell me to remove adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79799
  cosmetic: 41312
  scriptlet: 16512
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    ara-0: null
  default: 
    user-filters: 2-0, never
    easylist: 63996-9, 3d.15h.44m
    easyprivacy: 26629-122, 3d.15h.43m
    plowe-0: 3670-803, 11d.17h.25m
    ublock-abuse: 72-0, 3d.15h.46m
    ublock-badware: 3899-84, 3d.15h.48m
    ublock-filters: 30366-158, 3d.15h.50m
    ublock-privacy: 204-2, 3d.15h.47m
    ublock-unbreak: 1718-39, 3d.15h.45m
    urlhaus-1: 8437-0, 5h.58m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 234 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cammpaign.com: 1
    googletagmanager.com: 3
    iclickcdn.com: 1
    jwpltx.com: 1
```
</details>

**Comment by mapx-** [comment]
- The anti adblocking message is there even disabling uBO, no detecting
- AR list is breaking the video, add:

```
*$xmlhttprequest,3p,domain=faselhd.top,badfilter
*$script,3p,domain=faselhd.top,badfilter
```

@smed79
