### ISSUE TITLE
app.simplifimoney.com: breakage

### ISSUE THREAD

**Issue by vdibiase** [uBlockOrigin/uAssets#12031]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.simplifimoney.com/`

### Category

breakage

### Describe the issue

Receive an invalid credentials error when logging in. However, there is no issue when logging in after disabling uBO. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 79746
  cosmetic: 41359
  scriptlet: 16490
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64066-9, 3d.6h.19m
    easyprivacy: 26629-122, 3d.6h.18m
    plowe-0: 3670-803, 11d.3h.20m
    ublock-abuse: 72-0, 3d.6h.17m
    ublock-badware: 3893-84, 3d.6h.16m
    ublock-filters: 30274-156, 3d.6h.14m
    ublock-privacy: 204-2, 3d.6h.13m
    ublock-unbreak: 1718-39, 3d.6h.12m
    urlhaus-1: 8437-0, 38m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 595 ms (selfie)
  maxAssetCacheWait: 266 ms
popupPanel: 
  blocked: 57
  blockedDetails: 
    bugsnag.com: 1
    launchdarkly.com: 52
    mixpanel.com: 1
    pendo.io: 2
    quicken.com: 1
```
</details>

**Comment by uBlock-user** [comment]
try `||cloudflare.com/cdn-cgi/trace$xmlhttprequest,3p,redirect-rule=noop.txt,domain=~1bit.space|~1bitspace.com|~funimation.com,badfilter`

**Comment by mapx-** [comment]
even completely disabling uBO I get an error creating an account

![image](https://user-images.githubusercontent.com/10303732/156714663-794b1e93-ad93-4fc7-ba5b-f21b2d436c54.png)
