### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Alwisek** [uBlockOrigin/uAssets#12036]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

when I enter the video, at the beginning I see an advertisement, but during the video, none of it shows up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 97
filterset (summary): 
  network: 81276
  cosmetic: 48692
  scriptlet: 16677
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7773-8, 12h.54m
    POL-2: 1273-13, 12h.54m
    easylist: 64164-34, 12h.51m
    easyprivacy: 26642-122, 12h.50m
    plowe-0: 3675-815, 12h.49m
    ublock-abuse: 72-0, 12h.47m
    ublock-badware: 3924-85, 12h.45m
    ublock-filters: 30235-198, 12h.44m
    ublock-privacy: 204-2, 12h.42m
    ublock-unbreak: 1720-40, 12h.41m
    urlhaus-1: 8437-0, 12h.40m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3639 ms (selfie)
  maxAssetCacheWait: 256 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    youtube.com: 4
    doubleclick.net: 2
    sentry.io: 2
    ytimg.com: 1
```
</details>

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636
