### ISSUE TITLE
ur.ly [ADS] [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1203]
URL(s) where the issue occurs

`http://ur.ly/xWG3Vro`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try:
```
ur.ly##script:inject(abort-current-inline-script.js, uuidv4)
##a[href^="http://ur.ly/cnt.php"]
```

**Comment by SMed79** [comment]
```
||ur.ly/js/
||ur.ly/images/step/
```
https://forums.lanik.us/viewtopic.php?f=62&t=39586
