### ISSUE TITLE
mangasee123.com: breakage

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#12030]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mangasee123.com/search/`

### Category

breakage

### Describe the issue

Once you go to the search functionality, it won't show anything. The problem dissapears once you disable Ublock.

The reason for this is the following filter: 

`*$script,3p,denyallow=cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com|hcaptcha.com|jsdelivr.net|recaptcha.net,domain=mangasee123.com`

Once you allow any of the sites, the problem gets fixed. But the issue is with jsdelivr.maply.net and when that is allowed, the problem dissappears. Should be an easy fix.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://preview.redd.it/h6ik3ne3o2l81.jpg?width=1279&format=pjpg&auto=webp&s=511adba0b3778c89f1fda609838ec3f6d5929950

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 80100
  cosmetic: 42666
  scriptlet: 19226
  html: 635
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4380-4, 23h.41m
  default: 
    user-filters: 57-0, never
    ublock-filters: 30789-30, 2h.30m
    ublock-badware: 3903-3, 23h.41m
    ublock-privacy: 208-0, 23h.41m
    ublock-abuse: 72-0, 23h.41m
    ublock-unbreak: 1731-0, 23h.41m
    easylist: 64118-617, 23h.41m
    easyprivacy: 26641-571, 23h.41m
    urlhaus-1: 8437-0, 23h.41m
    plowe-0: 3674-2, 23h.41m
filterset (user): [array of 55 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 137 redacted]
hostRuleset: 
  added: [array of 394 redacted]
urlRuleset: 
  added: [array of 104 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 731 ms (selfie)
  maxAssetCacheWait: 410 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 2
    jsdelivr.map.fastly.net: 2
```
</details>

**Comment by Procyon-b** [comment]
I can't reproduce. The search functionnality works for me.
You've many rules and filters. It's probably caused by one of them.
