### ISSUE TITLE
Remove facil-iti.app & facil-iti.com from blocked URLs

### ISSUE THREAD

**Issue by ngouti87** [uBlockOrigin/uAssets#12035]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://cdn.facil-iti.app
https://ws.facil-iti.com
```

### Describe the issue

FACIL'iti is an inclusive solution that is installed on our clients' website. It allows users with disabilities to adapt the display of the website they are visiting according to their needs.
According to his/her disability, an internet user can activate specific filters to adapt the display. Our solution allows the website to meet the needs of each individual’s particular condition : visual issues, mobility troubles or cognitive disorders.
-> as an example, you can see the solution on these websites: `https://www.quaibranly.fr/en/`,  `https://www.infotbm.com/en/` etc..

Unfortunately, our solution is unduly blocked uBLock origin. It's why we are coming to you asking to 'whitelist' our domains *.facil-iti.app and *.facil-iti.com so that the solution can work and our common internet users could still use our inclusive solution.

I remain at your disposal
I'm looking forward to reading from you.

### uBlock Origin version

1.41.8

### Browser name and version

Firefox Browser 97.0.1

### Settings

- no change

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ngouti87** [comment]
an additional information that could be important, the following regex expression could also be problematic since it could target our js files : 
       /faciliti-tag. 

Thanks for your understanding.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/953c021f8716dbbedecae1fee79dbc4f83bfa328  Not a recent commit

`https://cdn.facil-iti.app/tags/faciliti-tag.min.js`  has a few privacy issues (localhost access, and fingerprinting). Can these be addressed.

**Comment by uBlock-user** [comment]
> Unfortunately, our solution is unduly blocked uBLock origin. 

I don't see any breakage @ngouti87 Report what's broken.
