### ISSUE TITLE
unblock https://go.fvtc.edu/acton/media/43715/fvtc-truck-driving-experience

### ISSUE THREAD

**Issue by manawa12** [uBlockOrigin/uAssets#12046]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

The block comes up for the following cite across my campus: 

`https://go.fvtc.edu/acton/media/43715/fvtc-truck-driving-experience`

please unblock

### Describe the issue

Students on campus must access 

`https://go.fvtc.edu/acton/media/43715/fvtc-truck-driving-experience`   

This site is blocked.  Please unblock

### uBlock Origin version

1.41.8

### Browser name and version

chrome

### Settings

no changes have been made

### Notes

no results.   All systems with uBlock cannot access this site.  I need to add the site to the white list or could you send me the instructions as to how to add it to the whitelist for 800 chromebooks that are managed by google workspace for education.
Thanks

**Comment by mapx-** [comment]
fixed in unbreak list

@ryan EP issue
