### ISSUE TITLE
bestpractices.ca.gov: nuisance

### ISSUE THREAD

**Issue by nanoha25** [uBlockOrigin/uAssets#12040]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://www.bestpractices.ca.gov/sysacq/roles.shtml#ProjectManager`

### Category

nuisance

### Describe the issue

The entire website and all of its sub-pages are essentially a full-page link that cannot be disabled through disabling scripts. Basically, whichever page you visit, as soon as you click anywhere that is not linked to a file, it will redirect you back to home page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/6c2kV0B

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 105869
  cosmetic: 51499
  scriptlet: 16568
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 0-0, 5h.22m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 5h.6m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 5h.21m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 5h.15m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-1, 5h.5m
    CHN-0: 28106-88, 5h.9m
  default: 
    user-filters: 3-0, never
    easylist: 64183-637, 5h.7m
    easyprivacy: 26642-177, 5h.10m
    plowe-0: 3675-2369, 5h.19m
    ublock-abuse: 72-0, 5h.14m
    ublock-badware: 3924-89, 5h.12m
    ublock-filters: 30203-174, 5h.13m
    ublock-privacy: 204-2, 5h.11m
    ublock-unbreak: 1720-40, 5h.8m
    urlhaus-1: 8437-0, 5h.4m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 376 ms (selfie)
  maxAssetCacheWait: 240 ms
popupPanel: 
  blocked: 3
  no-cosmetic-filtering: true
  no-scripting: true
  blockedDetails: 
    ca.gov: 2
    google.com: 1
```
</details>

**Comment by mapx-** [comment]
it seems to be a useless page

However, test

`bestpractices.ca.gov##+js(ra, href, [href="/"])`

**Comment by nanoha25** [comment]
> it seems to be a useless page
> 
> However, test
> 
> `bestpractices.ca.gov##+js(ra, href, [href="/"])`

I apologise but where should I put this? I can't seem to add it to "my rules". Should I add it to my personal filter? 

Thanks.

**Comment by Procyon-b** [comment]
You can also add this filter to remove the "underline" effect when moving the mouse over the text.
```
bestpractices.ca.gov##a:not([href]):style(text-decoration:none !important;)
```

If you still don't know where to add this: open ublock's dashboard, go to the "_My filters_" tab, and paste the filter in a blank line. You can add a comment (the line starts with a `!`) with a date and a link to this page to remember what it is used for.

**Comment by nanoha25** [comment]
Thanks to everyone who replied here. 
I have tried to create a custom filter like this below
`! 05/03/2022 03:17 http://http://www.bestpractices.ca.gov/ filter test
||http://www.bestpractices.ca.gov/sysacq/roles.shtml#ProjectManager##+js(ra, href, [href="/"])
||http://www.bestpractices.ca.gov/sysacq/roles.shtml#ProjectManager##a:not([href]):style(text-decoration:none !important;)`
for this page: 
[http://www.bestpractices.ca.gov/sysacq/roles.shtml#ProjectManager](url)

Unfortunately, the website behaviour remains the same. 
Maybe the way I use custom filter is wrong? I am copying the format from other working custom filters. 

Thanks for any help.

**Comment by mapx-** [comment]
We provided completely different filters, don't modify them, just add them in "my filters"

**Comment by mapx-** [comment]
ok, I added the filters in `uBlock filters` list.
Remove your wrong filters from `my filters` and update the list.
