### ISSUE TITLE
hubturkey.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1204]
URL(s) where the issue occurs

`https://www.hubturkey.net/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
try `@@||hubturkey.net/js/ads.js`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by llacb47** [comment]
Can't reproduce
