### ISSUE TITLE
dir50.net

### ISSUE THREAD

**Issue by mclovin74** [uBlockOrigin/uAssets#1205]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://dir50.net/t8vq30b3ehbx

### Describe the issue

antiadblock + popup

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/35187596/34647634-7fc5e322-f387-11e7-8e55-7012bb44b60e.png)

### Versions

- Browser/version: chrome 63.0.3239.84
- uBlock Origin version: 1.14.22

### Settings

- default settings + APB italian list

**Comment by zaphodbeebblebrox** [comment]
Add `dir50.net##script:inject(nano-setTimeout-booster.js)` for timer boosting?

**Comment by KiLL4FuNK** [comment]
antiadblock
