### ISSUE TITLE
surfline.com is broken by #11965

### ISSUE THREAD

**Issue by dafonso** [uBlockOrigin/uAssets#12051]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.surfline.com`

### Describe the issue

Seems like #11965 effectively breaks surfline report webpages.

Example: 
`https://www.surfline.com/surf-report/carcavelos/5842041f4e65fad6a7708bc0`

Panel with the report details is stuck loading with the loading animated icon.

Can you please revert this?

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 102484
  cosmetic: 0
  scriptlet: 32718
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 3m
    adguard-annoyance: 50591-43829, 3m
    adguard-generic: 62161-31630, 3m
    adguard-social: 16024-15454, 3m
    fanboy-thirdparty_social: 68-4, 3m
    ublock-annoyances: 4371-1434, 3m
  default: 
    user-filters: 1-0, never
    easylist: 64239-33935, 3m
    easyprivacy: 26642-358, 3m
    plowe-0: 3674-2374, 3m
    ublock-abuse: 72-0, 3m
    ublock-badware: 3929-651, 3m
    ublock-filters: 30203-9712, 3m
    ublock-privacy: 203-14, 3m
    ublock-unbreak: 1723-286, 3m
    urlhaus-1: 8437-0, 3m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 57 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 340 ms (selfie)
  maxAssetCacheWait: 301 ms
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
surfline.com#@#+js(nostif, , 1000)
surfline.com##body>div.ReactModalPortal
surfline.com##body:style(position: initial !important;)
```
The first one cancels the "bad filter", and the other 2 fix the anti-adblock.
