### ISSUE TITLE
9anime.id: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#12058]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/rumble-garanndoll-dub.jvv83/ep-1`

### Category

ads

### Describe the issue

When you click on a Video and stop it a pop up ad will display.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-03-05 164219](https://user-images.githubusercontent.com/100969549/156890305-6830448f-cacf-4222-bb9b-42a25efef94f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 97
filterset (summary): 
  network: 151891
  cosmetic: 186970
  scriptlet: 33278
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    DEU-0: null
  added: 
    adguard-annoyance: 50494-155, 3d.1h.25m
    adguard-generic: 62076-674, 3d.1h.25m
    adguard-mobile: 7281-44, 3d.1h.25m
    adguard-social: 15956-778, 3d.1h.25m
    adguard-spyware: 26403-809, 3d.1h.25m
    adguard-spyware-url: 491-12, 3d.1h.25m
    block-lan: 44-0, 3d.1h.25m
    curben-phishing: 10822-0, 21h.26m
    curben-pup: 386-0, 21h.25m
    dpollock-0: 10347-224, 3d.1h.25m
    fanboy-annoyance: 66267-8387, 3d.1h.25m
    fanboy-cookiemonster: 23345-23345, 3d.1h.25m
    fanboy-social: 23184-23184, 3d.1h.25m
    fanboy-thirdparty_social: 68-21, 3d.1h.25m
    mvps-0: 8730-1723, 3d.1h.25m
    ublock-annoyances: 4408-294, 3d.1h.24m
  default: 
    easylist: 64084-1219, 3d.1h.25m
    easyprivacy: 26634-10759, 3d.1h.25m
    plowe-0: 3673-1485, 3d.1h.24m
    ublock-abuse: 72-0, 3d.1h.24m
    ublock-badware: 3899-256, 3d.1h.24m
    ublock-filters: 30230-3403, 3d.1h.24m
    ublock-privacy: 204-40, 3d.1h.24m
    ublock-unbreak: 1720-113, 3d.1h.24m
    urlhaus-1: 8437-2, 21h.23m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 15 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  uiAccentCustom: true
  uiAccentCustom0: #2ea283
  uiTheme: dark
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 819 ms (selfie)
  maxAssetCacheWait: 855 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    9anime.id: 1
    addthis.com: 1
    amung.us: 1
    bidgear.com: 4
    fastestvolcano.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
vizcloud2.online##.xad-wrapper
```

**Comment by big-cat-loaf** [comment]
thank you :)

**Comment by sugarfreesweetener** [comment]
`9anime. id` - using console ultimately results in redirect I believe
