### ISSUE TITLE
mail.yandex.com.tr: ads

### ISSUE THREAD

**Issue by emrecansari** [uBlockOrigin/uAssets#12050]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yandex.com.tr/`

### Category

ads

### Describe the issue

Ads under the mail tabs are not blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81162
  cosmetic: 47641
  scriptlet: 16843
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8593-79, 1d.6h.8m
    easylist: 64139-25, 1d.6h.7m
    easyprivacy: 26642-127, 1d.6h.6m
    plowe-0: 3674-806, 28m
    ublock-abuse: 72-0, 1d.6h.5m
    ublock-badware: 3899-85, 1d.6h.4m
    ublock-filters: 30324-171, 1d.6h.3m
    ublock-privacy: 204-2, 1d.6h.1m
    ublock-unbreak: 1720-39, 1d.6h
    urlhaus-1: 7866-0, 26m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 408 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    yandex.ru: 20
```
</details>

**Comment by mapx-** [comment]
dor yandex subscribe other 2 lists:
`RUS: RU AdList` - from regional lists section in uBO

and `RU AdList: Counters` clicking here:
https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters

then test again
