### ISSUE TITLE
repco.com.au: breakage

### ISSUE THREAD

**Issue by aemondis** [uBlockOrigin/uAssets#12052]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.repco.com.au/en`

### Category

breakage

### Describe the issue

All basic functionality of the site upon load (location search in particular, which is totally non-functional) is unusable with an adblocker enabled (uBlock Origin & Adblock Plus tested). 
I had to add 
`https://www.repco.com.au/_ui/shared/js/analyticsmediator.js` 
in order to use basic store search functionality, a mandatory function before any further step.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 89690
  cosmetic: 44676
  scriptlet: 1
  html: 109
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 3330-0, 1313d.16h.13m
    ublock-badware: 37-0, 1313d.16h.11m
    ublock-privacy: 59-0, 1313d.16h.9m
    ublock-abuse: 273-2, 1313d.16h.7m
    ublock-unbreak: 547-1, 1312d.21h.26m
    easylist: 86057-213, 1312d.21h.24m
    easyprivacy: 15248-183, 1312d.21h.22m
    malware-0: 1131-0, 1313d.16h.5m
    malware-1: 25640-15, 1313d.16h.3m
    plowe-0: 2623-1, 1311d.17h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 255 ms
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    repco.com.au: 2
    bazaarvoice.com: 2
    brcdn.com: 1
    google.com: 6
    googletagmanager.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
`@@||repco.com.au/_ui/shared/js/analyticsmediator.js$script,1p`

EP issue @ryanbr

**Comment by phyco1991** [comment]
This issue is closed but appears to still be affecting the website in question, you cannot select your store location and have it persist beyond a reload of the page with uBlock Origin enabled.

**Comment by phyco1991** [comment]
> I selected `My Shop: Carnarvon` (after entering the postcode), then browsed a few pages, reloaded the page => `My Shop: Carnarvon` is still set

Looks like it is working now after a filter list update. Thanks!
