### ISSUE TITLE
sarzamindownload.com popup

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#12059]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sarzamindownload.com/tags/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF_%D9%86%D8%B1%D9%85_%D8%A7%D9%81%D8%B2%D8%A7%D8%B1/`

### Describe the issue

When you click on a text or a link, the page is redirected to an ads and a popup opens with the current page that the user was reading.

The popup URL: `https://oneshare.ir/pops/from-sdl-desktop/s2-dsk-12-140012/index.html`

### Notes

The popup code:
```
<script src="https://www.sarzamindownload.com/ppjs/combed.js" cf-async="false"></script>
<script>
    BetterJsPop.add('https://oneshare.ir/pops/from-sdl-desktop/dsk-rdirect.htm', {under: true, newTab: false});
</script>
```

Proposed filters:
```
||sarzamindownload.com/ppjs/combed.js$script,domain=sarzamindownload.com
sarzamindownload.com##+js(set, BetterJsPop, noopFunc)
```

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 71510
  cosmetic: 41337
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    easylist: 64240-10, now
    easyprivacy: 26642-121, now
    plowe-0: 3674-805, now
    ublock-abuse: 72-0, now
    ublock-badware: 3929-85, now
    ublock-filters: 30207-153, now
    ublock-privacy: 203-2, now
    ublock-unbreak: 1721-39, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 363 ms
  maxAssetCacheWait: 155 ms
```
</details>

**Comment by MasterKia** [comment]
Maybe it's geo specific?

**Comment by mapx-** [comment]
I get no `ppjs` for example.

Enough adding `sarzamindownload.com##+js(set, BetterJsPop, noopFunc)` ?

**Comment by MasterKia** [comment]
Yes that filter is enough to stop the popup but the ppjs script would still load.
![image](https://paste.pictures/FmAMEajmB.png)

The ppjs script: `https://pastetext.net/h5rnjt8bnm`
![image](https://user-images.githubusercontent.com/17685483/156913405-f0649914-cbb9-4b4f-87db-9d72dd6129a1.png)

Cookie after the popup opens:
![image](https://user-images.githubusercontent.com/17685483/156913260-eee7c4d4-2ef4-472e-9ba8-f4999f0903e0.png)

**Comment by MasterKia** [comment]
Yes that filter is enough to stop the popup but the ppjs script would still load.
![image](https://paste.pictures/acMz82loj.png)

The ppjs script: `https://pastetext.net/h5rnjt8bnm`
![image](https://user-images.githubusercontent.com/17685483/156913405-f0649914-cbb9-4b4f-87db-9d72dd6129a1.png)

Cookie after the popup opens:
![image](https://user-images.githubusercontent.com/17685483/156913260-eee7c4d4-2ef4-472e-9ba8-f4999f0903e0.png)
