### ISSUE TITLE
[nsfw] 9anime.id: popups

### ISSUE THREAD

**Issue by rolanggo** [uBlockOrigin/uAssets#12069]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/my-dress-up-darling.7jjw6/ep-9`

### Category

popups

### Describe the issue

Clicked to start a video and a redirect to a new tab happened. Site was nsfw.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://niceanimegames.com/common/tr/dl/land_dl_251121_en/?p1=https%3A//click.hooligapps.com/%3Fpid%3D3%26offer_id%3D24%26ref_id%3DVjN8MTYzOTMwNTZ8MzA5ODkzMHw4MDI2MjM3NXwxNjQ2NTI5NDM3fDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMHw4NS4yMjguMTQ2LjE0M3wxfHNoPTNjM2MwYzk3YTI1NGJmYmVhYWY1YmNhOWNiOTYzZjY2MzVjMWRhZTMwZjE3MWJhNGM1N2I2Y2I1NjExNTdmNDJkZWJlZjU3ZDRhNWE0NjVlYTI5MWI4NzlmMmFiYWIwODZjM2I0ZWYwMTRlZjc2NTk1ZDU5ZTAzNzZkMjgyOGRhYWE0MWM1MGVmYzY3YjVjMTVjNmQ4NTQwYThmZjIzNjg1ZjJjZGM3OWFjYjAzMjgwZGViOGU5YzdiOTc0ZjF8bHM9M3xvdHY9YXw0OTkwNDAwYmFiMTZjOTllYTFhMjg3YWU1N2Y2M2Y5Nw==%26sub1%3Dpu_main%26sub2%3D16393056
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79935
  cosmetic: 41332
  scriptlet: 16468
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64230-10, 1d.3h.50m
    easyprivacy: 26642-122, 1d.3h.49m
    plowe-0: 3673-804, 9d.4h.25m
    ublock-abuse: 72-0, 1d.3h.48m
    ublock-badware: 3924-85, 1d.3h.47m
    ublock-filters: 30203-155, 1d.3h.45m
    ublock-privacy: 203-2, 1d.3h.44m
    ublock-unbreak: 1721-39, 1d.3h.43m
    urlhaus-1: 8437-0, 11h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 566 ms (selfie)
  maxAssetCacheWait: 485 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    9anime.id: 1
    addresseepaper.com: 1
    addthis.com: 1
    amung.us: 1
    bidgear.com: 4
    clenchedyouthmatching.com: 1
    fastestvolcano.com: 1
    hallucinatecompute.com: 3
    venetrigni.com: 1
    zap.buzz: 9
```
</details>

**Comment by Procyon-b** [comment]
Try again after "Purge all caches" and "Update now"

**Comment by mapx-** [comment]
already fixed yesterday https://github.com/uBlockOrigin/uAssets/issues/12058
