### ISSUE TITLE
helloproject.actifforum.com: ads

### ISSUE THREAD

**Issue by majorpraline** [uBlockOrigin/uAssets#12066]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://helloproject.actifforum.com/profile?mode=editprofile&page_profil=informations`

### Category

ads

### Describe the issue

Ads leftovers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 95932
  cosmetic: 50496
  scriptlet: 16481
  html: 623
listset (total-discarded, last updated): 
  added: 
    FRA-0: 26020-521, 4d.1h.55m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30806-27, 4d.1h.56m
    ublock-badware: 3903-3, 4d.2h.2m
    ublock-privacy: 208-0, 4d.2h.1m
    ublock-abuse: 72-0, 4d.2h
    ublock-unbreak: 1731-0, 4d.1h.59m
    easylist: 64063-690, 4d.1h.58m
    easyprivacy: 26634-570, 4d.1h.57m
    urlhaus-1: 8437-0, 6h.45m
    plowe-0: 3670-2, 12d.5h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 147 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 4
```
</details>

**Comment by mapx-** [comment]
I guess is necessary an account.
We don't fix (only) PH

Better reporting here: https://github.com/easylist/listefr/issues
