### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by OnderKaratas** [uBlockOrigin/uAssets#12062]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Sometimes, the normal video ads on youtube are displayed when I start to watch videos. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 81212
  cosmetic: 47645
  scriptlet: 16807
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8600-79, 25m
    easylist: 64240-26, 24m
    easyprivacy: 26642-126, 23m
    plowe-0: 3673-806, 4d.6h.38m
    ublock-abuse: 72-0, 31m
    ublock-badware: 3929-85, 30m
    ublock-filters: 30210-164, 29m
    ublock-privacy: 204-2, 28m
    ublock-unbreak: 1720-39, 26m
    urlhaus-1: 7854-0, 22m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1229 ms (selfie)
  maxAssetCacheWait: 889 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    youtube.com: 7
    doubleclick.net: 2
    google.com: 1
    google.com.tr: 1
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try enabling "Suspend network activity until all filter lists are loaded" in the "Filter lists" tab.

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
