### ISSUE TITLE
https://ok.ru/{username}/photos regression

### ISSUE THREAD

**Issue by yurikoles** [uBlockOrigin/uAssets#1206]
### URL(s) where the issue occurs

https://ok.ru/{username}/photos 
### Describe the issue

The main content: user own photos is not visible.

### Screenshot(s)

![default](https://user-images.githubusercontent.com/922873/34649470-abbc9346-f3b8-11e7-8ba5-3a29a0839305.png)
### Versions

- Browser/version: Chrome/64.0.3282.71
- uBlock Origin version: v1.14.22

### Settings

Enabled filters specific for CIS sites. But after I had disabled them, the error still there.

### Notes

I see this in debug screen:
![1](https://user-images.githubusercontent.com/922873/34649506-4f422832-f3b9-11e7-8aeb-7e9b21110160.png)

**Comment by yurikoles** [comment]
How to install latest version to verify this fix?

**Comment by mapx-** [comment]
options, 3rd-party filters, "ublock filters" => click the clock icon on the right, click update

**Comment by yurikoles** [comment]
Thanx, now I see it's fixed.
