### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by cheesechipsss** [uBlockOrigin/uAssets#12065]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/playlist/56czVTYmvEdjCBzPhCJG2w`

### Category

ads

### Describe the issue

There are literally still ads?? Idk if this is spotify or the adblocker but I would enjoy listening to music a lot more if there weren't any interruptions! 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 97
filterset (summary): 
  network: 79844
  cosmetic: 41323
  scriptlet: 16480
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    easylist: 64118-9, 3d.29m
    easyprivacy: 26641-122, 3d.28m
    plowe-0: 3670-803, 11d.6h.16m
    ublock-abuse: 72-0, 3d.34m
    ublock-badware: 3899-85, 3d.33m
    ublock-filters: 30256-162, 3d.32m
    ublock-privacy: 204-2, 3d.31m
    ublock-unbreak: 1720-39, 3d.30m
    urlhaus-1: 8437-0, 16m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3199 ms (selfie)
  maxAssetCacheWait: 2097 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
    scdn.co: 1
    sentry.io: 25
```
</details>

**Comment by llacb47** [comment]
`[x] I did not answer truthfully to all the above checkpoints`

Really?

**Comment by krystian3w** [comment]
>  Joined 16 hours ago

so account to only report problem
