### ISSUE TITLE
Filter not blocking.

### ISSUE THREAD

**Issue by haslador** [uBlockOrigin/uAssets#12068]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://gogoanime.fi`

### Describe the issue

Most of the ads, when you try to watch a video are not being blocked.

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0.2

### Settings

None

**Comment by Procyon-b** [comment]
Can you post the content of "Troubleshooting Information" in the "Support" tab of ublock's dashboard ?

**Comment by haslador** [comment]
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79876
  cosmetic: 41313
  scriptlet: 16459
  html: 624
listset (total-discarded, last updated): 
  default: 
    user-filters: 45-0, never
    ublock-filters: 30865-157, 3d.22h.49m
    ublock-badware: 3903-3, 3d.22h.48m
    ublock-privacy: 208-0, 3d.22h.47m
    ublock-abuse: 72-0, 3d.22h.46m
    ublock-unbreak: 1731-0, 3d.22h.45m
    easylist: 64083-478, 3d.22h.44m
    easyprivacy: 26634-584, 3d.22h.43m
    urlhaus-1: 8437-0, 6h.29m
    plowe-0: 3673-2, 6d.1h.10m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 289 ms (selfie)
  maxAssetCacheWait: 332 ms

**Comment by Procyon-b** [comment]
In the "Filter lists" tab:
Enable, "Suspend network activity until all filter lists are loaded"
"Purge all caches" and "Update now". Then try again.
Verify also your "User filters" and your rules in case something is disabled for this site.
I'm unable to reproduce your problem (no ads for me). If the problem persists we'll have to wait for someone else to help.

**Comment by haslador** [comment]
Did as you suggested worked, but now its right back to it, and purging and updating is doing nothing.

**Comment by mapx-** [comment]
They changed the domain to `gogoplay5.com`

**Comment by haslador** [comment]
So since im not a programmer, and dont under stand a ton of code, does that mean i need to remove and re-add ublocker, since purgelists / update does nothing...................

**Comment by mapx-** [comment]
Do you still get popups ? Did you update the lists after my commit ?

**Comment by haslador** [comment]
Was as of 10 mins ago, Maybe i just dident take first time i tryed, but seems ads are gone now, thanks.
