### ISSUE TITLE
ukrainashop.com: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#12067]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ukrainashop.com/`

### Category

nuisance

### Describe the issue

Blocked right click / selection of text.

### Screenshot(s)

N/A

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 198393
  cosmetic: 102370
  scriptlet: 19669
  html: 895
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 491-3, 3h.36m
    block-lan: 44-0, 3h.36m
    fanboy-social: 23185-23, 3h.35m
    ublock-annoyances: 4364-12, 3h.35m
  default: 
    user-filters: 197-0, never
    ublock-filters: 30785-75, 2h.50m
    ublock-badware: 3933-3, 3h.37m
    ublock-privacy: 207-0, 3h.37m
    ublock-abuse: 72-0, 3h.37m
    ublock-unbreak: 1732-0, 3h.36m
    easylist: 64240-632, 3h.36m
    easyprivacy: 26642-574, 3h.36m
    urlhaus-1: 8437-0, 3h.35m
    plowe-0: 3674-2, 3h.34m
    POL-0: 7778-36, 3h.34m
    POL-2: 1276-12, 3h.34m
filterset (user): [array of 163 redacted]
trustedset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: null
  extensionUpdateForceReload: true
  filterAuthorMode: true
  popupPanelLockedSections: 32
  strictBlockingBypassDuration: 30
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 2868 ms (selfie)
  maxAssetCacheWait: 2016 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    facebook.net: 1
    google.com: 1
    googleadservices.com: 2
    googletagmanager.com: 2
    okazje.info.pl: 2
    trustedshops.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
ukrainashop.com##+js(aeld, contextmenu)
ukrainashop.com##body:style(user-select: unset !important;)
```

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12067#issuecomment-1059856367 - Your fix no covery Edge Legacy these use `-ms-` prefix.

Maybe some people still use outdated Windows 10 and blocked install Edge chromium.

**Comment by Procyon-b** [comment]
@krystian3w Can you test this:
```
ukrainashop.com##+js(aeld, contextmenu)
ukrainashop.com##body:style(user-select: unset !important; -moz-user-select: unset !important; -ms-user-select: unset !important;)
```

**Comment by Procyon-b** [comment]
@mapx- I only saw that you've already included the -moz- and -ms- version.
Note: from what I can see in the source code, this style targets only the `body` element.

**Comment by krystian3w** [comment]
I tried report remove use: `-webkit-touch-callout: default !important;` because cover only iOS Safari, not Chromium on Android but community not agree these.

**Comment by mapx-** [comment]
I know but in time became a `classic `filter so I always add it like this

**Comment by krystian3w** [comment]
But this works only on iOS 6-8 and removed in iOS 9.

**Comment by okiehsch** [comment]
@Procyon-b would you be interested in getting commit rights to `uAssets`?

**Comment by Procyon-b** [comment]
@okiehsch at some point yes. But I'm currently more focused on some of my projects and I don't want to make errors in committing fixes too fast.  ;)

**Comment by okiehsch** [comment]
> at some point yes. 

No problem, let me know when that point comes
