### ISSUE TITLE
vitan-auto.ro

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#12079]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://vitan-auto.ro/`
`http://vitan-auto.ro/oferta-zilei/44509/autoturisme/dacia-logan.html`

### Describe the issue

The images cannot be seen with uBlock enabled.

### Screenshot(s)

Without uBlock:
![screen07](https://user-images.githubusercontent.com/79897301/156941476-b5575282-87e9-45ef-a703-aee1db865585.jpg)
![screen09](https://user-images.githubusercontent.com/79897301/156941481-95c0198d-1f8a-44c2-bd98-97a80fd7fb10.jpg)

With uBlock:
![screen06](https://user-images.githubusercontent.com/79897301/156941488-2eda243e-f15e-443b-ab73-0e433269442f.jpg)
![screen08](https://user-images.githubusercontent.com/79897301/156941490-5cf5a475-18e6-4790-9b33-33e67f6d182b.jpg)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0.1

### Settings

Default settings

**Comment by mapx-** [comment]
@andreewmat keep reporting the romanian issues in the dedicated repository

**Comment by krystian3w** [comment]
Event break page by Peter Lowe then we don't remove domain from blockade?

**Comment by mapx-** [comment]
> Event break page by Peter Lowe then we don't remove domain from blockade?

translate it for me

**Comment by krystian3w** [comment]
If Peter Lowe break ro page, then fix will be added to small range ro list? Strange idea...

**Comment by andreewmat** [comment]
@mapx- Normally, i would report it to romanian filter list but I encounter this issue without RoAd filter enabled. So the problem is from the default filter not regional. And from what @krystian3w said, Peter Lowe is the culprit.

**Comment by okiehsch** [comment]
We only fix issues with a default setup and such a setup the issue is fixed in the regional list because that list is enabled by default for all users with a romanian locale.

**Comment by okiehsch** [comment]
> So the problem is from the default filter not regional..... Peter Lowe is the culprit.

Are you sure? On my end `EasyList` is blocking the picture.

**Comment by andreewmat** [comment]
> that list is enabled by default for all users with a romanian locale.

I didn't know that, I use uBlock for quite a long time and when I first installed it, those reguonal list were hidden by default.



> > So the problem is from the default filter not regional..... Peter Lowe is the culprit.
> 
> Are you sure? On my end `EasyList` is blocking the pictures.

You are right, the Easylist made the problem, not Peter Lowe. Thanks for heads up and fix.

**Comment by krystian3w** [comment]
I don't said that Peter Lowe broke this page, but I asked why put fix to small range list after Peter Lowe reject remove problematic domain from our list.

**Comment by okiehsch** [comment]
> I didn't know that, I use uBlock for quite a long time and when I first installed it, those regional lists were hidden by default

It depends on you browser locale.
Your browser locale is usually set to your corresponding language but if you set it to english for example you won't get any regional list enabled by default.
