### ISSUE TITLE
NSFW - tube8.*

### ISSUE THREAD

**Issue by Tube8-troubles** [uBlockOrigin/uAssets#12077]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW: `https://www.tube8.com/ebony/ebony-cali-calientes-training-turns-to-gangbang/81843551/`

### Describe the issue

Broken are section under video like:

 *   Related
 *   Newest Ebony
 *  Channel

### Screenshot(s)

IMO no needed screenshoting

### uBlock Origin version

1.41.8

### Browser name and version

Firefox Nightly 99

### Settings

- stock

### Notes

Bad is filter form EasyList: `##[id][style="display: block;"]`

```
tube8.com,tube8.fr,tube8.es#@#[id][style="display: block;"]
```

mirrored to: https://github.com/easylist/easylist/issues/11154

**Comment by mapx-** [comment]
let's see if @ryanbr (EL maintainer) will fix it soon

**Comment by Lairub** [comment]
Now works bad: 

`tube8.com,tube8.fr,tube8.es##[src*="blob:"]`

May need change to:

`tube8.com,tube8.fr,tube8.es##[src*="blob:"]:not(video)`

**Comment by Lairub** [comment]
@ryanbr
