### ISSUE TITLE
seznam.cz: ads

### ISSUE THREAD

**Issue by ok1xgh** [uBlockOrigin/uAssets#12074]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Describe the issue

Displays all ads on `www.seznam.cz`. They cannot be blocked. It will return in a moment. I am logged in to receive e-mails at `www.seznam.cz`. This problem was already in January but disappeared after about two weeks. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 80188
  cosmetic: 41700
  scriptlet: 16718
  html: 622
listset (total-discarded, last updated): 
  default: 
    user-filters: 19-2, never
    ublock-filters: 30788-153, 3h.29m
    ublock-badware: 3933-3, 3h.29m
    ublock-privacy: 207-0, 3h.29m
    ublock-abuse: 72-0, 3h.29m
    ublock-unbreak: 1732-0, 3h.29m
    easylist: 64274-489, 3h.29m
    easyprivacy: 26644-575, 3h.29m
    urlhaus-1: 8437-0, 3h.29m
    plowe-0: 3674-2, 3h.29m
    CZE-0: 828-0, 3h.29m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    seznam.cz: 3
    adnxs.com: 1
    gemius.pl: 2
```
</details>

**Comment by okiehsch** [comment]
> They cannot be blocked....  I am logged in

Maybe an account is required. I see ads but they can be hidden by adding
`seznam.cz##.ssp-advert`

**Comment by mapx-** [comment]
If you get ads you should report directly at CZE list repository (they are using uBO syntax / filters)
https://github.com/tomasko126/easylistczechandslovak/issues

**Comment by krystian3w** [comment]
https://github.com/tomasko126/easylistczechandslovak/pull/341
