### ISSUE TITLE
zona-iptv.ru: ads

### ISSUE THREAD

**Issue by ops244** [uBlockOrigin/uAssets#12071]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zona-iptv.ru/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b0
Chromium: 96
filterset (summary): 
  network: 98603
  cosmetic: 64571
  scriptlet: 20947
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1397-1, 3h.24m
    ublock-annoyances: 4353-11, 3h.24m
  default: 
    user-filters: 0-0, never
    RUS-0: 41642-21, 3h.24m
    easylist: 64240-26, 15h.44m
    easyprivacy: 26642-431, 15h.43m
    plowe-0: 3674-811, 15h.42m
    ublock-abuse: 72-1, 15h.40m
    ublock-badware: 3924-85, 15h.37m
    ublock-filters: 30207-186, 15h.36m
    ublock-privacy: 203-2, 15h.35m
    ublock-unbreak: 1723-40, 15h.34m
    urlhaus-1: 7854-0, 15h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 420 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    a-ads.com: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/4bc2a7fa72391451b045c376c14aec40a4803b36
