### ISSUE TITLE
viplink.in

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12070]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://viplink.in/SIBVD

### Describe the issue

The website detects UBlockOrigin and redirects to google.com

### uBlock Origin version

 1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All defaults

**Comment by Procyon-b** [comment]
This redirect (and many others) is part of it's normal behaviour.

**Comment by blazesprings** [comment]
If it's normal behavior then how to get the hosted file?

**Comment by Procyon-b** [comment]
I got it after several redirects (some with captcha) and 2 google with one preceded by a message telling me to click on the first result.

**Comment by blazesprings** [comment]
Yes now i am able to get the files too. Maybe this was the original behavior. Thanks @Procyon-b Closing the issue.
