### ISSUE TITLE
gearbest.com: popups

### ISSUE THREAD

**Issue by uizt** [uBlockOrigin/uAssets#12072]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gearbest.com/promotion-bestseller-special-1308.html?lkid=45687009&cid=524221473758654762`

### Category

popups

### Describe the issue

clicks redirect to unsafe website, opens in new tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79959
  cosmetic: 41530
  scriptlet: 16435
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 299-35, never
    ublock-filters: 30822-30, 3d.12h.9m
    ublock-badware: 3903-3, 3d.12h.4m
    ublock-privacy: 208-0, 3d.12h.7m
    ublock-abuse: 72-0, 3d.12h.6m
    ublock-unbreak: 1731-0, 3d.12h.5m
    easylist: 64183-627, 1d.23h.8m
    easyprivacy: 26642-571, 1d.23h.9m
    urlhaus-1: 8437-0, 12h.10m
    plowe-0: 3673-2, 9d.8h.52m
filterset (user): [array of 299 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 394 ms (selfie)
  maxAssetCacheWait: 215 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    gearbest.com: 2
    1talking.net: 1
    googletagmanager.com: 1
    logsss.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe you got `gearbest` ads clicking other page ? Which is that other page ?

**Comment by uizt** [comment]
yes, as i wrote in the report it's https://flixtor.video/home
