### ISSUE TITLE
hdrezka

### ISSUE THREAD

**Issue by spartaque12** [uBlockOrigin/uAssets#1207]
is it possible to remove ad after pressing play button here
https://i.imgur.com/5e1smX3.png
`http://hdrezka.ag/films/foreign/6079-zavtrak-u-tiffani.html`

adguard easily blocking this pre-play ad , or i dunno how exactly called type of that ad

**Comment by mapx-** [comment]
I get no preplay-ad, you could see in adguard log what filters are triggered.

**Comment by spartaque12** [comment]
my bad again :( sorry , Adblock Warning Removal List was unchecked
