### ISSUE TITLE
masterduelmeta.com: detection

### ISSUE THREAD

**Issue by pingufetch5** [uBlockOrigin/uAssets#12076]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.masterduelmeta.com/`

### Category

detection

### Describe the issue

Ad-Blocker detection blocks scrolling and asks user to whitelist site or pay monthly, can be closed by clicking on the "X" in the upper right of the message frame or clicking outside the frame.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/1Aej1e8.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79893
  cosmetic: 41329
  scriptlet: 16436
  html: 622
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-1, never
    ublock-filters: 30782-28, 9h.31m
    ublock-badware: 3933-3, 9h.30m
    ublock-privacy: 208-0, 2d.16h.12m
    ublock-abuse: 72-0, 2d.16h.11m
    ublock-unbreak: 1731-0, 2d.16h.10m
    easylist: 64164-609, 2d.16h.9m
    easyprivacy: 26642-571, 2d.16h.8m
    urlhaus-1: 8437-0, 1h.29m
    plowe-0: 3672-2, 10d.18h.16m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1280 ms (selfie)
  maxAssetCacheWait: 905 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    masterduelmeta.com: 1
    btloader.com: 1
    googletagmanager.com: 2
    intergient.com: 2
```
</details>

**Comment by Procyon-b** [comment]
I can reproduce: when the localStorage key `adbViews` reaches a specific number (`6`), the dialog appears.
Try this filter:
```
masterduelmeta.com##body > div > .modal:has-text(Please allow ads)
```

**Comment by okiehsch** [comment]
> do we have a way to reset/delete a localstorage key

No.

**Comment by okiehsch** [comment]
`masterduelmeta.com##+js(nostif, v=!)`
disables the detection.

**Comment by mapx-** [comment]
> `masterduelmeta.com##+js(nostif, v=!)` disables the detection.

breaking / delaying all pages

**Comment by mapx-** [comment]
this 1 is working but delaying for 5-6 seconds

`masterduelmeta.com##+js(nostif, , 50)`

**Comment by okiehsch** [comment]
Well,  in that case let's stick with hiding it.

**Comment by pingufetch5** [comment]
After purging cache and updating filters a site feature where hovering over a card image/link to a card with the mouse would open a small info panel for the card is broken. I've attached a screenshot of what it looks like when it's working correctly with Ublock disabled.

![Card info panel](https://user-images.githubusercontent.com/18482292/156951386-09f6b0ba-1d6b-457a-99f8-fdde92a9f7e4.png)

**Comment by Procyon-b** [comment]
@pingufetch5 can you try this solution?
```
masterduelmeta.com#@#[style*="duration"]
masterduelmeta.com##body > div > .modal:has-text(Please allow ads)
```

The first filter cancels the current solution, and the second is to target only the anti-adblock dialog.

**Comment by pingufetch5** [comment]
> 

Yup, that fixed it, info panels are working and the anti-adblock dialog is disabled.

**Comment by TheGreatFox1** [comment]
They've changed the popup text to get around the filter. https://i.imgur.com/QsavjVn.png

Using the above solution with different text works for now.
```
masterduelmeta.com#@#[style*="duration"]
masterduelmeta.com##body > div > .modal:has-text(Please disable adblock)
```

**Comment by TheGreatFox1** [comment]
At this point it seems to be a game of whack-a-mole. They changed their text again to get around the filter.

New popup: https://i.imgur.com/a3NGEjP.png

**Comment by ElMasterCheeks** [comment]
This issue is back

**Comment by Procyon-b** [comment]
Try this filter:
```
masterduelmeta.com##.top.modal:has-text(Please allow ads)
```
