### ISSUE TITLE
stooq.pl: detection

### ISSUE THREAD

**Issue by mpro7** [uBlockOrigin/uAssets#12088]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stooq.pl/`

### Category

detection

### Describe the issue

I haven't visited that www lately. so it's hard to say is this something new or has been there already for a while. I have opened 4 different tabs with graphs for more than an hour. These tabs were opened normally, w/o any problems. After an hour+ I've tried to open another tab, which resulted described below behavior:

Due to uBlock detection loading of the website is delayed and information about that is displayed on the web page (here translated to English because it's pretty informativ):

> You use adblock or other ad blocking solutions, or someone else is using them on the local network (IP: x.x.x.x), so we delay the loading of the page by 7 seconds. Deactivating this mechanism requires disabling adblock for the stooq.pl domain or disabling other blocking solutions, and waiting 4 business days. If you do not use adblock or other blocking solutions and you want to avoid delaying the page loading, do not delete the cookie file for the stooq.pl domain (the cookie file must be older than 3 days, and the age of your file is 39 days) and do not use the browser's incognito mode. (UID: xxxxxxxxxxxxxxx)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81595
  cosmetic: 50039
  scriptlet: 19427
  html: 0
listset (total-discarded, last updated): 
  added: 
    POL-0: 7774-8, 2h.17m
    POL-2: 1273-13, 22h.16m
    ublock-annoyances: 4354-10, 14m
  default: 
    user-filters: 8-0, never
    easylist: 64230-34, 2d.22h.24m
    easyprivacy: 26642-122, 2d.22h.23m
    plowe-0: 3673-815, 4d.23h.36m
    ublock-abuse: 72-0, 16m
    ublock-badware: 3951-85, 16m
    ublock-filters: 30199-188, 16m
    ublock-privacy: 203-2, 16m
    ublock-unbreak: 1720-40, 2d.22h.25m
    urlhaus-1: 8437-0, 2h.18m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 340 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    stooq.pl: 2
    doubleclick.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
```
</details>

**Comment by krystian3w** [comment]
Try use stooq.com

**Comment by mpro7** [comment]
@krystian3w thanks for suggestion, but `com` domain seems also affected, at least for me. I added more Information in the description. Will also try to reproduce it on another system and IP.
From the displayed message it can be concluded that they most probably flag the IP and generate also UID, which seems to be the same for all tabs opened in the same browser instance.

**Comment by mpro7** [comment]
Ok, so on the other machine it was pretty similar. I haven't face the problem at the beginning. Went to the ublock settings to find out if I miss something. To make it equal with above configuration I've added:

- uBlock filters – Annoyances
- POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
- POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda

That also didn't change anything, so left few tabs opened for couple of hours - no change after some refreshes of tabs. However the detection of ublock finally happen after restarting the browser.

**Comment by mapx-** [comment]
> detection of ublock finally happen after restarting the browser

only on browser restart ? try enabling `Suspend network activity until all filter lists are loaded`

**Comment by mpro7** [comment]
@mapx- well, this time it happened like that. Yesterday I didn't restart the browser and after some time having few tabs opened, refreshing one of these introduced the problem.

Unfortunately enabling that option doesn't help.

**Comment by mapx-** [comment]
try these filters

```
*$image,domain=stooq.pl,redirect-rule=1x1.gif
*$frame,domain=stooq.pl,redirect-rule=noopframe
```

**Comment by mpro7** [comment]
@mapx- these filters doesn't work. I've tried also to clear the cookies, but w/o luck.

**Comment by krystian3w** [comment]
If this is it similar IP ban to "kiss anime" then on origin PC need wait 2 days and after summary what works or not.

**Comment by mapx-** [comment]
any improvement adding ?

`stooq.*##+js(nostif, googlefc)`

**Comment by mpro7** [comment]
@mapx- unfortunately not.
@krystian3w it looks like IP ban and the message they sand gives some hint (cookie older than 3 days). I'll wait then and report if @mapx- ideas work.
Btw, are there many examples of banning/flagging blockers IP?

**Comment by mapx-** [comment]
what about

`stooq.*##+js(nostif, /cookie|cmp_a/)`

**Comment by mpro7** [comment]
Still no....

**Comment by mpro7** [comment]
Ok, so now it is working, but I'm not sure if this is one of your filter ideas @mapx- which I have added and which, or just 3 days cookies rule they informed in the message. Checking it would be probably not that easy.
