### ISSUE TITLE
kwejk.pl: detection

### ISSUE THREAD

**Issue by prazek** [uBlockOrigin/uAssets#12087]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kwejk.pl/strona/52043`

### Category

detection

### Describe the issue

After second refresh (or next page) the adblocker gets detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79987
  cosmetic: 41382
  scriptlet: 16475
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64282-10, 3h.23m
    easyprivacy: 26647-121, 3h.23m
    plowe-0: 3674-805, 3h.23m
    ublock-abuse: 72-0, 3h.23m
    ublock-badware: 3951-85, 3h.23m
    ublock-filters: 30224-151, 3h.23m
    ublock-privacy: 203-2, 3h.23m
    ublock-unbreak: 1720-39, 3h.23m
    urlhaus-1: 8437-0, 3h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 118 ms (selfie)
  maxAssetCacheWait: 139 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    aaxads.com: 1
    doubleclick.net: 1
    facebook.com: 1
    facebook.net: 1
    gemius.pl: 1
    googletagmanager.com: 1
    hotjar.com: 1
    maps.googleapis.com: 1
    onnetwork.tv: 1
    optad360.io: 2
    pushpushgo.com: 1
    spolecznosci.net: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable the polish lists

![image](https://user-images.githubusercontent.com/10303732/157113234-4a6d8307-9f06-4be2-adef-923354c78d52.png)
