### ISSUE TITLE
dropgalaxy.com : anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12084]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dropgalaxy.com/ntljug5hc6u3`

### Describe the issue

dropgalaxy redirects to a `https://techthematter.xyz/ link` where the Ad block is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/157059446-e6942889-26aa-4dbd-acc0-402603b260a5.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by JobcenterTycoon** [comment]
old filters works for this site too. for me are needed:

```
@@||techthematter.xyz$ghide
@@||googlesyndication.com^$script,xhr,domain=techthematter.xyz
@@.jpg$image,domain=techthematter.xyz
@@.png$image,domain=techthematter.xyz
*$script,redirect-rule=noopjs,domain=techthematter.xyz
*$image,redirect-rule=2x2.png,domain=techthematter.xyz
*$frame,redirect-rule=noopframe,domain=techthematter.xyz
*$xhr,redirect-rule=nooptext,domain=techthematter.xyz
```

**Comment by bogachenko** [comment]
on topic, this domain is dead `techyneed.com`
