### ISSUE TITLE
cdiscount.com: breakage

### ISSUE THREAD

**Issue by LouisRomeas** [uBlockOrigin/uAssets#12089]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cdiscount.com/search/10/%c3%a9cran+3840.html?TechnicalForm.SiteMapNodeId=0&TechnicalForm.DepartmentId=10&TechnicalForm.ProductId=&hdnPageType=Search&TechnicalForm.ContentTypeId=16&TechnicalForm.SellerId=&TechnicalForm.PageType=SEARCH_AJAX&TechnicalForm.LazyLoading.ProductSheets=False&TechnicalForm.BrandLicenseId=0&NavigationForm.CurrentSelectedNavigationPath=categorycodepath%2F07%7C0703&NavigationForm.FirstNavigationLinkCount=1&FacetForm.SelectedFacets.Index=0&FacetForm.SelectedFacets.Index=1&FacetForm.SelectedFacets.Index=2&FacetForm.SelectedFacets.Index=3&FacetForm.SelectedFacets.Index=4&FacetForm.SelectedFacets.Index=5&FacetForm.SelectedFacets.Index=6&FacetForm.SelectedFacets.Index=7&FacetForm.SelectedFacets.Index=8&FacetForm.SelectedFacets.Index=9&SortForm.SelectedSort=PERTINENCE&ProductListTechnicalForm.Keyword=%25C3%25A9cran%2B3840&ProductListTechnicalForm.TemplateName=InLine&&_his_`

### Category

breakage

### Describe the issue

This well-known French e-commerce website has a lot of filtering links which do not work when using uBlockOrigin. I verified it works well when I disable the extension. I'm talking about those :
![image](https://user-images.githubusercontent.com/90035206/157126403-54b95123-b908-4be2-92d2-f5c2ecfc6cad.png)
(translate : sort by relevance, best sales, price, customer reviews)

also all the filters on the left-hand column :
![image](https://user-images.githubusercontent.com/90035206/157126603-0dc80005-9610-421f-9b22-fe776b9a575e.png)

as well as the page selection at the bottom :
![image](https://user-images.githubusercontent.com/90035206/157126756-f4ebaeb7-4710-4604-b772-304131515305.png)

I'll let you try it out for yourself on the webpage. Thank you for your service to the community.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/90035206/157126403-54b95123-b908-4be2-92d2-f5c2ecfc6cad.png)
![image](https://user-images.githubusercontent.com/90035206/157126603-0dc80005-9610-421f-9b22-fe776b9a575e.png)
![image](https://user-images.githubusercontent.com/90035206/157126756-f4ebaeb7-4710-4604-b772-304131515305.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 95709
  cosmetic: 50487
  scriptlet: 16482
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30808-184, 3d.12h.16m
    ublock-badware: 3928-3, 3d.12h.15m
    ublock-privacy: 208-0, 3d.12h.13m
    ublock-abuse: 72-0, 3d.12h.12m
    ublock-unbreak: 1731-0, 3d.12h.11m
    easylist: 64183-712, 3d.12h.10m
    easyprivacy: 26642-570, 3d.12h.9m
    urlhaus-1: 8018-0, 4h.7m
    plowe-0: 3670-2, 12d.22h.34m
    FRA-0: 26077-366, 12h.38m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 177 ms (selfie)
  maxAssetCacheWait: 101 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    cdiscount.com: 6
    abtasty.com: 1
    adnxs-simple.com: 1
    analytics-cdiscount.com: 1
    aswpsdkeu.com: 2
    bing.com: 1
    contentsquare.net: 4
    criteo.net: 2
    facebook.net: 1
    facil-iti.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    hubvisor.io: 1
    kxcdn.com: 1
    sc-static.net: 1
    trustcommander.net: 1
    videoplayerhub.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||cdiscount.com/Js/tracking/cdtmv2.js$script,1p
```

**Comment by mapx-** [comment]
EP issue @ryanbr
