### ISSUE TITLE
Possibly redundant filters

### ISSUE THREAD

**Issue by PerfectSalad** [uBlockOrigin/uAssets#12094]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

N/A

### Describe the issue

Hello, so, there are two filters that may disable filters that would result in anti-adb kicking in, from what I remember. Example: using a URL monetizer -- that means attempting to advance towards the destination ("monetized" URL) -- that uses the `AdLinkFly` script or something similar (if anything like that exists) -- like `payskip . org` ...

Close to the two disabling filters, in uBlock Origin's `uBlock filters` there is:
```
! https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/377/comments/63
! https://github.com/AdguardTeam/AdguardFilters/issues/107617
```
(without the quotation / marking-as-code or whatever "``` ...```" would be called)

### uBlock Origin version

N/A

### Browser name and version

N/A

### Settings

N/A

### Notes

I know this has already discussed in uAssets, but I think that reducing memory usage when possible is a good thing.

Thank you for your time and have a great day/night - whatever!

**Comment by mapx-** [comment]
if you have some real issue provide the steps here

**Comment by okiehsch** [comment]
I don't really understand either, I don't think this is a filter issue, if your aim is to reduce memory usage maybe open an issue at 
https://github.com/uBlockOrigin/uBlock-issues
