### ISSUE TITLE
rustica.fr: detection

### ISSUE THREAD

**Issue by Marjolain** [uBlockOrigin/uAssets#12099]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rustica.fr/biodiversite/sainfoin-engrais-vert-decoratif-pour-nourrir-sol-abeilles-et-betail,16754.html`

### Category

detection

### Describe the issue

Detection and selector don't working : impossible to scroll.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79482
  cosmetic: 41337
  scriptlet: 16428
  html: 623
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
  default: 
    user-filters: 8-0, never
    ublock-filters: 30789-28, 4d.1h.52m
    ublock-badware: 3903-3, 4d.1h.50m
    ublock-privacy: 208-0, 4d.1h.56m
    ublock-abuse: 72-0, 4d.1h.55m
    ublock-unbreak: 1731-0, 4d.1h.54m
    easylist: 64183-626, 4d.1h.49m
    easyprivacy: 26642-571, 4d.1h.53m
    urlhaus-1: 8047-0, 3h.33m
    plowe-0: 3672-2, 12d.16h.46m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1766 ms (selfie)
  maxAssetCacheWait: 372 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    rustica.fr: 6
    beop.io: 1
    google-analytics.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment]
@adamwr
`rustica.fr##+js(aopw, dtctAB)`
for `AdGuard Français`.

**Comment by AdamWr** [comment]
Added, thank you.

**Comment by okiehsch** [comment]
@Marjolain you have to enable `AdGuard Français` or add
`rustica.fr##+js(aopw, dtctAB)`
to your personal filter list.

**Comment by Marjolain** [comment]
> @Marjolain you have to enable `AdGuard Français` or add `rustica.fr##+js(aopw, dtctAB)` to your personal filter list.

Thanks, but it's not working.
I'have already add AdGuard Français and I add thé orther one.
![Screenshot_20220309-182234_Firefox](https://user-images.githubusercontent.com/30159077/157496317-3a68b2f0-eae2-47e7-bd0b-319ef8c0e07e.jpg)

**Comment by mapx-** [comment]
Still working fine on my side using Adguard Français list.
Do you see in the logger

`rustica.fr##+js(aopw, dtctAB)`

?

**Comment by Marjolain** [comment]
> Still working fine on my side using Adguard Français list. Do you see in the logger
> 
> `rustica.fr##+js(aopw, dtctAB)`
> 
> ?

I try on my laptop too but same problem. (2 differents sessions)
And I don't have `rustica.fr##+js(aopw, dtctAB)` on my logger.
I try with a new session, I add Ublock origin, it's working.
I dont know why.
Thanks anyway.

**Comment by mapx-** [comment]
You have to enable Adguard Français list.
