### ISSUE TITLE
Broadcastify Audio Ads

### ISSUE THREAD

**Issue by KandiKlover** [uBlockOrigin/uAssets#12098]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.broadcastify.com/webPlayer/14747
https://www.broadcastify.com/webPlayer/32344
```

### Describe the issue

When you press play on any scanner feed page on broadcastify it plays an audio add before connecting to the scanners live audio output. 

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79622
  cosmetic: 41336
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  added: 
    block-lan: 44-0, 6d.16h
  default: 
    user-filters: 0-0, never
    easylist: 64240-10, 2d.14h.11m
    easyprivacy: 26647-121, 1d.3h.52m
    plowe-0: 3674-805, 1d.15h.53m
    ublock-abuse: 72-0, 1d.3h.51m
    ublock-badware: 3939-85, 11h.37m
    ublock-filters: 30212-151, 11h.36m
    ublock-privacy: 203-2, 11h.35m
    ublock-unbreak: 1720-39, 11h.34m
    urlhaus-1: 8047-0, 3h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 730 ms (selfie)
  maxAssetCacheWait: 497 ms
```
</details>

**Comment by okiehsch** [comment]
I don't think that's fixable, the ad is stitched into the stream as far as I can see.

**Comment by KandiKlover** [comment]
> 

Oh I thought it was seperate because it would play first then go quiet and say connected. Thank you for checking.

**Comment by PerfectSalad** [comment]
There could be a solution to the advertising though. Is anybody **sure** it can't be addressed with a scriptlet?

**Comment by KandiKlover** [comment]
How dareeeeeeeeeeeee you censor our troubleshooting. That's it I'm going back to adblock.

**Comment by mapx-** [comment]
No censorship, only perfectsalad useless stuff.
