### ISSUE TITLE
2345.com: ads

### ISSUE THREAD

**Issue by qingfengxieying** [uBlockOrigin/uAssets#12095]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.2345.com/`

### Category

ads

### Describe the issue

使用公司的2345王牌浏览器，安装了本插件，在进入这个站点时，不能拦截广告。

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 69
filterset (summary): 
  network: 97932
  cosmetic: 51417
  scriptlet: 16568
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28164-87, 5m
    easylist: 64350-12, 4m
    easyprivacy: 26652-147, 4m
    plowe-0: 3674-807, 4m
    ublock-abuse: 72-0, 4m
    ublock-badware: 3951-85, 4m
    ublock-filters: 30194-167, 4m
    ublock-privacy: 202-2, 4m
    ublock-unbreak: 1720-40, 4m
    urlhaus-1: 8437-0, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2056 ms
  maxAssetCacheWait: 940 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
maybe you @Yuki2718 could help here ..

**Comment by okiehsch** [comment]
> Chromium: 69

What browser is this?

**Comment by okiehsch** [comment]
Ok, according to google translate it seems to be a browser issue.
![image](https://user-images.githubusercontent.com/16838044/157198235-3c52c0b6-e898-4a89-9f66-6b780349432f.png)

**Comment by Yuki2718** [comment]
Apparetly this is the browser: `https://ie.2345.cc/` (name changed `王牌浏览器` => `加速浏览器`)
@qingfengxieying Use Firefox, Edge, or Chrome. This project is 100% volunteer-supported and we can't suppot all possible browser on which uBO can be installed (Unless one take time to investigate the cause of problem and then brings nice solution).
