### ISSUE TITLE
Dosent block some ads

### ISSUE THREAD

**Issue by lipici** [uBlockOrigin/uAssets#12096]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Ublock dosent block some ads from 1 month ago no mather the ublock version, 1.41.7, 1.41.8 or last one 1.41.9

### A specific URL where the issue occurs

Mail.yahoo.com

### Steps to Reproduce

I enter on different sites and some ads are showing where in the past they didnt.
Started to happen like 1 month ago 

### Expected behavior

To block ads

### Actual behavior

Ads are showing, but 1 month ago everything was perfect
https://user-images.githubusercontent.com/46893370/157193973-07a6705f-fbb8-4833-b6c2-4cd35447371f.png
![Screenshot_20220308-100347_1](https://user-images.githubusercontent.com/46893370/157194000-c071cee4-3846-4ef2-b965-44c6a84a2ae6.png)

### uBlock Origin version

uBlock Origin development build 1.41.9b0

### Browser name and version

Kiwi browser last version 98

### Operating System and version

Android 11

**Comment by mapx-** [comment]
"Some ads" is too vague.
Lastly, Kiwi is not reliable, you should do test on android using firefox.
Report back with details (page links where you see ads, screenshot etc)

**Comment by u-RraaLL** [comment]
You're running uBO on kiwi which disables it on certain websites.

**Comment by lipici** [comment]
> You're running uBO on kiwi which disables it on certain websites.

Not the case, if i open settings for those sites with ads ublock icon is red. 
If you read comments on webstore you will se many people have problems.  Thats why i made this report, coz im not the only one.

**Comment by lipici** [comment]
> "Some ads" is too vague. Lastly, Kiwi is not reliable, you should do test on android using firefox. Report back with details (page links where you see ads, screenshot etc)

If you read my post you see screenshots with ads , you see the site name and if you read the other reports from github or webstore extension you will find out many people have same problem.
How i said the problem wasnt there from begining, something might happened with the changes of app.

**Comment by mapx-** [comment]
I tested `realitatea.net`, in android + firefox, no such ads.
Test yourself in firefox.

> you see the site name and if you read the other reports from github or webstore extension

When you come here provide page specific links where the issues can be tested. We don't scan the web all the day, we are volunteers, so you should help us and help yourself in order to fix the issues providing all the necessary details.

**Comment by u-RraaLL** [comment]
> If you read my post you see screenshots with ads , you see the site name

Actually, all your screenshot shows in "search or type web address"... Is that the homepage/new tab page of the browser then? If so, uBO never had access to these.

It doesn't matter what page the ad leads to, what matters is where the ad is displayed.

**Comment by lipici** [comment]
You're talking like you are the only one who knows how to use ublock origin or knows when something its working or isnt working. I used from years and i know if something its wrong or not.
Also if you read more carefull first post like i said you will see that i writted the site name.

![Screenshot_2022-03-09_07-02-31_1](https://user-images.githubusercontent.com/46893370/157376911-fcf8b311-11b4-448f-ab1d-3fb50668ae85.png)
![Screenshot_2022-03-09_07-02-00](https://user-images.githubusercontent.com/46893370/157376932-3333f078-41eb-475f-8b90-9b0e4ffcd26a.png)
![Screenshot_20220308-142545](https://user-images.githubusercontent.com/46893370/157376978-1d8d74f0-3c68-4080-b72c-bd905c067b97.png)

**Comment by lipici** [comment]
![Uploading Screenshot_20220308-142555.png…]()

**Comment by lipici** [comment]
![Uploading Screenshot_20220308-142555.png…]()

**Comment by lipici** [comment]
![Screenshot_20220308-142555_1](https://user-images.githubusercontent.com/46893370/157377740-c909ddf6-5370-42de-9cbd-b60dfdcb8b23.png)

**Comment by lipici** [comment]
You're talking like you are the only one who knows how to use ublock origin or knows when something its working or isnt working. I used from years and i know if something its wrong or not.Also if you read more carefull first post like i said you will see that i writted the site name.
![Screenshot_2022-03-09_07-02-31_1](https://user-images.githubusercontent.com/46893370/157376911-fcf8b311-11b4-448f-ab1d-3fb50668ae85.png)![Screenshot_2022-03-09_07-02-00](https://user-images.githubusercontent.com/46893370/157376932-3333f078-41eb-475f-8b90-9b0e4ffcd26a.png)![Screenshot_20220308-142545](https://user-images.githubusercontent.com/46893370/157376978-1d8d74f0-3c68-4080-b72c-bd905c067b97.png)

    On Wednesday, March 9, 2022, 12:03:43 AM GMT+2, mapx- ***@***.***> wrote:  
 
 


Closed #12096.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
