### ISSUE TITLE
chd4.com: detection

### ISSUE THREAD

**Issue by stuartsteven4** [uBlockOrigin/uAssets#12092]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chd4.com/`

### Category

detection

### Describe the issue

it detects the adblock & dont let entering the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/101161496/157162785-83b0d1c9-e9b4-4c22-a56d-63ddd844c830.png

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79968
  cosmetic: 41371
  scriptlet: 16473
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64279-10, 19h.36m
    easyprivacy: 26647-121, 19h.35m
    plowe-0: 3673-805, 7d.19h.19m
    ublock-abuse: 72-0, 19h.34m
    ublock-badware: 3939-85, 19h.33m
    ublock-filters: 30205-151, 19h.32m
    ublock-privacy: 203-2, 19h.31m
    ublock-unbreak: 1723-39, 19h.30m
    urlhaus-1: 8437-0, 1d.9h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5964 ms (selfie)
  maxAssetCacheWait: 661 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflareinsights.com: 1
    doubleclick.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
needing account ?

**Comment by stuartsteven4** [comment]
No i've account but cant use with adblocker on.

**Comment by mapx-** [comment]
home page, no anti adblocking on my side

![image](https://user-images.githubusercontent.com/10303732/157277962-31231aeb-80d8-4d19-aac6-5a1d999ab94b.png)

**Comment by stuartsteven4** [comment]
oh sorry I didn't notice actually no anti adblocking before log in on my side too, anti adblocking starts after I logging in.


![chd1](https://user-images.githubusercontent.com/101161496/157699584-99beeb6a-ce9e-43e3-9f85-47d719fe3578.png)




![chd2](https://user-images.githubusercontent.com/101161496/157699617-f3b5da8f-c81b-4d79-abba-dc42f5acc37f.png)
