### ISSUE TITLE
ancientrom.xyz: detection

### ISSUE THREAD

**Issue by pi4a7a** [uBlockOrigin/uAssets#12108]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ancientrom.xyz/`

### Category

detection

### Describe the issue

Side detects uBlock Origin and doesn't display the page content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bgs](https://user-images.githubusercontent.com/54013607/157339312-8ef4097e-4494-4a46-aecc-e604698c5494.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 99852
  cosmetic: 85668
  scriptlet: 18458
  html: 0
listset (total-discarded, last updated): 
  added: 
    BGR-0: 1116-11, 6h.55m
    RUS-0: 41644-9, 1d.9h.23m
    fanboy-cookiemonster: 24054-41, 2d.8h.17m
  default: 
    user-filters: 37-3, never
    easylist: 64394-26, 2h.53m
    easyprivacy: 26651-216, 2h.52m
    plowe-0: 3673-810, 7d.10h.49m
    ublock-abuse: 72-1, 2h.51m
    ublock-badware: 3951-85, 2h.50m
    ublock-filters: 30198-188, 2h.49m
    ublock-privacy: 202-2, 2h.48m
    ublock-unbreak: 1723-40, 2h.47m
    urlhaus-1: 7888-0, 6h.54m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  uiTheme: dark
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 395 ms (selfie)
  maxAssetCacheWait: 424 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    ampproject.org: 2
    googlesyndication.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
Possibly caused by "BGR: Bulgarian Adblock list" (included as possible-to-be-enabled in uBO)

**Comment by Procyon-b** [comment]
Try this filter:
```
ancientrom.xyz#@##banner_ad
```
