### ISSUE TITLE
9anime.id: nuisance

### ISSUE THREAD

**Issue by Elmsburgh** [uBlockOrigin/uAssets#12106]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/rent-a-girlfriend.nllk/ep-1`

### Category

nuisance

### Describe the issue

A pop-up ad when video is paused

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![9anime](https://user-images.githubusercontent.com/101214587/157313667-4b7dab12-a3c0-43fb-9698-d1a9f60e69e4.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 79954
  cosmetic: 41341
  scriptlet: 16477
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64240-10, 3d.1h.30m
    easyprivacy: 26642-121, 3d.1h.29m
    plowe-0: 3673-805, 7d.3h.43m
    ublock-abuse: 72-0, 3d.1h.28m
    ublock-badware: 3929-85, 3d.1h.27m
    ublock-filters: 30241-170, 3d.1h.25m
    ublock-privacy: 203-2, 3d.1h.24m
    ublock-unbreak: 1720-39, 3d.1h.23m
    urlhaus-1: 8437-0, 6h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17488 ms (selfie)
  maxAssetCacheWait: 656 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    9anime.id: 3
    addthis.com: 1
    amung.us: 1
    bidgear.com: 4
    fastestvolcano.com: 1
    google-analytics.com: 1
    mcloud.to: 3
```
</details>

**Comment by Procyon-b** [comment]
Already fixed: #12058
"Purge all caches" and "Update now"
