### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by DEtrees95** [uBlockOrigin/uAssets#12100]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/landwirt_in_mv`

### Category

ads

### Describe the issue

pls fix this =// 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82038
  cosmetic: 44711
  scriptlet: 16476
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    DEU-0: 5521-0, 39m
    easylist: 64183-16, 3d.21h.57m
    easyprivacy: 26651-132, 46m
    plowe-0: 3672-805, 12d.6h.29m
    ublock-abuse: 72-0, 45m
    ublock-badware: 3939-85, 44m
    ublock-filters: 30211-156, 42m
    ublock-privacy: 202-2, 41m
    ublock-unbreak: 1723-40, 40m
    urlhaus-1: 8437-0, 16h.17m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms (selfie)
  maxAssetCacheWait: 172 ms
popupPanel: 
  blocked: 48
  blockedDetails: 
    twitch.tv: 8
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 35
```
</details>

**Comment by mapx-** [comment]
video ads ? on live stream or other videos ? other ads ?

**Comment by DEtrees95** [comment]
on livestream...  is sometimes so... not always my friend have this too...

**Comment by DEtrees95** [comment]
![image](https://user-images.githubusercontent.com/75539790/157458763-c7317fb5-910e-4679-a3f8-7165858072b1.png)

here its a screenshot: the channel: https://www.twitch.tv/shurjoka

**Comment by jsteave** [comment]
on Livestream. I am also facing the same issue.

**Comment by okiehsch** [comment]
Maybe the ad only appears if one is logged in.
I don't get any ads on the livestream.

**Comment by mapx-** [comment]
I have an account but no ad on my end

**Comment by jsteave** [comment]
> Maybe the ad only appears if one is logged in. I don't get any ads on the Livestream.

I agree with you

**Comment by CodeSMOP** [comment]
Facing the same issue here. Stream shows ads when tuning in to stream.

**Comment by KasimNasir** [comment]
also facing this issue for non subscribed streams

**Comment by jsteave** [comment]
and didn't get any good solution

**Comment by yrogerg77** [comment]
I have same problem... when clicking on a live stream, it will sometimes plan a 15-30 second ad before showing the stream. I am logged in to Twitch fwiw.

**Comment by jsteave** [comment]
@yrogerg77 and you didn't get any solution?

**Comment by jsteave** [comment]
@yrogerg77 you will get your solution very soon

**Comment by ellamacrow98** [comment]
@Prerequisites Hi, I have a question about the twitch ad. Unfortunately, ublock origin can no longer block Twitch ads.

**Comment by MasterKia** [comment]
@ellamacrow98 You should comment here:
https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by newworldapk** [comment]
Is There A Way To Get Rid Of Ads On Twitch? There are two ways to get rid of ads on Twitch: first, viewers can subscribe to a channel to avoid ads on that specific channel or second, [here](https://apkstick.com/clash-of-clans-mod/) viewers can subscribe to Twitch Turbo for $8.99 a month for ad-free viewing across the platform.

**Comment by sugarfreesweetener** [comment]
maybe read from https://github.com/pixeltris/TwitchAdSolutions
