### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by thomas-m-fr** [uBlockOrigin/uAssets#12101]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.deezer.com/fr/`

### Category

breakage

### Describe the issue

Similar issue was opened and closed recently but the issue persist : 
when using "Flow" feature of this website, it stops after one track.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 91
filterset (summary): 
  network: 96270
  cosmetic: 50553
  scriptlet: 16483
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30787-28, 12m
    ublock-badware: 3955-3, 12m
    ublock-privacy: 206-0, 12m
    ublock-abuse: 72-0, 12m
    ublock-unbreak: 1731-0, 12m
    easylist: 64358-684, 2m
    easyprivacy: 26651-907, 12m
    urlhaus-1: 8437-0, 12m
    plowe-0: 3674-2, 12m
    FRA-0: 26077-198, 12m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1588 ms (selfie)
  maxAssetCacheWait: 708 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    sentry.io: 2
```
</details>

**Comment by thomas-m-fr** [comment]
I'm not an expert but from the logs it looks related to "sentry.io"

**Comment by mapx-** [comment]
I cannot reproduce the issue even after 40 minutes.

Does this exception work for you ?
`@@||sentry.io/api/$xhr,domain=deezer.com`
