### ISSUE TITLE
[NSFW] xxxstreams.org – popup

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#1210]
### URL(s) where the issue occurs

**NSFW LINK** **–** `xxxstreams.org`

### Describe the issue

clicking anywhere triggers popup

### Screenshot(s)

–

### Versions

- Browser/version: **Firefox 57.0.4 (64-bit)**
- uBlock Origin version: **1.14.22**

### Settings

Default

### Notes

–

**Comment by zaphodbeebblebrox** [comment]
Sidebar ads, can be fixed with `||xxxstreams.org/*/index.php$xmlhttprequest,first-party`
