### ISSUE TITLE
101soundboards.com: detection

### ISSUE THREAD

**Issue by bceez** [uBlockOrigin/uAssets#12119]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.101soundboards.com/`

### Category

detection

### Describe the issue

Anti adblock script

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 81769
  cosmetic: 24611
  scriptlet: 19236
  html: 633
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4382-7, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30887-263, 1m
    ublock-badware: 3960-3, 1m
    ublock-privacy: 204-1, 1m
    ublock-abuse: 72-0, 1m
    ublock-unbreak: 1739-0, 1m
    adguard-mobile: 7316-169, 1m
    easylist: 64407-24304, 1m
    easyprivacy: 26653-578, 1m
    urlhaus-1: 8437-0, 1m
    plowe-0: 3674-2, 1m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6457 ms (selfie)
  maxAssetCacheWait: 3409 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Do you mean ?

![image](https://user-images.githubusercontent.com/10303732/157457630-61c420cd-1317-4fc8-bd82-4b4c816f0882.png)

It's just annoyance, isn't it?

**Comment by mapx-** [comment]
does this work for you ?

`101soundboards.com##.blocked-notice-small`

**Comment by mapx-** [comment]
@ryanbr @Yuki2718

**Comment by Yuki2718** [comment]
Hmm, somehow I don't get the anti-adb on AG (no diff in the log...) so maybe the rule should stay on uBlock - Annoyances. Will address placeholder.

**Comment by AdamWr** [comment]
I can't reproduce anti-adblock notice on my end.

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/157483154-bcccf6e4-252c-49a1-b7a3-3e7d7622644b.png)

**Comment by Yuki2718** [comment]
Yep, for some reason triggered only with uBO.

**Comment by AdamWr** [comment]
I guess that this rule:
```
#$#.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links { display: block !important; }
```
from AdGuard Base filter fixes it in AdGuard, that's why I can't reproduce it.
