### ISSUE TITLE
play.nova.bg: breakage

### ISSUE THREAD

**Issue by pi4a7a** [uBlockOrigin/uAssets#12110]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://play.nova.bg/video/bratya/season-4/bratq-2022-02-22/601437`

### Category

breakage

### Describe the issue

Video player stops working after enabling uBlock Origin on the website. Works when disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![play nova](https://user-images.githubusercontent.com/54013607/157342168-d3b8fbd3-ae2f-4ec2-8a06-3408f9174741.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 99852
  cosmetic: 85668
  scriptlet: 18458
  html: 0
listset (total-discarded, last updated): 
  added: 
    BGR-0: 1116-11, 7h.23m
    RUS-0: 41644-9, 1d.9h.51m
    fanboy-cookiemonster: 24054-41, 2d.8h.45m
  default: 
    user-filters: 37-3, never
    easylist: 64394-26, 3h.21m
    easyprivacy: 26651-216, 3h.20m
    plowe-0: 3673-810, 7d.11h.17m
    ublock-abuse: 72-1, 3h.19m
    ublock-badware: 3951-85, 3h.18m
    ublock-filters: 30198-188, 3h.17m
    ublock-privacy: 202-2, 3h.16m
    ublock-unbreak: 1723-40, 3h.15m
    urlhaus-1: 7888-0, 7h.22m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  uiTheme: dark
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 358 ms (selfie)
  maxAssetCacheWait: 231 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    gstatic.com: 1
    jwpcdn.com: 1
    jwpltx.com: 1
```
</details>

**Comment by pi4a7a** [comment]
> 

I'm not sure what those are. The reported problem sometimes fixes itself on random occasion without me interfering somehow.

**Comment by PerfectSalad** [comment]
@pi4a7a https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by mapx-** [comment]
No issue on my end, you should reset to default setup then force update all lists (click "Purge all caches", then click "Update now")
