### ISSUE TITLE
app.daily.dev: ads

### ISSUE THREAD

**Issue by clearbubble20** [uBlockOrigin/uAssets#12116]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.daily.dev/`

### Category

ads

### Describe the issue

There are some promoted posts in the feed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-03-09-15-32-55-64_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/101097101/157419273-7ff0b351-33d1-4b1f-b191-82ccedcb5b9b.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 96
filterset (summary): 
  network: 153190
  cosmetic: 188167
  scriptlet: 33676
  html: 633
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 62377-4849, 2m
    adguard-spyware: 26501-1037, 2m
    adguard-spyware-url: 499-3, 2m
    block-lan: 44-0, 2m
    curben-phishing: 11484-2, 2m
    curben-pup: 387-0, 2m
    adguard-annoyance: 50640-4266, 2m
    adguard-social: 16042-1071, 2m
    fanboy-thirdparty_social: 68-0, 2m
    fanboy-annoyance: 62914-47548, 2m
    fanboy-cookiemonster: 24272-140, 2m
    fanboy-social: 23192-30, 2m
    ublock-annoyances: 4382-4, 2m
    dpollock-0: 10347-488, 2m
    https://winhelp2002.mvps.org/hosts.txt: 8730-1891, never
  default: 
    user-filters: 16-0, never
    ublock-filters: 30891-60, 3m
    ublock-badware: 3955-3, 3m
    ublock-privacy: 204-0, 3m
    ublock-abuse: 72-0, 3m
    ublock-unbreak: 1739-0, 2m
    adguard-mobile: 7312-192, 2m
    easylist: 64406-958, 2m
    easyprivacy: 26652-10836, 2m
    urlhaus-1: 8437-0, 2m
    plowe-0: 3674-2, 2m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2141 ms (selfie)
  maxAssetCacheWait: 3354 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    ads-twitter.com: 1
    amplitude.com: 1
    google-analytics.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`app.daily.dev##article:has-text(Promoted)`

@ryanbr
