### ISSUE TITLE
[nsfw] zoosk.online: ads

### ISSUE THREAD

**Issue by mutludoc** [uBlockOrigin/uAssets#12117]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zoosk.online/?e73fl0sov4=1646824756e1381b10c7eaea1268d3e43962ae03629d489e9e`

### Category

ads PORN

### Describe the issue

ADS PORN I DID NOT OPEN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81265
  cosmetic: 47650
  scriptlet: 16811
  html: 0
listset (total-discarded, last updated): 
  added: 
    TUR-0: 8599-79, 4d.2h.1m
  default: 
    user-filters: 0-0, never
    easylist: 64239-26, 4d.2h
    easyprivacy: 26651-126, 15h.57m
    plowe-0: 3675-806, 4d.23h.8m
    ublock-abuse: 72-0, 4d.1h.59m
    ublock-badware: 3929-85, 4d.1h.58m
    ublock-filters: 30223-159, 15h.56m
    ublock-privacy: 203-2, 4d.1h.57m
    ublock-unbreak: 1721-39, 15h.55m
    urlhaus-1: 7888-0, 15h.54m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3189 ms (selfie)
  maxAssetCacheWait: 745 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
**Do not provide the popup link** => provide the original page where clicking you are redirect to the popup page
