### ISSUE TITLE
popup on nitroflare.com

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1211]
### URL(s) where the issue occurs

`https://nitroflare.com/view/9458251FB7333B3/Chaos.Intellect.10.1.0.5.2b.rar`

### Describe the issue

pop up as a new window after going to download in slow mode. It's heading to `http://www.nanoadexchange.com/a/display.php?r=`

### Versions

- Browser/version: Chrome 63.0.3239.108 (Official Build) (64-bit)
- uBlock Origin version: v1.14.22

### Notes

issue is coming from following in-line scripts:
```
https://pastebin.com/raw/yn3vFVw2
https://pastebin.com/raw/fWS13HcQ
```

**Comment by mapx-** [comment]
test these filters
```
nitroflare.com##script:inject(abort-current-inline-script.js, $, window.open)
nitroflare.com##script:inject(abort-current-inline-script.js, pop3, window.open)
```

**Comment by nimasaj** [comment]
They are working, thanks. Is there any tuts on how to make these params?

**Comment by mapx-** [comment]
Not that I know of
