### ISSUE TITLE
french-stream.so: breakage

### ISSUE THREAD

**Issue by blipblopok** [uBlockOrigin/uAssets#12112]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://french-stream.so/`

### Category

popups

### Describe the issue

For a week I had nothing and then suddenly pages open with each click I make on the site..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 97
filterset (summary): 
  network: 96103
  cosmetic: 50515
  scriptlet: 16525
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 25998-24, 2d.5h.12m
    easylist: 64277-97, 2d.5h.11m
    easyprivacy: 26646-446, 2d.5h.10m
    plowe-0: 3673-813, 4d.9h.23m
    ublock-abuse: 72-1, 2d.5h.9m
    ublock-badware: 3929-92, 2d.5h.8m
    ublock-filters: 30205-306, 2d.5h.7m
    ublock-privacy: 203-2, 2d.5h.6m
    ublock-unbreak: 1720-39, 2d.5h.5m
    urlhaus-1: 8437-0, 21h.3m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 602 ms (selfie)
  maxAssetCacheWait: 493 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    dacmaiss.com: 2
    denetsuk.com: 1
    dozubatan.com: 1
    pseepsie.com: 1
    toglooman.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
> [x] I did not answer truthfully to **all** the above checkpoints

ok

**Comment by PerfectSalad** [comment]
> ```yaml
> listset (total-discarded, last updated): 
>   default: 
>     user-filters: 0-0, never
>     FRA-0: 25998-24, 2d.5h.12m
>     easylist: 64277-97, 2d.5h.11m
>     easyprivacy: 26646-446, 2d.5h.10m
>     plowe-0: 3673-813, 4d.9h.23m
>     ublock-abuse: 72-1, 2d.5h.9m
>     ublock-badware: 3929-92, 2d.5h.8m
>     ublock-filters: 30205-306, 2d.5h.7m
>     ublock-privacy: 203-2, 2d.5h.6m
>     ublock-unbreak: 1720-39, 2d.5h.5m
>     urlhaus-1: 8437-0, 21h.3m
> ```

Could you update the filters ?

**Comment by blipblopok** [comment]
For a week I had nothing and then suddenly pages open with each click I make on the site..
![image](https://user-images.githubusercontent.com/101229504/157353757-68715a00-ddaa-49e7-986f-d3f6bdaa1504.png)
You told me to add the filter, but it gives this now

**Comment by PerfectSalad** [comment]
Are you using any other content (for example advertising / tracking) blocker?

**Comment by Procyon-b** [comment]
It works for me (in Belgium) in chrome and FF with default settings in ubo.

**Comment by mapx-** [comment]
add

```
*$script,3p,from=uqload.com,badfilter
||opsktp.com^$badfilter
```

@smed79
