### ISSUE TITLE
stltoday.com

### ISSUE THREAD

**Issue by PerfectSalad** [uBlockOrigin/uAssets#12114]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

the one present in https://github.com/AdguardTeam/AdguardFilters/issues/111501

### Describe the issue

anti-adb (I'm not sure if someone would have to browse several articles in order to encounter it)

### uBlock Origin version

1.41.8

### Browser name and version

Google Chrome

### Settings

N/A

**Comment by Procyon-b** [comment]
Try these filters:
```
stltoday.com##.modal-backdrop.fade.in, #lee-subscription-wall
stltoday.com##body.modal-open:style(overflow-y: auto !important;padding-right: unset !important;)
```

**Comment by mapx-** [comment]
anti adb or subscription-paywall ?

**Comment by okiehsch** [comment]
I get the same modal with uBO disabled.

**Comment by PerfectSalad** [comment]
they look pretty similar, hmm...
maybe it was a subscription paywall
maybe it also has anti-adb, but not sure if it detects ubo
