### ISSUE TITLE
coshink.co [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1212]
URL(s) where the issue occurs

`http://coshink.co/PsHAx`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
`@@||http://coshink.co/*/ads.js`

**Comment by zaphodbeebblebrox** [comment]
Add timer boosting with `coshink.co##script:inject(nano-setInterval-booster.js)`?

**Comment by KiLL4FuNK** [comment]
ADS fill captchas

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
