### ISSUE TITLE
digi24.ro: detection

### ISSUE THREAD

**Issue by invasi0n** [uBlockOrigin/uAssets#12129]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.digi24.ro/live/digi24`

### Category

detection

### Describe the issue

The live streaming doesn't work when uBlock origin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79827
  cosmetic: 41738
  scriptlet: 16446
  html: 622
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30798-29, 3d.2h.26m
    ublock-badware: 3933-3, 3d.2h.25m
    ublock-privacy: 207-0, 3d.2h.24m
    ublock-abuse: 72-0, 3d.2h.23m
    ublock-unbreak: 1732-0, 3d.2h.22m
    easylist: 64277-619, 3d.2h.21m
    easyprivacy: 26646-583, 3d.2h.20m
    urlhaus-1: 7888-0, 19h.58m
    plowe-0: 3674-2, 2d.1h.48m
    ROU-1: 820-23, 2d.5h.14m
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 261 ms (selfie)
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    digi24.ro: 1
    adtlgc.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 5
```
</details>

**Comment by mapx-** [comment]
- Working fine on my end using default settings (including Romanian list)
- If you are using other addons => disable them all, keep only uBO & test again
- reset uBO to default setup, then go into dashboard, filter lists tab, click "purge all caches", click "update now", test again

**Comment by invasi0n** [comment]
In Chrome is working fine but I was trying to watch it in Firefox.
Thanks.

**Comment by mapx-** [comment]
Did you disable "enhanced tracking protection" in firefox ?

go to `about:preferences#privacy` and disable it

**Comment by invasi0n** [comment]
Well, you're a genius! Thank you very much, now is working perfectly fine. Also thank you for this wonderful extension!
