### ISSUE TITLE
[nsfw] geeksforgeeks.org: breakage

### ISSUE THREAD

**Issue by User11535** [uBlockOrigin/uAssets#12138]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.geeksforgeeks.org/how-to-get-slice-of-a-primitive-array-in-java/`

### Category

breakage!

### Describe the issue

Popup blocker does not work!

`www.geeksforgeeks.org/wp-content/themes/iconic-one/js/gfg.min.js` Popop script

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 91657
  cosmetic: 152459
  scriptlet: 21888
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50694-156, 1h.19m
    adguard-social: 16061-777, 1h.18m
    fanboy-annoyance: 62654-3927, 1d.9h.23m
    fanboy-cookiemonster: 24139-24139, 1d.9h.22m
    fanboy-social: 23190-23190, 3d.22h.7m
    fanboy-thirdparty_social: 69-21, 1d.9h.21m
    ublock-annoyances: 4355-263, 1h.17m
  default: 
    user-filters: 0-0, never
    easylist: 64277-48, 3d.6h.5m
    easyprivacy: 26646-214, 3d.6h.4m
    plowe-0: 3674-806, 2d.5h.25m
    ublock-abuse: 72-0, 3d.6h.3m
    ublock-badware: 3929-85, 3d.6h.2m
    ublock-filters: 30210-490, 3d.6h.1m
    ublock-privacy: 203-10, 3d.6h
    ublock-unbreak: 1720-46, 3d.5h.59m
    urlhaus-1: 8437-0, 13h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 20047 ms (selfie)
  maxAssetCacheWait: 1632 ms
popupPanel: 
  blocked: 5
  no-popups: true
  blockedDetails: 
    geeksforgeeks.org: 1
    adpushup.com: 1
    adrecover.com: 1
    googletagmanager.com: 1
    servedby-buysellads.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12132

**Comment by iam-py-test** [comment]
> [nsfw] geeksforgeeks.org: breakage

How are Java arrays NSFW?

**Comment by mapx-** [comment]
> Popup blocker does not work!

Are you talking about other extension ? or about the login popup ?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12132
