### ISSUE TITLE
git.tc [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1213]
URL(s) where the issue occurs

`http://git.tc/Lh79`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
```
||s2block.com^$script
||adnimo.com/code^$script
@@||git.tc^$generichide
```
