### ISSUE TITLE
multiup.org: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#12135]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)

### URL address of the web page

`https://www.multiup.org/en/profile/manage-files`

### Category

breakage

### Describe the issue

Cannot preview links or view them with ubo enabled. When I click it it does nothing

### Screenshot(s)

![ubocreenshot 2022-03-09 131947](https://user-images.githubusercontent.com/69532417/157538108-7479b723-1e50-40de-9a9f-dc7c72afcdd0.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 121081
  cosmetic: 187522
  scriptlet: 33162
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50639-155, 1d.42m
    adguard-generic: 62373-685, 1d.42m
    adguard-mobile: 7312-44, 1d.42m
    adguard-social: 16042-781, 1d.42m
    curben-phishing: 10770-0, 38m
    curben-pup: 387-0, 37m
    fanboy-annoyance: 62654-3976, 1d.42m
    fanboy-cookiemonster: 24075-24031, 1d.42m
    fanboy-social: 23192-23192, 1d.42m
    ublock-annoyances: 4354-293, 1d.42m
  default: 
    user-filters: 2-0, never
    easylist: 64394-978, 1d.42m
    easyprivacy: 26651-336, 1d.42m
    plowe-0: 3674-903, 1d.42m
    ublock-abuse: 72-0, 1d.42m
    ublock-badware: 3951-253, 1d.42m
    ublock-filters: 30223-3433, 1d.42m
    ublock-privacy: 202-11, 1d.42m
    ublock-unbreak: 1721-100, 1d.42m
    urlhaus-1: 8437-2, 36m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 897 ms (selfie)
  maxAssetCacheWait: 797 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    multiup.org: 1
```
</details>

**Comment by mapx-** [comment]
does this exception work ?

`multiup.*#@#+js(disable-newtab-links)`

**Comment by jimmysofat6864** [comment]
@mapx- yes that works you can add that onto the filter lists now.

**Comment by mapx-** [comment]
You opened another issues maybe the exception above disabled a filter blocking the popups you reported
