### ISSUE TITLE
[nsfw] web.era-edta.org: popups

### ISSUE THREAD

**Issue by Visitage** [uBlockOrigin/uAssets#12130]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://beganfieldspeed.top/`

### Category

popups

### Describe the issue

The site pops up and takes over the tab, persists even if you you try to go back.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 125375
  cosmetic: 130227
  scriptlet: 33271
  html: 632
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 62313-5117, 2d.23h.17m
    adguard-spyware: 27000-945, 2d.23h.15m
    adguard-annoyance: 50604-4411, 2d.23h.13m
    adguard-social: 16039-1623, 2d.23h.12m
    fanboy-thirdparty_social: 68-1, 3d.14h.57m
    fanboy-annoyance: 59144-47473, 3d.14h.56m
    fanboy-cookiemonster: 21085-13185, 1d.1h.44m
    fanboy-social: 23191-13516, 2d.23h.10m
    ublock-annoyances: 4397-7, 2d.23h.16m
    adguard-spyware-url: 491-3, 2d.23h.14m
    block-lan: 44-0, 4m
  default: 
    user-filters: 14-0, never
    ublock-filters: 30890-262, 2d.23h.9m
    ublock-badware: 3943-3, 1d.15h.27m
    ublock-privacy: 206-1, 1d.15h.32m
    ublock-abuse: 72-0, 2d.23h.8m
    ublock-unbreak: 1737-0, 1d.15h.29m
    adguard-mobile: 7321-344, never
    easylist: 64349-24196, 1d.15h.28m
    easyprivacy: 26652-10885, 1d.15h.31m
    urlhaus-1: 8437-0, 14h.30m
    plowe-0: 3673-2, 8d.11h.5m
filterset (user): [array of 14 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1828 ms (selfie)
  maxAssetCacheWait: 1327 ms
popupPanel: 
  blocked: 2
  no-large-media: true
  blockedDetails: 
    beganfieldspeed.top: 2
```
</details>

**Comment by okiehsch** [comment]
> The site pops up and takes over the tab, persists even if you you try to go back.

Where does it pop up?

**Comment by mapx-** [comment]
is `https://beganfieldspeed.top/` the popup redirection ?
which is the real page where you clicked on and got the popups ?

**Comment by Visitage** [comment]
Ah, thats the word, yes, it was 
https://web.era-edta.org/uploads/pj5hl/will-the-supernova-in-2022-affect-earth

Thanks

**Comment by okiehsch** [comment]
That looks like a fake site, how did you end up at 
`https://web.era-edta.org/uploads/pj5hl/will-the-supernova-in-2022-affect-earth`

**Comment by mapx-** [comment]
maybe you want to download some file, provide that link

**Comment by Visitage** [comment]
I searched
`will we see a supernova in the sky`
And clicked 
`Will we see a supernova in 2022?`
![Screenshot_20220309-124826](https://user-images.githubusercontent.com/101285183/157510575-d0bd092d-de74-40fe-b1ff-59fda1358fdb.png)

**Comment by Visitage** [comment]
This was the first link
![Screenshot_20220309-125131](https://user-images.githubusercontent.com/101285183/157511142-f67d43aa-fa8e-4c7b-bd87-f7fe8634983b.png)

Now yhat i think about it i dont know if an adblocker can fix this

**Comment by okiehsch** [comment]
Hm, looks like that site was hacked.

**Comment by okiehsch** [comment]
I can reproduce but the best we can do is blocking `beganfieldspeed.top`.
