### ISSUE TITLE
Too many domains allowed in the exception for Intel in *Block Outsider Intrusion into LAN*

### ISSUE THREAD

**Issue by dungsaga** [uBlockOrigin/uAssets#12139]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.thailand.intel.com/content/www/th/th/support/intel-driver-support-assistant.html`

### Describe the issue

Ticket https://github.com/gwarser/filter-lists/issues/19 introduced an exception for Intel Drivers and Support Assistant
```
@@||127.0.0.1^*/intel/$xhr,domain=www.intel.*
```
This change allowed too many domains and it could be used in attacks (such as from www.intel.any.domain.com).

I proposed that we restrict this exception to the domains used by Intel.
Here is the list of domains I collected from the page Intel Drivers and Support Assistant (https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html):
```
www.intel.ca
www.intel.cn
www.intel.co
www.intel.com
www.intel.de
www.intel.es
www.intel.fr
www.intel.ie
www.intel.in
www.intel.it
www.intel.la
www.intel.pl
www.intel.ru
www.intel.sg
www.intel.vn
www.thailand.intel.com
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/5884951/157568648-4afe4ced-90c1-4899-8920-aca8bd199798.png)

### uBlock Origin version

1.41.8

### Browser name and version

Google Chrome 99.0.4844.51

### Settings

- select *Block Outsider Intrusion into LAN* in tab *Filter lists*

**Comment by mapx-** [comment]
@gwarser

**Comment by krystian3w** [comment]
> This change allowed too many domains and it could be used in attacks (such as of `www.intel.any.domain.com]`).

How about nope? The `domain=intel.*` reject load request on `any.domain.com`, becasue support only public suffix (in incorrect naming "TLD").

**Comment by krystian3w** [comment]
> This change allowed too many domains and it could be used in attacks (such as from/on `www.intel.any.domain.com`).

How about nope? The `domain=intel.*` reject load request on `any.domain.com`, becasue support only public suffix (in incorrect naming "TLD"). Also the simple syntax newtwork allow filter no have bug to load request form `domain.com` at Intel online page and vice-versa.

But if intel have only 15 regional public suffix then can by changed, if Intel don't fastly start buy and run new translations on new public suffix (but we see 🇹🇭 uses com instead run th public suffix).

Then test page should be fixed too for uBlock Origin Legacy in Firefox 45-56, PaleMoon, Basilisk and Watefox Classic.

---

Real attack with bug in ["`domain=evil.*`"](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity) on your e.g. `google.any.domain.com` the best report via mail: https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=security_report.yml

> Since the base domain name is used to derive the name of the "entity", `google.evil.biz` would not match `google.*`.

Wouldn't ≠ mustn't not so can by bugged.

**Comment by dungsaga** [comment]
> How about nope? The `domain=intel.*` reject load request on `any.domain.com`, becasue support only public suffix (in incorrect naming "TLD").

The public suffix list contains many cloud providers, and the attacker can use domains such as www.intel.herokuapp.com or www.intel.now.sh or even some weird TLD like www.intel.band or www.intel.bar

**Comment by dungsaga** [comment]
> Real attack with bug in ["`domain=evil.*`"](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity) on your e.g. `google.any.domain.com` the best report via mail:

This is not a bug for parsing `domain=evil.*`. This is a bug in an exception rule of *Block Outsider Intrusion into LAN* in tab *Filter lists*

**Comment by dungsaga** [comment]
@gwarser I'm curious to know why you deleted the whole exception instead of extending the part `domain=www.intel.*` to include domains used by Intel ?

**Comment by krystian3w** [comment]
Test page maybe no longer check xmlhttprequest, so filter can be outdated.

Then deletion is goodnes like "salmon from the company 'MOWI is good'".

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12287

**Comment by Jap2-0** [comment]
@gwarser I realize the other thread is locked so I'll only leave one brief comment here (along with my apologies), but to me "intrusion" implies unwanted/malicious use, rather than software I installed doing what I installed it to do.

**Comment by Jap2-0** [comment]
(Apologies for the late reply; I realize I'm kind of beating a dead horse here, but stumbled across this and thought I'd respond because none of these seem like clear reasons against this.  Apologies if I'm misunderstanding any of them.)


> Test page maybe no longer check xmlhttprequest, so filter can be outdated e.g. started use webrtc

...any filter can become outdated and cause breakage later?


> But malware can won with your Inteled localhost (override data needed on Intel page).

If you mean malware on my computer, then I already have malware on my computer, and it can bypass the browser; if you mean malware on intel.com, then it's trivial to get me to install an arbitrary executable as an updated driver, if you mean the intel.* issue, that can be resolved by a fixed list of TLDs.


> Also Intel with any exception can generate metod to tracking.

If I'm installing their software on my computer (rather than accessing their website), that's kind of become my problem, and they can bypass the browser anyway.
