### ISSUE TITLE
web.facebook.com: ads

### ISSUE THREAD

**Issue by al-reza421** [uBlockOrigin/uAssets#12141]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://web.facebook.com/`

### Category

ads

### Describe the issue

It seems that Facebook has found a way again to slip in their "Sponsored posts" by placing a sponsored contents on the right sidebar above "Contacts".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/101309820/157591938-fa2ca952-b5cf-45b1-b4e6-b6f1ad18e89a.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 84432
  cosmetic: 45947
  scriptlet: 16443
  html: 623
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 13h
    IDN-0: 8862-2, 15h.38m
  default: 
    user-filters: 3-0, never
    ublock-filters: 30790-187, 15h.39m
    ublock-badware: 3960-3, 15h.39m
    ublock-privacy: 204-0, 15h.39m
    ublock-abuse: 72-0, 15h.39m
    ublock-unbreak: 1733-0, 15h.39m
    easylist: 64407-485, 15h.38m
    easyprivacy: 26653-585, 15h.38m
    urlhaus-1: 8437-0, 15h.38m
    plowe-0: 3674-2, 15h.38m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2096 ms (selfie)
  maxAssetCacheWait: 806 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3367
