### ISSUE TITLE
megafly.in : Anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12144]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://megafly.in/VkLu`

### Describe the issue

The Adblock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/157625196-bc7c2250-8b17-4663-b13c-dd10a4ddf076.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by mapx-** [comment]
fixed yesterday, update your lists

**Comment by blazesprings** [comment]
Yep, thanks. It's working after updating.

**Comment by LikesCakes** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/126893
- a timer was encountered
- right click didn't work on one page
- anti adb was encountered
