### ISSUE TITLE
link1s.com : Anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12145]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://link1s.com/yDD4f7`

### Describe the issue

On stage 2, the adblock is detected. There is no adblock detection message or banner but you can't go to the next link.
After I disable the UBlock, it works fine.

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by okiehsch** [comment]
> [okiehsch](https://github.com/okiehsch) closed this in https://github.com/uBlockOrigin/uAssets/commit/f865e207c860e74a8432895b33e640dc8a1222b5 [9 minutes ago](https://github.com/uBlockOrigin/uAssets/issues/12145#event-6216045219)

That means that I added a fix that should work, force an update of your `uBO-filter` list.

**Comment by blazesprings** [comment]
Yes it works now. Closed.
