### ISSUE TITLE
adx.rs: breakage

### ISSUE THREAD

**Issue by markom84** [uBlockOrigin/uAssets#12147]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://adx.rs/`

### Category

breakage

### Describe the issue

Website does not load properly when uBlock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79965
  cosmetic: 41366
  scriptlet: 16473
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64277-10, 3d.12h.28m
    easyprivacy: 26652-121, 2d.12h.24m
    plowe-0: 3674-805, 3d.4h.26m
    ublock-abuse: 72-0, 3d.12h.30m
    ublock-badware: 3929-85, 3d.12h.32m
    ublock-filters: 30205-151, 3d.12h.34m
    ublock-privacy: 203-2, 3d.12h.31m
    ublock-unbreak: 1720-39, 3d.12h.29m
    urlhaus-1: 8437-0, 5h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 427 ms (selfie)
  maxAssetCacheWait: 299 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    adx.rs: 3
```
</details>

**Comment by mapx-** [comment]
@ryanbr
