### ISSUE TITLE
shr.cash

### ISSUE THREAD

**Issue by PerfectSalad** [uBlockOrigin/uAssets#12140]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

present in https://github.com/AdguardTeam/AdguardFilters/issues/57155

### Describe the issue

- Annoyance
- Disappearing popup
- ads

### uBlock Origin version

1.41.8

### Browser name and version

Tor

### Settings

.

### Notes

Should
```
shr.cash##.swal2-backdrop-show.swal2-center.swal2-container
shr.cash##body:style(overflow: auto !important;)
shr.cash##+js(aopr, open)
.gif$domain=shr.cash
```
be added?

Also, one filter for `shr.cash` may be obsolete.

**Comment by ExpertMen** [comment]
Maaan, you're using Tor Browser too???????????????????
