### ISSUE TITLE
adw.amsterdam.nl: breakage

### ISSUE THREAD

**Issue by silasje1** [uBlockOrigin/uAssets#12143]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://adw.amsterdam.nl/`

### Category

breakage

### Describe the issue

This is our Citrix webpage, due to the blocking the website won't load. Please remove this page from adblocks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80594
  cosmetic: 42743
  scriptlet: 16493
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2091-12, 22m
    easylist: 64277-11, 3d.17h.46m
    easyprivacy: 26646-121, 3d.17h.45m
    plowe-0: 3674-805, 7d.26m
    ublock-abuse: 72-0, 3d.17h.44m
    ublock-badware: 3929-85, 3d.17h.43m
    ublock-filters: 30218-197, 3d.17h.42m
    ublock-privacy: 203-2, 3d.17h.41m
    ublock-unbreak: 1723-54, 3d.17h.40m
    urlhaus-1: 8437-0, 21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 161 ms (selfie)
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    amsterdam.nl: 10
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`/adw.$domain=~adw.be|~adw.olsztyn.pl|~adw.org|~adw.org.pl|~valadoc.org`
is breaking the site.
