### ISSUE TITLE
myworkdayjobs.com cosmetic filtering

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1215]
### URL(s) where the issue occurs

`https://astrazeneca.wd3.myworkdayjobs.com/en-US/Careers/jobs`

### Describe the issue

With cosmetic filtering enabled, no results appear.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/34655395-f9a0481e-f3d6-11e7-8721-091c74390dac.png)

### Versions

- Browser/version: Chrome 63
- uBlock Origin version: 1.14.22

### Settings

Default

### Notes

This was not broken previously. Just started happening recently.

**Comment by nimasaj** [comment]
I cannot produce this issue, and the page is shown as it's supposed to. Do you have any rules in "my filters" section?

**Comment by okiehsch** [comment]
Same issue as https://github.com/uBlockOrigin/uAssets/issues/1206, already fixed with https://github.com/uBlockOrigin/uAssets/commit/0d1d9cf411bee8fee3efa81bdf55db6e2a6d13e6.

Just update your `uBlock filters` list.

**Comment by terrorist96** [comment]
Confirmed. Thanks!
