### ISSUE TITLE
eurogamer.net: nuisance

### ISSUE THREAD

**Issue by Ghost-BD** [uBlockOrigin/uAssets#12157]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.eurogamer.net/`

### Category

nuisance

### Describe the issue

www.eurogamer.net cookie notice (huge one, more of a pop up). Does not bother with adguard browser extension. With or without "uBlock filters – Annoyances" and "adguard annoyances" filter cookie notice shows with uBlock Origin but not with adguard browser extension. Reported [there](https://github.com/AdguardTeam/AdguardFilters/issues/109023) but they said need JS rules. I don't understand such things. JS rules might cause security issues, but they find a way and hope you can also. Another question, does there any uBlock Origin equivalent of adguard stealth mode? Like hide search queries, Self-destruction of third-party cookies etc. If not any plan to implement? Looks useful for better privacy.

### Screenshot(s)

![eurogamer cookie notice](https://user-images.githubusercontent.com/98824052/157737097-ca8682ad-1eea-422a-9cdd-34f842990b5b.jpg)
<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 84521
  cosmetic: 86388
  scriptlet: 21492
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50707-156, now
    ublock-annoyances: 4358-152, 1m
  default: 
    user-filters: 0-0, never
    easylist: 64500-48, now
    easyprivacy: 26664-213, now
    plowe-0: 3675-806, now
    ublock-abuse: 72-0, now
    ublock-badware: 3967-85, now
    ublock-filters: 30223-466, now
    ublock-privacy: 200-2, now
    ublock-unbreak: 1724-43, now
    urlhaus-1: 8437-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2146 ms
  maxAssetCacheWait: 563 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    eurogamer.net: 1
    onetrust.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
Have you tried enabling Fanboy's Annoyance?

**Comment by Ghost-BD** [comment]
Yep. But I like adguard one more.

**Comment by okiehsch** [comment]
Well, what do you want me to do?
I can't force them to block it.

**Comment by okiehsch** [comment]
We don't fix GDPR modals in `uAssets` as per our readme.

**Comment by Ghost-BD** [comment]
If blocked with cosmetic filter, it breaks website. Other filters don't try to block it for that reason. But with adguard browser extension I don't experience any website breakage, but they blocked the cookie notice properly. They asked for JS rules.

**Comment by okiehsch** [comment]
TRy adding
````
eurogamer.net##.onetrust-pc-dark-filter
eurogamer.net###onetrust-banner-sdk
eurogamer.net###onetrust-consent-sdk
````
to your filter list.

**Comment by Ghost-BD** [comment]
Try to view https://www.eurogamer.net/articles/digitalfoundry-2022-elden-ring-the-last-gen-analysis-can-the-older-consoles-still-cut-it page sir.
![euro broken](https://user-images.githubusercontent.com/98824052/157741713-a2925c16-3b81-45a4-93a7-07c38c83411a.jpg)

**Comment by okiehsch** [comment]
We can't fix that.

**Comment by PerfectSalad** [comment]
@okiehsch what about `eurogamer.net##+js(aopr, showOneTrustPlaceholders)` ?

**Comment by PerfectSalad** [comment]
@ryanbr what do you think?

**Comment by okiehsch** [comment]
How does that fix it?
I assuem the OP wants to see the content without accepting any cookies.

**Comment by Ghost-BD** [comment]
Still doesn't work. Breaks site.

**Comment by okiehsch** [comment]
It's not possible for us to circumvent it we don't support the ability to set cookies for security reasons.

**Comment by Ghost-BD** [comment]
Adguard set my cookie?

**Comment by PerfectSalad** [comment]
nvm

@Ghost-BD AdGuard Annoyances works best with AdGuard browser Extension (Windows/Mac/Linux/Android Firefox) / Program (Windows/Mac) as far as I know

**Comment by okiehsch** [comment]
I understand that but they won't show you externally hosted content without you accepting cookies.

> Adguard set my cookie?

I don't know.

**Comment by PerfectSalad** [comment]
> Adguard set my cookie?

AG rule engineers can make scripts that either mimic a click or "click" the accept button, for example -- for certain AG products

**Comment by Ghost-BD** [comment]
Ok bro, thanks for trying though. I completely missed that GDPR readme and just liked ublock origin more that's all. One website isn't a huge deal. Thank you again.

**Comment by Ghost-BD** [comment]
Ok bro, thanks for trying though. I completely missed that GDPR readme and just liked ublock origin more that's all. One website isn't a huge deal. Than you again.
