### ISSUE TITLE
huk24.de: breakage

### ISSUE THREAD

**Issue by piefel** [uBlockOrigin/uAssets#12154]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.huk24.de/meine-huk24/begruessung`

### Category

breakage

### Describe the issue

Note HUK24 is an insurance company.

`GET https://www.huk24.de/cookiebanner/cookiebanner.js` is blocked (yes, this looks very suspicious, but is from the same site), `POST https://xps.huk24.de/rest/v1/delivery?client=hukcoburg&sessionId=…` is blocked.

Page remains completely grey.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 91597
  cosmetic: 98665
  scriptlet: 16493
  html: 622
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    fanboy-annoyance: 65346-4336, 2d.9h.58m
  default: 
    user-filters: 2777-6, never
    ublock-filters: 30786-37, 2d.9h.57m
    ublock-badware: 3955-3, 2d.9h.56m
    ublock-privacy: 206-0, 2d.10h.1m
    ublock-abuse: 72-0, 2d.9h.55m
    ublock-unbreak: 1731-0, 2d.10h.2m
    easylist: 64352-632, 2d.10h
    easyprivacy: 26653-127, 2d.9h.59m
    plowe-0: 3673-445, 8d.22h.41m
    DEU-0: 5532-13, 6m
    urlhaus-1: 8047-0, 2d.9h.54m
filterset (user): [array of 2777 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 268 ms (selfie)
  maxAssetCacheWait: 383 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    huk24.de: 2
    omtrdc.net: 1
```
</details>

**Comment by PerfectSalad** [comment]
@ryanbr

**Comment by okiehsch** [comment]
`@@||huk24.de/cookiebanner/cookiebanner.js$script,1p`
