### ISSUE TITLE
booking.rm.dk: [unknown]

### ISSUE THREAD

**Issue by jacobhl** [uBlockOrigin/uAssets#12159]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://booking.rm.dk/selvbooking/`

### Category

[unknown]

### Describe the issue

Site for booking hospital-times for danish hospitals.

Danish error message saying: 
"Åh nej...
Forbindelsen til MineAftaler er blevet afbrudt. Vi forsøger automatisk at forbinde dig igen.
Prøv igen senere hvis forbindelsen ikke bliver genoprettet"
and a spinning wheel gif.

When uBlock Origin is disabled the site loads normally.

Tested on two different computers (both Chrome)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80182
  cosmetic: 41431
  scriptlet: 16488
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64500-10, 1m
    easyprivacy: 26664-121, 1m
    plowe-0: 3675-805, 1m
    ublock-abuse: 72-0, 1m
    ublock-badware: 3967-85, 1m
    ublock-filters: 30223-145, 1m
    ublock-privacy: 200-2, 1m
    ublock-unbreak: 1724-39, 1m
    urlhaus-1: 8437-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 756 ms (selfie)
  maxAssetCacheWait: 573 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    rm.dk: 1
```
</details>

**Comment by okiehsch** [comment]
Wait a few minutes then update the `uBO-unbreak` list, should work fine after that.
