### ISSUE TITLE
abc.es/bienestar

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#12155]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.abc.es/bienestar/`

### Describe the issue

The images of section `bienestar` in `https://www.abc.es` is break

Not in other "topics" example:
```
https://www.abc.es/sociedad/
https://www.abc.es/deportes/
```
...

### uBlock Origin version

1.41.8

### Browser name and version

Chrome - 99.0

### Settings

![Capturaf](https://user-images.githubusercontent.com/33556647/157736983-78e1dd74-65d1-4b21-999b-c9b76ac38d16.PNG)

**Comment by PIZZA90** [comment]
Maybe the filter `abc.es##+js(aopr, vocento.tracking)`  in _uBlock filters – Annoyances_

**Comment by okiehsch** [comment]
Yes, thanks for investigating, saves me some time. 😉

**Comment by okiehsch** [comment]
I commented it out for now, can you check if there is any anti adblock message occuring now?

**Comment by garry-ut99** [comment]
Ad placeholders all over the site, caused by `ghide` in "uBlock filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/214687719-b72b87f1-76e3-476a-a63d-f3a5b58330de.png)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0dbbe3df3ee4af5a6cfe5f2c00253662225d5188

**Comment by mapx-** [comment]
site issue, even disabling uBO I get only the ads but not the normal pics

**Comment by garry-ut99** [comment]
Also the images don't appear coz they are not even images, they are spying pixels: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/214695249-b18890ef-f535-475b-bd15-583018ed073a.png)
