### ISSUE TITLE
breakage - grandecosmetics.com

### ISSUE THREAD

**Issue by SyedSan1** [uBlockOrigin/uAssets#12153]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://grandecosmetics.com/`

Our client has implemented video carousel on their website and are reporting the videos are blocked from running. Please see the below screenshot.
![ublock origin](https://user-images.githubusercontent.com/93693440/157731591-0e84b4c3-8bde-4dfe-ba65-b0e73b8895ac.png)

### Describe the issue

We provide a video technology platform for partners to embed instagra/ tiktok like videos on their website.
Grande Cosmetics recently shared that their video is getting blocked by uBlock Origin.

Note, we don't put outside advertisements. We provide technology that the customers can use to put their product videos which is what happens in 90%+ cases. Occasionally, a customer may decide to insert ads.

We recently worked with the AdGuard team to get this issue resolved here by allowing filters to pass our content CDNs.
[Here](https://github.com/AdguardTeam/AdguardFilters/issues/111021)

We'd appreciate a similar resolution on this. Thank you.

### uBlock Origin version

1.41.8

### Browser name and version

Chrome - 98.0.4758.102 

### Settings

I am not aware what changes end viewers are making that makes the ublock to block video content on the website.

**Comment by okiehsch** [comment]
> Our client has implemented video carousel on their website and are reporting the videos are blocked from running.

I don't see any video at the provided link even if I disable `uBlock Origin`.

**Comment by okiehsch** [comment]
By the way your screenshot also shows that no request has been blocked.

**Comment by PerfectSalad** [comment]
Is this related to `fireworktv.com`?

@ryanbr can you take a look if you haven't already?

**Comment by mapx-** [comment]
PerfectSalad => all here => https://github.com/AdguardTeam/AdguardFilters/issues/111021

**Comment by okiehsch** [comment]
Well, they only show those videos outside the EU for a reason... 
@gorhill what do you think?
Should we follow Adguard in allowing those videos to play?

**Comment by mapx-** [comment]
why not, all legit

```
||fwcdn2.com^$third-party,badfilter
||fireworkapi.com^$third-party,badfilter
||fireworktv.com^$third-party,badfilter
```

**Comment by mapx-** [comment]
see https://fireworkapi.com/ site => all legit, broken by EL

**Comment by PerfectSalad** [comment]
> PerfectSalad => all here => [AdguardTeam/AdguardFilters#111021](https://github.com/AdguardTeam/AdguardFilters/issues/111021)

I remember seeing something somewhat related to this -- I mentioned @ryanbr in case this would change his mind on a decision

**Comment by mapx-** [comment]
It's only a tool, if someone is using it for ads we can block it on that specific site

**Comment by okiehsch** [comment]
It's fine by me I only wanted to check with gorhill before we badfiltered it.

**Comment by SyedSan1** [comment]
Thank you for correctly understand @mapx- 

We are happy to work with you guys to ensure that ads get blocked but the content should be allowed. So many websites are getting impacted with blanket block on content that EL is applying. 
fwcdn2 is for content only
this is the ads one - http://fireworkadservices.com/
fwpub1 is for publishers and was considered "annoyance" by AdGuard but still unblocked coz it's not an ad.

**Comment by ryanbr** [comment]
You keep spawning new domains, and cannot be trusted.  I'm looking at `fwcdn3.com`  and `fireworkapi1.com`, there is probably more.  For attempted to get around Easylist, it should remain blocked.

**Comment by gorhill** [comment]
> @gorhill what do you think?

Had to use a US IP to see the video. The videos are clearly legitimate content, and the server serving them describes itself as _"Short form Video And Live Streaming On Your website"_, which sounds legitimate. As @mapx- says, if these short forms are used for ads on some other sites, we can create filters for those sites specifically.

**Comment by SyedSan1** [comment]
@ryanbr 
As we shared before, we would like to work with you to ensure we comply with EL but we can't stop our business. 
I understand you think that these are not good visitor experiences but the stats are showing us that the engagement and transactions are very strong. As a result, the Fresh Market recently signed us up.
https://www.winsightgrocerybusiness.com/retailers/fresh-market-taps-firework-expand-omnichannel-experiences
Duda recently signed up with us to get the videos to their agencies
https://www.prnewswire.com/news-releases/firework-and-duda-join-forces-to-deliver-live-shopping-and-interactive-video-capabilities-to-over-1m-websites--17k-agencies-301500490.html 
Square and Shopify are trying to work with us.

All ads will be coming from fireworkadservices.com, so there is no need to block content CDNs. 
Please let us know what can we do to help and be compliant with EL.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/caac39ee564de5e1760c5ed76541c856d184a68a

If we see reports of any abuse or workarounds we'll re-evaluate this patch

**Comment by SyedSan1** [comment]
Hi @ryanbr 
Our intent is to not abuse with workaround but avoid legal problems both for adblock companies and us. We had customers who were extremely upset about their videos getting blocked on their website and wanting to go legal route. We are splitting our domains between content and ads and analytics so our users can access the content and allow easy list to block the ads requests.
We can post on github (where you recommend) every time we have any new domain to let you know. We can certainly work with you and be transparent to ensure we're a trustful partner.
