### ISSUE TITLE
Ublock not blocking ADs properly

### ISSUE THREAD

**Issue by lazinism** [uBlockOrigin/uAssets#12163]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tgd.kr/`

### Describe the issue

Not blocking Ads properly
if I custom my filter to block ad, then it shows error message popup (saying image block by adblock)

### Screenshot(s)

![화면 캡처 2022-03-11 181701](https://user-images.githubusercontent.com/3297355/157838162-31395822-eddc-4aa3-9fe4-2536be2233dc.png)

### Notes

there's several ads that trying to avoid adblocks

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82055
  cosmetic: 47688
  scriptlet: 16479
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    KOR-1: 8149-0, 1h.3m
    easylist: 64505-17, 1h.3m
    easyprivacy: 26664-125, 1h.3m
    plowe-0: 3675-807, 1h.3m
    ublock-abuse: 72-0, 1h.3m
    ublock-badware: 3967-85, 1h.3m
    ublock-filters: 30198-142, 1h.3m
    ublock-privacy: 200-2, 1h.3m
    ublock-unbreak: 1725-39, 1h.3m
    urlhaus-1: 8437-0, 1h.3m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1558 ms (selfie)
  maxAssetCacheWait: 339 ms
```
</details>

**Comment by okiehsch** [comment]
Does adding 
`tgd.kr##+js(nostif, [native code], 0)`
work without breaking anything.

**Comment by lazinism** [comment]
> 

OMG it works Thanks

**Comment by JobcenterTycoon** [comment]
@okiehsch no the image get hidden by ad shield, they detecting it. It must be look like
<img width="675" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/157857363-9885d7d6-dc73-433c-91c1-9b7f372cf770.PNG">

**Comment by okiehsch** [comment]
Ok.

**Comment by mapx-** [comment]
if it works, go ahead !

**Comment by lazinism** [comment]
> 

I think 
`ygosu.com,ppss.kr,tgd.kr##div[style="position: relative; display: inline-block; text-align: center;"]:style(height:1px;width:1px;overflow:hidden; !important)`
would be better, cause 'left 10k px' is kinda annoying when you mis-scrolled page

**Comment by JobcenterTycoon** [comment]
@mapx-  `##+js(nostif, [native code], 0)` no longer working i don’t know why

**Comment by mapx-** [comment]
I get no `native code` anymore

It seems working something like this (could break something)
`tgd.kr##+js(nostif, , 0)`

**Comment by JobcenterTycoon** [comment]
It works perfectly, even on the other 2 sites.

**Comment by JobcenterTycoon** [comment]
Seems to be there is no adcrap script anymore on this site

**Comment by ButterVsMargarine** [comment]
`https://skmedix.pl/downloads`
`googleads.g.doubleclick.net##.banner`
