### ISSUE TITLE
unlistedvideos.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#12164]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://unlistedvideos.com/search.php`

### Category

ads

### Describe the issue

if you search for something and then scroll all the way down there are ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/81616288/157838775-be8971f7-b113-4de2-a5c7-a07ccd49a588.jpeg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82293
  cosmetic: 44818
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    DEU-0: 5532-0, 2h.5m
    easylist: 64505-16, 2h.5m
    easyprivacy: 26664-132, 2h.5m
    plowe-0: 3675-806, 2h.5m
    ublock-abuse: 72-0, 2h.5m
    ublock-badware: 3967-85, 2h.5m
    ublock-filters: 30197-149, 2h.5m
    ublock-privacy: 200-2, 2h.5m
    ublock-unbreak: 1725-40, 2h.5m
    urlhaus-1: 8437-0, 2h.5m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  uiTheme: dark
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2523 ms (selfie)
  maxAssetCacheWait: 1729 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    unlistedvideos.com: 2
    infolinks.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`||followlike.net/extinban.php$frame,3p`
