### ISSUE TITLE
imggold.org [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1216]
URL(s) where the issue occurs

`http://imggold.org/tlxf80d1osyi/xxxft.jpg.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
||imggold.org##script:inject(abort-current-inline-script.js, popundersPerIP)
||zbzksshdcwrka.bid*
||mtpjldykpuhnmg.bid*
||32a79e2833309ebe.com*

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
