### ISSUE TITLE
clerk.io: breakage

### ISSUE THREAD

**Issue by Drugantibus** [uBlockOrigin/uAssets#12167]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.grejfreak.dk/`
`https://trony.it`
`https://unisportstore.com`

### Describe the issue

Today's update of EasyPrivacy introduced this filter: `||clerk.io^$3p`, breaking core functionality (e.g. search) for websites using clerk.io. The URLs provided are just an example, thousands of webshops are impacted.

### uBlock Origin version

1.41.9

### Browser name and version

Chrome 100

### Settings

None - aside from disabling EasyPrivacy after discovering the issue

**Comment by mapx-** [comment]
@ryanbr EP issue see how's broken `trony.it`

**Comment by Drugantibus** [comment]
Thanks for the blazing fast response! Kudos :100:
