### ISSUE TITLE
leboncoin.fr: breakage

### ISSUE THREAD

**Issue by groumi4246** [uBlockOrigin/uAssets#12179]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.leboncoin.fr/compte/part/mes-annonces`

### Category

breakage

### Describe the issue

Pictures of the listings are not displayed. Deactivating Ublock on the page makes them reappear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://user-images.githubusercontent.com/101430438/157964578-734a9983-7256-4d5f-80d8-9cff66a1cf16.png

https://user-images.githubusercontent.com/101430438/157964694-9b863757-5e07-412a-a2f6-847711392072.png

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 96738
  cosmetic: 50458
  scriptlet: 16502
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 30795-28, 9h.3m
    ublock-badware: 3971-3, 9h.2m
    ublock-privacy: 204-0, 9h.1m
    ublock-abuse: 72-0, 9h.8m
    ublock-unbreak: 1736-0, 9h.7m
    easylist: 64520-632, 9h.6m
    easyprivacy: 26665-887, 9h.5m
    urlhaus-1: 8437-0, 9h
    plowe-0: 3673-2, 12d.9h.15m
    FRA-0: 26195-195, 1h.38m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 390 ms (selfie)
  maxAssetCacheWait: 242 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    aticdn.net: 1
    doubleclick.net: 1
    hubvisor.io: 1
    pinimg.com: 1
    realytics.io: 2
    realytics.net: 2
```
</details>

**Comment by mapx-** [comment]
Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by groumi4246** [comment]
![image](https://user-images.githubusercontent.com/101430438/157974435-d5e54a75-d2e8-4254-951b-cc0d024e857a.png)

<details><summary>Logger output</summary>

```
+118
##div[class^="styles_ad__"]
www.leboncoin.fr
dom
https://www.leboncoin.fr/compte/part/mes-annonces
```
```
+117
/realytics-
--
www.leboncoin.fr
3
script
https://cdn-eu.realytics.net/realytics-1.2.min.js
```
```
+117
||realytics.io^$3p
--
www.leboncoin.fr
3
script
https://i.realytics.io/tc.js?cb=1647034892012
```
```
+117
/realytics-
--
www.leboncoin.fr
3
script
https://cdn-eu.realytics.net/realytics-1.2.min.js
```
```
+117
||realytics.io^$3p
--
www.leboncoin.fr
3
script
https://i.realytics.io/tc.js?cb=1647034891555
```
```
+117
||s.pinimg.com/ct/core.js
--
www.leboncoin.fr
3
script
https://s.pinimg.com/ct/core.js
```
```
+116
||hubvisor.io^$3p
--
www.leboncoin.fr
3
script
https://cdn.hubvisor.io/wrapper/01CE9HZCZVPW9QB522QNNS8MZQ/hubvisor.js
```
```
+115
googletagservices_gpt.js
<<
www.leboncoin.fr
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+115
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js
--
www.leboncoin.fr
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+115
||doubleclick.net^
--
www.leboncoin.fr
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+115
||tag.aticdn.net^
--
www.leboncoin.fr
3
script
https://tag.aticdn.net/598455/smarttag.js
```
```
+115
https://www.leboncoin.fr/compte/part/mes-annonces
```
```
+0
no-csp-reports: * true
--
www.messenger.com
0,3
csp_report
https://www.facebook.com/csp/reporting/?m=t&minimize=0
```
</details>

**Comment by Procyon-b** [comment]
I would have created an account but they need a french phone number. A belgian one doesn't work.

**Comment by mapx-** [comment]
does this work ?

`leboncoin.fr#@#div[class^="styles_ad__"]`

**Comment by groumi4246** [comment]
Yes it does! Thanks

**Comment by mapx-** [comment]
@smed79

**Comment by smed79** [comment]
https://github.com/easylist/listefr/commit/bd5378d824672c1668b511d3495a682c5a01726e

Thank you.
