### ISSUE TITLE
imgsay.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1217]
URL(s) where the issue occurs

`http://imgsay.com/?v=519478.jpg`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
> Warn with "**NSFW**" where applicable.
