### ISSUE TITLE
help.divineshop.vn: nuisance

### ISSUE THREAD

**Issue by nghiabros** [uBlockOrigin/uAssets#12189]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://help.divineshop.vn/huong-dan-thanh-toan`

### Category

nuisance

### Describe the issue

cookies detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43260081/158000508-00399cfe-779b-484d-a435-cbc65751b850.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 100915
  cosmetic: 87749
  scriptlet: 21284
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41732-9, 21h.4m
    VIE-1: 2031-2, 21h.3m
    fanboy-cookiemonster: 24066-44, 4d.1h.40m
    ublock-annoyances: 4356-121, 1h.12m
  default: 
    user-filters: 0-0, never
    easylist: 64579-33, 1h.15m
    easyprivacy: 26666-221, 1h.14m
    plowe-0: 3674-810, 4d.1h.40m
    ublock-abuse: 72-1, 1h.13m
    ublock-badware: 3967-85, 1h.11m
    ublock-filters: 30197-187, 1h.10m
    ublock-privacy: 200-2, 1h.9m
    ublock-unbreak: 1725-40, 1h.8m
    urlhaus-1: 8437-0, 21h.2m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 490 ms (selfie)
  maxAssetCacheWait: 328 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`divineshop.vn###animatedComponent`

@ryanbr
