### ISSUE TITLE
[nsfw] mini.eastday.com: ads

### ISSUE THREAD

**Issue by yangtingti** [uBlockOrigin/uAssets#12187]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mini.eastday.com/?qid=04421`

### Category

ads

### Describe the issue

总是自动弹出此网站 `https://mini.eastday.com/?qid=04433&rfstyle=qt`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 98131
  cosmetic: 51491
  scriptlet: 16585
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28244-88, 13h.17m
    easylist: 64520-13, 13h.14m
    easyprivacy: 26665-147, 13h.13m
    plowe-0: 3675-807, 13h.12m
    ublock-abuse: 72-0, 13h.9m
    ublock-badware: 3967-85, 13h.5m
    ublock-filters: 30201-160, 13h.4m
    ublock-privacy: 200-2, 13h.3m
    ublock-unbreak: 1725-40, 13h.2m
    urlhaus-1: 8437-0, 13h
filterset (user): [empty]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 403 ms (selfie)
  maxAssetCacheWait: 193 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
```
</details>

**Comment by PerfectSalad** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
I got popunder to `https://lieqi.kzynews.com/a/220220141816823184251.html?qid=ttdlq&njump=https%3A%2F%2Fmini.eastday.com%2F` only at the very first click on `https://mini.eastday.com/special_121.html` link on the reported page but can not reproduce any more. The site opening links in new tab is site's design. Wonder if anyone can reproduce the popunder.

**Comment by mapx-** [comment]
No popunder on my end

**Comment by Yuki2718** [comment]
I can't reproduce now too, no idea what was that. @uBlock-user @stephenhawk8054 How about you? Needs Chinese VPN.

**Comment by stephenhawk8054** [comment]
Yeah, I just tried it but couldn't reproduce it either
