### ISSUE TITLE
imgtornado.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1218]
URL(s) where the issue occurs

`http://imgtornado.com/img-57b7a7f5ba224.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up @okiehsch

**Comment by KiLL4FuNK** [comment]
ADS

`http://imgtornado.com/img-5b017525213f3.html`
