### ISSUE TITLE
codethislab.com: breakage

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#12193]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://codethislab.com/games-catalog/`

### Category

breakage

### Describe the issue

with ublock enabled there is no list of game cathegories, just a blank page, without it is working

### Screenshot(s)

<summary>Screenshot(s)</summary>

page with ublock enabled:
![grafik](https://user-images.githubusercontent.com/45161625/158015754-33488eb7-e3df-4876-ad12-e4458f68acc7.png)

i suspect this as wrongly blocked:

![grafik](https://user-images.githubusercontent.com/45161625/158015796-ab375052-9a5c-436c-9421-5ab36b484b61.png)

like 

​https://showcase.codethislab.com/banners/games_catalog/casino_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/seasonal_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/racing_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/board_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/logic_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/card_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/sport_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/arcade_puzzle_games.jpg
12:12:23​||com/banners/$image,domain=~pingdom.com|~thetvdb.com|~tooltrucks.com​--​codethislab.com​1​image​https://showcase.codethislab.com/banners/games_catalog/multiplayer_games.jpg

this is the page with ublock disabled:

![grafik](https://user-images.githubusercontent.com/45161625/158015840-8c57fc24-0be4-4aef-ab92-c5d7c90a9f07.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 82313
  cosmetic: 44820
  scriptlet: 16447
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30803-28, 1d.13h
    ublock-badware: 3971-3, 1d.12h.59m
    ublock-privacy: 204-0, 1d.12h.58m
    ublock-abuse: 72-0, 1d.12h.57m
    ublock-unbreak: 1736-0, 1d.12h.55m
    easylist: 64500-220, 1d.12h.54m
    easyprivacy: 26664-148, 1d.12h.53m
    urlhaus-1: 8437-0, 20h.51m
    plowe-0: 3673-807, 11d.23h.38m
    DEU-0: 5532-28, 20h.52m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6317 ms (selfie)
  maxAssetCacheWait: 3957 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    codethislab.com: 9
    google-analytics.com: 1
```
</details>

**Comment by nanderer** [comment]
lookes like this fixes it:

```
! 2022-03-12 https://codethislab.com
@@||showcase.codethislab.com/banners/*$image,1p


```

**Comment by mapx-** [comment]
EL issue @ryanbr
