### ISSUE TITLE
hotimage.uk [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1219]
URL(s) where the issue occurs

`https://www.hotimage.uk//img-55d30890b7595.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
> Warn with "NSFW" where applicable.

**Comment by nimasaj** [comment]
```
hotimage.uk##script:inject(abort-current-inline-script.js, ad_idzone)
www.hotimage.uk##center > center
www.hotimage.uk###container > center
www.hotimage.uk##body > center > div:nth-of-type(2)
www.hotimage.uk##body > center > div:nth-of-type(1)
www.hotimage.uk##center:nth-of-type(2)
```
