### ISSUE TITLE
ctbl.me [annoyance]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#12190]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ctbl.me/7kynKP`

### Describe the issue

Site requires you to "sub" to a random youtube channel before letting you continue. Possible to bypass or does it require a scriptlet?

### uBlock Origin version

1.41.8

### Browser name and version

Chrome v99

### Settings

default

**Comment by MasterKia** [comment]
Check if https://fastforward.team/install helps.

**Comment by MasterKia** [comment]
Check if the [FastForward ](https://fastforward.team/install) extension helps.

**Comment by MasterKia** [comment]
Check if the **FastForward** extension helps.
Install: https://fastforward.team/install
Github: https://github.com/FastForwardTeam/FastForward

**Comment by dumbusernameidk** [comment]
don't think that works. going to assume this would require a scriptlet seeing as the `can't fix` label is on here.

**Comment by PerfectSalad** [comment]
It doesn't check wether or not you actually subscribe -- I think, are you aware of that @dumbusernameidk ?
