### ISSUE TITLE
JS for Cloudflare Apps blocked

### ISSUE THREAD

**Issue by chanrycz** [uBlockOrigin/uAssets#12196]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://chanrycz.com`

### Describe the issue

uBO is blocking the JS file for Cloudflare Apps (`https://chanrycz.com/cdn-cgi/apps/head/8WAimv9AMd_Dr4sbuk_ihglyivg.js`) on my website.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 78976
  cosmetic: 40293
  scriptlet: 16388
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30802-105, never
    ublock-badware: 3989-3, never
    ublock-privacy: 202-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1727-0, never
    easylist: 62254-99, never
    easyprivacy: 26549-27, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-820, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1408 ms
  maxAssetCacheWait: 9 ms
```
</details>

**Comment by mapx-** [comment]
Describe what's broken on that site, how to reproduce

**Comment by chanrycz** [comment]
I'm using Cloudflare Apps to add HTML in order to add Statuspage Embed (and other JS such as blocking IE browsers) to all my of pages on the domain. uBO is blocking the JS for Cloudflare Apps so the embed will not be able to show.


Steps to show embed is blocked:
1. First go to `https://chanrycz.com` with uBO enabled
2. Run `statusEmbedTest()` in the console - function is not defined
3. Disable uBO and refresh the page
4. Run `statusEmbedTest()` again in the console - embed shows up with test message

**Comment by mapx-** [comment]
`@@||chanrycz.com/cdn-cgi/apps/head/*.js|$script,1p`

EP issue @ryanbr
