### ISSUE TITLE
fulptube.org: Badware risk

### ISSUE THREAD

**Issue by MDMCK10** [uBlockOrigin/uAssets#12194]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

fulptube.org

### Describe the issue

Infected site not on Badware risks list
https://urlhaus.abuse.ch/url/2090811/

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0

### Settings

N/A

**Comment by jkrosado** [comment]
Lmfao
