### ISSUE TITLE
imgrock.info [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1220]
URL(s) where the issue occurs

`http://imgrock.info/HSiQJWk5R9Fh9iDy2Kz7l7Q5NO4nsH8i2g.php`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
I think it's already added to EasyList

**Comment by okiehsch** [comment]
Link is dead, I used `http://imgrock.info/MBXHjk5hhtm5jllI8HzMHSEWUboTRvDAbw.php` to test.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://imgrock.pw/KcYRp4z64igg2GaThqemj08hCq8PhWYvLQ.php`

**Comment by redwra** [comment]
Not working again

`https://imgrock.pw/-ssV5Ww0BjrUnEzl2QCgT3MXmChqTaucSg.php`

**Comment by okiehsch** [comment]
Your example link is dead.

**Comment by mapx-** [comment]
example:
`https://imgrock.pw/1isfFQ3v1G-n21HLazur8jUAmh-vhBjExg.php`

**Comment by okiehsch** [comment]
Hm, I get the same "image not found" message with that link, even if I disable uBO.
I will try to find a working link.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c856b033a1d6e4d571532c8e4c3689ce89628ade
Fixed.
