### ISSUE TITLE
[nsfw] hentaila.com: popups

### ISSUE THREAD

**Issue by CamiloGames** [uBlockOrigin/uAssets#12206]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hentaila.com/ver/overflow-3`

### Category

popups

### Describe the issue

se abren muchas pestañas de anuncios

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82819
  cosmetic: 46009
  scriptlet: 16681
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    easylist: 64457-10, 2d.19h.31m
    easyprivacy: 26663-121, 2d.19h.30m
    plowe-0: 3674-805, 6d.22h.57m
    spa-0: 3813-30, 26m
    spa-1: 4258-166, 2d.19h.26m
    ublock-abuse: 72-0, 2d.19h.29m
    ublock-badware: 3967-85, 2d.19h.23m
    ublock-filters: 30237-210, 2d.19h.27m
    ublock-privacy: 202-2, 2d.19h.25m
    ublock-unbreak: 1722-40, 2d.19h.24m
    urlhaus-1: 8064-0, 27m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 18003 ms (selfie)
  maxAssetCacheWait: 1367 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    addthis.com: 1
    adoptexplorationanguish.com: 1
    disqus.com: 4
    exoclick.com: 1
    googletagmanager.com: 1
    hentaila.ml: 1
    joedisarmament.com: 1
    narrative.io: 1
    pippio.com: 1
    realsrv.com: 3
    rezync.com: 1
    rlcdn.com: 1
    viglink.com: 2
    yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
server Fembed => already fixed
