### ISSUE TITLE
CSP filter policy

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#1221]
### Describe the issue

A non-whitelisted domain appears in the popup UI after opening dev-tools with a CSP policy filter.

### Steps to Reproduce

Add `cbr.com^$csp=default-src 'self' 'unsafe-inline' www.facebook.com *.cbrimages.com fonts.googleapis.com fonts.gstatic.com platform.twitter.com *.twimg.com platform.instagram.com *.imgur.com` to My Filters

Browse to https://www.cbr.com/

Open popup UI and notice `indexww.com` doesn't appear which is expected.

Open and close devtools.

Open the popupUI and `indexww.com` appears even though it's not whitelisted with the CSP filter policy.

### Versions

- Browser/version: Chrome 65
- uBlock Origin version: 1.14.23.15

**Comment by uBlock-user** [comment]
@gorhill I accidently opened it here, if you can move it to uBlock, then do so.

**Comment by gorhill** [comment]
File the issue with the browser devs please, this is not a uBO issue: that the browser decides to not enforce the current CSP when using browser dev tools is out of control of uBO.

**Comment by uBlock-user** [comment]
It doesn't happen everytime with `default-src` but only when the type is 'other', but yeah it does look like Chrome is causing it.

**Comment by uBlock-user** [comment]
Fixed in v66.

**Comment by uBlock-user** [comment]
Filed -- https://bugs.chromium.org/p/chromium/issues/detail?id=979745
