### ISSUE TITLE
shortx.net: detection

### ISSUE THREAD

**Issue by iam23** [uBlockOrigin/uAssets#12210]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shortx.net/yftu0`

### Category

detection

### Describe the issue

detect ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ibb.co/w7VWXnK
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 103682
  cosmetic: 48059
  scriptlet: 38819
  html: 630
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 16h.30m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 26851-47, 16h.29m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter.txt: 24-0, 4d.13h.55m
    adguard-spyware: 26501-903, 3d.17h.4m
    ublock-annoyances: 4365-4, 1d.21h.11m
    IDN-0: 8862-2, 1d.21h.10m
    adguard-spyware-url: 499-3, 3d.17h.5m
    block-lan: 44-0, 5d.18h.11m
  default: 
    user-filters: 21-1, never
    ublock-filters: 30786-3178, 4d.1h.9m
    ublock-badware: 3971-4, 12h.28m
    ublock-privacy: 204-1, 12h.27m
    ublock-abuse: 72-0, 12h.26m
    ublock-unbreak: 1736-0, 12h.25m
    easylist: 64589-668, 12h.24m
    easyprivacy: 26669-10781, 12h.23m
    urlhaus-1: 8074-0, 16h.31m
    plowe-0: 3673-0, 12d.4h.18m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 227 ms (selfie)
  maxAssetCacheWait: 1372 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    iclickcdn.com: 1
    omoonsih.net: 2
    vooculok.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
```
/ads$image,1p,redirect-rule=2x2.png
shortx.net##+js(set, blurred, false)
@@||shortx.net^$ghide
||vooculok.com^
```

**Comment by PerfectSalad** [comment]
for collaborators / hwoever may want to try to fix this : `shortx.net##+js(aeld, load)` => broken countdown

**Comment by ghajini** [comment]
try this

```
||vooculok.com^
shortx.net##+js(aeld, load, nextFunction)
shortx.net##+js(set, blurred, false)
```
