### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by IgnatMiller** [uBlockOrigin/uAssets#12212]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rezka.ag/`

### Category

ads

### Describe the issue

For some time (a couple weeks) ads before each video are back. No custom filters, forcing an update of filter lists didn't help also. Brave & Windows 10 (up to date).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screen 2022 03 13 11 47 52](https://user-images.githubusercontent.com/54756964/158052101-f5b06b46-8261-4825-bd23-5d9c62c2ffe0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.4
Chromium: 98
filterset (summary): 
  network: 80098
  cosmetic: 41411
  scriptlet: 16484
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64423-10, 3d.15h.20m
    easyprivacy: 26658-121, 3d.15h.16m
    plowe-0: 3673-805, 10d.15h.38m
    ublock-abuse: 72-0, 3d.15h.14m
    ublock-badware: 3951-85, 3d.15h.17m
    ublock-filters: 30226-153, 3d.15h.19m
    ublock-privacy: 200-2, 3d.15h.15m
    ublock-unbreak: 1720-39, 3d.15h.21m
    urlhaus-1: 8437-0, 15h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2590 ms (selfie)
  maxAssetCacheWait: 902 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add `RUS: RU AdList`  list

**Comment by IgnatMiller** [comment]
Thank you for a tip, but it didn't help as well.

**Comment by mapx-** [comment]
I see the video ads only if I disable the russian list, so for me it works consistently.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11415#issuecomment-1066056574
