### ISSUE TITLE
Adblock bypassed: https://0day.kiev.ua/

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#1222]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

    https://0day.kiev.ua/

### Describe the issue
Ads still visible
### Versions

- Browser/version: latest
- uBlock Origin version: latest

**Comment by gorhill** [comment]
> Browser/version: latest

Latest _what_?

**Comment by uBlock-user** [comment]
```
kiev.ua##script:inject(abort-current-inline-script.js, String.fromCharCode, /[0-9a-f]{40}..$/)
kiev.ua##script:inject(set-constant.js, _mgq, undefined)
```

**Comment by gorhill** [comment]
`kiev.ua` is a public suffix, this should not be used in a filter, the base domain name must be used.

Anyways, seems to work in Chromium -- not sure the first filter is needed. In Firefox, I get an issue with the dev build, the encoding is messed up. I need to investigate this.

**Comment by gorhill** [comment]
I will just add (I don't think the other does anything):

    0day.kiev.ua##script:inject(set-constant.js, _mgq, undefined)

The messed up encoding on Firefox happens only to the ads which are being blocked, the rest seems fine (OP could confirm).

**Comment by uBlock-user** [comment]
> not sure the first filter is really needed

It is needed if you're blocking `piguiqproxy.com` by default. If you allow it or whitelist it then you won't need the first filter.

**Comment by gorhill** [comment]
I see. However this won't work with Chromium, it's unable to win the scriptlet-injection race. However it does work with Firefox and uBO dev build, confirming the fix to #3069.

**Comment by uBlock-user** [comment]
> this won't work with Chromium

Worked for me, I'm on Chromium 65 and wins the race too. I posted only after I tested on myself first.

**Comment by uBlock-user** [comment]
These are the pages I tested it on and it won the race everytime on Chromium 65

https://0day.kiev.ua/modules.php?name=News&topic_id=9
https://0day.kiev.ua/modules.php?name=News&topic_id=2
https://0day.kiev.ua/modules.php?name=News&topic_id=21
https://0day.kiev.ua/modules.php?name=News&topic_id=38
https://0day.kiev.ua/modules.php?name=News&topic_id=10
https://0day.kiev.ua/modules.php?name=News&topic_id=40
https://0day.kiev.ua/modules.php?name=News&topic_id=23
https://0day.kiev.ua/modules.php?name=News&topic_id=19

**Comment by gorhill** [comment]
It should definitely not work on Chromium, it does not on my side, as expected. Using _only_ uBO with default settings.

**Comment by uBlock-user** [comment]
I did, the page doesn't break.

**Comment by nimasaj** [comment]
still getting ad after applying rules,
```
https://cdn.pbrd.co/images/H1ZTsMQ.png
https://cdn.pbrd.co/images/H1ZV8Bt.png

```

**Comment by ReyCobin** [comment]
Does not work

**Comment by gorhill** [comment]
Can't reproduce. I will let somebody deal with the case here.

**Comment by mapx-** [comment]
@ReyCobin  upload a screenshot with what ads still on page  and eventually specific page link with ads

**Comment by nimasaj** [comment]
Restarted Chrome and now those ads are blocked here.

**Comment by uBlock-user** [comment]
Yeah that must have been a cache issue. Reload the page by bypassing the cache.

**Comment by ReyCobin** [comment]
Restarted my PC, confirmed working now.
