### ISSUE TITLE
carbon.now.sh: breakage

### ISSUE THREAD

**Issue by adriaanvanrossum** [uBlockOrigin/uAssets#12233]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=one-light&wt=none&l=javascript&width=503&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=0px&ph=0px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=const%2520audio%2520%253D%2520document.querySelector%28%27audio%27%29%253B%250A%250Aaudio.addEventListener%28%27play%27%252C%2520%28event%29%2520%253D%253E%2520%257B%250A%2520%2520if%2520%28window.sa_event%29%2520sa_event%28%27audio_play%27%29%253B%250A%257D%29%253B%250A`

### Category

breakage

### Describe the issue

No export buttons present.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

with blocker enabled:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1079135/158159496-7fcde4c8-672c-46e7-9004-da2443556f1d.png">

without:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/1079135/158159527-23519206-325b-49fc-918f-24929f6d2702.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 86831
  cosmetic: 121499
  scriptlet: 19216
  html: 625
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50741-3639, 1d.20h.29m
    adguard-social: 16132-18, 1d.20h.26m
    fanboy-thirdparty_social: 69-0, 6d.1h.32m
    fanboy-cookiemonster: 24101-36, 6d.1h.31m
    NLD-0: 2105-29, 2d.2h.15m
  default: 
    user-filters: 5-0, never
    ublock-filters: 30805-83, 1d.20h.34m
    ublock-badware: 3976-3, 1d.20h.35m
    ublock-privacy: 204-0, 1d.20h.33m
    ublock-abuse: 72-0, 1d.20h.32m
    ublock-unbreak: 1736-27, 1d.20h.30m
    easylist: 64589-605, 1d.20h.28m
    easyprivacy: 26669-100, 1d.20h.27m
    urlhaus-1: 8437-0, 1d.16m
    plowe-0: 3671-445, 20h.15m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 72 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1370 ms (selfie)
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    carbonads.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add
`carbon.now.sh#@#.share-buttons`

@Yuki2718 
`AdGuard Social Media`

@ryanbr => `fanboy's annoyances`

**Comment by adriaanvanrossum** [comment]
Wow @mapx-, you're fast!
