### ISSUE TITLE
bing.com (maps) : breakage

### ISSUE THREAD

**Issue by DeFaLT-dj** [uBlockOrigin/uAssets#12247]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bing.com/maps?cp=40.692617%7E-73.9909&lvl=12.4`

### Category

breakage

### Describe the issue

I usually perfectly used uBlock Origin and Bing maps together but lately it just opens blank page when I visited it. I tried turning of uBlock and the page loaded as normal. Then I tested turning off all filter lists one by one to find out which list causes this. And apparently "uBlock filers" list causes the issue. After I turn it of the site loaded properly again. Now I tried to look into the block list to find out which element exactly causes this but couldn't really find out since I am not an expert in this stuff. I also tried adding Bing maps to Trusted sites list but it didn't actually work. Adding "bing.com" solves the issue but "bing.com/maps" doesn't. I would like to only allow bing maps if it will solve it instead of allowing entire Bing domain

Now I found out something. When I go to bing.com/maps, it doesn't properly and when click all the extra files after /maps it loads properly. But trying to refresh the page etc. still causes the same problem. Even though I just write bing.com/maps (not choosing the saved option with complete URL) it still doesn't loads until I clear the extra stuff. For example, if I type bing.com/maps, the URL become https://www.bing.com/maps?cp=40.692617%7E-73.9909&lvl=12.4 after it tries to load the page. But it doesn't load up. clearing part after /maps (?cp=40.692617%7E-73.9909&lvl=12.4) makes it load properly until you try to refresh the page. 

So apparently going to maps.bing.com loads page properly but refreshing it still causes it to go blank. I attached a screenshot to show how it looks like when it goes blank.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/64617514/158262707-70e1dee0-4ba6-4752-99ef-402902191717.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 90301
  cosmetic: 98782
  scriptlet: 19792
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 63842-173, 7m
    fanboy-social: 23209-23209, 7m
    ublock-annoyances: 4365-123, 7m
  default: 
    user-filters: 114-5, never
    easylist: 64725-10, 6m
    easyprivacy: 26679-121, 6m
    plowe-0: 3671-805, 6m
    ublock-abuse: 72-0, 8m
    ublock-badware: 3972-85, 8m
    ublock-filters: 30304-158, 5m
    ublock-privacy: 200-10, 8m
    ublock-unbreak: 1727-42, 8m
    urlhaus-1: 10893-1, 6m
filterset (user): [array of 115 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8365 ms (selfie)
  maxAssetCacheWait: 513 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    bing.com: 6
```
</details>

**Comment by Procyon-b** [comment]
Can you go to the "Filter lists" tab and uncheck "My filters". Then test again.
What does happen when you open the link in an incognito window?

**Comment by DeFaLT-dj** [comment]
> Can you go to the "Filter lists" tab and uncheck "My filters". Then test again.
> What does happen when you open the link in an incognito window?

I tried that as well when I tested turning off every filter list one by one. It was actually first I tired thinking I blocked something by accident but it didn't change anything.

Result is same in incognito as well

**Comment by mapx-** [comment]
- save your current settings / custom filters
- reset uBO to default settings
- go into dashboard, filter lists tab, click "purge all caches", click "update now"

- disable any other extension in chrome
- test again
