### ISSUE TITLE
terraria.wiki.gg: ads

### ISSUE THREAD

**Issue by RGB773** [uBlockOrigin/uAssets#12246]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://terraria.wiki.gg/wiki/Terraria_Wiki`

### Category

ads

### Describe the issue

Simply put, there are ads on the entire official Terraria Wiki.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/74821032/158263131-2f17b19e-eb06-4d50-88ba-0f9e406cff93.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 97
filterset (summary): 
  network: 80081
  cosmetic: 41463
  scriptlet: 16492
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64583-10, 2d.15h.55m
    easyprivacy: 26666-121, 2d.15h.54m
    plowe-0: 3671-805, 1d.18h.14m
    ublock-abuse: 72-0, 2d.15h.53m
    ublock-badware: 3967-85, 2d.15h.52m
    ublock-filters: 30225-143, 2d.15h.51m
    ublock-privacy: 200-2, 2d.15h.50m
    ublock-unbreak: 1724-39, 2d.15h.49m
    urlhaus-1: 8287-0, 22h.51m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 816 ms (selfie)
  maxAssetCacheWait: 221 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add
`terraria.wiki.gg##[href^="https://store.steampowered.com/app/"]`

@ryanbr

**Comment by CataclystP** [comment]
This is a dirty fix; it does not get rid of the whitespace on pages where the ad sidebar was/is, and leaves the terraria merch ad in tact as its not a steam page.

I'd recommend these as filters instead:
`terraria.wiki.gg##.games-showcase-sidebar`
`terraria.wiki.gg##.header-showcase`
`terraria.wiki.gg##.footer-showcase`

Here's a comparison using https://terraria.wiki.gg/wiki/Forest as reference (the landing page does not have an ad sidebar so it's not a very good reference page)
[@mapx-'s suggested filters (i.imgur.com)](https://i.imgur.com/OftQkFN.jpeg)

[my suggested filters (i.imgur.com)](https://i.imgur.com/o1ERXUv.jpeg)
