### ISSUE TITLE
[nsfw] h-flash.com: breakage

### ISSUE THREAD

**Issue by VL4DST3R** [uBlockOrigin/uAssets#12249]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://h-flash.com/`

### Category

breakage

### Describe the issue

Seemingly on random flashes, either the seekbar, download button or both fail to load at all. Disabling the cosmetic filter seems to fix this, but its obviously not a desired solution. I tried to figure out if something is clashing naming-wise with any filters but i couldn't figure it out, plus the page elements don't do any funky obfuscation, so im not sure how this gets accidentally removed.

(Note about configuration below: i've done as instructed in the checklist in regards to custom lists and purging caches **after** generating the ticket initially, and yes the issue persists.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 78
filterset (summary): 
  network: 153238
  cosmetic: 172432
  scriptlet: 33906
  html: 630
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 1h.8m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 1h.10m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 18d.14h.55m
    https://mirror1.malwaredomains.com/files/immortal_domains.txt: 0-0, never
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.7m
    https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt: 2625-2625, 4d.17h.25m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 0-0, never
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-35, 4d.17h.23m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-0, 4d.17h.24m
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt: 34-0, 4d.17h.22m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-33, 4d.17h.26m
    https://www.fanboy.co.nz/r/fanboy-ultimate.txt: 154525-153816, 1d.17h.44m
    https://www.zoso.ro/pages/rolist.txt: 375-15, 1d.17h.43m
    https://www.zoso.ro/pages/rolist2.txt: 461-7, 1d.17h.46m
    https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt: 0-0, never
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-5, 1d.17h.42m
    https://winhelp2002.mvps.org/hosts.txt: 8730-417, 1h.11m
    adguard-generic: 62406-4949, 3d.23h.24m
    adguard-spyware: 26507-1235, 3d.23h.22m
    adguard-annoyance: 50689-3552, 3d.23h.23m
    [7 lists not shown]: [too many]
  default: 
    user-filters: 197-7, never
    ublock-filters: 30784-115, 3d.23h.20m
    ublock-badware: 3971-3, 3d.23h.19m
    ublock-privacy: 204-0, 3d.23h.18m
    ublock-abuse: 72-0, 3d.23h.17m
    ublock-unbreak: 1733-3, 3d.23h.16m
    easylist: 64455-993, 3d.23h.15m
    easyprivacy: 26664-10983, 3d.23h.14m
    urlhaus-1: 10893-0, 1h.6m
    plowe-0: 3675-1765, 3d.10h.52m
filterset (user): [array of 198 redacted]
trustedset: 
  added: [array of 34 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 4439 ms (selfie)
  maxAssetCacheWait: 1518 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    juicyads.com: 2
    realsrv.com: 1
```
</details>

**Comment by PerfectSalad** [comment]
> * I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists


> * [x]  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

are you sure?

**Comment by mapx-** [comment]
Firefox: 78 ? did you try the last version ?

**Comment by mapx-** [comment]
I added other filters for ads / popunder.

Upload some screenshots showing what's broken.

**Comment by iam-py-test** [comment]
@VL4DST3R the latest version of Firefox is 98.0.1
Please follow [the steps here](https://support.mozilla.org/en-US/kb/update-firefox-latest-release) to update your browser

**Comment by VL4DST3R** [comment]
> I added other filters for ads / popunder.
> 
> Upload some screenshots showing what's broken.
Thanks! Is there a way to find what rule exactly is removing a page element? maybe i could help figure it out when/if it happens again but im not exactly sure how to pinpoint it. Disabling cosmetic filters completely isn't really that specific.

> @VL4DST3R the latest version of Firefox is 98.0.1 Please follow [the steps here](https://support.mozilla.org/en-US/kb/update-firefox-latest-release) to update your browser

Yes, i am aware i am behind version-wise, i'm using a fork of an already ESR firefox (waterfox) but this should have no impact (and never has) on filters and how they work. Once i get home today i'll try on the latest ff just to rule it out.

**Comment by mapx-** [comment]
- open the logger
- reproduce the issue
- go into the logger page and see all cosmetic filters

for disabling such a filter (##.filter  or ###filter ):
add:
`h-flash.com#@#.filter` or `h-flash.com#@##filter`

**Comment by iam-py-test** [comment]
@VL4DST3R I doubt it is the cause, but did you purge your browser cache (Command-Shift-R or Control-Shift-R, or via browser settings) before retesting, because maybe the effects of your custom lists (which you disabled) would have persisted.

**Comment by mapx-** [comment]
> Upload some screenshots showing what's broken.

**Comment by VL4DST3R** [comment]
This should be reopened as not only the issue hasn't been fixed, now popup ads pass through.

**Comment by mapx-** [comment]
test

`@@||h-flash.com^$ghide`

**Comment by VL4DST3R** [comment]
It's hard to say with 100% certainty because as i mentioned before it tends to be inconsistent, but it SEEMS to have sorted the disappearing download button, at least as far as i can tell. Doesn't seem to prevent the popup when you first visit the site and click on something though.

**Comment by VL4DST3R** [comment]
So in regards to the popup, can something be done?

**Comment by mapx-** [comment]
I added a filter for the popup, did you update uBO lists ?

**Comment by VL4DST3R** [comment]
Iiii did not, will test now and report back. So i shall remove the one added manually above, right?

**Comment by Daxy7** [comment]
After removing new banner ads the download button is blocked. It was easy to find in a `pack1.js` file and make undefined:
```
||h-flash.com/data/image/mcs/*.jpg$image
||imobileporn.com^$all
h-flash.com##+js(set, adblocked, undefined)
```
