### ISSUE TITLE
p637.signalshares.com: breakage

### ISSUE THREAD

**Issue by beachsnap** [uBlockOrigin/uAssets#12240]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://p637.signalshares.com/welcome`

### Category

breakage

### Describe the issue

Hi,
Sorry for the extra work, when I attempting to access :-  https://p637.signalshares.com/welcome in Firefox with uBlock Origin actvated just goes to the site and nothing is downloaded.  Switch uBO off and the site loads.  I hope you can help please.  I am willing help you in testing any "fix(es)".  
Many thanks in advance.
beachsnap :-)  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 82451
  cosmetic: 41435
  scriptlet: 16450
  html: 623
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30800-28, 3d.17h.12m
    ublock-badware: 3960-3, 3d.17h.11m
    ublock-privacy: 204-0, 3d.17h.10m
    ublock-abuse: 72-0, 3d.17h.9m
    ublock-unbreak: 1736-0, 3d.17h.8m
    easylist: 64502-604, 3d.17h.7m
    easyprivacy: 26664-570, 3d.17h.6m
    urlhaus-1: 10713-0, 1h.6m
    plowe-0: 3671-2, 5h.7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 933 ms (selfie)
  maxAssetCacheWait: 691 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    signalshares.com: 2
    newrelic.com: 1
```
</details>

**Comment by okiehsch** [comment]
`@@||signalshares.com/webtrends.min.js$script,1p`
@ryanbr

**Comment by beachsnap** [comment]
Morning
Many thanks did a uBO cache purge and update, I can now access the site.
:-) 
Regards
beachsnap
