### ISSUE TITLE
Mixpanel dashboards blocked even after strict blocking disabled

### ISSUE THREAD

**Issue by matthathornmp** [uBlockOrigin/uAssets#12244]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.mixpanel.com/project/2054816/view/202279/app/dashboards`

### Describe the issue

uBlock Origin initially blocks access to www.mixpanel.com due to a `||mixpanel.com^` filter rule from Peter Lowe's Ad tracking and server list. (It shows the screen in the attached screenshot.) I can get around this initial block by telling uBlock Origin to disable strict blocking for mixpanel.com permanently. However, even if I do that, after signing in to Mixpanel, Mixpanel dashboards do not load when uBlock Origin extension is on.

### Screenshot(s)

![uBO_Error_Screen](https://user-images.githubusercontent.com/97570912/158255728-e6a4cc6a-9a6f-4017-9e1c-552c9776e888.jpg)

### Notes

I used the uBlock Origin console to debug, and I found that uBlock Origin is blocking a number of requests for Mixpanel resources due to the same `||mixpanel.com^` filter rule from Peter Lowe's Ad tracking and server list. If I add `@@||mixpanel.com$domain=mixpanel.com` to My Filters, everything loads properly.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 82772
  cosmetic: 41539
  scriptlet: 16543
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64683-10, 33m
    easyprivacy: 26679-121, 33m
    plowe-0: 3671-805, 33m
    ublock-abuse: 72-0, 33m
    ublock-badware: 3972-85, 33m
    ublock-filters: 30308-134, 33m
    ublock-privacy: 200-2, 33m
    ublock-unbreak: 1727-39, 33m
    urlhaus-1: 10893-1, 33m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5191 ms
  maxAssetCacheWait: 195 ms
```
</details>

**Comment by PerfectSalad** [comment]
`@@||mixpanel.com^$doc`
