### ISSUE TITLE
Reddit search box is blocked on all pages

### ISSUE THREAD

**Issue by clamtastic** [uBlockOrigin/uAssets#12241]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

reddit.com

### Describe the issue

The search boxes on all Reddit pages are blocked.

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98

### Settings

none

### Notes

When I purge the cache and refresh a Reddit page the search box appears for an instant then vanishes again.

The search boxes appear normally in troubleshooter mode.

**Comment by mapx-** [comment]
go into support tab and paste here `Troubleshooting Information`

**Comment by clamtastic** [comment]
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 82769
  cosmetic: 41567
  scriptlet: 16504
  html: 626
listset (total-discarded, last updated): 
  default: 
    user-filters: 32-0, never
    ublock-filters: 30874-29, 2h.7m
    ublock-badware: 3976-3, 2h.7m
    ublock-privacy: 204-0, 2h.7m
    ublock-abuse: 72-0, 2h.7m
    ublock-unbreak: 1737-0, 2h.7m
    easylist: 64682-592, 2h.7m
    easyprivacy: 26679-570, 2h.7m
    plowe-0: 3671-2, 2h.7m
    urlhaus-1: 10893-1, 2h.7m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  uiTheme: dark
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 500 ms (selfie)
  maxAssetCacheWait: 200 ms

**Comment by mapx-** [comment]
- Disable uBO, refresh the reddit page and post here a screenshot with that search box
- post an example page

**Comment by clamtastic** [comment]
Reddit with search box,

https://i.postimg.cc/0jHRtcm9/reddit-with-search-box.jpg

Reddit without search box,

https://i.postimg.cc/hv4Q8P8H/reddit-without-search-box.jpg

**Comment by clamtastic** [comment]
Resetting it to default settings restored the search box without doing
anything else.

I think that's fixed it.

I don't know what I might have done that affected it.

**Comment by mapx-** [comment]
maybe one of your custom filters (from "my filters")

**Comment by clamtastic** [comment]
There were some things in there but I haven't added in anything new in
quite a while.

It happened just after I'd updated to Firefox 98 so it had to be some issue
something had with that.
