### ISSUE TITLE
Ads Missed in Bing Search Results

### ISSUE THREAD

**Issue by jputting** [uBlockOrigin/uAssets#12255]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bing.com/search?q=mobile+phones+plans`

### Describe the issue

Ads inserted by Bing are appearing at the top and bottom of my search results.

They are clearly tagged as ads
<img width="1024" alt="Screen Shot 2022-03-15 at 3 03 02 pm" src="https://user-images.githubusercontent.com/10370101/158307308-4597b0df-791d-49b8-ba69-c81d668543f9.png">
.

### uBlock Origin version

1.41.8

### Browser name and version

Brave: Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (x86_64)

### Settings

NO CHANGES

I use uBlock Origin in its Default configuration

### Notes

Adblock Plus gets rid of those ads, it uses its own base filter list and also uses the ABP Anti-Circumvention List.

I have discovered it is the ABP Anti-Circumvention List which gets rid of those ads.

The ABP Anti-Circumvention List also gets rid of those ads when added to Adguard.

**Comment by mapx-** [comment]
I see no blocked item in your uBO icon

- reset uBO to default settings
- go into dashboard, filter lists tab, click "purge all caches", click "update now"

**Comment by jputting** [comment]
Hi, 

I have done exactly what you have requested.

The results are the same, unfortunately the ads are still there.

Please Note:
In my ongoing battle to defeat those ads only 2 adblockers have been effective, Adblock Plus & Adguard.

When the veteran Adblock Plus removed those Search Ads, I thoroughly checked all the settings and made sure "Allow Acceptable Ads" was disabled.
I then looked at the default Filter Lists it was using:
Easy List
ABP Anti-Circumvention List

I knew that Easy List was not blocking the Bing Search Results ads as I had subscribed to the Adguard Base Filter+Easy List when using Adguard and the Bing Search Result Ads were present.

In light of the fact that Adblock Plus was also using the ABP Anti-Circumvention Filter List, I added it to Adguard and returned to Bing and searched for "mobile phones" or "mobile phones plans" and the Bing Search Result Ads were once again 100% totally removed.

The problem is that ABP Anti-Circumvention Filter List is not compatible uBlock Origin because of the formatting/syntax of its Filter Rules.

I have indeed tried subscribing to that Filter List via adding a Custom Filter List and uBlock Origin fails to import any Filter Rules at all. uBlock Origin simply states "0 used out of 0" 

I used the exact same Filter List URL that I used to subscribe to that Filter List with Adguard.

**Comment by mapx-** [comment]
After refreshing uBO installation, do you see in uBO icon the number of blocked ads ?

**Comment by jputting** [comment]
Sorry it was my mistake as I checked the settings and had the "Show Blocked Requests on the Icon" Unchecked.

It now shows that 13 requests are blocked, but the ads are still there.

**Comment by mapx-** [comment]
What if you log off from your microsoft account ?

**Comment by jputting** [comment]
Still the same result unfortunately.
Still ads present and same number requests blocked.

**Comment by mapx-** [comment]
The problem is we cannot reproduce your issue.
Did you try not only resetting uBO but remove and then reinstall it ?

**Comment by jputting** [comment]
Yes I have done that.

I have also completely uninstalled Brave and reinstalled it and left it in the default state with ZERO Extensions and No changes to any part of Brave.

I then installed uBlock Origin and left it in its default configuration and made sure the Filter Lists were up to date.

I went to Bing and the Search Ads were present.

I have also tried uBlock Origin installed in fresh virginal untouched installations of Firefox, Chrome and Safari.

This has been a very tough ad issue to resolve as many people have trouble reproducing those ads at all, so I don't understand why I am getting them.

I have taken the precaution of thoroughly scanning my macos with Avira Anti-Virus and it reports that there is no virus, spyware or anything wrong.

I don't wanted to be forced into using the less capable Adguard or Adblock Plus adblockers.

But unfortunately uBlock Origin is failing to block those ads and I can NOT get it to use the 1 and only Filter List which effectively removes those ads.

**Comment by mapx-** [comment]
If I disable uBO for bing => I get the ads. So, uBO does its job very well.

**Comment by jputting** [comment]
If you get the ads when you disable uBlock Origin, then you may able to take a deeper look and discover the method Bing are using to insert them.

When Adguard is using the ABP Anti-Circumvention List to remove those ads, I opened the Adguard Filtering Log the results show that only 2 Filter Rules were active they were:

[bing.com#?#li[class=“b_algo”]:-abp-has](http://bing.com/#?#li%5Bclass=%22b_algo%22%5D:-abp-has)(> h2 + div[class=“b_caption”] > p[class])

[bing.com#?##b_results](http://bing.com/#?##b_results) > li:has(> h2 + .b_caption > div.b_attribution:not([u]) + p[class])

But because of their format/syntax they cant be used in uBlock Origin.

**Comment by mapx-** [comment]
Finally I'm able to get the ads.

As I already told you on forum, the filters above are translated very well by uBO.

So, add them in uBO format, are working for me:

```
bing.com##li[class="b_algo"]:has(> h2 + div[class="b_caption"] > p[class])
bing.com###b_results > li:has(> h2 + .b_caption > div.b_attribution:not([u]) + p[class])
```
