### ISSUE TITLE
aligsmlab anti-adb

### ISSUE THREAD

**Issue by AnnAngela** [uBlockOrigin/uAssets#12251]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.aligsmlab.com/2022/02/TFT-MTP-Bypass-V1.0-Samsung-FRP-Tool.html`

### Describe the issue

When uBlock enabled, there is a popup requiring user to disable adblock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9762652/158293832-c982b25b-f1dc-433b-9744-e2433be8c5a3.png)

### uBlock Origin version

1.41.8

### Browser name and version

Microsoft Edge 99.0.1150.39

### Settings

_None_

**Comment by mapx-** [comment]
Go into edge settings (tracking prevention) and switch to Balanced, I guess you are now using Strict.

![image](https://user-images.githubusercontent.com/10303732/158322020-e0416351-0688-485a-87f8-17b86d3f5304.png)

**Comment by AnnAngela** [comment]
@mapx- is there any way to remove the popup without changing the tracking prevention setting?

**Comment by mapx-** [comment]
Disable completely uBO, keep the strict settings and you'll still get the anti adb msg, so nothing to do.

**Comment by PerfectSalad** [comment]
@AnnAngela Microsoft Edge's tracking protection can be disabled on a per-site basis.
