### ISSUE TITLE
www.gsmware.com anti-adb

### ISSUE THREAD

**Issue by AnnAngela** [uBlockOrigin/uAssets#12250]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gsmware.com/2021/04/mct-ofp-extractor-tool.html`

### Describe the issue

When uBlock enabled, the download button in the page is removed, and there is a notice requiring user to disable adb extions.

### Screenshot(s)

uBlock deactivated:
![image](https://user-images.githubusercontent.com/9762652/158292328-078d7704-cdd4-4adc-b0d3-962a2e7f3469.png)

uBlock activated:
![image](https://user-images.githubusercontent.com/9762652/158292351-e4d74a5a-1fce-4389-9b3b-6cfb12cd068b.png)

### uBlock Origin version

1.41.8

### Browser name and version

Microsoft Edge 99.0.1150.39

### Settings

_None_

**Comment by PerfectSalad** [comment]
Does Microsoft Edge have a built-in ad blocker? And if yes, did you have it enabled?

**Comment by PerfectSalad** [comment]
`||countapi.xyz^$third-party` @ryanbr

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||gsmware.com^$ghide
```

**Comment by AnnAngela** [comment]
> ||countapi.xyz^$third-party

This one works for me.

**Comment by AnnAngela** [comment]
> Try this filter:
> 
> ```
> @@||gsmware.com^$ghide
> ```

This one works for me.

**Comment by stephenhawk8054** [comment]
I think it's blocked by `.adsbygoogle`

```
gsmware.com#@#.adsbygoogle
```

@ryanbr

**Comment by mapx-** [comment]
@stephenhawk8054 easylist cannot add filters for anti adblocking (for ... ABP legal reasons)

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 easylist cannot add filters for anti adblocking (for ... ABP legal reasons)

Oh I see, I thought it's just the button is hidden by that class, not really anti-adblock.

**Comment by pgl** [comment]
@PerfectSalad Why did you tag me?

**Comment by Yuki2718** [comment]
> 
> I thought `countapi.xyz` served tracking on the URL give in this GH issue.

This simply retrieves Views and Downloads counts on the page.

**Comment by PerfectSalad** [comment]
> This simply retrieves Views and Downloads counts on the page.

isn't that tracking?
