### ISSUE TITLE
flixtor.video: popups

### ISSUE THREAD

**Issue by uizt** [uBlockOrigin/uAssets#12257]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://flixtor.video/home`

getting popups like this one:
`https://www.gearbest.com/promotion-bestseller-special-1308.html?lkid=45687009&cid=527509212977443417`

### Category

popups

### Describe the issue

opens when using `https://flixtor.video/home`

after a minute or so without mouse/trackpad movement, hidden mask covers website and video controls no longer show up when mouse is moved. when a click is attempted, malicious advertising opens automatically in new tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 81429
  cosmetic: 41688
  scriptlet: 16504
  html: 626
listset (total-discarded, last updated): 
  default: 
    user-filters: 314-35, never
    ublock-filters: 30883-29, 10h.40m
    ublock-badware: 3976-3, 10h.36m
    ublock-privacy: 204-0, 10h.39m
    ublock-abuse: 72-0, 10h.38m
    ublock-unbreak: 1738-0, 10h.37m
    easylist: 64589-590, 2d.11h.52m
    easyprivacy: 26669-570, 2d.11h.53m
    urlhaus-1: 9515-1, 1h.15m
    plowe-0: 3674-2, 5d.8h.13m
filterset (user): [array of 315 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1830 ms (selfie)
  maxAssetCacheWait: 351 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    gearbest.com: 2
    1talking.net: 1
    googletagmanager.com: 1
    logsss.com: 1
```
</details>

**Comment by mapx-** [comment]
What server ?

You have a lot of custom filters. Try disabling "my filters" and test again
