### ISSUE TITLE
newsextv.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1225]
URL(s) where the issue occurs

`http://www.newsextv.com/4704672/Amateur_wife_fucking_black_monster_cock.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
what's the normal behaviour of the page ? it's normal to redirect to anyporn ?

**Comment by xDarkARG** [comment]
It only takes you to another website the first time afterwards no more

**Comment by xDarkARG** [comment]
It only takes you to another website the first time afterwards no more @mapx-

**Comment by KiLL4FuNK** [comment]
the video looks black

`https://es.anyporn.com/402773/`
