### ISSUE TITLE
White blocks on zerohedge.com

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#12263]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.zerohedge.com/geopolitical/taiwan-will-defend-differently-ukraine-event-chinese-invasion-expert`

### Describe the issue

On zerohedge.com are a lot of white places because of ads blocked. 

I propose `zerohedge.com##[class*="AdvertisingSlot_placement"]`

### Screenshot(s)

<details><summary> screenshot 1</summary> 

![image](https://user-images.githubusercontent.com/81161435/158380595-c6d3df1d-f9e6-4e2e-8605-b4b3063f565a.png)

</details>

<details><summary> screenshot 2</summary> 

![image](https://user-images.githubusercontent.com/81161435/158380685-d886aba8-69cf-44a5-9c6a-c64403f307bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 67357
  cosmetic: 43541
  scriptlet: 16619
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2995-10, 5h.30m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1972-0, 5h.30m
  default: 
    user-filters: 213-0, never
    ublock-filters: 30304-91, 5h.25m
    ublock-unbreak: 1727-10, 5h.24m
    easylist: 64152-145, 5h.23m
    easyprivacy: 26683-192, 5h.22m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  uiAccentCustom: true
  uiAccentCustom0: #312a65
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 21112 ms
  maxAssetCacheWait: 1927 ms
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
