### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by NickEckardt** [uBlockOrigin/uAssets#12268]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/s?k=spotlight+led&crid=QCD70DE339GH&sprefix=%2Caps%2C115&ref=nb_sb_ss_recent_1_0_recent`

### Category

ads

### Describe the issue

Sponsored items show up in Amazon on Android Firefox. Switching to "Desktop site" does not fix this.

Works fine on a real desktop. I went through the above checklist twice but it's still possible I miconfigured something.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220315-082714_Firefox](https://user-images.githubusercontent.com/15786050/158412629-44808443-3616-4824-ab2b-d7a283809046.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 83951
  cosmetic: 23328
  scriptlet: 16471
  html: 626
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 30870-262, 2d.23h.13m
    ublock-badware: 3976-3, 2d.23h.12m
    ublock-privacy: 204-1, 2d.19h.32m
    ublock-abuse: 72-0, 2d.23h.16m
    ublock-unbreak: 1742-0, 2d.20h.15m
    adguard-mobile: 7328-169, 2d.23h.14m
    easylist: 64635-24339, 2d.42m
    easyprivacy: 26669-578, 2d.23h.15m
    urlhaus-1: 10713-1, 19h.41m
    plowe-0: 3674-2, 12d.5h.27m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 223 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    amazon.com: 12
    amazon-adsystem.com: 1
    d1lxz4vuik53pc.cloudfront.net: 1
```
</details>

**Comment by PerfectSalad** [comment]
Maybe a candidate for an annoyance list? Have you tried some?

**Comment by mapx-** [comment]
@NickEckardt 

test

`amazon.*##.s-widget-container > .rush-component:has-text(Sponsored)`

**Comment by NickEckardt** [comment]
@mapx- adding that to my filters appears to have fixed the issue. Thanks!

**Comment by Yuki2718** [comment]
This seems to be uBO-specific issue due to Ignore generic cosmetic filters, `##.AdHolder` in EL hiding them.
