### ISSUE TITLE
tuyensinhso.vn: ads

### ISSUE THREAD

**Issue by nghiabros** [uBlockOrigin/uAssets#12277]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tuyensinhso.vn/nhom-nganh-dao-tao/nganh-ngon-ngu-anh-c16592.html`

### Category

ads

### Describe the issue

right hand / left hand side

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43260081/158558511-594358b3-eb3a-45ef-9905-fe1ffd0731ec.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 101578
  cosmetic: 87874
  scriptlet: 21356
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41766-9, 1d.9h.4m
    VIE-1: 2015-2, 8h.29m
    fanboy-cookiemonster: 24066-44, 8d.8h.35m
    ublock-annoyances: 4365-121, 4h.24m
  default: 
    user-filters: 0-0, never
    easylist: 64200-36, 4h.27m
    easyprivacy: 26684-221, 4h.26m
    plowe-0: 3674-810, 8d.8h.35m
    ublock-abuse: 72-1, 4h.25m
    ublock-badware: 3972-84, 4h.23m
    ublock-filters: 30306-184, 4h.22m
    ublock-privacy: 200-2, 4h.21m
    ublock-unbreak: 1728-43, 4h.20m
    urlhaus-1: 9515-1, 8h.28m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 459 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    dable.io: 1
    facebook.com: 1
    facebook.net: 1
    googleadservices.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by hoang-rio** [comment]
It done in ABPVN List
