### ISSUE TITLE
jobinja.ir nuisance (force login)

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#12279]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://jobinja.ir/companies/autokhatib/jobs/Rj1y/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%B4%D9%86%D8%A7%D8%B3-%D9%81%D8%B1%D9%88%D8%B4-%D8%AA%D9%84%D9%81%D9%86%DB%8C-%D8%AE%D9%88%D8%AF%D8%B1%D9%88-%D8%AE%D8%A7%D9%86%D9%85-%D8%AF%D8%B1-%D8%A7%D8%AA%D9%88-%D8%AE%D8%B7%DB%8C%D8%A8`

`https://jobinja.ir/companies/node-2/jobs/REys/%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85-%DA%A9%D8%A7%D8%B1%D8%B4%D9%86%D8%A7%D8%B3-%D8%AD%D8%B3%D8%A7%D8%A8%D8%AF%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%DA%AF%D8%B1%D9%88%D9%87-%D9%86%D9%88%D8%AF`

### Describe the issue

It's a website to find job offerings, but it forces users to login to be able to see the contents, the contents are partially visible and readable so this is **not** considered a paywall.

### Screenshot(s)

https://user-images.githubusercontent.com/17685483/158569550-b8357258-3b59-488f-9bef-123393af4a22.png

### Notes

Related issue: https://github.com/farrokhi/adblock-iran/issues/80

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 71701
  cosmetic: 41426
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    easylist: 64454-10, 5m
    easyprivacy: 26664-121, 5m
    plowe-0: 3674-805, 4d.17h.36m
    ublock-abuse: 72-0, 5m
    ublock-badware: 3967-85, 5m
    ublock-filters: 30214-145, 5m
    ublock-privacy: 200-2, 5m
    ublock-unbreak: 1723-39, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 185 ms
```
</details>

**Comment by mapx-** [comment]
I get (using translate to english)

![image](https://user-images.githubusercontent.com/10303732/158570717-ede6f9c3-f211-465c-bf36-e08e325101c9.png)

**Comment by okiehsch** [comment]
I can't read farsi. This is what I see at your second link.
![image](https://user-images.githubusercontent.com/16838044/158571217-fb5ec816-7b89-4938-ae67-25f7860f0286.png)

I suspect the left side is the login box. How can I reproduce your screenshot.

**Comment by MasterKia** [comment]
> I get (using translate to english)

Same, so it's a geo-specific issue.

* VPN On source code: https://pastetext.net/coekdhsnrs
* VPN Off source code: https://pastetext.net/vaivkyjsco
When I search for "force" in the "VPN On" code, I get 2 results but when I search it in the "VPN Off" code, I get 6 results.

* VPN On:
![image](https://user-images.githubusercontent.com/17685483/158571211-67051214-9a4b-42db-95fd-033cbaa4de56.png)


* VPN Off:
![image](https://user-images.githubusercontent.com/17685483/158571149-b5670791-3df9-4ccd-aee8-876b5771ada8.png)

**Comment by krystian3w** [comment]
> is the page source code enough

Maybe that method to save source no enough for everyone - after change dom tree the pop-up login wall is not visible on my side. 

If it was saved as active, I could check if the text is an image - if it is as image, it is not worth CSS to fix it, because the text is not there, then I would recommend a network filter or a scriptlet.

I don't rule out that someone knows a better method to debug as if the paths to the js files don't de-escalate.

In my paid VPN and AdGuard VPN are pointless looking for Iraqi and Iranian servers.

**Comment by MasterKia** [comment]
`jobinja.ir##.c-forceToLogin__overlay` and `jobinja.ir##.c-forceToLogin__message.o-box` remove the login prompt but the text is still blurry:
https://user-images.githubusercontent.com/17685483/158762967-98b3c0fd-07e0-479f-b9b5-c347ca895a11.png
(https://user-images.githubusercontent.com/17685483/158763036-fba0b24f-135f-422f-bdde-84c625823dd1.png


> looking for Iranian servers.

ZenMate VPN offers free Iran server during its one week free trial, you could sign up here with a fake mail and after email confirmation use it's browser extension:
`https://account.zenmate.com/en_US/signup`

![image](https://user-images.githubusercontent.com/17685483/158762626-dd683645-1a7b-48a4-a74b-c517978e8a34.png)

**Comment by MasterKia** [comment]
> If it was saved as active

You mean something like this?
[jobinja.zip](https://github.com/uBlockOrigin/uAssets/files/8282509/jobinja.zip)

I right clicked in the website and selected **save as**.

**Comment by krystian3w** [comment]
I can disable blur with:

```
##[class*="forceToLogin"] [class*="forceToLogin"]:style(filter: none !important)
```

So this is real text.

**Comment by MasterKia** [comment]
```
jobinja.ir##.c-forceToLogin__overlay
jobinja.ir##.c-forceToLogin__message.o-box
jobinja.ir##[class*="forceToLogin"] [class*="forceToLogin"]:style(filter: none !important)
```

These 3 filters get the job done.

**Comment by MasterKia** [comment]
Addressed in [PersianBlocker](https://github.com/MasterKia/PersianBlocker).
https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0

Gonna submit a PR to remove from uBlock Annoyances.
