### ISSUE TITLE
slidesgo.com: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#12273]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slidesgo.com/education`

### Category

ads

### Describe the issue

When you enter the site, some things are blocked but these ads are not

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/58097612/158492082-ab86356b-5075-46c4-a6b2-7fa483a3971d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 82533
  cosmetic: 41476
  scriptlet: 16466
  html: 624
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30821-29, 2d.22h.40m
    ublock-badware: 3976-3, 2d.22h.41m
    ublock-privacy: 204-0, 2d.22h.39m
    ublock-abuse: 72-0, 2d.22h.45m
    ublock-unbreak: 1736-0, 2d.22h.44m
    easylist: 64596-601, 2d.22h.43m
    easyprivacy: 26669-570, 2d.22h.42m
    urlhaus-1: 10713-1, 23h.18m
    plowe-0: 3674-2, 7d.22h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2072 ms (selfie)
  maxAssetCacheWait: 717 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    slidesgo.com: 2
    cloudflareinsights.com: 8
    google.com: 2
    googletagmanager.com: 2
    ssm.codes: 1
```
</details>

**Comment by 3kh0** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/58097612/158492784-44d19702-3d96-4077-8cea-b1e1a7c14375.png)

**Comment by mapx-** [comment]
add

```
slidesgo.com##.ssm_adunit_container
slidesgo.com##[id^="article_ads"]
```

@ryanbr

**Comment by casualkitten1** [comment]
Still seeing ads as of today. :-(

**Comment by mapx-** [comment]
fixed
