### ISSUE TITLE
su.gdatasoftware.com: breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#12278]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://su.gdatasoftware.com/us/sample-submission?key=Y2Q5YzFjZjdmMDIyYTJkMjNlZDcyZmJlYmVkN2VhNmQ2MjViMTVkMzQ5M2Y5YWJl5mQysEtbU28BgY8Kot8ucxlD_qfhKRcBylyAl-VUI4-oiu-Jf8hsXH-H4x4PU_VkTk6TEwTaD0oS5fLgdnMOEFgZAqm0pJj6rigoANAQjLxLOzz9XH9NsoK6NYgcv-53tEb7scNLsEW2m37ZpgLArCspbFxvY2IqVKdlfeB18FfhXhqmNdckroB7WTBDOGroTwJzYzJ5-KXKxua0cnpaNz07WIWUE-g3OuBr9uujv7a2npUWzY3kF9QlIQ94r58-kN6Hb6hBPOwUzhdkncGR8Sds5OIqATaJzYxdintUvubv0TfiqxG-EC7IRVs_h2c8g4rrKIwmE-HsJ7YmSHoDxtWrjkhT7VEiB6iIhllHaCR2X6ZA6w9shlBqzl0n5NjGQOCrfKfOH7DSwrBe0stGcUsE`

### Category

breakage

### Describe the issue

The tickbox before “By using this function, you explicitly agree to [...]” disappears when uBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 180995
  cosmetic: 207883
  scriptlet: 34023
  html: 633
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 879-6, 21m
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1957-14, 1d.28m
    https://paulgb.github.io/BarbBlock/blacklists/ublock-origin.txt: 550-7, 1d.48m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37498-972, 1d.29m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-0, 1d.49m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-1965, 1d.47m
    https://www.i-dont-care-about-cookies.eu/abp/: 24507-8731, 1d.30m
    adguard-generic: 62595-5212, 1d.45m
    adguard-mobile: 7339-190, 1d.38m
    adguard-spyware: 26737-1067, 1d.36m
    adguard-annoyance: 50851-4913, 1d.46m
    adguard-social: 16303-1107, 1d.35m
    fanboy-thirdparty_social: 68-0, 43m
    fanboy-annoyance: 65209-49838, 8d.4h.26m
    fanboy-cookiemonster: 24668-148, 42m
    fanboy-social: 23214-53, 1d.34m
    ublock-annoyances: 4373-10, 1d.32m
    dpollock-0: 10347-491, 10d.23h.43m
    adguard-spyware-url: 503-3, 1d.31m
    block-lan: 44-0, 10d.23h.41m
    [2 lists not shown]: [too many]
  default: 
    user-filters: 2-0, never
    ublock-filters: 30883-190, 1d.43m
    ublock-badware: 3976-3, 1d.42m
    ublock-privacy: 204-0, 1d.41m
    ublock-abuse: 72-4, 1d.40m
    ublock-unbreak: 1737-1, 1d.39m
    easylist: 64153-3467, 1d.37m
    easyprivacy: 26684-11178, 1d.44m
    urlhaus-1: 8505-1, 21m
    plowe-0: 3674-366, 6d.22h.23m
    GRC-0: 1002-1, 1d.27m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10881 ms (selfie)
  maxAssetCacheWait: 2573 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`gdatasoftware.com#@##privacyInfo`

FA issue @ryanbr
