### ISSUE TITLE
EasyPrivacy filter not works correctly on https://uptolike.ru

### ISSUE THREAD

**Issue by aerosy** [uBlockOrigin/uAssets#12271]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://uptolike.ru
http://uptolike.ru
```

### Describe the issue

EasyPrivacy filter not works correctly on `https://uptolike.ru` page, 
please fix this problem to make buttons for social networks work.
Thank you

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b1
Firefox: 99
filterset (summary): 
  network: 101148
  cosmetic: 66792
  scriptlet: 18112
  html: 630
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41774-110, 16m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30911-179, 15m
    ublock-badware: 3954-3, 15m
    ublock-privacy: 204-0, 16m
    ublock-abuse: 72-0, 16m
    ublock-unbreak: 1738-0, 16m
    easylist: 64200-506, 16m
    easyprivacy: 26683-583, now
    urlhaus-1: 9515-1, 16m
    plowe-0: 3671-2, 16m
    DEU-0: 5544-2, 17m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1599 ms
  maxAssetCacheWait: 626 ms
```
</details>

**Comment by mapx-** [comment]
> please fix this problem to make buttons for social networks work

details on what's broken ?

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
As I understand it, in EasyPrivacy need to change:
```
||uptolike.com^$third-party
||uptolike.com/widgets/*/imp?
```
`>`
```
||uptolike.com^$third-party,domain=~uptolike.ru
||uptolike.com/widgets/*/imp?$third-party,domain=~uptolike.ru
```
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a20cc116e8e646b6faf8512a50f43048458ec21c  all thats needed.

**Comment by dimisa-RUAdList** [comment]
But what about these: `https://i.imgur.com/ACAczIq.jpg` buttons?

**Comment by aerosy** [comment]
Thank you for fix, i have now clear cache and Update Main Base, all work now...
Great Thanks!!!!!!

**Comment by ryanbr** [comment]
`http://w.uptolike.com/widgets/v1/uptolike.js` works on the site, is currently unblocked.

**Comment by dimisa-RUAdList** [comment]
@aerosy 
Describe the steps you need to follow to reproduce the issue.

**Comment by aerosy** [comment]
1. I registered at https://uptolike.ru
2. Clicked on Share - (Поделиться)
3. Created the list I want.
4. Clicked on Generate code - (Генерировать код)
5. I pasted the finished code into the html site code

It works only if the filter EasyPrivacy is switched off...

**Comment by dimisa-RUAdList** [comment]
`Clicked on Share - (Поделиться)` - Where did you click it?

**Comment by dimisa-RUAdList** [comment]
At what step does the problem occur?

**Comment by aerosy** [comment]
Buttons stopped working again

**Comment by dimisa-RUAdList** [comment]
This is a dead end. Create a topic here: https://forums.lanik.us/viewforum.php?f=102

Here are the rules for how to do it: https://forums.lanik.us/viewtopic.php?t=24280

When the situation clears up, it will be possible to return with the solution to the github.
