### ISSUE TITLE
lidl.pt: breakage

### ISSUE THREAD

**Issue by ndias** [uBlockOrigin/uAssets#12276]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lidl.pt/pt/folhetos/oportunidades-a-partir-de-14-03/view/flyer/page/1?utm_source=newsletter_semanal&utm_medium=email&utm_campaign=22_kw11_seg&utm_content=nonfood`

### Category

breakage

### Describe the issue

When I try to block any element nothing happens, the page change the color but ublock doesn't display the options to block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80402
  cosmetic: 42072
  scriptlet: 16502
  html: 626
listset (total-discarded, last updated): 
  default: 
    user-filters: 687-28, never
    ublock-filters: 30872-29, 1d.17h.29m
    ublock-badware: 3976-3, 1d.17h.27m
    ublock-privacy: 204-0, 3d.16h.8m
    ublock-abuse: 72-0, 3d.16h.14m
    ublock-unbreak: 1736-0, 3d.16h.12m
    easylist: 64589-590, 3d.16h.16m
    easyprivacy: 26669-570, 3d.16h.10m
    plowe-0: 3671-2, 1d.17h.34m
    urlhaus-1: 8505-1, 52m
filterset (user): [array of 687 redacted]
trustedset: 
  added: [array of 129 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 452 ms (selfie)
  maxAssetCacheWait: 264 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
No issue on my end, maybe you should disable all your custom filters and test again

![image](https://user-images.githubusercontent.com/10303732/158563616-0d03433a-e864-4502-930a-17e3807cb11f.png)

**Comment by ndias** [comment]
I have this problem with Firefox and chrome, in chrome I reset to the defaults I do not usually use chrome, so I don't have any custom  filters and the problem happens.
I don't know if this is relevant but I' using Linux (Fedora 35) and Firefox 98 and Chrome 99

**Comment by stephenhawk8054** [comment]
Can you test in new profile? I can't reproduce it either.

**Comment by krystian3w** [comment]
I suppose rare issue then can by touched is only photo/video element by only network filtering sugestion.

Then gwaser recommend save erros from devtools,  browser js console or addon debug console.

**Comment by ndias** [comment]
I've tested with 2 different computers although the same OS (fedora 35), the problem happens in this 2 computers using Firefox or Chrome I can't see any errors in console or addon debug console
