### ISSUE TITLE
atomixhq.link: detection

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#12275]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://atomixhq.link/`

### Category

detection

### Describe the issue

not only detects an "ad blocker", not just ublock, but a general "ad blocker". it also shows a "verification page" which keeps popping ads and asks you to open links that will contain more and more ads promising that after a countdown you'll access the content, but that never happens. 
it asks you to open a website on a google search page (`www.pequerecetas.com/something`), then it shows you a site asking to click on an ad that will enable content for 24 hours after waiting for 30 seconds. no ads appear, but asks you to close and open the link again and again ...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 84363
  cosmetic: 46034
  scriptlet: 16688
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64586-10, 3d.20h.34m
    easyprivacy: 26666-121, 3d.20h.33m
    plowe-0: 3674-805, 10d.8h.35m
    spa-0: 3816-30, 20h.19m
    spa-1: 4259-166, 3d.20h.32m
    ublock-abuse: 72-0, 3d.20h.31m
    ublock-badware: 3967-85, 3d.20h.30m
    ublock-filters: 30224-200, 3d.20h.29m
    ublock-privacy: 200-2, 3d.20h.28m
    ublock-unbreak: 1725-40, 3d.20h.27m
    urlhaus-1: 9515-0, 20h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 618 ms (selfie)
  maxAssetCacheWait: 385 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    atomixhq.link: 2
    befirstcdn.com: 1
    d2q9y3krdwohfj.cloudfront.net: 3
    ducina.com: 1
    mauchopt.net: 2
    mingledventin.com: 1
    rndskittytor.com: 1
    uwoaptee.com: 1
```
</details>

**Comment by mapx-** [comment]
fixed anti adb on `sub-short.link​`
