### ISSUE TITLE
animedao.to: popups

### ISSUE THREAD

**Issue by MontyG13** [uBlockOrigin/uAssets#12274]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animedao.to/view/5890215112/`

### Category

popups

### Describe the issue

Popups happen when clicking on the video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80832
  cosmetic: 41549
  scriptlet: 16536
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64152-10, 21h.4m
    easyprivacy: 26677-121, 2d.2h.27m
    plowe-0: 3674-805, 6d.16h.12m
    ublock-abuse: 72-0, 2d.2h.26m
    ublock-badware: 3972-84, 1d.22h.4m
    ublock-filters: 30282-136, 2d.2h.30m
    ublock-privacy: 200-2, 2d.2h.29m
    ublock-unbreak: 1725-39, 2d.2h.28m
    urlhaus-1: 9515-1, 21h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1653 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    amung.us: 1
    bidgear.com: 3
    cdnativepush.com: 6
    cloudflareinsights.com: 1
    denetsuk.com: 1
    e2ertt.com: 1
    jomtingi.net: 5
    jwpltx.com: 1
    outoctillerytor.com: 6
    soaheeme.net: 2
```
</details>

**Comment by ghajini** [comment]
already addressed i think

https://github.com/uBlockOrigin/uAssets/commit/04458d08a25070e2bd2b94fe0b44637e0e4e2329

**Comment by stephenhawk8054** [comment]
> already addressed i think
> 
> [04458d0](https://github.com/uBlockOrigin/uAssets/commit/04458d08a25070e2bd2b94fe0b44637e0e4e2329)
> 
> user may not have updated filters ublock filters 2d 2h 30mins

Ah yeah I saw that filter, didn't realize it was added recently tho. However, I still got the ads and popup on chromium even with `##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/158553278-109bf62b-b13e-4251-8b79-e659bf65612d.png)

</details>

The `aost` filter works fine on Firefox, I don't know why. @mapx- Can you check it?

**Comment by mapx-** [comment]
aost does not work on my side FF / chrome
working => `gogoplay4.com##+js(acis, JSON.parse, break;case $.)`

**Comment by stephenhawk8054** [comment]
So, should we remove `aost` filter? Since `acis` already does the job.

**Comment by mapx-** [comment]
yes, maybe they are using some new version ?!

**Comment by stephenhawk8054** [comment]
> yes, maybe they are using some new version ?!

Hmmm... it's weird. When I tested removing `aost` filter with other domains that has `gogoplay4.com` (for example `https://gogoanime.fi/groizer-x-episode-33`) on different browsers:

- Firefox, Chrome, Edge and vanilla chromium works normally, no 3rd ads and popup.
- Brave still has that issue until adding `aost` filter again.

**Comment by mapx-** [comment]
well, let's keeping both for now
