### ISSUE TITLE
dcode.fr anti-adblockers

### ISSUE THREAD

**Issue by anonymous7002** [uBlockOrigin/uAssets#12288]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dcode.fr`

### Describe the issue

dcode.fr has anti-adblockers

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.1

### Settings

no changes

### Notes

these filters block them, but not perfectly:
`www.dcode.fr##div[style^="z-index: 100"]`
`www.dcode.fr##div[style^="z-index: 150"]`

**Comment by krystian3w** [comment]
Fixed years ago: https://github.com/uBlockOrigin/uAssets/blob/7686a82ad94d87365f4f566267549814516f3577/filters/filters-2020.txt#L2344-L2348

https://github.com/uBlockOrigin/uAssets/commit/272ae46eb342566e62d26e4400bf6ae270371818

**Comment by JobcenterTycoon** [comment]
Can’t reproduce too

**Comment by anonymous7002** [comment]
I resetted to the default settings
I'm talking about a new anti-adblocker:

"Oops! Issue detected!

Something is blocking dCode and prevent it to load correctly.

1/ Check connection status and/or browser update

2/ Whitelist dcode.fr and/or disable your ad-blocker ([How?](https://www.wikihow.com/Disable-Your-Ad-Blocker))

Thank You"

**Comment by mapx-** [comment]
Where do you get it ? home page ? specific page ?

So, you have now the default settings, lists, I guess the french list is enabled too, right ?

- open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the search box)

**Comment by krystian3w** [comment]
Easylist bugs:

```
/static/ad/*$badfilter
/ad/index_$badfilter
_ad_service.$badfilter
/static/ad/*$domain=~dcode.fr
/ad/index_$domain=~dcode.fr
_ad_service.$domain=~dcode.fr
```

**Comment by wxolp** [comment]
test

**Comment by mapx-** [comment]
> I reproduced the issue a couple of times https://ibb.co/MD9d4Yq

I asked 2 things:
- specific page
- **only the blocked items**

**Comment by krystian3w** [comment]
Nope, morse subpage needed too:

```
/ad/index_$badfilter
_ad_service.$badfilter
```

If newest EL don't deleted both silently.

**Comment by JobcenterTycoon** [comment]
Can confirm with the link. Click on the second calculate button to reproduce.

`@@||dcode.fr$xhr,1p` works

**Comment by mapx-** [comment]
add

```
.fr/*/ads/$from=~lemde.fr|~yoopies.fr,badfilter
/static\/*\/ads/$badfilter
```

@Yuki2718 french list
@smed79

**Comment by Yuki2718** [comment]
@smed79 Please notify when fixed in Liste FR.
