### ISSUE TITLE
members.equinoxplus.com: breakage

### ISSUE THREAD

**Issue by maxallen** [uBlockOrigin/uAssets#12289]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://members.equinoxplus.com/login`

### Category

breakage

### Describe the issue

On Chrome with Ublock enabled I see a black screen when I load this webpage. Whereas on Safari a sign-in page loads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80339
  cosmetic: 41520
  scriptlet: 16536
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64640-10, 2d.15h.8m
    easyprivacy: 26677-121, 2d.15h.7m
    plowe-0: 3671-805, 2d.15h.18m
    ublock-abuse: 72-0, 2d.15h.6m
    ublock-badware: 3972-85, 2d.15h.5m
    ublock-filters: 30282-132, 2d.15h.4m
    ublock-privacy: 200-2, 2d.15h.3m
    ublock-unbreak: 1725-39, 2d.15h.2m
    urlhaus-1: 8505-1, 11h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 117 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    equinoxplus.com: 2
    adobedtm.com: 2
    ipify.org: 1
    mparticle.com: 1
```
</details>

**Comment by mapx-** [comment]
test

`@@||api.ipify.org^$xhr,domain=members.equinoxplus.com`

EP issue @ryanbr
