### ISSUE TITLE
empflix.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1228]
URL(s) where the issue occurs

`https://www.empflix.com/blowjob-videos/Hot-Naomi-Woods-flashes-tits-to-a-stranger-for-money/video1826911`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by dumbusernameidk** [comment]
ads
