### ISSUE TITLE
lf1.lordfilm.lu: nuisance

### ISSUE THREAD

**Issue by Spok1** [uBlockOrigin/uAssets#12283]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [x] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lf1.lordfilm.lu/10898-film-mech-korolja-artura-2017.html`

### Category

nuisance

### Describe the issue

Кнопка поделиться без особой полезности в плеере!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/34476664/158619194-60331eca-5555-43b7-9191-ba47ca4bee77.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 89
filterset (summary): 
  network: 86140
  cosmetic: 62112
  scriptlet: 18027
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    RUS-0: 41768-9, 9m
    easylist: 62254-18, never
    easyprivacy: 26549-112, never
    ublock-abuse: 77-1, never
    ublock-badware: 3985-65, never
    ublock-filters: 30227-137, never
    ublock-privacy: 203-0, never
    ublock-unbreak: 1716-39, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5210 ms
  maxAssetCacheWait: 699 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    lordfilm.lu: 1
    aj1907.online: 1
    jsdelivr.net: 1
    myangular.life: 13
    stiven-king.com: 1
    vak345.com: 1
```
</details>

**Comment by krystian3w** [comment]
If AdGuard and Fanboy Social mark domains as too small then must block this in "my filters" tab in uBO dashboard.

**Comment by Spok1** [comment]
> try
> 
> `lordfilm.lu,synchroncode.com##[class^="top-right_"]`

should this be added to the custom list?

**Comment by mapx-** [comment]
add it in your "my filters"

**Comment by Spok1** [comment]
And who adds the rules to the subscription?

**Comment by mapx-** [comment]
Probably nobody and you'll use it as custom filter.
Why not ? because for you it's annoyance but for other people could be a feature (to share stuff)

**Comment by Spok1** [comment]
Are they generally involved in adding filtering rules to signatures here? I didn't see any requests.

**Comment by mapx-** [comment]
@ryanbr
