### ISSUE TITLE
Intel Driver & Support Assistant: breakage

### ISSUE THREAD

**Issue by MrUltimate** [uBlockOrigin/uAssets#12287]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html`

### Category

breakage

### Describe the issue

Intel® Driver & Support Assistant can no longer detect system specs and perform update actions when uBO is enabled. A blanket error is displayed that thinks that their plugin is not installed. Website works as expected when uBO is disabled on the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-03-16 150213](https://user-images.githubusercontent.com/7812204/158667162-2ce6791b-fe6c-4074-ba63-ebeb1c92c6ac.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 96877
  cosmetic: 41786
  scriptlet: 17030
  html: 626
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 26729-924, 1d.22h.19m
    adguard-spyware-url: 503-3, 1d.22h.18m
    block-lan: 43-0, 1d.22h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30884-32, 1d.22h.20m
    ublock-badware: 3971-3, 4d.16h.14m
    ublock-privacy: 207-0, 4d.16h.13m
    ublock-abuse: 72-0, 1d.22h.17m
    ublock-unbreak: 1736-0, 4d.2h.43m
    easylist: 64725-628, 1d.22h.23m
    easyprivacy: 26679-10670, 1d.22h.21m
    urlhaus-1: 9515-0, 20h.57m
    plowe-0: 3675-2, 12d.17h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5513 ms
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    intel.com: 8
    127.0.0.1: 10
    clicktale.net: 1
    googlesyndication.com: 1
    omtrdc.net: 1
```
</details>

**Comment by mapx-** [comment]
I get errors even disabling uBO

**Comment by MrUltimate** [comment]
> I get errors even disabling uBO

Does your browser have an in-built tracking blocker? I would try disabling that,

**Comment by okiehsch** [comment]
@mapx- you need to download the Intel Driver & Support Assistant app to reproduce would be my guess.

**Comment by okiehsch** [comment]
@MrUltimate what is blocking the  `127.0.0.1: 10`  requests on your end?

Seems like that could cause the issue.

**Comment by MrUltimate** [comment]
> @MrUltimate what is blocking the `127.0.0.1: 10` requests on your end?
> 
> Seems like that could cause the issue.

Not sure what this is. How can I find out?

**Comment by MrUltimate** [comment]
> @mapx- you need to download the Intel Driver & Support Assistant app to reproduce would be my guess.

I've had it installed for a few years now. Worked finally until just today when I saw this. Disabling uBO and reloading works.

**Comment by mapx-** [comment]
ok, this is the filter 
`/^\w+:\/\/127\.(?:(?:[1-9]?\d|1\d\d|2(?:[0-4]\d|5[0-5]))\.){2}(?:[1-9]?\d|1\d\d|2(?:[0-4]\d|5[0-5]))[:/]/$3p,domain=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost`

needing
`@@||127.0.0.1:*/intel/$xhr,domain=intel.com`

**Comment by mapx-** [comment]
@gwarser

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/158677491-edd08234-f556-406e-a8c9-28d93d7b3741.png)

**Comment by krystian3w** [comment]
We removed exceptions here: #12139 - IMO list no longer support exceptions compatible with ABP/EasyList syntax.

**Comment by gwarser** [comment]
"Block Outsider Intrusion into LAN" is doing it's job. If you don't want access from internet to your local network be blocked - disable the list.

**Comment by dungsaga** [comment]
@MrUltimate you can add an exception to "My Filters" instead of disabling the list "Block Outsider Intrusion into LAN":
`@@||127.0.0.1:*/intel/$xhr,domain=intel.com`

**Comment by krystian3w** [comment]
Disable for 10 minutes once on month is not bad.

**Comment by MrUltimate** [comment]
> @MrUltimate you can add an exception to "My Filters" instead of disabling the list "Block Outsider Intrusion into LAN": `@@||127.0.0.1:*/intel/$xhr,domain=intel.com`

Thank you, this is the way to go for me.
