### ISSUE TITLE
koszalincity.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#12295]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`koszalincity.pl`

### Describe the issue

locked selection by known:

`[id^="wpcp_"][id*="_disable_"]` + `HEAD STYLE:has-text(.unselectable)`

### Screenshot(s)

N/A

### uBlock Origin version

1.41.8

### Browser name and version

Firefox Nightly 100

### Settings

- enabled uBO annoyances

### Notes

html filtering works bad, **so don't use** this: `koszalincity.pl##^HEAD STYLE:has-text(.unselectable):has-text(/([\w\W]{303}|[\w\W]{286}|[\w\W]{259})/)` - page minified CSS and regex fail detect min-max range (in this scenario may no help exist `:min-text-length(n)`).

**Comment by Procyon-b** [comment]
Try these filters to re-enable selection, copying to clipboard and context menu.
```
koszalincity.pl##*:style(user-select:auto!important;)
koszalincity.pl##+js(set, disableEnterKey, noopFunc)
koszalincity.pl##+js(aopw, document.oncontextmenu)
```

**Comment by Procyon-b** [comment]
@stephenhawk8054 I used `js(set, disableEnterKey, noopFunc)` because it's the first declaration in the script block, not because it was in the first assignment.

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 I used `js(set, disableEnterKey, noopFunc)` because it's the first declaration in the script block, not because it was in the first assignment.

I think `+js(acis, document.onkeydown)` has the same effect?

**Comment by Procyon-b** [comment]
I thought too, but I think that you're more experienced than me, and I don't know what is the best method.

**Comment by stephenhawk8054** [comment]
> I thought too, but I think that you're more experienced than me, and I don't know what is the best method.

Oh it's ok, I'm not that experienced either. Any feedback is appreciated.
