### ISSUE TITLE
careers.southwestair.com: breakage

### ISSUE THREAD

**Issue by dkowis** [uBlockOrigin/uAssets#12294]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://careers.southwestair.com/`

### Category

breakage

### Describe the issue

Nothing loads, because there are a giant pile of CDN resources that are not delivered.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/28048/158703072-eba2b112-66d5-4d4a-af8e-391cf2ceecd5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79885
  cosmetic: 41577
  scriptlet: 16514
  html: 627
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30911-29, 18h.44m
    ublock-badware: 3976-3, 18h.43m
    ublock-privacy: 204-0, 18h.42m
    ublock-abuse: 72-0, 18h.41m
    ublock-unbreak: 1739-0, 18h.40m
    easylist: 64202-597, 18h.39m
    easyprivacy: 26683-572, 18h.38m
    urlhaus-1: 8505-1, 18h.37m
    plowe-0: 3672-2, 4d.19h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 781 ms (selfie)
  maxAssetCacheWait: 156 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    googletagmanager.com: 1
    phenompeople.com: 25
```
</details>

**Comment by Procyon-b** [comment]
If you want to make it work without allowing the entire cdn, try these filters:
```
@@||phenompeople.com^$image,css,font,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/ph-basic-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/require-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/vendor-bundle-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/common/ph-common-bundle-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/SOUTUS/en_us/desktop/page5/ph-page-page5-*.js?v=1$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/ph-loader-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/appConfig/ph-app-config-*.js?v=1$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/SOUTUS/en_us/desktop/assets/scripts/*-custom.js?v=1$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/caas-platform/vendor/vue.min-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/caas-platform/common/pcs-common-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/jquery.min-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/jquery-migrate.min-*.js$script,domain=careers.southwestair.com
@@||cdn.phenompeople.com/CareerConnectResources/common/js/vendor/slick-*.min.js$script,domain=careers.southwestair.com
```

**Comment by stephenhawk8054** [comment]
It's caused by `||phenompeople.com^$3p` in EP.

@ryanbr
