### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by GaetanGrd** [uBlockOrigin/uAssets#12299]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aternos.org/server/`

### Category

detection

### Describe the issue

![Uploading Capture d’écran 2022-03-17 133800.png…]()

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 96286
  cosmetic: 50500
  scriptlet: 16548
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 26195-25, 3d.23h.45m
    easylist: 64611-44, 3d.23h.44m
    easyprivacy: 26670-439, 3d.23h.43m
    plowe-0: 3671-813, 5h.15m
    ublock-abuse: 72-1, 3d.23h.42m
    ublock-badware: 3972-92, 3d.23h.41m
    ublock-filters: 30230-296, 3d.23h.40m
    ublock-privacy: 200-2, 3d.23h.39m
    ublock-unbreak: 1726-39, 3d.23h.38m
    urlhaus-1: 7937-1, 20h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 423 ms (selfie)
  maxAssetCacheWait: 85 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    aternos.org: 1
    cloudflareinsights.com: 1
    google-analytics.com: 1
    snigelweb.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Quick fixes`
<img width="356" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/158813462-e9d52638-3a3b-460d-a286-1d8059a1f156.PNG">

**Comment by GaetanGrd** [comment]
I, problem resolved thanks
