### ISSUE TITLE
amazon.com: breakage

### ISSUE THREAD

**Issue by ericrichards** [uBlockOrigin/uAssets#12291]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/gp/css/order-history?ref_=nav_orders_first`

### Category

breakage

### Describe the issue

Page keeps updating without completing the full display of information.  It may be tied to a facebook pixel on that page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79324
  cosmetic: 41576
  scriptlet: 16511
  html: 626
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30910-29, 1d.7m
    ublock-badware: 3976-3, 1d.14m
    ublock-privacy: 204-0, 1d.13m
    ublock-abuse: 72-0, 1d.12m
    ublock-unbreak: 1737-0, 1d.11m
    easylist: 64200-597, 1d.10m
    easyprivacy: 26683-570, 1d.9m
    urlhaus-1: 7937-1, 4h.6m
    plowe-0: 3674-2, 8d.9h.46m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1113 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Test using only uBO, no other addon.
Disable ETP (extended tracking protection).

If still does not work reset uBO to defaults or reinstall it.
