### ISSUE TITLE
trygghansa.se: breakage

### ISSUE THREAD

**Issue by zippy1979** [uBlockOrigin/uAssets#12298]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.trygghansa.se/logga-in`

### Category

breakage

### Describe the issue

Unable to initiate the "MobileBankID" login function

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79261
  cosmetic: 41567
  scriptlet: 16553
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64153-10, 2d.1h.28m
    easyprivacy: 26684-121, 21h.26m
    plowe-0: 3671-805, 2d.1h.29m
    ublock-abuse: 72-0, 21h.25m
    ublock-badware: 3950-84, 21h.24m
    ublock-filters: 30343-137, 21h.23m
    ublock-privacy: 200-2, 21h.22m
    ublock-unbreak: 1728-41, 21h.21m
    urlhaus-1: 7937-1, 17h.20m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3140 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 4
  no-cosmetic-filtering: true
  blockedDetails: 
    adobedtm.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
`@@||assets.adobedtm.com/extensions/*/AppMeasurement$script,domain=trygghansa.se`
