### ISSUE TITLE
theghostinmymachine.com: nuisance

### ISSUE THREAD

**Issue by cocapoda** [uBlockOrigin/uAssets#12297]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://theghostinmymachine.com/`

### Category

nuisance

### Describe the issue

Site prevents highlighting text, middle-click scrolling, and right-clicking. This issue occurs on all articles across the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79043
  cosmetic: 40294
  scriptlet: 16388
  html: 618
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 30802-105, 5m
    ublock-badware: 3989-3, 5m
    ublock-privacy: 202-0, 5m
    ublock-abuse: 77-0, 5m
    ublock-unbreak: 1727-0, 5m
    easylist: 62254-99, 5m
    easyprivacy: 26549-27, 5m
    urlhaus-1: 8168-0, 5m
    plowe-0: 3715-820, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1436 ms (selfie)
  maxAssetCacheWait: 394 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googletagmanager.com: 2
    mediavine.com: 2
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`
