### ISSUE TITLE
crunchyscan.fr: detection

### ISSUE THREAD

**Issue by Khabes31** [uBlockOrigin/uAssets#12309]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crunchyscan.fr/`

### Category

detection

### Describe the issue

![Crunchyscan](https://user-images.githubusercontent.com/101841161/158906861-d81ebd2b-fae6-4c11-b243-be03db61fbe6.JPG)

The same issue than here : https://github.com/uBlockOrigin/uAssets/issues/11698

It was working perfectly since one week, suddenly the website detect ublock again.. 

it's say : advertising blocker are not allowed on the website

Thanks in advance

PS : Sorry for my english

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 130016
  cosmetic: 208564
  scriptlet: 33477
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://cdn.jsdelivr.net/gh/bmyjacks/adlists@master/specific-area/AdGuard-English-Filter.txt: 131347-1700, 54m
    https://filters.adtidy.org/extension/ublock/filters/2.txt: 127039-111743, 54m
    https://filters.adtidy.org/extension/ublock/filters/2_optimized.txt: 52967-52967, 54m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 44m
    https://raw.githubusercontent.com/rampageX/fuckfuckadblock/master/my_antiadblock_selection.txt: 23793-18174, 10m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt: 955-173, 54m
    adguard-annoyance: 50948-3473, 54m
    adguard-social: 16362-785, 54m
    fanboy-annoyance: 63867-3983, 54m
    fanboy-cookiemonster: 25253-25253, 54m
    fanboy-social: 23231-23231, 54m
    fanboy-thirdparty_social: 69-21, 54m
    ublock-annoyances: 4367-296, 54m
  default: 
    user-filters: 0-0, never
    FRA-0: 26203-577, 54m
    easylist: 64339-64313, 54m
    easyprivacy: 26702-610, 54m
    plowe-0: 3671-825, 54m
    ublock-abuse: 72-1, 54m
    ublock-badware: 3922-254, 54m
    ublock-filters: 30354-4622, 54m
    ublock-privacy: 200-10, 54m
    ublock-unbreak: 1740-104, 54m
    urlhaus-1: 7933-1, 54m
    ublock-quick-fixes: 92-9, 54m
filterset (user): [empty]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 953 ms (selfie)
  maxAssetCacheWait: 1089 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    arc.io: 3
    d3tozt7si7bmf7.cloudfront.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    onesignal.com: 1
    sentry-cdn.com: 1
    taboola.com: 1
    tumultmarten.com: 4
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
crunchyscan.fr##+js(nostif, alert)
```

**Comment by Khabes31** [comment]
> Try this filter:
> 
> ```
> crunchyscan.fr##+js(nostif, alert)
> ```
> 
> Tu ouvres le "Tableau de bord" de ublock (clique l'icone d'ublock puis l'icone "engrenage") va dans l'onglet "Mes filtres", et copie le filtre çi-dessus dans une ligne vide. Clique "Appliquer". Re-visite le site et normalement c'est bon.

Ca marche nickel ! Merci beaucoup

**Comment by AdamLePrince** [comment]
Salut les gens ,  j'ai moi aussi le même problème avec Cruchyscan qui arrive a bloquer  Ublock. J'ai essayé l'astuce de Procyon
mais sa ne marche pas ou plus ! 
![image](https://user-images.githubusercontent.com/103552520/163097253-5055ad19-666d-400e-949f-32e49de7badd.png)

**Comment by Procyon-b** [comment]
@stephenhawk8054
They use this one too:
```
crunchyscan.fr##+js(set, document.oncontextmenu, null)
```

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 They use this one too:
> 
> ```
> crunchyscan.fr##+js(set, document.oncontextmenu, null)
> ```
> 
> **Edit:** I meant : `crunchyscan.fr##+js(aeld, contextmenu)` and you made a typo on the one above `no` instead of `on`

Ah right, tks a lot. It should be `oncontextmenu`.

**Comment by AdamLePrince** [comment]
![image](https://user-images.githubusercontent.com/103552520/163326921-35667306-ae27-4a47-84b3-7105dbfa5691.png)
Hi, I tried but it still doesn't work.
