### ISSUE TITLE
streamtapeadblock.art: breakage

### ISSUE THREAD

**Issue by ezzmay007** [uBlockOrigin/uAssets#12307]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamtapeadblock.art/v/RB1zWLJQQ9sdyVd/married.at.first.sight.au.s09e28.hdtv.x264-fqm.mp4`

### Category

breakage

### Describe the issue

video infinite loads with ublock enabled, without u block video will play after 500 ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79289
  cosmetic: 41556
  scriptlet: 16542
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64153-10, 2d.11h.39m
    easyprivacy: 26679-121, 2d.19h.43m
    plowe-0: 3674-805, 8d.11h.41m
    ublock-abuse: 72-0, 2d.19h.41m
    ublock-badware: 3972-84, 2d.19h.40m
    ublock-filters: 30303-137, 2d.19h.44m
    ublock-privacy: 200-2, 2d.19h.42m
    ublock-unbreak: 1739-40, 7h.45m
    urlhaus-1: 7950-1, 3h.44m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 75 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 21 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8707 ms (selfie)
  maxAssetCacheWait: 430 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    betotodilea.com: 1
    liveredwilton.com: 1
    yandex.ru: 1
```
</details>

**Comment by ezzmay007** [comment]
forgot to refresh after i purged the cache, so sorry, seems to work fine now, excelent work

**Comment by 89z** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12301
