### ISSUE TITLE
streamtape.com

### ISSUE THREAD

**Issue by 89z** [uBlockOrigin/uAssets#12301]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamtape.com/v/kPzO40PR68COAGD/This_is_TOXIC_-_Battlefield_2042`

### Category

category

### Describe the issue

It redirects here:

`https://streamtapeadblock.art/v/kPzO40PR68COAGD/This_is_TOXIC_-_Battlefield_2042`

then you cant play the video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

config

**Comment by 89z** [comment]
test

**Comment by 89z** [comment]
test

**Comment by mapx-** [comment]
already fixed

**Comment by 89z** [comment]
I dont think its fixed. This is why links should not be in code blocks. If you copy paste the link into a new tab, everything is fine. but if you actually clink the link from some domain, it fails and you get the redirect. For example, click the link:

https://streamtape.com/v/kPzO40PR68COAGD/This_is_TOXIC_-_Battlefield_2042

or click the link from this page:

https://www.reddit.com/r/OfficialPeJePLAY/comments/s9n8ih/this_is_toxic_battlefield_2042/

**Comment by 89z** [comment]
OK it seems to be working now, but I don't see where you changed anything. Did you make a recent commit? If so, where is it?

**Comment by 89z** [comment]
This is still not fixed. Sometimes it works other times no.

if I copy paste this into new tab

https://streamtape.com/v/kPzO40PR68COAGD/This_is_TOXIC_-_Battlefield_2042

I get the redirect to streamtapeadblock.art

**Comment by 89z** [comment]
I am still having problem with streamtape

~~~
Please disable your adblocker!

The creator of this video does not allow adblock. Please disable and reload!
~~~

**Comment by 89z** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12307

**Comment by mapx-** [comment]
- the video above still working on my side
- did you test using only the default settings / lists ?
- go into dashboard, support tab, post here `Troubleshooting Information`

**Comment by mapx-** [comment]
see if this commit fix your issue
https://github.com/uBlockOrigin/uAssets/commit/b7a5fcd01b97618dcf969444b0ba7f719af80645
