### ISSUE TITLE
upshrink.com : anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12311]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://upshrink.com/DGNnT

### Describe the issue

This link redirects to another link where adblock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/158928687-cb695ff7-46a1-4326-b3bd-578402afeab7.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by Procyon-b** [comment]
Try these filters:
```
kiktu.com##div[style*="flex"]:has-text(/adblocker/i)
kiktu.com##body:style(overflow-y: auto !important;)
```

**Comment by Procyon-b** [comment]
A better filter:
```
kiktu.com##+js(aeld,load, style.overflow)
```
