### ISSUE TITLE
m.twfanti.com [Anti-Adblock]

### ISSUE THREAD

**Issue by jdck** [uBlockOrigin/uAssets#12312]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://m.twfanti.com/*****/read_*****.html`

For example: 
`https://m.twfanti.com/WanYaoShengZu1/read_1.html`
`https://m.twfanti.com/XiaoShiShuChenMiWangLuoZhong3/read_902.html`

### Describe the issue

The articles on this site has anti-adblockers, it will cause the article content to not be displayed.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16664309/158937549-3f2e099a-8785-479e-820c-f4b6a5b837ef.png)

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Google Chrome 99.0 (64-bit)

### Settings

- Default

**Comment by mapx-** [comment]
go into dashboard, support tab, post here the `Troubleshooting Information`

**Comment by jdck** [comment]
> go into dashboard, support tab, post here the `Troubleshooting Information`

uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 97239
  cosmetic: 51697
  scriptlet: 16661
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 5d.14h.2m
  default: 
    user-filters: 0-0, never
    CHN-0: 27971-87, 1d.10h.47m
    easylist: 64273-410, 1d.10h.46m
    easyprivacy: 26702-147, 1d.10h.44m
    plowe-0: 3671-807, 1d.20h.30m
    ublock-abuse: 72-0, 1d.10h.45m
    ublock-badware: 3972-84, 1d.10h.51m
    ublock-filters: 30355-156, 1d.10h.50m
    ublock-privacy: 200-2, 1d.10h.49m
    ublock-unbreak: 1739-42, 1d.10h.48m
    urlhaus-1: 8023-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 321 ms (selfie)
  maxAssetCacheWait: 348 ms

**Comment by jdck** [comment]
I just tried it and still have anti-adblockers without uBlock Origin installed.
Disabling [Privacy Badger](https://github.com/EFForg/privacybadger) + [Steven Black's unified hosts](https://github.com/StevenBlack/hosts) solved it. Sorry for my poor inspection 😅

**Comment by stephenhawk8054** [comment]
Please read carefully what you have ticked on

> ### I tried to reproduce the issue when...
> 
> - [X] uBO is the only extension

**Comment by jdck** [comment]
> Please read carefully what you have ticked on
> 
> > ### I tried to reproduce the issue when...
> > 
> > * [x]  uBO is the only extension

I understand. But technically hosts file is not a browser extension...

**Comment by stephenhawk8054** [comment]
> I understand. But technically hosts file is not a browser extension...

It will help others to narrow the cause of the issue. If you are just testing with uBO only and others still can't reproduce with your given configurations, we can investigate further by outside softwares that have the same functions as content blocker extensions (browser's built-in, domains' blocking methods like hosts/DNS or antivirus softwares, etc.)
