### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by FallCheetah7373** [uBlockOrigin/uAssets#12314]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aternos.org/server/`

### Category

detection

### Describe the issue

Quick fixes is on but still facing the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79404
  cosmetic: 41728
  scriptlet: 16572
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64342-10, now
    easyprivacy: 26702-121, now
    plowe-0: 3671-805, now
    ublock-abuse: 72-0, now
    ublock-badware: 3922-84, now
    ublock-filters: 30372-134, now
    ublock-privacy: 200-2, now
    ublock-unbreak: 1739-41, now
    urlhaus-1: 7950-1, now
    ublock-quick-fixes: 92-4, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1369 ms
  maxAssetCacheWait: 273 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    3lift.com: 2
    4dex.io: 2
    a-mo.net: 1
    adnxs.com: 2
    adsrvr.org: 1
    amazon-adsystem.com: 3
    casalemedia.com: 1
    cloudflareinsights.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    criteo.com: 1
    criteo.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    id5-sync.com: 1
    indexww.com: 1
    onetag-sys.com: 2
    openx.net: 2
    rubiconproject.com: 6
    smartadserver.com: 2
    snigelweb.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Can reproduce with a US IP. Its fixed now, try update the quick filter it works for me now

**Comment by FallCheetah7373** [comment]
> Can reproduce with a US IP. Its fixed now, try update the quick filter it works for me now

yes it is working now thanks
