### ISSUE TITLE
hackforums.net: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#12310]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hackforums.net/index.php`

### Category

ads

### Describe the issue

There are still these animated gif ads,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/58097612/158921327-f7e5cc6f-43d8-4046-86e9-6c9b248a3b5f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79442
  cosmetic: 41640
  scriptlet: 16508
  html: 628
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30914-29, 3h.54m
    ublock-badware: 3976-3, 3h.55m
    ublock-privacy: 204-0, 3h.53m
    ublock-abuse: 72-0, 3h.59m
    ublock-unbreak: 1751-0, 3h.58m
    easylist: 64339-599, 3h.57m
    easyprivacy: 26702-572, 3h.56m
    urlhaus-1: 7950-1, 3h.52m
    plowe-0: 3674-2, 9d.23h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1184 ms (selfie)
  maxAssetCacheWait: 505 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
Apparently the "FRA" regional list has a fix.
Try this filter:
```
||hackforums.net/uploads/mam/$image
```

**Comment by 3kh0** [comment]
Oh thanks @Procyon-b! It would be nice if this was in the default block list tho, why do they not add these?

**Comment by stephenhawk8054** [comment]
I can't access the site. Is this site restricted to any regions?

**Comment by 3kh0** [comment]
> I can't access the site. Is this site restricted to any regions?

It might be, some of the content on that site is about large scale DDOS attacks and stuff so I see why it might be blocked, but here in the US it is not blocked, which country are you in?

**Comment by Procyon-b** [comment]
> It would be nice if this was in the default block list tho, why do they not add these?

It's in the FRA list probably in relation to solving a problem with a "french" page.
I speak french and I visit as much sites in french as in english. That's why I have the list enabled, and that's how I noticed that by default I did not see the ad. I always fall back to only the default lists when testing, and I then saw the ad.

**Comment by mapx-** [comment]
@ryanbr
