### ISSUE TITLE
nsfw streamtapeadblock.art

### ISSUE THREAD

**Issue by wxolp** [uBlockOrigin/uAssets#12319]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

nsfw
`https://streamtapeadblock.art/v/JYAJJqde4Xco16`

### Describe the issue

With the latest filters, if you go to the page, everything is fine.

but if you refresh the page, you get blocked with this:

Please disable your adblocker!

The creator of this video does not allow adblock. Please disable and reload!

### uBlock Origin version

no

### Browser name and version

no

### Settings

no

**Comment by wxolp** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12301

**Comment by mapx-** [comment]
test this filter
`@@||streamtapeadblock.*^$ghide`

**Comment by wxolp** [comment]
I think that works! Thank you!
