### ISSUE TITLE
https://fc-lc.com : Anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12327]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://fc-lc.com/eOguQJzB`

### Describe the issue
1. Click on "click here to continue" button.
2. Solve the captcha.
3. The above link redirects to a https://webhostingpost.com/ link where the ablock is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/159106340-6620a742-b6f7-449d-8f25-0b097073d764.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 98.XX

### Settings

All default settings

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||webhostingpost.com^$ghide
```

**Comment by blazesprings** [comment]
It's working but when i click on the "click here to continue", a popup appears. Thanks

**Comment by Procyon-b** [comment]
You can try this:
```
webhostingpost.com##+js(nowoif)
```

**Comment by stephenhawk8054** [comment]
Can you post your `Troubleshooting Information` in [Support button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools)?

**Comment by mapx-** [comment]
both filters are already in uBO filters list

**Comment by Procyon-b** [comment]
That's weird. They weren't in the version of "uBlock filters" I had from yesterday (I just searched). But after an update they are there...
