### ISSUE TITLE
identity.tescobank.com: breakage

### ISSUE THREAD

**Issue by Photolunatic** [uBlockOrigin/uAssets#12324]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://identity.tescobank.com/pf/adapter2adapter.ping`

### Category

breakage

### Describe the issue

Cannot log in to the bank.
Works with chromium but I do not trust it. I want to use my Firefox.
Thanks, guys.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79552
  cosmetic: 41734
  scriptlet: 16542
  html: 627
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30971-29, 9m
    ublock-badware: 3926-3, 9m
    ublock-privacy: 204-0, 9m
    ublock-abuse: 72-0, 9m
    ublock-unbreak: 1749-0, 9m
    easylist: 64411-593, 9m
    easyprivacy: 26704-584, 9m
    urlhaus-1: 7983-0, 9m
    plowe-0: 3709-2, 9m
    ublock-quick-fixes: 99-4, 9m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1153 ms (selfie)
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    tescobank.com: 1
    ensighten.com: 2
```
</details>

**Comment by mapx-** [comment]
does this filter work ?

`@@||ensighten.com^*/Bootstrap.js$domain=tescobank.com`

**Comment by Photolunatic** [comment]
> does this filter work ?
> 
> `@@||ensighten.com^*/Bootstrap.js$domain=tescobank.com`

Thank you for your reply.
I added this to My Filters but the issue is still there.

**Comment by mapx-** [comment]
> Cannot log in to the bank.

Describe the issue, if you get an error .. what error.
I tried with fake credentials => I get something  like not a valid one

**Comment by Photolunatic** [comment]
> > Cannot log in to the bank.
> 
> Describe the issue, if you get an error .. what error. I tried with fake credentials => I got something like not a valid one

I had no error. 
1. They ask for a username. That's OK.
2. Then security random numbers. That's OK too.
3. Then TEXT to mobile verification. Passed.
4. Then they ask for a password. -> When confirmed, it was throwing me back to log in = step1

It is absolutely ridiculous system but well I need it.

It's OK now. I will update if that was an another extension or just the restart of FF was needed. Thanks a ton!

**Comment by Photolunatic** [comment]
It was the 'ClearURLs' extension.
[ClearURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/)
