### ISSUE TITLE
bloomberg.com: detection

### ISSUE THREAD

**Issue by rutus85** [uBlockOrigin/uAssets#12325]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bloomberg.com/news/articles/2022-03-17/apple-s-latest-iphone-sidelines-carriers-from-buying-process`

### Category

detection

### Describe the issue

ublock is not working in bloomberg homepage

thanks for your efforts

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://user-images.githubusercontent.com/99778042/159103911-fcc73cd5-6823-49fa-9076-8f9f565d7a88.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81214
  cosmetic: 47833
  scriptlet: 16553
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    KOR-1: 8152-0, 2d.13h.39m
    easylist: 64202-17, 2d.13h.38m
    easyprivacy: 26684-125, 2d.13h.37m
    plowe-0: 3671-807, 1d.15h.13m
    ublock-abuse: 72-0, 2d.13h.36m
    ublock-badware: 3972-84, 2d.13h.35m
    ublock-filters: 30343-141, 2d.13h.34m
    ublock-privacy: 200-2, 2d.13h.33m
    ublock-unbreak: 1728-42, 2d.13h.32m
    urlhaus-1: 7950-1, 1d.12h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 313 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    bloomberg.com: 4
    2mdn.net: 1
    adsafeprotected.com: 2
    bwbx.io: 1
    crwdcntrl.net: 1
    doubleclick.net: 3
    google.com: 2
    googlesyndication.com: 2
    googletagmanager.com: 2
    indexww.com: 1
    moatads.com: 2
    newrelic.com: 1
    scorecardresearch.com: 1
    youborafds01.com: 2
```
</details>

**Comment by Procyon-b** [comment]
This is not a detectiong. It's a paywall. You can have access by simply deleting the site's data (cookies and local storage)

**Comment by mapx-** [comment]
We don't fix paywalls.
