### ISSUE TITLE
bluemediafiles.com: detection

### ISSUE THREAD

**Issue by MaguzK** [uBlockOrigin/uAssets#12323]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://bluemediafiles.com/url-generator.php`

### Category

detection

### Describe the issue

Popup that detects adblock. Same as IGG-GAMES.com.
![image](https://user-images.githubusercontent.com/32487807/159082645-5de6ea6a-8c28-4253-8475-15860974d60b.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 83963
  cosmetic: 86950
  scriptlet: 21593
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50980-155, 2m
    fanboy-thirdparty_social: 69-0, 2m
    ublock-annoyances: 4370-152, 2m
  default: 
    user-filters: 1-0, never
    easylist: 64411-47, 2m
    easyprivacy: 26704-213, 2m
    plowe-0: 3709-818, 2m
    ublock-abuse: 72-0, 2m
    ublock-badware: 3922-84, 2m
    ublock-filters: 30388-460, 2m
    ublock-privacy: 200-2, 2m
    ublock-unbreak: 1738-45, 2m
    urlhaus-1: 7983-0, 2m
    ublock-quick-fixes: 99-7, 2m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1161 ms
  maxAssetCacheWait: 317 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
redirecting to igg-games

**Comment by mapx-** [comment]
test link
`http://bluemediafiles.com/url-generator.php?url=+Cuyh878jdyLlymoop7h/fmUXTCbL8wBjBwgtkQVA30=`

**Comment by mapx-** [comment]
@FaggotGay you should remove ABP and install uBO (which is fixing anti adblocking issues)
