### ISSUE TITLE
uptostream.com: breakage

### ISSUE THREAD

**Issue by Tugakit** [uBlockOrigin/uAssets#12321]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uptostream.com/`

### Category

breakage

### Describe the issue

When using uBO the video player doesnt start. it just shows the movie/video image/preview and nothing else.
I can click on the play button, but after that the only way to watch something is to disable uBO and refresh.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 95870
  cosmetic: 50566
  scriptlet: 16591
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    FRA-0: 26203-25, 3d.6h.14m
    easylist: 64157-55, 3d.6h.11m
    easyprivacy: 26680-439, 3d.6h.10m
    plowe-0: 3671-813, 3d.6h.9m
    ublock-abuse: 72-1, 3d.6h.7m
    ublock-badware: 3972-91, 3d.5h.37m
    ublock-filters: 30276-288, 3d.5h.36m
    ublock-privacy: 200-2, 3d.5h.35m
    ublock-unbreak: 1728-41, 3d.5h.34m
    urlhaus-1: 8023-0, 31m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 181 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    uptostream.com: 6
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
example ?

**Comment by okiehsch** [comment]
`https://uptostream.com/scxg960fa5o2`

**Comment by okiehsch** [comment]
Caused by 
````
*$document,csp=worker-src 'none',domain=123moviesgo.nl|300mbfilms.co|akvideo.stream|alltube.pl|alltube.tv|annuaire-bleu.net|arnaques-internet.info|atk-exotics.com|atkebony.com|bamekoohrang.ir|bigspeeds.com|bmovies123.me|centrum-dramy.pl|chemikino.ru|clipwatching.com|coinfaucet.eu|cracklists.com|crictime.com|crictime.is|crimedocumentary.com|deltabit.co|descargas2020.com|domnuleprimar.ro|dragonballzpolo.blogspot.com|eduardolegatti.blogspot.com|extratorrent.si|fileone.tv|filmovix.com|filmovix.net|filmovix.org|firstone.tv|firstonetv.eu|firstonetv.live|flashx.net|flashx.pw|flashx.tv|fmoviesgo.me|full-mp3.com|funtik.tv|genashowalter.com|gomovie123.me|hdvid.fun|hdvid.online|hdvid.tv|hospital.plus|ianimes.co|ianimes.org|ianimes.top|javbros.com|lewd.ninja|luckybitco.in|mobology.ir|movie4k.is|nahnoji.cz|neurozinzin.com|novator.az|onion.ly|onion.pet|openload.cc|ovid.tv|ovid.xyz|pebx.pl|peliculas24.me|pelisplus.online|pezeshk.us|powvideo.net|protect-link.biz|salon.com|seriesenlinea.net|shush.se|sickrage.ca|skytorrents.me|sorteosrd.com|studio100.it|szukajka.tv|tapemovie.com|theappguruz.com|thepiratebay.cr|thepiratebay.org|thepiratebay.se.net|thepiratebay.vip|thevideo.me|tomadivx.tv|torrentrapid.com|tubetitties.com|ukpass.co|unblocked.app|unblocked.gdn|unblocked.is|unblocked.lc|unblocked.vet|unblocked2.vip|unblockit.dev|uptobox.com|uptostream.com|vidop.icu|vidoza.co|vidoza.net|vidtod.com|vidtodo.com|vidup.io|void.cat|wallpoper.com|wearesaudis.net|yazilir.com
````
in ` AdGuard Français`.

**Comment by AdamWr** [comment]
It seems that this rule comes from `Liste FR`.
Does this rule fix it?
```
@@$csp=worker-src 'none',domain=uptostream.com
```

**Comment by mapx-** [comment]
@smed79

**Comment by okiehsch** [comment]
@AdamWr yes that works.

**Comment by okiehsch** [comment]
Thank you for the quick fix. 😉
