### ISSUE TITLE
youtube.com: adss

### ISSUE THREAD

**Issue by durali07** [uBlockOrigin/uAssets#12335]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=7XTabruB1BU&list=PLbSAmJpE_X5MBHyoPDLMmkc_g1eiemgw-&index=62`

### Category

ads

### Describe the issue

reklam

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81394
  cosmetic: 48424
  scriptlet: 16946
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 12-0, never
    TUR-0: 9198-144, 3d.20h.13m
    easylist: 64187-26, 3d.23h.49m
    easyprivacy: 26680-126, 3d.23h.48m
    plowe-0: 3674-806, 12d.21h.55m
    ublock-abuse: 72-0, 3d.23h.47m
    ublock-badware: 3972-84, 3d.23h.46m
    ublock-filters: 30313-149, 3d.23h.44m
    ublock-privacy: 200-2, 3d.23h.43m
    ublock-quick-fixes: 92-8, 19h.45m
    ublock-unbreak: 1728-42, 3d.23h.42m
    urlhaus-1: 8178-0, 56m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7474 ms (selfie)
  maxAssetCacheWait: 380 ms
popupPanel: 
  blocked: 137
  blockedDetails: 
    youtube.com: 119
    doubleclick.net: 4
    google.com: 1
    google.com.tr: 1
    googlesyndication.com: 3
    googlevideo.com: 9
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
