### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by Vitalik93** [uBlockOrigin/uAssets#12332]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/intl/ru/gmail/about/`

### Category

ads

### Describe the issue

Предупреждение об использовании куки.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок экрана 2022-03-19 075254](https://user-images.githubusercontent.com/34383288/159121018-edc05c6c-063a-4edb-a047-89ff5c88b53d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 67802
  cosmetic: 89133
  scriptlet: 21077
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 30188-30, 6m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1405-25, 6m
    ublock-annoyances: 4370-11, 6m
  default: 
    user-filters: 0-0, never
    RUS-0: 41846-138, 6m
    easylist: 64409-40, 6m
    ublock-abuse: 72-1, 6m
    ublock-badware: 3922-83, 6m
    ublock-filters: 30402-178, 6m
    ublock-privacy: 200-9, 6m
    ublock-quick-fixes: 99-4, 6m
    ublock-unbreak: 1736-21, 6m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
  uiTheme: light
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3789 ms
  maxAssetCacheWait: 1754 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
- Use english in uAssets, if you don't know english use google translate
- report annoyances at Easylist repository https://github.com/easylist/easylist/issues

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets#gdpr

IMO this not old cookie bar.
