### ISSUE TITLE
Zoom meeting link blocked by you

### ISSUE THREAD

**Issue by AllanBraun** [uBlockOrigin/uAssets#12334]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://r20.rs6.net/tn.jsp?f=001cxXev-N5MkRCZmW6QTyybfCC9t79ZWz9WaJUHcPa64_OAgj7c-vvt7GCnesrjqiRdhDgRY31-AI_DCSM2cXX-N_E8RfkybsBNiovO2J0g3duBSptVFKSL7Oav5WKwtV_yxPVYqqcLBXuniCgNtyiLwfv9jc4dyc3-uGO2PWC_kAW1qGhLB7FVf0wa0mGNA4r9cy1SBnrxLOwlqt64vCPZk7zgdLXdRT1e0u9eQL1i4I=&c=CoVFIkS8wQsv9KPs1CghMLU9HjIuna0tbIGbCF6vDPSBCaUREiKI9Q==&ch=zxSvdhMuKyThdMH84xgzMTesvIbaL0as48OLI7eGhWxkoC5md8iMcA==`

### Describe the issue

My temple's Torah study class was blocked by your extension

`https://r20.rs6.net/tn.jsp?f=001cxXev-N5MkRCZmW6QTyybfCC9t79ZWz9WaJUHcPa64_OAgj7c-vvt7GCnesrjqiRdhDgRY31-AI_DCSM2cXX-N_E8RfkybsBNiovO2J0g3duBSptVFKSL7Oav5WKwtV_yxPVYqqcLBXuniCgNtyiLwfv9jc4dyc3-uGO2PWC_kAW1qGhLB7FVf0wa0mGNA4r9cy1SBnrxLOwlqt64vCPZk7zgdLXdRT1e0u9eQL1i4I=&c=CoVFIkS8wQsv9KPs1CghMLU9HjIuna0tbIGbCF6vDPSBCaUREiKI9Q==&ch=zxSvdhMuKyThdMH84xgzMTesvIbaL0as48OLI7eGhWxkoC5md8iMcA==`

Chrome then says

uBLock Origin has prevented the following page from loading:

Because of the following filter:
||rs6.net^

Disable strict blocking for r20.rs6.net

I got to the meeting by manually going to zoom.us and entering the meeting ID and password

### Screenshot(s)

https://www.file-utilities.com/images/zoom.jpg

### uBlock Origin version

1.41.8

### Browser name and version

chrome  99.0.4844.74

### Settings

None

**Comment by iam-py-test** [comment]
In my opinion, this looks legit (click through tracking) and should not be unblocked.
You can just use a online service to bypass it:
`https://r20.rs6.net/tn.jsp?f=001cxXev-N5MkRCZmW6QTyybfCC9t79ZWz9WaJUHcPa64_OAgj7c-vvt7GCnesrjqiRdhDgRY31-AI_DCSM2cXX-N_E8RfkybsBNiovO2J0g3duBSptVFKSL7Oav5WKwtV_yxPVYqqcLBXuniCgNtyiLwfv9jc4dyc3-uGO2PWC_kAW1qGhLB7FVf0wa0mGNA4r9cy1SBnrxLOwlqt64vCPZk7zgdLXdRT1e0u9eQL1i4I=&c=CoVFIkS8wQsv9KPs1CghMLU9HjIuna0tbIGbCF6vDPSBCaUREiKI9Q==&ch=zxSvdhMuKyThdMH84xgzMTesvIbaL0as48OLI7eGhWxkoC5md8iMcA==` --> `https://us02web.zoom.us/j/89426884763?pwd=OVh6QzI2NStzSC95WjRUZW5yWkhiUT09#success`

If you are find with risking your IP, you can just use curl: `curl -Ls "https://r20.rs6.net/tn.jsp?f=001cxXev-N5MkRCZmW6QTyybfCC9t79ZWz9WaJUHcPa64_OAgj7c-vvt7GCnesrjqiRdhDgRY31-AI_DCSM2cXX-N_E8RfkybsBNiovO2J0g3duBSptVFKSL7Oav5WKwtV_yxPVYqqcLBXuniCgNtyiLwfv9jc4dyc3-uGO2PWC_kAW1qGhLB7FVf0wa0mGNA4r9cy1SBnrxLOwlqt64vCPZk7zgdLXdRT1e0u9eQL1i4I=&c=CoVFIkS8wQsv9KPs1CghMLU9HjIuna0tbIGbCF6vDPSBCaUREiKI9Q==&ch=zxSvdhMuKyThdMH84xgzMTesvIbaL0as48OLI7eGhWxkoC5md8iMcA=="` (look for the `og:url`)
![image](https://user-images.githubusercontent.com/84232764/159127158-b23e8e29-4863-4c91-9cee-7673f5934627.png)

**Comment by stephenhawk8054** [comment]
You can click on `Temporarily` button to load the page

**Comment by Yuki2718** [comment]
@AllanBraun How you got these links?

**Comment by iam-py-test** [comment]
> @AllanBraun How you got these links?

In the OP:
> My temple's Torah study class

**Comment by Yuki2718** [comment]
I wonder whether the links are provided by teacher/professor, if so why.

**Comment by iam-py-test** [comment]
> I wonder whether the links are provided by teacher/professor, if so why.

Probably from a calendar or invite from a online service (I have gotten ones like that).

**Comment by Yuki2718** [comment]
I need a fact, not a guess.

**Comment by okiehsch** [comment]
> I need a fact, not a guess.



````
Designing grant programs:  Some
institutions
and systems create their own grant programs
for improving courses, using internal funds
or external grants or gifts. That makes sense
to us for a variety of reasons. For example,
there's evidence suggesting that instructors
benefit from designing such proposals, even
if they're not all funded. But how should
such a program be designed? What might the
request for proposals look like?  What
criteria should you use to evaluate
proposals?  How should you work with the
faculty.  For some ideas, click
here 
(http://rs6.net/tn.jsp?e=001bq5Rvl88sP25m6Im82kdQkL5dvLgliglDR6iIBwrCsdi9-Xz
LfAg0GBM4pr5q805gVovyWf13-hrqiM33R-8LCaLKwU346agjx5GmeRApwH9Z2y1aBfw1hVMZy1u
7lE0jZfnodrqwPq0lui71JPvobPwJNcw_hKk).
````

**Comment by okiehsch** [comment]
It's a tracking link and a legitimate block.

**Comment by AllanBraun** [comment]
Link comes from the temple administrator

This is not a legitimate block.  It is a false hit

Please reopen ticket

All of the other Zoom links from my temple work are not blocked

**Comment by stephenhawk8054** [comment]
> Link comes from the temple administrator
> 
> This is not a legitimate block. It is a false hit
> 
> Please reopen ticket
> 
> All of the other Zoom links from my temple work are not blocked

The destination of that link is `https://us02web.zoom.us/j/89426884763?pwd=OVh6QzI2NStzSC95WjRUZW5yWkhiUT09#success`. You can ask the administrator to give zoom's direct link instead of the tracking link.

**Comment by okiehsch** [comment]
> This is not a legitimate block. It is a false hit


‘R20.rs6.net’ is used by Constant Contact in their e-mails.
The purpose is to track which link one clicks - in an email for example - and redirecting to an encoded URL.

**Comment by Yuki2718** [comment]
> 
> All of the other Zoom links from my temple work are not blocked

This rather attests the blockage is legitimate. My concern was whether a substantial numbers of Zoom links use this tracker, but apparently was overthinking.

**Comment by iam-py-test** [comment]
> > All of the other Zoom links from my temple work are not blocked
> 
> This rather attests the blockage is legitimate. My concern was whether a substantial numbers of Zoom links use this tracker, but apparently was overthinking.

Just FYI, I don't think normal Zoom invites use any link tracking
