### ISSUE TITLE
fof.se: breakage

### ISSUE THREAD

**Issue by LinAGKar** [uBlockOrigin/uAssets#12330]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fof.se/`

### Category

breakage

### Describe the issue

When ubo is active, nothing happens when you press the menu or search buttons at the top of the page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 82982
  cosmetic: 49698
  scriptlet: 16822
  html: 681
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 515-3, 1m
  default: 
    user-filters: 28-0, never
    ublock-filters: 31077-44, 1m
    ublock-badware: 3926-3, 1m
    ublock-privacy: 204-0, 1m
    ublock-abuse: 72-0, 1m
    ublock-unbreak: 1753-0, 1m
    adguard-mobile: 7363-153, 1m
    easylist: 64409-735, 1m
    easyprivacy: 26708-597, 1m
    urlhaus-1: 8023-0, 1m
    plowe-0: 3709-2, 1m
    SWE-1: 3998-2, 1m
    ublock-quick-fixes: 99-4, 1m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3351 ms (selfie)
  maxAssetCacheWait: 1178 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    fof.se: 2
    cookiebot.com: 1
    doubleclick.net: 1
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add
`@@||consent.cookiebot.com/uc.js$script,domain=fof.se`

@lassekongo83 
blocked by
`||cookiebot.com^$3p,domain=advokaten.se|bax-shop.se|circlek.se|etc.se|findroommate.se|fof.se|fokus.se|goteborgdirekt.se|itaboutdoor.se|kingsizemag.se|kurera.se|livetochdiabetes.se|mitti.se|ng.se|polistidningen.se|sakochliv.se|skeppsbrons.se|smartsenior.se|spraktidningen.se|swedroid.se|tankesport.se|tn.se|upplysning.se|vaningen.se|varden.se|vasterastidning.se|wesafe.se`

maybe it should be removed ?
however maybe other pages are broken

@ryanbr FA is breaking the page too
