### ISSUE TITLE
pornomovies.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1233]
URL(s) where the issue occurs

`https://www.pornomovies.com/2132908-angel-wicky-and-katarina-muti-get-fucked-after-a-nice-sweaty-workout-getting-the-hot-and-horny.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
