### ISSUE TITLE
actualite.lachainemeteo.com: detection

### ISSUE THREAD

**Issue by raphpitt** [uBlockOrigin/uAssets#12343]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://actualite.lachainemeteo.com/actualite-meteo/2022-03-20/tendance-a-4-semaines-meteo-jusqu-au-17-avril-50102`

### Category

detection

### Describe the issue

Pop-up anti-ubo

### Screenshot(s)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/34160362/159155061-5da59b92-3d91-415e-9afd-a0858ace661b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81060
  cosmetic: 46985
  scriptlet: 28412
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 21h.13m
    adguard-generic: 62752-1168, 23h.4m
    adguard-spyware: 26777-793, 11h.31m
  default: 
    user-filters: 32-0, never
    ublock-filters: 30398-3118, 23h.6m
    urlhaus-1: 8178-0, 11h.30m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 70 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3413 ms (selfie)
  maxAssetCacheWait: 1212 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
You have a highly customised setup, have you really checked that the issue is present with a default setup?
![image](https://user-images.githubusercontent.com/16838044/159155535-b70894da-e43b-46a0-af44-e274f863e721.png)

**Comment by mapx-** [comment]
Reset uBO to default settings / lists.
