### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by nexus2001** [uBlockOrigin/uAssets#12342]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=rStsx8SGsPc`

### Category

breakage

### Describe the issue

I don't know if it's because Google did something to YT algorithm, but whenever I open any video loading circle appeares and it's stuck there for certain time (possibly ads). I have to reload page twice or three times in order to watch video. It happens almost 90% of the time. Tested everything, but problem is within uBO. When disabled everyhting works fine...thus ads. But it loads video after ads without any problem.

I only have my filters that block overlay buttons on video (usually which appear on the end of the video). And I removed them (cut/paste for testing), but that is not it.

uBO worked properly about two weeks ago, maybe less.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/9553081/159144742-5222bf23-56a5-402c-a745-ef279d635045.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79815
  cosmetic: 42298
  scriptlet: 16542
  html: 627
listset (total-discarded, last updated): 
  default: 
    user-filters: 668-43, never
    ublock-filters: 30971-29, 1d.4h.6m
    ublock-badware: 3926-3, 1d.4h.6m
    ublock-privacy: 204-0, 1d.4h.6m
    ublock-abuse: 72-0, 1d.4h.6m
    ublock-unbreak: 1749-0, 1d.4h.6m
    easylist: 64411-594, 1d.4h.6m
    easyprivacy: 26704-584, 1d.4h.6m
    urlhaus-1: 8178-0, 4h.2m
    plowe-0: 3709-2, 1d.4h.6m
    ublock-quick-fixes: 108-4, 4h.1m
filterset (user): [array of 668 redacted]
trustedset: 
  added: [array of 36 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 329 ms (selfie)
  maxAssetCacheWait: 81 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    youtube.com: 10
    doubleclick.net: 2
    google.com: 2
    google.rs: 1
```
</details>

**Comment by mapx-** [comment]
- save your current configuration (backup it)

- reset uBO to default settings
- go into dashboard, filter lists tab, click "purge all caches", click "update now"

- disable any other addon in firefox
- don't use HOSTS file for blocking requests
- test again

If nothing helps reinstall uBO then update the filter lists & test again

**Comment by u-RraaLL** [comment]
Also reported on reddit https://www.reddit.com/r/uBlockOrigin/comments/th08bv/youtube_ads_via_buffering/

**Comment by nexus2001** [comment]
It seems that it didn't worked. But restored FF to default, picked up some things from old profile and it seems that it works for now. Maybe FF uodate xorrupted profile a bit.

**Comment by DANIEL120321** [comment]
> 

hey i have the same problem, can you explain how can i fix it ?
I have no idea how to do what you write above

**Comment by nexus2001** [comment]
Well, it started it again.

**Comment by DANIEL120321** [comment]
would be happy to know if you will find out any fix

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/wiki/Youtube-Issues

**Comment by DANIEL120321** [comment]
> https://github.com/easylist/easylist/wiki/Youtube-Issues

did all of that, still got the issue :(

**Comment by nexus2001** [comment]
Yep, issue is till going on. I even tested with Chrome at work and same simptoms occur.
