### ISSUE TITLE
animeflv.net [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1234]
URL(s) where the issue occurs

`https://animeflv.net/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
try
`|https://$script,third-party,xmlhttprequest,domain=animeflv.net|descargasnsn.com|jkanime.net,badfilter`

easylist spanish issue
@diaux

**Comment by KiLL4FuNK** [comment]
It works perfect

**Comment by KiLL4FuNK** [comment]
@BlazDT @Alex-302

anti adblock `https://animeflv.net/ver/48960/uma-musume-pretty-derby-tv-7`
it does not let show the comments
![](https://i.imgur.com/wwVV6Sg.png)

**Comment by BlazDT** [comment]
@KiLL4FuNK

With AdGuard's filters I can't reproduce, you may try this rule:

@@||animeflv.net/js/adsbygoogle.js

**Comment by KiLL4FuNK** [comment]
@BlazDT it does not work your filter is left blank

**Comment by BlazDT** [comment]
Disable EasyList Spanish. AdGuard's Spanish filter doesn't contain that bad rule.

**Comment by KiLL4FuNK** [comment]
@BlazDT but he does not connect months ago he disappeared from the earth @diaux

**Comment by KiLL4FuNK** [comment]
@mapx- you could add the filter until @diaux comes back is very necessary

|https://$script,third-party,xmlhttprequest,domain=animeflv.net|descargasnsn.com|jkanime.net,badfilter

**Comment by KiLL4FuNK** [comment]
`https://animeflv.net/ver/49856/jashinchan-dropkick-6`
I can not see comments

**Comment by mapx-** [comment]
I see the comments, eventually remove (if exist) the custom filters for the site

**Comment by KiLL4FuNK** [comment]
https://animeflv.net/ver/48960/uma-musume-pretty-derby-tv-7

I can not see the video

**Comment by mapx-** [comment]
fixed, ...completely wrong filter in easylist spanish, why on earth do they add untested filters ?

**Comment by KiLL4FuNK** [comment]
I can not see comments

`https://animeflv.net/ver/52306/hachigatsu-no-cinderella-nine-11`

**Comment by mapx-** [comment]
I cannot reproduce your issue.

**Comment by BlazDT** [comment]
Also not reproduced.
