### ISSUE TITLE
realmadrid.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#12348]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.realmadrid.com/noticias/2020/06/11/asi-van-las-obras-del-estadio-santiago-bernabeu-?vauto=1`

### Describe the issue

scroll down and open any video..

![Captura123](https://user-images.githubusercontent.com/33556647/159184049-7524f13a-3e1c-4ccb-9885-20f9cea8d585.PNG)

that arrows not working with uBO active.. and sometimes clicking 15-20 times works... but the audio adds to other videos and is annoying... it's like playing multiple videos.

### uBlock Origin version

1.41.8

### Browser name and version

Chrome - 99.0

### Settings

![Capturaqq](https://user-images.githubusercontent.com/33556647/159184165-d3a1f577-a000-4d47-8891-7839f9c49a53.PNG)

### Notes

possible solution:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=realmadrid.com`

ref: https://forums.lanik.us/viewtopic.php?f=103&t=42882

**Comment by okiehsch** [comment]
The breakage you report was caused by our redirection  but the issue you refernece in the lanik forum needs your exception, so I added it.
