### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by ericpremraju** [uBlockOrigin/uAssets#12359]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://9anime.id/watch/hanasaku-iroha-blossoms-for-tomorrow.80zn/ep-13`

### Describe the issue

While playing any video on the mycloud server(image below), keyboard shortcuts doesn't seem to work when the mouse is click in the video player. If the mouse click is done outside the video player, say the red area in the picture below, some keyboard shortcuts work. I have tried disabling just the uBlock list and this issue goes away. I have been facing this issue from the past two weeks and after seeing the closed issue page, there seems to be an update to the list with respect to 9anime exactly two weeks ago. The issue link is https://github.com/uBlockOrigin/uAssets/issues/12058

### Screenshot(s)

![image](https://user-images.githubusercontent.com/58141370/159250818-6f49daed-4b8f-4cdb-a5ce-09fb7d1355eb.png)
![image](https://user-images.githubusercontent.com/58141370/159250705-8bf3172a-0561-441f-8d51-5d6493ff3470.png)
![image](https://user-images.githubusercontent.com/58141370/159250730-3ac02bd4-189a-434e-b814-6bd1f6094b6f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 99
filterset (summary): 
  network: 80408
  cosmetic: 41769
  scriptlet: 16568
  html: 629
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30965-29, now
    ublock-badware: 3934-3, now
    ublock-privacy: 204-0, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1747-0, now
    easylist: 64441-538, now
    easyprivacy: 26710-584, now
    urlhaus-1: 8801-0, now
    plowe-0: 3707-2, now
    ublock-quick-fixes: 111-4, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2400 ms
  maxAssetCacheWait: 1924 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Which keyboard shortcuts did you use?

**Comment by ericpremraju** [comment]
> Which keyboard shortcuts did you use?

Fast-forward, rewind, play-pause, volume up and down. These can be changed through arrow keys and spacebar

**Comment by jsteave** [comment]
what kind of keyboard you are using?

**Comment by ericpremraju** [comment]
> what kind of keyboard you are using?

A USB keyboard.

**Comment by mapx-** [comment]
if you add

`mcloud.to#@#+js(aeld, , keyCode)`

does it fix your issue ?

**Comment by ericpremraju** [comment]
Yes, this fixed it. Thank you
