### ISSUE TITLE
baike.baidu.com: breakage

### ISSUE THREAD

**Issue by liuyasi** [uBlockOrigin/uAssets#12354]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://baike.baidu.com/series/%E7%94%9F%E6%AD%BB%E9%92%9F%E5%A3%B0/9025614?part=1&anchor=2`

### Category

breakage

### Describe the issue

使用easylist，第一集剧情简介前面的文字不能显示出来。不使用，打开网页过一阵，就会显示出来。

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium Mobile: 99
filterset (summary): 
  network: 69204
  cosmetic: 23018
  scriptlet: 16571
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
  default: 
    user-filters: 465-1, never
    CHN-0: 27792-1198, never
    adguard-mobile: 7371-31, 4m
    easyprivacy: 26705-109, 2d.7m
    plowe-0: 3715-583, never
    ublock-abuse: 72-0, 2d.15m
    ublock-badware: 3922-4, 2d.14m
    ublock-filters: 30321-264, never
    ublock-privacy: 200-2, 2d.9m
    ublock-quick-fixes: 109-4, 3h.12m
    ublock-unbreak: 1744-29, 2d.13m
    urlhaus-1: 8714-0, 3h.14m
filterset (user): [array of 465 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 33 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2046 ms (selfie)
  maxAssetCacheWait: 2644 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    baidu.com: 15
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/159218661-ea628601-5d92-414e-9ff5-772f33126be2.png)

- use english
- use uBO default settings
