### ISSUE TITLE
finerdesk.com: breakage

### ISSUE THREAD

**Issue by aglceballos76** [uBlockOrigin/uAssets#12369]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://finerdesk.com/`

### Category

breakage

### Describe the issue

The shopping cart of the website disappears when I click the checkout button and the purchase cannot be completed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80347
  cosmetic: 41685
  scriptlet: 16552
  html: 628
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30965-29, 3h.59m
    ublock-badware: 3934-3, 4h.3m
    ublock-privacy: 204-0, 4h.2m
    ublock-abuse: 72-0, 4h.5m
    ublock-unbreak: 1747-0, 4h.4m
    easylist: 64443-571, 4h.1m
    easyprivacy: 26710-572, 4h
    urlhaus-1: 8801-0, 3h.58m
    plowe-0: 3671-2, 7d.15h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1324 ms (selfie)
  maxAssetCacheWait: 345 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    googletagmanager.com: 3
    maps.googleapis.com: 3
    secureserver.net: 1
    secureservercdn.net: 1
    segment.com: 1
```
</details>

**Comment by krystian3w** [comment]
Bugged is Peter Lowe List: 

`@@||cdn.segment.com^$domain=finerdesk.com`

Maybe possible specifity to load only needed tracking files https://github.com/uBlockOrigin/uAssets/commit/41fec921f20845aaea88d93dd2aaf2d5d4e7ab4e.

**Comment by mapx-** [comment]
add

`@@||cdn.segment.com^$xhr,script,domain=finerdesk.com`

@ryanbr
