### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by jkocc** [uBlockOrigin/uAssets#12365]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/endretta`

### Category

ads

### Describe the issue

i still have left over ads 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80384
  cosmetic: 41770
  scriptlet: 16591
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64444-10, 1h.6m
    easyprivacy: 26710-121, 1h.5m
    plowe-0: 3707-817, 1h.4m
    ublock-abuse: 72-0, 1h.2m
    ublock-badware: 3930-84, 1h
    ublock-filters: 30383-114, 59m
    ublock-privacy: 200-2, 58m
    ublock-unbreak: 1736-41, 57m
    urlhaus-1: 8801-0, 56m
    ublock-quick-fixes: 111-4, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 822 ms
  maxAssetCacheWait: 161 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    twitch.tv: 2
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 5
    scorecardresearch.com: 5
```
</details>

**Comment by mapx-** [comment]
> i still have left over ads

screenshot ?
