### ISSUE TITLE
semicolonworld.com: [unknown]

### ISSUE THREAD

**Issue by aaly00** [uBlockOrigin/uAssets#12367]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.semicolonworld.com/question/56794/implement-an-interactive-shell-over-ssh-in-python-using-paramiko`

### Category

[unknown]

### Describe the issue

Website doesn't work without adblock disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11652379/159347478-b8952b46-b857-40d6-a1a6-b6f2a856a855.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 81056
  cosmetic: 41687
  scriptlet: 16566
  html: 630
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30974-29, 4h.15m
    ublock-badware: 3934-3, 4h.14m
    ublock-privacy: 204-0, 4h.13m
    ublock-abuse: 72-0, 4h.12m
    ublock-unbreak: 1747-0, 4h.10m
    easylist: 64444-538, 4h.9m
    easyprivacy: 26710-572, 4h.8m
    urlhaus-1: 9482-0, 4h.7m
    plowe-0: 3674-2, 13d.3h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 400 ms (selfie)
  maxAssetCacheWait: 200 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googlesyndication.com: 4
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Did you disable all other addons ?
