### ISSUE TITLE
shink.me [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1236]
URL(s) where the issue occurs

`http://shink.me/nVs7E`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Oh what to fill the Captcha

**Comment by xDarkARG** [comment]
ads @okiehsch

**Comment by okiehsch** [comment]
Can't reproduce
![unbenat](https://user-images.githubusercontent.com/16838044/35700948-bfed7854-0794-11e8-85df-1dfb46074c16.JPG)

**Comment by xDarkARG** [comment]
this link appears with the button
`http://wmedia.adk2x.com/imp?p=70721618&ct=html&ap=1303`

**Comment by okiehsch** [comment]
That is fixed by `##a[href*=".adk2x.com/"]`, which is already part of `EasyList`.

**Comment by xDarkARG** [comment]
it's weird I just put the filter this and then remove the filter and the button went @okiehsch

**Comment by okiehsch** [comment]
Well, `##a[href*=".adk2x.com/"]` should work out of the box unless you have the option
`Ignore generic cosmetic filters` enabled.


This is the default setup
![unbenannt](https://user-images.githubusercontent.com/16838044/35701892-b7cf98ca-0797-11e8-92e1-b8ca3fde1467.JPG)
