### ISSUE TITLE
Twitter filters ("Annoyances") don't work on their onion domain

### ISSUE THREAD

**Issue by FallenKhadgar** [uBlockOrigin/uAssets#12368]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/search?q=blah`

### Describe the issue

Twitter filters don't support their onion address, `https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion`, so Twitter is showing all the annoyances (`Don’t miss what’s happening` at the bottom, etc)

### Screenshot(s)

![twitter](https://user-images.githubusercontent.com/102084607/159355398-85743eb7-ffa8-4f03-9bdc-25337c2a72ea.png)

### uBlock Origin version

1.41.8

### Browser name and version

Tor Browser 11.0.9

### Settings

none

### Notes

Twitter onion address launched early March 2022: https://www.vice.com/en/article/v7dqxd/twitter-tor-onion-service-dark-web-version

**Comment by krystian3w** [comment]
In Poland still works:

`###layers span:has-text(/^(Bądź na bieżąco|Wykorzystaj cały potencjał Twittera)$/):matches-css(font-weight: 700):upward(4)`

**Comment by mapx-** [comment]
@FallenKhadgar 
do you know for the "normal" Twitter the filters fixing those annoyances ? which list ?

**Comment by Yuki2718** [comment]
Updated a few rules. Not sure about the rules in uBlock Annoyances.

**Comment by FallenKhadgar** [comment]
> @FallenKhadgar do you know for the "normal" Twitter the filters fixing those annoyances ? which list ?

The issue in the screencap is fixed in the clearnet domain by the following `adguard-annoyance` rule:

```
twitter.com#?##layers > div[class] > div[class] > div[class] > div[class]:has(> div[class] > div[class] > div[class] > div[class] > div[class] > a[href="/login"])
```

Adding the corresponding `twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion` rule fixes it for me.

**Comment by Yuki2718** [comment]
> 
> Adding the corresponding `twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion` rule fixes it for me.

Already added so the issue here will be solved if you force-update filter lists.

cc: @ryanbr

**Comment by FallenKhadgar** [comment]
> > Adding the corresponding `twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion` rule fixes it for me.
> 
> Already added so the issue here will be solved if you force-update filter lists.
> 
> cc: @ryanbr

It didn't as I don't use the AG filters.  Plain twitter is covered by `uBlock filters – Annoyances` and it still doesn't support the onion domain.

**Comment by krystian3w** [comment]
No need uBo syntax.

**Comment by Yuki2718** [comment]
> 
>　Plain twitter is covered by `uBlock filters – Annoyances` 

No, there was no rule for that in uBlock filters - Annoyances until the last addition by @mapx-
