### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by ohn0n0n0** [uBlockOrigin/uAssets#12363]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/6015976/159280853-9ce2e616-e3fe-49e2-ad42-769aaa38f67d.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80355
  cosmetic: 41743
  scriptlet: 16572
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64409-10, 2d.2h.11m
    easyprivacy: 26708-121, 2d.2h.10m
    plowe-0: 3709-817, 1d.5h.6m
    ublock-abuse: 72-0, 2d.2h.9m
    ublock-badware: 3922-84, 2d.1h.48m
    ublock-filters: 30372-136, 2d.1h.47m
    ublock-privacy: 200-2, 2d.1h.46m
    ublock-unbreak: 1738-41, 2d.1h.45m
    urlhaus-1: 8801-0, 1h.41m
    ublock-quick-fixes: 111-4, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    linkneverdie.net: 1
    addthis.com: 1
    cachefly.net: 1
    dooloust.net: 1
    facebook.com: 1
    google-analytics.com: 1
    kolkwi4tzicraamabilis.com: 1
    optad360.io: 2
    trvdp.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed in `VIE: ABPVN List`, can you enable that list?
