### ISSUE TITLE
namu.wiki: breakage

### ISSUE THREAD

**Issue by mohand0603** [uBlockOrigin/uAssets#12374]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://namu.wiki/`

### Category

breakage

### Describe the issue

can't see article

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82238
  cosmetic: 47952
  scriptlet: 16600
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 15-0, never
    KOR-1: 8152-0, 1d.2h.55m
    easylist: 64441-17, 1d.2h.54m
    easyprivacy: 26710-125, 1d.2h.53m
    plowe-0: 3671-807, 6d.2h.11m
    ublock-abuse: 72-0, 1d.2h.47m
    ublock-badware: 3930-84, 1d.2h.45m
    ublock-filters: 30433-138, 1d.2h.44m
    ublock-privacy: 200-2, 1d.2h.43m
    ublock-unbreak: 1735-41, 1d.2h.42m
    urlhaus-1: 8801-0, 2h.39m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 528 ms (selfie)
  maxAssetCacheWait: 212 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 1
    googlesyndication.com: 3
```
</details>

**Comment by Procyon-b** [comment]
Verify that it's not one of your filters. You can disable them by going to the "Filter lists" tab, unchecking "My filters" and click "Apply changes". Then reload the website.

**Comment by keystore2077** [comment]
I have same issue. here's a screenshots.

![1](https://user-images.githubusercontent.com/63623597/159598869-ca762166-85c1-4db2-a85e-cb0a96134e26.PNG)

![2](https://user-images.githubusercontent.com/63623597/159598873-401ab238-dc98-4f35-8205-6e0e04226407.PNG)
These are screenshots when uBO is on and off.

![3](https://user-images.githubusercontent.com/63623597/159598874-46ffd888-fadc-45be-be4b-f4af5dce01db.png)
And there are ads that cannot be turned off on pages except main page.

**Comment by Procyon-b** [comment]
I don't read korean (as most here, I presume). Can you give us a url where the problem occurs?

**Comment by BasixKOR** [comment]
I was able to confirm this behaviour as well but it seems like it's an issue of https://github.com/yous/YousList as the issue only seems to occur with YousList enabled.

**Comment by keystore2077** [comment]
Main page url is https://namu.wiki/
And examples of blocked page are https://namu.wiki/w/The%20Angry%20Video%20Game%20Nerd https://namu.wiki/w/Fall%20Guys:%20Ultimate%20Knockout

But I'm not sure if the same issue occurs on the same page on other people's devices. This page(https://namu.wiki/w/Europa%20Universalis%20IV) is normally displayed on my PC, but blocked on moblie. And after trying a few times, the same page is blocked or not blocked.

If you need another example, you can also click any item on the right that says Recent Changes(최근 변경).

**Comment by Procyon-b** [comment]
I can't reproduce either.

**Comment by OctopusET** [comment]
It seems blocking adblock randomly. Site works with ublock sometimes, but it sometimes doesn't show any articles.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12374#issuecomment-1076739620 - More due need use fixes faster than 4 days later:

https://github.com/uBlockOrigin/uAssets/issues/12953

Often people lay about forced pruged cache.

**Comment by MDelusional** [comment]
> I have same issue. here's a screenshots.
> 
> ![1](https://user-images.githubusercontent.com/63623597/159598869-ca762166-85c1-4db2-a85e-cb0a96134e26.PNG)
> 
> ![2](https://user-images.githubusercontent.com/63623597/159598873-401ab238-dc98-4f35-8205-6e0e04226407.PNG) These are screenshots when uBO is on and off.
> 
> ![3](https://user-images.githubusercontent.com/63623597/159598874-46ffd888-fadc-45be-be4b-f4af5dce01db.png) And there are ads that cannot be turned off on pages except main page.

I have this same Issue, but reproducable only on chrome/edge (Firefox doesn't reproduce the issue). Same with the screenshot above.

**Comment by piquark6046** [comment]
@MDelusional Did you force-update the filter lists?

**Comment by MDelusional** [comment]
@piquark6046  No, and that resolved the issue. Sorry.
