### ISSUE TITLE
readcomiconline.li: popups

### ISSUE THREAD

**Issue by Djunna** [uBlockOrigin/uAssets#12370]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://readcomiconline.li/Comic/Jimmy-Corrigan-The-Smartest-Kid-on-Earth-2000/TPB-Part-1?id=179204`

### Category

popups

### Describe the issue

Ads for popup blockers open in a new tab after every other page turn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80432
  cosmetic: 41849
  scriptlet: 16605
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64535-10, 31m
    easyprivacy: 26711-121, 31m
    plowe-0: 3690-810, 31m
    ublock-abuse: 72-0, 31m
    ublock-badware: 3925-84, 31m
    ublock-filters: 30442-82, 31m
    ublock-privacy: 201-2, 31m
    ublock-unbreak: 1736-41, 31m
    urlhaus-1: 8770-0, 31m
    ublock-quick-fixes: 114-4, 31m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1188 ms
  maxAssetCacheWait: 226 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adro.pro: 1
    alklinker.com: 1
    chaturbate.com: 1
    juicyads.com: 1
    prtrackings.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Your blocked domains look different to what I tested. Do you use any other extensions?
