### ISSUE TITLE
atomtt.com: breakage

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#12372]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://atomtt.com/t_download/171144/resident-alien---temporada-2/`

### Category

breakage

### Describe the issue

atomixhq.link now redirects the content to atomtt.com. if you use ublock, links doesn't work. if you disable it links work, you get tons of ads, but when you click on links they open more ads on popups which are blocked by ublock too.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 84200
  cosmetic: 46461
  scriptlet: 16806
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64544-10, 3m
    easyprivacy: 26713-121, 3m
    plowe-0: 3690-810, 3m
    spa-0: 3824-32, 3m
    spa-1: 4277-166, 3m
    ublock-abuse: 72-0, 3m
    ublock-badware: 3925-84, 3m
    ublock-filters: 30460-139, 3m
    ublock-privacy: 202-2, 3m
    ublock-unbreak: 1736-42, 3m
    urlhaus-1: 9482-0, 3m
    ublock-quick-fixes: 114-4, never
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 965 ms (selfie)
  maxAssetCacheWait: 302 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    d2q9y3krdwohfj.cloudfront.net: 1
    jawholeminable.com: 1
    mulleysnutmeg.com: 1
    unnist.com: 1
    velocitycdn.com: 1
```
</details>

**Comment by mapx-** [comment]
>  if you use ublock, links doesn't work

these ones are working (I fixed the anti adb on `acorta-enlace.com`)
`DESCARGAR AHORA` => `AHORA YA PUEDES DESCARGAR TU ARCHIVO GRATIS` => `acorta-enlace.com`

**Comment by helpman** [comment]
yet I'm trying to use the site, and when ATOMTT is accessed and there's the
button to access the content, it returns to the last page instead of
loading the content. if you disable ublock it shows lots of ads, and when
clicking the link to access the content it opens ads on popup sites like
this site https://atomtt.com/t_download/171190/la-edad-dorada---temporada-1/
