### ISSUE TITLE
namu.wiki: detection

### ISSUE THREAD

**Issue by dlrnert** [uBlockOrigin/uAssets#12376]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

'https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8'

### Category

detection

### Describe the issue

I can't see the website with ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82919
  cosmetic: 48095
  scriptlet: 16611
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    KOR-1: 8152-0, 2h.6m
    easylist: 64409-17, 3d.1h.1m
    easyprivacy: 26709-125, 3d.1h
    plowe-0: 3671-807, 8d.5h.23m
    ublock-abuse: 72-0, 3d.1h.3m
    ublock-badware: 3925-84, 2h.4m
    ublock-filters: 30488-83, 2h.5m
    ublock-privacy: 200-2, 4d.2h.12m
    ublock-quick-fixes: 114-4, 6h.7m
    ublock-unbreak: 1738-41, 3d.1h.2m
    urlhaus-1: 9466-0, 13h.36m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 397 ms (selfie)
  maxAssetCacheWait: 219 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
> I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

I wonder how you did that, it's literally the first open issue.
