### ISSUE TITLE
exey.io: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#12373]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://exey.io/OcsNNfHo`

### Category

detection

### Describe the issue

this website previously didn't detect uBlock, but recently it can detect uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 85351
  cosmetic: 46271
  scriptlet: 16604
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.17h.44m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 8-0, never
    IDN-0: 8917-0, 22h.42m
    easylist: 64443-24, 22h.40m
    easyprivacy: 26710-123, 22h.39m
    plowe-0: 3671-805, 8d.1h.19m
    ublock-abuse: 72-0, 4d.22h.55m
    ublock-badware: 3925-84, 1h.45m
    ublock-filters: 30383-115, 22h.43m
    ublock-privacy: 200-2, 4d.22h.59m
    ublock-unbreak: 1735-42, 22h.41m
    urlhaus-1: 9513-0, 1h.44m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 23 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 543 ms (selfie)
  maxAssetCacheWait: 439 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    dba9ytko5p72r.cloudfront.net: 2
    exe.io: 1
    forfrogadiertor.com: 1
    googletagmanager.com: 1
    hbcdn.net: 1
    s3.us-east-1.amazonaws.com: 1
    varechphugoid.com: 1
    vdo.ai: 1
```
</details>

**Comment by mapx-** [comment]
update all lists, don't use other blocking extensions, test again
