### ISSUE TITLE
akorto.eu [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1237]
URL(s) where the issue occurs

`http://akorto.eu/3KKMV3s`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2dce118af33684dd54017a6b15ba2f57c17c4d05
