### ISSUE TITLE
themuse.com: ads

### ISSUE THREAD

**Issue by nghiabros** [uBlockOrigin/uAssets#12371]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.themuse.com/advice/great-student-struggle-working-world`

### Category

ads

### Describe the issue

twitter post

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://user-images.githubusercontent.com/43260081/159434555-39cc8d25-f2c6-46c7-9212-b27683fce89b.png

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 50783
  cosmetic: 67276
  scriptlet: 19885
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-badware: null
    ublock-privacy: null
  added: 
    VIE-1: 2027-0, 4h.41m
    fanboy-cookiemonster: 25520-45, 4h.41m
    ublock-annoyances: 4360-113, 4h.41m
  default: 
    user-filters: 0-0, never
    easylist: 64540-22, 4h.41m
    ublock-abuse: 72-0, 4h.41m
    ublock-filters: 30443-97, 4h.41m
    ublock-unbreak: 1736-13, 4h.41m
    urlhaus-1: 9482-0, 4h.41m
    ublock-quick-fixes: 114-4, 4h.41m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 922 ms (selfie)
  maxAssetCacheWait: 505 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 2
    googleadservices.com: 1
    linkedin.com: 1
    mouseflow.com: 1
    mpwdigital.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`themuse.com##center:has(iframe)`

@ryanbr

**Comment by nghiabros** [comment]
``listset (total-discarded, last updated): 
  added: 
    VIE-1: 2023-0, 2m
    fanboy-annoyance: 65205-183, 2m
    fanboy-cookiemonster: 25574-25046, 2m
    fanboy-social: 23244-23244, 2m
    ublock-annoyances: 4360-122, 2m
  default: 
    user-filters: 0-0, never
    easylist: 64545-22, 2m
    easyprivacy: 26713-126, 2m
    plowe-0: 3690-810, 2m
    ublock-abuse: 72-0, 2m
    ublock-badware: 3925-84, 2m
    ublock-filters: 30488-110, 2m
    ublock-privacy: 202-10, 2m
    ublock-unbreak: 1736-44, 2m
    urlhaus-1: 9482-0, 2m
    ublock-quick-fixes: 114-4, 2m

**Comment by mapx-** [comment]
use the filter I indicated above, the maintainer of EL didn't fix it

**Comment by nghiabros** [comment]
> use the filter I indicated above, the maintainer of EL didn't fix it

thanks for your help :D
