### ISSUE TITLE
urlcero.us [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1238]
URL(s) where the issue occurs

`http://urlcero.us/40k29qb`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Anti-Adblock @okiehsch

**Comment by KiLL4FuNK** [comment]
Fake Button
