### ISSUE TITLE
youtube.com: nuisance, certain videos crashed

### ISSUE THREAD

**Issue by jamesfernandowisata** [uBlockOrigin/uAssets#12388]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

nuisance

### Describe the issue

a small portion videos will crash on youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80115
  cosmetic: 41743
  scriptlet: 16593
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1h.29m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 64415-10, 2d.20h
    easyprivacy: 26708-121, 2d.20h.6m
    plowe-0: 3671-805, 7d.6h.53m
    ublock-abuse: 72-0, 2d.20h.5m
    ublock-badware: 3922-84, 2d.20h.4m
    ublock-filters: 30413-136, 2d.20h.3m
    ublock-privacy: 200-2, 2d.20h.2m
    ublock-quick-fixes: 111-4, 20h.18m
    ublock-unbreak: 1736-41, 2d.20h.1m
    urlhaus-1: 8562-0, 6h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 379 ms (selfie)
  maxAssetCacheWait: 267 ms
popupPanel: 
  blocked: 176
  blockedDetails: 
    youtube.com: 138
    doubleclick.net: 4
    google.co.id: 1
    google.com: 19
    googlevideo.com: 13
    ytimg.com: 1
```
</details>

**Comment by okiehsch** [comment]
> a small portion videos will crash on youtube

Can you be more specific or do you mean that random videos crash sometimes?
If so why do you think it is caused by uBO?

**Comment by jamesfernandowisata** [comment]
Hello, thank you for respondingRandom videos throughout 9gag and YouTube sometime crash i.e. the pic I uploaded, the video that was crashed will stay crashed even if I refresh and reset my cache . I have contacted the YT troubleshoot and 9gag troubleshoot with no respond or update so far, I simply don’t know who to pinpoint at this point so I am guessing it has problem with the overlay. I have used AdBlock before and it breaks certain website similar to this and when I change to ublock the problem is gone. I hope the current issue stems from my PC being old alone Sent from Mail for Windows From: okiehschSent: Wednesday, March 23, 2022 3:45 PMTo: uBlockOrigin/uAssetsCc: James Fernando; AuthorSubject: Re: [uBlockOrigin/uAssets] youtube.com: nuisance, certain videos crashed (Issue #12388) a small portion videos will crash on youtubeCan you be more specific or do you mean that random videos crash sometimes?If so why do you think it is caused by uBO?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
