### ISSUE TITLE
myanimelist.net: breakage

### ISSUE THREAD

**Issue by kah0922** [uBlockOrigin/uAssets#12383]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myanimelist.net/`

### Category

breakage

### Describe the issue

On mobile (I have forged a Chrome for Android UA here, though I have reproduced this on FF for Android), MyAnimeList shows an overlay with a cookie acceptance banner. Until you accept the cookie policy, you cannot interact with the web page. When EasyList Cookie is enabled, the acceptance banner is hidden, but the overlay remains, locking you out from the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With EasyList Cookie enabled
![image](https://user-images.githubusercontent.com/9474213/159605579-0f4fabf3-86ed-47e9-aefb-0bbdb0134978.png)

Without EasyList Cookie enabled
![image](https://user-images.githubusercontent.com/9474213/159605601-1c112e08-b653-4da8-9b28-ce7d5707aa01.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b4
Firefox: 100
filterset (summary): 
  network: 81804
  cosmetic: 66385
  scriptlet: 17140
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31057-36, 9m
    ublock-badware: 3929-3, 9m
    ublock-privacy: 207-0, 9m
    ublock-abuse: 72-0, 9m
    ublock-unbreak: 1747-0, 9m
    ublock-quick-fixes: 114-4, 9m
    easylist: 64595-544, 9m
    easyprivacy: 26715-579, 9m
    urlhaus-1: 8582-0, 9m
    fanboy-cookiemonster: 26625-47, now
    plowe-0: 3690-2, 9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 350 ms
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    consensu.org: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    sascdn.com: 1
    smartadserver.com: 1
```
</details>

**Comment by mapx-** [comment]
for overlay + some unblocked ads => test:

```
myanimelist.net##.modal-content-overlay
myanimelist.net###M_320x50_1_iframe
myanimelist.net###M_300x250_1_iframe
```

@ryanbr
