### ISSUE TITLE
idnes.cz: ads

### ISSUE THREAD

**Issue by tinukedaya** [uBlockOrigin/uAssets#12386]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.idnes.cz/`

### Category

ads

### Describe the issue

The big background adds show up as of today. And also the adds in front of videos. it used to successfully block those out till yesterday.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19891532/159636545-800810a2-1fc4-4e2b-9802-8f453d198b9f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80371
  cosmetic: 42101
  scriptlet: 16848
  html: 630
listset (total-discarded, last updated): 
  added: 
    CZE-0: 833-0, 21h.43m
  default: 
    user-filters: 3-0, never
    ublock-filters: 30974-29, 1d.14h.59m
    ublock-badware: 3934-3, 1d.15h.2m
    ublock-privacy: 204-0, 5d.18h.36m
    ublock-abuse: 72-0, 5d.18h.35m
    ublock-unbreak: 1747-0, 1d.15h.1m
    easylist: 64444-540, 1d.15h
    easyprivacy: 26710-577, 1d.14h.58m
    urlhaus-1: 8562-0, 9h.42m
    plowe-0: 3671-2, 9d.21h.30m
    ublock-quick-fixes: 110-4, 9h.41m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3095 ms (selfie)
  maxAssetCacheWait: 2017 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    criteo.net: 4
    gemius.pl: 1
    google-analytics.com: 1
    seznam.cz: 1
```
</details>

**Comment by mapx-** [comment]
tested with CZE ip, no such big background ads

**Comment by tinukedaya** [comment]
Yeah it's weird... Back to normal now... NVM...

**Comment by tinukedaya** [comment]
I don't know, but today morning it is again the same. the big BG adds are back...

**Comment by mapx-** [comment]
lot of ads too

test

```
idnes.cz##[style*="background-repeat"]
idnes.cz##[style*="z-index:0"]:remove()
idnes.cz##span:matches-css(background-image:/url.*//www.idnes.cz/):upward(2)
idnes.cz##+js(nostif, /Adform|didomi|adblock|forEach/)
```

**Comment by tinukedaya** [comment]
> lot of ads too
> 
> test
> 
> ```
> idnes.cz##[style*="background-repeat"]
> idnes.cz##[style*="z-index:0"]:remove()
> idnes.cz##span:matches-css(background-image:/url.*//www.idnes.cz/):upward(2)
> idnes.cz##+js(nostif, /Adform|didomi|adblock|forEach/)
> ```

Adding this to My Filters helps.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d9a5e6ccef019528ad9fe1841f120e0c22a36ae2
