### ISSUE TITLE
tvanouvelles.ca: detection

### ISSUE THREAD

**Issue by thekingarthur1** [uBlockOrigin/uAssets#12393]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tvanouvelles.ca/`

### Category

detection

### Describe the issue

Web page detects uBlock Origin and prevents navigation

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/97759020/159710266-c7f74127-c33a-453a-95a5-158850f23a23.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80195
  cosmetic: 41789
  scriptlet: 16606
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 64544-10, 1d.1h.39m
    easyprivacy: 26713-121, 1d.1h.38m
    plowe-0: 3672-805, 11d.23h.56m
    ublock-abuse: 72-0, 9d.14h.59m
    ublock-badware: 3930-84, 2d.13h.47m
    ublock-filters: 30460-82, 1d.1h.41m
    ublock-privacy: 200-2, 2d.13h.46m
    ublock-unbreak: 1736-41, 1d.1h.40m
    urlhaus-1: 8562-0, 21h.43m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 209 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    brightcove.com: 5
    doubleclick.net: 2
    go-mpulse.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by TNTUP** [comment]
Chimming in this issue report, affects all Quebecor's Media websites such as journaldemontreal.com, seems to load the same js on the same domain "cheezwiz"

**Comment by mapx-** [comment]
some other pages ?

**Comment by mapx-** [comment]
ok, I'll add

`||quebecormedia.com/infojdem/lib/cheezwhiz/$script`

**Comment by TNTUP** [comment]
from what I've noticed, journaldemontreal.com shows the same warning as tvanouvelles.ca, both owned by Quebecor Media. There's a JS which might be useful to see what domains it uses

Edit: Should do the trick, thanks Mapx!
