### ISSUE TITLE
cifraclub.com.br: breakage

### ISSUE THREAD

**Issue by JooJKappa** [uBlockOrigin/uAssets#12397]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cifraclub.com.br/`

### Category

breakage

### Describe the issue

the site simply doesn't work when ublock is active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80453
  cosmetic: 44644
  scriptlet: 16819
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  default: 
    user-filters: 0-0, never
    easylist: 64617-10, 3m
    easyprivacy: 26715-121, 2m
    plowe-0: 3691-810, 2m
    spa-1: 4278-78, 2m
    ublock-abuse: 72-0, 2m
    ublock-badware: 3941-84, 2m
    ublock-filters: 30569-121, 2m
    ublock-privacy: 202-2, 2m
    ublock-quick-fixes: 117-4, 2m
    ublock-unbreak: 1736-42, 2m
    urlhaus-1: 7406-0, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 232 ms (selfie)
  maxAssetCacheWait: 260 ms
popupPanel: 
  blocked: 2
  no-scripting: true
  blockedDetails: 
    cifraclub.com.br: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
What is broken ? steps to reproduce it ? needing account ?

**Comment by krystian3w** [comment]
And use translator if you don't like write in English to reduce mistunderstand you.

https://www.deepl.com/pt-PT/translator

**Comment by MasterKia** [comment]
> * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> * [x]  I did not answer truthfully to **all** the above checkpoints

> ```yaml
>   added: 
>     https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
> ```

This list that you added hasn't been updated for the last 6 years, you should **remove** it.

**Comment by krystian3w** [comment]
That list is no problem, link is blacklisted so show 0 used filters with uBo 1.30.0+. As long user don't workarounds (fake parameter, CDN/mirror/join to own list, latest direct url).
