### ISSUE TITLE
toolss.net: detection

### ISSUE THREAD

**Issue by camille-bigot** [uBlockOrigin/uAssets#12391]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://toolss.net/`

### Category

detection

### Describe the issue

Using Ublock on Firefox without any other add-ons. Website detected adblock. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 97
filterset (summary): 
  network: 81576
  cosmetic: 23726
  scriptlet: 16600
  html: 633
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31138-247, 7h.11m
    ublock-badware: 3929-3, 7h.10m
    ublock-privacy: 204-1, 8d.9h.13m
    ublock-abuse: 72-0, 8d.9h.12m
    ublock-unbreak: 1753-0, 10m
    adguard-mobile: 7384-186, 7m
    easylist: 64602-24338, 9m
    easyprivacy: 26716-580, 8m
    urlhaus-1: 8466-0, 7h.8m
    plowe-0: 3675-2, 12d.12h.6m
    ublock-quick-fixes: 115-4, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 253 ms (selfie)
  maxAssetCacheWait: 235 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 4
```
</details>

**Comment by camille-bigot** [comment]
Sorry, it's an error. Please delete the issue.

**Comment by okiehsch** [comment]
Well, I can reproduce, so...

**Comment by camille-bigot** [comment]
Is this fixed?  Since you again reclosed it.

**Comment by okiehsch** [comment]
Yes, I closed it via a commit. 
![image](https://user-images.githubusercontent.com/16838044/159688811-db621671-cf80-426b-9693-9589d7cce395.png)

If you update your filter list the site should work without issue.
