### ISSUE TITLE
sss.fi: detection

### ISSUE THREAD

**Issue by krisu5** [uBlockOrigin/uAssets#12396]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sss.fi/2022/03/kallionkieleke-sortui-asuinalueelle-halikossa-kivet-murjoivat-saunarakennuksen-ja-auton/`

### Category

detection

### Describe the issue

Page shows `section` box with the text:

> **Blocked because of Ad Blocker**
> It seems that you are using some ad blocking software which is preventing the page from fully loading. Please whitelist this website or disable ad blocking software.

It's in fixed position and closes when clicked in anywhere on the page. It might not load at the first page load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-03-23 at 19-10-59 Kallionkieleke sortui asuinalueelle Halikossa – kivet murjoivat saunarakennuksen ja auton](https://user-images.githubusercontent.com/3540275/159757498-6c0e9fba-3964-4fb2-9d80-0cf18f7660da.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b4
Firefox: 98
filterset (summary): 
  network: 134118
  cosmetic: 140935
  scriptlet: 51679
  html: 640
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 884-6, 1d.1h.6m
    https://gist.githubusercontent.com/gwarser/2d4b5dcd32b0d219e0ae65b43eb1f53d/raw/disqus%2520ctl%2520filter%2520list.txt: 6-0, 15d.20h.30m
    https://paulgb.github.io/BarbBlock/blacklists/ublock-origin.txt: 550-6, 2d.17h.18m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25424-133, 2d.17h.17m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-0, 1d.20h.29m
    https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/google_duckduckgo/global.txt: 1008-3, 1d.1h.3m
    adguard-generic: 62797-5428, 2d.4h.44m
    adguard-spyware: 27163-959, 2d.4h.42m
    adguard-annoyance: 50997-3169, 2d.4h.39m
    fanboy-thirdparty_social: 68-0, 5d.1h.8m
    fanboy-cookiemonster: 24801-153, 5d.1h.7m
    ublock-annoyances: 4371-6, 2d.4h.38m
    FIN-0: 1558-2, 2d.4h.37m
    adguard-spyware-url: 521-3, 2d.4h.36m
  default: 
    user-filters: 232-0, never
    ublock-filters: 31008-3097, 2d.4h.49m
    ublock-badware: 3934-3, 2d.4h.48m
    ublock-privacy: 204-0, 2d.4h.47m
    ublock-abuse: 72-4, 2d.4h.46m
    ublock-unbreak: 1747-0, 2d.4h.45m
    easylist: 64443-648, 2d.4h.43m
    easyprivacy: 26710-11058, 2d.4h.41m
    urlhaus-1: 8562-0, 1d.1h.7m
    plowe-0: 3671-366, 10d.1h.27m
    block-lan: 43-0, 1d.1h.8m
    curben-phishing: 10393-1, 1d.1h.5m
    curben-pup: 305-0, 1d.1h.4m
    ublock-quick-fixes: 110-4, 17h.2m
filterset (user): [array of 227 redacted]
switchRuleset: 
  added: [array of 8 redacted]
hostRuleset: 
  added: [array of 563 redacted]
urlRuleset: 
  added: [array of 106 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1577 ms (selfie)
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    sss.fi: 4
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    gravito.net: 1
    media.net: 1
    sascdn.com: 3
    scorecardresearch.com: 1
    userreport.com: 2
```
</details>

**Comment by mapx-** [comment]
working filters:

`sss.fi##+js(nostif, ai_)`

or more general for this `ad-inserter` pattern 

```
||media.net^$object,redirect-rule=noopjs
||google-analytics.com^$object,redirect-rule=noopjs
||doubleclick.net^$object,redirect-rule=noopjs
*###banner-advert-container:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
*##.ad-inserter:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
*##.SponsorAds:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
```

thoughts ? @Yuki2718 @okiehsch @stephenhawk8054

**Comment by Yuki2718** [comment]
Maybe
```
#@#.ad-inserter
#@#.SponsorAds
#@##banner-advert-container
##.ad-inserter:not(##banner-advert-container)
##.SponsorAds:not(.adsense)
###banner-advert-container:not(.ad-inserter)
```
as per the bab arguments?

**Comment by stephenhawk8054** [comment]
Do other sites with `##+js(nostif, ai_)` use the same pattern in the code?

**Comment by okiehsch** [comment]
It's widespread, so a generic solution in this case makes sense.
If 
````
#@#.ad-inserter
#@#.SponsorAds
#@##banner-advert-container
##.ad-inserter:not(#banner-advert-container)
##.SponsorAds:not(.adsense)
###banner-advert-container:not(.ad-inserter)
````
works it's preferable imo.
Redirections can lead to site breakage on rare occasions.

**Comment by mapx-** [comment]
checked `https://techkaran.co.in/`
whitelisting 
`techkaran.co.in##+js(abort-current-script, decodeURIComponent, ai_)`

working fine
```
||media.net^$object,redirect-rule=noopjs
||google-analytics.com^$object,redirect-rule=noopjs
||doubleclick.net^$object,redirect-rule=noopjs
#@#.ad-inserter
#@#.SponsorAds
#@##banner-advert-container
##.ad-inserter:not(#banner-advert-container)
##.SponsorAds:not(.adsense)
###banner-advert-container:not(.ad-inserter)
```
