### ISSUE TITLE
Undetected anti-adblocker uol.com.br

### ISSUE THREAD

**Issue by Rikk** [uBlockOrigin/uAssets#124]
### URL(s) where the issue occurs

http://economia.uol.com.br/cotacoes/cambio/dolar-turismo-estados-unidos/

### Describe the issue

Anti-adblocker in popup format hiding the entire page.

### Screenshot(s)

![uol-anti-adblock](https://cloud.githubusercontent.com/assets/2916485/18107139/1cde14f8-6edd-11e6-89e1-c74690e61858.png)

### Versions

- Browser/version: Firefox 48.0.3.6080
- uBlock Origin version: 1.9.5b0

### Settings

![screen shot 2016-08-31](https://cloud.githubusercontent.com/assets/2916485/18118677/bffe9aa0-6f2c-11e6-80be-cd1fb74471c9.png)

### Notes

I think the offending script is this one:
http://jsuol.com.br/c/detectadblock/detectadblock.js
(Looks like it is a library named "Detect AdBlock" at version 1.4.6. Could it be used somewhere else with another name?)

---
@gorhill I kindly ask you unblock me. Somehow I missed the part saying uAssets when I read the page. I would be glad to report real bugs, if I find one. Ref: https://github.com/gorhill/uBlock/issues/1950

Thank you for the excellent uBlockO.

**Comment by mapx-** [comment]
`@@||jsuol.com.br/*ad$script`

**Comment by Rikk** [comment]
This commit doesn't work. How is this related to Folha site ads?

>@@||jsuol.com.br/*ad$script

This is an exception rule. For blocking I suggest `||jsuol.com.br/*adblock$important,script`
`important` because there is one exception for `adframe.js` in a list.

**Comment by gorhill** [comment]
The overlay appeared again after I cleared the cookies -- I thought at first the existing defuser was doing the job.

How about:

    economia.uol.com.br##.overlay-lightbox
    economia.uol.com.br##.content-lightbox
    economia.uol.com.br###banner-stick

**Comment by Rikk** [comment]
Of course we can hide dom elements, but the fat script will run. Other than displaying the anti-adb spam, it slows down page load and displays many messages in console.

**Comment by gorhill** [comment]
> the fat script will run

What script? `http://jsuol.com.br/c/detectadblock/adframe.js`? that script is blocked on my side, by EasyList's `/adframe.` filter. There is no exception filters showing in the logger.

**Comment by Rikk** [comment]
Talking about http://jsuol.com.br/c/detectadblock/detectadblock.js that is the one that displays the anti-adblocker.

The list `Anti-Adblock Killer | Reek‎` contains `@@/adframe.js$script`
Btw, why does it has so many exceptions if it should block anti-adblockers? Should I disable this list?

**Comment by IDKwhattoputhere** [comment]
> block anti-adblockers

Where does it say that? It's purpose is to foil anti-adblockers, not necessarily to keep them from running.

**Comment by Rikk** [comment]
@IDKwhattoputhere 
huh? :confused:
In other words: I think the list "Anti-Adblock Killer" should block scripts of the type "anti-adblocker".
I think you mean "anti-adblockers purpose is to foil adblockers".

**Comment by IDKwhattoputhere** [comment]
No, I don't. Again, where do you get this:
> intends to block scripts of the type "anti-adblocker"

It doesn't say it on their page. It just says
> Anti-Adblock Killer helps you keep your Ad-Blocker active, when you visit a website and it asks you to disable.

AakList does this by either blocking anti-adblock scripts or allowing what you could call "bait". "Bait" meaning network requests or divs that purposefully match a filter in usually EasyList and when blocked will indicate the user is using an adblocker. "Bait" usually consists of a script named for example `adframe.js` which sets a variable like `adblocker = false`. This variable won't be set if the script is blocked by the adblocker which will often result in the anti-adblocker hiding the site's content.
Then there's also AakScript which defuses anti-adblockers that are hard to cricumvent using the filter list approach. It doesn't block the anti-adblocker but might for example set the variable `adblocker = false` or whatever works for the site. That's my non-programer understanding of it anyways.

**Comment by Rikk** [comment]
But...
> No, I don't. Again, where do you get this:
>>intends to block scripts of the type "anti-adblocker"

Later, despite the grammar, I think we said the same thing:
>AakList does this by either blocking anti-adblock scripts or, [....]

But thanks for your explanation, I understand why some are allowed: AakList intends to either *block* or ***confuse*** those scripts.

**Comment by ghajini** [comment]
reproduced on
https://esporte.uol.com.br/
clear site specific cookies to reproduce
![chrome_2017-07-30_12-21-30](https://user-images.githubusercontent.com/20338483/28751337-7f3a813a-7522-11e7-83d7-535b515a54fd.png)

**Comment by isantolin** [comment]
Please update the filters to

> www.uol##.overlay-lightbox
> www.uol##.content-lightbox
> www.uol###banner-stick

(New domain)

Test URL:
https://www.uol/educacao/especiais/entrevista-com-fernando-haddad.htm#no-palanque-da-educacao

**Comment by adranger** [comment]
@okiehsch overlay https://congressoemfoco.uol.com.br/especial/noticias/lista-todos-os-salarios-e-beneficios-de-um-deputado/
