### ISSUE TITLE
journaldemontreal.com: detection

### ISSUE THREAD

**Issue by anthonydiiorio** [uBlockOrigin/uAssets#12405]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.journaldemontreal.com/`

### Category

detection

### Describe the issue

Ad blocker is detected by the following script: `s1.quebecormedia.com/infojdem/lib/cheezwhiz/v2/index.js`

Proposed filter:
`||s1.quebecormedia.com/infojdem/lib/cheezwhiz/v2/index.js$script`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![qVJUBaIG](https://user-images.githubusercontent.com/1933848/159815903-8d00f6a0-b9ed-439a-af56-a430db235b4b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 83515
  cosmetic: 87350
  scriptlet: 21640
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 51128-158, 4h.17m
    ublock-annoyances: 4363-152, 4h.17m
  default: 
    user-filters: 0-0, never
    easylist: 64648-47, 4h.18m
    easyprivacy: 26715-213, 4h.18m
    plowe-0: 3691-811, 4h.18m
    ublock-abuse: 72-0, 4h.18m
    ublock-badware: 3941-84, 4h.18m
    ublock-filters: 30581-420, 4h.18m
    ublock-privacy: 202-2, 4h.18m
    ublock-quick-fixes: 117-7, 4h.18m
    ublock-unbreak: 1736-45, 4h.18m
    urlhaus-1: 7406-0, 4h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1048 ms
  maxAssetCacheWait: 463 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    cxense.com: 1
    doubleclick.net: 2
    facebook.com: 1
    go-mpulse.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by CorSix2022** [comment]
Hey it worked! And it worked for all quebecor sites. Great! Thank you.

**Comment by stephenhawk8054** [comment]
It's already added in [https://github.com/uBlockOrigin/uAssets/commit/8986e72bc1d50d10edcef21fc06fdc24436ef525](https://github.com/uBlockOrigin/uAssets/commit/8986e72bc1d50d10edcef21fc06fdc24436ef525), can you force update the filter lists?

**Comment by anthonydiiorio** [comment]
Great thanks. It's working!
