### ISSUE TITLE
hltv.org: breakage

### ISSUE THREAD

**Issue by NNoxius** [uBlockOrigin/uAssets#12406]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hltv.org/`

### Category

breakage

### Describe the issue

Some icons of teams are not being displayed. It only affects team logo icons.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bild](https://user-images.githubusercontent.com/78695152/159828631-456736dc-9146-4fc3-9e7c-441d24ea6365.png)
![bild](https://user-images.githubusercontent.com/78695152/159828778-4273846a-a1d8-4151-8bcc-715bbc34ac75.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80545
  cosmetic: 44154
  scriptlet: 16817
  html: 681
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31027-30, 1d.2h.59m
    ublock-badware: 3929-3, 1d.2h.57m
    ublock-privacy: 206-0, 1d.2h.58m
    ublock-abuse: 72-0, 1d.2h.53m
    ublock-unbreak: 1747-0, 1d.2h.56m
    easylist: 64595-548, 1d.2h.55m
    easyprivacy: 26715-577, 1d.2h.54m
    urlhaus-1: 7406-0, 11h.34m
    plowe-0: 3675-2, 13d.2h.36m
    SWE-1: 4035-2, 4d.2h.10m
    ublock-quick-fixes: 114-4, 1d.21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 105 ms (selfie)
  maxAssetCacheWait: 53 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    hltv.org: 7
    adnami.io: 3
    cloudflareinsights.com: 4
    cookiebot.com: 1
    doubleclick.net: 2
    google-analytics.com: 1
    gscontxt.net: 1
    igaming-service.io: 1
    insurads.com: 1
    rtmark.net: 3
    yieldbird.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps or exact URL? When I access the homepage, the UI looks different to your screenshots, and I don't know where to click next.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/159829984-8aa018a2-a17b-4f94-b2d1-3dde33fed368.png)

</details>

**Comment by stephenhawk8054** [comment]
Ok, the correct URL is
`https://www.hltv.org/events/6137/esl-pro-league-season-15#News`

and scroll down to `Team attending` section

```
hltv.org#@#.night-only
||img-cdn.hltv.org/partnerimage/$image,~third-party
```

@ryanbr

**Comment by NNoxius** [comment]
For me it's still not fixed. The issue is not limited to one part of the website, but the entirety of it. On your screenshot you can see the "Heroic" icon missing in the "Ranking by" section to the left.

**Comment by stephenhawk8054** [comment]
> For me it's still not fixed. The issue is not limited to one part of the website, but the entirety of it. On your screenshot you can see the "Heroic" icon missing in the "Ranking by" section to the left.

Can you force update the filter list?
