### ISSUE TITLE
kanqite.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1240]
URL(s) where the issue occurs

`http://kanqite.com/aEiV025N`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zaphodbeebblebrox** [comment]
Add time boosting with `kanqite.com##script:inject(nano-setInterval-booster.js)`?
