### ISSUE TITLE
vw1.ffmovies.sc: nuisance

### ISSUE THREAD

**Issue by HishaamDeVries** [uBlockOrigin/uAssets#12409]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vw1.ffmovies.sc`

### Category

nuisance

### Describe the issue

pop up ads still appear on the right hand corner of the site every time I enter a new page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80175
  cosmetic: 41857
  scriptlet: 16593
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-abuse: null
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1d.23h.35m
  default: 
    user-filters: 0-0, never
    easylist: 64540-10, 2d.3h.38m
    easyprivacy: 26713-121, 2d.3h.37m
    plowe-0: 3671-805, 10d.4h.33m
    ublock-badware: 3930-84, 2d.3h.39m
    ublock-filters: 30442-82, 2d.3h.36m
    ublock-privacy: 200-2, 10d.8h.38m
    ublock-quick-fixes: 117-4, 4h.47m
    ublock-unbreak: 1736-41, 2d.3h.40m
    urlhaus-1: 8466-0, 20h.48m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 160 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    awigglespouter.cam: 1
    bepiletussar.casa: 2
    enginsquawks.cam: 1
    mudshambone.com: 1
    myrrhicfoeman.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your filter lists
(how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

test again

**Comment by HishaamDeVries** [comment]
thanks advice seemed to have worked for the website
