### ISSUE TITLE
mavic.com: breakage

### ISSUE THREAD

**Issue by z28chris** [uBlockOrigin/uAssets#12401]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mavic.com/de-de/contact-form`

### Category

breakage

### Describe the issue

contact form is not showing when ublock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81121
  cosmetic: 45219
  scriptlet: 16590
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5595-0, 4h.47m
    easylist: 64444-16, 2d.1h.9m
    easyprivacy: 26710-132, 2d.1h.8m
    plowe-0: 3671-806, 7d.22h.24m
    ublock-abuse: 72-0, 2d.1h.7m
    ublock-badware: 3972-84, 2d.1h.6m
    ublock-filters: 30383-125, 2d.1h.12m
    ublock-privacy: 200-2, 2d.1h.11m
    ublock-unbreak: 1728-43, 2d.1h.10m
    urlhaus-1: 7406-0, 4h.48m
    ublock-quick-fixes: 117-4, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
````
@@||cdn.mavic.com/sites/default/files/google_tag/google_tag/*$script,1p
@@||googletagmanager.com/gtm.js$script,domain=mavic.com
````
@ryanbr
