### ISSUE TITLE
[nsfw] exey.io: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#12408]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://exey.io/j3SR6`

### Category

detection

### Describe the issue

Adblock detector

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220324-113108940](https://user-images.githubusercontent.com/19517680/159842703-15ae9960-f279-4211-bd8f-8734dab1686d.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium Mobile: 99
filterset (summary): 
  network: 103097
  cosmetic: 158659
  scriptlet: 23583
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6103-1, now
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 4938-14, now
    IDN-0: 8917-243, 1m
    adguard-annoyance: 51128-180, 1m
    adguard-spyware: 26196-863, 1m
    fanboy-annoyance: 65436-2909, now
    ublock-annoyances: 4384-278, now
  default: 
    user-filters: 6-0, never
    adguard-mobile: 7384-27, 1m
    easylist: 64649-1500, 1m
    easyprivacy: 26717-10431, 1m
    ublock-abuse: 72-0, now
    ublock-badware: 3941-83, now
    ublock-filters: 30684-552, now
    ublock-privacy: 202-38, now
    ublock-unbreak: 1746-63, now
    ublock-quick-fixes: 118-7, never
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2522 ms
  maxAssetCacheWait: 3342 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    dba9ytko5p72r.cloudfront.net: 2
    forfrogadiertor.com: 1
    googletagmanager.com: 1
    hbcdn.net: 1
    s3.us-east-1.amazonaws.com: 1
    varechphugoid.com: 1
    vdo.ai: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test with no other extensions enabled and no DNS blocking or other adblock apps on your phone?

**Comment by mapx-** [comment]
If you are using kiwi browser => it's not fully supported

**Comment by 3xploiton3** [comment]
![Screenshot_20220324-173355803](https://user-images.githubusercontent.com/19517680/159897947-1c6ec6a5-d601-486b-9567-6ec9738ce557.jpg)

With duckduckgo browser

**Comment by stephenhawk8054** [comment]
? ublock isn't supported on duckduckgo browser on mobile (you can't install it).

**Comment by mapx-** [comment]
If duckduckgo browser has some privacy enforcement disable it & test again

**Comment by 3xploiton3** [comment]
i'm changed my dns its worked now,
