### ISSUE TITLE
[nsfw] freeadultcomix.com: ads

### ISSUE THREAD

**Issue by Vitalik93** [uBlockOrigin/uAssets#12413]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freeadultcomix.com/`

### Category

ads

### Describe the issue

Ads appear for a second and only then are blocked.

### Screenshot(s)

Sorry, couldn't take a screenshot. Ads disappear too fast.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 69465
  cosmetic: 113861
  scriptlet: 21252
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 30228-30, 53m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1404-25, 53m
    fanboy-cookiemonster: 26796-231, 53m
    ublock-annoyances: 4366-117, 53m
  default: 
    user-filters: 0-0, never
    RUS-0: 41392-138, 53m
    easylist: 64648-40, 53m
    ublock-abuse: 72-1, 53m
    ublock-badware: 3941-83, 53m
    ublock-filters: 30592-131, 53m
    ublock-privacy: 202-9, 53m
    ublock-quick-fixes: 123-4, 53m
    ublock-unbreak: 1740-22, 53m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
  uiTheme: light
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1581 ms (selfie)
  maxAssetCacheWait: 752 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    feedburner.com: 1
    googletagmanager.com: 1
    hentaimotel.com: 6
    histats.com: 1
    realsrv.com: 4
    resalag.com: 1
    tsyndicate.com: 1
```
</details>

**Comment by Procyon-b** [comment]
They are iframes. I suspect that they are hidden when their url matches a blocked resource and that the initial value is not blocked.

**Comment by Vitalik93** [comment]
> They are iframes. I suspect that they are hidden when their url matches a blocked resource and that the initial value is not blocked.

So... Could it be blocked or not?

**Comment by gorhill** [comment]
The frames are being blocked, it's just the placeholders being collapsed in a delayed manner.

A specific cosmetic filter can be used to avoid the delay:

    freeadultcomix.com##.anuncios

**Comment by gorhill** [comment]
Those frames are blocked by EasyList filters, plain cosmetic filters should be added to EasyList(if they agree this is an issue in the first place)  -- same behavior can be seen in ABP.

**Comment by Vitalik93** [comment]
Some "Ads" buttons on site. Seemed that leftovers from blocked advertising.

![Image](https://github.com/user-attachments/assets/c72d0ea4-c037-4245-ade0-5c55cf532e64)

**Comment by gorhill** [comment]
`freeadultcomix.com##.widget-titulo:has-text(ADS)`

**Comment by Vitalik93** [comment]
Could it be added in Easylist?
