### ISSUE TITLE
hyperrogue.miraheze.org: breakage

### ISSUE THREAD

**Issue by Sgeo** [uBlockOrigin/uAssets#12410]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hyperrogue.miraheze.org/wiki/Geometry`

### Category

breakage

### Describe the issue

MathML images on this Miraheze MediaWiki site sometimes do not show up properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/251161/159856411-63c4515e-9acd-4201-9e0f-3051e517aac2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 78915
  cosmetic: 41745
  scriptlet: 16587
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64415-10, 3d.15h.28m
    easyprivacy: 26708-121, 3d.15h.27m
    plowe-0: 3671-805, 9d.4h.18m
    ublock-abuse: 72-0, 7d.17h.7m
    ublock-badware: 3922-84, 3d.15h.26m
    ublock-filters: 30394-136, 3d.15h.25m
    ublock-privacy: 200-2, 7d.17h.4m
    ublock-quick-fixes: 117-4, 12h.31m
    ublock-unbreak: 1737-41, 3d.15h.24m
    urlhaus-1: 7370-0, 4h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 41 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 280 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    miraheze.org: 1
```
</details>

**Comment by mapx-** [comment]
add

```
://matomo.$domain=~matomo.org,badfilter
://matomo.$domain=~matomo.org|~miraheze.org
```

**Comment by mapx-** [comment]
@ryanbr EP issue
