### ISSUE TITLE
stadt-bremerhaven.de: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#12412]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stadt-bremerhaven.de/`

### Category

ads

### Describe the issue

at hte bottom of the page there are ads

### Screenshot(s)

https://user-images.githubusercontent.com/81616288/159887894-d4bf6090-58d6-4fea-bf6c-df1d4d1afe97.png

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81283
  cosmetic: 45464
  scriptlet: 16636
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5595-0, 2h.4m
    easylist: 64648-16, 2h.3m
    easyprivacy: 26717-132, 2h.3m
    plowe-0: 3691-811, 2h.3m
    ublock-abuse: 72-0, 2h.3m
    ublock-badware: 3941-84, 2h.3m
    ublock-filters: 30592-93, 2h.3m
    ublock-privacy: 202-2, 2h.3m
    ublock-quick-fixes: 123-4, 2h.3m
    ublock-unbreak: 1740-42, 2h.3m
    urlhaus-1: 7401-0, 2h.3m
filterset (user): [empty]
modifiedUserSettings: 
  uiTheme: dark
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3025 ms (selfie)
  maxAssetCacheWait: 645 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    digidip.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    storage.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`stadt-bremerhaven.de##.psw-container`

@monzta @ryanbr
