### ISSUE TITLE
[nsfw] miobt.com: ads

### ISSUE THREAD

**Issue by tasty0tomato** [uBlockOrigin/uAssets#12418]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://miobt.com/show-307201759bf71553a098b7f3b8915423cb997f71.html`

### Category

ads

### Describe the issue

http://www.comicat.org/
http://miobt.com/
http://www.kisssub.org/
These three website are under the same template, and this page is just the first item of _miobt_.
Seems that just _kisssub_ works well.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**miobt**
![网页捕获_24-3-2022_224537_miobt com](https://user-images.githubusercontent.com/48764449/159942409-bb8b57a1-70e4-4907-8dfa-edff35a6a205.jpeg)
**comicat**
![网页捕获_24-3-2022_224638_www comicat org](https://user-images.githubusercontent.com/48764449/159942574-fe0b9804-374e-4dc4-880c-d25aaa1b902f.jpeg)
**kisssub**
![网页捕获_24-3-2022_224736_www kisssub org](https://user-images.githubusercontent.com/48764449/159942793-d0ec1cff-eca9-43d0-80c4-0eaffc62eb87.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 58376
  cosmetic: 79828
  scriptlet: 16725
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    urlhaus-1: null
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24581-3, 2m
    JPN-1: 6184-11, 2d.7h.39m
  default: 
    user-filters: 0-0, never
    CHN-0: 27815-87, 2d.7h.40m
    easylist: 64544-99, 2d.3h.4m
    ublock-filters: 30442-103, 2d.7h.36m
    ublock-unbreak: 1736-16, 2d.7h.35m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 567 ms
  maxAssetCacheWait: 279 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    miobt.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
comicat.org,kisssub.org,miobt.com##.c1 > div.box[style^="overflow"]
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Yuki2718** [comment]
If extended syntax is not needed, I prefer pinging @cjx82630

**Comment by cjx82630** [comment]
30分钟后更新. 96e5c4fabff5c9ed789e58fb3b26d652e03234a6
Fixed.Please manually update in 30 minutes.

**Comment by tasty0tomato** [comment]
@cjx82630 Seems not fixs now or which filter should I use?

**Comment by cjx82630** [comment]
@tasty0tomato 30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by Procyon-b** [comment]
@cjx82630
I only see ads images blocked on `miobt.com` but not on `comicat.org` and `kisssub.org`

see `http://www.kisssub.org/show-de3bfc13c8e311cbd5f7e7d468be0254e284bfb2.html`
and `http://www.comicat.org/show-ed58e0abae27c714fb27e7707a8846c9caecd849.html`

**Comment by tasty0tomato** [comment]
> @cjx82630 I only see ads images blocked on `miobt.com` but not on `comicat.org` and `kisssub.org`
> 
> see `http://www.kisssub.org/show-de3bfc13c8e311cbd5f7e7d468be0254e284bfb2.html` and `http://www.comicat.org/show-ed58e0abae27c714fb27e7707a8846c9caecd849.html`

http://www.kisssub.org/show-1484307f90b43775edf6321e864f8c91a6e6ea93.html
http://miobt.com/show-1484307f90b43775edf6321e864f8c91a6e6ea93.html
http://www.comicat.org/show-1484307f90b43775edf6321e864f8c91a6e6ea93.html

Still _miobt.com_ and _comicat.org_ not work and _kisssub.org_ works

**Comment by cjx82630** [comment]
@tasty0tomato Please test it with ABP

**Comment by tasty0tomato** [comment]
@cjx82630  Works and thanks!

**Comment by Yuki2718** [comment]
@tasty0tomato What do you mean by saying not work? I don't see ads in all the three sites.

**Comment by tasty0tomato** [comment]
@Yuki2718 Sorry, I did not test with ABP before.

**Comment by Yuki2718** [comment]
I'm using uBO and no ads in any of the 3 sites.

**Comment by tasty0tomato** [comment]
@Yuki2718 
With default filter and.
http://miobt.com/show-b5280f53083308aa71b0052c1747e7cea4684668.html
![Web キャプチャ_27-3-2022_235651_miobt com](https://user-images.githubusercontent.com/48764449/160289925-2b136680-8ba1-4f92-978f-66df632287f7.jpeg)

**Comment by Yuki2718** [comment]
Are you sure AdGurad Chinese is enabled and up-to-date?

**Comment by tasty0tomato** [comment]
So so sorry...
It's wired because I was sure that I followed wiki to force update every time but it just worked a few minuted ago. Maybe my wrong operation.
Again, so sorry 😭

**Comment by Yuki2718** [comment]
No problem, thank you for checking.
