### ISSUE TITLE
vakil.net nuisance 

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#12411]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vakil.net/%D9%88%D8%AC%D9%88%D9%87-%D8%A7%D9%81%D8%AA%D8%B1%D8%A7%D9%82-%D9%88-%D8%A7%D8%B4%D8%AA%D8%B1%D8%A7%DA%A9-%D8%B4%D8%B1%DA%A9%D8%AA%D9%87%D8%A7%DB%8C-%D8%B3%D9%87%D8%A7%D9%85%DB%8C-%D8%AE%D8%A7%D8%B5-3/`

### Describe the issue

Prevents: **Right click, Text selection, Ctrl + Key, F12, Image dragging, ...**

### Notes

**The nuisance code:** https://pastetext.net/raw/ebsfknz9kw

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 71701
  cosmetic: 41426
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    easylist: 64454-10, 5m
    easyprivacy: 26664-121, 5m
    plowe-0: 3674-805, 4d.17h.36m
    ublock-abuse: 72-0, 5m
    ublock-badware: 3967-85, 5m
    ublock-filters: 30214-145, 5m
    ublock-privacy: 200-2, 5m
    ublock-unbreak: 1723-39, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 185 ms
```
</details>

**Comment by MasterKia** [comment]
@stephenhawk8054 I tried your fix on `https://www.takmili.com/%D9%85%D8%B1%D8%A8%D8%B9-%D8%AC%D8%A7%D8%AF%D9%88%DB%8C%DB%8C/`, the text can be selected but it's not shown on the screen (the text doesn't get blue when selected).

My fix:
```
takmili.com##+js(acis, document.oncontextmenu)
takmili.com##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)

takmili.com##+js(set, disable_copy, noopFunc)
takmili.com##+js(set, disable_drag_text, noopFunc)
takmili.com##+js(set, disable_hot_keys, noopFunc)
takmili.com##+js(set, disable_drag_images, noopFunc)
```

**Comment by mapx-** [comment]
for select to be visible:

`takmili.com##*::selection:style(background-color:#338FFF!important)`

**Comment by MasterKia** [comment]
That worked, thanks
I noticed image drag is still disabled.
`##*:style(-webkit-user-drag: default !important; user-drag: default !important;)` doesn't work.

**Comment by mapx-** [comment]
it seems working for example on an image on the left side

![image](https://user-images.githubusercontent.com/10303732/172776670-81b20d26-e6b9-415a-ab18-2d4301f37f12.png)

**Comment by mapx-** [comment]
if you want to print the page (right click, print) you need:

`/wp-content/plugins/wccp-pro/css/print-protection`

I'll add it to uBO annoyances list too

**Comment by MasterKia** [comment]
> image on the left

Try image on the article (when I drag image from for example Google images into other program, I get the image address, but on this site that doesn't happen)

Try this:
![image](https://user-images.githubusercontent.com/17685483/172783953-bb8514d4-56a4-42f9-974b-1adda74190d2.png)

**Comment by MasterKia** [comment]
All scripts on this site with script id="wccp_pro..." are annoyances.

**Comment by mapx-** [comment]
add & test

```
takmili.com##+js(ra, draggable, , stay)
takmili.com##style:has-text(wccp):remove()
takmili.com##style:has-text(user-select):remove()
```

**Comment by MasterKia** [comment]
Image drag is still disabled.
Also Ctrl+C, PrtScr and similar keys wouldn't work with `takmili.com##style:has-text(wccp):remove()` and `takmili.com##style:has-text(user-select):remove()` unless I add:

```
takmili.com##+js(set, disable_copy, noopFunc)
takmili.com##+js(set, disable_drag_text, noopFunc)
takmili.com##+js(set, disable_hot_keys, noopFunc)
takmili.com##+js(set, disable_drag_images, noopFunc)
```

**Comment by MasterKia** [comment]
But at least they remove the nag ("you can't copy, bla bla").

**Comment by mapx-** [comment]
drag (that) image working  fine chrome / FF

**Comment by MasterKia** [comment]
You drag it into what? I drag into Telegram and it doesn't work.
I drag image from Google images into Telegram and it works.

**Comment by mapx-** [comment]
drag into pspad editor for example to see the link

**Comment by MasterKia** [comment]
Fixed with all above filters, gonna add to PersianBlocker.
Thanks.

**Comment by MasterKia** [comment]
Oops, forgot `takmili.com##+js(set, dealWithPrintScrKey, noopFunc)`.
