### ISSUE TITLE
vercanalestv.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1242]
URL(s) where the issue occurs

`http://www.vercanalestv.com/ver-bein-sport-espanol-online-y-en-directo-las-24h-por-internet-en-vivo/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@mapx-

`http://www.vercanalestv.com/ver-canal-plus-partidazo-online-y-directo-gratis/`

**Comment by KiLL4FuNK** [comment]
@mapx-  Anti-Adblock  `http://www.vercanalestv.com/ver-canal-plus-partidazo-online-y-directo-gratis/`

**Comment by KiLL4FuNK** [comment]
ADS Popups

http://vercanalestv1.com/ver-antena-3-en-directo-y-online-las-24h/

**Comment by KiLL4FuNK** [comment]
https://vercanalestv1.com/fox-sports-en-vivo-por-internet/

PLAY VIDEO ADS Popups

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO Popups

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fa3498f7bedec887c96c61ec92d4978eff7d9366

**Comment by KiLL4FuNK** [comment]
ADS

`https://vercanalestv1.com/fox-sports-en-vivo-por-internet/`

**Comment by mapx-** [comment]
try
`||static.tellerium.com/$frame`

**Comment by okiehsch** [comment]
I was just about to add 
`||static.tellerium.com^$frame,domain=telerium.tv`
works on my end.

**Comment by okiehsch** [comment]
That is a an old issue that can't be fixed without breaking fullscreen functionality.
https://github.com/uBlockOrigin/uAssets/issues/3370#issuecomment-419304536

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://vercanalestv1.com/fox-sports-en-vivo-por-internet/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://vercanalestv1.com/ver-espn-2-en-vivo-gratis-por-internet/`

**Comment by KiLL4FuNK** [comment]
Fake Button

`https://vercanalestv1.com/directv-sports-en-vivo-por-internet/`
