### ISSUE TITLE
tvanouvelles.ca: detection

### ISSUE THREAD

**Issue by chabuco** [uBlockOrigin/uAssets#12422]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tvanouvelles.ca/`

### Category

detection

### Describe the issue

The website (in French) detects UBlock and shows a popup windows that prevents reading the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![CaptureUblock](https://user-images.githubusercontent.com/102320635/159984191-5610d123-e0c8-464a-ac3e-f226c41cc843.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 95537
  cosmetic: 50820
  scriptlet: 16653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    FRA-0: 26213-25, 2d.14h.46m
    easylist: 64535-69, 2d.19h.21m
    easyprivacy: 26711-439, 2d.19h.24m
    plowe-0: 3671-813, 9d.23h.38m
    ublock-abuse: 72-1, 10d.21h.8m
    ublock-badware: 3930-91, 2d.19h.20m
    ublock-filters: 30426-289, 2d.19h.19m
    ublock-privacy: 200-2, 10d.21h.5m
    ublock-quick-fixes: 117-4, 15h.54m
    ublock-unbreak: 1736-41, 2d.19h.18m
    urlhaus-1: 7370-0, 15h.55m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 27 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 293 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    brightcove.com: 5
    cxense.com: 2
    doubleclick.net: 2
    go-mpulse.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
You didn't update the filter lists. It was already fixed.
