### ISSUE TITLE
[nsfw] kek3.com: popups

### ISSUE THREAD

**Issue by umerfaraz786** [uBlockOrigin/uAssets#12429]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kek3.com/`

### Category

popups

### Describe the issue

This is a fake site containing malicious websites and taking people to fill in unwanted surveys.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 78963
  cosmetic: 41688
  scriptlet: 16589
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 64505-10, 3d.6h.4m
    easyprivacy: 26710-121, 3d.6h.6m
    plowe-0: 3671-805, 9d.5h.15m
    ublock-abuse: 72-0, 8d.7h.53m
    ublock-badware: 3925-84, 3d.6h.5m
    ublock-filters: 30383-115, 3d.6h.3m
    ublock-privacy: 200-2, 8d.8h.13m
    ublock-unbreak: 1736-41, 3d.2h
    urlhaus-1: 7370-0, 14h.10m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1281 ms (selfie)
  maxAssetCacheWait: 548 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google.com: 2
    onesignal.com: 1
    waust.at: 1
```
</details>

**Comment by mapx-** [comment]
How did you arrive upon kek3? clicking on some other page (which one) ?

**Comment by iam-py-test** [comment]
It does have shady practices, but I see only one popup (`https://app.any.run/tasks/0a3a831c-36fb-4a84-9de7-91a8a05b0707`)
`  If you want to have  M416 Glacier {ice} ~ Go to google search  and type →  kek3com    .then enter the first site  - I have  M416 Glacier because of this site  `
