### ISSUE TITLE
hltv.org: ads

### ISSUE THREAD

**Issue by NNoxius** [uBlockOrigin/uAssets#12420]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hltv.org/`

### Category

ads

### Describe the issue

To the left on the landing page, there is one ad visible. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![bild](https://user-images.githubusercontent.com/78695152/159960314-854f9ede-5548-400d-9715-2eeb6d2a73fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80622
  cosmetic: 44285
  scriptlet: 16840
  html: 681
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31168-83, 13h.55m
    ublock-badware: 3945-3, 13h.55m
    ublock-privacy: 207-0, 13h.55m
    ublock-abuse: 72-0, 13h.55m
    ublock-unbreak: 1749-0, 13h.55m
    easylist: 64649-494, 13h.55m
    easyprivacy: 26717-582, 13h.55m
    urlhaus-1: 7401-0, 13h.55m
    plowe-0: 3691-2, 13h.55m
    SWE-1: 4038-2, 13h.55m
    ublock-quick-fixes: 118-4, 13h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  uiAccentCustom: true
  uiAccentCustom0: #ff5900
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 110 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    hltv.org: 7
    adnami.io: 3
    cloudflareinsights.com: 4
    doubleclick.net: 2
    google-analytics.com: 1
    gscontxt.net: 1
    igaming-service.io: 1
    insurads.com: 1
    rtmark.net: 3
    yieldbird.com: 1
```
</details>

**Comment by NNoxius** [comment]
I'm talking about the "Skinport" ad under the "Player of the week" section on the far left of the page.

**Comment by dportvine** [comment]
`https://www.hltv.org/news/35793/let-us-cook-upset-fnatic-in-cct-north-europe-series-4`
<details>
<summary>Screen</summary>

![2023-03-15_090214](https://user-images.githubusercontent.com/111344219/225232101-9608806d-3a97-4e7a-ad15-198dfed39233.png)
![2023-03-15_090330](https://user-images.githubusercontent.com/111344219/225232117-ddf2cc59-1f87-42e5-8f5a-409e409c9ee8.png)
</details>
