### ISSUE TITLE
tele-envivo.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1243]
URL(s) where the issue occurs

`http://www.tele-envivo.com/tvc-deportes-en-vivo-por-internet.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Anti-Adblock @mapx-

**Comment by mapx-** [comment]
@diaux

**Comment by diaux** [comment]
Thanks for reporting @mapx - I updated EasyList Spanish - https://github.com/easylist/easylistspanish/commit/7db6697
