### ISSUE TITLE
primevideo.com: ads

### ISSUE THREAD

**Issue by rodrigovda** [uBlockOrigin/uAssets#12438]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.primevideo.com/`

### Category

ads

### Describe the issue

The Cookie banner shows, even with Annoyances lists activated.

This filter hides it:
`##.DVWebNode.DVWebNode-cookie-banner-wrapper`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/15835304/160143594-f65e0df7-131d-4cfc-9f10-b0005ba86aad.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 145360
  cosmetic: 195106
  scriptlet: 34202
  html: 638
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 2d.16h.40m
    adguard-generic: 62798-4955, 3d.22h.54m
    adguard-mobile: 7376-212, 3d.23h.1m
    adguard-spyware: 27163-1286, 3d.22h.55m
    adguard-annoyance: 51004-4295, 3d.22h.53m
    adguard-social: 16384-18, 3d.22h.56m
    fanboy-thirdparty_social: 68-0, 8d.17h.29m
    fanboy-annoyance: 63858-47796, 8d.17h.30m
    fanboy-cookiemonster: 24675-144, 8d.17h.31m
    fanboy-social: 23241-1086, 3d.23h
    ublock-annoyances: 4371-4, 3d.22h.59m
    dpollock-0: 10362-1636, 6d.3h.42m
    spa-0: 3832-1, 5h.4m
    spa-1: 4276-109, 3d.23h.2m
    adguard-spyware-url: 524-3, 3d.22h.57m
    block-lan: 43-0, 6d.3h.43m
  default: 
    user-filters: 4-0, never
    ublock-filters: 31166-118, 14h.29m
    ublock-badware: 3934-5, 3d.22h.58m
    ublock-privacy: 207-0, 14h.31m
    ublock-abuse: 72-0, 14h.30m
    ublock-unbreak: 1753-0, 14h.28m
    easylist: 64683-1033, 14h.27m
    easyprivacy: 26718-10823, 14h.26m
    plowe-0: 3671-348, 8d.17h.33m
    urlhaus-1: 8466-0, 1d.2h.48m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5216 ms (selfie)
  maxAssetCacheWait: 1840 ms
popupPanel: 
  blocked: 130
  no-remote-fonts: true
  blockedDetails: 
    primevideo.com: 9
    aiv-cdn.net: 6
    akamaihd.net: 3
    amazon.com: 67
    amazonvideo.com: 3
    media-amazon.com: 42
```
</details>

**Comment by mapx-** [comment]
@ryanbr
