### ISSUE TITLE
breakage: urban.arcgis.com (french list)

### ISSUE THREAD

**Issue by DemersM** [uBlockOrigin/uAssets#12436]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://urban.arcgis.com/js/468.bundle.js`

### Describe the issue

The following filter: `/js/468.$domain=~mail.zoho.com`  in the list `FRA: AdGuard Français` should not block the following url: `https://urban.arcgis.com/js/468.bundle.js` because it is not on `mail.zoho.com` domain

### Screenshot(s)

![2022_03_23_13_35_17_uBlock_Journal_des_requêtes_réseau](https://user-images.githubusercontent.com/2590556/160126891-6c1da21c-a9f2-4b0a-9130-55ee4552f538.png)

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 99.0.4844.82 (Build officiel) (64 bits)

### Settings

Default settings

**Comment by mapx-** [comment]
Provide info (steps on reproducing the issue) about what is broken

`/js/468.$domain=~mail.zoho.com` => meaning `/js/468.` is blocked on all pages with 1 exception: `mail.zoho.com`

**Comment by DemersM** [comment]
> Provide info (steps on reproducing the issue) about what is broken
> 
> `/js/468.$domain=~mail.zoho.com` => meaning `/js/468.` is blocked on all pages with 1 exception: `mail.zoho.com`

Ok thank you for the info. Is it possible to add urban.arcgis.com to the exception at the list level?

**Comment by mapx-** [comment]
> Provide info (steps on reproducing the issue) about what is broken

**Comment by DemersM** [comment]
You can reproduce the error when loading a public ArcGIS Urban application such this one: https://urban.arcgis.com/?id=fd45a15550cf4ea6b361e3c54c8d3ed1
![2022_03_25_09_57_05_sgoPUBwp02_sgoPUBwp02_Connexion_Bureau_à_distance](https://user-images.githubusercontent.com/2590556/160134897-862697ea-a2e2-4353-9ad3-3ab2f21561d1.png)

The application does not works as intended when the `https://urban.arcgis.com/js/468.bundle.js` is missing. The buildings visibility are not toggled on/off when switching scenarios inside a project.

The issue is already documented on the application side: https://community.esri.com/t5/arcgis-urban-questions/scenarios-in-projects-does-not-toggle-off-when/m-p/1157168#M204

**Comment by mapx-** [comment]
@smed79

**Comment by smed79** [comment]
> Is it possible to add urban.arcgis.com

added https://github.com/easylist/listefr/commit/f404a6d7015f7e6a64bb511d715cf360ebced7cd
