### ISSUE TITLE
crazy-factory.com: breakage

### ISSUE THREAD

**Issue by rodrigovda** [uBlockOrigin/uAssets#12433]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.crazy-factory.com/es`

### Category

breakage

### Describe the issue

When trying to log-in in the spanish version of the webpage (so the "/es" part of the URL is important) the webpage shows this error message:
```
Error
Por favor activa las cookies en tu navegador para poder continuar con tu compra.
```
Wich translates to:
```
Error
Please, enable cookies on your browser to continue shopping.
```

The weird thing is that you can login the US store and go back to the spanish store without any issue, this happens only when trying to log-in the spanish website.

I can provide a mockup account I created to test this (no personal information in it).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://user-images.githubusercontent.com/15835304/160117224-0debd1a8-072f-4beb-9dfb-706dcdd2dac2.png)
![imagen](https://user-images.githubusercontent.com/15835304/160117352-1db885f3-a2cb-43e3-b228-5bec91a2fcee.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 147817
  cosmetic: 191961
  scriptlet: 33719
  html: 638
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 62859-4968, 3d.4h.47m
    adguard-mobile: 7375-191, 3d.4h.49m
    adguard-spyware: 27165-1097, 3d.4h.46m
    adguard-spyware-url: 528-3, 3d.4h.48m
    block-lan: 43-0, 7d.19h.17m
    curben-phishing: 10298-2, 54m
    curben-pup: 296-0, 53m
    adguard-annoyance: 51030-3893, 3d.14h.14m
    adguard-social: 16395-1074, 3d.4h.44m
    fanboy-thirdparty_social: 68-0, 7d.19h.17m
    fanboy-annoyance: 63708-49046, 7d.19h.19m
    fanboy-cookiemonster: 21982-123, 7d.19h.20m
    fanboy-social: 23244-30, 3d.4h.45m
    ublock-annoyances: 4371-5, 3d.14h.16m
    dpollock-0: 10362-489, 7d.19h.17m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31025-128, 3d.14h.12m
    ublock-badware: 3934-3, 3d.38m
    ublock-privacy: 207-0, 22h.38m
    ublock-abuse: 72-0, 22h.37m
    ublock-unbreak: 1747-0, 3d.14h.19m
    easylist: 64535-962, 3d.14h.15m
    easyprivacy: 26711-10713, 3d.14h.18m
    urlhaus-1: 7296-0, 56m
    plowe-0: 3671-2, 11d.23h.13m
    spa-0: 3832-1, 55m
    spa-1: 4277-103, 3d.14h.17m
    ublock-quick-fixes: 147-4, 57m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4276 ms (selfie)
  maxAssetCacheWait: 723 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    crazy-factory.com: 1
    adcell.com: 1
    adcell.de: 1
    chimpstatic.com: 1
    criteo.net: 1
    facebook.net: 1
    googleoptimize.com: 2
    googletagmanager.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
It's because you need to click on `OK` button for cookie prompt to log in, which is blocked by these 2 filters

```
_cookie_banner.
##.cookie_banner
```

in `EasyList Cookie` and `Fanboy’s Annoyance`.

You can add these to `My filters`

```
@@||crazy-factory.com/ajax_box_cookie_banner.php$xhr
crazy-factory.com#@#.cookie_banner
```

@ryanbr
