### ISSUE TITLE
[nsfw] datastudio.google.com: popups

### ISSUE THREAD

**Issue by ishyasiva** [uBlockOrigin/uAssets#12432]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://datastudio.google.com/u/0/reporting/a59c606a-63db-47db-8283-3cc0da7572df/page/UrOhC?s=kB27kmzJQag`

### Category

popups

### Describe the issue

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79040
  cosmetic: 42041
  scriptlet: 16638
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64648-10, 22h.25m
    easyprivacy: 26718-121, 22h.23m
    plowe-0: 3671-805, 9d.5h.31m
    ublock-abuse: 72-0, 4d.22h.26m
    ublock-badware: 3941-84, 22h.22m
    ublock-filters: 30597-82, 22h.21m
    ublock-privacy: 200-2, 4d.22h.23m
    ublock-quick-fixes: 147-5, 2h.30m
    ublock-unbreak: 1738-41, 22h.20m
    urlhaus-1: 7296-0, 10h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 14336 ms
  maxAssetCacheWait: 1721 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    maps.googleapis.com: 1
```
</details>

**Comment by ishyasiva** [comment]
-

**Comment by mapx-** [comment]
What popups are you talking about ? steps to reproduce such issue ? screenshot ?

**Comment by iam-py-test** [comment]
I see no popups in both Chrome and Firefox (I don't even see popups with it disabled). Also, NSFW?
@ishyasiva please test in a new browser profile and scan your device for malware, or provide more details (screenshots and more details would really be helpful)
