### ISSUE TITLE
finance.sina.com.cn: ads

### ISSUE THREAD

**Issue by sigilzen** [uBlockOrigin/uAssets#12448]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://finance.sina.com.cn/realstock/company/sh600588/nc.shtml`

### Category

ads
`https://finance.sina.com.cn/realstock/company/sh600588/nc.shtml`

### Describe the issue

`https://finance.sina.com.cn/realstock/company/sh600588/nc.shtml`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 96874
  cosmetic: 52004
  scriptlet: 16720
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 20-0, never
    CHN-0: 27810-86, 2d.14h.52m
    easylist: 64602-15, 2d.14h.51m
    easyprivacy: 26716-148, 2d.14h.50m
    plowe-0: 3687-811, 56m
    ublock-abuse: 72-0, 11d.3h.49m
    ublock-badware: 3922-84, 2d.14h.48m
    ublock-filters: 30534-100, 2d.14h.46m
    ublock-privacy: 200-2, 11d.3h.44m
    ublock-quick-fixes: 99-4, 53m
    ublock-unbreak: 1738-42, 2d.14h.45m
    urlhaus-1: 7645-0, 54m
filterset (user): [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 527 ms (selfie)
  maxAssetCacheWait: 192 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    sina.com.cn: 15
    allyes.com: 1
    sinaimg.cn: 10
    sinajs.cn: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Can you check this?

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
