### ISSUE TITLE
journaldemontreal.com: detection

### ISSUE THREAD

**Issue by smenes** [uBlockOrigin/uAssets#12449]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.journaldemontreal.com/`

### Category

detection

### Describe the issue

This site detects ublock.
if i remove the popup with zapper mode it works fine.
but if I want to remove it permanently with selector mode, that also removes the ability to scroll down. so the site is unusable

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![enng4jG](https://user-images.githubusercontent.com/4074396/160224889-a646f5c5-3656-47e1-8dcd-58c18be93c61.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 95520
  cosmetic: 50954
  scriptlet: 16670
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9h.20m
  default: 
    user-filters: 4-0, never
    FRA-0: 26213-25, 3d.13h.17m
    easylist: 64615-71, 2d.13h.16m
    easyprivacy: 26715-439, 2d.13h.15m
    plowe-0: 3687-817, 9h.57m
    ublock-abuse: 72-1, 6d.23h.52m
    ublock-badware: 3925-91, 2d.13h.14m
    ublock-filters: 30473-233, 2d.13h.13m
    ublock-privacy: 200-2, 6d.23h.49m
    ublock-quick-fixes: 147-15, 20h.33m
    ublock-unbreak: 1736-41, 2d.13h.12m
    urlhaus-1: 7296-0, 20h.34m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 170 ms (selfie)
  maxAssetCacheWait: 174 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cxense.com: 1
    doubleclick.net: 2
    go-mpulse.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
update uBO filters, fixed 2 days ago

**Comment by smenes** [comment]
thanks
