### ISSUE TITLE
techpowerup.com: breakage

### ISSUE THREAD

**Issue by snebes** [uBlockOrigin/uAssets#12447]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.techpowerup.com/`

### Category

breakage

### Describe the issue

The main content of the site is now blocked, with a message popping up saying that a recent UBO update blocks their content.  The content of the site is viewable for a fraction of a second, so it is not really blocked by UBO it appears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/666333/160209308-3cfb0e0b-4f03-42e5-986e-b7f2d40ce272.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79080
  cosmetic: 41894
  scriptlet: 16612
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1d.16h.35m
  default: 
    user-filters: 0-0, never
    easylist: 64544-10, 3d.10h.46m
    easyprivacy: 26713-121, 3d.10h.45m
    plowe-0: 3708-817, 4d.14h.52m
    ublock-abuse: 72-0, 7d.12h.3m
    ublock-badware: 3925-84, 3d.10h.44m
    ublock-filters: 30463-82, 3d.10h.43m
    ublock-privacy: 200-2, 7d.12h
    ublock-quick-fixes: 146-15, 8h.10m
    ublock-unbreak: 1736-41, 3d.10h.47m
    urlhaus-1: 7296-0, 16h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 414 ms (selfie)
  maxAssetCacheWait: 124 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Happened because `aside` got changed to `div` and the next `aside` with a empty space was next to the main content

**Comment by mapx-** [comment]
yeah, they destroy their own site and then put up a warning message about uBO
