### ISSUE TITLE
blick.ch: breakage

### ISSUE THREAD

**Issue by lawinchen** [uBlockOrigin/uAssets#12446]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.blick.ch/ausland/putins-perfider-plan-kreml-chef-will-offenbar-eigene-staedte-bombardieren-id17349557.html`

### Category

breakage

### Describe the issue

Article text is cut off on the right side (marked in red) happens only with some articles on that site, most work fine.
If I open the same article without uBlock it works fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81533
  cosmetic: 45448
  scriptlet: 16541
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5521-0, 19d.1h.31m
    easylist: 64827-57, 1m
    easyprivacy: 26646-133, 19d.1h.34m
    plowe-0: 3692-806, 23h.18m
    ublock-abuse: 72-0, 19d.1h.33m
    ublock-badware: 3939-85, 19d.1h.32m
    ublock-filters: 30483-92, 2h.27m
    ublock-privacy: 203-2, 9m
    ublock-quick-fixes: 144-15, 3m
    ublock-unbreak: 1738-41, 8m
    urlhaus-1: 7645-0, 7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 481 ms
  maxAssetCacheWait: 215 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    admeira.ch: 1
    brightcove.com: 5
    cxense.com: 1
    datawrapper.de: 1
    dreamlab.pl: 1
    googletagmanager.com: 1
    npttech.com: 1
    ocdn.eu: 2
    onesignal.com: 1
    onet.pl: 5
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
test

`blick.ch##.fKZLNI:style(width:120% !important)`

The reason is the filter
`blick.ch##+js(set, Object.prototype.isAdDisabled, true)`

but disabling it we'll get video ads
