### ISSUE TITLE
[Anti-AdBlock] Lolalytics.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#1245]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://lolalytics.com/ranked/worldwide/platinum/plus/champion/Akali/
### Describe the issue

Intended content not accessible.

### Versions

- Browser/version: Chrome, latest
- uBlock Origin version: latest

### Settings

default

**Comment by mapx-** [comment]
see https://github.com/uBlockOrigin/uAssets/issues/668#issuecomment-326760490

test those filters and report back there
