### ISSUE TITLE
ddrk.me: detection

### ISSUE THREAD

**Issue by jishuweiwang** [uBlockOrigin/uAssets#12454]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ddrk.me/turning-red/`

### Category

detection

### Describe the issue

识别到我屏蔽广告 并且有加载前的10s警示视频

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 96646
  cosmetic: 52065
  scriptlet: 16642
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 27852-86, 20h.22m
    easylist: 64683-15, 20h.28m
    easyprivacy: 26718-147, 20h.27m
    plowe-0: 3671-807, 11d.12h.31m
    ublock-abuse: 72-0, 10d.10h.4m
    ublock-badware: 3946-85, 20h.25m
    ublock-filters: 30480-99, 20h.24m
    ublock-privacy: 200-2, 10d.10h
    ublock-quick-fixes: 147-15, 13h.29m
    ublock-unbreak: 1742-42, 20h.23m
    urlhaus-1: 7296-0, 13h.28m
filterset (user): [empty]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 727 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    cnzz.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I still get that video ads even when disabling uBO. Is it related to this part in one of the scripts?

```js
if ((document.getElementById('fh972w3h4g3y9g').clientWidth < 1) || (document.getElementById('fh972w3h4g3y9g').getBoundingClientRect().left < 0) || ((document.getElementById('fh972w3h4g3y9g').getBoundingClientRect().top + jQuery(window).scrollTop()) < 0)) {
	myPlayer.ads();
	myPlayer.on('contentchanged', function() {
		myPlayer.trigger('adsready')
	});
	myPlayer.on('readyforpreroll', function() {
		myPlayer.ads.startLinearAdMode();
		myPlayer.src({
			src: '/vjs-plugins/12.m3u8',
			type: 'application/vnd.apple.mpegurl'
		});
		myPlayer.one('adplaying', function() {
			myPlayer.trigger('ads-ad-started')
		});
		myPlayer.one('adended', function() {
			myPlayer.ads.endLinearAdMode()
		})
	});
	myPlayer.trigger('adsready')
}
```

`document.getElementById('fh972w3h4g3y9g').clientWidth` is always 0.
