### ISSUE TITLE
poshukach.com: privacy

### ISSUE THREAD

**Issue by piskutekk** [uBlockOrigin/uAssets#12458]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poshukach.com/?fr=ps&gp=496723&altserp=1`

### Category

privacy

### Describe the issue

i dont know what im supposed to do with this web so i report it,it seems like russian virus 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79311
  cosmetic: 42367
  scriptlet: 16871
  html: 630
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31166-40, 1d.21h.26m
    ublock-badware: 3945-3, 1d.21h.25m
    ublock-privacy: 204-0, 6d.3h.6m
    ublock-abuse: 72-0, 9d.2h.40m
    ublock-unbreak: 1753-0, 21h.10m
    easylist: 64688-543, 21h.9m
    easyprivacy: 26719-582, 21h.8m
    urlhaus-1: 7296-0, 21h.6m
    plowe-0: 3690-2, 2d.20h.18m
    CZE-0: 833-0, 21h.7m
    ublock-quick-fixes: 146-4, 15h.15m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 341 ms (selfie)
  maxAssetCacheWait: 61 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe your system is affected by some malware, read here:

https://malwaretips.com/blogs/remove-poshukach-com/
