### ISSUE TITLE
Not blocking coolwallpapers.me anti-adblock popup

### ISSUE THREAD

**Issue by Samisafool** [uBlockOrigin/uAssets#12462]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://coolwallpapers.me/2804438-clouds-sky-white-war-military-eurofighter-typhoon-delta-wing.html#google_vignette

### Describe the issue

There is a very scummy anti-adblock popup there, here's the filter code to block it:

```
coolwallpapers.me##.dfgh-outer
coolwallpapers.me##.dfgh
```

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Mozilla Firefox 98.0.2

### Settings

Updated filter lists

**Comment by okiehsch** [comment]
Looks like an annoyance, the site only shows the message on the first pageload on my end.
You have to enable the `uBO-annoyances` list or add
`coolwallpapers.me##+js(nosiif, dfgh-adsbygoogle)`
to your personal filter list.
