### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#12461]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://megaup.net/13i1m`

### Category

detection

### Describe the issue

Note: ads are NSFW
loading gif briefly appears before instantly cutting to adblocker detected image.
I have catblock installed but disabled for the site.
verified that the issue still occurs without enabling external filter lists
verified that the issue still occurs without custom filters/rules

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/160241411-016c4780-aa6b-476f-a3eb-418258714ada.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 247207
  cosmetic: 52146
  scriptlet: 16640
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 27875-5961, 16m
  default: 
    user-filters: 185020-0, never
    easylist: 64848-14605, 16m
    easyprivacy: 26724-10992, 16m
    plowe-0: 3687-3076, 16m
    ublock-abuse: 72-2, 16m
    ublock-badware: 3947-501, 16m
    ublock-filters: 30492-362, 16m
    ublock-privacy: 203-27, 16m
    ublock-quick-fixes: 143-15, 16m
    ublock-unbreak: 1741-43, 16m
    urlhaus-1: 7472-487, 16m
filterset (user): [array of 185044 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 819 ms (selfie)
  maxAssetCacheWait: 494 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    megaup.net: 2
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 1
    googletagmanager.com: 1
    keydawnawe.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can reproduce on chromium, but not on firefox. Is this filter needed?

```
megaup.net##.imgAds,img[src^="https://megaup.net/imageads/"]:style(height:auto !important;display:block !important)
```

Removing it seems solve the problem.

**Comment by mapx-** [comment]
what if you add
```
$image,redirect-rule=noopframe,domain=megaup.net
$image,redirect-rule=1x1.gif,domain=megaup.net
```

**Comment by okiehsch** [comment]
@mapx- Does not work, Itried that.

**Comment by mapx-** [comment]
weird, in FF no issue
in chrome adding those filters working fine on my side

**Comment by okiehsch** [comment]
@stephenhawk8054 solution works for me.

**Comment by okiehsch** [comment]
@mapx- maybe it's because you can't predict which redirection occurs first, I remember asking gorhill about such a case and he says all things beeing equal like it would be with your filters thee outcome would be random.

**Comment by mapx-** [comment]
yeah, could be I remember that discussion

**Comment by stephenhawk8054** [comment]
Yeah, I tried @mapx- solution and it works on chromium, but quite concerned about 2 redirections on 1 link.

**Comment by mapx-** [comment]
well, go ahead with removing that filter

**Comment by aaronliu0130** [comment]
Now that was speedy! Thanks!

**Comment by krystian3w** [comment]
so these redirect don't help:

```
$image,redirect-rule=noopframe:100,domain=megaup.net
$image,redirect-rule=1x1.gif:100,domain=megaup.net
```

bug is inside chromium?

**Comment by aaronliu0130** [comment]
@krystian3w  okiehsch has guessed why it doesn't help:

> @mapx- maybe it's because you can't predict which redirection occurs first, I remember asking gorhill about such a case and he said all things beeing equal like it would be with your filters the outcome would be random.

The order is random, causing it to randomly succeed and fail due to the other problematic filter(that was removed). So not chromium bug.

**Comment by krystian3w** [comment]
I just want to rule out that someone forgot about the added feature with overwrite priority.
