### ISSUE TITLE
shavetape.cash: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#12468]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shavetape.cash/e/olq6qXV36PsJ0La/`

### Category

popups

### Describe the issue

opens unwanted tabs(streamtape mirror)
from
`https://ihavenotv.com/gaddafi-mad-dog-of-the-middle-east-evolution-of-evil`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 81214
  cosmetic: 49355
  scriptlet: 19375
  html: 666
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt: 143-4, 17h.23m
    ublock-annoyances: 4382-4, 17h.23m
  default: 
    user-filters: 786-0, never
    ublock-filters: 31166-225, 17h.24m
    ublock-badware: 3951-24, 17h.23m
    ublock-privacy: 208-0, 17h.23m
    ublock-abuse: 72-0, 17h.23m
    ublock-unbreak: 1757-0, 17h.23m
    adguard-mobile: 7408-156, 17h.23m
    easylist: 64848-829, 17h.23m
    easyprivacy: 26722-585, 17h.23m
    urlhaus-1: 7472-0, 17h.23m
    plowe-0: 3687-2, 17h.23m
    ublock-quick-fixes: 143-143, 17h.23m
filterset (user): [array of 608 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 538 ms (selfie)
  maxAssetCacheWait: 216 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    betotodilea.com: 1
    hetaint.com: 1
    yandex.ru: 1
```
</details>

**Comment by ghajini** [comment]
see if this `shavetape.*##+js(nano-stb)` fastup download wait time

`https://shavetape.cash/v/olq6qXV36PsJ0La/`

**Comment by ghajini** [comment]
does this still work?
`strcloud.*,streamtape.*,streamta.*,strtape.*,strtapeadblock.*##+js(set, towait, 0)`

**Comment by stephenhawk8054** [comment]
Ah yeah, looks like `##+js(set, towait, 0)` is obsolete now, `nano-stb` works on my end. But I need to change it a bit to `##+js(nano-stb, , *)` since each video might have different delay after clearing cookies.
