### ISSUE TITLE
Multiple Unblocked Ads audiobookbay.nl

### ISSUE THREAD

**Issue by zero77** [uBlockOrigin/uAssets#1246]
URL:audiobookbay.nl - **Main page**
###rsidebar > ul > li:nth-of-type(2)
###rsidebar > ul > li:nth-of-type(6)
||audiobookbay.nl/images/shields.jpg

URL:audiobookbay.nl/audio-books/points-of-impact-frontlines-book-6-marko-kloos - **Under any entry**
###rsidebar > ul > li:nth-of-type(5)
##.sky
##tr:nth-of-type(31)
##tr:nth-of-type(28)
##tr:nth-of-type(30)
##tr:nth-of-type(29)

**Comment by mapx-** [comment]
add
```
audiobookbay.nl##li:has-text(AD)
audiobookbay.nl##tr:has-text(AD)
audiobookbay.nl##a[href="/shield.php"]
audiobookbay.nl##a[href^="/download-now.php"]
```

**Comment by zero77** [comment]
What are you meaning by “add” and some of the adds at the bottom of the table are still unblocked.

![capture](https://user-images.githubusercontent.com/16563034/34727156-ff96aa9c-f54d-11e7-8a19-9487df7568db.JPG)

**Comment by gorhill** [comment]
Filters for these should be added to the Dutch filter list, report to the maintainers: <https://forums.lanik.us/viewforum.php?f=100>.

**Comment by mapx-** [comment]
added above another 2 filters. I mean add them to your `"my filters"`

**Comment by zero77** [comment]
Ok I will report it although, the domain is Dutch but the website content is in English.

**Comment by zaphodbeebblebrox** [comment]
@mapx-  Sidebar ads.

**Comment by mapx-** [comment]
filters above still working 
https://github.com/uBlockOrigin/uAssets/issues/1246#issuecomment-356302227

**Comment by zero77** [comment]
The site admin is very thorough, and the ads are back again.
Also, I have seen an anti-ad blocker although, I think that is blocked now.
