### ISSUE TITLE
callofwar.com: ads

### ISSUE THREAD

**Issue by Kkidtop** [uBlockOrigin/uAssets#12463]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.callofwar.com/play.php?bust=1&uid=41545915&gameID=5105688&source=browser-desktop`

### Category

ads

### Describe the issue

I see ads even if they are supposed to be blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 96381
  cosmetic: 51002
  scriptlet: 16690
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 26798-25, 1d.17h.24m
    easylist: 64683-95, 1d.17h.23m
    easyprivacy: 26718-438, 1d.17h.22m
    plowe-0: 3671-813, 9d.19h.28m
    ublock-abuse: 72-1, 5d.17h.43m
    ublock-badware: 3941-92, 1d.17h.21m
    ublock-filters: 30579-232, 1d.17h.20m
    ublock-privacy: 200-2, 5d.17h.40m
    ublock-quick-fixes: 144-5, 13h.41m
    ublock-unbreak: 1740-41, 1d.17h.18m
    urlhaus-1: 7472-0, 13h.42m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 468 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    callofwar.com: 8
    bytro.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    rubiconproject.com: 5
```
</details>

**Comment by krystian3w** [comment]
Account required?

**Comment by stephenhawk8054** [comment]
I can't see any ads even after registering and logging in. Can you screenshot it?

**Comment by krystian3w** [comment]
Maybe this opened form pop-up/popunders but then we need origin page with "infection" named as:

- PopMagic
- zfgloaded
