### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#12467]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

This may seem like an odd issue but when I am logged in via my main google account I have white spaces on the top right side of the page. But when I am logged out or logged in with a different google account, there is no white space on the side. I genuinely have no idea what is causing this. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1448" alt="Screen Shot 2022-03-26 at 7 16 16 PM" src="https://user-images.githubusercontent.com/69532417/160263763-1bcf6d7c-1fd5-47e2-9130-7fa27d0ed1e1.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 134030
  cosmetic: 177221
  scriptlet: 34080
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 51168-158, 2d.37m
    adguard-generic: 63038-684, 2d.36m
    adguard-mobile: 7394-48, 2d.41m
    adguard-spyware: 26203-878, 2d.38m
    adguard-spyware-url: 535-13, 2d.39m
    block-lan: 43-0, 7d.37m
    curben-phishing: 10302-0, 2d.29m
    curben-pup: 296-0, 2d.28m
    fanboy-annoyance: 64569-2944, 7d.37m
    fanboy-cookiemonster: 25942-25942, 7d.37m
    ublock-annoyances: 4358-291, 2d.40m
  default: 
    user-filters: 0-0, never
    easylist: 64683-1049, 2d.35m
    easyprivacy: 26718-10537, 2d.33m
    plowe-0: 3671-961, 14d.1h.45m
    ublock-abuse: 72-0, 13d.2h.18m
    ublock-badware: 3941-252, 2d.32m
    ublock-filters: 30577-3424, 2d.31m
    ublock-privacy: 200-40, 13d.2h.14m
    ublock-quick-fixes: 123-8, 2d.26m
    ublock-unbreak: 1740-115, 2d.30m
    urlhaus-1: 7296-1, 2d.27m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1034 ms (selfie)
  maxAssetCacheWait: 735 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    youtube.com: 4
    doubleclick.net: 2
    google.com: 1
    ytimg.com: 1
```
</details>

**Comment by DandelionSprout** [comment]
I am able to reproduce the empty space, but there doesn't seem to be any good methods to fill the space. Even `www.youtube.com##ytd-rich-grid-row:first-of-type:style(--ytd-rich-grid-items-per-row: 2 !important)` seems to forfeit more space than it fills.

**Comment by stephenhawk8054** [comment]
It's YouTube's design and other lines can't collapse to that space.

**Comment by jimmysofat6864** [comment]
@mapx- Does marking as external mean the case is closed or will it be fixed at some point?

**Comment by mapx-** [comment]
as @stephenhawk8054 said:

> It's YouTube's design and other lines can't collapse to that space.

so, it's nothing to be fixed
