### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by jessevoimala** [uBlockOrigin/uAssets#12471]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=UJfOAusuqo8`

### Category

ads

### Describe the issue

video ad before video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79263
  cosmetic: 42023
  scriptlet: 16538
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64687-10, 1d.20h.18m
    easyprivacy: 26718-121, 1d.20h.17m
    plowe-0: 3687-809, 23h.36m
    ublock-abuse: 72-0, 6d.13m
    ublock-badware: 3946-85, 1d.20h.20m
    ublock-filters: 30479-83, 1d.20h.21m
    ublock-privacy: 200-2, 6d.14m
    ublock-quick-fixes: 143-15, 19h.33m
    ublock-unbreak: 1742-41, 1d.20h.19m
    urlhaus-1: 7472-0, 23h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 236 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 57
  blockedDetails: 
    youtube.com: 45
    doubleclick.net: 2
    google.com: 4
    google.fi: 1
    googlesyndication.com: 1
    googlevideo.com: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

other indications:
https://github.com/easylist/easylist/wiki/Youtube-Issues

**Comment by iam-py-test** [comment]
> - [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

This checkbox isn't just there for show. Please check for other issues before opening a new one
