### ISSUE TITLE
ptsplus.tv: breakage

### ISSUE THREAD

**Issue by mysheepb** [uBlockOrigin/uAssets#12470]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ptsplus.tv/season/f0c4b32b-a273-4363-97aa-1260de212437/episode-type/Episode/e2262c76-3f97-4a68-90ca-fde0b361c4d1`

### Category

breakage

### Describe the issue

video won't play when uBlock is enabled, will play when disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79165
  cosmetic: 41922
  scriptlet: 16577
  html: 630
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31056-29, 3d.23h
    ublock-badware: 3929-3, 3d.22h.59m
    ublock-privacy: 204-0, 12d.6h.38m
    ublock-abuse: 72-0, 12d.6h.21m
    ublock-unbreak: 1747-0, 3d.22h.58m
    easylist: 64594-541, 3d.22h.57m
    easyprivacy: 26715-577, 3d.22h.56m
    urlhaus-1: 7472-0, 18h.19m
    plowe-0: 3687-2, 1d.11h.1m
    ublock-quick-fixes: 147-15, 18h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 749 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 2
```
</details>

**Comment by mapx-** [comment]
@mysheepb 
test

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=ptsplus.tv`

If still does not work:
- open the logger, reproduce the issue, go back into the logger and post here a screenshot containing **only the blocked items** you see there 
(you can select only the blocked items in the search box)
