### ISSUE TITLE
app.slack.com: breakage

### ISSUE THREAD

**Issue by vliedel** [uBlockOrigin/uAssets#12475]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.slack.com/client/T03QMNVUM/CB1TQ2C6P/thread/CB1TQ2C6P-1544013501.001500`

### Category

breakage

### Describe the issue

Slack threads won't open anymore and the dark mode is gone with UBO enabled. I see "slackb.com" being red, so that being blocked is probably the issue here.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79731
  cosmetic: 43497
  scriptlet: 16510
  html: 629
listset (total-discarded, last updated): 
  added: 
    NLD-0: 2134-29, 1d.15h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31076-85, 1d.15h.11m
    ublock-badware: 3951-3, 1d.15h.10m
    ublock-privacy: 204-0, 9d.23h.27m
    ublock-abuse: 72-0, 9d.23h.26m
    ublock-unbreak: 1751-0, 1d.15h.9m
    easylist: 64848-583, 1d.15h.8m
    easyprivacy: 26724-577, 1d.15h.7m
    plowe-0: 3687-2, 22h.51m
    urlhaus-1: 7225-0, 6m
    ublock-quick-fixes: 136-4, 7m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1309 ms (selfie)
  maxAssetCacheWait: 1036 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    slack.com: 9
    slackb.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger), reload the page and screenshot it?

**Comment by vliedel** [comment]
Yes, could do that. However, did something already change? Because, when enabling UBO, it now still works. While an hour ago and last week, that was not the case.

**Comment by vliedel** [comment]
Tried restarting firefox, but I can't reproduce it anymore, sorry. Are you still interested in the logs? Else I can just reopen or start a new issue when it breaks again.

**Comment by mapx-** [comment]
For now close yourself this issue (so if happens again just reopen this one)

**Comment by vliedel** [comment]
Alrighty.

**Comment by vliedel** [comment]
So, it's there again: dark theme doesn't load, threads don't load, switching channel sometimes doesn't work.

Here are some screenshots of the logger:

![Screenshot from 2022-04-20 10-07-50](https://user-images.githubusercontent.com/2011969/164181865-085228ab-f893-4d8d-b5cc-831adc2406eb.png)
![Screenshot from 2022-04-20 10-07-38](https://user-images.githubusercontent.com/2011969/164181803-8a7979ca-9a74-4225-b859-e055c75dff17.png)
![Screenshot from 2022-04-20 10-07-30](https://user-images.githubusercontent.com/2011969/164181698-357af8ee-8a1a-43ac-8fe1-1789c336a78e.png)

**Comment by mapx-** [comment]
Once unselected `Sync with OS setting` I was able to use dark theme

![image](https://user-images.githubusercontent.com/10303732/164186401-1bc47f89-fe8e-4807-ae83-76ac96db2ce1.png)

**Comment by vliedel** [comment]
It's not set to sync with OS for me (that option doesn't even show for me).
