### ISSUE TITLE
[nsfw] projectfreetv.one: privacy

### ISSUE THREAD

**Issue by thatguy244** [uBlockOrigin/uAssets#12474]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://projectfreetv.one/`

### Category

privacy

### Describe the issue

dont work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 93
filterset (summary): 
  network: 79144
  cosmetic: 42082
  scriptlet: 16524
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64831-51, 2d.3h.37m
    easyprivacy: 26722-121, 2d.3h.36m
    plowe-0: 3687-809, 2d.3h.35m
    ublock-abuse: 72-0, 2d.3h.33m
    ublock-badware: 3946-85, 2d.3h.31m
    ublock-filters: 30473-83, 2d.3h.30m
    ublock-privacy: 203-2, 2d.3h.29m
    ublock-unbreak: 1742-41, 2d.3h.28m
    urlhaus-1: 7294-0, 1d.1h.20m
    ublock-quick-fixes: 143-15, 1d.1h.19m
filterset (user): [empty]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11705 ms
  maxAssetCacheWait: 924 ms
popupPanel: 
  blocked: 12
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    2embed.ru: 5
    addthis.com: 1
    cloudflare.com: 1
    cloudflareinsights.com: 1
    google.com: 1
    googletagmanager.com: 1
    gstatic.com: 1
    jsdelivr.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
What exactly `dont work`? Please describe the issues and the steps to reproduce in more details.

```
Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
```

**Comment by JobcenterTycoon** [comment]
@thatguy244 because you enabled no-scripting, no-large-media and more in the popup panel.
