### ISSUE TITLE
wi.cr [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1247]
URL(s) where the issue occurs

`http://wi.cr/EVrYHy7`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SkeletalDemise** [comment]
@jspenguin2017 7 second timer.

**Comment by lain566** [comment]
There's a popup.
 Same as `https://github.com/uBlockOrigin/uAssets/issues/2751`
