### ISSUE TITLE
disneymusicemporium.com: breakage

### ISSUE THREAD

**Issue by Kiwipous** [uBlockOrigin/uAssets#12473]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.disneymusicemporium.com/`

### Category

breakage

### Describe the issue

Blank white page.
(DuckDuckGo privacy protection disabled and doesn't work. 
Does work when disabling uBlock)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-03-27 190214](https://user-images.githubusercontent.com/51043725/160292351-466a4b46-e3af-4908-9635-44fa48669c20.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 96286
  cosmetic: 50992
  scriptlet: 16645
  html: 630
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31166-29, 2d.22h.7m
    ublock-badware: 3950-3, 2d.22h.6m
    ublock-privacy: 204-0, 11d.11m
    ublock-abuse: 72-0, 11d.10m
    ublock-unbreak: 1751-0, 2d.22h.4m
    easylist: 64679-624, 2d.22h.3m
    easyprivacy: 26718-577, 2d.22h.2m
    urlhaus-1: 7355-0, 1h.27m
    plowe-0: 3687-2, 2d.2h.5m
    FRA-0: 26798-507, 2d.22h.8m
    ublock-quick-fixes: 136-15, 1h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 291 ms (selfie)
  maxAssetCacheWait: 193 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    bing.com: 1
    musictoday.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
disneymusicemporium.com##body:style(display: initial !important;)
```

**Comment by okiehsch** [comment]
It's caused by `://go.*/|$script,3p` in the french regional list and it's blocking a CNAME request hence it only breaks Firefox.

**Comment by okiehsch** [comment]
@adamwr I used
`@@||go.musictoday.com^$script,domain=disneymusicemporium.com`

**Comment by mapx-** [comment]
absolutely insane filter ..
`://go.*/|$script,3p`

**Comment by krystian3w** [comment]
@fyi smed79

**Comment by smed79** [comment]
Removed https://github.com/easylist/listefr/commit/7b2c86d05bd5bc6f7b2075428460a74648962d9a
