### ISSUE TITLE
chd4.com: detection

### ISSUE THREAD

**Issue by NichirinSword** [uBlockOrigin/uAssets#12479]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chd4.com/index.php`

### Category

detection

### Describe the issue

After login, it shows an adblocker detection screen

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot 2022-03-28 221702](https://user-images.githubusercontent.com/98078687/160442372-a7dd24e8-4a2e-4172-b174-1ab4269caac0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82997
  cosmetic: 43931
  scriptlet: 37587
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25591-22, 8m
    ublock-annoyances: 4337-43, 8h.21m
  default: 
    user-filters: 2-0, never
    easylist: 64886-57, 8h.24m
    easyprivacy: 26726-121, 8h.23m
    plowe-0: 3690-810, 6d.8h.13m
    ublock-abuse: 72-1, 8h.22m
    ublock-badware: 3953-86, 8h.19m
    ublock-filters: 30462-3155, 8h.18m
    ublock-privacy: 203-2, 8h.17m
    ublock-quick-fixes: 138-15, 8h.15m
    ublock-unbreak: 1741-42, 8h.16m
    urlhaus-1: 7225-0, 8h.14m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2462 ms (selfie)
  maxAssetCacheWait: 1653 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    chd4.com: 1
    doubleclick.net: 1
    googlesyndication.com: 3
    imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
> CrazyHD.com is invitation only

https://github.com/uBlockOrigin/uAssets/issues/12092
