### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by axpekt** [uBlockOrigin/uAssets#12472]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/?hl=pl&gl=PL`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80377
  cosmetic: 49302
  scriptlet: 16828
  html: 0
listset (total-discarded, last updated): 
  added: 
    POL-0: 7789-8, 17h.56m
    POL-2: 1273-13, 1d.18h.52m
  default: 
    user-filters: 0-0, never
    easylist: 64648-34, 3d.16h.8m
    easyprivacy: 26715-121, 3d.16h.7m
    plowe-0: 3671-814, 11d.19h.9m
    ublock-abuse: 72-0, 11d.22h.24m
    ublock-badware: 3925-84, 3d.16h.6m
    ublock-filters: 30581-120, 3d.16h.11m
    ublock-privacy: 200-2, 11d.22h.25m
    ublock-unbreak: 1736-42, 3d.16h.9m
    urlhaus-1: 7294-0, 17h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1286 ms (selfie)
  maxAssetCacheWait: 414 ms
popupPanel: 
  blocked: 158
  blockedDetails: 
    doubleclick.net: 7
    google.com: 8
    google.pl: 1
    googlesyndication.com: 3
    googlevideo.com: 9
    youtube.com: 130
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

other indications:
https://github.com/easylist/easylist/wiki/Youtube-Issues
