### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Norvelas** [uBlockOrigin/uAssets#12487]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ads show up randomly in the beginning, or in the middle, of the stream

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81065
  cosmetic: 42151
  scriptlet: 16481
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64952-51, now
    easyprivacy: 26733-121, now
    plowe-0: 3687-809, now
    ublock-abuse: 72-0, now
    ublock-badware: 3964-86, now
    ublock-filters: 30469-86, now
    ublock-privacy: 205-2, now
    ublock-quick-fixes: 135-15, now
    ublock-unbreak: 1741-41, now
    urlhaus-1: 9105-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 419 ms (selfie)
  maxAssetCacheWait: 233 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    amazon-adsystem.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22twitch.tv%22+in%3Atitle

**Comment by Joscpe** [comment]
I see all of these issues are closed. But I haven't read anything about work being done to prevent these Twitch video ads...

**Comment by mapx-** [comment]
You'll find here some answers / alternative player
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/

**Comment by JobcenterTycoon** [comment]
@Joscpe it got fixed multiply times but twitch fast circuvent the ad blocking script after it got added to uBO

Try the `Alternate Player for Twitch.tv` addon
