### ISSUE TITLE
alloschool.com: privacy

### ISSUE THREAD

**Issue by MHAMEX** [uBlockOrigin/uAssets#12480]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.alloschool.com/element/77219`

### Category

privacy

### Describe the issue

#This website cannot be reached `www.alloschool.com` took too long to respond.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-03-28_194525](https://user-images.githubusercontent.com/100492482/160475005-7d9d61a2-d669-472d-a139-72aabb2cdd00.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 99483
  cosmetic: 51816
  scriptlet: 16683
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 26798-25, 4d.15m
    ara-0: 2558-7, 1h.42m
    easylist: 64679-96, 4d.17m
    easyprivacy: 26718-443, 4d.14m
    plowe-0: 3715-816, never
    ublock-abuse: 72-1, 12d.22h.10m
    ublock-badware: 3946-92, 4d.13m
    ublock-filters: 30583-234, 4d.12m
    ublock-privacy: 200-2, 12d.22h.6m
    ublock-quick-fixes: 135-15, 1h.40m
    ublock-unbreak: 1740-41, 4d.11m
    urlhaus-1: 8819-0, 1h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6683 ms (selfie)
  maxAssetCacheWait: 7182 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Did you test with uBO disabled ?
