### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by 17robots** [uBlockOrigin/uAssets#12483]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/collection/tracks`

### Category

breakage

### Describe the issue

Songs skip until ad. Ads skip and then I can play songs. I only get 10 seconds of the song before audio cuts out. Song timer still moves but no audio is heard. When turned off, I get the songs and ads, but things function normally.

As an FYI, I do run https://github.com/arkenfox/user.js rules for firefox. I will be undoing these and testing again to see if the issue still persists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 99
filterset (summary): 
  network: 78976
  cosmetic: 40293
  scriptlet: 16388
  html: 618
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30802-27, never
    ublock-badware: 3989-3, never
    ublock-privacy: 202-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1727-0, never
    easylist: 62254-540, never
    easyprivacy: 26549-482, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-2, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 200 ms
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
    scdn.co: 1
    sentry.io: 3
```
</details>

**Comment by mapx-** [comment]
does this exception help ?

`@@||sentry.io/api/$xhr,domain=open.spotify.com`

**Comment by 17robots** [comment]
Where do I put the exception at?

**Comment by stephenhawk8054** [comment]
> Where do I put the exception at?

Click on [the gear icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), then go to [My filters pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

**Comment by 17robots** [comment]
Tried the filter, I was getting the same behavior.

**Comment by stephenhawk8054** [comment]
I tested with arkenfox + spotify free account but couldn't reproduce the issue. Can you test with a new profile and force update the filter lists?
