### ISSUE TITLE
4dayweek.io: ads

### ISSUE THREAD

**Issue by r8u** [uBlockOrigin/uAssets#12488]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://4dayweek.io/`

### Describe the issue

"Sponsored" listings are still showed, should be considered ads

### Screenshot(s)

https://i.imgur.com/e6IObFV.png

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 99.0.4844.82

### Settings

N/A_

**Comment by mapx-** [comment]
add

`4dayweek.io##.notadvert-tile-wrapper`

@ryanbr
