### ISSUE TITLE
customerconnect.vmware.com: breakage

### ISSUE THREAD

**Issue by agottschling** [uBlockOrigin/uAssets#12481]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://customerconnect.vmware.com/group/vmware/evalcenter?p=free-esxi7`

### Category

breakage

### Describe the issue

On VMWare's download portal, clicking the download buttons doesn't start the download. This does require being logged in, but the ESXi hypervisor is a free download. Disabling uBlock Origin allows the download to start. Feel free to ask if you need help diagnosing or checking a fix.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8459640/160499123-713328fa-eb99-484c-8711-2069c53c3148.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80756
  cosmetic: 42136
  scriptlet: 16508
  html: 629
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 31091-95, 1d.10h.17m
    ublock-badware: 3951-3, 1d.10h.14m
    ublock-privacy: 208-0, 23h.5m
    ublock-abuse: 72-0, 23h.4m
    ublock-unbreak: 1751-0, 1d.10h.16m
    easylist: 64950-529, 13m
    easyprivacy: 26726-577, 1d.10h.15m
    plowe-0: 3691-2, 4d.16h.14m
    urlhaus-1: 8819-0, 15m
    ublock-quick-fixes: 134-4, 14m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 25 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6511 ms (selfie)
  maxAssetCacheWait: 2877 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  blockedDetails: 
    vmware.com: 3
    bing.com: 1
    go-mpulse.net: 1
    tiqcdn.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like the filter `/utag.sync.` in EP causes issue

```
@@||tags.tiqcdn.com/utag/vmware/myvmware-privacy/prod/utag.sync.js$script,domain=customerconnect.vmware.com
```

@ryanbr 

Here's a test account (email and pass):

```
a16dc70371@catdogmail.live
zxZX12!@
```
