### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by CoderViki** [uBlockOrigin/uAssets#12485]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=ouNksHi-MmE`

### Category

ads

### Describe the issue

I came across a youtube video ad. (2 times)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_4](https://user-images.githubusercontent.com/53264005/160608253-06ebcd49-90fe-4114-895d-af86d2ed79aa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 82778
  cosmetic: 48815
  scriptlet: 16936
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    TUR-0: 9244-144, 2d.16h.44m
    easylist: 64848-68, 2d.16h.43m
    easyprivacy: 26724-126, 2d.16h.42m
    plowe-0: 3690-811, 5d.23h.29m
    ublock-abuse: 72-0, 1d.23h.11m
    ublock-badware: 3947-86, 2d.16h.41m
    ublock-filters: 30498-94, 2d.16h.2m
    ublock-privacy: 203-2, 1d.23h.10m
    ublock-unbreak: 1741-41, 2d.16h.1m
    urlhaus-1: 9079-0, 1h.12m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2314 ms (selfie)
  maxAssetCacheWait: 1161 ms
popupPanel: 
  blocked: 332
  blockedDetails: 
    youtube.com: 254
    doubleclick.net: 14
    google.com: 25
    google.com.tr: 1
    googlesyndication.com: 14
    googlevideo.com: 24
```
</details>

**Comment by MasterKia** [comment]
> [x] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by mapx-** [comment]
other indications:
https://github.com/easylist/easylist/wiki/Youtube-Issues
