### ISSUE TITLE
forestapp.cc: breakage

### ISSUE THREAD

**Issue by Crowley45** [uBlockOrigin/uAssets#12493]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.forestapp.cc/`

### Category

breakage

### Describe the issue

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 97408
  cosmetic: 64016
  scriptlet: 17667
  html: 633
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31064-29, 3d.10h.30m
    ublock-badware: 3950-3, 3d.10h.29m
    ublock-privacy: 208-0, 3d.10h.28m
    ublock-abuse: 72-0, 3d.10h.27m
    ublock-unbreak: 1753-0, 3d.10h.26m
    easylist: 64845-199, 3d.10h.14m
    easyprivacy: 26722-684, 3d.10h.13m
    urlhaus-1: 7431-0, 49m
    plowe-0: 3687-371, 3d.10h.11m
    RUS-0: 41418-61, 1d.7h.51m
    ublock-quick-fixes: 134-15, 50m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3589 ms (selfie)
  maxAssetCacheWait: 2424 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> breakage

What is broken ? Provide steps to reproduce it

**Comment by mapx-** [comment]
Weird, I already see all that text ..
