### ISSUE TITLE
Zerohedge pop-up for email deliveries

### ISSUE THREAD

**Issue by roadhazard** [uBlockOrigin/uAssets#12496]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`www.zerohedge.com`

### Describe the issue

To reproduce, go to zerohedge . com and click on any news story. Once the story loads, move your mouse to the very top of your browser. ZH can detect that you're maybe about to close the window or navigate away. It pops up a box asking if you'd like to have stories delivered to your inbox. A LONG time ago, I used the picker tool in UBO and was easily able to get rid of it by using the 'element picker mode' and clicked the box and created my custom pick and it was gone, never to return. But, they must have changed something because this no longer works. It hasn't in a while....just been too lazy to create an issue. :)

I think this is the offending HTML that UBO just can't make go away.....and stay away:
`||www.zerohedge.com/images/Backgrounds/exit-modal.jpg`

### Screenshot(s)

![zerohedge](https://user-images.githubusercontent.com/30935039/160697991-8b47ea50-2f4a-44a9-b2e8-84f968972ea3.png)

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.2

### Settings

No changes, other the trying to create my custom pick referenced above.....which doesn't work.

**Comment by mapx-** [comment]
test

`zerohedge.com##+js(aeld, mouseout)`
