### ISSUE TITLE
speedrun.com

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#12497]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.speedrun.com/`

### Describe the issue

There are ads along the sides and top of the page. Doesn't always seem to happen on the homepage, just sometimes.

### Screenshot(s)

https://i.imgur.com/eP8zajw.png

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.2

### Settings

Just have a couple of custom filters to block stuff on fandom, but that's it.

### Notes

Not much to be said here, i could block the adds with the element picker, but new ones will just show up that way.

**Comment by mapx-** [comment]
test 

`speedrun.com##+js(no-fetch-if, cloud)`

test for breakage too

**Comment by rmcin329** [comment]
That appears to fix it, went through several pages, no ads seen. Thanks for the help.

**Comment by BlazingRaven495** [comment]
Its happening again. even when trying to block ads manually, they all come back.

I tried mapx's fix, but either i don't know how to use it properly (very likely) or it no longer works and SRC has circumvented Origin's blocking.

![image](https://github.com/uBlockOrigin/uAssets/assets/80185013/784225e3-1a2d-45c5-b8d0-46f2e6c23ae3)

**Comment by stephenhawk8054** [comment]
@BlazingRaven495 Does this work?

```adb
||any-pct.speedrun.com/cargo.js
```

**Comment by BlazingRaven495** [comment]
> @BlazingRaven495 Does this work?
> 
> ```
> ||any-pct.speedrun.com/cargo.js
> ```

seems to be. i got rid of my manuals and put this in and it works now. thanks.
