### ISSUE TITLE
Can't get custom filter to download after fresh install

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#12490]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NA

### Describe the issue

After re-installing ublock origin the custom filter https://s3amazonaws.com/lists.disconnect.me/simple_malvertising.txt refuses to download.

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.2

### Settings

Default, with a custom filter or 2 for fandom.

### Notes

Tried purging all caches and updating, tried waiting several minutes as well, list just flat refuses to update.

**Comment by stephenhawk8054** [comment]
That link is dead, you can try opening it in your browsers.

**Comment by mapx-** [comment]
I guess the real link is:
`https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt`
