### ISSUE TITLE
imgpart.com [ADS] [Pop-up] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1249]
URL(s) where the issue occurs

`http://imgpart.com/img-59deed8303c07.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zaphodbeebblebrox** [comment]
@mapx- ads, fixed by `||rilnali.ru^$domain=imgpart.com`.

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
