### ISSUE TITLE
hotslogs.com adblock redirect

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uAssets#125]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.hotslogs.com/`

### Describe the issue

Posting this from a [thread](https://www.reddit.com/r/ublock/comments/50gzv4/website_is_detecting_ublock_unable_to_view_unless/) I saw over on https://reddit.com/r/ublock

I am currently unable to view this website once I try and click any character links. Doing so redirects me to this link: http://www.hotslogs.com/Info/AdBlock

until I have disabled adblock.

I have Chrome + Tampermonkey + Anti-Adblock Killer | Reek installed but I can not seem to bypass this website unless both Tampermonkey and uBlock are disabled.

### Screenshot(s)

None needed

### Versions

- Browser/version: Version 52.0.2743.116 m (64-bit)
- uBlock Origin version: 1.9.4

### Settings

https://i.imgur.com/8SxXWTK.png

### Filter Lists
 My filters‎ : 1,251 used out of 1,348
 uBlock filters‎ : 908 used out of 911
 uBlock filters – Badware risks‎  (github.com)
 uBlock filters – Experimental‎  (github.com)
 uBlock filters – Privacy‎
 uBlock filters – Unbreak‎

Ads (4)
 Adblock Warning Removal List‎ (forums.lanik.us): 218 used out of 229
 Anti-Adblock Killer | Reek‎  (github.com): 2,009 used out of 2,009
 EasyList‎ (forums.lanik.us): 66,679 used out of 66,787
 
Privacy (2)
Basic tracking list by Disconnect‎ : 29 used out of 34
 EasyPrivacy‎ (forums.lanik.us): 11,865 used out of 11,913

Malware domains (5)
 Malvertising filter list by Disconnect‎ : 358 used out of 5,692
 Malware Domain List‎ (malwaredomainlist.com): 1,233 used out of 1,233
 Malware domains‎ (www.malwaredomains.com): 23,019 used out of 23,103
 Malware filter list by Disconnect‎ : 178 used out of 2,956p
 Spam404‎ (www.spam404.com): 5,581 used out of 5,581

Social (2) 
Anti-ThirdpartySocial (see warning inside list)‎ (forums.lanik.us): 65 used out of 65
 Fanboy’s Annoyance List‎ (forums.lanik.us): 23,749 used out of 24,016

Regions, languages (1) 
EU: Prebake - Filter Obtrusive Cookie Notices‎ (github.com): 859 used out of 862

Custom (1)
 https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/c73ccfecda7c277f894e9eb2dd2f5a0806b29a82/gistfile1.txt‎ : 4 used out of 4

### Notes

The following filter seems to kill the redirect, posting here for information purposes if @gorhill wants to research this script further and/or add the following filter to uBlock filter list.

`||www.hotslogs.com/Sitewide/HeroDetails$inline-script,domain=www.hotslogs.com`

**Comment by zummuz** [comment]
> ||www.hotslogs.com/Sitewide/HeroDetails$inline-script,domain=www.hotslogs.com

It breaks site's functions. https://www.reddit.com/r/ublock/comments/50gzv4/website_is_detecting_ublock_unable_to_view_unless/d742c2n

**Comment by jjohns71** [comment]
Does this updated filter work but not break other site functionality? Just setting the filter to block all inline scripts with this one. I tested on Leaderboard and Statistics tab of the site and it seems to load but it could also be blocking some site functionality I am unaware of so please test and confirm everything else works as it should.

`||www.hotslogs.com$inline-script,domain=www.hotslogs.com`

**Comment by Xbye** [comment]
> ||www.hotslogs.com$inline-script,domain=www.hotslogs.com
Hello, I am the poster from /r/uBlock subreddit -
https://www.reddit.com/r/ublock/comments/50gzv4/website_is_detecting_ublock_unable_to_view_unless/d745545

Post:
>Nice, that script works site-wide. Unfortunately the site functionality isn't working still on any of the ad-filled pages:
http://i.imgur.com/SoUaTER.jpg  - Showing functionality without uBlock/Tampermonkey
Thank you very much for your help so far :)

**Comment by gorhill** [comment]
How about: `@@||d3pkae9owd2lcf.cloudfront.net/mb105.gz.js$script,domain=hotslogs.com`.

**Comment by Xbye** [comment]
>How about: **`@@||d3pkae9owd2lcf.cloudfront.net/mb105.gz.js$script,domain=hotslogs.com`** .

This seems to have done the trick! Able to access several different pages and site functionality _(Drop-down menus and panels)_ are interactable. I will update my reddit post with this fix.

**Comment by gorhill** [comment]
You should submit the filter to EasyList maintainers, it works also for ABP.

**Comment by gorhill** [comment]
Looks like this was already reported to EasyList: <https://forums.lanik.us/viewtopic.php?f=62&t=32007>.

**Comment by rickyars** [comment]
can you explain how to add this to ABP? i've been messing with the custom filter but can't get it to work. i must be doing something wrong.

**Comment by cicuz** [comment]
Isn't that just whitelisting the whole thing?

**Comment by IDKwhattoputhere** [comment]
On my side there's only this single script allowed and the resulting requests appear blocked. So if "the whole thing" is a single script then yes. If not then no. Please be a little bit more specific.

**Comment by gorhill** [comment]
> Isn't that just whitelisting the whole thing?

"[T]he whole thing"? Here is the difference between an exception filter for that one specific script, and whitelisting the site -- left side is allowing that one specific script, right side is whitelisting the site (a gray cell means no network requests occurred for the hostname):

![a](https://cloud.githubusercontent.com/assets/585534/18991817/db540672-86e8-11e6-95c9-1dcfe0588bc7.png)

My mistake however is that I put this exception filter in _"uBlock filters"_ rather than _"uBlock filters -- Unbreak"_.

**Comment by gorhill** [comment]
Note that I do not have the time to spare to find more fancy solution, this was probably the case back then. I looked at it again this morning, and found the time to create a small neutered script as replacement solution.

**Comment by cicuz** [comment]
By looking at the code, it seemed that that one was the "main" script responsible for the greatest part of the ad/tracking operations.. This looks great, thank you very much for that!

**Comment by gorhill** [comment]
> that one was the "main" script responsible for the greatest part of the ad/tracking operations

Absolutely not, look at the output of the HAR parser above. "Tracking" would be an issue if `d3pkae9owd2lcf.cloudfront.net` was an ubiquitous server throughout the web, but it's not. The ads that script tried to pull were all blocked (again, see HAR). There was no other issue than executing some javascript which purpose was foiled by other filters, and which allowed the site to function without the user being forced to whitelist it (with the content of the right pane above as a result).

**Comment by Hrxn** [comment]
> The tool used above is available to everybody: http://raymondhill.net/httpsb/har-parser.html.

Great, thanks a lot!
