### ISSUE TITLE
Broken when using AdGuard Annoyances filter https://cafe.naver.com/optimuslteuser 

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [uBlockOrigin/uAssets#12501]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://cafe.naver.com/optimuslteuser
https://cafe.naver.com/anycallusershow
https://cafe.naver.com/*

### Describe the issue

When using AdGuard Annoyances filter on ublock origin, this site does not look normally.

This is the AdGuard Annoyances filter's
"cafe.naver.com##+js(set-constant, document.body.oncopy, null)"
I think it's because of the rules.

Can you add a rule to uBlock filters – Annoyances to solve this problem?
cafe.naver.com#@#+js(set-constant, document.body.oncopy, null) 

### Screenshot(s)

![1](https://user-images.githubusercontent.com/101787143/160759422-93cb5a32-ed45-471c-8f9e-a2f18a77cc07.png)
![2](https://user-images.githubusercontent.com/101787143/160759426-8fce8a81-1602-4951-a59f-bd9bf4cd481d.png)

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Microsoft Edge 99.0.1150.55

### Settings

Subscribe to AdGuard Annoyances filter
Subscribe to uBlock filters – Annoyances 

### Notes

This is the AdGuard Annoyances filter's
"cafe.naver.com##+js(set-constant, document.body.oncopy, null)"
I think it's because of the rules.

Can you add a rule to uBlock filters – Annoyances to solve this problem?
cafe.naver.com#@#+js(set-constant, document.body.oncopy, null)

**Comment by adranger** [comment]
Please use this page to report problems with the AdGuard filters: https://reports.adguard.com/en/new_issue.html?product_type=Other

**Comment by mapx-** [comment]
@Yuki2718

**Comment by 88Va2wFDcYd1CT** [comment]
All right. thank you
