### ISSUE TITLE
imagecrest.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1250]
URL(s) where the issue occurs

`http://www.imagecrest.com/view/im1veulrlc`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters @mapx-
