### ISSUE TITLE
something with a link protection service (acorta-enlace.com) from atomixhq.link

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#12507]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://atomixhq.link/descargar/torrent/serie/caballero-luna/temporada-1/capitulo-01/
https://atomtt.com/t_download/171818/caballero-luna---temporada-1/
```

### Describe the issue

the site atomtt.com is loaded after click on a link on atomixhq.link (in this case, the link was
 `https://atomixhq.link/descargar/torrent/serie/caballero-luna/temporada-1/capitulo-01/`
)
first time you access with ublock, it opens acorta-enlace link protection (you click on the first result of a google search, a timer appears of 30 seconds, after that you can access the link).
the second link you click (and any other after that) when you click on the red button "descargar ahora" (download now) you return to the first link (atomixhq.link blah blah blah), clicking on it, return to atomtt and back over and over.
you need to disable ublock to access the content... after about 20 popups and false file downloads and garbage like that.

### Notes

As it seems to work once each day, and the link protection (acorta-enlace) is supposed to work for 24 hours maybe is something it stores which is not working through ublock? No idea really, just supposing about it...

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 84196
  cosmetic: 46749
  scriptlet: 16668
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64990-51, 19h.7m
    easyprivacy: 26733-121, 19h.7m
    plowe-0: 3690-809, 19h.7m
    spa-0: 3832-33, 19h.7m
    spa-1: 4287-166, 19h.7m
    ublock-abuse: 72-0, 19h.7m
    ublock-badware: 3984-86, 19h.7m
    ublock-filters: 30467-142, 19h.7m
    ublock-privacy: 205-2, 19h.7m
    ublock-quick-fixes: 135-15, 19h.7m
    ublock-unbreak: 1741-42, 19h.7m
    urlhaus-1: 9105-0, 19h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms (selfie)
  maxAssetCacheWait: 242 ms
```
</details>

**Comment by Procyon-b** [comment]
I'm unable to reproduce. To make sure that it's not already fixed in a filter, open ublock's dashboard, go to the "Filter lists" tab, click "Purge all caches" and "Update now".
Reload the website to verify if the problem persists.

**Comment by helpman** [comment]
I already tried that with no effect.
Try going to atomixhq.link, select any content, try ro download it. It will display the details, then a popup with the link protection. After waiting 30 second the link will be available and you can get it. Then close it. The protection should be available for 24 hours and no longer ask you to visita site and wait other 30 second, but instead of that, when you click the button to download it, you'll return to the content detail, click again, and will see the download button, click and back to the details and repeat, repeat, repeat...

**Comment by stephenhawk8054** [comment]
Can you check if adding these work for you?

```
/^https?:\/\/.*\.(jpg|gif|png|php|svg|ico|js|txt)/$popup,domain=animeflv.la|atomixhq.art|atomixhq.link|atomixhq.top|cliver.to|doramasflixs.com|gnula.nu|gnula.se|ibb.co|jkanime.net|myflixertv.to|pctreload1.com|pelishouse.me|pelismart.com|pelismarthd.com|pelisplus2.io|pelispop.me|pelispophd.com|seriesflix.live|seriesturcas.tv|tomatomatela.com|xn--solopeliculasespaol-c4b.com,badfilter
/^https?:\/\/.*\.(jpg|gif|png|php|svg|ico|js|txt)/$popup,domain=animeflv.la|atomixhq.art|atomixhq.top|cliver.to|doramasflixs.com|gnula.nu|gnula.se|ibb.co|jkanime.net|myflixertv.to|pctreload1.com|pelishouse.me|pelismart.com|pelismarthd.com|pelisplus2.io|pelispop.me|pelispophd.com|seriesflix.live|seriesturcas.tv|tomatomatela.com|xn--solopeliculasespaol-c4b.com
```

**Comment by stephenhawk8054** [comment]
I cannot reproduce either. After getting the link to download, closing the `atomtt.com` site and repeating the steps with `atomixhq.link` URL, it generates direct link without waiting as expected.

**Comment by helpman** [comment]
The custom filter you advised me to use works perfectly. I tried again without it, and the loop is back. Add that custom filter, and works. I don't know why you can't reproduce it. Default configuration, filters updated, no other popup or adblocker installed... weird. I'm going to delete all cookies from that site just in case
