### ISSUE TITLE
9anime.id: popups

### ISSUE THREAD

**Issue by Zancral** [uBlockOrigin/uAssets#12508]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/jujutsu-kaisen.32n8/ep-18`

### Category

popups

### Describe the issue

on occasion when clicking anywhere on the screen it will force open a nsfw tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79353
  cosmetic: 42139
  scriptlet: 16509
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64950-51, 1d.16h.23m
    easyprivacy: 26726-121, 2d.19h.40m
    plowe-0: 3671-805, 12d.22h.27m
    ublock-abuse: 72-0, 11d.19h.15m
    ublock-badware: 3953-86, 2d.23h.43m
    ublock-filters: 30484-86, 2d.23h.44m
    ublock-privacy: 200-2, 11d.19h.13m
    ublock-quick-fixes: 135-15, 19h.58m
    ublock-unbreak: 1741-41, 1d
    urlhaus-1: 7431-0, 19h.59m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 259 ms (selfie)
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    9anime.id: 2
    addthis.com: 1
    amung.us: 1
    apus.tech: 2
    bidgear.com: 4
    cloudflareinsights.com: 1
    googletagmanager.com: 1
    snagbaudhulas.com: 1
```
</details>

**Comment by Zancral** [comment]
I did not do any of the first three check marks, everything else is true

**Comment by okiehsch** [comment]
I can't reproduce, 
`on occasion when clicking anywhere on the screen it will force open a nsfw tab`
is rather vague, are you watching a video when this happens, are you just browsing, etc?

> I did not do any of the first three check marks

Try updating your lists and see if that helps. The third check mark.
