### ISSUE TITLE
google.ro: nuisance

### ISSUE THREAD

**Issue by hellcry37** [uBlockOrigin/uAssets#12509]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.ro/maps/dir/''/Strada+Vasile+Lucaciu+117,+Bucure%C8%99ti+030167/@44.4224606,26.1181187,16z/data=!4m14!4m13!1m5!1m1!1s0x40b1ff02b6d0c9c5:0xd748d86d43f5bdc!2m2!1d26.1133693!2d44.416683!1m5!1m1!1s0x40b1ff266634a22b:0x3f3ee594e40fff91!2m2!1d26.1244321!2d44.4319043!3e2?hl=ro`

### Category

nuisance

### Describe the issue

google maps looks bad and elements are black or half graphics

most sure is from "Peter Lowe’s Ad and tracking server list"

I see if I disable this, then all seem to work ok

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 80832
  cosmetic: 42177
  scriptlet: 16456
  html: 630
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 10h.37m
  default: 
    user-filters: 35-0, never
    ublock-filters: 31052-97, 1d.11h.14m
    ublock-badware: 3957-3, 1d.11h.22m
    ublock-privacy: 204-0, 10d.53m
    ublock-abuse: 72-0, 10d.51m
    ublock-unbreak: 1752-0, 1d.11h.20m
    easylist: 64950-516, 1d.11h.18m
    easyprivacy: 26732-585, 1d.11h.16m
    plowe-0: 3671-2, 12d.12h.22m
    urlhaus-1: 8896-0, 3h.33m
    ublock-quick-fixes: 138-4, 3h.35m
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 31 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 438 ms (selfie)
  maxAssetCacheWait: 116 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    google.ro: 16
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
I see nothing wrong.

Update all your filter lists, disable all other addons, test again

**Comment by hellcry37** [comment]
already did this many times, tested everything, it's fine if this can not be solved is okay, thanks. just close it

**Comment by hellcry37** [comment]
i'll post some images soon

**Comment by mapx-** [comment]
for example Peter Lowe's list was updated 12 days ago
    plowe-0: 3671-2, 12d.12h.22m

**Comment by hellcry37** [comment]
[Img1](https://ibb.co/FzfrKVk)
[Img2](https://ibb.co/rcJM9X0)

This problem is from almost a year old

**Comment by hellcry37** [comment]
this is how it looks (should normally look) with that list disabled

[Normal look](https://ibb.co/qN8xFcm)

**Comment by mapx-** [comment]
> Peter Lowe's list was updated 12 days ago

Did you update it **now** ?

**Comment by okiehsch** [comment]
>   blockedDetails: 
    google.ro: 16
    googlesyndication.com: 1

I can't see how that could be caused by Peter Lowe's list, the only thing that list can block here is `googlesyncdication` and that can't cause this,

**Comment by mapx-** [comment]
If still does not work:
- remove & reinstall uBO
- update all the lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by hellcry37** [comment]
Removed addon, closed browser, reinstall everything default, updated all filter lists, open the website again everything choppy again

[link](https://ibb.co/Js8gN9V)

then disabled again Peter Lowe’s Ad and tracking server list

[link](https://ibb.co/qgKHzDw)

**Comment by stephenhawk8054** [comment]
The site looks normal for me with Peter Lowe's list enabled

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/160972179-cdc5306f-c9c4-45d2-9e87-16f52297d8cd.png)

</details>

**Comment by hellcry37** [comment]
ok thank you for everything, it's fine not a big dial.
