### ISSUE TITLE
rustorka.games-pc.top: detection

### ISSUE THREAD

**Issue by Gorakil** [uBlockOrigin/uAssets#12504]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rustorka.games-pc.top/forum/index.php`

### Category

detection

### Describe the issue

Показывает грустного котенка с надписью, что я использую блокировщик.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 114276
  cosmetic: 93767
  scriptlet: 29140
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41450-9, 9h.3m
    adguard-generic: 63054-875, 2d.11h.7m
  default: 
    user-filters: 25-0, never
    easylist: 64869-850, 2d.11h.11m
    easyprivacy: 26726-311, 2d.20h.13m
    plowe-0: 3690-825, 5h.2m
    ublock-abuse: 72-1, 1d.17h.7m
    ublock-badware: 3953-258, 2d.11h.10m
    ublock-filters: 30503-3090, 2d.11h.9m
    ublock-privacy: 205-2, 1d.17h.6m
    ublock-unbreak: 1740-84, 2d.11h.8m
    urlhaus-1: 7431-0, 17h.4m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1814 ms (selfie)
  maxAssetCacheWait: 894 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    games-pc.top: 1
    aj1907.online: 2
    jsdelivr.net: 1
    yadro.ru: 1
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce a "sad kitten", maybe one needs to be logged in?

**Comment by Gorakil** [comment]
> I can't reproduce a "sad kitten", maybe one needs to be logged in?

Yeah looks like appears only after log in.

**Comment by stephenhawk8054** [comment]
You should add `RU AdList: Counters` list: [https://github.com/easylist/ruadlist/wiki/RU-Adlist-links](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links)

**Comment by Gorakil** [comment]
> You should add `RU AdList: Counters` list: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

This one works. Thnx!
