### ISSUE TITLE
193.164.131.42: ads

### ISSUE THREAD

**Issue by FayZia** [uBlockOrigin/uAssets#12510]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://193.164.131.42/nonton-movie/`

### Category

ads

### Describe the issue

there is still ads on the web

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 84697
  cosmetic: 23550
  scriptlet: 16419
  html: 621
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30899-327, never
    ublock-badware: 3989-3, never
    ublock-privacy: 202-1, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1733-0, never
    adguard-mobile: 7431-321, never
    easylist: 62254-23888, never
    easyprivacy: 26549-27, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-457, never
    IDN-0: 8944-3496, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3663 ms
  maxAssetCacheWait: 42 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 2
    histats.com: 1
```
</details>

**Comment by mapx-** [comment]
- Update all your lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

- Test again
- Provide a screenshot with what ads do you still see

**Comment by ghajini** [comment]
@FayZia you need to subscribe to regional list may be **IDN, MYS: ABPindo**

also popups at `https://databes.driveplayer.net/download/?id=tt5108870` 
`https://193.164.131.42/morbius-2022/play/`

`databes.driveplayer.net##+js(nowoif)`
