### ISSUE TITLE
minecraft.net: breakage

### ISSUE THREAD

**Issue by IPedrax** [uBlockOrigin/uAssets#12511]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.minecraft.net/`

### Category

breakage

### Describe the issue

the page gives a  Access Denied 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 80938
  cosmetic: 42173
  scriptlet: 16491
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65018-51, 3h.22m
    easyprivacy: 26734-121, 3h.21m
    plowe-0: 3707-816, 8d.21h.58m
    ublock-abuse: 72-0, 8d.21h.56m
    ublock-badware: 3984-86, 3h.20m
    ublock-filters: 30486-86, 3h.19m
    ublock-privacy: 201-2, 8d.21h.51m
    ublock-quick-fixes: 135-15, 3h.16m
    ublock-unbreak: 1742-41, 3h.18m
    urlhaus-1: 8896-0, 3h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 437 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Tried some european / us ip, no issues on my end

**Comment by iam-py-test** [comment]
@IPedrax try rebooting your device and internet router to get a new IP; maybe their Anti-DDoS flagged you by accident

**Comment by JobcenterTycoon** [comment]
Works fine for me too
