### ISSUE TITLE
patronlardunyasi.com: ads

### ISSUE THREAD

**Issue by kahveisteyen** [uBlockOrigin/uAssets#12518]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.patronlardunyasi.com/haber/Cumhurbaskani-Erdogan-in-yegeni-hangi-sektore-girdi/261883`

### Category

ads

### Describe the issue

The page has multiple sources of ads on page and ublock only detects one of them. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 82380
  cosmetic: 24005
  scriptlet: 16481
  html: 634
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31148-276, 1d.17h.7m
    ublock-badware: 3993-3, 12h.39m
    ublock-privacy: 210-1, 12h.51m
    ublock-abuse: 72-0, 1d.17h.6m
    ublock-unbreak: 1759-0, 5d.12h.57m
    adguard-mobile: 7431-171, 12h.42m
    easylist: 65046-24416, 12h.40m
    easyprivacy: 26734-585, 12h.45m
    urlhaus-1: 8896-0, 12h.35m
    plowe-0: 3687-2, 5d.12h.59m
    ublock-quick-fixes: 139-4, 12h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5338 ms (selfie)
  maxAssetCacheWait: 1251 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    adform.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Subscribe to `TUR: AdGuard Turkish` list.

**Comment by okiehsch** [comment]
Fixed in the regional list.
