### ISSUE TITLE
amazon.com.au: privacy

### ISSUE THREAD

**Issue by 224942** [uBlockOrigin/uAssets#12514]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com.au/ap/cvf/request?arb=7d3651e0-cdcf-4fd5-ac67-a3cf08093f77`

### Category

privacy

### Describe the issue

Amazon now asks for CVC on purchase rather than rely on their Fraud monitoring process. I believe my internet is limited to a copy of the actual internet (partly)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 98
filterset (summary): 
  network: 80401
  cosmetic: 22399
  scriptlet: 16419
  html: 621
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 30899-265, never
    ublock-badware: 3989-3, never
    ublock-privacy: 202-1, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1733-0, never
    adguard-mobile: 7431-172, 11m
    easylist: 62254-24091, never
    easyprivacy: 26549-490, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-2, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 426 ms
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> Amazon now asks for CVC on purchase rather than rely on their Fraud monitoring process.

if you disable uBO do you get a different behaviour ?
