### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by ahmetur2011** [uBlockOrigin/uAssets#12519]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=DIVtcUQPtg0`

### Category

ads

### Describe the issue

When watch a video, showing ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 82626
  cosmetic: 48924
  scriptlet: 16946
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 9244-144, 3d.19h.42m
    easylist: 64859-68, 3d.19h.42m
    easyprivacy: 26726-126, 3d.19h.42m
    plowe-0: 3687-810, 3d.19h.42m
    ublock-abuse: 72-0, 3d.19h.42m
    ublock-badware: 3952-86, 3d.19h.42m
    ublock-filters: 30520-94, 3d.19h.42m
    ublock-privacy: 203-2, 3d.19h.42m
    ublock-quick-fixes: 139-15, 17h.28m
    ublock-unbreak: 1740-41, 3d.19h.42m
    urlhaus-1: 8896-0, 17h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 674 ms (selfie)
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 221
  blockedDetails: 
    youtube.com: 208
    doubleclick.net: 7
    googleadservices.com: 1
    googlesyndication.com: 3
    googlevideo.com: 2
```
</details>

**Comment by iam-py-test** [comment]
@ahmetur2011 please reset uBo to default settings, disable ALL other extensions, clear your browser cache and cookies, and then retest. Also check your device for malicious software.
If it persists, please report it at the correct issue (https://github.com/uBlockOrigin/uAssets/issues/7636)
