### ISSUE TITLE
stats.statbroadcast.com: breakage

### ISSUE THREAD

**Issue by mx01xz** [uBlockOrigin/uAssets#12525]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stats.statbroadcast.com/broadcast/?id=405575&vislive=tam`

### Category

breakage

### Describe the issue

With uBlock Origin enabled, the stats dashboard does not load and gives error:

> Encountered an error attempting to retrieve the event information from the server.
> `Err Response: {"readyState":0,"status":0,"statusText":"error"}`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1728" alt="Screen Shot 2022-03-31 at 19 24 12" src="https://user-images.githubusercontent.com/93289197/161171222-209401ae-0310-4043-8791-53e1ef0af077.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 100
filterset (summary): 
  network: 79318
  cosmetic: 42132
  scriptlet: 16500
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64898-51, 3d.8h.2m
    easyprivacy: 26727-121, 3d.8h.1m
    plowe-0: 3687-809, 3d.8h
    ublock-abuse: 72-0, 3d.7h.58m
    ublock-badware: 3953-86, 3d.7h.56m
    ublock-filters: 30479-84, 3d.7h.55m
    ublock-privacy: 203-2, 3d.7h.54m
    ublock-quick-fixes: 118-4, 1h.43m
    ublock-unbreak: 1741-41, 3d.6h.40m
    urlhaus-1: 7425-0, 1h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 144 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    statbroadcast.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Do you see everything with this filter?
```
@@||stats.statbroadcast.com/interface/webservice/event/$xhr,1p
```

**Comment by stephenhawk8054** [comment]
It's blocked by `/stats.*/event` in EP.

@ryanbr
