### ISSUE TITLE
wcostream.com: breakage

### ISSUE THREAD

**Issue by newtoq** [uBlockOrigin/uAssets#12524]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wcostream.com/playlist-cat/600705/terra-formars-episode-3-english-dubbed`

### Category

breakage

### Describe the issue

Playlist player not loading. You have to turn off uBlockOrigin to play video. Checked other playlists and they are broken to. It used to work but stopped after filter list update.
With filter turned off . 
ssl.p.jwpcdn.com
jwplayer-dualstack.map.fastly.net
g.jwpsrv.com
The sites above are in green and player appears and funtions properly
I disabled 1 filter list at a time. Untill the offender was found .png provided

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock on](https://user-images.githubusercontent.com/24573245/161155626-55ecf312-e467-4238-82f1-6e3e39e2d725.png)

![ublock off](https://user-images.githubusercontent.com/24573245/161155649-d885c235-bc71-40fa-bc45-e2f85839cc17.png)

![filters disabled to fix problem](https://user-images.githubusercontent.com/24573245/161155664-45546678-983e-4cfa-b775-76dcc2429bc3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 79520
  cosmetic: 42185
  scriptlet: 16437
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31059-29, now
    ublock-badware: 3995-3, 8m
    ublock-privacy: 210-0, 9m
    ublock-abuse: 72-0, 9m
    ublock-unbreak: 1755-0, 9m
    ublock-quick-fixes: 117-4, 9m
    easylist: 65084-589, 10m
    easyprivacy: 26739-577, 9m
    urlhaus-1: 7414-0, 9m
    plowe-0: 3690-2, 9m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4042 ms
  maxAssetCacheWait: 550 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    addthis.com: 1
    bloxplay.com: 1
    cpmstar.com: 3
    google-analytics.com: 1
    gumgum.com: 1
    jwpcdn.com: 4
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
@@||ssl.p.jwpcdn.com/player/v/*/provider.html5.js$script,domain=wcostream.com
@@||ssl.p.jwpcdn.com/player/v/*/jwplayer.controls.js$script,domain=wcostream.com
```
