### ISSUE TITLE
tvanouvelles.ca: detection

### ISSUE THREAD

**Issue by DreadSpecter** [uBlockOrigin/uAssets#12526]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tvanouvelles.ca/2022/03/31/deux-enfants-meurent-apres-avoir-mange-de-la-pizza-surgelee?fbclid=IwAR2iK5IiZmNnRZScL_wymNqMwnrFuwHraL6YSUymgPePhjaUKkJaKQeUKio`

### Category

detection

### Describe the issue

detects ublock and forces user to disable ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock](https://user-images.githubusercontent.com/102774379/161176010-de43bab0-b21f-44d8-b438-286b9370a128.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79500
  cosmetic: 42047
  scriptlet: 16610
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65069-51, 1d.4h.16m
    easyprivacy: 26737-121, 21h.52m
    plowe-0: 3687-809, 5d.9h.28m
    ublock-abuse: 72-0, 2d.4h.57m
    ublock-badware: 3984-88, 1d.4h.17m
    ublock-filters: 30444-84, 3d.12h.30m
    ublock-privacy: 205-2, 8h.27m
    ublock-quick-fixes: 139-15, 23m
    ublock-unbreak: 1741-41, 2d.8h.38m
    urlhaus-1: 7443-0, 22m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 252 ms (selfie)
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    cxense.com: 2
    doubleclick.net: 2
    go-mpulse.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    twitter.com: 5
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?

**Comment by DreadSpecter** [comment]
Done, and working now, thanks a lot!

**Comment by stephenhawk8054** [comment]
Please read carefully the prerequisites that you have ticked on

> - [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
