### ISSUE TITLE
technipages.com: breakage

### ISSUE THREAD

**Issue by timothy-vas** [uBlockOrigin/uAssets#12523]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.technipages.com/review/the-8-best-adblockers-for-chrome`

### Category

breakage

### Describe the issue

The content is hidden by the `entry-content > div` rule. EasyList issue.

The source of the problematic rule
https://github.com/uBlockOrigin/uAssets/issues/9399#issuecomment-855490003

### Screenshot(s)

<details>
<summary>Screenshot(No content)</summary>

![t1](https://user-images.githubusercontent.com/99832738/161146254-9ccd74b9-53b1-42dd-a732-0a46dad4c042.png)

</details>

<details>
<summary>Screenshot(Expected behaviour)</summary>

![t2](https://user-images.githubusercontent.com/99832738/161146310-d4ea818a-de98-4711-a423-0e80c236d168.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 44848
  cosmetic: 45595
  scriptlet: 16437
  html: 631
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  default: 
    ublock-filters: 31059-40, 14m
    ublock-badware: 4022-3, 14m
    ublock-privacy: 210-0, 14m
    ublock-abuse: 72-0, 14m
    ublock-unbreak: 1752-0, 2d.4h.26m
    easylist: 64990-209, 2d.4h.26m
    DEU-0: 5602-1, 4m
    ublock-quick-fixes: 116-4, 15m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  uiAccentCustom0: #8000ff
  uiTheme: dark
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1048 ms (selfie)
  maxAssetCacheWait: 618 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

```
technipages.com#@#.entry-content > div
technipages.com##[style]:has([data-ad-layout])
```

@ryanbr
