### ISSUE TITLE
blog.fastssh.com anti-adblock

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#12527]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.fastssh.com/vpn-protocol/howdy-trojan-vpn/how-to-use-howdy-trojan-vpn-on-windows-64bit-and-32bit/`

### Describe the issue

The website shows an anti-adblock message.

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 99.0.4844.82

### Settings

! 2021-10-21 https://pixlr.com
pixlr.com##[src="/dad/slot/"]
pixlr.com###slot
||iplogger.org^$badfilter
||ipfounder.net^
||whatismyip.li^
||photographyinflux.com^
||tunneled.me^
||freeip.me^

! 2022-04-01 https://blog.fastssh.com
blog.fastssh.com###lrgwkd-blanket > div
blog.fastssh.com###lrgwkd-blanket

### Notes

I added blog.fastssh.com filters, but the page won't scroll.

**Comment by stephenhawk8054** [comment]
I can't reproduce your issue. Can you click on [Report button (the one in the middle)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), click on `Troubleshooting Information` and copy paste your configuration from there?

**Comment by SilkArt** [comment]
Ok, will do.

**Comment by SilkArt** [comment]
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 151411
  cosmetic: 192989
  scriptlet: 34047
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 2d.5h.59m
    adguard-annoyance: 51304-156, 2d.20h.21m
    adguard-generic: 63165-704, 2d.20h.16m
    adguard-mobile: 7423-99, 2d.20h.51m
    adguard-social: 16525-783, 2d.20h.20m
    adguard-spyware: 25922-1034, 2d.20h.49m
    adguard-spyware-url: 537-13, 2d.20h.52m
    block-lan: 43-0, 12d.15m
    curben-phishing: 10571-0, 23h.30m
    curben-pup: 263-0, 23h.32m
    dpollock-0: 10362-1449, 9d.51m
    fanboy-annoyance: 65633-3993, 6d.36m
    fanboy-cookiemonster: 27298-26925, 3d.18h.56m
    fanboy-social: 23249-23246, 2d.20h.17m
    fanboy-thirdparty_social: 68-21, 6d.37m
    ublock-annoyances: 4291-251, 2d.20h.50m
  default: 
    user-filters: 9-0, never
    easylist: 64994-1408, 2d.20h.18m
    easyprivacy: 26733-10643, 3d.3h.29m
    plowe-0: 3690-1486, 9d.16h.56m
    ublock-abuse: 72-0, 6d.21h.21m
    ublock-badware: 3984-261, 2d.20h.54m
    ublock-filters: 30452-3429, 3d.7h.30m
    ublock-privacy: 203-40, 6d.38m
    ublock-unbreak: 1741-105, 2d.20h.55m
    urlhaus-1: 7425-1, 23h.31m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 41 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4534 ms (selfie)
  maxAssetCacheWait: 1973 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    facebook.net: 1
    googlesyndication.com: 4
    onesignal.com: 1
    wp.com: 1

**Comment by SilkArt** [comment]
Hope this helps.

**Comment by stephenhawk8054** [comment]
I still can't reproduce with your configurations. Which browser are you using?

**Comment by mapx-** [comment]
- reset uBO to default settings
- go into dashboard, filter lists tab, click "purge all caches", click "update now"

- disable any other extension in chrome
- test again
