### ISSUE TITLE
bandcamp.com: breakage

### ISSUE THREAD

**Issue by perXautomatik** [uBlockOrigin/uAssets#12537]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://meta4recordings.bandcamp.com/`

### Category

breakage

### Describe the issue

can't play music, maybe you need to be logged in, worked when i blacklisted bandcamp

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 52017
  cosmetic: 104439
  scriptlet: 6272
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    plowe-0: null
    ublock-filters: null
    ublock-quick-fixes: null
  added: 
    adguard-annoyance: 51369-206, 4h.50m
    fanboy-annoyance: 66365-2886, 4h.50m
    fanboy-thirdparty_social: 68-20, 4h.50m
    ublock-annoyances: 4279-211, 4h.50m
  default: 
    user-filters: 1-0, never
    SWE-1: 4050-0, 4h.53m
    easyprivacy: 26743-198, 4h.49m
    ublock-abuse: 72-0, 4h.49m
    ublock-badware: 4001-3, 4h.49m
    ublock-privacy: 205-8, 4h.49m
    ublock-unbreak: 1744-36, 4h.49m
    urlhaus-1: 7425-0, 4h.49m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  collapseBlocked: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4582 ms
  maxAssetCacheWait: 1450 ms
popupPanel: 
  blocked: 7
  no-large-media: true
  blockedDetails: 
    bandcamp.com: 4
    bcbits.com: 2
    facebook.net: 1
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings and then don't touch the lists. You disabled very important lists.
