### ISSUE TITLE
tver.jp: detection

### ISSUE THREAD

**Issue by Audrey4431** [uBlockOrigin/uAssets#12535]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tver.jp/`

### Category

detection

### Describe the issue

I cannot watch videos on TVer when I use uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79501
  cosmetic: 42183
  scriptlet: 16542
  html: 0
listset (total-discarded, last updated): 
  removed: 
    JPN-1: null
  default: 
    user-filters: 15-1, never
    easylist: 65082-51, 18h.22m
    easyprivacy: 26738-121, 18h.21m
    plowe-0: 3690-810, 8d.19h.17m
    ublock-abuse: 72-0, 9d.18h.31m
    ublock-badware: 3989-88, 18h.19m
    ublock-filters: 30503-88, 4d.9h.20m
    ublock-privacy: 202-2, 8d.19h.13m
    ublock-quick-fixes: 141-15, 18h.17m
    ublock-unbreak: 1741-41, 4d.9h.19m
    urlhaus-1: 7425-0, 18h.18m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 25 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3065 ms (selfie)
  maxAssetCacheWait: 636 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    tver.jp: 8
    fout.jp: 1
    googletagmanager.com: 1
    interactive-circle.jp: 1
    newrelic.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable the regional filter list `JPN: AdGuard Japanese`

**Comment by Audrey4431** [comment]
I'm Japanese, so not good at English. Sorry.
Do you mean use AdGuard instead of uBO?

**Comment by mapx-** [comment]
No, just enabled again JPN list in regional lists sectionof uBO.

Now is removed / disabled:
```
removed: 
    JPN-1: null
```

**Comment by Yuki2718** [comment]
@Audrey4431 uBlock Originの設定から「フィルターリスト」>「地域・言語」下にあるAdGuard Japaneseで対応済みです。

**Comment by Audrey4431** [comment]
Thank you.
