### ISSUE TITLE
https://ay.live/ : anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12536]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ay.live/VZqRQ`

### Describe the issue

1. The above URL used to redirect to a link checker for turkdown CBOX.
2. Now it is detecting the UBo and stopping at some `https://bildirim.eu/` site. 
3. It can't redirect further to the final link checker webpage.

### uBlock Origin version

1.41.8

### Browser name and version

Chrome 100

### Settings

All defaults

**Comment by okiehsch** [comment]
Does it work if you add
````
||bildirim.eu^$badfilter
||bildirim.eu^$3p
````
to your filter list?

**Comment by okiehsch** [comment]
@ryanbr
