### ISSUE TITLE
torjackan.info [Anti-Adblock] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1253]
URL(s) where the issue occurs

`https://torjackan.info/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
