### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by TargetLocked** [uBlockOrigin/uAssets#12538]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/video/BV1cD4y1S7Yx`

### Category

breakage

### Describe the issue

The comments ("评论") disappeared.
Disabling EasyPrivacy fixes the problem.
(Not sure where to report problems caused by a certain list...)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
(broken page)

![image](https://user-images.githubusercontent.com/32962687/161265396-86dd25a6-5dd7-48d8-a86b-8c6d6e249235.png)

(EasyPrivacy disabled)

![image](https://user-images.githubusercontent.com/32962687/161265571-f2095d14-8424-42d9-aced-69815e4ecc51.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 97202
  cosmetic: 52259
  scriptlet: 16583
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-0, never
    CHN-0: 27971-86, 7h.53m
    easylist: 65076-56, 22h.9m
    easyprivacy: 26743-147, 1m
    plowe-0: 3709-818, 12d.22h.18m
    ublock-abuse: 72-0, 1m
    ublock-badware: 3989-88, 7h.55m
    ublock-filters: 30482-104, 8m
    ublock-privacy: 205-2, 8m
    ublock-quick-fixes: 119-4, 1h.32m
    ublock-unbreak: 1744-42, 1h.33m
    urlhaus-1: 7425-0, 22h.8m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 562 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    bilibili.com: 46
    hdslb.com: 6
```
</details>

**Comment by JobcenterTycoon** [comment]
@TargetLocked site breakage is always a issue for uAssets, see https://github.com/uBlockOrigin/uAssets/blob/master/README.md

A few times breakage can be fixed without whitelisting because uBO has more ways to fix a issue
