### ISSUE TITLE
brainly.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#12531]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://brainly.com/question/21897377`

### Category

breakage

### Describe the issue

After viewing a few answers, you are presneted with an option to watch a video to view the answer. However, attempting to view the video does not work and you can't view any of the answers. To reproduce, just scroll down and select to view other questions and eventually you will be presented with the paywall or to watch the video causing the problem. 

### Screenshot(s)

<details>

<summary>Screenshot(s)</summary>

![Screen Shot 2022-03-31 at 9 54 03 PM](https://user-images.githubusercontent.com/69532417/161197498-c292bf7a-45cb-405d-8d09-80a25adf0716.png)
![Screen Shot 2022-03-31 at 9 53 42 PM](https://user-images.githubusercontent.com/69532417/161197503-d130dac3-2b79-40f7-97d4-76e6575c3085.png)
![Screen Shot 2022-03-31 at 9 53 35 PM](https://user-images.githubusercontent.com/69532417/161197504-cee1f399-ac43-4521-8c77-bcc6ea339e3e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79657
  cosmetic: 42069
  scriptlet: 16470
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65014-51, 1d.21h.12m
    easyprivacy: 26734-121, 1d.21h.16m
    plowe-0: 3687-809, 5d.21h.43m
    ublock-abuse: 72-0, 5d.21h.42m
    ublock-badware: 3984-86, 1d.21h.15m
    ublock-filters: 30454-86, 1d.21h.14m
    ublock-privacy: 203-2, 5d.21h.41m
    ublock-unbreak: 1741-41, 1d.21h.13m
    urlhaus-1: 7657-0, 1d.21h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5206 ms (selfie)
  maxAssetCacheWait: 2151 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    ad.gt: 1
    amazon-adsystem.com: 1
    branch.io: 1
    datadome.co: 1
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
    pubmatic.com: 1
    sentry-cdn.com: 1
    truex.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe you should have an account ?

**Comment by stephenhawk8054** [comment]
Technically it's a video ad. To allow it, you need to allow other ads and trackers domains, which I don't think we could do it. So it would make more sense that you should

- Turn off ublock when watching video ad, or 
- Create an account, or
- Open in new Incognito session, or
- Adding these by yourselves

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=brainly.com
@@||ads.pubmatic.com/AdServer/js/pwt/$script,domain=brainly.com
@@||js-sec.indexww.com/htv/htv-brainly.min.js$script,domain=brainly.com
brainly.com##+js(aopr, indexapi)
brainly.com##+js(aopr, owpbjs)
brainly.com##+js(set, owpbjsChunk, undefined)
```

**Comment by jimmysofat6864** [comment]
@mapx- @stephenhawk8054 AdGuard doesn't have the same issue with this site and using the Annoyances List with AdGuard seems to fix this. The fix is detailed [here](https://github.com/AdguardTeam/AdguardFilters/commit/0bcf7787d61d17d8cf15c22b28a0812401975436). Would it be possible to add this into uBlock origin?

**Comment by mapx-** [comment]
`uBO` does not support for now these type of filters (`Javascript rules`)
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules-1

**Comment by jimmysofat6864** [comment]
@stephenhawk8054 Is there a solution that bypasses the advertisement?

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Is there a solution that bypasses the advertisement?

If you don't mind breakages, can you check if this one can show the answers?

`brainly.com##+js(set, jsData.hasVideoMeteringUnlogEnabled, undefined)`

**Comment by jimmysofat6864** [comment]
@stephenhawk8054 Yes it appears that works. Would that be added into future adlists as it's a not a script?

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Yes it appears that works. Would that be added into future adlists as it's a not a script?

Yeah, if it works, I can put it into `Annoyances` list
