### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by birdhippi** [uBlockOrigin/uAssets#12532]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rezka.ag/`

### Category

ads

### Describe the issue

The ads keep showing when play the video, also top panel has ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Untitled](https://user-images.githubusercontent.com/100544657/161208025-8a84c64b-6f42-4fc9-9a79-0f614d03dec5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79458
  cosmetic: 42180
  scriptlet: 16479
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65018-51, 1d.15h.18m
    easyprivacy: 26734-121, 1d.15h.17m
    plowe-0: 3687-809, 5d.18h.53m
    ublock-abuse: 72-0, 5d.18h.51m
    ublock-badware: 3984-86, 1d.15h.16m
    ublock-filters: 30478-86, 1d.15h.15m
    ublock-privacy: 203-2, 5d.18h.47m
    ublock-quick-fixes: 140-15, 11h.25m
    ublock-unbreak: 1742-41, 1d.15h.14m
    urlhaus-1: 7425-0, 11h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 913 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    adpod.in: 1
    franecki.net: 5
    franeski.net: 2
    jsdelivr.net: 1
    mail.ru: 1
    reichelcormier.bid: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
russian site, enable `RUS: RU AdList `
