### ISSUE TITLE
www7.bflix.to: popups

### ISSUE THREAD

**Issue by deejyun** [uBlockOrigin/uAssets#12546]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www7.bflix.to/movie/helvetica-yk5v1/1-full`

### Category

popups

### Describe the issue

- even though the popups are blocked by uBO itself, the ads that makes you open these tabs are still there/clicking anywhere on the site makes you open these ads
- if you pause whatever you are watching, an ad pops up and covers the play button/middle of screen
- this site used to work with uBO, but it recently got ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 81561
  cosmetic: 42192
  scriptlet: 16447
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 31067-30, 9h.9m
    ublock-badware: 3993-3, 9h.8m
    ublock-privacy: 210-0, 9h.7m
    ublock-abuse: 72-0, 9h.6m
    ublock-unbreak: 1753-0, 9h.5m
    easylist: 65093-589, 9h.4m
    easyprivacy: 26743-577, 9h.3m
    urlhaus-1: 9450-0, 4h.12m
    plowe-0: 3687-2, 4d.13h.12m
    ublock-quick-fixes: 123-4, 4h.12m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 153 ms (selfie)
  maxAssetCacheWait: 97 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    addthis.com: 1
    amung.us: 1
    bunnycdn.ru: 1
    denetsuk.com: 1
    disqus.com: 1
    jomtingi.net: 4
    rndskittytor.com: 1
    vizcloud.online: 1
    zikroarg.com: 2
```
</details>

**Comment by mapx-** [comment]
if you are talking about the ad appearing when pause the video just update all lists

**Comment by ghajini** [comment]
`bflix.to##+js(acis, Promise, JSON.parse)`
