### ISSUE TITLE
filmeserialegratis.net pop-up

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#12547]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://filmeserialegratis.net/the-bye-bye-man/`

### Describe the issue

When I play the video, pop-up show up on a new window.

### uBlock Origin version

1.42

### Browser name and version

Firefox 98

### Settings

Default settings

**Comment by andreewmat** [comment]
@mapx- the pop-up still appear: `https://filmeserialegratis.net/hide-and-seek/`

**Comment by andreewmat** [comment]
@mapx- also the pop here on "NETU" player: `https://divxfilmeonline.net/x-2022/`

**Comment by sugarfreesweetener** [comment]
Should/could filters be moved to `road-block lite`?

**Comment by mapx-** [comment]
it's ok here, audio is english so it's useful not only for romanians

**Comment by sugarfreesweetener** [comment]
oh, okay, but what about banner advertising

I opened https://github.com/tcptomato/ROad-Block/pull/233 before seeing your comment
