### ISSUE TITLE
homemoviestube.com [Pop-up] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1254]
URL(s) where the issue occurs

`http://www.homemoviestube.com/videos/405180/a-perfect-teen-fuck-toy.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ads
