### ISSUE TITLE
pcbac.com: breakage

### ISSUE THREAD

**Issue by DavidSalomonDev** [uBlockOrigin/uAssets#12545]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pcbac.com/web/login`

### Category

breakage

### Describe the issue

Website doesn't load at all
I disabled uBlock, ant it works again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 81564
  cosmetic: 42203
  scriptlet: 16479
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65102-51, 1h.45m
    easyprivacy: 26743-121, 1h.44m
    plowe-0: 3690-810, 9d.18h.42m
    ublock-abuse: 72-0, 12d.21h.2m
    ublock-badware: 3989-88, 1h.47m
    ublock-filters: 30486-88, 1h.46m
    ublock-privacy: 200-2, 12d.21h.7m
    ublock-quick-fixes: 140-15, 1h.41m
    ublock-unbreak: 1745-41, 1h.43m
    urlhaus-1: 9450-0, 1h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 215 ms (selfie)
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    pcbac.com: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||pcbac.com/web/*/js/analytics.js$script,1p`
