### ISSUE TITLE
foxnews.com: detection

### ISSUE THREAD

**Issue by samboa86** [uBlockOrigin/uAssets#12543]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.foxnews.com/politics/desantis-on-disney-i-dont-support-special-privileges-in-law-because-a-company-is-powerful`

### Category

detection

### Describe the issue

cant scroll

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 79817
  cosmetic: 42118
  scriptlet: 16433
  html: 631
listset (total-discarded, last updated): 
  added: 
    https://abp.perimeterx.com/whitelist.txt: 8-0, 10h.37m
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 266-4, 1d.10h.46m
  default: 
    user-filters: 17-0, never
    ublock-filters: 31062-29, 10h.40m
    ublock-badware: 3993-3, 10h.39m
    ublock-privacy: 208-0, 3d.10h.54m
    ublock-abuse: 72-0, 3d.10h.53m
    ublock-unbreak: 1755-0, 10h.43m
    easylist: 65092-590, 10h.42m
    easyprivacy: 26743-583, 10h.41m
    plowe-0: 3707-2, 10d.23h.57m
    urlhaus-1: 7443-0, 10h.38m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 653 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    foxnews.com: 4
    akamaihd.net: 3
    akamaized.net: 2
    amazon-adsystem.com: 2
    aswpsdkus.com: 1
    beyondwords.io: 1
    chartbeat.com: 1
    clarity.ms: 2
    criteo.net: 1
    datadoghq.com: 1
    edgekey.net: 1
    flipboard.com: 1
    google.com: 2
    googletagmanager.com: 1
    h-cdn.com: 6
    imasdk.googleapis.com: 1
    imrworldwide.com: 2
    lytics.io: 1
    newrelic.com: 2
    opecloud.com: 1
    outbrain.com: 1
    segment.com: 2
    spot.im: 5
    taplytics.com: 1
    watchingthat.net: 1
    yahoo.com: 3
```
</details>

**Comment by mapx-** [comment]
disable those added lists
```
    https://abp.perimeterx.com/whitelist.txt
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt
```

disable other addons in FF, test again
