### ISSUE TITLE
kitv.com: breakage

### ISSUE THREAD

**Issue by wdpk** [uBlockOrigin/uAssets#12556]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kitv.com/news/top-stories/hawaii-considers-4-day-work-weeks-for-state-employees/article_a8055486-b169-11ec-9e3b-df93b63d15a5.html`

### Category

breakage

### Describe the issue

Blocks the site's content. Ads successfully eliminated, but so is the text of the article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 115930
  cosmetic: 79023
  scriptlet: 28607
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 3d.4h.48m
    adguard-generic: 63225-732, 1d.11h.22m
    adguard-mobile: 7436-47, 1d.11h.24m
    adguard-spyware: 25948-697, 1d.11h.23m
  default: 
    user-filters: 49-0, never
    easylist: 65092-1084, 1d.3h.40m
    easyprivacy: 26738-10455, 1d.11h.25m
    plowe-0: 3690-967, 3d.4h.49m
    ublock-abuse: 72-0, 5d.13h.19m
    ublock-badware: 4018-258, 1d.11h.27m
    ublock-filters: 30476-3125, 1d.11h.26m
    ublock-privacy: 203-32, 5d.13h.18m
    ublock-quick-fixes: 125-6, 13h.4m
    ublock-unbreak: 1742-97, 1d.11h.21m
    urlhaus-1: 9450-0, 13h.5m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 119 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 249 ms (selfie)
  maxAssetCacheWait: 176 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    kitv.com: 3
    connatix.com: 2
    crwdcntrl.net: 4
    d3plfjw9uod7ab.cloudfront.net: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    ntv.io: 1
    revcontent.com: 1
    spot.im: 4
    taboola.com: 1
    townnews.com: 1
```
</details>

**Comment by mapx-** [comment]
add
`@@||kitv.com/shared-content/art/tncms/api/access.js$script,1p`

`AdGuard Tracking Protection` issue @Yuki2718

**Comment by wdpk** [comment]
Mahalo!
