### ISSUE TITLE
hamwaves.com: breakage

### ISSUE THREAD

**Issue by stroobandt** [uBlockOrigin/uAssets#12559]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hamwaves.com/qrp/en/index.html`

### Category

breakage

### Describe the issue

Plain vanilla uBlockOrigin blocks XMLHttpRequests to https://freegeoip.app/json/ , which is pretty harmless and only returns JSON with a very rough location guess.

As a result of this, the map at the bottom of the given URL does not show up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 98
filterset (summary): 
  network: 81609
  cosmetic: 42244
  scriptlet: 16449
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 47m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 65165-51, 40m
    easyprivacy: 26744-121, 39m
    plowe-0: 3691-810, 9d.2h.9m
    ublock-abuse: 72-0, 44m
    ublock-badware: 4002-88, 43m
    ublock-filters: 30476-88, 42m
    ublock-privacy: 206-2, 45m
    ublock-quick-fixes: 125-4, 18h.48m
    ublock-unbreak: 1731-41, 41m
    urlhaus-1: 9450-0, 18h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 186 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  blockedDetails: 
    freegeoip.app: 1
    googlesyndication.com: 1
```
</details>

**Comment by okiehsch** [comment]
Is the map with ones geolocation an integral part of the website?
I can fix the breakage without allowing that request but as a result the map thinks your location is ain the middle of the Atlantic Ocean. 😁
The map works fine as you can see if you zoom out.
Add
`||freegeoip.app/json/*$xhr,redirect-rule=nooptext,domain=hamwaves.com`
to your flter list to test.
