### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by Sognetan** [uBlockOrigin/uAssets#12554]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/video/BV1Hg411T7hp/?spm_id_from=333.788.recommend_more_video.-1`

### Category

breakage

### Describe the issue

can not see the comments

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 97323
  cosmetic: 52254
  scriptlet: 16580
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 1d.13h.1m
  default: 
    user-filters: 10-0, never
    CHN-0: 27971-86, 1d.12h.57m
    easylist: 65018-451, 2d.15h.22m
    easyprivacy: 26743-147, 12h.19m
    plowe-0: 3687-811, 7d.8h.38m
    ublock-abuse: 72-0, 1d.2h.5m
    ublock-badware: 3989-86, 1d.12h.56m
    ublock-filters: 30476-102, 1d.12h.58m
    ublock-privacy: 205-2, 1d.2h.6m
    ublock-quick-fixes: 125-4, 4h.18m
    ublock-unbreak: 1744-42, 1d.12h.59m
    urlhaus-1: 7493-0, 4h.17m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 272 ms (selfie)
  maxAssetCacheWait: 96 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    bilibili.com: 23
    hdslb.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists and test again
