### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by RarufuSicat** [uBlockOrigin/uAssets#12553]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=32g1ByDRzO0`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Chromium: 99
filterset (summary): 
  network: 81401
  cosmetic: 42143
  scriptlet: 16489
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64950-51, 3d.22h.11m
    easyprivacy: 26732-121, 3d.22h.10m
    plowe-0: 3687-809, 3d.22h.8m
    ublock-abuse: 72-0, 3d.22h.6m
    ublock-badware: 3958-86, 3d.22h.4m
    ublock-filters: 30471-87, 3d.22h.3m
    ublock-privacy: 203-2, 3d.22h.2m
    ublock-quick-fixes: 125-4, 1h.29m
    ublock-unbreak: 1741-41, 3d.22h.1m
    urlhaus-1: 9450-0, 18h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 411 ms (selfie)
  maxAssetCacheWait: 266 ms
popupPanel: 
  blocked: 690
  blockedDetails: 
    youtube.com: 545
    doubleclick.net: 11
    google.com: 87
    google.com.ph: 1
    googleadservices.com: 4
    googlesyndication.com: 34
    googlevideo.com: 8
```
</details>

**Comment by mapx-** [comment]
duplicate:
https://github.com/uBlockOrigin/uAssets/issues/7636

other indications:
https://github.com/easylist/easylist/wiki/Youtube-Issues

**Comment by iam-py-test** [comment]
@RarufuSicat please reset uBo to default settings, disable ALL other extensions, clear your browser cache and cookies, and then retest. Also check your device for malicious software.
If it persists, please report it at the correct issue (https://github.com/uBlockOrigin/uAssets/issues/7636)
