### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by CutterXYZ** [uBlockOrigin/uAssets#12552]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/`

### Category

ads

### Describe the issue

Ads for games are see in the top-right corner of the page. Sponsored ads keep showing up in the feed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/29694177/161372367-140b4fea-a61b-48c0-ab4c-30f52e9d6ea5.png)
![image](https://user-images.githubusercontent.com/29694177/161372323-8f819231-d51f-4c1b-8a21-be687f261a2f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 99
filterset (summary): 
  network: 138522
  cosmetic: 87961
  scriptlet: 28600
  html: 631
listset (total-discarded, last updated): 
  added: 
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 2d.12h.19m
    https://hosts-file.net/.%5Cad_servers.txt: 0-0, never
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 12m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-10, 2d.12h.20m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-5, 1d.13h.5m
    adguard-generic: 63165-5286, 3d.11h.48m
    adguard-mobile: 7423-193, 3d.11h.47m
    adguard-spyware: 25922-881, 3d.11h.45m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31049-226, 3d.11h.51m
    ublock-badware: 3962-3, 3d.11h.50m
    ublock-privacy: 210-0, 3d.11h.53m
    ublock-abuse: 72-0, 3d.11h.54m
    ublock-unbreak: 1752-1, 3d.11h.49m
    easylist: 64990-942, 3d.11h.46m
    easyprivacy: 26733-10723, 3d.11h.44m
    plowe-0: 3690-1755, 10d.12h.28m
    FRA-0: 26848-379, 3d.11h.43m
    urlhaus-1: 7443-0, 19h.42m
    ublock-quick-fixes: 117-4, 19h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 796 ms (selfie)
  maxAssetCacheWait: 612 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    facebook.com: 3
```
</details>

**Comment by okiehsch** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/3367
