### ISSUE TITLE
igg-games.com: detection

### ISSUE THREAD

**Issue by NoNick96** [uBlockOrigin/uAssets#12551]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://igg-games.com/`

### Category

detection

### Describe the issue

Shows an overlay with "Please support us by disabling Adblock and refresh page, thank you." message. After blocking the overlay it comes back after refreshing the site. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_Pcjr629XVf](https://user-images.githubusercontent.com/16721863/161366132-c8ee4f78-369a-4c33-966a-ae74722aab99.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 100
filterset (summary): 
  network: 80848
  cosmetic: 49521
  scriptlet: 16682
  html: 0
listset (total-discarded, last updated): 
  added: 
    POL-0: 7789-8, 22h.19m
    POL-2: 1273-13, 1d.22h.27m
  default: 
    user-filters: 12-1, never
    easylist: 64990-75, 3d.8h.50m
    easyprivacy: 26737-121, 2d.3h.14m
    plowe-0: 3690-818, 1d.10h.26m
    ublock-abuse: 72-0, 10d.10h.32m
    ublock-badware: 3984-86, 2d.3h.12m
    ublock-filters: 30452-125, 3d.8h.53m
    ublock-privacy: 202-2, 10d.10h.31m
    ublock-quick-fixes: 119-4, 22h.20m
    ublock-unbreak: 1742-42, 2d.3h.13m
    urlhaus-1: 7443-0, 22h.18m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 117 ms (selfie)
  maxAssetCacheWait: 75 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    igg-games.com: 1
    a-ads.com: 1
    bafbb792dc43155824c31350392a3cb3f86299ff650b2524cb9887a39c04.s3.amazonaws.com: 1
    bebi.com: 1
    d301cxwfymy227.cloudfront.net: 2
    googletagmanager.com: 1
    mondaysdoris.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists
