### ISSUE TITLE
scotsman.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1255]
![2018-01-09 19_37_10-the scotsman - scottish news](https://user-images.githubusercontent.com/5884000/34736910-d2ef3dde-f574-11e7-910c-6175f81f038c.png)
`https://www.scotsman.com/`

anti-adblock

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by TheEnhas** [comment]
`scotsman.com##script:inject(abort-on-property-read.js, getUrlParameters)`

**Comment by okiehsch** [comment]
@TheEnhas 
`scotsman.com##script:inject(abort-on-property-read.js, getUrlParameters)`
also works on my end, but `generichide` is the generally preffered fix for the reasoning read,
https://github.com/uBlockOrigin/uAssets/commit/f340633dc681d6e0fb696359e06f5498dd5e0c39#comments

**Comment by TheEnhas** [comment]
Thanks for the explanation, my problem is that I generally don't try generichide anymore to start with because it hardly ever works anymore (it also used to work on City TV but doesn't anymore, and I'm not sure there's an easy fix there).

**Comment by stephenhawk8054** [comment]
Video seems not able to play.

URL: 

`https://www.scotsman.com/news/politics/covid-scotland-demands-to-tackle-booster-chaos-in-race-to-beat-omicron-3492002`

<details><summary>Expect:</summary>

![image](https://user-images.githubusercontent.com/66517106/145748760-7bcf4a90-1176-4dc8-ae7d-f3a5d4c9993a.png)

</details>

<details><summary>Issue:</summary>

![image](https://user-images.githubusercontent.com/66517106/145748782-f7225158-ebaf-4b8e-9c32-789300e59ad5.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77976
  cosmetic: 39683
  scriptlet: 16301
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30508-31, 1h.20m
    ublock-badware: 3574-1, 1h.20m
    ublock-privacy: 185-0, 1h.20m
    ublock-abuse: 81-0, 1h.20m
    ublock-unbreak: 1723-0, 1h.20m
    easylist: 61707-556, 2h.30m
    easyprivacy: 26486-475, 1h.20m
    urlhaus-1: 7817-0, 1h.20m
    plowe-0: 3687-3, 1h.20m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 670
  launchFromSelfie: false
popupPanel: 
  blocked: 40
```
</details>

Proposed filter:

`@@||googletagservices.com/tag/js/gpt.js$script,domain=scotsman.com`

**Comment by mapx-** [comment]
@ryanbr
