### ISSUE TITLE
bilibili.com: nuisance

### ISSUE THREAD

**Issue by ShadowPikaqiu** [uBlockOrigin/uAssets#12557]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

nuisance

### Describe the issue

视频下发的评论看不见了

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 95
filterset (summary): 
  network: 97269
  cosmetic: 52253
  scriptlet: 16579
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-1, never
    CHN-0: 27972-86, 1d.5h.18m
    easylist: 65092-56, 1d.5h.17m
    easyprivacy: 26743-147, 1d.5h.16m
    plowe-0: 3691-812, 8d.23h.15m
    ublock-abuse: 72-0, 4d.11h.26m
    ublock-badware: 3989-88, 1d.5h.15m
    ublock-filters: 30476-104, 1d.5h.14m
    ublock-privacy: 203-2, 4d.11h.25m
    ublock-quick-fixes: 119-4, 9h.8m
    ublock-unbreak: 1744-42, 1d.5h.13m
    urlhaus-1: 7493-0, 9h.9m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 337 ms (selfie)
  maxAssetCacheWait: 230 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update filter lists it got fixed a day ago https://github.com/uBlockOrigin/uAssets/issues/12538
