### ISSUE TITLE
gamepro.de: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#12562]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gamepro.de/spiele/splatoon-3,14817.html`

### Category

ads

### Describe the issue

ad.... look at screenshot 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-02 170821](https://user-images.githubusercontent.com/100969549/161389471-caf13673-4c5f-4c1c-ac21-f3fc91bc5e9b.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 239831
  cosmetic: 297288
  scriptlet: 37397
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6030-7, 1d.20h.59m
    https://winhelp2002.mvps.org/hosts.txt: 8730-67, 3d.20h.2m
    ALB-0: 265-0, 21h.36m
    BGR-0: 1116-13, 3d.20h.4m
    CHN-0: 27976-86, 19h.31m
    CZE-0: 832-0, 21h.35m
    EST-0: 450-2, 21h.33m
    FIN-0: 1580-1, 19h.30m
    FRA-0: 26868-77, 19h.29m
    GRC-0: 1002-3, 1d.22h.8m
    HUN-0: 2158-14, 21h.32m
    IDN-0: 8947-28, 19h.28m
    IRN-0: 1340-7, 19h.27m
    ISL-0: 193-1, 3d.20h.3m
    ISR-0: 1617-2, 21h.11m
    ITA-0: 12881-99, 20h.53m
    JPN-1: 6323-16, 19h.26m
    KOR-1: 8156-15, 19h.25m
    LTU-0: 1186-7, 1d.21h
    LVA-0: 393-2, 19h.24m
    [30 lists not shown]: [too many]
  default: 
    user-filters: 44-4, never
    DEU-0: 5602-2, 21h.34m
    easylist: 65125-1842, 19h.15m
    easyprivacy: 26743-11020, 19h.14m
    plowe-0: 3691-1529, 8d.21h.2m
    ublock-abuse: 72-58, 19h.11m
    ublock-badware: 4002-273, 19h.6m
    ublock-filters: 30479-3767, 19h.9m
    ublock-privacy: 205-75, 19h.8m
    ublock-unbreak: 1745-141, 19h.7m
    urlhaus-1: 9450-1, 20h.55m
filterset (user): [array of 44 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 15 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  uiAccentCustom: true
  uiAccentCustom0: #009600
  uiTheme: dark
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 820 ms (selfie)
  maxAssetCacheWait: 626 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    gamepro.de: 1
    getjad.io: 1
    onesignal.com: 1
    privacy-center.org: 2
    promio-connect.com: 1
    relevant-digital.com: 1
    webcontentassessor.com: 1
```
</details>

**Comment by mapx-** [comment]
Only xbox seems to be an ad, above there are article links on the same `gamepro`

`gamepro.de##.health-banner`

**Comment by okiehsch** [comment]
`gamepro.de##.js-ga > .responsive.health-banner`
is better your filter would block some of the self advertisement too.
@khrin for `EasyList Germany`.
