### ISSUE TITLE
[nsfw] dropgalaxy.com: detection

### ISSUE THREAD

**Issue by AbhiDGamer** [uBlockOrigin/uAssets#12563]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropgalaxy.com/fwkl4k6l9xkz`

### Category

detection

### Describe the issue

It has antiadblock detection enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox Mobile: 100
filterset (summary): 
  network: 92281
  cosmetic: 92966
  scriptlet: 22052
  html: 641
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 51392-3583, 13h.45m
    fanboy-annoyance: 65941-32326, 4d.16h.32m
    ublock-annoyances: 4294-7, 1d.17h.10m
  default: 
    user-filters: 21-2, never
    ublock-filters: 31146-267, 3d.12h.29m
    ublock-badware: 3995-3, 19h.28m
    ublock-privacy: 210-1, 1d.4h.25m
    ublock-abuse: 72-0, 3d.20h.26m
    ublock-unbreak: 1763-0, 13h.46m
    adguard-mobile: 7449-171, 4h.43m
    easylist: 65165-24444, 4h.42m
    easyprivacy: 26738-585, 1d.17h.11m
    urlhaus-1: 7493-0, 3h.47m
    plowe-0: 3690-2, 3d.20h.25m
    ublock-quick-fixes: 124-4, 3h.48m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    moz-extension-scheme
hostRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 585 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    360yield.com: 5
    4dex.io: 2
    a2zapk.com: 1
    adform.net: 1
    amazon-adsystem.com: 1
    cagothie.net: 1
    cloudflareinsights.com: 1
    criteo.com: 3
    criteo.net: 1
    dw55pg05c2rl5.cloudfront.net: 1
    e-planning.net: 1
    googletagservices.com: 1
    onetag-sys.com: 1
    protagcdn.com: 1
    yahoo.com: 5
```
</details>

**Comment by JobcenterTycoon** [comment]
@AbhiDGamer i get only a error but does `@@||protagcdn.com/s/dropgalaxy.com/site.js$script,domain=dropgalaxy.com` works?

**Comment by AbhiDGamer** [comment]
It shows temporarily blocked

**Comment by AbhiDGamer** [comment]
![Screenshot_2022-04-02-23-11-41-751_org mozilla fenix](https://user-images.githubusercontent.com/7191374/161409649-30425326-d712-4346-bb05-029effe480aa.jpg)
I have added your comment as a filter in my filter. It still shows me an error.

**Comment by AbhiDGamer** [comment]
Try this link
https://dropgalaxy.com/k3c2mpn0qylv

**Comment by stephenhawk8054** [comment]
Direct link from `dropgalaxy.com` won't work any more. You should replace `dropgalaxy.com` by `dgdrive.xyz` and it will automatically redirect to `dropgalaxy.com` site. For example:
`https://dgdrive.xyz/k3c2mpn0qylv`

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054 thanks.

@AbhiDGamer i added a fix now. To get the fix force update the filter lists but i don’t know how long the filter will work because they change their anti adblock script often

**Comment by AbhiDGamer** [comment]
It stopped working again
https://dgdrive.xyz/s5m1oh51jves

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by stephenhawk8054** [comment]
> It stopped working again https://dgdrive.xyz/s5m1oh51jves

Which region are you? Sometimes it can be geo-related.

**Comment by dgowner** [comment]
> Works fine for me

yes works for me too thanks :-)

**Comment by AbhiDGamer** [comment]
I am in Guyana. Could you guys tell me what filters you guys have enabled.

**Comment by stephenhawk8054** [comment]
> I am in Guyana. Could you guys tell me what filters you guys have enabled.

Can you test with just default settings and force update the filter lists?
