### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#12565]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=vDAlgtqHptM&list=PLW5nq_LcyKoz2-WLslWfeKAgcQmxyD3ZW&index=7`

### Category

ads

### Describe the issue

An ad can be seen in the upper right corner of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![88ad601c-6a0f-4539-b470-c99b11653c3a](https://user-images.githubusercontent.com/43375046/161393363-d9585809-210e-493c-b9a9-de46efeb0da5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 100
filterset (summary): 
  network: 84634
  cosmetic: 46801
  scriptlet: 16696
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65092-51, 1d.6h.45m
    easyprivacy: 26743-121, 1d.6h.49m
    plowe-0: 3690-810, 10d.13h.26m
    spa-0: 3854-33, 22h.38m
    spa-1: 4288-166, 1d.6h.43m
    ublock-abuse: 72-0, 22h.40m
    ublock-badware: 4001-88, 1d.6h.44m
    ublock-filters: 30503-144, 1d.6h.42m
    ublock-privacy: 205-2, 22h.41m
    ublock-quick-fixes: 125-4, 22h.39m
    ublock-unbreak: 1730-42, 1h.39m
    urlhaus-1: 9450-0, 22h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 378 ms
popupPanel: 
  blocked: 157
  blockedDetails: 
    youtube.com: 127
    doubleclick.net: 4
    google.com: 15
    google.es: 1
    googlevideo.com: 9
    ytimg.com: 1
```
</details>

**Comment by rodrigosambadesaa** [comment]
Wrong screenshot. This is the correct one.
![Captura de pantalla 2022-04-02 190447](https://user-images.githubusercontent.com/43375046/161393550-bb3417bc-431f-474c-9d35-cd2c78ca3a1e.png)

**Comment by okiehsch** [comment]
You checked the box that says
"I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)"
which is obviously a wrong statement. 

You were nice enough to also check the box that says
"I did not answer truthfully to all the above checkpoints"
so kudos.

**Comment by iam-py-test** [comment]
@rodrigosambadesaa please reset uBo to default settings, disable ALL other extensions ,clear your browser cache and cookies, and then retest. If it persists, please report it at the correct issue (https://github.com/uBlockOrigin/uAssets/issues/7636)

**Comment by rodrigosambadesaa** [comment]
Too much sites to relogin-in to, will test it on a new Chrome Profile.
*Rodrigo Sambade Saá*
***@***.***
+34 608 030 077
Cuidemos el medio ambiente. Antes de imprimir este correo, pregúntese si
realmente es necesario: El medio ambiente es responsabilidad de todos.

**Comment by rodrigosambadesaa** [comment]
> @rodrigosambadesaa please reset uBo to default settings, disable ALL other extensions, clear your browser cache and cookies, and then retest. If it persists, please report it at the correct issue (#7636)

Too much sites to relogin-in to, I dont't want to lose time logging back into my accounts, redownloading my cached data etc. Will test it on a new Chrome Profile and post the bug there if it still appears.

**Comment by rodrigosambadesaa** [comment]
I can confirm the ad doesn't show up in a new profile performing the required steps.

**Comment by iam-py-test** [comment]
> I can confirm the ad doesn't show up in a new profile performing the required steps.

You have a lot of extensions installed. Try adding them one-by-one to the new profile & retesting.

**Comment by rodrigosambadesaa** [comment]
I don't have the time. Hope you do. Here are the names and links of all my extensions
[extensions.zip](https://github.com/uBlockOrigin/uAssets/files/8405495/extensions.zip)
.

**Comment by iam-py-test** [comment]
> I don't have the time. Hope you do. Here are the names and links of all my extensions. [extensions.zip](https://github.com/uBlockOrigin/uAssets/files/8405495/extensions.zip)

Thank you.
Please try disabling _[uBlock Origin Extra](https://chrome.google.com/webstore/detail/phmdbnodmecpjjjgaakdccegnchipjpo)_ and seeing if that fixes the issue. Thanks

**Comment by rodrigosambadesaa** [comment]
The ad appeared because of [this extension](https://chrome.google.com/webstore/detail/instant-gaming/lbnoedlobifdhbpjkcfhcbdcjhampmne).

**Comment by rodrigosambadesaa** [comment]
I think that the [Instant Gaming extension](https://chrome.google.com/webstore/detail/instant-gaming/lbnoedlobifdhbpjkcfhcbdcjhampmne) was causing the ad to appear, because I remember visiting the site to look up the prices of some products.
