### ISSUE TITLE
[nsfw] post.nites-tv.xyz: detection

### ISSUE THREAD

**Issue by duc196** [uBlockOrigin/uAssets#12567]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://post.nites-tv.xyz/JibxBQM`

### Category

detection

### Describe the issue

Can't tick on capcha

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b2
Chromium: 97
filterset (summary): 
  network: 80690
  cosmetic: 44581
  scriptlet: 19274
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    VIE-1: 1958-0, 7h.29m
    easylist: 65165-57, 8h.46m
    easyprivacy: 26745-126, 8h.49m
    plowe-0: 3687-809, 4d.21h.31m
    ublock-abuse: 72-0, 8h.50m
    ublock-annoyances: 4235-7, 8h.16m
    ublock-badware: 4002-88, 8h.47m
    ublock-filters: 30490-97, 8h.48m
    ublock-privacy: 206-2, 8h.51m
    ublock-unbreak: 1746-41, 7h.59m
    urlhaus-1: 7493-0, 7h.30m
    ublock-quick-fixes: 125-4, 7h.28m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 32 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 392 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    akamaihd.net: 2
    doubleclick.net: 1
    google.com: 1
    googlesyndication.com: 9
    media.net: 7
```
</details>

**Comment by JobcenterTycoon** [comment]
`nites-tv.xyz##+js(set, blurred, false)` for the focus detection but the captcha works fine for me
