### ISSUE TITLE
d3ward.github.io: detection

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#12564]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://d3ward.github.io/toolz/adblock.html`

### Category

detection

### Describe the issue

This site is a tester for adblockers. Ublock origin should improve its default settings so that all elements on the page are blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 100
filterset (summary): 
  network: 84634
  cosmetic: 46801
  scriptlet: 16696
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65092-51, 1d.6h.27m
    easyprivacy: 26743-121, 1d.6h.32m
    plowe-0: 3690-810, 10d.13h.8m
    spa-0: 3854-33, 22h.20m
    spa-1: 4288-166, 1d.6h.25m
    ublock-abuse: 72-0, 22h.22m
    ublock-badware: 4001-88, 1d.6h.26m
    ublock-filters: 30503-144, 1d.6h.24m
    ublock-privacy: 205-2, 22h.23m
    ublock-quick-fixes: 125-4, 22h.21m
    ublock-unbreak: 1730-42, 1h.21m
    urlhaus-1: 9450-0, 22h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 378 ms
popupPanel: 
  blocked: 116
  blockedDetails: 
    2o7.net: 1
    ads-twitter.com: 2
    adtago.s3.amazonaws.com: 1
    advice-ads.s3.amazonaws.com: 1
    apple.com: 3
    assoc-amazon.com: 1
    bugsnag.com: 4
    cleverads.vn: 1
    doubleclick.net: 5
    facebook.com: 3
    fastclick.com: 1
    fastclick.net: 3
    freshmarketer.com: 1
    getsentry.com: 1
    google-analytics.com: 2
    google.com: 2
    googleadservices.com: 2
    googlesyndication.com: 1
    hicloud.com: 10
    hotjar.com: 2
    icloud.com: 1
    linkedin.com: 2
    luckyorange.com: 3
    luckyorange.net: 3
    media.net: 3
    miui.com: 6
    mouseflow.com: 2
    mzstatic.com: 1
    oneplus.cn: 2
    oneplus.com: 1
    oneplus.net: 1
    pinterest.com: 5
    reddit.com: 1
    redditmedia.com: 1
    rereddit.com: 1
    samsung.com: 2
    samsungadhub.com: 2
    samsungads.com: 2
    samsunghealthcn.com: 1
    samsungknox.com: 1
    samsungusa.com: 1
    sentry-cdn.com: 1
    tiktok.com: 4
    twitter.com: 1
    wp.com: 1
    xiaomi.com: 9
    xiaomi.net: 1
    yahoo.com: 4
    yandex.com: 1
    yandex.net: 2
    yandex.ru: 1
    yandexadexchange.net: 1
    youtube.com: 1
```
</details>

**Comment by okiehsch** [comment]
We don't fix test cases.
