### ISSUE TITLE
bs.to: popups

### ISSUE THREAD

**Issue by RandyJackson59** [uBlockOrigin/uAssets#12561]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bs.to/`

### Category

popups

### Describe the issue

The site has set timer, for when it opens a popup or redirects you to another website with ads. It does not happen instantly, so it could be hard to reproduce. 
It mostly happens after you are on the website for some time, and click on anything

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 89215
  cosmetic: 105360
  scriptlet: 19770
  html: 639
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 66451-263, 6h.39m
    ublock-annoyances: 4243-4, 6h.39m
  default: 
    user-filters: 22-0, never
    ublock-filters: 31081-41, 6h.39m
    ublock-badware: 4006-3, 6h.39m
    ublock-privacy: 211-0, 6h.39m
    ublock-abuse: 72-0, 6h.39m
    ublock-unbreak: 1741-0, 6h.39m
    easylist: 65165-596, 6h.39m
    easyprivacy: 26745-588, 6h.39m
    urlhaus-1: 7493-0, 6h.39m
    plowe-0: 3687-2, 6h.39m
    DEU-0: 5605-2, 6h.39m
    ublock-quick-fixes: 123-4, 6h.39m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 41 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 299 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cloudflare.com: 1
    facebook.com: 1
    prunesbin.com: 2
    yandex.ru: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Can’t reproduce too
