### ISSUE TITLE
doomovie-hd.com: ads

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#12568]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.doomovie-hd.com/`

### Category

ads

### Describe the issue

When i clicked play button. 
I forced to watch ads and click button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ภาพ](https://user-images.githubusercontent.com/43577606/161397991-17734e1b-d6bb-4e3b-8932-7e5ac0a83f21.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 81702
  cosmetic: 44238
  scriptlet: 16716
  html: 631
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 7h.22m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 7h.23m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 32m
    https://pastebin.com/raw/T8RM7JtM: 10-0, 1d.5h.5m
    https://pastebin.com/raw/wTfVaMjf: 41-13, 1d.5h.4m
  default: 
    user-filters: 474-50, never
    ublock-filters: 31065-110, 1d.5h
    ublock-badware: 4005-3, 1d.4h.59m
    ublock-privacy: 210-0, 1d.9h.12m
    ublock-abuse: 72-0, 1d.9h.11m
    ublock-unbreak: 1753-3, 1d.5h.2m
    easylist: 65102-604, 1d.5h.1m
    easyprivacy: 26743-581, 1d.5h.3m
    plowe-0: 3687-3, 7h.25m
    THA-0: 999-2, 1h.21m
    urlhaus-1: 7493-0, 7h.21m
    ublock-quick-fixes: 123-4, 7h.20m
filterset (user): [array of 440 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 694 ms (selfie)
  maxAssetCacheWait: 762 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
@easylist-thailand Can you take a look at this site?
