### ISSUE TITLE
9anime.id: ads

### ISSUE THREAD

**Issue by fruhstuckf** [uBlockOrigin/uAssets#12560]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

9anime 

### Category

ads

### Describe the issue

ads problem

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Chromium: 99
filterset (summary): 
  network: 81332
  cosmetic: 48874
  scriptlet: 16869
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 9254-144, 3d.16h.3m
    easylist: 64990-68, 3d.16h.2m
    easyprivacy: 26733-126, 3d.16h.1m
    plowe-0: 3690-810, 1d.17h.7m
    ublock-abuse: 72-0, 7d.4h.2m
    ublock-badware: 3958-86, 3d.16h
    ublock-filters: 30467-97, 3d.15h.59m
    ublock-privacy: 205-2, 2d.20h.32m
    ublock-unbreak: 1741-41, 3d.15h.58m
    urlhaus-1: 7493-0, 4h
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 14787 ms (selfie)
  maxAssetCacheWait: 1128 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    9anime.id: 2
    addthis.com: 1
    amung.us: 1
    bidgear.com: 4
    disqus.com: 2
    narrative.io: 1
    pippio.com: 1
    rezync.com: 1
    viglink.com: 2
    vizcloud.xyz: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any ads. Can you describe in more details? Have you tried force update the filter lists?

**Comment by Procyon-b** [comment]
You have not updated the list. Open ublock's dashboard, go to the "_Filter lists_" tab, click "_Purge all caches_" and then "_Update now_". Try to use the website to see if it works.
