### ISSUE TITLE
forsal.pl: detection

### ISSUE THREAD

**Issue by genuinejanbar** [uBlockOrigin/uAssets#12569]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forsal.pl/swiat/bezpieczenstwo/artykuly/8390066,dlaczego-ukraina-pokonuje-rosje-powody-przewagi-ukrainy-w-wojnie-z-rosja.html`

### Category

detection

### Describe the issue

Just uBlock is detected and the site is blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 80971
  cosmetic: 49563
  scriptlet: 16645
  html: 642
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31066-29, 2d.9h.54m
    ublock-badware: 3993-3, 2d.9h.53m
    ublock-privacy: 207-0, 10d.21h.57m
    ublock-abuse: 72-0, 10d.21h.57m
    ublock-unbreak: 1753-0, 2d.9h.52m
    easylist: 65076-207, 2d.9h.51m
    easyprivacy: 26738-150, 2d.9h.50m
    urlhaus-1: 7493-0, 12h.6m
    plowe-0: 3690-812, 10d.21h.57m
    POL-0: 7794-47, 12h.7m
    POL-2: 1276-46, 3h.46m
    ublock-quick-fixes: 122-4, 12h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12666 ms (selfie)
  maxAssetCacheWait: 2941 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    2mdn.net: 1
    adocean.pl: 2
    d24rtvkqjwgutp.cloudfront.net: 1
    doubleclick.net: 3
    dqst.pl: 2
    gemius.pl: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    ocdn.eu: 3
    plista.com: 1
    videotarget.pl: 1
    yieldbird.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
forsal.pl##+js(no-xhr-if, dqst)
```

**Comment by genuinejanbar** [comment]
It's works only for first 2, 3 undersites. For next one it doesn't. Temat: Re: [uBlockOrigin/uAssets] forsal.pl: detection (Issue #12569)Data: 2022-04-03 5:57Nadawca: "Marc Boucher" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Try this filter:
forsal.pl##+js(no-xhr-if, dqst)
