### ISSUE TITLE
pinsystem.co.uk: detection

### ISSUE THREAD

**Issue by pisaman2** [uBlockOrigin/uAssets#12576]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pinsystem.co.uk/`

### Category

detection

### Describe the issue

The site detects that I'm using an adblocker, displays a red (and blurred) overlay and the site is unusable.

I am half way there with the following two filters. These allow the page to be interacted with, but the pages are still blurred making it unreadable.

pinsystem.co.uk##div[class$="blackout active"] 
pinsystem.co.uk##div[class$="wrapper"]

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 79640
  cosmetic: 42156
  scriptlet: 16398
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 31049-88, 16h.42m
    ublock-badware: 4011-3, 16h.44m
    ublock-privacy: 208-0, 7d.19h.15m
    ublock-unbreak: 1742-0, 16h.47m
    easylist: 65165-518, 16h.46m
    easyprivacy: 26744-590, 16h.45m
    plowe-0: 3690-2, 4d.13h.17m
    ublock-abuse: 72-0, 7d.13h.45m
    urlhaus-1: 7493-0, 22h.36m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 124 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    pinsystem.co.uk: 2
    googlesyndication.com: 10
    googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
Try this,
`pinsystem.co.uk##+js(acis, eval, replace)`
