### ISSUE TITLE
animeblix.org

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#12571]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.animeblix.org/sono-bisque-doll-wa-koi-wo-suru-12`

### Describe the issue

**Popups** when play & **Anti F12** in video

Direct URL for embed video: `https://viewsb.com/e/zdaohxichp6p.html`

### uBlock Origin version

1.41.8

### Browser name and version

Chrome - 99.0

### Settings

Default + ESP/POR + Annoyances

**Comment by Procyon-b** [comment]
Try this filter:
```
animeblix.org##+js(nowoif)
```
