### ISSUE TITLE
united.no: breakage

### ISSUE THREAD

**Issue by Pangaea666** [uBlockOrigin/uAssets#12573]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.united.no/`

### Category

breakage

### Describe the issue

The header and footer of the site shows up, but not the actual content, which is articles in this case. I've tried to fiddle around with settings, updated filters and all that stuff, but the only way I can get the site to function properly again (it worked normally a few days ago, not sure what has changed) was to disable uBlock. When I go to the site, the articles part of the site "flash" briefly, as if they try to be loaded, and then get blocked out. 

I am not using other extensions with similar function to uBlock (I don't think?), but am using NoScript, PrivacyBadger, ClearURLs and DecentralEyes. If any of these are included in the list of extensions I shouldn't use, then I am sorry for not knowing so. Please advice in that case.

Have tried to turn off NoScript for this domain, with uBlock still active, and the site still doesn't function. Have also allowed the non-spamming/tracking domain in NoScript, but to no avail. From what I could tell, the only way to get the site to load properly again was by disabling uBlock for that domain. 

Couldn't get a screenshot of domain settings in the extensions because they disappear when hitting PrintScreen. Don't have any custom settings in uBlock. 4 of 11 domains are connected when checking the uBlock context menu from the Firefox "front". In NoScript, these are the settings (others are at default):

Trusted
united.no

Untrusted
adnuntius.com
google-analytics.com
googletagmanager.com
hotjar.com
scorecardresearch.com

As mentioned, the domain worked normally on my computer (which is run on Linux Mint 20.3, if that matters) a few days ago. Don't know if the site itself has done anything lately to alter behaviour, or if something has changed in uBlock. But currently the site is not functioning properly while uBlock is enabled. Hopefully this report can be useful.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![United no blocked content](https://user-images.githubusercontent.com/2002335/161416179-d0ff588c-0cb0-4d62-9e0e-ea02cb6233c7.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 79574
  cosmetic: 42213
  scriptlet: 16406
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 79-1, never
    ublock-filters: 31061-29, 8h.12m
    ublock-badware: 4011-3, 8h.11m
    ublock-privacy: 210-0, 2d.23h.40m
    ublock-abuse: 72-0, 2d.23h.39m
    ublock-unbreak: 1741-0, 8h.10m
    easylist: 65165-591, 8h.9m
    easyprivacy: 26744-583, 8h.8m
    plowe-0: 3707-2, 12d.17h.52m
    urlhaus-1: 7399-0, 12h.13m
filterset (user): [array of 79 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1100 ms (selfie)
  maxAssetCacheWait: 800 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    adnuntius.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    k5a.io: 1
    lp4.io: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr @DandelionSprout

**Comment by DandelionSprout** [comment]
It doesn't seem to be caused by Dandelion Sprout's Nordic Filters, at least; especially since OP's configuration doesn't even seem to be using that list.

**Comment by Pangaea666** [comment]
Turn out this was an issue on the domain itself. I don't know what exactly, but I was in direct contact with them, and their technical people changed something again, and now it works normally again for me, also with uBlock active. Articles now show up again.
