### ISSUE TITLE
tver.jp: detection

### ISSUE THREAD

**Issue by JoshuaRamey** [uBlockOrigin/uAssets#12578]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tver.jp/`

### Category

detection

### Describe the issue

The website recently had a renewal and now it detects uBlock Origin when trying to play a video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![7BeSZuNFsK](https://user-images.githubusercontent.com/46817406/161426407-31a8794f-f7f0-4714-ad99-9f08c4d8d1f2.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80981
  cosmetic: 42186
  scriptlet: 16481
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65076-51, 2d.23h.24m
    easyprivacy: 26738-121, 2d.23h.23m
    plowe-0: 3687-809, 6d.23h.32m
    ublock-abuse: 72-0, 11d.6h.26m
    ublock-badware: 3989-88, 2d.23h.22m
    ublock-filters: 30481-88, 2d.23h.21m
    ublock-privacy: 202-2, 11d.6h.23m
    ublock-quick-fixes: 135-15, 3d.22h.31m
    ublock-unbreak: 1742-41, 2d.23h.19m
    urlhaus-1: 8896-0, 3d.22h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 392 ms (selfie)
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    tver.jp: 5
    fout.jp: 1
    googletagmanager.com: 1
    interactive-circle.jp: 1
    newrelic.com: 1
    spotxchange.com: 1
    treasuredata.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/12535

Enable the regional filter list `JPN: AdGuard Japanese` in the regional filter list section of uBO
