### ISSUE TITLE
vtm.be: detection - doesn't load videos anymore

### ISSUE THREAD

**Issue by ronnycoolen** [uBlockOrigin/uAssets#12572]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vtm.be/vtmgo/afspelen/eedc6e169-db11-407f-bc4b-f7b5b198f0b4`

### Category

detection

### Describe the issue

The sites recognises the ad blocker, and refuses to load the video file until I disable uBlockOrigin.

There is a message (in Dutch): De video kan niet afspelen als een adblocker actief is.
translation: The video cannot be played when an ad blocker is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80251
  cosmetic: 43671
  scriptlet: 16461
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2158-13, now
    easylist: 65169-52, now
    easyprivacy: 26746-121, now
    plowe-0: 3687-807, now
    ublock-abuse: 72-0, now
    ublock-badware: 4007-89, now
    ublock-filters: 30491-132, now
    ublock-privacy: 206-2, now
    ublock-unbreak: 1730-55, now
    urlhaus-1: 7422-0, now
    ublock-quick-fixes: 125-4, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 823 ms
  maxAssetCacheWait: 191 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    vtm.be: 1
    fwmrm.net: 1
    gemius.pl: 1
    imasdk.googleapis.com: 1
    litix.io: 2
    pushengage.com: 1
    spott.ai: 1
```
</details>

**Comment by Procyon-b** [comment]
I've tested with 2 versions of chrome (100 and an older one) and I've can't reproduce your problem. I've created a new account and I'm using the same lists as you. I can play the video.
Maybe geolocation is part of the problem (wallonia here).

Try with a brand new profile with only ublock installed and all lists updated, than log into vtm and try to view the video. This will eliminate the root of the problem being a modified chrome setting, or interference from another extension. Also, don't use a vpn or a dns server other than the one from the isp.

**Comment by ronnycoolen** [comment]
OK. I tried everything you did. Nothing worked, until I created a new account on vtm.be (dpg media). With the new account, everything works as expected...

Any ideas how to debug this? I would like to use my original account if at all possible.

**Comment by Procyon-b** [comment]
Open your normal account in your default profile, and the new account in the other profile. Then compare to see if there is a difference in the settings. Nothing seems obvious to me, but I don't use their website (as you could have guessed).

**Comment by ronnycoolen** [comment]
I couldn't find any relevant account settings, but I did find a difference.
There is a javascript to open the player. In the old account (which doesn't work) there is this code:
`window.playerConfig = {
...
    playerV3: true
}
`

In the new account, it says `playerV3: false`.

I haven't been able to hack the javascript to change the value, but maybe that could be the issue.

**Comment by stephenhawk8054** [comment]
> I couldn't find any relevant account settings, but I did find a difference. There is a javascript to open the player. In the old account (which doesn't work) there is this code:
> 
> ```
> window.playerConfig = {
>     ...
>     playerV3: true
> }
> ```
> 
> In the new account, it says `playerV3: false`.
> 
> I haven't been able to hack the javascript to change the value, but maybe that could be the issue.

Can you send the URL where you see that javascript code?

**Comment by ronnycoolen** [comment]
It's on every URL with a video on it. For example: https://vtm.be/vtmgo/afspelen/eedc6e169-db11-407f-bc4b-f7b5b198f0b4
I put the html code on pastebin: https://pastebin.com/3xu46urq

**Comment by stephenhawk8054** [comment]
Can you add this to [My filters pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) to test if it works for your old account?

`vtm.be##+js(set, playerConfig.playerV3, false)`

**Comment by ronnycoolen** [comment]
I tried that, but now I get a javascript error:

```
main.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'NONE')
    at main.js:2:186833
    at Wi (main.js:2:188893)
    at Xi (main.js:2:188989)
    at HTMLDocument.<anonymous> (main.js:2:221665)
```

In `main.js` on position 186833, there is this piece of code that triggers the error: `r=Types.Autoplay.NONE`
I think some portion of the javascript is still trying to load the other player version.

**Comment by ronnycoolen** [comment]
I think I found it:

```
<script src="https://videoplayer.dpgmedia.net/v2/popcornPlayer.js?t=8"></script>
```

```
<script src="https://videoplayer.dpgmedia.net/v3/popcornPlayer.js?t=7"></script>
```

Can we change the v3 to v2? I'm not yet comfortable with the UBO filter syntax.

**Comment by stephenhawk8054** [comment]
uBO can't change the elements in the DOM. Remove the previous filter, can you test this one?

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=vtm.be`

**Comment by ronnycoolen** [comment]
Works like a charm! Thank you!
