### ISSUE TITLE
[nsfw] chrome.google.com: detection

### ISSUE THREAD

**Issue by cbrito80** [uBlockOrigin/uAssets#12585]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://chrome.google.com/webstore/category/extensions?pli=1`

### Category

detection

### Describe the issue

estaba ejecutando una prueba y se quedo pegada la pantalla, no pude realizar mi prueba

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/102916538/161437170-f3a7db70-4176-422e-add9-a303fe570f6a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 99
filterset (summary): 
  network: 83185
  cosmetic: 46870
  scriptlet: 16637
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65175-51, 1h.6m
    easyprivacy: 26748-121, 1h.5m
    plowe-0: 3687-807, 1h.4m
    spa-0: 3854-33, 1h.8m
    spa-1: 4289-166, 1h.8m
    ublock-abuse: 72-0, 1h.2m
    ublock-badware: 4007-89, 59m
    ublock-filters: 30506-144, 58m
    ublock-privacy: 206-2, 57m
    ublock-quick-fixes: 126-4, 1h.8m
    ublock-unbreak: 1733-42, 56m
    urlhaus-1: 7910-0, 55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 484 ms (selfie)
  maxAssetCacheWait: 311 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    google.com: 2
    doubleclick.net: 4
    youtube.com: 6
```
</details>

**Comment by cbrito80** [comment]
no pude continuar mi prueba porque se quedo pegada la pagina y necesito volver a ingresar para terminar la prueba

**Comment by mapx-** [comment]
> detection

Explain what are you doing.

**Comment by iam-py-test** [comment]
This makes no sense; uBo _can't_ access the Chrome Web Store (Chrome security) and I see no issues in Firefox
> I could not continue my test because the page stuck and I need to re-enter to finish the test

URL? Screenshot?
I'm not aware of any _tests_ on the Chrome Web Store, so I assume the issue was on another URL and you just select the Chrome webstore (and the screenshot) just so the issue submitted.

Translated (using an online translator, so please forgive any errors):
Esto no tiene sentido; uBo _can t_ acceder a Chrome Web Store (seguridad de Chrome) y no veo problemas en Firefox 
> no pude continuar mi prueba porque la página se atascó y necesito volver a ingresar para terminar la prueba 

¿URL? ¿Captura de pantalla? No tengo conocimiento de ninguna _prueba_ en Chrome Web Store, así que supongo que el problema estaba en otra URL y simplemente seleccionas la tienda web de Chrome (y la captura de pantalla) solo para que se envíe el problema.
