### ISSUE TITLE
soap2day.ac: breakage

### ISSUE THREAD

**Issue by SoPat712** [uBlockOrigin/uAssets#12584]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soap2day.ac/`

### Category

breakage

### Describe the issue

The video player fails to open with UbO on. Only when it is turned off does it open the player.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30350506/161435068-6d2a6791-4373-4420-a205-f19f13f02414.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 99
filterset (summary): 
  network: 115010
  cosmetic: 137227
  scriptlet: 30268
  html: 631
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63297-4859, 5m
    adguard-mobile: 7455-155, 4m
    adguard-annoyance: 51387-1403, 4m
    adguard-social: 16555-16, 4m
    curben-phishing: 11506-1, 4m
    curben-pup: 261-0, 4m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31099-44, 5m
    ublock-badware: 4011-3, 5m
    ublock-privacy: 211-0, 5m
    ublock-abuse: 72-0, 5m
    ublock-unbreak: 1745-0, 5m
    easylist: 65175-724, 4m
    easyprivacy: 26748-587, 4m
    urlhaus-1: 7910-0, 4m
    plowe-0: 3687-2, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 23 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15423 ms
  maxAssetCacheWait: 8848 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    clksite.com: 1
    d27qffx6rqb3qm.cloudfront.net: 2
```
</details>

**Comment by SoPat712** [comment]
Fixed temporarily by manually blocking these links

![image](https://user-images.githubusercontent.com/30350506/161435292-5772a1fb-3a7f-4f7a-a221-a933a7c5f606.png)

Probably needs a real fix though.

**Comment by mapx-** [comment]
@Yuki2718 
Adguard filter is breaking the video
`soap2day.*##+js(abort-current-script, String.fromCharCode, /emZnbG9hZGVk|break;case \$\.|break;case \d{1}/)`
