### ISSUE TITLE
facebook.com: breakage

### ISSUE THREAD

**Issue by sillvva** [uBlockOrigin/uAssets#12583]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/matt.dekok/`

### Category

breakage

### Describe the issue

Nothing below the Facebook profile menu loads when uBlock Origin is enabled on facebook.com. If I disable the extension, it loads properly.

I have tried disabling various filters one at a time to see if any of them were causing the issue, but only disabling the extension fixes the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/5138384/161431100-9e55905c-e0f1-438b-af5f-1f1004eb78c1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 79543
  cosmetic: 42198
  scriptlet: 16475
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    easylist: 65089-51, 2d.12h.56m
    easyprivacy: 26739-121, 2d.17h.1m
    plowe-0: 3687-807, 16h.22m
    ublock-abuse: 72-0, 12d.17h.51m
    ublock-badware: 4007-88, 12h.21m
    ublock-filters: 30476-88, 2d.12h.58m
    ublock-privacy: 206-2, 1d.17h.5m
    ublock-quick-fixes: 124-4, 12h.19m
    ublock-unbreak: 1744-41, 2d.12h.57m
    urlhaus-1: 7422-0, 12h.20m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1581 ms (selfie)
  maxAssetCacheWait: 244 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
Try reinstalling uBO, then update all lists.
Disable any other extension while testing again.

**Comment by sillvva** [comment]
Before reinstalling, I checked the My Filters tab and saw a facebook entry. After removing that it started working again. Not sure what I tried to remove which caused that.

False alarm.

```
! 2022-01-24 https://www.facebook.com
www.facebook.com##.sv5sfqaa
```

**Comment by iam-py-test** [comment]
> Before reinstalling, I checked the My Filters tab and saw a facebook entry. After removing that it started working again. Not sure what I tried to remove which caused that.

Before submitting an issue, it is recommended you test in a new browser profile with default settings. This will save a lot of time/effort
