### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by GitYaoHub** [uBlockOrigin/uAssets#12590]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/video/BV1HF411s7mt?spm_id_from=333.851.b_7265636f6d6d656e64.1`

### Category

breakage

### Describe the issue

The video's comment section could not be loaded.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Chromium: 100
filterset (summary): 
  network: 97179
  cosmetic: 52165
  scriptlet: 16576
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 27972-86, 2d.16h.59m
    easylist: 65092-56, 2d.17h.2m
    easyprivacy: 26743-147, 2d.17h.23m
    plowe-0: 3693-812, 9d.21h.23m
    ublock-abuse: 72-0, 5d.20h.59m
    ublock-badware: 3989-88, 2d.17h
    ublock-filters: 30479-104, 2d.17h.4m
    ublock-privacy: 205-2, 5d.21h
    ublock-unbreak: 1744-42, 2d.17h.5m
    urlhaus-1: 7422-0, 21h.55m
filterset (user): [empty]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 348 ms (selfie)
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 73
  blockedDetails: 
    bilibili.com: 67
    hdslb.com: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?

**Comment by GitYaoHub** [comment]
I just forced the filter list to be updated and it went back to normal.
Thanks
