### ISSUE TITLE
animesonline22.com: popups

### ISSUE THREAD

**Issue by fernandodiacenco** [uBlockOrigin/uAssets#12597]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.animesonline22.com/video/189814`

### Category

popups

### Describe the issue

When you click on any of the video player controls, a new ad popup opens

To reproduce: Click play video (a new popup opens) then you can start/stop normally

Now go to another tab, and back, click play again and a new popup opens.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 98
filterset (summary): 
  network: 81369
  cosmetic: 44778
  scriptlet: 16635
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65093-51, 3d.1h.46m
    easyprivacy: 26748-121, 14h.57m
    plowe-0: 3691-810, 11d.17h.48m
    spa-1: 4289-78, 14h.58m
    ublock-abuse: 72-0, 7d.1h.49m
    ublock-badware: 4007-88, 14h.56m
    ublock-filters: 30514-127, 14h.55m
    ublock-privacy: 203-2, 7d.1h.48m
    ublock-unbreak: 1730-42, 14h.54m
    urlhaus-1: 7910-0, 22h.59m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11737 ms (selfie)
  maxAssetCacheWait: 9740 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    adtrue.fun: 1
    arc.io: 1
    benoopto.com: 2
    denetsuk.com: 1
    engageya.com: 1
    google-analytics.com: 2
    googletagmanager.com: 1
    jwpcdn.com: 1
    jwpltx.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Access denied for me too.

**Comment by fernandodiacenco** [comment]
How curious, perhaps it is a geoblock thing? It should show as this:

![image](https://user-images.githubusercontent.com/2643364/161611062-02a64075-533a-4a8c-9d06-92a76fa3c611.png)

But anyway, if it is difficult/impossible to debug then I ask the issue to be closed so it wont distract from more important issues.

**Comment by mapx-** [comment]
What country are you connecting from?

Open the logger, reproduce the issue, go back into the logger and post here a screenshot containing **only the blocked items** you see there 
(you can select only the blocked items in the search box)
