### ISSUE TITLE
anti-adblock

### ISSUE THREAD

**Issue by JOSE893** [uBlockOrigin/uAssets#1259]
### antiadblock in website
 http://www.vercanalestv.com/ver-telecinco-online-y-directo-gratis-fuera-de-espana/

### intalled script AAK-cont but still not working...very aggresive & intrusive ads

![image](https://user-images.githubusercontent.com/35278183/34748075-2ce252ec-f59b-11e7-89b9-926dce8deb43.png)

### Versions

- Browser/version: chrome latest version
- uBlock Origin version: latest, installed 10 Jan

### Settings

AakList (Anti-Adblock Killer)
others: 
![image](https://user-images.githubusercontent.com/35278183/34748129-6dfd19ce-f59b-11e7-890f-50d79d6c820f.png)

### Notes

I tried executing script with tampermonkey and violentmonkey. Tamoermonkey would work first time by chance, but when I open the website again doesnt work.

**Comment by gorhill** [comment]
Can't reproduce with uBO only and default filter lists.

You are using AdBlock along with uBO, this is your issue. Don't mix uBO with another blocker, this will prevent it from working as intended (aside the pointless waste of resources).

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1242
