### ISSUE TITLE
forum.release-apk.com: detection

### ISSUE THREAD

**Issue by vjrmy** [uBlockOrigin/uAssets#12593]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forum.release-apk.com/viewforum.php?f=26&sid=c3daab55e2164e7cbdef5ee83ab39cd7`

### Category

detection

### Describe the issue

detection Anti Adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 153955
  cosmetic: 186935
  scriptlet: 35483
  html: 0
listset (total-discarded, last updated): 
  added: 
    IDN-0: 8955-0, 3m
    RUS-0: 41482-13, 3m
    VIE-1: 1967-2, 3m
    adguard-annoyance: 51389-452, 3m
    adguard-generic: 63315-981, 3m
    adguard-social: 16559-788, 2m
    adguard-spyware: 25962-842, 2m
    adguard-spyware-url: 539-13, 2m
    curben-phishing: 11656-0, 2m
    fanboy-cookiemonster: 28068-2311, 2m
    spa-1: 4289-99, 2m
    ublock-annoyances: 4230-208, 2m
  default: 
    user-filters: 1-0, never
    easylist: 65179-956, 2m
    easyprivacy: 26748-10515, 2m
    plowe-0: 3687-885, 2m
    ublock-abuse: 72-1, 2m
    ublock-badware: 4007-263, 2m
    ublock-filters: 30489-3529, 2m
    ublock-privacy: 206-39, 2m
    ublock-quick-fixes: 126-10, 2m
    ublock-unbreak: 1734-106, 2m
    urlhaus-1: 7962-1, 2m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
modifiedHiddenSettings: 
  allowGenericProceduralFilters: true
supportStats: 
  allReadyAfter: 4217 ms
  maxAssetCacheWait: 2855 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    release-apk.com: 2
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
There is a message about enabling javascript and disabling ad-blockers, but it's only visible when the page is loading. The page is fine when it has finished loading.

**Comment by JobcenterTycoon** [comment]
@mapx- do you get 1x1 images from `metric.ipv6test.net` ? I got it one time and never again. Can be tracking

**Comment by mapx-** [comment]
I get nothing like that

**Comment by vjrmy** [comment]
sorry, i'm using DoH adguard that's why detect the anti-adblock
