### ISSUE TITLE
uploaded.net anti-adblock

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#126]
### URL(s) where the issue occurs

`http://uploaded.net/file/ofvhvfdw`

### Describe the issue

Go to `http://uploaded.net/file/ofvhvfdw`, if you want to continue on this site,
you have to disable your adblocking software.

### Versions

- Browser/version: Chrome 53
- uBlock Origin version: 1.9.4

### Settings

default settings

### Notes

uploaded.net uses "FuckAdBlock", so `uploaded.net##script:inject(fuckadblock.js-3.2.0)`
enables you to use the site without disabling your adblocker.

The filter `@@||uploaded.net/js2/blocktag.js$script,first-party`
also works but i would prefer not to allow scripts.

**Comment by amirtal** [comment]
added both filters listed, but anti adblock warning is still displayed
