### ISSUE TITLE
withgoogle.com - anti adblock

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1260]
### URL(s) where the issue occurs

`https://testmysite.withgoogle.com/intl/en-gb`

### Describe the issue

`/ads/js/` from Easylist is blocking `google.com/ads/js/peitho2/peitho2.min.js` on this site and make analyze button not to work. If you add `@@/ads/js/$domain=testmysite.withgoogle.com` it will solve the issue, but is there any other solution?

### Versions

- Browser/version: Chrome 63.0.3239.108 (Official Build) (64-bit)
- uBlock Origin version: v1.14.22

**Comment by krystian3w** [comment]
No works for my PC:

Windows 7 Pro x64 
Firefox 67 x64
Nano Adblocker 1.0.0.112

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | /ads/js/* | -- | testmysite.withgoogle.com | 3 | script | `https://www.google.com/ads/js/peitho2/peitho2.min.js` |
| +1 | /ads/js/* | -- | testmysite.withgoogle.com | 3 | script | `https://www.google.com/ads/js/peitho2/peitho2.min.js` |
</details>

---

@licybora / @jspenguin2017 fyi
