### ISSUE TITLE
ppss.kr: breakage

### ISSUE THREAD

**Issue by DavidLee3835** [uBlockOrigin/uAssets#12605]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ppss.kr/`

### Category

breakage

### Describe the issue

Images on the websites removed and alert appears when refreshed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/99162643/161687629-03b562d4-d5cd-4b98-8f90-00fb03fa4fb9.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 82629
  cosmetic: 48516
  scriptlet: 16379
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    KOR-1: 8160-0, 1m
    easylist: 65339-58, 1m
    easyprivacy: 26751-125, now
    plowe-0: 3687-809, now
    ublock-abuse: 72-0, now
    ublock-badware: 4007-90, now
    ublock-filters: 30398-90, now
    ublock-privacy: 207-2, now
    ublock-quick-fixes: 124-4, 1m
    ublock-unbreak: 1734-43, now
    urlhaus-1: 8422-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1136 ms
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    ppss.kr: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed now. It happens because there is a script named "ad-shield" which brings ads back and self breaking the page (removes content images) if a adblocker try to block the ad images
