### ISSUE TITLE
euw.op.gg: ads

### ISSUE THREAD

**Issue by Tenome** [uBlockOrigin/uAssets#12603]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://euw.op.gg/summoners/euw/Built`

### Category

ads

### Describe the issue

Ads leave behind a giant empty box.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss (2022-04-04 at 09 14 24)](https://user-images.githubusercontent.com/12216081/161658781-93f91fe8-9817-4502-8334-734fe106b260.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 80583
  cosmetic: 42305
  scriptlet: 16441
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 96-4, never
    ublock-filters: 31065-29, 3d.6h.47m
    ublock-badware: 4006-3, 2d.12h.47m
    ublock-privacy: 211-0, 19h.55m
    ublock-abuse: 72-0, 2d.12h.46m
    ublock-unbreak: 1742-0, 2d.12h.45m
    easylist: 65165-574, 2d.12h.44m
    easyprivacy: 26744-590, 2d.12h.43m
    urlhaus-1: 8414-0, 6h.26m
    plowe-0: 3687-2, 19h.54m
    ublock-quick-fixes: 122-5, 6h.25m
filterset (user): [array of 96 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1661 ms (selfie)
  maxAssetCacheWait: 1112 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    op.gg: 2
    datadoghq-browser-agent.com: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    jsdelivr.net: 2
    riotgames.com: 1
    vntsm.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The homepage also has placeholder:
`https://euw.op.gg/`

Any ABP-compatible filters without using `upward`?

```
euw.op.gg##.vm-placement:upward(div[class])
euw.op.gg##[id^="div-gpt-ad"]:upward(div[class])
```

**Comment by mapx-** [comment]
it would be worth adding them to our list

**Comment by stephenhawk8054** [comment]
I think so. I failed to find a good ABP-compatible alternative.

**Comment by mapx-** [comment]
However, in these cases (when we already had previous uBO specific filters for `op.gg`), cosmetic filters can be added without any compatibility with ABP.

**Comment by stephenhawk8054** [comment]
> However, in these cases (when we already had previous uBO specific filters for `op.gg`), cosmetic filters can be added without any compatibility with ABP.

Yeah, I didn't realize we had filters for this site already until checking again  😅

**Comment by mapx-** [comment]
me neither until seeing your filters in the list :-)
