### ISSUE TITLE
tennispro.fr: breakage

### ISSUE THREAD

**Issue by PrinceLucario** [uBlockOrigin/uAssets#12606]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tennispro.fr/`

### Category

breakage

### Describe the issue

Some content on this website, as sliders, and internet-stores ajax are broken

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/61843570/161700835-52d3150e-0fd5-440a-ac15-da640c4e9dc4.png)
![image](https://user-images.githubusercontent.com/61843570/161700881-5fe1bc47-4f64-47ae-b808-a46e7853e175.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 99
filterset (summary): 
  network: 98344
  cosmetic: 51148
  scriptlet: 16533
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 27108-42, never
    easylist: 65018-651, never
    easyprivacy: 26734-892, never
    plowe-0: 3690-2, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-236, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 124-4, never
    ublock-unbreak: 1742-0, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1571 ms
  maxAssetCacheWait: 23 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    tennispro.fr: 2
    early-birds.fr: 1
    googletagmanager.com: 1
    trustedshops.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like those are blocked by

```
||early-birds.fr^$third-party
||early-birds.io^$third-party
```

in EP?

```
@@||early-birds.fr^$domain=tennispro.fr
@@||early-birds.io^$domain=tennispro.fr
```

@ryanbr

**Comment by mapx-** [comment]
that's what working on my side

`@@||tennispro.fr^$script,1p`

**Comment by stephenhawk8054** [comment]
> that's what working on my side
> 
> `@@||tennispro.fr^$script,1p`

Hmm, this part is missing for me without exceptions of `early-birds` links

<details><summary>early-birds blocked</summary>

![image](https://user-images.githubusercontent.com/66517106/161704044-beef2867-e219-4b14-a948-1f5385a26800.png)

</details>

<details><summary>early-birds exceptions</summary>

![image](https://user-images.githubusercontent.com/66517106/161703889-857f1695-65e0-490b-aa01-d46c969b6fec.png)

</details>

**Comment by mapx-** [comment]
yes, indeed, needing those exceptions too

**Comment by okiehsch** [comment]
> Hmm, this part is missing for me without exceptions of early-birds links

Yes, the "Favorites" sectionis missing without the early-bird exceptions, the other issues opened by the same OP have the same issue.

**Comment by stephenhawk8054** [comment]
I wonder how many French sports sites use this template 👀

**Comment by mapx-** [comment]
maybe we should badfilter `||early-birds.fr^$3p`
It seems to be marketing / e-commerce

**Comment by okiehsch** [comment]
At
`https://lecol.cc`
it blocks the "recommendations", not sure if these are really recomendations and favorites or if they are sponsored items.

**Comment by stephenhawk8054** [comment]
Yeah, another site from `publicwww` is

`https://www.lestropeziennes.fr/`

which blocks `Our current recommendations`. It seems at least those "recommended" links are 1st party and no tracking/affiliate components in the URL, but there might be some tracking connections (I haven't checked this carefully yet).

**Comment by ryanbr** [comment]
https://pastebin.com/ZEbQphmD   from: https://cdn.early-birds.fr/tenants/tennispro/earlybirds-full.min.js

- trackActivity
- setting/getting/checking cookies
- useragent
- fingerprinting

tracks.
