### ISSUE TITLE
tennisachat.com: breakage

### ISSUE THREAD

**Issue by PrinceLucario** [uBlockOrigin/uAssets#12608]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tennisachat.com/`

### Category

breakage

### Describe the issue

Sliders, Internet-stores content and categories are broken.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/61843570/161701723-ca239e06-5bcc-4a46-b9ce-5873067c0800.png)
![image](https://user-images.githubusercontent.com/61843570/161701983-06fab1da-e536-4c55-bc1e-f4f405971498.png)
![image](https://user-images.githubusercontent.com/61843570/161701788-0c11c94c-0a2e-4e0d-a2c4-a2e87bf6fb6e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 99
filterset (summary): 
  network: 98344
  cosmetic: 51148
  scriptlet: 16533
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 27108-42, never
    easylist: 65018-651, never
    easyprivacy: 26734-892, never
    plowe-0: 3690-2, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-236, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 124-4, never
    ublock-unbreak: 1742-0, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1571 ms
  maxAssetCacheWait: 23 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    tennisachat.com: 1
    early-birds.fr: 1
    googletagmanager.com: 1
    trustedshops.com: 1
```
</details>

**Comment by mapx-** [comment]
`@@||tennisachat.com^$script,1p`

EP issue @ryanbr
