### ISSUE TITLE
google.com: breakage interactive stock chart

### ISSUE THREAD

**Issue by cooperbang** [uBlockOrigin/uAssets#12613]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=dow&client=firefox-b-d&channel=crow5&ei=fS5MYoONB6SV9u8PjOa2wA4`

### Category

breakage

### Describe the issue

data-period cannot be chosen...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 82876
  cosmetic: 45720
  scriptlet: 16344
  html: 630
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30991-40, 3m
    ublock-badware: 4011-3, 3m
    ublock-privacy: 212-0, 3m
    ublock-abuse: 72-0, 3m
    ublock-unbreak: 1747-0, 3m
    easylist: 65344-596, 3m
    easyprivacy: 26752-589, 3m
    urlhaus-1: 8422-0, 3m
    plowe-0: 3687-2, 3m
    DEU-0: 5606-2, 3m
    ublock-quick-fixes: 121-5, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 479 ms (selfie)
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by cooperbang** [comment]
Yes, now it works!
