### ISSUE TITLE
inven.co.kr: ads

### ISSUE THREAD

**Issue by gitwoojohn** [uBlockOrigin/uAssets#12618]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.inven.co.kr/board/webzine/2097?iskin=webzine`

### Category

ads

### Describe the issue

new ad-shield

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 82634
  cosmetic: 48520
  scriptlet: 16431
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    KOR-1: 8160-0, 13h.19m
    easylist: 65339-58, 13h.16m
    easyprivacy: 26750-125, 13h.15m
    plowe-0: 3687-809, 13h.14m
    ublock-abuse: 72-0, 13h.12m
    ublock-badware: 4007-90, 13h.10m
    ublock-filters: 30482-112, 13h.9m
    ublock-privacy: 206-2, 13h.8m
    ublock-quick-fixes: 124-4, 13h.19m
    ublock-unbreak: 1734-43, 13h.7m
    urlhaus-1: 8422-0, 13h.6m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 573 ms (selfie)
  maxAssetCacheWait: 378 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    inven.co.kr: 6
    contentsfeed.com: 2
    dable.io: 1
    doubleclick.net: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    naver.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
force update `uBlock filters – Quick fixes` it got fixed 5 hours ago.
