### ISSUE TITLE
tf1info.fr: detection

### ISSUE THREAD

**Issue by feierflorin** [uBlockOrigin/uAssets#12611]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tf1info.fr/direct/`

### Category

detection

### Describe the issue

Hi, it detects the ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1995" alt="Screenshot 2022-04-05 at 12 47 31" src="https://user-images.githubusercontent.com/103038722/161737889-88c97d9b-6843-404b-b7c8-27582263035a.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 80597
  cosmetic: 42254
  scriptlet: 16440
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65175-51, 1d.17h.50m
    easyprivacy: 26748-121, 1d.17h.49m
    plowe-0: 3687-809, 9d.23h.41m
    ublock-abuse: 72-0, 21h.48m
    ublock-badware: 4007-89, 2d.13h.55m
    ublock-filters: 30471-88, 2d.13h.56m
    ublock-privacy: 206-2, 1d.17h.52m
    ublock-quick-fixes: 126-4, 21h.46m
    ublock-unbreak: 1746-42, 1d.17h.51m
    urlhaus-1: 8414-0, 21h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 830 redacted]
switchRuleset: 
  added: [array of 26 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 830 ms (selfie)
  maxAssetCacheWait: 659 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adsafeprotected.com: 1
    aticdn.net: 1
    doubleclick.net: 1
    hubvisor.io: 1
    mediarithmics.com: 1
    ownpage.fr: 1
```
</details
[my-ublock-backup_2022-04-05_12.49.05.txt](https://github.com/uBlockOrigin/uAssets/files/8417328/my-ublock-backup_2022-04-05_12.49.05.txt)
>

**Comment by mapx-** [comment]
Enable `FRA: AdGuard Français` list

**Comment by mapx-** [comment]
- all fine here once I enabled FR List
- tested in brave too

**Comment by mapx-** [comment]
I get the detection only disabling the french list

**Comment by mapx-** [comment]
No, the page works fine using its regional list. All ok.

**Comment by mapx-** [comment]
default settings + french list => page working fine.

**Comment by mapx-** [comment]
Could you test in another browser ? FF or chrome ?

**Comment by mapx-** [comment]
I tested in opera too => still all ok

**Comment by mapx-** [comment]
I did my tests with a french ip and with my country ip, no differences on my side

**Comment by feierflorin** [comment]
![tf1](https://github.com/uBlockOrigin/uAssets/assets/103038722/0af641c1-0505-4409-af39-ce134331efd9)

Hi , the problem is back again, the site detects uBlock
