### ISSUE TITLE
Syte scripts blocked by uBO

### ISSUE THREAD

**Issue by moshe-ber** [uBlockOrigin/uAssets#12615]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`www.venca.es`

### Describe the issue

'Syte AI' is a product discovery platform, providing services to ecommerce platforms via JS snippet or API ( `https://www.syte.ai/` ).
We work with companies like - Farfetch, Next, Shien, Venca, Prada, Boohoo, La Redoute, and many more...  

We have noticed that customers, who are using uBlock plugging are unable to have our JS loaded, you can find more info in the attached screenshots.

Can you please check what can be done, in order to unblock Syte AI JS ? 

### Screenshot(s)

![image-20220405-121535](https://user-images.githubusercontent.com/103051297/161778472-d8cd4740-e52a-45c8-8a42-01d22253f87b.png)
![image-20220405-121254](https://user-images.githubusercontent.com/103051297/161778486-8c3c06fd-915c-4be7-b224-c3d90eeffe4e.png)

### uBlock Origin version

1.42.2

### Browser name and version

Chrome 99.0.4844.84

### Settings

No changes were done to uBO

### Notes

uBO is blocking our scripts:

syte_textual_search_loader.js
imajs.js

**Comment by mapx-** [comment]
In the end only `venca.es` has the search broken

**Comment by moshe-ber** [comment]
@mapx- We have additional customers who has this issue:

`nourison.com`
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/103051297/161929916-4831b17e-ec39-4118-b009-d6981b113337.png">

`oakandfort.com`

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/103051297/161932139-586c8002-b9e2-438d-a841-9948d49a671e.png">

So the issue not localized to `venca.es`
We kindly request to be unblocked by uBO by default

**Comment by mapx-** [comment]
Ryan fixed the issue, update all your lists and test again

**Comment by okiehsch** [comment]
I fixed oakandfort search it was broken by un unrelated filter.

**Comment by moshe-ber** [comment]
Thank you all so much!
@mapx- what do you mean by 'update all your lists'? What is needed on our end to see that it works?

**Comment by mapx-** [comment]
how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)

**Comment by okiehsch** [comment]
> What is needed on our end to see that it works?

All of the lists will auto update, so this is just for you to be able to test it right away.

**Comment by moshe-ber** [comment]
Wonderful! it works!
Do you know you if we would need to report this for every customer website we have?

**Comment by okiehsch** [comment]
> Do you know you if we would need to report this for every customer website we have?

All your customer sites should work fine with regards to `syteapi` after updating.
If you find that there are still sites that don't work correctly let us know.

**Comment by moshe-ber** [comment]
Gotcha. Thanks everyone!

**Comment by moshe-ber** [comment]
Hey, we are seeing some customers where ublock still blocks our product:

![image](https://user-images.githubusercontent.com/103051297/162997796-5fc6a919-22d8-4f3c-b5fc-fee604f0f1be.png)

**Comment by mapx-** [comment]
> we are seeing some customers where ublock still blocks our product

explain what's broken

**Comment by moshe-ber** [comment]
@mapx- Hey - hovering over the camera/search and then clicking on the 'start' button does nothing, and generates the console error seen in the screenshot

**Comment by stephenhawk8054** [comment]
I click on `Start` and it opens this normally for me

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/163378256-61ec447f-513d-4245-8c2b-923d45d175e3.png)

</details>

**Comment by okiehsch** [comment]
It is unrelated to syte and was fixed in `EasyPrivacy` recently, if you update that list it should work fine.
https://github.com/easylist/easylist/commit/55cbfef1eb77c346170e6e5c0fe09dfbe938923a
