### ISSUE TITLE
paraphrasetool.com – anti-adblock issue

### ISSUE THREAD

**Issue by mtomsic** [uBlockOrigin/uAssets#12616]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://paraphrasetool.com/`

### Describe the issue

The website shows an anti-adblock message.

### Screenshot(s)

<img width="1440" alt="Screenshot 2022-04-05 at 16 51 23" src="https://user-images.githubusercontent.com/74558669/161782098-03c024fb-4d5b-434c-9c94-a9e3d57a6cbc.png">

### uBlock Origin version

1.42.0

### Browser name and version

Firefox 98.0.2

### Settings

**Filter lists**

- [x] Auto-update filter lists
- [x] Suspend network activity until all filter lists are loaded
- [x] Parse and enforce cosmetic filters 
- [x] Ignore generic cosmetic filters 
- [x] My filters
- [x] Built-in (6/6)
- [x] Ads (3/3)
- [x] Privacy (4/4)
- [x] Malware domains (3/3)
- [x] Annoyances (7/7)
- [x] Multipurpose (2/2)
- [x] Regions, languages (7/33)
- [x] CHN: AdGuard Chinese (中文)
- [x] DEU: EasyList Germany
- [x] FIN: Adblock List for Finland
- [x] NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
- [x] RUS: RU AdList
- [x] SWE: Frellwit's Swedish Filter
- [x] THA: EasyList Thailand

**My filters**
```

! 2022-02-18 https://www.youtube.com
www.youtube.com##.ytd-consent-bump-v2-renderer.style-scope
www.youtube.com##.opened

! 2022-02-18 https://www.google.com
||www.google.com^$generichide,domain=www.google.*
||id.google.com^$image,domain=www.google.*
google.*###atvcap
www.google.*##+js(set-constant, rwt, noopFunc)
google.*##^script:has-text(consentCookiePayload)
||consent.google.*^
google.*##^script:has-text(CONSENT)

! 2022-04-02 https://www.nytimes.com
www.nytimes.com###gateway-content

```

**Comment by mapx-** [comment]
> uBO with default lists/settings

You are using a lot of lists.
Reset to default settings and test again (disabling all other addons)

**Comment by Procyon-b** [comment]
I don't have a problem either.
Why did you enable all the lists? And why so many regional lists? Do you speak Chinese, German, Finnish, Norwegian/Danish/Icelandic, Russian, Swedish, Thai?

**Comment by iam-py-test** [comment]
> - [X]  Ignore generic cosmetic filters

That could be a problem. Please uncheck that option

**Comment by Procyon-b** [comment]
@iam-py-test I've that option usually enabled, but I still wasn't able to reproduce his problem.

**Comment by iam-py-test** [comment]
> @iam-py-test I've that option usually enabled, but I still wasn't able to reproduce his problem.

Ok, but still it's best to keep it disabled unless you see major issues with it being enabled

**Comment by stephenhawk8054** [comment]
I tested with all of your configurations, even turning on Firefox's Enhanced Tracking Protection to `Strict` but still cannot reproduce the issue. Can you force update the filter lists and check other extensions/DNS/softwares...?
