### ISSUE TITLE
malt.fr: breakage

### ISSUE THREAD

**Issue by ccomb** [uBlockOrigin/uAssets#12626]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.malt.fr/profile/completion`

### Category

breakage

### Describe the issue

After creating a profile on malt.fr, the page blocks on a spinner.  By looking at the blocked URL, I see a blocked `api.js` that may be the cause

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran de 2022-04-06 09-51-59](https://user-images.githubusercontent.com/283404/161924006-ae50bead-24d6-4e2b-8feb-eccf7657b94a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 98020
  cosmetic: 51219
  scriptlet: 16455
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31065-180, 1d.21h.33m
    ublock-badware: 4011-3, 1d.21h.34m
    ublock-privacy: 212-0, 1d.36m
    ublock-abuse: 72-0, 1d.37m
    ublock-unbreak: 1745-0, 1d.21h.36m
    easylist: 65179-720, 1d.21h.35m
    easyprivacy: 26748-577, 1d.21h.38m
    urlhaus-1: 8422-0, 20h.34m
    plowe-0: 3687-2, 3d.12h.14m
    FRA-0: 27108-356, 1d.21h.39m
    ublock-quick-fixes: 122-5, 20h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 859 ms (selfie)
  maxAssetCacheWait: 424 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    malt.fr: 1
    cloudflareinsights.com: 2
    googletagmanager.com: 1
    heapanalytics.com: 1
    hotjar.com: 1
    trustpilot.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
works fine for me
