### ISSUE TITLE
valid.x86.fr nuisance (soft anti-adblock)

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#12623]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://valid.x86.fr`

### Describe the issue

Soft anti-adblock

### Screenshot(s)

`Hi! For some reason we can't display an ad here, probably because of an ad blocker. ....`
https://user-images.githubusercontent.com/17685483/161905371-05341db8-a81d-4edc-a107-844aea141a24.png

### Notes

This filter `valid.x86.fr##+js(nostif, hhbblrlrba-300-3, 1000)` can disable the nag but leaves a placeholder so I propose this filter:
~`valid.x86.fr##.widget-advert-300-600.widget-block`~ `valid.x86.fr##.widget-advert-300-600`

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 71701
  cosmetic: 41426
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    easylist: 64454-10, 5m
    easyprivacy: 26664-121, 5m
    plowe-0: 3674-805, 4d.17h.36m
    ublock-abuse: 72-0, 5m
    ublock-badware: 3967-85, 5m
    ublock-filters: 30214-145, 5m
    ublock-privacy: 200-2, 5m
    ublock-unbreak: 1723-39, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 185 ms
```
</details>

**Comment by stephenhawk8054** [comment]
I think it could be addressed in EL as it's a placeholder for an ads.

`##.widget-advert-300-600`

@ryanbr What do you think?

**Comment by MasterKia** [comment]
Good point, since EL has `##.widget-advert-728` and `##.widget-advert-970` that affect this site.
