### ISSUE TITLE
ecosia.org

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#12620]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.ecosia.org/search?method=index&q=uBlock%20Origin`

### Describe the issue

placeholder Anti-adblock after generate second search results.

Maybe that line no logner match  (if was for anti-adblock only): https://github.com/uBlockOrigin/uAssets/blob/6c877cd9efa087e305349ec96099427aa9e1e052/filters/annoyances.txt#L2284

### Screenshot(s)

https://user-images.githubusercontent.com/35370833/161826010-89440ab5-d731-44b8-a7da-6ff0735111a5.png

### uBlock Origin version

1.42.0

### Browser name and version

Firefox Dev 100.0b1

### Settings

- enabled uBo Annoyances

### Notes

Page still detect EasyList as bait node:

```html
<div data-test-id="mainline-result-ad" data-hp="true" class="product-ads-carousel ad-result mainline__result sidebar__result snippet result" data-v-441881d1=""></div>
```

often:
`##div[data-test-id="mainline-result-ad"]`
`##.product-ads-carousel`

rare - dunno why...:

`##.ad-result`

for my side this enough fast fool JS on page and section isn't loaded:

`ecosia.org##.ad-result:empty:remove()`

**Comment by iam-py-test** [comment]
I don't see any anti-adblock
