### ISSUE TITLE
rome.egybest.com: detection

### ISSUE THREAD

**Issue by noweir** [uBlockOrigin/uAssets#12638]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rome.egybest.com/?refresh=1`

### Category

detection

### Describe the issue

the site is not working 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 99
filterset (summary): 
  network: 79743
  cosmetic: 42302
  scriptlet: 16360
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 31009-29, 15m
    ublock-badware: 4016-3, 14m
    ublock-privacy: 212-0, 13m
    ublock-abuse: 72-0, 12m
    ublock-unbreak: 1750-0, 11m
    ublock-quick-fixes: 123-5, 20m
    easylist: 65489-593, 10m
    easyprivacy: 26761-578, 8m
    urlhaus-1: 7278-0, 7m
    plowe-0: 3687-2, 6m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 513 ms
  maxAssetCacheWait: 164 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/10255
