### ISSUE TITLE
onlinehacking.in anti-adblock

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#12633]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.onlinehacking.in/`

### Describe the issue

When visiting the site, they display a popup forcing users to disable adblock.

### uBlock Origin version

1.42.2

### Browser name and version

Chrome 99.0.4844.82

### Settings

```
My filters: ! 2021-10-21 https://pixlr.com
pixlr.com##[src="/dad/slot/"]
pixlr.com###slot
||iplogger.org^$badfilter
||ipfounder.net^
||whatismyip.li^
||photographyinflux.com^
||tunneled.me^
||freeip.me^

! 2022-04-01 https://blog.fastssh.com
blog.fastssh.com###lrgwkd-blanket > div
blog.fastssh.com###lrgwkd-blanket

! 2022-04-02 https://fireliker.com
fireliker.com##center

! 2022-04-05 https://pn.cgchotbox.com
pn.cgchotbox.com##.adb

! 2022-04-06 https://dl.literaturetimes.com
dl.literaturetimes.com##.adb


```

**Comment by mapx-** [comment]
> I tried to reproduce the issue when uBO with default lists/settings

Did you ?

**Comment by krystian3w** [comment]
Try disable use own network filters by these method:


```
||ipfounder.net^$domain=~onlinehacking.in
||whatismyip.li^$domain=~onlinehacking.in
||photographyinflux.com^$domain=~onlinehacking.in
||tunneled.me^$domain=~onlinehacking.in
||freeip.me^$domain=~onlinehacking.in
```
