### ISSUE TITLE
gogoanime.fi: ads

### ISSUE THREAD

**Issue by haslador** [uBlockOrigin/uAssets#12639]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

gogoanime.fi

### Describe the issue

U-blocker has stoped blocking adds on this site again, gogoanime.fi

### uBlock Origin version

1.42.0

### Browser name and version

firefox 99.0

### Settings

none

### Notes

I have purged filter lists and updated, and did no good.

**Comment by mapx-** [comment]
too vague: what ads ? popups ? Explain it better

I added a filter killing the popups on `goload.pro` server

**Comment by haslador** [comment]
Its the same problem ive posted about 2 or 3 times before, seems every few months or even every month same thing happens.

**Comment by stephenhawk8054** [comment]
If you just mean the popup when clicking on the video player, it's fixed by @mapx- with the above commit.

**Comment by krystian3w** [comment]
If page changes same fastly iframe domain then we can not help - then can fail moving this to quick fixes if domain will be changed in 1-23 hours intervals.
