### ISSUE TITLE
sendmyway.com - anti adblock - Solvemedia CAPTCHA

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1263]
### URL(s) where the issue occurs

`https://www.sendmyway.com/pfn4b9vs45le`

### Describe the issue

Head for downloading the ebook by choosing **Free User Download**, wait for 30 seconds, and then there is a CAPTCHA which is loaded from Solvemedia. The CAPTCHA won't be loaded unless you disable uBO to show ads.

### Versions

- Browser/version: 63.0.3239.108 (Official Build) (64-bit)
- uBlock Origin version: v1.14.22

**Comment by mapx-** [comment]
test this filter
`@@||web.industrybrains.com/js/ads/async/show.js$script,domain=sendmyway.com`

**Comment by nimasaj** [comment]
@mapx- than one as well as this one `@@||industrybrains.com^$domain=sendmyway.com` due to Peter Lowe’s list.

Thanks
