### ISSUE TITLE
Voiranime.com recaptcha blocked

### ISSUE THREAD

**Issue by MK1338** [uBlockOrigin/uAssets#12632]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voiranime.com/anime/shenmue-the-animation/shenmue-the-animation-02-vostfr/`

### Describe the issue

Recaptcha challenge is blocked and can't be verified

### Screenshot(s)

https://gyazo.com/cc5aa9b69f363df69f5b02a921fcd3af

### uBlock Origin version

1.42.0

### Browser name and version

Firefox 99.0 (64-bit)

### Settings

None

### Notes

Issue can be fixed by disabling "FRA: AdGuard Français" in ublock origin settings

**Comment by JobcenterTycoon** [comment]
happened because of the filter `*$script,3p,domain=voiranime.com`

@Yuki2718 @Alex-302

**Comment by okiehsch** [comment]
`@@||google.com/recaptcha/$csp,script,subdocument` is already part of EasyList.

**Comment by Alex-302** [comment]
`@@||google.com/recaptcha/api.js` is enough on my end. Maybe better add it to Liste-FR.

**Comment by JobcenterTycoon** [comment]
@ryanbr @khrin the filter `@@||google.com/recaptcha/$csp,script,subdocument` in EL is invalid and not working
<img width="461" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/162037964-91045f7e-8901-42c9-80d1-9631528a38d3.PNG">

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/d04a833d4eab524883691ca9fc059d9a00b2a409
