### ISSUE TITLE
listen.tidal.com: ads

### ISSUE THREAD

**Issue by whizshadow** [uBlockOrigin/uAssets#12647]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://listen.tidal.com/`

### Category

ads

### Describe the issue

Unlike spotify ads getting blocked, Tidal ads still go unblocked..!!!
It still plays ads in between songs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 80463
  cosmetic: 42256
  scriptlet: 16432
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 65339-51, 2d.12h.10m
    easyprivacy: 26751-121, 2d.12h.9m
    plowe-0: 3687-807, 2d.12h.8m
    ublock-abuse: 72-0, 2d.11h.52m
    ublock-badware: 4007-90, 2d.11h.50m
    ublock-filters: 30482-111, 2d.11h.48m
    ublock-privacy: 207-2, 2d.11h.47m
    ublock-quick-fixes: 124-4, 1d.2h.34m
    ublock-unbreak: 1734-43, 2d.11h.46m
    urlhaus-1: 8132-0, 1d.2h.33m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2073 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    tidal.com: 4
    datadome.co: 1
    firebaselogging-pa.googleapis.com: 3
    googletagmanager.com: 2
    sentry.io: 2
    trackjs.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like the Free plan with ads is only available for US. Might add `geo specific` as well.

**Comment by stephenhawk8054** [comment]
@whizshadow Can you test if adding this filter works on your side?

` /^https?:\/\/listen.tidal.com\/v1\/tracks\/[0-9]{6,10}\?/$xhr,redirect=nooptext`
