### ISSUE TITLE
schlueterhyundai.com: breakage

### ISSUE THREAD

**Issue by NoseyNick** [uBlockOrigin/uAssets#12642]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.schlueterhyundai.com/`

### Category

breakage

### Describe the issue

Page begins to load, then goes completely blank / white about 2sec later

### Screenshot(s)

I assume a blank screenshot is not going to help much?   :laughing: 

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 99
filterset (summary): 
  network: 101468
  cosmetic: 72254
  scriptlet: 27882
  html: 630
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-1, 5h.14m
    adguard-generic: 63458-4842, 1d.9h.23m
  default: 
    user-filters: 3-1, never
    ublock-filters: 30993-29, 1d.9h.22m
    ublock-badware: 4011-3, 1d.9h.21m
    ublock-privacy: 210-0, 8d.24m
    ublock-abuse: 72-0, 8d.23m
    ublock-unbreak: 1745-0, 2d.10h.20m
    easylist: 65423-593, 1d.9h.20m
    easyprivacy: 26754-578, 1d.9h.19m
    urlhaus-1: 8132-4558, 5h.15m
    plowe-0: 3687-2, 4d.12h.24m
    ublock-quick-fixes: 123-4, 5h.13m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 28993 ms (selfie)
  maxAssetCacheWait: 16681 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    d2cmedia.ca: 11
    google-analytics.com: 1
    googletagmanager.com: 1
    youtube.com: 2
```
</details>

**Comment by okiehsch** [comment]
@stephenhawk8054 cany you reproduce a blank screen?

**Comment by okiehsch** [comment]
@NoseyNick does it work if you add
````
||d2cmedia.ca^$~image,badfilter
||d2cmedia.ca^$~image,~font
````
to your filter list.

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 can you reproduce a blank screen?

Ah nope, I can't reproduce the blank screen, but the website is generally broken too

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/162228564-0778b628-eb83-45c7-92b4-dbe41737188a.png)

</details>

**Comment by okiehsch** [comment]
Yes, I noticed it's broken using Firefox, the breakage is only minor using chromium.

**Comment by stephenhawk8054** [comment]
> Yes, I noticed it's broken using Firefox, the breakage is only minor using chromium.

Maybe because the CNAME is not filtered in chromium? I see there are some CNAME connections with `d2cmedia.ca` domain also.

**Comment by okiehsch** [comment]
Yes, 
````
||d2cmedia.ca^$~image,badfilter
||d2cmedia.ca^$~image,~font
@@||dealersite4.d2cmedia.ca^$domain=schlueterhyundai.com
````
fixes the breakage in Chromium and Firefox.

**Comment by NoseyNick** [comment]
Splendid, works now... Although you're right, website is generally broken **anyway**   :laughing:   :beers: :+1:
