### ISSUE TITLE
elchapuzasinformatico.com: nuisance

### ISSUE THREAD

**Issue by CesareDj** [uBlockOrigin/uAssets#12640]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://elchapuzasinformatico.com/2022/04/windows-11-se-prepara-para-un-gran-avance-en-seguridad-pero-tendras-que-reinstalar-el-os-para-ello/`

### Category

nuisance

### Describe the issue

Trying to hide the background-image, but nothing happens.

##body:style(background-image: none !important)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 99
filterset (summary): 
  network: 82812
  cosmetic: 46929
  scriptlet: 16593
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    easylist: 65489-51, 6h.45m
    easyprivacy: 26761-121, 6h.44m
    plowe-0: 3687-810, 11d.15h.15m
    spa-0: 3867-34, 2h.39m
    spa-1: 4296-167, 1d.7h.22m
    ublock-abuse: 72-0, 3d.21h.5m
    ublock-badware: 4012-90, 6h.43m
    ublock-filters: 30428-147, 6h.42m
    ublock-privacy: 206-2, 3d.21h.4m
    ublock-quick-fixes: 126-4, 2h.38m
    ublock-unbreak: 1738-44, 6h.41m
    urlhaus-1: 7278-0, 2h.40m
filterset (user): [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 544 ms (selfie)
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    elchapuzasinformatico.com: 7
    clickiocdn.com: 11
    disqus.com: 3
    google-analytics.com: 2
    googlesyndication.com: 7
    googletagmanager.com: 7
    skimresources.com: 7
```
</details>

**Comment by mapx-** [comment]
working:

```
elchapuzasinformatico.com##.bg-ad
elchapuzasinformatico.com##body:style(background-image: none !important)
```

or
```
elchapuzasinformatico.com##.bg-ad
||elchapuzasinformatico.com/*Sk1n$image
```

**Comment by CesareDj** [comment]
Yes! It works perfect! I must start with "elchapuzasinformatico.com".

**Comment by mapx-** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Fixed, thank you.
