### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by srivanthsai** [uBlockOrigin/uAssets#12645]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=-y_YOWV4kPc&list=PLu0W_9lII9aiXlHcLx-mDH1Qul38wD3aR&index=26`

### Category

ads

### Describe the issue

few grammarly ads are always visible and some unskippable ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 79870
  cosmetic: 42314
  scriptlet: 16406
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 65537-51, 9m
    easyprivacy: 26761-121, 9m
    plowe-0: 3687-808, 9m
    ublock-abuse: 72-0, 9m
    ublock-badware: 4012-90, 9m
    ublock-filters: 30450-91, 9m
    ublock-privacy: 207-2, 9m
    ublock-quick-fixes: 125-4, 9m
    ublock-unbreak: 1740-43, 9m
    urlhaus-1: 7364-0, 9m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 276 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    youtube.com: 14
    doubleclick.net: 2
    google.co.in: 1
    google.com: 2
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by krystian3w** [comment]
Duplicate  of #7636

**Comment by krystian3w** [comment]
See also EasyList recommendation https://github.com/easylist/easylist/wiki/Youtube-Issues
