### ISSUE TITLE
jysk.nl: breakage

### ISSUE THREAD

**Issue by Bucketsmith** [uBlockOrigin/uAssets#12646]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://jysk.nl/kantoor/gamestoelen/gamestoel-hallum-met-voetsteun-zwart`

### Category

breakage

### Describe the issue

it blocks the cookie domain, which you need active to play the product videos (sadly)
I've checked that my other plugins do not cause the issue!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 99
filterset (summary): 
  network: 113422
  cosmetic: 145880
  scriptlet: 22577
  html: 638
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 19h.59m
    adguard-spyware: 26115-10947, 1d.21h.58m
    adguard-spyware-url: 542-4, 1d.21h.57m
    adguard-annoyance: 51534-3512, 1d.21h.55m
    fanboy-annoyance: 66588-276, 5d.3h.44m
    ublock-annoyances: 4329-8, 1d.21h.54m
    NLD-0: 2164-30, 18h.29m
  default: 
    user-filters: 3-0, never
    ublock-filters: 30987-78, 1d.22h.2m
    ublock-badware: 4011-7, 1d.22h.1m
    ublock-privacy: 211-0, 5d.3h.46m
    ublock-abuse: 72-0, 5d.3h.45m
    ublock-unbreak: 1745-0, 1d.22h
    easylist: 65363-635, 1d.21h.59m
    easyprivacy: 26752-578, 1d.21h.56m
    urlhaus-1: 7278-0, 6h.38m
    plowe-0: 3690-3, 7d.3h.18m
    ublock-quick-fixes: 124-5, 1d.1h.46m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3145 ms (selfie)
  maxAssetCacheWait: 2113 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cookieinformation.com: 2
    googletagmanager.com: 1
    maps.googleapis.com: 1
    pinterest.com: 2
```
</details>

**Comment by mapx-** [comment]
Are you talking about the video you find after clicking here:
![image](https://user-images.githubusercontent.com/10303732/162266361-5ae4ce84-33c3-4b49-ba48-0042722c71a7.png)

?

**Comment by Bucketsmith** [comment]
Nah, it's in the feed with pictures. The second option is a video, the
third is a 360 photo.

[image: image.png]

**Comment by mapx-** [comment]
add

```
@@||policy.cookieinformation.com/uc.js$script,domain=jysk.nl
@@||policy.app.cookieinformation.com/cookiesharingiframe.html$subdocument,domain=jysk.nl
@@||policy.app.cookieinformation.com/8a7671/jysk.nl/nl.js$script,domain=jysk.nl
jysk.nl#@##coiOverlay[role="banner"]
```

**Comment by okiehsch** [comment]
It's caused by `Fanboys Annoyance list` and `Adguards Annoyance list`.
@ryanbr

**Comment by mapx-** [comment]
@Yuki2718 for AA

```
@@||policy.cookieinformation.com/uc.js$script,domain=jysk.nl
@@||policy.app.cookieinformation.com/cookiesharingiframe.html$subdocument,domain=jysk.nl
@@||policy.app.cookieinformation.com/8a7671/jysk.nl/nl.js$script,domain=jysk.nl
```

@ryanbr  for FA
```
@@||policy.app.cookieinformation.com/8a7671/jysk.nl/nl.js$script,domain=jysk.nl
@@||policy.app.cookieinformation.com/cookiesharingiframe.html$subdocument,domain=jysk.nl
jysk.nl#@##coiOverlay[role="banner"]
```

**Comment by Bucketsmith** [comment]
Why thank you! Works!
