### ISSUE TITLE
Metacritic doesn't display properly

### ISSUE THREAD

**Issue by respel** [uBlockOrigin/uAssets#1264]
### URL(s) where the issue occurs

`http://www.metacritic.com/`

### Describe the issue

The page does not display properly with uBlock Origin. With it, it displays perfectly fine.

### Screenshot(s)

![metacritic](https://user-images.githubusercontent.com/30291673/34785001-e4f4bac2-f655-11e7-84f8-001b63773510.png)

### Versions

- Browser/version: Version 63.0.3239.132 (Official Build) (64-bit)
- uBlock Origin version: 1.14.22

### Settings

- I turned on all the available filters.

**Comment by gorhill** [comment]
Unable to reproduce.

> I turned on all the available filters.

From [the wiki](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters):

> The more filter lists one add, the higher the likelihood some web pages may not render properly, due to higher probability of false positives.

**Comment by respel** [comment]
@gorhill Is there any way to resolve it without turning off the filters ?

**Comment by mapx-** [comment]
see what's blocked in logger

**Comment by mapx-** [comment]
I tested turning ON all the lists like the OP, no issue here.

**Comment by respel** [comment]
Apparently, it was because of some cookies which I blocked.
