### ISSUE TITLE
blocked.goguardian.com: privacy

### ISSUE THREAD

**Issue by stayout6789** [uBlockOrigin/uAssets#12641]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blocked.goguardian.com/?ctx=YWZpPTIyOTY1MzEmYXBpPTI2NTYyJm9pPTE1NTI0NjgwMDI1Jm91PWh0dHBzJTNBJTJGJTJGdWJsb2Nrb3JpZ2luLmdpdGh1Yi5pbyUyRnVBc3NldHMlMkYmcnM9QURNSU5fU0lURV9GSUxURVImc3Q9Y2hyb21pdW0tbSZ2PTE%3D&sum=4ce0f456`

### Category

privacy

### Describe the issue

i just need help getting past this im not in school and i cant do anything 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 99
filterset (summary): 
  network: 80460
  cosmetic: 42259
  scriptlet: 16378
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65346-51, 2d.17m
    easyprivacy: 26752-121, 2d.16m
    plowe-0: 3687-807, 2d.45m
    ublock-abuse: 72-0, 2d.44m
    ublock-badware: 4007-90, 2d.41m
    ublock-filters: 30398-89, 2d.19m
    ublock-privacy: 206-2, 2d.43m
    ublock-quick-fixes: 124-4, 22h.26m
    ublock-unbreak: 1736-43, 2d.18m
    urlhaus-1: 8132-0, 22h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3306 ms (selfie)
  maxAssetCacheWait: 2052 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by krystian3w** [comment]
Maybe school banned public IP with fastly changed owners (or may owners generate Web traffic from once IP).

**Comment by mapx-** [comment]
I guess the school permit the access only on the internal network, so nothing to do.
