### ISSUE TITLE
kijk.nl: detection

### ISSUE THREAD

**Issue by Caiuspepsi** [uBlockOrigin/uAssets#12644]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kijk.nl/`

### Category

detection

### Describe the issue

the website detects adblocker and will not play videos until you turn it off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 81196
  cosmetic: 43707
  scriptlet: 16464
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2159-13, 1d.3h.58m
    easylist: 65439-52, 1d.2h.26m
    easyprivacy: 26762-121, 1d.2h.25m
    plowe-0: 3687-810, 10d.14h.55m
    ublock-abuse: 72-0, 4d.20h.38m
    ublock-badware: 4007-90, 1d.2h.24m
    ublock-filters: 30481-133, 1d.2h.23m
    ublock-privacy: 206-2, 4d.20h.35m
    ublock-quick-fixes: 124-4, 1d.21m
    ublock-unbreak: 1736-57, 1d.2h.22m
    urlhaus-1: 8132-0, 1d.22m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 530 ms (selfie)
  maxAssetCacheWait: 226 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    kijk.nl: 1
    d3hxtvexlru8r9.cloudfront.net: 1
    newrelic.com: 1
    talpanetwork.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed a few hours ago: [https://github.com/uBlockOrigin/uAssets/commit/6e2413c3f2f1b8bd37da7f6f4fbae215fe69bdb5](https://github.com/uBlockOrigin/uAssets/commit/6e2413c3f2f1b8bd37da7f6f4fbae215fe69bdb5).

Can you force update the filter lists?

**Comment by krystian3w** [comment]
> - [x] I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")

Lie:

> `ublock-filters: 30481-133, 1d.2h.23m`

**Comment by JohnyP36** [comment]
There is already the rule `@@||kijk.nl^$ghide`. Do we still need that?

**Comment by JohnyP36** [comment]
> Fyi Dutch boys: @JohnyP36 / @BPower0036
> 
> Nice will be copy to regional supplement if page is unpopular outside of Benelux.

We have copied those rules to the Dutch filter list (EasyDutch)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/43dd32995850d922e28eafd90fb799e12d228251

**Comment by aantonowycz** [comment]
Not working for me (after cache purge and update), however by inspecting the code that produces the error message I found that by setting the following cookie, you can circumvent the detection:
`document.cookie="__ALLOW_ADBLOCK__";`
Would it be possible to implement this as a workaround/fix?

**Comment by krystian3w** [comment]
IMO not by `set.js` and uBo no have plans implement `cerate-cookie.js` to generate `__ALLOW_ADBLOCK__`.

So need use other arsenal scriptlets/redirect-rule resources.

**Comment by stephenhawk8054** [comment]
> Not working for me (after cache purge and update), however by inspecting the code that produces the error message I found that by setting the following cookie, you can circumvent the detection: `document.cookie="__ALLOW_ADBLOCK__";` Would it be possible to implement this as a workaround/fix?

Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by aantonowycz** [comment]
Apologies for the inconvenience, it appears the EasyDutch list was not enabled while I thought it was, making the `__ALLOW_ADBLOCK__` unnecessary. The current implementation works.

**Comment by stephenhawk8054** [comment]
Fixed at https://github.com/uBlockOrigin/uAssets/commit/657ba12b49174d06a217ef0083694f2f91d2b994

**Comment by OneLoveX** [comment]
Problem still exits.

**Comment by stephenhawk8054** [comment]
Are you using uBO or uBOL?

**Comment by OneLoveX** [comment]
uBOL

**Comment by stephenhawk8054** [comment]
Wait until version `2026.125.1931` is updated on your side.

Or you can add this custom filter in the meantime:

```adb
||ssl.p.jwpcdn.com/player/v/*/freewheel.js$script
```

1. Go to uBOL dashboard `Settings` pane 
2. Enable `Developer mode` 
3. Go to `Develop` pane 
4. Choose `Custom DNR rules`
5. Copy paste the above filter(s) and `Save`, open new tab and test again

**Comment by persiansub88** [comment]
It works...tnx a lot my friend!!! 💃
