### ISSUE TITLE
vidembed.me/moviepl.xyz (annoyance)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#12652]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://vidembed.me/videos/elite-season-5-episode-1
https://moviepl.xyz/f/x3m27h5l-2m0rrw
```

### Describe the issue

when opening dev tools
site saying 
Close DevTools & Reload 
or don't open dev tools /redirects to `google.de`

### uBlock Origin version

1.42.4

### Browser name and version

opera browser

### Settings

_Default_

**Comment by mapx-** [comment]
go to directly & play
`https://vidembed.me/streaming.php?id=MzYxNzk3&title=Elite+-+Season+5+Episode+1&typesub=SUB&sub=&cover=Y292ZXIvZWxpdGUtc2Vhc29uLTUucG5n`

F12 & then play again the video

**Comment by stephenhawk8054** [comment]
> go to directly & play `https://vidembed.me/streaming.php?id=MzYxNzk3&title=Elite+-+Season+5+Episode+1&typesub=SUB&sub=&cover=Y292ZXIvZWxpdGUtc2Vhc29uLTUucG5n`
> 
> F12 - refresh the page - play again the video

Ah right, I forgot about situation of opening dev tools before playing.

**Comment by ghajini** [comment]
iam still getting redirected to google.de when surfing `https://moviepl.xyz/f/x3m27h5l-2m0rrw` & then dev tool opened,console cleared

`moviepl.xyz##+js(nostif, debugger)` or `moviepl.xyz##+js(nostif, devtoolIsOpening, 100)`

also  `moviepl.xyz##+js(aopr, __Y)` for popunders

**Comment by stephenhawk8054** [comment]
Hmmm... I get no redirections with `moviepl.xyz##+js(acis, devtoolIsOpening)`, even when opening dev tools while in page/video or before loading the page/video.

**Comment by ghajini** [comment]
on my side it's like this 
![opera_QzYikfMm6e](https://user-images.githubusercontent.com/20338483/162453308-95454fc2-87d8-4d93-9834-c51557983b99.gif)

**Comment by stephenhawk8054** [comment]
> on my side it's like this

Ah yeah, confirm I can reproduce it with Edge too. It's weird that both Chrome and Brave work fine, while Opera and Edge not. I'll adjust it to `nostif`.
