### ISSUE TITLE
[nsfw] milfnuts.net: nuisance

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#12658]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://milfnuts.net/24797/horny-step-mom-squirts-juliett-lopez/`

### Category

nuisance

### Describe the issue

Overlay play button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220409-030852227 (1)](https://user-images.githubusercontent.com/56762704/162519431-7b329857-b6a4-4332-8ca4-f80702ea3593.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 79957
  cosmetic: 108268
  scriptlet: 20626
  html: 0
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6104-1, 3d.12h.38m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 4938-14, 3d.4h.9m
    fanboy-annoyance: 66791-197, 2d.14h.51m
    ublock-annoyances: 4342-53, 2d.14h.51m
  default: 
    user-filters: 6-0, never
    easylist: 65337-1275, 3d.12h.40m
    easyprivacy: 26752-121, 3d.12h.39m
    ublock-abuse: 72-0, 2d.15h.28m
    ublock-badware: 4007-89, 3d.4h.8m
    ublock-filters: 30501-180, 3d.4h.7m
    ublock-privacy: 207-9, 2d.15h.27m
    ublock-quick-fixes: 126-4, 22h.50m
    ublock-unbreak: 1741-46, 3d.4h.6m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2391 ms (selfie)
  maxAssetCacheWait: 1244 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    condolencessumcomics.com: 1
    googletagmanager.com: 1
    hqq.to: 1
    lammasbananas.com: 1
    snugglethesheep.com: 1
    trdnewsnow.net: 1
    tubecorp.com: 2
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
add

```
hqq.to##[href="https://t.me/Russia_Vs_Ukraine_War3"]
||trdnewsnow.net/*/ban/iframe/$subdocument
```

You have to click the "overlay button" to start the video
