### ISSUE TITLE
tinyurl.is: ads

### ISSUE THREAD

**Issue by WebbJayden** [uBlockOrigin/uAssets#12667]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tinyurl.is/KcOZ?sport=soccer`

### Category

ads

### Describe the issue

pop ups on this page that lead to external website that could be potentially harmful

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80381
  cosmetic: 42324
  scriptlet: 16406
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65546-51, 22h.7m
    easyprivacy: 26763-121, 22h.11m
    plowe-0: 3687-808, 4d.20h.16m
    ublock-abuse: 72-0, 9d.27m
    ublock-badware: 4012-90, 22h.9m
    ublock-filters: 30451-91, 22h.10m
    ublock-privacy: 205-2, 9d.28m
    ublock-quick-fixes: 127-4, 19h.31m
    ublock-unbreak: 1739-43, 22h.8m
    urlhaus-1: 7873-0, 15h.56m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 141 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    awigglespouter.cam: 1
    cdn4ads.com: 1
    celeritascdn.com: 1
    cylize.com: 1
    d3g5ovfngjw9bw.cloudfront.net: 1
    google-analytics.com: 1
    linkonclick.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 ads are back on AG too

**Comment by ghajini** [comment]
another case for regex filter update

`https://ct.cerebrifetors.com/g624c0dfcc4d7d624c0dfcc4d81/44257`

**Comment by okiehsch** [comment]
You can add 
````
tinyurl.is##+js(acis, JSON, interactive)
tinyurl.is##+js(no-fetch-if, xhr0)
`````
to disable the offending inline scripts too.

**Comment by Yuki2718** [comment]
> another case for regex filter update

Maybe I have to revert back to `[a-z]`, which I wanted to avoid as far as possible as the current regex is far broad than the original.

**Comment by ghajini** [comment]
> You can add 
> ````
> tinyurl.is##+js(acis, JSON, interactive)
> tinyurl.is##+js(no-fetch-if, xhr0)
> `````
> to disable the offending inline scripts too.

can csp be option? i tried, it works good

**Comment by ghajini** [comment]
it is very well fixed with your filters👍👍👍
my mind is just curious 😇 ublock origin🤩
