### ISSUE TITLE
fmovies.to: [unknown]

### ISSUE THREAD

**Issue by evaa198** [uBlockOrigin/uAssets#12668]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/`

### Category

[unknown]

### Describe the issue

its great

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 94
filterset (summary): 
  network: 80328
  cosmetic: 42320
  scriptlet: 16405
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 65541-51, 1d.17h.27m
    easyprivacy: 26761-121, 1d.17h.26m
    plowe-0: 3687-810, 12d.13h.8m
    ublock-abuse: 72-0, 7d.20h.18m
    ublock-badware: 4012-90, 1d.17h.25m
    ublock-filters: 30450-91, 1d.17h.24m
    ublock-privacy: 206-2, 7d.20h.17m
    ublock-quick-fixes: 127-4, 12h.35m
    ublock-unbreak: 1740-43, 1d.17h
    urlhaus-1: 7824-0, 12h.37m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10513 ms (selfie)
  maxAssetCacheWait: 2622 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    disqus.com: 1
    likedstring.com: 2
```
</details>

**Comment by okiehsch** [comment]
> its great

Good to know.
