### ISSUE TITLE
jazzradio.com social login failed

### ISSUE THREAD

**Issue by andzi** [uBlockOrigin/uAssets#1266]
### URL(s) where the issue occurs

`jazzradio.com`

### Describe the issue

ERROR MESSAGE: social login failed 
when ogging with Google, even with disabled plugin

### Versions

- Browser/version: FF Dev. Ed. 58.0b13 (64-bit)
- uBlock Origin version: uBlock Origin v1.14.22

### Settings

- enabled some general 3rd party filters
- firebaseapp.com added to whitelist

### Notes

login failed even with disabled plugin, firebaseapp.com added to whitelist but not helps

**Comment by mapx-** [comment]
no issue for me logging in using google account

**Comment by P0Rtvine** [comment]
After 5-10 minutes of playback, a window appears with a reminder that you need to login, otherwise the pleasure will end in 30 minutes.
Can you fix it?
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/126279756-c89f77af-a6a7-4ca4-bd02-68e8d5a52074.png)
</details>

**Comment by P0Rtvine** [comment]
@mapx- 
Can you fix it?

**Comment by mapx-** [comment]
I have no idea if can be "fixed". 
However, it's kind of paywall and we don't fix that.

**Comment by andzi** [comment]
> `https://www.jazzradio.com/pariscafe`
> 
> After 5-10 minutes of playback, a window appears with a reminder that you need to login, otherwise the pleasure will end in 30 minutes.
> Can you fix it?
> 
> Screen
> ![image](https://user-images.githubusercontent.com/57287308/126279756-c89f77af-a6a7-4ca4-bd02-68e8d5a52074.png)

You can fix yourself: register for the free or paid account ;)
