### ISSUE TITLE
dawn.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#1267]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.dawn.com/

### Describe the issue

Ad Banner appears despite UBO on. 

### Versions

- Browser/version: Chrome/Latest 
- uBlock Origin version: Latest

### Settings

- Default

**Comment by mapx-** [comment]
Where is that ad ? upload a screenshot, eventually specific link where you see the ad

**Comment by ReyCobin** [comment]
Scroll down, you will see sponsored content banner.

**Comment by SMed79** [comment]
> Scroll down, you will see sponsored content banner.

? This one http://i.imgur.com/sSuCvZg.png

**Comment by mapx-** [comment]
probably, add 
`dawn.com##.sponsored-content`
