### ISSUE TITLE
dizilla.io: ads

### ISSUE THREAD

**Issue by doukanTR** [uBlockOrigin/uAssets#12684]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizilla.io/`

### Category

ads

### Describe the issue

ad blocker not working on this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80946
  cosmetic: 42179
  scriptlet: 16440
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31060-40, never
    ublock-badware: 3993-3, never
    ublock-privacy: 210-0, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1753-0, never
    ublock-quick-fixes: 138-4, never
    easylist: 65018-585, never
    easyprivacy: 26734-577, never
    urlhaus-1: 8896-0, never
    plowe-0: 3690-2, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 469 ms
  maxAssetCacheWait: 172 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    aj2373.online: 2
    googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `TUR: AdGuard Turkish` list in the settings.
