### ISSUE TITLE
Clicking on any of the channel links freezes browser (GA)

### ISSUE THREAD

**Issue by jeffshead** [uBlockOrigin/uAssets#12687]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.banned.video/channel/kristi-leigh-tv`

### Describe the issue

No issue browsing to `https://www.banned.video` but clicking on any of the links to the different channels causes the browser to freeze. Pages will not load. Goggle Analytics (GA) is being blocked hundreds of times.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 91
filterset (summary): 
  network: 80385
  cosmetic: 42326
  scriptlet: 16369
  html: 632
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31035-91, 1d.15h.48m
    ublock-badware: 4016-3, 1d.15h.47m
    ublock-privacy: 212-0, 1d.15h.45m
    ublock-abuse: 73-0, 1d.15h.44m
    ublock-unbreak: 1750-0, 1d.15h.43m
    ublock-quick-fixes: 123-5, 15h.39m
    easylist: 65579-518, 1d.15h.41m
    easyprivacy: 26763-591, 1d.15h.40m
    urlhaus-1: 7846-0, 15h.38m
    plowe-0: 3683-2, 1d.15h.38m
filterset (user): [empty]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 500 ms (selfie)
  maxAssetCacheWait: 200 ms
```
</details>

**Comment by mapx-** [comment]
Does this filter work for you ?

`banned.video#@#+js(set-constant, Object.prototype.ads, noopFunc)`

**Comment by jeffshead** [comment]
> Does this filter work for you ?
> 
> `banned.video#@#+js(set-constant, Object.prototype.ads, noopFunc)`

Wow. That was fast. Thank you. Yes, the page now loads and the videos can be played so long as you watch the ads and click on the **Skip ad** button after the allotted time.
![Snag_3dc7234b](https://user-images.githubusercontent.com/349651/162624435-7d40c9e9-554d-4db9-b489-69a324d17c3d.png)

**Comment by stephenhawk8054** [comment]
@mapx- @jeffshead Can you test this?

`banned.video##+js(set, Object.prototype.nopreroll_, true)`

Looks like it can skip ads and no freezing so far for me.

**Comment by mapx-** [comment]
- no breakage, as for ads I'm not sure because I cannot get those ads
- could you test for `freeworldnews.tv` too ?

**Comment by jeffshead** [comment]
> @mapx- @jeffshead Can you test this?
> 
> ```
> banned.video#@#+js(set-constant, Object.prototype.ads, noopFunc)
> banned.video##+js(set, Object.prototype.nopreroll_, true)
> ```
> 
> Looks like it can skip ads and no freezing so far for me.

Awesome! So far no ads and no freezing. Thank you.

**Comment by stephenhawk8054** [comment]
> * could you test for `freeworldnews.tv` too ?

Yup, `freeworldnews.tv##+js(set, Object.prototype.nopreroll_, true)` skip ads for me too. Without it, I get an ads before video begins
