### ISSUE TITLE
[nsfw] pornvite.org: nuisance

### ISSUE THREAD

**Issue by 3xploitzer0** [uBlockOrigin/uAssets#12689]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pornvite.org/cheating-anal-therapy/`

### Category

nuisance

### Describe the issue

Overlay

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220411-005521571](https://user-images.githubusercontent.com/56762704/162632853-87828e07-a86f-402d-8432-690952b81543.jpg)

![Uploading Screenshot_20220411-005521571.jpg…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 81764
  cosmetic: 114690
  scriptlet: 21232
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6109-1, now
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 4938-14, now
    fanboy-annoyance: 67904-212, now
    ublock-annoyances: 4335-52, now
  default: 
    user-filters: 6-0, never
    adguard-mobile: 7553-24, now
    easylist: 65612-1459, now
    easyprivacy: 26776-130, now
    ublock-abuse: 74-0, now
    ublock-badware: 4032-89, now
    ublock-filters: 30585-196, now
    ublock-privacy: 206-9, now
    ublock-quick-fixes: 130-0, now
    ublock-unbreak: 1749-47, now
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2175 ms (selfie)
  maxAssetCacheWait: 1254 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    pornvite.org: 3
    condolencessumcomics.com: 1
    googletagmanager.com: 1
    hqq.to: 1
    imglnkd.com: 1
    realsrv.com: 4
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by Procyon-b** [comment]
This?
```
pornvite.org##.hustle-popup
```
