### ISSUE TITLE
identi.li  incorrect blocking ?

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1268]
URL(s) where the issue occurs

`http://www.identi.li/index.php?topic=497807`

Describe the issue

incorrect blocking ?

![](https://i.imgur.com/62Ij8zS.png)
![](https://i.imgur.com/o2LKslF.png)
![](https://i.imgur.com/tNcawdC.png)

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
I confirm the page is shown correctly in my side as well.

**Comment by xDarkARG** [comment]
I already tried a vpn and the error follows. deactivating the Spanish easylist filter solved the problem @mapx- @diaux

**Comment by diaux** [comment]
I believe this should be fixed. Please confirm. https://github.com/easylist/easylistspanish/commit/4a286fbe89d7b6b1f19f0628c176d71b21344794

**Comment by xDarkARG** [comment]
@diaux funciona perfecto It works perfect

**Comment by xDarkARG** [comment]
@diaux parese funcionar bien pero despues se muestra mal

**Comment by diaux** [comment]
I do not have a login for that website, but it appears to work OK for me.

**Comment by KiLL4FuNK** [comment]
@diaux fijate si puedes corregir el error esta en la lista de  easylist spanish
