### ISSUE TITLE
willandable.co.nz: breakage

### ISSUE THREAD

**Issue by Function-10** [uBlockOrigin/uAssets#12690]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://willandable.co.nz/products/ecodish-liquid`

### Category

breakage

### Describe the issue

The "subscribe & save" options are not available with uBO enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/21187724/162641756-3b256b9f-fae1-4b85-b0bd-db5ae5f077fb.png)
![image](https://user-images.githubusercontent.com/21187724/162641768-170d758a-e02f-4db1-beb1-c987eb62c17d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 98
filterset (summary): 
  network: 80314
  cosmetic: 42325
  scriptlet: 16358
  html: 632
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 31016-28, 2d.3h.2m
    ublock-badware: 4016-3, 2d.3h.1m
    ublock-privacy: 210-0, 9d.9h.10m
    ublock-abuse: 72-0, 9d.9h.9m
    ublock-unbreak: 1751-0, 2d.3h
    easylist: 65577-596, 2d.2h.59m
    easyprivacy: 26763-578, 2d.2h.58m
    urlhaus-1: 7765-0, 2h.53m
    plowe-0: 3690-2, 11d.17h.20m
    ublock-quick-fixes: 128-1, 2h.52m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 803 ms (selfie)
  maxAssetCacheWait: 219 ms
popupPanel: 
  blocked: 48
  blockedDetails: 
    facebook.net: 1
    getcarro.com: 9
    google-analytics.com: 2
    google.com: 15
    googletagmanager.com: 2
    hotjar.com: 1
    shopify.com: 2
    shopifycloud.com: 10
    shopifysvc.com: 6
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
@@||www.google-analytics.com/analytics.js$script,domain=willandable.co.nz
@@||www.googletagmanager.com/gtag/js$script,domain=willandable.co.nz
```
