### ISSUE TITLE
ytv.co.jp: nuisance

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#12693]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ytv.co.jp/michiura_time/contents/202204/peteye9fpwbbe4hm.html`

### Category

nuisance

### Describe the issue

Cannot open context menu with right click

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81366
  cosmetic: 47580
  scriptlet: 16479
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    JPN-1: 6456-7, 2d.20h.2m
    easylist: 65545-134, 2d.20h.3m
    easyprivacy: 26763-142, 2d.20h.3m
    plowe-0: 3684-814, 2d.20h.2m
    ublock-abuse: 73-0, 2d.20h.3m
    ublock-badware: 4012-90, 2d.20h.3m
    ublock-filters: 30434-94, 2d.20h.3m
    ublock-privacy: 207-2, 2d.20h.3m
    ublock-quick-fixes: 127-4, 2d.20h.3m
    ublock-unbreak: 1740-46, 2d.20h.3m
    urlhaus-1: 7873-0, 2d.20h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 374 ms
  maxAssetCacheWait: 174 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    ytv.co.jp: 1
    anymind360.com: 1
    doubleclick.net: 1
    google.com: 2
    newrelic.com: 1
    www.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`
