### ISSUE TITLE
Load More button blocked on Sammobile.com website

### ISSUE THREAD

**Issue by iamiceparticle** [uBlockOrigin/uAssets#12691]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sammobile.com/`

### Describe the issue

When I enable adblocker on Firefox (adguard or ublock origin) scripting on sammobile doesn't work. For example on the homepage when you scroll to bottom you will see load more button. It doesn't work. It started happening after recent update. Earlier it was working fine.

Adguard is also blocking the load more button, but I was able to give exception to one script and it started working with adguard.

### Screenshot(s)

![Screenshot_20220411-141104_Firefox Nightly](https://user-images.githubusercontent.com/76210878/162698851-d826e3a3-cbf2-437f-96ae-599c1407dfc5.jpg)
![Screenshot_20220410-141227_Firefox Nightly](https://user-images.githubusercontent.com/76210878/162698867-27fc60db-e53e-4469-9ef9-dffb5ca9f8d0.jpg)

### uBlock Origin version

1.42.4

### Browser name and version

Firefox nightly 101.0a1 (Build #2015873643), aaad28ad7+

### Settings

No change in default settings.

**Comment by mapx-** [comment]
Update all filter lists & test again keeping only uBO enabled

**Comment by iamiceparticle** [comment]
Thanks, it's working fine now.
