### ISSUE TITLE
hotspotty.net: breakage

### ISSUE THREAD

**Issue by gutyex** [uBlockOrigin/uAssets#12697]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hotspotty.net/`

### Category

breakage

### Describe the issue

Main page appears blank. Disabling cosmetic filtering makes the page work as normal, cosmetic filtering can be re-enabled once logged in and the site continues to function as normal. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/42444475/162787582-87a80253-87f2-4a63-9dd5-18a5a5f9feec.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 91609
  cosmetic: 158745
  scriptlet: 22101
  html: 639
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.2h.31m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    ublock-annoyances: 4337-6, 3d.3h.34m
    adguard-annoyance: 51704-4300, 3d.3h.33m
    adguard-social: 16754-1091, 3d.3h.32m
    fanboy-thirdparty_social: 69-0, 7d.7h.28m
    fanboy-annoyance: 66779-51475, 7d.7h.30m
    fanboy-cookiemonster: 28068-96, 7d.7h.29m
    fanboy-social: 23260-29, 3d.3h.31m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31037-28, 3d.3h.30m
    ublock-badware: 4016-3, 3d.3h.29m
    ublock-privacy: 211-0, 7d.7h.32m
    ublock-abuse: 72-0, 7d.7h.31m
    ublock-unbreak: 1751-0, 3d.3h.37m
    easylist: 65545-616, 3d.3h.36m
    easyprivacy: 26763-585, 3d.3h.35m
    plowe-0: 3690-2, 12d.3h.32m
    urlhaus-1: 7301-0, 3h.37m
    ublock-quick-fixes: 127-0, 3h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1461 ms (selfie)
  maxAssetCacheWait: 300 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's because of the filter `##.cookies-not-set:not(body)` in EasyList Cookie and Fanboy's Annoyance.

Add

```
hotspotty.net#@#.cookies-not-set:not(body)
```

@ryanbr
