### ISSUE TITLE
minecraftpolska.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1269]
URL(s) where the issue occurs

`http://minecraftpolska.net/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by BottledSoda** [comment]
`http://minecraftpolska.net/` looks inactive to me

**Comment by BottledSoda** [comment]
> http://minecraftpolska.net/

this looks inactive to me
