### ISSUE TITLE
 gadgets ndtv issue

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#127]
@gorhill 
### URL(s) where the issue occurs

http://gadgets.ndtv.com/telecom/features/reliance-jio-prices-revealed-5-facts-on-whats-on-offer-and-when-1453087?pfrom=home-gadgetstop

### Describe the issue

adblocker alert seen on above site
### Screenshot(s)

![screenshot 33](https://cloud.githubusercontent.com/assets/20338483/18181332/5c677b6a-70a8-11e6-9b8c-a7d7e2c4aaa0.png)

### Versions

- Browser/version: chrome Version 53.0.2785.89 m (64-bit)

- uBlock Origin version: 1.9.4

### Settings

- uBO's default settings+antiadblock killer+adblock warning removal+youtube pure video

**Comment by ghajini** [comment]
issue is back even worsened.......
with ublock on content is hided.......
also antiadblock notice is given on
`http://www.ndtv.com/india-news/pm-modi-gets-emotional-says-left-family-and-home-for-nation-1624869?pfrom=home-lateststories`

**Comment by ghajini** [comment]
@gorhill 
if you have time,plz fix it
content is hidden on page 
`http://khabar.ndtv.com/news/chennai/jallikattu-case-supreme-court-says-cannot-allow-social-evil-in-name-of-tradition-1436224`

also adblocker alert with article content hidden
`http://www.ndtv.com/world-news/president-trumps-first-seven-days-of-false-claims-inaccurate-statements-and-exaggerations-1653349?pfrom=home-lateststories`

**Comment by mapx-** [comment]
add
`@@||s3.amazonaws.com/khachack/$script`

**Comment by ghajini** [comment]
works thanx @mapx- 
whitelisting amazonaws

**Comment by okiehsch** [comment]
Does `ndtv.com##script:inject(abort-on-property-read.js, ___p__p)`
 work?

**Comment by ghajini** [comment]
works @okiehsch 
thanx
this rule should not break site functionality

**Comment by uBlock-user** [comment]
> any other solution besides this

`||ndtv.com^$inline-script`

**Comment by ghajini** [comment]
on main page `special coverage on ....` is a legit site redirect to `profit.ndtv.com/budget`
![screenshot 126](https://cloud.githubusercontent.com/assets/20338483/22788808/06eb7dac-ef07-11e6-86ac-6cc8a0cb35ac.png)

but it is blocked by rule in peter lowes list
![screenshot 125](https://cloud.githubusercontent.com/assets/20338483/22788823/133ec4ce-ef07-11e6-9808-5a2b3ed2a7ce.png)
probably need a correction
