### ISSUE TITLE
sachvui.net: detection

### ISSUE THREAD

**Issue by anhkhoakz** [uBlockOrigin/uAssets#12703]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sachvui.net/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/52970693/162973669-9c6d1d7b-c2a2-41c8-a0f9-571a14011ee7.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 168780
  cosmetic: 218434
  scriptlet: 35484
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41569-9, 1d.8h.13m
    VIE-1: 1932-2, 23h.24m
    adguard-annoyance: 51778-464, 1d.8h.28m
    adguard-generic: 63611-930, 1d.8h.27m
    adguard-mobile: 7553-72, 1d.8h.26m
    adguard-social: 16769-863, 1d.8h.25m
    adguard-spyware: 26141-953, 1d.8h.24m
    adguard-spyware-url: 547-13, 1d.8h.23m
    ara-0: 2565-21, 2d.4h.55m
    block-lan: 43-0, 5d.23h.3m
    curben-phishing: 13544-0, 23h.23m
    curben-pup: 267-0, 23h.22m
    dpollock-0: 10363-241, 5d.23h.3m
    fanboy-annoyance: 66792-4053, 5d.23h.3m
    fanboy-cookiemonster: 28077-28077, 5d.23h.3m
    fanboy-social: 23270-23262, 1d.8h.20m
    fanboy-thirdparty_social: 69-21, 5d.23h.3m
    ublock-annoyances: 4314-217, 1d.8h.18m
  default: 
    user-filters: 8-0, never
    easylist: 65640-1390, 1d.8h.22m
    easyprivacy: 26775-10485, 1d.8h.21m
    plowe-0: 3687-1335, 5d.23h.3m
    ublock-abuse: 74-1, 1d.8h.19m
    ublock-badware: 4032-290, 1d.8h.17m
    ublock-filters: 30492-3498, 1d.8h.16m
    ublock-privacy: 206-43, 1d.8h.15m
    ublock-quick-fixes: 129-5, 23h.21m
    ublock-unbreak: 1744-106, 1d.8h.14m
    urlhaus-1: 7301-1, 23h.20m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1371 ms (selfie)
  maxAssetCacheWait: 1139 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    facebook.net: 2
    google-analytics.com: 2
    googlesyndication.com: 4
```
</details>

**Comment by JohnyP36** [comment]
I cannot reproduce this issue. 
##### I had the Edge built-in `Tracking prevention` turned off.
