### ISSUE TITLE
flightsim.to: detection

### ISSUE THREAD

**Issue by NomadElf** [uBlockOrigin/uAssets#12709]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://flightsim.to/`

### Category

detection

### Describe the issue

It is detecting uBlock and severely slowing down the downloads as well as showing warnings/longer cooldowns. I've tried purging my cache and updating the lists but it didn't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80373
  cosmetic: 43647
  scriptlet: 19263
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4324-7, 2m
  default: 
    user-filters: 0-0, never
    easylist: 65761-51, 2m
    easyprivacy: 26778-121, 2m
    plowe-0: 3687-808, 2m
    ublock-abuse: 74-0, 2m
    ublock-badware: 4057-93, 2m
    ublock-filters: 30502-100, 1m
    ublock-privacy: 208-2, 1m
    ublock-quick-fixes: 142-0, 1m
    ublock-unbreak: 1753-42, 1m
    urlhaus-1: 7377-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 314 ms (selfie)
  maxAssetCacheWait: 216 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    flightsim.to: 2
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    gstatic.com: 3
    primis.tech: 3
    pub.network: 2
    quantserve.com: 1
    sharethis.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Which browser are you using? Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocker,
- External blocking softwares outside browser,
- OS' hosts file for blocking

**Comment by NomadElf** [comment]
Chrome.
I don't really have any other external blocking software.
