### ISSUE TITLE
autotrader.co.uk: ads

### ISSUE THREAD

**Issue by LixMyBalls** [uBlockOrigin/uAssets#12700]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.autotrader.co.uk/car-search?sort=price-asc&postcode=bh51lr&radius=200&make=Jaguar&include-delivery-option=on&price-to=500`

### Category

ads

### Describe the issue

Obtrusive ads blended into the search function

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 79878
  cosmetic: 42336
  scriptlet: 16420
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65544-51, 3d.13h.50m
    easyprivacy: 26776-121, 6h.44m
    plowe-0: 3690-810, 10d.18h.48m
    ublock-abuse: 72-0, 11d.10h.51m
    ublock-badware: 4032-90, 6h.43m
    ublock-filters: 30494-90, 6h.42m
    ublock-privacy: 205-2, 11d.10h.50m
    ublock-quick-fixes: 129-0, 10h.45m
    ublock-unbreak: 1750-42, 6h.41m
    urlhaus-1: 7301-0, 6h.40m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 341 ms (selfie)
  maxAssetCacheWait: 249 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    atcdn.co.uk: 1
    googletagservices.com: 1
    scorecardresearch.com: 1
    sentry.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
For `Ad` section:

```
autotrader.co.uk##.search-page__products > [data-is-promoted-listing]
```

For `You may also like` section:

```
autotrader.co.uk##.search-page__products > [data-is-ymal-listing]
```

Should `You may also like` be considered as ads?

@ryanbr What do you think?
