### ISSUE TITLE
cheatermad.com: detection

### ISSUE THREAD

**Issue by lyonkrs** [uBlockOrigin/uAssets#12702]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cheatermad.com/`

### Category

detection

### Describe the issue

it has new AdBlock detection, it didn't detect it last time I checked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 79906
  cosmetic: 42375
  scriptlet: 16425
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-1, never
    easylist: 65612-51, 1d.13h.54m
    easyprivacy: 26776-121, 1d.13h.53m
    plowe-0: 3684-808, 1d.13h.56m
    ublock-abuse: 72-0, 11d.14h.16m
    ublock-badware: 4032-90, 1d.13h.52m
    ublock-filters: 30501-92, 1d.13h.51m
    ublock-privacy: 205-2, 11d.14h.15m
    ublock-quick-fixes: 129-0, 8h.30m
    ublock-unbreak: 1741-42, 1d.13h.55m
    urlhaus-1: 7301-0, 8h.29m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1063 ms (selfie)
  maxAssetCacheWait: 147 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    media.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Which browser are you using?

**Comment by lyonkrs** [comment]
i'm using chrome

**Comment by lyonkrs** [comment]
![image](https://user-images.githubusercontent.com/58339173/162866721-bee1feb2-2651-47ba-a5eb-fa71f26712b0.png)

**Comment by stephenhawk8054** [comment]
Can you force update the lists, and check if you are using any:

- Other extensions,
- DNS blocker,
- External blocking softwares outside browser,
- OS' hosts file for blocking

**Comment by Disqu3-mirOir-qt** [comment]
cheatermad.com#$#body {z-index: 9999 !important; overflow: auto !important;}

cheatermad.com##.adblockalert

**Comment by Procyon-b** [comment]
This filter works too:
```
cheatermad.com##+js(acis, decodeURIComponent, ads)
```
