### ISSUE TITLE
canale.live: detection

### ISSUE THREAD

**Issue by RVC2020** [uBlockOrigin/uAssets#12705]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://canale.live/tv/1`

### Category

detection

### Describe the issue

Pop-up anti-adblocker.
The site probably updated its script, as there is a previous filter in uBO filter list. Issue 10770 [https://github.com/uBlockOrigin/uAssets/issues/10770](url)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80550
  cosmetic: 42871
  scriptlet: 16395
  html: 634
listset (total-discarded, last updated): 
  added: 
    ROU-1: 867-23, now
  default: 
    user-filters: 136-1, never
    ublock-filters: 31075-28, now
    ublock-badware: 4051-3, now
    ublock-privacy: 213-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1764-0, now
    easylist: 65716-611, now
    easyprivacy: 26776-591, now
    urlhaus-1: 7377-0, now
    plowe-0: 3687-3, now
    ublock-quick-fixes: 131-0, now
filterset (user): [array of 135 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 203 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 807 ms (selfie)
  maxAssetCacheWait: 578 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    canale.live: 4
    google-analytics.com: 2
    googletagmanager.com: 1
    placingstandardanthem.com: 2
    unseenreport.com: 1
    videocdn.click: 2
```
</details>

**Comment by the-poor-gamer-124** [comment]
Stop using free site if you do not like ads!!! Pay for iptv provider
