### ISSUE TITLE
https://bclikeqt.com/

### ISSUE THREAD

**Issue by pastormorris** [uBlockOrigin/uAssets#12708]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bclikeqt.com/`

### Describe the issue

website detect ad blocker

### Configuration

website detect ad blocker

**Comment by stephenhawk8054** [comment]
Can you click on [Report button (the one in the middle)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), click on `Troubleshooting Information` and copy paste your configuration from there?

**Comment by pastormorris** [comment]
https://fc-lc.com/9roeA9o   >>>>  https://bclikeqt.com/2022/04/automattic-women-josepha-haden-chomphosy/

**Comment by stephenhawk8054** [comment]
Move to [https://github.com/uBlockOrigin/uAssets/issues/12710](https://github.com/uBlockOrigin/uAssets/issues/12710)
