### ISSUE TITLE
[nsfw] dropgalaxy.com: detection

### ISSUE THREAD

**Issue by MyNameIsBorat** [uBlockOrigin/uAssets#12706]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dgdrive.xyz/9iuilfuxpg10`

### Category

detection

### Describe the issue

Drop galaxy detects that ublock origin is used and tells to disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 99
filterset (summary): 
  network: 88972
  cosmetic: 52495
  scriptlet: 20420
  html: 644
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 67908-32438, 6m
    ublock-annoyances: 4352-7, 6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31189-357, 11m
    ublock-badware: 4051-3, 11m
    ublock-privacy: 213-1, 11m
    ublock-abuse: 74-0, 11m
    ublock-unbreak: 1769-0, 11m
    adguard-mobile: 7557-172, 11m
    easylist: 65738-24423, 11m
    easyprivacy: 26776-599, 11m
    urlhaus-1: 7377-0, 11m
    plowe-0: 3687-3, 11m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13221 ms (selfie)
  maxAssetCacheWait: 9257 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
The file expired

**Comment by stephenhawk8054** [comment]
> The file expired

Direct link to `dropgalaxy.com` will always show expired now. It should be changed to `https://dgdrive.xyz/9iuilfuxpg10` to redirect to `dropgalaxy.com` again

**Comment by JobcenterTycoon** [comment]
Works fine on desktop but i can’t test on mobile at the moment.

**Comment by MyNameIsBorat** [comment]
it is being detected on firefox with ubo on desktop as well.

**Comment by shrimplark** [comment]
dropgalaxy does detect AdBlock on Firefox nightly

**Comment by mapx-** [comment]
Did you update the filters ?

**Comment by mapx-** [comment]
yeah, you have to clear up cookies, storage, close / reopen the tab

**Comment by shrimplark** [comment]
> yeah, you have to clear up cookies, storage, close / reopen the tab

I've done it, that's why it's strange...

**Comment by MyNameIsBorat** [comment]
Ublock is detected again. They seem to have changed their site.

**Comment by stephenhawk8054** [comment]
> Ublock is detected again. They seem to have changed their site.

Which link? I can still download from the above `dgdrive.xyz` normally.

**Comment by MyNameIsBorat** [comment]
Same link as above. Site owners are quite active in patching any bypass. Could a guide or tut be shared on how to bypass adblock detection.

**Comment by Procyon-b** [comment]
Still working for me. I'm able to download the file.

**Comment by stephenhawk8054** [comment]
> Same link as above. Site owners are quite active in patching any bypass. Could a guide or tut be shared on how to bypass adblock detection, or how you come up with the filters for bypassing

 Which region are you? I can download the file on both mobile and PC.
