### ISSUE TITLE
foxnews.com: breakage

### ISSUE THREAD

**Issue by PreachJohn** [uBlockOrigin/uAssets#12714]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.foxnews.com/`

### Category

breakage

### Describe the issue

From 'Features & Faces' on down, no Pictures load. when uBlock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 80026
  cosmetic: 42728
  scriptlet: 16377
  html: 633
listset (total-discarded, last updated): 
  default: 
    user-filters: 451-31, never
    ublock-filters: 31051-28, 3d.29m
    ublock-badware: 4036-3, 3d.28m
    ublock-privacy: 211-1, 1d.2h.9m
    ublock-abuse: 74-0, 1d.2h.8m
    ublock-unbreak: 1752-0, 3d.22m
    easylist: 65607-594, 3d.21m
    easyprivacy: 26772-578, 3d.22h.13m
    urlhaus-1: 7377-0, 6h.49m
    plowe-0: 3687-1, 7d.6h.42m
    ublock-quick-fixes: 140-0, 7h.1m
filterset (user): [array of 451 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4140 ms (selfie)
  maxAssetCacheWait: 453 ms
popupPanel: 
  blocked: 38
  blockedDetails: 
    foxnews.com: 6
    amazon-adsystem.com: 1
    bing.com: 1
    chartbeat.com: 2
    criteo.net: 1
    demdex.net: 2
    doubleclick.net: 1
    fncstatic.com: 2
    go-mpulse.net: 5
    google.com: 5
    googletagmanager.com: 2
    gstatic.com: 1
    h-cdn.com: 1
    imrworldwide.com: 1
    lytics.io: 1
    newrelic.com: 1
    opecloud.com: 1
    outbrain.com: 1
    rlcdn.com: 1
    segment.com: 1
    uri.sh: 1
```
</details>

**Comment by PreachJohn** [comment]
From 'Features & Faces' on down, no Pictures load. when uBlock is enabled.

**Comment by stephenhawk8054** [comment]
You mean this part?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/163110730-23f91fb5-7163-45a3-b685-137cb7463b3c.png)

</details>

The pictures load normally for me. Can you turn off your `My filters` list and force update the filter lists?

**Comment by PreachJohn** [comment]
Simply this. Cause and effect. When I Disable Ublock and reload FFox, everything after/below the top News Articles loads properly.
As soon as I Enable UBlock and reload FFox , same error.
I am not aware that I have Enabled any Filters Lists. I will have to poke around to find any if they exist.

**Comment by stephenhawk8054** [comment]
I see that you are having many custom filters:

```
user-filters: 451-31, never
```

Can you go to [My filters pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) to check what you have added yourself?

You can go to [Filter lists pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) and turn off `My filters` list, force update all filter lists and check again.

**Comment by PreachJohn** [comment]
Thank you much. Must have added those years ago and let it be and forgot as
there have been no issues that I couldn't solve somehow.
I Unchecked/Applied My filters and will leave it like that. I would think
that's a sound idea?
Firefox loads completely now.
Thanks very much again.
PreachJohn
