### ISSUE TITLE
ad-doge.com: breakage

### ISSUE THREAD

**Issue by Nisha888** [uBlockOrigin/uAssets#12712]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ad-doge.com/user/default.aspx`

### Category

breakage

### Describe the issue

Man kann nichts mehr anklicken, die Seite stoppt irgendwie ganz komisch

---

You can no longer click on anything, the page stops somehow quite strangely

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82159
  cosmetic: 45873
  scriptlet: 16438
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 46-27, never
    DEU-0: 5618-0, 5m
    easylist: 65762-57, 5m
    easyprivacy: 26778-132, 5m
    plowe-0: 3687-809, 5m
    ublock-abuse: 74-0, 5m
    ublock-badware: 4057-93, 5m
    ublock-filters: 30506-110, 5m
    ublock-privacy: 208-2, 5m
    ublock-quick-fixes: 143-0, 5m
    ublock-unbreak: 1752-43, 5m
    urlhaus-1: 7267-0, 5m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 56 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 276 ms
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    bmcdn3.com: 1
    cloudflareinsights.com: 1
    cointraffic.io: 1
    coinzillatag.com: 1
    cpx-research.com: 1
    googletagmanager.com: 1
    sentry-cdn.com: 1
    surfe.pro: 1
    vlitag.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check if adding this filter works for you?

```
@@||coinzillatag.com/lib/display.js$script,domain=ad-doge.com
```
