### ISSUE TITLE
[nsfw] app.peardeck.com: detection

### ISSUE THREAD

**Issue by whattodomyuy** [uBlockOrigin/uAssets#12719]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.peardeck.com/`

### Category

detection

### Describe the issue

nobody is ever my shoulder

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
(/details\)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80055
  cosmetic: 42371
  scriptlet: 16419
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65640-51, 2d.28m
    easyprivacy: 26776-121, 2d.27m
    plowe-0: 3684-808, 2d.26m
    ublock-abuse: 74-0, 2d.24m
    ublock-badware: 4032-90, 2d.22m
    ublock-filters: 30492-95, 2d.21m
    ublock-privacy: 206-2, 2d.20m
    ublock-quick-fixes: 133-0, 5m
    ublock-unbreak: 1744-42, 2d.18m
    urlhaus-1: 7426-0, 4m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8412 ms
  maxAssetCacheWait: 720 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    bugsnag.com: 1
    google-analytics.com: 1
```
</details>

**Comment by thegu5** [comment]
This is a troll issue
