### ISSUE TITLE
bclikeqt.com: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#12717]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bclikeqt.com/2022/04/the-search-for-intelligence-a-cto-perspective/`

### Category

detection

### Describe the issue

Yesterday this site did not detect ublock, now this site can detect ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 84215
  cosmetic: 46944
  scriptlet: 16418
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 22h.43m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 13-0, never
    IDN-0: 8996-0, 1d.18h.16m
    easylist: 65640-68, 1d.22h.19m
    easyprivacy: 26776-123, 1d.22h.18m
    plowe-0: 3684-808, 3d.19h.55m
    ublock-abuse: 74-0, 18h.38m
    ublock-badware: 4047-90, 18h.37m
    ublock-filters: 30494-128, 1d.18h.17m
    ublock-privacy: 206-2, 18h.39m
    ublock-unbreak: 1744-43, 1d.22h.20m
    urlhaus-1: 7319-0, 1d.1h.19m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 575 ms (selfie)
  maxAssetCacheWait: 360 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    denetsuk.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    jomtingi.net: 5
    mucinshasht.com: 1
    taghaugh.com: 2
    toglooman.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Duplicate: [https://github.com/uBlockOrigin/uAssets/issues/12710](https://github.com/uBlockOrigin/uAssets/issues/12710)

It's fixed already. Can you force update the filter lists?

**Comment by yohanes4dip** [comment]
Its work, thank you 😊👍

Pada tanggal Rab, 13 Apr 2022 16.42, stephenhawk8054 <
***@***.***> menulis:
