### ISSUE TITLE
gocomics.com: breakage

### ISSUE THREAD

**Issue by PaladinTitus** [uBlockOrigin/uAssets#12718]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gocomics.com/garfield`

### Category

breakage

### Describe the issue

the comic strip is getting blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82145
  cosmetic: 45748
  scriptlet: 16378
  html: 633
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31077-106, 2d.5h.9m
    ublock-badware: 4036-3, 2d.5h.8m
    ublock-privacy: 211-0, 2d.22h.20m
    ublock-abuse: 74-0, 2d.22h.19m
    ublock-unbreak: 1755-0, 2d.5h.12m
    easylist: 65640-524, 2d.5h.11m
    easyprivacy: 26775-602, 2d.5h.10m
    urlhaus-1: 7426-0, 40m
    plowe-0: 3687-2, 8d.21h.28m
    DEU-0: 5618-2, 39m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 229 ms (selfie)
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    gocomics.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed recently. Can you force update the filter lists?

**Comment by PaladinTitus** [comment]
Yes, thank you. It works again.
