### ISSUE TITLE
tenies-online.best: popups

### ISSUE THREAD

**Issue by Tabithar** [uBlockOrigin/uAssets#12720]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tenies-online.best/`

### Category

popups

### Describe the issue

every time i 'm going to watch a movie or serf into site popups show up if you can please fix it 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80559
  cosmetic: 42947
  scriptlet: 16401
  html: 635
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31098-29, 5h.32m
    ublock-badware: 4036-3, 5h.31m
    ublock-privacy: 211-0, 11d.17h.10m
    ublock-abuse: 72-0, 11d.17h.9m
    ublock-unbreak: 1764-0, 5h.30m
    easylist: 65764-607, 5h.29m
    easyprivacy: 26778-578, 5h.28m
    urlhaus-1: 7377-0, 22h.51m
    plowe-0: 3687-2, 10d.5h.27m
    GRC-0: 1002-1, 22h.53m
    ublock-quick-fixes: 130-0, 22h.52m
filterset (user): [empty]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 353 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 10
  no-popups: true
  blockedDetails: 
    addresseepaper.com: 1
    clenchedyouthmatching.com: 1
    dismantlepenantiterrorist.com: 1
    googletagmanager.com: 1
    inflectionquake.com: 3
    odourprop.com: 1
    venetrigni.com: 2
```
</details>

**Comment by eddmax** [comment]
@stephenhawk8054 well done  , that site does not load anymore when ublock is active !!  for lolz
