### ISSUE TITLE
TVGuia.es detects ad blockers again

### ISSUE THREAD

**Issue by davidmef** [uBlockOrigin/uAssets#12737]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.tvguia.es/programacion-tv/programacion-tv-ahora`

### Describe the issue

As in #8202, when I click on one of the program links, such as 

`https://www.tvguia.es/television/tv-serie-cine/6/1/4/14/1/20/52` 

`https://www.tvguia.es/themes/tv_desktop/images/adblockers.png` 
shows under the line of the link. Normally, info about the program would appear.

(I haven't really tried the lines under "I tried to reproduce the issue when...". I don't think they are related to the issue).

### uBlock Origin version

1.16.4.30

### Browser name and version

Pale Moon 30.0.1 (64-bits, Windows)

### Settings

The filters I use are:

Anuncios (1/3)
-- EasyList
Privacidad (1/2)
-- EasyPrivacy
Dominios de malware (1/2)
-- Online Malicious URL Blocklist
Elementos molestos (1/7)
-- uBlock filters – Annoyances
Multiusos (1/3)
-- Peter Lowe’s Ad and tracking server list
Regiones, idiomas (2/33)
-- spa, por: AdGuard Spanish/Portuguese
-- spa: EasyList Spanish
Personalizado (2/2)
-- Malware Domain List
-- Malware domains

My filters:
```
! 24/3/2018 1:03:41 http://www.expansion.com/mercados/cronica-bolsa/2018/03/23/5ab4a614e2704e17758b464f.html#
||www.expansion.com/ed/modal/avisos.html$subdocument

! 12/7/2018 0:22:18 https://www.fundaciontelefonica.com/arte_cultura/publicaciones-listado/pagina-item-publicaciones/itempubli/636/?utm_source=publicaciones&utm_medium=invitacion&utm_campaign=lecturas-verano07032018
www.fundaciontelefonica.com###pantalla-Cookies

! 2020-09-10 https://gramvio.com
||gramvio.com/wp-content/uploads/2020/09/Become-an-Instagram-Star-from-0.99.gif$image
```

My rules:
```
no-cosmetic-filtering: www.expansion.com true
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
```

Trusted sites:
```
behind-the-scene
chrome-extension-scheme
duckduckgo.com
loopconversation.about-scheme
opera-scheme
vivaldi-scheme
www.muynegociosyeconomia.es
```

```
    Anuncios (1/3)
    -- EasyList​
    Privacidad (1/3)
    -- EasyPrivacy​
    Dominios de malware (1/2)
    -- Online Malicious URL Blocklist​
    Elementos molestos (1/7)
    -- uBlock filters – Annoyances​​​​​3.683 utilizados de 3.685​​
    Multiusos (1/3)
    -- Peter Lowe’s Ad and tracking server list​
    Regiones, idiomas (2/34)
    -- spa, por: AdGuard Spanish/Portuguese​
    -- spa: EasyList Spanish​
    Personalizado (2/2)
    -- Malware Domain List​​
    -- Malware domains​​
```

### Notes

The page `https://www.tvguia.es/television/tv-serie-cine/6/1/4/14/2/30/52` includes 

```
<script>
function detectAdBlockerAsync(url, cb){
    var script = document.createElement('script');
    script.onerror = function(){
        script.onerror = null;
        document.body.removeChild(script);
        cb();
    }
    script.src = url;
    document.body.appendChild(script);
}
detectAdBlockerAsync('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', function(){
    document.getElementById('detail-program-content').innerHTML="<div class='details-television' style='width:100%; height:100%'><img src='/themes/tv_desktop/images/adblockers.png' 'width='360' border='0' height='250' style='margin: 20px 0px 0px 60px;'></div>";

});
</script>
```

**Comment by mapx-** [comment]
Add back the default lists & test again.

It seems you disabled the main list (`uBlock filters`)

**Comment by krystian3w** [comment]
Also try use Firefox/Chrome Portable to exclude that bug is for PaleMoon/Basilisk, Firefox Pre-Quantum/Pre-Proton 45-56.

**Comment by davidmef** [comment]
I had the default filters enabled. Sorry that I did not make it clear.

I tried with Firefox which uses AdBlock Plus with EasyList ,  EasyList Spanish+EasyList (EasyList Spanish+EasyList)  and Malware Domains [DEPRECATED - Please remove!]. It also fails.

Due to the problems with recent versions of Pale Moon, I have changed to version 29.4.6 (64-bit).
I have enabled and disabled filters and I noticed that if, in the list of filters I provided, I disable EasyList and Peter Lowe’s Ad and tracking server list, TVGuia works. If I enable any of them, it detects the ad blocking.

Strangely chrome://ublock0/content/asset-viewer.html?url=easylist shows
! Version: 202105181204

chrome://ublock0/content/asset-viewer.html?url=plowe-0 shows:
# last updated:   Mon, 17 May 2021 13:32:20 GMT

**Comment by mapx-** [comment]
fixed => update `uBlock filters - Legacy` list
