### ISSUE TITLE
oke.io [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1273]
URL(s) where the issue occurs

`http://oke.io/LUJE8`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Oh what to fill the Captcha

**Comment by nimasaj** [comment]
`@@||oke.io^$generichide`

**Comment by KiLL4FuNK** [comment]
ADS
![](https://i.imgur.com/z7he4WP.png)

**Comment by KiLL4FuNK** [comment]
now it shows nothing

**Comment by IThinkIAmCool** [comment]
ad
