### ISSUE TITLE
shrtfly.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1274]
URL(s) where the issue occurs

`http://shrtfly.net/TywZ`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
```
@@/js/ads.$domain=shrtfly.net
@@||shrtfly.net^$generichide
||shrtfly.net/links/popad$popup
```

**Comment by SMed79** [comment]
```
/popad|$popup
shrtfly.net##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)
```

**Comment by xDarkARG** [comment]
Anti-Adblock @mapx-

**Comment by xDarkARG** [comment]
Anti-Adblock @mapx-

**Comment by mapx-** [comment]
still working for me

**Comment by xDarkARG** [comment]
Anti-Adblock  It is a clone page @mapx- `http://shrtfly.com/XMiOP`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by theinstantmatrix** [comment]
another clone
`http://imageoptimizer.us/ar3nOXm`

**Comment by lain566** [comment]
Anti adblock
`http://allreports.site/aJrz`

**Comment by KiLL4FuNK** [comment]
ADS

`https://shrtfly.net/717j7`

**Comment by ghajini** [comment]
`shrtfly.net/XbFt`
Popup ads

**Comment by wrhadie** [comment]
Anti Adblock - `techtrendmakers.com`

**Comment by ItsProfessional** [comment]
@wrhadie 1. Provide source shortener link
2. Continue in #17361
