### ISSUE TITLE
oxfordlearnersdictionaries.com: breakage

### ISSUE THREAD

**Issue by tjdickinson** [uBlockOrigin/uAssets#12745]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.oxfordlearnersdictionaries.com/definition/english/advertise?q=advertise`

### Category

breakage

### Describe the issue

I am trying to view a dictionary entry for the word 'advertise', but the definition is blocked by uBO. When uBO is disabled, the definition appears correctly. I suppose it has something to do with the word itself: uBO sees the word 'advertise', thinks it is an advertisement, and blocks it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80116
  cosmetic: 42376
  scriptlet: 16430
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65698-51, 2d.15h.53m
    easyprivacy: 26776-121, 1d.23h.55m
    plowe-0: 3687-808, 11d.22h.34m
    ublock-abuse: 72-0, 10d.10h.13m
    ublock-badware: 4032-92, 1d.23h.52m
    ublock-filters: 30509-100, 1d.23h.54m
    ublock-privacy: 207-2, 9d.13h.57m
    ublock-quick-fixes: 133-0, 22h.49m
    ublock-unbreak: 1753-42, 1d.23h.53m
    urlhaus-1: 7426-0, 22h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2323 ms (selfie)
  maxAssetCacheWait: 317 ms
popupPanel: 
  blocked: 38
  blockedDetails: 
    oxfordlearnersdictionaries.com: 1
    3lift.com: 2
    4dex.io: 2
    adnxs.com: 2
    casalemedia.com: 2
    criteo.com: 3
    criteo.net: 3
    doubleclick.net: 2
    google-analytics.com: 1
    hotjar.com: 1
    indexww.com: 1
    openx.net: 2
    pbstck.com: 1
    pubmatic.com: 2
    quantserve.com: 2
    rubiconproject.com: 6
    teads.tv: 1
    yahoo.com: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
@ryanbr `oxfordlearnersdictionaries.com#@##advertise`
