### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by Anuj8448** [uBlockOrigin/uAssets#12747]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://music.youtube.com/watch?v=qo0sHr5KvVk&list=RDAMVMqo0sHr5KvVk`

### Category

ads

### Describe the issue

Shows really good amount of ads 
![Screenshot 2022-04-14 181506](https://user-images.githubusercontent.com/92680217/163393132-5d2fa5cc-36a2-4a9b-9cae-5954935c2013.png)
![Screenshot 2022-04-14 181506](https://user-images.githubusercontent.com/92680217/163393213-6544e7d1-81ca-450a-aeb4-ea09cb43c900.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80267
  cosmetic: 42402
  scriptlet: 16438
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65783-51, 22h.15m
    easyprivacy: 26779-121, 22h.14m
    plowe-0: 3684-808, 3d.20h.45m
    ublock-abuse: 72-0, 11d.3h.55m
    ublock-badware: 4052-92, 22h.13m
    ublock-filters: 30496-99, 22h.12m
    ublock-privacy: 206-2, 11d.3h.54m
    ublock-quick-fixes: 149-0, 4h.22m
    ublock-unbreak: 1754-42, 22h.11m
    urlhaus-1: 7502-0, 22h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 471 ms (selfie)
  maxAssetCacheWait: 202 ms
popupPanel: 
  blocked: 167
  blockedDetails: 
    youtube.com: 119
    doubleclick.net: 6
    google.com: 36
    googleadservices.com: 3
    googlesyndication.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
I get no ads

**Comment by krystian3w** [comment]
IMO still will be moved #7636 - title no limit to only `m.youtube.com` and `www.youtube.com`.

Also worth clear cookies, localStorage, DNS cache, system cache: https://github.com/easylist/easylist/wiki/Youtube-Issues
