### ISSUE TITLE
pandora.com: detection

### ISSUE THREAD

**Issue by dozer4133** [uBlockOrigin/uAssets#12754]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pandora.com/station/play/143446221292324152`

### Category

detection

### Describe the issue

Pandora won't play until uBlock is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 80169
  cosmetic: 42382
  scriptlet: 16436
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65738-51, 2d.55m
    easyprivacy: 26776-121, 1d.23h.53m
    plowe-0: 3687-808, 9d.19h.37m
    ublock-abuse: 72-0, 11d.22h.19m
    ublock-badware: 4032-92, 3d.21h.15m
    ublock-filters: 30502-99, 1d.19h.52m
    ublock-privacy: 206-2, 1d.17h.37m
    ublock-quick-fixes: 149-0, 16h.23m
    ublock-unbreak: 1750-42, 2d.56m
    urlhaus-1: 7446-0, 16h.21m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 334 ms
  maxAssetCacheWait: 141 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    pandora.com: 5
    adsafeprotected.com: 1
    adswizz.com: 1
    branch.io: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    krxd.net: 2
    p-cdn.us: 3
    scorecardresearch.com: 1
```
</details>

**Comment by Prism019** [comment]
Had the issue as well just now -- updating EasyList fixed the issue for me.

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?

**Comment by dozer4133** [comment]
Looks like that worked, thank you!
