### ISSUE TITLE
kimcartoon.li: breakage

### ISSUE THREAD

**Issue by Ziko577** [uBlockOrigin/uAssets#12758]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kimcartoon.li/`

### Category

breakage

### Describe the issue

On my brother's setup which uses nearly identical filters, the clickable sidebar that scrolls shows does not work. It works on mine when tested though. I don't know what may have caused this. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 108579
  cosmetic: 35
  scriptlet: 31099
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master/9Anime%20filter%20list: 149-34, 23h.22m
    https://gitlab.com/kowith337/PersonalFilterListCollection/raw/master/filterlist/imageboard/GelboLube-Legacy.txt: 158-47, 2m
    adguard-annoyance: 51839-44924, 2d.15h.47m
    adguard-generic: 63685-32135, 2d.15h.49m
    fanboy-annoyance: 67245-59733, 4d.18h.17m
  default: 
    user-filters: 70-13, never
    easylist: 65797-34578, 23h.23m
    easyprivacy: 26779-332, 23h.23m
    plowe-0: 3687-823, 10d.20h.53m
    ublock-abuse: 74-1, 2d.15h.45m
    ublock-badware: 4052-687, 23h.22m
    ublock-filters: 30506-10044, 23h.22m
    ublock-privacy: 206-13, 2d.15h.43m
    ublock-quick-fixes: 149-97, 23h.22m
    ublock-unbreak: 1757-288, 23h.22m
    urlhaus-1: 7502-0, 23h.22m
filterset (user): [array of 78 redacted]
trustedset: 
  added: [array of 41 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 8 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 7799 ms
  maxAssetCacheWait: 1509 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
> clickable sidebar that scrolls shows does not work

> It works on mine

if works for you he should reset uBO to default settings and don't add  other lists

**Comment by Ziko577** [comment]
I fixed the problem. It was a bunch of unnecessary filters that were causing the issue. I just erased them and voila, it went away. I found a bunch under there that were the culprit. You can close this out.

**Comment by krystian3w** [comment]
Nice will be report on gitlab `gitlab.com/Sorrow-San/9anime-adblock-filters/` and later to  https://gitlab.com/kowith337 if legacy have updates 1+ on month.
