### ISSUE TITLE
jn.pt Video not starting, breakage

### ISSUE THREAD

**Issue by tnmendes** [uBlockOrigin/uAssets#12750]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jn.pt/mundo/videos/videos-mostram-homem-negro-a-ser-morto-a-tiro-pela-policia-no-michigan-14771184.html`

### Category

breakage

### Describe the issue

Basically is just the video that is not loaded when ublock is active.
The website is using the JW Player and will load the first video ads just after the real video.

(if the video do not load ads, please use VPN to Portugal)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-14 at 16 10 18](https://user-images.githubusercontent.com/9822076/163419749-302321f4-4b77-4371-bc3f-9b4247792874.png)

Video was not load
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80113
  cosmetic: 42379
  scriptlet: 16432
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65698-51, 2d.21h.54m
    easyprivacy: 26776-121, 2d.5h.27m
    plowe-0: 3687-808, 6d.19h.24m
    ublock-abuse: 72-0, 6d.19h.22m
    ublock-badware: 4012-90, 2d.5h.26m
    ublock-filters: 30498-98, 2d.5h.25m
    ublock-privacy: 206-2, 2d.5h.24m
    ublock-quick-fixes: 147-0, 6h.37m
    ublock-unbreak: 1750-42, 2d.5h.23m
    urlhaus-1: 7446-0, 6h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 132 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    jn.pt: 1
    doubleclick.net: 1
    facebook.com: 2
    gemius.pl: 1
    globalmediagroup.pt: 1
    globalnoticias.pt: 2
    google.com: 9
    googletagmanager.com: 1
    ipify.org: 2
    mookie1.com: 1
    npttech.com: 1
    weborama.fr: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||googletagmanager.com/gtm.js$script,domain=jn.pt
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by tnmendes** [comment]
@Procyon-b Yeap the filter did work well
