### ISSUE TITLE
marktplaats.nl cookiewall

### ISSUE THREAD

**Issue by DrIT2016** [uBlockOrigin/uAssets#1275]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.marktplaats.nl`

### Describe the issue

Cookie warning shows up, can not block with cosmetic. All Annoyance filters are set. 
AdGuard works fine with it due to this rule:
marktplaats.nl#%#AG_onLoad(function() { var form = document.forms['track-accept']; if (form) { form.submit(); } });
But uBlock does not support AG_onLoad?

### Versions

- Browser/version: Firefox latest
- uBlock Origin version: latest

**Comment by uBlock-user** [comment]
Will need to create a cook named `CookieOptIn` and se it to `true`

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2229
