### ISSUE TITLE
acortame.descargatepelis.com: nuisance

### ISSUE THREAD

**Issue by pastormorris** [uBlockOrigin/uAssets#12765]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://acortame.descargatepelis.com/`

### Category

nuisance

### Describe the issue

`https://acortame.descargatepelis.com/o.php?l=VjFaV2IxVXdNVWhVYTJ4VlZrWndUbHBXVW5OTk1XUlhZVVU1VGxKdVFscFdSbWhYV1ZaSmVGZHFXbGhXUlhCSVdsWmFkbVZXU25GUmJVWllVbFZ3ZWxkWGRHdGpNbFp5WlVoU1ZXSnNjSEJXV0hCdVpHeHdTR0l6YUZSU2JYaDVXVE52ZDFCUlBUMD0=`
====>> `https://acortame.descargatepelis.com/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 287476
  cosmetic: 219
  scriptlet: 35661
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@master/filters/filters.txt: 30527-7718, 17h.42m
    https://filters.adavoid.org/ultimate-ad-filter.txt: 114079-66995, 17h.42m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25712-3584, 17h.42m
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt: 213267-19128, 17h.42m
    adguard-spyware: 25825-14625, 17h.42m
  default: 
    user-filters: 294-17, never
    easylist: 65803-65757, 17h.42m
    easyprivacy: 26782-15977, 17h.42m
    plowe-0: 3687-3116, 17h.42m
    spa-0: 3872-2122, 17h.42m
    spa-1: 4358-2907, 17h.42m
    ublock-abuse: 74-3, 17h.42m
    ublock-badware: 4052-1133, 17h.42m
    ublock-filters: 30521-30489, 17h.42m
    ublock-privacy: 209-67, 17h.42m
    ublock-quick-fixes: 148-94, 17h.42m
    ublock-unbreak: 1757-293, 17h.42m
    urlhaus-1: 7446-865, 17h.42m
filterset (user): [array of 294 redacted]
trustedset: 
  added: [array of 88 redacted]
switchRuleset: 
  added: [array of 35 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 894 ms (selfie)
  maxAssetCacheWait: 986 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    descargaloaca.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the issues in more details?

Btw, why did you add this link?

```
https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@master/filters/filters.txt
```

It's the same list as the main one: `uBlock filters`

**Comment by pastormorris** [comment]
wow i didn't realize the filter was already there. Thanks for letting me know :-(


https://www.descargatepelis.com/batman-2022-1080p-hdrip/
when he entered the download button, it redirects me to the following link: 
https://acortame.descargatepelis.com/o.php?l=VjFaV2IxVXdNVWhVYTJ4VlZrWndUbHBXVW5OTk1XUlhZVVU1VGxKdVFscFdSbWhYV1ZaSmVGZHFXbGhXUlhCSVdsWmFkbVZXU25GUmJVWllVbFZ3ZWxkWGRHdGpNbFp5WlVoU1ZXSnNjSEJXV0hCdVpHeHdTR0l6YUZWV2JYUXpWRlZSZDFCUlBUMD0=
On that page I have to click on an ad and wait 30 seconds.
After waiting the 30 seconds, I can only get to the download site:
https://pastes.descargatepelis.com/?v=LcM

**Comment by stephenhawk8054** [comment]
The timer can be boosted by `descargatepelis.com##+js(nano-sib, , *)`, but you have to keep the popup tab opens until countdown finishes. 

Anyone has more specific filters for `nano-sib`?

**Comment by mapx-** [comment]
@stephenhawk8054 if you can reproduce (& found the fix) just add it

**Comment by stephenhawk8054** [comment]
@mapx- Is there any way to log `nano-sib` and see which calls it is affecting?

---

@pastormorris I can only boost the timer, are they any annoyances you actually encountered?

**Comment by mapx-** [comment]
> any way to log nano-sib

not that I know of

**Comment by okiehsch** [comment]
You can use `nosiif` to log all interval calls and sift through them to find the ones to boost.

**Comment by stephenhawk8054** [comment]
> You can use `nosiif` to log all interval calls and sift through them to find the ones to boost.

Ah good trick. I'll try this one.

**Comment by stephenhawk8054** [comment]
Update: Looks like the countdown doesn't start until clicking on the ads. Last time I checked, I was whitelisting ads domains to test so that's why it worked after clicking on 1 ad. Need to investigate more.

**Comment by Yuki2718** [comment]
On my end it starts without clicking ad.
```
||blog.descargatepelis.com/wp/$popup,1p
descargatepelis.com##+js(nano-sib, contador)
```

**Comment by pastormorris** [comment]
Ready! 
Thanks to everyone!

acortame.descargatepelis.com,acortame.xyz#%#!function(){var f=function(a){for(var c=0;10>c;c++)try{a=atob(a);try{new URL(a);var d=!0}catch(e){d=!1}if(d)try{window.location=a}catch(e){}}catch(e){}};if(-1<window.location.href.indexOf("/o.php?l=")){var b=location.href.split("/o.php?l=");b&&b[1]&&f(b[1])}AG_onLoad(function(){"string"===typeof Lnk&&f(Lnk)})}();

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt

**Comment by Yuki2718** [comment]
Vanilla script rule doesn't work on uBO.

**Comment by mapx-** [comment]
nothing more we can do
