### ISSUE TITLE
gmx.at: ads

### ISSUE THREAD

**Issue by StanMaster3** [uBlockOrigin/uAssets#12768]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gmx.at/`

### Category

ads

### Describe the issue

Several ads appar on the page 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82556
  cosmetic: 45790
  scriptlet: 16392
  html: 633
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 4d.2h.36m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 31102-28, 1d.18h.41m
    ublock-badware: 4056-3, 1d.18h.40m
    ublock-privacy: 211-0, 4d.2h.33m
    ublock-abuse: 74-0, 4d.2h.32m
    ublock-unbreak: 1765-0, 1d.18h.39m
    easylist: 65783-225, 1d.18h.38m
    easyprivacy: 26779-151, 1d.18h.37m
    plowe-0: 3684-810, 4d.2h.34m
    DEU-0: 5618-30, 18h.38m
    urlhaus-1: 7702-0, 2h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 378 ms (selfie)
  maxAssetCacheWait: 413 ms
popupPanel: 
  blocked: 56
  blockedDetails: 
    adition.com: 1
    criteo.net: 2
    gmx.net: 5
    googletagservices.com: 17
    tifbs.net: 1
    ui-portal.de: 20
    uicdn.com: 4
    uimserv.net: 4
    united-infos.net: 2
```
</details>

**Comment by okiehsch** [comment]
Looks like self advertisement, they all link to different gmx prodcucts.

**Comment by stephenhawk8054** [comment]
> Looks like self advertisement, they all link to different gmx prodcucts.

Maybe Annoyances list is more suitable?

**Comment by okiehsch** [comment]
I don't recall us ever fixing self advertisement in annoyances, the ads are quite large in this case.
@mapx- what do you think?

**Comment by mapx-** [comment]
I would say in this case - big ads even if self-promotion - we could add them (as a new category of filters) in the annoyances list

**Comment by okiehsch** [comment]
OK,
````
gmx.*##[src^="https://dl.gmx.net/uim/connector/live/"]
````
works for me without any noticable breakage, but maybe there is a better fix.

**Comment by mapx-** [comment]
I tested your filter in chrome and does .. nothing

this 1 is working on my side:
`||dl.gmx.*/uim/connector/live/v2/nonfriendlyiframe.html$frame,1p`

**Comment by okiehsch** [comment]
> does .. nothing on my side

My bad, my filter only works for `gmx.net`
`gmx.*##[src^="https://dl.gmx.at/uim/connector/live/"]`
would work for `gmx.at`.
Your filter is better, it works for all different gmx versions.

**Comment by mapx-** [comment]
@StanMaster3 fix added in `uBlock filters – Annoyances` , just enable it
