### ISSUE TITLE
cryptofans.asia: popups

### ISSUE THREAD

**Issue by Defcon404** [uBlockOrigin/uAssets#12763]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cryptofans.asia/?utm_source=ac_dsk&utm_medium=2585611&utm_campaign=NP&utm_content=16499900020455217290246492816830252`

### Category

popups

### Describe the issue

opens a popup and sometimes another tab which shows ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2022-04-15 082914](https://user-images.githubusercontent.com/83384787/163509808-adcf9d2f-960a-4c6c-9b9c-c92d356358c1.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80087
  cosmetic: 42372
  scriptlet: 16384
  html: 633
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31077-28, 3d.19h.31m
    ublock-badware: 4036-3, 3d.19h.30m
    ublock-privacy: 211-0, 3d.19h.34m
    ublock-abuse: 74-0, 3d.19h.33m
    ublock-unbreak: 1755-0, 3d.19h.29m
    easylist: 65640-598, 3d.19h.28m
    easyprivacy: 26775-578, 3d.19h.27m
    urlhaus-1: 7446-0, 22h.51m
    plowe-0: 3684-2, 3d.19h.32m
    ublock-quick-fixes: 145-0, 22h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 236 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    a-ads.com: 5
    google-analytics.com: 1
    yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps in more details to reproduce it?
