### ISSUE TITLE
kingarthurbaking.com: breakage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#12764]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kingarthurbaking.com/recipes/cream-cheese-frosting-recipe`

### Category

breakage

### Describe the issue

Reviews section isn't visible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80565
  cosmetic: 42428
  scriptlet: 16459
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65893-51, 2m
    easyprivacy: 26790-121, 2m
    plowe-0: 3687-808, 2m
    ublock-abuse: 74-0, 2m
    ublock-badware: 4066-93, 2m
    ublock-filters: 30496-101, 2m
    ublock-privacy: 209-2, 2m
    ublock-quick-fixes: 151-0, 2m
    ublock-unbreak: 1757-42, 2m
    urlhaus-1: 7702-0, 2m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1662 ms
  maxAssetCacheWait: 561 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    kingarthurbaking.com: 2
    go-mpulse.net: 2
    newrelic.com: 2
```
</details>

**Comment by contextnerror** [comment]
Didn't realize you could edit the post by clicking the checkboxes. I did, in fact, tell the truth to all checkpoints.

**Comment by mapx-** [comment]
add

```
@@||kingarthurbaking.com/sites/default/files/google_tag/$script,1p
@@||googletagmanager.com/gtm.js$script,domain=kingarthurbaking.com
```

@ryanbr
