### ISSUE TITLE
whois.com: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#12760]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.whois.com/whois/ytimg.com`

### Category

ads

### Describe the issue

Shows ads...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-14 220109](https://user-images.githubusercontent.com/100969549/163466749-c2afdc2b-5c81-46e1-a22e-2eea501b737c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 241237
  cosmetic: 300624
  scriptlet: 38233
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6046-23, 2d.11h.38m
    https://winhelp2002.mvps.org/hosts.txt: 8730-67, 4d.23h.20m
    ALB-0: 268-0, 3h.12m
    BGR-0: 1116-13, 4d.23h.22m
    CHN-0: 28177-88, 1d.9h.34m
    CZE-0: 832-0, 3h.11m
    EST-0: 450-2, 3h.9m
    FIN-0: 1595-1, 1d.9h.33m
    FRA-0: 27471-78, 1d.9h.32m
    GRC-0: 1002-3, 1d.6h.37m
    HUN-0: 2158-14, 3h.8m
    IDN-0: 8996-28, 1d.9h.31m
    IRN-0: 1340-7, 1d.9h.30m
    ISL-0: 193-1, 4d.23h.21m
    ISR-0: 1617-2, 3h.7m
    ITA-0: 12903-101, 3h.6m
    JPN-1: 6505-16, 1d.9h.29m
    KOR-1: 8171-15, 1d.9h.9m
    LTU-0: 1189-7, 2d.11h.39m
    LVA-0: 395-2, 1d.9h.28m
    [29 lists not shown]: [too many]
  default: 
    user-filters: 80-1, never
    DEU-0: 5620-2, 3h.10m
    easylist: 65764-1942, 1d.9h.19m
    easyprivacy: 26778-10900, 1d.9h.18m
    plowe-0: 3687-1528, 9d.23h.51m
    ublock-abuse: 74-58, 1d.9h.15m
    ublock-badware: 4057-305, 1d.9h.13m
    ublock-filters: 30511-3803, 1d.9h.12m
    ublock-privacy: 206-76, 1d.9h.11m
    ublock-quick-fixes: 152-5, 10m
    ublock-unbreak: 1752-129, 1d.9h.10m
    urlhaus-1: 7619-1, 9m
filterset (user): [array of 145 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 14 redacted]
hostRuleset: 
  added: [array of 19 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1519 ms
  maxAssetCacheWait: 918 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflare.com: 2
```
</details>

**Comment by mapx-** [comment]
self-promotion

**Comment by JohnyP36** [comment]
> self-promotion

Self-promoting 'ads' are not ads in the real sense of the word and thus not blocked. 
Ads are advertisements of third-party domains/server.
