### ISSUE TITLE
Adblock Detected

### ISSUE THREAD

**Issue by 5u9r1** [uBlockOrigin/uAssets#12762]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sanoybonito.club`

### Describe the issue

Adblock detected

### Screenshot(s)

![image](https://user-images.githubusercontent.com/102351021/163505923-7ae37e01-58f6-4157-a04f-e5550f4c6d1d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 147051
  cosmetic: 168763
  scriptlet: 34929
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 51946-173, 3h.28m
    adguard-generic: 63748-743, 3h.27m
    adguard-mobile: 7566-55, 3h.26m
    adguard-social: 16822-854, 3h.25m
    adguard-spyware: 25829-737, 3h.23m
    adguard-spyware-url: 550-13, 2h.59m
    block-lan: 43-0, now
    curben-phishing: 13115-0, 2h.51m
    curben-pup: 274-0, 2h.50m
    dpollock-0: 10365-324, 5d.23h.50m
    fanboy-cookiemonster: 29191-2340, 3h.30m
    ublock-annoyances: 4326-205, 2h.56m
  default: 
    user-filters: 0-0, never
    IDN-0: 8997-0, 3h.29m
    easylist: 65867-1408, 2h.58m
    easyprivacy: 26786-10414, 2h.57m
    plowe-0: 3683-1329, 5d.23h.51m
    ublock-abuse: 74-0, 3h.32m
    ublock-badware: 4066-290, 2h.55m
    ublock-filters: 30486-3501, 2h.53m
    ublock-privacy: 209-39, 3h.31m
    ublock-quick-fixes: 152-5, 2h.48m
    ublock-unbreak: 1757-105, 2h.52m
    urlhaus-1: 7619-1, 2h.49m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 38059 ms
  maxAssetCacheWait: 4563 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like a link that is redirected. Can you give original site?
