### ISSUE TITLE
[nsfw] vexacion.com: privacy

### ISSUE THREAD

**Issue by dantemepe** [uBlockOrigin/uAssets#12761]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://vexacion.com/afu.php?zoneid=1320852&var=818286&ymid=-393458983333079255`

### Category

privacy

### Describe the issue

¡¡¡this page hacks me, jump messages with : ana have se#

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![imagen](https://user-images.githubusercontent.com/103700978/163492774-d9a53d0f-8ee8-4d71-823a-90b4540474c5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 83263
  cosmetic: 47020
  scriptlet: 16588
  html: 634
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31078-80, 2d.22h.2m
    ublock-badware: 4036-3, 3d.2h.10m
    ublock-privacy: 211-0, 2d.22h.4m
    ublock-abuse: 74-0, 2d.22h.3m
    ublock-unbreak: 1755-0, 3d.10h.17m
    easylist: 65673-679, 3d.10h.20m
    easyprivacy: 26776-594, 3d.10h.19m
    urlhaus-1: 7502-0, 1d.1h.44m
    plowe-0: 3687-2, 8d.7h.3m
    spa-0: 3872-1, 3h.36m
    spa-1: 4321-104, 3d.10h.18m
    ublock-quick-fixes: 147-0, 1d.1h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1148 ms (selfie)
  maxAssetCacheWait: 1012 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
The page redirects to `gearbest` site for me. Can you give original page that you encountered the issue?

**Comment by ghajini** [comment]
`/afu.php?zoneid=$document`
