### ISSUE TITLE
ourl.io [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1276]
URL(s) where the issue occurs

`https://ourl.io/qvlFS`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
`https://ourl.io/COgIL`
