### ISSUE TITLE
cpmlink.net [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1277]
URL(s) where the issue occurs

`http://cpmlink.net/go/Q8QuAA`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Oh what to fill the Captcha

**Comment by okiehsch** [comment]
Captcha works fine on my end.

**Comment by xDarkARG** [comment]
if the Captcha works well it was only the ADS  @okiehsch

**Comment by KiLL4FuNK** [comment]
Pop-up @mapx-

**Comment by dumbusernameidk** [comment]
@okiehsch

Anti-adblock.

**Comment by okiehsch** [comment]
I can't reproduce an anti-adblock message with a default setup.
You are probaby using your own filter list, if so 
https://github.com/dumbusernameidk/ublock-filters/blob/master/Filters.txt#L858
causes the anti-adblock message on your end 😉 
`cpmlink.net##+js(set-constant.js, blockAdBlock, true)`
should work.

I can reproduce a popup and will add a fix for that issue.

**Comment by dumbusernameidk** [comment]
Huh odd I've had that filter up for almost a month. And I've used cpmlink on a couple occasions and never had the anti-adblock. I checked out the source page and they were running bab. So probably recently added. Could also be dependent on Firefox or even mobile.

**Comment by okiehsch** [comment]
They are runninf blockadblock and I checked with Firefox and I can only reproduce if I allow the cloudflare-request.
I can't check with Firefox mobile, if you can reproduce the anti-adblock message with a blocked `cloudflare-request` I can add `cpmlink.net##+js(set-constant.js, blockAdBlock, true)`

**Comment by dumbusernameidk** [comment]
Now I don't even get any anti-adblock with/without my filters. faulty detector I suppose.

Guess I'll pull out that cloudflare line anyway.

**Comment by dumbusernameidk** [comment]
Also for whatever reason the whole fuckadblock script is whitelisted in adguard base filter. Still can't trigger again.

**Comment by KiLL4FuNK** [comment]
ADS

`https://cpmlink.net/sMKrAA#`

**Comment by JobcenterTycoon** [comment]
i get popups
