### ISSUE TITLE
fmovies.to: ads and popups

### ISSUE THREAD

**Issue by COUPGIRL** [uBlockOrigin/uAssets#12777]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/home`

### Category

ads

### Describe the issue

ads is very convincing a the head of page for me it is a mcafee "ad " I did click on it so god save me ;(
![image](https://user-images.githubusercontent.com/103784049/163631900-be06257e-87ae-448a-b33f-7e09ba8ded65.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/103784049/163631835-f97c022f-f4be-4a3f-8080-fced9120acc9.png)

![image](https://user-images.githubusercontent.com/103784049/163634470-5e2166ec-1ab7-4712-8ad4-d7f5f63d4908.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80539
  cosmetic: 42441
  scriptlet: 16466
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65921-51, now
    easyprivacy: 26792-121, now
    plowe-0: 3682-804, now
    ublock-abuse: 74-0, now
    ublock-badware: 4066-93, now
    ublock-filters: 30516-99, now
    ublock-privacy: 209-2, now
    ublock-quick-fixes: 167-3, now
    ublock-unbreak: 1760-42, now
    urlhaus-1: 7630-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 735 ms
  maxAssetCacheWait: 236 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    ashoupsu.com: 2
    denetsuk.com: 1
    jomtingi.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I don't get that "McAfee banner". Are you using any other extensions or suspicious softwares outside browser? Also, which region are you when browsing that site?

**Comment by mapx-** [comment]
Could be you installed some bundle software including `mcafee webadvisor` ?!

**Comment by ghajini** [comment]
Offtopic

`https://www.virustotal.com/gui/url/1098f59e21cc9032e4831a33bdb3fe784a3c75f0a4788fbc0165d7618999f400?nocache=1`

**Comment by mapx-** [comment]
`denetsuk.com: 1` => it means anti propeller filters are not applied

@COUPGIRL 
- uninstall mcafee webadvisor from your system
- scan your system for malware
- uninstall uBO, reinstall it, update all filter lists, don't use any other blocking extension, test again

**Comment by ghajini** [comment]
so this it doesn't work for you?
`fmovies.*##+js(acis, parseInt, break;case $.)`

**Comment by COUPGIRL** [comment]
@mapx how do i scan for malware?

**Comment by mapx-** [comment]
Let's do another test: just update all filter lists and test again see if still see that banner

**Comment by COUPGIRL** [comment]
@mapx I already did that and still see the banner.

**Comment by COUPGIRL** [comment]
@mapx I will be conducting the other steps you have mentioned.

**Comment by mapx-** [comment]
I added above how to scan online for malware

**Comment by COUPGIRL** [comment]
@mapx- I am about to run scan now for for the late response also is this scanner legit?

**Comment by mapx-** [comment]
after reinstalling uBO it's important to **update all filter lists**
