### ISSUE TITLE
practicum.yandex.com: detection

### ISSUE THREAD

**Issue by tutorflutterapp** [uBlockOrigin/uAssets#12770]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://practicum.yandex.com/`

### Category

detection

### Describe the issue

Try playing the video in the home page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/76772113/163569964-63832642-0eb9-4360-90a8-e40ee0035499.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 162369
  cosmetic: 195768
  scriptlet: 35031
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1d.5h.13m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 2d.20h.46m
    adguard-annoyance: 51895-169, 2d.36m
    adguard-generic: 63744-707, 2d.30m
    adguard-mobile: 7562-102, 2d.35m
    adguard-social: 16790-853, 2d.37m
    adguard-spyware: 25818-975, 2d.33m
    adguard-spyware-url: 549-13, 2d.34m
    block-lan: 43-0, 17d.3h.21m
    curben-phishing: 13115-0, 17h.8m
    curben-pup: 274-0, 19m
    dpollock-0: 10364-1471, 1d.5h.14m
    fanboy-annoyance: 66792-4034, 8d.17h.8m
    fanboy-cookiemonster: 29343-28048, 4h.7m
    fanboy-social: 23278-23261, 2d.38m
    fanboy-thirdparty_social: 68-21, 21m
    ublock-annoyances: 4324-214, 2d.32m
  default: 
    user-filters: 44-5, never
    easylist: 65782-1482, 2d.40m
    easyprivacy: 26772-10525, 6d.3h.45m
    plowe-0: 3685-1486, 3d.14h.29m
    ublock-abuse: 74-0, 1d.1h.12m
    ublock-badware: 4047-296, 1d.20h.29m
    ublock-filters: 30511-3486, 2d.39m
    ublock-privacy: 209-44, 1d.1h.11m
    ublock-quick-fixes: 149-5, 17h.7m
    ublock-unbreak: 1753-106, 2d.31m
    urlhaus-1: 7702-1, 20m
filterset (user): [array of 44 redacted]
trustedset: 
  added: [array of 36 redacted]
switchRuleset: 
  added: [array of 10 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 4382 ms (selfie)
  maxAssetCacheWait: 2508 ms
popupPanel: 
  blocked: 64
  blockedDetails: 
    getsitecontrol.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    rudderlabs.com: 1
    typeform.com: 1
    yandex.net: 4
    yandex.ru: 54
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce with your configurations. Which browser are you using?
