### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by unrancid** [uBlockOrigin/uAssets#12779]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Describe the issue

ads are not viewed, but the "space" they occupied is left behind.

 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![unknown](https://user-images.githubusercontent.com/20506633/163635764-b3b8748c-1b2c-4353-b23c-2ba992eba830.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80506
  cosmetic: 42458
  scriptlet: 16444
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-2, never
    easylist: 65921-51, 3h.7m
    easyprivacy: 26792-121, 3h.6m
    plowe-0: 3687-808, 10d.41m
    ublock-abuse: 72-0, 10d.39m
    ublock-badware: 4066-92, 3h.9m
    ublock-filters: 30503-100, 2d.1m
    ublock-privacy: 207-2, 10d.40m
    ublock-quick-fixes: 151-0, 3h.5m
    ublock-unbreak: 1756-42, 3h.8m
    urlhaus-1: 7619-0, 21h.55m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 585 ms (selfie)
  maxAssetCacheWait: 93 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    pinterest.com: 2
    cedexis.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/10803
