### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by angelov-1080** [uBlockOrigin/uAssets#12771]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://music.youtube.com/`

### Category

ads

### Describe the issue

Ads are still showing on Youtube Music

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80567
  cosmetic: 42416
  scriptlet: 16452
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1d.15h.9m
  default: 
    user-filters: 4-2, never
    easylist: 65867-51, 14h.57m
    easyprivacy: 26783-121, 14h.56m
    plowe-0: 3687-808, 8d.16h
    ublock-abuse: 74-0, 14h.55m
    ublock-badware: 4066-92, 14h.54m
    ublock-filters: 30486-100, 14h.53m
    ublock-privacy: 208-2, 14h.52m
    ublock-quick-fixes: 142-0, 14h.50m
    ublock-unbreak: 1757-42, 14h.51m
    urlhaus-1: 7619-0, 14h.49m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 101 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    youtube.com: 4
    doubleclick.net: 3
    google.com: 1
    googleadservices.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/12747
