### ISSUE TITLE
cults3d.com: breakage

### ISSUE THREAD

**Issue by SlantedJack** [uBlockOrigin/uAssets#12774]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cults3d.com/en/3d-model/game/megazord-power-sword`

### Category

breakage

### Describe the issue

Does not allow purchase button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 80403
  cosmetic: 42379
  scriptlet: 16424
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    easylist: 65698-51, 3d.10h.53m
    easyprivacy: 26776-121, 3d.10h.52m
    plowe-0: 3687-808, 11d.13h.1m
    ublock-abuse: 72-0, 11d.12h.53m
    ublock-badware: 4032-92, 3d.10h.51m
    ublock-filters: 30498-101, 3d.10h.55m
    ublock-privacy: 206-2, 11d.12h.54m
    ublock-quick-fixes: 151-0, 10h.42m
    ublock-unbreak: 1752-42, 3d.10h.54m
    urlhaus-1: 7702-0, 10h.41m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 335 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  blockedDetails: 
    cults3d.com: 1
    azureedge.net: 1
    confiant-integrations.global.ssl.fastly.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    outbrain.com: 1
    unrulyvideo.com: 1
```
</details>

**Comment by mapx-** [comment]
> Does not allow purchase button

I see no such button, screenshot ?
