### ISSUE TITLE
cadenadial.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#12772]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cadenadial.com/`

### Describe the issue

1. Go to: `https://www.cadenadial.com/` and all Ok
2. press this button in the site header 
![Capturaq](https://user-images.githubusercontent.com/33556647/163578467-561bf78a-b938-4410-8a5b-545f88339f32.PNG)

break images

### uBlock Origin version

1.42.4

### Browser name and version

Chrome - 99.0

### Settings

The same as the last post

### Notes

Works well with ubo **OFF**

**Comment by PIZZA90** [comment]
Go to: `https://cadenaser.com/` (different site) same family of websites of: `cadenadial.com` or `elpais.com`

and press any post, result:

https://i.imgur.com/y3c49vk.png

**Comment by stephenhawk8054** [comment]
> The same as the last post

Can you elaborate in more details?

**Comment by PIZZA90** [comment]
you cant reproduce? I can in firefox and chrome

```
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 83789
  cosmetic: 48265
  scriptlet: 19486
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    ublock-annoyances: 4326-7, 33m
  default: 
    user-filters: 0-0, never
    easylist: 65903-51, now
    easyprivacy: 26792-121, 33m
    plowe-0: 3682-804, 33m
    spa-0: 3872-34, 1m
    spa-1: 4358-168, 2m
    ublock-abuse: 74-0, 33m
    ublock-badware: 4066-93, 33m
    ublock-filters: 30508-151, 1m
    ublock-privacy: 209-2, 33m
    ublock-unbreak: 1756-43, 33m
    urlhaus-1: 7630-0, 33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 230 ms (selfie)
  maxAssetCacheWait: 225 ms
```

![Capturaqqw](https://user-images.githubusercontent.com/33556647/163581904-44483bfc-9406-4844-8f8d-f87cdbc26fa6.PNG)

**Comment by stephenhawk8054** [comment]
> you cant reproduce? I can in firefox and chrome
> 
> ```
> uBlock Origin: 1.42.4
> Chromium: 100
> filterset (summary): 
>   network: 83789
>   cosmetic: 48265
>   scriptlet: 19486
>   html: 0
> listset (total-discarded, last updated): 
>   removed: 
>     ublock-quick-fixes: null
>   added: 
>     ublock-annoyances: 4326-7, 33m
>   default: 
>     user-filters: 0-0, never
>     easylist: 65903-51, now
>     easyprivacy: 26792-121, 33m
>     plowe-0: 3682-804, 33m
>     spa-0: 3872-34, 1m
>     spa-1: 4358-168, 2m
>     ublock-abuse: 74-0, 33m
>     ublock-badware: 4066-93, 33m
>     ublock-filters: 30508-151, 1m
>     ublock-privacy: 209-2, 33m
>     ublock-unbreak: 1756-43, 33m
>     urlhaus-1: 7630-0, 33m
> filterset (user): [empty]
> modifiedUserSettings: [none]
> modifiedHiddenSettings: [none]
> supportStats: 
>   allReadyAfter: 230 ms (selfie)
>   maxAssetCacheWait: 225 ms
> ```
> 

I mean it's always better if you can provide your configurations in details at beginning so others wouldn't have to search back and can save a little time for testing.

**Comment by PIZZA90** [comment]
sure, sorry was a fail 😅

**Comment by stephenhawk8054** [comment]
I can't reproduce with `elpais.com` but can with `cadenadial.com` and `cadenaser.com`. Better use Chrome for more obvious result.

For `cadenaser.com`:

- Click on any posts
- Click on homepage icon at the top -> Blank page

```
@@||assets.adobedtm.com/extensions/*$script,domain=cadenaser.com
@@||assets.adobedtm.com/*-source.min$script,domain=cadenaser.com
```

For `cadenadial.com`, there are 2 breakages:

1. Click on homepage icon at the top after loading -> Images can't load

```
@@||cadenadial.com/wp-content/themes/nwp/src/Blocks/Advertising/js/publi.js$script,1p
@@||ak-ads-ns.prisasd.com/slot/cdial/slot.js$script,domain=cadenadial.com
@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=cadenadial.com
@@||c.amazon-adsystem.com/e/dtb/bid$xhr,domain=cadenadial.com
```

2. Click on any posts, then click on homepage icon again -> Images can't load

```
@@||ak-ads-ns.prisasd.com/prebid/prebid_noticias.js$script,domain=cadenadial.com
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=cadenadial.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl$script,domain=cadenadial.com
@@||securepubads.g.doubleclick.net/pagead/ppub_config$xhr,domain=cadenadial.com
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=cadenadial.com
```

No redirections work for me so far, and the number of exceptions is too much that I'm not sure if it's worth to add or not. Anyone has any ideas?

**Comment by okiehsch** [comment]
>  the number of exceptions is too much that I'm not sure if it's worth to add or not. 

Following your steps I get mostly blank pages, surely that is a severe enough breakage to add your suggested exceptions.

**Comment by PIZZA90** [comment]
`||www.cadenadial.com/wp-content/themes/nwp/src/Ajaxify/*$script,domain=www.cadenadial.com`

**Comment by PIZZA90** [comment]
the live radio not working in firefox? in chrome all ok for me

I mean this:
![Capturaqqq](https://user-images.githubusercontent.com/33556647/163632514-e7faa9b4-485d-4d4f-9343-1ae11dc0aa1e.PNG)

**Comment by stephenhawk8054** [comment]
@PIZZA90 Can you check if these filters work for you for both websites?

```
cadenadial.com##+js(aost, History, stackDepth:2)
cadenaser.com##+js(aost, React, Object)
```

Do they cause any breakages?

**Comment by PIZZA90** [comment]
**stephenhawk8054**

that filter works.. the images load.

other break in this site.. the podcasts not working.. the site trying load ads (no related with the filter)
`https://www.cadenadial.com/programas`
`https://www.cadenadial.com/podcast/perro-que-dices`

**Comment by PIZZA90** [comment]
need this: `@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=cadenadial.com`

😅😆

**Comment by stephenhawk8054** [comment]
> need this: `@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=cadenadial.com`
> 
> 😅😆

Yeah, confirm your filter works on both links above. I'll add it to `unbreak`.

**Comment by Yuki2718** [comment]
Why nobody pings @ryanbr ?

**Comment by stephenhawk8054** [comment]
> Why nobody pings @ryanbr ?

Oh I forgot, I was focusing on fixing the breakages.

**Comment by PIZZA90** [comment]
Anti adblock ( click in play button of the video )

`https://cadenaser.com/nacional/2022/05/12/el-chef-con-estrella-michelin-que-casi-muere-atragantado-cadena-ser/`

![qweas](https://user-images.githubusercontent.com/33556647/168170266-7205dffc-db3b-44c8-86e1-c3ac6dd9683c.PNG)

**Comment by stephenhawk8054** [comment]
> Anti adblock ( click in play button of the video )
> 
> `https://cadenaser.com/nacional/2022/05/12/el-chef-con-estrella-michelin-que-casi-muere-atragantado-cadena-ser/`

Actually my issue is not able to play audio/video after pressing play button, but I don't see any anti-adblock notice like above.

Does this filter work for you?

`@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=cadenaser.com`

**Comment by PIZZA90** [comment]
no works..

Maybe some script is applying that anti adblocker

![Capturaaa](https://user-images.githubusercontent.com/33556647/168198415-29c70a34-e53b-45d4-b208-eafe65ca9cbc.PNG)

**Comment by PIZZA90** [comment]
https://user-images.githubusercontent.com/33556647/168199062-d56be9c6-1ede-4f79-8d65-fb412b623ef6.mp4

**Comment by stephenhawk8054** [comment]
Ah I see. I thought you meant pressing the button in the article, not the button at the bottom.

**Comment by PIZZA90** [comment]
both buttons does the antiadblockers appears

**Comment by stephenhawk8054** [comment]
Ok, actually I have to refresh once more to trigger the anti-adblock. Open it in new session/incognito mode makes it just stuck there without any warnings.

**Comment by PIZZA90** [comment]
yes is weird.. every time that I refresh the page whit CTRL+F5 the anti adblock NO appears

but whit F5 only YES

(whitout CTRL)

**Comment by stephenhawk8054** [comment]
Can you check if these work for you?

```
@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=cadenaser.com
cadenaser.com##+js(set, Object.prototype.adblockerEnabled, false)
```

**Comment by PIZZA90** [comment]
Works perfect! :D

**Comment by stephenhawk8054** [comment]
I click next many times but cannot reproduce the audio ads (I guess the one with `Publicidad`?). Which region are you?

**Comment by Yuki2718** [comment]
addressed PH: https://github.com/AdguardTeam/AdguardFilters/commit/6a9e47c12470da3744ab03e4e340524651654d1d I wonder if you get those anti-adb with AG - I don't.

**Comment by Yuki2718** [comment]
Enabled TPF but the same, maybe geo-dependent.

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/e78c1c06e78180a3e37b667f4e7c900945b8bb61
https://github.com/AdguardTeam/AdguardFilters/commit/2ea3cd54a7b0c1ab4c0b4027bc3e4270a3ec47d3

**Comment by Yuki2718** [comment]
I can't reproduce.

**Comment by Yuki2718** [comment]
Does `||live.streamtheworld.com/ondemand/ars?type=preroll&$xhr,domain=cadenaser.com` work?

**Comment by Yuki2718** [comment]
@AdamWr What do you think about `cmp.prisa.com`? Related to cookie, ads, and tracking all.

**Comment by AdamWr** [comment]
>@AdamWr What do you think about cmp.prisa.com? Related to cookie, ads, and tracking all.

Seems to be related to cookie consent, so I guess that it could be added to Annoyances filter (if it doesn't break anything).

**Comment by Yuki2718** [comment]
But no cookie consent thx to `||privacy-center.org^$third-party`. @PIZZA90 Can you test if blocking this is safe?

**Comment by Yuki2718** [comment]
> you can test here

I guess `cmp.prisa.com` is used by many more sites.

Yes, `privacy-center.org` is blocked by AGA.
