### ISSUE TITLE
ylilauta.org: popups

### ISSUE THREAD

**Issue by Maikkelinos** [uBlockOrigin/uAssets#12780]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ylilauta.org/`

### Category

popups, alarm()

### Describe the issue

Lauta.js and adsload.js cause the annoyances.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 222162
  cosmetic: 291757
  scriptlet: 37918
  html: 740
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63774-6199, 2h.22m
    adguard-spyware: 25832-881, 2h.22m
    adguard-spyware-url: 551-4, 2h.22m
    curben-phishing: 13483-1, 2h.22m
    curben-pup: 270-0, 2h.22m
    adguard-annoyance: 51971-4691, 2h.22m
    adguard-social: 16825-1094, 2h.22m
    fanboy-thirdparty_social: 68-0, 2h.22m
    fanboy-annoyance: 68110-52856, 2h.22m
    fanboy-cookiemonster: 29343-157, 2h.22m
    fanboy-social: 23286-40, 2h.22m
    ublock-annoyances: 4337-12, 2h.22m
    ara-0: 2566-0, 2h.22m
    BGR-0: 1116-11, 2h.22m
    CHN-0: 28202-134, 2h.22m
    CZE-0: 833-0, 2h.22m
    DEU-0: 5625-3, 2h.22m
    EST-0: 451-1, 2h.22m
    FIN-0: 1604-1, 2h.22m
    FRA-0: 27468-602, 2h.22m
    [24 lists not shown]: [too many]
  default: 
    user-filters: 1-0, never
    ublock-filters: 31104-424, 2h.22m
    ublock-badware: 4070-3, 2h.22m
    ublock-privacy: 214-0, 2h.22m
    ublock-abuse: 74-0, 2h.22m
    ublock-unbreak: 1771-0, 2h.22m
    easylist: 65921-1119, 2h.22m
    easyprivacy: 26792-10634, 2h.22m
    urlhaus-1: 7630-0, 2h.22m
    plowe-0: 3682-3, 2h.22m
    ublock-quick-fixes: 165-0, 2h.22m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 304 ms (selfie)
  maxAssetCacheWait: 844 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
First, you shouldn't have enabled all the filter lists. Go back to enable only the default ones and others only when needed or recommended here.

I can't reproduce your problem even with all these lists enabled. But I see in your configuration that the popup panel shows 0 blocked for this page. And you have 3 trusted sites. When you click the popup, is the ["power" button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) blue or gray (disabled)?
