### ISSUE TITLE
techydino.net: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#12785]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techydino.net/detected.php?page=https://techydino.net/2020/09/14/top-3-logo-maker-apps-for-android/`

### Category

detection

### Describe the issue

this site detect ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 84630
  cosmetic: 46980
  scriptlet: 16438
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 14-0, never
    IDN-0: 8996-0, 3d.1h.7m
    easylist: 65764-68, 3d.1h.7m
    easyprivacy: 26778-123, 3d.1h.7m
    plowe-0: 3687-808, 3d.1h.7m
    ublock-abuse: 74-0, 3d.1h.7m
    ublock-badware: 4052-93, 3d.1h.7m
    ublock-filters: 30514-132, 3d.1h.7m
    ublock-privacy: 208-2, 3d.1h.7m
    ublock-unbreak: 1754-43, 3d.1h.7m
    urlhaus-1: 7630-0, 16h.12m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 524 ms (selfie)
  maxAssetCacheWait: 289 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    cdn4ads.com: 1
    cleverwebserver.com: 1
    d3g5ovfngjw9bw.cloudfront.net: 1
    katukaunamiss.com: 2
    netpub.media: 5
    surfe.pro: 2
    thisiswaldo.com: 2
```
</details>

**Comment by okiehsch** [comment]
How did you end up at that page?
