### ISSUE TITLE
crunchyroll.com [Video player]

### ISSUE THREAD

**Issue by SylveonBottle** [uBlockOrigin/uAssets#1279]
### Describe the issue

Before playing a video on Crunchyroll, an advertisement will appear. This was not a problem a week ago, as Crunchyroll has changed something in their webpage to display this new advertisement before the video loads. The video loads properly after the advertisement, and the page is not broken.

Other extensions installed include TamperMonkey and Stylish, both of which have been uninstalled completely during tests and do not affect this issue.

Switching tabs during the loading of the page will not load the advertisement, allowing you time to start the logger before the advertisement displays. 

Here is the provided logger, recording after the loading of the full page, but before the video player and during the advertisement: 
[uBlock₀ — Logger.zip](https://github.com/gorhill/uBlock/files/1627660/uBlock.Logger.zip)

### One or more specific URLs where the issue occurs

http://www.crunchyroll.com/overlord/episode-13-player-vs-non-player-character-736661

### Screenshot in which the issue can be seen

https://i.imgur.com/xjaylsq.png
10 second gif: https://i.imgur.com/z3kR2Bb.gifv

### Steps for anyone to reproduce the issue

1. Download, install, & open Google Chrome v63
2. Install uBlock Origin
3. Adjust settings of uBlock Origin as per "Your Settings" below, enable every filter list _except_ Experimental and all after Regions, languages
4. Open http://www.crunchyroll.com/overlord/episode-13-player-vs-non-player-character-736661
5. Observe as the first frame of the video is shown for a split second, without the player. This may be a background image used behind the player itself, as per the gif.
6. Observe as the player goes black with a grey bar on top, with the phrase "Advertisement: 0", then changes to "Advertisement:  ", as per the gif.
7. Observe as the bar on top disappears for a split second, before reshowing with "Advertisement: 30", as per the gif
8. Observe the advertisement that only started showing recently.

### Your settings

https://i.imgur.com/xM7YogM.png

- **OS/version:** Windows 10 Version 1709 (OS Build 16299. 192)
- **Browser/version:** Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- **uBlock Origin version:** uBlock Origin 1.14.22

##### Your filter lists

Everything except Experimental and other languages.

##### Your custom filters (if any)

`! http://www.crunchyroll.com/
www.crunchyroll.com##.premium
www.crunchyroll.com###ecom_deal_img_div
www.crunchyroll.com##.large-margin-bottom:nth-of-type(1)
www.crunchyroll.com###showmedia_about_info_details > div:nth-of-type(3)
||static.ak.crunchyroll.com/i/star*$image
www.crunchyroll.com##.clearfix.right
www.crunchyroll.com##.small-margin-bottom.container-shadow.cf.white-wrapper.showmedia-submenu
www.crunchyroll.com##.footer-categories-container > .footer-column:nth-of-type(3)
`

**Comment by uBlock-user** [comment]
They removed HTML 5 player and made it Flash only, can't test it.

**Comment by SylveonBottle** [comment]
@uBlock-user They've always used Flash player. HTML 5 player is limited to premium users only. uBlock origin has _always_ been able to block the ads.

**Comment by uBlock-user** [comment]
No, not always, I was able to watch episodes there without having Flash player installed and on HTML 5 player without having an account. They removed HTML 5 player for the guests apparently. So guests are stuck with Flash.

**Comment by nimasaj** [comment]
try `||fwmrm.net/ad/*`

**Comment by SylveonBottle** [comment]
In that case we may be talking about different websites, because I remember distinctly for the past 2 years not being able to watch Crunchyroll without enabling Flash. Maybe there's something to do with country-locking or something?

### Regardless, adding `||crunchyroll.com/*.mp4` successfully blocks the ad 10/10 times.

Though, I might add, when I tried adding this via the selection tool it was added as `||crunchyroll.com/*.mp4$media` which does not block.

**Comment by nimasaj** [comment]
I see in your logger that you have this rule `@@||v.fwmrm.net/ad/*&resp=vast2`, removing it might help blocking ads without adding any extra rule.

**Comment by SylveonBottle** [comment]
@nimasaj I can confirm that removing that rule successfully blocks the ads as well.

The rule was found in Adguard Mobile Filters list, I'll stop using that since I'm not even on fucking mobile. 

I guess I've gotten used to just enabling every filter on uBlock Origin, this mobile filter must be new since I'm pretty sure I'm not stupid enough to enable that considering the name.

I'll file a report with AdguardTeam about this, but I'll make sure to note that I'm not even on mobile in the first place and thus could be a bug of misuse.

**Comment by SylveonBottle** [comment]
This entire thing may as well be marked invalid, as it's due to a filterlist made by another team that shouldn't even be used on Mobile in the first place.

I can confirm that adding `||crunchyroll.com/*.mp4` _does_ block the ad, but the main issue is more than likely due to the Adguard Mobile List, which for some reason I had enabled. I didn't even know it existed. I'll be careful when enabling every single ad filter from now on, as it seems that mobile ad filters can cause unintended side effects on desktop filters.

**Comment by uBlock-user** [comment]
> In that case we may be talking about different websites

Nope, I checked again, it's the same one. I always used Chromium and Chromium doesn't come with Flash installed and I was able to watch the episode on 480p before they removed it and put back a 2 minute preview in 480p and then push the signup to gain subscribers, could be any other reason, but HTML 5 player was allowed before.

**Comment by SylveonBottle** [comment]
@uBlock-user Just to confirm what you're saying, I'm to continue using the mobile filter we the added `||crunchyroll.com/*.mp4`? Disabling mobile filter already resolves the problem, so it seems obvious that I may be at fault for using an ad filter list made for an entirely different platform.

**Comment by uBlock-user** [comment]
I meant keep` ||crunchyroll.com/*.mp4` and `||fwmrm.net/ad/*`

**Comment by SylveonBottle** [comment]
@uBlock-user `||fwmrm.net/ad/*` is found within the mobile list filter, which I have disabled. The ad no longer shows after disabling. There's a chance that adding redundant filters could cause unintended side effects.

**Comment by uBlock-user** [comment]
`fwmrm.net/ad/*` won't have any unintended side effects as it's only used for pulling ads, but it's your choice.

**Comment by lain566** [comment]
@okiehsch @mapx- Blocking this ads manifest 
`https://static.crunchyroll.com/config/cx-vilos-ads/558.json`

Fix this issue
https://www.reddit.com/r/uBlockOrigin/comments/b8r8ui/unable_to_pause_video_player_on_crunchyroll_while/


Test link:
`https://www.crunchyroll.com/kinos-journey-the-beautiful-world-the-animated-series/episode-12-fields-of-sheep-749579`

`https://www.crunchyroll.com/mob-psycho-100/episode-12-the-battle-for-social-rehabilitation-friendship-780931`

**Comment by okiehsch** [comment]
Thanks.

**Comment by uBlock-user** [comment]
fix for `https://www.reddit.com/r/uBlockOrigin/comments/ckgp74/crunchyroll_ads_getting_through_again/`

`crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)`
