### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by bfbcping0** [uBlockOrigin/uAssets#12791]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=easter+funny&hl=en&tbm=isch&sxsrf=APq-WBsJ9BhHXZSf8ajkrcWx42SS72GhKQ%3A1650119194165&source=hp&biw=1726&bih=1282&ei=GtJaYtOqBKiyggf-krXABA&iflsig=AHkkrS4AAAAAYlrgKpbJ5gQDMmt3miS8seAOJj5UwL1J&oq=&gs_lcp=CgNpbWcQARgAMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnMgoIIxDvAxDqAhAnUABYAGDqEGgBcAB4AIABAIgBAJIBAJgBAKoBC2d3cy13aXotaW1nsAEK&sclient=img`

### Category

ads

### Describe the issue

Going to images.google.com and searching for anything will include ads on the page. 
Right-clicking and selecting "Block Element" does not seem to do anything.
Element Picker and Element Zapper also do not launch.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 80539
  cosmetic: 42533
  scriptlet: 16446
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 93-3, never
    easylist: 65893-51, 1d.11h.57m
    easyprivacy: 26790-121, 1d.11h.56m
    plowe-0: 3687-808, 9d.12h.27m
    ublock-abuse: 74-0, 1d.11h.55m
    ublock-badware: 4066-92, 1d.11h.54m
    ublock-filters: 30500-100, 1d.11h.53m
    ublock-privacy: 209-2, 1d.11h.52m
    ublock-quick-fixes: 159-0, 11h.48m
    ublock-unbreak: 1757-42, 1d.11h.51m
    urlhaus-1: 7664-0, 11h.47m
filterset (user): [array of 93 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1090 ms (selfie)
  maxAssetCacheWait: 563 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 2
```
</details>

**Comment by mapx-** [comment]
screenshot (showing the ads) for the page you provided above ?

**Comment by bfbcping0** [comment]
https://mega.nz/file/WXZWjQIR#PjphML5vS3_VynFPwlnEsT3gBSrDS59H9vLuBFP5U7c

**Comment by gwarser** [comment]
Opera browser?

**Comment by bfbcping0** [comment]
Yes.

**Comment by gwarser** [comment]
Turn on access to search pages in Opera add-on manager settings.
