### ISSUE TITLE
cocomanga.com crashing Firefox

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#12797]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cocomanga.com/`

### Describe the issue

Recently (4-5 days), sometimes above site generates 2+GB of memory use, CPU max, cases Firefox to a hung and crashes.
Few minutes ago, The uBo browserAction badge showed **11k**

### uBlock Origin version

1.42.4

### Browser name and version

Firefox Nightly 101.0a1 (2022-04-16) (64-bit)

### Settings

default

**Comment by mapx-** [comment]
- Provide `Troubleshooting Information` (support tab)
- open the logger, test again, provide what's blocked in the logger

**Comment by erosman** [comment]
When it crashes Firefox, the only options is to force shut down Firefox. I couldn't eve take a screenshot.
It is not possible to use the logger at that time.
It issue doesn't happen all the time, but it often happens once in 10+ pages.
Normally, the number on the uBo badge is about **6**.
When Today, it went to **1K**, I had to close the tab before it crashed Firefox.

I will see if I can log something before it crashes.

**Comment by erosman** [comment]
Here is the report of **18K** and crash
### Screenshot
![ubo2](https://user-images.githubusercontent.com/6458876/163794501-6aa4f910-b5c0-45b9-b0c5-520a972fbfd1.jpg)
![ubo](https://user-images.githubusercontent.com/6458876/163794561-8e6c4733-73c5-4b77-aa4e-f84a74a2e50c.jpg)

### Log entry
```
+125
no-csp-reports: * true
--
www.cocomanga.com
3
csp_report
https://csp-reporting.cloudflare.com/cdn-cgi/script_monitor/report?m=3s7i8m1_C5mUtY.W504Op2IUwNFx1UMftw_g8.UNeBw-1650276012-0-AfMZ548ivIInNBDZwX5wzpj3XriyM3WJ-cnKOfLnRIV6Z9Q2wA2lpkXYOVhfLk9yx4Zdlyx1EcDAB9S1hIoeD0k
```

**Comment by stephenhawk8054** [comment]
Can you test the site with a new profile with just uBO installed (no other extensions) and force update the filter lists?

**Comment by erosman** [comment]
I will force update the list.
There is an infinite loop somewhere.

It doesn't happen all the time and I have spent fair amount of time to reproduce the issue.
It causes interruption to my work as the CPU/RAM max interferes with OS.

**Comment by stephenhawk8054** [comment]
It's better to test with a new profile, since it's easier to isolate which one causes the issue.

**Comment by erosman** [comment]
True... report, screenshots, & log has been provided. Debugging can be passed on to the experts.

**Comment by stephenhawk8054** [comment]
Actually your log looks pretty strange, at least I personnally can't see those `https://csp-reporting.cloudflare.com/cdn-cgi/script_monitor/report` connections when accessing to the site. I see that you are using other extensions as well, so I'm not sure if the reason could be from them or from your network or other softwares as well.

**Comment by erosman** [comment]
cloudflare uses different servers around the world. Therefore the location where the connection is made from might be relevant.

There are other reporting to cloudflare e.g.
```
HTTP/2 200 OK
date: Mon, 18 Apr 2022 11:17:17 GMT
set-cookie: cf_chl_seq_4e822e617660a13=_NWwbVkbejg9q2S;SameSite=Strict;HttpOnly
cf_chl_gen: Z6hd7KXEQBLknDXlw......CKJbl6bVVVxNylw==
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=exMC%2B7JUar4bTY2Jc9CHKyz.....RUhKR"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6fdcfe3ff8d61801-EWR
X-Firefox-Spdy: h2
```
![ubo3 20220418](https://user-images.githubusercontent.com/6458876/163801708-c9f8fee0-c3f0-4f7e-a6df-003da503981c.jpg)

**Comment by erosman** [comment]
It appears that it is a measure introduced by cocomanga.com within the last few days which results in a loop in uBo.

https://developers.cloudflare.com/page-shield/use-dashboard/configure-reporting-endpoint/

**Comment by stephenhawk8054** [comment]
Which region are you when accessing to the site?

**Comment by mapx-** [comment]
Did you disable `Block CSP reports` ?

**Comment by erosman** [comment]
> Did you disable `Block CSP reports` ?

Block is enabled. Isn't that the default?

![ubo4 20220418](https://user-images.githubusercontent.com/6458876/163813534-e6093188-ab17-4156-928a-718e01f78016.jpg)

**Comment by mapx-** [comment]
yes, just disable it and see if you still have that issue

**Comment by erosman** [comment]
I will try.

**Comment by krystian3w** [comment]
Also don't create filter to allow csp-raport (something like `@@||cloudflare.net$csp-report`), this still be added to my rules if works on other 99.9% of websites.

**Comment by erosman** [comment]
After disabling **Block CSP reports** I experienced the same crash once so far but the log was not open to observe the logged data.

Please note that I don't use that site often (I don't speak Chinese). I only check what has been released.

Note: I have not experienced such a crash on any other site.

**Comment by krystian3w** [comment]
Maybe bug is inside few (3-4) Daily releases if you downloaded update minimum once.

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
Most likely OP is using another extension which causes those CSP reports to be fired non-stop.

**Comment by stephenhawk8054** [comment]
@erosman Have you tested which I suggested yet?

> Have you tested it in new profile with only uBO installed?

**Comment by erosman** [comment]
> Have you tested which I suggested yet?

Yes, at first.
As mentioned earlier, the issue does not occur on every page loading and it is not feasible for me to use a clean profile for debugging for a long period of time as it prevents me from doing my work.

**Comment by stephenhawk8054** [comment]
> Yes, at first. As mentioned earlier, the issue does not occur on every page loading and it is not feasible for me to use a clean profile for debugging for a long period of time as it prevents me from doing my work.

I know it takes time but actually everyone here is also busy with our own work, and we are just here as volunteers. So if we cannot reproduce the issue, you are the only one who can do the investigation.

**Comment by erosman** [comment]
Just for Info ....

I only have 3 enabled extensions that have not been written by myself:
- uBlock Origin
- Don't track me Google _(doesn't apply to above site)_
- Extension source viewer _(doesn't apply to above site)_

Among the extensions written by myself, only 2 have `webRequest` + `blocking`
- FoxyTab has `types: ['main_frame']` which deals with Tab URL
- FireMonkey has 2 
  - one with `types: ['xmlhttprequest']` and then only generated from own extension e.g. 
    `if(!e.originUrl || !e.originUrl.startsWith(this.FMUrl)) { return; }`
  - One deals with specific URLS
```js
 urls: [
        'https://greasyfork.org/scripts/*.user.js',
        'https://greasyfork.org/scripts/*.user.css',
        'https://sleazyfork.org/scripts/*.user.js',
        'https://sleazyfork.org/scripts/*.user.css',
        'https://openuserjs.org/install/*.user.js',
        ]
```


They do not appear to be applicable to the issue.

**Comment by mapx-** [comment]
You could keep Block CSP reports enabled and add in "my rules"

`no-csp-reports: cocomanga.com false`

**Comment by erosman** [comment]
> You could keep `Block CSP reports` enabled and add in "my rules"
> 
> `no-csp-reports: cocomanga.com false`

OK.. done

**Comment by erosman** [comment]
Why was it closed?
Was the reason found?

As mentioned, the crash still happen even with `Block CSP reports` disabled.

**Comment by mapx-** [comment]
If you find a reliable way to reproduce the issue just let us know here

**Comment by mapx-** [comment]
Another thing: do you get such issue on some specific page or even just the home page ?

**Comment by mapx-** [comment]
see if helps adding

`||cocomanga.com/js/dynamicjs.js$script`

**Comment by erosman** [comment]
> If you find a reliable way to reproduce the issue just let us know here

As a developer, I do not expect the users to debug for me. I am grateful that they report issues/bugs and any additional information that would help me in finding the cause and fix it; but ultimately, the debugging is left to me, the developer of the extension.

There has been many issues that I have fixed (based on logic), even though I could not reproduce them myself, and it only applied to a handful of situations.

An example was an issue related to government filtering in a small country. There was no way for me to be able to reproduce that issue, short of travelling to that country and use their internet, OR find a proxy from that country.

OS specific issues are another example that the developer might not be able to reproduce unless tried on that OS. As we know, it is not possible for a developers to test on all possible OS. Even Firefox has many OS specific bugs that are still outstanding.

I have come across many such unreproducible examples.

**Comment by stephenhawk8054** [comment]
Actually, almost everyone here are users, not developers, and we are helping each other here to resolve the issues, especially when almost no one else can reproduce the problems.

**Comment by gorhill** [comment]
The body content of the CSP request in the Network pane of browser tools will show what triggered the the CSP violations. This will tell you what is causing this issue.

uBO is merely receiving the request and either blocking it or not. The crash is only because there are so many of these requests fired that Firefox is unable to garbage-collect memory as a result and eventually runs out of memory -- there is an open issue about this in bugzilla -- this is not an issue specific to uBO, any extension with a webRequest handler receiving the CSP request should also lead to a crash.

**Comment by gorhill** [comment]
> it is not feasible for me to use a clean profile for debugging for a long period of time

In that case, please do **not** check _"using a new, unmodified browser profile"_ or _"uBO is the only extension"_ if you did not actually reproduce the issue in a new profile or with uBO as the only extension. Bad information is worst than no information and waste precious time to all involved.

**Comment by gorhill** [comment]
So this site is full of obfuscated JS code and also prevents debugging the source code by adding `debugger` statement which is triggered as soon as the browser tools are opened. Likely the site itself is at the origin of those incessant CSP violations as a form of DoS to visitors using a blocker.

**Comment by erosman** [comment]
@gorhill  Thanks.
I have only experienced this issue recently and only on one site. My guess is that there is loop in the site's JS that causes the repeated report.

I would make a couple of suggestions:
- Auto-log sites (plus some data) that generate more than X notices (without the need to have the logger open)
- Cut-off processing on after X notices to prevent 100% CPU/RAM

Generating 18K notices is not practical.


> In that case, please do not check "using a new, unmodified browser profile" or "uBO is the only extension" if you did not actually reproduce the issue in a new profile or with uBO as the only extension. Bad information is worst than no information and waste precious time to all involved.

It was done at first before reporting and making changes to **Block CSP reports**.

After the initial test, subsequent tests with clean profile and uBo only, was not feasible.

[Bug 1504623](https://bugzilla.mozilla.org/show_bug.cgi?id=1504623) is 4 years old but the issue started 1 week ago.

While the CSP reports generated from the site, their processing by uBo was a factor in the crash as it should normally go through once and not be required to be repeated ... but of course that is not 100% for certain.

It could also be a bug in Nightly  but it is not feasible for me to test it on Nightly, Beta, Dev, Release, and on all OS.

**Comment by gorhill** [comment]
> Cut-off processing on after X notices to prevent 100% CPU/RAM

It does not matter, the bugzilla report I linked to made the case that even an empty webRequest listener leads to memory usage ballooning.

There is an experimental filter option in uBO which might be able to defuse what seems to be this deliberate DoS of users of blocker:

- Go to [_"Advanced settings"_](https://github.com/gorhill/uBlock/wiki/Advanced-settings)
- Set `filterOnHeaders` to `true`
- Add the following filter to _"My filters"_: `cocomanga.com##^responseheader(report-to)`

See if this helps. If so, it might be time to bring this filtering option out of experimental status.

**Comment by erosman** [comment]
@gorhill 

The issue is not happening any more but I think it might have been the result of *“The Page isn’t Redirecting Properly”*.

Due to some reason (*cocomanga server error, cloudflare server error, URL search parameter error, connection errors, etc*), the connection resulted in bad redirect.

Firefox normally, cuts off bad redirects after X attempts, however in this case, with `no-csp-reports: * true`, it got into a loop and never got cut off.

It is a guess though.

**Comment by erosman** [comment]
Spoke too soon ....

It happened again and I didnt have the logger open to see what is going on

Block CSP reports on
My Filters
```
cocomanga.com##^responseheader(report-to)
```
My Rules
```
no-csp-reports: * true
no-csp-reports: cocomanga.com false
no-large-media: behind-the-scene false
* facebook.net * block
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
```

**Comment by erosman** [comment]
Does `no-csp-reports: cocomanga.com false` work?

I am still getting crashes, now got it with 28K notices, with the same `https://csp-reporting.cloudflare.com/cdn-cgi/...`

Should the `false` be attached to `csp-reporting.cloudflare.com`?

**Comment by erosman** [comment]
Before testing:
- Reset uBo to default setting
- Disabled **Block CSP reports** 
- Added `cocomanga.com##^responseheader(report-to)` to My filters
- Added `no-csp-reports: cocomanga.com false` to My rules


The problem is still there but slightly less, as there is reduced processing.
- `csp_report` is sent and that causes an almost 100% CPU/RAM
- uBo no longer blocks so the processing is reduced by half
- uBo browserAction badge is not updated which also reduces the processing (imagine 28K async `browserAction.setBadgeText`) (it would be an idea to stop after X count anyway)

What I have noticed:
- .cocomanga has implemented a system to limit the number of requests. That is to say, if you open many pages rapidly (as I was testing to cause the issue), it blocks the request (presumably to combat site-crawling/spidering). It also sends the `csp_report`
- I tested after the crash and pages weren't loading any more (partial load only from browser cache)
- Tested via a proxy and pages loaded fine so there probably was an IP block
- All requests go through cloudflare cache and due to large number of images, there are many per page (e.g. `https://cdn.cocomanga.com.cdn.cloudflare.net/`)
- It ends up in loop sometimes

```
+3
www.cocomanga.com
3
csp_report
https://csp-reporting.cloudflare.com/cdn-cgi/script_monitor/report?m=LZuDwtq7_jaHhcZOZK7gB63qFM99RCYME1jH4UMPGCI-1650686609-0-AZBbtnYri6rOyRK-3yYWE9sv6owRVUonSPeEPUov3ENr7dd5e3Cnoi6f-FIkohx1KD38kE-MIF1hy2AqfPuDYdA
```

_PS. Off-topic: Why cant the logger window be maximised?_

**Comment by gorhill** [comment]
What [about](https://github.com/uBlockOrigin/uAssets/issues/12797#issuecomment-1103893211):

> The body content of the CSP request in the Network pane of browser tools will show what triggered the the CSP violations. This will tell you what is causing this issue.

**Comment by erosman** [comment]
I have tried 30-40 times by opening the _Dev Tools -> Network_  and then loading the page. It never passes the "_Checking your browser..._" stage and gets stuck there. The tab becomes unresponsive so I cant stop the tab or reload the tab. The only option is to close the tab.

**Comment by gorhill** [comment]
> "Checking your browser..."

This is a Cloudflare thing, so something on your side is causing CSP violations on that page, you need to find out what that is.

**Comment by erosman** [comment]
I understand that is cloudflare. 

I said that when the Dev Tool is open the tab doesn't forward. How can that be?
What effect does Dev Tool have?

Since you asked me to check `..in the Network pane of browser tools will show what triggered the the CSP violations...``, I was trying.

Right now I tested.

- New Tab
- Opened `https://www.cocomanga.com/show?orderBy=update`
- It opened
- Closed Tab
- New Tab
- F12 to open Dev Tools -> Network Tab
- Opened `https://www.cocomanga.com/show?orderBy=update`
- It doesn't open the page

**Comment by gorhill** [comment]
I am not sitting in front of your computer. If I was I would focus on findind out whether the issue is uBO-related, so I would narrow down as follow:

- New browser profile
- No extension
- Is the issue still there?
- If yes, not a uBO issue, investigate elsewhere
- If no, install uBO, default setting
- Is the issue still there?
- If yes, disable filter lists in step to identify if the issue is a specific filter list

**Comment by erosman** [comment]
I tried with a Clean profile and no extensions, and after many pages didn't experience the issue (although that is not a 100% proof).

> What [about](https://github.com/uBlockOrigin/uAssets/issues/12797#issuecomment-1103893211):
> 
> > The body content of the CSP request in the Network pane of browser tools will show what triggered the the CSP violations. This will tell you what is causing this issue.

As mentioned before, the site interferes with Dev Tools

- Clean Profile, no extensions
- New Tab
- F12 to open Dev Tools -> Network Tab
- Opened `https://www.cocomanga.com/`
- It doesn't open the page

![cocomanga-debugger](https://user-images.githubusercontent.com/6458876/165111671-0559bcf5-9125-45cc-9bba-3c859387f624.jpg)

![cocomanga-debugger2](https://user-images.githubusercontent.com/6458876/165111708-2118d09c-44c3-41fb-a417-9633ae11108a.jpg)

**Comment by gorhill** [comment]
> I tried with a Clean profile and no extensions, and after many pages didn't experience the issue (although that is not a 100% proof).

No words about installing only uBO as extension in that new profile?
