### ISSUE TITLE
Please add MacKeeper to the Badware list

### ISSUE THREAD

**Issue by j4ckhaal** [uBlockOrigin/uAssets#128]
Sorry, couldn't find any other place to post it.

www.mackeeper.com

Probably the most notorious crapware for macOS.

**Comment by zummuz** [comment]
> Sorry, couldn't find any other place to post it.

Probably https://www.malwaredomainlist.com/forums/index.php is the place, or http://www.malwaredomains.com/?page_id=13

**Comment by j4ckhaal** [comment]
I'm actually asking so that it's added to the uBlock list. That one only has seven or so links in it.

**Comment by gorhill** [comment]
Does not qualify as per <https://github.com/gorhill/uBlock/wiki/Badware-risks>. It needs 3rd-party, independent sources to support adding to Badware risks.

**Comment by j4ckhaal** [comment]
Sorry, I'm not sure I understand. I read that page and it seems to qualify. What do you mean by "it needs 3rd party independent sources?" I'm not sure I understand that.

**Comment by IDKwhattoputhere** [comment]
From the page:
> [...] and links giving further information as to why.

**Comment by j4ckhaal** [comment]
Oh, in that case:

http://www.cultofmac.com/170522/is-mackeeper-really-a-scam/

https://discussions.apple.com/docs/DOC-3036

http://m.imore.com/avoid-mackeeper

http://apple.stackexchange.com/questions/228451/is-mackeeper-scam-malware-please-give-me-advice

Last one seems to have accepted what looks like a sockpuppet answer. Not surprising given their marketing tactics. The top answer is much more believable: either it's useless, or you don't need it. 

I can find many, many more sources if needed.

**Comment by gorhill** [comment]
That site is not a download repo site, it's one specific vendor of one specific piece of software. I am not getting into this.
