### ISSUE TITLE
itsolutions-inc.com: breakage

### ISSUE THREAD

**Issue by scamdotnet** [uBlockOrigin/uAssets#12805]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.itsolutions-inc.com/news-and-training/article/how-to-create-fillable-forms-in-microsoft-word`

### Category

breakage

### Describe the issue

The website appears as a blank screen, even with the dark reader chrome extension turned off.  Turning off Ublock origin seems to let the site load fine, so I am not sure if this is an issue with the filters, or the website choosing to not display the page when ads are blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43154292/163695539-9e94857e-b67f-4564-964d-4b651b0c0b0f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80493
  cosmetic: 42441
  scriptlet: 16466
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65921-51, 1d.3h.50m
    easyprivacy: 26792-121, 1d.3h.49m
    plowe-0: 3682-804, 1d.3h.55m
    ublock-abuse: 74-0, 1d.3h.56m
    ublock-badware: 4066-93, 1d.3h.51m
    ublock-filters: 30516-99, 1d.3h.52m
    ublock-privacy: 209-2, 1d.3h.57m
    ublock-quick-fixes: 167-3, 17m
    ublock-unbreak: 1760-42, 1d.3h.53m
    urlhaus-1: 7584-0, 18m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1930 ms (selfie)
  maxAssetCacheWait: 1597 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    etrigue.com: 2
    facebook.net: 1
    fonts.net: 1
    googletagmanager.com: 2
    sharethis.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||fast.fonts.net/jsapi/core/mt.js$script,domain=itsolutions-inc.com`

@ryanbr EP issue
