### ISSUE TITLE
fextralife.com: nuisance

### ISSUE THREAD

**Issue by aPaperTree** [uBlockOrigin/uAssets#12801]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fextralife.com/`

### Category

nuisance

### Describe the issue

Please get rid of the twitch player. it is slow and annoying.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![unknosasdasdwn](https://user-images.githubusercontent.com/90895856/163690326-9f0f911c-af98-4e7c-8ce2-31f68eb088e1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80454
  cosmetic: 42350
  scriptlet: 16423
  html: 636
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31104-28, 18h.44m
    ublock-badware: 4070-3, 18h.43m
    ublock-privacy: 211-0, 5d.19h.51m
    ublock-abuse: 74-0, 5d.19h.50m
    ublock-unbreak: 1771-0, 18h.42m
    easylist: 65923-604, 18h.41m
    easyprivacy: 26811-578, 2h.18m
    urlhaus-1: 7584-0, 2h.17m
    plowe-0: 3687-2, 9d.1h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 146 ms (selfie)
  maxAssetCacheWait: 61 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    cloudflareinsights.com: 5
    d2v02itv0y9u9t.cloudfront.net: 1
    enthusiastgaming.net: 1
    fraudjs.io: 2
    gleam.io: 2
    google-analytics.com: 1
    googletagmanager.com: 2
    imrworldwide.com: 1
    sentry.io: 1
    twitch.tv: 1
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

`||embed.twitch.tv/embed/v1.js$script,domain=fextralife.com`
