### ISSUE TITLE
id.churchofjesuschrist.org: breakage

### ISSUE THREAD

**Issue by curtlytle** [uBlockOrigin/uAssets#12806]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://id.churchofjesuschrist.org/`

### Category

breakage

### Describe the issue

Screen goes blank when I try to enter my creds

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80509
  cosmetic: 42491
  scriptlet: 16440
  html: 638
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31118-31, now
    ublock-badware: 4081-3, now
    ublock-privacy: 216-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1772-0, now
    ublock-quick-fixes: 169-0, now
    easylist: 65984-601, now
    easyprivacy: 26818-577, now
    urlhaus-1: 7537-0, now
    plowe-0: 3682-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 956 ms (selfie)
  maxAssetCacheWait: 879 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adobedtm.com: 8
    trustarc.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||assets.adobedtm.com/*-source.min.js$script,domain=id.churchofjesuschrist.org`

EP issue @ryanbr
