### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Raiiodavida** [uBlockOrigin/uAssets#12804]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81835
  cosmetic: 45149
  scriptlet: 16662
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 65921-51, 22h.22m
    easyprivacy: 26800-121, 22h.23m
    plowe-0: 3687-808, 2d.59m
    spa-1: 4360-79, 22h.25m
    ublock-abuse: 74-0, 2d.57m
    ublock-badware: 4066-93, 22h.26m
    ublock-filters: 30516-134, 22h.27m
    ublock-privacy: 209-2, 2d.58m
    ublock-quick-fixes: 159-3, 2h.48m
    ublock-unbreak: 1760-43, 22h.24m
    urlhaus-1: 7584-0, 2h.49m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 378 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 45
  blockedDetails: 
    twitch.tv: 8
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    google.com: 1
    imrworldwide.com: 8
    scorecardresearch.com: 24
```
</details>

**Comment by mapx-** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
