### ISSUE TITLE
uesp.net

### ISSUE THREAD

**Issue by wodim** [uBlockOrigin/uAssets#1280]
### URL(s) where the issue occurs

http://en.uesp.net/wiki/Morrowind:Dagoth_Ur_(god)

### Describe the issue

Loads http://cdm.cursecdn.com/js/uesp/cdmfactorem_min.js?sec=home&misc=1515859936900 which outputs lots of stuff to the console

> CDMADS[900ms]: Inside runZones
> CDMADS[900ms]: Parsed AdZones: 01,02,07,end in section: home
> CDMADS[900ms]: Run Auction
> Loading failed for the <script> with source “http://gads.pubmatic.com/AdServer/AdCallAggregator?SAVersion=1000&js=1&kltstamp=2018-1-13%2016%3A12%3A18&timezone=0&screenResolution=1858x1138&ranreq=0.969485746966475&pageURL=http%3A%2F%2Fen.uesp.net%2Fwiki%2FMorrowind%3ADagoth_Ur_(god)&refurl=https%3A%2F%2Fwww.google.com%2F&inIframe=0&kadfloor=0.5&kadpageurl=http%3A%2F%2Fen.uesp.net%2Fwiki%2FMorrowind%3ADagoth_Ur_(god)&pubId=30296&pm_cb=pm_async_callback&a=1&lmk=1515859938100&adslots=%5B001%40728x90%2C002%40300x250%2C003%40300x250%2C004%40728x90%2C005%40728x90%2C006%40300x250%2C865721%40160x600%2C1082388%40160x600%5D”.
> Morrowind:Dagoth_Ur_(god):1
> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
> load.php:48:359
> CDMADS[2000ms]: ***********************
> CDMADS[2000ms]: Platforms responded: 3/14:::::::::::::
> CDMADS[2000ms]: Bid Slots on Page: 01,02,07
> CDMADS[2000ms]: High Bids by Slot: 0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
> CDMADS[2000ms]: uPartner: n,n,n,n,n,n,n,n
> CDMADS[2000ms]: uPrice: 0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
> CDMADS[2000ms]: RPM Goal: 0
> CDMADS[2000ms]: RPM Current: 0
> CDMADS[2000ms]: Time Out - Bids Accepted
> CDMADS[2000ms]: Bid landscape partners order: [[r:ca:pm:ox:a9:yh:am:sv:br:cm:pp:dm:an:cr]]
> Array [ "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0", "0:0:0:0:0:0:0:0:0:0:0:0:0:0" ]
> cdmfactorem_min.js:2:29799
> CDMADS[2100ms]: ABP OFF
> CDMADS[2100ms]: Deploy::Run GPT: none
> CDMADS[2100ms]: No SLB, No Skin Layout
> CDMADS[2100ms]: DFP Experiment version: n
> CDMADS[2100ms]: AdBlockPlus Detection: false
> CDMADS[2100ms]: Displaying Ads: 01,02,07,end

I think even if the ads end up not loading this js file should be blocked too.

**Comment by mapx-** [comment]
add
`||cdm.cursecdn.com/js/uesp/cdmfactorem_min.js`

and see if some funtionality is broken
