### ISSUE TITLE
the123movies.site: popups

### ISSUE THREAD

**Issue by kosakian** [uBlockOrigin/uAssets#12810]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://the123movies.site/movie/the-batman-16076`

### Category

popups

### Describe the issue

It redirects to other websites when interacting, or even by itself.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 80341
  cosmetic: 42404
  scriptlet: 16446
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65797-51, 3d.11h.20m
    easyprivacy: 26779-121, 3d.11h.19m
    plowe-0: 3687-808, 3d.11h.18m
    ublock-abuse: 74-0, 3d.11h.16m
    ublock-badware: 4052-93, 3d.10h.51m
    ublock-filters: 30503-99, 3d.10h.50m
    ublock-privacy: 208-2, 3d.10h.49m
    ublock-quick-fixes: 169-0, 1h.39m
    ublock-unbreak: 1756-42, 3d.10h.48m
    urlhaus-1: 7537-0, 1h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 698 ms (selfie)
  maxAssetCacheWait: 759 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    addthis.com: 1
    cloudflareinsights.com: 1
    d2kd9y1bp4zc6.cloudfront.net: 1
    denetsuk.com: 1
    eehuzaih.com: 1
    googletagmanager.com: 2
    jwpltx.com: 1
    prevotch.com: 1
    thaudray.com: 2
```
</details>

**Comment by mapx-** [comment]
Update all filter lists & test again

(how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by kosakian** [comment]
> Update all filter lists & test again
> 
> (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Thank you very much. It worked.
