### ISSUE TITLE
fmovies.to: ads

### ISSUE THREAD

**Issue by Archer201977** [uBlockOrigin/uAssets#12815]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/movies`

### Category

ads

### Describe the issue

Shows ads opening in new tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80366
  cosmetic: 42430
  scriptlet: 16464
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65903-51, 2d.3h.47m
    easyprivacy: 26792-121, 2d.3h.47m
    plowe-0: 3687-808, 2d.3h.47m
    ublock-abuse: 74-0, 2d.3h.47m
    ublock-badware: 4066-93, 2d.3h.47m
    ublock-filters: 30500-99, 2d.3h.47m
    ublock-privacy: 209-2, 2d.3h.47m
    ublock-quick-fixes: 167-0, 1h.22m
    ublock-unbreak: 1756-42, 2d.3h.47m
    urlhaus-1: 7478-0, 1h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 654 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    ashoupsu.com: 2
    denetsuk.com: 1
    jomtingi.net: 2
```
</details>

**Comment by Procyon-b** [comment]
Update the filter lists and try again.

**Comment by Archer201977** [comment]
Thanks Man! Appreciated!
