### ISSUE TITLE
fmovies.to: popups

### ISSUE THREAD

**Issue by BonjourYOU** [uBlockOrigin/uAssets#12819]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/tv-series`
Pop up when we click on the page after a while on all pages of the website

### Category

popups

### Describe the issue

Pop up when we click on the page after a while on all pages of the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
https://fmovies.to/tv-series
```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 80447
  cosmetic: 42447
  scriptlet: 16466
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    easylist: 65921-51, 1d.19h.47m
    easyprivacy: 26794-121, 1d.19h.46m
    plowe-0: 3687-808, 9d.23h.54m
    ublock-abuse: 72-0, 9d.23h.52m
    ublock-badware: 4066-92, 1d.19h.45m
    ublock-filters: 30516-99, 1d.19h.43m
    ublock-privacy: 207-2, 9d.23h.47m
    ublock-quick-fixes: 167-3, 6h.29m
    ublock-unbreak: 1760-42, 1d.19h.42m
    urlhaus-1: 7537-0, 6h.28m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3615 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    ashoupsu.com: 2
    denetsuk.com: 1
    rtmark.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Update the filter lists and try again
