### ISSUE TITLE
Last modified header (in file) not set

### ISSUE THREAD

**Issue by sjhgvr** [uBlockOrigin/uAssets#12814]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

-

### Describe the issue

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

! Title: uBlock filters
! Description: Filters optimized for uBlock, to be used along EasyList
! Expires: 4 days
! Last modified: **%timestamp%**

### Screenshot(s)

![image](https://user-images.githubusercontent.com/51121527/163719701-8a56f6cc-bd57-412b-8875-d15fc60411e1.png)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome 

### Settings

-

**Comment by Procyon-b** [comment]
For me it's already fixed.

**Comment by gwarser** [comment]
uAssets master branch holds only template. Lists are "published" in hg-pages branch every few hours, and then timestamp is updated https://raw.githubusercontent.com/uBlockOrigin/uAssets/gh-pages/filters/filters.txt

**Comment by sjhgvr** [comment]
Makes sense. Thanks.
