### ISSUE TITLE
gables.com: breakage

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#12826]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gables.com/communities/florida/palm-beach-gardens/gables-montecito/`

### Category

breakage

### Describe the issue

The layout/content is broken with the default filters enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80472
  cosmetic: 42477
  scriptlet: 16450
  html: 637
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31127-35, 3h.37m
    ublock-badware: 4081-3, 3h.37m
    ublock-privacy: 216-0, 3h.37m
    ublock-abuse: 74-0, 3h.37m
    ublock-unbreak: 1773-0, 3h.37m
    ublock-quick-fixes: 169-0, 3h.36m
    easylist: 65991-601, 3h.36m
    easyprivacy: 26822-577, 3h.36m
    urlhaus-1: 7478-0, 3h.36m
    plowe-0: 3682-3, 3h.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3093 ms (selfie)
  maxAssetCacheWait: 405 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    addthis.com: 1
    btstatic.com: 1
    facebook.net: 1
    fonts.net: 1
    google-analytics.com: 3
    googletagmanager.com: 1
    launchdarkly.com: 2
    pusher.com: 1
    rapidzebra.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Add

`@@||fast.fonts.net/jsapi/core/mt.js$script,domain=gables.com`

@ryanbr
