### ISSUE TITLE
[nsfw] myreadingmanga.info: breakage

### ISSUE THREAD

**Issue by geverin** [uBlockOrigin/uAssets#12823]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myreadingmanga.info/camohouse-yuji-itadori-death-room/3/`

### Category

breakage

### Describe the issue

blocks gifs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81124
  cosmetic: 43935
  scriptlet: 16498
  html: 0
listset (total-discarded, last updated): 
  added: 
    NLD-0: 2183-13, 1d.51m
  default: 
    user-filters: 0-0, never
    easylist: 65991-52, 53m
    easyprivacy: 26822-121, 52m
    plowe-0: 3687-808, 4d.4h.20m
    ublock-abuse: 74-0, 4d.4h.18m
    ublock-badware: 4077-93, 51m
    ublock-filters: 30555-143, 50m
    ublock-privacy: 208-2, 4d.4h.14m
    ublock-quick-fixes: 167-3, 48m
    ublock-unbreak: 1762-56, 49m
    urlhaus-1: 7478-0, 47m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1012 ms (selfie)
  maxAssetCacheWait: 651 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    myreadingmanga.info: 11
    aaxads.com: 1
    disqus.com: 4
    realsrv.com: 3
    rezync.com: 1
    wp.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
*.gif$domain=myreadingmanga.info,image,badfilter
```
