### ISSUE TITLE
target.com: breakage

### ISSUE THREAD

**Issue by hypodium** [uBlockOrigin/uAssets#12827]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.target.com/s?searchTerm=hat`

### Category

breakage

### Describe the issue

When searching (any term), result content (product images, names, prices, etc) no longer appears while uBlockOrigin is enabled. Instead there is only a gray grid where the content should appear. Please see screenshots. 

The content does appear if you refresh the page, but if you click on a product, a same issue occurs on the next page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1438" alt="Screen Shot 2022-04-16 at 12 08 26 PM" src="https://user-images.githubusercontent.com/103852852/163741540-49726679-18a2-4950-8d21-ac25c00bfe16.png">

![Uploading Screen Shot 2022-04-17 at 6.41.51 PM.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80484
  cosmetic: 42482
  scriptlet: 16451
  html: 637
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31128-35, now
    ublock-badware: 4081-3, now
    ublock-privacy: 216-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1773-0, now
    easylist: 65995-601, now
    easyprivacy: 26823-577, now
    urlhaus-1: 7490-0, now
    plowe-0: 3682-3, now
    ublock-quick-fixes: 169-0, now
filterset (user): [empty]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 75 ms (selfie)
  maxAssetCacheWait: 105 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    target.com: 20
    bing.com: 1
    doubleclick.net: 1
    indexww.com: 1
    kampyle.com: 1
    targetimg1.com: 2
    zeronaught.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can reproduce with these steps:

1. Open `https://www.target.com` in new Private Window/Incognito to ensure no caches and cookies were stored,
2. Type `hat` in the search bar and press enter -> Gray grid with no contents

It's blocked by `/fingerprintjs2.` in EasyPrivacy.

`@@||assets.targetimg1.com/webui/top-of-funnel/_next/static/chunks/fingerprintjs2.*.js$script,domain=target.com`

@ryanbr
