### ISSUE TITLE
yts.mx: nuisance

### ISSUE THREAD

**Issue by mert41994** [uBlockOrigin/uAssets#12821]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yts.mx/`

### Category

nuisance

### Describe the issue

The Menu Bar doesn't selectable while uBlock Origins works. If a pop-up doesn't show up, that bar won't be clickable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82202
  cosmetic: 48850
  scriptlet: 16797
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8741-92, 3d.2h.49m
    easylist: 65866-68, 3d.2h.50m
    easyprivacy: 26783-126, 3d.2h.52m
    plowe-0: 3684-809, 8d.8h.13m
    ublock-abuse: 73-0, 9d.4h.49m
    ublock-badware: 4052-92, 3d.2h.47m
    ublock-filters: 30476-109, 3d.2h.53m
    ublock-privacy: 207-2, 9d.4h.51m
    ublock-quick-fixes: 168-0, 1d.5h.45m
    ublock-unbreak: 1757-42, 3d.2h.48m
    urlhaus-1: 7537-0, 9h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 443 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    addthis.com: 1
    cloudflareinsights.com: 1
    glyphas.com: 1
    superfastcdn.com: 1
    youradexchange.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Works for me. Force-update your filter lists and try again.
