### ISSUE TITLE
sunporno.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1282]
URL(s) where the issue occurs

`https://www.sunporno.com/videos/1197393/tiny-teen-alex-grey-pounded-in-her-tight-pussy`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@mapx- ADS  click play `https://www.sunporno.com/`

**Comment by zaphodbeebblebrox** [comment]
@okiehsch video covered by adbox, can be removed with `sunporno.com###videoContainer_a`.

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by dumbusernameidk** [comment]
two cosmetic filters make it so you can't play the video `sunporno.com##.movie-atv` <- Adguard filter
`sunporno.com###videoContainer_a` uBo filter.

Better filter for the advert popup in the player would be `www.sunporno.com##.pop-container`.

**Comment by mapx-** [comment]
click the video => it will play as well

**Comment by dumbusernameidk** [comment]
strange i did do that before but it wasn't working seems to work now.
