### ISSUE TITLE
centrum.cz: breakage

### ISSUE THREAD

**Issue by 191881** [uBlockOrigin/uAssets#12830]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.centrum.cz/`

### Category

breakage

### Describe the issue

When the page is loaded for the first time in session it's broken - white spaces, page is completely without formating. To fix it you need to reload page (refresh)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81183
  cosmetic: 42770
  scriptlet: 16698
  html: 636
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 551-4, 2d.4h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31085-28, 2d.4h.40m
    ublock-badware: 4070-3, 2d.4h.39m
    ublock-privacy: 212-0, 9d.22h.45m
    ublock-abuse: 72-0, 9d.22h.44m
    ublock-unbreak: 1773-0, 2d.4h.38m
    easylist: 65932-590, 2d.4h.36m
    easyprivacy: 26803-595, 2d.4h.35m
    urlhaus-1: 7490-0, 1h.33m
    plowe-0: 3682-3, 1d.16h.22m
    CZE-0: 833-0, 1h.34m
    ublock-quick-fixes: 169-3, 1h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 205 ms (selfie)
  maxAssetCacheWait: 90 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    centrum.cz: 3
    caroda.io: 1
    cpex.cz: 2
    gemius.pl: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    mrezadosa.com: 1
    r2b2.cz: 1
    rubiconproject.com: 1
    sentry.io: 1
    xsd.cz: 1
```
</details>

**Comment by 191881** [comment]
Issue:
![obrazek](https://user-images.githubusercontent.com/73115068/163811369-62cca79d-e43a-477f-a550-96759764ccfa.png)
Normal (after refreshing):
![obrazek](https://user-images.githubusercontent.com/73115068/163811458-47b6db3a-d858-4ede-8d26-70b5990317d7.png)

**Comment by JobcenterTycoon** [comment]
I can’t reproduce too
