### ISSUE TITLE
hotgirlclub.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1283]
URL(s) where the issue occurs

`http://www.hotgirlclub.com/videos/8049/one-day-busty-milf-alexis-fawx-comes-to-a-bar-and-gets-her-big-tits-worship/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by kulfoon** [comment]
Ads gain, on main page and subpages: `http://www.hotgirlclub.com/videos/20739/alice-judge-fucking-season-in-the-backcountry/`

**Comment by kulfoon** [comment]
Still some left, on the subpage from the above comment, at the bottom, clicking these sponsored ads (try clicking even multiple times) most of the times redirects to some third-party pages which some of them are even malware.
