### ISSUE TITLE
192.168.0.31: detection

### ISSUE THREAD

**Issue by cvorvairbob** [uBlockOrigin/uAssets#12832]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://192.168.0.31:49131/`

### Category

detection

### Describe the issue

when i open my camera app i get a popup type that wants me to download a app to run the camera. i have the program so i do not need to be reminded to download that again. i want to block that element. i had ublock installed and it was doing a good job but because ublock took some of the parts i wanted i removed ublock to start over and now it will not even try to block those elements. i get a circule with the line thru it. i can send you a screenshot of the issue. this happens in the foscam app for just a few of the cameras that i try to use. the other cameras all seem to work good and i can block the very same element in those cameras.
thanks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![foscam -2](https://user-images.githubusercontent.com/29764483/163822530-c5356e81-eb38-42e2-a1eb-72baf4d4a10a.jpg)
![foscam-3](https://user-images.githubusercontent.com/29764483/163822574-ae189a9c-9223-41f3-9b4b-2c64e1add21a.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81685
  cosmetic: 42487
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-2, never
    easylist: 66009-51, 3m
    easyprivacy: 26830-121, 2m
    plowe-0: 3682-804, 1m
    ublock-abuse: 72-0, never
    ublock-badware: 3989-90, never
    ublock-filters: 30477-114, never
    ublock-privacy: 205-2, never
    ublock-quick-fixes: 139-15, never
    ublock-unbreak: 1742-41, never
    urlhaus-1: 8896-0, never
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 633 ms
  maxAssetCacheWait: 284 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    192.168.0.31: 1
```
</details>

**Comment by Procyon-b** [comment]
In the second screenshot, select the first filter in "cosmetic filters" or the last one.
or try these filters directly:
```
192.168.0.31###upgradeToolText

! or

192.168.0.31###searchToolUpdatePage
```

**Comment by cvorvairbob** [comment]
thanks now sure how to do that i deleted the app for now. when i did a search for ublock i got like 5 of them so then i did a search for ublock origin and only one came up so i will install that one and see if it works. if not i will come back here and ask for help thanks
  

    On Monday, April 18, 2022, 10:58:59 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


In the second screenshot, select the first filter in "cosmetic filters" or the last one.
or try these filters directly:
192.168.0.31###upgradeToolText

! or

192.168.0.31###searchToolUpdatePage

**Comment by cvorvairbob** [comment]
ok did not work so you telling me to look for one of those terms and delet it? i did right click and did a side panel and deleted some things and they did not work. and i can't seem to fine a save button to save the deleted items.

  

    On Monday, April 18, 2022, 10:58:59 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


In the second screenshot, select the first filter in "cosmetic filters" or the last one.
or try these filters directly:
192.168.0.31###upgradeToolText

! or

192.168.0.31###searchToolUpdatePage

**Comment by Procyon-b** [comment]
In ublock origin 's dashboard, you can paste one of the filter in the tab "My filters", then click "Apply changes". Reload the page and see if it's better. Try the other filter if the first one is not the solution. You can comment (disable) a filter by adding a ! in front. Or hit "tab" when the cursor is on that line

**Comment by cvorvairbob** [comment]
ok so where is the dashboard? if i click on the ublock icon and the dropdown show what icon do i pick for the dashboard? when i have the camera trying to open and that popup it there if i right click and pick the bottom time i get a side bad  so if i need that to be open where is the dashboard in that 
 so is it one of these  

    On Monday, April 18, 2022, 11:08:01 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


In ublock origin 's dashboard, you can paste one of the filter in the tab "My filters", then click "Apply changes". Reload the page and see if it's better. Try the other filter if the first one is not the solution. You can comment (disable) a filter by adding a ! in front. Or hit "tab" when the cursor is on that line

**Comment by Procyon-b** [comment]
Click ublock's icon, in the popup click the "gears" icon. It will open the dashboard.

**Comment by cvorvairbob** [comment]
ok mark i think i found it. it would not let me edit that page so i had to go into the email and do a compose an email and change the 31 to 21 for the camera named 21 and i added that to that list inserted here and it looks like that popup may be gone. i will try it for a few days and see if it holds that. the one thing that i would like is the background but it works for now so i will leave well enough alone.
  

    On Monday, April 18, 2022, 11:08:01 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


In ublock origin 's dashboard, you can paste one of the filter in the tab "My filters", then click "Apply changes". Reload the page and see if it's better. Try the other filter if the first one is not the solution. You can comment (disable) a filter by adding a ! in front. Or hit "tab" when the cursor is on that line

**Comment by cvorvairbob** [comment]
ok i think i have it for now thanks
  

    On Monday, April 18, 2022, 11:32:12 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


Click ublock's icon, in the popup click the "gears" icon. It will open the dashboard.

**Comment by mapx-** [comment]
> detection

no detection, right ?

**Comment by cvorvairbob** [comment]
not sure what you mean?  but i did get help figuring this out and now that part is working. it must be that foscam when they changed their firmware and required a new search tool that  the new search tool is evading detection enough as to not allow that popup to be taken down. but someone from the ublock site helped me get it figured out thanks
  

    On Tuesday, April 19, 2022, 01:34:04 AM EDT, mapx- ***@***.***> wrote:  
 
 



detection


no detection, right ?

**Comment by cvorvairbob** [comment]
it did it before. and someone from ublock helped me get rid of it. yesterday i had to enter these lines in the my filters rulesand the popup went away. now i call it a popup but you may call it something else here is what it looked like 

192.168.0.21###searchToolUpdatePage
192.168.0.31###searchToolUpdatePage
192.168.0.17###searchToolUpdatePage
192.168.0.18###searchToolUpdatePage 

this is what i had to see
 so by using those lines in the my filters that top one went away. ublock used to take that one away when i right-clicked and then selected pick and then create. but this new popup evaded that procedure so one of you helped me yesterday with that line and said to put it in my filters. i had to change the 21 to 31 to 17 and then to18 and it worked for all the cameras.
thanks bob p


    On Tuesday, April 19, 2022, 07:56:12 AM EDT, stephenhawk8054 ***@***.***> wrote:  
 
 


I think this issue is about hiding the popup. There's no information of detecting ublock here in the popup's words.

**Comment by cvorvairbob** [comment]
ok mark i went into the filters and deleted the 2 lines that were there that i did not put there and applied them and the boxes came back i removed the lines that had image at the end of the line.

 
 

    On Monday, April 18, 2022, 11:32:12 AM EDT, Marc Boucher ***@***.***> wrote:  
 
 


Click ublock's icon, in the popup click the "gears" icon. It will open the dashboard.
