### ISSUE TITLE
il.investing.com: detection

### ISSUE THREAD

**Issue by trulyx** [uBlockOrigin/uAssets#12831]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://il.investing.com/indices/nasdaq-composite`

### Category

detection

### Describe the issue

Website detects an ad blocker and demands whitelisting or a paid subscription.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Clipboard01](https://user-images.githubusercontent.com/48521027/163814095-c8d16c7c-5e37-46e9-a4aa-e9a472f39044.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81157
  cosmetic: 43340
  scriptlet: 16502
  html: 646
listset (total-discarded, last updated): 
  added: 
    ISR-0: 1622-0, 4h.30m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31118-28, 1d.8h.31m
    ublock-badware: 4081-3, 1d.8h.30m
    ublock-privacy: 214-0, 4d.8h.37m
    ublock-abuse: 74-0, 4d.8h.36m
    ublock-unbreak: 1772-0, 1d.8h.29m
    easylist: 65984-604, 1d.8h.28m
    easyprivacy: 26819-580, 1d.8h.27m
    plowe-0: 3684-2, 7d.12h.25m
    urlhaus-1: 7490-0, 4h.29m
    ublock-quick-fixes: 167-3, 4h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 446 ms (selfie)
  maxAssetCacheWait: 227 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    investing.com: 1
    cloudflareinsights.com: 2
    doubleclick.net: 1
    facebook.net: 1
    googletagmanager.com: 2
    hotjar.com: 1
    primis.tech: 1
```
</details>

**Comment by Procyon-b** [comment]
I don't see the popup.
Force-update the filter lists and try again.

**Comment by trulyx** [comment]
> I don't see the popup. Force-update the filter lists and try again.

Already did, I'm getting the same result on two different PCs.

**Comment by mapx-** [comment]
Are you using some other blocking addon / software ?

**Comment by trulyx** [comment]
Only uBlock Origin
Win 10, Firefox

**Comment by mapx-** [comment]
It could be some antivirus with web shields enabled. HOSTS file, some VPN, router with blocking capabilities etc

**Comment by Procyon-b** [comment]
Someone has reported the same problem on reddit, and I was able to see it to (can't reproduce anymore).

Try this filter:
```
investing.com##div[class*="adBlock-popup"], div[class*="overlay_overlay_"]
```

**Comment by avotoko** [comment]
I reproduced it several times on my end (firefox nightly 101.0a1), and it stopped reproducing as I tested it, deleting cookies and site data and turning off Enhanced Tracking Protection.

I will report back how it reproduced on my end.
The following code in the `checkAdBlocker` function detected an adblocker. The `checkAdBlocker` function is located in `https://i-invdn-com.investing.com/x/prod/67729ab/_next/static/chunks/pages/_app-a09c984594178bc7ef35.js`.
```
return e.prev = 0, e.abrupt("return", fetch(new Request("https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js", {
	method: "HEAD",
	mode: "no-cors",
	cache: "no-cache"
})).then((function(e) {
	return t = e.type !== bl // breakpoint here
})).catch((function() {
	return t = !0
})));
```
The value of the variable when stopped at breakpoint is `e.type: "default", bl: "opaque"`.

Oddly enough, this request does not appear in the uBO's logger nor in the network tab of the firefox developer tools nor in the console tab.
Since the issue is no longer reproduced, I cannot investigate further.

**Comment by avotoko** [comment]
On my end, the issue reproduces itself in browser that store cookies named `adBlockerNewUserDomains`.
For example adBlockerNewUserDomains: "1502375534"
This number seems to be generated by the calculation `(new Date).getTime() / 1e3`.
Delete this cookie and the issue will not reproduce.
Creating this cookie in a browser that is not reproducing the issue will reproduce the issue.
Hope this helps you.

**Comment by mapx-** [comment]
I get that cookie `adBlockerNewUserDomains` but still cannot reproduce the issue

**Comment by avotoko** [comment]
> I get that cookie `adBlockerNewUserDomains` but still cannot reproduce the issue

What value did you set for `adBlockerNewUserDomains`?
According to the `shouldDisplayPopup` function in `https://i-invdn-com.investing.com/x/prod/67729ab/_next/static/chunks/pages_app-a09c984594178bc7ef35.js`, it should be less than `Math.floor((new Date).getTime() / 1e3) - 60*60*24*3`. In extreme cases, 0 is also acceptable.

**Comment by avotoko** [comment]
There was one more thing to consider in reproducing the issue.
At first I tried placing a breakpoint in the `shouldDisplayPopup` function to force it to return true in order to reproduce the issue, The popup was not generated at that time. The cookie-setting method reproduced the issue.
I don't understand the code `(0, an.jsxs)(an.Fragment...` that generates the popup, but it seems to me that at least if the `shouldDisplayPopup` function returns false, it would not execute the code that generates the popup. 
I will await the first poster's response.

**Comment by stephenhawk8054** [comment]
Ok, I can reproduce it with these steps, basically I need to browse the site for a little bit before getting anti-adblock warning:

- Go to `https://www.investing.com/`
- Choose any links from the far right of the drop down `Markets`, for example `Markets` -> `Indices` -> `S&P 500`
- Choose another, for example `Markets` -> `Stocks` -> `Apple`
- Continue like that, until there's an anti-adblock warning. It takes about 4 or 5 steps to trigger it.

**Comment by okiehsch** [comment]
I could reproduce once but after reloading I can't anymore even following your steps.
I think ghide should work but can't be sure.

**Comment by stephenhawk8054** [comment]
> I could reproduce once but after reloading I can't anymore even following your steps. I think ghide should work but can't be sure.

I just tested and even with `ghide`, it still appears sometimes. Refreshing does make it disappear, but after browsing with a few links, it appears again. Most stable way to reproduce maybe when doing it in private window/incognito.

**Comment by stephenhawk8054** [comment]
Can anyone else test this? So far I haven't reproduced the warning, but since this site is really unstable, I'm not sure if it actualy works:

`investing.com##+js(set, Object.prototype.adBlockDetected, false)`

**Comment by okiehsch** [comment]
Well, reproducing is the real issue here, there is no rhyme nor reason to the detection interval as far as I can see.
````
investing.com##[class*="adBlock"]
investing.com##[class*="overlay_overlay"]
investing.com##body:style(overflow: auto !important)
````
works on my end and I can see in the logger when those filters do apply and if I disable cosmetic filtering at that point I can see the anti adblock message, so that should work.

If your filter works too that would be the preferable solution.

**Comment by stephenhawk8054** [comment]
Yeah, let's wait for the feedbacks.
