### ISSUE TITLE
streamango.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1284]
`https://streamango.com/embed/nomklkrskrfeapre`

popup ads on clicked the player

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.26
Nano Defender 13.19
Chrome 63.0.3239.132

**Comment by ghajini** [comment]
new site
`https://streamangos.com/e/cpdpnfbsetcfllce/La.Compagnia.Del.Cigno.1x01.L.Arrivo.Di.Matteo.ITA.WEBRip.x264-UBi.mkv.mp4`
popup ads
