### ISSUE TITLE
sparda-b.de broken [EasyList Cookie]

### ISSUE THREAD

**Issue by GfEW** [uBlockOrigin/uAssets#12840]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sparda-b.de`

### Describe the issue

The cookie banner is collapsed while apparently waiting for user input, preventing the site from being used (e. g. login).

### Screenshot(s)

![Bildschirmfoto zu 2022-04-18 23-56-27](https://user-images.githubusercontent.com/15276963/163884811-4d932ec1-fca2-42f2-a718-a84d5475fa93.png)

### Notes

This issue does not occur with UBO default config. 
However, as soon as "EasyList Cookie" is activated, it does. 
Disabling "EasyList Cookie" again allows the cookie banner to show up and be interacted with, and then the site to be used. 

(Alternatively, disabling the option "Parse and enforce cosmetic filters" also allows the cookie banner to show up, regardless of "EasyList Cookie" being active or not.)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 84174
  cosmetic: 73069
  scriptlet: 17803
  html: 638
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 30018-65, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 31203-52, now
    ublock-badware: 4081-3, now
    ublock-privacy: 216-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1773-0, now
    ublock-quick-fixes: 167-0, now
    easylist: 66055-622, now
    easyprivacy: 26830-591, now
    urlhaus-1: 7453-0, now
    plowe-0: 3682-3, now
    DEU-0: 5628-2, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5805 ms
  maxAssetCacheWait: 592 ms
```
</details>

**Comment by mapx-** [comment]
Test

```
sparda-b.de##.open.darken-layer
sparda-b.de##.lightbox--cookie-consent
```

@ryanbr
