### ISSUE TITLE
www1.dramacool.fo: popups

### ISSUE THREAD

**Issue by JahrJahrBinks** [uBlockOrigin/uAssets#12847]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www1.dramacool.fo/sell-your-haunted-house-2021-episode-10.html`

### Category

popups

### Describe the issue

Whenever I click on the play button on dramacool it takes me to a website called Gearbest.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80298
  cosmetic: 42348
  scriptlet: 16455
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65932-51, 3d.1h.28m
    easyprivacy: 26792-121, 4d.36m
    plowe-0: 3687-808, 7d.1h.54m
    ublock-abuse: 74-0, 7d.7h.16m
    ublock-badware: 4066-93, 4d.35m
    ublock-filters: 30501-101, 4d.34m
    ublock-privacy: 206-2, 7d.7h.15m
    ublock-unbreak: 1757-42, 4d.33m
    urlhaus-1: 7458-0, 3h.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1697 ms (selfie)
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    adxpub.com: 2
    amung.us: 1
    denetsuk.com: 1
    disqus.com: 3
    googletagmanager.com: 2
    imrworldwide.com: 1
    narrative.io: 1
    nessainy.net: 2
    pippio.com: 1
    rezync.com: 1
    vdo.ai: 2
    viglink.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?
