### ISSUE TITLE
[nsfw] dropmms.com: detection

### ISSUE THREAD

**Issue by shrimplark** [uBlockOrigin/uAssets#12844]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropmms.com/topic/39666-alysha-newman/`

### Category

detection

### Describe the issue

ubo gets detected and a popup saying to whitelist the site shows up. although it doesn't make the site unusable. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 43345
  cosmetic: 76752
  scriptlet: 21477
  html: 635
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-unbreak: null
    ublock-quick-fixes: null
    adguard-mobile: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-annoyance: 51971-3044, 3d.3h.50m
    adguard-social: 16826-1105, 1d.18h.26m
    ublock-annoyances: 4363-7, 1d.15h.59m
  default: 
    user-filters: 177-0, never
    ublock-filters: 31239-259, 1d
    easylist: 65991-23922, 1d.15h.58m
filterset (user): [array of 177 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1157 ms (selfie)
  maxAssetCacheWait: 407 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    a-ads.com: 1
    barscreative1.com: 1
    d301cxwfymy227.cloudfront.net: 1
    dq06u9lt5akr2.cloudfront.net: 2
    f034c21f6f8f233fa195ab8e3d5e9156386800ea9a4081ad473b1b8d571f.s3.amazonaws.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
is `dropmms` the original link you started of ?
