### ISSUE TITLE
namethatporn.com [ADS] [Pop-up] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1285]
URL(s) where the issue occurs

`https://namethatporn.com`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by namethatporn** [comment]
Proposed fix: Stop using the site

**Comment by KiLL4FuNK** [comment]
the thumbnails are not visible
