### ISSUE TITLE
amc.com: ads

### ISSUE THREAD

**Issue by ahauptli** [uBlockOrigin/uAssets#12856]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amc.com/`

### Category

ads

### Describe the issue

Multiple video ads play when watching shows like "Better Call Saul" or other clips available on the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80437
  cosmetic: 42511
  scriptlet: 16428
  html: 638
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 31114-31, 1d.19h.13m
    ublock-badware: 4086-3, 34m
    ublock-privacy: 213-0, 6d.8h.13m
    ublock-abuse: 74-0, 6d.8h.14m
    ublock-unbreak: 1773-0, 1d.19h.12m
    easylist: 65994-601, 1d.19h.14m
    easyprivacy: 26823-577, 1d.19h.15m
    urlhaus-1: 7453-0, 22h.10m
    plowe-0: 3682-3, 3d.5h.12m
    ublock-quick-fixes: 169-0, 22h.15m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 39 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 285 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    brightcove.com: 7
    googletagmanager.com: 1
    imrworldwide.com: 1
    moatads.com: 1
    mparticle.com: 5
    newrelic.com: 1
    perfdrive.com: 1
    scorecardresearch.com: 5
    youborafds01.com: 4
```
</details>

**Comment by ahauptli** [comment]
This was on firefox btw

**Comment by mapx-** [comment]
`amc` is needing an account (provider / subscription)

**Comment by mapx-** [comment]
@ahauptli without an account we cannot investigate if the ads can be blocked.
