### ISSUE TITLE
epekta.com: breakage

### ISSUE THREAD

**Issue by YannikFirre** [uBlockOrigin/uAssets#12851]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://epekta.com/`

### Category

breakage

### Describe the issue

the file /js/468.js seems to be blocked for no reason ?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/3316758/164051302-55188363-59f9-4b97-b9fa-3f26fa22c4a7.png)

![image](https://user-images.githubusercontent.com/3316758/164051355-3a0e11aa-ea65-4881-ae18-418fe71d8590.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 98087
  cosmetic: 51436
  scriptlet: 16498
  html: 636
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 31118-28, 3d.1h.32m
    ublock-badware: 4080-3, 3d.1h.31m
    ublock-privacy: 214-0, 3d.1h.30m
    ublock-abuse: 74-0, 3d.1h.29m
    ublock-unbreak: 1775-0, 3d.1h.28m
    easylist: 65930-793, 3d.1h.27m
    easyprivacy: 26804-892, 3d.1h.26m
    urlhaus-1: 7453-0, 1d.1h.13m
    plowe-0: 3682-3, 2d.5h.3m
    FRA-0: 27468-190, 3d.1h.25m
    ublock-quick-fixes: 169-3, 1d.1h.12m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 56 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 206 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    epekta.com: 1
```
</details>

**Comment by Procyon-b** [comment]
The same issue was already treated for another site in this thread: #12436

**Comment by mapx-** [comment]
@smed79 could you remove that filter ?

**Comment by mapx-** [comment]
@AdamWr

**Comment by smed79** [comment]
Removed https://github.com/easylist/listefr/commit/e2977ba64112832941cf5ce0e639ed9b15175f22

**Comment by mapx-** [comment]
Thanks
