### ISSUE TITLE
pomvideo.cc [Fake button] [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#12857]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pomvideo.cc/601kbyg4bpn6`

### Describe the issue

Fake button Pop-up

### Screenshot(s)

No response

### uBlock Origin version

1.42.4

### Browser name and version

Google Chrome

### Settings

None

### Notes

Ninguna respuesta

**Comment by ludmila3333** [comment]
Fake button Pop-up

**Comment by KiLL4FuNK** [comment]
Fake button Pop-up

`https://pomvideo.cc/2h2lwn66jzw7`
