### ISSUE TITLE
repack-games.com: popups

### ISSUE THREAD

**Issue by SrCastell** [uBlockOrigin/uAssets#12859]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://repack-games.com/`

### Category

popups

### Describe the issue

From time to time I click on parts of the site and other windows open on gearbest.com

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 81698
  cosmetic: 45123
  scriptlet: 16665
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65991-51, 2d.13h.20m
    easyprivacy: 26825-121, 1d.23h.12m
    plowe-0: 3684-808, 9d.1h.45m
    spa-1: 4360-79, 2d.13h.21m
    ublock-abuse: 73-0, 10d.58m
    ublock-badware: 4077-92, 1d.23h.11m
    ublock-filters: 30535-134, 1d.23h.10m
    ublock-privacy: 207-2, 10d.57m
    ublock-unbreak: 1764-43, 1d.23h.9m
    urlhaus-1: 7454-0, 11h.9m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 585 ms (selfie)
  maxAssetCacheWait: 291 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    repack-games.com: 1
    bet365.com: 1
    discord.com: 1
    s3.us-east-1.amazonaws.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?
