### ISSUE TITLE
english-e-reader.net: breakage

### ISSUE THREAD

**Issue by byzantium225** [uBlockOrigin/uAssets#12852]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://english-e-reader.net/register`

### Category

breakage

### Describe the issue

The registration form is being blocked, I can only see it if I disable uBO.

### Screenshot(s)

<details>
<summary>Without uBO enabled</summary>

![Screenshot_2022-04-19-22-09-59-38_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/102585192/164053388-53f3bb0f-22a7-4cca-aef4-893bbb3a758a.jpg)

</details>

<details>
<summary>With uBO enabled</summary>

![Screenshot_2022-04-19-22-10-35-82_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/102585192/164053465-6f0f00c2-0548-43f6-8a07-307d9f93e5a8.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox Mobile: 96
filterset (summary): 
  network: 166564
  cosmetic: 218037
  scriptlet: 36333
  html: 651
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63845-5263, 23h.29m
    adguard-spyware: 26227-1165, 23h.22m
    adguard-spyware-url: 556-4, 9h.36m
    block-lan: 43-0, 27d.8h.56m
    curben-phishing: 13141-2, 8h.13m
    curben-pup: 275-0, 8h.12m
    adguard-annoyance: 52024-4626, 23h.26m
    adguard-social: 16827-1090, 23h.25m
    fanboy-thirdparty_social: 69-0, 2d.7h.23m
    fanboy-annoyance: 68575-53305, 2d.7h.22m
    fanboy-cookiemonster: 29800-95, 2d.7h.21m
    fanboy-social: 23300-28, 23h.24m
    ublock-annoyances: 4363-4, 23h.23m
    dpollock-0: 10364-489, 5d.2h.58m
    RUS-0: 41423-265, 1d.8h.42m
  default: 
    user-filters: 23-0, never
    ublock-filters: 31302-68, 1d.42m
    ublock-badware: 4081-3, 1d.41m
    ublock-privacy: 211-0, 8d.6h.46m
    ublock-abuse: 74-0, 8d.6h.7m
    ublock-unbreak: 1778-0, 1d.40m
    adguard-mobile: 7585-196, 23h.28m
    easylist: 66009-958, 23h.27m
    easyprivacy: 26842-10662, 6h.22m
    urlhaus-1: 7458-0, 8h.14m
    plowe-0: 3687-2, 12d.7h.26m
    ublock-quick-fixes: 168-0, 8h.15m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2199 ms (selfie)
  maxAssetCacheWait: 4176 ms
popupPanel: 
  blocked: 8
  no-cosmetic-filtering: true
  blockedDetails: 
    cloudflare.com: 4
    facebook.net: 1
    googletagmanager.com: 1
    onesignal.com: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr
