### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Twister-Fries** [uBlockOrigin/uAssets#12863]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=1uOE3Uj0sWc`

### Category

ads

### Describe the issue

every yt vid, there is the same ad everytime

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80424
  cosmetic: 42495
  scriptlet: 16474
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65987-51, 2d.21h.43m
    easyprivacy: 26824-121, 2d.21h.42m
    plowe-0: 3687-808, 7d.6h.3m
    ublock-abuse: 74-0, 5d.10h.24m
    ublock-badware: 4077-93, 2d.21h.41m
    ublock-filters: 30528-99, 2d.21h.40m
    ublock-privacy: 208-2, 5d.7h.2m
    ublock-quick-fixes: 171-4, 9h.55m
    ublock-unbreak: 1761-42, 2d.21h.39m
    urlhaus-1: 7454-0, 9h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1127 ms (selfie)
  maxAssetCacheWait: 381 ms
popupPanel: 
  blocked: 999
  blockedDetails: 
    youtube.com: 697
    doubleclick.net: 27
    google.com: 65
    google.com.ph: 1
    googleadservices.com: 4
    googlesyndication.com: 143
    googlevideo.com: 62
```
</details>

**Comment by faastcall** [comment]
#7636
