### ISSUE TITLE
bagzcart.com: ads

### ISSUE THREAD

**Issue by 0x6900** [uBlockOrigin/uAssets#12862]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://bagzcart.com/bag/index.php/lists/tp705tzae887f/confirm-unsubscribe/tv1959f1d9bda/fj09480jr0424`

### Category

ads

### Describe the issue

Ads leeftovers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/14212781/164192620-ee36f65a-2ed7-4b1f-9f90-7914f3013ab6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 80524
  cosmetic: 42669
  scriptlet: 16538
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 131-0, never
    easylist: 66067-51, 21h.8m
    easyprivacy: 26842-121, 21h.8m
    plowe-0: 3682-804, 21h.8m
    ublock-abuse: 74-0, 21h.8m
    ublock-badware: 4077-93, 21h.8m
    ublock-filters: 30634-106, 21h.8m
    ublock-privacy: 211-2, 21h.8m
    ublock-quick-fixes: 171-3, 21h.8m
    ublock-unbreak: 1762-42, 21h.8m
    urlhaus-1: 7458-0, 21h.8m
filterset (user): [array of 131 redacted]
trustedset: 
  added: [array of 45 redacted]
hostRuleset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10261 ms (selfie)
  maxAssetCacheWait: 9037 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    supportonline.in: 1
```
</details>

**Comment by mapx-** [comment]
> Ads leftovers

no difference with / without uBO, I'm not sure if it's normal page (shopping site)

@ryanbr

**Comment by 0x6900** [comment]
It's an unsubscribe page from a spammer's spam list. Don't know how to block on all instances of it or to use wildcard on it.

**Comment by mapx-** [comment]
How did you get on that page?

**Comment by 0x6900** [comment]
By clicking the unsubscribe link in mail.

It's a common practice of this spammer, who adds recipients illegally and used to earn by showing these ads on unsubscribe page for affiliate marketing.

**Comment by mapx-** [comment]
add to your "my filters"

`||bagzcart.com/*/confirm-unsubscribe`
