### ISSUE TITLE
Fake download buttons on torrent sites

### ISSUE THREAD

**Issue by Mirellanmawl** [uBlockOrigin/uAssets#1286]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://monova.to/D9F2438C8046B394E5525AFE8145F15F436E07AF
https://yourbittorrent.com/torrent/7771929/debian-8-0-jessie-i386.html
https://1337x.to/torrent/2084127/Debian-8-7-1-LIVE-Jessie-Standard-x32-i386-ISO-Uzerus/
https://www.torlock.com/torrent/4019067/debian-8-0-jessie-i386.html
https://www.seedpeer.eu/details/59a361262be2494ecc2eed68
http://www.torrentdownloads.me/torrent/1659971955/Debian-8+0-Jessie-i386
https://www.limetorrents.cc/-torrent-6124073.html
http://www.magnetdl.com/file/1856703/debian-gnu-linux-8.0-jessie-i386-3xdvd-multilingual-appzdam/
http://www.torrentdownload.ch/Debian-8-0-Jessie-i386/D9F2438C8046B394E5525AFE8145F15F436E07AF

### Describe the issue

These torrent sites have fake download buttons, that when clicked opens a random popup, some paid "direct download" services that I assume is a scam (you should not pay for torrents...) or a sponsor website, in some cases malwaretising or scam sites.
MagnetDL.com also has a sneaky ad banner (image file with text that begins with "Tip: Downlaod anonymously and use a VPN Service".)

### Versions

- Browser/version: Firefox Quantum 57.0.4 (64-bit)
- uBlock Origin version: 1.14.24

### Settings

- Enable cloud storage support
- I am an advanced user
- Auto-update filter lists
- Subscribed to multiple filter lists
- Custom filters (I do not think the ones I have would affect the result)
- Few dynamic filtering rules (that does not effect mentioned websites)

### Notes

I was able to hide them all using the element picker

**Comment by FatOrangutan** [comment]
`monova.*##.files-box` seems to remove the files list. Example link from OP: https://monova.to/D9F2438C8046B394E5525AFE8145F15F436E07AF

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a1bcfef4b47bfd99308336f8f6dc2531021a5a68

already fixed.

**Comment by dportvine** [comment]
`https://www.torrentdownloads.pro/torrent/1704717079/Back-to-Black-2024-1080p-Amazon-WebDL-H264-iTz-Will1869-mp4`

<details>
<summary>Screen</summary>

![2024-05-29_122734](https://github.com/uBlockOrigin/uAssets/assets/111344219/5573578b-87c5-4f7b-b0c3-c817983a4688)
</details>
