### ISSUE TITLE
paramountplus.com: breakage

### ISSUE THREAD

**Issue by rountreecdr** [uBlockOrigin/uAssets#12873]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.paramountplus.com/home/`

### Category

breakage

### Describe the issue

because ads are blocked, when a show is finished, its not updating in the carousel of my shows. When I watch on my phone, and then the ad plays, the carousel updates to the next episode. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80770
  cosmetic: 42535
  scriptlet: 16536
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66068-51, 2d.19m
    easyprivacy: 26839-121, 2d.20m
    plowe-0: 3687-808, 12d.20h.44m
    ublock-abuse: 74-0, 2d.25m
    ublock-badware: 4077-92, 2d.23m
    ublock-filters: 30613-106, 2d.22m
    ublock-privacy: 211-2, 2d.24m
    ublock-quick-fixes: 171-0, 13h.57m
    ublock-unbreak: 1762-42, 2d.21m
    urlhaus-1: 7717-1, 13h.58m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6642 ms
  maxAssetCacheWait: 3892 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    paramountplus.com: 1
    ads-twitter.com: 1
    appboycdn.com: 1
    bing.com: 1
    branch.io: 1
    cedexis.com: 1
    demdex.net: 2
    facebook.net: 1
    googletagmanager.com: 1
    impactradius-event.com: 1
    pinimg.com: 1
    qualtrics.com: 1
    sc-static.net: 1
    scorecardresearch.com: 2
    yahoo.com: 1
```
</details>

**Comment by mapx-** [comment]
Does this exception help ?

`@@||saa.paramountplus.com^$xhr,1p`
