### ISSUE TITLE
japantimes.co.jp: nuisance

### ISSUE THREAD

**Issue by giovanni-TR** [uBlockOrigin/uAssets#12870]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.japantimes.co.jp/life/2011/10/09/general/women-warriors-of-japan/`

### Category

nuisance

### Describe the issue

The Japan Times website brings up a subscribe paywall that isn't automatically blocked, but can be removed using the element picker tool. After filtering the pop-up, I am able to read the article for about two seconds before the scroll bar disappears and I can't scroll anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (2878)](https://user-images.githubusercontent.com/104107772/164337878-5204cea7-e021-48f5-8fd9-fd544cc5bbbd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80752
  cosmetic: 42556
  scriptlet: 16499
  html: 638
listset (total-discarded, last updated): 
  default: 
    user-filters: 15-0, never
    ublock-filters: 31225-34, 1d.6h.7m
    ublock-badware: 4086-3, 1d.6h.6m
    ublock-privacy: 212-0, 10d.22h.24m
    ublock-abuse: 74-0, 10d.22h.23m
    ublock-unbreak: 1773-0, 1d.6h.5m
    easylist: 66083-605, 1d.6h.4m
    easyprivacy: 26842-577, 1d.6h.3m
    urlhaus-1: 7667-1, 22h
    plowe-0: 3682-3, 5d.8h.12m
    ublock-quick-fixes: 167-0, 21h.59m
filterset (user): [array of 15 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 268 ms (selfie)
  maxAssetCacheWait: 186 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    japantimes.co.jp: 3
    addthis.com: 1
    ads-twitter.com: 1
    chartbeat.com: 3
    cxense.com: 1
    doubleclick.net: 1
    google-analytics.com: 3
    google.com: 2
    googletagmanager.com: 2
    indexww.com: 2
    npttech.com: 1
    piano.io: 1
    stripe.com: 4
    taboola.com: 2
    typekit.net: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Paywall is out-of-scope of uAssets. You can try yourself: `japantimes.co.jp##body:style(overflow: auto !important)`
