### ISSUE TITLE
euw.op.gg: breakage

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#12887]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://euw.op.gg/summoners/euw/don%20noway`

### Category

breakage

### Describe the issue

Issue only happens on the "new op.gg interface" (enable through yellow banner on the top)

Problems:
- clicking on the down arrow of a match hides the complete game list instead of showing the game's details.
- Ad placeholders are still shown (1 top, 1 left sidebar and 1 bottom)

(disabling cosmetic filters shows the match details again, but also the top self-advertisment banner and it wouldn't hide the ad placeholders if the filters would match)

light/darkmode seems irrelevant for this issue

tested also on chrome without other plugins, same result.

### Screenshot(s)

<details><summary>Screenshot(s)</summary>

![screenshot_1](https://user-images.githubusercontent.com/3533175/164544526-46d24880-2dee-4d72-aee9-6c63f768f242.png)
![screenshot_2](https://user-images.githubusercontent.com/3533175/164544681-0dfbf516-8bcd-43f5-95b3-d8263cef169d.png)
![screenshot_3](https://user-images.githubusercontent.com/3533175/164544755-dd0717cd-ca15-4fb5-b91f-a626cfadf4f9.png)</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 80602
  cosmetic: 47545
  scriptlet: 19360
  html: 646
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    ublock-annoyances: 4343-4, 1d.23h.51m
  default: 
    user-filters: 349-0, never
    ublock-filters: 31237-47, 1d.21h.44m
    ublock-badware: 4086-3, 1d.23h.55m
    ublock-privacy: 211-0, 10d.2h.49m
    ublock-abuse: 74-0, 10d.2h.49m
    ublock-unbreak: 1774-0, 1d.23h.54m
    easylist: 66123-256, 1d.23h.53m
    easyprivacy: 26844-141, 1d.23h.52m
    urlhaus-1: 7860-1, 1h.54m
    DEU-0: 5631-1, 1h.53m
    ublock-quick-fixes: 160-0, 1h.52m
filterset (user): [array of 346 redacted]
trustedset: 
  added: [array of 118 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 8 redacted]
hostRuleset: 
  added: [array of 2 redacted]
urlRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 200 ms (selfie)
  maxAssetCacheWait: 200 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    datadoghq-browser-agent.com: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    jsdelivr.net: 2
    riotgames.com: 1
    vntsm.com: 1
```
</details>

**Comment by Janmm14** [comment]
Thanks, it works!

**Comment by lazinism** [comment]
I think
op.gg##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement)
breaks the page
![image](https://user-images.githubusercontent.com/3297355/166114086-88263c70-f0bb-49bf-b749-d83965364b7b.png)
What it should be look on [this](https://www.op.gg/summoners/kr/%EC%8B%A4%EB%B2%84%EC%93%B0%EB%A0%88%EA%B8%B0%EC%98%88%EC%A0%95)
and what it looks like is
![image](https://user-images.githubusercontent.com/3297355/166114115-df378f68-c411-4d12-bd6c-0d07a5c15ac1.png)
the parts omitted is
![image](https://user-images.githubusercontent.com/3297355/166114142-b334b598-5337-45af-922d-f0b81c47cd50.png)
2nd, 3rd divs
so we should selectively block first div which has div.vm-placement
