### ISSUE TITLE
italiashare.life (again)

### ISSUE THREAD

**Issue by mclovin74** [uBlockOrigin/uAssets#1288]
URL(s) where the issue occurs

`http://www.italiashare.life`

Describe the issue
Anti-adblock

Screenshot(s)
![cattura](https://user-images.githubusercontent.com/35187596/34915803-6b8a6cde-f92c-11e7-8b1d-dc8713a4549e.PNG)

Versions

Chrome: 63.0.3239.84
uBlock Origin version: 1.14.24

Settings

default setting + easylist italian + apb italian

Notes
i have made a clean install of chrome+ubo. Updated filter, with last modify of some hours ago and now there is a different screen.
In the filter, solution start at line 980.

**Comment by mapx-** [comment]
don't post anymore clickable links !

However, still working for me.

**Comment by mclovin74** [comment]
sorry for the link.
I have marked Adblock Plus-compatible “element hiding” filters and it works. Thanks.
With same setting but with nanoadblocker not work.
