### ISSUE TITLE
derechadiario.com.ar: breakage

### ISSUE THREAD

**Issue by 0uros** [uBlockOrigin/uAssets#12883]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://derechadiario.com.ar/norteamerica/norteamerica_estados-unidos/ron-desantis-esta-a-un-paso-de-sacarle-a-disney-su-estatus-especial-en-florida-como-respuesta-a-su-boicot`

### Category

breakage

### Describe the issue

I can't read the article when I activate uBlock, the page only show the titles.

I'm using Firefox Android.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 85251
  cosmetic: 28774
  scriptlet: 16677
  html: 641
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31239-314, 3d.12h.18m
    ublock-badware: 4081-3, 3d.12h.17m
    ublock-privacy: 212-1, 11d.15h.20m
    ublock-abuse: 74-0, 11d.15h.19m
    ublock-unbreak: 1778-0, 3d.12h.16m
    ublock-quick-fixes: 171-0, 16h.26m
    adguard-mobile: 7584-173, 3d.12h.19m
    easylist: 65994-24594, 3d.12h.14m
    easyprivacy: 26830-602, 2d.18h.50m
    urlhaus-1: 7717-1, 13h.16m
    plowe-0: 3684-2, 10d.21h.38m
    spa-0: 3875-219, 13h.17m
    spa-1: 4360-183, 3d.12h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1015 ms (selfie)
  maxAssetCacheWait: 285 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    derechadiario.com.ar: 4
    cleverwebserver.com: 2
    googlesyndication.com: 13
    googletagmanager.com: 1
    vidverto.io: 5
```
</details>

**Comment by mapx-** [comment]
add

`derechadiario.com.ar#@#div[class] > p:has-text(Ad):upward(1)`

@Yuki2718 @AdamWr

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
Thank you.
