### ISSUE TITLE
frospiren.dk: breakage

### ISSUE THREAD

**Issue by KillerDvD** [uBlockOrigin/uAssets#12885]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://frospiren.dk/`

### Category

breakage

### Describe the issue

The pictures don't load on the site when uBlockOrigin is enabled on the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80864
  cosmetic: 42631
  scriptlet: 16546
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66261-51, 3h.59m
    easyprivacy: 26858-121, 3h.58m
    plowe-0: 3684-808, 10d.21h.10m
    ublock-abuse: 74-0, 3h.54m
    ublock-badware: 4092-92, 3h.57m
    ublock-filters: 30656-107, 3h.56m
    ublock-privacy: 212-2, 3h.53m
    ublock-quick-fixes: 130-0, 3h.51m
    ublock-unbreak: 1763-43, 3h.55m
    urlhaus-1: 7692-1, 3h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 297 ms (selfie)
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    frospiren.dk: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by KillerDvD** [comment]
It's fixed now with the update.
