### ISSUE TITLE
https://hepster.com/datenschutz broken [EasyList Cookie]

### ISSUE THREAD

**Issue by GfEW** [uBlockOrigin/uAssets#12886]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://hepster.com/datenschutz`

### Describe the issue

The cookie banner is hidden while apparently waiting for user input, preventing the page from being scrolled, so most of its text content cannot be read.

### Screenshot(s)

![Bildschirmfoto zu 2022-04-21 18-47-15](https://user-images.githubusercontent.com/15276963/164512967-bdf2efc4-0584-448f-8cca-9aa736f56aa6.png)

### Notes

The screenshot depicts the expected cookie banner that, if this issue is triggered, fails to be shown.

This issue does not occur with UBO default config.
However, as soon as "EasyList Cookie" is activated, it does.
Disabling "EasyList Cookie" again allows the cookie banner to show up and be interacted with, and then the site to be scrolled.

(Alternatively, disabling the option "Parse and enforce cosmetic filters" also allows the cookie banner to show up and be interacted with, and then the page to be scrolled, regardless of "EasyList Cookie" being active or not.)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 84468
  cosmetic: 73420
  scriptlet: 17830
  html: 638
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 30410-87, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 31203-42, 2d.18h.54m
    ublock-badware: 4081-3, 2d.18h.54m
    ublock-privacy: 216-0, 2d.18h.54m
    ublock-abuse: 74-0, 2d.18h.54m
    ublock-unbreak: 1773-0, 2d.18h.54m
    ublock-quick-fixes: 167-0, 2m
    easylist: 66055-610, 2d.18h.54m
    easyprivacy: 26830-588, 2d.18h.54m
    urlhaus-1: 7728-1, 2m
    plowe-0: 3682-3, 2d.18h.54m
    DEU-0: 5631-2, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1149 ms (selfie)
  maxAssetCacheWait: 663 ms
```
</details>

**Comment by mapx-** [comment]
add

`hepster.com##body:style(overflow: auto !important;)`

@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8b7038aefbec00e302d16e329e9d1bfba5badf26
