### ISSUE TITLE
waaw.to: breakage

### ISSUE THREAD

**Issue by PrometheusQ** [uBlockOrigin/uAssets#12881]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://waaw.to/`

### Category

breakage

### Describe the issue

On this site a randomly placed play button has to be pressed as part of validation before the video could be played. It worked fine in the past with UBlock but now that play button is not clickable - I cannot view any video on this site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80801
  cosmetic: 42515
  scriptlet: 16555
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66199-51, 16h.53m
    easyprivacy: 26835-122, 2d.12h.2m
    plowe-0: 3682-804, 2d.20h.4m
    ublock-abuse: 74-0, 11d.1h.41m
    ublock-badware: 4092-93, 16h.56m
    ublock-filters: 30678-106, 16h.55m
    ublock-privacy: 207-2, 11d.1h.40m
    ublock-unbreak: 1763-42, 16h.54m
    urlhaus-1: 7717-1, 12h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms (selfie)
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    waaw.to: 1
    addthis.com: 1
    disqus.com: 5
    viglink.com: 2
    your-notice.com: 1
```
</details>

**Comment by mapx-** [comment]
provide an example (I tried a couple from the home page => no issue, the video is starting directly)

**Comment by ghajini** [comment]
does this make any difference
```
||waaw.to/js/script-2.12.5.js$script,1p
||waaw.to/cdn-cgi/trace$xhr,1p
```

**Comment by okiehsch** [comment]
`waaw.*#@#+js(aopr, console.clear)`
works for me, try adding that to your filter list.

**Comment by PrometheusQ** [comment]
> `waaw.*#@#+js(aopr, console.clear)` works for me, try adding that to your filter list.

It helped me, now it works fine. Thank you.

**Comment by krystian3w** [comment]
#13987
