### ISSUE TITLE
themoscowtimes.com: nuisance

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#12897]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.themoscowtimes.com/2022/04/22/5-russian-enlistment-offices-hit-by-arson-attacks-reports-a77454`

### Category

nuisance

### Describe the issue

Annoying popup that appears everyday. Can be replicated with privacy mode

Note: I use uBlock filters – Annoyances

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/40742924/164687688-f9815a9e-08b4-4be2-bab6-93410577547d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82163
  cosmetic: 45745
  scriptlet: 19581
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4347-8, 4m
  default: 
    user-filters: 0-0, never
    NOR-0: 2703-0, 5m
    easylist: 66286-51, 5m
    easyprivacy: 26858-122, 5m
    plowe-0: 3682-805, 5m
    ublock-abuse: 74-0, 5m
    ublock-badware: 4093-94, 5m
    ublock-filters: 30822-108, 5m
    ublock-privacy: 212-2, 5m
    ublock-quick-fixes: 166-0, 5m
    ublock-unbreak: 1766-42, 5m
    urlhaus-1: 7870-1, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1317 ms
  maxAssetCacheWait: 227 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googletagmanager.com: 1
    googletagservices.com: 1
    onesignal.com: 1
    s-onetag.com: 1
    themoneytizer.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
themoscowtimes.com##.contribute-modal
themoscowtimes.com##.contribute-bar
themoscowtimes.com##body:style(overflow: auto !important;)
```

@ryanbr

**Comment by AndnixSH** [comment]
interesting, so uBlock filters – Annoyances is no longer been updated? wanted to avoid easylist filters

**Comment by stephenhawk8054** [comment]
> interesting, so uBlock filters – Annoyances is no longer been updated? wanted to avoid easylist filters

Per [Readme](https://github.com/uBlockOrigin/uAssets#uassets):

> If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

**Comment by AndnixSH** [comment]
Understood, thanks
