### ISSUE TITLE
apkmirror.com: detection

### ISSUE THREAD

**Issue by shrimplark** [uBlockOrigin/uAssets#12893]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.apkmirror.com/apk/supercell/clash-of-clans/clash-of-clans-14-426-6-release/clash-of-clans-14-426-6-2-android-apk-download/`

### Category

detection

### Describe the issue

I'm using Firefox Nightly 101.0a1 and ublock origin is getting detected in all apk download pages in this website. I've disabled my custom dns, reinstalled the browser, added only the ublock origin addon, updated the filter without adding or removing anything. But it's still getting detected for some reason. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 82572
  cosmetic: 24454
  scriptlet: 16694
  html: 642
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31505-266, 1m
    ublock-badware: 4097-3, 1m
    ublock-privacy: 217-1, 1m
    ublock-abuse: 74-0, 1m
    ublock-unbreak: 1779-0, 1m
    ublock-quick-fixes: 167-0, 1m
    adguard-mobile: 7596-172, 1m
    easylist: 66286-24580, 1m
    easyprivacy: 26858-585, 1m
    urlhaus-1: 7870-1, 1m
    plowe-0: 3682-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9898 ms
  maxAssetCacheWait: 802 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    clarity.ms: 1
    cloudflareinsights.com: 2
    crsspxl.com: 1
    google-analytics.com: 1
    google.com: 5
    googlesyndication.com: 1
    instant.page: 1
    outbrain.com: 1
    pro-market.net: 2
    quantserve.com: 1
    scorecardresearch.com: 1
    wp.com: 2
```
</details>

**Comment by krystian3w** [comment]
Test too with disabled Firefox tracking protection - PC no need new added commit.

**Comment by stephenhawk8054** [comment]
> Test too with disabled Firefox tracking protection - PC no need new added commit.

I still got detection on PC.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/164652461-a5b22eb9-3c40-4488-b7ec-10f5d3e5373e.png)

</details>
