### ISSUE TITLE
dropgalaxy.com : Anti adblock

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#12892]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dgdrive.xyz/cf5upi0y3w92`

### Describe the issue

The website detects UBlock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80951522/164621356-afb7217c-d703-42e4-a89c-b7f5ad20ff30.png)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome 100.xx

### Settings

All default settings

**Comment by blazesprings** [comment]
I updated the filters, worked for one link then again from the next link onwards detected the UBo
Check this link : https://dgdrive.xyz/c0l0yfpuaezb

**Comment by blazesprings** [comment]
When the countdown timer starts, a small popup window appears below which closes automatically
I guess it  is closed by UBo. I think the website detects the UBo by this popup window. I am not sure.

**Comment by blazesprings** [comment]
@JobcenterTycoon This update isn't working. I have updated the filters and verified the link. UBo still detected.

**Comment by stephenhawk8054** [comment]
Maybe adding these?

```
@@||assets.vlitag.com/prebid/default/prebid-*.js$script,domain=dropgalaxy.com
dropgalaxy.com##.grid-container
```

**Comment by JobcenterTycoon** [comment]
Works, added.

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon I think this filter can cause a popup on chromium:

`@@||cloudfront.net/publishers/dropgalaxycom.min.js$domain=dropgalaxy.com`

Click on `Free download` -> Wait 5s and click on `Free download ready`

**Comment by stephenhawk8054** [comment]
> Edit: The popup is gone, does removing `cloudfront.net/publishers/dropgalaxycom.min.js$domain=dropgalaxy.com` works without anti adblock? @stephenhawk8054

Currently, there's no anti-adblock if removing that filter but there's still a fast popup when clicking on `Create download link` on chromium for me.

**Comment by JobcenterTycoon** [comment]
I get no popups anymore

**Comment by stephenhawk8054** [comment]
Actually, the popup appears for me when clicking on any where in the 15s countdown stage.

**Comment by blazesprings** [comment]
Yes @stephenhawk8054 for me as well.

**Comment by stephenhawk8054** [comment]
Looks like the one that caused issue for me is

`@@||blockadsnot.com/tabletop.min.js$script,domain=financemonk.net|dropgalaxy.*`
