### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by UnaidedButton86** [uBlockOrigin/uAssets#12895]
### Prerequisites

- [ ] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aternos.org/`

### Category

detection

### Describe the issue

There's a big red screen that detects the adblocker. If you go to any subpage, you have to wait a few seconds before being allowed to continue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81780
  cosmetic: 44056
  scriptlet: 16600
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    NLD-0: 2188-13, 9m
    easylist: 66286-54, 14m
    easyprivacy: 26858-121, 13m
    plowe-0: 3684-808, 11d.1h.50m
    ublock-abuse: 74-0, 8d.1h.31m
    ublock-badware: 4093-92, 12m
    ublock-filters: 30696-149, 11m
    ublock-privacy: 209-2, 8d.1h.30m
    ublock-quick-fixes: 166-0, 7m
    ublock-unbreak: 1763-56, 10m
    urlhaus-1: 7870-1, 8m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 898 ms (selfie)
  maxAssetCacheWait: 235 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    aternos.org: 3
    amazon-adsystem.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    snigelweb.com: 1
```
</details>

**Comment by UnaidedButton86** [comment]
Sorry, I didn't saw this was reported already. Here's a report that describes it better: https://github.com/uBlockOrigin/uAssets/issues/8246

**Comment by UnaidedButton86** [comment]
I'm sorry, I didn't saw there was another report done. I close the thread with this comment. https://github.com/uBlockOrigin/uAssets/issues/8246

**Comment by krystian3w** [comment]
Maybe JobcenterTycoon add new network exeptions in Quick Fixes...

**Comment by JobcenterTycoon** [comment]
@UnaidedButton86 i fixed it a day ago force update the quick filter list

**Comment by DumbGameMaker** [comment]
they seem to have patched it. hiding or removing the 'turn off adblock' screen nukes the entire page... it's almost like they don't want us to block their ads 🤯
