### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by vjrmy** [uBlockOrigin/uAssets#12890]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dgdrive.xyz/qs70zukn1vf9`

### Category

detection

### Describe the issue

Anti Adblock detection. Try to download the file, in first page safe then second page safe but in the third page anti adblock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 138114
  cosmetic: 169049
  scriptlet: 35134
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52015-173, 3d.14h.18m
    adguard-generic: 63806-743, 3d.14h.16m
    adguard-social: 16825-854, 3d.14h.25m
    adguard-spyware: 25843-737, 3d.14h.26m
    adguard-spyware-url: 556-13, 3d.14h.34m
    curben-phishing: 13614-2, 23h.7m
    fanboy-cookiemonster: 29343-2341, 6d.14h.46m
    ublock-annoyances: 4355-215, 3d.15h.30m
  default: 
    user-filters: 6-0, never
    IDN-0: 8998-0, 1d.12h.25m
    adguard-mobile: 7584-56, 3d.16h.18m
    easylist: 65996-1193, 3d.14h.15m
    easyprivacy: 26826-10361, 3d.14h.9m
    plowe-0: 3687-965, 6d.22h.1m
    ublock-abuse: 74-0, 6d.21h.59m
    ublock-badware: 4077-290, 3d.13h.59m
    ublock-filters: 30647-3506, 3d.13h.54m
    ublock-privacy: 209-39, 6d.21h.57m
    ublock-quick-fixes: 171-5, 22h.58m
    ublock-unbreak: 1767-106, 3d.13h.53m
    urlhaus-1: 7692-2, 23h.6m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3767 ms (selfie)
  maxAssetCacheWait: 2322 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    a-ads.com: 1
    vlitag.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?
