### ISSUE TITLE
lp.mentor.duden.de: breakage

### ISSUE THREAD

**Issue by TotalDraenor** [uBlockOrigin/uAssets#12896]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lp.mentor.duden.de/chrome-plugin-installiert/`

### Category

breakage

### Describe the issue

It's not a big problem, but the web page display looks shifted when uBO is used.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="742" alt="uncentered" src="https://user-images.githubusercontent.com/50454988/164679277-5d9c9bbb-3274-42d0-bb3e-91391032acd9.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 83246
  cosmetic: 46103
  scriptlet: 16701
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    DEU-0: 5631-0, 10m
    easylist: 66286-57, 13m
    easyprivacy: 26858-132, 12m
    plowe-0: 3682-805, 5d.23m
    ublock-abuse: 74-0, 16m
    ublock-badware: 4093-93, 11m
    ublock-filters: 30817-116, 15m
    ublock-privacy: 212-2, 17m
    ublock-quick-fixes: 166-0, 9m
    ublock-unbreak: 1763-43, 14m
    urlhaus-1: 7870-1, 8m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 351 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    d34qb8suadcc4g.cloudfront.net: 1
    googletagmanager.com: 1
    unbounce.com: 3
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
