### ISSUE TITLE
genshinimpactcalculator.com: detection

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#12891]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://genshinimpactcalculator.com/genshinCalc.html`

### Category

detection

### Describe the issue

Antiadblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 98
filterset (summary): 
  network: 102755
  cosmetic: 58577
  scriptlet: 28439
  html: 641
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63964-1431, 1d.6h.34m
  default: 
    user-filters: 8-0, never
    ublock-filters: 31335-3359, 1d.6h.40m
    ublock-badware: 4081-3, 1d.6h.39m
    ublock-privacy: 216-1, 1d.6h.37m
    ublock-abuse: 74-0, 1d.6h.36m
    ublock-unbreak: 1779-0, 1d.6h.35m
    adguard-mobile: 7592-172, 23h.38m
    easylist: 66260-25437, 23h.28m
    easyprivacy: 26857-713, 23h.22m
    urlhaus-1: 7860-1, 10h.7m
    plowe-0: 3682-3, 10h.8m
    spa-0: 3875-219, 10h.6m
    spa-1: 4378-183, 23h.11m
    ublock-quick-fixes: 171-0, 10h.5m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  uiFlavor: -
supportStats: 
  allReadyAfter: 3132 ms (selfie)
  maxAssetCacheWait: 1519 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    ampproject.org: 2
    clarity.ms: 1
    google.com: 4
    googletagmanager.com: 1
    nitropay.com: 2
    paypal.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe in more details? The site runs normally for me.

**Comment by mapx-** [comment]
The header is slightly broken, the `Please disable adBlock` message is present even disabling uBO

These should help (on desktop, on mobile seems to be ok)

```
genshinimpactcalculator.com#@#.adban
genshinimpactcalculator.com###BannerTop:style(height: 20px!important)
```

![image](https://user-images.githubusercontent.com/10303732/164610670-61162b53-3eb7-44bc-9795-4e9354d04730.png)

**Comment by krystian3w** [comment]
So need mark as unbreak or site issue with won't fix.

**Comment by stephenhawk8054** [comment]
@mapx- I think 2nd filter makes the site's display/table not in center when clicking on the full screen button (the 2-side arrow at the top right). It goes up instead

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/164674270-09ef0072-767c-46ee-a537-9646a926815f.png)

</details>

Maybe `genshinimpactcalculator.com#@#.adban` is good enough?

**Comment by mapx-** [comment]
sure - @ryanbr should fix `adban` and we are ok
