### ISSUE TITLE
vivads.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1290]
URL(s) where the issue occurs

`http://vivads.net/eXkBuw`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SkeletalDemise** [comment]
@okiehsch There is a redundancy. There's two copies of this filter, `vivads.net##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)`

**Comment by okiehsch** [comment]
Thx, fixed https://github.com/uBlockOrigin/uAssets/commit/b0dfc3ccef0fbfb9927fc8f12b314fd1e2520fa0

**Comment by SkeletalDemise** [comment]
There's also three more redundancies. `@@||cllkme.com^$generichide` `||pussl5.com^$script,third-party` and `||imglnka.com^`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f78628c32f3865e4ed4195366bf0ea6d1ff489c1

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Popup. You need to solve captcha to get to it. Also, scripts try to hide if you open dev console. `vivads.net##div:has(> a[target="_blank"][style*="height: inherit"])` fixes it, but there is certainly a better solution.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
I added 
`@@||vivads.net^$generichide`

but I get  `CAPTCHA was incorrect. Try again`

**Comment by KiLL4FuNK** [comment]
just add the anti adblock until the CAPTCHA is fixed

@@||vivads.net^$generichide

**Comment by KiLL4FuNK** [comment]
ADS

`http://vivads.net/EK3OSRL`
