### ISSUE TITLE
[nsfw] waaw.to: breakage

### ISSUE THREAD

**Issue by cleuton4k** [uBlockOrigin/uAssets#12904]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://waaw.to/watch_video.php?v=R0JmTm8vY0tOTDMwakJhVWNQSXlvREFMN2QvOVZHdlNvMUdROHN2ZlUrM0ZEYVpjNGZxVUZ4Tks4YTlNQThCTw%3D%3D`

### Category

breakage

### Describe the issue

player doesn't work when ublock filters is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 140024
  cosmetic: 161307
  scriptlet: 32494
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41434-21, 1d.13h
    adguard-annoyance: 52026-463, 3d.19h.35m
    adguard-generic: 63857-896, 3d.19h.34m
    adguard-spyware: 26231-1032, 3d.19h.33m
    curben-pup: 275-0, 1d.1h
    fanboy-social: 23300-26, 3d.19h.30m
    fanboy-thirdparty_social: 68-20, 7d.22h.16m
    spa-1: 4360-99, 3d.19h.28m
  default: 
    user-filters: 45-0, never
    easylist: 66055-1011, 3d.19h.32m
    easyprivacy: 26830-10426, 3d.19h.31m
    plowe-0: 3687-886, 7d.22h.16m
    ublock-abuse: 74-1, 3d.19h.27m
    ublock-badware: 4077-290, 3d.19h.26m
    ublock-filters: 30605-3523, 3d.19h.23m
    ublock-privacy: 211-44, 3d.19h.25m
    ublock-quick-fixes: 160-12, 1d.59m
    ublock-unbreak: 1762-102, 3d.19h.24m
    urlhaus-1: 7860-1, 1d.58m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 63 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 25 redacted]
hostRuleset: 
  added: [array of 96 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  allReadyAfter: 1055 ms (selfie)
  maxAssetCacheWait: 681 ms
popupPanel: 
  blocked: 23
  no-popups: true
  blockedDetails: 
    waaw.to: 3
    addthis.com: 1
    apprefaculty.pro: 1
    buyseoblog.com: 1
    condolencessumcomics.com: 1
    disqus.com: 5
    easyads28.mobi: 1
    realsrv.com: 1
    rusenov.com: 1
    tagbom.com: 1
    viglink.com: 2
    yadro.ru: 1
    yandex.ru: 2
    yomeno.xyz: 1
    your-notice.com: 1
```
</details>

**Comment by mapx-** [comment]
You didn't:
`I forced an update of my filter lists`

fixed yesterday
