### ISSUE TITLE
rtxkeeda.com: detection

### ISSUE THREAD

**Issue by shrimplark** [uBlockOrigin/uAssets#12903]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rtxkeeda.com/wp/as-crackdown-looms-south-koreas-defiant-crypto-fans-dig-in/`

### Category

detection

### Describe the issue

ublock origin gets detected on the page that opens after clicking 'Direct Download APK From A2ZAPK'. I'm using all default host lists except a few custom cosmetic filters for other sites. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 87337
  cosmetic: 82374
  scriptlet: 19090
  html: 642
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52159-3005, 8h.2m
    adguard-social: 16858-1107, 8h.2m
  default: 
    user-filters: 183-0, never
    ublock-filters: 31505-271, 8h.2m
    ublock-badware: 4097-3, 8h.2m
    ublock-privacy: 217-1, 8h.2m
    ublock-abuse: 74-0, 8h.2m
    ublock-unbreak: 1779-0, 8h.2m
    ublock-quick-fixes: 167-0, 8h.2m
    adguard-mobile: 7596-172, 8h.5m
    easylist: 66286-24580, 8h.2m
    easyprivacy: 26858-587, 8h.2m
    urlhaus-1: 7870-1, 8h.2m
    plowe-0: 3682-3, 8h.2m
filterset (user): [array of 183 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2496 ms (selfie)
  maxAssetCacheWait: 758 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    a-ads.com: 1
    a2zapk.com: 3
    cloudflareinsights.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
There is no download on the page you linked here.

**Comment by stephenhawk8054** [comment]
> There is no download on the page you linked here.

The original site is `a2zapk.com`, for example:

`https://a2zapk.com/1213778-onkyo-hf-player-2-10-0-full-mod-arm64-v8a-a2z.html`

But I can't reproduce the anti-adblock.

**Comment by JobcenterTycoon** [comment]
Works fine for me too
