### ISSUE TITLE
flashx.to [Pop-up] [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1291]
URL(s) where the issue occurs

`https://www.flashx.to/o3vyoqzlgtck.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Anti-adblock.

**Comment by okiehsch** [comment]
This website has always been buggy on my end, so I would like to know if the updated fix works fine.
