### ISSUE TITLE
babiato.co: detection

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#12911]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://babiato.co/`

### Category

detection

### Describe the issue

AdBlock Detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/95934994/164781680-dad7a5eb-4465-4b6e-8737-4337977a2b51.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 81971
  cosmetic: 43678
  scriptlet: 16762
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1924-0, 7h.31m
    easylist: 66265-57, 1d.4h.35m
    easyprivacy: 26858-126, 1d.4h.34m
    plowe-0: 3682-804, 5d.6h.37m
    ublock-abuse: 74-0, 5d.6h.37m
    ublock-badware: 4092-93, 1d.22h.58m
    ublock-filters: 30836-109, 1m
    ublock-privacy: 211-2, 5d.6h.37m
    ublock-quick-fixes: 177-0, 1m
    ublock-unbreak: 1763-42, 1d.4h.33m
    urlhaus-1: 7919-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 151 ms (selfie)
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    babiato.co: 1
    cloudflareinsights.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Enable the list "uBlock filters – Annoyances".
Open ublock's dashboard, go to the "Filter lists" tab, scroll to "Annoyance", click to expand, enable "uBlock filters – Annoyances", then click "Update now".

**Comment by zeref-dragneel** [comment]
> Enable the list "uBlock filters – Annoyances". Open ublock's dashboard, go to the "Filter lists" tab, scroll to "Annoyance", click to expand, enable "uBlock filters – Annoyances", then click "Update now".

It works, thank you
