### ISSUE TITLE
wiadomosci.wp.pl: ads

### ISSUE THREAD

**Issue by jangromadowski** [uBlockOrigin/uAssets#12913]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wiadomosci.wp.pl/gdynia-w-pazurach-smoka-chinskie-oczy-i-uszy-w-porcie-pod-szczegolnym-nadzorem-6761005011180320a`

### Category

ads

### Describe the issue

I can't get rid of the ads on this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 43866
  cosmetic: 115621
  scriptlet: 48631
  html: 852
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    urlhaus-1: null
  added: 
    https://alleblock.pl/alleblock/alleblock.txt: 94-0, 1d.19m
    https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 1d.18m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt: 9447-13, 1d.21m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_test.txt: 3-1, 1d.22m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt: 589-1, 1d.17m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25731-24, 2h.29m
    https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-1, 3d.4h.3m
    adguard-generic: 63913-4655, 3d.3h.58m
    adguard-annoyance: 52075-841, 3d.3h.57m
    adguard-social: 16844-856, 3d.3h.56m
  default: 
    user-filters: 5-0, never
    ublock-filters: 31157-3082, 3d.4h.1m
    ublock-badware: 4086-3, 3d.4h
    ublock-privacy: 213-0, 9d.11h.26m
    ublock-abuse: 74-1, 9d.11h.25m
    ublock-unbreak: 1775-1, 3d.3h.59m
    plowe-0: 3682-29, 3d.4h.4m
    POL-0: 7833-679, 1d.20m
    POL-2: 1276-115, 1d.23m
    ublock-quick-fixes: 167-13, 1d.16m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2892 ms (selfie)
  maxAssetCacheWait: 1647 ms
popupPanel: 
  blocked: 104
  blockedDetails: 
    wp.pl: 1
    adform.net: 5
    adnxs.com: 16
    amazon-adsystem.com: 1
    casalemedia.com: 5
    connectad.io: 10
    criteo.com: 6
    criteo.net: 4
    facebook.com: 1
    facebook.net: 1
    gemius.pl: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    indexww.com: 5
    naanalle.pl: 5
    pubmatic.com: 10
    pushpushgo.com: 1
    rubiconproject.com: 6
    sharethrough.com: 15
    smartadserver.com: 9
```
</details>

**Comment by Procyon-b** [comment]
I don't see ads.
Check you user filters. You can disable them for a test by unchecking "My filters" in the "Filter lists" tab (and click "Apply changes")

**Comment by stephenhawk8054** [comment]
I can't see any ads. Can you force update the filter lists and if the issue still persists, can you take a screenshot of the page?

**Comment by P-o-R-t-v-i-n-e** [comment]
detection
<details>
<summary>Screenshot(s)</summary>

![2022-04-23_112631](https://user-images.githubusercontent.com/104250631/164886813-7ff64764-3a10-45fb-92f9-00f0af45c420.png)
</details>

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 1090
  cosmetic: 6619
  scriptlet: 111
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    ublock-filters: null
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-unbreak: null
    ublock-quick-fixes: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    RUS-0: null
  added: 
    POL-0: 7828-8, 19m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 156 ms (selfie)
  maxAssetCacheWait: 36 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    adform.net: 5
    amazon-adsystem.com: 1
    doubleclick.net: 2
    smartadserver.com: 9
```
</details>

**Comment by P-o-R-t-v-i-n-e** [comment]
detection
<details>
<summary>Screenshot(s)</summary>

![2022-04-23_112631](https://user-images.githubusercontent.com/104250631/164887296-0d76c865-05ff-4b0e-959f-48e0d2bc7375.png)
</details>
<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 13084
  cosmetic: 15036
  scriptlet: 16832
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    RUS-0: null
  added: 
    POL-0: 7828-15, 35m
  default: 
    ublock-filters: 30859-30, 3m
    ublock-badware: 4093-3, 3m
    ublock-privacy: 212-0, 3m
    ublock-abuse: 74-0, 3m
    ublock-unbreak: 1766-0, 3m
    ublock-quick-fixes: 177-0, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  uiFlavor: classic
supportStats: 
  allReadyAfter: 154 ms (selfie)
  maxAssetCacheWait: 200 ms
popupPanel: null
```
</details>

**Comment by Procyon-b** [comment]
This is caused by filters in `POL-0`.
Try these filter:
```
wiadomosci.wp.pl#@#[class^="advertisement"]
wiadomosci.wp.pl#@#body > div:nth-of-type(1)[style^="display: block;"]:not(#page)
```

You should also re-enable these lists:
```
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
```

**Comment by P-o-R-t-v-i-n-e** [comment]
Yes, it works.
@MajkiIT

@ryanbr 
generichide
<details>
<summary>Cookies</summary>

![2022-04-23_182503](https://user-images.githubusercontent.com/104250631/164912520-e257c9da-2c11-49ee-b345-847808bb98ad.png)
</details>

**Comment by krystian3w** [comment]
fyi @olegwukr

**Comment by jangromadowski** [comment]
I did everything according to the instructions. It still does not work.

**Comment by stephenhawk8054** [comment]
> I did everything according to the instructions. It still does not work.

Which instructions?

**Comment by jangromadowski** [comment]
`[wiadomosci.wp.pl#@#](http://wiadomosci.wp.pl/#@#)[class^="advertisement"]
[wiadomosci.wp.pl#@#body](http://wiadomosci.wp.pl/#@#body) > div:nth-of-type(1)[style^="display: block;"]:not(#page)

You should also re-enable these lists:

    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null`

**Comment by stephenhawk8054** [comment]
Can you copy your troubleshooting information here after adjusting?

**Comment by krystian3w** [comment]
On my side help refresh after detection and no clear cookies - so rare clear cookies if 99% ads are back but on once on page.

**Comment by ryanbr** [comment]
@P-o-R-t-v-i-n-e which generichide?

**Comment by P-o-R-t-v-i-n-e** [comment]
@ryanbr 
 `https://www.wp.pl/` & `https://www.o2.pl/`
<details>
<summary>Cookies</summary>

![2022-04-23_182503](https://user-images.githubusercontent.com/104250631/164912520-e257c9da-2c11-49ee-b345-847808bb98ad.png)
![2022-04-23_182503](https://user-images.githubusercontent.com/104250631/164912802-cf74a5c7-3520-4365-b1ee-87a2c30afd5d.png)
</details>


<details>
<summary>generichide ~> Quick fixes</summary>

![2022-04-28_072009](https://user-images.githubusercontent.com/104250631/165676288-b4fa04c3-95fa-4dc3-bf25-fd69fee35462.png)
</details>
