### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by hsingh1754** [uBlockOrigin/uAssets#12914]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

Still can see ads after ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 80999
  cosmetic: 42541
  scriptlet: 16561
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66131-51, 2d.15h.18m
    easyprivacy: 26845-121, 2d.15h.17m
    plowe-0: 3684-808, 11d.5h.30m
    ublock-abuse: 74-0, 2d.11h.38m
    ublock-badware: 4082-92, 2d.15h.16m
    ublock-filters: 30653-106, 2d.15h.15m
    ublock-privacy: 212-2, 2d.11h.35m
    ublock-quick-fixes: 166-0, 11h.36m
    ublock-unbreak: 1762-42, 2d.15h.14m
    urlhaus-1: 7870-1, 11h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 98 ms (selfie)
  maxAssetCacheWait: 65 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    doubleverify.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 2
    sentry.io: 2
    serving-sys.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues?q=twitch.tv

Try the solutions here https://github.com/pixeltris/TwitchAdSolutions/#twitchadsolutions
