### ISSUE TITLE
repo.hackyouriphone.org: detection

### ISSUE THREAD

**Issue by haz255** [uBlockOrigin/uAssets#12924]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [x] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://repo.hackyouriphone.org/onlinenotify`

### Category

detection

### Describe the issue

d

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 105974
  cosmetic: 54031
  scriptlet: 35251
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 107d.19h.41m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 23h.7m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25731-28, 2d.23h.22m
    FRA-0: 27510-39, 2d.23h.24m
    ara-0: 2566-9, 2d.23h.23m
  default: 
    user-filters: 0-0, never
    easylist: 66162-279, 2d.23h.29m
    easyprivacy: 26846-445, 2d.23h.28m
    plowe-0: 3687-816, 8d.3h.4m
    ublock-abuse: 74-2, 11d.5h.6m
    ublock-badware: 4092-100, 2d.23h.26m
    ublock-filters: 30678-3326, 2d.23h.27m
    ublock-privacy: 206-2, 11d.5h.5m
    ublock-quick-fixes: 171-1, 23h.8m
    ublock-unbreak: 1763-43, 2d.23h.25m
    urlhaus-1: 8442-1, 23h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 34 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
It's because of the filter `hackyouriphone.org##+js(noeval)` in your custom list:

`https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt`

You should test without external filter lists first.

**Comment by iam-py-test** [comment]
> - [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> - [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

You have to follow this BEFORE reporting an issue. It saves everyone time. Don't just check all the boxes because you have to 
Luckily, you told the truth:
> - [X]  I did not answer truthfully to **all** the above checkpoints
