### ISSUE TITLE
amoyshare.com: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#12923]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amoyshare.com/free-youtube-downloader/?v=ac6ed-www.youtube.com%2Fwatch%3Fv%3DigzEuIMw4Uo&t=youtube`

### Category

ads

### Describe the issue

ads.... see screenshot 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-23 145926](https://user-images.githubusercontent.com/100969549/164895591-4f97681f-a19f-49bf-a263-2d8401f67836.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 369823
  cosmetic: 304858
  scriptlet: 39305
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://abl.arapurayil.com/filters/main.txt: 150471-2, 16h.52m
    https://filters.adtidy.org/extension/ublock/filters/6_optimized.txt: 5187-121, 1d.18h.52m
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 166-0, 1d.16h.51m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-28, 1d.16h.52m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6081-72, 4d.4h.24m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-92, 6d.17h.35m
    https://winhelp2002.mvps.org/hosts.txt: 8730-1641, 3d.1h.15m
    ALB-0: 268-1, 16h.59m
    BGR-0: 1116-14, 3d.1h.18m
    CHN-0: 28267-6527, 1d.20h.51m
    CZE-0: 832-4, 16h.58m
    EST-0: 450-2, 16h.56m
    FIN-0: 1672-1, 1d.20h.57m
    FRA-0: 27512-5030, 1d.20h.56m
    GRC-0: 1002-3, 1d.18h.51m
    HUN-0: 2158-28, 16h.55m
    IDN-0: 8999-173, 1d.20h.50m
    IRN-0: 1340-18, 1d.20h.49m
    ISL-0: 193-1, 3d.1h.16m
    ISR-0: 1617-18, 16h.54m
    [34 lists not shown]: [too many]
  default: 
    user-filters: 96-1, never
    DEU-0: 5631-2393, 16h.57m
    easylist: 66284-15668, 1d.19h.26m
    easyprivacy: 26859-14848, 1d.19h
    plowe-0: 3682-3012, 5d.16h.10m
    ublock-abuse: 74-59, 6d.40m
    ublock-badware: 4092-679, 1d.18h.56m
    ublock-filters: 30704-3969, 1d.18h.55m
    ublock-privacy: 211-81, 6d.36m
    ublock-quick-fixes: 171-12, 16h.45m
    ublock-unbreak: 1763-132, 1d.18h.54m
    urlhaus-1: 8442-1062, 16h.44m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 14 redacted]
hostRuleset: 
  added: [array of 12 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1788 ms
  maxAssetCacheWait: 1142 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    addthis.com: 1
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`amoyshare.com##.game-poster`

@ryanbr
