### ISSUE TITLE
fedex.com: breakage

### ISSUE THREAD

**Issue by hisXLNC** [uBlockOrigin/uAssets#12922]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fedex.com/fedextrack/system-error?trknbr=776650242533`

### Category

breakage

### Describe the issue

with ublock enabled tracking returns "Unfortunately we are unable to retrieve your tracking results at this time. Please try again later. "

with ublock disabled it correctly returns tracking details

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81759
  cosmetic: 42646
  scriptlet: 16666
  html: 639
listset (total-discarded, last updated): 
  default: 
    user-filters: 18-4, never
    ublock-filters: 31419-31, 17h.51m
    ublock-badware: 4097-3, 12h.33m
    ublock-privacy: 216-0, 5d.19h.3m
    ublock-abuse: 74-0, 5d.15h.2m
    ublock-unbreak: 1774-0, 3d.16h.5m
    easylist: 66339-606, 17h.52m
    easyprivacy: 26861-577, 10h.17m
    urlhaus-1: 8442-1, 12h.32m
    plowe-0: 3682-3, 6d.15h.28m
    ublock-quick-fixes: 171-0, 17h.50m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 585 ms (selfie)
  maxAssetCacheWait: 524 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    fedex.com: 3
    adobedtm.com: 2
    demdex.net: 2
    google.com: 4
    googletagmanager.com: 1
    optimizely.com: 1
    qualtrics.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Does `@@||fedex.com/akam/13/` works?

**Comment by hisXLNC** [comment]
sorry i havent dabbled deeply into ublock origin as it works great out the box. am i supposed to add that line to trusted sites?

if so, no it doesnt work

**Comment by Procyon-b** [comment]
Open ublock's dashboard. Go to the "My filters" tab and copy the filter above in a blank line. Then click "Apply changes".

**Comment by hisXLNC** [comment]
> Open ublock's dashboard. Go to the "My filters" tab and copy the filter above in a blank line. Then click "Apply changes".

thanks. just did that but the site is still broken.

**Comment by Procyon-b** [comment]
We'll have to wait for someone else who can replicate your problem.

**Comment by Yuki2718** [comment]
Or else someone who doesn't care sharing tracking ID of his luggage.

**Comment by stephenhawk8054** [comment]
Can you check these:

1. Open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger)
2. In logger's search box, select `Blocked` and `Allowed`
3. Reload the page and do the steps to trigger the error
4. Click on this button at the top right:
![image](https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png)
5. Choose `Markdown` -> `Copy to clipboard` and paste here
