### ISSUE TITLE
kissanime.ac [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1292]
URL(s) where the issue occurs

`https://kissanime.ac/Anime/Space-Battleship-Yamato-2-Dub.33607/Episode-012?id=126685`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
I can not play the video

`https://kissanime.ac/Anime/3x3-Eyes-Seima-Densetsu/OVA-001?id=30064`
