### ISSUE TITLE
polsat sport.pl

### ISSUE THREAD

**Issue by lorak9912** [uBlockOrigin/uAssets#12935]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.polsatsport.pl/wiadomosc/2022-04-22/motogp-grand-prix-portugalii-transmisja-na-polsatsport-plll/?ref=slider

### Describe the issue

Wyłącz oprogramowanie do blokowania reklam, aby obejrzeć ten materiał

### uBlock Origin version

1.42.4

### Browser name and version

Opera 85.0.4341.75

### Settings

z

**Comment by okiehsch** [comment]
Fixed in the regional list.
Enable the `POL: Oficjalne polskie filtry przeciwko alertom o Adblocku` list.
