### ISSUE TITLE
fmoviesto.cc: ads

### ISSUE THREAD

**Issue by AriaMoradi** [uBlockOrigin/uAssets#12936]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmoviesto.cc/watch-tv/house-2004-full-39423.4882498`

### Category

ads

### Describe the issue

displays ads "by mgbid" 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8719233/164969738-f7f92258-63f6-4b4b-a7ef-ca7742ca0a3a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81722
  cosmetic: 42626
  scriptlet: 16596
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66288-51, 1d.23h.22m
    easyprivacy: 26859-121, 1d.23h.18m
    plowe-0: 3687-808, 11d.4h.25m
    ublock-abuse: 74-0, 1d.19h.16m
    ublock-badware: 4093-93, 1d.23h.19m
    ublock-filters: 30696-105, 1d.23h.20m
    ublock-privacy: 212-2, 1d.19h.17m
    ublock-quick-fixes: 178-0, 1h.20m
    ublock-unbreak: 1763-42, 1d.23h.21m
    urlhaus-1: 8473-1, 10h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1293 ms (selfie)
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    addthis.com: 1
    facebook.com: 1
    googletagmanager.com: 2
    soaheeme.net: 1
    untimburra.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The site embeds frames with `https://mgbid.net/embed/` I think `mgbid.net` can be considered as an ads domain, but I haven't checked in details yet.

@ryanbr What do you think?

**Comment by okiehsch** [comment]
It is an ad domain.

**Comment by AriaMoradi** [comment]
and it was registered very recently. 1st of April
