### ISSUE TITLE
tiktok.com: breakage

### ISSUE THREAD

**Issue by MisterSheeple** [uBlockOrigin/uAssets#12931]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tiktok.com/`

### Category

breakage

### Describe the issue

Actions such as likes and follows do not work when uBO is enabled. It will briefly show that you have liked a video after clicking the button, but after about 5 seconds, the button will revert.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81696
  cosmetic: 42627
  scriptlet: 16574
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66284-51, 1d.23h.2m
    easyprivacy: 26843-122, 4d.30m
    plowe-0: 3682-804, 6d.7h.45m
    ublock-abuse: 74-0, 6d.7h.41m
    ublock-badware: 4094-93, 1d.23h.5m
    ublock-filters: 30674-107, 1d.23h.4m
    ublock-privacy: 211-2, 6d.7h.40m
    ublock-quick-fixes: 177-0, 2h.30m
    ublock-unbreak: 1763-42, 1d.23h.3m
    urlhaus-1: 8473-1, 2h.31m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 283 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    tiktokv.com: 1
```
</details>

**Comment by krystian3w** [comment]
Broken with disabled all lists

**Comment by Yuki2718** [comment]
On my end it's brokne on Firefox even with uBO disalbed, but works fine on Chrome with uBO enabled. Likely to be either a site or browser issue.

**Comment by Daxy7** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19009#issuecomment-1925218069

> Seems that something changed in tiktok code and `##+js(aeld, visibilitychange, pagehide)` no longer keeps the video playing in a new tab. test link:
> ```
> https://www.tiktok.com/@jadafacer/video/82714842335199232
> ```
> 
We can either remove the filter now in uBO Annoyances as it does nothing or replace it
