### ISSUE TITLE
2114.hdvideosnet.com: ads

### ISSUE THREAD

**Issue by LittleBenjiBoy** [uBlockOrigin/uAssets#12934]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://2114.hdvideosnet.com/ggl26_lnk17.html?ymid=0b406d2bdccc57e39bda5042273e649b&zoneid=4052874&sourceid=577539&rs=1&cnt=2114`

### Category

ads

### Describe the issue

This is an intrusive ad link that generates a new link every time it is refreshed and asks for notification permissions. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 83088
  cosmetic: 24439
  scriptlet: 16621
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 7592-32, 2d.23h.34m
    easylist: 66260-24075, 2d.23h.32m
    easyprivacy: 26857-130, 2d.23h.31m
    plowe-0: 3682-891, 2d.23h.30m
    ublock-abuse: 74-0, 2d.23h.28m
    ublock-badware: 4077-93, 2d.23h.26m
    ublock-filters: 30781-341, 2d.23h.25m
    ublock-privacy: 212-3, 2d.23h.24m
    ublock-quick-fixes: 179-0, now
    ublock-unbreak: 1768-44, 2d.23h.17m
    urlhaus-1: 8432-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 756 ms (selfie)
  maxAssetCacheWait: 245 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Your given link appears like this on my side

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/164958513-e84db5ee-0426-444f-870f-94c6709ef181.png)

</details>

Can you describe the steps to reproduce in more details?

**Comment by LittleBenjiBoy** [comment]
Hi @stephenhawk8054,

Yes, you need to have Chrome opened in a normal window. In a non-incognito window, I will get a request to receive notifications from this link.

Here is an image of what I get (opened on Windows 10 Chrome):
![image](https://user-images.githubusercontent.com/43734617/164989836-8a85ce95-3c5f-409f-b3b8-9239fea4ed96.png)

This link popped up when I opened a link on a website with "Open in new tab in group", which opened a link I did not intend to open. It seemed like they had this link embedded into the link that I was trying to open. 

Thank you,
Benjamin

**Comment by LittleBenjiBoy** [comment]
I expect uBlock Origin to replace this webpage with a warning like this:
![image](https://user-images.githubusercontent.com/43734617/164990351-a637b955-9f25-47cd-9444-e6bdc393b76d.png)

**Comment by okiehsch** [comment]
>  when I opened a link on a website

Could you provide a link to that website.

**Comment by okiehsch** [comment]
https://malwaretips.com/blogs/remove-hdvideosnet-com/

I will add the domain to the badware list.

**Comment by LittleBenjiBoy** [comment]
> > when I opened a link on a website
> 
> Could you provide a link to that website.

Yes, I can, but this was on a NSFW website. I cannot reproduce this link opening again with uBlock Origin enabled, but I was able to reproduce it with uBlock Origin disabled. I was only able to reproduce this ad link opening on Chrome mobile and not on Windows 10 with uBlock Origin disabled. When I try to open the link on Windows 10, it opens the direct link to where I intended to go, and not that ad link.

**Comment by okiehsch** [comment]
> Yes, I can, but this was on a NSFW website. I cannot reproduce this link opening again with uBlock Origin enabled, but I was able to reproduce it with uBlock Origin disabled.

OK, I added site as requested in https://github.com/uBlockOrigin/uAssets/issues/12934#issuecomment-1107890726
