### ISSUE TITLE
beermoneyforum.com: breakage

### ISSUE THREAD

**Issue by FedeFluork** [uBlockOrigin/uAssets#12942]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.beermoneyforum.com/conversations/`

### Category

breakage

### Describe the issue

The extension is blocking the popup apparition for example in the text editor for replying (when clicking on a button that needs it like URL)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 87342
  cosmetic: 49899
  scriptlet: 16559
  html: 639
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31288-31, 2d.21h.7m
    ublock-badware: 4098-3, 2d.21h.4m
    ublock-privacy: 217-0, 2d.21h.3m
    ublock-abuse: 74-0, 2d.20h.57m
    ublock-unbreak: 1774-0, 2d.20h.56m
    ublock-quick-fixes: 178-0, 7h.22m
    easylist: 66285-608, 2d.20h.54m
    easyprivacy: 26859-579, 2d.20h.53m
    urlhaus-1: 8432-1, 7h.21m
    plowe-0: 3682-3, 2d.20h.51m
    ITA-0: 12944-9, 7h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 767 ms (selfie)
  maxAssetCacheWait: 685 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    beermoneyforum.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by FedeFluork** [comment]
The issue is resolved when disabling the cosmetic filter (third button in the extension menu, middle one)

**Comment by JobcenterTycoon** [comment]
@FedeFluork does `beermoneyforum.com#@#.is-active.overlay-container` unbreaks all? I only can reproduce on the chat (can’t open the profile overlay) but all reply functions works fine for me

If yes try `beermoneyforum.com##.is-active.overlay-container:has(div[data-position] > center > a)` for the overlay ad and look if it works fine without breakage
