### ISSUE TITLE
rok.guide: ads

### ISSUE THREAD

**Issue by imhornyaf69** [uBlockOrigin/uAssets#12943]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rok.guide/alexander-the-great/`

### Category

ads

### Describe the issue

There is a betting website ad on the top banner of the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://user-images.githubusercontent.com/104329539/165000971-1d95ef4f-3e22-4bc9-b763-dd9c3b10607d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81900
  cosmetic: 42637
  scriptlet: 16708
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 6h.38m
  default: 
    user-filters: 0-0, never
    easylist: 66339-51, 2d.7h.7m
    easyprivacy: 26861-121, 2d.3h.5m
    plowe-0: 3682-804, 2d.23h.2m
    ublock-abuse: 74-0, 10d.3h.8m
    ublock-badware: 4098-93, 2h.37m
    ublock-filters: 30827-106, 2d.3h.4m
    ublock-privacy: 209-2, 9d.2h.29m
    ublock-quick-fixes: 177-0, 1d.2h.23m
    ublock-unbreak: 1767-43, 2h.36m
    urlhaus-1: 8473-1, 1d.2h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 900 ms (selfie)
  maxAssetCacheWait: 517 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    rok.guide: 1
    facebook.com: 2
    google.com: 1
    monu.delivery: 1
    onesignal.com: 1
    wp.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Some of them looks like self-promotion

```
rok.guide##.code-block
rok.guide##.stake-bet
rok.guide##[href^="https://bstk.me"]
```

@ryanbr
