### ISSUE TITLE
tvlicensing.co.uk: breakage

### ISSUE THREAD

**Issue by billysielu** [uBlockOrigin/uAssets#12945]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tvlicensing.co.uk/check-if-you-need-one/topics/cancellations-and-refunds-top7`

### Category

breakage

### Describe the issue

This is the website of TV Licensing - everyone in the UK has to pay for a license to watch live TV (yes really).
This is an FAQ page in accordion format.
Expected: Clicking a question should expand the answer. 
Actual: Clicking a question does not expand the answer.
Also there is content missing at the top of the page. See screenshot. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/59173811/165045843-da8f6298-d30f-46f1-92cd-b4acacc25f41.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81732
  cosmetic: 42698
  scriptlet: 16575
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 43-2, never
    easylist: 66376-51, 15h.45m
    easyprivacy: 26858-121, 3d.16h.43m
    plowe-0: 3687-808, 11d.15h
    ublock-abuse: 74-0, 1d.14h.9m
    ublock-badware: 4094-93, 3d.16h.42m
    ublock-filters: 30674-110, 3d.16h.44m
    ublock-privacy: 212-2, 1d.14h.8m
    ublock-quick-fixes: 178-0, 19h.41m
    ublock-unbreak: 1763-42, 3d.16h.41m
    urlhaus-1: 8432-1, 19h.40m
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 262 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    webtrends-optimize.com: 3
    webtrends.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
`@@||webtrends.com/js/webtrends.min.js$script,domain=tvlicensing.co.uk`

**Comment by okiehsch** [comment]
````
@@||c.webtrends-optimize.com/acs/common/js/5.1/common.js$script,domain=tvlicensing.co.uk
@@||c.webtrends-optimize.com/acs/common/js/5.1/wt_lib.js$script,domain=tvlicensing.co.uk
@@||ots.webtrends-optimize.com/ots/ots/*$xhr,domain=tvlicensing.co.uk
````
should work for the missing content part of the issue.

**Comment by stephenhawk8054** [comment]
> ```
> @@||c.webtrends-optimize.com/acs/common/js/5.1/common.js$script,domain=tvlicensing.co.uk
> @@||c.webtrends-optimize.com/acs/common/js/5.1/wt_lib.js$script,domain=tvlicensing.co.uk
> @@||ots.webtrends-optimize.com/ots/ots/*$xhr,domain=tvlicensing.co.uk
> ```
> 
> should work for the missing content part of the issue.

Hmmm... weird, I have to allow one more on my side to see those connections:

```
@@||c.webtrends-optimize.com/acs/accounts/$script,domain=tvlicensing.co.uk
```

**Comment by okiehsch** [comment]
You are right, don't know how I missed that earlier.

**Comment by billysielu** [comment]
Looking good now. Thanks all.
