### ISSUE TITLE
videonuz.ensonhaber.com: breakage

### ISSUE THREAD

**Issue by mss1451** [uBlockOrigin/uAssets#12955]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://videonuz.ensonhaber.com/izle/sanliurfada-seker-yuklu-tir-devrilince-etrafa-sacilanlari-yagmaladilar`

### Category

breakage

### Describe the issue

`div` element with `id="video"` is blank. The video player appears for a split of a second and then disappears.

Disabling `EasyList` fixes the problem. Enabling or disabling `TUR: AdGuard Turkish` has no effect.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81840
  cosmetic: 42618
  scriptlet: 16530
  html: 638
listset (total-discarded, last updated): 
  removed: 
    TUR-0: null
  default: 
    user-filters: 2-0, never
    ublock-filters: 31246-31, 4d.1h.19m
    ublock-badware: 4098-3, 4d.1h.18m
    ublock-privacy: 217-0, 3d.1h.16m
    ublock-abuse: 74-0, 3d.1h.15m
    ublock-unbreak: 1774-0, 4d.1h.17m
    easylist: 66268-607, 4d.1h.16m
    easyprivacy: 26858-577, 4d.1h.15m
    urlhaus-1: 8612-0, 16h.17m
    plowe-0: 3678-3, 2d.21h.35m
    ublock-quick-fixes: 177-0, 16h.16m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1010 ms (selfie)
  maxAssetCacheWait: 824 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    ensonhaber.com: 1
    alexametrics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 3
```
</details>

**Comment by Alex-302** [comment]
done
