### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by syborgxx** [uBlockOrigin/uAssets#12959]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/gp/video/detail/B09D42S7TF/ref=atv_dp_season_select_s7`

### Category

ads

### Describe the issue

imdb pops up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://www.amazon.com/gp/video/detail/B09D42S7TF/ref=atv_dp_season_select_s7
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 159657
  cosmetic: 141143
  scriptlet: 35363
  html: 646
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-1, 3d.6h.41m
    adguard-generic: 64053-5458, 3d.2h.15m
    adguard-mobile: 7650-231, 3d.2h.16m
    adguard-spyware: 26252-1370, 3d.2h.14m
    adguard-spyware-url: 570-4, 3d.2h.13m
    block-lan: 43-0, 1d.4m
    curben-phishing: 15247-2, 3h.38m
    curben-pup: 263-0, 3h.37m
    adguard-annoyance: 52220-4541, 3d.2h.11m
    adguard-social: 16915-1647, 3d.2h.10m
    fanboy-thirdparty_social: 68-1, 3h.42m
    fanboy-annoyance: 70649-59281, 3h.40m
    fanboy-cookiemonster: 31745-15065, 3h.41m
    fanboy-social: 23329-13593, 3d.2h.9m
    ublock-annoyances: 4354-7, 3d.2h.12m
    dpollock-0: 10364-1637, 7d.4h.2m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31289-284, 3d.2h.21m
    ublock-badware: 4097-3, 3d.2h.20m
    ublock-privacy: 217-1, 1d.3h.29m
    ublock-abuse: 74-0, 1d.3h.28m
    ublock-unbreak: 1777-0, 3d.2h.19m
    easylist: 66350-24867, 3d.2h.18m
    easyprivacy: 26861-10776, 3d.2h.17m
    urlhaus-1: 9144-0, 3h.39m
    plowe-0: 3682-348, 8d.23h.59m
    ublock-quick-fixes: 180-0, 3h.36m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1471 ms (selfie)
  maxAssetCacheWait: 972 ms
popupPanel: 
  blocked: 81
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    amazon.com: 81
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot the popup?
