### ISSUE TITLE
racedepartment.com: detection

### ISSUE THREAD

**Issue by kyranbrazier** [uBlockOrigin/uAssets#12956]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.racedepartment.com/`

### Category

detection

### Describe the issue

Website detects uBlock is installed and presents a popup and highlights the page. This has to be dismissed everytime a page is opened.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82470
  cosmetic: 42654
  scriptlet: 16695
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 66355-51, 2d.2h.33m
    easyprivacy: 26861-121, 2d.2h.32m
    plowe-0: 3682-804, 6d.12h.34m
    ublock-abuse: 74-0, 6d.12h.33m
    ublock-badware: 4093-93, 2d.2h.36m
    ublock-filters: 30825-106, 2d.2h.35m
    ublock-privacy: 211-2, 6d.12h.32m
    ublock-quick-fixes: 178-0, 15m
    ublock-unbreak: 1766-42, 2d.2h.34m
    urlhaus-1: 9149-0, 14m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 153 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    racedepartment.com: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    quantserve.com: 1
    yieldlove.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
racedepartment.com##+js(aeld, DOMContentLoaded, removeEventListener)
racedepartment.com##+js(aeld, load, removeEventListener)
```

**Comment by kyranbrazier** [comment]
Perfect - thank you
