### ISSUE TITLE
samuraiscan.com: detection

### ISSUE THREAD

**Issue by XdarkaltX** [uBlockOrigin/uAssets#12958]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://samuraiscan.com/`

### Category

detection

### Describe the issue

buenas noches espero que puedan ayudar desactivar ese mensaje 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 85586
  cosmetic: 47363
  scriptlet: 16937
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 66355-51, 2d.5h.41m
    easyprivacy: 26861-121, 2d.5h.40m
    plowe-0: 3678-805, 2d.5h.39m
    spa-0: 3875-34, 18h.31m
    spa-1: 4395-168, 2d.22h.39m
    ublock-abuse: 74-0, 2d.5h.37m
    ublock-badware: 4098-93, 2d.5h.35m
    ublock-filters: 30875-157, 2d.5h.34m
    ublock-privacy: 212-2, 2d.5h.33m
    ublock-quick-fixes: 180-0, 1h.30m
    ublock-unbreak: 1766-43, 2d.4h.44m
    urlhaus-1: 9149-0, 1h.29m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1019 ms (selfie)
  maxAssetCacheWait: 339 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed already: [https://github.com/uBlockOrigin/uAssets/issues/12954](https://github.com/uBlockOrigin/uAssets/issues/12954). Can you force update the filter lists?

**Comment by krystian3w** [comment]
I suppose maybe someone must write wiki for Spain native speakers.

If all countries still poor know English then may no help translate mechanism in Chrome/Edge/Vivaldi.

**Comment by advertblocker** [comment]
`https://samuraiscan.com/` => right-click drag/select ctrl+u
