### ISSUE TITLE
List-KR subscription URL issue

### ISSUE THREAD

**Issue by piquark6046** [uBlockOrigin/uAssets#12953]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://github.com/List-KR/List-KR`

### Describe the issue

There is a problematic issue that administrator of them updates their website too fast to resolve if default update interval is 4 days.

https://github.com/List-KR/List-KR/issues/277
https://github.com/List-KR/List-KR/issues/236 
https://github.com/AdguardTeam/AdguardFilters/issues/108883#issuecomment-1107374239
https://listauthorschat.slack.com/archives/C010N14G4TF/p1650768976206329
https://listauthorschat.slack.com/archives/C010N14G4TF/p1650728939299509

Please change contentURL to the following URL:
```
https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt
```

### uBlock Origin version

1.42.4

### Browser name and version

Firefox Dev 100.0b9

### Settings

```
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 515
  cosmetic: 731
  scriptlet: 49
  html: 8
listset (total-discarded, last updated): 
  removed: 
    ublock-filters: null
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-unbreak: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    ublock-quick-fixes: null
  added: 
    https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt: 1310-7, 2d.2h.10m
  default: 
    user-filters: 0-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 100 ms (selfie)
  maxAssetCacheWait: 0 ms
```

### Notes

@piquark6046 is administrator of List-KR.

PS. If you want write permission of List-KR, please tell me.

**Comment by piquark6046** [comment]
@gorhill

**Comment by gorhill** [comment]
I have changed the URL, but also added CDN URLs to avoid getting in trouble with using GitHub as a CDN provider: <https://github.com/gorhill/uBlock/commit/792ef1186de5de8913ae5f5289b818652aac34ac>

**Comment by krystian3w** [comment]
Better no allow write access for random pepole, on my side check who repair KR pages in Quick Fixes and ask about add trial priveleges:

https://github.com/uBlockOrigin/uAssets/commits/master/filters/quick-fixes.txt

 p​p​s​s[.]kr
 y​g​o​s​u[.]com
 t​g​d[.]kr
 i​n​v​e​n[.]co[.]kr
 l​o​a​w​a[.]com

**Comment by JobcenterTycoon** [comment]
1 hour is pretty often, 24x more than the quick fixes filter list

> Better no allow write access for random pepole

Like undercover ad shield people lol. But https://github.com/List-KR/List-KR/blob/master/CONTRIBUTING.md is pretty clear

**Comment by krystian3w** [comment]
Maybe [piquark](https://github.com/piquark6046) asking in that way:

> I would be happy to correct the file myself every month or so if I had access to your " assets/assets.json"

Such a request is rather pointless, it generates an additional attack vector on the repository as someone does not enforce 2FA generated on a clean PC e.g. GNU/Linux in Live Mode.
