### ISSUE TITLE
ruutu.fi: detection

### ISSUE THREAD

**Issue by JellonaII** [uBlockOrigin/uAssets#12957]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ruutu.fi/`

### Category

detection

### Describe the issue

Ruutu.fi domain detects uBlock when you try to watch an stream, and tells you to shut it off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82130
  cosmetic: 42748
  scriptlet: 16738
  html: 643
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31565-30, now
    ublock-badware: 4108-3, now
    ublock-privacy: 217-0, now
    ublock-abuse: 74-0, now
    ublock-unbreak: 1778-0, now
    easylist: 66491-595, now
    easyprivacy: 26893-590, now
    plowe-0: 3679-3, now
    urlhaus-1: 8653-0, now
    ublock-quick-fixes: 180-0, now
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 197 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    ruutu.fi: 5
    brandmetrics.com: 1
    facebook.com: 5
    fwmrm.net: 2
    giosg.com: 4
    google-analytics.com: 11
    google.com: 2
    krxd.net: 3
    omtrdc.net: 3
    sentry.io: 7
    userreport.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
As this looks like requiring an account with phone number, we might need you to try and investigate it. Can you try adding this to [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters):

```
@@||ruutu.fi^$ghide
```

click `Apply changes` and test again?

---

If it doesn't work, can you copy the logger information with these steps:

1. Open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger)
2. In logger's search box, select `Blocked` and `Allowed`
3. Reload the page and do the steps to trigger the issue
4. Click on this button at the top right:
![image](https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png)
5. Choose `Table` at the top left -> `Markdown` at top middle -> `Copy to clipboard` at top right and paste here

Video: [https://www.youtube.com/watch?v=IHIz5rFnieg](https://www.youtube.com/watch?v=IHIz5rFnieg)

**Comment by Nojuuu** [comment]
@peace2000 Do you have account?

**Comment by peace2000** [comment]
@Nojuuu 

Yes I have an account. Works totally fine to me, the Finnish list handles those properly.

@JellonaII Enable the Finnish list, it should work and handle those ads.

**Comment by JellonaII** [comment]
Yeah... It works perfectly. I had the Finland list list disabled....
Thank you all very much with this one dumb-ass xD
