### ISSUE TITLE
[nsfw] bimbim.com: breakage

### ISSUE THREAD

**Issue by gene-pavlovsky** [uBlockOrigin/uAssets#12961]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bimbim.com/en/chat/NaomiRise`
or any other online model's page opened from the gallery on the home page `https://bimbim.com`

### Category

breakage

### Describe the issue

When first opening bimbim.com, uBlock Origin says it is blocked by the `||bimbim.com^` rule. After choosing to disable strict blocking either temporarily or permanently, the site opens. However, after choosing any of the online models from the gallery, their page opens but the video stream doesn't load. Several network requests are shown as blocked in uBlock's log, which I assume are essential to this website's operation. 

The `||bimbim.com rule^` comes from EasyList and seems to be too generic, affecting the entire website. By contrast, EasyList includes multiple separate rules for livejasmin.com (a site that is owned by the same company and is operating using mostly the same engine), those rules are more specific, and I assume they prevent ads from livejasmin but don't break the livejasmin site itself.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-04-26 at 09 33 44](https://user-images.githubusercontent.com/2841193/165246680-84fa8941-97a7-48dc-adb1-41eaac7dad19.png)

![Screenshot 2022-04-26 at 09 28 30](https://user-images.githubusercontent.com/2841193/165245624-4f663da1-a5d2-47ad-8c8d-6a374093030c.png)

![Screenshot 2022-04-26 at 09 35 14](https://user-images.githubusercontent.com/2841193/165246883-c9527b80-6aab-4443-9aff-c115f339a709.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82497
  cosmetic: 42759
  scriptlet: 16785
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66499-51, 15m
    easyprivacy: 26899-121, 15m
    plowe-0: 3679-805, 15m
    ublock-abuse: 74-0, 15m
    ublock-badware: 4104-93, 15m
    ublock-filters: 30987-107, 15m
    ublock-privacy: 212-2, 15m
    ublock-quick-fixes: 180-0, 15m
    ublock-unbreak: 1767-42, 15m
    urlhaus-1: 9017-0, 15m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 790 ms (selfie)
  maxAssetCacheWait: 373 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    bimbim.com: 3
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr Can you check it? Maybe it can be changed to `||bimbim.com^$third-party`?

**Comment by gene-pavlovsky** [comment]
Thanks
