### ISSUE TITLE
[nsfw] playdede.tv: popups

### ISSUE THREAD

**Issue by otkashix** [uBlockOrigin/uAssets#12963]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://playdede.tv/`

### Category

popups

### Describe the issue

It's a web where external multimedia (video) web embeds and links are inside. uBlock blocks almost everything, but some web and popups are shown, mostly of hentai and "Allow notification" webs.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 85432
  cosmetic: 47341
  scriptlet: 16916
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66339-51, 3d.18h.49m
    easyprivacy: 26861-121, 3d.18h.48m
    plowe-0: 3682-804, 7d.2h.13m
    spa-0: 3875-34, 9h.32m
    spa-1: 4390-168, 3d.18h.50m
    ublock-abuse: 74-0, 8d.3h.31m
    ublock-badware: 4093-93, 3d.18h.47m
    ublock-filters: 30836-156, 3d.18h.46m
    ublock-privacy: 211-2, 8d.3h.30m
    ublock-quick-fixes: 180-0, 9h.34m
    ublock-unbreak: 1763-43, 3d.18h.45m
    urlhaus-1: 9017-0, 9h.33m
filterset (user): [empty]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 325 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 10
  no-popups: true
  blockedDetails: 
    agaenteitor.com: 1
    koynvjwsunkgmxn.top: 1
    oakapsot.com: 8
```
</details
![Captura de pantalla 2022-04-26 161239](https://user-images.githubusercontent.com/36087508/165320045-f8196a40-73ab-4aae-b40b-f08a9ca32799.png)
![Captura de pantalla 2022-04-26 161339](https://user-images.githubusercontent.com/36087508/165320054-aa65a369-50d0-4548-a1b2-b8c123516612.png)
>

**Comment by otkashix** [comment]
I add some screenshots of some web are show
![Captura de pantalla 2022-04-26 161239](https://user-images.githubusercontent.com/36087508/165320303-bf41bd66-590d-4e30-a773-16c9fb40f975.png)
![Captura de pantalla 2022-04-26 161339](https://user-images.githubusercontent.com/36087508/165320306-bf1c6e63-51cf-4984-950e-369d74e0d66d.png)
n

**Comment by stephenhawk8054** [comment]
I fixed popup problem, but I can't reproduce the notification. Can you force update the filter lists in about 10 minutes?

**Comment by otkashix** [comment]
> I fixed popup problem, but I can't reproduce the notification. Can you force update the filter lists in about 10 minutes?

I explained my self wrong. What I meant is that web opens a Pop-up of webs that gives you the "Allow notification" thing.
I will force it in 10 min and tell you.

**Comment by otkashix** [comment]
Looks like now no Pop-ups are shown. Looks fixed. Thank you very much.
