### ISSUE TITLE
mstream.io: breakage

### ISSUE THREAD

**Issue by fabi321** [uBlockOrigin/uAssets#12976]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mstream.io/`

### Category

breakage

### Describe the issue

The entire content is not visible. After digging a bit deeper, I found out that the origin of this issue is probably in `Fanboy’s Annoyance`. Specifically it's the css selector `.push-wrap:not(body):not(html)` that blocks it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_20220427_080701](https://user-images.githubusercontent.com/42294590/165452244-65002ccb-78ba-404e-9ac8-dff5bd6a4d26.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 91195
  cosmetic: 107927
  scriptlet: 18079
  html: 643
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 70651-251, 23h.23m
    DEU-0: 5637-2, 7h.20m
  default: 
    user-filters: 33-6, never
    ublock-filters: 31456-41, 3d.3h.45m
    ublock-badware: 4102-3, 3d.3h.44m
    ublock-privacy: 217-0, 19h.22m
    ublock-abuse: 74-0, 19h.21m
    ublock-unbreak: 1777-0, 3d.3h.43m
    easylist: 66355-599, 3d.3h.42m
    easyprivacy: 26861-601, 3d.3h.41m
    urlhaus-1: 8483-0, 7h.19m
    plowe-0: 3682-3, 9d.4h.45m
    ublock-quick-fixes: 179-0, 3h.18m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 186 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`mstream.io#@#.push-wrap:not(body):not(html)`
