### ISSUE TITLE
igg-games.com: detection

### ISSUE THREAD

**Issue by Lunoxia** [uBlockOrigin/uAssets#12975]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://igg-games.com/`

### Category

detection

### Describe the issue

lorsque je rentre sur le site internet cela demande de desactiver adblock alors que j'utilise ublock mais ce problème est récent sur ce site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![inspectation gg game](https://user-images.githubusercontent.com/67620915/165407519-676c4845-0ff7-43ea-b896-18f6c49453e4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82343
  cosmetic: 42652
  scriptlet: 16720
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
  default: 
    user-filters: 0-0, never
    easylist: 66355-51, 3d.2h.9m
    easyprivacy: 26861-121, 3d.2h.13m
    plowe-0: 3682-804, 8d.22h.36m
    ublock-abuse: 74-0, 23h.40m
    ublock-badware: 4093-93, 3d.2h.11m
    ublock-filters: 30849-106, 3d.2h.12m
    ublock-privacy: 212-2, 23h.41m
    ublock-quick-fixes: 180-0, 11h.25m
    ublock-unbreak: 1766-42, 3d.2h.10m
    urlhaus-1: 9017-0, 11h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 288 ms (selfie)
  maxAssetCacheWait: 174 ms
popupPanel: 
  blocked: 9
  no-cosmetic-filtering: true
  blockedDetails: 
    igg-games.com: 1
    10dfe782e555876082a4ed6d8dda8d267585707bfd37e7fd1a9c8df43194.s3.amazonaws.com: 1
    a-ads.com: 1
    asemskull.com: 1
    bebi.com: 1
    d301cxwfymy227.cloudfront.net: 2
    googletagmanager.com: 1
    patinesgaulin.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
igg-games.com##+js(nostif, Math)
```

**Comment by stephenhawk8054** [comment]
It's fixed a few hours ago already: [https://github.com/uBlockOrigin/uAssets/issues/12966](https://github.com/uBlockOrigin/uAssets/issues/12966). Can you force update the filter lists?
