### ISSUE TITLE
[nsfw] lowclark.site: privacy

### ISSUE THREAD

**Issue by MeesterChris** [uBlockOrigin/uAssets#12974]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lowclark.site/06ukmcPeTSIrxMGv8HwwV5ORvM/?ip=81.100.65.142&lpkey=16dc51ef01b5376d44&thjp=dGVybmF0b3IuY29t&uclick=g59rh9tw&uclickhash=g59rh9tw-g59rh9tw-bzsc-0-usuq-4pdu-whsy-ae1864`

### Category

privacy

### Describe the issue

nasty lil scammer shits

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 78111
  cosmetic: 40845
  scriptlet: 16482
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62754-9, 83d.1h.53m
    easyprivacy: 26693-18, 83d.1h.52m
    plowe-0: 3676-817, 93d.5h.17m
    ublock-abuse: 77-0, 83d.1h.51m
    ublock-badware: 3831-70, 83d.1h.55m
    ublock-filters: 30176-149, 83d.1h.56m
    ublock-privacy: 194-2, 83d.1h.54m
    ublock-unbreak: 1694-39, 83d.1h.50m
    urlhaus-1: 7599-0, 82d.10h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1376 ms
  maxAssetCacheWait: 796 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
The link is blocked by `/?ip=*&uclickhash=$doc` in `uBlock filters – Badware risks` already. Please force update your filter lists. I see that your filter lists have not been updated for nearly 3 months.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/165452212-fe8d4d7e-3215-4703-98f9-1f497621bfc4.png)
