### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by outrax** [uBlockOrigin/uAssets#12985]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

it come adds sometimes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81914
  cosmetic: 42669
  scriptlet: 16699
  html: 643
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31526-30, 23h.41m
    ublock-badware: 4108-3, 23h.46m
    ublock-privacy: 216-0, 9d.18h.11m
    ublock-abuse: 74-0, 10d.20h.7m
    ublock-unbreak: 1776-0, 23h.45m
    easylist: 66536-608, 23h.44m
    easyprivacy: 26902-577, 23h.43m
    urlhaus-1: 8483-0, 23h.40m
    plowe-0: 3682-3, 8d.2h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1626 ms (selfie)
  maxAssetCacheWait: 1089 ms
popupPanel: 
  blocked: 160
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 2
    imrworldwide.com: 2
    scorecardresearch.com: 152
    sentry.io: 1
```
</details>

**Comment by krystian3w** [comment]
adds =/= ads
