### ISSUE TITLE
freedownloadvideo.net: detection

### ISSUE THREAD

**Issue by poqgit** [uBlockOrigin/uAssets#12980]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freedownloadvideo.net/dailymotion-video-downloader`

### Category

detection

### Describe the issue

A big block saying adblock detected is shown after a few seconds of entering the page. Asked on reddit before which it didn't even let me look at the real page. Now it takes a few seconds for it to show the box. https://www.reddit.com/r/uBlockOrigin/comments/ucsg1g/adblock_detected_wont_allow_use/?utm_source=share&utm_medium=web2x&context=3

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 82177
  cosmetic: 42786
  scriptlet: 16730
  html: 644
listset (total-discarded, last updated): 
  default: 
    user-filters: 21-2, never
    ublock-filters: 31552-30, now
    ublock-badware: 4108-3, now
    ublock-privacy: 218-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1779-0, now
    easylist: 66555-229, now
    easyprivacy: 26907-151, now
    urlhaus-1: 8643-0, now
    plowe-0: 3679-808, now
    ublock-quick-fixes: 181-0, now
filterset (user): [array of 21 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2151 ms (selfie)
  maxAssetCacheWait: 1302 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    freedownloadvideo.net: 1
    googlesyndication.com: 4
```
</details>

**Comment by sugarfreesweetener** [comment]
Should the scriptlets replaced by `freedownloadvideo.net##+js(nostif, show)`?

**Comment by JobcenterTycoon** [comment]
Why? I get no anti adblock

**Comment by sugarfreesweetener** [comment]
Increased efficiency I guess
