### ISSUE TITLE
opgg block all new interface

### ISSUE THREAD

**Issue by FrapzHaash** [uBlockOrigin/uAssets#12983]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.op.gg/champions` (with any character if I try to enter their page it happens)

### Describe the issue

with the new interface ublock block all the content

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80805708/165558630-805a19ff-6c8d-44c5-aedd-df0d70dbf3a6.png)

### uBlock Origin version

1.42.4

### Browser name and version

OperaGX LVL 3 (core: 85.0.4341.72)

### Settings

![image](https://user-images.githubusercontent.com/80805708/165560241-3344fd00-cd43-4e0d-91ba-31ef7d6d4df0.png)
in built-in try to disable all filters and the problem is uBlock filter

### Notes

![image](https://user-images.githubusercontent.com/80805708/165560576-ea58eb01-84fe-4ba1-83a7-e543f627d7ba.png)
the problem is only with the new interface

**Comment by krystian3w** [comment]
Try use uBo logger and DOM inspector:
https://github.com/gorhill/uBlock/wiki/The-logger
https://github.com/gorhill/uBlock/wiki/DOM-inspector

**Comment by FrapzHaash** [comment]
I don't know how to use those things

**Comment by JobcenterTycoon** [comment]
@FrapzHaash fixed. 

To get the update faster click on the uBlock Origin logo -> gears -> filter lists -> click on Clear all cache and after this on update now

**Comment by krystian3w** [comment]
Placeholders/Leftovers are back.
