### ISSUE TITLE
ggwash.org: nuisance

### ISSUE THREAD

**Issue by infinitebuffalo** [uBlockOrigin/uAssets#12986]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ggwash.org/view/84518/advocates-protest-for-housing-to-be-added-to-library-redevelopment-plans-in-chevy-chase`

### Category

nuisance

### Describe the issue

Site (a local publication) has an overlay that pops up when you reach the bottom of an article, any article (screenshot below)

Attempting to block the overlay popup results in the entire content of the page vanishing, and the page being unable to scroll.  Disabling 'cosmetic filtering' in uBO brings back the content, but also the popup.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/7200103/165580317-1b16b0ce-4360-4a10-8bd8-1c145f6f7c4b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 127556
  cosmetic: 169914
  scriptlet: 23877
  html: 650
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-10, 2d.12h.24m
    https://winhelp2002.mvps.org/hosts.txt: 8730-1, 3d.16h.42m
    adguard-mobile: 7655-215, 2d.19h.28m
    adguard-spyware: 25676-1140, 1d.8h.28m
    adguard-annoyance: 52272-4028, 2d.38m
    adguard-social: 16915-1111, 2d.12h.20m
    fanboy-thirdparty_social: 69-0, 18h.22m
    fanboy-annoyance: 69187-54260, 6d.22h.14m
    fanboy-cookiemonster: 31744-100, 1d.17h.30m
    fanboy-social: 23347-31, 18h.20m
    ublock-annoyances: 4359-8, 2d.19h.30m
    dpollock-0: 10364-1635, 2d.12h.26m
  default: 
    user-filters: 72-0, never
    ublock-filters: 31434-97, 3d.16h.40m
    ublock-badware: 4102-4, 2d.19h.32m
    ublock-privacy: 217-0, 1d.17h.34m
    ublock-abuse: 74-0, 1d.17h.32m
    ublock-unbreak: 1777-1, 3d.2h.36m
    easylist: 66499-1047, 1d.8h.26m
    easyprivacy: 26892-10532, 2d.12h.22m
    plowe-0: 3682-349, 9d.20h.31m
    urlhaus-1: 8483-0, 18h.18m
    ublock-quick-fixes: 180-0, 1d.1h.24m
filterset (user): [array of 72 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 268 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  collapseBlocked: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  selfieAfter: 3
supportStats: 
  allReadyAfter: 870 ms (selfie)
  maxAssetCacheWait: 1343 ms
popupPanel: 
  blocked: 9
  no-cosmetic-filtering: true
  blockedDetails: 
    broadstreetads.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    newrelic.com: 1
    t.co: 1
```
</details>

**Comment by krystian3w** [comment]
anti-adblock or soft paywall (if jump without block ads).
