### ISSUE TITLE
keskustelu.suomi24.fi: ads

### ISSUE THREAD

**Issue by pinworm** [uBlockOrigin/uAssets#12984]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://keskustelu.suomi24.fi/t/17409392/joku-unohtui-se-fakta-etta-usa-aloitti-sodan`

### Category

ads

### Describe the issue

Adblocker doesn't block Invisible elements under the ads, leaving large empty fields ie. between topics and comments.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![emptyarealeft](https://user-images.githubusercontent.com/46077487/165562605-d9c1232b-57c3-49c3-8111-c03c334c73a2.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81980
  cosmetic: 42782
  scriptlet: 16725
  html: 643
listset (total-discarded, last updated): 
  default: 
    user-filters: 23-0, never
    ublock-filters: 31548-30, 1d.16m
    ublock-badware: 4108-3, 1d.15m
    ublock-privacy: 217-0, 1d.14m
    ublock-abuse: 74-0, 1d.13m
    ublock-unbreak: 1778-0, 1d.12m
    ublock-quick-fixes: 180-0, 8m
    easylist: 66518-609, 1d.8m
    easyprivacy: 26902-578, 1d.7m
    urlhaus-1: 8483-0, 1d.5m
    plowe-0: 3679-3, 1d.4m
filterset (user): [array of 23 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 183 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    suomi24.fi: 1
    d1zgderxoe1a.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    lwadm.com: 1
    pushpushgo.com: 1
```
</details>

**Comment by krystian3w** [comment]
Fyi @peace2000, @Nojuuu / @theel0ja

**Comment by Nojuuu** [comment]
Enable `FIN: Adblock list for Finland` on the filter lists tab

**Comment by peace2000** [comment]
@pinworm The Finnish list handles it, you should enable it.

**Comment by AmCarte** [comment]
@stephenhawk8054

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054

Is there anything wrong?

**Comment by AmCarte** [comment]
> > @stephenhawk8054
> 
> Is there anything wrong?

@stephenhawk8054  `peace2000` said:



> @pinworm The Finnish list handles it, you should enable it.

**Comment by stephenhawk8054** [comment]
@AmCarte Yup, I'm waiting for OP to confirm, but if others already confirmed it. I think the issue can be closed.

**Comment by pinworm** [comment]
Enabling list for Finland did the job. Thanks :) As a newb I used to always block them manually. If I knew that earlier... :D
