### ISSUE TITLE
namu.wiki: breakage

### ISSUE THREAD

**Issue by kangdol** [uBlockOrigin/uAssets#12994]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://namu.wiki`

### Category

breakage

### Describe the issue

Editing, history, and other features are not displayed on all pages except the document body

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/33724177/165672287-38de1b6e-f69a-4b74-a3d7-53b7fce6b18d.png)
![image](https://user-images.githubusercontent.com/33724177/165672256-3ff40174-921c-4a8e-a581-96c7cfc9872f.png)
![image](https://user-images.githubusercontent.com/33724177/165672318-5fd4e6e4-a8a2-434e-9fd2-3900bd2e350f.png)
![image](https://user-images.githubusercontent.com/33724177/165672349-db89ad65-039d-49e0-8c08-5a5112ae86c9.png)
![image](https://user-images.githubusercontent.com/33724177/165672373-a40213bf-4b96-4267-9ec0-ef7fda589213.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 83987
  cosmetic: 49026
  scriptlet: 16768
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    KOR-1: 8206-0, 2d.11h.53m
    easylist: 66453-58, 2d.11h.52m
    easyprivacy: 26899-125, 1d.21h.34m
    plowe-0: 3678-807, 4d.14h.38m
    ublock-abuse: 74-0, 11d.17h.48m
    ublock-badware: 4098-93, 2d.11h.55m
    ublock-filters: 30955-106, 2d.11h.54m
    ublock-privacy: 211-2, 8d.12h.43m
    ublock-quick-fixes: 185-0, 17m
    ublock-unbreak: 1766-42, 4d.1h.41m
    urlhaus-1: 8643-0, 1d.1h.2m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 867 ms (selfie)
  maxAssetCacheWait: 594 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    doubleclick.net: 1
```
</details>

**Comment by krystian3w** [comment]
You use YousList, disable and correct to KR-List: #12953

**Comment by krystian3w** [comment]
To reproduce may needed is real Korean IP not from VPN/Proxy.
