### ISSUE TITLE
worldofbuzz.com: ads

### ISSUE THREAD

**Issue by expiredyogurt** [uBlockOrigin/uAssets#12996]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://worldofbuzz.com/spore-money-changers-are-running-out-of-rm-as-sporeans-rush-to-buy/`

### Category

ads

### Describe the issue

huge ass overlay ad that shows up. cant use element zapper as its an overlay 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 89301
  cosmetic: 105740
  scriptlet: 20922
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 70745-221, now
    fanboy-cookiemonster: 31663-31655, 3d.19h.24m
    ublock-annoyances: 4339-45, 2d.16h.21m
  default: 
    user-filters: 5-0, never
    easylist: 66453-51, 2d.16h.23m
    easyprivacy: 26893-121, 2d.16h.22m
    plowe-0: 3678-805, 5d.17h.48m
    ublock-abuse: 74-0, 6d.1h.51m
    ublock-badware: 4098-93, 2d.16h.20m
    ublock-filters: 30873-126, 2d.16h.19m
    ublock-privacy: 212-10, 6d.1h.50m
    ublock-unbreak: 1767-45, 2d.16h.18m
    urlhaus-1: 8492-0, 18h.15m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 21
  no-cosmetic-filtering: true
  blockedDetails: 
    adbro.me: 2
    adsafeprotected.com: 1
    anymind360.com: 1
    byinspired.com: 3
    doubleclick.net: 5
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 3
    maps.googleapis.com: 1
    moatads.com: 1
    scorecardresearch.com: 1
    taboola.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Ads/tracking script: `https://media-cdn.synkd.life/fenix.js`

@ryanbr
