### ISSUE TITLE
memangbau.com: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#12998]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://memangbau.com/6-tu-the-quan-he-cho-me-bau-an-toan-tranh-dong-thai/`

### Category

detection

### Describe the issue

This site detect uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Cuplikan web_28-4-2022_144816_memangbau com](https://user-images.githubusercontent.com/45124799/165703599-f39eb0e0-a926-42ec-b5bb-aa6fe1b5a051.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 85902
  cosmetic: 47347
  scriptlet: 16744
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    IDN-0: 8983-0, 2d.13h.20m
    easylist: 66490-53, 2d.13h.19m
    easyprivacy: 26893-123, 2d.13h.18m
    plowe-0: 3679-805, 1d.20h.11m
    ublock-abuse: 74-0, 1d.20h.10m
    ublock-badware: 4104-93, 2d.13h.17m
    ublock-filters: 30955-142, 2d.13h.16m
    ublock-privacy: 212-2, 1d.20h.9m
    ublock-unbreak: 1767-43, 2d.13h.15m
    urlhaus-1: 8236-0, 59m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 546 ms (selfie)
  maxAssetCacheWait: 394 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    memangbau.com: 1
    googletagmanager.com: 1
    netpub.media: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?

**Comment by yohanes4dip** [comment]
It's work, thank you. God bless

Pada tanggal Kam, 28 Apr 2022 14.52, stephenhawk8054 <
***@***.***> menulis:
