### ISSUE TITLE
teny.co.jp: breakage

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#12993]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.teny.co.jp/nnn/news114usnqskwhvwjnrt33.html`

### Category

breakage

### Describe the issue

When uBlock is enabled, the article headline is covered by the button. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし](https://user-images.githubusercontent.com/86018494/165669218-91ab3861-6501-4167-b9b2-d1722c83a074.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 83085
  cosmetic: 49532
  scriptlet: 19710
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4360-7, 47m
  default: 
    user-filters: 0-0, never
    JPN-1: 6740-7, 47m
    easylist: 66601-134, 47m
    easyprivacy: 26909-142, 47m
    plowe-0: 3679-811, 47m
    ublock-abuse: 75-0, 47m
    ublock-badware: 4109-93, 47m
    ublock-filters: 30966-113, 47m
    ublock-privacy: 213-2, 47m
    ublock-quick-fixes: 183-0, 47m
    ublock-unbreak: 1767-45, 47m
    urlhaus-1: 8236-0, 47m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 158 ms (selfie)
  maxAssetCacheWait: 105 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    brightcove.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    yimg.jp: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe

`teny.co.jp##body > .wrapper:style(padding-top: 40px !important)`

? @Yuki2718

**Comment by Yuki2718** [comment]
Caused by `##.s-ad` @ryanbr 
I prefer removing the cause first (`teny.co.jp#@#.s-ad`) and then add an alternative solution (`teny.co.jp##.s-ad:style(height: 1px !important;)`). Not all blocker support css rule.
