### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by cornbed** [uBlockOrigin/uAssets#12997]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Describe the issue

'something went wrong'. Works when ublock disabled. if all filters updated, works once - then same issue again when next opened

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82144
  cosmetic: 42778
  scriptlet: 16733
  html: 644
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 11h.38m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31562-30, 11h.38m
    ublock-badware: 4113-3, 11h.38m
    ublock-privacy: 218-0, 11h.38m
    ublock-abuse: 75-0, 11h.38m
    ublock-unbreak: 1778-0, 11h.38m
    easylist: 66601-597, 11h.38m
    easyprivacy: 26907-590, 11h.38m
    urlhaus-1: 8492-0, 11h.38m
    plowe-0: 3679-3, 11h.38m
    ublock-quick-fixes: 186-0, 11h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 483 ms (selfie)
  maxAssetCacheWait: 269 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    twitter.com: 4
```
</details>

**Comment by krystian3w** [comment]
Account Required?

**Comment by cornbed** [comment]
Sorry, don't understand comment? Twitter account? I have one

**Comment by krystian3w** [comment]
So filter may created in this week or uBo download corrupted files from CDN.

**Comment by gorhill** [comment]
> I have a twitter account. Worked fine with UBlock on until this week

I have a twitter account, it still work fine -- unable to reproduce your issue.

> - [X] I did not answer truthfully to **all** the above checkpoints

Please revise the requested steps and answer truthfully.

**Comment by cornbed** [comment]
Sorry - I'm new to this and not following. I haven't changed anything in the UBlock settings - it's all just as per default. I cleared the cache in firefox, did the 'purge all caches' and update now in Ublock. What else am I supposed to do?

**Comment by stephenhawk8054** [comment]
> Sorry - I'm new to this and not following. I haven't changed anything in the UBlock settings - it's all just as per default. I cleared the cache in firefox, did the 'purge all caches' and update now in Ublock. What else am I supposed to do?

Can you test in a new Firefox profile?

**Comment by gorhill** [comment]
Open the logger, filter out the output so that only blocked network requests are shown, and share the result here (use the clipboard icon in the logger). I have seen this _"something went wrong"_ in the past for example when using Twitter through the Tor browser -- so for now I am skeptical that your issue is caused by uBO.
