### ISSUE TITLE
www.cnx-software.com banner ads

### ISSUE THREAD

**Issue by maurerr** [uBlockOrigin/uAssets#12995]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cnx-software.com/2022/04/28/orbbec-persee-3d-ai-camera-ubuntu-android-amlogic-a311d-processor/`

### Describe the issue

without custom filters almost all the banners are displayed.
Please implement the following:
```
www.cnx-software.com##.gxmas-single[class*="axmas-"]
www.cnx-software.com##.gxmas-1.gxmas
```

### uBlock Origin version

1.42.4

### Browser name and version

Chromium 100.0.4896.88

### Settings

implemented the following filters:
```
www.cnx-software.com##.gxmas-single[class*="axmas-"]
www.cnx-software.com##.gxmas-1.gxmas
```

### Notes

no more ads :)

**Comment by stephenhawk8054** [comment]
`cnx-software.com##.gxmas`

@ryanbr
