### ISSUE TITLE
ad.nl: detection

### ISSUE THREAD

**Issue by SOMSilence4all** [uBlockOrigin/uAssets#12999]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ad.nl/show/derksen-wijzigt-uitspraken-kaars-stond-tussen-benen-dronken-vrouw-niet-gepenetreerd~a4048e9c/`

### Category

detection

### Describe the issue

Have to disable Ublock to be able to watch news videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock](https://user-images.githubusercontent.com/20141354/165705609-191acae2-2d96-46c6-bbe8-e7ac35388aa4.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82039
  cosmetic: 42775
  scriptlet: 16770
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 66578-51, 15h.14m
    easyprivacy: 26907-121, 15h.13m
    plowe-0: 3678-805, 4d.21h.5m
    ublock-abuse: 75-0, 15h.12m
    ublock-badware: 4104-93, 15h.11m
    ublock-filters: 30965-109, 15h.10m
    ublock-privacy: 213-2, 15h.9m
    ublock-quick-fixes: 182-0, 15h.7m
    ublock-unbreak: 1767-42, 15h.8m
    urlhaus-1: 8492-0, 15h.6m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 965 ms (selfie)
  maxAssetCacheWait: 88 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ad.nl: 2
    adhese.com: 1
    dpgmedia.cloud: 2
    dpgmedia.net: 1
    imasdk.googleapis.com: 1
    jwpltx.com: 1
    kijk.nl: 2
    talpanetwork.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `NLD: EasyDutch` list in `Regions, languages` section of [Filter lists pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists)?

**Comment by SOMSilence4all** [comment]
EasyList did it... cant understand why i did not see that myself.
THANKS!

**Comment by JohnyP36** [comment]
> Can you enable `NLD: EasyDutch` list in `Regions, languages` section of [Filter lists pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists)?

As one of the maintainers of `NLD: EasyDutch` I couldn't reproduce an adblock detection. But as @SOMSilence4all it's ok now.
