### ISSUE TITLE
[nsfw] hitomi.la: breakage

### ISSUE THREAD

**Issue by GPMS** [uBlockOrigin/uAssets#13002]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hitomi.la/`

### Category

breakage

### Describe the issue

No entry is shown when site is open with ublock on. Sometimes it works, sometimes it doesn't

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81825
  cosmetic: 42796
  scriptlet: 16776
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66623-51, 4m
    easyprivacy: 26912-121, 3m
    plowe-0: 3679-805, 3m
    ublock-abuse: 75-0, 3m
    ublock-badware: 4109-93, 3m
    ublock-filters: 30975-109, 3m
    ublock-privacy: 213-2, 3m
    ublock-quick-fixes: 187-0, 3m
    ublock-unbreak: 1767-42, 3m
    urlhaus-1: 8236-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9701 ms
  maxAssetCacheWait: 6398 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    hitomi.la: 5
```
</details>

**Comment by GPMS** [comment]
It's back to normal for some reason

**Comment by stephenhawk8054** [comment]
It's fixed in EL: [https://github.com/easylist/easylist/commit/076684446456bb775f4a996c13c0d7825f66faa9](https://github.com/easylist/easylist/commit/076684446456bb775f4a996c13c0d7825f66faa9)
