### ISSUE TITLE
facebook.com: in-video ads

### ISSUE THREAD

**Issue by ojanecek** [uBlockOrigin/uAssets#13000]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/watch/?v=227255992449987`

### Category

ads

### Describe the issue

In-video ads still show up. Quite annoying.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 83895
  cosmetic: 71865
  scriptlet: 18457
  html: 0
listset (total-discarded, last updated): 
  added: 
    CZE-0: 832-0, 20h.38m
    fanboy-cookiemonster: 31816-83, 16h.47m
  default: 
    user-filters: 0-0, never
    easylist: 66499-53, 1d.21h.49m
    easyprivacy: 26902-126, 1d.21h.49m
    plowe-0: 3679-805, 1d.21h.49m
    ublock-abuse: 74-0, 1d.21h.49m
    ublock-badware: 4104-93, 1d.21h.49m
    ublock-filters: 30984-114, 1d.21h.48m
    ublock-privacy: 212-2, 1d.21h.48m
    ublock-quick-fixes: 181-0, 20h.37m
    ublock-unbreak: 1767-43, 1d.21h.48m
    urlhaus-1: 8643-0, 20h.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 434 ms (selfie)
  maxAssetCacheWait: 240 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please discuss in this thread: [https://github.com/uBlockOrigin/uAssets/issues/3367](https://github.com/uBlockOrigin/uAssets/issues/3367)
