### ISSUE TITLE
tribunnews.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#13007]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.tribunnews.com/nasional/2022/04/28/hasil-sidang-isbat-idul-fitri-1-syawal-1443-h-jatuh-pada-tanggal-2-atau-3-mei-cek-di-sini`

### Category

nuisance

### Describe the issue

Ads on the top

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220429-013422_Kiwi Browser](https://user-images.githubusercontent.com/19517680/165822945-7cf6373b-97f0-4cb4-9541-ebc969fb2f58.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 82517
  cosmetic: 116397
  scriptlet: 18944
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6301-1, 5h.50m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 3404-11, 5h.49m
    fanboy-annoyance: 70636-232, 3d.13h.53m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 7659-21, 6h.27m
    easylist: 66623-251, 6h.43m
    easyprivacy: 26912-130, 5h.41m
    ublock-abuse: 75-0, 6h.38m
    ublock-badware: 4109-91, 6h.11m
    ublock-filters: 31058-205, 6h.1m
    ublock-privacy: 213-9, 6h
    ublock-quick-fixes: 184-0, 5h.48m
    ublock-unbreak: 1772-47, 5h.53m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1076 ms (selfie)
  maxAssetCacheWait: 503 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    contextads.live: 1
    d31qbv1cthcecs.cloudfront.net: 1
    doubleclick.net: 3
    facebook.com: 1
    google.com: 2
    googletagmanager.com: 1
    gstatic.com: 1
    mgid.com: 1
    r2b2.io: 1
    scorecardresearch.com: 1
    tstatic.net: 1
    youtube.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Self advertisment not getting fixed in uAssets
