### ISSUE TITLE
eroprofile.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1300]
URL(s) where the issue occurs

`http://www.eroprofile.com/m/videos/view/hot_brunette_sucking_and_playing_bf_big_cock_like_a_pro_2`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS

`https://www.eroprofile.com/m/videos/home?pnum=9`
