### ISSUE TITLE
online.citadelbanking.com: breakage

### ISSUE THREAD

**Issue by nobodytooo** [uBlockOrigin/uAssets#13010]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://online.citadelbanking.com/CitadelOLB/uux.aspx`

### Category

breakage

### Describe the issue

the website fails to load; white screen

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81812
  cosmetic: 42776
  scriptlet: 16771
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66601-51, 21h.39m
    easyprivacy: 26907-121, 21h.38m
    plowe-0: 3679-805, 20h.58m
    ublock-abuse: 75-0, 20h.56m
    ublock-badware: 4109-93, 20h.54m
    ublock-filters: 30966-109, 20h.53m
    ublock-privacy: 213-2, 20h.52m
    ublock-quick-fixes: 185-0, 20h.51m
    ublock-unbreak: 1767-42, 15h.26m
    urlhaus-1: 8236-0, 15h.25m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1425 ms (selfie)
  maxAssetCacheWait: 556 ms
popupPanel: 
  blocked: 5
  no-cosmetic-filtering: true
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    pendo.io: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Can you copy the logger information with these steps:

1. Open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger)
2. In logger's search box, select `Blocked` and `Allowed`
3. Reload the page and do the steps to trigger the issue
4. Click on this button at the top right:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png)

</details>

5. Choose `Table` at the top left -> `Markdown` at top middle -> `Copy to clipboard` at top right and paste here

Video: [https://www.youtube.com/watch?v=IHIz5rFnieg](https://www.youtube.com/watch?v=IHIz5rFnieg)

**Comment by nobodytooo** [comment]
Stephenhawk8504
Thank you fo closing without looking
I responded to the log request on April 28, 2022.
 
From: lz.junks 
Sent: Thursday, April 28, 2022 23:23
To: 'uBlockOrigin/uAssets' ***@***.***>
Subject: RE: <details><summary>Logger output</summary>Re: [uBlockOrigin/uAssets] online.citadelbanking.com: breakage (Issue #13010)
 
<details><summary>Logger output</summary>
 
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | xhr | `https://app.pendo.io/data/errorlog?apiKey=4cfc5253-789b-470f-45eb-e4d59dd0bf11` |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | xhr | `https://app.pendo.io/data/guide.json/4cfc5253-789b-470f-45eb-e4d59dd0bf11?jzb=eJylj01LAzEQQP9LzpJk0xVlb7UWKogVXL2GcXdcg-lkzUctyP73TlUWvHjxlrzM8F4-xd4ll0O86UUj7P367nprW9u2H5v35YVePS3EmYCuC4Xy18i5rgyjEj1fXnMeU6NUIO8IZecy9Oifgd4cDbILO7X6RtvbK1XKQUIaD7y9Q6aQQTSz_3R0fzR4oKHAgDyBZB8fxDR3zas_bXuMyQViUMtaallVi_U_k1k2QkTKy1nJiL9w6jGXStfKaPNbblispbFjDD0_JPQvm5AycmmOBafpCH7VeoY&v=2.110.2_prod&ct=1651212953607&acc=NTAxMg` |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | image | `https://app.pendo.io/data/ptm.gif/4cfc5253-789b-470f-45eb-e4d59dd0bf11?v=2.110.2_prod&ct=1651212953603&jzb=eJzFkUtv4jAUhf-L1ygP50GGHQNIIKoSaTKzaFVFTmKCRWKn9g2EIv47N8MQqYvphkV38bk-OZ_veT0TODWcTEjNgZERybQ6Gq5TEDWqbhi41KU_Ai8IwxE5CCNA6VQUaEjjxfN8kyZpkhyX79OxM_vj4Q9YnqtWwu1O4LgUtVZXeNgBNGZi20pWQnIrF8AKXmVM7oUsrVzV9uwmbZ5-2m3bWcw0HbobrRpDJud7fP_5FUHFZNmysn8Ul-nvX-QyUA3Wf2AHro1QEgXf8i3Hcl1v8SAvhjVMcwnTIRKlgkHPQyPb8W3q0M_hFIMdi6b40gIHhlfbpTLAkRR0y9EPLFv13KtdVAXlfp37p8SL1RpvbzWr-d_htIgPHy9xx-oQNvMu6-s8Acfd-ePoMhqqrhTrY_5fdfTtVfeId7AoGD--AeoHl7crSwDv5A&acc=NTAxMg` |
| +3 |  |  | online.citadelbanking.com | 3 | image | `https://cdn1.onlineaccess1.com/cdn/5012/4.4.0.113E/000060/images/favicon.ico` |
| +3 | \|\|google-analytics.com^ | -- | online.citadelbanking.com | 3 | image | `https://ssl.google-analytics.com/__utm.gif?utmwv=5.7.2&utms=1&utmn=854641641&utmhn=online.citadelbanking.com&utmt=event&utme=5(Bk101ExifAndrey243*NotifUI*msgForNotifsURLs%20is%20EMPTY)&utmcs=UTF-8&utmsr=1920x1080&utmvp=974x948&utmsc=24-bit&utmul=en-us&utmje=0&utmfl=-&utmdt=Citadel%20FCU&utmhid=582051993&utmr=https%3A%2F%2Fwww.citadelbanking.com%2F&utmp=%2FCitadelOLB%2Fuux.aspx&utmht=1651212953449&utmac=UA-68817852-1&utmcc=__utma%3D217568968.1814121940.1651212953.1651212953.1651212953.1%3B%2B__utmz%3D217568968.1651212953.1.1.utmcsr%3Dcitadelbanking.com%7Cutmccn%3D(referral)%7Cutmcmd%3Dreferral%7Cutmcct%3D%2F%3B&utmjid=&utmu=4AAAAAAAAAAAAAAAAAAAAAAE~` |
| +3 |  |  | online.citadelbanking.com | 3 | font | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/fonts/OpenSans/OpenSans-Regular.woff` |
| +3 |  |  | online.citadelbanking.com | 3 | image | `https://cdn1.onlineaccess1.com/cdn/5012/4.4.0.113E/000060/images/favicon.ico` |
| +3 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/static/q2-pendo/pendo-2.110.2_a.js` |
| +2 |  |  | online.citadelbanking.com | 3 | script | `https://lptag.liveperson.net/tag/tag.js?site=71465649` |
| +2 | googletagmanager.com/gtm.js | << | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js | -- | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 | \|\|googletagmanager.com^ | -- | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/ember-template-compiler.js?_=1651212952784` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/pendo/q2-pendo.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/resources/en-us-75d16226601814ab949f092b4060baf2.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/themejs/theme-q2-84dab942cd359ebf0910a39d404d01b2.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/vendorapp.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/add-engine-meta.js` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/theme-q2-cb27e21c62dce26d132dbe11fb4a7639.css` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/highcontrast-a26c018c7a1b0edecad5916881aacf80.css` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/app.css` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cds-sdkcfg.onlineaccess1.com/common.js` |
| +1 |  |  | online.citadelbanking.com | 1 | doc | `https://online.citadelbanking.com/CitadelOLB/uux.aspx` |
| +0 |  |  | online.citadelbanking.com | 1 | doc | `https://online.citadelbanking.com/CitadelOLB/uux.aspx` |
</details>
 
From: stephenhawk8054 
Sent: Thursday, April 28, 2022 20:00
To: uBlockOrigin/uAssets ***@***.*** ***@***.***> >
Cc: nobodytooo ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Subject: <details><summary>Logger output</summary>Re: [uBlockOrigin/uAssets] online.citadelbanking.com: breakage (Issue #13010)
 
Can you copy the logger information with these steps:
1.	Open The logger <https://github.com/gorhill/uBlock/wiki/The-logger> 
2.	In logger's search box, select Blocked and Allowed
3.	Reload the page and do the steps to trigger the issue
4.	Click on this button at the top right:
Screenshot 
 <https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png> 
1.	Choose Table at the top left -> Markdown at top middle -> Copy to clipboard at top right and paste here
Video: https://www.youtube.com/watch?v=IHIz5rFnieg

**Comment by stephenhawk8054** [comment]
I think it's better to comment directly on github. Comment via e-mail seems have many bugs with github now. Looks like your repond didn't arrive in github.

**Comment by stephenhawk8054** [comment]
Can you test if adding this filter works?

`@@||app.pendo.io/data/guide.json$xhr,domain=citadelbanking.com`

**Comment by nobodytooo** [comment]
<details><summary>Logger output</summary>
 
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | xhr | `https://app.pendo.io/data/errorlog?apiKey=4cfc5253-789b-470f-45eb-e4d59dd0bf11` |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | xhr | `https://app.pendo.io/data/guide.json/4cfc5253-789b-470f-45eb-e4d59dd0bf11?jzb=eJylj01LAzEQQP9LzpJk0xVlb7UWKogVXL2GcXdcg-lkzUctyP73TlUWvHjxlrzM8F4-xd4ll0O86UUj7P367nprW9u2H5v35YVePS3EmYCuC4Xy18i5rgyjEj1fXnMeU6NUIO8IZecy9Oifgd4cDbILO7X6RtvbK1XKQUIaD7y9Q6aQQTSz_3R0fzR4oKHAgDyBZB8fxDR3zas_bXuMyQViUMtaallVi_U_k1k2QkTKy1nJiL9w6jGXStfKaPNbblispbFjDD0_JPQvm5AycmmOBafpCH7VeoY&v=2.110.2_prod&ct=1651212953607&acc=NTAxMg` |
| +3 | \|\|app.pendo.io^ | -- | online.citadelbanking.com | 3 | image | `https://app.pendo.io/data/ptm.gif/4cfc5253-789b-470f-45eb-e4d59dd0bf11?v=2.110.2_prod&ct=1651212953603&jzb=eJzFkUtv4jAUhf-L1ygP50GGHQNIIKoSaTKzaFVFTmKCRWKn9g2EIv47N8MQqYvphkV38bk-OZ_veT0TODWcTEjNgZERybQ6Gq5TEDWqbhi41KU_Ai8IwxE5CCNA6VQUaEjjxfN8kyZpkhyX79OxM_vj4Q9YnqtWwu1O4LgUtVZXeNgBNGZi20pWQnIrF8AKXmVM7oUsrVzV9uwmbZ5-2m3bWcw0HbobrRpDJud7fP_5FUHFZNmysn8Ul-nvX-QyUA3Wf2AHro1QEgXf8i3Hcl1v8SAvhjVMcwnTIRKlgkHPQyPb8W3q0M_hFIMdi6b40gIHhlfbpTLAkRR0y9EPLFv13KtdVAXlfp37p8SL1RpvbzWr-d_htIgPHy9xx-oQNvMu6-s8Acfd-ePoMhqqrhTrY_5fdfTtVfeId7AoGD--AeoHl7crSwDv5A&acc=NTAxMg` |
| +3 |  |  | online.citadelbanking.com | 3 | image | `https://cdn1.onlineaccess1.com/cdn/5012/4.4.0.113E/000060/images/favicon.ico` |
| +3 | \|\|google-analytics.com^ | -- | online.citadelbanking.com | 3 | image | `https://ssl.google-analytics.com/__utm.gif?utmwv=5.7.2&utms=1&utmn=854641641&utmhn=online.citadelbanking.com&utmt=event&utme=5(Bk101ExifAndrey243*NotifUI*msgForNotifsURLs%20is%20EMPTY)&utmcs=UTF-8&utmsr=1920x1080&utmvp=974x948&utmsc=24-bit&utmul=en-us&utmje=0&utmfl=-&utmdt=Citadel%20FCU&utmhid=582051993&utmr=https%3A%2F%2Fwww.citadelbanking.com%2F&utmp=%2FCitadelOLB%2Fuux.aspx&utmht=1651212953449&utmac=UA-68817852-1&utmcc=__utma%3D217568968.1814121940.1651212953.1651212953.1651212953.1%3B%2B__utmz%3D217568968.1651212953.1.1.utmcsr%3Dcitadelbanking.com%7Cutmccn%3D(referral)%7Cutmcmd%3Dreferral%7Cutmcct%3D%2F%3B&utmjid=&utmu=4AAAAAAAAAAAAAAAAAAAAAAE~` |
| +3 |  |  | online.citadelbanking.com | 3 | font | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/fonts/OpenSans/OpenSans-Regular.woff` |
| +3 |  |  | online.citadelbanking.com | 3 | image | `https://cdn1.onlineaccess1.com/cdn/5012/4.4.0.113E/000060/images/favicon.ico` |
| +3 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/static/q2-pendo/pendo-2.110.2_a.js` |
| +2 |  |  | online.citadelbanking.com | 3 | script | `https://lptag.liveperson.net/tag/tag.js?site=71465649` |
| +2 | googletagmanager.com/gtm.js | << | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js | -- | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 | \|\|googletagmanager.com^ | -- | online.citadelbanking.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-W6HFGV` |
| +2 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/ember-template-compiler.js?_=1651212952784` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/pendo/q2-pendo.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/resources/en-us-75d16226601814ab949f092b4060baf2.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/themejs/theme-q2-84dab942cd359ebf0910a39d404d01b2.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/vendorapp.js` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/add-engine-meta.js` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/theme-q2-cb27e21c62dce26d132dbe11fb4a7639.css` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/depot/5012/3434/1867a2010310a3ded5b08d4d543e9fca/assets/highcontrast-a26c018c7a1b0edecad5916881aacf80.css` |
| +1 |  |  | online.citadelbanking.com | 3 | css | `https://cdn1.onlineaccess1.com/cdn/base/4.4.0.113E/assets/app.css` |
| +1 |  |  | online.citadelbanking.com | 3 | script | `https://cds-sdkcfg.onlineaccess1.com/common.js` |
| +1 |  |  | online.citadelbanking.com | 1 | doc | `https://online.citadelbanking.com/CitadelOLB/uux.aspx` |
| +0 |  |  | online.citadelbanking.com | 1 | doc | `https://online.citadelbanking.com/CitadelOLB/uux.aspx` |
</details>
 
From: stephenhawk8054 
Sent: Thursday, April 28, 2022 20:00
To: uBlockOrigin/uAssets ***@***.***>
Cc: nobodytooo ***@***.***>; Author ***@***.***>
Subject: <details><summary>Logger output</summary>Re: [uBlockOrigin/uAssets] online.citadelbanking.com: breakage (Issue #13010)
 
Can you copy the logger information with these steps:
1.	Open The logger <https://github.com/gorhill/uBlock/wiki/The-logger> 
2.	In logger's search box, select Blocked and Allowed
3.	Reload the page and do the steps to trigger the issue
4.	Click on this button at the top right:
Screenshot 
 <https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png> 
1.	Choose Table at the top left -> Markdown at top middle -> Copy to clipboard at top right and paste here
Video: https://www.youtube.com/watch?v=IHIz5rFnieg
