### ISSUE TITLE
wcofun.com: detection

### ISSUE THREAD

**Issue by TheBlackBeans** [uBlockOrigin/uAssets#13019]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wcofun.com/the-simpsons-season-30-episode-21-doh-canada`

### Category

detection

### Describe the issue

Attempting to watch any video (that I tried) on the `wcofun.com` website triggers, after a few seconds the video was started, the following message to be shown, entirely replacing the video:
>AdBlock Detected !!!
>
>We no longer can allow adblock users for free videos. Please unblock us on adblock or register as a premium user to help us running our website.
This behavior has started very suddenly (I was watching a video, it ended, I started an other one, and suddenly it stopped working.  The previous video also did not work anymore).

PS. About the *"I am not using another content blocker along uBO"*. I am, actually, not sure I am not, since my browser might have built-in blockers, other add-ons I have installed might interfere with uBO and even my internet provider may block ads (yes... don't ask why, I don't know). What I am sure, however, is that disabling *just* uBO makes the site work properly again (but invaded by ads, of course).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/23179762/165994309-9884d7c5-49f8-4db1-99f3-57bf21ea43b6.png)

</details>
Note that the website may look different as it may usually due to cosmetic filters removing some useless navigation bars.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 98
filterset (summary): 
  network: 81295
  cosmetic: 42781
  scriptlet: 16712
  html: 643
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    ublock-filters: 31501-30, 35m
    ublock-badware: 4129-3, 34m
    ublock-privacy: 217-0, 3d.12h.6m
    ublock-abuse: 74-0, 3d.12h.5m
    ublock-unbreak: 1777-0, 33m
    easylist: 66262-635, 31m
    easyprivacy: 26914-577, 32m
    urlhaus-1: 8087-0, 30m
    plowe-0: 3682-3, 10d.20h.46m
    ublock-quick-fixes: 176-0, 29m
filterset (user): [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 235 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    wcofun.com: 4
    addthis.com: 2
    bloxplay.com: 2
    cpmstar.com: 4
    google-analytics.com: 2
    googletagmanager.com: 2
    gumgum.com: 2
    vdo.ai: 4
    vlitag.com: 4
```
</details>

**Comment by TheBlackBeans** [comment]
After some though, I still wondered if it was possible that the issue was caused by cosmetic filters. I tried without, and it works perfectly, so I feel very dump...

I still leave open, as I don't know whether it is considered to be a bug (as cosmetic filtering should not trigger anti-adblocks, IMO).

**Comment by okiehsch** [comment]
It's not a bug and you were right to open the issue, I will add a fix.

**Comment by okiehsch** [comment]
>  cosmetic filtering should not trigger anti-adblocks

You are wrong about that one, many websites check for cosmetic filters to see if one uses an adblocker or not.
I added a fix,  wait a few minutes and if you then update the `uBO-filters` list the message should be gone.

**Comment by Procyon-b** [comment]
@TheBlackBeans  Many adblock detections are triggered by the effect of cosmetic filters. It's not a bug, and it's good to report those issues.

**Comment by TheBlackBeans** [comment]
@okiehsch works like a charm. Thanks!
