### ISSUE TITLE
Paste into customer number and password fields not allowed.

### ISSUE THREAD

**Issue by xpufx** [uBlockOrigin/uAssets#13017]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://esube.albaraka.com.tr/LoginIB.aspx?sID=-1&type=corporate`

### Describe the issue

Site won't allow pasting into the Customer Number and Password fields.

### uBlock Origin version

 1.42.4

### Browser name and version

Firefox 99.0.1 

### Settings

Note: I didn't actually do the steps in the "I tried to reproduce the issue when..." as they are not relevant.

### Notes

None

**Comment by gorhill** [comment]
The disabling of copy/paste of password is a security choice by the site, that choice is not something to be second-guessed by uBO's lists, as opposed to a website disabling selecting/copying text content for no good reasons.

**Comment by zeref-dragneel** [comment]
You can use this extension.
[Don't Fuck With Paste](https://github.com/aaronraimist/DontFuckWithPaste)
