### ISSUE TITLE
animepahe.ru: popups

### ISSUE THREAD

**Issue by vnaf1** [uBlockOrigin/uAssets#13018]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animepahe.ru/`

### Category

popups

### Describe the issue

popu tab when clicking after a while

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 79995
  cosmetic: 39466
  scriptlet: 16076
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62151-5, 290d.18h.13m
    easyprivacy: 27641-37, 290d.18h.13m
    plowe-0: 3632-300, 290d.18h.13m
    ublock-abuse: 72-0, 290d.18h.13m
    ublock-badware: 1861-28, 290d.18h.13m
    ublock-filters: 28894-87, 290d.18h.13m
    ublock-privacy: 141-2, 290d.18h.13m
    ublock-unbreak: 1634-42, 290d.18h.13m
    urlhaus-1: 10169-0, 290d.18h.13m
filterset (user): [empty]
modifiedUserSettings: 
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 792 ms (selfie)
  maxAssetCacheWait: 305 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 1
    holiestcoseys.com: 1
```
</details>

**Comment by AnimalLover23232323** [comment]
I sorted it out!!!!
