### ISSUE TITLE
hdfilmcehennemi.film: popups

### ISSUE THREAD

**Issue by Baracuddo** [uBlockOrigin/uAssets#13014]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hdfilmcehennemi.film/dizi/moon-knight/sezon-1/bolum-5/1`

### Category

popups

### Describe the issue

This website opens youtube on the background. When I sign in to my youtube account I see some korean live videos on my history which I did not watch. I have checked and found out that there is some unnoticable popup windows appearing  and open youtube videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 98
filterset (summary): 
  network: 83596
  cosmetic: 49180
  scriptlet: 17110
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8770-92, 3d.23h.42m
    easylist: 66425-68, 3d.23h.41m
    easyprivacy: 26892-126, 3d.23h.40m
    plowe-0: 3678-806, 3d.23h.43m
    ublock-abuse: 74-0, 7d.18h.46m
    ublock-badware: 4104-93, 3d.23h.39m
    ublock-filters: 30932-116, 3d.23h.38m
    ublock-privacy: 212-2, 7d.18h.45m
    ublock-quick-fixes: 184-0, 1h.5m
    ublock-unbreak: 1767-42, 3d.23h.37m
    urlhaus-1: 8349-0, 1h.6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 26025 ms (selfie)
  maxAssetCacheWait: 547 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    aj2373.online: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    staticmoly.me: 10
    vidmoly.to: 1
    yandex.ru: 1
    youtube.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists?
