### ISSUE TITLE
feet9.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1301]
URL(s) where the issue occurs

`https://www.feet9.com/5961/footjob-cumshot-compilation-tons-of-cum-on-cute-feet/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
what ads ? I get self-promo adv

**Comment by mapx-** [comment]
test

```
feet9.com##[data-vid^="live-"]:remove()
feet9.com##.ig
||feet9.com/t/newbuttonyellow.png$image
```

**Comment by stephenhawk8054** [comment]
The cam images appear normal for me after waiting a bit for them to load.

**Comment by mapx-** [comment]
test

```
feet9.com##[onclick*="banner"]:upward(.video)
feet9.com##.hvr-pulse
feet9.com##[class^="ig"]
||feet9.com^$csp=worker-src 'none';
```
