### ISSUE TITLE
live.720pstream.me: detection

### ISSUE THREAD

**Issue by ThatAnonymousGuy1** [uBlockOrigin/uAssets#13011]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://live.720pstream.me/live-2022-nfl-draft-stream`

### Category

detection

### Describe the issue

Player is showing a blank screen with emojis on the bottom rather than the actual video player. This happened a few months ago where it showed a black box and said it detected an ad blocker and to disable it. The suggested workaround was the following:

@@||embedstream.me/cash.min.js$script,1p

I added this to my filters list, and it has not done the trick. I also purged and updated my lists with no luck. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/yC4ePTq

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81914
  cosmetic: 42814
  scriptlet: 16770
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 18-4, never
    easylist: 66652-51, 1m
    easyprivacy: 26912-121, 1m
    plowe-0: 3679-805, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4125-94, 1m
    ublock-filters: 30975-109, 1m
    ublock-privacy: 213-2, 1m
    ublock-quick-fixes: 184-0, 1m
    ublock-unbreak: 1767-42, 1m
    urlhaus-1: 8282-0, 1m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 45 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 345 ms
  maxAssetCacheWait: 134 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    allsportsflix.best: 1
    ashoupsu.com: 2
    becorsolaom.com: 1
    eehuzaih.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    inklinkor.com: 1
    rtsts.me: 2
    sharethis.com: 1
    taboola.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue and can watch the video normally. Which region are you when browsing the site?

**Comment by ThatAnonymousGuy1** [comment]
My apologies. I think the video player was actually not yet active or started by the site administrator. I think the video source was on hold until the broadcast started. It did end up working for me. Thank you for checking though.
