### ISSUE TITLE
instagram.com nuisance (log in to view story)

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#13025]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.instagram.com/stories/sadeghsabety/2827334057473272071/`

### Describe the issue

Similar:
https://github.com/uBlockOrigin/uAssets/issues/7249
https://github.com/uBlockOrigin/uAssets/pull/7764

Page is public.

### Screenshot(s)

https://user-images.githubusercontent.com/17685483/166088865-4f4be252-9c9c-4a67-a786-cdfb11a18983.png

### Notes

![image](https://user-images.githubusercontent.com/17685483/166088886-0da15a79-ade9-49c2-80d8-29ac6e3532dd.png)
![image](https://user-images.githubusercontent.com/17685483/166089075-6131f8bc-9555-41e4-b72c-eb242f1e48de.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81614
  cosmetic: 44084
  scriptlet: 19621
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4363-6, 2m
  default: 
    user-filters: 0-0, never
    easylist: 66333-51, 2m
    easyprivacy: 26925-121, 2m
    plowe-0: 3676-805, 2m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4117-92, 1m
    ublock-filters: 30903-88, 1m
    ublock-privacy: 213-3, 1m
    ublock-quick-fixes: 184-0, 1m
    ublock-unbreak: 1766-41, 1m
    urlhaus-1: 8128-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1029 ms
  maxAssetCacheWait: 185 ms
```
</details>

**Comment by gwarser** [comment]
You need to login to get the content. 

This is what you will see when you hide the login dialog: https://www.instagram.com/static/images/stories/desktop-login-background.png/48f3de4ebabb.png

**Comment by MasterKia** [comment]
So [L1345](https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L1345) and [L1351](https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L1351) can only **disable** the log in prompt for viewing images and posts but not for stories?

**Comment by gwarser** [comment]
Yes.

**Comment by australo87** [comment]
Cookie notice in Safari for iOS (Note: I can’t reproduce on iPadOS with the same configuration)

Configuration
<yaml>
```yaml
name: uBlock Origin Lite
version: 2025.818.1918
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 annoyances-others
 annoyances-social
 ublock-badware
 annoyances-overlays
 ublock-filters
 block-lan
 annoyances-cookies
 annoyances-notifications
 annoyances-widgets
 ita-0
 pgl
 easylist
 easyprivacy
```
</yaml> 

<details>
<summary> Screenshot </summary>

![Image](https://github.com/user-attachments/assets/a55c2b0f-bafb-4103-bac4-d6159d882beb)

</details>
