### ISSUE TITLE
cbs.com: detection

### ISSUE THREAD

**Issue by Mostafa-Wahied** [uBlockOrigin/uAssets#13024]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cbs.com/shows/video/qjPRzQN7dGXWB985LVZBmHSpTzmA_s0f/`

### Category

detection

### Describe the issue

it wouldn't show the video because they couldn't play the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81316
  cosmetic: 42801
  scriptlet: 16760
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66291-51, 1h.44m
    easyprivacy: 26914-121, 1h.43m
    plowe-0: 3682-804, 8d.7h.27m
    ublock-abuse: 75-0, 1h.42m
    ublock-badware: 4117-92, 1h.41m
    ublock-filters: 30899-84, 1h.40m
    ublock-privacy: 213-2, 1h.39m
    ublock-quick-fixes: 184-0, 1h.37m
    ublock-unbreak: 1766-40, 1h.38m
    urlhaus-1: 8087-0, 1h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1671 ms (selfie)
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    cbs.com: 1
    cbsaavideo.com: 3
    cbsivideo.com: 7
    cedexis.com: 1
    demdex.net: 2
    doubleclick.net: 3
    facebook.net: 1
    scorecardresearch.com: 2
    summerhamster.com: 2
```
</details>

**Comment by krystian3w** [comment]
Works but first is too vide:

```
@@*$3p,xhr,domain=imasdk.googleapis.com
@@||ads.play.cbsi.video^$media,domain=www.cbs.com
```

no needed is refresh window/tab.

**Comment by krystian3w** [comment]
Maybe geo locked (https://github.com/uBlockOrigin/uAssets/labels/geo%20specific), for my possible play 1 or 2 vide pre roll ad(s) only.

**Comment by stephenhawk8054** [comment]
I can watch the video normally. Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by krystian3w** [comment]
Also confirm if you connect from Egypt 🇪🇬.

**Comment by Mostafa-Wahied** [comment]
It must've been another extension, yea. Maybe it was rushed of me to report it.
