### ISSUE TITLE
theverge.com: ads

### ISSUE THREAD

**Issue by zootedb0t** [uBlockOrigin/uAssets#13028]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theverge.com/2019/3/4/18246182/usb-4-thunderbolt-3-specs-features-release-date`

### Category

ads

### Describe the issue

At top of the page an error message is shown **Unable to connect**.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (10)](https://user-images.githubusercontent.com/62596687/166100717-5721a78f-0255-4ba4-b99a-c35e8683afbf.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 86377
  cosmetic: 87867
  scriptlet: 19152
  html: 644
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 570-4, 3d.14h.29m
    adguard-annoyance: 52354-649, 3d.14h.27m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31582-30, 3d.14h.32m
    ublock-badware: 4108-3, 3d.14h.33m
    ublock-privacy: 217-0, 4d.20h.32m
    ublock-abuse: 74-0, 4d.20h.31m
    ublock-unbreak: 1778-0, 2d.17h.10m
    easylist: 66537-609, 3d.14h.30m
    easyprivacy: 26902-577, 3d.14h.28m
    urlhaus-1: 8087-0, 7h.45m
    plowe-0: 3679-3, 4d.20h.30m
    ublock-quick-fixes: 185-0, 7h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 475 ms (selfie)
  maxAssetCacheWait: 759 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    theverge.com: 1
    associates-amazon.com: 2
    facebook.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    linkedin.com: 1
    moatads.com: 1
    outbrain.com: 1
    parsely.com: 2
    voxmedia.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test in a new profile with only uBO, force update the filter lists and no other configs in Firefox?

**Comment by zootedb0t** [comment]
I just tested this on new profile. The issue remains the same

![Screenshot (11)](https://user-images.githubusercontent.com/62596687/166101476-65c93b3d-8696-4bd2-9083-b5adba47cd7d.png)
e

**Comment by stephenhawk8054** [comment]
Which region are you when browsing the site? Try turning off FF's built-in tracking protection and if you are using any:

- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains

**Comment by zootedb0t** [comment]
I am using nextdns. After deactivating it the issue was solved.

**Comment by zootedb0t** [comment]
You can close the issue
