### ISSUE TITLE
cocomanga.com: detection

### ISSUE THREAD

**Issue by netyami** [uBlockOrigin/uAssets#13020]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cocomanga.com/21653/1/114.html`

### Category

detection

### Describe the issue

this site does't work when use Built-in uBlock filters 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 78023
  cosmetic: 166
  scriptlet: 35103
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    adguard-annoyance: 52467-45474, 6h.43m
    adguard-generic: 63980-32284, 2h.37m
    adguard-mobile: 7672-5960, 6h.41m
    adguard-social: 16942-16365, 2d.20h.50m
    fanboy-cookiemonster: 31836-29161, 15h.1m
    ublock-annoyances: 4363-1377, 6h.42m
  default: 
    user-filters: 190-14, never
    THA-0: 999-655, 2h.36m
    easylist: 66537-34787, 2d.20h.49m
    ublock-abuse: 74-1, 10d.23h.43m
    ublock-badware: 4125-691, 6h.45m
    ublock-filters: 30977-10164, 14h.45m
    ublock-privacy: 211-11, 10d.23h.42m
    ublock-quick-fixes: 183-81, 6h.38m
    ublock-unbreak: 1767-255, 6h.44m
    urlhaus-1: 8349-0, 6h.39m
filterset (user): [array of 190 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1183 ms
  maxAssetCacheWait: 383 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    cocomanga.com: 1
```
</details>

**Comment by okiehsch** [comment]
You do realize that their is already an open issue for that site?
The points you checked are there for a reason, I suggest you read them carefully, including the last one....
