### ISSUE TITLE
euw.op.gg: ad placeholder

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#13023]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://euw.op.gg/`

### Category

ads

### Describe the issue

Choose NEW design!

Big ad placeholder stays on home page below "downlaod now" button and above "Experience the fast speed of the OP.GG Desktop App!Now concentrate more on the game.".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81530
  cosmetic: 47802
  scriptlet: 19590
  html: 652
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    ublock-annoyances: 4362-4, 2d.3h.5m
  default: 
    user-filters: 350-0, never
    ublock-filters: 31570-46, 1d.3h.29m
    ublock-badware: 4108-3, 2d.3h.11m
    ublock-privacy: 218-0, 2d.3h.10m
    ublock-abuse: 75-0, 2d.3h.9m
    ublock-unbreak: 1778-0, 2d.3h.8m
    easylist: 66580-261, 2d.3h.7m
    easyprivacy: 26907-141, 2d.3h.6m
    urlhaus-1: 8350-0, 23h.45m
    DEU-0: 5644-1, 23h.44m
    ublock-quick-fixes: 174-0, 8h.26m
filterset (user): [array of 347 redacted]
trustedset: 
  added: [array of 117 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 8 redacted]
urlRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 100 ms (selfie)
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    datadoghq-browser-agent.com: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    jsdelivr.net: 2
    riotgames.com: 1
    vntsm.com: 1
```
</details>

**Comment by krystian3w** [comment]
Maybe due: https://github.com/uBlockOrigin/uAssets/issues/12983 - try add to custom list these:

`op.gg##[id^="div-gpt-ad"][id^="div-gpt-ad"]:upward(div[class])`

**Comment by Janmm14** [comment]
> Maybe due: #12983 - try add to custom list these:
> 
> `op.gg##[id^="div-gpt-ad"][id^="div-gpt-ad"]:upward(div[class])`
> ![obraz](https://user-images.githubusercontent.com/35370833/166073732-d758ce8b-6ae2-4213-9e95-1d553d567a57.png) 	![obraz](https://user-images.githubusercontent.com/35370833/166073529-c12185e0-b1f1-4beb-9ecd-d94e933f7be1.png)
> old 	new
> 
> duplicate id is to override `#@#`.

That filter breaks https://euw.op.gg/multisearch

**Comment by krystian3w** [comment]
So must wait as will be fixed by stephenhawk8054 / JobcenterTycoon.

For now possible try use:


`op.gg##:not(:matches-path(/multisearch)) [id^="div-gpt-ad"][id^="div-gpt-ad"]:upward(div[class])`

**Comment by krystian3w** [comment]
Maybe safe is jump 1 node higher:

`##[id^="div-gpt-ad"]:upward(1)`

**Comment by Janmm14** [comment]
> ##[id^="div-gpt-ad"]:upward(1)

nope

**Comment by krystian3w** [comment]
Again break search? Then may try:

`##[id^="div-gpt-ad"]:style(position: fixed !important; top: -10000px !important; left: 10000px !important;)`

On my side gpt ad is resized to 1x1px square without scale by CSS3 to big rectangles:

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale
https://developer.mozilla.org/en-US/docs/Web/CSS/transform

**Comment by krystian3w** [comment]
AdGuard Base may detected stable class for ads:

```
op.gg##div[class*="er9l3dz"]
```

**Comment by Janmm14** [comment]
> `op.gg##:not(:matches-path(/multisearch)) [id^="div-gpt-ad"]:upward(div[class])`
Just as a note, this works.

> `op.gg##div[class*="er9l3dz"]`
This doesn't hide ad placeholder on homepage and generally seems to do nothing.

**Comment by krystian3w** [comment]
If blinks are no problem then try:

`##div[class]:matches-css-after(content: /op\.gg/i)`

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again? The filters for this site were adjusted a few times recently, and I see your last update was 2 days ago. So I want to make sure which placeholders are still left at which links.

**Comment by krystian3w** [comment]
Both layouts have placeholder on `:matches-path(/^/$/)`.

**Comment by stephenhawk8054** [comment]
Currently this works for me for both old and new UI. Can you test?

`op.gg##[id^="div-gpt-ad"]:not([class]):upward(div[class])`

**Comment by krystian3w** [comment]
I can not use search bar on that site - I need video tutorial how use.
