### ISSUE TITLE
[nsfw] spcs.me: ads

### ISSUE THREAD

**Issue by ssdhub** [uBlockOrigin/uAssets#13021]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://spcs.me/`

### Category

ads

### Describe the issue

there are ads in any section

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 80
filterset (summary): 
  network: 99847
  cosmetic: 64463
  scriptlet: 17946
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 49-0, never
    RUS-0: 41266-9, 1d.4h.38m
    easylist: 66556-64, 2d.7h.57m
    easyprivacy: 26907-217, 2d.7h.56m
    plowe-0: 3676-810, 1h.22m
    ublock-abuse: 74-1, 5d.2h.30m
    ublock-badware: 4104-93, 2d.7h.55m
    ublock-filters: 30949-139, 2d.7h.54m
    ublock-privacy: 212-2, 5d.2h.29m
    ublock-quick-fixes: 181-0, 18m
    ublock-unbreak: 1768-42, 2d.7h.53m
    urlhaus-1: 8087-0, 19m
filterset (user): [array of 49 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2295 ms
  maxAssetCacheWait: 1012 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any ads. Can you describe in more details and take some screenshots of the ads?

**Comment by mapx-** [comment]
ads, for example here: `https://spcs.me/sz/video/`

@dimisa-RUAdList

![image](https://user-images.githubusercontent.com/10303732/166105344-b7d34a18-141f-4a6c-b70c-9e72c40c94d5.png)

**Comment by dimisa-RUAdList** [comment]
The domain did not work for almost two years: https://github.com/easylist/ruadlist/commit/ff5eeee4cc937fb594e261ebea1bda18ae21eea4

Returned previously deleted rules: https://github.com/easylist/ruadlist/commit/afedc0423cc631eca3b806e58d0a3e87b633195f
