### ISSUE TITLE
op.gg looks weird

### ISSUE THREAD

**Issue by lazinism** [uBlockOrigin/uAssets#13033]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.op.gg/summoners/kr/%EC%8B%A4%EB%B2%84%EC%93%B0%EB%A0%88%EA%B8%B0%EC%98%88%EC%A0%95`

### Describe the issue

![image](https://user-images.githubusercontent.com/3297355/166114086-88263c70-f0bb-49bf-b749-d83965364b7b.png)
What it should be look on [this](https://www.op.gg/summoners/kr/%EC%8B%A4%EB%B2%84%EC%93%B0%EB%A0%88%EA%B8%B0%EC%98%88%EC%A0%95)
and what it looks like is
![image](https://user-images.githubusercontent.com/3297355/166114115-df378f68-c411-4d12-bd6c-0d07a5c15ac1.png)
the parts omitted is
![image](https://user-images.githubusercontent.com/3297355/166114142-b334b598-5337-45af-922d-f0b81c47cd50.png)
2nd, 3rd divs

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3297355/166114337-a784a8bf-4a1f-43f6-8c2d-682606cf4ba5.png)
![image](https://user-images.githubusercontent.com/3297355/166114353-442dbc2f-c4dc-4c6b-a6df-f03fab872d9b.png)

### Notes

I think
`op.gg##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement)`
breaks the page
so we should selectively block first div which has div.vm-placement
`op.gg##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement) > div:not([class], [id])`
maybe?

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81919
  cosmetic: 43623
  scriptlet: 16819
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 24-0, never
    KOR-1: 1360-8, 8m
    easylist: 66334-71, 8m
    easyprivacy: 26925-131, 8m
    plowe-0: 3676-812, 8m
    ublock-abuse: 75-0, 8m
    ublock-badware: 4122-92, 8m
    ublock-filters: 30928-93, 8m
    ublock-privacy: 212-5, 8m
    ublock-quick-fixes: 185-28, 8m
    ublock-unbreak: 1773-40, 8m
    urlhaus-1: 8183-0, 8m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 637 ms (selfie)
  maxAssetCacheWait: 299 ms
```
</details>

**Comment by krystian3w** [comment]
Maybe after: #13023

**Comment by JobcenterTycoon** [comment]
Ok just to clarify the problematic sites:

`https://www.op.gg/summoners/kr/%EC%8B%A4%EB%B2%84%EC%93%B0%EB%A0%88%EA%B8%B0%EC%98%88%EC%A0%95` (old design)
`https://euw.op.gg/champions/aatrox/top/build` (new design)
`https://euw.op.gg/summoners/euw/Zueb` (new design)

Test

```
op.gg#@#div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement)
op.gg##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement:not([style]))
op.gg##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placement[data-display-type="hybrid-banner"])
```

It hides the placeholders on old and new design without breaking the site on my end

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon No false positives for me so far 👍

**Comment by Janmm14** [comment]
The only problem with these filters is that the placeholder is visible briefly during loading.

**Comment by stephenhawk8054** [comment]
> The only problem with these filters is that the placeholder is visible briefly during loading. Not sure how easy it is to fix that without breaking other stuff, so maybe just go for it.

Yeah, it's unavoidable for sites that have inconsistent DOM.
