### ISSUE TITLE
starlive.xyz: popups

### ISSUE THREAD

**Issue by xlollomanx** [uBlockOrigin/uAssets#13034]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://starlive.xyz/embed.php?id=live37`

### Category

popups

### Describe the issue

To start watching the stream you have to click the play button but this will open an annoying window full of ads. It happend even while watching the stream because after a while the media player control buttons disappear. To make them reappear you have to click on the stream window but this will open again that annoying window.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 87111
  cosmetic: 50160
  scriptlet: 16737
  html: 647
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31526-37, 3m
    ublock-badware: 4126-3, 3m
    ublock-privacy: 217-0, 3m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1784-0, 3m
    ublock-quick-fixes: 186-0, 3m
    easylist: 66334-590, 3m
    easyprivacy: 26925-579, 3m
    urlhaus-1: 8183-0, 3m
    plowe-0: 3676-3, 3m
    ITA-0: 12994-1, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 444 ms (selfie)
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    amung.us: 2
    celeritascdn.com: 2
    denetsuk.com: 1
    googletagmanager.com: 2
    histats.com: 1
    intellipopup.com: 1
    jomtingi.net: 1
    nessainy.net: 2
    netrailed.com: 1
    shitcustody.com: 1
    venetrigni.com: 1
```
</details>

**Comment by xlollomanx** [comment]
@mapx- Sorry for re-open but seems the filters has been neutralized. Btw seems that filters used broke the main page: on https://starlive.xyz/
To be more clear  if you click on a category (for example click on "Serie A" in the screenshot) it should display different streams, it works if I disable ublock. Thank you for your efforts.
![image](https://user-images.githubusercontent.com/6764804/166152538-4fb22aee-9bf5-4826-b4c5-395ec96f251c.png)

**Comment by mapx-** [comment]
It should work now, just update uBO filter lists and test again

**Comment by xlollomanx** [comment]
Thanks it works now

**Comment by rapperskull** [comment]
I think this issue needs to be re-opened. I updated the filter lists, but I can't open the categories. It works if I disable uBO.

**Comment by mapx-** [comment]
I added a fix, maybe you are using firefox ?

**Comment by rapperskull** [comment]
Yes, I'm using Firefox. I updated the filters again and now it works. Thank you.
