### ISSUE TITLE
ruyamanga.com: detection

### ISSUE THREAD

**Issue by Cyber0120** [uBlockOrigin/uAssets#13037]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ruyamanga.com/`

### Category

detection

### Describe the issue

Ad blocker detects

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 116779
  cosmetic: 85639
  scriptlet: 29451
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63976-676, 1d.7h.20m
    adguard-mobile: 7675-49, 1d.7h.19m
    adguard-spyware: 25725-667, 1d.7h.18m
    adguard-spyware-url: 586-13, 1d.7h.17m
  default: 
    user-filters: 2-0, never
    TUR-0: 8834-95, 1d.7h.21m
    easylist: 66241-871, 1d.7h.16m
    easyprivacy: 26914-10072, 1d.7h.15m
    plowe-0: 3678-965, 5d.9h.6m
    ublock-abuse: 74-0, 5d.9h.5m
    ublock-badware: 4125-294, 1d.7h.14m
    ublock-filters: 30949-3219, 1d.7h.13m
    ublock-privacy: 212-39, 5d.9h.5m
    ublock-quick-fixes: 187-9, 1h.32m
    ublock-unbreak: 1766-96, 1d.7h.12m
    urlhaus-1: 8183-0, 1h.31m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 960 ms (selfie)
  maxAssetCacheWait: 1084 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    onesignal.com: 1
    virgul.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list.
