### ISSUE TITLE
111.90.150.149: ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13030]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

```
https://111.90.150.149/mardaani/

https://111.90.150.149/?s=mardani&post_type%5B%5D=post&post_type%5B%5D=tv
```

### Category

ads

### Describe the issue

preroll ads and banner ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 83080
  cosmetic: 49023
  scriptlet: 16902
  html: 680
listset (total-discarded, last updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt: 187-0, 45m
  default: 
    user-filters: 971-2, never
    ublock-filters: 31609-228, 45m
    ublock-badware: 4121-26, 45m
    ublock-privacy: 218-0, 45m
    ublock-abuse: 75-0, 45m
    ublock-unbreak: 1790-0, 45m
    adguard-mobile: 7676-156, 45m
    easylist: 66334-863, 45m
    easyprivacy: 26925-586, 45m
    urlhaus-1: 8128-0, 45m
    plowe-0: 3676-3, 45m
    ublock-quick-fixes: 187-187, 45m
filterset (user): [array of 733 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 652 ms (selfie)
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    111.90.150.149: 4
    googletagmanager.com: 1
    histats.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed here: [https://github.com/uBlockOrigin/uAssets/commit/8382253d4e1c3f1985945efcf11d037ffb863650](https://github.com/uBlockOrigin/uAssets/commit/8382253d4e1c3f1985945efcf11d037ffb863650)

**Comment by ghajini** [comment]
`https://111.90.150.149/?s=mardani&post_type%5B%5D=post&post_type%5B%5D=tv`

This is remained here
![Screenshot_20220430-162215-867](https://user-images.githubusercontent.com/20338483/166102511-c89a8094-ceac-4367-a3b3-b14466c49d17.png)

`111.90.150.149##[href="http://buaksib.in/"]`

**Comment by stephenhawk8054** [comment]
> `https://111.90.150.149/?s=mardani&post_type%5B%5D=post&post_type%5B%5D=tv`
> 
> This is remained here ![Screenshot_20220430-162215-867](https://user-images.githubusercontent.com/20338483/166102511-c89a8094-ceac-4367-a3b3-b14466c49d17.png)
> 
> `111.90.150.149##[href="http://buaksib.in/"]`

Ah right, I forgot mobile has different structure.
