### ISSUE TITLE
moviesjoy.one: popups

### ISSUE THREAD

**Issue by jeffreybexz** [uBlockOrigin/uAssets#13035]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://moviesjoy.one/search?keyword=top+boy&vrf=GnIFj62H0RJnv%2FXhYM`

### Category

popups

### Describe the issue

whenever I go on this website and have Ublock on for some reason most of the time it still gives me popups and opens new windows and tabs to unsafe virus websites I have tried turning Ublock on and off and have tried many different things and they just won't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://user-images.githubusercontent.com/104692959/166117666-e0e2e636-0198-4418-b5ec-4581e385103c.png

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81666
  cosmetic: 42778
  scriptlet: 16779
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66601-51, 2d.21h.40m
    easyprivacy: 26907-121, 2d.22h.54m
    plowe-0: 3682-804, 9d.17h.22m
    ublock-abuse: 75-0, 21h.34m
    ublock-badware: 4104-93, 3d.22h.1m
    ublock-filters: 30980-108, 3d.21h.59m
    ublock-privacy: 213-2, 21h.35m
    ublock-quick-fixes: 184-0, 16h.54m
    ublock-unbreak: 1767-43, 3d.22h
    urlhaus-1: 8087-0, 16h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1483 ms (selfie)
  maxAssetCacheWait: 943 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    addthis.com: 1
    amung.us: 1
    ashoupsu.com: 2
    denetsuk.com: 1
    inpage-push.com: 1
    jomtingi.net: 3
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists

just do it
