### ISSUE TITLE
flipgrid.com: breakage

### ISSUE THREAD

**Issue by ReiderApprentice** [uBlockOrigin/uAssets#13047]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://flipgrid.com/3e442b23?av=1`

### Category

breakage

### Describe the issue

When Trying to use flipgrid, console is telling me that Ublock is blocking the use of my camera

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82222
  cosmetic: 42848
  scriptlet: 16770
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66297-51, 7h.14m
    easyprivacy: 26926-121, 7h.16m
    plowe-0: 3679-805, 2d.23h.39m
    ublock-abuse: 74-0, 6d.4h.59m
    ublock-badware: 4140-92, 7h.17m
    ublock-filters: 30924-87, 7h.15m
    ublock-privacy: 212-3, 7d.2h.54m
    ublock-quick-fixes: 192-0, 6m
    ublock-unbreak: 1781-40, 7h.13m
    urlhaus-1: 8970-0, 7m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 719 ms (selfie)
  maxAssetCacheWait: 480 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    microsoft.com: 5
    newrelic.com: 1
    nr-data.net: 3
```
</details>

**Comment by mapx-** [comment]
> When Trying to use flipgrid, console is telling me that Ublock is blocking the use of my camera

Provide a screenshot with the console content

**Comment by llacb47** [comment]
Can't reproduce, I used flipgrid with ubo enabled and recorded a video with my webcam yesterday.
