### ISSUE TITLE
sephora.com: breakage

### ISSUE THREAD

**Issue by asymmetricia** [uBlockOrigin/uAssets#13043]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sephora.com/shop/eye-cream-dark-circles`

### Category

breakage

### Describe the issue

Navigation links for different categories (e.g., Skincare > Moisturizers) don't work; they produce a JS error in the console, and no navigation occurs:

```
Uncaught ReferenceError: insideFrontInterface is not defined
    closeChatPane HomeChat.js:4
    linkToSPA History.js:202
    onClick BccRwdLinkHOC.f.jsx:61
    React 12
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    g 3c812ae7f6642a03f9e3b5f9aca755a11630011008b74:24
    apply 3c812ae7f6642a03f9e3b5f9aca755a11630011008b74:21
    Y 3c812ae7f6642a03f9e3b5f9aca755a11630011008b74:222
    apply 3c812ae7f6642a03f9e3b5f9aca755a11630011008b74:21
    y Dropdown.ctrlr.jsx:162
    g 3c812ae7f6642a03f9e3b5f9aca755a11630011008b74:24
HomeChat.js:4:8
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82099
  cosmetic: 42840
  scriptlet: 16735
  html: 646
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 31574-31, 2d.23h.36m
    ublock-badware: 4113-3, 2d.23h.39m
    ublock-privacy: 217-0, 7d.1h.33m
    ublock-abuse: 75-0, 23h.18m
    ublock-unbreak: 1779-0, 2d.23h.37m
    easylist: 66334-650, 1d.12h.11m
    easyprivacy: 26913-577, 2d.23h.38m
    plowe-0: 3678-3, 7d.1h.31m
    urlhaus-1: 8865-0, 6h.2m
    ublock-quick-fixes: 188-0, 2h.1m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 15 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 699 ms (selfie)
  maxAssetCacheWait: 145 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    sephora.com: 4
    demdex.net: 1
    forter.com: 3
    go-mpulse.net: 1
    inside-graph.com: 1
    kampyle.com: 4
    techlab-cdn.com: 5
```
</details>

**Comment by mapx-** [comment]
add

```
@@||sephora-track.inside-graph.com/gtm/*/inside.min.js$script,domain=sephora.com
@@||sephora-track.inside-graph.com/ig.js$script,domain=sephora.com
```

EP issue @monzta @khrin
