### ISSUE TITLE
Black boxes on `msn.com`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#13052]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.msn.com/nl-nl/lifestyle/reizen/solo-reizen-als-vrouw-dit-zijn-de-veiligste-en-onveiligste-landen-ter-wereld/ar-AAWzyAN?ocid=EMMX&cvid=c81167aa2bca4707bb39cc0d43fee995`

### Describe the issue

There are under the article several black boxes. But I can't block them, because the element picker can't pick it. 
See the screenshot for the problem: the select element can't be picked. 

### Screenshot(s)

<details> 

![image](https://user-images.githubusercontent.com/81161435/166270685-656299e8-4323-4887-a094-b5bb0e65a530.png)

</details>

### Notes

I'm not sure this is an filter issue.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 69045
  cosmetic: 44834
  scriptlet: 16826
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2996-10, 7h.31m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 2069-0, 7h.31m
  default: 
    user-filters: 214-0, never
    ublock-filters: 30941-90, 7h.26m
    ublock-unbreak: 1781-10, 7h.25m
    easylist: 66297-134, 7h.24m
    easyprivacy: 26926-194, 7h.23m
filterset (user): [array of 162 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1247 ms (selfie)
  maxAssetCacheWait: 599 ms
```
</details>

**Comment by JobcenterTycoon** [comment]
The black placeholders can be hidden but the space is still here. Not sure if it can be resolved

**Comment by JohnyP36** [comment]
> The black placeholders can be hidden but the space is still here. Not sure if it can be resolved

Which rule do you propose?

**Comment by JobcenterTycoon** [comment]
I tried `msn.com##msft-article-card[card-fill-color="#2E2E2E"]:not(.contentCard)` it removed the boxed but not the space

**Comment by JohnyP36** [comment]
@JobcenterTycoon 

As you can see in the screenshot below the picker picks nothing. 

![image](https://user-images.githubusercontent.com/81161435/166307507-103d264a-f516-4c6d-99a1-095579e95058.png)


I thing the problem lies in the fact the msn.nl makes use of `#shadow-root (open)` uBlock can not pick elements which are in this branche (see screenshot in the [issue tracker](https://user-images.githubusercontent.com/81161435/166270685-656299e8-4323-4887-a094-b5bb0e65a530.png)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/803

**Comment by JohnyP36** [comment]
> [uBlockOrigin/uBlock-issues#803](https://github.com/uBlockOrigin/uBlock-issues/issues/803)

I see what the problem is. Thank you.
