### ISSUE TITLE
bilibili.com

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#13059]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bilibili.com/video/BV1zq4y1z7mR`

### Describe the issue

`||hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js$script,redirect-rule=noopjs,domain=bilibili.com` was introduced in https://github.com/uBlockOrigin/uAssets/commit/8c83811034325ccf8a37156d2174668a54dbccc4 and https://github.com/uBlockOrigin/uAssets/commit/0699cd1d155cc190ddfd086b86d5946e38bf5c07, presumably to counter comment breakage caused by https://github.com/easylist/easylist/commit/3b5e54c7102510287749fc50891df26a9c61b9cd. Not sure why it was later removed in https://github.com/uBlockOrigin/uAssets/commit/b9ae01f8441b2f2f869fcf28c40d5714cd7a665e, because noop-ing the script works (and still does) and noop-ing wasn't necessary until some time around late 2020 to mid 2021 (personal experience). Which is all the more reason for blocking/redirecting it (at least for uBO users) because this looks very much like a tracking script.

### uBlock Origin version

1.42.4

### Browser name and version

 Firefox 99.0.1

### Settings

EasyList China/ AdGuard Chinese

### Notes

```
! Need countering EasyList China (and thereby AdGuard Chinese)
! https://github.com/easylist/easylistchina/commit/c23db26f68d137404dd41e843e11b01740bbaab2
@@||hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js$badfilter
||hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js$script,redirect=noopjs,domain=bilibili.com
```

**Comment by JobcenterTycoon** [comment]
AdGuard Chinese support redirect too @Yuki2718

**Comment by stephenhawk8054** [comment]
It was removed by EP: [https://github.com/easylist/easylist/commit/97e541ca83544f311d7cad9fba53cd250cc050bf](https://github.com/easylist/easylist/commit/97e541ca83544f311d7cad9fba53cd250cc050bf), and the `quick fix` list is just for hotfixing the breakage, hence removed after EP removing that filter.

About the whitelisting, does redirecting it causes any breakages elsewhere? @Yuki2718

**Comment by Yuki2718** [comment]
In my quick test redirecting appears to be fine + OP's reports have been reliable. But the script looks to be tracker, so probably better to add to AGTPF and uBlock Privacy.
