### ISSUE TITLE
[nsfw] pornolab.net: ads

### ISSUE THREAD

**Issue by kiencuongpo** [uBlockOrigin/uAssets#13055]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pornolab.net/forum/index.php`

### Category

ads

### Describe the issue

Ads on the left side and bottom of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 83979
  cosmetic: 45201
  scriptlet: 19659
  html: 654
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4373-5, 1d.16h.12m
  default: 
    user-filters: 2-0, never
    ublock-filters: 31546-29, 1d.16h.17m
    ublock-badware: 4144-3, 1d.16h.16m
    ublock-privacy: 217-0, 9d.19h.49m
    ublock-abuse: 74-0, 9d.19h.49m
    ublock-unbreak: 1784-0, 1d.16h.15m
    ublock-quick-fixes: 192-0, 17h.50m
    easylist: 66297-594, 1d.16h.14m
    easyprivacy: 26926-582, 1d.16h.13m
    urlhaus-1: 9661-0, 17h.49m
    plowe-0: 3678-3, 9d.19h.49m
    VIE-1: 1981-7, 11h.24m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 460 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `RUS: RU AdList` in `Regions, languages` section of [Filter lists pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists)?

**Comment by kiencuongpo** [comment]
> Can you enable `RUS: RU AdList` in `Regions, languages` section of [Filter lists pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists)?

OK, Thanks!
