### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by BabeRossey** [uBlockOrigin/uAssets#13054]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Im getting video ads, like an ad for adblocker 360. bro you got competition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82816
  cosmetic: 42777
  scriptlet: 16755
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 14-1, never
    easylist: 66297-51, 2d.6h.38m
    easyprivacy: 26926-121, 2d.6h.37m
    plowe-0: 3676-805, 1d.19h.59m
    ublock-abuse: 74-0, 11d.5h.14m
    ublock-badware: 4140-92, 2d.6h.41m
    ublock-filters: 30931-87, 2d.6h.40m
    ublock-privacy: 212-3, 11d.5h.13m
    ublock-unbreak: 1773-40, 2d.6h.39m
    urlhaus-1: 9661-0, 4h.21m
filterset (user): [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13984 ms (selfie)
  maxAssetCacheWait: 6396 ms
popupPanel: 
  blocked: 235
  blockedDetails: 
    youtube.com: 208
    doubleclick.net: 2
    google.com: 8
    googleadservices.com: 3
    googlesyndication.com: 5
    googlevideo.com: 9
```
</details>

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
