### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by DaniBedd** [uBlockOrigin/uAssets#13056]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Describe the issue

![image](https://user-images.githubusercontent.com/104833811/166443423-4433cb78-8b64-46fa-b71a-7412f44a767f.png)
![adouy](https://user-images.githubusercontent.com/104833811/166443481-df85d577-72b2-413b-9abb-eeeb22793b2c.jpg)

Ads appear in top line, this has only just started happening, refresh, cache clearing, reinstalling of extension has not affected their appearance.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82792
  cosmetic: 42722
  scriptlet: 16754
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 2h.12m
  default: 
    user-filters: 0-0, never
    easylist: 66239-51, 4d.26m
    easyprivacy: 26914-121, 4d.22m
    plowe-0: 3682-804, 12d.2h.36m
    ublock-abuse: 74-0, 8d.1h.31m
    ublock-badware: 4125-92, 4d.25m
    ublock-filters: 30979-145, 4d.24m
    ublock-privacy: 212-2, 8d.1h.32m
    ublock-unbreak: 1768-42, 4d.23m
    urlhaus-1: 9572-0, 2h.13m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 459 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 112
  blockedDetails: 
    live.com: 2
    3lift.com: 3
    adnxs.com: 3
    microsoft.com: 19
    office.net: 85
```
</details>

**Comment by Procyon-b** [comment]
(Using a hotmail account here)
This is caused by the list `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt`. It allows `@@||taboola.com^*` and ads get in.

**Comment by Procyon-b** [comment]
I have my own userstyle to recover whitespace on `outlook.live.com` .
From this, I know that there is the possibility to hide the ad-slot when it contains not ad, or to hide it permanently (but we won't notice if ads are loaded)
Is it usefull for one of ublock own lists, or for easylist ?
