### ISSUE TITLE
nitter.net: breakage

### ISSUE THREAD

**Issue by Arutemu64** [uBlockOrigin/uAssets#13057]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nitter.net/firefoxbeta`

### Category

breakage

### Describe the issue

White page when trying to load this page with uBO enabled. With uBO disabled this page loads correctly every time.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 144353
  cosmetic: 215257
  scriptlet: 36803
  html: 658
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64088-4989, 2h.26m
    adguard-spyware: 25887-10734, 2h.26m
    adguard-annoyance: 52583-177, 2h.26m
    adguard-social: 16950-855, 2h.26m
    fanboy-annoyance: 70804-4102, 1m
    ublock-annoyances: 4380-144, 2h.26m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31544-369, 14h.3m
    ublock-badware: 4144-3, 14h.3m
    ublock-privacy: 217-0, 14h.3m
    ublock-abuse: 75-0, 14h.3m
    ublock-unbreak: 1787-0, 14h.3m
    ublock-quick-fixes: 193-0, 14h.3m
    easylist: 66322-684, 14h.3m
    easyprivacy: 26931-671, 14h.3m
    urlhaus-1: 9661-0, 14h.3m
    plowe-0: 3676-4, 14h.3m
    RUS-0: 41310-504, 14h.3m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 780 ms (selfie)
  maxAssetCacheWait: 907 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I can load it normally.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/166455777-96b8df45-106c-4fb9-9690-e31cf2c6347b.png)

</details>

Your logger also said there's nothing blocked in uBO too.
