### ISSUE TITLE
analytics.magstimconnect.net: breakage

### ISSUE THREAD

**Issue by andynugent** [uBlockOrigin/uAssets#13058]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://analytics.magstimconnect.net`

### Category

breakage

### Describe the issue

We have a backend REST API https://api-analytics.magstimconnect.net/api accessed from https://analytics.magstimconnect.net

"/api-analytics." part of the URL is identified as an ad (this has only started occuring recently).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/6598396/166457547-b13c8d0b-8539-4ecd-a85b-cf1e8b27da0e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82934
  cosmetic: 42855
  scriptlet: 16783
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.16h.33m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 66327-51, 54m
    easyprivacy: 26931-121, 50m
    plowe-0: 3679-805, 6d.17h.47m
    ublock-abuse: 74-0, 6d.17h.46m
    ublock-badware: 4140-92, 53m
    ublock-filters: 30961-91, 52m
    ublock-privacy: 212-3, 6d.17h.45m
    ublock-quick-fixes: 165-0, 17h.7m
    ublock-unbreak: 1781-40, 51m
    urlhaus-1: 9661-0, 17h.8m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 298 ms (selfie)
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    magstimconnect.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr @monzta
