### ISSUE TITLE
movgotv.net: popups

### ISSUE THREAD

**Issue by revivemarketing** [uBlockOrigin/uAssets#13064]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://movgotv.net/series/the-blacklist/`

### Category

popups

### Describe the issue

When accessing the site, if you click anywhere on the page or wait for a specified timeout, a popup window will show, and hide behind your primary window. Good, ole fashioned annoying popup!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1820684/166573241-a5fb2019-6609-4b98-aaa5-e2693b07c53b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 80939
  cosmetic: 42179
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65018-167, never
    easyprivacy: 26734-100, never
    plowe-0: 3690-811, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-97, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-29, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1528 ms
  maxAssetCacheWait: 20 ms
popupPanel: 
  blocked: 14
  no-popups: true
  blockedDetails: 
    addthis.com: 1
    adsco.re: 1
    d11enq2rymy0yl.cloudfront.net: 1
    doubleclick.net: 2
    dyrfxuvraq0fk.cloudfront.net: 1
    google-analytics.com: 1
    xadsmart.com: 1
    youtube.com: 6
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
movgotv.net##+js(nowoif)
```
also, force-update your filter lists. They don't seem up-to-date.

**Comment by revivemarketing** [comment]
Excellent, I will try that filter out..
I purged the cache and updated the Filter list just before submitting the ticket.

**Comment by revivemarketing** [comment]
Unfortunately, that filter didn't work. 
I added the filter, purged cache, and re-updated the Filter List.
The site still pops a full window if you click anwyhere.

**Comment by revivemarketing** [comment]
Perfect. Great work! Thank you.
