### ISSUE TITLE
[nsfw] porntn.com: detection

### ISSUE THREAD

**Issue by tempaccountnotgonnause** [uBlockOrigin/uAssets#13068]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://porntn.com/videos/3484/goddess-alexandra-snow-position-available-personal-slave-10-december-2020/`

### Category

detection

### Describe the issue

Website blocks playback of video when adblocker is detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82237
  cosmetic: 42914
  scriptlet: 16778
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 35-3, never
    easylist: 66373-51, 7m
    easyprivacy: 26935-121, 7m
    plowe-0: 3678-805, 7m
    ublock-abuse: 75-0, 7m
    ublock-badware: 4140-92, 7m
    ublock-filters: 30958-92, 7m
    ublock-privacy: 212-2, 7m
    ublock-quick-fixes: 206-0, 7m
    ublock-unbreak: 1777-40, 7m
    urlhaus-1: 8902-0, 7m
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 368 ms (selfie)
  maxAssetCacheWait: 416 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    porntn.com: 5
    dropkickmedia.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can play the video normally. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by JohnyP36** [comment]
On my side I don't have an adblock detection.
