### ISSUE TITLE
ygosu.com: popups

### ISSUE THREAD

**Issue by ond145** [uBlockOrigin/uAssets#13061]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ygosu.com/`

### Category

popups

### Describe the issue

Even if you turn the block on or off
The message "Failed to load images. (AdBlock Exception)" is output.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![제목 없음](https://user-images.githubusercontent.com/104849749/166487017-f634a67e-ed25-42de-9aa8-134d105725f2.png)
be-4c27-a55f-da001858de65.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 83327
  cosmetic: 43539
  scriptlet: 16801
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-0, never
    KOR-1: 1365-8, 23h.49m
    easylist: 66297-71, 1d.13h.43m
    easyprivacy: 26926-131, 1d.13h.42m
    plowe-0: 3679-812, 7d.9h.32m
    ublock-abuse: 74-0, 7d.23h.49m
    ublock-badware: 4140-92, 1d.13h.41m
    ublock-filters: 30930-93, 1d.13h.40m
    ublock-privacy: 212-6, 7d.23h.48m
    ublock-unbreak: 1781-40, 1d.13h.39m
    urlhaus-1: 9661-0, 23h.48m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 720 ms (selfie)
  maxAssetCacheWait: 230 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    clickmon.co.kr: 1
    daumcdn.net: 2
    doubleclick.net: 2
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by JobcenterTycoon** [comment]
Clear the browser cache, update the filter lists and enable `uBlock filters – Quick fixes`

Be sure no other adblocker like Adblock Plus is active

**Comment by ond145** [comment]
Clear the browser cache, update the filter lists and enable uBlock filters – Quick fixes
checked
Be sure no other adblocker like Adblock Plus is active
checked
Also you have 11 custom filter, be sure its not cause the issue on ygosu
checked

Still having the same problem.

**Comment by ond145** [comment]
> Can you force update the filter lists and test again?
Still having the same problem.

**Comment by JobcenterTycoon** [comment]
If you have a antivirus with "Anti Banner" feature, disable the antivirus adblocking

**Comment by stephenhawk8054** [comment]
heck if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.
