### ISSUE TITLE
touch.mail.ru: breakage

### ISSUE THREAD

**Issue by vitalii0133** [uBlockOrigin/uAssets#13069]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://touch.mail.ru/`

### Category

breakage

### Describe the issue

With the default regional filter "RU AdList" enabled, this site does not load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 123222
  cosmetic: 95033
  scriptlet: 18125
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 30471-30, 1h.6m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1437-24, 1h.6m
    curben-phishing: 14560-0, 51m
  default: 
    user-filters: 11-0, never
    RUS-0: 41339-136, 1h.5m
    adguard-mobile: 7676-36, 4d.23m
    easylist: 66333-265, 4d.22m
    easyprivacy: 26925-526, 3d.10h.12m
    plowe-0: 3682-898, 12d.5h.24m
    ublock-abuse: 75-1, 3d.8h.3m
    ublock-badware: 4140-92, 2d.20h.15m
    ublock-filters: 31036-140, 2d.20h.14m
    ublock-privacy: 212-10, 2d.20h.13m
    ublock-quick-fixes: 205-0, 3h.6m
    ublock-unbreak: 1778-44, 2d.20h.12m
    urlhaus-1: 8902-1, 51m
filterset (user): [array of 11 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 367 ms (selfie)
  maxAssetCacheWait: 243 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    mail.ru: 5
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like it needs an account. @dimisa-RUAdList Sorry do you have an account for this site to check it?

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/738fde40f1ccb3583de5ce6aebe1c5605e1089d3
