### ISSUE TITLE
loreps.com: popups

### ISSUE THREAD

**Issue by stuartgamesh** [uBlockOrigin/uAssets#13063]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://loreps.com/prod/ngo.html?lu=https%3A%2F%2Fadverster.g2afse.com%2Fclick%3Fpid%3D162%26offer_id%3D10%26sub4%3D5246291%26sub1%3D16516095923042895126145885930285399`

### Category

popups

### Describe the issue

its a redirect pop up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 86060
  cosmetic: 47556
  scriptlet: 16976
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66335-51, 2d.23h.21m
    easyprivacy: 26926-121, 2d.19h.19m
    plowe-0: 3676-805, 19h.45m
    spa-0: 3877-34, 19h.44m
    spa-1: 4408-168, 2d.19h.20m
    ublock-abuse: 75-0, 23h.47m
    ublock-badware: 4140-92, 2d.19h.18m
    ublock-filters: 30931-137, 2d.19h.17m
    ublock-privacy: 212-2, 23h.46m
    ublock-quick-fixes: 190-0, 19h.42m
    ublock-unbreak: 1773-41, 2d.19h.16m
    urlhaus-1: 9661-0, 19h.43m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8351 ms (selfie)
  maxAssetCacheWait: 1097 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Provide the original page from where you were redirected to that crap
