### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by Marty2438** [uBlockOrigin/uAssets#13074]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Describe the issue

ads is showing up blocking music and forcing me to reload the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 88602
  cosmetic: 50174
  scriptlet: 16779
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 12996-0, 1h.58m
    easylist: 66297-55, 1d.13h.30m
    easyprivacy: 26926-123, 1d.13h.28m
    plowe-0: 3678-806, 9d.26m
    ublock-abuse: 74-0, 9d.27m
    ublock-badware: 4140-92, 1d.13h.27m
    ublock-filters: 30953-95, 1d.13h.29m
    ublock-privacy: 212-3, 9d.28m
    ublock-quick-fixes: 205-0, 1h.59m
    ublock-unbreak: 1783-40, 1d.13h.26m
    urlhaus-1: 9661-0, 1d.17h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 427 ms (selfie)
  maxAssetCacheWait: 220 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    akamaized.net: 2
    doubleclick.net: 6
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
> ads is showing up blocking music and forcing me to reload the page


Is it a consistent behavior ? I guess you are meaning audio ads, right ?

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/12483
