### ISSUE TITLE
reddit.com: ads

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#13076]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/`

### Category

ads

### Describe the issue

As you can see in the screenshots the rule `##._3RPJ8hHnfFohktLZca18J6` makes also some blocks disappear which should not be blocked. 

**Note** `Fanboy's Enhanced Tracking List` has this rule *(so no problem at uBlock side)* 
and maybe we have to make an unbreak rule for this, which is `reddit.com#@#._3RPJ8hHnfFohktLZca18J6`

### Screenshot(s)

<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/81161435/166661022-d3d0e971-905d-436e-a36e-9fa3a43bde26.png)

</details>

<details>
<summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/81161435/166661101-fac0e356-fa3e-42a4-bf68-c2866211cb24.png)

</details>

<details>
<summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/81161435/166661198-aa7c856d-6c39-464f-aaee-f80b9d0e5324.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 101
filterset (summary): 
  network: 69103
  cosmetic: 44860
  scriptlet: 16823
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2996-10, 1h.21m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 2069-0, 1h.21m
  default: 
    user-filters: 214-0, never
    ublock-filters: 30946-90, 1h.16m
    ublock-unbreak: 1777-10, 1h.15m
    easylist: 66373-139, 1h.14m
    easyprivacy: 26935-194, 1h.13m
filterset (user): [array of 162 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 19417 ms
  maxAssetCacheWait: 1099 ms
popupPanel: 
  blocked: 77
  blockedDetails: 
    reddit.com: 12
    doubleclick.net: 2
    gfycat.com: 1
    google-analytics.com: 1
    google.com: 2
    redditmedia.com: 1
    redditstatic.com: 51
    streamable.com: 1
    youtube.com: 6
```
</details>

**Comment by JohnyP36** [comment]
ryanbr is very slow to respond to issues (I still have an issue from April 8, 2021 which he did not respond on).

**Comment by mapx-** [comment]
@ryanbr
