### ISSUE TITLE
anime.dutchycorp.space: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#13079]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://anime.dutchycorp.space/adblock.php`

### Category

detection

### Describe the issue

This site detect uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Cuplikan web_4-5-2022_19734_anime dutchycorp space](https://user-images.githubusercontent.com/45124799/166678082-f18b3682-88d8-4942-ae05-188743310ff7.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 101
filterset (summary): 
  network: 86363
  cosmetic: 47459
  scriptlet: 16760
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    IDN-0: 8993-0, 1d.18h.40m
    easylist: 66297-54, 1d.18h.39m
    easyprivacy: 26926-123, 1d.18h.38m
    plowe-0: 3679-805, 6d.4h.12m
    ublock-abuse: 75-0, 6d.4h.12m
    ublock-badware: 4140-92, 1d.18h.37m
    ublock-filters: 30953-122, 1d.18h.36m
    ublock-privacy: 213-3, 6d.4h.12m
    ublock-unbreak: 1783-41, 1d.18h.35m
    urlhaus-1: 8902-0, 16h.8m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 560 ms (selfie)
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adcryp.to: 1
    cointraffic.io: 1
    coinverti.com: 2
    doubleclick.net: 2
    exchange-traffic.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    inpagepush.com: 1
    mxuiso.com: 1
    stat-rock.com: 1
    vlitag.com: 2
    youtube.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original page that you accessed or describe the steps to reproduce in more details?
