### ISSUE TITLE
aeromexico.com: breakage

### ISSUE THREAD

**Issue by ivanovishado** [uBlockOrigin/uAssets#13070]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aeromexico.com/es-mx`

### Category

breakage

### Describe the issue

The site doesn't load any useful functionality. It's stuck on a loader animation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-05-03 at 10 15 35 p m](https://user-images.githubusercontent.com/17692634/166618799-b9f6c380-2600-4ce9-bcbb-89b6716351bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82871
  cosmetic: 42856
  scriptlet: 16730
  html: 647
listset (total-discarded, last updated): 
  removed: 
    spa-0: null
    spa-1: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 31544-29, 1d.21m
    ublock-badware: 4144-3, 1d.20m
    ublock-privacy: 218-0, 7d.59m
    ublock-abuse: 74-0, 7d.1h
    ublock-unbreak: 1787-0, 1d.24m
    easylist: 66322-589, 1d.23m
    easyprivacy: 26931-578, 1d.22m
    urlhaus-1: 9572-0, 1d.19m
    plowe-0: 3679-3, 7d.1h.1m
    ublock-quick-fixes: 193-0, 1d.18m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2520 ms (selfie)
  maxAssetCacheWait: 1798 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    aeromexico.com: 2
    bluekai.com: 1
    googletagmanager.com: 2
    newrelic.com: 1
    online-metrix.net: 4
    optimizely.com: 1
    uplift-platform.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`@@||googletagmanager.com/gtm.js?id=GTM-$script,domain=aeromexico.com`

@ryanbr @monzta
