### ISSUE TITLE
discretemath.org: breakage

### ISSUE THREAD

**Issue by James-Musselman** [uBlockOrigin/uAssets#13071]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://discretemath.org/ads/s-graphs-introduction.html`

### Category

breakage

### Describe the issue

All Diagrams/Pictures in the website/texbook disappear with uBlock Enabled. The only thing that brings them back is if ublock is disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without uBlock 
![image](https://user-images.githubusercontent.com/74808546/166619183-dc129002-9a48-410a-9ba0-0d254cc0c8ea.png)
With uBlock
![image](https://user-images.githubusercontent.com/74808546/166619265-4b345665-9611-48e3-a0e9-422bd2cc4c9d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 98812
  cosmetic: 42854
  scriptlet: 16743
  html: 647
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31528-29, 2d.8h.6m
    ublock-badware: 4144-3, 2d.8h.5m
    ublock-privacy: 217-0, 2d.8h.4m
    ublock-abuse: 75-0, 2d.8h.3m
    ublock-unbreak: 1792-0, 2d.8h.2m
    ublock-quick-fixes: 205-0, 45m
    easylist: 66297-586, 2d.8h
    adguard-spyware-url: 586-4, 2d.8h.10m
    easyprivacy: 26926-577, 2d.7h.59m
    urlhaus-1: 8824-0, 44m
    curben-phishing: 14378-1, 46m
    plowe-0: 3676-3, 2d.7h.57m
    LegitimateURLShortener: 1854-85, 47m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 500 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    discretemath.org: 32
    google-analytics.com: 1
    statcounter.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
@okiehsch I think there are other links with `ads` that are blocked incorrectly too:

For `https://discretemath.org/`:

```
https://discretemath.org/ADS2_style.css
```

For `https://discretemath.org/ads/index-ads.html`:

```
http://discretemath.org/images/ads_v3_cover.jpg
```

As `ADS` here is meant to be `Applied Discrete Structures` so there might be more things that can be broken. I think `@@||discretemath.org/*$1p` is better.

**Comment by James-Musselman** [comment]
There are also different sites that it is also hosted on!
This one is up and down but it also has the same problem https://faculty.uml.edu/klevasseur/ads/index-ads.html

**Comment by stephenhawk8054** [comment]
I see. Maybe `@@||discretemath.org^`?

**Comment by James-Musselman** [comment]
Pardon my ignorance but would that also work for the other website too?

**Comment by stephenhawk8054** [comment]
> Pardon my ignorance but would that also work for the other website too?

Yes, `@@||discretemath.org^` allows any resources from `discretemath.org` to be used by other websites.
