### ISSUE TITLE
go.techgeek.digital: breakage

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#13088]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://go.techgeek.digital/CDEx`

### Category

breakage

### Describe the issue

Recaptcha on this site error when uBlock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.2
Chromium: 101
filterset (summary): 
  network: 86342
  cosmetic: 47503
  scriptlet: 16762
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    IDN-0: 8998-0, 22h.47m
    easylist: 66387-54, 22h.47m
    easyprivacy: 26936-123, 22h.47m
    plowe-0: 3679-805, 22h.47m
    ublock-abuse: 75-0, 22h.47m
    ublock-badware: 4140-92, 22h.47m
    ublock-filters: 30963-127, 22h.47m
    ublock-privacy: 213-2, 22h.47m
    ublock-unbreak: 1775-41, 22h.47m
    urlhaus-1: 8824-0, 22h.47m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 502 ms (selfie)
  maxAssetCacheWait: 331 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    aniview.com: 1
    avplayer.com: 1
    d2ers4gi7coxau.cloudfront.net: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    s3.us-east-1.amazonaws.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by yohanes4dip** [comment]
Why not with me?

Pada tanggal Kam, 5 Mei 2022 18.23, JobcenterTycoon <
***@***.***> menulis:

**Comment by mapx-** [comment]
@yohanes4dip I updated a filter (for popups), update your lists in 5-10 min and test again. 
Disable all other extensions while testing.

**Comment by yohanes4dip** [comment]
Okay

Pada tanggal Kam, 5 Mei 2022 pukul 18.53 mapx- ***@***.***>
menulis:
