### ISSUE TITLE
pablocp.github.io: privacy

### ISSUE THREAD

**Issue by ChessMaster2012** [uBlockOrigin/uAssets#13081]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pablocp.github.io/HexGL/`

### Category

unblocked game

### Describe the issue

this is a blocked game but it is unblocked on this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 94
filterset (summary): 
  network: 81671
  cosmetic: 42855
  scriptlet: 16776
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66297-51, 1d.21h.11m
    easyprivacy: 26926-121, 1d.21h.8m
    plowe-0: 3676-805, 1d.21h.14m
    ublock-abuse: 75-0, 1d.21h.15m
    ublock-badware: 4140-92, 1d.21h.12m
    ublock-filters: 30935-87, 1d.21h.10m
    ublock-privacy: 212-2, 1d.21h.16m
    ublock-quick-fixes: 205-0, 2h.15m
    ublock-unbreak: 1783-40, 1d.21h.9m
    urlhaus-1: 8407-0, 2h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5752 ms (selfie)
  maxAssetCacheWait: 2368 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    google.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
What is wrong here?
