### ISSUE TITLE
btweb.trontv.com: ads

### ISSUE THREAD

**Issue by filipkamenski** [uBlockOrigin/uAssets#13087]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://btweb.trontv.com/gui/index.html?v=1.2.8.4523&localauth=localapief0c3f97208335a3:`

### Category

ads

### Describe the issue

Shows upgrade to premium and other ads. I tried using the element zapper to get rid of them, but they come back after web page refresh.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 93449
  cosmetic: 162058
  scriptlet: 20581
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52580-170, 2d.1h.54m
    adguard-social: 16950-852, 2d.1h.53m
    fanboy-annoyance: 70664-4042, 8d.15h.40m
    fanboy-thirdparty_social: 68-21, 8d.15h.39m
  default: 
    user-filters: 0-0, never
    easylist: 66322-91, 2d.1h.52m
    easyprivacy: 26931-216, 2d.1h.51m
    plowe-0: 3676-806, 2d.1h.55m
    ublock-abuse: 75-0, 2d.1h.57m
    ublock-badware: 4140-92, 2d.1h.50m
    ublock-filters: 30946-440, 2d.1h.49m
    ublock-privacy: 213-11, 6d.18h.42m
    ublock-quick-fixes: 204-3, 32m
    ublock-unbreak: 1773-47, 2d.1h.48m
    urlhaus-1: 8493-0, 31m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 567 ms (selfie)
  maxAssetCacheWait: 1467 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    127.0.0.1: 1
    google-analytics.com: 7
    privacy-center.org: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details? It shows this when I access your URL.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/166904935-08736e34-a2df-433d-8b38-6fd91599460a.png)

</details>

**Comment by filipkamenski** [comment]
Hi. It's my bad for not explaining. Bittorrent web is a torrent application for win and mac. You have to download the app before the webpage shows up.

**Comment by stephenhawk8054** [comment]
[Element zapper](https://github.com/gorhill/uBlock/wiki/Element-zapper) is just temporary, can you try [Element picker](https://github.com/gorhill/uBlock/wiki/Element-picker) instead?

**Comment by filipkamenski** [comment]
Thank you very much! Didn't realise element zapper is only temporary. This means there wasn't a issue in the firs place. everything is working correctly now.
