### ISSUE TITLE
cafe.naver.com: ads

### ISSUE THREAD

**Issue by ademaineee** [uBlockOrigin/uAssets#13084]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cafe.naver.com/yoondyedu/1209981`

### Category

ads

### Describe the issue

this shows leftover ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82312
  cosmetic: 48654
  scriptlet: 16446
  html: 0
listset (total-discarded, last updated): 
  added: 
    KOR-1: 8171-0, 20d.10h.35m
  default: 
    user-filters: 3-0, never
    easylist: 65818-58, 20d.10h.34m
    easyprivacy: 26783-125, 20d.10h.33m
    plowe-0: 3687-810, 26d.13h.5m
    ublock-abuse: 72-0, 31d.22h.6m
    ublock-badware: 4057-92, 20d.10h.32m
    ublock-filters: 30476-99, 20d.10h.31m
    ublock-privacy: 206-2, 31d.22h.5m
    ublock-quick-fixes: 151-0, 20d.10h.29m
    ublock-unbreak: 1752-42, 20d.10h.30m
    urlhaus-1: 7619-0, 20d.10h.28m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    naver.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by piquark6046** [comment]
@ademaineee
Did you mean this advertisement?

<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/98787049/166925608-100f91d0-1bc1-4021-b03b-646b40a55111.png)

</details>

**Comment by ademaineee** [comment]
yea, i meant this ad

i haven't used the new filter tho, i will test it tomorrow

best regards

**Comment by piquark6046** [comment]
@ademaineee 
Okay. I will push commits to [List-KR Extension](https://github.com/List-KR/List-KR#list-kr-script-and-list-kr-extension).

**Comment by ademaineee** [comment]
Thank you so much!

Sincerely
