### ISSUE TITLE
DuckDuckGo Search Results Page Ads

### ISSUE THREAD

**Issue by q1800** [uBlockOrigin/uAssets#13080]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://duckduckgo.com/?q=total+defense+anti-virus&ia=web`
`https://duckduckgo.com/?q=cat+food&ia=web`
`https://duckduckgo.com/?q=CDs&ia=web`

### Describe the issue

Starting today, I noticed that doing some random searches on DuckDuckGo that there are ads being displayed on the right hand side on the search results page. I have included a few example search results links and their associated screenshots.

### Screenshot(s)

![DDG-Ads-Anti-Virus](https://user-images.githubusercontent.com/95879668/166719640-d539c39d-1f0b-4864-88bb-6ec82a5854e7.png)

![DDG-Ads-Cat-Food](https://user-images.githubusercontent.com/95879668/166719664-745398f0-356c-4f0e-b013-8a951eaf3c7d.png)

![DDG-Ads-CDs](https://user-images.githubusercontent.com/95879668/166719687-a0152f95-ebc2-475c-9271-fd4f4212bf25.png)

### uBlock Origin version

uBO 1.42.5b3

### Browser name and version

Firefox Nightly 102

### Settings

N/A

**Comment by JobcenterTycoon** [comment]
@q1800 got fixed in EasyList

**Comment by Procyon-b** [comment]
@Khrin the filter is too broad. It will also hide the "about" info.
Use this instead:
```
duckduckgo.com##.js-sidebar-ads > .nrn-react-div
```

**Comment by Procyon-b** [comment]
@JobcenterTycoon right.
I didn't attempt to test their filter, but by reading the commit I knew that the "about" block would be hidden too.
