### ISSUE TITLE
randpac.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1308]
### URL(s) where the issue occurs

`http://randpac.com/fisa-reform-now`

### Describe the issue

`ADD YOUR NAME` button doesn't work

### Notes

`@@center.io` fixes it. Note: clicking the button without entering info will show that the fields are required, acting as if the button works. But then after filling in the fields, clicking the button does nothing unless center.io is whitelisted.

**Comment by mapx-** [comment]
@ryanbr @Khrin
