### ISSUE TITLE
[nsfw] facebook.com: detection

### ISSUE THREAD

**Issue by FaysolNihal** [uBlockOrigin/uAssets#13086]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/watch/?ref=tab`

### Category

detection

### Describe the issue

Please stop advertising on this page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 197424
  cosmetic: 0
  scriptlet: 38573
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    plowe-0: null
  added: 
    ALB-0: 270-236, 1h.6m
    BGR-0: 1116-414, 1h.6m
    CHN-0: 28493-10245, 1h.6m
    CZE-0: 710-331, 1h.6m
    DEU-0: 5668-3521, 1h.6m
    EST-0: 450-195, 1h.6m
    FIN-0: 1701-1504, 1h.6m
    FRA-0: 27628-9129, 1h.6m
    GRC-0: 1002-547, 1h.5m
    HUN-0: 2158-1790, 1h.5m
    IDN-0: 8998-4709, 1h.5m
    IND-0: 10582-5488, 1h.5m
    IRN-0: 1340-758, 1h.5m
    ISL-0: 193-126, 1h.5m
    ISR-0: 1622-857, 1h.5m
    ITA-0: 12997-7361, 1h.5m
    JPN-1: 6823-5650, 1h.5m
    KOR-1: 8227-6309, 1h.5m
    LTU-0: 1192-617, 1h.5m
    LVA-0: 395-196, 1h.5m
    [26 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    easyprivacy: 26943-10484, 1h.4m
    ublock-abuse: 75-3, 1h.4m
    ublock-badware: 4144-638, 41m
    ublock-filters: 30969-10336, 6m
    ublock-privacy: 215-49, 1h.4m
    ublock-quick-fixes: 208-85, 1h.4m
    ublock-unbreak: 1778-311, 1h.4m
    urlhaus-1: 8493-1, 1h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  collapseBlocked: false
  hyperlinkAuditingDisabled: false
  parseAllABPHideFilters: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1083 ms (selfie)
  maxAssetCacheWait: 2646 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    facebook.com: 14
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3367
