### ISSUE TITLE
video not load(firefox)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13095]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [x] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://gomo.to/movie/tom-clancy-s-without-remorse?src=mirror4`

### Describe the issue

upon clicking play it gives error as per ss

### Screenshot(s)

![Screenshot (338)](https://user-images.githubusercontent.com/20338483/167090781-a57f2b14-7d00-4c77-b1aa-49ccf4b9c4d8.png)

### uBlock Origin version

1.42.5b3

### Browser name and version

firefox 100.0

### Settings

Default

### Notes

It seems issue doesn't occur on opera browser ,only firefox
when i badfilter EL rule as

`*$subdocument,csp=worker-src 'none',domain=alltube.pl|alltube.tv|assia1.tv|assia2.tv|centrum-dramy.pl|cmovies.ac|coinfaucet.eu|crictime.com|crictime.is|deltabit.co|doodcdn.com|estream.to|extreme-down.tv|flashx.co|flashx.to|flashx.tv|gomo.to|hdvid.fun|hdvid.tv|hitomi.la|kinox.to|lewd.ninja|nflbite.com|pirateproxy.live|plytv.me|potomy.ru|powvideo.cc|powvideo.net|putlocker.to|reactor.cc|rojadirecta.watch|sickrage.ca|streamtape.com|thehiddenbay.com|thepiratebay.org|thepiratebay10.org|torlock.com|tpb.party|uptomega.me|ustream.to|vidoza.co|vidoza.net|vidtodo.pro|wallpoper.com|wearesaudis.net|yazilir.com,badfilter`

it works on my end

it was informed to EL Maintainers

**Comment by stephenhawk8054** [comment]
@ryanbr
