### ISSUE TITLE
short.pe [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1309]
URL(s) where the issue occurs

`http://short.pe/y2ZXos`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Pop-up @mapx-

**Comment by dumbusernameidk** [comment]
csp filter prevents the second page loading.

**Comment by mapx-** [comment]
no issue for me, I get "get link" and then the final destination (google page)

**Comment by dumbusernameidk** [comment]
this is what i get

`https://gyazo.com/1490d8b82be34117f3503051233a43bd` it's something called stackpath.

**Comment by mapx-** [comment]
still ok with us ip

**Comment by dumbusernameidk** [comment]
strange as to why i get it definitely wasn't here before.

**Comment by dumbusernameidk** [comment]
@mapx- 
`short.pe` fake push notification plus popups. New link `https://short.pe/xnmGu`

**Comment by doio** [comment]
Recaptcha checkbox disappeared

https://short.pe/xOxqCY

**Comment by dumbusernameidk** [comment]
Junk xhr request and popup on second page `short.pe##+js(acis, Math, zfgloaded)`.

this link still works `https://short.pe/xnmGu`.
