### ISSUE TITLE
[NSFW] tabooporns.com

### ISSUE THREAD

**Issue by RicoHeat** [uBlockOrigin/uAssets#13096]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tabooporns.com`

### Describe the issue

```
hqq.*##[href="https://t.me/Russia_Vs_Ukraine_War3"]
hqq.*##a[onclick="openAuc();"]
```

The hqq. filter still works on older videos in the website.. However in newer videos I had to modify to

```
! 2022-05-05 https://player.tabooporns.com 
player.tabooporns.*##[href="https://t.me/Russia_Vs_Ukraine_War3"]
player.tabooporns.*##a[onclick="openAuc();"]
```

Additionally the new widget added to the video player opens

```
||auction.bingo^$popup
```

### uBlock Origin version

1.42.4

### Browser name and version

Fennec_fdroid

### Settings

None

**Comment by mapx-** [comment]
it seems to be broken

**Comment by mapx-** [comment]
The site seems to be broken, at least that video
