### ISSUE TITLE
Wrong typo? Yellow background in filters

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#13099]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

inside lists

### Category

??

### Describe the issue

"Yellow background... in different filtes"

Found in:
- uBlock Filter List
- Unbreak List

### Screenshot(s)

![Captura88](https://user-images.githubusercontent.com/33556647/167171369-3a220313-250d-4d1f-8954-a5516c2c9003.PNG)

![Capturaasdqw](https://user-images.githubusercontent.com/33556647/167171388-6432692b-5da1-45f9-a4be-f59507c940be.PNG)

![Capturaqwe1](https://user-images.githubusercontent.com/33556647/167171404-f70c0fc1-3562-440a-862b-5f094c908f82.PNG)

### Configuration

??

**Comment by JobcenterTycoon** [comment]
Its not, see https://www.reddit.com/r/uBlockOrigin/comments/t25jzn/regex_filters_are_underlined_with_gray_or_orange/

**Comment by PIZZA90** [comment]
oh thanks

thinking it was outdated filters or wrong typo.. and is gray sorry
