### ISSUE TITLE
magicgameworld.com: detection

### ISSUE THREAD

**Issue by XenonZe** [uBlockOrigin/uAssets#13093]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.magicgameworld.com/luigis-mansion-3-nintendo-switch-cheats/`

### Category

detection

### Describe the issue

Any page on the domain magicgameworld uses Deblocker and has an annoying blur script that persists after the block overlay is removed. 

If you use a script to block javascript as a whole, or specifically mdp-deblocker-js, the following script will also attempt to block you

            <div id='mdp-deblocker-js-disabled'>
                <div><h3>Please Enable JavaScript in your Browser to Visit this Site.</h3>
<h3></h3></div>
            </div>
            <style>
                #mdp-deblocker-js-disabled {
                    position: fixed;
                    top: 0;
                    left: 0;
                    height: 100%;
                    width: 100%;
                    z-index: 999999;
                    text-align: center;
                    background-color: #FFFFFF;
                    color: #000000;
                    font-size: 40px;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
            </style>
        

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 98
filterset (summary): 
  network: 81856
  cosmetic: 42911
  scriptlet: 16786
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    easylist: 66425-51, 13m
    easyprivacy: 26943-121, 12m
    plowe-0: 3679-805, 11m
    ublock-abuse: 75-0, 9m
    ublock-badware: 4149-92, 7m
    ublock-filters: 30959-92, 6m
    ublock-privacy: 212-2, 5m
    ublock-quick-fixes: 214-0, 4m
    ublock-unbreak: 1778-40, 3m
    urlhaus-1: 8471-0, 2m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2009 ms
  maxAssetCacheWait: 339 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    magicgameworld.com: 1
    bkrtx.com: 1
    doubleclick.net: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    network-n.com: 1
```
</details>

**Comment by Procyon-b** [comment]
No detection for me.
In ublock's dashboard, in the "Filter lists" tab, disable "My filters", click "Apply changes". Reload the website and test again.

**Comment by stephenhawk8054** [comment]
I can't reproduce the block overlay. Which browser are you using? Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.
