### ISSUE TITLE
facebook.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#13091]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/privacy/consent/user_cookie_choice/?source=pft_user_cookie_choice`

### Category

nuisance

### Describe the issue

Full screen cookie warning when signing in to facebook.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 186431
  cosmetic: 218554
  scriptlet: 35788
  html: 654
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 881-6, 8h.39m
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1957-14, 8h.46m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37701-1269, 8h.43m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-0, 8h.47m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 11-0, 2d.12h.53m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-1964, 2d.12h.54m
    https://www.i-dont-care-about-cookies.eu/abp/: 24770-4, 8h.44m
    adguard-generic: 64007-4344, 3d.10h.25m
    adguard-mobile: 7687-29, 3d.10h.20m
    adguard-spyware: 25743-732, 3d.10h.18m
    adguard-annoyance: 52521-4662, 3d.10h.26m
    adguard-social: 16978-59, 3d.10h.17m
    fanboy-thirdparty_social: 68-3, 8h.49m
    fanboy-annoyance: 70709-55827, 6d.13h.58m
    fanboy-cookiemonster: 31863-8917, 8h.48m
    fanboy-social: 23364-1107, 3d.10h.16m
    ublock-annoyances: 4373-9, 3d.10h.15m
    dpollock-0: 10364-209, 3d.10h.27m
    adguard-spyware-url: 586-4, 3d.10h.14m
    block-lan: 43-0, 8d.4h.22m
    [2 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 31539-67, 3d.10h.23m
    ublock-badware: 4144-3, 3d.10h.22m
    ublock-privacy: 217-0, 2d.12h.58m
    ublock-abuse: 75-4, 2d.12h.57m
    ublock-unbreak: 1792-1, 3d.10h.21m
    easylist: 66297-3947, 3d.10h.19m
    easyprivacy: 26926-10817, 3d.10h.24m
    urlhaus-1: 8493-0, 8h.42m
    plowe-0: 3676-687, 2d.12h.55m
    GRC-0: 1002-4, 8h.45m
    ublock-quick-fixes: 206-0, 8h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11588 ms (selfie)
  maxAssetCacheWait: 4408 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    facebook.com: 3
```
</details>

**Comment by okiehsch** [comment]
As per our readme we don't address GDPR issues.
