### ISSUE TITLE
Sourceforge ads

### ISSUE THREAD

**Issue by quilloss** [uBlockOrigin/uAssets#131]
### URL(s) where the issue occurs

https://sourceforge.net/projects/hugin/

### Describe the issue

Sourceforge loads ads using WebRTC.

### Versions

Firefox 50
uBlock Origin 1.9.5rc0

### Notes

The site loads a javascript file using WebRTC and inserts it as a blob url. This script will then insert ads using background data url.

Filter:
`sourceforge.net##script:inject(nowebrtc.js)`

**Comment by gorhill** [comment]
Where is the ad on that page?

**Comment by quilloss** [comment]
On the side bar above Recommended Projects. It takes a while for it to appear.

**Comment by IDKwhattoputhere** [comment]
![](https://cloud.githubusercontent.com/assets/16030872/18368673/75928bce-7621-11e6-83c0-b4e65eeb2d2f.png)

**Comment by gorhill** [comment]
I don't know why, I can't get this ad on my side. Is this a Windows thing?

**Comment by gorhill** [comment]
I could reproduce immediately when using a UA spoofing the OS to Windows.

**Comment by Tmp341** [comment]
I don't see that, even i'm on windows.

**Comment by IDKwhattoputhere** [comment]
@Tmp341 I doub that's the reason. Wireshark shows me no connections to ad servers. Just Sourceforge's own servers, some JS library hoster, STUN servers but nothing that looks like straight ad servers.
