### ISSUE TITLE
okdo.com: breakage

### ISSUE THREAD

**Issue by tamarindmonkey** [uBlockOrigin/uAssets#13102]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.okdo.com/`

### Category

breakage

### Describe the issue

All pages will retain a grayed out overlay because the "privacy preferences" bottom toolbar is prevented from being displayed unless uBlock is disabled. After the first visit, once the user accepts all cookies from the site or manually sets their privacy preferences from the bottom toolbar (with uBlock Origin disabled) it can be re-enabled and the site will function fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 126486
  cosmetic: 199995
  scriptlet: 35699
  html: 655
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63833-4837, 22h.55m
    adguard-mobile: 7705-155, 22h.56m
    adguard-spyware: 25930-928, 22h.46m
    adguard-annoyance: 52731-4423, 22h.53m
    adguard-social: 17004-1090, 22h.52m
    fanboy-thirdparty_social: 69-0, 5d.8h.3m
    fanboy-annoyance: 70783-55397, 5d.8h.2m
    fanboy-cookiemonster: 31840-100, 5d.8h.1m
    fanboy-social: 23367-28, 22h.54m
    ublock-annoyances: 4396-4, 22h.57m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31573-58, 22h.51m
    ublock-badware: 4153-3, 22h.50m
    ublock-privacy: 217-0, 10d.9h.40m
    ublock-abuse: 74-0, 10d.9h.41m
    ublock-unbreak: 1789-0, 22h.49m
    easylist: 66425-771, 22h.48m
    easyprivacy: 26943-10356, 22h.45m
    urlhaus-1: 8471-0, 22h.43m
    plowe-0: 3679-3, 10d.5h.26m
    ublock-quick-fixes: 206-0, 22h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 21 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2832 ms (selfie)
  maxAssetCacheWait: 1056 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    okdo.com: 4
    digicert.com: 1
    googleoptimize.com: 1
    meet3monk.com: 2
    newrelic.com: 1
    parsely.com: 2
    trustpilot.com: 3
    wp.com: 4
```
</details>

**Comment by mapx-** [comment]
add

```
okdo.com#@#div[data-cookie-name]
okdo.com#@#.c-notification-bar
```

@ryanbr (first filter)
@AdamWr (second filter)
