### ISSUE TITLE
vods.tv: detection

### ISSUE THREAD

**Issue by Janfel** [uBlockOrigin/uAssets#13104]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vods.tv/`

### Category

detection

### Describe the issue

A popup reading "AdBlock Detected" appears that disables scrolling on the website even when removed using "Inspect Element".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 82014
  cosmetic: 42918
  scriptlet: 16742
  html: 647
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 31548-29, 4m
    ublock-badware: 4158-3, 4m
    ublock-privacy: 220-0, 4m
    ublock-abuse: 75-0, 4m
    ublock-unbreak: 1791-0, 4m
    easylist: 66484-590, 4m
    easyprivacy: 26943-577, 4m
    plowe-0: 3676-3, 4m
    urlhaus-1: 8573-0, 4m
    ublock-quick-fixes: 213-0, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1080 ms (selfie)
  maxAssetCacheWait: 627 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by MasterKia** [comment]
Add `vods.tv##+js(no-fetch-if, doubleclick.net)` to _My Filters_ and check if it works for you.

**Comment by Janfel** [comment]
That seems to work. Thank you.
