### ISSUE TITLE
exey.io: breakage

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#13106]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://exey.io/blog/category/communication/`

### Category

breakage

### Describe the issue

recaptcha in this website error while ublock active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 86052
  cosmetic: 47513
  scriptlet: 16770
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    IDN-0: 8998-0, 1d.20h.14m
    easylist: 66414-54, 1d.20h.14m
    easyprivacy: 26943-123, 1d.20h.14m
    plowe-0: 3679-805, 1d.20h.14m
    ublock-abuse: 75-0, 1d.20h.14m
    ublock-badware: 4144-92, 1d.20h.14m
    ublock-filters: 30974-126, 1d.20h.14m
    ublock-privacy: 215-2, 1d.20h.14m
    ublock-unbreak: 1778-41, 1d.20h.14m
    urlhaus-1: 8497-0, 19h.58m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 526 ms (selfie)
  maxAssetCacheWait: 328 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    doubleclick.net: 1
    exe.io: 1
    googletagmanager.com: 1
    taghaugh.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original URL which redirected to that link?

**Comment by yohanes4dip** [comment]
https://exey.io/UFfBHm

Pada tanggal Sab, 7 Mei 2022 pukul 15.32 stephenhawk8054 <
***@***.***> menulis:
