### ISSUE TITLE
time.mk: ads

### ISSUE THREAD

**Issue by jakche** [uBlockOrigin/uAssets#13103]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://time.mk/`

### Category

ads

### Describe the issue

There are always ads on the website, using zapper or picker just removes the ad for a couple of seconds, after that the ad is right back at it's place. Nothing I do blocks the ad permanently.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81776
  cosmetic: 42856
  scriptlet: 16731
  html: 646
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31521-31, 4d.11m
    ublock-badware: 4144-3, 4d.10m
    ublock-privacy: 217-0, 4d.9m
    ublock-abuse: 75-0, 4d.8m
    ublock-unbreak: 1787-0, 4d.7m
    ublock-quick-fixes: 213-0, 20m
    easylist: 66322-588, 3d.23h.23m
    easyprivacy: 26931-577, 3d.23h.22m
    urlhaus-1: 8483-0, 19m
    plowe-0: 3676-3, 3d.23h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 607 ms (selfie)
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`time.mk##.advert_pos`

@ryanbr

**Comment by jakche** [comment]
Thanks for the quick fix, I've also searched other Maceodnian websites on some of them uBlock Origin works.
I have found another website which uB doesn't work. I will post the link here in the comments since the fix is easy as I can guess.
Website which has the same problem as stated above: https://motika.mk/

**Comment by mapx-** [comment]
add

`||motika.mk/reklami`

@ryanbr

**Comment by ryanbr** [comment]
Non english?

**Comment by stephenhawk8054** [comment]
> Non english?

Yeah, Macedonian. Do we have any decent Macedonian filter list?

**Comment by jakche** [comment]
I am just find more and more, I think I'll start a new thread with Macedonian websites which aren't in the filter list. So they can be blocked in one go.

**Comment by DandelionSprout** [comment]
@stephenhawk8054 https://raw.githubusercontent.com/RandomAdversary/Macedonian-adBlock-Filters/master/Filters is the closest I know to a decent Macedonian list.
