### ISSUE TITLE
console.statsig.com: breakage

### ISSUE THREAD

**Issue by maria-statsig** [uBlockOrigin/uAssets#13101]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://console.statsig.com/4jUE04eQSypmDL7dvE1F3Y/metrics/metrics_catalog`

### Category

breakage

### Describe the issue

Hello!

I work for Statsig and users are reporting that uBlock is breaking our metrics page. I am also able to repo this issue. This is only occurring on this specific link https://console.statsig.com/4jUE04eQSypmDL7dvE1F3Y/metrics/metrics_catalog, the rest of our site does not seem to be impacted. The page loads as an entirely blank screen when ublock is enabled and works as expected when ublock is disabled. 

Thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-05-06 at 11 25 42 AM](https://user-images.githubusercontent.com/99914387/167196656-16117b8c-1829-4bd6-94e0-60f6b91bed4c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81861
  cosmetic: 42909
  scriptlet: 16791
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66425-51, 18h.49m
    easyprivacy: 26943-121, 18h.48m
    plowe-0: 3679-805, 18h.47m
    ublock-abuse: 75-0, 18h.46m
    ublock-badware: 4149-92, 18h.44m
    ublock-filters: 30968-91, 23h.27m
    ublock-privacy: 215-2, 23h.26m
    ublock-quick-fixes: 216-0, 23h.25m
    ublock-unbreak: 1778-40, 23h.24m
    urlhaus-1: 8471-0, 23h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1076 ms
  maxAssetCacheWait: 206 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    statsig.com: 1
```
</details>

**Comment by okiehsch** [comment]
We would need an account to investigate further.
You could tell your users to simply whitelist your site `statsig.com`.
We won't add a fix for an internal page to our lists.

**Comment by mapx-** [comment]
EP breakage @ryanbr

**Comment by ryanbr** [comment]
I don't have a login to check.

**Comment by mapx-** [comment]
@ryanbr credentials on slack
