### ISSUE TITLE
titantv.com: nuisance

### ISSUE THREAD

**Issue by Ocelotsden** [uBlockOrigin/uAssets#13100]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.titantv.com/default.aspx`

### Category

nuisance

### Describe the issue

uBlock stopped blocking video that plays and then pops to a video window when scrolling the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/42783561/167192242-3182f0bf-d933-431c-90c7-7c6baa309e55.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 86315
  cosmetic: 89537
  scriptlet: 22006
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52732-171, 16h.10m
    ublock-annoyances: 4388-146, 16h.9m
  default: 
    user-filters: 4-0, never
    easylist: 66413-90, 2d.21m
    easyprivacy: 26938-217, 2d.20m
    plowe-0: 3679-806, 10d.22h
    ublock-abuse: 74-0, 12d.17h.42m
    ublock-badware: 4140-92, 2d.19m
    ublock-filters: 30963-426, 2d.18m
    ublock-privacy: 212-3, 12d.17h.41m
    ublock-quick-fixes: 210-3, 48m
    ublock-unbreak: 1777-44, 2d.17m
    urlhaus-1: 8483-0, 49m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 262 ms (selfie)
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 36
  no-large-media: true
  no-popups: true
  blockedDetails: 
    titantv.com: 10
    aaxads.com: 1
    amazon-adsystem.com: 1
    connatix.com: 2
    d29xw9s9x32j3w.cloudfront.net: 2
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    indexww.com: 1
    infolinks.com: 1
    pbxai.com: 1
    pinterest.com: 1
    powerad.ai: 1
    resonate.com: 1
    rubiconproject.com: 1
    sendtonews.com: 8
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||boomselljamwelunch.com/player$script,domain=titantv.com
titantv.com##[data-stn-player]:upward(tr)
```

**Comment by Ocelotsden** [comment]
Thanks very much!
