### ISSUE TITLE
hdhub4u.tel: ads

### ISSUE THREAD

**Issue by Waqartariq100** [uBlockOrigin/uAssets#13105]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdhub4u.tel/`

### Category

ads

### Describe the issue

Pop ups on this page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 82374
  cosmetic: 24263
  scriptlet: 16472
  html: 634
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31155-319, never
    ublock-badware: 3993-3, never
    ublock-privacy: 210-1, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1759-0, never
    ublock-quick-fixes: 139-4, never
    adguard-mobile: 7686-325, never
    easylist: 65018-24221, never
    easyprivacy: 26734-129, never
    urlhaus-1: 8896-0, never
    plowe-0: 3690-450, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8938 ms
  maxAssetCacheWait: 61 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    hdhub4u.tel: 2
    addresseepaper.com: 1
    clenchedyouthmatching.com: 1
    googletagmanager.com: 1
    unseenreport.com: 1
    uprightmidsummer.com: 1
```
</details>

**Comment by mapx-** [comment]
force update all the filter lists and test again

**Comment by Waqartariq100** [comment]
I tried to force update but it's not working.

**Comment by Waqartariq100** [comment]
> force update all the filter lists and test again

Tried but not working. Pop ups coming back

**Comment by MasterKia** [comment]
> Pop ups on this page

Could you share a screenshot?

What is the URL of the pop up?

**Comment by stephenhawk8054** [comment]
I can't reproduce any popups. Can you copy the logger information with these steps:

1. Open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger)
2. In logger's search box, select `Blocked` and `Allowed`
3. Reload the page and do the steps to trigger the issue
4. Click on this button at the top right:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/164956446-aaef7120-ed8f-4376-b154-68d5a569fc60.png)

</details>

5. Choose `Table` at the top left -> `Markdown` at top middle -> `Copy to clipboard` at top right and paste here

Video: [https://www.youtube.com/watch?v=IHIz5rFnieg](https://www.youtube.com/watch?v=IHIz5rFnieg)

**Comment by mapx-** [comment]
@Waqartariq100 do you see in the logger this filter ?

`hdhub4u.*##+js(abort-on-property-read, mm)`

**Comment by ghajini** [comment]
Did this help you

`hdhub4u.*##^script:has-text(appendFingerprint)`

**Comment by Waqartariq100** [comment]
![Screenshot_2022-05-07-10-01-58-736_org mozilla firefox](https://user-images.githubusercontent.com/105098122/167272207-68721222-4193-4430-bd97-e6de6880f3d1.jpg)

**Comment by stephenhawk8054** [comment]
Can you check the logger as we suggested above?
