### ISSUE TITLE
9anime.id: detection

### ISSUE THREAD

**Issue by S00pertaco** [uBlockOrigin/uAssets#13113]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/dororo.y7nx/ep-1`

### Category

detection

### Describe the issue

detects U block and the site works when i turn U block off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 51265
  cosmetic: 38554
  scriptlet: 16065
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 62502-6, 388d.22h.46m
    easyprivacy: 22694-35, 388d.15h.22m
    plowe-0: 3568-251, 396d.13h.35m
    ublock-abuse: 73-0, 388d.22h.44m
    ublock-badware: 1455-21, 388d.22h.42m
    ublock-filters: 28299-69, 388d.22h.31m
    ublock-privacy: 120-0, 388d.22h.29m
    ublock-unbreak: 1529-8, 388d.22h.27m
    urlhaus-1: 12012-0, 385d.11h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1654 ms
  maxAssetCacheWait: 835 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
`ublock-filters: 28299-69, 388d.22h.31m`

All your filter lists are outdated 
Update all lists
