### ISSUE TITLE
blogs.sapib.ca

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#1311]
### URL(s) where the issue occurs

`https://blogs.sapib.ca/apps/mkvcleaver/mkvcleaver-downloads/`

### Describe the issue

Download buttons not displayed because of an anti-adblocker.

### Versions

- Browser/version: Firefox 57
- uBlock Origin version:  1.14.24

### Notes

This URL has been reported to EasyList but they never fixed it:

https://github.com/easylist/easylist/issues/322
https://forums.lanik.us/viewtopic.php?f=62&t=37114

**Comment by TheEnhas** [comment]
`blogs.sapib.ca##script:inject(abort-current-inline-script.js, Abd_Detector)`

**Comment by adranger** [comment]
>I don't know why you posted this here
Because they won't add it to EasyList, and this problem affects all uBlock Origin users.

**Comment by TheEnhas** [comment]
Yeah, sometimes they outright ignore some fixes which is pretty odd.

**Comment by adranger** [comment]
@mapx-  it now uses another anti-adblock method. Please take a look at it.
