### ISSUE TITLE
sunriseupctv.ch: nuisance

### ISSUE THREAD

**Issue by unitrix0** [uBlockOrigin/uAssets#13118]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sunriseupctv.ch/de/settings/accountandprofiles/login`

### Category

nuisance

### Describe the issue

The login form on this page seems to prevent my password manager (Bitwarden) from filling in, and even recognize the inputed values.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 84001
  cosmetic: 46444
  scriptlet: 16740
  html: 648
listset (total-discarded, last updated): 
  default: 
    user-filters: 26-0, never
    ublock-filters: 31550-40, 7h.19m
    ublock-badware: 4158-3, 7h.18m
    ublock-privacy: 217-0, 6d.11h.51m
    ublock-abuse: 75-0, 8d.5h.41m
    ublock-unbreak: 1789-0, 2d.10h.4m
    easylist: 66414-597, 2d.10h.6m
    easyprivacy: 26943-588, 2d.10h.5m
    urlhaus-1: 8483-0, 1d.44m
    plowe-0: 3679-3, 2d.23h.48m
    DEU-0: 5679-2, 1d.46m
    ublock-quick-fixes: 211-0, 1d.45m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 597 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    go-mpulse.net: 2
```
</details>

**Comment by mapx-** [comment]
You should report the issue to Bitwarden

**Comment by unitrix0** [comment]
What shall they do?! it's because the page prevents it in HTML. They can't do anything about it.

**Comment by mapx-** [comment]
They can do anything uBO does like any other extension.
We cannot investigate (no account) and - more - we could break some security measure for that site
