### ISSUE TITLE
emptycharacter.com: ads

### ISSUE THREAD

**Issue by costicost** [uBlockOrigin/uAssets#13114]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://emptycharacter.com/`

### Category

ads

### Describe the issue

There are some ads on the page that even when trying to remove with element picker mode dont go away.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/93033739/167262607-b9b8a672-4437-42c9-8c78-2ef9365393c2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81625
  cosmetic: 42898
  scriptlet: 16730
  html: 647
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-3, never
    ublock-filters: 31527-29, 3d.5h.15m
    ublock-badware: 4144-3, 3d.5h.14m
    ublock-privacy: 220-0, 4m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1790-0, 3d.5h.13m
    ublock-quick-fixes: 209-0, 2m
    easylist: 66386-590, 3d.5h.12m
    easyprivacy: 26936-577, 3d.5h.11m
    urlhaus-1: 8281-0, 1m
    plowe-0: 3679-3, 11d.20h.44m
filterset (user): [array of 16 redacted]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 136 ms (selfie)
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
using the element picker:

`||emptycharacter.com/w_thatbio.png$image`

or

`emptycharacter.com##[href="https://that.bio"]`

**Comment by mapx-** [comment]
@ryanbr
