### ISSUE TITLE
Startpage.com "/sp/adsense/search/async-ads.js"

### ISSUE THREAD

**Issue by rn83** [uBlockOrigin/uAssets#13111]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://eu.startpage.com/sp/search`
`https://us.startpage.com/sp/search`
`https://www.startpage.com/sp/search`

### Describe the issue

When searching with startpage.com, `async-ads.js` is always loaded.
```
https://eu.startpage.com/sp/adsense/search/async-ads.js
https://us.startpage.com/sp/adsense/search/async-ads.js
https://www.startpage.com/sp/adsense/search/async-ads.js
```
The script is obfuscated but the module declare itself as `ads`.
```sh
var sffeData_ = {
  service_host: "www.startpage.com/sp",
  hash: "8638727905704534049",
  packages: "search",
  module: "ads",
  version: "3",
  m: {
    cei: "17300953,17300954",
    ah: true,
    uatm: 500,
    ecfc2: true,
    llrm: 1000,
    llel: "Lio=",
    lldl: "bS5zZWFycy5jb20=",
    abf: {
      "_afsRsPath": true,
      "_enableLazyLoading": true,
      "_googEnableQup": true,
      "_googErrorTurnOffPersonalization": true,
      "_googTimeoutTurnOffPersonalization": true,
      "enableEnhancedTargetingRsonc": true,
      "enableNonblockingSasCookie": true
    },
    mdp: 1800000
  }
};
```
And it seems to create an iframe `https://www.startpage.com/sp/afs/ads/i/iframe.html`.

### Notes

If I block the script, there will be no iframe on the result page.
```
||startpage.com/sp/adsense/search/async-ads.js
```

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81738
  cosmetic: 42937
  scriptlet: 16750
  html: 647
listset (total-discarded, last updated): 
  removed: 
    CHN-0: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 31564-29, 27m
    ublock-badware: 4158-3, 27m
    ublock-privacy: 220-0, 27m
    ublock-abuse: 75-0, 27m
    ublock-unbreak: 1791-0, 27m
    ublock-quick-fixes: 214-0, 27m
    easylist: 66508-590, 27m
    easyprivacy: 26945-577, 27m
    urlhaus-1: 8281-0, 27m
    plowe-0: 3676-3, 27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 831 ms (selfie)
  maxAssetCacheWait: 266 ms
```
</details>

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/5b92ae109185190a94e6281abf11cf0dbbd1b97d
