### ISSUE TITLE
chicagotribune.com: ads

### ISSUE THREAD

**Issue by johnrperales** [uBlockOrigin/uAssets#13124]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chicagotribune.com/`

### Category

ads

### Describe the issue

Hello, When I open the main Chicago tribune website, I get a video that pops up and starts playing. It plays with audio muted on the lower right side of the page. I create uBlock filter with the picking tool and it goes away. However, if I refresh the page or come back to the main chicago tribune page at a later time, the video pops up again. I'm using firefox version 100. The only other extension I'm running is privacy badger. I have tried turning privacy badger on and off but that doesn't stop the pop up. 

The video appears to be sports recaps

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-05-08 064354](https://user-images.githubusercontent.com/5560161/167294647-d721ce89-cf01-40d0-bade-216de95d64ae.png)

![image](https://user-images.githubusercontent.com/5560161/167294906-f222f3a4-ad62-4159-9ee4-16b98af0a8fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81885
  cosmetic: 42878
  scriptlet: 16742
  html: 646
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-1, never
    ublock-filters: 31544-29, 4d.20h.27m
    ublock-badware: 4144-3, 4d.20h.26m
    ublock-privacy: 217-0, 10d.16h.52m
    ublock-abuse: 75-0, 10d.16h.51m
    ublock-unbreak: 1794-0, 4d.20h.25m
    easylist: 66327-590, 4d.20h.24m
    easyprivacy: 26931-578, 4d.20h.28m
    urlhaus-1: 8573-0, 1d
    plowe-0: 3679-3, 10d.16h.53m
    ublock-quick-fixes: 213-0, 23h.59m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 174 ms (selfie)
  maxAssetCacheWait: 82 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    2mdn.net: 1
    amazon-adsystem.com: 2
    chartbeat.com: 1
    confiant-integrations.global.ssl.fastly.net: 2
    d1n00d49gkbray.cloudfront.net: 1
    d29xw9s9x32j3w.cloudfront.net: 2
    doubleclick.net: 3
    go-mpulse.net: 3
    google-analytics.com: 2
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 3
    indexww.com: 1
    onesignal.com: 1
    quantserve.com: 3
    resonate.com: 1
    sendtonews.com: 13
    smoggysnakes.com: 1
    zeustechnology.com: 2
```
</details>

**Comment by mapx-** [comment]
I get no such video with / without uBO enabled

**Comment by zeref-dragneel** [comment]
Try blocking the "TODAY'S TOP VIDEOS" element
`chicagotribune.com##.nt-no-chain.pb-f-global-video-stn.pb-layout-item.pb-feature.full.pb-curated.clearfix.wrapper`

<img src="https://i.imgur.com/nMZZXYB.png" height=150>

**Comment by johnrperales** [comment]
I received the tip below from Zeref and it worked

Try blocking the "TODAY'S TOP VIDEOS" element
[chicagotribune.com##.nt-no-chain.pb-f-global-video-stn.pb-layout-item.pb-feature.full.pb-curated.clearfix.wrapper](http://chicagotribune.com/#%23.nt-no-chain.pb-f-global-video-stn.pb-layout-item.pb-feature.full.pb-curated.clearfix.wrapper)

![image](https://user-images.githubusercontent.com/5560161/167626534-916051c3-4c24-4956-acc6-85630c8f5883.png)

**Comment by johnrperales** [comment]
That worked!! I added it to my filters

--
Best Regards,

John R Perales
