### ISSUE TITLE
systemupdatesy.life: ads

### ISSUE THREAD

**Issue by naim828** [uBlockOrigin/uAssets#13120]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://systemupdatesy.life/smartsecurityd2_0419/index.html?clickid=0c1d33767d880fc053afb28d0ec2802d&utm_source=17039008&utm_medium=490965&publisher=adsterra_direct`

### Category

ads

### Describe the issue

They ignore popup

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 83684
  cosmetic: 25458
  scriptlet: 16824
  html: 657
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31659-269, 3d.11h.24m
    ublock-badware: 4081-3, 3d.11h.22m
    ublock-privacy: 218-1, 7d.21h.1m
    ublock-abuse: 75-0, 7d.21h
    ublock-unbreak: 1795-0, 3d.11h.21m
    adguard-mobile: 7699-180, 3d.11h.23m
    easylist: 66387-24636, 3d.11h.20m
    easyprivacy: 26936-593, 3d.11h.19m
    urlhaus-1: 8483-0, 1d.7h.13m
    plowe-0: 3679-3, 12d.6h.46m
    KOR-1: 1353-89, 1d.7h.15m
    ublock-quick-fixes: 211-21, 1d.7h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2088 ms (selfie)
  maxAssetCacheWait: 1425 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original URL that leads to that site?

**Comment by Yuki2718** [comment]
Blocked anyway as it's obviously a scam site. Still nice to hear where you got to this site if you can provide @naim828 .
