### ISSUE TITLE
yt5s.com: ads

### ISSUE THREAD

**Issue by Thuribulum** [uBlockOrigin/uAssets#13128]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yt5s.com/en87/youtube-to-mp3`

### Category

ads

### Describe the issue

I load the page and there is ad leftovers no images jsut bottom text + invisible ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/91972966/167303255-28ee3bcd-1f3a-4589-9722-76923bef1dac.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 81637
  cosmetic: 42903
  scriptlet: 16785
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66413-51, 3d.19h.51m
    easyprivacy: 26938-121, 3d.19h.50m
    plowe-0: 3676-805, 8d.15h.4m
    ublock-abuse: 75-0, 8d.15h.21m
    ublock-badware: 4140-92, 3d.19h.49m
    ublock-filters: 30959-91, 3d.19h.48m
    ublock-privacy: 213-3, 8d.15h.6m
    ublock-quick-fixes: 214-0, 17h.7m
    ublock-unbreak: 1775-40, 3d.19h.47m
    urlhaus-1: 8281-0, 17h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 560 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 8
  no-large-media: true
  no-popups: true
  blockedDetails: 
    addthis.com: 1
    awigglespouter.cam: 1
    bepiletussar.casa: 2
    besmeargleor.com: 1
    eehuzaih.com: 1
    googletagmanager.com: 1
    propu.sh: 1
```
</details>

**Comment by Daxy7** [comment]
new popup ads [similar domain]
```
https://yt1s.com.co/
```
put this link into the 'Search or paste YouTube link here' box and attempt to download MP3 or VIDEO
```
https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

**Comment by Daxy7** [comment]
it says adblock detected apparently. happens randomly but try this url `https://www.youtube.com/watch?v=CnQm2_cAZvo`
and download attempt audio format [uk ip?]
https://github.com/user-attachments/assets/6d430bbc-9f52-410f-a1a1-93b8149b29cf

**Comment by BlazeFTL** [comment]
fixed
