### ISSUE TITLE
1377x.to: popups

### ISSUE THREAD

**Issue by alighafoori** [uBlockOrigin/uAssets#13122]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.1377x.to/`

### Category

popups

### Describe the issue

Clicking on any link from this site will open a new page. This problem is only with Firefox browser

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 81565
  cosmetic: 42829
  scriptlet: 16727
  html: 647
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31566-29, 2d.24m
    ublock-badware: 4153-3, 2d.23m
    ublock-privacy: 217-0, 12d.9h.30m
    ublock-abuse: 74-0, 12d.9h.29m
    ublock-unbreak: 1789-0, 1d.16h.20m
    easylist: 66428-591, 1d.20h.22m
    easyprivacy: 26943-578, 1d.16h.19m
    urlhaus-1: 8281-0, 15h.52m
    plowe-0: 3679-3, 3d.16h.11m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 848 ms (selfie)
  maxAssetCacheWait: 1568 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    histats.com: 1
```
</details>

**Comment by mapx-** [comment]
`ublock-filters: 31566-29, 2d.24m`

It was fixed 19h ago, just update your filter lists

**Comment by alighafoori** [comment]
Updated and the problem was resolved
thank you
