### ISSUE TITLE
Animeflv problem with video option called FIRE 17-1-2018

### ISSUE THREAD

**Issue by rayran007** [uBlockOrigin/uAssets#1313]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://animeflv.net/

### Describe the issue

When you tried to open video in first option called FIRE, video try to open in a new tab but uBlock Origin block it. You can see in the numbers increasing in the icon. It happens in all animes

### Versions

- Browser/version: 63.0.3239.132
- uBlock Origin version: 1.14.24

### Settings

No changes in uBO's default settings

### Notes

It seems that Ublock is blocking the new tab with the video display

**Comment by mapx-** [comment]
already reported and fixed 4 days ago. 
https://github.com/uBlockOrigin/uAssets/issues/1281

Does it happen again ? Update your lists and try again.

**Comment by rayran007** [comment]
It works with filter proposed. Thanks
