### ISSUE TITLE
Whitelist a currently blocked domain

### ISSUE THREAD

**Issue by synthXR** [uBlockOrigin/uAssets#13136]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://cubics.com`

### Describe the issue

Our domain was previously used as an ad network and blacklisted in your global blacklist. Could you please remove the domain from your blacklist? Thank you!

### uBlock Origin version

Newest

### Browser name and version

Firefox

### Settings

NA

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e8b0564c1721078f573e212b294f4153b5a0a86f

**Comment by mapx-** [comment]
@pgl
