### ISSUE TITLE
titantv.com: ads

### ISSUE THREAD

**Issue by Motworraf** [uBlockOrigin/uAssets#13132]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.titantv.com/default.aspx`

### Category

ads

### Describe the issue

Can use element picker to block; however, identity of element changes with refresh of window and ad returns

Add consumes one greater enlarges row in the TV listing with movie playing (currently baseball) in right column of frame and left column of the infected row 
![Screenshot from 2022-05-08 13-14-00](https://user-images.githubusercontent.com/105167237/167307695-76f32e88-ff70-4db2-a12a-218078e55fb4.png)
blank.

### Screenshot(s)

![Screenshot from 2022-05-08 13-14-00](https://user-images.githubusercontent.com/105167237/167307855-f4a55923-55ad-4b67-af03-f33e574a560d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81742
  cosmetic: 42959
  scriptlet: 16806
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 66518-51, 6h.28m
    easyprivacy: 26946-121, 6h.27m
    plowe-0: 3679-805, 13d.2h.18m
    ublock-abuse: 75-0, 6h.30m
    ublock-badware: 4165-92, 6h.26m
    ublock-filters: 31005-90, 6h.25m
    ublock-privacy: 216-2, 6h.29m
    ublock-quick-fixes: 183-0, 6h.22m
    ublock-unbreak: 1781-40, 6h.24m
    urlhaus-1: 8293-0, 6h.23m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 645 ms (selfie)
  maxAssetCacheWait: 498 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    sendtonews.com: 4
```
</details>

**Comment by ghost** [comment]
They seem to have three ads on the top of the page:
<img width="1891" height="354" alt="Image" src="https://github.com/user-attachments/assets/049abaf1-493c-4ae2-9780-41a86db40420" />
