### ISSUE TITLE
formulapassion.it: ads

### ISSUE THREAD

**Issue by xlollomanx** [uBlockOrigin/uAssets#13138]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.formulapassion.it/opinioni/alberto-antonini/f1-sviluppi-mannari-ferrari-binotto-leclerc-miami-verstappen-redbull-barcellona-616821.html`

### Category

ads

### Describe the issue

There are many areas where are shown windows ads. Ads are no visible but their area is grey out, as it's visible in the screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![immagine](https://user-images.githubusercontent.com/6764804/167361248-765f7168-7d82-4e93-b22f-838e9310a9c6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 88075
  cosmetic: 51568
  scriptlet: 19696
  html: 656
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4410-4, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 31690-38, now
    ublock-badware: 4169-3, now
    ublock-privacy: 221-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1791-0, now
    ublock-quick-fixes: 220-0, now
    easylist: 66546-594, now
    easyprivacy: 26949-579, now
    urlhaus-1: 8632-0, now
    plowe-0: 3676-3, now
    ITA-0: 12997-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1724 ms
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    formulapassion.it: 1
    brid.tv: 1
    googletagmanager.com: 1
    outbrain.com: 2
    yobee.it: 1
```
</details>

**Comment by MasterKia** [comment]
Add `formulapassion.it##*[class$="-adv"]` to my filters and check if it works for you.

**Comment by xlollomanx** [comment]
> https://www.formulapassion.it/opinioni/alberto-antonini/f1-sviluppi-mannari-ferrari-binotto-leclerc-miami-verstappen-redbull-barcellona-616821.html

Seems it's working fine, thanks!

**Comment by MasterKia** [comment]
There's also anti-adblock which needs to be addressed.
https://user-images.githubusercontent.com/17685483/167382558-102465f2-838d-4311-ad5a-65f29ffea805.png
<details>
  <summary>Anti-adblock code</summary>

```javascript
if (b.adBlockerEnabled && d.monetize && d.adblocker_disables && !b.isBot())
 this.showMessage(d.translate && d.translate.adblocker ? d.translate.adblocker : "AD BLOCKER DETECTED!<br />Bla bla bla");
else {
    d.alterPlaybackBehaviour && b.PlaybackBehaviours.alterPlaybackBehaviour(d,
        d.alterPlaybackBehaviour);
    b.adBlockerEnabled && d.monetize && d.adblocker_disables_autoplay && (d.autoplay = !1, d.autoplay_on_ad = !1, d.ad_preload = !1);
```
</details>

**Comment by MasterKia** [comment]
`formulapassion.it##+js(set, document.bridCanRunAds, true)` seems to disable the adblock.

**Comment by xlollomanx** [comment]
> `formulapassion.it##+js(set, document.bridCanRunAds, true)` seems to disable the adblock ~but the video wouldn't play even with uBO off~ it took a couple of seconds for the video to load.

I can confirm this is working, just take a few seconds to load, thanks

**Comment by stephenhawk8054** [comment]
I think the video in `https://www.formulapassion.it/opinioni/alberto-antonini/f1-sviluppi-mannari-ferrari-binotto-leclerc-miami-verstappen-redbull-barcellona-616821.html` is an ads video? Each time I refresh the link it shows a different video
