### ISSUE TITLE
who13.com: nuisance

### ISSUE THREAD

**Issue by john-clark** [uBlockOrigin/uAssets#13130]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://who13.com/news/post-prom-party-shooting-in-des-moines-injures-three/`

### Category

nuisance

### Describe the issue

Overlay on content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Capture](https://user-images.githubusercontent.com/3967451/167306463-f483a1a7-0c00-4e02-ad69-a0481c1da42a.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 91
filterset (summary): 
  network: 81986
  cosmetic: 42988
  scriptlet: 16800
  html: 649
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31680-29, now
    ublock-badware: 4169-3, now
    ublock-privacy: 221-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1792-0, now
    ublock-quick-fixes: 214-0, now
    easylist: 66531-588, now
    easyprivacy: 26948-577, now
    urlhaus-1: 8474-0, now
    plowe-0: 3676-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 987 ms
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 39
  blockedDetails: 
    who13.com: 2
    aaxads.com: 1
    addthis.com: 1
    amazon-adsystem.com: 1
    chartbeat.com: 3
    confiant-integrations.global.ssl.fastly.net: 2
    d15kdpgjg3unno.cloudfront.net: 2
    d3plfjw9uod7ab.cloudfront.net: 2
    dmpxs.com: 2
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    imrworldwide.com: 2
    nexstardigital.net: 2
    nxstrib.com: 2
    onesignal.com: 2
    permutive.app: 2
    revcontent.com: 2
    rlcdn.com: 1
    sail-horizon.com: 2
    segment.com: 1
    wp.com: 2
```
</details>

**Comment by zeref-dragneel** [comment]
I don't have any problems 😺 

https://user-images.githubusercontent.com/95934994/167306651-5c73296c-dc15-4d3e-b734-cc3980c585e2.mp4

**Comment by JobcenterTycoon** [comment]
Works fine for me to

**Comment by john-clark** [comment]
Update: works as expected in IceCat and FireFox but not WaterFox, probably not a uBlockOrigin problem.
