### ISSUE TITLE
crystalmark.info: breakage

### ISSUE THREAD

**Issue by coldjg** [uBlockOrigin/uAssets#13135]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crystalmark.info/en/software/crystaldiskinfo/`

### Category

breakage

### Describe the issue

I cannot see the screenshots of the program I am about to download on the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ublock origin
![image](https://user-images.githubusercontent.com/101618239/167320287-c3957eb9-ee3d-4851-acb9-7dd18408386f.png)

Ublock origin disabled
![Screenshot 2022-05-08 4 33 26 PM](https://user-images.githubusercontent.com/101618239/167320296-1a64efff-326b-49b9-9e93-4122ee4b2105.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 81851
  cosmetic: 42911
  scriptlet: 16794
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 66425-51, 3d.6h.22m
    easyprivacy: 26943-121, 3d.6h.21m
    plowe-0: 3679-805, 3d.6h.20m
    ublock-abuse: 75-0, 3d.6h.18m
    ublock-badware: 4139-92, 3d.6h.16m
    ublock-filters: 30974-91, 3d.6h.15m
    ublock-privacy: 212-2, 3d.6h.14m
    ublock-quick-fixes: 214-0, 5h.51m
    ublock-unbreak: 1778-40, 3d.6h.12m
    urlhaus-1: 8474-0, 5h.50m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3124 ms (selfie)
  maxAssetCacheWait: 1366 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    crystalmark.info: 3
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    paypal.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`@@||crystalmark.info/wp-content/uploads/sites/3/CrystalDiskInfo8*.png$image,1p`

@ryanbr
