### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Donti42** [uBlockOrigin/uAssets#13137]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=BKznMMf7I4o`

### Category

ads

### Describe the issue

ublock is supposed to block all ads, and it was doing that, but then it began showing youtube ads, which isnt suppose to be happening

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 84958
  cosmetic: 47654
  scriptlet: 17006
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66425-51, 3d.13m
    easyprivacy: 26943-121, 3d.12m
    plowe-0: 3676-805, 11d.9h.17m
    spa-0: 3879-35, 5h.45m
    spa-1: 4458-168, 3d.14m
    ublock-abuse: 75-0, 3d.11m
    ublock-badware: 4139-92, 3d.10m
    ublock-filters: 30967-145, 3d.9m
    ublock-privacy: 212-2, 3d.8m
    ublock-quick-fixes: 213-0, 5h.44m
    ublock-unbreak: 1778-41, 3d.7m
    urlhaus-1: 8474-0, 5h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 440 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    youtube.com: 6
    doubleclick.net: 2
    google.com: 2
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by mapx-** [comment]
- try these indications: https://github.com/easylist/easylist/wiki/Youtube-Issues
- duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
