### ISSUE TITLE
filmzie.com breakage [cookie notice]

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#13143]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://filmzie.com/content/behind-the-wall?sourceId=613744175971e8001d714cd5`

### Describe the issue

The `##.cookie-modal` filter from EasyList Cookie does remove the cookie notice but also breaks the website because the scrollbar is disabled until you click "Reject" or "Agree".

### Screenshot(s)

The cookie notice:
https://user-images.githubusercontent.com/17685483/167378189-e42c1c79-809e-421c-98f0-2cf0f7838b8d.png

After clicking "Reject" or "Accept" (Notice the scrollbar):
https://user-images.githubusercontent.com/17685483/167378543-18e9afb3-859c-4fef-9a7c-73ddd4517b56.png

Removing the cookie notice using EasyList Cookie (The scrollbar is deactivated):
https://user-images.githubusercontent.com/17685483/167378870-d34fc69c-e760-48f1-aceb-847f65c183d0.png

### Notes

Only disabling JavaScript fixed the problem.
If this can't be fixed using the current uBO resources then I could ask the `EasyList Cookie` maintainer to whitelist this website.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 83580
  cosmetic: 71753
  scriptlet: 18184
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 31879-83, 19m
  default: 
    user-filters: 0-0, never
    easylist: 66428-51, 2d.21h.53m
    easyprivacy: 26943-121, 3d.3h.5m
    plowe-0: 3676-805, 9d.5h.47m
    ublock-abuse: 75-0, 3d.3h.4m
    ublock-badware: 4149-92, 3d.3h.4m
    ublock-filters: 30970-98, 3d.3h.4m
    ublock-privacy: 215-2, 3d.3h.4m
    ublock-quick-fixes: 220-0, 19m
    ublock-unbreak: 1779-41, 2d.20h.18m
    urlhaus-1: 8632-0, 19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 235 ms (selfie)
  maxAssetCacheWait: 219 ms
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
Actually `ghide` has just been added to this site: https://github.com/uBlockOrigin/uAssets/commit/ab828e5e860c75961780f0131717223c30e4a4f5 so that filter won't affect to the site any more. But it might need a specific one.

**Comment by MasterKia** [comment]
Why do these sites intentionally break functionality if the user doesn't reject/accept the cookies? It's weird.

**Comment by MasterKia** [comment]
> Actually `ghide` has just been added to this site: [ab828e5](https://github.com/uBlockOrigin/uAssets/commit/ab828e5e860c75961780f0131717223c30e4a4f5) so that filter won't affect to the site any more. But it might need a specific one.

https://github.com/easylist/easylist/commit/24fdc57ee928aae6e7792a8b7cc39c2625c5fd4c addresses the scrollbar being disabled but `@@||filmzie.com^$ghide` (https://github.com/uBlockOrigin/uAssets/commit/ab828e5e860c75961780f0131717223c30e4a4f5) prevents `##.cookie-modal` from EL Cookie to take effect.

**Comment by mapx-** [comment]
if I add
`filmzie.com##.cookie-modal` 
it seems the video is unplayable

**Comment by ryanbr** [comment]
Should filmzie.com#@#.cookie-modal also be applied, or is there a another snippet that can avoid/disablle the cookie check?

**Comment by mapx-** [comment]
I guess you have to add `filmzie.com#@#.cookie-modal` to EL cookie

**Comment by MasterKia** [comment]
The video can only be played of you "Accept All" cookies.

https://user-images.githubusercontent.com/17685483/167568167-2827d8c3-21b5-4519-9dd8-dbc5accb0a9c.mp4

**Comment by MasterKia** [comment]
The site checks for localStorage and not for cookies, so I guess we can't do anything about this using uBO resources.
