### ISSUE TITLE
loawa.com: ads

### ISSUE THREAD

**Issue by ZeNjiGG** [uBlockOrigin/uAssets#13149]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://loawa.com/`

### Category

ads

### Describe the issue

Ads are showing on the website. All the ads were blocked before, but it seems that the website creator does update the site from time to time and ads are going through sometimes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82123
  cosmetic: 42953
  scriptlet: 16793
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    easylist: 66546-51, 4h.13m
    easyprivacy: 26949-121, 4h.15m
    plowe-0: 3676-804, 8d.20h.39m
    ublock-abuse: 75-0, 9d.40m
    ublock-badware: 4165-92, 4h.14m
    ublock-filters: 30970-91, 2d.17h.24m
    ublock-privacy: 213-3, 10d.3h.39m
    ublock-quick-fixes: 214-0, 8h.18m
    ublock-unbreak: 1780-40, 4h.16m
    urlhaus-1: 8632-0, 8h.17m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 305 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    cloudflareinsights.com: 1
    doubleclick.net: 2
    fonts.googleapis.com: 4
    googleadservices.com: 1
    googlesyndication.com: 9
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update `uBlock filters – Quick fixes` it got fixed 8 hours ago
