### ISSUE TITLE
Startpage.com privacy

### ISSUE THREAD

**Issue by rn83** [uBlockOrigin/uAssets#13141]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://eu.startpage.com/sp/search
https://us.startpage.com/sp/search
https://www.startpage.com/sp/search
```

### Describe the issue

The result page of startpage.com sends an XHR request to the following URL.
```
https://eu.startpage.com/sp/elp
https://us.startpage.com/sp/elp
https://www.startpage.com/sp/elp
```

And the request content (POST parameters) is like this.

> sg=`TIMESTAMP`&tzo=`TIMEZONE_OFFSET`&uw=`SCREEN_WIDTH`&uh=`SCREEN_HEIGHT`&bw=`BROWSER_WIDTH`&bh=`BROWSER_HEIGHT`&ln=en

These values expose client info that can be used for fingerprinting, so I am wondering if this should be blocked for privacy.

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 100

### Settings

none

**Comment by JohnyP36** [comment]
It seems these are the only things `sp/elp` is colleting. So I could be blocked.

**Comment by MasterKia** [comment]
> Yes, and the POST parameters are collected as follows.
> 
> ```js
> {sg:window.elpSupport.sig,tzo:-o.getTimezoneOffset(),uw:window.screen.width,uh:window.screen.height,bw:window.innerWidth?window.innerWidth:r.clientWidth,bh:window.innerHeight?window.innerHeight:r.clientHeight,ln:window.elpSupport.lang}
> ```

So much for a 'privacy' focused search engine.

**Comment by JobcenterTycoon** [comment]
Got fixed in EasyPrivacy

**Comment by rn83** [comment]
Sorry for nagging @JobcenterTycoon, but I found that there is a XHR to `/sp/cl` when a result link is clicked.
```htm
    <script>
        var spClick = csInit('/sp/cl?sc=<RANDOM_HASH>', '/sp/pb?sc=<RANDOM_HASH>');
    </script>
```

Also, `/sp/pb` seems to be the pingback URL.
```js
window.csInit=function(t,n){
...
{baseClickUrl:t,basePingbackUrl:n,
...
```

**Comment by JobcenterTycoon** [comment]
@Yuki2718 your thoughs? https://github.com/uBlockOrigin/uAssets/issues/13141#issuecomment-1121853561 not getting fixed in EP

**Comment by Yuki2718** [comment]
I don't see these xhr requests.

**Comment by JobcenterTycoon** [comment]
Can’t see `/sp/pb` to

**Comment by rn83** [comment]
Another one. When javascript is disabled, `/sp/nojst` works as a fallback for `/sp/jst`.
```htm
    <noscript class="bdst">
        <img src="/sp/nojst?bdst=RANDOM_HASH">
    </noscript>
    <script>window.sp=window.sp||{};window.sp.bdst='RANDOM_HASH'</script>

        <script data-ps="startpage/bdst.html">
            !function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=629)}({629:function(e,t,n){e.exports=n(630)},630:function(e,t){window.addEventListener("load",(function(){var e="bdst=".concat(window.sp.bdst);try{window.navigator.sendBeacon("/sp/jst",window.elpSupport.makeBlob(e))}catch(t){(new Image).src="".concat("/sp/jst","?").concat(e)}}))}});
        </script>
```
