### ISSUE TITLE
hl.co.uk: breakage

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#13148]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hl.co.uk/contact-us/email-us`

### Category

breakage

### Describe the issue

Infinite spinner on form submit.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82129
  cosmetic: 43022
  scriptlet: 16823
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 46-2, never
    easylist: 66531-51, 1d.27m
    easyprivacy: 26948-121, 1d.26m
    plowe-0: 3676-805, 5h.34m
    ublock-abuse: 75-0, 5h.33m
    ublock-badware: 4165-92, 1d.25m
    ublock-filters: 31039-90, 1d.24m
    ublock-privacy: 216-2, 5h.32m
    ublock-quick-fixes: 224-0, 1h.31m
    ublock-unbreak: 1780-40, 1d.23m
    urlhaus-1: 8632-0, 1h.30m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    hl.co.uk: 1
    ads-twitter.com: 1
    bing.com: 1
    chartbeat.net: 2
    demdex.net: 2
    doubleclick.net: 1
    facebook.com: 1
    omtrdc.net: 7
    verisign.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||assets.adobedtm.com/*libraryCode_source.min.js$script,domain=hl.co.uk`

EP breakage @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/90cb47cc5d552874bd140cb9163fd5184c7fd9bf
