### ISSUE TITLE
vipmarathi.com ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#1314]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://vipmarathi.com/download/7164/04_aala_holicha_sar_lai_bhari`

### Describe the issue

Ads/popup/
Also fake download {now/here} buttons(flashing)/

### Screenshot(s)

`http://prntscr.com/i2949z`

### Versions

- Browser/version: Firefox Android 57.04
- uBlock Origin version: 1.14.24

### Settings

-  uBO's default settings

### Notes

Apart from ubo default settings I tried adguard base filters+adguard mobile filters+annoyance filters....
Nothing yield

**Comment by ghajini** [comment]
Still showing those ads....
I used element picker to nullify ads but too much filters needed and ad reappear
@okiehsch

**Comment by okiehsch** [comment]
I changed my `User Agent`, does
`vipmarathi.com##a[href^="http://34.212.19.168:8080/Ck.php"]`
work for you?

**Comment by nimasaj** [comment]
Also, try the followings:
```
||34.212.19.168*
||54.68.166.58*
||cdn.1120057983.world*
vipmarathi.com##*[id^="vcb"]
vipmarathi.com##*[onclick="cdcd_sde_sder()"]
```

**Comment by ghajini** [comment]
@okiehsch Yes those worked,but I see these 3rd party images loaded as per logger(but they are hided by your filters🤔)
`http://prntscr.com/i2gxrv`
`http://prntscr.com/i2gxks`

**Comment by okiehsch** [comment]
Well, just block them.
````
||adgup.com^$image,domain=vipmarathi.com
||1120057983.world^$image,domain=vipmarathi.com
````
You will need
`````
vipmarathi.com##a[href*="/Ck.php"]
vipmarathi.com##a[href^="http://adgup.com/Google.php"]
````
anyway to remove the clickable links.

**Comment by okiehsch** [comment]
I will add the filters, seeing as this is a mobile specific issue and I don't know EasyList's "policy" regarding such issues.
