### ISSUE TITLE
sessions.bugsnag.com

### ISSUE THREAD

**Issue by russellholz** [uBlockOrigin/uAssets#13150]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

sessions.bugsnag.com

### Describe the issue

Chrome cannot connect to sessions.bugsnag.com getting ERR_BLOCKED_BY_CLIENT

### Screenshot(s)

![Screen Shot 2022-05-09 at 2 00 21 PM](https://user-images.githubusercontent.com/103079936/167497890-a5eae3bc-a3ed-4714-a742-3da7e1223601.jpg)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome Version 101.0.4951.54

### Settings

none

**Comment by stephenhawk8054** [comment]
Can you give original site where you are having issues, describe the breakages and steps to reproduce?

**Comment by russellholz** [comment]
It's on our localhost, we are developing a Sass product and are using bugsnag as our bug reporting service, the site is not public yet so unfortunately you won't be able to visit to repro. As for steps literally as soon as we login when bugsnag tries to initialize we get the connection refused error

**Comment by mapx-** [comment]
For now add

`||bugsnag.com^$3p,badfilter`

when the site will be online (and you'll be able to provide a test account) let us know
