### ISSUE TITLE
balance.vanillagift.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#13156]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`balance.vanillagift.com`

### Describe the issue

Can't check balance of card. Gives error when entering card info.

### uBlock Origin version

1.42.4

### Browser name and version

Chrome 101

### Settings

Default

### Notes

`@@||ssl.kaptcha.com/collect/sdk$xhr,domain=balance.vanillagift.com`
If needed, I can provide an example card to test by email.

**Comment by mapx-** [comment]
@ryanbr
