### ISSUE TITLE
geeknetic.es

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#13159]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.geeknetic.es/`

### Describe the issue

Ads

Tested: `geeknetic.es##+js(cookie-remover)` and blocking all scripts.. 🤨

### Screenshot(s)

![adsss](https://user-images.githubusercontent.com/33556647/167703132-9b9dadd1-fce9-4b3c-9e63-c3f5661ebc47.PNG)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome - 100.

### Settings

Default ESP + Annoyances

**Comment by mapx-** [comment]
`geeknetic.es##.geekads`

does it work ?

**Comment by PIZZA90** [comment]
yeeah works

**Comment by mapx-** [comment]
@Yuki2718

**Comment by mapx-** [comment]
the background (clickable) ads ?

test

```
geeknetic.es##body:style(background-image:none !important)
geeknetic.es##+js(nowoif)
```

**Comment by mapx-** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
`||geeknetic.es/ajax/renderads.asp` works, but I'll also add css and js fixes in case they change the path.
