### ISSUE TITLE
conad.it - breakage (missing items in the page)

### ISSUE THREAD

**Issue by MilosBranko** [uBlockOrigin/uAssets#13157]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Some items in the page do not show up. 
(even after having cleared the cache + updated the filters)

### A specific URL where the issue occurs

`https://www.conad.it/prodotti.1608.html?page=2`

### Steps to Reproduce

Just accessing the above page

### Expected behavior

in the lower part of the page "i prodotti" (The products) should appear, but they don't
(verifyed using an other browser without uBO)

### Actual behavior

Some items in the page do not show up

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 86989
  cosmetic: 50323
  scriptlet: 16832
  html: 650
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31714-101, now
    ublock-badware: 4139-3, now
    ublock-privacy: 221-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1792-0, now
    ublock-quick-fixes: 229-0, now
    easylist: 66621-519, now
    easyprivacy: 26952-592, now
    urlhaus-1: 7755-0, now
    plowe-0: 3676-3, now
    ITA-0: 12997-1, now
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13202 ms (selfie)
  maxAssetCacheWait: 7208 ms
```
</details>

**Comment by mapx-** [comment]
Test this filter

`@@||assets.adobedtm.com/extensions/*/AppMeasurement$script,domain=conad.it`
