### ISSUE TITLE
[nsfw] onlyhotleaks.com: popups

### ISSUE THREAD

**Issue by Hajdar51** [uBlockOrigin/uAssets#13162]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://onlyhotleaks.com/`

### Category

popups

### Describe the issue

This site opens 3 popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 400816
  cosmetic: 47575
  scriptlet: 29265
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt: 6097-0, 11h
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/specific.txt: 23399-507, 11h
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-136, 11h
    https://raw.githubusercontent.com/Yuki2718/adblock/master/adguard/anti-antiadb.txt: 307-19, 11h
    https://raw.githubusercontent.com/Yuki2718/adblock/master/no_gen_cosm/phhider.txt: 681-44, 11h
    https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt: 2625-44, 11h
    adguard-generic: 63581-23670, 11h
    adguard-mobile: 7697-71, 11h
    adguard-spyware: 26154-797, 11h
  default: 
    user-filters: 2102-225, never
    ublock-filters: 31108-3508, 11h
    ublock-quick-fixes: 229-9, 11h
    urlhaus-1: 8557-609, 9h.46m
filterset (user): [array of 2067 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1561 ms
  maxAssetCacheWait: 582 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by FanOfRootBeer** [comment]
dead site?
