### ISSUE TITLE
[nsfw] vod.afreecatv.com: ads

### ISSUE THREAD

**Issue by gibson-kim** [uBlockOrigin/uAssets#13163]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vod.afreecatv.com/player/87247519`

### Category

ads

### Describe the issue

On afreeca.tv, the ads on clips and VODs are not blocked. It works fine on live streams.

However on Chrome, it successfully blocks all ads on live streams, vods, and clips. Seems to be a problem for Firefox version only.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83161
  cosmetic: 49284
  scriptlet: 16780
  html: 648
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31610-30, 3d.1h.10m
    ublock-badware: 4158-3, 3d.1h.9m
    ublock-privacy: 220-0, 5d.29m
    ublock-abuse: 75-0, 5d.28m
    ublock-unbreak: 1791-0, 1d.3h.2m
    easylist: 66548-594, 1d.3h.1m
    easyprivacy: 26951-581, 1d.3h
    urlhaus-1: 7755-0, 2m
    plowe-0: 3676-3, 1d.3h.3m
    KOR-1: 8232-3, 3d.1h.11m
    ublock-quick-fixes: 229-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 402 ms (selfie)
  maxAssetCacheWait: 219 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    afreecatv.com: 23
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Your video needs an account.

I tested another one without needing of an account and I get no ads
`https://vod.afreecatv.com/player/87108405`

**Comment by mapx-** [comment]
@piquark6046

**Comment by piquark6046** [comment]
@gibson-kim 
I cannot access the content.
Can you provide the information of your account via my email?

---

I cannot reproduce your issue without an account and Afreecatv grid computing program.

**Comment by gibson-kim** [comment]
Seems like the ads may only appear if you set your browser/windows language to Korean. They were showing on both NSFW and non-NSFW clips and VODs, but only on firefox for some reason.

I was able to disable ads from showing up by adding these filters:

play.afreecatv.com###ad_video
play.afreecatv.com##.text_output
play.afreecatv.com##.promotion_area
play.afreecatv.com##.promotion_area_left
play.afreecatv.com##.promotion_area_right
vod-player.afreecatv.com/creatives/media/*
play.afreecatv.com###videoLayerCover
windroloxy.afreecatv.com/v101/hls/creatives/media/*
vod-player001.afreecatv.com/v101/hls/creatives/media/*
vod-player002.afreecatv.com/v101/hls/creatives/media/*
vod-player003.afreecatv.com/v101/hls/creatives/media/*

vod.afreecatv.com##.adcon-area
vod.afreecatv.com##.adballoon_icon
play.afreecatv.com##.adcon-area
play.afreecatv.com##.adballoon_icon

vod-play*.afreecatv.com/creatives/media/*
vod-play*.afreecatv.com/v101/creatives/media/*
