### ISSUE TITLE
[nsfw] camwhorescloud.com: popups

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13164]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.camwhorescloud.com/videos/806960/cosmicstarlight-of-joi-while-we-eat-each-other-out/`

### Category

popups ans ads-video

### Describe the issue

The site opens video ads before displaying the video and then during playback, popups open if you click somewhere on the page.

![image](https://user-images.githubusercontent.com/50231020/167739797-51235d9c-3dbb-479a-af8f-3ee76a5e3258.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 400018
  cosmetic: 47568
  scriptlet: 29273
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-unbreak: null
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt: 6097-0, 1h.31m
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/specific.txt: 23404-507, 1h.31m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-136, 1h.31m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/adguard/anti-antiadb.txt: 300-18, 1h.31m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/no_gen_cosm/phhider.txt: 681-44, 1h.31m
    https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt: 2625-44, 1h.31m
    adguard-generic: 63576-23676, 1h.31m
    adguard-mobile: 7703-71, 1h.31m
    adguard-spyware: 26160-797, 1h.31m
  default: 
    user-filters: 2107-225, never
    ublock-filters: 31110-3509, 1h.31m
    ublock-quick-fixes: 229-9, 1h.31m
    urlhaus-1: 7755-610, 1h.31m
filterset (user): [array of 2044 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1355 ms
  maxAssetCacheWait: 497 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    camwhorescloud.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I see the popup when clicking on video and thumbnails, so I fixed that. However, I can't reproduce the videos ads before playing or popup at other places. Can you force update the filter lists in about 10 minutes and test again?

**Comment by mapx-** [comment]
> I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

Did you ? You disabled important lists and added other ones

**Comment by Yuki2718** [comment]
I recommend not to derail too much from the default. Spam404 and Nano Defender Integration are pretty much dead lists. AG Base in stock uBO lists is to be used with EasyList and also adding `https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/specific.txt` doesn't make sense if you have Base enabled. My Anti Anti-adblock Enhancer for AdGuard is for AG as the title says and is mostly redundant for uBO.
