### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by syborgxx** [uBlockOrigin/uAssets#13166]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/gp/video/detail/B09D42S7TF/ref=atv_dp_season_select_s7`

### Category

ads

### Describe the issue

Freevee ads show up on Amazon Prime Videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![freevee](https://user-images.githubusercontent.com/81539304/167745685-974a7931-7813-49b6-b7b6-8a0407e163b4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 158288
  cosmetic: 142522
  scriptlet: 35818
  html: 656
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-1, 2d.20h.39m
    adguard-generic: 63625-5237, 1d.18m
    adguard-mobile: 7696-232, 1d.19m
    adguard-spyware: 26153-1239, 1d.17m
    adguard-spyware-url: 597-15, 1d.16m
    block-lan: 43-0, 15d.20h.38m
    curben-phishing: 14469-2, 1d.10m
    curben-pup: 257-0, 1d.9m
    adguard-annoyance: 52812-4570, 1d.14m
    adguard-social: 17022-1652, 1d.13m
    fanboy-thirdparty_social: 68-1, 5d.20h.50m
    fanboy-annoyance: 70812-59433, 5d.20h.48m
    fanboy-cookiemonster: 31862-15071, 5d.20h.49m
    fanboy-social: 23368-13617, 1d.12m
    ublock-annoyances: 4410-7, 1d.15m
    dpollock-0: 10364-1637, 10d.21h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31702-283, 1d.24m
    ublock-badware: 4174-3, 1d.23m
    ublock-privacy: 221-1, 2d.20h.41m
    ublock-abuse: 75-0, 2d.20h.40m
    ublock-unbreak: 1792-0, 1d.22m
    easylist: 66580-24919, 1d.21m
    easyprivacy: 26951-10569, 1d.20m
    urlhaus-1: 8632-0, 1d.11m
    plowe-0: 3676-348, 10d.1h.48m
    ublock-quick-fixes: 229-0, 1d.8m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1442 ms (selfie)
  maxAssetCacheWait: 970 ms
popupPanel: 
  blocked: 109
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    amazon.com: 109
```
</details>

**Comment by mapx-** [comment]
> Amazon Prime

if you would like us to investigate and would like to provide us with your amazon prime account just let us know ( moderators of https://www.reddit.com/r/uBlockOrigin ) on reddit (private msg)

**Comment by Movisivi** [comment]
Why was this closed? Ads still appear

**Comment by mapx-** [comment]
> if you would like us to investigate and would like to provide us with your amazon prime account just let us know ( moderators of https://www.reddit.com/r/uBlockOrigin ) on reddit (private msg)

**Comment by okiehsch** [comment]
I have amazon prime but can't reproduce, so I assume it's only an issue for US prime members.

**Comment by Avnsx** [comment]
Nope I'm not from the US and still get advertisements on as amazon prime customer, when watching freevee content

**Comment by mapx-** [comment]
- Example links ? 
- what country are you accessing that site ?
- free or is required a paid account ? => if a paid one tell me if you are willing to give us the credentials of your account in order to investigate the issue (I'll provide an email address in case you confirm it)

**Comment by okiehsch** [comment]
I assume you are using `amazon.nl`?
If so try adding
````
amazon.nl##+js(json-prune, cuepointPlaylist)
amazon.nl##+js(xml-prune, Period:\has([value="Ad"]), , .mpd)
amazon.nl##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] | //*[name()="Period"]/@start), [value="Ad"], .mpd)
````
to your filter list.

**Comment by okiehsch** [comment]
@mapx- you need an amazon prime account to watch for freevee content.
I can reproduce video ads at my location.

**Comment by stephenhawk8054** [comment]
@Avnsx So which domain are you using when accessing amazon, is it `amazon.nl`?

**Comment by Avnsx** [comment]
> @Avnsx So which domain are you using when accessing amazon, is it `amazon.nl`?

No it's .de and his commit fixed it
