### ISSUE TITLE
"Service Unavailable" error for: https://firebase.google.com/docs/analytics/events?platform=android

### ISSUE THREAD

**Issue by ozmium** [uBlockOrigin/uAssets#13178]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://firebase.google.com/docs/analytics/events?platform=android`

### Describe the issue

Whilst logged into any Google account, open the Firebase documentation link `https://firebase.google.com/docs/analytics/events?platform=android` with uBlock Origin enabled (latest version), with the common settings. You will see "Service Unavailable" and the web page will not load. The expected result is to load the page normally.

Workarounds:
- Disable the uBlock Origin extension, then reload the page
- Turn off uBlock Origin for site firebase.google.com (click the 'on/off' blue button for the website, and reload the page)
- Use an Incognito Tab or Private Tab, signed out of Google, then open the link

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Mozilla Firefox 99.0.1, Google Chrome Version 100.0.4896.127

### Settings

None

**Comment by mapx-** [comment]
- I can reproduce only using firefox
- bypassing the cache "fixes" the issue

test
`@@||firebase.google.com/docs/analytics/events$xhr,1p`

**Comment by mapx-** [comment]
@ryanbr
