### ISSUE TITLE
rockfile.co [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1317]
URL(s) where the issue occurs

`http://rockfile.co/n86y7iom5imw.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
`http://rockfile.co/860al7tc8cas.html` @mapx-

**Comment by KiLL4FuNK** [comment]
@mapx- Anti-Adblock

**Comment by KiLL4FuNK** [comment]
@mapx- Anti-Adblock  
fill the captcha

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://rockfile.co/mqmtkjc1hptz.html`

**Comment by ghajini** [comment]
antiadblock
`https://rockfile.co/8rg6aren02u2.html`
![screenshot 103](https://user-images.githubusercontent.com/20338483/51376919-8927a380-1b2f-11e9-8add-da3016bb80ea.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fed405a57104c323c5bfbc3938b0f1d7b75c45cc

**Comment by mapx-** [comment]
Tested in opera Version:60.0.3255.79 too
uBo last dev build 1.18.17rc5

No odd baheviour on my side

**Comment by mapx-** [comment]
No issue here, last uBo dev build 1.18.17rc5, last opera version 60.0.3255.79

**Comment by mapx-** [comment]
No issue here, last uBo dev build 1.18.17rc5, last opera version 60.0.3255.79

**Comment by mapx-** [comment]
No issue here, `last uBo dev build 1.18.17rc5, last opera version 60.0.3255.79`

**Comment by mapx-** [comment]
No issue in opera

**Comment by mapx-** [comment]
No issue in opera

**Comment by mapx-** [comment]
No issue in opera

**Comment by mapx-** [comment]
No issue in opera

**Comment by bogachenko** [comment]
@mapx- well, see for yourself  https://user-images.githubusercontent.com/8535285/57423706-c17afb00-7260-11e9-93ba-8abde71bf1bc.gif
