### ISSUE TITLE
guancha.cn: ads

### ISSUE THREAD

**Issue by hzx505** [uBlockOrigin/uAssets#13179]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.guancha.cn/internation/2022_05_11_639311.shtml`

### Category

ads

### Describe the issue

Bottom Banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 74673
  cosmetic: 82106
  scriptlet: 19544
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
  added: 
    adguard-annoyance: 52942-1720, 1h.14m
    adguard-social: 17048-1936, 1h.14m
  default: 
    user-filters: 2-0, never
    CHN-0: 28618-1153, 1h.38m
    adguard-mobile: 7715-57, 1h.38m
    easyprivacy: 26958-232, 1h.34m
    plowe-0: 3677-587, 1h.33m
    ublock-abuse: 75-0, 1h.31m
    ublock-badware: 4140-5, 1h.29m
    ublock-filters: 31400-623, 1h.28m
    ublock-privacy: 216-3, 1h.27m
    ublock-quick-fixes: 230-3, 1h.26m
    ublock-unbreak: 1784-37, 1h.24m
    urlhaus-1: 7984-0, 1h.23m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 634 ms
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    guancha.cn: 1
    baidu.com: 1
    cnzz.com: 1
```
</details>

**Comment by mapx-** [comment]
```
m.guancha.cn##.swiper-slide
m.guancha.cn##.g_swiper_container
m.guancha.cn##.g_seat
```

for chn list, @Yuki2718

**Comment by cjx82630** [comment]
@stephenhawk8054 Those banners are considered to be self-promotion, guiding readers to download the website app, will not be fixed by ELC.
