### ISSUE TITLE
fullcrack.vn: badware

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13177]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fullcrack.vn/idm-6-38-full-crack/`

### Category

privacy

### Describe the issue

You can get malware by downloading file. Looks like it's hidden in the folder 0 to 9. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82434
  cosmetic: 21193
  scriptlet: 19864
  html: 657
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4412-7, 7h.34m
  default: 
    user-filters: 1-0, never
    ublock-filters: 31893-260, 7h.35m
    ublock-badware: 4144-3, 7h.35m
    ublock-privacy: 221-1, 7h.35m
    ublock-abuse: 75-0, 7h.35m
    ublock-unbreak: 1789-0, 7h.34m
    ublock-quick-fixes: 229-0, 7h.34m
    easylist: 66621-24530, 7h.34m
    easyprivacy: 26952-581, 7h.34m
    urlhaus-1: 7805-0, 7h.34m
    plowe-0: 3676-3, 7h.34m
    VIE-1: 1906-31, 7h.34m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 675 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    a-ads.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
needing more details: the whole site is providing malware or only a part of it, can we distinguish between them (downloaded items) .. ?

**Comment by JobcenterTycoon** [comment]
Seems to be the downloads on the startpage contains no malware but all other downloads contains the malware hidden in the file 0-9 (go every page a number higher so start from 0, next is 1, next is 2 ...)

I get `1.exe` (33 detections on VT) and `msw.exe` (40 detections on VT)

`||fullcrack.vn/*Cr@ck*.rar$all` seems to work fine and not affect the downloads on the startpage

**Comment by zeref-dragneel** [comment]
> `||fullcrack.vn/*Cr@ck*.rar$all` seems to work fine and not affect the downloads on the startpage

 I can still download this way
<img src="https://i.imgur.com/AYKSORH.png" height="150">
 Not to mention they can add other download sources like mediafıre, mega, ... if they know they are blocked by ublock

**Comment by stephenhawk8054** [comment]
Yeah, I think the whole site should be blocked. Even the URL is starting to get flagged on virustotal and is already flagged as malware by Avira and ESET:

https://www.virustotal.com/gui/url/dbbaf150f10822d2df1fb5a3e7543602b0f658d9a46ed0e982e3d294f3aeec89/detection

**Comment by zeref-dragneel** [comment]
> So hardblock the complete site?

You can decide this through what I report. I'm just checking for you where users might encounter it so you can handle it in the best way.
