### ISSUE TITLE
https://punchsub.com/ resource abuse script mining

### ISSUE THREAD

**Issue by ialexsilva** [uBlockOrigin/uAssets#1318]
### URL(s) where the issue occurs

`https://punchsub.com/`

### Describe the issue

This site run script mining

### Versions

- Browser/version: Firefox 57.0.4
- uBlock Origin version: 1.14.24

### Settings

- [uBO's default settings +Adguard’s Annoyance List ]

**Comment by mapx-** [comment]
I'm redirected to `http://www.aliancaproject.com.br/` and then to `https://zlx.com.br/` without clicking the page, so I guess it's some geo-redirection

If you can use that page, see if this filter is helping you
`||punchsub.com^$csp=child-src 'none';frame-src *;worker-src 'none';`

**Comment by ialexsilva** [comment]
@mapx-  
![image](https://user-images.githubusercontent.com/6363160/35172510-1e13efc6-fd4f-11e7-95d7-9889eb3bf98b.png)

**Comment by mapx-** [comment]
test also:
`punchsub.com##script:inject(abort-on-property-read.js, miner)`

did you test the other filter ?

**Comment by ialexsilva** [comment]
@mapx dont work the `https://zlx.com.br/assets/playermon.js` still loading

I added ` ||zlx.com.br/assets/playermon.js$script,domain=punchsub.com` and works
