### ISSUE TITLE
Iqiyi video playing will be break when a video playing was done.

### ISSUE THREAD

**Issue by vgjh2005** [uBlockOrigin/uAssets#13180]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.iqiyi.com/v_19rrjzj6n0.html#curid=108798000_undefined`

### Describe the issue

Hi:
0. Please ensure  
      uBlock filters
has been opened.
1. Please use the below link to finish the video playing
`https://www.iqiyi.com/v_19rrjzj6ck.html#curid=108798600_undefined`
2. Web page will certainly  load another video. But not now.
Thanks!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6017838/167956419-3d5f6165-67bb-449e-9d15-429bafb2ee54.png)

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Google Chrome: 101.0.4951.54 release （x64 ） 

### Settings

Please ensure regular list "uBlock filters" is enabled.

### Notes

Enable all filter lists one by one to decide error from the uBlock filters.

**Comment by stephenhawk8054** [comment]
I think it's caused by `iqiyi.com##+js(set, Object.prototype.parseXML, noopFunc)` from this issue: [https://github.com/uBlockOrigin/uAssets/issues/7136](https://github.com/uBlockOrigin/uAssets/issues/7136)? However looks like it needs Chinese VPN to play the videos.

**Comment by mapx-** [comment]
Using a Taiwan vpn the link above redirects to

`https://www.iq.com/play/the-wind-blows-from-longxi-episode-1-2331nywa02w?lang=en_us`

and the video is playing fine

**Comment by stephenhawk8054** [comment]
Yeah, the domain `iqiyi.com` seems only work with China IP, Taiwan and Hong Kong's IPs will just redirect to `iq.com`.

**Comment by mapx-** [comment]
maybe @cjx82630 could help

**Comment by mapx-** [comment]
@vgjh2005 

what if you add this exception ?
`iqiyi.com#@#+js(set, Object.prototype.parseXML, noopFunc)`

if works for this issue, do you get some other issue as a consequence ?
