### ISSUE TITLE
lacentrale.fr: breakage

### ISSUE THREAD

**Issue by ErnestPietryka** [uBlockOrigin/uAssets#13197]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lacentrale.fr/`

### Category

breakage

### Describe the issue

Can't start a search with ublock origin activated (first screenshot)
It's also impossible to sort results on lacentrale.fr/listing (second screenshot)

### Screenshot(s)

<details>
<img width="1036" alt="screen 1" src="https://user-images.githubusercontent.com/51130381/168152755-05066138-c5c4-45c5-b12d-f15e758ae6cb.png">

<summary>Screenshot(s)</summary>
<img width="976" alt="screen 2" src="https://user-images.githubusercontent.com/51130381/168152760-4cf05977-c3c7-47be-99ad-7bdfdbbf453b.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 123750
  cosmetic: 200171
  scriptlet: 35846
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    plowe-0: null
  added: 
    adguard-annoyance: 52849-171, 2d.46m
    adguard-generic: 63576-682, 2d.45m
    adguard-mobile: 7703-50, 2d.44m
    adguard-social: 17029-852, 2d.43m
    adguard-spyware: 26160-881, 2d.42m
    adguard-spyware-url: 597-13, 2d.41m
    block-lan: 43-0, 7d
    fanboy-annoyance: 70817-4122, 7d
    fanboy-cookiemonster: 31865-31865, 7d
    fanboy-social: 23369-23365, 2d.38m
    fanboy-thirdparty_social: 68-21, 7d
    ublock-annoyances: 4402-218, 2d.37m
  default: 
    user-filters: 12-5, never
    easylist: 66621-912, 2d.40m
    easyprivacy: 26952-10185, 2d.39m
    ublock-abuse: 75-0, 7d
    ublock-badware: 4135-295, 2d.36m
    ublock-filters: 31108-3603, 2d.35m
    ublock-privacy: 215-47, 7d
    ublock-unbreak: 1780-103, 2d.34m
    urlhaus-1: 7913-0, 2h.43m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 28 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 834 ms (selfie)
  maxAssetCacheWait: 546 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    lacentrale.fr: 4
    datadome.co: 1
    kameleoon.eu: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`||lacentrale.fr/static/fragment-layout/tracking-$badfilter`
fixes the issue, I think you have to remove that filter.
