### ISSUE TITLE
nsfw 10starhd.lol

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13191]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW
`https://10starhd.lol/18-feisty-and-elegant-scarlett-jones-2022-english-720p-hdrip-400mb-download/`

### Describe the issue

popup ads

### uBlock Origin version

1.42.5rc0

### Browser name and version

opera stable

### Settings

Default

### Notes

going back to homepage brings back propeller thus ads when tried scriptlet filters
(when propeller code is at top of page)

**Comment by ghajini** [comment]
This work for me

`10starhd.lol##+js(aopr, XMLHttpRequest)`
but since script is inline i would expect `acis` work(there are other cases where `acis` not worked)

**Comment by ghajini** [comment]
this is also good
`10starhd.lol##+js(aopr, XMLHttpRequest)`

**Comment by mapx-** [comment]
yes, it's good but could break something
