### ISSUE TITLE
docs.google.com: breakage

### ISSUE THREAD

**Issue by barkabar999** [uBlockOrigin/uAssets#13198]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://docs.google.com/`

### Category

breakage

### Describe the issue

When the website loads, it says that it is not connected. It is.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 96
filterset (summary): 
  network: 150330
  cosmetic: 200519
  scriptlet: 35994
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52943-171, 23h.18m
    adguard-generic: 63621-682, 23h.18m
    adguard-mobile: 7715-50, 23h.18m
    adguard-social: 17050-852, 23h.18m
    adguard-spyware: 26166-881, 23h.18m
    adguard-spyware-url: 597-13, 23h.18m
    block-lan: 43-0, 23h.18m
    curben-phishing: 14254-0, 23h.18m
    curben-pup: 262-0, 23h.18m
    dpollock-0: 10366-226, 23h.18m
    fanboy-annoyance: 70877-4128, 23h.18m
    fanboy-cookiemonster: 31889-31889, 23h.18m
    fanboy-social: 23369-23369, 23h.18m
    fanboy-thirdparty_social: 69-21, 23h.18m
    ublock-annoyances: 4404-220, 23h.18m
  default: 
    user-filters: 0-0, never
    easylist: 66642-1136, 1d.3h.15m
    easyprivacy: 26957-10252, 1d.3h.11m
    plowe-0: 3676-1326, 10d.3h.52m
    ublock-abuse: 75-0, 23h.18m
    ublock-badware: 4140-298, 1d.3h.14m
    ublock-filters: 31294-3613, 1d.3h.13m
    ublock-privacy: 216-49, 1d.3h.23m
    ublock-quick-fixes: 229-12, 23h.18m
    ublock-unbreak: 1778-98, 1d.3h.12m
    urlhaus-1: 7697-1, 23h.18m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 12 redacted]
urlRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6701 ms (selfie)
  maxAssetCacheWait: 1732 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google.com: 3
    gstatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce `not connected` issue. Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.
