### ISSUE TITLE
gtop100.com: detection

### ISSUE THREAD

**Issue by TheCodeboy12** [uBlockOrigin/uAssets#13196]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gtop100.com/topsites/MapleStory/sitedetails/MapleRoyals-The-Nostalgic-MapleStory-Server-79510?vote=1&pingUsername=gabixd`

### Category

detection

### Describe the issue

Website is not allowing me to vote

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81476
  cosmetic: 43015
  scriptlet: 16826
  html: 649
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31724-93, 2d.5h.4m
    ublock-badware: 4174-3, 2d.5h
    ublock-privacy: 220-0, 6d.5h.37m
    ublock-abuse: 75-0, 6d.5h.36m
    ublock-unbreak: 1792-0, 2d.5h.3m
    easylist: 66606-516, 2d.5h.2m
    easyprivacy: 26952-590, 2d.5h.1m
    urlhaus-1: 7880-0, 6h.20m
    plowe-0: 3676-3, 6d.5h.34m
    ublock-quick-fixes: 230-0, 6h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3182 ms (selfie)
  maxAssetCacheWait: 863 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    gtop100.com: 26
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot the issue?

**Comment by pgl** [comment]
The domain was added to my list on Sat Mar 3rd 2007 08:24. It's been a while. It does seem to have legit content on it now though, so I've removed it from my list.
