### ISSUE TITLE
imagefap.com NSFW

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#1319]
`http://www.imagefap.com/gallery.php` NSFW

There's a banner ad at the top and other ads on that website. Is there a way to get uBlock Origin to block those ads? Why aren't the various filter updates blocking those ads? uBlock Origin is a really good concept, but many times it doesn't block ads or websites are able to detect that you're using an adblocker and won't display the websites properly. Also, instead of having to find out which filter lists you need and installing scripts to make them work, can you just integrate all of that with uBlock Origin by default so that people don't have to customize all of that after they install it? Keep up the good work. Have a nice day. Thanks.

![imagefap com nsfw](https://user-images.githubusercontent.com/26278182/35176820-66c7ba14-fd49-11e7-9c9e-f0de70cd569a.jpg)

Waterfox 56.0.3 (64-bit)
uBlock Origin 1.14.24

**Comment by mapx-** [comment]
@js017, why are you posting here if you don't understand what you see on this page ?

` closed this in cb123a2` means it was fixed and you can click `cb123a2` above to see the fix. Update your lists and test the fix.

**Comment by okiehsch** [comment]
> I assume you closed this thread because you don't have an answer to fix that issue?

I assume you can't remember that I already explained to **you**,  what "closed this in ******" means.
https://github.com/uBlockOrigin/uAssets/issues/577#issuecomment-317548462

**Comment by SMed79** [comment]
Can someone (please) converte the inline **nsfw** image to a link.
