### ISSUE TITLE
forum.frag-mutti.de

### ISSUE THREAD

**Issue by alexara** [uBlockOrigin/uAssets#132]
### URL where the issue occurs

`https://forum.frag-mutti.de/index.php?showtopic=39961]`

### Describe the issue

To banners are showing, compare screenshot.

### Screenshot

![bannres_frag_mutti](https://cloud.githubusercontent.com/assets/13819719/18387932/b13ae04e-769f-11e6-807d-ae450b908c9f.png)

### Versions

- Browser/version:  FF 48.0
- uBlock Origin version: 1.9.6

### Settings

- Default + EasyList Germany

### Notes

If the Anti-Adblock Killer | Reek‎ filter list is activated, the banners are gone. However, if I block adternal.com completely in the expert mode, the banners come back.

Does this mean in order to block the advertising I MUST NOT block `adtech.com`?

### Logger (Filter: << || -- | image)
![bannres_frag_mutti_log](https://cloud.githubusercontent.com/assets/13819719/18388098/796f5900-76a0-11e6-8e95-1b8efb5ff793.png)

### HTML left banner
![bannres_frag_mutti_html](https://cloud.githubusercontent.com/assets/13819719/18388156/d6a6561e-76a0-11e6-90de-9b1591970a8e.png)

### Anti adblock detection script:
```JS
 function detect() {
        if (!window.trckd) {
            var body = doc.getElementsByTagName("body")[0],
                img = doc.createElement("img");
            if (isSafari()) {
                body.appendChild(img);
            };
            img.src = "https://www.adternal.com/" + Date.now() + "/ad-loading.bmp";
            img.onerror = function() {
                track();
                clean(this);
            };
            img.onload = function() {
                3 != this.width && (track(), clean(this));
            };
        }
    }
```

**Comment by alexara** [comment]
That was quick and works, thanks! However, unfortunately `adternal.com` scripts need to be allowed in order to block the ads.
As a workaround I created some filters with the picker, which remove the two banners and the space completely:
```
! 9.9.2016, 16:31:45 https://forum.frag-mutti.de/index.php?showtopic=39961
forum.frag-mutti.de###content > .container > .container-left > div:nth-of-type(1)

! 9.9.2016, 16:32:00 https://forum.frag-mutti.de/index.php?showtopic=39961
forum.frag-mutti.de###tsm > div
```

**Comment by gorhill** [comment]
Not sure I understand what you are saying. You say it works, but then you seem to say it does not work? I could not get the ads after I create the redirect filter. What ads are you talking about. Screenshot would help.

**Comment by gorhill** [comment]
> blocking it additionally with uMatrix make the ads come back ... :-(

Ok, that is because if you block with uMatrix, uBO won't see the network request and thus can't redirect it. You will have to locally allow the network requests to `adternal.com` for images in uMatrix, to give the opportunity for uBO to redirect the blocked images.

**Comment by alexara** [comment]
> Ok, that is because if you block with uMatrix, uBO won't see the network requests and thus can't redirect them. You will have to locally allow the network requests to adternal.com for images in uMatrix, to give the opportunity to uBO to redirect the blocked images.

Thanks, got it!
