### ISSUE TITLE
Twitter generated URLs can't be accessed

### ISSUE THREAD

**Issue by yeganathan18** [uBlockOrigin/uAssets#13207]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://twitter.com`

### Describe the issue

The URLs that's been generated by Twitter, link in the posts such as `https://t.co/Y2t0QMuuyn` isn't accessible and shots an error. I think it is due to Peter Lowe's Ad and tracking server list, blocking the URLs that starts with `||t.co^`.

I also tried using Firefox mobile app and the issue still persists. It would be great if someone reproduces the issue and ensure it happens due to the Peter Lowe's list.

### Screenshot(s)

LibreWolf

<img width="1792" alt="Screenshot 2022-05-13 at 7 48 03 PM" src="https://user-images.githubusercontent.com/63534555/168303529-6dd393a4-f438-4d97-9d15-214f461504fc.png">

Firefox Mobile App

<img width="300" alt="Screenshot 2022-05-13 at 7 48 03 PM" src="https://user-images.githubusercontent.com/63534555/168306618-bbaa3739-85eb-4aad-8ff4-1bb39527a2ac.png">

### uBlock Origin version

1.42.4

### Browser name and version

LibreWolf 1.42.4

### Settings

None

### Notes

There is no any changes with the extension settings, it runs by default settings.

**Comment by Janmm14** [comment]
Try update your filters (ubo filter settings, clear cache , then update)

An attempt was made to override peter lowe's filter list blocking it. if updating doesnt fix it for you, maybe the override is not working right

https://github.com/uBlockOrigin/uAssets/commit/45542b053fa902e5440ea2c1a1e0c7e6ccbd03b4

**Comment by okiehsch** [comment]
> if updating doesnt fix it for you, maybe the override is not working right.

Does it work for you?

**Comment by Janmm14** [comment]
> > if updating doesnt fix it for you, maybe the override is not working right.
> 
> Does it work for you?

for me t.co is not blocked right now (with & without peter lowe's filter active)

**Comment by okiehsch** [comment]
Ok, it works for me as well, if the OP continues to have the issue after updateing the `uBO-unbreak` then maybe it is because of the rather unusal browser in use.
The first screenshot is rather unusal, I have never seen that caused by a filter.
