### ISSUE TITLE
s.to: ads

### ISSUE THREAD

**Issue by darmstadt40** [uBlockOrigin/uAssets#13203]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.to/serie/stream/fresh-off-the-boat/staffel-1/episode-2`

### Category

ads

### Describe the issue

Ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 85075
  cosmetic: 28013
  scriptlet: 16759
  html: 650
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31596-274, 5h.8m
    ublock-badware: 4150-3, 5h.7m
    ublock-privacy: 220-1, 6h.14m
    ublock-abuse: 75-0, 6h.13m
    ublock-unbreak: 1794-0, 5h.6m
    ublock-quick-fixes: 186-0, 16h.24m
    adguard-mobile: 7723-178, 5h.9m
    easylist: 66711-24663, 5h.5m
    easyprivacy: 26964-596, 5h.4m
    urlhaus-1: 7913-0, 16h.23m
    plowe-0: 3676-3, 11d.5h.6m
    DEU-0: 5745-379, 16h.25m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 944 ms
  maxAssetCacheWait: 354 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    ads-twitter.com: 1
    chaturbate.com: 1
    imasdk.googleapis.com: 1
    tenbowed.com: 2
    yandex.ru: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any ads on the page, can you describe in more details?

**Comment by avotoko** [comment]
On my end, clicking on the video will open a new tab with ads.

Works for me.
```
voe-unblock.com##+js(nowoif)
```

**Comment by stephenhawk8054** [comment]
> On my end, clicking on the video will open a new tab with ads.
> 
> Works for me.
> 
> ```
> voe-unblock.com##+js(nowoif)
> ```

The filters for `voe-unblock` were already added few days ago: https://github.com/uBlockOrigin/uAssets/commit/eb09d242d6a6b71e312a47246a4c681045c768fd

**Comment by avotoko** [comment]
> The filters for voe-unblock were already added few days ago

Sorry, I neglected to update the filter.
