### ISSUE TITLE
skolon.lidingo.se: breakage

### ISSUE THREAD

**Issue by tombergstrom** [uBlockOrigin/uAssets#13201]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://skolon.lidingo.se/`

### Category

breakage

### Describe the issue

I can not acces the page. It says I am not connected to WIFI even though I am.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 83034
  cosmetic: 45332
  scriptlet: 17261
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    SWE-1: 3973-0, 1d.2h.59m
    easylist: 66674-59, 1d.2h.47m
    easyprivacy: 26958-128, 1d.2h.51m
    plowe-0: 3676-806, 11d.17h.37m
    ublock-abuse: 75-0, 11d.17h.39m
    ublock-badware: 4140-93, 1d.2h.50m
    ublock-filters: 31286-95, 1d.2h.49m
    ublock-privacy: 211-3, 11d.17h.38m
    ublock-quick-fixes: 230-0, 4m
    ublock-unbreak: 1778-40, 1d.2h.48m
    urlhaus-1: 8007-0, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 517 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
popupPanel: 
  blocked: 0
```

Looks like there's nothing blocked in your uBO logger. The site returns to this page for me:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/168238723-2a467cc6-06e6-4683-ae69-c924c1ff6eaf.png)

</details>

**Comment by mapx-** [comment]
> I can not acces the page

meaning after logging in or the logging is broken for you ?
