### ISSUE TITLE
gturls.com

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1320]
### URL(s) where the issue occurs
`http://gturls.com/qdrWjkK1`

### Describe the issue
Anti-adblock message.

### Screenshot(s)
![cookie-cutter shortener](https://user-images.githubusercontent.com/29117662/35180349-46b28744-fd63-11e7-9e08-77c971518786.PNG)

### Versions

- Browser/version: Chrome 63.0.3239.132 (Official Build) (64-bit)
- uBlock Origin version: v1.14.25.100 (Nano Adblocker 1.0.0.27)

### Settings
Default.

### Notes
Another cookie-cutter URL shortener.

**Comment by ghajini** [comment]
They start swapping new domains?
