### ISSUE TITLE
gmx.co.uk: ads

### ISSUE THREAD

**Issue by billysielu** [uBlockOrigin/uAssets#13208]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gmx.co.uk/`

### Category

ads

### Describe the issue

ads are visible
see screenshot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://user-images.githubusercontent.com/59173811/168316906-3ea43a83-72e8-48db-ba33-f4c3af99c2a5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81472
  cosmetic: 43037
  scriptlet: 16866
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 46-2, never
    easylist: 66606-51, 3d.3h.13m
    easyprivacy: 26952-121, 3d.3h.13m
    plowe-0: 3676-804, 3d.3h.13m
    ublock-abuse: 75-0, 3d.3h.13m
    ublock-badware: 4135-93, 3d.3h.12m
    ublock-filters: 31107-92, 3d.3h.12m
    ublock-privacy: 216-2, 3d.3h.12m
    ublock-quick-fixes: 229-0, 23h.24m
    ublock-unbreak: 1781-40, 3d.3h.12m
    urlhaus-1: 7913-0, 23h.23m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 210 ms (selfie)
  maxAssetCacheWait: 121 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    criteo.net: 2
    gmx.com: 2
    googletagmanager.com: 2
    googletagservices.com: 1
    taboola.com: 2
    ui-portal.de: 1
    uicdn.com: 1
    united-infos.net: 2
```
</details>

**Comment by okiehsch** [comment]
Does
`gmx.co.uk##+js(nostif, UABP)`
work without breaking anything on your end?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e25c8b0aa4767a346fac3d48cdabee92ed1a127b
