### ISSUE TITLE
websleuths.com: ads

### ISSUE THREAD

**Issue by michaelchany** [uBlockOrigin/uAssets#13200]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.websleuths.com/forums/threads/aruba-natalee-holloway-18-oranjestad-30-may-2005-2.347200/`

### Category

ads

### Describe the issue

Placeholder for the top ad still shows instead of being removed completely.  This is a recent change after they upgraded the server software.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-05-12 at 23-45-02 - Copy](https://user-images.githubusercontent.com/22213879/168227179-6ba0a5f7-cf11-4247-86db-4637ca2025e9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81704
  cosmetic: 43099
  scriptlet: 16950
  html: 652
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31951-96, 2m
    ublock-badware: 4150-3, 2m
    ublock-privacy: 220-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1790-0, 2m
    ublock-quick-fixes: 230-0, 2m
    easylist: 66711-517, 2m
    easyprivacy: 26964-590, 2m
    urlhaus-1: 8007-0, 2m
    plowe-0: 3676-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1132 ms
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    websleuths.com: 19
    doubleclick.net: 1
    ezodn.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`websleuths.com##[style]:has([id^="ezoic-pub-ad-placeholder"])`

@ryanbr
