### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by albertor00** [uBlockOrigin/uAssets#13217]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

[unknown]

### Describe the issue

Embedded video ads are showing again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 89231
  cosmetic: 79285
  scriptlet: 18371
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 31924-86, 1m
  default: 
    user-filters: 0-0, never
    ITA-0: 12999-0, 1m
    easylist: 66738-55, 1m
    easyprivacy: 26966-123, 1m
    plowe-0: 3672-804, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4145-94, 1m
    ublock-filters: 31338-111, 1m
    ublock-privacy: 214-2, 1m
    ublock-quick-fixes: 219-0, 1m
    ublock-unbreak: 1780-42, 1m
    urlhaus-1: 8292-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 369 ms (selfie)
  maxAssetCacheWait: 225 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    amplitude.com: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 3
    scorecardresearch.com: 5
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

Try the solutions here: https://github.com/pixeltris/TwitchAdSolutions/#twitchadsolutions
