### ISSUE TITLE
t.co links marked malicious

### ISSUE THREAD

**Issue by helpmonmon** [uBlockOrigin/uAssets#13214]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://t.co

### Describe the issue

blocking all links posted on and shortened by twitter through t.co and marking them as malicious

### uBlock Origin version

1.42.4

### Browser name and version

chrome

### Settings

-

**Comment by okiehsch** [comment]
Already fixedm update the `uBO-unbreak` list.
