### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by un-tren-raro** [uBlockOrigin/uAssets#13212]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=oqB1TH_fJp8`

### Category

ads

### Describe the issue

ublock no quita los anuncios

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85121
  cosmetic: 47869
  scriptlet: 17204
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66738-51, 24m
    easyprivacy: 26966-121, 23m
    plowe-0: 3673-803, 22m
    spa-0: 3882-35, 27m
    spa-1: 4485-167, 27m
    ublock-abuse: 75-0, 20m
    ublock-badware: 4146-94, 18m
    ublock-filters: 31353-152, 17m
    ublock-privacy: 214-2, 16m
    ublock-quick-fixes: 219-0, 15m
    ublock-unbreak: 1779-42, 14m
    urlhaus-1: 8292-0, 13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 31267 ms
  maxAssetCacheWait: 1921 ms
popupPanel: 
  blocked: 317
  blockedDetails: 
    youtube.com: 279
    doubleclick.net: 8
    google.com: 17
    google.com.mx: 1
    googlesyndication.com: 2
    googlevideo.com: 9
    ytimg.com: 1
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
