### ISSUE TITLE
gmx.com: ads

### ISSUE THREAD

**Issue by akademsubotnik** [uBlockOrigin/uAssets#13218]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

gmx.com

### Describe the issue

Ads show up on gmx.com

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Chromium -- Version 99.0.4844.74 (Official Build) (64-bit)

### Settings

Default settings

**Comment by mapx-** [comment]
removing "invisible" placeholder

**Comment by mapx-** [comment]
maybe 
`gmx.*###container:style(width:100%!important)`
