### ISSUE TITLE
Buxfer.com

### ISSUE THREAD

**Issue by swiewior** [uBlockOrigin/uAssets#1321]
### URL(s) where the issue occurs

`https://www.buxfer.com/budgets?tags=10185724&periodType=month_current`

### Describe the issue

Could you please block Defender for Buxfer domain? There is no ads and anti-adblock features on this web app. However, when I click for Budget details (eg. `https://www.buxfer.com/budgets?tags=10185724&periodType=month_current`), an error is thrown. With Nano Defender disabled, everything works well. 
I have uBlock Origin disabled for Buxfer domain.
The same happens in last version of Google Chrome.

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/17534342/35183189-29df24a4-fde2-11e7-9d6d-dd00800cd389.png)

### Versions

- Browser/version: Firefox 57.0.4 x64
- uBlock Origin version: 1.14.24

### Settings

- uBlock Origin is disabled for `https://www.buxfer.com`

**Comment by mapx-** [comment]
@jspenguin2017

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/35189762-35111b34-fe0f-11e7-9f84-64d17ce0f93a.png)
![image](https://user-images.githubusercontent.com/7283682/35189765-46038166-fe0f-11e7-9d92-9652f59d48f2.png)

**Comment by swiewior** [comment]
https://drive.google.com/file/d/1LYlkYRepdDXoc3tI4DQBjKjokI_ixwag/view?usp=sharing

I recorded video to demonstrate the issue. Error reproduction starts at 1:50

**Comment by jspenguin2017** [comment]
OK, false positive in BAB defuser, I'll add a whitelist.

**Comment by swiewior** [comment]
Thank you
