### ISSUE TITLE
SourceForge website broken

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#13210]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sourceforge.net/projects/dxwnd/`

### Describe the issue

Website popups won't open when adblock is enabled

### uBlock Origin version

1.42.4

### Browser name and version

Brave 1.38.117 Chromium: 101.0.4951.67 (Official Build) (64-bit)

### Settings

https://user-images.githubusercontent.com/18757054/168335594-e2f51dcd-3e41-4899-81b2-a9385d73ae4b.jpg
https://user-images.githubusercontent.com/18757054/168335597-a34e6715-83ae-4c64-85c8-b1dea8764b96.jpg
https://user-images.githubusercontent.com/18757054/168335598-1907625e-b60d-4e4a-9e26-713b2868ebbd.jpg
https://user-images.githubusercontent.com/18757054/168335599-4552a6dc-9dfa-464a-8819-57999d0c9dfd.jpg

**Comment by mapx-** [comment]
> Website popups won't open when adblock is enabled

Are you talking about downloading process ?

**Comment by GKid94** [comment]
@mapx-  No when you press the Get updates button it won't show the popup

**Comment by mapx-** [comment]
add

```
sourceforge.net#@#.psp_newsletter_subscribe
sourceforge.net#@#.newsletter-subscribe-form:not(html):not(body)
```

FA issue @ryanbr
