### ISSUE TITLE
[nsfw] tnaflix.com: breakage

### ISSUE THREAD

**Issue by the-user1250** [uBlockOrigin/uAssets#13215]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tnaflix.com/`

### Category

breakage

### Describe the issue

All videos are not playing on this website when uBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 155853
  cosmetic: 133624
  scriptlet: 36026
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 2d.2h.40m
    adguard-annoyance: 53016-1710, 1d.1h.54m
    adguard-generic: 63677-1070, 13h.42m
    adguard-mobile: 7723-118, 13h.31m
    adguard-social: 17065-1938, 13h.41m
    adguard-spyware: 26174-1119, 13h.40m
    adguard-spyware-url: 598-13, 13h.39m
    block-lan: 43-0, 19d.13h.49m
    curben-phishing: 13928-0, 5h.55m
    curben-pup: 257-0, 5h.55m
    dpollock-0: 10366-1443, 4d.10h.45m
    fanboy-cookiemonster: 31867-15969, 7d.3h.55m
    fanboy-social: 23369-14155, 13h.36m
    fanboy-thirdparty_social: 69-21, 7d.3h.5m
    ublock-annoyances: 4409-212, 13h.35m
  default: 
    user-filters: 26-0, never
    easylist: 66711-25103, 13h.38m
    easyprivacy: 26964-10384, 13h.37m
    plowe-0: 3676-1479, 5d.11h.30m
    ublock-abuse: 75-0, 6d.1h.7m
    ublock-badware: 4140-300, 13h.34m
    ublock-filters: 31344-3837, 13h.33m
    ublock-privacy: 215-48, 6d.1h.6m
    ublock-quick-fixes: 219-12, 5h.55m
    ublock-unbreak: 1779-96, 13h.32m
    urlhaus-1: 8292-2, 5h.54m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1786 ms (selfie)
  maxAssetCacheWait: 1560 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    tnaflix.com: 6
    shukriya90.com: 1
    stripchat.com: 1
    twinrdsrv.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`tnaflix.com#@#+js(abort-on-property-write, ads)`

@Yuki2718 Adguard bad filter

**Comment by mathiasfabro553-png** [comment]
Hola mi nombre es el Mati
