### ISSUE TITLE
mail.com: detection

### ISSUE THREAD

**Issue by J0eybb** [uBlockOrigin/uAssets#13211]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mail.com/`

### Category

detection

### Describe the issue

Kicks me out stating fair play.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81446
  cosmetic: 43000
  scriptlet: 16850
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66546-51, 4d.3h.23m
    easyprivacy: 26949-121, 4d.3h.22m
    plowe-0: 3678-804, 9d.20h.55m
    ublock-abuse: 75-0, 4d.3h.28m
    ublock-badware: 4165-92, 4d.3h.26m
    ublock-filters: 31101-90, 4d.3h.25m
    ublock-privacy: 216-2, 4d.3h.29m
    ublock-quick-fixes: 229-0, 23h.29m
    ublock-unbreak: 1780-40, 4d.3h.24m
    urlhaus-1: 7913-0, 23h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 32353 ms (selfie)
  maxAssetCacheWait: 773 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    mail.com: 2
    criteo.net: 2
    googleoptimize.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    primis.tech: 1
    taboola.com: 1
    ui-portal.de: 1
    uicdn.com: 1
    united-infos.net: 2
```
</details>

**Comment by mapx-** [comment]
test

```
mail.com##+js(nostif, offsetHeight)
mail.com##.mod-container:has-text(/sponsor/i)
```
