### ISSUE TITLE
levmeddiabetes.no: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#13224]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://levmeddiabetes.no/2017/10/vegansk-hostgryte/`

### Category

ads

### Describe the issue

Have ad on the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-05-14 at 16-38-32 Vegansk høstgryte - Lev med diabetes no](https://user-images.githubusercontent.com/19490515/168430438-b5d4ace8-c441-4c9c-ac0e-7bbdc4eaa28c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 134731
  cosmetic: 160021
  scriptlet: 34580
  html: 658
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24822-3, 1d.17h.54m
    adguard-generic: 63617-4886, 3d.27m
    adguard-spyware: 26164-945, 3d.28m
    adguard-spyware-url: 597-15, 3d.29m
    block-lan: 43-0, 23d.6h.53m
    curben-phishing: 13784-2, 14h.9m
    curben-pup: 257-0, 14h.10m
    adguard-annoyance: 52910-3119, 3d.25m
    adguard-social: 17031-32, 3d.26m
    ublock-annoyances: 4411-6, 3d.24m
    NOR-0: 2731-8, 14h.11m
  default: 
    user-filters: 2-0, never
    ublock-filters: 31898-31, 3d.23m
    ublock-badware: 4144-3, 3d.22m
    ublock-privacy: 217-0, 10d.5h
    ublock-abuse: 75-0, 10d.4h.59m
    ublock-unbreak: 1789-0, 3d.21m
    ublock-quick-fixes: 219-0, 14h.8m
    easylist: 66640-637, 3d.20m
    easyprivacy: 26954-10396, 3d.19m
    urlhaus-1: 8292-0, 14h.7m
    plowe-0: 3678-3, 10d.4h.58m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1627 ms (selfie)
  maxAssetCacheWait: 634 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cookielaw.org: 2
    facebook.net: 1
    googletagmanager.com: 1
    shareaholic.net: 2
```
</details>

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
Frellwit's Swedish Filter seems to have `##a[data-bid="1"][href*="/linkout"]`, which works surprisingly well for this site and can be copied verbatim over to my list. Give me 5min.
