### ISSUE TITLE
bigdatauni.com ads 

### ISSUE THREAD

**Issue by DOSVEN** [uBlockOrigin/uAssets#13221]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hrqsad.gaverathercarry.xyz/dhegaxqc/? .....`

### Category

ads

### Describe the issue

Show unwanted link with a lot of ads when you access: 
`https://bigdatauni.com/tin-tuc/phuong-phap-clustering.html`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-05-14 at 11 16 09 AM](https://user-images.githubusercontent.com/64687854/168410382-731233fb-8f49-432b-9cad-e8e21062e394.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81595
  cosmetic: 43081
  scriptlet: 16862
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 65-2, never
    easylist: 66641-51, 2d.12h.21m
    easyprivacy: 26952-121, 3d.16h.6m
    plowe-0: 3676-804, 1d.9h.1m
    ublock-abuse: 75-0, 3d.10h.20m
    ublock-badware: 4140-93, 2d.12h.20m
    ublock-filters: 31121-94, 3d.16h.5m
    ublock-privacy: 216-2, 4d.11h.11m
    ublock-quick-fixes: 230-0, 20h.47m
    ublock-unbreak: 1778-40, 2d.12h.19m
    urlhaus-1: 8007-0, 20h.48m
filterset (user): [array of 65 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 0
  no-popups: true
```
</details>

**Comment by mapx-** [comment]
@ryanbr advertising platform
`||autoads.asia^$3p`

annoyances:
https://github.com/uBlockOrigin/uAssets/commit/1be24ae9db31fcf5a2c6789f6881a710d52e1845

**Comment by mapx-** [comment]
> Show unwanted link with a lot of ads 

where exactly ?

**Comment by DOSVEN** [comment]
> where exactly ?

When I click on the link: https://bigdatauni.com/tin-tuc/phuong-phap-clustering.html it redirects me to a spam site https://hrqsad.gaverathercarry.xyz/dhegaxqc/... but now after I try again it doesn't show up anymore.

**Comment by Yuki2718** [comment]
@DOSVEN I guess you're redirected when came from search engine.

**Comment by stephenhawk8054** [comment]
> When I click on the link: https://bigdatauni.com/tin-tuc/phuong-phap-clustering.html it redirects me to a spam site https://hrqsad.gaverathercarry.xyz/dhegaxqc/... but now after I try again it doesn't show up anymore.

Which URL that had `bigdatauni.com` link and you clicked on?

**Comment by DOSVEN** [comment]
> @DOSVEN I guess you're redirected when came from search engine.

@Yuki2718  Yes, Exactly
