### ISSUE TITLE
open3dmodel.com: detection

### ISSUE THREAD

**Issue by Triangulix** [uBlockOrigin/uAssets#13220]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open3dmodel.com/3d-models/3d-model-full-male-body_47125.html`

### Category

detection

### Describe the issue

The blocking layer can easily be removed but we also need to remove the added classes from the body tag

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 83830
  cosmetic: 46681
  scriptlet: 16974
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    DEU-0: 5745-0, 15h
    easylist: 66711-57, 19h.3m
    easyprivacy: 26964-132, 19h.1m
    plowe-0: 3676-805, 2d.23h.15m
    ublock-abuse: 75-0, 23h.6m
    ublock-badware: 4146-94, 19h.2m
    ublock-filters: 31325-107, 19h.5m
    ublock-privacy: 214-2, 23h.7m
    ublock-quick-fixes: 230-0, 14h.58m
    ublock-unbreak: 1781-43, 19h.4m
    urlhaus-1: 8007-0, 14h.59m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 869 ms (selfie)
  maxAssetCacheWait: 245 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
@mapx- 
This problem is difficult to reproduce, but sometimes it is still observed. 

[Fix in RU AdList](https://github.com/easylist/ruadlist/commit/1e2aeba60fdc8a1a9bb2569ee0c78ba1374d076e#diff-13eb320f99a3b77245d49dd692219a98f00daaf6978b582d576d546ed1e70071R219)

**Comment by mapx-** [comment]
so, I guess it's good enough:

```
open3dmodel.com##+js(aopr, mdp_deblocker)
open3dmodel.com##[style]:has(.adsbygoogle)
```

**Comment by dimisa-RUAdList** [comment]
I thought that this problem is specific to users with a russian ip, so I put the scriptlet in the regional list. Since it is now present in uBlock filters, I remove it: https://github.com/easylist/ruadlist/commit/ec205d3bc8833cd66ec678bc031641187a7dd40c

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=open3dmodel.com`
~ this exception is only needed for users ABP/AB.

**Comment by Triangulix** [comment]
It seems fine now. Thanks :-)
