### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by odellus** [uBlockOrigin/uAssets#13227]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/gp/video/detail/B07QGX74TH/ref=atv_3p_fre_c_O2hWln_brws_4_4`

### Category

ads

### Describe the issue

It's letting through all the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81198
  cosmetic: 43101
  scriptlet: 16945
  html: 653
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 31945-32, 20m
    ublock-badware: 4131-3, 20m
    ublock-privacy: 220-0, 20m
    ublock-abuse: 75-0, 20m
    ublock-unbreak: 1791-0, 20m
    easylist: 66748-596, 20m
    easyprivacy: 26970-577, 20m
    urlhaus-1: 7489-0, 20m
    plowe-0: 3672-3, 20m
    ublock-quick-fixes: 225-0, 20m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 669 ms
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 154
  blockedDetails: 
    amazon.com: 150
    aiv-cdn.net: 3
    amazon-adsystem.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/13166

**Comment by odellus** [comment]
The issue persists
https://github.com/uBlockOrigin/uAssets/issues/13166#issuecomment-1133888979
