### ISSUE TITLE
hootsuite.com: breakage / (CNAME) blocking for `postclickmarketing.com` breaks various sites

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#13222]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hootsuite.com/resources/digital-trends`

### Category

breakage

### Describe the issue

@ryanbr

`||postclickmarketing.com^$third-party` is a long-lived filter initially introduced to fanboy's list https://github.com/ryanbr/fanboy-adblock/commit/27cd6d0 in 2011 and later merged into EP.
Indeed this domain is used by a certain type of marketing tool, [Rock Content's Ion](https://rockcontent.com/products/ion/)<sup>1</sup>. However, in my observation, there are no examples of it being blocked without major breakage.

I would suggest removing it from the block list.

#### Other websites with  breakage

- With and Without CNAME uncloaking
~~~
https://www.demandmetric.com
~~~

- With CNAME uncloaking (found by @Yuki2718)
~~~
http://www.systemsprotect.com/
https://www.adtspecials.com/
https://www.cursodemedicina.com.br/
https://www.semipresencial.com.br/
https://www.befinanciallyfit.com/
~~~

---

<sub>

1:  `https://help.rockcontent.com/en/pointing-subdomains-toward-your-ion-console-part-1`
> When your ion console is initially set up, it will have a dedicated subdomain such as: `http://yourcompany.postclickmarketing.com`

</sub>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

#### Default filter lists
![Screenshot1](https://user-images.githubusercontent.com/82331005/168419846-82546a72-cacf-417e-831e-5268a001eec1.png)
#### Default filter lists + `||postclickmarketing.com^$3p,badfilter`
![Screenshot2](https://user-images.githubusercontent.com/82331005/168419856-d580e505-040d-4e8e-bd95-31a1eaae1772.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81988
  cosmetic: 43093
  scriptlet: 16944
  html: 652
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31945-32, now
    ublock-badware: 4149-3, now
    ublock-privacy: 220-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1790-0, now
    ublock-quick-fixes: 222-0, now
    easylist: 66739-596, now
    easyprivacy: 26968-577, now
    urlhaus-1: 8268-0, now
    plowe-0: 3672-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms
  maxAssetCacheWait: 110 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    evgnet.com: 2
    googletagmanager.com: 1
    newrelic.com: 1
    optimizely.com: 2
    postclickmarketing.com: 1
```
</details>

**Comment by ryanbr** [comment]
"Major Breakage" I don't see. https://www.demandmetric.com/ blocking `https://demandmetric.postclickmarketing.com/home-page-vsl?_ion_target=embed-1.0` still looks fine and acceptable. I see no reason for any sudden changes on our part.

**Comment by hirorpt** [comment]
I would consider the page major breakages if a large portion of the page does not show up, even if it is not important to you.
Well fine, I'll go with your opinion.

I went to `https://www.hootsuite.com/resources/digital-trends` to access the material on ad blocker usage statistics, but the material did not show up at all. This is due to CNAME blocking against `postclickmarketing.com`. This would indeed be considered a major breakage for you, wouldn't it?

**Comment by Yuki2718** [comment]
@ryanbr It's not CNAME uncloak that's causing problems - if not uncloaked, not blocked in the first place. Whereever postclickmarketing is blocked, there is breakage more or less. You'll see some images are blocked even without uncloak on `https://www.adtspecials.com/` and `http://www.systemsprotect.com/`. Maybe `$~image` is one solution - but these are literally all the sites still using postclickmarketing found on [publicwww](https://publicwww.com/websites/%22postclickmarketing.com%22/). Maybe something has changed in this decade.
