### ISSUE TITLE
[nsfw] bt-tt.com: ads

### ISSUE THREAD

**Issue by d121346630** [uBlockOrigin/uAssets#13226]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bt-tt.com/`

### Category

ads

### Describe the issue

the sex ad on the right down corner can't be hidden after several times trying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 80943
  cosmetic: 42179
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 65018-51, never
    easyprivacy: 26734-121, never
    plowe-0: 3690-811, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-85, never
    ublock-filters: 30477-97, never
    ublock-privacy: 205-1, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-41, never
    urlhaus-1: 8896-0, never
filterset (user): [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1140 ms
  maxAssetCacheWait: 23 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    baidu.com: 2
    cloudflareinsights.com: 1
```
</details>

**Comment by mapx-** [comment]
It's a chinese site, just enable `CHN: AdGuard Chinese`

**Comment by d121346630** [comment]
So I need another Chrome extension for that? I already have AdGurad English

**Comment by mapx-** [comment]
Enable the chinese list in uBO 

![image](https://user-images.githubusercontent.com/10303732/168458261-70a601a1-d494-4197-991a-3a1069cc5e22.png)

**Comment by d121346630** [comment]
Thank you. It works!
