### ISSUE TITLE
10fastfingers.com: ads

### ISSUE THREAD

**Issue by DoronLGN** [uBlockOrigin/uAssets#13229]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://10fastfingers.com/typing-test/english`

### Category

ads

### Describe the issue

A video ad pops up at the bottom right. I attempted to block it with the element picker, but that didn't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 80975
  cosmetic: 42932
  scriptlet: 16836
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 66621-51, 3d.15h.41m
    easyprivacy: 26952-121, 3d.15h.40m
    plowe-0: 3676-804, 1d.12h.7m
    ublock-abuse: 75-0, 7d.14h.10m
    ublock-badware: 4170-94, 3d.15h.38m
    ublock-filters: 31124-92, 3d.15h.37m
    ublock-privacy: 215-2, 7d.18h.16m
    ublock-unbreak: 1778-40, 3d.15h.36m
    urlhaus-1: 7489-0, 6h.8m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1734 ms (selfie)
  maxAssetCacheWait: 192 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    10fastfingers.com: 26
    amazon-adsystem.com: 1
    connatix.com: 1
    doubleclick.net: 1
    ezodn.com: 1
    fouanalytics.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    imasdk.googleapis.com: 1
    quantserve.com: 1
```
</details>

**Comment by v-ns** [comment]
Try:
`10fastfingers.com###ez-video-wrap-ece92d46f80559e5b70d44e19a3314295a676902
`

**Comment by DoronLGN** [comment]
That appears to fix it. Thank you!
