### ISSUE TITLE
news.discuss.com.hk: detection

### ISSUE THREAD

**Issue by hr8473** [uBlockOrigin/uAssets#13223]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://news.discuss.com.hk/viewthread.php?tid=30576063&extra=page%3D1%26amp%3BthreadMode%3Dneutral&tr_h=1182026334627f883f235554_42882893`

### Category

detection

### Describe the issue

It detects uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/105545048/168422622-6be68c2d-14bd-4f07-add0-54db1aa051d4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 101867
  cosmetic: 82121
  scriptlet: 18444
  html: 652
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 1m
    fanboy-cookiemonster: 31925-70, 1m
    CHN-0: 28669-95, 2m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31937-58, 2m
    ublock-badware: 4131-3, 2m
    ublock-privacy: 220-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1790-0, 2m
    ublock-quick-fixes: 225-0, 2m
    easylist: 66746-618, 2m
    easyprivacy: 26970-605, 2m
    urlhaus-1: 8268-0, 2m
    plowe-0: 3672-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1190 ms
  maxAssetCacheWait: 261 ms
popupPanel: 
  blocked: 57
  blockedDetails: 
    discuss.com.hk: 11
    aaxads.com: 1
    aaxdetect.com: 1
    ads-twitter.com: 2
    amazon-adsystem.com: 1
    anymind360.com: 2
    cloudflare.com: 2
    criteo.com: 1
    criteo.net: 5
    doubleclick.net: 2
    facebook.net: 2
    googleadservices.com: 2
    googlesyndication.com: 1
    impactradius-go.com: 2
    indexww.com: 2
    n2.hk: 4
    navdmp.com: 1
    price.com.hk: 8
    scorecardresearch.com: 1
    sjv.io: 2
    skimresources.com: 2
    vidoomy.com: 2
```
</details>

**Comment by Yuki2718** [comment]
@mapx- It seems this is dismissable by top-right X.

**Comment by mapx-** [comment]
I tested it: close X, ctrl-f5 still nothing, f5, another ctrl-f5 => appears again

**Comment by Yuki2718** [comment]
Yeah, you're right. So this is the same case as in re-appearing admiral once dicussed.

**Comment by hr8473** [comment]
Hi,

Is it possible to include the fix for the entire domain of **discuss.com.hk**? 

The same ad-detection appears on this example too.
https://www.discuss.com.hk/viewthread.php?tid=30576129&extra=page%3D1&tr_h=1217201959627fd24db8d971_36913288

![image](https://user-images.githubusercontent.com/105545048/168439692-14ea768e-4ab5-4e9b-9563-de11d042d411.png)

**Comment by Yuki2718** [comment]
@hr8473 Done.

**Comment by hr8473** [comment]
> @hr8473 Done.

Thanks. It works like a charm.
