### ISSUE TITLE
[nsfw] https-xvideos.com: nuisance

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#13230]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://https-xvideos.com/`

### Category

nuisance

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/98657967/168454648-df8b957b-c97b-4733-80d6-ed52ec4510e7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 73871
  cosmetic: 49067
  scriptlet: 17748
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6381-1, 1d.16h.35m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 3410-11, 1d.16h.34m
  default: 
    user-filters: 8-0, never
    easylist: 66711-67, 1d.16h.37m
    easyprivacy: 26966-121, 1d.16h.36m
    ublock-abuse: 75-0, 1d.16h.33m
    ublock-badware: 4146-92, 1d.16h.32m
    ublock-filters: 31346-162, 1d.16h.30m
    ublock-privacy: 216-3, 1d.16h.29m
    ublock-quick-fixes: 230-0, 29m
    ublock-unbreak: 1779-41, 1d.16h.27m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1910 ms (selfie)
  maxAssetCacheWait: 418 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    budvawshes.ru: 1
    tick-tock.net: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr @dimisa-RUAdList `https://mainad-codpp.com/bens/vinos8.js`

**Comment by Yuki2718** [comment]
@@dimisa-RUAdList I missed at the first look but `https-xvideos.com##+js(nowoif)` is still needed for popup on playing video e.g. `https://https-xvideos.com/russian/1623604123.html`.

**Comment by dimisa-RUAdList** [comment]
@Yuki2718 
As far as I understand, this site is a fake, copying the popular portal `xvideos.com`. In addition, it is not known how long this fake will last before migrating to another address. It seems to me that we should not add rules attached to such sites if it is possible to solve the problem with a general rule. RU AdList contains a rule for this: `||popadon.com^$popup`

**Comment by Yuki2718** [comment]
@dimisa-RUAdList Okay, sure that rule should mitigate the issue.
