### ISSUE TITLE
haipedia.com: detection

### ISSUE THREAD

**Issue by hagiwarauchiha** [uBlockOrigin/uAssets#13238]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.haipedia.com/stocks-mutualfunds-157`

### Category

detection

### Describe the issue

original link: 
`https://apk.miuiku.com/7vFIKrpHab`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/105593173/168475215-4f66ed89-195e-448f-8abf-26965d459a50.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 87545
  cosmetic: 104408
  scriptlet: 19391
  html: 652
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53029-1469, 2d.14h.18m
    adguard-social: 17065-32, 2d.14h.18m
    fanboy-thirdparty_social: 69-3, 2d.14h.18m
  default: 
    user-filters: 4-1, never
    ublock-filters: 31946-29, 2d.14h.18m
    ublock-badware: 4150-3, 2d.14h.18m
    ublock-privacy: 220-0, 2d.14h.18m
    ublock-abuse: 75-0, 2d.14h.18m
    ublock-unbreak: 1790-0, 2d.14h.18m
    ublock-quick-fixes: 225-1, 1m
    easylist: 66686-597, 2d.14h.18m
    easyprivacy: 26964-579, 2d.14h.18m
    urlhaus-1: 8974-0, 1m
    plowe-0: 3676-3, 2d.14h.18m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 504 ms (selfie)
  maxAssetCacheWait: 821 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    googlesyndication.com: 8
    histats.com: 1
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce an anti adb issue
I addressed an issue (cannot open the final download link) and popups:

https://github.com/uBlockOrigin/uAssets/commit/38002a63b8e6423b7c3681d63d2e99c18f7d9195

**Comment by okiehsch** [comment]
I can only reproduce the screenshot if I disable `uBO-filters` or if I  add 
````
sekilastekno.com#@#+js(no-fetch-if, ads)
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,redirect-rule=googlesyndication_adsbygoogle.js:5
````
to my filter list.
