### ISSUE TITLE
telia.no: breakage

### ISSUE THREAD

**Issue by Eddorgus** [uBlockOrigin/uAssets#13231]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.telia.no/kundeservice/kontakt-oss/`

### Category

breakage

### Describe the issue

This is a support page where you're supposed to get a chat in the bottom right corner, either automatically or by clicking the "kontakt oss" or "Chat with otelia". When in incognito or turning off ublock it works again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82793
  cosmetic: 44976
  scriptlet: 17017
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NOR-0: 2734-5, 18h.51m
    easylist: 66738-52, 1d.12h.31m
    easyprivacy: 26966-122, 1d.12h.30m
    plowe-0: 3672-804, 1d.4h.24m
    ublock-abuse: 75-0, 1d.12h.29m
    ublock-badware: 4146-95, 1d.12h.28m
    ublock-filters: 31349-98, 1d.12h.27m
    ublock-privacy: 216-4, 1d.12h.26m
    ublock-quick-fixes: 222-0, 18h.50m
    ublock-unbreak: 1779-41, 14h.48m
    urlhaus-1: 8268-0, 18h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    telia.no: 4
    blueconic.net: 1
    hotjar.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||cat.telia.no/gtm.js$script,domain=telia.no`

@ryanbr
