### ISSUE TITLE
timesprime.com: breakage

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#13233]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.timesprime.com/categories`

### Category

breakage

### Describe the issue

Not loading offers when uBlockOrigin enabled.

### Screenshot(s)

![Screenshot 2022-05-15 at 13-40-05 Times Prime Membership Offers on Food Travel Entertainment News Healthcare Fashion   Lifestyle etc](https://user-images.githubusercontent.com/19629778/168463464-436e1e07-cb87-473b-ba6b-bd009fd66006.png)

![Screenshot 2022-05-15 at 13-38-53 Times Prime Membership Offers on Food Travel Entertainment News Healthcare Fashion   Lifestyle etc](https://user-images.githubusercontent.com/19629778/168463471-31d424db-485c-4d5b-9941-632133402b97.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82358
  cosmetic: 43084
  scriptlet: 16922
  html: 651
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 31890-29, 2d.18h.37m
    ublock-badware: 4149-3, 2d.18h.36m
    ublock-privacy: 222-0, 2d.18h.35m
    ublock-abuse: 75-0, 2d.18h.34m
    ublock-unbreak: 1790-0, 2d.18h.33m
    ublock-quick-fixes: 222-0, 2h.56m
    easylist: 66681-594, 2d.18h.30m
    easyprivacy: 26960-577, 2d.18h.29m
    urlhaus-1: 8707-0, 2h.55m
    plowe-0: 3676-3, 2d.18h.27m
filterset (user): [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 258 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    artfut.com: 1
    d2r1yp2w7bby2u.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    sentry-cdn.com: 1
```
</details>

**Comment by ghajini** [comment]
@ryanbr 

`||sentry-cdn.com^$3p,domain=~sentry.dev|~sentry.io|~timesprime.com`

**Comment by tillcash** [comment]
> 

It works after adding the filter.

**Comment by okiehsch** [comment]
> Not working.

You have to add
````
||sentry-cdn.com^$third-party,badfilter,domain=~sentry.dev|~sentry.io
||sentry-cdn.com^$3p,domain=~sentry.dev|~sentry.io|~timesprime.com
````
until it's fixed in `EasyPrivacy`

**Comment by tillcash** [comment]
> > Not working.
> 
> You have to add
> 
> ```
> ||sentry-cdn.com^$third-party,badfilter,domain=~sentry.dev|~sentry.io
> ||sentry-cdn.com^$3p,domain=~sentry.dev|~sentry.io|~timesprime.com
> ```
> 
> until it's fixed in `EasyPrivacy`

Thanks.
