### ISSUE TITLE
ddxs.cc: ads

### ISSUE THREAD

**Issue by wunaier** [uBlockOrigin/uAssets#13243]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.ddxs.cc/ddxs/806/466691.html`

### Category

ads

### Describe the issue

Recently, I have often encountered similar webpages. There is an advertisement video at the top, and when I slide to the end of the page, the advertisement video appears at the bottom, but it cannot be removed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 102149
  cosmetic: 34059
  scriptlet: 17128
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 23-0, never
    CHN-0: 28677-1157, 1d.1h.41m
    adguard-mobile: 7729-55, 1d.1h.37m
    easylist: 66749-24182, 1d.1h.40m
    easyprivacy: 26974-156, 1d.1h.39m
    plowe-0: 3676-893, 2d.18h.38m
    ublock-abuse: 75-0, 3d.13h.10m
    ublock-badware: 4145-94, 1d.1h.35m
    ublock-filters: 31457-355, 1d.1h.38m
    ublock-privacy: 216-5, 3d.13h.12m
    ublock-quick-fixes: 226-4, 19h.14m
    ublock-unbreak: 1785-44, 1d.1h.36m
    urlhaus-1: 8707-0, 19h.15m
filterset (user): [array of 23 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  largeMediaSize: 30
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 420 ms (selfie)
  maxAssetCacheWait: 146 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
it's down or geo-restricted

![image](https://user-images.githubusercontent.com/10303732/168525236-a18c97ec-d1e0-4c85-8b65-1ee79e4a8ca0.png)

![image](https://user-images.githubusercontent.com/10303732/168525268-5a6d81af-63bc-40c5-bf5e-2839bc63b191.png)
