### ISSUE TITLE
fox40.com: breakage

### ISSUE THREAD

**Issue by craigmaloney** [uBlockOrigin/uAssets#13248]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fox40.com/weather/forecast/`

### Category

breakage

### Describe the issue

None of the videos load (all show broken links / empty spaces). Not sure which filter is breaking this site in particular, but when disabling uBlock Origin it displays pictures / video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![KTXL](https://user-images.githubusercontent.com/527251/168598674-4e2590d1-2a05-4084-85cd-f50fb58977af.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82713
  cosmetic: 43116
  scriptlet: 16985
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 2-0, never
    easylist: 66767-51, 27m
    easyprivacy: 26976-121, 26m
    plowe-0: 3676-804, 7d.5m
    ublock-abuse: 75-0, 1d.13h.52m
    ublock-badware: 4128-94, 25m
    ublock-filters: 31357-97, 24m
    ublock-privacy: 214-2, 1d.13h.51m
    ublock-quick-fixes: 225-3, 22m
    ublock-unbreak: 1780-41, 23m
    urlhaus-1: 8985-0, 21m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3956 ms (selfie)
  maxAssetCacheWait: 774 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    fox40.com: 1
    aaxads.com: 1
    addthis.com: 1
    amazon-adsystem.com: 1
    chartbeat.com: 2
    confiant-integrations.global.ssl.fastly.net: 1
    d15kdpgjg3unno.cloudfront.net: 1
    d3plfjw9uod7ab.cloudfront.net: 1
    dmpxs.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    nexstardigital.net: 1
    nxstrib.com: 1
    onesignal.com: 1
    permutive.app: 1
    rlcdn.com: 1
    sail-horizon.com: 1
    segment.com: 1
    wp.com: 1
```
</details>

**Comment by craigmaloney** [comment]
Was this "unable to reproduce" as in you got video stills, or unable to reproduce as in it's geo-locked for your location?

Thanks!

**Comment by mapx-** [comment]
I get the video playing after some delay (6-7 seconds) - using a vpn us ip
