### ISSUE TITLE
nung-sub.com: ads

### ISSUE THREAD

**Issue by NelloZ133** [uBlockOrigin/uAssets#13245]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nung-sub.com/`

### Category

ads

### Describe the issue

too many ads still there
have pop up & banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/90823087/168542629-ff6619e6-2391-41c3-a205-7f67a9bc582b.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82686
  cosmetic: 43090
  scriptlet: 16984
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 18h.5m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 20-6, never
    easylist: 66711-51, 2d.17h.7m
    easyprivacy: 26966-121, 2d.17h.6m
    plowe-0: 3676-804, 4d.20h.58m
    ublock-abuse: 75-0, 9d.6h.44m
    ublock-badware: 4146-94, 2d.17h.9m
    ublock-filters: 31340-96, 2d.17h.5m
    ublock-privacy: 215-4, 9d.6h.45m
    ublock-quick-fixes: 222-0, 7h.1m
    ublock-unbreak: 1779-41, 2d.17h.8m
    urlhaus-1: 8985-0, 7h
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 307 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    nung-sub.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
I get no popups but for the ad images `||nung-sub.com/images/banners/` is enough

**Comment by JobcenterTycoon** [comment]
@gluons

**Comment by NelloZ133** [comment]
Thank you for your help

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
