### ISSUE TITLE
bbc.com: detection

### ISSUE THREAD

**Issue by JJRobertsSex30** [uBlockOrigin/uAssets#13242]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bbc.com/news`

### Category

detection

### Describe the issue

overlay at the bottom of the screen

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81884
  cosmetic: 43088
  scriptlet: 16945
  html: 653
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 31944-93, 21h.28m
    ublock-badware: 4149-3, 21h.27m
    ublock-privacy: 220-0, 1d.15h.5m
    ublock-abuse: 75-0, 1d.14h.58m
    ublock-unbreak: 1793-0, 4d.20h.30m
    easylist: 66621-515, 4d.20h.29m
    easyprivacy: 26952-590, 4d.20h.28m
    urlhaus-1: 8268-0, 1d.14h.56m
    plowe-0: 3678-3, 11d.15h.3m
    ublock-quick-fixes: 230-0, 1d.14h.57m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6031 ms
  maxAssetCacheWait: 2428 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adsafeprotected.com: 1
    bbci.co.uk: 2
    chartbeat.com: 1
    dotmetrics.net: 1
    doubleclick.net: 1
    europe-west1-bbc-otg-traf-mgr-bq-prod-4591.cloudfunctions.net: 1
    google.com: 1
    permutive.com: 1
```
</details>

**Comment by mapx-** [comment]
screenshot ?

**Comment by mapx-** [comment]
PH right side

`bbc.com###sticky-mpu:has(.dotcom-ad-inner)`

@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/dc7467d5774579a47f463dbe5969aadcf908b132
