### ISSUE TITLE
gamegtx.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1325]
URL(s) where the issue occurs

`https://www.gamegtx.com/forums/Netflix/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
maybe you need to log in ? yes ? ==> provide test account

**Comment by KiLL4FuNK** [comment]
visiting the main page, see the message

`https://gamegtx.com/`

**Comment by mapx-** [comment]
only in chrome
