### ISSUE TITLE
shahed4u.click new-tab ad

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#13251]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://shahed4u.click`

### Describe the issue

Open a new-tab ad with the first click then opens again once every a while.

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Google Chrome Version 101.0.4951.54 (Official Build) (64-bit)

### Settings

- unchecked "Show the number of blocked requests on the icon"

**Comment by okiehsch** [comment]
Try updating the filter lists.

**Comment by ghajini** [comment]
Its a race condition in chrome, i can reproduce

In firefox a, i can consistently reproduce 

`shahed4u.*##^script:has-text(break;case $.)`

**Comment by ghajini** [comment]
@Iaycomand 

try
`shahed4u.click##+js(aopr, parseFloat)`

**Comment by Iaycomand** [comment]
Issue is no longer occur, didn't have to add the filter
