### ISSUE TITLE
vandaaginside.nl: detection

### ISSUE THREAD

**Issue by DaveJ86** [uBlockOrigin/uAssets#13260]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vandaaginside.nl/nieuws/vandaag-inside/johan-derksen-reageert-op-stoppen-vandaag-inside-na-kaars-anekdote`

### Category

detection

### Describe the issue

Watching the video is blocked unless you deactivate uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 207386
  cosmetic: 220473
  scriptlet: 27135
  html: 0
listset (total-discarded, last updated): 
  added: 
    ALB-0: 272-5, never
    BGR-0: 1116-15, never
    CHN-0: 28660-198, never
    CZE-0: 710-10, never
    DEU-0: 5754-33, never
    EST-0: 0-0, never
    FIN-0: 1754-6, never
    FRA-0: 27646-872, never
    GRC-0: 1002-5, never
    HUN-0: 2158-59, never
    IDN-0: 8998-42, never
    IND-0: 10553-6, never
    IRN-0: 1340-18, never
    ISL-0: 193-3, never
    ISR-0: 1622-5, never
    ITA-0: 12999-85, never
    JPN-1: 6982-150, never
    KOR-1: 1645-76, never
    LTU-0: 1198-7, never
    LVA-0: 395-3, never
    [21 lists not shown]: [too many]
  default: 
    user-filters: 2-0, never
    NLD-0: 2241-11, 9m
    easylist: 66836-130, 9m
    easyprivacy: 26976-10651, 9m
    plowe-0: 3673-867, 8m
    ublock-abuse: 75-0, 8m
    ublock-badware: 4128-94, 8m
    ublock-filters: 31373-493, 8m
    ublock-privacy: 214-40, 8m
    ublock-quick-fixes: 228-6, 8m
    ublock-unbreak: 1780-74, 8m
    urlhaus-1: 8921-2, 8m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 633 ms (selfie)
  maxAssetCacheWait: 498 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    kijk.nl: 3
    privacymanager.io: 1
    talpanetwork.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||kijk.nl^$xhr,1p`

@JohnyP36

**Comment by Luukth** [comment]
Watching the video is blocked unless you deactivate uBlock. The same URL as used by the original poster of this issue can be used to check.

**Comment by Luukth** [comment]
Watching the video is blocked unless you deactivate uBlock. The same URL as used by the original poster of this issue can be used to check.
https://github.com/user-attachments/assets/9f2d8281-cb54-4cfc-b2e4-39e12fbf106c

**Comment by RickEagles** [comment]
The problem is back again: the video does not play when uBO Lite is enabled.

**Comment by stephenhawk8054** [comment]
Share your uBOL troubleshooting information to here while reproducing the issue.
