### ISSUE TITLE
won.pe [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1326]
URL(s) where the issue occurs

`https://won.pe/4tmwH`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by BottledSoda** [comment]
inactive?
