### ISSUE TITLE
apkmagic.com.ar: detection

### ISSUE THREAD

**Issue by DarealBingoxz** [uBlockOrigin/uAssets#13267]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://apkmagic.com.ar/dead-trigger-2-mod-apk-v1-8-15-endless-ammo/`

### Category

detection

### Describe the issue

Ublock Origin is being detected, and mentioned site also gives a popup if you disable javascript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82790
  cosmetic: 43092
  scriptlet: 16987
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-1, never
    easylist: 66711-51, 4d.35m
    easyprivacy: 26964-121, 4d.34m
    plowe-0: 3679-804, 12d.18h.30m
    ublock-abuse: 75-0, 13h.41m
    ublock-badware: 4146-94, 4d.33m
    ublock-filters: 31344-96, 4d.32m
    ublock-privacy: 214-2, 13h.40m
    ublock-quick-fixes: 228-1, 1h.55m
    ublock-unbreak: 1779-41, 4d.31m
    urlhaus-1: 9092-0, 1h.54m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1113 ms (selfie)
  maxAssetCacheWait: 390 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    apkmagic.com.ar: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    wp.com: 1
```
</details>

**Comment by ghajini** [comment]
force update filter lists
