### ISSUE TITLE
ads.finance breaks

### ISSUE THREAD

**Issue by JuanMZC** [uBlockOrigin/uAssets#13268]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ads.finance/`

### Describe the issue

The `https://ads.finance/` doesn't load correctly as some content is blocked due to uBlock.
Anti-advertising rules break the display of the site. It seems it now blocks any content when the path starts with `https://ads.`

### uBlock Origin version

Latest

### Browser name and version

Latest Chrome version

### Settings

None

**Comment by mapx-** [comment]
EL breakage @ryanbr
