### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Gladiatorg** [uBlockOrigin/uAssets#13263]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

when i went to go to the video it started with an ad i thought i click the wrong video but no its an ad

### Screenshot(s)

![2022-05-16](https://user-images.githubusercontent.com/93134690/168726923-fcacca7a-d7c4-47f2-b968-8279cdbb11c5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82789
  cosmetic: 43133
  scriptlet: 16993
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    easylist: 66836-51, 59m
    easyprivacy: 26976-121, 1d.1h.16m
    plowe-0: 3676-804, 7d.23h.49m
    ublock-abuse: 75-0, 6d.7h.16m
    ublock-badware: 4145-94, 3d.7h.49m
    ublock-filters: 31369-99, 6h.17m
    ublock-privacy: 216-4, 6d.7h.17m
    ublock-quick-fixes: 225-3, 17h.15m
    ublock-unbreak: 1779-41, 2d.22h.53m
    urlhaus-1: 8985-0, 17h.14m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 24846 ms (selfie)
  maxAssetCacheWait: 963 ms
popupPanel: 
  blocked: 47
  blockedDetails: 
    youtube.com: 40
    google.com: 2
    googleadservices.com: 1
    googlesyndication.com: 2
    googlevideo.com: 2
```
</details>

**Comment by mapx-** [comment]
follow the indications here:
https://github.com/easylist/easylist/wiki/Youtube-Issues


duplicate: https://github.com/uBlockOrigin/uAssets/issues/7636
