### ISSUE TITLE
cairn.info: ads

### ISSUE THREAD

**Issue by leeuwerck** [uBlockOrigin/uAssets#13275]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cairn.info/revue-bulletin-de-psychologie-2012-2-page-149.htm`

### Category

ads

### Describe the issue

At the ninth paragraph paragraph, an ad for CAIRN PRO is visible in the form of a .png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 100644
  cosmetic: 52232
  scriptlet: 17014
  html: 653
listset (total-discarded, last updated): 
  added: 
    FRA-0: 27646-40, 19h.45m
  default: 
    user-filters: 78-0, never
    ublock-filters: 31972-173, 19h.43m
    ublock-badware: 4149-3, 19h.42m
    ublock-privacy: 220-0, 19h.48m
    ublock-abuse: 75-0, 19h.47m
    ublock-unbreak: 1791-0, 7h.9m
    easylist: 66849-890, 6h.46m
    easyprivacy: 26976-892, 19h.44m
    plowe-0: 3676-3, 6d.6h.46m
    urlhaus-1: 9092-0, 6h.45m
    ublock-quick-fixes: 228-0, 6h.44m
filterset (user): [array of 78 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1148 ms (selfie)
  maxAssetCacheWait: 637 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    addthis.com: 1
    datadome.co: 2
    en25.com: 1
    oracleinfinity.io: 2
```
</details>

**Comment by leeuwerck** [comment]
@JobcenterTycoon Thanks, indeed that’s what I did. How can this information be contributed to lists that are used in uBlockOrigin to the benefit of all users?

**Comment by okiehsch** [comment]
Self advertisement will generally not be fixed in most filter list.

You can ask the regional french list if they will add the filter but I doubt it.
https://github.com/AdguardTeam/AdguardFilters
