### ISSUE TITLE
japantimes.co.jp nuisance

### ISSUE THREAD

**Issue by soleurs** [uBlockOrigin/uAssets#13271]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.japantimes.co.jp`

### Describe the issue

Setting aside paywall issues which are out of scope, all articles are now unreadable entirely beyond the first two paragraphs without disabling uBlock. Sometimes the article abruptly ends, sometimes it is requested to whitelist japantimes.co.jp and piano.io to read anything
<img width="833" alt="Screen Shot 2022-05-17 at 6 02 06 pm" src="https://user-images.githubusercontent.com/24378229/168773470-fb86cfc7-69cb-4834-a4ed-b60d397178bb.png">
.

### uBlock Origin version

1.42.4

### Browser name and version

Mozilla Firefox 100.0

### Settings

- Blocked piano.io previously to end old adblock blocker behavior.

**Comment by okiehsch** [comment]
I am guessing an account is needed to reproduce?

**Comment by soleurs** [comment]
Not needed, I use the site without an account

**Comment by okiehsch** [comment]
All I see is
![image](https://user-images.githubusercontent.com/16838044/168778869-fe5be652-92a4-40d5-a533-233a0ba331ec.png)

**Comment by mapx-** [comment]
@okiehsch on simple refreshing the page it's all ok, if bypass cache (ctrl-f5) I get "unable to view", it seems a 3-rd party script has to be whitelisted

**Comment by okiehsch** [comment]
>  if bypass cache

Would be interesting to know if one can read the article if you register,if yes then no fix is needed imo, i.e. why allow a third-party script if nothing is broken.

I can only reproduce using Firefox.

**Comment by mapx-** [comment]
yes, it seems to be a site issue, even whitelisting all third-party scripts I get sometimes that issue - in firefox

**Comment by Yuki2718** [comment]
> > if bypass cache
> 
> Would be interesting to know if one can read the article if you register, if yes then no fix is needed imo, i.e. why allow a third-party script if nothing is broken. You can't read the article anyway unless you register even if you disable uBO.

Yes, you can read full article with free acount but I still get "unable to view" by ctrl + F5 with logged in. I found `||japantimes.co.jp/wp-content/themes/jt_theme/library/css/piano.css` works fine and so far don't see breakage so will add this.
