### ISSUE TITLE
zetfliks.vip: nuisance

### ISSUE THREAD

**Issue by cyxoqprykt** [uBlockOrigin/uAssets#13279]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zetfliks.vip/podborka/pro-katastrofy/4191-halo-43.html`

### Category

nuisance

### Describe the issue

When trying to play a video, commercials were shown at the beginning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 82494
  cosmetic: 43136
  scriptlet: 16979
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 52-2, never
    easylist: 66746-51, 3d.10h.17m
    easyprivacy: 26970-121, 3d.10h.16m
    plowe-0: 3677-804, 6d.54m
    ublock-abuse: 75-0, 6d.53m
    ublock-badware: 4145-94, 3d.10h.15m
    ublock-filters: 31337-96, 3d.10h.14m
    ublock-privacy: 216-4, 6d.52m
    ublock-quick-fixes: 222-1, 55m
    ublock-unbreak: 1780-41, 3d.2h.20m
    urlhaus-1: 8762-0, 54m
filterset (user): [array of 52 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 188 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 6
  no-scripting: true
  blockedDetails: 
    adfox.ru: 2
    imasdk.googleapis.com: 1
    pjstat.com: 2
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
I get no video ad, however it's a russian site you should enable `RUS: RU AdList`

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@mapx- 
That's right, RU AdList blocks ads there.
