### ISSUE TITLE
businessinsider.com: nuisance

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13270]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.businessinsider.com/tiktok-could-compete-with-facebook-meta-2022-5`

### Category

nuisance

### Describe the issue

Can you block this pop-up?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ảnh](https://user-images.githubusercontent.com/95934994/168761423-e34487f1-c4d9-4997-8ac0-51b56b4fbb65.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83877
  cosmetic: 21190
  scriptlet: 19905
  html: 660
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4430-8, 18h
  default: 
    user-filters: 0-0, never
    ublock-filters: 31960-254, 18h.7m
    ublock-badware: 4132-3, 18h.6m
    ublock-privacy: 220-1, 18h.5m
    ublock-abuse: 75-0, 18h.4m
    ublock-unbreak: 1791-0, 18h.3m
    ublock-quick-fixes: 225-3, 5h.17m
    easylist: 66767-24537, 18h.2m
    easyprivacy: 26976-594, 18h.1m
    urlhaus-1: 9092-0, 5h.16m
    plowe-0: 3677-3, 4d.21h.51m
    VIE-1: 1888-36, 5h.15m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 672 ms (selfie)
  maxAssetCacheWait: 249 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    businessinsider.com: 1
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    chartbeat.com: 4
    confiant-integrations.global.ssl.fastly.net: 1
    cxense.com: 2
    doubleverify.com: 1
    flipboard.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    imhd.io: 1
    parsely.com: 1
    permutive.app: 1
    rebel.ai: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
    speedcurve.com: 2
    tinypass.com: 2
    trackonomics.net: 1
```
</details>

**Comment by mapx-** [comment]
It's not a popup, it's paywall (which we don't block)

However for your own tests => try blocking `tinypass` requests

**Comment by ghost** [comment]
Cookie notice even with EL and AG Cookie List filters

<img width="1597" height="720" alt="Image" src="https://github.com/user-attachments/assets/a24ee199-ec5a-45da-8d72-44a28f3f5795" />
