### ISSUE TITLE
tinhocdongthap.com: detection

### ISSUE THREAD

**Issue by Nabhan87** [uBlockOrigin/uAssets#13289]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tinhocdongthap.com/`

### Category

detection

### Describe the issue

the website detects ublock, and i block element with picker mode and it doesn't work.
![image](https://user-images.githubusercontent.com/96574749/169042967-a452bc39-2643-4238-a2bb-aa5833707e06.png)

when I have selected the element that I blocked it ends up blurry
![image](https://user-images.githubusercontent.com/96574749/169043680-ca95f01c-dcf5-41c1-86d3-61fbea6f76ea.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 80939
  cosmetic: 42181
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65018-51, never
    easyprivacy: 26734-121, never
    plowe-0: 3690-809, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-86, never
    ublock-filters: 30477-86, never
    ublock-privacy: 205-2, never
    ublock-quick-fixes: 139-15, never
    ublock-unbreak: 1742-41, never
    urlhaus-1: 8896-0, never
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1375 ms
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    tinhocdongthap.com: 3
    ampproject.org: 2
    googlesyndication.com: 4
    googletagmanager.com: 1
    onesignal.com: 2
    wp.com: 2
    zdn.vn: 1
```
</details>

**Comment by mapx-** [comment]
reproduced using a VIE ip
