### ISSUE TITLE
Filtering out systematically all names with AD or ADS prefixes

### ISSUE THREAD

**Issue by Pierre-aka-Terdef** [uBlockOrigin/uAssets#13282]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://assiste.com/Logitheque/ADS_Spy.html`

### Describe the issue

Hello,

I am the developer of a computer website (security, privacy and web neutrality) `https://assiste.com/`.

I have an old WEB page, which I hadn't looked at for a while, concerning the security tool of Merijn Bellekom (currently at Malwarebytes): Ads Spy at `https://assiste.com/Logitheque/ADS_Spy.html` (at the beginning of paragraph 2).
This tool identifies invisible ADS (Alternate Data Stream) files.
In this page, there is an image called ADS_Spy.png and its thumbnail ADS_Spy_V.png.
Unable to get those images displayed. I have to deactivate uBlock Origin to check that they do are on the server, under the good names, and that my URLs are correct.
I already had this problem with the ad-remover page (`https://assiste.com/Logitheque/Ad-Remover.html`) and I had to change the name of the illustration and its thumbnail.

This is probably a problem for visitors to my site using uBlock Origin.

I work under :
Windows 10 up to date
Firefox 100.0.1
uBlock Origin 1.42.24 

I think uBlock Origin filters out systematically all names with AD or ADS prefixes.

Thanks to look at that.
Pierre Pinard.
`https://assiste.com`

### uBlock Origin version

1.42.24

### Browser name and version

Firefox 100.0.1

### Settings

None

**Comment by mapx-** [comment]
Better renaming that png too: it's due to a filter in EasyList
`/images/ads_`

to see the image:
`@@||assiste.com/Assiste/media/images/ADS_Spy_V.png$image,1p`

**Comment by mapx-** [comment]
@ryanbr
