### ISSUE TITLE
A+ Content Delivered by Flixmedia is blocked 

### ISSUE THREAD

**Issue by Rohith-Flix** [uBlockOrigin/uAssets#13284]
### Prerequisites

- [x] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

All product pages where Flixmedia content is delivered.

For example,
`https://www.harveynorman.com.au/samsung-65-inch-q60a-4k-qled-smart-tv.html`

### Describe the issue

Hi Team,

Retailers in AU and NZ have been trying to integrate Flixmedia (`https://www.flixmedia.com/`) on their product pages to receive A+ content directly from brands through a single line of JS Code. Unfortunately, they have reported that all requests from Flixmedia on their product pages are being blocked by ublock Origin.

There are many retailers across AU and NZ who have reported this issue. _For example Bing Lee in AU, Mwave in AU and many other_

Flixmedia as a business, helps Brands and Retailers SELL MORE! We deliver rich content automatically onto retailer product pages through a single line of JavaScript Code. All the rich content is provided to us by the brand directly - content authorized by the brands (like LG, Samsung etc.,)

Here is a live example highlighting the services we deliver,
`https://www.harveynorman.com.au/samsung-65-inch-q60a-4k-qled-smart-tv.html`

Service 1 - HotSpots - https://prnt.sc/0Q4OjpCgaIXM
Service 2 - MiniSites - https://prnt.sc/xupvGAq09tYT
Service 3 - INpages - https://prnt.sc/04yKdRR70r9V

Requests that are being blocked,
https://prnt.sc/QpJEretev4_4
https://prnt.sc/vqQQpjWil4fd

All the requests from Flixmedia are blocked by uBlock Origin
https://prnt.sc/Gi1_BtKReEO-

Could you please test the above page and help in whitelisting our domains for seamless delivery of A+ (Rich Content) content directly onto product pages?

Here are the domains that needs to be whitelisted,
```
1. media.flixcar.com
2. media.flixfacts.com
3. logo.flixfacts.co.uk
4. media.flixsyndication.net
5. t.flix360.com
6. Syndication.flix360.com
7. content.jwplatform.com
8. assets-jpcust.jwpsrv.com
9. ssl.p.jwpcdn.com
10. *.cloudfront.net
12. media.pointandplace.com
13. player.pointandplace.com
14. t.pointandplace.com
15. *.flix360.com
16. *.flix360.io
17. intent://arvr.google.com
18. dev-origin.flixsyndication.net (for staging)
19. dev-delivery.flix360.com (for staging)
```
The Intent protocol should be whitelisted like this:
https://user-images.githubusercontent.com/105775065/168983608-3eafe62f-3a90-46e2-b4fa-f17a07d016cc.png

Will look forward to have this issue resolved as early as possible.

Best Regards,
Rohith P

### Screenshot(s)

https://user-images.githubusercontent.com/105775065/168981120-7f4eac0e-db5c-4ee2-9a25-e35092c285ad.png

### uBlock Origin version

1.42

### Browser name and version

Chrome Version 101.0.4951.67

### Settings

No Changes done

**Comment by mapx-** [comment]
The resources are mainly blocked by Easyprivacy list (not a uBO list).
However let's see all the improvements we can reach and we'll contact the maintainer.

Test 

```
@@||googletagmanager.com/gtm.js?id=GTM-3W36$script
||flixcar.com/*/tracking/$important
||flixcar.com/delivery/$badfilter
```

For any other blocked resource provide example cases and what's broken

**Comment by Rohith-Flix** [comment]
[uBlock details.xlsx](https://github.com/uBlockOrigin/uAssets/files/8718562/uBlock.details.xlsx)
I have tested couple of Retailer product pages, and noticed that all the requests delivered by Flixmedia are blocked. Please find the attached list of domains triggered with and without uBlock origin on the URL's highlighted.

We deliver brands own rich content (A+ Content) across 1600+ retailers and resellers in 90+ countries, and recently we have been reported by many retailers about our content being blocked by ad-blockers especially uBlock Origin. We need your support in whitelisting all our domains (listed below), for seamless delivery of A+ content directly onto retailer product pages.

1. media.flixcar.com
2. media.flixfacts.com
3. logo.flixfacts.co.uk
4. media.flixsyndication.net
5. t.flix360.com
6. Syndication.flix360.com
7. content.jwplatform.com
8. assets-jpcust.jwpsrv.com
9. ssl.p.jwpcdn.com
10. *.cloudfront.net
12. media.pointandplace.com
13. player.pointandplace.com
14. t.pointandplace.com
15. *.flix360.com
16. *.flix360.io
17. intent://arvr.google.com
18. dev-origin.flixsyndication.net (for staging)
19. dev-delivery.flix360.com (for staging)
The Intent protocol should be whitelisted like this:
![image](https://user-images.githubusercontent.com/105775065/169103261-102b6635-dccf-48ac-a0c4-3e7753ce7eda.png)

Please let us know if you need any further details from our end.

Thanks,
Rohith P

**Comment by mapx-** [comment]
I tested on `https://www.harveynorman.com.au/samsung-65-inch-q60a-4k-qled-smart-tv.html`
The filters I provided above work fine on it.

You are using googletagmanager.com to deliver your content / scripts.
Are you able to provide all the id for all those retailers ? (such as `id=GTM-3W36`)
If not => a list of those sites ?

We can not whitelist `googletagmanager.com/gtm.js` for all the pages in the world.

**Comment by Rohith-Flix** [comment]
Harvey Norman Australia is using Google Tag Manager to integrate our script, however there are other retailers like Croma in India who have integrated our script directly on their pages - and I see that the content is being blocked.
URL : https://www.croma.com/bose-700-noise-cancelling-bluetooth-headphones-sliver-luxe-/p/218849
https://prnt.sc/zkwK0OZz5b2c

Our content is ideally delivered under "Product Showcase" tab on this retailer website. When uBlock Origin is enabled, the content isn't loading - could you please test?

Below are the services that we deliver on this page,
https://www.croma.com/bose-700-noise-cancelling-bluetooth-headphones-sliver-luxe-/p/218849

Service 1 - HotSpots & WebAR - https://prnt.sc/fw6a_DWkOavG
Service 2 - MiniSites - https://prnt.sc/Ri_jJ_X1zWGr
Service 3 - INpages - https://prnt.sc/LnZe25p5vcET (all the way down)

We technically need the Domains listed in my above comment to be Whitelisted - the list of domains doesn't contain Google Tag Manager.

**Comment by mapx-** [comment]
on croma all fine if you use my filters above
```
||flixcar.com/*/tracking/$important
||flixcar.com/delivery/$badfilter
```

but the page has an issue I guess: even whitelisting the site, flix stuff appears ONLY if you scroll down the page and then go back to the top

**Comment by mapx-** [comment]
In this moment for the examples above we have 3 working filters 

```
@@||googletagmanager.com/gtm.js$script,domain=harveynorman.com.au
||flixcar.com/*/tracking/$important
||flixcar.com/delivery/$badfilter
```

**Comment by Rohith-Flix** [comment]
Where do we need to add these filters? Could you please help us with more detail on how we can make this work?

**Comment by mapx-** [comment]
I thought you already tested using my filters .. 
You should add them in "my filters" section (right click uBO icon, options, "my filters" tab, add the filters, click "apply changes")

The goal is adding them to the official lists but now we testing your sites, right ?

**Comment by Rohith-Flix** [comment]
||flixcar.com/*/tracking/$important
||flixcar.com/delivery/$badfilter

I have added above filters to Croma product page, and it is now working as expected - A+ Content is being delivered.

Integration is slightly different on Croma, wherein they trigger Flixmedia script only when a shopper scrolls down.

What are the next steps to make sure this filters apply across ALL our retail network?

**Comment by mapx-** [comment]
You have to test other pages to see if there are still issues.

I already notified Easyprivacy maintainer to take a look here, if for him is all ok he'll fix the issue in Easyprivacy list (and in 4-5 days all your clients / partners will receive automatically the updates).

It would be better for you to test quickly some other pages to see if all it's ok.

**Comment by Rohith-Flix** [comment]
I will have this checked and confirm as early as possible in the same thread. Thanks for your support.

**Comment by mapx-** [comment]
I'll add for now the filters in quick-fixed list just waiting easyprivacy decision (and the updates will be very fast - 1 day)

**Comment by Rohith-Flix** [comment]
Hi, Just wanted to check if there is any update on the above

**Comment by mapx-** [comment]
If your network is using uBO it's already fixed (see commit above).

**Comment by mapx-** [comment]
@ryanbr

**Comment by Rohith-Flix** [comment]
Content is still being blocked and not rendering. Are the filters added to the list?

**Comment by mapx-** [comment]
> 
I'll add for now the filters in quick-fixes list just waiting easyprivacy decision (and the updates will be very fast - 1 day)

**Comment by Rohith-Flix** [comment]
so are we waiting on easyprivacy decision?
could you please loop the relevant PIC from easyprivacy who would be able to support on this?

**Comment by mapx-** [comment]
I fixed the issue in quick-fixes list (as I already wrote above) 
uBO will update that list in maximum 1 day.

Easyprivacy could help who is using other adblockers.

**Comment by Rohith-Flix** [comment]
@mapx- Thanks for your support in having it fixed for uBO. I will give it a day and check again tomorrow to see if the content is rendering as expected with uBO extension enabled - will keep you posted.

@ryanbr  - Could you please assist in applying a similar fix on Easyprivacy, for seamless delivery of our rich content to pages using other adblockers?

**Comment by Rohith-Flix** [comment]
@mapx- @ryanbr  - I have tested on the below product page and the content is still being blocked when uBlock Origin extension is enabled,
https://www.currys.co.uk/products/samsung-ue65tu7020kxxu-65-smart-4k-ultra-hd-hdr-led-tv-10213566.html

Is there anything to do with the below?
https://hg.adblockplus.org/easylist/rev/70563037714c
https://prnt.sc/hjL89czAuZp3

**Comment by mapx-** [comment]
`currys` - unfortunately - implemented your stuff differently

needing:
```
@@||assets.adobedtm.com/*-source.min.js$script,domain=currys.co.uk
@@||currys.co.uk/on/*/js/tracking.js$script,1p
```

**Comment by mapx-** [comment]
That's why I asked you to test various / more pages .. quickly to have a fast response from easyprivacy too.
Added in uBO internal list for now.

**Comment by Rohith-Flix** [comment]
Thanks @mapx- 

There are over 1600 retailers in our network and every retailer has their own way of implementing Flix code. I am afraid and not sure if we would be able to test across ALL retailers. Let me randomly check our top retailers and confirm back.

**Comment by Yuki2718** [comment]
@Alex-302 If you agree to the above, the following should be removed from AGTPF as well:
```
||flixcar.com^$third-party
||flixfacts.com^$third-party
```
and add these:
```
||flixcar.com/*/tracking/
@@||googletagmanager.com/gtm.js$domain=harveynorman.co.nz|harveynorman.com.au
```

**Comment by Alex-302** [comment]
@Yuki2718 Ok. Exclusion + `$redirect` rule.

**Comment by Rohith-Flix** [comment]
@mapx- We have found an other retailer facing the same issue - https://www.mumzworld.com/ar/dyson-outsize-cordless-vacuum

Could you please check?

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
`domain=mumzworld.com` is working for subdomains too

**Comment by Rohith-Flix** [comment]
> `domain=mumzworld.com` is working for subdomains too

Thank you

**Comment by ryanbr** [comment]
Are you intentionally breaking these sites to allow googletag? because it looks a lot like it. @Rohith-Flix

**Comment by Rohith-Flix** [comment]
> Are you intentionally breaking these sites to allow googletag? because it looks a lot like it. @Rohith-Flix

No, we technically just want Flix rich content to be delivered to their product pages.

**Comment by Rohith-Flix** [comment]
On a separate note, our team internally is testing on top retailers across our network with uBlock Origin enabled in browser extension. Will share the list of product pages, where content is being blocked by uBlock Origin.
Thanks

**Comment by ryanbr** [comment]
If you're testing with uBO, then stop relying on GTM. So it won't break.

**Comment by mapx-** [comment]
> If you're testing with uBO, then stop relying on GTM. So it won't break.

The fact is there are a lot of sites with their own implementations

**Comment by Rohith-Flix** [comment]
> If you're testing with uBO, then stop relying on GTM. So it won't break.

@ryanbr - There are few retailers who are implementing our script through GTM or Adobe Dynamic Tag Manager.
Are you able to allow only the Flix script/domains to get through for retailers using GTM to integrate our code?

**Comment by ryanbr** [comment]
We've fixed the flixmedia stuff, other 3rd-party shouldn't be a requirement. So blocking gtm or adobe shouldn't also break .

**Comment by Rohith-Flix** [comment]
> We've fixed the flixmedia stuff, other 3rd-party shouldn't be a requirement. So blocking gtm or adobe shouldn't also break .

so this means, Flix content will render automatically if the retailer implements the code through GTM or Adobe?

**Comment by ryanbr** [comment]
Have GTM or adobe implemented, that's fine. Just don't make it a requirement to make things work. We're not expected to fix thousands of sites because there is a hardcoded requirement for gtm.

**Comment by Rohith-Flix** [comment]
> Have GTM or adobe implemented, that's fine. Just don't make it a requirement to make things work. We're not expected to fix thousands of sites because there is a hardcoded requirement for gtm.

I am not sure if you are getting me right. Let me re-iterate what we do as a business - Flixmedia delivers rich content directly onto RETAILER (Harvey Norman or Noel Leeming or Currys) product pages through a line of JavaScript Code. Now it's completely with the retailer on how they would like to implement our JavaScript Code. Few directly add the code to their HTML and few implement through extensions or plugins.

For example,
- Harvey Norman AU has integrated Flix code through Google Tag Manager – in this case will you be able to allow Flix content to render without whitelisting GTM?

- Currys UK has integrated Flix code through Adobe Dynamic Tag Manager - in this case will you be able to allow Flix content to render without whitelisting Adobe?

My only requirement here is to allow Flix content to be delivered seamlessly across all our retailer network, though they are using GTM or Adobe or any other extensions for implementing our script. Is this something possible without whitelisting GTM or Adobe or other extensions?

**Comment by Rohith-Flix** [comment]
@ryanbr - Just wanted to follow-up and check if there is any other way to allow Flix content on product pages without whitelisting GTM and Adobe for retailers using these tag management systems to integrate our Flix script.

**Comment by mapx-** [comment]
> Is there a way we could only allow Flix JS to be triggered for retailers integrating our code through GTM or Adobe?

no way.
I added the new exception in unbreak list.

@ryanbr

**Comment by Rohith-Flix** [comment]
@mapx- Could you please check for the below link as well?
https://www.tsbohemia.cz/philips-qp220-50-oneblade-nahradni-brity-2ks_d375168.html
Content is being blocked.

**Comment by Rohith-Flix** [comment]
@mapx- We have a new retailer who has added our script through GTM, and it is being blocked by ad-blockers. Could you please check?
https://www.teds.com.au/canon-powershot-g7x-mark-ii

**Comment by Rohith-Flix** [comment]
> 

Thanks for your feedback. We do suggest the retailer to add the code directly to their template, however there are few retailers who prefer to add the code through GTM or Adobe or Plugins (for Wordpress). It would be great if you are able to create an individual tag for Flixmedia which will allow the content to render though Retailer is using GTM or Adobe or a Plugin.

**Comment by Rohith-Flix** [comment]
> > however there are few retailers who prefer to add the code through GTM or Adobe
> 
> So you do acknowledge that your request to whitelist GTM for those sites, exposes users to tracking by Google; and you're okay with this?

My intent here is to not expose users to tracking by google, but it is to provide our services seamlessly to Retailers without any ad-blockers restricting our rich content delivered onto retailer product pages. We would recommend you to try and find a way to only allow Flix domains to be whitelisted, though the retailer implements the script through GTM/Adobe.

like for example, `@@||googletagmanager.com/gtm.js$FlixScript`

**Comment by Rohith-Flix** [comment]
> > My intent is to provide our services seamlessly to Retailers without any ad-blockers restricting our rich content delivered onto retailer product pages
> 
> And that's achievable by simply forcing the retailers not to use GTM/Adobe to implement your stuff, instead of asking uBO to whitelist trackers for many sites.
> 
> > We would recommend "_you_" **_to try and find a way_** to only allow Flix domains to be whitelisted
> 
> Why not make it mandatory for your customers to directly implement your services instead of putting the burden on uBO and exposing users to trackers such as GTM or Adobe? Your "Flix" domains are already whitelisted.

We cannot make this mandatory for retailers to implement directly. The decision here is completely with the retailer on whether to implement the script through a Plugin/GTM/Adobe or direct - we as a service provider can only recommend/suggest - end of the day, it is with the retailer on how they would like to implement the script.

**Comment by Rohith-Flix** [comment]
> If retailers choose GTM/Adobe over direct implemention then they already know that it's gonna be blocked by uBO, so why should uBO "try and find a way to only allow Flix domains to be whitelisted" when your customers are ignorant?

Customers are not ignorant, it's just that they are not aware that ad-blockers block any content that is delivered through GTM/Adobe. It is probably lack of communication from the ad-blockers on what will be blocked and what wouldn't be.

In a service industry, it's about helping the customers (Retailers and Brands in our case) to solve/fix the issue.
_Hope you understand this_

If this is something not possible, then we may ideally need to recommend/suggest retailer to add the script directly onto their template (which we already do) or ask them to suggest their shoppers/buyers to disable ad-blockers for seamless delivery of all their services.

**Comment by Rohith-Flix** [comment]
> https://github.com/gorhill/uBlock (Main page for uBlock Origin): "Ads, "unintrusive" or not, are just the visible portions of privacy-invading apparatus entering your browser when you visit most sites nowadays. **uBlock Origin's main goal is to help users neutralize such privacy-invading apparatus**".
 
> > In a service industry, it's about helping the customers
> 
> In that case, uBO is about helping users take back their privacy.

Great that uBO is helping their users, however this help is directly/indirectly affecting shopper browsing experience.

You may either need to update your [Wikipedia ](https://en.wikipedia.org/wiki/UBlock_Origin) or provide more information on [extension](https://chrome.google.com/webstore/detail/ublock-origin/), indicating/highlighting that any functionality added through tag managers like GTM or Adobe will be blocked as uBO treats it as "_privacy-invading_".

>"privacy-invading" includes trackers such as GTM and Adobe tag manager as well therefore your request to whitelist GTM for certain sites exposes users to tracking; a problem which seems to be solvable at its core by your customers.

I would like to reiterate that our intention is not to have GTM whitelisted as a whole , but only Flix code added through GTM.

**Comment by mapx-** [comment]
> not to have GTM whitelisted as a whole , but only Flix code added through GTM

as I already said time ago, it's impossible.

**Comment by Rohith-Flix** [comment]
>@mapx-
[https://github.com/uBlockOrigin/uAssets/issues/13284#issuecomment-128…](https://github.com/uBlockOrigin/uAssets/commit/19182f3a57c3858bb70a851329d9994bcf0d2db1) …
[19182f3](https://github.com/uBlockOrigin/uAssets/commit/19182f3a57c3858bb70a851329d9994bcf0d2db1)
…5046609

Noted @mapx- !
Thanks for having it resolved.

**Comment by Rohith-Flix** [comment]
@mapx- Could you please help in checking this URL - https://www.binglee.com.au/products/lg-75-uq90-4k-smart-uhd-tv-75uq9000psd
Content seems to be blocked.

**Comment by mapx-** [comment]
@Rohith-Flix provide useful info: what exactly is missing on that page ?  => screenshot indicating the missing item

**Comment by Rohith-Flix** [comment]
@mapx- Here is the screenshot of the content that is missing when I switch ON uBlock Origin extension in my browser.
https://www.awesomescreenshot.com/image/38001347?key=4b817ca2f3091283ae90d19fd2ec35bf

I have highlighted the services that we deliver on the given page,
https://www.binglee.com.au/products/lg-75-uq90-4k-smart-uhd-tv-75uq9000psd

**Comment by mapx-** [comment]
test

```
@@||googletagmanager.com/gtm.js$script,domain=binglee.com.au
@@||googleoptimize.com/optimize.js$script,domain=binglee.com.au
```

**Comment by Rohith-Flix** [comment]
> test
> 
> ```
> @@||googletagmanager.com/gtm.js$script,domain=binglee.com.au
> @@||googleoptimize.com/optimize.js$script,domain=binglee.com.au
> ```

@mapx- If I add this to "My filters" it works as expected.

**Comment by mapx-** [comment]
sure, it was fixed in Easyprivacy as you can see above

**Comment by Rohith-Flix** [comment]
> sure, it was fixed in Easyprivacy as you can see above

That's great! If I remove the filters and test, content is still being blocked. Should this be added to uBlock Origin list as well?

**Comment by mapx-** [comment]
No, you have to update manually easyprivacy list. If still does not work .. wait and try again (could be cloudflare issue)

**Comment by Rohith-Flix** [comment]
> No, you have to update manually easyprivacy list. If still does not work .. wait and try again (could be cloudflare issue)

Sorry, didn't get you. You mean to say, I have to update easyprivacy list manually?

I thought you have to add the domain to this,
[](https://github.com/uBlockOrigin/uAssets/commit/19182f3a57c3858bb70a851329d9994bcf0d2db1)

**Comment by mapx-** [comment]
Normally, in 4-5 days easyprivacy list will be updated automatically on all browsers using easyprivacy.
BUT, if you want to check again, update MANUALLY that list.

**Comment by Rohith-Flix** [comment]
> Normally, in 4-5 days easyprivacy list will be updated automatically on all browsers using easyprivacy. BUT, if you want to check again, update MANUALLY that list.

Noted! Will check again after 5 days and update accordingly.

**Comment by Rohith-Flix** [comment]
@mapx-

1) Content is now delivering as expected on Binglee. However, there are few tracking URL's that are still being blocked which technically allows our system to check if content is delivered as expected seamlessly,

||flix360.com/beat?
||flixcar.com/*/tracking/
||flixcar.com/gvid
||flixcdn.com^*/track.js
||flixgvid.flix360.io^
||flixster.com^*/analytics.

Is it possible to allow this?

https://www.binglee.com.au/products/lg-75-uq90-4k-smart-uhd-tv-75uq9000psd
Screenshot of the errors in Console for the given page pertaining to Flixmedia - https://prnt.sc/yyKbI3zoVyxa

2) We deliver Shop in Shops.
For example,
https://www.fnac.com/processeurs-amd

Content is being blocked on this URL. Here is the screenshot of the content without Adblocker,
https://www.awesomescreenshot.com/image/38465297?key=e6650e643b9951cf0084af56505dbe94

Could you please check and help in whitelisting content delivered through media.flixsyndication.net ?
Screenshot - https://prnt.sc/8SsjMftX3rqQ

Thanks in advance.

**Comment by mapx-** [comment]
I visited `https://www.fnac.com/processeurs-amd`
with uBO disabled, I get nothing like in your screenshot

**Comment by Rohith-Flix** [comment]
@mapx- Thanks for adding the changes. Is it the same standard process of 4-5 days to be added and updated automatically on all browsers using easyprivacy?

We have an other product page URL with similar issue - content is not rendering when uBO is enabled.
https://www.dns-shop.ru/product/5007e04adde92ff2/43-108-sm-televizor-led-philips-43pus795660-serebristyj/
Screenshot of the error - https://prnt.sc/LAEr3s6kuTss

**Comment by mapx-** [comment]
yes, the same but it has nothing to do with easyprivacy. It's fixed in our uBO lists (`unbreak` list).

If you want to fix for other adblockers too just report the at their repository:
https://github.com/easylist/easylist/issues

@ryanbr

**Comment by Rohith-Flix** [comment]
Hi @mapx- A new retailer has reported about content being blocked when uBO is enabled.
https://www.target.com.au/p/lego-reg-technic-ford-mustang-shelby-reg-gt5-reg-42138/66049562

Here is the screenshot highlighting the services we deliver on this page,
https://www.awesomescreenshot.com/image/38488830?key=50a164381bc1828dac10e74cf34122e4

Could you please check and have it fixed?

**Comment by Rohith-Flix** [comment]
> 

Reported the issue for other ad-blockers,
https://github.com/easylist/easylist/issues/15367

**Comment by Rohith-Flix** [comment]
> > I visited `https://www.fnac.com/processeurs-amd` with uBO disabled, I get nothing like in your screenshot
> 
> with uBO disabled I am able to see content - see video in the below link, https://www.awesomescreenshot.com/video/16053026?key=02b8a0f10e80087ac83d913fdc1e3515
> 
> Console errors screenshot with uBO enabled - https://prnt.sc/9UOyDKXTwmuA
> 
> `https://media.flixsyndication.net/microsite/static/js/loader.js`

Hi @mapx- , We have similar issue on below URL's too with uBO enabled,

https://www.fnac.com/intel
https://www.awesomescreenshot.com/image/38535537?key=ece0b727c87c42d4ea4ca63faeadd3df

https://www.boulanger.com/evenement/dyson
https://www.awesomescreenshot.com/image/38535711?key=8f39d0c57daa0b11f9f5c6b2cfecbe33

Content highlighted in the attached screenshots is blocked with uBO enabled. Kindly help.

Thanks.

**Comment by mapx-** [comment]
all the pages using `flixsyndication` are already ok, it's a general fix

**Comment by Rohith-Flix** [comment]
> `https://www.fnac.com/intel`

https://prnt.sc/WBP5AxVam2AH
Information still seems to be blocked. Is it the same protocol of waiting for 4-5 days for it to be applied?
Thanks

**Comment by mapx-** [comment]
@Rohith-Flix did you update your lists ?

**Comment by Rohith-Flix** [comment]
> @Rohith-Flix did you update your lists ?

@mapx- my bad, I have updated the list and it now works as expected. Will reach out to you if there is any further support required.
Thanks.

**Comment by Rohith-Flix** [comment]
> @mapx-
> 
> 1. Content is now delivering as expected on Binglee. However, there are few tracking URL's that are still being blocked which technically allows our system to check if content is delivered as expected seamlessly,
> 
> ```
> ||flix360.com/beat?
> ||flixcar.com/*/tracking/
> ||flixcar.com/gvid
> ||flixcdn.com^*/track.js
> ||flixgvid.flix360.io^
> ||flixster.com^*/analytics.
> ```
> 
> Is it possible to allow this?
> 
> `https://www.binglee.com.au/products/lg-75-uq90-4k-smart-uhd-tv-75uq9000psd` Screenshot of the errors in Console for the given page pertaining to Flixmedia - https://prnt.sc/yyKbI3zoVyxa
> 
> 2. We deliver Shop in Shops.
>    For example,
>    `https://www.fnac.com/processeurs-amd`
> 
> Content is being blocked on this URL. Here is the screenshot of the content without Adblocker, https://www.awesomescreenshot.com/image/38465297?key=e6650e643b9951cf0084af56505dbe94
> 
> Could you please check and help in whitelisting content delivered through media.flixsyndication.net ? Screenshot - https://prnt.sc/8SsjMftX3rqQ
> 
> Thanks in advance.

Hi @mapx- hope you are doing well. In reference to the first point mentioned in the above quote, there are few tracking URL's that are still being blocked which technically allows our system to check if product information is delivered as expected seamlessly and if there is any section of the information which needs to be optimized.

![image](https://user-images.githubusercontent.com/105775065/235611522-f4406570-2483-40de-8be8-13dd47b3420c.png)

Here is a copy of the Logger,

<details><summary>Logger output</summary>

```
+2
||flixcar.com/*/tracking/
--
www.binglee.com.au
3
get
script
https://media.flixcar.com/delivery/static/tracking/tracking.js
```
```
+2
||flixcar.com/*/tracking/
--
www.binglee.com.au
3
get
script
https://media.flixcar.com/delivery/static/tracking/tracking.js
```
```
+1
||flixcar.com/*/tracking/
--
www.binglee.com.au
3
get
script
https://media.flixcar.com/delivery/static/tracking/tracking.js
```
```
+1
||rt.flix360.com^
--
www.binglee.com.au
3
get
image
https://rt.flix360.com/jserr?f=https%3A%2F%2Fmedia.flixcar.com%2Fdelivery%2Fstatic%2Ftracking%2Ftracking.js%3F%26ssl%3D1%26abtesting%3D1&d=https%3A%2F%2Fwww.binglee.com.au%2Fproducts%2Flg-75-uq90-4k-smart-uhd-tv-75uq9000psd&m=Flix%20domain%20blocked
```
```
+1
||rt.flix360.com^
--
www.binglee.com.au
3
get
image
https://rt.flix360.com/jserr?f=https%3A%2F%2Fprod.flixgvid.flix360.io%2F&d=https%3A%2F%2Fwww.binglee.com.au%2Fproducts%2Flg-75-uq90-4k-smart-uhd-tv-75uq9000psd&m=Flix%20domain%20blocked
```
```
+0
||flixcar.com/*/tracking/
--
www.binglee.com.au
3
get
script
https://media.flixcar.com/delivery/static/tracking/tracking.js?&ssl=1&abtesting=1
```
```
+0
||flixgvid.flix360.io^
--
www.binglee.com.au
3
get
script
https://prod.flixgvid.flix360.io/
```
</details>


Could you please allow this domains too?

**Comment by mapx-** [comment]
That's tracking, we cannot allow it.

**Comment by Rohith-Flix** [comment]
> That's tracking, we cannot allow it.

Hi @mapx- This tracking is basically to check if product information is delivered as expected and it also helps to optimize information based on shopper/user preference.

**Comment by Yuki2718** [comment]
You totally misunderstand. Those who block tracking do not want any such sorts of optimization, they want websites to behave equally regardless who the user is.

**Comment by Rohith-Flix** [comment]
> You totally misunderstand. Those who block tracking do not want any such sorts of optimization, they want websites to behave equally regardless who the user is.

@Yuki2718 - thanks for your response. Me as a user enable ad-blocker, to block unwanted ads, pop-ups and to block domains tracking my personal information. Here at Flixmedia, we do not track any personal information, we just track whether the product information delivered from Flixmedia is delivered as expected on the retailer product page. Also, the optimization doesn't vary from one user to the other - product information delivered is consistent. For example, if product information delivered from our side has a lifestyle video which no user is interested to watch, then we ideally suggest our brands to remove such videos and add any informative video that speaks about the respective product. This is basically to help the users with more information about the product they want to purchase online.
