### ISSUE TITLE
rapidgrab.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1328]
URL(s) where the issue occurs

`http://rapidgrab.pl/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
I cannot reproduce, perhaps you have some specific link ?

**Comment by SMed79** [comment]
@xDarkARG test

`rapidgrab.pl##script:inject(overlay-buster.js)`

**Comment by xDarkARG** [comment]
I do not see anything now you can close the topic @mapx-
