### ISSUE TITLE
carhartt-wip.com: breakage

### ISSUE THREAD

**Issue by ErnestPietryka** [uBlockOrigin/uAssets#13280]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.carhartt-wip.com/fr/homme-featured-9`

### Category

breakage

### Describe the issue

Can't see the items for sell

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1366" alt="carhartt" src="https://user-images.githubusercontent.com/51130381/168911053-101b4701-cf10-42ea-8ae7-a727f19ececd.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 138543
  cosmetic: 146584
  scriptlet: 30880
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63815-1131, 4h.16m
    adguard-social: 17131-30, 4h.15m
    adguard-spyware: 27330-768, 4h.14m
    adguard-spyware-url: 599-13, 4h.13m
    block-lan: 43-0, 5d.58m
    fanboy-cookiemonster: 31918-85, 5d.58m
    fanboy-social: 23377-1074, 4h.12m
    fanboy-thirdparty_social: 68-21, 5d.58m
  default: 
    user-filters: 0-0, never
    FRA-0: 27646-24, 1d.46m
    easylist: 66876-981, 4h.21m
    easyprivacy: 27035-10962, 4h.20m
    plowe-0: 3676-885, 5d.59m
    ublock-abuse: 75-1, 5d.59m
    ublock-badware: 4128-305, 4h.19m
    ublock-filters: 31363-3376, 4h.18m
    ublock-privacy: 214-47, 5d.59m
    ublock-quick-fixes: 225-12, 4h.11m
    ublock-unbreak: 1780-92, 4h.17m
    urlhaus-1: 8762-0, 4h.10m
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 887 ms
  maxAssetCacheWait: 479 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    baqend.com: 4
```
</details>

**Comment by mapx-** [comment]
add

`carhartt-wip.com#@#div[data-cookie-name]`

**Comment by mapx-** [comment]
@ryanbr
