### ISSUE TITLE
reelrundown.com: nuisance

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13281]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://reelrundown.com/movies/Doctor-Strange-in-the-Multiverse-of-Madness-A-Multitude-of-Magical-and-Fun-Proportions`

### Category

nuisance

### Describe the issue

 There is a white border that hides the content and appears a pop-up video
 Almost all posts have the same pop-up video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ảnh](https://user-images.githubusercontent.com/95934994/168929140-bd6a9cdd-07f7-4877-b999-da50fd6658f9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83877
  cosmetic: 21190
  scriptlet: 19905
  html: 660
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4430-8, 1d.9h.36m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31960-254, 1d.9h.43m
    ublock-badware: 4132-3, 1d.9h.42m
    ublock-privacy: 220-1, 1d.9h.41m
    ublock-abuse: 75-0, 1d.9h.40m
    ublock-unbreak: 1791-0, 1d.9h.39m
    ublock-quick-fixes: 225-3, 20h.53m
    easylist: 66767-24537, 1d.9h.38m
    easyprivacy: 26976-594, 1d.9h.37m
    urlhaus-1: 9092-0, 20h.52m
    plowe-0: 3677-3, 5d.13h.27m
    VIE-1: 1888-36, 20h.51m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 672 ms (selfie)
  maxAssetCacheWait: 249 ms
popupPanel: 
  blocked: 75
  blockedDetails: 
    reelrundown.com: 4
    33across.com: 2
    3lift.com: 4
    adnxs.com: 6
    amazon-adsystem.com: 1
    casalemedia.com: 2
    ccgateway.net: 2
    doubleclick.net: 1
    google-analytics.com: 1
    hubpages.com: 2
    imasdk.googleapis.com: 1
    indexww.com: 2
    justpremium.com: 2
    jwpltx.com: 13
    lijit.com: 1
    mavencoalition.io: 1
    outbrain.com: 1
    petametrics.com: 1
    pubmatic.com: 4
    rubiconproject.com: 5
    scorecardresearch.com: 1
    spotxchange.com: 1
    teads.tv: 1
    yahoo.com: 16
```
</details>

**Comment by mapx-** [comment]
test

`reelrundown.com##.m-detail--feature-spacer`

**Comment by zeref-dragneel** [comment]
No more pop-up video

> test
> 
> `reelrundown.com##.m-detail--feature-spacer`

**Comment by mapx-** [comment]
@ryanbr annoyance maybe ?
