### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by benpinpop** [uBlockOrigin/uAssets#13299]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=uXHyoR5gTYw`

### Category

ads

### Describe the issue

Now shows ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81045
  cosmetic: 43113
  scriptlet: 16989
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66767-51, 2d.12h.55m
    easyprivacy: 27035-122, 1d.1h.50m
    plowe-0: 3676-804, 11d.5m
    ublock-abuse: 75-0, 8d.4h.32m
    ublock-badware: 4128-94, 2d.12h.58m
    ublock-filters: 31362-97, 2d.12h.57m
    ublock-privacy: 214-2, 5d.12h.30m
    ublock-quick-fixes: 222-0, 19m
    ublock-unbreak: 1780-41, 2d.12h.56m
    urlhaus-1: 7257-0, 4h.57m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 526 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 356
  blockedDetails: 
    youtube.com: 289
    doubleclick.net: 8
    google.com: 29
    googleadservices.com: 1
    googlesyndication.com: 16
    googlevideo.com: 13
```
</details>

**Comment by mapx-** [comment]
what you could try: https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
