### ISSUE TITLE
s.to: popups

### ISSUE THREAD

**Issue by darmstadt40** [uBlockOrigin/uAssets#13298]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.to/serie/stream/fresh-off-the-boat/staffel-2/episode-2`

### Category

popups

### Describe the issue

Opens new tab when clicking on the player of the videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 86102
  cosmetic: 28207
  scriptlet: 16996
  html: 657
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32081-281, 1d.12h.26m
    ublock-badware: 4132-3, 1d.12h.25m
    ublock-privacy: 220-1, 1d.12h.24m
    ublock-abuse: 75-0, 1d.12h.23m
    ublock-unbreak: 1796-0, 1d.12h.22m
    ublock-quick-fixes: 223-0, 11h.24m
    adguard-mobile: 7734-178, 1d.12h.21m
    easylist: 66851-24688, 1d.12h.20m
    easyprivacy: 27019-597, 1d.12h.19m
    urlhaus-1: 8688-0, 11h.23m
    plowe-0: 3676-3, 5d.12h.30m
    DEU-0: 5756-379, 11h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 807 ms (selfie)
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    ads-twitter.com: 1
    falsifythomas.com: 2
    imasdk.googleapis.com: 1
    yandex.ru: 2
```
</details>

**Comment by butilka123** [comment]
s.to when watching series does indeed make popups. They first call a Link that redirects to the unwanted website.

My filter list:
https://de.royalcams.com
https://royalcams.com
https://annual-gamers-choice.com
https://bestgames-2022.com
https://widespreadglamour.com
https://falsifythomas.com
https://futiledrugstore.com
https://clarifysuper.com
https://www.sesar.info
https://forecastsinglegait.com


Configuration:
<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 103986
  cosmetic: 83774
  scriptlet: 29010
  html: 658
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64179-4904, 3d.18h.57m
    adguard-mobile: 7769-161, 3d.18h.58m
  default: 
    user-filters: 10-0, never
    ublock-filters: 32137-58, 2d.21h.47m
    ublock-badware: 4137-3, 2d.6h.11m
    ublock-privacy: 220-0, 5d.22m
    ublock-abuse: 75-0, 5d.21m
    ublock-unbreak: 1800-0, 2d.6h.10m
    easylist: 67575-738, 2d.6h.9m
    easyprivacy: 27106-597, 2d.6h.8m
    urlhaus-1: 9446-0, 21h.7m
    plowe-0: 3671-3, 3d.23h.2m
    DEU-0: 5774-2, 21h.8m
    ublock-quick-fixes: 190-0, 21h.9m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 186 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    ads-twitter.com: 2
    chaturbate.com: 1
    forecastsinglegait.com: 2
    imasdk.googleapis.com: 2
    yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
update your filter lists

**Comment by mapx-** [comment]
yes, it was reported in FF / FF android sometimes the settings are broken, all the lists unselected.

**Comment by darmstadt40** [comment]
![Uploading Screenshot_20220530-200551.png…]()

**Comment by darmstadt40** [comment]
The lists are still selected

**Comment by darmstadt40** [comment]
![Screenshot_20220530-200551](https://user-images.githubusercontent.com/43100020/171042669-af59c156-789e-4c03-bdda-3a18c32381f8.png)
