### ISSUE TITLE
devopscube.com: ads

### ISSUE THREAD

**Issue by BeanJuice** [uBlockOrigin/uAssets#13291]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://devopscube.com/checkout-clone-specific-git-commit-id-sha/`

### Category

ads

### Describe the issue

Closeable Linux foundation ad/popup

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82516
  cosmetic: 43046
  scriptlet: 16974
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66876-51, 20h.23m
    easyprivacy: 27035-122, 16h.17m
    plowe-0: 3673-804, 16h.20m
    ublock-abuse: 75-0, 16h.19m
    ublock-badware: 4128-94, 9h.37m
    ublock-filters: 31363-99, 20h.24m
    ublock-privacy: 214-2, 16h.21m
    ublock-unbreak: 1780-41, 16h.16m
    urlhaus-1: 8762-0, 20h.22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 397 ms (selfie)
  maxAssetCacheWait: 1087 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
