### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by AvenCores** [uBlockOrigin/uAssets#13294]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aternos.org/server/`
`https://aternos.org/options/`
and more

### Category

detection

**You represent an ad blocker!
Our service works 100%, we only pay for servers with ads. This project cannot exist without income from this advertising. We would really appreciate it if you could disable your ad blocker. We promise you that our ads will not torment you with annoying recovery windows.**

### Describe the issue

Aternos detects the use of an ad blocker. Specifically Ublock Origin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/64781822/169151106-0394dc78-443e-4d2b-a134-d383e1cea2d9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 99206
  cosmetic: 64872
  scriptlet: 18178
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 24-0, never
    RUS-0: 41336-9, 1d.9h.43m
    easylist: 66768-64, 2d.4h.57m
    easyprivacy: 26976-218, 2d.4h.56m
    plowe-0: 3676-809, 10d.5h.25m
    ublock-abuse: 75-1, 10d.5h.25m
    ublock-badware: 4128-94, 2d.4h.55m
    ublock-filters: 31366-128, 2d.4h.54m
    ublock-privacy: 216-4, 10d.5h.25m
    ublock-quick-fixes: 222-0, 3h.42m
    ublock-unbreak: 1780-41, 2d.4h.53m
    urlhaus-1: 7257-0, 3h.42m
filterset (user): [array of 24 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3611 ms (selfie)
  maxAssetCacheWait: 364 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    aternos.org: 1
    33across.com: 1
    360yield.com: 1
    3lift.com: 1
    4dex.io: 1
    a-mo.net: 1
    adnxs.com: 1
    adsrvr.org: 1
    cloudflareinsights.com: 1
    criteo.com: 3
    fastclick.net: 1
    google-analytics.com: 1
    google.com: 1
    google.ru: 1
    googlesyndication.com: 3
    id5-sync.com: 1
    indexww.com: 1
    onetag-sys.com: 1
    openx.net: 1
    pubmatic.com: 1
    rlcdn.com: 1
    rubiconproject.com: 1
```
</details>

**Comment by mapx-** [comment]
ongoing https://github.com/uBlockOrigin/uAssets/issues/13144
