### ISSUE TITLE
outlook.live.com

### ISSUE THREAD

**Issue by DesertBear** [uBlockOrigin/uAssets#13297]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://outlook.live.com/mail/0/`

### Describe the issue

The ad bar on the right-hand side is no longer hidden by the cosmetic filter if the left pane is minimised.  See screenshots below.

### Screenshot(s)

**Left pane visible: Ad bar hidden (correct):**
![Screenshot A](https://user-images.githubusercontent.com/27423064/169162368-6264f914-0e43-4b67-ad1a-f976150a00a4.png)

**Left pane collapsed: Ad bar visible (incorrect):**
![Screenshot B](https://user-images.githubusercontent.com/27423064/169162391-c4cbdc42-d2d1-4f1b-a5ab-fa10ef2b56b3.png)

### Notes

**Relevant "uBlock filters – Annoyances" filter:**
```
Filter       outlook.live.com##div[class][tabindex="-1"][role=region][aria-label][data-min-width][data-max-width] ~ div[class][data-max-width="2400"] + div[class]
Filter list  uBlock filters – Annoyances 
Context      outlook.live.com
Type         dom
URL          https://outlook.live.com/mail/0/
```

**Relevant "AdGuard Annoyances" filter:**
```
Filter       outlook.live.com###app div[class] > div[role="region"] ~ div[class]:not([data-max-width]):not([role]):has(div[class] > img[aria-label][src*="adbar"])
Filter list  AdGuard Annoyances 
Context      outlook.live.com
Type         dom
URL          https://outlook.live.com/mail/0/
```

**"AdGuard Annoyances" reported here:**
https://github.com/AdguardTeam/AdguardFilters/issues/119166

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 85737
  cosmetic: 90282
  scriptlet: 22310
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53289-174, 23m
    block-lan: 43-0, 23m
    ublock-annoyances: 4422-149, 23m
  default: 
    user-filters: 86-0, never
    easylist: 66894-90, 8h.23m
    easyprivacy: 27035-219, 8h.23m
    plowe-0: 3673-805, 23m
    ublock-abuse: 75-0, 23m
    ublock-badware: 4128-94, 23m
    ublock-filters: 31383-435, 23m
    ublock-privacy: 214-2, 23m
    ublock-quick-fixes: 226-3, 23m
    ublock-unbreak: 1780-45, 23m
    urlhaus-1: 7257-0, 23m
filterset (user): [array of 86 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1301 ms (selfie)
  maxAssetCacheWait: 233 ms
```
</details>

**Comment by mapx-** [comment]
Even disabling the filter in uBO Annoyances => no ad bar still there

**Comment by DesertBear** [comment]
I have tried this in Windows Sandbox, therefore using default Microsoft Edge and default uBlock Origin settings (with the exception of enabling "uBlock filters – Annoyances") and it is reproducible every time.

I also tried with a different Microsoft account and it is reproducible with that account as well.

Are you collapsing the left column using the button shown in the above screenshot?  If you are, then it could be that Microsoft have updated some Microsoft accounts to a newer format and the Microsoft account you are testing with is still on the old version.

As well as the issue occurring when collapsing the left column, if the browser window size is reduced in width, the ad placeholder is then visible at the bottom too.

**When window width reduced, ad placeholder appears at the bottom too (incorrect):**
![Screenshot C](https://user-images.githubusercontent.com/27423064/169268054-b9b666a5-a745-4463-bef7-0c0a4fa8c3e8.png)


### Configuration in Windows Sandbox


```
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82799
  cosmetic: 44635
  scriptlet: 19911
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4422-6, 5m
  default: 
    user-filters: 0-0, never
    easylist: 67151-51, 26m
    easyprivacy: 27041-122, 26m
    plowe-0: 3673-804, 26m
    ublock-abuse: 75-0, 26m
    ublock-badware: 4128-94, 26m
    ublock-filters: 31390-105, 26m
    ublock-privacy: 214-2, 26m
    ublock-quick-fixes: 226-0, 26m
    ublock-unbreak: 1780-41, 26m
    urlhaus-1: 8630-0, 26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3444 ms
  maxAssetCacheWait: 470 ms
```

**Comment by Yuki2718** [comment]
Test `outlook.live.com###MainModule div[data-max-width="2400"] + div`

**Comment by DesertBear** [comment]
That rule prevents it appearing when the left-hand column is collapsed, however it still appears at the bottom if the browser window width is reduced (as per the screenshot in the last comment).

**Comment by Yuki2718** [comment]
Okay, add this too: `outlook.live.com###MainModule + div[class] > div[style^="width"] > div > i[data-icon-name="OutlookLogo"]:upward(3)`

**Comment by DesertBear** [comment]
The two rules together appear to work OK.  Thanks.

```
outlook.live.com###MainModule div[data-max-width="2400"] + div[class]

outlook.live.com###MainModule + div[class] > div[style^="width"] > div > i[data-icon-name="OutlookLogo"]:upward(3)
```
