### ISSUE TITLE
alemdarleech.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1329]
URL(s) where the issue occurs

`http://alemdarleech.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
`http://185.153.231.222/jetapi/?file=86851589310168`
(alemdarleech)

There's popup ads
