### ISSUE TITLE
app.detrack.com: breakage

### ISSUE THREAD

**Issue by Andrewteng8** [uBlockOrigin/uAssets#13290]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.detrack.com/dashboard/`

### Category

breakage

### Describe the issue

does not show detail

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/20695199/169047264-c39f6427-caea-412a-8696-7c62437ddda1.png)
![image](https://user-images.githubusercontent.com/20695199/169047452-3bbdf947-4df5-4682-96c5-513d918234c9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82497
  cosmetic: 43121
  scriptlet: 16988
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 18m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 18-0, never
    easylist: 66760-51, 2d.8h.15m
    easyprivacy: 26976-121, 2d.8h.14m
    plowe-0: 3677-804, 6d.7h.9m
    ublock-abuse: 75-0, 2d.8h.20m
    ublock-badware: 4128-94, 2d.8h.18m
    ublock-filters: 31360-97, 2d.8h.17m
    ublock-privacy: 214-2, 2d.8h.19m
    ublock-quick-fixes: 228-3, 23h.25m
    ublock-unbreak: 1780-41, 2d.8h.16m
    urlhaus-1: 8762-0, 23h.26m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 536 ms (selfie)
  maxAssetCacheWait: 239 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    detrack.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Is a account needed?

**Comment by mapx-** [comment]
yes, needing an account ..

@Andrewteng8 

open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the logger's search box)

**Comment by Andrewteng8** [comment]
![image](https://user-images.githubusercontent.com/20695199/169073764-b056f6fb-c461-40e0-bcf5-305311ddcd05.png)

**Comment by Andrewteng8** [comment]
![image](https://user-images.githubusercontent.com/20695199/169074064-9956b758-f0ce-435d-8151-0eb7ec17b8f4.png)

**Comment by mapx-** [comment]
does this filter work ?

`@@||app.detrack.com/api/v2/tracking$xhr`
