### ISSUE TITLE
[nsfw] leaknudes.com: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13296]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://leaknudes.com/`

### Category

breakage

### Describe the issue

Images do not load properly.
The display is broken.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/169161432-659bc784-87e1-4aea-a6d7-bc36535f7e8a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 428902
  cosmetic: 57665
  scriptlet: 29477
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    easyprivacy: null
    plowe-0: null
  added: 
    adguard-generic: 63867-1086, 2m
    adguard-mobile: 7741-70, 2m
    adguard-spyware: 27275-764, 2m
  default: 
    user-filters: 2125-239, never
    easylist: 67127-24838, 2m
    ublock-abuse: 75-0, 2m
    ublock-badware: 4128-297, 2m
    ublock-filters: 31383-3579, 2m
    ublock-privacy: 214-40, 2m
    ublock-quick-fixes: 226-9, 2m
    ublock-unbreak: 1780-83, 2m
    urlhaus-1: 7257-577, 2m
filterset (user): [array of 2054 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 774 ms (selfie)
  maxAssetCacheWait: 450 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings, test again
