### ISSUE TITLE
shellshock.io: ads, breakage

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#13295]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shellshock.io/`

### Category

ads

### Describe the issue

Whenever you are in the lobby, loading screen, or on the weapon select screen, an ad of another game may pop up.
It also detects ublock origin, and shows a pop up of "please disable your ad blocker", gives a slight delay, but it sometimes does not pop up, and sometimes it does. You can't close it, you have to wait for it to go away, then you can play the game.
I am new to making these issues so sorry if I accidentally messed up a step.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_GQhsz0A7ub](https://user-images.githubusercontent.com/104040739/169151558-32c69057-3bc8-433c-906e-446835a4bee0.png)
![castles](https://user-images.githubusercontent.com/104040739/169151497-3ed88c08-a851-4d2b-a800-41f3b4d27fb5.png)
![firefox_6WAK4QCTIs](https://user-images.githubusercontent.com/104040739/169151595-4ebb2f7e-c318-4990-b6b8-14b160e7da8b.png)
![firefox_RuioWxnHCI](https://user-images.githubusercontent.com/104040739/169151680-2f33d57d-b6fb-4db7-8910-98ea1799b55f.png)
![firefox_VzT2jYXBCJ](https://user-images.githubusercontent.com/104040739/169151922-2635922b-932a-43e9-b154-02b798012017.png)
![firefox_E2Tb4DRaTV](https://user-images.githubusercontent.com/104040739/169153204-03130dee-b883-4b72-9c66-158fb03b81be.png)
![firefox_VnPBLIwiON](https://user-images.githubusercontent.com/104040739/169153271-c1dce9f5-fb0b-4d18-88f0-327a9c87ccc0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 81178
  cosmetic: 43335
  scriptlet: 16972
  html: 655
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31991-30, 1m
    ublock-badware: 4132-3, 1m
    ublock-privacy: 220-0, 1m
    ublock-abuse: 75-0, 1m
    ublock-unbreak: 1791-0, 1m
    ublock-quick-fixes: 226-0, 1m
    easylist: 67117-602, 1m
    easyprivacy: 27036-579, 1m
    urlhaus-1: 7257-0, 1m
    plowe-0: 3673-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2885 ms
  maxAssetCacheWait: 301 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adinplay.com: 2
    cloudflareinsights.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    onesignal.com: 2
```
</details>

**Comment by mapx-** [comment]
test these filters

```
shellshock.io##.box_relative.chw-progress-wrapper
shellshock.io##.respawn-container > .pauseFiller > .house-wrap
shellshock.io##.house-small
shellshock.io##.overlay_dark.overlay
shellshock.io###spinnerOverlay
```

**Comment by mapx-** [comment]
You should use chrome, FF is very slow playing this game.

> anti adblock still there

I cannot reproduce anymore, if you are able to get it use the element picker and tell me if you get some useful filter

**Comment by mapx-** [comment]
I didn't understand how to reproduce the issue, explain again (with some screenshot)

**Comment by StingyAir** [comment]
get to this screen 
![image](https://github.com/uBlockOrigin/uAssets/assets/146357583/22a17c2e-f570-4cda-b3d0-2e7ed439a35a)

Then press play.
That is where the issue occurs. sometimes it happens sometimes it doesn't.
I recommend pressing escape waiting for the 5-second timer and then loading back in.
I can't show how the problem looks exactly but here is a list of events
1) Press play button
2) Observe no sound, but game works nonetheless
3) after short >1 time game acts as if you pressed the esc key

I think that the timing of the glitch may be related to when ads are supposed to dissappear

**Comment by mapx-** [comment]
I cannot reproduce any issue.
Did you try to reset uBO to default settings / lists and disable any other extension ?

**Comment by StingyAir** [comment]
Hello, I will attempt to disable other extensions. 
I will say, it only occurred once I installed this extension. Ublock is, and has been on default settings. and I force reseted the filter lists.
Just wanted to ask are you on macos or windows, I am on windows

**Comment by mapx-** [comment]
windows, it does not matter

**Comment by StingyAir** [comment]
Interesting, I am disableing other extensions now and will report back on the effects

**Comment by StingyAir** [comment]
how long did you play for? try for a little bit longer.
also when I switch tabs that seems to sometimes trigger it, so try doing that first (switch tabs after a round and then go back to the game and continue testing).

**Comment by luftra** [comment]
![Image](https://github.com/user-attachments/assets/741a6db7-0655-4b86-aa0b-b7d9b1cd4093)

Reward ads detect ad blocking software.

**Comment by luftra** [comment]
![Image](https://github.com/user-attachments/assets/5ebbd3b6-6782-4f8b-ae8d-8588b457ba05)

Reward ads detect ad blocking software.
