### ISSUE TITLE
uBlock blocks YouTube annotations

### ISSUE THREAD

**Issue by DangerousDarkEspeon** [uBlockOrigin/uAssets#133]
### URL(s) where the issue occurs
www.youtube.com/*

### Describe the issue

Been using uBO for quite a long time now, and only now I got so mad at annotations not working, that I decided to investigate. I have 2 adblocks installed: AdBlock and uBlock Origin, and I tried turning them off one by one, and it seems the reason behind the annotations block is uBO. Annotations on YouTube videos are not showing. Turning them off and on again and again, reloading - nothing helped. Adding youtube.com/* to whitelist didn't help either.

### Screenshot(s)

It's hard to see on these pictures, but oh well, here I go.
This one is with uBlock turned off. You cannot see, thanks to black background, but the words "YES" and "NO" are clickable. Also here's your typical advertisement, because AdBlock sucks.
http://puu.sh/r5jqq/94dac1423d.jpg
Now I turn on uBlock. Ad is gone, but so are annotations. Notice the second line on the tab to the right. It says "Annotations" and they're turned on.
http://puu.sh/r5jzM/64d6d9a24d.jpg

### Versions

- Browser/version: Opera 39.0
- uBlock Origin version: 1.9.4

### Settings

- Default

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Sorry, somehow I thought I was on uBlock repo.

**Comment by gorhill** [comment]
- Please provide a URL.
- Your filter lists.

**Comment by DangerousDarkEspeon** [comment]
Here's an example of URL that has lots of annotations in it; https://www.youtube.com/watch?v=4Bz0pYhAoFg
And I only use default filters, my personal filter list is empty.

**Comment by gorhill** [comment]
How long do I have to wait to get the annotation, or at which time do I seek to see it?

**Comment by DangerousDarkEspeon** [comment]
They appear right from the beginning. All the "pictures" are clickable.

**Comment by gorhill** [comment]
The thumbnails are clickable on my side, with uBO's default filter lists.

**Comment by DangerousDarkEspeon** [comment]
Thumbnails work for me too. Annotations don't work.
Wait, are we using the same terminology?
Just to clarify: thumbnails are videos on the right, and annotations are clickable links and text in a border inside the video itself.

**Comment by gorhill** [comment]
RU AdList is doing this: `youtube.com##.video-annotations .annotation-type-text`. You will have to report to them.

**Comment by DangerousDarkEspeon** [comment]
I see. Thanks a lot, I'll tell them about this problem!

**Comment by gorhill** [comment]
Meanwhile you can use `youtube.com#@#.video-annotations .annotation-type-text` to cancel the RU AdList filter.
