### ISSUE TITLE
sportowefakty.wp.pl: breakage

### ISSUE THREAD

**Issue by KGHTW** [uBlockOrigin/uAssets#13305]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sportowefakty.wp.pl/zuzel/zdjecia/galeria/23305/final-mistrzostw-europy-w-poznaniu-galeria`

### Category

breakage

### Describe the issue

It does not display photos from the gallery. This is caused by uBlock filters – Quick fixes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83826
  cosmetic: 50799
  scriptlet: 17179
  html: 666
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32013-69, 2m
    ublock-badware: 4132-3, 2m
    ublock-privacy: 219-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1791-0, 2m
    ublock-quick-fixes: 226-0, 2m
    easylist: 67171-621, 2m
    easyprivacy: 27039-579, 2m
    urlhaus-1: 8491-0, 2m
    plowe-0: 3673-3, 2m
    POL-0: 7841-25, 3m
    POL-2: 1276-12, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2501 ms
  maxAssetCacheWait: 293 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    wp.pl: 1
    gemius.pl: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Breakage is fixed now. Does 

```
sportowefakty.wp.pl##article > div:has(> div:empty)
sportowefakty.wp.pl###gallerybox_id > div:first-child:has(> div:empty)
sportowefakty.wp.pl##.articleteasers__list > .articleteaser:has(> .inview + span > a[target="_blank"])
```

Works as a replacment? (to hide placeholders and ads)

**Comment by KGHTW** [comment]
Can confirm, gallery works now.
About replacment, it acts weird if there's a video in article and you try to scroll down (https://sportowefakty.wp.pl/inne/1001085/nowy-ranking-forbesa-to-on-jest-najbogatszym-sportowcem-na-swiecie)

Without first line:
`sportowefakty.wp.pl##article > div:has(> div:empty)`
seems to be ok.
This website is one big mess :P

**Comment by JobcenterTycoon** [comment]
Yes the site is problematic. Ok i know the problem now the first rule was not spezific enough. Try `sportowefakty.wp.pl##article > div[class*=" "]:has(> div:empty:not([style]))`

**Comment by KGHTW** [comment]
This one works fine, thanks!
