### ISSUE TITLE
[nsfw] aniworld.to: popups

### ISSUE THREAD

**Issue by Lufrog67** [uBlockOrigin/uAssets#13309]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aniworld.to/`

### Category

popups

### Describe the issue

NSFW Popups opens nsfw tabs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 83077
  cosmetic: 45779
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5768-0, 3m
    easylist: 65018-57, never
    easyprivacy: 26734-132, never
    plowe-0: 3690-810, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-86, never
    ublock-filters: 30477-97, never
    ublock-privacy: 205-2, never
    ublock-quick-fixes: 139-15, never
    ublock-unbreak: 1742-42, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 559 ms
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    7vid.net: 2
    addtoany.com: 1
    ads-twitter.com: 2
    allvideometrika.com: 1
    cameraunswing.com: 1
    d1ac2du043ydir.cloudfront.net: 1
    futiledrugstore.com: 2
    google-analytics.com: 1
    googletagmanager.com: 2
    imasdk.googleapis.com: 2
    o333o.com: 1
    overdonereciprocalimpure.com: 1
    twitter.com: 1
    vidoza.net: 1
    yandex.ru: 4
```
</details>

**Comment by mapx-** [comment]
`ublock-filters: 30477-97, never`

You have some issue with updating the filter lists.
Force update all your lists and test again
[click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)
