### ISSUE TITLE
tw.piliapp.com: breakage

### ISSUE THREAD

**Issue by cavemanone** [uBlockOrigin/uAssets#13316]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tw.piliapp.com/timer/stopwatch/`

### Category

breakage

### Describe the issue

在開啟插件時，網頁無法正常運行，關閉插件後重新整理才可以

**When the plug-in is turned on, the webpage cannot run normally, and it can be refreshed after closing the plug-in.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 99246
  cosmetic: 52350
  scriptlet: 16586
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28728-121, never
    easylist: 65018-533, never
    easyprivacy: 26734-100, never
    plowe-0: 3690-449, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-113, never
    ublock-privacy: 205-1, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-29, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3027 ms
  maxAssetCacheWait: 22 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflare.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr
