### ISSUE TITLE
nieuwsblad.be: detection

### ISSUE THREAD

**Issue by davleema** [uBlockOrigin/uAssets#13321]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nieuwsblad.be/cnt/dmf20220518_98212152`

### Category

detection

### Describe the issue

videos on this Belgian news site show "disable your adblocker to see this video" (in Ducth). 
Till a  few days ago, this did not happen, and videos played just fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-05-20_12-01-02](https://user-images.githubusercontent.com/10529668/169505190-0ae2a5e9-a20e-407c-ab91-1c8b348220d1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 52941
  cosmetic: 43428
  scriptlet: 16973
  html: 655
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  default: 
    user-filters: 70-1, never
    ublock-filters: 31999-30, 18h.26m
    ublock-badware: 4132-3, 18h.25m
    ublock-privacy: 220-0, 7d.53m
    ublock-abuse: 75-0, 7d.52m
    ublock-unbreak: 1791-0, 18h.24m
    easylist: 67171-225, 18h.23m
    urlhaus-1: 8630-0, 1d.2h.28m
    ublock-quick-fixes: 226-0, 1d.2h.27m
filterset (user): [array of 70 redacted]
trustedset: 
  added: [array of 32 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 26 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 250 ms (selfie)
  maxAssetCacheWait: 272 ms
  unsuspendAfter: 65 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    cxense.com: 1
    doubleclick.net: 13
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 4
    googletagservices.com: 1
    imasdk.googleapis.com: 4
    mediahuis.be: 1
```
</details>

**Comment by mapx-** [comment]
Enable `NLD: EasyDutch` list
