### ISSUE TITLE
imdbembed.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13320]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://123films.imdbembed.xyz/movie/imdb/tt10698680`

from `https://123films.cc/k-g-f-chapter-2/`

### Describe the issue

popup arising when try to play various servers

### uBlock Origin version

1.42.4

### Browser name and version

opera stable

### Settings

Default

### Notes

```
123films.imdbembed.xyz###addiv
||psurigrabi.com^
||scrapethrillmostly.com^$all
```

**Comment by ghajini** [comment]
@mapx- woul you tell how you found **window.open** call

**Comment by ghajini** [comment]
so i should have de-obfuscate the code given in  `https://123films.imdbembed.xyz/JS/hqlps.js` 
i just hided overlay
thanks for nice through explanation

**Comment by mapx-** [comment]
"Automatically" when I get a classic (not a popunder) popup I try `nowoif`
Then if I want to go deeper to the popup reason I can use `nowoif, , , log` or the script content

**Comment by ghajini** [comment]
if i have no `nowoif` scriptlet ,then this would be fixed like this `imdbembed.xyz##+js(aopw, open)`
or any other way?

**Comment by mapx-** [comment]
for popups you can try killing `open` or .. `opener`, for popunders "they" are using various tricks (`location.href` for example)
