### ISSUE TITLE
index.hr: breakage

### ISSUE THREAD

**Issue by itisljar** [uBlockOrigin/uAssets#13324]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.index.hr/vijesti/clanak/zbog-devastacije-vruje-podignuta-optuznica-protiv-milanovicevog-donatora-i-prijatelja/2365930.aspx`

### Category

breakage

### Describe the issue

When filtering is on, video in the article does not play; only preview runs. Pressing play does nothing. When disabling filters, video plays normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82458
  cosmetic: 43408
  scriptlet: 17017
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 18-1, never
    easylist: 67182-51, 5h.50m
    easyprivacy: 27052-122, 5h.49m
    plowe-0: 3676-804, 11d.12h.29m
    ublock-abuse: 75-0, 9d.4h.49m
    ublock-badware: 4128-94, 5h.52m
    ublock-filters: 31412-104, 20h.57m
    ublock-privacy: 216-4, 9d.4h.50m
    ublock-quick-fixes: 226-0, 20h.54m
    ublock-unbreak: 1786-41, 5h.51m
    urlhaus-1: 8491-0, 20h.55m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 30 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 92 ms
popupPanel: 
  blocked: 48
  blockedDetails: 
    index.hr: 1
    adform.net: 1
    adnxs.com: 2
    adpushup.com: 1
    adrecover.com: 1
    adxpremium.services: 1
    amazon-adsystem.com: 2
    brid.tv: 1
    casalemedia.com: 1
    clarity.ms: 1
    cloudflareinsights.com: 2
    connectad.io: 2
    criteo.com: 2
    criteo.net: 2
    dotmetrics.net: 1
    doubleclick.net: 2
    facebook.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    indexww.com: 1
    midas-network.com: 1
    openx.net: 1
    pinterest.com: 1
    rubiconproject.com: 8
    smartadserver.com: 7
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr
