### ISSUE TITLE
dlsfile.com: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13325]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dlsfile.com/dd/ODYxODgwMHppaXdrZWF0ZG96cV8zNjc1MTA%3D`

### Category

breakage

### Describe the issue

Once the countdown has elapsed, the file does not download and no matter how hard you press the download button, nothing happens.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/169620071-e1ae1003-6c8f-4634-b30b-0d9e902ac4fd.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 430228
  cosmetic: 57738
  scriptlet: 29495
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    easyprivacy: null
    plowe-0: null
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt: 6097-0, 11h.28m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/adguard/anti-antiadb.txt: 318-20, 11h.28m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/no_gen_cosm/phhider.txt: 683-7, 11h.28m
    adguard-generic: 63932-1092, 11h.28m
    adguard-mobile: 7750-71, 11h.28m
    adguard-spyware: 27323-765, 11h.28m
  default: 
    user-filters: 2126-119, never
    easylist: 67182-24860, 11h.28m
    ublock-abuse: 75-0, 11h.28m
    ublock-badware: 4128-297, 11h.28m
    ublock-filters: 31425-3695, 11h.28m
    ublock-privacy: 213-40, 11h.28m
    ublock-quick-fixes: 212-9, 11h.28m
    ublock-unbreak: 1786-83, 11h.28m
    urlhaus-1: 8493-581, 11h.28m
filterset (user): [array of 2055 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 760 ms (selfie)
  maxAssetCacheWait: 456 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    dlsfile.com: 1
    xovilumium.space: 7
```
</details>

**Comment by mapx-** [comment]
I get no countdown. The site seems to be a fake one.
