### ISSUE TITLE
iplt20.com: nuisance

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#13323]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.iplt20.com/`

### Category

nuisance

### Describe the issue

Partial cookies banners.

### Screenshot(s)

uBO OFF

![Screenshot 2022-05-20 at 23-20-53 IPLT20 com - Indian Premier League Official Website](https://user-images.githubusercontent.com/19629778/169586448-47e75185-7448-4805-bf90-3954de8dac5f.png)

uBO ON

![Screenshot 2022-05-20 at 23-27-58 IPLT20 com - Indian Premier League Official Website](https://user-images.githubusercontent.com/19629778/169586485-7735fd1a-fa61-40c5-9673-7fad40851459.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 109253
  cosmetic: 150759
  scriptlet: 24182
  html: 664
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 27328-907, 3m
    adguard-spyware-url: 603-26, 3m
    adguard-annoyance: 53386-3637, 3m
    fanboy-annoyance: 71175-309, 3m
    ublock-annoyances: 4432-4, 3m
  default: 
    user-filters: 48-1, never
    ublock-filters: 32046-38, 3m
    ublock-badware: 4132-3, 3m
    ublock-privacy: 219-0, 3m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1797-0, 3m
    ublock-quick-fixes: 179-0, 3m
    easylist: 67247-637, 3m
    easyprivacy: 27052-10986, 3m
    urlhaus-1: 8182-0, 3m
    plowe-0: 3671-3, 3m
filterset (user): [array of 50 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 150 redacted]
urlRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 328 ms (selfie)
  maxAssetCacheWait: 445 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    brightcove.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`iplt20.com##.cookie`

@ryanbr
