### ISSUE TITLE
Anti-adblock on dubznetwork.com

### ISSUE THREAD

**Issue by djdelarosa25** [uBlockOrigin/uAssets#13333]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

dubznetwork.com

### Describe the issue

Anti-adblock shows up with default filters + Fanboy Annoyances.

### Screenshot(s)

https://user-images.githubusercontent.com/34760155/169657010-d3ca38cd-c7f6-45ce-acb1-aec5bba4599e.png

### uBlock Origin version

1.42.4

### Browser name and version

Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit)

### Settings

- Enabled Fanboy's Annoyances filter list

**Comment by mapx-** [comment]
It was fixed today. Did you update all the lists before reporting the issue ?
