### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by shinigami052** [uBlockOrigin/uAssets#13338]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/watch/?v=605959550589430`

### Category

ads

### Describe the issue

Video ads play in the middle of the FB Video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82057
  cosmetic: 43358
  scriptlet: 17003
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67151-51, 2d.17h.8m
    easyprivacy: 27041-122, 2d.17h.7m
    plowe-0: 3671-806, 1h.47m
    ublock-abuse: 75-0, 11d.18h.49m
    ublock-badware: 4128-94, 2d.17h.6m
    ublock-filters: 31382-101, 2d.17h.5m
    ublock-privacy: 216-4, 11d.18h.48m
    ublock-quick-fixes: 179-0, 17h.23m
    ublock-unbreak: 1780-41, 2d.17h.4m
    urlhaus-1: 8173-0, 17h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by shinigami052** [comment]
No it's not, I'm not talking about ad posts, I'm talking about ads playing in the middle of videos.

**Comment by mapx-** [comment]
3367 it's about all FB issues 
see for example video ads => https://github.com/uBlockOrigin/uAssets/issues/3367#issuecomment-1111941738
