### ISSUE TITLE
pahe.li: nuisance

### ISSUE THREAD

**Issue by GoodyOG** [uBlockOrigin/uAssets#13337]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pahe.li/love-death-robots-season-1-2/`

### Category

nuisance

### Describe the issue

There is an overlap of ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 83758
  cosmetic: 25332
  scriptlet: 17053
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 28-2, never
    adguard-mobile: 7752-32, 8h.18m
    easylist: 67309-24229, 8h.19m
    easyprivacy: 27055-131, 8h.20m
    plowe-0: 3676-891, 11d.15h.36m
    ublock-abuse: 75-0, 1d.14h.17m
    ublock-badware: 4128-95, 3h.44m
    ublock-filters: 31533-348, 14h.3m
    ublock-privacy: 213-3, 1d.15h.34m
    ublock-quick-fixes: 180-0, 1h.10m
    ublock-unbreak: 1791-43, 8h.21m
    urlhaus-1: 8335-0, 1h.9m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  largeMediaSize: 400
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 312 ms (selfie)
  maxAssetCacheWait: 146 ms
popupPanel: 
  blocked: 9
  no-large-media: true
  no-popups: true
  blockedDetails: 
    pahe.li: 8
    googletagmanager.com: 1
```
</details>

**Comment by krystian3w** [comment]
domain often change public suffix.
