### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by thiopixel** [uBlockOrigin/uAssets#13339]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/F5KEt0M`

### Category

breakage

### Describe the issue

The website begins to load, and shows attributes of the site loading, but then turns grey and will not progress further. Was only able to grab a screenshot of this intermediate screen by using the chrome debugger.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/88973207/169688706-3349bfd8-eab4-4240-84cd-a55b13ca9592.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82342
  cosmetic: 43481
  scriptlet: 17019
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67343-51, 2m
    easyprivacy: 27056-122, 2m
    plowe-0: 3671-806, 2m
    ublock-abuse: 75-0, 2m
    ublock-badware: 4128-95, 2m
    ublock-filters: 31428-107, 2m
    ublock-privacy: 213-2, 1m
    ublock-quick-fixes: 180-0, 1m
    ublock-unbreak: 1786-41, 1m
    urlhaus-1: 8344-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 128 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    imgur.com: 5
    alexametrics.com: 1
    ccgateway.net: 1
    consensu.org: 1
    facebook.net: 1
    google-analytics.com: 1
    media-lab.ai: 1
    quantserve.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
even disabling uBO that page is broken

**Comment by mapx-** [comment]
I guess the real link is

`https://i.imgur.com/F5KEt0M.png`

**Comment by gwarser** [comment]
Works fine here.

**Comment by Maxhawkgt** [comment]
I'm seeing the same issue but it doesn't seem to be a uBlockOrigin issue. I see it in Chrome, Edge, and Firefox, with and without VPN, normal and incognito/private modes.
