### ISSUE TITLE
voeunblock.com: popups

### ISSUE THREAD

**Issue by Voidyx** [uBlockOrigin/uAssets#13334]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://voeunblock.com/`

### Category

popups

### Describe the issue

Sometimes there is a website opening up in a new tab and closing again quickly, but this disturbs browsing the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 84254
  cosmetic: 46986
  scriptlet: 17011
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5768-0, 18h.52m
    easylist: 67173-57, 1d.17h.59m
    easyprivacy: 27040-132, 1d.17h.58m
    plowe-0: 3673-804, 7d.22h.17m
    ublock-abuse: 75-0, 8d.22h.8m
    ublock-badware: 4128-94, 1d.17h.57m
    ublock-filters: 31412-115, 1d.17h.56m
    ublock-privacy: 214-2, 8d.22h.7m
    ublock-quick-fixes: 210-0, 18h.51m
    ublock-unbreak: 1780-42, 1d.17h.55m
    urlhaus-1: 8182-0, 18h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 143 ms (selfie)
  maxAssetCacheWait: 70 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    ads-twitter.com: 1
    artisticbuoyemphasize.com: 1
    gamingadult.com: 1
    l4meet.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
It was fixed 12 hours ago. You didn't update the filter lists and didn't provide a working link for the issue above.
