### ISSUE TITLE
voeunblock.com

### ISSUE THREAD

**Issue by KanasIsReale** [uBlockOrigin/uAssets#13346]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I deactivated all Filters that block voeunblock.com but it still not work because it is still blocked.

### A specific URL where the issue occurs

`www.voeunblock.com`

### Steps to Reproduce

1. I tried to search the Filter and deactivate it and it still didn't worked.
2. After i tried to add it to "My Rules" it still didn't worked
3. So i go to the Report to report it for a bug

### Expected behavior

The the Site doesn't will be blocked anymore

### Actual behavior

It was still blocked

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 70508
  cosmetic: 49299
  scriptlet: 29487
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 9h.41m
    adguard-generic: 63937-665, 15m
    adguard-mobile: 7755-55, 15m
    adguard-spyware: 27330-746, 15m
  default: 
    user-filters: 17-0, never
    DEU-0: 5770-0, 5h.40m
    plowe-0: 3672-275, 8d.20h.34m
    ublock-abuse: 75-0, 31m
    ublock-badware: 4128-234, 9h.44m
    ublock-filters: 31433-3269, 9h.43m
    ublock-privacy: 216-39, 8d.21h.59m
    ublock-quick-fixes: 180-9, 22h.5m
    ublock-unbreak: 1786-73, 9h.42m
    urlhaus-1: 8335-0, 22h.4m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1539 ms (selfie)
  maxAssetCacheWait: 845 ms
```
</details>

**Comment by mapx-** [comment]
- update all your lists and test again
- You have to provide a working link (with a video)
