### ISSUE TITLE
ally.com: breakage

### ISSUE THREAD

**Issue by gbochenek** [uBlockOrigin/uAssets#13344]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ally.com/`

### Category

breakage

### Describe the issue

Clicking login on ally.com does nothing when the adblocker is enabled in Chrome.  I updated all lists and disabled my custom lists, but the issue persists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ad block:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/1930086/169705876-5b895607-a5f2-4d46-b0aa-9a74f3a4a796.png">

Without ad block:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/1930086/169705890-4ce86bfd-97cc-4e40-965d-d397adc3551b.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82246
  cosmetic: 44365
  scriptlet: 17841
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1873-0, 2d.20h.29m
  default: 
    user-filters: 0-0, never
    easylist: 67306-57, 1d.4h.31m
    easyprivacy: 27055-125, 1d.4h.30m
    plowe-0: 3673-804, 6d.30m
    ublock-abuse: 75-0, 6d.28m
    ublock-badware: 4128-95, 1d.4h.34m
    ublock-filters: 31387-113, 1d.4h.33m
    ublock-privacy: 214-3, 6d.29m
    ublock-quick-fixes: 179-0, 1d.4h.29m
    ublock-unbreak: 1786-41, 1d.4h.32m
    urlhaus-1: 8173-0, 1d.4h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 448 ms (selfie)
  maxAssetCacheWait: 345 ms
popupPanel: 
  blocked: 61
  blockedDetails: 
    adobedtm.com: 32
    brightcove.com: 5
    datadoghq.com: 8
    demdex.net: 1
    globalsiteanalytics.com: 2
    go-mpulse.net: 1
    launchdarkly.com: 6
    lr-ingest.io: 1
    omtrdc.net: 1
    techlab-cdn.com: 4
```
</details>

**Comment by mapx-** [comment]
Test and tell me if it's enough

`@@||assets.adobedtm.com/*-libraryCode_source.min.js$script,domain=ally.com`

**Comment by mapx-** [comment]
@ryanbr
