### ISSUE TITLE
canon.fr: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13340]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.canon.fr/support/consumer_products/products/fax__multifunctionals/inkjet/pixma_mg_series/pixma_mg2140.html?type=software&language=&os=windows+10+%2864-bit%29`

### Category

breakage, layer

### Describe the issue

The loading of the OS and drivers selection insert is not done correctly.

After a while, the site displays a layer asking to answer a questionnaire.

### Screenshot(s)

Loading fail
![image](https://user-images.githubusercontent.com/50231020/169696180-0e8ba73d-8ce3-4b21-bcf1-6e45521c3629.png)

Layer
![image](https://user-images.githubusercontent.com/50231020/169696156-83ee1841-7666-49fd-8560-6655d57e3743.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 429975
  cosmetic: 57818
  scriptlet: 29498
  html: 0
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
    easyprivacy: null
    plowe-0: null
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt: 6097-0, 4m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/adguard/anti-antiadb.txt: 326-24, 4m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/no_gen_cosm/phhider.txt: 684-6, 4m
    adguard-generic: 63938-1087, 4m
    adguard-mobile: 7752-71, 4m
    adguard-spyware: 27330-764, 4m
  default: 
    user-filters: 2129-239, never
    easylist: 67343-24871, 4m
    ublock-abuse: 75-0, 4m
    ublock-badware: 4128-298, 4m
    ublock-filters: 31425-3589, 4m
    ublock-privacy: 213-40, 4m
    ublock-quick-fixes: 180-9, 4m
    ublock-unbreak: 1786-83, 4m
    urlhaus-1: 8181-572, 3m
filterset (user): [array of 2058 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 762 ms (selfie)
  maxAssetCacheWait: 626 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    tiqcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
- test using the default settings including the french list, don't add any other list

**Comment by mapx-** [comment]
maybe it's one of your numerous custom filters

`user-filters: 2129-239`

Don't open other issues in the future if you are not testing using the default settings / lists.
