### ISSUE TITLE
aniworld.to: breakage

### ISSUE THREAD

**Issue by Rubyurek** [uBlockOrigin/uAssets#13341]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aniworld.to/`

### Category

breakage

### Describe the issue

"Diese Seite wurde von einer Erweiterung blockiert" when i want to look some streams

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 84320
  cosmetic: 47080
  scriptlet: 17020
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5770-0, 3m
    easylist: 67343-57, 3m
    easyprivacy: 27056-132, 3m
    plowe-0: 3671-807, 3m
    ublock-abuse: 75-0, 3m
    ublock-badware: 4128-95, 3m
    ublock-filters: 31425-116, 3m
    ublock-privacy: 213-2, 3m
    ublock-quick-fixes: 181-0, 3m
    ublock-unbreak: 1786-42, 3m
    urlhaus-1: 8181-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1041 ms
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    yandex.ru: 1
```
</details>

**Comment by Yami-x3** [comment]
same problem :(

**Comment by mapx-** [comment]
bad filter in DEU list

**Comment by Rubyurek** [comment]
which u recommend?

**Comment by mapx-** [comment]
I fixed the issue, see above the commit

**Comment by Rubyurek** [comment]
it works now thanks!

**Comment by yaboku1204** [comment]
How did you fix it? ?

**Comment by BlazeFTL** [comment]
Add in my filters
```
@@||timmaybealready.com^
```
How to Add Custom Filters
Open uBlockOrigin Dashboard: Click uBO icon > Gears ⚙️ > My filters tab > Paste code > Apply changes > Refresh page.

**Comment by yaboku1204** [comment]
where i have to add this ?

**Comment by yaboku1204** [comment]
Found it myself.

**Comment by Yami-x3** [comment]
> How did you fix it? ?
go to the ublock origin Settings -> Filterlists and setup like this:

https://github.com/user-attachments/assets/8b0cd792-eaff-4f83-acdc-23ba21ef40d5

then click Save changes, u can click the all clock-symbols to refresh the lists then it should works again :).
