### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by desouzabrandon** [uBlockOrigin/uAssets#13345]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aternos.org/players/`

### Category

detection

### Describe the issue

A giant red page appears that says adblock has been detected. I can click "continue" or whatever, but it makes me wait 3 seconds. This happens every time I interact with their website, which makes navigating it very cumbersome. I've tried all sorts of ways of bypassing it, with tamper monkey and custom scripts to no avail. I've also tried just the default settings with nothing else enabled (I use opera which has its own adblock and tracker software). Even with having everything disabled except for Ublock, I was still detected. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/63067544/169710119-5697d157-7ad9-4bb1-aacf-0a3288c7fafc.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 110798
  cosmetic: 93784
  scriptlet: 42132
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53400-1713, 18m
    curben-phishing: 13369-0, 18m
    fanboy-annoyance: 71193-34214, 18m
    fanboy-thirdparty_social: 68-20, 8d.1h.21m
    ublock-annoyances: 4422-192, 2d.16h.50m
  default: 
    user-filters: 25818-3368, never
    easylist: 67175-24065, 2d.16h.51m
    easyprivacy: 27045-219, 2d.16h.49m
    plowe-0: 3673-805, 5d.18h.17m
    ublock-abuse: 75-0, 5d.18h.5m
    ublock-badware: 4140-94, 2d.16h.48m
    ublock-filters: 31412-683, 2d.16h.47m
    ublock-privacy: 214-10, 5d.17h.57m
    ublock-quick-fixes: 179-3, 17h.15m
    ublock-unbreak: 1780-48, 2d.16h.46m
    urlhaus-1: 8344-1, 17h.14m
filterset (user): [array of 890 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 529 ms (selfie)
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 2
  no-popups: true
  blockedDetails: 
    aternos.org: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/13144
