### ISSUE TITLE
filmozavr.net: ads

### ISSUE THREAD

**Issue by PonnyHydro** [uBlockOrigin/uAssets#13347]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filmozavr.net/videos/4509/rik-i-morti-rick-and-morty-5-y-sezon-7-ya-seriya/`

### Category

ads

### Describe the issue

pop ups during playback

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 100622
  cosmetic: 65580
  scriptlet: 18366
  html: 0
listset (total-discarded, last updated): 
  added: 
    CZE-0: 710-0, 2m
    RUS-0: 41370-9, 2m
  default: 
    user-filters: 8-3, never
    easylist: 67350-67, 2m
    easyprivacy: 27056-225, 2m
    plowe-0: 3671-811, 2m
    ublock-abuse: 75-1, 2m
    ublock-badware: 4128-95, 2m
    ublock-filters: 31424-136, 2m
    ublock-privacy: 213-2, 2m
    ublock-quick-fixes: 186-0, 2m
    ublock-unbreak: 1790-45, 2m
    urlhaus-1: 8181-0, 2m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 307 ms (selfie)
  maxAssetCacheWait: 356 ms
popupPanel: 
  blocked: 7
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    filmozavr.net: 3
    googletagmanager.com: 1
    pljs.ru: 1
    plrjs.org: 2
```
</details>

**Comment by mapx-** [comment]
add

```
filmozavr.net###pop-up
filmozavr.net##pwa-update
filmozavr.net##[target='_blank']
```

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/19a25f534d90025fc42778fdc4bc9592624d221a
