### ISSUE TITLE
derstandard.at [Anti-Adblock]

### ISSUE THREAD

**Issue by rafuse** [uBlockOrigin/uAssets#1334]
### URL(s) where the issue occurs

`https://derstandard.at/2000072656035/Google-CEO-bereut-es-nicht-Autor-von-sexistischem-Memo-entlassen`

### Describe the issue

On the left side, instead of a picture, an anti-adblock warning is shown.

### Screenshot of the anti-adblock warning

![bildschirmfoto 2018-01-21 um 14 58 00](https://user-images.githubusercontent.com/11586542/35194903-a59f5d46-febb-11e7-8574-4f4ba7979677.png)

### Versions

- Browser/version: Firefox for Mac 57.0.4 
- uBlock Origin version: 1.14.24

### Settings

- Default Settings

**Comment by nimasaj** [comment]
unable to reproduce, this is what I see with default settings:
`https://pasteboard.co/H3Z82AM.png`
Are your filterlists updated?
Can you post your logger data here?

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by mapx-** [comment]
You need an account and an austrian IP.

**Comment by mapx-** [comment]
see `https://derstandard.at/Forum/bundles/js/loader?v=wkbM1knjwH421-dUcZgAXhOMe_TbgBkjMyqS0nu5X-01` script

**Comment by okiehsch** [comment]
That script is about the comment section. specifically the rating of postings, not the removal of pictures as far as I can see.

**Comment by mapx-** [comment]
`js-adblockcampaign, initializeAdblockCampaignTemplate, applyAdblockCampaign, removeAdblockCampaign`

**Comment by okiehsch** [comment]
See my edit.

**Comment by mapx-** [comment]
yeah, I get the issue not only using a vpn

**Comment by okiehsch** [comment]
Well. I cant reliably reproduce, but the problem I have is if I get site with the issue for example
`https://derstandard.at/2000072716078/SPD-stimmt-fuer-Koalitionsverhandlungen-mit-Union-Zittersieg-fuer-Martin-Schulz`
the picture remains removed even if I diasble uBO.

![aufzeichnen](https://user-images.githubusercontent.com/16838044/35198554-d55150fa-fef0-11e7-9123-cc7c3e6f4ea7.JPG)

**Comment by okiehsch** [comment]
Now the same site after I logged out and enabled uBO.

![aufzeichnen1](https://user-images.githubusercontent.com/16838044/35198580-30ebe948-fef1-11e7-9063-1886aecd80db.JPG)

**Comment by mapx-** [comment]
yeah, I get the same but ... if I use the austrian vpn (and uBo disabled) I get the normal page.

**Comment by rafuse** [comment]
Thanks for looking into this issue!

Could it have to do something with cookie settings/cookie addons (like cookie autodelete)?

**Comment by okiehsch** [comment]
I can now reproduce, sometimes, without being logged in and it is cookie based.
If I delete and then block cookies, the issue is fixed on my end.
I do not see a fix, besides blocking cookies, that does not also break the comment section, so maybe somebody else can come up with a workable fix.

**Comment by okiehsch** [comment]
````
|imagesrv.adition.com/js/srp.js$script,redirect=noopjs,domain=derstandard.at
@@||derstandard.at/MetaAdServer/MAS.aspx$xmlhttprequest,first-party
@@||derstandard.at/s/*$image,first-party`
````
works for me, you have to delete the existing cookies if you already get the ant-adblock warning, after that the issue is fixed on my end.
Some feedback would be appreciated.

**Comment by rafuse** [comment]
Works perfectly on my end! 👍 
Thanks a ton for all your effort!
