### ISSUE TITLE
cbssports.com: breakage

### ISSUE THREAD

**Issue by jscott0918** [uBlockOrigin/uAssets#13349]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cbssports.com/golf/pga-championship/live/`

### Category

breakage

### Describe the issue

No video player or controls appear in the video sections.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1908" alt="Screen Shot 2022-05-22 at 3 38 48 PM" src="https://user-images.githubusercontent.com/1441007/169712902-8a428b01-8ee7-43b7-8457-0f52dc28fe68.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82031
  cosmetic: 43123
  scriptlet: 17003
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66876-51, 4d.19h.18m
    easyprivacy: 27038-122, 3d.17h.56m
    plowe-0: 3672-803, 8d.4h.52m
    ublock-abuse: 75-0, 8d.5h.5m
    ublock-badware: 4128-94, 4d.19h.17m
    ublock-filters: 31383-98, 3d.17h.55m
    ublock-privacy: 214-2, 8d.5h
    ublock-quick-fixes: 179-0, 1d.21h.51m
    ublock-unbreak: 1780-41, 3d.17h.54m
    urlhaus-1: 8182-0, 1d.21h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 547 ms (selfie)
  maxAssetCacheWait: 204 ms
popupPanel: 
  blocked: 849
  blockedDetails: 
    cbssports.com: 2
    ads-twitter.com: 1
    adsafeprotected.com: 2
    advertising.com: 1
    agkn.com: 1
    amazon-adsystem.com: 1
    cbsaavideo.com: 5
    cbsi.com: 1
    cbsivideo.com: 13
    cedexis.com: 1
    chartbeat.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    decibelinsight.net: 1
    demdex.net: 2
    doubleclick.net: 1
    facebook.net: 1
    getpublica.com: 1
    go-mpulse.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gstatic.com: 790
    imrworldwide.com: 1
    litix.io: 2
    moatads.com: 1
    mtvnservices.com: 2
    ns1p.net: 3
    plotrabbit.com: 2
    qualtrics.com: 1
    rum.us-east-1.amazonaws.com: 1
    scorecardresearch.com: 3
    taboola.com: 1
    tealiumiq.com: 1
    urbanairship.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||plotrabbit.com^$xhr,domain=cbssports.com`

@ryanbr
