### ISSUE TITLE
dailymotion.com: detection

### ISSUE THREAD

**Issue by Diablo-0** [uBlockOrigin/uAssets#13351]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dailymotion.com/video/x6n5g8i`

### Category

detection

### Describe the issue

I did try using the block element function, but when I did the video wouldn't continue playing, it just kept stopping, I'm currently using Opera GX browser with the most recent update as of this report.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Opera Snapshot_2022-05-22_193343_www dailymotion com](https://user-images.githubusercontent.com/43107370/169720856-a67b1718-9b7d-4adf-b7f4-f512299866d6.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82210
  cosmetic: 43640
  scriptlet: 17020
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 166-1, never
    easylist: 67361-52, 4m
    easyprivacy: 27058-122, 4m
    plowe-0: 3671-806, 4m
    ublock-abuse: 75-0, 4m
    ublock-badware: 4128-95, 4m
    ublock-filters: 31426-106, 4m
    ublock-privacy: 213-2, 4m
    ublock-quick-fixes: 188-0, 4m
    ublock-unbreak: 1790-45, 4m
    urlhaus-1: 8181-0, 4m
filterset (user): [array of 166 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  showIconBadge: false
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8803 ms (selfie)
  maxAssetCacheWait: 500 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    dailymotion.com: 1
    dmcdn.net: 4
    doubleclick.net: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Disable opera's adblock

![image](https://user-images.githubusercontent.com/10303732/169743551-68dcf84e-4d42-47fd-a392-bdef971bd879.png)
