### ISSUE TITLE
[nsfw] next.nexusmods.com: ads

### ISSUE THREAD

**Issue by rourien** [uBlockOrigin/uAssets#13350]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://next.nexusmods.com/skyrimspecialedition/collections`

### Category

ads

### Describe the issue

An ad section is left over on the left side of the page. Adding the following rule fixes it:

`next.nexusmods.com##.lg\:shrink-0.lg\:mr-6.lg\:block.hidden.ad-section__skyscraper`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
before: https://imgur.com/T9v6TGK

after: https://imgur.com/95xKaYe
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82204
  cosmetic: 43486
  scriptlet: 16983
  html: 657
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    ublock-filters: 32035-32, 2m
    ublock-badware: 4132-3, 2m
    ublock-privacy: 219-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1801-4, 2m
    easylist: 67358-606, 2m
    easyprivacy: 27057-579, 2m
    plowe-0: 3671-3, 2m
    urlhaus-1: 8181-0, 2m
    ublock-quick-fixes: 188-0, 2m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 47 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 740 ms
  unsuspendAfter: 301 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    nexusmods.com: 2
    enthusiastgaming.net: 1
    hotjar.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
