### ISSUE TITLE
s.to: breakage

### ISSUE THREAD

**Issue by darmstadt40** [uBlockOrigin/uAssets#13352]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.to/serie/stream/fresh-off-the-boat/staffel-2/episode-7`

### Category

breakage

### Describe the issue

Blocks dance yesterday the first streaming host. Second workey. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 85813
  cosmetic: 28412
  scriptlet: 17001
  html: 658
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32090-281, 4d.3h.14m
    ublock-badware: 4132-3, 4d.3h.14m
    ublock-privacy: 220-1, 4d.3h.14m
    ublock-abuse: 75-0, 4d.3h.14m
    ublock-unbreak: 1796-0, 4d.3h.14m
    ublock-quick-fixes: 186-0, 22h.54m
    adguard-mobile: 7741-178, 4d.3h.13m
    easylist: 67128-24704, 4d.3h.13m
    easyprivacy: 27036-598, 4d.3h.13m
    urlhaus-1: 8344-0, 18h.51m
    plowe-0: 3673-3, 4d.3h.13m
    DEU-0: 5770-379, 22h.52m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 636 ms (selfie)
  maxAssetCacheWait: 279 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    voeunblock.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
Update all your filter lists.
