### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by gaelgar-kallian** [uBlockOrigin/uAssets#13357]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Describe the issue

when on the twitter homepage, most tweets are only the account icon with nothing else. if I go into a tag, tweets seem to appear normally, and if I click on one of the icon-only tweets I can view the tweet that way, though if I want to view replies I have to manually clock on those as well. disabling cosmetic filtering does fix the problem, but it also brings back all the ads. most of the 'what's happening' topics do not appear either except for two. there does not seem to be a pattern to what is visible and what is blocked, as image-only, text-only, image and text and quote retweets have both been affected and visible. I am using firefox 100.0.1 however on chrome the issue doesn't seem to be present, so I don't know if there is something that I'm using on firefox that is interfering, I am a bit of a noob when it comes to digital tech. 

![Photos 23_05_2022 7_37_29 PM (2)](https://user-images.githubusercontent.com/106069290/169789279-6daf92d8-655c-4b94-85be-c235e19c5294.png)
 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Photos 23_05_2022 7_37_29 PM (2)](https://user-images.githubusercontent.com/106069290/169790166-cb4d9a46-2190-4b37-a581-654a230cc17b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82294
  cosmetic: 43515
  scriptlet: 16984
  html: 657
listset (total-discarded, last updated): 
  default: 
    user-filters: 27-3, never
    ublock-filters: 32038-33, 14m
    ublock-badware: 4132-3, 14m
    ublock-privacy: 219-0, 14m
    ublock-abuse: 75-0, 14m
    ublock-unbreak: 1801-0, 14m
    easylist: 67365-606, 14m
    easyprivacy: 27060-580, 14m
    plowe-0: 3671-3, 14m
    urlhaus-1: 8266-0, 13m
    ublock-quick-fixes: 188-4, 13m
filterset (user): [array of 27 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7692 ms (selfie)
  maxAssetCacheWait: 4796 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    twitter.com: 26
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Test keeping only uBO enabled - no other addon

**Comment by Branzeturi** [comment]
Does disabling `"My filters"` in uBlock Origin's do anything?

**Comment by gaelgar-kallian** [comment]
@Branzeturi yes it did! thank you so much
