### ISSUE TITLE
bmovies.to

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#1335]
fmovies.is now redirects to bmovies.to

https://github.com/uBlockOrigin/uAssets/search?&q=fmovies

**Comment by mapx-** [comment]
do you get issues on bmovies ?

see
https://github.com/uBlockOrigin/uAssets/search?&q=bmovies

**Comment by adranger** [comment]
I've reported this because you can delete the old domain. Their frontpage says that this change is permanent.
