### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by coffeelover696969** [uBlockOrigin/uAssets#13364]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=AKUr_CNTdGo`

### Category

ads

### Describe the issue

All of a sudden, after using ublock origin for years, started to receive ads on every youtube video I play. I've tried restarting the browser and restarting the PC. Still ads at the beginning of each video. This didn't happen just last night. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82203
  cosmetic: 43418
  scriptlet: 16993
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67362-51, 16h.16m
    easyprivacy: 27060-122, 16h.17m
    plowe-0: 3672-803, 9d.13h.21m
    ublock-abuse: 75-0, 2d.15h.35m
    ublock-badware: 4128-95, 16h.19m
    ublock-filters: 31424-105, 16h.18m
    ublock-privacy: 214-2, 3d.15h.43m
    ublock-unbreak: 1790-41, 16h.15m
    urlhaus-1: 8266-0, 16h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 169 ms (selfie)
  maxAssetCacheWait: 76 ms
popupPanel: 
  blocked: 202
  blockedDetails: 
    youtube.com: 153
    doubleclick.net: 8
    google.com: 20
    googlesyndication.com: 15
    googlevideo.com: 6
```
</details>

**Comment by mapx-** [comment]
see if helps: https://github.com/easylist/easylist/wiki/Youtube-Issues


duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
