### ISSUE TITLE
us.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by TheSubDex** [uBlockOrigin/uAssets#13369]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=9784&ItemNamePattern=%D0%94%D0%B2%D1%83%D1%80%D1%83%D1%87%D0%BD%D1%8B%D0%B9+%D0%BC%D0%B5%D1%87+%D0%BE%D0%B1%D0%B5%D1%80%D0%B5%D0%B3%D0%B0+%D0%A1%D0%B8%D1%80%D0%BE%D0%B4%D0%B8%D0%BB%D0%B0`

### Category

detection

### Describe the issue

When i am trying to search any items site says "Please disable your adblocker for this site and refresh the page to continue "

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/74463256/169909092-581949b6-a392-45b4-a457-aa7b4b402b04.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 119122
  cosmetic: 153414
  scriptlet: 23099
  html: 683
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 30581-29, 1d.7h.38m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1457-24, 1d.7h.37m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29945-203, 23h.3m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-1, 7d.2h.12m
    fanboy-annoyance: 71104-58915, 6d.5h.10m
    fanboy-cookiemonster: 32097-276, 6d.5h.9m
    fanboy-social: 23406-18290, 23h.5m
    ublock-annoyances: 4432-4, 23h.4m
  default: 
    user-filters: 10-2, never
    ublock-filters: 32035-67, 23h.10m
    ublock-badware: 4132-3, 23h.9m
    ublock-privacy: 219-8, 3d.10h.17m
    ublock-abuse: 75-4, 3d.10h.16m
    ublock-unbreak: 1801-9, 23h.8m
    easylist: 67359-807, 23h.7m
    easyprivacy: 27058-1216, 23h.6m
    urlhaus-1: 8266-0, 11h.22m
    plowe-0: 3671-11, 3d.6h.11m
    RUS-0: 41379-3852, 1d.7h.39m
    ublock-quick-fixes: 188-4, 11h.21m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 465 ms (selfie)
  maxAssetCacheWait: 697 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by hh-100** [comment]
It appears the site relies on the following checks:
`    if (window.adsbygoogle != null && window.adsbygoogle.loaded)`
and
```
            const elements = document.getElementsByClassName("adsbygoogle");
            for (let i = 0; i < elements.length; i++) {
                const element = elements[i];
                if (element.style.display != "none" && element.clientHeight > 0 && element.clientWidth > 0)
                    return AdMode.Full;
            }

```

**Comment by hh-100** [comment]
As a side note, I did read and follow all the pre-requisites of posting a new issue, as opposed to the OP who said "I did not answer truthfully to all the above checkpoints"...

**Comment by kiechb** [comment]
Still an issue, same exact problem. Not sure why someone closed this.

**Comment by HazardTrance** [comment]
Recently this site is again detecting, attempts to use the site search produce the message:
Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed

Posting here, as there is mention in the [related ](us.tamrieltradecentre.com: detection #13427) thread that posts should be made to this original thread.
Thank you.

**Comment by JobcenterTycoon** [comment]
Works fine for me
