### ISSUE TITLE
thelincolnite.co.uk: breakage

### ISSUE THREAD

**Issue by piregg** [uBlockOrigin/uAssets#13360]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://thelincolnite.co.uk/`

### Category

breakage

### Describe the issue

The articles requires clicking a button "READ MORE" to view the article. When clicking this button nothing happens. Disabling  uBlock for this page fixes the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82267
  cosmetic: 43486
  scriptlet: 17024
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 67334-51, 1d.15h.31m
    easyprivacy: 27055-122, 1d.15h.30m
    plowe-0: 3673-804, 6d.18h.12m
    ublock-abuse: 75-0, 7d.19h.36m
    ublock-badware: 4128-95, 1d.15h.29m
    ublock-filters: 31444-106, 1d.15h.28m
    ublock-privacy: 214-2, 7d.19h.35m
    ublock-quick-fixes: 179-0, 2h.19m
    ublock-unbreak: 1786-41, 1d.15h.27m
    urlhaus-1: 8266-0, 2h.18m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 245 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    typekit.net: 1
    webpushr.com: 2
    wp.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`thelincolnite.co.uk#@#.inline-ad`
