### ISSUE TITLE
Torrentz2.eu sponsor banner

### ISSUE THREAD

**Issue by Mirellanmawl** [uBlockOrigin/uAssets#1336]
### URL(s) where the issue occurs

`https://torrentz2.eu/search?f=gNewSense`
`https://torrentz2.eu/0e666384ad77ce8b4aebdae9de8babfc82fbc08e`

### Description of the issue

There is a (banner-like) text on the search and torrent pages on the torrentz2.eu website that says "Your IP:", "Your Location:", "Hide your torrent activity with CyberGhost VPN". Clicking "CyberGhost VPN" links to `https://privacysecurityprotection.com/torrentz2/warning/`, which is a pretty deceptive website as it has fake "Torrent Search" button etc, and the whole thing just feels like a sponsored message with the intent of making people pay for a third-party service (very ad-like, but more surreptitious), using scareware-like tactics.

### Screenshot(s)

Will provide if desired.

### Versions

- Browser/version: Firefox Quantum 57.0.4 (64-bit)
- uBlock Origin version: uBlock Origin 1.14.24

### Settings

- Many third party filters enabled
- Some options of lesser importance

### Notes

Resolved by adding the filter `##.generic`.

**Comment by mapx-** [comment]
@ryanbr

**Comment by Mirellanmawl** [comment]
What was the reason for closing?

**Comment by mapx-** [comment]
such normal filters have to be reported to easylist (easyprivacy) authors 
here:
https://github.com/easylist/easylist/issues
or
http://forums.lanik.us/
