### ISSUE TITLE
jpopsingles.eu: nuisance

### ISSUE THREAD

**Issue by yuukiAme** [uBlockOrigin/uAssets#13363]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jpopsingles.eu/`

### Category

nuisance, detection

### Describe the issue

The site detected ad block with a banner. I zapped the banner. The site in the back are all blurred. Every text and images. Not a screen hover over it, so I could not zap the content of the site if I want to access it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot from 2022-05-23 22-49-45](https://user-images.githubusercontent.com/45681604/169858294-36b4f23d-cef1-4477-90ff-8c90ac4adedd.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 94378
  cosmetic: 165538
  scriptlet: 23669
  html: 664
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53422-4390, now
    adguard-social: 17368-1095, now
    fanboy-thirdparty_social: 69-0, now
    fanboy-annoyance: 71249-55741, now
    fanboy-cookiemonster: 32160-101, now
    fanboy-social: 23406-28, now
    ublock-annoyances: 4434-4, now
  default: 
    user-filters: 10-0, never
    ublock-filters: 32038-47, now
    ublock-badware: 4132-3, now
    ublock-privacy: 220-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1800-2, now
    ublock-quick-fixes: 187-0, now
    easylist: 67379-622, now
    easyprivacy: 27061-587, now
    urlhaus-1: 8352-0, now
    plowe-0: 3671-3, now
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1668 ms (selfie)
  maxAssetCacheWait: 599 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    a-ads.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    h12-media.com: 3
    stripe.com: 12
    wp.com: 2
```
</details>

**Comment by intrnl** [comment]
The blur is affected by this styling

```
body.ntakze-kyesqd-blur > :not(#wpadminbar):not(.ntakze-kyesqd-modal):not(.ntakze-kyesqd-wrapper):not(.ntakze-kyesqd-blackout) {
  -webkit-filter: blur(5px);
  filter: blur(5px);
}
```

As for the adblock check itself, it seems to be checking if it can:
- fetch `https://googleads.g.doubleclick.net/pagead/id` (Opera-only)
- inject `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` (all other browsers)

For the latter, it checks if `window.adsbygoogle` is present after injecting, and it also does an extra XHR to see if it was "redirected" (`callback(request.responseURL !== adsSrc)`)
