### ISSUE TITLE
quora.com never loads and says an error has occurred. Console log indicates it's clashing with some antiadblock.

### ISSUE THREAD

**Issue by oherman** [uBlockOrigin/uAssets#13368]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.quora.com/?__nsrc__=4&__snid3__=36895278643&scheduled_email_story=65294107`

### Category

breakage

### Describe the issue

quora.com never loads and says an error has occurred. Disabling ublock origin will make it work. Console log indicates it's clashing with some antiadblock on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/4970522/169900093-4362cb6a-f626-4fb1-b74a-5ae28ede83f2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82269
  cosmetic: 43389
  scriptlet: 17014
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 18h.23m
  default: 
    user-filters: 5-0, never
    easylist: 67181-53, 2d.22h.26m
    easyprivacy: 27050-122, 2d.22h.27m
    plowe-0: 3672-803, 6d.22h.32m
    ublock-abuse: 75-0, 8d.7h.17m
    ublock-badware: 4128-94, 2d.22h.25m
    ublock-filters: 31415-104, 2d.22h.23m
    ublock-privacy: 214-2, 8d.7h.18m
    ublock-quick-fixes: 180-0, 18h.25m
    ublock-unbreak: 1785-41, 2d.22h.24m
    urlhaus-1: 8344-0, 18h.24m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 957 ms (selfie)
  maxAssetCacheWait: 424 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Branzeturi** [comment]
Are there any other extensions in `chrome://extensions/` ?
