### ISSUE TITLE
goplay.be: detection

### ISSUE THREAD

**Issue by adriaan1313** [uBlockOrigin/uAssets#13366]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.goplay.be/video/de-mol/de-mol-s10/de-mol-finale-de-rode-loper` Note: probably also geoblocked
`https://www.goplay.be/video/de-mol/de-mol-s10/de-mol-s10-aflevering-9`

### Describe the issue

When trying to watch the video, the page will show: 
"Zo te zien staat je adblocker nog aan.
Adblocker uitschakelen op goplay.be"
translated: 
"Looks like your adblocker is still on.
Disable adblocker on goplay.be"

Sometimes, it shows the "Schakel je ad blocker uit om deze video te kunnen bekijken." message from issue 13246

### Screenshot(s)

Original image ↓
![image](https://user-images.githubusercontent.com/19620346/169885148-38db1cad-5366-4f52-aa62-73acd58f7c56.png)

Image with new profile/disabling all other extensions ↓
![image](https://user-images.githubusercontent.com/19620346/169885649-f4e330f0-2720-4b46-81f3-8e391fdf9861.png)

### Notes

https://www.goplay.be/themes/custom/drupack/public/resources/js/global.js?v=9.3.2 seems to detect that you're using an adblocker (I assume, because it console.logs it), but blocking that just breaks everything

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 71980
  cosmetic: 45130
  scriptlet: 17283
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    urlhaus-1: null
  added: 
    http://cdn.jsdelivr.net/gh/NanoAdblocker/NanoFilters@master/NanoMirror/NanoDefender.txt: 2625-1, now
    http://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 863-18, now
    https://cdn.jsdelivr.net/gh/NanoAdblocker/NanoFilters@master/NanoFilters/NanoBase.txt: 416-0, now
  default: 
    user-filters: 47-0, never
    easylist: 67386-70, now
    easyprivacy: 27060-128, now
    plowe-0: 3671-806, now
    ublock-abuse: 75-0, now
    ublock-filters: 31429-142, now
    ublock-privacy: 214-2, now
    ublock-quick-fixes: 187-2, now
    ublock-unbreak: 1789-43, now
filterset (user): [array of 47 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    edge-scheme
    opera-scheme
    vivaldi-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 488 ms (selfie)
  maxAssetCacheWait: 197 ms
```
</details>

**Comment by mapx-** [comment]
Enable this regional list and test again

`NLD: EasyDutch`

**Comment by adriaan1313** [comment]
hm, i could swear it worked without like a week ago

**Comment by JohnyP36** [comment]
> hm, i could swear it worked without like a week ago

That was true. But since goplay.be is a dutch (language) domain the rules are moved to our list.
