### ISSUE TITLE
dashboard.streetlib.com: breakage

### ISSUE THREAD

**Issue by smatzis** [uBlockOrigin/uAssets#13372]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dashboard.streetlib.com/analytics`

### Category

breakage

### Describe the issue

Webpage does load when ublock origin is disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82205
  cosmetic: 43387
  scriptlet: 17016
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67182-51, 4d.1h.24m
    easyprivacy: 27052-122, 4d.1h.23m
    plowe-0: 3677-804, 12d.5h.5m
    ublock-abuse: 75-0, 12d.5h.3m
    ublock-badware: 4128-94, 4d.1h.22m
    ublock-filters: 31417-104, 4d.1h.21m
    ublock-privacy: 216-4, 12d.4h.59m
    ublock-quick-fixes: 188-0, 1d.3h.10m
    ublock-unbreak: 1786-41, 4d.1h.20m
    urlhaus-1: 8266-0, 23h.9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 183 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@ryanbr
