### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by otherside1** [uBlockOrigin/uAssets#13370]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Top left add is still their

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-05-23 6 43 57 PM](https://user-images.githubusercontent.com/94060774/169916492-2d27855a-9af0-4125-a659-dd7bc1f30112.png)\

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 151176
  cosmetic: 1
  scriptlet: 36153
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53388-46269, 3d.45m
    adguard-generic: 63931-32612, 3d.45m
    adguard-mobile: 7752-6052, 3d.45m
    adguard-social: 17332-16752, 3d.45m
    adguard-spyware: 27327-1106, 3d.45m
    adguard-spyware-url: 603-13, 3d.45m
    block-lan: 43-0, 3d.45m
    curben-phishing: 13367-0, 5h.16m
    curben-pup: 252-0, 5h.15m
    dpollock-0: 10368-229, 3d.45m
    fanboy-annoyance: 71175-62934, 3d.45m
    fanboy-cookiemonster: 32103-32103, 3d.45m
    fanboy-social: 23400-23400, 3d.45m
    fanboy-thirdparty_social: 68-21, 3d.45m
    ublock-annoyances: 4424-1392, 3d.45m
  default: 
    user-filters: 6-2, never
    easylist: 67247-35626, 3d.45m
    easyprivacy: 27052-10844, 3d.45m
    plowe-0: 3671-1325, 3d.45m
    ublock-abuse: 75-1, 3d.45m
    ublock-badware: 4128-697, 3d.45m
    ublock-filters: 31438-10356, 3d.45m
    ublock-privacy: 213-50, 3d.45m
    ublock-quick-fixes: 188-75, 5h.14m
    ublock-unbreak: 1786-299, 3d.45m
    urlhaus-1: 8352-1, 5h.13m
filterset (user): [array of 6 redacted]
trustedset: 
  removed: 
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  largeMediaSize: 1000
  parseAllABPHideFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6681 ms
  maxAssetCacheWait: 3656 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    youtube.com: 12
    doubleclick.net: 2
    google.com: 1
    ytimg.com: 1
```
</details>

**Comment by Branzeturi** [comment]
Do you have any other ad blocker (Can you take a look at `chrome://extensions/` ?)?
Also, did you visit the website immediately after opening the browser?

**Comment by Branzeturi** [comment]
Also, this could've been reported in https://github.com/uBlockOrigin/uAssets/issues/13370 instead of making creating another ticket.

**Comment by otherside1** [comment]
No I do have another add blocker and this was not immediately after opening chrome

**Comment by Branzeturi** [comment]
![for uAssets issue](https://user-images.githubusercontent.com/106122341/169919488-524a6777-f49f-4cf1-9c01-693d9d2df6d4.png)
Do you see something similar to what is highlighted in the attached screenshot?

**Comment by otherside1** [comment]
Nope
![Screenshot 2022-05-23 7 24 43 PM](https://user-images.githubusercontent.com/94060774/169920083-230269d6-5761-41f6-91aa-f65990f2c047.png)

**Comment by Branzeturi** [comment]
Can you open a fresh instance of `https://www.youtube.com/` in your browser?

**Comment by otherside1** [comment]
ok

**Comment by otherside1** [comment]
![Screenshot 2022-05-23 7 33 16 PM](https://user-images.githubusercontent.com/94060774/169920617-14b49faa-5d9a-4359-be79-d0452f125d39.png)

**Comment by Branzeturi** [comment]
I saw a `YouTube TV` ad after disabling cosmetic filtering

**Comment by otherside1** [comment]
Turning on cosmetic filtering worked thank you :)

**Comment by Branzeturi** [comment]
You're welcome. I only commented https://github.com/uBlockOrigin/uAssets/issues/13370#issuecomment-1135228255 to find out whether you had cosmetic filtering disabled.

**Comment by krystian3w** [comment]
All = all => #7636
