### ISSUE TITLE
enbdev.com: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13374]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://enbdev.com/`

### Category

detection

### Describe the issue

An image appears informing us that an ad blocker has been detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/170012275-03e45d59-754b-463e-a498-1afbf4082559.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 114357
  scriptlet: 29550
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 27681-3277, 1d.17h.28m
    easylist: 67350-25095, 1d.17h.28m
    ublock-abuse: 75-1, 1d.17h.28m
    ublock-badware: 4128-303, 1d.17h.28m
    ublock-filters: 31425-3610, 1d.17h.28m
    ublock-privacy: 213-39, 1d.17h.28m
    ublock-quick-fixes: 188-9, 17h.6m
    ublock-unbreak: 1790-86, 1d.17h.28m
    urlhaus-1: 8352-0, 17h.4m
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 845 ms (selfie)
  maxAssetCacheWait: 490 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    enbdev.com: 1
```
</details>

**Comment by ghajini** [comment]
Antiadblock

```
window.onload = function () {
    if (window.isexistAd === undefined) {
        var div = document.createElement("div");
        div.id = "blocknotify";
        div.className = "main_adbalert";
        div.style.visibility = "visible";
        div.style.textAlign = "center";
        div.innerHTML = "<b>Ad blocker detected!</b><br><img src='_main_abkalarm.gif'><br>ENBSeries project is actively developed thanks to the banners on this web site and the donations<br>By blocking the banners you <b>reduce</b> the time that could be spent on ENBSeries<br><img src='_main_abkalarm2.gif'><br>";
        if (!(null == document.body)) {
            var s = document.body.firstChild;
            s.parentNode.insertBefore(div, s);
        }
    }
}
```

**Comment by mapx-** [comment]
I get no anti adb, FF / chrome / brave , european / us ip

**Comment by okiehsch** [comment]
We can block the script, I get it on my end too and blocking it can't hurt.

**Comment by mapx-** [comment]
mmhmm anti adb only if block `http://enbdev.com/_google_ads.js`

**Comment by ghajini** [comment]
its reproducible on my end in firefox android with default settings

**Comment by mapx-** [comment]
well, we can "fix" it if someone can reproduce it

**Comment by ghajini** [comment]
Like this

![Screenshot_20220525-003831-741.png](https://user-images.githubusercontent.com/20338483/170113622-5813d24c-2201-4fde-8c15-9cd87eb3051a.png)

what functionalities are hampered btw with this antiadb warning? iam no regular visiter of this website
