### ISSUE TITLE
eloism.net: detection

### ISSUE THREAD

**Issue by mahmoudsawaby** [uBlockOrigin/uAssets#13373]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://eloism.net/-116781EIVW/VJR7?rndad=3308692219-1653387253`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/94251044/170011196-cca67afd-8322-4215-8880-cd888e22a861.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82226
  cosmetic: 43475
  scriptlet: 17019
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 67282-51, 3d.1h.59m
    easyprivacy: 27052-122, 3d.1h.58m
    plowe-0: 3671-806, 3d.2h.2m
    ublock-abuse: 75-0, 3d.2h.1m
    ublock-badware: 4128-94, 3d.1h.57m
    ublock-filters: 31436-105, 3d.1h.56m
    ublock-privacy: 213-2, 3d.2h
    ublock-quick-fixes: 188-0, 23h.54m
    ublock-unbreak: 1786-41, 3d.1h.55m
    urlhaus-1: 8266-0, 23h.52m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195 ms (selfie)
  maxAssetCacheWait: 126 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  no-popups: true
  blockedDetails: 
    eloism.net: 4
    d1a3jb5hjny5s4.cloudfront.net: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your lists
