### ISSUE TITLE
watchthekingofqueens.com: detection

### ISSUE THREAD

**Issue by sfasih** [uBlockOrigin/uAssets#13387]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watchthekingofqueens.com/episode-watch/the-king-of-queens-6x20/`

### Category

detection

### Describe the issue

The website detects uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 92306
  cosmetic: 44725
  scriptlet: 19909
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 12h.57m
    dpollock-0: 10369-0, now
    ublock-annoyances: 4426-6, 2m
  default: 
    user-filters: 0-0, never
    easylist: 67372-296, 12h.54m
    easyprivacy: 27063-240, 12h.55m
    plowe-0: 3671-1202, now
    ublock-abuse: 75-0, 8h.49m
    ublock-badware: 4128-97, 12h.52m
    ublock-filters: 31383-108, 12h.53m
    ublock-privacy: 214-2, 4m
    ublock-quick-fixes: 190-1, 12h.50m
    ublock-unbreak: 1789-44, 12h.56m
    urlhaus-1: 8300-0, 12h.51m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 234 ms (selfie)
  maxAssetCacheWait: 134 ms
popupPanel: 
  blocked: 8
  no-popups: true
  blockedDetails: 
    ads-twitter.com: 1
    adskeeper.com: 1
    dejectioninvention.com: 1
    flagmantensity.com: 1
    imasdk.googleapis.com: 1
    sortyrails.com: 1
    statcounter.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
No issue here, test using only the default settings / filter lists.

Why using `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt` ?
If you get issues while visiting shopping sites just report them here.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/170197434-1765c4e3-bc57-4ac0-9972-63487502b025.png)

The highlighted request causes the detection, it is not blocked with a default setup,

**Comment by mapx-** [comment]
- Reset uBO to default settings (no other filter list)
- update all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by sfasih** [comment]
Thank you! Much appreciated!
