### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by PhillipeBrosard** [uBlockOrigin/uAssets#1338]
github.com/uBlockOrigin

Your efforts to develop uBlock Origin are appreciated, but basically uBlock Origin is useless, as it doesn't actually block ads reliably. Is uBlock Origin still in beta? You should only release software to the public that actually works. A piece of software with a great concept, but that doesn't actually work is just useless. You should stop trying to develop uBlock Origin since you're obviously incompetent, and let a real software developer with talent, who knows what they're doing take over your project instead. Maybe you would be better suited working at something else that you'd be better at. Have a nice day. Thanks.

Waterfox 56.0.3
uBlock Origin 1.14.24

**Comment by uBlock-user** [comment]
Another useless issue moaning about uBO not working...
