### ISSUE TITLE
nypost.com: breakage

### ISSUE THREAD

**Issue by cmcken1** [uBlockOrigin/uAssets#13385]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nypost.com/`

### Category

breakage

### Describe the issue

Breaks log in process. User is unable to log in when U-Block is enabled and generates error in red print by the website. When U-Block is disabled, user is logged in without issue. 

When U-Block plug-in is enabled, website logs user out of account while displaying "Log In" as if user is logged out / not logged in:
Sample 1. PLUG IN <ENABLED>
![New_York_Post_–_Breaking_News__Top_Headlines__Photos___Videos_-_Vivaldi](https://user-images.githubusercontent.com/54412746/170136035-5181e98d-bee8-437e-84aa-2e4ef6780e08.png)

Sample 2. PLUG IN <ENABLED> 
Upon attempting to log in, breakage occurs when plug-in is engaged resulting in the following error message:
![Log_In_-_New_York_Post_-_Vivaldi](https://user-images.githubusercontent.com/54412746/170134074-2fb93d2f-8a3f-4d47-a8b0-ed6c083b28af.png)

Sample 3. PLUG IN <DISABLED>
Disable U-Block, Reload website. Website auto logs user in as expected and shows user account is logged in as expected.
![New_York_Post_–_Breaking_News__Top_Headlines__Photos___Videos_-_Vivaldi](https://user-images.githubusercontent.com/54412746/170135002-a56d9b5c-c483-4f5a-8518-4c1fe445de93.png)

 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 82261
  cosmetic: 43403
  scriptlet: 16992
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67282-51, 3d.15h.30m
    easyprivacy: 27052-122, 3d.15h.29m
    plowe-0: 3672-803, 10d.22h.52m
    ublock-abuse: 75-0, 3d.23h.18m
    ublock-badware: 4128-94, 3d.15h.28m
    ublock-filters: 31438-105, 3d.15h.27m
    ublock-privacy: 213-2, 3d.23h.17m
    ublock-unbreak: 1785-41, 3d.15h.26m
    urlhaus-1: 8387-0, 17h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 206 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    nypost.com: 3
    adlightning.com: 1
    amazon-adsystem.com: 1
    bounceexchange.com: 1
    d1z2jf7jlzjs58.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    newscgp.com: 1
    p-n.io: 1
    permutive.app: 1
    scorecardresearch.com: 1
    sentry.io: 3
    speedcurve.com: 1
    spot.im: 2
    unrulymedia.com: 1
    videoplayerhub.com: 1
    vidora.com: 1
    wp.com: 1
    zqtk.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`||nypost.com/blaize/$badfilter`

@ryanbr
