### ISSUE TITLE
Page not finish load when block element

### ISSUE THREAD

**Issue by GamezUzer** [uBlockOrigin/uAssets#13395]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`www.brasil247.com##.swg-dialog`

### Describe the issue

Page not show, stay grey, no finish load

### uBlock Origin version

1.42.4

### Browser name and version

Chrome Lastet stable version

### Settings

```
true=Ocultar espaços ocupados por elementos bloqueados

true=Mostrar o número de solicitações bloqueadas no ícone

true=Utilizar o menu de contexto onde apropriado

true=Ativar suporte de armazenamento na nuvem 
Privacidade

true=Desativar serviço de previsão (para prevenir qualquer solicitação de redes bloqueadas) 

true=Desativar auditoria em hyperlinks 

true=Bloquear relatórios CSP 

false=Revelar nomes canônicos 
Comportamento padrão
Estes comportamentos padrões podem ser substituídos por site 

false=Desativar filtragem cosmética 

false=Bloquear elementos de mídia maiores que 50 KB 

false=Bloquear fontes remotas 

false=Desativar JavaScript 

```

**Comment by mapx-** [comment]
go into options, dashboard, support tab, `Troubleshooting Information` section, copy the info and paste it here

**Comment by GamezUzer** [comment]
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 154051
  cosmetic: 205941
  scriptlet: 36488
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 9h.24m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 4d.28m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-11, 4d.27m
    adguard-annoyance: 53401-218, 2d.22h.12m
    adguard-generic: 63938-757, 2d.22h.11m
    adguard-mobile: 7757-102, 2d.22h.10m
    adguard-social: 17367-878, 2d.6h.3m
    adguard-spyware: 26302-1035, 2d.6h.2m
    adguard-spyware-url: 606-13, 5h.36m
    block-lan: 43-0, 6d.1h.32m
    dpollock-0: 10368-1458, 8d.9h.39m
    fanboy-annoyance: 71104-4148, 7d.9h.18m
    fanboy-cookiemonster: 32103-32097, 4d.23h.47m
    fanboy-social: 23406-23378, 2d.6h
    fanboy-thirdparty_social: 68-21, 4d.29m
    ublock-annoyances: 4429-226, 5h.33m
  default: 
    user-filters: 34-1, never
    easylist: 67366-1252, 2d.6h.1m
    easyprivacy: 27089-10670, 5h.35m
    plowe-0: 3673-1479, 8d.7h.29m
    spa-1: 4502-103, 5h.34m
    ublock-abuse: 75-0, 4d.9h.18m
    ublock-badware: 4128-305, 2d.22h.15m
    ublock-filters: 31424-3719, 2d.22h.14m
    ublock-privacy: 213-47, 2d.22h.17m
    ublock-quick-fixes: 189-13, 9h.23m
    ublock-unbreak: 1790-105, 2d.22h.13m
    urlhaus-1: 8366-0, 9h.22m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 435 ms (selfie)
  maxAssetCacheWait: 545 ms

**Comment by mapx-** [comment]
- reset uBO to default settings / filter lists
- don't add any other list
- disable any other extension
- update all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- test again
