### ISSUE TITLE
oggi.it: detection

### ISSUE THREAD

**Issue by lukepass** [uBlockOrigin/uAssets#13393]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.oggi.it/`

### Category

detection

### Describe the issue

A popup forcing to disable uBlock Origin appears. Thanks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/6429961/170239060-6f67180f-5819-46f2-b98e-96d59a7c6e49.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 88010
  cosmetic: 50816
  scriptlet: 17020
  html: 0
listset (total-discarded, last updated): 
  added: 
    ITA-0: 13024-0, 19h.38m
  default: 
    user-filters: 0-0, never
    easylist: 67372-55, 19h.39m
    easyprivacy: 27060-124, 2d.2h.11m
    plowe-0: 3671-807, 2d.2h.12m
    ublock-abuse: 75-0, 7d.20h.27m
    ublock-badware: 4128-96, 2d.2h.10m
    ublock-filters: 31427-113, 2d.2h.9m
    ublock-privacy: 214-2, 7d.20h.26m
    ublock-quick-fixes: 187-2, 21h.58m
    ublock-unbreak: 1790-45, 2d.2h.8m
    urlhaus-1: 8300-0, 19h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 156 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    oggi.it: 2
    adsafeprotected.com: 1
    amazon-adsystem.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    corriereobjects.it: 2
    crazyegg.com: 1
    d2bnxibecyz4h5.cloudfront.net: 1
    doubleclick.net: 1
    facebook.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    imasdk.googleapis.com: 2
    imrworldwide.com: 2
    insurads.com: 1
    permutive.app: 1
    rcs.it: 1
    rcsmetrics.it: 2
    rcsobjects.it: 4
    seedtag.com: 1
    taboola.com: 1
    tiqcdn.com: 1
```
</details>

**Comment by Branzeturi** [comment]
video player seemed to be broken with uBO enabled on `https://www.oggi.it/people/famiglie-reali/2022/05/25/charlene-wittstock-solo-il-fratello-minore-gareth-puo-salvarla-ecco-perche/`
