### ISSUE TITLE
torrentstatus.top: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13391]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://torrentstatus.top/extratorrent`

### Category

popups

### Describe the issue

popups(adfpoint) when clicked anywhere or on sections like clicking torrentz2,limetorrents etc
race condition with scriptlets
also popunders

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.5rc0
Firefox: 100
filterset (summary): 
  network: 82721
  cosmetic: 44754
  scriptlet: 19932
  html: 667
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4434-6, 43m
  default: 
    user-filters: 40-0, never
    ublock-filters: 32081-54, 43m
    ublock-badware: 4132-3, 43m
    ublock-privacy: 220-0, 43m
    ublock-abuse: 75-0, 43m
    ublock-unbreak: 1800-2, 43m
    ublock-quick-fixes: 189-0, 43m
    easylist: 67398-611, 43m
    easyprivacy: 27088-580, 43m
    urlhaus-1: 8366-0, 43m
    plowe-0: 3671-3, 43m
filterset (user): [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1621 ms (selfie)
  maxAssetCacheWait: 799 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    addthis.com: 1
    adfpoint.com: 1
    amung.us: 2
    rablinhiphape.com: 1
```
</details>

**Comment by ghajini** [comment]
```
torrentstatus.*##+js(aopw, afStorage)
torrentstatus.*,yts2.*,y2mate.*##+js(acis, Math, XMLHttpRequest)
```

Other sites
```
torrentstatus.top
yts2.cc
y2mate.uno
```

**Comment by mapx-** [comment]
test

```
torrentstatus.top##+js(nosiif, Click)
torrentstatus.top##+js(nowoif)
```

**Comment by mapx-** [comment]
`extratorrent.*,torrentstatus.top##+js(nosiif, Click)`

**Comment by ghajini** [comment]
i still get adfpoint popup(blocked by EL)

opera/firefox

**Comment by mapx-** [comment]
does this work ? (and removing nosiif)

`extratorrent.*,torrentstatus.*,yts2.cc##+js(aopw, afStorage)`

**Comment by ghajini** [comment]
yes work
alongwith

`torrentstatus.*,yts2.*,y2mate.*##+js(aopr, mm)`
or
`torrentstatus.*,yts2.*,y2mate.*##+js(acis, Math, XMLHttpRequest)`

**Comment by mapx-** [comment]
still needing `torrentstatus.*,yts2.*,y2mate.*##+js(aopr, mm)`
 ?

**Comment by ghajini** [comment]
yes not everytime it gets served, intermittently
