### ISSUE TITLE
adidas.fr: breakage

### ISSUE THREAD

**Issue by ErnestPietryka** [uBlockOrigin/uAssets#13397]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.adidas.fr/`

### Category

breakage

### Describe the issue

Impossible to access account page with uBlock Origin activated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1904" alt="Capture d’écran 2022-05-25 143945" src="https://user-images.githubusercontent.com/51130381/170264005-32b6d46f-5038-4d64-88a6-52b938219242.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 138243
  cosmetic: 147436
  scriptlet: 30916
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 63938-1131, 3d.11h.15m
    adguard-social: 17332-30, 3d.11h.15m
    adguard-spyware: 27330-767, 3d.11h.15m
    adguard-spyware-url: 603-13, 3d.11h.15m
    block-lan: 43-0, 2d.17h.24m
    fanboy-cookiemonster: 32113-85, 2d.17h.21m
    fanboy-social: 23406-1077, 2d.17h.20m
    fanboy-thirdparty_social: 68-21, 2d.17h.19m
  default: 
    user-filters: 0-0, never
    FRA-0: 27681-24, 3d.11h.15m
    easylist: 67350-995, 2d.17h.23m
    easyprivacy: 27056-10977, 2d.17h.22m
    plowe-0: 3671-887, 2d.17h.18m
    ublock-abuse: 75-1, 2d.17h.17m
    ublock-badware: 4128-305, 2d.17h.15m
    ublock-filters: 31424-3401, 2d.17h.14m
    ublock-privacy: 213-47, 2d.17h.13m
    ublock-quick-fixes: 190-9, 15h.2m
    ublock-unbreak: 1786-92, 2d.17h.11m
    urlhaus-1: 8300-0, 15h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 328 ms (selfie)
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    instana.io: 2
```
</details>

**Comment by mapx-** [comment]
add

`adidas.fr#@#.cookie-consent-modal___14Zeo`

@ryanbr

**Comment by andiwunder** [comment]
Still an issue

**Comment by mapx-** [comment]
I updated the cookies for adidas, but what issue / breakage are you talking about ? provide more details
