### ISSUE TITLE
pages.emails.bbc.com: breakage

### ISSUE THREAD

**Issue by dannwebb** [uBlockOrigin/uAssets#13390]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://pages.emails.bbc.com/subscribe/?ocid=ear.bbc.email.we.email-signup`

### Category

breakage

### Describe the issue

Input field to subscribe is blocked. Disabling uBlock Origin and reloading fixes the issue. Re-enabling uBlock Origin blocks the subscription field again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82320
  cosmetic: 43491
  scriptlet: 17019
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.5h.59m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 7-1, never
    easylist: 67361-51, 2d.5h.57m
    easyprivacy: 27058-122, 2d.5h.56m
    plowe-0: 3671-806, 2d.6h
    ublock-abuse: 75-0, 9d.6h.5m
    ublock-badware: 4128-95, 2d.5h.54m
    ublock-filters: 31424-105, 2d.5h.53m
    ublock-privacy: 214-2, 9d.6h.4m
    ublock-quick-fixes: 187-0, 5h.49m
    ublock-unbreak: 1790-45, 2d.5h.55m
    urlhaus-1: 8300-0, 5h.50m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1853 ms (selfie)
  maxAssetCacheWait: 374 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    exacttarget.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||exacttarget.com/page.aspx$frame,domain=pages.emails.bbc.com`

@ryanbr

**Comment by dannwebb** [comment]
where?
(sorry, new user, reading a lot but not absorbing much yet)
