### ISSUE TITLE
twitch-tools.rootonline.de: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#13392]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitch-tools.rootonline.de/channel_previews.php`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>

https://user-images.githubusercontent.com/81616288/170225473-11eefe73-a64e-4dd6-8168-490234ac2e64.jpeg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 84605
  cosmetic: 47092
  scriptlet: 17048
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5772-0, 1h.41m
    easylist: 67398-56, 1h.41m
    easyprivacy: 27088-132, 1h.41m
    plowe-0: 3671-807, 1h.41m
    ublock-abuse: 75-0, 1h.41m
    ublock-badware: 4128-96, 1h.41m
    ublock-filters: 31470-117, 1h.41m
    ublock-privacy: 214-2, 1h.41m
    ublock-quick-fixes: 189-2, 1h.41m
    ublock-unbreak: 1789-45, 1h.41m
    urlhaus-1: 8366-0, 1h.41m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3097 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    d2v02itv0y9u9t.cloudfront.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`twitch-tools.rootonline.de##[rel*="sponsored"]`

@ryanbr @monzta
