### ISSUE TITLE
fuckadblock surrogate fails on FuckAdBlock 4.0.0-beta.3

### ISSUE THREAD

**Issue by Halibut80** [uBlockOrigin/uAssets#134]
<a href="http://filmix.net/">site for example</a>

<a href="http://filmix.net/templates/Filmix/media/js/settings/fuckadblock.js">script link</a>

**Comment by quilloss** [comment]
The site defines `var fuckAdBlock = undefined;`. This causes the redirected script to throw `TypeError: can't redefine non-configurable property "fuckAdBlock"`. Perhaps `window.hasOwnProperty('fuckAdBlock')` would be a better check of whether `fuckAdBlock` is defined.

**Comment by gorhill** [comment]
@quilloss thanks for investigating.
