### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Daqtoillo** [uBlockOrigin/uAssets#13401]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=xgJNeDik2lU&list=PL9KviB6Up8IldgnwGOe7zYeXKUFIGJ-ZY&index=5`

### Category

ads

### Describe the issue

still ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 82665
  cosmetic: 48714
  scriptlet: 16872
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8805-138, never
    easylist: 65018-167, never
    easyprivacy: 26734-100, never
    plowe-0: 3690-811, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-109, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-29, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10333 ms
  maxAssetCacheWait: 125 ms
popupPanel: 
  blocked: 81
  blockedDetails: 
    youtube.com: 64
    doubleclick.net: 5
    google.com: 1
    googlesyndication.com: 8
    googlevideo.com: 3
```
</details>

**Comment by mapx-** [comment]
could help => https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate: https://github.com/uBlockOrigin/uAssets/issues/7636
