### ISSUE TITLE
amartfurniture.com.au: breakage

### ISSUE THREAD

**Issue by nivinj** [uBlockOrigin/uAssets#13406]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amartfurniture.com.au/living-room/lounges/home-theatre-lounges/?cgid=living-room-lounges-hometheatre&prefn1=numberOfSeats&prefv1=4`

### Category

breakage

### Describe the issue

When uBO is on, search filtering options along the left (e.g. price range, number of seats) don't work. Suspect AJAX callbacks are being blocked incorrectly. When a filter is applied, a loading spinner shows indefinitely.

Repeating the same action with uBO off immediately shows the filtered results.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 74044
  cosmetic: 43475
  scriptlet: 17023
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 1-0, never
    easylist: 67368-51, 1d.19h.39m
    easyprivacy: 27061-122, 1d.19h.38m
    plowe-0: 3671-806, 2d.12h.30m
    ublock-abuse: 75-0, 3d.2h.34m
    ublock-badware: 4128-96, 1d.19h.37m
    ublock-filters: 31432-106, 1d.19h.36m
    ublock-privacy: 213-2, 3d.2h.33m
    ublock-quick-fixes: 189-1, 2h.59m
    ublock-unbreak: 1789-43, 1d.19h.35m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 1622 ms (selfie)
  maxAssetCacheWait: 708 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    amartfurniture.com.au: 1
    cquotient.com: 1
    googletagmanager.com: 1
    igodigital.com: 1
    maps.googleapis.com: 1
    pingdom.net: 1
    trustpilot.com: 3
    visualwebsiteoptimizer.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||widget.trustpilot.com/bootstrap/$script,domain=amartfurniture.com.au`

@ryanbr
