### ISSUE TITLE
stellen.donaukurier.de: breakage

### ISSUE THREAD

**Issue by mekabar** [uBlockOrigin/uAssets#13400]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stellen.donaukurier.de/stellenanzeigen/DK104381.html`

### Category

breakage

### Describe the issue

The button "Jetzt bewerben" (apply for a job offer) does not work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 102626
  cosmetic: 71990
  scriptlet: 19893
  html: 664
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 24881-3, 2d.18h.39m
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 4d.22h.46m
    dpollock-0: 10368-1632, 5d.9h.57m
    ublock-annoyances: 4434-4, 1d.10h.31m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32042-48, 1d.10h.29m
    ublock-badware: 4132-4, 1d.10h.30m
    ublock-privacy: 220-0, 1d.10h.33m
    ublock-unbreak: 1797-0, 1d.10h.28m
    easylist: 67386-872, 1d.18h.35m
    easyprivacy: 27060-877, 1d.18h.34m
    plowe-0: 3673-348, 7d.15h.19m
    DEU-0: 5772-3, 10h.24m
    ublock-abuse: 75-0, 1d.10h.32m
    urlhaus-1: 8366-0, 10h.23m
    ublock-quick-fixes: 189-0, 10h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 357 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    donaukurier.de: 3
    cdntrf.com: 2
    googletagmanager.com: 1
    iocnt.net: 1
    maps.googleapis.com: 1
    matomo.cloud: 1
    opencmp.net: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||stellen.donaukurier.de/Scripts/ApiTracking.js$script,1p`
