### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by PhillipeBrosard** [uBlockOrigin/uAssets#1341]
github.com/uBlockOrigin

Most websites are able to detect that you're using an adblocker despite keeping the filter lists updated in uBlock Origin. Also, the filter lists for uBlock Origin that are supposed to be able to get rid of the adblocker detected warning on different websites, keep changing names, so it's hard to know which one to install.

When those websites detect that you're using an adblocker, don't let you view the website properly unless you disable your adblocker, and the filter lists for uBlock Origin don't work, then uBlock Origin is basically useless.

Why doesn't uBlock Origin just come pre-installed with all the necessary filter lists automatically configured by default, and update those filter lists automatically, so that it's easier for users to use it?

So many times users have to post new issues on github.com because uBlock Origin doesn't work properly, to ask for fixes, and then they have to put those fixes in the customization settings of uBlock Origin themselves, which basically means that they have to do all the work themselves to make uBlock Origin work properly, which you should be doing instead because it's your program that's supposed to block ads properly, so why don't you make an adblocker that actually works reliably? Is uBlock Origin still in beta? You should fix uBlock Origin, because otherwise people will just use other alternatives. Have a nice day. Thanks.

Waterfox 56.0.3
uBlock Origin 1.14.24

**Comment by nimasaj** [comment]
Sorry Phillipe, you can bring your bill to get your money back; or you can open an issue for those websites which uBO doesn't work on to be fixed.
