### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by dummifiedme** [uBlockOrigin/uAssets#13416]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=kb6hhhfBo-M&list=PL2jzazaAMNtXispAP7pNNQSn9Bj84D1f7&index=2`

### Category

ads

### Describe the issue

Earlier I was using Brave ad blocker by default unknowingly along with uBlock and never experienced any issue with youtube. 
Recently, being a long term user of uBlock, I switched off the Brave adBlocker. I now notice that ads are frequent before the video. I tried finding a setting which could tackle it but couldn't fix it.

Attaching a screenshot as well. As you can see, the blocker is on, but the ad still loads up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/68785729/170538717-58f7f942-cc8d-497d-852b-d6035b97d559.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82348
  cosmetic: 43498
  scriptlet: 17018
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 67387-51, 2d.20h.47m
    easyprivacy: 27060-122, 2d.20h.46m
    plowe-0: 3671-806, 3d.14h.25m
    ublock-abuse: 75-0, 3d.14h.28m
    ublock-badware: 4128-96, 2d.20h.50m
    ublock-filters: 31426-105, 2d.20h.49m
    ublock-privacy: 213-2, 3d.14h.27m
    ublock-quick-fixes: 187-2, 23h.6m
    ublock-unbreak: 1789-43, 2d.20h.48m
    urlhaus-1: 8311-0, 23h.7m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10092 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    youtube.com: 18
    google.co.in: 1
    google.com: 4
    googlesyndication.com: 1
    googlevideo.com: 3
```
</details>

**Comment by mapx-** [comment]
could help => https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate: https://github.com/uBlockOrigin/uAssets/issues/7636
