### ISSUE TITLE
neoteric.eu: [unknown]

### ISSUE THREAD

**Issue by BanijaDev** [uBlockOrigin/uAssets#13418]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://neoteric.eu/blog/6-best-successful-pwa-examples/`

### Category

[unknown]

### Describe the issue

Anti-adblock notice

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20220527-015223_Kiwi Browser](https://user-images.githubusercontent.com/97141433/170556964-7ad13da9-3786-44a4-a47e-126cc3c71cd2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 85702
  cosmetic: 156715
  scriptlet: 24459
  html: 0
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6415-1, 3d.13h.44m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 3410-11, 3d.14h.22m
    adguard-annoyance: 53529-191, 54m
    fanboy-annoyance: 71193-3007, 4d.8h.28m
    ublock-annoyances: 4449-207, 55m
  default: 
    user-filters: 0-0, never
    easylist: 67363-105, 3d.14h.19m
    easyprivacy: 27094-219, 8h.18m
    ublock-abuse: 75-0, 2d.4h.55m
    ublock-badware: 4128-93, 3d.14h.21m
    ublock-filters: 31542-537, 3d.14h.20m
    ublock-privacy: 214-9, 2d.4h.54m
    ublock-quick-fixes: 190-4, 8h.17m
    ublock-unbreak: 1795-52, 3d.14h.28m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2593 ms (selfie)
  maxAssetCacheWait: 1882 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    getsitecontrol.com: 1
    googletagmanager.com: 2
    optimole.com: 1
```
</details>

**Comment by mapx-** [comment]
fixed as annoyance in `uBlock filters – Annoyances` it's not a blocking issue
