### ISSUE TITLE
apkmirror.com: [unknown]

### ISSUE THREAD

**Issue by BanijaDev** [uBlockOrigin/uAssets#13413]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.apkmirror.com/apk/google-inc/arcore/arcore-1-31-2210202-release/`

### Category

[unknown]

### Describe the issue

Pop up banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220526-203445_Kiwi Browser](https://user-images.githubusercontent.com/97141433/170498433-87cc2b0e-e06b-414d-92c0-e9859c7cdd05.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium Mobile: 101
filterset (summary): 
  network: 85695
  cosmetic: 156602
  scriptlet: 24449
  html: 0
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6415-1, 3d.8h.26m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 3410-11, 3d.9h.5m
    adguard-annoyance: 53398-190, 3d.20h.47m
    fanboy-annoyance: 71193-3006, 4d.3h.10m
    ublock-annoyances: 4446-207, 3d.20h.48m
  default: 
    user-filters: 0-0, never
    easylist: 67363-105, 3d.9h.1m
    easyprivacy: 27094-219, 3h
    ublock-abuse: 75-0, 1d.23h.37m
    ublock-badware: 4128-93, 3d.9h.4m
    ublock-filters: 31542-535, 3d.9h.3m
    ublock-privacy: 214-9, 1d.23h.36m
    ublock-quick-fixes: 190-4, 2h.59m
    ublock-unbreak: 1795-52, 3d.9h.10m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2295 ms (selfie)
  maxAssetCacheWait: 1666 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    cloudflareinsights.com: 1
    crsspxl.com: 1
    google.com: 4
    googlesyndication.com: 1
    googletagmanager.com: 1
    instant.page: 1
    pro-market.net: 1
    quantserve.com: 1
    scorecardresearch.com: 1
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`apkmirror.com##.apkm-timed-slider`
