### ISSUE TITLE
amcplus.com

### ISSUE THREAD

**Issue by 89z** [uBlockOrigin/uAssets#13417]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.amcplus.com/shows/orphan-black/episodes/season-1-instinct--1011152`

### Describe the issue

Did you forget to turn your ad-blocker off? Turn it off so you can access this content. Error Code: 403_AD_BLOCKED

### uBlock Origin version

*

### Browser name and version

*

### Settings

*

**Comment by mapx-** [comment]
- without an account nothing to do
- however the "error" reminds me of another similar site, just a try => test this filter

`@@||amcplus.com^$ghide`

**Comment by 89z** [comment]
Yes that does work. If you want, I can send you login privately. However I can confirm that filter fixes the problem.

**Comment by mapx-** [comment]
it's ok, I added the filter to our list

**Comment by 89z** [comment]
Thank you!
