### ISSUE TITLE
sbofficial.in ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#13425]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sbofficial.in/fantastic-beasts-3`

### Describe the issue

banner ads,amazon  promotions

### Screenshot(s)

https://user-images.githubusercontent.com/20338483/170673746-8835f183-4744-4b36-a5b2-a9fa0e57d72c.png

### uBlock Origin version

1.42.4

### Browser name and version

firefox android stable

### Settings

Default

### Notes

```
sbofficial.in##[href^="https://amzn.to/"]
sbofficial.in##[href^="https://link.upstox.com/"]
```

**Comment by mapx-** [comment]
stuff for easylist

@ryanbr
