### ISSUE TITLE
anydebrid.com: detection

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#13423]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://anydebrid.com/`

### Category

detection

### Describe the issue

I verified that the issue still occurs without enabling external filter lists *

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/170664247-5344e534-28c2-4524-bc2c-af1a3bbef014.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 375701
  cosmetic: 99863
  scriptlet: 19647
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt: 213267-0, 15m
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt: 97609-39, 14m
    CHN-0: 28865-7451, 22m
    adguard-annoyance: 53543-289, 21m
  default: 
    easylist: 67540-16800, 20m
    easyprivacy: 27100-12782, 19m
    plowe-0: 3673-3101, 6d.23h.53m
    ublock-abuse: 75-1, 6d.23h.56m
    ublock-badware: 4128-563, 18m
    ublock-filters: 31519-705, 17m
    ublock-privacy: 213-29, 6d.23h.55m
    ublock-quick-fixes: 183-5, 12m
    ublock-unbreak: 1789-48, 16m
    urlhaus-1: 8328-645, 13m
filterset (user): [array of 185044 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1154 ms (selfie)
  maxAssetCacheWait: 824 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adnxs.com: 4
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 after i clicked "get premium link" i need to wait until the 3 fake waiting times are done but after this i just get this
<details>
<img width="474" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/178569261-47cdd722-63a3-4651-a17c-17225ff892b6.PNG">
</details>
Also the "blog" is just a content farm

Do anyone get the same behavior? (to bypass the anti adb add `||tags.creativecdn.com/uy0qcdwAfwU7AhDORUmm.js$script,redirect-rule=noopjs,domain=anydebrid.com|hotdebrid.com` )
