### ISSUE TITLE
us.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by kiechb** [uBlockOrigin/uAssets#13427]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://us.tamrieltradecentre.com/pc/Trade`

### Category

detection

### Describe the issue

Same exact issue as " us.tamrieltradecentre.com: detection #13369 " which was closed, despite the issue not being fixed. Do not see a way to reopen.

Detects adblock, prevents interaction with search terms+site until disabled. Specifies that it uses Google ads and that message will remain if anything affects interaction with google ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 88984
  cosmetic: 107584
  scriptlet: 21882
  html: 665
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
  added: 
    adguard-spyware: 26332-866, 2h.3m
    adguard-spyware-url: 607-14, 2h.3m
    fanboy-thirdparty_social: 69-0, 2h.3m
    fanboy-annoyance: 71393-55790, 2h.3m
    fanboy-cookiemonster: 32290-87, 2h.3m
    fanboy-social: 23409-28, 2h.3m
    ublock-annoyances: 4438-4, 2h.3m
  default: 
    user-filters: 12-0, never
    ublock-filters: 32142-48, 2h.3m
    ublock-badware: 4137-3, 2h.3m
    ublock-privacy: 228-0, 2h.3m
    ublock-abuse: 75-0, 2h.3m
    ublock-unbreak: 1803-1, 2h.3m
    easylist: 67564-633, 2h.3m
    urlhaus-1: 8376-0, 2h.3m
    plowe-0: 3668-3, 2h.3m
    ublock-quick-fixes: 189-0, 2h.3m
filterset (user): [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 151 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    paypalobjects.com: 2
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
> detection https://github.com/uBlockOrigin/uAssets/issues/13369 " which was closed, despite the issue not being fixed

It was closed because in that moment it was fixed 

Don't open in the future other issue, just add another comment (in the closed thread) and we'll see it.

**Comment by Yuki2718** [comment]
It was fixed and the site updated anti-adb (possibly responded to our fixes), it's just that and is all happening on such sites.

**Comment by osogrande99** [comment]
### 

1. > 

- [ ] [](`_**@https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext**_`)

**Comment by kiechb** [comment]
Ah, I see. That would seem correct, as it's no longer working again this morning (10am PST at least maybe earlier), so they are hell-bent on making it anti-ad.

**Comment by Yuki2718** [comment]
Yes, they monitor us. Now they removed doubleclick check and instead sees if .adsbygoogle has 2x2 size. @piquark6046 exclude `tamrieltradecentre.com` too from ins.adsbygoogle.

**Comment by piquark6046** [comment]
@Yuki2718 Pushed.

**Comment by kiechb** [comment]
Thanks. Confirmed worked great last night. It is back to being circumvented again, now has an infinitely-loading "checking for adblock" message.

**Comment by kiechb** [comment]
Worked flawlessly almost all weekend. It is back to circumventing as of Monday night.

**Comment by Branzeturi** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13501#issuecomment-1142729843

**Comment by HazardTrance** [comment]
Recently this site is again detecting, attempts to use the site produce the message: 
Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed

**Comment by kiechb** [comment]
> Recently this site is again detecting, attempts to use the site produce the message: Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed

I also had this issue beginning a couple weeks ago. However-- It was fully resolved by purging caches and re-updating filter lists. Did you try that first?

**Comment by HazardTrance** [comment]
Yes.  The Prerequisites were considered (to the best of my ability) prior to posting about the issue with the site.
