### ISSUE TITLE
hindutamil.in: nuisance

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#13421]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hindutamil.in/`

### Category

nuisance

### Describe the issue

cookie policy banner

### Screenshot(s)

![Screenshot 2022-05-27 at 13-45-31 இந்து தமிழ் திசை News in Tamil Latest Tamil News India   World Cinema Hindu Tamil Thisai Daily Newspaper Online தமிழால் இணைவோம்](https://user-images.githubusercontent.com/19629778/170660132-8c29a267-f957-489a-88be-5e6aa5be908f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 109064
  cosmetic: 151158
  scriptlet: 24268
  html: 665
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 26320-864, now
    adguard-spyware-url: 607-25, now
    adguard-annoyance: 53543-3652, now
    fanboy-annoyance: 71345-295, now
    ublock-annoyances: 4438-4, now
  default: 
    user-filters: 37-0, never
    ublock-filters: 32139-40, now
    ublock-badware: 4132-3, now
    ublock-privacy: 228-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1803-1, now
    ublock-quick-fixes: 183-0, now
    easylist: 67540-630, now
    easyprivacy: 27100-10654, now
    urlhaus-1: 8328-0, now
    plowe-0: 3671-3, now
filterset (user): [array of 39 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 156 redacted]
urlRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms (selfie)
  maxAssetCacheWait: 1327 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    hindutamil.in: 8
    clarity.ms: 1
    doubleclick.net: 12
    fwcdn2.com: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    scorecardresearch.com: 1
    sentry.io: 2
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
> cookie policy banner

I see no such banner.
However such annoyances have to be reported at adguard / easylist repositories
