### ISSUE TITLE
mail.yahoo.com: ads

### ISSUE THREAD

**Issue by YesTrustMe** [uBlockOrigin/uAssets#13439]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yahoo.com/d/folders/6?.src=ym&reason=desktop`

### Category

ads

### Describe the issue

Not preventing ads 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 125545
  cosmetic: 114389
  scriptlet: 24280
  html: 667
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 26334-902, 3m
    adguard-spyware-url: 607-14, 3m
    curben-phishing: 13373-2, 3m
    curben-pup: 255-0, 3m
    adguard-annoyance: 53467-4600, 3d.10h.47m
    adguard-social: 17444-1664, 3m
    fanboy-thirdparty_social: 69-1, 3m
    fanboy-annoyance: 71175-59735, 8d.7h.28m
    fanboy-cookiemonster: 32160-15085, 5d.11h.7m
    fanboy-social: 23409-13635, 1d.8h.35m
    ublock-annoyances: 4454-7, 3d.10h.46m
  default: 
    user-filters: 8-1, never
    ublock-filters: 32182-294, 3d.10h.49m
    ublock-badware: 4132-3, 1d.8h.37m
    ublock-privacy: 228-1, 1d.9h.31m
    ublock-abuse: 75-0, 1d.9h.30m
    ublock-unbreak: 1808-1, 1d.8h.36m
    adguard-mobile: 7763-172, 3d.10h.50m
    easylist: 67398-24780, 3d.10h.48m
    easyprivacy: 27089-10668, 3d.10h.45m
    urlhaus-1: 9328-0, 3m
    plowe-0: 3671-3, 1d.8h.38m
    ublock-quick-fixes: 184-0, 9h.19m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1104 ms
  maxAssetCacheWait: 543 ms
popupPanel: 
  blocked: 68
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    yahoo.com: 45
    advertising.com: 1
    akamaized.net: 1
    d1vl8wytztdz.cloudfront.net: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    innovid.com: 2
    llnwd.net: 1
    oath.com: 1
    scorecardresearch.com: 1
    yahoo.net: 3
    yahoodns.net: 7
    yimg.com: 3
```
</details>

**Comment by mapx-** [comment]
Does help ?

`mail.yahoo.com##[data-test-id="video-container"]`

**Comment by krystian3w** [comment]
IMO we can hide text above video:

```adb
##DIV[data-test-id="efv-subheader"]:has(:upward(1) ~ DIV[data-test-id="video-container"])
```

Some of legacy:
```adb
||s.yimg.com/rx/builds/*/iframe-controller-page.html$domain=mail.yahoo.com
mail.yahoo.com###messageListContainer DIV[class]:has(~ DIV#video-player > IFRAME)
mail.yahoo.com##div[data-test-id="virtual-list"] > UL > LI.p_a:style(position: static !important)
```
