### ISSUE TITLE
atomohd.net: nuisance

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#13431]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://atomohd.net/`

### Category

nuisance

### Describe the issue

popups at random, sometimes when you click a link you open a popup ad, overlays...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 85659
  cosmetic: 48377
  scriptlet: 17299
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 67547-50, 21h.5m
    easyprivacy: 27101-122, 21h.5m
    plowe-0: 3671-806, 21h.5m
    spa-0: 3890-35, 21h.5m
    spa-1: 4503-169, 21h.5m
    ublock-abuse: 75-0, 21h.5m
    ublock-badware: 4128-96, 21h.5m
    ublock-filters: 31528-150, 21h.5m
    ublock-privacy: 222-2, 21h.5m
    ublock-quick-fixes: 187-2, 21h.5m
    ublock-unbreak: 1792-43, 21h.5m
    urlhaus-1: 8328-0, 21h.5m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1381 ms (selfie)
  maxAssetCacheWait: 254 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    atomohd.net: 1
    cdnativepush.com: 2
    celeritascdn.com: 1
    chinlesufer.com: 1
    d2q9y3krdwohfj.cloudfront.net: 3
    denetsuk.com: 1
    inpage-push.com: 1
    jomtingi.net: 6
    latcoy.com: 1
    offerimage.com: 2
    rndskittytor.com: 1
    rtmark.net: 8
    ugroocuw.net: 2
```
</details>

**Comment by mapx-** [comment]
fixed 12 hours ago, update your lists.
