### ISSUE TITLE
13tv.co.il: detection

### ISSUE THREAD

**Issue by motorbreth** [uBlockOrigin/uAssets#13437]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://13tv.co.il/live/`

### Category

detection

### Describe the issue

website detects an ad blocker and doesnt play the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 128035
  cosmetic: 203383
  scriptlet: 35790
  html: 0
listset (total-discarded, last updated): 
  added: 
    ISR-0: 1622-0, now
    adguard-annoyance: 53584-175, now
    adguard-generic: 64234-692, now
    adguard-mobile: 7773-51, now
    adguard-social: 17444-855, now
    curben-phishing: 13373-0, now
    curben-pup: 255-0, now
    fanboy-annoyance: 71485-4157, now
    fanboy-cookiemonster: 32372-32372, now
    fanboy-social: 23411-23411, now
    fanboy-thirdparty_social: 68-21, now
    ublock-annoyances: 4430-222, now
  default: 
    user-filters: 0-0, never
    easylist: 67583-900, now
    easyprivacy: 27106-347, now
    plowe-0: 3671-904, 5d.1h.3m
    ublock-abuse: 75-0, 5d.1h.5m
    ublock-badware: 4139-306, now
    ublock-filters: 31458-3670, now
    ublock-privacy: 213-10, 5d.1h.6m
    ublock-quick-fixes: 189-21, now
    ublock-unbreak: 1794-85, now
    urlhaus-1: 9328-2, now
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2683 ms (selfie)
  maxAssetCacheWait: 1229 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    brandmetrics.com: 1
    cooladata.com: 1
    crowdad.io: 1
    doubleclick.net: 3
    go-mpulse.net: 1
    googletagmanager.com: 1
    permutive.com: 1
    taboola.com: 1
```
</details>

**Comment by Branzeturi** [comment]
Is an Israeli IP address required or ... ?

**Comment by mapx-** [comment]
@motorbreth I tested on a video not on live (I get a message ..)

`https://13tv.co.il/item/entertainment/the-big-brother/season-04/aritcles/coswm-903061986/`

Test these filters:
```
13tv.co.il#@#+js(abort-on-property-read, TextDecoder)
@@||www3.doubleclick.net^$xhr,domain=13tv.co.il
```

**Comment by Branzeturi** [comment]
@mapx- what about using `redirect-rule` instead of the network exception filter?

**Comment by mapx-** [comment]
in this case is working for firefox too

**Comment by mapx-** [comment]
@EasyListHebrew

**Comment by motorbreth** [comment]
yes israeli ip is requierd

**Comment by motorbreth** [comment]
> 13tv.co.il#@#+js(abort-on-property-read, TextDecoder)
> ||doubleclick.net^$xhr,domain=13tv.co.il,redirect-rule=nooptext

worked

**Comment by Branzeturi** [comment]
@mapx- https://github.com/easylist/EasyListHebrew/commit/c1c685c2ff092c3f272607058d8130400bcff9f1
