### ISSUE TITLE
[nsfw] applive.co.in: ads

### ISSUE THREAD

**Issue by Hassa2404** [uBlockOrigin/uAssets#13434]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://applive.co.in/i.html`

### Category

ads

### Describe the issue

2 Small horizontal ad windows are appearing in the bottom right corner of the screen in this webpage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 82377
  cosmetic: 24344
  scriptlet: 16475
  html: 634
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31155-277, never
    ublock-badware: 3993-3, never
    ublock-privacy: 210-1, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1759-0, never
    ublock-quick-fixes: 139-4, never
    adguard-mobile: 7773-172, 8m
    easylist: 65018-24408, never
    easyprivacy: 26734-585, never
    urlhaus-1: 8896-0, never
    plowe-0: 3690-2, never
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 646 ms
  maxAssetCacheWait: 282 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Yuki2718** [comment]
> Small horizontal ad windows are appearing in the bottom right corner of the screen in this webpage

Not sure what you mean. I only see Sexy Video Call popup which seems to be all of this site.
