### ISSUE TITLE
dubznetwork.com: detection

### ISSUE THREAD

**Issue by LolFish42** [uBlockOrigin/uAssets#13447]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://dubznetwork.com/meet/racing/formula-1-monaco-grandprix-raceday-2022/`

### Category

detection

### Describe the issue

The website recognises the usage of an adblocker, and puts up a screen asking for it to be disabled. Says "we only use clean banners", which isn't the case as it lags the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/25848455/170871972-f6f62eba-423f-426f-92eb-46d1e56dd3b3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 83700
  cosmetic: 43620
  scriptlet: 17103
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 67575-50, 1d.2h.5m
    easyprivacy: 27106-122, 1d.2h.3m
    plowe-0: 3668-806, 21h.2m
    ublock-abuse: 75-0, 21h
    ublock-badware: 4133-96, 1d.2h.7m
    ublock-filters: 31586-95, 1d.2h.4m
    ublock-privacy: 222-2, 21h.1m
    ublock-quick-fixes: 189-2, 20m
    ublock-unbreak: 1792-42, 1d.2h.6m
    urlhaus-1: 9446-0, 21m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8340 ms (selfie)
  maxAssetCacheWait: 3431 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    dubznetwork.com: 2
    avplayer.com: 1
    doubleclick.net: 1
    google-analytics.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
    greeter.me: 3
    histats.com: 2
    taboola.com: 1
    udmserve.net: 1
    underdog.media: 1
    vlitag.com: 1
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists

Try updating them
