### ISSUE TITLE
Domain directive wildcard issue

### ISSUE THREAD

**Issue by crssi** [uBlockOrigin/uAssets#1344]
### URL(s) where the issue occurs
[https://drive.google.com/file/d/1beg-GcVOi8iYu1UrUg98BmFRJQzCAVMc/view](https://drive.google.com/file/d/1beg-GcVOi8iYu1UrUg98BmFRJQzCAVMc/view)

### Describe the issue
Open URL, hour glass is working endlessly, where the page should load normally.
When `@@||content.googleapis.*^$subdocument,domain=drive.google.*` is changed to `@@||content.googleapis.*^$subdocument,domain=drive.google.com` then there is no issues.
Note: pay attention to wildcard on the `domain` directive.

### Versions

- Browser/version: Firefox 57.0.4 (x64)
- uBlock Origin version: 1.14.24

### Settings
`||$third-party,subdocument`
`@@||content.googleapis.*^$subdocument,domain=drive.google.*`

### Notes
If this is a intentional feature, then, please, accept the apology for non-intended spam.

Cheers

**Comment by mapx-** [comment]
could you force an update of your lists and test again ?

**Comment by gorhill** [comment]
`domain=drive.google.*` is not a valid `domain` directive: the `domain.*` form is only allowed in [static extended filtering](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering), not in static network filtering.

**Comment by crssi** [comment]
I see. Shame.

@gorhill thank you
