### ISSUE TITLE
eu.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by Dorennor** [uBlockOrigin/uAssets#13440]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eu.tamrieltradecentre.com/pc/Trade`

### Category

detection

### Describe the issue

The site detects a blocker and when you go to the page of an item or when searching, it displays a message about this and the page, as well as the data that should be on it, is not loaded further.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![photo_2022-05-29_00-48-35](https://user-images.githubusercontent.com/40647609/170843878-f54718aa-a24a-4826-affe-25ed7bea7955.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 99163
  cosmetic: 63991
  scriptlet: 17670
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41424-154, never
    easylist: 65018-167, never
    easyprivacy: 26734-100, never
    plowe-0: 3690-811, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-97, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-29, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2132 ms
  maxAssetCacheWait: 16 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    facebook.com: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    paypalobjects.com: 1
    twitter.com: 1
```
</details>

**Comment by Branzeturi** [comment]
Could you update the enabled-by-default filter lists?

**Comment by Dorennor** [comment]
I did the following: cleared the cache, updated - did not help. Set the default settings - did not help. Then I cleared the cache again and updated - I checked the site, it still gives a message about the detection.

**Comment by Branzeturi** [comment]
Does adding `tamrieltradecentre.com##+js(no-fetch-if, doubleclick)` fix this?

**Comment by Dorennor** [comment]
This works, but only when I click on an item or search, when I am already on the page in the displayed items and click on a specific item-lot, the detailed information page should open and the same message appears there again.
For example https://eu.tamrieltradecentre.com/pc/Trade/Detail/665923903, detail page.

**Comment by Branzeturi** [comment]
Is `||syndication.twitter.com/i/$image,redirect-rule=2x2.png,domain=eu.tamrieltradecentre.com` a good filter?

**Comment by Dorennor** [comment]
Found the reason. After two edits that you gave, everything works and there are no errors, but there remains a huge field where advertising should have been. If you try to select an element and create a rule using the blocker menu, the error starts popping up again. In general, if you do not remove this field, even without a syndication.twitter, it almost always works without a detection message.

![image](https://user-images.githubusercontent.com/40647609/170844366-adde3967-a2b9-4ab1-be09-de0d2de2d240.png)

**Comment by Branzeturi** [comment]
Does adding `eu.tamrieltradecentre.com##.glass-panel > .inpage.adsbygoogle` cause any issues with any `eu.tamrieltradecentre.com` web page?

**Comment by Dorennor** [comment]
It works with search and items list pages but on detail page it give detection message.

**Comment by Dorennor** [comment]
> 

tamrieltradecentre.com###search-result-view > .inpage.adsbygoogle - this give detection message on any page, such as search and item lists.
tamrieltradecentre.com##.glass-panel > .inpage.adsbygoogle - works but on detail page detection.

**Comment by WizardShotTheFood** [comment]
I'm having the same issue on us.tamrieltradecentre.com.

**Comment by Branzeturi** [comment]
Is `@@||googleads.g.doubleclick.net/pagead/ads$subdocument,domain=us.tamrieltradecentre.com` a good filter?
