### ISSUE TITLE
apkmirror.com: detection

### ISSUE THREAD

**Issue by UserNameA1** [uBlockOrigin/uAssets#13448]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.apkmirror.com/apk/braintrapp/ampere/ampere-v3-55-release/ampere-v3-55-android-apk-download/`

### Category

detection

### Describe the issue

apkmirror.com is able to decect ublock origin
I use Firefox 100.0.2 on Linux with uBlock Origin 1.42.4
uBlock Origin is set with default settings

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![apkmirror-detection](https://user-images.githubusercontent.com/29185143/170872547-5988ca84-ac0b-42ae-85a2-b07ee48079ad.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 85898
  cosmetic: 47155
  scriptlet: 17064
  html: 659
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32123-52, 4m
    ublock-badware: 4143-3, 4m
    ublock-privacy: 228-0, 4m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1833-0, 3m
    ublock-quick-fixes: 190-0, 3m
    easylist: 67598-604, 3m
    easyprivacy: 27110-589, 3m
    urlhaus-1: 9446-0, 3m
    plowe-0: 3669-3, 3m
    DEU-0: 5774-2, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1165 ms
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    cloudflareinsights.com: 2
    crsspxl.com: 1
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    instant.page: 1
    pro-market.net: 2
    quantserve.com: 1
    scorecardresearch.com: 1
    wp.com: 2
```
</details>

**Comment by Branzeturi** [comment]
Are these
```
apkmirror.com#@#.gooWidget:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px)
apkmirror.com#@#.ains
apkmirror.com##.advertisement-text
```
good filters?
