### ISSUE TITLE
[nsfw] upvideo.to: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13442]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://upvideo.to/v/pa2xxpa4bdg8`

### Category

detection

### Describe the issue

The problem was previously reported and fixed in 2021, but apparently the problem is back.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/170846893-b4c96758-17f1-44ac-ab0c-46ba63fca6e1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 114660
  scriptlet: 29633
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easyprivacy: null
    plowe-0: null
  added: 
    adguard-generic: 64234-1504, now
    adguard-mobile: 7773-67, now
    adguard-spyware: 26334-750, now
  default: 
    FRA-0: 27698-3277, now
    easylist: 67589-25148, now
    ublock-abuse: 75-1, now
    ublock-badware: 4139-310, now
    ublock-filters: 31459-3628, now
    ublock-privacy: 222-40, now
    ublock-quick-fixes: 191-18, now
    ublock-unbreak: 1794-83, now
    urlhaus-1: 9328-0, now
filterset (user): [array of 2067 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 828 ms (selfie)
  maxAssetCacheWait: 442 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ghajini** [comment]
can't reproduce plus a non-default config

**Comment by mapx-** [comment]
no anti adb: test using default settings, disable brave adblocker / shields on site
