### ISSUE TITLE
[nsfw] highload.to: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13441]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://highload.to/f/r9al9vko9kld`

### Category

breakage

### Describe the issue

The display is not correct, the player is stuck on the right side of the image.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/170845892-9ada68ee-37ec-46b0-9842-a5e4b1a80cba.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 114528
  scriptlet: 29646
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easyprivacy: null
    plowe-0: null
  added: 
    adguard-generic: 64173-1503, 2d.10h.50m
    adguard-mobile: 7769-67, 2d.10h.50m
    adguard-spyware: 26318-750, 2d.10h.50m
  default: 
    FRA-0: 27698-3277, 2d.10h.50m
    easylist: 67456-25116, 2d.10h.50m
    ublock-abuse: 75-1, 2d.10h.50m
    ublock-badware: 4128-304, 2d.10h.50m
    ublock-filters: 31505-3634, 2d.10h.50m
    ublock-privacy: 222-40, 2d.10h.50m
    ublock-quick-fixes: 192-10, 10h.8m
    ublock-unbreak: 1789-83, 2d.10h.50m
    urlhaus-1: 9328-0, 10h.6m
filterset (user): [array of 2069 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 676 ms (selfie)
  maxAssetCacheWait: 462 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
even disabling uBO I get same position, video playing fine.
