### ISSUE TITLE
livejournal.com: ads

### ISSUE THREAD

**Issue by meongu** [uBlockOrigin/uAssets#13445]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.livejournal.com/`

### Category

ads

### Describe the issue

Ads appear one or two seconds after page finishes loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Web capture_29-5-2022_125414_www livejournal com](https://user-images.githubusercontent.com/22195331/170854325-e5392d92-28e3-4e1d-b77d-ea0e322dd2ff.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 99182
  cosmetic: 44797
  scriptlet: 17668
  html: 0
listset (total-discarded, last updated): 
  added: 
    VIE-1: 1824-0, 3h.23m
    adguard-spyware: 26331-669, 1d.12h.26m
  default: 
    user-filters: 1-0, never
    easylist: 67564-91, 1d.12h.24m
    easyprivacy: 27101-10280, 1d.12h.23m
    plowe-0: 3671-869, 5d.16h.58m
    ublock-abuse: 75-0, 5d.16h.57m
    ublock-badware: 4128-96, 1d.12h.22m
    ublock-filters: 31528-106, 1d.12h.21m
    ublock-privacy: 213-39, 5d.16h.56m
    ublock-quick-fixes: 189-1, 3h.21m
    ublock-unbreak: 1789-55, 1d.12h.25m
    urlhaus-1: 9599-0, 3h.22m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 756 ms
  maxAssetCacheWait: 348 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    livejournal.com: 1
    buzzoola.com: 1
    google.com: 5
    googletagmanager.com: 1
    otm-r.com: 1
    seedr.com: 1
    top100.ru: 1
```
</details>

**Comment by mapx-** [comment]
Enable `RUS: RU AdList`

and subscribe `RU counters list`
https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters
