### ISSUE TITLE
estudafq.pt: detection

### ISSUE THREAD

**Issue by janeirin13** [uBlockOrigin/uAssets#13456]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://estudafq.pt/fqa10/fqa10f1-1/`

### Category

detection

### Describe the issue

just by entering the website, the adblock gets detected on chrome

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/42879519/170890723-462c65f6-7615-4ea7-9d8a-394d2f8f3ee0.png)

AdBlock Detected!
We have detected that you are using an AdBlock!

To help continue to develop the site we use some advertising! Advertising is the responsibility of Google Adsense, which manages the amount and types of ads you will see on the site.

Please add estudafq.pt to your ad whitelist or disable your ad blocking software.

Also consider making a donation so we can continue to do a great job! Thanks.

Thanks!

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 85131
  cosmetic: 46376
  scriptlet: 17289
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67496-50, 2d.16h.16m
    easyprivacy: 27096-122, 2d.16h.15m
    plowe-0: 3673-804, 10d.23h.47m
    spa-1: 4503-79, 1d.8h.16m
    ublock-abuse: 75-0, 10d.23h.45m
    ublock-badware: 4133-96, 1d.22h.41m
    ublock-filters: 31526-134, 2d.16h.14m
    ublock-privacy: 214-2, 10d.23h.41m
    ublock-quick-fixes: 183-2, 1d.17h.29m
    ublock-unbreak: 1789-43, 2d.16h.13m
    urlhaus-1: 9599-0, 17h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 432 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    estudafq.pt: 1
    doubleclick.net: 8
    facebook.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    microsoft.com: 1
    onesignal.com: 1
    statcounter.com: 1
    themoneytizer.com: 10
    twitter.com: 1
    wp.com: 1
    youtube.com: 22
```
</details>

**Comment by Branzeturi** [comment]
`chrome://extensions/`
Do you have any other extension with ad blocking and/or tracking blocking integrated? Do you use any ad / tracker blocking hosts file? Any ad / tracking blocking DNS service?
