### ISSUE TITLE
html5.gamemonetize.co: detection through Poki's SDK

### ISSUE THREAD

**Issue by Explosion-Scratch** [uBlockOrigin/uAssets#13453]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://html5.gamemonetize.co/9td2pwzqhjsg0vo9z1csm5lo9aes8s1i/`

### Category

detection

### Describe the issue

Ads are detected on all poki games via JavaScript (somehow):
![image](https://user-images.githubusercontent.com/61319150/170883042-f98de888-d197-4daa-b801-21dc3a4dd27a.png)

Game developers can the modify their games if ads are detected. The particular game I'm playing sets `window.pokiAdBlock` to true but using this filter simply breaks the game:
```
html5.gamemonetize.co##+js(set, pokiAdBlock, false)
```

In addiction `PokiSDK.commercialBreak()` and other similar APIs for game developers return incomplete statuses when called, notifying the game that an adblocker is active and/or something was blocked/skipped

![image](https://user-images.githubusercontent.com/61319150/170883209-fa4d1a07-f491-4d58-a2d8-b96e0edf9931.png)

![image](https://user-images.githubusercontent.com/61319150/170883204-71d606f2-4b72-4297-9d4e-079a2a2fa86d.png)

This seems to be because of the request to `https://html5.gamemonetize.co/9td2pwzqhjsg0vo9z1csm5lo9aes8s1i/prebid4.12.0.js`, blocked by `/prebid4` in EasyList.

### Screenshot(s)

<details>
<summary>Screenshot(s) [none]</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 83708
  cosmetic: 44577
  scriptlet: 17109
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gist.githubusercontent.com/Explosion-Scratch/73327c11e2b42f7d667d3bfb22846b8d/raw: 957-81, 1d.22h.9m
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt: 244-44, 21h.21m
  default: 
    user-filters: 217-17, never
    easylist: 67538-60, 2d.9h.14m
    easyprivacy: 27100-163, 2d.9h.13m
    plowe-0: 3671-830, 2d.9h.17m
    ublock-abuse: 75-0, 2d.9h.16m
    ublock-badware: 4128-96, 2d.9h.12m
    ublock-filters: 31525-95, 2d.9h.11m
    ublock-privacy: 222-2, 2d.9h.15m
    ublock-quick-fixes: 189-1, 21h.23m
    ublock-unbreak: 1789-42, 2d.9h.10m
    urlhaus-1: 9328-0, 21h.22m
filterset (user): [array of 217 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 432 ms (selfie)
  maxAssetCacheWait: 1236 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    gamemonetize.co: 1
    2mdn.net: 1
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 2
    imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no anti adb stuff / blocking

**Comment by Explosion-Scratch** [comment]
Test in console

**Comment by mapx-** [comment]
I get adblocker active in console even whitelisting the page.

Can you play the game without any limitations ?

**Comment by Branzeturi** [comment]
`https://sybogame.com/` had an unhidden element

@ryanbr Could `sybogame.com#?#.game-container > div:not([class="row"]):-abp-contains(Ad)` be added to `EasyList`?

**Comment by Explosion-Scratch** [comment]
> I get `adblocker active` in console even whitelisting the page.
> 
> Can you play the game without any limitations ?

Oh, ok, you're right
