### ISSUE TITLE
indiatoday.in: ads and overlays

### ISSUE THREAD

**Issue by prirai** [uBlockOrigin/uAssets#13452]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did answered truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.indiatoday.in/`

### Category

ads

### Describe the issue

The website shows sponsorships and ads while on different article pages. The same can be disabled by using these filters which I created using the pick tool, really handy. After I added the below filter, the site looked way better and a lot cleaner than before. I still don't know how to contribute filters upstream so I'm putting this as an issue here.

My custom filters:

```
! 2022-05-29 https://www.indiatoday.in
www.indiatoday.in##.closeBottomSlider
www.indiatoday.in##.bottomSliderSwipe

! 2022-05-29 https://akm-img-a-in.tosshub.com
||akm-img-a-in.tosshub.com/sites/test/ipl/2022/img/IPL-Sponsor-Web_strip2.jpg?imbypass=true$image
||akm-img-a-in.tosshub.com/sites/test/ipl/2022/img/IPL-Sponsor-Web_strip2.jpg?imbypass=true$image

! 2022-05-29 https://www.indiatoday.in
||akm-img-a-in.tosshub.com/sites/test/ipl/2022/index4.html?site=it&device=web&ver=2.30$subdocument
www.indiatoday.in##.rhs-fixwhtsapp.mhide > .whticon.whatsapp_share > svg > g > g > circle
www.indiatoday.in##.rhs-fixwhtsapp.mhide > .whticon.whatsapp_share > svg
www.indiatoday.in##.rhs-fixwhtsapp.mhide
||akm-img-a-in.tosshub.com/sites/test/ipl/2022/index4.html?site=it&device=web&ver=2.30$subdocument
www.indiatoday.in##.readmore
www.indiatoday.in##.story-recommended-chunk
www.indiatoday.in##.mhide.may-be-recommend > h3
www.indiatoday.in###cubebutn
www.indiatoday.in###getAudio
www.indiatoday.in###audio_status
||smedia2.intoday.in/images/txttoaudio/audio_pause_y.svg?13$image
www.indiatoday.in##.audtxt-wrapper
www.indiatoday.in###shoppingWidget
www.indiatoday.in##.mhide.may-be-recommend
||www.indiatoday.in/live-score/widgets/cubescore_it.html?v=3$subdocument
www.indiatoday.in##.crosscloseif
||www.indiatoday.in/live-score/widgets/cubescore_it.html?v=3$subdocument
www.indiatoday.in##div.mrg15.hp-sectionad:nth-of-type(12)
www.indiatoday.in##div.mrg15.hp-sectionad:nth-of-type(7)
www.indiatoday.in##.liveblog-header-ad
www.indiatoday.in##.footer-mid
www.indiatoday.in##.video-header-right.col-md-4
www.indiatoday.in##.jw-reset.jw-video
www.indiatoday.in##.fixedsmall-video.video-iframe-wrapper
```
--

_Hope it helps._

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83790
  cosmetic: 43559
  scriptlet: 17046
  html: 658
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    ublock-filters: 32138-33, 2d.19h.10m
    ublock-badware: 4132-3, 2d.19h.9m
    ublock-privacy: 228-0, 2d.19h.8m
    ublock-abuse: 75-0, 2d.19h.7m
    ublock-unbreak: 1800-0, 2d.19h.6m
    ublock-quick-fixes: 191-0, 9h.25m
    easylist: 67483-597, 2d.19h.4m
    easyprivacy: 27094-579, 2d.19h.2m
    urlhaus-1: 9599-0, 9h.24m
    plowe-0: 3671-3, 2d.19h
filterset (user): [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1011 ms (selfie)
  maxAssetCacheWait: 510 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    chartbeat.com: 2
    crazyegg.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    izooto.com: 3
    jwpcdn.com: 1
    jwpltx.com: 1
    pubmatic.com: 1
    scorecardresearch.com: 1
    taboola.com: 1
    tosshub.com: 2
```
</details>

**Comment by mapx-** [comment]
Report at Easylist repository but you should indicate examples / specific pages, where are the ads etc

@ryanbr
