### ISSUE TITLE
[nsfw] mozinet.me: ads

### ISSUE THREAD

**Issue by skyfighteer** [uBlockOrigin/uAssets#13466]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

```
https://mozinet.me/
https://filmvilag.me/
```

### Category

ads

### Describe the issue

These 2 sites are pretty much the same in terms of the DOM, they host links and videos to movies from the same main site.
The ad is from a hungarian NSFW site called "rosszlanyok.hu".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83515
  cosmetic: 43618
  scriptlet: 17108
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    easylist: 67664-50, 55m
    easyprivacy: 27114-122, 55m
    plowe-0: 3669-807, 55m
    ublock-abuse: 75-0, 55m
    ublock-badware: 4139-96, 55m
    ublock-filters: 31517-95, 55m
    ublock-privacy: 222-2, 55m
    ublock-quick-fixes: 193-8, 55m
    ublock-unbreak: 1822-42, 55m
    urlhaus-1: 9201-0, 55m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 452 ms
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adskeeper.co.uk: 2
    adskeeper.com: 1
    google-analytics.com: 1
    projectagora.net: 1
```
</details>

**Comment by mapx-** [comment]
add

```
filmvilag.me##[href^="https://rosszlanyok.hu/"]
filmvilag.me##[style]:has(.adslot_1)
```

and report at https://github.com/hufilter/hufilter/issues
