### ISSUE TITLE
aj-crypto-miner

### ISSUE THREAD

**Issue by GoGoris** [uBlockOrigin/uAssets#1346]
### URL(s) where the issue occurs

`https://www.gadgetgear.nl/`

### Describe the issue

New aggressive cryptominer script called "aj-crypto-miner". It takes up 3/4 of all cpu power on my MacBook Pro.

### Screenshot(s)

Invisible, no warning or asking of the user's consent

### Versions

- Browser/version: Any
- uBlock Origin version: 1.14.25.101

### Settings

- none

### Notes

aj-crypto-miner is a crypto-miner for wordpress, so probably more sites will be affected

Proposed filter: `*/aj-crypto-miner/*$xmlhttprequest`

**Comment by mapx-** [comment]
already in easyprivacy:
`/aj-crypto-miner/*`

update easyprivacy and test again

**Comment by GoGoris** [comment]
I did not know that Easyprivacy also provides mining filters.

**Comment by mapx-** [comment]
yeah, there is a section dedicated to (anti-)mining
