### ISSUE TITLE
iconmonstr.com: detection

### ISSUE THREAD

**Issue by japaslu** [uBlockOrigin/uAssets#13461]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://iconmonstr.com/?s=money`
All pages searched for any word.

### Category

detection

### Describe the issue

the adblock warning is there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1440" alt="スクリーンショット 2022-05-30 午後4 01 13" src="https://user-images.githubusercontent.com/39429350/170935309-df492d3a-90b2-48fb-8384-70273ddaf40c.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 84704
  cosmetic: 49291
  scriptlet: 17145
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    JPN-1: 7082-8, 3d.9h.23m
    easylist: 67483-133, 3d.9h.22m
    easyprivacy: 27094-142, 3d.9h.21m
    plowe-0: 3671-812, 5d.20h.22m
    ublock-abuse: 75-0, 7d.12h.21m
    ublock-badware: 4128-96, 3d.9h.20m
    ublock-filters: 31481-109, 3d.9h.19m
    ublock-privacy: 213-2, 7d.12h.20m
    ublock-quick-fixes: 190-1, 17h.10m
    ublock-unbreak: 1789-51, 3d.9h.18m
    urlhaus-1: 9446-0, 17h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 235 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    carbonads.com: 1
    google-analytics.com: 1
    servedby-buysellads.com: 1
```
</details>

**Comment by BlocksAds** [comment]
anti-adb on `https://iconmonstr.com/quote-right-filled-svg/`
https://github.com/AdguardTeam/AdguardFilters/issues/139688
