### ISSUE TITLE
gandi.net: breakage

### ISSUE THREAD

**Issue by romuald** [uBlockOrigin/uAssets#13467]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gandi.net/en/domain/tld/bcn?currency=USD&taxes=yes&sw=currency,taxes`

### Category

breakage

### Describe the issue

This static page is blocked by a rule named "/bcn?"

Resulting in a **This site can’t be reached** error (ERR_FAILED) on Chrome

The bcn is the dynamic part of the URL, it works fine when you remove the querystring, it also works fine when using another ressource (eg: `https://www.gandi.net/en/domain/tld/com?currency=USD&taxes=yes&sw=currency,taxes`)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83512
  cosmetic: 43615
  scriptlet: 17103
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 5h.11m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 67662-50, 5h.3m
    easyprivacy: 27114-122, 5h.2m
    plowe-0: 3669-807, 5h.6m
    ublock-abuse: 75-0, 4h.59m
    ublock-badware: 4139-96, 5h.5m
    ublock-filters: 31513-95, 5h.1m
    ublock-privacy: 222-2, 5h
    ublock-quick-fixes: 193-8, 4h.56m
    ublock-unbreak: 1822-42, 5h.4m
    urlhaus-1: 9201-0, 4h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 174 ms (selfie)
  maxAssetCacheWait: 87 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    gandi.net: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
```
This site can’t be reachedThe webpage at https://www.gandi.net/en/domain/tld/bcn?currency=USD&taxes=yes&sw=currency,taxes might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED
```

**Comment by romuald** [comment]
Thank you :bow:
