### ISSUE TITLE
namu.wiki: detection

### ISSUE THREAD

**Issue by dummest** [uBlockOrigin/uAssets#13476]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://namu.wiki/`

### Category

detection

### Describe the issue

the site detect ublock and hiding contents

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 99
filterset (summary): 
  network: 85518
  cosmetic: 26417
  scriptlet: 17153
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32227-284, 17h.22m
    ublock-badware: 4143-3, 15h.54m
    ublock-privacy: 220-1, 5d.5h.26m
    ublock-abuse: 75-0, 4d.14h.40m
    ublock-unbreak: 1838-0, 16h.47m
    adguard-mobile: 7773-181, 17h.23m
    easylist: 67662-24797, 14h.5m
    easyprivacy: 27113-594, 13h.52m
    urlhaus-1: 9201-0, 16h.46m
    plowe-0: 3668-3, 2d.7h.46m
    KOR-1: 1769-90, 1h.40m
    ublock-quick-fixes: 193-4, 1h.39m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2449 ms (selfie)
  maxAssetCacheWait: 1899 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    doubleclick.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@piquark6046 please take a look i have no korean IP

**Comment by piquark6046** [comment]
if you want to block PowerLink advertisement, please install [List-KR/NamuLink](https://github.com/List-KR/NamuLink).

<details>
<summary>References</summary>

https://bbs.ruliweb.com/best/board/300143/read/57606018?
https://twitter.com/purengom/status/1537392014169640960

</details>

**Comment by dummest** [comment]
Wow i didnt thought things gonna be fast like this lol thx XD

**Comment by piquark6046** [comment]
@dummest 
I am writing NamuLink.
I left the comment for a visitor who is from the mentioned websites.
