### ISSUE TITLE
tokuzilla.net: breakage

### ISSUE THREAD

**Issue by Ziko577** [uBlockOrigin/uAssets#13478]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tokuzilla.net/watch/uchu-sentai-kyuranger-episode-of-stinger.html`

### Category

breakage

### Describe the issue

The site up until today worked fine with uBlock but even refreshing the page without uBlock enabled causes the video to not load and this affects the whole site. It's more or less needed to just watch things as the ads and popups are annoying. My phone loads the site fine and it works as there's no adblock on there other than the Brave shields which don't really block popups. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 111642
  cosmetic: 35
  scriptlet: 33030
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master/9Anime%20filter%20list: 149-34, 22m
    https://gitlab.com/kowith337/PersonalFilterListCollection/raw/master/filterlist/imageboard/GelboLube-Legacy.txt: 158-47, 22m
    adguard-annoyance: 53633-46487, 22m
    adguard-generic: 64341-32804, 22m
    fanboy-annoyance: 71612-63286, 22m
  default: 
    user-filters: 70-13, never
    easylist: 67698-35414, 22m
    easyprivacy: 27116-340, 22m
    plowe-0: 3670-822, 22m
    ublock-abuse: 75-1, 22m
    ublock-badware: 4159-704, 22m
    ublock-filters: 31543-10383, 22m
    ublock-privacy: 222-13, 22m
    ublock-quick-fixes: 191-88, 22m
    ublock-unbreak: 1822-313, 22m
    urlhaus-1: 9195-0, 22m
filterset (user): [array of 78 redacted]
trustedset: 
  added: [array of 41 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 8 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 3205 ms (selfie)
  maxAssetCacheWait: 1220 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    twitter.com: 1
```
</details>

**Comment by ghajini** [comment]
check on default ublock origin settings

**Comment by mapx-** [comment]
Reset uBO to default settings, don't add any other list, update all filter lists (after reset).

**Comment by mapx-** [comment]
If Brave => disable completely the shields on that page.
