### ISSUE TITLE
motherless.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1347]
URL(s) where the issue occurs

`http://motherless.com/3D9F037`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by gwarser** [comment]
`https://www.reddit.com/r/uBlockOrigin/comments/fp0vy9/motherlesscom_videoplayer_broken/`

`motherless.com#@#+js(aopr, _ml_ads_ns)` fixes player controls, but I think ads starts to appear next to the player.

**Comment by mapx-** [comment]
it should work now
