### ISSUE TITLE
troypoint.com: nuisance

### ISSUE THREAD

**Issue by Beach77** [uBlockOrigin/uAssets#13470]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://troypoint.com/iptv/`

### Category

nuisance

### Describe the issue

Has this ad/message on the screen that says
"Save 73% on IPVanish
Limited Time Offer
Claim Discount", the message might not be exactly the same when you read this. I have seen these kind of messages a lot on other sites so I decided to finally report it because it slows down my phone.  

### Screenshot(s)

![Screenshot_20220530-181548_Firefox Nightly](https://user-images.githubusercontent.com/101499628/171030525-2028941e-fe95-447d-ad73-9ba9eaa2ccc0.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 102
filterset (summary): 
  network: 84948
  cosmetic: 25425
  scriptlet: 17110
  html: 662
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32234-282, 33m
    ublock-badware: 4143-3, 32m
    ublock-privacy: 228-1, 31m
    ublock-abuse: 75-0, 30m
    ublock-unbreak: 1838-0, 29m
    ublock-quick-fixes: 193-0, 28m
    adguard-mobile: 7785-172, 38m
    easylist: 67664-24785, 27m
    easyprivacy: 27114-587, 26m
    urlhaus-1: 9195-0, 25m
    plowe-0: 3669-3, 24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3820 ms
  maxAssetCacheWait: 660 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    cloudflareinsights.com: 2
    googletagmanager.com: 3
    onesignal.com: 2
    wp.com: 3
```
</details>

**Comment by mapx-** [comment]
add

`troypoint.com##.mysticky-welcomebar-fixed-wrap`

**Comment by Branzeturi** [comment]
@ryanbr

**Comment by Beach77** [comment]
> add
> 
> `troypoint.com##.mysticky-welcomebar-fixed-wrap`
> 
> 

Thank you! Site seems to work much more smoothly now.

**Comment by jimmysofat6864** [comment]
The page is now showing a pop up advertisement message and a unlabeled red bar at the bottom of the page which should be removed as well. 


Website: `https://troypoint.com/sports-streaming-apps/`
Browser: Chrome and Firefox 

https://github.com/user-attachments/assets/dd35c793-962b-4910-9918-389fc653af3c

**Comment by mapx-** [comment]
```adb
troypoint.com##.mysticky-welcomebar-fixed
troypoint.com##.code-block:has([href*="vpn"])
troypoint.com###sgpb-popup-dialog-main-div-wrapper
troypoint.com##.sgpb-popup-overlay
```

@ryanbr
