### ISSUE TITLE
voe.sx break

### ISSUE THREAD

**Issue by Yami-x3** [uBlockOrigin/uAssets#13477]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voeunblock2.com/*`

### Describe the issue

if u open a stream on `https://voe.sx/` it redirected to a new Domain `https://voeunblock2.com/*` ublock origin isnt work for the new domain from `voe.sx`

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Opera GX | LVL 3 (core: 85.0.4341.79)

### Settings

- no changes

**Comment by ghajini** [comment]
force update your filter lists

**Comment by ghajini** [comment]
you haven't provided any details such as URL where it occurs.
force update your filter lists in couple of time
