### ISSUE TITLE
bestdizi.net: ads

### ISSUE THREAD

**Issue by DevNightshade** [uBlockOrigin/uAssets#13473]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bestdizi.net/bolum/kingdom-of-the-winds-ruzgarin-kralligi-1-bolum`

### Category

ads

### Describe the issue

The Website is full of ads and in built ads whenever you try to watch a video. Windows also Pop up, even with the block enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 144486
  cosmetic: 206325
  scriptlet: 36258
  html: 665
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 48d.19h.42m
    adguard-generic: 64214-4997, 2d.23h
    adguard-mobile: 7772-155, 2d.22h.59m
    adguard-spyware: 26332-888, 2d.22h.57m
    adguard-spyware-url: 607-14, 2d.22h.56m
    block-lan: 43-0, 5d.7h.25m
    curben-phishing: 13458-1, 1h.57m
    curben-pup: 246-0, 1h.56m
    adguard-annoyance: 53580-4466, 2d.22h.54m
    adguard-social: 17443-1098, 2d.22h.53m
    fanboy-thirdparty_social: 68-0, 5d.7h.24m
    fanboy-annoyance: 71350-55859, 5d.7h.23m
    fanboy-cookiemonster: 32254-91, 5d.7h.22m
    fanboy-social: 23409-28, 2d.22h.52m
    ublock-annoyances: 4438-4, 2d.22h.51m
    DEU-0: 5782-8, 1h.59m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32140-77, 2d.23h.3m
    ublock-badware: 4132-3, 2d.23h.2m
    ublock-privacy: 220-0, 4d.4h.58m
    ublock-abuse: 75-0, 4d.4h.57m
    ublock-unbreak: 1800-1, 2d.23h.1m
    easylist: 67564-786, 2d.22h.58m
    easyprivacy: 27101-10672, 2d.22h.55m
    urlhaus-1: 9195-0, 1h.58m
    plowe-0: 3671-3, 8d.19h.10m
    ublock-quick-fixes: 192-0, 1h.55m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 348 ms (selfie)
  maxAssetCacheWait: 587 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 4
    odnoklassniki.ru: 3
    skyad.me: 2
    youtubex.top: 1
```
</details>

**Comment by Branzeturi** [comment]
Did you try enabling the "AdGuard Turkish" filter list?
