### ISSUE TITLE
help needed on script inject rule making

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1348]
### URL(s) where the issue occurs
`http://varagh.com/en/`

### Describe the issue
Is it possible to make a script inject for following case?

`/advertisement.js` has following contents:

`document.write('<div id="ads_block_1">an advertisement</div>');`
.
.
.
.
and source of page has a call to advertisement.js and followed by lines below:
```
<style type="text/css">
	#modal_ads {
		visibility:hidden;
		width:360px;
		padding:8px;
		background:rgba(0,0,0,.3);
	
		-webkit-border-radius:8px;
		-moz-border-radius:8px;
		border-radius:8px;
	
		position:absolute !important;
		top:50% !important;
		left:50% !important;
		margin-top:-94px !important;
		margin-left:-180px !important;
		z-index:101;
	}
	
	.reveal-modal-bg {
	    position: fixed;
	    height: 100%;
	    width: 100%;
	    background: rgba(0, 0, 0, 0.45);
	    z-index: 40;
	    top: 0;
	    left: 0;
	    display: none;
	}
</style>
<div class="reveal-modal-bg" style=""></div>
<div id="modal_ads" class="reveal-modal pane">
     <table class="pane">
	<tbody><tr>
	<td height="28" class="paneltop c">Attention: AdBlocking Software Detected!</td>
	</tr>
	<tr>
	<td class="manPanel panel" style="background-color: #000; height: 161px;">
	<p>کاربر گرامی‌، بخش مهمی‌ از هزینه‌های سایت ورق از طریق تبلیغات پرداخت میشوند. برای پشتیبانی‌ و بهتر شدن سایت، از شما تقاضا می‌کنیم که لطفا از نرم افزار adblocker در سایت ورق استفاده نکنید. ممنون از پشتیبانی‌ شما...</p>		
	<p class='countdown'></p>
	<button id="ads_close" class="btn submitbttn close-reveal-modal" style="cursor:pointer; display:none">Close</button>
	</td>
	</tr>
	</tbody></table>
</div>

if (document.getElementById("ads_block_1") != undefined) {
    
} else {
    $('#modal_ads').reveal({ 
        animation: 'fade', 
        animationspeed: 600, 
        closeonbackgroundclick: false, 

    });
    $('.reveal-modal-bg').css('display', 'block');

    $(".countdown").countdown(hide_button, 15, " seconds to close");

    if (location.pathname.substring(1).split('/')[1] != 'adBlock') {

    }

}
```
It's possible to resolve the issue with `@@||domain.com/advertisement.js` or using element hiding rules, but I would like to know if it could be fixed with `abort-on-property-read.js`, `abort-on-property-write.js` or others?

### Versions

- Browser/version: Chrome 63.0.3239.132 (Official Build) (64-bit)
- uBlock Origin version: 1.14.24

### Notes

I already tried with this one but there was no luck:
`domain.com##script:inject(abort-on-property-write.js, ('.reveal-modal-bg').css('display', 'block'))`

Thanks in advance

**Comment by okiehsch** [comment]
This is not a support forum, try `https://www.reddit.com/r/uBlockOrigin/`, or give a reproducable
example link.

**Comment by okiehsch** [comment]
>  I would like to know if it could be fixed with abort-on-property-read.js, abort-on-property-write.js or others?

Your code snippet suggests that the only way is **probably** abort-current-inline-script.js, but that is hypothetical without a specific link.

**Comment by nimasaj** [comment]
@okiehsch I edited my post to include link.

**Comment by okiehsch** [comment]
`varagh.com##script:inject(abort-current-inline-script.js, $, adBlock)` works on my end and should not break anything, I did not try to play any games to check if this is the case but it is highly unlikely.

In such a case`abort-current-inline-script.js` will most of the time work, you disable the part of the inline script that the bait script, i.e. `/advertisement.js`, calls if possible.

**Comment by nimasaj** [comment]
@okiehsch Thanks, it's working. 
I have some questions regarding params. Is `adBlock` coming from this part:
```
 if (location.pathname.substring(1).split('/')[1] != 'adBlock') {

    }
```
If so, then since this `if` condition is empty and obsolete, is it necessary? I changed your proposed rule with the following one and it's still working.
`varagh.com##script:inject(abort-current-inline-script.js, $)`
but then the question is how did you choose `$`?
Based on the following topic, `$()` is an alias for `jQuery()` used in the jQuery Library.
`https://stackoverflow.com/questions/1150381/what-is-the-meaning-of-sign-in-javascript`
Then, does it mean that this rule is making interference with all other jQuesry()-related functions? If so, wouldn't it be a problem in general (not specifically for this site)?

**Comment by okiehsch** [comment]
Read [this](https://github.com/uBlockOrigin/uAssets/issues/618#issuecomment-321842729) for a basic explanation how `abort-current-inline-script.js` works.
This should answer your question why 
`varagh.com##script:inject(abort-current-inline-script.js, $, adBlock)`
is preferable to
`varagh.com##script:inject(abort-current-inline-script.js, $)`
even though both work.
