### ISSUE TITLE
jobs.automobilwoche.de: breakage

### ISSUE THREAD

**Issue by cenderDA** [uBlockOrigin/uAssets#13483]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://jobs.automobilwoche.de/OfferDetail?cn=RYENU_PxHJY1DHkBkMn8L5Gim1ytL7arz_GsldPb1uTxm-bw0C_Fqb6zibGwJ4vY0nMVbqYv4EsVpBolF4CCeuUhcvLY86zrzwMxqSCzm79VazNbbfjQjcXY1uUqiHxYcpLOtrH6a4kZiuNmnjCI07HrZ54NhHB3ud2RFanX56dC0n38815esEyMKK0vPGt6oj5atvsT2imjFkcYFbbLJ8CsNl5YY0BfbYV8pkNzy1TfyOcyXdZvWbyi7m95ov6GqjoQGdM1AVpTdApMLLSz5fv5hetTqjnsc6-iEMdtWskd_L8ggM1tob9DbP0wUl_lqB9na2T6SWgoKu3_RJ-ObqjmkppU6HK5JAoa7X0DxqKOm81epNf9fi8K16xsCoRj3NE15nFgG2ua-c2jRu6GKHqp9c0lMM78ZDNzDxxV8Awzfx8DVCV8sethsqsjsM7OFliFifEkjcWqK_ZakQLCIDMqVvf5CmN-RAp39dSmhDs1MOHDzxtHv5RK1XaawSTLT_onE6ES_mpsUjh69-kyGicV05FlH11HW9e_XA-AX4Rj8bpy1IPP-HbY6TGvHCflvOAUiMt7-HV13U9OBUvus5j4a_IX1inPSs_-bzWHP36NNS9C4eNt7U7qnvo6PBW_1cQ3u6k6egpzJfihQaNQQmy-D3Jua1DyR1NUYNB7-XwFOAyzcxL7P78BV6U_koq6Ho8qhhdMTAJ-gnICbvCHHReZoog522iPqV8X3r1uG1W6uPw4rVsaIDjyWRYeoIfiZ0eUKoCEWKW_8ngh8ksMzO3bN68tSYcnYjdzitMIHGTclLSYx3JyXodnqMbGwW4zfQYhfrvT5jD4KIdZlHuLaPMWcIzgu0GroiXp0xgOV2HWoEEIm9Y9APDtN16Y_CrPFzSko2IUyqWDnhL7jQf5lXfTqXapna71cfEyZjnDqhyBKrpIi16VvpJKrLifUAg0jXng1z0IHt87CkI7EbYIug`

### Category

breakage

### Describe the issue

the button "Jetzt Bewerben" (apply for a job offer) does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 85590
  cosmetic: 47160
  scriptlet: 16827
  html: 651
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31724-29, 23h.30m
    ublock-badware: 4143-3, 23h.29m
    ublock-privacy: 220-0, 5d.23h.18m
    ublock-abuse: 75-0, 5d.23h.18m
    ublock-unbreak: 1833-0, 23h.28m
    easylist: 67664-610, 23h.27m
    easyprivacy: 27114-589, 23h.26m
    urlhaus-1: 9195-0, 23h.25m
    plowe-0: 3671-3, 5d.23h.18m
    DEU-0: 5774-13, 23h.24m
    ublock-quick-fixes: 222-1, 23h.23m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    automobilwoche.de: 5
    google-analytics.com: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||jobs.automobilwoche.de/Scripts/ApiTracking.js$script,1p`
