### ISSUE TITLE
idnes.cz: ads

### ISSUE THREAD

**Issue by tinukedaya** [uBlockOrigin/uAssets#13485]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.idnes.cz/`

### Category

ads

### Describe the issue

Background ads still show as well as ads in front of videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83716
  cosmetic: 43880
  scriptlet: 17176
  html: 658
listset (total-discarded, last updated): 
  added: 
    CZE-0: 711-0, 1d.29m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32071-41, 2d.1h.41m
    ublock-badware: 4143-3, 2d.1h.40m
    ublock-privacy: 228-0, 2d.17h.37m
    ublock-abuse: 75-0, 2d.17h.36m
    ublock-unbreak: 1833-0, 2d.1h.39m
    easylist: 67598-587, 2d.1h.42m
    easyprivacy: 27110-597, 2d.1h.38m
    urlhaus-1: 9195-0, 1d.30m
    plowe-0: 3669-3, 1d.4h.31m
    ublock-quick-fixes: 189-0, 1d.28m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1809 ms (selfie)
  maxAssetCacheWait: 703 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    1gr.cz: 1
    criteo.net: 4
    gemius.pl: 1
    google-analytics.com: 1
    seznam.cz: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Maybe 

```
/www\.idnes\.cz\/[a-zA-Z0-9\/]{100,}\?\.jpg/$image,domain=idnes.cz
idnes.cz##body > div[id] > .counters + table#r-leaderboardrub
tv.idnes.cz##div[style="position:relative; width:300px; height:250px;"]
||vod.idnes.cz/*.mp4#$media
```

**Comment by JobcenterTycoon** [comment]
If you visited the site before with a other adblocker/`CZE-0` disabled clear the cookies from this page. A script checks for adblocking and if the script detect one it sets a cookie so for 2 days obfuscated ads get loaded even if the script is already defused. I get no ads with `CZE-0` enabled.

To block the obfuscated ad images try `/www\.idnes\.cz\/[a-zA-Z0-9\/]{100,}\?\.jpg/$image,domain=idnes.cz`

**Comment by tinukedaya** [comment]
Well, I'm not aware ever visiting the page with disabled adblocker, but clearing the cookies actually worked.
Adding the line to the filter broke the site completely.

But a I said, clearing cookies worked like a charm.
