### ISSUE TITLE
jobs.main-echo.de: breakage

### ISSUE THREAD

**Issue by cenderDA** [uBlockOrigin/uAssets#13487]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://jobs.main-echo.de/OfferDetail?cn=0wzQCYMEboEJmwGPWkzTL8BI9Lp7x9VKTjoOAac_dwjttp_YhZBL3ur86LijUVrThqiimfY6Wn4dgs8gKuIRKY2yxxXyoL6kQuXIPE_BTmbrej5IxuhVTV8nCs0E6ujEW2jNB_RMZqbGgPon4yk-ydklSMU2zBySD7LzLnEoQ8EifqlBRUMNx5a3FnPAklaYRCLNzx4CxdAdBG2G57mNTOzSzwbt4A1dfCeZEkdz994VqFox-sBQaPrlKAN2_m3zSowN2BQoIyKJWR5H29XC34S4YbMCfy-wOE5C4P0FOv6KFDaTkvMNxALPA3zdQnw15_f-ffyQWNbP5Q0b7xmPmS3Cdfs3h7WwNEqlJsTFM5ZSSeds_tME40nvKQB02Z0G48rGnM1A82qM8VqAzwzbMWdAtTZFm3gRFZqcv4DBvvWaUjA2iBPIRM87do66Q5g8oFjNjAm8wDj_Hp2SgWFVybjHh-WPSDGZFq_jA0vl8vqko-dwx5PZsrsGOlr4NqmtzEI7xPl3QPpAipkfAaRitdQKw6aaBKj3YtFxbxrJtRzB5TBY4DIBXZWgkAh_YfIjCFm_MkAg8ALOWRq25tscgymUGNuAknH2_OYfcwcywEUDjbkNRpC9oymvHC-Jq11YnHZdeKyY4_UBhGGWvEWbSNzaqjO7F_cAUzaMkh8TALWR0aLWPXRorTkQeKOtix6DetWFx4leDFCAt9yCzmPTAzuShhMkZsI23mwFl32x5geEbD2NZiGP9lMR3132h6GxZeg0YhnlGczeX57t0SurSRxyHeh8HexNi7UjCBtGqLA_97MuBZlNEwF0Y4d8dxKkPz5TmGPnjoq90PNGDqQ0AxV5UE_t0bLzWNG2_G639fx0gZusYdqfZBjdCJOdX5wlcocoNsH7ip36O7Te_oQ_nj8zlLQm0eu2CqPY22uUfX8bBn6BqwecfQLSa5PLyIN7WxTLyGmYHnEuYXUe_MMPAQ&interest=true`

### Category

breakage

### Describe the issue

the button "Jetzt Bewerben" (apply for a job offer) does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 85590
  cosmetic: 47160
  scriptlet: 16827
  html: 651
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31724-29, 23h.45m
    ublock-badware: 4143-3, 23h.44m
    ublock-privacy: 220-0, 5d.23h.33m
    ublock-abuse: 75-0, 5d.23h.33m
    ublock-unbreak: 1833-0, 23h.43m
    easylist: 67664-610, 23h.42m
    easyprivacy: 27114-589, 23h.41m
    urlhaus-1: 9195-0, 23h.40m
    plowe-0: 3671-3, 5d.23h.33m
    DEU-0: 5774-13, 23h.39m
    ublock-quick-fixes: 222-1, 23h.38m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    main-echo.de: 2
    googletagmanager.com: 1
    maps.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||jobs.main-echo.de/Scripts/ApiTracking.js$script,1p`
