### ISSUE TITLE
jobs-in-mittelhessen.de: breakage

### ISSUE THREAD

**Issue by cenderDA** [uBlockOrigin/uAssets#13484]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jobs-in-mittelhessen.de/OfferDetail?cn=7jcPgKIO2ST0l56EyaRmnlV_Ukg8oUbFUivrlf3T2R5z7eWFy3jEulejReEtZZfIY1_WMMwsSPIaaPYOtCsOZEJ1_pgKmA2RpdJzes7MqdqQOpPvEfe334a_HXw1naGsSG1-ZjQuzkjPdu1Hbtw4XTAThc4I8t-YF0A55edf2UpOfcjAXrkw54JbUsMiZ8t6whsUYRBBRdll6UXQBMIoZX8qEf5Exk7FmNrref5JtWi-etCOONMWi4TShcAzU4wiAXv7gmaXvwXT-5t9ATD7jhsHHnn2eorTrzVUiiiq5LKE6ePB8QKOkm8uRZ-iHg4xf_HUYwJMbetIPzaa0xxQsYcuvA0zccQOZc157W2EwiZe_C8KkmcXvW4bxMOrViGXLRPQFA9To06IQ3LCrysKVI_tY_Iwmet3ZRgw6DsFcaSsTlfYGk35VnXuExvHJ9SZMdjY-oCJXxtL6cckfvM5s1DhCMVEjXl8sWfVx41G2AHol-8JNFx2oA0o7_JAjWU4PUf5cXqwWcQg8phvrgvsVP3dTnV81ez7mORGSUDizoNGDTBNGAUSnRpFlEzgT8HYFmD62dlwuFdH19kUYcyDRYWdlK1TVfWV1Wt3Q2cLcjMmTDeG_gQjeJ65BlEj0XolGi9cax6SPNk1SuBWdg4yWoecvQLTv82q1T0vqSRz-kW_JBkEpa5MF0un_KTDImCdvdghW6VE3Nvkw8S_Up7XaOLDF7-3EyugBxe9jZ1goPzRIuU-kF3TkBu_V0otHRHrJHFeaRIqvZLM6eoSZI8Ho5H7Z1akcpyPqT3EeMOA5znRDCvq_hmqOALGg0zL4EaPOvawrtu2N4FcGovwoyU9dRKRiEkNMJRnAsG_bgYzG0IFV5_JvPSle-YM-KpcV994_CqmqhA7ERqtwVdN_ub2EoN7hlx0qFL_L1jEKowQ7a4kBR_qY3hxyn50V0C4CSyG6_mEpoB714ZqSRce04DRrg&interest=true`

### Category

breakage

### Describe the issue

the button "Jetzt Bewerben" (apply for a job offer) does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 85590
  cosmetic: 47160
  scriptlet: 16827
  html: 651
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31724-29, 23h.34m
    ublock-badware: 4143-3, 23h.33m
    ublock-privacy: 220-0, 5d.23h.21m
    ublock-abuse: 75-0, 5d.23h.21m
    ublock-unbreak: 1833-0, 23h.32m
    easylist: 67664-610, 23h.31m
    easyprivacy: 27114-589, 23h.30m
    urlhaus-1: 9195-0, 23h.29m
    plowe-0: 3671-3, 5d.23h.21m
    DEU-0: 5774-13, 23h.28m
    ublock-quick-fixes: 222-1, 23h.27m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    jobs-in-mittelhessen.de: 2
    cdntrf.com: 2
    d2wu036mkcz52n.cloudfront.net: 1
    google-analytics.com: 1
    ioam.de: 2
    maps.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||jobs-in-mittelhessen.de/Scripts/ApiTracking.js$script,1p`
