### ISSUE TITLE
jobs.weser-kurier.de: breakage

### ISSUE THREAD

**Issue by cenderDA** [uBlockOrigin/uAssets#13493]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://jobs.weser-kurier.de/OfferDetail?cn=EtZZKCWAWlRhUctXGiaWcFN0DGN65K4k633mGc80PzpXrxGTJFvtezwpkTAaAgzSB2mqxaTwVLhE87Ge4Yj0GJtup1JLi-ppMqTs0_2Z-wwz-tBJJ88N50PE2jlFwbWLgLIA95Gtq61zln6L71dCM7WLU5qiDdc96YaWu4c9-vNnlTGUYgjoIYi-0cKnfGe0-gbEPpalz5HG2lV5mRGB8ZsPZmgODMJzxsIyP8Z0oDj4eGnKw2ABJ_5w7DLm3yH8i9r15GsucBNYTdofOEv-NSu0LTLBa6OoPECTrfJuPO_jvliM6liub-41nzzl3zWg-7FVcQYVX267qoduT5Y3uDK14_FHwA0YB1CuaUFnag4_EzKhv40lSl7DVpBrf3lbDyxdVF-mhrBMxeUzPvSRP1Uib2e03FLpePB63fMHNYFonTQF1H-0RrPaF_7IqK0bFZzw7TymcFHDYpJr06m_Dw3eg94N34wi1j-k0-aCRwTpPBaTEd-NQV8zs9-w244bhdmr79QcM1uCCwSuCh-o5KB5xAcYGmpAjT0qdks3rpgEAJh3csvyyDkpkmhaiTP56bBbGdJalRlHvh59ZTYu-ChLqU1GbUZBx2JZQWbECLwPvrNHW69vT5L7Faw2Nk6c-xPmwnlvOmadCv50alBjpB3p_42FOebbumWM5ha4mTL1HnrNXQZGxkgAC8HpyywNBPI5d0-Ng2WzWlxv2IuEj8N0XOyAVH7rdp7glKwDFI6WXnIuhrZddcU8qCr0qvii00tDMg4qXwkU2evkbLyXYHXdyHfWfig0SDsqdorGqgT35Zv4zCpgdA2UMDC-hAAhtf_-e44_ZsSP8zqIXDQDBrRIa4fAhnoghwW8rM6w-Ota2lRdq4cikql2NEvfHGAMFGoIqPejnQfRWG33VemVzPtS-q18Nt9rXSXyv9G93xwxBVjnME8KNC7X_yCIn6eRkV7P_QhDBPMAN_URJ76QGg&interest=true`

### Category

breakage

### Describe the issue

the button "Jetzt bewerben" (apply for a job offer) does not work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 85590
  cosmetic: 47160
  scriptlet: 16827
  html: 651
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31724-29, 23h.58m
    ublock-badware: 4143-3, 23h.57m
    ublock-privacy: 220-0, 5d.23h.45m
    ublock-abuse: 75-0, 5d.23h.45m
    ublock-unbreak: 1833-0, 23h.56m
    easylist: 67664-610, 23h.55m
    easyprivacy: 27114-589, 23h.54m
    urlhaus-1: 9195-0, 23h.53m
    plowe-0: 3671-3, 5d.23h.45m
    DEU-0: 5774-13, 23h.52m
    ublock-quick-fixes: 222-1, 23h.51m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    weser-kurier.de: 3
    adscale.de: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    ioam.de: 2
    iocnt.net: 2
    m6r.eu: 1
    maps.googleapis.com: 1
    mxcdn.net: 1
    theadex.com: 1
    userreport.com: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr
`@@||jobs.weser-kurier.de/Scripts/ApiTracking.js$script,1p`

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/4fbc55eb9fc11e66c54c3fcb277be1c4c5cf556a
