### ISSUE TITLE
bold.dk: detection

### ISSUE THREAD

**Issue by bumkarl** [uBlockOrigin/uAssets#13495]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bold.dk/fodbold/nyheder/la-liga-chef-vi-sender-mbappe-klage-snart/`

### Category

detection

### Describe the issue

Hey guys.
First of all, thanks for a great app!

This news site for football i use, have some videos with highlights and so on. It used to work with ublock, if it didnt i could clear and update, but it doesnt anymore.

Im not a shark with these IT stuff, so i hope I dont waste precious time.
![1](https://user-images.githubusercontent.com/106607302/171201588-351f9f67-b26b-4083-92eb-4a55219c8378.jpg)

Sincerely

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 83977
  cosmetic: 45533
  scriptlet: 17149
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NOR-0: 2735-5, now
    easylist: 67761-51, now
    easyprivacy: 27117-123, now
    plowe-0: 3670-808, now
    ublock-abuse: 75-0, now
    ublock-badware: 4159-97, now
    ublock-filters: 31563-103, now
    ublock-privacy: 222-2, now
    ublock-quick-fixes: 190-9, now
    ublock-unbreak: 1824-42, now
    urlhaus-1: 8741-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1139 ms
  maxAssetCacheWait: 607 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adnami.io: 1
    adrecover.com: 1
    cadreon.com: 1
    fwmrm.net: 1
    gemius.pl: 1
    googletagmanager.com: 3
    keppet.com: 1
    onthe.io: 1
    pbstck.com: 2
    permutive.com: 1
    pushpushgo.com: 1
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
@DandelionSprout it's kind of breakage, you should add the filter in your list (similar filter for `viafree`)

**Comment by mapx-** [comment]
@DandelionSprout when you add a fix let us know in order to remove our filter.

**Comment by DandelionSprout** [comment]
Oh, okay. That was news to me, but I'll try to keep it in mind.

**Comment by StigNygaard** [comment]
Currently videos are not playing on bold.dk for me with uBlock Origin activated using Firefox.

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?
