### ISSUE TITLE
fontspace.com: breakage

### ISSUE THREAD

**Issue by 2020-Julian** [uBlockOrigin/uAssets#13499]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fontspace.com/search`

### Category

breakage

### Describe the issue

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 86529
  cosmetic: 48382
  scriptlet: 17305
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 67564-50, 3d.23h.26m
    easyprivacy: 27101-122, 3d.23h.25m
    plowe-0: 3671-806, 8d.1h.15m
    spa-0: 3891-35, 18h.47m
    spa-1: 4503-169, 3d.23h.27m
    ublock-abuse: 75-0, 3d.23h.29m
    ublock-badware: 4128-96, 3d.23h.24m
    ublock-filters: 31519-150, 3d.23h.23m
    ublock-privacy: 222-2, 3d.23h.28m
    ublock-quick-fixes: 191-1, 18h.46m
    ublock-unbreak: 1792-43, 3d.23h.22m
    urlhaus-1: 9195-0, 18h.45m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1303 ms (selfie)
  maxAssetCacheWait: 725 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 4
    proper.io: 1
    quantserve.com: 1
    visualstudio.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`fontspace.com#@#.container-ads`
