### ISSUE TITLE
voeunblock2.com  - streamz.ws - anti adb

### ISSUE THREAD

**Issue by Simon80** [uBlockOrigin/uAssets#13509]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Ublock no longer works with certain sites: "Please disable you adblocker" 
```
https://voeunblock2.com/
https://streamz.ws/
```
Can you solve it?

### A specific URL where the issue occurs

`https://voeunblock2.com/`

### Steps to Reproduce

No work

### Expected behavior

Please disable you adblocker

### Actual behavior

No work

### uBlock Origin version

4

### Browser name and version

Firefox

### Operating System and version

Windows 11

**Comment by mapx-** [comment]
provide example links for the sites above - where we cam see the anti adb stuff

**Comment by Simon80** [comment]
https://voeunblock2.com/9sam3ay9w5l7
https://streamz.ws/wdu?9f9qlhg8r88t2gadlp43jfkwn48fb2akhja31rbtzkm21xgmnkp6za3nfb3qedbw

**Comment by Simon80** [comment]
https://streamz.ws/wdu?bx72j1s5kubpcmr7tkcjfweelssawqt7o1a722cnwoc9a4g4osn4p1iatblp2exq
https://voeunblock2.com/emb3gc38sjyd

**Comment by mapx-** [comment]
streamz => file not found => provide the real page containing  the links

**Comment by Simon80** [comment]
https://toonitalia.co/la-casa-nella-prateria/

**Comment by mapx-** [comment]
it seems streamz is broken: I get anti adb message even disabling uBO.
Maybe someone else could confirm or not

**Comment by mapx-** [comment]
read what happens in the thread:

![image](https://user-images.githubusercontent.com/10303732/171433510-d90a527d-8efa-404c-a235-6e950501c25c.png)

**Comment by Simon80** [comment]
![Immagine1](https://user-images.githubusercontent.com/1065811/171434828-aa70bc2e-7829-4717-ac8f-31b01b61f1f5.png)
![Immagine2](https://user-images.githubusercontent.com/1065811/171434840-55977614-4856-44e5-9d79-23055a8f71fd.png)

**Comment by Simon80** [comment]
https://voeunblock2.com/emb3gc38sjyd

**Comment by Simon80** [comment]
ok now it work fine!!! thank you so much!
Regards
