### ISSUE TITLE
eu.tamrieltradecentre.com: [detection]

### ISSUE THREAD

**Issue by Dorennor** [uBlockOrigin/uAssets#13501]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=211&SortBy=LastSeen&Order=desc`

### Category

[detection]

### Describe the issue

This, perhaps, is already ridiculous, but the author of the site again aggravated the work of the site).
Now instead of a window with a banner, just an inscription with a title (I'll throw off the code below) about the detection of a blocker.

<h 3 class="bold" data-bind="text: Status">Adblocker detected</h 3

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/40647609/171297121-5e50c740-3bc2-44d7-b10d-44ae8354ea1e.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 101399
  cosmetic: 65532
  scriptlet: 18318
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    RUS-0: 41496-8, 5h.54m
    easylist: 67771-64, 5h.54m
    easyprivacy: 27117-220, 5h.54m
    plowe-0: 3670-812, 5h.54m
    ublock-abuse: 75-1, 5h.54m
    ublock-badware: 4159-96, 5h.54m
    ublock-filters: 31569-132, 5h.54m
    ublock-privacy: 222-2, 5h.54m
    ublock-quick-fixes: 190-9, 5h.54m
    ublock-unbreak: 1824-42, 5h.54m
    urlhaus-1: 8741-0, 5h.54m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 679 ms (selfie)
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    doubleclick.net: 1
    facebook.com: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    paypalobjects.com: 2
    twitter.com: 1
```
</details>

**Comment by Dorennor** [comment]
"<h3 class="bold" data-bind="text: Status">Adblocker detected</h3>"

**Comment by Branzeturi** [comment]
Are
```
@@||pagead2.googlesyndication.com/pagead/managed/js/*$script,domain=eu.tamrieltradecentre.com
@@||googleads.g.doubleclick.net/pagead/html/r20220526/r20190131/zrt_lookup.html$subdocument,domain=eu.tamrieltradecentre.com
@@||adservice.google.com/adsid/integrator.js$xhr,domain=eu.tamrieltradecentre.com
tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
```
good filters?

**Comment by Dorennor** [comment]
> Are
> 
> ```
> @@||pagead2.googlesyndication.com/pagead/managed/js/*$script,domain=eu.tamrieltradecentre.com
> @@||googleads.g.doubleclick.net/pagead/html/r20220526/r20190131/zrt_lookup.html$subdocument,domain=eu.tamrieltradecentre.com
> @@||adservice.google.com/adsid/integrator.js$xhr,domain=eu.tamrieltradecentre.com
> tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
> tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
> ```
> 
> good filters?

Yep, it works.

**Comment by Dorennor** [comment]
> Are
> 
> ```
> @@||pagead2.googlesyndication.com/pagead/managed/js/*$script,domain=eu.tamrieltradecentre.com
> @@||googleads.g.doubleclick.net/pagead/html/r20220526/r20190131/zrt_lookup.html$subdocument,domain=eu.tamrieltradecentre.com
> @@||adservice.google.com/adsid/integrator.js$xhr,domain=eu.tamrieltradecentre.com
> tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
> tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
> ```
> 
> good filters?

Also it's about another site but there are filter that will be cool to add to your rules
mapgenie.io##.pogo.text-center

**Comment by Branzeturi** [comment]
> > Are
> > ```
> > @@||pagead2.googlesyndication.com/pagead/managed/js/*$script,domain=eu.tamrieltradecentre.com
> > @@||googleads.g.doubleclick.net/pagead/html/r20220526/r20190131/zrt_lookup.html$subdocument,domain=eu.tamrieltradecentre.com
> > @@||adservice.google.com/adsid/integrator.js$xhr,domain=eu.tamrieltradecentre.com
> > tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
> > tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > good filters?
> 
> Also it's about another site but there are filter that will be cool to add to your rules mapgenie.io##.pogo.text-center

- @Dorennor 

On `https://mapgenie.io/elden-ring/guides/quests` it looks like `mapgenie.io###blobby-banner` would be good @ryanbr 

@Dorennor URL?

**Comment by Dorennor** [comment]
> mapgenie.io###blobby-banner

mapgenie.io###blobby-banner - does not work

**Comment by Branzeturi** [comment]
@mapx- (Could you take a look at the `mapgenie` URL given by @Dorenno?)

**Comment by Branzeturi** [comment]
Maybe `mapgenie.io##.pogo.text-center:has-text(upgrade)` would be better (idk for sure, I didn't look a lot)

**Comment by Dorennor** [comment]
> Maybe `mapgenie.io##.pogo.text-center:has-text(upgrade)` would be better (idk for sure, I didn't look a lot)

It works same as 'mapgenie.io##.pogo.text-center' visually, nice. Site works with no ads

**Comment by kiechb** [comment]
Thanks for the link Branzeturi. I tried adding these filters manually for the US version of the site (swapped out EU for US), but instead just get an infinitely loading "Waiting for ads to load" instead of "Adblocker detected"

**Comment by Branzeturi** [comment]
Are
```
tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
@@||syndication.twitter.com/i/*$image,domain=tamrieltradecentre.com
@@||googleads.g.doubleclick.net/pagead/*$subdocument,domain=tamrieltradecentre.com
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*$script,domain=tamrieltradecentre.com
```
good filters?

**Comment by kiechb** [comment]
> Are
> 
> ```
> tamrieltradecentre.com#@#+js(set-constant, canDisableAds, true)
> tamrieltradecentre.com#@#+js(no-fetch-if, adsid)
> @@||syndication.twitter.com/i/*$image,domain=tamrieltradecentre.com
> @@||googleads.g.doubleclick.net/pagead/*$subdocument,domain=tamrieltradecentre.com
> @@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*$script,domain=tamrieltradecentre.com
> ```
> 
> good filters?

Working solid for the moment. Thanks!

**Comment by Yuki2718** [comment]
```
@@||syndication.twitter.com/i/*$image,domain=tamrieltradecentre.com
@@||googleads.g.doubleclick.net/pagead/*$subdocument,domain=tamrieltradecentre.com
```
Not needed on my end.

**Comment by Branzeturi** [comment]
@Yuki2718 
the first one isn't needed on my side (oops), but the other one is

**Comment by Yuki2718** [comment]
> the first one isn't needed on my side (oops), but the other one is

For what?
