### ISSUE TITLE
vidsrc.me / vidsrc.xyz (annoyance)

### ISSUE THREAD

**Issue by facorread** [uBlockOrigin/uAssets#13500]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vidsrc.me/embed/tt0275140/2-20`

### Describe the issue

When opening Firefox Developer Tools, the page is rewritten with the message " Dont open Developer Tools. " Some time later the page redirects to `https://www.google.de`

### Screenshot(s)

No screenshot

### uBlock Origin version

1.42.4

### Browser name and version

100.0.2

### Settings

Default settings

### Notes

Thanks for your volunteering

**Comment by mapx-** [comment]
@okiehsch can you reproduce it ?

**Comment by facorread** [comment]
Would you be able to reconsider your decision on this PR?

**Comment by mapx-** [comment]
if I disable the current filter
`vidsrc.*#@#+js(nosiif, /devtools|0x/)`

I'm able to reproduce the debug issue, so still working fine.
