### ISSUE TITLE
smallseotools.com: ads

### ISSUE THREAD

**Issue by byzantium225** [uBlockOrigin/uAssets#13513]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://smallseotools.com/page-comparison/`

### Category

ads

### Describe the issue

The site has Grammarly ads as GIFs.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_2022-06-01-20-53-13-02_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/102585192/171441248-7a4fae8b-1949-4dad-bef9-cf386881d098.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 170743
  cosmetic: 279665
  scriptlet: 37455
  html: 672
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-1443, 5h.11m
    https://www.i-dont-care-about-cookies.eu/abp/: 24916-8829, 3m
    adguard-generic: 64279-5249, 2d.6h.25m
    adguard-spyware: 26336-980, 2d.6h.22m
    adguard-spyware-url: 607-14, 2d.6h.21m
    block-lan: 43-0, 6d.7h.54m
    curben-phishing: 13375-2, 5h.9m
    curben-pup: 246-0, 5h.8m
    adguard-annoyance: 53607-5340, 2d.6h.19m
    adguard-social: 17446-1097, 2d.6h.18m
    fanboy-thirdparty_social: 69-0, 6d.7h.54m
    fanboy-annoyance: 71329-55881, 6d.7h.54m
    fanboy-cookiemonster: 32228-88, 6d.7h.54m
    fanboy-social: 23419-28, 2d.6h.17m
    ublock-annoyances: 4459-4, 2d.6h.15m
    dpollock-0: 10369-484, 6d.7h.54m
    RUS-0: 41505-249, 5h.12m
  default: 
    user-filters: 26-0, never
    ublock-filters: 32171-78, 2d.6h.30m
    ublock-badware: 4143-3, 2d.6h.29m
    ublock-privacy: 228-0, 2d.6h.28m
    ublock-abuse: 75-0, 2d.6h.27m
    ublock-unbreak: 1838-1, 2d.6h.26m
    adguard-mobile: 7773-194, 2d.6h.24m
    easylist: 67662-965, 2d.6h.23m
    easyprivacy: 27114-10727, 2d.6h.20m
    urlhaus-1: 8814-0, 5h.10m
    plowe-0: 3671-3, 6d.7h.54m
    ublock-quick-fixes: 193-0, 5h.7m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 25
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5832 ms (selfie)
  maxAssetCacheWait: 4402 ms
popupPanel: 
  blocked: 6
  no-large-media: true
  blockedDetails: 
    adpushup.com: 1
    googletagmanager.com: 2
    gstatic.com: 3
```
</details>

**Comment by krystian3w** [comment]
AdGuard Base is not regional, @DandelionSprout tries enforce enable for only one language.

**Comment by Branzeturi** [comment]
@Alex-302

**Comment by byzantium225** [comment]
seems like the ads are gone but there are empty spaces :(, would be great if those removed too

**Comment by mapx-** [comment]
Test

```
smallseotools.com##.mx-auto:has(.adsbygoogle):style(height: 1px !important)
smallseotools.com##div.my-3.mx-auto
```
