### ISSUE TITLE
easeus.com: ads

### ISSUE THREAD

**Issue by reddraegon** [uBlockOrigin/uAssets#13514]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.easeus.com/partition-manager-software/antimalware-service-executable-high-disk-usage.html`

### Category

ads

### Describe the issue

Annoying overlays

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture1](https://user-images.githubusercontent.com/56732705/171456158-4ca74221-ec8e-4bd6-9d22-929e5dfeceab.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 84651
  cosmetic: 51078
  scriptlet: 17332
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7839-8, 5h.28m
    POL-2: 1273-13, 5h.29m
    easylist: 67783-75, 5h.26m
    easyprivacy: 27117-122, 5h.25m
    plowe-0: 3670-816, 5h.41m
    ublock-abuse: 75-0, 5h.38m
    ublock-badware: 4159-96, 5h.36m
    ublock-filters: 31579-138, 5h.35m
    ublock-privacy: 222-2, 5h.33m
    ublock-quick-fixes: 192-12, 5h.32m
    ublock-unbreak: 1825-43, 5h.31m
    urlhaus-1: 8814-0, 5h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 798 ms (selfie)
  maxAssetCacheWait: 583 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    addthis.com: 1
    bing.com: 1
    clarity.ms: 1
    cloudflareinsights.com: 1
    googletagmanager.com: 1
    qbox.me: 1
    trustpilot.com: 1
```
</details>

**Comment by mapx-** [comment]
If you are talking about the bottom one it's self-promotion.

Add in "my filters"

`easeus.com##[class*="banner"]`
