### ISSUE TITLE
paraphraser.io: detection

### ISSUE THREAD

**Issue by R-Vivek-S** [uBlockOrigin/uAssets#13519]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.paraphraser.io/`

### Category

detection

### Describe the issue

This website detects uBO and prompts to disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83573
  cosmetic: 43655
  scriptlet: 17083
  html: 662
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32179-32, 1d.3h
    ublock-badware: 4163-3, 1d.3h.3m
    ublock-privacy: 228-0, 4d.23h.11m
    ublock-abuse: 75-0, 4d.23h.12m
    ublock-unbreak: 1833-1, 1d.3h.1m
    easylist: 67761-601, 1d.3h.2m
    easyprivacy: 27117-580, 1d.2h.59m
    urlhaus-1: 9135-0, 44m
    plowe-0: 3673-3, 12d.22h.53m
    ublock-quick-fixes: 188-1, 45m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 341 ms (selfie)
  maxAssetCacheWait: 538 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    snigelweb.com: 3
```
</details>

**Comment by krystian3w** [comment]
I reproduced, so this no longer works:

https://github.com/uBlockOrigin/uAssets/blob/772b5f9c1825b34edf2fa462f664ebed9c4caef1/filters/filters-2021.txt#L6406-L6410
