### ISSUE TITLE
EasyList filter: doesn't permit to open mail embedded links in Gmail Web

### ISSUE THREAD

**Issue by ftarlao** [uBlockOrigin/uAssets#1352]
I have a problem with [https://mail.google.com](https://mail.google.com)

### Describe the issue
EasyList filter prevent me to open embedded links in emails (clicking on them does nothing). Putting gmail in whitelist and clicking on one embedded link, it opens in a new tab.

### Versions

- Browser/version: Firefox 57.0.4
- uBlock Origin version: 1.14.24

### Settings

I have left UBlock on defaults

### Notes
Perhaps is not a filter defect, in that case one Ublock whitelist for disabling specific filters will be great

**Comment by mapx-** [comment]
update easylist and test again

**Comment by ftarlao** [comment]
Works like a charm, thank you.
