### ISSUE TITLE
ads.8designers.com false positive

### ISSUE THREAD

**Issue by fantasticsiur** [uBlockOrigin/uAssets#13521]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ads.8designers.com/`

### Describe the issue

Page gets flagged as false positive. It's an ads generator. 

### uBlock Origin version

1.42.4

### Browser name and version

Version 102.0.5005.63 

### Settings

I tried unblocking everything but even that didn't seem to fix it. I have to open the page in incognito to work properly.

**Comment by mapx-** [comment]
Easylist issue @ryanbr
