### ISSUE TITLE
news.sky.com: breakage

### ISSUE THREAD

**Issue by fabio-piras** [uBlockOrigin/uAssets#13525]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://news.sky.com/watch-live`

### Category

breakage

### Describe the issue

Live content video is not loading when the plugin is ON

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 88413
  cosmetic: 51057
  scriptlet: 17100
  html: 667
listset (total-discarded, last updated): 
  added: 
    ITA-0: 13047-1, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32223-51, 2m
    ublock-badware: 4169-3, 2m
    ublock-privacy: 228-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1837-0, 2m
    ublock-quick-fixes: 198-0, 2m
    easylist: 67816-587, 2m
    easyprivacy: 27141-581, 2m
    urlhaus-1: 8219-0, 2m
    plowe-0: 3670-3, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2610 ms (selfie)
  maxAssetCacheWait: 1115 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    adobedtm.com: 4
    dotmetrics.net: 1
    googletagservices.com: 1
    indexww.com: 2
    outbrain.com: 1
    sharethrough.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||assets.adobedtm.com/*-source.min.js$script,domain=news.sky.com`

@ryanbr
