### ISSUE TITLE
aniworld.to: popups

### ISSUE THREAD

**Issue by Rubyurek** [uBlockOrigin/uAssets#13528]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aniworld.to/`

### Category

popups

### Describe the issue

Everytime when i pause or start the video then i get a pop up into my tabbar.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 84604
  cosmetic: 47310
  scriptlet: 17138
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5791-0, 1h.1m
    easylist: 67819-56, 1h.1m
    easyprivacy: 27142-132, 1h.1m
    plowe-0: 3670-808, 1h.1m
    ublock-abuse: 75-0, 1h.1m
    ublock-badware: 4165-91, 1h.1m
    ublock-filters: 31604-99, 1h.1m
    ublock-privacy: 222-2, 1h.1m
    ublock-quick-fixes: 199-11, 1h.1m
    ublock-unbreak: 1825-41, 1h.1m
    urlhaus-1: 7938-0, 1h.1m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 278 ms (selfie)
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    ads-twitter.com: 1
    imasdk.googleapis.com: 1
    simplysemblance.com: 1
    yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
It was fixed 22 minutes ago. Just force update `uBlock filters`

**Comment by Rubyurek** [comment]
i forced it many times and i still get pop ups.
