### ISSUE TITLE
[nsfw] uniondht.org: detection

### ISSUE THREAD

**Issue by Morpheen** [uBlockOrigin/uAssets#13524]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uniondht.org/topic/2069364-aria-valencia.html`

### Category

detection

### Describe the issue

Site doesn't allow viewing screenshots of the movie, if an adblocker is detected, by replacing the image.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Capture](https://user-images.githubusercontent.com/25306776/171621081-3456d473-eee4-4ecd-a261-a7584b3729f8.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 147690
  cosmetic: 144668
  scriptlet: 52902
  html: 674
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25836-62, 13m
    adguard-generic: 64450-5620, 13m
    adguard-mobile: 7805-155, 13m
    adguard-spyware: 27018-1003, 13m
    curben-phishing: 13300-1, 13m
    adguard-annoyance: 53728-1737, 13m
    adguard-social: 17531-31, 13m
    ublock-annoyances: 4440-4, 13m
    dpollock-0: 10373-524, 13m
  default: 
    user-filters: 16-2, never
    ublock-filters: 32223-3143, 13m
    ublock-badware: 4169-3, 13m
    ublock-privacy: 228-0, 13m
    ublock-abuse: 75-0, 13m
    ublock-unbreak: 1837-0, 13m
    easylist: 67816-928, 13m
    easyprivacy: 27141-10724, 13m
    urlhaus-1: 8219-0, 13m
    plowe-0: 3670-3, 13m
    ublock-quick-fixes: 198-0, 13m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1480 ms
  maxAssetCacheWait: 806 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    kotikinar2ko8tiki09.com: 2
    nighter.club: 1
    traffer.net: 2
    trtjigpsscmv9epe10.com: 2
    ulogin.ru: 2
    yadro.ru: 3
    yandex.ru: 2
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce.

**Comment by mapx-** [comment]
I get the message even disabling uBO

`Внимание! AdBlock блокирует показ скриншотов, все вопросы к разработчикам )))`

**Comment by MasterKia** [comment]
That's a placebo message.

**Comment by MasterKia** [comment]
That's a placebo message but the screenshots section is blocked for him.

**Comment by MasterKia** [comment]
> * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists



> ```yaml
>   added: 
>     https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25836-62, 13m
>     adguard-generic: 64450-5620, 13m
>     adguard-mobile: 7805-155, 13m
>     curben-phishing: 13300-1, 13m
>     adguard-annoyance: 53728-1737, 13m
>     adguard-social: 17531-31, 13m
>     dpollock-0: 10373-524, 13m
> ```
