### ISSUE TITLE
Browser extension uBlock Origin blocks the receive of Branch SDK from https://api2.branch.io/v1/url

### ISSUE THREAD

**Issue by Alexeyyy** [uBlockOrigin/uAssets#13538]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://api2.branch.io/v1/url

### Describe the issue

We are facing the issue when trying to get Branch SDK (https://help.branch.io/using-branch/docs/creating-a-deep-link) via the request https://api2.branch.io/v1/url. This service helps us to generate QR-codes.

**Note for the Developer** about how to repeat the issue in a real life:
1. register store with https://my.ecwid.com/cp/#dashboard:wizard=tiles
2. go to #mobile page (screenshot 1)
3. turn on uBlock Origin Plugin in the Browser.
4. press the button "Get the app" and watch the Network in Browser DevTools. Filter it like on the screenshot 2.

Without uBlock everything works smoothly.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3105537/171843697-3f33e813-9973-48bd-979c-b8fb69e86e9d.png)
![image](https://user-images.githubusercontent.com/3105537/171843837-59d6e4a3-d18d-4a62-b688-b5c10c9d9dcd.png)

### uBlock Origin version

1.42.4

### Browser name and version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36

### Settings

No changes were made for uBlock Origin Plugin since its installation.

### Notes

Feel free to contact me if You have any questions and Thanks in Advance!

**Comment by mapx-** [comment]
Test

```
@@||cdn.branch.io/branch-latest.min.js$script,domain=ecwid.com
@@||app.link/_r?sdk$script,domain=ecwid.com
@@||api2.branch.io/v1/url$xhr,domain=ecwid.com
```

EP issue @ryanbr

**Comment by mapx-** [comment]
I asked you to test those filters (add them in "my filters").
I also notified easyprivacy maintainer where the filters should belong.

first step => test the filters

**Comment by Alexeyyy** [comment]
Rules work! I got the QR code with the active plugin.
Thanks! What is the ETA of these rules to be added to the rules file?

**Comment by mapx-** [comment]
waiting easyprivacy decision I added the filters to quick fixes list. Obviously will fix only the users using uBlock Origin.
If a fix will be added in easyprivacy will work for all adblockers.

**Comment by Alexeyyy** [comment]
Great! Thanks a lot!

**Comment by Alexeyyy** [comment]
And could you please extend the rules' scope for different domains?
The reason is that we distribute Ecwid not only under ecwid.com, but under another domains as well (via Partnership programs).

**Comment by Alexeyyy** [comment]
Doing smth like:
```
@@||cdn.branch.io/branch-latest.min.js$script,domain=*
@@||app.link/_r?sdk$script,domain=*
@@||api2.branch.io/v1/url$xhr,domain=*
```

where * means any domain

**Comment by ryanbr** [comment]
remove the requirements for third-parties if its blocked. This is NOT good for privacy. ^

**Comment by mapx-** [comment]
> And could you please extend the rules' scope for different domains?

You should provide a list of these domains.

**Comment by Alexeyyy** [comment]
I understand but we have many domains of partners that require that QR code. E.g. shopsettings.com. 
I cannot show all of them due to NDA :(

**Comment by ryanbr** [comment]
We literally have no fixes for branch.io and app.link and suddenly we need to whitelist everything from branch, so I'm skeptical this is a legit request. Bad faith request.

**Comment by mapx-** [comment]
> list of these domains

This is just to help them - `branch.io` also uses fingerprinting (this is why we can't whitelist all branch.io material), so it's a major concern on privacy stuff

**Comment by Alexeyyy** [comment]
And you're right too - I can't disagree. 
Anyway, I'll get back soon to this thread asking the management about sharing the domain list. Stay tuned.
BTW, which email I can send it (to not share it here)?

**Comment by mapx-** [comment]
and / or `misu39@mail.com`

You should provide test accounts for those domains

**Comment by Alexeyyy** [comment]
Unfortunately, I can't give you domains. So please set the rules up for this one:
```
ecwid.com
```
as was the initial goal)

Thanks in advance!

**Comment by Alexeyyy** [comment]
Hello!
Another one is blocked.
![image](https://user-images.githubusercontent.com/3105537/172139350-ff3cd477-8aa2-493b-b457-694fe6684019.png)

Here is the url: https://api2.branch.io/v1/open
Could you please add it as well for ecwid.com?

cc: @mapx-

**Comment by mapx-** [comment]
provide the test link

**Comment by Alexeyyy** [comment]
False alarm, sorry for mention - I checked once again and everything works smoothly)
