### ISSUE TITLE
newcleo.com: breakage

### ISSUE THREAD

**Issue by Quanterxotur** [uBlockOrigin/uAssets#13534]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.newcleo.com/`

### Category

breakage

### Describe the issue

Site starts with a central image of an atom (with rotating electrons). after 2 seconds the full home page should be loaded (attached preview). 
While it's "freezed" with atom image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlock Preview](https://user-images.githubusercontent.com/63197953/171720271-3b9fa5a8-d151-42c0-b649-d8ca4c01641e.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 88070
  cosmetic: 51014
  scriptlet: 17084
  html: 662
listset (total-discarded, last updated): 
  added: 
    ITA-0: 13049-3, 1h.13m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32163-51, 1d.6h.28m
    ublock-badware: 4173-3, 1d.6h.27m
    ublock-privacy: 228-0, 23h.36m
    ublock-abuse: 75-0, 23h.35m
    ublock-unbreak: 1837-0, 1d.6h.26m
    ublock-quick-fixes: 198-0, 5h.15m
    easylist: 67789-608, 1d.6h.25m
    easyprivacy: 27117-131, 1d.6h.23m
    urlhaus-1: 7938-0, 5h.14m
    plowe-0: 3670-451, 23h.34m
filterset (user): [empty]
switchRuleset: 
  added: [array of 167 redacted]
modifiedUserSettings: 
  largeMediaSize: 500
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1311 ms (selfie)
  maxAssetCacheWait: 819 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    piwik.pro: 1
```
</details>

**Comment by mapx-** [comment]
Disable all other addons and test again.
