### ISSUE TITLE
goplextor.com: breakage

### ISSUE THREAD

**Issue by Eziohawk** [uBlockOrigin/uAssets#13547]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goplextor.com/cn/Support/Downloads`

### Category

breakage

### Describe the issue

After enabling the ublock extension, the download button in this interface is disabled. After disabling uBlockOrigin, the download function of this page returned to normal.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 101793
  cosmetic: 53877
  scriptlet: 17242
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28996-90, 2d.10h.29m
    easylist: 67809-69, 2d.6h.31m
    easyprivacy: 27123-148, 2d.10h.30m
    plowe-0: 3670-809, 1d.3h.7m
    ublock-abuse: 75-0, 9d.1h.3m
    ublock-badware: 4170-96, 2d.10h.28m
    ublock-filters: 31600-121, 2d.10h.31m
    ublock-privacy: 222-2, 7d.17h.45m
    ublock-quick-fixes: 203-10, 2h.32m
    ublock-unbreak: 1827-43, 2d.10h.27m
    urlhaus-1: 8763-0, 2h.33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 435 ms (selfie)
  maxAssetCacheWait: 87 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce.
I was able download a file: `https://www.goplextor.com/cn/uploadFile/d3217....`

**Comment by Eziohawk** [comment]
> I can't reproduce. I was able download a file: `https://www.goplextor.com/cn/uploadFile/d3217....`

Oh well, thanks for your reply. I temporarily disabled this extension and it quickly solved the problem. I just want to upgrade the firmware of my computer's solid-state drive, and it is quite unexpected to encounter this bug.😊
