### ISSUE TITLE
posh-samples.com: breakage

### ISSUE THREAD

**Issue by Yannik** [uBlockOrigin/uAssets#13546]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://posh-samples.com/2021/12/04/the-missing-set-gppermission-powershell-function/`

### Category

breakage

### Describe the issue

The main content of the page is not displayed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Current:
![Screenshot from 2022-06-04 00-46-23](https://user-images.githubusercontent.com/801996/171963815-4c62999f-7a1a-4585-bbee-55e4aa70a5db.png)

Should look like:
![Screenshot from 2022-06-04 00-46-42](https://user-images.githubusercontent.com/801996/171963830-f2950dd7-db51-4216-82c4-16257b5f4e56.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 83270
  cosmetic: 43691
  scriptlet: 17092
  html: 667
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 1-0, never
    ublock-filters: 32219-43, 1d.8h.47m
    ublock-badware: 4169-3, 1d.8h.45m
    ublock-privacy: 219-0, 10d.14h.35m
    ublock-abuse: 75-0, 10d.14h.34m
    ublock-unbreak: 1837-0, 1d.8h.46m
    easylist: 67819-582, 1d.8h.44m
    easyprivacy: 27117-579, 2d.10h.46m
    plowe-0: 3671-3, 11d.12h.40m
    urlhaus-1: 8763-0, 7h.18m
    ublock-quick-fixes: 200-0, 7h.17m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 25 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4033 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
The problem is `##.category-ad:not(html):not(body)` from the EasyList.

`posh-samples.com#@#.category-ad:not(html):not(body)`

**Comment by MasterKia** [comment]
The problem is `##.category-ad:not(html):not(body)` from the EasyList.

Solution: `posh-samples.com#@#.category-ad:not(html):not(body)`

**Comment by MasterKia** [comment]
@ryanbr
