### ISSUE TITLE
linuxquestions.org: ads

### ISSUE THREAD

**Issue by byzantium225** [uBlockOrigin/uAssets#13542]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.linuxquestions.org/questions/`

### Category

ads

### Describe the issue

there's a little "Advertisement" section, uBO blocks the ads but text is still there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_2022-06-03-22-17-18-85_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/102585192/171910007-2af6fd84-bb4c-4c04-b347-5d510f569040.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 172183
  cosmetic: 280790
  scriptlet: 37617
  html: 682
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-1445, 4m
    https://www.i-dont-care-about-cookies.eu/abp/: 24928-8856, 4m
    adguard-generic: 64466-5286, 5m
    adguard-spyware: 27017-1006, 4m
    adguard-spyware-url: 613-14, 4m
    block-lan: 43-0, 4m
    curben-phishing: 13863-2, 4m
    curben-pup: 255-0, 4m
    adguard-annoyance: 53768-5377, 4m
    adguard-social: 17548-1097, 4m
    fanboy-thirdparty_social: 68-0, 4m
    fanboy-annoyance: 72097-56561, 4m
    fanboy-cookiemonster: 32887-96, 4m
    fanboy-social: 23430-28, 4m
    ublock-annoyances: 4460-4, 4m
    dpollock-0: 10373-485, 4m
    RUS-0: 41524-249, 4m
  default: 
    user-filters: 26-0, never
    ublock-filters: 32333-79, 5m
    ublock-badware: 4170-3, 5m
    ublock-privacy: 228-0, 5m
    ublock-abuse: 75-0, 5m
    ublock-unbreak: 1842-1, 5m
    ublock-quick-fixes: 202-0, 5m
    adguard-mobile: 7812-194, 5m
    easylist: 67887-925, 4m
    easyprivacy: 27145-10729, 4m
    urlhaus-1: 8763-0, 4m
    plowe-0: 3638-3, 4m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 25
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9481 ms (selfie)
  maxAssetCacheWait: 4479 ms
popupPanel: 
  blocked: 9
  no-large-media: true
  blockedDetails: 
    linuxquestions.org: 6
    datadoghq-browser-agent.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`linuxquestions.org##.vbmenu_control:has-text(Advertisement)`

@ryanbr
