### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by PufflyMan** [uBlockOrigin/uAssets#13543]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=I0orEUD5I6A`

### Category

ads

### Describe the issue

When I open youtube, it just gives the ads. It doesn't matter that I reactivated the uBO, refreshed the page and etc.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85767
  cosmetic: 48464
  scriptlet: 17351
  html: 0
listset (total-discarded, last updated): 
  added: 
    spa-0: 3891-36, 1d.7h.22m
    spa-1: 4505-169, 2d.11h.15m
  default: 
    user-filters: 0-0, never
    easylist: 67778-50, 2d.11h.13m
    easyprivacy: 27121-122, 2d.11h.14m
    plowe-0: 3670-807, 12h.55m
    ublock-abuse: 75-0, 12h.56m
    ublock-badware: 4159-96, 2d.11h.12m
    ublock-filters: 31574-156, 2d.11h.16m
    ublock-privacy: 222-2, 3d.11h.16m
    ublock-quick-fixes: 198-13, 1d.7h.23m
    ublock-unbreak: 1826-42, 8h.53m
    urlhaus-1: 8219-0, 1d.7h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9314 ms (selfie)
  maxAssetCacheWait: 700 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    googlesyndication.com: 1
    youtube.com: 16
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
