### ISSUE TITLE
pornomico.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1355]
URL(s) where the issue occurs

`https://www.pornomico.com/videos/krystal-jordan-tiene-dentro-grandes-pollas-18671/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
