### ISSUE TITLE
distrowatch.com: ads

### ISSUE THREAD

**Issue by byzantium225** [uBlockOrigin/uAssets#13557]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://distrowatch.com/`

### Category

ads

### Describe the issue

there's some kind of sponsor thing which is blocked but there's empty space.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-06-04-21-22-57-90_9c7ad408470e52983cc8816adf9ff347](https://user-images.githubusercontent.com/102585192/172013788-4888d623-0086-4f8c-a151-3e80b708ab55.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 100
filterset (summary): 
  network: 170875
  cosmetic: 225647
  scriptlet: 37604
  html: 682
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64466-5258, 23h.12m
    adguard-spyware: 27017-1006, 23h.12m
    adguard-spyware-url: 613-14, 23h.12m
    block-lan: 43-0, 23h.12m
    curben-phishing: 13863-2, 23h.12m
    curben-pup: 255-0, 23h.12m
    adguard-annoyance: 53768-4766, 23h.12m
    adguard-social: 17548-34, 23h.12m
    fanboy-thirdparty_social: 68-0, 23h.12m
    fanboy-annoyance: 72097-56499, 23h.12m
    fanboy-cookiemonster: 32887-96, 23h.12m
    fanboy-social: 23430-1091, 23h.12m
    ublock-annoyances: 4460-4, 23h.12m
    dpollock-0: 10373-485, 23h.12m
    RUS-0: 41524-274, 23h.11m
  default: 
    user-filters: 26-0, never
    ublock-filters: 32333-79, 23h.12m
    ublock-badware: 4170-3, 23h.12m
    ublock-privacy: 228-0, 23h.12m
    ublock-abuse: 75-0, 23h.12m
    ublock-unbreak: 1842-1, 23h.12m
    ublock-quick-fixes: 202-0, 23h.12m
    adguard-mobile: 7812-194, 23h.12m
    easylist: 67887-940, 23h.12m
    easyprivacy: 27145-10727, 23h.12m
    urlhaus-1: 8763-0, 23h.12m
    plowe-0: 3638-3, 23h.12m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 25
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4008 ms (selfie)
  maxAssetCacheWait: 1837 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    distrowatch.com: 1
    googlesyndication.com: 1
    media.net: 3
    s-onetag.com: 2
    unblockia.com: 2
```
</details>

**Comment by mapx-** [comment]
Test

```
distrowatch.com##[href*="3cx"]:upward(tbody)
distrowatch.com##[href*="utm"]:upward(tbody)
```
