### ISSUE TITLE
wetransfer.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#13552]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wetransfer.com/`

### Category

nuisance

### Describe the issue

Full screen cookie warning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-05-23 at 13-29-08 WeTransfer - Send Large Files   Share Photos Online - Up to 2GB Free](https://user-images.githubusercontent.com/101707608/171994558-89374e46-02f7-4c29-9016-e363513a92cd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 192748
  cosmetic: 222491
  scriptlet: 36552
  html: 675
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 863-6, 22h.14m
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1956-14, 22h.14m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 43560-2313, 22h.14m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-0, 22h.14m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 12-0, 22h.14m
    https://www.fanboy.co.nz/enhancedstats.txt: 2995-1963, 22h.14m
    https://www.i-dont-care-about-cookies.eu/abp/: 24928-8853, 22h.14m
    adguard-generic: 64473-5400, 22h.14m
    adguard-mobile: 7802-194, 22h.14m
    adguard-spyware: 27016-1018, 22h.14m
    adguard-annoyance: 53751-4753, 22h.14m
    adguard-social: 17164-1118, 22h.14m
    fanboy-thirdparty_social: 68-0, 22h.14m
    fanboy-annoyance: 72073-56975, 22h.14m
    fanboy-cookiemonster: 32863-98, 22h.14m
    fanboy-social: 23430-31, 22h.14m
    ublock-annoyances: 4440-8, 22h.14m
    dpollock-0: 10373-488, 22h.14m
    adguard-spyware-url: 613-14, 22h.14m
    block-lan: 43-0, 22h.14m
    [2 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 32237-203, 22h.14m
    ublock-badware: 4170-3, 22h.14m
    ublock-privacy: 228-0, 22h.14m
    ublock-abuse: 75-4, 22h.14m
    ublock-unbreak: 1838-2, 22h.14m
    easylist: 67849-3450, 22h.14m
    easyprivacy: 27145-11095, 22h.14m
    urlhaus-1: 8903-0, 22h.14m
    plowe-0: 3668-5, 22h.14m
    GRC-0: 1002-1, 22h.14m
    ublock-quick-fixes: 198-0, 22h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12247 ms (selfie)
  maxAssetCacheWait: 2033 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cloudflare.com: 1
    google.gr: 1
    googletagmanager.com: 1
    wetransfer.net: 2
```
</details>

**Comment by mapx-** [comment]
If you don't click "I accept" / "No thanks" and then "I agree" it seems you cannot use this service.

**Comment by MasterKia** [comment]
More like `cantfix`.
