### ISSUE TITLE
zh.zixmailencryption.com: popups

### ISSUE THREAD

**Issue by YinziMike** [uBlockOrigin/uAssets#13565]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zh.zixmailencryption.com/`

### Category

popups

### Describe the issue

https://user-images.githubusercontent.com/104178195/172034619-52b2a688-8f99-4a5e-8284-7779e29cd3c4.png
https://user-images.githubusercontent.com/104178195/172034620-cc3655ca-b02f-4d79-a219-260b5b13636e.png
https://user-images.githubusercontent.com/104178195/172034824-944d9f18-5dc4-40c0-a5e2-6ee9074ab684.png

This website has sent me hundreds of pop-up ads since I visited it, though it looks like an ordinary program teaching website
And most of their ads are from other viral / pornographic websites

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 101715
  cosmetic: 53842
  scriptlet: 17230
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28990-90, 3d.14h.51m
    easylist: 67792-69, 3d.14h.43m
    easyprivacy: 27117-148, 3d.14h.42m
    plowe-0: 3670-809, 3d.14h.41m
    ublock-abuse: 75-0, 3d.14h.39m
    ublock-badware: 4159-96, 3d.14h.37m
    ublock-filters: 31548-120, 3d.14h.36m
    ublock-privacy: 222-2, 3d.14h.35m
    ublock-quick-fixes: 203-8, 13h.16m
    ublock-unbreak: 1827-43, 3d.14h.33m
    urlhaus-1: 8727-0, 8m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 313 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 1
  no-popups: true
  blockedDetails: 
    optad360.io: 1
```
</details>

**Comment by MasterKia** [comment]
Those seem like notifications to me, not popups; maybe you allowed the site to send you notifications.

Could you reset the notifications permission by clicking on the "lock icon" next to the address bar?

**Comment by MasterKia** [comment]
The site loads `di5.biz/sw/w1s.js` and `us07.biz/?te=he4tgmrwmm5ha3ddf42tamzz` for push notifcation.

```
||di5.biz^$domain=zixmailencryption.com
||us07.biz^$domain=zixmailencryption.com
```

**Comment by MasterKia** [comment]
I could reproduce by visiting `https://zh.zixmailencryption.com/tips-solving-crashing-issues-elex-windows-10`.

**Comment by mapx-** [comment]
yes, my chrome automatically is blocking that crap.

**Comment by MasterKia** [comment]
Good, it wasn't blocked on Vivaldi.

**Comment by MasterKia** [comment]
Good, it wasn't blocked on Vivaldi.
He seems to have Chrome as well though.

**Comment by mapx-** [comment]
@YinziMike you can disable all notifications or just for that site:

all notifications
chromium browsers: go to: 
chrome://settings/content/notifications

or only for that site: click the icon on the left and turn OFF the notifications for that site
![image](https://user-images.githubusercontent.com/10303732/172036980-b362eb2b-e285-418b-afd0-f45204d2fd65.png)


for firefox similar:
see here => https://sendpulse.com/knowledge-base/push-notifications/enable-disable-push-notifications-mozilla-firefox#:~:text=Go%20to%20the%20browser%20menu,appear%20until%20you%20restart%20Firefox.
