### ISSUE TITLE
photopea.com: ads

### ISSUE THREAD

**Issue by Ambahthukhan** [uBlockOrigin/uAssets#13563]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.photopea.com/`

### Category

Anti adblock in chrome

### Describe the issue

anti adblock, detects UbO and displays self-ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 99
filterset (summary): 
  network: 83109
  cosmetic: 43644
  scriptlet: 17074
  html: 667
listset (total-discarded, last updated): 
  default: 
    user-filters: 63-29, never
    ublock-filters: 32224-88, 2d.11h.15m
    ublock-badware: 4169-3, 2d.11h.14m
    ublock-privacy: 228-0, 8h.45m
    ublock-abuse: 75-0, 8h.44m
    ublock-unbreak: 1837-0, 2d.11h.13m
    easylist: 67819-513, 2d.11h.12m
    easyprivacy: 27142-592, 2d.11h.11m
    urlhaus-1: 8654-0, 4h.43m
    plowe-0: 3671-3, 12d.11h.36m
filterset (user): [array of 63 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1934 ms (selfie)
  maxAssetCacheWait: 1412 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    uniconsent.com: 3
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate https://github.com/uBlockOrigin/uAssets/issues/13094

Please enable the "_**uBlock Annoyances**_" list from uBlock Origin settings, Filter lists tab.

**Comment by MasterKia** [comment]
Or add these to "_My filters_" if you don't wish to enable any additional list:
```
photopea.com##+js(no-fetch-if, /googlesyndication|uniconsent/)
photopea.com##+js(set, console.clear, noopFunc)
```
