### ISSUE TITLE
turbo1.co: detection

### ISSUE THREAD

**Issue by alooool** [uBlockOrigin/uAssets#13569]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.turbo1.co/2021/02/2022-hyundai-ioniq-5-review.html`

### Category

detection

### Describe the issue

it says "close the ad blocker"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 102650
  cosmetic: 53589
  scriptlet: 17203
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 27702-24, 1d.20h.17m
    ara-0: 2573-7, 8h.15m
    easylist: 67849-373, 1d.20h.16m
    easyprivacy: 27145-443, 1d.20h.15m
    plowe-0: 3669-814, 5d.23h.44m
    ublock-abuse: 75-1, 1d.20h.19m
    ublock-badware: 4165-97, 1d.20h.14m
    ublock-filters: 31611-226, 1d.20h.13m
    ublock-privacy: 222-2, 1d.20h.18m
    ublock-quick-fixes: 203-10, 8h.14m
    ublock-unbreak: 1826-40, 1d.20h.12m
    urlhaus-1: 8654-0, 8h.13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 523 ms (selfie)
  maxAssetCacheWait: 364 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    google-analytics.com: 1
    google.com: 3
    googlesyndication.com: 7
```
</details>

**Comment by MasterKia** [comment]
`turbo1.co##+js(aeld, load)`

**Comment by MasterKia** [comment]
`turbo1.co##+js(aeld, load)`

**Comment by MasterKia** [comment]
Also when scripts are disabled, it blocks the screen.
```
<noscript><i id=s020>
<p>Please enable JavaScript!</p>
</i></noscript>
```
https://user-images.githubusercontent.com/17685483/172041176-98328c17-d73a-4bac-bdd6-4efe7c6f23ec.png

**Comment by okiehsch** [comment]
`turbo1.co##+js(aeld, load)`
That's to broad it will disable all load events on the site.
`turbo1.co##+js(nostif, getComputedStyle, 250)`
should work.
