### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by FreyPomerantz** [uBlockOrigin/uAssets#13566]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

When I open a video in a new tab, nothing but the video loads (the video is fine but everything else on the site is gray).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/106899196/172035940-efc023ec-904c-4472-9e6a-a5daeb580893.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83363
  cosmetic: 43775
  scriptlet: 17150
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 7h.53m
  default: 
    user-filters: 0-0, never
    easylist: 67950-50, 11h.44m
    easyprivacy: 27150-122, 11h.43m
    plowe-0: 3638-781, 25m
    ublock-abuse: 75-0, 24m
    ublock-badware: 4166-91, 11h.42m
    ublock-filters: 31636-89, 11h.41m
    ublock-privacy: 222-2, 23m
    ublock-quick-fixes: 203-10, 3h.52m
    ublock-unbreak: 1825-40, 11h.40m
    urlhaus-1: 8654-0, 3h.51m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 115 ms (selfie)
  maxAssetCacheWait: 62 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    youtube.com: 15
    doubleclick.net: 3
    google.com: 5
    ytimg.com: 1
```
</details>

**Comment by MasterKia** [comment]
See: https://github.com/easylist/easylist/wiki/Youtube-Issues

> [x] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by MasterKia** [comment]
> ```yaml
>   added: 
>     https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 7h.53m
> ```

That Honey list whitelists a whole lot more than just Honey, it basically opens up wide to whitelist all sorts of trackers and domains that (may) otherwise be blocked in various lists. Using this list may have significant impacts on ad blocking or tracking.
There are a lot of general ad-serving and telemetry domains on this list. If you whitelist them, you open up a new avenue for ads, regardless of what websites you are visiting.

A few examples from that list:
```
@@||taboola.com^*
@@||quantserve.com^*
@@||connect.facebook.net^*/fbevents.js
@@||connect.facebook.net/signals/
@@||googleadservices.com/pagead/conversion.js
@@||googleadservices.com/pagead/conversion_async.js
```

Someone has made a list for Honey without all the crap in it: 
https://raw.githubusercontent.com/wefalltomorrow/HoneyAdBlockWhitelist/main/honey-probablysmart-shopping.txt

Source: https://www.reddit.com/r/pihole/comments/nzqd2u/whitelisting_honey_domains/

**Comment by MasterKia** [comment]
@mapx- Shouldn't `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt` be included in the [badlists](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt)?

It whitelists a lot of ads/tracker sites.

`https://help.joinhoney.com/article/303-how-do-i-whitelist-honey-on-my-ad-blocker-so-i-can-still-earn-honey-gold`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d83242fc3b4f705c11e008501220b4fd336bd765
