### ISSUE TITLE
filecr.com: detection

### ISSUE THREAD

**Issue by upthegraph** [uBlockOrigin/uAssets#13573]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filecr.com/windows/adobe-acrobat-pro-dc-0012?id=436769626`

### Category

detection

### Describe the issue

The website is able to detect I am using uBlock and continuosly asks to disable my ad blocker before I can download anything. The pop up is persistent and does not go away using zapper or anything

https://user-images.githubusercontent.com/97389508/172049853-16af4ce6-0774-432d-a11c-d4d9a59b2d26.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/97389508/172049857-20e88438-aace-48c6-8e99-6500080eecc7.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 142952
  cosmetic: 204230
  scriptlet: 36474
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53773-174, 4m
    adguard-generic: 64467-682, 4m
    adguard-mobile: 7804-51, 3m
    adguard-social: 17551-855, 3m
    adguard-spyware: 27018-837, 3m
    adguard-spyware-url: 613-13, 3m
    curben-phishing: 13778-0, 3m
    fanboy-annoyance: 72272-4185, 3m
    fanboy-cookiemonster: 33139-33139, 3m
    fanboy-social: 23332-23332, 3m
    fanboy-thirdparty_social: 68-21, 3m
    ublock-annoyances: 4438-222, 3m
  default: 
    user-filters: 2-0, never
    easylist: 67953-956, 3m
    easyprivacy: 27151-10457, 3m
    plowe-0: 3638-940, 3m
    ublock-abuse: 75-0, 3m
    ublock-badware: 4171-302, 3m
    ublock-filters: 31694-3694, 3m
    ublock-privacy: 222-48, 3m
    ublock-quick-fixes: 204-22, 3m
    ublock-unbreak: 1825-124, 3m
    urlhaus-1: 8727-1, 3m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 25 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1599 ms (selfie)
  maxAssetCacheWait: 1622 ms
popupPanel: 
  blocked: 13
  no-remote-fonts: true
  blockedDetails: 
    filecr.com: 5
    cloudflare.com: 3
    googlesyndication.com: 3
    googletagmanager.com: 1
    zinlab.com: 1
```
</details>

**Comment by mapx-** [comment]
- some special steps to reproduce the issue ?
- did you disable any other extension / addon ?
