### ISSUE TITLE
hdrezkagghrt2.net: ads

### ISSUE THREAD

**Issue by Studiosis** [uBlockOrigin/uAssets#13576]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdrezkagghrt2.net/`

### Category

ads

### Describe the issue

Заголовок страницы содержит огромный отступ под рекламу

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.5rc0
Chromium: 102
filterset (summary): 
  network: 161109
  cosmetic: 224915
  scriptlet: 37624
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53768-467, 1d.17h.34m
    adguard-generic: 64467-875, 1d.17h.33m
    adguard-mobile: 7813-69, 1d.17h.38m
    adguard-social: 17550-867, 1d.17h.36m
    adguard-spyware: 27017-897, 1d.17h.37m
    adguard-spyware-url: 613-13, 1d.17h.39m
    block-lan: 43-0, 27d.2h.12m
    curben-phishing: 13724-0, 17h.22m
    curben-pup: 256-0, 17h.21m
    fanboy-annoyance: 71393-4175, 8d.20h.13m
    fanboy-cookiemonster: 32290-32290, 8d.20h.14m
    fanboy-social: 23430-23408, 1d.17h.32m
    fanboy-thirdparty_social: 69-21, 8d.20h.15m
    ublock-annoyances: 4432-223, 1d.17h.35m
  default: 
    user-filters: 0-0, never
    RUS-0: 41515-8, 1d.17h.31m
    easylist: 67903-961, 1d.17h.45m
    easyprivacy: 27145-10502, 1d.17h.43m
    plowe-0: 3638-945, 1d.9h.27m
    ublock-abuse: 75-1, 1d.9h.26m
    ublock-badware: 4166-302, 1d.17h.42m
    ublock-filters: 31617-3713, 1d.17h.41m
    ublock-privacy: 222-48, 1d.9h.25m
    ublock-quick-fixes: 203-22, 9h.19m
    ublock-unbreak: 1825-124, 1d.17h.40m
    urlhaus-1: 8654-1, 17h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2504 ms (selfie)
  maxAssetCacheWait: 2618 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    franecki.net: 1
    franeski.net: 1
    jsdelivr.net: 1
    vk.com: 1
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
> RUS-0: 41515-8, 1d.17h.31m

The rules for this domain were added ~ 18 hours ago: https://github.com/easylist/ruadlist/commit/b9ff2833c8f302b5a41ea7c16278f83c9d7c6e54
