### ISSUE TITLE
watchmygf.me [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1357]
URL(s) where the issue occurs

`https://www.watchmygf.me/video/pretty-cute-babes-are-enjoying.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by dumbusernameidk** [comment]
Ad in video with countdown timer. Link in the OP still works.
