### ISSUE TITLE
bluemediafiles.com: detection

### ISSUE THREAD

**Issue by zerlkung** [uBlockOrigin/uAssets#13572]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://bluemediafiles.com/url-generator.php`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/68957345/172049430-efcfaec5-72e5-4fd1-b528-9db2ebbfd118.png)
 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![capture_20220605185912411](https://user-images.githubusercontent.com/68957345/172049418-8068ea40-4fc6-4881-9fb8-7411fab75562.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83252
  cosmetic: 43687
  scriptlet: 17123
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 67819-50, 2d.21h.46m
    easyprivacy: 27142-122, 2d.21h.45m
    plowe-0: 3671-806, 10d.4m
    ublock-abuse: 75-0, 1d.21h.17m
    ublock-badware: 4165-91, 2d.21h.44m
    ublock-filters: 31600-102, 2d.21h.43m
    ublock-privacy: 214-2, 10d.23h.55m
    ublock-quick-fixes: 203-10, 2h.49m
    ublock-unbreak: 1825-40, 2d.21h.42m
    urlhaus-1: 8727-0, 2h.48m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 749 ms (selfie)
  maxAssetCacheWait: 575 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    bluemediafiles.com: 1
    asemskull.com: 1
    bebi.com: 2
    bookljlihooli.com: 1
    d301cxwfymy227.cloudfront.net: 2
    e30c269ae1a27413f9a9e498df89d8b36dbcdacb954c22e48050f431fe.s3.amazonaws.com: 1
    google-analytics.com: 1
    patinesgaulin.com: 1
```
</details>

**Comment by mapx-** [comment]
it was fixed yesterday.
