### ISSUE TITLE
cryptomonitor.in: detection

### ISSUE THREAD

**Issue by ahmedok2022** [uBlockOrigin/uAssets#13577]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cryptomonitor.in/`

### Category

detection

### Describe the issue

![ScreenShot_20220605173657](https://user-images.githubusercontent.com/106882633/172058458-38b06ebd-cb6f-4844-a426-f1d34a571086.png)

### Screenshot(s)

![ScreenShot_20220605173657](https://user-images.githubusercontent.com/106882633/172058431-6e42c896-c6f9-4e62-bf49-80cf006d985e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 644870
  cosmetic: 301958
  scriptlet: 39386
  html: 756
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/: 342939-0, 4h.13m
    https://hblock.molinero.dev/hosts_adblock.txt: 228379-114124, 4h.13m
    adguard-generic: 64466-7035, 22h.20m
    adguard-spyware: 27018-11115, 22h.21m
    adguard-spyware-url: 613-14, 22h.21m
    block-lan: 43-0, 22h.21m
    curben-phishing: 13724-4063, 22h.21m
    curben-pup: 256-222, 22h.21m
    adguard-annoyance: 53771-4666, 22h.21m
    adguard-social: 17551-1116, 22h.21m
    fanboy-thirdparty_social: 69-0, 22h.21m
    fanboy-annoyance: 72270-248, 22h.21m
    fanboy-cookiemonster: 33138-33138, 22h.21m
    fanboy-social: 23331-23331, 22h.21m
    ublock-annoyances: 4444-56, 22h.21m
    dpollock-0: 10373-5527, 21h.51m
    ALB-0: 267-7, 8h.36m
    ara-0: 2573-16, 8h.36m
    BGR-0: 1116-18, 8h.36m
    CHN-0: 29050-7091, 8h.36m
    [30 lists not shown]: [too many]
  default: 
    user-filters: 2-0, never
    ublock-filters: 32282-360, 22h.21m
    ublock-badware: 4170-465, 22h.21m
    ublock-privacy: 228-31, 22h.21m
    ublock-abuse: 75-3, 22h.21m
    ublock-unbreak: 1837-24, 22h.21m
    ublock-quick-fixes: 203-10, 22h.21m
    easylist: 67952-14155, 6h.39m
    easyprivacy: 27150-13544, 22h.21m
    urlhaus-1: 8654-974, 22h.21m
    plowe-0: 3638-3168, 21h.51m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4040 ms (selfie)
  maxAssetCacheWait: 3174 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    adoto.net: 7
    adsfirm.com: 2
    ctengine.io: 1
    foremedia.net: 9
    googlesyndication.com: 4
    googletagmanager.com: 1
    googletagservices.com: 1
    mql5.com: 2
    orquideassp.com: 10
    wp.com: 4
```
</details>

**Comment by ahmedok2022** [comment]
still not working

**Comment by ahmedok2022** [comment]
![ScreenShot_20220605180207](https://user-images.githubusercontent.com/106882633/172059450-71ea0201-5232-4cd0-a226-fd2e0e203428.png)

**Comment by mapx-** [comment]
Did you update uBlock filters list ?
If after updating still not working => use only the default settings / lists in uBO and test again

**Comment by ahmedok2022** [comment]
yes i update ublock filters +  using only the default settings
still not working

**Comment by mapx-** [comment]
- Open the logger, reproduce the issue, go again into the logger and post here a screenshot only with the blocked requests. 
- don't use other addons during the test
- disable ETP in firefox

**Comment by ahmedok2022** [comment]
![ScreenShot_20220605184730](https://user-images.githubusercontent.com/106882633/172061298-eb1af31b-911b-433e-9fd6-3520b92377c2.png)

**Comment by ahmedok2022** [comment]
![ScreenShot_20220605185021](https://user-images.githubusercontent.com/106882633/172061368-65195687-810f-47d4-99e2-51685eb66044.png)

**Comment by mapx-** [comment]
If you respected all the last steps I asked you, I don't know what's wrong on your side.

**Comment by ahmedok2022** [comment]
any way thanks for your help
