### ISSUE TITLE
animeunity.tv: popups

### ISSUE THREAD

**Issue by tukay3kid** [uBlockOrigin/uAssets#13574]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.animeunity.tv/anime/430-naruto-shippuden/11843`

### Category

popups

### Describe the issue

when i click on an episode a popup shows, sometimes i see the ad, other times it says "uBlock Origin has prevented the following page from loading" but i get the neew tab anyways

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 88964
  cosmetic: 51146
  scriptlet: 17170
  html: 0
listset (total-discarded, last updated): 
  added: 
    ITA-0: 13049-0, 58m
  default: 
    user-filters: 0-0, never
    easylist: 67954-54, 58m
    easyprivacy: 27151-124, 58m
    plowe-0: 3638-782, 58m
    ublock-abuse: 75-0, 58m
    ublock-badware: 4171-91, 58m
    ublock-filters: 31694-97, 58m
    ublock-privacy: 222-2, 58m
    ublock-quick-fixes: 204-10, 58m
    ublock-unbreak: 1825-40, 58m
    urlhaus-1: 8659-0, 58m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 583 ms
  maxAssetCacheWait: 397 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by tukay3kid** [comment]
i still have the same issue !!

**Comment by mapx-** [comment]
Did you update `uBlock filters` list ?
