### ISSUE TITLE
gamecopyworld.eu: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13586]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gamecopyworld.eu/games/pc_tormented_souls.shtml`

### Category

ads

### Describe the issue

Il y a des encarts publicitaires et quelques soucis d'affichage lors des recherches.
"cse.google".

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/172075882-61e2bf67-be94-4482-a2bf-cbd90e679a7f.png)
![image](https://user-images.githubusercontent.com/50231020/172075894-b31b3abc-092f-4ec2-8a93-de33d7bb56f6.png)
![image](https://user-images.githubusercontent.com/50231020/172075899-19f51657-021b-41df-8c3e-7a0218636501.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 446279
  scriptlet: 29829
  html: 0
listset (total-discarded, last updated): 
    adguard-generic: 64480-1525, now
    adguard-mobile: 7805-70, now
    adguard-spyware: 27019-783, now
  default: 
    user-filters: 2139-120, never
    FRA-0: 28283-3314, now
    easylist: 67949-25247, now
    plowe-0: 3638-570, now
    ublock-abuse: 75-1, now
    ublock-badware: 4171-308, now
    ublock-filters: 31713-3779, now
    ublock-privacy: 222-41, now
    ublock-quick-fixes: 203-20, now
    ublock-unbreak: 1795-82, now
    urlhaus-1: 8659-0, now
filterset (user): [array of 2068 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1585 ms
  maxAssetCacheWait: 539 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    gamecopyworld.eu: 1
```
</details>

**Comment by Procyon-b** [comment]
Pour les pubs, essaye ce filtre:
```
||gamecopyworld.com/!_$frame
```

Pour ce qui est de la recherche, je vois que pour moi elle est bloquée par un filtre de la liste FR.

**Comment by Procyon-b** [comment]
(FR) Aucun problème pour moi, je suis belge  ;)
Et les autres utilisent probablement l'option de traduction de la page (dans chrome en tous cas)

La liste FR est bien celle d'adguard.
Si tu veux les résultats de google dans la page du site (si c'est bloqué pour toi), ajoute les filtres:
```
@@||cse.google.com^$script,domain=gamecopyworld.eu
@@||www.google.com^$3p,domain=gamecopyworld.eu
```

**Comment by Procyon-b** [comment]
Tu devrais laisser la liste FR. Elle est très utile pour tous les sites francophones.
Si tu ajoutes les 2 filtres que je t'ai donné, ils te permettront d'utiliser google sur ce site.
Le filtre de la liste FR vise gamecopyworld et pas google en particulier.

**Comment by mapx-** [comment]
@Yuki2718 @AdamWr

**Comment by krystian3w** [comment]
This is form Liste FR then maybe @smed79 may rethink block Google (remove or add 1 more domain to exeption/exclusion).


Block all scripts look like fight with nasty ads too fastly (uBo and AG can rewrite filter to `denyallow` if all Adguard apps/extensions have support).
