### ISSUE TITLE
lrepacks.net: nuisance

### ISSUE THREAD

**Issue by AhsanAshfaq1** [uBlockOrigin/uAssets#13581]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lrepacks.net/`

### Category

ads and nuisance

### Describe the issue

Ads and overlays on the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/93876609/172066905-bda9b7c1-52a4-402f-8c12-8449016aa7f7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 80939
  cosmetic: 42179
  scriptlet: 16478
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65018-167, never
    easyprivacy: 26734-100, never
    plowe-0: 3690-811, never
    ublock-abuse: 72-0, never
    ublock-badware: 3989-3, never
    ublock-filters: 30477-97, never
    ublock-privacy: 205-0, never
    ublock-quick-fixes: 139-4, never
    ublock-unbreak: 1742-29, never
    urlhaus-1: 8896-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1854 ms
  maxAssetCacheWait: 25 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    offerimage.com: 4
    untimburra.com: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
@mapx- 
Initially, this is a Russian site. Its interface can be translated into other languages using the built-in Google translator, but all the problems of this site are solved in RU AdList.

**Comment by mapx-** [comment]
yes, I saw the filters in RU AdList but as you say the site can be used by non-russians (like OP)

**Comment by dimisa-RUAdList** [comment]
No problem. I just thought I should report it.
