### ISSUE TITLE
trailsoffroad.com: nuisance

### ISSUE THREAD

**Issue by thals1992** [uBlockOrigin/uAssets#13584]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.trailsoffroad.com/trails/1864-yankee-hill-the-actual-hill`

### Category

nuisance

### Describe the issue

Their website puts up a large banner across the whole screen. I was able to use the zapper on the middle banner three times to get rid of the middle part, and once for the background that greys out. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30422974/172074136-4f5148fc-ac14-43d6-94e2-62a7ae788da0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 151827
  cosmetic: 189061
  scriptlet: 36394
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1d.4h.40m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 3d.19h.32m
    adguard-annoyance: 53721-174, 3d.19h.25m
    adguard-generic: 64432-699, 3d.19h.24m
    adguard-mobile: 7805-102, 3d.19h.27m
    adguard-spyware: 27018-1054, 3d.19h.26m
    adguard-spyware-url: 613-13, 3d.19h.28m
    dpollock-0: 10373-1458, 1d.19h.51m
    fanboy-annoyance: 72275-3121, 21m
    fanboy-cookiemonster: 32462-32453, 3d.19h.33m
    ublock-annoyances: 4430-222, 3d.19h.29m
  default: 
    user-filters: 0-0, never
    easylist: 67808-1260, 3d.19h.22m
    easyprivacy: 27141-10645, 3d.19h.23m
    plowe-0: 3668-1481, 9d.4h.45m
    ublock-abuse: 75-0, 1d.30m
    ublock-badware: 4170-312, 3d.19h.21m
    ublock-filters: 31600-3695, 3d.19h.31m
    ublock-privacy: 222-48, 1d.31m
    ublock-unbreak: 1825-125, 3d.19h.30m
    urlhaus-1: 8727-0, 19h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1189 ms (selfie)
  maxAssetCacheWait: 981 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    firstpromoter.com: 1
    google.com: 1
    googletagmanager.com: 1
    maillist-manage.com: 1
    mapbox.com: 4
    pagesense.io: 1
    youtube.com: 2
    zoho.com: 1
```
</details>

**Comment by Procyon-b** [comment]
This should work:
```
trailsoffroad.com##.modal.paywall
```

**Comment by mapx-** [comment]
@ryanbr
