### ISSUE TITLE
2the.space: detection

### ISSUE THREAD

**Issue by ahmedok2022** [uBlockOrigin/uAssets#13583]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://2the.space/`

### Category

detection

### Describe the issue

![ScreenShot_20220605221415](https://user-images.githubusercontent.com/106882633/172068835-612e3eaa-a6ac-4891-9960-1c2b3f5ffade.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 83286
  cosmetic: 43777
  scriptlet: 17132
  html: 676
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32336-100, 1h.11m
    ublock-badware: 4175-3, 1h.11m
    ublock-privacy: 228-0, 1h.11m
    ublock-abuse: 75-0, 1h.11m
    ublock-unbreak: 1807-0, 1h.11m
    ublock-quick-fixes: 203-0, 1h.11m
    easylist: 67949-489, 1h.11m
    easyprivacy: 27151-591, 1h.11m
    urlhaus-1: 8659-0, 1h.11m
    plowe-0: 3638-3, 1h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1366 ms
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    2the.space: 4
    adoto.net: 5
    adsfirm.com: 3
    ctengine.io: 1
    foremedia.net: 21
    googlesyndication.com: 1
    googletagmanager.com: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
No anti adb on my side, only the 5 seconds counter

`2the.space##+js(aeld, scroll, modal)`

**Comment by ahmedok2022** [comment]
try this link
https://2the.space/?wpsafelink=https%3A%2F%2Fzipcrypto.site%2F9hpXZQz&redir=aHR0cHM6Ly8ydGhlLnNwYWNl

**Comment by Procyon-b** [comment]
Try this filter:
```
2the.space##+js(no-fetch-if, googlesyndication.com)
```
