### ISSUE TITLE
hdrezka.website: ads

### ISSUE THREAD

**Issue by toodhoover** [uBlockOrigin/uAssets#13585]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdrezka.website/cartoons/fiction/47335-ekzodiit-2022.html`

### Category

ads

### Describe the issue

Video ads playing before video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 84731
  cosmetic: 46022
  scriptlet: 17444
  html: 692
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 32336-101, 1h.55m
    ublock-badware: 4170-3, 1h.54m
    ublock-privacy: 228-0, 8d.9h.50m
    ublock-abuse: 75-0, 8d.9h.49m
    ublock-unbreak: 1837-0, 1h.53m
    easylist: 67949-522, 1h.58m
    easyprivacy: 27151-598, 1h.57m
    plowe-0: 3668-3, 8d.9h.51m
    SWE-1: 3997-2, 1h.56m
    urlhaus-1: 8659-0, 5h.59m
    ublock-quick-fixes: 204-0, 6h
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 178 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    adpod.in: 1
    franecki.net: 6
    franeski.net: 3
    jsdelivr.net: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
russian site, enable `RUS: RU AdList `
