### ISSUE TITLE
wsj.com: breakage

### ISSUE THREAD

**Issue by tkuehn** [uBlockOrigin/uAssets#13593]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wsj.com/articles/the-power-of-the-lunch-breakand-why-so-many-of-us-are-bad-at-taking-one-11654488060?mod=hp_featst_pos5`

### Category

breakage

### Describe the issue

Clicking on the story headline shows content for a split second, then goes gray with the message: Application error: a client-side exception has occurred (see the browser console for more information). This happens on many but not all articles, the homepage seems unaffected.

This URL is the link WSJ provides to share the article without a subscription: https://www.wsj.com/articles/the-power-of-the-lunch-breakand-why-so-many-of-us-are-bad-at-taking-one-11654488060?st=z8z1rmjk63ceh00&reflink=desktopwebshare_permalink

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![browser with console](https://user-images.githubusercontent.com/6548800/172162300-9c123c1a-d8f8-4c55-a430-e60c13b3f86b.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83304
  cosmetic: 43698
  scriptlet: 17130
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 117-2, 1d.20h.31m
  default: 
    user-filters: 0-0, never
    easylist: 67819-50, 3d.22h.25m
    easyprivacy: 27142-122, 3d.22h.25m
    plowe-0: 3670-807, 3d.22h.25m
    ublock-abuse: 75-0, 3d.22h.25m
    ublock-badware: 4165-91, 3d.22h.25m
    ublock-filters: 31604-87, 3d.22h.25m
    ublock-privacy: 222-2, 3d.22h.25m
    ublock-quick-fixes: 203-10, 17h.6m
    ublock-unbreak: 1825-40, 3d.22h.25m
    urlhaus-1: 8659-0, 17h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 176 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    wsj.com: 1
    amazon-adsystem.com: 1
    demdex.net: 1
    doubleclick.net: 1
    google.com: 7
    moatads.com: 1
    newrelic.com: 1
    newscgp.com: 1
    permutive.app: 1
```
</details>

**Comment by mapx-** [comment]
You should remove `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt` => whitelisting a lot of advertising stuff

**Comment by tkuehn** [comment]
Thank you for the suggestion. I removed the Honey whitelist, then purged and updated. That didn't resolve it so I reset the browser which clears browsing data turns off all extensions. I completely removed the Honey extension. I also removed, reinstalled and enabled the uBlock Origin extension. I did not re-enable any other extension. Still have the issue.

**Comment by mapx-** [comment]
Test

`wsj.com#@#+js()`

**Comment by tkuehn** [comment]
Adding that line seems to have resolved the issue. Thanks!
