### ISSUE TITLE
zzcartoon.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1359]
URL(s) where the issue occurs

`http://www.zzcartoon.com/videos/dragonbal-characters-fuck-all.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
add
`||zzcartoon.com/*.gif$image`
