### ISSUE TITLE
tandt.posta.sk: breakage

### ISSUE THREAD

**Issue by vlado2222** [uBlockOrigin/uAssets#13599]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tandt.posta.sk/en/items/RY546804042CN`

### Category

breakage

### Describe the issue

this is official web page of Slovak national postal service and the provided link is for tracking web site. It works only if i completely disable uBlock origin for this site. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82155
  cosmetic: 43707
  scriptlet: 17094
  html: 667
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32218-98, 3d.14h.6m
    ublock-badware: 4169-3, 3d.14h.5m
    ublock-privacy: 228-0, 9d.13h.44m
    ublock-abuse: 75-0, 9d.13h.43m
    ublock-unbreak: 1837-0, 3d.14h.4m
    easylist: 67849-513, 3d.14h.3m
    easyprivacy: 27142-592, 3d.14h.2m
    urlhaus-1: 7605-0, 4h.35m
    plowe-0: 3668-3, 9d.13h.41m
    ublock-quick-fixes: 203-0, 4h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 99 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 900 ms (selfie)
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    facebook.com: 2
    google-analytics.com: 2
    google.com: 1
    maps.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment]
Works fine for me,
![image](https://user-images.githubusercontent.com/16838044/172223547-4672487f-a2cf-4070-afc8-5d3ba79d1f0c.png)

**Comment by vlado2222** [comment]
I have absolutely no idea why it doesn't work for me. This is how it looks for me. 
![posta sk](https://user-images.githubusercontent.com/106996116/172225269-5aeb54da-f03e-479d-8d34-8fbe89a3176a.PNG)
![uBlock settings](https://user-images.githubusercontent.com/106996116/172225734-5148b56d-ca3c-4b72-9ea7-017de2ab823d.png)
:

**Comment by okiehsch** [comment]
What is blocking the google.com request on your end?
It's not blocked on my end.
Open the logger and reload the site to look it up.
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by okiehsch** [comment]
I can reproduce your screenshot if I manually block your google-request, so that appears to be the cause of your problem.

**Comment by vlado2222** [comment]
Here is logger output.
![logger](https://user-images.githubusercontent.com/106996116/172227534-7688f719-36df-4358-a526-81eb4aa34828.PNG)

**Comment by okiehsch** [comment]
You have added a rule to block google.com globally, you need to remove it.

**Comment by okiehsch** [comment]
Open the my rules pane.
https://github.com/gorhill/uBlock/wiki/Dashboard:-My-rules
and post a screenshot of it's content.

**Comment by vlado2222** [comment]
@okiehsch After removing the global block for google.com it started to work. I wanted to have google.com blocked globally and then allow it per site manually if needed. I guess I did something wrong with the local "noop".

**Comment by okiehsch** [comment]
You can see if the local noop works or not if you look at the colot on the left side of the google colomn in your screenshot, red means all requests have been blocked, i.e. your noop rule does not work.
Blocking google.com globally is a recipe for site breakage if you don't know exactly what you are doing, so I would advice against it.
