### ISSUE TITLE
check-host.net: ads

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#13594]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://check-host.net/`

### Category

ads

### Describe the issue

Ads can be seen in the bottom of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 86281
  cosmetic: 48500
  scriptlet: 17361
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67818-50, 4d.6m
    easyprivacy: 27142-122, 4d.7m
    plowe-0: 3638-781, 1d.21h.1m
    spa-0: 3891-36, 16h.21m
    spa-1: 4511-169, 4d.4m
    ublock-abuse: 75-0, 1d.21h.3m
    ublock-badware: 4165-91, 4d.5m
    ublock-filters: 31599-142, 4d.3m
    ublock-privacy: 222-2, 1d.16h.57m
    ublock-quick-fixes: 204-10, 16h.22m
    ublock-unbreak: 1825-41, 4d.2m
    urlhaus-1: 8659-0, 16h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1499 ms (selfie)
  maxAssetCacheWait: 321 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by rodrigosambadesaa** [comment]
Resetted to default settings, updated lists, cleared the website's cookies and I still see the ads.

**Comment by mapx-** [comment]
- the fix should be added by easylist
- add
`check-host.net##[class^="athold"]`

or/and report at easylist repository: https://github.com/easylist/easylist/issues

@ryanbr

**Comment by rodrigosambadesaa** [comment]
it isn't solved yet: https://github.com/easylist/easylist/commit/f88d9b5a9e61bbf3fda85693cf1ba8d7180a927f#commitcomment-77641696

**Comment by mapx-** [comment]
`check-host.net##[href^="//ddos-guard.net/"]`

**Comment by rodrigosambadesaa** [comment]
That doesn't hide the ads completely. The zone where they were shown shows now ad chunks (a few crosses) and it's ugly.
https://user-images.githubusercontent.com/43375046/177154288-16e5f8bd-a73c-4e13-8d29-8670297098e4.png

**Comment by rodrigosambadesaa** [comment]
@ryanbr Please update easylist repo.

**Comment by rodrigosambadesaa** [comment]
The ads are still there.

**Comment by stephenhawk8054** [comment]
```adb
check-host.net##[id$="ddos-guard"]
check-host.net##[id$="ddos-guard2"]
```

@ryanbr

**Comment by rodrigosambadesaa** [comment]
The ads are still visible.

**Comment by mapx-** [comment]
Update again all your filter lists, I get no ad

**Comment by rodrigosambadesaa** [comment]
> Update again all your filter lists, I get no ad

Just did it, you're right.

**Comment by rodrigosambadesaa** [comment]
> `Update` again all your filter lists, I get no ad

No, just updated lists, if I don't add these rules the ads are still there.

`check-host.net##[id$="ddos-guard"]
check-host.net##[id$="ddos-guard2"]`

**Comment by rodrigosambadesaa** [comment]
> Update again all your filter lists, I get no ad

No, just updated lists, if I don't add the rules above the ads are still there.

**Comment by rodrigosambadesaa** [comment]
> > Update again all your filter lists, I get no ad
> 
> No, just updated lists, if I don't add the rules above the ads are still there.

You don't believe me? Has someone read my previous comment? If someone read it, you're going to do nothing?

I'm telling you, without any of these 

> * the fix should be added by easylist
> * add
>   `check-host.net##[class^="athold"]`
> 
> or/and report at easylist repository: https://github.com/easylist/easylist/issues
> 
> @ryanbr


> `check-host.net##[href^="//ddos-guard.net/"]:upward(1)`



> ```
> check-host.net##[id$="ddos-guard"]
> check-host.net##[id$="ddos-guard2"]
> ```
> 
> @ryanbr

the ads are still there

**Comment by mapx-** [comment]
add
`check-host.net##[title^="DDOS"]`

or
`check-host.net##*:matches-attr(id="/[\W\w]{19,}/")`

the first one could be added in EL @ryanbr  ... but they are fighting back, so you can use the second one (not for EL)

**Comment by garry-ut99** [comment]
> add `check-host.net##[title^="DDOS"]`
> the first one could be added in EL

- not needed, because the ones provided a week ago in [this comment](https://github.com/uBlockOrigin/uAssets/issues/13594#issuecomment-1420642284)  still works, the problem is that the EasyList dev didn't add them,  and instead he added own / different filters which stopped working
- also `check-host.net##[title^="DDOS"]` doesn't remove the whole ads, still chunks remain

**Comment by rodrigosambadesaa** [comment]
I don't want the site owner to win unless it's my site.

**Comment by rodrigosambadesaa** [comment]
Also in [this page](https://check-host.net/check-ping?host=wolframalpha.com&csrf_token=9200b1c2c4f0eac3cb1f4778380a41d1f2e78baa) another ad shows up
![FireShot Capture 004 - Ping server, ping website_ Check host - online website monitoring_ - check-host net](https://github.com/uBlockOrigin/uAssets/assets/43375046/2cdb6848-5d79-405a-bcd1-2828ad8c1b8e)

**Comment by rodrigosambadesaa** [comment]
Now the ads are gone, but a rest of an ad is still visible. See this screenshot.
![60aede8b-2ae2-463f-b4d3-8982ceeed320](https://github.com/uBlockOrigin/uAssets/assets/43375046/48b3be22-c462-492a-a375-aa3f0169fadc)

**Comment by rodrigosambadesaa** [comment]
I see a new ad.
![d42063e4-c39d-4a23-8e4d-05013c66ca95](https://github.com/uBlockOrigin/uAssets/assets/43375046/ed3ca9df-f405-414c-97c5-c78e8a81b9da)

**Comment by stephenhawk8054** [comment]
You mean the one above "About `check-host.net`"?

**Comment by rodrigosambadesaa** [comment]
> You mean the one above "About `check-host.net`"?

Yes.

**Comment by rodrigosambadesaa** [comment]
> > You mean the one above "About `check-host.net`"?
> 
> Yes.

Now I don't see it.

**Comment by huyszn** [comment]
I see the ad. The ad doesn't show again if I close the ad unless I clear cookies.

**Comment by rodrigosambadesaa** [comment]
The previous issue was fixed without a single commit notice in this thread. Is it going to happen again?

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because the last ad I reported is visible again.

**Comment by rodrigosambadesaa** [comment]
> They continue to fight back because the last ad I reported is visible again.

With [AdGuard AdBlocker MV3 experimental](https://chromewebstore.google.com/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf) the ad is blocked.

**Comment by rodrigosambadesaa** [comment]
Also an ad chunk (cross) is now visible near the page's footer.
![FireShot Capture 003 - Check server _ Check host - online website monitoring - check-host net](https://github.com/uBlockOrigin/uAssets/assets/43375046/99935308-f20e-4356-ae2a-70387b650129)

**Comment by rodrigosambadesaa** [comment]
> They continue to fight back because the last ad I reported is visible again.

It's different because the cross on the upper right corner is different.

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because the two ads near the page's footer are visible again.

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because the last ad I reported is visible again.

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because there's a new ad in the upper right corner.

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because the last ad I reported is visible again. Also an ad chunk (cross) is visible near the page's footer.

**Comment by rodrigosambadesaa** [comment]
Why don't keep this open, as they keep fighting back continuously?

**Comment by 055110** [comment]
Hello, they don't seem to be fighting back now. Should this still be open?

**Comment by rodrigosambadesaa** [comment]
In the past they've taken longer to fight back, I don't think it should be closed.

**Comment by stephenhawk8054** [comment]
Just continue commenting here. All volunteers are notified with new comments.

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because there's one ad visible. And please reopen just in case they fight back again in a few days after the fix.

**Comment by JobcenterTycoon** [comment]
Im monitoring the site already no need to worry.

**Comment by rodrigosambadesaa** [comment]
@JobcenterTycoon Thank you for your ongoing efforts in monitoring the site for ad circumventions. I'm curious—how are you monitoring the site? Are you using automation tools or scripts to detect changes, or are you visiting it regularly to check manually?

**Comment by rodrigosambadesaa** [comment]
Good morning. They continue to fight back because one of the ads is still visible[ when a search is made](https://check-host.net/ip-info?host=google.es&csrf_token=75b62ef244031eaa51d4864cfaa51b12bf04bbc2).
![Captura de pantalla (22)](https://github.com/user-attachments/assets/6db4a080-8a75-4291-acaf-de485c4eb803)

**Comment by rodrigosambadesaa** [comment]
With uBlock Origin Lite one ad and two ad chunks are visible.

**Comment by stephenhawk8054** [comment]
Can you switch to "Optimal" or "Complete" mode in uBOL on that site and test again?

**Comment by rodrigosambadesaa** [comment]
Using Optimal or Complete mode works.

**Comment by rodrigosambadesaa** [comment]
> > Also an ad chunk (cross) is now visible near the page's footer. ![FireShot Capture 004 - Check server _ Check host - online website monitoring - check-host net](https://private-user-images.githubusercontent.com/43375046/317009883-5925eb43-fd5e-4370-9d98-3ad860419683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODEwOTgsIm5iZiI6MTcxMTQ4MDc5OCwicGF0aCI6Ii80MzM3NTA0Ni8zMTcwMDk4ODMtNTkyNWViNDMtZmQ1ZS00MzcwLTlkOTgtM2FkODYwNDE5NjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZGY1ZTkyNzU3MWJiYTU2ZGNlNzQ4NWU2MTVjMGM4ZTYxNTg5ZmZmOGU3ODk5MTQ0NTZlYzk2MWFjMzY4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HsHciLmjg6q15GxLy6iYa51qVzQw3RdmJnpGZZZvdW4)
> 
> Which is also not visible using [AdGuard AdBlocker MV3 experimental](https://chromewebstore.google.com/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf).



> > > > They continue to fight back because the last ad I reported is visible again.
> > > 
> > > 
> > > With [AdGuard AdBlocker MV3 experimental](https://chromewebstore.google.com/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf) the ad is blocked.
> > 
> > 
> > Also an ad chunk (cross) is now visible near the page's footer. ![FireShot Capture 004 - Check server _ Check host - online website monitoring - check-host net](https://github.com/uBlockOrigin/uAssets/assets/43375046/5925eb43-fd5e-4370-9d98-3ad860419683)
> 
> Which is also not visible using [AdGuard AdBlocker MV3 experimental](https://chromewebstore.google.com/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf).

It's different because the cross on the upper right corner is different.

**Comment by xglossyntx** [comment]
Looks like you missed one on: ``https://check-host.net/articles/how_to_choose_hosting_guide?lang=en``

<details>
<summary>Screenshot</summary>

<img width="473" height="328" alt="Image" src="https://github.com/user-attachments/assets/94bf94b6-de3f-4d3b-bcb5-ab2820cc472b" />

</details>

**Comment by JobcenterTycoon** [comment]
fixed now.

**Comment by xglossyntx** [comment]
They updated some of their ads again one is visible at `https://check-host.net/check-http?host=https://1.1.1.1`

**Comment by rodrigosambadesaa** [comment]
They continue to fight back because that ad is visible [here](https://check-host.net/articles/how_to_choose_hosting_guide?lang=en) in Chrome with uBOL in Optimal or Complete mode.

**Comment by rodrigosambadesaa** [comment]
Hello? The ad is still there.

**Comment by JobcenterTycoon** [comment]
Its all fine for me.

**Comment by rodrigosambadesaa** [comment]
<img width="1919" height="1039" alt="Image" src="https://github.com/user-attachments/assets/3a960697-b130-4244-8467-e652b4880187" />

<img width="1919" height="952" alt="Image" src="https://github.com/user-attachments/assets/e59ad002-850e-4a3b-ba92-eba8da94b641" />

<img width="844" height="33" alt="Image" src="https://github.com/user-attachments/assets/b2ead189-b4e3-4c3c-9781-a9d41e4917ed" />

Not for me on Incognito mode to clarify. [Here](https://check-host.net/articles/how_to_choose_hosting_guide?lang=en). As it can be seen, the ad is still there.

**Edit: Sorry, it was a different page (edited [comment](https://github.com/uBlockOrigin/uAssets/issues/13594#issuecomment-3297559205)).**

**Comment by ghost** [comment]
No ads on my side, using FF + uBO.

**Comment by rodrigosambadesaa** [comment]
It might be regional. I also see it in Firefox with uBO and Private Window.

**Comment by rodrigosambadesaa** [comment]
Now I don't see it.

**Comment by xglossyntx** [comment]
They updated the ad at the top of this page: https://check-host.net/articles/how_to_choose_hosting_guide?lang=en.

**Comment by ghost** [comment]
I can see it too

**Comment by JobcenterTycoon** [comment]
Updated

**Comment by xglossyntx** [comment]
There appears to be an ad at the bottom of the page that is not blocked.

<details>
<summary>Screenshot</summary>
<img width="658" height="417" alt="Image" src="https://github.com/user-attachments/assets/8690fff4-e91a-4612-a320-915e0df5391c" />

**Comment by playonevideo** [comment]
Ads again:

<img width="1052" height="277" alt="Image" src="https://github.com/user-attachments/assets/d5ac94a8-103b-4ea2-908d-a8d4641dacd9" />

**Comment by playonevideo** [comment]
> Ads again:
> <img alt="Image" width="1052" height="277" src="https://private-user-images.githubusercontent.com/277447603/609882038-d5ac94a8-103b-4ea2-908d-a8d4641dacd9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcwMzg3NjcsIm5iZiI6MTc4NzAzODQ2NywicGF0aCI6Ii8yNzc0NDc2MDMvNjA5ODgyMDM4LWQ1YWM5NGE4LTEwM2ItNGVhMi05MDhkLWE4ZDQ2NDFkYWNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgxOFQwNzM0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWMxMWQ5ZDlhMDI1MWMyYTMyMTQ5MjU4M2IwMGI1YzZjNzAyMzA3MDZmM2YwOTNhN2Q3MmEyNjZmMjdiOWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.NPQleTTeh98vj6qCDh2LA3MsqriopCKvLehoR2Dv01k">

And again.
