### ISSUE TITLE
Ads via ow.ly 

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#136]
I've encountered an ad appearing on all article pages of thehackernews.com of the form ##a[href=], including ow.ly, always for **_2016 Magic Quadrant for Siem_**, i.e. at :
> http://thehackernews.com/2016/09/fbi-cia-hacker-arrested.html

I've added ##a[href*="ow.ly/"] to My Filters in order to make the rule active on all sites.

Not being a specialist I am wondering if this practice is related to this old article about Ow.ly Framejacking :
> http://www.webmaster-source.com/2009/07/31/is-ow-ly-framejacking/

Anyway the rule blocks it...

**Comment by gorhill** [comment]
No frame jacking here -- just a case of an ad for which there is no filter yet. Just report to EasyList maintainer, this ad needs no special handling.
