### ISSUE TITLE
mangaeden.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1360]
URL(s) where the issue occurs

`http://www.mangaeden.com/en/en-manga/4-cut-hero/82/10/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by mapx-** [comment]
No anti adb message for me

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
