### ISSUE TITLE
youtube.fandom.com: ads

### ISSUE THREAD

**Issue by Matthewrbowker** [uBlockOrigin/uAssets#13604]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://youtube.fandom.com/wiki/Kyle_Hill?so=search`

### Category

ads

### Describe the issue

Fandom appears to be embedding a large video player running ads at the top of their articles.  I attempted to filter it using a custom filter but UBlock was not able to do that.  Filters tried:

- `##.jw-reset.jw-video`
- `##.jw-reset.jw-wrapper`

The video player minimizes and continues playing on scroll.  Screenshots are from a completely fresh Chrome profile with a completely fresh UBlock Origin install.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1792" alt="Screen Shot 2022-06-06 at 11 43 53 PM" src="https://user-images.githubusercontent.com/802331/172305060-95c4da4c-1568-40f2-bdfd-9e8379d42e4a.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81924
  cosmetic: 43774
  scriptlet: 17139
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Matthewrbowker/filterlist/master/list.txt: 32-1, now
  default: 
    user-filters: 0-0, never
    easylist: 67903-50, 3d.7h.54m
    easyprivacy: 27145-122, 3d.7h.53m
    plowe-0: 3671-806, 12d.12h.11m
    ublock-abuse: 75-0, 3d.6h.29m
    ublock-badware: 4165-91, 3d.7h.52m
    ublock-filters: 31630-87, 3d.7h.50m
    ublock-privacy: 222-2, 3d.8h.24m
    ublock-quick-fixes: 203-10, now
    ublock-unbreak: 1825-40, 3d.7h.51m
    urlhaus-1: 7336-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 330 ms (selfie)
  maxAssetCacheWait: 294 ms
popupPanel: 
  blocked: 69
  blockedDetails: 
    fandom.com: 3
    ad.gt: 2
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    d15kdpgjg3unno.cloudfront.net: 1
    durationmedia.net: 1
    dyv1bugovvq1g.cloudfront.net: 1
    facebook.net: 1
    fastly-insights.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imrworldwide.com: 1
    jwpcdn.com: 1
    jwpltx.com: 16
    moatads.com: 1
    nocookie.net: 1
    ntv.io: 1
    pubmatic.com: 1
    quantserve.com: 1
    scorecardresearch.com: 1
    twitter.com: 1
    wikia-services.com: 28
```
</details>

**Comment by mapx-** [comment]
Test

```
youtube.fandom.com###featured-video__player
youtube.fandom.com###featured-video__player-container
```

**Comment by Matthewrbowker** [comment]
`youtube.fandom.com###featured-video__player`
<img width="1792" alt="Screen Shot 2022-06-07 at 12 02 40 AM" src="https://user-images.githubusercontent.com/802331/172307298-540cc444-77d1-418c-96eb-a70f5e5f64ac.png">

`youtube.fandom.com###featured-video__player-container`
<img width="1792" alt="Screen Shot 2022-06-07 at 12 03 28 AM" src="https://user-images.githubusercontent.com/802331/172307351-f43f3015-5b3b-45f2-8482-8a13a3c3d058.png">

Both:
<img width="1792" alt="Screen Shot 2022-06-07 at 12 03 46 AM" src="https://user-images.githubusercontent.com/802331/172307410-ba1f3ebd-0fc2-4263-b141-f06b95e4c865.png">

Side note: I expect this affects other Fandom subdomains, however; I can't find an example at this time...
