### ISSUE TITLE
uploadmx.com pp popups

### ISSUE THREAD

**Issue by piankton** [uBlockOrigin/uAssets#13605]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

upload a file to => `uploadmx.com`  then test it

### Category

popups

### Describe the issue

I download software from uploadmx and click create link download 
then this website is open a new tabs and want me to allow notification

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82221
  cosmetic: 43771
  scriptlet: 17174
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-0, never
    easylist: 67947-50, 1d.6h.47m
    easyprivacy: 27151-122, 1d.6h.46m
    plowe-0: 3638-781, 1d.6h.48m
    ublock-abuse: 75-0, 1d.6h.50m
    ublock-badware: 4171-91, 1d.6h.45m
    ublock-filters: 31707-89, 1d.6h.44m
    ublock-privacy: 222-2, 1d.6h.49m
    ublock-quick-fixes: 183-2, 6h.35m
    ublock-unbreak: 1795-41, 1d.6h.43m
    urlhaus-1: 7605-0, 6h.34m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 207 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    yonhelioliskor.com: 1
```
</details>

**Comment by MasterKia** [comment]
> I download software from uploadmx

Can you send a link from uploadmx?
