### ISSUE TITLE
fox.com ad blocker

### ISSUE THREAD

**Issue by hKQwHW** [uBlockOrigin/uAssets#13602]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.fox.com/the-simpsons/`

### Describe the issue

Can we have a filter for fox.com? 

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Version 101.0.4951.64 (Official Build) Built on Ubuntu

### Settings

- I enabled every filter other than the annoyances, regions/languages, phishing/PUP blacklist, privacy ones except EasyPrivacy, and ads except EasyList

**Comment by mapx-** [comment]
I get an episode playing, no anti adblocking stuff

![image](https://user-images.githubusercontent.com/10303732/172295808-9837b4bf-f39f-47f5-a511-8d51fbd4d051.png)

You should test using only the default settings / filter lists

**Comment by mapx-** [comment]
It's clickable chrome / FF. 
I get 1 or 2 video ad (SSAI) and then I can play the video (pause it, play again etc)

**Comment by hKQwHW** [comment]
Oops, sorry for not responding. Yes, it's SSAI, probably because I signed in with my TV provider which has crappy service.
