### ISSUE TITLE
Youtube subscriptions

### ISSUE THREAD

**Issue by Eriklinuxuser** [uBlockOrigin/uAssets#13600]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.youtube.com/feed/subscriptions

### Describe the issue

When logged in to YT and viewing your subscriptions pages keeps loading old content videos under sections labeld: this month, last month, previous month, older....
How do i remove these sections older then a week?
So that the page is loaded faster.

And i ask this because im using the extension: better subscriptions for youtube with ublock, this allows to make invisible wachted videos, but on this page (subscriptions) it first searches all of them and the reason i want to remove the elements larger then 1 week is that it saves time to load.

### Screenshot(s)

![Schermafdruk van 2022-06-06 21-15-30](https://user-images.githubusercontent.com/106800138/172231252-380a86b1-9337-482d-9eef-61651a199683.png)

### uBlock Origin version

1.42.4

### Browser name and version

Brave

### Settings

none

**Comment by mapx-** [comment]
I doubt you save time => it's only hiding elements (you don't stop network requests). On the contrary, if such a filter would be possible more CPU will be involved to do the job.

If still you are not convinced ask on uBO's reddit: https://www.reddit.com/r/uBlockOrigin

**Comment by Eriklinuxuser** [comment]
I used to be able to do this and it worked faster but no i can't

**Comment by mapx-** [comment]
add

`youtube.com##.ytd-shelf-renderer:has-text( month)`

and see what happens when you go to the ... temporary "bottom"

**Comment by Eriklinuxuser** [comment]
Nothing happens.

This is one of the many it uses: `##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(9)`
But it keeps renaming the numbers and sometimes it just doesnt work.

**Comment by Eriklinuxuser** [comment]
Stuff like this used to do the job
`www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(2)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(3)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(4)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(5)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(6)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(7)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(8)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(9)
www.youtube.com##ytd-item-section-renderer.ytd-section-list-renderer.style-scope:nth-of-type(10)`

**Comment by Eriklinuxuser** [comment]
anyone?
