### ISSUE TITLE
adclickersbot.com: detection

### ISSUE THREAD

**Issue by ahmedok2022** [uBlockOrigin/uAssets#13607]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://adclickersbot.com/faucet-claim?id=6288b895e4838987eef63cb4`

### Category

detection

### Describe the issue

![ScreenShot_20220607122510](https://user-images.githubusercontent.com/106882633/172357931-a96f6901-42b8-4fff-bb23-d646c2016ef8.png)

### Screenshot(s)

![ScreenShot_20220607122510](https://user-images.githubusercontent.com/106882633/172357985-97b52e66-2e5d-41fb-972c-fbee19c94ef7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 119399
  cosmetic: 109905
  scriptlet: 32211
  html: 676
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64515-4724, 1d.35m
    adguard-spyware: 27027-11001, 1d.31m
    adguard-spyware-url: 613-14, 1d.31m
    adguard-annoyance: 53814-3096, 1d.30m
    adguard-social: 17563-1126, 1d.30m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32352-269, 1d.44m
    ublock-badware: 4175-3, 1d.44m
    ublock-privacy: 228-1, 1d.43m
    ublock-abuse: 75-0, 1d.43m
    ublock-unbreak: 1808-1, 1d.43m
    ublock-quick-fixes: 203-10, 24m
    easylist: 67949-25233, 1d.43m
    easyprivacy: 27156-131, 1d.43m
    urlhaus-1: 7336-0, 23m
    plowe-0: 3638-450, 1d.43m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1818 ms (selfie)
  maxAssetCacheWait: 1108 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    a-ads.com: 2
    ajfnee.com: 2
    cdn4ads.com: 1
    d3g5ovfngjw9bw.cloudfront.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    surfe.pro: 2
```
</details>

**Comment by ahmedok2022** [comment]
worked but stuck in loading button
![ScreenShot_20220607124648](https://user-images.githubusercontent.com/106882633/172361729-8ae834f4-1784-4972-bb3b-cbe638768ad2.png)

**Comment by mapx-** [comment]
@ahmedok2022 what should happen now ? clicking on loading ?

**Comment by okiehsch** [comment]
I think the site messed up it's detection script.
Adding
````
adclickersbot.com##+js(acis, document.getElementById, adblock)
adclickersbot.com#`@#+js(aopr, adblockDetected)
````
will make the captcha work again but after clicking loading the adblock detection reappears, which should not happen.

**Comment by okiehsch** [comment]
> what should happen now ? clicking on loading ?

With your filter the button is unresponsive using chromium on my end.

**Comment by JobcenterTycoon** [comment]
With disabled adblocker: First the button is "loading" after a popup it changes to "Claim Now!" and is clickable but after i clicked on it the site reloads and show a anti adblock again.

**Comment by ahmedok2022** [comment]
> 

claim now

**Comment by mapx-** [comment]
@ahmedok2022 
test

```
@@*$xhr,domain=adclickersbot.com
adclickersbot.com##+js(aeld, , _0x)
adclickersbot.com##+js(nowoif, /^/, 1)
adclickersbot.com##+js(aopw, _pop)
*$frame,domain=adclickersbot.com,redirect-rule=noopframe
*$image,domain=adclickersbot.com,redirect-rule=1x1.gif
||surfe.be^$important
```

**Comment by mapx-** [comment]
Did you clear cookies ? and don't keep open the developer tools / console

**Comment by mapx-** [comment]
Another thing: disabling uBO I got completed all steps (claimed ok), so I don't know if the link is still valid

**Comment by ahmedok2022** [comment]
> Another thing: disabling uBO I got completed all steps (claimed ok), so I don't know if the link is still valid (now arriving to the last step I get again the same claim button and not the ok completion)
the link is valid for cliaming once every 60 min

**Comment by ahmedok2022** [comment]
> @ahmedok2022 test
> 
> ```
> @@*$xhr,domain=adclickersbot.com
> adclickersbot.com##+js(aeld, , _0x)
> adclickersbot.com##+js(nowoif, /^/, 1)
> adclickersbot.com##+js(aopw, _pop)
> *$frame,domain=adclickersbot.com,redirect-rule=noopframe
> *$image,domain=adclickersbot.com,redirect-rule=1x1.gif
> ||surfe.be^$important
> ```

still stuck in loading button

**Comment by ahmedok2022** [comment]
![ScreenShot_20220607140656](https://user-images.githubusercontent.com/106882633/172375082-63ffb940-5e83-4f18-a73f-b9e5b7a98ac5.png)
it"s worked for me

**Comment by ahmedok2022** [comment]
thank you

**Comment by ahmedok2022** [comment]
workred only once then not working

**Comment by mapx-** [comment]
try adding too

`@@||static.surfe.pro/js/net.js$script,domain=adclickersbot.com`

**Comment by ahmedok2022** [comment]
yes, it worked thanks
