### ISSUE TITLE
en.mercedesclub.cz: detection

### ISSUE THREAD

**Issue by LastePurustaja** [uBlockOrigin/uAssets#13601]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://en.mercedesclub.cz/engines_family.php?id=60`

### Category

detection

### Describe the issue

even with uBlock origin turned off it still wont let me view the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82249
  cosmetic: 43784
  scriptlet: 17164
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67954-50, 1d.5h
    easyprivacy: 27151-122, 1d.4h.59m
    plowe-0: 3670-807, 4d.26m
    ublock-abuse: 75-0, 4d.4h.29m
    ublock-badware: 4171-91, 1d.4h.58m
    ublock-filters: 31694-89, 1d.4h.57m
    ublock-privacy: 222-2, 4d.4h.28m
    ublock-quick-fixes: 203-10, 4h.8m
    ublock-unbreak: 1825-40, 1d.4h.56m
    urlhaus-1: 7605-0, 50m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 277 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 2
    toplist.cz: 2
```
</details>

**Comment by mapx-** [comment]
The site is loaded fine and I get no anti adblocking modal / message.

> even with uBlock origin turned off it still wont let me view the site

This means you have other blocking extension / antivirus with ad-blocking capabilities / other utility

**Comment by LastePurustaja** [comment]
Nope i have others removed a long time ago

**Comment by mapx-** [comment]
> even with uBlock origin turned off it still wont let me view the site

You have to investigate on you side what is interfering with the normal navigation.

**Comment by LastePurustaja** [comment]
Ok, I'll check it out.
