### ISSUE TITLE
w2g.tv: ads

### ISSUE THREAD

**Issue by casualkitten1** [uBlockOrigin/uAssets#13616]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://w2g.tv/rooms/knv7j9lisu25y45txh6?lang=fr&access_key=6adw6gs5bf81hsyc2y4w3w`

### Category

ads

### Describe the issue

A banner can be seen under the video-player when making a room.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/49318780/172483578-dbd6bb36-4c51-44b5-9cf6-32fcbcd532e5.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 168311
  cosmetic: 183298
  scriptlet: 25655
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41566-218, 1d.5h.8m
    adguard-annoyance: 53768-487, 3d.6h.58m
    adguard-spyware: 27017-897, 3d.6h.57m
    adguard-spyware-url: 613-13, 3d.6h.56m
    block-lan: 43-0, 4h.56m
    curben-phishing: 14200-0, 4h.52m
    dpollock-0: 10373-148, 3d.5h.41m
    fanboy-annoyance: 72275-3097, 1d.22h.31m
    fanboy-cookiemonster: 32840-32835, 5d.6h.42m
    ublock-annoyances: 4433-192, 3d.6h.53m
  default: 
    user-filters: 0-0, never
    FRA-0: 27729-24, 3d.6h.59m
    easylist: 67950-706, 3d.6h.55m
    easyprivacy: 27150-10742, 3d.6h.54m
    plowe-0: 3638-1239, 3d.1h.54m
    ublock-abuse: 75-2, 3d.1h.53m
    ublock-badware: 4166-98, 3d.6h.52m
    ublock-filters: 31636-615, 3d.6h.51m
    ublock-privacy: 222-48, 3d.1h.52m
    ublock-quick-fixes: 203-13, 4h.54m
    ublock-unbreak: 1825-61, 3d.6h.50m
    urlhaus-1: 7236-1, 4h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 717 ms (selfie)
  maxAssetCacheWait: 366 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    w2g.tv: 1
    amazon-adsystem.com: 2
    consensu.org: 1
    doubleclick.net: 1
    imasdk.googleapis.com: 1
    pbstck.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`w2g.tv##.w2g-cas-ad`

@ryanbr
