### ISSUE TITLE
ru-facts.com: ads

### ISSUE THREAD

**Issue by lockieluke** [uBlockOrigin/uAssets#13613]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ru-facts.com/how-do-i-manually-add-framework-to-xcode/`

### Category

ads

### Describe the issue

it still has ads on it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 83811
  cosmetic: 73046
  scriptlet: 18537
  html: 677
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 9d.17h.58m
    fanboy-cookiemonster: 32372-63, 9d.17h.57m
  default: 
    user-filters: 33-3, never
    ublock-filters: 32350-33, 18h.30m
    ublock-badware: 4170-3, 3d.6h.4m
    ublock-privacy: 228-0, 10d.17h.16m
    ublock-abuse: 75-0, 9d.21h.59m
    ublock-unbreak: 1807-0, 18h.29m
    easylist: 67989-576, 18h.28m
    easyprivacy: 27160-581, 18h.27m
    urlhaus-1: 7605-0, 18h.26m
    plowe-0: 3638-3, 3d.6h.5m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 489 ms (selfie)
  maxAssetCacheWait: 344 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ru-facts.com: 2
    doubleclick.net: 2
    google.com: 1
    wp.com: 2
    youtube.com: 4
```
</details>

**Comment by mapx-** [comment]
add

ru-facts.com##.banlink

@ryanbr
