### ISSUE TITLE
ultraten.net: detection

### ISSUE THREAD

**Issue by craticar** [uBlockOrigin/uAssets#13617]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ultraten.net/detected.html`

### Category

detection

### Describe the issue

A shortlink that Detects UBO even when it's turned off from blocking ads on the site, the site itself doesn't seem to detect it but the shortlink does
https://user-images.githubusercontent.com/79741887/172512165-8bf73565-0c9f-4ab2-a408-dede9fb53669.png
, the only work around has been disabling the extension completely. The extension "Undetectable Adblocker" however remains undetected.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/79741887/172511269-76c06908-50a0-4f4a-ae96-bd04d59be66d.png

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 388268
  cosmetic: 168221
  scriptlet: 42942
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 5h.14m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25844-24, 5m
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt: 213267-0, 5m
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt: 97609-39, 5m
    adguard-annoyance: 53882-335, 5m
    adguard-social: 17601-852, 1m
    adguard-spyware: 26189-13426, 5h.15m
    dpollock-0: 10375-5876, 5m
    fanboy-annoyance: 72288-4215, 5m
    fanboy-cookiemonster: 33250-33250, 5h.15m
    ublock-annoyances: 4434-218, 5h.14m
  default: 
    user-filters: 9-1, never
    easylist: 68027-16868, 1m
    easyprivacy: 27167-16035, 5h.15m
    plowe-0: 3639-3211, 5m
    ublock-abuse: 75-2, 5h.15m
    ublock-badware: 4171-558, 5h.14m
    ublock-filters: 31727-3785, 3m
    ublock-privacy: 222-68, 5h.14m
    ublock-quick-fixes: 191-6, 5h.14m
    ublock-unbreak: 1798-61, 5h.15m
    urlhaus-1: 7285-619, 2m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 79 redacted]
switchRuleset: 
  added: [array of 49 redacted]
hostRuleset: 
  added: [array of 40 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 458 ms (selfie)
  maxAssetCacheWait: 966 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> A shortlink that Detects UBO

provide an example

**Comment by craticar** [comment]
https://uniqueten.net/worcestershire/QC9M It should be this, if it does not redirect

**Comment by mapx-** [comment]
uBO enabled / disable, I get always:

![image](https://user-images.githubusercontent.com/10303732/172540118-7a80edde-1324-47ba-b4b3-6fa4c5acda94.png)

**Comment by craticar** [comment]
![Uploading image_2022-06-08_014507806.png…]()
with ubo i get this
