### ISSUE TITLE
diakov.net: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13612]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://diakov.net/`

### Category

ads

### Describe the issue

There are advertising inserts on the site.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/172390849-b73a7c42-2ef4-4ec6-a7c8-97adfd97e6b1.png)
![image](https://user-images.githubusercontent.com/50231020/172390892-43894a9e-dc3b-4242-a590-6a13758509e7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 116434
  scriptlet: 29853
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64576-1515, 2m
    adguard-mobile: 7823-67, 2m
    adguard-spyware: 26189-754, 2m
  default: 
    FRA-0: 28283-3278, 2m
    easylist: 68011-25241, 2m
    plowe-0: 3639-571, 2m
    ublock-abuse: 75-1, 2m
    ublock-badware: 4171-308, 2m
    ublock-filters: 31718-3676, 2m
    ublock-privacy: 222-41, 2m
    ublock-quick-fixes: 204-22, 2m
    ublock-unbreak: 1795-82, 2m
    urlhaus-1: 7236-0, 2m
filterset (user): [array of 2069 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1464 ms
  maxAssetCacheWait: 567 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- russian site, use RU AdList
- however the "ads" are self-promotion

**Comment by mapx-** [comment]
no such empty items on my side

**Comment by mapx-** [comment]
maybe needing russian ip ?!

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is a russian site. The rules for it are contained in RU AdList. As far as I can see from the specified configuration, this filter is not active.

**Comment by mapx-** [comment]
official list
![image](https://user-images.githubusercontent.com/10303732/208306263-7d651da9-1445-4d16-acfd-f950c950d026.png)
