### ISSUE TITLE
techcrunch.com detection

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#13618]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://techcrunch.com/2020/07/17/cloudflare-dns-goes-down-taking-a-large-piece-of-the-internet-with-it/`

### Describe the issue

It silently checks for adblock and sets a cookie which could be used to track/detect adblock users.

```js
}(t, xi), Pi(t, [{
    key: "init",
    value: function(e) {}
}, {
    key: "track",
    value: function(e, t) {
        document.cookie = "__adblocker=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/";
        Qa("//www.npttech.com/advertising.js", "adblocker-check", function() {}, function() {
            return e = !0, (t = new Date).setTime(t.getTime() + 3e5), void(document.cookie = "__adblocker=" + (e ? "true" : "false") + "; expires=" + t.toUTCString() + "; path=/");
            var e, t
        }, !0, !0)
    }
}]), t
```

### Screenshot(s)

https://user-images.githubusercontent.com/17685483/172536363-e5866d3b-35d7-4f5f-8fe2-900ed902f3c9.png
https://user-images.githubusercontent.com/17685483/172536421-b5f53d05-6def-454e-a472-45ccfdf51abb.png

### uBlock Origin version

Latest

### Browser name and version

Chrome

### Settings

Stock lists

**Comment by MasterKia** [comment]
There is `||npttech.com/advertising.js$script,important,redirect-rule=fuckadblock.js-3.2.0` from uBlock filters.

**Comment by mapx-** [comment]
I get that cookie only whitelisting `npttech`

**Comment by MasterKia** [comment]
I think I only get that cookie when `npttech` is blocked.

**Comment by MasterKia** [comment]
I only get that cookie when `npttech` is blocked.
What about `techcrunch.com##+js(cookie-remover, __adblocker)`?

**Comment by mapx-** [comment]
- delete all cookies, refresh the page => no `__adblocker` cookie
- add `||npttech.com/advertising.js$script,important,redirect-rule=fuckadblock.js-3.2.0,badfilter`
- refresh the page => `__adblocker` cookie was created

**Comment by MasterKia** [comment]
https://user-images.githubusercontent.com/17685483/172542023-e52323a5-266b-4db7-b0bc-b2e092fbb67c.mp4

I waited until the page was fully loaded.

**Comment by mapx-** [comment]
use the classic view of cookies: developer tools (application - storage - cookies)

**Comment by MasterKia** [comment]
![image](https://user-images.githubusercontent.com/17685483/172547037-0eb673d6-4b3c-4e1e-b96b-b576a0296cf8.png)

Why does this happen?
* `__adblocker` from modern view of cookies isn't present in the classic view.

Is this a bug or accepted behavior?

**Comment by mapx-** [comment]
I guess it's a bug ?!

**Comment by oifj34f34f** [comment]
**20.05.2026**

<img width="851" height="281" alt="Image" src="https://github.com/user-attachments/assets/77523b4a-75ec-4656-bc50-d1610b23a9bd" />

`techcrunch.com##.DCDOr` fixes the issue.

<details>
<summary>Troubleshooting Information</summary>

```yaml
uBlock Origin: 1.71.0
Chromium: 148
filterset (summary):
 network: 223482
 cosmetic: 288462
 scriptlet: 75831
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1932-0, 14h.21m
  adguard-generic: 95914-7207, 21h.21m
  adguard-cookies: 38339-84, 2d.19h.21m
  ublock-cookies-adguard: 5658-81, 4d.21h.53m
  fanboy-cookiemonster: 57387-14737, 7d.22h.5m
  ublock-cookies-easylist: 5658-5658, 4d.21h.53m
  adguard-social: 26218-45, 2d.19h.22m
  fanboy-social: 17570-897, 7d.22h.5m
  fanboy-thirdparty_social: 69-0, 5d.21h.38m
  adguard-popup-overlays: 31019-1015, 2d.19h.21m
  adguard-mobile-app-banners: 7270-103, 2d.19h.21m
  adguard-other-annoyances: 16030-308, 2d.19h.22m
  [7 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 51612-84, 20m Δ
  ublock-badware: 11178-29, 20m Δ
  ublock-privacy: 4027-9, 20m Δ
  ublock-unbreak: 2759-5, 20m Δ
  ublock-quick-fixes: 465-0, 20m Δ
  easylist: 93918-160, 20m Δ
  easyprivacy: 55983-246, 20m Δ
  urlhaus-1: 28490-11, 11h.21m
  plowe-0: 3517-1031, 7d.11h.4m
  RUS-0: 41776-555, 11h.21m Δ
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 622 ms (selfie)
 maxAssetCacheWait: 202 ms
 cacheBackend: indexedDB
```

</details>
