### ISSUE TITLE
indiewire.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13614]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.indiewire.com/2020/04/better-call-saul-rhea-seehorn-kim-wexler-season-5-ending-1202226029/`

### Category

ads

### Describe the issue

Several advertising inserts are present. Even if the ad is blocked, the empty inserts are present. I think there should be a cosmetic rule.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/172422340-3136d153-0ab3-4069-b898-8580ca04d65f.png)
![image](https://user-images.githubusercontent.com/50231020/172422392-37593c53-445f-43ca-94f8-5b3560d4b60e.png)
![image](https://user-images.githubusercontent.com/50231020/172422457-6a286e55-44dc-4a4f-951e-70fb5d41a904.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 150737
  cosmetic: 82902
  scriptlet: 31046
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41582-1076, 1h.57m
    adguard-generic: 64576-1657, 2h.6m
    adguard-mobile: 7823-85, 2h.6m
    adguard-spyware: 26189-813, 2h.6m
  default: 
    FRA-0: 28283-3278, 2h.6m
    easylist: 68011-25250, 2h.6m
    easyprivacy: 27166-10431, 2h.6m
    plowe-0: 3639-953, 2h.6m
    ublock-abuse: 75-2, 2h.6m
    ublock-badware: 4171-308, 2h.6m
    ublock-filters: 31718-3699, 2h.6m
    ublock-privacy: 222-41, 2h.6m
    ublock-quick-fixes: 204-22, 2h.6m
    ublock-unbreak: 1795-90, 2h.6m
    urlhaus-1: 7236-0, 2h.6m
filterset (user): [array of 2075 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 726 ms (selfie)
  maxAssetCacheWait: 541 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
I guess it's difficult for you to test on default settings.

`ignoreGenericCosmeticFilters: true`
