### ISSUE TITLE
[nsfw] porn-4k.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13611]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://porn-4k.com/latest/`

### Category

ads

### Describe the issue

There are advertising inserts on the site. I think a good cleaning would be welcome 👍🏻

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/172380070-79faa181-d1d8-4eba-b00a-e8a2526e1522.png)
![image](https://user-images.githubusercontent.com/50231020/172380256-8d5bf71b-0800-4db0-a1eb-501c97a83d3e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 444224
  scriptlet: 29863
  html: 0
listset (total-discarded, last updated): 
    adguard-generic: 64572-1525, 58m
    adguard-mobile: 7823-70, 58m
    adguard-spyware: 26193-759, 58m
  default: 
    FRA-0: 28283-3314, 58m
    easylist: 68001-25256, 58m
    plowe-0: 3639-571, 58m
    ublock-abuse: 75-1, 58m
    ublock-badware: 4171-308, 58m
    ublock-filters: 31719-3789, 58m
    ublock-privacy: 222-41, 58m
    ublock-quick-fixes: 204-22, 58m
    ublock-unbreak: 1795-82, 58m
    urlhaus-1: 7336-0, 58m
filterset (user): [array of 2068 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1464 ms
  maxAssetCacheWait: 567 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`porn-4k.com##[href*="bemobtracks.com"]`

@ryanbr
