### ISSUE TITLE
santander.cl: breakage

### ISSUE THREAD

**Issue by fMaxBelemmi** [uBlockOrigin/uAssets#13615]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.santander.cl/transa/segmentos/Menu/view.asp`

### Category

breakage

### Describe the issue

Relevant element in bank's page (santander.cl) doesn't load (one of the main functions of the page is being blocked). Tested on Edge and Chrome.

Attached screenshots showing the console printing an `ERR_BLOCKED_BY_CLIENT` error for two GET requests when uBO is  enabled: 

```
https://cdn.appdynamics.com/adrum/adrum-20.12.0.3360.js 
https://bcdn-god.we-stats.com/scripts
``` 

(the attached screenshots are edited due to potentially sensitive information)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO
![Captura de pantalla 2022-06-07 133056](https://user-images.githubusercontent.com/26583296/172449320-1b46d417-9bbb-446a-a518-f92f1b4f178f.png)

Without uBO
![Captura de pantalla 2022-06-07 133130](https://user-images.githubusercontent.com/26583296/172449512-d2ef2121-eca5-44cd-a3a5-ffde3692a2e0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85034
  cosmetic: 48582
  scriptlet: 17369
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67949-50, 1d.17h.41m
    easyprivacy: 27151-122, 1d.17h.42m
    plowe-0: 3670-807, 6d.15h.40m
    spa-0: 3892-36, 14h.37m
    spa-1: 4513-169, 1d.17h.39m
    ublock-abuse: 75-0, 12d.5h.8m
    ublock-badware: 4166-91, 1d.17h.40m
    ublock-filters: 31652-144, 1d.17h.43m
    ublock-privacy: 222-2, 11d.16h.32m
    ublock-quick-fixes: 203-10, 14h.38m
    ublock-unbreak: 1795-42, 1d.17h.44m
    urlhaus-1: 7336-0, 14h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 212 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    santander.cl: 1
    appdynamics.com: 1
    evergage.com: 2
    googletagmanager.com: 4
    we-stats.com: 4
```
</details>

**Comment by mapx-** [comment]
> Relevant element in bank's page (santander.cl) doesn't load

meaning ?

Test this exception, see if it's enough to unblock that element

`@@||cdn.appdynamics.com/adrum/adrum-*.js`

**Comment by fMaxBelemmi** [comment]
> > Relevant element in bank's page (santander.cl) doesn't load
> 
> meaning ?
> 
> Test this exception, see if it's enough to unblock that element
> 
> `@@||cdn.appdynamics.com/adrum/adrum-*.js`

After adding the exception, the element loads properly and the site works as intended. Thanks @mapx-
