### ISSUE TITLE
RE: github.com #1338

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#1362]
https://github.com/uBlockOrigin/uAssets/issues/1338

uBlock-user said:

"Another useless issue moaning about uBO not working..."

uBlock-user,

Did it ever occur to you that if there's so many issues moaning about uBlock Origin not working, that that means that the program doesn't work, and that's why users are complaining about it? Instead of being rude to users who try and let you know that uBlock Origin doesn't work, why don't you try and fix it instead? Have a nice day. Thanks.

**Comment by uBlock-user** [comment]
> Did it ever occur to you that if there's so many issues moaning about uBlock Origin not working, that that means that the program doesn't work, 

Yes it did and no that doesn't mean that it's not working. I'm not that gullible and you're a troll and most of them are clueless when it comes to claiming that it doesn't work.

> and that's why users are complaining about it? 

Users 'moan' all the time, that doesn't mean they are rightfully moaning. 


> Instead of being rude to users who try and let you know that uBlock Origin doesn't work, 

I'm rude to trolls, not to users. Correction - I'm allergic to morons and trolls, not users, hence my rudeness to trolls/morons is a sign of a side effect having been a witness to numerous failed moans before you.

**Comment by okiehsch** [comment]
Just ignore him.
