### ISSUE TITLE
Ads on msn.com

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#13620]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

msn.com/nl-nl/

`https://www.msn.com/nl-nl/auto/nieuws/kroatische-huisartsen-in-verzet-tegen-nieuwe-verkeerswet/ar-AAYb4e6?li=BBoPOOe`

### Describe the issue

On the right side of an article is a grey block, because network requests for ads are blocked. 

I propose 
```
msn.com##[data-test-id$="ad"]
```

### Screenshot(s)

<details>

![image](https://user-images.githubusercontent.com/81161435/172548895-a6f2f994-12d1-4613-ad67-ba72839b46a3.png)

</details>

### uBlock Origin version

1.42.4

### Browser name and version

MS Edge v102

### Settings

- Disable `Peter Lowe` and `Online Malicious URL Blocklist`

**Comment by mapx-** [comment]
@ryanbr
