### ISSUE TITLE
Autoscroll is blocked on erome.com (adult)

### ISSUE THREAD

**Issue by eromecom** [uBlockOrigin/uAssets#13621]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

(NSFW) `https://www.erome.com/explore`

### Describe the issue

Hi,

We have implemented autoscroll on mobile only.

With a mobile browser that has uBlockOrigin as brave, our users complain about not being able to scroll and reach page 2 and following.

Url : (NSFW)
`https://www.erome.com/explore`

erome.com##+js(abort-current-script, $, ready)

Can you check, thank you

### uBlock Origin version

Brave 1.39.115

### Browser name and version

Brave 1.39.115

### Settings

nothing

**Comment by mapx-** [comment]
it should work now, tested on FF mobile.

**You should be very careful with those horrible popunders => it's the cause of breakage.**
