### ISSUE TITLE
[nsfw] javcl.com: breakage

### ISSUE THREAD

**Issue by cramit2000** [uBlockOrigin/uAssets#13627]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://javcl.com/`

### Category

breakage

### Describe the issue

Browser: Microsoft Edge Chromium
Issue: When visiting the site, the video streaming elements are no longer appearing on the site. Have verified that when utilizing an 'InPrivate' browsing window the site fully works but with ads and pop-ups displayed everywhere. I have 2 extensions that potentially block elements (uBlock & Malwarebytes). I have confirmed that simply disabling both of these extensions in the browser and then revisiting the site does not resolve the issue.

I have also verified that the standalone Malwarebytes Premium Anti-Malware software is not blocking any of the elements on the page since it was fully viewable using the 'InPrivate' browser window and the only items which were getting blocked by this software were the content of the ad pop-ups that occurred during the 'InPrivate' browser test.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![uBlock On - JAVCL](https://user-images.githubusercontent.com/39716923/172658986-807c80d3-cb2e-49be-a0f0-e41bf5c26a26.png)
![InPrivate Browsing - JAVCL](https://user-images.githubusercontent.com/39716923/172659011-7639295f-00fc-4ee4-a492-d3fb774241b8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81886
  cosmetic: 43765
  scriptlet: 17145
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67948-50, 2d.6h.23m
    easyprivacy: 27153-122, 2d.6h.22m
    plowe-0: 3638-781, 2d.6h.24m
    ublock-abuse: 75-0, 18h.59m
    ublock-badware: 4171-91, 2d.6h.21m
    ublock-filters: 31652-89, 2d.6h.20m
    ublock-privacy: 222-2, 18h.58m
    ublock-quick-fixes: 203-10, 23h
    ublock-unbreak: 1795-40, 2d.6h.19m
    urlhaus-1: 7285-0, 6h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 323 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    meo257na3rch.com: 1
    realsrv.com: 1
```
</details>

**Comment by mapx-** [comment]
No issues on my end.
Did you disable edge adblocker ?
