### ISSUE TITLE
ukr.net: breakage

### ISSUE THREAD

**Issue by Maks2909** [uBlockOrigin/uAssets#13634]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ukr.net/`

### Category

breakage

### Describe the issue

Links on the page do not open when uBlock Origin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 101637
  cosmetic: 46688
  scriptlet: 18393
  html: 684
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32467-295, 11h.19m
    ublock-badware: 4175-3, 11h.18m
    ublock-privacy: 228-1, 11h.17m
    ublock-abuse: 75-0, 11h.14m
    ublock-unbreak: 1816-0, 11h.12m
    ublock-quick-fixes: 193-0, 11h.11m
    adguard-mobile: 7824-172, 11h.24m
    easylist: 68069-24808, 11h.10m
    easyprivacy: 27173-586, 11h.9m
    urlhaus-1: 7229-0, 11h.8m
    plowe-0: 3639-3, 11h.7m
    RUS-0: 41612-1025, 11h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 523 ms (selfie)
  maxAssetCacheWait: 213 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ukr.net: 3
    cloudflareinsights.com: 2
    doubleclick.net: 1
    fwdcdn.com: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`ukr.net#@#+js(aopr, window.googletag)`

@dimisa-RUAdList

**Comment by mapx-** [comment]
sure, it's ok

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/0d1c1b20dd1aebf8a01e35214a7843be39756ecc

**Comment by Maks2909** [comment]
Thanks a lot guys.  Everything works, I checked.
