### ISSUE TITLE
hepsiburada.com: breakage

### ISSUE THREAD

**Issue by mehmetcelikkol** [uBlockOrigin/uAssets#13630]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hepsiburada.com/`

### Category

breakage

### Describe the issue

fzdfdsf

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 83659
  cosmetic: 50302
  scriptlet: 17552
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32348-45, 1d.7h.17m
    ublock-badware: 4175-3, 1d.7h.14m
    ublock-privacy: 228-0, 2d.8h.23m
    ublock-abuse: 75-0, 2d.8h.22m
    ublock-unbreak: 1807-0, 1d.7h.13m
    easylist: 68012-606, 1d.7h.18m
    easyprivacy: 27166-584, 1d.7h.15m
    urlhaus-1: 7229-0, 28m
    plowe-0: 3670-3, 6d.2h.13m
    TUR-0: 8810-117, 1d.7h.16m
    ublock-quick-fixes: 191-0, 29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 421 ms (selfie)
  maxAssetCacheWait: 248 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    cedexis.net: 10
    doubleclick.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> fzdfdsf

interesting

**Comment by hkaancaliskan** [comment]
@mapx- I didn't wanted to open a new issue but i have also problem with hepsiburada. As you can see in the screenshot top right elements are not loading, i can't login because of this.

![resim](https://user-images.githubusercontent.com/17825767/183726844-1c6425f3-ce52-4ff9-88a5-e3d20729222d.png)

If i turn off the ublock problem goes.

![resim](https://user-images.githubusercontent.com/17825767/183726917-b0b26988-6eb2-4a1b-b465-252e662672dd.png)

```
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 113056
  cosmetic: 181877
  scriptlet: 37667
  html: 726
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    urlhaus-1: null
    plowe-0: null
    TUR-0: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1936-0, now
    adguard-generic: 66717-5120, now
    adguard-mobile: 8075-11, now
    adguard-spyware: 26771-874, now
    adguard-spyware-url: 702-93, now
    block-lan: 43-0, now
    adguard-annoyance: 55752-4415, now
    adguard-social: 18118-28, now
    fanboy-thirdparty_social: 69-0, now
    fanboy-cookiemonster: 39092-130, now
    ublock-annoyances: 4526-4, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33103-69, now
    ublock-privacy: 247-2, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1867-1, now
    easylist: 69309-411, now
    easyprivacy: 27306-9439, now
    ublock-quick-fixes: 355-1, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  largeMediaSize: 100
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 684 ms (selfie)
  maxAssetCacheWait: 700 ms

```

**Comment by ghajini** [comment]
do you mean this
![Screenshot 2022-08-10 at 00-51-22 Türkiye'nin En Büyük Online Alışveriş Sitesi Hepsiburada com](https://user-images.githubusercontent.com/20338483/183744240-5d9416bd-1cf3-48b6-8224-517f677c8118.png)

then it loads ,you require regional list `adguard turkish` which you have disabled & need default settings or ensure that your custom lists not interfere

**Comment by hkaancaliskan** [comment]
@ghajini yep that one and the one at right of it. At you it didn't loaded the other one.
For me, disabling EasyPrivacy and AdGuard Tracking Protection lists fixes the issue.
Enabling adguard and other defaults not helped.

**Comment by hkaancaliskan** [comment]
AdGuard Tracking Protection blocks cedexis.net at line 2016 and that breaks the page.

`@@||*.cedexis.net^$domain=hepsiburada.com` filter rule fixes the problem

**Comment by hkaancaliskan** [comment]
Also adding `www.hepsiburada.com##.Advertisement.voltran-body.sf-voltran-body` filter removes the white leftover space from top

**Comment by MasterKia** [comment]
>  For me, disabling AdGuard Tracking Protection list fixes the issue.

I can't visit the website because I get "Access Denied"; so does the breakage happen _**using only the default uBO lists**_?

If it **only** happens with AdGuard Tracking Protection then you should report here:
https://github.com/AdguardTeam/AdguardFilters/

**Comment by hkaancaliskan** [comment]
Only happens with AdGuard Tracking Protection list

**Comment by MasterKia** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
This is cname-blocked so only with uBO and perhaps AGDNS.
