### ISSUE TITLE
7review.com: detection

### ISSUE THREAD

**Issue by spatula75** [uBlockOrigin/uAssets#13633]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://7review.com/teac-tn-5bb-review/`

### Category

detection

### Describe the issue

Detects the use of uBlock Origin and displays an overlay ("Blocking because of ad blocker") preventing interaction with the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/7718879/172741446-791cdfec-da00-4756-af09-f4e6829f243c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81860
  cosmetic: 43778
  scriptlet: 17169
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67954-50, 3d.8h.15m
    easyprivacy: 27151-122, 3d.8h.14m
    plowe-0: 3638-781, 3d.8h.19m
    ublock-abuse: 75-0, 3d.8h.18m
    ublock-badware: 4166-91, 3d.8h.13m
    ublock-filters: 31694-89, 3d.8h.12m
    ublock-privacy: 222-2, 3d.8h.17m
    ublock-quick-fixes: 192-2, 8h.4m
    ublock-unbreak: 1825-40, 3d.8h.11m
    urlhaus-1: 7229-0, 8h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 159 ms (selfie)
  maxAssetCacheWait: 108 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    7review.com: 1
    doubleclick.net: 1
    flexlinkspro.com: 1
    google-analytics.com: 1
    google.com: 3
    googlesyndication.com: 2
    media.net: 1
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
if you are using a chromium browser like Brave => click Brave shields icon and disable it for this site.
For other chromium browsers disable the builtin adblocker.

**Comment by mapx-** [comment]
however, you can add:

`7review.com##+js(aopr, b2a)`
