### ISSUE TITLE
t3n.de: nuisance

### ISSUE THREAD

**Issue by Bondarz** [uBlockOrigin/uAssets#13631]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://t3n.de/consent?redirecturl=%2F`

### Category

nuisance

### Describe the issue

Can't deactivate the cookiebanner

### Screenshot(s)

https://user-images.githubusercontent.com/19914015/172735281-58154be9-fb44-4e59-9809-7046d32b7dea.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 87178
  cosmetic: 43919
  scriptlet: 18612
  html: 680
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 33276-15188, 1h.26m
  default: 
    user-filters: 4-0, never
    ublock-filters: 32474-314, 1h.23m
    ublock-badware: 4175-3, 1h.22m
    ublock-privacy: 228-1, 43m
    ublock-abuse: 75-0, 42m
    ublock-unbreak: 1816-0, 40m
    ublock-quick-fixes: 192-0, 39m
    adguard-mobile: 7829-172, 1h.28m
    easylist: 68098-24800, 38m
    easyprivacy: 27173-596, 37m
    urlhaus-1: 7229-0, 36m
    plowe-0: 3639-3, 35m
    DEU-0: 5807-385, 1h.28m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1374 ms
  maxAssetCacheWait: 468 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
This is a redirection. Nothing that can be prevented by ublock.
I use the extension "I don't care about cookies". It's more powerful than the filter list version.

**Comment by Bondarz** [comment]
> This is a redirection. Nothing that can be prevented by ublock. I use the extension "I don't care about cookies". It's more powerful than the filter list version.

Thank you, I had seen it once. But I don't want everything to be accepted ;)

Will everything be accepted with the list if I add it to uBlock? or will the lists simply be "hidden"?

https://www.i-dont-care-about-cookies.eu/abp/

**Comment by Nailuj1** [comment]
With the latest update in the "I don't care about cookies" it solved the problem.
