### ISSUE TITLE
pikabu.ru: breakage

### ISSUE THREAD

**Issue by RiseOfDeath** [uBlockOrigin/uAssets#13636]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pikabu.ru/story/normalnaya_takaya_palatka_9177544`

### Category

breakage

### Describe the issue

Video not work with enabled  filters.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 160194
  cosmetic: 167481
  scriptlet: 37712
  html: 691
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64612-5548, now
    adguard-spyware: 26189-900, now
    adguard-spyware-url: 623-14, now
    block-lan: 43-0, now
    curben-phishing: 14512-1, now
    curben-pup: 250-0, now
    adguard-annoyance: 53961-4914, now
    adguard-social: 17632-1651, now
    fanboy-thirdparty_social: 68-1, now
    fanboy-annoyance: 72446-60969, now
    fanboy-cookiemonster: 33404-15239, now
    fanboy-social: 23272-13657, now
    ublock-annoyances: 4462-7, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32480-314, now
    ublock-badware: 4175-3, now
    ublock-privacy: 228-1, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1816-1, now
    ublock-quick-fixes: 203-0, now
    adguard-mobile: 7831-172, now
    easylist: 68103-24830, now
    easyprivacy: 27176-10394, now
    urlhaus-1: 7238-0, now
    plowe-0: 3639-3, now
    RUS-0: 41628-1118, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 405 ms (selfie)
  maxAssetCacheWait: 3859 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    pikabu.ru: 4
    adfox.ru: 1
    facebook.net: 1
    googletagmanager.com: 1
    mail.ru: 2
    tns-counter.ru: 1
    vk.com: 1
    yandex.ru: 6
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by RiseOfDeath** [comment]
Additional info - plugin was used in Firefox for Android.
