### ISSUE TITLE
rheinpfalz.de: nuisance

### ISSUE THREAD

**Issue by Bondarz** [uBlockOrigin/uAssets#13632]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rheinpfalz.de/`

### Category

nuisance

### Describe the issue

Can't deactivate the cookiebanner 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/19914015/172735990-a1697081-7ecc-445f-ad27-6f948a631cc8.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 87181
  cosmetic: 43918
  scriptlet: 18612
  html: 680
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 33276-15188, 1h.47m
  default: 
    user-filters: 6-0, never
    ublock-filters: 32474-314, 1h.43m
    ublock-badware: 4175-3, 1h.42m
    ublock-privacy: 228-1, 1h.4m
    ublock-abuse: 75-0, 1h.3m
    ublock-unbreak: 1816-0, 1h.1m
    ublock-quick-fixes: 192-0, 1h
    adguard-mobile: 7829-178, 1h.48m
    easylist: 68098-24800, 59m
    easyprivacy: 27173-596, 58m
    urlhaus-1: 7229-0, 57m
    plowe-0: 3639-3, 56m
    DEU-0: 5807-379, 1h.48m
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1374 ms
  maxAssetCacheWait: 489 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    rheinpfalz.de: 4
    googletagmanager.com: 1
    iocnt.net: 2
    kameleoon.eu: 1
```
</details>

**Comment by Procyon-b** [comment]
You can enable the list "AdGuard Annoyances" in the "Filter lists" tab. Or you can add the list "I don't care about cookies" from here: https://www.i-dont-care-about-cookies.eu/

**Comment by Bondarz** [comment]
> You can enable the list "AdGuard Annoyances" in the "Filter lists" tab. Or you can add the list "I don't care about cookies" from here: https://www.i-dont-care-about-cookies.eu/

Thanks, at least it worked on my smartphone. :)
