### ISSUE TITLE
bcvc.xyz: popups

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13639]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bcvc.xyz/Pt3smiM`

### Category

popups

### Describe the issue

 A pop-up window appears when clicking Get link!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82691
  cosmetic: 20433
  scriptlet: 17233
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32385-277, 21m
    ublock-badware: 4175-3, 21m
    ublock-privacy: 228-1, 21m
    ublock-abuse: 75-0, 21m
    ublock-unbreak: 1811-10, 21m
    ublock-quick-fixes: 202-2, 21m
    easylist: 68103-24298, 21m
    easyprivacy: 27177-596, 21m
    urlhaus-1: 7238-0, 21m
    plowe-0: 3639-345, 21m
    VIE-1: 1741-44, 22m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 293 ms (selfie)
  maxAssetCacheWait: 127 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by zeref-dragneel** [comment]
Google Drive

> Which should be the correct destination ?

**Comment by mapx-** [comment]
Test:

```
bcvc.*##+js(cookie-remover, /^/))
bcvc.*##+js(aost, Cookies, , 2)
||bc.vc/js/app.v5.js$script
||bcvc.*/dist/js/po_v9.js

||skiptheadz.com^$all
||adblockerapp.com^$all
||track.bcvc.mobi^$all
||doaipomer.com^$all
```

**Comment by okiehsch** [comment]
`bcvc.*##+js(aopr, open)`

does not work for you?

**Comment by mapx-** [comment]
The real issue is repeating the steps: first you get the real file then a lot of other random ones.

**Comment by okiehsch** [comment]
If I only add  `bcvc.*##+js(aopr, open)`, and click "Get Link", I end up at

![image](https://user-images.githubusercontent.com/16838044/172852530-78421498-79d6-47ba-9d5e-1a71c2cff54f.png)

every time without any popups.

**Comment by okiehsch** [comment]
>  when I go back (from destination) and repeat the steps

Hm, yes I can reproduce. Don't know how to fix that. It's a weird way to induce popups, almost no one will go back from the destination page and then go back again.

**Comment by mapx-** [comment]
adding too:

```
||skiptheadz.com^$all
||adblockerapp.com^$all
||track.bcvc.mobi^$all
||doaipomer.com^$all
```

at least will stop loading that crap

**Comment by okiehsch** [comment]
Sure let's add those as well.
