### ISSUE TITLE
Managed Dynatrace Returns 500 Errors

### ISSUE THREAD

**Issue by 4lch4** [uBlockOrigin/uAssets#13642]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dynatrace.jbhunt.com`

### Describe the issue

Attempting to log in to the managed (self-hosted) Dynatrace instance causes the website to return a 500 error. The error only occurs when uBlock is enabled and running. When I get the 500 error, I can disable uBlock, refresh the page, and log in just fine.

I've tested this with a browser profile where uBlock was the _only_ extension installed. However, I managed to reproduce the issue, so I'm confident it's a uBlock Origin Filter issue and not the website or my browser.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6931731/172442906-dbf46949-33e4-49e0-acfc-cff3edc40494.png)

### uBlock Origin version

1.42.4

### Browser name and version

Brave Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64)

### Settings

I've not made any changes to my default settings.

**Comment by mapx-** [comment]
trying to redirect to some microsoft account:

`https://login.microsoftonline.com/....`

**Comment by mapx-** [comment]
Any company should be able to provide a test account.

Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there 
(you can select only the blocked items in the logger's search box)

**Comment by jsteave** [comment]
we've one application sending HTTP 500 Internal Server Error when we are dealing with a controlled error.

 

This is a common bad practice but this application is consumed by several clients and is not so easy for us to change the behaviour.

 

Dynatrace raises problems for these HTTP 500 Internal Server Error  (as usual) but they are not "real" errors.

 

So, there's any option in Dynatrace to obviate these HTTP 500 Internal Server Error in the problems and not raise problems in this kind of HTTP 500 Internal Server Error (maybe based on some exceptions or messages)?

**Comment by 4lch4** [comment]
> Any company should be able to provide a test account.

Unfortunately, it's out of my hands.

> Use only the default settings, open the logger, reproduce the issue, go back into the logger and post here a screenshot containing only the blocked items you see there (you can select only the blocked items in the logger's search box)

I'll do this today and post the data! Thanks.

**Comment by mapx-** [comment]
A fix has been added in easyprivacy list, update it and test again. If still does not work post the data above

**Comment by 4lch4** [comment]
Looks like I wasn't using the default settings as I thought... I switched to the default and it's working now. Thank you all for the help.

**Comment by thermiteTermite** [comment]
Proper exclusion rules are explained here. 
https://github.com/easylist/easylist/issues/12240

These filters are too general.
