### ISSUE TITLE
airmail.news: ads

### ISSUE THREAD

**Issue by augustuscrown** [uBlockOrigin/uAssets#13645]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://airmail.news/issues/2022-3-26/yale-for-sale`

### Category

ads

### Describe the issue

the website signs me out periodically and won't refresh while logged in.

there are also ads still on the page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-06-09 at 1 11 32 PM](https://user-images.githubusercontent.com/69601514/172905340-516014ac-a4c7-4067-aed4-88d100a71092.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 86173
  cosmetic: 90174
  scriptlet: 19682
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53820-174, 3d.6h.33m
  default: 
    user-filters: 39-1, never
    easylist: 67950-90, 3d.6h.32m
    easyprivacy: 27156-220, 3d.6h.31m
    plowe-0: 3670-808, 9d.8h.32m
    ublock-abuse: 75-0, 2d.1h.41m
    ublock-badware: 4171-91, 3d.6h.30m
    ublock-filters: 31718-430, 3d.6h.29m
    ublock-privacy: 222-2, 2d.1h.40m
    ublock-quick-fixes: 202-5, 14h.51m
    ublock-unbreak: 1795-44, 3d.6h.28m
    urlhaus-1: 7238-0, 14h.52m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 52 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1588 ms (selfie)
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`airmail.news##.display`

> the website signs me out periodically and won't refresh while logged in

Do you mean it's a breakage due to some filters ? Did you test disabling uBO ?

**Comment by mapx-** [comment]
@ryanbr
