### ISSUE TITLE
Gravitec script block

### ISSUE THREAD

**Issue by BagiTornado** [uBlockOrigin/uAssets#13641]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

on the domain `https://www.nagargram.com/`
blocks external script  `https://cdn.gravitec.net/storage/886b1f08c6bc743890e4ee312fe8b030/client.js` 

### Describe the issue

There is a blocking of the connected external script from Gravitec (browser push notification delivery service)

### uBlock Origin version

uBlock Origin 1.42.4

### Browser name and version

Firefox 101.0 (64-bit)

### Settings

Didn't make any changes to the default settings

### Notes

A similar problem is present on other resources where Gravitec is integrated

**Comment by mapx-** [comment]
> There is a blocking of the connected external script from Gravitec (browser push notification delivery service)

Explain what functionality is broken and how we can see effects, if an account is necessary etc
