### ISSUE TITLE
getbukkit.org: ads

### ISSUE THREAD

**Issue by Ndot10** [uBlockOrigin/uAssets#13648]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://getbukkit.org/download/spigot`

### Category

ads

### Describe the issue

there is a video banner ad in the middle of the page leading to ramshard hosting: `https://ramshard.com/aff.php?aff=405`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![homepage](https://user-images.githubusercontent.com/69880636/172929489-8ce40c50-c74a-472b-8fea-0474bc3388ac.png)
![download latest page](https://user-images.githubusercontent.com/69880636/172929584-c3be6a40-76d5-4975-98cc-6b44eb2964bb.png)
![download list page](https://user-images.githubusercontent.com/69880636/172928267-b858f422-9ae4-438c-af6c-de30841a518f.png)
![the gif being shown](https://getbukkit.org/assets/img/Ramshardv2.gif)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83522
  cosmetic: 73934
  scriptlet: 18605
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 21h.27m
    fanboy-cookiemonster: 33252-81, 1d.21h.53m
  default: 
    user-filters: 2-0, never
    easylist: 68026-50, 1d.21h.55m
    easyprivacy: 27168-122, 1d.21h.54m
    plowe-0: 3639-781, 1d.21h.54m
    ublock-abuse: 75-0, 1d.21h.54m
    ublock-badware: 4171-91, 1d.21h.54m
    ublock-filters: 31727-108, 1d.21h.54m
    ublock-privacy: 222-2, 1d.21h.54m
    ublock-quick-fixes: 191-2, 21h.26m
    ublock-unbreak: 1798-41, 1d.21h.54m
    urlhaus-1: 7229-0, 21h.25m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 268 ms (selfie)
  maxAssetCacheWait: 186 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`getbukkit.org##[href*="/aff.php"]`

@ryanbr
