### ISSUE TITLE
tweakers.net: breakage

### ISSUE THREAD

**Issue by Bucketsmith** [uBlockOrigin/uAssets#13640]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tweakers.net/nieuws/197696/deliver-us-mars-van-nederlandse-ontwikkelaar-verschijnt-op-27-september.html`

### Category

breakage

### Describe the issue

Embedded Youtube videos keep reverting to a screen saying I need to adjust cookie settings.
Even if I disable UO, set up the cookies, set up NoScript, then put UO back on, it still reverts to this screen.
I suspect something is being blocked that makes it so embedded videos just cannot play with UO on, in one of their filters?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/20886583/172827059-be340d51-9032-4e51-9440-0b3bf78dee88.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 131206
  cosmetic: 154539
  scriptlet: 24456
  html: 685
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-4, 7m
    adguard-spyware: 26190-866, 7m
    adguard-spyware-url: 623-14, 7m
    block-lan: 43-0, 5m
    adguard-annoyance: 53972-3713, 7m
    fanboy-annoyance: 72481-305, 7m
    ublock-annoyances: 4444-8, 7m
    NLD-0: 2284-11, 7m
    curben-phishing: 14512-1, 6m
    curben-pup: 250-0, 6m
  default: 
    user-filters: 8-0, never
    ublock-filters: 32374-85, 7m
    ublock-badware: 4175-3, 7m
    ublock-privacy: 228-0, 7m
    ublock-abuse: 75-0, 7m
    ublock-unbreak: 1811-18, 7m
    easylist: 68103-609, 7m
    easyprivacy: 27177-10386, 7m
    urlhaus-1: 7238-0, 7m
    plowe-0: 3639-4, 7m
    ublock-quick-fixes: 202-0, 7m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 664 ms (selfie)
  maxAssetCacheWait: 626 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    tweakers.net: 2
    tweakers.nl: 2
    usabilla.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
@@||tweakers.net/x/build/cookieBar$script,1p
@@||tweakers.net/x/styles/components/cookiebar/cookie_bar.css$css,1p
@@||tweakers.net/ajax/cookie-consent/*$xhr,1p
```

maintainers of adguard annoyances / fanboy annoyances notified

**Comment by Bucketsmith** [comment]
Thanks!
