### ISSUE TITLE
dudestream.com: detection

### ISSUE THREAD

**Issue by saurjk** [uBlockOrigin/uAssets#13656]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://dudestream.com/`

### Category

detection

### Describe the issue

Adblock is detected, powered by CHP Ads Block Detector PRO 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82058
  cosmetic: 43862
  scriptlet: 17217
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 68144-50, 4m
    easyprivacy: 27181-122, 4m
    plowe-0: 3641-780, 4m
    ublock-abuse: 75-0, 4m
    ublock-badware: 4171-91, 4m
    ublock-filters: 31817-99, 4m
    ublock-privacy: 222-2, 3m
    ublock-quick-fixes: 202-2, 3m
    ublock-unbreak: 1798-40, 3m
    urlhaus-1: 7232-0, 3m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8471 ms (selfie)
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
no anti adb on my side, tested here for example:

`http://dudestream.com/2022/05/14/tennis-channel-live/`

**Comment by saurjk** [comment]
Huh, yea seems to be fine now, no idea why it got messed up before, will close the issue.
