### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by msbhosale** [uBlockOrigin/uAssets#13654]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/`

### Category

ads

### Describe the issue

##div:nth-of-type(19) > .sjgh65i0.l9j0dhe7.k4urcfbm.du4w35lb > .l9j0dhe7.du4w35lb > div > div > .lzcic4wl > .cbu4d94t.j83agx80 > .du4w35lb.l9j0dhe7.rq0escxv > .k4urcfbm.l9j0dhe7.j83agx80 > .sbcfpzgs.stjgntxs.ni8dbmo4.k4urcfbm.nwvqtn77.fbipl8qg.m5lcvass.io0zqebd.hybvsw6c.du4w35lb.l9j0dhe7.rq0escxv > div > div:nth-of-type(2) > div

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

##div:nth-of-type(19) > .sjgh65i0.l9j0dhe7.k4urcfbm.du4w35lb > .l9j0dhe7.du4w35lb > div > div > .lzcic4wl > .cbu4d94t.j83agx80 > .du4w35lb.l9j0dhe7.rq0escxv > .k4urcfbm.l9j0dhe7.j83agx80 > .sbcfpzgs.stjgntxs.ni8dbmo4.k4urcfbm.nwvqtn77.fbipl8qg.m5lcvass.io0zqebd.hybvsw6c.du4w35lb.l9j0dhe7.rq0escxv > div > div:nth-of-type(2) > div
![Screenshot 2022-06-10 at 11-02-52 Facebook](https://user-images.githubusercontent.com/29226304/172997138-7571cc07-42a0-4f28-9c18-aa5a5b32f82a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 81977
  cosmetic: 43805
  scriptlet: 17160
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32359-40, 1d.18h.26m
    ublock-badware: 4175-3, 1d.18h.25m
    ublock-privacy: 228-0, 23h.23m
    ublock-abuse: 75-0, 23h.22m
    ublock-unbreak: 1810-0, 1d.18h.24m
    ublock-quick-fixes: 202-2, 14h.7m
    easylist: 68053-563, 1d.18h.23m
    easyprivacy: 27173-579, 1d.18h.22m
    urlhaus-1: 7259-0, 14h.6m
    plowe-0: 3638-3, 5d.1h.13m
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4086 ms (selfie)
  maxAssetCacheWait: 1919 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
https://www.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_facebook

duplicate: https://github.com/uBlockOrigin/uAssets/issues/3367
