### ISSUE TITLE
ads.tiktok.com: breakage

### ISSUE THREAD

**Issue by Blokje93** [uBlockOrigin/uAssets#13655]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ads.tiktok.com/i18n/login?redirect=https%3A%2F%2Fads.tiktok.com%2Fi18n%2Fhome%3Fis_new_connect%3D0%26is_new_user%3D0`

### Category

breakage

### Describe the issue

When uBlock is activated the website gives a network error message. After disabling uBlock it is possible to login.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82667
  cosmetic: 45286
  scriptlet: 17220
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2222-11, 1d.9m
    easylist: 68103-53, 1d.11m
    easyprivacy: 27176-122, 1d.10m
    plowe-0: 3669-807, 11d.26m
    ublock-abuse: 75-0, 11d.29m
    ublock-badware: 4171-91, 1d.14m
    ublock-filters: 31750-145, 1d.13m
    ublock-privacy: 222-2, 11d.28m
    ublock-quick-fixes: 202-2, 6m
    ublock-unbreak: 1799-54, 1d.12m
    urlhaus-1: 7232-0, 5m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 218 ms (selfie)
  maxAssetCacheWait: 174 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    tiktok.com: 11
    byteoversea.com: 30
    tiktokv.com: 1
```
</details>

**Comment by mapx-** [comment]
I'm able to login tiktok, no error on my side.
How did you get that (ads.) address  ? Describe exactly the steps.

**Comment by Blokje93** [comment]
> I'm able to login `tiktok`, no error on my side. How did you get that (ads.) address ? Describe exactly the steps.

I just went to Google and searched for tiktok ad manager and the first hit is https://ads.tiktok.com/i18n/ . 
After this I just tried to login, but I keep getting a network error and the page keeps reloading.
First I used the incognito mode form Chrome but that was a workaround with a lot of extra steps. After this I tried FireFox and it worked fine, installed uBlock on FireFox and it stopped working. I went back to Chrome and disabled uBlock and it worked, activated and it didn't.

**Comment by mapx-** [comment]
Does this work for you ?

`||ads.tiktok.com^$badfilter`

**Comment by Blokje93** [comment]
Do I need to copy this into uBlock?

**Comment by mapx-** [comment]
right click uBO icon, "my filters" tab, add that filter, click "apply now"

**Comment by Blokje93** [comment]
Yes, that worked! What is the reason this is working?

**Comment by mapx-** [comment]
a restrictive filter in one of the default lists, I "killed" it (`badfilter` keyword)

**Comment by Blokje93** [comment]
Okay, good to know. Thank you very much for your help!
