### ISSUE TITLE
khanoumi.com breakage and tracking

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uAssets#13658]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://khanoumi.com`

### Describe the issue

* `://ads.` from _uBlock Unbreak_ blocks most images: `ads.khanoumi.com/storage/637888263791489130.jpg`.
\> `@@||ads.khanoumi.com/storage/*$image,1p`

* Every picture in the homepage is rigged with click tracking, look for **_trackClick_** function in `static.khanoumi.com/scripts/api/main-ads.js` and `static.khanoumi.com/scripts/api/A-home-ads.4.1.7.js`.
On every click, it sends user ip to `ads.khanoumi.com/api/services/app/AdsTrackingPanel/Post` which is also blocked by `://ads.` (no problems with that) and then redirects the user to destination page.
`khanoumi.com##+js(no-xhr-if, ads.khanoumi.com)` defuses calls to that URL but doesn't return **true** for the redirect to happen.

### Screenshot(s)

Broken:
https://user-images.githubusercontent.com/17685483/173070484-c982dca3-612e-4757-9be3-5c3e2ee00ff9.png

### uBlock Origin version

Latest

### Browser name and version

Chrome

### Settings

-

### Notes

I'll add the final filters to PersianBlocker.

**Comment by mapx-** [comment]
You have to whitelist that xhr.
However is sending not the reaL ip but something like `192.168.80.*` a router external address

**Comment by MasterKia** [comment]
> is not sending the reaL ip but something like `192.168.80.*`

I assume that's an oversight and it would be changed by the site when noticed.

**Comment by krystian3w** [comment]
Maybe failed copied from dev environment to production (at 5 pm on Friday before Computer scientists have weekend).

**Comment by mapx-** [comment]
just add those fixes in your list. For the tracking stuff I guess we should wait for trust lists.

**Comment by MasterKia** [comment]
Alright.

@mapx- 
Why doesn't `khanoumi.com##+js(set, input, {})` or `khanoumi.com##+js(set, input, [])` work?
I can still see the xhr payload.

```js
function trackClick(adid, zonecode, redirectTo) {
    ip = $("#UserIP").val();
    var input =
    {
        "zoneCode": zonecode ,
        "adsId": adid,
        "ip": ip,
        "userId": adsuid,
        "pageUrl": url,
        "type": 2//view
    };
    
    $.ajax({
         url: 'https://ads.khanoumi.com/api/services/app/AdsTrackingPanel/Post',
         type: 'POST',
         contentType: 'application/json; charset=UTF-8',
         dataType: "json",
         data: JSON.stringify(input),
         success: function (data) {
             window.location = redirectTo;
             if (data.success) {
            }
         },
         error: function (request, error) {
         },
         complete: function (data) {
         }
     });
}
```

**Comment by mapx-** [comment]
I have no idea, tried the same

**Comment by MasterKia** [comment]
> we should wait for trust lists.

Is it planned/confirmed to be added in the future?

https://github.com/uBlockOrigin/uAssets/issues/11167#issuecomment-1003719497

**Comment by krystian3w** [comment]
We checked use `aopr`/`aopw`/`aeld`?

**Comment by MasterKia** [comment]
```
khanoumi.com##+js(aopr, input)
khanoumi.com##+js(aopw, input)
khanoumi.com##+js(aeld, input)
```
When all used, it seems that the "userId" becomes zero.
![image](https://user-images.githubusercontent.com/17685483/173184877-d26483ae-8c7e-4362-9f8d-c08cbbcf0aaa.png)

I don't know which of those filters is causing this.

**Comment by MasterKia** [comment]
I think `remove-class.js`/`remove-attr.js` could help.

**Comment by mapx-** [comment]
yeah, it seems you are right:

killing xhr exception and using rc seems working

```
@@||ads.khanoumi.com/api/services/app/adstrackingpanel/post$xmlhttprequest,1p,badfilter
khanoumi.com##+js(rc, ads-track, , stay)
```

**Comment by MasterKia** [comment]
Thank you @mapx-

**Comment by MasterKia** [comment]
Let's explicitly block `ads.khanoumi.com/api/services/app/adstrackingpanel`.

**Comment by krystian3w** [comment]
Maybe better is use `asap stay` if for `rc` that was implemented.

In ra possible check use 2 scriptlets if one not exclude first.
