### ISSUE TITLE
tetris.com: ads

### ISSUE THREAD

**Issue by brookeknowles** [uBlockOrigin/uAssets#13653]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tetris.com/play-tetris/?utm_source=top_nav_link&utm_medium=webnav&utm_campaign=playNow_btm_tst&utm_content=text_play_now`

### Category

ads

### Describe the issue

ads used to be blocked, but are no longer being blocked left, right and above the game

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/62309663/172978614-fc1e23b1-8294-4c3d-bf54-2e03e03cc4ee.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81972
  cosmetic: 43804
  scriptlet: 17196
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-50, 1d.17h.42m
    easyprivacy: 27172-122, 1d.17h.43m
    plowe-0: 3670-807, 6d.19h.11m
    ublock-abuse: 75-0, 1d.21h.47m
    ublock-badware: 4171-91, 1d.17h.40m
    ublock-filters: 31729-101, 1d.17h.41m
    ublock-privacy: 222-2, 1d.21h.48m
    ublock-quick-fixes: 202-2, 2h.3m
    ublock-unbreak: 1798-40, 1d.17h.44m
    urlhaus-1: 7259-0, 2h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 550 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    tetris.com: 1
    addthis.com: 1
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    insops.net: 1
```
</details>

**Comment by mapx-** [comment]
All 3 seem to be self-promotion.

However, add in "my filters" this filter:

`tetris.com##[onclick]`
