### ISSUE TITLE
soundcloud.com: detection / nuisance

### ISSUE THREAD

**Issue by caber345** [uBlockOrigin/uAssets#13659]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soundcloud.com/discover`

### Category

detection

### Describe the issue

This website don't let you to sign in if you have any kind of adblocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82070
  cosmetic: 43823
  scriptlet: 17174
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32383-42, 3h.29m
    ublock-badware: 4175-3, 3h.28m
    ublock-privacy: 228-0, 3h.24m
    ublock-abuse: 75-0, 3h.23m
    ublock-unbreak: 1811-0, 3h.27m
    ublock-quick-fixes: 202-0, 1d.37m
    easylist: 68147-563, 3h.26m
    easyprivacy: 27181-579, 3h.25m
    urlhaus-1: 7259-0, 1d.36m
    plowe-0: 3638-3, 4d.4h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2953 ms (selfie)
  maxAssetCacheWait: 2645 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
reset uBO to default settings, update all lists, don't use any other blocking addon.
If ETP enabled in FF try using the standard (not the strict) configuration.

**Comment by Residentcl** [comment]
Hello.

When trying to change the player timeline for long audio, this message appears asking you to log in.

Is it possible to add the filter to the list?

![sound](https://github.com/user-attachments/assets/2b3b1526-3b31-4081-8411-1c683a049c82)

`https://soundcloud.com/tbogas/swedish-house-mafia-live-at-electric-daisy-carnival-2010-sat-06-25-2010-la`

**Comment by mapx-** [comment]
This "issue" is more similar to a paywall

**Comment by Residentcl** [comment]
The payment method is for creators who pay to upload unlimited audios to the platform.
There is no payment required to listen:
`https://checkout.soundcloud.com/artist?ref=t132`

**Comment by stephenhawk8054** [comment]
I can't see any ways to address this.

**Comment by stephenhawk8054** [comment]
For Firefox, you can use this filter:

```adb
||sndcdn.com/assets/*.js^$script,replace=/shouldBlockScrubbing\(\w\.getMediaDuration\(\)\)/shouldBlockScrubbing(false)/
```

but it can't be used for other browsers. Also, you'll need to refresh the page while bypassing the cache (`Ctrl + Shift + R`).

**Comment by Residentcl** [comment]
I tested it with Firefox and the solution works while waiting for a solution for other browsers.

**Comment by stephenhawk8054** [comment]
I don't think there's any ways for other browsers.
