### ISSUE TITLE
hdfilmcehennemi2.top: ads

### ISSUE THREAD

**Issue by MuhammetEminCakir** [uBlockOrigin/uAssets#13657]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hdfilmcehennemi2.top/`

### Category

ads

### Describe the issue

There are two ads in this website.

This is my filters for this ads:
[ublock-statik-filtrelerim_2022-06-10_14.30.41.txt](https://github.com/uBlockOrigin/uAssets/files/8878429/ublock-statik-filtrelerim_2022-06-10_14.30.41.txt)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Ekran görüntüsü 2022-06-10 143154" src="https://user-images.githubusercontent.com/64583157/173056310-a897cdd2-2594-4ad2-b773-ec1943ce2b19.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 88056
  cosmetic: 96824
  scriptlet: 20056
  html: 677
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53968-664, 1d.3h.50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32357-53, 1d.3h.58m
    ublock-badware: 4175-3, 1d.3h.57m
    ublock-privacy: 228-0, 1d.3h.56m
    ublock-abuse: 75-0, 1d.3h.55m
    ublock-unbreak: 1811-0, 1d.3h.54m
    ublock-quick-fixes: 202-0, 23h.22m
    easylist: 68103-582, 1d.3h.53m
    easyprivacy: 27176-583, 1d.3h.52m
    urlhaus-1: 7238-0, 23h.21m
    plowe-0: 3638-3, 5d.16h.21m
    TUR-0: 8810-117, 1d.3h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 363 ms (selfie)
  maxAssetCacheWait: 441 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    hdfilmcehennemi2.top: 10
    aj2373.online: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
`hdfilmcehennemi2.top##[href^="https://rebrand.ly"]`
or
`hdfilmcehennemi2.top##a.text-dark.bg-white.money-text`

for turkish list
@Yuki2718
