### ISSUE TITLE
eenadu.net: ads

### ISSUE THREAD

**Issue by mrdmanohar1** [uBlockOrigin/uAssets#13669]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.eenadu.net/videos/playVideo/old-man-urges-minister-roja-for-pension/1/26092`

### Category

ads

### Describe the issue

Ads shows up in the webpage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/94883276/173198136-e9720a3c-9d94-49b9-a622-3826322dcfb2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82289
  cosmetic: 43824
  scriptlet: 17210
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 68149-50, 1d.2h.9m
    easyprivacy: 27181-122, 1d.2h.8m
    plowe-0: 3670-807, 10d.12h.55m
    ublock-abuse: 75-0, 2d.13h.46m
    ublock-badware: 4191-91, 1d.2h.7m
    ublock-filters: 31753-101, 1d.2h.6m
    ublock-privacy: 222-2, 2d.13h.45m
    ublock-quick-fixes: 202-2, 9h.44m
    ublock-unbreak: 1798-40, 1d.2h.5m
    urlhaus-1: 7457-0, 9h.43m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 26 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13411 ms (selfie)
  maxAssetCacheWait: 2012 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    adpushup.com: 1
    adrecover.com: 1
    aniview.com: 1
    doubleclick.net: 1
    escalated.io: 1
    facebook.com: 1
    google.com: 5
    googletagmanager.com: 1
    googletagservices.com: 1
    imrworldwide.com: 1
    izooto.com: 1
    vdo.ai: 1
    vidcrunch.com: 2
    vuukle.com: 4
```
</details>

**Comment by ghajini** [comment]
At above url i can't see any ad 

i only see a banner ad over here `https://www.eenadu.net/telugu-news/sports/ind-vs-sa-clip-of-ugly-brawl-at-arun-jaitley-stadium-during-1st-t20i-makes-rounds-on-internet/0400/122114379`

![Screenshot (358)](https://user-images.githubusercontent.com/20338483/173203171-4911e5f8-ac2a-44a1-86f9-62d74dd10d8f.png)

so 
`||aj2031.online^`

@ryanbr please check out

**Comment by mapx-** [comment]
add
`eenadu.net###aniBox`

Report at thai repository: https://github.com/easylist-thailand/easylist-thailand/issues

**Comment by ghajini** [comment]
does that require thai ip?
a indian site

**Comment by mapx-** [comment]
oh, first a piece of text => google told me it's thai .. now telugu which it's indian, well ..
