### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by EDEPOLAR** [uBlockOrigin/uAssets#13664]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=p37xu9HaLpY&list=RDGMEM6ijAnFTG9nX1G-kbWBUCJA&start_radio=1`

### Category

ads

### Describe the issue

everytime that I open youtube (or chrome with a youtube video in a tab), the video ALWAYS has an ad but only the first video, the rest is fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 81902
  cosmetic: 43770
  scriptlet: 17191
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67998-50, 3d.17h.46m
    easyprivacy: 27164-122, 3d.17h.45m
    plowe-0: 3639-781, 3d.17h.44m
    ublock-abuse: 75-0, 3d.17h.42m
    ublock-badware: 4171-91, 3d.17h.40m
    ublock-filters: 31720-93, 3d.17h.39m
    ublock-privacy: 222-2, 3d.17h.38m
    ublock-quick-fixes: 192-2, 2d.12h.1m
    ublock-unbreak: 1795-40, 3d.17h.36m
    urlhaus-1: 7229-0, 2d.12h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 546 ms (selfie)
  maxAssetCacheWait: 284 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    youtube.com: 29
    doubleclick.net: 2
    google.com: 1
    google.com.cy: 1
    googlesyndication.com: 1
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate https://github.com/uBlockOrigin/uAssets/issues/7636

See: https://github.com/easylist/easylist/wiki/Youtube-Issues
