### ISSUE TITLE
faucetpay.nurul-huda.or.id: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13666]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://faucetpay.nurul-huda.or.id/?url=https://drive.google.com/u/0/uc?id=0B9gv-bZITzJvZU0zMzZtQlZjVDQ&export=download`

### Category

ads

### Describe the issue

Ads are displayed on the page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/173189669-1a2200b0-5699-43cf-b130-e3b3729be38f.png)
![image](https://user-images.githubusercontent.com/50231020/173189680-56480594-74e7-4b01-9129-23f7f3e94188.png)
![image](https://user-images.githubusercontent.com/50231020/173189689-49c6ce88-ef74-4679-a230-6ca0001f7705.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 478655
  cosmetic: 113394
  scriptlet: 31062
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41630-257, 1d.17h.7m
    adguard-generic: 64577-1302, 3d.21h.8m
    adguard-mobile: 7823-71, 3d.21h.8m
    adguard-spyware: 26188-802, 3d.21h.8m
  default: 
    user-filters: 2150-2, never
    FRA-0: 28283-64, 3d.21h.8m
    easylist: 68012-1255, 3d.21h.8m
    easyprivacy: 27166-10432, 3d.21h.8m
    plowe-0: 3639-953, 3d.21h.8m
    ublock-abuse: 75-2, 3d.21h.8m
    ublock-badware: 4171-308, 3d.21h.8m
    ublock-filters: 31723-3592, 3d.21h.8m
    ublock-privacy: 222-40, 3d.21h.8m
    ublock-quick-fixes: 210-12, 5h.13m
    ublock-unbreak: 1795-90, 3d.21h.8m
    urlhaus-1: 7457-0, 5h.11m
filterset (user): [array of 2079 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 874 ms (selfie)
  maxAssetCacheWait: 513 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

```
faucetpay.nurul-huda.or.id###satoshi1
faucetpay.nurul-huda.or.id###satoshi2
||dl.dropboxusercontent.com$image
```

@ryanbr

**Comment by mapx-** [comment]
classic filters => it should be fixed by easylist @ryanbr

**Comment by mapx-** [comment]
```
faucetpay.nurul-huda.or.id##[id^="satoshi"]
faucetpay.nurul-huda.or.id##[href^="https://goo.gl/"]
faucetpay.nurul-huda.or.id##[src^="https://i.ibb.co/"]
```

**Comment by mapx-** [comment]
if @ryanbr is seeing this thread will add the filters but sure .. you should add them as custom filters
