### ISSUE TITLE
myurbanjungle.com: breakage

### ISSUE THREAD

**Issue by dfunct** [uBlockOrigin/uAssets#13662]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myurbanjungle.com/`

### Category

breakage

### Describe the issue

The website just loads into an empty (white) page. Disabling uBlock will make the website show contents.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 89547
  cosmetic: 108539
  scriptlet: 21476
  html: 684
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 6d.5h.13m
    fanboy-annoyance: 72270-56536, 6d.5h.11m
    fanboy-cookiemonster: 33138-101, 6d.5h.12m
    fanboy-social: 23267-28, 2d.2h.43m
    ublock-annoyances: 4442-4, 2d.2h.44m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32374-52, 2d.2h.49m
    ublock-badware: 4175-3, 2d.2h.48m
    ublock-privacy: 228-0, 2d.2h.52m
    ublock-abuse: 75-0, 2d.2h.51m
    ublock-unbreak: 1811-0, 2d.2h.47m
    easylist: 68098-579, 2d.2h.46m
    easyprivacy: 27173-580, 2d.2h.45m
    urlhaus-1: 7336-0, 9h.12m
    plowe-0: 3639-3, 2d.2h.53m
    ublock-quick-fixes: 202-0, 9h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6572 ms (selfie)
  maxAssetCacheWait: 3720 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    googletagmanager.com: 1
    sc-static.net: 1
    sentry.io: 4
    stripe.com: 9
    trustpilot.com: 1
    zdassets.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||static.zdassets.com/ekr/snippet.js$script,domain=myurbanjungle.com`

FA issue @ryanbr
