### ISSUE TITLE
xoxo.egybest.ltd: detection

### ISSUE THREAD

**Issue by minaabdo** [uBlockOrigin/uAssets#13660]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xoxo.egybest.ltd/movie/pirates-of-the-caribbean-at-worlds-end-2007/?ref=trends-p2&r=112`

### Category

detection

### Describe the issue

It detects ublock origin and prevents me from accessing the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82208
  cosmetic: 43867
  scriptlet: 17220
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68167-50, now
    easyprivacy: 27181-122, now
    plowe-0: 3642-780, now
    ublock-abuse: 75-0, now
    ublock-badware: 4191-91, now
    ublock-filters: 31820-96, now
    ublock-privacy: 222-2, now
    ublock-quick-fixes: 210-2, now
    ublock-unbreak: 1798-40, now
    urlhaus-1: 7336-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 320 ms (selfie)
  maxAssetCacheWait: 240 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
The video in page is ok, the other ones (links) no.

Duplicate: https://github.com/uBlockOrigin/uAssets/issues/10255
