### ISSUE TITLE
[nsfw] taiv8.cc: ads

### ISSUE THREAD

**Issue by EricNgo** [uBlockOrigin/uAssets#13667]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://taiv8.cc/?a=v8_propellerads_ken&utm_source=propellerads_ken&utm_medium=popunder.pc.gold&utm_campaign=adnetwork`

### Category

ads 

### Describe the issue

malware ads always poped up on Window screen when logging in 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (22)](https://user-images.githubusercontent.com/17892352/173190220-239f3e8c-5544-43d9-9d3e-c394766f5c5c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82039
  cosmetic: 43814
  scriptlet: 17187
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68048-50, 3d.8h.25m
    easyprivacy: 27172-122, 3d.8h.24m
    plowe-0: 3638-781, 7d.10h.34m
    ublock-abuse: 75-0, 7d.10h.32m
    ublock-badware: 4171-91, 3d.8h.23m
    ublock-filters: 31712-94, 3d.8h.22m
    ublock-privacy: 222-2, 7d.10h.28m
    ublock-quick-fixes: 210-2, 11h.58m
    ublock-unbreak: 1798-40, 3d.8h.21m
    urlhaus-1: 7336-0, 11h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 2
    prprocess.com: 1
```
</details>

**Comment by mapx-** [comment]
logging in windows ?

scan for malware / antivirus your system using:
https://www.f-secure.com/en/home/free-tools/online-scanner
