### ISSUE TITLE
gettyimages-downloader.beatsnoop.com: detection

### ISSUE THREAD

**Issue by lightmoon16** [uBlockOrigin/uAssets#13663]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gettyimages-downloader.beatsnoop.com/`

### Category

detection

### Describe the issue

Doesn't allow you to enter the site of uBlock Origin is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/107288973/173168744-86964aec-eafe-4552-bffc-e3cbdbcaf9bf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82592
  cosmetic: 45130
  scriptlet: 20130
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4436-7, never
  default: 
    user-filters: 1-0, never
    easylist: 68168-50, 5m
    easyprivacy: 27185-122, 5m
    plowe-0: 3642-780, 5m
    ublock-abuse: 75-0, 5m
    ublock-badware: 4191-91, 5m
    ublock-filters: 31823-96, 5m
    ublock-privacy: 222-2, 5m
    ublock-quick-fixes: 209-2, 5m
    ublock-unbreak: 1798-40, 5m
    urlhaus-1: 7457-0, 5m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 165 ms (selfie)
  maxAssetCacheWait: 205 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 3
```
</details>

**Comment by Colliwomple** [comment]
[Fetchpick.com](https://fetchpik.com/gettyvideos-downloader.php#) i can only download the example successfully with all other links it doesnt work for me. i post some links that dosent work for example:
https://www.gettyimages.com/detail/video/news-footage/862-24
https://www.gettyimages.com/detail/video/news-footage/103762465 (this video show in preview window but when try to download i get this) :{"response":{"status":{"errors":[{"code":"ERROR","message":"Error performing getty download: status: 403, body: '{\"ErrorCode\":\"NoDownloadAuthorization\",\"ErrorMessage\":\"No download authorization were found for asset 103762465. Perhaps the user has no active product types.\"}'"}],"code":400}}}
Maybe this could help. Wish it was working

**Comment by stephenhawk8054** [comment]
@Colliwomple The same happens to me even when I disable all extensions.
