### ISSUE TITLE
bold.dk: ads

### ISSUE THREAD

**Issue by Mickey182** [uBlockOrigin/uAssets#13661]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bold.dk/video/`

### Category

ads

### Describe the issue

Yesterday, I was able to watch videos on bold.dk without ads when running uBlock. Today, the ads are now playing on every video - Even when uBlock is running.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (38)](https://user-images.githubusercontent.com/58091794/173167473-43d6ab70-5614-46fd-94ac-c42547d43512.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82888
  cosmetic: 45687
  scriptlet: 17225
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NOR-0: 2776-7, 8h.40m
    easylist: 68049-51, 2d.18h.25m
    easyprivacy: 27172-123, 2d.18h.24m
    plowe-0: 3638-782, 6d.46m
    ublock-abuse: 75-0, 1d.21h.19m
    ublock-badware: 4171-92, 2d.18h.23m
    ublock-filters: 31727-103, 2d.18h.22m
    ublock-privacy: 222-2, 1d.21h.18m
    ublock-quick-fixes: 202-2, 8h.39m
    ublock-unbreak: 1795-40, 2d.18h.21m
    urlhaus-1: 7336-0, 8h.38m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2413 ms (selfie)
  maxAssetCacheWait: 338 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    adnami.io: 1
    adrecover.com: 1
    cadreon.com: 1
    doubleclick.net: 1
    fwmrm.net: 5
    gemius.pl: 1
    googletagmanager.com: 2
    keppet.com: 1
    onthe.io: 1
    pbstck.com: 1
    permutive.com: 1
    pushpushgo.com: 1
    sentry.io: 1
    stickyadstv.com: 4
    userreport.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`||freewheel-mtgx-tv.akamaized.net^$media,domain=embed.viaplay.com,redirect=noopmp3-0.1s`

@DandelionSprout

**Comment by DandelionSprout** [comment]
I have problems reproducing OP's ads (though coincidentally I did whitelist `@@.v.fwmrm.net/ad/g^*:mtg_play_` yesterday because it worked for such embeds on `ekstrabladet.dk`), but I'll add your entry regardless. Give me 10min.
