### ISSUE TITLE
forum.pfsense.org

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1366]
![2018-01-25-whitelist for ublock_](https://user-images.githubusercontent.com/5884000/35361931-928fec8e-0163-11e8-8d7f-a03a694c446a.png)
`https://forum.pfsense.org/index.php?topic=125869.0`

ad

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.25
Chrome 64.0.3282.119

**Comment by SMed79** [comment]
add
```
-4860-ad.
```
or
```
-banner-*-ad.
```
