### ISSUE TITLE
logitech.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#13676]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.logitech.com/en-us/products/keyboards/k375s-multidevice-stand-combo.html`

### Category

breakage

### Describe the issue

website broken 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 104
filterset (summary): 
  network: 82566
  cosmetic: 115325
  scriptlet: 22327
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7134-9, 3m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-2, 3m
    fanboy-annoyance: 72992-219, 3m
    ublock-annoyances: 4437-54, 3m
  default: 
    user-filters: 13-0, never
    easylist: 68191-64, 3m
    easyprivacy: 27193-122, 3m
    ublock-abuse: 75-0, 3m
    ublock-badware: 4191-89, 3m
    ublock-filters: 31818-209, 3m
    ublock-privacy: 222-9, 3m
    ublock-quick-fixes: 210-2, 3m
    ublock-unbreak: 1798-43, 3m
filterset (user): [array of 13 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1158 ms (selfie)
  maxAssetCacheWait: 601 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    logitech.com: 1
    tiqcdn.com: 1
```
</details>

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/173227217-b908e850-b083-46b0-b153-f408bdc3f610.png)

**Comment by mapx-** [comment]
add

```
@@||logitech.com/etc.clientlibs/logitech-common/clientlibs/onetrust.min$script,1p
logitech.com#@##onetrust-banner-sdk
```

FA issue @ryanbr
