### ISSUE TITLE
w2g.tv: ads

### ISSUE THREAD

**Issue by casualkitten1** [uBlockOrigin/uAssets#13672]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://w2g.tv/rooms/16xtacni0unwyacy72i?lang=fr&access_key=01zjjk684c5207085k4edk`

### Category

ads

### Describe the issue

A banner can be seen under the video-player when making a room, one is for NordVPN and another one is for the website.

To see the ads, go on https://w2g.tv/ and create a room. You should see an ad under the video-player.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/49318780/173205566-cc6d4741-d2c5-4a66-872b-7610b346c5c4.png)
![image](https://user-images.githubusercontent.com/49318780/173205581-09195b6b-cf7e-40f4-aa8a-74d606cf5acf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 170789
  cosmetic: 184289
  scriptlet: 25747
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41659-218, now
    adguard-annoyance: 54060-447, now
    adguard-spyware: 26211-876, now
    adguard-spyware-url: 629-13, now
    block-lan: 43-0, now
    curben-phishing: 18126-0, now
    dpollock-0: 10375-153, now
    fanboy-annoyance: 72835-3111, now
    fanboy-cookiemonster: 33793-33793, now
    ublock-annoyances: 4437-193, now
  default: 
    user-filters: 0-0, never
    FRA-0: 28869-24, now
    easylist: 68190-724, now
    easyprivacy: 27192-10469, now
    plowe-0: 3644-1243, now
    ublock-abuse: 75-2, now
    ublock-badware: 4191-100, now
    ublock-filters: 31815-638, now
    ublock-privacy: 222-48, now
    ublock-quick-fixes: 210-5, now
    ublock-unbreak: 1798-61, now
    urlhaus-1: 4831-1, now
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1179 ms (selfie)
  maxAssetCacheWait: 523 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    w2g.tv: 1
    amazon-adsystem.com: 2
    consensu.org: 1
    doubleclick.net: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`w2g.tv##.w2g-dub-ad`

@ryanbr
