### ISSUE TITLE
plovdiv24.bg: ads

### ISSUE THREAD

**Issue by alfotmelmak** [uBlockOrigin/uAssets#13675]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.plovdiv24.bg/novini/Bylgaria/Horata-s-luksozni-avtomobili-nyama-da-poluchat-otstupka-za-gorivata-1281690?fbclid=IwAR0F8qFHBC7K1R-ugze0GPlZTVf54uTS45fTLjwSxQn07Ff9L1l2abBELZo`

### Category

ads

### Describe the issue

THere are adds on both sides - left and right.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 79564
  cosmetic: 43816
  scriptlet: 17160
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32359-42, 3d.19h.18m
    ublock-badware: 4175-3, 3d.19h.17m
    ublock-privacy: 228-0, 3d.19h.16m
    ublock-abuse: 75-0, 3d.19h.10m
    ublock-unbreak: 1810-0, 3d.19h.9m
    ublock-quick-fixes: 210-0, 17h.53m
    easylist: 68069-564, 3d.19h.7m
    easyprivacy: 27173-579, 3d.18h.50m
    urlhaus-1: 4831-0, 17h.52m
    plowe-0: 3639-3, 3d.18h.48m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 400 ms (selfie)
  maxAssetCacheWait: 221 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    facebook.com: 2
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    onesignal.com: 2
    wtg-ads.com: 1
```
</details>

**Comment by mapx-** [comment]
1. it's a bulgarian site => enable `BGR: Bulgarian Adblock list` => this will fix partially the issue (removing the images)
2. however needing also (to remove the clickable placeholders):

```
plovdiv24.bg###leftbrand
plovdiv24.bg###rightbrand
```

to be added to BG list => You should send an email to the maintainer Alexander Stanev `alex@stanev.org`
https://stanev.org/abp/?Contacts

**Comment by mapx-** [comment]
I guess it's him: @RealEnder

**Comment by RealEnder** [comment]
10x, the Bulgarian list is updated accordingly
