### ISSUE TITLE
diep.io: breakage

### ISSUE THREAD

**Issue by JMask480** [uBlockOrigin/uAssets#13679]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://diep.io/`

### Category

breakage

### Describe the issue

every time the extension is on it requests a page refresh on in-game death

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/107352173/173232445-f3bed3ae-5aa8-44a5-b3af-5b7c5ebab6f3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 79705
  cosmetic: 43858
  scriptlet: 17209
  html: 0
listset (total-discarded, last updated): 
  removed: 
    TUR-0: null
  default: 
    user-filters: 21-3, never
    easylist: 68190-50, 12h.7m
    easyprivacy: 27192-122, 12h.6m
    plowe-0: 3670-807, 12d.12h.1m
    ublock-abuse: 75-0, 8d.5h.52m
    ublock-badware: 4191-91, 12h.5m
    ublock-filters: 31754-102, 3d.1h.45m
    ublock-privacy: 222-2, 8d.5h.53m
    ublock-quick-fixes: 210-2, 16h.8m
    ublock-unbreak: 1799-40, 3d.1h.46m
    urlhaus-1: 4831-0, 16h.9m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  largeMediaSize: 100
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8214 ms (selfie)
  maxAssetCacheWait: 1132 ms
popupPanel: 
  blocked: 4
  no-large-media: true
  no-popups: true
  no-scripting: true
  blockedDetails: 
    diep.io: 1
    googletagmanager.com: 2
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings / filter lists, don't touch them anymore, test again.

![image](https://user-images.githubusercontent.com/10303732/173233045-aa878b3f-65dc-449a-a933-727fa58999aa.png)

**Comment by JMask480** [comment]
![image](https://user-images.githubusercontent.com/107352173/173233980-fc572326-8cb0-49d3-bca5-466a32db4e65.png)
same problem

**Comment by JMask480** [comment]
Thank you

**Comment by JMask480** [comment]
doesnt work 
![image](https://user-images.githubusercontent.com/107352173/173242084-b50fa1f5-32f5-45d1-a8c1-8fc14d54db96.png)

**Comment by mapx-** [comment]
I already told you what to do

> Reset uBO to default settings / filter lists, don't touch them anymore

**Comment by JMask480** [comment]
it worked for a very short time but faced the same problem again

**Comment by okiehsch** [comment]
> it worked for a very short time but faced the same problem again

Looking at your screenshot you changed the default settings again.

**Comment by JMask480** [comment]
I try every possible way with resetting settings
and it's not just my problem it's been brought up on reddit

**Comment by MasterKia** [comment]
> it's been brought up on reddit

Link?

**Comment by MasterKia** [comment]
Should add another **Prerequisites**:

> * [ ] I did not change any of the defaults settings, or I verified that the issue still occurs with the default settings.

**Comment by JMask480** [comment]
https://www.reddit.com/r/Diepio/search/?q=crashed&restrict_sr=1&sr_nsfw=

**Comment by JMask480** [comment]
and everyone points out that it's due to the extension

**Comment by MasterKia** [comment]
> https://www.reddit.com/r/Diepio/search/?q=crashed&restrict_sr=1&sr_nsfw=

[Literally the first result](https://www.reddit.com/r/Diepio/comments/v91a15/comment/ibw0l2t/?context=3):
"To all having this issue – I'm out of the office today, but we'll be deploying a fix for this tomorrow. Thanks for your patience!"

**Comment by JMask480** [comment]
![image](https://user-images.githubusercontent.com/107352173/173242908-82f65a75-a711-47cb-bfe3-350a9d931bc0.png)

**Comment by mapx-** [comment]
> I try every possible way with resetting settings

There is only 1 possible way: just **reset uBO to default and don't touch the settings anymore**.

![image](https://user-images.githubusercontent.com/10303732/173243013-0d78e9d0-2a0a-43e4-b776-54f4d8bb005b.png)

**Comment by MasterKia** [comment]
It seems I can reproduce.

**Comment by MasterKia** [comment]
```js
}, window.onerror = function(e, t, n, i, o) {
        if (window.onerror = null, o && (o = o.toString()), "undefined" != typeof Uint8Array && "undefined" != typeof WebSocket && "undefined" != typeof CanvasRenderingContext2D && document.createElement("canvas").getContext("2d") && (null == t || -1 != t.indexOf("//diep.io")) && !(null != t && -1 == t.indexOf(".js") || (null != t && setTimeout((function() {
                alert("The game crashed, refreshing page to recover from error"), window.onbeforeunload = null, window.location.reload(!0)
            }), 1e3), null == o && 0 == n && 0 == i || null != o && -1 != o.indexOf("renoTransGloRef")))) {
            var r = JSON.stringify({
                message: e,
                source: t,
                lineno: n,
                colno: i,
                error: o
            });
            console.log("Uncaught error: " + r)
```

**Comment by okiehsch** [comment]
Me too, but it's hard to debug, I need an easier way to get killed. 😉

**Comment by MasterKia** [comment]
I just colide with the tanks :p  
https://user-images.githubusercontent.com/17685483/173243192-49951cec-1b45-4ab6-8c25-142964673e87.png

**Comment by okiehsch** [comment]
`@@||api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/release/*$xhr,domain=diep.io`

seems to work.

**Comment by MasterKia** [comment]
Yeah it works.
What about defusing the `setTimeout`?
That script doesn't look innocent to me.

**Comment by okiehsch** [comment]
It isn't it pulls a whole bunch of ad scripts but they are all blocked, so I don't see an issue.

**Comment by JMask480** [comment]
What should I do to fix

**Comment by MasterKia** [comment]
Yeah it tries to pull more scripts from `enthusiastgaming.net` but it should be blocked from EP.

**Comment by okiehsch** [comment]
Try adding
`@@||api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/release/*$xhr,domain=diep.io`
to your filter list.

**Comment by MasterKia** [comment]
Also reset the uBO to default settings just in case.
https://github.com/uBlockOrigin/uAssets/issues/13679#issuecomment-1153225061

**Comment by MasterKia** [comment]
> I don't see an issue.

Third-party expousre.

**Comment by okiehsch** [comment]
Which specific third-party request do you mean?

**Comment by MasterKia** [comment]
I meant the third-party request to that script (`enthusiastgaming.net`), but nvm

**Comment by JMask480** [comment]
i think it worked for now thank you

**Comment by okiehsch** [comment]
Sure, my comment "I don't see an issue" meant I don't see an issue if the request I allow is the only one that connects due to the exception filter.

**Comment by MasterKia** [comment]
@JMask480 If possible, please let us know when the dev deployed a fix for this problem and maybe we could remove the whitelist filter then.

![image](https://user-images.githubusercontent.com/17685483/173245475-bfd3b1b8-2223-4edf-935c-2afcec49934c.png)
