### ISSUE TITLE
loawa.com: detection

### ISSUE THREAD

**Issue by JaronPryor** [uBlockOrigin/uAssets#13671]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://loawa.com/`

### Category

detection

### Describe the issue

Failed to load images. (AdBlock Exception)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://gyazo.com/a13607121877e5c1eda16a9268e3c014
</details>
Photo of error message after visiting site

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82259
  cosmetic: 43811
  scriptlet: 17203
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68146-50, 1d.7h.9m
    easyprivacy: 27181-122, 1d.7h.8m
    plowe-0: 3638-781, 5d.18h.28m
    ublock-abuse: 75-0, 9d.15h.18m
    ublock-badware: 4171-91, 1d.7h.7m
    ublock-filters: 31728-101, 1d.7h.6m
    ublock-privacy: 222-2, 9d.14h.55m
    ublock-quick-fixes: 210-2, 15h.5m
    ublock-unbreak: 1798-40, 1d.7h.5m
    urlhaus-1: 7457-0, 15h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1470 ms (selfie)
  maxAssetCacheWait: 69 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflareinsights.com: 1
    google.com: 2
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce.
