### ISSUE TITLE
[nsfw] fr.pornhub.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13681]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fr.pornhub.com/`

### Category

ads

### Describe the issue

Des encarts vides peuvent être bloqués.
Aussi, la mention "Annonces de Traffic Junky" est affichée.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/173241425-0fb66093-4629-4609-8cd0-2c12032de587.png)

![image](https://user-images.githubusercontent.com/50231020/173241471-91e509f5-3f7d-4cb4-a602-ae9ecb6c597c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 486971
  cosmetic: 1805
  scriptlet: 34855
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41664-22253, now
    adguard-generic: 64711-33456, now
    adguard-mobile: 7849-6156, now
    curben-phishing: 19910-0, now
    curben-pup: 239-0, now
    fanboy-cookiemonster: 34152-31127, now
    ublock-annoyances: 4437-1304, now
  default: 
    FRA-0: 28869-9182, now
    easylist: 68191-36018, now
    easyprivacy: 27193-605, now
    plowe-0: 3644-891, now
    ublock-abuse: 75-3, now
    ublock-badware: 4191-722, now
    ublock-filters: 31814-10331, now
    ublock-privacy: 222-12, now
    ublock-quick-fixes: 195-81, now
    ublock-unbreak: 1798-280, now
    urlhaus-1: 7596-1, now
filterset (user): [array of 2079 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  parseAllABPHideFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1207 ms
  maxAssetCacheWait: 423 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    pornhub.com: 4
    phncdn.com: 1
```
</details>

**Comment by mapx-** [comment]
I still don't understand WHY are you touching the various settings provoking lots of issues ?!

![image](https://user-images.githubusercontent.com/10303732/173241853-690a9a24-855d-4f37-ae67-37623fa9c640.png)

**Comment by okiehsch** [comment]
Don't embed NSWF images!

**Comment by okiehsch** [comment]
> What is this default setting?

The setting that is enabled on the first install.

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/173242076-06045f48-c1e9-4331-8b1d-3b10d1f06890.png)

**Comment by MasterKia** [comment]
Should add another **Prerequisites**:

> * [x] I did not change any of the defaults settings, or I verified that the issue still occurs with the default settings.



But then again:


> * [x]  I did not answer truthfully to **all** the above checkpoints

**Comment by MasterKia** [comment]
Should add another **Prerequisites**:

> * [x] I did not change any of the defaults settings, or I verified that the issue still occurs with the default settings.



But then again:


> * [x]  I did not answer truthfully to **all** the above checkpoints

**Comment by MasterKia** [comment]
Should add another **Prerequisites**:

> * [x] I did not change any of the defaults settings, or I verified that the issue still occurs with the default settings.



But then again:


> * [x]  I did not answer truthfully to **all** the above checkpoints

**Comment by stephenhawk8054** [comment]
Please don't ended NSFW images directly. Just put the link of the images to the reply.
