### ISSUE TITLE
digital.elmercurio.com: [unknown]

### ISSUE THREAD

**Issue by wottan32** [uBlockOrigin/uAssets#13683]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://digital.elmercurio.com/2022/06/12/A/G344PIMT`

### Category

[unknown]

### Describe the issue

Website Won't Load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-06-12_12-03](https://user-images.githubusercontent.com/29763931/173242213-e33bb750-c306-4a7e-b1bb-0955e8341a8d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85625
  cosmetic: 49623
  scriptlet: 18290
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1922-24, never
    easylist: 68191-50, 1h.35m
    easyprivacy: 27193-122, 1h.34m
    plowe-0: 3638-781, 7d.16h.38m
    spa-0: 3897-36, 13h.37m
    spa-1: 4520-169, 1h.30m
    ublock-abuse: 75-0, 4d.5h.41m
    ublock-badware: 4191-91, 1h.32m
    ublock-filters: 31822-151, 1h.31m
    ublock-privacy: 222-2, 4d.5h.42m
    ublock-quick-fixes: 210-2, 13h.38m
    ublock-unbreak: 1798-42, 1h.33m
    urlhaus-1: 7499-0, 13h.36m
filterset (user): [array of 290 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 348 ms (selfie)
  maxAssetCacheWait: 429 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    elmercurio.com: 4
    emol.cl: 2
    google-analytics.com: 1
```
</details>

**Comment by wottan32** [comment]
thx

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/173242477-dd302f19-8fcb-4d1d-ad3d-5c039c982a7b.png)

I assume you have an account, does the site show if you disable uBO?
