### ISSUE TITLE
m.gamer.com.tw: nuisance

### ISSUE THREAD

**Issue by n-buna404** [uBlockOrigin/uAssets#13689]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.gamer.com.tw/forum/C.php?bsn=60076&snA=7151093`

### Category

nuisance

### Describe the issue

m.gamer.com.tw will open popup to download its app everytime when ppl click to use the navigations key at the bottom as well as change page on the top from 1st page.
Moreover when expanding the comments > than 100 it will also trigger the popup

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

I provided a short video to replicate the issue
https://www44.zippyshare.com/v/p8WxrqUM/file.html
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 110950
  cosmetic: 55296
  scriptlet: 20180
  html: 685
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4445-4, 10h.31m
    dpollock-0: 10375-3, 4d.12h.48m
    CHN-0: 29181-102, 10h.30m
  default: 
    user-filters: 7-0, never
    ublock-filters: 32447-56, 10h.38m
    ublock-badware: 4195-3, 10h.37m
    ublock-privacy: 228-0, 10h.36m
    ublock-abuse: 75-0, 10h.35m
    ublock-unbreak: 1812-1, 10h.34m
    easylist: 68199-766, 10h.33m
    easyprivacy: 27196-700, 10h.32m
    urlhaus-1: 7596-0, 10h.29m
    plowe-0: 3639-483, 4d.12h.48m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 31 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  popupFontSize: 13px
supportStats: 
  allReadyAfter: 370 ms (selfie)
  maxAssetCacheWait: 442 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bahamut.com.tw: 2
    cloudflareinsights.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
```
</details>

**Comment by mapx-** [comment]
try

```
m.gamer.com.tw##.open-app
m.gamer.com.tw##.dialogify__fixedwidth.dialogify__content
```

**Comment by n-buna404** [comment]
Using the second option still prompt grey screen to be removed using 1
click. Is there any other way to fully remove them since blocking the grey
screen will cause the whole screen to be non responsive?

**Comment by mapx-** [comment]
I see no other way => adding a filter to remove the gray thing will block the navigations arrows at the bottom and some articles are non responsive

**Comment by n-buna404** [comment]
Ok thanks for the heads up. That ‘s was the same conclusion that i came up
with thanks for confirming there are another way round
