### ISSUE TITLE
ygosu.com: ads

### ISSUE THREAD

**Issue by changho3995** [uBlockOrigin/uAssets#13685]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.ygosu.com/board/yeobgi/1948045/?searcht=&search=&m3=real_article&frombest=Y&page=3`

### Category

ads

### Describe the issue

Ads don't go away.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 103
filterset (summary): 
  network: 242586
  cosmetic: 239765
  scriptlet: 39533
  html: 773
listset (total-discarded, last updated): 
  added: 
    https://github.com/List-KR/List-KR/raw/master/filter.txt: 1837-85, 23h.21m
    adguard-generic: 64623-6553, 3d.8h.12m
    adguard-spyware: 26191-1092, 3d.8h.12m
    adguard-spyware-url: 627-14, 3d.8h.12m
    block-lan: 43-0, 3d.8h.12m
    curben-phishing: 18126-2, 23h.48m
    curben-pup: 241-0, 23h.47m
    adguard-annoyance: 53987-4987, 3d.8h.11m
    adguard-social: 17645-1663, 3d.8h.11m
    fanboy-thirdparty_social: 69-1, 3d.8h.11m
    fanboy-annoyance: 72483-61025, 3d.8h.11m
    fanboy-cookiemonster: 33441-15269, 3d.8h.11m
    fanboy-social: 23273-13667, 3d.8h.11m
    ublock-annoyances: 4464-15, 3d.8h.11m
    dpollock-0: 10375-508, 3d.8h.11m
    ALB-0: 267-7, 23h.42m
    ara-0: 2573-243, 3d.8h.11m
    BGR-0: 1116-19, 3d.8h.11m
    CHN-0: 29100-1275, 3d.8h.11m
    CZE-0: 711-40, 23h.40m
    [28 lists not shown]: [too many]
  default: 
    user-filters: 4-0, never
    ublock-filters: 32494-687, 3d.8h.12m
    ublock-badware: 4175-3, 3d.8h.12m
    ublock-privacy: 228-3, 3d.8h.12m
    ublock-abuse: 75-0, 3d.8h.12m
    ublock-unbreak: 1816-1, 3d.8h.12m
    ublock-quick-fixes: 203-5, 23h.22m
    adguard-mobile: 7834-230, 3d.8h.12m
    easylist: 68104-25496, 3d.8h.12m
    easyprivacy: 27179-10526, 3d.8h.12m
    urlhaus-1: 4831-0, 23h.49m
    plowe-0: 3639-17, 3d.8h.11m
    KOR-1: 1848-1757, 23h.27m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1239 ms (selfie)
  maxAssetCacheWait: 686 ms
popupPanel: 
  blocked: 8
  no-cosmetic-filtering: true
  blockedDetails: 
    clickmon.co.kr: 1
    coupang.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    mediacategory.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
@piquark6046 @seia-soto

I can reproduce Ad-Shield ads but the ads are extremely delayed (up to 10 seconds ... Seems to be the script is crap and slow) and only on the `m.ygosu.com` subdomain. Tested with uBlock Origin and Adguard with Firefox (simulated a mobile device with the dev tools)

Also i get regular ads please take a look

<img width="444" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/173254332-6d424ed6-b730-4ec2-9958-6a1dfbd50c68.PNG">

**Comment by seia-soto** [comment]
@JobcenterTycoon 

I just checked but I didn't see any slow downs on `ygosu.com`. Their logic to check ad visibility is maybe the problem.

**Comment by JobcenterTycoon** [comment]
Yes adcrap got temporary disabled on this site to fool us

**Comment by piquark6046** [comment]
@changho3995 
Please install [microShield](https://github.com/List-KR/microShield) to remove Ad-Shield.

**Comment by garry-ut99** [comment]
Example URL: `https://ygosu.com/community/animation/310706`
Ad placeholders, caused by `ghide` from "uBlock Filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219865735-392b0e75-83ea-4931-88b1-4768847f7111.png)
I get no AA with `ghide` off, but I've not been investigation so deep, also there is still AA in the source code.

**Comment by seia-soto** [comment]
@garry-ut99 Try `##ins[data-ad-slot]`

**Comment by seia-soto** [comment]
Some of filters might be disabled to counteract anti-adblocking strategy, and the filter above can be your solution.

**Comment by garry-ut99** [comment]
> Try `##ins[data-ad-slot]`

Doesn't work, however this works: `ygosu.com##ins[data-ad-slot]`

> Some of filters might be disabled to counteract anti-adblocking strategy, and the filter above can be your solution.

Seems so, recently: https://github.com/uBlockOrigin/uAssets/commit/5b52525005b22f649be1b65f7d004358aee685ad

**Comment by JobcenterTycoon** [comment]
With `KOR: List-KR` enabled i get no placeholder.

**Comment by garry-ut99** [comment]
I had the `KOR` list already enabled all the time, and the both ad placeholders were still there, always.
Now I've refreshed the page 20 times and what I'm noticing now is the following differencies since the last time:
- only one of them appear (the one at the bottom, under the comments section)
- it appears randomly, sometimes appears, sometimes not
- when it appears it looks like this: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219954528-a742b06e-1c57-4416-a996-43e2991bcbdd.png)

**Comment by piquark6046** [comment]
@garry-ut99 
Then, please add the following filter into your user filter:
```adblock
@@*$ghide,domain=ygosu.com|loawa.com|feedclick.net|algumon.com|sportalkorea.com|ondemandkorea.com,badfilter
```
and, install [microShield](https://github.com/List-KR/microShield/blob/main/README.ko.md) into your web browser.

**Comment by garry-ut99** [comment]
Nah, I won't bother, see https://github.com/uBlockOrigin/uAssets/issues/16537#issuecomment-1407701541 especially given a fact I don't visit Korean sites personally because I'm of a different nationality and came across it once by accident.
