### ISSUE TITLE
tf1.fr: detection

### ISSUE THREAD

**Issue by claudemontreal** [uBlockOrigin/uAssets#13682]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tf1.fr/tf1/the-voice-kids/videos/battle-tiago-amani-diego-chant-sirenes-frero-delavega.html`

### Category

detection

### Describe the issue

Asks me to turn off ad blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 109382
  cosmetic: 161510
  scriptlet: 23954
  html: 684
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53961-3658, 3d.17h.49m
    fanboy-annoyance: 72314-305, 3d.17h.57m
    ublock-annoyances: 4442-4, 3d.17h.50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32357-189, 3d.17h.51m
    ublock-badware: 4175-3, 3d.17h.56m
    ublock-privacy: 228-0, 1d.2h.16m
    ublock-abuse: 75-0, 1d.2h.15m
    ublock-unbreak: 1811-0, 3d.17h.55m
    easylist: 68098-896, 3d.17h.54m
    easyprivacy: 27173-578, 3d.17h.53m
    urlhaus-1: 4831-0, 18h.14m
    plowe-0: 3639-3, 4d.18h.5m
    FRA-0: 28437-358, 3d.17h.52m
    ublock-quick-fixes: 202-0, 18h.13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 703 ms (selfie)
  maxAssetCacheWait: 878 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    facil-iti.app: 1
    sentry-cdn.com: 1
```
</details>

**Comment by okiehsch** [comment]
Hm.
![image](https://user-images.githubusercontent.com/16838044/173242272-b04be19a-4809-4386-b779-eea6a8a43c83.png)

Does not work even if I disable uBO on my end.

**Comment by mapx-** [comment]
same here even disabling uBO

**Comment by claudemontreal** [comment]
Other videos on TF1 are working fine so I guess it's just that specific link that has an issue!

sorry about that!

-------- Message d'origine --------

**Comment by claudemontreal** [comment]
On Chrome I get the same blue screen than you but on Firefox I get the Adblock message seen in the attached file.

-------- Message d'origine --------
