### ISSUE TITLE
twitch.tv: breakage

### ISSUE THREAD

**Issue by AlchemysEyes** [uBlockOrigin/uAssets#13684]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

breakage

### Describe the issue

Any time I try to connect to a stream with Ublock origin enabled I get an infinite stream loading circle bar
![2022-06-12 12_03_36-BeyondTheSummit - Twitch — Mozilla Firefox](https://user-images.githubusercontent.com/107363491/173244639-71c74ab3-095f-43a2-9927-a77d14180179.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82389
  cosmetic: 43872
  scriptlet: 17176
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32445-33, 19h.11m
    ublock-badware: 4195-3, 19h.12m
    ublock-privacy: 228-0, 3d.8h.30m
    ublock-abuse: 75-0, 4d.32m
    ublock-unbreak: 1811-0, 19h.10m
    easylist: 68190-553, 19h.9m
    easyprivacy: 27192-592, 15h.8m
    urlhaus-1: 7499-0, 11h.7m
    plowe-0: 3638-3, 7d.4h.45m
    ublock-quick-fixes: 193-2, 3h.5m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 563 ms (selfie)
  maxAssetCacheWait: 398 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 1
    sentry.io: 1
    serving-sys.com: 1
    ttvnw.net: 1
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by MasterKia** [comment]
> * [x]  I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)

Duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

See: https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
