### ISSUE TITLE
italiashare.net

### ISSUE THREAD

**Issue by andrewxyxyxy** [uBlockOrigin/uAssets#1368]
`http://www.italiashare.net/e-books/riviste-italiane/653342-limes-ottobre-2017.html`

There's a BlockAdBlock

![immagine](https://user-images.githubusercontent.com/26189057/35384491-c48d6b96-01c5-11e8-89b7-eeeb709500a1.png)

- Browser/version: Firefox Quantum 58.0
- uBlock Origin version: Ublock Origin 1.14.24
- Nano Defender 13.24

**Comment by mapx-** [comment]
already fixed in ublock filters, see https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt

**Comment by andrewxyxyxy** [comment]
so, why does the BlockAdBlock come out? where can I be wrong?

**Comment by gorhill** [comment]
> where can I be wrong?

I can reproduce only after I install Nano Defender. You will have to report your issue to Nano Defender.

**Comment by jspenguin2017** [comment]
I don't have build tools on me, it's already fixed for Chrome, I'll upload Firefox version tonight. 
I need to figure out how automation works for Firefox...

**Comment by jspenguin2017** [comment]
I guess I should add a whitelist instead... The scriptlet collided on generic solution.

**Comment by andrewxyxyxy** [comment]
to this address there's a redirecting
http://www.italiashare.net/e-books/riviste-italiane/673687-internazionale-n1240-26-gennaio-2018.html

![immagine](https://user-images.githubusercontent.com/26189057/35503452-7540b656-04e0-11e8-8435-5f255091413b.png)

**Comment by mapx-** [comment]
don't post clickable links

**Comment by andrewxyxyxy** [comment]
`http://www.italiashare.net/regolamento/676475-modifica-al-regolamento-06-02-2018.html`

![immagine](https://user-images.githubusercontent.com/26189057/35989641-f9cf88e2-0d01-11e8-8790-5c8fded26708.png)
