### ISSUE TITLE
forum.donanimarsivi.com: ads

### ISSUE THREAD

**Issue by Oki404** [uBlockOrigin/uAssets#13688]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forum.donanimarsivi.com/`

### Category

ads

### Describe the issue

In Windows everything is fine. But when i start using linux with firefox, i reinstalled uBlock and i see uBlock does not block ads. It blocks some ads, but not all ads. In windows uBlock blocked all ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82588
  cosmetic: 43878
  scriptlet: 17194
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32456-35, now
    ublock-badware: 4195-3, now
    ublock-privacy: 230-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1812-0, now
    ublock-quick-fixes: 195-2, now
    easylist: 68209-565, now
    easyprivacy: 27199-579, now
    urlhaus-1: 7675-0, now
    plowe-0: 3644-3, now
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 466 ms
  maxAssetCacheWait: 180 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    donanimarsivi.com: 2
    cloudflareinsights.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
It's a turkish site.
Enable `TUR: AdGuard Turkish`
