### ISSUE TITLE
my.dxdelivery.com: breakage

### ISSUE THREAD

**Issue by PinkDuck** [uBlockOrigin/uAssets#13690]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.dxdelivery.com/t/1575967697?utm_source=pdn&utm_medium=email`

### Category

breakage

### Describe the issue

The parcel tracking form with reference and postcode is blocked from the page with uBlock running.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/155881/173345354-3f1e74dc-6040-4dcc-8328-0f9f20c2f1db.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 82485
  cosmetic: 43783
  scriptlet: 17173
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32455-32, 14m
    ublock-badware: 4195-3, 1d.19h.59m
    ublock-privacy: 228-1, 11d.17h.14m
    ublock-abuse: 75-0, 7d.4h.29m
    ublock-unbreak: 1811-0, 1d.20h.2m
    easylist: 68190-578, 1d.20h
    easyprivacy: 27192-593, 1d.20h.1m
    urlhaus-1: 7675-0, 13m
    plowe-0: 3670-2, 11d.17h.16m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 30 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7935 ms (selfie)
  maxAssetCacheWait: 305 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    dxdelivery.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
`@@||my.dxdelivery.com/js/tracking.js$script,1p`
should work, can you test with a valid tracking number?

**Comment by okiehsch** [comment]
@ryanbr
