### ISSUE TITLE
Resource Abuse: https://www.freecontent.bid

### ISSUE THREAD

**Issue by ialexsilva** [uBlockOrigin/uAssets#1369]
### URL(s) where the issue occurs
https://punchsub.com/ 

### Describe the issue

Please add this rules to block more miner script https://www.freecontent.bid./scripts/crn.wasm

`||www.freecontent.bid^$third-party`

### Versions

- Browser/version: 64.0.3282.119
- uBlock Origin version: 1.14.24

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
Which is the site / sites where you noted that miner ?

**Comment by ialexsilva** [comment]
@mapx- https://punchsub.com/ (geolocation redirect)
