### ISSUE TITLE
livongo.com: breakage

### ISSUE THREAD

**Issue by great2bnaustin** [uBlockOrigin/uAssets#13695]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.livongo.com/`

### Category

breakage

### Describe the issue

On Google Chrome Log in button will not work with uBlock enabled. Disabling uBlock allows the Log in button to work normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82446
  cosmetic: 43817
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68167-50, 3d.3h.37m
    easyprivacy: 27181-122, 3d.3h.35m
    plowe-0: 3670-807, 11d.5h.46m
    ublock-abuse: 75-0, 1d.3h.28m
    ublock-badware: 4191-91, 3d.3h.34m
    ublock-filters: 31753-101, 3d.3h.36m
    ublock-privacy: 222-2, 1d.3h.27m
    ublock-quick-fixes: 195-2, 23h.25m
    ublock-unbreak: 1798-40, 3d.3h.33m
    urlhaus-1: 7596-0, 23h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 49 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1365 ms (selfie)
  maxAssetCacheWait: 755 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 5
    mixpanel.com: 1
    sentry.io: 1
    visualwebsiteoptimizer.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
@@||googletagmanager.com/gtag/js?id=UA$domain=livongo.com
```

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by great2bnaustin** [comment]
works great now, thank you!
