### ISSUE TITLE
animeout.xyz: nuisance

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#13697]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.animeout.xyz/`

### Category

nuisance

### Describe the issue

pop-up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 83599
  cosmetic: 49839
  scriptlet: 17281
  html: 678
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    ublock-filters: 32458-39, 3m
    ublock-badware: 4211-3, 3m
    ublock-privacy: 230-0, 3m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1812-0, 3m
    ublock-quick-fixes: 196-2, 3m
    easylist: 68248-640, 3m
    easyprivacy: 27206-603, 3m
    urlhaus-1: 7519-0, 3m
    plowe-0: 3644-3, 3m
    JPN-1: 7277-23, now
filterset (user): [array of 72 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 894 ms
  maxAssetCacheWait: 688 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googletagmanager.com: 1
    patreon.com: 5
```
</details>

**Comment by mapx-** [comment]
add

```
animeout.xyz##.spu-box
animeout.xyz##.spu-bg
```

@ryanbr
