### ISSUE TITLE
[nsfw] pcmclks.com: popups

### ISSUE THREAD

**Issue by Ar3sTANK** [uBlockOrigin/uAssets#13698]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pcmclks.com/circus/be/sindex.php?site=pc28-5400099-sxlnd`

### Category

popups

### Describe the issue

Le site de pub s'ouvre sans arrêt.

--

The ad site keeps opening.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 101166
  cosmetic: 52888
  scriptlet: 17266
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-1, never
    FRA-0: 28869-24, 3d.10h.18m
    easylist: 68144-389, 3d.10h.17m
    easyprivacy: 27181-439, 3d.10h.16m
    plowe-0: 3638-788, 7d.13h.53m
    ublock-abuse: 75-1, 7d.13h.53m
    ublock-badware: 4171-99, 3d.10h.15m
    ublock-filters: 31753-249, 3d.10h.14m
    ublock-privacy: 222-2, 7d.13h.53m
    ublock-quick-fixes: 196-2, 5h.47m
    ublock-unbreak: 1797-40, 3d.10h.13m
    urlhaus-1: 7519-0, 5h.46m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 344 ms (selfie)
  maxAssetCacheWait: 1042 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    doubleclick.net: 2
    google.com: 1
    youtube.com: 7
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like original site gives popup and redirects to `pcmclks.com`? Can you describe the steps to reproduce in more details?
