### ISSUE TITLE
20minutos.es

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#13696]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.20minutos.es/videos/cinemania/asi-ha-cambiado-ariana-richards-la-nina-de-parque-jurasico-5013557/`

### Describe the issue

videos no works

### uBlock Origin version

1.42.4

### Browser name and version

Chrome

### Settings

Default + ESP + Annoyances

### Notes

`20minutos.es##+js(aopr, window.hb_now)`

**Comment by stephenhawk8054** [comment]
@Yuki2718
