### ISSUE TITLE
playdede.nu: popups

### ISSUE THREAD

**Issue by nfortea** [uBlockOrigin/uAssets#13709]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://playdede.nu/`

### Category

popups

### Describe the issue

When I do a clic on screen it launch a new window, but the content of new window are blocked por uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 0
  cosmetic: 0
  scriptlet: 0
  html: 0
listset (total-discarded, last updated): [none]
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 
  maxAssetCacheWait: 0 ms
popupPanel: 
  blocked: 48
  no-popups: true
  blockedDetails: 
    adsco.re: 11
    adtelligent.com: 1
    affluentshinymulticultural.com: 1
    ajfnee.com: 2
    antiadblocksystems.com: 3
    commentsengine.com: 1
    d3cod80thn7qnd.cloudfront.net: 3
    declk.com: 4
    google-analytics.com: 2
    histats.com: 1
    jrpkizae.com: 2
    streampiay.me: 4
    unpkg.com: 1
    waaw.to: 5
    youtube.com: 1
    yqmxfz.com: 2
    zap.buzz: 4
```
</details>

**Comment by mapx-** [comment]
no popup on my side:

- go to `https://playdede.nu` => log in using `discord` => no popup

Describe the steps to reproduce the issue

**Comment by Procyon-b** [comment]
@nfortea Are you using ublock with no filter lists enabled at all ?
