### ISSUE TITLE
rbxscripts.net: detection

### ISSUE THREAD

**Issue by Carlosk12xd** [uBlockOrigin/uAssets#13707]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rbxscripts.net/`

### Category

detection

### Describe the issue

Website detects adblocker and even after forcing an update it didnt work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 82407
  cosmetic: 43879
  scriptlet: 17234
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68260-50, 1m
    easyprivacy: 27208-122, 1m
    plowe-0: 3644-781, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4207-91, 1m
    ublock-filters: 31827-100, 1m
    ublock-privacy: 224-2, 1m
    ublock-quick-fixes: 196-4, 1m
    ublock-unbreak: 1799-40, 1m
    urlhaus-1: 7433-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 178 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    rbxscripts.net: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
rbxscripts.net##+js(no-xhr-if, googlesyndication.com)
```
