### ISSUE TITLE
google.com: nuisance

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#13705]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=hold+my+hand+lyrics`

### Category

nuisance

### Describe the issue

I can't copy lyrics.
There was no problem when using the US server with VPN, so it is possible that the problem is only in Japan.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![スクリーンショット 2022-06-14 082319](https://user-images.githubusercontent.com/107383950/173464643-d4eca6dd-2fd4-4236-966f-9a3cad50de0f.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 95918
  cosmetic: 66437
  scriptlet: 21274
  html: 1427
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    JPN-1: null
  added: 
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt: 6992-3, now
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 46135-18586, now
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-social.txt: 2427-1, now
    ublock-annoyances: 4452-51, 51m
  default: 
    ublock-filters: 32458-447, 51m
    ublock-badware: 4211-3, 51m
    ublock-privacy: 230-0, 51m
    ublock-abuse: 75-0, 51m
    ublock-unbreak: 1812-1, 51m
    ublock-quick-fixes: 196-2, 51m
    easylist: 68247-574, 51m
    easyprivacy: 27206-611, 51m
    urlhaus-1: 7519-0, 51m
    plowe-0: 3644-3, 51m
filterset (user): [array of 72 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 695 ms (selfie)
  maxAssetCacheWait: 545 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    google.com: 13
```
</details>

**Comment by gorhill** [comment]
I disabled the filter for the time being, see <https://www.reddit.com/r/uBlockOrigin/comments/vitvol/ublock_origin_seems_to_break_view_image_extension/idgvee7/>.

**Comment by krystian3w** [comment]
@Yuki2718 try test:

```
www.google.*##div[data-song-title] > div, div[data-song-title] [data-lyricid]:style(user-select: auto !important;)
```

if only songs has protected.

**Comment by chimaha** [comment]
Some lyrics don't have [data-song-title]
[https://www.google.com/search?q=%E6%96%B0%E6%99%82%E4%BB%A3+%E6%AD%8C%E8%A9%9E](url)
How about [data-attrid="kc:/music/recording_cluster:lyrics"]

**Comment by krystian3w** [comment]
I see that need change language in setting, because English still have.
