### ISSUE TITLE
nytimes.com: breakage

### ISSUE THREAD

**Issue by Armavica** [uBlockOrigin/uAssets#13706]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nytimes.com/2022/06/13/crosswords/chess/chess-replay-you-versus-frumkin.html`

### Category

breakage

### Describe the issue

This is a new game of the New York Times.
The pieces don't appear on the chess board if `EasyPrivacy` is selected. When I unselect this list, the page works properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 91
filterset (summary): 
  network: 149208
  cosmetic: 205003
  scriptlet: 36526
  html: 686
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64703-5107, 3d.10m
    adguard-mobile: 7843-155, 3d.16m
    adguard-spyware: 26209-887, 3d.12m
    adguard-spyware-url: 629-27, 3d.14m
    block-lan: 43-0, 24d.6h.45m
    adguard-annoyance: 54059-4493, 3d.11m
    adguard-social: 17689-1077, 3d.13m
    fanboy-thirdparty_social: 69-0, 4d.22h.31m
    fanboy-annoyance: 72445-56870, 4d.22h.30m
    fanboy-cookiemonster: 33403-100, 4d.22h.29m
    fanboy-social: 23271-28, 3d.15m
    ublock-annoyances: 4444-4, 3d.17m
    curben-phishing: 20720-1, 17h.11m
    curben-pup: 235-0, 17h.10m
  default: 
    user-filters: 219-2, never
    ublock-filters: 32451-66, 3d.9m
    ublock-badware: 4195-3, 3d.8m
    ublock-privacy: 228-0, 7d.2h.29m
    ublock-abuse: 75-0, 7d.2h.28m
    ublock-unbreak: 1811-1, 3d.7m
    easylist: 68167-752, 3d.6m
    easyprivacy: 27185-10395, 2d.18h.7m
    urlhaus-1: 7675-0, 17h.12m
    plowe-0: 3639-3, 5d.2h.34m
    ublock-quick-fixes: 195-0, 17h.13m
filterset (user): [array of 224 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 606 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    nytimes.com: 17
    amazon-adsystem.com: 1
    doubleclick.net: 1
    geoedge.be: 1
    googletagmanager.com: 1
    nyt.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
@@||www.nytimes.com/games-assets/chess-puzzles/analytics.js$script,domain=nytimes.com
```

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by Armavica** [comment]
Thank you to both of you! :)
