### ISSUE TITLE
faselhd.club: popups

### ISSUE THREAD

**Issue by ManoMomen** [uBlockOrigin/uAssets#13719]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.faselhd.club/episodes/%d9%85%d8%b3%d9%84%d8%b3%d9%84-evil-%d8%a7%d9%84%d9%85%d9%88%d8%b3%d9%85-%d8%a7%d9%84%d8%ab%d8%a7%d9%86%d9%8a-%d8%a7%d9%84%d8%ad%d9%84%d9%82%d8%a9-9`

### Category

popups

### Describe the issue

popups tabs open when i press any place in the page specially on the video players  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82295
  cosmetic: 43799
  scriptlet: 17214
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68258-50, 1d.3h.29m
    easyprivacy: 27208-122, 1d.3h.28m
    plowe-0: 3638-781, 9d.11h.8m
    ublock-abuse: 75-0, 9d.11h.10m
    ublock-badware: 4197-91, 1d.3h.31m
    ublock-filters: 31827-100, 1d.3h.30m
    ublock-privacy: 222-2, 9d.11h.9m
    ublock-unbreak: 1799-40, 1d.3h.27m
    urlhaus-1: 7433-0, 19h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 572 ms (selfie)
  maxAssetCacheWait: 399 ms
popupPanel: 
  blocked: 43
  blockedDetails: 
    cammpaign.com: 1
    denetsuk.com: 5
    googletagmanager.com: 4
    jomtingi.net: 16
    jwpltx.com: 1
    nessainy.net: 2
    rtmark.net: 8
    thaudray.com: 2
    toglooman.com: 2
    waisheph.com: 2
```
</details>

**Comment by ghajini** [comment]
update your ublock filters with default settings

**Comment by Yuki2718** [comment]
@ghajini If you use `fix #issue_number` in commit title, corresponding issue will automaticlly be closed.

**Comment by ghajini** [comment]
> @ghajini If you use `fix #issue_number` in commit title, corresponding issue will automaticlly be closed.

thanks, sounds good
