### ISSUE TITLE
Crypto giveaway scam 2xdoubles.com

### ISSUE THREAD

**Issue by resulin** [uBlockOrigin/uAssets#13718]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.2xdoubles.com/`

### Describe the issue

This is a crypto giveaway scam 2xdoubles.com that should be blocked

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 91 ESR

### Settings

default

**Comment by MasterKia** [comment]
Should be reported to [PhishTank](https://www.phishtank.com/add_web_phish.php) / [OpenPhish](https://openphish.com/faq.html)?

From [Phishing URL Blocklist](https://gitlab.com/malware-filter/phishing-filter#issues):
> Please report new phishing URL to [PhishTank](https://www.phishtank.com/add_web_phish.php) or [OpenPhish](https://openphish.com/faq.html).

**Comment by mapx-** [comment]
@resulin do you have some more details ?

**Comment by krystian3w** [comment]
PhishTank no longer allow create new accounts via web forms - maybe via e-mailing can by add accounts for new bug companies/corporations.

**Comment by MasterKia** [comment]
![image](https://user-images.githubusercontent.com/17685483/173833075-8efafce8-cd7d-44e9-94fd-e3bb8ed3b7a9.png)

Windows Defender.

**Comment by MasterKia** [comment]
Windows Defender:
![image](https://user-images.githubusercontent.com/17685483/173833626-32e9d075-adf1-4312-af71-fd1ddb91479a.png)

Microsoft Edge SmartScreen:
![image](https://user-images.githubusercontent.com/17685483/173833729-969a0b5e-2ee6-4c26-8b58-d1fb7c75af16.png)
