### ISSUE TITLE
theblock.co: nuisance

### ISSUE THREAD

**Issue by RedDeadRandy** [uBlockOrigin/uAssets#13717]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theblock.co/`

### Category

nuisance

### Describe the issue

Full page pop up overlays and a few embedded items/banners
![image](https://user-images.githubusercontent.com/73184649/173709249-f3077398-9ee8-4924-bcb7-b9bb4e6af471.png)
![image](https://user-images.githubusercontent.com/73184649/173709297-557c72fd-2b9b-4440-bd94-37d92b954259.png)
![image](https://user-images.githubusercontent.com/73184649/173709368-bb9a328c-18be-4042-82c3-1cd3483a63e3.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 127895
  cosmetic: 151144
  scriptlet: 36939
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-136, 1h.46m
    https://raw.githubusercontent.com/dumbusernameidk/ublock-filters/master/Filters.txt: 5295-34, 1h.46m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 1h.46m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-47, 1h.46m
    adguard-annoyance: 54088-1751, 1h.46m
    adguard-generic: 64806-1275, 1h.46m
    adguard-mobile: 7860-127, 1h.46m
    adguard-social: 17735-1975, 1h.46m
    fanboy-annoyance: 73409-35257, 1h.46m
    fanboy-cookiemonster: 34425-34425, 1h.46m
    ublock-annoyances: 4454-229, 1h.46m
  default: 
    easylist: 68293-25327, 1h.46m
    easyprivacy: 27213-628, 1h.46m
    ublock-abuse: 75-0, 1h.46m
    ublock-badware: 4152-324, 1h.46m
    ublock-filters: 31825-4064, 1h.46m
    ublock-privacy: 224-9, 1h.46m
    ublock-quick-fixes: 201-18, 1h.46m
    ublock-unbreak: 1799-86, 1h.46m
    urlhaus-1: 7001-0, 1h.46m
filterset (user): [array of 308 redacted]
trustedset: 
  added: [array of 733 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 18 redacted]
hostRuleset: 
  added: [array of 19 redacted]
urlRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 520 ms (selfie)
  maxAssetCacheWait: 438 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    theblock.co: 19
    google-analytics.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
theblock.co##div[ga-event-category="Advertisement"]
theblock.co##.newsletterBox 
theblock.co##body.overflow-hidden:style(overflow: auto !important;)
```
