### ISSUE TITLE
hdrezka.website: ads

### ISSUE THREAD

**Issue by TicTacFruit** [uBlockOrigin/uAssets#13715]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdrezka.website/cartoons/fiction/30299-lyubov-smert-i-roboty-2019.html`

### Category

ads

### Describe the issue

The AD built in the media player remains unblocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 81899
  cosmetic: 43878
  scriptlet: 17178
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-1, never
    ublock-filters: 32447-99, 2d.7h.26m
    ublock-badware: 4195-3, 2d.7h.27m
    ublock-privacy: 228-0, 11d.23h.7m
    ublock-abuse: 75-0, 11d.23h.6m
    ublock-unbreak: 1811-10, 2d.7h.30m
    easylist: 68191-137, 2d.7h.29m
    easyprivacy: 27193-592, 2d.7h.28m
    urlhaus-1: 7001-0, 4h
    plowe-0: 3670-370, 11d.23h.8m
    ublock-quick-fixes: 197-0, 4h.1m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 440 ms
  maxAssetCacheWait: 186 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adpod.in: 1
    franecki.net: 6
    franeski.net: 3
    jsdelivr.net: 1
    mail.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
russian site, add RUS: RU AdList
