### ISSUE TITLE
cuon.io [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1371]
URL(s) where the issue occurs

`http://cuon.io/SHP4N`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
it redirects to `adlinkme.com`, already fixed
