### ISSUE TITLE
[nsfw] trtworld.com: breakage

### ISSUE THREAD

**Issue by rsssxd** [uBlockOrigin/uAssets#13716]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.trtworld.com/`

### Category

breakage

### Describe the issue

The homepage is completely broken

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 157150
  cosmetic: 204994
  scriptlet: 36527
  html: 689
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64702-5131, 3d.10h.10m
    adguard-spyware: 26209-991, 3d.10h.11m
    adguard-spyware-url: 629-14, 3d.10h.25m
    block-lan: 43-0, 7d.12h.6m
    curben-phishing: 20024-2, 6h.29m
    curben-pup: 233-0, 6h.28m
    adguard-annoyance: 54060-4497, 3d.10h.12m
    adguard-social: 17689-1082, 3d.10h.2m
    fanboy-thirdparty_social: 68-0, 7d.12h.6m
    fanboy-annoyance: 72307-56728, 7d.12h.6m
    fanboy-cookiemonster: 33282-108, 7d.12h.6m
    fanboy-social: 23271-29, 2d.10h.24m
    ublock-annoyances: 4465-4, 3d.10h.9m
    dpollock-0: 10375-485, 7d.12h.5m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32539-54, 3d.9h.54m
    ublock-badware: 4195-3, 3d.9h.53m
    ublock-privacy: 228-0, 3d.9h.52m
    ublock-abuse: 75-0, 7d.12h.6m
    ublock-unbreak: 1816-1, 3d.9h.51m
    ublock-quick-fixes: 196-0, 43m
    adguard-mobile: 7843-194, 3d.10h.26m
    easylist: 68190-921, 3d.9h.50m
    easyprivacy: 27187-10451, 3d.9h.49m
    urlhaus-1: 7001-0, 42m
    plowe-0: 3639-3, 7d.12h.5m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2200 ms (selfie)
  maxAssetCacheWait: 1500 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    h-cdn.com: 1
```
</details>

**Comment by rsssxd** [comment]
![Screenshot_20220615-004258](https://user-images.githubusercontent.com/60405617/173694301-0f160c2a-8b5b-4052-88f6-69b1fa82556e.png)

**Comment by rsssxd** [comment]
![Screenshot_20220615-004326](https://user-images.githubusercontent.com/60405617/173694343-a320033e-0515-48da-b200-df45456771ae.png)

**Comment by Procyon-b** [comment]
Try this:
```
trtworld.com##body > header.navbar:style(margin-top: 0 !important;)
```

**Comment by rsssxd** [comment]
Thanks it worked.

**Comment by mapx-** [comment]
I see no breakage.
Does it happen only on mobile ? The pics are couples with / without uBO enabled ?

**Comment by rsssxd** [comment]
This error only applies to mobile

**Comment by rsssxd** [comment]
uBo active in both pictures

**Comment by mapx-** [comment]
@Yuki2718 maybe you could add it to `AdGuard Mobile Ads` if able to reproduce it

**Comment by mapx-** [comment]
@ghajini can you reproduce it and then test on your side @Procyon-b fix ?

**Comment by mapx-** [comment]
@rsssxd you should investigate which non-default filter list breaks that page

**Comment by rsssxd** [comment]
Adguard annoyances list

**Comment by ghajini** [comment]
Describe what do you mean by a breakage?

i see no blank homepage with adguard annoyances or even if i select all filter lists jyst like you

**Comment by rsssxd** [comment]
Look carefully at the picture I posted above. The header that should have stayed above slides down carelessly.

**Comment by ghajini** [comment]
update **adguard annoyances** in couple of hours, its fixed

**Comment by Yuki2718** [comment]
> * [x]  I did not remove any of the default filter lists, or I verified that the issue is not caused by removing any of the default lists
> * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> * [x]  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
> 
> * [x]  I did not answer truthfully to **all** the above checkpoints
