### ISSUE TITLE
letsread.site: ads

### ISSUE THREAD

**Issue by stanislavyv** [uBlockOrigin/uAssets#13712]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://letsread.site/?utm_click_id=AqDvpwQAAAGBYSmClgAAWVwAAANJAAAAAA`

### Category

ads

### Describe the issue

The site is a scam

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary): 
  network: 84456
  cosmetic: 26041
  scriptlet: 17204
  html: 681
listset (total-discarded, last updated): 
  added: 
    BGR-0: 1116-19, 2d.18h.18m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32474-295, 1d.1h.33m
    ublock-badware: 4150-3, 3d.6h.22m
    ublock-privacy: 228-1, 7d.3h.55m
    ublock-abuse: 75-0, 7d.21h.35m
    ublock-unbreak: 1816-0, 2d.14h.4m
    adguard-mobile: 7850-173, 55m
    easylist: 68263-24846, 54m
    easyprivacy: 27206-587, 13h.4m
    urlhaus-1: 7433-0, 53m
    plowe-0: 3670-3, 11d.9h.54m
    ublock-quick-fixes: 193-0, 52m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 961 ms (selfie)
  maxAssetCacheWait: 1655 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by MasterKia** [comment]
> ads

Where is the _ads_?
I all get is `error code: 1020`.
Send address of the **_actual_** page where you see the ads.

**Comment by MasterKia** [comment]
> ads

Where is the _ads_?
All I get is `error code: 1020`.
Send address of the **_actual_** page where you see the ads.

**Comment by stanislavyv** [comment]
I can't seem to recreate the problem so I'll close the issue.
Initially, I clicked the google link of a local university site and it redirected me through 4-5 different sites before finally stopping at the provided link. Now it works as expected for some reason.

**Comment by stanislavyv** [comment]
Here's a screenshot of the provided ad link (maybe you have to be situated in Bulgaria to open it?): ![Screenshot_2022-06-14-11-54-21-280_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/63970354/173536972-fe00b42a-e64d-4894-a27b-2b084aa82b56.jpg)

**Comment by MasterKia** [comment]
Could you send the "Google link" that lead to those 4-5 redirects?

**Comment by stanislavyv** [comment]
Yeah I happily would but as I've already mentioned the link leads me to the actual site now for some reason...
