### ISSUE TITLE
lightnovelworld.com: detection

### ISSUE THREAD

**Issue by ecorchee** [uBlockOrigin/uAssets#13729]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelworld.com/novel/my-disciples-are-all-villains-10062255/chapters?chorder=desc`

### Category

detection

### Describe the issue

the site detects ad blockers and shows a pop up every few seconds to disable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82902
  cosmetic: 43799
  scriptlet: 17214
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68258-50, 1d.23h.11m
    easyprivacy: 27208-122, 1d.23h.12m
    plowe-0: 3644-781, 3d.1h.30m
    ublock-abuse: 75-0, 10d.5h.13m
    ublock-badware: 4197-91, 1d.23h.10m
    ublock-filters: 31827-100, 1d.23h.8m
    ublock-privacy: 222-2, 10d.5h.12m
    ublock-unbreak: 1799-40, 1d.23h.9m
    urlhaus-1: 8033-0, 2h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1125 ms (selfie)
  maxAssetCacheWait: 446 ms
popupPanel: 
  blocked: 5
  no-popups: true
  blockedDetails: 
    lightnovelworld.com: 2
    googletagmanager.com: 1
    quantserve.com: 1
    vntsm.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
sailthru.js$script,domain=lightnovelworld.com,redirect-rule=noop.js
```

**Comment by KonoromiHimaries** [comment]
@mapx- ref

**Comment by mapx-** [comment]
fixed yesterday, update quick fixes list

**Comment by KonoromiHimaries** [comment]
@mapx- ref

**Comment by KonoromiHimaries** [comment]
@mapx- ref

**Comment by KonoromiHimaries** [comment]
@Yuki2718 ref, aa detect on all domains

**Comment by KonoromiHimaries** [comment]
@mapx-  ref, aa detect on all domains

**Comment by KonoromiHimaries** [comment]
@mapx-  ref, aa detect on all domains

**Comment by KonoromiHimaries** [comment]
@mapx- ref, aa detect on all domains

**Comment by Procyon-b** [comment]
@mapx- https://www.reddit.com/r/uBlockOrigin/comments/13fpnd9/adblock_detection_on_lightnovelpub/

**Comment by mapx-** [comment]
I get no detection, do you ?

**Comment by Procyon-b** [comment]
I got one before creating the filter.

**Comment by Procyon-b** [comment]
But now I realize that one of my filter lists wasn't updated.
