### ISSUE TITLE
lightnovelpub.com: detection

### ISSUE THREAD

**Issue by Plebianweeb** [uBlockOrigin/uAssets#13725]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelpub.com/`

### Category

detection

### Describe the issue

cant block element either it scroll locks the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2](https://user-images.githubusercontent.com/106827163/173896394-68812ddf-5e9a-4216-a19b-9470d36e3a4e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 84069
  cosmetic: 50409
  scriptlet: 17616
  html: 0
listset (total-discarded, last updated): 
  added: 
    TUR-0: 8813-116, 2d.22h.28m
  default: 
    user-filters: 3-0, never
    easylist: 68191-68, 2d.22h.27m
    easyprivacy: 27193-127, 2d.22h.26m
    plowe-0: 3638-782, 10d.21h.22m
    ublock-abuse: 75-0, 10d.21h.21m
    ublock-badware: 4191-91, 2d.22h.25m
    ublock-filters: 31822-106, 2d.22h.24m
    ublock-privacy: 222-2, 10d.21h.20m
    ublock-quick-fixes: 201-2, 6h.43m
    ublock-unbreak: 1798-40, 2d.22h.23m
    urlhaus-1: 7444-0, 6h.44m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1231 ms (selfie)
  maxAssetCacheWait: 711 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    lightnovelpub.com: 2
    googletagmanager.com: 1
    pub.network: 2
    quantserve.com: 1
```
</details>

**Comment by Plebianweeb** [comment]
it still doesnt work btw also checked on chrome aswell, why close the issue if it isnt fixed...

**Comment by mapx-** [comment]
Did you update `uBlock filter` list ?
