### ISSUE TITLE
elecktrotanya.com - detection

### ISSUE THREAD

**Issue by KPackratt2k** [uBlockOrigin/uAssets#13720]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://elektrotanya.com/rca_25gt240tx3_chassis_ctc185aa9.pdf/download.html`

### Describe the issue

This website detects adblocker when it should display a captcha in the download field. This is my first time encountering this problem. I used to be able to download from this site with uBlock enabled, but now I can't anymore.

### Screenshot(s)

![electrotanya](https://user-images.githubusercontent.com/91852423/173746800-4be06555-684e-4b1f-8d48-ce13673dbef4.png)

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 91.10.0esr and Google Chrome 102.0.5005.115

### Settings

I haven't made any changes to the default settings.

**Comment by Yuki2718** [comment]
How about `||elektrotanya.com/files/ads/adsbygoogle.js$script,redirect=prebid-ads.js`?

**Comment by mapx-** [comment]
very easy to circumvent.
