### ISSUE TITLE
twitter.com home page - login not possible with ublock enabled

### ISSUE THREAD

**Issue by EricRa** [uBlockOrigin/uAssets#13728]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://twitter.com/

### Describe the issue

As of today's uBlock origin version, the login bar no longer shows at Twitter.com, making it not possible to login from the home page unless uBlock is disabled.  After toggling some filter lists, this seems to be caused by the "uBlock filters – Annoyances" filter list.  

### Screenshot(s)

![with-ublock-enabled](https://user-images.githubusercontent.com/6969787/173932094-630a32ee-1c97-4455-9d50-1e1068844dcc.png)
![with-ublock-disabled](https://user-images.githubusercontent.com/6969787/173932108-6bb244f7-0cda-458c-924b-a1feef0718b7.png)

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 101.0.1 (64-bit)

### Settings

- I don't recall if the "uBlock filters – Annoyances" is enabled by default, but this seems to be causing the problem.

**Comment by EricRa** [comment]
I should also note that this was displaying properly yesterday (6/14/22) before UBO's latest update.

**Comment by Procyon-b** [comment]
I don't have any problem, even with "uBlock filters – Annoyances".
The twitter page doesn't look like this at all for me. Check if you don't have a userstyle enabled for this site.

Here is what I see:
![twitter-login](https://user-images.githubusercontent.com/40043075/173956505-79fef3bd-8a46-47a5-8489-cd5960dc18e0.jpg)

**Comment by EricRa** [comment]
I am now getting the same page as you when opening the site.  Don't know if it was an issue with their site temporarily or if I was just getting A/B tested or something.  I'll close for now and reopen after testing if it occurs again.

**Comment by hughes** [comment]
This is happening for me today, also on 1.43.0 with the default lists.
