### ISSUE TITLE
cinemaniahdd.com [Anti-Adblock] [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1373]
URL(s) where the issue occurs

`https://cinemaniahdd.com/valiente-2012-full-1080p-latino`

Describe the issue

Anti-Adblock

![](https://i.imgur.com/7IYoNyw.png)
![](https://i.imgur.com/zNShRwm.png)
![](https://i.imgur.com/E4lnMuI.png)

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
I'm not sure about the expected behaviour, test these filters:

```
cinemaniahdd.com##script:inject(window.open-defuser.js)
sobremascotas.info##script:inject(abort-on-property-write.js, adBlockDetected)
shortn-me.com##script:inject(abort-current-inline-script.js, $, document.oncontextmenu)
```

**Comment by xDarkARG** [comment]
Pop-up keeps appearing but the anti-adblock left blank forces you to click on the advertisement for the counter to give you the link

![](https://i.imgur.com/tLOiTci.png)

**Comment by xDarkARG** [comment]
@mapx- with this line blocks the perfect Pop-up

`cinemaniahdd.com##script:inject(bab-defuser.js)`

**Comment by xDarkARG** [comment]
@mapx- 
You can close the post if you want

**Comment by xDarkARG** [comment]
Here is the solution @mapx-
https://github.com/AdguardTeam/AdguardFilters/issues/10865

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.cinemaniahdd.net/el-marginal-2019-temporada-3-web-dl-108p-latino/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://reyna-anime.com/#aHR0cDovL3Bhc3RlZHBlbGlzLmNsdWIvP3Y9bEFC`
