### ISSUE TITLE
zerohedge.com: breakage

### ISSUE THREAD

**Issue by DrMandible** [uBlockOrigin/uAssets#13735]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zerohedge.com/markets/recession-now-guaranteed-one-term-white-house-begins-panic`

### Category

breakage

### Describe the issue

Cannot sign in using button at the bottom of any article (not just the particular one linked in this bug). Button has text "Sign in to comment"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83038
  cosmetic: 43883
  scriptlet: 17231
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68283-50, 1d.21h.4m
    easyprivacy: 27213-122, 1d.21h.3m
    plowe-0: 3638-781, 10d.17m
    ublock-abuse: 75-0, 10d.19m
    ublock-badware: 4207-91, 1d.21h.7m
    ublock-filters: 31823-101, 1d.21h.6m
    ublock-privacy: 222-2, 10d.20m
    ublock-quick-fixes: 211-3, 17h
    ublock-unbreak: 1799-40, 1d.21h.5m
    urlhaus-1: 8033-0, 16h.59m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 17
  no-large-media: true
  blockedDetails: 
    zerohedge.com: 2
    d2c4ylitp1qu24.cloudfront.net: 1
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
    s-onetag.com: 1
    twitter.com: 10
```
</details>

**Comment by mapx-** [comment]
Nothing happens when I click `Sign in to comment` - even disabling uBO

**Comment by ghajini** [comment]
need to sign in with account
1st login & then you can comment
