### ISSUE TITLE
leaguelineup.com: detection

### ISSUE THREAD

**Issue by eleeucsd** [uBlockOrigin/uAssets#13736]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.leaguelineup.com/welcome.asp?url=callookouts`

### Category

detection

### Describe the issue

Detects Ublock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 153967
  cosmetic: 148082
  scriptlet: 36719
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-3, 23h.33m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 23h.30m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 4d.22h.22m
    https://slickdeals.net/attachment/extension/allowlist.txt: 111-1, 3d.22h.3m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-44, 4d.22h.21m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-137, 1d.15h.2m
    https://winhelp2002.mvps.org/hosts.txt: 8730-316, 4d.22h.20m
    adguard-annoyance: 54074-1732, 3d.22h.15m
    adguard-generic: 64711-1149, 3d.22h.14m
    adguard-mobile: 7849-242, 3d.22h.13m
    adguard-social: 17692-1970, 3d.22h.12m
    adguard-spyware: 26212-1094, 3d.22h.11m
    dpollock-0: 10375-1775, 5d.10h.29m
    fanboy-annoyance: 72827-35167, 5d.10h.28m
    fanboy-cookiemonster: 33785-33785, 5d.10h.27m
    fanboy-social: 23271-23271, 3d.22h.8m
    fanboy-thirdparty_social: 69-21, 6d.11h.3m
    ublock-annoyances: 4437-398, 3d.22h.7m
  default: 
    user-filters: 9-1, never
    easylist: 68191-25467, 3d.22h.10m
    easyprivacy: 27193-10414, 3d.22h.9m
    plowe-0: 3639-2478, 8d.13h.36m
    ublock-abuse: 75-0, 7d.15h.10m
    ublock-badware: 4191-323, 3d.22h.6m
    ublock-filters: 31822-4003, 3d.22h.5m
    ublock-privacy: 222-47, 7d.15h.9m
    ublock-quick-fixes: 211-14, 23h.31m
    ublock-unbreak: 1798-99, 3d.22h.4m
    urlhaus-1: 8033-0, 23h.32m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 112 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1144 ms (selfie)
  maxAssetCacheWait: 493 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adsafeprotected.com: 2
    advertising.com: 1
    consensu.org: 1
    doubleclick.net: 1
    facebook.com: 3
    facebook.net: 1
    googlesyndication.com: 1
    hotjar.com: 1
    mxpnl.com: 1
    newrelic.com: 1
    scorecardresearch.com: 3
```
</details>

**Comment by mapx-** [comment]
reset uBO to default settings, don't add any other list, test again
