### ISSUE TITLE
nationalreview.com: detection

### ISSUE THREAD

**Issue by mark-eh** [uBlockOrigin/uAssets#13730]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nationalreview.com/`

### Category

detection
Blocks page

### Describe the issue

getadmiral.com. Covers page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![getadmiral com](https://user-images.githubusercontent.com/52550845/173985142-3216bd69-1ce2-4ae7-bccf-97a4516a8d4d.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 99497
  cosmetic: 194752
  scriptlet: 24010
  html: 686
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-1, 2h.52m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt: 211-0, 2h.52m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-139, 2h.52m
    https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt: 211-211, 2h.52m
    adguard-annoyance: 54106-3767, 2h.5m
    fanboy-annoyance: 73402-1514, 2h.50m
    ublock-annoyances: 4464-4, 2h.52m
  default: 
    user-filters: 128-8, never
    ublock-filters: 32404-100, 2h.52m
    ublock-badware: 4161-3, 2h.52m
    ublock-privacy: 230-2, 2h.52m
    ublock-abuse: 75-0, 2h.52m
    ublock-unbreak: 1813-0, 2h.52m
    easylist: 68409-490, 2h.52m
    easyprivacy: 27216-593, 2h.52m
    urlhaus-1: 8033-3485, 2h.52m
    plowe-0: 3645-3, 2h.52m
    ublock-quick-fixes: 211-211, 2h.52m
filterset (user): [array of 129 redacted]
trustedset: 
  added: [array of 199 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2023 ms
  maxAssetCacheWait: 520 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    nationalreview.com: 3
    adsafeprotected.com: 2
    advertising.com: 1
    beop.io: 2
    bounceexchange.com: 1
    d14pdm1b7fi5kh.cloudfront.net: 1
    d1z2jf7jlzjs58.cloudfront.net: 1
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    liadm.com: 2
    ntv.io: 1
    onesignal.com: 2
    revcontent.com: 1
    sail-horizon.com: 2
    scorecardresearch.com: 2
    tfla.xyz: 1
    tru.am: 1
```
</details>

**Comment by mark-eh** [comment]
More info:
https://blog.getadmiral.com/ultimate-guide-whitelisting
How to defeat Ublock,

**Comment by MasterKia** [comment]
Add this to "_My filters_" and see if it works:
`||childlikecrowd.com^$domain=nationalreview.com`

**Comment by mark-eh** [comment]
Seems to have worked. Thanks...
