### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Directrix-Digital** [uBlockOrigin/uAssets#13731]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

You tube reports 'not connected to the internet' if uBlockOrigin is enabled. If I disable uBlockOrigin , YouTube works without issues.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 83003
  cosmetic: 43875
  scriptlet: 17195
  html: 678
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32454-32, 2d.7h.24m
    ublock-badware: 4201-3, 2d.7h.28m
    ublock-privacy: 230-0, 2d.7h.31m
    ublock-abuse: 75-0, 2d.7h.30m
    ublock-unbreak: 1812-0, 2d.7h.27m
    easylist: 68248-212, 2d.7h.26m
    easyprivacy: 27206-593, 2d.7h.25m
    urlhaus-1: 8033-0, 3h.50m
    plowe-0: 3644-344, 2d.7h.29m
    ublock-quick-fixes: 201-5, 3h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 27 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 14166 ms (selfie)
  maxAssetCacheWait: 228 ms
popupPanel: 
  blocked: 303
  blockedDetails: 
    youtube.com: 252
    doubleclick.net: 4
    google.com: 37
    google.com.au: 1
    googlevideo.com: 9
```
</details>

**Comment by Directrix-Digital** [comment]
The tool to verify that the issue has not already been reported is completely broken and I could not get it to work after spending considerable time trying. So I submitted this report anyway.

**Comment by mapx-** [comment]
Reset uBO to default settings / filter lists. Disable ETP. Test again.

YT issues: https://github.com/uBlockOrigin/uAssets/issues/7636
