### ISSUE TITLE
streamingcommunity.press: detection

### ISSUE THREAD

**Issue by jackmattia** [uBlockOrigin/uAssets#13738]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamingcommunity.press/watch/5075?e=37243`

### Category

detection

### Describe the issue

uBlock detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 89158
  cosmetic: 51241
  scriptlet: 17237
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 13081-0, 1m
    easylist: 68450-54, 1m
    easyprivacy: 27220-124, 1m
    plowe-0: 3648-783, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4158-91, 1m
    ublock-filters: 31792-109, 1m
    ublock-privacy: 224-2, 1m
    ublock-unbreak: 1802-40, 1m
    urlhaus-1: 8552-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 255 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 3
  no-large-media: true
  blockedDetails: 
    googletagmanager.com: 1
    thaudray.com: 2
```
</details>

**Comment by Procyon-b** [comment]
@JobcenterTycoon
no-xhr-if gets rid of the adblock message, but the video doesn't play.
This works:
```
||thaudray.com^$script,xhr,redirect-rule=noop.js,domain=streamingcommunity.*
```

**Comment by mapx-** [comment]
working fine FF / chrome

**Comment by jackmattia** [comment]
<img width="474" alt="Schermata 2022-06-16 alle 19 10 59" src="https://user-images.githubusercontent.com/104214895/174128239-ae7106b3-28fb-4a25-ab81-c8e70ddb48ef.png">

**Comment by Procyon-b** [comment]
@jackmattia  paste the 2 filters in "my filters":
```
streamingcommunity.*#@#+js(no-xhr-if, thaudray.com)
||thaudray.com^$script,xhr,redirect-rule=noop.js,domain=streamingcommunity.*
```

**Comment by jackmattia** [comment]
Wow thank you. Problem solved

**Comment by Procyon-b** [comment]
@jackmattia you can comment the user filters and refresh the filter lists. @JobcenterTycoon has fixed the issue.
