### ISSUE TITLE
hdfilmcehennem.live: ads

### ISSUE THREAD

**Issue by MuhammetEminCakir** [uBlockOrigin/uAssets#13739]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hdfilmcehennem.live/malefiz-2-turkce-dublaj-izle.html`

### Category

ads

### Describe the issue

This site has ads and pop-ups.
`||www.hdfilmcehennem.live/reklams/hcnm/pg.webp$image` filter only works once.  Ad appears again after refreshing the tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/64583157/174129124-375f0f5a-368d-4cd3-bfcc-1fdfa0b49e38.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 89058
  cosmetic: 96651
  scriptlet: 20073
  html: 679
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54118-626, 9h.53m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32405-45, 9h.54m
    ublock-badware: 4161-3, 9h.54m
    ublock-privacy: 230-0, 9h.54m
    ublock-abuse: 75-0, 9h.54m
    ublock-unbreak: 1813-0, 9h.54m
    ublock-quick-fixes: 211-2, 9h.54m
    easylist: 68411-584, 9h.54m
    easyprivacy: 27217-584, 9h.54m
    urlhaus-1: 7993-0, 9h.53m
    plowe-0: 3645-3, 9h.53m
    TUR-0: 8254-59, 9h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    opera-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 588 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    alexametrics.com: 1
```
</details>

**Comment by mapx-** [comment]
```
hdfilmcehennem.live##[href*="/redirect"]
||hdfilmcehennem.live/reklams/
hdfilmcehennem.live##+js(nowoif)
```

for turkish list @Yuki2718 @AdamWr

**Comment by Procyon-b** [comment]
This filter displays the video player immediately:
```
hdfilmcehennem.live###content .filmicerik[style*="display: none"]:style(display: block !important;)
```

**Comment by MasterKia** [comment]
> ||hdfilmcehennem.live/reklams/

> ||example.com/script/

@mapx- Are `||example.com/script/^` or `||example.com/script^` useless or are they more effective?
I assume to maximize the effectiveness, `^$all` should be used but what effect does `^` have?

I couldn't find any info [here](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax), other than that all hostnames from HOSTS file (`example.com`) are equivalent to `||example.com^` in uBO's point of view.

**Comment by mapx-** [comment]
`^` is useless

read `Marking separator characters` here: `https://help.eyeo.com/en/adblockplus/how-to-write-filters`

**Comment by MasterKia** [comment]
> `^` is useless

Then why uBO views `example.com` as `||example.com^` and not `||example.com`?





> read `Marking separator characters` here: `https://help.eyeo.com/en/adblockplus/how-to-write-filters`

Thanks.
