### ISSUE TITLE
faz.net: breakage

### ISSUE THREAD

**Issue by hollowyears** [uBlockOrigin/uAssets#13737]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.faz.net/aktuell/fotografie/supermond-beeindruckende-aufnahmen-aus-der-ganzen-welt-18104441.html`

### Category

breakage

### Describe the issue

The image viewer doesn't work, when you click the button to the next image the page just stops working. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 86360
  cosmetic: 28854
  scriptlet: 17222
  html: 681
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 32497-297, 22h.52m
    ublock-badware: 4211-3, 1d.21h.54m
    ublock-privacy: 228-1, 7d.18h.55m
    ublock-abuse: 75-0, 5d.16h.11m
    ublock-unbreak: 1817-0, 1d.9h.36m
    adguard-mobile: 7860-179, 1d.9h.37m
    easylist: 68191-24809, 3d.23h.56m
    easyprivacy: 27216-596, 1d.9h.35m
    urlhaus-1: 7993-0, 10h.32m
    plowe-0: 3638-3, 10d.6h.30m
    DEU-0: 5816-379, 10h.33m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1241 ms (selfie)
  maxAssetCacheWait: 1069 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    faz.net: 2
    adobedtm.com: 1
    cleverpush.com: 3
    demdex.net: 1
    imasdk.googleapis.com: 1
    iocnt.net: 2
    taboola.com: 1
```
</details>

**Comment by ghajini** [comment]
can't reproduce on chrome/firefox desktop browser

on firefox android it's caused by cname block from easyprivacy

`||iocnt.net^$3p`
