### ISSUE TITLE
smarttalksuccess.com: ads

### ISSUE THREAD

**Issue by lottomansosa** [uBlockOrigin/uAssets#13748]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.smarttalksuccess.com/its-imperative-that-women-take-the-field-and-find-success/?ar=1079&template=513&utm_source=ppm&target_id=null&pub_id=null&utm_medium=social&utm_campaign=ppm-smarttalksuccess_sco`

### Category

ads

### Describe the issue

same ads keep popping up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 83001
  cosmetic: 43918
  scriptlet: 17245
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68411-50, 19h.52m
    easyprivacy: 27193-122, 3d.23h.56m
    plowe-0: 3639-781, 7d.16h.33m
    ublock-abuse: 75-0, 7d.16h.35m
    ublock-badware: 4157-91, 19h.55m
    ublock-filters: 31772-97, 19h.54m
    ublock-privacy: 222-2, 7d.16h.34m
    ublock-quick-fixes: 211-2, 23h.57m
    ublock-unbreak: 1800-40, 19h.53m
    urlhaus-1: 8033-0, 23h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 289 ms (selfie)
  maxAssetCacheWait: 135 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    adpushup.com: 1
    connatix.com: 2
    playbuzz.com: 1
```
</details>

**Comment by ghajini** [comment]
Give us the idea where the ads are on tgis page may be through screenshot?

also from which page you landed on this website?
