### ISSUE TITLE
streamingcommunity.press: detection

### ISSUE THREAD

**Issue by SkateIV** [uBlockOrigin/uAssets#13740]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamingcommunity.press/watch/81?e=2215`

### Category

detection

### Describe the issue

website detect ubo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 89142
  cosmetic: 51259
  scriptlet: 17241
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 13081-0, 18m
    easylist: 68191-54, 3d.22h.40m
    easyprivacy: 27193-124, 3d.22h.39m
    plowe-0: 3648-782, 19m
    ublock-abuse: 75-0, 1d.21h.18m
    ublock-badware: 4207-91, 1d.21h.16m
    ublock-filters: 31825-104, 1d.21h.15m
    ublock-privacy: 224-2, 1d.21h.17m
    ublock-quick-fixes: 209-2, 16m
    ublock-unbreak: 1798-40, 3d.22h.38m
    urlhaus-1: 8552-0, 17m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 453 ms (selfie)
  maxAssetCacheWait: 365 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 1
    thaudray.com: 2
    youtube.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Just fixed here #13738
Refresh you filter lists. Open the dashboard, "Filter lists" tab, click "Purge caches" then  "Update now"
