### ISSUE TITLE
dizipal.xyz: ads

### ISSUE THREAD

**Issue by MuhammetEminCakir** [uBlockOrigin/uAssets#13745]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dizipal.xyz/kapilar-izle-doors-2021-turkce-dublaj-full-hd-izle/`

### Category

ads

### Describe the issue

There are ads in this site.
This is my filters:
`##iframe:nth-of-type(2)`
`##.footer-sticky-inner`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1470" alt="Ekran görüntüsü 2022-06-16 212507" src="https://user-images.githubusercontent.com/64583157/174140475-6e204d6c-74a2-4b4d-94d9-ddf81d8b6a1e.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 89058
  cosmetic: 96654
  scriptlet: 20073
  html: 679
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54118-587, 11h.7m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32405-45, 11h.7m
    ublock-badware: 4161-3, 11h.7m
    ublock-privacy: 230-0, 11h.7m
    ublock-abuse: 75-0, 11h.7m
    ublock-unbreak: 1813-0, 11h.7m
    ublock-quick-fixes: 211-2, 11h.7m
    easylist: 68411-623, 11h.7m
    easyprivacy: 27217-584, 11h.7m
    urlhaus-1: 7993-0, 11h.7m
    plowe-0: 3645-3, 11h.7m
    TUR-0: 8257-59, 57m
filterset (user): [empty]
trustedset: 
  removed: 
    opera-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 611 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    allvideometrika.com: 1
    cdnativepush.com: 2
    dotsenhanced.com: 2
    googlesyndication.com: 2
    googletagmanager.com: 4
    inklinkor.com: 4
    inpage-push.com: 1
    offerimage.com: 2
    offfurreton.com: 1
    rtmark.net: 4
    staticmoly.me: 1
    tzegilo.com: 1
    vidmoly.net: 1
    vidmoly.to: 1
    wp.com: 2
    wpadmngr.com: 1
    yandex.ru: 3
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
||chgiymjkqy.com^$domain=dizipal.xyz
dizipal.xyz##body > .footer-sticky
```

**Comment by mapx-** [comment]
@Yuki2718
