### ISSUE TITLE
stopgame.ru: breakage

### ISSUE THREAD

**Issue by ar1394** [uBlockOrigin/uAssets#13752]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stopgame.ru/newsdata/53780/v_rising_poluchila_russkiy_perevod_a_v_tmnt_shredder_s_revenge_ego_dobavyat_pozzhe`

### Category

breakage

### Describe the issue

Ublock deletes links in news. This links aren't ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://dropmefiles.com/N8e4k

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 91
filterset (summary): 
  network: 101703
  cosmetic: 65962
  scriptlet: 18382
  html: 683
listset (total-discarded, last updated): 
  default: 
    user-filters: 76-8, never
    ublock-filters: 32405-32, 17h.42m
    ublock-badware: 4162-3, 17h.41m
    ublock-privacy: 230-0, 3d.1h.43m
    ublock-abuse: 75-0, 3d.1h.42m
    ublock-unbreak: 1813-0, 17h.40m
    easylist: 68416-212, 17h.39m
    easyprivacy: 27220-153, 17h.38m
    urlhaus-1: 8552-0, 13h.37m
    plowe-0: 3639-784, 6d.21h.42m
    RUS-0: 41697-159, 21h.43m
filterset (user): [array of 76 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3733 ms (selfie)
  maxAssetCacheWait: 1133 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    dotterian.ru: 1
    googletagmanager.com: 3
    yadro.ru: 1
    yandex.ru: 2
```
</details>

**Comment by ghajini** [comment]
- Force update all filter lists
- If it still doesn't solve, go to ublock origin logger & post here screenshot of only blocked entries

**Comment by mapx-** [comment]
it was fixed 13 hours ago
https://hg.adblockplus.org/ruadlist/rev/2bbcebabb492
