### ISSUE TITLE
v7player.wostreaming.net breakage

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#13750]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://v7player.wostreaming.net/6497`

### Describe the issue

Stuck on loading screen

### Notes

Console:
```
Uncaught (in promise) TypeError: can't access property "settings", e is null
    imaSetupSdk https://v7player.wostreaming.net/v7player-09fed381.js:2
    setupSdk https://v7player.wostreaming.net/v7player-09fed381.js:2
...
```

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 103
filterset (summary): 
  network: 83616
  cosmetic: 43849
  scriptlet: 17205
  html: 683
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 32432-33, now
    ublock-badware: 4162-3, now
    ublock-privacy: 230-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1815-0, now
    easylist: 68457-570, now
    easyprivacy: 27224-580, now
    urlhaus-1: 8664-0, now
    plowe-0: 3648-3, now
    ublock-quick-fixes: 0-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2006 ms
```
</details>

**Comment by Procyon-b** [comment]
Does this work for you:
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=v7player.wostreaming.net
@@||api.clarity.abacast.com/gateway/getmediavast.php?source=v7player$xhr,domain=imasdk.googleapis.com
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ccb9dde4d6d784ccb5916ad3990df227ab5d3198
