### ISSUE TITLE
file-upload.com: nuisance

### ISSUE THREAD

**Issue by xproflipscarab** [uBlockOrigin/uAssets#13754]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.file-upload.com/u1rfalr7e5q9`

### Category

nuisance

### Describe the issue

Download timers still make you wait 30 seconds 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 87913
  cosmetic: 90598
  scriptlet: 19763
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54134-117, 14h.58m
  default: 
    user-filters: 0-0, never
    easylist: 68450-90, 14h.53m
    easyprivacy: 27220-222, 14h.57m
    plowe-0: 3645-782, 1d.23h.24m
    ublock-abuse: 75-0, 12d.13h.57m
    ublock-badware: 4158-91, 14h.56m
    ublock-filters: 31765-441, 14h.55m
    ublock-privacy: 222-2, 12d.13h.56m
    ublock-quick-fixes: 211-5, 23h.20m
    ublock-unbreak: 1800-44, 14h.54m
    urlhaus-1: 8552-0, 14h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 488 ms (selfie)
  maxAssetCacheWait: 159 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    alexametrics.com: 1
    d26adrx9c3n0mq.cloudfront.net: 2
    facebook.com: 3
    google-analytics.com: 1
    google.com: 2
    protectionabate.com: 1
```
</details>

**Comment by MasterKia** [comment]
@ghajini The site also has popup on click.
`file-upload.*##+js(window.open-defuser)` from uBlock Filters does work but it's better to block `file-upload.site/page.js` and `file-upload.site/page2.js`.

`||file-upload.site/page*.js`

Also for some reason, `window.open-defuser` can't stop the popup on Vivaldi; but works on Chrome.

**Comment by ghajini** [comment]
@MasterKia 
does this work for you 
`file-upload.com##+js(noeval)`

**Comment by MasterKia** [comment]
Yes it works; also no breakages, file downloaded successfully.

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/85da612957d9b7e1bd717310d083bf2a70e36ac0
