### ISSUE TITLE
youtube.com: nuisance - Promoted videos mixed in with search results

### ISSUE THREAD

**Issue by Heralda** [uBlockOrigin/uAssets#13753]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/results?search_query=battlestar+galactica+jump`

### Category

nuisance

### Describe the issue

When making a search on youtube, youtube has sections of other "promoted videos" mixed in with your true positive search hits.

Now, these false positive search hits are divided into sections. First there's a section of true search hits. Then there's a section of 4-20 promoted videos. Then a section of 2-3 more true search hits and so on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/10226418/174259134-349d9ecf-9b2f-4c84-a061-8036c35f724a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 83730
  cosmetic: 43952
  scriptlet: 17231
  html: 684
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32445-32, now
    ublock-badware: 4162-3, now
    ublock-privacy: 230-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1815-0, now
    easylist: 68479-558, now
    easyprivacy: 27226-594, now
    urlhaus-1: 8664-0, now
    plowe-0: 3648-3, now
    ublock-quick-fixes: 212-2, now
filterset (user): [empty]
trustedset: 
  added: [array of 156 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 286 ms (selfie)
  maxAssetCacheWait: 460 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    youtube.com: 6
    doubleclick.net: 2
    google.com: 2
    google.se: 1
```
</details>

**Comment by MasterKia** [comment]
@Heralda Add these to "My filters" and see if it satisfies your needs:
```
youtube.com##ytd-shelf-renderer:has-text(People also watched)
youtube.com##ytd-shelf-renderer:has-text(For you)
```

**Comment by zeref-dragneel** [comment]
```
youtube.com##ytd-shelf-renderer.ytd-item-section-renderer.style-scope:nth-of-type(1)
youtube.com##ytd-shelf-renderer.ytd-item-section-renderer.style-scope:nth-of-type(2)
```
