### ISSUE TITLE
forex-gold.net: breakage

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#13757]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forex-gold.net/can-forex-bankrupt-an-individual/`

### Category

breakage

### Describe the issue

This website doesn't show captcha when uBlock is active.
This is the link to the page I reported on:
```
https://mobi2c.com/iphone-13-phone-review/
https://newforex.online/what-is-repainting-indicators-in-forex-part-1/
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 87883
  cosmetic: 48683
  scriptlet: 17264
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    IDN-0: 8931-0, 1h.9m
    easylist: 68479-54, 1h.8m
    easyprivacy: 27226-124, 1h.6m
    plowe-0: 3648-782, 1h.13m
    ublock-abuse: 75-0, 1h.12m
    ublock-badware: 4157-91, 1h.5m
    ublock-filters: 31806-133, 1h.4m
    ublock-privacy: 224-2, 1h.11m
    ublock-quick-fixes: 212-2, 1h.1m
    ublock-unbreak: 1802-41, 1h.3m
    urlhaus-1: 8664-0, 1h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 528 ms (selfie)
  maxAssetCacheWait: 358 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    demand.supply: 2
    doubleverify.com: 3
    googlesyndication.com: 5
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Provide all the steps to reproduce the breakage.

**Comment by yohanes4dip** [comment]
First I visited this link: https://mobi2c.com/iphone-13-phone-review/ and I was thrown to this link: https://newforex.online/what-is-repainting-indicators-in-forex-part-1/.

After the second link I was thrown to the link I reported, which doesn't display a timer/captcha when uBlock is active. If I turn off uBlock, the timer/captcha appears.

**Comment by mapx-** [comment]
You still don't provide the real download link.

**Comment by orariley70** [comment]
@yohanes4dip You need to disable "Privacy Badger" addon to able to pass the anti-adblock check, built-in lists and external lists are not the issue.
mobi2c.com and world-trips.net will require the same workaround.
@mapx- example would be http://ultimate.turkdown.com/link.php?link=aHR0cHM6Ly9mYy1sYy5jb20vdDFreWlxd3I=
