### ISSUE TITLE
freeshib.biz: detection

### ISSUE THREAD

**Issue by raperov** [uBlockOrigin/uAssets#13755]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freeshib.biz/dashboard`

### Category

detection

### Describe the issue

Ad Blocker Detected, script failed to load after 353.00ms, Disable it or you will see this forever.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![shib](https://user-images.githubusercontent.com/107613909/174278032-2ccb8f13-ebaa-4c6c-ae65-ed443597ae75.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 101912
  cosmetic: 65960
  scriptlet: 18449
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2617-0, never
    RUS-0: 41710-8, 3h.2m
    easylist: 68263-74, 2d.21h.48m
    easyprivacy: 27213-221, 2d.21h.52m
    plowe-0: 3644-786, 3d.5h.6m
    ublock-abuse: 75-1, 8d.4h.31m
    ublock-badware: 4207-91, 2d.21h.51m
    ublock-filters: 31831-2708, 2d.21h.50m
    ublock-privacy: 222-2, 8d.4h.30m
    ublock-quick-fixes: 212-3, 3h.1m
    ublock-unbreak: 1799-40, 2d.21h.49m
    urlhaus-1: 8664-0, 3h
filterset (user): [array of 1855 redacted]
trustedset: 
  added: [array of 16 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1700 ms
  maxAssetCacheWait: 838 ms
popupPanel: 
  blocked: 7
  no-scripting: true
  blockedDetails: 
    freeshib.biz: 1
    cointraffic.io: 2
    coinzillatag.com: 4
```
</details>

**Comment by mapx-** [comment]
I guess an account is required.
However if it's as your precedent report you should test & report back:

`freeshib.biz##+js(acs, document.createElement, onerror)`

**Comment by raperov** [comment]
> and ... ? test that filter

It works, thanks!!!
