### ISSUE TITLE
submityourflicks.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1375]
URL(s) where the issue occurs

`https://www.submityourflicks.com/1966997-adara-bears-it-beautifully-getting-naked-on-camera-taking-the-cock-of-her-boyfriend-deeply.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ads @mapx-

**Comment by mapx-** [comment]
screenshot ?

**Comment by KiLL4FuNK** [comment]
`https://i.imgur.com/xtxccxk.png`

**Comment by mapx-** [comment]
still nothing, try updating all your lists
