### ISSUE TITLE
animego.online: breakage

### ISSUE THREAD

**Issue by GreamDesu** [uBlockOrigin/uAssets#13759]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animego.online/`

### Category

breakage

### Describe the issue

The website freezes when trying to load it with uBlock turned on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 101958
  cosmetic: 66012
  scriptlet: 18454
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 14h.48m
  default: 
    RUS-0: 41710-8, 15h.4m
    easylist: 68465-64, 15h.2m
    easyprivacy: 27225-221, 14h.56m
    plowe-0: 3648-787, 15h.13m
    ublock-abuse: 75-1, 15h.11m
    ublock-badware: 4158-91, 15h
    ublock-filters: 31798-134, 14h.58m
    ublock-privacy: 224-2, 15h.9m
    ublock-quick-fixes: 209-2, 14h.50m
    ublock-unbreak: 1802-40, 14h.54m
    urlhaus-1: 8664-0, 14h.52m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 45 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  selfieAfter: 3
supportStats: 
  allReadyAfter: 418 ms (selfie)
  maxAssetCacheWait: 282 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
Try disabling any other extension & test again

**Comment by dimisa-RUAdList** [comment]
@mapx- 
Broken player and comments: `~animego.org,animego.*##+js(set, String.prototype.charAt, noopFunc)`
Example: `https://animego.online/229-zachem-vy-zdes-uchitel.html`

**Comment by mapx-** [comment]
The player was ok on my end, however I removed it
