### ISSUE TITLE
mail.yahoo.com: breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#13764]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yahoo.com/d/folders/1`

### Category

breakage

### Describe the issue

The ad banner on the top of mail list leaves a big blank space when uBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 197762
  cosmetic: 225126
  scriptlet: 36761
  html: 686
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 867-6, 2h.51m
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-14, 2h.55m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 43841-2263, 1d.6h.25m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-0, 2h.58m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 12-0, 4d.1h.10m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-1962, 4d.22h.47m
    https://www.i-dont-care-about-cookies.eu/abp/: 25025-4, 1d.6h.26m
    adguard-generic: 64860-5449, 1d.6h.35m
    adguard-mobile: 7862-203, 1d.6h.34m
    adguard-spyware: 26152-1050, 1d.6h.32m
    adguard-annoyance: 54148-5159, 1d.6h.30m
    adguard-social: 17672-1114, 1d.6h.29m
    fanboy-thirdparty_social: 68-0, 4d.22h.51m
    fanboy-annoyance: 73242-57776, 4d.22h.50m
    fanboy-cookiemonster: 34263-8987, 4d.22h.49m
    fanboy-social: 23266-51, 1d.6h.28m
    ublock-annoyances: 4464-8, 2h.57m
    dpollock-0: 10375-491, 3d.4h.4m
    adguard-spyware-url: 633-15, 1d.6h.27m
    block-lan: 43-0, 14d.23h.59m
    [2 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 32405-191, 2d.2h.30m
    ublock-badware: 4161-3, 1d.6h.37m
    ublock-privacy: 230-0, 1d.6h.40m
    ublock-abuse: 75-4, 1d.6h.39m
    ublock-unbreak: 1813-1, 1d.6h.36m
    easylist: 68475-3475, 1d.6h.33m
    easyprivacy: 27226-10858, 1d.6h.31m
    urlhaus-1: 9213-0, 2h.54m
    plowe-0: 3648-5, 1d.6h.38m
    GRC-0: 1002-1, 2h.56m
    ublock-quick-fixes: 197-2, 2h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12459 ms (selfie)
  maxAssetCacheWait: 2074 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    yahoo.com: 12
    oath.com: 1
    yimg.com: 3
```
</details>

**Comment by ghajini** [comment]
Reset to default settings with updated filters & then check

**Comment by MasterKia** [comment]
@mapx- 
Should `https://easylist-msie.adblockplus.org/antiadblockfilters.txt` be added to badlists?

There is `https://easylist-msie.adblockplus.org/abp-filters-anti-cv.txt` in the [badlists](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt#L8) file.

**Comment by DimitrisKalaboukas** [comment]
The gap is still there, but I was able to shorten it by the following filter:

mail.yahoo.com##.I_ZkbNhI.m_Z14vXdP.p_R.P_2bJhi.en_0.H_7bcz.ek_EZ.D_F.k_w.ab_C

**Comment by Procyon-b** [comment]
> mail.yahoo.com##.I_ZkbNhI.m_Z14vXdP.p_R.P_2bJhi.en_0.H_7bcz.ek_EZ.D_F.k_w.ab_C

For me this selects the div with the mail grid header. It contains the "select all" checkbox, the "Archive" "Move" "Delete" "Span" "..." buttons as well as the "sort" submenu. Don't you see these items?

**Comment by DimitrisKalaboukas** [comment]
You are right! This filter really breaks the top toolbar.

**Comment by Procyon-b** [comment]
is the gap above or below this toolbar?

**Comment by DimitrisKalaboukas** [comment]
Between the toolbar and the first message, i.e. below it.

**Comment by Procyon-b** [comment]
Does it have the height of a message line?
I see one for 30s, then it disappears. (the html tag of the line is removed by a process of the page)

**Comment by DimitrisKalaboukas** [comment]
In my browser it has the height of approximately 3 message lines.
It really disappears if you stay patient for half a minute!

**Comment by Procyon-b** [comment]
Can you try this filter? It should reduce the waiting time to less than a second once the page has finished loading.
```
mail.yahoo.com##+js(nano-stb, native, 20000, 0.01)
```

**Comment by DimitrisKalaboukas** [comment]
It doesn't make any difference.

**Comment by Procyon-b** [comment]
Does anyone know how yahoo-mail works in FF without settimeouts? (nothing displayed for me with `+js(nostif)`)
