### ISSUE TITLE
filescan.io: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#13767]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.filescan.io/scan`

### Category

nuisance

### Describe the issue

Cookie warning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-06-18 at 15-04-03 FileScan IO - Next-Gen Malware Analysis Platform](https://user-images.githubusercontent.com/101707608/174438614-4dd5e332-09cd-4e37-b1c7-651558c3ebc6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 197762
  cosmetic: 225126
  scriptlet: 36761
  html: 686
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 867-6, 4h
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-14, 4h.4m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 43841-2263, 1d.7h.35m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-0, 4h.8m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 12-0, 4d.2h.20m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-1962, 4d.23h.57m
    https://www.i-dont-care-about-cookies.eu/abp/: 25025-4, 1d.7h.36m
    adguard-generic: 64860-5449, 1d.7h.45m
    adguard-mobile: 7862-203, 1d.7h.44m
    adguard-spyware: 26152-1050, 1d.7h.42m
    adguard-annoyance: 54148-5159, 1d.7h.40m
    adguard-social: 17672-1114, 1d.7h.39m
    fanboy-thirdparty_social: 68-0, 5d.1m
    fanboy-annoyance: 73242-57776, 5d
    fanboy-cookiemonster: 34263-8987, 4d.23h.59m
    fanboy-social: 23266-51, 1d.7h.38m
    ublock-annoyances: 4464-8, 4h.6m
    dpollock-0: 10375-491, 3d.5h.14m
    adguard-spyware-url: 633-15, 1d.7h.37m
    block-lan: 43-0, 15d.1h.9m
    [2 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 32405-191, 2d.3h.40m
    ublock-badware: 4161-3, 1d.7h.47m
    ublock-privacy: 230-0, 1d.7h.50m
    ublock-abuse: 75-4, 1d.7h.49m
    ublock-unbreak: 1813-1, 1d.7h.46m
    easylist: 68475-3475, 1d.7h.43m
    easyprivacy: 27226-10858, 1d.7h.41m
    urlhaus-1: 9213-0, 4h.3m
    plowe-0: 3648-5, 1d.7h.48m
    GRC-0: 1002-1, 4h.5m
    ublock-quick-fixes: 197-2, 3h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1143 ms (selfie)
  maxAssetCacheWait: 634 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    yahoo.com: 3
    yimg.com: 1
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)

https://github.com/uBlockOrigin/uAssets#gdpr:
"GDPR modals will not be addressed in uAssets"

Enable "EasyList Cookie" from the Annoyances list in uBO settings, then report to https://github.com/easylist/easylist/issues.

**Comment by MasterKia** [comment]
@DimitrisKalaboukas 
For your personal use, add `filescan.io##.cookie` to "_My filters_" in uBO settings.
