### ISSUE TITLE
listen.tidal.com: breakage

### ISSUE THREAD

**Issue by Gl-b** [uBlockOrigin/uAssets#13769]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://listen.tidal.com/`

### Category

breakage

### Describe the issue

After reloading of the page, it gradually becomes almost impossible to use: buttons stop to react, pages don't open.

Another issue: there is still one specific ad that still appears from time to time, the ad about lyrics feature.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85096
  cosmetic: 43990
  scriptlet: 17275
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68524-50, 23m
    easyprivacy: 27234-122, 22m
    plowe-0: 3647-783, 20m
    ublock-abuse: 75-0, 18m
    ublock-badware: 4172-91, 16m
    ublock-filters: 31820-102, 15m
    ublock-privacy: 224-2, 14m
    ublock-quick-fixes: 211-2, 13m
    ublock-unbreak: 1802-40, 12m
    urlhaus-1: 10009-0, 11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1017 ms
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 3422
  blockedDetails: 
    tidal.com: 3414
    firebaselogging-pa.googleapis.com: 3
    googletagmanager.com: 2
    trackjs.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Breakage is fixed but I'm afraid the ad cannot be removed.

**Comment by Gl-b** [comment]
It seems that breakage is here again
