### ISSUE TITLE
ophim.pro: ads

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13766]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ophim.pro/ke-noi-gian-insider`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 84975
  cosmetic: 20574
  scriptlet: 17337
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1763-31, 1m
    easylist: 68521-24204, 4h.30m
    easyprivacy: 27231-127, 4h.30m
    plowe-0: 3647-783, 4h.30m
    ublock-abuse: 75-0, 4h.30m
    ublock-badware: 4170-91, 4h.30m
    ublock-filters: 31821-345, 4h.30m
    ublock-privacy: 224-3, 4h.30m
    ublock-quick-fixes: 211-2, 4h.30m
    ublock-unbreak: 1802-40, 4h.30m
    urlhaus-1: 9213-0, 4h.30m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 719 ms (selfie)
  maxAssetCacheWait: 323 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    belickitungchan.com: 1
    facebook.com: 4
    googletagmanager.com: 1
    phimfullhd.herokuapp.com: 1
    trackpush.com: 4
```
</details>

**Comment by ghajini** [comment]
```
||viranet.work^
ophim.pro##.adsContainer
```

**Comment by stephenhawk8054** [comment]
@hoang-rio Can you check this?
