### ISSUE TITLE
[nsfw] luscious.net: detection

### ISSUE THREAD

**Issue by Clemdawgg** [uBlockOrigin/uAssets#13760]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.luscious.net/adblock/`

### Category

detection

### Describe the issue

redirect to AdBlocker detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![detected](https://user-images.githubusercontent.com/107717714/174389944-282af231-0992-4f41-8487-27400d24ecb1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 83537
  cosmetic: 43924
  scriptlet: 17208
  html: 679
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 16m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 8-0, never
    ublock-filters: 32403-35, 1d.20h.2m
    ublock-badware: 4161-3, 1d.20h.1m
    ublock-privacy: 228-0, 8d.15h.57m
    ublock-abuse: 75-0, 8d.15h.58m
    ublock-unbreak: 1813-30, 1d.20h
    easylist: 68394-567, 1d.19h.59m
    easyprivacy: 27216-101, 1d.19h.58m
    plowe-0: 3639-450, 8d.15h.55m
    urlhaus-1: 8552-0, 18h.47m
    ublock-quick-fixes: 211-0, 18h.48m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  prefetchingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 219 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by noonien** [comment]
Still detected

**Comment by stephenhawk8054** [comment]
Anyone has better solutions except

`@@||js.wpadmngr.com/static/adManager.js$xhr,domain=luscious.net`

?

**Comment by mapx-** [comment]
now it's an annoyance, maybe:

```
luscious.net###modal-root
luscious.net##body:style(overflow: auto !important;)
```

**Comment by stephenhawk8054** [comment]
> now it's an annoyance, maybe:

Yeah I thought about it too, but then realized the title on the tab is changed to `Adblock Detected`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/177259514-87d00294-84f1-418e-8079-85b3e6c57e96.png)

</details>

**Comment by mapx-** [comment]
on redirect-rule I get (due to await ?!)
`Failed to load resource: net::ERR_UNSAFE_REDIRECT`

**Comment by mapx-** [comment]
`luscious.net##+js(set, Promise, trueFunc)`

breaking expanding stuff on page
`https://www.luscious.net/albums/happy-4th-of-july_464086/`
