### ISSUE TITLE
last.fm: breakage

### ISSUE THREAD

**Issue by Shpigorx** [uBlockOrigin/uAssets#13768]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.last.fm/user/Shpigor/library?date_preset=LAST_7_DAYS`

### Category

breakage

### Describe the issue

Select period button at the right not working properly. It should open variants. After reload page you can select period 1 time. After this button becomes irresponsible and you need to reload page again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/12695405/174438660-67e45121-d413-4343-a611-4ee9a1b94ebb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 102403
  cosmetic: 65982
  scriptlet: 18438
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41703-8, 1d.21h.4m
    easylist: 68384-64, 2d.23h.33m
    easyprivacy: 27213-221, 3d.20h.14m
    plowe-0: 3639-786, 8d.20h.6m
    ublock-abuse: 75-1, 12d.16h.26m
    ublock-badware: 4207-91, 2d.23h.34m
    ublock-filters: 31768-129, 2d.19h.29m
    ublock-privacy: 222-2, 12d.16h.27m
    ublock-quick-fixes: 211-2, 17h.18m
    ublock-unbreak: 1799-40, 2d.23h.35m
    urlhaus-1: 9148-0, 17h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 280 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    last.fm: 1
    doubleclick.net: 1
    moatads.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`@@||last.fm/static/js-build/tracking/tealium-utag-set.js$script,1p`
@ryanbr
