### ISSUE TITLE
tangasmix.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1376]
URL(s) where the issue occurs

`http://www.tangasmix.com/fotoc-1327819.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.22

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
add
`||tangasmix.com^$script,subdocument`
