### ISSUE TITLE
price.com.hk anti-ads block detector

### ISSUE THREAD

**Issue by sum2012** [uBlockOrigin/uAssets#13770]
### Prerequisites

- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.price.com.hk`

### Describe the issue

Click few sub menu.pop up anti-ads block detector

### Screenshot(s)

![1](https://user-images.githubusercontent.com/2177532/174460076-5cd2dc72-0bb5-4cce-a004-d0614ceb6db5.png)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome  v102.0.5005.115 64 bit

### Settings

None

**Comment by Procyon-b** [comment]
Try this:
```
||aaxwall.com^$script,domain=price.com.hk
```

**Comment by sum2012** [comment]
Thanks,it works

**Comment by hr8473** [comment]
The site is still intermittently showing the anti-block screen.

https://www.price.com.hk/product.php?p=486572

5 out of 10 times I will get this screen. Not sure what is causing this issue. 

![image](https://user-images.githubusercontent.com/105545048/179359912-7e5024b7-e126-4b44-b676-17f4b3daee14.png)
