### ISSUE TITLE
eu.tamrieltradecentre.com: breakage

### ISSUE THREAD

**Issue by RedSkull-666** [uBlockOrigin/uAssets#13777]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=crafting+motif+18`

### Category

breakage

### Describe the issue

Error message: "Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 176650
  cosmetic: 215538
  scriptlet: 36790
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54184-138, 8m
    adguard-generic: 64904-1145, 8m
    adguard-mobile: 7865-52, 8m
    adguard-social: 17645-865, 8m
    adguard-spyware: 26159-878, 8m
    adguard-spyware-url: 634-13, 8m
    block-lan: 43-0, 8m
    curben-phishing: 17435-0, 8m
    curben-pup: 229-0, 8m
    dpollock-0: 10375-270, 8m
    fanboy-annoyance: 73692-4211, 7m
    fanboy-cookiemonster: 34674-34674, 7m
    fanboy-social: 23261-23261, 7m
    fanboy-thirdparty_social: 69-21, 7m
    ublock-annoyances: 4467-223, 7m
  default: 
    user-filters: 0-0, never
    FRA-0: 28853-24, 8m
    easylist: 68572-1251, 8m
    easyprivacy: 27236-10546, 7m
    plowe-0: 3647-1314, 7m
    ublock-abuse: 75-1, 7m
    ublock-badware: 4185-328, 7m
    ublock-filters: 31830-3823, 7m
    ublock-privacy: 224-49, 7m
    ublock-quick-fixes: 211-15, 7m
    ublock-unbreak: 1807-100, 7m
    urlhaus-1: 10167-1, 7m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 988 ms (selfie)
  maxAssetCacheWait: 1010 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    tamrieltradecentre.com: 3
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    google.com: 1
    google.fr: 1
    googleadservices.com: 1
    googlesyndication.com: 2
    paypalobjects.com: 2
    twitter.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Caused by `/\/Content\/images\/[a-z]+\/[a-z]+\d\.(?:gif|jpeg)/$image,~third-party,domain=tamrieltradecentre.com` in Adguard Base @Yuki2718
