### ISSUE TITLE
suchen.mobile.de: [unknown]

### ISSUE THREAD

**Issue by HKEB** [uBlockOrigin/uAssets#13779]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://suchen.mobile.de/fahrzeuge/search.html?dam=0&isSearchRequest=true&ms=17200%3B%3B%3B&ref=quickSearch&sb=rel&vc=Car`

### Category

[unknown]

### Describe the issue

Search results not shown until UBO is disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 87421
  cosmetic: 47681
  scriptlet: 17275
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.2h.13m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 1-0, never
    DEU-0: 5838-0, 3h.38m
    easylist: 68572-56, 3h.41m
    easyprivacy: 27236-132, 3h.40m
    plowe-0: 3647-784, 3h.45m
    ublock-abuse: 75-0, 3h.47m
    ublock-badware: 4172-91, 3h.44m
    ublock-filters: 31818-117, 3h.43m
    ublock-privacy: 224-3, 3h.48m
    ublock-quick-fixes: 211-2, 3h.37m
    ublock-unbreak: 1807-41, 3h.42m
    urlhaus-1: 10167-0, 3h.39m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 69 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1607 ms (selfie)
  maxAssetCacheWait: 433 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    adnxs.com: 1
    adsafeprotected.com: 1
    amazon-adsystem.com: 3
    casalemedia.com: 1
    classistatic.de: 1
    criteo.com: 2
    criteo.net: 3
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    google.com: 1
    googletagmanager.com: 1
    indexww.com: 1
    ioam.de: 1
    openx.net: 2
    optimizely.com: 2
    pubmatic.com: 1
    rubiconproject.com: 6
    speedcurve.com: 1
    theadex.com: 1
    xplosion.de: 1
    yieldlab.net: 2
```
</details>

**Comment by mapx-** [comment]
add

`mobile.de#@#[data-ad-id]`

@ryanbr

**Comment by Procyon-b** [comment]
Try this:
```
@@||suchen.mobile.de^$ghide
```
