### ISSUE TITLE
tv.vevo.com

### ISSUE THREAD

**Issue by 89z** [uBlockOrigin/uAssets#13771]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tv.vevo.com/watch/artist/janet-jackson/US0450100550`

### Describe the issue

Unless you have uBlock Origin totally disabled, the video wont play, and eventually youll see this:

Sorry! We're unable to play this content.
Skip to Next Song

### uBlock Origin version

!

### Browser name and version

!

### Settings

!

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by 89z** [comment]
US

**Comment by stephenhawk8054** [comment]
Can you check if this filter works?

`@@||v.fwmrm.net/ad/g/$script,domain=tv.vevo.com`

**Comment by 89z** [comment]
I dont think it worked :(

**Comment by ghajini** [comment]
it works

**Comment by 89z** [comment]
It did not work

**Comment by stephenhawk8054** [comment]
Can you open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger), choose `Block` and `Allow` in its search bar, reload the page by `Ctrl + F5` and screenshot the logger?

**Comment by 89z** [comment]
OK I tried it again. For some reason the audio works, but not the video

**Comment by 89z** [comment]
OK now the video and audio seem to work. Sorry I don't know what the hell is going on with that site. I guess that filter works now. Thanks

**Comment by stephenhawk8054** [comment]
@ryanbr
