### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by ThibeOnFire** [uBlockOrigin/uAssets#13774]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/search/idgaf`

### Category

ads

### Describe the issue

sometimes I'm listening to music and suddenly there's an ad, the weird thing is it doesn't play but just is there and doesn't go away. Pls fix this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85600
  cosmetic: 45366
  scriptlet: 17256
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2307-11, 16h.9m
    easylist: 68385-54, 3d.18h.44m
    easyprivacy: 27216-123, 3d.10h.44m
    plowe-0: 3645-781, 3d.18h.46m
    ublock-abuse: 75-0, 11h.56m
    ublock-badware: 4170-91, 1d.33m
    ublock-filters: 31812-144, 1d.25m
    ublock-privacy: 224-2, 3d.18h.45m
    ublock-unbreak: 1802-54, 1d.24m
    urlhaus-1: 10009-0, 20h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 511 ms (selfie)
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 22
  no-large-media: true
  no-popups: true
  blockedDetails: 
    akamaized.net: 1
    doubleclick.net: 3
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 16
```
</details>

**Comment by mapx-** [comment]
> sometimes 

If we don't have an accurate way to reproduce an issue, there's not much we can do.
