### ISSUE TITLE
pacsun.com: breakage

### ISSUE THREAD

**Issue by manzoman96** [uBlockOrigin/uAssets#13776]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pacsun.com/`

### Category

breakage

### Describe the issue

Website stops allowing access after navigating through a few links, then is inaccessible after.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/107805183/174488779-ab76a6c2-8cf6-45a9-ab3b-34debd086f64.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 85086
  cosmetic: 43983
  scriptlet: 17239
  html: 685
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.13h.26m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32459-35, 1d.13h.31m
    ublock-badware: 4174-3, 1d.13h.32m
    ublock-privacy: 228-0, 9d.15h.38m
    ublock-abuse: 75-0, 9d.3h.36m
    ublock-unbreak: 1815-0, 1d.13h.29m
    easylist: 68517-571, 1d.13h.33m
    easyprivacy: 27230-579, 1d.13h.30m
    urlhaus-1: 9997-0, 3h
    plowe-0: 3644-3, 5d.3h.4m
    ublock-quick-fixes: 212-0, 2h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 337 ms (selfie)
  maxAssetCacheWait: 238 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Are you sure your access denied message is caused by `uBO`?

**Comment by Procyon-b** [comment]
It's caused by a cookie. If you delete that specific cookie, the server accepts the connection.
The cookie info from an (cookie) extension, is:
```
Domain	.pacsun.com
Name	ak_bmsc
Value	[removed]
Host Only	false
Path	/
Secure	false
HTTP Only	true
Session	false
Expiration Date	6/19/2022 20:18:52
Store Id	0
```

`pacsun.com##+js(cookie-remover, ak_bmsc)` won't work

**Comment by manzoman96** [comment]
That worked! Thank you
