### ISSUE TITLE
Outlook.com ads

### ISSUE THREAD

**Issue by arthurduino** [uBlockOrigin/uAssets#13787]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://outlook.live.com/mail/0/`

### Describe the issue

ads in the page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/82079353/174642558-6fc44a89-2316-4beb-b050-43970dc0f469.png)

### uBlock Origin version

uBlock Origin 1.43.0

### Browser name and version

Google Chrome

### Settings

nothing

**Comment by Zaharos** [comment]
Are using any other ad blocker?
