### ISSUE TITLE
allmusic.com: detection

### ISSUE THREAD

**Issue by jddtt01** [uBlockOrigin/uAssets#13783]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.allmusic.com/`

### Category

detection

### Describe the issue

pop up on page  adblock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot ](https://user-images.githubusercontent.com/107857960/174598948-74092eca-349e-429f-8a62-80af140bbc84.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 101837
  cosmetic: 75358
  scriptlet: 19191
  html: 684
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 26154-948, 2d.21h.42m
    adguard-spyware-url: 633-14, 2d.21h.41m
    fanboy-cookiemonster: 34263-88, 6d.22h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32442-32, 2d.21h.46m
    ublock-badware: 4162-3, 2d.21h.45m
    ublock-privacy: 230-0, 6d.22h.24m
    ublock-abuse: 75-0, 6d.22h.24m
    ublock-unbreak: 1815-11, 2d.21h.44m
    ublock-quick-fixes: 211-2, 23h.48m
    easylist: 68479-207, 2d.21h.43m
    easyprivacy: 27226-10443, 2d.21h.40m
    urlhaus-1: 9997-0, 23h.47m
    plowe-0: 3644-344, 6d.22h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6944 ms (selfie)
  maxAssetCacheWait: 1105 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    allmusic.com: 1
    doubleverify.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by Procyon-b** [comment]
@mapx- I can reproduce.
@jddtt01 Try this filter:
```
allmusic.com##+js(no-xhr-if, googlesyndication.com)
```

**Comment by mapx-** [comment]
it's already fixed as annoyance in `uBlock filters – Annoyances`

**Comment by Procyon-b** [comment]
@mapx- oh, sorry. Missed that. I usually test with and without the annoyance list when it's a detection issue. But forgot to reenable it this time.
