### ISSUE TITLE
fr.surveymonkey.com: breakage

### ISSUE THREAD

**Issue by FLavictoire** [uBlockOrigin/uAssets#13785]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fr.surveymonkey.com/collect/list?sm=_2FIIBkX9ycXwX8oLM2rfSe611v3nYsYao9FP5p1SgW3Q_3D`

### Category

breakage

### Describe the issue

Unable to open/close a survey link on SurveyMonkey while uBlock extention is on (browser: Chrome).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_ROD6QCKh0B](https://user-images.githubusercontent.com/107873773/174637546-e3693639-7986-4854-a4e1-036eddd789e7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 104001
  cosmetic: 53087
  scriptlet: 17331
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 28853-24, 2h.6m
    easylist: 68593-80, 2h.8m
    easyprivacy: 27240-439, 2h.5m
    plowe-0: 3647-790, 2h.10m
    ublock-abuse: 75-1, 2h.13m
    ublock-badware: 4180-102, 2h.9m
    ublock-filters: 31812-246, 2d.23h.35m
    ublock-privacy: 224-3, 2h.12m
    ublock-quick-fixes: 201-2, 2h.3m
    ublock-unbreak: 1810-40, 2h.7m
    urlhaus-1: 9732-0, 2h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 804 ms (selfie)
  maxAssetCacheWait: 369 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    amplitude.com: 1
    googletagmanager.com: 1
    nr-data.net: 1
    signalfx.com: 2
    ywxi.net: 1
```
</details>

**Comment by mapx-** [comment]
How to reproduce your issue ?

![image](https://user-images.githubusercontent.com/10303732/174987318-9cbf98b4-0e75-4ff7-b07b-60e32a97d54d.png)

**Comment by FLavictoire** [comment]
I just realized that you need an account with SurveyMonkey to be able to see this page. Also, it looks like SurveyMonkey did an update that repare this problem while using uBlock. I will close this issus.
