### ISSUE TITLE
goodreads.com: breakage

### ISSUE THREAD

**Issue by dwsmpsn** [uBlockOrigin/uAssets#13784]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goodreads.com/?ref=nav_hom`

### Category

breakage

### Describe the issue

Links often don't work ('like' buttons, hitting send). Buttons will work to open elements on the page such as updating book progress, but then when clicking 'send' the site will error out and do nothing. Clicking like bring up a popup full of javascript and html in text.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 85213
  cosmetic: 43933
  scriptlet: 17225
  html: 684
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32433-34, 3d.14h.52m
    ublock-badware: 4162-3, 3d.14h.51m
    ublock-privacy: 230-0, 2d.6h.45m
    ublock-abuse: 75-0, 2d.6h.44m
    ublock-unbreak: 1813-0, 3d.14h.50m
    easylist: 68457-558, 3d.14h.49m
    easyprivacy: 27224-592, 3d.14h.48m
    plowe-0: 3639-3, 11d.11h.1m
    urlhaus-1: 10167-0, 18h.39m
    ublock-quick-fixes: 212-0, 18h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4028 ms (selfie)
  maxAssetCacheWait: 236 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    amazon-adsystem.com: 1
    amazon.com: 2
    doubleclick.net: 1
```
</details>

**Comment by ghajini** [comment]
> Links often don't work ('like' buttons, hitting send). Buttons will work to open elements on the page such as updating book progress, but then when clicking 'send' the site will error out and do nothing. Clicking like bring up a popup full of javascript and html in text.

would you describe this part with screenshots
