### ISSUE TITLE
[nsfw] xhamster.com: ads

### ISSUE THREAD

**Issue by phob** [uBlockOrigin/uAssets#13780]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xhamster.com/videos/peppermint-pmv-fylgja-xhv5L7q`

### Category

ads

### Describe the issue

Advertising occasionally. Tested in incognito mode.
In the cookie popup I unchecked all necessary checkboxes.
At first time no ads were shown no matter how many times I clicked through the videos. 5 minutes tested again and ads came up immediately. Only uBlock is allowed in incognito mode. Internal blocker is disabled.

Tested with Vivaldi 5.3.2679.58 (Stable channel) (64-bit)

I know FF hasn't the issue. I'm not switching to FF.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/Hpf30ZB

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 86663
  cosmetic: 69773
  scriptlet: 18503
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 710-0, 18h.9m
    https://raw.githubusercontent.com/Rudloff/adblock-imokwithcookies/master/filters.txt: 233-0, 2d.21h.20m
    https://raw.githubusercontent.com/acnapyx/paywall-remover/master/paywall-remover-list.txt: 40-0, 2d.21h.30m
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1873-19, 2d.21h.30m
    https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt: 1260-12, 18h.12m
    https://www.i-dont-care-about-cookies.eu/abp/: 25025-374, 2d.21h.30m
  default: 
    user-filters: 0-0, never
    easylist: 68457-65, 2d.21h.30m
    easyprivacy: 27224-129, 2d.21h.30m
    plowe-0: 3648-782, 2d.21h.30m
    ublock-abuse: 75-0, 2d.21h.30m
    ublock-badware: 4158-91, 2d.21h.30m
    ublock-filters: 31797-110, 2d.21h.30m
    ublock-privacy: 224-3, 2d.21h.30m
    ublock-quick-fixes: 211-2, 18h.11m
    ublock-unbreak: 1802-40, 2d.21h.30m
    urlhaus-1: 9997-0, 18h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 384 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    xhamster.com: 4
    faphouse.com: 1
    googletagmanager.com: 1
    tsyndicate.com: 2
```
</details>

**Comment by mapx-** [comment]
Did you test the site using only the default settings / lists ?
Did you disable vivaldi blocker ?

**Comment by okiehsch** [comment]
He provided a screenshot and mentioned that he disabled the internal blocker, looks like the typical video ads on such sites.

I can't reproduce.

**Comment by mapx-** [comment]
I was able now to get the video ads

**Comment by mapx-** [comment]
@phob 
test this filter

`||go.xhamster.com/api/models/vast*Preroll$xhr,1p`

**Comment by phob** [comment]
That did it, thank you very much.

**Comment by okiehsch** [comment]
>  I thought the checkboxes were verification enough that I did all that.

Sadly most users just check the boxes without really following the mentioned steps.
