### ISSUE TITLE
leeuwerik.nl: breakage

### ISSUE THREAD

**Issue by PdM-NL** [uBlockOrigin/uAssets#13782]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.leeuwerik.nl/customer/account/login/referer/aHR0cHM6Ly93d3cubGVldXdlcmlrLm5sL2N1c3RvbWVyL2FjY291bnQvaW5kZXgv/`

### Category

breakage

### Describe the issue

after filling in the login data, the website does not continue.
It keeps showing a "busy loading wheel".
Turning of Ublock Origin solves the problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/107848949/174578100-a169a552-097d-47fb-b770-6705c26df27f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 82634
  cosmetic: 45304
  scriptlet: 17201
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2278-11, 11d.19h.14m
    easylist: 68069-54, 11d.19h.5m
    easyprivacy: 27173-123, 11d.19h.13m
    plowe-0: 3670-807, 18d.22h.6m
    ublock-abuse: 75-0, 21d.56m
    ublock-badware: 4165-91, 11d.19h.12m
    ublock-filters: 31729-145, 11d.19h.11m
    ublock-privacy: 212-4, 21d.55m
    ublock-quick-fixes: 192-2, 11d.19h.3m
    ublock-unbreak: 1799-54, 11d.19h.10m
    urlhaus-1: 7229-0, 11d.19h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 282 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 1
    hotjar.com: 1
    marketingautomation.services: 1
    youtube.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
@@||marketingautomation.services/client/ss.js$script,domain=leeuwerik.nl
@@||marketingautomation.services/*login$script,domain=leeuwerik.nl
```

@ryanbr

**Comment by PdM-NL** [comment]
That seems to work!
Can these exceptions be added to the official filterlist? 
And if so how long will it take for our systems te receive the update?

Thanks,
Paul

**Comment by mapx-** [comment]
temporary added in our quick fix (6-12 h updating frequency) but the definitive fix should land in easyprivacy

**Comment by PdM-NL** [comment]
Thanks!

**Comment by ryanbr** [comment]
`@@||marketingautomation.services/*login$script,domain=leeuwerik.nl`  what is blocking is this?  Only seeing https://koi-3qn8yzjwa6.marketingautomation.services/client/ss.js?ver=2.4.0

**Comment by mapx-** [comment]
whitelist that 1 and then you'll get the login
