### ISSUE TITLE
watch.tataplay.com: breakage

### ISSUE THREAD

**Issue by araj98199** [uBlockOrigin/uAssets#13781]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watch.tataplay.com/`

### Category

breakage

### Describe the issue

website is for watching tata play live tv for tataplay subscribers in india, somehow it doesnt work when the adblocker is turned on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/40234116/174567264-d1457c95-c69a-4f28-bb3f-d955b2e2412d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 101
filterset (summary): 
  network: 85215
  cosmetic: 43953
  scriptlet: 17274
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.21h.35m
  default: 
    user-filters: 0-0, never
    easylist: 68479-50, 2d.20h.15m
    easyprivacy: 27226-122, 2d.20h.4m
    plowe-0: 3639-781, 10d.22h.21m
    ublock-abuse: 75-0, 10d.22h.19m
    ublock-badware: 4170-91, 2d.3h.36m
    ublock-filters: 31819-102, 2d.3h.35m
    ublock-privacy: 222-2, 10d.22h.15m
    ublock-quick-fixes: 201-2, 2h.37m
    ublock-unbreak: 1802-40, 2d.3h.34m
    urlhaus-1: 10167-0, 18h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 330 ms (selfie)
  maxAssetCacheWait: 167 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    branch.io: 1
    google-analytics.com: 1
    moengage.com: 1
    mxpnl.com: 1
```
</details>

**Comment by mapx-** [comment]
Test this filter

`@@||cdn.branch.io/branch-latest.min.js$script`

**Comment by ghajini** [comment]
this much play videos on my end

`@@||cdn.branch.io/branch-latest.min.js$script,domain=watch.tataplay.com`

**Comment by Manikandan-Vanniyar** [comment]
@ghajini 
![Screenshot 2024-12-13 135001](https://github.com/user-attachments/assets/7a318423-1a7c-4216-afe5-a6fb6580af4a)
 Anyway to get rid of this irritating popup tried everything from zapper to picker but nothing worked

**Comment by Manikandan-Vanniyar** [comment]
@ghajini 
Yeah bro those filters solve the issue but create another problem ie. login popup is not showing

**Comment by Manikandan-Vanniyar** [comment]
@ghajini 
Great bro. It seems to work. Thanks🙏. will report if any issue arises.

**Comment by Manikandan-Vanniyar** [comment]
@ghajini 
![Screenshot 2024-12-14 144136](https://github.com/user-attachments/assets/bb4ef61b-ee5a-45ca-9224-b4c30798b5ac)
Update: the issue still persists

**Comment by Manikandan-Vanniyar** [comment]
Yesterday popup was shown but today it seems to work.
