### ISSUE TITLE
cocomanga.com: ads

### ISSUE THREAD

**Issue by raozhihongdie** [uBlockOrigin/uAssets#13797]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cocomanga.com/`

### Category

ads

### Describe the issue

The AD screen doesn't load, but when your hand touches the screen, it jumps to the AD link

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium Mobile: 75
filterset (summary): 
  network: 100685
  cosmetic: 34889
  scriptlet: 17431
  html: 0
listset (total-discarded, last updated): 
  default: 
    CHN-0: 28457-1189, 1d.5h.30m
    adguard-mobile: 7864-55, 1d.5h.31m
    easylist: 68594-24420, 1d.5h.14m
    easyprivacy: 27240-157, 1d.5h.10m
    plowe-0: 3644-870, 8d.22h.4m
    ublock-abuse: 75-0, 9d.18h.6m
    ublock-badware: 4184-93, 1d.5h.9m
    ublock-filters: 31919-375, 1d.5h.7m
    ublock-privacy: 222-4, 9d.18h.2m
    ublock-quick-fixes: 201-2, 3h.32m
    ublock-unbreak: 1812-43, 1d.4h.44m
    urlhaus-1: 6166-0, 3h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 567 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by MasterKia** [comment]
> ```yaml
> Chromium Mobile: 75
> ```

Kiwi browser isn't supported, it has problems with uBlock Origin.
Also version 75 is too old, the latest version is 101 ...

**Comment by MasterKia** [comment]
> ```yaml
> Chromium Mobile: 75
> ```

Kiwi browser isn't supported, it has problems with uBlock Origin.
Also version 75 is too old, the latest version is 101 ...

Use Firefox Android, it supports uBlock Origin.
