### ISSUE TITLE
maxdeportv.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1379]
URL(s) where the issue occurs

`http://maxdeportv.net/?canal=1`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Anti-Adblock @okiehsch
`http://maxdeportv.net/?canal=beinhd`

**Comment by okiehsch** [comment]
`http://maxdeportv.net/?canal=beinhd` works fine on my end.

**Comment by xDarkARG** [comment]
en el Reproductor multimedia tienes que poner opcion 1 Latino prueba varios botones aparecera @okiehsch

**Comment by okiehsch** [comment]
I do not get any working video with `Latino option 1`, does
````
vipracing.tv##.in-video-adds.row
@@||deportesmax.info^$generichide
bro.adca.st##.xclo
bro.adca.st##.xraulitox
bro.adca.st##.xpepinx
````
work for you?

**Comment by okiehsch** [comment]
How about
````
@@||vipracing.tv^$generichide
@@||bro.adca.st^$generichide
@@||deportesmax.info^$generichide
bro.adca.st##.xclo
bro.adca.st##.xraulitox
bro.adca.st##.xpepinx
vipracing.tv##.in-video-adds.row
````

**Comment by xDarkARG** [comment]
este sigue apareciendo pero ahora se ve el con la imagen blanca un poco trasparente @okiehsch 
![](https://i.imgur.com/bZ0mTtU.png)

**Comment by okiehsch** [comment]
I can't reproduce,  I don't get that message, sorry.

**Comment by xDarkARG** [comment]
The message appears when I try too much by pressing buttons step from one channel to another.

this works perfect for this @okiehsch

vipracing.tv##.in-video-adds.row
@@||deportesmax.info^$generichide
bro.adca.st##.xclo
bro.adca.st##.xraulitox
bro.adca.st##.xpepinx

![](https://i.imgur.com/kAAcxDP.png)

**Comment by okiehsch** [comment]
That picture I can reproduce, so I will add them.
