### ISSUE TITLE
insurance.veganab.co: ads

### ISSUE THREAD

**Issue by Stickman-1** [uBlockOrigin/uAssets#13796]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.easysky.in/UmwbzBCt`

### Category

Ads

### Describe the issue

Showing cookies notice 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 248023
  cosmetic: 241104
  scriptlet: 39678
  html: 783
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64904-6637, 1d.16h.59m
    adguard-spyware: 26159-1142, 1d.16h.59m
    adguard-spyware-url: 634-14, 1d.16h.59m
    block-lan: 43-0, 1d.16h.59m
    curben-phishing: 21883-3, 5m
    curben-pup: 232-0, 5m
    adguard-annoyance: 54184-4976, 1d.16h.59m
    adguard-social: 17645-1659, 1d.16h.59m
    fanboy-thirdparty_social: 68-1, 1d.16h.59m
    fanboy-annoyance: 73692-62257, 1d.16h.59m
    fanboy-cookiemonster: 34674-15521, 1d.16h.59m
    fanboy-social: 23261-13680, 1d.16h.59m
    ublock-annoyances: 4495-15, 1d.16h.59m
    dpollock-0: 10375-512, 1d.16h.59m
    ALB-0: 267-7, 5m
    ara-0: 2581-243, 1d.16h.59m
    BGR-0: 1091-19, 1d.16h.59m
    CHN-0: 28447-1258, 1d.16h.59m
    CZE-0: 711-40, 4m
    DEU-0: 5838-380, 5m
    [28 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 32570-682, 1d.16h.59m
    ublock-badware: 4188-3, 1d.16h.59m
    ublock-privacy: 230-1, 1d.16h.59m
    ublock-abuse: 75-0, 1d.16h.59m
    ublock-unbreak: 1825-24, 1d.16h.59m
    ublock-quick-fixes: 206-0, 4m
    adguard-mobile: 7865-239, 1d.17h
    easylist: 68572-25312, 1d.16h.59m
    easyprivacy: 27236-10571, 1d.16h.59m
    urlhaus-1: 6166-0, 4m
    plowe-0: 3647-3, 1d.16h.59m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2202 ms (selfie)
  maxAssetCacheWait: 4092 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    doubleclick.net: 8
```
</details>

**Comment by Stickman-1** [comment]
![Screenshot_2022-06-21-15-31-32-04_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/102072078/174774961-7ce51877-6ae7-4ed6-aa6c-b0d07e2756f0.jpg)

**Comment by MasterKia** [comment]
Enable the "EasyList Cookie" list from the Annoyances filters in uBO settings and then report the website here:
https://github.com/easylist/easylist/issues
