### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by arrfrgl** [uBlockOrigin/uAssets#13794]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/k3soju`

### Category

ads

### Describe the issue

i see lots of ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 87035
  cosmetic: 50082
  scriptlet: 17620
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8264-58, 3d.2h.18m
    easylist: 68521-68, 3d.2h.15m
    easyprivacy: 27231-127, 3d.2h.14m
    plowe-0: 3647-784, 3d.2h.13m
    ublock-abuse: 75-0, 3d.2h.11m
    ublock-badware: 4170-91, 3d.2h.9m
    ublock-filters: 31819-112, 3d.2h.8m
    ublock-privacy: 224-2, 3d.2h.7m
    ublock-quick-fixes: 211-2, 1d.1h.38m
    ublock-unbreak: 1802-40, 3d.2h.5m
    urlhaus-1: 10223-0, 1d.1h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 336 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 1
```
</details>

**Comment by arrfrgl** [comment]
please

**Comment by zeref-dragneel** [comment]
#5184

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see other indications
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
