### ISSUE TITLE
sj-r.com: ads

### ISSUE THREAD

**Issue by DoronLGN** [uBlockOrigin/uAssets#13790]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sj-r.com/story/news/politics/elections/congressional/2022/05/26/newcomers-battle-over-seat-13-th-congressional-district-illinois/9719305002/`

### Category

ads

### Describe the issue

"Get local news this summer for free" banner ad is present below Budzinski's answer.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 85180
  cosmetic: 43955
  scriptlet: 17260
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 68594-50, 8h.54m
    easyprivacy: 27240-122, 8h.53m
    plowe-0: 3639-781, 10d.16h.50m
    ublock-abuse: 75-0, 11d.16h.14m
    ublock-badware: 4172-91, 8h.52m
    ublock-filters: 31831-105, 8h.51m
    ublock-privacy: 222-3, 11d.16h.13m
    ublock-unbreak: 1807-40, 8h.50m
    urlhaus-1: 10167-0, 20h.55m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 473 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    sj-r.com: 3
    2mdn.net: 1
    adsafeprotected.com: 1
    adsrvr.org: 1
    amazon-adsystem.com: 1
    btloader.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    google.com: 3
    googleadservices.com: 1
    googletagmanager.com: 1
    igodigital.com: 1
    imasdk.googleapis.com: 1
    impactradius-event.com: 1
    krxd.net: 1
    parsely.com: 1
    sc-static.net: 1
    scorecardresearch.com: 1
    taboola.com: 2
    xg4ken.com: 1
```
</details>

**Comment by ghajini** [comment]
Its a first party promotion which do not get blocked in default lists
add this `sj-r.com###gnt_atomsnc` to your my filters or subscribe to **fanboy annoyances list**
