### ISSUE TITLE
google infocards are blocked by cosmetic filtering

### ISSUE THREAD

**Issue by kopurando** [uBlockOrigin/uAssets#138]
### URL(s) where the issue occurs

`https://www.google.co.th/?gws_rd=cr%2Cssl&ei=4EHXV73tOKT4jwToqpGABA#newwindow=1&q=direct+HKT+flights`

### Describe the issue

Normally google displays an infocard with flights destinations, but uBlock cosmetic filtering hides it along with text ads. I could not figure out how to hide ads and leave the infocard in place.

### Screenshot(s)

![image](https://cloud.githubusercontent.com/assets/6130979/18462497/05d3ac3e-79ad-11e6-9ac5-5a7561e125be.png)
![image](https://cloud.githubusercontent.com/assets/6130979/18462505/1166b42e-79ad-11e6-844c-c94798bec5ee.png)

### Versions

- Browser/version: Version 53.0.2785.89 beta (64-bit)
Version 55.0.2853.0 canary (64-bit)

- uBlock Origin version: uBlock Origin v1.9.4

### Settings
Tried switching off/on all filters, can't hide ads w/o hiding infoblock too :(

![image](https://cloud.githubusercontent.com/assets/6130979/18462515/281a96e0-79ad-11e6-859d-2bb4497afaab.png)

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/18472931/3213ecc0-7988-11e6-860e-8b81acf16128.png)

Report to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by F4z** [comment]
I think in "uBlock filters"‎ is also the same rule - https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L11
No?

**Comment by gorhill** [comment]
Looks like the same. _uBlock filters_ should have been reported in the info box, looks like an issue to fix.

**Comment by gorhill** [comment]
Interesting: when I replace `co.th` with `ca` in the URL, the info card is labeled _"Sponsored"_.

**Comment by F4z** [comment]
> uBlock filters should have been reported in the info box, looks like an issue to fix.

For me it is reported in uBO 1.9.4 for Chrome and uBO 1.9.6 for Firefox.
![image](https://cloud.githubusercontent.com/assets/11742596/18473972/f4234446-79bf-11e6-970c-93850c5845b4.png)

> This should still be reported to EasyList maintainers

I will report this.

> Interesting: when I replace co.th with ca in the URL, the info card is labeled "Sponsored".

Yes, I also see this, when I replace `co.th` with `pl` or `ru` or `de` in the URL, the info card is labeled "Sponsored", but when I replace `co.th` with `fi` or `by` it is looks the same like on `co.th`.
