### ISSUE TITLE
austiblox.net: detection

### ISSUE THREAD

**Issue by samdisk11** [uBlockOrigin/uAssets#13803]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://austiblox.net/`

### Category

detection

### Describe the issue

Upon loading the site with uBlockOrigin, the site's contents will be deleted and replaced with the following text: 
`"This website costs a lot of money to operate, I am the only one funding it and its getting harder to pay for the servers. All ad revenue goes to hosting, I make no money off of this. Im not crazy with ads (unlike others who put 999 ads on their page). Please whitelist this website in your adblocker. Thanks."`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/24478471/174906126-a5406381-7224-4ddf-bade-4b2026375363.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 81184
  cosmetic: 44018
  scriptlet: 17226
  html: 685
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 23h.27m
  default: 
    user-filters: 94-4, never
    ublock-filters: 32464-33, 2d.11h.34m
    ublock-badware: 4176-3, 2d.11h.33m
    ublock-privacy: 230-0, 8d.3h.55m
    ublock-abuse: 75-0, 7d.23h.54m
    ublock-unbreak: 1820-0, 2d.7h.32m
    easylist: 68572-576, 2d.7h.31m
    easyprivacy: 27236-582, 2d.7h.30m
    urlhaus-1: 6166-0, 16h.18m
    plowe-0: 3647-3, 16h.19m
filterset (user): [array of 95 redacted]
trustedset: 
  added: [array of 77 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16948 ms (selfie)
  maxAssetCacheWait: 410 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    austiverse.com: 2
    googlesyndication.com: 2
    hitwebcounter.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
austiblox.net##+js(set, areWeWorkin, true)
austiblox.net##+js(no-fetch-if, googlesyndication.com)
```

**Comment by samdisk11** [comment]
works perfectly now, no more ublock detections.

**Comment by samdisk11** [comment]
Site detects uBlock again, redirects to https://austiblox.net/please.html (disable adblock message)

**Comment by mapx-** [comment]
Do I need an account ?

**Comment by samdisk11** [comment]
> Do I need an account ?

Yes

**Comment by mapx-** [comment]
You should provide a test account, send it to this reddit user [u/ajaxmix](https://www.reddit.com/user/ajaxmix/)

**Comment by eloas3** [comment]
Hi, I'm being detected
All the prerequisites are checked for me except custom rules (but they do not affect this website at all) Here are my details:
```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 257322
 cosmetic: 240276
 scriptlet: 46531
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 28010-31, 10m
  adguard-generic: 79380-481, 10m
  adguard-mobile: 8831-45, 10m
  adguard-mobile-app-banners: 4729-10, 10m
  adguard-other-annoyances: 13752-9, 10m
  adguard-popup-overlays: 25060-74, 9m
  adguard-social: 21998-929, 9m
  adguard-spyware: 63267-1395, 9m
  adguard-spyware-url: 1306-5, 9m
  adguard-widgets: 2340-6, 9m
  block-lan: 54-0, 9m
  curben-phishing: 76626-20, 9m
  [9 lists not shown]: [too many]
 default:
  easylist: 75151-1734, 9m
  easyprivacy: 32839-16634, 9m
  plowe-0: 3720-1243, 9m
  ublock-badware: 7430-331, 9m
  ublock-filters: 35157-4258, 9m
  ublock-privacy: 661-179, 9m
  ublock-quick-fixes: 146-93, 9m
  ublock-unbreak: 2134-147, 9m
  urlhaus-1: 11855-1, 9m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 32512 ms (selfie)
 maxAssetCacheWait: 793 ms
popupPanel:
 blocked: 1
 network:
  hitwebcounter.com: 1
 extended:
  ##+js(abort-on-property-read, document.body.innerHTML)
  ##+js(set-constant, detectAdBlock, noopFunc)
```

Use this account since it's required 
**Email:** theawesomeguy173@gmail.com 
**Password:** yoursecurityissohighthatyoucanseethispassword

**Comment by thexkey** [comment]
Try this:
`austiblox.net##+js(set, coolStuff, true)`

**Comment by eloas3** [comment]
> Try this: `austiblox.net##+js(set, coolStuff, true)`

Site is down, will try once it's back up

**Comment by eloas3** [comment]
> > Try this: `austiblox.net##+js(set, coolStuff, true)`
> 
> Site is down, will try once it's back up

It doesn't work unfortunately, still redirects to https://austiblox.net/please.html

**Comment by stephenhawk8054** [comment]
@eloas3 Have you forced update the filter lists yet?

**Comment by eloas3** [comment]
@stephenhawk8054 Yep, force updated all of them right now, not working still

**Comment by mapx-** [comment]
@eloas3 reset uBO to default lists / settings, disable other extensions and test again

**Comment by eloas3** [comment]
> @eloas3 reset uBO to default lists / settings, disable other extensions and test again

Works now, thanks!!
