### ISSUE TITLE
65.108.132.145: ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#13807]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://65.108.132.145/`

### Category

ads

### Describe the issue

The ads always show, only on this website. Tried reinstalling uBO, didnt solve it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (14)](https://user-images.githubusercontent.com/108001860/175028409-c014df4e-a6ca-4dcb-81f4-30151514d341.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 80575
  cosmetic: 44035
  scriptlet: 17282
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68594-50, 2d.31m
    easyprivacy: 27240-122, 2d.30m
    plowe-0: 3647-783, 2d.20h.20m
    ublock-abuse: 75-0, 3d.20h.35m
    ublock-badware: 4180-93, 2d.29m
    ublock-filters: 31831-106, 2d.28m
    ublock-privacy: 224-3, 3d.20h.34m
    ublock-quick-fixes: 204-2, 4h.48m
    ublock-unbreak: 1807-40, 2d.27m
    urlhaus-1: 5453-0, 4h.47m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 843 ms (selfie)
  maxAssetCacheWait: 511 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    65.108.132.145: 3
    googletagmanager.com: 1
    histats.com: 1
    scurfrubicon.com: 1
    throwerdeaner.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
65.108.132.145##.sgpb-popup-overlay
65.108.132.145##.sgpb-popup-dialog-main-div-wrapper
||65.108.132.145/*.gif$image
```

maybe you should report here: https://github.com/ABPindo/indonesianadblockrules/issues

@gmarcher
