### ISSUE TITLE
uBlock Origin is not blocking ads on TIDAL

### ISSUE THREAD

**Issue by logicalwillow** [uBlockOrigin/uAssets#13805]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

uBlock Origin is not blocking advertisements on listen.tidal.com.
This was not always the case. At first, ads were blocked on TIDAL, but autoplay didn't work. Disabling uBlock Origin fixed autoplay, but now, even with uBlock Origin enabled, ads aren't blocked.

I took a screenshot of the console when autoplay didn't work.
![image](https://user-images.githubusercontent.com/56515875/174921402-5b82e19e-835c-4167-9d43-98c7e4fc9a78.png)

### A specific URL where the issue occurs

listen.tidal.com

### Steps to Reproduce

Play music on listen.tidal.com. Advertisements won't be blocked.

### Expected behavior

Advertisements that appear between songs are blocked.

### Actual behavior

Advertisements that appear between songs play even with uBlock Origin enabled.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 79549
  cosmetic: 44037
  scriptlet: 17246
  html: 686
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32464-35, 2d.9h.35m
    ublock-badware: 4189-3, 2d.9h.35m
    ublock-privacy: 230-0, 2d.9h.35m
    ublock-abuse: 75-0, 2d.9h.35m
    ublock-unbreak: 1820-0, 2d.9h.35m
    easylist: 68572-577, 2d.9h.35m
    easyprivacy: 27236-582, 2d.9h.35m
    urlhaus-1: 4440-0, 3h
    plowe-0: 3647-3, 2d.9h.35m
    ublock-quick-fixes: 205-0, 2h.59m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1285 ms (selfie)
  maxAssetCacheWait: 479 ms
```
</details>

**Comment by MasterKia** [comment]
Duplicate
https://github.com/uBlockOrigin/uAssets/issues/12647
https://github.com/uBlockOrigin/uAssets/issues/13769

**Comment by carapaces** [comment]
There does not seem to be a fix for this problem.

**Comment by stephenhawk8054** [comment]
@carapaces Can you test this filter?

```adb
listen.tidal.com##+js(no-fetch-if, /\d\?country/)
```
