### ISSUE TITLE
welingelichtekringen.nl: breakage

### ISSUE THREAD

**Issue by AmberStones** [uBlockOrigin/uAssets#13800]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [x] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.welingelichtekringen.nl/`

### Category

breakage

### Describe the issue

Wanneer ik een kop van een nieuwsbericht aanklik wordt het nieuwsbericht niet geladen. 
Het wordt geblokkeerd door Ublock
Het programma dat ik gebruik is Firefox voor Android versie 101.2.0

or translate with Google:

When I click on a headline of a news item, the news item is not loaded. 
It is blocked by Ublock
The program I use is Firefox for Android version 101.2.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 83373
  cosmetic: 27283
  scriptlet: 17279
  html: 689
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32549-336, 3d.6h.52m
    ublock-badware: 4174-3, 3d.6h.23m
    ublock-privacy: 228-1, 10d.18h.59m
    ublock-abuse: 75-0, 12d.19h.21m
    ublock-unbreak: 1820-17, 3d.6h.48m
    ublock-quick-fixes: 206-0, 8h.38m
    adguard-mobile: 7865-175, 3d.6h.53m
    easylist: 68520-24854, 3d.6h.37m
    easyprivacy: 27231-588, 3d.6h.32m
    urlhaus-1: 6166-0, 8h.37m
    plowe-0: 3642-3, 10d.2h.14m
    NLD-0: 2316-23, 31m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 261 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by okiehsch** [comment]
@BPower0036
Can you reproduce?

**Comment by ghajini** [comment]
@AmberStones 
do you see this in ubo logger(which fixes your issue)
![Screenshot_20220622-111818-548](https://user-images.githubusercontent.com/20338483/174954359-5159dc0a-6ff9-429a-8040-ec425d6ca06a.png)

**Comment by ghajini** [comment]
will you force update the filters and see if that fixes the issue?

**Comment by BPower0036** [comment]
@okiehsch I can't reproduce. However i can confirm what @Zaharos said.
Fixes are to made.

**Comment by okiehsch** [comment]
> Fixes are to made.

Meaning you will fix it in your list?

**Comment by AmberStones** [comment]
Thanks @mapx- , that was really helpful!!

@ghajini : I thought I updated the filters, did it again just to be sure... 
And upps, the site looks normal now!

Thank you **all** for your support!!!
