### ISSUE TITLE
matcharenagame.com: breakage

### ISSUE THREAD

**Issue by frshhh** [uBlockOrigin/uAssets#13814]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://matcharenagame.com/play`

### Category

breakage

### Describe the issue

When uBO is active, clicking play does nothing (the loading circle just spins and the game never loads). The only way to get the game to load is to disable uBO, then click play, at which point you can then re-enable uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 79637
  cosmetic: 44059
  scriptlet: 17247
  html: 687
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32469-32, 2d.14h.2m
    ublock-badware: 4184-4, 2d.14h.1m
    ublock-privacy: 230-0, 1d.14h.18m
    ublock-abuse: 75-0, 1d.14h.17m
    ublock-unbreak: 1824-2, 1d.3h.56m
    easylist: 68684-580, 1d.3h.58m
    easyprivacy: 27244-582, 1d.3h.57m
    urlhaus-1: 4440-0, 23h.55m
    plowe-0: 3645-3, 7d.7h.15m
    ublock-quick-fixes: 205-2, 23h.54m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 122 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    gamedistribution.com: 7
    gamedock.io: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    headerlift.com: 1
```
</details>

**Comment by Zaharos** [comment]
Is Firefox's anti-tracking enabled?

`https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop`

**Comment by frshhh** [comment]
> Is Firefox's anti-tracking enabled?
> 
> `https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop`

It was, yes, but I just disabled it and nothing changed.

**Comment by Zaharos** [comment]
I reproduced after disabling uBO, refreshing the webpage, and then re-enabling it

**Comment by mapx-** [comment]
@frshhh Test:
`gamedistribution.com##+js(no-fetch-if, error)`

**Comment by frshhh** [comment]
> @frshhh Test:

>gamedistribution.com##+js(no-fetch-if, error)

Doesn't fix it for me.

**Comment by mapx-** [comment]
@stephenhawk8054 could you test this issue ?

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 could you test this issue ?

Yeah, sometimes the game loads, but sometimes it can't.

**Comment by mapx-** [comment]
does this work better ?

`gamedistribution.com##+js(no-fetch-if, /^/)`

**Comment by frshhh** [comment]
> does this work better ?
> 
> `gamedistribution.com##+js(no-fetch-if, /^/)`

YES! That works, although weirdly I no longer have to click "play" to load the game (is that intended?)

**Comment by stephenhawk8054** [comment]
That works for me too.

**Comment by garry-ut99** [comment]
The paradox is that `gamedistribution.com##+js(no-fetch-if, /^/)` fixes games on some sites but at the same time breaks games on others:
- it fixed games at `matcharenagame.com` and `gamedistribution.com` but on the other side it broke games at `girlsgogames.com` https://github.com/uBlockOrigin/uAssets/issues/3594#issuecomment-1414457113
- now the filter has been removed in https://github.com/uBlockOrigin/uAssets/commit/639806654c566dcae7feee30ca73ad2a2349b90f to fix games at `girlsgogames.com`,  which broke games on `matcharenagame.com` and `gamedistribution.com` again

**Comment by stephenhawk8054** [comment]
@garry-ut99 Does

```adb
html5.gamedistribution.com##+js(no-fetch-if, api)
```

work for you?

**Comment by garry-ut99** [comment]
Yes.
