### ISSUE TITLE
rlsbb.ru: nuisance

### ISSUE THREAD

**Issue by Robbie711** [uBlockOrigin/uAssets#13811]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rlsbb.ru/category/movies/`

### Category

nuisance

### Describe the issue

Picker doesn't work on these two images.
`https://rlsbb.ru/category/movies/`
"UploadGIG" and "Follow us on Twitter"
`https://www.screenpresso.com/=wwuAe`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Picker doesn't work on these two images.
https://rlsbb.ru/category/movies/
"UploadGIG" and "Follow us on Twitter"

![rlsbb](https://user-images.githubusercontent.com/17227103/175145532-4a9674e6-afa7-4f21-a571-633badd9a58e.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 85282
  cosmetic: 92100
  scriptlet: 22640
  html: 695
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    ublock-annoyances: 4475-4, 1d.12h.48m
    adguard-annoyance: 54240-272, 1d.12h.47m
  default: 
    user-filters: 140-13, never
    ublock-filters: 32474-383, 1d.12h.52m
    ublock-badware: 4199-3, 1d.12h.46m
    ublock-privacy: 228-0, 12d.17h.50m
    ublock-abuse: 75-0, 12d.17h.51m
    ublock-unbreak: 1823-2, 1d.12h.51m
    easylist: 68684-620, 1d.12h.50m
    easyprivacy: 27244-678, 1d.12h.49m
    plowe-0: 3641-3, 12d.5h.48m
    urlhaus-1: 5435-0, 7h.6m
    ublock-quick-fixes: 205-0, 7h.7m
filterset (user): [array of 141 redacted]
trustedset: 
  added: [array of 203 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 286 ms (selfie)
  maxAssetCacheWait: 354 ms
popupPanel: 
  blocked: 20
  no-large-media: true
  no-popups: true
  no-scripting: true
  blockedDetails: 
    rlsbb.ru: 19
    histats.com: 1
```
</details>

**Comment by mapx-** [comment]
> Picker doesn't work

Explain better

![image](https://user-images.githubusercontent.com/10303732/175214003-774bc4e1-f832-4cfe-baca-3f0a30157e0c.png)

**Comment by mapx-** [comment]
yes, after creating the filter with the element picker you should hard-refresh (Ctrl-F5) and the gif will be gone.

Or use a more general filter editing that one:
`||picimg.net/*.gif$image`
