### ISSUE TITLE
Corksicle cork circle broken

### ISSUE THREAD

**Issue by CookieSalesman** [uBlockOrigin/uAssets#13817]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://corkcicle.com/pages/rewards?utm_source=Yotpo`

### Describe the issue

Large sections of webpage not loading

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9441933/175209850-0a12fd99-efea-43cd-93ff-2212770ee516.png)

### uBlock Origin version

1.43.0

### Browser name and version

Chrome latest

### Settings

-None significant

### Notes

Should be reproducable by others.

**Comment by mapx-** [comment]
add

`@@||cdn.yottaa.com/rapid.min.js?key=$script,domain=corkcicle.com`

@ryanbr
