### ISSUE TITLE
play.aidungeon.io: nuisance

### ISSUE THREAD

**Issue by coolusernamegoeshere** [uBlockOrigin/uAssets#13818]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://play.aidungeon.io/`

### Category

nuisance

### Describe the issue

So they implemented ads recently, except when you try to block them it does what's shown in the attached screenshot. Trying to add filters doesn't help, eventually you can get the overlay away but most buttons aren't functional once you do that.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ihateithere](https://user-images.githubusercontent.com/108046888/175217343-32d283be-f74a-4bba-825c-24a63a81a2b4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 79805
  cosmetic: 44150
  scriptlet: 17280
  html: 691
listset (total-discarded, last updated): 
  default: 
    user-filters: 9-0, never
    ublock-filters: 32505-37, 10h.27m
    ublock-badware: 4209-3, 10h.26m
    ublock-privacy: 230-0, 3d.14h.10m
    ublock-abuse: 75-0, 3d.14h.9m
    ublock-unbreak: 1824-2, 10h.25m
    easylist: 68820-579, 10h.24m
    easyprivacy: 27251-580, 10h.23m
    urlhaus-1: 4509-0, 35m
    plowe-0: 3644-3, 10d.10h.44m
    ublock-quick-fixes: 221-0, 36m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 436 ms (selfie)
  maxAssetCacheWait: 248 ms
popupPanel: 
  blocked: 5
  no-popups: true
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 2
    stat-rock.com: 2
```
</details>

**Comment by mapx-** [comment]
Where are the ads ? Do I need an account ?
