### ISSUE TITLE
animegamesus.com: ads

### ISSUE THREAD

**Issue by CrazyMega02** [uBlockOrigin/uAssets#13820]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animegamesus.com/ce/ce_0821/land_ce_300821_na_en/?utm_campaign=pu_ce_propeller_fr_ron&utm_content=5052683&bnid=land_ce_300821_na_en&crID=2493306&zID=96725&land=land_ce_300821_na_en&landing=modest`

### Category

ads

### Describe the issue

I got sent directly to a dangerous type ad site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 99816
  cosmetic: 53116
  scriptlet: 17374
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-4, never
    FRA-0: 28854-24, 1d.16h.40m
    easylist: 68684-89, 1d.16h.45m
    easyprivacy: 27244-439, 1d.16h.41m
    plowe-0: 3647-790, 3d.11h.44m
    ublock-abuse: 75-1, 4d.11h.56m
    ublock-badware: 4205-102, 1d.16h.44m
    ublock-filters: 31859-250, 1d.16h.43m
    ublock-privacy: 224-3, 4d.11h.55m
    ublock-quick-fixes: 223-2, 12h.9m
    ublock-unbreak: 1811-42, 1d.16h.42m
    urlhaus-1: 5435-0, 12h.10m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 457 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    gamesrevenue.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
Which is the original page you wanted to visit ? `animegamesus` one ? other ?

**Comment by Yuki2718** [comment]
How did you come to this site?

**Comment by CrazyMega02** [comment]
oh sorry no I was visiting https://vostfree.tv/animes-vostfr/
originaly

**Comment by CrazyMega02** [comment]
hm strange
