### ISSUE TITLE
[Anti adblock] megaup.net

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#13826]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://megaup.net/9eeT/TyranoBuilder.Visual.Novel.Studio.APP.rar

### Describe the issue

Wait the full time and you'll see Anti Adblock.

### Screenshot(s)

https://imgur.com/a/rk8chUj

### uBlock Origin version

Latest

### Browser name and version

Chrome Latest

### Settings

N/A

**Comment by JobcenterTycoon** [comment]
Force update the filter lists it got fixed 2 hours ago

**Comment by zeref-dragneel** [comment]
`https://megaup.net/1LG97/God_of_War_v1.0.12-Razor1911.part01.rar`

![ảnh](https://user-images.githubusercontent.com/95934994/178542618-c27cb45c-1752-4ef5-adc6-cfad5d6dbf92.png)
