### ISSUE TITLE
[nsfw] t-online.de: ads

### ISSUE THREAD

**Issue by zorks1233** [uBlockOrigin/uAssets#13828]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.t-online.de/nachrichten/ausland/eu/id_91329964/hohe-gaspreise-eu-will-gemeinsamen-einkauf-ermoeglichen-.html`

### Category

ads

### Describe the issue

Es verschwindet immer die Cookie-Balken 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 81517
  cosmetic: 47833
  scriptlet: 17335
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    DEU-0: 5845-0, 1h.22m
    easylist: 67868-56, 1d.4h.18m
    easyprivacy: 27257-132, 1d.4h.18m
    plowe-0: 3647-784, 1d.4h.18m
    ublock-abuse: 75-0, 1d.4h.18m
    ublock-badware: 4211-93, 1d.4h.18m
    ublock-filters: 31869-117, 1d.4h.18m
    ublock-privacy: 224-3, 1d.4h.18m
    ublock-quick-fixes: 223-2, 1h.21m
    ublock-unbreak: 1813-43, 1d.4h.18m
    urlhaus-1: 5045-0, 1h.20m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 233 ms (selfie)
  maxAssetCacheWait: 126 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    t-online.de: 1
    googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment]
> Es verschwindet immer die Cookie-Balken

Geht es etwas genauer?
![image](https://user-images.githubusercontent.com/16838044/175650060-25a8386f-ed73-4aa3-82f2-5fb27887e84b.png)

Ich nehme an dieser "Balken" ist gemeint, wo ist das Problem?

**Comment by Procyon-b** [comment]
Do you have an extension like "I don't care about cookie"?
What does happen when you disable ublock? Does the cookie dialog stays on screen?
