### ISSUE TITLE
voe.sx domain change. Adblock detection, preventing playback

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#13839]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://streamkiste.tv/movie/lotte-jaeger-und-das-tote-maedchen-2016-5194658#video`

### Describe the issue

See #13582
voe now serves from `voeun-block.com` and successfully prevents playback again.

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 101.0.1

### Settings

not relevant

**Comment by ghajini** [comment]
did you updated the filters?

`voeun-block.com` >domain does not exist

**Comment by Janmm14** [comment]
I'm sorry, my filters were out of date. also its .net and not .com, my bad
