### ISSUE TITLE
athletic.net: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#13830]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.athletic.net/result/2Kile8gsXSzwnWpTr/`

### Category

breakage

### Describe the issue

Cannot view athelte information when enabled. Can view when it is disabled. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-06-24 at 10 42 36 PM](https://user-images.githubusercontent.com/69532417/175760072-f2573b7d-81f7-4bfb-9711-f91630023ad2.png)
![Screen Shot 2022-06-24 at 10 41 02 PM](https://user-images.githubusercontent.com/69532417/175760075-eea0aa2e-b669-4907-a84d-ff98f433528b.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 148026
  cosmetic: 191888
  scriptlet: 36888
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54335-104, 45m
    adguard-generic: 65076-681, 44m
    adguard-mobile: 7860-44, 43m
    adguard-spyware: 25820-833, 42m
    adguard-spyware-url: 646-13, 13m
    block-lan: 43-0, 20d.23h.47m
    curben-phishing: 23735-0, 12m
    curben-pup: 219-1, 12m
    fanboy-annoyance: 73872-3147, 49m
    fanboy-cookiemonster: 34878-34862, 48m
    ublock-annoyances: 4468-223, 13m
  default: 
    user-filters: 0-0, never
    easylist: 67930-1034, 13m
    easyprivacy: 27264-10170, 13m
    plowe-0: 3645-951, 10d.24m
    ublock-abuse: 75-0, 51m
    ublock-badware: 4216-319, 13m
    ublock-filters: 31931-3733, 13m
    ublock-privacy: 224-49, 50m
    ublock-quick-fixes: 229-58, 12m
    ublock-unbreak: 1813-102, 46m
    urlhaus-1: 5056-1, 47m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16551 ms
  maxAssetCacheWait: 9396 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    athletic.net: 1
    addthis.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    quantserve.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`athletic.net#@#.share-header`

FA issue @ryanbr

**Comment by jimmysofat6864** [comment]
@mapx- @ryanbr Text that says "View Athletic.net Ad Free" is still present.

**Comment by mapx-** [comment]
add

`athletic.net###ATF_Remove_Ads`
