### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by Adwaid5048** [uBlockOrigin/uAssets#13836]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dgdrive.xyz/pzqfgs6egklj`

### Category

detection

### Describe the issue

The site asks to disable the adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-06-25-22-39-26-97_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/108191689/175783807-5d3659fb-c067-43f0-8ba0-06035e86df9a.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 81050
  cosmetic: 25923
  scriptlet: 17344
  html: 695
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32622-290, 11h.22m
    ublock-badware: 4219-3, 11h.21m
    ublock-privacy: 230-1, 7d.11h.10m
    ublock-abuse: 75-0, 7d.11h.9m
    ublock-unbreak: 1832-2, 11h.23m
    adguard-mobile: 7860-167, 11h.19m
    easylist: 67898-24898, 1d.8h.58m
    easyprivacy: 27264-590, 11h.20m
    urlhaus-1: 5260-0, 1h.47m
    plowe-0: 3647-3, 2d.7h.28m
    ublock-quick-fixes: 228-0, 1h.48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5650 ms (selfie)
  maxAssetCacheWait: 4950 ms
popupPanel: 
  blocked: 88
  blockedDetails: 
    a-ads.com: 1
    a-mx.com: 1
    adnxs.com: 1
    cloudflareinsights.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    id5-sync.com: 1
    imasdk.googleapis.com: 1
    quantumdex.io: 7
    vliplatform.com: 69
    vlitag.com: 4
```
</details>

**Comment by Procyon-b** [comment]
No detection for me.

**Comment by Adwaid5048** [comment]
Try it while downloading a file

**Comment by Procyon-b** [comment]
Got the message today (not yesterday). I'll look into it.

**Comment by Procyon-b** [comment]
Mhhhh, the detection is also there when I have ublock disabled...
