### ISSUE TITLE
[nsfw] mail.ru: ads

### ISSUE THREAD

**Issue by barmaglot18** [uBlockOrigin/uAssets#13835]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.ru/`

### Category

ads

### Describe the issue

Hello.
Suddenly, advertising began to appear on the mail ru page, and in the mail itself everything is in order.
Advertising looks like a separate block above the line with the news, in the upper right corner there is an inscription Direct. Advertising is contextual
<img width="1311" alt="Снимок экрана 2022-06-25 в 18 02 51" src="https://user-images.githubusercontent.com/35504348/175780348-1cac9f74-f018-4457-89b2-7693b6ea7117.png">
.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 97687
  cosmetic: 66417
  scriptlet: 18538
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 41870-8, 2d.56m
    easylist: 67938-65, 1h.35m
    easyprivacy: 27266-222, 1h.34m
    plowe-0: 3644-786, 12d.21h.22m
    ublock-abuse: 75-1, 1d.5h.6m
    ublock-badware: 4217-93, 1h.33m
    ublock-filters: 31931-139, 1h.16m
    ublock-privacy: 224-3, 1d.5h.5m
    ublock-quick-fixes: 229-47, 18h.16m
    ublock-unbreak: 1816-44, 1h.15m
    urlhaus-1: 5045-0, 18h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1483 ms (selfie)
  maxAssetCacheWait: 873 ms
popupPanel: 
  blocked: 613
  blockedDetails: 
    mail.ru: 503
    digitaltarget.ru: 1
    imgsmail.ru: 105
    tns-counter.ru: 2
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
Subscribe `RU counters` list too and see if helps

https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters

**Comment by barmaglot18** [comment]
did not help, the ad disappears for 2 seconds and reappears.(

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by barmaglot18** [comment]
Thanks!

**Comment by barmaglot18** [comment]
The problem was solved more easily. Selected ads, right-clicked and selected adguard through the context menu and blocked it. Hooray!

**Comment by dimisa-RUAdList** [comment]
> I forced an update of my filter lists...

It wasn't done.

> RUS-0: 41870-8, 2d.56m

> I am not using another content blocker along uBO...

Obviously not.

> Selected ads, right-clicked and selected **adguard** through the context menu and blocked it.

The simultaneous use of two or more blockers leads to a conflict, as a result of which none of these blockers does its job properly.

This is exactly what happens on mail.ru when uBlock Origin works together with AdGuard.
