### ISSUE TITLE
vote.mainichi.jp: breakage

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#13834]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vote.mainichi.jp/26san/result`

### Category

breakage

### Describe the issue

Vote compass graphs are not displayed. (See screenshot)
Allowing this script seems to work fine.
`@@||widgets.outbrain.com/outbrain.js$script,domain=vote.mainichi.jp`

ping @Yuki2718 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし](https://user-images.githubusercontent.com/86018494/175764136-f44c7abb-7a31-4419-9829-c5ef08664f71.png)

![タイトルなし1](https://user-images.githubusercontent.com/86018494/175764137-3da2ad89-95bb-4053-a2ab-ff47cec72f11.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 88666
  cosmetic: 116598
  scriptlet: 21787
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 646-13, now
    block-lan: 43-0, now
    fanboy-annoyance: 73928-227, now
    ublock-annoyances: 4468-47, now
  default: 
    user-filters: 38-0, never
    JPN-1: 7412-9, now
    easylist: 67930-123, now
    easyprivacy: 27264-145, now
    plowe-0: 3644-788, now
    ublock-abuse: 75-0, now
    ublock-badware: 4216-93, now
    ublock-filters: 31931-135, now
    ublock-privacy: 224-12, now
    ublock-quick-fixes: 229-50, now
    ublock-unbreak: 1814-55, now
    urlhaus-1: 5056-0, now
filterset (user): [array of 42 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 305 ms (selfie)
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    mainichi.jp: 1
    cxense.com: 1
    facebook.net: 1
    google-analytics.com: 1
    outbrain.com: 1
```
</details>

**Comment by Yuki2718** [comment]
It seems the issue is caused by redirect resource. @gorhill

**Comment by mapx-** [comment]
better

```
||widgets.outbrain.com/outbrain.js$script,redirect-rule=outbrain-widget.js:5,badfilter
||widgets.outbrain.com/outbrain.js$script,redirect-rule=outbrain-widget.js:5,domain=~mainichi.jp
```
