### ISSUE TITLE
forocoches.com | blocking the user's own avatar in the front page

### ISSUE THREAD

**Issue by Percle1** [uBlockOrigin/uAssets#1383]
# URL(s) where the issue occurs

forocoches.com

# Describe the issue

Title basically. See screenshots for visuals. I'm not the only one getting this trouble. It's the biggest spanish forum.

# Screenshot(s)

uBlock enabled
https://i.imgur.com/8pbbJtx.png

uBlock disabled
https://i.imgur.com/6Ve23kP.png

# Versions

- Browser/version: [Opera/50]
- uBlock Origin version: [1.14.24]

# Settings

None. I reinstalled it to make sure it wasn't my fault.

# Notes

The forum requires registration, and it's invite only. This reddit guy helped me and helped me find the issue: https://www.reddit.com/r/uBlockOrigin/comments/7swr6m/how_do_i_turn_off_this/

This is causing the trouble:
`forocoches.com#@##AutoNumber1 > tbody > tr > td:nth-of-type(3)
`
from EasyList spanish

**Comment by Percle1** [comment]
btw I won't back to this account, I made it so i could post the issue

**Comment by okiehsch** [comment]
fyi @diaux

**Comment by diaux** [comment]
Thanks for reporting! I removed the conflicting rule.
