### ISSUE TITLE
ads.reddit.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#13848]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://ads.reddit.com

### Describe the issue

Page detect anti-adblock, to login possible use normal account and create business profile.

### Screenshot(s)

[Screenshot_20220626-183923_Firefox](https://user-images.githubusercontent.com/35370833/175824728-9a49d139-83c6-45c4-86ac-e6878e9006dd.jpg)

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 102 on Android 12

### Settings

- enabled Polish regional lists

### Notes

It should be fixed to similar glitch on `ads.allegro.pl` a few years ago (2018?)

Maybe detected by @Kolor33

**Comment by krystian3w** [comment]
My switch account pages `https://ads.reddit.com/account/gba7ibsd/accounts` / `https://ads.reddit.com/account/9rm9yzjy/accounts` need something like:

`@@||ads-api.reddit.com/api/v2.0/accounts/*$xhr,domain=ads.reddit.com`

without page generate fake error 500.

But this may need disable uBo as uBo users may no create 3-party ads on Internet (only self-promo e.g. on own small blogs).

**Comment by mapx-** [comment]
if I add

`@@||ads-api.reddit.com/api/v2.0/accounts/*$xhr,1p`

it's all ok ?

**Comment by krystian3w** [comment]
then works switch function (without fake error 500) but in right corner I see network error requests:

https://user-images.githubusercontent.com/35370833/175826413-825eecb3-171d-4c53-ba44-f62edfd742a6.png - maybe need some noopjs and noop.txt due EL and EP filtering.

Works invite new persons.

I don't see back anti-adblock after allow api form `/accont/` catalog.

**Comment by mapx-** [comment]
ok, let me know if you tested a set of working filters
