### ISSUE TITLE
cut-y.net: detection

### ISSUE THREAD

**Issue by lakshits11** [uBlockOrigin/uAssets#13842]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cut-y.net/jI8R`

### Category

detection

### Describe the issue

Shows adblocker detected. Also tried removing all the filterlists but still adblocker detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[![https://imgur.com/Wd5t4x2.png](https://imgur.com/Wd5t4x2.png)](https://imgur.com/Wd5t4x2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 1275466
  cosmetic: 190456
  scriptlet: 41349
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    plowe-0: null
  added: 
    https://abp.oisd.nl/: 371986-0, 12h.36m
    https://hosts.oisd.nl/: 1076913-358239, 12h.35m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 42m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23783-26, 2d.3h.17m
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt: 244-211, 43m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-61, 2d.11h.43m
    https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt: 300805-172954, 20h.15m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-42, 1d.3h.3m
    https://www.i-dont-care-about-cookies.eu/abp/: 25081-227, 2d.3h.16m
    adguard-annoyance: 54363-2013, 1d.18h.54m
    adguard-social: 17727-1085, 1d.18h.55m
    adguard-spyware: 25819-14776, 1d.18h.56m
    adguard-spyware-url: 646-13, 1d.18h.57m
    fanboy-annoyance: 73689-12996, 5d.14h.2m
    ublock-annoyances: 4469-245, 1d.18h.58m
  default: 
    user-filters: 34-1, never
    easyprivacy: 27261-14387, 1d.18h.19m
    ublock-abuse: 75-7, 10d.15h.8m
    ublock-badware: 4216-510, 1d.18h.46m
    ublock-filters: 31878-3542, 2d.3h.19m
    ublock-privacy: 224-70, 10d.15h.7m
    ublock-quick-fixes: 229-6, 12h.34m
    ublock-unbreak: 1813-55, 2d.3h.18m
    urlhaus-1: 5168-1093, 41m
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 846 ms (selfie)
  maxAssetCacheWait: 2602 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    simoolkankrej.com: 1
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings / filter lists, **don't add any other list** and test again

**Comment by lakshits11** [comment]
Basically it were some 3rd party scripts. As soon as i blocked them like this, the page loaded.

![image](https://user-images.githubusercontent.com/54276661/175817820-e9f6a969-a50b-4db4-b197-634c3dbef889.png)
