### ISSUE TITLE
9gag.com: breakage

### ISSUE THREAD

**Issue by emmandyar** [uBlockOrigin/uAssets#13840]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9gag.com/`

### Category

breakage

### Describe the issue

When ublock is enabled in firefox mobile, you can't comment on any of the site's sections. Tapping the comment textbox doesn't bring the new comment page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 101
filterset (summary): 
  network: 91328
  cosmetic: 62171
  scriptlet: 18976
  html: 689
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 73692-42982, 6d.7h.38m
    fanboy-social: 23253-13656, 3d.22h.53m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32566-344, 19h.12m
    ublock-badware: 4219-3, 17h.19m
    ublock-privacy: 230-1, 4d.21h.33m
    ublock-abuse: 75-0, 4d.21h.32m
    ublock-unbreak: 1832-2, 19h.11m
    adguard-mobile: 7860-167, 18h.53m
    easylist: 67929-24993, 19h.13m
    easyprivacy: 27264-608, 15h.54m
    urlhaus-1: 5260-0, 2m
    plowe-0: 3647-3, 4d.1h.13m
    spa-0: 3898-220, 18h.52m
    spa-1: 4547-184, 15h.53m
    ublock-quick-fixes: 228-0, 3h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 611 ms (selfie)
  maxAssetCacheWait: 620 ms
popupPanel: 
  blocked: 58
  blockedDetails: 
    9gag.com: 11
    amazon-adsystem.com: 1
    cloudflareinsights.com: 5
    consensu.org: 5
    doubleclick.net: 1
    facebook.net: 5
    google-analytics.com: 1
    googlesyndication.com: 2
    gstatic.com: 7
    privacymanager.io: 5
    pubmatic.com: 5
    quantserve.com: 5
    stakingsmile.com: 5
```
</details>

**Comment by mapx-** [comment]
add & test

`9gag.com#@#.overlay-layer`

@ryanbr

**Comment by Zero-G-Sys** [comment]
Yes, that fixed the problem, can comment in a post now.
