### ISSUE TITLE
[nsfw] pornolab.net: ads

### ISSUE THREAD

**Issue by kazemkhan123** [uBlockOrigin/uAssets#13846]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://pornolab.net/forum/index.php`

### Category

ads

### Describe the issue

There are ads on top and left of the websites. removing with element picker may break the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82039
  cosmetic: 43897
  scriptlet: 17323
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32649-82, 6m
    ublock-badware: 4221-3, 5m
    ublock-privacy: 230-0, 4m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1829-0, 2m
    ublock-quick-fixes: 202-2, never
    easylist: 68049-561, never
    easyprivacy: 27172-578, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 735 ms
  maxAssetCacheWait: 265 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    dynspt.com: 3
    vsexshop.ru: 1
    yadro.ru: 1
```
</details>

**Comment by okiehsch** [comment]
Fixed in the regional russian list.
