### ISSUE TITLE
pururin.us [Pop-up] [NSFW]

### ISSUE THREAD

**Issue by lievedido** [uBlockOrigin/uAssets#1384]
### URL(s) where the issue occurs

`http://pururin.us/`

### Describe the issue

Go to website and click anywhere.

### Versions

- Browser/version: Firefox 59.0b3
- uBlock Origin version: 1.14.24

### Settings

Default

**Comment by utlasidyo** [comment]
@mapx- Please update filter, issue popped up again.

**Comment by mapx-** [comment]
It seems to be a parked domain ?!

**Comment by utlasidyo** [comment]
@mapx- It's pururin.io now.

**Comment by utlasidyo** [comment]
@mapx- filter hides gallery and comments, example: https://pururin.io/gallery/37350/trymix
