### ISSUE TITLE
download.cnet.com: ads

### ISSUE THREAD

**Issue by Ali-Ferwez** [uBlockOrigin/uAssets#13841]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://download.cnet.com/Microsoft-Visual-Studio-2010-Ultimate/3000-2383_4-75450998.html`

### Category

ads

### Describe the issue

still shows unwanted/promotional video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 79373
  cosmetic: 44179
  scriptlet: 17340
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67870-50, 2d.5h.55m
    easyprivacy: 27257-122, 2d.5h.54m
    plowe-0: 3644-782, 7h.51m
    ublock-abuse: 75-0, 1d.2h.7m
    ublock-badware: 4211-93, 2d.5h.53m
    ublock-filters: 31879-105, 2d.5h.52m
    ublock-privacy: 224-3, 1d.2h.5m
    ublock-quick-fixes: 229-2, 15h.3m
    ublock-unbreak: 1811-42, 2d.5h.51m
    urlhaus-1: 5056-0, 19h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2014 ms (selfie)
  maxAssetCacheWait: 963 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    confiant-integrations.global.ssl.fastly.net: 1
    doubleclick.net: 2
    go-mpulse.net: 1
    google.com: 3
    googlesyndication.com: 1
    moatads.com: 1
    redventures.io: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
the right side video ? self-promo

add

`download.cnet.com##.c-avStickyVideo`

eventually for annoyances list @ryanbr  ?

**Comment by Ali-Ferwez** [comment]
What do you mean? Why I can't use element zapper mode to remove this?

**Comment by mapx-** [comment]
add the filter above in "my filters"

**Comment by Ali-Ferwez** [comment]
Thanks. Issue is now closed.
