### ISSUE TITLE
youtube.com: nuisance

### ISSUE THREAD

**Issue by crazymonkyyy** [uBlockOrigin/uAssets#13849]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=iJyZsR7uP-M&list=RDiJyZsR7uP-M&start_radio=1`

### Category

nuisance

### Describe the issue

youtube tv pop up ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-06-26-125926_679x211_scrot](https://user-images.githubusercontent.com/5334907/175829852-ff1cc457-57e2-4b36-a493-e0430f725b64.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 79882
  cosmetic: 44054
  scriptlet: 17293
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    easylist: 68684-50, 5d.42m
    easyprivacy: 27244-122, 5d.41m
    plowe-0: 3644-781, 15d.1h.34m
    ublock-abuse: 75-0, 7d.2h.7m
    ublock-badware: 4195-93, 5d.40m
    ublock-filters: 31832-109, 5d.39m
    ublock-privacy: 224-3, 7d.2h.6m
    ublock-quick-fixes: 228-2, 2d.20h.6m
    ublock-unbreak: 1812-42, 2d.20h.7m
    urlhaus-1: 4651-0, 2d.20h.5m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10021 ms (selfie)
  maxAssetCacheWait: 357 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    youtube.com: 15
    doubleclick.net: 2
    google.com: 2
    googlevideo.com: 3
    ytimg.com: 1
```
</details>

**Comment by mapx-** [comment]
Did you try enabling `Fanboy’s Annoyance` or `AdGuard Annoyances` ?

**Comment by mapx-** [comment]
Test

`youtube.com##.ytd-mealbar-promo-renderer`
