### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Chotat0** [uBlockOrigin/uAssets#13852]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Ads for YouTube rented movies are showing up while browsing channels and the home screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 79642
  cosmetic: 44198
  scriptlet: 17305
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32576-154, 2d.3h.33m
    ublock-badware: 4220-3, 1d.23h.29m
    ublock-privacy: 230-0, 11d.5h.28m
    ublock-abuse: 75-0, 11d.5h.27m
    ublock-unbreak: 1827-2, 2d.3h.32m
    easylist: 67930-503, 1d.23h.30m
    easyprivacy: 27262-580, 2d.3h.34m
    urlhaus-1: 5260-0, 1d.2h.43m
    plowe-0: 3645-3, 11d.5h.29m
    ublock-quick-fixes: 227-0, 1d.2h.44m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1151 ms
  maxAssetCacheWait: 5560 ms
popupPanel: 
  blocked: 589
  blockedDetails: 
    youtube.com: 323
    doubleclick.net: 4
    google.com: 247
    googlevideo.com: 15
```
</details>

**Comment by mapx-** [comment]
> Ads for YouTube rented movies

Maybe could be considered as self-promo.
 
However without a clear way to reproduce your "issue" => nothing to do.
Just use the element picker to create custom filters.

**Comment by Chotat0** [comment]
> > Ads for YouTube rented movies
> 
> Maybe could be considered as self-promo.
> 
> However without a clear way to reproduce your "issue" => nothing to do. Just use the element picker to create custom filters.

It happens on the home screen and the channel is "YouTube Movies". I don't understand how you can't replicate it, it happens nearly every time I use YouTube for the past week. What more can I give you to help you fix this? Element Picker blocked all videos from displaying on my Home screen on YouTube.

**Comment by mapx-** [comment]
maybe this filter from fanboy's annoyances list:

`youtube.com##.ytd-primetime-promo-renderer`
