### ISSUE TITLE
[nsfw] siska.video: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13850]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://siska.video/video.php?videoID=108340`

### Category

ads

### Describe the issue

Popups open up before the videos start. I think a good cleanup of this site is in order 👍🏻

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 435075
  cosmetic: 146881
  scriptlet: 35134
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41879-256, 1d.10h.57m
    adguard-generic: 65063-1293, 3d.11h.19m
    adguard-mobile: 7855-63, 3d.11h.19m
    curben-phishing: 25041-0, 2h.58m
    curben-pup: 219-0, 2h.56m
    fanboy-cookiemonster: 34826-96, 3d.11h.19m
    ublock-annoyances: 4469-69, 3d.11h.19m
  default: 
    FRA-0: 28912-64, 3d.11h.19m
    easylist: 67867-1046, 3d.11h.19m
    easyprivacy: 27257-598, 3d.11h.19m
    plowe-0: 3647-893, 3d.11h.19m
    ublock-abuse: 75-2, 3d.11h.19m
    ublock-badware: 4211-327, 3d.11h.19m
    ublock-filters: 31869-3604, 3d.11h.19m
    ublock-privacy: 224-3, 3d.11h.19m
    ublock-quick-fixes: 237-14, 2h.54m
    ublock-unbreak: 1813-83, 3d.11h.19m
    urlhaus-1: 5236-1, 2h.52m
filterset (user): [array of 2086 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 715 ms (selfie)
  maxAssetCacheWait: 811 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    hqq.tv: 1
    korall.xyz: 3
    lumupu.xyz: 1
    unpkg.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
korall.xyz##+js(nowoif)
```

**Comment by Procyon-b** [comment]
We'll have to wait. I can't do this myself.
