### ISSUE TITLE
restart problem

### ISSUE THREAD

**Issue by vjklein** [uBlockOrigin/uAssets#13859]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.raiplay.it/dirette/rai3`

### Describe the issue

the restart fuction doesn't work on this site when ublock is on. The strange think is that on others tv channel of this network it works perfectly. only rai 3 give me problem.

### uBlock Origin version

uBlock Origin: 1.43.0

### Browser name and version

firefox 101.0.1

### Settings

nothing

**Comment by mapx-** [comment]
add

`@@||analytics.edgekey.net/config/beacon-$xhr,domain=raiplay.it`

@ryanbr

**Comment by mapx-** [comment]
Test this 1

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=raiplay.it`
