### ISSUE TITLE
icutit.ca [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1385]
URL(s) where the issue occurs

`http://icutit.ca/vU0odOQJc`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
Bad Request
http://icutit.ca/vU0odOQJc

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
