### ISSUE TITLE
zen.yandex.ru: ads

### ISSUE THREAD

**Issue by Ancrom** [uBlockOrigin/uAssets#13866]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zen.yandex.ru/`

### Category

ads

### Describe the issue

ads in the player while watching a video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 98005
  cosmetic: 66565
  scriptlet: 18566
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    RUS-0: 41879-8, 1d.22h.11m
    easylist: 68089-64, 18h.34m
    easyprivacy: 27282-222, 18h.30m
    plowe-0: 3648-787, 11d.23h.15m
    ublock-abuse: 75-1, 7d.16h.2m
    ublock-badware: 4217-93, 18h.33m
    ublock-filters: 32018-141, 18h.32m
    ublock-privacy: 224-3, 7d.16h.3m
    ublock-quick-fixes: 229-47, 1d.2h.34m
    ublock-unbreak: 1816-44, 18h.31m
    urlhaus-1: 5271-0, 1d.2h.35m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 204 ms (selfie)
  maxAssetCacheWait: 110 ms
popupPanel: 
  blocked: 317
  blockedDetails: 
    yandex.ru: 315
    serving-sys.ru: 1
    yandex.net: 1
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
subscribe `RU AdList: Counters` ~ >
https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters
