### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by MrXenBey** [uBlockOrigin/uAssets#13867]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/lilvayne`

### Category

ads

### Describe the issue

reklam çıkıyor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 81579
  cosmetic: 50434
  scriptlet: 17693
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-1, never
    TUR-0: 8337-59, 3d.3h.1m
    easylist: 67949-68, 3d.3h
    easyprivacy: 27266-127, 3d.2h.59m
    plowe-0: 3647-784, 7d.6h.13m
    ublock-abuse: 75-0, 7d.6h.11m
    ublock-badware: 4217-93, 3d.2h.58m
    ublock-filters: 31990-115, 3d.2h.57m
    ublock-privacy: 224-3, 7d.6h.7m
    ublock-quick-fixes: 237-47, 7h.18m
    ublock-unbreak: 1816-44, 3d.2h.56m
    urlhaus-1: 5454-0, 7h.17m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3430 ms (selfie)
  maxAssetCacheWait: 2046 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 26
```
</details>

**Comment by pplplo** [comment]
i have the same problem since today...there is an ad every time i change the streamer ( sorry for my bad english)

**Comment by mapx-** [comment]
see https://github.com/pixeltris/TwitchAdSolutions#scripts

duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
