### ISSUE TITLE
[solved] file-upload.com: automatically download APK

### ISSUE THREAD

**Issue by shruru** [uBlockOrigin/uAssets#13862]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.file-upload.com/tkmphpwmo9uc`

### Category

popups

### Describe the issue

Everytime you refresh the page, it downloads .APK file auto background, can't block it with uBlock
System, MacOS / Chrome v103

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 105396
  cosmetic: 121096
  scriptlet: 21851
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 74062-231, 12m
    ublock-annoyances: 4476-47, 11m
  default: 
    user-filters: 2-0, never
    CHN-0: 28591-91, 11m
    easylist: 68109-70, 12m
    easyprivacy: 27291-148, 12m
    plowe-0: 3644-784, 11m
    ublock-abuse: 75-0, 12m
    ublock-badware: 4232-93, 12m
    ublock-filters: 32019-151, 12m
    ublock-privacy: 224-11, 12m
    ublock-quick-fixes: 237-47, 12m
    ublock-unbreak: 1816-48, 12m
    urlhaus-1: 5454-0, 12m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 259 ms (selfie)
  maxAssetCacheWait: 214 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    alexametrics.com: 1
    d26adrx9c3n0mq.cloudfront.net: 2
    facebook.com: 1
    google-analytics.com: 1
    inklinkor.com: 1
    protectionabate.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`||file-upload.com^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation`

on the last page use middle click to download the file (clicking `Click here to download`)

**Comment by shruru** [comment]
@mapx- Thank you so ~~ much. You are a star. it works well. Thanks again! (sorry I am noob on any codes)
