### ISSUE TITLE
pelismkvhd.com => awlinks.live => detection

### ISSUE THREAD

**Issue by iban89** [uBlockOrigin/uAssets#13874]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`pelismkvhd.com`  => click one of ENLACES PÚBLICOS => awlinks.live => detection

### Category

detection

### Describe the issue

Page do not continius because ublock was detected, plugin is update and i do the steps above to try to solve but still detect ubloc

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![imagen](https://user-images.githubusercontent.com/28080809/176465505-59a4642b-43c8-45bb-9593-e195b87dca4f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 82391
  cosmetic: 49173
  scriptlet: 17536
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32632-92, 3d.2m
    ublock-badware: 4221-3, 3d.1m
    ublock-privacy: 230-0, 11d.8h.12m
    ublock-abuse: 75-0, 11d.8h.11m
    ublock-unbreak: 1829-2, 3d
    ublock-quick-fixes: 193-0, 32m
    easylist: 68032-663, 2d.23h.59m
    easyprivacy: 27270-597, 2d.23h.58m
    urlhaus-1: 4860-0, 30m
    plowe-0: 3647-3, 11d.8h.5m
    spa-0: 3899-2, 33m
    spa-1: 4547-105, 3d.3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 229 ms (selfie)
  maxAssetCacheWait: 146 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ghajini** [comment]
provide a proper url (from where you landed on this page)

`https://awlinks.live/` redirects to `google.com`

**Comment by iban89** [comment]
from here
[https://www.pelismkvhd.com/2022/06/asesino-sin-memoria-2022-1080p-hd-mkv-espanol-latino/](url)

**Comment by ghajini** [comment]
`awlinks.live#@#.adsbygoogle`

btw how this site work?

**Comment by iban89** [comment]
Is a "link protector", for example clic in download from googledrive link between site pelismkvhd and googledrive is that awlink.
Works "awlinks.live#@#.adsbygoogle"
