### ISSUE TITLE
kissfm.es

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#13876]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.kissfm.es/player/`

### Describe the issue

radio break

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 102.0

### Settings

![ff](https://user-images.githubusercontent.com/33556647/176480502-ff6a502d-4078-42d0-82f6-669b70b59219.PNG)

**Comment by mapx-** [comment]
@ryanbr EP issue `/comscore.`
