### ISSUE TITLE
chip.de: popups

### ISSUE THREAD

**Issue by MuhammetEminCakir** [uBlockOrigin/uAssets#13877]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chip.de/`

### Category

popups

### Describe the issue

Cookie warning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/64583157/176499069-993ad4d9-2917-4c4d-be65-1a8694d4fa8b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 126717
  cosmetic: 195075
  scriptlet: 34439
  html: 694
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 65230-5143, 1d.19h.50m
    adguard-spyware: 26187-923, 1d.19h.50m
    adguard-spyware-url: 647-14, 1d.19h.50m
    adguard-annoyance: 54354-3486, 1d.19h.50m
    fanboy-annoyance: 74058-270, 1d.19h.50m
    DEU-0: 5859-2, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32664-65, 1d.19h.51m
    ublock-badware: 4236-3, 1d.19h.50m
    ublock-privacy: 230-0, 1d.19h.50m
    ublock-abuse: 75-0, 1d.19h.50m
    ublock-unbreak: 1829-3, 1d.19h.50m
    ublock-quick-fixes: 188-0, 9h.34m
    easylist: 68089-634, 1d.19h.50m
    easyprivacy: 27282-10474, 1d.19h.50m
    urlhaus-1: 5145-0, 9h.33m
    plowe-0: 3644-3, 1d.19h.50m
    TUR-0: 8502-64, 1d.19h.50m
filterset (user): [empty]
trustedset: 
  removed: 
    opera-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1953 ms (selfie)
  maxAssetCacheWait: 914 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    chip.de: 4
    bf-ad.net: 1
    bf-tools.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Cookie banner will not be addressed in uAssets.

**Comment by JobcenterTycoon** [comment]
Please note: A few cookie banner can’t be blocked without breakage thats why a few pass through even with annoyance filterlists enabled. For security reasons uBlock Origin can’t autoclick.

**Comment by mapx-** [comment]
more: it's GDPR which we wont remove / block

**Comment by krystian3w** [comment]
Or CCPA if pages are pupular in USA.
