### ISSUE TITLE
dymontiger.livejournal.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13886]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dymontiger.livejournal.com/`

### Category

ads

### Describe the issue

An advertising platform is very intrusive.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/176705394-e55b209b-78c9-4a5c-b55d-ecac73402a0d.png)

![image](https://user-images.githubusercontent.com/50231020/176705456-822d85d1-2e6f-42cb-9e55-d96b45c57c05.png)

![image](https://user-images.githubusercontent.com/50231020/176705531-7ba81377-86e1-4c3e-8316-b6bab6230f91.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 430042
  cosmetic: 147148
  scriptlet: 35173
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41835-256, 22h.32m
    adguard-generic: 65180-1298, 3d.3h.40m
    adguard-mobile: 7904-64, 3d.3h.46m
    curben-phishing: 20139-0, 2h.28m
    curben-pup: 200-1, 2h.26m
    fanboy-cookiemonster: 34826-96, 7d.3h.59m
    ublock-annoyances: 4468-69, 3d.3h.42m
  default: 
    FRA-0: 29095-64, 3d.3h.44m
    easylist: 68052-1053, 3d.3h.38m
    easyprivacy: 27281-597, 3d.3h.36m
    plowe-0: 3647-895, 7d.3h.59m
    ublock-abuse: 75-2, 7d.3h.59m
    ublock-badware: 4217-328, 3d.3h.34m
    ublock-filters: 32012-3631, 3d.3h.32m
    ublock-privacy: 224-3, 7d.3h.59m
    ublock-quick-fixes: 191-14, 2h.24m
    ublock-unbreak: 1816-84, 3d.3h.30m
    urlhaus-1: 4857-1, 2h.22m
filterset (user): [array of 2087 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 4195 ms (selfie)
  maxAssetCacheWait: 502 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    livejournal.com: 1
    beeline.ru: 1
    rambler.ru: 2
    top100.ru: 1
```
</details>

**Comment by mapx-** [comment]
for the russian sites use always RU Counters list too

subscribe RU counters list
https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters

**Comment by mapx-** [comment]
This is a semi-official resource (also from RUAdList) - only recommended - to better combat some unpleasant "actors"
