### ISSUE TITLE
console.otc.t-systems.com: breakage

### ISSUE THREAD

**Issue by shaderecker** [uBlockOrigin/uAssets#13888]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://console.otc.t-systems.com/mrs/?region=eu-de&locale=en-us`

### Category

breakage

### Describe the issue

The page doesn't load the content from this url:

GET https://console.otc.t-systems.com/mrs/rest/api/v1/log?type=&start=1653861600&end=1656626400&content=&currentPage=1&pageSize=10 net::ERR_BLOCKED_BY_CLIENT

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/16366556/176783711-0936ea21-12cb-4678-a745-9be70b83f672.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 81546
  cosmetic: 48060
  scriptlet: 17368
  html: 0
listset (total-discarded, last updated): 
  added: 
    DEU-0: 5859-0, 13h.48m
  default: 
    user-filters: 0-0, never
    easylist: 68148-56, 1d.14h.28m
    easyprivacy: 27291-132, 1d.14h.27m
    plowe-0: 3653-783, 1d.14h.30m
    ublock-abuse: 75-0, 1d.14h.32m
    ublock-badware: 4222-93, 1d.14h.26m
    ublock-filters: 32036-122, 1d.14h.25m
    ublock-privacy: 224-3, 1d.14h.31m
    ublock-quick-fixes: 197-2, 13h.49m
    ublock-unbreak: 1816-45, 1d.14h.24m
    urlhaus-1: 4857-0, 13h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1339 ms (selfie)
  maxAssetCacheWait: 765 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    t-systems.com: 1
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/account%20required "or not to be"?

**Comment by krystian3w** [comment]
Also check neutralize by empty file:

`||console.otc.t-systems.com/mrs/rest/api/v1/log$redirect=noop.txt`

later:

`@@||console.otc.t-systems.com/mrs/rest/api/v1/log$xhr` `# I mean this is only xhr`

**Comment by shaderecker** [comment]
> [ account required](https://github.com/uBlockOrigin/uAssets/labels/account%20required) "or not to be"?

Yes, an account is needed.

**Comment by krystian3w** [comment]
In my filters tab into Dashboard:

https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters

**Comment by mapx-** [comment]
@shaderecker could you provide a test account and the steps to get that issue (explaining what functionality is really broken ) ?

**Comment by krystian3w** [comment]
Maybe @okiehsch have account.

**Comment by okiehsch** [comment]
@krystian3w I don't have an account.
@shaderecker You can mail the credentials to [testdaily@protonmail.com](mailto:testdaily@protonmail.com) or wait for `mapx-` to respond.

**Comment by okiehsch** [comment]
Actually looking at the error message that request is probably blocked by 
`/log?type=` in `EasyPrivacy`.
Does adding 
`@@||console.otc.t-systems.com/mrs/rest/api/v1/log?type=$script,1p` 
to your filter list work?

**Comment by shaderecker** [comment]
No, adding it doesn't solve the issue.

**Comment by mapx-** [comment]
@shaderecker just send the credentials to the mail above

**Comment by okiehsch** [comment]
If you update the `uBO-unbreak` list the site should load as expected.

**Comment by shaderecker** [comment]
Wow, thanks for working on it so quickly @okiehsch  🎉
I just updated the list and now it work correctly 😁
Awesome!

**Comment by okiehsch** [comment]
Gern geschehen.

**Comment by krystian3w** [comment]
Possible move to fix fixes due https://github.com/easylist/easylist/commit/a2d6073fcd4b78f6e7681317eba5fdd420b3fb45

**Comment by mapx-** [comment]
@ryanbr  script => xhr ?
