### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by LightShaft** [uBlockOrigin/uAssets#13887]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://megaup.net/18wD/Devil.May.Cry.HD.Collection.part2_(2).rar`

### Category

detection

### Describe the issue

Detecting ublock origin ... again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 125312
  cosmetic: 164533
  scriptlet: 24811
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 6h.49m
    adguard-annoyance: 54393-87, 1d.20h.36m
    adguard-spyware: 26201-857, 1d.20h.35m
    adguard-spyware-url: 647-13, 1d.20h.34m
    block-lan: 43-0, 22d.8h.41m
    fanboy-annoyance: 74106-3104, 4d.1h.47m
    fanboy-cookiemonster: 35020-35020, 4d.1h.46m
    ublock-annoyances: 4476-192, 1d.20h.31m
  default: 
    user-filters: 9-2, never
    FRA-0: 29095-24, 1d.20h.37m
    easylist: 68137-198, 1d.20h.33m
    easyprivacy: 27290-10429, 1d.20h.32m
    plowe-0: 3647-863, 9d.6h.26m
    ublock-abuse: 75-1, 10d.21m
    ublock-badware: 4232-103, 1d.20h.30m
    ublock-filters: 32036-615, 1d.20h.29m
    ublock-privacy: 224-49, 10d.17m
    ublock-quick-fixes: 195-2, 22h.50m
    ublock-unbreak: 1817-65, 1d.20h.28m
    urlhaus-1: 4860-0, 22h.49m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 31 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2066 ms (selfie)
  maxAssetCacheWait: 645 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    megaup.net: 2
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
    societingna.info: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me, maybe its caused by one of the user filter you added.

PS: You should remove `https://www.joinhoney.com/whitelist/honey-smart-shopping.txt` it whitelist a ton of ad and tracking server

**Comment by krystian3w** [comment]
> ` 0-0, 6h.49m`

List are banned as recommended @MasterKia:

https://github.com/uBlockOrigin/uAssets/commit/d83242fc3b4f705c11e008501220b4fd336bd765

https://github.com/uBlockOrigin/uAssets/blob/d83242fc3b4f705c11e008501220b4fd336bd765/filters/badlists.txt#L18-L19

**Comment by LightShaft** [comment]
I've disabled this list but it still doesn't work, not with this link at least https://megaup.net/4cx6n/TLOZ-MM-EUR-DecrTD-Ziperto.rar

Tried disabling almost all lists, leaving only all the integrated, but then it doesn't block everything, added then just « Easylist », blocked everything but I can't pass the bypass

I genuinely don't get how you get that working

**Comment by mapx-** [comment]
reset uBO to default settings, don't add any other list, disable other extensions, test again

**Comment by LightShaft** [comment]
Couldn't find the culprit but now it works, thanks for your big help and sorry for the bother

**Comment by krystian3w** [comment]
Also possible reinstall uBO if database was damaged  (sometimes in Chrome, rarely in Firefox) and this recover anti-adblock.
