### ISSUE TITLE
herbarien.uzh.ch: breakage

### ISSUE THREAD

**Issue by larsgw** [uBlockOrigin/uAssets#13880]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.herbarien.uzh.ch/en/herbarien-zzt/sammler-details.html?id=8671`

### Category

breakage

### Describe the issue

This website holds information on the Herbaria in Zürich. Part of that information is a record of who collected the specimens in the herbaria. These people are called "collectors" ("sammler" in German). The page tries to display this information by calling an internal API with URLs like `https://www.herbarien.uzh.ch/static/manager/app/src/view/web/collector.php?id=8671`. According to the logger, this is blocked by the EasyPrivacy with the filter `/collector.php?`, leading to an empty page (other than headers, sidebars, etc.).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220629_221208](https://user-images.githubusercontent.com/14018963/176536136-9a4c838d-97bb-43d3-91af-2a8986d9bccd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 80098
  cosmetic: 45963
  scriptlet: 17371
  html: 0
listset (total-discarded, last updated): 
  added: 
    NLD-0: 2360-11, 11h.58m
  default: 
    user-filters: 1-0, never
    easylist: 68160-54, 2h.51m
    easyprivacy: 27284-123, 2h.54m
    plowe-0: 3647-783, 10d.2h.4m
    ublock-abuse: 75-0, 2h.56m
    ublock-badware: 4232-93, 2h.53m
    ublock-filters: 32017-154, 2h.52m
    ublock-privacy: 224-3, 2h.55m
    ublock-quick-fixes: 195-2, 2h.48m
    ublock-unbreak: 1825-58, 2h.50m
    urlhaus-1: 4860-0, 2h.49m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 77385 ms (selfie)
  maxAssetCacheWait: 2318 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    uzh.ch: 2
```
</details>

**Comment by mapx-** [comment]
`@@||herbarien.uzh.ch/static/manager/app/src/view/web/collector.php$frame,1p`

@ryanbr
