### ISSUE TITLE
ads on youtube

### ISSUE THREAD

**Issue by wrrrrrrrrrrr** [uBlockOrigin/uAssets#13899]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

youtube.com
https://www.youtube.com/watch?v=oEpg7s7l4WA

### Describe the issue

hi. this is the second time I've gotten an ad on youtube.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/108573511/176996423-b88f8d23-8ef7-4124-a9c3-351d5172c8b8.png)

### uBlock Origin version

 1.43.0

### Browser name and version

Opera GX LVL 4 (core: 88.0.4412.65)

### Settings

I've installed all sorts of anti-subscription popup filters for Polish websites. I can paste all my filters here if it's necessary.

### Notes

This is the second time it happened since I've ditched Youtube Premium. Let me know if anything is wrong with my form - this is the first time I'm doing this and English is not my first language. :>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by DoorCar** [comment]
@wrrrrrrrrrrr Did this occur immediately after opening your browser (for example, with saved tabs?). If yes, refreshing the webpage may be a fix, I think.

**Comment by krystian3w** [comment]
In Chromium browser better no recover session on pages, due no possible cover this by https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded (legacy https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready).

Also what is anti-subscribiton:

https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PAF_pop-ups.txt
https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PAF_push.txt

?
