### ISSUE TITLE
poczta.o2.pl: breakage

### ISSUE THREAD

**Issue by ar-b** [uBlockOrigin/uAssets#13890]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poczta.o2.pl/w/`

### Category

breakage

### Describe the issue

In the right top corner account button with logout option stops being visible when ublock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8228302/176849790-cdc022b9-c1fd-4aec-94d8-6f6ed33e8a3b.png)
![image](https://user-images.githubusercontent.com/8228302/176850211-25cbbcf3-32a3-4eee-a4e2-ff7c09060c96.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 382018
  cosmetic: 52984
  scriptlet: 20263
  html: 696
listset (total-discarded, last updated): 
  added: 
    https://hole.cert.pl/domains/domains_adblock.txt: 301060-23, 1h.29m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt: 589-1, 21h.33m
    ublock-annoyances: 4475-7, 1d.13h.42m
    POL-0: 7851-612, 1h.30m
    POL-2: 1279-13, 1d.13h.39m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32323-74, 1d.13h.41m
    ublock-badware: 4236-3, 2d.1h.49m
    ublock-privacy: 230-0, 1d.17h.43m
    ublock-abuse: 75-0, 2d.5h.50m
    ublock-unbreak: 1838-0, 1d.13h.40m
    easylist: 68170-669, 1d.1h.38m
    easyprivacy: 27290-581, 21h.34m
    urlhaus-1: 4857-0, 21h.32m
    plowe-0: 3647-3, 10d.2h.48m
    ublock-quick-fixes: 201-2, 1h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 1770 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    wp.pl: 3
```
</details>

**Comment by mapx-** [comment]
@krystian3w can you help here ? do you have an account ?

**Comment by ar-b** [comment]
I'm not familiar with filter format but as far as I understand what ublock logger is showing, the issue is that the scripts required to display that part are blocked because they have quite unusual name format - js file with account/logout secion is this seleced one starting with MTI).
ublock disabled:
![image](https://user-images.githubusercontent.com/8228302/176869954-8973f9f3-0fe2-4d47-ba35-38609fd8767d.png)
ublock enabled - logger:
![image](https://user-images.githubusercontent.com/8228302/176870105-31a7d220-45c2-4de2-8885-33e5c4fe28ef.png)
scripts section from <head> tag:
`<script crossorigin src="https://www.wp.pl/Mjg1MzcxYgsGUztJTANvHkULbxkTEBIZE1VvVkEnb1BFbhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4bhIlPCcSNThuEiU8JxI1OG4SJTwnEjU4E2FYFlp3SEhGPRAQFCQISEY9EBAUJAhKQiobE1YnGUVM" id="wpjslib"></script> <script src="https://www.wp.pl/MTIxMzNhYjUoGjtJYRNvIGtCbxk-ABI7Jx0hFSkBI3ZlWhJYdEoSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlETcSCxYnEiURNxILFicSJRE3EgsWJxIlbERvIWtCb1UhBig4Jh8kFGEHISMgHCofOkYnJ2sF"></script> <script src="manifest-bundle_7c3ceb9d.js"></script> <script src="vendor-bundle_7c3ceb9d.js"></script> <script src="universal-bundle_7c3ceb9d.js"></script> <script src="bundle-bundle_7c3ceb9d.js"></script>`

**Comment by mapx-** [comment]
@ar-b if you add

`/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl,badfilter`

does it work ? do you see ads previously blocked ?

**Comment by ar-b** [comment]
@mapx- , it works, but as you anticipated - some of blocked ads are now visible.

For example those loaded from this URL:
`https://www.wp.pl/a3M1NTI4TlIsUzhnZk9DR28LbCYiFk0REhN0dhZrPmwSbhELFms-bBJuEQsWaz5sEm4RCxZrPmwSbhELFms-bBJuEQsWaz5sEm4RCxZrPmwSbhELFms-bBJuEQsWaz5sEm4RCxZrPmwSbhELFms-bBJuEQsWaz5sEm4RCxZrPmwSbhELFms-bBJuEQsWaz5sEm4RCxZrPmwSbhELFms-bBJuEQtrGENGbwtsey5VBx0nQnEmPwlQFT5fczt7axFcLks6NRZbU2w9XRE6IRIRRSRVc2x9BARVfVUoNi8BVVZ1VythfQFUFT9UJT0tR1wBfgN_Y3kSFWUoQz09JlpccWtBJiAkWFxDIlI0ICgaDgFjQSJxe3IWFn93aCQhVRJbcBR8EiRVCF8-FHwSbAcnXyxTKzhsByUCa2EZFTpDXAJ0A35yGWMgQCUMf2RxBEdbJFYmGChNDkY5DH5yKkAYQygMJzogQAhSIRciNTBbFEdwRicwLBIxZAxuLzArUFwDa1AsICxHFQ4sVToxKlxEBA5hD3l4BUQEDnBrZwtVBUcoUiZxfncxYQocfG1-BEQEDnNrZwtVBUcoUiZxfncxYQocfWZ9BEQEDnBrZwtVBUcoUiZxfncxYQocfWB_DEQEDnBrZwtVBUcoUiZxfncxYQocfWB6BUQEDnJrZwtVEUMhWC01PV0OXWgGDRoZGVAHfQZrYwp1RAAMdxwRDBIVZShDfGkKEgBXO2IiOz1HXAN4AWtmCgRQBWgDDWR5B0QBDgF7Z2wGIgN9BmtmCgRRB2gDDWR8AEQBDgF8ZmwGIgN_AmtmCgRTB2gDDWR7AUQBDgF8YmwGIgN_BmtmCgRTAmsUfBIkVQhfPhR8EmwHJ18sUys4dAVHQD1YIGkmVlQALEMtO29WAkVwA2wp`

![image](https://user-images.githubusercontent.com/8228302/176874673-d68611fd-18b0-4a01-81a4-e8cf20e74019.png)

**Comment by mapx-** [comment]
keep the filter above and add this 1 too

`/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,900}/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl`

test again for breakage + ads

**Comment by ar-b** [comment]
Unfortunatelly this breaks the logout button again (ads are not visible as well). In logger I can see that thie filter is applied anyway because the `{200,900}` match is greedy and not doing any lookbehind lookup.

When I changed it to a few more characters match and added end of line matching then logout button is visible but ads are not shown - I'm not sure how long this will work though becaue it will probably break when they regenerate names of those scripts files.

`/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl,badfilter`
`/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,915}$/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl`

**Comment by mapx-** [comment]
ok, for now we can add in quick fixes

```
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,}/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl,badfilter
/^https:\/\/[a-z]{2,14}\.wp\.pl\/[a-zA-Z0-9_-]{200,915}$/$script,domain=nowy.tlen.pl|poczta.o2.pl|profil.wp.pl
```

**Comment by krystian3w** [comment]
You can safe disable 1login od WP and header buttons back.

Follow: https://github.com/MajkiIT/polish-ads-filter/issues/21075
