### ISSUE TITLE
webmail.freenet.de: breakage

### ISSUE THREAD

**Issue by dave11112222** [uBlockOrigin/uAssets#13896]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://webmail.freenet.de/web/`

### Category

breakage

### Describe the issue

The mail programm is loading forever after login. After deactivating uBO it instantly loads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 81672
  cosmetic: 48130
  scriptlet: 17331
  html: 696
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32694-52, now
    ublock-badware: 4236-3, now
    ublock-privacy: 230-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1846-2, now
    ublock-quick-fixes: 201-0, now
    easylist: 68254-586, now
    easyprivacy: 27302-591, now
    urlhaus-1: 4896-0, now
    plowe-0: 3646-3, now
    DEU-0: 5860-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 320 ms
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by gwarser** [comment]
freenet.de#@#^script:has-text(===):has-text(/[\w\W]{16000}/)
