### ISSUE TITLE
odysee.com: ads

### ISSUE THREAD

**Issue by vekrixiblez** [uBlockOrigin/uAssets#13895]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://odysee.com/@TecnophonePro:c/nuevo-poco-x4-gt-anuncio-oficial-%F0%9F%A4%AF-lo:0`

### Category

ads

### Describe the issue

En el video no bloquea los anuncios.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82602
  cosmetic: 49282
  scriptlet: 17591
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68221-50, 5h.5m
    easyprivacy: 27299-122, 5h.4m
    plowe-0: 3647-783, 8d.7h.11m
    spa-0: 3899-36, 9h.9m
    spa-1: 4551-171, 5h.6m
    ublock-abuse: 75-0, 8d.7h.9m
    ublock-badware: 4232-93, 5h.3m
    ublock-filters: 32071-167, 5h.2m
    ublock-privacy: 224-3, 5h.1m
    ublock-quick-fixes: 203-2, 9h.8m
    ublock-unbreak: 1831-46, 5h
    urlhaus-1: 4868-0, 9h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 264 ms (selfie)
  maxAssetCacheWait: 453 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    odysee.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    odycdn.com: 1
    unrulymedia.com: 2
```
</details>

**Comment by DoorCar** [comment]
@vekrixiblez I found an ad that seems to be part of the video; I don't think uBO can block it.
