### ISSUE TITLE
ebay.fr: nuisance

### ISSUE THREAD

**Issue by AR404lab** [uBlockOrigin/uAssets#13892]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ebay.fr/itm/203569412724?hash=item2f65aeba74:g:nb8AAOSw4e9hHZd3&amdata=enc%3AAQAHAAAA8DLQKagaGBnf3zMwjzH2RBE1ESXmAQA8l1dALT5oMa5KICmd8JRClnUR3NJgBhqBlf%2BJZvYpXnIyDlT1OliB3qKLDQfYj5RiX76ytoWZkx73P%2BrD89sFTZLvH46dnDT7GTuUqD5TfS7jTxhK1yUKXiiY%2BjIsXKjgiKs%2Fe2bueB27l1rg%2FQNOMk4xHy5Yy2v4UpmUb59J9qhX1y3rFD9ou7ZH2oWDjZACDfj9%2FswwSLKdo90ItQ7C77eFRFISK88c9Y2MpatGTG4IEaDRxVM1lJadsIBIGlldUtcvLAsP2sapqlmRGF5fi8tzm5ZrOmUUEA%3D%3D%7Ctkp%3ABFBMvqSlmbdg`

### Category

nuisance

### Describe the issue

Hello, I have a problem (On FireFox) with the filter on all eBay products indeed look at the text in description it seems distorted it when I disable Ublock it works fine. Do you have any idea knowing that I have already reset the default settings etc.. 

### Screenshot(s)
![Sans titre](https://user-images.githubusercontent.com/97963753/176894241-8c5afdd1-1f59-4e05-acce-bb17b878e301.png)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 101430
  cosmetic: 52900
  scriptlet: 17231
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32409-32, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-2, never
    easylist: 68049-584, never
    easyprivacy: 27172-579, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-3, never
    FRA-0: 29107-491, 7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8764 ms
  maxAssetCacheWait: 462 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    ebay.fr: 7
    ebay.com: 11
    ebayrtm.com: 2
    go-mpulse.net: 2
    perfdrive.com: 4
```
</details>

**Comment by AR404lab** [comment]
![Sans titre](https://user-images.githubusercontent.com/97963753/176892460-7e63f3d3-1889-41e8-889d-91e808449c2b.png)

**Comment by mapx-** [comment]
Force an update of all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) 

then test again

**Comment by AR404lab** [comment]
> Force an update of all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
> 
> then test again

I cleared the cache again and reset the settings of Ublock always the same problem

**Comment by mapx-** [comment]
only update the lists, I see `never` on all your lists

**Comment by mapx-** [comment]
does this help ?

`@@||ebay.fr^$cname`

**Comment by AR404lab** [comment]
![image](https://user-images.githubusercontent.com/97963753/176900958-db464040-2cb7-45a4-9c3c-1a4dc98dbd7a.png)

**Comment by AR404lab** [comment]
> @@||ebay.fr^$cname

Added but still same .

**Comment by mapx-** [comment]
open the logger then repeat again the steps to get the issue, post here all blocked items (you can see in the logger - you can select only the blocked items in the box search)

**Comment by mapx-** [comment]
it seems to be an issue only with firefox

**Comment by mapx-** [comment]
Test 

`@@||ebay.fr^$ghide`

**Comment by AR404lab** [comment]
doesnt work :(

**Comment by AR404lab** [comment]
I also tried it and I can confirm that it doesn't work for me, I don't know what to do anymore

**Comment by mapx-** [comment]
I'll add it only for firefox

**Comment by Yuki2718** [comment]
May possibly be too permisive, particularly as the issue happens only to OP and not to others so far.
@AR404lab Can you help us to identify the exact cause? Add
```
@@*$image,ghide,domain=ebay.*,badfilter
@@||ebay.^$ghide
```
to partly counter the fix and then test
`@@/roverclk/*`
, if the problem persists, change to `@@/roverimp/*`, rinse and repeat until you ends up allowing all blocked image requests.

**Comment by mapx-** [comment]
I'm able to reproduce the issue, unfortunately only whitelisting (no redirecting works) is working

**Comment by Yuki2718** [comment]
Okay then, thanks.

**Comment by Yuki2718** [comment]
@AdamWr AGTPF also blocks them.

**Comment by AR404lab** [comment]
The command line had solved the problem 



> May possibly be too permisive, particularly as the issue happens only to OP and not to others so far. @AR404lab Can you help us to identify the exact cause? Add
> 
> ```
> @@*$image,ghide,domain=ebay.*,badfilter
> @@||ebay.^$ghide
> ```
> 
> to partly counter the fix and then test `@@/roverclk/*` if the problem persists, change to `@@/roverimp/*`, rinse and repeat until either the problem goes away or you ends up allowing all blocked image requests in the log.

but as of today the problem has reappeared.  😥
