### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by nomaddc** [uBlockOrigin/uAssets#13897]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/a/d7WX7oQ`

### Category

breakage

### Describe the issue

does not display

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 576169
  cosmetic: 152517
  scriptlet: 35614
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1d.19h.58m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 2d.12m
    https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt: 421307-2346, 1d.19h.56m
    https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt: 15787-4, 1d.19h.54m
    https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt: 1703-4, 1d.19h.55m
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.19h.57m
    JPN-1: 7439-22, 1d.20h.11m
    adguard-annoyance: 54459-73, 1d.20h.10m
    adguard-generic: 65347-747, 1d.20h.9m
    adguard-mobile: 7913-334, 1d.20h.8m
    adguard-social: 17771-862, 1d.20h.7m
    adguard-spyware: 26210-1821, 1d.20h.6m
    adguard-spyware-url: 648-13, 1d.20h.5m
    block-lan: 43-0, 22d.5h.6m
    dpollock-0: 10378-2625, 3h.49m
    fanboy-thirdparty_social: 69-3, 4d.22m
    ublock-annoyances: 4477-184, 1d.20h.2m
  default: 
    easylist: 68170-1725, 1d.20h.4m
    easyprivacy: 27290-10759, 1d.20h.3m
    plowe-0: 3647-1831, 9d.4h.57m
    ublock-abuse: 75-0, 9d.21h.11m
    ublock-badware: 4232-328, 1d.20h.1m
    ublock-filters: 32065-3769, 1d.20h
    ublock-privacy: 224-45, 9d.21h.7m
    ublock-quick-fixes: 203-14, 19h.51m
    ublock-unbreak: 1828-111, 1d.19h.59m
    urlhaus-1: 4868-2, 19h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 28 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1758 ms (selfie)
  maxAssetCacheWait: 1643 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    imgur.com: 4
    alexametrics.com: 1
    ccgateway.net: 1
    consensu.org: 1
    facebook.net: 1
    google-analytics.com: 1
    media-lab.ai: 1
    primis.tech: 1
    quantserve.com: 1
    scorecardresearch.com: 1
    sentry-cdn.com: 1
```
</details>

**Comment by gwarser** [comment]
Caused by "Lightswitch05's ads-and-tracking-extended.txt".
