### ISSUE TITLE
page broken i think

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#139]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
forward , backward button not working on itimes.com with ublock enabled

### One or more specific URLs where the issue occurs

http://ww.itimes.com/photo/sunny-leone-skips-own-documentary

### Screenshot in which the issue can be seen

![screenshot 37](https://cloud.githubusercontent.com/assets/20338483/18469630/8a75c8c8-79c6-11e6-9144-57f90e1913e8.png)

### Steps for anyone to reproduce the issue

1. go here itimes.com, i used no cosmetic filtering for this site as this site detects adblock

1. click any news e.g 
http://ww.itimes.com/photo/sunny-leone-skips-own-documentary

1. click forward button to see next pic,this time it will load pic but then
again click forward button it will not show(load next page) next story or pic, similarly backward button :it will not work 
![screenshot 37 1](https://cloud.githubusercontent.com/assets/20338483/18470065/8962d258-79c8-11e6-8e3d-acbaf85cecfb.jpg)

### Your settings

all default settings + antiadblock killer+ adblock warning removal+ 
no cosmetic filtering for itimes.com

- Browser/version: 

        mozilla firefox 48.02
        chrome Version 53.0.2785.101 m (64-bit)

- uBlock Origin version:  1.9.6(for firefox)
 1.9.4(for chrome)

##### Your filter lists
all default settings + antiadblock killer+ adblock warning removal+ 
no cosmetic filtering for itimes.com

##### Your custom filters (if any)
no cosmetic filtering for itimes.com

notes=

on disabling ublock origin i can load next pages by clicking forward button

**Comment by ghajini** [comment]
on clicking forward or backward button nothing happens

works fine with ublock disabled

**Comment by ghajini** [comment]
@gorhill  
console
![screenshot 39](https://cloud.githubusercontent.com/assets/20338483/18480887/ee71adfc-79f7-11e6-8cfe-b40745ef5a09.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/20338483/18480886/ee715690-79f7-11e6-8955-28d235e4f59a.png)

**Comment by mapx-** [comment]
add this filter
`@@||static.columbia.timesinternet.in/ad/commons/js/colombia_v2.js$script,domain=ww.itimes.com`

**Comment by ghajini** [comment]
basically whitelisting timesinternet.in for this site which is blocked by ublock origin
@mapx- 
thanx

**Comment by mapx-** [comment]
blocked by a filter in easylist, so you should report issues like this at easylist forum:
http://forums.lanik.us/
