### ISSUE TITLE
rollercoin.com: ads

### ISSUE THREAD

**Issue by dimarques-creator** [uBlockOrigin/uAssets#13903]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rollercoin.com/game/choose_game`

### Category

ads

### Describe the issue

until now it worked really good but for no reason it started to appear ads..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80879
  cosmetic: 47331
  scriptlet: 17594
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68271-50, 6h.51m
    easyprivacy: 27308-122, 6h.50m
    plowe-0: 3644-782, 8d.8h.40m
    spa-1: 4551-80, 6h.52m
    ublock-abuse: 75-0, 12d.12h.36m
    ublock-badware: 4232-93, 6h.49m
    ublock-filters: 32048-151, 6h.46m
    ublock-privacy: 224-3, 12d.12h.35m
    ublock-quick-fixes: 205-4, 6h.45m
    ublock-unbreak: 1831-45, 6h.48m
    urlhaus-1: 4915-0, 6h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 356 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    rollercoin.com: 1
    baidu.com: 1
    cloudflareinsights.com: 1
    facebook.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
try

`rollercoin.com##.banners-container`

if still other ads you have to indicate where you get them, add screenshot

**Comment by mapx-** [comment]
@ryanbr
