### ISSUE TITLE
wikihow.com: ads

### ISSUE THREAD

**Issue by Windos-7** [uBlockOrigin/uAssets#13902]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wikihow.com/Use-a-Green-Screen`

### Category

ads

### Describe the issue

Advertisements appear on some Wikihow articles. Position and content of the ad stays the same across refreshes. The article linked consistently has an ad on it, but I cannot find any other articles at the moment that have that type of ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[semi-nsfw ad?](https://i.redd.it/mcg9i3uft0991.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-564, now
    easyprivacy: 27172-101, now
    plowe-0: 3639-450, now
    ublock-abuse: 75-0, now
    ublock-badware: 4171-3, now
    ublock-filters: 31779-34, now
    ublock-privacy: 224-0, now
    ublock-quick-fixes: 202-2, never
    ublock-unbreak: 1797-30, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1469 ms
  maxAssetCacheWait: 14 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    wikihow.com: 10
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    pubmatic.com: 1
    videoplayerhub.com: 1
```
</details>

**Comment by ghajini** [comment]
i can reproduce

`wikihow.com###affiliate_2`
