### ISSUE TITLE
xbdeals.net: breakage - "buy" button not showing

### ISSUE THREAD

**Issue by imsys** [uBlockOrigin/uAssets#13904]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xbdeals.net/us-store/game/596714/bioshock-infinite-the-complete-edition`

### Category

breakage

### Describe the issue

The "Buy at Microsoft Store" button bellow the game image is being removed by ublock. A few days ago it was showing ok, I believe it is because of a filter update, because I just tried installing ublock in another browser and it worked as I would expect (blocking the ads, but showing the buy button), and then when I update the filters, the button disappears.

Note that the button uses a referral link using "click.linksynergy.com", so that's why it is getting blocked by the filter.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 79605
  cosmetic: 44475
  scriptlet: 17328
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32710-38, 1d.20h.42m
    ublock-badware: 4236-3, 5h.46m
    ublock-privacy: 230-0, 9d.21h.27m
    ublock-abuse: 75-0, 9d.21h.26m
    ublock-unbreak: 1846-2, 5h.45m
    easylist: 68271-583, 5h.44m
    easyprivacy: 27308-581, 5h.43m
    urlhaus-1: 4958-0, 17h.47m
    plowe-0: 3647-3, 9d.5h.22m
    ublock-quick-fixes: 201-0, 17h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 167 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    xbdeals.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by Procyon-b** [comment]
This is cause by this filter: `##a[href^="https://click.linksynergy.com/"]` in EasyList
Add this filter:
```
xbdeals.net#@#a[href^="https://click.linksynergy.com/"]
```

**Comment by imsys** [comment]
Thanks! That worked!

**Comment by mapx-** [comment]
@ryanbr
