### ISSUE TITLE
Doubleclick Cookie Allowed

### ISSUE THREAD

**Issue by AllanHigdon** [uBlockOrigin/uAssets#13905]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://en.softonic.com/windows/free-new-versions`

### Describe the issue

Allows a doubleclick.net cookie.
Specifically, it's securepubads.g.doubleclick.net

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 82011
  cosmetic: 43831
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68049-50, never
    easyprivacy: 27172-122, never
    plowe-0: 3639-781, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-91, never
    ublock-filters: 31779-94, never
    ublock-privacy: 222-2, never
    ublock-quick-fixes: 202-2, never
    ublock-unbreak: 1797-40, never
    urlhaus-1: 7285-0, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4672 ms
  maxAssetCacheWait: 773 ms
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7673
