### ISSUE TITLE
VOE Anti Adblock

### ISSUE THREAD

**Issue by HerzogVonWiesel** [uBlockOrigin/uAssets#13900]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://un-block-voe.net/e/q0lism2x9d7o
https://voe.bar/f/5d8yo8o74o7t
```

### Describe the issue

VOE seems to have patched the method used to bypass the anti adblock used by uBO before and asks to remove adblock to watch the video.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 81734
  cosmetic: 48140
  scriptlet: 17366
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, never
  default: 
    user-filters: 0-0, never
    DEU-0: 5860-0, 2h.21m
    easylist: 68263-56, 2h.18m
    easyprivacy: 27307-132, 2h.17m
    plowe-0: 3646-781, 2h.16m
    ublock-abuse: 75-0, 2h.14m
    ublock-badware: 4232-93, 2h.12m
    ublock-filters: 32046-124, 2h.11m
    ublock-privacy: 224-3, 2h.10m
    ublock-quick-fixes: 203-2, 2h.9m
    ublock-unbreak: 1831-45, 2h.8m
    urlhaus-1: 4958-0, 2h.7m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 245 ms (selfie)
  maxAssetCacheWait: 146 ms
```
</details>

**Comment by dimisa-RUAdList** [comment]
`un-block-voe.net##+js(abort-on-property-read, VODMonetisation)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=un-block-voe.net`
