### ISSUE TITLE
promocaogames.com.br: nuisance

### ISSUE THREAD

**Issue by flaviojcojr** [uBlockOrigin/uAssets#13908]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.promocaogames.com.br/2022/07/xbox-store-de-1-14-de-julho.html`

### Category

nuisance

### Describe the issue

Cosmetic filtering is hiding text from site tables. This site posts Xbox promotions in tables and some of this text contains redirect links (which ublock correctly blocks). But a few days ago ublock started to hide the text too. Disabling cosmetic filtering resolves the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Clipboard01](https://user-images.githubusercontent.com/60268722/177050764-9073f0b5-e266-41f2-bb80-ed8a3d903536.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 80865
  cosmetic: 47294
  scriptlet: 17591
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68225-50, 1d.22h.43m
    easyprivacy: 27299-122, 1d.22h.42m
    plowe-0: 3646-780, 1d.22h.48m
    spa-1: 4551-80, 1d.22h.44m
    ublock-abuse: 75-0, 3d.23h.49m
    ublock-badware: 4232-93, 1d.22h.47m
    ublock-filters: 32045-151, 1d.22h.46m
    ublock-privacy: 224-3, 3d.23h.48m
    ublock-quick-fixes: 205-4, 20h.48m
    ublock-unbreak: 1831-45, 1d.22h.45m
    urlhaus-1: 4915-0, 20h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 289 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 13
  no-cosmetic-filtering: true
  blockedDetails: 
    google-analytics.com: 1
    google.com: 9
    googlesyndication.com: 3
```
</details>

**Comment by DoorCar** [comment]
`promocaogames.com.br#@#a[href^="https://click.linksynergy.com/"]` -- disables EasyList filter
