### ISSUE TITLE
sport.tv2.dk: breakage

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#13907]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sport.tv2.dk/live/2022-07-03-3-etape-af-tour-de-france-vejle-soenderborg`

### Category

breakage

### Describe the issue

More videos below won't play, no matter how many times to click play. The first video plays fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/40742924/177045196-b43d4658-27a6-4a8e-b8d7-5dc09bfe3455.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80754
  cosmetic: 47659
  scriptlet: 20349
  html: 0
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4479-7, 1m
  default: 
    user-filters: 0-0, never
    NOR-0: 2796-7, 1m
    easylist: 68288-51, 1m
    easyprivacy: 27309-123, 1m
    plowe-0: 3647-781, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4232-94, 1m
    ublock-filters: 32074-116, 1m
    ublock-privacy: 224-3, 1m
    ublock-quick-fixes: 206-4, 1m
    ublock-unbreak: 1829-44, 1m
    urlhaus-1: 5003-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 404 ms
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    adnami.io: 1
    adobedtm.com: 5
    doubleclick.net: 1
    imasdk.googleapis.com: 1
    k5a.io: 1
    lp4.io: 1
    tv2a.dk: 2
```
</details>

**Comment by mapx-** [comment]
Even using a vpn and disabling uBO I get:

```
Hov, noget gik galt.
Der skete desværre en fejl under afspilningen.
Prøv at genindlæse siden.
```

```
Hey, something went wrong.
Unfortunately, an error occurred during playback.
Try reloading the page.
```

@DandelionSprout

**Comment by AndnixSH** [comment]
Strange. Forgot to mention, the video works after I disabled uBO

**Comment by mapx-** [comment]
I guess only a real DK ip is working

**Comment by DandelionSprout** [comment]
I seem to be getting videos to work without any problems when using AdGuard VPN: 
![image](https://user-images.githubusercontent.com/22780683/177046173-095908b2-adf2-41d8-a920-47d1ebd42d3e.png)

**Comment by AndnixSH** [comment]
@DandelionSprout Yes first video works fine. what about the other videos when you scroll down below?

**Comment by DandelionSprout** [comment]
Now that you mention it, I couldn't even get the videos to play, no matter how many times I clicked on the videos.

It seems to be caused by `||imasdk.googleapis.com^` in EasyList and AdGuard Mobile Ads, oddly enough.
