### ISSUE TITLE
bose.no: breakage

### ISSUE THREAD

**Issue by oddstr13** [uBlockOrigin/uAssets#13901]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bose.no/nb_no/my-cart.html`

### Category

breakage

### Describe the issue

Shopping cart does not load.
Seems to be caused by «Fanboy’s Annoyance», as disabling that list lets it load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/638706/177005999-00a4f109-376a-4b67-9fe4-080ca0f38c30.png)
![image](https://user-images.githubusercontent.com/638706/177006019-db998ba0-4262-4fee-a00a-a9d384009fba.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 86595
  cosmetic: 109892
  scriptlet: 18811
  html: 696
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 74291-261, 1d.20h.54m
  default: 
    user-filters: 6-0, never
    ublock-filters: 32685-38, 19h.24m
    ublock-badware: 4236-3, 19h.23m
    ublock-privacy: 230-0, 12d.23h.12m
    ublock-abuse: 75-0, 12d.23h.11m
    ublock-unbreak: 1846-2, 19h.22m
    easylist: 68225-582, 19h.21m
    easyprivacy: 27299-581, 19h.20m
    urlhaus-1: 4896-0, 23h.25m
    plowe-0: 3644-3, 6d.22h
    ublock-quick-fixes: 201-0, 23h.26m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3819 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    adobedtm.com: 3
    bose.com: 10
    btttag.com: 2
    curalate.com: 1
    demdex.net: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
add & test

`bose.no#@#.exitIntent`

@ryanbr

**Comment by oddstr13** [comment]
Adding that to my filters does indeed fix the issue
