### ISSUE TITLE
lightnovelpub.com: detection

### ISSUE THREAD

**Issue by Ram-512bit** [uBlockOrigin/uAssets#13919]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelpub.com/`

### Category

detection

### Describe the issue

Last week when I visited the site it was fine. But today when I used it there was a pop-up detecting the ad blocker, I tried to remove it using the "element picker mode" feature in ublock origin but I can't figure it out how to do it. So reporting here, to solve the issue universally. Thanks. (P.S: Seeing the attached screenshot will be useful.)
Edit: The pop-up appears with approx. 0.5 to 1 second delay after loading the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screen shot](https://user-images.githubusercontent.com/92179847/177159997-4320d461-4498-4984-a311-772c51194791.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79587
  cosmetic: 44543
  scriptlet: 17331
  html: 695
listset (total-discarded, last updated): 
  default: 
    user-filters: 83-2, never
    ublock-filters: 32693-34, 2m
    ublock-badware: 4236-4, 2m
    ublock-privacy: 230-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1846-2, 2m
    easylist: 68263-580, 2m
    easyprivacy: 27307-582, 2m
    urlhaus-1: 4958-0, 2m
    plowe-0: 3646-3, 2m
    ublock-quick-fixes: 201-4, 2m
filterset (user): [array of 91 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1464 ms (selfie)
  maxAssetCacheWait: 773 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    lightnovelpub.com: 5
    googletagmanager.com: 1
    intergient.com: 2
    pub.network: 4
    quantcast.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
working fine on my side, update again all your lists, disable custom filters (from my filters) for this site, disable other blocking addons, test again

**Comment by Procyon-b** [comment]
@Ram-512bit I can confirm what @mapx- wrote. I've tested with the lists not updated (around 1 day old) and I saw the detection. But I don't see it anymore after updating.

**Comment by Ram-512bit** [comment]
After resetting uBlock and again updating the filter list the problem is solved. But when I did the same(resetting from settings, purging caches, updating the filters and removing all filters) last week the problem still persisted. Anyhow it's solved now. Thx guys for the quick response.
