### ISSUE TITLE
slotlights1x.com: ads

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13916]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slotlights1x.com/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80161
  cosmetic: 45528
  scriptlet: 17420
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32739-124, 56m
    ublock-badware: 4211-3, 56m
    ublock-privacy: 230-0, 56m
    ublock-abuse: 75-0, 56m
    ublock-unbreak: 1845-2, 56m
    ublock-quick-fixes: 202-0, 56m
    easylist: 68297-495, 56m
    easyprivacy: 27316-598, 56m
    urlhaus-1: 4832-0, 56m
    plowe-0: 3647-3, 55m
    VIE-1: 1798-1, 55m
filterset (user): [array of 7 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 521 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Are you talking about ads on `slotlights1x` or `slotlights1x` is the ad itself ?

**Comment by zeref-dragneel** [comment]
`slotlights1x` is the ad itself

**Comment by zeref-dragneel** [comment]
> Where did you get that ad

`slotslights.com`

**Comment by mapx-** [comment]
> steps to reproduce

Don't waste our time.
