### ISSUE TITLE
express.co.uk: nuisance

### ISSUE THREAD

**Issue by EvUnGithub** [uBlockOrigin/uAssets#13927]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.express.co.uk/`

### Category

nuisance

### Describe the issue

Cookie notice/Privacy notice

### Screenshot(s)

![image](https://user-images.githubusercontent.com/108665466/177203124-ae212cd3-ee2d-4c82-8bc2-be4480216f40.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 874666
  cosmetic: 112110
  scriptlet: 38472
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/: 392207-0, 8m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1913-0, 8m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23828-26, 8m
    https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt: 420719-6268, 8m
    fanboy-annoyance: 74681-348, 8m
    fanboy-cookiemonster: 35600-35600, 8m
    ublock-annoyances: 4479-88, 8m
  default: 
    user-filters: 5-0, never
    easylist: 68335-13992, 8m
    easyprivacy: 27314-6126, 8m
    plowe-0: 3647-3398, 8m
    ublock-abuse: 75-4, 8m
    ublock-badware: 4212-528, 8m
    ublock-filters: 32086-3182, 8m
    ublock-privacy: 224-41, 8m
    ublock-quick-fixes: 213-6, 8m
    ublock-unbreak: 1824-49, 8m
    urlhaus-1: 4837-1117, 8m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 2200 ms
  maxAssetCacheWait: 1139 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    express.co.uk: 1
    adnami.io: 1
    amazon-adsystem.com: 1
    consensu.org: 1
    d2q1qtsl33ql2r.cloudfront.net: 1
    facebook.com: 1
    google-analytics.com: 1
    google.com: 7
    googleadservices.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    grapeshot.co.uk: 1
    indexww.com: 1
    moatads.com: 1
    privacymanager.io: 1
    pubmatic.com: 1
    quantserve.com: 1
    scorecardresearch.com: 1
    webcontentassessor.com: 1
```
</details>

**Comment by mapx-** [comment]
enable AdGuard Annoyances

**Comment by EvUnGithub** [comment]
Thanks for the work you're doing! Kudos to you and the whole team!
