### ISSUE TITLE
[nsfw] camcaps.to: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#13920]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://camcaps.to/video/1681/jewelz-blu-my-feet-saved-my-party-plans`

### Category

breakage

### Describe the issue

Some videos are blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/177161429-0294a86b-907d-418e-bfac-d7864ce2bea3.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 433098
  cosmetic: 147923
  scriptlet: 35348
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1462-6, 1d.2h.59m
    RUS-0: 41812-232, 1d.3h.1m
    adguard-generic: 65362-1297, 3d.5h.6m
    adguard-mobile: 7914-67, 3d.5h.6m
    curben-phishing: 21936-0, 20h.11m
    curben-pup: 201-0, 20h.9m
    fanboy-cookiemonster: 35240-96, 3d.5h.6m
    ublock-annoyances: 4477-83, 3d.5h.6m
  default: 
    FRA-0: 29107-59, 3d.5h.6m
    easylist: 68222-1062, 3d.5h.6m
    easyprivacy: 27296-816, 3d.5h.6m
    plowe-0: 3653-895, 3d.5h.6m
    ublock-abuse: 75-2, 3d.5h.6m
    ublock-badware: 4232-328, 3d.5h.6m
    ublock-filters: 32064-3530, 3d.5h.6m
    ublock-privacy: 224-3, 3d.5h.6m
    ublock-quick-fixes: 205-14, 20h.7m
    ublock-unbreak: 1829-84, 3d.5h.6m
    urlhaus-1: 5003-1, 20h.5m
filterset (user): [array of 2089 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 568 ms (selfie)
  maxAssetCacheWait: 432 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    aufr67i8sten.com: 2
    vtube.to: 1
```
</details>

**Comment by mapx-** [comment]
working fine with french, adguard base too
