### ISSUE TITLE
buyertrade.taobao.com: breakage

### ISSUE THREAD

**Issue by jill00007** [uBlockOrigin/uAssets#13921]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://buyertrade.taobao.com/trade/itemlist/list_bought_items.htm`

### Category

breakage

### Describe the issue

In the order search box, enter the name of any previously purchased product and click search, it will not be able to jump normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 86
filterset (summary): 
  network: 81484
  cosmetic: 44532
  scriptlet: 17406
  html: 0
listset (total-discarded, last updated): 
  removed: 
    CHN-0: null
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-0, 7d.1h.19m
    https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt: 204-0, 13h.2m
    https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt: 1210-1, 6h.33m
  default: 
    user-filters: 0-0, never
    easylist: 68221-85, 3d.9h.15m
    easyprivacy: 27296-451, 3d.9h.14m
    plowe-0: 3646-785, 2d.8h.16m
    ublock-abuse: 75-5, 2d.8h.20m
    ublock-badware: 4232-93, 3d.9h.12m
    ublock-filters: 32013-124, 3d.9h.8m
    ublock-privacy: 224-3, 2d.8h.18m
    ublock-quick-fixes: 203-2, 13h.4m
    ublock-unbreak: 1828-44, 3d.9h.7m
    urlhaus-1: 5003-0, 13h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 86 ms (selfie)
  maxAssetCacheWait: 54 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    taobao.com: 3
    aliyuncs.com: 7
    mmstat.com: 8
    tanx.com: 2
```
</details>

**Comment by MasterKia** [comment]
Please update your browser, it's too old.
