### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by MrBloom43** [uBlockOrigin/uAssets#13929]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=J7p4bzqLvCw`

### Category

ads

### Describe the issue

Trailer and Advertising is back on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 98806
  cosmetic: 53550
  scriptlet: 17449
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 29107-24, 14h.43m
    easylist: 68297-127, 23h.56m
    easyprivacy: 27314-430, 14h.42m
    plowe-0: 3647-790, 11d.22h.5m
    ublock-abuse: 75-1, 11d.22h.6m
    ublock-badware: 4232-103, 3d.17h.28m
    ublock-filters: 32081-248, 23h.57m
    ublock-privacy: 224-3, 11d.18h.1m
    ublock-quick-fixes: 212-4, 14h.41m
    ublock-unbreak: 1829-44, 14h.44m
    urlhaus-1: 4782-0, 18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1461 ms (selfie)
  maxAssetCacheWait: 661 ms
popupPanel: 
  blocked: 86
  blockedDetails: 
    youtube.com: 76
    doubleclick.net: 5
    googlesyndication.com: 5
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues
duplicate #7636
