### ISSUE TITLE
[nsfw] time9learning.com: ads

### ISSUE THREAD

**Issue by mygithubisdumbasf** [uBlockOrigin/uAssets#13934]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.time9learning.com/App/Dashboards/Upper/`

### Category

ads

### Describe the issue

i

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
kk

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79401
  cosmetic: 44380
  scriptlet: 17357
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68349-50, 50m
    easyprivacy: 27352-122, 49m
    plowe-0: 3644-782, 8d.3h.1m
    ublock-abuse: 75-0, 8d.3h.4m
    ublock-badware: 4212-93, 48m
    ublock-filters: 32025-96, 47m
    ublock-privacy: 224-3, 8d.3h.3m
    ublock-unbreak: 1829-42, 46m
    urlhaus-1: 4782-0, 2h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 428 ms (selfie)
  maxAssetCacheWait: 145 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
> ### URL address of the web page
> 
> `https://www.time9learning.com/App/Dashboards/Upper/`
 are you sure about URL

**Comment by mapx-** [comment]
maybe
`https://www.time4learning.com/App/Dashboards/Upper/`

**Comment by mapx-** [comment]
> i

> kk
