### ISSUE TITLE
factable.com: breakage

### ISSUE THREAD

**Issue by Dulani** [uBlockOrigin/uAssets#13935]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.factable.com/history/maps-that-show-us-a-new-perspective/2/?utm_source=tp&utm_campaign=ovo-d-us-n-0-0-220518-fa-tp-g5&utm_medium=blank&utm_content=blank&utm_term=blank&twclid=24bphqrmcw5wlclh07r3442m1v&chrome=1&A1c=1&D2c=1&D3c=1&D4c=1&D_4_6cALL=1&D_4_6_10cALL=1&D6c=1&A5c=1&D7c=1&D10c=1&D_10_20cALL=1&A10c=1`

### Category

breakage

### Describe the issue

uBO blocks nearly all images, ads and non-ads on this site which is "breakage." 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79532
  cosmetic: 44376
  scriptlet: 17343
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68262-50, 3d.10h.9m
    easyprivacy: 27305-122, 3d.10h.8m
    plowe-0: 3644-782, 7d.22h.53m
    ublock-abuse: 75-0, 7d.22h.56m
    ublock-badware: 4232-93, 3d.10h.7m
    ublock-filters: 32045-112, 3d.10h.6m
    ublock-privacy: 224-3, 7d.22h.55m
    ublock-unbreak: 1831-42, 3d.10h.5m
    urlhaus-1: 5003-0, 1d.14h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 33 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1046 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 39
  blockedDetails: 
    factable.com: 1
    amazon-adsystem.com: 1
    aniview.com: 1
    doubleclick.net: 1
    doubleverify.com: 3
    google-analytics.com: 1
    googlesyndication.com: 25
    quantcast.com: 2
    quantserve.com: 2
    scorecardresearch.com: 1
    upapi.net: 1
```
</details>

**Comment by ghajini** [comment]
can you provide a screenshot of issue here?

also click **next** at bottom of page to load content

**Comment by okiehsch** [comment]
@ghajini 
Add 
````
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=factable.com
@@||securepubads.g.doubleclick.net/gpt/*$script,domain=factable.com
````
to see the content that is missing.

I think adding 
````
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=factable.com
@@||securepubads.g.doubleclick.net/gpt/*$script,domain=factable.com
factable.com##.puicontainer
factable.com##.pohcontainer
````
should work and hide all of the "Advertisement" messages.

**Comment by ghajini** [comment]
yes i seen but clicking next should load content (w/o allowing adserver)
alongwith hiding filters above

**Comment by okiehsch** [comment]
@ghajini has a point, if you don't add my filters and click "next" the content loads on new pages.
With my filters all of the content loads on one page.
Don't know if that is a "breakage" or not.
What do you think?

**Comment by mapx-** [comment]
if you remove uBO the page is an "infinite" one so I guess that is the correct behaviour

**Comment by okiehsch** [comment]
Ok, I will add the fix.

**Comment by mapx-** [comment]
@ryan too

**Comment by okiehsch** [comment]
You pinged the wrong ryan. 😁
