### ISSUE TITLE
bing.com: detection

### ISSUE THREAD

**Issue by LorenDB** [uBlockOrigin/uAssets#13936]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bing.com/search`

### Category

detection

### Describe the issue

When I search on Bing, I would like to be able to remove the "Trending searches" box. However, it appears that the element picker is broken. Whether I try to activate it from the right-click menu or the extension's dialog, the element picker action does absolutely nothing. However, it works as expected on other sites.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 101
filterset (summary): 
  network: 147679
  cosmetic: 208768
  scriptlet: 36981
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 4h.33m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 8h.34m
    adguard-annoyance: 54612-67, 2d.8h.40m
    adguard-generic: 65384-701, 2d.8h.39m
    adguard-mobile: 7915-94, 2d.8h.44m
    adguard-social: 17786-864, 2d.8h.41m
    adguard-spyware: 26223-1097, 2d.8h.42m
    dpollock-0: 10378-1472, 4d.8h.59m
    fanboy-annoyance: 74465-4208, 2d.20h.52m
    fanboy-cookiemonster: 35405-35405, 2d.20h.54m
    fanboy-social: 23275-23274, 2d.8h.43m
    fanboy-thirdparty_social: 69-21, 2d.20h.55m
    ublock-annoyances: 4477-231, 2d.8h.45m
    ublock-quick-fixes: 202-33, never
  default: 
    user-filters: 9-0, never
    easylist: 68285-1348, 2d.8h.49m
    easyprivacy: 27309-10445, 2d.8h.48m
    plowe-0: 3647-1461, 1d.4h.36m
    ublock-abuse: 75-0, 5d.9h.4m
    ublock-badware: 4232-325, 2d.8h.50m
    ublock-filters: 32045-3777, 2d.8h.47m
    ublock-privacy: 224-48, 5d.9h.3m
    ublock-unbreak: 1831-102, 2d.8h.46m
    urlhaus-1: 4782-0, 32m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 841 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/177412346-0d344d85-ef19-41aa-9bbc-ebf06fd58247.png)
