### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by haihefa** [uBlockOrigin/uAssets#13943]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=kmBzm9DJDPI`

### Category

ads

### Describe the issue

ad break through. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/79131225/177453636-a5c41a13-0445-49de-bfe6-2fff9e113ea8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 79565
  cosmetic: 44478
  scriptlet: 17374
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68271-50, 3d.9h.24m
    easyprivacy: 27309-122, 2d.9h.13m
    plowe-0: 3647-783, 12d.4h.10m
    ublock-abuse: 75-0, 22h.19m
    ublock-badware: 4232-93, 2d.9h.12m
    ublock-filters: 32065-112, 2d.9h.11m
    ublock-privacy: 224-3, 22h.18m
    ublock-quick-fixes: 206-4, 4h.1m
    ublock-unbreak: 1829-44, 2d.9h.7m
    urlhaus-1: 4939-0, 4h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 84 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    youtube.com: 26
    doubleclick.net: 3
    google.com: 3
    google.com.pe: 1
    googlesyndication.com: 1
    googlevideo.com: 3
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues
duplicate #7636
