### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by thegreatboi** [uBlockOrigin/uAssets#13947]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Describe the issue

![Screenshot (441)](https://user-images.githubusercontent.com/97782655/177579119-1d3d47f0-b56c-4e18-b9d5-c579bea3d684.png)
uBlock origin is always enabled on my end, but recently, it has not been working on Spotify. I'm getting the double ads as Spotify has in their interface, and they don't go away even on refreshing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 79605
  cosmetic: 44497
  scriptlet: 17396
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 68324-50, 2d.55m
    easyprivacy: 27314-122, 2d.59m
    plowe-0: 3644-782, 11d.21h.2m
    ublock-abuse: 75-0, 3d.9h.41m
    ublock-badware: 4212-93, 2d.58m
    ublock-filters: 32098-113, 2d.57m
    ublock-privacy: 224-3, 3d.9h.40m
    ublock-quick-fixes: 213-4, 22h.4m
    ublock-unbreak: 1831-44, 2d.56m
    urlhaus-1: 4939-0, 22h.5m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 383 ms (selfie)
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
It's about spotify premium ? that is self-promo

**Comment by krystian3w** [comment]
Also Disable Opera Adblocker:

> ![obraz](https://user-images.githubusercontent.com/35370833/177612707-e78f34b1-5a5d-47a2-b8b1-7b643b5075c1.png)
