### ISSUE TITLE
[nsfw] allporncomic.com: breakage

### ISSUE THREAD

**Issue by Palloxin** [uBlockOrigin/uAssets#13946]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://allporncomic.com/`

### Category

breakage

### Describe the issue

So when ublock is active, images (covers) don't load AND the main bar is "cutted" (see the image). Actual pages of comics load normally. This happens only on the mobile version of this website AND only on Firefox for android with ublock. i tried the mobile version on Firefox Pc and the problem doesn't occour so it is firefox android. i also tried the pc version of the website on firefox android and the problem doesn't occour.
here is the image of the bar cutted:

### Screenshot(s)

![IMG_20220706_160322](https://user-images.githubusercontent.com/75091899/177569000-f103745d-015c-4d10-a111-190dfef9d38d.jpg)
the page is scrolled at the maximum of the top part, seems ublock cancels something.
https://drive.google.com/file/d/1KsStb3XZR0Gx9vioXVKMtQFlHDC0UnmD/view?usp=sharing link of a video with adult material.
here u can see images are not loaded for some reason.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 86800
  cosmetic: 33396
  scriptlet: 17402
  html: 696
listset (total-discarded, last updated): 
  default: 
    user-filters: 173-6, never
    ublock-filters: 32846-302, 1d.8h.26m
    ublock-badware: 4215-3, 1d.8h.25m
    ublock-privacy: 230-1, 8d.17h.55m
    ublock-abuse: 75-0, 8d.17h.54m
    ublock-unbreak: 1845-2, 1d.8h.24m
    adguard-mobile: 7916-167, 2d.5h.56m
    easylist: 68343-24954, 1d.8h.23m
    easyprivacy: 27351-593, 1d.8h.22m
    urlhaus-1: 4963-0, 31m
    plowe-0: 3647-3, 1d.19h.46m
    ITA-0: 13085-403, 30m
    ublock-quick-fixes: 210-0, 35m
filterset (user): [array of 173 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1987 ms (selfie)
  maxAssetCacheWait: 1098 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    allporncomic.com: 4
    cloudflare.com: 2
    cloudflareinsights.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    o333o.com: 3
    profield.ddns.net: 4
```
</details>

**Comment by mapx-** [comment]
it should work:

```
*$script,3p,domain=allporncomic.com,badfilter
*$script,3p,domain=allporncomic.com,denyallow=cloudflare.com
```
