### ISSUE TITLE
[nsfw] getsecuritysuite.com: nuisance

### ISSUE THREAD

**Issue by Kevoffthashi** [uBlockOrigin/uAssets#13941]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://getsecuritysuite.com/?scenario=promo5v1ns&trackingdomain=trc.customlightworks.com&source_id=ad77a2ee-3d31-456e-888e-2057e06e4e29&cep=2EQ8zDDQckkPXR4wVjlWKGN9Su10yevw_0EOpai7hiTk8jXaaxEybZDXumMQbstIXoXjRb4f3Xq8ky0XfKTt3jsqke-_ASDQ3Lwlxo-QudTuPGwBhgxYKyxixl12dDJmn1sLmCtFImwqFWpAR0xrUJ6WDr8ssoYNx2kn-EsjQgOe1P4BVX57Xt_nGVs0ch5t2sg5186tR2T3gkkxbB59_VxLcc3lFbd2IVe7V0BI22sj97hZyuBLsxB1u5btGR7TDQ33NMMK832xJpfvUJNxT7jx7D4rjBOmvuu8GlDYEWfsD0wFl_UhAvoYvxEQzpPiTi7yDubn13oG_VCKiolnNSxvu6g0PnP-9rXMPM1j6Y85Uk6Zbd3HozIh2-9sMXySBkzU5gScZzPKREGfULrxMc0OIx_7oAoYs331lzwsg7slTn3o31ytgV8eZJglf2eX0pkIWY5qILRvIsHNv5PqAdeVN822OxsX3As12EEns_0&lptoken=161657000617744991fb&zoneid=212_133609&clickid=62c4d0da14c0f100019e4031`

### Category

nuisance

### Describe the issue

It fakes google pop ups and may be harmful to your device.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/108771442/177436382-ee0bbe7a-3273-4698-8c87-0a1982d4b375.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-60, never
    easyprivacy: 27172-152, never
    plowe-0: 3639-784, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-89, never
    ublock-filters: 31779-96, never
    ublock-privacy: 222-1, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-0, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2514 ms
  maxAssetCacheWait: 35 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ghajini** [comment]
It got fixed a day back
https://github.com/uBlockOrigin/uAssets/commit/f861cc715f1e8f20a33b82269a84e7437cb616ba

update your filter lists
