### ISSUE TITLE
onvideo.hu: detection

### ISSUE THREAD

**Issue by skyfighteer** [uBlockOrigin/uAssets#13956]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://onvideo.hu/`

### Category

detection

### Describe the issue

Please assign this to the hufilter team.
Thank you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-101, never
    plowe-0: 3639-784, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-3, never
    ublock-filters: 31779-96, never
    ublock-privacy: 222-0, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-30, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1264 ms
  maxAssetCacheWait: 13 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    agorahtag.tech: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    linkedin.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
@@||onvideo.hu^$ghide
hu#@#.ad
```

@scripthunter7

**Comment by mapx-** [comment]
@skyfighteer you can report directly at HU filter repository
https://github.com/hufilter/hufilter/issues

**Comment by krystian3w** [comment]
https://github.com/hufilter/hufilter/issues/12

**Comment by krystian3w** [comment]
Report issues was moved in:

https://github.com/hufilter/hufilter-dev/issues
