### ISSUE TITLE
tweakers.net: ads

### ISSUE THREAD

**Issue by justSem** [uBlockOrigin/uAssets#13954]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tweakers.net/`

### Category

ads

### Describe the issue

Tweakers is fighting it's way around adblockers.
The 'fix' implemented previous month in #13494 seems to be cicrumvented. Instead of the `##widebanner` tag they're now using randomly generated tags per page (at least that's what my quick investigation pointed out)

The ads appear roughly 5 seconds after the page has initially been loaded.
Most content is served from either `aa.tweakers.net` or `ab.tweakers.net`

![image](https://user-images.githubusercontent.com/86064734/177878129-3b23c590-372e-4cce-aa93-528eb4114c0e.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://user-images.githubusercontent.com/86064734/177877148-9d7869fb-4c1f-4b52-a03d-37623e88dd2d.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79722
  cosmetic: 44470
  scriptlet: 17344
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32671-102, 2d.11h.6m
    ublock-badware: 4216-3, 2d.11h.5m
    ublock-privacy: 230-0, 13d.2h.16m
    ublock-abuse: 75-0, 2h.52m
    ublock-unbreak: 1840-2, 2d.11h.4m
    ublock-quick-fixes: 211-0, 2h.51m
    easylist: 68346-492, 2d.11h.3m
    easyprivacy: 27352-594, 2d.11h.2m
    urlhaus-1: 5003-0, 2h.50m
    plowe-0: 3644-3, 12d.11h.7m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1627 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    tweakers.nl: 2
    usabilla.com: 2
```
</details>

**Comment by mapx-** [comment]
add `NLD: EasyDutch` , test again
