### ISSUE TITLE
gocmod.com: detection

### ISSUE THREAD

**Issue by hieuck** [uBlockOrigin/uAssets#13957]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gocmod.com/2021/09/tv360-truyen-hinh-truc-tuyen-v209-mod.html`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/30469654/177926564-7dea3cee-1805-4d87-978c-37662501783b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 86
filterset (summary): 
  network: 85886
  cosmetic: 93069
  scriptlet: 20043
  html: 0
listset (total-discarded, last updated): 
  removed: 
    VIE-1: null
  added: 
    https://abpvn.com/vip/quangnhut123.txt?ublock: 3502-2, 1m
    adguard-annoyance: 54952-73, 33m
  default: 
    user-filters: 18-0, never
    easylist: 68483-383, now
    easyprivacy: 27361-557, 1m
    plowe-0: 3647-805, now
    ublock-abuse: 75-1, now
    ublock-badware: 4212-93, now
    ublock-filters: 32077-466, 32m
    ublock-privacy: 223-4, now
    ublock-quick-fixes: 212-4, now
    ublock-unbreak: 1829-48, now
    urlhaus-1: 5011-0, now
filterset (user): [array of 18 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1337 ms
  maxAssetCacheWait: 619 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 7
    googletagmanager.com: 1
```
</details>

**Comment by zeref-dragneel** [comment]
Enable the list `VIE: ABPVN List`
