### ISSUE TITLE
surveymonkey.com: breakage

### ISSUE THREAD

**Issue by pacifisticuffs** [uBlockOrigin/uAssets#13953]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.surveymonkey.com/collect/email/manage?sm=ciHGBJNLiseIxelu_2F_2F71_2BWD9tfC7qPnOe1ucZEhRAJWmwOCqit1_2FUnbGHxB_2F7RJG`

### Category

breakage

### Describe the issue

The link on which this happened to me isn't public, but you can recreate the issue if you have access to a paid account on SurveyMonkey. There are several async requests that happen to validate/sanitize input or hydrate a page, and a broad match pattern is blocking these valid requests. I believe the pattern is coming from EasyPrivacy, `||surveymonkey.com/collect/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Console error:
<img width="800" alt="Screen Shot 2022-07-07 at 12 01 52 PM" src="https://user-images.githubusercontent.com/363766/177852120-5510da8d-7311-4844-9847-11aed8faa9bd.png">

UI error:
<img width="800" alt="Screen Shot 2022-07-07 at 12 02 08 PM" src="https://user-images.githubusercontent.com/363766/177852159-a5f2bb42-ee5e-49c1-b15c-38f0e39c8c35.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79605
  cosmetic: 44487
  scriptlet: 17388
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68288-50, 3d.20h.58m
    easyprivacy: 27309-122, 3d.20h.57m
    plowe-0: 3644-782, 10d.15h.45m
    ublock-abuse: 75-0, 11d.11h.50m
    ublock-badware: 4232-93, 3d.20h.56m
    ublock-filters: 32077-111, 3d.20h.55m
    ublock-privacy: 224-3, 11d.11h.49m
    ublock-quick-fixes: 214-4, 20h.47m
    ublock-unbreak: 1831-44, 3d.20h.54m
    urlhaus-1: 4963-0, 20h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 852 ms (selfie)
  maxAssetCacheWait: 192 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    surveymonkey.com: 1
    googletagmanager.com: 1
    signalfx.com: 5
    usabilla.com: 1
    ywxi.net: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
