### ISSUE TITLE
ad-flipcards.webflow.io: breakage

### ISSUE THREAD

**Issue by GeorgyBuns** [uBlockOrigin/uAssets#13951]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ad-flipcards.webflow.io/`

### Category

breakage

### Describe the issue

uBlock Origin blocks Webflow’s CSS for some reason. I’ve checked my own sites — everything working fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/mHgHa0c.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79626
  cosmetic: 44479
  scriptlet: 17365
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68287-50, 4d.58m
    easyprivacy: 27309-122, 4d.59m
    plowe-0: 3651-782, 9d.52m
    ublock-abuse: 75-0, 11d.19h.23m
    ublock-badware: 4232-93, 4d.57m
    ublock-filters: 32044-113, 4d.55m
    ublock-privacy: 224-3, 11d.19h.24m
    ublock-quick-fixes: 206-4, 3h.48m
    ublock-unbreak: 1831-44, 4d.56m
    urlhaus-1: 4991-0, 3h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1072 ms (selfie)
  maxAssetCacheWait: 224 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    website-files.com: 1
```
</details>

**Comment by mapx-** [comment]
it's due to this Easylist filter

`/css/ad-$domain=~ad-shield.io`


@ryanbr

**Comment by GeorgyBuns** [comment]
> it's due to this Easylist filter
> 
> `/css/ad-$domain=~ad-shield.io`
> 
> @ryanbr

Kekw, quite funny because my mate’s initials are AD. Will you fix it?
