### ISSUE TITLE
console.statsig.com: breakage

### ISSUE THREAD

**Issue by alex-statsig** [uBlockOrigin/uAssets#13965]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://console.statsig.com/BPJcDV1K1g87fTib5ZEMk/metrics/metrics_catalog`

### Category

breakage

### Describe the issue

The issue is when loading this page of a SPA a full reload happens (causing a few other flickering issues). This website uses NextJS and loads a routing bundle for the page ("metrics_catalog.json") and script ("metrics_catalog.js") matching the route name, which gets blocked by uBlock.

Loading the page requires the user to be logged in, but the blocked resources are 
- "https://console.statsig.com/_next/static/chunks/pages/%5Bcompany_id%5D/metrics/metrics_catalog-99bf2f9aea033a77.js"
- "https://console.statsig.com/_next/data/rOhgty1saMdZCSRF7a2G8/BPJcDV1K1g87fTib5ZEMk/metrics/metrics_catalog.json?company_id=BPJcDV1K1g87fTib5ZEMk"

I think scripts defined by a website coming from _next directory should be allowed as these are just the website's main functionality

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 79841
  cosmetic: 44519
  scriptlet: 17421
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68494-50, 5m
    easyprivacy: 27362-122, 5m
    plowe-0: 3646-780, 5m
    ublock-abuse: 75-0, 5m
    ublock-badware: 4212-93, 5m
    ublock-filters: 32103-98, 5m
    ublock-privacy: 225-3, 5m
    ublock-quick-fixes: 207-5, 5m
    ublock-unbreak: 1831-44, 5m
    urlhaus-1: 4991-0, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 647 ms (selfie)
  maxAssetCacheWait: 424 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    statsig.com: 1
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/account-required or not to be?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/account%20required or not to be?

**Comment by krystian3w** [comment]
Page have public demo to test service before paid if no possible add random mail to developer?

**Comment by alex-statsig** [comment]
> Page have public demo to test service before paid if no possible add random mail to developer (I see limit to same domain like admin account)?

Yeah you can fill out a form at https://console.statsig.com/demo and it will take you to a demo version, then you should be able to access https://console.statsig.com/4TLCtqzctSqusYcQljJLJE/metrics/events or https://console.statsig.com/4TLCtqzctSqusYcQljJLJE/metrics/metrics_catalog and repro (when trying to navigate between the tabs)

**Comment by okiehsch** [comment]
`@@||console.statsig.com/_next/static/chunks/*metrics/*$other,domain=console.statsig.com`
works for you?

**Comment by alex-statsig** [comment]
> `@@||console.statsig.com/_next/static/chunks/*metrics/*$other,1p`

I think that should work, not positive how to test.

Tried adding to "My Filters" and it didn't resolve the issue. Seemed like the "/metrics/metrics_catalog/%5Bmetric_name%5D/%5Bmetric_type%5D-b6305e69b8fbfde9.js" was resolved, but not "metrics/metrics_catalog.json?company_id=BPJcDV1K1g87fTib5ZEMk"
