### ISSUE TITLE
f1tv.formula1.com: breakage

### ISSUE THREAD

**Issue by Miladiir** [uBlockOrigin/uAssets#13960]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://f1tv.formula1.com/detail/1000005166/gp-von-osterreich-2022-freies-training-1?action=play`

### Category

breakage

### Describe the issue

Consensu cookie banner is needed to set a cookie. Ublock blocks the domain, I am unable to whitelist. The player will not start the video, if the cookie is not set.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 151200
  cosmetic: 212262
  scriptlet: 37041
  html: 701
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-4, 1d.1h.19m
    https://winhelp2002.mvps.org/hosts.txt: 8730-3, 4d.2h.52m
    adguard-generic: 65570-5255, 42m
    adguard-mobile: 7922-214, 52m
    adguard-spyware: 26313-1196, 43m
    adguard-spyware-url: 665-14, 41m
    block-lan: 43-0, 17d.2h.16m
    adguard-annoyance: 54979-4114, 50m
    adguard-social: 17841-1059, 49m
    fanboy-thirdparty_social: 68-0, 57m
    fanboy-annoyance: 73686-58381, 55m
    fanboy-cookiemonster: 34676-105, 56m
    fanboy-social: 23236-28, 48m
    ublock-annoyances: 4487-4, 51m
    dpollock-0: 10378-1656, 7d.1h.40m
  default: 
    user-filters: 14-0, never
    ublock-filters: 32743-86, 47m
    ublock-badware: 4216-3, 53m
    ublock-privacy: 231-0, 54m
    ublock-abuse: 75-0, 4d.2h.55m
    ublock-unbreak: 1845-3, 46m
    easylist: 68488-1000, 45m
    easyprivacy: 27362-10665, 44m
    urlhaus-1: 5011-0, 5h.40m
    plowe-0: 3647-345, 4d.5h.55m
    DEU-0: 5870-3, 5h.41m
    ublock-quick-fixes: 210-0, 5h.39m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 448 ms (selfie)
  maxAssetCacheWait: 708 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    consensu.org: 2
    trustarc.com: 4
```
</details>

**Comment by mapx-** [comment]
Subscribe to test (watch) ?

Did you test using **only** the default settings / filter lists ? (if not just reset uBO to default and test again)

**Comment by Miladiir** [comment]
Yes, its subscribe to watch. I am closing this, as I finally managed to unblock this with an allow rule. I didnt notice, that you have to perform a little dance in order to create allow rules in the popup now.
