### ISSUE TITLE
file-upload.com: breakage

### ISSUE THREAD

**Issue by GianniGi** [uBlockOrigin/uAssets#13968]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.file-upload.com/fytfhdru2yux`

### Category

breakage

### Describe the issue

can't download anything

I have the same problem with chrome too.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79914
  cosmetic: 44528
  scriptlet: 17392
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32762-41, 40m
    ublock-badware: 4216-3, 38m
    ublock-privacy: 231-0, 46m
    ublock-abuse: 75-0, 44m
    ublock-unbreak: 1847-0, 37m
    easylist: 68499-567, 42m
    easyprivacy: 27367-581, 41m
    plowe-0: 3646-3, 47m
    urlhaus-1: 5048-0, 35m
    ublock-quick-fixes: 204-2, 36m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1097 ms
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  blockedDetails: 
    alexametrics.com: 1
    d26adrx9c3n0mq.cloudfront.net: 1
    google-analytics.com: 1
    inklinkor.com: 1
    protectionabate.com: 2
```
</details>

**Comment by mapx-** [comment]
- it's because a very nasty stuff on site
- when on last page the normal click does not work but use middle click or right click on "click here to download" and then "save link..."
