### ISSUE TITLE
sledujserialy.io shows unskippable 30s ad.

### ISSUE THREAD

**Issue by cudla100** [uBlockOrigin/uAssets#13967]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://sledujserialy.io/episode/cernobyl-s01e01#590790
https://sledujserialy.io/
```

### Describe the issue

When I try to play the video, the video player shows instead 30 second unskippable ad.

### Screenshot(s)

[picture](https://user-images.githubusercontent.com/27821549/178085667-ad5bccba-55ee-485a-8a50-7ffb69861d54.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80063
  cosmetic: 44856
  scriptlet: 17549
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32760-41, 14m
    ublock-badware: 4216-3, 14m
    ublock-privacy: 231-0, 14m
    ublock-abuse: 75-0, 14m
    ublock-unbreak: 1847-2, 14m
    ublock-quick-fixes: 204-0, 14m
    easylist: 68495-569, 14m
    easyprivacy: 27363-586, 14m
    urlhaus-1: 4991-0, 14m
    plowe-0: 3646-3, 14m
    CZE-0: 711-0, 14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 981 ms
  maxAssetCacheWait: 107 ms
```
</details>

**Comment by mapx-** [comment]
- Slovakia ip needed
- on Netu getting only blank frame
- streamtape is ok

**Comment by mapx-** [comment]
I get no preRoll
