### ISSUE TITLE
es.wallapop.com: breakage

### ISSUE THREAD

**Issue by Mecawento** [uBlockOrigin/uAssets#13963]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://es.wallapop.com/app/search?keywords=samsung+t7+ssd&filters_source=search_box`

### Category

breakage

### Describe the issue

--Problem description:
Ublock Origin 1.43.0 on Chrome browser Version 103.0.5060.114 (Official Build) (64-bit)

Using the search bar in es.wallapop.com breaks the normal load of the website and hides from Ublock Origin most of the elements so the user cannot allow or block whatever is causing the problem. The only option is to completely disable Ublock Origin, eat a truckload of web ads, and even then doing a selective filter of the huge new cascade of elements to reload again UO doesnt stop the problem

The logged user site chat doesnt work neither

--Solutions tried:
Sorry I dont have the tech skills to determine where is the problem using Ublock Origin tools but I can give a warning about this site:

es.wallapop.com is a very rogue and advertising hungry website Im pretty sure they are actively crippling Ublock Origin from their side

This error started happening yesterday and I have not changed my system or web browser settings for months

This is very similar to this closed issue:
es.wallapop.com: breakage #12860
https://github.com/uBlockOrigin/uAssets/issues/12860

Sorry I cannot be of more help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 94851
  cosmetic: 177115
  scriptlet: 24511
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54979-72, 1h.22m
    adguard-social: 17841-861, 1h.22m
    fanboy-annoyance: 75040-4147, 1h.22m
    fanboy-cookiemonster: 35989-35989, 1h.22m
    fanboy-social: 23236-23236, 1h.21m
    spa-0: 3900-38, 1h.21m
    spa-1: 4554-176, 1h.21m
    ublock-annoyances: 4479-200, 1h.21m
  default: 
    user-filters: 0-0, never
    easylist: 68488-91, 1h.22m
    easyprivacy: 27362-222, 1h.22m
    plowe-0: 3646-781, 1h.21m
    ublock-abuse: 75-0, 1h.21m
    ublock-badware: 4212-93, 1h.21m
    ublock-filters: 32096-524, 1h.21m
    ublock-privacy: 225-11, 1h.21m
    ublock-quick-fixes: 207-4, 1h.21m
    ublock-unbreak: 1829-53, 1h.21m
    urlhaus-1: 4991-0, 1h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 78 redacted]
hostRuleset: 
  added: [array of 1069 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 542 ms (selfie)
  maxAssetCacheWait: 781 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    cookielaw.org: 1
```
</details>

**Comment by mapx-** [comment]
test this filter

`@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$script,domain=es.wallapop.com`

**Comment by Yuki2718** [comment]
Tell me if there's any trouble left.
