### ISSUE TITLE
link.paid4link.net: popups

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#13961]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://link.paid4link.net/i255G`

### Category

popups

### Describe the issue

This is the correct address, the rest are pop-up ads: `https://pastehouse.com/kvquuajgc7`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ảnh](https://user-images.githubusercontent.com/95934994/178026597-73c686ee-e9c1-4cfe-8d81-58af0f99f286.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80790
  cosmetic: 46840
  scriptlet: 20384
  html: 701
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4487-4, 1h.9m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32743-47, 1h.9m
    ublock-badware: 4216-3, 1h.9m
    ublock-privacy: 231-0, 1h.9m
    ublock-abuse: 75-0, 1h.9m
    ublock-unbreak: 1845-2, 1h.9m
    ublock-quick-fixes: 204-0, 1h.9m
    easylist: 68488-574, 1h.9m
    easyprivacy: 27362-585, 1h.9m
    urlhaus-1: 4991-0, 1h.9m
    plowe-0: 3646-3, 1h.9m
    VIE-1: 1817-1, 1h.9m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 284 ms (selfie)
  maxAssetCacheWait: 309 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment]
````
link.paid4link.net##+js(disable-newtab-links)
link.paid4link.net##+js(nowoif)
link.paid4link.net##.blog-content
link.paid4link.net##.card-body
link.paid4link.net##.card-img-top
````
works but you have to click "Get Link" four times to reach the destination page.

**Comment by huyszn** [comment]
`https://link.paid4link.net/i255G` redirects to `https://link.paid4file.com/i255G`
