### ISSUE TITLE
stackblitz.com: breakage

### ISSUE THREAD

**Issue by GeorgeWL** [uBlockOrigin/uAssets#13962]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stackblitz.com/`

### Category

breakage

### Describe the issue

States that third-party cookies are blocked, even when disable uBlock Origin for the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/5931248/178022787-a581d5ea-9c9c-4f4c-abd2-26fe6b20e4a9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79710
  cosmetic: 44467
  scriptlet: 17379
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68346-50, 3d.2h.45m
    easyprivacy: 27352-122, 3d.2h.41m
    plowe-0: 3644-782, 11d.6h.45m
    ublock-abuse: 75-0, 11d.6h.44m
    ublock-badware: 4212-93, 3d.2h.44m
    ublock-filters: 32025-96, 3d.2h.43m
    ublock-privacy: 224-3, 11d.6h.43m
    ublock-quick-fixes: 213-4, 23h.1m
    ublock-unbreak: 1824-44, 3d.2h.42m
    urlhaus-1: 5003-0, 23h
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 184 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    clearbitjs.com: 1
    newrelic.com: 1
    segment.com: 1
```
</details>

**Comment by krystian3w** [comment]
Works on Firefox Mobile, maybe Yandex, Kiwi and UnGoogled Chromium bug.

**Comment by mapx-** [comment]
> even when disable uBlock Origin for the site

something else in your browser / system
