### ISSUE TITLE
techautomate.in: detection

### ISSUE THREAD

**Issue by Silversurferone** [uBlockOrigin/uAssets#13964]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techautomate.in/`

### Category

detection

### Describe the issue

Ads Blocker Detected!!! Message error

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20220706_234422](https://user-images.githubusercontent.com/108948824/178038928-41ab74b1-9fee-4627-8d02-593c8746ef0e.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 103
filterset (summary): 
  network: 110393
  cosmetic: 135700
  scriptlet: 36556
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 54995-1624, 2m
    adguard-generic: 65570-1063, 2m
    adguard-spyware-url: 665-13, 2m
    block-lan: 43-0, 2m
    fanboy-annoyance: 75040-35235, 2m
    ublock-annoyances: 4499-243, 2m
  default: 
    user-filters: 3-0, never
    adguard-mobile: 7922-62, 2m
    easylist: 68489-25204, 2m
    easyprivacy: 27362-348, 2m
    plowe-0: 3646-881, 2m
    ublock-abuse: 75-0, 2m
    ublock-badware: 4211-314, 2m
    ublock-filters: 32203-4007, 2m
    ublock-privacy: 225-12, 2m
    ublock-quick-fixes: 207-22, 2m
    ublock-unbreak: 1836-92, 2m
    urlhaus-1: 4991-0, 2m
filterset (user): [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2606 ms (selfie)
  maxAssetCacheWait: 2045 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    ad.plus: 2
    doubleclick.net: 3
    googlesyndication.com: 2
    googletagmanager.com: 1
    googletagservices.com: 1
```
</details>

**Comment by mapx-** [comment]
Chromium Mobile: what browser is this ?

How did you arrive on that page ? directly or starting from another one ? (which one)

**Comment by krystian3w** [comment]
> -[x] I did not answer truthfully to all the above checkpoints

You are use unsupported Chromium mobile fork, on Firefox that pop-up doesn't prompt.

**Comment by Silversurferone** [comment]
> 

Kiwi browser android

**Comment by mapx-** [comment]
> How did you arrive on that page ? directly or starting from another one ? (which one)

**Comment by krystian3w** [comment]
So better move to Firefox Mobile: https://github.com/kiwibrowser/src/blob/ad4fdb6d6e87d5587e4d9b54c6f159ffa055b67d/extensions/renderer/extension_injection_host.cc#L56-L72 - uBo can be disabled any time.

**Comment by Silversurferone** [comment]
> > How did you arrive on that page ? directly or starting from another one ? (which one)

https://newsinfo.club/web.php?cid=2052560

**Comment by krystian3w** [comment]
Still not on Firefox or remember long history about refferers/http header locations.

**Comment by mapx-** [comment]
- working fine desktop / FF mobile
- use FF mobile
