### ISSUE TITLE
tvbanywherena.com: video ads

### ISSUE THREAD

**Issue by azuredreamysky** [uBlockOrigin/uAssets#13978]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tvbanywherena.com/cantonese/videos/695-AllThatIsBitterIsSweet/6005571316001`

### Describe the issue

Video ads occur at the beginning and during multiple intervals of the non-ad video. This problem occurs throughout the entire site on different shows/dramas within the streaming platform. 

Tried un-installing/re-installing uBlock Origin Chrome extension, updated Chrome to latest version, purged cache for uBO and Chrome all to no avail. Appreciate any insight or help on this issue!

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 153605
  cosmetic: 219784
  scriptlet: 36679
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 28564-91, 1m
    adguard-annoyance: 55014-83, 3m
    adguard-generic: 65599-721, 3m
    adguard-mobile: 7923-66, 3m
    adguard-social: 17843-864, 3m
    curben-phishing: 24919-0, 3m
    curben-pup: 205-0, 3m
    fanboy-annoyance: 75081-4202, 3m
    fanboy-cookiemonster: 36026-36026, 3m
    fanboy-social: 23236-23236, 3m
    fanboy-thirdparty_social: 68-21, 3m
    ublock-annoyances: 4479-232, 3m
  default: 
    user-filters: 0-0, never
    easylist: 68529-1033, 3m
    easyprivacy: 27371-370, 3m
    plowe-0: 3646-883, 3m
    ublock-abuse: 75-0, 3m
    ublock-badware: 4202-314, 3m
    ublock-filters: 32129-3793, 3m
    ublock-privacy: 226-11, 3m
    ublock-quick-fixes: 207-18, 3m
    ublock-unbreak: 1833-92, 3m
    urlhaus-1: 5164-1, 3m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 809 ms
  maxAssetCacheWait: 635 ms
```
</details>

**Comment by mapx-** [comment]
I get no video ad FF / chrome, however the site is using SSAI

![image](https://user-images.githubusercontent.com/10303732/178133063-f1f055f9-409d-4e52-8514-ea676bf20a20.png)

**Comment by krystian3w** [comment]
@llacb47
