### ISSUE TITLE
audiomack.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#13975]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://audiomack.com/`

### Category

ads

### Describe the issue

https://user-images.githubusercontent.com/81616288/178119749-6e472734-fd67-4f4e-ba4e-8dcd2cef768b.mp4

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82069
  cosmetic: 48224
  scriptlet: 17431
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5885-0, 9h.11m
    easylist: 68502-56, 9h.11m
    easyprivacy: 27368-132, 9h.11m
    plowe-0: 3646-781, 9h.11m
    ublock-abuse: 75-0, 9h.11m
    ublock-badware: 4212-93, 9h.11m
    ublock-filters: 32122-110, 9h.11m
    ublock-privacy: 225-3, 9h.11m
    ublock-quick-fixes: 207-5, 9h.11m
    ublock-unbreak: 1831-45, 9h.11m
    urlhaus-1: 5048-0, 9h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8128 ms (selfie)
  maxAssetCacheWait: 334 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 1
    mxpnl.com: 1
    newrelic.com: 1
    quantserve.com: 2
    scorecardresearch.com: 1
    unequalbrake.com: 1
```
</details>

**Comment by krystian3w** [comment]
SSAI / CSAI?

**Comment by mapx-** [comment]
That sponsored artist is still on the same `audiomack` site, kind of self-promo
