### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by imboredandu** [uBlockOrigin/uAssets#13977]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=5_ZfmrWPUeM`

### Category

ads

### Describe the issue

since the new chrome update, the ads preceding youtube videos have not been blocked as they were pre the new update. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79855
  cosmetic: 44493
  scriptlet: 17412
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68435-50, 2d.1h.35m
    easyprivacy: 27358-122, 2d.1h.39m
    plowe-0: 3646-780, 7d.15h.21m
    ublock-abuse: 75-0, 8d.2h.50m
    ublock-badware: 4212-93, 2d.1h.38m
    ublock-filters: 32087-97, 2d.1h.37m
    ublock-privacy: 224-3, 8d.2h.49m
    ublock-quick-fixes: 207-4, 15h.3m
    ublock-unbreak: 1829-44, 2d.1h.36m
    urlhaus-1: 5048-0, 15h.2m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2146 ms (selfie)
  maxAssetCacheWait: 915 ms
popupPanel: 
  blocked: 445
  no-popups: true
  blockedDetails: 
    youtube.com: 381
    doubleclick.net: 8
    google.co.uk: 1
    google.com: 23
    googlesyndication.com: 14
    googlevideo.com: 18
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues

duplicate #7636
