### ISSUE TITLE
[nsfw] yhdm2.com: breakage

### ISSUE THREAD

**Issue by githudzxl** [uBlockOrigin/uAssets#13974]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://yhdm2.com/acg/71679/1.html`

### Category

breakage

### Describe the issue

_Playback of anime videos is blocked_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 97998
  cosmetic: 56855
  scriptlet: 17544
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2184-101, never
    CHN-0: 28556-91, now
    easylist: 68507-71, now
    easyprivacy: 27369-148, now
    plowe-0: 3646-782, now
    ublock-abuse: 75-0, now
    ublock-badware: 4212-93, now
    ublock-filters: 32128-116, now
    ublock-privacy: 225-3, now
    ublock-quick-fixes: 207-5, now
    ublock-unbreak: 1833-45, now
    urlhaus-1: 5081-0, now
filterset (user): [array of 2184 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 777 ms (selfie)
  maxAssetCacheWait: 2864 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    baidu.com: 2
```
</details>

**Comment by krystian3w** [comment]
Works fine on stock lists in Firefox.

So bug may is in:
```yaml
    user-filters: 2184-101, never
    CHN-0: 28556-91, now
filterset (user): [array of 2184 redacted]
```
