### ISSUE TITLE
Apple Tracking Pixel

### ISSUE THREAD

**Issue by RiversideRocks** [uBlockOrigin/uAssets#13970]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.apple.com/maps/`

### Describe the issue

uBlock allows a tracking pixel from Apple to pass the filter system. When on the Apple Maps page, the following tracking pixel passes the filter:

`
https://securemetrics.apple.com/b/ss/applestoreww/1/JS-2.22.0/s06039341003127?AQB=1&ndh=1&pf=1&t=9/6/2022 10:13:59 6 240&fid=7C8DB37BE7881CC2-0BE8DFFEFC334289&ce=UTF-8&cdp=2&cl=1800&pageName=maps (us)&g=https://www.apple.com/maps/&cc=USD&events=event243=39.59,event244&h1=www.us.ios&l3=D=as_tex&v4=D=pageName&v14=en-us&c34=hero&c35=39.59&c36=1&v49=https://duckduckgo.com/&v54=D=g&v97=s.tl-o&pe=lnk_o&pev2=section engagement&s=1333x750&c=24&j=1.6&v=N&k=Y&bw=1333&bh=349&lrt=200&AQE=1
`

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 102

### Settings

None

**Comment by mapx-** [comment]
It's about an easyprivacy filter added 2 years ago to fix a breakage
`@@||securemetrics.apple.com/b/ss/$image`


![image](https://user-images.githubusercontent.com/10303732/178111710-1350772e-7c13-4db1-8aea-d5888958964a.png)

@ryanbr

**Comment by mapx-** [comment]
@RiversideRocks test this filter for breakage

`||securemetrics.apple.com/b/ss/*maps$image,important`

**Comment by RiversideRocks** [comment]
No breakage on my side.

**Comment by RiversideRocks** [comment]
Actually, another script to block would be `https://www.apple.com/metrics/ac-analytics/2.15.1/scripts/ac-analytics.js` which is what is triggering the tracking pixel.

**Comment by mapx-** [comment]
another list (`AdGuard Tracking Protection`) is whitelisting it for some other breakage 

`@@||apple.com/metrics/ac-analytics/*/scripts/$domain=apple.com`

**Comment by krystian3w** [comment]
@llacb47
