### ISSUE TITLE
tameteo.com: [unknown]

### ISSUE THREAD

**Issue by bphd** [uBlockOrigin/uAssets#13979]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tameteo.com/meteo_Ivry+sur+Seine-Europe-France-Val+de+Marne--1-24850.html`

### Category

[unknown]

### Describe the issue

a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79812
  cosmetic: 44494
  scriptlet: 17366
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32718-35, 2d.13h.30m
    ublock-badware: 4216-4, 2d.13h.29m
    ublock-privacy: 230-0, 5d.11h.49m
    ublock-abuse: 75-0, 5d.11h.48m
    ublock-unbreak: 1846-2, 2d.13h.28m
    ublock-quick-fixes: 211-4, 23h.49m
    easylist: 68393-553, 4d.57m
    easyprivacy: 27345-594, 4d.56m
    urlhaus-1: 5048-0, 23h.48m
    plowe-0: 3647-3, 4d.15h.4m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4381 ms (selfie)
  maxAssetCacheWait: 1255 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    duckduckgo.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> Category [unknown] 

> Describe the issue a

**Comment by bphd** [comment]
It was Ghostery
