### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by Jaougraal** [uBlockOrigin/uAssets#13971]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/`

### Category

ads

### Describe the issue

shows ads on videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79827
  cosmetic: 44475
  scriptlet: 17387
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68388-50, 3d.16h.4m
    easyprivacy: 27345-122, 3d.16h.3m
    plowe-0: 3647-780, 3d.16h.2m
    ublock-abuse: 75-0, 3d.16h
    ublock-badware: 4212-93, 3d.15h.58m
    ublock-filters: 32042-96, 3d.15h.57m
    ublock-privacy: 224-3, 3d.15h.56m
    ublock-quick-fixes: 207-4, 31m
    ublock-unbreak: 1828-44, 3d.15h.54m
    urlhaus-1: 5081-0, 30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 146 ms (selfie)
  maxAssetCacheWait: 77 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by ClaraJenny** [comment]
Please help me with my Facebook account please get it reset and resolved with any issues please
