### ISSUE TITLE
defenseone.com: breakage (cannot scroll)

### ISSUE THREAD

**Issue by danthl** [uBlockOrigin/uAssets#13976]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.defenseone.com/technology/2022/07/us-chips-are-paving-chinas-path-ai-superiority-and-theres-no-easy-fix/368906/`

### Category

breakage

### Describe the issue

Unfortunately, this page cannot seem to scroll with ubp enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 79834
  cosmetic: 44480
  scriptlet: 17387
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68394-50, 3d.6h.27m
    easyprivacy: 27351-122, 3d.6h.25m
    plowe-0: 3647-780, 3d.6h.29m
    ublock-abuse: 75-0, 3d.6h.30m
    ublock-badware: 4212-93, 3d.6h.23m
    ublock-filters: 32042-97, 3d.6h.24m
    ublock-privacy: 224-3, 3d.6h.31m
    ublock-quick-fixes: 207-4, 2h.59m
    ublock-unbreak: 1829-44, 3d.6h.28m
    urlhaus-1: 5081-0, 2h.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2015 ms (selfie)
  maxAssetCacheWait: 314 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    facebook.com: 1
    facebook.net: 1
    googleadservices.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    licdn.com: 1
    sail-personalize.com: 1
    sail-track.com: 2
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`

**Comment by mapx-** [comment]
@ryanbr

**Comment by danthl** [comment]
brilliant
