### ISSUE TITLE
radio-m.net: ads

### ISSUE THREAD

**Issue by BoFFire** [uBlockOrigin/uAssets#13981]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://radio-m.net/`

### Category

ads

### Describe the issue

Ad banner still displayed on the header.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 169489
  cosmetic: 63583
  scriptlet: 30281
  html: 694
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 65599-5907, 1h.4m
    adguard-mobile: 7923-168, 1h.3m
    adguard-spyware: 26316-1020, 1h.3m
    adguard-spyware-url: 665-15, 1h.3m
    curben-phishing: 24919-2, 1h.3m
    curben-pup: 205-0, 1h.3m
    dpollock-0: 10407-524, 1h.3m
    ara-0: 2582-243, 1h.3m
  default: 
    user-filters: 8-1, never
    ublock-filters: 32788-301, 1h.4m
    ublock-badware: 4206-3, 1h.4m
    ublock-privacy: 232-1, 1h.4m
    ublock-abuse: 75-0, 1h.4m
    ublock-unbreak: 1849-2, 1h.4m
    ublock-quick-fixes: 204-0, 1h.4m
    easylist: 68540-25190, 1h.3m
    easyprivacy: 27373-10548, 1h.3m
    urlhaus-1: 5164-0, 1h.3m
    plowe-0: 3646-3, 1h.3m
    FRA-0: 29299-3755, 1h.3m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1091 ms (selfie)
  maxAssetCacheWait: 613 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    radio-m.net: 4
    ampproject.org: 1
    facebook.net: 1
    googlesyndication.com: 2
    googletagmanager.com: 3
    quantserve.com: 2
    synsads.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`radio-m.net##.mega-banner`

@smed79
