### ISSUE TITLE
dupload.net: popups

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#13980]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dupload.net/euegc7mkq15c`

### Category

redirections

### Describe the issue

to get download link quick please change the link:
`https://dupload.net/euegc7mkq15c`
redirect to 
`https://dupload.net/cgi-bin/index.cgi?op=download2&id=euegc7mkq15c`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2022-07-10 at 13-30-57 10 best news sites about cryptocurrencies](https://user-images.githubusercontent.com/109018577/178136461-3e96ef11-9778-41ce-86ce-38304551e90f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79966
  cosmetic: 44547
  scriptlet: 17396
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32774-41, 5h.59m
    ublock-badware: 4216-3, 5h.58m
    ublock-privacy: 231-0, 6h.2m
    ublock-abuse: 75-0, 23h.12m
    ublock-unbreak: 1849-2, 5h.57m
    ublock-quick-fixes: 204-0, 23h.10m
    easylist: 68529-569, 6h.1m
    easyprivacy: 27371-581, 6h
    urlhaus-1: 5081-0, 23h.11m
    plowe-0: 3644-3, 12d.21h.47m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 114 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1167 ms (selfie)
  maxAssetCacheWait: 81 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
no popup / (malicious) redirection
