### ISSUE TITLE
syosetu.top: detection

### ISSUE THREAD

**Issue by fello3** [uBlockOrigin/uAssets#13982]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://syosetu.top/%e3%83%af%e3%83%b3%e3%83%94%e3%83%bc%e3%82%b9-raw-free-one-piece-chapter-1`

### Category

detection

### Describe the issue

The images on the site do not load when uBlock is enabled, and a placeholder "disable adblock" image is shown instead

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/75750135/178142055-05693cbd-a376-4679-ab5f-ead60a874511.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79899
  cosmetic: 44485
  scriptlet: 17352
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32688-40, 2d.18h.4m
    ublock-badware: 4236-3, 3d.14h.21m
    ublock-privacy: 230-0, 2d.18h.1m
    ublock-abuse: 75-0, 2d.18h.3m
    ublock-unbreak: 1846-0, 2d.18h.2m
    easylist: 68432-567, 2d.17h.58m
    easyprivacy: 27357-581, 2d.18h
    urlhaus-1: 5081-0, 15h.8m
    plowe-0: 3646-3, 7d.20h.42m
    ublock-quick-fixes: 204-2, 15h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 273 ms (selfie)
  maxAssetCacheWait: 270 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    syosetu.top: 1
```
</details>

**Comment by Yuki2718** [comment]
This is already fixed in Japanese filters.

**Comment by mapx-** [comment]
oh, so ... @fello3 => enable `JPN: AdGuard Japanese`
