### ISSUE TITLE
pravda.com.ua: breakage

### ISSUE THREAD

**Issue by ac3p** [uBlockOrigin/uAssets#13983]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pravda.com.ua/`

### Category

breakage

### Describe the issue

uBO blocks part of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![10 07 2022 14 39 41 Українська правда - новини онлайн про Украї](https://user-images.githubusercontent.com/49343476/178143750-225ac804-aaec-4a28-97ff-4ac9cb53a37b.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 64966
  cosmetic: 101025
  scriptlet: 22952
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-privacy: null
    urlhaus-1: null
  added: 
    fanboy-cookiemonster: 36091-90, 8m
    ublock-annoyances: 4483-49, 8m
  default: 
    user-filters: 15-0, never
    RUS-0: 41922-70, never
    easylist: 68543-50, 8m
    ublock-abuse: 75-0, 8m
    ublock-badware: 4202-91, 8m
    ublock-filters: 32152-106, 8m
    ublock-quick-fixes: 207-5, 8m
    ublock-unbreak: 1833-15, 8m
filterset (user): [array of 15 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 786 ms (selfie)
  maxAssetCacheWait: 715 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    gemius.pl: 1
    googletagservices.com: 1
    membrana.media: 1
```
</details>

**Comment by mapx-** [comment]
You should re-enable those lists or reset uBO to default settings / filter lists, force am update of all lists , test again

```
easyprivacy: null
plowe-0: null
ublock-privacy: null
urlhaus-1: null
```

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/9763b85f395ad5a0ee159681423b8b9fc240f317
