### ISSUE TITLE
seomonitor.com: breakage

### ISSUE THREAD

**Issue by emlynjones** [uBlockOrigin/uAssets#13984]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.seomonitor.com/`

### Category

breakage

### Describe the issue

Ublock blocks css files

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/4113665/178144575-f838a3e6-f528-4a25-91a2-ccc067d3cce8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 103
filterset (summary): 
  network: 79921
  cosmetic: 44517
  scriptlet: 17420
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68489-50, 1d.20h.17m
    easyprivacy: 27362-122, 1d.20h.16m
    plowe-0: 3646-780, 8d.4m
    ublock-abuse: 75-0, 8d.7m
    ublock-badware: 4212-93, 1d.20h.15m
    ublock-filters: 32096-98, 1d.20h.14m
    ublock-privacy: 224-3, 8d.6m
    ublock-quick-fixes: 207-4, 16h.9m
    ublock-unbreak: 1829-44, 1d.20h.13m
    urlhaus-1: 5081-0, 16h.10m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    seomonitor.com: 19
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
```
/seomonitor/*$badfilter
/seomonitor/*$3p
```

@ryanbr
