### ISSUE TITLE
carnival.com: breakage: Page blank

### ISSUE THREAD

**Issue by ShahBinoy** [uBlockOrigin/uAssets#13988]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.carnival.com/booking/review?currency=USD&durDays=4&embkCode=MIA&isMilitary=N&isOver55=N&isPastGuest=N&itinCode=WC2&locality=1&numGuests=4&roomType=OS&sailDate=08012022&sailingID=94362&shipCode=CQ&subRegionCode=CW`

### Category

breakage

### Describe the issue

The page appears empty, blank
If I disable ublock, it appears

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80080
  cosmetic: 44567
  scriptlet: 17410
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32801-36, 2m
    ublock-badware: 4226-3, 2m
    ublock-privacy: 232-0, 2m
    ublock-abuse: 75-0, 2m
    ublock-unbreak: 1849-0, 2m
    easylist: 68554-568, 2m
    easyprivacy: 27377-581, 2m
    plowe-0: 3646-3, 2m
    urlhaus-1: 5151-0, 2m
    ublock-quick-fixes: 204-7, 2m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 677 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    go-mpulse.net: 1
    optimizely.com: 6
    uplift-platform.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
The page appears fine for me with your URL

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/178172034-463f346a-378f-4857-af3c-7c8a2d652960.png)

</details>
