### ISSUE TITLE
waaw.to: breakage - again

### ISSUE THREAD

**Issue by PrometheusQ** [uBlockOrigin/uAssets#13987]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://waaw.to/watch_video.php?v=N29JdTJ3QTVTTDlvc09zUE80a2tQM2VBakxtcEtuQzl5Q1F4aGtNbjZSS09Xclk1Q2wyRm05Ynh1RGpDdXhOOA%3D%3D`

### Category

breakage

### Describe the issue

Same issue as reported previously in [https://github.com/uBlockOrigin/uAssets/issues/12881](12881)
On this site a randomly placed play button has to be pressed as part of validation before the video could be played. It worked fine in the past with UBlock but now that play button is not clickable - I cannot view any video on this site.
The issue now occurs with or without the custom filter that solved this problem earlier `waaw.*#@#+js(aopr, console.clear)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79960
  cosmetic: 44470
  scriptlet: 17424
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68545-50, 6m
    easyprivacy: 27376-122, 6m
    plowe-0: 3646-780, 6m
    ublock-abuse: 75-0, 6m
    ublock-badware: 4207-93, 6m
    ublock-filters: 32151-98, 6m
    ublock-privacy: 226-3, 6m
    ublock-unbreak: 1833-42, 6m
    urlhaus-1: 5151-0, 6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2090 ms (selfie)
  maxAssetCacheWait: 522 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    waaw.to: 3
    addthis.com: 1
    alleviatepracticableaddicted.com: 1
    commentsengine.com: 1
    disqus.com: 4
    viglink.com: 2
    zap.buzz: 3
```
</details>

**Comment by mapx-** [comment]
after removing `waaw.*##+js(set-constant, console.clear, undefined)`
it's all ok on my side

**Comment by mapx-** [comment]
update uBO filter list in 5 - 10 min

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/12881
