### ISSUE TITLE
systemed.fr: detection

### ISSUE THREAD

**Issue by Sarisisop** [uBlockOrigin/uAssets#13985]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.systemed.fr/`

### Category

detection

### Describe the issue

Ad blocker detected 
Found a report here: https://github.com/uBlockOrigin/uAssets/issues/11949 but it was closed in Feb.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot from 2022-07-10 16-22-08](https://user-images.githubusercontent.com/64807977/178148933-03f134bf-177b-48b3-807a-43df2368e2bb.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 129755
  cosmetic: 218652
  scriptlet: 36621
  html: 701
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt: 32701-557, 8m
    fanboy-thirdparty_social: 69-0, 8m
    fanboy-annoyance: 75157-59531, 8m
    fanboy-social: 23233-28, 8m
    FRA-0: 29299-372, 8m
    adguard-annoyance: 55022-4418, 8m
    fanboy-cookiemonster: 36093-127, 8m
    adguard-generic: 65607-5637, 8m
    adguard-mobile: 7923-149, 8m
    ublock-annoyances: 4491-4, 8m
    adguard-social: 17843-1058, 8m
  default: 
    user-filters: 38-0, never
    ublock-filters: 32802-241, 8m
    ublock-badware: 4211-3, 8m
    ublock-privacy: 232-0, 8m
    ublock-unbreak: 1849-2, 8m
    easylist: 68543-32831, 8m
    easyprivacy: 27376-606, 8m
    plowe-0: 3646-3, 8m
    ublock-abuse: 75-0, 8m
    urlhaus-1: 5151-0, 8m
    ublock-quick-fixes: 204-0, 8m
filterset (user): [array of 38 redacted]
trustedset: 
  added: [array of 36 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 764 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    systemed.fr: 3
    adnxs.com: 2
    consentframework.com: 2
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Try resetting uBO to default settings / filter lists

**Comment by Sarisisop** [comment]
Resetting to default fixed it, thank you.
