### ISSUE TITLE
autokult.pl: detection

### ISSUE THREAD

**Issue by liske310** [uBlockOrigin/uAssets#13999]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://autokult.pl/45366,autobusy-z-przyczepami-na-rowery-ruszyly-z-krakowa`

### Category

detection

### Describe the issue

we can`t read this site when ublock is on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 212519
  cosmetic: 51988
  scriptlet: 17599
  html: 705
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt: 131258-173, 2d.4h.29m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32762-80, 2d.4h.35m
    ublock-badware: 4216-3, 2d.4h.34m
    ublock-privacy: 232-0, 2d.4h.37m
    ublock-abuse: 75-0, 2d.4h.36m
    ublock-unbreak: 1849-2, 2d.4h.33m
    ublock-quick-fixes: 204-0, 2d.4h.27m
    easylist: 68543-586, 2d.4h.32m
    easyprivacy: 27375-581, 2d.4h.31m
    urlhaus-1: 5164-0, 2d.4h.26m
    plowe-0: 3647-3, 8d.3h.41m
    POL-0: 7850-25, 2d.4h.28m
    POL-2: 1279-12, 2d.4h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 402 ms (selfie)
  maxAssetCacheWait: 373 ms
popupPanel: 
  blocked: 67
  blockedDetails: 
    3lift.com: 1
    adform.net: 2
    adnxs.com: 6
    amazon-adsystem.com: 1
    casalemedia.com: 2
    connectad.io: 4
    creativecdn.com: 3
    criteo.com: 2
    criteo.net: 4
    facebook.net: 1
    gemius.pl: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    hotjar.com: 1
    id5-sync.com: 1
    indexww.com: 2
    openx.net: 4
    pubmatic.com: 5
    pushpushgo.com: 3
    rubiconproject.com: 2
    sharethrough.com: 9
    smartadserver.com: 7
    wp.pl: 3
```
</details>

**Comment by mapx-** [comment]
> we can`t read this site when ublock is on

Do you get anti adb wall ? other ? screenshot ?

**Comment by krystian3w** [comment]
fyi @olegwukr

**Comment by mapx-** [comment]
only an issue on my side, the videos are broken, add:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=autokult.pl`

**Comment by mapx-** [comment]
@krystian3w what  issue did you get on that page ?

**Comment by krystian3w** [comment]
On my side back many social share buttons cut long time ago - in the past these scenario exist due diffrent dom tree if anti-adblock was disabled by hide node instead disable by scriptlet or disable bait cosmetic filter.
