### ISSUE TITLE
444.hu: breakage

### ISSUE THREAD

**Issue by SKiss1234** [uBlockOrigin/uAssets#13995]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://444.hu/`

### Category

breakage

### Describe the issue

Using uBlock Origin will break the site. Only on this website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_20220711_191746](https://user-images.githubusercontent.com/109099745/178321323-20452bba-52ef-4f14-b5bb-e50e57d8f9b2.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80173
  cosmetic: 46316
  scriptlet: 17431
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    HUN-0: 2147-5, 2h.10m
    easylist: 68502-50, 2d.5h.57m
    easyprivacy: 27368-133, 2d.5h.56m
    plowe-0: 3646-784, 2d.5h.55m
    ublock-abuse: 75-0, 2d.5h.48m
    ublock-badware: 4212-93, 2d.5h.46m
    ublock-filters: 32084-100, 2d.5h.45m
    ublock-privacy: 225-3, 2d.5h.44m
    ublock-quick-fixes: 204-4, 2h.9m
    ublock-unbreak: 1829-44, 2d.5h.42m
    urlhaus-1: 5013-0, 2h.8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 200 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    bbelements.com: 1
    doubleclick.net: 2
    google.com: 2
    googletagmanager.com: 1
    youtube.com: 6
```
</details>

**Comment by scripthunter7** [comment]
@mapx- I removed `hu##.ad` completely, because it is too general and causing some issues.

See https://github.com/hufilter/hufilter-dev/commit/beef2eb82b2de95106411149c6b4fa547c741114
