### ISSUE TITLE
rutr.life: popups

### ISSUE THREAD

**Issue by thebrokepope** [uBlockOrigin/uAssets#13998]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://rutr.life/forum/index.php`

### Category

popups

### Describe the issue

Website has pop ups, however the pop ups themselves are blank.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79789
  cosmetic: 44545
  scriptlet: 17390
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68507-50, 2d.13h.39m
    easyprivacy: 27369-122, 2d.13h.38m
    plowe-0: 3647-780, 7d.13h.28m
    ublock-abuse: 75-0, 7d.13h.29m
    ublock-badware: 4212-93, 2d.13h.42m
    ublock-filters: 32090-116, 2d.13h.41m
    ublock-privacy: 224-3, 7d.13h.30m
    ublock-quick-fixes: 204-4, 10m
    ublock-unbreak: 1833-44, 2d.13h.40m
    urlhaus-1: 4945-0, 9m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 153 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    advcash.com: 1
    bongacams.com: 1
    chicgar.info: 5
    cloudflareinsights.com: 1
    google.com: 2
    jsdelivr.net: 1
    momijoy.ru: 1
    pinnacle.com: 1
    rutrk.org: 1
    umekana.ru: 1
    yadro.ru: 1
```
</details>

**Comment by ghajini** [comment]
enable regional adblocking filter list

** RU Adlist**
