### ISSUE TITLE
Filter breaks dark mode on techpowerup.com

### ISSUE THREAD

**Issue by gashtal** [uBlockOrigin/uAssets#13990]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [ ] uBO is the only extension -- Not applicable since Dark Reader extensions is required
- [X] uBO with default lists/settings
- [ ] using a new, unmodified browser profile -- Reproduced on two different browsers, so not specific to browser profile

### URL(s) where the issue occurs

`https://www.techpowerup.com/`

### Describe the issue

The following filter breaks dark mode (Enabled using Dark Reader extension) on `techpowerup.com` by removing the left and right parts of the page's background, which do not seem to be needed to be removed anyway:

`techpowerup.com##body:style(background-color: whitesmoke !important)`

Commenting out this particular filter (part of "uBlock filters") immediately resolves the issue and doesn't seem to have any negative side-effects since no ads are unblocked after commenting out that filter.

### Screenshot(s)

With filter enabled:

![image](https://user-images.githubusercontent.com/27990818/178161543-7db14bed-78a6-4a44-9fc8-c826d89a064b.png)

With filter disabled:

![image](https://user-images.githubusercontent.com/27990818/178161597-24c13b83-5def-4b30-a7f0-c9371f1aaaa9.png)

### uBlock Origin version

1.43.0

### Browser name and version

Opera 89.0.4447.38 and Firefox 102.0.1

### Settings

N/A

### Notes

Issue seems to be a side-effect of fix for #721. Reproduced on two different browsers in the same way.

**Comment by krystian3w** [comment]
try found bad filter by logger.
