### ISSUE TITLE
global.americanexpress.com: breakage

### ISSUE THREAD

**Issue by mujido** [uBlockOrigin/uAssets#13997]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://global.americanexpress.com/rewards/redeem-for-credit`

### Category

breakage

### Describe the issue

Form input area does not complete loading with default rules. In the attached broken.png is what it looks like with default rules. In fixed.png you can see the expected view after I have added the following rule:

```global.americanexpress.com https://assets.adobedtm.com script allow```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Broken:
![broken](https://user-images.githubusercontent.com/7462729/178379672-11faab79-4bd1-4a0b-a499-e6c2cf4b7474.png)

Fixed:
![fixed](https://user-images.githubusercontent.com/7462729/178379673-c762cf6c-f599-429d-aa9a-d1dd4c5a9a56.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79943
  cosmetic: 44563
  scriptlet: 17411
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32803-41, 1d.1h.16m
    ublock-badware: 4226-3, 1d.1h.15m
    ublock-privacy: 230-0, 9d.5h.48m
    ublock-abuse: 75-0, 9d.5h.47m
    ublock-unbreak: 1849-2, 1d.1h.14m
    easylist: 68555-567, 1d.1h.13m
    easyprivacy: 27377-581, 1d.1h.12m
    plowe-0: 3647-3, 6d.5h.35m
    urlhaus-1: 5013-0, 5h.10m
    ublock-quick-fixes: 204-0, 5h.9m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 6 redacted]
urlRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 355 ms (selfie)
  maxAssetCacheWait: 255 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    americanexpress.com: 7
    aexp-static.com: 3
    qualtrics.com: 1
```
</details>

**Comment by ryanbr** [comment]
Does adding `@@||assets.adobedtm.com/*-librarycode_source.min.js$script,domain=www.americanexpress.com` help @mujido  ?

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f0f19e65d4f85c56c070143a12a49bbc12d2f485

**Comment by samrjones5** [comment]
Had the same issue and fixed it by adding:
@@||assets.adobedtm.com/*-librarycode_source.min.js$script,domain=americanexpress.com

Please add this to your defaults.

**Comment by ryanbr** [comment]
We already have `@||adobedtm.com^*_source.min.js$domain=americanexpress.com`
