### ISSUE TITLE
xeroshoes.co.uk: breakage

### ISSUE THREAD

**Issue by lennie420** [uBlockOrigin/uAssets#13996]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xeroshoes.co.uk/`

### Category

breakage

### Describe the issue

Some of the pictures are missing and website in general is incomplete.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80048
  cosmetic: 44558
  scriptlet: 17412
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32802-41, 1d.1h.54m
    ublock-badware: 4211-3, 1d.1h.53m
    ublock-privacy: 230-0, 5d.8h.31m
    ublock-abuse: 75-0, 5d.8h.30m
    ublock-unbreak: 1849-2, 1d.1h.52m
    ublock-quick-fixes: 204-0, 1d.1h.49m
    easylist: 68554-568, 1d.1h.51m
    easyprivacy: 27377-581, 1d.1h.50m
    urlhaus-1: 5134-0, 1d.1h.48m
    plowe-0: 3647-3, 5d.6h.27m
filterset (user): [empty]
switchRuleset: 
  added: [array of 9 redacted]
hostRuleset: 
  added: [array of 77 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 0
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 139 ms (selfie)
  maxAssetCacheWait: 52 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    xeroshoes.co.uk: 2
    google-analytics.com: 1
    google.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||xeroshoes.co.uk/affiliate/scripts/trackjs.js$script,1p`

@ryanbr
