### ISSUE TITLE
ublock can't block anything in this website

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uAssets#13993]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

`https://www.livelaw.in/news-updates/`

### A specific URL where the issue occurs

`https://www.livelaw.in/news-updates/byjus-learning-app-district-consumer-forum-proper-app-tab-deficiency-in-service-refund-203411#`

### Steps to Reproduce

open this website and check nothing get blocks

### Expected behavior

it should be blocked

### Actual behavior

it blocked some stuff but most of the part does not get blocked.

### uBlock Origin version

1.43.0

### Browser name and version

firefox-android

### Operating System and version

android 12

**Comment by mapx-** [comment]
> it blocked some stuff but most of the part does not get blocked.

provide screenshot on what is not blocked / ads

**Comment by mapx-** [comment]
I don't read your mind: do you mean the lists were still enabled ?

If YES, disable (unselect) `Ignore generic cosmetic filters` and test again

**Comment by holequantum** [comment]
i am in firefox-android on android. 12

**Comment by mapx-** [comment]
Did you unselect `Ignore generic cosmetic filters` ?

**Comment by holequantum** [comment]
uninstalling the browser and reinstall fixed
