### ISSUE TITLE
123moviesgoto.com: breakage

### ISSUE THREAD

**Issue by dimondmine2** [uBlockOrigin/uAssets#13991]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://123moviesgoto.com/yellowstone-season-1`

### Category

breakage

### Describe the issue

Can't click the fullscreen button in the video player when Ublock Origin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 88
filterset (summary): 
  network: 79956
  cosmetic: 44504
  scriptlet: 17366
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-0, never
    ublock-filters: 32718-35, 3d.16h.43m
    ublock-badware: 4216-4, 3d.16h.42m
    ublock-privacy: 230-0, 5d.16h.48m
    ublock-abuse: 75-0, 1d.20h.34m
    ublock-unbreak: 1846-14, 3d.16h.41m
    easylist: 68418-204, 3d.16h.40m
    easyprivacy: 27353-594, 3d.16h.39m
    urlhaus-1: 5164-0, 16h.29m
    plowe-0: 3646-342, 1d.20h.33m
    ublock-quick-fixes: 204-4, 16h.28m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2445 ms (selfie)
  maxAssetCacheWait: 1358 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    addthis.com: 2
    cursormedicabnormal.com: 3
    doubleclick.net: 2
    google-analytics.com: 1
    googletagmanager.com: 2
    nomeuspagrus.com: 2
    yadro.ru: 1
    youtube.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
I can click on the full screen button normally, can you force update the filter lists and test again? Also, which server of the video player were you using?

**Comment by dimondmine2** [comment]
I force updated the filter lists and turned off other privacy and ad related extensions to retest. I still was unable to click the full screen button or interact with other video player settings. Vidcloud server. Looks like this issue may just be me
