### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#140]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.youtube.com/watch?v=kajpCSSF1-Y

### Describe the issue

i want to see comments in youtube videos,its not shown....
iam using filter "pure video experience" described over here 
https://youtube.adblockplus.me/

i choosed "block all youtube annoyances"
now i want to see comments in youtube videos
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Version 53.0.2785.101 m (64-bit)

- uBlock Origin version: 1.9.4

### Settings

- uBO's default settings+ antiadblock killer + adblock warning removal list+
filter at https://youtube.adblockplus.me/

i choosed "block all youtube annoyances"

### Notes

iam not reporting any bug in ublock: just an filter to unblock comments in youtube

**Comment by F4z** [comment]
Try this rule:
`youtube.com#@##watch-discussion`

**Comment by gorhill** [comment]
Just pick the two other filter lists instead of the "all" one.
