### ISSUE TITLE
freecodecamp.org: breakage

### ISSUE THREAD

**Issue by dembeck** [uBlockOrigin/uAssets#14006]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.freecodecamp.org/news/create-a-rest-api-with-dot-net-5-and-c-sharp/`

### Category

breakage

## Summary

When uBlock Origin is enabled the page gets caught in what seems to be a JavaScript loop.

## Details

**When uBlock is enabled and loading this page:**

The CPU stays at 100% until the page is exited, and the page memory usage has sudden increases at the approx times below:

```
  0 Seconds: Memory: 95mb,  JS Memory: 14mb 
 20 Seconds: Memory: 95mb,  JS Memory: 230mb
 90 Seconds: Memory: 1.3gb, JS Memory: 1.1gb
120 Seconds: MS Edge locks up
```
_I collected memory usage from the browser task manager, and CPU usage from the system task manager._

**When uBlock is disabled and loading this page:**

The page is fully loaded in about 10 seconds while never causing the CPU to max out and consumes only 80mb of memory and 12mb JS Memory.

## Notes

Even with uBlock enabled, the page appears to be fully loaded in about the same 10-15 seconds, it just consumes a lot of system resources.

I have not had this issue on any other sites over the several years of using uBlock, so I thought it was worth reporting. For now, I will just keep it disabled for the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 105
filterset (summary): 
  network: 79726
  cosmetic: 44952
  scriptlet: 17467
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 493-120, never
    easylist: 68340-79, 1m
    easyprivacy: 27403-123, 1m
    plowe-0: 3646-782, 1m
    ublock-abuse: 75-0, 1m
    ublock-badware: 4223-94, 1m
    ublock-filters: 32180-101, 1m
    ublock-privacy: 226-3, 1m
    ublock-quick-fixes: 213-14, 1m
    ublock-unbreak: 1834-42, 1m
    urlhaus-1: 5040-0, 1m
filterset (user): [array of 494 redacted]
trustedset: 
  added: [array of 288 redacted]
switchRuleset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 2 redacted]
urlRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4411 ms (selfie)
  maxAssetCacheWait: 2508 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cloudflareinsights.com: 1
    doubleclick.net: 2
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    youtube.com: 2
```
</details>

**Comment by dembeck** [comment]
I did not realize that configuration details do not have browser identifier information. 

```
Browser Version:       Microsoft Edge Version 105.0.1319.0 (Official build) canary (64-bit)
uBlock Origin Version: 1.42.4

Latest Version:        1.42.4
Installed From:        https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak

Windows Version:       Windows 11 Enterprise 22H2 (OS Build 25151.1010)
```

The Microsoft Store does not have version 1.43.0. Should I install the Google Chrome version instead? Were there any changes that might impact this issue?

**Comment by mapx-** [comment]
I guess the problem is using canary edge, try beta or stable one

**Comment by playonevideo** [comment]
Ad leftovers on their forum

`https://forum.freecodecamp.org/t/certification-exams/769338/2`

<img width="1651" height="758" alt="Image" src="https://github.com/user-attachments/assets/cc585959-23f8-4a09-adc1-934db798fb16" />
