### ISSUE TITLE
my.zon.tools: breakage

### ISSUE THREAD

**Issue by jason4567890** [uBlockOrigin/uAssets#14005]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.zon.tools/`

### Category

breakage

### Describe the issue

Several of the website functionalities do not work with Ublock!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79700
  cosmetic: 44642
  scriptlet: 17432
  html: 696
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32829-118, 3m
    ublock-badware: 4227-3, 3m
    ublock-privacy: 232-0, 3m
    ublock-abuse: 75-0, 3m
    ublock-unbreak: 1850-0, 3m
    easylist: 68341-506, 3m
    easyprivacy: 27403-581, 3m
    urlhaus-1: 5040-0, 3m
    plowe-0: 3646-3, 3m
    ublock-quick-fixes: 210-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 327 ms (selfie)
  maxAssetCacheWait: 184 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    zon.tools: 1
    googletagmanager.com: 1
    segment.com: 1
    smartlook.com: 1
```
</details>

**Comment by mapx-** [comment]
- account required ? => provide a test one ?

> Several of the website functionalities do not work with Ublock!

After having an account provide complete explanation on what happens
