### ISSUE TITLE
youtube sponsored products

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1400]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=P_1zZsJuY0I`

### Describe the issue

Sponsored products

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/35472759-2fef8580-0343-11e8-9a35-5aa0c521a120.png)

### Versions

- Browser/version: Chrome 63
- uBlock Origin version: 1.14.24

### Settings

Default

### Notes

Need to have the window wide enough so comments and recommended videos are shown side by side (as opposed to comments being below recommended videos) for the sponsored section to appear.

**Comment by gorhill** [comment]
This works but I wonder if this causes false positives:

    youtube.com###pla-shelf

**Comment by SMed79** [comment]
Reported here [#p127623](https://forums.lanik.us/viewtopic.php?p=127623#p127623) two months ago / still no fix added.

@ryanbr @monzta

**Comment by xDarkARG** [comment]
ami does not appear to me nothing should be that you have adware some program that you installed you put advertising

**Comment by terrorist96** [comment]
It doesn't always appear and may be region dependant. This is not the type of ad you would see if you have adware.

**Comment by uBlock-user** [comment]
> if this causes false positives:

No false positives, I have been using that filter for over 3 months.
