### ISSUE TITLE
old.reddit.com: nuisance

### ISSUE THREAD

**Issue by Beach77** [uBlockOrigin/uAssets#14000]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://old.reddit.com/r/learnart/comments/6yi1zs/first_tablet_what_software_should_i_use_digital/`

### Category

nuisance

### Describe the issue

When going to a post on old.reddit.com there is this "more of r/subredditname" section that gets annoying, at first I didn't even know that there were more comments below it so I just assumed that the site was broken. I tried my best at searching if a similar report has been made but I found none. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![20220712_182458](https://user-images.githubusercontent.com/101499628/178545524-172e8de6-522a-466c-a27b-0ac94c679f23.jpg)

</details> 

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 104
filterset (summary): 
  network: 81312
  cosmetic: 26291
  scriptlet: 17374
  html: 697
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32796-292, 2d.4h.8m
    ublock-badware: 4205-3, 2d.4h.7m
    ublock-privacy: 230-1, 4d.5h.48m
    ublock-abuse: 75-0, 4d.5h.47m
    ublock-unbreak: 1845-0, 2d.4h.3m
    ublock-quick-fixes: 208-0, 2h.14m
    adguard-mobile: 7923-167, 2d.4h.2m
    easylist: 68543-24977, 2d.3h.47m
    easyprivacy: 27375-591, 2d.3h.46m
    urlhaus-1: 5031-0, 2h.13m
    plowe-0: 3646-3, 3d.22h.30m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 956 ms (selfie)
  maxAssetCacheWait: 271 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    reddit.com: 2
    redditmedia.com: 1
```
</details>

**Comment by krystian3w** [comment]
https://developer.mozilla.org/docs/Tools/Remote_Debugging/Firefox_for_Android

https://firefox-source-docs.mozilla.org/devtools-user/remote_debugging/index.html

https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

If picker show randomized classes and hard is use on this `:has-text(...)`.

Maybe possible spoof this on your PC with enforce Firefox Android user-agent:

`Mozilla/5.0 (Android 12; Mobile; rv:102.0) Gecko/102.0 Firefox/102.0`

**Comment by Beach77** [comment]
I will try to do that, thanks.
