### ISSUE TITLE
pxxbay.com: ads

### ISSUE THREAD

**Issue by Amit-Biswas** [uBlockOrigin/uAssets#14018]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pxxbay.com/`

### Category

ads

### Describe the issue

Popups issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80085
  cosmetic: 44760
  scriptlet: 17428
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 161-6, never
    ublock-filters: 32825-39, 2d.9h.33m
    ublock-badware: 4227-3, 2d.9h.37m
    ublock-privacy: 230-0, 11d.14h.36m
    ublock-abuse: 75-0, 12d.22h.25m
    ublock-unbreak: 1849-0, 2d.9h.36m
    easylist: 68640-571, 2d.9h.35m
    easyprivacy: 27394-581, 2d.9h.34m
    urlhaus-1: 5082-0, 10h.20m
    plowe-0: 3647-3, 9d.1h.7m
    ublock-quick-fixes: 213-0, 10h.19m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 40 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 41 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1338 ms (selfie)
  maxAssetCacheWait: 1273 ms
popupPanel: 
  blocked: 23
  no-popups: true
  blockedDetails: 
    pxxbay.com: 2
    adsco.re: 1
    alternativecpmgate.com: 2
    d11enq2rymy0yl.cloudfront.net: 1
    eabids.com: 1
    ecybnxxpeq.com: 1
    jads.co: 3
    juicyads.com: 2
    msgose.com: 2
    pornyhd.com: 2
    realsrv.com: 4
    varietyofdisplayformats.com: 1
    xadsmart.com: 1
```
</details>

**Comment by Procyon-b** [comment]
First update your filter lists and try again. Open ublock's dashboard, go to the "Filter lists" tab, click "Purge all caches", click "Update now"
