### ISSUE TITLE
topappx.modmakers.xyz: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#14010]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://topappx.modmakers.xyz/index.php/2022/07/07/5-reasons-why-businesses-need-ethical-hackers/`

### Category

detection

### Describe the issue

A message appears informing us that an ad blocker has been detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/178838577-dcf1b522-10e4-4264-943a-f0256b7e3fd1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 538676
  cosmetic: 149067
  scriptlet: 35401
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41945-258, 3h.56m
    adguard-generic: 65756-1317, 3h.56m
    adguard-mobile: 7957-84, 3h.56m
    curben-phishing: 26112-0, 3h.56m
    curben-pup: 205-1, 3h.56m
    fanboy-cookiemonster: 36053-104, 3h.56m
    ublock-annoyances: 4488-83, 3h.56m
  default: 
    FRA-0: 29410-64, 3h.56m
    easylist: 68353-1061, 3h.56m
    easyprivacy: 27403-611, 3h.56m
    plowe-0: 3646-906, 3h.56m
    ublock-abuse: 75-2, 3h.56m
    ublock-badware: 4229-331, 3h.56m
    ublock-filters: 32163-3669, 3h.56m
    ublock-privacy: 226-3, 3h.56m
    ublock-quick-fixes: 215-26, 3h.56m
    ublock-unbreak: 1834-83, 3h.56m
    urlhaus-1: 5059-1, 3h.56m
filterset (user): [array of 2093 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 710 ms (selfie)
  maxAssetCacheWait: 546 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    modmakers.xyz: 6
```
</details>

**Comment by Procyon-b** [comment]
What happens when you disable your user filters ?  (uncheck "My filters" in the "Filter lists" tab, then click "Apply changes")

**Comment by mapx-** [comment]
@x-R0b0T-x Did you land on that page arriving from some other address ?

**Comment by mapx-** [comment]
working fine => disable "my filters" as @Procyon-b  suggested or use default settings
