### ISSUE TITLE
ultimaterewardspoints.chase.com: breakage

### ISSUE THREAD

**Issue by jawshooah** [uBlockOrigin/uAssets#14019]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ultimaterewardspoints.chase.com/travel/landing`

### Category

breakage

### Describe the issue

When uBO is enabled, the Search button on the Chase Ultimate Rewards Travel landing page doesn't do anything at all. From the console log, it looks like this is because the /web-analytics endpoint is blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/4551271/179068989-de4a9255-4296-417c-9d99-4204c613d867.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/4551271/179069046-9f8dfc8a-ce20-4a2c-84aa-f432d01ec716.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80050
  cosmetic: 44601
  scriptlet: 17458
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-0, 4d.13h.26m
  default: 
    user-filters: 0-0, never
    easylist: 68614-50, 2d.21h.28m
    easyprivacy: 27385-122, 2d.21h.27m
    plowe-0: 3647-780, 11d.2h.45m
    ublock-abuse: 75-0, 15h.54m
    ublock-badware: 4223-94, 2d.21h.26m
    ublock-filters: 32176-100, 2d.21h.24m
    ublock-privacy: 226-3, 15h.55m
    ublock-quick-fixes: 214-4, 15h.52m
    ublock-unbreak: 1833-44, 2d.21h.23m
    urlhaus-1: 5082-0, 15h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 227 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    chase.com: 1
```
</details>

**Comment by mapx-** [comment]
Account required.

Open the logger, repeat the steps to get the issue, go back in the logger, copy to clipboard (see the right side button bellow) and post here

![image](https://user-images.githubusercontent.com/10303732/179073569-64ff8ab9-0212-4ca9-ab23-907d12e4be43.png)

**Comment by jawshooah** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +33 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +33 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +30 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +24 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +22 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +17 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardstravel.chase.com/Services/HelperServices/SearchService.svc/Search` |
| +16 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardstravel.chase.com/Services/HelperServices/SearchService.svc/Search` |
| +15 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +15 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +14 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +14 |  |  | ultimaterewardspoints.chase.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN8rsOUuhp.woff2` |
| +9 |  |  | ultimaterewardspoints.chase.com | 1 | image | `https://ultimaterewardspoints.chase.com/public/the-app/resources/ui-bg_flat_75_ffffff_40x100.c05a059603fec34b44a2.png` |
| +9 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardstravel.chase.com/Services/HelperServices/SearchService.svc/Search` |
| +2 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +2 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +2 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/e/b2a8ee90e0000138a2a5865c` |
| +2 |  |  | ultimaterewardspoints.chase.com | 3 | script | `https://execution-360-cicolusp.cxtrvl.com/t/s/p/b2a8ee90e0000138a2a5865c?version=1.1.0&domain=ultimaterewardspoints.chase.com&p=%2Ftravel%2Flanding&params=AI%3D622870139&page_title=Travel%20Landing%20-%20Ultimate%20Rewards%20-%20Chase&referrer=https%3A%2F%2Fultimaterewardspoints.chase.com%2Faccount-selector&uri=https%3A%2F%2Fultimaterewardspoints.chase.com%2Ftravel%2Flanding%3FAI%3D622870139&requestedfile=%2Ftravel%2Flanding&platform=MacIntel&port=&protocol=https&browser_language=en-US&character_set=UTF-8` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | script | `https://execution-360-cicolusp.cxtrvl.com/t/s/c/b2a8ee90e0000138a2a5865c/1657839997768?version=1.1.0&domain=ultimaterewardspoints.chase.com&vid=b3b9b5729686b6480aa55a77&sid=424eac2a55f58b254927a28b&hb=16290&p=%2Ftravel%2Flanding&params=AI%3D622870139&page_title=Travel%20Landing%20-%20Ultimate%20Rewards%20-%20Chase&referrer=https%3A%2F%2Fultimaterewardspoints.chase.com%2Faccount-selector&uri=https%3A%2F%2Fultimaterewardspoints.chase.com%2Ftravel%2Flanding%3FAI%3D622870139&requestedfile=%2Ftravel%2Flanding&cts=1657839997768&tzo=240&platform=MacIntel&port=&protocol=https&flash_enabled=false&flash_version=&java_enabled=false&java_version=&screen_info=1440x900@24&browser_language=en-US&character_set=UTF-8&csz=1958497&bsz=1440x796&tab_id=274808477983` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://execution-360-cicolusp.cxtrvl.com/t/s/c/b2a8ee90e0000138a2a5865c?domain=ultimaterewardspoints.chase.com&vid=b3b9b5729686b6480aa55a77&sid=424eac2a55f58b254927a28b&hb=16290&p=%2Ftravel%2Flanding&params=AI%3D622870139&page_title=Travel%20Landing%20-%20Ultimate%20Rewards%20-%20Chase&referrer=https%3A%2F%2Fultimaterewardspoints.chase.com%2Faccount-selector&uri=https%3A%2F%2Fultimaterewardspoints.chase.com%2Ftravel%2Flanding%3FAI%3D622870139&cts=1657839997798&tzo=240&platform=MacIntel&port=&protocol=https&screen_info=1440x900@24&browser_language=en-US&character_set=UTF-8&csz=1958813&bsz=1440x796&tab_id=274808477983&java_enabled=false&flash_enabled=false` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | script | `https://execution-360-cicolusp.cxtrvl.com/js/ot-api.min.js` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | script | `https://execution-360-cicolusp.cxtrvl.com/js/ot-min.js` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/tile/load-gift-cards` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | script | `https://execution-360-cicolusp.cxtrvl.com/js/ot-all.min.js` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | css | `https://ultimaterewardstravel.chase.com/uploads/sites/jpmorganchase/themes/chase/css/widgetized-booker-main.ltr.zz-zz.css?v=299000218` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/public/svgs/common/23_fa-chevron-down.svg` |
| +1 |  |  | ultimaterewardspoints.chase.com | 3 | xhr | `https://ur.static.chasecdn.com/content/UltimateRewards/Ads/PROD-DATA/REMs/redeem-cash-back-lifestyle-image-ways-to-use-page/jcr:content/adcreationcontainer/par.REM.html` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/public/svgs/common/10_fa-angle-right.svg` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://midas.chase.com/prweb/PRRestService/MIDASSVCS/v1/MakeDecision?envID=&pageID=ur_travel_explore&ssv_channel=ultimaterewards&ssv_eci=0578862087&ssv_locale=en_us&ssv_pfid=135356463&ssv_product=19&ssv_random=9070597&ssv_v1st=&ssv_zip=222032164&ssv_egift_fl=true&ssv_digaccountid=622870139` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/mrm` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/load-allCategories` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/load-allLocations` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardstravel.chase.com/services/helperservices/widgetviewservice.svc/GetSearchWidget/en-US/default?Catalogid=8029` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/top-articles` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/wanderlist` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/searchDestinations?searchPage=DREAM_DESTINATION&regionId=THE_WORLD&categoryId=ALL_CATEGORIES&audienceList=` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/afartravel/latest-news` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/travel/mytrips` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/chrome/nav/menu` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | image | `https://ultimaterewardspoints.chase.com/public/favicon.ico` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/common/maintenance-list` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/common/customer-profile` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/common/messages/en` |
| +1 |  |  | ultimaterewardspoints.chase.com | 1 | xhr | `https://ultimaterewardspoints.chase.com/rest/common/env-config` |
| +0 |  |  | ultimaterewardspoints.chase.com | 1 | script | `https://ultimaterewardspoints.chase.com/public/the-app/main-es2015.83c1d1a9c3f2b772f24f.js` |
| +0 |  |  | ultimaterewardspoints.chase.com | 1 | script | `https://ultimaterewardspoints.chase.com/public/the-app/polyfills-es2015.55c82337a451de3e7880.js` |
| +0 |  |  | ultimaterewardspoints.chase.com | 1 | script | `https://ultimaterewardspoints.chase.com/public/the-app/runtime-es2015.74f85114b9627a2f58f5.js` |
| +0 | /web-analytics/* | -- | ultimaterewardspoints.chase.com | 1 | script | `https://ultimaterewardspoints.chase.com/web-analytics/ur-reporting.js` |
| +0 |  |  | ultimaterewardspoints.chase.com | 1 | css | `https://ultimaterewardspoints.chase.com/rest/chrome/nav/chrome-dynamic.css` |
| +0 |  |  | ultimaterewardspoints.chase.com | 1 | doc | `https://ultimaterewardspoints.chase.com/travel/landing?AI=622870139` |
</details>

**Comment by mapx-** [comment]
`@@||ultimaterewardspoints.chase.com/web-analytics/ur-reporting.js$script,1p`

@ryanbr
