### ISSUE TITLE
[nsfw] ci-en.dlsite.com: breakage

### ISSUE THREAD

**Issue by feltcute** [uBlockOrigin/uAssets#14013]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ci-en.dlsite.com/`

### Category

breakage

### Describe the issue

Auto-translation via wovn.io on the website breaks while uBlock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/58532836/178884474-4e6e6bcf-0652-4da0-ae86-d3bdbd9b8cde.png)
![image](https://user-images.githubusercontent.com/58532836/178884876-85260e25-ddc0-4b18-bbab-90a969c39461.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 140780
  cosmetic: 126142
  scriptlet: 31698
  html: 694
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 65724-5138, 21h.5m
    adguard-spyware: 25412-839, 21h.4m
    adguard-spyware-url: 674-14, 21h.3m
    curben-phishing: 26441-2, 20h.57m
    curben-pup: 202-0, 20h.56m
    adguard-social: 17874-28, 21h.1m
    fanboy-thirdparty_social: 69-0, 1d.19h.46m
    fanboy-cookiemonster: 36044-84, 1d.19h.45m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32814-56, 21h
    ublock-badware: 4226-3, 21h.8m
    ublock-privacy: 230-0, 11d.2h.4m
    ublock-abuse: 75-0, 10d.21h.54m
    ublock-unbreak: 1850-1, 21h.7m
    easylist: 68680-618, 21h.6m
    easyprivacy: 27403-10299, 21h.2m
    urlhaus-1: 5040-0, 20h.58m
    plowe-0: 3646-3, 1d.23h.49m
    ublock-quick-fixes: 208-0, 20h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1198 ms (selfie)
  maxAssetCacheWait: 206 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 2
    newrelic.com: 1
    pinterest.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=dlsite.com`

@Yuki2718

**Comment by Yuki2718** [comment]
Auto-translation? From where to where? I don't see any problem with or without blocker and hardly see difference in your screenshots.
@ryanbr `dlsite.com` has many subdomain, maybe better to narrow down to ci-en only.
