### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by alderson41** [uBlockOrigin/uAssets#14017]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropgalaxy.com/`
`https://dropgalaxy.com/7wfgix5pldsa`

### Category

detection

### Describe the issue

the site is detecting the adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-07-14 213906](https://user-images.githubusercontent.com/62504842/179027700-12b3c4b3-9f88-4a0b-841b-7b49d70d7794.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 164466
  cosmetic: 210318
  scriptlet: 37201
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55238-74, 12m
    adguard-generic: 65921-686, 12m
    adguard-mobile: 7957-44, 12m
    adguard-social: 17899-866, 12m
    adguard-spyware: 28732-1254, 12m
    adguard-spyware-url: 685-13, 12m
    block-lan: 43-0, 12m
    curben-phishing: 27966-0, 12m
    curben-pup: 204-1, 12m
    dpollock-0: 10406-282, 12m
    fanboy-annoyance: 75144-4217, 12m
    fanboy-cookiemonster: 36054-36054, 12m
    fanboy-social: 23240-23240, 12m
    fanboy-thirdparty_social: 68-21, 12m
    ublock-annoyances: 4488-239, 12m
  default: 
    user-filters: 0-0, never
    easylist: 68655-1271, 2d.14m
    easyprivacy: 27394-11471, 2d.13m
    plowe-0: 3646-1309, 6d.2h.8m
    ublock-abuse: 75-0, 6d.2h.6m
    ublock-badware: 4222-321, 2d.12m
    ublock-filters: 32190-3802, 2d.11m
    ublock-privacy: 226-49, 2d.10m
    ublock-quick-fixes: 204-28, 23h.50m
    ublock-unbreak: 1833-106, 2d.9m
    urlhaus-1: 5059-1, 23h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 475 ms (selfie)
  maxAssetCacheWait: 601 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    a-ads.com: 1
    cloudflareinsights.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by adsdestroyer** [comment]
> 

Works fine for me also
