### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by anapalkov** [uBlockOrigin/uAssets#14015]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://colonist.io/`

### Category

detection

### Describe the issue

after clicking play + selecting a game mode a screen pops up linking to:
https://colonist.io/disable_ad_block

this issue came with an update of the website 2 days ago

### Screenshot(s)

<img src = "https://i.imgur.com/NzD9XNE.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79978
  cosmetic: 44557
  scriptlet: 17440
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 68539-50, 3d.22h.35m
    easyprivacy: 27375-122, 3d.22h.34m
    plowe-0: 3646-780, 4h.39m
    ublock-abuse: 75-0, 4h.38m
    ublock-badware: 4202-93, 3d.22h.33m
    ublock-filters: 32141-98, 3d.22h.32m
    ublock-privacy: 226-3, 4h.37m
    ublock-quick-fixes: 216-3, 4h.35m
    ublock-unbreak: 1831-42, 3d.22h.31m
    urlhaus-1: 5082-0, 4h.34m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2642 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adinplay.com: 1
    googleoptimize.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 2
    lr-ingest.io: 1
    threetruck.com: 1
    vlitag.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@anapalkov the anti adblock got fixed. To get the fix directly force update the filter lists
