### ISSUE TITLE
vezifilme.online ads

### ISSUE THREAD

**Issue by mortyam** [uBlockOrigin/uAssets#14016]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vezifilme.online/the-black-phone-online-subtitrat/`

### Describe the issue

On the video player after I press the "PLAY" button and I skip to another minute(ike 16:03) ads appear.

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 102

### Settings

No changes to uBO's default settings.

**Comment by mapx-** [comment]
It seems to be a fake movie site
