### ISSUE TITLE
next-episode.net [Anti-Adblock]

### ISSUE THREAD

**Issue by kaktus42** [uBlockOrigin/uAssets#1401]
### URL(s) where the issue occurs

`https://next-episode.net/` **when logged in**

### Describe the issue

After logging in, an anti-adblock modal appears, blocking access to the site and giving instructions for whitelisting.

### Screenshot(s)

![anti-adblock](https://i.imgur.com/PjY7Fsx.png)

### Versions

- Browser/version: Firefox 57.0.4 (64-Bit)
- Nano Defender version: 13.20
- Nano Adblocker version: 1.0.0.28

**Comment by mapx-** [comment]
test this filter
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=next-episode.net`

**Comment by okiehsch** [comment]
I can't reproduce, I am logged in with a default setup using Chrome/Firefox.

![nextt](https://user-images.githubusercontent.com/16838044/35475964-18224bee-03a8-11e8-82c3-b5d5b188716f.JPG)

**Comment by mapx-** [comment]
3 years ago:
https://forums.lanik.us/viewtopic.php?f=62&t=23809

**Comment by okiehsch** [comment]
OK, so you have to wait a couple of days after you sign up to get the anti-adblock warning.

**Comment by kaktus42** [comment]
Thanks! It works now. And awesome response time <3
