### ISSUE TITLE
thizissam.in: detection

### ISSUE THREAD

**Issue by zOmar11** [uBlockOrigin/uAssets#14029]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thizissam.in/`

### Category

detection

### Describe the issue

this website detects ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80007
  cosmetic: 44597
  scriptlet: 17461
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68614-50, 3d.19h.18m
    easyprivacy: 27385-122, 3d.19h.17m
    plowe-0: 3646-780, 7d.3h
    ublock-abuse: 75-0, 8d.18h.5m
    ublock-badware: 4223-94, 3d.19h.16m
    ublock-filters: 32176-101, 3d.19h.15m
    ublock-privacy: 224-3, 8d.18h.4m
    ublock-quick-fixes: 216-4, 21h.9m
    ublock-unbreak: 1833-42, 3d.19h.14m
    urlhaus-1: 5040-0, 21h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 720 ms (selfie)
  maxAssetCacheWait: 459 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    thizissam.in: 9
    adtrackers.net: 1
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 2
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    livetrafficfeed.com: 2
    yahoo.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||thizissam.in^$ghide
```

**Comment by garry-ut99** [comment]
Ad placeholders all over the site, caused by `ghide` from "uBlock Filters", on both main page and subpages:
[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219353221-be328bd3-246b-4e3c-b041-95e95fe9b749.png) (mainpage) [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219353235-b3a9f08f-bf61-4060-a25e-95c7e5f12ff1.png) (subpage), I get no AA with `ghide` off but there is AA still in the source code, so if not removing `ghide`, then maybe: `thizissam.in##.ad-container, .adsbygoogle`
