### ISSUE TITLE
skypost.ulifestyle.com.hk: breakage

### ISSUE THREAD

**Issue by randomguyingithub** [uBlockOrigin/uAssets#14023]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://skypost.ulifestyle.com.hk/article/3301395/%E6%B6%88%E8%B2%BB%E5%88%B8%20%EF%B8%B3%E5%85%A8%E8%81%B7%E5%AA%BD%E5%AA%BD%E6%94%B6%E4%B8%8D%E7%8D%B2%E7%99%BC%245000%E6%B6%88%E8%B2%BB%E5%88%B8%E8%A8%8A%E6%81%AF%204%E5%A4%A7Q%26A%E6%8B%86%E8%A7%A3%E4%B8%8A%E8%A8%B4%E6%96%B9%E6%B3%95`

### Category

breakage

### Describe the issue

The website doesn't let you scroll (e.g remove the scroll bar and using the mouse wheel doesn't work) when ublock origin is enabled. 

Tested on Edge (applies to Prerequisites/checkpoints)  and Firefox (may not apply to Prerequisites/checkpoints as custom filter was used before, don't know if the rules are synced after reinstall)

Bypass (Tested on Edge): disable ublock, refresh, enable again, then refresh.

### Screenshot(s)

<details>
<summary>

https://user-images.githubusercontent.com/13596387/179164327-de767dff-e7a2-4127-a747-095452c6a9c4.png

https://user-images.githubusercontent.com/13596387/179164347-07b90d84-981d-441f-87d5-352c72281acb.png
</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80068
  cosmetic: 44621
  scriptlet: 17428
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32825-39, 3d.9m
    ublock-badware: 4227-3, 3d.8m
    ublock-privacy: 232-0, 22h.47m
    ublock-abuse: 75-0, 22h.46m
    ublock-unbreak: 1849-0, 3d.7m
    ublock-quick-fixes: 213-0, 18h.11m
    easylist: 68638-571, 3d.6m
    easyprivacy: 27394-581, 3d.5m
    urlhaus-1: 5082-0, 18h.10m
    plowe-0: 3646-3, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 679 ms (selfie)
  maxAssetCacheWait: 399 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    ulifestyle.com.hk: 4
    facebook.com: 1
    facebook.net: 1
    googleads.github.io: 12
    googletagmanager.com: 1
    hotjar.com: 1
    imasdk.googleapis.com: 2
    scorecardresearch.com: 1
```
</details>

**Comment by randomguyingithub** [comment]
You sneak the not word at last checkpoint so sneaky there, I didn't see it

**Comment by mapx-** [comment]
Enable `CHN: AdGuard Chinese (中文)`

**Comment by JasonHK** [comment]
> Enable `CHN: AdGuard Chinese (中文)`

@mapx- Enable AdGuard Chinese DOES NOT fix the issue. The way I fix it is by the following rule: `ulifestyle.com.hk#$#body:not(.scrollable) { overflow: revert !important }`

**Comment by MasterKia** [comment]
@Yuki2718 AG Chinese

**Comment by Yuki2718** [comment]
On my end this happens only on mobile. Maybe for Mobile filters.

**Comment by MasterKia** [comment]
I could reproduce on Firefox mobile as well.

**Comment by JasonHK** [comment]
The issue is also occurs on desktop. It also only occurs in some subpages. Finally, it's not just occurred on skypost.ulifestyle.com.hk, but alsoon food.ulifestyle.com.hk and ezone.ulifestyle.com.hk (maybe there's more that I didn't notice).

**Comment by Yuki2718** [comment]
@JasonHK Okay, then I'll move the rule to Chinese filters.

**Comment by MasterKia** [comment]
> It only occurs in some subpages.

Link?
