### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Allu71** [uBlockOrigin/uAssets#14022]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79911
  cosmetic: 46286
  scriptlet: 17481
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    FIN-0: 1845-1, 23h.3m
    easylist: 68363-52, 23h.3m
    easyprivacy: 27403-124, 23h.3m
    plowe-0: 3646-780, 23h.3m
    ublock-abuse: 75-0, 23h.3m
    ublock-badware: 4219-94, 23h.3m
    ublock-filters: 32154-109, 23h.3m
    ublock-privacy: 226-3, 23h.3m
    ublock-quick-fixes: 216-14, 23h.3m
    ublock-unbreak: 1834-42, 23h.3m
    urlhaus-1: 5082-0, 23h.3m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 485 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
