### ISSUE TITLE
3dmili.com: detection

### ISSUE THREAD

**Issue by zekosan** [uBlockOrigin/uAssets#14024]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://3dmili.com/hdri`

### Category

detection

### Describe the issue

detects adblock and orders to disable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![arara](https://user-images.githubusercontent.com/109336753/179168572-8bc89163-f423-4a85-8c9f-ee0908778ef3.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 83531
  cosmetic: 45146
  scriptlet: 34207
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23888-26, 19m
  default: 
    user-filters: 0-0, never
    easylist: 68375-57, 15m
    easyprivacy: 27414-123, 14m
    plowe-0: 3647-780, 11d.23h.45m
    ublock-abuse: 75-1, 21m
    ublock-badware: 4223-94, 20m
    ublock-filters: 32167-2894, 13m
    ublock-privacy: 224-3, 16m
    ublock-quick-fixes: 216-15, 18m
    ublock-unbreak: 1834-43, 22m
    urlhaus-1: 5027-0, 17m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 325 ms
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by huyszn** [comment]
"Adblocker Enabled" message: https://github.com/uBlockOrigin/uAssets/assets/46979193/4934a984-88a1-4672-ae27-3386a45ad995

`3dmili.com##+js(aost, setTimeout, ads)`
