### ISSUE TITLE
msn.com: detection

### ISSUE THREAD

**Issue by grfxwzdesigner** [uBlockOrigin/uAssets#14028]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.msn.com/`

### Category

detection

### Describe the issue

This problem pertains to Firefox.  All areas previously blocked now show up on the web page (msn.com opening page).  If I try to block any area, the entire page is automatically selected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>![Uploading NOTHING blocked.JPG…]()
![Uploading NOTHING blocked.JPG…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79693
  cosmetic: 44666
  scriptlet: 17431
  html: 696
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-1, never
    ublock-filters: 32841-50, 1d.23h.56m
    ublock-badware: 4226-3, 2d.23h.50m
    ublock-privacy: 230-0, 13d.12m
    ublock-abuse: 75-0, 1d.19h.44m
    ublock-unbreak: 1850-0, 1d.23h.32m
    easylist: 68344-589, 1d.23h.55m
    easyprivacy: 27394-581, 2d.23h.49m
    urlhaus-1: 5040-0, 23h.53m
    plowe-0: 3647-3, 9d.19h.54m
    ublock-quick-fixes: 213-0, 11h.5m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 739 ms (selfie)
  maxAssetCacheWait: 476 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    msn.com: 19
    akadns.net: 1
    azure.com: 2
    btloader.com: 3
    microsoft.com: 7
    scorecardresearch.com: 1
    yahoo.com: 2
```
</details>

**Comment by MasterKia** [comment]
Please re-upload your screenshots.

**Comment by mapx-** [comment]
> detection

No detection => invalid

> If I try to block any area, the entire page is automatically selected

I cannot reproduce it.
