### ISSUE TITLE
movie4k.is

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#1402]
### URL(s) where the issue occurs

`movie4k.is`

### Describe the issue

Popups and miner

### Versions

- Browser/version: Chrome 64
- uBlock Origin version: 1.14.24

### Settings

- default

**Comment by ghajini** [comment]
There's a popup when clicking `option 3 and option 4`....any custom filter for that?
`https://www1.movie4k.is/7211-watch-anna-2-online-movie4k.html`

**Comment by bogachenko** [comment]
@Yuki2718 add to the list `movie4k.dev##+js(nano-setTimeout-booster)`

**Comment by Omega-6** [comment]
obsolete filters
