### ISSUE TITLE
discover.com: breakage

### ISSUE THREAD

**Issue by FrostyNick** [uBlockOrigin/uAssets#14020]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.discover.com/`

### Category

breakage

### Describe the issue

After verifying my account, it let to a page that had "cookie-error" or something like that.  I can't reproduce this to my knowledge. 

Logging in though doesn't work in general. It will show an error that "The information you provided does not match our records. Please re-enter your login information below." from [this login screen](https://portal.discover.com/customersvcs/universalLogin/signin).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79687
  cosmetic: 44626
  scriptlet: 17355
  html: 693
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32688-38, 2d.1h.37m
    ublock-badware: 4227-3, 30m
    ublock-privacy: 230-0, 8d.23h.17m
    ublock-abuse: 75-0, 8d.23h.16m
    ublock-unbreak: 1850-0, 29m
    ublock-quick-fixes: 213-0, 25m
    easylist: 68368-590, 28m
    easyprivacy: 27409-581, 27m
    urlhaus-1: 5040-0, 26m
    plowe-0: 3647-3, 8d.23h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 308 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    discover.com: 3
    app.link: 3
    btstatic.com: 1
    demdex.net: 3
    doubleclick.net: 1
```
</details>

**Comment by mapx-** [comment]
Does this help ?

`@@||portal.discover.com/global/scripts/visitorAPI.js$script,1p`

**Comment by FrostyNick** [comment]
Okay, it seems like it works now without modifying filters. I've logged out and back in three times with no breakage anymore.

Also tried logging out and back in after clearing cookies, still working with no breakage.
