### ISSUE TITLE
ebay-kleinanzeigen.de: breakage

### ISSUE THREAD

**Issue by coffeedrank** [uBlockOrigin/uAssets#14039]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ebay-kleinanzeigen.de/s-anzeige/skyridge-und-aquapolis-pokemon-karten/2149467815-234-1736`

### Category

breakage

### Describe the issue

`www.ebay-kleinanzeigen.de` is a german marketplace for reselling used goods. 

When opening any product site, it shows a gallery with the pictures of the product and a description.

Issue: Clicking on the gallery does not open image in bigger format

Expected behaviour: Clicking on an image in the gallery opens the gallery "full screen" and the picture in bigger view

Real behaviour: Clicking on an image in the gallery opens the gallery "full screen", but the picture in bigger view doesnt show

The great blank space in front of the background should show the image in bigger. (see screenshot)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/109411469/179346753-f66d6bc7-e25b-4aab-ad75-0ef8776cac6e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 255638
  cosmetic: 315866
  scriptlet: 40282
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    ALB-0: 267-1, 2h.20m
    BGR-0: 1091-11, 2d.12h.33m
    CHN-0: 28598-92, 2d.12h.33m
    CZE-0: 715-0, 2h.17m
    EST-0: 450-1, 2h.7m
    FIN-0: 1846-1, 2d.12h.33m
    FRA-0: 29410-69, 2d.12h.33m
    GRC-0: 1002-0, 12h.31m
    HUN-0: 2149-6, 2h.4m
    IDN-0: 8993-22, 2d.12h.33m
    IND-0: 11025-0, 2h.16m
    IRN-0: 1780-1, 12h.32m
    ISL-0: 194-1, 2d.12h.33m
    ISR-0: 1635-2, 2h.13m
    ITA-0: 13108-72, 2h.19m
    JPN-1: 7594-17, 2d.12h.33m
    KOR-1: 2095-12, 2h.11m
    LTU-0: 1194-7, 2d.12h.33m
    LVA-0: 397-2, 2d.12h.33m
    NLD-0: 2427-19, 2d.12h.33m
    [28 lists not shown]: [too many]
  default: 
    DEU-0: 5891-0, 2h.8m
    easylist: 68368-1542, 1d.14h.55m
    easyprivacy: 27421-11844, 16h.23m
    plowe-0: 3646-1343, 2d.12h.33m
    ublock-abuse: 75-2, 2d.12h.33m
    ublock-badware: 4233-338, 2d.12h.32m
    ublock-filters: 32149-4130, 2d.12h.32m
    ublock-privacy: 226-50, 2d.12h.32m
    ublock-quick-fixes: 216-26, 2h.6m
    ublock-unbreak: 1834-134, 2d.12h.32m
    urlhaus-1: 4979-1, 2h.5m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1125 ms
  maxAssetCacheWait: 691 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    ebay-kleinanzeigen.de: 5
    amazon-adsystem.com: 1
    ebay.de: 1
    facebook.net: 1
    google.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists





> ```yaml
>   added: 
>     ALB-0: 267-1, 2h.20m
>     BGR-0: 1091-11, 2d.12h.33m
>     CHN-0: 28598-92, 2d.12h.33m
>     CZE-0: 715-0, 2h.17m
>     EST-0: 450-1, 2h.7m
>     FIN-0: 1846-1, 2d.12h.33m
>     FRA-0: 29410-69, 2d.12h.33m
>     GRC-0: 1002-0, 12h.31m
>     HUN-0: 2149-6, 2h.4m
>     IDN-0: 8993-22, 2d.12h.33m
>     IND-0: 11025-0, 2h.16m
>     IRN-0: 1780-1, 12h.32m
>     ISL-0: 194-1, 2d.12h.33m
>     ISR-0: 1635-2, 2h.13m
>     ITA-0: 13108-72, 2h.19m
>     JPN-1: 7594-17, 2d.12h.33m
>     KOR-1: 2095-12, 2h.11m
>     LTU-0: 1194-7, 2d.12h.33m
>     LVA-0: 397-2, 2d.12h.33m
>     NLD-0: 2427-19, 2d.12h.33m
>     [28 lists not shown]: [too many]
> ```

Did you try with _only_ the default lists?

**Comment by mapx-** [comment]
yeah, because you enabled all the planet filters

add

`#@#.ad-image`

AR list @smed79 => such filters are for EL list not for regional lists

**Comment by VetaLioSTV** [comment]
I think its broken on ebay-kleinanzeigen itself, because i remember that annoying problem earlier. One of image are not loaded and not visible in full mode of gallery. Try to disable uBlock and check how it works.

PS @coffeedrank right now(and i think for month+) there is another problem, when you stay on ebay-kleinanzeigen "for some reason" ublock "sometimes"doing redirect to ebay.com which is ultra-ultra annoying. Do you have same behavior?
