### ISSUE TITLE
Juno.finance live chat broken

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#14031]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://juno.finance/support`

### Describe the issue

Live chat doesn't work. Might need to be logged in.

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 103

### Settings

Default

### Notes

`@@||o425957.ingest.sentry.io^$xhr,domain=juno.finance`

**Comment by terrorist96** [comment]
Actually you can reproduce on the login page too.
`https://juno.finance/login`

The bubble at the bottom right doesn't appear without the whitelist filter noted above.

**Comment by terrorist96** [comment]
Reproducibility is sketchy though.. so let me know if it works for y'all.

**Comment by terrorist96** [comment]
Blocking sentry.io is also causing some other issues, like here:
`https://juno.finance/stellar-madness`
requires login.

**Comment by terrorist96** [comment]
I think the following is needed too:
```
@@||d2r1yp2w7bby2u.cloudfront.net/js/a.js$script,domain=juno.finance
@@||us1.wzrkt.com^$script,domain=juno.finance
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by terrorist96** [comment]
@mapx- actually I think cloudfront and wzrkt can be blocked. The issue I thought they were causing is still present with uBO disabled, so might be a site issue.

**Comment by ryanbr** [comment]
`@@||us1.wzrkt.com^$script,domain=juno.finance` isn't needed.
