### ISSUE TITLE
nexuspipe.com: breakage

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#14033]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nexuspipe.com/`

### Category

breakage

### Describe the issue

when you're flagged by nexuspipe, it's anti-adblock refuses to load the captcha image, causing hardened firefox users unable to access the site
openfpcdn.io being unblocked seems for it to work? (speculation), but that's fingerprintjs
tfw privacy.resistFingerprinting turned on flags you
tested this on blank, stock firefox with reset ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

on
![image](https://user-images.githubusercontent.com/104040739/179323343-96d60e90-bac1-44ae-a961-7f6d0f39726c.png)
off
![image](https://user-images.githubusercontent.com/104040739/179323353-88d57f3d-7506-4db3-bd6b-eb7b002b33f6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 89593
  cosmetic: 110872
  scriptlet: 18919
  html: 694
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1921-0, 19h.49m
    adguard-spyware-url: 674-99, 3d.7h.21m
    fanboy-annoyance: 75078-241, 7d.19h.50m
  default: 
    user-filters: 18-0, never
    ublock-filters: 32812-35, 3d.7h.25m
    ublock-badware: 4227-4, 3d.7h.24m
    ublock-privacy: 229-2, 7d.19h.50m
    ublock-abuse: 75-0, 7d.19h.50m
    ublock-unbreak: 1849-31, 3d.7h.23m
    ublock-quick-fixes: 213-3, 19h.51m
    easylist: 68655-600, 3d.7h.22m
    easyprivacy: 27394-102, 3d.7h.20m
    urlhaus-1: 5027-0, 19h.50m
    plowe-0: 3647-452, 7d.19h.50m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 216 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 1
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 42751 ms (selfie)
  maxAssetCacheWait: 1350 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    openfpcdn.io: 1
    openreplay.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in details?

**Comment by mapx-** [comment]
add

`@@||openfpcdn.io/fingerprintjs/$script`

@ryanbr
