### ISSUE TITLE
drakescans.com: detection

### ISSUE THREAD

**Issue by Moonwolf287** [uBlockOrigin/uAssets#14035]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://drakescans.com/`

### Category

detection

### Describe the issue

As soon as you open the website an overlay will block you from going further. It seems to be powered by "CHP Adblock Detector".

Tried the same in a clean firefox profile with only uBlock installed and it still appears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/1161223/179328432-32144d71-9e57-4e17-a844-ae728ac38d17.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79641
  cosmetic: 44588
  scriptlet: 17361
  html: 706
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Yumire/kiss-filters/master/filters.txt: 24-0, now
  default: 
    user-filters: 7-0, never
    ublock-filters: 32792-37, now
    ublock-badware: 4224-3, now
    ublock-privacy: 240-0, now
    ublock-abuse: 75-0, now
    ublock-unbreak: 1853-0, now
    easylist: 68405-576, now
    easyprivacy: 27423-581, now
    plowe-0: 3644-3, now
    urlhaus-1: 4979-0, now
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6815 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    drakescans.com: 1
    discord.com: 2
    facebook.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
drakescans.com##+js(no-fetch-if, ads.)
```

**Comment by gorhill** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/11xnmf1/cant_block_antiishadblocker_wrap/

Oops, I didn't see it was already fixed.
