### ISSUE TITLE
tv.gab.com youtube-like ads

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#14037]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tv.gab.com/channel/a/view/gab-community-update-july-2022-62c6ff755733bc63441757d0`

### Describe the issue

gab tv now has ads just like youtube, they keep showing up whether ublock origin is on or off.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/179342792-e5705958-2756-4aa7-a524-dfaf1f071ef5.png)

### uBlock Origin version

1.42.4

### Browser name and version

Chrome 103.0.5060.114

### Settings

Default

**Comment by mapx-** [comment]
Test 

```
||grow.gab.com/get/status?video=tv$xhr,domain=tv.gab.com,redirect=nooptext
||grow.gab.com/galahad/$media
tv.gab.com###ad-clicks-overlay
```

**Comment by Mennaruuk** [comment]
> Test
> 
> ```
> ||grow.gab.com/get/status?video=tv$xhr,domain=tv.gab.com,redirect=nooptext
> ||grow.gab.com/galahad/$media
> tv.gab.com###ad-clicks-overlay
> ```

works like a charm! 🤩 you're so smart, i don't know how you figured it out, but those pesky ads are no more!!! thank you so much
