### ISSUE TITLE
solarmovie.pe => popups

### ISSUE THREAD

**Issue by Alsbach-14** [uBlockOrigin/uAssets#14034]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

solarmovie.pe => clicking => popup:
`https://www.fetishpartner.com/landing/gn8007?clickId=29cecee4-d59f-4c31-afe5-a7872584c0ce&tracker=SGM_Pro&publisher=30610&subPublisher=E78HPGP632&zz=true&hit_id=29cecee4-d59f-4c31-afe5-a7872584c0ce&tp_redirect_id=29cecee4-d59f-4c31-afe5-a7872584c0ce`

### Category

ads

### Describe the issue

i was watching a show on a website and normallt it would block thew popup and well it didnt this time and well a porn scam wabsite popped up and took me by surprise.
if i could get a resposne on why that would be great.

the website :
`https://www.fetishpartner.com/landing/gn8007?clickId=29cecee4-d59f-4c31-afe5-a7872584c0ce&tracker=SGM_Pro&publisher=30610&subPublisher=E78HPGP632&zz=true&hit_id=29cecee4-d59f-4c31-afe5-a7872584c0ce&tp_redirect_id=29cecee4-d59f-4c31-afe5-a7872584c0ce`

thank you for reading this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80035
  cosmetic: 44625
  scriptlet: 17465
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68655-50, 3d.8h.39m
    easyprivacy: 27394-122, 3d.8h.38m
    plowe-0: 3646-780, 2d.1h.51m
    ublock-abuse: 75-0, 3d.21h.21m
    ublock-badware: 4223-94, 3d.8h.37m
    ublock-filters: 32190-101, 3d.8h.36m
    ublock-privacy: 226-3, 3d.21h.20m
    ublock-quick-fixes: 216-14, 1h.57m
    ublock-unbreak: 1833-42, 3d.4h.32m
    urlhaus-1: 5043-0, 1h.56m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 24785 ms (selfie)
  maxAssetCacheWait: 655 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    onesignal.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in details? Looks like the link you give is the popup link after clicking on original link?

**Comment by Alsbach-14** [comment]
well i went to go play the the show and well that link popped up and it was
quite unusual because it never seemed to do this any other time
the link i was on :
https://solarmovie.pe/watch-tv/watch-the-boys-free-33895.8371990

kind regards

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Which browser were you using and which server of that site did you choose? Can you force update the filter lists and check again?

**Comment by Alsbach-14** [comment]
I think it might of been a one off and the ublock may not have loaded in
yet.
I'm sorry for wasting your time.
And have a wonderful day!

Kind regards
