### ISSUE TITLE
ffxiv.gamerescape.com: ads

### ISSUE THREAD

**Issue by RustyLovecraft** [uBlockOrigin/uAssets#14036]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gamerescape.com/`

### Category

ads

### Describe the issue

Hi, I love uBlock. <3 It is a nearly flawless solution.
This issue seems to have been reported before with insufficient details: https://github.com/uBlockOrigin/uAssets/issues/11112 and was deemed non reproducible.

Ad leftovers: When I try removing the top banner ad for this site's membership (appears on all pages on this website), I am left with the background image that is still a clickable link to buying their service at `gamerescape.com/subscribe`. I can try zapping or filtering repeatedly but no success there.

The stubborn element is called `||www.gamerescape.com/images/cta_space.png` . 
I can disable an element that's on top of it: `||gamerescape.com/images/cta_ad.png` . And the "close this ad" bar below, `##.cta-collapse`

Removing the latter two makes the distraction less intrusive, but `cta_space.png` still wastes lots of space, and it's less than ideal on a wiki site. I am guessing this is an anti-adblock thing. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![beforeAfter](https://user-images.githubusercontent.com/55685536/179328773-8c696feb-cde3-46dd-93db-029f278bcf05.jpg)
![elements](https://user-images.githubusercontent.com/55685536/179328778-9825da3d-3cc9-4e80-9a66-5b575ef42b4d.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80027
  cosmetic: 44629
  scriptlet: 17412
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 34-2, never
    ublock-filters: 32801-107, 3d.19h.25m
    ublock-badware: 4227-3, 3d.19h.24m
    ublock-privacy: 232-0, 1d.15h.50m
    ublock-abuse: 75-0, 1d.15h.49m
    ublock-unbreak: 1849-0, 3d.19h.23m
    easylist: 68637-491, 3d.19h.22m
    easyprivacy: 27394-594, 3d.19h.21m
    urlhaus-1: 5027-0, 21h.46m
    plowe-0: 3646-3, 5d.33m
    ublock-quick-fixes: 213-0, 21h.47m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 231 ms (selfie)
  maxAssetCacheWait: 93 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    gamerescape.com: 3
    aaxads.com: 2
    cloudflareinsights.com: 2
    disqus.com: 3
    google-analytics.com: 1
    rlcdn.com: 1
    vntsm.com: 2
    wp.com: 3
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
gamerescape.com##.cta, .cta-collapse
```

In your screenshots you can see these 2 classnames in the "cosmetic filters" propositions.

**Comment by stephenhawk8054** [comment]
You can add the above filter to `My filters`, it's a self-promo section.
