### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by victorgonzcuriel** [uBlockOrigin/uAssets#14032]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

ads still running

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 83165
  cosmetic: 49486
  scriptlet: 17662
  html: 694
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32837-35, 3d.5h.23m
    ublock-badware: 4227-4, 3d.5h.22m
    ublock-privacy: 232-0, 3d.5h.21m
    ublock-abuse: 75-0, 3d.5h.17m
    ublock-unbreak: 1849-0, 3d.5h.16m
    ublock-quick-fixes: 221-14, 4m
    easylist: 68669-656, 3d.4h.54m
    easyprivacy: 27394-597, 3d.4h.53m
    urlhaus-1: 5043-0, 3m
    plowe-0: 3646-3, 3d.4h.51m
    spa-0: 3900-20, 5m
    spa-1: 4564-144, 3d.5h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  largeMediaSize: 20480
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 496 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 23
  no-large-media: true
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 18
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by mapx-** [comment]
see other indications https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
