### ISSUE TITLE
wpking.in: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#14041]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wpking.in/`

### Category

detection

### Describe the issue

This site does not display content when uBo is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/179353639-95e306c4-d15c-43d1-91ee-b3469a622d8b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 83800
  cosmetic: 49384
  scriptlet: 17397
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 20-0, never
    IDN-0: 8993-0, 7m
    easylist: 68408-57, 7m
    easyprivacy: 27422-125, 7m
    plowe-0: 3647-780, 12d.4h.19m
    ublock-abuse: 75-0, 7m
    ublock-badware: 4224-94, 7m
    ublock-filters: 32158-137, 7m
    ublock-privacy: 226-3, 7m
    ublock-unbreak: 1836-43, 7m
    urlhaus-1: 4979-0, 5h.12m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 591 ms (selfie)
  maxAssetCacheWait: 459 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    bmcdn3.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    greeter.me: 2
    modoro360.com: 1
    netpub.media: 8
    wtg-ads.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original link that redirects to that?

**Comment by yohanes4dip** [comment]
https://wpking.in/?link=NrTv
