### ISSUE TITLE
rarpc.co: badware

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#14045]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rarpc.co/idm-crack-patch/`

### Category

[unknown]

### Describe the issue

`https://www.virustotal.com/gui/file/7bd70210fb934588a8b73f57863add9a25a21f921ca40032be5e12f88c69aaa9`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80412
  cosmetic: 45748
  scriptlet: 17459
  html: 706
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32823-126, 30m
    ublock-badware: 4228-3, 30m
    ublock-privacy: 240-0, 30m
    ublock-abuse: 77-0, 30m
    ublock-unbreak: 1852-0, 30m
    ublock-quick-fixes: 224-0, 30m
    easylist: 68410-511, 30m
    easyprivacy: 27422-585, 30m
    urlhaus-1: 4970-0, 30m
    plowe-0: 3644-3, 30m
    VIE-1: 1836-1, 30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 263 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    wp.com: 2
```
</details>

**Comment by MasterKia** [comment]
IMO 6 random antivirus out of 65 is too low/meaningless.

Also most if not all software "cracks/patches/keygens" get flagged by some _AV_.

So should we block _all_ software crack sites?

**Comment by zeref-dragneel** [comment]
It's not a software crack site. You can see that all download links lead to only one file

**Comment by MasterKia** [comment]
> all download links lead to **_only one file_**

`https://rarpc.co/ant-download-manager-pro-crack/` => `https://usersdrive.com/fxenbn8uclpz.html` (35.8 MB)
`https://rarpc.co/pepakura-designer-crack-keygen/` => `https://usersdrive.com/b0ffn43oil0c.html` (40.6 MB)
`https://rarpc.co/adobe-acrobat-pro-dc-crack-keys-july-8/` => `https://usersdrive.com/0zi3mjqi5iy5.html` (1.1 GB)

**Comment by zeref-dragneel** [comment]
WTF? Are you the owner of the website? Why do my downloads lead to a zip file with password 1234

**Comment by MasterKia** [comment]
Because you're click on the [in my opinion] "fake" download buttons.

![image](https://user-images.githubusercontent.com/17685483/179361129-cb713d53-fe8d-4085-9c55-f6ed41b59334.png)
![image](https://user-images.githubusercontent.com/17685483/179361131-5ecc6fc9-4abd-4f70-9274-98883aa0fd2c.png)
![image](https://user-images.githubusercontent.com/17685483/179361144-4f10028f-3861-4c14-901a-ff5de0b1c058.png)


I guess the legit link is at the bottom:
![image](https://user-images.githubusercontent.com/17685483/179361162-33942393-ef1d-4614-8a8b-a9ab8fc90b28.png)

**Comment by MasterKia** [comment]
@mapx- 

`##button` or `##button:has-text(DOWNLOAD)` ?

**Comment by zeref-dragneel** [comment]
So the site tries to create a fake link for the user to download the bad software. uBlock Origin will keep users away from sites like this. There are many websites to download safely, please help users stay away from these sites

**Comment by zeref-dragneel** [comment]
Similar sites:
`warecracks.com`
`procrackserial.com`
`piratespc.net`
`crackmacware.com`
`getsoftcrack.com`
`94fbr.org`
`cdcrack.org`
`keysfiles.com`
`allpcprocrack.co`

**Comment by MasterKia** [comment]
> So the site tries to create a fake link for the user to download the bad software. 

AFAIK It's not uncommon for even legit sites to sometimes do this as advertisement/promotion (have one fake and one real download button).
Usually they only have one fake button, not three.

For example, `farsroid.com` is a legit site to download Android apps and games.
`https://www.farsroid.com/empires-puzzles-rpg-quest/`:
https://user-images.githubusercontent.com/17685483/179361396-fd6acf23-eca4-4570-9715-c938d04775b5.png
In this case, a (harmless?) messenger app called "iGap" gets downloaded if user clicks on the fake button.








> uBlock Origin will keep users away from sites like this. please help users stay away from these sites

IMO blocking the fake download buttons should suffice.

**Comment by mapx-** [comment]
for example

`rarpc.co,warecracks.com##[onclick*="open"]`

@zeref-dragneel you could prepare filters like this above and propose to easylist

@ryanbr

**Comment by zeref-dragneel** [comment]
I see many websites are blocked, for example #9955, #11310,...
https://ublockorigin.github.io/uAssets/filters/badware.txt
Why is there a website that is blocked entirely, but there is a website that only blocks the download button.

**Comment by JobcenterTycoon** [comment]
Even the "real" download get flagged by 27 antivirus

https://www.virustotal.com/gui/file/05919c527c0bb13361cf6b75f0d97036707ff05e103fa8a427c5eba7549264f1?nocache=1

**Comment by MasterKia** [comment]
Software cracks usually get flagged by most AV.

**Comment by MasterKia** [comment]
Software cracks usually get flagged by most AV.

I just downloaded IDM with crack from a legit site, Windows defender:
![image](https://user-images.githubusercontent.com/17685483/179398665-5a0c27bb-9fbc-4612-b31d-1e91a3e591fc.png)

`https://soft98.ir/internet/download-manager/4-%D8%A7%DB%8C%D9%86%D8%AA%D9%80%D8%B1%D9%86%D9%80%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D9%85%D9%86%DB%8C%D8%AC%D9%80%D8%B1.html`

**Comment by JobcenterTycoon** [comment]
And this is why a few users disable the antivirus when a real virus get detected but the user think its not a virus because the site say this.

Ok back to the topic i tested a few sites and the fake buttons are not always the same but they are clearly different and can be easily hidden. Hard blocks are no longer needed but there are MANY sites (over 150)

**Comment by MasterKia** [comment]
> there are MANY sites (over 150)

https://github.com/uBlockOrigin/uAssets#porn-farms

Maybe should add another rule:
**Crack-farms**
_Sites found to be crack-farms (families of mass-produced software crack sites without any original contents) or part of crack-farms will not be addressed in uAssets._

**Comment by JobcenterTycoon** [comment]
To protect the user its good to add fixes as long the site is popular enough. I already work on it to make the hard blocks obsolete

**Comment by MasterKia** [comment]
Let's hope these sites don't bundle _malicious_ software cracks.

**Comment by JobcenterTycoon** [comment]
@ryanbr @mapx- 

```
goharpc.com,procrackerz.org,pccrackbox.com,365crack.com,cracklabel.com,keystool.com,pcwarezbox.com,10crack.com,crackproductkey.com,profullversion.com,allcracks.org,crackswall.com,crackpcsoft.net,proappcrack.com,flstudiocrack.org,crackwinz.com,crackedpcs.com,cracksmad.com,excrack.com,mahcrack.com,get4pcs.com,genuineactivator.com,keygenwin.com,crackedroot.com,topcracked.com,mycrackfree.com,crackfullpro.com,crackpro.org,fullcrackedpc.com,crackkey4u.com,rootcracks.org,getproductkey.co,idmfullcrack.info,fileserialkey.com,licensekeyup.com,thecrackbox.com,cracksway.com,clevercracks.com,idmpatched.com,autocracking.com,macwinsofts.com,productkeyfree.org,chcracked.com,cracksdat.com,patchcracks.com,piratpc.com,cracksole.com,finalcracked.com,activatorpros.com,miraclecrack.com,allsoftwarekeys.com,softwar2crack.com,procracks.net,productkeyforfree.com,crackgrid.com,licensekeysfree.com,crackedmod.com,crackedpc.org,whitecracked.com,kalicrack.com,bypassapp.com,zgamespc.com,cracksoon.com,boxcracked.com,activationkey.org,newproductkey.com,serialkeypatch.org,serialkeysfree.org,crackdev.com,wazusoft.com,getpcsofts.net,patchlinks.com,rootscrack.com,cracktel.com,crackedsoftpc.com,idmfullversion.com,activators4windows.com,crackfury.com,proapkcrack.com,up4crack.com,crackkeymac.com,softscracked.com,freeappstorepc.com,reallpccrack.com,cracknew.org,crackfullkey.net,torrentfilefree.com,hitcracker.com,fullactivationkey.com,hmzapc.com,9to5crack.com,greencracks.com,zcracked.com,cracka2zsoft.com,masterkreatif.net,onhax.io,usecracked.com,crackedversion.com,freecrack4u.com,procrackhere.com,crackedmacapps.com,proproductkey.com,crackpckey.com,aryancrack.com,crack11.com,piratespc.net##[onclick*="open"]
filepapa.com,serialkey89.com,pclicensekeys.com,installcracks.com,licensekey4u.co,keysfull.net,crackserialkey.co,maliksofts.com,crackpropc.com,ayeshapc.com,crackhomes.com,crackspro.co,cracksoftwareguru.com,crackknow.com,cracxpro.com,4howcrack.com,trycracksoftware.com,proactivationkey.com,getprocrack.co,allpcsoftcrack.co,activationkeys.co,bulletcracks.com,organiccrack.com,softwarance.com,pcactivationkey.co,procrackkey.co,download4mac.com,freeactivationkeys.org,explorecrack.com,softtware.net,okproductkey.com,cracksmain.com,downloadpc.net,serialkey.info,up4pc.com,hitproversion.com,cracktube.net,abbaspc.net,crackdownload.org,crackdownload.me,corecrack.com,windowsactivator.info,keygenstore.com##center > [class*="buttonPress-"]
free4pc.org,warezcrack.net,freeprosoftz.com,vcracks.com,crackthere.com,keygenfile.net,scracked.com,cyberspc.com,softzcrack.com,crackintopc.com,zslicensekey.com,procrackpc.com,crackshere.com,crackdj.com,cracktopc.com,serialsofts.com,prosoftlink.com,zscracked.com,crackvip.com,windowcrack.com,softsnew.com,licensecrack.net,vstpatch.net,newcrack.info,topkeygen.com,vsthomes.com,vstserial.com,procrackerz.com,pcfullcrack.org,keygenpc.com,bicfic.com,ikcrack.com,downloadcracker.com,karancrack.com,piratesfile.com,activatorwin.com,starcrack.net,crackproduct.com##div[class^="code-block code-block-"]
crackkits.com,rootcracks.co,crackwatch.org,crackfix.net,origincrack.com##.getox
alicracks.com,win-crack.com##center > a
```

**Comment by advertblocker** [comment]
```
! activationkeys.co drag right-click
activationkeys.co##+js(aopw, nocontext)
activationkeys.co##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```
