### ISSUE TITLE
(possible gpu miner?) itstillworks dot com

### ISSUE THREAD

**Issue by DwarfFighterCleric** [uBlockOrigin/uAssets#14042]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://itstillworks.com/finding-ip-addresses-logs-facebook-2169.html`

### Describe the issue

This page causes Chromium's "GPU Process" to bloat up (exhausting free memory) and constantly causing CPU on the background (some kind of miner?)
Disabling Javascript on the page does not curb the behavior.

### uBlock Origin version

1.43.0

### Browser name and version

Ungoogled Chromium 86.0 (yes, it's old, I already know that, I don't care, it's going to stay this way for a few more years LOL I didn't ask you anything, why are u still thinking about it, stop it)

### Settings

- block images higher than 96kb by default (whitelist individually)
- (browser) Block all 3rd party cookies automatically by default (whitelist each site individually)

**Comment by stephenhawk8054** [comment]
Looks like it's because of the animation?

Try this and check again:

`itstillworks.com##.logo,.blinker:style(animation: none !important;)`
