### ISSUE TITLE
p.ynet.co.il: ads

### ISSUE THREAD

**Issue by maddoc1** [uBlockOrigin/uAssets#14048]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://p.ynet.co.il/mentamen/c/d00c19a4/?externalurl=true&cardId=d00c19a4&redirect=0`

### Category

ads

### Describe the issue

ads on the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 125053
  cosmetic: 189335
  scriptlet: 37219
  html: 0
listset (total-discarded, last updated): 
  added: 
    ISR-0: 1635-0, 33m
    adguard-annoyance: 55165-285, 1d.3h.46m
    adguard-generic: 66014-697, 1d.3h.50m
    adguard-spyware: 28737-1238, 1d.3h.53m
    adguard-spyware-url: 685-13, 1d.3h.48m
    fanboy-annoyance: 75038-3161, 8d.8h.53m
    ublock-annoyances: 4488-231, 1d.3h.47m
  default: 
    user-filters: 3-0, never
    easylist: 68381-878, 1d.3h.55m
    easyprivacy: 27421-11418, 1d.3h.49m
    plowe-0: 3647-868, 8d.8h.55m
    ublock-abuse: 75-0, 8d.8h.57m
    ublock-badware: 4219-320, 1d.3h.51m
    ublock-filters: 32138-3788, 1d.3h.52m
    ublock-privacy: 223-49, 8d.8h.56m
    ublock-quick-fixes: 225-26, 34m
    ublock-unbreak: 1834-103, 1d.3h.54m
    urlhaus-1: 4970-0, 35m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 37 redacted]
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 647 ms
  maxAssetCacheWait: 417 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
Those "ads" seem to be self-promo, clicking them will result in other `ynet.co.il` articles

@Hebrew-uBO-User
