### ISSUE TITLE
Videos on spiegel.de contain ads 

### ISSUE THREAD

**Issue by momu** [uBlockOrigin/uAssets#1404]
### URL(s) where the issue occurs

`http://www.spiegel.de/video/china-auto-bricht-auf-zugefrorenen-xingkai-see-ein-video-99013106.html`
Happens to all the videos there.

### Describe the issue

When viewing videos, after a few seconds a 20-30 s ad is shown. 

### Versions

- Browser/version: Chrome Version 63.0.3239.132
- uBlock Origin version: uBlock Origin v1.14.24

### Settings

- using advanced mode
- no other changes

### Notes

Used filters:
- uBlock filters​
- uBlock filters​ - Privacy
- uBlock filters​ - Resource Abuse
- uBlock filters​ - Resource Unbreak
- EasyList
- DEU: Easylist Germany

**Comment by TheEnhas** [comment]
`spiegel.de##script:inject(set-constant.js, ADI.disabled, true)`

Try that.

**Comment by tokariu** [comment]
doesn't work for me. 
they have a new video backend (nexx.tv) and blocking *.damoh.spiegel.de or anything nexx.cloud url like doesn't help. they use tokens with ads and timeouts. overwriting ADI constant doesn't help here it seems. 
probably must inject something to the 747.js (which is the nexx.tv video player id for spiegel.de)

**Comment by TheEnhas** [comment]
That seems to work for me though, I hard-reloaded many different videos after adding that and never saw a single ad, while before that the ads were injected at random (sometimes right at the start of the video).

I am using Firefox though if that makes any difference.

**Comment by tokariu** [comment]
hm I'm using Firefox ESR and ublock 1.13.8, I've got all ublock filters checked and updated.. yet injecting ADI.disabled / true doesn't work for me.

either i don't have the latest uAssets, or it's just not working.

**Comment by TheEnhas** [comment]
It's possible that the ads might be injected in the same way that Twitch and CityTV does which might make them very hard to block.

I hope that doesn't become commonplace.

**Comment by okiehsch** [comment]
Does
````
||svonm.com/hd-main.js$script,redirect=hd-main.js,domain=spiegel.de
spiegel.de##script:inject(golem.de.js)
````
work for you?

**Comment by momu** [comment]
I don't know what it is doing but for me it worked (tried 4 different videos).

Thanks a lot.

**Comment by TheEnhas** [comment]
That seems to work okay, but it's really hard to tell because I've reloaded videos before and had no ads, only to suddenly get one out of nowhere.

The scriptlets are still very poorly documented and unable to be used by anyone who doesn't know advanced javascript, so I always end up just trying stuff out of trial and error and then waiting for someone who knows what they're doing to fix it. Like, I tried addEventListener-defuser.js and that didn't work, but I had no idea that "golem.de.js" was also a defuser for that.

Now if I could only figure out what the hell is wrong with CityTV.

**Comment by okiehsch** [comment]
> had no idea that "golem.de.js" was also a defuser for that.

@TheEnhas you can look up `golem.de.js` at `https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L1341-L1351`
There you can see that it was added to fix https://github.com/uBlockOrigin/uAssets/issues/88
Basically `golem.de.js` can be used to partially fix pre-roll video ads for websites using `schneevonmorgen.com`.
