### ISSUE TITLE
qns.com: nuisance

### ISSUE THREAD

**Issue by thornofqueens** [uBlockOrigin/uAssets#14044]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://qns.com/2022/07/ditmars-boulevard-starbucks-employee-fired-union/`

### Category

nuisance

### Describe the issue

Giant pop-up covers the entire page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 104
filterset (summary): 
  network: 81115
  cosmetic: 26370
  scriptlet: 17464
  html: 709
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32928-314, 1d.18m
    ublock-badware: 4222-3, 1d.17m
    ublock-privacy: 240-1, 1h.37m
    ublock-abuse: 75-0, 1h.36m
    ublock-unbreak: 1855-0, 1d.16m
    ublock-quick-fixes: 222-0, 1h.34m
    adguard-mobile: 7957-167, 1d.14m
    easylist: 68381-25018, 1d.15m
    easyprivacy: 27421-591, 1d.13m
    urlhaus-1: 4979-0, 1h.35m
    plowe-0: 3647-3, 8d.20h.51m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2064 ms (selfie)
  maxAssetCacheWait: 284 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    qns.com: 4
    addthis.com: 1
    basis.net: 2
    datadoghq.com: 4
    doubleclick.net: 1
    empowerlocal.co: 1
    getclicky.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
    pico.tools: 3
    quantserve.com: 1
    spot.im: 19
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

`||gadget.pico.tools/load/build.js$script,domain=qns.com`
