### ISSUE TITLE
vodafone.de: breakage

### ISSUE THREAD

**Issue by Windows-Is-Cancer** [uBlockOrigin/uAssets#14055]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vodafone.de/meinvodafone/services/`

### Category

breakage

### Describe the issue

unable to switching to "my account" page 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 187826
  cosmetic: 288616
  scriptlet: 25567
  html: 763
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30190-251, 2d.20h.11m
    https://raw.githubusercontent.com/gfmaster/adblock-korea-contrib/master/filter.txt: 1489-3, 2d.20h.4m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.23h.16m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-5, 7d.5h.10m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6134-48, 6d.2h.19m
    fanboy-thirdparty_social: 69-0, 2h.54m
    fanboy-annoyance: 75305-59670, 23h.54m
    fanboy-social: 23240-41, 2d.20h.16m
    ara-0: 2582-1, 2d.20h.3m
    BGR-0: 1091-11, 23h.52m
    CHN-0: 28610-159, 2d.20h.10m
    CZE-0: 716-0, 18h.52m
    EST-0: 451-5, 18h.48m
    FRA-0: 29410-531, 2d.20h.15m
    GRC-0: 1002-4, 2h.52m
    HUN-0: 2167-12, 18h.59m
    IDN-0: 8993-6, 2d.20h.14m
    IRN-0: 1780-17, 2h.49m
    ISL-0: 194-1, 23h.51m
    [23 lists not shown]: [too many]
  default: 
    user-filters: 34-7, never
    ublock-filters: 32813-462, 2d.20h.21m
    ublock-badware: 4227-3, 2d.20h.20m
    ublock-privacy: 232-0, 6d.15h.45m
    ublock-unbreak: 1850-6, 2d.20h.19m
    easylist: 68364-1600, 2d.20h.18m
    easyprivacy: 27408-758, 2d.20h.17m
    plowe-0: 3647-64, 10d.17h.54m
    ublock-abuse: 75-58, 6d.15h.44m
    urlhaus-1: 4970-0, 18h.54m
    ublock-quick-fixes: 222-0, 18h.50m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
  removed: 
    no-large-media: behind-the-scene false
urlRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1439 ms (selfie)
  maxAssetCacheWait: 2042 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    vodafone.de: 1
```
</details>

**Comment by mapx-** [comment]
well, first of all @Windows-Is-Cancer you have to test again using ONLY the default lists (reset uBO to default settings)

**Comment by ghost** [comment]
uBO detected on the website. Using Edge Mobile for Android.

`https://www.vodafone.de/privat/handys-tablets-tarife/zusatzkarten.html`

https://github.com/user-attachments/assets/ce2459ec-2c3e-41f5-ac1b-7ef2c433fda5

<details>

```yaml
uBlock Origin: 1.66.2
Chromium Mobile: 139
filterset (summary):
 network: 165357
 cosmetic: 98674
 scriptlet: 34935
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 57581-11435, 2h.24m
  ublock-cookies-easylist: 5101-47, 2h.24m
  DEU-0: 8129-49, never
 default:
  user-filters: 0-0, never
  ublock-filters: 41370-82, 2h.24m Δ
  ublock-badware: 10987-31, 2h.24m Δ
  ublock-privacy: 3492-4, 2h.24m Δ
  ublock-unbreak: 2682-1, 2h.24m Δ
  ublock-quick-fixes: 313-0, 2h.26m
  adguard-mobile: 11371-67, 2h.24m
  easylist: 79882-279, 2h.24m
  easyprivacy: 54551-95, 2h.24m
  urlhaus-1: 31765-5, 2h.26m
  plowe-0: 3421-979, 2h.27m
  ROU-1: 1572-35, 2h.27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 781811 ms (selfie)
 maxAssetCacheWait: 135 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  vodafone.de: 2
  appdynamics.com: 1
  demdex.net: 1
  dimml.io: 1
```


</details>

**Comment by stephenhawk8054** [comment]
Fixed in `uBlock filters – Annoyances` list.
