### ISSUE TITLE
zupload.me [Pop-up] [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1405]
URL(s) where the issue occurs

`https://zupload.me/6542dcda21b1513e`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
Unknown 3rd parties increasing if blocked
