### ISSUE TITLE
hitpaw.com: ads

### ISSUE THREAD

**Issue by DevNightshade** [uBlockOrigin/uAssets#14056]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hitpaw.com/photo-tips/photo-enhancer-photoshop.html`

### Category

ads

### Describe the issue

Shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 186853
  cosmetic: 182122
  scriptlet: 38779
  html: 717
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
    adguard-generic: 66045-5794, now
    adguard-mobile: 7959-167, now
    adguard-spyware: 28742-1507, now
    adguard-spyware-url: 686-14, now
    block-lan: 43-0, now
    curben-phishing: 28856-3, now
    curben-pup: 195-0, now
    adguard-annoyance: 55196-5109, now
    adguard-social: 17915-1649, now
    fanboy-thirdparty_social: 69-1, now
    fanboy-annoyance: 75392-63831, now
    fanboy-cookiemonster: 36294-16011, now
    fanboy-social: 23247-13668, now
    ublock-annoyances: 4496-7, now
    dpollock-0: 10406-524, now
    DEU-0: 5891-385, now
    RUS-0: 41941-1150, now
    TUR-0: 8739-244, now
  default: 
    user-filters: 1-0, never
    ublock-filters: 32848-340, now
    ublock-badware: 4228-3, now
    ublock-privacy: 240-1, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1853-1, now
    ublock-quick-fixes: 222-0, now
    easylist: 68460-25255, now
    easyprivacy: 27422-11683, now
    urlhaus-1: 4977-0, now
    plowe-0: 3644-3, now
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 258 ms (selfie)
  maxAssetCacheWait: 697 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cloudflareinsights.com: 2
    digicert.com: 3
    googletagmanager.com: 3
```
</details>

**Comment by MasterKia** [comment]
> * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> ```yaml
>   added: 
>     https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
>     adguard-generic: 66045-5794, now
>     adguard-mobile: 7959-167, now
>     adguard-spyware: 28742-1507, now
>     adguard-spyware-url: 686-14, now
>     block-lan: 43-0, now
>     curben-phishing: 28856-3, now
>     curben-pup: 195-0, now
>     adguard-annoyance: 55196-5109, now
>     adguard-social: 17915-1649, now
>     fanboy-thirdparty_social: 69-1, now
>     fanboy-annoyance: 75392-63831, now
>     fanboy-cookiemonster: 36294-16011, now
>     fanboy-social: 23247-13668, now
>     ublock-annoyances: 4496-7, now
>     dpollock-0: 10406-524, now
>     DEU-0: 5891-385, now
>     RUS-0: 41941-1150, now
>     TUR-0: 8739-244, now
> ```


Can you try with _**only**_ the default lists?

**Comment by DevNightshade** [comment]
> > * [x]   I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> 
> > ```yaml
> >   added: 
> >     https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
> >     adguard-generic: 66045-5794, now
> >     adguard-mobile: 7959-167, now
> >     adguard-spyware: 28742-1507, now
> >     adguard-spyware-url: 686-14, now
> >     block-lan: 43-0, now
> >     curben-phishing: 28856-3, now
> >     curben-pup: 195-0, now
> >     adguard-annoyance: 55196-5109, now
> >     adguard-social: 17915-1649, now
> >     fanboy-thirdparty_social: 69-1, now
> >     fanboy-annoyance: 75392-63831, now
> >     fanboy-cookiemonster: 36294-16011, now
> >     fanboy-social: 23247-13668, now
> >     ublock-annoyances: 4496-7, now
> >     dpollock-0: 10406-524, now
> >     DEU-0: 5891-385, now
> >     RUS-0: 41941-1150, now
> >     TUR-0: 8739-244, now
> > ```
> 
> I don't see any ads, screenshot? Can you try with _**only**_ the default lists?

Here's with factory settings, see images for adspace

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 82018
  cosmetic: 43831
  scriptlet: 17169
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32409-97, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-131, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-784, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 882 ms
  maxAssetCacheWait: 7 ms
popupPanel: 
  blocked: 0
```
</details>

<img width="1280" alt="Screenshot 2022-07-17 140702" src="https://user-images.githubusercontent.com/106551976/179397542-bbdc2787-987c-4969-b194-b4e364988eca.png">
<img width="1280" alt="Screenshot 2022-07-17 140338" src="https://user-images.githubusercontent.com/106551976/179397544-efb82f52-ddd5-4103-bff5-882866a87661.png">

**Comment by mapx-** [comment]
Photo Enhancer is their product !? so, it's only self-promo.

**Comment by MasterKia** [comment]
> * [x]  I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)

@DevNightshade

_The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html):_
> Self-promotion should not be specifically removed, although equally should not be allowed if it is blocked.

**Comment by DevNightshade** [comment]
> > * [x]   I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
> 
> @DevNightshade
> 
> _The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html):_
> 
> > Self-promotion should not be specifically removed, although equally should not be allowed if it is blocked.

Context for the coverage of 
>> [...] although equally should not be allowed if it is blocked.

please, I'm not sure on how to understand that part of the sentence, sorry.

**Comment by MasterKia** [comment]
@DevNightshade 

![image](https://user-images.githubusercontent.com/17685483/179398389-51520ef9-6e8f-4750-b239-d485945e5022.png)

These are self-promotion, meaning the website is advertising its own product.
We don't block self-promotions.
