### ISSUE TITLE
webteizle.one: ads

### ISSUE THREAD

**Issue by weinbaum** [uBlockOrigin/uAssets#14050]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://webteizle.one/`

### Category

ads

### Describe the issue

ad container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![webteizle](https://user-images.githubusercontent.com/98059187/179387902-9a6dae99-8448-4f28-a14a-85fb80c88851.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 82576
  cosmetic: 51194
  scriptlet: 17799
  html: 706
listset (total-discarded, last updated): 
  added: 
    https://cdn.rawgit.com/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, 10h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32847-61, 10h.37m
    ublock-badware: 4228-3, 10h.37m
    ublock-privacy: 240-0, 10h.37m
    ublock-abuse: 77-0, 10h.37m
    ublock-unbreak: 1852-0, 10h.37m
    easylist: 68410-593, 10h.37m
    easyprivacy: 27422-586, 10h.37m
    plowe-0: 3644-3, 10h.37m
    TUR-0: 8739-67, 10h.42m
    ublock-quick-fixes: 222-0, 1h.56m
    urlhaus-1: 4977-0, 1h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 431 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    webteizle.one: 4
    googletagmanager.com: 4
```
</details>

**Comment by mapx-** [comment]
add

`webteizle.one###header:has([alt="reklam"])`

@Yuki2718 turkish list
