### ISSUE TITLE
444.hu: breakage

### ISSUE THREAD

**Issue by JohnnyBone92** [uBlockOrigin/uAssets#14059]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://444.hu/2022/07/17/ketharmada-a-magyaroknak-nem-megy-iden-nyaralni-a-publicus-felmerese-szerint`

### Category

breakage

### Describe the issue

I cant see the disqus section when uBlock is on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80060
  cosmetic: 46577
  scriptlet: 17465
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 98-4, never
    HUN-0: 2149-5, 7h.23m
    easylist: 68410-51, 21h.16m
    easyprivacy: 27422-134, 1d.16h.53m
    plowe-0: 3646-784, 2d.18h.17m
    ublock-abuse: 75-0, 4d.21h.37m
    ublock-badware: 4219-94, 21h.15m
    ublock-filters: 32195-104, 21h.14m
    ublock-privacy: 226-3, 4d.21h.36m
    ublock-quick-fixes: 227-14, 3h.21m
    ublock-unbreak: 1834-42, 21h.13m
    urlhaus-1: 5006-0, 3h.22m
filterset (user): [array of 98 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 90777 ms (selfie)
  maxAssetCacheWait: 5633 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    bbelements.com: 1
    disqus.com: 1
    googlesyndication.com: 4
    taboola.com: 1
    teads.tv: 1
    youtube.com: 1
```
</details>

**Comment by okiehsch** [comment]
If I click the "show comments" button it works fine on my end.

**Comment by Magasul** [comment]
Broken again.

**Comment by mapx-** [comment]
@Magasul which is the comments button ? provide a screenshot indicating it

**Comment by Magasul** [comment]
> [@Magasul](https://github.com/Magasul) which is the comments button ? provide a screenshot indicating it

Not sure, but lately ads keep showing up and even if I pick and remove them they return.

![Image](https://github.com/user-attachments/assets/f35174c0-64a7-4416-b01c-2ce3f6e40b75)

**Comment by mapx-** [comment]
Did you add the regional list hufilter ?

> Broken again.


What is broken and how to reproduce it ?

**Comment by Magasul** [comment]
> Did you add the regional list hufilter ?
> 
> > Broken again.
> 
> What is broken and how to reproduce it ?

How do I add that? :) Sorry if I'm asking a dumb question, I never had to add anything.

**Comment by stephenhawk8054** [comment]
Click on ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > There's a search bar, search for `hufilter` and enable that list.

**Comment by Magasul** [comment]
Ah, thanks, it worked!
