### ISSUE TITLE
piratespc.net: badware

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#14054]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://piratespc.net/dvdvideosoft-crack-2/`

### Category

privacy

### Describe the issue

```
https://www.virustotal.com/gui/url/91108f4609396cb3f6ea959bc559d8dc69d1f448dc7bdba77372963979ad9cc5
https://www.virustotal.com/gui/file/74b9f0056f45b9c19aac742527a25231fe35956009e909be28ecfd58169451d1
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ảnh](https://user-images.githubusercontent.com/95934994/179392915-64469665-2e5f-4d23-b74d-0f9179c31f0e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80412
  cosmetic: 45748
  scriptlet: 17459
  html: 706
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32823-57, 19h.12m
    ublock-badware: 4228-3, 19h.12m
    ublock-privacy: 240-0, 19h.12m
    ublock-abuse: 77-0, 19h.12m
    ublock-unbreak: 1852-0, 19h.12m
    ublock-quick-fixes: 224-0, 19h.12m
    easylist: 68410-580, 19h.12m
    easyprivacy: 27422-585, 19h.12m
    urlhaus-1: 4970-0, 19h.12m
    plowe-0: 3644-3, 19h.12m
    VIE-1: 1836-1, 19h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 288 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
well, the best thing you can do is reporting such pages to our specialist maintaining the default list:

`Online Malicious URL Blocklist`

issues for that list:
https://gitlab.com/malware-filter/urlhaus-filter/-/issues

**Comment by mapx-** [comment]
@curbengh
