### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by cocona20xx** [uBlockOrigin/uAssets#14052]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Describe the issue

From what I can tell, twitter _attempts_ to re-insert ads into the timeline, but fails, and ends up leaving large amounts of small empty spacers instead (which usually show up far more scarcely where ads would be when uBO is blocking them normally). Worst case scenario is that the feed gets stuck trying to reload the ads to the point where it refreshes itself, and eventually doesn't load any tweets, best case is a small stack of these empty tweet spots at the top of the feed. Seems to only happen on the main feed, subject/trending feeds are possibly not as heavily effected? 

Note that the ads blink on screen for a fraction of a second as twitter tries to load them... sometimes.

Curiously, this behavior seems to get worse when memory usage by Firefox overall is higher, as well.

### Screenshot(s)

Footage of the feed-breakage behavior: https://youtu.be/oYS0omh6wx0
Screenshot of a slightly less broken instance of this bug, where a concerning amount of 'empty' tweet-spacer-things are stuck at the top of the feed: 
![Screen Shot 2022-07-17 at 5 15 43 AM](https://user-images.githubusercontent.com/24525012/179392076-4790feda-be36-47ab-b7a0-48a1e20eae9a.png)
 

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 91550
  cosmetic: 172788
  scriptlet: 24267
  html: 713
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55196-1769, 5m
    adguard-social: 17915-24, 5m
    fanboy-annoyance: 75392-4238, 5m
    ublock-annoyances: 4496-4, 5m
  default: 
    user-filters: 20-4, never
    ublock-filters: 32843-43, 5m
    ublock-badware: 4228-3, 5m
    ublock-privacy: 240-0, 5m
    ublock-abuse: 76-0, 5m
    ublock-unbreak: 1852-0, 5m
    easylist: 68446-585, 5m
    easyprivacy: 27421-583, 5m
    urlhaus-1: 4977-0, 5m
    plowe-0: 3644-3, 5m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 867 ms
  maxAssetCacheWait: 375 ms
popupPanel: 
  blocked: 51
  blockedDetails: 
    twitter.com: 50
    google-analytics.com: 1
```
</details>

**Comment by Nerixyz** [comment]
I got the same issue.


> From what I can tell, twitter _attempts_ to re-insert ads into the timeline

(For me) the tweets are not ads, but recommended tweets (for example "Based on your likes").

The following CSS rule was injected (by some filter):
```css
[v91dd6t8v][wr0shs12j] {
  display:none!important;
}
```
It hides the tweets that are recommendations.

I'll try to find the filter this is coming from.

**Comment by mapx-** [comment]
Open the logger and see what filters are used

**Comment by mapx-** [comment]
Does it happen only when using one of annoyances list ?

```
Fanboy’s Annoyance
AdGuard Annoyances
uBlock filters – Annoyances
```

**Comment by Nerixyz** [comment]
It's from `AdGuard Annoyances`

Seems to be this rule:
```
twitter.com##section[aria-labelledby][role="region"] > div[aria-label] > div[style] > div[style^="transform: translate"] article[data-testid="tweet"]:has(> div[class] > div[class] > div[class] a[href^="/i/topics"][dir="auto"])
```
[Code in AdguardTeam/AdguardFilters](https://github.com/AdguardTeam/AdguardFilters/blob/5ed740f34b8750f02e4afffb38f9ac1e97e88bfb/AnnoyancesFilter/sections/annoyances.txt#L1921-L1922)

**Comment by mapx-** [comment]
@AdamWr @Yuki2718

**Comment by Yuki2718** [comment]
Are they really the same issue? On my end the rule in Annoyances is working as expected - it aims to hide these recommendation.

**Comment by Yuki2718** [comment]
@cocona20xx Please disable AG Annoyances and see if the issue persists.

**Comment by Yuki2718** [comment]
@Nerixyz If you don't want them to be hidden, add `twitter.com#@#section[aria-labelledby][role="region"] > div[aria-label] > div[style] > div[style^="transform: translate"] article[data-testid="tweet"]:has(> div[class] > div[class] > div[class] a[href^="/i/topics"][dir="auto"])`. BTW AGA will soon be modulated into sub lists, maybe in next week. So you'll be able to choose specific sub-list(s).

**Comment by cocona20xx** [comment]
> @cocona20xx Please disable AG Annoyances and see if the issue persists.

Yep, disabling AG Annoyances fixes the issue.

**Comment by Yuki2718** [comment]
@AdamWr Can you reproduce? I can't.

**Comment by cocona20xx** [comment]
I wonder if it got fixed by an unrelated change in the AG Annoyances scripts? I can't replicate the actual breakage anymore either, though the 'stacking' of empty promoted-tweets from the scriptset removing them still occurs, which didn't happen in the past.

**Comment by Yuki2718** [comment]
No change was made in AGA.

**Comment by bxkx** [comment]
I'm getting this too with the Adguard Annoyances list enabled. It sometimes loads and hides dozens of tweets this way. Was never an issue until recently.
I wonder if this was a thing before and now that Twitter is blasting my feed with these kind of tweets it became noticable? Cuz I don't know if it's normal to see 90%+ "based on" and random topic tweets in the feed, I was amazed at how long I had to scroll to see a tweet from somebody I follow when I turned it off lol

**Comment by Yuki2718** [comment]
@Alex-302 @AdamWr @BlazDT @zloyden Probably difficult to reproduce.

**Comment by Yuki2718** [comment]
Oh, wait @bxkx are you just saying AGA is hidding (many) correct targets?

**Comment by bxkx** [comment]
I'm not sure? Seems like it's mainly hiding "based on your likes" and the topic tweets. I thought those are supposed to be hidden by it?

**Comment by BlazDT** [comment]
Topic tweets?

**Comment by bxkx** [comment]
![image](https://user-images.githubusercontent.com/15363535/180660861-455ca783-725d-4a3d-b105-93bedbbe4ac7.png)

See the icon and the "topic" name in the top left.

**Comment by BlazDT** [comment]
Ah those. Yes, Annoyances filter is designed to hide both elements you have mentioned.

On a side note: Facebook's tries to show me 10 suggested posts in a row with one of my accounts (if filter is disabled).
