### ISSUE TITLE
huffpost.com: ads

### ISSUE THREAD

**Issue by GreatAlfredini** [uBlockOrigin/uAssets#14060]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.huffpost.com/`

### Category

ads

### Describe the issue

Even after zapping the "Shopping" div, it always returns upon reload/revisit

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79646
  cosmetic: 44655
  scriptlet: 17424
  html: 697
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32813-52, 3d.8h.41m
    ublock-badware: 4223-3, 3d.8h.45m
    ublock-privacy: 231-0, 7d.20h.51m
    ublock-abuse: 75-0, 7d.20h.50m
    ublock-unbreak: 1849-0, 3d.8h.44m
    ublock-quick-fixes: 224-0, 12h.54m
    easylist: 68364-575, 3d.8h.43m
    easyprivacy: 27403-581, 3d.8h.42m
    urlhaus-1: 4977-0, 12h.55m
    plowe-0: 3646-3, 6d.53m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1823 ms (selfie)
  maxAssetCacheWait: 965 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    huffpost.com: 1
    adlightning.com: 1
    amazon-adsystem.com: 1
    buzzfeed.com: 12
    chartbeat.com: 1
    connatix.com: 2
    doubleclick.net: 1
    doubleverify.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    permutive.app: 1
    quantserve.com: 1
    sail-horizon.com: 1
    scorecardresearch.com: 1
    spot.im: 1
    taboola.com: 1
    yimg.com: 2
```
</details>

**Comment by krystian3w** [comment]
Zapper ⚡ that works (element can back if refresh page or have reinsertion mechanism).

You can try learn what is CSS selector/CSS path to create more stable filters than uses many times the Zapper ⚡.

I don't exclude disable ads by more readable scriptlet.

**Comment by mapx-** [comment]
it's between self-promo & reviews

add in "my filters"

`huffpost.com##.js-cet-subunit.zone--has-title.zone--theme-default.zone--layout-trending-gemini`
