### ISSUE TITLE
indishare.me [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1406]
URL(s) where the issue occurs

`http://www.indishare.me/xuf0ek9imopj`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Popups

**Comment by ghajini** [comment]
Download button not visible in final download page when ublock enabled
`https://www.indishare.me/1hcugap6vqkb`
Also more 3rd parties unblocked

**Comment by okiehsch** [comment]
Does it work if you add
````
||indishare.me^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.google-analytics.com,badfilter
||indishare.me^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.bootstrapcdn.com *.cloudflare.com *.google-analytics.com
````

**Comment by ghajini** [comment]
Yes, thanks

**Comment by ghajini** [comment]
`http://www.indishare.me/qfu6p9mq329x`
this is `file not found` url, if clicked anywhere leads to popups
also fake player.download button

**Comment by ghajini** [comment]
Unknown xhr's 3rd party.....increasing if blocked....

`||*/r9vHhXf0GI1Er/*$important`

**Comment by ghajini** [comment]
domain changed
`https://www.indishare.org/jioqppw9asc5`
ads by `runative` /shady xhr's

**Comment by ghajini** [comment]
`indishare.org/sh5xd4eyjh7f`
tracking...
`|| www.indishare.org/sw.js$important`

**Comment by ghajini** [comment]
`indishare.org/bdv1n8aeesqe`
Filter 
`indishare.org##[href="https://bit.ly/2YxrUda"]`
to remove fake download button

**Comment by ghajini** [comment]
Update existing filter{ `indishare.org##+js(acis, math.sin, vocabulary)` 
} to

`indishare.org##+js(acis, Object.defineProperty, vocabulary)`

**Comment by ghajini** [comment]
Sometimes popup ads like on 1st visit
`indishare.org/loynjfnphyyv`

**Comment by ghajini** [comment]
Popup ads on `file not found page`

`indishare.org/bdv1n8aeesqe`
