### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by Togeluga** [uBlockOrigin/uAssets#14061]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Describe the issue

It pop up an anti adbocker page said that I need to shut down adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80354
  cosmetic: 45718
  scriptlet: 17514
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1841-0, 23h.51m
    easylist: 68370-56, 2d.22h.2m
    easyprivacy: 27411-128, 2d.22h.1m
    plowe-0: 3646-780, 2d.22h
    ublock-abuse: 75-0, 2d.21h.58m
    ublock-badware: 4219-94, 2d.21h.56m
    ublock-filters: 32156-109, 2d.21h.54m
    ublock-privacy: 226-3, 2d.21h.53m
    ublock-quick-fixes: 227-14, 23h.50m
    ublock-unbreak: 1834-42, 2d.21h.51m
    urlhaus-1: 4977-0, 23h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 135 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    linkneverdie.net: 1
    addthis.com: 1
    cachefly.net: 1
    facebook.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    optad360.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Try to update the filter lists it got fixed 3 days ago

**Comment by Togeluga** [comment]
> Try to update the filter lists it got fixed 3 days ago

thank you, It works perfectly after update
