### ISSUE TITLE
thequint.com: breakage

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#14063]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thequint.com/`

### Category

breakage

### Describe the issue

The top parts of the pages are truncated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![what it looks like](https://user-images.githubusercontent.com/11874211/179523281-f432dd45-8cc0-4a03-aa51-c1f28caf4825.png)
![ditto](https://user-images.githubusercontent.com/11874211/179523543-d70699d5-5786-480a-a187-1545f4a1d9b0.png)
![what it "should"](https://user-images.githubusercontent.com/11874211/179523891-150c3f37-d246-4fec-b0f9-7006603b9636.png)
![ditto](https://user-images.githubusercontent.com/11874211/179523570-54a7c132-2d5e-40ce-8f67-966d7dcbdda1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 102306
  cosmetic: 102421
  scriptlet: 20150
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    CHN-0: 28668-92, 11h.28m
    adguard-annoyance: 108994-53996, 11h.27m
  default: 
    easylist: 68365-112, 3d.22h.57m
    easyprivacy: 27423-248, 11h.33m
    plowe-0: 3647-783, 11d.57m
    ublock-abuse: 76-0, 7h.23m
    ublock-badware: 4224-94, 11h.32m
    ublock-filters: 32209-478, 11h.30m
    ublock-privacy: 226-3, 7h.22m
    ublock-quick-fixes: 223-3, 11h.24m
    ublock-unbreak: 1837-47, 11h.29m
    urlhaus-1: 5012-0, 11h.26m
filterset (user): [array of 185044 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1420 ms (selfie)
  maxAssetCacheWait: 653 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    thequint.com: 1
    affinity.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    ipinfo.io: 1
    moengage.com: 1
```
</details>

**Comment by krystian3w** [comment]
@ryanbr / @khrin -  possible delete `thequint.com##._4xQrn` or disable for uBo only if ABP has fix in ABP filters (Anti-CV project)?
