### ISSUE TITLE
vclock.com: ads

### ISSUE THREAD

**Issue by RuzgarErik** [uBlockOrigin/uAssets#14068]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vclock.com/stopwatch/`

### Category

ads

### Describe the issue

Shows self ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19328147/179742412-0f27e1c0-8111-4379-ab20-e0e4b56ba77a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 101879
  cosmetic: 98832
  scriptlet: 20914
  html: 707
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 28740-1324, 3d.2h.4m
    adguard-annoyance: 55178-864, 3d.1h.58m
    TUR-0: 8739-67, 3d.2h.2m
    adguard-spyware-url: 686-15, 3d.2h.5m
  default: 
    user-filters: 46-3, never
    ublock-filters: 32817-52, 3d.2h.3m
    ublock-badware: 4228-3, 3d.2h
    ublock-privacy: 240-0, 3d.2h.10m
    ublock-abuse: 75-0, 3d.2h.9m
    ublock-unbreak: 1851-0, 3d.2h.6m
    easylist: 68408-627, 3d.1h.59m
    easyprivacy: 27422-11626, 3d.2h.1m
    urlhaus-1: 5014-0, 23h.34m
    plowe-0: 3644-3, 3d.2h.8m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 31 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 899 ms (selfie)
  maxAssetCacheWait: 165 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
> Shows self ad

it seems to be an online page for that stopwatch, self-promo.
We don't block such "ads"
