### ISSUE TITLE
calendar.umkc.edu: breakage

### ISSUE THREAD

**Issue by lightingnerd** [uBlockOrigin/uAssets#14064]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://calendar.umkc.edu/academic-calendar/`

### Category

breakage

### Describe the issue

When attempting to visit the site, I was greeted with this error message "Unable to load calendar templates. Please disable any ad blockers and try again, or email support@livewhale.com if this problem persists."

Firefox version 102.0.1 (64-bit)

![image](https://user-images.githubusercontent.com/8975739/179530080-ccfcdc6c-0ac8-429f-98f5-bca9c31d815b.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 164235
  cosmetic: 210272
  scriptlet: 37185
  html: 714
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66019-5278, 2d.10h.36m
    adguard-mobile: 7957-188, 2d.10h.41m
    adguard-spyware: 28739-1483, 2d.10h.40m
    adguard-spyware-url: 686-15, 2d.10h.42m
    block-lan: 43-0, 27d.7h.25m
    adguard-annoyance: 55177-4701, 2d.10h.38m
    adguard-social: 17912-1058, 2d.10h.39m
    fanboy-thirdparty_social: 68-0, 7d.10h.3m
    fanboy-annoyance: 75182-59553, 7d.10h.1m
    fanboy-cookiemonster: 36112-128, 7d.10h.2m
    fanboy-social: 23245-28, 2d.10h.43m
    ublock-annoyances: 4496-4, 2d.10h.37m
    dpollock-0: 10406-485, 3d.11h.15m
    curben-phishing: 28128-3, 8h.58m
    curben-pup: 196-0, 9h
  default: 
    user-filters: 7-0, never
    ublock-filters: 32818-85, 3d.18h.40m
    ublock-badware: 4223-3, 3d.18h.39m
    ublock-privacy: 240-0, 17h.3m
    ublock-abuse: 77-0, 13h.2m
    ublock-unbreak: 1850-0, 3d.18h.38m
    easylist: 68368-926, 3d.18h.37m
    easyprivacy: 27409-11674, 3d.18h.36m
    urlhaus-1: 5012-0, 8h.59m
    plowe-0: 3646-3, 6d.14h.4m
    ublock-quick-fixes: 222-0, 21h.4m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 71 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1202 ms (selfie)
  maxAssetCacheWait: 165 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    umkc.edu: 5
    doubleclick.net: 2
    facebook.net: 1
    google-analytics.com: 2
    google.com: 3
    googleadservices.com: 1
    googletagmanager.com: 2
    maps.googleapis.com: 1
    sc-static.net: 2
    technolutions.net: 2
```
</details>

**Comment by mapx-** [comment]
"bad" filter 
`_share_icons.`

add
`@@||calendar.umkc.edu/live/component/$xhr,1p`

@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/e238082e53465351968539c4adff6c892b7e8d2a
