### ISSUE TITLE
dragontea.ink: breakage / detection

### ISSUE THREAD

**Issue by Moonwolf287** [uBlockOrigin/uAssets#14067]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

breakage

### Describe the issue

When opening the website with uBO enabled a Cloudeflare check page will be displayed for infinity. When uBO is disabled, the site loads normally. I think this might be an intentional break, since the Cloudeflare pages source has a few places where I'm unsure if this is a real one. 
Also I have no issues accessing other sites with uBO that I know have a valid Cloudeflare check.

PS: When turning off uBO loading in normally and turning it back on. You can use the site as normal for a few minutes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1161223/179662436-1633b55d-886a-4a8b-9071-0ecdcfaa1d4b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79925
  cosmetic: 44841
  scriptlet: 17386
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32877-37, now
    ublock-badware: 4208-0, now
    ublock-privacy: 241-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1852-0, now
    easylist: 68590-585, now
    easyprivacy: 27423-581, now
    plowe-0: 3645-3, now
    urlhaus-1: 5320-0, now
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1153 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
update and test again

**Comment by Moonwolf287** [comment]
👍  works now. Thanks!
