### ISSUE TITLE
*.hyper.ag: breakage

### ISSUE THREAD

**Issue by rizo** [uBlockOrigin/uAssets#14076]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://*.hyper.ag/`

### Category

breakage

### Describe the issue

This website is a dashboard that serves metrics for my company's product. I don't understand why it's blocked by uBlock considering it does not perform any tracking nor serves ads at all. It provides sensor analytics data for our customers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79963
  cosmetic: 44946
  scriptlet: 17429
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32893-38, 1h.2m
    ublock-badware: 4208-0, 1h.1m
    ublock-privacy: 241-0, 1h
    ublock-abuse: 76-0, 59m
    ublock-unbreak: 1849-0, 58m
    ublock-quick-fixes: 226-0, 57m
    easylist: 68658-584, 56m
    easyprivacy: 27428-581, 55m
    urlhaus-1: 5198-0, 54m
    plowe-0: 3645-3, 53m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2325 ms
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    hyper.ag: 1
```
</details>

**Comment by mapx-** [comment]
You didn't provide useful info.
Account required ? => provide a test account.

Use the uBO's logger (open the logger, reproduce the issue, go into the logger, post here the blocked requests)

**Comment by mapx-** [comment]
blocked by Easyprivacy @ryanbr 

`@@||hyper.ag/api/sites/1/analytics/$xhr,1p`

**Comment by mapx-** [comment]
just to have complete info => what's the issue ? what is broken (because I can click and see various pages from the left side menu)

**Comment by rizo** [comment]
Could you help me understand why this was blocked in the first place? I'm worried that other ad-blockers might block this request without us knowing about it and affecting our customers' ability to use the product.

**Comment by mapx-** [comment]
It wasn't blocked for your site, it's a generic filter in Easyprivacy

`/analytics/v3/*`

**Comment by rizo** [comment]
Oh wow, that's pretty strict. Thanks for handling this so quickly!
