### ISSUE TITLE
spotify.com: breakage

### ISSUE THREAD

**Issue by GeorgeWL** [uBlockOrigin/uAssets#14079]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.spotify.com/heardle/`

### Category

breakage

### Describe the issue

Main content didn't load in until disabled uBlock entirely

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220720-215639](https://user-images.githubusercontent.com/5931248/180080907-0922f096-a158-4ec4-8ceb-52afcb21e2a1.jpg)
![Screenshot_20220720-215634](https://user-images.githubusercontent.com/5931248/180080917-499e1ed8-681a-41ae-b253-56bb26fc67b3.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 81309
  cosmetic: 26640
  scriptlet: 17442
  html: 709
listset (total-discarded, last updated): 
  default: 
    user-filters: 31-5, never
    ublock-filters: 32951-311, 3d.6h.37m
    ublock-badware: 4207-0, 7h.41m
    ublock-privacy: 241-1, 1d.10h.56m
    ublock-abuse: 76-0, 1d.5h.30m
    ublock-unbreak: 1852-0, 14m
    adguard-mobile: 7966-167, 1d.2h.55m
    easylist: 68590-25040, 1d.10h.55m
    easyprivacy: 27422-591, 3d.6h.38m
    urlhaus-1: 5198-0, 7h.40m
    plowe-0: 3646-3, 9d.2h.55m
    ublock-quick-fixes: 208-0, 22h.24m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 18 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1657 ms (selfie)
  maxAssetCacheWait: 632 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You should reset uBO to default, disable any other addon & test again

![image](https://user-images.githubusercontent.com/10303732/180138300-960743bb-9c2b-4e65-89ca-4b15f9c55576.png)
