### ISSUE TITLE
clicknupload.org [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1407]
URL(s) where the issue occurs

`https://clicknupload.org/26je65u5ot5b`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
`https://clicknupload.org/thtsij5vjcb9`
popups after navigating to at final download page

**Comment by ghajini** [comment]
`https://clicknupload.org/ro9p2bt4218x`
popups after navigating to at final download page

**Comment by ghajini** [comment]
Same problem again

**Comment by mapx-** [comment]
Does this work for you
`clicknupload.org##+js(addEventListener-defuser.js)`

**Comment by ghajini** [comment]
Small problem loading bar....
`clicknupload.org##[id*="ScriptRoot"]`

**Comment by mapx-** [comment]
already working `##[id*="ScriptRoot"]` from easylist
(did you add a `generichide` filter ?)

**Comment by ghajini** [comment]
`##[id*="ScriptRoot"]` isn't triggering on my end with firefox android
![Screenshot_2019-03-31-11-38-53-480_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55285450-05363700-537c-11e9-8ffc-b20779920eed.png)

**Comment by ghajini** [comment]
`https://clicknupload.org/ak2tz3d4drw5`
`click to start download` button not working at final download page

**Comment by mapx-** [comment]
I disabled uBo for `clicknupload` => still locked, it seems to be an issue on their side

**Comment by ghajini** [comment]
Sorry wrong call....I will test onwards with ubo disabled also😅

**Comment by ghajini** [comment]
`clicknupload.org/mnzacbrg1gg3`

***click to start download*** button not working at final download page

**Comment by mapx-** [comment]
It work for me, what requests are shown as blocked in your logger ?

**Comment by ghajini** [comment]
Sorry it was false report on my side due to filter suggested here https://github.com/uBlockOrigin/uAssets/issues/6587#issuecomment-554903843
 being on my side

**Comment by uBlock-user** [comment]
> Sorry it was false report on my side due to filter suggested here #6587 (comment)
being on my side

That filter was NOT suggested for you :sighs: but rather for filter list maintainers to speed up the investigation. Don't just copy-paste what I post without knowing what you're copy-pasting.
