### ISSUE TITLE
1movieshd: popups

### ISSUE THREAD

**Issue by uzzbuzz01** [uBlockOrigin/uAssets#14078]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

using 1movieshd and when pressing to play the player this site pops up. only one ive noticed so far

### Category

popups

### Describe the issue

using 1movieshd and when pressing to play the player this site pops up. only one ive noticed so far 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79963
  cosmetic: 44943
  scriptlet: 17455
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 68659-51, 2h.38m
    easyprivacy: 27428-123, 2h.37m
    plowe-0: 3646-779, 8d.21h.8m
    ublock-abuse: 75-0, 12d.10h.3m
    ublock-badware: 4204-92, 2h.40m
    ublock-filters: 32241-111, 2h.41m
    ublock-privacy: 223-3, 12d.10h.4m
    ublock-quick-fixes: 221-1, 2h.36m
    ublock-unbreak: 1834-42, 2h.39m
    urlhaus-1: 5198-0, 2h.35m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 443 ms (selfie)
  maxAssetCacheWait: 281 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    d7o8kvfhpwxk.cloudfront.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Test site `https://1movieshd.com/watch-movie/free-universal-soldier-ii-brothers-in-arms-hd-3004.5458195`
