### ISSUE TITLE
eBay and Firefox: ergonimy problem of product description text

### ISSUE THREAD

**Issue by AR404lab** [uBlockOrigin/uAssets#14073]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.ebay.fr/itm/274884442772

### Describe the issue

there seems to be a text layout problem only on eBay with Firefox and when uBlock is running. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/97963753/179951422-9565ba5e-b36a-4b7c-8755-a4cd9bc6c91c.png)

### Configuration

uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 99748
  cosmetic: 53778
  scriptlet: 17490
  html: 707
listset (total-discarded, last updated): 
  default: 
    user-filters: 9-0, never
    ublock-filters: 32852-178, 2d.14h.28m
    ublock-badware: 4228-3, 2d.14h.27m
    ublock-privacy: 241-0, 1d.31m
    ublock-abuse: 76-0, 1d.30m
    ublock-unbreak: 1853-1, 2d.14h.26m
    ublock-quick-fixes: 232-0, 13m
    easylist: 68465-622, 2d.14h.25m
    easyprivacy: 27422-581, 2d.14h.24m
    urlhaus-1: 5195-0, 13m
    plowe-0: 3646-3, 5d.2h.50m
    FRA-0: 29472-352, 2d.14h.29m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 427 ms (selfie)
  maxAssetCacheWait: 273 ms

**Comment by krystian3w** [comment]
Test after purge cache for lists in uBo Dashboard:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

Your lists are most form Monday not Wednesday (today).

**Comment by mapx-** [comment]
site issue, I can reproduce even disabling uBO

**Comment by krystian3w** [comment]
@Yuki2718 maybe for resized window possible add to AG Annoyances "other" these:

`###desc_ifr:style(width: 100% !important;)`

Page almost never update attribute width after resize window.

**Comment by AR404lab** [comment]
> @Yuki2718 maybe for resized window possible add to AG Annoyances "other" these:
> 
> `###desc_ifr:style(width: 100% !important;)`
> 
> Page almost never update attribute width after resize window.

Works fine now !! I have done a cache clear that solved my problem but I know the problem is coming back so I am trying to do that.

**Comment by krystian3w** [comment]
I will remove these for Polish file if ebay add dynamic update html attribute or enforce 100% in attr or CSS section/file.

**Comment by Yuki2718** [comment]
It happens randomly, regardless of blocker enabled or not. IDK if worth fixing.
