### ISSUE TITLE
diffchecker.com: obtrusively sized banners

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#14080]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.diffchecker.com/`

### Describe the issue

These huge banners.. right at the top. Almost covers half the screen on my smallish laptop..
Not sure what the policy here on stuff like this was again, but I think this is very obnoxious.
It's late, and don't we all have to draw a line somewhere?

### uBlock Origin version

uBlock Origin 1.43.0

### Browser name and version

Chrome 103.0.5060.134 (Official Build) (64-bit) (cohort: 103_Win_134) 

### Settings

default settings

**Comment by stephenhawk8054** [comment]
I can't see any banners with the link above

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/180108385-708dfe27-a9ac-4866-9f92-1ec7961f067d.png)

</details>

Can you screenshot the page?

**Comment by stephenhawk8054** [comment]
You can add this filter to ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

`diffchecker.com##[class^="hero_hero__"]`

**Comment by Hrxn** [comment]
Thanks.. is this something that should be added to one of the uBO filter lists?

**Comment by Hrxn** [comment]
What about the uBO Annoyances List?

**Comment by stephenhawk8054** [comment]
uBlock Annoyances list is usually used for sites that circumvent context menu, copy/cut/paste/drag or dev tools so I doubt it can added into that list either.

Even with Adguard or Fanboy annoyance lists, I don't think they will hide the `Compare` section since it's the explanation of the page. At most they could only hide the `https://www.diffchecker.com/desktop/` part.

**Comment by Hrxn** [comment]
Well..

Just took a glance at the `annoyances.txt` in this repo, which I assume is the Annoyance Filter List entry in the uBO Filter Lists panel, and it definitely has a entries like these, for example:

https://github.com/uBlockOrigin/uAssets/blob/c2292354a5a2bc33d5f21bc7357e2b40d5eecaa5/filters/annoyances.txt#L53-L56
https://github.com/uBlockOrigin/uAssets/blob/c2292354a5a2bc33d5f21bc7357e2b40d5eecaa5/filters/annoyances.txt#L108-L112

Seems like the same kind of annoyances this issue here is about?

**Comment by stephenhawk8054** [comment]
Those are for soft anti-adblock sites (which means could be solve by ABP-compatible CSS filter), not for self-promotion.

If I remember correctly, very few situations where the self promotion appears continuously and blocks the main view of the page were addressed in that list, but I don't think this case is one of them as the self-promotion is just in a corner of the page.

**Comment by Hrxn** [comment]
I see.. but, you know *"just in a corner of the page"*, let's say that is highly debatable...

If anyone else is interested:
Those promo banners directly below the relevant textareas, I managed to remove them with
```
diffchecker.com##form > div > div:has(a[href="https://www.diffchecker.com/desktop"]) 
diffchecker.com##form > div > div:has(a[href="https://www.diffchecker.com/pro-features"])
```

Not sure if that is the right way to write filters, I'm not versed in that at all, but it seems to work..

**Comment by stephenhawk8054** [comment]
> I mean the banners with _Compare Text_ and _Try our desktop app_, as visible in your screenshot.

I mean the `Try our desktop app` you mentioned is on the corner. If you also mean the other sections at the bottom, you can try

`diffchecker.com##.banner`

As I said, you can open these issues in Adguard or Fanboy annoyances repos.

**Comment by Hrxn** [comment]
> `diffchecker.com##.banner`

Yes, but this matches any element with the name of `banner` in its `class` attribute?
Are you sure this does not trigger any false positives here?

What is wrong with my examples?

**Comment by stephenhawk8054** [comment]
> > `diffchecker.com##.banner`
> 
> Yes, but this matches any element with the name of `banner` in its `class` attribute? Are you sure this does not trigger any false positives here?
> 
> What is wrong with my examples?

If you find any pages that have false positives, you can report back so others can help modify the filters. Nothing's wrong with your filters but `has` is a [procedural cosmetic filter](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters) which is a bit less efficient.

**Comment by Hrxn** [comment]
I see, thanks.
uBO has a great and very detailed wiki on github, but I guess this short sentence could need a bit more emphasis, because it's otherwise quite easy to miss:

> Only use procedural cosmetic filters when plain CSS selectors won't work.

I have a question here, is the evaluation of a less efficient procedural cosmetic filter only an issue when actually visiting the specific site that is targeted by the filter, or is this always an issue in any case?
