### ISSUE TITLE
behance.net: breakage

### ISSUE THREAD

**Issue by cannadi** [uBlockOrigin/uAssets#14084]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.behance.net/gallery/64897521/UX-UI-Design-for-Online-Verification-Web-Application`

### Category

breakage

### Describe the issue

loading loop entering the page. nothing was shown

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98272
  cosmetic: 54952
  scriptlet: 17572
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 28668-92, 3d.5h.25m
  default: 
    user-filters: 0-0, never
    easylist: 68470-73, 3d.5h.29m
    easyprivacy: 27423-149, 3d.5h.24m
    plowe-0: 3644-782, 3d.5h.33m
    ublock-abuse: 76-0, 3d.5h.32m
    ublock-badware: 4224-95, 3d.5h.28m
    ublock-filters: 32209-128, 3d.5h.27m
    ublock-privacy: 226-3, 3d.5h.31m
    ublock-quick-fixes: 240-1, 3h.9m
    ublock-unbreak: 1837-43, 3d.5h.26m
    urlhaus-1: 5318-0, 3h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1676 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Can't reproduce. Do I need to be logged in for the breakage to happen?

**Comment by ghajini** [comment]
>   blocked: 0
  what exactly is broken , a screenshot?

**Comment by cannadi** [comment]
complete blank page

**Comment by cannadi** [comment]
you don't

**Comment by mapx-** [comment]
maybe you are using edge ? brave ? be sure to disable their internal adblockers or tracking protection

**Comment by cannadi** [comment]
chrome on mac
Version 106.0.5249.103 (Official Build) (arm64)

**Comment by mapx-** [comment]
Try reinstalling uBO, keep it with the default settings, close / reopen the browser, test again
