### ISSUE TITLE
bezrealitky.cz: breakage

### ISSUE THREAD

**Issue by drastickrutor** [uBlockOrigin/uAssets#14085]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bezrealitky.cz/moje-bezrealitky/moje-inzeraty/upravit/628101`

### Category

breakage

### Describe the issue

does not work parts of this site (images ing gallery edit are blocked, editing the inzerat etc.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80182
  cosmetic: 45270
  scriptlet: 17581
  html: 707
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32894-38, 1d.1h.25m
    ublock-badware: 4208-0, 1d.1h.27m
    ublock-privacy: 240-0, 4d.8h.14m
    ublock-abuse: 76-0, 13h.20m
    ublock-unbreak: 1851-0, 1d.1h.26m
    easylist: 68653-586, 1d.1h.24m
    easyprivacy: 27426-586, 1d.1h.28m
    plowe-0: 3644-3, 4d.8h.15m
    CZE-0: 716-0, 17h.23m
    urlhaus-1: 5198-0, 17h.21m
    ublock-quick-fixes: 218-0, 17h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1641 ms (selfie)
  maxAssetCacheWait: 354 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    bezrealitky.cz: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    id-sign.com: 1
```
</details>

**Comment by mapx-** [comment]
You should find a (still broken) page but which does not require an account.

**Comment by krystian3w** [comment]
Worse if free content (no paid by register) is loaded fine.
