### ISSUE TITLE
cnews.fr: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#14089]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cnews.fr/monde/2022-07-21/italie-une-religieuse-interrompt-un-baiser-entre-deux-femmes-video-1245275`

### Category

ads

### Describe the issue

There are still frames to hide.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/180328009-e91434d9-419b-4c7d-865f-eb309c21ffb5.png)
![image](https://user-images.githubusercontent.com/50231020/180328020-c2a2f225-32f3-4d32-8062-38d1c2266672.png)
![image](https://user-images.githubusercontent.com/50231020/180328050-ac3f1531-848a-4eae-822e-ac201f83f955.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 541688
  cosmetic: 149491
  scriptlet: 35463
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41958-258, 2m
    adguard-generic: 66092-1323, 2d.13h.35m
    adguard-mobile: 7964-84, 2d.13h.33m
    curben-phishing: 28657-0, 18h.7m
    curben-pup: 190-1, 18h.5m
    fanboy-cookiemonster: 36060-104, 6d.23h.52m
    ublock-annoyances: 4493-83, 2d.13h.24m
  default: 
    FRA-0: 29472-64, 2d.13h.37m
    easylist: 68590-1082, 2d.13h.30m
    easyprivacy: 27423-611, 2d.13h.26m
    plowe-0: 3646-906, 6d.23h.52m
    ublock-abuse: 75-2, 6d.23h.52m
    ublock-badware: 4204-329, 2d.13h.22m
    ublock-filters: 32225-3700, 2d.13h.20m
    ublock-privacy: 226-3, 6d.23h.52m
    ublock-quick-fixes: 242-11, 18h.3m
    ublock-unbreak: 1840-84, 2d.13h.18m
    urlhaus-1: 5318-1, 18h.1m
filterset (user): [array of 2092 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 970 ms (selfie)
  maxAssetCacheWait: 775 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    dailymotion.com: 3
    instagram.com: 8
```
</details>

**Comment by Procyon-b** [comment]
Je n'ai pas les blocs vides au dessus des pastilles "1 2 3 4 5" à droite.
Pour ce qui est du bloc du player "A voir aussi" tu peux essayer ce filtre:
```
cnews.fr##.related-video
```

**Comment by Procyon-b** [comment]
Je me suis dit qu'en français c'était plus simple pour être certain de se comprendre correctement.  :)

**Comment by mapx-** [comment]
@smed79
