### ISSUE TITLE
www.ilfattoquotidiano.it can still track me

### ISSUE THREAD

**Issue by elnath78** [uBlockOrigin/uAssets#14093]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ilfattoquotidiano.it/`

### Category

tracking non prevented

### Describe the issue

website can track how many articles I have read, regardless the fact that uBO is active. I also tried deleting the cookies `shift+f9` (Firefox 102.0.1) not sure what technology they are using to keep the record. I do not have an account on that website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 85732
  cosmetic: 52375
  scriptlet: 17428
  html: 699
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32893-46, 1d.11h.17m
    ublock-badware: 4208-0, 15h.47m
    ublock-privacy: 232-0, 8d.1h.1m
    ublock-abuse: 76-0, 3d.16h.14m
    ublock-unbreak: 1856-1, 3d.43m
    easylist: 68651-588, 2d.12h.49m
    easyprivacy: 27428-583, 1d.21h.23m
    urlhaus-1: 5289-0, 24m
    plowe-0: 3646-3, 8d.22h
    ITA-0: 13123-1, 23h.13m
    ublock-quick-fixes: 226-0, 1d.1h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3209 ms (selfie)
  maxAssetCacheWait: 2031 ms

**Comment by mapx-** [comment]
> website can track how many articles I have read

Explain where did you see that ?

**Comment by elnath78** [comment]
> Explain where did you see that ?

You are right, sorry. Here is ho to replicate: enter the website and read any article (click a title) when you do so for 3+ times it start showing a popup with exact amount of how many articles you have read in the past X days. I'm not sure if they track a "per day" usage or not. The popup is shown only once per session after opening an article.

**Comment by mapx-** [comment]
Test this filter

`ilfattoquotidiano.it##+js(aost, localStorage, /(?=^(?!.*(https|comments)))/, 2)`

**Comment by mapx-** [comment]
However, even if the filter above is working we wont add it to our lists => it's kind of paywall

**Comment by elnath78** [comment]
> However, even if the filter above is working we wont add it to our lists => it's kind of paywall

What do you mean? The filter is partially working, it stops the tracking of how many articles you have read and prevent the popup to disrupt the reading. However if breaks the homepage, stripping the featured images of every article.

**Comment by mapx-** [comment]
remove the filter above and test:

```
ilfattoquotidiano.it##.modal-sostenitore-wrapper
ilfattoquotidiano.it##.modal-sostenitore--blur
ilfattoquotidiano.it##.bg-yellow.modal-sostenitore
ilfattoquotidiano.it##body:style(overflow: auto !important;)
ilfattoquotidiano.it##*:style(filter: none !important)
```

**Comment by elnath78** [comment]
> remove the filter above and test:
> 
> ```
> ilfattoquotidiano.it##.modal-sostenitore-wrapper
> ilfattoquotidiano.it##.modal-sostenitore--blur
> ilfattoquotidiano.it##.bg-yellow.modal-sostenitore
> ilfattoquotidiano.it##body:style(overflow: auto !important;)
> ilfattoquotidiano.it##*:style(filter: none !important)
> ```

This is more like hiding the popup via CSS, but it is not preventing the tracking. I think they are using fingerprinting, I also think it is what should be prevented without disrupting the page functionality.
