### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by ymhomer** [uBlockOrigin/uAssets#14098]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=KOfmJC0Xa1g`

### Category

breakage

### Describe the issue

video cannot play during enable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80132
  cosmetic: 44952
  scriptlet: 17430
  html: 709
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32900-46, 23h.35m
    ublock-badware: 4208-0, 23h.34m
    ublock-privacy: 240-0, 23h.33m
    ublock-abuse: 76-0, 23h.32m
    ublock-unbreak: 1847-0, 23h.31m
    ublock-quick-fixes: 237-0, 23h.30m
    easylist: 68709-584, 23h.29m
    easyprivacy: 27432-580, 23h.28m
    urlhaus-1: 5312-0, 23h.27m
    plowe-0: 3645-3, 23h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 598 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    youtube.com: 9
    doubleclick.net: 2
    google.com: 1
    google.com.my: 1
```
</details>

**Comment by mapx-** [comment]
YT issues https://github.com/uBlockOrigin/uAssets/issues/7636
