### ISSUE TITLE
avgle.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1409]
URL(s) where the issue occurs

`https://avgle.com/video/131244/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
see this thread
https://forums.lanik.us/viewtopic.php?p=131658#p131658

however, they are following all the threads about avgle and do changes on daily basis

**Comment by xDarkARG** [comment]
yes but try to update every day if you can secretly ok @mapx-

**Comment by mapx-** [comment]
secretly ? this means a closed group with access to the updates .. it's utopy :) or Utopia.

**Comment by mapx-** [comment]
probably we all need a next step to the future: an utility with AI abilities which analyzes the page / code and create the necessary filters. This way will have smaller lists (eventually only with some generic filters), only for the pages we visit ..etc

**Comment by ghajini** [comment]
https://github.com/mun3/F-ckAvgleAntiAdblock

**Comment by justforadblock** [comment]
@uBlock-user  @ghajini 
https://raw.githubusercontent.com/mun3/F-ckAvgleAntiAdblock/master/fu_antiadblock.user.js
 this  scrpit is not work , now (2018 05 07)
