### ISSUE TITLE
epicchatting.wikidot.com: detection

### ISSUE THREAD

**Issue by INNSERTGOODUSERNAMEHERE** [uBlockOrigin/uAssets#14097]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://epicchatting.wikidot.com/chatroom`

### Category

detection

### Describe the issue

it wont let see that contbt

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 80094
  cosmetic: 44954
  scriptlet: 17466
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68707-51, 1d.7h.47m
    easyprivacy: 27431-123, 1d.7h.46m
    plowe-0: 3646-779, 8d.12h.47m
    ublock-abuse: 75-0, 8d.21h.25m
    ublock-badware: 4204-92, 1d.7h.45m
    ublock-filters: 32227-111, 1d.7h.44m
    ublock-privacy: 226-3, 8d.21h.24m
    ublock-quick-fixes: 251-1, 17h.24m
    ublock-unbreak: 1833-42, 1d.7h.43m
    urlhaus-1: 5283-0, 21h.43m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1114 ms
  maxAssetCacheWait: 537 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    doubleclick.net: 2
    quantcount.com: 2
    quantserve.com: 2
    wdfiles.com: 1
```
</details>

**Comment by mapx-** [comment]
Even disabling uBO I get a site issue:

![image](https://user-images.githubusercontent.com/10303732/180459160-f9577bd4-92e9-46ed-bdac-ff22e7818e98.png)

**Comment by mapx-** [comment]
Explain what's the issue, what detection ?
Add a screenshot if helps
