### ISSUE TITLE
global.americanexpress.com: breakage

### ISSUE THREAD

**Issue by wtftf** [uBlockOrigin/uAssets#14096]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://global.americanexpress.com/rewards/redeem-for-credit`

### Category

breakage

### Describe the issue

Page never fully loads. The "business" portion at the center of the page (where I need to transact my actual business while at the site) remains blank. This was never a problem before.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>/home/brek/Downloads/Screenshot from 2022-07-22 07-00-29.png

![Screenshot from 2022-07-22 07-00-29](https://user-images.githubusercontent.com/49805887/180435094-8ef0f1cb-d6ca-4f3d-b305-525c43d93414.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80138
  cosmetic: 44953
  scriptlet: 17436
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32911-46, 1d.3h.10m
    ublock-badware: 4208-0, 1d.3h.9m
    ublock-privacy: 240-0, 5d.4h.38m
    ublock-abuse: 75-0, 5d.4h.37m
    ublock-unbreak: 1847-0, 1d.3h.8m
    easylist: 68707-584, 1d.3h.7m
    easyprivacy: 27431-580, 1d.3h.6m
    urlhaus-1: 5318-0, 23h.4m
    plowe-0: 3644-3, 5d.4h.36m
    ublock-quick-fixes: 237-0, 23h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 683 ms (selfie)
  maxAssetCacheWait: 334 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    americanexpress.com: 5
    adobedtm.com: 1
    aexp-static.com: 3
    demdex.net: 1
    qualtrics.com: 1
```
</details>

**Comment by mapx-** [comment]
does this exception help ?

`@@||aexp-static.com/cdaas/api/testtarget/maxymiser/2.0.0/mmcore.js$script,domain=global.americanexpress.com`

still in trouble:
- open the logger
- repeat the steps to get the issue
- from the logger copy and paste here all blocked requests
