### ISSUE TITLE
Random Youtube videos will not play.

### ISSUE THREAD

**Issue by mikekaylor98** [uBlockOrigin/uAssets#14091]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Random videos will not play for me, but I am not sure it will be the same video for every user.
I have started encountering this issue a few months ago, then I had the issue yesterday, and now I am having it again today. It has happened a total of three times with specific videos.
Videos play fine when uBO is disabled. I am able to hover on the timeline and see the image preview for that part of the video, but the video will not play and is a black screen. I've never changed the default settings for this extension. If I put the youtube video into a playlist, then I can play the video with uBO.

### A specific URL where the issue occurs

`https://www.youtube.com/watch?v=AReCzM8fhiE`

### Steps to Reproduce

1. Click videos on YouTube
2. Encounter a video that won't play

### Expected behavior

The video should play

### Actual behavior

The video does not play

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 82018
  cosmetic: 43831
  scriptlet: 17169
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32409-35, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-0, never
    easylist: 68049-564, never
    easyprivacy: 27172-578, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 713 ms
  maxAssetCacheWait: 163 ms
```
</details>

**Comment by mapx-** [comment]
YT issues thread: https://github.com/uBlockOrigin/uAssets/issues/7636
