### ISSUE TITLE
packhacker.com: breakage

### ISSUE THREAD

**Issue by dechamps** [uBlockOrigin/uAssets#14092]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://packhacker.com/travel-gear/aer/commuter-brief-2/`

### Category

breakage

### Describe the issue

All review pages under https://packhacker.com/ are broken with uBlock Origin: the actual review content does not appear. The linked URL is just one example out of many.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**With** uBlock Origin: 
![image](https://user-images.githubusercontent.com/866859/180388225-f803b8bc-37c2-4e23-83f7-df55b5984039.png)

**Without** uBlock Origin: 
![image](https://user-images.githubusercontent.com/866859/180388396-a0abe3e5-d845-4403-8044-ca493c07bf0c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 131055
  cosmetic: 204667
  scriptlet: 36676
  html: 698
listset (total-discarded, last updated): 
  removed: 
    ublock-privacy: null
    easyprivacy: null
  added: 
    https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt: 1072-3, 4d.17h.28m
    adguard-generic: 66156-5617, 1d.10h.29m
    adguard-mobile: 7969-149, 1d.10h.28m
    adguard-annoyance: 55156-3585, 1d.10h.27m
    fanboy-annoyance: 75166-36198, 6d.8h.44m
    fanboy-cookiemonster: 36070-361, 6d.8h.43m
    ublock-annoyances: 4502-5, 1d.10h.26m
    FRA-0: 29598-193, 1d.10h.30m
    curben-phishing: 27535-2, 53m
    curben-pup: 187-0, 52m
    ublock-quick-fixes: 239-0, 51m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32897-60, 1d.10h.25m
    ublock-badware: 4208-0, 1d.10h.24m
    ublock-abuse: 76-0, 1d.10h.32m
    ublock-unbreak: 1849-0, 1d.22h.38m
    easylist: 68652-755, 1d.22h.37m
    urlhaus-1: 5289-0, 50m
    plowe-0: 3646-2, 10d.12h.55m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1607 ms (selfie)
  maxAssetCacheWait: 1296 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    ad-delivery.net: 2
    adthrive.com: 2
    google-analytics.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    stripe.com: 3
```
</details>

**Comment by dechamps** [comment]
I tracked it down to this rule in the "Fanboy’s Annoyance" list: `##.push-container:not(body):not(html)`

One workaround is to add the following under "My filters":

```
packhacker.com#@#.push-container:not(body):not(html)
```

**Comment by mapx-** [comment]
yes, that's the wrong one.

You should remove this outdated list:
https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt

and re-enable the 2 privacy lists.

@ryanbr
