### ISSUE TITLE
[nsfw] cutebabe.co: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#14090]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cutebabe.co/`

### Category

detection

### Describe the issue

Access to the site is only allowed if you deactivate ublock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/180335632-c51fde49-9e6b-4b7c-bc18-012f39f7012c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 439025
  cosmetic: 150027
  scriptlet: 35511
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 41958-220, 1h.13m
    adguard-generic: 66162-1317, 1h.13m
    adguard-mobile: 7975-64, 1h.13m
    curben-phishing: 27536-0, 1h.13m
    curben-pup: 189-1, 1h.13m
    fanboy-cookiemonster: 36540-104, 1h.13m
    ublock-annoyances: 4494-84, 1h.13m
  default: 
    FRA-0: 29597-59, 1h.13m
    easylist: 68713-1076, 1h.13m
    easyprivacy: 27432-599, 1h.13m
    plowe-0: 3645-892, 1h.13m
    ublock-abuse: 76-2, 1h.13m
    ublock-badware: 4204-330, 1h.13m
    ublock-filters: 32264-3591, 1h.13m
    ublock-privacy: 225-3, 1h.13m
    ublock-quick-fixes: 251-19, 1h.13m
    ublock-unbreak: 1834-83, 1h.13m
    urlhaus-1: 5283-1, 1h.13m
filterset (user): [array of 2093 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 2381 ms (selfie)
  maxAssetCacheWait: 448 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
cutebabe.co##+js(no-xhr-if, googlesyndication)
```

**Comment by mapx-** [comment]
@Procyon-b 's filter is working fine.
You should re-test using the default settings / filters

**Comment by mapx-** [comment]
does this filter work for you ?

`cutebabe.co##+js(nostif, show)`

**Comment by mapx-** [comment]
Could be your enabled DNS service has blocking capabilities ? (like adguard one)
