### ISSUE TITLE
raulprietofernandez.net: detection

### ISSUE THREAD

**Issue by fractalismx** [uBlockOrigin/uAssets#14099]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.raulprietofernandez.net/blog/windows/como-generar-y-comprobar-checksums-en-windows`

### Category

detection

### Describe the issue

Detect adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2022-07-22 104224](https://user-images.githubusercontent.com/24963667/180475295-724c5be4-8306-4b0b-b190-dcd8e7883109.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 83142
  cosmetic: 49794
  scriptlet: 17654
  html: 707
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 14h.56m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 2-0, never
    ublock-filters: 32860-93, 2d.15h.6m
    ublock-badware: 4208-0, 2d.15h.5m
    ublock-privacy: 241-0, 2d.15h.11m
    ublock-abuse: 76-0, 2d.15h.16m
    ublock-unbreak: 1849-0, 2d.15h.10m
    easylist: 68636-669, 2d.15h.8m
    easyprivacy: 27422-596, 2d.15h.9m
    plowe-0: 3645-3, 2d.15h.12m
    spa-0: 3902-2, 10h.43m
    spa-1: 4563-107, 2d.15h.7m
    urlhaus-1: 5312-0, 10h.45m
    ublock-quick-fixes: 226-0, 10h.44m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 373 ms (selfie)
  maxAssetCacheWait: 242 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    raulprietofernandez.net: 3
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 10
    pinimg.com: 1
    pushmaster-cdn.xyz: 1
    themoneytizer.com: 28
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by JobcenterTycoon** [comment]
@Yuki2718 there are also popups (click 2 times and random amazon links pops up)

**Comment by Yuki2718** [comment]
> there are also popups (click 2 times and random amazon links pops up)

Sorry what to click?

**Comment by Yuki2718** [comment]
I see this ad: `##.itemBody > div[style*="background-color"]` but don't see popup.

**Comment by JobcenterTycoon** [comment]
When i click anywhere i get a popup. It coming from this inline script
<img width="992" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/180486950-96c6354f-3c49-4863-b040-4fe2c39484eb.PNG">

**Comment by Yuki2718** [comment]
Reproduced with EU IP.
