### ISSUE TITLE
[nsfw] xvideos.com: ads

### ISSUE THREAD

**Issue by AriaMoradi** [uBlockOrigin/uAssets#14094]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.xvideos.com/video18285827/i_ll_tell_mom_edit`

### Category

ads

### Describe the issue

ads for cams.xvideos.com to the left hand side of the video player

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8719233/180429686-46c88a14-767b-4910-85d1-f17d1af3ba93.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80140
  cosmetic: 44953
  scriptlet: 17471
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68709-51, 1d.48m
    easyprivacy: 27431-123, 1d.4h.55m
    plowe-0: 3646-779, 9d.4h.52m
    ublock-abuse: 75-0, 9d.4h.56m
    ublock-badware: 4204-92, 1d.4h.54m
    ublock-filters: 32257-111, 1d.4h.53m
    ublock-privacy: 226-3, 9d.4h.54m
    ublock-quick-fixes: 242-9, 1d.4h.49m
    ublock-unbreak: 1833-42, 1d.4h.52m
    urlhaus-1: 5318-0, 1d.4h.50m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 248 ms (selfie)
  maxAssetCacheWait: 131 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    trafficfactory.biz: 2
```
</details>

**Comment by mapx-** [comment]
However - even if I cannot reproduce the cams section - it's still a self-promo thing which we wont block / hide

**Comment by Daxy7** [comment]
[Ad placeholder, 50/50 chance in random location:](https://user-images.githubusercontent.com/91396482/224696460-3e910433-f076-4d6b-a7fb-2396f8abe456.png) `https://www.xvideos.com/?k=test`
