### ISSUE TITLE
Block some site functionnalities at viedemerde.fr

### ISSUE THREAD

**Issue by stemy2** [uBlockOrigin/uAssets#141]
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Enabling ublock disables some sites functionnalities.

### One or more specific URLs where the issue occurs
viedemerde.fr

### Screenshot in which the issue can be seen
Neverending loading.
![capture](https://cloud.githubusercontent.com/assets/22192600/18507806/2f01fca8-7a72-11e6-9925-41dad06efde8.PNG)

### Steps for anyone to reproduce the issue

1. Enable ublock.
2. Browse to viedemerde.fr.
3. Click on the number wich is below every text.
4. The url form is: www.viedemerde.fr/[category]/[number]
5. The comments loading never ends.

### Your settings

- Browser/version: Firefox 48.0.2
- uBlock Origin version: 1.9.6

##### Your filter lists

Default filter list.

##### Your custom filters (if any)
None

**Comment by gorhill** [comment]
The site requires a script from 3rd-party `criteo.net`, which is blocked by a filter in EasyPrivacy. I created scriptlet to fool the site into thinking the script was loaded.
