### ISSUE TITLE
xxxvideosputas.xxx [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1410]
URL(s) where the issue occurs

`http://xxxvideosputas.xxx/video_2766/sheena_shaw_arruinada_por_la_polla_monster.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
add
```
||xxxvideosputas.xxx/includes/adds/
xxxvideosputas.xxx###ventana-flotante
```
