### ISSUE TITLE
backcar.fr: breakage

### ISSUE THREAD

**Issue by zozoh94** [uBlockOrigin/uAssets#14105]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://backcar.fr/recherche/?size=n_20_n`

### Category

breakage

### Describe the issue

Blocks with car result are hidden.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ublock enabled :
![image](https://user-images.githubusercontent.com/3100264/180605712-384d9839-3ae9-472d-9f45-2f5ffb4f0a5f.png)
Without :
![image](https://user-images.githubusercontent.com/3100264/180605741-2e17eb6b-6af6-4154-aa35-8b5aa3ff9867.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 99987
  cosmetic: 54025
  scriptlet: 17508
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32918-188, 1d.16h.32m
    ublock-badware: 4208-0, 1d.16h.31m
    ublock-privacy: 240-0, 7d.11m
    ublock-abuse: 75-0, 7d.10m
    ublock-unbreak: 1847-0, 1d.16h.30m
    ublock-quick-fixes: 248-0, 1d.16h.27m
    easylist: 68713-630, 1d.16h.29m
    easyprivacy: 27432-887, 1d.16h.28m
    urlhaus-1: 5283-0, 1d.16h.26m
    plowe-0: 3645-3, 1d.16h.34m
    FRA-0: 29597-47, 1d.16h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1497 ms (selfie)
  maxAssetCacheWait: 1015 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`backcar.fr#@#.ad-content`

@ryanbr
