### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by ATaylor66** [uBlockOrigin/uAssets#14100]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=VrXOVdlcSI4`

### Category

breakage

### Describe the issue

for the last 48 hours several youtube videos have refused to play with ublockorigin enabled but play in a private window, I think it is the videos with an ad at the beginning of them. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79996
  cosmetic: 44946
  scriptlet: 17427
  html: 708
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32890-46, 2d.17h.44m
    ublock-badware: 4208-0, 2d.17h.46m
    ublock-privacy: 241-0, 2d.1h.51m
    ublock-abuse: 76-0, 2d.1h.52m
    ublock-unbreak: 1851-0, 2d.17h.48m
    easylist: 68651-570, 2d.17h.45m
    easyprivacy: 27423-595, 2d.17h.47m
    urlhaus-1: 5225-0, 25m
    plowe-0: 3645-3, 2d.1h.50m
    ublock-quick-fixes: 248-0, 26m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1056 ms (selfie)
  maxAssetCacheWait: 270 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    youtube.com: 19
    doubleclick.net: 4
    google.co.uk: 1
    google.com: 7
```
</details>

**Comment by unknowndomain** [comment]
This is the 2nd report, the 1st being #14098 in 6 hours. I am also reporting this issue on my device. 

It works fine in private browsing where uBlock is disabled, the video is loading the doesn't play.

<img width="1552" alt="Screenshot 2022-07-22 at 21 38 23" src="https://user-images.githubusercontent.com/147143/180562744-32fc7b66-0047-465a-99f7-3f42d727c7b3.png">

This is all YouTube videos.

**Comment by mapx-** [comment]
YT issues https://github.com/uBlockOrigin/uAssets/issues/7636
