### ISSUE TITLE
blog.apkhex.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#14109]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blog.apkhex.com/how-to-get-free-fire-dimond/`

### Category

detection

### Describe the issue

anti-adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 105
filterset (summary): 
  network: 88101
  cosmetic: 164054
  scriptlet: 25357
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9890-4, 3d.15h.59m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 3d.15h.58m
    adguard-annoyance: 55135-428, 3d.15h.56m
    fanboy-annoyance: 75143-3112, 9d.17h.53m
    ublock-annoyances: 4493-217, 3d.15h.57m
  default: 
    user-filters: 10-0, never
    easylist: 68652-107, 3d.16h.4m
    easyprivacy: 27426-221, 3d.16h.3m
    ublock-abuse: 76-0, 5d.13h.26m
    ublock-badware: 4204-90, 3d.16h.2m
    ublock-filters: 32241-582, 3d.16h.1m
    ublock-privacy: 226-10, 5d.13h.25m
    ublock-quick-fixes: 252-9, 22h.8m
    ublock-unbreak: 1833-47, 3d.16h
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 863 ms (selfie)
  maxAssetCacheWait: 522 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    ad.plus: 2
    adnxs.com: 1
    doubleclick.net: 1
    googletagservices.com: 1
```
</details>

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/180627384-cd53ed5d-32e7-4f27-b6bd-a705faf7561b.png)

**Comment by Procyon-b** [comment]
2 solutions:
```
||adnxs.com^$redirect-rule=noop.js,domain=apkhex.com
```
or
```
apkhex.com##+js(set,style,noopFunc)
```
