### ISSUE TITLE
tickets.gotransit.com: breakage

### ISSUE THREAD

**Issue by xtrad3markx** [uBlockOrigin/uAssets#14101]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tickets.gotransit.com/en-us/book?type=promo&ticket_weekend_day_pass=1&start_address=WR&start_name=West%20Harbour%20GO&end_address=EX&end_name=Exhibition%20GO`

### Category

breakage

### Describe the issue

It says, "network error" and all the options to purchases tickets and passes are not shown

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 81542
  cosmetic: 26654
  scriptlet: 17470
  html: 710
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32996-306, 1d.20h.18m
    ublock-badware: 4207-0, 1d.20h.17m
    ublock-privacy: 241-1, 1d.20h.16m
    ublock-abuse: 76-0, 1d.20h.11m
    ublock-unbreak: 1854-0, 1d.20h.9m
    ublock-quick-fixes: 248-0, 18h.26m
    adguard-mobile: 7969-167, 1d.20h.25m
    easylist: 68700-25039, 1d.19h.44m
    easyprivacy: 27428-591, 1d.19h.32m
    urlhaus-1: 5289-0, 18h.25m
    plowe-0: 3645-3, 1d.19h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2112 ms (selfie)
  maxAssetCacheWait: 1428 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adnxs.com: 2
    adsrvr.org: 1
    doubleclick.net: 2
```
</details>

**Comment by mapx-** [comment]
I got network error only once, I got this page after that (what does not work ?):

![image](https://user-images.githubusercontent.com/10303732/180518413-d58dfdfe-b6d5-4b0a-8702-819ea6c95ffa.png)
