### ISSUE TITLE
soranews24.com: breakage

### ISSUE THREAD

**Issue by madiechan** [uBlockOrigin/uAssets#14103]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soranews24.com/`

### Category

breakage

### Describe the issue

site images being blocked, often the lead image will load but the others within the text will not. Disabling ublock and reloading loads the images.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/109855139/180602707-50949827-a68e-46df-bfc9-023378a6c877.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 80137
  cosmetic: 44948
  scriptlet: 17430
  html: 709
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32900-46, 1d.17h.2m
    ublock-badware: 4208-0, 1d.17h.1m
    ublock-privacy: 240-0, 18h.31m
    ublock-abuse: 76-0, 18h.30m
    ublock-unbreak: 1847-0, 1d.17h
    ublock-quick-fixes: 237-0, 1d.12h.57m
    easylist: 68709-584, 1d.16h.59m
    easyprivacy: 27432-580, 1d.16h.58m
    urlhaus-1: 5312-0, 1d.12h.56m
    plowe-0: 3646-3, 11d.14h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 895 ms (selfie)
  maxAssetCacheWait: 776 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    soranews24.com: 5
    amazon-adsystem.com: 1
    criteo.net: 2
    doubleclick.net: 1
    googletagmanager.com: 2
    parsely.com: 2
    twitter.com: 2
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr
