### ISSUE TITLE
reevown.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1411]
URL(s) where the issue occurs

`https://reevown.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by happysurf** [comment]
Still recognize ublock.
Last uBlock Origin v1.23.1rc0 + Firefox 70beta + default filters.
