### ISSUE TITLE
20min.ch: breakage

### ISSUE THREAD

**Issue by hakimbalestrieri** [uBlockOrigin/uAssets#14118]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.20min.ch/fr/video/sion-a-tout-perdu-en-six-minutes-718491111631`

### Category

breakage

### Describe the issue

Video not loading

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 99611
  cosmetic: 54047
  scriptlet: 17563
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.6h.30m
  default: 
    user-filters: 1-0, never
    FRA-0: 29597-24, 1d.6h.32m
    easylist: 68753-104, 1d.6h.34m
    easyprivacy: 27435-431, 1d.6h.31m
    plowe-0: 3640-788, 1d.6h.37m
    ublock-abuse: 76-1, 4d.11m
    ublock-badware: 4204-105, 1d.6h.35m
    ublock-filters: 32297-254, 1d.6h.36m
    ublock-privacy: 226-3, 6d.4h.2m
    ublock-quick-fixes: 251-1, 2h.45m
    ublock-unbreak: 1835-42, 1d.6h.33m
    urlhaus-1: 4880-0, 2h.44m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 249 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    da-services.ch: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    tda.link: 1
```
</details>

**Comment by okiehsch** [comment]
@Alex-302
Caused by `AdGuard French filter`
`@@||tdn.da-services.ch/current/20min_durable.js$script,domain=20min.ch`
works.

**Comment by mapx-** [comment]
or
`||da-services.ch^$3p,badfilter`
?
@Yuki2718 
@smed79

**Comment by Alex-302** [comment]
Fixed
