### ISSUE TITLE
documaniatv.com: detection

### ISSUE THREAD

**Issue by Mverte77** [uBlockOrigin/uAssets#14115]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.documaniatv.com/social/el-estado-contra-pablo-ibar-5-el-veredicto-video_26f7ba21e.html`

### Category

detection

### Describe the issue

Imposible to skip adds

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 82806
  cosmetic: 49887
  scriptlet: 17668
  html: 700
listset (total-discarded, last updated): 
  default: 
    user-filters: 98-11, never
    ublock-filters: 32911-36, 2d.18h.8m
    ublock-badware: 4208-1, 2d.18h.7m
    ublock-privacy: 232-0, 9d.8h.29m
    ublock-abuse: 75-0, 9d.8h.28m
    ublock-unbreak: 1849-0, 2d.18h.6m
    easylist: 68709-669, 2d.18h.5m
    easyprivacy: 27431-596, 2d.18h.4m
    urlhaus-1: 4853-0, 15h.57m
    plowe-0: 3646-3, 9d.8h.30m
    spa-0: 3902-20, 15h.58m
    spa-1: 4563-144, 2d.18h.9m
    ublock-quick-fixes: 248-9, 15h.59m
filterset (user): [array of 98 redacted]
trustedset: 
  added: [array of 61 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 1024
  prefetchingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11438 ms (selfie)
  maxAssetCacheWait: 2338 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    documaniatv.com: 2
    ayads.co: 2
```
</details>

**Comment by Mverte77** [comment]
Any solution for this

**Comment by mapx-** [comment]
Do you get detection again ? Explain "this".

**Comment by Mverte77** [comment]
https://www.documaniatv.com/
When you enter a video this message appears and I cannot block it with any configuration that I have tried.

"Por desactive su adblocker, sin publicidad no podriamos darte gratis este servicio. Si lo tiene desactivado y le sigue saliendo este aviso, limpie el cache de su navegador y con eso debería reolverlo."

then forwards to the main page in a loop

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by Mverte77** [comment]
Mexico, thanks
