### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by DrToffik** [uBlockOrigin/uAssets#14112]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yandex.ru/`

### Category

ads

### Describe the issue

The ads keep appearing and I can block those elements, because this feature just doesn't work on this site. It can block anything on any other site, but not on yandex.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/109899214/180642221-b1a726c1-70df-4854-870f-13456ef57ef2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 143454
  cosmetic: 233711
  scriptlet: 38524
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55222-4785, never
    adguard-generic: 66186-5480, never
    adguard-mobile: 7985-323, never
    adguard-social: 17965-1096, never
    adguard-spyware: 26254-10964, never
    adguard-spyware-url: 689-15, never
    block-lan: 43-0, never
    fanboy-annoyance: 76013-60376, never
    fanboy-cookiemonster: 36913-157, never
    fanboy-social: 23233-34, never
    fanboy-thirdparty_social: 68-0, never
    ublock-annoyances: 4498-9, never
  default: 
    user-filters: 0-0, never
    RUS-0: 41977-9, 46m
    easylist: 68760-66, 43m
    easyprivacy: 27441-223, 42m
    plowe-0: 3640-785, 41m
    ublock-abuse: 76-1, 39m
    ublock-badware: 4209-92, 37m
    ublock-filters: 32284-147, 36m
    ublock-privacy: 225-3, 35m
    ublock-quick-fixes: 252-9, 34m
    ublock-unbreak: 1837-42, 33m
    urlhaus-1: 4790-0, 32m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5419 ms
  maxAssetCacheWait: 637 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
subscribe RU counters list and then test again

https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters

**Comment by DrToffik** [comment]
Well, I found the filter list with such emi in the internet, because the link doesn't work for me in any way (i tried to open it and also tried to add the list via the extension menu, maybe I did something wrong). And after the subscribing to this list nothing has changed. Besides, I don't think that the feature of elements blocking that doesn't work only on one site has something to do with those lists... I wonder what is it and why is it so...

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@DrToffik 
The link is working. Probably, in your case, some third-party extension or too strict antivirus settings are responsible for blocking it.

You are using a conflicting filters configuration. How to set up uBlock correctly is described [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=3#1).

You can also [report a problem](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=6#1) and get support there.

**Comment by DrToffik** [comment]
Well, I'm sorry if I'm a bit stupid, but I can't open it in any way. I turned off all the extensions, tried another browser, asked my friend to open it, used VPN and it all had no effect. I have no antivirus and the windows defender is turned off, so I don't think that it has any impact on it. Besides, I tried to use downfor.io and it says that the site is down. I'm really sorry for spending your time but I want to figure out how to make it all work...
![image](https://user-images.githubusercontent.com/109899214/180650510-c222962d-f8c7-4123-ab00-383de91918c4.png)

**Comment by DrToffik** [comment]
Feeling stupid... I had just to turn on this one and there is no ads on the yandex page... Though it didn't fixed the problem with the filter list, but the initial one is solved.
![image](https://user-images.githubusercontent.com/109899214/180650730-6710a73d-eff8-4d8d-90a6-9ba09485747c.png)

**Comment by dimisa-RUAdList** [comment]
Do you have Opera?

**Comment by DrToffik** [comment]
Yes, it's Opera, classic version, not GX

**Comment by dimisa-RUAdList** [comment]
Open the uBlock Origin dashboard, go to the "Настройки" tab and use the "Восстановить из файла" item (at the bottom of the page) to load the [configuration file](http://sendfile.su/1653023). Then update the [filters manually](http://forum.ru-board.com/topic.cgi?forum=5&topic=50761&start=0&limit=1&m=5#1).

**Comment by DrToffik** [comment]
It works now, thank you!

**Comment by dimisa-RUAdList** [comment]
I think I figured out why you couldn't subscribe to RU AdList Counters. You probably tried to open the filter link using the right mouse button.
