### ISSUE TITLE
[nsfw] hypnoporn.net: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#14110]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hypnoporn.net/hypnotized-blonde-neighbor/`

### Category

ads

### Describe the issue

Ads download buttons 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220724-110426_1DM+](https://user-images.githubusercontent.com/98657967/180631807-c856bddb-2276-463b-87b2-cc7c6a484314.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 103
filterset (summary): 
  network: 81108
  cosmetic: 51281
  scriptlet: 17536
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 7985-8, 1h.29m
    easylist: 68754-236, 1h.24m
    easyprivacy: 27440-132, 1h.23m
    plowe-0: 3640-868, 1h.21m
    ublock-abuse: 76-0, 1h.19m
    ublock-badware: 4208-92, 1h.16m
    ublock-filters: 32400-127, 1h.15m
    ublock-privacy: 225-3, 1h.15m
    ublock-quick-fixes: 252-9, 1h.15m
    ublock-unbreak: 1842-44, 1h.15m
    urlhaus-1: 4790-0, 1h.15m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1552 ms (selfie)
  maxAssetCacheWait: 323 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    addthis.com: 1
    google-analytics.com: 1
    pagushythu.com: 1
```
</details>

**Comment by mapx-** [comment]
download button is ok will open a legit page where you can still see the video or download it
`https://k2s.cc/file/e1ef9017efba8/Hypnotized_Blonde%20Neighbor.mp4`

`vidlox` is not available anymore
