### ISSUE TITLE
vozer.fr: nuisance

### ISSUE THREAD

**Issue by Rudloff** [uBlockOrigin/uAssets#14117]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vozer.fr/`

### Category

nuisance

### Describe the issue

The page displays an annoying pop-in asking to enable browser notifications.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/840125/180657902-6bc00443-fda6-451d-a663-180091f347f5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 101281
  cosmetic: 87796
  scriptlet: 19026
  html: 710
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 36979-83, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32942-188, now
    ublock-badware: 4213-0, now
    ublock-privacy: 240-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1849-0, now
    easylist: 68768-651, now
    easyprivacy: 27442-580, now
    urlhaus-1: 4880-0, now
    plowe-0: 3640-3, now
    FRA-0: 29619-355, now
    ublock-quick-fixes: 248-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 30 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 281 ms (selfie)
  maxAssetCacheWait: 198 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    privacy-center.org: 1
```
</details>

**Comment by mapx-** [comment]
You could add

`vozer.fr###batchsdk-ui-alert-container`

in "my filters"

or enable `AdGuard Annoyances` or `Fanboy’s Annoyance`

**Comment by Procyon-b** [comment]
Try this:
```
||batch.com^$3p
```
I've it in my filters for more than 2 years.

**Comment by Rudloff** [comment]
Fanboy's Annoyance List did the trick, thanks.
