### ISSUE TITLE
https://www.wakefit.co/  site does not load in Firefox with uBlock origin enabled, works when UBO is diabled.

### ISSUE THREAD

**Issue by bonyjose** [uBlockOrigin/uAssets#14125]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.wakefit.co/`

### Describe the issue

site wont load when UBO is enabled. tried in Firefox for windows and Firefox for android . diabling UBO solves the page load.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/2097150/180766700-ac55bf36-5f76-46fa-848d-63333322d8b1.png)

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 102 stable

### Settings

none. default lists

**Comment by mapx-** [comment]
add

```
@@||dev.visualwebsiteoptimizer.com/j.php$script,domain=wakefit.co
@@||dev.visualwebsiteoptimizer.com/web/*/tag-$script,domain=wakefit.co
```

@ryanbr
