### ISSUE TITLE
hdfilme.io: detection

### ISSUE THREAD

**Issue by Luchs3-tech** [uBlockOrigin/uAssets#14128]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hdfilme.io/serien1/tempel-3879/staffel-1/folge-5`

### Category

detection

### Describe the issue

The movie keeps loading and won't start

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 83329
  cosmetic: 29965
  scriptlet: 17396
  html: 697
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32795-302, 1d.21h.56m
    ublock-badware: 4212-0, 18m
    ublock-privacy: 232-1, 10d.4h.23m
    ublock-abuse: 76-0, 7d.7m
    ublock-unbreak: 1855-0, 21m
    adguard-mobile: 7986-173, 15m
    easylist: 68773-25085, 17m
    easyprivacy: 27445-600, 18h.14m
    urlhaus-1: 4942-0, 19m
    plowe-0: 3645-3, 6d.18h.48m
    DEU-0: 5894-383, 20m
    ublock-quick-fixes: 249-0, 16m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 637 ms (selfie)
  maxAssetCacheWait: 319 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    9purdfe9xg.com: 2
    addthis.com: 1
    googletagmanager.com: 1
    jwpcdn.com: 2
    thaudray.com: 1
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue, however see if helps:

`hdfilme.*#@#+js(abort-on-property-read, console.clear)`
