### ISSUE TITLE
download.pixelexperience.org: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#14123]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://download.pixelexperience.org/whyred`

### Category

ads

### Describe the issue

Cookies notice

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/98657967/180671333-161e67e5-02d1-4a9e-bd4e-4a06767736ae.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 103
filterset (summary): 
  network: 85670
  cosmetic: 126277
  scriptlet: 23114
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9896-4, 12h.40m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 12h.40m
    fanboy-annoyance: 76037-247, 12h.40m
    ublock-annoyances: 4521-79, 12h.40m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 7985-14, 21h.23m
    easylist: 68754-252, 21h.18m
    easyprivacy: 27440-132, 21h.17m
    ublock-abuse: 76-0, 21h.13m
    ublock-badware: 4208-90, 21h.10m
    ublock-filters: 32400-443, 21h.9m
    ublock-privacy: 225-10, 21h.9m
    ublock-quick-fixes: 252-9, 21h.9m
    ublock-unbreak: 1842-47, 21h.9m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4792 ms (selfie)
  maxAssetCacheWait: 3292 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    pixelexperience.org: 18
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 1
    fouanalytics.com: 1
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
download.pixelexperience.org###cookieconsent\:desc
download.pixelexperience.org##.cc-dismiss.cc-btn
```

@ryanbr for mobile
