### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by ae61195p** [uBlockOrigin/uAssets#14126]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20220725052311&isPremium=y&SearchText=bike+bag&spm=a2g0o.productlist.1000002.0`

### Category

breakage

### Describe the issue

Items on aliexpress do not load up properly when ubo is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-07-25 094728](https://user-images.githubusercontent.com/37096213/180793069-ef580fc5-5eaa-4d28-9d59-c3631037c715.png)
![Screenshot 2022-07-25 094708](https://user-images.githubusercontent.com/37096213/180793066-0ca26f14-47fb-44a4-a7b1-44b4fe09840c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79757
  cosmetic: 44983
  scriptlet: 17487
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68772-51, 11h.34m
    easyprivacy: 27445-123, 15h.38m
    plowe-0: 3640-779, 19h.39m
    ublock-abuse: 77-1, 8d.19h.8m
    ublock-badware: 4209-92, 15h.37m
    ublock-filters: 32266-113, 2d.19h.58m
    ublock-privacy: 226-4, 6d.1m
    ublock-quick-fixes: 251-1, 15h.36m
    ublock-unbreak: 1834-42, 2d.19h.57m
    urlhaus-1: 4880-0, 15h.35m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 73 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 329 ms (selfie)
  maxAssetCacheWait: 131 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    creativecdn.com: 1
    facebook.net: 1
    go-mpulse.net: 1
    google-analytics.com: 2
    googletagmanager.com: 1
    mmstat.com: 13
```
</details>

**Comment by mapx-** [comment]
> Items on aliexpress do not load up properly when ubo is enabled.

What exactly is missing ?

**Comment by ae61195p** [comment]
![Screenshot 2022-07-25 094708](https://user-images.githubusercontent.com/37096213/180792812-a1326a53-211a-44a3-ad15-f2567ee28d0e.png)
![Screenshot 2022-07-25 094728](https://user-images.githubusercontent.com/37096213/180792815-f081b300-3519-464d-9134-a546cc2550e6.png)

**Comment by mapx-** [comment]
I cannot reproduce your issue.
Did you try disabling any other extension or built blocker in your browser ?

**Comment by ae61195p** [comment]
Yes I disabled all other extensions. The site loads the item images only when ublock is disabled. I reset ublock to factory settings and it still does not load correctly

**Comment by mapx-** [comment]
Open the logger, refresh that aliexpress page, go back in the logger copy & paste all blocked requests here

**Comment by ae61195p** [comment]
Upon refresh, page loaded correctly. I had cleared Chrome browser data (browsing histroy, cache, etc) prior to the refresh, so it must have been something with that. Problem solved
