### ISSUE TITLE
rus.tvnet.lv: detection

### ISSUE THREAD

**Issue by nightcat2005** [uBlockOrigin/uAssets#14135]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rus.tvnet.lv/`

### Category

detection

### Describe the issue

Wesite detect ublock origin and does not show content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 106884
  cosmetic: 84705
  scriptlet: 19200
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30206-72, 3d.21h.26m
    LVA-0: 407-3, 3d.21h.33m
    RUS-0: 41977-3616, 1d.21h.20m
  default: 
    user-filters: 8-0, never
    easylist: 68712-236, 3d.21h.32m
    easyprivacy: 27433-240, 3d.21h.31m
    plowe-0: 3645-786, 5d.10h.18m
    ublock-abuse: 75-1, 12d.31m
    ublock-badware: 4204-92, 3d.21h.30m
    ublock-filters: 32266-155, 3d.21h.29m
    ublock-privacy: 226-3, 12d.30m
    ublock-quick-fixes: 251-1, 21h.17m
    ublock-unbreak: 1835-43, 3d.21h.28m
    urlhaus-1: 4999-0, 21h.16m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2981 ms (selfie)
  maxAssetCacheWait: 659 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    chartbeat.com: 2
    cxense.com: 1
    doubleclick.net: 1
    gemius.pl: 1
    googletagmanager.com: 1
    postimees.ee: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
@mapx- 
The rules for this domain are contained in RU AdList.

https://github.com/easylist/ruadlist/commit/4f58a3b212a6dd69dd3807d86da31a05a99038df

**Comment by Yuki2718** [comment]
`www.tvnet.lv`, a Latvian page, has the same anti-adb with Latvian List enabled so still needs fix.
