### ISSUE TITLE
web.roblox.com: detection

### ISSUE THREAD

**Issue by githubmemeb** [uBlockOrigin/uAssets#14138]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://web.roblox.com/games/166986752/Plane-Crazy`

### Category

Roblox

### Describe the issue

It made Me block the roblox play button and the taskbar

### Screenshot(s)

<details> https://web.roblox.com/games/6068707488/Navy-Simulator
<summary>Screenshot(s)</summary> While i was playing roblox i wanted to use Block element, i blocked the play button and the taskbar which was not supposed to happen so i didn't know what to do at that time but as i keep trying and trying it wont work which means that only a taskbar and a play button is blocked

![Screen Shot 2022-07-26 at 6 47 40 AM](https://user-images.githubusercontent.com/110033323/180998773-cde2c87f-b715-4c9f-a5f8-1a1dc747daf9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-50, never
    easyprivacy: 27172-122, never
    plowe-0: 3639-784, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-89, never
    ublock-filters: 31779-96, never
    ublock-privacy: 222-1, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-40, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7483 ms
  maxAssetCacheWait: 153 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    roblox.com: 10
    google-analytics.com: 1
```
</details> Blocked taskbar , blocked play button

**Comment by githubmemeb** [comment]
I may want my stuff back as i am sorry about blocking something which is not common to do

**Comment by mapx-** [comment]
If you are saying you randomly blocked legit stuff => right click uBO icon, options, "my filters" tab => remove roblox stuff from there, click "apply changes"
