### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by sunvexcrossing** [uBlockOrigin/uAssets#14136]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=BObS94qOH84`

### Category

breakage

### Describe the issue

When attempting to load the page, whether through a link or by refreshing the page, the video never loads. If uBlock Origin is disabled and an ad is watched, the video plays fine after the ad, but reloading the page causes the issue to reoccur. Other parts of the page, such as the comments section, load fine. Other videos work fine with uBlock Origin on. Deactivating all other extensions, clearing the cache, and restarting the browser did not help. I have had this issue with one other video, but it no longer occurs there after watching an ad.

### Screenshot(s)

<details>
<summary>Screenshot of the video infinitely loading</summary>

![image](https://user-images.githubusercontent.com/110025430/180973693-f376e5f6-c23c-4595-88ae-e8adb623e4e2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79849
  cosmetic: 44997
  scriptlet: 17468
  html: 710
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32946-38, 2m
    ublock-badware: 4213-0, 2m
    ublock-privacy: 240-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1848-0, 2m
    ublock-quick-fixes: 257-0, 2m
    easylist: 68796-588, 2m
    easyprivacy: 27449-580, 2m
    urlhaus-1: 4937-0, 2m
    plowe-0: 3640-3, 2m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 351 ms (selfie)
  maxAssetCacheWait: 219 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    youtube.com: 21
    doubleclick.net: 2
    google.co.nz: 1
    google.com: 5
```
</details>

**Comment by mapx-** [comment]
duplicate

read the last comments in YT all issues starting with: 
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1194755922
