### ISSUE TITLE
delicious-audio.com: detection

### ISSUE THREAD

**Issue by EricBuist** [uBlockOrigin/uAssets#14134]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://delicious-audio.com/the-delis-events-for-musicians/`

### Category

detection

### Describe the issue

URL such as `https://delicious-audio.com/the-delis-events-for-musicians/` seem to work at first, then a pop up shows stating that an ad blocker was detected. I cannot effectively browse the website unless I temporarily uninstall or disable uBlock Origin, or switch to another Web browser without ad blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 99680
  cosmetic: 54048
  scriptlet: 17528
  html: 710
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32953-38, 2d.6h.41m
    ublock-badware: 4208-0, 2d.6h.40m
    ublock-privacy: 240-0, 7d.23h.14m
    ublock-abuse: 76-0, 7d.20m
    ublock-unbreak: 1848-0, 2d.6h.45m
    easylist: 68753-639, 2d.6h.44m
    easyprivacy: 27435-580, 2d.6h.43m
    urlhaus-1: 4942-0, 2h.51m
    plowe-0: 3645-3, 4d.2m
    FRA-0: 29597-496, 2d.6h.42m
    ublock-quick-fixes: 248-0, 2h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 137 ms (selfie)
  maxAssetCacheWait: 74 ms
popupPanel: 
  blocked: 64
  blockedDetails: 
    clarity.ms: 1
    doubleclick.net: 6
    getnitropack.com: 2
    google.com: 4
    googlesyndication.com: 2
    googletagmanager.com: 6
    nitrocdn.com: 3
    themoneytizer.com: 6
    youtube.com: 34
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
delicious-audio.com#@#.ad-box
```
