### ISSUE TITLE
[nsfw] grey.egybest.fit: detection

### ISSUE THREAD

**Issue by zOmar11** [uBlockOrigin/uAssets#14139]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://grey.egybest.fit/movie/thor-love-and-thunder-2022/?ref=home-trends`

### Category

detection

### Describe the issue

detects ublock origin when trying to watch a movie

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79835
  cosmetic: 44986
  scriptlet: 17493
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68771-51, 1d.15h.13m
    easyprivacy: 27446-123, 1d.15h.12m
    plowe-0: 3645-779, 4d.23h.58m
    ublock-abuse: 76-0, 6d.14h.9m
    ublock-badware: 4209-92, 1d.15h.11m
    ublock-filters: 32287-113, 1d.15h.10m
    ublock-privacy: 226-3, 6d.14h.8m
    ublock-quick-fixes: 251-1, 13h.2m
    ublock-unbreak: 1837-42, 1d.15h.9m
    urlhaus-1: 4937-0, 13h.1m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 796 ms (selfie)
  maxAssetCacheWait: 458 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    thaudray.com: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/10255
