### ISSUE TITLE
Cosmetic issue from filter on https://comicbook.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [uBlockOrigin/uAssets#14131]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://comicbook.com/gaming/news/cyberpunk-2077-harry-potter-reddit-secret/`

### Describe the issue

Basically the filter is too broad and causing some content to be cut off. The filter is in uBlock filters and is `comicbook.com##body:style(margin-top:84px !important)`. A simple change to `comicbook.com##body[class^="pcm-public"]:style(margin-top: 84px !important;)` will fix content being cutoff.

### Screenshot(s)

![comicbook screenshot](https://user-images.githubusercontent.com/100051044/180838428-64219b46-389c-4669-96db-87ac8e507418.JPG)

### uBlock Origin version

uBlock Origin 1.43.0

### Browser name and version

Version 103.0.5060.134 (Official Build) (64-bit)

### Settings

See description for suggestion

**Comment by krystian3w** [comment]
Maybe this was copied from AdGuard Base: https://github.com/AdguardTeam/AdguardFilters/commit/9c7366fd15891806f5999ccafc2508674c458185 https://github.com/AdguardTeam/AdguardFilters/issues/29292

**Comment by mapx-** [comment]
I get no breakage.

**Comment by joebagadonuts188** [comment]
I don't know if the rule was copied. To be clear, I still think the rule should exist. I just think it needs to be fine tuned so that it only affects the top of the page and not other elements. The suggestion I provided earlier seems to work fine.

**Comment by krystian3w** [comment]
So for moment enable AG Base: https://filterlists.com/lists/adguard-base-filter-ublock-origin

if works fine then uBO need:

`comicbook.com#$#body > section.main { margin-top: 84px!important; }`

**Comment by joebagadonuts188** [comment]
I enabled AG Base and still have the issue occurring.

**Comment by Procyon-b** [comment]
Like the others I don't see a margin problem on this site. For me all pages have the classname `pcm-public` on the `body` tag.
What are you doing to get pages with and without this classname?

**Comment by joebagadonuts188** [comment]
The problem is not the margin at the top, it is further down. It is adding a margin to the reddit post that is in the middle of the article. If you disable the filter, you will see that the reddit post is corrected and aligned properly and not moved 84 px downward. Also, I am not getting pages without the `pcm-public` class. I am saying to make the filter with the specific class name in it, instead of just `body`, to prevent the filter affecting other elements on the page that don't need the filter.

**Comment by Procyon-b** [comment]
OK. I get it now.
@mapx- @krystian3w the problem is with the iframe in his screenshot (where the video is displayed). There is a blank above, and the bottom of the frame is not visible. You can't see this:
```
r/GamingDetail [...] 2m ago
2688 points 59 comments
```

**Comment by mapx-** [comment]
filter already replaced

**Comment by krystian3w** [comment]
For my margin gone:
![obraz](https://user-images.githubusercontent.com/35370833/180877387-6a70f13b-17db-4a2f-af69-b662f65d0eac.png)

**Comment by joebagadonuts188** [comment]
Thank you!! That was it. I really appreciate it

**Comment by krystian3w** [comment]
In future try add paint red box with arrrows: https://user-images.githubusercontent.com/35370833/180877704-48e829e0-83d7-4b89-bd2d-ac4a869e17b5.png

**Comment by Procyon-b** [comment]
@mapx- sorry. didn't see your fix.
By the way `.pcm-public` is a valid classname. No need to use `[class^=...]`

**Comment by krystian3w** [comment]
in future page can use only `.pcm-public-Proton-Krystian-joe-is-not-albatroz`. Then these fool by webmaster look bad in filters and we can generate delay by `[class^=...]`.
