### ISSUE TITLE
send.cm: hcaptcha breakage

### ISSUE THREAD

**Issue by rxihoon** [uBlockOrigin/uAssets#14130]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://send.cm/register`

### Category

breakage

### Describe the issue

Having uBO enabled makes the hcaptcha not load. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 104
filterset (summary): 
  network: 85758
  cosmetic: 72751
  scriptlet: 20087
  html: 713
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55222-2129, 1d.6h.50m
  default: 
    user-filters: 3-0, never
    ublock-filters: 33045-298, 1d.6h.50m
    ublock-badware: 4212-0, 1d.6h.50m
    ublock-privacy: 240-1, 1d.6h.50m
    ublock-abuse: 76-0, 1d.6h.50m
    ublock-unbreak: 1854-0, 1d.6h.50m
    ublock-quick-fixes: 248-0, 6h.42m
    adguard-mobile: 7985-167, 1d.6h.52m
    easylist: 68760-25058, 1d.6h.50m
    easyprivacy: 27441-590, 1d.6h.50m
    urlhaus-1: 4999-0, 6h.41m
    plowe-0: 3640-3, 1d.6h.50m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1447 ms (selfie)
  maxAssetCacheWait: 580 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JorgeGNL** [comment]
This issue continues to occur.

**Comment by JobcenterTycoon** [comment]
The captcha works fine for me

**Comment by JorgeGNL** [comment]
It's working again. Possible uBlock Origin was not updated yet.
