### ISSUE TITLE
laptopmag.com [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1413]
URL(s) where the issue occurs

`https://www.laptopmag.com/articles/get-4k-dell-gaming-laptop-611`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
it does not work this appears

![](https://i.imgur.com/sdiHyqJ.png)

**Comment by mapx-** [comment]
Weird, I cannot reproduce the issue.

**Comment by xDarkARG** [comment]
then I will clean the history and re-install the return extension and try

**Comment by okiehsch** [comment]
The site uses Instart Logic, to fix your issue you will have to use `uBO-Extra`.

**Comment by mapx-** [comment]
oh right .. @xDarkARG  install it from:
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco
