### ISSUE TITLE
onelink.me: breakage

### ISSUE THREAD

**Issue by zeref-dragneel** [uBlockOrigin/uAssets#14143]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=7bH4hZF-4Vg`
`https://www.youtube.com/watch?v=J1Gq3HmWwbw`
`https://www.youtube.com/watch?v=eeV7eupmb7U`
`https://www.youtube.com/watch?v=PnAW2kslte0`
Etc.

### Category

breakage

### Describe the issue

uBlock Origin blocks when I click on onelink's links under youtube description

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80556
  cosmetic: 46047
  scriptlet: 17568
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1840-0, 23m
    easylist: 68820-56, 23m
    easyprivacy: 27450-128, 23m
    plowe-0: 3641-779, 23m
    ublock-abuse: 76-0, 23m
    ublock-badware: 4209-92, 23m
    ublock-filters: 32281-126, 23m
    ublock-privacy: 225-3, 23m
    ublock-quick-fixes: 262-1, 23m
    ublock-unbreak: 1836-42, 23m
    urlhaus-1: 4926-0, 23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2205 ms
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    youtube.com: 14
    doubleclick.net: 2
    google.com: 6
    google.com.vn: 1
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by krystian3w** [comment]
EasyList banned by:

`||onelink.me^`

So strict block is enabled.


To disable possible use:

`||onelink.me^$badfilter`
`||onelink.me^$all,~doc,important`
