### ISSUE TITLE
scanurl.net: breakage

### ISSUE THREAD

**Issue by tekeek** [uBlockOrigin/uAssets#14148]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://scanurl.net/`

### Category

breakage

### Describe the issue

`https://scanurl.net/`

By disabling Ublock it works. I reset Ublock to default to be certain and the issue still applies. I did discover if I uncheck Parse and enforce cosmetic filters it will load without disabling the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79735
  cosmetic: 44894
  scriptlet: 17448
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 68796-51, 1d.14h.46m
    easyprivacy: 27449-123, 1d.14h.45m
    plowe-0: 3641-779, 10h.38m
    ublock-abuse: 76-0, 1d.6h.41m
    ublock-badware: 4209-92, 1d.14h.44m
    ublock-filters: 32289-115, 1d.14h.43m
    ublock-privacy: 225-3, 1d.6h.40m
    ublock-unbreak: 1836-42, 1d.14h.42m
    urlhaus-1: 4926-0, 6h.36m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 921 ms (selfie)
  maxAssetCacheWait: 660 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable again `Parse and enforce cosmetic filters` and then update the filter lists
