### ISSUE TITLE
genbird.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1414]
URL(s) where the issue occurs

`http://genbird.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SMed79** [comment]
add `genbird.com##script:inject(overlay-buster.js)`
or
https://forums.lanik.us/viewtopic.php?f=62&t=21101

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters @mapx-
