### ISSUE TITLE
novelgames.com: breakage

### ISSUE THREAD

**Issue by GolfingSuccess** [uBlockOrigin/uAssets#14141]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.novelgames.com/`

### Category

breakage

### Describe the issue

If you click the "Play Games" button at the top, and then click on any item in the "Game Categories" list on the left, the game list gets stuck with a loading icon.

Also, if you go to any game and click inside to start it, it will get stuck for a few seconds before showing the "You can skip this ad in 5 seconds" screen.

Finally, if you finish a game, it gets stuck on a loading icon for 8-10 seconds before it returns to the game (what it's supposed to do is show the "skip this ad" screen again immediately, and not always).

If I disable uBO (click the big power button and refresh), none of these issues happen (in the latter case, it loads the ad from the ad provider normally).

Up until a few days ago, uBO did not cause any problems to the site (well, apart from not letting it load its ad provider haha).

### Example

This assumes that you are **not** logged into novelgames.com (e.g. via incognito mode).

Let's suppose we want to browse through **Logic** games. Firstly, go to https://novelgames.com. Then, click the "Play Games" button at the top. Finally, on the big list to the left, click "Logic". This is where the first issue appears; the results never load!

Now, we want to play [**Easy as ABC**](https://www.novelgames.com/en/easyabc/). The first step is to click inside the game when it initializes. This is where the second issue introduces itself; an orange wheel is spinning for 8-10 seconds, and only then is an internal ad forced through.

After that, the game has loaded up. Just click "START" and "START", and then click the "Hint" button 24 times to complete the game. After you click "Discard", the third issue appears, in similar fashion to the second but without an internal ad appearing; it's just the loading icon.

Repeating the above steps with uBO disabled, none of these issues present themselves.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79660
  cosmetic: 44875
  scriptlet: 17446
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68753-51, 3d.6h.24m
    easyprivacy: 27434-123, 3d.14h.28m
    plowe-0: 3644-780, 9d.22h.41m
    ublock-abuse: 76-0, 2d.14h.22m
    ublock-badware: 4204-92, 3d.14h.27m
    ublock-filters: 32281-113, 3d.14h.26m
    ublock-privacy: 225-3, 2d.14h.21m
    ublock-unbreak: 1836-42, 3d.14h.25m
    urlhaus-1: 4899-0, 39m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1285 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    novelgames.com: 1
    btloader.com: 1
    clarity.ms: 1
    google-analytics.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    intergient.com: 4
    moatads.com: 1
    quantserve.com: 1
```
</details>

**Comment by Procyon-b** [comment]
You can solve the first problem with these filters:
```
novelgames.com##+js(set, window.ramp.destroyUnits, noopFunc)
novelgames.com##+js(set, etInsertAd, noopFunc)
```

**Comment by mapx-** [comment]
Test

```
@@||novelgames.com^$script,1p
@@||cdn.intergi.com^$script,domain=novelgames.com
@@||cdn.intergient.com^$domain=novelgames.com
@@||cdn.intergient.com^$1p
*$image,domain=novelgames.com,redirect-rule=1x1.gif
*$script,domain=novelgames.com,redirect-rule=noopjs
*$xhr,domain=novelgames.com,redirect-rule=nooptext
novelgames.com##+js(nano-sib)
```

**Comment by GolfingSuccess** [comment]
> Test
> 
> ```
> @@||novelgames.com^$script,1p
> @@||cdn.intergi.com^$script,domain=novelgames.com
> @@||cdn.intergient.com^$domain=novelgames.com
> @@||cdn.intergient.com^$1p
> *$image,domain=novelgames.com,redirect-rule=1x1.gif
> *$script,domain=novelgames.com,redirect-rule=noopjs
> *$xhr,domain=novelgames.com,redirect-rule=nooptext
> novelgames.com##+js(nano-sib)
> ```

Woah, so I just tested this and did not expect this behavior! It fixes the first issue completely. Now, for the other two, I can see it lets the ad provider through, but no actual ad appears and, in the second case, the 15 seconds of the skip screen are fast-forwarded to a fraction of a second. This definitely improves things **a lot**!

**Comment by GolfingSuccess** [comment]
UPDATE: Unfortunately, these rules had worked for a day or so, but, now, the slow loading issues (second and third) have returned. Disabling the rules now has no effect either, as the first problem (game category lists not loading) is seemingly fixed completely.
