### ISSUE TITLE
fmovies.to: ads

### ISSUE THREAD

**Issue by kiencuongpo** [uBlockOrigin/uAssets#14144]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fmovies.to/movie/minions-the-rise-of-gru-qz2ww/1-full`

### Category

ads

### Describe the issue

go to slotslights.com win real money

(You must watch the video to see it) I don't know if this is called advertising because when I visit this site it contains gambling ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/102970802/181234515-70e6dc8c-bed2-4e2b-b311-3f401665b688.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 86
filterset (summary): 
  network: 80556
  cosmetic: 21412
  scriptlet: 17568
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1840-31, 2m
    easylist: 68820-24401, 2m
    easyprivacy: 27450-130, 2m
    plowe-0: 3641-779, 2m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4209-92, 1m
    ublock-filters: 32271-370, 1m
    ublock-privacy: 225-4, 1m
    ublock-quick-fixes: 260-1, 1m
    ublock-unbreak: 1836-42, 1m
    urlhaus-1: 4926-0, 1m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2277 ms
  maxAssetCacheWait: 319 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    fmovies.to: 1
    addthis.com: 1
    amung.us: 1
    disqus.com: 1
    likedstring.com: 2
```
</details>

**Comment by MasterKia** [comment]
> go to slotslights.com win real money



>> I don't know if this is called advertising

It's not. This is _**baked into**_ the video itself. Even if you download the actual video and open it using a video player it would still have that "win real money" watermark at the beginning.

**Comment by MasterKia** [comment]
> ```yaml
> Chromium: 86
> ```

Please update your browser, it's 2 years old.
