### ISSUE TITLE
avherald.com: ads

### ISSUE THREAD

**Issue by reuveng60** [uBlockOrigin/uAssets#14149]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://avherald.com/h?article=4fc2feb3&opt=0`

### Category

ads

### Describe the issue

There are extra elements that Zap is needed but zap does not save the changes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/23532620/181380630-ffa02a2d-8b65-43c0-9d5c-235446793476.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80573
  cosmetic: 45897
  scriptlet: 17572
  html: 0
listset (total-discarded, last updated): 
  added: 
    ISR-0: 1635-0, 4h.13m
  default: 
    user-filters: 80-7, never
    easylist: 68768-51, 3d.5h.1m
    easyprivacy: 27442-125, 3d.4h.59m
    plowe-0: 3645-779, 6d.4h.18m
    ublock-abuse: 76-0, 7d.1h.4m
    ublock-badware: 4209-92, 3d.5h
    ublock-filters: 32288-112, 2d.21m
    ublock-privacy: 226-4, 7d.1h.3m
    ublock-quick-fixes: 271-1, 4h.14m
    ublock-unbreak: 1836-42, 2d.18h.18m
    urlhaus-1: 4948-0, 4h.12m
filterset (user): [array of 80 redacted]
trustedset: 
  added: [array of 658 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 26 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 69 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
`no-cosmetic-filtering: true`
Please enable cosmetic filtering on this site. Click ublock's icon to open the popup panel, and click the icon. https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

**Comment by reuveng60** [comment]
Yes, but it will leave some black areas:

**Comment by Procyon-b** [comment]
If you disable cosmetic filtering, nothing will be hidden.
Where do you see black areas?

**Comment by reuveng60** [comment]
Yes but the problem is that I’ll be missing the highlighted information:

 



 

 

 

No cosmetic filters:

 



 

 

Cosmetic filters on:

**Comment by Procyon-b** [comment]
You're replying by email. I don't see your attachments if you're adding any.

**Comment by reuveng60** [comment]
The problem is that I’ll be missing the highlighted information:
![image](https://user-images.githubusercontent.com/23532620/181387656-9d4a8fdb-31bd-4948-b279-b885428550fd.png)

Here is how it looks like without cosmetic filters:
![image](https://user-images.githubusercontent.com/23532620/181387771-09b09126-b9cc-49be-91e0-6dc41500583b.png)
If I turn on the cosmetic filters I get the information with extra blank space where the ads use to be:
![image](https://user-images.githubusercontent.com/23532620/181387900-1731c95c-13e0-45d8-8834-4e65ee50631e.png)
I can Zap the black space but it's temporary. How do I make it permanent?

**Comment by Procyon-b** [comment]
I've loaded the same page ("Canada rouge") and don't have the text hidden.
One of your user filters must be at fault.
To be sure, open ublock's dashboard, go to the "_Filter lists_" tab, uncheck "_User filters_" then click "_Apply changes_". Reload the page with cosmetic filters enabled. It should display correctly.
Go back to the "_Filter list_" tab to reenable your user filters and go to the "_My filters_" tab to find the filter at fault.

**Comment by reuveng60** [comment]
Yep, one of the user filters was the culprit. Sorry for the confusion and thank you for your guidance.

**Comment by Procyon-b** [comment]
No problem. We are all here to help.   :)
