### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by aetinx** [uBlockOrigin/uAssets#14147]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/`

### Category

ads

### Describe the issue

Sponsored ads appear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/65425469/181276852-e4574fb0-4fb5-40b7-a57e-a2c08ac2b373.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79817
  cosmetic: 45002
  scriptlet: 17511
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    easylist: 68792-51, 1d.19h.4m
    easyprivacy: 27449-123, 1d.19h.6m
    plowe-0: 3646-779, 12d.12h.51m
    ublock-abuse: 76-0, 2d.23h.47m
    ublock-badware: 4209-92, 1d.19h.3m
    ublock-filters: 32302-114, 1d.15h.2m
    ublock-privacy: 225-3, 2d.23h.46m
    ublock-quick-fixes: 262-1, 21h
    ublock-unbreak: 1835-42, 21h.2m
    urlhaus-1: 4899-0, 21h.1m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1548 ms (selfie)
  maxAssetCacheWait: 690 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    instagram.com: 34
```
</details>

**Comment by gorhill** [comment]
Was this immediately after browser launch?

**Comment by aetinx** [comment]
> Was this immediately after browser launch?

No.

**Comment by krystian3w** [comment]
Need subscribe profiles?

**Comment by aetinx** [comment]
> Need subscribe profiles?

?

**Comment by krystian3w** [comment]
To reproduce needed is subscribe domek profiles, becasue if I subscribe only Ewa Chodakowska then have only her posts.

Firend zone may no exist on Instagram.

**Comment by aetinx** [comment]
@mapx- this clearly isn't finished.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/65425469/182509691-61309e9e-6a5a-46cb-9ad8-a5e51bb38d00.png">

**Comment by krystian3w** [comment]
But we don't follow many Instagram profile to see sponsored posts.

Try save wall to zip file maybe someone write ExtendedCSS to manually hide post (after publish in uBo stock list the Meta can be rebuilt post in 8h to down global filter - in Quick fixes can help for 1/3 of viewers Instagram wall and need continue update 3 tires at day).

**Comment by aetinx** [comment]
The ads are still here.

![image](https://user-images.githubusercontent.com/65425469/184716543-2594ea1f-66e7-4846-a8ec-e656e2fcf2b4.png)

**Comment by krystian3w** [comment]
test after unfollow all ebay instagram account/profiles.

**Comment by MasterKia** [comment]
@aetinx 

Does the filters said in this post help?

https://reddit.com/r/uBlockOrigin/comments/wmnwhf/ads_going_through_ublock_on_instagram_desktop/

**Comment by krystian3w** [comment]
I think Meta can try inject fake letters in span/div so all `/Sponsor(ed)?/` fails.

https://codepen.io/web-forum-dobre/pen/vYdvVMz - `exampleemail@dot.com` for Polish community in anti-spam topic.

**Comment by aetinx** [comment]
> @aetinx
> 
> Does the filters said in this post help?
> 
> https://reddit.com/r/uBlockOrigin/comments/wmnwhf/ads_going_through_ublock_on_instagram_desktop/

Yes.

**Comment by MasterKia** [comment]
@okiehsch 

A) `instagram.com##article div:has-text(/Sponsored/i):upward(article)`

B) `instagram.com##article div:has-text(/Sponsored/i):upward(article > div)`

C) `instagram.com##article > div > div > div > header > div:nth-of-type(2) > div:nth-of-type(2) > div > div > span:has-text(/Sponsored/i):upward(article > div)`

**Comment by MasterKia** [comment]
@aetinx Force update your lists, it's fixed.

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
