### ISSUE TITLE
[nsfw] mdisk.me: ads

### ISSUE THREAD

**Issue by Adwaid5048** [uBlockOrigin/uAssets#14140]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mdisk.me/convertor/90x149/kGSDNs`

### Category

ads

### Describe the issue

The messenger chat type bubble ad and lots of other ads keep showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 81164
  cosmetic: 26663
  scriptlet: 17489
  html: 702
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33035-306, 3d.11h.8m
    ublock-badware: 4207-0, 3d.11h.7m
    ublock-privacy: 232-1, 11d.22h.42m
    ublock-abuse: 75-0, 11d.22h.41m
    ublock-unbreak: 1853-0, 3d.11h.9m
    adguard-mobile: 7978-167, 3d.11h.5m
    easylist: 68707-25046, 5d.11h.41m
    easyprivacy: 27434-590, 3d.11h.6m
    urlhaus-1: 4899-0, 5m
    plowe-0: 3645-3, 7d.5h.15m
    ublock-quick-fixes: 236-0, 6m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5660 ms (selfie)
  maxAssetCacheWait: 4930 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    mdisk.me: 1
    beamempire.com: 1
    doubleclick.net: 1
    google.co.in: 1
    google.com: 2
    promotebred.com: 1
```
</details>

**Comment by mapx-** [comment]
provide a screenshot indicating the ads

**Comment by ghajini** [comment]
reproduced on android device...
here's another way on desktop devices
add-on => mobile view switcher
clear cookie data
these are 

https://user-images.githubusercontent.com/20338483/181199418-ba40b750-3443-457a-abf7-c69f898c49f7.png
https://user-images.githubusercontent.com/20338483/181199429-67d2f54e-ddc0-4863-a59f-9849668a515e.png

```
mdisk.me##.liveBox
mdisk.me##.live-ad
mdisk.me##.sterra-ad
```

**Comment by mapx-** [comment]
@ryanbr
