### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by helgen77** [uBlockOrigin/uAssets#14154]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=bYlvRK-tOKI`

### Category

breakage

### Describe the issue

ublock has an issue with youtube and "fanboys annoyance" list causing breakage where videos are not playing. disabling this list makes videos play like normal.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 67416
  cosmetic: 177893
  scriptlet: 24767
  html: 736
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
  added: 
    block-lan: 43-0, 21h.53m
    adguard-annoyance: 55342-4374, 8h.50m
    adguard-social: 18013-35, 8h.51m
    fanboy-annoyance: 75627-37692, 6d.17h.52m
    fanboy-cookiemonster: 36540-173, 6d.17h.53m
    ublock-annoyances: 4511-5, 8h.52m
    SWE-1: 4087-5, 8h.53m
  default: 
    user-filters: 4-0, never
    ublock-filters: 32952-42, 8h.56m
    ublock-badware: 4213-0, 8h.55m
    ublock-privacy: 240-0, 3d.9h.44m
    ublock-abuse: 76-0, 3d.9h.43m
    ublock-unbreak: 1849-0, 8h.54m
    ublock-quick-fixes: 277-0, 4h.47m
    easylist: 68889-599, 8h.49m
    urlhaus-1: 4788-0, 4h.46m
    plowe-0: 3644-3, 11d.20h.2m
    NOR-0: 2802-10, 4h.48m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 658 ms (selfie)
  maxAssetCacheWait: 677 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    youtube.com: 2
    doubleclick.net: 2
```
</details>

**Comment by mapx-** [comment]
I can not reproduce your issue with fanboy's annoyances.

However, if you still can reproduce the breakage could you test (one by one) the FA's filters you find in the logger (disabling them) ?

@ryanbr

**Comment by ryanbr** [comment]
Haven't been able to reproduce any issues with YT, maybe just purge and update filters?
