### ISSUE TITLE
superfb.com: ads

### ISSUE THREAD

**Issue by tuncaydnz** [uBlockOrigin/uAssets#14153]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.superfb.com/futbol/jesus-takima-guveniyor-bugun-takim-oldukSXHBQ138194SXQ`

### Category

ads

### Describe the issue

Please add this `/_js/prbd_6.19.0.js` prebid script to EasyList.

### Screenshot(s)

`https://www.superfb.com/futbol/jesus-takima-guveniyor-bugun-takim-oldukSXHBQ138194SXQ`
<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/181577705-efefaecd-3950-4149-ac3b-9cfd55b5575d.png)

</details>

`https://www.webaslan.com/`
<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/181579083-6d8e6232-9f4c-4142-bf08-d51830cbae7d.png)

</details>

`https://www.sporx.com/`
<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/181579278-dfee268a-821e-41ac-95ad-ec9f7b410015.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 84619
  cosmetic: 139664
  scriptlet: 17775
  html: 3
listset (total-discarded, last updated): 
  removed: 
    ublock-filters: null
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    ublock-quick-fixes: null
  added: 
    adguard-generic: 66188-712, 3d.17h.30m
    adguard-spyware: 26257-756, 3d.17h.25m
    adguard-spyware-url: 689-14, 3d.17h.27m
    adguard-annoyance: 55227-1093, 3d.17h.24m
    adguard-social: 17971-24, 3d.17h.26m
  default: 
    user-filters: 64-0, never
    ublock-unbreak: 1849-0, 3d.17h.31m
    easylist: 68771-888, 3d.17h.29m
    TUR-0: 8697-77, 3d.17h.28m
filterset (user): [array of 68 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 487 ms (selfie)
  maxAssetCacheWait: 344 ms
popupPanel: 
  blocked: 45
  blockedDetails: 
    superfb.com: 6
    adform.net: 1
    admatic.com.tr: 3
    adpushup.com: 1
    adrecover.com: 1
    btloader.com: 1
    criteo.com: 1
    criteo.net: 1
    dimml.io: 1
    doubleclick.net: 1
    dugout.com: 2
    engageya.com: 2
    facebook.net: 2
    gemius.pl: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    hurriyet.com.tr: 1
    medyanetads.com: 1
    milliyet.com.tr: 2
    netmera-web.com: 2
    programattik.com: 3
    scorecardresearch.com: 1
    sporx.com: 1
    taboola.com: 1
    teads.tv: 4
    twitter.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
```
 removed: 
    ublock-filters: null
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    ublock-quick-fixes: null
```

Enable back these very important lists
