### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by mahade31** [uBlockOrigin/uAssets#14151]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=xKxh3fQwU8E&list=PLxCzCOWd7aiHGhOHV-nwb0HR5US5GFKFI&index=25`

### Category

ads

### Describe the issue

showing ads on youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79925
  cosmetic: 45026
  scriptlet: 17512
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68842-51, 8m
    easyprivacy: 27452-123, 8m
    plowe-0: 3641-779, 8m
    ublock-abuse: 76-0, 8m
    ublock-badware: 4209-92, 8m
    ublock-filters: 32295-115, 8m
    ublock-privacy: 225-3, 8m
    ublock-quick-fixes: 271-1, 8m
    ublock-unbreak: 1846-42, 8m
    urlhaus-1: 4980-0, 8m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8954 ms (selfie)
  maxAssetCacheWait: 569 ms
popupPanel: 
  blocked: 236
  blockedDetails: 
    youtube.com: 209
    doubleclick.net: 4
    google.com: 14
    google.com.bd: 1
    googlesyndication.com: 2
    googlevideo.com: 6
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by gorhill** [comment]
> `allReadyAfter: 8954 ms (selfie)`

Was the Youtube page opened at browser launch? uBO had to wait nearly 9s before being ready, so given you are using a Chromium-based browser, this might be a case of uBO not being ready before the Youtube page opened.

**Comment by mahade31** [comment]
Yes the tab was pre-opened when I launched the browser.
