### ISSUE TITLE
eksisozluk.com: [unknown]

### ISSUE THREAD

**Issue by tekinumut** [uBlockOrigin/uAssets#14152]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eksisozluk.com/`

### Category

[unknown]

### Describe the issue

The web page hangs on loading. This error started occurring a few days ago. The page starts working when I disable AdBlock. I think there is a redirect situation. If I enable Adblock, redirection from the loading screen to the main site is disabled.

### Screenshot(s)

Both URL is: https://eksisozluk.com/

It seems like they blocked the webpage with this loading screen.
![Screen Shot 2022-07-28 at 10 52 46](https://user-images.githubusercontent.com/33953921/181451926-d4db5211-2932-4b40-8b7a-6a12c265911a.png)

When I disable the AdBlock it's working as expected.
![Screen Shot 2022-07-28 at 10 54 32](https://user-images.githubusercontent.com/33953921/181452321-ec2d43a6-951f-4f78-9455-1997ae658e9f.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79829
  cosmetic: 44999
  scriptlet: 17508
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 68772-51, 3d.2h.32m
    easyprivacy: 27447-123, 3d.2h.31m
    plowe-0: 3645-779, 8d.5h
    ublock-abuse: 76-0, 9d.1h.8m
    ublock-badware: 4209-92, 3d.2h.30m
    ublock-filters: 32306-112, 3d.2h.29m
    ublock-privacy: 226-4, 9d.1h.7m
    ublock-quick-fixes: 262-1, 22h.23m
    ublock-unbreak: 1835-42, 3d.2h.28m
    urlhaus-1: 4926-0, 22h.22m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 131 ms (selfie)
  maxAssetCacheWait: 214 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
1. clear the cookies for this site
2. update uBO filters list
3. enable the regional list: TUR: AdGuard Turkish

**Comment by tekinumut** [comment]
Thank you it works as expected now. That was quite a quick response.
