### ISSUE TITLE
paytm - ads

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uAssets#14158]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://assetscdn1.paytm.com/`
this url loads ads such as

### Describe the issue

when i open paytm it loqds ads and other stuff and ads are some illegal stuff .

### Screenshot(s)

![Screenshot_20220729-122545~2](https://user-images.githubusercontent.com/108695843/181701344-217841f6-26be-424e-a472-749dda22cf47.png)

### uBlock Origin version

1.43.0

### Browser name and version

firefox

### Settings

none

### Notes

i have added that url my deny list in my personal dns filter and that solved the issue.

**Comment by krystian3w** [comment]
So this is ad reinsertion?

Also test on DNS without filler connections like https//one.one.one.one

**Comment by krystian3w** [comment]
In html that ad no have stable id/class/atributes, so may need block all subdomain or write working scriptlet.

**Comment by mapx-** [comment]
@holequantum what page did you visit to get those ads ?

**Comment by ghajini** [comment]
@holequantum 
you have not described the steps to reproduce ads, this is a payment site
i can't reproduce

**Comment by krystian3w** [comment]
On homepage is visible in enforced load mobile web page.

**Comment by krystian3w** [comment]
@DandelionSprout do you know something about paytm?

**Comment by krystian3w** [comment]
At mobile look safe this:

`#?#ul > li:-abp-has(img[src*="assets"][src*=".paytm.com"][src*=".jpg"])`

**Comment by holequantum** [comment]
> 

i am using pihole in my local network with 9.9.9.9 dns

**Comment by holequantum** [comment]
> @DandelionSprout do you know something about paytm?
yes it is a company.

**Comment by krystian3w** [comment]
Not that mean... (any "w gorącej wodzie company" [idiom - "kąpany" have similar pronounced to company]).

**Comment by holequantum** [comment]
> @holequantum you have not described the steps to reproduce ads, this is a payment site i can't reproduce signed in if i include `||assetscdn1.paytm.com^` will result in no payment/login ,all functionalities will be blocked
> 
> https://user-images.githubusercontent.com/20338483/181714902-bd38754d-96b3-4c87-81d1-66f4fd884afc.png https://user-images.githubusercontent.com/20338483/181715176-73a8392c-f43f-48c4-8f23-9da5af3ed5bc.png
> 
> so you need to be specific ,which are ads & give details about how to reproduce ads

yes actually right now i see that maybe that time it was cached hence i didn't face that but just ads blocked but now many stuff are get blocked result can't be logged in.

**Comment by krystian3w** [comment]
Maybe Indonesian-Malaysia List can cut, both support English page layout.

**Comment by mapx-** [comment]
@holequantum 

> you have not described the steps to reproduce ads

> what page did you visit to get those ads ? Do I need an account ?

Answer these questions.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14158#issuecomment-1199018305

**Comment by krystian3w** [comment]
He don't need - you omited

**Comment by krystian3w** [comment]
Ad is in mobile homepage

**Comment by mapx-** [comment]
I got that ad in desktop version, @krystian3w filter is ok

`paytm.com#?#ul > li:-abp-has(img[src*="assets"][src*=".paytm.com"][src*=".jpg"])`

report to easylist or whatever regional list
