### ISSUE TITLE
gplinks.co: breakage

### ISSUE THREAD

**Issue by shawon2901** [uBlockOrigin/uAssets#14159]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gplinks.co/xJIenIgn`

### Category

breakage

### Describe the issue

Clicking On Continue Button Keeps Refreshing The Page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 105
filterset (summary): 
  network: 81143
  cosmetic: 26703
  scriptlet: 17519
  html: 713
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33050-298, 2d.20h.23m
    ublock-badware: 4212-0, 2d.20h.23m
    ublock-privacy: 241-1, 2d.20h.23m
    ublock-abuse: 76-0, 2d.20h.23m
    ublock-unbreak: 1853-0, 2d.20h.23m
    ublock-quick-fixes: 277-0, 6h.41m
    adguard-mobile: 7987-167, 2d.20h.23m
    easylist: 68815-25066, 2d.20h.23m
    easyprivacy: 27449-590, 2d.20h.23m
    urlhaus-1: 4772-0, 6h.40m
    plowe-0: 3641-3, 2d.20h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 306 ms (selfie)
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Probably a mobile only issue, it works fine on my end using a desktop browser.

**Comment by mapx-** [comment]
@shawon2901 test these filters:

```
@@||cdn.biddercore.io/tagman/Purify/sites/mynewsmedia.co/index.js$script,domain=mynewsmedia.co
@@||m2d.m2.ai/pg.mynewsmedia.js$script,domain=mynewsmedia.co
```

**Comment by krystian3w** [comment]
No works on PC too with Firefox with In Private window/session.

**Comment by mapx-** [comment]
it seems to be firefox specific desktop / mobile => site issue

**Comment by hKQwHW** [comment]
Can reproduce on Firefox Desktop on Windows 11 with every extension other than uBlock turned off. It seems to work with uBlock off.

Either way though, this site has a lot of intrusive/deceptive ads and other weird things. Unless this is happening on other sites, I see no problem with this site & associated shady sites not working.

**Comment by shawon2901** [comment]
> @shawon2901 test these filters:
> 
> ```
> @@||cdn.biddercore.io/tagman/Purify/sites/mynewsmedia.co/index.js$script,domain=mynewsmedia.co
> @@||m2d.m2.ai/pg.mynewsmedia.js$script,domain=mynewsmedia.co
> ```

Doesn't Seem To Work...Same Reload Happening

I Did My Filters>Added>Enabled My Filters

**Comment by shawon2901** [comment]
> @shawon2901 test these filters:
> 
> ```
> @@||cdn.biddercore.io/tagman/Purify/sites/mynewsmedia.co/index.js$script,domain=mynewsmedia.co
> @@||m2d.m2.ai/pg.mynewsmedia.js$script,domain=mynewsmedia.co
> ```

Tested With Kiwi Browser These Filters Do Fix The Problem..But Doesn't Work On FireFox Android So It Was FireFox Android Problem

**Comment by krystian3w** [comment]
So fixed on PC Firefox 103+ (and macOS)?

**Comment by shawon2901** [comment]
> So fixed on PC Firefox 103+ (and macOS)?

I Dont Have A PC..I Tried On Android..The Admins Here Said That It Was. already Working In PC & It Was A Mobile Issue
