### ISSUE TITLE
bricomart.es: breakage

### ISSUE THREAD

**Issue by frbuceta** [uBlockOrigin/uAssets#14156]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bricomart.es/`

### Category

breakage

### Describe the issue

The web page search cannot be used when UBlock is activated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura desde 2022-07-28 23-22-59](https://user-images.githubusercontent.com/13822438/181640065-d244f013-19ea-4d4f-a310-993f31ec935e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82842
  cosmetic: 49862
  scriptlet: 17741
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68815-51, 2d.7h.27m
    easyprivacy: 27449-123, 2d.7h.26m
    plowe-0: 3645-779, 8d.1m
    spa-0: 3902-36, 52m
    spa-1: 4568-172, 2d.7h.35m
    ublock-abuse: 76-0, 10d.21h.4m
    ublock-badware: 4209-92, 2d.7h.6m
    ublock-filters: 32292-167, 2d.7h.5m
    ublock-privacy: 226-3, 10d.21h.3m
    ublock-quick-fixes: 280-1, 50m
    ublock-unbreak: 1836-44, 1d.9h.28m
    urlhaus-1: 4788-0, 51m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 262 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    datadome.co: 1
    geoip-js.com: 1
    googletagmanager.com: 1
    sensefuel.live: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||tag.search.sensefuel.live/tag/$script,domain=bricomart.es`

@ryanbr

**Comment by mapx-** [comment]
test 

`@@||geoip-js.com^$domain=bricomart.es`

@ryanbr
