### ISSUE TITLE
mundodonghua.com: detection

### ISSUE THREAD

**Issue by v0lt3r** [uBlockOrigin/uAssets#14155]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mundodonghua.com/donghua/quan-zhi-gao-shou`

### Category

detection

### Describe the issue

i think would happen on all webpage, any series link obviously, its crazy but i tried even greasemoney (only after be sure it happens with ublock only) with filters (anti-adblock-killer-filters) for ads and nothing.... 

With ublock too, SOMETIMES doesn't appear the "adblock detection panel, not allowed on this site" but others it does...
Javascript disable fix it ofc, but its not a solution since i can't watch videos, and i'd like to be solved.

I don't know why sometimes if the code its the same always... Anyway id be very grateful if you look it and add it to whitelist, since surely, its a very easy thing to modify i guess.

Best regards and thank you for your work

### Screenshot(s)

![imagen](https://user-images.githubusercontent.com/6199099/181636322-44f8d229-897b-42e8-a7d8-ad5d18e6ca33.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82978
  cosmetic: 49855
  scriptlet: 17701
  html: 710
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 23h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32941-36, 3d.3h.9m
    ublock-badware: 4213-1, 3d.3h.14m
    ublock-privacy: 240-0, 4d.4h.55m
    ublock-abuse: 76-0, 4d.4h.54m
    ublock-unbreak: 1848-0, 3d.3h.13m
    easylist: 68792-658, 3d.3h.12m
    easyprivacy: 27449-610, 3d.3h.11m
    urlhaus-1: 4948-0, 23h.8m
    plowe-0: 3644-3, 13d.1h.14m
    spa-0: 3902-20, 23h.10m
    spa-1: 4568-141, 3d.3h.10m
    ublock-quick-fixes: 268-1, 23h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 138 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    disqus.com: 4
    googlesyndication.com: 1
    googletagmanager.com: 1
    viglink.com: 2
```
</details>

**Comment by mapx-** [comment]
No anti adb on my end, already fixed by `spa, por: AdGuard Spanish/Portuguese` list 

- update all your filter lists
- disable greasemonkey (the AAK list is very old and could trigger various issues)

**Comment by v0lt3r** [comment]
I dont know why it happens to me sometimes then, im gonna do what you said, disable greasemoney, and about update the lists, how i do that?? 

Just out of curiosity i was looking is this the javascript file that trigger it? or have nothing to do with it. And would be for the ad that i show or its another? i just looked with inspector

var _0xdefd=["\x75\x6E\x64\x65\x66\x69\x6E\x65\x64","\x69\x6E\x69\x74","\x66\x61\x64\x65\x4F\x75\x74","\x64\x65\x6C\x61\x79","\x2E\x70\x61\x67\x65\x2D\x70\x72\x65\x6C\x6F\x61\x64\x65\x72","\x2F\x61\x6A\x61\x78\x5F\x61\x70\x70\x6C\x79\x5F\x76\x69\x65\x77\x2E\x70\x68\x70","\x70\x6F\x73\x74","\x76\x61\x6C\x75\x65","\x63\x75\x72\x72\x65\x6E\x74\x54\x61\x72\x67\x65\x74","\x68\x72\x65\x66","\x2F\x62\x75\x73\x71\x75\x65\x64\x61\x73\x2F","\x73\x75\x62\x6D\x69\x74","\x2E\x73\x65\x61\x72\x63\x68\x2D\x66\x6F\x72\x6D","\x6D\x6F\x75\x73\x65\x64\x6F\x77\x6E","\x77\x68\x69\x63\x68","\x2F\x61\x6A\x61\x78\x5F\x61\x70\x70\x6C\x79\x5F\x64\x6F\x77\x6E\x6C\x6F\x61\x64\x2E\x70\x68\x70","\x69\x64","\x61\x74\x74\x72","\x6F\x6E","\x61\x2E\x64\x77\x6C\x64","\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4A\x4B\x4C\x4D\x4E\x4F\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5A\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6A\x6B\x6C\x6D\x6E\x6F\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7A\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x2B\x2F\x3D","","\x72\x65\x70\x6C\x61\x63\x65","\x63\x68\x61\x72\x41\x74","\x69\x6E\x64\x65\x78\x4F\x66","\x66\x72\x6F\x6D\x43\x68\x61\x72\x43\x6F\x64\x65","\x6C\x65\x6E\x67\x74\x68","\x63\x68\x61\x72\x43\x6F\x64\x65\x41\x74","\x58\x63\x56\x43\x43\x57","\x67\x65\x74\x45\x6C\x65\x6D\x65\x6E\x74\x42\x79\x49\x64","\x6F\x66\x66\x73\x65\x74\x48\x65\x69\x67\x68\x74","\x64\x69\x73\x70\x6C\x61\x79","\x73\x74\x79\x6C\x65","\x6C\x69\x67\x68\x74","\x62\x6C\x6F\x63\x6B","\x66\x61\x64\x65","\x6F\x76\x65\x72\x66\x6C\x6F\x77","\x64\x6F\x63\x75\x6D\x65\x6E\x74\x45\x6C\x65\x6D\x65\x6E\x74","\x68\x69\x64\x64\x65\x6E","\x73\x63\x72\x6F\x6C\x6C","\x62\x6F\x64\x79","\x6E\x6F","\x73\x63\x72\x6F\x6C\x6C\x54\x6F","\x3A\x76\x69\x73\x69\x62\x6C\x65","\x69\x73","\x2E\x61\x64\x73\x62\x79\x67\x6F\x6F\x67\x6C\x65"];if(typeof youplay!==_0xdefd[0]){youplay[_0xdefd[1]]({parallax:true,navbarSmall:false,fadeBetweenPages:true})};$(_0xdefd[4])[_0xdefd[3]](50)[_0xdefd[2]](200);function ApplyView(_0x833ax2){$[_0xdefd[6]](_0xdefd[5],{id_ep:_0x833ax2})}$(_0xdefd[12])[_0xdefd[11]](function(_0x833ax3){var _0x833ax4=_0x833ax3[_0xdefd[8]][0][_0xdefd[7]];location[_0xdefd[9]]=_0xdefd[10]+_0x833ax4;return false});$(_0xdefd[19])[_0xdefd[18]](_0xdefd[13],function(_0x833ax5){if(_0x833ax5[_0xdefd[14]]<=2){$[_0xdefd[6]](_0xdefd[15],{id_ep:$(this)[_0xdefd[17]](_0xdefd[16])})}});function _x75x6c(_0x833ax7){var _0x833ax8=_0xdefd[20];var _0x833ax9=_0xdefd[21];var _0x833axa,_0x833axb,_0x833axc;var _0x833axd,_0x833axe,_0x833axf,_0x833ax10;var _0x833ax11=0;_0x833ax7=_0x833ax7[_0xdefd[22]](/[^A-Za-z0-9\+\/\=]/g,_0xdefd[21]);while(_0x833ax11<_0x833ax7[_0xdefd[26]]){_0x833axd=_0x833ax8[_0xdefd[24]](_0x833ax7[_0xdefd[23]](_0x833ax11++));_0x833axe=_0x833ax8[_0xdefd[24]](_0x833ax7[_0xdefd[23]](_0x833ax11++));_0x833axf=_0x833ax8[_0xdefd[24]](_0x833ax7[_0xdefd[23]](_0x833ax11++));_0x833ax10=_0x833ax8[_0xdefd[24]](_0x833ax7[_0xdefd[23]](_0x833ax11++));_0x833axa=(_0x833axd<<2)|(_0x833axe>>4);_0x833axb=((_0x833axe&15)<<4)|(_0x833axf>>2);_0x833axc=((_0x833axf&3)<<6)|_0x833ax10;_0x833ax9=_0x833ax9+String[_0xdefd[25]](_0x833axa);if(_0x833axf!=64){_0x833ax9=_0x833ax9+String[_0xdefd[25]](_0x833axb)};if(_0x833ax10!=64){_0x833ax9=_0x833ax9+String[_0xdefd[25]](_0x833axc)}};_0x833ax9=utf8_decode(_0x833ax9);return _0x833ax9}function utf8_decode(_0x833ax13){var _0x833ax14=_0xdefd[21];var _0x833ax11=0;var _0x833ax15=c1=c2=0;while(_0x833ax11<_0x833ax13[_0xdefd[26]]){_0x833ax15=_0x833ax13[_0xdefd[27]](_0x833ax11);if(_0x833ax15<128){_0x833ax14+=String[_0xdefd[25]](_0x833ax15);_0x833ax11++}else{if((_0x833ax15>191)&&(_0x833ax15<224)){c2=_0x833ax13[_0xdefd[27]](_0x833ax11+1);_0x833ax14+=String[_0xdefd[25]](((_0x833ax15&31)<<6)|(c2&63));_0x833ax11+=2}else{c2=_0x833ax13[_0xdefd[27]](_0x833ax11+1);c3=_0x833ax13[_0xdefd[27]](_0x833ax11+2);_0x833ax14+=String[_0xdefd[25]](((_0x833ax15&15)<<12)|((c2&63)<<6)|(c3&63));_0x833ax11+=3}}};return _0x833ax14}var ejecutado=0;function Tamamo_Blocker(){if(ejecutado==0){var _0x833ax18=document[_0xdefd[29]](_0xdefd[28]);if(_0x833ax18==null||_0x833ax18[_0xdefd[30]]<=0||typeof(_0x833ax18)==_0xdefd[0]){document[_0xdefd[29]](_0xdefd[33])[_0xdefd[32]][_0xdefd[31]]=_0xdefd[34];document[_0xdefd[29]](_0xdefd[35])[_0xdefd[32]][_0xdefd[31]]=_0xdefd[34];document[_0xdefd[37]][_0xdefd[32]][_0xdefd[36]]=_0xdefd[38];document[_0xdefd[40]][_0xdefd[39]]=_0xdefd[41];window[_0xdefd[42]](0,0)};ejecutado=1}}function aadb_recheck(){if(!$(_0xdefd[45])[_0xdefd[44]](_0xdefd[43])){document[_0xdefd[29]](_0xdefd[33])[_0xdefd[32]][_0xdefd[31]]=_0xdefd[34];document[_0xdefd[29]](_0xdefd[35])[_0xdefd[32]][_0xdefd[31]]=_0xdefd[34];document[_0xdefd[37]][_0xdefd[32]][_0xdefd[36]]=_0xdefd[38];document[_0xdefd[40]][_0xdefd[39]]=_0xdefd[41];window[_0xdefd[42]](0,0)}}setTimeout(function(){Tamamo_Blocker()},1000);setTimeout(function(){aadb_recheck()},1000)
document.addEventListener('DOMContentLoaded',init,false);function init(){if(window.loadingAds===undefined){Tamamo_Blocker();}else{console.log(`%c 　　　　　　 /:.:.:/:.:.{　　 　 |:.:.:.∨:.:.:.＼　　　,,,,;;;;;;;;;;;/
.＿　　　　/:r､:.}:.:.:.ﾊ.　　　|:.:.:.:.:∨f" i,:.Y,;;;;;;;;;;;;;;;;;;〈
ヽ;;;;;;;;,,,,,,ｬｰ'　}:.:.:.:.:ﾊ　　 i|:.:.:.:.:.:.ﾊ　　 "''ﾑ;;;;;;;;;;;;;;;;}
　 ＼;;_ -‐ ,"; {:.:.:.:.:.:.ﾊ　　}:.:.:.:.:.:.:.:ﾊ";:", 　　 /;;;く
　　 /;;;;;ｧ　';　 {:.:.:.:...: ::¨¨v∠::::::....､:ヽ,;'　,;',　ｚ;;;;_}
　　 ヽ,,,,,　,';'　 }／;:/::::::;:ヽ:::::::::､::､::＼},;　　 ,,; ＞_
　　　 }∠　 ,;',/:::/; ::::::/:::::::::::}::i::ヽ＼:::ヽ 　f=:i:i:i:i:i:i＞､__
　　　_＞ｆ　, /::://::::::/;:::::::::::;:{:::;::::::::::ヽ:::ﾊi:i:i:i:i:i:i:i:i:i:i:i:i:i:i:ﾊ
. x＜:i:i:i:i:i:i:7:::/ | ::::::|::|:::::::::::;:|:::}l};::::}::::::::::::∨i:i:i:i:i:i:i:i:i:i:i:i:i/
:i:i:i:i:i:i:i:／:/::::′| ::::::|::{i ::::::::|:|:::{_:|:::ﾄ､::::::::::::∨:i:i:i:i:i:i:i:i:i:i:{
_:i:i:i:i:ノ:i:ｉ/:::/:::::ｉ|::::::::!::|{:::::::::|:'::j 八ﾉｫｔ::´::::::::::ﾊ:i:i:ヽ:i:i:i:i:i:)
_）／-:／ｨ:::}:::::::i|::::::人ﾊ::::;:/}:/　ｨｖじi}ﾘ:;:::::;::::{::ﾊ:i:i:i:＼:/
ヽ:i:i:}:i／:::::ﾉｫﾄ､i}:r:ﾑ. ==ﾐ　　　　　¨´ }:::＼{＼{::ﾊ:i:i:人{
　 .／::::::;:´:::ミ}､ヽﾐ=　　　　　 ,　 　 　/:::|::}:＼ }::::Ⅳ::::::::ﾊ
／:/::::::/::::/ハ {､＼ヽ＼　　 r=＝ｧ　 { :::ﾘ:|::::ﾘ }::::|}:::::::::::, ＼_,
::::/::::::/::::〃　入'ヽ '　　＼_　ー '　イ|:::::|:ｉ|ﾊ:{::ぃ::∨:::::::::l
_/::::::/::://　 ﾉｲ:＼ヽ　　　　 ﾐ¨: :::＞j}:::::|:ﾘ　}:ヽ:.,::::i.}::::::::ﾄ､
::::::::/:::/ {　〃 }:::|i. ＼＼, _.　　}三三1} :ﾘ;'￣}::ﾄ:::ﾊ:::{:::::::ﾘハ
::／,:::/　|i { /|1:::|i　 |i7　　}　　ｉ彡三ii|:/;' ／::／} .入＼:::{
　 }::/ 　.ﾊ }j {ﾊ:::}.}　Ｖ　　 |　　 r三iiiУ'ｉ/ｨ:/ 　 |/:::::＼:ミ_,
　 ﾚ　　八V　} .ヽ 　/　　/i}　　 }三 //ﾊ　{　　 /}::::::::/|ヽ:|
　 {　　　　 }　　r　Ｖ　　 {ii-}　　iﾚ´ {i' { .| ′　 { |;:::::/.ｉ|:::::|
　ｒ‐ﾆﾆ=ミ-- v　 /　　　}　,|　 　{ 　{　 .ﾉ　　　八ｉ}:/　ﾘ :::j
　∨//////≧ｰ/　　　 i_＞} 　　ﾋﾆミﾑ--=ｰ∧=={=,/ノ:/
　　Ｙ´ｘ＜イ¨77　　　／／ii|　　 ∨//＞)////////ヽ）
　／ く //////　　 く </// | 　 　 ｝＞x彳￣' 　 ＜ 〈_`,"font-family:'MS PGothic'; font-size:12pt; color:blue;");console.log('Mikoon~');}}

**Comment by v0lt3r** [comment]
Okay now im seeing about that tamamo_blocker() that triggers that file that its in the file you say of portuguese spanish..

That means that its included into ublocker already?

seriesdonghua.com,mundodonghua.com#%#//scriptlet("prevent-setTimeout", "/Tamamo_Blocker|aadb_recheck/")
@@||seriesdonghua.com/*banner.gif
@@||mundodonghua.com/*banner.gif
@@||mundodonghua.com/js/adsbygoogle.js
seriesdonghua.com,mundodonghua.com#%#//scriptlet("set-constant", "loadingAds", "true")

**Comment by v0lt3r** [comment]
I did all you said, update and disable the greasemoney and the old filter. And trying again, if appears again then ill post it here with another screenshot ok?

**Comment by mapx-** [comment]
- just report back, no screenshot is necessary in this case.
- be sure no other blocking addon is enabled
