### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Sadian23** [uBlockOrigin/uAssets#14157]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=zOHzvvTroXQ`

### Category

ads

### Describe the issue

On every youtube video a white box appears, what I assume is a leftover of  an add, even if I create custom filters the same white add keeps popping on the video player and I need to manually create the filter every time it pops which eventually leads to the add appearing again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="943" alt="image" src="https://user-images.githubusercontent.com/62084884/181652856-cf6c8891-d142-4494-9563-bcac64b4091e.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82834
  cosmetic: 49857
  scriptlet: 17732
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68815-51, 2d.4h.32m
    easyprivacy: 27449-123, 2d.4h.31m
    plowe-0: 3641-779, 2d.4h.30m
    spa-0: 3902-36, 54m
    spa-1: 4568-172, 2d.4h.35m
    ublock-abuse: 76-0, 2d.4h.28m
    ublock-badware: 4209-92, 2d.4h.26m
    ublock-filters: 32292-167, 2d.4h.25m
    ublock-privacy: 225-3, 2d.4h.24m
    ublock-quick-fixes: 262-1, 53m
    ublock-unbreak: 1836-44, 2d.4h.22m
    urlhaus-1: 4788-0, 52m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 406 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    youtube.com: 13
    doubleclick.net: 2
    google.com: 3
    google.com.ar: 1
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by krystian3w** [comment]
Try disable NoScript and all other addons like "VNP" (I mean blue shield is VPN based on proxy in browser).


Also you can share your fails saved  by element picker - then we can boost filter to cover element after refresh if have something stable and newbie don't see this.

**Comment by krystian3w** [comment]
All = all = #7636

**Comment by Sadian23** [comment]
> Try disable NoScript and all other addons like "VPN" (I mean blue shield is VPN based on proxy in browser).
> 
> Also you can share your fails saved by element picker - then we can boost filter to cover element after refresh if have something stable and newbie don't see this.

all plugins disabled the issue persists :( 

the block changes name every time it appears, and when deleting it with the element deletion tool it doesnt create a new filter

**Comment by krystian3w** [comment]
Don't use zapper, he delete elemtent and normal is back after refresh.

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/wiki/Element-picker
