### ISSUE TITLE
cbsnews.com - PLS Cancel fixed since I posted on another board

### ISSUE THREAD

**Issue by enduser1** [uBlockOrigin/uAssets#1415]
URL(s) where the issue occurs
`https://www.cbsnews.com/news/millennium-tower-san-francisco-leaning-tower-of-lawsuits-1/ `

Describe the issue:
Videos will not play with UBO default filters.

Versions
Running FF v58, UBO v1.14.24 with all updated default filters. W7 x64
- Browser/version: [Firefox V58.0.1 x64]
- uBlock Origin version: [1.14.24]

Settings
- Running all UBO default filters, no custom filters running

### Notes
Problem traced to Peter Lowe’s Ad and tracking server list.
If disabled video plays correctly as intended.

**Comment by mapx-** [comment]
just update unbreak list
