### ISSUE TITLE
oneasurecta.evolutionpayroll.com: breakage

### ISSUE THREAD

**Issue by Olderogt** [uBlockOrigin/uAssets#14163]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://oneasurecta.evolutionpayroll.com/ess`
`https://oneasurecta.evolutionpayroll.com/ess#/login`

### Category

breakage, not loading

### Describe the issue

The website is not loading correctly and hangs at a loading screen until whitelisted. 
Thank you for your help!!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/110250527/181802273-faf4b8ca-057d-4af8-a876-d8ed91a43bde.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79771
  cosmetic: 45010
  scriptlet: 17518
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68820-51, 2d.10h.11m
    easyprivacy: 27450-123, 2d.10h.10m
    plowe-0: 3640-779, 6d.12h.21m
    ublock-abuse: 76-0, 9d.20h.16m
    ublock-badware: 4209-92, 2d.10h.9m
    ublock-filters: 32286-114, 2d.10h.8m
    ublock-privacy: 226-4, 9d.20h.15m
    ublock-quick-fixes: 291-1, 2h.36m
    ublock-unbreak: 1836-42, 2d.10h.7m
    urlhaus-1: 4839-0, 2h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 509 ms (selfie)
  maxAssetCacheWait: 174 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||oneasurecta.evolutionpayroll.com/*/angularytics/$script,1p`

@ryanbr
