### ISSUE TITLE
bestiefy.com: privacy

### ISSUE THREAD

**Issue by hKQwHW** [uBlockOrigin/uAssets#14166]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bestiefy.com/q?=iYVlb`

### Category

privacy

### Describe the issue

Sort of continuing from #14150. https://fingerprinter-production.herokuapp.com should be blocked, as it appears to send a unique ID in `https://fingerprinter-production.herokuapp.com/visitors/(string of lowercase letters and numbers)/audience_segments` and return various "audience segments". I found this on Bestiefy, but I am unsure if it also exists on other sites or not. It appears to be referenced by that same `tyche` script that I mentioned earlier.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 81541
  cosmetic: 79304
  scriptlet: 19064
  html: 713
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 1d.6h.38m
    fanboy-cookiemonster: 37577-85, 1d.6h.38m
  default: 
    user-filters: 4-0, never
    ublock-filters: 32980-62, 1d.6h.38m
    ublock-badware: 4215-0, 1d.6h.38m
    ublock-privacy: 242-0, 1d.6h.38m
    ublock-abuse: 76-0, 1d.6h.38m
    ublock-unbreak: 1864-0, 1d.6h.38m
    ublock-quick-fixes: 268-1, 6h.13m
    easylist: 68890-599, 1d.6h.38m
    easyprivacy: 27456-580, 1d.6h.38m
    urlhaus-1: 4839-0, 6h.12m
    plowe-0: 3642-3, 1d.6h.38m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 242 ms (selfie)
  maxAssetCacheWait: 141 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    agkn.com: 1
    amazon-adsystem.com: 1
    crwdcntrl.net: 1
    doubleclick.net: 1
    googletagmanager.com: 2
    id5-sync.com: 1
    moatads.com: 2
```
</details>

**Comment by hKQwHW** [comment]
Wait, sorry, I just checked the valid issue list and I think I should submit this to EasyList or EasyPrivacy.

**Comment by hKQwHW** [comment]
Sorry, but I'm not sure how to send this to EasyList or EasyPrivacy. I will re-open for now until I have further instructions.

**Comment by ryanbr** [comment]
Not seen.

**Comment by hKQwHW** [comment]
Hmm? I do see it.
