### ISSUE TITLE
herafertility.co: [breakage]

### ISSUE THREAD

**Issue by tparamso** [uBlockOrigin/uAssets#14165]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://herafertility.co/get-started-2`

### Category

[breakage]

### Describe the issue

Have an embedded form on the page. The page is a credible form for someone to complete lending

<div id="personal-loan-embedded-prequal"> </div>
<script>
var script = document.createElement('script');
script.type = "text/javascript";
script.addEventListener("load", function(event) {
 CredibleSDK.initWidget('#personal-loan-embedded-prequal', {
 environment: 'production',
 product: {
 marketplace: 'personal-loan',
 type: 'embedded-prequal',
 },
 ui: {
 theme: 'default',
 banner: 'false'
 },
 analytics: {
 source: 'herafertility',
 },
 })
});
script.src = "https://sdk.credible.com/sdk.js";
document.getElementsByTagName('head')[0].appendChild(script);
</script>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79722
  cosmetic: 45025
  scriptlet: 17516
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 16h.37m
  default: 
    user-filters: 0-0, never
    easylist: 68839-51, 1d.18h.1m
    easyprivacy: 27450-123, 1d.18h
    plowe-0: 3645-779, 11d.4h.51m
    ublock-abuse: 76-0, 11d.4h.50m
    ublock-badware: 4209-92, 1d.17h.57m
    ublock-filters: 32288-115, 1d.17h.58m
    ublock-privacy: 226-3, 11d.4h.49m
    ublock-quick-fixes: 280-1, 16h.2m
    ublock-unbreak: 1836-42, 1d.17h.59m
    urlhaus-1: 4788-0, 16h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2046 ms (selfie)
  maxAssetCacheWait: 310 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    credible.com: 1
    facebook.net: 1
    googleoptimize.com: 1
    googletagmanager.com: 2
    hotjar.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||sdk.credible.com/sdk.js$script,domain=herafertility.co`

@ryanbr 

why this filter ?
`||credible.com/sdk.js$3p`

**Comment by krystian3w** [comment]
This can be floating load widget picked to corner of screen.

**Comment by tparamso** [comment]
Looks like issue is resolved once I updated the list on unlock origin. Thanks!
