### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by vhgjbkl** [uBlockOrigin/uAssets#14164]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=psEKsOGfM1U&list=PLv4dE0B-k0WjLyEfBg22_9qvImGqfcR1_&index=4&t=1406s`

### Category

ads

### Describe the issue

shows video ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79698
  cosmetic: 45020
  scriptlet: 17513
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 2d.16h.16m
  default: 
    user-filters: 1-0, never
    easylist: 68838-51, 1d.19h.33m
    easyprivacy: 27450-123, 1d.19h.34m
    plowe-0: 3640-779, 5d.16h.55m
    ublock-abuse: 76-0, 5d.16h.58m
    ublock-badware: 4209-92, 2d.16h.19m
    ublock-filters: 32279-115, 2d.16h.18m
    ublock-privacy: 225-3, 5d.16h.57m
    ublock-quick-fixes: 280-1, 9m
    ublock-unbreak: 1836-42, 2d.16h.17m
    urlhaus-1: 4771-0, 10m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11662 ms (selfie)
  maxAssetCacheWait: 360 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    youtube.com: 17
    doubleclick.net: 2
    google.com: 5
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
