### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by kunzajap** [uBlockOrigin/uAssets#14162]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/intl/en-GB/account/about/privacy-tools/`

### Category

breakage

### Describe the issue

Ad setting and Ad personalization pages does not open when EasyList/uBo filters is active.
This issue is caused by EasyList and uBlock filters.
Please see the video
https://gofile.io/d/an7FMk

### Screenshot(s)

`https://myaccount.google.com/intro/yourdata/search`

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/109770855/181783430-a9619247-247f-4dd2-8456-d03a2394bf56.png)

</details>

`https://www.google.com/intl/en-GB/account/about/privacy-tools/`

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/109770855/181783486-7b5d2d98-898c-4ada-a8f9-3cc37f2358fd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 95492
  cosmetic: 147520
  scriptlet: 33415
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    adguard-annoyance: 55380-75, 1h.7m
    adguard-generic: 66318-703, 30m
    adguard-social: 18024-864, 1h.7m
    adguard-spyware: 27470-1063, 1h.7m
    adguard-spyware-url: 683-0, 1h.7m
  default: 
    user-filters: 59-0, never
    TUR-0: 8713-66, 1h.7m
    easylist: 68901-921, now
    ublock-abuse: 76-0, now
    ublock-badware: 4211-321, now
    ublock-filters: 32336-3824, now
    ublock-privacy: 226-42, now
    ublock-quick-fixes: 291-29, now
    ublock-unbreak: 1851-94, now
filterset (user): [array of 61 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 912 ms (selfie)
  maxAssetCacheWait: 1081 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 2
    google-analytics.com: 1
```
</details>

**Comment by ghajini** [comment]
you need to sign in when trying to use those features...sign in & use that feature ,you will not encounter a block

when not signed in ,it goes through `||doubleclick.net^` adserver which is blocked by EL & peter lowe's list...

**Comment by kunzajap** [comment]
Thanks for your help
This issue does not occur with AdGuard even if you are not signed in to Google. So the pages I mentioned are displayed with AdGuard.

**Comment by korAPUcard** [comment]
Same here. In my case, uBlock Origin is blocked my google preferences cookies so I can't use my all settings in google services.
