### ISSUE TITLE
uktvplay.uktv.co.uk: ads

### ISSUE THREAD

**Issue by subhumanfreak** [uBlockOrigin/uAssets#14168]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uktvplay.uktv.co.uk/shows/whose-line-is-it-anyway-usa/watch-online/6283856423001`

### Category

ads

### Describe the issue

Ads used to be blocked perfectly and seamlessly until today (or within the past few days), but are now present.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79780
  cosmetic: 45082
  scriptlet: 17527
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 68901-51, 4m
    easyprivacy: 27458-123, 4m
    plowe-0: 3638-777, 4m
    ublock-abuse: 76-0, 4m
    ublock-badware: 4221-92, 4m
    ublock-filters: 32342-114, 4m
    ublock-privacy: 226-3, 4m
    ublock-quick-fixes: 291-19, 4m
    ublock-unbreak: 1851-42, 4m
    urlhaus-1: 4771-0, 4m
filterset (user): [array of 3 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 444 ms (selfie)
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    2cnt.net: 2
    aticdn.net: 1
    brightcove.com: 7
    fwmrm.net: 3
    google-analytics.com: 1
    googletagmanager.com: 1
    s3-eu-west-1.amazonaws.com: 6
    sentry.io: 2
    thefilter.com: 1
    uktvapi.co.uk: 4
    uptime.com: 1
```
</details>

**Comment by MasterKia** [comment]
I get:
>Ad Blocker Detected 
Please remove or disable your ad blocking software to view this content.

But maybe that's just because Digital Restrictions Management (DRM) is disabled on my Firefox.

**Comment by subhumanfreak** [comment]
I can confirm I get the desired effect on Firefox (fresh install). Would still prefer Chrome though.

The "Ad Blocker Detected" message you get is what I would see if I didn't have uBlock switched on (or used another ad-blocker, which was what prompted me to try uBlock in the first place). Might be because of the DRM in your case.

**Comment by ghajini** [comment]
i get only preroll ad with default settings
`||cdn.http.anno.channel4.com/m/1/$media,domain=uktvplay.uktv.co.uk`
works for me
confirm the same

**Comment by ghajini** [comment]
update your filter lists & if still ad, report back here only
