### ISSUE TITLE
imdb & 'uBlock Filters' list

### ISSUE THREAD

**Issue by hoshsadiq** [uBlockOrigin/uAssets#1416]
### URL(s) where the issue occurs

`http://www.imdb.com/title/tt1825683/`

### Describe the issue

Broken

### Screenshot(s)

![image](https://user-images.githubusercontent.com/600045/35594615-bb665bf0-060b-11e8-8e80-7167ad5c5a12.png)

When disabled
![image](https://user-images.githubusercontent.com/600045/35594732-1072df74-060c-11e8-9af2-ad8d4fb0a321.png)

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: 1.14.24

### Settings

N/A

### Notes

#687 seems to be back. Can't seem to identify what the exact filter is, but disable `uBlock Filters` list fixes it.

**Comment by mapx-** [comment]
Are you using some userscript ? I have another design in imdb
![imdb](https://user-images.githubusercontent.com/10303732/35649817-7b299884-06da-11e8-8205-cd2d257e47e2.PNG)

**Comment by hoshsadiq** [comment]
Indeed it has changed now. I've just got Anti-Adblock Killer as a userscript. Anyway, I disabled all chrome addons that may interfere including uMatrix, Tampermonkey and Stylus. And it's still the same. I've figured out which filter breaks it though:

```
imdb.com###injected_navstrip_wrapper
```

Added in #740

**Comment by mapx-** [comment]
so, if you add
`imdb.com#@##injected_navstrip_wrapper`
does it fix your issue ?

**Comment by hoshsadiq** [comment]
Yup, that fixes it (I was trying to figure out how to disable one specific filter earlier).

**Comment by okiehsch** [comment]
`imdb.com###injected_navstrip_wrapper` fixes the "spiderman" background ads of  https://github.com/uBlockOrigin/uAssets/issues/740 on my end.

**Comment by mapx-** [comment]
@okiehsch  can you reproduce this issue ?

**Comment by okiehsch** [comment]
No, I get your screenshot without all the background stuff.

**Comment by mapx-** [comment]
well, could be imdb uses more different versions ?!
@hoshsadiq  just use it as custom filter ..

**Comment by okiehsch** [comment]
It probably depends on your geo-location.

**Comment by hoshsadiq** [comment]
Sure no problem. I'll add it as a custom filter!
