### ISSUE TITLE
dnt.abine.com: breakage

### ISSUE THREAD

**Issue by a80b8829** [uBlockOrigin/uAssets#14169]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dnt.abine.com/`

### Category

breakage

### Describe the issue

Refuses to login after entering valid authentication code.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 113973
  cosmetic: 134456
  scriptlet: 24925
  html: 737
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-217, 3h.2m
    adguard-annoyance: 55299-4730, 3d.2h.15m
    adguard-social: 17996-1651, 3d.2h.14m
    fanboy-thirdparty_social: 69-1, 3d.23h.1m
    fanboy-annoyance: 76309-64704, 3d.23h
    fanboy-cookiemonster: 37284-16279, 3d.10h.21m
    fanboy-social: 23236-13669, 3d.2h.13m
    ublock-annoyances: 4531-8, 3d.2h.12m
    CHN-0: 28864-1300, 3d.2h.11m
    NOR-0: 3034-179, 3h
    SWE-1: 4065-291, 3d.2h.10m
  default: 
    user-filters: 43-1, never
    ublock-filters: 33046-334, 3d.22h.59m
    ublock-badware: 4212-0, 3d.22h.58m
    ublock-privacy: 242-1, 1d.9h.24m
    ublock-abuse: 76-0, 1d.9h.23m
    ublock-unbreak: 1853-1, 3d.22h.57m
    adguard-mobile: 7984-167, 3d.22h.56m
    easylist: 68815-25275, 3d.2h.17m
    easyprivacy: 27449-600, 3d.2h.16m
    urlhaus-1: 4839-0, 3h.1m
    plowe-0: 3638-3, 7h.3m
    ublock-quick-fixes: 277-1, 2h.59m
filterset (user): [array of 63 redacted]
trustedset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1548 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9557 ms (selfie)
  maxAssetCacheWait: 7784 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    abine.com: 1
```
</details>

**Comment by ghajini** [comment]
can't reproduce with default settings

**Comment by Yuki2718** [comment]
I can't register even with blocker disabled both on Chrome and on Firerfox. Bugmenot credential requires 2FA code.

**Comment by ghajini** [comment]
i manage to login with any available temp mail credentials and creating account

**Comment by krystian3w** [comment]
Works fine on my old account (successfully enabled and logged again).

So the best backup uBo settings and refresh by reset (to stock config).
