### ISSUE TITLE
twitch.tv: nuisance

### ISSUE THREAD

**Issue by Popedigoz** [uBlockOrigin/uAssets#14160]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

nuisance

### Describe the issue

Hello,

I wish to be able to block "Prime Loot" -notifications (up-right corner, next to notifications & whispers) (might be you have to be logged in to see that), on the site of Twitch.tv.

sometimes it's possible to block the element, but then it breaks; the button itself isn't there but the amount of "notifications" in the red circle with # is there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 79786
  cosmetic: 45064
  scriptlet: 17481
  html: 712
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32980-135, 14h.12m
    ublock-badware: 4213-0, 14h.11m
    ublock-privacy: 241-0, 9d.21h.38m
    ublock-abuse: 76-0, 9d.21h.37m
    ublock-unbreak: 1864-0, 14h.10m
    easylist: 68891-493, 14h.9m
    easyprivacy: 27457-595, 14h.8m
    urlhaus-1: 4788-0, 18h.14m
    plowe-0: 3645-3, 9d.21h.39m
    ublock-quick-fixes: 277-0, 18h.13m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2155 ms (selfie)
  maxAssetCacheWait: 1961 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google.com: 7
    scorecardresearch.com: 1
```
</details>

**Comment by Popedigoz** [comment]
![firefox_jlON0YrfGC](https://user-images.githubusercontent.com/38588890/181764447-1da546e5-6294-4413-9558-c61655366e93.png)

**Comment by mapx-** [comment]
try

`twitch.tv##.prime-offers`

**Comment by mapx-** [comment]
@ryanbr 

twitch is amazon's property, same about prime stuff, idk if can be considered self-promo
