### ISSUE TITLE
avito.ru: breakage

### ISSUE THREAD

**Issue by zrmnd** [uBlockOrigin/uAssets#14174]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.avito.ru/moskva/rasteniya/gidroponika_dlya_rasteniy_2499992179`
and any other ad page or profile page

### Category

breakage

### Describe the issue

page with enabled uBO: 
![Screenshot_20220730_110453](https://user-images.githubuser
![Screenshot_20220730_110500](https://user-images.githubusercontent.com/36887526/181888519-7e2eacf6-dbce-4fac-afed-8ddebeda81b7.png)
content.com/36887526/181888477-a9d3cecd-ebdb-48cc-8cdf-9ff9cd02324e.png)

page with disabled uBO: 
![Screenshot_20220730_110537](https://user-images.githubusercontent.com/36887526/181888553-f9579e1f-74cc-472a-a6e2-517d8d23aa4a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 90
filterset (summary): 
  network: 121537
  cosmetic: 169023
  scriptlet: 33665
  html: 716
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66310-5414, 18h.59m
    adguard-mobile: 7987-149, 3d.17h.24m
    adguard-annoyance: 55276-1673, 3d.17h.23m
    adguard-social: 18026-25, 16h.50m
  default: 
    user-filters: 9-0, never
    ublock-filters: 32979-73, 19h.2m
    ublock-badware: 4213-0, 19h.1m
    ublock-privacy: 240-0, 4d.14h.23m
    ublock-abuse: 76-0, 4d.14h.22m
    ublock-unbreak: 1864-0, 19h
    easylist: 68890-737, 1d.14h.24m
    easyprivacy: 27459-590, 18h.58m
    urlhaus-1: 4772-0, 18h.57m
    plowe-0: 3641-3, 1d.22h.28m
    RUS-0: 42046-200, 1d.53m
    ublock-quick-fixes: 268-0, 18h.56m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 949 ms (selfie)
  maxAssetCacheWait: 457 ms
popupPanel: 
  blocked: 264
  blockedDetails: 
    avito.ru: 4
    edgecdn.ru: 252
    googleadservices.com: 2
    googletagmanager.com: 1
    scorecardresearch.com: 1
    tns-counter.ru: 1
    weborama.fr: 2
    yandex.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/edf0a70324c4f944f46b07492b37094a53fe3e27
