### ISSUE TITLE
behindwoods.com [Anti-Adblock] 

### ISSUE THREAD

**Issue by meetajhu** [uBlockOrigin/uAssets#1417]
### URL(s) where the issue occurs

`https://www.behindwoods.com/`

### Describe the issue

Anti-Adblock does not work.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3233495/35618871-40773fd0-06a2-11e8-8004-86522f99ebf8.png)

### Versions

- Browser/version: Firefox 58/59
- uBlock Origin version: 1.14.24

### Settings

- Default Settings

### Notes
Site is most likely using this to block ads:
`https://github.com/elidickinson/ad-block-test`

**Comment by mapx-** [comment]
test these filters
```
behindwoods.com###cboxOverlay
behindwoods.com###cboxWrapper
behindwoods.com###colorbox
behindwoods.com##.vedio-block
```

or
```
||behindwoods.com/js/colorbox.js
behindwoods.com##.vedio-block
```

**Comment by meetajhu** [comment]
`behindwoods.com###cboxOverlay
behindwoods.com###cboxWrapper
behindwoods.com###colorbox
behindwoods.com##.vedio-block
`

Works

**Comment by meetajhu** [comment]
So just find id's and classes and add it to filter?

**Comment by mapx-** [comment]
about sync:
https://github.com/gorhill/uBlock/wiki/Cloud-storage
