### ISSUE TITLE
Adblock detected

### ISSUE THREAD

**Issue by jakche** [uBlockOrigin/uAssets#14176]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://idevicecentral.com

### Describe the issue

uBlock Origin is detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/70672583/181906268-01221f48-1233-4c1d-ab73-1cbfaa1b8487.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 79767
  cosmetic: 45053
  scriptlet: 17481
  html: 713
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 32962-128, 21h.19m
    ublock-badware: 4215-0, 21h.18m
    ublock-privacy: 241-0, 21h.17m
    ublock-abuse: 76-0, 21h.16m
    ublock-unbreak: 1850-0, 21h.15m
    ublock-quick-fixes: 277-0, 21h.12m
    easylist: 68901-493, 21h.14m
    easyprivacy: 27459-594, 21h.13m
    urlhaus-1: 4771-0, 21h.11m
    plowe-0: 3644-3, 11d.23h.44m
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1425 ms (selfie)
  maxAssetCacheWait: 159 ms
```
</details>

**Comment by SwiftWinds** [comment]
Anti-adblock again
