### ISSUE TITLE
fiscalitatea.ro: nuisance

### ISSUE THREAD

**Issue by labelingot** [uBlockOrigin/uAssets#14173]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fiscalitatea.ro/`

### Category

nuisance

### Describe the issue

Cookie notification present at the top, on a grey background.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 876542
  cosmetic: 221433
  scriptlet: 37411
  html: 719
listset (total-discarded, last updated): 
  added: 
    https://block.energized.pro/unified/formats/hosts.txt: 740843-59031, 4d.17h
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1927-0, 1d.9h.31m
    adguard-generic: 66236-5745, 3d.14h.34m
    adguard-mobile: 7987-150, 3d.14h.34m
    adguard-spyware: 27460-1276, 1d.9h.37m
    adguard-spyware-url: 689-101, 1d.9h.33m
    block-lan: 43-0, 24d.7h.59m
    curben-phishing: 36321-2, 10h.15m
    curben-pup: 185-0, 1d.9h.32m
    adguard-annoyance: 55277-4566, 3d.14h.34m
    adguard-social: 17992-1057, 3d.14h.34m
    fanboy-thirdparty_social: 69-0, 5d.11h.28m
    fanboy-annoyance: 76079-60427, 5d.11h.29m
    fanboy-cookiemonster: 36979-129, 5d.11h.30m
    fanboy-social: 23237-28, 1d.9h.41m
    ublock-annoyances: 4511-5, 3d.14h.34m
    dpollock-0: 10412-528, 9d.3h.31m
    FRA-0: 29710-398, 1d.9h.40m
    ISL-0: 194-1, 4d.16h.59m
    ROU-1: 979-23, 1d.21h.46m
  default: 
    user-filters: 15-0, never
    ublock-filters: 32954-218, 1d.9h.39m
    ublock-badware: 4215-0, 1d.9h.38m
    ublock-privacy: 240-2, 7d.16h.50m
    ublock-abuse: 76-0, 7d.16h.49m
    ublock-unbreak: 1864-0, 1d.9h.36m
    ublock-quick-fixes: 277-0, 1d.9h.30m
    easylist: 68890-981, 1d.9h.35m
    easyprivacy: 27456-10538, 1d.9h.34m
    urlhaus-1: 4839-0, 10h.16m
    plowe-0: 3640-3, 5d.11h.31m
filterset (user): [array of 15 redacted]
switchRuleset: 
  added: [array of 41 redacted]
hostRuleset: 
  added: [array of 188 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1084 ms (selfie)
  maxAssetCacheWait: 1767 ms
popupPanel: 
  blocked: 19
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    fiscalitatea.ro: 10
    addthis.com: 2
    fonts.googleapis.com: 1
    googletagmanager.com: 1
    onesignal.com: 2
    rs.ro: 3
```
</details>

**Comment by ghajini** [comment]
update your existing fanboy annoyance list
