### ISSUE TITLE
gg.deals: ads

### ISSUE THREAD

**Issue by GhostOfJericho72** [uBlockOrigin/uAssets#14177]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gg.deals/page/keyshops-risks/`

### Category

ads

### Describe the issue

Ad leftovers either side of the store front

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<  
![Screenshot 2022-07-30 114952](https://user-images.githubusercontent.com/90412368/181907651-a8f19ed7-1342-484f-bb50-391c7489694e.png)
![Screenshot 2022-07-30 115123](https://user-images.githubusercontent.com/90412368/181907652-e0227c1c-cecf-4472-9d58-80a099248da8.png)
 >

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79776
  cosmetic: 45013
  scriptlet: 17519
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1h.3m
  default: 
    user-filters: 9-1, never
    easylist: 68815-51, 3d.21h.27m
    easyprivacy: 27449-123, 3d.21h.26m
    plowe-0: 3640-779, 7d.1h.14m
    ublock-abuse: 76-0, 10d.18h.26m
    ublock-badware: 4209-92, 3d.21h.25m
    ublock-filters: 32291-115, 3d.21h.24m
    ublock-privacy: 226-4, 10d.18h.25m
    ublock-quick-fixes: 291-1, 1h.2m
    ublock-unbreak: 1835-42, 3d.21h.23m
    urlhaus-1: 4843-0, 1h.1m
filterset (user): [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 350 ms (selfie)
  maxAssetCacheWait: 90 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    gg.deals: 1
    googletagmanager.com: 1
```
</details>

**Comment by GhostOfJericho72** [comment]
This is on every page of the website

**Comment by pocketdrummer** [comment]
@stephenhawk8054 
This issue appears to have reemerged. I added the following to get them to go away again:
||img.gg.deals/06/6e/5eb19ab8b760229b04062b1dda8d9f89872c_2560xt1440_Q100.jpg$image
gg.deals##.pinned-bg.pinned.with-image.site-banner-content-widget
gg.deals##.site-banner-top-widget
gg.deals##.with-image.site-banner-content-widget

**Comment by mapx-** [comment]
add

`gg.deals##[class*="banner"]`

@ryanbr
