### ISSUE TITLE
itsguider.com: detection

### ISSUE THREAD

**Issue by Known-Enigma** [uBlockOrigin/uAssets#14172]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://itsguider.com/best-serp-tracking-tool-for-tracking-the-position-of-keywords`

### Category

detection

### Describe the issue

Website detects adblock and blocks with screenshot attached

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110271070/181866831-94c16f83-b2cb-4254-8f94-d9c1163fcd27.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79711
  cosmetic: 45005
  scriptlet: 17515
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 68819-51, 2d.23h.23m
    easyprivacy: 27450-123, 2d.23h.22m
    plowe-0: 3645-779, 8d.1h.23m
    ublock-abuse: 76-0, 15h.48m
    ublock-badware: 4209-92, 2d.23h.21m
    ublock-filters: 32292-115, 2d.23h.20m
    ublock-privacy: 226-4, 9d.5h.7m
    ublock-quick-fixes: 280-1, 19h.49m
    ublock-unbreak: 1836-42, 2d.23h.25m
    urlhaus-1: 4772-0, 19h.50m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 503 ms (selfie)
  maxAssetCacheWait: 261 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    doubleclick.net: 2
    dozubatan.com: 1
    rtmark.net: 4
    shrtfly.com: 1
```
</details>

**Comment by hKQwHW** [comment]
Can't reproduce using Firefox or Chrome on Windows 11.

**Comment by TwoPackShaker** [comment]
I'm experiencing the same problem. It looks like it only occurs when redirected through another link shortening service; copying and pasting the itsguider.com URL into your browser will not trigger the adblock detector.

For example, this link will redirect to an itsguider.com URL, which displays the adblock detection message that is displayed in by OP:
https://stfly.me/RNyzYpgU
