### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by KhoaSoCool** [uBlockOrigin/uAssets#14181]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Describe the issue

The web page detects uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 158493
  cosmetic: 192331
  scriptlet: 37530
  html: 0
listset (total-discarded, last updated): 
  added: 
    VIE-1: 1863-0, now
    adguard-annoyance: 55404-75, now
    adguard-generic: 66352-723, now
    adguard-spyware: 25707-1147, now
    adguard-spyware-url: 687-0, now
    block-lan: 43-0, now
    curben-phishing: 33677-0, now
    curben-pup: 184-1, now
    fanboy-annoyance: 77296-3352, now
    ublock-annoyances: 4504-244, now
  default: 
    user-filters: 0-0, never
    easylist: 68907-908, now
    easyprivacy: 27462-9497, now
    plowe-0: 3639-864, now
    ublock-abuse: 76-0, now
    ublock-badware: 4221-323, now
    ublock-filters: 32351-3839, now
    ublock-privacy: 226-49, now
    ublock-quick-fixes: 330-30, now
    ublock-unbreak: 1851-106, now
    urlhaus-1: 4946-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1075 ms
  maxAssetCacheWait: 578 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    addthis.com: 1
    cachefly.net: 1
    dooloust.net: 1
    facebook.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    kolkwi4tzicraamabilis.com: 1
    optad360.io: 1
```
</details>

**Comment by MasterKia** [comment]
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists 



> ```yaml
>   added: 
>     VIE-1: 1863-0, now
>     adguard-annoyance: 55404-75, now
>     adguard-generic: 66352-723, now
>     adguard-spyware: 25707-1147, now
>     adguard-spyware-url: 687-0, now
>     block-lan: 43-0, now
>     curben-phishing: 33677-0, now
>     curben-pup: 184-1, now
>     fanboy-annoyance: 77296-3352, now
>     ublock-annoyances: 4504-244, now
> ```



I can't reproduce, could you try with **_only the default lists_**?

**Comment by KhoaSoCool** [comment]
It's work on the default lists only, thanks

**Comment by MasterKia** [comment]
If you find which specific list is causing this, you could let us know.

**Comment by KhoaSoCool** [comment]
> If you find which specific list is causing this, you could let us know.

I enable some strict modes in Edge, which caused the problem xD

**Comment by KhoaSoCool** [comment]
I manage the reproduce the problem
You have to login to the website
Here the username and pass:
bugmenot
bugmenot

**Comment by MasterKia** [comment]
> I manage the reproduce the problem

With only the default lists?

**Comment by KhoaSoCool** [comment]
> > I manage the reproduce the problem
> 
> With only the default lists?

Yes

**Comment by MasterKia** [comment]
> You have to login to the website

And then do what?
I visited `https://linkneverdie.net/game/digimon-survive-7825`, play the trial and download from Google drive without detection.

**Comment by KhoaSoCool** [comment]
It was the Adguard Base filter that created the problem, for me

**Comment by stephenhawk8054** [comment]
Adguard Base is not in default filter lists.

**Comment by KhoaSoCool** [comment]
> Adguard Base is not in default filter lists.

Really, thanks for spending time helping me...

**Comment by MasterKia** [comment]
> It was the Adguard Base filter that created the problem, for me

If you're **_sure_** about that, you could [report to AdGuard.](https://github.com/AdguardTeam/AdguardFilters/issues/new?assignees=&labels=Unsorted&template=bug_report.yml)
