### ISSUE TITLE
shorterall.com: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#14189]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shorterall.com/q5QjE`

### Category

detection

### Describe the issue

This site detect uBo.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/182099810-05f0d4f6-47a2-4913-a82b-664f2b26d404.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 84030
  cosmetic: 49756
  scriptlet: 17449
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-0, never
    IDN-0: 8993-0, 2d.18h.38m
    easylist: 68901-57, 2d.18h.37m
    easyprivacy: 27459-125, 2d.18h.36m
    plowe-0: 3640-779, 6d.23h.52m
    ublock-abuse: 76-0, 2d.18h.35m
    ublock-badware: 4211-92, 2d.18h.34m
    ublock-filters: 32322-148, 2d.18h.33m
    ublock-privacy: 225-3, 2d.18h.32m
    ublock-unbreak: 1851-44, 2d.18h.31m
    urlhaus-1: 4947-0, 16h.28m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  largeMediaSize: 1024
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 608 ms (selfie)
  maxAssetCacheWait: 405 ms
popupPanel: 
  blocked: 21
  no-remote-fonts: true
  blockedDetails: 
    shorterall.com: 5
    diclotrans.com: 1
    gogshorterall.tk: 1
    googletagmanager.com: 1
    govbusi.info: 1
    gstatic.com: 3
    mc7clurd09pla4nrtat7ion.com: 1
    runative-syndicate.com: 2
    themoneytizer.com: 6
```
</details>

**Comment by Sandor-Helper** [comment]
It detects uBlock again and until you turn it off it goes in a circle all the time and it is impossible to reach the end.
Here what it says
![image_2022_10_12T07_16_27_702Z](https://user-images.githubusercontent.com/31479044/195277008-88165c93-4538-4e44-9515-15aad245773f.png)

And here is the problem link - https://shorterall.com/Yr8e

**Comment by Sandor-Helper** [comment]
I cleared the cache and updated the filters, but the problem still persists.
Maybe it's because they randomly redirect to different intermediate pages?
For example, now redirected from https://shorterall.com/1Viq to https://satoshi-win.xyz/url/Onv9VMSN?no-adblock=fals

**Comment by JobcenterTycoon** [comment]
Works fine for me. Do you have any other adblocker installed? Try with only uBlock Origin

**Comment by JobcenterTycoon** [comment]
@mapx- can you reproduce? When the site detect adblocking the site redirect to `?no-adblock=false` and after this to crap

**Comment by stephenhawk8054** [comment]
I can't reproduce with this link either: `https://shorterall.com/1Viq`. Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

From the screenshot, I see that you are using Firefox's tracking prevention feature. Disable it and test again, also check if you are using any:

- Custom filters,
- Other extensions,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by mapx-** [comment]
No detection on my side.

**Comment by Sandor-Helper** [comment]
Here it is:

uBlock Origin: 1.44.4
Firefox: 91
filterset (summary): 
  network: 96077
  cosmetic: 100101
  scriptlet: 24164
  html: 810
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  added: 
    fanboy-cookiemonster: 41265-117, 3h.37m
    ublock-annoyances: 4870-51, 3h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33797-33, 3h.37m
    ublock-badware: 4373-0, 3h.37m
    ublock-privacy: 281-0, 3h.37m
    ublock-abuse: 76-0, 3h.37m
    ublock-unbreak: 1882-0, 3h.37m
    ublock-quick-fixes: 350-13, 3h.37m
    easylist: 62124-248, 3h.37m
    easyprivacy: 30712-1199, 3h.37m
    plowe-0: 3673-865, 3h.37m
    RUS-0: 40646-197, 3h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3988 ms (selfie)
  maxAssetCacheWait: 2460 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    githubassets.com: 2

**Comment by stephenhawk8054** [comment]
Still can't reproduce with your configurations, although I'm not using Firefox 91. Check other things I have mentioned too.

> From the screenshot, I see that you are using Firefox's tracking prevention feature. Disable it and test again, also check if you are using any:
> 
>     * Custom filters,
>     * Other extensions,
>     * DNS blocking methods,
>     * Blocking softwares outside browser,
>     * OS' hosts file to block domains.

**Comment by Sandor-Helper** [comment]
As I said before I do not have any other blockers.
Hosts is clean
I'm not using DNS bloking methods

I've logged what is downloading - https://www65.zippyshare.com/v/pT0fgx3w/file.html
In the end of logging it switched me to `bitterlythread.com` which was also blocked

**Comment by stephenhawk8054** [comment]
How about this?

> From the screenshot, I see that you are using Firefox's tracking prevention feature. Disable it and test again

**Comment by Sandor-Helper** [comment]
This must be disabled for each specific site. For what exactly to disable? And then I usually use it in private mode. so it turns everything back on. So even if it helps, it won't be a solution.
And the log that above checked it just in the usual mode, not private.

**Comment by stephenhawk8054** [comment]
Sometimes browser's built-in blocker can trigger anti-adblock, and extension cannot intervene it. That's why we asked testing when disabling built-in blocker on that website to see if it's the cause or not.

I have just tested with Firefox ETP setting to `Strict` and there's still no anti-adblock for me, so you need to investigate yourself or wait for someone else who can reproduce and find the cause.

**Comment by Sandor-Helper** [comment]
Shouldn't you please change the status from closed to open so that others can see that you need to check the problem with yourself and need a solution?

**Comment by Yuki2718** [comment]
Redirect to `bitterlythread.com` is server-side (location header in response) but not always done.

**Comment by Yuki2718** [comment]
@Sandor-Helper Clear cookies, force-update filters, and test again.

**Comment by Sandor-Helper** [comment]
I've checked it, unfortunately it still doesn't work. Logs and screenshots at the link.
But if it works for everyone else except me, then let it stay until the protection is redone again.
`https://www68.zippyshare.com/v/bGwYN34b/file.html`
