### ISSUE TITLE
[nsfw] proxifiedpiratebay.org: detection

### ISSUE THREAD

**Issue by mrBega** [uBlockOrigin/uAssets#14180]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://proxifiedpiratebay.org/search.php?q=top100:201`

### Category

detection

### Describe the issue

Search does not show. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 102
filterset (summary): 
  network: 81264
  cosmetic: 26730
  scriptlet: 17525
  html: 715
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2d.15h.9m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33072-317, 2d.15h.20m
    ublock-badware: 4212-0, 3d.22h.38m
    ublock-privacy: 242-1, 19h.15m
    ublock-abuse: 76-0, 12d.11h.35m
    ublock-unbreak: 1854-0, 3d.15h.12m
    adguard-mobile: 7987-167, 3d.22h.39m
    easylist: 68890-25077, 2d.15h.19m
    easyprivacy: 27460-590, 11h.49m
    plowe-0: 3640-3, 7d.23h.40m
    urlhaus-1: 4839-0, 1d.14h.45m
    ublock-quick-fixes: 288-1, 1d.14h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7411 ms (selfie)
  maxAssetCacheWait: 737 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
> Search does not show.

There is nothing to show.

**Comment by mrBega** [comment]
You're right. That is strange. When I tried it a few days back with adblocker turned off it did.

**Comment by mrBega** [comment]
Closeing
