### ISSUE TITLE
awebstories.com: nuisance

### ISSUE THREAD

**Issue by StupidlyKind** [uBlockOrigin/uAssets#14183]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://awebstories.com/im-going-to-marry-a-poor-count-in-the-middle-of-nowhere-and-im-going-to-work-hard-to-reform-my-territory-chapter-21/`

### Category

nuisance

### Describe the issue

An overlay directing to a Kofi link completely blocks reading the websites. Similar to pay to view filter. Clicking the link does not remove the overlay and the site is unreadable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/109827951/182030781-31cfcde1-45d0-490a-8b6e-f8666edaf5fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 79841
  cosmetic: 45036
  scriptlet: 17519
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1d.10h.30m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 68838-51, 3d.14h.22m
    easyprivacy: 27450-123, 3d.14h.21m
    plowe-0: 3709-810, 134d.9h.41m
    ublock-abuse: 76-0, 11h.25m
    ublock-badware: 4209-91, 3d.14h.20m
    ublock-filters: 32288-114, 3d.14h.19m
    ublock-privacy: 226-3, 11h.26m
    ublock-quick-fixes: 318-12, 11h.23m
    ublock-unbreak: 1844-42, 3d.14h.23m
    urlhaus-1: 4852-0, 11h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 215 ms (selfie)
  maxAssetCacheWait: 64 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    awebstories.com: 8
    connatix.com: 1
    doubleclick.net: 1
    ezodn.com: 1
    googletagmanager.com: 2
    imasdk.googleapis.com: 1
    quantserve.com: 1
```
</details>

**Comment by MasterKia** [comment]
Add these to "My filters" and report back:
```
||ko-fi.com^$domain=awebstories.com
awebstories.com##+js(acis, counterwidget)
```

**Comment by StupidlyKind** [comment]
Works perfectly, no longer get that Kofi overlay

Thank you

**Comment by krystian3w** [comment]
Blog also block selection IMO by CSS #14070 #7916.

**Comment by okiehsch** [comment]
Hm, I don't see any overlay on my end.

**Comment by MasterKia** [comment]
> Hm, I don't see any overlay on my end.

I needed to wait for at least 10 seconds.

**Comment by okiehsch** [comment]
````
||ko-fi.com^$script,domain=awebstories.com
awebstories.com##+js(acis, counterwidget)
````

On my end those filters won't do anything, i.e. there is no `ko-fi` request and nothing in the source that
`awebstories.com##+js(acis, counterwidget)` could abort.

Maybe it depends on ones geo location.

**Comment by krystian3w** [comment]
Ko-fi is not overlay this delete body dom tree and inject iframe.

Try with many Polish VPN-s, maybe reporoduce also recommend try in Firefox if Chrome hide this as havy ad.

**Comment by MasterKia** [comment]
> there is no `ko-fi` request and nothing in the source that
> `awebstories.com##+js(acis, counterwidget)` could abort.

Either depends on geo location or the site admin has removed this because I couldn't reproduce now (I took those from source yesterday).
Maybe @krystian3w still can reproduce.

**Comment by krystian3w** [comment]
Now looks as disabled on page if webmaster don't delete "inline" JavaScript by other script (sic!).

Maybe wait to fix with real paid coffee ☕ (e.g. fix bugs with enabled total cookie protection in Firefox or add-ons like auto cookie-delete).

**Comment by MasterKia** [comment]
@ghajini It was reproducible yesterday.

**Comment by krystian3w** [comment]
But yesterday now will be only in UTC-X (UTC 0 and + have "tomorrow").

**Comment by MasterKia** [comment]
Thanks for the lesson.

**Comment by MasterKia** [comment]
@StupidlyKind Do you still get the Ko-Fi overlay if you remove the two filters I sent you?

**Comment by ghajini** [comment]
@StupidlyKind 
when it happens again, leave a message here
