### ISSUE TITLE
Babiato adblock

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#14188]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://babiato.co/conversations/
https://babiato.co/

### Describe the issue

The anti adblock popup will appear few second after we fully load the sites....
and i think, the id will randomly generate for each load page we had... so maybe it will need different approach to get anti adblock working (this is already few times since i reporting this)

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by okiehsch** [comment]
I assume you ar logged in, I can't reproduce if I am not.

**Comment by Dhanamerdeka** [comment]
> I assume you are logged in, I can't reproduce if I am not.

yeah i logged :( but for home link... i think you didn't need to logged to be able to see anti adblock notification popup
