### ISSUE TITLE
asia.nikkei.com: breakage

### ISSUE THREAD

**Issue by sidmat** [uBlockOrigin/uAssets#14195]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://asia.nikkei.com/`

### Category

breakage

### Describe the issue

`Log in` button (top right corner of the page) does not work. As a subscriber, I am unable to log in. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 79949
  cosmetic: 45094
  scriptlet: 17493
  html: 714
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32994-64, 2d.7h.13m
    ublock-badware: 4225-0, 2d.7h.12m
    ublock-privacy: 241-0, 2d.7h.11m
    ublock-abuse: 76-0, 2d.7h.10m
    ublock-unbreak: 1864-0, 2d.6h.54m
    ublock-quick-fixes: 328-0, 6h.8m
    easylist: 68900-585, 2d.6h.52m
    easyprivacy: 27458-580, 2d.6h.49m
    urlhaus-1: 4929-0, 6h.6m
    plowe-0: 3638-3, 2d.6h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 192 ms (selfie)
  maxAssetCacheWait: 101 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    nikkei.com: 13
    chartbeat.com: 1
    cxense.com: 1
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    hotjar.com: 1
    npttech.com: 1
    outbrain.com: 1
    piano.io: 1
    taboola.com: 1
    twitter.com: 1
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce.
You have to wait until the page is fully loaded then "log in" button would appear.

**Comment by Yuki2718** [comment]
Hmm, `piano.io` is blocked on your side while not on my side. Can you upload screenshots of the logger @sidmat ?
