### ISSUE TITLE
RU AdList - filter works with issue

### ISSUE THREAD

**Issue by ilyak83** [uBlockOrigin/uAssets#14190]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.ivory.co.il/

### Describe the issue

I noticed that when I used "RU AdList" filter, he is break some sites. For example ivory.co.il. Screenshot attached: 1- With "AdGuard Russian filter" manual filter added the site works well. But with "RU AdList" - Screenshot-2 a half content dissapear.

### Screenshot(s)

![Screenshot_1](https://user-images.githubusercontent.com/37582972/182109720-c1829892-8f16-4462-99bc-c3a03edfdec1.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/37582972/182109755-e69e3045-2fc4-46aa-b311-1627f3030ceb.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/37582972/182109972-17a96997-9355-47b1-ad40-3d77837e044b.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/37582972/182109985-a4ab57ed-e887-4fb0-90ab-c4575ae744ab.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 93581
  cosmetic: 100449
  scriptlet: 22054
  html: 728
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt: 29752-115, 1d.2h.47m
    adguard-spyware-url: 687-1, 1d.2h.40m
    fanboy-cookiemonster: 37531-143, 3d.22h.46m
    ublock-annoyances: 4512-5, 1d.2h.42m
    ISR-0: 1640-0, 1d.2h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33029-36, 1d.2h.46m
    ublock-badware: 4225-1, 1d.2h.45m
    ublock-privacy: 240-0, 8d.2h.52m
    ublock-abuse: 76-0, 8d.2h.51m
    ublock-unbreak: 1864-1, 1d.2h.44m
    ublock-quick-fixes: 315-45, 1d.2h.39m
    easylist: 68906-748, 1d.2h.43m
    easyprivacy: 27460-647, 1d.2h.41m
    urlhaus-1: 4852-0, 1d.2h.38m
    plowe-0: 3640-3, 6d.2h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 203 ms (selfie)
  maxAssetCacheWait: 351 ms
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/6fa2e5beda12f7fe89f07633f3a54ace42e45a6b
