### ISSUE TITLE
oricon.co.jp: nuisance

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#14193]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.oricon.co.jp/prof/174418/lyrics/I077156/`

### Category

nuisance

### Describe the issue

This site doesn't allow select and copy lyrics

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 35466
  cosmetic: 34351
  scriptlet: 21667
  html: 1594
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    JPN-1: null
  added: 
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt: 8009-64, 18h.15m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 48737-9875, 18h.15m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-social.txt: 2533-0, 19h.28m
    ublock-annoyances: 4512-4, 19h.28m
  default: 
    ublock-filters: 33039-526, 19h.28m
    ublock-badware: 4225-0, 19h.28m
    ublock-privacy: 251-2, 19h.28m
    ublock-abuse: 76-0, 19h.28m
    ublock-unbreak: 1864-0, 19h.27m
    ublock-quick-fixes: 328-1, 19h.27m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 796 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    oricon.co.jp: 3
    akamaized.net: 2
    amazon-adsystem.com: 1
    doubleclick.net: 1
    facebook.net: 1
    flux-cdn.com: 2
    googletagmanager.com: 1
    im-apps.net: 1
    logly.co.jp: 1
    popin.cc: 1
    taxel.jp: 2
    yimg.jp: 1
```
</details>

**Comment by MasterKia** [comment]
Add these to "My filters" and report back:
```
oricon.co.jp##+js(ra, oncontextmenu, .all-lyrics)
oricon.co.jp##+js(ra, onmousedown, .all-lyrics)
oricon.co.jp##+js(ra, onselectstart, .all-lyrics)
oricon.co.jp##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```
