### ISSUE TITLE
vitepress.vuejs.org: ads

### ISSUE THREAD

**Issue by git-Hmmm** [uBlockOrigin/uAssets#14196]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vitepress.vuejs.org/guide/getting-started.html`

### Category

ads

### Describe the issue

At bottom right corner this empty box is there which is an ad leftover.
![image](https://user-images.githubusercontent.com/102938585/182168756-6bb20222-8645-4b8e-90ca-10119037d0f0.png)

How I came to know?
Inspect Tool ;)
![image](https://user-images.githubusercontent.com/102938585/182168929-dd5eb474-03a5-4b18-84c0-82c0b575c457.png)
See it's saying `VPCarbonAds` so it's probably an ad leftover box.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/102938585/182168756-6bb20222-8645-4b8e-90ca-10119037d0f0.png)

![image](https://user-images.githubusercontent.com/102938585/182168929-dd5eb474-03a5-4b18-84c0-82c0b575c457.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 140745
  cosmetic: 125444
  scriptlet: 21709
  html: 714
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55402-3239, now
    fanboy-cookiemonster: 38226-87, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33065-110, 1m
    ublock-badware: 4174-0, 1m
    ublock-privacy: 246-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1864-1, 1m
    ublock-quick-fixes: 344-1, 1m
    easylist: 68946-603, 1m
    adguard-spyware-url: 687-1, now
    easyprivacy: 27465-580, now
    urlhaus-1: 5269-0, now
    curben-phishing: 52167-4, now
    plowe-0: 3639-3, now
    LegitimateURLShortener: 1932-92, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1477 ms (selfie)
  maxAssetCacheWait: 638 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    carbonads.com: 1
```
</details>

**Comment by okiehsch** [comment]
`vitepress.vuejs.org##.VPCarbonAds`
@ryanbr

**Comment by git-Hmmm** [comment]
Thank you for fixing it I am no longer seeing that leftover after updating lists.

**Comment by git-Hmmm** [comment]
wait a min! 
you should have blocked the parent element too but ok no problem as long as it's not causing any issues.
![image](https://user-images.githubusercontent.com/102938585/182379418-f24a59a9-835c-453e-bfb8-71a57d4c7977.png)
