### ISSUE TITLE
morosedog.gitlab.io: detection

### ISSUE THREAD

**Issue by DarrenChung63** [uBlockOrigin/uAssets#14191]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://morosedog.gitlab.io/

### Describe the issue

This site and its sub-domains detects uBo.

### Screenshot(s)

![螢幕擷取畫面 2022-08-01 174123](https://user-images.githubusercontent.com/53455329/182120828-2c5b4756-d396-4206-9ad4-4edd8420f4d2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98368
  cosmetic: 55392
  scriptlet: 17646
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28964-92, 1d.18h.10m
    easylist: 68906-73, 1d.18h.9m
    easyprivacy: 27460-149, 1d.18h.8m
    plowe-0: 3640-781, 9d.18h.56m
    ublock-abuse: 76-0, 1d.18h.7m
    ublock-badware: 4221-92, 1d.18h.6m
    ublock-filters: 32347-133, 1d.18h.5m
    ublock-privacy: 226-3, 1d.18h.4m
    ublock-quick-fixes: 331-28, 8h.3m
    ublock-unbreak: 1851-43, 1d.18h.3m
    urlhaus-1: 4947-0, 8h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 615 ms (selfie)
  maxAssetCacheWait: 252 ms
```
</details>

**Comment by DarrenChung63** [comment]
It could be fixed by opening AdGuard Annoyance list.

**Comment by krystian3w** [comment]
But uBo still allow copy advance fixes to uBo Annoyances (EasyList added suppelemt where put CSS and scriptlets).

**Comment by MasterKia** [comment]
`morosedog.gitlab.io##+js(set, checkAds, noopFunc)`

**Comment by DarrenChung63** [comment]
Sorry, AdGuard Annoyance doesn't really prevent this, The detection warning shows up after refreshing the page.

**Comment by DarrenChung63** [comment]
> 
Added. It works fine.
