### ISSUE TITLE
komputerswiat.pl: detection

### ISSUE THREAD

**Issue by genuinejanbar** [uBlockOrigin/uAssets#14198]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.komputerswiat.pl/poradniki/sprzet/jak-sprawdzic-stan-dysku-twardego/07z87ye`

### Category

detection

### Describe the issue

Just uBlock is detected and content is covered with demand to off adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 103
filterset (summary): 
  network: 81726
  cosmetic: 52532
  scriptlet: 17708
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 33055-36, 54m
    ublock-badware: 4174-1, 53m
    ublock-privacy: 246-0, 1h.1m
    ublock-abuse: 76-0, 1h
    ublock-unbreak: 1864-0, 52m
    easylist: 68988-240, 51m
    easyprivacy: 27465-594, 50m
    urlhaus-1: 5269-0, 55m
    plowe-0: 3639-340, 58m
    POL-0: 7834-45, 56m
    POL-2: 1279-47, 49m
    ublock-quick-fixes: 315-41, 57m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4790 ms (selfie)
  maxAssetCacheWait: 1612 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    doubleclick.net: 1
    dqst.pl: 2
    dreamlab.pl: 3
    gemius.pl: 1
    ocdn.eu: 3
    onet.pl: 8
    pushpushgo.com: 2
```
</details>

**Comment by genuinejanbar** [comment]
How should I use it? Just copy into My filters section in uBlock Original settings?Temat: Re: [uBlockOrigin/uAssets] komputerswiat.pl: detection (Issue #14198)Data: 2022-08-02 10:18Nadawca: "krystian3w" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Fyi @olegwukr (AdQuesto)

**Comment by Procyon-b** [comment]
Refresh the filter lists.

**Comment by genuinejanbar** [comment]
Of course I made it and when I use that filters from @Oleginukr, in My Own section, I've got a warning that there are non actual... It's mean that lists are included in official uBlock Original filter lists?Temat: Re: [uBlockOrigin/uAssets] komputerswiat.pl: detection (Issue #14198)Data: 2022-08-02 19:49Nadawca: "Marc Boucher" ***@***.***&gt;Adresat: "uBlockOrigin/uAssets" ***@***.***&gt;; DW: "genuinejanbar" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Refresh the filter lists.

**Comment by krystian3w** [comment]
You mean Polish Privacy List aka supplement to EasyPrivacy?

**Comment by genuinejanbar** [comment]
Well..., for now, all is fine, the filters work, so that solution is good enough. Thnx!
