### ISSUE TITLE
pornqd.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1419]
URL(s) where the issue occurs

`https://www.pornqd.com/movie/naughtyamerica-ashley-adams-sean-lawless-bald-guy-gave-the-letter-and-had-sex-with-a-pretty-girl.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
anti adblock
