### ISSUE TITLE
cbtnuggets.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#14192]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cbtnuggets.com/blog/certifications/cisco/when-to-use-20mhz-vs-40mhz-vs-80mhz`

### Category

ads

### Describe the issue

cookies banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 105
filterset (summary): 
  network: 88386
  cosmetic: 166404
  scriptlet: 25592
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9896-4, 1h.43m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 1h.43m
    adguard-annoyance: 55396-427, 1h.43m
    fanboy-annoyance: 77368-3300, 1h.43m
    ublock-annoyances: 4503-220, 1h.43m
  default: 
    user-filters: 12-0, never
    easylist: 68946-107, 1h.43m
    easyprivacy: 27465-221, 1h.43m
    ublock-abuse: 76-0, 1h.43m
    ublock-badware: 4221-90, 1h.43m
    ublock-filters: 32407-603, 1h.43m
    ublock-privacy: 230-10, 1h.43m
    ublock-quick-fixes: 347-66, 1h.43m
    ublock-unbreak: 1851-47, 1h.43m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 956 ms (selfie)
  maxAssetCacheWait: 614 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    doubleclick.net: 2
    google.com: 3
    googletagmanager.com: 1
    youtube.com: 8
```
</details>

**Comment by JobcenterTycoon** [comment]
> GDPR modals will not be addressed in https://github.com/uBlockOrigin/uAssets/issues/4123#issuecomment-439232886.

**Comment by MasterKia** [comment]
> cookies banner

You should report to EasyList Cookie: https://github.com/easylist/easylist/issues/new
