### ISSUE TITLE
cibc.com: breakage

### ISSUE THREAD

**Issue by mach128x** [uBlockOrigin/uAssets#14194]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cibc.com/en/personal-banking.html`

### Category

breakage

### Describe the issue

When login in via "Sign On" : if the login info is incorrect, the site tries to redirect to https://www.cibconline.cibc.com which enters an infinite loop due to elements being blocked by uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 79986
  cosmetic: 45107
  scriptlet: 17498
  html: 714
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33005-63, 2d.12m
    ublock-badware: 4225-0, 2d.14m
    ublock-privacy: 242-0, 2d.18m
    ublock-abuse: 76-0, 2d.17m
    ublock-unbreak: 1864-0, 2d.11m
    easylist: 68906-585, 2d.15m
    easyprivacy: 27460-580, 2d.13m
    urlhaus-1: 4947-0, 19h.52m
    plowe-0: 3639-3, 2d.19m
    ublock-quick-fixes: 344-1, 1h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 305 ms (selfie)
  maxAssetCacheWait: 256 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 1
    online-metrix.net: 1
```
</details>

**Comment by MasterKia** [comment]
After entering wrong login info and clicking on "Sign On", I get "Signing out ..." then get redirected to `https://www.cibconline.cibc.com/ebm-resources/public/banking/cibc/client/web/index.html#/signon` just fine:
> You have entered incorrect information. Check your information and try again. After multiple failed attempts, you may be locked out. For password issues, you can select the checkbox to view your password or reset it.
For CIBC Costco Mastercard holders, use the phone number you previously had on file.

**Comment by mach128x** [comment]
> After entering wrong login info and clicking on "Sign On", I get "Signing out ..." loop then get redirected to `https://www.cibconline.cibc.com/ebm-resources/public/banking/cibc/client/web/index.html#/signon` just fine:
> 
> > You have entered incorrect information. Check your information and try again. After multiple failed attempts, you may be locked out. For password issues, you can select the checkbox to view your password or reset it.
> > For CIBC Costco Mastercard holders, use the phone number you previously had on file.

Here, the "Signing out..." is an infinite loop.
Disabling uBlock for https://www.cibconline.cibc.com solves the problem.
I tried re-installing the uBlock extension, flushing cibc.com site data in Firefox (btw I am on 103.0.1), but neither helped.

**Comment by MasterKia** [comment]
Have you tried disabling Firefox ETP (Enhanced Tracking Protection)?

**Comment by msgpacket** [comment]
same problem in Chromium browsers (with clean defaults)

**Comment by ghajini** [comment]
does this work for you

`@@||cibc.com.ssl.d2.sc.omtrdc.net^$xhr,domain=cibconline.cibc.com`

**Comment by ghajini** [comment]
@mach128x 
update your filter lists, its fixed

**Comment by mach128x** [comment]
> @mach128x update your filter lists, its fixed

@ghajini thank you! Confirmed and working.
