### ISSUE TITLE
tn.nova.cz: detection

### ISSUE THREAD

**Issue by Aksille** [uBlockOrigin/uAssets#14199]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tn.nova.cz/sport/clanek/468185-hroziva-nehoda-v-drahove-cyklistice-zavodnik-vjel-mezi-fanousky`

### Category

detection

### Describe the issue

"Could not play video because of active adblock" = "Video nelze přehrát, protože máte aktivní adblock"

### Screenshot(s)

![image](https://user-images.githubusercontent.com/31105698/182241437-a8ec46c2-3fbd-411f-9576-a58c61383e27.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80305
  cosmetic: 45088
  scriptlet: 17523
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 68901-51, 2d.20h.31m
    easyprivacy: 27458-123, 2d.20h.30m
    plowe-0: 3645-779, 12d.9h.58m
    ublock-abuse: 76-0, 12d.9h.57m
    ublock-badware: 4221-92, 2d.20h.29m
    ublock-filters: 32320-114, 2d.20h.28m
    ublock-privacy: 226-4, 12d.9h.56m
    ublock-quick-fixes: 347-26, 2h.52m
    ublock-unbreak: 1851-42, 2d.20h.27m
    urlhaus-1: 5269-0, 2h.53m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 528 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 66
  blockedDetails: 
    nova.cz: 4
    adform.net: 18
    adnxs.com: 9
    adscale.de: 3
    bkrtx.com: 1
    connectad.io: 6
    criteo.com: 7
    criteo.net: 2
    gemius.pl: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    seznam.cz: 2
    smartadserver.com: 6
    trackad.cz: 3
    upscore.com: 1
```
</details>

**Comment by okiehsch** [comment]
It's already fixed in the regional `Czech` list.
