### ISSUE TITLE
Golem.de: big abo-banners

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#142]
### URL(s) where the issue occurs

`[http://www.golem.de/news/ende-der-stoererhaftung-bei-verstoessen-droht-hotspot-anbietern-nutzerregistierung-1609-123268.html]`

### Describe the issue

The page has large annoying green banners that advertise their ad-free subscription which should be hidden.

### Screenshot(s)

![gad](https://cloud.githubusercontent.com/assets/17909/18545625/41957066-7b3a-11e6-997f-2e0774f0289d.JPG)

### Versions

- Browser/version:  Firefox 47
- uBlock Origin version: 1.9.6

### Settings

https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt was added

### Notes

These boxes seem come from
'[http://ecruos.golem.de/dyn]'
unfortunately you trigger the anti-adblock mechanism that way which blurrs the original articles and
prints a "please disable your adblocker" on top.

**Comment by gorhill** [comment]
It's self-promotion, so a filter for this is probably more fit for Fanboy Annoyances. Report to EasyList forum please: <https://forums.lanik.us/viewforum.php?f=62>.

**Comment by yoshimo** [comment]
@gorhill I do think that handling Anti-Adblock filters is something worth doing here.
I therefore suggest some version of:

`golem.de##script:contains(_sp_)
forum.golem.de##script:contains(_sp_)
video.golem.de##script:contains(_sp_)`

Judging by the origin (sourcepoint) this might become a bad habit elsewhere as well.

**Comment by IDKwhattoputhere** [comment]
To me it looks like `spieletipps.de` which [displays actual ads](https://cloud.githubusercontent.com/assets/16030872/19609536/0ed64744-97d8-11e6-86f4-65723e186d32.jpg) seems to use this sourcepoint code too.
