### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by kfilius** [uBlockOrigin/uAssets#14200]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=mZ0XpCUAHHA`

### Category

breakage

### Describe the issue

Youtube upload doesn't play

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![afbeelding](https://user-images.githubusercontent.com/110426460/182242379-971c6b29-ee45-45d9-a03b-80dc627a7730.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 81053
  cosmetic: 46755
  scriptlet: 17525
  html: 715
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33065-147, 2h.44m
    ublock-badware: 4174-0, 2h.44m
    ublock-privacy: 246-0, 2h.44m
    ublock-abuse: 76-0, 2h.44m
    ublock-unbreak: 1865-0, 2h.44m
    easylist: 68988-595, 2h.44m
    easyprivacy: 27465-581, 2h.44m
    plowe-0: 3639-3, 2h.44m
    NLD-0: 2442-29, 2h.44m
    urlhaus-1: 5269-0, 2h.44m
    ublock-quick-fixes: 344-1, 2h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 178 ms (selfie)
  maxAssetCacheWait: 93 ms
popupPanel: 
  blocked: 39
  blockedDetails: 
    youtube.com: 27
    doubleclick.net: 5
    google.com: 5
    google.nl: 1
    googlesyndication.com: 1
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
