### ISSUE TITLE
itsguider.com [anti-adblock]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#14202]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://stfly.me/NQ75UC

### Describe the issue

After clicking 'Human Verification' on the `stfly.me` site you get redirected to `itsguider.com` which has anti-adblock. Also trying to hide the element results in the site getting messed up.

### uBlock Origin version

1.43.0

### Browser name and version

Chrome V103.0.5060.134

### Settings

default settings.

**Comment by ghajini** [comment]
force update your default filter lists & see if that solves problem

**Comment by dumbusernameidk** [comment]
its fixed now.
