### ISSUE TITLE
btdb.to [Pop-up]

### ISSUE THREAD

**Issue by lievedido** [uBlockOrigin/uAssets#1420]
### URL(s) where the issue occurs

`https://btdb.to/q/test/`

### Describe the issue

Go to website and click anywhere on torrents.

### Versions

- Browser/version: Firefox 59.0b5
- uBlock Origin version: 1.14.24

### Settings

Default

**Comment by mapx-** [comment]
I cannot reproduce the issue: try updating `ublock filters` (be sure `ublock filters` are enabled), test again.

**Comment by lievedido** [comment]
@mapx- It's updated for me, but i need to wait until Ublock is updated to check it. You need to click on area with torrent entries, not above.

**Comment by mapx-** [comment]
I clicked any area, still no issues here.

What do you mean by 

> It's not updating properly

 ?

**Comment by lievedido** [comment]
@mapx- My uBlock wasn't updating so i created new profile, now it's fixed.
