### ISSUE TITLE
zadfaucet.com: detection

### ISSUE THREAD

**Issue by ahmedok2022** [uBlockOrigin/uAssets#14209]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zadfaucet.com/free-bitcoin/`

### Category

detection

### Describe the issue

![ScreenShot_20220802113928](https://user-images.githubusercontent.com/106882633/182344237-79bb4478-847e-4c07-b0bb-6d4ab3bbcb0f.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 102698
  cosmetic: 140948
  scriptlet: 32512
  html: 714
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66444-5234, 15h.17m
    adguard-annoyance: 55418-1421, 15h.17m
    adguard-social: 18049-31, 15h.17m
  default: 
    user-filters: 3-0, never
    ublock-filters: 33065-37, 15h.17m
    ublock-badware: 4174-1, 15h.17m
    ublock-privacy: 246-0, 15h.17m
    ublock-abuse: 76-0, 15h.17m
    ublock-unbreak: 1865-30, 15h.17m
    ublock-quick-fixes: 344-66, 15h.17m
    easylist: 68988-592, 15h.30m
    easyprivacy: 27465-102, 15h.17m
    urlhaus-1: 5269-0, 15h.17m
    plowe-0: 3639-451, 15h.17m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2572 ms (selfie)
  maxAssetCacheWait: 429 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    a-ads.com: 3
    ayelads.xyz: 2
    bmfads.com: 3
    cointraffic.io: 2
    doubleclick.net: 2
    getclicky.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    surfe.pro: 1
```
</details>

**Comment by MasterKia** [comment]
`zadfaucet.com##+js(set, verifica_adblock, noopFunc)`
