### ISSUE TITLE
vix.com: ads

### ISSUE THREAD

**Issue by parasiteoflife** [uBlockOrigin/uAssets#14213]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vix.com/es-es/detail/video-2687602`

### Category

ads

### Describe the issue

Site shows ads using default list or the current filter list config shown below. The adds are similar to YouTube's in the way they are presented.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 195342
  cosmetic: 218290
  scriptlet: 37785
  html: 721
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66474-5431, now
    adguard-mobile: 8031-149, now
    adguard-spyware: 28364-1617, now
    adguard-spyware-url: 687-1, now
    block-lan: 43-0, now
    curben-phishing: 54769-8, now
    curben-pup: 183-0, now
    adguard-annoyance: 55468-4701, now
    adguard-social: 18064-1058, now
    fanboy-thirdparty_social: 69-0, now
    fanboy-annoyance: 77458-61758, now
    fanboy-cookiemonster: 38299-134, now
    fanboy-social: 23251-28, now
    ublock-annoyances: 4523-4, now
    dpollock-0: 10413-523, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33083-196, now
    ublock-badware: 4175-0, now
    ublock-privacy: 246-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1864-1, now
    ublock-quick-fixes: 360-1, now
    easylist: 69026-1028, now
    easyprivacy: 27474-10363, now
    urlhaus-1: 4957-0, now
    plowe-0: 3639-3, now
    spa-0: 3898-2, now
    spa-1: 4580-110, now
filterset (user): [empty]
hostRuleset: 
  added: [array of 66 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 580 ms (selfie)
  maxAssetCacheWait: 868 ms
popupPanel: 
  blocked: 79
  blockedDetails: 
    braze.com: 9
    conviva.com: 4
    cookielaw.org: 2
    doubleclick.net: 5
    googletagservices.com: 1
    imasdk.googleapis.com: 2
    kochava.com: 50
    lura.live: 2
    newrelic.com: 1
    permutive.app: 2
    segment.com: 1
```
</details>

**Comment by MasterKia** [comment]
I get "Lo sentimos, pero ViX no está disponible en tu país. (_We're sorry, but ViX is not available in your country._)"

I don't have Spanish VPN.

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> added: 
    adguard-generic: 66474-5431, now
    adguard-mobile: 8031-149, now
    adguard-spyware: 28364-1617, now
    adguard-spyware-url: 687-1, now
    block-lan: 43-0, now
    curben-phishing: 54769-8, now
    curben-pup: 183-0, now
    adguard-annoyance: 55468-4701, now
    adguard-social: 18064-1058, now
    fanboy-thirdparty_social: 69-0, now
    fanboy-annoyance: 77458-61758, now
    fanboy-cookiemonster: 38299-134, now
    fanboy-social: 23251-28, now
    ublock-annoyances: 4523-4, now
    dpollock-0: 10413-523, now

Could you test with **_only the default lists_**?

**Comment by parasiteoflife** [comment]
Yes, tested with the default lists and I still get the ads:
![snap256](https://user-images.githubusercontent.com/57022988/182426531-5475c762-1497-4c39-ab19-a1cee56a8cc7.png)

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
I can access with Brazilian IP but needs an account.

**Comment by MasterKia** [comment]
> with Spanish IP redirects to another domain

Weird. Wikipedia said Vix is available in Spanish.

**Comment by Yuki2718** [comment]
This is SSAI and I suspect is not fixable.

**Comment by MasterKia** [comment]
Maybe add SSAI label too

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1905
