### ISSUE TITLE
Page reload necessary to block ads on specific site 

### ISSUE THREAD

**Issue by fabi94music** [uBlockOrigin/uAssets#1421]
### Describe the issue
Not all ads on 9to5mac.com are blocked when loading the page. Only a manual reload of the page will block those ads. 

### One or more specific URLs where the issue occurs
`https://9to5mac.com`

### Screenshot in which the issue can be seen
![bildschirmfoto 2018-01-25 um 19 37 26](https://user-images.githubusercontent.com/29753374/35405666-34f0687a-0207-11e8-8812-d2b53bb8e222.png)
![bildschirmfoto 2018-01-25 um 19 37 10](https://user-images.githubusercontent.com/29753374/35405667-35086d1c-0207-11e8-956d-485ea4757652.png)

### Steps for anyone to reproduce the issue

1. Open Safari and go to the URL
2. Scroll down to see the ad
3. Refresh the site and the ads will be gone

### Your settings

> [If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- MacOS version: 10.13.3
- Safari version: 11.0.3
- uBlock Origin version: 1.14.24

##### Your filter lists

<img width="573" alt="bildschirmfoto 2018-01-25 um 19 40 03" src="https://user-images.githubusercontent.com/29753374/35405926-d283bf06-0207-11e8-8dd8-ca020a2a085a.png">
<img width="621" alt="bildschirmfoto 2018-01-25 um 19 40 22" src="https://user-images.githubusercontent.com/29753374/35405927-d29f2a2a-0207-11e8-8894-4a852aecdeca.png">

##### Your custom filters (if any)
<img width="670" alt="bildschirmfoto 2018-01-25 um 19 40 54" src="https://user-images.githubusercontent.com/29753374/35405930-d73bb13e-0207-11e8-8b7f-9c1b3a60040d.png">

**Comment by okiehsch** [comment]
I can't reproduce, the ad is blocked by
`9to5mac.com##script:inject(abort-on-property-read.js, canRunAds)`
on first load with Chrome/Firefox and Windows/Linux on my end.

I do not have a MacOS device.

**Comment by fabi94music** [comment]
I only have this issue on Safari, Chrome works fine

**Comment by mapx-** [comment]
You should report here:
https://github.com/el1t/uBlock-Safari/issues

**Comment by okiehsch** [comment]
Well, the filter works, so it is a Safari specific issue.

**Comment by fabi94music** [comment]
Thanks, I did and they said I should report here :P

**Comment by mapx-** [comment]
@fabi94music  you have a lot of lists, what if you keep only the normal uBo setup and test again ?

**Comment by fabi94music** [comment]
Okay, I tried that but still have the same issue. A little weird, because I only noticed it on that website. It  does not bother me too much though...

**Comment by krystian3w** [comment]
It should be removed renamed label.
