### ISSUE TITLE
censor.net: ads

### ISSUE THREAD

**Issue by kurttu4** [uBlockOrigin/uAssets#14212]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://censor.net/ua/news/all`

### Category

ads

### Describe the issue

ad appeared

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98140
  cosmetic: 67047
  scriptlet: 17477
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 40349-9, 1m
    easylist: 69026-66, 1m
    easyprivacy: 27474-223, 1m
    plowe-0: 3639-782, 1m
    ublock-abuse: 76-1, now
    ublock-badware: 4171-92, now
    ublock-filters: 32425-150, now
    ublock-privacy: 230-3, now
    ublock-unbreak: 1851-42, now
    urlhaus-1: 4957-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 486 ms (selfie)
  maxAssetCacheWait: 267 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    censor.net: 5
    doubleclick.net: 1
    google-analytics.com: 1
    googleoptimize.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
You need to do this:
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
>
