### ISSUE TITLE
[nsfw] yandex.ru: ads

### ISSUE THREAD

**Issue by Dima62M74** [uBlockOrigin/uAssets#14211]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yandex.ru/`

### Category

ads

### Describe the issue

Contextual advertising began to appear, although it has never appeared since the day the blocker was installed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://disk.yandex.ru/i/Ecsyoa0nmkj-xw

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 98460
  cosmetic: 67129
  scriptlet: 17497
  html: 714
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33000-63, 3d.19m
    ublock-badware: 4225-0, 3d.18m
    ublock-privacy: 242-0, 3d.17m
    ublock-abuse: 76-0, 3d.16m
    ublock-unbreak: 1864-0, 3d.15m
    ublock-quick-fixes: 344-1, 17h.5m
    easylist: 68900-600, 3d.13m
    easyprivacy: 27460-580, 3d.12m
    urlhaus-1: 5269-0, 17h.4m
    plowe-0: 3639-3, 3d.10m
    RUS-0: 40343-144, 21h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15214 ms (selfie)
  maxAssetCacheWait: 1094 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    yandex.ru: 29
```
</details>

**Comment by MasterKia** [comment]
Click and subscribe to the RU counters list and then test again:

https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters


https://github.com/uBlockOrigin/uAssets/issues/14112#issuecomment-1193288142

**Comment by MasterKia** [comment]
> - [X] I verified that the issue has not already been reported (use this button to find out)
> - [X] I did not answer truthfully to **all** the above checkpoints

Please read and follow the Prerequisites instead of blindly ticking them.

**Comment by dimisa-RUAdList** [comment]
For Firefox browsers, in addition to [Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters), you will need to install [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor), for Firefox: 103 - [scriptlet-doctor-quantum](https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.5/scriptlet-doctor-quantum-1.2.5.xpi).
