### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by MishyMish19** [uBlockOrigin/uAssets#14219]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Describe the issue

getting leftover ads making my music pause and not play the next song

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80301
  cosmetic: 45098
  scriptlet: 17532
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68901-51, 3d.22h.13m
    easyprivacy: 27458-123, 3d.22h.12m
    plowe-0: 3640-777, 3h.44m
    ublock-abuse: 76-0, 20h.15m
    ublock-badware: 4221-92, 3d.22h.11m
    ublock-filters: 32336-114, 3d.22h.10m
    ublock-privacy: 230-3, 20h.14m
    ublock-quick-fixes: 347-27, 1d.17m
    ublock-unbreak: 1851-42, 3d.22h.9m
    urlhaus-1: 5269-0, 1d.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 685 ms (selfie)
  maxAssetCacheWait: 213 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    doubleclick.net: 21
    scdn.co: 7
```
</details>

**Comment by okiehsch** [comment]
See #14231

**Comment by pootzah** [comment]
I confirm this started happening for me as well in the past ~3 days.
