### ISSUE TITLE
sinoptik.ua: ads

### ISSUE THREAD

**Issue by ieroglif** [uBlockOrigin/uAssets#14218]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sinoptik.ua/`

### Category

ads

### Describe the issue

Ads reappeared recently, previously there were none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Opera Snapshot_2022-08-03_003237_sinoptik ua](https://user-images.githubusercontent.com/9120600/182477339-bb0aa6a2-3a16-43e9-88de-3bc898ec0906.png)
![Opera Snapshot_2022-08-03_003309_sinoptik ua](https://user-images.githubusercontent.com/9120600/182477343-a5624b32-37c0-4b5d-95ba-ca10787d2136.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 98266
  cosmetic: 67162
  scriptlet: 17558
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 40342-9, 3m
  default: 
    user-filters: 0-0, never
    easylist: 69063-66, 3m
    easyprivacy: 27478-223, 3m
    plowe-0: 3640-782, 3m
    ublock-abuse: 76-1, 3m
    ublock-badware: 4171-92, 3m
    ublock-filters: 32425-151, 3m
    ublock-privacy: 230-3, 3m
    ublock-quick-fixes: 344-55, 3m
    ublock-unbreak: 1851-42, 3m
    urlhaus-1: 4957-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 825 ms (selfie)
  maxAssetCacheWait: 380 ms
popupPanel: 
  blocked: 23
  no-remote-fonts: true
  blockedDetails: 
    adpartner.pro: 1
    adtelligent.com: 2
    doubleclick.net: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gstatic.com: 3
    mgid.com: 1
    rcvlink.com: 5
    rcvlinks.com: 1
    ukr.net: 4
    yadro.ru: 1
```
</details>

**Comment by krystian3w** [comment]
Check after purge all cache:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2193

**Comment by dimisa-RUAdList** [comment]
@ieroglif 
You need to do this:
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
>
