### ISSUE TITLE
[nsfw] attvideo.filmscomplets.org: breakage

### ISSUE THREAD

**Issue by navkb** [uBlockOrigin/uAssets#14215]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://attvideo.filmscomplets.org/video/DMJEF0GQVzY_cewek-cantik-ini-di-tatto-bagian-ini-langsung-muncrat-tak-berdaya-tatto-di-miss-v.html`

### Category

breakage

### Describe the issue

Video doesn't play on the website 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 81445
  cosmetic: 26819
  scriptlet: 17545
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33113-332, 2d.6h.59m
    ublock-badware: 4224-0, 2d.6h.58m
    ublock-privacy: 241-1, 4d.3h.24m
    ublock-abuse: 76-0, 4d.3h.12m
    ublock-unbreak: 1869-0, 2d.6h.57m
    adguard-mobile: 8021-28, 2d.7h
    easylist: 68907-25082, 2d.6h.56m
    easyprivacy: 27463-590, 2d.5h.28m
    urlhaus-1: 4957-0, 23m
    plowe-0: 3640-142, 9d.7h.31m
    ublock-quick-fixes: 360-0, 24m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 620 ms (selfie)
  maxAssetCacheWait: 300 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    addthis.com: 1
    alternativemgate.com: 5
    arabdevastatingpatty.com: 2
    glimtors.net: 4
    glizauvo.net: 1
    googlesyndication.com: 1
    lowlatiasan.com: 4
    rndskittytor.com: 2
    variouscreativeformats.com: 1
    yandex.ru: 3
```
</details>

**Comment by ghajini** [comment]
a site issue, even without ublock origin, there is no video displayed
