### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by Wolfien75** [uBlockOrigin/uAssets#14225]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://e.mail.ru/`

### Category

ads

### Describe the issue

For the first time, ads on this website was invisible, but after several days the ads start showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/110527469/182559443-13c8e56a-6a30-4e42-97d4-4d859d128c71.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 121463
  cosmetic: 153717
  scriptlet: 35478
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55518-366, 1m
    adguard-generic: 66477-5466, never
    adguard-mobile: 8031-326, never
    fanboy-thirdparty_social: 68-0, 1m
    ublock-annoyances: 4515-158, 1m
  default: 
    user-filters: 19-1, never
    RUS-0: 40342-9, 1m
    easylist: 69065-106, 1m
    easyprivacy: 27478-312, 1m
    plowe-0: 3640-784, 1m
    ublock-abuse: 76-1, 1m
    ublock-badware: 4171-92, 1m
    ublock-filters: 32425-519, 1m
    ublock-privacy: 230-3, 1m
    ublock-quick-fixes: 344-55, 1m
    ublock-unbreak: 1851-44, 1m
    urlhaus-1: 4861-0, 1m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 858 ms (selfie)
  maxAssetCacheWait: 422 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    mail.ru: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/14206

Force update the filter lists
