### ISSUE TITLE
mail.aol.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#14227]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.aol.com/webmail-std/en-us/suite`

### Category

ads

### Describe the issue

pop up ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/182572708-c666ab57-515f-47c5-9a82-47c6cc4479b1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 105
filterset (summary): 
  network: 88386
  cosmetic: 166404
  scriptlet: 25592
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9896-4, 1d.21h.39m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 1d.21h.38m
    adguard-annoyance: 55396-427, 1d.21h.39m
    fanboy-annoyance: 77368-3300, 1d.21h.39m
    ublock-annoyances: 4503-220, 1d.21h.38m
  default: 
    user-filters: 12-0, never
    easylist: 68946-107, 1d.21h.39m
    easyprivacy: 27465-221, 1d.21h.39m
    ublock-abuse: 76-0, 1d.21h.38m
    ublock-badware: 4221-90, 1d.21h.38m
    ublock-filters: 32407-603, 1d.21h.38m
    ublock-privacy: 230-10, 1d.21h.38m
    ublock-quick-fixes: 347-66, 21h.2m
    ublock-unbreak: 1851-47, 1d.21h.38m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 15 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 956 ms (selfie)
  maxAssetCacheWait: 614 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    aol.com: 2
    oath.com: 2
    yahoo.com: 18
    yimg.com: 4
```
</details>

**Comment by MasterKia** [comment]
I think this counts as self-promotion (ads for AOL product on `mail.aol.com`) and we don't block self-promotions.

**Comment by 3xploiton3** [comment]
> I think this counts as self-promotion (ads for AOL product on `mail.aol.com`) and we don't block self-promotions. Similar if ProtonMail advertises ProtonVPN on their mail site.

but this very annoying when start open email,

**Comment by krystian3w** [comment]
If lock scroll then can by blocked in uBo Annoyances to reduce breakage by use: Fanboy Annoyances

Or waiting if AdGuard Annoyances cover pop-up with compatible filters.

**Comment by MasterKia** [comment]
> very annoying when start open email

Does it happen everytime you open an email?
