### ISSUE TITLE
[nsfw] koushoku.org: popups

### ISSUE THREAD

**Issue by AsianPutin** [uBlockOrigin/uAssets#14220]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://koushoku.org/`

### Category

popups

### Describe the issue

Just like nhentai, popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 79509
  cosmetic: 45134
  scriptlet: 17558
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69021-51, 12h.24m
    easyprivacy: 27474-123, 12h.24m
    plowe-0: 3639-777, 12h.24m
    ublock-abuse: 76-0, 12h.23m
    ublock-badware: 4171-92, 12h.23m
    ublock-filters: 32425-122, 12h.23m
    ublock-privacy: 230-3, 12h.23m
    ublock-quick-fixes: 363-73, 12h.23m
    ublock-unbreak: 1851-42, 12h.23m
    urlhaus-1: 4401-0, 12h.23m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1302 ms (selfie)
  maxAssetCacheWait: 547 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    realsrv.com: 2
```
</details>

**Comment by ghajini** [comment]
test(put in `my filters`)
`koushoku.org##+js(aost, document.createElement, )`

&report if any breakages
