### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by LenmonZ** [uBlockOrigin/uAssets#14222]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kimcartoon.li/Cartoon/Beavis-and-Butt-Head/Season-03-Episode-002?id=12941`

### Category

detection

### Describe the issue

I was using Ublocker to watch this for a few days and out of nowhere, the Adblocker started being detected.
I did some googling and came across some extra extensions like the Nano and Ad-killer but they both failed to work. I turned those off purged my caches and then updated and tried again with no luck. 

I was able to find a solution, I turned off the easy list filter and replaced it with Adgaurd Base and just blocked the pop-ups using the button's via the extension pop-up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110511253/182511203-4ed635f0-bc8d-4930-ad50-75a34c9d6401.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80013
  cosmetic: 45136
  scriptlet: 17558
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69064-51, 1m
    easyprivacy: 27478-123, 1m
    plowe-0: 3640-777, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4171-92, 1m
    ublock-filters: 32425-123, 1m
    ublock-privacy: 230-3, 1m
    ublock-quick-fixes: 344-55, 1m
    ublock-unbreak: 1851-42, 1m
    urlhaus-1: 4861-0, 1m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 4479 ms (selfie)
  maxAssetCacheWait: 497 ms
popupPanel: 
  blocked: 19
  no-popups: true
  blockedDetails: 
    kimcartoon.li: 3
    bebi.com: 1
    canangalaities.com: 1
    coninemelior.com: 1
    eehuzaih.com: 1
    fstats.xyz: 1
    google-analytics.com: 1
    hhklc.com: 1
    propellerads.com: 1
    pubmatic.com: 1
    sharethis.com: 3
    twitter.com: 1
    washdaycalmly.com: 1
    yandex.ru: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists it got fixed already
