### ISSUE TITLE
zgbk.com: nuisance

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#14233]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zgbk.com/ecph/words?SiteID=1&ID=84858&Type=bkzyb&SubID=51673`

### Category

nuisance

### Describe the issue

Web page content cannot be copied using right-click and shortcut keys

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 106899
  cosmetic: 123880
  scriptlet: 22104
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1927-0, 23h.7m
    block-lan: 43-0, 27d.22h.44m
    fanboy-annoyance: 76079-239, 9d.22h.28m
    ublock-annoyances: 4515-70, 39m
  default: 
    user-filters: 0-0, never
    CHN-0: 28577-91, 40m
    easylist: 69080-74, 38m
    easyprivacy: 27478-147, 37m
    plowe-0: 3639-779, 23h.10m
    ublock-abuse: 76-0, 4d.22h.40m
    ublock-badware: 4171-92, 36m
    ublock-filters: 32425-167, 35m
    ublock-privacy: 226-13, 4d.22h.39m
    ublock-quick-fixes: 354-73, 23h.9m
    ublock-unbreak: 1851-46, 34m
    urlhaus-1: 4401-0, 23h.8m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1983 ms (selfie)
  maxAssetCacheWait: 628 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    zgbk.com: 1
```
</details>

**Comment by DeepChirp** [comment]
Currently, the website prevents users from selecting or copying content, and the original rules do not seem to be working. Example link: `https://www.zgbk.com/ecph/words?SiteID=1&ID=3jq7Pm&SubID=52017`

**Comment by DeepChirp** [comment]
After updating the filter rules, I am indeed able to select and copy the text. However, the copied content appears as garbled text. I apologize that I am unable to check the source code right now.

**Comment by stephenhawk8054** [comment]
That is the source text. You can check in the browser devtools. However, you need their fonts to view those texts: `https://www.zgbk.com/ecph/api/content/preview-font/3jq7Pm?v=1642646165000&scope=body`
