### ISSUE TITLE
UB does not block publicity

### ISSUE THREAD

**Issue by angelog0** [uBlockOrigin/uAssets#14230]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

.

### Describe the issue

Since also Brave has this issue you can read the issue I flagged them: https://github.com/brave/brave-browser/issues/24372

### Screenshot(s)

.

### uBlock Origin version

the last

### Browser name and version

Chromium: the last

### Settings

None

### Notes

.

**Comment by krystian3w** [comment]
You enabled EasyList Italy supplement if page has real Italian language?

**Comment by krystian3w** [comment]
https://github.com/easylist/easylistitaly/commit/314d2588f74bb91ea6f7067e7d4c1375e49a5d5f

**Comment by angelog0** [comment]
Yesterday it was better... This morning still the full issue :-(

**Comment by Khrin** [comment]
> Yesterday it was better... This morning still the full issue :-(

Aggiorna i filtri, lo puoi fare dalle impostazioni di ublock origin.

**Comment by krystian3w** [comment]
Also share URLs/domains where banners are visible. Don't forget protect click on links by around: \`(URL/domain)\`.
