### ISSUE TITLE
theappstore.org: nuisance

### ISSUE THREAD

**Issue by NJSAUND** [uBlockOrigin/uAssets#14237]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://theappstore.org/search.php?search=bust-a-mve&platform=software`

### Category

nuisance

### Describe the issue

blocks and blurs the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80013
  cosmetic: 45017
  scriptlet: 17473
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 2h.2m
  default: 
    user-filters: 2-0, never
    easylist: 69062-51, 22h.32m
    easyprivacy: 27474-123, 22h.31m
    plowe-0: 3640-779, 8d.21h.26m
    ublock-abuse: 76-0, 8d.21h.25m
    ublock-badware: 4170-92, 22h.35m
    ublock-filters: 32425-123, 22h.34m
    ublock-privacy: 225-3, 9d.1h.34m
    ublock-unbreak: 1851-42, 22h.33m
    urlhaus-1: 4957-0, 22h.30m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 23 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 562 ms (selfie)
  maxAssetCacheWait: 301 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 2
```
</details>

**Comment by huyszn** [comment]
The search function on the site is not working. When I disable uBO, searching works.
