### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by 188227495** [uBlockOrigin/uAssets#14232]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

breakage

### Describe the issue

not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 97916
  cosmetic: 55408
  scriptlet: 17650
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    CHN-0: 28514-91, 1d.9h.31m
    easylist: 68994-74, 1d.9h.30m
    easyprivacy: 27460-147, 4d.1h.20m
    plowe-0: 3639-779, 3d.21h.15m
    ublock-abuse: 76-0, 6d.8h.50m
    ublock-badware: 4211-92, 4d.1h.19m
    ublock-filters: 32342-138, 4d.1h.18m
    ublock-privacy: 225-3, 6d.8h.49m
    ublock-quick-fixes: 344-9, 6h.21m
    ublock-unbreak: 1851-43, 4d.1h.17m
    urlhaus-1: 4861-0, 6h.22m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 330 ms (selfie)
  maxAssetCacheWait: 143 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    bilibili.com: 30
    hdslb.com: 1
```
</details>

**Comment by ghajini** [comment]
> breakage
> ### Describe the issue
> 
> not work

can you explain it better?

**Comment by JobcenterTycoon** [comment]
When its the same like https://github.com/uBlockOrigin/uAssets/issues/14236 Force update the filter lists https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches and test again
