### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by Lord-Benendearu** [uBlockOrigin/uAssets#14235]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kimcartoon.li/Cartoon/Big-Bad-Beetleborgs/Episode-004-The-Ghost-Is-Toast?id=52693`

### Category

detection

### Describe the issue

After watching a video in Kimcartoon for about half a minute, the video is interrupted and replaced with a message telling me to turn Adblock off. This problem seems to be very recent, as I could still use the site without issues a week ago.

I also tried the above steps on my laptop, with the same results.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Schermafbeelding 2022-08-03 153127](https://user-images.githubusercontent.com/110545068/182623653-1b28e9d2-071e-4c69-8a54-a43278c7e2c3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80802
  cosmetic: 46791
  scriptlet: 17537
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33097-144, 2m
    ublock-badware: 4175-0, 2m
    ublock-privacy: 246-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1864-0, 2m
    ublock-quick-fixes: 349-1, 2m
    easylist: 69080-597, 1m
    easyprivacy: 27478-581, 1m
    urlhaus-1: 4919-0, 1m
    plowe-0: 3640-3, 1m
    NLD-0: 2445-29, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 276 ms (selfie)
  maxAssetCacheWait: 135 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    kimcartoon.li: 3
    bebi.com: 1
    canangalaities.com: 1
    coninemelior.com: 1
    cookiesstandee.com: 1
    eehuzaih.com: 1
    google-analytics.com: 1
    hhklc.com: 2
    propellerads.com: 1
    pubmatic.com: 1
    washdaycalmly.com: 2
```
</details>

**Comment by SquitterYeen** [comment]
Started having this issue yesterday, made an account just to report it. This site has a history of doing this and is nearly impossible to use without a blocker. UBlock was the best until this occurred.

**Comment by JobcenterTycoon** [comment]
@SquitterYeen just force update the filter lists it got fixed 19 hours ago

**Comment by SquitterYeen** [comment]
> 

Confirmed @JobcenterTycoon , it seems the team is quick on the draw! 💥🔫
