### ISSUE TITLE
rojadirectatv.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1423]
URL(s) where the issue occurs

`http://www.rojadirectatv.tv/directv-sports-plus.php`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@diaux

**Comment by diaux** [comment]
Thanks for reporting. I do not see any Anti-Adblock using ABP + EasyList + EasyPrivacy + EasyList Spanish

**Comment by diaux** [comment]
I looked around and I have now found it on another website, pirlotv.es - loading frame from same source livesports.pw - I'll add this filter to EasyList Spanish

**Comment by diaux** [comment]
ABP does not support $redirect so I added it in as whitelisted (Anti-Adblock) in EasyList Spanish. Thanks.
@xDarkARG @mapx-

**Comment by mapx-** [comment]
@diaux  if you want, you can maintain a sublist with uBo spcific filters
see (Sub-filter lists) https://github.com/gorhill/uBlock/releases

**Comment by diaux** [comment]
@mapx Thanks much, it looks interesting, but I will have to pass for now. EasyList Spanish is already giving me lots of work, and I'm starting up EasyList Portuguese, so I don't have any extra time. Perhaps in some time from now.

**Comment by KiLL4FuNK** [comment]
ADS

`http://www.rojadirecta.fr/`
`http://www.tarjetarojatvonline.com/`
`http://www.rojadirectatv.live/`

**Comment by KiLL4FuNK** [comment]
Pop-up

`http://www.rojadirectatv.biz/espn2.php`

**Comment by lain566** [comment]
Popup
`http://rojadirectatv.tv/`

**Comment by KiLL4FuNK** [comment]
PLAY Popup

`http://www.rojadirecta.today/canal-5.php`
