### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by sean956** [uBlockOrigin/uAssets#14236]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

breakage

### Describe the issue

推广的条目下所有视频疯狂闪烁，显示不正常

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![SC_2022-08-03_22-29-47](https://user-images.githubusercontent.com/63991395/182634446-12586614-c680-4ee6-b08c-3b9ec0a0fba8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 193337
  cosmetic: 142390
  scriptlet: 36120
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55460-86, 1d.15m
    adguard-generic: 66471-732, 1d.17m
    adguard-mobile: 8031-67, 1d.17m
    adguard-spyware: 28367-1393, 1d.17m
    adguard-spyware-url: 687-0, 1d.17m
    block-lan: 43-0, 1d.17m
    curben-phishing: 54769-0, 1d.17m
    curben-pup: 183-1, 1d.17m
    ublock-annoyances: 4515-189, 1d.17m
  default: 
    user-filters: 9-0, never
    CHN-0: 28527-91, 1d.2h
    easylist: 69021-1117, 1d.1h.57m
    easyprivacy: 27474-10122, 1d.1h.56m
    plowe-0: 3639-956, 1d.1h.55m
    ublock-abuse: 76-0, 1d.1h.53m
    ublock-badware: 4170-319, 1d.1h.51m
    ublock-filters: 32418-3866, 1d.1h.50m
    ublock-privacy: 230-37, 1d.1h.49m
    ublock-quick-fixes: 344-66, 1h.14m
    ublock-unbreak: 1852-104, 1d.1h.47m
    urlhaus-1: 4919-2, 1h.12m
filterset (user): [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 391 ms (selfie)
  maxAssetCacheWait: 524 ms
popupPanel: 
  blocked: 66
  blockedDetails: 
    bilibili.com: 65
    hdslb.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches and test again

**Comment by sean956** [comment]
非常感谢你！已解决

JobcenterTycoon ***@***.***> 于2022年8月3日周三 23:43写道：

**Comment by sean956** [comment]
在我再次尝试强制更新每一条规则后，可以正常显示了 XD

Sean Lee ***@***.***> 于2022年8月3日周三 23:56写道：

**Comment by sean956** [comment]
Emmm...Sorry!我再次刷新后再次显示不正常了。如果使用adguard，就是正常的。

JobcenterTycoon ***@***.***> 于2022年8月3日周三 23:49写道：

**Comment by JobcenterTycoon** [comment]
What is broken?

**Comment by MichaelPan1026** [comment]
> What is broken?

On the [main](https://www.bilibili.com) page of the site , all the buttons in the top right corner of the site are gone, and it's all useful buttons about 'me'.
![ublock_issue](https://user-images.githubusercontent.com/26241105/195241826-7309da33-8183-4475-bc96-aaee81c806d6.png)

**Comment by mapx-** [comment]
@MichaelPan1026 provide the info from support tab (options, dashboard, support tab) => **Troubleshooting Information**

**Comment by mapx-** [comment]
Are you logged in when testing ?

**Comment by MichaelPan1026** [comment]
> Are you logged in when testing ?

The issue is the same whether I'm logged in or not.
