### ISSUE TITLE
efahrer.chip.de: ads

### ISSUE THREAD

**Issue by MartinKurtz** [uBlockOrigin/uAssets#14246]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://efahrer.chip.de/news/4500-kilometer-mit-dem-e-auto-in-den-urlaub-die-stromkosten-sind-unglaublich_108793`

### Category

ads

### Describe the issue

ad still there

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82302
  cosmetic: 48850
  scriptlet: 17513
  html: 715
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33097-89, 16h.16m
    ublock-badware: 4175-0, 16h.15m
    ublock-privacy: 246-0, 2d.21h.29m
    ublock-abuse: 76-0, 2d.21h.28m
    ublock-unbreak: 1864-0, 16h.14m
    easylist: 69091-601, 16h.13m
    easyprivacy: 27478-590, 16h.12m
    urlhaus-1: 4957-0, 1d.11h.18m
    plowe-0: 3642-3, 6d.15h.57m
    DEU-0: 5894-2, 1d.11h.17m
    ublock-quick-fixes: 315-1, 1d.11h.19m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 256 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    chip.de: 6
    2mdn.net: 1
    adobedtm.com: 2
    bf-ad.net: 3
    bf-tools.net: 1
    cleverpush.com: 2
    dl8.me: 4
    facebook.net: 1
    googlesyndication.com: 1
    iocnt.net: 1
    outbrain.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
I see no ads
