### ISSUE TITLE
masterduelmeta.com: nuisance

### ISSUE THREAD

**Issue by ollyyyyyy** [uBlockOrigin/uAssets#14247]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.masterduelmeta.com/tier-list/deck-types/Ancient%20Gear`

### Category

nuisance

### Describe the issue

note: there is a previous ticket for this issue, but it has been marked as closed (and the site has since updated to work around the solution in the ticket) . if this is a violation of the second checkbox, i'm very sorry.

site has an anti-adblocker popup that somehow dodges the picker, and the site owners seem to be updating the code every couple months to work around any filters that still manage to get it. 

popup itself is a basic "whitelist us or pay for our no ad subscription", blocks scrolling but can be closed with the "x" in the top right

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80073
  cosmetic: 45154
  scriptlet: 17547
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-9, never
    easylist: 69065-51, 1d.2h.24m
    easyprivacy: 27478-123, 1d.2h.23m
    plowe-0: 3639-777, 2d.22h.20m
    ublock-abuse: 76-0, 3d.20h.48m
    ublock-badware: 4171-92, 1d.2h.22m
    ublock-filters: 32407-123, 2d.18h.19m
    ublock-privacy: 226-3, 3d.20h.47m
    ublock-quick-fixes: 344-40, 10h.22m
    ublock-unbreak: 1851-42, 2d.18h.18m
    urlhaus-1: 4919-0, 10h.21m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 266 ms (selfie)
  maxAssetCacheWait: 236 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
```
</details>

**Comment by okiehsch** [comment]
Do I need to be logged in for the anti-adblock message?
I clicked on quite a few cards and can't reproduce.

**Comment by ollyyyyyy** [comment]
message appears for me when not logged in. doesn't appear on homepage, but appears on all subsequent pages i can find (see screenshot). 
![image](https://user-images.githubusercontent.com/110602328/182827078-1fc86244-f9c2-401e-a376-26c9d3f04440.png)

**Comment by okiehsch** [comment]
Hm, I can't reproduce, I tried with Edge too with the same result.
Maybe someone else can reproduce.

**Comment by MasterKia** [comment]
> site owners seem to be updating the code every couple months to work around any filters that still manage to get it.

Some sites update their code every _day_ to achieve that.

**Comment by ollyyyyyy** [comment]
at that point you've got to imagine it's easier to simply not fill the site with obtrusive ads

**Comment by MasterKia** [comment]
What do you mean? :p

**Comment by ollyyyyyy** [comment]
updating the codebase daily for the sole purpose of annoying users seems a lot harder than just not designing the website to annoy users

**Comment by MasterKia** [comment]
I see. And yet some sites still do.

Like changing sidebar to si1deba1r or top-links to top2-links and etc.

**Comment by ollyyyyyy** [comment]
yes, i do

**Comment by ollyyyyyy** [comment]
okay, issue has fixed itself somehow. it just works, i guess?
