### ISSUE TITLE
americanexpress.com: breakage

### ISSUE THREAD

**Issue by jcbeck37** [uBlockOrigin/uAssets#14249]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.americanexpress.com/en-us/account/login`

### Category

breakage

### Describe the issue

If you open the Rewards page, something is blocked, and an endless loop of XHR requests are made to https://loyalty-1.americanexpress.com/home/report/errors. I believe what is blocked may be this:

https://ds-aksb-a.akamaihd.net/aksb.min.js

But there's also a failed call to 
https://loyalty-1.americanexpress.com/home/report/security/csp-violation

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/2824364/182862235-ef902ece-c1e2-46ec-8b03-19ff359f3410.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 79963
  cosmetic: 45140
  scriptlet: 17513
  html: 714
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 33065-75, 2d.22h.46m
    ublock-badware: 4174-0, 2d.22h.45m
    ublock-privacy: 241-0, 6d.23h.36m
    ublock-abuse: 76-0, 6d.23h.35m
    ublock-unbreak: 1864-0, 2d.22h.44m
    easylist: 68946-591, 2d.22h.43m
    easyprivacy: 27465-580, 2d.22h.42m
    urlhaus-1: 4919-0, 14h.37m
    plowe-0: 3638-3, 5d.10h.53m
    ublock-quick-fixes: 354-0, 10h.36m
filterset (user): [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 501 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    americanexpress.com: 6
    adobedtm.com: 1
    aexp-static.com: 1
    demdex.net: 1
    googletagservices.com: 1
    qualtrics.com: 1
```
</details>

**Comment by okiehsch** [comment]
`@@||assets.adobedtm.com/*-libraryCode_$script,domain=global.americanexpress.com`
seems to work for me.

**Comment by okiehsch** [comment]
@ryanbr
