### ISSUE TITLE
cataz.net: nuisance

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#14241]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cataz.net/watch-tv/watch-90-day-fiance-uk-2022-84897.8802996`

### Category

nuisance

### Describe the issue

Banner popups up on each stream page "Sharing is caring.
It's the biggest motivation to help us to make the site better."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/17252998/182709770-de3255cc-af05-485a-9a6f-581e1a20b57f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 91370
  cosmetic: 156469
  scriptlet: 21543
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/fanboy-cookiemonster.txt: 36540-78, 13d.1h.57m
    adguard-annoyance: 55072-2549, 16d.5h.19m
    fanboy-annoyance: 75627-37084, 13d.1h.56m
    fanboy-cookiemonster: 36540-36540, 13d.1h.55m
  default: 
    user-filters: 48-0, never
    easylist: 68557-101, 16d.5h.53m
    easyprivacy: 27423-227, 16d.5h.50m
    plowe-0: 3646-781, 23d.29m
    ublock-abuse: 75-0, 23d.27m
    ublock-badware: 4224-95, 16d.5h.52m
    ublock-filters: 32218-496, 16d.5h.54m
    ublock-privacy: 226-11, 23d.28m
    ublock-quick-fixes: 251-1, 13d.1h.54m
    ublock-unbreak: 1837-49, 16d.5h.51m
    urlhaus-1: 5283-0, 13d.1h.53m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7343 ms (selfie)
  maxAssetCacheWait: 2340 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    addthis.com: 1
    facebook.com: 1
    googletagmanager.com: 2
    soaheeme.net: 1
    zdassets.com: 1
```
</details>

**Comment by krystian3w** [comment]
```css
###modalshare
##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
```

off-topic, page froze after open devtools at debugger - maybe possible safe unlock use.
