### ISSUE TITLE
glassdoor.com: nuisance

### ISSUE THREAD

**Issue by g0tsteve** [uBlockOrigin/uAssets#14252]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.glassdoor.com/Overview/Working-at-Hampton-Roads-Communications-Technologies-EI_IE1532139.11,52.htm`

### Category

nuisance

### Describe the issue

Cannot scroll

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 82011
  cosmetic: 43832
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-101, never
    plowe-0: 3639-784, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-3, never
    ublock-filters: 31779-96, never
    ublock-privacy: 222-0, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-30, never
    urlhaus-1: 7285-0, never
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2377 ms
  maxAssetCacheWait: 37 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    d2k1bn3ko1qk4.cloudfront.net: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    indexww.com: 1
```
</details>

**Comment by Procyon-b** [comment]
When revisiting the site I get an overlay asking to subscribe with an email address.
The overlay can be hidden and the scrolling reenabled with:
```
glassdoor.*###HardsellOverlay
glassdoor.*##body[style*="overflow"]:style(overflow-y: auto !important; height: auto !important; margin: unset !important;)
glassdoor.*##+js(set, window.scrollTo, noopFunc)
```

**Comment by Procyon-b** [comment]
There is also the possibility to block this script instead. But I don't know if this breaks something else.
```
||glassdoor.com/garnish/static/js/gd-user-hardsell-overlay.bundle.js$domain=glassdoor.*
```

**Comment by ghajini** [comment]
lack of feedback
