### ISSUE TITLE
[nsfw] mybeautyland.shop: ads

### ISSUE THREAD

**Issue by SaeedFarrahi** [uBlockOrigin/uAssets#14259]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mybeautyland.shop/ab2new29/?ccid=IR&campaignid=5707208&zoneid=4923326&clickid=579310091292123783&cost=0.000090&countryname=IR&carrier=?&rdk=rk3`

### Category

ads

### Describe the issue

I use uBlockOrigin to avoid stuff like this!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/110657689/183020273-729e2633-e325-4df8-ba10-5166a11be65a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80167
  cosmetic: 45165
  scriptlet: 17551
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33125-94, 10h.38m
    ublock-badware: 4175-0, 10h.39m
    ublock-privacy: 242-0, 5d.17h.19m
    ublock-abuse: 76-0, 4d.21h.49m
    ublock-unbreak: 1864-0, 10h.35m
    easylist: 69167-592, 10h.37m
    easyprivacy: 27481-580, 10h.36m
    urlhaus-1: 4912-0, 23h.59m
    plowe-0: 3641-3, 8d.17h.32m
    ublock-quick-fixes: 354-1, 1d.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 775 ms
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Where do you see that ad, I need a site to reproduce.

**Comment by MasterKia** [comment]
> I use uBlockOrigin _**to avoid stuff like this!**_

> ccid=IR&countryname=IR

Then I suggest to you to "go to uBlock Origin settings => Filter lists tab =>  Regions, languages => Enable the [IRN: PersianBlocker list](https://github.com/MasterKia/PersianBlocker)"

So you won't see stuff like this on Persian websites.

**Comment by gorhill** [comment]
It's a page with only a link and a gif, nothing else -- if we remove these it will be a blank page. Closing as _invalid_.
