### ISSUE TITLE
linkedin.com: breakage

### ISSUE THREAD

**Issue by giovannigf2** [uBlockOrigin/uAssets#14254]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.linkedin.com/feed/`

### Category

breakage

### Describe the issue

Menu bar missing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-08-04 at 15-21-43 Feed LinkedIn](https://user-images.githubusercontent.com/61993240/182935597-43444a71-98d4-4d9b-bfd4-b3550d775e7a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 87364
  cosmetic: 113886
  scriptlet: 19201
  html: 716
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 77756-247, 1m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33072-40, 1m
    ublock-badware: 4175-0, 1m
    ublock-privacy: 246-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1864-0, 1m
    easylist: 69167-619, 1m
    easyprivacy: 27481-580, 1m
    urlhaus-1: 5003-0, 1m
    plowe-0: 3640-3, 1m
    ublock-quick-fixes: 344-1, 1m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 41 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6925 ms (selfie)
  maxAssetCacheWait: 348 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  blockedDetails: 
    linkedin.com: 2
    scorecardresearch.com: 4
```
</details>

**Comment by krystian3w** [comment]
Test without Fanboy's Annoyances.
