### ISSUE TITLE
tutv-gratis.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1425]
URL(s) where the issue occurs

`http://www.tutv-gratis.com/2017/06/discovery-channel-en-vivo-por-internet.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
ADS  @mapx-  `http://www.tutv-gratis.com/2017/11/fox-sports-en-vivo-por-internet.html`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-   `http://www.tutv-gratis.com/2017/11/espn-en-vivo-por-internet.html`  OPCIÓN 2

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-
