### ISSUE TITLE
kijk.nl: detection

### ISSUE THREAD

**Issue by MarcDirven** [uBlockOrigin/uAssets#14262]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kijk.nl/programmas/masterchef-australie/Vx2CuY6YcHb`

### Category

detection

### Describe the issue

Kijk.nl detects an ad blocker (uBlock)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80110
  cosmetic: 45135
  scriptlet: 17593
  html: 715
listset (total-discarded, last updated): 
  default: 
    user-filters: 21251-21, never
    ublock-filters: 33042-21174, 3d.17h
    ublock-badware: 4174-0, 3d.16h.59m
    ublock-privacy: 246-0, 3d.16h.58m
    ublock-abuse: 76-0, 3d.16h.57m
    ublock-unbreak: 1864-0, 3d.16h.56m
    ublock-quick-fixes: 344-1, 14h.11m
    easylist: 68988-591, 3d.16h.54m
    easyprivacy: 27465-580, 3d.16h.53m
    urlhaus-1: 5003-0, 14h.10m
    plowe-0: 3639-3, 3d.16h.51m
filterset (user): [array of 13894 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 466 ms (selfie)
  maxAssetCacheWait: 278 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    newrelic.com: 1
    talpanetwork.com: 2
```
</details>

**Comment by okiehsch** [comment]
It's alreaddy fixed in the regional Dutch list, if you enable it the video should play without issue provided you use a Dutch IP.

**Comment by MarcDirven** [comment]
You mean NLD: EasyDutch? Just enabled it, same issue.

**Comment by MarcDirven** [comment]
Oh never mind. Brainfart: my AdBlock was still turned off.
