### ISSUE TITLE
nartag.com: detection

### ISSUE THREAD

**Issue by konsowsz** [uBlockOrigin/uAssets#14260]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nartag.com/`

### Category

detection

### Describe the issue

Nartag detect ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 84725
  cosmetic: 31446
  scriptlet: 17800
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33187-381, 2d.14h.8m
    ublock-badware: 4173-0, 2d.14h.7m
    ublock-privacy: 246-1, 2d.14h.6m
    ublock-abuse: 76-0, 2d.14h.5m
    ublock-unbreak: 1870-0, 2d.14h.4m
    ublock-quick-fixes: 344-1, 11h.34m
    adguard-mobile: 8031-167, 2d.14h.13m
    easylist: 69062-25158, 2d.14h.2m
    easyprivacy: 27474-606, 2d.14h.1m
    urlhaus-1: 5003-0, 11h.32m
    plowe-0: 3640-3, 2d.13h.59m
    spa-0: 3898-220, 2d.14h.13m
    spa-1: 4580-186, 2d.14h.13m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1440 ms (selfie)
  maxAssetCacheWait: 259 ms
popupPanel: 
  blocked: 66
  no-cosmetic-filtering: true
  no-large-media: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    nartag.com: 58
    googlesyndication.com: 5
    googletagmanager.com: 2
    youtube.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists it got fixed here https://github.com/uBlockOrigin/uAssets/commit/a434ea544ceae15fdeddce3d88e139604089b0cb
