### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by omegadmm** [uBlockOrigin/uAssets#14269]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=OKmL2nZsM9g`

### Category

breakage

### Describe the issue

Using Firefox with no settings changed.
Load Youtube.com as I do every day.
Try to watch video; normally video plays without issue, now it does not.
Try Edge, video plays. Try Firefox again with with Ublock Origins disabled for that page; video works. Re-enable UBO; video might play if the ad cycle is clear that time around. 
Defining Ad Cycle: By default youtube videos don't always play an ad, but most of the time they do. 
Usually starting with an ad, seems Youtube is looking for a completion of the loading of the ad, UBO seemingly prevents this and Youtube videos refuse to load even after multiple refreshes until I disable UBO and refresh again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80180
  cosmetic: 45155
  scriptlet: 17525
  html: 713
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33083-37, 2d.2h.16m
    ublock-badware: 4175-1, 2d.2h.15m
    ublock-privacy: 240-0, 12d.10h.12m
    ublock-abuse: 76-0, 12d.10h.11m
    ublock-unbreak: 1864-0, 2d.2h.14m
    easylist: 69080-595, 2d.2h.13m
    easyprivacy: 27478-580, 2d.2h.12m
    urlhaus-1: 5003-0, 22h.52m
    plowe-0: 3640-3, 12d.10h.10m
    ublock-quick-fixes: 360-41, 22h.53m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 637 ms (selfie)
  maxAssetCacheWait: 584 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    youtube.com: 16
    doubleclick.net: 2
    google.com: 1
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
