### ISSUE TITLE
Video Playback issue after 7 - 10 sec @ CHIP.de

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#1426]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.chip.de`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

all Videos from chip.de playback issue after 7-10 sec!

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [Firefox 59 beta 5]
- uBlock Origin version: [1.15.0]

### Settings

uBO's default settings

- [List here all the changes you made to uBO's default settings]

### Notes
standart Filterlist´s are up 2 date!

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
@gorhill  the video disappears due to:
`||svonm.com/hd-main.js$script,redirect=hd-main.js,domain=chip.de`

**Comment by okiehsch** [comment]
`||svonm.com/hd-main.js$script,redirect=hd-main.js,domain=chip.de` works as expected, it disables the pre-roll ads, which in turn leads to the video stopping after 10 seconds.
That was fixed by `chip.de##script:inject(golem.de.js)` and this is no longer sufficient at `chip.de`.

**Comment by okiehsch** [comment]
Does
`chip.de##script:inject(setTimeout-defuser.js, (), 15000)`
work for you?

**Comment by akks1981** [comment]
i tested 20 videos and it seems to work! Thx for the help :)
