### ISSUE TITLE
animego.org: ads

### ISSUE THREAD

**Issue by BigArty** [uBlockOrigin/uAssets#14266]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animego.org/anime/sozdannyy-v-bezdne-163`

### Category

ads

### Describe the issue

Ad still shows in video player

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80739
  cosmetic: 45158
  scriptlet: 17570
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 69217-51, 4h.51m
    easyprivacy: 27487-123, 4h.50m
    plowe-0: 3639-777, 4d.12h.54m
    ublock-abuse: 76-0, 4d.12h.52m
    ublock-badware: 4171-92, 4h.49m
    ublock-filters: 32381-120, 4h.48m
    ublock-privacy: 235-3, 4d.12h.48m
    ublock-quick-fixes: 348-4, 46m
    ublock-unbreak: 1851-42, 4h.47m
    urlhaus-1: 5437-0, 45m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 117 ms (selfie)
  maxAssetCacheWait: 99 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adprofits.ru: 1
    aniboom.one: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    jsdelivr.net: 2
    mail.ru: 1
    serving-sys.ru: 1
    yandex.ru: 7
```
</details>

**Comment by JobcenterTycoon** [comment]
I just get a blank page

**Comment by gorhill** [comment]
The page loads fine when using a VPN, I used a server in Estonia.

If there are ads in there, I don't which they are. Please provide screenshot of the page with ads highlighted.

**Comment by dimisa-RUAdList** [comment]
This is a Russian site, the rules for it are contained in RU AdList.

**Comment by BigArty** [comment]
![image](https://user-images.githubusercontent.com/25989268/183152226-ca890ad9-245c-4f0b-a93a-c860ab4f2baa.png)
![image](https://user-images.githubusercontent.com/25989268/183152342-3f9399f2-385d-490b-9f9f-3334cd6d4106.png)
Here is screenshots of Lost Arc ad in the player. But yes, I'm dumb. I didn't saw Ru AdList. I'm sorry to bother.
