### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by pootzah** [uBlockOrigin/uAssets#14261]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/album/2mEAk0qqVLDbmRLtsuwX7E`

### Category

breakage

### Describe the issue

I see there are similar issues opened, but all are already closed.
I'm up to date with FF & UBlock versions and purged & updated filters.
**Issue still happens**:
- after an ad is blocked, playback is blocked as well.
-- sometimes if I just click <play> on a song, it can start again
-- otherwise I need to reload the browser window.
Tried updates / restarts / everything.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80746
  cosmetic: 45157
  scriptlet: 17560
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33070-40, 39m
    ublock-badware: 4175-0, 39m
    ublock-privacy: 247-0, 39m
    ublock-abuse: 76-0, 39m
    ublock-unbreak: 1865-0, 39m
    ublock-quick-fixes: 345-1, 39m
    easylist: 69219-591, 39m
    easyprivacy: 27490-581, 39m
    urlhaus-1: 5437-0, 39m
    plowe-0: 3640-3, 39m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 381 ms
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    doubleclick.net: 9
    flashtalking.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    scdn.co: 3
    sentry.io: 17
```
</details>

**Comment by okiehsch** [comment]
> I see there are similar issues opened, but all are already closed.

Um, https://github.com/uBlockOrigin/uAssets/issues/14231 is still open.

**Comment by pootzah** [comment]
> > I see there are similar issues opened, but all are already closed.
> 
> Um, #14231 is still open and it "is" your issue.

my bad, got confused by the last 2 comments with the "closed" label near them.
