### ISSUE TITLE
mail.yahoo.com: ads

### ISSUE THREAD

**Issue by Zeno20** [uBlockOrigin/uAssets#14268]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yahoo.com/d/folders/1?.intl=us&.partner=sbc&.lang=en-US&pspid=1197744451&activity=ybar-mail&guce_referrer=aHR0cHM6Ly9hdHQteWFob28uYXR0Lm5ldC8&guce_referrer_sig=AQAAAGEXA2FP6h8n0x4WE2kiX3rzdoGGmrPa2pNEgFWg7gsXr2Fkv2yWRSNe_UANQcUYYW8fjdb80swGrql9GcSDCYDfVUlF-4q7vmENzqiZlbmzZg9UutFrOLTiP40migAnQaU7eHXgyeWOH3wEA6wmKvnOnaxgmBDIduPiGZpCEAWJ`

### Category

ads

### Describe the issue

There is an ad above my emails and they use to disappear and leave no empty block. I tried enabling cosmetic filtering but leaves a big space with ad gone. They don't disappear anymore automatically and i tried adding this in my filter mail.yahoo.com##[href^="https://ad.doubleclick.net/ddm/trackclk"]

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-08-05 at 10-00-54 ngokussj5@bellsouth net - AT T Yahoo Mail](https://user-images.githubusercontent.com/6423622/183094650-44fa340f-1964-45f3-a68a-93a4a9cf1466.png)
![Screenshot 2022-08-05 at 10-11-17 ngokussj5@bellsouth net - AT T Yahoo Mail](https://user-images.githubusercontent.com/6423622/183095267-3bbbf1c3-299c-47a9-bc98-8266d3bc4410.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 97611
  cosmetic: 76636
  scriptlet: 29929
  html: 714
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 66543-5230, 1d.36m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33083-92, 1d.35m
    ublock-badware: 4175-0, 1d.34m
    ublock-privacy: 241-0, 7d.16h.57m
    ublock-abuse: 76-0, 7d.16h.56m
    ublock-unbreak: 1864-0, 1d.33m
    easylist: 69158-604, 1d.32m
    easyprivacy: 27481-580, 1d.31m
    urlhaus-1: 5003-0, 1d.29m
    plowe-0: 3640-3, 20h.28m
    ublock-quick-fixes: 341-0, 1d.30m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 36486 ms (selfie)
  maxAssetCacheWait: 345 ms
popupPanel: 
  blocked: 28
  no-cosmetic-filtering: true
  blockedDetails: 
    yahoo.com: 21
    demdex.net: 1
    doubleclick.net: 1
    scorecardresearch.com: 1
    yimg.com: 4
```
</details>

**Comment by gorhill** [comment]
> `no-cosmetic-filtering: true`

You disabled cosmetic filtering for that site. Re-enabled it, by default it's always enabled.

**Comment by Zeno20** [comment]
Okay after refreshing the ad is gone after re-enabling it. Still getting used to using this i use to use another ad block before sticking to ublock orgin. It has an X on cosmetic filters on every tab i open so didn't know to do that.

**Comment by gorhill** [comment]
> It has a red X on cosmetic filters on every tab i open so didn't know to do that.

This means you have rules to disable cosmetic filters, you can go into _My rules_ pane in the dashboard, and remove rules which look like `no-cosmetic-filtering: ... true`, then click _Save_, then click _Commit_. Be sure you read the documentation before using more advanced features in uBO, by default the no-cosmetic-filtering switch is not shown, so it's something you opted-in to use.
