### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by xproot** [uBlockOrigin/uAssets#14264]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bing.com/search`

### Category

ads

### Describe the issue

**Microsoft Edge** Version 103.0.1264.77 (Official build) (64-bit)

> About "I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers) *"

I am using Privacy Badger and HTTPS Everywhere along with uBO. I've tried disabling all of my extensions except uBO and they still show up. I've tried InPrivate and Google Chrome but they don't show these ads (with or without uBO) probably because im not signed in then?

More oddly, while I was disabling the extensions, if I enabled uBO they'd dissapear, but if I disabled HTTPS Everywhere after that they'd show up.

Ads on Bing while searching.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/49620652/183078418-03c18dad-8e16-4349-bfdd-932e1b0b8752.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80196
  cosmetic: 45151
  scriptlet: 17555
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69102-51, 1d.5h.35m
    easyprivacy: 27479-123, 1d.5h.34m
    plowe-0: 3641-779, 9d.12h.3m
    ublock-abuse: 76-0, 9d.12h.1m
    ublock-badware: 4171-92, 1d.5h.33m
    ublock-filters: 32439-122, 1d.5h.32m
    ublock-privacy: 225-3, 9d.11h.57m
    ublock-quick-fixes: 354-61, 21h.30m
    ublock-unbreak: 1851-42, 1d.5h.31m
    urlhaus-1: 5003-0, 21h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 430 ms (selfie)
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    bing.com: 29
```
</details>

**Comment by gorhill** [comment]
Is uBO allowed to work on Bing in your MS Edge?

**Comment by xproot** [comment]
Yes, the ticker goes up whenever I search with bing. From: Raymond HillSent: Friday, August 5, 2022 6:36 AMTo: uBlockOrigin/uAssetsCc: xproot; AuthorSubject: Re: [uBlockOrigin/uAssets] bing.com: ads (Issue #14264) Is uBO allowed to work on Bing in your MS Edge?

**Comment by gorhill** [comment]
My web page looks like nothing in your screenshot -- unable to reproduce. You will need to investigate more on your side to find out whether these ads are injected by another extension or malware on your computer -- especially considering that you said uBO removes them properly when being enabled.

**Comment by xproot** [comment]
I already had ruled out the extension problem by disabling all of them. and I just did a quick scan that returned no problems.
It is weird how I cannot reproduce this anywhere else than edge on this specific computer, as I already tried edge on a linux computer.
