### ISSUE TITLE
surfline.com: detection

### ISSUE THREAD

**Issue by JDDab** [uBlockOrigin/uAssets#14276]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.surfline.com/`

### Category

detection

### Describe the issue

Surfline is again detecting UBO on all pages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Surfline UBO detection](https://user-images.githubusercontent.com/110704856/183229145-027943ad-c25e-4ed5-809c-0b0f3a05c2fb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 145541
  cosmetic: 102267
  scriptlet: 24741
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://secure.fanboy.co.nz/r/fanboy-ultimate.txt: 166732-58993, 2d.55m
    adguard-annoyance: 55554-3313, 2d.55m
    curben-phishing: 51711-0, 1d.1m
    fanboy-annoyance: 77667-67386, 2d.55m
    fanboy-cookiemonster: 38504-38504, 2d.55m
    fanboy-social: 23253-23253, 2d.55m
    ublock-annoyances: 4516-219, 2d.55m
  default: 
    user-filters: 9-0, never
    easylist: 69098-69098, 2d.55m
    easyprivacy: 27478-27475, 2d.55m
    plowe-0: 3640-781, 2d.55m
    ublock-abuse: 76-0, 2d.55m
    ublock-badware: 4171-93, 2d.55m
    ublock-filters: 32443-800, 2d.55m
    ublock-privacy: 230-11, 2d.55m
    ublock-quick-fixes: 347-25, 1d.3m
    ublock-unbreak: 1851-48, 2d.55m
    urlhaus-1: 5437-2, 1d.2m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 32 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 449 ms (selfie)
  maxAssetCacheWait: 345 ms
popupPanel: 
  blocked: 11
  no-cosmetic-filtering: true
  no-popups: true
  blockedDetails: 
    surfline.com: 1
    appsflyer.com: 1
    cdn-surfline.com: 1
    cloudflareinsights.com: 1
    googletagservices.com: 1
    htlbid.com: 2
    jwpcdn.com: 1
    lr-in.com: 1
    newrelic.com: 1
    unpkg.com: 1
```
</details>

**Comment by MasterKia** [comment]
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> - [X] I did not answer truthfully to **all** the above checkpoints

Please read and follow the Prerequisites truthfully instead of blindly ticking them.


>   added: 
    https://secure.fanboy.co.nz/r/fanboy-ultimate.txt: 166732-58993, 2d.55m
    adguard-annoyance: 55554-3313, 2d.55m
    curben-phishing: 51711-0, 1d.1m
    fanboy-annoyance: 77667-67386, 2d.55m
    fanboy-cookiemonster: 38504-38504, 2d.55m
    fanboy-social: 23253-23253, 2d.55m
    ublock-annoyances: 4516-219, 2d.55m

Test using **_only the default lists_**.
