### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by Zauhi** [uBlockOrigin/uAssets#14270]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage

### Describe the issue

The website plays the audio, but when it was supposed to skip the ad, it just break and don't play anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 81675
  cosmetic: 48038
  scriptlet: 17801
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69235-51, 31m
    easyprivacy: 27490-123, 30m
    plowe-0: 3642-779, 7d.20h.7m
    spa-1: 4582-80, 32m
    ublock-abuse: 76-0, 3d.17h.24m
    ublock-badware: 4171-92, 29m
    ublock-filters: 32381-156, 28m
    ublock-privacy: 235-3, 3d.17h.23m
    ublock-quick-fixes: 347-4, 16h.38m
    ublock-unbreak: 1852-44, 27m
    urlhaus-1: 5003-0, 16h.37m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 437 ms (selfie)
  maxAssetCacheWait: 293 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/14231
