### ISSUE TITLE
rynek-kolejowy.pl: detection

### ISSUE THREAD

**Issue by macibol775** [uBlockOrigin/uAssets#14271]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rynek-kolejowy.pl/`

### Category

detection

### Describe the issue

forces to turn off uBlock

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 83830
  cosmetic: 52570
  scriptlet: 17733
  html: 725
listset (total-discarded, last updated): 
  added: 
    https://letyshops.com/adblock.txt: 2401-128, 22h.51m
  default: 
    user-filters: 8-0, never
    ublock-filters: 33083-118, 2d.16h.30m
    ublock-badware: 4175-0, 2d.16h.34m
    ublock-privacy: 246-0, 2d.7h.11m
    ublock-abuse: 76-0, 2d.7h.10m
    ublock-unbreak: 1864-0, 2d.16h.33m
    easylist: 69063-610, 2d.16h.32m
    easyprivacy: 27478-580, 2d.16h.31m
    urlhaus-1: 5003-0, 22h.52m
    plowe-0: 3638-3, 6d.19h.54m
    POL-0: 7834-25, 22h.53m
    POL-2: 1279-12, 9h.43m
    ublock-quick-fixes: 360-1, 22h.54m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 346 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    disqus.com: 2
    facebook.net: 1
    gemius.pl: 1
    google-analytics.com: 1
    optad360.io: 4
    viglink.com: 2
```
</details>

**Comment by MasterKia** [comment]
> forces to turn off uBlock

Screenshot?

I can't reproduce on Firefox even with the two POL list enabled.

> I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists

> added: 
    https://letyshops.com/adblock.txt: 2401-128, 22h.51m

Please test with **_only the default lists_**.

**Comment by gorhill** [comment]
Can't reproduce either. But enabling ABP beside uBO is causing issues.
