### ISSUE TITLE
trade.dydx.exchange

### ISSUE THREAD

**Issue by IIIYE** [uBlockOrigin/uAssets#14274]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://trade.dydx.exchange

### Describe the issue

False alarm.

URL trade.dydx.exchage for some reason ended up in the "Phishing URL Blocklist" filter list.

This is a regular and proven crypto exchange that ended up in the filter by mistake.

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103.0.1

### Settings

- Enable "Phishing URL Blocklist".

**Comment by MasterKia** [comment]
> ### Settings
> 
>     * Enable "Phishing URL Blocklist".

Report here: https://gitlab.com/malware-filter/phishing-filter#issues

**Comment by Yuki2718** [comment]
Not a default list
@curbengh
