### ISSUE TITLE
lkong.com: ads

### ISSUE THREAD

**Issue by wclmgcd** [uBlockOrigin/uAssets#14281]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lkong.com/forum/60`

### Category

ads

### Describe the issue

有广告

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 82074
  cosmetic: 45166
  scriptlet: 17566
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-1, never
    ublock-filters: 33070-36, 4m
    ublock-badware: 4175-1, 4h.37m
    ublock-privacy: 247-0, 4h.35m
    ublock-abuse: 76-0, 4h.34m
    ublock-unbreak: 1865-0, 4h.33m
    ublock-quick-fixes: 353-3, 4h.32m
    easylist: 69264-578, 4m
    easyprivacy: 27498-594, 4h.30m
    urlhaus-1: 6721-0, 4h.29m
    plowe-0: 3634-3, 4h.27m
    CHN-0: 0-0, never
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 28523 ms
  maxAssetCacheWait: 373 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    baidu.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
CHN-0: 0-0, never
```
Can you disable and enable `CHN: AdGuard Chinese (中文)` list again?
