### ISSUE TITLE
tweakcentral.net: detection

### ISSUE THREAD

**Issue by Adityadey321** [uBlockOrigin/uAssets#14288]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tweakcentral.net/download/azurite`

### Category

detection

### Describe the issue

Can't access the website with uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-50, never
    easyprivacy: 27172-122, never
    plowe-0: 3639-781, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-91, never
    ublock-filters: 31779-94, never
    ublock-privacy: 222-2, never
    ublock-quick-fixes: 202-2, never
    ublock-unbreak: 1797-40, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5370 ms
  maxAssetCacheWait: 684 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cloudflareinsights.com: 2
    doubleclick.net: 2
    fightingleatherconspicuous.com: 2
```
</details>

**Comment by Adityadey321** [comment]
Fix this issue please

**Comment by shawon2901** [comment]
Seems Fine In Mobile No Issues

**Comment by okiehsch** [comment]
It's fixed in uBO-filters if I disable that list I can reproduce the anti adblock message.

![image](https://user-images.githubusercontent.com/16838044/183256933-5ed07c47-c1d7-46c5-b655-156916b9bc60.png)

That is good to know.
