### ISSUE TITLE
filepress.site: detection

### ISSUE THREAD

**Issue by shawon2901** [uBlockOrigin/uAssets#14280]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filepress.site/file/62ed22da93d6fef17f4a4956`

### Category

detection

### Describe the issue

Link>Direct Download>Ask To Disable AdBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 105
filterset (summary): 
  network: 82887
  cosmetic: 27081
  scriptlet: 17601
  html: 718
listset (total-discarded, last updated): 
  default: 
    user-filters: 207-1, never
    ublock-filters: 33219-332, 1d.17h.33m
    ublock-badware: 4174-0, 14h.4m
    ublock-privacy: 247-1, 14h.3m
    ublock-abuse: 76-0, 14h.2m
    ublock-unbreak: 1870-0, 14h.1m
    ublock-quick-fixes: 353-1, 14h
    adguard-mobile: 8054-167, 2d.4h.29m
    easylist: 69235-25103, 13h.59m
    easyprivacy: 27490-590, 13h.58m
    urlhaus-1: 6095-0, 13h.57m
    plowe-0: 3634-3, 13h.56m
filterset (user): [array of 207 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1578 ms
  maxAssetCacheWait: 1065 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue on mobile.

**Comment by MasterKia** [comment]
I can reproduce on Firefox desktop.
![Screenshot_20220806_195220](https://user-images.githubusercontent.com/17685483/183255324-efe714f9-2635-486f-90bc-bab41374aae0.png)

**Comment by okiehsch** [comment]
> I can reproduce on Firefox desktop.

I can only reproduce your screenshot if I disable `uBO-filters`. The fix added for https://github.com/uBlockOrigin/uAssets/issues/13854 still works.

**Comment by MasterKia** [comment]
I can reproduce with stock lists on Ungoogled Chromium as well.
I purged cache and updated the lists.

**Comment by shawon2901** [comment]
> I can't reproduce the issue on mobile.

![Screenshot_2022-08-06-21-56-09-892_org mozilla fenix](https://user-images.githubusercontent.com/40642163/183256494-2b26d5ab-f0e2-4362-a5ef-cf852bf7deab.jpg)

**Comment by stephenhawk8054** [comment]
Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps outside browser

**Comment by shawon2901** [comment]
> I can't reproduce the issue on mobile.

![Uploading Screenshot_2022-08-06-21-56-09-892_org.mozilla.fenix.jpg…]()


> Check if you are using any:
> 
>     * Custom filters (I see that you are using over 200 custom filters),
> 
>     * Other extensions,
> 
>     * Browser's built-in blocker,
> 
>     * DNS blocking methods,
> 
>     * Blocking apps outside browser

Im Sorry Man...I Was Using DNS A Few Hours Ago To Block Ads In Some Apps..Now Its Working.. Should I Delete This ?
