### ISSUE TITLE
soft98.ir: detection

### ISSUE THREAD

**Issue by 0x416c69** [uBlockOrigin/uAssets#14296]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://soft98.ir/
https://soft98.ir/internet/web-browser/3545-microsoft-edge-2.html

### Describe the issue

JavaScript gets rid of the whole content element and changes the hrefs of the download links when the uBO is detected.

### Screenshot(s)

![chrome_2022-08-07_08-55-40](https://user-images.githubusercontent.com/10671711/183275249-9fb26e0f-7f6f-4fc0-bae5-9723546b35d4.png)

Which roughly translates to disable ad blocker and refresh the page.

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 103.0.5060.134

### Settings

- Enabled [PersianBlocker](https://github.com/MasterKia/PersianBlocker) filter list

### Notes

New anti ad block does some heuristics on elements containing the "c1e1y2*" classes.

List of the heuristics:
![ss1](https://user-images.githubusercontent.com/10671711/183274574-604aec42-b522-4a26-aa08-7cb379da260d.png)

If the above function throws an exception, the following catch block will be executed:
![2022-08-07_08-31-07-AM](https://user-images.githubusercontent.com/10671711/183274650-1bca33f1-bb6f-4023-a73d-755814828150.png)

Which is pretty explanatory for itself.

Specifically, this condition is the cause of the very first throw in my uBO:
![chrome_2022-08-07_08-33-05](https://user-images.githubusercontent.com/10671711/183274715-5ce6598a-8568-4fde-8c8d-f0ea9ef7574f.png)

_$panel_ here is the same as _n_ in the first screenshot.

div.c1e1y2__inner is the cause of the exception when uBO built in filter (main one) is enabled, with PersianBlocker filter list alone the first element to cause this exception is: c1e1y2-li2nk c1e1y2

cc @MasterKia

**Comment by MasterKia** [comment]
I just pushed a fix.
For uBO, I decided that`soft98` filters would no longer be in PersianBlocker and would only be in Quick-Fixes.

So force update the PersianBlocker then wait for [my fix](https://github.com/uBlockOrigin/uAssets/pull/14297) to get merged in Quick-Fixes.

Then you can manually force update the Quick-Fixes list to get the latest filters.

I have to push new fixes **_everyday_** because the site admin has so much respect for its users that he updates the site daily to circumvent the filters.

@0x416c69 If you have expertise in Javascript and you can defuse their anti-adblock using uBO's [resources library](https://github.com/gorhill/uBlock/wiki/Resources-Library), I'd be happy to incorporate your fixes.

**Comment by MasterKia** [comment]
Can anyone defuse their anti-adblock?
To trigger it, disable Quick Fixes and use `||file.soft98.ir^`.

**Comment by okiehsch** [comment]
`soft98.ir##+js(nostif, , 3000)`

**Comment by MasterKia** [comment]
Should this issue get the "ongoing" label?
Similar to https://github.com/uBlockOrigin/uAssets/issues/13144

**Comment by 0x416c69** [comment]
> ```soft98.ir##+js(nostif, , 3000)```

I'm not familiar with the JS scriptlets but having read the [resources library](https://github.com/gorhill/uBlock/wiki/Resources-Library) page a bit, this workaround is hit or miss. The reason that setTimeout prevention works sometimes is that the "df" function is getting called in the JS initialization while the page DOMs are not yet downloaded completely so the first iteration wouldn't throw an exception simply because the DOMs are not there. Considering that this website is primarily used by the locals, we have an extremely low latency (I personally have a ping of 6ms with their servers) so the first iteration is all it takes to remove the whole page content.

I suggest that for each of the elements that is modified, it should follow the checks done under the "tu" function. That would mean replacing those images, div blocks, etc. with a blank 16x16 image and/or set the DOM width/height property accordingly. I think the set.js scriptlet would do the job here, modifying the "style.width/height" property and offsetHeight/offsetWidth properties.

**Comment by MasterKia** [comment]
@0x416c69 If you have Telegram please join: @PersianBlocker

**Comment by MasterKia** [comment]
@0x416c69 If you have Telegram please join: @PersianBlocker

https://t.me/PersianBlocker

**Comment by MasterKia** [comment]
@gorhill What do you suggest to do when the site admin has been changing filters manually _**every hour**_ [for almost a year now](https://github.com/uBlockOrigin/uAssets/issues/10883) and also self-sabotages his site just to evade uBO's filters?

There's a userscript written by @DRSDavidSoft for this site that defuses the anti-adblock and also removes the ads and it's evasion-proof, maybe it could be added to [URL-specific resources](https://github.com/gorhill/uBlock/wiki/Resources-Library#url-specific-sanitized-redirect-resources-surrogates) similar to `twitch-videoad.js` or `outbrain-widget.js` so `soft98.ir##+js(soft98-antiadb)`.

**Comment by gorhill** [comment]
> What do you suggest to do when the site admin has been changing the site source manually every day https://github.com/uBlockOrigin/uAssets/issues/10883 and also self-sabotages his site just to evade uBO's filters?

If it's a burden, just stop trying to work around it -- you don't have to "win" against such sites, your personal time and quality of life are more important than trying to make content blockers perfect all the time everywhere to everybody.

**Comment by 0x416c69** [comment]
@gorhill I was wondering if you could take advantage of the extension API and counter measure some of the common anti ad block techniques, such as checking for the size property/opacity/existence/attribute manipulation so when the JS VM asks for such data you would just return the original (fake) value.

This would improve the overall quality of the entirety of uBlock Origin since these methods are very common in all of the detection scripts and should decrease the amount of detection issues posted here.

**Comment by MasterKia** [comment]
> If it's a burden

Well I suspect there's a trend going on. If no content blocker can defuse this site's anti-adb then it's a lucrative way for others to follow suit.

Aternos is one example.

**Comment by JobcenterTycoon** [comment]
Many adblock detection scripts which gettting reported here using a `try...catch` block to detect adblocking. Unlike older common scripts redirecting a nooptext doesn’t work so every single site need to be fixed. More advanced scripts also checking the length of the response to be sure the real file has been served and not the empty one from the uBO `no-fetch-if` scriptlet.

advanced scripts which really deep checking elements with `getComputedStyle` are less common. I don’t know if such things like `getComputedStyle` can be fooled without a custom script for every site.

**Comment by gorhill** [comment]
Ultimately, visitors have the last word, they can also choose to not visit the site anymore when it becomes too unpleasant to visit.

In any case, I don't see the anti-blocker being triggered with AdGuard, using the same list.

**Comment by MasterKia** [comment]
> I don't see the anti-blocker being triggered with AdGuard, using the same list. I see only 3 network requests being blocked as per AdGuard's logger.

For trigger try blocking this banner:
![Screenshot_20220807_232021](https://user-images.githubusercontent.com/17685483/183306543-52303dcd-593b-4729-b7d3-2f836b95dd91.png)

Or the "آسیاتک" banner on the right side.

**Comment by MasterKia** [comment]
> Ultimately, visitors have the last word, they can also choose to not visit the site anymore when it becomes too unpleasant to visit.

True that, but this has gone beyond "unpleasant", the site is being hostile towards the users who chose to not see ads by installing a blocker.
IMO Sites disrespecting the user deserve to be strict-blocked.

**Comment by 0x416c69** [comment]
Closing this since after using this extension: https://addons.mozilla.org/addon/soft98-anti-adblock-bypass/ this problem is gone now.
