### ISSUE TITLE
webbtelescope.org: breakage

### ISSUE THREAD

**Issue by yiannislog** [uBlockOrigin/uAssets#14294]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://webbtelescope.org/news/first-images/gallery`

### Category

breakage

### Describe the issue

zoom-able images do not render

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 188936
  cosmetic: 213794
  scriptlet: 37595
  html: 0
listset (total-discarded, last updated): 
  added: 
    GRC-0: 1002-0, 4h.14m
    adguard-annoyance: 55554-74, 2d.20h.27m
    adguard-generic: 66522-697, 2d.20h.26m
    adguard-mobile: 8054-46, 2d.20h.25m
    adguard-social: 18080-865, 2d.20h.24m
    adguard-spyware: 28360-1382, 2d.20h.23m
    adguard-spyware-url: 688-0, 2d.20h.22m
    block-lan: 43-0, 6d.20h.47m
    curben-phishing: 49027-0, 13m
    curben-pup: 182-1, 12m
    dpollock-0: 10413-285, 6d.20h.47m
    fanboy-annoyance: 77063-4404, 6d.20h.47m
    fanboy-cookiemonster: 37929-37929, 6d.20h.47m
    fanboy-social: 23253-23239, 2d.20h.19m
    fanboy-thirdparty_social: 68-21, 6d.20h.47m
    ublock-annoyances: 4515-244, 2d.20h.17m
  default: 
    user-filters: 0-0, never
    easylist: 69098-1318, 2d.20h.21m
    easyprivacy: 27478-10156, 2d.20h.20m
    plowe-0: 3639-1308, 6d.20h.47m
    ublock-abuse: 76-0, 2d.20h.18m
    ublock-badware: 4171-320, 2d.20h.16m
    ublock-filters: 32443-3874, 2d.20h.15m
    ublock-privacy: 230-44, 2d.20h.14m
    ublock-quick-fixes: 356-35, 11m
    ublock-unbreak: 1851-107, 2d.20h.13m
    urlhaus-1: 6793-3, 10m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1083 ms (selfie)
  maxAssetCacheWait: 869 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    webbtelescope.org: 31
```
</details>

**Comment by stephenhawk8054** [comment]
```
@@||webbtelescope.org/files/live/sites/*/_images/$image,1p
webbtelescope.org#@#.ad-box
```

@ryanbr
