### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by blumnio** [uBlockOrigin/uAssets#14299]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yandex.ru/`

### Category

ads

### Describe the issue

A banner with the inscription "Mozilla Firefox больше не поддерживает поиск Яндекса" flies out

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/82469213/183283215-886da45a-7a57-44df-abc5-bd639f0c8623.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 81363
  cosmetic: 45167
  scriptlet: 17560
  html: 715
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33124-150, 2d.13h.31m
    ublock-badware: 4175-0, 2d.13h.30m
    ublock-privacy: 246-0, 2d.13h.29m
    ublock-abuse: 76-0, 2d.13h.28m
    ublock-unbreak: 1864-0, 2d.13h.27m
    ublock-quick-fixes: 344-1, 1d.11h.25m
    easylist: 69167-491, 2d.13h.25m
    easyprivacy: 27481-594, 2d.13h.24m
    urlhaus-1: 6095-0, 1d.11h.24m
    plowe-0: 3640-3, 2d.13h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 175 ms (selfie)
  maxAssetCacheWait: 64 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    yandex.ru: 32
    yastatic.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `RUS: RU AdList` in ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) and test again?

**Comment by dimisa-RUAdList** [comment]
The rules for this site are contained in [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt&title=RU%20AdList%20for%20uBO%20only) and [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters). In addition, for browsers of the Firefox family, you will need to install [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor), for Firefox: 103 - [scriptlet-doctor-quantum](https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.5/scriptlet-doctor-quantum-1.2.5.xpi).

**Comment by taff-blur** [comment]
My bad, my bad, thanks for letting me know.
