### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by shawon2901** [uBlockOrigin/uAssets#14290]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropgalaxy.com/jc3054o9ymo3`

### Category

detection

### Describe the issue

Wait 15 Second > Create Download >AdBlocker Detected

Same Setting On Kiwi Browser Doesn't Detect AdBlocker..I Guess This Is FireFox Problem ?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2022-08-06-22-54-03-840_org mozilla firefox](https://user-images.githubusercontent.com/40642163/183259090-cf89e739-3a32-4b51-b994-515bb2b1e6d1.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 83369
  cosmetic: 26892
  scriptlet: 17607
  html: 718
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33177-312, 1m
    ublock-badware: 4174-0, 1m
    ublock-privacy: 247-1, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1870-0, 1m
    ublock-quick-fixes: 349-1, 1m
    adguard-mobile: 8062-167, 1m
    easylist: 69270-25107, 1m
    easyprivacy: 27284-590, 1m
    urlhaus-1: 6793-0, 1m
    plowe-0: 3634-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 515 ms
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 75
  blockedDetails: 
    a-ads.com: 1
    a-mx.com: 1
    cloudflareinsights.com: 1
    criteo.com: 1
    googletagmanager.com: 1
    id5-sync.com: 1
    imasdk.googleapis.com: 1
    quantumdex.io: 7
    vliplatform.com: 57
    vlitag.com: 4
```
</details>

**Comment by okiehsch** [comment]
Works fine here using Firefox. 
Is the internal Firefox tracking protection enabled on your end?

**Comment by shawon2901** [comment]
> Works fine here using Firefox. Is the internal Firefox tracking protection enabled on your end?

Ok So Even After Disabling Tracking Protection It Didnt Work...Seems Like They My IP BlockListed Or Marked To Be AdBlock User..I Tried With VPN & Everything Working As Usual

**Comment by adsdestroyer** [comment]
> 

same here but which VPN you used? i will try also
