### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by TLord3690** [uBlockOrigin/uAssets#14293]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=McbpCFyMt28`

### Category

ads

### Describe the issue

The ads started showing up few minutes ago on YT

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/93601492/183264734-e4d927d0-90f9-4dea-afc1-893f6c736752.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 81940
  cosmetic: 45168
  scriptlet: 17568
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 69270-51, 6h.51m
    easyprivacy: 27282-123, 6h.52m
    plowe-0: 3639-777, 4d.6h.43m
    ublock-abuse: 76-0, 6h.27m
    ublock-badware: 4171-92, 6h.49m
    ublock-filters: 32383-121, 6h.53m
    ublock-privacy: 231-3, 6h.26m
    ublock-quick-fixes: 356-3, 6h.47m
    ublock-unbreak: 1851-42, 6h.50m
    urlhaus-1: 6793-0, 6h.48m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 837 ms (selfie)
  maxAssetCacheWait: 410 ms
popupPanel: 
  blocked: 410
  blockedDetails: 
    youtube.com: 375
    doubleclick.net: 7
    googleadservices.com: 4
    googlesyndication.com: 24
```
</details>

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
