### ISSUE TITLE
Addition of Ghostery Filters

### ISSUE THREAD

**Issue by clementine123** [uBlockOrigin/uAssets#143]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[N/A]`

### Describe the issue

[I would like to make a suggestion. Are you able to include filters for Ghostery as well? I saw filters from Disconnect which is great but it would be nice to have filters for Ghostery as well.]

### Screenshot(s)

[N/A]

### Versions

- Browser/version: [Chrome 53.0.2785.116 m]
- uBlock Origin version: [uBlock Origin 1.9.4]

### Settings

- [None]

### Notes

[See description above]

**Comment by gorhill** [comment]
Ghostery is proprietary code.
