### ISSUE TITLE
speedostream.com: breakage

### ISSUE THREAD

**Issue by github-lintcode** [uBlockOrigin/uAssets#14304]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://speedostream.com/s2tgt43bkmfi.html`

### Category

breakage

### Describe the issue

The video on the aforementioned website stops working while uBlock is switched on and gives the following error : 

```
Sorry, the video player failed to load.(Error Code: 100012)
```

The issue seems to be due to ostensibly 
``` jwpltx.com```

It would be great if it is added to rectify this issue!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot issue ](https://imgur.com/a/TRXzbil)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 282415
  cosmetic: 289001
  scriptlet: 56041
  html: 767
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 116d.6h.9m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1h.38m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23921-84, 1h.40m
    https://winhelp2002.mvps.org/hosts.txt: 8730-350, 2d.9h.29m
    adguard-generic: 66542-6771, 3d.7h.28m
    adguard-mobile: 8055-234, 3d.7h.16m
    adguard-spyware: 28362-1955, 3d.7h.29m
    adguard-spyware-url: 693-1, 3d.7h.15m
    block-lan: 43-0, 5d.22h.9m
    curben-phishing: 47866-16, 1h.29m
    curben-pup: 180-0, 1h.32m
    adguard-annoyance: 55611-5151, 2d.9h.28m
    adguard-social: 18089-1066, 3d.7h.19m
    fanboy-thirdparty_social: 68-0, 1h.44m
    fanboy-annoyance: 78222-62567, 1h.43m
    fanboy-cookiemonster: 39060-188, 1h.42m
    fanboy-social: 23253-36, 3d.7h.17m
    ublock-annoyances: 4524-8, 3d.7h.14m
    dpollock-0: 10413-1657, 7d.21h.32m
    ALB-0: 267-1, 1h.25m
    [16 lists not shown]: [too many]
  default: 
    user-filters: 74-2, never
    ublock-filters: 33127-3177, 3d.7h.27m
    ublock-badware: 4175-4, 3d.7h.26m
    ublock-privacy: 247-0, 1d.8h.28m
    ublock-abuse: 76-0, 1d.8h.27m
    ublock-unbreak: 1864-6, 3d.7h.25m
    ublock-quick-fixes: 353-1, 1h.26m
    easylist: 69158-1257, 3d.7h.24m
    easyprivacy: 27480-10505, 3d.7h.23m
    urlhaus-1: 6831-0, 1h.27m
    plowe-0: 3639-4, 7d.1h.2m
filterset (user): [array of 74 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 10 redacted]
  removed: 
    no-csp-reports: * true
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 372 ms (selfie)
  maxAssetCacheWait: 842 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    aj1907.online: 2
    googletagmanager.com: 1
    jwpltx.com: 1
    uphermonilia.com: 2
```
</details>

**Comment by MasterKia** [comment]
You don't need "adguard-mobile" on the desktop.

**Comment by ghajini** [comment]
this issue doesn't occur on default configuration
your given link is expired
so at
 `https://speedostream.com/3joan62hstl9`
so you need to see which list is causing that error
