### ISSUE TITLE
htforum.net: detection

### ISSUE THREAD

**Issue by roni1986** [uBlockOrigin/uAssets#14306]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://htforum.net/`

### Category

detection

### Describe the issue

The detection always return after some page refresh, even though the select of element.

I put by select element several times as can be seen below:

! 2022-07-31 https://htforum.net
htforum.net##.q62e62583106cf266413910

! 2022-08-01 https://htforum.net
htforum.net##.b62e7cf5db2d70114653375

! 2022-08-07 https://htforum.net
htforum.net##.i62ef540fcc085283417352
htforum.net##.f62eff1a4ecfab061257411

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110794108/183317585-d8b13133-bb59-49ce-8997-5fc49da45a2e.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 83344
  cosmetic: 48076
  scriptlet: 17807
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-0, never
    easylist: 69285-51, 35m
    easyprivacy: 27295-123, 34m
    plowe-0: 3639-777, 8d.2h.50m
    spa-1: 4582-80, 36m
    ublock-abuse: 76-0, 8d.2h.48m
    ublock-badware: 4176-92, 33m
    ublock-filters: 32391-157, 32m
    ublock-privacy: 226-3, 8d.2h.44m
    ublock-quick-fixes: 356-3, 4h.38m
    ublock-unbreak: 1852-44, 31m
    urlhaus-1: 6831-0, 4h.37m
filterset (user): [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 786 ms (selfie)
  maxAssetCacheWait: 1412 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    htforum.net: 1
    cloudflareinsights.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    mikle.com: 1
```
</details>

**Comment by roni1986** [comment]
Hi @okiehsch, is not account required: 
![image](https://user-images.githubusercontent.com/110794108/183471409-35b53450-532f-41d4-a090-f6edcb787872.png)

**Comment by okiehsch** [comment]
> Hi @okiehsch, is not account required:


In that case I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/183480716-e14fc43b-664b-4f5b-a277-56eef889bd7c.png)

**Comment by Procyon-b** [comment]
@roni1986 if hiding the message is enough, you can use this filter:
```
htforum.net##.p-body-inner > div[class][style*="display: block;"]
```

**Comment by roni1986** [comment]
Wow, thank you!! This work for me.

**Comment by mapx-** [comment]
update uBO annoyances list & test again
