### ISSUE TITLE
9anime.id: breakage + detects devtools

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uAssets#14308]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/watch/gintama-season-3.8nln/ep-1`

### Category

breakage

### Describe the issue

Attempting to play videos results in no videos playing and instead a black screen. This occurs on any of the four "servers".

This site also implements anti-devtools code, something along the lines of https://x-c3ll.github.io/posts/javascript-antidebugging/#0x02-breakpoints.

This may or may not be a uAssets issue. The anti-devtools code makes it unfortunately hard to tell.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 84147
  cosmetic: 81629
  scriptlet: 22090
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 38281-98, 6d.2h.19m
    ublock-annoyances: 4518-50, 2d.5h.13m
  default: 
    user-filters: 248-2, never
    easylist: 69242-51, 2d.5h.14m
    easyprivacy: 27498-123, 2d.4h.11m
    plowe-0: 3634-776, 2d.7h.30m
    ublock-abuse: 76-0, 1d.11h.12m
    ublock-badware: 4171-92, 2d.4h.10m
    ublock-filters: 32377-128, 2d.4h.9m
    ublock-privacy: 231-3, 1d.11h.11m
    ublock-quick-fixes: 356-3, 2h.40m
    ublock-unbreak: 1852-44, 2d.4h.8m
    urlhaus-1: 6920-0, 2h.41m
filterset (user): [array of 248 redacted]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 174 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    9anime.id: 1
    addthis.com: 1
    amung.us: 1
    bidgear.com: 4
```
</details>

**Comment by okiehsch** [comment]
Video plays fine on all servers on my end, except streamtape, that one has been deleted.
