### ISSUE TITLE
seekingalpha.com: breakage

### ISSUE THREAD

**Issue by cactuspat1** [uBlockOrigin/uAssets#14305]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://seekingalpha.com/`

### Category

breakage

### Describe the issue

Seekingalpha.com is often broken by Ublock. As in the page is blank, or a section of it, until cosmetic filters are disabled. Then with cosmetic filters disabled the ads for membership are viewable with no way to block.

Not positive but believe SA to be writing code to defeat ad blocking as this occurs regularly...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Seekingalpha-example](https://user-images.githubusercontent.com/110790836/183313120-8b9aeba9-96f6-4469-b8e1-b1c150e01fb8.jpg)
![Seekingalpha-example2](https://user-images.githubusercontent.com/110790836/183313130-07aa576d-7989-449b-a137-b1607dd6851f.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 101
filterset (summary): 
  network: 95188
  cosmetic: 117214
  scriptlet: 24739
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-44, 23h.43m
    adguard-annoyance: 55644-1679, 1d.23h.50m
    adguard-social: 18092-1987, 1d.23h.41m
    fanboy-annoyance: 77367-36550, 6d.2h.52m
    fanboy-thirdparty_social: 69-21, 6d.2h.52m
    ublock-annoyances: 4518-219, 1d.23h.51m
  default: 
    user-filters: 93-4, never
    easylist: 69235-24484, 1d.23h.53m
    easyprivacy: 27490-266, 1d.23h.42m
    plowe-0: 3639-779, 6d.2h.52m
    ublock-abuse: 76-0, 1d.23h.40m
    ublock-badware: 4171-92, 1d.23h.52m
    ublock-filters: 32375-802, 1d.23h.39m
    ublock-privacy: 231-11, 1d.23h.38m
    ublock-quick-fixes: 357-4, 3h.33m
    ublock-unbreak: 1852-49, 1d.23h.37m
    urlhaus-1: 6095-0, 1d.19h.25m
filterset (user): [array of 93 redacted]
trustedset: 
  added: [array of 33 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4044 ms (selfie)
  maxAssetCacheWait: 1407 ms
popupPanel: 
  blocked: 28
  no-cosmetic-filtering: true
  blockedDetails: 
    seekingalpha.com: 23
    gbqofs.com: 1
    googletagmanager.com: 1
    petametrics.com: 1
    sail-horizon.com: 1
    tinypass.com: 1
```
</details>

**Comment by ghajini** [comment]
backup settings and reinstall ubo to see if that solves your issue
