### ISSUE TITLE
9anime.id: ads

### ISSUE THREAD

**Issue by raj-069** [uBlockOrigin/uAssets#14302]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.id/home`

### Category

ads

### Describe the issue

The site displays an ad leftover as shown in the screenshot. It never used to happen before until the site changed it's UI.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/82037299/183299029-a52f124c-3acb-40ce-904b-682e6383522f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-50, never
    easyprivacy: 27172-122, never
    plowe-0: 3639-781, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-91, never
    ublock-filters: 31779-94, never
    ublock-privacy: 222-2, never
    ublock-quick-fixes: 202-2, never
    ublock-unbreak: 1797-40, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 274 ms
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    9anime.id: 1
    addthis.com: 1
    amung.us: 1
    bidgear.com: 1
```
</details>

**Comment by okiehsch** [comment]
`9anime.id##.adx`
@ryanbr
