### ISSUE TITLE
[nsfw] scrolller.com: breakage

### ISSUE THREAD

**Issue by delebota** [uBlockOrigin/uAssets#14319]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://scrolller.com/`

### Category

breakage

### Describe the issue

Nothing loads while the plugin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82160
  cosmetic: 45199
  scriptlet: 17577
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33092-37, 2m
    ublock-badware: 4180-0, 2m
    ublock-privacy: 247-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1867-0, 2m
    ublock-quick-fixes: 355-1, 2m
    easylist: 69302-592, 2m
    easyprivacy: 27302-580, 2m
    urlhaus-1: 6987-0, 2m
    plowe-0: 3634-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 348 ms (selfie)
  maxAssetCacheWait: 122 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    scrolller.com: 2
    google-analytics.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
Add
`@@||scrolller.com/popunderjs/script.js$xhr,script,1p`
to your filter list.

**Comment by okiehsch** [comment]
The site works fine now on my end even without the exception.
It had to be a site issue, blocking that request should not lead to site breakage.
