### ISSUE TITLE
mako.co.il: detection

### ISSUE THREAD

**Issue by regore-droid** [uBlockOrigin/uAssets#14313]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mako.co.il/news-israel/2022_q3/Article-e9222fc37cd7281027.htm?sCh=31750a2610f26110&pId=173113802_349301`

### Category

detection

### Describe the issue

Video is not shown without turning off uBlock because uBlock is detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82066
  cosmetic: 45180
  scriptlet: 17567
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33072-39, 1d.19h
    ublock-badware: 4175-0, 1d.18h.59m
    ublock-privacy: 247-0, 1d.18h.58m
    ublock-abuse: 76-0, 1d.18h.57m
    ublock-unbreak: 1865-0, 1d.18h.56m
    ublock-quick-fixes: 353-1, 18h.8m
    easylist: 69281-592, 1d.18h.55m
    easyprivacy: 27290-580, 1d.18h.54m
    urlhaus-1: 6920-0, 2h.36m
    plowe-0: 3634-3, 1d.18h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 935 ms
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    mako.co.il: 6
    cooladata.com: 1
    exelator.com: 1
    google-analytics.com: 1
    googletagmanager.com: 4
    googletagservices.com: 1
    h-cdn.com: 1
    outbrain.com: 1
    permutive.com: 1
    sekindo.com: 1
    upapi.net: 2
```
</details>

**Comment by okiehsch** [comment]
Enable the regional hebrew list.
