### ISSUE TITLE
mail.yandex.ru: ads

### ISSUE THREAD

**Issue by Drivik** [uBlockOrigin/uAssets#14310]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Describe the issue

Ads still show

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 100230
  cosmetic: 67167
  scriptlet: 17575
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33094-39, 34m
    ublock-badware: 4180-0, 33m
    ublock-privacy: 241-0, 11d.18h.45m
    ublock-abuse: 76-0, 11d.18h.44m
    ublock-unbreak: 1864-0, 4d.32m
    ublock-quick-fixes: 354-0, 18h.34m
    easylist: 69143-605, 4d.31m
    easyprivacy: 27480-580, 4d.30m
    urlhaus-1: 6831-0, 18h.33m
    plowe-0: 3641-3, 11d.18h.38m
    RUS-0: 40329-143, 1d.20h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 272 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 127
  blockedDetails: 
    yandex.ru: 125
    yandex.net: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
The rules for this site are contained in [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt&title=RU%20AdList%20for%20uBO%20only) and [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters). In addition, for browsers of the Firefox family, you will need to install [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor), for Firefox: 103 - [scriptlet-doctor-quantum](https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.5/scriptlet-doctor-quantum-1.2.5.xpi).
