### ISSUE TITLE
ebay.com: breakage

### ISSUE THREAD

**Issue by HypdUp** [uBlockOrigin/uAssets#14312]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ebay.com/itm/165606154789`

### Category

breakage

### Describe the issue

Cant cycle through images of listings.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 188462
  cosmetic: 133955
  scriptlet: 37606
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 0-0, 18h.27m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1940-0, 18h.28m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-24, 22h.31m
    adguard-annoyance: 55645-1639, 1d.22h.33m
    adguard-generic: 66586-1110, 1d.22h.36m
    adguard-spyware: 28365-1385, 1d.22h.33m
    adguard-spyware-url: 695-90, 1d.22h.33m
    block-lan: 43-0, 1d.22h.33m
    curben-phishing: 47961-0, 22h.30m
    curben-pup: 180-1, 22h.29m
    dpollock-0: 10413-203, 1d.22h.33m
    fanboy-annoyance: 78090-36263, 1d.22h.33m
    fanboy-cookiemonster: 38922-38922, 1d.22h.33m
    ublock-annoyances: 4518-247, 1d.22h.33m
  default: 
    user-filters: 1-0, never
    easylist: 69270-25505, 1d.23h.5m
    easyprivacy: 27284-10131, 1d.23h.5m
    plowe-0: 3634-1243, 1d.23h.5m
    ublock-abuse: 76-0, 1d.23h.5m
    ublock-badware: 4171-320, 1d.23h.5m
    ublock-filters: 32386-4149, 1d.23h.5m
    ublock-privacy: 231-46, 1d.23h.5m
    ublock-quick-fixes: 350-15, 22h.33m
    ublock-unbreak: 1852-109, 1d.23h.5m
    urlhaus-1: 6831-3, 22h.32m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: 
  modifyWebextFlavor: fenix
supportStats: 
  allReadyAfter: 1097 ms
  maxAssetCacheWait: 1018 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ebaydesc.com: 1
    ebaystatic.com: 10
```
</details>

**Comment by MasterKia** [comment]
> ```yaml
>     https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-24, 22h.31m
> ```


> 2196-24, 22h.31m

How? It's in the badlists.

**Comment by gwarser** [comment]
> How? It's in the badlists.

Badlist has `https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt`. Maybe it needs to be updated?
