### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by yndingo** [uBlockOrigin/uAssets#14325]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://e.mail.ru/inbox/`

### Category

ads

### Describe the issue

cleared by ##.hNiHWG.sc-aqzsh0.qkmddoK.RfuBqsJ

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-08-09 105853](https://user-images.githubusercontent.com/80397258/183575491-4e720e9a-d9e8-4184-9f65-2478b41f1f8a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 91
filterset (summary): 
  network: 98442
  cosmetic: 67188
  scriptlet: 17561
  html: 716
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33072-37, 4d.1h.19m
    ublock-badware: 4175-0, 4d.1h.18m
    ublock-privacy: 242-0, 10d.18h.7m
    ublock-abuse: 76-0, 10d.18h.6m
    ublock-unbreak: 1864-0, 4d.1h.17m
    ublock-quick-fixes: 355-1, 1h.21m
    easylist: 69216-591, 4d.1h.16m
    easyprivacy: 27487-580, 4d.1h.15m
    urlhaus-1: 4968-0, 1h.22m
    plowe-0: 3639-3, 8d.1h.50m
    RUS-0: 40351-158, 1d.2h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1141 ms (selfie)
  maxAssetCacheWait: 346 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    mail.ru: 6
```
</details>

**Comment by dimisa-RUAdList** [comment]
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
> 
Do it twice.

**Comment by yndingo** [comment]
Thank you! And good luck!
