### ISSUE TITLE
Facebook and Instagram embedded video ads

### ISSUE THREAD

**Issue by cheetoslover** [uBlockOrigin/uAssets#14322]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

ublock can't block any ad on fb like on the right ads or inside video ads or anything  tried to enable all filter and still the same 

### A specific URL where the issue occurs

fb.com

### Steps to Reproduce

play any random video on fb and this will happen

### Expected behavior

to skip video ads automatically 

### Actual behavior

nothing happen and it keep loading the original ad

### uBlock Origin version

Latest

### Browser name and version

Chrome v 104

### Operating System and version

Windows 10 21H2

**Comment by krystian3w** [comment]
> I tried to enable all filter and still the same

back to stock config and minimal of regional lists.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by krystian3w** [comment]
But linked issue no support instagram

**Comment by MasterKia** [comment]
Maybe should change the name to "ALL facebook.com and instagram.com" or "ALL facebook products" issues.

**Comment by okiehsch** [comment]
The OP has not given an instagram link.
The steps to reproduce are
"Play any fb video".

**Comment by MasterKia** [comment]
It was a drive-by issue anyway, but should future `instagram.com` issues be aimed at the issue you linked?

**Comment by okiehsch** [comment]
We have quite a few instagtam issues https://github.com/uBlockOrigin/uAssets/search?q=instagram&type=issues
We could pick one, reopen and rename  it to "All instagram issues".

**Comment by krystian3w** [comment]
Maybe better create fresh by bot account to avoid user bannish half of GitHub accounts (to reduce write second post in issue).
