### ISSUE TITLE
telecinco.es: detection

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#14329]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.telecinco.es/yaesmediodia/secciones/sucesos/victima-manada-no-cree-perdon-prenda_18_3214848018.html`

### Category

detection

### Describe the issue

When the extension is enabled, the video shows an error message and does not load. When it is disabled, the video is played correctly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 85209
  cosmetic: 50077
  scriptlet: 17812
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69309-51, 3h.6m
    easyprivacy: 27306-123, 3h.5m
    plowe-0: 3639-777, 8d.48m
    spa-0: 3898-37, 21h.17m
    spa-1: 4588-172, 13h.18m
    ublock-abuse: 76-0, 9d.1h
    ublock-badware: 4176-92, 3h.4m
    ublock-filters: 32395-173, 3h.3m
    ublock-privacy: 226-3, 9d.59m
    ublock-quick-fixes: 357-1, 21h.18m
    ublock-unbreak: 1855-45, 3h.2m
    urlhaus-1: 6920-0, 1d.1h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 573 ms (selfie)
  maxAssetCacheWait: 265 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    amazon-adsystem.com: 1
    bkrtx.com: 1
    chartbeat.com: 2
    doubleclick.net: 1
    facebook.net: 1
    go-mpulse.net: 1
    googlesyndication.com: 10
    googletagmanager.com: 1
    gstatic.com: 1
    mediaset.es: 2
    omtrdc.net: 2
    seedtag.com: 1
    sensic.net: 2
    smartmeapp.com: 1
    socy.es: 1
    taboola.com: 1
```
</details>

**Comment by MasterKia** [comment]
Video plays fine for me on Firefox and Ungoogled Chromium.

**Comment by rodrigosambadesaa** [comment]
Now I can play the video. I use Chrome with a lot of extensions, none of which caused the problem because I didn't disable any of them. I don't know why I couldn't play it yesterday.
