### ISSUE TITLE
kizi.com: detection

### ISSUE THREAD

**Issue by Gamingzone123** [uBlockOrigin/uAssets#14338]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kizi.com`

### Category

detection

### Describe the issue

detects the blocker, tried a script to fix, still detects the blocker
detection completely blocks access to site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/47021866/183816825-1fef5b57-6250-4411-90a9-6385282cedfd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 154016
  cosmetic: 176981
  scriptlet: 25203
  html: 730
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 5m
    adguard-spyware: 26771-1007, 12m
    adguard-spyware-url: 702-2, 11m
    block-lan: 43-0, 11m
    curben-phishing: 45119-7, 12m
    curben-pup: 183-0, 12m
    adguard-annoyance: 55753-4833, 11m
    adguard-social: 18119-1058, 11m
    fanboy-thirdparty_social: 69-0, 11m
    fanboy-annoyance: 78388-23614, 11m
    fanboy-social: 23268-28, 11m
    ublock-annoyances: 4526-4, 11m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33091-49, 20h.27m
    ublock-badware: 4180-0, 20h.31m
    ublock-privacy: 242-0, 11d.22h.50m
    ublock-abuse: 76-0, 11d.22h.49m
    ublock-unbreak: 1865-1, 1d.18h.48m
    ublock-quick-fixes: 355-1, 1h.48m
    easylist: 69301-631, 1d.18h.50m
    easyprivacy: 27301-9814, 1d.18h.49m
    urlhaus-1: 5164-0, 1h.49m
    plowe-0: 3639-3, 9d.21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1550 ms
  maxAssetCacheWait: 817 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    2mdn.net: 2
    cookiepro.com: 2
    crwdcntrl.net: 1
    facebook.net: 1
    gamedock.io: 1
    google-analytics.com: 3
    google.com.tr: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    headerlift.com: 2
    imasdk.googleapis.com: 1
    improvedigital.com: 3
    kizicdn.com: 2
```
</details>

**Comment by MasterKia** [comment]
@Gamingzone123 You can add this to "My filters":

`kizi.com##+js(set, window.ad_blocker_active, false)`

**Comment by MasterKia** [comment]
@Gamingzone123 This filterlist that you added has been unmaintained for +5 years and it won't do anything:
> added: 
    `https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt`: 0-0, 5m

**Comment by ghajini** [comment]
@MasterKia although it sounds bait(prebid stuff), you can add filters as its reproducible on default settings
