### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by Skaramush** [uBlockOrigin/uAssets#14332]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://e.mail.ru/spam/?authid=l6j0ctl4.qb&back=1%2C1&dwhsplit=s10273.b1ss12743s&from=login&x-login-auth=1&afterReload=1`

### Category

ads

### Describe the issue

ADS show after logon

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 147894
  cosmetic: 236046
  scriptlet: 37555
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55650-367, 2d.7h.33m
    adguard-generic: 66584-895, 3d.21h.18m
    adguard-mobile: 8062-63, 2d.7h.34m
    adguard-social: 18112-876, 3h.32m
    adguard-spyware: 28363-1442, 3d.21h.12m
    adguard-spyware-url: 696-0, 3h.33m
    block-lan: 43-0, 4d.1h.19m
    fanboy-annoyance: 78144-4472, 2d.3h.30m
    fanboy-cookiemonster: 38982-38982, 2d.3h.29m
    fanboy-social: 23262-23262, 2d.7h.31m
    fanboy-thirdparty_social: 68-21, 3d
    ublock-annoyances: 4518-244, 2d.7h.32m
  default: 
    user-filters: 6-0, never
    RUS-0: 40346-9, 2d.3h.28m
    easylist: 69235-1121, 3d.21h.17m
    easyprivacy: 27490-10157, 3d.21h.16m
    plowe-0: 3642-959, 12d.3h.28m
    ublock-abuse: 76-1, 12d.11h.34m
    ublock-badware: 4171-318, 3d.21h.15m
    ublock-filters: 32436-3895, 3d.21h.14m
    ublock-privacy: 225-49, 12d.11h.32m
    ublock-unbreak: 1852-107, 3d.21h.13m
    urlhaus-1: 6987-0, 15h.34m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  colorBlindFriendly: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7209 ms (selfie)
  maxAssetCacheWait: 1599 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    mail.ru: 27
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=mail.ru

**Comment by dimisa-RUAdList** [comment]
@Skaramush 
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
> 
Do it twice.
