### ISSUE TITLE
ukr.net: ads

### ISSUE THREAD

**Issue by BlackStar1991** [uBlockOrigin/uAssets#14333]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ukr.net/`

### Category

ads

### Describe the issue

can't check #pvssaowUqRpvesa elements

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 100298
  cosmetic: 67214
  scriptlet: 17580
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 40352-9, 1d.22h.12m
    easylist: 69283-66, 2d.10h.42m
    easyprivacy: 27294-222, 2d.10h.41m
    plowe-0: 3634-781, 2h.14m
    ublock-abuse: 76-1, 21h.46m
    ublock-badware: 4171-92, 2d.10h.40m
    ublock-filters: 32389-149, 2d.10h.39m
    ublock-privacy: 231-3, 1d.4h.49m
    ublock-quick-fixes: 357-1, 1d.48m
    ublock-unbreak: 1854-44, 2d.10h.38m
    urlhaus-1: 6987-0, 1d.47m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 808 ms (selfie)
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    ukr.net: 3
    adpartner.pro: 1
    adtcdn.com: 2
    cloudflareinsights.com: 1
    doubleclick.net: 1
    fwdcdn.com: 2
    googletagmanager.com: 1
    mgid.com: 1
    mixadvert.com: 1
    phoenix-widget.com: 1
    rcvlink.com: 2
    trafmag.com: 1
```
</details>

**Comment by MasterKia** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@BlackStar1991 
> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
> 
Do it twice.

**Comment by dimisa-RUAdList** [comment]
> ```yaml
> RUS-0: 40352-9, 1d.22h.12m
> ```

Should be a little less than 42000.
