### ISSUE TITLE
behance.net annoyances

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14337]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.behance.net/search?search=cats
https://www.behance.net/gallery/137196631/Cool-cats-in-town
```

### Describe the issue

There are several annoyances on Behance. Here are some filters to fix them.

1. Prevent sign-in gate that appears when scrolling down to the bottom of a search result:
  `behance.net##[class*="Search-contentBlocker-"]`

2. Hide Adobe stock photo promo ads from search results:
  `behance.net##[class*="StockRail-rail-"]`

3. Disable right-click pointer-event blockers on images:
   ```
   behance.net##[class*="ImageElement-blockPointerEvents-"]:style(pointer-events: auto !important)
   behance.net##[class*="Module-blockGridPointerEvents-"] .grid__item-image:style(pointer-events: auto !important)
   behance.net###lightbox-wrap img:style(pointer-events: auto !important)
   ```

### uBlock Origin version

1.43

### Browser name and version

Firefox 103

### Settings

- uBO annoyances list
- AdGuard annoyances list

**Comment by okiehsch** [comment]
Thx.
The adobe filter is an ad not an annoyance, so I did not include it.
@ryanbr 
`behance.net##[class*="StockRail-rail-"]`
