### ISSUE TITLE
explorecams.com: detection

### ISSUE THREAD

**Issue by okacca** [uBlockOrigin/uAssets#14345]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://explorecams.com/`

### Category

detection

### Describe the issue

The site detects the uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-08-10 at 23-33-35 Canon EOS M50 (EOS Kiss M) sample photo](https://user-images.githubusercontent.com/111018238/184015212-8591b3ea-9bf2-4415-a4bc-b52b5942997e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 104661
  cosmetic: 118519
  scriptlet: 20015
  html: 723
listset (total-discarded, last updated): 
  added: 
    adguard-spyware: 26770-1001, 4m
    fanboy-annoyance: 75416-280, 4d.7h.50m
  default: 
    user-filters: 8-0, never
    ublock-filters: 33097-52, 21m
    ublock-badware: 4180-0, 20m
    ublock-privacy: 247-0, 4d.7h.52m
    ublock-abuse: 76-0, 4d.7h.51m
    ublock-unbreak: 1867-0, 19m
    easylist: 69313-623, 18m
    easyprivacy: 27316-9816, 23m
    urlhaus-1: 4918-0, 16m
    plowe-0: 3634-3, 1d.1h.2m
    TUR-0: 8736-67, 22m
    ublock-quick-fixes: 355-1, 17m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 36 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1071 ms (selfie)
  maxAssetCacheWait: 537 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    nitropay.com: 4
```
</details>

**Comment by KandiKlover** [comment]
This still an issue when trying to use the site. Shouldn't have to play with the zapper since it's a fixed feature of the site.
