### ISSUE TITLE
bizjournals.com: detection

### ISSUE THREAD

**Issue by oconnorv** [uBlockOrigin/uAssets#14342]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bizjournals.com/charlotte/news/2021/09/17/mecklenburg-county-highest-paid-employees.html`

### Category

detection

### Describe the issue

javascript to detect uBlock. But they use so much js on the site that blocking js renders the site useless.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 84527
  cosmetic: 93370
  scriptlet: 20218
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55812-75, 2m
  default: 
    user-filters: 4-0, never
    easylist: 69302-91, 2d.2h.25m
    easyprivacy: 27302-221, 2d.2h.26m
    plowe-0: 3634-778, 1d.22h.23m
    ublock-abuse: 76-0, 2d.2h.29m
    ublock-badware: 4176-92, 2d.2h.27m
    ublock-filters: 32398-492, 2d.2h.24m
    ublock-privacy: 230-3, 5d.15h.18m
    ublock-quick-fixes: 376-1, 2m
    ublock-unbreak: 1851-44, 2d.2h.28m
    urlhaus-1: 4918-0, 2m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 38 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 952 ms (selfie)
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    bizjournals.com: 2
    adobedtm.com: 4
    airtable.com: 6
    bounceexchange.com: 1
    brandmetrics.com: 1
    cookielaw.org: 2
    crwdcntrl.net: 1
    demdex.net: 1
    doubleclick.net: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    indexww.com: 1
    marketo.net: 1
    moatads.com: 3
    newrelic.com: 1
    p-n.io: 1
    sail-horizon.com: 1
    scorecardresearch.com: 1
    sentry.io: 2
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce with chromium even if I add adguard annoyance.
