### ISSUE TITLE
total-croatia-news.com: ads

### ISSUE THREAD

**Issue by eoc-flux** [uBlockOrigin/uAssets#14340]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.total-croatia-news.com/`

### Category

ads

### Describe the issue

Mastercard ads now visible on most pages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 56
filterset (summary): 
  network: 80232
  cosmetic: 45147
  scriptlet: 17578
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33081-36, 1d.23h.49m
    ublock-badware: 4175-1, 3d.11h.25m
    ublock-privacy: 247-0, 2d.7h.51m
    ublock-abuse: 76-0, 12d.39m
    ublock-unbreak: 1867-0, 1d.17h.40m
    ublock-quick-fixes: 352-1, 41m
    easylist: 69158-238, 5d.18h.51m
    easyprivacy: 27302-155, 1d.17h.41m
    urlhaus-1: 5164-0, 42m
    plowe-0: 3638-780, 11d.20h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 675 ms (selfie)
  maxAssetCacheWait: 160 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    total-croatia-news.com: 9
    doubleclick.net: 2
    ezodn.com: 3
    ezojs.com: 2
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by MasterKia** [comment]
```
||total-croatia-news.com/images/banners/
total-croatia-news.com##.custombanner
```
Maybe one of them.

@ryanbr

**Comment by MasterKia** [comment]
> Firefox: 56

PLEASE update your browser, it's 5 years old.

**Comment by eoc-flux** [comment]
Using current version of Waterfox Classic.  The ads also appear in 
current version of chrome.
