### ISSUE TITLE
stream.cz: ads

### ISSUE THREAD

**Issue by marcelpetran** [uBlockOrigin/uAssets#14346]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.stream.cz/mistri-volantu/na-moste-se-splasil-kamaz-smolari-po-narazu-zacalo-auto-horet-64370004?utm_source=odebirane-porady&utm_medium=notifikace`

### Category

ads

### Describe the issue

Ads in video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80550
  cosmetic: 45557
  scriptlet: 17749
  html: 0
listset (total-discarded, last updated): 
  added: 
    CZE-0: 716-0, 4h.1m
  default: 
    user-filters: 0-0, never
    easylist: 69309-53, 22h.31m
    easyprivacy: 27306-128, 1d.2h.32m
    plowe-0: 3639-777, 9d.35m
    ublock-abuse: 76-0, 4h.3m
    ublock-badware: 4176-92, 1d.2h.34m
    ublock-filters: 32396-121, 1d.2h.33m
    ublock-privacy: 230-3, 9d.4h.44m
    ublock-quick-fixes: 375-1, 4h.2m
    ublock-unbreak: 1855-43, 1d.2h.35m
    urlhaus-1: 5164-0, 8h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 362 ms (selfie)
  maxAssetCacheWait: 161 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    stream.cz: 3
    adform.net: 2
    adnxs.com: 1
    gemius.pl: 2
    googletagmanager.com: 1
```
</details>

**Comment by MasterKia** [comment]
@tomasko126
@addisr 

Can you reproduce?

**Comment by marcelpetran** [comment]
Sometimes is not shown for the first time, but give it a refresh few times and it will show up.
[screenshot](https://imgur.com/nxInIEv)

**Comment by stephenhawk8054** [comment]
Yup, I can reproduce after refreshing.

@marcelpetran Can you check if adding this filter works?

`||stream.cz/*/v2/vast$xhr`

**Comment by ghajini** [comment]
i can reproduce after multiple refreshes of webpage, said filter works
