### ISSUE TITLE
insiderstore.com.br: breakage

### ISSUE THREAD

**Issue by diegoweb** [uBlockOrigin/uAssets#14347]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.insiderstore.com.br/products/tech-t-shirt`

### Category

breakage

### Describe the issue

The buttons that says: PROVADOR VIRTUAL and TABELA DE MEDIDAS are gone. They are reponsible to open an inside popup to show the sizes of the clothes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Without Ublock Origin:
![image](https://user-images.githubusercontent.com/12632119/184047234-f864a256-2a62-47be-8531-bb5174dcf1c8.png)

With Ublock Origin:
![image](https://user-images.githubusercontent.com/12632119/184046632-ffe4046e-d5ad-4061-8eef-d912838151bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 123177
  cosmetic: 197573
  scriptlet: 37552
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/2.txt: 135967-1523, 1d.21h.44m
    https://raw.githubusercontent.com/anudeepND/youtubeadsblacklist/master/hosts.txt: 8882-0, 1d.9h.34m
    https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt: 2625-94, 1d.9h.33m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-224, 1d.5h.31m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-1, 1d.5h.30m
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt: 34-34, 1d.5h.29m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-104, 1d.5h.28m
    adguard-annoyance: 55712-197, 1d.21h.48m
    fanboy-annoyance: 78410-3494, 27m
    fanboy-social: 23268-23264, 1d.21h.45m
    spa-1: 4588-100, 1d.21h.43m
    ublock-annoyances: 4518-245, 1d.21h.42m
  default: 
    user-filters: 206-10, never
    easylist: 69314-69282, 1d.21h.47m
    easyprivacy: 27306-413, 1d.21h.46m
    plowe-0: 3634-2318, 3d.9h.31m
    ublock-abuse: 76-0, 4d.9h.37m
    ublock-badware: 4176-323, 1d.21h.41m
    ublock-filters: 32396-3960, 1d.21h.40m
    ublock-privacy: 231-11, 4d.9h.36m
    ublock-quick-fixes: 374-13, 1h.34m
    ublock-unbreak: 1854-95, 1d.21h.39m
    urlhaus-1: 4918-0, 1h.33m
filterset (user): [array of 209 redacted]
trustedset: 
  added: [array of 103 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 60 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 570 ms (selfie)
  maxAssetCacheWait: 449 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    app-us1.com: 1
    bugsnag.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    k-analytix.com: 1
    klaviyo.com: 2
    lgpdy.com: 1
    pinimg.com: 1
    shopify.com: 2
    shopifysvc.com: 6
    useinsider.com: 1
    zdassets.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`@@||googletagmanager.com/gtm.js$script,domain=insiderstore.com.br`

@ryanbr
