### ISSUE TITLE
tweaktown.com: ads

### ISSUE THREAD

**Issue by dovigz** [uBlockOrigin/uAssets#14344]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tweaktown.com/news/87834/metas-most-advanced-ai-chatbot-goes-after-its-own-ceo-mark-zuckerberg/index.html`

### Category

ads

### Describe the issue

Shows a ad for something i searched on amazon this morning 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/28153305/183999859-98c5a569-68b8-4bd6-add8-2ed9b644d7f7.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80081
  cosmetic: 45228
  scriptlet: 17589
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 69310-51, 1d.15h.49m
    easyprivacy: 27306-123, 1d.15h.53m
    plowe-0: 3634-776, 2d.2h.41m
    ublock-abuse: 76-0, 3d.17h.44m
    ublock-badware: 4176-92, 1d.15h.52m
    ublock-filters: 32396-121, 1d.15h.51m
    ublock-privacy: 231-3, 3d.17h.43m
    ublock-quick-fixes: 375-1, 1h.56m
    ublock-unbreak: 1852-43, 1d.15h.50m
    urlhaus-1: 4918-0, 1h.55m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 542 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    ocelot.studio: 1
    outbrain.com: 1
```
</details>

**Comment by okiehsch** [comment]
`tweaktown.com##.product_box`
@ryanbr
