### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by dionyziz** [uBlockOrigin/uAssets#14349]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Describe the issue

When uBlockOrigin is enabled, Reddit's login pop-up form appears blank. When uBlockOrigin is disabled, the login form appears fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="Screenshot 2022-08-10 at 20 34 05" src="https://user-images.githubusercontent.com/544572/184060793-9327c6f2-2a4f-494a-b30c-b7d95108430b.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 92432
  cosmetic: 176628
  scriptlet: 24570
  html: 730
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55823-4644, 5h.25m
    adguard-social: 18130-24, 5h.26m
    fanboy-annoyance: 77664-39734, 7d.12h.17m
    fanboy-cookiemonster: 38501-132, 7d.12h.18m
    ublock-annoyances: 4526-4, 5h.39m
    GRC-0: 1002-1, 5h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33097-52, 5h.36m
    ublock-badware: 4180-0, 5h.35m
    ublock-privacy: 247-0, 4d.11h.43m
    ublock-abuse: 76-0, 4d.11h.42m
    ublock-unbreak: 1867-0, 5h.34m
    easylist: 69313-589, 5h.33m
    easyprivacy: 27316-582, 5h.38m
    urlhaus-1: 4918-0, 4h.51m
    plowe-0: 3634-3, 4d.11h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1125 ms (selfie)
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    reddit.com: 5
    redditmedia.com: 1
    redditstatic.com: 20
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce using Firefox.
>   added: 
    adguard-annoyance: 55823-4644, 5h.25m
    adguard-social: 18130-24, 5h.26m
    fanboy-annoyance: 77664-39734, 7d.12h.17m
    fanboy-cookiemonster: 38501-132, 7d.12h.18m
    ublock-annoyances: 4526-4, 5h.39m
    GRC-0: 1002-1, 5h.24m

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

Please test with **_only the default lists_**.

**Comment by krystian3w** [comment]
Bad may is filter from AG Annoyances:

`reddit.com##+js(remove-class, scroll-disable, body)`

If I disable then login back.

But devtools show for my hide iframes by procedural filtering - so interesting is why scriptlet can break iframes.

Before lament to AG maybe needed found is unknown bad iframe hide filtering.

**Comment by MasterKia** [comment]
> Bad filter from AG Annoyances:
`reddit.com##+js(remove-class, scroll-disable, body)`
If I disable then login back.

@Yuki2718

**Comment by MasterKia** [comment]
@krystian3w That filter doesn't break the login prompt for me using Firefox.

**Comment by krystian3w** [comment]
Try these (Also form uBo Annoyances):

`||reddit.com/account/sso` # and later remove

**Comment by BlazDT** [comment]
Login window shows up fine here.

**Comment by krystian3w** [comment]
On my PC this filter works bad with uBo as long have enabled "hide placeholders for blocked items".

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#hide-placeholders-of-blocked-elements

So I please consider disable these for uBo. I think this can be race condition if page use one iframe with restyle to big pop-up.

**Comment by krystian3w** [comment]
Video with error in logic or race conditions to unhide node after change in Dom tree (fyi @gorhill, @gwarser, @uBlock-user):


https://user-images.githubusercontent.com/35370833/184105366-b4ee2899-8184-4db0-8be7-743644bfc843.mp4

Sorry for blinks.

**Comment by gorhill** [comment]
The filter `||reddit.com/account/sso` from AdGuard Annoyances is causing the issue, please report to AdGuard people. Meanwhile you can use `||reddit.com/account/sso$badfilter` to disable that filter.

**Comment by MasterKia** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
I can reproduce (there are cases that Login button brings 1. redirect vs. 2. popup) and it happens only on uBO. Redirecting the frame to noop.html seems to work.

**Comment by MasterKia** [comment]
If you go with option 2 and someone has both uBO and AG Annoyances (like OP), then what would happen?

**Comment by Yuki2718** [comment]
> If you go with option 2 and someone has both uBO and AG Annoyances (like OP), then what would happen?

Will be redirected so no problem.

**Comment by Yuki2718** [comment]
I will exclude uBO (Option 1). If if's useful we can add the redirect rule any time, but so far I can't reproduce the original popup in the AG issue.

**Comment by gorhill** [comment]
> happens only on uBO

I checked with AdGuard, and I find that it does not collapse the matching `iframe` which is blocked by the network filter. Doesn't AdGuard support collapsing the placeholder of elements associated with blocked network requests?

**Comment by Yuki2718** [comment]
Assuming you're talking about Extension, from my experience I assume it collapses. Not on Apps (remove from source) and iOS (no collapse). @ameshkov

**Comment by uBlock-user** [comment]
> I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

OP didn't perform this and wasn't honest about it either.

**Comment by krystian3w** [comment]
But more network filters can generate same glitch.
