### ISSUE TITLE
my.wealthsimple.com: breakage

### ISSUE THREAD

**Issue by whatsup1827** [uBlockOrigin/uAssets#14348]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.wealthsimple.com/`

### Category

breakage

### Describe the issue

Entire website won't load when ublock is enabled, when I disable it the website loads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/23003809/184054046-396a6dbc-b0f3-4425-a31e-e80e2ec06b4c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80088
  cosmetic: 45227
  scriptlet: 17593
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69310-51, 1d.25m
    easyprivacy: 27306-123, 1d.24m
    plowe-0: 3634-776, 3d.9h.2m
    ublock-abuse: 76-0, 4d.1h.23m
    ublock-badware: 4176-92, 1d.23m
    ublock-filters: 32407-121, 1d.22m
    ublock-privacy: 231-3, 4d.1h.22m
    ublock-quick-fixes: 374-1, 4h.16m
    ublock-unbreak: 1854-43, 1d.21m
    urlhaus-1: 4918-0, 3h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 181 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    maps.googleapis.com: 1
    rollbar.com: 1
    segment.com: 1
```
</details>

**Comment by krystian3w** [comment]
Protected by Canadian human ID.

**Comment by Yuki2718** [comment]
@gorhill Can you possibly check?

**Comment by krystian3w** [comment]
@whatsup1827 can you show logger with only blocked and redirected "elements"?
