### ISSUE TITLE
wiadomosci.onet.pl: ads

### ISSUE THREAD

**Issue by tomekdot** [uBlockOrigin/uAssets#14343]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wiadomosci.onet.pl/slask/pozar-w-elektrowni-jaworzno-ii-plonie-tasmociag-brak-poszkodowanych/n8jb7y5`

### Category

ads

### Describe the issue

A field with the ad removed is visible on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 83683
  cosmetic: 26903
  scriptlet: 17612
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33210-311, 5h.45m
    ublock-badware: 4179-0, 5h.35m
    ublock-privacy: 246-1, 1d.1h.41m
    ublock-abuse: 76-0, 1d.1h.40m
    ublock-unbreak: 1869-0, 5d.5h.14m
    ublock-quick-fixes: 341-1, 5h.29m
    adguard-mobile: 8075-168, 5h.46m
    easylist: 69220-25101, 5d.4h.55m
    easyprivacy: 27490-590, 5d.4h.54m
    urlhaus-1: 6920-0, 2d.4h.4m
    plowe-0: 3640-3, 5d.4h.47m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    onet.pl: 8
    doubleclick.net: 1
    dreamlab.pl: 3
    gemius.pl: 1
    googletagmanager.com: 2
    ocdn.eu: 2
    pushpushgo.com: 2
```
</details>

**Comment by tomekdot** [comment]
![Screenshot_20220810-175941_Firefox](https://user-images.githubusercontent.com/73403480/183957368-e656d70d-f516-433b-b86b-aa7a929de9c8.jpg)

**Comment by MasterKia** [comment]
```
onet.pl##[class^="AdSlotPlaceholder"]
onet.pl##[class^="AdPlaceholder"]
onet.pl##[class^="CenterAd"]

onet.pl##[class*="EmbeddedApplication_moneteasy"]
```
Check if the last one is really an ad.

@MajkiIT

**Comment by MasterKia** [comment]
@tomekdot 
Go to uBlock Origins settings > Filter lists > Regions, languages
Then enable the two "POL" lists and wait for the fix.

**Comment by MajkiIT** [comment]
@MasterKia Thanks a lot

**Comment by MasterKia** [comment]
@tomekdot Force update your lists in 10 minutes.
