### ISSUE TITLE
go.slink.bid: detection

### ISSUE THREAD

**Issue by FabulousSpaceCat** [uBlockOrigin/uAssets#14354]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://go.slink.bid/t5GpJDr`

### Category

detection

### Describe the issue

"Warning, Adblock Detected !
Our website is made possible by displaying online advertisements to our visitors.
Please consider supporting us by disabling your ad blocker. "

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 105
filterset (summary): 
  network: 81393
  cosmetic: 46388
  scriptlet: 17724
  html: 723
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 12h.46m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 3m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33094-59, 3d.5h
    ublock-badware: 4180-0, 3d.4h.59m
    ublock-privacy: 247-0, 2d.5h.10m
    ublock-abuse: 76-0, 2d.5h.9m
    ublock-unbreak: 1867-2, 3d.4h.58m
    easylist: 69302-607, 3d.4h.57m
    easyprivacy: 27302-584, 3d.4h.56m
    urlhaus-1: 4947-0, 12h.48m
    plowe-0: 3634-3, 2d.5h.7m
    ublock-quick-fixes: 379-1, 12h.47m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 753 ms (selfie)
  maxAssetCacheWait: 159 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    a-ads.com: 1
    exdynsrv.com: 2
    glugherg.net: 2
    googlesyndication.com: 4
    greatdexchange.com: 2
    jads.co: 2
    tqibyjqyly.com: 5
    velocitycdn.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
go.slink.bid##+js(no-fetch-if, adsbygoogle)
```

**Comment by MasterKia** [comment]
@FabulousSpaceCat You can install the FastForward add-on, it helps to bypass _**some**_ of these shortlinks.
https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/
