### ISSUE TITLE
addictinggames.com: ads

### ISSUE THREAD

**Issue by MilesW-98** [uBlockOrigin/uAssets#14356]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.addictinggames.com/io-games/megachessio`

### Category

ads

### Describe the issue

When using this site every time I press play to play a game, the game never loads. As a result at the top of the screen says "ADVERTISEMENT - YOUR GAME WILL START IN 00:00" it gets stuck and the game never loads as intended. The only way to use this site is turn uBlock off for this site or get their premium game pass it seems, otherwise it breaks, metaphorically, the game from loading because it believes an ad should play and it doesn't with uBlock on.

### Screenshot(s)
https://user-images.githubusercontent.com/48692365/184263810-c432ce71-5ff6-43b6-aa04-5bfebd689a8b.png

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 79942
  cosmetic: 45248
  scriptlet: 17594
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69326-51, 21h.20m
    easyprivacy: 27317-123, 21h.19m
    plowe-0: 3634-776, 3d.9h.51m
    ublock-abuse: 76-0, 4d.5h.18m
    ublock-badware: 4176-92, 21h.22m
    ublock-filters: 32408-121, 21h.23m
    ublock-privacy: 231-3, 4d.5h.19m
    ublock-quick-fixes: 379-1, 48m
    ublock-unbreak: 1854-43, 21h.21m
    urlhaus-1: 4761-0, 47m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 718 ms (selfie)
  maxAssetCacheWait: 155 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    3lift.com: 2
    adnxs.com: 4
    casalemedia.com: 1
    doubleclick.net: 1
    google-analytics.com: 2
    indexww.com: 1
    openx.net: 2
    pubmatic.com: 2
    rubiconproject.com: 2
    scorecardresearch.com: 1
```
</details>

**Comment by Procyon-b** [comment]
There is a frame on that particular page that can't be loaded: `megachess.io’s server IP address could not be found.`

**Comment by LikesCakes** [comment]
`https://www.addictinggames.com/mmo/big-farm`

@AdamWr

**Comment by stephenhawk8054** [comment]
I can't load the game even when turning off uBO.
