### ISSUE TITLE
channel4.com: breakage

### ISSUE THREAD

**Issue by loc3219** [uBlockOrigin/uAssets#14352]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.channel4.com/`

### Category

breakage

### Describe the issue

I have not put it down as detected as there is not the usual message to disable ad-blocker. It seems that when uBlock is active and I go to hit play on any programme, the page remains in a loading state indefinitely and I cannot play the programme until I hvae disabled uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80328
  cosmetic: 45207
  scriptlet: 17580
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33094-124, 3d.4h.47m
    ublock-badware: 4180-0, 3d.4h.46m
    ublock-privacy: 247-0, 3d.4h.42m
    ublock-abuse: 76-0, 3d.4h.41m
    ublock-unbreak: 1865-0, 3d.4h.45m
    ublock-quick-fixes: 355-1, 1d.1h.56m
    easylist: 69301-505, 3d.4h.44m
    easyprivacy: 27300-133, 3d.4h.43m
    urlhaus-1: 5164-0, 1d.1h.55m
    plowe-0: 3640-451, 7d.20h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1529 ms (selfie)
  maxAssetCacheWait: 599 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    channel4.com: 1
    braze.eu: 2
    c4assets.com: 3
    optimizely.com: 2
```
</details>

**Comment by elite4jonny** [comment]
Same issue, Firefox, Ublock origin, Linux, default filters

Website functions but video will not play, continual buffering, if ublock disabled then video will play (with ads) and ublock can be enabled without issues.

Issue #14352

**Comment by ghajini** [comment]
does following filter work when you put into ubo my filters

`channel4.com#@#+js(set, Object.prototype.AdRequest, noopFunc)`

also confirm whether you get ads or not


i tried above filter & watched a video, i don't get any ads

**Comment by elite4jonny** [comment]
Seems to have fixed it thanks!

Not sure if it's just GitHub formatting but on my notification there was a space between "set," and "Object" while on the mobile site it's showing a space after "AdRequest,"

**Comment by ghajini** [comment]
update ublock filters in couple of minutes ,

**Comment by elite4jonny** [comment]
Seems to be a small issue - 5 to 10 seconds into a video starting the image freezes or returns to the splash screen but audio continues
