### ISSUE TITLE
utreon.com: breakage

### ISSUE THREAD

**Issue by NatTuck** [uBlockOrigin/uAssets#14353]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://utreon.com/v/maTqqPAxQiK`

### Category

breakage

### Describe the issue

Video won't play on utreon. Plays with ublock disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 91
filterset (summary): 
  network: 106699
  cosmetic: 147843
  scriptlet: 34679
  html: 730
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-10, 4d.21h.21m
    ublock-annoyances: 4530-8, 1d.1h.4m
    adguard-generic: 66761-5396, 1d.1h.9m
    fanboy-thirdparty_social: 68-0, 4d.1h.18m
    fanboy-annoyance: 77850-378, 6d.5h.32m
  default: 
    user-filters: 32-1, never
    ublock-filters: 33111-73, 1d.1h.6m
    ublock-badware: 4180-0, 1d.1h.5m
    ublock-privacy: 246-0, 8d.9h.39m
    ublock-abuse: 76-0, 8d.9h.38m
    ublock-unbreak: 1867-1, 1d.1h.10m
    easylist: 69313-608, 1d.1h.8m
    easyprivacy: 27313-622, 1d.1h.7m
    plowe-0: 3634-4, 5d.1h.29m
    urlhaus-1: 4918-0, 17h.3m
    ublock-quick-fixes: 371-1, 17h.2m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 102 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 492 ms (selfie)
  maxAssetCacheWait: 746 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    utreon.com: 2
```
</details>

**Comment by okiehsch** [comment]
`Firefox: 91` what browser is this?

**Comment by NatTuck** [comment]
The about screen shows version 91.12.0esr (64-bit). Stock browser on Debian 11.

**Comment by okiehsch** [comment]
I don't run Debian, the videos play fine on my end using the latest Chromium and Firefox versions on my end.
Can you test if the videos play with the latest Chromium versions on your end?

**Comment by MasterKia** [comment]
Video plays fine on Fedora using Firefox 100+ but I'm getting pre-roll ads, weird.

**Comment by stephenhawk8054** [comment]
> Video plays fine on Fedora using Firefox 100+ but I'm getting pre-roll ads, weird. https://user-images.githubusercontent.com/17685483/184312612-830e2a6e-f8e5-49cc-b302-c056459baf7a.png

Does this one work for you?

`utreon.com##+js(json-prune, videos)`

**Comment by MasterKia** [comment]
Yes it works.
Also `utreon.com##.ad-banner-static`
