### ISSUE TITLE
mtv.fi: ads on videos

### ISSUE THREAD

**Issue by Popedigoz** [uBlockOrigin/uAssets#14368]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.mtv.fi/sarja/taxi-driver-10004111`

It's a finnish (free-to-watch) site with annoying video-ads that may have 7 of them each being 10-45s long. You might want to use a vpn to test 

### Describe the issue

I don't know how to block video ads on this site while trying to watch something, without it crying about that an adblocker was enabled.

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103.0.2 (64-bit)

### Settings

wat

**Comment by MasterKia** [comment]
@Popedigoz Go to uBlock Origin settings => Filter lists => Regions, languages => Enable the "FIN" filterlist and test again.

**Comment by MasterKia** [comment]
@peace2000 Can you reproduce?

**Comment by Popedigoz** [comment]
> @Popedigoz Go to uBlock Origin settings => Filter lists => Regions, languages => Enable the "FIN" filterlist and test again.

@MasterKia 

That seems to have done the trick, thanks. However, I wonder why it's not automatically enabled?

**Comment by MasterKia** [comment]
uBlock Origin will check for your browser language after installation, so if your browser language was Finnish then uBO would've enabled the list for you.
