### ISSUE TITLE
[nsfw] stripchat.com: ads

### ISSUE THREAD

**Issue by searchHz3** [uBlockOrigin/uAssets#14363]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stripchat.com/`

### Category

ads

### Describe the issue

edit from closed issue.
ad from redirect site:
`https://go.xlivrdr.com/api/goToTheTag?campaignId=ff2af6e688847e2330f5e4fecf1b6e4800161adc13d601c3f42356e0b206da0d&campaignType=smartpop&creativeId=4ae70553c37573f455aa087e182b0526aefd59c3377ac421659f87b45b91c97d&iterationId=90235&masterSmartpopId=0&memberId=io9nd79e0ut513rkrmfc&p1=176172&ruleId=0&smartpopId=3306&sourceId=D076FG0B9U&tag=girls%2Fchinese&userId=158ab6ae94c92b9e84e23bd988f6815c3399840c5d6cecc72f6d7e0d2c66bf64&variationId=25803`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 80147
  cosmetic: 45262
  scriptlet: 17589
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33098-37, 14h.55m
    ublock-badware: 4180-0, 14h.54m
    ublock-privacy: 247-0, 14h.53m
    ublock-abuse: 76-0, 14h.52m
    ublock-unbreak: 1867-0, 14h.51m
    ublock-quick-fixes: 379-1, 14h.50m
    easylist: 69331-571, 14h.49m
    easyprivacy: 27324-580, 14h.48m
    urlhaus-1: 4947-0, 14h.47m
    plowe-0: 3634-3, 14h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1277 ms (selfie)
  maxAssetCacheWait: 579 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    amplitude.com: 1
    cloudflare.com: 1
    exoclick.com: 1
    google-analytics.com: 1
    trafficjunky.net: 1
    tsyndicate.com: 1
    xxxivjmp.com: 1
```
</details>

**Comment by okiehsch** [comment]
I don't understand the issue are you getting redirected to this site or are getting redirected while you surf on this site?

**Comment by HongZhe3** [comment]
i got redirected to this site by the link mentioned in comments

**Comment by okiehsch** [comment]
And how did you end up at
`go.xlivrdr.com`?

**Comment by HongZhe3** [comment]
https://w1.opomanga.com/

**Comment by okiehsch** [comment]
Thx. We need the links you encounter the redirections at not the redirection link itself.

**Comment by HongZhe3** [comment]
what pages i was surfing when i got redirected u mean?

**Comment by okiehsch** [comment]
Yes, that's the only way we can investigate and potentially fix your issues.

**Comment by searchHz3** [comment]
i will keep this in mind when i report new redirection links
