### ISSUE TITLE
[nsfw] groglezapto.pro: popups

### ISSUE THREAD

**Issue by blitzHz3** [uBlockOrigin/uAssets#14360]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://groglezapto.pro/`

### Category

popups

### Describe the issue

redirects me to dangerous sites

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 80147
  cosmetic: 45262
  scriptlet: 17589
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33098-37, 14h.24m
    ublock-badware: 4180-0, 14h.23m
    ublock-privacy: 247-0, 14h.22m
    ublock-abuse: 76-0, 14h.21m
    ublock-unbreak: 1867-0, 14h.20m
    ublock-quick-fixes: 379-1, 14h.19m
    easylist: 69331-571, 14h.18m
    easyprivacy: 27324-580, 14h.17m
    urlhaus-1: 4947-0, 14h.16m
    plowe-0: 3634-3, 14h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1277 ms (selfie)
  maxAssetCacheWait: 579 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
We need the site where the redirects occur.

**Comment by okiehsch** [comment]
Is this also happening opomanga?

**Comment by HongZhe3** [comment]
yes, it was before i discovered this ad blocker

**Comment by okiehsch** [comment]
Are all your issues caused by opomanga?

**Comment by searchHz3** [comment]
there are other sites that also have this, i believe it is bc they are... "unofficial" sites

**Comment by searchHz3** [comment]
https://arifuretamanga.online/ is another example

**Comment by okiehsch** [comment]
For the issues you opened we need the names of those sites.
I added a fix for opomanga, if you wait a few minutes and then update your filter lists the redirects on opomanga should be gone.
I will leave this issue open and close your other ones.
If you find other sites post them here.

**Comment by blitzHz3** [comment]
thank you

**Comment by blitzHz3** [comment]
page URL: https://mangakakalot.com
redirection link: https://mywondertrip.com/news/11727051/?utm_campaign=promo&utm_medium=article&utm_content=P3DtuVLEADo0k0TyyMp0QcPXiSC*6Kknx_Ew8B7PrDwuwV2lFDyFq*v*lZu0M*GD9TikLO_dsDqXLhH4P7gV10pWTb_T3le_MXIf1WcPqOzemuKukodfJeoXIM0RHxIZyhiKTnETgRwaugNJ4njIRmIgBJyhpK6aoIt0Y0lNcuq44DasVrGC8yRV9Mwkn8lfBcc2M7Y2IHKIaNsXeNixKXGMsph3YgnTeoyqOMlUuSdm9xcMkXPzCUaq2KmcKhQo905I*8ZzIyM2TTDKYgqcjr1djMxlCGca9Qy4aUaguq0RAlGPXXaWtOJM1yJrqptc4YKOoAmzcaQP1e4m3q2Swpp_sKq04x3_vRj7V6whLMKdLQYd9u3oZSvN65sJSGxMmQPpKShVX9BLjOf1L4AJMb08KNpe*shZzxHx7ZoyPxAUZXuNXpHRwGe*FwCbUQ6ZCdvQHzDRsniiN21X4EIctw
original link: https://mangakakalot.com/manga/pn926289
