### ISSUE TITLE
loot.jfrog.io: nuisance

### ISSUE THREAD

**Issue by sibir-ine** [uBlockOrigin/uAssets#14367]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://loot.jfrog.io/ui/native/loot`

### Category

nuisance

### Describe the issue

When opening the link, the user is redirected to a login page that can be bypassed by pressing the difficult-to-see `x` button in the top-right corner as an account is not required to access the site. However, upon reopening the site, attempting to dismiss the login page will briefly take the user to the desired page but will redirect back to the login page in a loop. The only way to get around this is to hard-reset the page (i.e., `Ctrl` + `F5` in Firefox & Chrome to clear cookies & cache), but the issue will return the next time the user attempts to access the page. Since logging in is unnecessary to access the site & can be done elsewhere if needed, it'd be ideal if the redirection to the login page could be avoided entirely.

This occurs when trying to access other areas of the artifact manager, e.g., `https://loot.jfrog.io/ui/repos/tree/General/artifactory-build-info`, & I assume it happens for other repositories, so this may apply to anything under `https://*.jfrog.io/`. However, we do have anonymous access enabled, so I don't know how that'd affect repos that have it disabled; it might actually be better to do it on a case-by-case basis.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

The `x` button to bypass the login screen, highlighted by a red box

![image](https://user-images.githubusercontent.com/69141501/184296211-3ff3c81e-a6d4-45b0-a88a-51498755c4ce.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80446
  cosmetic: 45242
  scriptlet: 17592
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33100-37, now
    ublock-badware: 4211-0, now
    ublock-privacy: 247-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1868-0, now
    ublock-quick-fixes: 367-1, now
    easylist: 69323-571, now
    easyprivacy: 27326-580, now
    urlhaus-1: 5213-0, now
    plowe-0: 3634-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 964 ms
  maxAssetCacheWait: 125 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
@sibir-ine Add these to "My filters" and test:
```
loot.jfrog.io##.el-button.close:style(font-size: 50px !important;)
loot.jfrog.io##+js(cookie-remover, jf_sh)
```

Also try logging in and see if you **_stay logged in_** after reloading and navigating because the cookie-remover might cause a logout.

**Comment by krystian3w** [comment]
uBo cookie renover works bad (generate loop), can you test AdGuard cookie remover scriptlet implementation and network legacy:

||loot.jsfrog.io^$cookie=js_sh

**Comment by MasterKia** [comment]
> uBo cookie renover works bad (generate loop)

Have you reported to uBO-issues?

**Comment by sibir-ine** [comment]
> @sibir-ine Add these to "My filters" and test:
> 
> ```
> loot.jfrog.io##.el-button.close:style(font-size: 50px !important;)
> loot.jfrog.io##+js(cookie-remover, jf_sh)
> ```
> 
> Also try logging in and see if you **_stay logged in_** after reloading and navigating because there's a chance that removing the `jf_sh` cookie might cause a logout.

The filters didn't address the redirection loop, only the `x` button is bigger (which is nice). As for logging in, I tried making an account, but I'm unable to log in with it. I believe only people with administrative access to the repo can log in. I can log into my own repo (that I had to make along with the account), so I tested the filters with that URL instead. They didn't log me out, but they also didn't fix the redirection loop.

**Comment by MasterKia** [comment]
@sibir-ine Does `jfrog.io##+js(cookie-remover)` stop the redirection? (might break the login though)

**Comment by sibir-ine** [comment]
> @sibir-ine Does `jfrog.io##+js(cookie-remover)` stop the redirection? (might break the login though)
> 
> Edit: looks like it doesn't.

Yeah, doesn't look like it stopped it for me either.

**Comment by krystian3w** [comment]
Maybe need use debugger form devtools if isn't easy visible in JS files.

**Comment by sibir-ine** [comment]
> uBo cookie remover works bad (don't hide login / generate loop after click x), can you test AdGuard cookie remover scriptlet implementation and network legacy:
> 
> `||loot.jsfrog.io^$cookie=js_sh`

Assuming you meant `||loot.jfrog.io^$cookie=jf_sh`, that didn't work in AdGuard either. I tried with `js_sh` too just in case, same result.

**Comment by MasterKia** [comment]
I get this in the Console, maybe the site is broken?
https://user-images.githubusercontent.com/17685483/184320967-738917a8-21b2-4b13-9dc7-118909e1143c.png

**Comment by sibir-ine** [comment]
Possibly, I'll see if it's possible to contact them about it.

**Comment by MasterKia** [comment]
> Maybe need use debugger form devtools if isn't easy visible in JS files.

@krystian3w Search for "autoredirect": https://pastetext.net/q1lqqte2za

**Comment by krystian3w** [comment]
error 404, so suspicious (Persian CERT deleted this?).

**Comment by MasterKia** [comment]
Weird.

**Comment by krystian3w** [comment]
Or geo locked portal with fake errors.

**Comment by MasterKia** [comment]
Maybe it was too long.

https://loot.jfrog.io/ui/js/app.416dd45a.js

**Comment by ghajini** [comment]
@sibir-ine you are asking to bypass native feature of website

**Comment by sibir-ine** [comment]
Preventing the bugged redirect loop would be enough if possible. Unfortunately, the site has been practically unresponsive despite multiple attempts to report this to them, so I was hoping this was something that could be accomplished through an ad blocker. I understand if that's not possible or not within the scope of the project.

**Comment by MasterKia** [comment]
> you are asking to bypass native feature of website

It's similar to Pinterest/Instagram which asks for login even for just **_viewing_** the pictures and videos.

**Comment by ghajini** [comment]
> > you are asking to bypass native feature of website
> 
> It's similar to Pinterest/Instagram that asks to login even for just **_viewing_** the pictures and videos.

i think that's altogether a diff issue,int that case you can see posts after that one can see sign in as an annoyance
