### ISSUE TITLE
4ty.me: popups

### ISSUE THREAD

**Issue by HongZhe3** [uBlockOrigin/uAssets#14362]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://4ty.me/`

### Category

popups

### Describe the issue

redirects me to dangerous sites
original site: `http://4ty.me/h6l1fd `

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 80147
  cosmetic: 45262
  scriptlet: 17589
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33098-37, 14h.36m
    ublock-badware: 4180-0, 14h.35m
    ublock-privacy: 247-0, 14h.34m
    ublock-abuse: 76-0, 14h.33m
    ublock-unbreak: 1867-0, 14h.32m
    ublock-quick-fixes: 379-1, 14h.31m
    easylist: 69331-571, 14h.30m
    easyprivacy: 27324-580, 14h.29m
    urlhaus-1: 4947-0, 14h.28m
    plowe-0: 3634-3, 14h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1277 ms (selfie)
  maxAssetCacheWait: 579 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
This is a shortener it redirects you to whatever site one enters.
For example `http://4ty.me/rjlcuo` you will end up at `google.com`.
