### ISSUE TITLE
arura.win [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1437]
URL(s) where the issue occurs

`http://arura.win/FsIjj9x`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
@mapx- Pop-up

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters @mapx-
