### ISSUE TITLE
web.facebook.com recovery code

### ISSUE THREAD

**Issue by kazzy924113** [uBlockOrigin/uAssets#14373]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://web.facebook.com/recover/code/?ph[0]=%2B2348112058706&rm=send_sms&hash=AUbBOOKULIfxzxE6RI4`

### Category

one time password

### Describe the issue

access

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82018
  cosmetic: 43831
  scriptlet: 17169
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32409-97, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-131, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-784, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5238 ms
  maxAssetCacheWait: 1352 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    facebook.com: 2
```
</details>

**Comment by MasterKia** [comment]
> one time password
access

Could you explain more?

**Comment by kazzy924113** [comment]
wanna generate the account link password

**Comment by MasterKia** [comment]
And what happens?

**Comment by MasterKia** [comment]
@kazzy924113 
> default: 
    user-filters: 0-0, never
    ublock-filters: 32409-97, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-131, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-784, never


You should update your lists.

**Comment by kazzy924113** [comment]
can you assist with the password generator or otp bypass
