### ISSUE TITLE
g1.globo.com: breakage

### ISSUE THREAD

**Issue by jakecharlie** [uBlockOrigin/uAssets#14379]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://g1.globo.com/mundo/noticia/2022/08/12/justica-divulga-mandado-que-motivou-operacao-do-fbi-na-casa-de-trump-ex-presidente-tinha-posse-de-documentos-confidenciais.ghtml`

### Category

breakage

### Describe the issue

The video player from https://g1.globo.com and all pages inside www.globo.com does not load when ublock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 87981
  cosmetic: 102460
  scriptlet: 20297
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/easylistbrasil/easylistbrasil/filtro/easylistbrasil.txt: 6460-15, 23h.14m
    https://raw.githubusercontent.com/fabiom/br-paywall/master/br-paywall.txt: 20-0, 4d.1h.7m
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1873-1, 2d.10h.33m
    https://www.i-dont-care-about-cookies.eu/abp/: 25197-4, 1m
    fanboy-cookiemonster: 39323-9120, 1h.38m
    spa-1: 4590-88, 1d.1h.17m
  default: 
    user-filters: 95-5, never
    easylist: 69331-163, 1d.1h.16m
    easyprivacy: 27324-351, 1d.1h.15m
    plowe-0: 3640-778, 9d.2h.4m
    ublock-abuse: 76-0, 9d.2h.4m
    ublock-badware: 4176-93, 1d.1h.14m
    ublock-filters: 32404-158, 1d.1h.13m
    ublock-privacy: 230-4, 9d.2h.4m
    ublock-quick-fixes: 379-1, 23h.13m
    ublock-unbreak: 1855-45, 1d.1h.12m
    urlhaus-1: 4761-0, 23h.15m
filterset (user): [array of 97 redacted]
trustedset: 
  added: [array of 192 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 37 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 3995 ms (selfie)
  maxAssetCacheWait: 710 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    globo.com: 4
    aswpsdkus.com: 1
    doubleclick.net: 1
    glbimg.com: 18
    google-analytics.com: 1
```
</details>

**Comment by jakecharlie** [comment]
![ublock enabled](https://user-images.githubusercontent.com/3200574/184453921-0761417a-3852-42f3-9d65-48e4300d4f52.png)
![ublock disabled](https://user-images.githubusercontent.com/3200574/184453925-cfb74ab0-68fc-46ce-9cdc-4d45f9a87613.png)

**Comment by Procyon-b** [comment]
The problem is with the list "EasyList Brasil"

**Comment by stephenhawk8054** [comment]
It's because of the filters related to `glbimg.com` in your custom filter list:

```yaml
https://raw.githubusercontent.com/easylistbrasil/easylistbrasil/filtro/easylistbrasil.txt: 6460-15, 23h.14m
```

Report to `EasyList Brasil`: https://github.com/easylistbrasil/easylistbrasil

and please check carefully what you have ticked on:

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> - [X] I did not answer truthfully to **all** the above checkpoints

**Comment by jakecharlie** [comment]
Thank you very much!! I deleted Easy List Brasil and now it is working again.
