### ISSUE TITLE
sbs.com.au: detection

### ISSUE THREAD

**Issue by FGmodule** [uBlockOrigin/uAssets#14372]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sbs.com.au/ondemand/`

### Category

detection

### Describe the issue

Attempting to watch a video generates an ad blocker detected notification. When following through to play the video, a playback error occurs.

I have reproduced this error on two browsers (Firefox and Chrome) on two different computers, and tested in incognito mode on both browsers. On one computer I am using the program Portmaster, which will successfully block the ads and avoid these errors when I disable uBlock Origin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/111137150/184381985-577b8dec-4678-4e80-8696-c237e780cf84.png

https://user-images.githubusercontent.com/111137150/184382056-e1288b03-01fb-4f77-9336-724f8e4c1e3d.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 195404
  cosmetic: 216352
  scriptlet: 37863
  html: 730
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-1, 2m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 2m
    https://winhelp2002.mvps.org/hosts.txt: 8730-317, 2m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-10, 2m
    adguard-generic: 66841-5530, 2m
    adguard-mobile: 8124-243, 2m
    adguard-spyware: 26783-1358, 2m
    adguard-annoyance: 55901-4895, 2m
    adguard-social: 18151-1082, 2m
    fanboy-thirdparty_social: 68-0, 2m
    fanboy-annoyance: 78635-62790, 2m
    fanboy-cookiemonster: 39323-132, 2m
    fanboy-social: 23270-31, 2m
    ublock-annoyances: 4529-8, 2m
    dpollock-0: 11380-1723, 2m
    adguard-spyware-url: 710-2, 2m
    block-lan: 43-0, 2m
    curben-phishing: 40599-15, 2m
    curben-pup: 188-0, 2m
  default: 
    user-filters: 25-3, never
    ublock-filters: 33120-109, 3m
    ublock-badware: 4211-4, 3m
    ublock-privacy: 247-0, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1867-2, 3m
    easylist: 69394-1089, 2m
    easyprivacy: 27329-10022, 2m
    plowe-0: 3629-1799, 2m
    urlhaus-1: 5190-0, 2m
    ublock-quick-fixes: 386-1, 2m
filterset (user): [array of 25 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 917 ms (selfie)
  maxAssetCacheWait: 833 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    tremorhub.com: 1
```
</details>

**Comment by okiehsch** [comment]
Does
````
@@||sbs.com.au/ondemand/ad/*$script,1p
@@||publishers.tremorhub.com/getTVID$script,domain=sbs.com.au
````
work?

**Comment by FGmodule** [comment]
> Does
> 
> ```
> @@||sbs.com.au/ondemand/ad/*$script,1p
> @@||publishers.tremorhub.com/getTVID$script,domain=sbs.com.au
> ```
> 
> work?

On Chrome, yes (tested on both computers). On Firefox, no (also tested on both computers).

**Comment by MasterKia** [comment]
> https://user-images.githubusercontent.com/111137150/184382056-e1288b03-01fb-4f77-9336-724f8e4c1e3d.png

Looks like you're using Privacy Badger alongside uBO, does this issue also happen when it's disabled?

**Comment by okiehsch** [comment]
I can reproduce using chromium and firefox, after adding my filters the warning does not come up if I press play and I get to a login page.
I have no account, so I can't investigate any further.

**Comment by FGmodule** [comment]
> > https://user-images.githubusercontent.com/111137150/184382056-e1288b03-01fb-4f77-9336-724f8e4c1e3d.png
> 
> Looks like you're using Privacy Badger alongside uBO, does this issue also happen when it's disabled?

Yep. Enabling/disabling Privacy Badger doesn't change anything.

It was working just fine yesterday on Firefox for me, but today the ad blocker detected notifications came up. I've noticed that even disabling uBlock Origin and Privacy Badger doesn't fix it on Firefox. Since the filters suggested have fixed the issue on Chrome, it's possible some change in Firefox's built-in tracking protection or something is what's being detected.

**Comment by shawon2901** [comment]
> > > https://user-images.githubusercontent.com/111137150/184382056-e1288b03-01fb-4f77-9336-724f8e4c1e3d.png
> > 
> > 
> > Looks like you're using Privacy Badger alongside uBO, does this issue also happen when it's disabled?
> 
> Yep. Enabling/disabling Privacy Badger doesn't change anything.
> 
> It was working just fine yesterday on Firefox for me, but today the ad blocker detected notifications came up. I've noticed that even disabling uBlock Origin and Privacy Badger doesn't fix it on Firefox. Since the filters suggested have fixed the issue on Chrome, it's possible some change in Firefox's built-in tracking protection or something is what's being detected.

I Have Faced Similar Problem With FireFox Android In DropGalaxy..Try Using A VPN That Changes IP & Re Check Or Check 5-6 Hours Later

**Comment by ghajini** [comment]
checked with account available online ,video play fine with a fix suggested
