### ISSUE TITLE
frieze.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14377]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.frieze.com/article/orit-gat-internet-deserts-2022`

### Category

ads

### Describe the issue

There's an ad container at the bottom of the page.

### Screenshot(s)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/110956608/184450263-ab40421a-9cca-4555-bca3-2ae35bb36ce4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 104
filterset (summary): 
  network: 82135
  cosmetic: 81240
  scriptlet: 19254
  html: 723
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 39323-85, 18m
  default: 
    user-filters: 69-0, never
    ublock-filters: 33122-48, 2m
    ublock-badware: 4211-0, 1h.6m
    ublock-privacy: 247-0, 1h.6m
    ublock-abuse: 76-0, 1h.6m
    ublock-unbreak: 1867-0, 1h.6m
    ublock-quick-fixes: 386-1, 1h.6m
    easylist: 69394-604, 2m
    easyprivacy: 27329-580, 2m
    urlhaus-1: 5190-0, 1h.6m
    plowe-0: 3629-3, 2m
filterset (user): [array of 73 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 954 ms
  maxAssetCacheWait: 404 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    frieze.com: 3
    datadoghq-browser-agent.com: 1
    doubleclick.net: 1
    newrelic.com: 1
    onetrust.com: 2
    pelcro.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
frieze.com##[id*="ad-area"]
```

**Comment by stephenhawk8054** [comment]
@ryanbr
