### ISSUE TITLE
sumikai.com: ads

### ISSUE THREAD

**Issue by Chriwro** [uBlockOrigin/uAssets#14386]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sumikai.com/nachrichten-aus-japan/japans-detektiv-conan-flughafen-erstrahlt-in-neuem-look-226954/`

### Category

ads

### Describe the issue

There are some ads left on the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82523
  cosmetic: 48939
  scriptlet: 17583
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33092-49, 2d.20h.36m
    ublock-badware: 4180-0, 2d.20h.37m
    ublock-privacy: 247-0, 5d.37m
    ublock-abuse: 76-0, 5d.38m
    ublock-unbreak: 1867-0, 2d.20h.38m
    easylist: 69313-598, 2d.20h.34m
    easyprivacy: 27313-590, 2d.20h.35m
    urlhaus-1: 5190-0, 20h.19m
    plowe-0: 3634-3, 1d.21h.23m
    DEU-0: 5894-2, 20h.17m
    ublock-quick-fixes: 376-1, 20h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
@ryanbr @monzta

Add:
```
||x.sumikai.com^
sumikai.com##.td-pb-span4
sumikai.com##.tdi_57
sumikai.com##.tdi_67
sumikai.com##.tdi_78
sumikai.com##.tdi_118
sumikai.com##.tdi_148
```

**Comment by krystian3w** [comment]
Sometime also @Khrin edit German files.

**Comment by Yuki2718** [comment]
> Sometimes also @Khrin edit German files.

Rather he is the main maintainer and Ryan doesn't maintain German list.

**Comment by MasterKia** [comment]
> Ryan doesn't maintain German list

Ok. I tagged him because I thought he has write access: https://github.com/uBlockOrigin/uAssets/issues/13392#issuecomment-1137014491

**Comment by monzta** [comment]
Added the blocking rule only as the hiding ones are removing content as well: https://github.com/easylist/easylistgermany/commit/1aa7f61 

Ryan/fanboy doesn't have access to EasyList Germany.

**Comment by MasterKia** [comment]
Ok, maybe the ad blank space could be removed using extended syntax.

**Comment by Yuki2718** [comment]
I know Alex doesn't like even `example.com##somead:upward(1)`. Prefers `example.com##g-parent > parent > somead:upward(1)`

**Comment by MasterKia** [comment]
Then probably needs more than one filter for the different ad spots.

**Comment by Yuki2718** [comment]
But for uAssets we're free to add, if that's safe.

**Comment by MasterKia** [comment]
Ok, I'll test again and add if safe.

**Comment by Yuki2718** [comment]
Isn't upward(1) enough? The lower number, the safer.

**Comment by MasterKia** [comment]
upward(1) leaves a blank space on top of "Weitere Artikel" in this page:
`https://sumikai.com/nachrichten-aus-japan/japans-detektiv-conan-flughafen-erstrahlt-in-neuem-look-226954/`

**Comment by Yuki2718** [comment]
@monzta @Khrin Probably `##.desk` is safe to add.

**Comment by monzta** [comment]
@Yuki2718 thanks, added: https://github.com/easylist/easylistgermany/commit/de19a81
