### ISSUE TITLE
holidaypark.de: breakage

### ISSUE THREAD

**Issue by errror** [uBlockOrigin/uAssets#14382]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.holidaypark.de/de/tickets-0`

### Category

breakage

### Describe the issue

When clicking on `Kaufen sie ihre Tickets` you get redirected to the main page. When clicking the button after disabling uBlockOrigin, a menu pops up on the left where you can buy tickets. So basically uBlockOrigin prevents buying tickets!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![buy-tickets](https://user-images.githubusercontent.com/12214394/184471011-e9646c20-ef3d-43fc-b827-f6d10c531d2b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 91
filterset (summary): 
  network: 82552
  cosmetic: 48924
  scriptlet: 17588
  html: 723
listset (total-discarded, last updated): 
  added: 
    DEU-0: 5894-2, 21h.47m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33105-49, 2d.22h.1m
    ublock-badware: 4180-0, 2d.22h.3m
    ublock-privacy: 247-0, 21h.49m
    ublock-abuse: 76-0, 21h.50m
    ublock-unbreak: 1867-0, 2d.22h
    easylist: 69310-598, 2d.21h.59m
    easyprivacy: 27312-590, 2d.22h.2m
    plowe-0: 3629-3, 5h.45m
    urlhaus-1: 5213-0, 21h.46m
    ublock-quick-fixes: 368-1, 21h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2454 ms (selfie)
  maxAssetCacheWait: 512 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    holidaypark.de: 1
```
</details>

**Comment by MasterKia** [comment]
> When clicking on `Kaufen sie ihre Tickets` you get redirected to the main page.

When I click on the red "Tickets" button I get sent to `https://www.holidaypark.de/de#/convious`, not the main page.

**Comment by MasterKia** [comment]
Using Firefox, with uBO off I have requests to `convious.com` and `convious-app.com` but with uBO on I don't have any third-party requests at all.
