### ISSUE TITLE
jpopsingles.eu: detection

### ISSUE THREAD

**Issue by kofway** [uBlockOrigin/uAssets#14388]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

~`https://www.adslink.pw/MiJPfAGz1Nil`~
`https://www.jpopsingles.eu/`

### Describe the issue

jpopsingles.eu will detect adblock after a few seconds.
~adslink.pw hides the download button upon entering the site.~

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 259434
  cosmetic: 322440
  scriptlet: 40867
  html: 0
listset (total-discarded, last updated): 
  added: 
    ALB-0: 267-1, 14m
    BGR-0: 1091-11, 14m
    CHN-0: 28695-90, 14m
    CZE-0: 716-0, 14m
    DEU-0: 5896-0, 14m
    EST-0: 451-1, 14m
    FIN-0: 1947-1, 14m
    FRA-0: 30456-72, 14m
    GRC-0: 1002-0, 14m
    HUN-0: 2132-1, 14m
    IDN-0: 9211-25, 14m
    IND-0: 11235-0, 14m
    IRN-0: 2238-1, 14m
    ISL-0: 194-1, 14m
    ISR-0: 1635-2, 14m
    ITA-0: 13136-74, 14m
    JPN-1: 7595-15, 14m
    KOR-1: 2920-12, 14m
    LTU-0: 1191-7, 14m
    LVA-0: 392-2, 14m
    [26 lists not shown]: [too many]
  default: 
    user-filters: 4-1, never
    easylist: 69419-1439, 14m
    easyprivacy: 27333-9989, 14m
    plowe-0: 3629-1001, 14m
    ublock-abuse: 76-2, 14m
    ublock-badware: 4228-343, 14m
    ublock-filters: 32459-4231, 14m
    ublock-privacy: 231-45, 14m
    ublock-quick-fixes: 388-13, 14m
    ublock-unbreak: 1858-135, 14m
    urlhaus-1: 5279-1, 14m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1127 ms
  maxAssetCacheWait: 608 ms
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce either of these issues.

> - [X] uBO with default lists/settings

You have enabled all the filter lists on the planet.
Please test using **_only the default lists_**.

**Comment by kofway** [comment]
I just did a factory reset for uBlock and retried the above urls.
adslink.pw is working properly now. However, https://www.jpopsingles.eu/ would still show a banner with adblock detected a few seconds after loading the page.

**Comment by Procyon-b** [comment]
try this:
```
jpopsingles.eu##+js(aeld, load, Blanket)
```

**Comment by kofway** [comment]
Verified the above is working. Detection is no longer showing up after loading the page.

**Comment by garry-ut99** [comment]
Again: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217250785-9b22e12f-92cb-4a09-bd90-a40ad8993eaa.png)

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25098

**Comment by mapx-** [comment]
I cannot reproduce the detection => reset uBO to defaults - disable any other extension - test again

**Comment by jimmysofat6864** [comment]
> I cannot reproduce the detection => reset uBO to defaults - disable any other extension - test again

I tried factory settings and got the same issue. It takes some time to show up but it will show up eventually. I found that navigating around the site and using the search bar and other general website navigation got it to show up. 
![Screenshot 2024-08-29 152503](https://github.com/user-attachments/assets/c441e2bf-3e7e-4acf-9f54-a6e6077c382c)
