### ISSUE TITLE
censor.net: ads

### ISSUE THREAD

**Issue by assc0bar** [uBlockOrigin/uAssets#14389]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://censor.net/`

### Category

ads

### Describe the issue

A lot of ads seems to be integrated into main pages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 98584
  cosmetic: 67315
  scriptlet: 17605
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    RUS-0: 40382-9, 1d.23h.41m
    easylist: 69331-66, 1d.23h.48m
    easyprivacy: 27324-222, 1d.23h.47m
    plowe-0: 3629-781, 1d.6h.54m
    ublock-abuse: 76-1, 1d.23h.46m
    ublock-badware: 4207-92, 1d.23h.45m
    ublock-filters: 32404-128, 1d.23h.44m
    ublock-privacy: 231-3, 1d.23h.43m
    ublock-quick-fixes: 387-1, 22h.53m
    ublock-unbreak: 1855-43, 1d.23h.42m
    urlhaus-1: 5190-0, 22h.52m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 293 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    censor.net: 12
    doubleclick.net: 1
    google-analytics.com: 1
    googleoptimize.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
> ```yaml
>     RUS-0: 40382-9, 1d.23h.41m
> ```

> * [x]  I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
> 

Do it twice.
