### ISSUE TITLE
itsguider.com: detection

### ISSUE THREAD

**Issue by Draminha** [uBlockOrigin/uAssets#14384]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://itsguider.com/best-email-clients-for-windows`

### Category

detection

### Describe the issue

adblock detected, already clean caches and update...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://user-images.githubusercontent.com/27032033/184472987-b61f04ce-05fc-4e05-b8a6-d0bf4e481281.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 107064
  cosmetic: 177862
  scriptlet: 41420
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23907-26, 3m
    adguard-annoyance: 55914-133, 3m
    adguard-social: 18156-864, 3m
    dpollock-0: 11380-1, 3m
    fanboy-annoyance: 78799-4514, 3m
    fanboy-cookiemonster: 39480-39480, 3m
    fanboy-social: 23272-23272, 3m
    fanboy-thirdparty_social: 69-21, 3m
    ublock-annoyances: 4523-229, 3m
  default: 
    user-filters: 23907-23907, never
    easylist: 69419-339, 3m
    easyprivacy: 27330-346, 3m
    plowe-0: 3629-1173, 3m
    ublock-abuse: 76-1, 3m
    ublock-badware: 4207-93, 3m
    ublock-filters: 32455-3302, 3m
    ublock-privacy: 231-11, 3m
    ublock-quick-fixes: 390-6, 3m
    ublock-unbreak: 1856-50, 3m
    urlhaus-1: 5283-0, 3m
filterset (user): [array of 958 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 620 ms (selfie)
  maxAssetCacheWait: 529 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    kaspersky-labs.com: 1
    lowsteelixor.com: 1
```
</details>

**Comment by MasterKia** [comment]
> -[X]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

>   added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23907-26, 3m
    adguard-annoyance: 55914-133, 3m
    adguard-social: 18156-864, 3m
    dpollock-0: 11380-1, 3m
    fanboy-annoyance: 78799-4514, 3m
    fanboy-cookiemonster: 39480-39480, 3m
    fanboy-social: 23272-23272, 3m
    fanboy-thirdparty_social: 69-21, 3m
    ublock-annoyances: 4523-229, 3m

You should test using **_only the default lists_**.

**Comment by stephenhawk8054** [comment]
Looks like it's a redirection page. Can you give original website?

**Comment by Draminha** [comment]
> > * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> 
> > added:
> > https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23907-26, 3m
> > adguard-annoyance: 55914-133, 3m
> > adguard-social: 18156-864, 3m
> > dpollock-0: 11380-1, 3m
> > fanboy-annoyance: 78799-4514, 3m
> > fanboy-cookiemonster: 39480-39480, 3m
> > fanboy-social: 23272-23272, 3m
> > fanboy-thirdparty_social: 69-21, 3m
> > ublock-annoyances: 4523-229, 3m
> 
> You should test using **_only the default lists_**.

Sorry, I tested with this filter disable and get the same insue, I did it again (disable custom filter/apply changes/purge all caches/update) and still get this detection thing...

the original link is: [https://stfly.me/bXwe]
