### ISSUE TITLE
minecraftalpha.net

### ISSUE THREAD

**Issue by LikesCakes** [uBlockOrigin/uAssets#14381]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.minecraftalpha.net/p/install-night-vision-resource-pack.html`

### Describe the issue

- anti-adb
- counter which can be sped up

### uBlock Origin version

1.43.0

### Browser name and version

chrome

### Settings

.

### Notes

https://github.com/AdguardTeam/AdguardFilters/issues/126658

**Comment by Procyon-b** [comment]
Try this:
```
||spadelocket.com^$script,domain=minecraftalpha.net
```

**Comment by LikesCakes** [comment]
I think the domain can be addressed in EasyPrivacy, but couldn't uBlock Origin address the regarded anti-adb with a scriptlet?

**Comment by Procyon-b** [comment]
I don't have the anti-adb message after adding the filter above.

**Comment by stephenhawk8054** [comment]
Network filters are usually preferable to scriptlets. Do you still have anti adb after adding the above filter?

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by Yuki2718** [comment]
We don't add admiral domain, removed https://github.com/uBlockOrigin/uAssets/commit/b420aa44dbc6ae276e071286fd358d40ab726882
@uBlock-user Is this for potential legal issue?

**Comment by Yuki2718** [comment]
Also @pgl

**Comment by MasterKia** [comment]
Admiral anti-adblock remover is in the Chrome store so no legal issues.

https://chrome.google.com/webstore/detail/admiral-sucks/bhkgjcmhgbpmedkghbphnfkjibekjdgp

But Google doesn't allow paywall bypass extensions for legal reasons.

**Comment by stephenhawk8054** [comment]
> We don't add admiral domain, removed [b420aa4](https://github.com/uBlockOrigin/uAssets/commit/b420aa44dbc6ae276e071286fd358d40ab726882) @uBlock-user Is this for potential legal issue?

Oh I see, didn't know about that

**Comment by Yuki2718** [comment]
IIRC Admiral abused DMCA and suceeded to remoe their domain from EL. Now admiral domain is in EP which is not default to ABP and ABP allows admiral domain in their ABP filters (since it doesn't support $important or $badfilter, there's no way for user to override this other than disabling the list).

**Comment by uBlock-user** [comment]
> Is this for potential legal issue?

Was based on their DMCA against EL previously.

**Comment by pgl** [comment]
> Also @pgl

Added `spadelocket.com` to my list.
