### ISSUE TITLE
aniworld.to: popups

### ISSUE THREAD

**Issue by GermanLetsFails** [uBlockOrigin/uAssets#14397]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aniworld.to/anime/stream/gate/staffel-1/episode-4`

### Category

popups

### Describe the issue

opens and closes a new window in the browser, which makes the full screen smaller each time.
Happens almost every time I press play and pause

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 99
filterset (summary): 
  network: 82662
  cosmetic: 48987
  scriptlet: 17640
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5896-0, now
    easylist: 69421-57, now
    easyprivacy: 27334-137, now
    plowe-0: 3630-778, now
    ublock-abuse: 76-0, now
    ublock-badware: 4233-92, now
    ublock-filters: 32466-128, now
    ublock-privacy: 231-3, now
    ublock-quick-fixes: 378-0, now
    ublock-unbreak: 1856-44, now
    urlhaus-1: 5176-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 588 ms
  maxAssetCacheWait: 247 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    ads-twitter.com: 2
    fittingcentermonday.com: 2
    yandex.ru: 3
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+aniworld.to - test what cdn are used to download uBlock Filters (`filters.txt` with supplement file `filters-2022.txt`)

**Comment by JobcenterTycoon** [comment]
Got fixed here https://github.com/uBlockOrigin/uAssets/commit/0bfcfc864ac13a349016008d87fe4f69b52a1b23
