### ISSUE TITLE
ravoque.com.br: breakage

### ISSUE THREAD

**Issue by xlipe** [uBlockOrigin/uAssets#14390]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ravoque.com.br/`

### Category

not an ad

### Describe the issue

it is blocking my website just cause i'm mentioning facebook ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 81896
  cosmetic: 48143
  scriptlet: 17839
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69394-51, 22h.19m
    easyprivacy: 27329-126, 22h.18m
    plowe-0: 3634-776, 3d.21h.53m
    spa-1: 4590-80, 22h.20m
    ublock-abuse: 76-0, 3d.21h.56m
    ublock-badware: 4207-92, 22h.17m
    ublock-filters: 32407-173, 4d.2h.20m
    ublock-privacy: 231-3, 3d.21h.55m
    ublock-quick-fixes: 392-1, 5h.5m
    ublock-unbreak: 1854-44, 4d.2h.19m
    urlhaus-1: 5279-0, 5h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 668 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    onesignal.com: 1
```
</details>

**Comment by Procyon-b** [comment]
What is the problem with this site ?  It looks exactly the same in a guest window.
You know that it has an inline script syntax error. Right?

**Comment by krystian3w** [comment]
Maybe too generic is `.category-ads:not(html):not(body)` for his blog, but once incorrect "self-promo" will be not never unlocked.

![obraz](https://user-images.githubusercontent.com/35370833/184516286-95529340-2ef9-4b8c-97a9-496b67e0471a.png)

**Comment by Procyon-b** [comment]
I forgot that I had "Ignore generic cosmetic filters" enabled.

**Comment by Procyon-b** [comment]
@xlipe you shouldn't use this classname if it's not an ad: `.category-ads`

**Comment by krystian3w** [comment]
Or use longer name "advertising" / "adverts" (may never added to EL).

**Comment by stephenhawk8054** [comment]
The page looks normal for me, can you elaborate what is being blocked?

![image](https://user-images.githubusercontent.com/66517106/184519337-dbf5f157-9acf-4252-a8cd-db11e1a923d1.png)

**Comment by krystian3w** [comment]
Black article if he don't rebuild tags on "wordpress" or RayanBr silent whitelisted or deleted generic: `.category-ads`.

**Comment by xlipe** [comment]
guys, thank you all for the quick responses! it was tagged under a category named "ads". i removed it.
it's because it was an article about ads on facebook! i didn't write the code, it's a wordpress setup with a third party theme.
