### ISSUE TITLE
maxstream.video: breakage

### ISSUE THREAD

**Issue by Demigodzz** [uBlockOrigin/uAssets#14392]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://maxstream.video/tp7sxd35r1w1/aEtYQVIzOWFuQk13L0lxN2xVR09rQT09`

### Category

breakage

### Describe the issue

media player  not shown with ublock active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 126329
  cosmetic: 129833
  scriptlet: 32187
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6192-9, 1d.6h.39m
    https://winhelp2002.mvps.org/hosts.txt: 8730-62, 1d.6h.39m
    adguard-generic: 66843-757, 1d.6h.39m
    adguard-mobile: 8124-106, 1d.6h.39m
    block-lan: 43-0, 1d.6h.39m
    dpollock-0: 11380-1407, 1d.6h.39m
    fanboy-cookiemonster: 39323-115, 1d.6h.39m
    ublock-quick-fixes: 388-13, 4h.2m
  default: 
    user-filters: 11-0, never
    ITA-0: 13136-36, 4h.3m
    easylist: 69419-1494, 1h.10m
    easyprivacy: 27329-585, 1d.6h.39m
    plowe-0: 3629-1424, 1d.6h.39m
    ublock-abuse: 76-58, 1d.6h.39m
    ublock-badware: 4207-325, 1d.6h.39m
    ublock-filters: 32426-3546, 1d.6h.39m
    ublock-privacy: 231-35, 1d.6h.39m
    ublock-unbreak: 1854-90, 1d.6h.39m
    urlhaus-1: 5279-0, 4h.1m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8325 ms (selfie)
  maxAssetCacheWait: 2327 ms
popupPanel: 
  blocked: 6
  no-popups: true
  blockedDetails: 
    googletagmanager.com: 1
    host-cdn.net: 1
    impatientlyastonishing.com: 2
    intellipopup.com: 1
    setsdowntown.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
ads.host-cdn.net$image,redirect-rule=empty,domain=maxstream.video
```

**Comment by Demigodzz** [comment]
> ads.host-cdn.net$image,redirect-rule=empty,domain=maxstream.video

Seems to be working, thank you.

**Comment by Demigodzz** [comment]
doesn't work anymore.

**Comment by Procyon-b** [comment]
I can't access it anymore.

**Comment by Demigodzz** [comment]
try this: https://maxstream.video/iyv9cme8718i/bFVWa2x5eXBXUWUrRXdxQ3BqUzg2Zz09
The issue is in any maxstream video.

**Comment by Procyon-b** [comment]
I've tested again and a cosmetic rule is hiding the player.
With this it works:
```
maxstream.video#@##adsads:style(height: 9px !important;)
```

**Comment by giovariot** [comment]
Not working anymore

**Comment by mapx-** [comment]
provide a working link
