### ISSUE TITLE
lenovo.com: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#14393]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadp/thinkpad-p16s-(16-inch-amd)/len101t0038?visibleDatas=701%3AWQXGA%20(2560%20x%201600)`

### Category

detection

### Describe the issue

Detects that ublock origin is enabled and when I leave a review it fails to do so saying that content blockers are enabled. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="576" alt="image" src="https://user-images.githubusercontent.com/69532417/184522218-65b597ff-ff9a-4c2b-9ca1-2ad704c1d9bf.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80510
  cosmetic: 45294
  scriptlet: 17638
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69422-51, now
    easyprivacy: 27334-127, now
    plowe-0: 3630-777, now
    ublock-abuse: 76-0, now
    ublock-badware: 4228-92, now
    ublock-filters: 32462-116, now
    ublock-privacy: 231-3, now
    ublock-quick-fixes: 388-1, now
    ublock-unbreak: 1858-43, now
    urlhaus-1: 5191-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 936 ms
  maxAssetCacheWait: 290 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    adobedtm.com: 22
    bazaarvoice.com: 2
    evidon.com: 1
    facebook.net: 1
    go-mpulse.net: 2
    google-analytics.com: 2
    google.com: 1
    googletagmanager.com: 1
    impactradius-event.com: 1
    licdn.com: 1
    quantummetric.com: 1
    tealiumiq.com: 1
```
</details>

**Comment by okiehsch** [comment]
Does adding
`@@||mpsnare.iesnare.com/snare.js$script,domain=lenovo.com`
to your filter list work?

**Comment by stephenhawk8054** [comment]
> Does adding `@@||mpsnare.iesnare.com/snare.js$script,domain=lenovo.com` to your filter list work?

This works on my end.
