### ISSUE TITLE
americanexpress.com: nuisance

### ISSUE THREAD

**Issue by iamvecr** [uBlockOrigin/uAssets#14396]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.americanexpress.com/it/carte-di-credito/tutte-le-carte/?intlink=it-it-hp-product-personal-090321`

### Category

nuisance

### Describe the issue

On the italian site of American Express the cookie banner if of course present, I tried enabling  EasyList Cookie with no luck. 
With element picker, I was able to remove the overlay and the banner, maybe there is a better way but here's what worked for me. 

`www.americanexpress.com###user-consent-management-binary-banner-overlay`

Thanks 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2022-08-14 at 14-52-59 Informazioni e Richiesta Carte American Express](https://user-images.githubusercontent.com/7118651/184538179-e9a13681-8f97-4df7-a324-ab9eafb96982.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 182992
  cosmetic: 223428
  scriptlet: 37776
  html: 732
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    adguard-generic: 66855-5517, 1m
    adguard-mobile: 8129-11, 1m
    adguard-spyware: 26785-1134, 1m
    adguard-spyware-url: 710-3, 1m
    block-lan: 43-0, 1m
    curben-phishing: 38462-7, 1m
    curben-pup: 189-0, 1m
    adguard-annoyance: 55919-4866, 1m
    adguard-social: 18156-33, 1m
    fanboy-thirdparty_social: 68-0, 1m
    fanboy-annoyance: 78871-40813, 1m
    fanboy-cookiemonster: 39545-143, 1m
    ublock-annoyances: 4532-6, 1m
    dpollock-0: 11380-531, 1m
    ITA-0: 13136-12, now
    ROU-1: 979-25, now
  default: 
    ublock-filters: 33164-50, 1m
    ublock-badware: 4237-0, 1m
    ublock-privacy: 247-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1869-0, 1m
    ublock-quick-fixes: 375-0, 1m
    easylist: 69424-962, 1m
    easyprivacy: 27334-9892, 1m
    urlhaus-1: 5176-0, 1m
    plowe-0: 3630-142, now
filterset (user): [array of 201 redacted]
trustedset: 
  added: [array of 293 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 333 ms (selfie)
  maxAssetCacheWait: 645 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    aexp-static.com: 1
    demdex.net: 2
```
</details>

**Comment by MasterKia** [comment]
> - [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)

[_GDPR (Cookie) modals will not be addressed._](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#gdpr)

For EasyList Cookie, report to https://github.com/easylist/easylist

**Comment by krystian3w** [comment]
Also if page have ads in Ad Sense then can froze load embedded videos to don't lost ads and Google account.

So Google generated bad time when needed is correct close pop-up instead hide by simiple cosmetic filter.

**Comment by MasterKia** [comment]
> needed is correct close pop-up instead hide by simiple cosmetic filter.

I believe AdGuard can auto-click cookie banners, so they might be able to fix this.

**Comment by krystian3w** [comment]
Or migrate to Kiboke addon: https://www.i-dont-care-about-cookies.eu/
