### ISSUE TITLE
wv.1-123movies.com: breakage

### ISSUE THREAD

**Issue by Roffy02** [uBlockOrigin/uAssets#14391]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wv.1-123movies.com/tvshows/star-trek-strange-new-worlds-R67o76/`

### Category

breakage

### Describe the issue

When attempting to load any video content on 123movies Ublock breaks links that connect to content and shows blank images/pages with no links

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30046771/184516519-4d3b4a5c-e01d-4909-8c56-83f59be8546f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80419
  cosmetic: 45257
  scriptlet: 17605
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69331-51, 2d.8h.1m
    easyprivacy: 27324-123, 2d.8h.1m
    plowe-0: 3634-776, 2d.8h.1m
    ublock-abuse: 76-0, 2d.8h.1m
    ublock-badware: 4206-92, 2d.8h.1m
    ublock-filters: 32404-100, 2d.8h.1m
    ublock-privacy: 231-3, 2d.8h.1m
    ublock-quick-fixes: 387-1, 22h.42m
    ublock-unbreak: 1855-43, 2d.8h.1m
    urlhaus-1: 5190-0, 1d.2h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 216 ms (selfie)
  maxAssetCacheWait: 164 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
That page doesn't even work in a "guest" window.

**Comment by stephenhawk8054** [comment]
The page looks like that even when I disable uBO. You can also see that uBO was not blocking anything in the site

```yaml
popupPanel: 
  blocked: 0
```
