### ISSUE TITLE
Elements blocked incorrectly: www.dpp.org.tw

### ISSUE THREAD

**Issue by ztdu** [uBlockOrigin/uAssets#14399]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.dpp.org.tw/`

### Describe the issue

- Text above 「深入了解」button missing. 
- Some squared image link missing. 

### Screenshot(s)

https://i.postimg.cc/mkym0wW6/2022-08-15-09-22-23.png

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 100229
  cosmetic: 54068
  scriptlet: 17282
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32409-97, never
    ublock-badware: 4175-3, never
    ublock-privacy: 228-0, never
    ublock-abuse: 75-0, never
    ublock-unbreak: 1809-0, never
    ublock-quick-fixes: 202-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-131, never
    urlhaus-1: 7285-0, never
    plowe-0: 3639-784, never
    CHN-0: 28717-156, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9865 ms
  maxAssetCacheWait: 49 ms
```
</details>

**Comment by MasterKia** [comment]
Is the link only accessible in China?

**Comment by Yuki2718** [comment]
@ryanbr `dpp.org.tw#@#.ad_url`

**Comment by ztdu** [comment]
I don’t believe so, though I were not the owner. Contrarily it might block traffic from China to avoid cyber attacks. My visiting from IP from Taiwan is allowed.
