### ISSUE TITLE
s.to: popups

### ISSUE THREAD

**Issue by Rubyurek** [uBlockOrigin/uAssets#14398]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.to/`

### Category

popups

### Describe the issue

When i click play on a stream the it open a tab.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82662
  cosmetic: 48996
  scriptlet: 17640
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    DEU-0: 5896-0, now
    easylist: 69421-57, now
    easyprivacy: 27334-137, now
    plowe-0: 3630-778, now
    ublock-abuse: 76-0, now
    ublock-badware: 4233-92, now
    ublock-filters: 32467-128, now
    ublock-privacy: 231-3, now
    ublock-quick-fixes: 380-0, now
    ublock-unbreak: 1856-44, now
    urlhaus-1: 5176-0, now
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 238 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    ads-twitter.com: 1
    fittingcentermonday.com: 1
    glizauvo.net: 1
    imasdk.googleapis.com: 1
    yandex.ru: 2
```
</details>

**Comment by MasterKia** [comment]
Similar to https://github.com/uBlockOrigin/uAssets/issues/14397

**Comment by JobcenterTycoon** [comment]
Its `voe.sx`, they changed the domain to avoid the existing filter. 

To reproduce easily: `https://housecardsummerbutton.com/e/1sr4vamqzdhw`

**Comment by Janmm14** [comment]
It seems voe also uses domain bigclatterhomesguideservide.com

**Comment by JobcenterTycoon** [comment]
Ok i added a generic rule to counter the popups

**Comment by Janmm14** [comment]
Other domains they use: `uptodatefinishconferenceroom.com` `uptodatefinishconference.com`.
Also popups appear again on there.

**Comment by Janmm14** [comment]
https://github.com/easylist/easylist/issues/13208
