### ISSUE TITLE
animmex.com BlockAdBlock

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#144]
### URL(s) where the issue occurs

`https://www.animmex.com/video/7872/bojack-horseman-s02e13-sabrina-s-christmas-wish`

### Describe the issue

BlockAdBlock in use. The frame that loads the video uses BlockAdBlock too which seems to sometimes cause problems with defusing it.

### Screenshot(s)

![](https://cloud.githubusercontent.com/assets/16030872/18560366/8c84ae70-7b7b-11e6-8cd4-e38048b5c349.png)
![](https://cloud.githubusercontent.com/assets/16030872/18560367/8c8aa2b2-7b7b-11e6-9de1-afa5583f21bc.png)

### Versions

- Browser/version: Chrome 53.0.2785.89
- uBlock Origin version: 1.9.4

### Settings

- No changes

### Notes

`animmex.com##script:inject(bab-defuser.js)`
`4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)`

**Comment by uBlock-user** [comment]
To block it from loading it in the frame, use `amx.4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)` instead of `4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)`

**Comment by uBlock-user** [comment]
`http://www.animmex.co/
http://www.animmex.com/
https://www.animmex.net/
https://www.animmex.org/
https://www.animmex.online/
https://www.animmex.website/
https://www.animmex.xyz/
https://www.animmex.tech/
https://www.animmex.info/
https://www.animmex.site/
https://www.animmex.space/
https://www.animmex.co.uk/
https://www.animmex.club/
http://www.animmex.press/`

Might as well go with animmex.* for all cosmetic and injection filters

**Comment by uBlock-user** [comment]
Another Animmex clone - `jukezilla.com/video/5488/futurama-s07e17`, add that too.

**Comment by F4z** [comment]
I think, now they use newer version of BlockAdBlock, because `bab-defuser.js` does not work.
`https://www.animmex.net/video/12217/robocop-1987`

![image](https://cloud.githubusercontent.com/assets/11742596/19216218/b7d8b450-8db3-11e6-906b-0ecc2c972917.png)
