### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Skylarisdeadcri** [uBlockOrigin/uAssets#14406]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

'Save to Playlist' fails to load. (I'm not going to go and look through 5+ pages worth of youtube reports,)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot](https://user-images.githubusercontent.com/88257037/184763515-67285e32-a7ca-4427-ae0d-cfe40d8f23b9.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 123091
  cosmetic: 45256
  scriptlet: 17610
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-2, never
    ublock-filters: 33099-37, 4d.1h.37m
    ublock-badware: 4211-0, 4d.1h.37m
    ublock-privacy: 247-0, 4d.1h.37m
    ublock-abuse: 76-0, 4d.1h.37m
    ublock-unbreak: 1868-1, 4d.1h.37m
    ublock-quick-fixes: 375-0, 22h.13m
    easylist: 69331-571, 4d.1h.37m
    adguard-spyware-url: 710-2, 4d.1h.37m
    easyprivacy: 27324-580, 4d.1h.37m
    urlhaus-1: 5247-0, 22h.12m
    curben-phishing: 40068-5, 22h.11m
    plowe-0: 3634-3, 4d.1h.37m
    LegitimateURLShortener: 1940-96, 22h.10m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1250 ms (selfie)
  maxAssetCacheWait: 1100 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    youtube.com: 9
    doubleclick.net: 2
    google.com: 1
```
</details>

**Comment by Skylarisdeadcri** [comment]
Im using a forked version of firefox if that helps.

**Comment by MasterKia** [comment]
> I'm not going to go and look through 5+ pages worth of youtube reports

Please report here: https://github.com/uBlockOrigin/uAssets/issues/7636

Also see: https://github.com/easylist/easylist/youtube-issues
