### ISSUE TITLE
False Positive of the "NoScript" site

### ISSUE THREAD

**Issue by Fjpqeign5713** [uBlockOrigin/uAssets#14404]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://noscript.net/faq`

`https://noscript.net/`

### Describe the issue

When attempting to connect to `https://noscript.net/faq` from the DuckDuckGo search results, uBlock Origin stops the site from loading due to a filter in the "Phishing URL Blocklist". 

When attemping to connect to the main page, `https://noscript.net/`, uBlock Origin allows it to load, however ProtonVPN's Netshield blocks it from loading. (two separate browsers were unable to connect to the server until I disabled Netshield).

It seems that the term "noscript" was falsely flagged. There are other URL's contained in the rules list that have "noscript" in the URL. Two of them are from sites I am unfamiliar with, and are probably correctly flagged. However, I think this may have led to the noscript site itself being falsely flagged.

Here is a link to screenshots showing the "Phishing URL Blocklist" rules in uBlock Origin that contain the term "noscript":
https://imgur.com/a/3jnprRI

And here are a couple screenshots showing what happens when trying to visit the site:
https://imgur.com/a/x3kMcOK

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103.0.2 (64-bit)

### Settings

- Block media elements larger than 50 KB enabled
- Block remote fonts enabled
- Disable JavaScript enabled
- I am an advanced user enabled

### Notes

As stated previously, when searching through the Phishing URL Blocklist (the blocklist that is causing the false positive), I found three URL's that contained the term "noscript". Two of the three are sites I am unfamiliar with, so I assume they are not false positives. However, the third site is the noscript faq URL (noscript being the script-blocker extension). The main site for noscript is not blocked by uBlock Origin.

However, ProtonVPN's Netshield (a DNS ad-blocking service built into ProtonVPN) blocks the main noscript site from loading. This has led me to believe that the filter list is at issue, as Netshield may share the same Phishing URL Blocklist as uBlock Origin.

**Comment by MasterKia** [comment]
> uBO with default lists/settings

"Phishing URL Blocklist" is not a default list so you should report here:
https://gitlab.com/malware-filter/phishing-filter/issues

You can add this to "My filters":
`||noscript.net/faq$all,badfilter`

**Comment by MasterKia** [comment]
@curbengh

**Comment by Fjpqeign5713** [comment]
My bad, I thought it was a default list. Thank you for directing me to the correct place.
