### ISSUE TITLE
wellgames.com: nuisance

### ISSUE THREAD

**Issue by Hedgehawk11** [uBlockOrigin/uAssets#14409]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://wellgames.com/`

### Category

nuisance

### Describe the issue

there seems to be ads when I try to use UBo on the games

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/84346970/184798885-150803e6-9b03-4238-8ced-932adae97a31.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80438
  cosmetic: 45239
  scriptlet: 17606
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69323-51, 3d.23h.45m
    easyprivacy: 27326-123, 3d.23h.47m
    plowe-0: 3630-776, 1d.4h.17m
    ublock-abuse: 76-0, 2d.10h.53m
    ublock-badware: 4207-92, 3d.23h.43m
    ublock-filters: 32404-105, 3d.23h.46m
    ublock-privacy: 231-3, 1d.4h.22m
    ublock-quick-fixes: 380-0, 5h.32m
    ublock-unbreak: 1855-43, 3d.23h.44m
    urlhaus-1: 5212-0, 5h.31m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 551 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 1
    gamedock.io: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    selectmedia.asia: 1
```
</details>

**Comment by okiehsch** [comment]
````
wellgames.com##.cross-promo
wellgames.com##.post-banner
````
@ryanbr
