### ISSUE TITLE
upwork.com: breakage. an important button is not working.

### ISSUE THREAD

**Issue by Ahwar** [uBlockOrigin/uAssets#14408]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.upwork.com/jobs/~0109685e82a620dd12`

### Category

breakage

### Describe the issue

When I click on the "submit a proposal" button, it keeps loading for a long time and does not go to the next page.  
But the issue resolves after I disable the extension.

this screenshot shows the page button showing loading but not proceeding to the next page  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

This screenshot shows the page button showing loading but not moving to the next page

![This screenshot shows the page button showing loading but not proceeding to the next page](https://user-images.githubusercontent.com/20405797/184795077-0cf84334-4715-41a7-8a26-ced402e1115b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 106
filterset (summary): 
  network: 80583
  cosmetic: 45315
  scriptlet: 17648
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69458-51, 2m
    easyprivacy: 27348-127, 2m
    plowe-0: 3630-777, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4233-92, 2m
    ublock-filters: 32476-115, 2m
    ublock-privacy: 231-3, 2m
    ublock-quick-fixes: 379-0, 2m
    ublock-unbreak: 1860-43, 2m
    urlhaus-1: 5230-0, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 369 ms (selfie)
  maxAssetCacheWait: 245 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    upwork.com: 1
    googletagmanager.com: 1
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
@Ahwar open the logger, repeat the steps to get the issue, go back in the logger and post here all the blocked requests you see in the log

**Comment by Ahwar** [comment]
I opened the logger, opened the webpage, clicked the button which was not working, applied the blocked filter, and copied the logs as markdown; below are the resultant logs

<details><summary>Logger output</summary>

```
+8
||usabilla.com^$3p
--
www.upwork.com
3
script
https://w.usabilla.com/202452b9c34b.js?lv=1
```
```
+3
googletagmanager_gtm.js
<<
www.upwork.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K9RTCGW
```
```
+3
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www.upwork.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K9RTCGW
```
```
+3
||googletagmanager.com^
--
www.upwork.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-K9RTCGW
```
```
+2
||upwork.com/ss13u803/init.js
--
www.upwork.com
1
script
https://www.upwork.com/Ss13U803/init.js
```
```
+0
https://www.upwork.com/jobs/~010ed5d3a7b5e2aced
```
</details>

**Comment by mapx-** [comment]
does this help ?

`||upwork.com/ss13u803/init.js`

**Comment by Ahwar** [comment]
> does this help?
> 
> `||upwork.com/ss13u803/init.js$badfilter`

@mapx- I added the above filter and allowed this specific script URL, but the issue still exists.

**Comment by mapx-** [comment]
test 1 by 1 these other exceptions:

`@@||googletagmanager.com/gtm.js$script,domain=upwork.com`

`@@||usabilla.com^$script,domain=upwork.com`

**Comment by Ahwar** [comment]
I added this below the filter, removed other filters and it is working now
```@@||googletagmanager.com/gtm.js$script,domain=upwork.com```

**Comment by mapx-** [comment]
@ryanbr
