### ISSUE TITLE
Exist ads/tracking scripts on website: `vov.vn`

### ISSUE THREAD

**Issue by vhpcdpgl** [uBlockOrigin/uAssets#14407]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vov.vn/quan-su-quoc-phong/phan-tich/phuong-tay-tinh-chuyen-giao-chien-dau-co-toi-tan-cho-ukraine-da-qua-muon-post963398.vov`
`https://vov2.vov.vn/`

### Describe the issue

There are some ads/tracking scripts, ex:
`https://vov.vn/ads/show-ads?tids[]=4&tids[]=80&type=node&position=64`
`https://vov2.vov.vn/ads/show-ads?tids[]=43267&type=front&position=45`

**Proposed rules:**
`||vov.vn/ads/$xmlhttprequest`

### uBlock Origin version

uBlock Origin 1.43.0

### Browser name and version

Firefox 91.12.0esr (64-bit)

### Settings

<details>
    <summary>Settings</summary>

```yaml
filterset (summary): 
  network: 305695
  cosmetic: 216171
  scriptlet: 37843
  html: 732
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/hosts.txt: 31613-0, 17h.35m
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts: 133944-808, 20h.33m
    https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts: 17269-9639, 20h.31m
    adguard-generic: 66859-5835, 1d.50m
    adguard-mobile: 8131-672, 1d.49m
    adguard-spyware: 26785-11476, 1d.47m
    adguard-spyware-url: 710-3, 1d.46m
    adguard-annoyance: 55919-693, 1d.44m
    adguard-social: 18156-873, 1d.43m
    fanboy-thirdparty_social: 69-3, 6d.20m
    fanboy-annoyance: 78372-4592, 6d.20m
    fanboy-cookiemonster: 39096-39096, 6d.20m
    fanboy-social: 23272-23266, 1d.42m
    ublock-annoyances: 4532-238, 1d.41m
    dpollock-0: 11380-11380, 6d.20m
    curben-phishing: 38403-77, 1d.38m
    curben-pup: 189-1, 1d.37m
  default: 
    ublock-filters: 33165-151, 1d.55m
    ublock-badware: 4237-98, 1d.54m
    ublock-privacy: 247-3, 1d.53m
    ublock-abuse: 76-0, 1d.52m
    ublock-unbreak: 1871-1, 1d.51m
    easylist: 69422-16057, 1d.48m
    easyprivacy: 27339-12397, 1d.45m
    urlhaus-1: 5247-666, 1d.40m
    VIE-1: 1897-88, 15h.46m
    ublock-quick-fixes: 375-12, 1d.36m
filterset (user): [array of 642 redacted]
trustedset: 
  added: [array of 26 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4724 ms (selfie)
  maxAssetCacheWait: 5639 ms
```

</details>

**Comment by MasterKia** [comment]
@hoang-rio

**Comment by hoang-rio** [comment]
I see no ads in this url `https://vov.vn/quan-su-quoc-phong/phan-tich/phuong-tay-tinh-chuyen-giao-chien-dau-co-toi-tan-cho-ukraine-da-qua-muon-post963398.vov` if it simple is tracking url ABPVN will be ignore it. Please request to add to Privacy list

**Comment by MasterKia** [comment]
I see no ads either.
Only requests to `vov.vn/ads/show-ads`.

https://user-images.githubusercontent.com/17685483/184802499-f580f7b0-2432-4f5d-b084-7c92a31b7013.png
