### ISSUE TITLE
omroepzeeland.nl: breakage

### ISSUE THREAD

**Issue by Bucketsmith** [uBlockOrigin/uAssets#14410]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.omroepzeeland.nl/video/De-paarden-van-Marinus-lopen-los-in-Colijn-ZNO220815FZ/de-paarden-van-marinus-lopen-los-in-colijnsplaat-en-daar-is-niet-iedereen-blij-mee`

### Category

breakage

### Describe the issue

Video's in articles won't play

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 94120
  cosmetic: 109978
  scriptlet: 24694
  html: 735
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4552-7, 10h.47m
    adguard-annoyance: 55983-4016, 7h.31m
    fanboy-annoyance: 78144-34604, 8d.23h.30m
    NLD-0: 2449-47, 2d.12h.59m
  default: 
    user-filters: 36-1, never
    ublock-filters: 33276-384, 11h.55m
    ublock-badware: 4236-0, 11h.52m
    ublock-privacy: 247-1, 11h.51m
    ublock-abuse: 76-0, 10h.55m
    ublock-unbreak: 1878-0, 8h.18m
    adguard-mobile: 8135-171, 7h.36m
    easylist: 69449-25151, 7h.33m
    easyprivacy: 27346-591, 7h.32m
    plowe-0: 3634-3, 8d.23h.30m
    urlhaus-1: 5230-0, 2h.6m
filterset (user): [array of 36 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 658 ms (selfie)
  maxAssetCacheWait: 3693 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    omroepzeeland.nl: 2
    aticdn.net: 2
    outbrain.com: 2
    privacymanager.io: 4
    rackcdn.com: 1
    smartocto.com: 1
    sprinklecontent.com: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr caused by `Fanboy Annoyance`.
````
@@||cmp-consent-tool.privacymanager.io^$frame,domain=omroepzeeland.nl
@@||gdpr.privacymanager.io/*/gdpr.bundle.js$script,domain=omroepzeeland.nl
@@||gdpr-wrapper.privacymanager.io/gdpr/*$script,domain=omroepzeeland.nl
@@||gdpr-wrapper.privacymanager.io/gdpr/*$xhr,domain=omroepzeeland.nl
@@||vendors.privacymanager.io/vendor-list.json$xhr,domain=omroepzeeland.nl
````
