### ISSUE TITLE
[NSFW] manhuascan.io: popups

### ISSUE THREAD

**Issue by anderav1** [uBlockOrigin/uAssets#14416]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manhuascan.io/`

### Category

popups

### Describe the issue

Clicking on the scroll bar triggers a popup to open in a new window. Occurs on various pages throughout the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80515
  cosmetic: 45289
  scriptlet: 17647
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69425-51, 2d.1h.20m
    easyprivacy: 27348-127, 8h.30m
    plowe-0: 3634-776, 11d.12h.33m
    ublock-abuse: 76-0, 7d.3h.15m
    ublock-badware: 4233-92, 8h.31m
    ublock-filters: 32476-116, 8h.29m
    ublock-privacy: 231-3, 7d.3h.14m
    ublock-quick-fixes: 378-0, 12h.33m
    ublock-unbreak: 1858-43, 8h.28m
    urlhaus-1: 5167-0, 12h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 23737 ms (selfie)
  maxAssetCacheWait: 1040 ms
popupPanel: 
  blocked: 21
  no-popups: true
  blockedDetails: 
    adnxs.com: 1
    adsco.re: 1
    agkn.com: 1
    betteradsystem.com: 1
    d2kk0o3fr7ed01.cloudfront.net: 1
    disqus.com: 4
    googletagmanager.com: 1
    hoazinangles.com: 2
    lijit.com: 1
    narrative.io: 1
    pippio.com: 1
    rezync.com: 1
    rlcdn.com: 1
    viglink.com: 2
    zeinssibby.com: 2
```
</details>

**Comment by MasterKia** [comment]
` ||kozuyzcciaygg.com^` 
@ryanbr EasyList
