### ISSUE TITLE
unite-db.com: breakage

### ISSUE THREAD

**Issue by DaFiestyBanana** [uBlockOrigin/uAssets#14412]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://unite-db.com/tier-list/pokemon`

### Category

breakage

### Describe the issue

It blocks elements on the webpage which shows images and links that otherwise appear with ublock turned off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox Mobile: 103
filterset (summary): 
  network: 81851
  cosmetic: 27007
  scriptlet: 17672
  html: 727
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33258-310, 3d.2h.24m
    ublock-badware: 4179-0, 5d.19h.15m
    ublock-privacy: 247-1, 23h.41m
    ublock-abuse: 76-0, 2d.17h.44m
    ublock-unbreak: 1872-0, 5d.19h.14m
    adguard-mobile: 8124-168, 3d.2h.26m
    easylist: 69313-25104, 5d.19h.13m
    easyprivacy: 27330-591, 3d.2h.25m
    urlhaus-1: 5191-0, 2d.1h.28m
    plowe-0: 3630-3, 23h.8m
    ublock-quick-fixes: 385-1, 2d.4h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 365 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 3
    google-analytics.com: 1
    network-n.com: 2
```
</details>

**Comment by gorhill** [comment]
I see the images fine at that page. Provide a screenshot of what is broken on your side -- if there is something broken on that page, I don't see it.

**Comment by DaFiestyBanana** [comment]
Wasnt sure where to mention it but this is on mobile. At work atm so will check on desktop when i am done
![Screenshot_20220816_171142_org mozilla firefox](https://user-images.githubusercontent.com/108105543/184927943-bf268b7f-8225-4557-93cd-f55f8d99f32a.jpg)
![Screenshot_20220816_171200_org mozilla firefox](https://user-images.githubusercontent.com/108105543/184927953-68e8d871-0af3-41f8-bee1-b0973aa34085.jpg)

**Comment by gorhill** [comment]
I checked on mobile and the images still show fine for me. See what the logger reports, if there are any network requests for images being blocked, and if so what by which filter/rule.

**Comment by gorhill** [comment]
I checked on mobile and the images still show fine for me. See what the logger reports, if there are any cosmetic filter causing this, and if so by which filter from which list.

**Comment by DaFiestyBanana** [comment]
<details><summary>Logger output</summary>

```
+16
###nn_lb2
unite-db.com
dom
https://unite-db.com/tier-list/pokemon
```
```
+16
###nn_lb1
unite-db.com
dom
https://unite-db.com/tier-list/pokemon
```
```
+16
google-analytics.com/analytics.js
<<
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+16
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5
--
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+16
||google-analytics.com^
--
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+15
||network-n.com^$3p,domain=~lostarkhub.com
--
unite-db.com
3
script
https://kumo.network-n.com/dist/app.js
```
```
+15
||network-n.com^$3p,domain=~lostarkhub.com
--
unite-db.com
3
script
https://kumo.network-n.com/dist/app.js
```
```
+15
googletagservices_gpt.js
<<
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+15
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js:5
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+15
||doubleclick.net^
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+15
||doubleclick.net^
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/
```
```
+15
https://unite-db.com/tier-list/pokemon
```
```
+3
###nn_lb2
unite-db.com
dom
https://unite-db.com/tier-list/pokemon
```
```
+3
###nn_lb1
unite-db.com
dom
https://unite-db.com/tier-list/pokemon
```
```
+1
google-analytics.com/analytics.js
<<
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5
--
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
unite-db.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+1
||network-n.com^$3p,domain=~lostarkhub.com
--
unite-db.com
3
script
https://kumo.network-n.com/dist/app.js
```
```
+1
||doubleclick.net^
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/
```
```
+0
||network-n.com^$3p,domain=~lostarkhub.com
--
unite-db.com
3
script
https://kumo.network-n.com/dist/app.js
```
```
+0
googletagservices_gpt.js
<<
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+0
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js:5
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+0
||doubleclick.net^
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+0
||doubleclick.net^
--
unite-db.com
3
script
https://securepubads.g.doubleclick.net/
```
```
+0
https://unite-db.com/tier-list/pokemon
```
</details>
Thats what i pasted from logger. Not sure how helpful it is but

**Comment by DaFiestyBanana** [comment]
Whoops clicked submit trying to change comment but it works fine on desktop so probs a personal configuration issue. Sorry for hassle and thanks for your time
