### ISSUE TITLE
salesangels.learnworlds.com: breakage

### ISSUE THREAD

**Issue by juliuspopp** [uBlockOrigin/uAssets#14417]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://salesangels.learnworlds.com/path-player?courseid=google-ads&unit=google-ads_62e25fd1c8b5aUnit`

### Category

breakage

### Describe the issue

This is an online academy / online course / membership area, and the videos which are the main content are not displaying when uBO is enabled.

I do not know which resource it is:
All Ressources:

learnworlds.com
salesangels.learnworlds.com
cloudflare.com
cdnjs.cloudflare.com
d2wy8f7a9ursnm.cloudfront.net
fonts.googleapis.com
google.com
googletagmanager.com
gstatic.com
mycourse.app

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82731
  cosmetic: 48992
  scriptlet: 17640
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33171-50, 2d.7h.42m
    ublock-badware: 4232-0, 2d.7h.41m
    ublock-privacy: 247-0, 9d.4h.9m
    ublock-abuse: 76-0, 9d.4h.8m
    ublock-unbreak: 1871-0, 2d.7h.45m
    easylist: 69425-596, 2d.7h.44m
    easyprivacy: 27342-590, 2d.7h.43m
    urlhaus-1: 5230-0, 1d.6m
    plowe-0: 3634-3, 9d.4h.6m
    DEU-0: 5897-2, 1d.5m
    ublock-quick-fixes: 375-0, 1d.4m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 984 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    d2wy8f7a9ursnm.cloudfront.net: 2
    google.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
We need to know what is blocked on your end to be able to help.
You would have to use the logger and post a screenshot of the blocked requests. 
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by juliuspopp** [comment]
Ok, here comes the log:

screenshot: 
![image](https://user-images.githubusercontent.com/29792509/185149225-4b06a185-460a-4353-b4dd-93f5966aaaa5.png)

Table:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | /google-ads/* | -- | salesangels.learnworlds.com | 1 | xhr | `https://salesangels.learnworlds.com/api/chapter/google-ads/google-ads_62e25fd1bc9bc` |
| +2 | \|\|d2wy8f7a9ursnm.cloudfront.net^ | -- | salesangels.learnworlds.com | 3 | script | `https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js` |
| +2 | \|\|d2wy8f7a9ursnm.cloudfront.net^ | -- | salesangels.learnworlds.com | 3 | script | `https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js` |
| +2 | googletagmanager_gtm.js | << | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +2 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +2 | \|\|googletagmanager.com^ | -- | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +1 | \|\|d2wy8f7a9ursnm.cloudfront.net^ | -- | salesangels.learnworlds.com | 3 | script | `https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js` |
| +1 | \|\|vimeocdn.com/add/player-stats? | -- | player.vimeo.com | 3,3 | beacon | `https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=ad68109b99371e203509fe5d7ba21d2c552d85fa1660736484` |
| +1 | \|\|player-telemetry.vimeo.com^ | -- | player.vimeo.com | 3,1 | beacon | `https://player-telemetry.vimeo.com/player-events/log/partial` |
| +0 | \|\|d2wy8f7a9ursnm.cloudfront.net^ | -- | salesangels.learnworlds.com | 3 | script | `https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js` |
| +0 | googletagmanager_gtm.js | << | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +0 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +0 | \|\|googletagmanager.com^ | -- | salesangels.learnworlds.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-119892968-1` |
| +0 | .de/ads/$~xmlhttprequest | -- | salesangels.learnworlds.com | 3 | image | `https://www.google.de/ads/ga-audiences?v=1&t=sr&slf_rd=1&_r=4&tid=G-YQ1YZ3QKXB&cid=325394182.1660735135&gtm=2oe8f0&aip=1&z=589278117` |
| +0 | \|\|doubleclick.net^ | -- | salesangels.learnworlds.com | 3 | beacon | `https://stats.g.doubleclick.net/g/collect?v=2&tid=G-YQ1YZ3QKXB&cid=325394182.1660735135&gtm=2oe8f0&aip=1` |
| +0 | \|\|analytics.google.com^ | -- | salesangels.learnworlds.com | 3 | beacon | `https://region1.analytics.google.com/g/collect?v=2&tid=G-YQ1YZ3QKXB&gtm=2oe8f0&_p=1771138973&_gaz=1&cid=325394182.1660735135&ul=de&sr=1920x1080&_z=ccd.v9B&_s=6&dr=https%3A%2F%2Fsalesangels.learnworlds.com%2Fpath-player%3Fcourseid%3Dgoogle-ads%26unit%3Dgoogle-ads_62e25fd1bf050Unit&sid=1660743411&sct=2&seg=0&dl=https%3A%2F%2Fsalesangels.learnworlds.com%2Fpath-player%3Fcourseid%3Dgoogle-ads%26unit%3Dgoogle-ads_62e25fd1bc9bcUnit&dt=Conversion%20Tracking%20Ziel&en=user_engagement&_ss=1` |
</details>

**Comment by okiehsch** [comment]
> and the videos which are the main content are not displaying when uBO is enabled.

Hm, could be numerous things.
Does adding
`@@||salesangels.learnworlds.com/api/*$xhr,1p`
to your filter list fix the issue?
