### ISSUE TITLE
francoischarron.com: detection

### ISSUE THREAD

**Issue by Pascal-007** [uBlockOrigin/uAssets#14414]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://francoischarron.com/`

### Category

detection

### Describe the issue

The web site show an error message because of the blocker and redirect to `https://francoischarron.com/erreur/message-aux-usagers-adb/`.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/111365953/184899225-3229d9ca-fcb9-4478-9b41-c0e780f372bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 101366
  cosmetic: 54142
  scriptlet: 17663
  html: 723
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33094-184, 3d.19h.28m
    ublock-badware: 4228-3, 3d.19h.27m
    ublock-privacy: 247-0, 7d.21h.48m
    ublock-abuse: 76-0, 7d.21h.47m
    ublock-unbreak: 1867-0, 3d.19h.26m
    ublock-quick-fixes: 375-0, 19h.16m
    easylist: 69394-669, 3d.19h.25m
    easyprivacy: 27329-882, 3d.19h.30m
    urlhaus-1: 5212-0, 19h.17m
    plowe-0: 3629-3, 3d.3h.22m
    FRA-0: 30456-47, 3d.19h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3155 ms (selfie)
  maxAssetCacheWait: 326 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    alexametrics.com: 1
    freeskreen.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 3
    m32.media: 3
    quantserve.com: 2
    rumble.com: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

**Comment by Procyon-b** [comment]
Can't reproduce too.
Apparently you haven't updated the filter lists. Test again after doing so.
