### ISSUE TITLE
forum.release-apk.com: detection

### ISSUE THREAD

**Issue by ComatoseBadger** [uBlockOrigin/uAssets#14426]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://forum.release-apk.com/viewforum.php?f=26&sid=79874759b72d47c11310d9c78e203295`

### Category

detection

### Describe the issue

ReleaseAPK shows online advertisements to our visitors to cover the cost of hosting.
Please, consider supporting ReleaseAPK by deactivating your Ad-Blocker on ReleaseAPK. !!!
Disable your ad-blocker on ReleaseAPK to enjoy the content.

Read Instructions :
1.- Press the ad-blocker icon.
2.- Select "Do not act on pages of this domain" (or similar).
3.- You can also press the "Activated on this site" or "Pause ad-blocker" (or similar) button.
4.- Also disable "Enhanced Tracking Protection" or "Lite mode" (or similar) function of browser.
5.- Press the "Refresh" button of your browser to see the content you want to view.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 185227
  cosmetic: 219323
  scriptlet: 54114
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 23h.30m
    https://github.com/uBlock-user/uBO-Personal-Filters/blob/master/uPF.txt: 0-0, never
    https://gitlab.com/kowith337/PersonalFilterListCollection/raw/master/filterlist/facebook/FacebookZuckestionKiller.txt: 998-0, 23h.32m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 23h.31m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23907-66, 2d.3h.14m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 2196-26, 3h.17m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-1960, 3h.19m
    adguard-annoyance: 55983-190, 2d.23h.52m
    adguard-generic: 66861-1514, 2d.23h.51m
    adguard-mobile: 8135-50, 2d.23h.50m
    adguard-social: 18197-889, 1d.13h.58m
    adguard-spyware: 26789-954, 3d.5h.3m
    adguard-spyware-url: 710-1, 3d.5h.2m
    block-lan: 43-0, 17d.3h.59m
    curben-phishing: 43715-9, 3h.14m
    curben-pup: 189-1, 3h.15m
    fanboy-annoyance: 79364-4624, 23h.29m
    fanboy-cookiemonster: 39981-39981, 23h.28m
    fanboy-social: 23274-23274, 3d.4h.59m
    fanboy-thirdparty_social: 69-21, 23h.27m
    [1 lists not shown]: [too many]
  default: 
    user-filters: 14-0, never
    easylist: 69431-1207, 3d.5h.1m
    easyprivacy: 27344-9663, 3d.5h
    plowe-0: 3634-953, 9d.17m
    ublock-abuse: 76-1, 10d.23h.27m
    ublock-badware: 4233-332, 3d.4h.57m
    ublock-filters: 32476-6478, 2d.23h.54m
    ublock-privacy: 231-44, 10d.23h.1m
    ublock-quick-fixes: 409-19, 3h.16m
    ublock-unbreak: 1858-108, 2d.23h.53m
    urlhaus-1: 4669-1, 3h.18m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 558 ms (selfie)
  maxAssetCacheWait: 378 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    release-apk.com: 2
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Sandvici** [comment]
@okiehsch Is `$elemhide` supposed to not work if it's only applied on `forum.release-apk.com`? Does uBO think there's DOM coming from a different site?

**Comment by okiehsch** [comment]
I can't reproduce an anti adblock message. Maybe I need to be logged in?

@Sandvici
>> Does uBO think there's DOM coming from a different site?

Yes.
![image](https://user-images.githubusercontent.com/16838044/185569857-79ca79ef-ad53-4040-ada9-b2da92228812.png)

**Comment by MasterKia** [comment]
> I can't reproduce an anti adblock message. Maybe I need to be logged in?

The anti-adb message is at the bottom of page, I could reproduce using Firefox.

**Comment by okiehsch** [comment]
> The anti-adb message is at the bottom of page,

I see it now because I scrolled down quickly, it dissapears on my end after 2-3 seconds.

**Comment by ghajini** [comment]
it disappears then again visit another link then in new page it remains constant hiding content

**Comment by shawon2901** [comment]
> > The anti-adb message is at the bottom of page,
> 
> I see it now because I scrolled down quickly, it disappears on my end after 2-3 seconds.

Thats For The HomePage Only...There Post/SubPost There Where That Wont Happen.. Should I Share My Account With You ?

**Comment by JobcenterTycoon** [comment]
I get this and the anti adblock need 10 seconds until it disappear
<img width="796" alt="Unbenannt7" src="https://user-images.githubusercontent.com/48647394/185622535-2b5d81a7-79d7-4e5e-aec1-268d5589c458.PNG">

**Comment by Sandvici** [comment]
I don't even know if it detects uBO, did you test without uBO's filtering?

**Comment by shawon2901** [comment]
Website Is Working Now With UBO...There Is Big Gaps In Page Contents Tho

**Comment by MasterKia** [comment]
For the ad spots `forum.release-apk.com##.adsbygoogle` works.

But I can't reproduce an anti-adblock message even when badfilter-ing these from uBO filters:
```
@@||googleads.g.doubleclick.net/pagead/*forum.release-apk.com$subdocument,domain=forum.release-apk.com,badfilter

@@||pagead2.googlesyndication.com/pagead/$script,domain=forum.release-apk.com,badfilter

@@||forum.release-apk.com^$generichide,badfilter
```

**Comment by okiehsch** [comment]
Not on my end, but I don't have an account.

**Comment by okiehsch** [comment]
They were clearly needed a few days ago, as you can see by the fact that Adguard added filters similar to ours.
https://github.com/AdguardTeam/AdguardFilters/commit/3d4644db6de71f60a8514731bdb08973b2e22b84

Let's wait a bit before removing our filters.

**Comment by MasterKia** [comment]
With first filter on one of my reloads I saw Google ads.

**Comment by okiehsch** [comment]
> On one of my reloads I saw Google ads

I don't I only see blank spaces. `.adsbygoogle` is used as a bait check in such cases most of the time, it's the reason we added the ghide filter.

**Comment by MasterKia** [comment]
Maybe we could use style rules on it, but as you said let's wait a few days.

**Comment by hKQwHW** [comment]
Cannot reproduce on Firefox, Windows 10. An anti-adblock shows up at the very bottom for a few seconds, but goes away very quickly, doesn't interfere w/ page.

**Comment by stephenhawk8054** [comment]
Wait a few seconds and the content appears normally on firefox android for me.

**Comment by JobcenterTycoon** [comment]
Works fine for me. Just the loading time is a bit longer

**Comment by orariley70** [comment]
Nope, broken.
![image](https://user-images.githubusercontent.com/96967473/211741907-d406f599-6440-4773-8270-a0b61709cf30.png)
I can supply my account for debugging.

**Comment by stephenhawk8054** [comment]
It works fine for me after waiting a bit

![image](https://user-images.githubusercontent.com/66517106/211793128-293345ca-3425-46d8-a05c-7ec44a5df645.png)

**Comment by garry-ut99** [comment]
Many big ad placeholders all over the site caused by `ghide` from "uBlock filters":

![2222](https://user-images.githubusercontent.com/72945564/215355315-01825e85-6b9a-419b-ab7d-72f227f9691f.png)

**Comment by mapx-** [comment]
nothing to do, they are checking exactly the using of cosmetic filters

**Comment by garry-ut99** [comment]
Are you sure,  when "uBlock filters" disabled, the placeholders are gone.

**Comment by vanTheodore** [comment]
This is detecting again.
Link: `https://forum.release-apk.com/viewforum.php?f=60`

**Comment by dportvine** [comment]
`https://forum.release-apk.com/`

<details>
<summary>Screenshot(s)</summary>

![2023-10-13_092644](https://github.com/uBlockOrigin/uAssets/assets/111344219/42a368ae-059e-4fb3-98d5-06d54e89689c)
</details>

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 124909
 cosmetic: 106403
 scriptlet: 26514
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  fanboy-cookiemonster: 48555-229, 3m
  ublock-annoyances: 5547-59, 3m
  ublock-cookies-easylist: 326-326, 2m
 default:
  RUS-0: 40002-9, 3m
  easylist: 71734-38, 3m
  easyprivacy: 33199-154, 3m
  plowe-0: 3726-1073, 3m
  ublock-badware: 7297-134, 2m
  ublock-filters: 34941-184, 2m
  ublock-privacy: 560-7, 2m
  ublock-quick-fixes: 241-100, 2m
  ublock-unbreak: 2142-33, 2m
  urlhaus-1: 12055-0, 2m
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 643 ms (selfie)
 maxAssetCacheWait: 352 ms
popupPanel:
 blocked: 12
 network:
  release-apk.com: 2
  adskeeper.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  googleadservices.com: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
 extended:
  ##.phpbb-ads-center:style(pointer-events: none !important)
  ##ins:style(opacity: 0 !important; pointer-events: none !importa…
  ##+js(remove-attr, style, ins, complete)
  ##+js(addEventListener-defuser, load, onload)
  ##+js(nobab)
```
</details>

**Comment by JobcenterTycoon** [comment]
`forum.release-apk.com##+js(ra, style, ins, complete)` causing problems on my end. Should work fine now.

**Comment by AlexanderQueen** [comment]
> `forum.release-apk.com##+js(ra, style, ins, complete)` causing problems on my end. Should work fine now.

Same problem.

**Comment by drogga** [comment]
IDK about you guys, but the site and the ad blocker detection are so nasty, that it detects it (uBO) even when disabled (from the On/Off toggle switch in the /Extensions page), I guess it can detect if you have any ad blocker at all, I haven't tried to remove the extension to see if it will still detect a non-existing ad blocker whatsoever.

_Win 11 with 3 Chromium based browsers, in incognito, blocked third-party cookies, enabled "Do Not Track" and no DNS or anything other that can interrupt the loading and showing of any ads, well except the Ads Site Setting, which by default is set to block intrusive or misleading ads in most/all Chromium based browsers._

**Comment by stephenhawk8054** [comment]
> I guess it can detect if you have any ad blocker at all

No it doesn't. It means something else on your machine is triggering it OR the website has issue themselves. This website's code is a mess and can easily have false positives.

**Comment by drogga** [comment]
Must be the site then, because the problem is not on my end or my machine, I don't believe it's a network one either. I completely agree that it's a mess and an awful one (there's a better alternative).

**Comment by AlexanderQueen** [comment]
> Must be the site then, because the problem is not on my end or my machine, I don't believe it's a network one either. I completely agree that it's a mess and an awful one (there's a better alternative).

I experience the same issue even after with some "fixes" from above. Also, the site is buggy while loading their .JS modules...

**Comment by AlexanderQueen** [comment]
> The posts won't show unless I disable adblocker
> 
> `https://forum.release-apk.com/viewtopic.php?t=99023`
> 
> ![Image](https://github.com/user-attachments/assets/e2b5d6e1-ad05-4363-8515-37b76614ee03)

They change patterns every time. Sometimes it even with uBlock off it shows that you're running adblocker. Shitty detection...

**Comment by JobcenterTycoon** [comment]
Works fine for me with latest filter but with long loading times.
