### ISSUE TITLE
fcportables.com: detection and timer

### ISSUE THREAD

**Issue by AtharvaChavan** [uBlockOrigin/uAssets#14423]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.fcportables.com/wondershare-filmora-portable/`

### Describe the issue

Website not allowing: 
`https://www.fcportables.com/wondershare-filmora-portable/`

### uBlock Origin version

1.44.0

### Browser name and version

Firefox latest

### Settings

.

**Comment by MasterKia** [comment]
What do you mean "Website not allowing"?
Please explain more.

**Comment by MasterKia** [comment]
What do you mean "Website not allowing"?
Please explain more and send screenshot.

**Comment by krystian3w** [comment]
Maybe not allowing earn money for developers of paid software.

But uBo is not guillotine to block paid content shared as free.

**Comment by MasterKia** [comment]
https://user-images.githubusercontent.com/17685483/185410246-e38835cf-74ff-43f7-8ca7-c232dac5e573.png

**Comment by krystian3w** [comment]
On mobile don't detect uBo.

**Comment by MasterKia** [comment]
On desktop Firefox it does.

**Comment by MasterKia** [comment]
> On mobile don't detect uBo.

Yeah, I can't reproduce anymore.

**Comment by Procyon-b** [comment]
I can reproduce. I clear all cookies before page reload. And I scroll up and down mid page (it seems to help to trigger).
2 possibilities for me:
```
fcportables.com##+js(set, adsClasses, undefined)
```
or remove the stylesheet used by the dialog:
```
fcportables.com##head > style:has-text(.adblock):remove()
```

**Comment by MasterKia** [comment]
I like the first one.

**Comment by MasterKia** [comment]
I know cosmetic filters are preferred over scriptlets but I think first one is better; defuses the anti-adb.

**Comment by okiehsch** [comment]
> defuses the anti-adb.

That has priority.

**Comment by MasterKia** [comment]
I'll add.

**Comment by MasterKia** [comment]
@Procyon-b Since you can reproduce, is `fcportables.com##+js(no-fetch-if, doubleclick)` still needed?
```
fcportables.com#@#+js(no-fetch-if, doubleclick)
fcportables.com##+js(set, adsClasses, undefined)
```

**Comment by Procyon-b** [comment]
with
```
fcportables.com##+js(set, adsClasses, undefined)
```
no need to do anything about xhr connections.
Looking at the logger, the detection is defused before the 2 xhr connections (doubleclick and googlesyndication).

**Comment by MasterKia** [comment]
> no need to do anything about xhr connections.

Ok, so I'll remove it.

**Comment by dimisa-RUAdList** [comment]
<details>
<summary>The problem is back again</summary>

![portabl](https://user-images.githubusercontent.com/20126984/188262593-45ebe89d-74d1-4d4d-afdb-b295f8f3ff69.jpg)

</details>

**Comment by okiehsch** [comment]
Hm, still works on my end, I can only reproduce if I disable `uBO-filters`.

**Comment by stephenhawk8054** [comment]
Yeah, I can't reproduce either. Tried scrolling up and down, waiting or downloading, but still works fine.

**Comment by dimisa-RUAdList** [comment]
The detector window appears unstable. I have not been able to establish patterns. Perhaps the problem is specific only to Russia, where Google has disabled ads. Maybe add to the existing rules: `fcportables.com##div[id][class^="popup"][class$="wrap"]`?

**Comment by okiehsch** [comment]
>  the problem is specific only to Russia

Can't it be added to the russian list then?
If you can reproduce and you never add filters for non russian sites. We can add it, it won't break anything as far as I can see.

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/b7dfc578271f60702ce3c1fc565c22fe4872e411

**Comment by dimisa-RUAdList** [comment]
In fact, this rule works great even when uBlock filters are disabled.

**Comment by krystian3w** [comment]
Worse if page add frezze click on links.

**Comment by dimisa-RUAdList** [comment]
Are these any specific links?

**Comment by krystian3w** [comment]
Nobody read description on that page, so webmaster can add block to download even pop-up is hidden by vanilla css.
