### ISSUE TITLE
diziroll.me: ads

### ISSUE THREAD

**Issue by SumsukBirb** [uBlockOrigin/uAssets#14424]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://diziroll.me/dizi/euphoria/sezon-1/bolum-6`

### Category

ads

### Describe the issue

it still shows ads although i got an adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80172
  cosmetic: 45320
  scriptlet: 17645
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-0, never
    easylist: 69428-51, 3d.2h.4m
    easyprivacy: 27344-127, 3d.2h.5m
    plowe-0: 3630-777, 3d.17h.55m
    ublock-abuse: 76-0, 3d.17h.58m
    ublock-badware: 4233-92, 3d.2h.9m
    ublock-filters: 32463-116, 3d.2h.7m
    ublock-privacy: 231-3, 3d.17h.57m
    ublock-quick-fixes: 404-0, 21h.43m
    ublock-unbreak: 1860-43, 3d.2h.8m
    urlhaus-1: 4828-0, 21h.42m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 842 ms (selfie)
  maxAssetCacheWait: 521 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    aj2373.online: 1
    googletagmanager.com: 1
    hotpoint.pw: 1
```
</details>

**Comment by okiehsch** [comment]
Enable the regional turkish list.
