### ISSUE TITLE
att.com: breakage

### ISSUE THREAD

**Issue by awhelton** [uBlockOrigin/uAssets#14422]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.att.com/myatt/lgn/resources/auth/login/haloc/target-redirect?targeturl=https%3A%2F%2Fwww.att.com%2Facctmgmt%2Flogin%3Fstate%3Dfrom%253Didp%26haloSuccess%3Dtrue%26lt%3DZDEremk-OEZgYT5IIzkhI2hqfXRFQXQlRHY-TlQmQC5IVE4oOkpoNW9UKCUhKm8i`

### Category

breakage

### Describe the issue

page redirects endlessly without loading the actual page. occurs at login.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80471
  cosmetic: 45327
  scriptlet: 17640
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33202-70, 55m
    ublock-badware: 4237-0, 58m
    ublock-privacy: 247-0, 53m
    ublock-abuse: 76-0, 52m
    ublock-unbreak: 1871-0, 57m
    ublock-quick-fixes: 377-0, 21h.14m
    easylist: 69556-595, 56m
    easyprivacy: 27354-580, 54m
    urlhaus-1: 5026-0, 21h.13m
    plowe-0: 3634-3, 12d.4h.56m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 588 ms (selfie)
  maxAssetCacheWait: 304 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
open the logger, repeat the steps to get the issue, go back in the logger and post here all the blocked requests you see in the logger
