### ISSUE TITLE
lite.animevibe.se: breakage

### ISSUE THREAD

**Issue by 0-shubham-0** [uBlockOrigin/uAssets#14429]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lite.animevibe.se/recently-updated`

### Category

breakage

### Describe the issue

breakage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 212147
  cosmetic: 268795
  scriptlet: 39938
  html: 0
listset (total-discarded, last updated): 
  added: 
    IND-0: 11245-0, 50m
    JPN-1: 7606-9, 3d.20h.32m
    KOR-1: 1737-10, 83d.21h.30m
    POL-0: 7833-9, 53m
    RUS-0: 42019-12, 1d.20h.28m
    TUR-0: 8738-73, 3d.20h.46m
    VIE-1: 1910-2, 48m
    adguard-annoyance: 55983-392, 3d.20h.45m
    adguard-generic: 66940-1163, 2d.21h.2m
    adguard-mobile: 8135-98, 3d.20h.44m
    adguard-social: 18163-878, 3d.20h.43m
    adguard-spyware: 26789-1035, 3d.20h.42m
    adguard-spyware-url: 710-1, 3d.20h.41m
    block-lan: 43-0, 58m
    curben-phishing: 44713-1, 49m
    curben-pup: 189-1, 52m
    dpollock-0: 11380-290, 3d.19h.13m
    fanboy-annoyance: 79572-4633, 56m
    fanboy-cookiemonster: 40177-40177, 55m
    fanboy-social: 23272-23272, 3d.20h.38m
    [3 lists not shown]: [too many]
  default: 
    user-filters: 18-2, never
    easylist: 69428-1520, 3d.20h.40m
    easyprivacy: 27344-9757, 3d.20h.39m
    plowe-0: 3630-1322, 3d.20h.47m
    ublock-abuse: 76-1, 3d.20h.50m
    ublock-badware: 4233-330, 3d.20h.35m
    ublock-filters: 32473-4001, 3d.20h.34m
    ublock-privacy: 231-45, 3d.20h.49m
    ublock-quick-fixes: 409-22, 51m
    ublock-unbreak: 1858-117, 3d.20h.33m
    urlhaus-1: 4611-1, 47m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 81 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 920 ms (selfie)
  maxAssetCacheWait: 1728 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    animevibe.se: 1
    animemate.xyz: 1
```
</details>

**Comment by okiehsch** [comment]
You enabled 23 external lists...... try with a default setup.
The videos play fine on my end.
