### ISSUE TITLE
tv.cima4u.cloud: popups

### ISSUE THREAD

**Issue by madjid27** [uBlockOrigin/uAssets#14425]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tv.cima4u.cloud/`

### Category

popups

### Describe the issue

The extension was working like it always did on this website for me, but now it is not.
This website has popups.
I activated "Block all popups" on this site because of this.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80149
  cosmetic: 45345
  scriptlet: 17646
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33202-37, 11h.54m
    ublock-badware: 4237-1, 11h.53m
    ublock-privacy: 247-0, 4d.21h.55m
    ublock-abuse: 76-0, 11h.52m
    ublock-unbreak: 1872-0, 11h.51m
    ublock-quick-fixes: 401-34, 8h.14m
    easylist: 69559-240, 11h.50m
    easyprivacy: 27358-158, 11h.49m
    urlhaus-1: 4702-0, 8h.13m
    plowe-0: 3629-779, 4d.21h.44m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 761 ms (selfie)
  maxAssetCacheWait: 270 ms
popupPanel: 
  blocked: 9
  no-popups: true
  blockedDetails: 
    aubergearise.com: 3
    googletagmanager.com: 2
    thaudray.com: 4
```
</details>

**Comment by MasterKia** [comment]
Go to uBlock Origin settings => Filter lists => Regions, languages => Enable the "Liste AR" => Press "Update now"
Then test again.

There are filters for this site in the list.

**Comment by madjid27** [comment]
okay.
Thank you.
