### ISSUE TITLE
skodacommunity.de: ads

### ISSUE THREAD

**Issue by p-p-s** [uBlockOrigin/uAssets#14432]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.skodacommunity.de/threads/motor-geht-waehrend-der-fahrt-aus.118189/`

### Category

ads

### Describe the issue

This is a forum page and unfortunately in German only. The issue is the same with every thread in that forum. What appears as the first response to the question which was raised by opening the new thread is actually a link to amazon.de, where something with hardly any relation to the forum thread is being offered. It's just also about cars.

Translated, the display text of the link to amazon.de is "look here: Engine stops while driving. Everyone will find what they are looking for there!", i.e. generally it is "look here: _title of this thread._ Everyone will find what they are looking for there!", with the short Amazon icon (the "a" underlined by an arrow) in front of "Everyone." In the left pane, where the authors are shown it says "ad" instead of giving a user name. 

But if one does not carefully check the user name, overlooks the tiny icon, and does not think twice about the weird plural of "Everyone will find what they are looking for there!" in this thread's context, then one thinks the forum topic has been discussed somewhere else and a nice forum user is pointing me to the solution of my problem. I use that forum for years since I own a Skoda car and trapped in clicking the link several times, because fortunately I don't need to use the forum often and forget about the trap. 

I wouldn't report an ad issue with a forum, because often forums have troubles financing their hosting cost. But this camouflage tricking users to visit Web sites they don't want to visit is inappropriate.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80008
  cosmetic: 45317
  scriptlet: 17663
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 14h.24m
  default: 
    user-filters: 4-0, never
    easylist: 69429-51, 3d.15h.57m
    easyprivacy: 27357-127, 14h.27m
    plowe-0: 3629-776, 5d.12h.19m
    ublock-abuse: 76-0, 6d.5h.14m
    ublock-badware: 4233-92, 14h.26m
    ublock-filters: 32526-116, 14h.25m
    ublock-privacy: 231-3, 6d.5h.13m
    ublock-quick-fixes: 409-37, 7m
    ublock-unbreak: 1835-41, 14h.28m
    urlhaus-1: 4669-0, 14h.23m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1750 ms (selfie)
  maxAssetCacheWait: 470 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google-analytics.com: 1
    google.com: 5
    intellitxt.com: 1
    yieldscale.com: 1
```
</details>

**Comment by okiehsch** [comment]
It's pretty common on german forum sites, I have seen it on quite a few.
`skodacommunity.de##article.message--post.message:has-text(Anzeigen zu deaktivieren)`
works for me.
@monzta @khrin

**Comment by MasterKia** [comment]
@okiehsch Does EL Germany accept the extended syntax`:has-text`?

**Comment by okiehsch** [comment]
EasyList supports `:-abp-contains` which is the same thing.

**Comment by MasterKia** [comment]
Okay, I thought they don't support _any_ of the extended syntax at all (like redirect and scriptlet injection).

**Comment by MasterKia** [comment]
@okiehsch EasyList Cookie supports scriptlets, I wonder why EasyList doesn't.
![Screenshot_20220820_183059](https://user-images.githubusercontent.com/17685483/185749828-c98a2b8c-3d91-4a44-921e-9309794a32e9.png)
