### ISSUE TITLE
ymovies.to: ads

### ISSUE THREAD

**Issue by cap7707** [uBlockOrigin/uAssets#14434]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ymovies.to/film/by-the-sea-2015-61393/watching/`

### Category

ads

### Describe the issue

blanket filter overlay that creates pop ups. Unable to block as element. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80083
  cosmetic: 45472
  scriptlet: 17658
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 161-7, never
    easylist: 69556-51, 1d.14h.55m
    easyprivacy: 27354-127, 1d.10h.52m
    plowe-0: 3634-776, 9d.20h.54m
    ublock-abuse: 76-0, 11d.22h.36m
    ublock-badware: 4233-92, 1d.10h.51m
    ublock-filters: 32475-121, 1d.23h.17m
    ublock-privacy: 231-3, 1d.2h.50m
    ublock-quick-fixes: 410-2, 22h.49m
    ublock-unbreak: 1860-43, 3d.22h.50m
    urlhaus-1: 4611-0, 11h.53m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6681 ms (selfie)
  maxAssetCacheWait: 1895 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    ardslediana.com: 2
    dscex7u1h4a9a.cloudfront.net: 1
    googletagmanager.com: 1
    goomaphy.com: 1
    rtmark.net: 4
    tharbadir.com: 1
```
</details>

**Comment by cap7707** [comment]
Any suggestions welcome. So many popups now. Recent issue.

**Comment by ghajini** [comment]
update your filter lists
