### ISSUE TITLE
macleans.ca: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14439]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.macleans.ca/longforms/the-hunt-for-b-c-s-most-notorious-fisherman/`

### Category

ads

### Describe the issue

Leaderboard ad container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185690347-e3eca7d0-97a7-4f20-9a2f-950c2dc24831.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81785
  cosmetic: 82235
  scriptlet: 19302
  html: 725
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40236-81, 6h.35m
  default: 
    user-filters: 60-0, never
    ublock-filters: 33225-84, 6h.35m
    ublock-badware: 4247-0, 6h.35m
    ublock-privacy: 247-0, 6h.35m
    ublock-abuse: 76-0, 6h.35m
    ublock-unbreak: 1842-0, 6h.35m
    ublock-quick-fixes: 417-0, 6h.35m
    easylist: 69593-610, 6h.35m
    easyprivacy: 27390-583, 6h.35m
    urlhaus-1: 4611-0, 6h.35m
    plowe-0: 3632-3, 6h.35m
filterset (user): [array of 60 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 216 ms (selfie)
  maxAssetCacheWait: 304 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    macleans.ca: 8
    adobedtm.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    privy.com: 1
```
</details>

**Comment by MasterKia** [comment]
`macleans.ca###leaderboard.ad`
@ryanbr

**Comment by MasterKia** [comment]
Thanks for reporting to EL.
