### ISSUE TITLE
[nsfw] koushoku.org: detection

### ISSUE THREAD

**Issue by coolkid3245** [uBlockOrigin/uAssets#14437]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://koushoku.org/archive/9335/the-tale-of-a-decent-female-adventurer-getting-lost-inside-an-erotic-trap-dungeon-character-file-qa-1/2`

### Category

detection

### Describe the issue

Main content does not load with ublock enabled (screenshot 1, note "?" on zoom level)

Content loads after ad loads (page loads, default koushoku banner on adspace > ad loads > content loads [screenshot 2, note "100%" on zoom level])

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/24840466/185651220-80cefe70-267f-4e2d-b552-49635662d979.png)
![image](https://user-images.githubusercontent.com/24840466/185651302-18f2013c-678b-447e-b56b-8b62b814ee06.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80117
  cosmetic: 45370
  scriptlet: 17669
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69597-51, 5m
    easyprivacy: 27390-126, 5m
    plowe-0: 3632-776, 3m
    ublock-abuse: 76-0, 3m
    ublock-badware: 4243-92, 3m
    ublock-filters: 32530-122, 5m
    ublock-privacy: 231-3, 3m
    ublock-quick-fixes: 420-37, 3m
    ublock-unbreak: 1829-41, 3m
    urlhaus-1: 4622-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1059 ms
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    realsrv.com: 2
```
</details>

**Comment by sverafan** [comment]
@okiehsch Main content loads after this fix but now the navigation is broken. Clicking on the left side of the image should take you to the previous image and clicking on the right side should take you to the next one. Navigation arrow keys above the image are not working either.
