### ISSUE TITLE
Domain not Blocked (noop)

### ISSUE THREAD

**Issue by eldelamai** [uBlockOrigin/uAssets#14435]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://advice-ads.s3.amazonaws.com

### Describe the issue

The AdBlock Test by D3ward (https://d3ward.github.io/toolz/adblock.html) says the domain, "https://advice-ads.s3.amazonaws.com" should be blocked, but my uBlock Logger says it got 'nooped'

### Screenshot(s)

<img width="1440" alt="Screen Shot 2022-08-19 at 9 48 51 AM" src="https://user-images.githubusercontent.com/96963449/185646448-f7aebf18-0420-4ece-8dad-20f4adcca8fe.png">
<img width="1440" alt="Screen Shot 2022-08-19 at 9 51 27 AM" src="https://user-images.githubusercontent.com/96963449/185646465-6d467bff-40ec-431e-b5fa-ec25b8971399.png">

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 104.0.5112.79

### Settings

.

**Comment by Yuki2718** [comment]
We don't "fix" PoX/test sites.
