### ISSUE TITLE
interier-ricany.cz: breakage

### ISSUE THREAD

**Issue by Vilican** [uBlockOrigin/uAssets#14436]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://interier-ricany.cz/cs/produkty/vse`

### Category

breakage

### Describe the issue

Scrolling on the page does not work because of a removed cookie notice.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11300407/185651409-96ca0fd3-4c2e-4a3b-9b68-73f18fa5a2be.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 191559
  cosmetic: 201653
  scriptlet: 37991
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1h.2m
    adguard-annoyance: 56428-81, 1d.13h.23m
    adguard-generic: 67014-710, 1d.13h.21m
    adguard-mobile: 8149-46, 1d.13h.25m
    adguard-spyware: 26458-1003, 1d.13h.24m
    adguard-spyware-url: 713-1, 1d.13h.22m
    block-lan: 43-0, 1d.13h.34m
    curben-phishing: 47113-8, 57m
    curben-pup: 189-1, 56m
    dpollock-0: 11381-261, 1d.17h.35m
    fanboy-annoyance: 79631-3591, 1h.3m
    fanboy-cookiemonster: 40070-40038, 19h.4m
    ublock-annoyances: 4524-238, 1d.13h.26m
  default: 
    user-filters: 2-0, never
    CZE-0: 716-0, 58m
    easylist: 69556-1401, 1d.13h.32m
    easyprivacy: 27354-9616, 1d.13h.31m
    plowe-0: 3629-1306, 6d.15h.30m
    ublock-abuse: 76-0, 6d.15h.29m
    ublock-badware: 4233-333, 1d.13h.30m
    ublock-filters: 32507-3921, 1d.13h.29m
    ublock-privacy: 231-44, 6d.15h.28m
    ublock-quick-fixes: 420-48, 1h
    ublock-unbreak: 1859-107, 1d.13h.27m
    urlhaus-1: 4622-1, 59m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 635 ms
  maxAssetCacheWait: 441 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    app-us1.com: 1
    googletagmanager.com: 2
    leady.com: 1
```
</details>

**Comment by MasterKia** [comment]
> because of a removed cookie notice.

uBlock Origin doesn't remove any cookie notice with the default lists.

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1h.2m
    adguard-annoyance: 56428-81, 1d.13h.23m
    adguard-generic: 67014-710, 1d.13h.21m
    adguard-mobile: 8149-46, 1d.13h.25m
    adguard-spyware: 26458-1003, 1d.13h.24m
    adguard-spyware-url: 713-1, 1d.13h.22m
    block-lan: 43-0, 1d.13h.34m
    curben-phishing: 47113-8, 57m
    curben-pup: 189-1, 56m
    dpollock-0: 11381-261, 1d.17h.35m
    fanboy-annoyance: 79631-3591, 1h.3m
    fanboy-cookiemonster: 40070-40038, 19h.4m
    ublock-annoyances: 4524-238, 1d.13h.26m


Please test using _**only the default lists**_.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/185659044-5bf62ac0-d8eb-47d0-b767-b752ad5826f5.png)


Atleast he's honest about it. 😉 
`interier-ricany.cz#@##cookies-modal`
@ryanbr it's in the annoyance and the cookie list.
