### ISSUE TITLE
forbes.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14433]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.forbes.com/sites/emilybaker-white/2022/08/10/bytedance-tiktok-china-state-media-propaganda/`

### Category

ads

### Describe the issue

Ad container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185647151-273da439-57c9-4905-9059-b33be0ac325e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81776
  cosmetic: 82228
  scriptlet: 19300
  html: 725
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40236-86, 2h.20m
  default: 
    user-filters: 42-0, never
    ublock-filters: 33225-84, 2h.20m
    ublock-badware: 4247-0, 2h.20m
    ublock-privacy: 247-0, 2h.20m
    ublock-abuse: 76-0, 2h.20m
    ublock-unbreak: 1842-0, 2h.20m
    ublock-quick-fixes: 417-0, 2h.20m
    easylist: 69593-610, 2h.20m
    easyprivacy: 27390-578, 2h.20m
    urlhaus-1: 4611-0, 2h.20m
    plowe-0: 3632-3, 2h.20m
filterset (user): [array of 42 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms
  maxAssetCacheWait: 272 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    forbes.com: 3
    adsafeprotected.com: 1
    amazon-adsystem.com: 1
    criteo.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 2
    media.net: 2
    moatads.com: 1
    newrelic.com: 1
    p-n.io: 2
    sharethrough.com: 2
    speedcurve.com: 2
    tinypass.com: 1
```
</details>

**Comment by MasterKia** [comment]
`##[class^="fbs-ad"]` from uBlock filters is defunct.

![Screenshot_20220819_225305](https://user-images.githubusercontent.com/17685483/185683066-b1f39d7c-5e2e-446c-ad02-d87f4d8fb11f.png)
