### ISSUE TITLE
melmagazine.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14441]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://melmagazine.com/en-us/story/healthy-drive-thru`

### Category

ads

### Describe the issue

Two ad containers:
- Leaderboard ad
- Inline content ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185693419-3dfa3708-042e-4e47-b0ff-899d96b05140.png)

---

![image](https://user-images.githubusercontent.com/110956608/185693532-18860976-8979-4be8-b83d-68f3855380d1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81787
  cosmetic: 82236
  scriptlet: 19302
  html: 725
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40236-113, 6h.53m
  default: 
    user-filters: 63-0, never
    ublock-filters: 33225-159, 6h.53m
    ublock-badware: 4247-0, 6h.53m
    ublock-privacy: 247-0, 6h.53m
    ublock-abuse: 76-0, 6h.53m
    ublock-unbreak: 1842-0, 6h.53m
    ublock-quick-fixes: 417-0, 6h.53m
    easylist: 69593-491, 6h.53m
    easyprivacy: 27390-595, 6h.53m
    urlhaus-1: 4611-0, 6h.53m
    plowe-0: 3632-3, 6h.53m
filterset (user): [array of 63 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 216 ms (selfie)
  maxAssetCacheWait: 304 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    melmagazine.com: 2
    ad.gt: 2
    amazon-adsystem.com: 1
    chartbeat.com: 1
    connatix.com: 1
    doubleclick.net: 1
    organiccdn.io: 2
    sail-horizon.com: 2
    sentry.io: 1
    skimresources.com: 2
    tru.am: 2
```
</details>

**Comment by Sandvici** [comment]
`melmagazine.com##.empire-unit-prefill-container` @ryanbr
