### ISSUE TITLE
[nsfw] sissymeet.com: malfunction

### ISSUE THREAD

**Issue by spock1231gaming** [uBlockOrigin/uAssets#14440]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sissymeet.com/account/messages/`

### Category

malfunction

### Describe the issue

the paywall blocker does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 80114
  cosmetic: 45347
  scriptlet: 17657
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 69560-51, 1d.15h.46m
    easyprivacy: 27354-127, 1d.15h.45m
    plowe-0: 3634-776, 9d.17h.26m
    ublock-abuse: 76-0, 9d.17h.24m
    ublock-badware: 4233-92, 1d.15h.44m
    ublock-filters: 32507-121, 1d.15h.43m
    ublock-privacy: 231-3, 9d.17h.20m
    ublock-quick-fixes: 410-37, 1d.1h.24m
    ublock-unbreak: 1858-43, 1d.15h.42m
    urlhaus-1: 4669-0, 1d.1h.23m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1494 ms (selfie)
  maxAssetCacheWait: 941 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
> the paywall

Screenshot?

**Comment by MasterKia** [comment]
If what you're asking is similar to what you asked in https://github.com/uBlockOrigin/uAssets/issues/14335, then you can't workaround a hard paywall (I assume the site asks you to pay before messaging other users).
Even If it's a soft paywall:

> [Circumventing a paywall is considered out of scope.](https://github.com/uBlockOrigin/uAssets#paywall)
