### ISSUE TITLE
link.square-enix-games.com: breakage

### ISSUE THREAD

**Issue by psxlover** [uBlockOrigin/uAssets#14443]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://link.square-enix-games.com/view/5e5cfdbc3e01dd6abe2de3e5h4u8v.149g/19665a2c`

### Category

breakage

### Describe the issue

Images are blocked in Square Enix newsletter. The images don't appear both when viewing the e-mail in outlook, and when clicking `View this email in your browser` where a dedicated page opens.

Issue seems to be caused by EasyPrivacy filter list. Disabling it makes the images work both when viewing the newsletter as an e-mail in outlook.live.com and when visiting the dedicated newsletter page.

(off topic: image for [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png) seems to be quite outdated)

### Screenshot(s)

<details>
<summary>Screenshots</summary>

- With `EasyPrivacy` filter list **on**:
  - E-mail
     ![image](https://user-images.githubusercontent.com/1429524/185704481-1440d9ef-2915-4fba-9558-51308973c683.png)
  - Dedicated web page
     ![image](https://user-images.githubusercontent.com/1429524/185704853-153c230a-d004-47fc-9e77-fc445ae23e9e.png)
- With `EasyPrivacy` filter list **off**:
  - E-mail
     ![image](https://user-images.githubusercontent.com/1429524/185705148-526e5a8a-3704-4376-8162-72841a0c00f1.png)
  - Dedicated web page
     ![image](https://user-images.githubusercontent.com/1429524/185705598-c3f86be9-d80b-4731-8ad0-0877fff6ea16.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 79976
  cosmetic: 45339
  scriptlet: 17652
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 33174-40, 3d.13h.7m
    ublock-badware: 4237-0, 3d.13h.6m
    ublock-privacy: 247-0, 3d.13h.11m
    ublock-abuse: 76-0, 3d.13h.12m
    ublock-unbreak: 1873-0, 3d.13h.5m
    easylist: 69461-590, 3d.13h.9m
    easyprivacy: 27348-580, 3d.13h.8m
    plowe-0: 3634-3, 12d.16h.10m
    urlhaus-1: 4611-0, 8h.51m
    ublock-quick-fixes: 406-0, 8h.50m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12014 ms (selfie)
  maxAssetCacheWait: 260 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    sailthru.com: 10
```
</details>

**Comment by Sandvici** [comment]
@ryanbr

**Comment by MasterKia** [comment]
`@@||media.sailthru.com/composer/images$image,domain=link.square-enix-games.com`

@ryanbr EasyPrivacy

**Comment by MasterKia** [comment]
@psxlover It's fixed, force update your filter lists after 10 minutes.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
