### ISSUE TITLE
radiomitre.cienradios.com: breakage

### ISSUE THREAD

**Issue by pardo-bsso** [uBlockOrigin/uAssets#14445]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://radiomitre.cienradios.com/player/mitre-am790/`

### Category

breakage

### Describe the issue

On this site, and most under `*.cienradios.com/player/*` (with this one I can reproduce all the time), the audio and video player crashes because it fails to load the imasdk from google (throws to the console and never manages to play). EDIT: fixed formatting of base url.

Currently I'm working around this adding an exception for it:

    @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=radiomitre.cienradios.com

doing so restores the expected behaviour (audio or video plays upon request). Even if it allows that script in media ads are skipped (thanks uBlock!)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 91
filterset (summary): 
  network: 92039
  cosmetic: 118241
  scriptlet: 24650
  html: 732
listset (total-discarded, last updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    adguard-annoyance: 56470-4973, 1d.6h.44m
    adguard-social: 18227-1653, 1d.6h.38m
    fanboy-thirdparty_social: 68-1, 3d.21h.18m
    fanboy-annoyance: 79085-67299, 3d.21h.16m
    fanboy-cookiemonster: 39708-16833, 3d.21h.17m
    fanboy-social: 23293-13680, 8h.43m
    ublock-annoyances: 4532-7, 1d.6h.45m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33205-304, 1d.6h.43m
    ublock-badware: 4237-0, 1d.6h.42m
    ublock-privacy: 247-1, 8d.6h.4m
    ublock-abuse: 76-0, 8d.6h.3m
    ublock-unbreak: 1852-0, 1d.6h.41m
    easylist: 69578-25018, 1d.6h.40m
    easyprivacy: 27357-584, 1d.6h.39m
    urlhaus-1: 4622-0, 8h.42m
    plowe-0: 3629-3, 7d.11h.2m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 64 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7280 ms (selfie)
  maxAssetCacheWait: 1126 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    2mdn.net: 1
    chartbeat.com: 2
    cxense.com: 1
    doubleclick.net: 1
    facebook.net: 2
    go-mpulse.net: 2
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    scorecardresearch.com: 1
    smartadserver.com: 3
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by pardo-bsso** [comment]
That was fast, thanks!
