### ISSUE TITLE
lightnovelpub.com: nuisance

### ISSUE THREAD

**Issue by JoKEraI1** [uBlockOrigin/uAssets#14448]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelpub.com/novel/the-authors-pov-07082217`

### Category

nuisance

### Describe the issue

I am accessing this website using kiwi browser on mobile but with the native ad block option disabled

New implementation of ad block detection. Once you enter any novel listed on the site you will see a big red warning about using ad block.

Accessing any chapters now with ad block will show a blank screen without any content. The content appears after turning off ad block.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**At novel page**
https://user-images.githubusercontent.com/51981209/185727984-43c79e89-6726-47e5-8d2d-da4a091e3785.jpg

**Accessing a chapter with ublock active**
https://user-images.githubusercontent.com/51981209/185727987-32f1637c-7acc-4c06-b484-2c45528be54d.jpg

**Accessing same chapter with ublock turned off**
https://user-images.githubusercontent.com/51981209/185727989-c78f02f3-46f9-4ff5-81ad-12c9e02631ea.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 101
filterset (summary): 
  network: 86187
  cosmetic: 75526
  scriptlet: 23171
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 56543-1643, 2m
    ublock-annoyances: 4550-168, 4m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8144-31, 2d.11h.37m
    easylist: 69526-24690, 2d.13h.36m
    easyprivacy: 27354-236, 2d.13h.35m
    plowe-0: 3635-867, 21h.24m
    ublock-abuse: 76-0, 1d.13h.8m
    ublock-badware: 4232-92, 2d.13h.34m
    ublock-filters: 32617-769, 2d.13h.33m
    ublock-privacy: 231-4, 1d.13h.7m
    ublock-quick-fixes: 271-55, 21h.23m
    ublock-unbreak: 1863-47, 2d.11h.36m
    urlhaus-1: 4611-0, 21h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 821 ms
  maxAssetCacheWait: 529 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    intergient.com: 2
    moatads.com: 1
    pub.network: 2
    quantcast.com: 1
```
</details>

**Comment by MasterKia** [comment]
It's fixed, force update your filter lists after 10 minutes.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
