### ISSUE TITLE
bloggertheme.xyz

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#14444]
https://github.com/AdguardTeam/AdguardFilters/issues/126929
hidden timer
could an exclusion for `go.bloggertheme.xyz` be made from (such as `go.bloggertheme.xyz#@##timer` or adding `,~go.bloggertheme.xyz` to a filter?

**Comment by MasterKia** [comment]
What's the problem?
`bloggertheme.xyz##+js(nano-setTimeout-booster, waiting, 5000)` from uBO filters works fine and gets past `go.bloggertheme.xyz/KVTWwSv1`.

**Comment by MasterKia** [comment]
What's the problem?
`bloggertheme.xyz##+js(nano-setTimeout-booster, waiting, 5000)` from uBO Filters works fine and gets past `go.bloggertheme.xyz/KVTWwSv1` timer.
I didn't get any anti-adb along the way.

**Comment by okiehsch** [comment]
> What's the problem?

The OP deleted the account.
