### ISSUE TITLE
visa.com/supplierlocator/search/index.jsp

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1444]
### URL(s) where the issue occurs

`https://www.visa.com/supplierlocator/search/index.jsp`

### Describe the issue

Clicking SEARCH doesn't work.

### Settings

Default

### Notes

`@@javascript/analytics` fixes it.
More specifically:
`@@https://www.visa.com/supplierlocator/search/javascript/analytics/analytics.js`
and
`@@https://www.visa.com/supplierlocator/search/javascript/analytics/ntpagetag.js`

This doesn't seem to be required: `@@https://www.visa.com/supplierlocator/search/javascript/analytics/ntautotag.js`

**Comment by okiehsch** [comment]
Thx for investigating.
