### ISSUE TITLE
anandtech.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#14450]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.anandtech.com/show/11790/the-hp-s700-and-s700-pro-ssd-review/9`

### Category

ads

### Describe the issue

Blank white space in the text area. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1303" alt="Screen Shot 2022-08-19 at 9 30 47 PM" src="https://user-images.githubusercontent.com/69532417/185728986-5b6f43da-1536-450b-b01b-d792ac2f28fd.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 176751
  cosmetic: 217145
  scriptlet: 37854
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 56543-80, 3m
    adguard-generic: 67083-696, 3m
    adguard-mobile: 8155-46, 3m
    adguard-social: 18234-868, 3m
    adguard-spyware: 26486-1002, 3m
    adguard-spyware-url: 720-1, 3m
    block-lan: 43-0, 3m
    curben-phishing: 48645-0, 3m
    curben-pup: 188-1, 3m
    fanboy-annoyance: 79681-4669, 3m
    fanboy-cookiemonster: 40286-40286, 3m
    ublock-annoyances: 4530-238, 3m
  default: 
    user-filters: 0-0, never
    easylist: 69599-1177, 3m
    easyprivacy: 27394-9561, 3m
    plowe-0: 3634-952, 9d.9h.57m
    ublock-abuse: 76-0, 3m
    ublock-badware: 4259-329, 3m
    ublock-filters: 32535-3925, 3m
    ublock-privacy: 231-44, 9d.9h.59m
    ublock-quick-fixes: 420-48, 3m
    ublock-unbreak: 1829-104, 3m
    urlhaus-1: 5419-1, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 660 ms (selfie)
  maxAssetCacheWait: 694 ms
popupPanel: 
  blocked: 43
  blockedDetails: 
    3lift.com: 1
    adsrvr.org: 1
    bidswitch.net: 2
    consensu.org: 1
    contextweb.com: 1
    criteo.com: 1
    dotmetrics.net: 1
    doubleclick.net: 1
    emxdgt.com: 3
    facebook.com: 1
    futurehybrid.tech: 1
    google-analytics.com: 5
    google.com: 1
    googletagmanager.com: 1
    id5-sync.com: 1
    jwpcdn.com: 1
    jwpltx.com: 1
    lijit.com: 1
    mfadsrvr.com: 1
    omnitagjs.com: 1
    openx.net: 2
    parsely.com: 1
    pubmatic.com: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
    skimresources.com: 1
    smartadserver.com: 1
    spotxchange.com: 3
    stackadapt.com: 1
    taboola.com: 2
    twitter.com: 1
    uuidksinc.net: 1
```
</details>

**Comment by MasterKia** [comment]
`anandtech.com###taboola-mid-article`

@ryanbr

**Comment by MasterKia** [comment]
@okiehsch I kept it open because I figured if they don't address it in ~4 days we could/should add it ourselves.

Though they addressed this one pretty quickly: https://github.com/uBlockOrigin/uAssets/issues/14446

**Comment by okiehsch** [comment]
As per our readme
> If an issue can be fixed without using extended syntax, i.e. [scriptlet injection](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection), [redirect](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect), [procedural cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters), etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

We usually don't fix these kind of issues in uAssets, especially an issue like this, i.e. a blank space and not even an ad.

**Comment by MasterKia** [comment]
> fixing it in EasyList **_if possible_** is preferable.

"Not possible" if they don't pay attention and address it.

> We usually don't fix blank space and not even an ad.

Ok.

**Comment by okiehsch** [comment]
The "if possible" means if it is possible to fix the issue with the filter syntax EasyList supports.

**Comment by MasterKia** [comment]
Fair enough.
The OP could always add it to "My filters" if it bothers him so much.
