### ISSUE TITLE
coolors.co ads

### ISSUE THREAD

**Issue by RedyAu** [uBlockOrigin/uAssets#14457]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://coolors.co/generate`
(Redirects to unique URLs depending on selected colors, ads appear on any of them)

### Describe the issue

On the generator page, two floating and one "docked" ads appear.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12989935/185760399-1035a369-a1cf-4435-851c-b64014b0fe67.png)

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 104.0.5112.82

### Settings

No relevant setting changes

### Notes

The ads have randomly generated IDs. Should be possible to filter by looking at style.
Previous filters for these are not working anymore, as the site started using random IDs.

**Comment by okiehsch** [comment]
It's self advertisement or an annoyance,
````
coolors.co###generator-tutorial-intro
coolors.co##body.route-generate:style(overflow: auto !important; position: initial !important;)
````
or enable `AdGuard Annoyances`.

**Comment by RedyAu** [comment]
These are not always used for self-advertisement, the placements are sold too. In the example it happened to show all self-ads.

**Comment by MasterKia** [comment]
`https://coolors.co/advertise`

`https://affiliates.coolors.co/` (For me it got stuck on loading)

**Comment by MasterKia** [comment]
> the placements are sold too

`https://coolors.co/advertise`

`https://affiliates.coolors.co/`
(For me it got stuck on loading)
