### ISSUE TITLE
lightnovelpub.com: nuisance

### ISSUE THREAD

**Issue by shadus** [uBlockOrigin/uAssets#14452]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelpub.com/novel/my-necromancer-class-07082217/1405-chapter-1`

### Category

nuisance

### Describe the issue

I am aware of https://github.com/uBlockOrigin/uAssets/issues/14448 but it is not entirely resolved (tested last at 3am EDT (GMT-4)), the red "you have an adblocker" issue has been resolved after the update however, even after purge and update, restarting browser, the novel contents still do not display.  I verified same results with chrome in windows 10 with internal adblocker on and off and I am using no additional adblockers.  Verified issue occurs in firefox in windows 10 as well.

Examples with ublock on and off included in screenshots.  Added example of the popup adds that occur with blocking off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot-ublock-off](https://user-images.githubusercontent.com/343631/185733581-d69c7236-e9c9-4db1-b1d8-370a42292480.png)
![screenshot-ublock-on](https://user-images.githubusercontent.com/343631/185733584-fd467785-4dc6-4c14-8ec5-dccaabc9f6c0.png)
![image](https://user-images.githubusercontent.com/343631/185733713-9de9f3b8-239a-45e3-8d4b-27d79548acac.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80924
  cosmetic: 45411
  scriptlet: 17672
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-0, never
    easylist: 69600-51, 12m
    easyprivacy: 27394-126, 12m
    plowe-0: 3632-776, 12m
    ublock-abuse: 76-0, 12m
    ublock-badware: 4259-92, 12m
    ublock-filters: 32536-122, 12m
    ublock-privacy: 231-3, 12m
    ublock-quick-fixes: 420-37, 12m
    ublock-unbreak: 1830-41, 12m
    urlhaus-1: 5419-0, 12m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 30 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 343 ms (selfie)
  maxAssetCacheWait: 110 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    intergient.com: 1
    quantserve.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by MasterKia** [comment]
```
lightnovelpub.com##.lnadcontainer
lightnovelpub.com##.adsbox
```

@ryanbr These from EasyList remove the content

**Comment by MasterKia** [comment]
@shadus Force update your filter lists again after 10 minutes.

**Comment by shadus** [comment]
@MasterKia Purged and updated, the novel is now showing however, so are all the ads.
