### ISSUE TITLE
olx.pt: breakage

### ISSUE THREAD

**Issue by motorider34** [uBlockOrigin/uAssets#14458]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.olx.pt/d/anuncio/suzuki-jimny-1-3i-cabrio-ar-condicionado-IDHfZPo.html`

### Category

breakage

### Describe the issue

When access to this webpage, it shows an error.
Disable UBlock and works fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80904
  cosmetic: 45348
  scriptlet: 17657
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33176-37, 2d.9h.14m
    ublock-badware: 4237-1, 2d.9h.13m
    ublock-privacy: 247-0, 2d.9h.12m
    ublock-abuse: 76-0, 2d.9h.11m
    ublock-unbreak: 1872-0, 2d.9h.10m
    ublock-quick-fixes: 417-2, 1h.59m
    easylist: 69559-594, 2d.9h.8m
    easyprivacy: 27358-581, 2d.9h.7m
    urlhaus-1: 5443-0, 1h.58m
    plowe-0: 3635-3, 1d.17h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 520 ms (selfie)
  maxAssetCacheWait: 315 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    criteo.net: 3
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    newrelic.com: 1
    olx-st.com: 3
    olx.org: 1
    sentry.io: 4
```
</details>

**Comment by Yuki2718** [comment]
@gorhill No error on AG with doubleclick redirect.
