### ISSUE TITLE
[nsfw] animemeat.com: popups

### ISSUE THREAD

**Issue by D3mitre** [uBlockOrigin/uAssets#14455]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animemeat.com/cw/cw_0822/land_cw_050822_na_en/?utm_campaign=pu_exo_mushoku-tensei.online_na&utm_medium=click&utm_source=pu&utm_content=mushoku-tensei.online&bnid=land_cw_050822_na_en&landing=modest&land=land_cw_250522_na_en&crID=2497885&zID=99123`

### Category

popups

### Describe the issue

Shows up while I'm traversing through links on a website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 71847
  cosmetic: 38519
  scriptlet: 16050
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63161-7, 508d.20h.26m
    easyprivacy: 22344-40, 508d.20h.24m
    plowe-0: 3571-230, 508d.20h.38m
    ublock-abuse: 72-0, 508d.20h.30m
    ublock-badware: 1354-20, 508d.20h.34m
    ublock-filters: 28082-87, 508d.20h.36m
    ublock-privacy: 119-2, 508d.20h.32m
    ublock-unbreak: 1523-10, 508d.20h.28m
    urlhaus-1: 6742-0, 508d.20h.21m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4530 ms (selfie)
  maxAssetCacheWait: 2274 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    gamesrevenue.com: 1
    yandex.ru: 1
```
</details>

**Comment by MasterKia** [comment]
> - [X] I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Do it twice and test again. Your filter lists are almost two years old.

**Comment by MasterKia** [comment]
> - [X] I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Do it twice and test again. Your filter lists are almost two years old.

**Comment by MasterKia** [comment]
> - [X] I forced an update of my filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Do it twice and test again.

**Comment by okiehsch** [comment]
> while I'm traversing through links on a website

Which website?

**Comment by Yuki2718** [comment]
We need the original link which led you to this site.

**Comment by ghajini** [comment]
i guess website

`mushoku-tensei.online##+js(acs, document.querySelectorAll, popMagic)`

**Comment by Yuki2718** [comment]
Yeah, it's in utm paramter.

**Comment by MasterKia** [comment]
> ublock-filters: 28082-87, 508d.20h.36m

508d, is this normal?

**Comment by Yuki2718** [comment]
> 508d, is this normal?

Obviously abnormal

**Comment by MasterKia** [comment]
> modifiedUserSettings: 
  autoUpdate: false

I see.
