### ISSUE TITLE
wings.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1445]
### URL(s) where the issue occurs
`http://wings.io`

### Describe the issue
Displays an anti-adblock message.

### Screenshot(s)
![wings io anti-adblock](https://user-images.githubusercontent.com/29117662/35716797-ebb1d1a6-078f-11e8-9593-38e07d662cc4.PNG)

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.14.25.101 (Nano Adblocker 1.0.0.28)

### Settings
Default.

### Notes
Anti-adblock.

**Comment by okiehsch** [comment]
Fixed in `uBlock filters – Annoyances`.
