### ISSUE TITLE
eksisozluk.com: [breakage]

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#14464]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://eksisozluk.com/`

### Describe the issue

same issue as this: https://github.com/uBlockOrigin/uAssets/issues/6295
you can't click most links in first click after a page is loaded. only second click works.

### uBlock Origin version

1.44.0

### Browser name and version

Firefox latest

### Settings

Default + Adguard Turkish list

**Comment by ahmedtds** [comment]
adding this again solves the problem: https://github.com/uBlockOrigin/uAssets/commit/8cfc3fe34e685756bf3c330e261db189090f04a9

and I don't see the issue that required it to be removed there.

**Comment by MasterKia** [comment]
> I don't see the issue that required it to be removed there.

https://github.com/uBlockOrigin/uAssets/issues/14152

**Comment by ahmedtds** [comment]
> > I don't see the issue that required it to be removed there.
> 
> So the issue said here #14152 doesn't happen anymore?

No I'm not seeing that issue now that I added the filter back as a custom filter.

**Comment by okiehsch** [comment]
@Yuki2718 I can reproduce, is this something Adguard fixes in the regional turkish list?

**Comment by Yuki2718** [comment]
This is kind of caused by redirect, `@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule,domain=eksisozluk.com` fixes this on my end. AG also has the issue but the fix will go to Tracking Protection filter. An alternative will be a bit more specified scriptlet `eksisozluk.com##+js(nostif, wt(), 100)`.

**Comment by okiehsch** [comment]
>  caused by redirect

Your right, I will fix it in `uBO-unbreak`.

**Comment by ahmedtds** [comment]
unfortunately this created another problem, I can't press the "her zamanki görünüme dön" button while logged-in now. (for some reason it can be pressed while not logged-in, I don't know how can I help to debug this)

I disabled "uBlock filters – Unbreak" and added this to "My Filters" (was suggested by @Yuki2718 above): `eksisozluk.com##+js(nostif, wt(), 100)`

and there is no issue while both logged out or logged in.

**Comment by ahmedtds** [comment]
@Yuki2718 thanks for re-opening, where can I send account info?

**Comment by mapx-** [comment]
> @Yuki2718 thanks for re-opening, where can I send account info?

You could try a pm on reddit
https://www.reddit.com/user/Yuki2718/

**Comment by Yuki2718** [comment]
Or if you use Twitter: https://twitter.com/Yuki27183

**Comment by Yuki2718** [comment]
@ahmedtds If you don't have an account of either and don't want to create one, PM to `bh.ssp220[at]gmail.com`. I'll soon delete this post.

**Comment by MasterKia** [comment]
@Yuki2718 Did he send an account?

**Comment by Yuki2718** [comment]
> Did he send an account?

No.

**Comment by Drawingnearer** [comment]
Hello
[This issue](https://github.com/uBlockOrigin/uAssets/issues/14591#issue-1355353877) still persists.
The "her zamanki gorunume don" (switch back to classic view) button does not work unless You disable Ublock's built-in "Unbreak" filter. Are there any workarounds?

**Comment by Drawingnearer** [comment]
Hello
https://github.com/uBlockOrigin/uAssets/issues/14591#issue-1355353877 still persists.
The "her zamanki gorunume don" (switch back to classic view) button does not work unless You disable Ublock's built-in "Unbreak" filter. Are there any workarounds? @Yuki2718 @okiehsch

**Comment by mapx-** [comment]
@Drawingnearer could you send an account ?

**Comment by Drawingnearer** [comment]
Hello
https://github.com/uBlockOrigin/uAssets/issues/14591#issue-1355353877 still persists.
The "her zamanki gorunume don" (switch back to classic view) button does not work unless You disable Ublock's built-in "Unbreak" filter. Are there any workarounds? @Yuki2718 @okiehsch

**Comment by mapx-** [comment]
Did you update unbreak list ?

**Comment by Drawingnearer** [comment]
> Did you update unbreak list ?

Yes, sir, I did.

**Comment by Drawingnearer** [comment]
@Yuki2718 
I'd like to notify you that the same issue also happens with Adguard, as You, sir, are an Adguard filters volunteer.

**Comment by Yuki2718** [comment]
`@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule,domain=eksisozluk.com` is the cause, but this solves another problem https://github.com/uBlockOrigin/uAssets/issues/14464#issuecomment-1221491970

**Comment by Drawingnearer** [comment]
> An alternative will be a bit more specified scriptlet `eksisozluk.com##+js(nostif, wt(), 100)`.
Ok, How do I use this scriptlet then? I tried to add it to "My Filters" but It does not seem to work. I'm not sure but there seems to be a syntax error in it. @Yuki2718

**Comment by MasterKia** [comment]
Did you test in Firefox?
If so, test using Chrome.

**Comment by Drawingnearer** [comment]
> Did you test in Firefox? If so, test using Chromium.

Thank you, Sir. I have just tried it with Chromium and the website works just fine and I didn't even have to use Yuki2718's scriptlet.
Oddly enough though the issue still persists with Firefox.

**Comment by MasterKia** [comment]
@Yuki2718 Can you reproduce issues using Firefox?

**Comment by Drawingnearer** [comment]
@MasterKia @Yuki2718 Thank you all. Yuki2718's removing the rule from filter lists did the trick both for uBlock Origin and for AdGuard. The issue I have reported is now resolved. I appreciate your taking the time to help.
