### ISSUE TITLE
medievalists.net: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14469]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

- `https://www.medievalists.net/`
- `https://www.medievalists.net/2022/08/mongols-silk/`

### Category

ads

### Describe the issue

leftover ad containers:

1. `medievalists.net##.widget:has(.ad-tag)`
2. `medievalists.net###primis_intext`
3. `||img.medievalists.net/wp-content/uploads/2021/03/support-medievalists-on-patreon.png`

### Screenshot(s)

<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/110956608/185774239-d64b63bb-c734-472c-9827-be57354e5b0a.png)

</details>

<details>
<summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/110956608/185774478-229763a6-3b2a-4afc-ba6e-85e2423c467e.png)

</details>

<details>
<summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/110956608/185774581-9b342cfb-76ca-4167-bceb-f6c6b913d669.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82375
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 4h.13m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 4h.13m
    fanboy-cookiemonster: 40297-86, 11h.49m
  default: 
    user-filters: 119-0, never
    ublock-filters: 33232-77, 11h.49m
    ublock-badware: 4263-0, 11h.49m
    ublock-privacy: 247-2, 11h.49m
    ublock-abuse: 76-0, 11h.49m
    ublock-unbreak: 1845-0, 11h.49m
    ublock-quick-fixes: 425-0, 11h.49m
    easylist: 69600-610, 11h.49m
    easyprivacy: 27394-578, 11h.49m
    urlhaus-1: 5443-0, 11h.49m
    plowe-0: 3633-3, 11h.49m
filterset (user): [array of 117 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    medievalists.net: 1
    amazon-adsystem.com: 1
    confiant-integrations.global.ssl.fastly.net: 2
    doubleclick.net: 1
    gravitec.net: 2
    lijit.com: 1
    navdmp.com: 1
```
</details>

**Comment by MasterKia** [comment]
`medievalists.net##.widget:has(.ad-tag)`
`medievalists.net###primis_intext`

@ryanbr EasyList

**Comment by MasterKia** [comment]
@wavygecko The third one is self-promotion (asking for donation/support), not ads.

**Comment by MasterKia** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14432#issuecomment-1220724161

**Comment by MasterKia** [comment]
Yes, https://github.com/uBlockOrigin/uAssets/issues/14432#issuecomment-1220724161
