### ISSUE TITLE
picsart.com many annoyances

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#14460]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://picsart.com`
`https://picsart.com/create`

### Describe the issue

- When visiting `https://picsart.com/create`, the following overlay appears:
![Screenshot 2022-08-20 at 15-12-49 Picsart Editor](https://user-images.githubusercontent.com/52135169/185762830-8c5fc7b0-c0d4-4aae-ac90-bd7834a03714.jpg)

- Every single time I create a new project by pressing the New Project button, I get a welcome tour, even if I've been using Picsart for years:

![Screenshot 2022-08-20 at 15-13-50 Project 14 Picsart Editor](https://user-images.githubusercontent.com/52135169/185762942-9c422fcd-5e1c-47f7-b42b-7c7441f57e5c.jpg)

- Say I got done with a project then export it. After exporting, there's a prompt that asks if I want to create a new project. When I press that, I get the following overlay:

![Screenshot 2022-08-20 at 15-14-42 Project 14 Picsart Editor](https://user-images.githubusercontent.com/52135169/185762905-9e620794-f02f-43b2-a688-fc70b1782a6a.jpg)

- 
 

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103.0.2

### Settings

Default

**Comment by mapx-** [comment]
Test

```
picsart.com##[class^="pa-monetization"]
picsart.com##[class^="hintWrapper"]
```

**Comment by Mennaruuk** [comment]
> Test
> 
> ```
> picsart.com##[class^="pa-monetization"]
> picsart.com##[class^="hintWrapper"]
> ```

Works perfectly. Gone are the headaches!

**Comment by mapx-** [comment]
@ryanbr
