### ISSUE TITLE
bloomberg.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14466]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bloomberg.com/features/2021-hushpuppi-gucci-influencer/`

### Category

ads

### Describe the issue

- leaderboard ad: `##.dvz-v0-ad-top`
- inline content ads: `##.css--ad`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185773253-354b2d3f-5dcd-4770-9d14-8ecd781e2d78.png)

---

![image](https://user-images.githubusercontent.com/110956608/185773298-da6328da-a186-40ff-bb35-ce07a423c661.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82382
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 3h.30m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 3h.30m
    fanboy-cookiemonster: 40297-81, 11h.6m
  default: 
    user-filters: 126-0, never
    ublock-filters: 33232-77, 11h.6m
    ublock-badware: 4263-0, 11h.6m
    ublock-privacy: 247-2, 11h.6m
    ublock-abuse: 76-0, 11h.6m
    ublock-unbreak: 1845-0, 11h.6m
    ublock-quick-fixes: 425-0, 11h.6m
    easylist: 69600-610, 11h.6m
    easyprivacy: 27394-583, 11h.6m
    urlhaus-1: 5443-0, 11h.6m
    plowe-0: 3633-3, 11h.6m
filterset (user): [array of 123 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    bloomberg.com: 1
    adsafeprotected.com: 1
    bbthat.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    indexww.com: 1
    moatads.com: 1
    youborafds01.com: 2
```
</details>

**Comment by MasterKia** [comment]
```
bloomberg.com##[class$="ad-div"] 
bloomberg.com##.css--ad
```

@ryanbr EasyList
