### ISSUE TITLE
dizipal361.com: ads

### ISSUE THREAD

**Issue by CarCo53** [uBlockOrigin/uAssets#14462]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizipal361.com/`

### Category

ads

### Describe the issue

ad ever where

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82649
  cosmetic: 51813
  scriptlet: 18063
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8717-66, 2d.4h.25m
    easylist: 69578-69, 2d.4h.24m
    easyprivacy: 27357-131, 2d.4h.22m
    plowe-0: 3629-777, 7d.1h.22m
    ublock-abuse: 76-0, 7d.1h.20m
    ublock-badware: 4233-92, 2d.4h.21m
    ublock-filters: 32514-130, 2d.4h.20m
    ublock-privacy: 231-3, 2d.4h.19m
    ublock-quick-fixes: 420-37, 2h.12m
    ublock-unbreak: 1839-41, 2d.4h.18m
    urlhaus-1: 5443-0, 2h.11m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 522 ms (selfie)
  maxAssetCacheWait: 410 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 5
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this for the banners:
```
dizipal361.com###page-end.hdd
dizipal361.com##a[target="_blank"][id^="player"]
dizipal361.com##.sidebar section#block-10
```
I've seen ads before the video, but someone else will have to look at that.

**Comment by MasterKia** [comment]
@Yuki2718 AG Turkish.
`dizipal361.com##+js(acis, jQuery, window.open)` for popups.
It has banners and pre-roll ads as well.

**Comment by MasterKia** [comment]
@CarCo53 Force update your filter lists, it's fixed.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
