### ISSUE TITLE
economist.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14465]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.economist.com/`

### Category

ads

### Describe the issue

banner ads (at top of page and in between content sections):

`[class*="adComponent_advert__"]`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185771820-81789ad9-4d9b-441a-8565-38ab38d96f14.png)

---

![image](https://user-images.githubusercontent.com/110956608/185771827-a97c82bd-1f94-48c8-a498-1da10d5e2eda.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82384
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 2h.21m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 2h.21m
    fanboy-cookiemonster: 40297-81, 9h.56m
  default: 
    user-filters: 128-0, never
    ublock-filters: 33232-77, 9h.57m
    ublock-badware: 4263-0, 9h.57m
    ublock-privacy: 247-2, 9h.57m
    ublock-abuse: 76-0, 9h.57m
    ublock-unbreak: 1845-0, 9h.57m
    ublock-quick-fixes: 425-0, 9h.57m
    easylist: 69600-610, 9h.57m
    easyprivacy: 27394-583, 9h.57m
    urlhaus-1: 5443-0, 9h.57m
    plowe-0: 3633-3, 9h.56m
filterset (user): [array of 125 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    economist.com: 3
    cloudflareinsights.com: 2
    doubleclick.net: 1
    google-analytics.com: 1
    moatads.com: 1
    newrelic.com: 1
    parsely.com: 2
    permutive.app: 1
    permutive.com: 1
    qualtrics.com: 1
    taboola.com: 1
    tinypass.com: 2
```
</details>

**Comment by MasterKia** [comment]
`economist.com##[class^="adComponent"]`

@ryanbr EasyList
