### ISSUE TITLE
Source Forge Browsing is not filtered.

### ISSUE THREAD

**Issue by schitty-hub** [uBlockOrigin/uAssets#14461]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`sourceforge.net/directory/` _[...]_

### Describe the issue

It is full of ads. On the top, in between content,  ... . 
Which occur on all of the Websites `Home/Browse/[...]` (Sub-)Directorys, which is also the search results.

As seen in the Picture, Ads are undeniably identifieable by having:

- a colored title;
- an additional column of text in a special color;
- no stars, reviews, downloads, nor last update date.
- Aswell as by a diffent style of Link to the project/ad. Whichs text is either "the Ads Name" or "Learn More" **instead** of "See Project" for **legit listings**.

### Screenshot(s)

![Image](https://user-images.githubusercontent.com/111659325/185765126-ddc134f4-06a0-437f-8e1b-b3e277ffb8c0.png)

### uBlock Origin version

uBlock Origin: 1.43.0

### Browser name and version

Firefox: 99

### Settings

uBlock Origin: 1.43.0
Firefox: 99
filterset (summary): 

-   network: 192446
-   cosmetic: 221616
-   scriptlet: 37860
-   html: 736

listset (total-discarded, last updated): 
**added:** 
- adguard-generic: 67101-5449, 3m
- adguard-mobile: 8155-163, 3m
- adguard-spyware: 26489-917, 3m
- adguard-spyware-url: 720-3, 3m
- block-lan: 43-0, 4m
- curben-phishing: 51595-7, 4m
- curben-pup: 188-0, 4m
- adguard-annoyance: 56546-4990, 3m
- adguard-social: 18234-1070, 3m
- fanboy-thirdparty_social: 68-0, 3m
- fanboy-annoyance: 79695-63829, 3m
- fanboy-cookiemonster: 40295-145, 3m
- fanboy-social: 23297-31, 3m
- ublock-annoyances: 4538-4, 4m
- dpollock-0: 11381-624, 3m
   **default:** 
- user-filters: 778-27, never
- ublock-filters: 33231-97, 5m
- ublock-badware: 4263-0, 5m
- ublock-privacy: 247-0, 5m
- ublock-abuse: 76-0, 5m
- ublock-unbreak: 1849-0, 5m
- ublock-quick-fixes: 418-0, 5m
- easylist: 69600-966, 3m
- easyprivacy: 27394-9832, 3m
- urlhaus-1: 5443-0, 4m
- plowe-0: 3633-143, 3m
- DEU-0: 5905-12, 3m

filterset (user): [array of 778 redacted]
trustedset: 
  removed: 

- about-scheme
- chrome-extension-scheme
- chrome-scheme
- edge-scheme
- moz-extension-scheme
- opera-scheme
- vivaldi-scheme
- wyciwyg-scheme

modifiedUserSettings: 

- autoUpdate: false

modifiedHiddenSettings: [none]
supportStats: 

- allReadyAfter: 5784 ms (selfie)
- maxAssetCacheWait: 1057 ms

### Notes

Tried updating to 1.44 - not available through "about:addons".

The image is redacted for privacy, but NOT altered in any other way.
The image only shows the top ads, not the inline ads, which are the same but with a legit listing above it.

The Settings I pasted is a formated copy of the debug info on the bottom of the support tab in the uBO-Settings.

...
If you need to know more, please let me know.

**Comment by okiehsch** [comment]
@ryanbr 
`sourceforge.net##.can-truncate`

**Comment by okiehsch** [comment]
Just update your filter lists, "bruh".
