### ISSUE TITLE
lithub.com & crimereads.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14468]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

- `https://lithub.com/`
- `https://lithub.com/the-making-of-a-muse-when-edie-sedgwick-met-andy-warhol/`
- `https://crimereads.com/`
- `https://crimereads.com/lost-history-americas-traveling-ghost-shows/`

### Category

ads

### Describe the issue

Literary Hub and CrimeReads are run by the same group & share some code. There are unblocked ad containers that can be blocked with:

1. `lithub.com##.header-ad-leaderboard`
2. `lithub.com,crimereads.com##.code-block:has(> [class*="pubg-"])`
3. `lithub.com,crimereads.com##.ai_widget`
4. `crimereads.com##[class*="ai-viewport-"]`

### Screenshot(s)

<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/110956608/185773710-ef9bee03-aff8-45c9-ba46-edbfb2d84e54.png)

</details>

<details>
<summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/110956608/185773764-075de811-762d-4df9-a623-bf82b477bb41.png)

---

![image](https://user-images.githubusercontent.com/110956608/185774113-de8df628-f90c-4d76-a8a4-9c970cccccbe.png)

---

![image](https://user-images.githubusercontent.com/110956608/185774129-a62d5951-264d-4a4b-842c-1042babc5da0.png)

---

![image](https://user-images.githubusercontent.com/110956608/185774072-acc29937-1927-496c-949c-2cb7eae486db.png)

</details>

<details>
<summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/110956608/185773796-c487e9b4-8864-40fa-be84-618f64b61187.png)

---

![image](https://user-images.githubusercontent.com/110956608/185774186-caa9e960-fe35-4cca-9f43-ef97bf08b36d.png)

</details>

<details>
<summary>Screenshot 4</summary>

![image](https://user-images.githubusercontent.com/110956608/185774036-16162158-98be-4009-924a-0f2e720f52bf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82375
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 3h.51m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 3h.51m
    fanboy-cookiemonster: 40297-98, 11h.26m
  default: 
    user-filters: 119-0, never
    ublock-filters: 33232-65, 11h.26m
    ublock-badware: 4263-0, 11h.26m
    ublock-privacy: 247-2, 11h.26m
    ublock-abuse: 76-0, 11h.26m
    ublock-unbreak: 1845-0, 11h.26m
    ublock-quick-fixes: 425-0, 11h.26m
    easylist: 69600-610, 11h.26m
    easyprivacy: 27394-578, 11h.26m
    urlhaus-1: 5443-0, 11h.26m
    plowe-0: 3633-3, 11h.26m
filterset (user): [array of 119 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    doubleclick.net: 1
    doubleverify.com: 2
    enormousearth.com: 2
    google-analytics.com: 1
    krxd.net: 1
    myfonts.net: 1
    newrelic.com: 1
    omappapi.com: 4
    pbxai.com: 2
    pubgenius.io: 2
    quantserve.com: 1
    sail-horizon.com: 2
    wp.com: 2
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr 
@wavygecko Can you please report to EL if an issue doesn't require extended syntax?

**Comment by MasterKia** [comment]
> convenient

@wavygecko Issues directly reported to EL usually get fixed pretty quickly.
