### ISSUE TITLE
currentaffairs.org: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14467]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.currentaffairs.org/2022/08/if-we-want-humanity-to-survive-we-must-cooperate-with-china`

### Category

ads

### Describe the issue

big inline ad: `currentaffairs.org##.wp-block-image:has(> a[href$="/subscribe"])`

(note: sometimes link uses `www.` & other times no `www.` hence the `$="/subscribe"` attr selector)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185773533-36d7fedb-7f0b-4af3-b52c-505099f74070.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82381
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 3h.44m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 3h.44m
    fanboy-cookiemonster: 40297-93, 11h.20m
  default: 
    user-filters: 125-0, never
    ublock-filters: 33232-65, 11h.20m
    ublock-badware: 4263-0, 11h.20m
    ublock-privacy: 247-2, 11h.20m
    ublock-abuse: 76-0, 11h.20m
    ublock-unbreak: 1845-0, 11h.20m
    ublock-quick-fixes: 425-0, 11h.20m
    easylist: 69600-610, 11h.20m
    easyprivacy: 27394-583, 11h.20m
    urlhaus-1: 5443-0, 11h.20m
    plowe-0: 3633-3, 11h.20m
filterset (user): [array of 122 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by MasterKia** [comment]
This is self-promotion (_subscribe, donate_), not ads.
```
https://images.currentaffairs.org/2021/10/printad-scaled-1-1261x2048-1-631x1024.jpg
https://images.currentaffairs.org/2022/08/Screen-Shot-2022-08-08-at-10.05.55-AM-1-1024x904.jpg
```

**Comment by MasterKia** [comment]
It can be combined with [your filters](https://github.com/uBlockOrigin/uAssets/issues/14467#issue-1345371143):
```
currentaffairs.org##.wp-block-image:has(> a[href$="/subscribe"]):style(max-width: 30% !important; margin-inline: auto !important;)
currentaffairs.org##.wp-block-image:has(> a[href$="/donate"]):style(max-width: 40% !important; margin-inline: auto !important;)
```

**Comment by okiehsch** [comment]
I am against starting to make self advertisement smaller in our annoyance list. Where do we start and what size is "acceptable".
As long as it is not a full page overlay we should leave it alone, we can post a filter here and the user can decide what to do.

**Comment by MasterKia** [comment]
> starting to make self advertisement smaller in our annoyance list

We're not _starting_ to make **_every_** self-promotion smaller.
This self-promotion in particular disrupts the user experience.

**Comment by MasterKia** [comment]
> a full page overlay

This looks like a full page overlay to me, it's just missing a background blur.
![Screenshot_20220821_104651](https://user-images.githubusercontent.com/17685483/185778267-b3c4b75e-7ee6-4896-a2e2-90d5df430aa6.png)

**Comment by ghajini** [comment]
**content is available**, this is just an overlay, if you go on addressing self promotion, list is more

**Comment by MasterKia** [comment]
> if you **_go on_** addressing self promotion, list is more

No one is going on a rampage to address every self-promotion on the planet.

**Comment by okiehsch** [comment]
> This looks like a full page overlay to me, it's just missing a background blur and a close (X) button.

It's in the middle of a rather lengthy article, it's not a full page overlay to me and that's the point what you consider "to big" is completely subjective.

**Comment by MasterKia** [comment]
Ok, now I understand; sorry for the lengthy discussion.

> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by EasyList/EasyPrivacy policies

Then I guess EasyList fixing snowflakes in the annoyances list doesn't qualify as completely subjective.

https://github.com/uBlockOrigin/uAssets/issues/4704
https://github.com/easylist/easylist/commit/f2c56c6ae6093d14ea8be681dec75217ec3bd6aa

**Comment by okiehsch** [comment]
> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by EasyList/EasyPrivacy policies

That does not cover annoyances, the readme is only meant to clarify our policies in regards to ads.
I am pretty sure that when that part was written we didn't even have an annoyance list, that was added much later.
