### ISSUE TITLE
tf1.fr: detection

### ISSUE THREAD

**Issue by claudemontreal** [uBlockOrigin/uAssets#14473]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tf1.fr/tf1/the-voice-kids/videos/the-voice-kids-2022-louison-chante-carmen-de-stromae-audition-a-laveugle-99894538.html`

### Category

detection

### Describe the issue

Says it detected an ad blocker and to disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 103
filterset (summary): 
  network: 115141
  cosmetic: 131267
  scriptlet: 24912
  html: 738
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 56543-5082, 1d.10h.45m
    adguard-social: 18234-1654, 1d.10h.46m
    fanboy-thirdparty_social: 69-1, 1d.46m
    fanboy-annoyance: 79695-67915, 1d.44m
    fanboy-cookiemonster: 40297-16874, 1d.45m
    fanboy-social: 23293-13680, 1d.10h.44m
    ublock-annoyances: 4558-7, 1d.10h.38m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33336-345, 12h.5m
    ublock-badware: 4262-0, 11h.57m
    ublock-privacy: 247-1, 8d.2h.41m
    ublock-abuse: 76-0, 8d.2h.40m
    ublock-unbreak: 1854-0, 11h.48m
    ublock-quick-fixes: 415-0, 13h.57m
    adguard-mobile: 8157-169, 10h.20m
    easylist: 69597-25234, 1d.18h.27m
    easyprivacy: 27394-593, 11h.47m
    urlhaus-1: 5443-0, 13h.56m
    plowe-0: 3630-3, 7d.12h.32m
    FRA-0: 30469-3728, 10h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1838 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    facebook.net: 1
    facil-iti.app: 1
    sentry-cdn.com: 1
```
</details>

**Comment by Yuki2718** [comment]
> * I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

**Comment by Yuki2718** [comment]
Okay I can reproduce only if ETP is set to strict.

**Comment by Yuki2718** [comment]
`tf1.fr##+js(no-fetch-if, adsafeprotected)` should fix this, but why is it limited to Chrome?

**Comment by uBlock-user** [comment]
I don't know why. It was like that before that commit too.

**Comment by Yuki2718** [comment]
All right, fine unless there's a problem.
