### ISSUE TITLE
manganoon.com: detection

### ISSUE THREAD

**Issue by BlackSoull** [uBlockOrigin/uAssets#14478]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manganoon.com/`

### Category

detection

### Describe the issue

It detect uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 105
filterset (summary): 
  network: 82669
  cosmetic: 27139
  scriptlet: 17707
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8157-28, 9h.39m
    easylist: 69601-24674, 9h.38m
    easyprivacy: 27395-137, 8h.3m
    plowe-0: 3629-864, 8d.11h.30m
    ublock-abuse: 76-0, 8d.11h.28m
    ublock-badware: 4258-92, 8h.2m
    ublock-filters: 32645-394, 8h.1m
    ublock-privacy: 231-4, 8h
    ublock-quick-fixes: 404-29, 7h.49m
    ublock-unbreak: 1841-43, 7h.51m
    urlhaus-1: 5709-0, 7h.50m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1145 ms (selfie)
  maxAssetCacheWait: 476 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Maybe it's mobile only, I can't reproduce on a desktop.

**Comment by BlackSoull** [comment]
Yes it's mobile I'm using kiwi browser

**Comment by BlackSoull** [comment]
Yes it's mobile I'm using kiwi browser

**Comment by MasterKia** [comment]
AFAIK Kiwi browser doesn't work well with uBlock Origin, please try with Firefox Mobile (it supports uBlock Origin).

**Comment by BlackSoull** [comment]
Yes it does work with Firefox

**Comment by BlackSoull** [comment]
Thanks
