### ISSUE TITLE
[nsfw] koushoku.org: ads+detection

### ISSUE THREAD

**Issue by Ech0Sierra** [uBlockOrigin/uAssets#14477]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://koushoku.org/`

### Category

ads

### Describe the issue

Placeholder images load as banners at top and bottom, then get replaced with large NSFW geolocating banner ads. Site also again blocks loading main content when uBO enabled identically to issue #14437 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 104
filterset (summary): 
  network: 81199
  cosmetic: 20795
  scriptlet: 17687
  html: 731
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 33344-297, 6m
    ublock-badware: 4262-0, 6m
    ublock-privacy: 248-1, 6m
    ublock-abuse: 76-0, 6m
    ublock-unbreak: 1855-0, 6m
    easylist: 69604-25028, 6m
    easyprivacy: 27396-580, 6m
    urlhaus-1: 5688-0, 6m
    plowe-0: 3633-3, 6m
    ublock-quick-fixes: 384-0, 6m
filterset (user): [empty]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9705 ms (selfie)
  maxAssetCacheWait: 2914 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    realsrv.com: 5
```
</details>

**Comment by Procyon-b** [comment]
Try these filters:
```
koushoku.org##body > div[class]:style(position:absolute; top: -500px;)
||realsrv.com^$xhr,redirect-rule=noop.txt,domain=koushoku.org
||afcdn.net^$media,domain=koushoku.org
```

**Comment by Ech0Sierra** [comment]
Ads are now blocked successfully with the filter suggestion but an
identical content loading problem from the referenced issue #14437 persists.

**Comment by Procyon-b** [comment]
It should work with 4th filter:
```
@@||koushoku.org^$ghide
```

**Comment by Procyon-b** [comment]
@mapx-  With the filter `koushoku.org##body > div[class]:style(position:absolute; top: -500px;)` I move the top and bottom banners out of the way (I can't just hide them because it prevents the loading of the fullsize image).

**Comment by Patient6038** [comment]
I tried those filters and the main content isnt loading.

**Comment by okiehsch** [comment]
@Yuki2718 you can reproduce?

It works for me,
![image](https://user-images.githubusercontent.com/16838044/185988472-1fb08c35-abed-4174-9b8a-5e227f8c329f.png)
`https://koushoku.org/archive/9494/dream-application-2/4`

**Comment by Yuki2718** [comment]
I could reproduce, but going to bed.

**Comment by okiehsch** [comment]
Good night.

**Comment by mapx-** [comment]
It seems they were breaking the site (on the detail / story page) even disabling uBO

**Comment by okiehsch** [comment]
Right now it's sometimes broken sometimes it works even if I disable uBO on my end.

> Does not work for me, also breaks page before main content 
`https://koushoku.org/archive/9335/the-tale-of-a-decent-female-adventurer-getting-lost-inside-an-erotic-trap-dungeon-character-file-qa-1`

That site works fine on my end with up to date filter lists.

**Comment by coolkid3245** [comment]
Updated filter lists and no custom filter still breaks site, ads does not load leaving an empty banner on preview page,

`https://koushoku.org/archive/9335/the-tale-of-a-decent-female-adventurer-getting-lost-inside-an-erotic-trap-dungeon-character-file-qa-1`
<details>

![image](https://user-images.githubusercontent.com/24840466/186100896-2e58f85b-9e90-42f0-8359-40b9df5ded69.png)
</details>

But placeholder image loads on main page
`https://koushoku.org/archive/9335/the-tale-of-a-decent-female-adventurer-getting-lost-inside-an-erotic-trap-dungeon-character-file-qa-1/3`

Navigation is also broken as in issue #14477
<details>

![image](https://user-images.githubusercontent.com/24840466/186103170-b2316ffd-3e71-4698-9f0d-ce397af09369.png)</details>

<details>
<summary>Configuration</summary>

```uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80175
  cosmetic: 44720
  scriptlet: 17688
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68991-51, 4m
    easyprivacy: 27405-126, 4m
    plowe-0: 3633-776, 4m
    ublock-abuse: 76-0, 4m
    ublock-badware: 4214-92, 4m
    ublock-filters: 32510-122, 4m
    ublock-privacy: 241-3, 4m
    ublock-quick-fixes: 383-0, 4m
    ublock-unbreak: 1838-41, 4m
    urlhaus-1: 4670-0, 4m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 273 ms
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    afcdn.net: 6
    realsrv.com: 7```

</details>

**Comment by mapx-** [comment]
Disabling uBO I get no content here (only the ads)

`https://koushoku.org/archive/9335/the-tale-of-a-decent-female-adventurer-getting-lost-inside-an-erotic-trap-dungeon-character-file-qa-1/3`

**Comment by Yuki2718** [comment]
Same, broken even with uBO disabled. Yesterday I could see contents if disabled.

**Comment by garry-ut99** [comment]
Same here, even with uBO disabled, gallery images sometimes shows up and sometimes not.

**Comment by ghajini** [comment]
if that's case then exception filters can be removed

**Comment by Patient6038** [comment]
gallery images load for me with ublock disabled.

**Comment by Yuki2718** [comment]
Yeah, now loads if disabled.

**Comment by garry-ut99** [comment]
This odd issue is two-faced:
- one thing is that the breakage occurs sometimes even with uBO turned off
- apart of that, the another/separate reason of the breakage are uBO filters itself too, the current fix should be further supplemented by another exceptions (or by removing the offending filters):
   -  `koushoku.org#@#video:upward([style])`
   - `@@||s3t3d2y8.afcdn.net/library/*$media,image,domain=koushoku.org`
   - optionally `@@||koushoku.org^$ghide` can be replaced by:
      - `#@#.exo-native-widget-outer-container`
      - `#@#.exo-native-widget`

**Comment by garry-ut99** [comment]
Yes, after the above commit, the breakage is gone (the one caused by filters).

**Comment by Yuki2718** [comment]
I'll keep this opened for a while. They may counter again.

**Comment by Yuki2718** [comment]
On firefox unable to move to next image, don't know why.

**Comment by garry-ut99** [comment]
Not fixed, I'm unable to move to the next image too, the last commit is messing with `.exo-native-widget` which is breaking the gallery, I mean that messing/hiding DOMs with `exo` causes gallery breakage, like I described in [my previous comment](https://github.com/uBlockOrigin/uAssets/issues/14477#issuecomment-1224280805) (see the `ghide` replacement whitelists, all of them contains `exo`).

**Comment by Yuki2718** [comment]
Maybe `koushoku.org##+js(aeld, click, bypassEventsInProxies)` if it doesn't have side effect. No other problem.

**Comment by Ech0Sierra** [comment]
Is the standing procedure here to continue rewriting filters as needed for
a site engaging in active countermeasure development? I don't want to
unnecessarily distract the devs from higher priority work and can close
this if it's going to turn into whack-a-mole.

**Comment by MasterKia** [comment]
They'll eventually come around.

**Comment by UndergroundSol** [comment]
To apply these fixes, do I 
1: Purge caches and update "Filter Lists" **or** 
2: Manually add custom filters in "My Filters"

I did 1, but it's not working.

**Comment by MasterKia** [comment]
1 should be enough.
If it's not working then maybe they patched this filter.

> which filters do I need to add
`koushoku.org##div[style^="zoom"]:watch-attr(src):has(img[src]):upward(html) .exo-native-widget,div[style*="250px"],div[style*="728px"],video`

**Comment by Yuki2718** [comment]
Please precisely describe what is not "working". I see some ads unbloked and will fix. But remember they're watching us so *any* fix won't last long enough.

**Comment by UndergroundSol** [comment]
Right now, when I turn off ublock, ads load fully, but gallery images do not load and gallery navigation by clicking the page or using side arrows does not work. 
![image](https://user-images.githubusercontent.com/111994242/186718389-3081de4d-ba6f-4a6a-b2b9-e5b740b8d6bb.png)

When I turn on ublock, everything is the same, except ads only partially load (ad images do not load but ad text does load. Gallery images and navigation remain similarly broken. 
![image](https://user-images.githubusercontent.com/111994242/186718920-8da3e248-95b3-4f34-a0a3-c134bdfe5e53.png)

I currently do not have any custom filters for koushoku in "My Filters". I did purge caches and update "Filter Lists".
Thanks for your help.

**Comment by Yuki2718** [comment]
@gorhill matches-path doesn't support look ahead, so how to apply a filter except for /archive path (actually more specified regex should be used but as an example)? Tried
```
koushoku.org#@#:matches-path(/(?!archive).*/) div[style*="250px"],div[style*="728px"]
koushoku.org##div[style*="250px"],div[style*="728px"]
```
without sucess.

**Comment by Yuki2718** [comment]
@UndergroundSol As you said on Firefox images doesn't load even with uBO turned off, but I see images on Chrome.

**Comment by UndergroundSol** [comment]
I've been getting no images on Chrome. However, now it looks like the site broke further. Currently just getting a white screen with and without ublock turned on.

**Comment by Yuki2718** [comment]
Yes, now broken on Chrome too.

**Comment by Patient6038** [comment]
He might be IP banning now? I had the same white screen issue. Disabled ublock on that site and still had it. So I purged all caches, removed the site cookies, kept ublock disabled, and still got the issue. Then (with ublock still disabled) I used a vpn, it immediately loads. But as soon as I used what Yuki posted, it immediately went back to the white screen, and even when it was disabled I still got the issue.

**Comment by coolkid3245** [comment]
+1 on probable IP banning, only getting white screen but changing connections fixed it.

**Comment by Yuki2718** [comment]
The site is desperate to counter us.

**Comment by Yuki2718** [comment]
To me reminder of avgle who also started banning IP at the time:
`https://forums.lanik.us/viewtopic.php?t=39393-nsfw-avgle-com&start=30`
`https://github.com/NanoAdblocker/NanoFilters/issues/215`

**Comment by gorhill** [comment]
> how to apply a filter except for /archive path

Use `:not:matches-path(/archive)`?

**Comment by garry-ut99** [comment]
Ads are back again and gallery is broken again...

**Comment by Yuki2718** [comment]
Broken even though uBO is turned off from the beginning with a new IP. Nothing to fix except for missed ads.

**Comment by garry-ut99** [comment]
It's not broken for me when uBO is turned off, regardless of using same or new ip. Once I enable uBO back,  the gallery is broken again.

**Comment by Yuki2718** [comment]
Yes now recovered. And IDK what they detects, even allowing everything doesn't work.
@gorhill Somehow they bypass matches-path. On `https://koushoku.org/archive/9506/chilled` `koushoku.org##.exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]` works but `koushoku.org##:matches-path(/archive) .exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]` doesn't.

**Comment by gorhill** [comment]
This is difficult to debug, but I suspect the page removes the random attributes uBO uses on the elements to hide when enforcing procedural operators -- the elements matching the filter do not have uBO's assigned attributes.

**Comment by gorhill** [comment]
How about:

    koushoku.org##:matches-path(/^\/(archive\/\d+\/[-a-z]+)?$/) .exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]:remove()
    koushoku.org##+js(nostif, ()=>o())

**Comment by Yuki2718** [comment]
Working fine

**Comment by UndergroundSol** [comment]
Currently, every page displays black screen with text "Adblocker detected" as in image below.

https://user-images.githubusercontent.com/111994242/187054938-db88d623-b595-4706-9de6-9dc9f92d8d54.png

**Comment by Yuki2718** [comment]
And if I reload the page this message:
> You have been temporarily banned. Warning 1 out of 10

**Comment by JobcenterTycoon** [comment]
Ok i have working filter without ban, without breakage and with adblocking:

<details>
<summary> useful filters </summary>

```
koushoku.org#@#.exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]:style(filter:opacity(0%)!important;pointer-events:none!important)
koushoku.org#@#:matches-path(/^\/(archive\/\d+\/[-a-z]+)?$/) .exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]:remove()
koushoku.org#@#+js(nostif, ()=>o())

koushoku.org##+js(no-xhr-if, cimp)
||afcdn.net^$image,redirect=32x32.png,domain=koushoku.org
koushoku.org##.exo-native-widget-outer-container:style(clip-path: circle(0%);)
koushoku.org##video[loop][muted][autoplay][width="300px"][height="250px"]:style(clip-path: circle(0%);)
```
</details>

**Comment by Patient6038** [comment]
> Ok i have working filter without ban, without breakage and with adblocking:


Doesnt work on my end, adblock detected with it on

**Comment by JobcenterTycoon** [comment]
Because the admins are here

**Comment by UndergroundSol** [comment]
For someone who is new to coding, how are you guys coming up with these filters that work (until the admin checks this page and counters)? What knowledge/skills are required? I want to try a solution for myself but I don't know where to start.

**Comment by Yuki2718** [comment]
@UndergroundSol That should be asked in reddit or in Discussion.

**Comment by UndergroundSol** [comment]
Why am I still getting blocked even when I disable uBlock on Koushoku? All the ads are still loading, but the individual gallery pages won't load and I also got a temp ban.
