### ISSUE TITLE
theguardian.com: breakage

### ISSUE THREAD

**Issue by R3dXIII** [uBlockOrigin/uAssets#14472]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theguardian.com/world/2022/aug/20/crimeas-civilians-sound-alarm-after-ukrainian-drone-hits-russian-fleet-hq`

### Category

breakage

### Describe the issue

Video does not play.  Privacy badger disabled. 
Phone is oneplus n10 5g, android 11.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220821-093755](https://user-images.githubusercontent.com/4928684/185782983-8c2f24b8-08e5-4137-80cf-c60b195504ec.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 103
filterset (summary): 
  network: 82258
  cosmetic: 26958
  scriptlet: 17586
  html: 728
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33337-311, 1d.17m
    ublock-badware: 4236-0, 4d.4h.29m
    ublock-privacy: 247-1, 12d.10h.44m
    ublock-abuse: 76-0, 9d.23h.21m
    ublock-unbreak: 1876-0, 4d.5h.5m
    adguard-mobile: 8142-169, 4d.6h.1m
    easylist: 69600-25168, 1d.18m
    easyprivacy: 27348-590, 4d.5h.32m
    urlhaus-1: 5443-0, 14h.58m
    plowe-0: 3634-3, 12d.10h.45m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3079 ms (selfie)
  maxAssetCacheWait: 1837 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    theguardian.com: 16
    confiant-integrations.global.ssl.fastly.net: 1
```
</details>

**Comment by Yuki2718** [comment]
Have you accepted cookie compliance?

**Comment by R3dXIII** [comment]
> 

I just copied it to a private tab. There was no cookie warning and the result was the same.

**Comment by MasterKia** [comment]
@R3dXIII Does the video play with uBlock Origin off?

Also are you running a DNS blocker that blocks ads/trackers?

**Comment by Yuki2718** [comment]
This again is a ETP issue. I seriously have to un-recommend ETP, it has been causing tooooo many problems with very limited benefit to uBO user.

**Comment by R3dXIII** [comment]
> @R3dXIII Does the video play with uBlock Origin off?
> 
> Also are you running a DNS blocker that blocks ads/trackers?

No it doesn't. No DNS blocker.

**Comment by MasterKia** [comment]
@R3dXIII Does the video play if you turn off Firefox Enhanced Tracking Protection?

**Comment by Yuki2718** [comment]
On my end the video doesn't play by Firefox ETP even with uBO turned off.

**Comment by R3dXIII** [comment]
> This again is an ETP issue. I seriously have to un-recommend ETP, it has been causing tooooo many problems with very limited benefit to uBO user.

Confirmed, with ETP off it works fine.

**Comment by MasterKia** [comment]
> I seriously have to un-recommend ETP, it has been causing tooooo many problems with very limited benefit to uBO user.

> - [X] I can reproduce the problem with Firefox Enhanced Tracking Protection disabled 

Maybe this prerequisite?

**Comment by R3dXIII** [comment]
Thanks for the support.

**Comment by Yuki2718** [comment]
> Maybe this prerequisite?

I don't know, by default enabled only in Private tab.

> Thanks for the support.

You're welcome!

**Comment by MasterKia** [comment]
> by default enabled only in Private tab

I'm pretty sure ETP is enabled out-of-the-box after installation for all tabs.

**Comment by Yuki2718** [comment]
You're right, enabled by default now. If it's by default, I think we should not require user to turn it off before reporting.

**Comment by MasterKia** [comment]
> If it's default-enabled, I think we should ~not~ require user to turn it off before reporting.

Because as you said "_ETP causes tooooo many problems with very limited benefit to uBO user._"

ETP on default (standard) mode provides no benefits that uBO can't provide.
The only benefit it has is blocking cross-tracking cookies.
uBO can prevent tracking scripts that set those cookies.
So ETP standard doesn't provide anything useful imo.

Personally I just set it to block all third-party cookies.

**Comment by Yuki2718** [comment]
ETP blocks tracker on privileged page where uBO doesn't run.

**Comment by MasterKia** [comment]
> on privileged page

Only Mozilla pages are privileged.

https://github.com/gorhill/uBlock/wiki/Privileged-Pages

**Comment by MasterKia** [comment]
> It will be too much for average user to change and test that before reporting.


As easy as clicking a button ;)

![IMG_20220821_202924](https://user-images.githubusercontent.com/17685483/185799975-4f6b72ac-cc46-452a-8aae-289d1dca1df2.jpg)

**Comment by Yuki2718** [comment]
I can't find the post but I though @gwarser spotted something on PP.

> As easy as clicking a button ;)

Tha't not really easy to vast majority of user actually.

**Comment by MasterKia** [comment]
All the user has to do is "click on the lock icon in address bar"
I bet it's easier than doing this:
> I forced an update of my filter lists (how to do this: click "Purge all caches", then click "Update now")

**Comment by Yuki2718** [comment]
Well the conversation here is going off-topic, we should move to internal discussion.

**Comment by MasterKia** [comment]
Ok.

**Comment by MasterKia** [comment]
@R3dXIII Were you using Private tabs the whole time or did you set ETP to "Strict"?

**Comment by R3dXIII** [comment]
> @R3dXIII Were you using Private tabs the whole time or did you set ETP to "Strict"?

ETP was already enabled, I think it was on Standard. The issue is sorted out for me now.

**Comment by nqlp** [comment]
I have this huge cookie banner:

<img width="1440" height="657" alt="Image" src="https://github.com/user-attachments/assets/0201b88d-a8e6-48a6-974b-0aeffbc47f57" />

My troubleshooting information:

<details>

```yaml
uBlock Origin: 1.67.0
Chromium: 142
filterset (summary):
 network: 182974
 cosmetic: 166221
 scriptlet: 44193
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 36162-75, now
  ublock-cookies-adguard: 5247-69, now
  fanboy-cookiemonster: 45887-3677, now
  ublock-cookies-easylist: 5247-5247, now
  adguard-popup-overlays: 29105-300, now
  adguard-mobile-app-banners: 6493-430, now
  adguard-other-annoyances: 15244-204, now
  easylist-annoyances: 5023-471, now
  easylist-notifications: 2426-9, now
  ublock-annoyances: 4713-149, now
  FRA-0: 19402-278, now
  ublock-experimental: 4-0, now
 default:
  user-filters: 22-0, never
  ublock-filters: 41886-72, now
  ublock-badware: 10574-31, now
  ublock-privacy: 3563-4, now
  ublock-unbreak: 2709-1, now
  ublock-quick-fixes: 410-10, now
  easylist: 82827-508, now
  easyprivacy: 54897-756, now
  urlhaus-1: 30925-5, now
  plowe-0: 3474-0, now
filterset (user): [array of 22 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1509 ms
 maxAssetCacheWait: 522 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  theguardian.com: 12
  guardianapis.com: 1
  guim.co.uk: 1
 extended:
  ##.top-banner-ad-container
  ##.ad-slot-container
  ##.js-ad-slot
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.ad-slot--top-above-nav
  ##.ad-slot--mpu-banner-ad
  ##.ad-slot--rendered
  ##.ad-slot--right
  ##.ad-slot--mostpop
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  ##[name="StickyBottomBanner"]
  ##[name="SlotBodyEnd"]
  ###maincontent #sign-in-gate
  ##div[id^="dfp-ad-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by nqlp** [comment]
> Which country are you when accessing the site?

Canada
