### ISSUE TITLE
starve.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1447]
### URL(s) where the issue occurs
`http://starve.io`

### Describe the issue
Displays an anti-adblock message.

### Screenshot(s)
![starve io anti-adblock](https://user-images.githubusercontent.com/29117662/35722757-640d0d16-07ac-11e8-9603-72c4e28beee4.PNG)

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.14.25.101 (Nano Adblocker 1.0.0.28) 

### Settings
Default.

### Notes
Anti-adblock.

**Comment by Awazonn** [comment]
try use another ad blocker
