### ISSUE TITLE
albumoftheyear.org: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14470]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.albumoftheyear.org/discover/`

### Category

ads

### Describe the issue

ad container at bottom of page (also appears in the middle of the page on some urls):

`albumoftheyear.org##div:has(> .adHeading)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/185774834-4f6e265c-9fd2-4899-a72a-3fad63466932.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82368
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 4h.38m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 4h.38m
    fanboy-cookiemonster: 40297-86, 12h.13m
  default: 
    user-filters: 112-0, never
    ublock-filters: 33232-77, 12h.14m
    ublock-badware: 4263-0, 12h.14m
    ublock-privacy: 247-2, 12h.14m
    ublock-abuse: 76-0, 12h.14m
    ublock-unbreak: 1845-0, 12h.14m
    ublock-quick-fixes: 425-0, 12h.14m
    easylist: 69600-610, 12h.14m
    easyprivacy: 27394-578, 12h.14m
    urlhaus-1: 5443-0, 12h.14m
    plowe-0: 3633-3, 12h.14m
filterset (user): [array of 111 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    btloader.com: 2
    cloudflareinsights.com: 2
    consensu.org: 1
    googletagmanager.com: 1
    intergient.com: 1
```
</details>

**Comment by mapx-** [comment]
IT should be fixed by the same EL @ryanbr
