### ISSUE TITLE
musescore.com: nuisance

### ISSUE THREAD

**Issue by moviemanic** [uBlockOrigin/uAssets#14476]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://musescore.com/`

### Category

nuisance

### Describe the issue

"Please Rate This Score" popup cannot be removed from any music score pages. The message will reappear after each page refresh. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80930
  cosmetic: 45383
  scriptlet: 17669
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    easylist: 69599-51, 1d.10h.15m
    easyprivacy: 27394-126, 1d.10h.14m
    plowe-0: 3630-777, 5d.21h.27m
    ublock-abuse: 76-0, 6d.2h.25m
    ublock-badware: 4233-92, 1d.10h.13m
    ublock-filters: 32535-122, 1d.10h.12m
    ublock-privacy: 231-3, 6d.2h.24m
    ublock-quick-fixes: 420-37, 20h.33m
    ublock-unbreak: 1829-41, 1d.10h.11m
    urlhaus-1: 5443-0, 20h.34m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 317 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 15
  no-popups: true
  blockedDetails: 
    musescore.com: 8
    google-analytics.com: 2
    sentry.io: 2
    ultimate-guitar.com: 1
    yandex.com: 2
```
</details>

**Comment by MasterKia** [comment]
For me the "Please rate this score" isn't a popup and surely isn't an annoyance.
Please provide screenshot of the popup.

**Comment by moviemanic** [comment]
Hmm interesting, it seems to only appear on scores that you have favorited, and will not stop appearing even if you have previously rated the score in question. My apologies, I didn't realize that the pop-up didn't appear when viewing scores that aren't in your favorites.  The image below is the most I'm able to successfully block: 

<img width="1333" alt="Screen Shot 2022-08-21 at 12 09 43 PM" src="https://user-images.githubusercontent.com/16908079/185800450-cdad49dd-ff98-4d8b-ab00-408bceb441d4.png">

And this is the popup with no blocking enabled (I'm shown my previous 5 star rating here): 
<img width="1337" alt="Screen Shot 2022-08-21 at 12 13 33 PM" src="https://user-images.githubusercontent.com/16908079/185800556-e7f16b36-7f56-41da-a38d-d5fdfc97a68b.png">

Each time the page refreshes the element picker reads the popup differently, even on the same score. 
For example from three consecutive page refreshes of the same score the element shows: 
###wWkc7aiUIwsFwGcDdkVNU-title.G26v7
###\31 WyYjXX0azgIAxRMjxB3l-title.G26v7
###bTUnzAuPwHzkxwrt9U_To-title.G26v7

**Comment by MasterKia** [comment]
> and will not stop appearing even if you have previously rated the score in question

Then it's a site issue, can you try contacting site support and telling them about this?

**Comment by moviemanic** [comment]
Just sent their support line an email. I'll provide any updates here if they respond.
