### ISSUE TITLE
courseclub.me: detection

### ISSUE THREAD

**Issue by itsramesh** [uBlockOrigin/uAssets#14489]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://courseclub.me/academyzerotomastery-rust-programming-the-complete-developers-guide/`

### Category

detection

### Describe the issue

Site Finds Ad block detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 81224
  cosmetic: 45420
  scriptlet: 17667
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69632-51, 4h.25m
    easyprivacy: 27402-126, 4h.24m
    plowe-0: 3629-776, 9d.20h.54m
    ublock-abuse: 76-0, 9d.20h.52m
    ublock-badware: 4259-92, 4h.23m
    ublock-filters: 32546-122, 4h.22m
    ublock-privacy: 231-3, 4h.21m
    ublock-quick-fixes: 404-29, 8h.27m
    ublock-unbreak: 1830-41, 4h.20m
    urlhaus-1: 5708-0, 8h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 478 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googlesyndication.com: 4
    googletagmanager.com: 1
    onesignal.com: 1
    wp.com: 1
```
</details>

**Comment by AntiAdvert** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134507
