### ISSUE TITLE
mobi2c.com [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#14481]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mobi2c.com/samsung-m22-phone-review/`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![mobi2c](https://user-images.githubusercontent.com/29841633/185812443-87b99838-ea5a-4db3-af7d-36fd1ce345ea.png)

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 103.0.2

### Settings

Default Settings

### Notes

None

**Comment by MasterKia** [comment]
I can't reproduce.

[Force update](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) your filter lists and ensure you're using only the default lists, then test again.

**Comment by mapx-** [comment]
provide the original page redirecting you to this page
