### ISSUE TITLE
88hd.com: breakage

### ISSUE THREAD

**Issue by masktao** [uBlockOrigin/uAssets#14482]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.88hd.com/vod-play-id-207237-src-1-num-1.html`
can't play movies, if blockad

### Category

breakage

### Describe the issue

if blockad ,can't play movies
alway loading...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 102
filterset (summary): 
  network: 99553
  cosmetic: 55674
  scriptlet: 17801
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    CHN-0: 28856-89, 3m
    easylist: 69631-74, 1m
    easyprivacy: 27402-150, 1m
    plowe-0: 3633-778, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4259-92, 1m
    ublock-filters: 32546-141, 1m
    ublock-privacy: 232-3, 1m
    ublock-quick-fixes: 382-0, 1m
    ublock-unbreak: 1837-42, 1m
    urlhaus-1: 5708-0, 1m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1738 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    88hd.com: 2
    sohu.com: 1
```
</details>

**Comment by garry-ut99** [comment]
EasyPrivacy and AdGuard Tracking Protection lists causing it, the solution:
`@@||pv.sohu.com/cityjson?ie=utf-8$script,domain=vip.jsjinfu.com`

**Comment by mapx-** [comment]
@ryanbr @AdamWr

**Comment by AdamWr** [comment]
Fixed.
