### ISSUE TITLE
raider.io: breakage

### ISSUE THREAD

**Issue by marco-kretz** [uBlockOrigin/uAssets#14484]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://raider.io/`

### Category

breakage

### Describe the issue

The content of the page is viewable for a second and then disappears into a blank site. The only thing visible is the privacy button in the bottom left corner.

Browser: Google Chrome 104.0.5112.101
OS: Archlinux
Other "privacy" or content blocking addons: none

As soon as I disable UB, the site works perfectly fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 83343
  cosmetic: 49116
  scriptlet: 17684
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5905-0, 14h.42m
    easylist: 69604-57, 14h.37m
    easyprivacy: 27396-136, 14h.36m
    plowe-0: 3633-777, 14h.35m
    ublock-abuse: 76-0, 14h.33m
    ublock-badware: 4259-92, 14h.31m
    ublock-filters: 32542-134, 14h.30m
    ublock-privacy: 231-3, 14h.29m
    ublock-quick-fixes: 381-0, 14h.28m
    ublock-unbreak: 1837-42, 14h.25m
    urlhaus-1: 5688-0, 14h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 146 ms (selfie)
  maxAssetCacheWait: 61 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    btloader.com: 1
    googletagmanager.com: 1
    intergi.com: 1
    quantserve.com: 1
    vntsm.com: 1
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/185867415-56f5161e-9a2a-4ed4-a544-8cda816b2562.png)

After clicking "Agree".
![image](https://user-images.githubusercontent.com/16838044/185867965-762d5746-6148-4546-a4ec-4d224c79f585.png)

Are you maybe logged in when the site breakage occurs?

**Comment by marco-kretz** [comment]
@okiehsch Oh you are totally right! This only occurs, when logged in. Just tested it and works fine when logged out. My bad!

**Comment by okiehsch** [comment]
@marco-kretz 
Does adding 
````
@@||cdn.intergi.com/hera/tyche.js$script,domain=raider.io
@@||hb.vntsm.com/v3/live/ad-manager.min.js$script,domain=raider.io
raider.io##.slds-p-around--x-small
````
to your filter list work for you when you are logged in?

**Comment by okiehsch** [comment]
Actually now it's broken logged out on my end too, weird.

**Comment by marco-kretz** [comment]
@okiehsch 

Yes. I can confirm that it works like a charm :+1:

**Comment by jahraphael** [comment]
> It's broken even logged out on my side (tested in brave browser), needing:
> 
> ```
> @@||cdn.intergi.com/hera/tyche.js$script,domain=raider.io
> @@||hb.vntsm.com/v3/live/ad-manager.min.js$script,domain=raider.io
> raider.io##.slds-p-around--x-small
> ```

Hi there - I hope this isn't a problem to bring this thread back.

I'm the author of raider.io and this change made above is using a selector that is breaking **lots** of regular functionality on the site, because that selector is simply our very small padding class. So we now have many buttons and elements all over the site getting removed when users have uBlock enabled.

I wanted to provide you with a selector you can use that will target display ads on the site. This is something we have always had in place, so it hasn't changed in 5+ years:

```
.rio-zone--wrapper
```

We always put this around our display ad units, and you can reliably nuke these.

Should I open this as a new ticket?

We are getting a lot of support issues from users with uBlock due to the above change.
