### ISSUE TITLE
[nsfw] cyberleaks.to: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#14483]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cyberleaks.to/`

### Category

ads

### Describe the issue

ads showing

### Screenshot(s)

<details>

NSFW
https://user-images.githubusercontent.com/81616288/185850594-f892b520-825c-4694-a6ff-f8efd64f2030.png

https://user-images.githubusercontent.com/81616288/185850593-479d9bc0-6140-4489-8839-0477150cf149.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 83376
  cosmetic: 49146
  scriptlet: 17682
  html: 730
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33243-50, 31m
    ublock-badware: 4263-0, 31m
    ublock-privacy: 249-0, 31m
    ublock-abuse: 76-0, 31m
    ublock-unbreak: 1850-0, 31m
    ublock-quick-fixes: 385-0, 31m
    easylist: 69631-601, 31m
    easyprivacy: 27402-588, 31m
    urlhaus-1: 5708-0, 31m
    plowe-0: 3633-3, 31m
    DEU-0: 5907-2, 31m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2616 ms (selfie)
  maxAssetCacheWait: 916 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    cyberleaks.to: 2
    b-cdn.net: 2
    d2juccxzu13rax.cloudfront.net: 2
    googletagmanager.com: 1
    realsrv.com: 2
```
</details>

**Comment by okiehsch** [comment]
````
cyberleaks.to##[href="https://camvids.is"]
cyberleaks.to##[href^="https://go.xlrdr.com"]
````
@ryanbr
