### ISSUE TITLE
douyu.com: breakage

### ISSUE THREAD

**Issue by kaiminz** [uBlockOrigin/uAssets#14485]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.douyu.com/`

### Category

breakage

### Describe the issue

Blank content 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium Mobile: 101
filterset (summary): 
  network: 106657
  cosmetic: 39830
  scriptlet: 17850
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt: 9773-39, 6m
  default: 
    user-filters: 302-26, never
    CHN-0: 28862-1735, 8m
    adguard-mobile: 8156-134, 8m
    easylist: 69631-24793, 8m
    easyprivacy: 27402-207, 8m
    plowe-0: 3633-912, 7m
    ublock-abuse: 76-0, 7m
    ublock-badware: 4258-92, 7m
    ublock-filters: 32649-414, 7m
    ublock-privacy: 232-5, 7m
    ublock-quick-fixes: 382-0, 7m
    ublock-unbreak: 1842-44, 7m
    urlhaus-1: 5708-0, 7m
filterset (user): [array of 298 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 991 ms
  maxAssetCacheWait: 427 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    baidu.com: 1
    douyucdn.cn: 1
    qq.com: 1
    thefatherofsalmon.com: 1
```
</details>

**Comment by ghajini** [comment]
your custom filter list
`https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt`
 is causing the issue, not ubo
