### ISSUE TITLE
przegladsportowy.onet.pl: ads

### ISSUE THREAD

**Issue by tomekdot** [uBlockOrigin/uAssets#14486]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://przegladsportowy.onet.pl/`

### Category

ads

### Describe the issue

A field with the ad removed is visible on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 103
filterset (summary): 
  network: 84037
  cosmetic: 34393
  scriptlet: 17894
  html: 738
listset (total-discarded, last updated): 
  added: 
    POL-0: 7838-143, 19h.40m
    POL-2: 1279-17, 2h.20m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33330-381, 2d.19h.36m
    ublock-badware: 4236-0, 2d.21h.2m
    ublock-privacy: 247-1, 2d.1h.43m
    ublock-abuse: 76-0, 2d.16h.16m
    ublock-unbreak: 1847-0, 2d.16h.15m
    ublock-quick-fixes: 376-0, 17h.26m
    adguard-mobile: 8155-169, 2d.16h.14m
    easylist: 69597-25183, 2d.16h.13m
    easyprivacy: 27394-588, 2d.1h.42m
    urlhaus-1: 5709-0, 1d.29m
    plowe-0: 3634-3, 11d.11h.10m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 482 ms (selfie)
  maxAssetCacheWait: 176 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    onet.pl: 8
    doubleclick.net: 1
    dreamlab.pl: 3
    gemius.pl: 1
    googletagmanager.com: 1
    ocdn.eu: 3
    opecloud.com: 2
    pushpushgo.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
przegladsportowy.onet.pl##.onet-ad:upward([class])
przegladsportowy.onet.pl##.onet-ad:upward([class*="placeholder"])

```

**Comment by garry-ut99** [comment]
> mapx- : `przegladsportowy.onet.pl##.onet-ad:upward([class])`

Cuts too much (cuts valid sections of the page) on both desktop and mobile.

> mapx- : `przegladsportowy.onet.pl##.onet-ad:upward([class*="placeholder"])`

This is OK.

<br>
Regardless of that, I notcied that enabling Adguard Base Filter fixes placeholders on desktop browser (but not on mobile), so it's worth considering copying/getting idea of some filters from AdGuard Base filter.

**Comment by mapx-** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
@mapx- Thanks

**Comment by garry-ut99** [comment]
> https://github.com/MajkiIT/polish-ads-filter/commit/9e64d43da3ca7416fb0ea460d9823b141ef5b95e

Wrong:
- POL list tries to keep compatibility with ABP as much as possible, therefore thoughtless copying / duplicating uBO only solution, despite there is ABP solution available like the one provided in AdGuard Base Filter, is simply wrong
- especially given a fact that in POL list there are already similiar ABP compatible solutions present and preffered:
`przegladsportowy.pl,auto-swiat.pl,businessinsider.com.pl,fakt.pl,komputerswiat.pl,noizz.pl,ofeminin.pl,plejada.pl,onet.pl##div[class^="AdPlaceholder_"]`
`przegladsportowy.pl,auto-swiat.pl,businessinsider.com.pl,fakt.pl,komputerswiat.pl,noizz.pl,ofeminin.pl,plejada.pl,onet.pl##aside[class^="CenterAd_container"]`
therefore logical is to keep the same logic, and AdGuard Base filters should be the ones choosen as the solution:
`przegladsportowy.onet.pl##aside[class^="Top_placeholderTop"]`
`przegladsportowy.onet.pl##aside[class^="Panel_placeholderPanel_"]`
`przegladsportowy.onet.pl##aside[class^="FlatBoxRight_"]`

- also this upward filter has landed in wrong file, it should be put into:
   - https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_ublock.txt and not in 
   https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt
   - by the way the same applies for the other upward filter filter mistakenly put in a wrong file:
https://github.com/MajkiIT/polish-ads-filter/blob/6605a34767ff58b1b61fee8d765d43eebf27b9e0/polish-adblock-filters/adblock.txt#L2100

**Comment by tomekdot** [comment]
##.FlatBoxRight_container__z4GIW 
One ad field remains on the page.

**Comment by Tasiorsa** [comment]
New clean instalation
Only ublock Origin with default filters and still same problem
Please change status to Open or New

<details>

<img width="3830" height="1545" alt="Image" src="https://github.com/user-attachments/assets/9a6f0553-5f49-4eea-a539-8b011cd42a1c" />

</details>

<details>

```yaml
uBlock Origin: 1.74.0
Firefox: 155
filterset (summary):
 network: 204113
 cosmetic: 51364
 scriptlet: 34978
 html: 3823
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 54236-72, now
  ublock-badware: 10395-17, now
  ublock-privacy: 4133-2, now
  ublock-unbreak: 2866-1, now
  ublock-quick-fixes: 514-13, now
  easylist: 88337-143, now
  easyprivacy: 56509-44, now
  urlhaus-1: 47575-11, now
  plowe-0: 3540-1044, now
  POL-0: 9052-54, now
  POL-3: 18657-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1798 ms
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 58
 network:
  onet.pl: 12
  doubleclick.net: 2
  dreamlab.pl: 1
  gemius.pl: 2
  google.com: 2
  googletagmanager.com: 2
  html-load.com: 30
  npttech.com: 1
  ocdn.eu: 5
  pushpushgo.com: 1
 extended:
  ##ad-default
  ##iframe[id][height^="  "]:style(visibility: hidden !important;)
  ##+js(prevent-clipboard-write, /^mshta |^msiexec |^(bash <<<|cur…
  ##html:not(:has(> head > style:only-child:has-text(width:399px;h…
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce.

@MajkiIT Sorry, can you reproduce the above one?

**Comment by MajkiIT** [comment]
@Tasiorsa Is it about advertising or lack of events?

**Comment by Tasiorsa** [comment]
it's about an ad that pops up 2 seconds after opening the page at the top

<img width="3840" height="555" alt="Image" src="https://github.com/user-attachments/assets/19b08cd7-eef3-47d7-9b78-2564bb773428" />

**Comment by MajkiIT** [comment]
@Tasiorsa Update polish filters

**Comment by Tasiorsa** [comment]
After update - no ads but white bar on top still exists

<details>

<img width="2079" height="963" alt="Image" src="https://github.com/user-attachments/assets/a439ba92-9dc0-4f68-a717-c116d995ef96" />

</details>

**Comment by MajkiIT** [comment]
@Tasiorsa try private mode or clear the cache.

<details>

<img width="1441" height="736" alt="Image" src="https://github.com/user-attachments/assets/1ad80731-27e2-465d-9894-dd08bb453587" />

</details>

**Comment by Tasiorsa** [comment]
After clearing the cache, everything is fine. Thanks for the update.
