### ISSUE TITLE
olx.pl: breakage

### ISSUE THREAD

**Issue by HausnerR** [uBlockOrigin/uAssets#14487]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.olx.pl/d/oferta/corvette-c5-z06-bezwypadkowa-super-okazja-CID5-IDQhUmm.html`

### Category

breakage

### Describe the issue

Page loads correctly and after second change to "Ooops, something went wrong". Disabling uBlock fix issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1680" alt="Zrzut ekranu 2022-08-22 o 13 07 39" src="https://user-images.githubusercontent.com/5604289/185907003-d8e2259d-4878-4571-b914-5e412fc912f9.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82628
  cosmetic: 52846
  scriptlet: 17893
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7833-8, 3m
    POL-2: 1276-13, 3m
    easylist: 69660-74, 3m
    easyprivacy: 27401-126, 3m
    plowe-0: 3633-785, 3m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4259-92, 2m
    ublock-filters: 32546-164, 2m
    ublock-privacy: 232-3, 2m
    ublock-quick-fixes: 382-1, 2m
    ublock-unbreak: 1840-42, 2m
    urlhaus-1: 5708-0, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 117 ms (selfie)
  maxAssetCacheWait: 48 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    criteo.net: 3
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    newrelic.com: 1
    olx-st.com: 3
    olx.org: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=olx.pl`

@ryanbr
