### ISSUE TITLE
lastpass.com: breakage

### ISSUE THREAD

**Issue by Veltys** [uBlockOrigin/uAssets#14490]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lastpass.com/es/features/password-generator`

### Category

breakage

### Describe the issue

When uBLock Origin is enabled, all JS controls and password generator are disabled and don't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2022-08-22 161937](https://user-images.githubusercontent.com/9419619/185944079-31de941c-9f16-4423-a16c-8d816cc76e7f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 154979
  cosmetic: 221827
  scriptlet: 38095
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt: 244-44, 29m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1d.11h
    https://winhelp2002.mvps.org/hosts.txt: 8730-35, 16h.13m
    adguard-annoyance: 56547-82, 1d.15h.13m
    adguard-generic: 67101-716, 1d.15h.12m
    adguard-mobile: 8155-106, 1d.15h.2m
    adguard-social: 18234-868, 1d.15h.11m
    adguard-spyware: 26490-1304, 1d.15h.10m
    dpollock-0: 11380-1477, 5d.16h.46m
    fanboy-annoyance: 79229-4621, 5d.16h.44m
    fanboy-cookiemonster: 39851-39851, 5d.16h.43m
    fanboy-social: 23297-23290, 1d.15h.7m
    fanboy-thirdparty_social: 69-21, 5d.16h.45m
    ublock-annoyances: 4530-238, 1d.15h.5m
  default: 
    user-filters: 9-0, never
    easylist: 69601-1487, 1d.15h.9m
    easyprivacy: 27394-9755, 1d.15h.8m
    plowe-0: 3633-1466, 16h.14m
    spa-0: 3897-104, 28m
    spa-1: 4600-193, 1d.15h.6m
    ublock-abuse: 76-0, 12d.16h.2m
    ublock-badware: 4259-334, 1d.15h.4m
    ublock-filters: 32535-3973, 1d.15h.3m
    ublock-privacy: 231-43, 12d.16h.1m
    ublock-quick-fixes: 381-11, 26m
    ublock-unbreak: 1836-106, 1d.15h.1m
    urlhaus-1: 5681-0, 27m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 62 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 803 ms (selfie)
  maxAssetCacheWait: 699 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    lastpass.com: 2
    go-mpulse.net: 1
    lmiutil.com: 1
```
</details>

**Comment by Veltys** [comment]
I am so sorry, I have thought my configuration was the default one.

Problematic lists were "AdGuard Tracking Protection" and "EasyPrivacy".

Thank you so much for your very quick answer.

**Comment by MasterKia** [comment]
> Problematic lists were "AdGuard Tracking Protection" and "EasyPrivacy".

Are you sure?
I tried with both of these lists and had no problems.
By the way you should keep EasyPrivacy enabled.

**Comment by Veltys** [comment]
> > Problematic lists were "AdGuard Tracking Protection" and "EasyPrivacy".
> 
> Are you sure? I tried with both of these lists and had no problems. By the way you should keep EasyPrivacy enabled.

Well... I was until your answer 😂 Enabling one from the two lists I said (and also I have to refresh with Ctrl + F5), I cannot use mentioned page. With all of them disabled, I can.

If you would like me to run some additional tests, just let me know. It will be a pleasure.

**Comment by MasterKia** [comment]
If this problem happens with *the default lists* and you've pinpointed the problem to "EasyPrivacy" list then please do additional tests by opening the logger and setting it on "blocked/modified" and seeing what's blocked.

**Comment by Veltys** [comment]
Just with "included" section active and EasyPrivacy:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | \|\|go-mpulse.net^ | -- | `www.lastpass.com` | 3 | script | `https://s.go-mpulse.net/boomerang/WH2TM-VVP9E-KZ9SR-39YA8-GGXQ9` |
| +1 | /analyticsjs. | -- | `www.lastpass.com` | 1 | script | `https://www.lastpass.com/assets/js/analyticsjs.js?t=14072022141127` |
| +1 | \|\|lmiutil.com^$3p | -- | `www.lastpass.com` | 3 | script | `https://cdn.lmiutil.com/lpassets/contentsquare/248c3f0a09329.js` |
</details>

Same result with "AdGuard Tracking Protection":

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | \|\|go-mpulse.net^$3p | -- | `www.lastpass.com` | 3 | script | `https://s.go-mpulse.net/boomerang/WH2TM-VVP9E-KZ9SR-39YA8-GGXQ9` |
| +1 | \|\|lastpass.com/assets/js/analyticsjs.js | -- | `www.lastpass.com` | 1 | script | `https://www.lastpass.com/assets/js/analyticsjs.js?t=14072022141127` |
| +1 | \|\|cdn.lmiutil.com/lpassets/contentsquare/ | -- | `www.lastpass.com` | 3 | script | `https://cdn.lmiutil.com/lpassets/contentsquare/248c3f0a09329.js` |
</details>

With none of above, block log is empty.

**Comment by MasterKia** [comment]
@Veltys Add this to "My filters" and test again:
`@@||lastpass.com/assets/js/analyticsjs.js$script,1p`

@Yuki2718 `||lastpass.com/assets/js/analyticsjs.js` from AdGuard Tracking Protection is causing issues.

**Comment by Veltys** [comment]
Done and... same blocks but works fine! I will report this problem to the mentioned lists, when I have time. Thanks again!

**Comment by MasterKia** [comment]
That's good to know.
I tagged someone who can solve this problem in that list.

**Comment by Yuki2718** [comment]
If that's the cause, EP should be affected too by `/analyticsjs.`. Will check later.

**Comment by MasterKia** [comment]
> EP should be affected too

Yes it is, I tried redirects but it didn't work.
The exception opens up a lot of tracking requests but all of them are blocked.

**Comment by AdamWr** [comment]
Did you try to use `google-analytics.com` redirect rosource?
Something like:
```
||lastpass.com/assets/js/analyticsjs.js$script,redirect=google-analytics.com/analytics.js
```
I'm not sure if it's correct syntax.

**Comment by MasterKia** [comment]
> Works fine for me on Firefox.

For clarification, the english version (`lastpass.com/en/features/password-generator` which redirects to `lastpass.com/features/password-generator-a `) works fine even with that `analyticsjs.js` blocked.

**Comment by MasterKia** [comment]
@AdamWr Your filter works.

**Comment by AdamWr** [comment]
I have added it to AdGuard Tracking Protection filter (filters update should be available in 1-2 hours).

**Comment by MasterKia** [comment]
`@@||lastpass.com/assets/js/analyticsjs.js$script,1p`

@ryanbr EasyPrivacy

**Comment by Yuki2718** [comment]
@MasterKia If works, you can add redirect rule with $important to counter coming EP exception.

**Comment by MasterKia** [comment]
> with $important

`$important` or `,important`?

In https://github.com/uBlockOrigin/uAssets/commit/7ec59a19e595f3d9eb77769d93a6228b3d4eaaf2#comments it was the latter.
