### ISSUE TITLE
Website stuck and should be refreshed, homeplus.co.kr

### ISSUE THREAD

**Issue by gybeom8008** [uBlockOrigin/uAssets#14495]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://front.homeplus.co.kr/`
`https://escrow.homeplus.co.kr/home/cart/cartList`

### Describe the issue

The first URL is Korean online grocery store. The second URL is its cart URL, where the issue occurs.

When I click 'remove from cart' button and click 'confirm', the popup should disappear and the page should be refreshed. When Ublock is on, it doesn't. (~00:59)

The website requires an account to put items into cart, so you have to proceed with 'Order without signing up' to reproduce the issue. The demonstration is included in the video.

Click 'Log in' (~00:05)
Click 'Order without signing up' (~00:09)
Fill in the ordering information, and confirm. (~00:28)

You can put any name (without spacing) and any email. Address should be real though, so here's an address you can use for reproducing issue:

서울특별시 종로구 성균관로 25-2
(put a period in the address line 2). 

The expected result is demonstrated from 00:59. 

https://user-images.githubusercontent.com/46715731/185997495-603b5c64-2191-4c26-bb19-7d6f033060fe.mp4

 

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 103.0.2

### Settings

Video is captured on new profile without any modification.

**Comment by mapx-** [comment]
@piquark6046

**Comment by piquark6046** [comment]
@gybeom8008 
Can you provide troubleshooting Information of uBlock Origin in support tab?
I cannot reproduce with uBlock built-in filters lists + List-KR.

**Comment by piquark6046** [comment]
Never mind. I can reproduce it by enabling EasyPrivacy.
