### ISSUE TITLE
megadb.net: ads

### ISSUE THREAD

**Issue by rrrcabral** [uBlockOrigin/uAssets#14494]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://megadb.net/download`

### Category

ads

### Describe the issue

showing ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82562
  cosmetic: 48319
  scriptlet: 17918
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69630-51, 16h.40m
    easyprivacy: 27401-126, 16h.39m
    plowe-0: 3634-776, 12d.4h.17m
    spa-1: 4600-80, 16h.41m
    ublock-abuse: 76-0, 8d.6h.49m
    ublock-badware: 4259-92, 16h.38m
    ublock-filters: 32537-158, 16h.37m
    ublock-privacy: 231-3, 8d.6h.48m
    ublock-quick-fixes: 382-0, 8h.32m
    ublock-unbreak: 1837-42, 16h.36m
    urlhaus-1: 5708-0, 8h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 574 ms (selfie)
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    betotodilea.com: 1
    cdnativepush.com: 4
    google-analytics.com: 1
    goomaphy.com: 3
    offerimage.com: 6
    rtmark.net: 4
    uponelectabuzzor.club: 1
```
</details>

**Comment by MasterKia** [comment]
Send the original link which you were redirected from.

**Comment by MasterKia** [comment]
Provide the original page redirecting you to this page.
