### ISSUE TITLE
blocksandfiles.com: breakage

### ISSUE THREAD

**Issue by jok1ch** [uBlockOrigin/uAssets#14492]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blocksandfiles.com/`

### Category

breakage

### Describe the issue

No thumbnails on news, no pics in each post

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 99348
  cosmetic: 67885
  scriptlet: 18843
  html: 732
listset (total-discarded, last updated): 
  default: 
    user-filters: 15-0, never
    ublock-filters: 33205-38, 4d.11m
    ublock-badware: 4237-0, 4d.10m
    ublock-privacy: 247-0, 10d.7h.42m
    ublock-abuse: 76-0, 10d.7h.41m
    ublock-unbreak: 1852-0, 4d.9m
    easylist: 69566-609, 4d.8m
    easyprivacy: 27358-578, 4d.7m
    urlhaus-1: 5688-0, 23h.30m
    plowe-0: 3634-3, 10d.7h.40m
    RUS-0: 42103-148, 32m
    ublock-quick-fixes: 384-0, 23h.29m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1880 ms (selfie)
  maxAssetCacheWait: 1030 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    blocksandfiles.com: 4
    doubleclick.net: 2
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Test this filter

`blocksandfiles.com#@#div[class*="td-a-rec-id-"]`

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Exceptions won't help here. If the tracking settings in Firefox are too strict, then this site breaks even without a blocker.

**Comment by mapx-** [comment]
tested in brave (chromium) and the exception above is fixing the OP issue

**Comment by dimisa-RUAdList** [comment]
It's not difficult for me to add an exception, however I don't see any breakage when using browsers based on the Chrome engine. At the same time, I see crashes when using the default settings of Firefox 103.0.2, clean, without extensions.

**Comment by dportvine** [comment]
Only disabling uBO helps
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/111344219/185988266-945ed05b-48a4-4949-9a3a-ab44f7b79095.gif)
</details>

or if i add `blocksandfiles.com##+js(aeld, load, /return"undefined"/)` i see images after few seconds.

<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/111344219/185994350-d9feff79-71ab-46f6-9f78-1181546785dd.gif)
</details>
