### ISSUE TITLE
garticphone.com: ads

### ISSUE THREAD

**Issue by Lubrsi** [uBlockOrigin/uAssets#14497]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://garticphone.com/`

### Category

ads

### Describe the issue

Has a blank space on the left of the page where an ad would be. This causes the game to appear off center.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2022-08-22 21-57-57](https://user-images.githubusercontent.com/25595356/186017826-d73e7be7-be19-414f-8e16-08b1a49d4eea.png)
![Screenshot from 2022-08-22 22-00-05](https://user-images.githubusercontent.com/25595356/186018025-a099ecf1-c3db-431b-87d9-3c187ba63acc.png)
![Screenshot from 2022-08-22 22-03-40](https://user-images.githubusercontent.com/25595356/186018821-ea23f2be-c350-4863-a50f-6323d3c32466.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 93288
  cosmetic: 178956
  scriptlet: 24806
  html: 741
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 56592-4913, 2m
    adguard-social: 18250-1059, 2m
    fanboy-thirdparty_social: 69-0, 2m
    fanboy-annoyance: 79984-64017, 2m
    fanboy-cookiemonster: 40534-132, 2m
    fanboy-social: 23299-28, 2m
    ublock-annoyances: 4539-4, 2m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33205-53, 2m
    ublock-badware: 4218-0, 2m
    ublock-privacy: 263-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1851-0, 2m
    easylist: 69389-618, 2m
    easyprivacy: 27403-582, 2m
    urlhaus-1: 5681-0, 2m
    plowe-0: 3633-3, 2m
    ublock-quick-fixes: 384-0, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3229 ms (selfie)
  maxAssetCacheWait: 753 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
garticphone.com###__next > [class^="jsx-"]:not([id])
```

**Comment by Lubrsi** [comment]
Works for me 👍

**Comment by mapx-** [comment]
@ryanbr
