### ISSUE TITLE
fool.ca: breakage

### ISSUE THREAD

**Issue by yhager** [uBlockOrigin/uAssets#14496]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fool.ca/free-stock-report/5-stocks-under-50/?source=isaspp7410000011&adname=CA_SA_5under50_5under50&placement=pitch`

### Category

breakage

### Describe the issue

The email signup field does not show when ublock Origin is enabled.
I do have the duckduckgo extension that I think does a bit of filtering, but I haven't seen any mention of it being problematic in the twitter thread or in this github project

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ublock Origin:
![image](https://user-images.githubusercontent.com/65973/186009581-c831f21e-33cb-464d-bf4a-0a719c19d7da.png)

Without:
![image](https://user-images.githubusercontent.com/65973/186009695-c994c34a-386e-483f-a5bd-63f1de067ef1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81205
  cosmetic: 45387
  scriptlet: 17659
  html: 726
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33212-72, 2d.13h.2m
    ublock-badware: 4263-0, 2d.13h.6m
    ublock-privacy: 247-0, 6d.23h
    ublock-abuse: 76-0, 6d.22h.59m
    ublock-unbreak: 1843-0, 2d.13h.5m
    easylist: 69600-595, 2d.13h.4m
    easyprivacy: 27394-578, 2d.13h.3m
    urlhaus-1: 5708-0, 14h.57m
    plowe-0: 3634-3, 11d.2h.41m
    ublock-quick-fixes: 417-0, 14h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4234 ms (selfie)
  maxAssetCacheWait: 1176 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    doubleclick.net: 2
    getnitropack.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    lytics.io: 1
    newrelic.com: 1
    segment.com: 1
    yimg.com: 1
```
</details>

**Comment by ghajini** [comment]
@ryanbr 
`fool.ca##.fool-ecap` causing email sign up hide
