### ISSUE TITLE
fuckadblock detector

### ISSUE THREAD

**Issue by jo2dan23** [uBlockOrigin/uAssets#145]
i tried redirecting it to the built in fuckadblock script but it doesn't work. here is what is triggering anti adblcok message:

http://www.lcpdfr.com/detect.js

located: http://www.lcpdfr.com/files/

**Comment by gorhill** [comment]
Try:

    lcpdfr.com##script:inject(fuckadblock.js-3.2.0)
    ||pagead2.googlesyndication.com/*.js$important,script,domain=lcpdfr.com

The second filter is to cancel the whitelisting of `googlesyndication.com` from EasyList.

Is the result ok for uBO?

**Comment by jo2dan23** [comment]
it isn't injecting. must be a different script?

**Comment by Tmp341** [comment]
There is an inline script contains : `_lcpdfr.vars["ADSBLOCKED"] = false;`

**Comment by gorhill** [comment]
Is it about the warning at the top?

**Comment by Tmp341** [comment]
I've only seen that warning. I don't know if there are more.

**Comment by gorhill** [comment]
If it's only about that warning, a cosmetic filter should suffice. How about:

    ||pagead2.googlesyndication.com/*.js$important,script,domain=lcpdfr.com
    lcpdfr.com##:xpath(/html/body/div[./b/text()="Ad blocking software detected"])

**Comment by Tmp341** [comment]
@gorhill, Tried with those, like 5 times. No warning showed up.

**Comment by jo2dan23** [comment]
worked. thanks!
