### ISSUE TITLE
My company's website is being blocked by your list

### ISSUE THREAD

**Issue by TheDesignerXD** [uBlockOrigin/uAssets#14508]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.ispot.tv/`

### Describe the issue

My company's website is being blocked by your list
 
Upon going directly to the homepage url, or most of the secondary pages I am met with a "This site can't be reached" error.
https://user-images.githubusercontent.com/5721469/186224833-d99ef7c4-5eb8-432e-9dfb-74ec6107652b.png
s

Upon hard refreshing cmd+shift+r the pages work:
https://user-images.githubusercontent.com/5721469/186225004-dca66b6d-e8e3-4c11-9f07-82ce0fff0a8a.png

When I turn off your adblocker, our site once again works as expected. I am hoping that we can just get our domain whitelisted... because we specialize in Nationally broadcasted Advertisement Metrics (we tell our clients how their ads are performing on Television)

### uBlock Origin version

<details>
    <summary>Info</summary>

```yaml
uBlock Origin: 1.43.0 Chromium: 104 filterset (summary):    network: 80217   cosmetic: 44671   scriptlet: 17692   html: 0 listset (total-discarded, last updated):    default:      user-filters: 0-0, never     easylist: 68947-51, 29m     easyprivacy: 27408-126, 28m     plowe-0: 3633-776, 27m     ublock-abuse: 76-0, 25m     ublock-badware: 4214-94, 23m     ublock-filters: 32510-122, 22m     ublock-privacy: 241-3, 21m     ublock-quick-fixes: 386-0, 20m     ublock-unbreak: 1838-41, 19m     urlhaus-1: 4707-0, 18m filterset (user): [empty] modifiedUserSettings: [none] modifiedHiddenSettings: [none] supportStats:    allReadyAfter: 1061 ms   maxAssetCacheWait: 186 ms
```
</details>

### Browser name and version

Google Chrome: Version 104.0.5112.101 (Official Build) (x86_64)

### Settings

None

**Comment by MasterKia** [comment]
I can access the site just fine using Firefox.

From our default lists only `pi.ispot.tv` and `pt.ispot.tv` are blocked and not the whole site so maybe there's something wrong with the browser.

Please test with Firefox.
I can't enter your site using Chromium even with uBO off.

**Comment by krystian3w** [comment]
Test without any service like NextDNS.

**Comment by okiehsch** [comment]
Using Chrome going to your website....
![image](https://user-images.githubusercontent.com/16838044/186230622-58b8dcbc-3b56-4c55-aaa5-076cb629aefc.png)

> This site can't be reached

That's not an error that is usually caused by an extension blocking requests.

**Comment by MasterKia** [comment]
> we specialize in Advertisement Metrics

Then I guess `||ispot.tv^$3p` for EasyPrivacy would be nice.

**Comment by krystian3w** [comment]
And NextDNS convert this to DNS ban (he convert `3p` and `popup` as DNS ban).

**Comment by TheDesignerXD** [comment]
> Using Chrome going to your website.... ![image](https://user-images.githubusercontent.com/16838044/186230622-58b8dcbc-3b56-4c55-aaa5-076cb629aefc.png)
> 
> > This site can't be reached
> 
> That's not an error that is usually caused by an extension blocking requests.

I should have been more specific in my link... try this page: https://www.ispot.tv/products/analytics/custom

Alternatively try navigating to it through the nav menu via products -> Analytics (far right column) -> Custom

Then try turning off ublock and going to it. It seems to always fail for me when ublock is on, but succeeds without it. Certainly possible it's not a ublock issue specifically, but interesting that it is blocked at all, when as you pointed out the homepage works even with ublock on.

**Comment by TheDesignerXD** [comment]
A secondary thought... where might I find the filter list? I want to check for a few other things we have in front of our site that our marketing team has added to provide site caching...

**Comment by TheDesignerXD** [comment]
> Maybe your site has DNS issues because I get "Unable to connect" on Firefox mobile.

Curious indeed. That's Firefox on what device? On my iPhone it works fine via Firefox mobile...

**Comment by TheDesignerXD** [comment]
> Maybe your site has DNS issues because I get "Unable to connect" on Firefox mobile.

This actually makes me think it might be a third party we are using called Huckabuy... they are supposed to "accelerate" your site by serving cached copies of the pages... but they use Cloudflare on the front and we've have issues with their use of Cloudflare in the past... wondering if this is more of the same...

**Comment by MasterKia** [comment]
I did some checking and my DNS blocklist was the issue on Firefox Mobile in Android.
Tomorrow I'll see which DNS list has blocked your list but nevertheless I don't think uBO is causing this issue.

**Comment by TheDesignerXD** [comment]
Thank you for the help you have been thus far... It is much further along than I would have been on my own. 👍

**Comment by TheDesignerXD** [comment]
Might I ask... in the filters-2021 list, what is does this mean? If I'm understanding it correctly, it is set to block js from ispot.tv? It seems more specific than that, but I don't understand the shorthand.

! ispot. tv anti adb
ispot.tv##+js(aeld, , adb)

**Comment by MasterKia** [comment]
Your site has anti-adblock to detect uBlock Origin therefore we addressed it.

You can disable that filter by going to uBO settings and adding this to "My filters":
`ispot.tv#@#+js(aeld, , adb)`

**Comment by TheDesignerXD** [comment]
Ah... lol I see. We setup an alert for customers that told them they had ad block on and it used to block all images and videos on our site because they were served up with the word /ad in the src url... we have since addressed that issue... and actually are removing any adblock detection in our next release as luck would have it (today). Who would have thought having the text ad in the name of so many things on our website would be a problem (hint, I did...)

**Comment by MasterKia** [comment]
> ad block used to block all images and videos on our site because they were served up with the word /ad in the src url

You could've just reported here and we would've instabtly fixed that breakage by adding exceptions for your `ispot.tv/images/ad/legitpicture.jpg`.

**Comment by TheDesignerXD** [comment]
That is realllly good to know. I will make sure we reach out in the future... HA! Wasn't aware of how active the community of devs were on this. (It makes sense in retrospect... but hindsight is 20:20... )

**Comment by krystian3w** [comment]
France?

**Comment by TheDesignerXD** [comment]
> France?

Huh?

**Comment by TheDesignerXD** [comment]
> > ad block used to block all images and videos on our site because they were served up with the word /ad in the src url
> 
> You could've just reported here and we would've instantly fixed that breakage by adding exceptions for your `ispot.tv/images/ad/legitpicture.jpg`.

Moving forward is it possible to get removed from this list, if I can prove to you that we don't have adblock anymore? Our next release that removes it (and moves our entire CMS to /hub rather than the super awesome /ads directory) is actually later today 2pm PST... afterwhich all adblock detection will be removed from our site.

**Comment by MasterKia** [comment]
Don't worry, that filter won't break your site even if you remove the detection codes.

**Comment by okiehsch** [comment]
> Moving forward is it possible to get removed from this list,

Sure as soon as your bait script
`https://www.ispot.tv/ads/wp-content/themes/ispot/adblocker/adblocker.js`
has been removed our filter becomes obsolete.

**Comment by okiehsch** [comment]
Detection is gone.
https://github.com/uBlockOrigin/uAssets/commit/75728706aa7513dc4d8c22705a91e687405317eb
