### ISSUE TITLE
animevietsub.co: ads

### ISSUE THREAD

**Issue by toaitk123** [uBlockOrigin/uAssets#14507]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://animevietsub.co/`

### Category

ads

### Describe the issue

Still showing ads or ad containers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 97
filterset (summary): 
  network: 82344
  cosmetic: 28194
  scriptlet: 17748
  html: 728
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33337-348, 3d.51m
    ublock-badware: 4262-0, 22h.11m
    ublock-privacy: 247-1, 2d.6h.58m
    ublock-abuse: 76-0, 2d.6h.57m
    ublock-unbreak: 1855-0, 22h.10m
    adguard-mobile: 8155-171, 3d.49m
    easylist: 69600-25174, 3d.50m
    easyprivacy: 27403-592, 22h.9m
    urlhaus-1: 4670-0, 11h.19m
    plowe-0: 3634-3, 13d.6h.34m
    VIE-1: 1910-32, 3d.10h.44m
    ublock-quick-fixes: 355-1, 11h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 272 ms (selfie)
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    admicro.vn: 2
    facebook.com: 1
    googletagmanager.com: 1
    i8xkjci7nd.com: 2
    jarvispopsu.com: 2
```
</details>

**Comment by MasterKia** [comment]
> Our service is not available in your area
Caution! If you are not Vietnamese, please exit this page, it may be dangerous to you.

**Comment by MasterKia** [comment]
@hoang-rio
