### ISSUE TITLE
thingiverse.com: breakage

### ISSUE THREAD

**Issue by iHaired** [uBlockOrigin/uAssets#14503]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thingiverse.com/thing:4810040`

### Category

breakage

### Describe the issue

uBlock brakes thingivers pages. When enabled the page will show «Something went wrong».

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 98429
  cosmetic: 67304
  scriptlet: 18869
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 153-10, never
    RUS-0: 42091-9, 2m
    easylist: 68945-66, 2m
    easyprivacy: 27406-225, 2m
    plowe-0: 3633-781, 2m
    ublock-abuse: 76-1, 2m
    ublock-badware: 4214-94, 2m
    ublock-filters: 32510-156, 2m
    ublock-privacy: 241-3, 1m
    ublock-quick-fixes: 391-0, 1m
    ublock-unbreak: 1839-42, 1m
    urlhaus-1: 4670-0, 1m
filterset (user): [array of 153 redacted]
trustedset: 
  added: [array of 176 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1321 ms (selfie)
  maxAssetCacheWait: 307 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    amazon-adsystem.com: 1
    doubleclick.net: 2
    googletagmanager.com: 2
    thingiverse.com: 1
    uptime.com: 1
```
</details>

**Comment by okiehsch** [comment]
Site looks fine on my end, maybe you need to be logged in for the breakage to occur?

**Comment by dimisa-RUAdList** [comment]
Maybe that's the problem? ~>
> ```yaml
> user-filters: 153-10, never
> ```

**Comment by iHaired** [comment]
> `https://www.thingiverse.com/thing:4810040`

Yep that's the thing. I've created an account and now it's working fine. Thank you.
