### ISSUE TITLE
4rxworld.su: ads

### ISSUE THREAD

**Issue by MichaelCharles** [uBlockOrigin/uAssets#14505]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://4rxworld.su/`

### Category

ads

### Describe the issue

This site is a fake russian site advertising as a Canadian pharmacy.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 80198
  cosmetic: 45401
  scriptlet: 17681
  html: 0
listset (total-discarded, last updated): 
  added: 
    block-lan: 43-0, 24d.23h.53m
  default: 
    user-filters: 2-0, never
    easylist: 69600-51, 2d.23h.21m
    easyprivacy: 27394-126, 2d.23h.20m
    plowe-0: 3633-776, 1d.19h.12m
    ublock-abuse: 76-0, 2d.7h.16m
    ublock-badware: 4259-92, 2d.23h.19m
    ublock-filters: 32536-122, 2d.23h.18m
    ublock-privacy: 232-3, 2d.3h.13m
    ublock-quick-fixes: 381-0, 7h.7m
    ublock-unbreak: 1832-41, 2d.23h.17m
    urlhaus-1: 4670-0, 7h.8m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 294 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    ipinfo.io: 1
```
</details>

**Comment by MasterKia** [comment]
And where is the "ads"?
Please send screenshot.

**Comment by okiehsch** [comment]
I think the idea is that we should block the whole site.

**Comment by MasterKia** [comment]
@dimisa-RUAdList Is this a fake "Russian" site?

**Comment by dimisa-RUAdList** [comment]
@MasterKia 
I doubt. I did not find any characteristic details, the presence of which would make it possible to classify this site as Russian.

**Comment by MasterKia** [comment]
Only the `whois` indicates a sign of being Russian ...

![IMG_20220824_130831](https://user-images.githubusercontent.com/17685483/186371954-85ef5c50-89bb-4724-90c7-f55318718263.jpg)

**Comment by dimisa-RUAdList** [comment]
There are no requests, service, functional or advertising related to Russia, there.

**Comment by mapx-** [comment]
@MichaelCharles Did you get a `4rxworld` page being redirected from another site?

**Comment by okiehsch** [comment]
Maybe the OP thinks it's russian because it uses a .su TLD.

**Comment by MichaelCharles** [comment]
I am claiming the entire site is a bogus ad.  Your reporting form does not
have a selection that allows me to say that.

.su is a ccTLD, presumably under the control of the Russian Institute for
Public Networks.  (My best guess is that .su is really under control of no
one.)   Yet 4rxworld.su traceroutes to California.  This is probably a
violation of ICANN policy.

Your whois info identifies an owner.  Try contacting that owner and see
what you get.  Better yet, go to 4rxworld.su and select "Contact Us".  The
page is not just defective, it is plainly intentionally defective.  On top
of that, it is non-functional.  One cannot contact anyone.

Then try and order a prescription item.  Note that a doctor's prescription
is not required, which is illegal in Canada (and USA).  If you follow thru
and actually get your order (which you will not), then you are receiving
illegal goods.

I can send you a phishing email that advertises this site if you wish.

Fake Canadian pharmacy sites under Russian control are well known to
Canadian pharmacies.  See
https://www.canadapharmacy.com/blog/fake-canadian-pharmacies or
https://www.cipa.com/beware-of-rogues.  Wikipedia indicates that .su is
"known for usage by cybercriminals and right-wing extremists".  See .su -
Wikipedia <https://en.wikipedia.org/wiki/.su>.

It seems to me you block ads in sites for much less than what is described
above.
