### ISSUE TITLE
webnovelpub.com: detection

### ISSUE THREAD

**Issue by WaywardFellow** [uBlockOrigin/uAssets#14509]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.webnovelpub.com/novel/astral-apostle-22082212/1383-chapter-245`

### Category

detection

### Describe the issue

the site detects adblock and replaces ads with huge red anti-adblock messages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://user-images.githubusercontent.com/108738459/186232817-a7e2210b-3b18-4cd2-803e-572b8fb176be.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82011
  cosmetic: 43830
  scriptlet: 17205
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68049-168, never
    easyprivacy: 27172-101, never
    plowe-0: 3639-784, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-3, never
    ublock-filters: 31779-96, never
    ublock-privacy: 222-0, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-30, never
    urlhaus-1: 7285-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 991 ms
  maxAssetCacheWait: 5 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    moatads.com: 1
    translate.googleapis.com: 3
```
</details>

**Comment by okiehsch** [comment]
Isn't that an annoyance?

**Comment by MasterKia** [comment]
No, they're changing fast.

If after a week they don't change it to a hard anti-adb then we could address it in the annoyances list.

**Comment by okiehsch** [comment]
Fine, the same fix works here.

**Comment by MasterKia** [comment]
@WaywardFellow It's fixed, force update your filter lists.

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by garry-ut99** [comment]
Anti-adblock here too: `novelpub.com`
