### ISSUE TITLE
[nsfw] gspf.qingepxsjdshaode.xyz: ads

### ISSUE THREAD

**Issue by banbiantian** [uBlockOrigin/uAssets#14502]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://gspf.qingepxsjdshaode.xyz/?c=cq34`

### Category

ads

### Describe the issue

This site will cause an ad browser shortcut to appear on your computer desktop, which will pop up every time your computer boots up, and there is no way to block it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 99575
  cosmetic: 55395
  scriptlet: 17795
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-5, never
    CHN-0: 28868-89, 19h.8m
    easylist: 69371-75, 19h.13m
    easyprivacy: 27403-150, 19h.12m
    plowe-0: 3634-778, 12d.19h.34m
    ublock-abuse: 76-0, 11d.5h.55m
    ublock-badware: 4259-92, 19h.10m
    ublock-filters: 32545-145, 19h.9m
    ublock-privacy: 231-3, 9d.17h.59m
    ublock-quick-fixes: 378-0, 19h.6m
    ublock-unbreak: 1840-42, 19h.14m
    urlhaus-1: 5681-0, 19h.7m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 16 redacted]
hostRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 215 ms (selfie)
  maxAssetCacheWait: 105 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Well, that sound like malware/adware, so how did you end up at that site?
