### ISSUE TITLE
mope.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1450]
### URL(s) where the issue occurs
`http://mope.io`

### Describe the issue
Displays an anti-adblock message. Also has leftover ad-placeholders.

### Screenshot(s)
![mope io anti-adblock](https://user-images.githubusercontent.com/29117662/35724137-8fa6fb4e-07b1-11e8-8a44-88c5eab89fbd.PNG)

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.14.25.101 (Nano Adblocker 1.0.0.28)

### Settings
Default.

### Notes
Anti-adblock, and ad-placeholders.

**Comment by agam3r** [comment]
advertising leftover(s) with uBO's ebd + uBlock filters -- Annoyances enabled

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/17fab2bec5e3b5a121cdd444e02727bed069d75a
