### ISSUE TITLE
brisbanetimes.com.au, smh.com.au, theage.com.au, watoday.com.au: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14500]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

- `https://www.brisbanetimes.com.au/`
- `https://www.smh.com.au/`
- `https://www.theage.com.au/`
- `https://www.watoday.com.au/`

### Category

ads

### Describe the issue

There's a big ad area at the top of each of the listed sister sites.

See: https://github.com/easylist/easylist/issues/13036#issuecomment-1223502490

### Screenshot(s)

<details><summary>Screenshot</summary>

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110956608/186042288-940c159d-bf47-41a7-8b36-4a3233e844c1.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 138718
  cosmetic: 82057
  scriptlet: 19931
  html: 735
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 719-2, 38m
    block-lan: 43-0, 38m
    curben-phishing: 55907-6, 38m
    curben-pup: 188-0, 38m
    fanboy-cookiemonster: 40546-101, 1m
  default: 
    user-filters: 196-0, never
    ublock-filters: 33206-137, 38m
    ublock-badware: 4218-0, 38m
    ublock-privacy: 263-0, 38m
    ublock-abuse: 76-0, 38m
    ublock-unbreak: 1851-1, 38m
    ublock-quick-fixes: 384-0, 38m
    easylist: 69018-491, 38m
    easyprivacy: 27405-595, 38m
    urlhaus-1: 4670-0, 38m
    plowe-0: 3633-3, 38m
filterset (user): [array of 136 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 622 ms
  maxAssetCacheWait: 333 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    bing.com: 1
    d2uhnetoehh304.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    moatads.com: 1
    parsely.com: 1
    pubmatic.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe 

```
brisbanetimes.com.au,smh.com.au,theage.com.au,watoday.com.au##[class]:matches-css(height: 267px)
brisbanetimes.com.au,smh.com.au,theage.com.au,watoday.com.au##[class]:matches-css(height: 427px)
brisbanetimes.com.au,smh.com.au,theage.com.au,watoday.com.au##header:style(top: 0 !important)
```
