### ISSUE TITLE
clutchpoints.com: nuisance

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#14506]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://clutchpoints.com/49ers-news-san-francisco-expects-jimmy-garoppolo-to-sign-with-nfc-rival-if-qbs-cut/`

### Category

nuisance

### Describe the issue

when visiting after a time period you get a redirect to a warning page that says your using a outdated version of Firefox, and then it redirects again to download the newest version of Firefox. Also I think it only on initial visit.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
Not sure how to screen shot it I don't know the exact time it will happen, or if its a scroll point.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b1
Firefox: 104
filterset (summary): 
  network: 140134
  cosmetic: 90154
  scriptlet: 20679
  html: 751
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 480-1, 17m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 510-0, 16m
    https://www.i-dont-care-about-cookies.eu/abp/: 25286-4, 17m
    adguard-spyware-url: 719-2, 17m
    block-lan: 43-0, 17m
    curben-phishing: 56224-4, 17m
    curben-pup: 188-0, 17m
    fanboy-social: 23300-9, 17m
    ublock-annoyances: 4539-9, 17m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33214-44, 17m
    ublock-badware: 4223-0, 17m
    ublock-privacy: 263-0, 17m
    ublock-abuse: 76-0, 17m
    ublock-unbreak: 1851-3, 17m
    ublock-quick-fixes: 391-0, 17m
    easylist: 68947-338, 17m
    easyprivacy: 27408-148, 17m
    urlhaus-1: 4707-0, 17m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 39 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: none
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 181 ms (selfie)
  maxAssetCacheWait: 238 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    clutchpoints.com: 1
    adthrive.com: 1
    cloudflareinsights.com: 2
    facebook.net: 2
    google-analytics.com: 1
    googletagmanager.com: 3
    indexww.com: 1
    onesignal.com: 1
    quantserve.com: 1
    sc-static.net: 1
    scorecardresearch.com: 1
    taboola.com: 2
    vuukle.com: 6
```
</details>

**Comment by MasterKia** [comment]
> after a time period you get a redirect to a warning page

I waited for 3 minutes and got no warning page.
Maybe this is caused by one of your extensions, try disabling all of them and test again.

**Comment by troysjanda** [comment]
disabled my addons except Ublock, which were 

- paywall bypass clean
- Cookie Autodelete
- Country flags and whois
- localcdn
- reddit enhancement suite
- reload in url bar

Cleared cache and cookies but I can't seem to get it to trigger again.

**Comment by MasterKia** [comment]
Did the warning you saw look like this? (with Firefox logo and name ofc)

https://user-images.githubusercontent.com/17685483/186224329-600deebe-1cc8-4fcc-b6ce-c0c7b59b4ae2.png

**Comment by troysjanda** [comment]
yes similar, but not chrome logo

**Comment by MasterKia** [comment]
> someone I know (who uses Chrome and uBlock Origin) reported the same thing

I asked and he said "_I was there in that very same page (example.com), suddenly the page was modified under the same url and the "download" button had a javascript blob file so they had javascript access which shouldn't be possible using the filter rules unless they've found a vulnerability_"

**Comment by troysjanda** [comment]
>I asked and he said "I was there in that very same page (example.com), suddenly the page was modified under the same url and the "download" button had a javascript blob file so they had javascript access which shouldn't be possible using the filter rules unless they've found a vulnerability"

not sure I understand this.

**Comment by MasterKia** [comment]
No problem. I was just leaving it here for more details, maybe someone knows what's going on.

**Comment by ghajini** [comment]
may be adware ,do you get on this website only or generally all website?

**Comment by troysjanda** [comment]
As stated it only happen in that site. Never seen it on another site.
