### ISSUE TITLE
keran.co: detection

### ISSUE THREAD

**Issue by imprateekd** [uBlockOrigin/uAssets#14515]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://keran.co/ETH/`

### Category

detection

### Describe the issue

adblocker is being detected please fix the issue for the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80204
  cosmetic: 20709
  scriptlet: 17705
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.2m
  default: 
    user-filters: 0-0, never
    easylist: 68950-23750, 1h.2m
    easyprivacy: 27411-128, 1h.2m
    plowe-0: 3633-776, 1h.2m
    ublock-abuse: 76-0, 1h.2m
    ublock-badware: 4219-94, 1h.2m
    ublock-filters: 32522-381, 1h.2m
    ublock-privacy: 241-4, 1h.2m
    ublock-quick-fixes: 392-4, 1h.2m
    ublock-unbreak: 1838-41, 1h.2m
    urlhaus-1: 4681-0, 1h.2m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7285 ms
  maxAssetCacheWait: 727 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    keran.co: 3
    a-ads.com: 1
    bmcdn3.com: 2
    bmcdn4.com: 2
    cointraffic.io: 1
    coinzillatag.com: 1
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce detection.
Please send screenshot.

`0x6f6870feb48f08388ee345cf0261e2f03d2fa310`

> Rewards: 24 Satoshi ETH every 60 minutes
Your Claim
You've claimed successfully 24 Satoshi ETH.
You can claim again in 60 minutes! and Withdraw your balance to withdraw menu `https://keran.co/ETH/withdraw.php`

**Comment by MasterKia** [comment]
By the way the site looks like a scam.
