### ISSUE TITLE
cavea.plus: detection

### ISSUE THREAD

**Issue by thesandro** [uBlockOrigin/uAssets#14519]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cavea.plus/ka/watch/coma-5b`

### Category

detection

### Describe the issue

Detects ublock origin and says to turn it off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/37246896/186500923-131fd0ca-2019-4dc9-b8df-72f0bd51b5d8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 109867
  cosmetic: 210094
  scriptlet: 37348
  html: 742
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4539-4, 10m
    adguard-generic: 67195-5449, 10m
    adguard-annoyance: 56731-4438, 10m
    adguard-social: 18295-1059, 10m
    fanboy-annoyance: 80021-64484, 10m
    fanboy-cookiemonster: 40565-132, 10m
    fanboy-social: 23302-8, 10m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33181-57, 10m
    ublock-badware: 4165-0, 10m
    ublock-privacy: 263-0, 10m
    ublock-abuse: 76-0, 10m
    ublock-unbreak: 1851-0, 10m
    easylist: 68710-669, 10m
    easyprivacy: 27414-582, 10m
    plowe-0: 3633-3, 10m
    urlhaus-1: 4810-0, 10m
    ublock-quick-fixes: 397-0, 10m
filterset (user): [empty]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 252 ms (selfie)
  maxAssetCacheWait: 536 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    cavea.plus: 12
    googletagmanager.com: 1
```
</details>

**Comment by thesandro** [comment]
How can I provide account info?

**Comment by thesandro** [comment]
It seems message is triggered by this: 
![image](https://user-images.githubusercontent.com/37246896/186512752-7ad575ff-6c81-42d9-a0b7-3f71c0d8c8d7.png)

**Comment by mapx-** [comment]
> How can I provide account info?


send the info to `misu39@yahoo.com`

**Comment by thesandro** [comment]
> > How can I provide account info?
> 
> send the info to `misu39@yahoo.com`

done

**Comment by mapx-** [comment]
Could you test

`/ads?position$badfilter`

**Comment by thesandro** [comment]
> Could you test
> 
> `/ads?position$badfilter`

Do you mean this? the request still gets blocked.
![image](https://user-images.githubusercontent.com/37246896/186637214-69e82365-101f-4664-9deb-9dfdc5f111cd.png)

**Comment by thesandro** [comment]
> 

works
