### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by bits933** [uBlockOrigin/uAssets#14517]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=jfKfPfyJRdk`

### Category

ads

### Describe the issue

it is showing ads .. isnt it supposed to block that???

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 80205
  cosmetic: 44391
  scriptlet: 17704
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 68673-51, 10h.46m
    easyprivacy: 27411-126, 10h.49m
    plowe-0: 3633-776, 1h.12m
    ublock-abuse: 76-0, 1h.14m
    ublock-badware: 4219-94, 10h.50m
    ublock-filters: 32522-122, 10h.48m
    ublock-privacy: 241-3, 1h.15m
    ublock-quick-fixes: 390-4, 8h.17m
    ublock-unbreak: 1838-41, 10h.47m
    urlhaus-1: 4681-0, 8h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 462 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 105
  blockedDetails: 
    youtube.com: 85
    doubleclick.net: 3
    google.co.in: 1
    google.com: 6
    googleadservices.com: 2
    googlesyndication.com: 2
    googlevideo.com: 6
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
