### ISSUE TITLE
philo.com: breakage

### ISSUE THREAD

**Issue by mufffffin56** [uBlockOrigin/uAssets#14513]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY2NDI5Mw`

### Category

breakage

### Describe the issue

cant skip anything when the uorigin app is on, doesn't work on this site at all. when enabled cant use subtitles or pause/play/seek in the player. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 80177
  cosmetic: 45406
  scriptlet: 17686
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 69604-51, 2d.2h.46m
    easyprivacy: 27408-126, 9h.56m
    plowe-0: 3635-777, 4d.23h.34m
    ublock-abuse: 76-0, 6d.56m
    ublock-badware: 4259-92, 2d.2h.49m
    ublock-filters: 32546-122, 2d.2h.48m
    ublock-privacy: 231-3, 6d.57m
    ublock-quick-fixes: 381-0, 23h.15m
    ublock-unbreak: 1837-41, 2d.2h.47m
    urlhaus-1: 4670-0, 23h.16m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 934 ms (selfie)
  maxAssetCacheWait: 504 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    imrworldwide.com: 1
    segment.com: 1
```
</details>

**Comment by MasterKia** [comment]
> Sorry, Philo is only available in the United States... for now.

**Comment by mapx-** [comment]
- open the logger
- repeat the steps to get the issue
- go back into the logger and then copy and paste here all blocked requests
