### ISSUE TITLE
[NSFW] cn.xsz-av.com: detection

### ISSUE THREAD

**Issue by chuyueye** [uBlockOrigin/uAssets#14510]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cn.xsz-av.com/video/91504/%E6%9E%81%E5%93%81%E9%9D%93%E4%B9%B3%E7%BE%8E%E5%B0%91%E5%A5%B3%E9%93%83%E6%9C%A8%E7%BE%8E%E5%92%B22019%E6%9C%80%E5%BC%BA%E5%A4%A7%E5%B0%BA%E5%BA%A6%E6%96%B0%E4%BD%9C-%E6%B7%AB%E6%AC%B2x%E4%BA%A4%E5%8F%8B%E4%BA%BA%E7%9A%84lo%E5%A8%98-%E7%BE%8E%E4%B9%B3%E7%B2%89%E7%A9%B4-%E5%8E%9F%E7%89%88%E7%A7%81%E6%8B%8D59p-%E8%B6%85%E6%B8%851080p%E5%8E%9F%E7%89%88%E6%97%A0%E6%B0%B4%E5%8D%B0?asgtbndr=1`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 99577
  cosmetic: 55384
  scriptlet: 17796
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 9-1, never
    CHN-0: 28870-89, 1d.2h.29m
    easylist: 69371-75, 1d.6h.33m
    easyprivacy: 27403-150, 1d.6h.34m
    plowe-0: 3634-778, 11d.18h.48m
    ublock-abuse: 76-0, 11d.18h.51m
    ublock-badware: 4259-92, 1d.6h.30m
    ublock-filters: 32543-143, 1d.6h.32m
    ublock-privacy: 231-3, 11d.18h.50m
    ublock-quick-fixes: 380-0, 22h.28m
    ublock-unbreak: 1840-42, 1d.6h.31m
    urlhaus-1: 5681-0, 22h.27m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 296 ms (selfie)
  maxAssetCacheWait: 210 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    xsz-av.com: 1
    cloudflareinsights.com: 1
    realsrv.com: 2
```
</details>

**Comment by ghajini** [comment]
`cn.xsz-av.com##+js(nostif, ad)`

**Comment by MasterKia** [comment]
@Yuki2718 AG Chinese.

**Comment by Yuki2718** [comment]
> AG Chinese.

Not exactly, it seems the site is international and OP happened to choose Chinese locale.

**Comment by chuyueye** [comment]
> OP

btw,what is "OP " means.
beg your pardon

**Comment by MasterKia** [comment]
Original poster (you).
