### ISSUE TITLE
afcdp.net: breakage

### ISSUE THREAD

**Issue by stonehellway** [uBlockOrigin/uAssets#14516]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://afcdp.net/`

### Category

breakage

### Describe the issue

The website is unresponsive until I disable uBlock. After I refresh the website the cookie banner appears. I can pick my choice and enable ublock once again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 203511
  cosmetic: 223737
  scriptlet: 37903
  html: 736
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 67120-5892, 1d.23h.56m
    adguard-mobile: 8156-150, 1d.23h.57m
    adguard-spyware: 26495-1080, 1d.23h.59m
    adguard-spyware-url: 720-3, 2d.1m
    block-lan: 43-0, 8d.28m
    curben-phishing: 55793-5, 20h.32m
    curben-pup: 188-0, 20h.31m
    adguard-annoyance: 56561-4710, 1d.23h.58m
    adguard-social: 18235-1065, 1d.23h.54m
    fanboy-thirdparty_social: 68-0, 8d.17m
    fanboy-annoyance: 76789-61102, 8d.16m
    fanboy-cookiemonster: 37658-139, 8d.15m
    fanboy-social: 23299-28, 2d
    ublock-annoyances: 4538-4, 1d.23h.55m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33243-52, 1d.23h.53m
    ublock-badware: 4263-0, 1d.23h.52m
    ublock-privacy: 247-0, 8d.25m
    ublock-abuse: 76-0, 8d.24m
    ublock-unbreak: 1850-0, 1d.23h.51m
    ublock-quick-fixes: 384-0, 20h.30m
    easylist: 69631-855, 1d.23h.50m
    easyprivacy: 27402-9770, 1d.23h.49m
    urlhaus-1: 4670-0, 20h.28m
    plowe-0: 3630-3, 8d.23m
    FRA-0: 30470-515, 2d.2m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1708 ms (selfie)
  maxAssetCacheWait: 801 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    afcdp.net: 1
```
</details>

**Comment by okiehsch** [comment]
`afcdp.net#@##cooky`
@ryanbr in  Annoyance and EasyList Cookie.
