### ISSUE TITLE
[nsfw] nhentai.net: breakage

### ISSUE THREAD

**Issue by thonking3** [uBlockOrigin/uAssets#14522]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nhentai.net/`

### Category

breakage

### Describe the issue

When I click to some manga, my browser doesn't redirect me to read them. It stuck at first page of the site. It only happend to some manga, not all of them. I need to refresh the website 3 or 4 times to make the bug disappear. This bug only happend if I turn Ublock Origin on. I'm using Kiwi browser. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium Mobile: 101
filterset (summary): 
  network: 103384
  cosmetic: 77093
  scriptlet: 23850
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 56736-1647, 3m
    adguard-spyware: 25423-743, 3m
    adguard-spyware-url: 721-1, 3m
    ublock-annoyances: 4551-168, 3m
  default: 
    user-filters: 0-0, never
    VIE-1: 1924-31, 8m
    adguard-mobile: 8159-33, 8m
    easylist: 68523-23543, 5m
    easyprivacy: 27415-9029, 4m
    plowe-0: 3634-939, never
    ublock-abuse: 76-0, never
    ublock-badware: 4232-96, never
    ublock-filters: 32615-793, never
    ublock-privacy: 231-38, never
    ublock-quick-fixes: 389-37, never
    ublock-unbreak: 1863-62, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3334 ms
  maxAssetCacheWait: 1726 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Repeat your test using FF mobile => kiwi has its own issues with uBO

> It only happend to some manga, not all of them
provide one of them

**Comment by thonking3** [comment]
> Repeat your test using FF mobile => kiwi has its own issues with uBO
> 
> > It only happend to some manga, not all of them
> 
> provide one of them

Anything in "Popular now" section.
And sorry to ask but... What does "FF mobile" means? I need to test it on some more devices?

**Comment by mapx-** [comment]
You are using Kiwi browser which has some issues with uBO / other adblockers.
Instead of kiwi use **firefox mobile** on your device and repeat the tests.

**Comment by thonking3** [comment]
> You are using Kiwi browser which has some issues with uBO / other adblockers. Instead of kiwi use **firefox mobile** on your device and repeat the tests.

Oh thank you. I'll try that.
