### ISSUE TITLE
aresmanga.com: detection

### ISSUE THREAD

**Issue by BlackSoull** [uBlockOrigin/uAssets#14527]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aresmanga.com/`

### Category

detection

### Describe the issue

It detect uBlock Origin 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium Mobile: 105
filterset (summary): 
  network: 84407
  cosmetic: 28129
  scriptlet: 17862
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://secure.fanboy.co.nz/enhancedstats.txt: 2996-44, 1d.21h.7m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8159-28, 8h.12m
    easylist: 68438-23367, 8h.11m
    easyprivacy: 27417-180, 7h.40m
    plowe-0: 3629-864, 12d.11h.18m
    ublock-abuse: 76-0, 12d.11h.16m
    ublock-badware: 4160-96, 7h.39m
    ublock-filters: 32587-409, 7h.38m
    ublock-privacy: 241-4, 7h.37m
    ublock-quick-fixes: 390-4, 8h.7m
    ublock-unbreak: 1843-43, 7h.36m
    urlhaus-1: 5668-0, 8h.8m
filterset (user): [array of 2 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1412 ms (selfie)
  maxAssetCacheWait: 441 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    diasciaplatly.com: 1
```
</details>

**Comment by MasterKia** [comment]
MDP Deblocker

**Comment by BlackSoull** [comment]
Yes thanks it works now
