### ISSUE TITLE
theguardian.com: nuisance

### ISSUE THREAD

**Issue by Telmesomething** [uBlockOrigin/uAssets#14528]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theguardian.com/international`

### Category

nuisance

### Describe the issue

When using either the zapper, or the element picker mode, the element is overlaid with a pale yellow film. However when clicking that in order to save it no dialog box appears and the selected element is simply removed. Consequently, when the page is reloaded or refreshed the element reappears. 
Selected element to block.

Cannot save selected blocked element
https://user-images.githubusercontent.com/33827636/186709830-d6e7fd4a-21f8-4d21-b0b3-b36c3b889739.PNG

Selected element disappears after clicking it
https://user-images.githubusercontent.com/33827636/186710272-e284f795-b7c7-46ed-a348-1a1ccd8a558c.PNG

Element returns as soon as the page is refreshed or reloaded
https://user-images.githubusercontent.com/33827636/186710748-dc8b4d8a-0c3a-48d1-8da7-233259b809b5.PNG

Incidentally, I tried to report this via de in-app report form, but that justs loads a 404 error.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 88840
  cosmetic: 119058
  scriptlet: 22281
  html: 737
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 68-0, 23h.1m
    fanboy-annoyance: 80020-64038, 23h.1m
    fanboy-cookiemonster: 40564-134, 23h.1m
    fanboy-social: 23302-28, 23h.1m
    ublock-annoyances: 4539-4, 23h.1m
    NLD-0: 2445-33, 23h.1m
    THA-0: 1028-3, never
  default: 
    user-filters: 121-1, never
    ublock-filters: 33226-98, 1d.4h.4m
    ublock-badware: 4218-0, 1d.4h.3m
    ublock-privacy: 247-0, 5d.4h.8m
    ublock-abuse: 76-0, 5d.4h.7m
    ublock-unbreak: 1852-0, 1d.4h.2m
    ublock-quick-fixes: 397-0, 23h.3m
    easylist: 68677-626, 1d.4h.1m
    easyprivacy: 27413-581, 1d.4h
    urlhaus-1: 4810-0, 23h.2m
    plowe-0: 3632-3, 5d.4h.1m
filterset (user): [array of 121 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 553 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    theguardian.com: 32
    getsentry.com: 1
```
</details>

**Comment by MasterKia** [comment]
Right click in the page and press "Block element".
Select the element you like and press create, if it *somehow* doesn't work then copy the filter and add it to "My filters" in uBlock Origin settings.
