### ISSUE TITLE
spellingmistakescostlives.com: breakage

### ISSUE THREAD

**Issue by aricooperdavis** [uBlockOrigin/uAssets#14524]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.spellingmistakescostlives.com/single-post/digital-ad-space-efficiency-rating`

### Category

breakage

### Describe the issue

The page initially loads but then the post contents disappear and an error message is displayed.

This behaviour does not occur when uBlock origin is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8947634/186618211-e0ca2b48-387c-4aff-b7c2-deb8d4fc1a50.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81197
  cosmetic: 44011
  scriptlet: 17700
  html: 729
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 33181-38, 10m
    ublock-badware: 4165-0, 14m
    ublock-privacy: 247-0, 6d.22h.42m
    ublock-abuse: 76-0, 6d.22h.41m
    ublock-unbreak: 1851-0, 13m
    easylist: 68380-599, 12m
    easyprivacy: 27418-578, 11m
    urlhaus-1: 5668-0, 8m
    plowe-0: 3633-3, 15m
    ublock-quick-fixes: 397-0, 9m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1937 ms (selfie)
  maxAssetCacheWait: 478 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    spellingmistakescostlives.com: 2
    facebook.com: 1
    googletagmanager.com: 1
    paypalobjects.com: 2
    twitter.com: 1
    wix.com: 37
    wixpress.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`-ad-space-$badfilter`

EL issue @ryanbr

**Comment by ryanbr** [comment]
Don't have -ad-space- in Easylist @mapx-

**Comment by mapx-** [comment]
it's about `-Ad-Space-`

**Comment by garry-ut99** [comment]
uBO logger says: `-ad-space-`, not a uBO logger's bug?

![44444](https://user-images.githubusercontent.com/72945564/186630497-c925563a-9679-415d-82c9-57c607d8ba95.png)

**Comment by mapx-** [comment]
The network filters are case-insensitive => it does not matter how the logger displays them

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/dc6ec59de16563c6035e2e8bbfab3c6a12011846
