### ISSUE TITLE
[NSFW]koushoku.org

### ISSUE THREAD

**Issue by rushuna86** [uBlockOrigin/uAssets#14523]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://koushoku.org/

### Describe the issue

Pages of comic doesn't display with adblock on.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 81245
  cosmetic: 44097
  scriptlet: 17705
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    easylist: 68438-51, now
    easyprivacy: 27417-126, now
    plowe-0: 3633-776, now
    ublock-abuse: 76-0, 1d.7h.4m
    ublock-badware: 4219-97, 1d.7h.4m
    ublock-filters: 32522-132, 1d.7h.4m
    ublock-privacy: 241-3, 1d.7h.4m
    ublock-quick-fixes: 392-4, 7h.4m
    ublock-unbreak: 1838-41, 1d.7h.4m
    urlhaus-1: 5668-0, now
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 677 ms (selfie)
  maxAssetCacheWait: 362 ms
```
</details>

**Comment by garry-ut99** [comment]
> rushuna86 : I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

https://github.com/uBlockOrigin/uAssets/issues/14477

**Comment by rushuna86** [comment]
so sorry when i search nothing came up for me
