### ISSUE TITLE
Something is being blocked from today (or yesteday) that prevents the O2 webmail to load

### ISSUE THREAD

**Issue by FlashThunder** [uBlockOrigin/uAssets#14525]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

poczta.o2.pl

### Describe the issue

Login site doesn't load, after logging in with uBlock turned off, emails don't appear.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16067512/186649402-1e68913f-4a25-4a81-80fe-fd21530e7525.png)
![image](https://user-images.githubusercontent.com/16067512/186649511-3c6f4446-b65a-4938-bb63-c71c0c50cbf0.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 81751
  cosmetic: 52092
  scriptlet: 17898
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 17h.13m
  default: 
    user-filters: 0-0, never
    POL-0: 7842-8, 17h.12m
    POL-2: 1276-13, 1d.13h.16m
    easylist: 68945-74, 2d.1h.23m
    easyprivacy: 27406-126, 2d.1h.25m
    plowe-0: 3633-785, 4d.20h.18m
    ublock-abuse: 76-0, 6d.20h.36m
    ublock-badware: 4259-94, 2d.1h.24m
    ublock-filters: 32510-160, 2d.1h.22m
    ublock-privacy: 231-3, 6d.20h.35m
    ublock-quick-fixes: 394-1, 17h.15m
    ublock-unbreak: 1837-43, 2d.1h.21m
    urlhaus-1: 4810-0, 17h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 291 ms (selfie)
  maxAssetCacheWait: 147 ms
```
</details>

**Comment by JobcenterTycoon** [comment]
@krystian3w

**Comment by krystian3w** [comment]
Test on disabled Vivaldi AdBlock "Protection"?

For now I reproduce only glitch with empty mail from self promotion mail to have free account (without detect guilty).

**Comment by FlashThunder** [comment]
Oh it worked, thank You.
