### ISSUE TITLE
cnnbrasil.com.br: nuisance

### ISSUE THREAD

**Issue by SimplesmenteMaria** [uBlockOrigin/uAssets#14526]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cnnbrasil.com.br/politica/pesquisa-realtime-big-data-governo-de-sp-haddad-34-tarcisio-e-rodrigo-20/`

### Category

nuisance

### Describe the issue

Sticky header and headlines occupying a large part of phone screens. Please overwrite the style to make the position of the header/headlines static.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img src="https://camo.githubusercontent.com/96c39d56be54dec6b7ab8279c40f788840186bd9d540b38719003e757d099722/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f3356674a7949752e706e67">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 104587
  cosmetic: 152223
  scriptlet: 36568
  html: 742
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
  added: 
    adguard-generic: 67080-5351, now
    adguard-mobile: 8159-150, now
    adguard-spyware: 25439-822, now
    adguard-spyware-url: 723-2, now
    adguard-annoyance: 56752-1634, now
    adguard-social: 18303-30, now
    ublock-annoyances: 4539-4, now
    spa-1: 4605-15, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33180-96, now
    ublock-badware: 4166-0, now
    ublock-privacy: 263-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1851-1, now
    ublock-quick-fixes: 395-0, now
    easylist: 68392-814, now
    urlhaus-1: 5668-0, now
    plowe-0: 3633-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7059 ms
  maxAssetCacheWait: 2704 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cnnbrasil.com.br: 1
    flipboard.com: 2
    googletagmanager.com: 1
    onesignal.com: 2
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
test

```
cnnbrasil.com.br##.hot__content:style(position: relative !important)
cnnbrasil.com.br##.header__group:style(position: relative !important)
```

**Comment by SimplesmenteMaria** [comment]
This works for me. It adds an empty block between the logo and the headlines, but in my opinion that's better than keeping them visible all the time.
