### ISSUE TITLE
telus.com: breakage

### ISSUE THREAD

**Issue by potatoleek** [uBlockOrigin/uAssets#14520]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.telus.com/en/health/virtual-pharmacy`

### Category

breakage

### Describe the issue

The page content is displayed briefly before turning into a blank page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80601
  cosmetic: 45630
  scriptlet: 20667
  html: 742
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4539-4, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33181-126, now
    ublock-badware: 4165-0, now
    ublock-privacy: 263-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1851-0, now
    easylist: 68710-497, now
    easyprivacy: 27414-595, now
    urlhaus-1: 4810-0, now
    plowe-0: 3633-3, now
    ublock-quick-fixes: 393-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 959 ms (selfie)
  maxAssetCacheWait: 282 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    telus.com: 2
    googletagmanager.com: 1
    marketo.net: 2
```
</details>

**Comment by mapx-** [comment]
Test 

`@@||munchkin.marketo.net/munchkin.js$script,domain=telus.com`

EP issue @ryanbr
