### ISSUE TITLE
[nsfw] 18comic.org: breakage

### ISSUE THREAD

**Issue by tainchuan** [uBlockOrigin/uAssets#14521]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://18comic.org/photo/371611`

### Category

breakage

### Describe the issue

I delet every windows then I cant click any links in the websit.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 99550
  cosmetic: 55682
  scriptlet: 17811
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 14-3, never
    CHN-0: 28866-89, 2d.16h.4m
    easylist: 69662-75, 2d.16h.3m
    easyprivacy: 27402-150, 2d.16h.2m
    plowe-0: 3632-778, 4d.21h.28m
    ublock-abuse: 76-0, 5d.15h.48m
    ublock-badware: 4259-92, 2d.16h.1m
    ublock-filters: 32546-145, 2d.16h
    ublock-privacy: 231-3, 5d.15h.47m
    ublock-quick-fixes: 394-0, 20m
    ublock-unbreak: 1837-42, 2d.15h.59m
    urlhaus-1: 5668-0, 19m
filterset (user): [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 638 ms (selfie)
  maxAssetCacheWait: 397 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    18comic.org: 2
    exoclick.com: 1
    googletagmanager.com: 1
    jads.co: 2
    realsrv.com: 1
```
</details>

**Comment by mapx-** [comment]
> I delet every windows

What do you mean ?

**Comment by mapx-** [comment]
The anti adb message is present even disabling uBO (simple warning)

**Comment by tainchuan** [comment]
oh I mean I delete every pop up windows in that websit

mapx- ***@***.***> 於 2022年8月25日 週四 下午2:40寫道：

**Comment by mapx-** [comment]
You deleted them because annoyances ?

**Comment by tainchuan** [comment]
yes. I turned off the ublock but some pictures were still blocked.

mapx- ***@***.***> 於 2022年8月25日 週四 下午6:20寫道：

**Comment by MasterKia** [comment]
> The anti adb message is present even disabling uBO (simple warning)

Soft anti-adb is addressed in uBO annoyances?

**Comment by tainchuan** [comment]
sorry I cant understand, I just use the tool on the ublock and click the
pop up windows

MasterKia ***@***.***> 於 2022年8月25日 週四 晚上8:40寫道：

**Comment by mapx-** [comment]
> Soft anti-adb is addressed in uBO annoyances?

Yes, but in this case is present even disabling uBO. Eventually addressable by FA / adguard annoyances lists

@tainchuan you are breaking the page using your own filters, you should report the annoyances to fanboy annoyances list or adguard annoyances
