### ISSUE TITLE
iqiyi.com: breakage

### ISSUE THREAD

**Issue by sparksfly0** [uBlockOrigin/uAssets#14533]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.iqiyi.com/`

### Category

breakage

### Describe the issue

Open iqiyi with edge 104.0.1293.63. There is no content on the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Uploading 爱奇艺20220826114059.png…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 99525
  cosmetic: 55669
  scriptlet: 17808
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28862-89, 3d.18h.42m
    easylist: 69632-74, 3d.18h.41m
    easyprivacy: 27402-150, 3d.18h.40m
    plowe-0: 3635-779, 7d.19h.16m
    ublock-abuse: 76-0, 3d.18h.39m
    ublock-badware: 4259-92, 3d.18h.37m
    ublock-filters: 32546-141, 3d.18h.35m
    ublock-privacy: 232-3, 3d.18h.34m
    ublock-quick-fixes: 390-0, 19h.45m
    ublock-unbreak: 1837-42, 3d.18h.33m
    urlhaus-1: 5668-0, 19h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1210 ms (selfie)
  maxAssetCacheWait: 807 ms
popupPanel: 
  blocked: 121
  blockedDetails: 
    baidu.com: 1
    bdstatic.com: 1
    qy.net: 119
```
</details>

**Comment by garry-ut99** [comment]
I don't use Edge, but on Firefox and Opera the site is working fine for me.

**Comment by okiehsch** [comment]
Looks fine on my end using Edge.

**Comment by Yuki2718** [comment]
Fine too.
