### ISSUE TITLE
Buffer icons are filtered on Twitter

### ISSUE THREAD

**Issue by delaunay75** [uBlockOrigin/uAssets#14536]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://twitter.com`
`https://tweetdeck.twitter.com`

### Describe the issue

Buffer icons are filtered by uBlock origin on Chromium on Ubuntu. The logger doesn't seem to show anything wrong. The settings seem ok. The only way to make it work is uninstalling uBlock. The issue only occurs with Chromium on Ubuntu. No issues with Firefox on Ubuntu and no issues on Mac OS (with the same extensions installed). I've been trying to solve the problem with the Buffer team but we ran out of ideas.

### uBlock Origin version

1.44.0

### Browser name and version

Chromium 104.0.5112.101

### Settings

I've tried to check Block CSP reports (as it's checked by default on uBlock on Firefox) but it didn't make a difference

**Comment by MasterKia** [comment]
> Buffer icons are filtered by uBlock origin

Please send screenshot and the steps needed to reproduce.

**Comment by delaunay75** [comment]
While uninstalling uBO did solve the problem earlier, I've realized I had forgotten to remove another extension called Shortkeys (my bad). Removing Shortkeys solved issue even with uBO installed. Not too sure what's going on but Buffer is now working fine even with uBO.
