### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by dahgul333** [uBlockOrigin/uAssets#14532]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rezka.ag/series/fiction/47699-pakt-2022.html`

### Category

ads

### Describe the issue

add window in player

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 100258
  cosmetic: 66413
  scriptlet: 18873
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-1, never
    RUS-0: 41990-9, 1d.5h.47m
    easylist: 68392-67, 6h.50m
    easyprivacy: 27423-225, 6h.46m
    plowe-0: 3630-782, 11d.10h.9m
    ublock-abuse: 76-1, 11d.10h.7m
    ublock-badware: 4162-96, 6h.48m
    ublock-filters: 32477-152, 6h.47m
    ublock-privacy: 231-3, 11d.10h.8m
    ublock-quick-fixes: 386-5, 3h.19m
    ublock-unbreak: 1838-41, 6h.49m
    urlhaus-1: 6478-0, 3h.20m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 969 ms (selfie)
  maxAssetCacheWait: 331 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adpod.in: 1
    franecki.net: 6
    franeski.net: 2
    hdrezka.ac: 1
    jsdelivr.net: 1
    nogravity.fun: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/a2dc7ffb7706461869f103f30ff659ea20b0527d
