### ISSUE TITLE
productz.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#14538]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://productz.com/en/lenovo-thinkpad-l380-vs-lenovo-thinkpad-l390/v/lEmWx-YZrAN`

### Category

nuisance

### Describe the issue

cookies notice

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 106
filterset (summary): 
  network: 84762
  cosmetic: 122669
  scriptlet: 23423
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9939-4, 1d.1h.37m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 1d.1h.36m
    fanboy-annoyance: 79709-244, 5d.8h.56m
    ublock-annoyances: 4531-75, 1d.1h.42m
  default: 
    user-filters: 12-0, never
    easylist: 68392-66, 1d.1h.44m
    easyprivacy: 27423-126, 1d.1h.43m
    ublock-abuse: 76-0, 5d.4h.52m
    ublock-badware: 4162-94, 1d.1h.40m
    ublock-filters: 32480-434, 1d.1h.39m
    ublock-privacy: 231-10, 5d.4h.48m
    ublock-quick-fixes: 394-5, 1h.17m
    ublock-unbreak: 1837-44, 1d.1h.38m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 19 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 635 ms (selfie)
  maxAssetCacheWait: 498 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    google.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/186950111-feff9301-58b4-4e0e-9cb1-52880bd7d85f.png)

**Comment by MasterKia** [comment]
> - [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)

> uAssets will not address GDPR (cookie) modals.

Go to settings => Filter lists => Annoyances => Enable the "EasyList Cookie" list and test again.

Report to: https://github.com/easylist/easylist/
