### ISSUE TITLE
bng-qa.xyz: nuisance

### ISSUE THREAD

**Issue by FsGraphy** [uBlockOrigin/uAssets#14539]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://bng-qa.xyz/`

### Category

nuisance

### Describe the issue

Its a scam website, which forcefully makes website full screen.
Better to block the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/49984733/186958891-8cc22cfb-50b0-4ecd-9312-63c8305183f2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 82018
  cosmetic: 43832
  scriptlet: 17169
  html: 677
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32409-34, 3d.2h.47m
    ublock-badware: 4175-3, 2d.17h.45m
    ublock-privacy: 228-0, 2d.22h.42m
    ublock-abuse: 75-0, 2d.22h.43m
    ublock-unbreak: 1809-0, 3d.2h.49m
    easylist: 68049-564, 3d.2h.48m
    easyprivacy: 27172-579, 3d.2h.46m
    urlhaus-1: 7285-0, 17h
    plowe-0: 3639-3, 1d.21h.5m
    ublock-quick-fixes: 202-0, 21h.31m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 47 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 180885 ms (selfie)
  maxAssetCacheWait: 28929 ms
popupPanel: 
  blocked: 2
  no-popups: true
  blockedDetails: 
    bng-qa.xyz: 2
```
</details>

**Comment by Yuki2718** [comment]
Only redirected to `safeshare.tv`

**Comment by Yuki2718** [comment]
And how your SS is related to the site?
