### ISSUE TITLE
cbs.com: detection

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#14543]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cbs.com/shows/video/zph4KM_1N_kzJaq7h31VV16wVePmg5AC/`

### Category

detection

### Describe the issue

video will not play due to adblock detection.
![cbserror](https://user-images.githubusercontent.com/24624945/187000223-1ea878cc-9349-4b8a-9335-130cd5a1cc9d.GIF)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b2
Firefox: 104
filterset (summary): 
  network: 152770
  cosmetic: 89110
  scriptlet: 20698
  html: 753
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 480-1, 6h.37m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 509-0, 6h.37m
    https://www.i-dont-care-about-cookies.eu/abp/: 25302-4, 6h.37m
    adguard-spyware-url: 725-2, 6h.37m
    block-lan: 43-0, 6h.37m
    curben-phishing: 66113-5, 6h.37m
    curben-pup: 189-0, 6h.37m
    fanboy-social: 23307-9, 6h.37m
    ublock-annoyances: 4539-9, 6h.37m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33186-134, 6h.37m
    ublock-badware: 4166-0, 6h.37m
    ublock-privacy: 263-0, 6h.37m
    ublock-abuse: 76-0, 6h.37m
    ublock-unbreak: 1852-3, 6h.37m
    ublock-quick-fixes: 397-0, 6h.37m
    easylist: 68048-248, 6h.37m
    easyprivacy: 27425-151, 6h.37m
    urlhaus-1: 7355-0, 6h.37m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 40 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: none
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 276 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    2mdn.net: 1
    cbsi.com: 1
    polyfill.io: 1
    sentry.io: 1
```
</details>

**Comment by Infrastructural** [comment]
Are you using any other content blocker? Did you also try visiting the webpage without any third-party filter lists?

**Comment by troysjanda** [comment]
No and yes

**Comment by tamiep** [comment]
I have the same issue.
It just started happening today and I watch videos on this website ever weekday.
I have no other ad-blocker software.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0a10846c2fa45ef01714ceb40f2982b0de1d6c27

**Comment by sugarfreesweetener** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14849#issuecomment-1248962943
