### ISSUE TITLE
kpopjams.com: detection

### ISSUE THREAD

**Issue by honeylump** [uBlockOrigin/uAssets#14545]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kpopjams.com`

### Category

detection

### Describe the issue

detects the adblocker when i go to the website. i'm using firefox, recently switched from chrome and **when i was using chrome, it did not detect ubo.** i am using privacy badger as well but i'm not sure if this counts as a "content blocker" since its meant to block tracking. i also use decentraleyes, same issue, as well as firefox built in tracking blockers. again not sure if these would interfere or count. i am not using any other ad blockers specifically though! when i disable ubo for this website, but nothing else, the website works again but shows ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1440" alt="Screen Shot 2022-08-26 at 6 01 45 PM" src="https://user-images.githubusercontent.com/112220833/187008165-b659d6ff-37c1-4f37-866a-9c10ed167cbc.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81160
  cosmetic: 45432
  scriptlet: 17681
  html: 729
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33243-38, 4d.19h.13m
    ublock-badware: 4263-0, 4d.19h.12m
    ublock-privacy: 247-0, 13d.23h.10m
    ublock-abuse: 76-0, 13d.23h.9m
    ublock-unbreak: 1850-0, 4d.19h.11m
    ublock-quick-fixes: 384-0, 4d.15h.55m
    easylist: 69631-595, 4d.19h.10m
    easyprivacy: 27354-578, 8d.19h.17m
    urlhaus-1: 5708-0, 4d.15h.54m
    plowe-0: 3629-3, 13d.23h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 343 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    criteo.net: 1
    disqus.com: 4
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    gstatic.com: 13
    paypal.com: 1
    rezync.com: 1
    taboola.com: 1
    wp.com: 4
```
</details>

**Comment by Yuki2718** [comment]
> i am using privacy badger as well but i'm not sure if this counts as a "content blocker" since its meant to block tracking.

It counts as a content blocker and interferes with uBO's resource redirect.

**Comment by honeylump** [comment]
I removed both of these extensions and it's still not working...

**Comment by Infrastructural** [comment]
@honeylump Did you update uBlock Origin's enabled-by-default filter lists?

**Comment by Yuki2718** [comment]
@honeylump Please force-update filter lists i.e. in Filter lists pane Purge all caches => Update now
