### ISSUE TITLE
duellinksmeta.com: detection

### ISSUE THREAD

**Issue by WhisperInTheDark** [uBlockOrigin/uAssets#14549]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.duellinksmeta.com/`

### Category

detection

### Describe the issue

The website detects Ublock Origin and shows a popup every time you click on a new page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/97631664/187026327-95c3c2d5-4057-49f3-91bf-94a83baee90d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82903
  cosmetic: 44366
  scriptlet: 17703
  html: 734
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33215-138, 3d.14h.17m
    ublock-badware: 4218-0, 2d.21h.48m
    ublock-privacy: 263-0, 14h.46m
    ublock-abuse: 76-0, 14h.45m
    ublock-unbreak: 1852-0, 2d.21h.47m
    ublock-quick-fixes: 397-0, 14h.43m
    easylist: 68690-496, 2d.21h.46m
    easyprivacy: 27413-595, 2d.21h.45m
    urlhaus-1: 7355-0, 14h.44m
    plowe-0: 3633-3, 4d.20h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 511 ms (selfie)
  maxAssetCacheWait: 107 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    btloader.com: 1
    googletagmanager.com: 1
    intergient.com: 4
```
</details>

**Comment by sum2012** [comment]
@Yuki2718  I reproduce.For example
https://www.duellinksmeta.com/top-decks
![2](https://user-images.githubusercontent.com/2177532/187053873-467fe797-fa4d-49d7-8db9-853421371502.jpg)

**Comment by Yuki2718** [comment]
@sum2012 I still can't, where do you access from?

**Comment by sum2012** [comment]
My english is not good enough.
I am in Hong Kong.
![1](https://user-images.githubusercontent.com/2177532/187057717-c2e03a61-1b30-42e7-b185-7531afa8e917.jpg)

**Comment by Yuki2718** [comment]
Reproduced after some interaction with the site. It's dismissable so will address in Annoyances.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14708
