### ISSUE TITLE
watch.truecrimenetworktv.com: detection

### ISSUE THREAD

**Issue by EW1S** [uBlockOrigin/uAssets#14546]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watch.truecrimenetworktv.com/series/true-crime-network-originals`

### Category

detection

### Describe the issue

pretty self explainatory - the site sees ublock and I have to turn it off to use the site

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 102
filterset (summary): 
  network: 82099
  cosmetic: 44645
  scriptlet: 17697
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3h.53m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 435-65, never
    ublock-filters: 33181-33, 2d.3h.26m
    ublock-badware: 4218-1, 2d.3h.25m
    ublock-privacy: 247-0, 10d.20h.16m
    ublock-abuse: 76-0, 10d.20h.15m
    ublock-unbreak: 1851-29, 2d.3h.27m
    easylist: 68710-601, 2d.3h.24m
    easyprivacy: 27414-102, 2d.3h.23m
    plowe-0: 3630-451, 10d.20h.13m
    urlhaus-1: 6478-0, 1d.2h.31m
    ublock-quick-fixes: 389-4, 1d.2h.32m
filterset (user): [array of 436 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1474 ms (selfie)
  maxAssetCacheWait: 1075 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    4info.com: 1
    amagi.tv: 13
    execute-api.us-east-1.amazonaws.com: 1
    google-analytics.com: 1
```
</details>

**Comment by MasterKia** [comment]
> We're sorry. You've reached our on-demand platform which is only available to users in the United States.

**Comment by MasterKia** [comment]
> - [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

> user-filters: 435-65

Please test without your custom filters ("My filters").

**Comment by EW1S** [comment]
I am in the US.

CONFIDENTIALITY NOTICE: This communication is intended for the sole use of the individual and entity to whom it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are hereby notified that any dissemination, distribution or duplication of this communication by someone other than the intended addressee or its designated agent is strictly prohibited. DO NOT FORWARD.


     On Friday, August 26, 2022, 11:49:15 PM GMT-8, MasterKia  <> wrote:  
 
   ] 




We're sorry. You've reached our on-demand platform which is only available to users in the United States.

**Comment by EW1S** [comment]
What are you talking about? I am not a programmer.

CONFIDENTIALITY NOTICE: This communication is intended for the sole use of the individual and entity to whom it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are hereby notified that any dissemination, distribution or duplication of this communication by someone other than the intended addressee or its designated agent is strictly prohibited. DO NOT FORWARD.


     On Friday, August 26, 2022, 11:51:06 PM GMT-8, MasterKia  <> wrote:  
 
   ] 



   
   -  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules



user-filters: 435-65


Please test without your custom filters ("My filters").

**Comment by ghajini** [comment]
i can reproduce that video is not playing
@ryanbr 
`@@||cdn-ue1-prod.tsv2.amagi.tv/beacon$xhr,domain=watch.truecrimenetworktv.com`

**Comment by MasterKia** [comment]
@EW1S Please remove Adblock Plus (and Privacy Badger) from your add-ons.

**Comment by MasterKia** [comment]
@EW1S Please remove Adblock Plus (and optionally Privacy Badger) from your add-ons.
