### ISSUE TITLE
sinau-thewe.com [anti-copy]

### ISSUE THREAD

**Issue by cyberboh** [uBlockOrigin/uAssets#14551]
### Prerequisites

- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sinau-thewe.com/2022/08/unduh-cara-instal-dapodik-versi-2023c.html`

### Describe the issue

anti copy paste
can't copy
can't right click

### uBlock Origin version

1.44.0

### Browser name and version

Chrome 104.0.5112.102

### Settings

default

**Comment by okiehsch** [comment]
I can right click.
````
sinau-thewe.com##*:style(-webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
````
fixes the issues I can reproduce on my end.

**Comment by cyberboh** [comment]
> I can right click.
> 
> ```
> sinau-thewe.com##*:style(-webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
> ```
> 
> fixes the issues I can reproduce on my end.

Thanks, this fixes my issue.
Would you merged into filterlist?

**Comment by okiehsch** [comment]
It's fixed in the uBO-annoyance list.
