### ISSUE TITLE
esportstales.com: detection

### ISSUE THREAD

**Issue by zentriex** [uBlockOrigin/uAssets#14552]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.esportstales.com/apex-legends/how-to-increase-fps-videoconfig-settings-launch-options`

### Category

detection

### Describe the issue

Tried blocking elements, trued refreshing the page and filter list. Still detecting

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82969
  cosmetic: 20708
  scriptlet: 17714
  html: 736
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 33186-279, now
    ublock-badware: 4165-0, 1d.14h.3m
    ublock-privacy: 263-1, 1d.14h.2m
    ublock-abuse: 76-0, 1d.14h.1m
    ublock-unbreak: 1852-0, 1d.14h
    ublock-quick-fixes: 397-0, 39m
    easylist: 68048-23254, 15h.29m
    easyprivacy: 27425-581, 15h.28m
    urlhaus-1: 7355-0, 15h.27m
    plowe-0: 3633-3, 15h.26m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 152 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    esportstales.com: 2
    adsafeprotected.com: 2
    adthrive.com: 1
    advertising.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    outstandingincome.com: 1
    squarespace.com: 2
    typekit.net: 1
```
</details>

**Comment by zentriex** [comment]
***UPDATE*** Javascript seems to be the backend of what they're using. disabling JS on this site removes the intrusion. Not sure if it blocks them detecting it (I doubt it does) but it does at least remove them being able to block you from seeing/scrolling on the page.

**Comment by zentriex** [comment]
Figured out how to reopen it. Again admins, I apologize for the closing and reopening. I'm figuring it out

**Comment by ghajini** [comment]
@pgl 
admiral
`||marriedbelief.com^`

**Comment by pgl** [comment]
> marriedbelief.com

Thanks, added!

**Comment by MasterKia** [comment]
@zentriex Force update your filter lists, it's fixed.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by zentriex** [comment]
Thank you!
