### ISSUE TITLE
nybooks.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14553]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nybooks.com/`

### Category

ads

### Describe the issue

EasyList blocks `.top-ad-wrapper` but in Firefox when you scroll down the page, the element style changes and for some reason causes the page to jump down when you scroll past the header (even though the element is hidden).

This can be fixed by removing the ad completely from the HTML:

`nybooks.com##^.top-ad-wrapper`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/110956608/186998053-2776dbe8-0048-4ea9-a652-f786042d93ac.mov

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 86872
  cosmetic: 80899
  scriptlet: 19987
  html: 741
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1942-0, 22h.28m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 22h.28m
    adguard-spyware-url: 725-98, 12m
    block-lan: 43-0, 12m
    fanboy-cookiemonster: 40672-88, 15m
  default: 
    user-filters: 833-0, never
    ublock-filters: 33186-49, 3m
    ublock-badware: 4166-0, 3m
    ublock-privacy: 263-2, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1852-1, 3m
    ublock-quick-fixes: 397-0, 3m
    easylist: 67502-619, 16m
    easyprivacy: 27436-579, 16m
    urlhaus-1: 7355-0, 22h.28m
    plowe-0: 3633-3, 11m
filterset (user): [array of 174 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 151 ms (selfie)
  maxAssetCacheWait: 484 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bugherd.com: 2
    cookiebot.com: 2
    googletagmanager.com: 1
    wp.com: 2
```
</details>

**Comment by Yuki2718** [comment]
Not only Firefox
@ryanbr Probably the rule should be removed, no fix for ABP.
