### ISSUE TITLE
expressvpn.com: breakage

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#14555]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.expressvpn.com/`

### Describe the issue

Click on `Need help? Chat with us!` don't open live chat.

Based on Alex 302 words I checked this on uBo: https://github.com/AdguardTeam/Scriptlets/issues/233

### Screenshot(s)

N/A

### uBlock Origin version

1.44.1b2

### Browser name and version

Firefox 104

### Settings

- enabled uBO Annoyances
- enabled POL-0 and POL-2

### Notes

EP may need add:

`@@||googletagmanager.com/gtm.js$domain=expressvpn.com`

**Comment by Yuki2718** [comment]
Apparently uBO doesn't have the problem.

**Comment by Infrastructural** [comment]
@Yuki2718 So could it be used with `$important`?

**Comment by Yuki2718** [comment]
No, GTM should be allowed.

**Comment by krystian3w** [comment]
So this can be reveted: https://github.com/easylist/easylist/commit/88f27b059af92d06a91a52dd5ca670867586aaec

**Comment by Yuki2718** [comment]
> So this can be reveted

Again, no. The GTM exception is needed.
