### ISSUE TITLE
vili.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1455]
### URL(s) where the issue occurs
`http://vili.io`

### Describe the issue
Displays an anti-adblock message.

### Screenshot(s)
![vili io anti-adblock](https://user-images.githubusercontent.com/29117662/35729763-9bfbc09c-07c4-11e8-8efc-4a37549f16a9.PNG)

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.14.25.101 (Nano Adblocker 1.0.0.28)

### Settings
Default.

### Notes
Anti-adblock.

**Comment by mapx-** [comment]
Even disabling uBo I still get that message.

**Comment by SkeletalDemise** [comment]
Yes, it does that for me too.
