### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by Pudgezxc** [uBlockOrigin/uAssets#14557]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vk.com/feed`

### Category

breakage

### Describe the issue

there is an extension for vk, Vk styles, and when you turn on an ad blocker, the background (which is set through the extension) becomes black and the font changes back (it is also through the extension)

### Screenshot(s)

https://imgur.com/KRxHOIK                                      This is how it should be: https://imgur.com/SL2TxRv

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 105035
  cosmetic: 66511
  scriptlet: 35798
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1483-237, never
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23936-26, 2h.3m
  default: 
    user-filters: 0-0, never
    RUS-0: 42043-109, 2h.57m
    easylist: 67502-74, 2h.54m
    easyprivacy: 27436-225, 2h.53m
    plowe-0: 3634-781, 2h.52m
    ublock-abuse: 76-2, 2h.50m
    ublock-badware: 4162-96, 2h.48m
    ublock-filters: 32487-2949, 2h.47m
    ublock-privacy: 241-3, 2h.46m
    ublock-quick-fixes: 394-6, 2h.45m
    ublock-unbreak: 1839-42, 2h.44m
    urlhaus-1: 6830-0, 2h.43m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 365 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    vk.com: 4
    mail.ru: 3
    mycdn.me: 2
    tns-counter.ru: 9
    vk-portal.net: 1
    yandex.ru: 2
    yastatic.net: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
It looks like it's a conflict with some other extension. All questions related to this domain are discussed here: https://forums.lanik.us/viewtopic.php?t=28751

**Comment by MasterKia** [comment]
> there is an extension for vk, Vk styles

Which extension?
