### ISSUE TITLE
ph.ontools.net: [detection]

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#14556]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ph.ontools.net/2022/05/1.html`

### Category

[unknown]

### Describe the issue

Adblock detected on `https://ph.ontools.net/2022/05/1.html#?o=60553a331ada89fae11624dae8b0c897fccfdef773649945078d3390540f20e922281b396f0fce72`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 81922
  cosmetic: 43516
  scriptlet: 17718
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67552-51, 10h.6m
    easyprivacy: 27436-126, 10h.6m
    plowe-0: 3633-776, 10h.6m
    ublock-abuse: 76-0, 10h.6m
    ublock-badware: 4162-96, 10h.6m
    ublock-filters: 32487-121, 10h.6m
    ublock-privacy: 241-3, 10h.6m
    ublock-quick-fixes: 394-5, 10h.6m
    ublock-unbreak: 1839-41, 10h.6m
    urlhaus-1: 6711-0, 10h.6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 492 ms (selfie)
  maxAssetCacheWait: 285 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googlesyndication.com: 1
```
</details>

**Comment by Infrastructural** [comment]
`ph.ontools.net##+js(aopr, this._options.bait)`

**Comment by ghajini** [comment]
provide the original link from where you land on this page

**Comment by Infrastructural** [comment]
> Adblock detected on `https://ph.ontools.net/2022/05/1.html#?o=60553a331ada89fae11624dae8b0c897fccfdef773649945078d3390540f20e922281b396f0fce72`

Is there any detection on this as of now? @ghajini

**Comment by ghajini** [comment]
i can't see any,but pic might be different when navigating from original link, thatswhy asked to provide one

**Comment by Infrastructural** [comment]
Did you test on mobile?

**Comment by ghajini** [comment]
all browsers

**Comment by Cyberavater** [comment]
Closing as I can't provide any way to reproduce it.

**Comment by Cyberavater** [comment]
Not possible at this point, you can close this issue if it's not feasible
without it.
