### ISSUE TITLE
hbzb111.com: ads

### ISSUE THREAD

**Issue by nptiger** [uBlockOrigin/uAssets#14550]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hbzb111.com/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 100372
  cosmetic: 53806
  scriptlet: 17833
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 29006-90, 1m
    easylist: 67562-76, 1m
    easyprivacy: 27436-150, 1m
    plowe-0: 3633-778, now
    ublock-abuse: 76-0, now
    ublock-badware: 4162-96, now
    ublock-filters: 32487-140, now
    ublock-privacy: 241-3, now
    ublock-quick-fixes: 394-5, now
    ublock-unbreak: 1839-42, now
    urlhaus-1: 6711-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 351 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    baidu.com: 2
    cnzz.com: 1
```
</details>

**Comment by Yuki2718** [comment]
@cjx82630 Accessible only from Taiwan IP, `||hbzb111.com/api/advert/` works on my side.

**Comment by Yuki2718** [comment]
They are self-promotion, will address in Annoyances filters.
