### ISSUE TITLE
udemycourses.org: detection

### ISSUE THREAD

**Issue by YogaGlace** [uBlockOrigin/uAssets#14567]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://udemycourses.org/download/flutter-dart-the-complete-guide-2022-edition/`

### Category

detection

### Describe the issue

Detects uBO when I click "Download Now"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 102
filterset (summary): 
  network: 212498
  cosmetic: 215760
  scriptlet: 37986
  html: 745
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 67133-5520, 4m
    adguard-spyware: 25440-925, 4m
    adguard-spyware-url: 725-2, 4m
    block-lan: 43-0, 4m
    curben-phishing: 72874-9, 3m
    curben-pup: 188-0, 3m
    adguard-annoyance: 56782-5034, 3m
    adguard-social: 18316-1061, 3m
    fanboy-thirdparty_social: 69-0, 3m
    fanboy-annoyance: 80143-64184, 3m
    fanboy-cookiemonster: 40672-134, 3m
    fanboy-social: 23306-28, 3m
    ublock-annoyances: 4577-4, 3m
    dpollock-0: 11387-482, 3m
  default: 
    user-filters: 7-0, never
    ublock-filters: 33302-77, 4m
    ublock-badware: 4165-0, 4m
    ublock-privacy: 263-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1859-1, 4m
    ublock-quick-fixes: 398-0, 4m
    adguard-mobile: 8161-189, 4m
    easylist: 67231-966, 4m
    easyprivacy: 27437-9405, 4m
    urlhaus-1: 7028-0, 3m
    plowe-0: 3634-3, 3m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2939 ms (selfie)
  maxAssetCacheWait: 3382 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    a-ads.com: 1
    inklinkor.com: 1
    profitablecpmgate.com: 6
```
</details>

**Comment by MasterKia** [comment]
@ghajini Anti-adb nag:
```
downloadudemy.com##.text.notice
downloadudemy.com##.wp-block-quote
```

Ads:
(Maybe) `downloadudemy.com##p:not(:has-text(Click))`

**Comment by MasterKia** [comment]
I can't "Get Code" for the "INPUT CODE( Link Of Red Frame)" section.

![Screenshot_20220828_151936](https://user-images.githubusercontent.com/17685483/187070246-5b68a5c0-f52d-4f66-8354-e85aedbf50c3.png)

**Comment by ghajini** [comment]
checked already, even disabling ubo ,i don't get **get code**

**Comment by MasterKia** [comment]
So the site is broken.

**Comment by ghajini** [comment]
@YogaGlace are you able to use site functions
