### ISSUE TITLE
i find ads in flipkart.com

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uAssets#14565]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

1.`https://www.flipkart.com/televisions/~cs-0hb2nbuaq2/pr?sid=ckf%2Cczl&collection-tab-name=4K+UHD+TVs&p%5B%5D=facets.availability%255B%255D%3DExclude%2BOut%2Bof%2BStock&param=hjhc&otracker=hp_bannerads_2_2.bannerAdCard.BANNERADS_TV-APPHPW-BBD-AUG-4k_VWKGBH3OT8B0`

2.`https://www.flipkart.com/metronaut-flipkart-men-checkered-casual-multicolor-shirt/p/itma6111430dec38?pid=SHTG8U3YGFEC6QUG&lid=LSTSHTG8U3YGFEC6QUGZBI5F6&marketplace=FLIPKART&fm=factBasedRecommendation%2FrecentlyViewed&iid=R%3Arv%3Bpt%3App%3Buid%3Ad8b583ab-26af-11ed-a4df-e9dadc723d97%3B.SHTG8U3YGFEC6QUG&ppt=pp&ppn=pp&ssid=8jacasbdwquzwidc1661677213607&otracker=pp_reco_Recently%2BViewed_3_38.productCard.RECENTLY_VIEWED_METRONAUT%2Bby%2BFlipkart%2BMen%2BCheckered%2BCasual%2BMulticolor%2BShirt_SHTG8U3YGFEC6QUG_factBasedRecommendation%2FrecentlyViewed_2&otracker1=pp_reco_PINNED_factBasedRecommendation%2FrecentlyViewed_Recently%2BViewed_DESKTOP_HORIZONTAL_productCard_cc_3_NA_view-all&cid=SHTG8U3YGFEC6QUG`

3.`https://www.flipkart.com/wildcraft-volga-nx-hiking-trekking-shoes-men/p/itm565b48b128bd2?pid=SHOG4HG3TBYPM5MK&lid=LSTSHOG4HG3TBYPM5MKMLQXV9&marketplace=FLIPKART&fm=factBasedRecommendation%2FrecentlyViewed&iid=R%3Arv%3Bpt%3App%3Buid%3Adef53eef-26af-11ed-933c-9f0f7090db9e%3B.SHOG4HG3TBYPM5MK&ppt=pp&ppn=pp&ssid=8jacasbdwquzwidc1661677213607&otracker=pp_reco_Recently%2BViewed_3_38.productCard.RECENTLY_VIEWED_Wildcraft%2BVolga%2BNX%2BHiking%2B%2526%2BTrekking%2BShoes%2BFor%2BMen_SHOG4HG3TBYPM5MK_factBasedRecommendation%2FrecentlyViewed_2&otracker1=pp_reco_PINNED_factBasedRecommendation%2FrecentlyViewed_Recently%2BViewed_DESKTOP_HORIZONTAL_productCard_cc_3_NA_view-all&cid=SHOG4HG3TBYPM5MK`

### Describe the issue

in flipkart.com i find ads i have tried in 2devices and pc also this was same after surfing for a while you will find ads in product page above the product page bellow suggested products you will find ads

### Screenshot(s)

https://user-images.githubusercontent.com/108695843/187066277-dd9e77cd-4da7-4e46-902d-bad512e94b9f.png

https://user-images.githubusercontent.com/108695843/187066279-02629fa8-6877-4ef0-ae87-e534b366255d.jpeg

https://user-images.githubusercontent.com/108695843/187066280-854e0696-4988-4218-bd9f-61c944a33729.jpeg

https://user-images.githubusercontent.com/108695843/187066447-2b0cf130-2939-4b65-ad33-e8b6839ff5aa.png

https://user-images.githubusercontent.com/108695843/187066281-fa9e47e9-7d01-46f8-8b07-dde5089dbad8.png

https://user-images.githubusercontent.com/108695843/187066453-e17dd268-1bb9-46cd-a5a6-f4a1b02534b5.png

all of them are taken from desktop and mobile

### uBlock Origin version
1.44.0

### Browser name and version

Firefox 104

### Settings

no changes

### Notes
https://github.com/uBlockOrigin/uBlock-issues/issues/2231#issuecomment-1229225451

**Comment by Infrastructural** [comment]
Are those considered self-promotion?

**Comment by MasterKia** [comment]
[This one](https://user-images.githubusercontent.com/108695843/187066281-fa9e47e9-7d01-46f8-8b07-dde5089dbad8.png) seems like paid advertising of product, on top of my head I think we block those in amazon.

**Comment by MasterKia** [comment]
[This one](https://user-images.githubusercontent.com/108695843/187066281-fa9e47e9-7d01-46f8-8b07-dde5089dbad8.png) seems like paid advertising of product, I think we block those in amazon.

**Comment by MasterKia** [comment]
It seems like paid advertising of product, I think we block those in amazon.

**Comment by MasterKia** [comment]
This removes paid ads products:
`flipkart.com##div[data-id][style="width: 25%;"]:has(span:has-text(Ad)):remove()`

But it leaves empty blank space, `:upward(1)` doesn't fix it because each row is isolated from another.

<details>
<summary>Example link</summary>

`https://www.flipkart.com/womens-footwear/~sports-casual-shoes/pr?sid=osp%2Ciko&p%5B%5D=facets.discount_range_v1%255B%255D%3D50%2525%2Bor%2Bmore&sort=popularity&p%5B%5D=facets.brand%255B%255D%3DADIDAS&p%5B%5D=facets.brand%255B%255D%3DSkechers&p%5B%5D=facets.brand%255B%255D%3DREEBOK&p%5B%5D=facets.brand%255B%255D%3DUnder%2BArmour&p%5B%5D=facets.brand%255B%255D%3DADIDAS%2BORIGINALS&p%5B%5D=facets.brand%255B%255D%3DADIDAS%2BNEO&p%5B%5D=facets.brand%255B%255D%3DAdidas%2BCore&p%5B%5D=facets.brand%255B%255D%3DREEBOK%2BCLASSICS&p%5B%5D=facets.brand%255B%255D%3DATHLETIC%2BWORKS&p%5B%5D=facets.brand%255B%255D%3DPUMA&p%5B%5D=facets.brand%255B%255D%3DFILA&p%5B%5D=facets.brand%255B%255D%3Dasics&p%5B%5D=facets.brand%255B%255D%3DNIKE&p%5B%5D=facets.brand%255B%255D%3DLOTTO&p%5B%5D=facets.brand%255B%255D%3DPOWER&p%5B%5D=facets.brand%255B%255D%3DMarc%2BLoire&hpid=sYEZUABlgIeKEXiNkztwZqp7_Hsxr70nj65vMAAFKlc%3D&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJNaW4gNTAlIE9mZiJdLCJ2YWx1ZVR5cGUiOiJNVUxUSV9WQUxVRUQifX0sImhlcm9QaWQiOnsic2luZ2xlVmFsdWVBdHRyaWJ1dGUiOnsia2V5IjoiaGVyb1BpZCIsImluZmVyZW5jZVR5cGUiOiJQSUQiLCJ2YWx1ZSI6IlNIT0Y4SFlNOTNHS0NQR0QiLCJ2YWx1ZVR5cGUiOiJTSU5HTEVfVkFMVUVEIn19LCJ0aXRsZSI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ0aXRsZSIsImluZmVyZW5jZVR5cGUiOiJUSVRMRSIsInZhbHVlcyI6WyJBRElEQVMsIFBVTUEgJiBtb3JlIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fX19fQ%3D%3D&fm=neo%2Fmerchandising&iid=M_e7ff34fa-7255-48b5-a306-adafe92fc699_7.9NFWS5S2MUZH&ssid=sezuiwiltc2wx5341661704657000&otracker=hp_omu_Today%2527s%2BFashion%2BDeals_1_7.dealCard.OMU_9NFWS5S2MUZH_5&otracker1=hp_omu_PINNED_neo%2Fmerchandising_Today%2527s%2BFashion%2BDeals_NA_dealCard_cc_1_NA_view-all_5&cid=9NFWS5S2MUZH`

</details>

**Comment by holequantum** [comment]
> It seems like paid advertising of product, I think we block those in amazon.

Yes you are right i never find anything like that in amazon. Or ebay


> Are those considered self-promotion?

I don't know

**Comment by holequantum** [comment]
> 

Can you explain what does it mean how can i block it i find it is a issue in firefox 105 beta and chromium also.
And manually turned on all blocklist but does not do any better and by default blocklist also was same. So i think block list need to be updated so it can rectify that ads and stuff.

**Comment by MasterKia** [comment]
@holequantum You can copy the filter sent here https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1229503171 and go to uBlock Origin settings => My filters

And paste it there.

**Comment by ghajini** [comment]
these are self promotion as far as i know

**Comment by MasterKia** [comment]
The site lets you become "a seller" and "sell online".
`https://seller.flipkart.com/sell-online/`

**Comment by holequantum** [comment]
> flipkart.com##div[data-id][style="width: 25%;"]:has(span:has-text(Ad))

i still find ads
https://www.flipkart.com/new-blue-eyes-sport-bra-seemlaes-3-women-sports-non-padded/p/itm7ce5ad5f509cd?pid=BRAFHZ2CVVQ4C7YM&lid=LSTBRAFHZ2CVVQ4C7YMFSKUFA&marketplace=FLIPKART&fm=factBasedRecommendation%2FrecentlyViewed&iid=R%3Arv%3Bpt%3App%3Buid%3A29fbf475-2778-11ed-9080-e10f5b28fc70%3B.BRAFHZ2CVVQ4C7YM&ppt=pp&ppn=pp&ssid=p8cia9k7fnpujke81661763241152&otracker=pp_reco_Recently%2BViewed_2_38.productCard.RECENTLY_VIEWED_new%2Bblue%2Beyes%2Bsport%2Bbra%2Bseemlaes%2B-3%2BWomen%2BSports%2BNon%2BPadded%2BBra_BRAFHZ2CVVQ4C7YM_factBasedRecommendation%2FrecentlyViewed_1&otracker1=pp_reco_PINNED_factBasedRecommendation
![Screenshot from 2022-08-29 14-23-24](https://user-images.githubusercontent.com/108695843/187164200-ae2704e3-efbe-4e62-b091-8cd1ac53a334.png)
%2FrecentlyViewed_Recently%2BViewed_DESKTOP_HORIZONTAL_productCard_cc_2_NA_view-all&cid=BRAFHZ2CVVQ4C7YM

**Comment by holequantum** [comment]
https://www.flipkart.com/search?q=laptop&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off
![Screenshot from 2022-08-29 14-29-18](https://user-images.githubusercontent.com/108695843/187164611-18483315-ec7c-4da8-82e8-6c238cef14bf.png)

**Comment by holequantum** [comment]
> The site lets you become "a seller" and "sell online". `https://seller.flipkart.com/sell-online/`

surely it blocked some but not all not upto the mark of marge in to main

**Comment by holequantum** [comment]
https://www.flipkart.com/bata-varys-oxford-men/p/itme55bcd3a4172a?pid=SHOGEHMATGVA27GV&lid=LSTSHOGEHMATGVA27GVTBUS74&marketplace=FLIPKART&fm=factBasedRecommendation%2FrecentlyViewed&iid=R%3Arv%3Bpt%3App%3Buid%3A29fbf475-2778-11ed-9080-e10f5b28fc70%3B.SHOGEHMATGVA27GV&ppt=pp&ppn=pp&ssid=p8cia9k7fnpujke81661763241152&otracker=pp_reco_Recently%2BViewed_6_38.productCard.RECENTLY_VIEWED_Bata%2BVarys%2BOxford%2BOxford%2BFor%2BMen_SHOGEHMATGVA27GV_factBasedRecommendation%2FrecentlyViewed_5&otracker1=pp_reco_PINNED_factBasedRecommendation%2FrecentlyViewed_Recently%2BViewed_DESKTOP_HORIZONTAL_productCard_cc_6_NA_view-all&cid=SHOGEHMATGVA27GV


![Screenshot from 2022-08-29 14-33-42](https://user-images.githubusercontent.com/108695843/187165443-3dd4396a-a45c-4f80-ac9c-7dc088f288d2.png)

**Comment by MasterKia** [comment]
@holequantum Remove the previous filter I gave you and test:
`flipkart.com##span:has-text(/^Ad$/):upward(div[style])`

**Comment by holequantum** [comment]
It was better seems like but here are more
https://www.flipkart.com/mens-footwear/pr?sid=osp%2Ccil&p%5B%5D=facets.brand%255B%255D%3DAadi&p%5B%5D=facets.brand%255B%255D%3DBata&p%5B%5D=facets.brand%255B%255D%3DRED%2BTAPE&p%5B%5D=facets.brand%255B%255D%3DKraasa&p%5B%5D=facets.brand%255B%255D%3DRED%2BCHIEF&p%5B%5D=facets.brand%255B%255D%3DChevit&p%5B%5D=facets.brand%255B%255D%3DLayasa&p%5B%5D=facets.brand%255B%255D%3DBRUTON&p%5B%5D=facets.brand%255B%255D%3DT-ROCK&p%5B%5D=facets.brand%255B%255D%3DRobbie%2Bjones&p%5B%5D=facets.brand%255B%255D%3DPROVOGUE&p%5B%5D=facets.brand%255B%255D%3DESSENCE&p%5B%5D=facets.brand%255B%255D%3DMILESWALKER&p%5B%5D=facets.brand%255B%255D%3DORICUM&p%5B%5D=facets.brand%255B%255D%3DArivo&p%5B%5D=facets.brand%255B%255D%3DTR&p%5B%5D=facets.brand%255B%255D%3DK%2B%2527%2BFootlance&p%5B%5D=facets.brand%255B%255D%3DVellinto&p%5B%5D=facets.brand%255B%255D%3DWorld%2BWear%2BFootwear&p%5B%5D=facets.brand%255B%255D%3DU.S.%2BPOLO%2BASSN.&p%5B%5D=facets.brand%255B%255D%3DLEE%2BCOOPER&p%5B%5D=facets.brand%255B%255D%3Dbacca%2Bbucci&p%5B%5D=facets.brand%255B%255D%3DAxter&p%5B%5D=facets.brand%255B%255D%3Drestinfoot&p%5B%5D=facets.brand%255B%255D%3DHOTSTYLE&p%5B%5D=facets.brand%255B%255D%3DAbsolute%2Bcomfort&p%5B%5D=facets.brand%255B%255D%3DPery%2Bpao&p%5B%5D=facets.brand%255B%255D%3DMonoction&p%5B%5D=facets.brand%255B%255D%3DHUSH%2BPUPPIES&p%5B%5D=facets.brand%255B%255D%3DBond%2BStreet%2BBy%2BRed%2BTape&p%5B%5D=facets.brand%255B%255D%3DAlfiyo&p%5B%5D=facets.brand%255B%255D%3DACTION&p%5B%5D=facets.brand%255B%255D%3DADIDAS%2BORIGINALS&p%5B%5D=facets.brand%255B%255D%3DROCKFIELD&p%5B%5D=facets.brand%255B%255D%3DREEBOK%2BCLASSICS&p%5B%5D=facets.brand%255B%255D%3Dbluemaker&p%5B%5D=facets.brand%255B%255D%3DTRYME&p%5B%5D=facets.brand%255B%255D%3DZixer&p%5B%5D=facets.brand%255B%255D%3D3SIX5&p%5B%5D=facets.brand%255B%255D%3DMartin%2BScott&p%5B%5D=facets.brand%255B%255D%3DKzaara&p%5B%5D=facets.brand%255B%255D%3DFzzirok&p%5B%5D=facets.brand%255B%255D%3DNumenzo&p%5B%5D=facets.brand%255B%255D%3DK%2527%2BFootlance&p%5B%5D=facets.brand%255B%255D%3DDeals4you&p%5B%5D=facets.brand%255B%255D%3DFoot%2BPrint&p%5B%5D=facets.brand%255B%255D%3DUnistar&p%5B%5D=facets.brand%255B%255D%3DMagnolia&p%5B%5D=facets.brand%255B%255D%3DAfashion&p%5B%5D=facets.brand%255B%255D%3DiD&p%5B%5D=facets.brand%255B%255D%3DTying&p%5B%5D=facets.brand%255B%255D%3DWOODLAND&p%5B%5D=facets.brand%255B%255D%3DKnoos&p%5B%5D=facets.brand%255B%255D%3DSHOEFLY&p%5B%5D=facets.brand%255B%255D%3DSCATCHITE&p%5B%5D=facets.brand%255B%255D%3DNayka&p%5B%5D=facets.brand%255B%255D%3DD-SNEAKERZ&p%5B%5D=facets.brand%255B%255D%3Dadzon&p%5B%5D=facets.brand%255B%255D%3DShoes%2BBank&p%5B%5D=facets.brand%255B%255D%3DPara%2BCommando&p%5B%5D=facets.brand%255B%255D%3DEnglewood&p%5B%5D=facets.brand%255B%255D%3DBIRDE&p%5B%5D=facets.brand%255B%255D%3DCLYMB&p%5B%5D=facets.price_range.from%3D199&p%5B%5D=facets.price_range.to%3DMax&param=7753232&offer=nb%3Amp%3A072179c425%2Cnb%3Amp%3A07cfe9ca25&hpid=GLrBhHOlEWgq77YJT8nc_qp7_Hsxr70nj65vMAAFKlc%3D&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJGcm9tIOKCuTE0OStFeHRyYTUlb2ZmIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fSwiaGVyb1BpZCI6eyJzaW5nbGVWYWx1ZUF0dHJpYnV0ZSI6eyJrZXkiOiJoZXJvUGlkIiwiaW5mZXJlbmNlVHlwZSI6IlBJRCIsInZhbHVlIjoiU0hPR0VETko1NlBQUFlCNCIsInZhbHVlVHlwZSI6IlNJTkdMRV9WQUxVRUQifX0sInRpdGxlIjp7Im11bHRpVmFsdWVkQXR0cmlidXRlIjp7ImtleSI6InRpdGxlIiwiaW5mZXJlbmNlVHlwZSI6IlRJVExFIiwidmFsdWVzIjpbIkJydXRvbiwgQmF0YSwgQmlyZGUuLi4iXSwidmFsdWVUeXBlIjoiTVVMVElfVkFMVUVEIn19fX19&pageUID=1661769914841


https://www.flipkart.com/yora-women-sports-lightly-padded-bra/p/itm7cc645f4671a0?pid=BRAFVENPBD5RZHBT&lid=LSTBRAFVENPBD5RZHBTJVARTH&marketplace=FLIPKART&pageUID=1661770042255


Above banner ads
![Screenshot_20220829-161520~2](https://user-images.githubusercontent.com/108695843/187184813-1087a360-e74f-464f-a512-a7de15e45e45.png)
![Screenshot_20220829-161533~2](https://user-images.githubusercontent.com/108695843/187184831-5dfd86e5-652d-42b8-865b-34417977f330.png)

**Comment by holequantum** [comment]
https://www.flipkart.com/wildcraft-volga-nx-hiking-trekking-shoes-men/p/itm565b48b128bd2?pid=SHOG4HG3TBYPM5MK&pageUID=1661770176058

![Screenshot_20220829-161940~2](https://user-images.githubusercontent.com/108695843/187185088-5309eaed-3921-4391-ac9a-a3198868ee9b.png)

**Comment by holequantum** [comment]
rukminim1.flixcart.com
2.rome.api.flipkart.com
www.flipkart.com

**Comment by MasterKia** [comment]
@holequantum Test on mobile:

`flipkart.com##div[dir]:has-text(/^AD$/):upward(div[style])`

**Comment by MasterKia** [comment]
I can't reproduce this:
https://user-images.githubusercontent.com/108695843/187185088-5309eaed-3921-4391-ac9a-a3198868ee9b.png

**Comment by holequantum** [comment]
> I can't reproduce this: https://user-images.githubusercontent.com/108695843/187185088-5309eaed-3921-4391-ac9a-a3198868ee9b.png

Yes i also can't
In incognito you can't see them you need to login first

**Comment by holequantum** [comment]
All ads are coming from this `static-assets-web.flixcart.com` why can't we terget that

**Comment by MasterKia** [comment]
What ads is left behind other than the one that needs login?

**Comment by MasterKia** [comment]
> you need to login first

Registering requires phone number, I don't have Indian phone number.

What ads is left behind other than the one that needs login?

**Comment by holequantum** [comment]
> I can't reproduce this: https://user-images.githubusercontent.com/108695843/187185088-5309eaed-3921-4391-ac9a-a3198868ee9b.png

https://www.flipkart.com/world-wear-footwear-stylish-casual-walking-comfortable-sports-running-shoes-men/p/itmeb140b0cd6900?pid=SHOFZ6XXSFHZGAGZ&lid=LSTSHOFZ6XXSFHZGAGZUUK2MM&marketplace=FLIPKART&q=shoe&store=osp&srno=s_1_7&otracker=search&otracker1=search&fm=Search&iid=77367d1a-db23-4921-803b-3004131580c5.SHOFZ6XXSFHZGAGZ.SEARCH&ppt=sp&ppn=sp&ssid=uhjh640d967e9ybk1661798929890&qH=d8a48e3f0e1322d5

scroll down and see there a part called similar products

**Comment by MasterKia** [comment]
> a part called similar products

This filter removes ads in similar products.
https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1230003897

**Comment by MasterKia** [comment]
Did you verify this?
https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1230700380

**Comment by holequantum** [comment]
yes just done it yes does that was not added on my pc it was added in my phone so i missed

**Comment by MasterKia** [comment]
If you send login info, I can take a look.
Reddit: `FreeLibre`

**Comment by ghajini** [comment]
@MasterKia there's a website `https://sms24.me/en/countries/in/` where you can do what is required to login

**Comment by MasterKia** [comment]
I thought only dumb websites allow virtual numbers

**Comment by holequantum** [comment]
> @holequantum Remove the previous filter I gave you and test: `flipkart.com##span:has-text(/^Ad$/):upward(div[style])`
> 
> I tested on all the page you sent.

do i need to add this also along with


> @holequantum Test on mobile:
> 
> `flipkart.com##div[dir]:has-text(/^AD$/):upward(div[style])`
> 
> I'm afraid nothing can be done about the blank spots (maybe someone can fix them by style rules).

this??

**Comment by MasterKia** [comment]
This:

```
flipkart.com##span:has-text(/^Ad$/):upward(div[style])
!#if env_mobile
flipkart.com##div[dir]:has-text(/^AD$/):upward(div[style])
!#endif
```

**Comment by ghajini** [comment]
@MasterKia this work

**Comment by holequantum** [comment]
![Screenshot_20220830-004028~2](https://user-images.githubusercontent.com/108695843/187279525-e31e0869-9e99-4bc1-83b7-25d76565738b.png)

**Comment by MasterKia** [comment]
@ghajini I tried 4 numbers, all of them already registered and I got not "OTP code".

**Comment by ghajini** [comment]
i tried https://sms24.me/en/numbers/917379932768/
may be use indian ip as well
check otp at bottom 
![image](https://user-images.githubusercontent.com/20338483/187280481-9b7628b5-d17a-4e84-bed5-a00663ff110c.png)

**Comment by MasterKia** [comment]
I'm in.

**Comment by ghajini** [comment]
& try `https://addons.mozilla.org/en-US/firefox/addon/mobile-view-switcher/` for mobile

**Comment by MasterKia** [comment]
That's much more minimal compared to https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/, thanks.

**Comment by ghajini** [comment]
yeah habited to that addon for mobile sites

**Comment by MasterKia** [comment]
`<div style="height:100%;width:100%" data-observerid-255f5f...="..."">`

@ghajini uBO can't find div by other attributes, right?
`##div[/data-observerid../]` won't work because no regex in cosmetic filters.

**Comment by ghajini** [comment]
@gwarser @okiehsch https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1230779771

**Comment by holequantum** [comment]
> @holequantum Test on mobile:
> 
> `flipkart.com##div[dir]:has-text(/^AD$/):upward(div[style])`

@ghajini  hey you missed this kindly marge it also

**Comment by gwarser** [comment]
https://stackoverflow.com/questions/8308328/xpath-to-find-attributes-where-the-name-starts-with-a-given-value ?

**Comment by MasterKia** [comment]
@holequantum Test:
```
flipkart.com##span:has-text(/^Ad$/):upward(div[style])
!#if env_mobile
flipkart.com##div[dir]:has-text(/^AD$/):upward(div[style]).
flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div[style])
!#endif

```

**Comment by MasterKia** [comment]
@holequantum Force update your lists.

**Comment by holequantum** [comment]
Yes i have force update
It worked but the above ads are still here

**Comment by MasterKia** [comment]
What above ads?

**Comment by holequantum** [comment]
https://www.flipkart.com/lenovo-ideapad-3-core-i3-10th-gen-8-gb-256-gb-ssd-windows-11-home-15iml05-thin-light-laptop/p/itmd1871bfcde765?pid=COMG6AKVAHWTHAQG&lid=LSTCOMG6AKVAHWTHAQGXUICJF&marketplace=FLIPKART&q=Laptop&store=6bo%2Fb5g&pageUID=1661807802728

**Comment by holequantum** [comment]
> What above ads?

To see them you have to logged in

**Comment by holequantum** [comment]
Just above the verified ratings

**Comment by MasterKia** [comment]
Test:
`flipkart.com##div[style*="width:24px;height:20px;"]:upward(div)`

**Comment by holequantum** [comment]
> 

Yes it seems like blocked but refreshing the page again and again sometimes ot come back

**Comment by MasterKia** [comment]
> refreshing the page again and again sometimes ot come back

Test:
`flipkart.com##div[style*="width:24px;height:20px;"]:upward(div):remove()`

**Comment by MasterKia** [comment]
That filter worked fine for me in mobile, but you can test each of these and say which one works.


A) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div)`

B) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div)`

C) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div[style])`

D) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src]):upward(div)`

**Comment by holequantum** [comment]
Let me test

**Comment by holequantum** [comment]
> That filter worked fine for me in mobile, but you can test each of these and say which one works.
> 
> A) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div)`
> 
> B) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div)`
> 
> C) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div[style])`
> 
> D) `flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src]):upward(div)`

Can you test
www.flipkart.com##.r-knv0ih.r-1kb76zh.r-1jkjb.r-5oul0u.r-eqz5dr.r-13awgt0.css-1dbjc4n > div

It worked for me.

**Comment by holequantum** [comment]
-Scroll down and find this ad also
> 
> `https://www.flipkart.com/hp-15s-ryzen-3-dual-core-3250u-8-gb-1-tb-hdd-256-gb-ssd-windows-10-home-15s-gr0012au-laptop/p/itm9e1f8deeed35f?marketplace=FLIPKART&q=Laptop`
> 
> https://user-images.githubusercontent.com/108695843/187301450-a66a1c88-7736-4cc3-ab68-ed9aeeb28b2c.png

It can block all in page that i have shared screenshot can you test it i have tested and i find positive.
`www.flipkart.com##.r-ttdzmv.r-1pyaxff.r-1m04atk.r-kzbkwu.r-1wtj0ep.r-18u37iz.css-1dbjc4n`

**Comment by ghajini** [comment]
well you mind to give feedback on https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1230887706

stop unnecessary replies & give all urls in main post only

**Comment by MasterKia** [comment]
I've updated the filters, make sure you test A to F.

**Comment by holequantum** [comment]
> I've updated the filters, make sure you test A to F one by one.

flipkart.com##div[style*="width:24px;height:20px;"]:upward(div)
This one was better but does not block the ads that appears in between


> -Scroll down and find this ad also
> 
> > `https://www.flipkart.com/hp-15s-ryzen-3-dual-core-3250u-8-gb-1-tb-hdd-256-gb-ssd-windows-10-home-15s-gr0012au-laptop/p/itm9e1f8deeed35f?marketplace=FLIPKART&q=Laptop`
> > https://user-images.githubusercontent.com/108695843/187301450-a66a1c88-7736-4cc3-ab68-ed9aeeb28b2c.png
> 
> It can block all in page that i have shared screenshot can you test it i have tested and i find positive. `www.flipkart.com##.r-ttdzmv.r-1pyaxff.r-1m04atk.r-kzbkwu.r-1wtj0ep.r-18u37iz.css-1dbjc4n`

In this

**Comment by MasterKia** [comment]
Do I need to be logged in to see this ad?

**Comment by MasterKia** [comment]
> This one was better

Are you sure filter "A" doesn't work?

**Comment by holequantum** [comment]
> Do I need to be logged in to see this ad?

I am always logged in. O think you have to logged in to see ads maybe.

**Comment by holequantum** [comment]
> > This one was better
> 
> Are you sure filter "A" doesn't work?

Let me check again

**Comment by holequantum** [comment]
For A i just checked
`flipkart.com##div[style*="width:24px;height:20px;"]:has(img[src*="/promos/"]):upward(div[style])`
It does block some banner ads but if you open another peoduct from similar peoduct list i find ads appear again and if i reload that page ads disappears.

**Comment by holequantum** [comment]
`flipkart.com##div[style*="width:24px;height:20px;"]:upward(div)`
For this juat search for shoe and open a product and you will see the ads but reloading the page makes ads disappear

**Comment by holequantum** [comment]
I find this actually works far better
1. www.flipkart.com##.r-knv0ih.r-1kb76zh.r-1jkjb.r-5oul0u.r-eqz5dr.r-13awgt0.css-1dbjc4n > div
2. www.flipkart.com##.r-ttdzmv.r-1pyaxff.r-1m04atk.r-kzbkwu.r-1wtj0ep.r-18u37iz.css-1dbjc4n

**Comment by MasterKia** [comment]
> I find this actually works far better 

These are based on randomly generated class names and will stop working after a while.

**Comment by holequantum** [comment]
https://www.flipkart.com/search?q=Shoe&marketplace=FLIPKART&pageUID=1661861231072


Ads you have to login first
![Screenshot_20220830-173825~3](https://user-images.githubusercontent.com/108695843/187432967-a0a836e2-f10f-4481-a4e7-da6137ef03e3.png)

**Comment by MasterKia** [comment]
The number ghajini sent yesterday got hit with a 24hour login limit.

I tried other numbers but the code didn't get sent.

**Comment by MasterKia** [comment]
The number ghajini sent yesterday got a 24hour login limit.
Every other I try is the same:
> Verification unsuccessful
Maximum attempts reached. Retry in 24 hours.

**Comment by holequantum** [comment]
Hey i think this should stay reopened as it have not been solved yet.

**Comment by MasterKia** [comment]
@holequantum 

I can't login.

https://github.com/uBlockOrigin/uAssets/issues/14565#issuecomment-1230744645:

![Screenshot_20220901_201653](https://user-images.githubusercontent.com/17685483/187957143-ade6ed32-9ccd-4f07-a833-b22b4380d514.png)
