### ISSUE TITLE
Crypto giveaway scam bnbdeal.net

### ISSUE THREAD

**Issue by resulin** [uBlockOrigin/uAssets#14569]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bnbdeal.net`

### Describe the issue

`https://www.bnbdeal.net` is a classic crypto scam website that should be blocked

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 103

### Settings

Stock

**Comment by MasterKia** [comment]
`https://bnbdeal.net/btc`

**Comment by MasterKia** [comment]
> To verify your address, just send from 0.02 to 5 BTC to the address below and get from .20 to 50 BTC back!

https://bnbdeal.net/btc

**Comment by MasterKia** [comment]
`https://bnbdeal.net/btc`

> To verify your address, just send from 0.02 to 5 BTC to the address below and get from .20 to 50 BTC back!

**Comment by Infrastructural** [comment]
blocking `medium.com` doesn't even seem to block the "article" from `https://www.bnbdeal.net/`

**Comment by Infrastructural** [comment]
Also, I don't think the CEO of Binance wrote it 😆

**Comment by Infrastructural** [comment]
![image](https://user-images.githubusercontent.com/112278288/187084172-d4606604-846c-4f0e-83d6-1f98a7f58fde.png)

**Comment by MasterKia** [comment]
Fake comment section then.

**Comment by Infrastructural** [comment]
Do you know how a `medium` article looks like? I think it tries to resemble one without actually being one.

**Comment by Infrastructural** [comment]
![image](https://user-images.githubusercontent.com/112278288/187084403-5d0be5b9-7fb3-4840-a136-6d7e418332ee.png)

**Comment by Infrastructural** [comment]
https://user-images.githubusercontent.com/112278288/187084650-7aa8f41b-55a4-4dd1-a479-5a75e59af3a8.png

**Comment by krystian3w** [comment]
@iam-py-test  or maybe @spirillen ban page on uBo or DNS level.

**Comment by krystian3w** [comment]
Blocked by Microsoft - fyi @mapx- 

https://user-images.githubusercontent.com/35370833/187089585-ee128ed0-16fb-4bab-a8c3-c9dc57ebd89d.png
