### ISSUE TITLE
ebay-kleinanzeigen.de: breakage option "Versand möglich" / "Nur Selbstabholer" seems to be blocked by EasyList

### ISSUE THREAD

**Issue by HaraldKi** [uBlockOrigin/uAssets#14568]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ebay-kleinanzeigen.de/p-anzeige-aufgeben-schritt2.html`

### Category

breakage

### Describe the issue

The site is a German classified ads site. When adding a new entry to sell, there should be an option to select between "shipment possible" or "pickup only" (Versand möglich / nur Abholung).

After switching EasyList off, the option is shown again, switching EasyList on, it disappears. Digging into the DOM the content of `id="j-post-ad-frontend"` gets blocked in:
```html
<div class="" id="j-post-ad-frontend">
  <div class="jsx-1774661615 jsx-3625817074">
  ...
```
The element itself is kept.

NOTE: to reach the respective page, logging into ebay-kleinanzeigen is necessary. Then a click near the top right "Anzeige aufgeben".

I see the 'post-add' rule(s) in EasyList and wonder whether they are a bit too general. But maybe I need to add an exception for ebay-kleinanzeigen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Missing shipment option:

![ebay-kleinanzeigen-missing-option](https://user-images.githubusercontent.com/6305643/187073606-86d23fa5-50f0-4941-b6e5-49b7929053eb.png)

After switching off EasyList, with shipment option:
![ebay-kleinanzeigen-with-shipment-option](https://user-images.githubusercontent.com/6305643/187073615-b681eb77-f46a-47d9-a8a0-ce29b78ea839.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84119
  cosmetic: 46327
  scriptlet: 17812
  html: 734
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-10, 3d.21h.21m
  default: 
    user-filters: 45-1, never
    ublock-filters: 33226-140, 3d.21h.20m
    ublock-badware: 4218-0, 3d.21h.19m
    ublock-privacy: 263-0, 3d.21h.26m
    ublock-abuse: 76-0, 3d.21h.25m
    ublock-unbreak: 1851-0, 3d.21h.17m
    easylist: 69310-506, never
    easyprivacy: 27414-634, 3d.21h.18m
    plowe-0: 3633-4, 3d.21h.24m
    urlhaus-1: 7028-0, 5h.11m
    ublock-quick-fixes: 399-0, 5h.12m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 35 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms (selfie)
  maxAssetCacheWait: 725 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    ebay-kleinanzeigen.de: 8
    ebay.de: 1
    google.com: 1
    googleadservices.com: 2
    googletagmanager.com: 1
    maps.googleapis.com: 1
```
</details>

**Comment by ghajini** [comment]
@Khrin easylist germany ,can you check

**Comment by okiehsch** [comment]
Well, to reproduce you have to register which includes giving a working mobile phone number.

@HaraldKi Can you give the exact filter that is causing the issue on your end?
Check the logger to get it. https://github.com/gorhill/uBlock/wiki/The-logger
