### ISSUE TITLE
mudwars.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#1456]
### URL(s) where the issue occurs
`https://mudwars.io`

### Describe the issue
Displays an anti-adblock message.

### Screenshot(s)
![mudwars io anti-adblock](https://user-images.githubusercontent.com/29117662/35730371-beb59b10-07c6-11e8-8b00-832d9596ac86.PNG)

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.14.25.101 (Nano Adblocker 1.0.0.28)

### Settings
Default.

### Notes
Anti-adblock.

**Comment by mapx-** [comment]
The page keeps loading but never ends

**Comment by okiehsch** [comment]
I get the anti-ablock message with uBO disabled, so seems to be the same as https://github.com/uBlockOrigin/uAssets/issues/1455
