### ISSUE TITLE
allpremium.net: detection

### ISSUE THREAD

**Issue by YogaGlace** [uBlockOrigin/uAssets#14566]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.allpremium.net/udemy-courses/`

### Category

detection

### Describe the issue

Detects uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 102
filterset (summary): 
  network: 211110
  cosmetic: 216229
  scriptlet: 37958
  html: 739
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 67118-5507, 1d.19h.34m
    adguard-spyware: 25441-926, 1d.19h.35m
    adguard-spyware-url: 725-2, 1d.19h.36m
    block-lan: 43-0, 18d.16h.10m
    curben-phishing: 71311-9, 18h.49m
    curben-pup: 188-0, 18h.52m
    adguard-annoyance: 56761-5023, 1d.19h.33m
    adguard-social: 18314-1061, 1d.19h.32m
    fanboy-thirdparty_social: 68-0, 1d.19h.42m
    fanboy-annoyance: 80059-64107, 1d.19h.40m
    fanboy-cookiemonster: 40595-144, 1d.19h.41m
    fanboy-social: 23306-28, 20h.30m
    ublock-annoyances: 4559-4, 1d.19h.31m
    dpollock-0: 11381-522, 9d.22m
  default: 
    user-filters: 7-0, never
    ublock-filters: 33290-65, 1d.20h.16m
    ublock-badware: 4165-0, 1d.20h.15m
    ublock-privacy: 247-0, 12d.2h.9m
    ublock-abuse: 76-0, 12d.2h.8m
    ublock-unbreak: 1857-1, 1d.19h.39m
    ublock-quick-fixes: 397-0, 18h.51m
    adguard-mobile: 8161-150, 1d.20h.17m
    easylist: 68201-963, 1d.19h.38m
    easyprivacy: 27425-9401, 1d.19h.37m
    urlhaus-1: 6830-0, 18h.50m
    plowe-0: 3630-3, 12d.2h.7m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2939 ms (selfie)
  maxAssetCacheWait: 660 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googlesyndication.com: 7
```
</details>

**Comment by ghajini** [comment]
we can fix antiadblock, do you get site operational without ubo?
