### ISSUE TITLE
v.qq.com: breakage

### ISSUE THREAD

**Issue by lleeopen** [uBlockOrigin/uAssets#14562]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://v.qq.com/x/cover/mzc00200kwy29cd/v0043fw36b1.html`

### Category

breakage

### Describe the issue

视频无法播放
Video cannot be played

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://i2.100024.xyz/2022/08/28/jwwxjm.webp

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 95
filterset (summary): 
  network: 100695
  cosmetic: 53759
  scriptlet: 17838
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 29010-90, now
    easylist: 67502-76, now
    easyprivacy: 27437-150, now
    plowe-0: 3634-778, now
    ublock-abuse: 76-0, now
    ublock-badware: 4162-96, now
    ublock-filters: 32501-140, now
    ublock-privacy: 241-3, now
    ublock-quick-fixes: 396-5, now
    ublock-unbreak: 1841-42, now
    urlhaus-1: 7028-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 323 ms (selfie)
  maxAssetCacheWait: 222 ms
popupPanel: 
  blocked: 61
  blockedDetails: 
    qq.com: 60
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
@cjx82630 Could you take a look ?

**Comment by cjx82630** [comment]
No probleom here. I cannot reproduce the issue.
