### ISSUE TITLE
dizipal364.com: ads

### ISSUE THREAD

**Issue by CarCo53** [uBlockOrigin/uAssets#14564]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizipal364.com/dizi/sokagin-cocuklari/sezon-1/bolum-1`

### Category

ads

### Describe the issue

reklam kalıntıları var (turkish)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 84329
  cosmetic: 50454
  scriptlet: 18114
  html: 735
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33181-38, 3d.34m
    ublock-badware: 4165-0, 3d.33m
    ublock-privacy: 263-0, 3d.32m
    ublock-abuse: 76-0, 3d.31m
    ublock-unbreak: 1851-0, 3d.30m
    ublock-quick-fixes: 393-0, 2h.39m
    easylist: 68380-617, 3d.28m
    easyprivacy: 27418-583, 3d.27m
    urlhaus-1: 7028-0, 2h.38m
    plowe-0: 3633-3, 3d.25m
    TUR-0: 8684-30, 3d.39m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 244 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    dizipal364.com: 10
    diziyoucdn.xyz: 1
    googletagmanager.com: 1
    waust.at: 2
```
</details>

**Comment by Yuki2718** [comment]
@AdamWr Possibly they have changed site structure, many of existing rules doesn't match.
