### ISSUE TITLE
app.luggagehero.com: breakage

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#14587]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.luggagehero.com/shop-details/62a0d712e74f716d82994e1f;bags=1;from=202208301200;to=202208301300;source=app`

### Category

breakage

### Describe the issue

The formatting on the page is messed up with the default filters enabled. Note how e.g. the stars don't render properly. If you disable uBlock, then it looks much better.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82241
  cosmetic: 43180
  scriptlet: 17712
  html: 731
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33187-37, 1d.8h.28m
    ublock-badware: 4166-0, 1d.4h.24m
    ublock-privacy: 247-0, 13d.1h.43m
    ublock-abuse: 76-0, 6d.2h.34m
    ublock-unbreak: 1852-0, 1d.8h.26m
    ublock-quick-fixes: 407-0, 1h.22m
    easylist: 67214-603, 1d.8h.25m
    easyprivacy: 27439-578, 1d.8h.27m
    urlhaus-1: 7021-0, 1h.21m
    plowe-0: 3634-3, 2d.6h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1583 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    hotjar.com: 1
    intercom.io: 1
    maps.googleapis.com: 2
    myfonts.net: 2
```
</details>

**Comment by MasterKia** [comment]
```css
<style>@import"https://hello.myfonts.net/count/3517B1";body{padding:0;margin:0}@charset "UTF-8";html{f......</style>
```

`@@||hello.myfonts.net/count/$stylesheet,domain=luggagehero.com`

@ryanbr EasyPrivacy
