### ISSUE TITLE
protopage.com: ads

### ISSUE THREAD

**Issue by Miro-Collas** [uBlockOrigin/uAssets#14580]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.protopage.com/mirocollas`

### Category

ads

### Describe the issue

The website is `https://www.protopage.com/` - it shows no ads until you create an account and customise the page for yourself.
Until a few hours ago, ads were correctly blocked; now they no longer are.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220829_014421](https://user-images.githubusercontent.com/39207573/187133766-d219cd5b-07a1-43e9-8cbe-ca70868569a7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 93904
  cosmetic: 161446
  scriptlet: 24875
  html: 745
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.19m
    adguard-annoyance: 56782-4100, 1h.1m
    fanboy-thirdparty_social: 69-0, 1h.19m
    fanboy-annoyance: 80176-23639, 1h.19m
    fanboy-social: 23306-28, 1h.19m
    ublock-annoyances: 4558-4, 1h.19m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33164-39, 1h.19m
    ublock-badware: 4166-0, 1h.19m
    ublock-privacy: 263-0, 1h.19m
    ublock-abuse: 76-0, 1h.19m
    ublock-unbreak: 1855-0, 1h.19m
    ublock-quick-fixes: 398-0, 1h.19m
    easylist: 67116-581, 1h.19m
    easyprivacy: 27441-582, 1h.19m
    urlhaus-1: 7101-0, 1h.19m
    plowe-0: 3634-3, 1h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1677 ms
  maxAssetCacheWait: 927 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce any ads even after registering and customizing my page (adding widgets, etc).

> - [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)

Please read and answer the prerequisites **_truthfully_**.
You're using Adblock Plus and Privacy badger; **remove them** and test again.

**Comment by Miro-Collas** [comment]
Thanks for the fast reply.

Done:
https://i.imgur.com/NhGbpgv.png
then restarted Firefox.

Problem still exists:
https://i.imgur.com/juv5bgj.png

I also reset uBlock to defaults. Tangentially, AdBlock Plus has the same problem.

**Comment by MasterKia** [comment]
Can you make another account and test?

**Comment by Miro-Collas** [comment]
Interesting - no ads:
https://i.imgur.com/uw9tOsI.png 
So maybe they start running ads some time after the account is made? I haven't had it that long.

**Comment by MasterKia** [comment]
In your main account, you can block those ads by right clicking => "Block Element" => Selecting the ads => Press "Create"

**Comment by Miro-Collas** [comment]
Yeah I  tried that before filing this, element by element, and it still shows ads... till removing the last apparently related element makes everything vanish, widgets and all.
Would page source be of any use?

**Comment by MasterKia** [comment]
Yes, right click and save the page.
Then send make a zip file from the folder and the .html file and send it here.

**Comment by Miro-Collas** [comment]
Here you go... thanks for the help!
[Protopage.zip](https://github.com/uBlockOrigin/uAssets/files/9442683/Protopage.zip)

**Comment by MasterKia** [comment]
Go to uBlock Origin settings => My filters => Add `protopage.com##.adsbygoogle` 

And test again.

**Comment by Miro-Collas** [comment]
Done - no apparent change.

(Sorry for the delayed reply .... bed called.)

**Comment by MasterKia** [comment]
The zip file you sent didn't carry the actual ads with it (but maybe someone else can diagnose).
So I need access to the account.

You can message me on Reddit: `FreeLibre`

**Comment by Miro-Collas** [comment]
I saved the contents of the uBlock logger, in case that helps:
[Protopage-Logger-Dump.zip](https://github.com/uBlockOrigin/uAssets/files/9447212/Protopage-Logger-Dump.zip)

As for reddit, the site says:
Hm... we couldn’t find any results for “FreeLibre”
(I have a reddit account but I never use the site.)
So use this
https://pastewith.me/?bcb78b065fabe30a#AxmwjKQv6YewTWC3VFsp1T4C3e2d42FRVLzBhQRKFu3M
paste will burn once you read it

**Comment by MasterKia** [comment]
Someone else got to the paste.

**Comment by MasterKia** [comment]
Someone else took care of the paste.
Try: https://www.reddit.com/message/compose/?to=FreeLibre

**Comment by Miro-Collas** [comment]
I figured there was a good chance of that happening. :-| Password changed, message sent.

**Comment by Miro-Collas** [comment]
(Btw, now away for about an hour)

**Comment by MasterKia** [comment]
@Miro-Collas Test and check for site breakage:
`protopage.com##+js(aost, document.createElement, createSecondarySubscribeToProtopageAdDiv)`

**Comment by MasterKia** [comment]
@Miro-Collas Test and check for site breakage:
`protopage.com##+js(aost, document.createElement, createSecondarySubscribeToProtopageAdDiv)`

**Comment by MasterKia** [comment]
@Miro-Collas Test:
`protopage.com##+js(aost, document.createElement, createSecondarySubscribeToProtopageAdDiv)`

**Comment by Miro-Collas** [comment]
Wow, that seems to work! Congrats!

**Comment by MasterKia** [comment]
@Miro-Collas Enable the uBlock Annoyances list.

**Comment by Miro-Collas** [comment]
Done; does that mean I can/should now remove the custom filter you gave me?
Anyway, that you SO MUCH for your help and the time spent on this!
[offers you a virtual 6-pack of your favorite beverage]

**Comment by MasterKia** [comment]
You can keep that custom filter and not enable the Annoyance list.

**Comment by Miro-Collas** [comment]
I'll leave annoyance on; I think. 
Thanks again!
