### ISSUE TITLE
webnovel.com

### ISSUE THREAD

**Issue by drkui** [uBlockOrigin/uAssets#1458]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.webnovel.com/book/7834185605001405/26177951129198029/True-Martial-World/Windsong-Ruins`

### Describe the issue

There's an adwall on the bottom of the page where you have to click 'Watch ad to get chapter' to proceed.

### Versions

- Browser/version: Chrome
- uBlock Origin version: 1.14.25.101+2

### Notes

When you click on the 'Watch ad to get chapter' button, with the adblocker on you get a bright red message: 'Please check if AdBlock is active'.

**Comment by mapx-** [comment]
Could you test this filter ?
`webnovel.com##script:inject(set-constant.js, adblockSuspected, false)`

**Comment by drkui** [comment]
That worked for getting rid of the 'Please check if AdBlock is active' message, but there is still the video ad that currently can't be skipped.

**Comment by okiehsch** [comment]
How about 
````
webnovel.com##script:inject(nano-setTimeout-booster.js)
webnovel.com##script:inject(set-constant.js, adblockSuspected, false)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=webnovel.com
````
click "Watch ad", then I can click "skip" and be able to access the bonus chapter.

**Comment by mapx-** [comment]
it works for me, but after skip, I get `Load failed, please RETRY` and then if I click `RETRY` I can read the article.

**Comment by okiehsch** [comment]
Hm, weird I don't get any error, tried with Chrome and Firefox.

**Comment by mapx-** [comment]
However, in the end ...it works.
