### ISSUE TITLE
flightradar24.com: detection

### ISSUE THREAD

**Issue by zentriex** [uBlockOrigin/uAssets#14585]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.flightradar24.com/38.48,-87.72/6`

### Category

detection

### Describe the issue

Detected, forced reload of list and toggled settings. Still detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82583
  cosmetic: 20707
  scriptlet: 17714
  html: 736
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 33186-274, 2d.6h.28m
    ublock-badware: 4165-1, 3d.20h.32m
    ublock-privacy: 263-1, 3d.20h.31m
    ublock-abuse: 76-0, 3d.20h.30m
    ublock-unbreak: 1852-0, 3d.20h.29m
    ublock-quick-fixes: 397-4, 1d.3h.32m
    easylist: 68048-23237, 2d.21h.58m
    easyprivacy: 27425-597, 2d.21h.57m
    urlhaus-1: 6967-0, 20h.22m
    plowe-0: 3633-3, 2d.21h.55m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 491 ms (selfie)
  maxAssetCacheWait: 302 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    cloudflareinsights.com: 2
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 5
    googlesyndication.com: 1
    indexww.com: 2
    maps.googleapis.com: 2
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce.

> forced reload of list 

Your lists are still ~3 days old.

**Comment by zentriex** [comment]
Well that sucks. On my screen it Saud it loaded ;-; thanks!

Respectfully,

Hayden Williams
________________________________

**Comment by MasterKia** [comment]
> ignoreGenericCosmeticFilters: true

You enabled this on purpose?
