### ISSUE TITLE
TagPro.gg broke

### ISSUE THREAD

**Issue by jasonkhanlar** [uBlockOrigin/uAssets#14581]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tagpro.gg/`
`https://tagpro.gg/games/find`

### Describe the issue

At the TagPro website, when clicking on "Play Now" button, when the settings section appears, there should be checkboxes to the left of each text, but they are hidden. When clicking the power button to turn off/disable the uBlock Origin extension, then the checkboxes appear.

### uBlock Origin version

1.44.0

### Browser name and version

Chromium Version 104.0.5112.101 (Official Build) Arch Linux (64-bit)

### Settings

Default settings

### Notes

When clicking the power button to turn off/disable the uBlock Origin extension, then the checkboxes appear.

**Comment by ghajini** [comment]
if you are talking about this 
![image](https://user-images.githubusercontent.com/20338483/187255649-0a792439-f7ac-4cec-a70e-9ffceb596569.png)

then it appears correctly for me

**Comment by jasonkhanlar** [comment]
In the uBlock Origin dashboard, Filter Lists tab, "Annoyances" branch, deselecting "Fanboy's Annoyance" and clicking "Apply changes" and then refreshing the page, the checkboxes appear. Reselecting it, the checkboxes disappear again.

**Comment by ghajini** [comment]
Caused by **Fanboy annoyances**
@ryanbr
