### ISSUE TITLE
[nsfw] play.geoflix.me: privacy

### ISSUE THREAD

**Issue by tern** [uBlockOrigin/uAssets#14588]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://play.geoflix.me/`

### Category

privacy

### Describe the issue

Will lead people to register an account and deceive people to provide credit card numbers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 98932
  cosmetic: 55538
  scriptlet: 17764
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33207-138, never
    ublock-badware: 4237-0, never
    ublock-privacy: 247-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1871-0, never
    ublock-quick-fixes: 386-0, never
    easylist: 69310-176, never
    easyprivacy: 27312-133, never
    urlhaus-1: 5164-0, never
    plowe-0: 3634-779, never
    CHN-0: 29067-158, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2606 ms
  maxAssetCacheWait: 5 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    histats.com: 1
```
</details>

**Comment by MasterKia** [comment]
How did you get to this site?
Send the original page that redirected you to this page.

**Comment by tern** [comment]
I'm looking for a movie, google keyword:同床異夢 mp4 download

[image: 截圖 2022-08-30 下午5.20.58.png]

MasterKia ***@***.***> 於 2022年8月30日 週二 下午2:59寫道：

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/187401419-9382af91-9c28-48c6-a9b8-0d7d944753ab.png)

I don't get any geofli results on my end.
Anyway why do you think the site deceives users?

**Comment by tern** [comment]
As you are directed to the registration page, you will be asked to enter
your credit card number. On the registration page, every time the browser
is refreshed, the URL will change, and I accidentally entered my credit
card number.
[image: 截圖 2022-08-30 下午5.37.50.png]

[image: 截圖 2022-08-30 下午5.38.15.png]

[image: 截圖 2022-08-30 下午5.38.46.png]

Here every time you refresh the page, you can get a new URL.



okiehsch ***@***.***> 於 2022年8月30日 週二 下午5:28寫道：

**Comment by okiehsch** [comment]
If you update your filter lists the site will be blocked.

>   I accidentally entered my credit card number.

How can you "accidentally" enter your credit card number? 
I assume you looket it up beforehand or have you memorized it. 😉 

Never add your credit card number unless you trust the site 100%.

**Comment by MasterKia** [comment]
Maybe the browser auto-fill "accidentally" entered the credit card number.
