### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by kamaal001** [uBlockOrigin/uAssets#14590]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=IiEYb3kTbeo`

### Category

ads

### Describe the issue

it shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82358
  cosmetic: 43002
  scriptlet: 17716
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67084-51, 1h.37m
    easyprivacy: 27443-126, 1h.36m
    plowe-0: 3633-776, 8d.2h.44m
    ublock-abuse: 76-0, 3d.22h.30m
    ublock-badware: 4162-96, 3d.22h.29m
    ublock-filters: 32484-129, 3d.22h.28m
    ublock-privacy: 241-3, 3d.22h.27m
    ublock-quick-fixes: 394-4, 18h.49m
    ublock-unbreak: 1839-41, 3d.22h.26m
    urlhaus-1: 7101-0, 18h.48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1162 ms (selfie)
  maxAssetCacheWait: 605 ms
popupPanel: 
  blocked: 1693
  blockedDetails: 
    youtube.com: 1389
    doubleclick.net: 19
    google.co.ke: 1
    google.com: 101
    googleadservices.com: 2
    googlesyndication.com: 4
    googlevideo.com: 177
```
</details>

**Comment by holequantum** [comment]
It does not show ads.
Do one thing delete your browser cache or delete youtube.com data and then reload yoir browsegr and remove ublock and reinatall ublock and check it again. You should not see ads.

**Comment by ghajini** [comment]
comment here https://github.com/uBlockOrigin/uAssets/issues/7636 s

**Comment by MasterKia** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by MasterKia** [comment]
Also see: https://github.com/easylist/easylist/wiki/youtube-issues
