### ISSUE TITLE
eksisozluk.com: breakage

### ISSUE THREAD

**Issue by weinbaum** [uBlockOrigin/uAssets#14591]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eksisozluk.com/`

### Category

breakage

### Describe the issue

The "return to usual view" button (her zamanki görünüme dön) does not work when uBlock Origin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran Alıntısı](https://user-images.githubusercontent.com/98059187/187384954-381c6781-a73c-49de-a257-3dcf435b01e7.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 84072
  cosmetic: 49483
  scriptlet: 18150
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 33-2, never
    TUR-0: 8699-20, 1m
    easylist: 67082-68, now
    easyprivacy: 27443-131, 1m
    plowe-0: 3634-777, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4172-96, 1m
    ublock-filters: 32474-117, 1m
    ublock-privacy: 241-3, 1m
    ublock-quick-fixes: 403-4, 1m
    ublock-unbreak: 1845-41, 1m
    urlhaus-1: 7018-0, 1m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 446 ms
  maxAssetCacheWait: 345 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adform.net: 1
    adrecover.com: 1
    criteo.net: 1
    doubleclick.net: 2
    facebook.com: 2
    gelirartisi.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    nativespot.com: 1
    networkad.net: 1
    twitter.com: 1
```
</details>

**Comment by ghajini** [comment]
comment here
https://github.com/uBlockOrigin/uAssets/issues/14464
