### ISSUE TITLE
nookea.com: detection

### ISSUE THREAD

**Issue by Ketsuna009** [uBlockOrigin/uAssets#14595]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nookea.com/`

### Category

detection

### Describe the issue

website has a delayed popover that covers the entire screen and is not 'pick-able' by the pick tool in uBlock. also probably deletes the scroll bar. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 234999
  cosmetic: 209392
  scriptlet: 37980
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 22h.12m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 4m
    adguard-annoyance: 56832-83, 22h.16m
    adguard-generic: 67221-714, 22h.20m
    adguard-social: 18328-876, 22h.15m
    adguard-spyware: 26670-1280, 22h.18m
    adguard-spyware-url: 737-1, 22h.22m
    curben-phishing: 82052-10, 3m
    curben-pup: 187-1, 3m
    dpollock-0: 11383-1418, 8d.1h.51m
    fanboy-annoyance: 80181-4700, 18h.10m
    fanboy-cookiemonster: 40701-40701, 18h.9m
    fanboy-social: 23310-23310, 22h.14m
    fanboy-thirdparty_social: 69-21, 18h.11m
    ublock-annoyances: 4551-240, 22h.13m
  default: 
    user-filters: 32-2, never
    easylist: 67065-1348, 22h.19m
    easyprivacy: 27442-9457, 22h.17m
    plowe-0: 3633-1401, 8d.1h.52m
    ublock-abuse: 76-0, 4d.5h.15m
    ublock-badware: 4162-332, 1d.6h.23m
    ublock-filters: 32465-3916, 1d.6h.24m
    ublock-privacy: 241-44, 4d.5h.16m
    ublock-quick-fixes: 403-16, 6h
    ublock-unbreak: 1845-105, 22h.21m
    urlhaus-1: 6984-2, 5h.59m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 710 ms (selfie)
  maxAssetCacheWait: 815 ms
popupPanel: 
  blocked: 10
  no-cosmetic-filtering: true
  blockedDetails: 
    nookea.com: 8
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by MasterKia** [comment]
> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

>   added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 22h.12m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 4m
    adguard-annoyance: 56832-83, 22h.16m
    adguard-generic: 67221-714, 22h.20m
    adguard-social: 18328-876, 22h.15m
    adguard-spyware: 26670-1280, 22h.18m
    adguard-spyware-url: 737-1, 22h.22m
    curben-phishing: 82052-10, 3m
    curben-pup: 187-1, 3m
    dpollock-0: 11383-1418, 8d.1h.51m
    fanboy-annoyance: 80181-4700, 18h.10m
    fanboy-cookiemonster: 40701-40701, 18h.9m
    fanboy-social: 23310-23310, 22h.14m
    fanboy-thirdparty_social: 69-21, 18h.11m
    ublock-annoyances: 4551-240, 22h.13m


Please test using **_only the default lists_**.

**Comment by mapx-** [comment]
> website has a delayed popover

> detection

maybe you are talking about an annoyance and not about antiadblocking detection
