### ISSUE TITLE
haberglobe.com: ads

### ISSUE THREAD

**Issue by DarkXFast** [uBlockOrigin/uAssets#14599]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://haberglobe.com/guardian-gazetesinin-devlet/`

### Category

ads

### Describe the issue

There are ads on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 84097
  cosmetic: 49359
  scriptlet: 18143
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    TUR-0: 8701-20, 42m
    easylist: 67013-68, 41m
    easyprivacy: 27446-131, 40m
    plowe-0: 3633-777, 8d.13h.20m
    ublock-abuse: 76-0, 9d.4h.21m
    ublock-badware: 4177-96, 39m
    ublock-filters: 32457-105, 38m
    ublock-privacy: 232-3, 9d.20m
    ublock-quick-fixes: 403-4, 22h.8m
    ublock-unbreak: 1839-41, 3d.10h.49m
    urlhaus-1: 7021-0, 22h.9m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 381 ms (selfie)
  maxAssetCacheWait: 186 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
```
haberglobe.com##+js(aeld, scroll, undefined)
haberglobe.com##.ads
```

@Yuki2718

**Comment by Yuki2718** [comment]
Hm, on my end `haberglobe.com##+js(aeld, scroll, undefined)` looks not needed.
