### ISSUE TITLE
w3schools.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14594]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_hr_noshade_css`

### Category

ads

### Describe the issue

There's whitespace at the top of the page where an ad was removed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<kbd>

<img src="https://user-images.githubusercontent.com/110956608/187441840-5f486a80-c963-4a3a-a273-b12fc0c2afdc.png"/>

</kbd>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 83971
  cosmetic: 80701
  scriptlet: 20003
  html: 742
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40701-83, 18h.3m
  default: 
    user-filters: 1085-0, never
    ublock-filters: 33170-49, 18h.3m
    ublock-badware: 4166-0, 18h.3m
    ublock-privacy: 263-0, 18h.3m
    ublock-abuse: 76-0, 18h.3m
    ublock-unbreak: 1858-0, 18h.3m
    ublock-quick-fixes: 407-0, 18h.3m
    easylist: 67065-595, 18h.3m
    easyprivacy: 27442-583, 18h.3m
    urlhaus-1: 7021-0, 18h.3m
    plowe-0: 3634-3, 18h.3m
filterset (user): [array of 189 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 500 ms
  maxAssetCacheWait: 282 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    snigelweb.com: 2
```
</details>

**Comment by mapx-** [comment]
maybe
`w3schools.com##.trytopnav:style(top: 0 !important)`

**Comment by MasterKia** [comment]
`w3schools.com##.trytopnav:style(top: 36px!important;)` is already in uBlock Filters.

**Comment by mapx-** [comment]
indeed, interfering with the other issue too
https://github.com/uBlockOrigin/uAssets/issues/12688

@Yuki2718

**Comment by krystian3w** [comment]
If we don't resize window too often on that page, then possible for PC use filter with `:not(:has(` on pages without `breadcrumb` to avoid rebuild all procedural filtering to works after resize window do similar size simulated on smartphones.

**Comment by Yuki2718** [comment]
@krystian3w Enough:
```
w3schools.com#@#.trytopnav:style(top: 36px!important;)
w3schools.com#@##tryitLeaderboard ~ #container:style(top: 84px!important;)
w3schools.com###breadcrumb + .trytopnav:style(top: 36px!important;)
w3schools.com###tryitLeaderboard + .trytopnav:style(top: 0!important;)
w3schools.com###tryitLeaderboard + #breadcrumb ~ #container:style(top: 84px!important;)
w3schools.com###tryitLeaderboard ~ #dragbar + #container:style(top: 50px!important;)
```
But TBH I prefer ignoring this size of PH.

**Comment by krystian3w** [comment]
For now I have overlapped buttons if breadcrumb exist (maybe webmaster touched try it template).

HTTPS://i.imgur.com/EV8eIfQ.png

At: `https://www.w3schools.com/css/tryit.asp?filename=trycss_form_padding~

**Comment by Yuki2718** [comment]
`###tryitLeaderboard + .trytopnav ~ #dragbar + #container:style(top: 50px!important;)`?

**Comment by krystian3w** [comment]
As cssNazi I recommend test lower number than 50 (I see 1px white line).

To test reset zoom//DPI in browser.

**Comment by Yuki2718** [comment]
Yep, #tryhome has margin-top: -2px.
