### ISSUE TITLE
marinetraffic.com: breakage

### ISSUE THREAD

**Issue by Lulucmy** [uBlockOrigin/uAssets#14593]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.marinetraffic.com/en/ais/home/centerx:2.0/centery:47.5/zoom:6`

### Describe the issue

Live map isn't displayed when uBlock is turned on.

### uBlock Origin version

1.44.0

### Browser name and version

Chrome 104.0.5112.102 (Official build) (64 bits)

### Settings

- None

### Notes

The map appears when I turn off "Visual filter", but it is displayed weirdly:

![image](https://user-images.githubusercontent.com/20552095/187438831-c9b3f9c5-d6f1-4f29-a06c-51221098d929.png)

**Comment by MasterKia** [comment]
@Lulucmy Go to uBlock Origin settings => My filters => Add these and test:
```
marinetraffic.com#@#.ads
marinetraffic.com##.ads:style(width: 0px !important; height: 0px !important;)
```

**Comment by MasterKia** [comment]
Works fine for me in Firefox and Ungoogled Chromium.
Did you test using **only the default filter lists**?
