### ISSUE TITLE
Github star and unstar malfunction cause by repository name

### ISSUE THREAD

**Issue by Wei-1** [uBlockOrigin/uAssets#146]
### URL(s) where the issue occurs

[https://github.com/pa7/heatmap.js](url)

### Describe the issue

Star and Unstar malfunction

### Screenshot(s)

![ublock01](http://i.imgur.com/fAm6gmo.png "ublock01")

### Versions

- Browser/version: Chrome 53.0.2785.113 m (64-bit)
- uBlock Origin version: 1.8.5.7

### Settings

Default setting

### Notes

The Github project name "heatmap.js" is blocked while sending XHR.
When we try to star or unstar the repository "heatmap.js", we send an XHR:
[https://github.com/pa7/heatmap.js/star](URL)
from our browser to Github server.
Since the message is blocked, star and unstar will not work.

![ublock02](http://i.imgur.com/XBVkUCl.png "ublock02")

The reason why "heatmap.js" is blocked is because the word is listed in easyprivacy.txt.

![ublock03](http://i.imgur.com/9HbFTlK.png "ublock03")

**Comment by gorhill** [comment]
Best is to report to EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.
