### ISSUE TITLE
mcsweeneys.net: nuisance

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14603]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mcsweeneys.net/articles/ill-drink-this-pumpkin-spice-latte-before-labor-day-but-only-because-demons-are-making-me`

### Category

nuisance

### Describe the issue

sticky popup at bottom of page
can be blocked with `mcsweeneys.net###floating-footer-container`

there's a self-promo banner `mcsweeneys.net##.breaking-news-container`

and also promo ads `mcsweeneys.net##.house-ad-right`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/187595504-4f9480fe-cb68-40c9-adf3-7b377385e5ba.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 173496
  cosmetic: 127900
  scriptlet: 25514
  html: 749
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1942-0, 1h.42m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 1h.42m
    adguard-spyware-url: 738-108, 1h.42m
    block-lan: 43-0, 1h.42m
    curben-phishing: 82102-6, 1h.42m
    curben-pup: 188-0, 1h.42m
    adguard-annoyance: 56926-3678, 1h.42m
    fanboy-cookiemonster: 40535-131, 1h.42m
    ublock-annoyances: 4561-6, 1h.42m
  default: 
    user-filters: 975-0, never
    ublock-filters: 33158-50, 1h.42m
    ublock-badware: 4181-0, 1h.42m
    ublock-privacy: 263-2, 1h.42m
    ublock-abuse: 76-0, 1h.42m
    ublock-unbreak: 1858-1, 1h.42m
    ublock-quick-fixes: 407-0, 1h.42m
    easylist: 66797-596, 1h.42m
    easyprivacy: 27446-578, 1h.42m
    urlhaus-1: 7132-0, 1h.42m
    plowe-0: 3634-3, 1h.42m
filterset (user): [array of 139 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 305 ms (selfie)
  maxAssetCacheWait: 529 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
report directly at FA annoyances or adguard annoyances

@ryanbr
