### ISSUE TITLE
newscon.net: nuisance

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#14607]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.newscon.net/?hl=en`

### Category

nuisance

### Describe the issue

You must wait for at least 10s for the popup.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82197
  cosmetic: 43516
  scriptlet: 17726
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67552-51, 3d.21h.49m
    easyprivacy: 27436-126, 3d.21h.49m
    plowe-0: 3633-776, 3d.21h.49m
    ublock-abuse: 76-0, 3d.21h.49m
    ublock-badware: 4162-96, 3d.21h.49m
    ublock-filters: 32487-121, 3d.21h.49m
    ublock-privacy: 241-3, 3d.21h.49m
    ublock-quick-fixes: 403-4, 18h.18m
    ublock-unbreak: 1839-41, 3d.21h.49m
    urlhaus-1: 6984-0, 18h.17m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6747 ms (selfie)
  maxAssetCacheWait: 5404 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    arc.io: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    sentry-cdn.com: 1
    unative.com: 1
```
</details>

**Comment by mapx-** [comment]
> You must wait for at least 10s for the popup.

what popup ?

Did you reach this page starting from another one ? => provide it

**Comment by Cyberavater** [comment]
![Screenshot](https://user-images.githubusercontent.com/32187927/187627577-1fb92b4e-4d92-4c8f-ad28-770269146779.png)
This one. Maybe it's on the geolocation?

> Did you reach this page starting from another one ? => provide it

This is the homepage.

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`, already fixed as annoyance
