### ISSUE TITLE
empire.goodgamestudios.com: ads

### ISSUE THREAD

**Issue by UserMe99** [uBlockOrigin/uAssets#14608]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://empire.goodgamestudios.com/`

### Category

ads

### Describe the issue

I did not change anything on my browser but white banners show up where ads should be.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 81866
  cosmetic: 42653
  scriptlet: 17732
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 66408-51, 5h.42m
    easyprivacy: 27436-126, 3d.20h.25m
    plowe-0: 3632-777, 11d.20h
    ublock-abuse: 76-0, 12d.23h.57m
    ublock-badware: 4172-99, 1d.1h.28m
    ublock-filters: 32424-105, 5h.43m
    ublock-privacy: 231-3, 12d.23h.58m
    ublock-quick-fixes: 403-4, 19h.57m
    ublock-unbreak: 1845-41, 19h.59m
    urlhaus-1: 6984-0, 19h.58m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 196 ms (selfie)
  maxAssetCacheWait: 76 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    goodgamestudios.com: 2
    bugsnag.com: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    jsdelivr.net: 1
```
</details>

**Comment by MasterKia** [comment]
> white banners show up where ads should be.

Send screenshot.
I don't see any blank space.
https://user-images.githubusercontent.com/17685483/187740675-65f06cc0-0969-4994-b613-949d641f79da.png

**Comment by UserMe99** [comment]
![Screenshot 2022-08-31 232421](https://user-images.githubusercontent.com/112562478/187775351-1f3bd9cd-6880-4245-8867-81717559136c.png)

**Comment by UserMe99** [comment]
![Screenshot 2022-08-31 232421](https://user-images.githubusercontent.com/112562478/187776498-2768f6cc-f359-4f99-acd9-d6c254e4fa1b.png)

**Comment by UserMe99** [comment]
I installed uBlock Origin on Edge and there it seemed to block ads, I had both Edge and Chrome open and quickly compared things and didn't notice any check or unchecked boxes. 
In the end I Reset to default settings. It works great now.
I'm not sure what happened.
