### ISSUE TITLE
climatempo.com.br: breakage

### ISSUE THREAD

**Issue by SHJordan** [uBlockOrigin/uAssets#14609]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.climatempo.com.br/previsao-do-tempo/agora/cidade/714/feiradesantana-ba`

### Category

breakage

### Describe the issue

The small videoplayer that plays the day forecast is shut black. But one can go directly and watch it if fiddle through source:
`https://obj-gravscale.zadarazios.com:443/v1/AUTH_f57eb386f52e4dc0bcdf19764aecc205/ct/bl_br.mp4`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
With ublock:

![image](https://user-images.githubusercontent.com/884602/187710701-3ebc3835-a367-4774-a6a3-61f463453a5a.png)

With ublock turnoff:

![image](https://user-images.githubusercontent.com/884602/187710966-fd2b2678-b65f-4e51-aab5-b3a304e38c62.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 80955
  cosmetic: 94824
  scriptlet: 20641
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1945-0, 23h.52m
    adguard-annoyance: 56810-83, 2d.3h.50m
    adguard-spyware-url: 738-107, 19h.51m
  default: 
    user-filters: 6-0, never
    easylist: 67008-106, 19h.50m
    easyprivacy: 27444-224, 19h.49m
    spa-1: 4606-77, 19h.44m
    ublock-abuse: 76-0, 7d.19h.39m
    ublock-badware: 4167-94, 19h.47m
    ublock-filters: 32472-520, 19h.46m
    ublock-privacy: 241-5, 7d.19h.38m
    ublock-quick-fixes: 403-4, 23h.53m
    ublock-unbreak: 1845-45, 19h.45m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 19 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 332 ms (selfie)
  maxAssetCacheWait: 235 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    climatempo.com.br: 1
    cloudflareinsights.com: 1
    consensu.org: 1
    google-analytics.com: 1
    googleads.github.io: 3
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by MasterKia** [comment]
```
@@||googleads.github.io/videojs-ima/node_modules/video.js/dist/video.min.js$script,domain=climatempo.com.br
@@||googleads.github.io/videojs-ima/node_modules/video.js/dist/video-js.min.css$stylesheet,domain=climatempo.com.br
```

@ryanbr EasyList
