### ISSUE TITLE
tumblr.com

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14606]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.tumblr.com/explore/trending`

### Describe the issue

There is a sign-in gate popup that appears when clicking usernames/tags.

Can be blocked with `tumblr.com##+js(aeld, click, loginWallType)`

However this appears to not work in Firefox (see https://github.com/DandelionSprout/adfilt/discussions/642#discussioncomment-3514965)

---

There is still a sign-in gate popup that appears when you scroll down the page a lot. I'm not sure how to block this one. Any ideas are welcome!

### Screenshot(s)

<img width="785" alt="image" src="https://user-images.githubusercontent.com/110956608/187612391-88c2eb66-b511-4393-b4dc-e2e119dbec4c.png">

### uBlock Origin version

1.44

### Browser name and version

chromium 107
ff 104

### Notes

https://github.com/DandelionSprout/adfilt/discussions/642
https://github.com/uBlockOrigin/uAssets/discussions/14605

**Comment by mapx-** [comment]
test

```
tumblr.com##body:style(overflow: auto !important;)
tumblr.com###glass-container:has-text(clearance)
```

**Comment by MasterKia** [comment]
@wavygecko If the second filter doesn't work for Firefox then maybe @mapx- filters can help.

**Comment by mapx-** [comment]
However no filter can be added because the login will be broken otherwise, just use whatever filters you want as custom ones

**Comment by Yuki2718** [comment]
The sentence of auto-appearing modal is different from the one appears you explicitly clicked login. Maybe
```
tumblr.com###glass-container:has-text(You need clearance for that)
tumblr.com##body:style(overflow: auto !important;)
```

**Comment by MasterKia** [comment]
> (works only for English locale ofc)

Maybe
`tumblr.com###glass-container:has-text(51)`
depends if they keep the area 51 joke in other locales.

**Comment by Yuki2718** [comment]
Not working in JP locale

**Comment by wavygecko** [comment]
I don't think those filters will work 100%.

`assets.tumblr.com/pop/js/modern/async-login-wall-*.js` needs to be blocked.
If it is not blocked then after you scroll down the page for a bit (when the popup gate would appear), clicking images stops working.

Blocking that script, however, blocks the popup when you click on the signup/login buttons.

But! If we can create a filter that defuses the click event for the signup/login buttons that opens up the popup, then they should take the browser directly to a login/register page. (`https://www.tumblr.com/login` and `https://www.tumblr.com/register`)

**Comment by wavygecko** [comment]
Here's an overzealous approach that ostensibly works:

```
||assets.tumblr.com/pop/js/modern/async-login-wall-*.js$script,1p
tumblr.com##+js(aeld, click)
```

I think we would want a more targeted approach though rather than blocking all click events.

e.g.:
```
tumblr.com##+js(aeld, click, loginWallType)
! *some rule that defuses the click event for the login/signup buttons*
```

**Comment by Yuki2718** [comment]
As already said, scriptlet doesn't work thx to csp.

**Comment by piquark6046** [comment]
`tumblr.com#?##glass-container:contains(/You need clearance for that|おっと、この先に進むには認証が必要/)` does not work in KR locale.
Please change the regex to `/You need clearance for that|おっと、この先に進むには認証が必要|앗, 허가를 받아야 합니다/`.

**Comment by wavygecko** [comment]
True, but it does work for Chromium.

But blocking the popup without scriplets breaks the site.

**Comment by Yuki2718** [comment]
@ryanbr @Khrin `||tumblr.com/services/bblog`

**Comment by MasterKia** [comment]
> scriptlet doesn't work thx to csp.

There's hope for that issue: https://github.com/uBlockOrigin/uAssets/discussions/14605#discussioncomment-3519838

**Comment by wavygecko** [comment]
I actually found multiple problematic things with the cosmetic block approach :(

## issue 1
1. Click login button to open popup
2. Click outside popup to close it
3. Scroll down the page a bunch
4. The login popup reappears

https://user-images.githubusercontent.com/110956608/187744316-3a72747c-27ca-4c64-8f1f-6a3289c81f97.mov




## issue 2
1. Click on post image
2. Nothing happens

**Comment by piquark6046** [comment]
It seems that `EventTarget.prototype.addEventListener` is modified by tumblr.
Please try `EventTarget.prototype.addEventListener.toString()` in a browser console.

**Comment by wavygecko** [comment]
There's a click event on `#root` that, if removed, allows the log-in and sign-up buttons to work even when the popup is blocked.

https://user-images.githubusercontent.com/110956608/187775241-55171a89-e646-4754-bc30-77c013cb1570.mov

But I can't figure out how to remove that click event with uBO. Any ideas?

**Comment by Yuki2718** [comment]
> Please change the regex to
> I actually found multiple problematic things with the cosmetic blocking approach :(

Actually I was aware of the issue 1 and it's acceptable, but the issue 2 is problematic and violates at least AG's criteria. I'll disable the rules.

**Comment by MasterKia** [comment]
@Yuki2718 Did you test with `:remove()` or `:style(filter: opacity(0) !important;)?

**Comment by Yuki2718** [comment]
No.

**Comment by MasterKia** [comment]
@wavygecko https://github.com/uBlockOrigin/uAssets/issues/14606#issuecomment-1234057068

**Comment by wavygecko** [comment]
> Did you test with `:remove()` or `:style(filter: opacity(0) !important;)`?

Seems like we still run into the same problems using those.

I think we can only move forward with this if
1. the CSP issue is fixed in uBO for Firefox (https://github.com/uBlockOrigin/uAssets/discussions/14605#discussioncomment-3519838)
2. we figure out a solution for the login/signup buttons (https://github.com/uBlockOrigin/uAssets/issues/14606#issuecomment-1233387289)
