### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by btsmp** [uBlockOrigin/uAssets#14613]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/alanzoka`

### Category

ads

### Describe the issue

ads 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 83559
  cosmetic: 46080
  scriptlet: 17948
  html: 731
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33187-73, 3d.2h.13m
    ublock-badware: 4166-0, 3d.2h.12m
    ublock-privacy: 247-0, 10d.18h.24m
    ublock-abuse: 76-0, 7d.4h.16m
    ublock-unbreak: 1854-0, 3d.2h.11m
    ublock-quick-fixes: 407-0, 21h.38m
    easylist: 67214-654, 3d.2h.10m
    easyprivacy: 27439-591, 3d.2h.9m
    urlhaus-1: 6984-0, 23h.51m
    plowe-0: 3633-3, 7d.4h.14m
    spa-1: 4605-14, 2d.8h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 391 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 2
    imrworldwide.com: 4
    scorecardresearch.com: 13
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5184
