### ISSUE TITLE
1d6cdf6786e.perfectlotto.net: popups

### ISSUE THREAD

**Issue by Gabypunk** [uBlockOrigin/uAssets#14615]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://1d6cdf6786e.perfectlotto.net/push-win?ctrack=1661998003.2326340779&traffic=eyJpdiI6IlY5MG5NTlwvUXlFWFhVNW53ek5XWTdnPT0iLCJ2YWx1ZSI6IkpORWFTRDdYZWdWcmRoZVZFNGV1Q1RDMzBEMGZncUc3aHBXdlpveDVjblVjKytVdEJFeDBCdlNPNzZjdyt4ME4iLCJtYWMiOiIwZmI5YWIyNzg1N2NkMTJkNDQ0MGY3YzllMmU3NWE1MGExNjRjYmYwODA4NGRjNDZhMWMxYzZkZjliNzI0NTI2In0%3D&out=eyJpdiI6Ik5yNjc0TVFcL3NoUHZtZXZGWUxIWVVBPT0iLCJ2YWx1ZSI6IkVoSHpueXMzMmRlcEdIT21hMmhkOTZ5RXlORjRQUVZqT0t2UUoxWUduUzNkSWJPc1FHSGNxU09EeHdTTUFGdURzZUhyZWgyVjhvZFVWeVh3cXdlaEd0aTNreDFldEs4NkREeXdicFlNSWVhMEYydzhOQXVGUkJHS21YNjZJeUJTMkRySWxpb3VUbmtyc2x6NWl2Tk1Jdz09IiwibWFjIjoiMzNhOTljMDEyNzdiMThhMzg4ZGY3ZjY2NjhhZWUwNTdhMTk4M2RiMWRlMWU1ZDkwODdjMWQ4OTQ1YjdlMzdiMSJ9`

### Category

popups

### Describe the issue

> La pagina a la que quise acceder no tiene nada que ver a donde me derivó el enlace. No es un anuncio, por lo que tengo que cerrar la pestaña para poder salir. En ella me ofrecen ganar un iphone, sospecho que es phishing. 

**The page I wanted to access has nothing to do with where the link took me. It's not an ad, so I have to close the tab to get out. In it they offer me to win an iphone, I suspect it is phishing.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 85675
  cosmetic: 47650
  scriptlet: 17971
  html: 740
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3h.15m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33140-33, 3h.6m
    ublock-badware: 4181-0, 3h.12m
    ublock-privacy: 263-0, 4d.5h.27m
    ublock-abuse: 76-0, 4d.5h.26m
    ublock-unbreak: 1859-0, 3h.11m
    ublock-quick-fixes: 409-4, 3h.3m
    easylist: 66784-692, 3h.10m
    easyprivacy: 27449-594, 3h.9m
    urlhaus-1: 7332-0, 3h.5m
    plowe-0: 3634-3, 4d.5h.25m
    spa-0: 3955-19, 3h.4m
    spa-1: 4611-148, 3h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2514 ms (selfie)
  maxAssetCacheWait: 1491 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    oostotsu.com: 1
```
</details>

**Comment by MasterKia** [comment]
> The page I wanted to access has nothing to do with where the link took me

Send the original page that redirected you to this page.
