### ISSUE TITLE
mafiatown.pl: detection

### ISSUE THREAD

**Issue by RozvM** [uBlockOrigin/uAssets#14610]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mafiatown.pl/`

### Category

detection

### Describe the issue

The website displays this message until you disable uBlock Origin:
> It looks like you're blocking ads on mafiatown.pl. Please add mafiatown.pl to your adblock's white list. That way we can still run this website for you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![kép](https://user-images.githubusercontent.com/74600479/187722143-8be3885b-fedf-477a-90fe-8759070623a8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 84557
  cosmetic: 53290
  scriptlet: 17939
  html: 756
listset (total-discarded, last updated): 
  added: 
    HUN-0: 2174-5, 22h.34m
    JPN-1: 7721-23, 1d.16h.55m
    KOR-1: 3133-35, 22h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33170-114, 1d.17h
    ublock-badware: 4166-0, 1d.16h.59m
    ublock-privacy: 263-0, 5d.19h.3m
    ublock-abuse: 76-0, 5d.19h.2m
    ublock-unbreak: 1858-0, 1d.16h.58m
    easylist: 67065-575, 1d.16h.57m
    easyprivacy: 27442-638, 1d.16h.56m
    urlhaus-1: 6984-0, 22h.35m
    plowe-0: 3634-3, 1d.17h.1m
    ublock-quick-fixes: 407-0, 22h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 605 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    mafiatown.pl: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by MasterKia** [comment]
`mafiatown.pl##+js(set, aLoad, noopFunc)`

@MajkiIT

**Comment by krystian3w** [comment]
Rather @olegwukr after end bomb alarm at 🇺🇦.

**Comment by MasterKia** [comment]
https://github.com/MajkiIT/polish-ads-filter/graphs/contributors:
![Screenshot_20220831_212723](https://user-images.githubusercontent.com/17685483/187736288-610921aa-e5b0-443c-92b7-710bc429bc86.png)

**Comment by krystian3w** [comment]
Bad repo.

**Comment by MasterKia** [comment]
Line 5612 from https://github.com/MajkiIT/polish-ads-filter:

`filmweb.pl##+js(abort-current-inline-script.js, decodeURIComponent, newAdblockBoardDisplayed)`

**Comment by MasterKia** [comment]
https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_ublock.txt#L140:

`filmweb.pl##+js(abort-current-inline-script.js, decodeURIComponent, newAdblockBoardDisplayed)`

**Comment by krystian3w** [comment]
Legacy bad cleaned file and Eyeo law protection maybe ignore a mess in the supplement no compatible ABP.

**Comment by MasterKia** [comment]
The list you sent has barely been updated in the last year.
https://github.com/olegwukr/polish-privacy-filters/commits/master

**Comment by krystian3w** [comment]
But MajkiIT will not recover anti-adblock fixes in POL-0 instead POL-2.

you have to wait for Oleg's remote kick by the panniers and t to ignore the escape to the shelter.

**Comment by MasterKia** [comment]
Test the filter then I'll add to filters-2022.

**Comment by MasterKia** [comment]
You test the filter then I'll add to filters-2022.

**Comment by krystian3w** [comment]
IMO works fine @RozvM you have account to test page after login, maybe logged users have another bait or second bait to detect state `null`, `false`, `falseFunc`, `''` and `noopFunc`.

**Comment by MasterKia** [comment]
```
mafiatown.pl##+js(set, aLoad, noopFunc)
mafiatown.pl##+js(set, mtCanRunAdsSoItCanStillBeOnTheWeb, true)
```

@olegwukr

**Comment by RozvM** [comment]
> IMO works fine; @RozvM you have account to test page after login, maybe logged users have another bait or second bait to detect state `null`, `false`, `falseFunc`, `''` and `noopFunc`.
> 
> Or login form is fake and works for only wembaster and redactors.

I don't have an account but now the page works fine, after the commit you guys made. Thanks for the hard work and keep it up! 🙂
