### ISSUE TITLE
rtl.de: breakage

### ISSUE THREAD

**Issue by hagezi** [uBlockOrigin/uAssets#14617]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rtl.de/cms/formel-1-in-zandvoort-max-verstappen-gewinnt-lustiges-rennen-gegen-tsunoda-rueckwaerts-5004564.html`

### Category

breakage

### Describe the issue

Can't play video (play button is not displayed).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/104343908/187839130-6ca26d61-14ae-4329-9ad7-9387e8585694.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 12553
  cosmetic: 10436
  scriptlet: 20711
  html: 747
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    DEU-0: null
  added: 
    ublock-annoyances: 4562-4, 12h.10m
  default: 
    user-filters: 5-1, never
    ublock-filters: 33145-38, 12h.9m
    ublock-badware: 4181-0, 12h.16m
    ublock-privacy: 263-0, 1d.20m
    ublock-abuse: 76-0, 1d.19m
    ublock-unbreak: 1858-0, 12h.15m
    ublock-quick-fixes: 408-0, 54m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  cnameUncloakEnabled: false
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1083 ms
  maxAssetCacheWait: 55 ms
  unsuspendAfter: 848 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    akamaihd.net: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    outbrain.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I think we can move all `rtl.de` filters (in unbreak and ublock filters) to one place.

**Comment by MasterKia** [comment]
>   removed: 
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    DEU-0: null

@hagezi Why remove these filter lists?

**Comment by hagezi** [comment]
@MasterKia Only for testing and report. ;)
