### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by mazdek96** [uBlockOrigin/uAssets#14612]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=mF5NQS6bePc`

### Category

breakage

### Describe the issue

youtube videos arent opening sometimes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 84366
  cosmetic: 49475
  scriptlet: 18141
  html: 738
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 1h.13m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 22-0, never
    ublock-filters: 33166-46, 2d.1h.48m
    ublock-badware: 4166-0, 2d.1h.47m
    ublock-privacy: 263-0, 2d.23h.26m
    ublock-abuse: 76-0, 2d.23h.27m
    ublock-unbreak: 1855-0, 2d.1h.46m
    easylist: 67065-596, 2d.1h.45m
    easyprivacy: 27442-583, 2d.1h.49m
    plowe-0: 3633-3, 7d.3h.1m
    TUR-0: 8698-21, 2d.1h.44m
    urlhaus-1: 7332-0, 2h.19m
    ublock-quick-fixes: 409-0, 2h.18m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 431 ms (selfie)
  maxAssetCacheWait: 359 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    youtube.com: 9
    doubleclick.net: 2
    google.com: 2
    google.com.tr: 1
```
</details>

**Comment by MasterKia** [comment]
- [X] I verified that the issue has not already been reported (use this button to find out)

Comment here: https://github.com/uBlockOrigin/uAssets/issues/7636

Also see: https://github.com/easylist/easylist/wiki/youtube-issues

**Comment by MasterKia** [comment]
Duplicte of https://github.com/uBlockOrigin/uAssets/issues/7636
