### ISSUE TITLE
moviepilot.de: breakage

### ISSUE THREAD

**Issue by hagezi** [uBlockOrigin/uAssets#14619]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.moviepilot.de/movies/sieben-leben/trailer`

### Category

breakage

### Describe the issue

Video not loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b2
Chromium: 104
filterset (summary): 
  network: 12562
  cosmetic: 10440
  scriptlet: 20718
  html: 0
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    ublock-annoyances: 4559-4, 4h.55m
  default: 
    user-filters: 0-0, never
    ublock-abuse: 76-0, 4h.55m
    ublock-badware: 4202-0, 4h.55m
    ublock-filters: 32437-31, 4h.55m
    ublock-privacy: 241-0, 4h.55m
    ublock-quick-fixes: 404-4, 4h.55m
    ublock-unbreak: 1846-0, 4h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 144 ms (selfie)
  maxAssetCacheWait: 47 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    outbrain.com: 1
    smartadserver.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like it needs quite a lot of exceptions:

```
moviepilot.de##+js(nano-stb, _0x, *)
moviepilot.de##+js(no-xhr-if, doubleclick)

@@||cdn.lib.getjad.io/library/*Moviepilot$script,domain=moviepilot.de
@@||cdn.lib.getjad.io/prebid/*$script,domain=moviepilot.de
@@||securepubads.g.doubleclick.net/gpt/pubads_impl$script,domain=moviepilot.de
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=moviepilot.de
```

Anyone has other options?

**Comment by okiehsch** [comment]
Looks good to me.
