### ISSUE TITLE
jeep-cj.com [anti-adblock]

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#14626]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://jeep-cj.com` ( ==> `https://jeep-cj.com/community/` )

### Describe the issue

Hard anti-adblock.

### Screenshot(s)

![ss](https://user-images.githubusercontent.com/72945564/187960498-1625e1a5-157c-4162-9e2a-c16926558151.png)

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 104.1

### Settings

- default

**Comment by MasterKia** [comment]
> Hard anti-adblock.

**Comment by MasterKia** [comment]
> Hard anti-adblock.

Is it hard if it has an "No thanks" button?

**Comment by MasterKia** [comment]
> Hard anti-adblock.

Is it hard if it has a "No thanks" button?

**Comment by MasterKia** [comment]
Test:
`jeep-cj.com##+js(set, document.body.contains, trueFunc)`

**Comment by garry-ut99** [comment]
Yes, it's working.

**Comment by MasterKia** [comment]
@okiehsch Why these don't work?

`jeep-cj.com##+js(acis, document.body.contains)`
`jeep-cj.com##^script:has-text(document.body.contains)`

**Comment by garry-ut99** [comment]
`jeep-cj.com##^script:has-text(document.body.contains)` 
will not remove the anti-adblock, the assumption that it will do so is wrong.
