### ISSUE TITLE
lordz.io: ads

### ISSUE THREAD

**Issue by LukeBuonanno** [uBlockOrigin/uAssets#14621]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lordz.io/`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-01 082921](https://user-images.githubusercontent.com/93083273/187914001-0acb202d-6f4d-42e3-a01a-9691ee1b9107.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82579
  cosmetic: 43002
  scriptlet: 17736
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67065-51, 2d.17h.6m
    easyprivacy: 27442-126, 2d.17h.4m
    plowe-0: 3633-776, 11d.10h.23m
    ublock-abuse: 76-0, 2d.17h.9m
    ublock-badware: 4162-96, 2d.17h.5m
    ublock-filters: 32471-97, 2d.17h.3m
    ublock-privacy: 241-3, 2d.17h.10m
    ublock-quick-fixes: 404-4, 11h.22m
    ublock-unbreak: 1841-41, 2d.17h.7m
    urlhaus-1: 7332-0, 11h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 52 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1951 ms (selfie)
  maxAssetCacheWait: 1271 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adinplay.com: 2
    facebook.com: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    indexww.com: 1
    truepush.com: 1
    unity3d.com: 1
```
</details>

**Comment by Yuki2718** [comment]
It seems to be ad-reinjection.
