### ISSUE TITLE
find ads in swiggy

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uAssets#14625]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.swiggy.com/`

### Describe the issue

I find many ads here in this website which does not get blocked by ublock.

### uBlock Origin version

1,44

### Browser name and version

firefox 104

### Settings

None

**Comment by MasterKia** [comment]
@holequantum https://github.com/uBlockOrigin/uBlock-issues/issues/2231#issuecomment-1229225451

**Comment by MasterKia** [comment]
@holequantum https://github.com/uBlockOrigin/uBlock-issues/issues/2231#issuecomment-1229225451

URL + screenshots

**Comment by holequantum** [comment]
>https://www.swiggy.com/

![Screenshot from 2022-09-01 22-44-36](https://user-images.githubusercontent.com/108695843/187974159-4be4ed3a-902d-4d73-a2d2-f5d290785114.png)
![session-attachment-2022-09-01-224631](https://user-images.githubusercontent.com/108695843/187974175-91f934bd-fc02-4a69-9ac6-7d60857e375f.jpeg)
![session-attachment-2022-bh09-01-224631](https://user-images.githubusercontent.com/108695843/187974180-f857678f-f6cb-4e08-8a06-e23f8fb5695f.jpeg)

**Comment by MasterKia** [comment]
I can't sign up using virtual numbers (I tested 2 different sites).

Can you provide account info?
https://www.reddit.com/message/compose/?to=FreeLibre

**Comment by MasterKia** [comment]
For picture 3 and 4 account is not required and this works:
`swiggy.com##div[class]:has-text(/Promoted/):upward(a[href])`

For picture 1 and 2, account is required but I can't sign up using virtual numbers (I tested 2 sites => No SMS).
If you can provide login info I can take a look.
https://www.reddit.com/message/compose/?to=FreeLibre

**Comment by MasterKia** [comment]
Luckily account wasn't required.

@holequantum Test on desktop and mobile.

**Comment by holequantum** [comment]
Tested and seems like it is working fine thanks.

**Comment by Yuki2718** [comment]
Not really ads, tho EL sometimes hides these PRs AG, I, and a few others have been opposing.

**Comment by Yuki2718** [comment]
Moved to Annoyances

**Comment by MasterKia** [comment]
I'd argue those restaurants paid this site to get higher in the results.

**Comment by Yuki2718** [comment]
The past discussion on Slack also didn't reach an agreement. So EL tends to hide them, AG not (hides in Annoyances), uBO case by case. We had at least one similar case and hid that, but on this page hiding them only makes outlook ugly without any saved space. Other than being paid, these PRs are legit and useful search results only distinguisable by the label.

**Comment by Yuki2718** [comment]
Also regarding EL policy, that is about 3p ads. The policy clearly states this.

**Comment by MasterKia** [comment]
> Self-promotion

This does not qualify as self-promotion (clearly says "Ad"):
https://user-images.githubusercontent.com/108695843/187974175-91f934bd-fc02-4a69-9ac6-7d60857e375f.jpeg

**Comment by MasterKia** [comment]
> So EL tends to hide them, AG not (hides in Annoyances)

Personally this doesn't make a difference for as I don't use this site, but I'd go with EL decision instead of AG.
> The rationale on whether to include a specific filter in one of uBO's filter lists is the same as outlined by EasyList].

**Comment by Yuki2718** [comment]
Many of self-promotion are actually labelled as Ad. Maybe we should move to internal discussion.

**Comment by MasterKia** [comment]
@holequantum For now you should enable the "uBlock Annoyances" filter list.

**Comment by holequantum** [comment]
Okey!
