### ISSUE TITLE
Too general rule which hides pictures on search.seznam.cz

### ISSUE THREAD

**Issue by Huararanga** [uBlockOrigin/uAssets#14628]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://search.seznam.cz/?q=radlicka+10`

### Describe the issue

Rule https://github.com/uBlockOrigin/uAssets/blame/master/filters/quick-fixes.txt#L69 removes panorama on the right of the map.
The rule seems to be so unspecific, that it can posibbly remove multiple unwanted elements on the site.

Please delete this rule, it does not work for hiding ads, but it is hiding valuable content

### Screenshot(s)

![image](https://user-images.githubusercontent.com/17761193/187965016-06ddf50e-6ad3-415b-801f-4edeb8763b82.png)

### uBlock Origin version

1.44.0

### Browser name and version

chrome 99.0.4844.74, windows 10

### Settings

no changes

**Comment by MasterKia** [comment]
@mapx- These filters don't match anymore: https://github.com/uBlockOrigin/uAssets/commit/af27ab756fffb92d2869876dece96df060c07e3a
