### ISSUE TITLE
[nsfw] techymozo.com: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14639]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techymozo.com/b85BtJ`

### Category

nuisance

### Describe the issue

Can u Remove all the useless things in this page ? Skip the timer or waiting time too ?

it opens pages In 3 links from time to time 

veganal.co
veganho.co
themorningtribune.com

After that it opens a push.bdnewsx. link which has useless buttons and timer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 106
filterset (summary): 
  network: 93895
  cosmetic: 82584
  scriptlet: 20487
  html: 741
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 58068-2188, 30m
    IND-0: 11385-1, 30m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33273-297, 30m
    ublock-badware: 4205-0, 30m
    ublock-privacy: 263-1, 30m
    ublock-abuse: 76-0, 30m
    ublock-unbreak: 1864-0, 30m
    ublock-quick-fixes: 414-0, 30m
    adguard-mobile: 8038-168, 30m
    easylist: 66208-21799, 30m
    easyprivacy: 27451-623, 30m
    urlhaus-1: 7364-0, 30m
    plowe-0: 3671-3, 30m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 507 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
> The connection has timed out

The server at techymozo.com is taking too long to respond

**Comment by MasterKia** [comment]
> The connection has timed out
The server at techymozo.com is taking too long to respond

**Comment by iSmokeMid69** [comment]
> > The connection has timed out
> > The server at techymozo.com is taking too long to respond

maybe try with a vpn - india/Asia

**Comment by MasterKia** [comment]
@iSmokeMid69 Force update your filter lists and test.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by MasterKia** [comment]
@iSmokeMid69 `https://techymozo.com/b85BtJ` doesn't work anymore.
