### ISSUE TITLE
xo.gr: ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#14637]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.xo.gr/profile/profile-911640078/el/`

### Category

ads

### Describe the issue

Intrusive prompt to buy online advertising services.

### Screenshot(s)

<details>

![Screenshot 2022-09-02 at 08-36-39 9ο ΝΗΠΙΑΓΩΓΕΙΟ ΑΙΓΑΛΕΩ Δημόσιο Νηπιαγωγείο Αιγάλεω Αττικής 2105692733 xo gr](https://user-images.githubusercontent.com/101707608/188067247-30bbe682-a442-4323-b569-f7d5a0ffb7e6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 264863
  cosmetic: 234093
  scriptlet: 38063
  html: 744
listset (total-discarded, last updated): 
  added: 
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1d.1h.26m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 45963-1025, 1h.13m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1038-0, 3d.19h.52m
    https://www.i-dont-care-about-cookies.eu/abp/: 25316-5, 1h.12m
    adguard-generic: 67156-5830, 3d.19h.46m
    adguard-mobile: 8164-189, 3d.19h.45m
    adguard-spyware: 25442-924, 3d.19h.39m
    adguard-spyware-url: 725-2, 3d.19h.38m
    block-lan: 43-0, 13d.15h.32m
    curben-phishing: 81940-9, 1h.9m
    curben-pup: 188-0, 1h.8m
    adguard-annoyance: 56824-5645, 3d.13h.53m
    adguard-social: 18328-1083, 3d.13h.52m
    fanboy-thirdparty_social: 69-0, 3d.19h.55m
    fanboy-annoyance: 80183-64277, 3d.19h.54m
    fanboy-cookiemonster: 40703-9229, 3d.19h.53m
    fanboy-social: 23310-31, 3d.13h.51m
    ublock-annoyances: 4558-6, 3d.13h.50m
    dpollock-0: 11387-484, 1d.18h.27m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33190-207, 3d.19h.51m
    ublock-badware: 4166-0, 3d.19h.50m
    ublock-privacy: 263-0, 3d.19h.49m
    ublock-abuse: 76-4, 3d.19h.48m
    ublock-unbreak: 1855-1, 3d.19h.47m
    ublock-quick-fixes: 417-0, 1h.11m
    easylist: 67099-3141, 3d.19h.44m
    easyprivacy: 27442-9764, 3d.19h.37m
    urlhaus-1: 7364-0, 1h.10m
    plowe-0: 3671-5, 1h.14m
    GRC-0: 1002-1, 1d.1h.27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1295 ms (selfie)
  maxAssetCacheWait: 2001 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    xo.gr: 3
    google.gr: 1
    googletagmanager.com: 1
    newrelic.com: 1
```
</details>

**Comment by MasterKia** [comment]
https://user-images.githubusercontent.com/17685483/188071138-a699f417-9ec3-4522-966d-8e11483ce2a5.png

This translates to:
> Choose the XO promotion package that suits you, promote your business and win customers!

So this is self-promotion, not an advertisement.

Go to uBlock Origin settings => My filters => Add:
`xo.gr##.purchaseOnline-msg`
