### ISSUE TITLE
totaldebrid.org [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1463]
URL(s) where the issue occurs

`https://totaldebrid.org/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by ghajini** [comment]
Antiadblock again
`http://totaldebrid.ml/shorti/pub/?file=0e52fb4a55a1f64`

**Comment by ghajini** [comment]
Antiadblock
`http://totaldebrid.org/shorti/pub/?file=92fc79abb4c8876`
![IMG_20191203_120111](https://user-images.githubusercontent.com/20338483/70026099-df28fc80-15c4-11ea-8c1a-28b749fa21e6.jpg)

**Comment by ghajini** [comment]
Antiadblock 
`http://totaldebrid.org/files/api.php?info=aHR0cHM6Ly93d3cuY2xpY3R1bmUuY29tLzdNTHU=`

**Comment by ghajini** [comment]
Offtopic= so I should post clickable links?

**Comment by uBlock-user** [comment]
>  so I should post clickable links?

clickable links to websites ? No.

**Comment by mapx-** [comment]
In this case it's ok, githubusercontent link
