### ISSUE TITLE
ygeiaonline.gr: ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#14638]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ygeiaonline.gr/listing/%CE%B1%CE%B8%CE%AE%CE%BD%CE%B1/%CE%B3%CE%B9%CE%B1%CF%84%CF%81%CE%BF%CE%AF/%CF%83%CE%B2%CE%BF%CE%BB%CE%BF%CF%80%CE%BF%CF%85%CE%BB%CE%BF%CF%85-%CE%B1%CE%B9%CE%BA%CE%B1%CF%84%CE%B5%CF%81%CE%B9%CE%BD%CE%B7/`

### Category

ads

### Describe the issue

Booking ad banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-02 at 08-50-37 Σβολοπουλου Αικατερινη Βρες γιατρό](https://user-images.githubusercontent.com/101707608/188068281-3c1f67da-2a76-475a-b6d0-8ec9f73ad74b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 264863
  cosmetic: 234093
  scriptlet: 38063
  html: 744
listset (total-discarded, last updated): 
  added: 
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1d.1h.38m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 45963-1025, 1h.24m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1038-0, 3d.20h.3m
    https://www.i-dont-care-about-cookies.eu/abp/: 25316-5, 1h.23m
    adguard-generic: 67156-5830, 3d.19h.57m
    adguard-mobile: 8164-189, 3d.19h.56m
    adguard-spyware: 25442-924, 3d.19h.50m
    adguard-spyware-url: 725-2, 3d.19h.49m
    block-lan: 43-0, 13d.15h.43m
    curben-phishing: 81940-9, 1h.20m
    curben-pup: 188-0, 1h.19m
    adguard-annoyance: 56824-5645, 3d.14h.4m
    adguard-social: 18328-1083, 3d.14h.3m
    fanboy-thirdparty_social: 69-0, 3d.20h.6m
    fanboy-annoyance: 80183-64277, 3d.20h.5m
    fanboy-cookiemonster: 40703-9229, 3d.20h.4m
    fanboy-social: 23310-31, 3d.14h.2m
    ublock-annoyances: 4558-6, 3d.14h.1m
    dpollock-0: 11387-484, 1d.18h.38m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33190-207, 3d.20h.2m
    ublock-badware: 4166-0, 3d.20h.1m
    ublock-privacy: 263-0, 3d.20h
    ublock-abuse: 76-4, 3d.19h.59m
    ublock-unbreak: 1855-1, 3d.19h.58m
    ublock-quick-fixes: 417-0, 1h.22m
    easylist: 67099-3141, 3d.19h.55m
    easyprivacy: 27442-9764, 3d.19h.48m
    urlhaus-1: 7364-0, 1h.21m
    plowe-0: 3671-5, 1h.25m
    GRC-0: 1002-1, 1d.1h.39m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1295 ms (selfie)
  maxAssetCacheWait: 2001 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ygeiaonline.gr: 8
    googlesyndication.com: 1
    googletagmanager.com: 1
    webpushr.com: 1
```
</details>

**Comment by MasterKia** [comment]
Is this a booking site?
Can you send a wider screenshot and point to the ads?

**Comment by MasterKia** [comment]
Can you send a wider screenshot and point to the ads?

**Comment by DimitrisKalaboukas** [comment]
@MasterKia No, it is a health site.

**Comment by MasterKia** [comment]
Please do this: https://github.com/uBlockOrigin/uAssets/issues/14638#issuecomment-1235115333

**Comment by DimitrisKalaboukas** [comment]
![Screenshot 2022-09-05 at 08-43-28 Σβολοπουλου Αικατερινη](https://user-images.githubusercontent.com/101707608/188368910-4b8f460a-1623-4b25-8212-98767504e6d1.png)

**Comment by mapx-** [comment]
Use the element picker trying to create a filter or report directly at Greek list repository
https://github.com/kargig/greek-adblockplus-filter/issues
