### ISSUE TITLE
UKTVPlay Video Controls

### ISSUE THREAD

**Issue by cosycloud** [uBlockOrigin/uAssets#14636]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://uktvplay.co.uk/shows/jon-richardson-ultimate-worrier/series-1/episode-6/5817156698001`

### Describe the issue

When uBlock Origin is enabled for the ukTVplay website it does indeed block the ads in Chrome. However, video controls are also disabled. They appear on the screen but you cannot pause, rewind, fast forward or change the volume. The bottom "scrub" bar stays at the bottom making it not possible to click anything underneath but then you can't use it for moving through the video either. You also can't click on the video to pause. 

This did work before but maybe in the last couple months the above started happening. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3666024/188062561-a4ef4fa7-fb64-4333-8a3b-948f078f022d.png)

### uBlock Origin version

 1.44.0

### Browser name and version

Chrome Version 104.0.5112.102

### Settings

default settings

**Comment by ghajini** [comment]
@ryanbr 
player controls are broken => play,pause etc
By EP
`@@||tag.aticdn.net/*/smarttag.js$script,domain=uktvplay.co.uk`

site account=
`http://bugmenot.com/view/uktvplay.co.uk`

**Comment by cosycloud** [comment]
I don't know if this is a faux pas or not - but wowie! already working again. You folks are amazing! Thanks!!!
