### ISSUE TITLE
gamingzion.com [anti-adblock]

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#14630]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gamingzion.com/`

### Describe the issue

Hard anti-adblock (or just an annoyance because at the bottom?...I don't remember)

### Screenshot(s)

![dd](https://user-images.githubusercontent.com/72945564/187973310-898c79a8-3a34-4b3b-aedf-46e06e92f95d.png)

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 104.1

### Settings

- default
- Fanboy Annoyance & AdGuard Annoyance & uBO Annoyance didn't help

**Comment by MasterKia** [comment]
> or just an annoyance because at the bottom?...I don't remember

If it can't be dismissed and disrupts user experience then it's hard anti-blocker.
