### ISSUE TITLE
plctalk.net: nuisance

### ISSUE THREAD

**Issue by HaxNobody** [uBlockOrigin/uAssets#14645]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://www.plctalk.net/qanda/forumdisplay.php?f=2`

### Category

nuisance

### Describe the issue

Flashing/blinking Gifs and widgets at the top of the page, as well as modal prompts occasionally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 94830
  cosmetic: 177561
  scriptlet: 24928
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.15h.38m
    adguard-annoyance: 58084-83, 5h.31m
    adguard-social: 18332-874, 3d.6h.11m
    fanboy-annoyance: 80181-4660, 3d.17h.40m
    fanboy-thirdparty_social: 69-21, 4d.5h.47m
    ublock-annoyances: 4559-209, 5h.36m
  default: 
    easylist: 66206-107, 5h.32m
    easyprivacy: 27439-225, 4d.16h.25m
    plowe-0: 3634-779, 1d.23h.41m
    ublock-abuse: 76-0, 1d.23h.42m
    ublock-badware: 4202-101, 5h.35m
    ublock-filters: 32466-507, 5h.34m
    ublock-privacy: 241-11, 2d.3h.44m
    ublock-quick-fixes: 405-4, 16h.43m
    ublock-unbreak: 1846-46, 5h.33m
    urlhaus-1: 7364-0, 16h.44m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 30 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 942 ms (selfie)
  maxAssetCacheWait: 622 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
Banners are self-promotion, not ads (plctalk.net => plcs.net)
Go to uBlock Origin settings => My filters => Add these:
```
||plctalk.net/bookanim.gif
||plctalk.net/storean2.gif
```

I didn't get any "modal prompts".
