### ISSUE TITLE
techus.website: nuisance

### ISSUE THREAD

**Issue by shawon2901** [uBlockOrigin/uAssets#14649]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techus.website/`

### Category

nuisance

### Describe the issue

First Open > `https://mlwbd.fit/movie/cobra-2022/`
Then Download > 1080p
Then Opens Techus.website & I Have To Click 7-8 Times To Reach 1st Destination Which Is a SongLyric.com Website..Remove Usless Stuff And Also Bypassing Those 7-8 Time Clicks If Possible
Then Any Download Link In Songlyric.com Also Has Usless Stuff In Page Remove Those Too

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium Mobile: 105
filterset (summary): 
  network: 84734
  cosmetic: 27062
  scriptlet: 17815
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    adguard-mobile: 8038-28, 13h.53m
    easylist: 66213-21306, 13h.51m
    easyprivacy: 27451-137, 13h.50m
    plowe-0: 3671-900, 13h.49m
    ublock-abuse: 76-0, 13h.47m
    ublock-badware: 4201-100, 53m
    ublock-filters: 32574-364, 53m
    ublock-privacy: 241-2, 53m
    ublock-quick-fixes: 416-4, 53m
    ublock-unbreak: 1851-43, 53m
    urlhaus-1: 7919-0, 53m
filterset (user): [empty]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 646 ms
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adnxs.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    media.net: 1
```
</details>

**Comment by MasterKia** [comment]
We have already boosted the timer so you don't have to wait.
`techus.website##+js(nano-setInterval-booster, counter, *)`

**Comment by MasterKia** [comment]
The timer is already boosted so you don't have to wait.
`techus.website##+js(nano-setInterval-booster, counter, *)`

**Comment by MasterKia** [comment]
For the useless content, go to uBlock Origin settings => My filters => Add these:
```
techus.website###download-button, #generate-link, .button, #main-download:others()
specx.me##.butt:others()
```

**Comment by iSmokeMid69** [comment]
> For the useless content, go to uBlock Origin settings => My filters => Add these:
> 
> ```
> techus.website###download-button, #generate-link, .button, #main-download:others()
> specx.me##.butt:others()
> ```

I Did Clean Everything With Element Picker But Wanted To Know If those Multiple Clicks Could Be Bypassed..Thanks AnyWay
