### ISSUE TITLE
android.com.pl: ads

### ISSUE THREAD

**Issue by szyha** [uBlockOrigin/uAssets#14644]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://android.com.pl/tech/510780-5-lat-wsparcia-dla-kazdego-smartfona/`

### Category

ads

### Describe the issue

ad in background article

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_2SMCq03H59](https://user-images.githubusercontent.com/12976368/188156190-e724a471-1614-42a5-9008-f6fc39397523.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 134488
  cosmetic: 204415
  scriptlet: 52249
  html: 1031
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 362-0, now
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1942-2, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 21689-364, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 881-0, now
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 12889-1, now
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24082-72, now
    https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt: 143-0, now
    https://www.i-dont-care-about-cookies.eu/abp/: 25316-145, now
    adguard-generic: 69497-6223, now
    adguard-spyware: 26687-1116, now
    adguard-spyware-url: 745-107, now
    fanboy-annoyance: 80038-32896, now
    fanboy-social: 23314-23, now
    ublock-annoyances: 4567-44, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33187-2908, now
    ublock-badware: 4206-0, now
    ublock-privacy: 263-2, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1859-3, now
    ublock-quick-fixes: 420-0, now
    easylist: 66208-663, now
    easyprivacy: 27451-9520, now
    urlhaus-1: 7919-0, now
    plowe-0: 3671-13, now
    POL-0: 7847-30, now
    POL-2: 1279-12, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 803 ms (selfie)
  maxAssetCacheWait: 3483 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    optad360.io: 2
```
</details>

**Comment by MasterKia** [comment]
`android.com.pl##.banner--custom`

@MajkiIT @krystian3w

**Comment by MasterKia** [comment]
@krystian3w You don't have write access for `Polish ads filter`?

**Comment by krystian3w** [comment]
Yes, I can only create PR and wait to merge.

But long time don't created any to hide/block ads.

**Comment by MajkiIT** [comment]
@MasterKia Thanks

**Comment by szyha** [comment]
After updating filters, site does not display article and home page does not display anything.
![firefox_gi4Yg43wzT](https://user-images.githubusercontent.com/12976368/188232571-d664f4e5-0533-452a-82d6-40c2ea2ec526.png)

Tested on clear Firefox and Chrome with default settings.

**Comment by krystian3w** [comment]
How? Please use dom inspector:

https://github.com/gorhill/uBlock/wiki/DOM-inspector

**Comment by krystian3w** [comment]
@MajkiIT I see in same article placeholders in middle column:

```
##aside.banner--content.banner
```

**Comment by szyha** [comment]
> How? Please use dom inspector:
> 
> https://github.com/gorhill/uBlock/wiki/DOM-inspector

It seems to me that I did good.

![Zrzut ekranu 2022-09-03 000252](https://user-images.githubusercontent.com/12976368/188241235-f76f5a3b-a457-491f-9566-45ad73f73f16.png)

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/188251661-6171507c-737f-4f89-aab8-4ba206f6397f.png)

**Comment by krystian3w** [comment]
So `.has-screening` ad is guilty?

**Comment by szyha** [comment]
Try to make the page smaller. In my case on my computer when I have 120% of the size then the page displays correctly.

https://user-images.githubusercontent.com/12976368/188258638-c0b9ae04-64c4-4467-9f9d-a4abdfcecabd.mp4

**Comment by MasterKia** [comment]
@MajkiIT

**Comment by krystian3w** [comment]
IMO the best is add `:not([class*="screen"])`.

Ads can be clickable after only network block few resources.

**Comment by szyha** [comment]
In Adguard filters has already been fixed (https://github.com/AdguardTeam/AdguardFilters/commit/3f9b0f6e9503cbe2ae4fc5115035a1aeca9948ab).
It is possible to add temporarily to ``uBlock filters - Unbreak``?

**Comment by MasterKia** [comment]
So https://github.com/AdguardTeam/AdguardFilters/commit/3f9b0f6e9503cbe2ae4fc5115035a1aeca9948ab fixes the breakage?

**Comment by szyha** [comment]
On the default settings the site works but keeps showing the ad. It seems to me that something was changed in the code of the site.

**Comment by krystian3w** [comment]
IMO this is still bug with screening, not new anti-adblock to hide main content.
