### ISSUE TITLE
vg.no: breakage

### ISSUE THREAD

**Issue by nepse1** [uBlockOrigin/uAssets#14646]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vg.no/rampelys/tv/i/jl9Lxw/henning-solberg-trakk-seg-fra-kompani-lauritzen-paa-grunn-av-rettssak`

### Category

breakage

### Describe the issue

Page render and is visible a half second then main body is removed and only header and footer is visible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 104
filterset (summary): 
  network: 84939
  cosmetic: 29013
  scriptlet: 17831
  html: 742
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33273-296, 10h.41m
    ublock-badware: 4205-0, 22h.4m
    ublock-privacy: 263-1, 7d.10h.32m
    ublock-abuse: 76-0, 7d.10h.31m
    ublock-unbreak: 1860-0, 3d.21h.38m
    adguard-mobile: 8038-169, 22h.6m
    easylist: 67065-22746, 3d.13h.58m
    easyprivacy: 27450-588, 22h.5m
    urlhaus-1: 7364-0, 11h.40m
    plowe-0: 3633-3, 11d.18h.33m
    NOR-0: 3031-179, 11h.41m
    ublock-quick-fixes: 407-0, 11h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4381 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adnxs.com: 1
    brandmetrics.com: 1
    medietall.no: 2
    schibsted.io: 1
```
</details>

**Comment by shawon2901** [comment]
Tested With FireFox Android And Kiwi Cant Reproduce.. Working Fine Here...Try Resetting Ublock And Updating Default List

**Comment by krystian3w** [comment]
Nordic list recommend enable AdGuard Base and disable EasyPrivacy (maybe possible enable AdGuard Tracking Protection).

If then works, so AdGuard use scriptlet or redirect resource to disable blink.

**Comment by mapx-** [comment]
@nepse1 add
`vg.no#@#div[class*=" hyperion-css-"][data-ad-subtype]:upward(1)`

@DandelionSprout

**Comment by krystian3w** [comment]
Worse if these filter needed deletion due EasyPrivacy filtering only.
