### ISSUE TITLE
Digital Photography school webpages not fully loading with u block origin FF extension active 

### ISSUE THREAD

**Issue by Rackmani** [uBlockOrigin/uAssets#14641]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://digital-photography-school.com/four-ways-improve-photos-clarity-slider-lightroom/`

On latest FF 104.0.1 web pages from this site not fully loading with u block origin active - fine when not or in safari.  can anyone help?

### Describe the issue

On latest FF 104.0.1 web pages from this site not fully loading with u block origin active - fine when not or in safari.  can anyone help?  get warning also slowing FF down 

### Screenshot(s)

<img width="1393" alt="Screenshot 2022-09-02 at 11 05 16" src="https://user-images.githubusercontent.com/57327107/188116376-33ef23b3-5d40-48b7-8365-3541cd1283cb.png">

### uBlock Origin version

1.4.4.0

### Browser name and version

FF 104.0.1 on a Mac 

### Settings

None 

### Notes

Fine when switched off and on safari but then ads not blocked

**Comment by krystian3w** [comment]
JavaScript conflict - maybe due block needed file.

**Comment by MasterKia** [comment]
I can reproduce using Firefox 104.0 but not Firefox ~91.

**Comment by Rackmani** [comment]
I've just played around and if I switch off the Easylist filter the webpage loads fine.  Is it possible to switch off  just this one filter for this site permanantely?

**Comment by stephenhawk8054** [comment]
I cannot reproduce it with default lists:

![image](https://user-images.githubusercontent.com/66517106/188121726-e33a6337-57d1-4d75-ad08-a61b5974e3ea.png)

Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by Rackmani** [comment]
Interesting.  i've just completely reinstalled ublock origin back to all defaults and I still have the issue.  If I switch off the EasyList filter I then don't get the problem 
Note I'm on an iMac

**Comment by okiehsch** [comment]
I can reproduce the "slowing down" waring and the site becomes unresponsive after a while.

**Comment by okiehsch** [comment]
@Rackmani Does adding
`@@||cdn.bluebillywig.com/apps/player/*/admanager$script,domain=digital-photography-school.com`
to your filter list works for you?

**Comment by Rackmani** [comment]
> @Rackmani Does adding `@@||cdn.bluebillywig.com/apps/player/*/admanager$script,domain=digital-photography-school.com` to your filter list works for you?

Yeah wow...how did you do that!  It works!!!

**Comment by krystian3w** [comment]
For me works:

`aopr, window.bluebillywing.adBlockaDetected`.

**Comment by Rackmani** [comment]
Haven't tried your filter krystian3w but okiehsch filter has worked for me adding it to my filter list.  Crazy you guys are geniouses.  Do I need to report this to Easylist people?

**Comment by okiehsch** [comment]
@ryanbr 
`@@||cdn.bluebillywig.com/apps/player/*/admanager$script,domain=digital-photography-school.com`

**Comment by okiehsch** [comment]
> Do I need to report this to Easylist people?

No need, I pinged them in my comment above.

**Comment by okiehsch** [comment]
> aopr, window.bluebillywing.adBlockDetected.

`digital-photography-school.com##+js(aopr, bluebillywing.adBlockDetected)`
does not work on my end.

**Comment by okiehsch** [comment]
Seeing as it completely breaks the site I will add my filter to quick fixes and remove it after a few days.

**Comment by Rackmani** [comment]
> Seeing as it completely breaks the site I will add my filter to quick fixes and remove it after a few days.

Cheers buddy wishing you the best of Karma 🙏
