### ISSUE TITLE
thetimes.co.uk: breakage

### ISSUE THREAD

**Issue by rafikiphoto** [uBlockOrigin/uAssets#14655]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thetimes.co.uk/article/sailors-prepare-to-take-on-solo-round-the-world-golden-globe-race-90kwgww6g`
This breakage occurs with all `www.thetimes.co.uk` article pages which have comments allowed, some don't.

### Category

breakage

### Describe the issue

When uBO is active the comments section below the articles will not show the comments section (most articles allow comments but some do not). When uBO is switched off the comments sections appear as expected.
https://user-images.githubusercontent.com/28431654/188258602-e4450123-6204-4b4b-bcaa-18a0501292b1.png

https://user-images.githubusercontent.com/28431654/188258603-c0b03537-b48d-4b3b-b774-43bd2c5b00c7.png
Upper screenshot without uBO, lower screenshot with uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 83227
  cosmetic: 42925
  scriptlet: 17740
  html: 739
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-0, never
    ublock-filters: 33172-37, 3d.11h.49m
    ublock-badware: 4181-0, 3d.11h.48m
    ublock-privacy: 263-0, 3d.11h.47m
    ublock-abuse: 76-0, 3d.11h.46m
    ublock-unbreak: 1855-0, 3d.11h.45m
    ublock-quick-fixes: 420-0, 10h.48m
    easylist: 67008-590, 3d.11h.44m
    easyprivacy: 27444-578, 3d.11h.43m
    urlhaus-1: 7919-0, 10h.49m
    plowe-0: 3633-3, 9d.9h.48m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 406 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    thetimes.co.uk: 6
    google.com: 15
    newrelic.com: 1
    unrulymedia.com: 1
```
</details>

**Comment by MasterKia** [comment]
> account required

https://user-images.githubusercontent.com/17685483/188263511-d97379a6-469e-420f-9f2e-3072355d92a6.png
https://user-images.githubusercontent.com/17685483/188263521-3123a891-3773-4d20-82cd-49bbe0d9421b.png

**Comment by rafikiphoto** [comment]
Not sure what I can do about that?

**Comment by MasterKia** [comment]
Unless you can provide login info (privately ofc), we should hope someone has a subscription for the site.

**Comment by okiehsch** [comment]
> Not sure what I can do about that?

Nobody here expects you to give away private login info
 What we are saying is that we can't to do much about it ourselves. :wink:

You can post all blocked requests on your end here using  https://github.com/gorhill/uBlock/wiki/The-logger
Then we can try to debug the issue together.

**Comment by rafikiphoto** [comment]
No suggestion that I thought that at all.
In the meantime I have made one small adjustment in advanced mode to allow The Times locally. That has fixed it. 
Thanks for looking at it.

**Comment by Desmo46** [comment]
I have the same issue which seems to be worked around by disabling EasyPrivacy

**Comment by rafikiphoto** [comment]
Thanks. That seems to have fixed it here too.

**Comment by mapx-** [comment]
disabling EP is a very bad idea.
If you can share your account credentials we could investigate to find a real fix.
https://github.com/uBlockOrigin/uAssets/issues/15463#issuecomment-1374445371

**Comment by rafikiphoto** [comment]
> disabling EP is a very bad idea. If you can share your account credentials we could investigate to find a real fix. [#15463 (comment)](https://github.com/uBlockOrigin/uAssets/issues/15463#issuecomment-1374445371)

Thanks.

Done.

Brian.

**Comment by mapx-** [comment]
@rafikiphoto 

- tested FF / chrome, I get the comments section on the article above
- tested this article too (for the low resolution issue), still no issue (and comments visible too)
`https://www.thetimes.co.uk/article/james-corden-interview-catlin-moran-late-late-show-v5sf2vnpb`

**Comment by mapx-** [comment]
only a filter for some ads placeholder
`thetimes.co.uk##[class^="responsive__InlineAdWrapper"]`

**Comment by mapx-** [comment]
only an idea if you still have the issue, test this filter

`@@||thetimes.co.uk/assets/optimizely/custom/tnl_custom_snippet.js$script,1p`

**Comment by stephenhawk8054** [comment]
I can reproduce the issue and mapx's filter works for me.

**Comment by Desmo46** [comment]
Tested on https://www.thetimes.co.uk/article/prince-harry-had-second-thoughts-about-his-memoir-spare-after-uk-visit-86g8nxf89
Before and after with @mapx- 's filter and that seems to resolve the issue for me.
Not sure if its helpful but the Adguard filters which are based on the same underlying block lists as uBlock did not show the same issue
