### ISSUE TITLE
Cannot enter a location into the edit box 

### ISSUE THREAD

**Issue by Tighbu** [uBlockOrigin/uAssets#14650]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

weather.com

### Describe the issue

Weather.com has an edit box at the top of every screen. With unlock enabled, touching on the edit box does not put it into edit mode or get the on-screen keyboard to pop up as it should, so it's not possible to enter a place name.

### uBlock Origin version

1.44.0

### Browser name and version

Firefox Android 104.1.0

### Settings

None 

### Notes

Disabling Ublock allows the website to work normally

**Comment by stephenhawk8054** [comment]
It's fixed recently. Force update your filter lists ([click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by Tighbu** [comment]
Thank you, that works
