### ISSUE TITLE
hktvmall.com

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#14653]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [ ] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.hktvmall.com/hktv/en/
https://www.hktvmall.com/hktv/en/deals
https://www.hktvmall.com/hktv/en/cs-help
```

### Describe the issue

Analytics and tracking scripts (that can be blocked without affecting site functionality). Scripts are requested in batches in the form of `https://www.hktvmall.com/yuicombo?[script_path1]&[script_path2]&` which are then 302-redirected to `https://www.hktvmall.com/_ui/uilibrary/yui/cache/[hash].js?[timestamp]`.

```
||hktvmall.com/yuicombo?$script,removeparam=/^\/_ui\/desktop\/common\/js\/uiAnalytics\//
||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/analytics/commonComponentsAnalytics.js
||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/analytics/with-intersection-track.js
||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/InappCommunicationManager.js
||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/util/jquery.analytics-utils.js
||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/util/Logger.js
```

Scripts are __not__ fetched in batches on `https://www.hktvmall.com/hktv/en/deals` and `https://www.hktvmall.com/hktv/en/cs-help` (except for anything related to `/_ui/addons/hktvcheckoutaddon/`). It would be easier to inspect script contents there if you wanted to.

```
||hktvmall.com/_ui/desktop/common/js/uiAnalytics/$script,domain=hktvmall.com
||hktvmall.com/_ui/shared/common/js/InappCommunicationManager.js^$script,domain=hktvmall.com
||hktvmall.com/_ui/shared/common/js/analytics/commonComponentsAnalytics.js^$script,domain=hktvmall.com
||hktvmall.com/_ui/shared/common/js/analytics/with-intersection-track.js^$script,domain=hktvmall.com
||hktvmall.com/_ui/shared/common/js/util/jquery.analytics-utils.js^$script,domain=hktvmall.com
||hktvmall.com/_ui/shared/common/js/util/Logger.js^$script,domain=hktvmall.com
```

`headerAnalytics.js` is always fetched separately so we will only need one rule for it.

```
/_ui/shared/common/js/headerAnalytics.js^$script,domain=hktvmall.com
```

The order of these batch requests can be somewhat random and the server will return 500 Internal Server Error when there is no trailing query parameter behind `yuicombo`. These modified requests should also be blocked.

```
||hktvmall.com/yuicombo|$script,domain=hktvmall.com
```

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 104.0.1

### Settings

AdGuard Chinese

**Comment by krystian3w** [comment]
Maybe the best test first in Legitimate URL Shortener:

https://github.com/DandelionSprout/adfilt/discussions/163#issue-comment-box

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
He don't add removeparam.

**Comment by MasterKia** [comment]
@Yuki2718 Maybe AdGuard URL Tracking Protection?

**Comment by MasterKia** [comment]
Maybe AdGuard URL Tracking Protection?

**Comment by krystian3w** [comment]
Or remove both posts and lock conversation.

**Comment by mapx-** [comment]
for the scripts in batches it's enough a classic filter

`||hktvmall.com/yuicombo?$script,1p`

**Comment by krystian3w** [comment]
(¿)Request exist in logger (?), if nope maybe is created as invisible for MV2+ add-on (then possible test with uBo Legacy to detect this as visible request if browser are not too old).

**Comment by mapx-** [comment]
@otksm I added your filters in `uBlock filters – Privacy` list, could you test again for breakage ?

**Comment by Yuki2718** [comment]
@otksm It regex necessary?

**Comment by Yuki2718** [comment]
Ah, all right. No problem in using regex if there's no breakage.
