### ISSUE TITLE
manwa.fun: detection

### ISSUE THREAD

**Issue by CallMeChin** [uBlockOrigin/uAssets#14652]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://manwa.fun/chapter/731147`

### Category

detection

### Describe the issue

`您目前使用的浏览器与本站功能不相符或请关闭adblock插件或关闭浏览器“阻挡广告”的设定，会导致许多BUG出现，为了让您有更好的观看体验，强烈建议使用 Chrome 或Safari或 Edge 等浏览器，若无法下载，请复制下载连结使用其他浏览器下载，祝您观看愉快。`

`The browser you are currently using does not conform to the functions of this site, or please close the adblock plug-in or the "blocking ads" setting of the browser, which will cause many bugs to appear. In order to give you a better viewing experience, it is strongly recommended to use Chrome or Browsers such as Safari or Edge, if you cannot download, please copy the download link and use other browsers to download, I wish you a happy viewing.`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="956" alt="image" src="https://user-images.githubusercontent.com/77185235/188254614-cb1c7230-a411-436f-bd01-e5f55bc02c2e.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 101236
  cosmetic: 52654
  scriptlet: 17860
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 29111-90, 1m
  default: 
    user-filters: 0-0, never
    easylist: 66503-81, 1d.15h.31m
    easyprivacy: 27449-150, 1d.15h.30m
    plowe-0: 3634-779, 2d.7h.34m
    ublock-abuse: 76-0, 3d.1h.9m
    ublock-badware: 4202-99, 1d.15h.29m
    ublock-filters: 32452-137, 1d.15h.28m
    ublock-privacy: 241-3, 3d.1h.8m
    ublock-quick-fixes: 413-4, 16h.46m
    ublock-unbreak: 1846-42, 1d.15h.27m
    urlhaus-1: 7364-0, 16h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1287 ms (selfie)
  maxAssetCacheWait: 526 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    manwa.fun: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`||manwa.fun/static/upload/ads/*$image,redirect-rule=1x1.gif`

@Yuki2718
