### ISSUE TITLE
pikabu.ru: detection

### ISSUE THREAD

**Issue by roman73zh** [uBlockOrigin/uAssets#14657]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pikabu.ru/story/proshchay_pikabu_na_pk_9422735`

### Category

detection

### Describe the issue

The site detects Ublock usage a few seconds after the page is loaded. When you try to block a notification, the functionality of the site breaks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/67602470/188273468-f564fb26-f517-4ece-919d-5585fa4363aa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 101528
  cosmetic: 64751
  scriptlet: 18945
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    RUS-0: 42072-9, 1d.4h.19m
    easylist: 66456-68, 1d.19h.21m
    easyprivacy: 27449-225, 1d.19h.20m
    plowe-0: 3634-782, 5d.22h.14m
    ublock-abuse: 76-1, 5d.22h.25m
    ublock-badware: 4202-100, 1d.19h.19m
    ublock-filters: 32458-141, 1d.19h.18m
    ublock-privacy: 241-3, 5d.22h.24m
    ublock-quick-fixes: 416-4, 21h.31m
    ublock-unbreak: 1845-41, 1d.19h.16m
    urlhaus-1: 7919-0, 21h.30m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 304 ms (selfie)
  maxAssetCacheWait: 215 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    pikabu.ru: 12
    adfox.ru: 1
    googletagmanager.com: 1
    mail.ru: 1
    tns-counter.ru: 1
    vk.com: 1
    yandex.ru: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
I have been trying to reproduce this problem for the second day, but so far it has failed. Complaints are being received, but the detector probably works selectively, only for certain groups of users.

**Comment by mapx-** [comment]
I was able to reproduce the issue 4-5 times (simply refreshing the page), then I enabled `RU AdList: Counters` and from that moment I cannot reproduce it anymore (even disabling `RU AdList: Counters`, clearing cache / local storage)

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/4373a1ac354c1737e7987ee526125333ef911dc0
