### ISSUE TITLE
[nsfw] linkvertise.com: ads

### ISSUE THREAD

**Issue by MrNeedMoreMhz** [uBlockOrigin/uAssets#14659]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkvertise.com/194025/arngl1/2`

### Category

ads

### Describe the issue

Unblock-able advertisement breaks site.

Can not block add or continue. Tested it on Chromium, Firefox with different blockers even with DNS based ones. This

https://user-images.githubusercontent.com/48572450/188282450-1e985135-8f22-421a-baef-092b608ac95f.png

https://user-images.githubusercontent.com/48572450/188282718-e5f6f501-18bf-46c2-a1b1-8a98d82aa87f.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 217339
  cosmetic: 228131
  scriptlet: 37654
  html: 748
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 69508-5899, 3m
    adguard-mobile: 8042-150, 3m
    adguard-annoyance: 58095-4987, 3m
    adguard-social: 18391-29, 3m
    fanboy-thirdparty_social: 69-0, 3m
    fanboy-annoyance: 80045-41823, 3m
    fanboy-cookiemonster: 40551-132, 3m
    ublock-annoyances: 4570-4, 3m
    FRA-0: 30582-362, 3m
    NLD-0: 2448-33, 3m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33197-253, 3m
    ublock-badware: 4206-0, 3m
    ublock-privacy: 263-0, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1860-1, 3m
    ublock-quick-fixes: 417-0, 3m
    easylist: 65652-1405, 3m
    adguard-spyware-url: 746-2, 3m
    easyprivacy: 27454-624, 3m
    urlhaus-1: 7674-0, 3m
    curben-phishing: 80490-5, 3m
    plowe-0: 3671-3, 3m
    LegitimateURLShortener: 1942-107, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 400 ms (selfie)
  maxAssetCacheWait: 917 ms
popupPanel: 
  blocked: 27
  no-large-media: true
  no-remote-fonts: true
  blockedDetails: 
    brightcove.com: 5
    cloudflare.com: 3
    consensu.org: 1
    googletagmanager.com: 1
    gstatic.com: 9
    media.net: 2
    ostrichesica.com: 2
    taboola.com: 1
    typekit.net: 3
```
</details>

**Comment by iSmokeMid69** [comment]
Disable Adguard & Test With UBlock Enabled Only

**Comment by stephenhawk8054** [comment]
I cannot reproduce with your configuration.

<details>

![image](https://user-images.githubusercontent.com/66517106/188295146-58f04e84-ca5f-423d-8424-64fd98efeb0d.png)

![image](https://user-images.githubusercontent.com/66517106/188295207-ff3f4145-b57e-4965-843e-a4e59102e19b.png)

</details>

Check your other blockers (DNS, hosts file, programs outside browser...)

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/xalw1q/ads_showing_up_again_on_linkvertise/ ?

**Comment by mapx-** [comment]
`http://linkvertise.com/187733/057MF/1`

maybe
```
linkvertise.com##.static-banner
linkvertise.com##.advertise
```

**Comment by MasterKia** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14761
