### ISSUE TITLE
adshort.pro [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1466]
URL(s) where the issue occurs

`http://adshort.pro/oaBx`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
