### ISSUE TITLE
[nsfw] youtube.com: ads

### ISSUE THREAD

**Issue by Araboja** [uBlockOrigin/uAssets#14666]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=yi2F18hFqQs`

### Category

ads

### Describe the issue

advertize is comming up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 83901
  cosmetic: 44441
  scriptlet: 17845
  html: 740
listset (total-discarded, last updated): 
  default: 
    user-filters: 22-0, never
    ublock-filters: 33149-39, 2d.9h.7m
    ublock-badware: 4206-0, 2d.9h.6m
    ublock-privacy: 263-0, 5d.21h.7m
    ublock-abuse: 76-0, 5d.21h.6m
    ublock-unbreak: 1860-0, 2d.9h.5m
    easylist: 66458-619, 2d.9h.4m
    easyprivacy: 27450-587, 2d.9h.3m
    urlhaus-1: 7674-0, 18h.16m
    plowe-0: 3634-3, 4d.20h.21m
    KOR-1: 3152-31, 18h.15m
    ublock-quick-fixes: 420-0, 18h.14m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2446 ms (selfie)
  maxAssetCacheWait: 959 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    youtube.com: 29
    doubleclick.net: 2
    google.co.kr: 1
    google.com: 2
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
