### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by flacito13** [uBlockOrigin/uAssets#14667]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=iiyama+g-master+red+eagle+gb3461wqsu-b1&sxsrf=ALiCzsZ2NwcCHME2kKiTEHAAuAw0dMv_PQ%3A1662296793563`

### Category

ads

### Describe the issue

ads are shown in top google search result. see img.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-04 151831](https://user-images.githubusercontent.com/55808978/188315598-fd7c1a11-5202-484e-90e6-883d0a62ed68.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 15207
  cosmetic: 13862
  scriptlet: 17822
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    DEU-0: 5913-382, 9m
    NLD-0: 2441-27, 9m
  default: 
    user-filters: 0-0, never
    ublock-abuse: 76-0, 9m
    ublock-badware: 4202-0, 9m
    ublock-filters: 32512-328, 9m
    ublock-privacy: 241-1, 9m
    ublock-quick-fixes: 423-4, 9m
    ublock-unbreak: 1847-15, 9m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1543 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Because you disabled important filter lists

>   removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null

**Comment by flacito13** [comment]
Thanks! It works with easylist

**Comment by MasterKia** [comment]
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
Please read and follow the prerequisites _**truthfully**_.

**Comment by flacito13** [comment]
> > * [x]  I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
> 
> Please read and follow the prerequisites _**truthfully**_.

MasterKia, thanks for pointing out the default filter lists. If it means anything to you, I wasn't aware I have edited the default filter list. In fact, I was even looking for an option "reset settings to default values" but couldn't find it. I know technicians have the saying RTFM, but please realize that before posting an issue on this Github I (and probably others too) have read tons of information. I may then unfortunately read over some things _**uncarefully**_, rather than untruthfully 🤔

**Comment by MasterKia** [comment]
> I was even looking for an option "reset settings to default values" but couldn't find it

https://user-images.githubusercontent.com/17685483/188317840-c8b16cbe-5727-4a9e-925c-a76f00343589.png

> I know technicians have the saying RTFM

That's mostly done by the Arch people :p

**Comment by MasterKia** [comment]
> modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true

Btw Google ads isn't gonna be affected by this change but other sites might be (you'll see big ads placeholders), you could disable this option if you like.

**Comment by flacito13** [comment]
> > modifiedUserSettings:
> > ignoreGenericCosmeticFilters: true
> 
> Btw some sites might be affected by this (you'll see big ads placeholders), you could disable this option if you like.

Aha! So that's the culprit! I thought these big placeholders were just one of the perils that come with an adblock. I appreciate your eye of detail 👍
