### ISSUE TITLE
baketax.com: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14660]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shareus.in/?i=Xh0cWV` => `https://baketax.com/banking/`

### Category

nuisance

### Describe the issue

1st Open - `https://shareus.in/?i=Xh0cWV` (They Changed Referus Site,Guess They Got To Know About What Was Done To That Site)
That Should Open The Baketax.com Site..It Has Ads,3×10=30 second Bypass Timer,remove Useless Elements

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox Mobile: 106
filterset (summary): 
  network: 89474
  cosmetic: 35235
  scriptlet: 20823
  html: 749
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4592-7, 9h.49m
    IND-0: 11385-1, 9h.49m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33293-298, 9h.49m
    ublock-badware: 4205-0, 9h.49m
    ublock-privacy: 263-1, 9h.49m
    ublock-abuse: 76-0, 9h.49m
    ublock-unbreak: 1864-0, 9h.49m
    ublock-quick-fixes: 420-0, 9h.49m
    adguard-mobile: 8042-169, 9h.49m
    easylist: 65567-21640, 9h.49m
    easyprivacy: 27453-623, 9h.49m
    urlhaus-1: 7674-0, 9h.49m
    plowe-0: 3671-3, 9h.49m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 636 ms (selfie)
  maxAssetCacheWait: 422 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    baketax.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by iSmokeMid69** [comment]
This is What I Made

baketax.com##.btn-wrp:others()
baketax.com##+js(nano-stb)
||baketax.com/img/*$image

If Something More Can Be Done By A Admin Then It Be Being Able To Go To Final Link In First/Second Page

**Comment by MasterKia** [comment]
Now redirects to `play.possiblewithelementor.com/banking`

**Comment by MasterKia** [comment]
@iSmokeMid69 The most that can be done:
```
baketax.com,play.possiblewithelementor.com#@#.btn-ad
baketax.com,play.possiblewithelementor.com##+js(nano-stb, , , 0)
baketax.com,play.possiblewithelementor.com###myClickButton:others()
```

**Comment by stephenhawk8054** [comment]
I think we can use these:

```
baketax.com,play.possiblewithelementor.com##+js(nano-stb, [native code])
baketax.com,play.possiblewithelementor.com##+js(nano-stb, myCount)
baketax.com,play.possiblewithelementor.com#@#.btn-ad
```

`##+js(nano-stb, , , 0)` causes some weird behavior at the final step for me

**Comment by MasterKia** [comment]
Does `##+js(nano-stb, myCount, , 0)` work for you?
I think it's a bit faster.

```js
window.onload = function () {
  setTimeout(function () {
    recurseMyFunction();
  }, 1000);
};
```

Should this be boosted too?

**Comment by stephenhawk8054** [comment]
Yeah, of course `##+js(nano-stb, myCount, , 0)` will be faster as default value of the last argument is `0.05` (which is 20x faster), maximum boost is 50x (equivalent to `0.02` or lower). But tbh, with the timer below 30s, I usually just use default one, as it doesn't have much differences. I just used `0.02` when some sites use very long timer (about 1 minute or more). But it's ok if you choose maximum boost.

`##+js(nano-stb, recurseMyFunction)` is good too, as it's used for some delay before the `skip ad` starts to count down.

**Comment by MasterKia** [comment]
> But it's ok if you choose maximum boost.

Maybe I noticed the difference just because I tested on a low power CPU.

**Comment by Yuki2718** [comment]
@MasterKia The reason you need nobab is `others()` hiding bait. So now we have to add "tends to trigger anti-adb" to the internal discussion.

**Comment by Yuki2718** [comment]
No, because this is an old bab. The old bab is cosmetic bait only while bab 4.2b also uses network bait. However, we generically defuse network bait too by https://github.com/uBlockOrigin/uBlock-issues/issues/1863 so nobab is rarely needed. BTW we tend to prefer ghide for old bab and `##+js(nosiif, visibility, 1000)` for 4.2b nowadays as nobab blocks eval and occasionally causes problem (e.g. cloudflare DDoS guard). OTOH nosiif can possibly be interferred by nano-sib so best to specify at least one parameter.

**Comment by Yuki2718** [comment]
Avoiding cosmetic bait is prefered to whatever scriptlet, see https://github.com/uBlockOrigin/uAssets/commit/967e718e7665bcb01316bb0b6d5ed500828069b9 `###verify_button:upward(1) ~ #primary, #secondary` is pretty enough for user experience, but we don't necessarily have to hide placeholder or likes - there was an old internal dicsussion about that too.
