### ISSUE TITLE
aniworld.to: [unknown]

### ISSUE THREAD

**Issue by ditrix5kh** [uBlockOrigin/uAssets#14668]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aniworld.to/anime/stream/that-time-i-got-reincarnated-as-a-slime/staffel-2/episode-4`

### Category

[unknown]

### Describe the issue

detictit again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 84964
  cosmetic: 46002
  scriptlet: 17749
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5913-0, 12m
    easylist: 66435-57, 3d.54m
    easyprivacy: 27449-136, 3d.53m
    plowe-0: 3634-778, 7d.16h.24m
    ublock-abuse: 76-0, 3d.56m
    ublock-badware: 4202-99, 3d.52m
    ublock-filters: 32437-120, 3d.51m
    ublock-privacy: 241-3, 3d.55m
    ublock-quick-fixes: 413-4, 7m
    ublock-unbreak: 1846-42, 3d.50m
    urlhaus-1: 7465-0, 8m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: 
  largeMediaSize: 1
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 638 ms
  maxAssetCacheWait: 224 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    ads-twitter.com: 3
    glizauvo.net: 1
    imasdk.googleapis.com: 3
    uptodatefinishconference.com: 2
    yandex.ru: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists
