### ISSUE TITLE
[nsfw] bdsmtest.org: ads

### ISSUE THREAD

**Issue by claria-tan** [uBlockOrigin/uAssets#14675]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bdsmtest.org/`

### Category

ads

### Describe the issue

Website imports banner ads even after being manually hidden using the picker tool

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 82953
  cosmetic: 42104
  scriptlet: 17772
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 42-0, never
    easylist: 66210-51, 2d.6h.30m
    easyprivacy: 27451-126, 2d.6h.29m
    plowe-0: 3671-814, 14h.22m
    ublock-abuse: 76-0, 14h.21m
    ublock-badware: 4202-101, 2d.6h.28m
    ublock-filters: 32486-109, 2d.6h.27m
    ublock-privacy: 241-1, 14h.20m
    ublock-quick-fixes: 413-4, 10h.18m
    ublock-unbreak: 1846-41, 2d.6h.26m
    urlhaus-1: 7594-0, 10h.19m
filterset (user): [array of 42 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1543 ms (selfie)
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||fmgroupdist.com/mafanikio/global/partner/$image
||fmgroupdist.com/mafanikio/global/skyscraper/$image
||fmgroupdist.com/mafanikio/global/leaderboard/*ad$image
```

@ryanbr
