### ISSUE TITLE
filmybro.top: detection

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#14679]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filmybro.top/`

### Category

detection

### Describe the issue

Show Adblocker detected 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220905-102139_Kiwi Browser](https://user-images.githubusercontent.com/42665606/188363373-b5d0645e-47cd-414d-90c5-041323d2465d.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium Mobile: 105
filterset (summary): 
  network: 84416
  cosmetic: 27077
  scriptlet: 17823
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-0, never
    adguard-mobile: 8042-28, 1d.13h.25m
    easylist: 66456-21554, 3d.1h.43m
    easyprivacy: 27454-137, 1d.16h.29m
    plowe-0: 3634-864, 3d.16h.1m
    ublock-abuse: 76-0, 4d.1h.8m
    ublock-badware: 4201-100, 1d.13h.24m
    ublock-filters: 32592-364, 1d.13h.4m
    ublock-privacy: 241-4, 4d.1h.9m
    ublock-quick-fixes: 413-4, 10h.28m
    ublock-unbreak: 1851-43, 1d.13h.22m
    urlhaus-1: 7594-0, 20h.35m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1691 ms
  maxAssetCacheWait: 503 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 2
    webpushr.com: 1
```
</details>

**Comment by MasterKia** [comment]
Could you install Firefox, go to Add-ons, install uBlock Origin and then test again?

**Comment by yashzade** [comment]
> 



> Could you install Firefox, open the Settings menu, go to Add-ons, install uBlock Origin and then test again?

I am using in kiwi browser android, with UBorigin extension.

**Comment by MasterKia** [comment]
I know, Kiwi Browser can be problematic for uBlock Origin and that's why I asked you to test Firefox Android with uBlock Origin.

**Comment by yashzade** [comment]
> I know, Kiwi Browser can be problematic for uBlock Origin and that's why I asked you to test Firefox Android with uBlock Origin.



> I know, Kiwi Browser can be problematic for uBlock Origin and that's why I asked you to test Firefox Android with uBlock Origin.

In firefox, Using VPN and ublock, it don't show Adblocker is enabled. But i have to use VPN here, without VPN I cannot open the site.
Where as in Edge browser the website is opening without VPN, but it show Adblocker is enabled.

**Comment by MasterKia** [comment]
> In firefox, Using VPN and ublock, it don't show Adblocker is enabled.

Then the problem is with the Kiwi Browser.

>  in Edge browser the website is opening without VPN, but it show Adblocker is enabled.

Edge on Android doesn't support uBlock Origin

**Comment by yashzade** [comment]
I use edge and firefox on desktop not on Android.

**Comment by MasterKia** [comment]
You reported detection in this website while using Kiwi Browser on Android, **_the solution is to use Firefox Android instead._**

For the desktop, I couldn't reproduce detection using Firefox.

**Comment by mapx-** [comment]
@yashzade see in the settings "Tracking prevention" => if it's `strict` you have to switch it to `balanced`

**Comment by krystian3w** [comment]
In kiwi possible try uBo Dev, for now no exist on list of add-ons to disable by insane reason (or moved to any different file).

https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii

> https://github.com/kiwibrowser/src/blob/c51d640a8e984ff0fb24049c53a7ed4e458775ef/extensions/renderer/extension_injection_host.cc#L56

> https://github.com/kiwibrowser/src/blob/c51d640a8e984ff0fb24049c53a7ed4e458775ef/extensions/browser/api/web_request/web_request_permissions.cc#L368

**Comment by MasterKia** [comment]
Or just use Firefox Mobile.

**Comment by krystian3w** [comment]
But this may need tutorial how move too history, bookmarks, cookies about logged session.
