### ISSUE TITLE
go.techgeek.digital: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#14678]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://go.techgeek.digital/nenvRG`

### Category

detection

### Describe the issue

This site detect uBo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/188361114-ca15f700-5c48-41c4-8970-df31606f5e51.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 86845
  cosmetic: 46818
  scriptlet: 17818
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 28-0, never
    IDN-0: 9215-3, 1d.1h.39m
    easylist: 65652-58, 1d.1h.38m
    easyprivacy: 27454-128, 1d.1h.37m
    plowe-0: 3671-814, 7h.3m
    ublock-abuse: 76-0, 7h.2m
    ublock-badware: 4202-101, 7h
    ublock-filters: 32533-141, 6h.59m
    ublock-privacy: 241-1, 7h.1m
    ublock-quick-fixes: 416-4, 17h.36m
    ublock-unbreak: 1848-43, 6h.58m
    urlhaus-1: 7594-0, 17h.35m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 532 ms (selfie)
  maxAssetCacheWait: 318 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  no-remote-fonts: true
  blockedDetails: 
    adshort.media: 4
    adshort.space: 1
    googletagmanager.com: 1
    gstatic.com: 1
```
</details>

**Comment by MasterKia** [comment]
Send the original page that redirected you to this page.
