### ISSUE TITLE
altblogger.net: detection

### ISSUE THREAD

**Issue by BlackBean69** [uBlockOrigin/uAssets#14671]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://altblogger.net/how-one-can-create-a-new-document-in-photoshop-cc`

### Category

detection

### Describe the issue

When trying to click a link it the original website redirects to this website altblogger.net telling you to disable add blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (496)](https://user-images.githubusercontent.com/112817257/188321561-22674675-5e15-4bce-b472-2f3a12ffc9d8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82845
  cosmetic: 42039
  scriptlet: 17705
  html: 735
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 33166-60, 2d.6h.41m
    ublock-badware: 4206-0, 2d.6h.44m
    ublock-privacy: 263-0, 2d.6h.49m
    ublock-abuse: 76-0, 2d.6h.48m
    ublock-unbreak: 1859-0, 2d.6h.43m
    easylist: 66214-594, 2d.6h.42m
    easyprivacy: 27451-613, 2d.6h.45m
    urlhaus-1: 7465-0, 6m
    plowe-0: 3671-3, 2d.6h.46m
    ublock-quick-fixes: 378-1, 5m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2367 ms (selfie)
  maxAssetCacheWait: 1157 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    altblogger.net: 1
    doubleclick.net: 4
    lowsteelixor.com: 1
    shrtfly.com: 1
```
</details>

**Comment by MasterKia** [comment]
> When trying to click a link it the **_original website redirects to this website_** altblogger.net 

Send the original page that redirected you to this page.
