### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by Zaptosis** [uBlockOrigin/uAssets#14676]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://work.ink/1qM/Anime%20Adventures`

### Category

detection

### Describe the issue

Anti-Ad Block in effect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82752
  cosmetic: 42674
  scriptlet: 17742
  html: 740
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-0, never
    ublock-filters: 33132-37, 3d.22h.21m
    ublock-badware: 4181-0, 3d.22h.20m
    ublock-privacy: 263-0, 2d.18h.53m
    ublock-abuse: 76-0, 2d.18h.52m
    ublock-unbreak: 1859-0, 3d.19h.26m
    easylist: 66784-592, 3d.22h.23m
    easyprivacy: 27449-613, 3d.22h.22m
    urlhaus-1: 7465-0, 5h.18m
    plowe-0: 3671-3, 2d.6h.4m
    ublock-quick-fixes: 420-0, 5h.17m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2265 ms (selfie)
  maxAssetCacheWait: 401 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    work.ink: 1
    achcdn.com: 1
    taboola.com: 1
    thisiswaldo.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by Zaptosis** [comment]
Its working perfectly now & there is no more anti-adblock! Amazing

**Comment by stephenhawk8054** [comment]
Please read the prerequisites that you have ticked on carefully

> - [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by Zaptosis** [comment]
oof sorry. I did the first 2 & then just skimmed through the rest as it was a big block of text & I don't remember changing the settings as well as not having another ad block so I thought I was good.

**Comment by Zaptosis** [comment]
Wait hold up @stephenhawk8054 I think I was right. I am once again having the same issue on the site, haven't changed any of the options with uBlock Origin & I made sure to follow your specific instructions this time.

I'm trying to navigate to this link: https://work.ink/1qQ/raceclicker & its presenting me with this pop up.

![image](https://user-images.githubusercontent.com/103388640/188758004-f9f7ee0e-c76e-4b7b-b7ea-a513a189bf0a.png)

Here is a screenshot of uBlock Origins quick view tab:

![image](https://user-images.githubusercontent.com/103388640/188758069-d2b0b2fe-6d41-421a-a82e-cecf43e42f41.png)

**Comment by Procyon-b** [comment]
Try this filter:
```
||cdn.taboola.com/libtrc/workink/loader.js$redirect-rule=noopjs,domain=work.ink
```

**Comment by MasterKia** [comment]
If it's a reoccurring theme, what about blocking all 3p scripts except google/gstatic?

**Comment by stephenhawk8054** [comment]
> I am once again having the same issue on the site

Sites can change the code very quickly to circumvent our filters. Sometimes, it worked and next day they fix it.

**Comment by krystian3w** [comment]
So this move to quick fixes instead the oldest `filters.txt`?

> except google/gstatic?

These have `:5` in priority, if no longer works then needed is debug add-on code to found guilty.

**Comment by MasterKia** [comment]
> So this move to quick fixes

Next time.

**Comment by Zaptosis** [comment]
I wonder if their monitoring GitHub for activity about their site with keyword alerts, otherwise its very unlikely they happened to fix the issue in as little as 24 hours

**Comment by stephenhawk8054** [comment]
> I wonder if their monitoring GitHub for activity about their site with keyword alerts, otherwise its very unlikely they happened to fix the issue in as little as 24 hours

It's not unlikely. There were sites used to circumvent the filters just hours after we added it.

**Comment by Zaptosis** [comment]
uBlock was working for a bit, looks like they patched it again

**Comment by mapx-** [comment]
test
`work.ink##+js(nostif, console)`

**Comment by BlockingAds** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/133157

**Comment by Zaptosis** [comment]
Looks like their up to their old shenanigans again

**Comment by CxdeLeaked** [comment]
still broken
