### ISSUE TITLE
discord.com: Spotify embeds doesn't work with uBlock

### ISSUE THREAD

**Issue by Eithoo** [uBlockOrigin/uAssets#14670]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://discord.com/`

### Category

breakage

### Describe the issue

Spotify changed its embeds a few days ago. Since then they are not working on **discord.com** when uBlock is enabled.
![image](https://user-images.githubusercontent.com/62159998/188319909-bb7075de-93a5-48f0-b75f-df2f21250931.png)
They are loaded, but the play button doesn't work. If I disable uBlock it works as it should.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 84266
  cosmetic: 50094
  scriptlet: 17953
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7846-8, 22h.48m
    POL-2: 1276-13, 1d.2h.52m
    easylist: 66783-74, 3d.18h.40m
    easyprivacy: 27449-126, 3d.18h.39m
    plowe-0: 3633-786, 11d.20h.23m
    ublock-abuse: 76-0, 11d.20h.22m
    ublock-badware: 4177-99, 3d.18h.38m
    ublock-filters: 32431-144, 3d.18h.37m
    ublock-privacy: 241-3, 11d.20h.22m
    ublock-quick-fixes: 416-5, 22h.50m
    ublock-unbreak: 1846-42, 3d.18h.36m
    urlhaus-1: 7601-0, 22h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2522 ms (selfie)
  maxAssetCacheWait: 800 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    discord.com: 16
    sentry.io: 2
    spotifycdn.com: 1
```
</details>

**Comment by mapx-** [comment]
provide a page with Spotify embeds

**Comment by Eithoo** [comment]
@mapx- https://open.spotify.com/embed/track/3T06rGO2dVEntMvym0vpQu?utm_source=discord&utm_medium=desktop
But if you go directly there it works. Only when discord shows it in iframe something is broken.

**Comment by mapx-** [comment]
I asked for a discord page with that embed

**Comment by Eithoo** [comment]
It shows automatically when someone sends a link to Spotify song in chat.

**Comment by mapx-** [comment]
founded this channel
`https://discord.com/channels/400455387855323137/733740930225537084`

the play button is working fine

**Comment by candela97** [comment]
I can reproduce this. Something to do with this filter from EasyList
`/overture.$script,domain=~overture.doremus.org|~overture.london|~overture.plus`

You can create a group chat with just yourself, and paste this link to generate an embed `https://open.spotify.com/track/3T06rGO2dVEntMvym0vpQu`

**Comment by mapx-** [comment]
right

`@@||open.spotifycdn.com/cdn/build/embed/overture.$script,domain=open.spotify.com`

**Comment by mapx-** [comment]
@ryanbr
