### ISSUE TITLE
poedb.tw: ads

### ISSUE THREAD

**Issue by laymanal** [uBlockOrigin/uAssets#14680]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poedb.tw/`

### Category

ads

### Describe the issue

Shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![图片](https://user-images.githubusercontent.com/1684121/188369499-10f66ef6-310b-4d12-a6c0-4f926362483c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 100283
  cosmetic: 51960
  scriptlet: 17777
  html: 737
listset (total-discarded, last updated): 
  default: 
    user-filters: 37-2, never
    ublock-filters: 33238-52, 1m
    ublock-badware: 4221-0, 1m
    ublock-privacy: 263-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1860-0, 1m
    easylist: 64939-628, 1m
    easyprivacy: 27487-614, 1m
    plowe-0: 3671-3, 1m
    CHN-0: 29057-119, 1m
    urlhaus-1: 7483-0, 1m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 346 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  selfieAfter: 11
supportStats: 
  allReadyAfter: 156 ms (selfie)
  maxAssetCacheWait: 122 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    poedb.tw: 2
    googletagmanager.com: 1
    nitropay.com: 2
```
</details>

**Comment by mapx-** [comment]
maybe for `CHN: AdGuard Chinese (中文)` @Yuki2718 

`poedb.tw##[target="_blank"]:has([src*="webp"])`

**Comment by Yuki2718** [comment]
@mapx-  Looks to be an international sites, you can choose many locale from the up-right button.

**Comment by laymanal** [comment]
is a third-party ad

**Comment by Yuki2718** [comment]
Hm, looks to be the case.

**Comment by Yuki2718** [comment]
@ryanbr @Khrin `poedb.tw##a[target="_blank"] > img[src$=".webp"]` is also fine.

**Comment by ryanbr** [comment]
Non english?

**Comment by Yuki2718** [comment]
@ryanbr https://github.com/uBlockOrigin/uAssets/issues/14680#issuecomment-1237325870 You can choose English too.
