### ISSUE TITLE
linkshortify.site: nuisance

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#14684]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkshortify.site//qfsFYR`

### Category

nuisance

### Describe the issue

Has to wait for 5 secs, can you speed up the countdown speed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20220905-131732_Kiwi Browser](https://user-images.githubusercontent.com/42665606/188396419-844eb567-c766-4eaf-b353-ff7a52cdd273.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium Mobile: 105
filterset (summary): 
  network: 83304
  cosmetic: 27106
  scriptlet: 17868
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 23-0, never
    adguard-mobile: 8043-28, 1h.12m
    easylist: 64951-21085, 1h.12m
    easyprivacy: 27487-137, 1h.12m
    plowe-0: 3671-902, 1h.12m
    ublock-abuse: 76-0, 1h.12m
    ublock-badware: 4216-101, 1h.12m
    ublock-filters: 32637-367, 20m
    ublock-privacy: 241-2, 1h.12m
    ublock-quick-fixes: 423-4, 1h.12m
    ublock-unbreak: 1852-43, 1h.12m
    urlhaus-1: 7483-0, 1h.12m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 881 ms
  maxAssetCacheWait: 266 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
I could only reproduce once.

Can you send the original page that redirected you to this page?

**Comment by yashzade** [comment]
> I could only reproduce once.
> 
> Can you send the original page that redirected you to this page?

You have to pass two website then you will reach linkshortify site.
https://privatemoviez.fun/secret/?data=TlNXM0xOdG02Nm5KZ01yVjg5TS84N1hwdE5HUXR1YWw1R0pqTHN5a05scklsNGQvR1M5KzF4ZzVpN0ljM3NPYzo6o3BvJJZq1B317pdSXRKClg_e__e_

**Comment by MasterKia** [comment]
> You have to pass two website then you will reach linkshortify site.

Actually I had to pass 3 websites to reach `linkshortify`, the timer on those 3 websites is fixed.
Force update your lists and test.

**Comment by yashzade** [comment]
From where I can learn this things?
