### ISSUE TITLE
watchmynameisearl.com: breakage

### ISSUE THREAD

**Issue by Ciubowski** [uBlockOrigin/uAssets#14687]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://watchmynameisearl.com/episode-watch/my-name-is-earl-1x23/`

### Category

breakage

### Describe the issue

Video player shows an error when Ublock origin is enabled, says an extension is blocking the page. No other details. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 81802
  cosmetic: 41692
  scriptlet: 17666
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64979-51, 4h.58m
    easyprivacy: 27487-126, 4h.57m
    plowe-0: 3633-777, 9d.16h.2m
    ublock-abuse: 76-0, 12d.11h.47m
    ublock-badware: 4217-101, 4h.56m
    ublock-filters: 32534-111, 4h.55m
    ublock-privacy: 241-3, 12d.11h.46m
    ublock-unbreak: 1847-41, 4h.54m
    urlhaus-1: 7510-0, 1m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 290 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    cdn4ads.com: 1
    d3g5ovfngjw9bw.cloudfront.net: 1
    e2ertt.com: 1
    maximumductpictorial.com: 1
    reasonablelandmark.com: 1
    statcounter.com: 1
    uptodatefinishconferenceroom.com: 1
```
</details>

**Comment by mapx-** [comment]
@Ciubowski 

- update all filter lists
- if you use brave => turn OFF the shields for that site
- if edge => don't use strict protection => switch to balanced

**Comment by okiehsch** [comment]
I can reproduce.

**Comment by Yuki2718** [comment]
`||uptodatefinishconferenceroom.com^` was removed from EL, is the exception still needed? https://github.com/easylist/easylist/commit/986773a82587d1cddda57ec17e7bdcd0eaaed49d

**Comment by okiehsch** [comment]
No.
