### ISSUE TITLE
economize.adrenaline.com.br: detection

### ISSUE THREAD

**Issue by SHJordan** [uBlockOrigin/uAssets#14686]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://economize.adrenaline.com.br/`

### Category

detection

### Describe the issue

As soon as the website detects ublock is working, it stops the requests with enough just to put a "Disable adblock" screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
This is with ublock on:

![image](https://user-images.githubusercontent.com/884602/188445230-dca331f7-0d5f-4108-aab9-c7fb089209dc.png)

And this is with ublock off:

![image](https://user-images.githubusercontent.com/884602/188445389-b945ae32-41f3-434b-9734-c97671668785.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 80074
  cosmetic: 95046
  scriptlet: 20731
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1945-0, 52m
    adguard-annoyance: 58082-83, 3d.47m
    adguard-spyware-url: 746-106, 1h
  default: 
    user-filters: 6-0, never
    easylist: 64984-107, 59m
    easyprivacy: 27487-225, 58m
    spa-1: 4612-77, 54m
    ublock-abuse: 76-0, 12d.16h.47m
    ublock-badware: 4217-99, 57m
    ublock-filters: 32534-521, 56m
    ublock-privacy: 241-5, 12d.16h.46m
    ublock-quick-fixes: 423-4, 53m
    ublock-unbreak: 1846-45, 55m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 22 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 291 ms (selfie)
  maxAssetCacheWait: 265 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    rackcdn.com: 22
```
</details>

**Comment by MasterKia** [comment]
Also there's breakage.

**Comment by MasterKia** [comment]
`@@||4e4356b68404a5138d2d-33393516977f9ca8dc54af2141da2a28.ssl.cf1.rackcdn.com^$domain=economize.adrenaline.com.br`

@ryanbr EasyPrivacy

**Comment by MasterKia** [comment]
@okiehsch With the exception, there is no need to defuse the anti-blocker; so should the fix be reverted if exception is added to EP/Unbreak?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f75dcfcbc19ce39e496b71b90c428a63d0207458
