### ISSUE TITLE
ohmymag.de: breakage

### ISSUE THREAD

**Issue by hagezi** [uBlockOrigin/uAssets#14692]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ohmymag.de/tipp/traumt-ihr-von-einem-eigenen-umweltbewussten-garten-so-gehts_art14269.html`

### Category

breakage

### Describe the issue

Videos not playing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b2
Chromium: 104
filterset (summary): 
  network: 84164
  cosmetic: 45487
  scriptlet: 17828
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5913-0, 1m
    easylist: 64971-56, 1m
    easyprivacy: 27487-136, 1m
    plowe-0: 3671-815, now
    ublock-abuse: 76-0, now
    ublock-badware: 4217-101, now
    ublock-filters: 32545-123, now
    ublock-privacy: 253-1, now
    ublock-quick-fixes: 420-1, now
    ublock-unbreak: 1848-42, now
    urlhaus-1: 7510-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 200 ms (selfie)
  maxAssetCacheWait: 190 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    adnami.io: 1
    ads-twitter.com: 1
    ayads.co: 1
    dailymotion.com: 1
    dm-event.net: 2
    facebook.com: 1
    facebook.net: 1
    googletagmanager.com: 2
    gscontxt.net: 1
    id5-sync.com: 1
    imasdk.googleapis.com: 2
    img-static.com: 1
    mediarithmics.com: 1
    outbrain.com: 2
    pmdstatic.net: 1
    richaudience.com: 1
    sc-static.net: 1
    stickyadstv.com: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||tra.scds.pmdstatic.net/advertising-core/$script,domain=ohmymag.de`

@ryanbr

**Comment by hagezi** [comment]
@mapx- Thanks, yes, that fixes the problem.
