### ISSUE TITLE
techjunkie.com

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#14690]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.techjunkie.com/`

### Describe the issue

Ad placeholder at the top on front page

### Screenshot(s)

https://user-images.githubusercontent.com/84513173/188482576-cafbed25-f6a4-4671-aa25-20037b6deb26.png
https://user-images.githubusercontent.com/84513173/188482669-82b3fe1e-df96-4278-91c8-eda3be79cf31.png

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 104.0.1 

### Settings

--

### Notes

Something like:

```adblock
techjunkie.com##body:style(padding-top: 0px !important)
techjunkie.com##header:style(position: sticky !important; top: 0px !important)
techjunkie.com##.slideMenu:style(top: -7px !important;)
```

Seems to be how it works when not on front page.

**Comment by stephenhawk8054** [comment]
I think we only need

```adblock
techjunkie.com##body:style(padding-top: 0px !important;)
techjunkie.com##header:style(top: 0px !important;)
```

**Comment by Nojuuu** [comment]
Navbar follows when you scroll down in other places, so I thought maybe it should also do that on the front page when there are no ads, that's why I had `position: sticky !important;`

and `##.slideMenu:style(top: -7px !important;)` tried to fix this gap:
<detail>


<details>
<summary>View image</summary>

![image](https://user-images.githubusercontent.com/84513173/188527157-11b94440-6d9c-4188-8ef8-070a2b4b5af2.png)

</details>

**Comment by stephenhawk8054** [comment]
Ah I see the `slideMenu` now. However on the front page, the nav bar doesn't follow if scrolling in desktop mode even when turning off uBO. It does follow when in mobile mode regardless of uBO turned on or off, so I don't think we need extra filter for `sticky`.

**Comment by Nojuuu** [comment]
Yeah, it doesn't really matter that much if it follows or not.

**Comment by MasterKia** [comment]
[Off-Topic] Where is the announcement that GitHub added adblock-syntax support?

**Comment by stephenhawk8054** [comment]
> [Off-Topic] Where is the GitHub announcement that they added adblock-syntax support?

I think these:

https://github.com/github/linguist/releases/tag/v7.23.0

https://github.com/github/linguist/pull/5968
