### ISSUE TITLE
20minutos.es: breakage (some videos don't work)

### ISSUE THREAD

**Issue by jmgomezpoveda** [uBlockOrigin/uAssets#14691]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.20minutos.es/noticia/5050055/0/multa-de-500-euros-para-el-ciclista-temerario-intentaba-adelantar-a-un-coche-en-una-curva-sin-visibilidad-y-acaba-atropellado/`

### Category

breakage

### Describe the issue

The video player doesn't show at all when uBlock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 82452
  cosmetic: 41902
  scriptlet: 17778
  html: 740
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33191-37, 1d.23h.52m
    ublock-badware: 4206-0, 1d.23h.51m
    ublock-privacy: 263-0, 7d.9h.50m
    ublock-abuse: 76-0, 9h
    ublock-unbreak: 1859-0, 1d.23h.49m
    easylist: 65652-598, 1d.23h.50m
    easyprivacy: 27454-578, 1d.23h.48m
    urlhaus-1: 7483-0, 8h.58m
    plowe-0: 3634-3, 7d.9h.49m
    ublock-quick-fixes: 427-0, 8h.57m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3151 ms (selfie)
  maxAssetCacheWait: 1985 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    20m.es: 3
    amazon-adsystem.com: 3
    chartbeat.com: 2
    criteo.net: 1
    doubleclick.net: 1
    google-analytics.com: 2
    google.com: 1
    googletagmanager.com: 1
    jwpcdn.com: 2
    jwpltx.com: 2
    pghub.io: 1
    scorecardresearch.com: 1
    socy.es: 1
    taboola.com: 1
    teads.tv: 1
```
</details>

**Comment by jmgomezpoveda** [comment]
This could be related to the closed item https://github.com/uBlockOrigin/uAssets/issues/13696

**Comment by okiehsch** [comment]
Enable the regional spanish lists and try again.

**Comment by jmgomezpoveda** [comment]
I can see the videos if I enable the list "spa: EasyList Spanish"

**Comment by okiehsch** [comment]
That list is enabled by default for all users with a spanish locale.
