### ISSUE TITLE
test-ipv6.com: breakage

### ISSUE THREAD

**Issue by washuu** [uBlockOrigin/uAssets#14696]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://test-ipv6.com/`

### Category

breakage

### Describe the issue

A few URLs are being blocked, like `https://ipv6.fra.test-ipv6.com/ip/?callback=?&testdomain=test-ipv6.com&testname=test_aaaa`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 81841
  cosmetic: 41826
  scriptlet: 17801
  html: 740
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 33231-38, 1d.3h.26m
    ublock-badware: 4206-0, 1d.15h.41m
    ublock-privacy: 263-0, 1d.15h.46m
    ublock-abuse: 76-0, 1d.15h.45m
    ublock-unbreak: 1860-0, 1d.11h.37m
    ublock-quick-fixes: 417-0, 13h.45m
    easylist: 64950-580, 1d.15h.42m
    easyprivacy: 27454-631, 1d.15h.40m
    urlhaus-1: 7483-0, 13h.44m
    plowe-0: 3671-3, 1d.15h.43m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 287 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any `callback` connections being blocked.

<details>

![image](https://user-images.githubusercontent.com/66517106/188525081-9032de4d-f550-48c7-8400-18af7b0b8a95.png)

</details>

Can you open [The logger](https://github.com/gorhill/uBlock/wiki/The-logger) to see which filter in what filter list is blocking it?
