### ISSUE TITLE
doordash.com: breakage

### ISSUE THREAD

**Issue by GabuEx** [uBlockOrigin/uAssets#14694]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.doordash.com/consumer/checkout/?order_cart_id=9e05ba49-ee6e-4160-99a4-a3bb66223643`

### Category

breakage

### Describe the issue

On DoorDash's website, uBlockOrigin is deleting the entire section of the website where you can specify a tip for the dasher.  The website works fine if I resize the window to mobile dimensions, but otherwise I need to disable uBlockOrigin to be able to add a tip and place my order with that tip.

### Screenshot(s)

With uBlockOrigin enabled:

![image](https://user-images.githubusercontent.com/7245618/188511892-eea39745-688c-4a36-9306-6320b31c7643.png)

Without uBlockOrigin enabled:

![image](https://user-images.githubusercontent.com/7245618/188511910-b8095909-29d9-4937-ab98-e76ebbd3d1ef.png)

With uBlockOrigin enabled and the website sized down to mobile dimensions:

![image](https://user-images.githubusercontent.com/7245618/188512011-019ac610-63e4-4b43-86ad-0f14409fcaef.png)

(personal information redacted)

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 82896
  cosmetic: 42060
  scriptlet: 17773
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66240-51, 3d.56m
    easyprivacy: 27451-126, 3d.55m
    plowe-0: 3671-813, 2d.8h.49m
    ublock-abuse: 76-0, 3d.12h.58m
    ublock-badware: 4202-101, 3d.54m
    ublock-filters: 32471-109, 3d.53m
    ublock-privacy: 241-1, 3d.12h.57m
    ublock-quick-fixes: 420-1, 42m
    ublock-unbreak: 1846-41, 3d.52m
    urlhaus-1: 7510-0, 43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 420 ms (selfie)
  maxAssetCacheWait: 147 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    google.com: 14
```
</details>

**Comment by mapx-** [comment]
@GabuEx 

if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced 

still in trouble:

- open the logger
- repeat the steps to get the issue
- go back into the logger and then copy and paste here all blocked requests

**Comment by aldobarr** [comment]
@mapx- With shields down on Brave:
![image](https://user-images.githubusercontent.com/1071197/188702741-533d2167-1237-4ace-aced-6fd223fa5f53.png)

**Comment by mapx-** [comment]
I mean the requests you see in uBO's logger:
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by aldobarr** [comment]
Sorry this is legitimately the first time I've ever had any issue at all with uBlock Origin haha

<details><summary>Logger output</summary>

```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
||google.com/log?
--
pay.google.com
3,1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0
```
```
+3
/quotaservice.recordevent?
--
www.doordash.com
3
script
https://maps.googleapis.com/maps/api/js/QuotaService.RecordEvent?1shttps%3A%2F%2Fwww.doordash.com%2Fconsumer%2Fcheckout%2F&2sgme-doordashinc1&7sqhp97a&9sconsumer_web&10e1&callback=_xdc_._35zza&client=gme-doordashinc1&channel=consumer_web&token=28055
```
```
+3
google-analytics.com/analytics.js
<<
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5
--
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
||google-analytics.com^
--
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
google-analytics.com/analytics.js
<<
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5
--
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
||google-analytics.com^
--
pay.google.com
3,3
script
https://www.google-analytics.com/analytics.js
```
```
+3
/counter.cgi?
--
www.doordash.com
3
image
https://b.stats.paypal.com/counter.cgi?i=127.0.0.1&p=255fdf2225d3b307338486052047ddc0&t=1662486774.212&a=14
```
```
+3
||client-analytics.braintreegateway.com^
--
www.doordash.com
3
xhr
https://client-analytics.braintreegateway.com/wzp38ym33349bbsv
```
```
+3
/collect/kasupport
--
www.doordash.com
3
xhr
https://ssl.kaptcha.com/collect/kasupport
```
```
+3
||client-analytics.braintreegateway.com^
--
www.doordash.com
3
xhr
https://client-analytics.braintreegateway.com/wzp38ym33349bbsv
```
```
+3
||client-analytics.braintreegateway.com^
--
www.doordash.com
3
xhr
https://client-analytics.braintreegateway.com/wzp38ym33349bbsv
```
```
+3
||client-analytics.braintreegateway.com^
--
www.doordash.com
3
xhr
https://client-analytics.braintreegateway.com/wzp38ym33349bbsv
```
```
+3
##div[size="12"]:has(> div:has(span:has-text(Ad)))
www.doordash.com
dom
https://www.doordash.com/consumer/checkout/?order_cart_id=d0419190-54a4-4012-8f66-8b21bfbaa558
```
```
+2
||sift.com^$3p
--
www.doordash.com
3
script
https://cdn.sift.com/s.js
```
```
+1
||googleapis.com^*/gen_204?
--
www.doordash.com
3
xhr
https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true
```
```
+1
||btncdn.com^$3p
--
www.doordash.com
3
script
https://web.btncdn.com/v1/button.js
```
```
+1
||sentry.io^$3p
--
www.doordash.com
3
xhr
https://o17585.ingest.sentry.io/api/6196846/envelope/?sentry_key=f55609756bfb481c8ad0a180c8248883&sentry_version=7
```
```
+0
||cdn.segment.com^
--
www.doordash.com
3
script
https://cdn.segment.com/analytics.js/v1/L3UWqZFYa0jF2PtgpEsKod2WtZet4Zvr/analytics.min.js
```
```
+0
||cloudflareinsights.com^
--
www.doordash.com
3
script
https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194
```
```
+0
https://www.doordash.com/consumer/checkout/?order_cart_id=d0419190-54a4-4012-8f66-8b21bfbaa558
```
</details>

**Comment by mapx-** [comment]
see if helps:

`doordash.com#@#div[size="12"]:has(> div:has(span:has-text(Ad)))`

**Comment by aldobarr** [comment]
Didn't help, in fact inspecting the dom I see the content is there just hidden. It doesn't look like ublock origin is the one blocking it. Seems like they're detecting ublock origin and just screwing with you if you use it. On page load you can actually see the right section for a split second before it goes away.

**Comment by mapx-** [comment]
test this filter

`@@||doordash.com^$ehide`

**Comment by aldobarr** [comment]
That worked. Necessary to keep that filter on from now on?

**Comment by mapx-** [comment]
disable the 2 filters, add only 
`doordash.com#@#[data-testid="card.store"] > div:has(div[data-anchor-id="SponsoredBadge"])`

and test again

if still broken, add the first filter too and test again

**Comment by aldobarr** [comment]
That doesn't work with or without the first filter.

**Comment by mapx-** [comment]
test only

`@@||doordash.com^$ghide`

**Comment by aldobarr** [comment]
> test only
> 
> `@@||doordash.com^$ghide`

That's actually what I had done initially. That one works with or without the first one.

**Comment by mapx-** [comment]
No, previously you tested EHIDE, now GHIDE

**Comment by aldobarr** [comment]
> @@||doordash.com^$ghide

Yeah mb just saw, ghide does not work.

**Comment by mapx-** [comment]
test these

```
doordash.com#@#div[size="12"]:has(> div:has(span:has-text(Ad)))
doordash.com#@#[data-testid="card.store"] > div:has(div[data-anchor-id="SponsoredBadge"])
@@||doordash.com^$ghide
```

**Comment by aldobarr** [comment]
Doesn't work

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
@aldobarr did you disable any other blocking extension ? 

What is this icon ?
![image](https://user-images.githubusercontent.com/10303732/188735789-39da59a9-eba8-4a23-8546-e5441151c17b.png)

**Comment by aldobarr** [comment]
That's bitwarden. I don't have any other blocking extensions:

![image](https://user-images.githubusercontent.com/1071197/188739404-8b2bada2-d429-4829-82bb-28e63b91f494.png)

**Comment by MasterKia** [comment]
[Off-Topic] @aldobarr, Netflix party is a malicious extension, you should remove it.

https://www.mcafee.com/blogs/other-blogs/mcafee-labs/malicious-cookie-stuffing-chrome-extensions-with-1-4-million-users/

**Comment by aldobarr** [comment]
>The operating system has a built-in screenshot functionality already.

The point of it is to capture a screenshot of a full webpage regardless of how long it is in one go, without having to manually scroll and take multiple screenshots.

**Comment by MasterKia** [comment]
I see.

Remove the filters mapx- gave you, then force update your filter lists (Purge all cache => Update now) and see if it's fixed.
