### ISSUE TITLE
altblogger.net: detection

### ISSUE THREAD

**Issue by KorehDoreh** [uBlockOrigin/uAssets#14697]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://altblogger.net/5-best-tools-to-check-keyword-rankings-on-different-search-engines`

### Category

detection

### Describe the issue

About a week about this website started to block Ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/72111795/188526701-5f6c9c64-5fdd-4c0c-8f43-43d6bc7a379d.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104
filterset (summary): 
  network: 100852
  cosmetic: 82011
  scriptlet: 30460
  html: 741
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 69606-5489, 1m
    adguard-mobile: 8045-149, 1m
  default: 
    user-filters: 3-0, never
    ublock-filters: 33235-128, 10h.28m
    ublock-badware: 4221-0, 10h.27m
    ublock-privacy: 263-0, 3d.22h.38m
    ublock-abuse: 76-0, 3d.22h.37m
    ublock-unbreak: 1860-0, 10h.26m
    easylist: 64958-643, 10h.25m
    easyprivacy: 27487-602, 10h.24m
    urlhaus-1: 7465-0, 22h.30m
    plowe-0: 3634-3, 4d.10h.46m
    ublock-quick-fixes: 424-0, 2h.23m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 170 ms (selfie)
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    altblogger.net: 1
    doubleclick.net: 4
    lowsteelixor.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Duplicate: https://github.com/uBlockOrigin/uAssets/issues/14671

Please give original URL that redirects to the above site in that thread.
