### ISSUE TITLE
Filter to block bandcamp from blocking streaming via site

### ISSUE THREAD

**Issue by CrazyPython** [uBlockOrigin/uAssets#147]
If you play a song/album on bandcamp often enough, a message will appear requesting donations. If you continue playing, it will appear more often and eventually stop you from playing anything at all. Clearing cookies eliminates the problem, but a filter to block this couldn't be hard.

**Comment by gorhill** [comment]
> but a filter to block this couldn't be hard

I have no clue what is "bandcamp". Best is that you find that "couldn't be hard" filter.

**Comment by CrazyPython** [comment]
@gorhill *.bandcamp.com e.g. http://thomasveith.bandcamp.com/album/time-2-versions-music-for-the-kurzgesagt-youtube-channel

**Comment by lewisje** [comment]
You sound like you're talking about a filter to keep bandcamp.com sites from setting cookies; I'm not sure you can do that with uBlock Origin filters. It's even less likely that you can delete existing cookies with uBlock Origin.

**Comment by CrazyPython** [comment]
@lewisje uBlock is a content blocker... if this functionality doesn't exist, @gorhill should add it. uBlock already blocks badware and other annoying things.

**Comment by lewisje** [comment]
Cookies do not require their own network requests, and they are not elements that can be hidden with CSS; this means it's not as straightforward as you may think for uBlock Origin to keep websites from setting cookies. Have you considered one of the extensions that *does* help you manage cookie permissions, like EditThisCookie for Chrome?

uBO was never intended to be all things to all people, and neither was its predecessor, uMatrix (which *does* have [functionality to keep cookies from being sent](https://github.com/gorhill/uMatrix/wiki/Cookies) from the browser).

**Comment by CrazyPython** [comment]
@lewisje obviously, it can't be blocked with CSS. But uBlock should take a bold new step and block all sorts of annoying things.

**Comment by lewisje** [comment]
Have you considered whether uMatrix fits your needs? It can't keep cookies from being set, or delete existing cookies, but it *can* keep cookies from being *sent* and that might be what you want, if you'd rather not use a more narrowly focused extension like EditThisCookie.

(If you're on Firefox, Policeman is similar to uMatrix, and I believe there are narrower extensions for blocking cookies specifically.)

**Comment by gorhill** [comment]
> or delete existing cookies

It can delete pre-existing cookies. This will happens as a "janitor" task once in a while in the background, and according to matrix rules. After a while running uMatrix, the existing cookies in the browser will reflect the matrix ruleset.

**Comment by CrazyPython** [comment]
@gorhill hm, but does uMatrix have most of the features of uBlock?

**Comment by gorhill** [comment]
They are different extensions, they are not specifically made to run with each others, they have no knowledge of each others. Probably best you use a narrower cookie management extension.
