### ISSUE TITLE
Whitelist pstmrk.it

### ISSUE THREAD

**Issue by jefm-semco** [uBlockOrigin/uAssets#14701]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

pstmrk.it

### Describe the issue

The company is using a survey coming from WOBA and it is redirecting pstmrk.it . And we have a large number of employees who are not good in using computers. We are requesting to whitelist pstmrk.it. 

### Screenshot(s)

<img width="796" alt="pstmrk" src="https://user-images.githubusercontent.com/100128929/188623519-bb0c36f7-a33c-43bf-b51a-698c2e1b5cc6.png">

### uBlock Origin version

1.44.0

### Browser name and version

Microsoft Edge Version 104.0.1293.70

### Settings

None

**Comment by MasterKia** [comment]
@pgl It is email click tracker (redirect link), right?

**Comment by MasterKia** [comment]
> we have a large number of employees who are not good in using computers.

Your users can't click the "**_Permanently_**" button to disable the block? [and expose themselves to tracking]

https://user-images.githubusercontent.com/17685483/188627674-779d50d7-72b6-4822-a2a0-99381da24f4e.jpg

Also in https://github.com/uBlockOrigin/uAssets/issues/14258:
> Website is being blocked by UBlock. And we have numbers of users accessing the webiste `https://exponea.com`

I wonder why your users always access ad servers and tracker links.

**Comment by MasterKia** [comment]
@pgl Is this an email click tracker (redirect link)?

**Comment by MasterKia** [comment]
`Postmark uses the pstmrk.it domain to deliver a variety of analytics to the users of our email service.`

**Comment by MasterKia** [comment]
> Postmark uses the pstmrk.it domain **_to deliver a variety of analytics_** to the users of our email service.

**Comment by pgl** [comment]
Thanks @MasterKia, you have once again saved me typing out the standard explanation. :)

**Comment by pgl** [comment]
> This may have rare chance to convert in block only 3p.

Sure, the rule can be changed to that, but people usually come across this when they click a link in a newsletter (as that's what Postmark does, send out email marketing / newsletters). So I don't think it'd have much effect I'm afraid, sorry.

**Comment by krystian3w** [comment]
Maybe this should be moved to policies: https://github.com/gorhill/uBlock/pull/3865

Then only rotten Coproration will be more tracked.

**Comment by MasterKia** [comment]
Declined by okiehsch:
> this is about link tracking, which we will obviously decline.

**Comment by MasterKia** [comment]
Declined by okiehsch:
> this is about link tracking, which we will obviously decline.

**Comment by jefm-semco** [comment]
@MasterKia 
Appreciated the feedback.

**Comment by MasterKia** [comment]
@jefm-semco If you have a sysadmin that can deply uBlock Origin to employees' machines; then you can easily whitelist every website you like:
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin:-configuration
