### ISSUE TITLE
duellinksmeta.com: breakage

### ISSUE THREAD

**Issue by WolfgangDS** [uBlockOrigin/uAssets#14708]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.duellinksmeta.com/`

### Category

breakage

### Describe the issue

Search function and anything built on the modal framework (or whatever it's called) will not work.  While this DOES disable the "Please allow ads" message, it also decreases the overall functionality of the site.  Card information pop-ups are also disabled because of this.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![DLM Broke](https://user-images.githubusercontent.com/4020732/188723180-1950cf40-3d12-49a5-9ec2-4a06d54f98a6.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 234389
  cosmetic: 218315
  scriptlet: 38206
  html: 750
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-5, 1h.10m
    https://winhelp2002.mvps.org/hosts.txt: 8730-343, 1h.10m
    adguard-generic: 69653-5611, 1h.11m
    adguard-mobile: 8045-210, 1h.11m
    adguard-spyware: 27135-1501, 1h.11m
    adguard-spyware-url: 748-2, 1h.11m
    block-lan: 43-0, 1h.11m
    curben-phishing: 79871-17, 1h.11m
    curben-pup: 190-0, 1h.11m
    adguard-annoyance: 58598-5059, 1h.11m
    adguard-social: 18423-1061, 1h.11m
    fanboy-thirdparty_social: 68-0, 1h.11m
    fanboy-annoyance: 80160-64146, 1h.10m
    fanboy-cookiemonster: 40585-133, 1h.10m
    fanboy-social: 23356-28, 1h.10m
    ublock-annoyances: 4577-4, 1h.10m
    dpollock-0: 11387-1655, 1h.10m
  default: 
    user-filters: 17-0, never
    ublock-filters: 33264-74, 1h.11m
    ublock-badware: 4221-0, 1h.11m
    ublock-privacy: 273-0, 1h.11m
    ublock-abuse: 76-0, 1h.11m
    ublock-unbreak: 1861-1, 1h.11m
    easylist: 64859-1039, 1h.11m
    easyprivacy: 27489-9748, 1h.11m
    urlhaus-1: 7528-0, 1h.11m
    plowe-0: 3671-3, 1h.10m
    ublock-quick-fixes: 425-0, 1h.10m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 12 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5507 ms (selfie)
  maxAssetCacheWait: 3650 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    btloader.com: 1
    googletagmanager.com: 1
    intergient.com: 2
```
</details>

**Comment by MasterKia** [comment]
> - [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

>   added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-5, 1h.10m
    https://winhelp2002.mvps.org/hosts.txt: 8730-343, 1h.10m
    adguard-generic: 69653-5611, 1h.11m
    adguard-mobile: 8045-210, 1h.11m
    adguard-spyware: 27135-1501, 1h.11m
    adguard-spyware-url: 748-2, 1h.11m
    block-lan: 43-0, 1h.11m
    curben-phishing: 79871-17, 1h.11m
    curben-pup: 190-0, 1h.11m
    adguard-annoyance: 58598-5059, 1h.11m
    adguard-social: 18423-1061, 1h.11m
    fanboy-thirdparty_social: 68-0, 1h.11m
    fanboy-annoyance: 80160-64146, 1h.10m
    fanboy-cookiemonster: 40585-133, 1h.10m
    fanboy-social: 23356-28, 1h.10m
    ublock-annoyances: 4577-4, 1h.10m
    dpollock-0: 11387-1655, 1h.10m

Please test using **_only the default lists_**.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14549
