### ISSUE TITLE
Divi themed sites

### ISSUE THREAD

**Issue by LCGdsgn** [uBlockOrigin/uAssets#14707]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I'm having issues with Divi sites I create and users being unable to see modules.

Sometimes is a contact form module, sometimes a code module. SSL certs are valid and the pages show no errors.

Disabling UBO results in the missing items showing, is there something with UBO that needs adjustment? Is it misidentifying an issue?

Example page:
`https://www.onepercentclub.co.uk/`

Browser, latest FF although some Chrome users reporting issues too.

### A specific URL where the issue occurs

`https://www.onepercentclub.co.uk/`

### Steps to Reproduce

Click on link

Is there a login form on the right?

### Expected behavior

There should be a form on the right

### Actual behavior

There is no form on the right

### uBlock Origin version

latest

### Browser name and version

FF latest also chrome

### Operating System and version

win 7, 10, 11

**Comment by mapx-** [comment]
- provide the list of your enabled filter lists
- however it seems you enabled `Fanboy’s Annoyance`  which indeed hides that section
- provide all those broken sites / pages

**Comment by mapx-** [comment]
@ryanbr FA issue

**Comment by mapx-** [comment]
@LCGdsgn test yourself adding :
`onepercentclub.co.uk#@#.et_pb_newsletter`

and see if the issue is gone

**Comment by LCGdsgn** [comment]
Thanks @mapx- the link didn't change anything for me but disabling the FA list does mean it shows.

Thanks for the investigation.

**Comment by mapx-** [comment]
What link ?

It's an exception you have to add to "my filters"

`onepercentclub.co.uk#@#.et_pb_newsletter`

provide the other sites or ... modify your pages using other class name replacing `.et_pb_newsletter`

**Comment by krystian3w** [comment]
Worse if all webmasters now must rebuild divi template.
