### ISSUE TITLE
playplus.com: breakage

### ISSUE THREAD

**Issue by Fernandesss** [uBlockOrigin/uAssets#14704]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.playplus.com/live/liveEvent/180`

### Category

breakage

### Describe the issue

video player does not work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 83857
  cosmetic: 44843
  scriptlet: 18064
  html: 0
listset (total-discarded, last updated): 
  added: 
    spa-1: 4612-78, 1d.16h.40m
  default: 
    user-filters: 29-0, never
    easylist: 65652-52, 2d.17h.9m
    easyprivacy: 27475-126, 1d.16h.38m
    plowe-0: 3671-814, 21h.12m
    ublock-abuse: 76-0, 1d.12h.37m
    ublock-badware: 4202-101, 1d.16h.39m
    ublock-filters: 32545-145, 11h.46m
    ublock-privacy: 241-1, 1d.12h.36m
    ublock-quick-fixes: 420-1, 21h.10m
    ublock-unbreak: 1848-42, 1d.12h.35m
    urlhaus-1: 7510-0, 21h.11m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 593 ms (selfie)
  maxAssetCacheWait: 454 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
```
</details>

**Comment by mapx-** [comment]
needing subscription, so:

if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced

still in trouble:

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
-
