### ISSUE TITLE
multiplayer.it: detection

### ISSUE THREAD

**Issue by JakSpoon** [uBlockOrigin/uAssets#14703]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://multiplayer.it/`

### Category

detection

### Describe the issue

At the precise moment I open the web page, I am warned that I am using an adblock.
![adblock_detection_MultiplayerIT](https://user-images.githubusercontent.com/63912221/188656419-c46f915a-8034-405d-93fb-f38720b1b2a5.jpeg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 168387
  cosmetic: 49368
  scriptlet: 17783
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    curben-phishing: 80051-0, 22h.48m
    curben-pup: 190-1, 21h.28m
  default: 
    ITA-0: 13161-0, 22h.46m
    easylist: 65652-58, 2d.23h.14m
    easyprivacy: 27454-128, 2d.23h.14m
    plowe-0: 3633-780, 10d.17h.54m
    ublock-abuse: 76-0, 10d.17h.55m
    ublock-badware: 4202-102, 2d.23h.14m
    ublock-filters: 32490-117, 2d.23h.14m
    ublock-privacy: 241-3, 10d.18h.8m
    ublock-quick-fixes: 420-1, 22h.45m
    ublock-unbreak: 1847-41, 2d.23h.14m
    urlhaus-1: 7510-1, 22h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 28 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 556 ms (selfie)
  maxAssetCacheWait: 363 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    ams3.cdn.digitaloceanspaces.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    iubenda.com: 1
    scorecardresearch.com: 1
    tapad.com: 1
    tradelab.fr: 1
```
</details>

**Comment by Samidaro** [comment]
can this be checked again please

**Comment by mapx-** [comment]
> can this be checked again please

Do I need an account to reproduce the issue ?

**Comment by mapx-** [comment]
@Samidaro @JakSpoon 

**You should have said that an account is required**

Test this filter for breakage:

`multiplayer.it##+js(aeld, , adb)`

**Comment by Samidaro** [comment]
you don't need an account. Same happens when either logged in or not.
