### ISSUE TITLE
kurs.com.ua: breakage

### ISSUE THREAD

**Issue by SimaBublik** [uBlockOrigin/uAssets#14717]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kurs.com.ua/`

### Category

breakage

### Describe the issue

hardly see anything

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 100276
  cosmetic: 64186
  scriptlet: 19017
  html: 746
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33261-35, 23h.56m
    ublock-badware: 4221-0, 23h.55m
    ublock-privacy: 273-0, 23h.54m
    ublock-abuse: 76-0, 23h.53m
    ublock-unbreak: 1862-0, 23h.52m
    ublock-quick-fixes: 425-0, 23h.51m
    easylist: 64839-598, 23h.50m
    easyprivacy: 27489-614, 23h.49m
    urlhaus-1: 7528-0, 23h.48m
    plowe-0: 3671-3, 23h.47m
    RUS-0: 42167-164, 1d.1m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 423 ms (selfie)
  maxAssetCacheWait: 308 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adtcdn.com: 2
    doubleclick.net: 1
    facebook.net: 1
    googlesyndication.com: 8
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@dimisa-RUAdList
`kurs.com.ua##+js(acis, document.documentElement.clientWidth)`
causes the breakage.

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/eb19a8c7aa23b3fd28a9a582f985f8acbf0efa5d

**Comment by SimaBublik** [comment]
Site Курс валют на сьогодні. Конвертор валют. Курс всіх банків. НБУ. Міжбанк not work with Ublock. Screen below.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Курс валют на сьогодні. Конвертор валют. Курс всіх банків. НБУ. Міжбанк

Сайт №1 про курси валют в Україні і світі. Курс грошей на сьогодні. Курси валют 74 банків України. Курси валют Н...
 |

 |

 |







    среда, 7 сентября 2022 г., 19:04:39 GMT+3, MasterKia ***@***.***> написал(-а):  
 
 


Closed #14717 as completed.

**Comment by MasterKia** [comment]
@SimaBublik Force update your filter lists and test again.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches

**Comment by SimaBublik** [comment]
All OK!! Thanks for your support!!

    четверг, 8 сентября 2022 г., 10:11:42 GMT+3, MasterKia ***@***.***> написал(-а):  
 
 


@SimaBublik Force update your filter lists and test again.
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
