### ISSUE TITLE
officepoolstop.com - detection

### ISSUE THREAD

**Issue by BrayFlex** [uBlockOrigin/uAssets#14716]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://officepoolstop.com/Players-Only/`

### Describe the issue

*May require an account to get to this page* => Use `guest` for username and password
After you login you are redirected to this page which has a script that detects adblocker and redirects you to this other page.
`https://officepoolstop.com/Players-Only/` any of the domains off this will redirect to `https://officepoolstop.com/Players-Only/AdBlockInfo.aspx`

### uBlock Origin version

uBlock Origin 1.44.0

### Browser name and version

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### Settings

n/a

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16391
