### ISSUE TITLE
localhost: [unknown]

### ISSUE THREAD

**Issue by bob123124** [uBlockOrigin/uAssets#14714]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://localhost:6543/block_screen.html?id=ebbddaa3-c816-45ee-a344-f740c70df1e2`

### Category

[unknown]

### Describe the issue

can not get into google griavity 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 0
  cosmetic: 0
  scriptlet: 0
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 35920 ms (selfie)
  maxAssetCacheWait: 683 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
> can not get into google griavity

There you go:
https://mrdoob.com/projects/chromeexperiments/google-gravity/2013.html
