### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Thebaba1** [uBlockOrigin/uAssets#14718]
### Prerequisites

- [ ] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [ ] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [ ] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=sQr1G4oVmDQ&list=RDQHwNFf1tzUk&index=27`

### Category

ads

### Describe the issue

It started today playing adds on youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 84321
  cosmetic: 45391
  scriptlet: 17838
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5925-0, 3h.53m
    easylist: 64839-56, 1d.4h.44m
    easyprivacy: 27489-136, 1d.4h.43m
    plowe-0: 3671-815, 3d.16h.46m
    ublock-abuse: 76-0, 3d.16h.49m
    ublock-badware: 4217-101, 1d.4h.42m
    ublock-filters: 32558-123, 1d.4h.41m
    ublock-privacy: 241-1, 3d.16h.48m
    ublock-quick-fixes: 430-2, 3h.52m
    ublock-unbreak: 1849-42, 1d.4h.40m
    urlhaus-1: 7688-0, 3h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 916 ms (selfie)
  maxAssetCacheWait: 446 ms
popupPanel: 
  blocked: 200
  blockedDetails: 
    youtube.com: 186
    doubleclick.net: 10
    googlesyndication.com: 4
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
