### ISSUE TITLE
[nsfw] altblogger.net: detection

### ISSUE THREAD

**Issue by Draminha** [uBlockOrigin/uAssets#14711]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://altblogger.net/get-backlinks-for-a-new-site-without-money`

Original Link (NSFW):   `https://stfly.me/nzmZ`

### Category

detection

### Describe the issue

I Purged all caches and update, still get detection on this site...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 220472
  cosmetic: 218194
  scriptlet: 38210
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 58620-83, 1m
    adguard-generic: 69656-703, 1m
    adguard-mobile: 8046-45, 1m
    adguard-social: 18424-879, 1m
    adguard-spyware: 27136-1132, 1m
    adguard-spyware-url: 751-1, 1m
    block-lan: 43-0, 1m
    curben-phishing: 79871-0, 1m
    curben-pup: 190-1, 1m
    dpollock-0: 11387-250, now
    fanboy-annoyance: 80161-4736, now
    fanboy-cookiemonster: 40584-40584, now
    fanboy-social: 23356-23356, now
    fanboy-thirdparty_social: 68-21, now
    ublock-annoyances: 4569-241, now
  default: 
    user-filters: 0-0, never
    easylist: 64865-1488, now
    easyprivacy: 27490-9404, now
    plowe-0: 3671-1344, now
    ublock-abuse: 76-0, now
    ublock-badware: 4222-333, now
    ublock-filters: 32562-3955, now
    ublock-privacy: 251-43, now
    ublock-quick-fixes: 421-14, now
    ublock-unbreak: 1850-105, now
    urlhaus-1: 7528-1, now
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 945 ms (selfie)
  maxAssetCacheWait: 736 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    altblogger.net: 1
    doubleclick.net: 1
    lowsteelixor.com: 1
    shrtfly.com: 1
```
</details>

**Comment by MasterKia** [comment]
I can't reproduce detection and I could reach the destination link (`streamtape.com`).

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

> added: 
    adguard-annoyance: 58620-83, 1m
    adguard-generic: 69656-703, 1m
    adguard-mobile: 8046-45, 1m
    adguard-social: 18424-879, 1m
    adguard-spyware: 27136-1132, 1m
    adguard-spyware-url: 751-1, 1m
    block-lan: 43-0, 1m
    curben-phishing: 79871-0, 1m
    curben-pup: 190-1, 1m
    dpollock-0: 11387-250, now
    fanboy-annoyance: 80161-4736, now
    fanboy-cookiemonster: 40584-40584, now
    fanboy-social: 23356-23356, now
    fanboy-thirdparty_social: 68-21, now
    ublock-annoyances: 4569-241, now

Please test using **_only the default lists_**.

**Comment by Draminha** [comment]
> I can't reproduce detection and I could reach the destination link (`streamtape.com`).
> 
> > * [x]  I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
> 
> > added:
> > adguard-annoyance: 58620-83, 1m
> > adguard-generic: 69656-703, 1m
> > adguard-mobile: 8046-45, 1m
> > adguard-social: 18424-879, 1m
> > adguard-spyware: 27136-1132, 1m
> > adguard-spyware-url: 751-1, 1m
> > block-lan: 43-0, 1m
> > curben-phishing: 79871-0, 1m
> > curben-pup: 190-1, 1m
> > dpollock-0: 11387-250, now
> > fanboy-annoyance: 80161-4736, now
> > fanboy-cookiemonster: 40584-40584, now
> > fanboy-social: 23356-23356, now
> > fanboy-thirdparty_social: 68-21, now
> > ublock-annoyances: 4569-241, now
> 
> Please test using **_only the default lists_**.

Settings>Reset to default settings>filter list>update. And still get the detection, I'm doing someting wrong?
I only have ublock origin in my chrome extentions too...
