### ISSUE TITLE
apkmirror.com: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#14719]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.apkmirror.com/apk/electronic-arts/plants-vs-zombies-3-pre-alpha/`

### Category

nuisance

### Describe the issue

I see back **self-promo** placeholders:

```adb
! https://www.apkmirror.com/apk/google-inc/google-wallet/
apkmirror.com##.ains:not(:matches-path(-download))
apkmirror.com##.ains:style(visibility: hidden !important; height: 1px !important; width: 1px important;)
```

~60 days ago hide his tigger anti-adblock so not recommend send this to EasyList. 
`visibility: hidden` worked good these 60 days ago for download pages.

For EasyList **Annoyances** maybe worth report:

```adb
###bottom-slider.apkm-timed-slider
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://user-images.githubusercontent.com/35370833/188951052-75842c02-d08e-4912-bdd5-550bd7edd9a0.png)

![obraz](https://user-images.githubusercontent.com/35370833/188951086-b598a5f3-afd0-4a71-8c4d-80b941a21eb3.png)

![obraz](https://user-images.githubusercontent.com/35370833/188951147-bf6d586b-7d51-4709-92d2-763a1c9013ee.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b4
Firefox: 105
filterset (summary): 
  network: 236164
  cosmetic: 128800
  scriptlet: 21282
  html: 1014
listset (total-discarded, last updated): 
  added:
    ublock-annoyances: 4577-6, 1d.21h.4m
  default: 
    user-filters: 167-0, never
    ublock-filters: 33249-78, 1d.21h.4m
    ublock-badware: 4221-0, 1d.21h.4m
    ublock-privacy: 275-0, 1d.21h.4m
    ublock-abuse: 76-0, 1d.21h.4m
    ublock-unbreak: 1862-1, 1d.21h.4m
    ublock-quick-fixes: 424-0, 1d.21h.4m
    easylist: 64971-626, 1d.21h.4m
    easyprivacy: 27487-621, 1d.21h.4m
    urlhaus-1: 7510-0, 1d.21h.4m
    plowe-0: 3671-3, 1d.21h.4m
    POL-0: 7851-30, 1d.21h.4m
    POL-2: 1279-12, 1d.21h.4m
filterset (user): [array of 134 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cnameUncloakEnabled: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: null
  extensionUpdateForceReload: true
  filterAuthorMode: true
  popupPanelLockedSections: 32
  strictBlockingBypassDuration: 30
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 718 ms (selfie)
  maxAssetCacheWait: 431 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    googlesyndication.com: 11
    googletagmanager.com: 11
```
</details>

**Comment by krystian3w** [comment]
OK, I see anti-adblock here:

`https://www.apkmirror.com/apk/allegro-pl-sp-z-o-o/allegro-convenient-shopping/allegro-convenient-shopping-7-52-0-release/allegro-convenient-shopping-7-52-0-android-apk-download/`

**Comment by stephenhawk8054** [comment]
Can you check if this causes any breakages?

```adb
apkmirror.com##+js(aost, document.querySelectorAll, onload)
```

**Comment by krystian3w** [comment]
Look almost works fine - to test needed upload apk file, maybe fake app for only test anti-adblock.
