### ISSUE TITLE
New Mining Website Not Blocked

### ISSUE THREAD

**Issue by Infinitay** [uBlockOrigin/uAssets#1471]
### URL(s) where the issue occurs

`[oclasrv.com and go.oclasrv.com]`

### Describe the issue

[I have reason to believe this is a crypto-mining website and it's not being blocked via uBlock and it's not in the Resource Abuse list as far as I know.]

### Versions

- Browser/version: [any]
- uBlock Origin version: [any]

### Notes

[I was watching a basketball game and I noticed my fans were loud, and my Chrome's CPU usage very high. I checked out the list of sites I was connected to on the livestreaming website, and only one stood out, "oclasrv.com". When I blocked it ( https://i.imgur.com/B4Hs8Nf.png ), refreshed, and CPU usage went down. 

Not sure if it helps, but apparently go.oclasrv.com leads to `http://www.deloton.com` which also leads to `https://propellerads.com` if that helps. But then again, blocking oclasrv domain solved my issue. Would be nice to have it added to the resource abuse list]

**Comment by okiehsch** [comment]
`oclasrv.com` is part of EasyList **and** Peter Lowe's list, so it is already blocked if you use uBO with a default setup.

**Comment by okiehsch** [comment]
Makes no sense to keep this open without a link to reproduce.
