### ISSUE TITLE
tcsjerky.com: breakage

### ISSUE THREAD

**Issue by Braxusz** [uBlockOrigin/uAssets#14723]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tcsjerky.com`

### Category

breakage

### Describe the issue

When enabled, the scrollbar disappears on the site and you are unable to scroll. Happens on each section of the site, not just main page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Tilamook_not_working_with_uBlock](https://user-images.githubusercontent.com/70422288/189002433-355872fb-8f31-4ac0-81fe-6655cf4ed98d.png)
![Tilamook_working_noUblock](https://user-images.githubusercontent.com/70422288/189002435-5aa40b50-7a97-4e6f-aad0-9aafbab446a5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 82082
  cosmetic: 41825
  scriptlet: 17820
  html: 741
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33235-34, 3d.1h.41m
    ublock-badware: 4206-0, 3d.1h.40m
    ublock-privacy: 273-0, 1d.5h.6m
    ublock-abuse: 76-0, 1d.5h.5m
    ublock-unbreak: 1861-0, 3d.1h.39m
    ublock-quick-fixes: 435-0, 2h.57m
    easylist: 64954-597, 3d.1h.38m
    easyprivacy: 27475-614, 3d.1h.37m
    urlhaus-1: 7688-0, 2h.56m
    plowe-0: 3671-3, 1d.5h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1717 ms (selfie)
  maxAssetCacheWait: 93 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    acsbapp.com: 1
    bing.com: 2
    clarity.ms: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    justuno.com: 1
    klaviyo.com: 2
    sentry-cdn.com: 1
    shopify.com: 2
    shopifysvc.com: 5
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
tcsjerky.com##body.body-load:style(overflow: auto !important;)
```

**Comment by Braxusz** [comment]
That worked like a charm, is there a way to identify a fix like this in the future if I come across it using the tools in the extension?

**Comment by Braxusz** [comment]
> Try this:
> 
> ```
> tcsjerky.com##body.body-load:style(overflow: auto !important;)
> ```

That worked like a charm, is there a way to identify a fix like this in the future if I come across it using the tools in the extension?

**Comment by Procyon-b** [comment]
This is a CSS solution (you don't need ublock to apply it. A userstyle would work)
If you now css you know which property to look for (`overflow`)
Open the devtools, go to "Inspector", focus the _html_ element, look at the "_computed_" panel on the right. Scroll and look if _overflow_ has been defined. In this case, no.
Focus the _body_ element, same as for _html_ . In this case "computed" is redefined. In the style panel you have the list of styles applied. `.body-load` is the classname that redefines _overflow_.
To target _body_ only in this case I use the classname in the css selector used in the filter.

**Comment by Braxusz** [comment]
> This is a CSS solution (you don't need ublock to apply it. A userstyle would work) If you know css you know which property to look for (`overflow`) Open the devtools, go to "Inspector", focus the _html_ element, look at the "_computed_" panel on the right. Scroll and look if _overflow_ has been defined. In this case, no. Focus the _body_ element, same as for _html_ . In this case "computed" is redefined. In the style panel you have the list of styles applied. `.body-load` is the classname that redefines _overflow_. To target _body_ only in this case I use the classname in the css selector used in the filter.

That's great info, thanks again.
