### ISSUE TITLE
twickets.live: breakage

### ISSUE THREAD

**Issue by piemmepi** [uBlockOrigin/uAssets#14726]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twickets.live/`

### Category

breakage

### Describe the issue

Does not work properly 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 104
filterset (summary): 
  network: 83781
  cosmetic: 27111
  scriptlet: 17877
  html: 745
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33371-293, 20h.25m
    ublock-badware: 4220-0, 1d.18h.57m
    ublock-privacy: 263-1, 12d.21h.20m
    ublock-abuse: 76-0, 14m
    ublock-unbreak: 1865-0, 3d.22h.44m
    adguard-mobile: 8042-168, 3d.22h.46m
    easylist: 64950-21554, 3d.22h.45m
    easyprivacy: 27492-588, 14h.57m
    urlhaus-1: 7932-0, 12m
    plowe-0: 3634-3, 10d.22h.35m
    ublock-quick-fixes: 434-0, 13m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16792 ms (selfie)
  maxAssetCacheWait: 1717 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    typekit.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe in details what does not work?

**Comment by andrewmeepos** [comment]
Hello. I can confirm that uBlock Origin with default settings breaks Twickets.

Take the following link to an event on Twickets as an example:
https://www.twickets.live/block/613768007197704,2

Here is what the page looks like with uBlock Origin enabled:
<img width="1462" alt="Screenshot 2022-12-20 at 12 54 29 AM" src="https://user-images.githubusercontent.com/28188533/208625847-78ce85ea-7676-476e-87f5-034e206a8dab.png">

Here is what the page should look like, and does look like, with uBlock Origin disabled.
<img width="1476" alt="Screenshot 2022-12-20 at 12 54 44 AM" src="https://user-images.githubusercontent.com/28188533/208625909-408a37c6-ac85-4838-b5d1-a85ae032918c.png">

Twickets is unusable with uBlock Origin enabled.

**Comment by andrewmeepos** [comment]
@stephenhawk8054 @mapx- 

Should have tagged you in my previous post.

**Comment by okiehsch** [comment]
Are you seeing the breakage on a mobile device?

Site looks fine on a desktop on my end.

**Comment by kdistin** [comment]
This site is still broken:

https://github.com/user-attachments/assets/0741c935-6833-45bf-91c4-bdcb2ef827bc

should be:

https://github.com/user-attachments/assets/83089789-cd7d-4a1e-a543-b4b6c0def069

**Comment by mapx-** [comment]
- provide all the details: specific link, desktop or mobile, required account ?
- test with uBO with default settings / lists

**Comment by kdistin** [comment]
The actual link is: https://www.twickets.live/app/sell
I'm running Firefox 148.0 on a Fedora 43 desktop.

Having tested with the default filter lists (which work) and then turning on others this is the one which causes the failure:

<img width="493" height="158" alt="Image" src="https://github.com/user-attachments/assets/1212af4b-c524-4017-b3ef-b495eb1e538e" />

**Comment by mapx-** [comment]
```adb
@@||twickets.live/app/assets/resources/languages/core/terms/cookiePolicy/*.json$xhr,1p
```
