### ISSUE TITLE
ufacw.com: ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#14725]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ufacw.com/2022/06/shoes-for-evening-dress-which-to-choose/`

### Category

ads

### Describe the issue

referrer
`https://exe.io/Qb0I`

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/189007538-6e82ccf2-8f91-4642-a91a-762ee272a3f5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 112784
  cosmetic: 150055
  scriptlet: 34057
  html: 743
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 69495-5266, now
    adguard-spyware: 27142-1063, now
    adguard-spyware-url: 751-2, now
    adguard-annoyance: 58653-1560, now
    adguard-social: 18437-25, now
  default: 
    user-filters: 60-0, never
    ublock-filters: 33270-53, now
    ublock-badware: 4226-0, now
    ublock-privacy: 273-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1863-1, now
    ublock-quick-fixes: 435-0, now
    easylist: 64596-321, now
    easyprivacy: 27492-9163, now
    TUR-0: 8469-20, now
filterset (user): [array of 63 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3823 ms
  maxAssetCacheWait: 1356 ms
  unsuspendAfter: 1801 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ufacw.com: 1
    demand.supply: 2
    facebook.com: 1
    googlesyndication.com: 7
```
</details>

**Comment by Procyon-b** [comment]
Maybe this:
```
ufacw.com##+js(no-fetch-if, googlesyndication)
```
