### ISSUE TITLE
vimeo.com: nuisance

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14727]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vimeo.com/737566297`

### Category

nuisance

### Describe the issue

annoying sticky banner / login popup

they can be blocked with:

```
vimeo.com##+js(set, vimeo.clip_page_config.google_app_id, '')
vimeo.com##+js(set, vimeo.clip_page_config.banner, {})
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/189054628-87f9c489-0367-440c-906c-4b8670faf1ad.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 171406
  cosmetic: 114461
  scriptlet: 22846
  html: 750
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1942-0, 23m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 23m
    adguard-spyware-url: 751-108, 23m
    block-lan: 43-0, 23m
    curben-phishing: 79022-6, 23m
    curben-pup: 192-0, 23m
    fanboy-annoyance: 80463-347, 23m
    ublock-annoyances: 4576-4, 23m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33283-35, 23m
    ublock-badware: 4226-0, 23m
    ublock-privacy: 273-2, 23m
    ublock-abuse: 76-0, 23m
    ublock-unbreak: 1864-1, 23m
    ublock-quick-fixes: 435-0, 23m
    easylist: 64431-602, 23m
    easyprivacy: 27495-617, 23m
    urlhaus-1: 7932-0, 23m
    plowe-0: 3671-3, 23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 822 ms
  maxAssetCacheWait: 382 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    vimeo.com: 9
    app.link: 3
    googletagmanager.com: 1
    newrelic.com: 1
    vimeocdn.com: 7
```
</details>

**Comment by krystian3w** [comment]
Second is needed?

**Comment by wavygecko** [comment]
- first filter blocks login popup
- second filter blocks sticky bottom banner

**Comment by krystian3w** [comment]
Maybe worth add into locked door project:

https://filterlists.com/lists/browse-websites-without-logging-in

fyi @DandelionSprout / @iam-py-test

**Comment by garry-ut99** [comment]
Be aware the filters have been disabled due to a breakage: https://github.com/uBlockOrigin/uAssets/issues/17992 ==> https://github.com/uBlockOrigin/uAssets/commit/8cf9f7734f7906aad638dec30b69a0dbbe7eeea9
