### ISSUE TITLE
nautiljon.com: breakage

### ISSUE THREAD

**Issue by ActxLeToucan** [uBlockOrigin/uAssets#14720]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nautiljon.com/animes/summer+time+rendering.html`

### Category

breakage

### Describe the issue

The action bar on each article (anime, manga, ...) is totally broken. You can't use many of the actions (set the score, update the counter, like, show who liked, ...).
The website knows this problem (see the 1st screenshot).
(You need to be logged in to use this action bar.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Notice from the site:
![image](https://user-images.githubusercontent.com/56509120/188956684-a2007bdf-c66a-4e9d-8e37-ae3998f5448e.png)
-> If you use adblock and you have a lot of features that don't work anymore on the site, it's because they have a bug, so disable it for Nautiljon.com the time they fix the problem.

The action bar:
![image](https://user-images.githubusercontent.com/56509120/188956393-f10eac58-ad00-41ef-9a90-e106ac5d8f9c.png)

Example, after clicking a button on the counter (with uBlock Origin enabled):
![image](https://user-images.githubusercontent.com/56509120/188955705-b3c3517c-0168-42b2-b48e-1509b8baa7f9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 102116
  cosmetic: 50781
  scriptlet: 17904
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30589-23, 1h.47m
    easylist: 64593-718, 1h.45m
    easyprivacy: 27492-429, 1h.44m
    plowe-0: 3671-823, 2d.23h.32m
    ublock-abuse: 76-1, 2d.23h.34m
    ublock-badware: 4222-112, 1h.48m
    ublock-filters: 32567-244, 1h.43m
    ublock-privacy: 241-1, 2d.23h.35m
    ublock-quick-fixes: 420-1, 1h.41m
    ublock-unbreak: 1850-41, 1h.46m
    urlhaus-1: 7688-0, 1h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 250 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    nautiljon.com: 3
    do69ll745l27z.cloudfront.net: 1
    googletagmanager.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Does this help?
```
*$redirect-rule=noopjs,domain=nautiljon.com
```
