### ISSUE TITLE
socialblade.com: detection

### ISSUE THREAD

**Issue by msifrt** [uBlockOrigin/uAssets#14739]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://socialblade.com/`

### Category

detection

### Describe the issue

Large red boxes appear on the page with the identifier that an AdBlocker is activated and you are asked to deactivate it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/24431825/189313743-61fb9aeb-77e2-4776-8f2f-14bab0ceab31.png)
![image](https://user-images.githubusercontent.com/24431825/189313785-c06c872a-95d5-4f73-880a-c197884415c0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 84162
  cosmetic: 44915
  scriptlet: 17841
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5932-0, 16h.38m
    easylist: 64168-56, 13m
    easyprivacy: 27508-136, 12m
    plowe-0: 3671-846, 16h.40m
    ublock-abuse: 76-0, 16h.39m
    ublock-badware: 4222-101, 11m
    ublock-filters: 32566-126, 10m
    ublock-privacy: 241-1, 4d.1h.10m
    ublock-quick-fixes: 431-1, 16h.37m
    ublock-unbreak: 1851-41, 9m
    urlhaus-1: 7716-0, 16h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 293 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    alexametrics.com: 1
    doubleclick.net: 2
    facebook.net: 1
    google-analytics.com: 1
    lngtd.com: 1
    quantcount.com: 1
    quantserve.com: 1
    youtube.com: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances`
