### ISSUE TITLE
telerama.fr: breakage

### ISSUE THREAD

**Issue by lostinthiswhirlpool** [uBlockOrigin/uAssets#14733]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.telerama.fr/enfants/enfants-trois-jeux-de-societe-ou-mentir-n-est-pas-tricher-7011940.php`

### Category

breakage

### Describe the issue

The comments area doesn't appear on all of the articles from the website `https://www.telerama.fr`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 102432
  cosmetic: 50659
  scriptlet: 17913
  html: 743
listset (total-discarded, last updated): 
  default: 
    user-filters: 19-0, never
    ublock-filters: 33294-34, 38m
    ublock-badware: 4226-0, 12h.1m
    ublock-privacy: 263-0, 7d.43m
    ublock-abuse: 76-0, 7d.44m
    ublock-unbreak: 1864-0, 39m
    easylist: 64509-1258, 40m
    easyprivacy: 27495-617, 12h
    urlhaus-1: 7932-0, 11h.58m
    plowe-0: 3671-3, 12h.2m
    FRA-0: 30582-492, 3d.23h.39m
    ublock-quick-fixes: 435-0, 11h.59m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7218 ms (selfie)
  maxAssetCacheWait: 531 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    telerama.fr: 5
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add & test

`@@||cmp.telerama.fr/js/telerama.min.js$script,1p`

**Comment by lostinthiswhirlpool** [comment]
Hi,
I have added this line in 'My filters', and it works, that's cool !
I've been trying to display this comment area with uBlock Origin for months without success... Thanks !

Just for me to try to understand : what does this line mean, what does this filter add ?

And will this filter be added to an existing filter list, or should I keep it in my personal filters ?

**Comment by mapx-** [comment]
The filter above is an exception added due to this blocking filter from Easyprivacy (cause of the breakage you reported)

`||cmp.telerama.fr^`

@ryanbr 

I notified Easyprivacy maintainer so he'll fix the issue in EP list.
Just keep that filter until the issue will be officially fixed.
