### ISSUE TITLE
ubeat.tv: ads

### ISSUE THREAD

**Issue by Yllelder** [uBlockOrigin/uAssets#14737]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ubeat.tv/v/los-doblajes-de-borja-episodio-xii`

### Category

ads

### Describe the issue

Several visible advertisements.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Portapapeles01](https://user-images.githubusercontent.com/6941502/189277841-87d5940b-c67f-416f-a994-54f3347fd6ed.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 84845
  cosmetic: 46470
  scriptlet: 18086
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 6h.20m
  default: 
    user-filters: 24-0, never
    easylist: 64503-51, 6h.23m
    easyprivacy: 27506-126, 6h.27m
    plowe-0: 3671-844, 6d.6h.22m
    spa-0: 3673-35, 6h.18m
    spa-1: 4624-173, 6h.22m
    ublock-abuse: 76-0, 6d.6h.25m
    ublock-badware: 4222-101, 6h.26m
    ublock-filters: 32590-164, 6h.25m
    ublock-privacy: 241-1, 6d.6h.24m
    ublock-quick-fixes: 402-1, 6h.21m
    ublock-unbreak: 1851-42, 6h.24m
    urlhaus-1: 7716-0, 6h.19m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 338 ms (selfie)
  maxAssetCacheWait: 121 ms
popupPanel: 
  blocked: 447
  blockedDetails: 
    doubleclick.net: 2
    google-analytics.com: 1
    jwpltx.com: 36
    onesignal.com: 1
    sascdn.com: 1
    youboranqs01.com: 406
```
</details>

**Comment by mapx-** [comment]
I get only video-ads

`||cdn.jwplayer.com/videos/$media,domain=ubeat.tv`

@Yuki2718
