### ISSUE TITLE
dfys6.com: ads

### ISSUE THREAD

**Issue by Walker2018** [uBlockOrigin/uAssets#14738]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://dfys6.com/acg/67351/22.html?qp=yj`

### Category

ads

### Describe the issue

there are still ads

**NSFW**
https://user-images.githubusercontent.com/29248534/189313643-ece6046b-909c-4ae2-a93a-719608a63e6c.jpg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 104
filterset (summary): 
  network: 238470
  cosmetic: 170520
  scriptlet: 38304
  html: 750
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 69606-5960, 3d.9h.58m
    adguard-spyware: 27134-1338, 3d.9h.52m
    adguard-spyware-url: 748-3, 3d.9h.51m
    block-lan: 43-0, 17d.12h
    adguard-annoyance: 58568-5241, 3d.9h.49m
    adguard-social: 18407-1656, 3d.9h.48m
    fanboy-thirdparty_social: 68-1, 8d.6h.15m
    fanboy-annoyance: 80019-68184, 8d.6h.13m
    fanboy-cookiemonster: 40535-16965, 8d.6h.14m
    fanboy-social: 23356-13710, 3d.9h.59m
    ublock-annoyances: 4593-7, 3d.9h.47m
    dpollock-0: 11387-482, 6d.6h.53m
    curben-phishing: 79022-8, 23h.39m
    curben-pup: 192-0, 23h.38m
  default: 
    user-filters: 34-11, never
    ublock-filters: 33338-306, 3d.9h.55m
    ublock-badware: 4220-0, 3d.9h.54m
    ublock-privacy: 263-1, 6d.6h.52m
    ublock-abuse: 76-0, 6d.6h.51m
    ublock-unbreak: 1866-0, 3d.9h.53m
    adguard-mobile: 8045-209, 3d.9h.57m
    easylist: 64971-21726, 3d.9h.56m
    easyprivacy: 27488-9638, 3d.9h.50m
    urlhaus-1: 7932-0, 23h.40m
    plowe-0: 3671-3, 4d.2h.19m
    CHN-0: 29045-1364, 3d.9h.46m
    ublock-quick-fixes: 435-0, 23h.41m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4110 ms (selfie)
  maxAssetCacheWait: 3684 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    24klm.cn: 1
    aliyuncs.com: 10
    baidu.com: 2
```
</details>

**Comment by mapx-** [comment]
`dfys6.com##+js(aopr, JSON.parse)`

or

`||dr.mlcuzee.cn^$script,domain=dfys6.com`

@Yuki2718 for CHN list

**Comment by Yuki2718** [comment]
> 
> `||dr.mlcuzee.cn^$script,domain=dfys6.com`

is working fine so @cjx82630

**Comment by cjx82630** [comment]
[Fixed](https://github.com/easylist/easylistchina/commit/c9e882deb4aa567b552e5ca7c0c2652eff01b581)
