### ISSUE TITLE
melgeek.com: breakage

### ISSUE THREAD

**Issue by etrigan63** [uBlockOrigin/uAssets#14730]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.melgeek.com/products/melgeek-keycap-re-cap-mg-ghost-mg-fishing-mg-salmon-mg-salon-keycaps-in-stock?variant=43376559653118`

### Category

breakage

### Describe the issue

Shop site is broken. Contacted vendor and they claim otherwise.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/7347264/189170722-76de622e-14d1-435d-944a-21021bf687bd.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 82155
  cosmetic: 41662
  scriptlet: 17828
  html: 742
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33261-37, 2d.1h.55m
    ublock-badware: 4221-0, 2d.1h.54m
    ublock-privacy: 263-0, 2d.1h.53m
    ublock-abuse: 76-0, 2d.1h.52m
    ublock-unbreak: 1862-0, 2d.1h.51m
    ublock-quick-fixes: 427-0, 23h.2m
    easylist: 64839-598, 2d.1h.49m
    easyprivacy: 27489-614, 2d.1h.48m
    urlhaus-1: 7688-0, 23h.1m
    plowe-0: 3671-3, 2d.1h.46m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 218 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    facebook.net: 1
    getshogun.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    privy.com: 1
    shopify.com: 2
    shopifycloud.com: 8
    shopifysvc.com: 7
    yotpo.com: 7
    ywxi.net: 1
    zotabox.com: 1
```
</details>

**Comment by mapx-** [comment]
> Shop site is broken

Infinite loading ? Give us more details / steps. 
What did you click to get that behaviour ?
Required account ?

**Comment by etrigan63** [comment]
It looks like the site is Linux browser hostile. I removed UbO from Edge
and got the same thing. On a Windows or Mac device it works.
[image: photo]
Carlos Echenique
Photographer at  CE Photographic
P  305.219.2433  <305.219.2433>
E  ***@***.***  ***@***.***>
W  cephotographic.com
<https://mailtrack.io/trace/link/8413adea4f423cd88a6bd031c18709486a718858?url=http%3A%2F%2Fcephotographic.com&userId=3957204&signature=7a9fd8f374160edf>
<https://mailtrack.io/trace/link/b822892d3df44095749b59dfebf9a549fe688e4d?url=http%3A%2F%2Finstagram.com%2Fcephotographic&userId=3957204&signature=127063f0387592c0>
<https://mailtrack.io/trace/link/45b7ac74d17d1a0b6a2c729a670081047d258274?url=http%3A%2F%2Ffacebook.com%2Fcephotos&userId=3957204&signature=3c8082f028628d26>
<https://mailtrack.io/trace/link/890c9de0de666b19c467ed20af3eb8e8f13a98d6?url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fechenique&userId=3957204&signature=bc62acfd4980017a>

"Wine is constant proof that God loves us and loves to see us happy." -
Benjamin Franklin.
Create your own email signature
<https://mailtrack.io/trace/link/321b2649b3c801ab79c23c551194ab71ac201eb6?url=https%3A%2F%2Fwww.wisestamp.com%2Fcreate-own-email-signature%2F%3Futm_source%3Dpromotion%26utm_medium%3Dsignature%26utm_campaign%3Dcreate_your_own%26srcid%3D&userId=3957204&signature=341d2478190a498b>

**Comment by mapx-** [comment]
You should also test after turning OFF the tracking protection in edge
