### ISSUE TITLE
gamerevolution.com => blocked Website Logo

### ISSUE THREAD

**Issue by aaolea** [uBlockOrigin/uAssets#14732]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gamerevolution.com/`

### Describe the issue

We encountered the following using your product:

When activating uBlock the logo of our site disappears: `https://www.gamerevolution.com/`

This has been reported by several users. They are unable to go back to the home screen via the header logo as it's not available when uBlock is activated.

### Screenshot(s)

![Screenshot_33](https://user-images.githubusercontent.com/112659253/189196518-bf999a25-7f22-4d8b-999e-515097e12d8d.jpg)

### uBlock Origin version

v1.44.2

### Browser name and version

Google Chrome Version 103.0.5060.134 (64-bit)

### Settings

- Default

### Notes

The product is blocking our logo asset URL for some reason. 

`https://cdn-www.gamerevolution.com/assets/uploads/2022/09/logo_gr_original.svg`

**Comment by mapx-** [comment]
right click uBO icon, options, "Support" tab, copy and paste here the `Troubleshooting Information` info

**Comment by mapx-** [comment]
If you already tested with uBO disabled for that site (and the logo wasn't blocked)

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by aaolea** [comment]
> If you already tested with uBO disabled for that site (and the logo wasn't blocked)
> 
> * open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
> * repeat the steps to get the issue
> * go back into the uBO's logger and then copy and paste here all blocked requests

Here's the requests, but oddly enough I'm seeing the logo back up when using uBlock.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +4 |  |  | `www.gamerevolution.com` | 3 | css | `https://api.searchiq.co/api/css/1da9b496187e05799d74d64fdf19cd69/custom.css?v=2.2.72&cb=3240793` |
| +4 |  |  | `www.gamerevolution.com` | 3 | css | `https://static.searchiq.co/css/2.2.72/autocomplete.css` |
| +4 |  |  | `www.gamerevolution.com` | 1 | other | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/manifest.json` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/favicon.ico` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/08/cotl-box-236x306.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/08/Rollerdrome-PS5-cover-236x306.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/07/saints-row-2022-box-236x306.jpeg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/08/81l41iKPF3L._SL1500_-236x306.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/08/dreamlight-valley-box-236x306.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/wendell-and-wild-trailer-netflix.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/xbox-elite-series-2-core.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/NZXT-H1-V2-Review_0004_Layer-1.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/final-fantasy-14-callback-campaign.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/agdq-2023.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/oie_vhH9r8aELCZn.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/pokemon-scarlet-violet-nintendo-switch.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/xbox-home-update-dashboard.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/new-battlefield-game-narrative-campaign.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/xbox-fall-showcase-ghostbusters.jpg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/menu_brightness_icon.svg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://cdn-www.gamerevolution.com/assets/uploads/2022/09/logo_gr_original.svg` |
| +3 |  |  | `www.gamerevolution.com` | 3 | image | `https://api.searchiq.co/live?engineKey=1da9b496187e05799d74d64fdf19cd69` |
| +3 | \|\|searchiq.co/api/tr? | -- | `www.gamerevolution.com` | 3 | image | `https://track3.searchiq.co/api/tr?event=impression&eventInfo=%7B%22sid%22%3A%2211167975%22%2C%22said%22%3A%22gamerevolution.com%22%2C%22engine_key%22%3A%221da9b496187e05799d74d64fdf19cd69%22%2C%22source_url%22%3A%22https%3A%2F%2Fwww.gamerevolution.com%2F%22%2C%22external_referrer%22%3A%22%22%2C%22impression_id%22%3A%22607fee20-23e3-47ee-853c-9d7dc84ba781%22%7D&cb=1662666048897` |
| +3 | \|\|ct.pinterest.com^ | -- | `www.gamerevolution.com` | 3 | image | `https://ct.pinterest.com/v3/?tid=2612465858884&event=pagevisit&ed[sid]=11167975&ed[said]=gamerevolution.com&ed[engineKey]=1da9b496187e05799d74d64fdf19cd69` |
| +3 | \|\|facebook.com/tr/ | -- | `www.gamerevolution.com` | 3 | image | `https://www.facebook.com/tr/?id=649690295426340&ev=pageView&cd[sid]=11167975&cd[said]=gamerevolution.com&cd[engineKey]=1da9b496187e05799d74d64fdf19cd69` |
| +3 |  |  | `www.gamerevolution.com` | 3 | script | `https://static.searchiq.co/js/2.2.72/autocomplete.js` |
| +3 |  |  | `www.gamerevolution.com` | 3 | script | `https://static.searchiq.co/js/2.2.72/sa.js` |
| +3 | ##.gpt-ad |  | `www.gamerevolution.com` |  | dom | `https://www.gamerevolution.com/` |
| +3 | noop.js | << | `www.gamerevolution.com` | 3 | script | `https://succeedscene.com/ads_5f62853e-ef16-46c0-a0d5-a6ae101f1f4c/v2/ads.load.js` |
| +3 | \|\|succeedscene.com/ads_*/ads.load.js$script,redirect-rule=noop.js | -- | `www.gamerevolution.com` | 3 | script | `https://succeedscene.com/ads_5f62853e-ef16-46c0-a0d5-a6ae101f1f4c/v2/ads.load.js` |
| +3 | \|\|succeedscene.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://succeedscene.com/ads_5f62853e-ef16-46c0-a0d5-a6ae101f1f4c/v2/ads.load.js` |
| +3 | \|\|evolvemediallc.com^$3p | -- | `www.gamerevolution.com` | 3 | script | `https://secureassets.evolvemediallc.com/js/tracking/gn_tracking.js` |
| +3 | /pxl.gif? | -- | `www.gamerevolution.com` | 3 | image | `https://static.searchiq.co/t/pxl.gif?engineKey=1da9b496187e05799d74d64fdf19cd69&pageUrl=https%3A%2F%2Fwww.gamerevolution.com%2F&referrer=&cb=770659328` |
| +3 |  |  | `www.gamerevolution.com` | 3 | script | `https://api.searchiq.co/api/searchEngines/1da9b496187e05799d74d64fdf19cd69/settings.js?callback=SIQ_settings_loaded&cb=688636023169864` |
| +3 |  |  | `www.gamerevolution.com` | 3 | font | `https://fonts.gstatic.com/s/merriweathersans/v22/2-cM9IRs1JiJN1FRAMjTN5zd9vgsFHXwWDvLBsPDdpWMaq3NzdsFxxU.woff2` |
| +3 |  |  | `www.gamerevolution.com` | 3 | font | `https://fonts.gstatic.com/s/opensans/v34/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/evolvemedia-logo-white.svg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/gamerev.svg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/star.svg` |
| +3 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/small-logo-white.svg` |
| +2 | ##+js(abort-on-property-read, googletag) |  | `www.gamerevolution.com` |  | dom | `https://www.gamerevolution.com/` |
| +2 | ##+js(abort-on-property-read, googletag) |  | `www.gamerevolution.com` |  | dom | `https://www.gamerevolution.com/` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/small-logo.svg` |
| +2 | \|\|tastelesstrucks.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://tastelesstrucks.com/v2dxxXlJSmf2euXxNI1PJ6FSqBgFlm7utBDWRs57aW-GCElTrUxiRAy4` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/discord-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/facebook-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/instagram-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/twitter-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/youtube-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 3 | font | `https://fonts.gstatic.com/s/merriweathersans/v22/2-c99IRs1JiJN1FRAMjTN5zd9vgsFHX1QjU.woff2` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/twitch-icon-white.svg` |
| +2 |  |  | `www.gamerevolution.com` | 1 | image | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/images/svg/navbar_search.svg` |
| +2 |  |  | `www.gamerevolution.com` | 3 | font | `https://fonts.gstatic.com/s/opensanscondensed/v23/z7NFdQDnbTkabZAIOl9il_O6KJj73e7Ff0GmDuXMRw.woff2` |
| +2 | \|\|scorecardresearch.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://sb.scorecardresearch.com/cs/6036161/beacon.js` |
| +2 |  |  | `www.gamerevolution.com` | 3 | script | `https://pub.searchiq.co/js/container/siq-container-2.js?cb=821010&engineKey=1da9b496187e05799d74d64fdf19cd69` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-includes/js/wp-emoji-release.min.js?ver=639` |
| +2 | \|\|evolvemediallc.com^$3p | -- | `www.gamerevolution.com` | 3 | script | `https://secureassets.evolvemediallc.com/prebid/prebid_6_6_0_custom_060120221808.js` |
| +2 | googletagservices.com/gpt.js | << | `www.gamerevolution.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +2 | \|\|googletagservices.com/tag/js/gpt.js$script,redirect-rule=googletagservices.com/gpt.js:5 | -- | `www.gamerevolution.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +2 | \|\|googletagservices.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +2 | \|\|tastelesstrucks.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://tastelesstrucks.com/v2betTkdhqmJfitpTVF0T_o-iJupP3ZGaA_RxTZBbCyWBwnGQTUnG-Xvu2jBG-h5mGTOcJN_L` |
| +2 | \|\|tastelesstrucks.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://tastelesstrucks.com/v2dxxXlJSmf2euXxNI1PJ6FSqBgFlm7utBDWRs57aW-GCElTrUxiRAy4` |
| +2 | \|\|ad.gt^ | -- | `www.gamerevolution.com` | 3 | script | `https://a.ad.gt/api/v1/u/matches/316?url=https%3A%2F%2Fwww.gamerevolution.com%2F&ref=` |
| +2 | \|\|cloudflareinsights.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194` |
| +2 | \|\|pingdom.net^$3p | -- | `www.gamerevolution.com` | 3 | script | `https://rum-static.pingdom.net/pa-5c523a6c9a3f830016000542.js` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/rocket-lazy-load/assets/js/16.1/lazyload.min.js` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-includes/js/wp-embed.min.js` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/vendor/jquery.visible.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/controllers/pb.global.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.dark-theme.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.gamestop-buynow-ga.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.share.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.billboard-close-button.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.scrollout-header.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.konami-code.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/jquery.easteregg.min.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.coming-soon-games.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.slider.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/jquery.bxslider.min.js?ver=4.1.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.autocomplete-search.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/vendors/selectize.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.header-nav.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/controllers/pb.home.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.sticky-element.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.stickify.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/modules/pb.article-listing.js?ver=1.0.5` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/libs/pb.media-queries.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.mediaquery.js?ver=1.7.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-includes/js/underscore.min.js?ver=1.8.3` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/js/libs/pb.utils.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.cookie.notice.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pb-smooth-scroll-to-top/js/pb-smooth-scroll.js?ver=1.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pb-gr-twitch//assets/js/gr.twitch.widget.js?ver=0.1.6` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pb-ajax-sidebars-2/assets/js/pb.sidebar-loader-v2.js?ver=2.0.2` |
| +2 | googletagmanager_gtm.js | << | `www.gamerevolution.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-2328145-1` |
| +2 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | `www.gamerevolution.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-2328145-1` |
| +2 | \|\|googletagmanager.com^ | -- | `www.gamerevolution.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-2328145-1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/modernizr.js?ver=2.6.2` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/pb.core.js?ver=1.0.1` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-scroll-depth/js/jquery-scrolldepth/jquery.scrolldepth.min.js` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/svg-support/js/min/svgs-inline-min.js?ver=1.0.0` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/libraries/pebblebed/js/gn_country.js` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/postscribe.min.js?ver=1.1.2` |
| +2 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/htmlParser.js?ver=1.0.0` |
| +2 | ##+js(abort-on-property-read, googletag) |  | `www.gamerevolution.com` |  | dom | `https://www.gamerevolution.com/` |
| +1 | /contentiq.js | -- | `www.gamerevolution.com` | 3 | script | `https://dashboard.evolveplatform.net/contentiq.js?url=//www.gamerevolution.com/` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.lazy-load-gpt-ads.js?ver=1.0.1` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.load-gpt-ads.js?ver=1.0.1` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.gpt-ads-callbacks.js?ver=1.0.0` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pb-ga-google-analytics/js/pb.ga-init.js?ver=0.0.1` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.auto-refresh.js?ver=1.0.0` |
| +1 |  |  | `www.gamerevolution.com` | 3 | css | `https://fonts.googleapis.com/css?family=Merriweather+Sans:300,400,400i,700\|Merriweather:400,400i,700\|Open+Sans+Condensed:700\|Open+Sans:400,600` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.gpt-builder.js?ver=2.0.1` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/wp-evolve-gpt/js/pb.resize-iframe.js?ver=1.0.0` |
| +1 |  |  | `www.gamerevolution.com` | 1 | script | `https://www.gamerevolution.com/wp-content/plugins/pebblebed/media/js/jquery.ba-resize.js?ver=1.0.0` |
| +1 |  |  | `www.gamerevolution.com` | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js?ver=1.0.3` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/tablepress-responsive-tables/css/tablepress-responsive-flip.min.css?ver=1.5` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/tablepress/css/default.min.css?ver=1.9.1` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/tablepress-responsive-tables/css/responsive.dataTables.min.css?ver=1.5` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/themes/gamerevolution-2018/css/dist/main.css?ver=1651094840` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/wp-lightbox-2/styles/lightbox.min.css?ver=1.3.4` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/nextgen-gallery/css/nggallery.css?ver=1.0.0` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.70` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/spotim-comments/assets/stylesheets/main.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/wp-to-twitter/css/twitter-feed.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/svg-support/css/svgs-attachment.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/pb-spotim-comments//assets/css/cta-widget.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/pb-smooth-scroll-to-top/css/pb-smooth-scroll.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/pb-gr-twitch//assets/css/pb-gr-twitch.css?ver=0.1.0` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/plugins/pb-cover-panel/widget/assets/css/jquery.coverpanel.css` |
| +1 |  |  | `www.gamerevolution.com` | 1 | css | `https://www.gamerevolution.com/wp-content/mu-plugins/general-css/general-styles.css?ver=1.0.0` |
| +1 | \|\|geoedge.be^ | -- | `www.gamerevolution.com` | 3 | script | `https://rumcdn.geoedge.be/grumi-ip.js` |
| +1 | /cdn-cgi/rum? | -- | `www.gamerevolution.com` | 1 | ping | `https://www.gamerevolution.com/cdn-cgi/rum?` |
| +0 |  |  | `www.gamerevolution.com` | 1 | doc | `https://www.gamerevolution.com/` |
</details>

**Comment by mapx-** [comment]
> oddly enough I'm seeing the logo back up when using uBlock

Well, as we can see from the requests the logo image is not blocked
