### ISSUE TITLE
100.lordayeweek.live: ads

### ISSUE THREAD

**Issue by LastDice** [uBlockOrigin/uAssets#14745]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://100.lordayeweek.live/imnoeiey/?u=1nup806&o=0wywy2l&t=LPk3Mix&cid=2i1r5ke10q32a5&f=1&sid=t1~bpan44zhiwwcn40sn0f213rh&fp=2idOR0BAjeggNsygN%2B%2BnRsb%2BCdC2G9g1h6n5cN2ZipdZomVethnFX%2F5mf9O%2BroVjpNqJ9LXxwz3365Pfh9vPAL73sFsOeeNO5qQV6NCBqkMNnPkoB%2BDOvytAQHkijFPdrAh4z%2BeQh8G7jlT5Kd%2FUlNeC43HxQSNYj3Vuj9xMwVTVBAlLaZQ7lxm2yYh5i7tuNorQrFD1IQhR33iyFoha3x6ocjmH52u9K2V1oTpXcneaZZkScmgsKuvsPEnKY7LaO9%2B8dWwCQ%2F%2B5uJ5naFX74nq988oPqUb99lmUZkfRioOQcqSxZ8MTwP8adrtAhpqm1fXMUXuMMiLcdWserfUNmHAV14D%2FrLcipuFZJPeWuAyEz%2Fii3%2FU%2BTqJsLZchuhC1H8rMIPJaMeod40wU8N%2BF%2Fr46KrPQOp7OWsvWUmBb9SdiZzEAReyxIiyerk%2F08jU2%2Bf6NB45ykn%2FlQUxZJmtvFNDnldH73%2F4TsB0Ddx7Pggfkc95AuuLOAXdz%2FRIS1wgS9Rgun%2FINwkPvPn3W882l50XdBB6EQAf%2FreeMzyEA%2ByW0yuuGZDZOXMXXBSLGipk2%2BEnxIorZ1UoZZ2jZ6YYFjmaayoynDAWWQmaQ4lLAiUK408EjO1UWm%2Ba4m6UNUNWiEQD6BSfXe3etQW23xI7mK9IVvSBG0XLo9XIl8HWPldffsTTdCKROIbaymYq1Aw0ek%2BPhYw7I%2BCO1ao5wzcBIjyMRyQVZDF5EME2xE4dkkEJMXOrMmG%2FXKMGvDcoKiVrkgf9391agdPRoxI3b4q%2F2%2FJ6J9seyPNw0YcIG%2BJ%2Fe%2FmsVoUn8VhACV%2BCRwUKmHgZV4yEIPwYBP0xt87QkD0HtOTEWEYBxnwWmQoqty48YyFEsilNxsco%2B2q29ETnN60QwvkHPX2LF25WG47C7rc19tGnQv2Tt3Wk32ZIJNiQsMamKVTlmW18Zu%2FwxBE9YhuN1%2B9IVAjeDHp4ukaskkHUFFMHs2Eo4f7TYUFsKIiXFFA%2Bsnn3wrfu9DXvlNxujNdLgaGLR6Tea%2F0rxhv4wsV3a152BqjyNFRaNNoMGLYiZYEMHrIfK0odPkHBQFu66XrqFFtW7zPhyQVyokh4HVwvngUsBA1S2PNtuaQXvJNw2awjfjgMXGzMBwp4aJSMpxpAnf8nK5qAhwY47HbNylcp7wFF8t7wUHHx%2F%2F%2B8bm6fBkjrYykmyIAKaHjUxAwCbKS%2FyjOoLULLi3RA2GOrrFpF%2BtTG41pcAk0CrI1uUBNIVovgjelHIlHa5mZNkb96IESOA1nTtSotZV8jP0TzwNnAM9fsNy7vUh%2FrOJkw4ev4otra7JXEm4ZoeUVp0XF0wKnqYwkl4JgME%2BqPmEq417LNEKiIditE2BoDQSzcSFcQ1LEbz1b78j79K9OSqCuhcVQWHK8Lb6dbybELYzQ13R7nnmh89lza0g6YLwf7JAvl9dLDpoHJzNLbRV6Yv5VWP9LaV4N4YoB0l%2FbEdX%2BawJbG%2BkF%2FB%2F%2BNhcoyMBVH0N5RmxKfwq%2FfWYljqagG7n%2B4KXg735QSXq5i8cuZ32Wc7pNUZaPivDk0TuKJjCZQZjS0jDmdddpcfaHkMuuVQgjcRqQ8PJ3bISKqmpXRUdicJC0TcdmVGwLBpfNg9vDMdu5pKE1Y9Opwv1QMNTN%2Fbpyf5t8wTgpTCcvuF%2BqkhaHKuqmBiWVrM0NE9FsUPnoJHHOQbFx3kEK0aKyHInXWfMc3Kp024r7NU0QMW2TyEGNxghQXL2clqPWkg%2B6kcLwlXNvOs4Alw1vNsyZHP8%2BiEdwCt%2BGCH3eCKE1mxYVw0%2FBaE8jnUULLuzm9cc1BjRPKJrFC22ifROdbwvxMxn8RfxNgPeoRlqU%2FpesOgr4XZ%2B%2Byig%2BYC6Q1t5oFaOnuGpjOlu%2BlIWthHuhDQ0oEUmEu%2BR5gDqmSaWmvcFRK7WItrwz37T5TpUFwlUcN7%2BS06rF5gOgRppOrrwMUTaCKJx5Kgq0%2F5reAhcfIuaHo%2FofVaA%2FkK4C480Qvg4Kxg%2FgP7cU%2BMq7wOiEX5svJ%2Bx8z9VRt2oQzBIHum`

### Category

ads

### Describe the issue

It's a fraudulent website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 79725
  cosmetic: 42709
  scriptlet: 17941
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
  default: 
    user-filters: 0-0, never
    KOR-1: 3200-6, 7h.22m
    easylist: 64168-84, 7h.26m
    easyprivacy: 27508-135, 7h.25m
    plowe-0: 3673-860, 7h.27m
    ublock-abuse: 76-0, 7h.30m
    ublock-filters: 32590-114, 7h.24m
    ublock-privacy: 251-3, 7h.29m
    ublock-quick-fixes: 407-1, 7h.21m
    ublock-unbreak: 1851-40, 7h.23m
    urlhaus-1: 8051-0, 7h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> ublock-badware: null

You are reporting a fraudulent site but you disabled the badware list

How did you land on that page ? original page ?
