### ISSUE TITLE
newscon.net: ads

### ISSUE THREAD

**Issue by doanmuoi65** [uBlockOrigin/uAssets#14743]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.newscon.net/downloader/`

### Category

ads

### Describe the issue

there are still ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83229
  cosmetic: 42778
  scriptlet: 17911
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1941-0, 9h.28m
    easylist: 64851-59, 3d.9h.17m
    easyprivacy: 27488-131, 3d.9h.16m
    plowe-0: 3634-777, 12d.4h.28m
    ublock-abuse: 76-0, 3d.9h.19m
    ublock-badware: 4217-101, 3d.9h.15m
    ublock-filters: 32545-121, 3d.8h.59m
    ublock-privacy: 253-1, 3d.9h.18m
    ublock-quick-fixes: 402-1, 9h.27m
    ublock-unbreak: 1848-41, 3d.8h.58m
    urlhaus-1: 8051-0, 9h.26m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 161 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 1
    fuseplatform.net: 2
    googletagmanager.com: 1
    googletagservices.com: 1
    videoplayerhub.com: 1
```
</details>

**Comment by doanmuoi65** [comment]
there are still ads

**Comment by doanmuoi65** [comment]
there are still ads

**Comment by mapx-** [comment]
What  ads ? Do you have a specific link ?

**Comment by ghajini** [comment]
may be he mean antiadb warning which comes after 15sec
![image](https://user-images.githubusercontent.com/20338483/189394880-45b53259-3c68-4811-86f5-cc0c902538bc.png)

`newscon.net##+js(nosiif, checkads)`

**Comment by mapx-** [comment]
already fixed as annoyance

@doanmuoi65 enable `uBlock filters – Annoyances`
