### ISSUE TITLE
modrinth.com anti-adb

### ISSUE THREAD

**Issue by KaspianDev** [uBlockOrigin/uAssets#14749]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://modrinth.com/mods`

### Describe the issue

They recently added atb message where ad normally is if ad does not load.
Filter that does resolve it:
```
modrinth.com##.info-wrapper[ethical-ads-big=""]
```

### Screenshot(s)

(github failed uploading)

### uBlock Origin version

1.44.2

### Browser name and version

Firefox developer 105.0b4

### Settings

- Added i dont care about cookies

**Comment by mapx-** [comment]
added as annoyance (uBlock filters – Annoyances)
