### ISSUE TITLE
Block video-player from gvideo.io

### ISSUE THREAD

**Issue by kcherkas** [uBlockOrigin/uAssets#14750]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.u-tv.ru/shows/obmen-zhenami-russkiy-sezon/episodes/1834272/`

### Describe the issue

Blocking the main video-player

### Screenshot(s)

![изображение](https://user-images.githubusercontent.com/18234578/189432416-99636ae7-f0fa-4cf4-aa20-1ba72f4df92e.png)

### uBlock Origin version

1.44.2

### Browser name and version

FF 104.0.2

### Settings

nothing, using default settings

**Comment by mapx-** [comment]
add

`@@||gvideo.io/videos/$frame,domain=u-tv.ru`

@dimisa-RUAdList @ryanbr

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/1ac121ce81c6440ddbbef083225c9ae89058c625

**Comment by MasterKia** [comment]
@kcherkas Enable the "Russian" list if you haven't already.
