### ISSUE TITLE
ergotron.com: breakage

### ISSUE THREAD

**Issue by direrFlood** [uBlockOrigin/uAssets#14756]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ergotron.com/en-gb/company/patented-technology/cf-technology`

### Category

breakage

### Describe the issue

video is not showing when ublock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Imported_2022_09_10_11_10_14](https://user-images.githubusercontent.com/110556802/189474982-b64fc21a-9960-4747-890f-39feae045a8f.png)
</details>
!

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 92045
  cosmetic: 114761
  scriptlet: 19571
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.14h.52m
    ISR-0: 1637-0, 58m
    ara-0: 2601-1, 57m
    fanboy-annoyance: 80465-254, 1d.19h.45m
  default: 
    user-filters: 66-1, never
    easylist: 64873-80, 2d.20h.14m
    easyprivacy: 27492-133, 2d.20h.22m
    plowe-0: 3634-777, 11d.11h.24m
    ublock-abuse: 76-0, 11d.11h.27m
    ublock-badware: 4222-101, 2d.20h.21m
    ublock-filters: 32562-141, 2d.20h.16m
    ublock-privacy: 241-11, 11d.11h.26m
    ublock-quick-fixes: 402-1, 1h
    ublock-unbreak: 1850-44, 2d.20h.15m
    urlhaus-1: 7958-0, 59m
filterset (user): [array of 64 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 647 ms (selfie)
  maxAssetCacheWait: 439 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=ergotron.com`

@ryanbr
