### ISSUE TITLE
myflixer.to: popups

### ISSUE THREAD

**Issue by SquidBoiSwitch** [uBlockOrigin/uAssets#14753]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myflixer.to/watch-tv/breaking-bad-39506.4858939`

### Category

popups

### Describe the issue

clicking redirects to webpage before closing it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 82539
  cosmetic: 41677
  scriptlet: 17841
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 22h.28m
  default: 
    user-filters: 5-0, never
    easylist: 64873-51, 2d.14h.51m
    easyprivacy: 27492-126, 2d.14h.50m
    plowe-0: 3671-814, 2d.22h.56m
    ublock-abuse: 76-0, 14h.25m
    ublock-badware: 4222-101, 2d.14h.49m
    ublock-filters: 32562-111, 2d.14h.48m
    ublock-privacy: 251-1, 14h.24m
    ublock-quick-fixes: 407-1, 18h.26m
    ublock-unbreak: 1849-41, 2d.14h.47m
    urlhaus-1: 8051-0, 18h.27m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 290 ms (selfie)
  maxAssetCacheWait: 153 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    1clickcdn.com: 1
    addthis.com: 1
    cagothie.net: 2
    googletagmanager.com: 2
    imgur.com: 1
    jwpltx.com: 1
    mgbid.net: 2
    onesignal.com: 2
    rndskittytor.com: 1
    staixooh.com: 4
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
mzzcloud.life##+js(aeld, click, /^function _/ )
```

**Comment by mapx-** [comment]
I get no redirecting / popup

**Comment by mapx-** [comment]
it seems fixed here
https://github.com/uBlockOrigin/uAssets/commit/a788dc17e0ccbc1b99255862cfd2e2c208ddfe59
