### ISSUE TITLE
lrepacks.net: ads

### ISSUE THREAD

**Issue by hieuck** [uBlockOrigin/uAssets#14759]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://lrepacks.net/repaki-sistemnyh-programm/333-startisback-aio-repack.html`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-09-10_180251](https://user-images.githubusercontent.com/30469654/189480374-e200ae39-33e0-40c6-8b62-e4582907588d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 86
filterset (summary): 
  network: 84206
  cosmetic: 42744
  scriptlet: 17922
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 22-1, never
    VIE-1: 1935-1267, 45m
    easylist: 64168-352, 1d.3h.43m
    easyprivacy: 27508-453, 1d.3h.42m
    plowe-0: 3634-832, 11d.6h.17m
    ublock-abuse: 76-1, 1d.3h.41m
    ublock-badware: 4232-101, 9h
    ublock-filters: 32588-131, 1d.3h.39m
    ublock-privacy: 251-2, 1d.3h.38m
    ublock-quick-fixes: 415-1, 47m
    ublock-unbreak: 1851-40, 1d.3h.37m
    urlhaus-1: 7958-0, 46m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 941 ms (selfie)
  maxAssetCacheWait: 410 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    absoluteroute.com: 1
    google-analytics.com: 1
    mndsrv.com: 2
    offerimage.com: 2
    translate.googleapis.com: 3
    tzegilo.com: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by MasterKia** [comment]
`Chromium: 86`

Any reason for still using that old insecure browser and not updating?

**Comment by dimisa-RUAdList** [comment]
https://github.com/uBlockOrigin/uAssets/issues/10419
