### ISSUE TITLE
wnd.com Pop-Up suppression Incomplete

### ISSUE THREAD

**Issue by DAMoran2022** [uBlockOrigin/uAssets#14758]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Pop=ups on WND>COM consist of an ad with a separate "close" tab on the top right of the pop-up ad. UBO suppresses the ad itself, leaving the close tab.
[UBO.zip](https://github.com/uBlockOrigin/uBlock-issues/files/9539945/UBO.zip)

### A specific URL where the issue occurs

wnd.com

### Steps to Reproduce

Page down at least one page. Wnd has pop-up ads at the bottom.

### Expected behavior

Pop-up should br suppressed.

### Actual behavior

Pop-up is suppressed, BUT NOT the close tab on the top right of the ad.

### uBlock Origin version

Latest 1.44.2

### Browser name and version

Waterfox G%.0b, Firefox 104.0.2 (64-bit)

### Operating System and version

Windows 7E 64-bit

**Comment by mapx-** [comment]
add

`wnd.com##.persistent-footer`

@ryanbr
