### ISSUE TITLE
en.travel2latam.com: nuisance

### ISSUE THREAD

**Issue by SimplesmenteMaria** [uBlockOrigin/uAssets#14754]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://en.travel2latam.com/`

### Category

nuisance

### Describe the issue

Overlay while scrolling down.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://user-images.githubusercontent.com/110785003/189458451-cbaeebd5-b84a-49f1-b074-8b524a8d8819.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 105755
  cosmetic: 147468
  scriptlet: 37084
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
  added: 
    adguard-annoyance: 58690-83, 15h.41m
    adguard-generic: 69586-499, 15h.40m
    adguard-social: 18442-878, 15h.43m
    adguard-spyware: 27153-1121, 15h.42m
    adguard-spyware-url: 751-1, 15h.46m
    block-lan: 43-0, now
    spa-1: 4624-86, 15h.45m
    ublock-annoyances: 4798-189, 15h.44m
  default: 
    user-filters: 0-0, never
    easylist: 64168-1083, 15h.39m
    plowe-0: 3673-495, 15h.47m
    ublock-abuse: 76-0, 5d.21h.57m
    ublock-badware: 4222-331, 15h.38m
    ublock-filters: 32590-3964, 15h.37m
    ublock-privacy: 241-38, 5d.21h.56m
    ublock-quick-fixes: 407-13, 15h.35m
    ublock-unbreak: 1851-95, 15h.36m
    urlhaus-1: 8051-0, 15h.34m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2635 ms (selfie)
  maxAssetCacheWait: 3749 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cloudflareinsights.com: 2
    googletagmanager.com: 2
    googletagservices.com: 1
    onesignal.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
travel2latam.com##+js(nostif, popup_)
```

**Comment by mapx-** [comment]
or classic filter

`travel2latam.com###t2l_popup_newsletter`

report directly at fanboy's annoyances or adguard annoyances

@ryanbr

**Comment by SimplesmenteMaria** [comment]
AdGuard won't add it: https://github.com/AdguardTeam/AdguardFilters/issues/129250.

**Comment by mapx-** [comment]
well, use one of the filters above in your "my filters" section
