### ISSUE TITLE
kinopoisk.ru: ads

### ISSUE THREAD

**Issue by DaemonLife** [uBlockOrigin/uAssets#14763]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kinopoisk.ru/film/497/`

### Category

ads

### Describe the issue

When you watch the movie trailer, two commercials open

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 82434
  cosmetic: 41206
  scriptlet: 17861
  html: 745
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33330-35, 22h.28m
    ublock-badware: 4226-0, 22h.27m
    ublock-privacy: 273-0, 22h.31m
    ublock-abuse: 76-0, 22h.32m
    ublock-unbreak: 1864-0, 22h.25m
    ublock-quick-fixes: 412-0, 22h.21m
    easylist: 64338-606, 22h.24m
    easyprivacy: 27511-645, 22h.23m
    urlhaus-1: 7993-0, 22h.22m
    plowe-0: 3671-3, 22h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1518 ms (selfie)
  maxAssetCacheWait: 445 ms
popupPanel: 
  blocked: 85
  blockedDetails: 
    adfox.ru: 2
    adlooxtracking.com: 1
    tns-counter.ru: 1
    weborama.fr: 1
    yandex.net: 7
    yandex.ru: 72
    yastatic.net: 1
```
</details>

**Comment by mapx-** [comment]
Russian site => enable `RUS: RU AdList` list
