### ISSUE TITLE
[nsfw] ferme-lesca.fr: ads

### ISSUE THREAD

**Issue by GUGUDALI** [uBlockOrigin/uAssets#14769]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ferme-lesca.fr/`

### Category

ads

### Describe the issue

This website is completely designed to show click ads,
They collected the most searched words on Google on their home page, and it was designed to defraud people who clicked on the links.
(Used Google Translate)

**Sites to which links refer:**
- https://1112.postlakemug.live/
- https://odulunual.sa.com/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://user-images.githubusercontent.com/55906355/189521035-0267dad7-3551-4b64-9b9e-b6d7a41928d2.jpg)
![2](https://user-images.githubusercontent.com/55906355/189521049-29cacd23-01cc-4c23-8dd1-7e76bf612c17.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83695
  cosmetic: 47478
  scriptlet: 18220
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-1, never
    TUR-0: 8476-13, 2d.57m
    easylist: 64168-68, 2d.56m
    easyprivacy: 27508-131, 2d.55m
    plowe-0: 3671-847, 1d.8h
    ublock-abuse: 76-0, 1d.8h.3m
    ublock-badware: 4222-101, 2d.54m
    ublock-filters: 32583-123, 2d.53m
    ublock-privacy: 251-1, 1d.8h.2m
    ublock-quick-fixes: 431-1, 16h.9m
    ublock-unbreak: 1851-40, 2d.52m
    urlhaus-1: 7634-0, 16h.10m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    scriptcdn.net: 1
```
</details>

**Comment by okiehsch** [comment]
Thanks for the report.
Please don't use a hotlink if it involves dodgy sites.
