### ISSUE TITLE
mangacrab.com: detection

### ISSUE THREAD

**Issue by forcecde** [uBlockOrigin/uAssets#14766]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mangacrab.com/`

### Category

detection

### Describe the issue

Detect ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 110052
  cosmetic: 90319
  scriptlet: 47044
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 8m
    https://filters.adavoid.org/ultimate-ad-filter.txt: 117301-1350, 8m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8m
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/antiadblock.txt: 17883-6952, 7m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24071-37, 8m
    adguard-generic: 69878-53371, 8m
  default: 
    user-filters: 3-0, never
    easylist: 64283-64231, 8m
    easyprivacy: 30556-1287, 8m
    plowe-0: 3671-867, 8m
    spa-0: 3685-96, 8m
    spa-1: 4626-184, 8m
    ublock-abuse: 76-1, 8m
    ublock-badware: 4232-331, 8m
    ublock-filters: 32638-6225, 8m
    ublock-privacy: 251-1, 8m
    ublock-unbreak: 1852-87, 8m
    urlhaus-1: 7628-0, 8m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 29 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1247 ms
  maxAssetCacheWait: 998 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    cloudflareinsights.com: 1
    disqus.com: 2
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    narrative.io: 1
    onesignal.com: 1
    pippio.com: 1
    rezync.com: 1
    rlcdn.com: 1
    viglink.com: 2
    wp.com: 1
    youtube.com: 1
```
</details>

**Comment by ghajini** [comment]
i get access denied message
@Yuki2718 spanish website for AG spanish?

**Comment by Yuki2718** [comment]
> i get access denied message 

Me too even with Spanish or Columbian IP
