### ISSUE TITLE
bilibili.com: blank spaces

### ISSUE THREAD

**Issue by InkJadeite** [uBlockOrigin/uAssets#14767]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

blank spaces on page

### Describe the issue

这些视频和广告在同一行，导致在页面上出现了空白区域。
The videos are on the same line as the ads, resulting in some blank space on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-11 at 12-37-42 哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://user-images.githubusercontent.com/59567872/189512987-92b8ea2c-0b1a-489d-8ee7-9ccc50ecc187.png)
![Screenshot 2022-09-11 at 13-02-29 哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://user-images.githubusercontent.com/59567872/189513234-3e40b75f-3301-45b0-a20c-ef58aa7a81d0.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 105
filterset (summary): 
  network: 102860
  cosmetic: 51268
  scriptlet: 17978
  html: 746
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33349-53, 30m
    ublock-badware: 4236-0, 30m
    ublock-privacy: 273-0, 30m
    ublock-abuse: 76-0, 30m
    ublock-unbreak: 1865-0, 30m
    ublock-quick-fixes: 412-0, 30m
    easylist: 64283-641, 30m
    easyprivacy: 30556-1698, 30m
    urlhaus-1: 7628-0, 30m
    plowe-0: 3671-3, 30m
    CHN-0: 29167-111, 15m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  prefetchingDisabled: false
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 233 ms
  unsuspendAfter: 93 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    bilibili.com: 3
    hdslb.com: 2
```
</details>

**Comment by mapx-** [comment]
I get no blank spaces on the home page

**Comment by InkJadeite** [comment]
Hello, I found that different accounts have different performance on this website.
Here are screenshots of two accounts and one unlogged account.
您好，我发现不同的账号在这个网站上有不同的表现。
这里有两个账号和一个未登录账号的网页截图。


When logging into the first account, the page appears blank.
and When uBO is closed, some videos appear with the tag "AD"
在登录第一个账户时，首页出现了空白。
当关闭uBO之后，有一些带有“广告”标签的视频出现


When logging into the second account, the page detected uBO
If you do not log in to the page, the page is normal
在登录第二个账户时，网页检测出了uBO。
在未登录的页面，网页正常。
### Account 1
<details>
close uBO

Notice the red circle,its meaning is advertising

![1-0-1](https://user-images.githubusercontent.com/59567872/190866768-02df0e3f-07ca-44e4-8b19-236a04ad5b25.png)
open uBO

![1-1](https://user-images.githubusercontent.com/59567872/190864711-518bc892-73b2-429d-b5b2-0d4c324f8827.png)

![1-2](https://user-images.githubusercontent.com/59567872/190864713-34c9ecbe-7333-4ee8-936e-4d872833f0d0.png)
![1-3](https://user-images.githubusercontent.com/59567872/190864714-5b96aae7-c9d3-48ed-bfd5-451f3874fa70.png)

</details>

 
### Account 2
<details>
You can see adblock-tips

![2-1](https://user-images.githubusercontent.com/59567872/190865181-cf18839e-f007-490e-bbfc-81962503081e.png)
![2-2](https://user-images.githubusercontent.com/59567872/190865183-3ffe2662-a6e8-47e4-bba5-5927ccfd7397.png)

</details>

 
### Unlogged
<details>
No AD,no tips

![3](https://user-images.githubusercontent.com/59567872/190865198-14dfbd87-a7a5-4575-83b6-59b218b40ee6.png)

</details>

**Comment by mapx-** [comment]
maybe @cjx82630 could help here

**Comment by cjx82630** [comment]
可以自定义试试`bilibili.com#?#.bili-video-card:-abp-has(.bili-video-card__info--ad-img)` 
前段时间这规则导致闪烁,已经临时移除.

**Comment by cjx82630** [comment]
可以自定义这规则 `bilibili.com#?#.business-card:-abp-has(.bili-video-card__info--ad)`
但是会出现闪烁

**Comment by mapx-** [comment]
- @InkJadeite use the filter above, eventually with `:remove()`
- for the second issue we cannot help (2 accounts), you should further investigate on your side
