### ISSUE TITLE
bluemediafiles.eu: detection

### ISSUE THREAD

**Issue by robert21281** [uBlockOrigin/uAssets#14765]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://bluemediafiles.eu/url-generator.php?url=onAhF5ZLCDGjfP3AAUIv/XlRmDn+wudFEkfnJ7uEgBcfp7Wht4h1F0dFSld5gNUK2Wq4szXzsRycnQeRv+51N+fdNl82CwXVB46gi10hr+up0xudcI+5I+NxtMYiNF2S`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/18016422/189504632-9af2551a-c9fd-4f91-9f6a-9fd1cfd7392a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 83590
  cosmetic: 48970
  scriptlet: 18057
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    POL-0: 7849-8, 10h.23m
    POL-2: 1276-13, 10h.24m
    easylist: 64499-74, 2d.4h.34m
    easyprivacy: 27500-126, 2d.4h.33m
    plowe-0: 3671-854, 6d.23h.32m
    ublock-abuse: 76-0, 8d.43m
    ublock-badware: 4222-101, 2d.4h.32m
    ublock-filters: 32585-151, 2d.4h.31m
    ublock-privacy: 241-1, 8d.42m
    ublock-quick-fixes: 415-2, 10h.22m
    ublock-unbreak: 1851-41, 2d.4h.30m
    urlhaus-1: 7958-0, 10h.21m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 247 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    bluemediafiles.eu: 1
    376048ad5f7feb89addaebe2a755a678fe27fc5f4b60c033151bd67.s3.amazonaws.com: 1
    bebi.com: 2
    bookljlihooli.com: 1
    choobinoobi.com: 1
    d301cxwfymy227.cloudfront.net: 2
    googletagmanager.com: 1
    sixthpriodon.com: 1
    tykinggowd.com: 1
```
</details>

**Comment by krystian3w** [comment]
test with: https://greasyfork.org/pl/scripts/423435-igg-games-bluemediafiles-bypass https://greasyfork.org/pl/scripts/425739-igg-games-bluemediafiles-auto-continue-after-wait

**Comment by D3mong13** [comment]
> 

``

**Comment by D3mong13** [comment]
Yc6v5

**Comment by D3mong13** [comment]
> Yc6v5

**Comment by D3mong13** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14765#issuecomment-1242818464
