### ISSUE TITLE
linkvertise.com: no longer skips the annoying steps

### ISSUE THREAD

**Issue by SquidBoiSwitch** [uBlockOrigin/uAssets#14761]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkvertise.com/`

### Category

ads

### Describe the issue

doesnt skip the steps needed to get to the link anymore

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 82443
  cosmetic: 41214
  scriptlet: 17866
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 17h.14m
  default: 
    user-filters: 5-0, never
    easylist: 64338-51, 17h.14m
    easyprivacy: 27511-126, 17h.14m
    plowe-0: 3671-846, 17h.14m
    ublock-abuse: 76-0, 17h.14m
    ublock-badware: 4232-101, 17h.14m
    ublock-filters: 32623-119, 17h.14m
    ublock-privacy: 251-1, 17h.14m
    ublock-quick-fixes: 415-2, 17h.14m
    ublock-unbreak: 1851-40, 17h.14m
    urlhaus-1: 7993-0, 17h.14m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 991 ms (selfie)
  maxAssetCacheWait: 463 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    brightcove.com: 5
    googletagmanager.com: 1
    indexww.com: 1
    media.net: 1
    nighttstand.com: 1
    ostrichesica.com: 2
    sentry.io: 1
    streamrail.com: 1
    taboola.com: 1
```
</details>

**Comment by MasterKia** [comment]
Send the linkvertise.com link.
