### ISSUE TITLE
upc.pl: breakage

### ISSUE THREAD

**Issue by szyha** [uBlockOrigin/uAssets#14771]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.upc.pl/pomoc/`

### Category

breakage

### Describe the issue

Clicking on ``Rozpocznij czat`` button does not open chat.
Tested also on the default configuration with this same problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/12976368/189524245-5ff251b5-9a3f-420a-a34d-375cf44641b6.mp4

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 273386
  cosmetic: 203599
  scriptlet: 35888
  html: 1015
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 363-0, now
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1944-2, now
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 148002-198, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 21836-365, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 883-0, now
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 12889-1, now
    https://www.i-dont-care-about-cookies.eu/abp/: 25350-145, now
    adguard-generic: 69883-5533, now
    curben-pup: 192-0, now
    fanboy-annoyance: 80430-9660, now
    ublock-annoyances: 4814-43, now
    dpollock-0: 11387-482, now
  default: 
    user-filters: 6-0, never
    ublock-filters: 33375-81, now
    ublock-badware: 4239-0, now
    ublock-privacy: 273-2, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1865-0, now
    ublock-quick-fixes: 424-0, now
    easylist: 64051-815, now
    easyprivacy: 30558-1797, now
    urlhaus-1: 7628-0, now
    plowe-0: 3674-3, now
    POL-0: 7854-39, now
    POL-2: 1279-12, now
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3017 ms
  maxAssetCacheWait: 3096 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Cookie popup is blocked

```adb
@@||www.googletagmanager.com/gtm.js$script,domain=upc.pl
```

@ryanbr
