### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by Leo4542** [uBlockOrigin/uAssets#14773]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dgdrive.xyz/zfputgs1xh5e`
=>
`https://dropgalaxy.com/zfputgs1xh5e`

### Category

detection

### Describe the issue

Ublock detected 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 104
filterset (summary): 
  network: 316200
  cosmetic: 259155
  scriptlet: 41690
  html: 820
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 69884-6793, 1d.19h.11m
    adguard-spyware: 27158-1440, 1d.19h.11m
    adguard-spyware-url: 752-2, 1d.19h.11m
    block-lan: 43-0, 1d.19h.11m
    curben-phishing: 82943-10, 18h.7m
    curben-pup: 192-0, 18h.35m
    adguard-annoyance: 58719-5566, 1d.19h.11m
    adguard-social: 18445-1666, 1d.19h.10m
    fanboy-thirdparty_social: 69-1, 1d.19h.11m
    fanboy-annoyance: 80475-68642, 1d.19h.11m
    fanboy-cookiemonster: 40889-16993, 1d.19h.11m
    fanboy-social: 23357-13719, 1d.19h.11m
    ublock-annoyances: 4832-11, 1d.19h.11m
    dpollock-0: 11387-500, 1d.19h.10m
    ALB-0: 273-7, 18h.38m
    ara-0: 2601-241, 7h.28m
    BGR-0: 1091-19, 1d.19h.10m
    CHN-0: 29124-1341, 1d.19h.11m
    CZE-0: 725-40, 18h.33m
    DEU-0: 5933-385, 18h.34m
    [28 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    ublock-filters: 33432-682, 1d.19h.11m
    ublock-badware: 4235-0, 1d.19h.11m
    ublock-privacy: 273-1, 1d.19h.11m
    ublock-abuse: 76-0, 1d.19h.11m
    ublock-unbreak: 1869-7, 1d.19h.11m
    ublock-quick-fixes: 407-0, 7h.17m
    adguard-mobile: 8107-240, 1d.19h.15m
    easylist: 64338-21951, 1d.19h.10m
    easyprivacy: 27511-9693, 1d.19h.10m
    urlhaus-1: 7628-0, 7h.16m
    plowe-0: 3671-3, 1d.19h.10m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2250 ms (selfie)
  maxAssetCacheWait: 1284 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    a-ads.com: 1
    cloudflareinsights.com: 1
```
</details>

**Comment by adsdestroyer** [comment]
working fine here no adblock message. leochutiya wasting time here.
