### ISSUE TITLE
blancoshrimp.com: ads

### ISSUE THREAD

**Issue by xDopure** [uBlockOrigin/uAssets#14774]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blancoshrimp.com/?rdk=rk1`

### Category

ads

### Describe the issue

whole page of ads
opened as pop up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/25983734/189538036-e88c6b20-a411-4ffe-bca7-ecbf9192f6f5.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 107232
  cosmetic: 58933
  scriptlet: 18158
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 17h.14m
    DEU-0: 5933-0, 17h.11m
    FRA-0: 30589-37, 2d.20h.27m
    spa-0: 3685-99, 17h.10m
    spa-1: 4624-180, 2d.20h.28m
  default: 
    user-filters: 3-0, never
    easylist: 64338-764, 1d.23h.8m
    easyprivacy: 27511-437, 1d.23h.7m
    plowe-0: 3634-818, 12d.3h.2m
    ublock-abuse: 76-1, 2d.20h.30m
    ublock-badware: 4217-112, 1d.23h.6m
    ublock-filters: 32599-312, 1d.23h.5m
    ublock-privacy: 251-1, 2d.20h.29m
    ublock-quick-fixes: 403-2, 17h.12m
    ublock-unbreak: 1851-43, 1d.22h.44m
    urlhaus-1: 7634-0, 17h.13m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 74 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    securely-send.com: 1
```
</details>

**Comment by mapx-** [comment]
Provide the original page where clicking you'll land on the site above
