### ISSUE TITLE
superstats.dk: breakage

### ISSUE THREAD

**Issue by reportingproblemsonly** [uBlockOrigin/uAssets#14770]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://superstats.dk/`

### Category

breakage

### Describe the issue

Site UI breaks to only show plaintext

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 82924
  cosmetic: 43086
  scriptlet: 17867
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NOR-0: 2802-7, 5m
    easylist: 64338-52, 1d.16h.3m
    easyprivacy: 27511-127, 1d.16h.2m
    plowe-0: 3671-846, 5d.18h.45m
    ublock-abuse: 76-0, 5d.18h.43m
    ublock-badware: 4222-102, 1d.16h.1m
    ublock-filters: 32572-119, 1d.16h
    ublock-privacy: 251-1, 5d.18h.39m
    ublock-quick-fixes: 409-2, 4m
    ublock-unbreak: 1851-40, 1d.15h.59m
    urlhaus-1: 7628-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 221 ms (selfie)
  maxAssetCacheWait: 97 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    superstats.dk: 14
    cleverwebserver.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    twitter.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
/superstats.$badfilter
/superstats.$domain=~superstats.dk
```

@ryanbr
