### ISSUE TITLE
uploadydl.com: detection

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#14775]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uploadydl.com/uj620o7c4996`

### Category

detection

### Describe the issue

The detector is triggered a few seconds after opening the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![upload-det](https://user-images.githubusercontent.com/20126984/189543503-f5f0a5d3-8450-4354-8e96-79c654e72bd2.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 85384
  cosmetic: 78534
  scriptlet: 19527
  html: 746
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    RUS-0: null
  added: 
  default: 
    ublock-filters: 33389-47, now
    ublock-badware: 4239-0, now
    ublock-privacy: 273-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1865-0, now
    ublock-quick-fixes: 437-0, now
    easylist: 64056-623, now
    easyprivacy: 30560-1701, now
    urlhaus-1: 7316-0, now
    plowe-0: 3674-3, now
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 596 ms (selfie)
  maxAssetCacheWait: 755 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    furlsstealbilk.com: 2
    google-analytics.com: 1
    sharethis.com: 1
    waisheph.com: 2
```
</details>

**Comment by dportvine** [comment]
When the storage period has expired.

<details>
<summary>Screen</summary>

![2022-10-04_100922](https://user-images.githubusercontent.com/111344219/193756779-70938aa3-bcde-410d-80a5-b33b0f8d7bc1.png)
</details>
