### ISSUE TITLE
mall.tv: detection

### ISSUE THREAD

**Issue by JinruiTeki** [uBlockOrigin/uAssets#14788]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mall.tv/vlaky-a-tramvaje/mazacka-jizda-prahou`

### Category

detection

### Describe the issue

Site is detected uBlock and blocking maps.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок](https://user-images.githubusercontent.com/41969496/189609062-68bb2967-6975-44a3-bb6c-8024e53e6243.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 92
filterset (summary): 
  network: 100391
  cosmetic: 63705
  scriptlet: 19043
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33335-35, 1d.23h.41m
    ublock-badware: 4236-0, 1d.23h.38m
    ublock-privacy: 273-0, 1d.23h.37m
    ublock-abuse: 76-0, 1d.23h.36m
    ublock-unbreak: 1865-0, 1d.23h.35m
    ublock-quick-fixes: 413-0, 21h.28m
    easylist: 64353-607, 1d.23h.33m
    easyprivacy: 27513-645, 1d.23h.15m
    urlhaus-1: 7628-0, 21h.27m
    plowe-0: 3671-3, 1d.23h.13m
    RUS-0: 42153-163, 1d.23h.45m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 818 ms (selfie)
  maxAssetCacheWait: 756 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    mall.tv: 10
    caroda.io: 1
    doubleclick.net: 1
    facebook.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 3
    performax.cz: 1
    privacy-center.org: 1
    rubiconproject.com: 2
    slunecnice.cz: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
`endless-live.cz#@##reklama`
