### ISSUE TITLE
Seemingly for-sale domain name

### ISSUE THREAD

**Issue by sugarfreesweetener** [uBlockOrigin/uAssets#14780]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`vidmela.com` => `https://www.hugedomains.com/domain_profile.cfm?d=vidmela.com`

### Describe the issue

Possibly obsolete filters from uBlock Origin's "uBlock Filters":

- `vidmela.com##+js(set, xxSetting.adBlockerDetection, false)`
- `@@||vidmela.com^$ghide`

### uBlock Origin version

1.44.2

### Browser name and version

Firefox

### Settings

N/A

**Comment by sugarfreesweetener** [comment]
Would it be possible to use this issue or a different issue for informing about any filters / domain names should I find any obsolete filters in uAssets?

**Comment by mapx-** [comment]
Just go with PR
