### ISSUE TITLE
atresplayer.com: ads

### ISSUE THREAD

**Issue by BaldHard** [uBlockOrigin/uAssets#14797]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.atresplayer.com/`

### Category

ads

### Describe the issue

In the website, all the ads are blocked but when you try to watch a video, it shows the usual 3 ads before showing the content. I've tried uninstalling and reinstalling the extension, purge caches and updating and nothing works

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 86500
  cosmetic: 45981
  scriptlet: 18120
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64103-52, 20m
    easyprivacy: 30569-1171, 20m
    plowe-0: 3674-860, 20m
    spa-0: 3692-35, 20m
    spa-1: 4629-171, 20m
    ublock-abuse: 76-0, 20m
    ublock-badware: 4245-102, 20m
    ublock-filters: 32699-176, 20m
    ublock-privacy: 246-1, 20m
    ublock-quick-fixes: 423-2, 20m
    ublock-unbreak: 1847-42, 20m
    urlhaus-1: 7168-0, 20m
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 466 ms (selfie)
  maxAssetCacheWait: 121 ms
popupPanel: 
  blocked: 84
  blockedDetails: 
    atresplayer.com: 3
    adform.net: 1
    adsrvr.org: 1
    appsflyer.com: 1
    atresmedia.com: 1
    chartbeat.com: 1
    conviva.com: 20
    demdex.net: 6
    doubleclick.net: 2
    doubleverify.com: 3
    everesttech.net: 1
    facebook.net: 1
    fwmrm.net: 13
    getpublica.com: 1
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 2
    googletagservices.com: 1
    hotjar.com: 1
    mathtag.com: 1
    moatads.com: 1
    nice264.com: 1
    omtrdc.net: 7
    outbrain.com: 1
    richaudience.com: 3
    scorecardresearch.com: 1
    smartclip.net: 1
    spotxchange.com: 1
    stickyadstv.com: 3
    tiktok.com: 1
```
</details>

**Comment by mapx-** [comment]
Can you indicate a free video still with ads ?

![image](https://user-images.githubusercontent.com/10303732/189818143-86d3169b-2337-4ea3-81c2-95dae5047ead.png)

**Comment by BaldHard** [comment]
They don't appear appear anymore, but the player is still trying to display the ads. After clicking the play button the load symbol  appears for 15 secons, same as in the middle of the video when it tries to display more ads.
Thank you for your work

![Captura de pantalla 2022-09-13 08 13 05](https://user-images.githubusercontent.com/13878689/189983022-847f0414-de5f-45e3-b2b2-a42bfa4babbf.png)

**Comment by mapx-** [comment]
without testing .. nothing to do

**Comment by BaldHard** [comment]
With this account you have access to free content (just free content and accounts show ads)

email: rayshad.suhan@eledeen.org
password: BaldHard10

An example of free content is this video:

[https://www.atresplayer.com/lasexta/programas/al-rojo-vivo/septiembre-2022/13-09-22-diaz-pide-compromiso-para-limitar-los-precios-de-la-cesta-de-la-compra-y-planas-rechaza-medidas-impuestas_6320730338cfb0e464c95471/](url)

**Comment by mapx-** [comment]
even using that account I get 
https://github.com/uBlockOrigin/uAssets/issues/14797#issuecomment-1244925093

**Comment by BaldHard** [comment]
I used a VPN selecting the US and it seems it's just free in Spain. Maybe you can check it using it with Spain as location. I think it should work.

**Comment by mapx-** [comment]
Yes, with a spanish ip I can watch the video, no video ad. I'm no sure why that initial waiting time (slow due to vpn ? ).
On the other hand I get in the logger only blocked tracking requests .. so no ad ?!

**Comment by BaldHard** [comment]
> Yes, with a spanish ip I can watch the video, no video ad. I'm not sure why that initial waiting time (slow due to vpn ? ).

With high speed fiber it also happens. I think it tries to load ads and it takes awile to show the content. Also, when watching the tv show, after some minutes (around 20 mins, i'd say) the video stops and that load screen appears for 30 seconds.

**Comment by mapx-** [comment]
try

```
@@||imasdk.googleapis.com/js/sdkloader/vpaid_adapter.js$script,domain=atresplayer.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=atresplayer.com
```

**Comment by mapx-** [comment]
nobody tested the filters above ?

**Comment by BaldHard** [comment]
They don't work and the videos of the website show ads again, but now after those 20 secs loading. They are making it hard haha

**Comment by BaldHard** [comment]
Also this website of the same company is showing ads at the beginning of videos:

https://www.lasexta.com/programas/lasexta-clave/que-mandatarios-internacionales-iran-vuelos-comerciales-funeral-isabel_2022091563239d4060c19f0001975a84.html

**Comment by mapx-** [comment]
for `lasexta` test:

```
@@||imasdk.googleapis.com/js/sdkloader/vpaid_adapter.js$script,domain=www.lasexta.com
||publi.atresmediapublicidad.com^$media,domain=lasexta.com,redirect=noopmp3-0.1s
```

**Comment by BaldHard** [comment]
> instant load the videos in atresplayer for me with this filter:
> 
> `||mssl.fwmrm.net/libs/adm/*/AdManager.js$script,domain=www.atresplayer.com,important ` whitelisted in easylist
> 
> Example URL: `https://www.atresplayer.com/directos/lasexta/`

This worked perfectly, thanks!

**Comment by BaldHard** [comment]
> I don't see ads.. anyways I tested you filters
> 
> but 20+ seconds for play the video in **lasexta**

Yeah, same for me. No ads in La Sexta but i have to wait some seconds
