### ISSUE TITLE
techvybes.com: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14790]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techvybes.com/?id=Y21BeDBicmo5RkowZ1Zqbm5paC9PUk9QNmFncnJKR0tRQTI0UWxrRldzQVB1aEZzdjdleU1MTnBuVWVSa3dPNkJxcVlkSjZ2bnhtL1dWT1R4SXZ1bGxRK1d5TXJuY3JjSmxwazVUc0p1enR5bnlYL3czTGtvVzNWcFp6SW92bTA=`

### Category

nuisance

### Describe the issue

`https://vegamovies.store/?7586d82ad6=OVdxdWhQVUZTVG8vY1U1T0RrNkt2cXdLcUxETkdqOWR1SERJdDF1endqWEtYa3Jqb2JpSmE5emRyYStCeXNJaGdZMFVMMFRMSnpRSzVvc3R4OGtpQU8xeWZGQUk5VTExSDVnSG1SdUtwL0VjOU40WEVybjFIWHlBdHpFQTNmenk=`

This Takes To Techvybes.com...Nano-sib ByPassed Timer But Doesn't Boost The Actual Steps..It Shows Please Wait And Still Makes Me Wait

techvybes.com###lite-human-verif-button, #lite-start-sora-a, #lite-end-sora-button:others()
techvybes.com###lite-human-verif-button, #lite-start-sora-a, #lite-end-sora-button:style(display: block !important;)

Using This Filters But Would Like To Know Why Nano Sib Didnt Actually Work..& What Rules Can Be Used With Nano-sib Or Other Thing..Page Source Code Is Weird Too🥴

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 106
filterset (summary): 
  network: 90549
  cosmetic: 35581
  scriptlet: 21183
  html: 756
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4836-7, 50m
    IND-0: 11471-1, 50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33504-304, 50m
    ublock-badware: 4238-0, 50m
    ublock-privacy: 273-1, 50m
    ublock-abuse: 76-0, 50m
    ublock-unbreak: 1863-0, 50m
    ublock-quick-fixes: 430-0, 50m
    adguard-mobile: 8112-169, 50m
    easylist: 64018-20605, 50m
    easyprivacy: 30566-1713, 50m
    urlhaus-1: 7187-0, 50m
    plowe-0: 3674-3, 50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 956 ms
  maxAssetCacheWait: 395 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
something to be fixed here ?

**Comment by Yuki2718** [comment]
Please do not post question here. All user support are done by reddit forum whether you like or not. `techvybes.com##+js(nano-stb, -wait, 10000)` works perfectly fine and you have to use it correctly.

**Comment by Yuki2718** [comment]
Or [Discussions](https://github.com/uBlockOrigin/uAssets/discussions) or [General filter chit-chat](https://github.com/DandelionSprout/adfilt/issues/63)

**Comment by krystian3w** [comment]
If anybody write or repaste course how write scriptlet without wait for uAssets mainstream.
