### ISSUE TITLE
aaj tak issue

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#148]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
http://m.aajtak.in/video.jsp?id=888263

### Describe the issue

Go to above URL
Load the video, it will say error shown in screenshot "error loading media:file couldn't played"

### Screenshot(s)

![screenshot_2016-09-18-15-15-09](https://cloud.githubusercontent.com/assets/20338483/18614890/5b2d1ef2-7db5-11e6-902f-8caecd5f3dda.png)

### Versions

- Browser/version: Firefox for Android 48.0 running ublock origin
- uBlock Origin version: 1.9.6 and tested dev build 1.9.7b4

### Settings

- all default Settings+ adblock warning removal list+ anti adblock killer list

### Notes

Disabled Firefox inbuilt tracking protection still error occurs.
Disabling adblocker works

opera browser on android(w/o adblocker) able to play videos
![screenshot_2016-09-18-15-37-25](https://cloud.githubusercontent.com/assets/20338483/18614923/3f48d0d6-7db6-11e6-8abf-1f9cd8f1cf28.png)

List of sites where videos not played
http://abpnews.abplive.in/india-news/terror-attack-at-army-headquarters-in-jammu-and-kashmirs-uri-458459/
http://m.khabar.ibnlive.com/news/desh/jammu-and-kashmir-uri-sector-terrorist-attack-loc-514658.html
http://m.indiatoday.in/story/terror-attack-militants-army-headquarters-jandk/1/766962.html
http://m.businesstoday.in/video/budget-2016-health-insurance-up-to-rs-1-lakh-per-family/1/229716.html

**Comment by ghajini** [comment]
Can anyone help to fix situation
@gorhill
@mapx-

**Comment by Atavic** [comment]
For http://m.aajtak.in/ try to allow:
http://media2.intoday.in/aajtak/

For http://abpnews.abplive.in/ you can allow:
http://api.abplive.in/index.php/playmedia/

For http://m.indiatoday.in/ allow:
http://indiatoday.intoday.in/embed/

**Comment by gorhill** [comment]
For <http://abpnews.abplive.in/india-news/terror-attack-at-army-headquarters-in-jammu-and-kashmirs-uri-458459/>: video plays fine, it needs Flash though. It does not work without Flash, even after whitelisting the site.

**Comment by gorhill** [comment]
For <http://m.khabar.ibnlive.com/news/desh/jammu-and-kashmir-uri-sector-terrorist-attack-loc-514658.html>: I do not see a video player on that page.

**Comment by gorhill** [comment]
For <http://m.businesstoday.in/video/budget-2016-health-insurance-up-to-rs-1-lakh-per-family/1/229716.html>: I get a crossdomain error with HTML5 player. Works finr with Flash-based player.

**Comment by ghajini** [comment]
`https://aajtak.intoday.in/lite/story/madhya-pradesh-bhind-marriage-dilip-bride-vinita-sarpanch-1-1144054.html?utm_source=atwap_home`

***Firefox android***

- empty `amp` ads placeholders on page, takes so much space on page....

Filters-
aajtak.intoday.in##body > div.amp-ad:nth-of-type(1)
`aajtak.intoday.in###placeAds
`aajtak.intoday.in##.i-amphtml-unresolved.amp-unresolved.i-amphtml-layout-size-defined.i-amphtml-layout-responsive.amp-notbuilt.i-amphtml-notbuilt.i-amphtml-element > i-amphtml-sizer`
`aajtak.intoday.in##div.amp-ad:nth-of-type(3)`
`aajtak.intoday.in##.amp-ad-inner`

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5190
Like this issue exists here also

**Comment by mapx-** [comment]
Explain in this case what is wrongly blocked / hidden or still to be fixed, with screenshots etc

**Comment by ghajini** [comment]
URL=
`https://aajtak.intoday.in/lite/story/delhi-anaj-mandi-fire-update-accused-rihan-detained-by-police-1-1144092.html?utm_source=atwap_home`

Platform = firefox android stable, ublock origin 1.24.2

Problem= unfortunately site uses taboola to serve legit articles. ..taboola served legit articles are blocked....

STR=
Go to `https://aajtak.intoday.in/lite/story/delhi-anaj-mandi-fire-update-accused-rihan-detained-by-police-1-1144092.html?utm_source=atwap_home`
2. You will see taboola based legit articles blocked

**Comment by mapx-** [comment]
test
```
@@||cdn.ampproject.org/*/amp-ad-*.js$script,domain=aajtak.intoday.in
@@||taboola.com/*indiatoday$domain=ampproject.net
@@||trc.taboola.com/indiatoday
```

**Comment by ghajini** [comment]
No ads so far....
@ryanbr check for abp also

**Comment by ghajini** [comment]
High memory usage, anything possible to counter?

**Comment by mapx-** [comment]
it's heavy `ampproject` stuff, if you block something you'll break the site

**Comment by ghajini** [comment]
@mapx- , @okiehsch 
`https://aajtak.intoday.in/lite/story/priya-prakash-varrier-wink-video-viral-social-media-2020-begins-tmov-1-1150721.html#referrer=https://www.google.com&amp_tf=From%20%251$s?amp_js_v=a2&amp_gsa=1`

This issue is back https://github.com/uBlockOrigin/uAssets/issues/148#issuecomment-562973657

Filter responsible = from adguard mobile ads filter  `||imasdk.googleapis.com^`

Fix=

`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=noopjs,domain=ampproject.net`
