### ISSUE TITLE
mimaletadepeliculas.blogspot.com.ar [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1480]
URL(s) where the issue occurs

`http://mimaletadepeliculas.blogspot.com.ar/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by anewuser** [comment]
@mapx-  Blogger redirects users to different domains depending on their country. This blog may have users from different Spanish-speaking countries, who are redirected to `com.uy`, `com.mx` etc.

**Comment by mapx-** [comment]
yes, I know, an alternative could be:

```
@@||mimaletadepeliculas.blogspot.*^$generichide
mimaletadepeliculas.blogspot.*##[id*=ScriptRoot]
||resources.blogblog.com/*.png#$image,redirect=2x2-transparent.png
```
but .. I don't know why the second filter does not work.
@gorhill
