### ISSUE TITLE
pixelexperience.org: ads

### ISSUE THREAD

**Issue by cyberboh** [uBlockOrigin/uAssets#14801]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.pixelexperience.org/2022/09/september-update-android-13-beta-is-here/`
`https://download.pixelexperience.org/mars`

### Describe the issue

Ads still exist

### Screenshot(s)

![ads2](https://user-images.githubusercontent.com/99109969/189894113-3795ede0-aef1-49ec-845a-e8328475c2da.png)
![ads1](https://user-images.githubusercontent.com/99109969/189894119-51d365cf-5ff8-42ea-a688-5666cefc9d0e.png)

### uBlock Origin version

1.44.3b2

### Browser name and version

Google Chrome x64 105.0.5195.102

### Settings

[my-ublock-backup_2022-09-13_18.50.38.txt](https://github.com/uBlockOrigin/uAssets/files/9556785/my-ublock-backup_2022-09-13_18.50.38.txt)

**Comment by Yuki2718** [comment]
Make sure cosmetic filters are enabled on the site.

**Comment by cyberboh** [comment]
> Make sure cosmetic filters are enabled on the site.

Working now after disabled `CHN adguard filters https://github.com/AdguardTeam/AdguardFilters#adguard-filters`
Seems filters inside breakage other adblocker filter

**Comment by Yuki2718** [comment]
Yeah, it has `@@||pixelexperience.org^$generichide`. @cjx82630 Can you please check if the rule is still needed? If so, can add specific hiding rules?

**Comment by cjx82630** [comment]
It's to counter anti-adblock. Since the website is not in CN, removed it.
