### ISSUE TITLE
loglogin.i-ready.com: popups

### ISSUE THREAD

**Issue by M8M11** [uBlockOrigin/uAssets#14806]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://login.i-ready.com/student/dashboard/home`

### Category

popups

### Describe the issue

a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 83428
  cosmetic: 40650
  scriptlet: 17889
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63797-52, 1h.14m
    easyprivacy: 30569-1171, 1h.19m
    plowe-0: 3671-855, 11d.2h.3m
    ublock-abuse: 76-0, 11d.2h.1m
    ublock-badware: 4235-103, 1h.18m
    ublock-filters: 32697-128, 1h.17m
    ublock-privacy: 241-3, 11d.2h.2m
    ublock-quick-fixes: 434-2, 1h.12m
    ublock-unbreak: 1847-40, 1h.15m
    urlhaus-1: 6907-0, 1h.13m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10200 ms (selfie)
  maxAssetCacheWait: 4896 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    trackjs.com: 1
```
</details>

**Comment by mapx-** [comment]
Provide more details: what sort of popups ? => newsletter type or just clicking the page you get some malicious / other popups ?

Account required or do you get the "popups" on that login page ?
