### ISSUE TITLE
ziarulargesul.ro - anti f12, right click

### ISSUE THREAD

**Issue by sugarfreesweetener** [uBlockOrigin/uAssets#14810]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ziarulargesul.ro/`

### Describe the issue

I believe there was anti contextmenu anti right click etc on `https://ziarulargesul.ro/`

### uBlock Origin version

1.44.2

### Browser name and version

Firefox

### Settings

uBlock Origin's `uBlock filters - Annoyances` = enabled

### Notes

```
ziarulargesul.ro##+js(aopr, nocontext)
ziarulargesul.ro##+js(aopr, disableEnterKey)
```
any filter for making dragging work?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c8a0d616b043983cdb7f35d83598e99000c97393
