### ISSUE TITLE
obsolete rules/filter maintenance

### ISSUE THREAD

**Issue by jmjou** [uBlockOrigin/uAssets#14819]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
! https://github.com/NanoMeow/QuickReports/issues/4189
||trdiziizle1.com/player/vast.php$xhr,1p,redirect=noop.txt
```

---

```
dizirun.co,setfilmizlee.com##+js(aopw, puShown)
dizirun.co##+js(aopw, ilkPopup)
||setfilmizlee.com/gurme.js
```

---

```
||dizirun.co/test*$script,1p
||dizirun.co/img/1000x90.png
```

---

```
! https://www.reddit.com/r/uBlockOrigin/comments/uy6zl8/ads_started_show_up_on_top_of_video/
gggdrive.xyz##iframe[style]
*$frame,3p,domain=gggdrive.xyz
*.php$xhr,domain=gggdrive.xyz
*aHR$css,image,domain=gggdrive.xyz
?key=$frame,domain=dizipal254.com
||iamcdn.net/players/playhydraxs.min.js

```

---

`! izlemac10.net##+js(aopr, open)`

---

```
! https://www.reddit.com/r/uBlockOrigin/comments/niiytr/help_needed_filtering_wwwsporizle1pw/
@@||sporizle1.pw^$ghide
*$image,redirect-rule=1x1.gif,domain=sporizle1.pw
sporizle1.pw##+js(acis, $, 'body')
sporizle1.pw##+js(nosiif, reklam)
sporizle1.pw##+js(nowoif)
sporizle1.pw##+js(nostif, detectLoop)
sporizle1.pw##+js(noeval-if, devtoolsDetector)
||sporizle1.pw/inc/zcx/frame/
sporizle1.pw##[src="/cdn/img/728x90.png"]
sporizle1.pw##a[href="https://hdweb.pw"][target="_blank"]
```

---
---

The sites below are not dead, but they are already in the Adguard Turkish filter.

```
! https://github.com/uBlockOrigin/uAssets/issues/10631
tranimeizle.net##+js(nowoif)
```

```
! https://github.com/uBlockOrigin/uAssets/issues/13359
sezonlukdizi2.com##+js(aopr, puShown)
```

```
! https://github.com/NanoMeow/QuickReports/issues/2102
@@||tranimeizle.com^$ghide
tranimeizle.com##+js(acis, puShown, /doOpen|popundr/)
tranimeizle.com##+js(aopr, jsPopunder)
```

### Describe the issue

these are dead/obsolete rules and can be removed from the uBO filter.
also tr sites should be handled by adguard turkish, not uBO filters.

### uBlock Origin version

1.44.2

### Browser name and version

Firefox 104

### Settings

<details><summary>screenshot</summary>

![firefox-filtreler](https://user-images.githubusercontent.com/110184059/190113915-92a722df-5c7d-43c7-a052-9799b74bbba1.png)

</details>

**Comment by mapx-** [comment]
thanks
