### ISSUE TITLE
paramountplus.com: detection

### ISSUE THREAD

**Issue by Spitchcock** [uBlockOrigin/uAssets#14813]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.paramountplus.com/`

### Category

detection

### Describe the issue

Will not play video because it detected an adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 83429
  cosmetic: 40688
  scriptlet: 17893
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63817-52, 4m
    easyprivacy: 30569-1171, 4m
    plowe-0: 3674-860, 4m
    ublock-abuse: 76-0, 4m
    ublock-badware: 4245-103, 4m
    ublock-filters: 32720-129, 4m
    ublock-privacy: 245-1, 4m
    ublock-quick-fixes: 422-2, 4m
    ublock-unbreak: 1847-40, 4m
    urlhaus-1: 6907-0, 4m
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1142 ms
  maxAssetCacheWait: 533 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    ads-twitter.com: 1
    app.link: 6
    appboycdn.com: 1
    bing.com: 1
    cbsaavideo.com: 3
    cbsivideo.com: 4
    cedexis.com: 1
    demdex.net: 1
    facebook.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    impactradius-event.com: 1
    mtvnservices.com: 1
    ns1p.net: 4
    pinimg.com: 1
    qualtrics.com: 1
    sc-static.net: 1
    scorecardresearch.com: 2
    sentry.io: 3
    yahoo.com: 1
```
</details>

**Comment by mapx-** [comment]
needing subscription ?

I added today filters for `cbs.com`

```
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=cbs.com
@@||pubads.g.doubleclick.net/ondemand/dash/content/*/streams$xhr,domain=cbs.com
```

try similar filters for `paramountplus.com`

if does not work we'd need an account or a free video to test

**Comment by elissahuang** [comment]
hi, I have the same issue right now. I tried adding those filters except replacing cbs with paramountplus. this gets rid of the message 
![image](https://user-images.githubusercontent.com/18093673/190005090-447d948c-77f3-46c4-b35c-0eca782361d6.png)
but now the ads play.

**Comment by mapx-** [comment]
for now I'll add the filters as for cbs

**Comment by mapx-** [comment]
@elissahuang could you test this video with / without this filter:

`cbs.com##+js(json-prune, ads)`

**Comment by maraster9** [comment]
Getting the same issue, added the paramount plus filter, but still getting the ads. Is there any fix to get rid of the ads?

**Comment by Evenstar00** [comment]
I am getting this as well. Am I looking for something in the source to add to the filter? Any of this helpful?
`<html>
<body>


CBS.Registry.brand.name = 'PPLUS';
--
  | CBS.Registry.braze_safari_push_id = "web.com.cbs.safari";
  | CBS.Registry.brand_platform_desktop_id = "pplus_site_desktop";
  | CBS.Registry.braze_sdk_endpoint = "sdk.iad-03.braze.com";
  | CBS.Registry.braze_api_key = "8cb8412e-2475-416f-b1df-c03199764b1f";
  | CBS.Registry.facebook_app_id = "527890468593737";
  | CBS.Registry.google_client_id = "622419776613.apps.googleusercontent.com";
  | CBS.Registry.user_auth = true;
  | CBS.Registry.ssl = true;
  | CBS.Registry.host = "www.paramountplus.com";
  | CBS.Registry.imageHost = 'https://wwwimage-us.pplusstatic.com';
  | CBS.Registry.videoImageHost = 'https://thumbnails.cbsig.net';


</body>
</html>`

**Comment by sugarfreesweetener** [comment]
@mapx- @Yuki2718 https://github.com/AdguardTeam/AdguardFilters/issues/129658

**Comment by mapx-** [comment]
just AG fix for now impossible to do it for uBO

**Comment by mapx-** [comment]
How to block the ads cbs / paramountplus:

https://github.com/uBlockOrigin/uAssets/issues/14849#issuecomment-1248962943
