### ISSUE TITLE
gocmod.com: detection

### ISSUE THREAD

**Issue by furkankolsuz** [uBlockOrigin/uAssets#14816]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gocmod.com/`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 102
filterset (summary): 
  network: 85201
  cosmetic: 47140
  scriptlet: 18333
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 8722-13, 7h.33m
    easylist: 63817-69, 7h.32m
    easyprivacy: 30569-1176, 7h.31m
    plowe-0: 3673-859, 4d.14h.34m
    ublock-abuse: 76-0, 4d.14h.35m
    ublock-badware: 4245-103, 7h.30m
    ublock-filters: 32707-139, 7h.29m
    ublock-privacy: 245-1, 7h.28m
    ublock-quick-fixes: 423-2, 7h.27m
    ublock-unbreak: 1847-40, 7h.34m
    urlhaus-1: 6907-0, 7h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 407 ms (selfie)
  maxAssetCacheWait: 230 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    google.com: 1
    google.com.tr: 1
    googlesyndication.com: 11
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Vietnamese site => already fixed by the regional list (enable it) => `VIE: ABPVN List`
