### ISSUE TITLE
filecrypt.co: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#14817]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filecrypt.co/Container/22953CE68B.html`

### Category

breakage

### Describe the issue

When the "AdGuard Base" list is active, the captcha is not displayed.
(I have done all the tests before to check)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/190090096-11a25159-8417-4720-b72e-1f08620ba807.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 519883
  scriptlet: 37355
  html: 0
listset (total-discarded, last updated): 
    RUS-0: 42219-257, 1m
    adguard-generic: 69987-5714, never
    adguard-mobile: 8123-32, now
    adguard-spyware: 27304-1500, 1m
    adguard-spyware-url: 754-111, 1m
    curben-phishing: 88068-1, 1m
    curben-pup: 192-1, 1m
    fanboy-cookiemonster: 40982-113, 1m
    ublock-annoyances: 4811-53, 1m
  default: 
    FRA-0: 30591-63, 1m
    easylist: 69310-366, never
    easyprivacy: 30573-14382, 1m
    plowe-0: 3674-1023, 1m
    ublock-abuse: 76-2, 1m
    ublock-badware: 4245-106, 1m
    ublock-filters: 32719-416, 1m
    ublock-privacy: 245-44, 1m
    ublock-quick-fixes: 431-2, 1m
    ublock-unbreak: 1858-60, never
    urlhaus-1: 6901-1, 1m
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 606 ms (selfie)
  maxAssetCacheWait: 640 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Did you report the issue at adguard repository ?

for now add

`@@||filecrypt.co^$shide`

@AdamWr
@Yuki2718

**Comment by AdamWr** [comment]
I cannot reproduce it with AdGuard, so I suppose that it's related to this issue - https://github.com/uBlockOrigin/uBlock-issues/issues/2262
Adding:
```adblock
filecrypt.co#@?#form > .protection.online ul > li:not(.buttons):-abp-has(> div:not(.circle_captcha))
```
to `My filters` should fixes it.

**Comment by jordansworld** [comment]
cant open legit links. the below fixes that problem.tried each separate but guess both are required

@@||filecrypt.co/Link/$popunder
@@||filecrypt.co/index.php$popunder

**Comment by jordansworld** [comment]
captcha is broken by ||filecrypt.co/*.php^$1p

fix: @@||filecrypt.co/captcha/

issue url:

https://filecrypt.co/Container/D353C522D8.html

**Comment by jordansworld** [comment]
anti adblock here:

https://filecrypt.co/Container/22953CE68B.html

**Comment by stephenhawk8054** [comment]
The `popunder` filter is already disabled. I don't know how to reproduce the issue.
