### ISSUE TITLE
crockolinks.com, 1ink.cc, met.bz

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#1481]
### URL(s) where the issue occurs

1.  `http://crockolinks.com/YrMT6r`
2.  `http://1ink.cc/o0DTB`
3.  `https://met.bz/VfKivut1gt`

### Describe the issue

Since timer bypassing is added to uAssests, I was hoping if these sites could be bypassed altogether (since these don't require captcha solving); like adf.ly and linkshrink.net

**Comment by okiehsch** [comment]
> I was hoping if these sites could be bypassed altogether

That is not possible, with the currently available scriptlets.
I will add a filter for `1ink.cc` to boost the timer of that site.

**Comment by KiLL4FuNK** [comment]
Bad Request

https://met.bz/VfKivut1gt

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://met.bz/VfKivut1gt`
