### ISSUE TITLE
sports.ru: breakage

### ISSUE THREAD

**Issue by leosher** [uBlockOrigin/uAssets#14814]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sports.ru/football/`

### Category

breakage

### Describe the issue

Upper menu with the choices of different sports is broken with cosmetic filter. Turning this filter off returns the menu 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![upper menu appears with cosmetic filter off](https://user-images.githubusercontent.com/37189525/190011075-851c003f-0ff1-4b79-b64d-0c4eb5612f4a.png)

</details>
![no upper menu with Ublock ON](https://user-images.githubusercontent.com/37189525/190011104-4d23a965-987b-439c-a470-b1235e7e4cc9.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 102
filterset (summary): 
  network: 105683
  cosmetic: 80692
  scriptlet: 19569
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29979-74, 3d.14h.42m
  default: 
    user-filters: 3-0, never
    RUS-0: 42205-3628, 14h.15m
    easylist: 64340-237, 3d.14h.43m
    easyprivacy: 27513-240, 3d.14h.41m
    ublock-abuse: 76-1, 10d.20h.17m
    ublock-badware: 4232-99, 3d.14h.45m
    ublock-filters: 32623-160, 2d.23h.42m
    ublock-privacy: 253-0, 7d.3h.12m
    ublock-quick-fixes: 423-2, 14h.14m
    ublock-unbreak: 1851-41, 3d.14h.44m
    urlhaus-1: 7022-0, 14h.13m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 308 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    sports.ru: 3
    doubleclick.net: 2
    google-analytics.com: 2
    googletagmanager.com: 3
    googletagservices.com: 1
    yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
remove `AdGuard Russian filter` (`https://filters.adtidy.org/extension/ublock/filters/1.txt`), uBO is working fine with `RUS: RU AdList`

**Comment by Alex-302** [comment]
This is not our fail. uBO converts valid rule to invalid, which breaks the site:
`sports.ru#$?##branding-layout > div.page-layout:not(:has(> *)) { remove: true; }`
`sports.ru###branding-layout > div.page-layout:not():remove()`
It original rule should not applied, like in AdGuard.
