### ISSUE TITLE
[nsfw] shinchu.net: breakage

### ISSUE THREAD

**Issue by HirumaDaichi** [uBlockOrigin/uAssets#14820]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shinchu.net/backup/w/?get=UboRLdX`

### Category

breakage

### Describe the issue

I can login with disable ublock origin extension, but when the ublock enable my browser stuck at cloudflare.Help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-09-14-16-32-08-19_60683f88e2cbcfee82dd9c478fa24c2f](https://user-images.githubusercontent.com/111042667/190118146-479ffbe6-64da-472a-99a1-ee8a334977ee.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium Mobile: 93
filterset (summary): 
  network: 87836
  cosmetic: 45666
  scriptlet: 17907
  html: 0
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
  default: 
    user-filters: 91-0, never
    IDN-0: 9236-3, 2h.19m
    easylist: 63820-59, 2h.19m
    easyprivacy: 30572-1173, 2h.19m
    plowe-0: 3674-860, 2h.19m
    ublock-abuse: 76-0, 2h.19m
    ublock-badware: 4244-103, 2h.19m
    ublock-filters: 32822-158, 2h.19m
    ublock-privacy: 245-1, 2h.19m
    ublock-quick-fixes: 431-2, 2h.19m
    ublock-unbreak: 1852-41, 2h.19m
    urlhaus-1: 6901-0, 2h.19m
filterset (user): [array of 90 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  ignoreGenericCosmeticFilters: false
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 830 ms (selfie)
  maxAssetCacheWait: 307 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    shinchu.net: 4
```
</details>

**Comment by Yuki2718** [comment]
I don't get the cloudflare issue on Android, but the site says screen resolution is not compatible.

**Comment by HirumaDaichi** [comment]
> 1. `Chromium Mobile: 93`
>    Update your browser, it's old.
> 2. `Chromium Mobile:`
>    Kiwi Browser doesn't work well with uBlock Origin, install Firefox Mobile + uBlock Origin and test again.
> 3. `removed:  adguard-mobile: null`
> 
> You shouldn't remove AdGuard Mobile when using uBO on mobile.
> 
> 4. `modifiedUserSettings:    hyperlinkAuditingDisabled: false   prefetchingDisabled: false`
> 
> Why disable these useful features?
> 
> 5. `user-filters: 91-0`
>    Test without your custom filters.
> 
> > * [x]  I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules

Thank you for your advice I will test it
