### ISSUE TITLE
loawa.com: ads

### ISSUE THREAD

**Issue by Lynacchi** [uBlockOrigin/uAssets#14828]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://loawa.com/`

### Category

ads

### Describe the issue

banners with ad-shield

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://lynacchi.mekaku.de/vivaldi-2022-09-14-21-32-21.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 85551
  cosmetic: 44750
  scriptlet: 17889
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 34-0, never
    DEU-0: 5936-0, 2h.50m
    easylist: 64075-57, 2d.3h.58m
    easyprivacy: 30569-1181, 2d.3h.57m
    plowe-0: 3671-858, 5d.1h.59m
    ublock-abuse: 76-0, 5d.1h.58m
    ublock-badware: 4235-102, 2d.3h.56m
    ublock-filters: 32692-137, 2d.3h.55m
    ublock-privacy: 251-1, 5d.1h.57m
    ublock-quick-fixes: 436-2, 2h.48m
    ublock-unbreak: 1845-41, 2d.3h.54m
    urlhaus-1: 6907-0, 2h.49m
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 31 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 454 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cloudflareinsights.com: 1
    dable.io: 1
    doubleclick.net: 3
    googleadservices.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Adshield ads and tracking are hard to block and can’t be fully defused. To block Ad-Shield ads and tracking completely install [microShield](https://github.com/List-KR/microShield)
