### ISSUE TITLE
helvetia.com: breakage

### ISSUE THREAD

**Issue by CedricReichenbach** [uBlockOrigin/uAssets#14824]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.helvetia.com/ch/web/de/privatkunden/kontakt/schaden-melden.html`

### Category

breakage

### Describe the issue

Chatbot won't launch (clicking on "Jetzt melden" does nothing). Disabling uBlockOrigin and refreshing makes it work as expected.

From JS console:
`chatbotContainer is null!
(anonymous) @ clientlib-js.min.ac15ce6806b5cadfa69db78a66da8067.js:22`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1576321/190194611-8d4077f4-1699-4686-8f03-12706ca50acf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83643
  cosmetic: 41000
  scriptlet: 17889
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64101-52, 1d.18h.5m
    easyprivacy: 30569-1171, 1d.18h.4m
    plowe-0: 3671-856, 9d.17h.39m
    ublock-abuse: 76-0, 13d.20h.59m
    ublock-badware: 4235-102, 1d.18h.3m
    ublock-filters: 32698-125, 1d.18h.2m
    ublock-privacy: 241-3, 13d.20h.58m
    ublock-quick-fixes: 434-2, 1d.18h
    ublock-unbreak: 1845-40, 1d.18h.1m
    urlhaus-1: 7168-0, 1d.17h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1471 ms (selfie)
  maxAssetCacheWait: 406 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adobedtm.com: 5
```
</details>

**Comment by mapx-** [comment]
add

`@@||assets.adobedtm.com/*-source.min.js$script,domain=helvetia.com`

@ryanbr
