### ISSUE TITLE
[nsfw] xnxx.com: breakage

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14822]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.xnxx.com/`

### Category

breakage

### Describe the issue

Login doesn't work with ubo Enabled,if disabled login works

To login>go to any video click Download icon below>below that it would ask to create account or login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 106
filterset (summary): 
  network: 90425
  cosmetic: 35644
  scriptlet: 21202
  html: 756
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4842-7, 9h.13m
    IND-0: 11485-1, 9h.13m
  default: 
    user-filters: 0-0 never
    ublock-filters: 33531-305, 9h.13m
    ublock-badware: 4248-0, 9h.13m
    ublock-privacy: 267-1, 9h.13m
    ublock-abuse: 76-0, 9h.13m
    ublock-unbreak: 1865-0, 9h.13m
    ublock-quick-fixes: 432-0, 9h.13m
    adguard-mobile: 8123-169, 9h.14m
    easylist: 63820-20257, 9h.13m
    easyprivacy: 30572-1713, 9h.13m
    urlhaus-1: 6901-0, 9h.13m
    plowe-0: 3674-3, 9h.13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1447 ms
  maxAssetCacheWait: 382 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
working fine desktop / mobile on my end

**Comment by stephenhawk8054** [comment]
I can reproduce it when trying to sign up (clicking on sign up button after filling new account doesn't work). Looks like it's caused by

```adb
xnxx.com##+js(aopr, decodeURI)
```

but disabling it will cause popup when clicking on the thumbnails below each video.

@iSmokeMid69 Can you check if adding these works, and do they cause any breakages?

```adb
xnxx.com#@#+js(abort-on-property-read, decodeURI)
/js/static/header/sda/ppsuma*.js$script
```
