### ISSUE TITLE
examples.yourdictionary.com: ads

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14829]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://examples.yourdictionary.com/list-of-suffixes-and-suffix-examples.html`

### Category

ads

### Describe the issue

sticky header has space above where ad used to be

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/190249741-7484969f-f317-4f25-a4f8-4c3b7cc0c943.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 90983
  cosmetic: 93379
  scriptlet: 24127
  html: 755
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1947-0, 4h.11m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 4h.11m
    adguard-spyware-url: 755-110, 4h.11m
    block-lan: 43-0, 4h.11m
    adguard-annoyance: 59055-768, never
    ublock-annoyances: 4822-4, 4h.11m
  default: 
    user-filters: 25-0, never
    ublock-filters: 33432-36, 4h.11m
    ublock-badware: 4249-0, 4h.11m
    ublock-privacy: 267-2, 4h.11m
    ublock-abuse: 76-0, 4h.11m
    ublock-unbreak: 1863-0, 3m
    ublock-quick-fixes: 441-0, 4h.11m
    easylist: 63850-626, 4h.11m
    easyprivacy: 30575-1703, 4h.11m
    urlhaus-1: 6907-0, 4h.11m
    plowe-0: 3674-3, 4h.11m
filterset (user): [array of 25 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 417 ms
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    ip-api.com: 2
    quantserve.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
Test
`examples.yourdictionary.com##.header:style(top: 0 !important)`

**Comment by wavygecko** [comment]
@mapx- That appears to work for me 👍

**Comment by wavygecko** [comment]
Actually domain should be `yourdictionary.com` because it occurs on e.g., `https://www.yourdictionary.com/automated-test-framework` too
