### ISSUE TITLE
[nsfw] chan.sankakucomplex.com: detection

### ISSUE THREAD

**Issue by gwarpDN** [uBlockOrigin/uAssets#14832]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://chan.sankakucomplex.com/`

### Category

detection

### Describe the issue

the site cancels selete element overlay

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 103073
  cosmetic: 51450
  scriptlet: 17999
  html: 747
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 23h.48m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 30m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 5d.1h.13m
    CHN-0: 29182-111, 2d.20h.3m
  default: 
    user-filters: 160-3, never
    ublock-filters: 33391-53, 3d.4m
    ublock-badware: 4249-0, 1d.11h.49m
    ublock-privacy: 263-0, 10d.3h.11m
    ublock-abuse: 76-0, 10d.3h.12m
    ublock-unbreak: 1865-1, 2d.20h.1m
    easylist: 64031-988, 2d.20h
    easyprivacy: 30569-1703, 1d.11h.48m
    plowe-0: 3674-3, 3d.12h.48m
    urlhaus-1: 7879-0, 28m
    ublock-quick-fixes: 441-0, 29m
filterset (user): [array of 160 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
  removed: 
    no-large-media: behind-the-scene false
modifiedUserSettings: 
  collapseBlocked: false
  colorBlindFriendly: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 568 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    sankakucomplex.com: 1
    juicyads.com: 1
    otaserve.net: 3
```
</details>

**Comment by mapx-** [comment]
> the site cancels selete element overlay

Try again an explanation. 
Add a screenshot too and be sure you are using only uBO with **default settings** and no other blocking extension.

**Comment by Yuki2718** [comment]
If that measn that you can't use the picker, I can't reproduce.
