### ISSUE TITLE
cooking.nytimes.com: breakage

### ISSUE THREAD

**Issue by srikanth-viswanathan** [uBlockOrigin/uAssets#14839]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cooking.nytimes.com/`

### Category

breakage

### Describe the issue

When logged in on `https://cooking.nytimes.com/` and clicking "Your Grocery List", uBlock appears to prevent the associated modal window from opening. Disabling uBlock results in the modal opening.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2022-09-15 at 8 13 40 AM](https://user-images.githubusercontent.com/4712464/190441348-41bb6d87-b6f9-4ebd-91bc-1258c4196847.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83482
  cosmetic: 41023
  scriptlet: 17867
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 64281-51, 4d.20h.19m
    easyprivacy: 30556-1172, 4d.20h.23m
    plowe-0: 3671-853, 6d.37m
    ublock-abuse: 76-0, 6d.40m
    ublock-badware: 4222-101, 4d.20h.22m
    ublock-filters: 32628-122, 4d.20h.21m
    ublock-privacy: 251-1, 6d.39m
    ublock-quick-fixes: 423-2, 2d.1m
    ublock-unbreak: 1852-40, 4d.20h.20m
    urlhaus-1: 6907-0, 2d
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2680 ms (selfie)
  maxAssetCacheWait: 1921 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    nytimes.com: 2
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by krystian3w** [comment]
Test on Dev build?

I think copied AdGuard filter now works well:

https://github.com/uBlockOrigin/uAssets/blob/6b78f437aeedcee01df6c17e3630a63ea366b84c/filters/filters.txt#L2876-L2879

**Comment by krystian3w** [comment]
#14839

#816

#3708

**Comment by krystian3w** [comment]
@adamwr possible disable match pop-up for logged users?

**Comment by krystian3w** [comment]
Bad is old @Adamwr filter:

https://github.com/uBlockOrigin/uAssets/blob/6b78f437aeedcee01df6c17e3630a63ea366b84c/filters/filters.txt#L2876

I tested with account form recommended bug me not by @ghajini.

**Comment by krystian3w** [comment]
Also in recipes filter no longer match for guests.

So need copy latest or write new with AdGuard team (still possible check exist :X: in right corner).

**Comment by mapx-** [comment]
@srikanth-viswanathan update the filter lists and test now

**Comment by AdamWr** [comment]
@krystian3w Any special steps to reproduce it?
If I click on a `Your Grocery List` button at the top then modal window shows up correctly.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/190597471-5dded34d-2200-4aad-a3fb-62a72a8cf130.png)

</details>

**Comment by krystian3w** [comment]
Yes:

- needed is use filter from "2019"
- logon
- don't try open recipes, so don't go out form homepage (or back to homepage)
- click on button grocery, then filter match due on homepage is used `.nytc---modal-window---isShown` and without :x:

But in recipes the container has `[class*="modal_show_"]` (`_` instead `-` and compressed ID form "React" at end of almost classes).

**Comment by AdamWr** [comment]
Okay, I was able to reproduce it and I have modified a rule, so this popup shouldn't be blocked.

**Comment by krystian3w** [comment]
But you plan cover new pop-up on recipes with `[class*="modal_show_"]`?

**Comment by AdamWr** [comment]
I don't see any new popup.

**Comment by krystian3w** [comment]
Maybe needed is open homepage in incognito/private mode (Firefox 104)

And form homepage open recipe.

https://i.imgur.com/etfIoW7.png

But then needed id detected new name for grocery as second negation.

**Comment by srikanth-viswanathan** [comment]
I can confirm this solved the issue for me. Thanks for the quick fix!
