### ISSUE TITLE
driversed.com: breakage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#14835]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://driversed.com/login.aspx`

### Describe the issue

When attempting to log in using valid credentials, site gets stuck on the loading icon forever. (Invalid credentials will still display the correct message.)

### Screenshot(s)

![driversed](https://user-images.githubusercontent.com/54487525/190395790-4f2d659f-6077-44cd-a4cf-acf1092dc3bd.png)

### Notes

Adding `driversed.com https://cdn.segment.com/analytics.js/v1/ script allow` to "My Rules" seems to fix the issue.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 103
filterset (summary): 
  network: 84453
  cosmetic: 40693
  scriptlet: 17891
  html: 747
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33620-261, 1m
    ublock-badware: 4249-0, 1m
    ublock-privacy: 267-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1862-0, 1m
    ublock-quick-fixes: 449-0, 1m
    easylist: 63870-625, 1m
    easyprivacy: 30587-1702, 1m
    urlhaus-1: 7879-0, 1m
    plowe-0: 3674-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 236 ms (selfie)
  maxAssetCacheWait: 198 ms
```
</details>

**Comment by mapx-** [comment]
@ryanbr
