### ISSUE TITLE
vkprime.com: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#14847]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://vkprime.com/embed-q09g8ozv9rcs.html`

### Category

nuisance

### Describe the issue

Remove The Skip Ads Button At Bottom..Video Should Play After Clicking On Play

Another Link (Same Video)
`bestlinkz.xyz/hxplay.php?cid=tBqJdGWoPPuN`
Opens New Tab(Which Is Blocked In UBO But Still Opens A UBO Page About It Being Blocked)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox Mobile: 106
filterset (summary): 
  network: 91414
  cosmetic: 35656
  scriptlet: 21208
  html: 757
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4842-7, 1d.12h.20m
    IND-0: 11497-1, 11h.32m
  default: 
    user-filters: 833-17, never
    ublock-filters: 33531-305, 1d.12h.20m
    ublock-badware: 4248-0, 1d.12h.20m
    ublock-privacy: 267-1, 1d.12h.20m
    ublock-abuse: 76-0, 1d.12h.20m
    ublock-unbreak: 1865-0, 1d.12h.20m
    ublock-quick-fixes: 441-0, 11h.31m
    adguard-mobile: 8123-169, 1d.12h.21m
    easylist: 63820-20257, 1d.12h.20m
    easyprivacy: 30572-1713, 1d.12h.20m
    urlhaus-1: 7879-0, 11h.30m
    plowe-0: 3674-3, 1d.12h.20m
filterset (user): [array of 823 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 815 ms (selfie)
  maxAssetCacheWait: 558 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    vkprime.com: 2
    bidvol.com: 2
    googletagmanager.com: 1
    reyden-x.com: 2
    vidalak.com: 2
    yomeno.xyz: 2
```
</details>

**Comment by mapx-** [comment]
add

`vkprime.com##+js(nano-sib)`

then click skip ads

**Comment by mapx-** [comment]
if someone else could find a way:

`$('[id^="closeme2"]').click(function(event){ $('#adprimary').hide(); $('#over_main').hide(); jwplayer().play(); });`

I see the play() is enabled only if you click "skip ads"

**Comment by mapx-** [comment]
@iSmokeMid69 are you using some horrible keyboard (with those capital letters) ?
