### ISSUE TITLE
yahoo.com: ads

### ISSUE THREAD

**Issue by K-Stas** [uBlockOrigin/uAssets#14844]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.yahoo.com/` 

### Category

ads

### Describe the issue

- There is a  ad for amazon prime video that is taking up the ENTIRE PAGE on yahoo.com homepage.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 84452
  cosmetic: 40619
  scriptlet: 17885
  html: 747
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33404-35, 22m
    ublock-badware: 4249-0, 21m
    ublock-privacy: 267-0, 20m
    ublock-abuse: 76-0, 19m
    ublock-unbreak: 1865-0, 18m
    ublock-quick-fixes: 449-0, 17m
    easylist: 63819-625, 16m
    easyprivacy: 30588-1702, 15m
    urlhaus-1: 7835-0, 14m
    plowe-0: 3674-3, 13m
filterset (user): [empty]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  largeMediaSize: 11
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2560 ms
  maxAssetCacheWait: 1160 ms
popupPanel: 
  blocked: 31
  no-large-media: true
  no-popups: true
  blockedDetails: 
    yahoo.com: 16
    advertising.com: 2
    doubleclick.net: 1
    scorecardresearch.com: 2
    yimg.com: 10
```
</details>
![image](https://user-images.githubusercontent.com/64835690/190457695-63a2f39c-94cd-4fcb-945e-aaa3f2423398.png)

**Comment by mapx-** [comment]
add

`yahoo.com###HPSPON-ad`

@ryanbr
