### ISSUE TITLE
Block addotnet.com

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#14852]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://11165151.addotnet.com/redirect.html?l=https%3A%2F%2Fwww.apple.com%2Fitunes%2F` (etc)
Redirects to (samples):
(Music) `https://itunes.apple.com/subscribe?app=music&at=1001lLm9&itscg=30200&itsct=addotnet_music&ls=1`
(News) `https://news.apple.com/subscription?app=news&itsct=addotnet_news&itscg=30200&at=1001l35h8&campaign_id=aff_1001l35h8&mttnsubad=adnet&mttnrefid=913-11165151`

### Describe the issue

Addotnet.com tries to redirect you to Apple sites, such as Music, TV, Arcade, News, Podcasts, and Books. The links are affiliate links and they open the corresponding app and prompt you to subscribe to the plus version of these services.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 232548
  cosmetic: 218360
  scriptlet: 38667
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
    adguard-annoyance: 59032-83, 2d.2h.15m
    adguard-generic: 69968-501, 2d.2h.14m
    adguard-mobile: 8123-45, 2d.5h.47m
    adguard-social: 18488-882, 2d.2h.16m
    adguard-spyware: 27304-1541, 2d.2h.17m
    adguard-spyware-url: 754-1, 2d.2h.18m
    block-lan: 43-0, 11d.30m
    curben-phishing: 94547-0, 18h.43m
    curben-pup: 192-1, 18h.44m
    dpollock-0: 11387-250, now
    fanboy-annoyance: 80447-4743, 1d.17h.25m
    fanboy-cookiemonster: 40943-40943, 1d.17h.26m
    fanboy-social: 23356-23356, 2d.2h.20m
    fanboy-thirdparty_social: 69-21, 1d.17h.27m
    ublock-annoyances: 4805-240, 2d.2h.19m
  default: 
    user-filters: 15-0, never
    easylist: 63817-1482, 2d.2h.12m
    easyprivacy: 30569-14265, 2d.2h.11m
    plowe-0: 3673-1376, 6d.18h.55m
    ublock-abuse: 76-0, 6d.18h.54m
    ublock-badware: 4245-335, 2d.2h.10m
    ublock-filters: 32707-3986, 2d.2h.9m
    ublock-privacy: 251-48, 6d.18h.53m
    ublock-quick-fixes: 436-14, 3h.7m
    ublock-unbreak: 1847-105, 2d.2h.8m
    urlhaus-1: 6907-1, 18h.45m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9186 ms (selfie)
  maxAssetCacheWait: 4127 ms
```
</details>

**Comment by sugarfreesweetener** [comment]
example of it being used? like, on a website

**Comment by mapx-** [comment]
provide complete steps to reproduce the issue

**Comment by SilkArt** [comment]
Visited http://atnt.com, got redirected to https://11165151.addotnet.com/redirect.html?l=https%3A%2F%2Fwww.apple.com%2Fitunes%2F, then got redireted to https://www.apple.com/itunes. Sometimes it may redirect to other Apple Services via Affiliate Links.

**Comment by mapx-** [comment]
`http://atnt.com` => scam / malicious stuff
