### ISSUE TITLE
scammer.info: ads

### ISSUE THREAD

**Issue by hKQwHW** [uBlockOrigin/uAssets#14850]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://scammer.info/`

### Category

ads

### Describe the issue

A few issues:

First, these ads are still loaded onto the page:

- `creepy.link/upload/thundertechxyzadsi.jpg`
- `creepy.link/upload/KyberAd.jpg`

Second, this fingerprinter should be blocked:

- `scammer.info/plugins/discourse-fingerprint/javascripts/fp.js`
- `scammer.info/assets/plugins/discourse-fingerprint-261a4fa710c5c80ea9bc4fed5b78581a7ab84b6740c8dacc7af7f627801c1bef.js`

I think it may be a good to idea to block any JS file that has discourse-fingerprint in the name, and also block `plugins/discourse-fingerprint/javascripts/fp.js`

The URL
`scammer.info/assets/plugins/discourse-adplugin-fb892cd6b2883f1673019377956aa97e21d44bd263861467c1a29c034664bdd8.js` 
seems to be used to load ads onto the site. It may be good to block JS files that have discourse-adplugin in the name.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 232347
  cosmetic: 202449
  scriptlet: 38707
  html: 755
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 70038-5410, 1d.24m
    adguard-mobile: 8123-190, 1d.25m
    adguard-spyware: 27309-1724, 1d.26m
    adguard-spyware-url: 755-2, 1d.27m
    block-lan: 43-0, 9d.1h.53m
    curben-phishing: 93953-8, 3m
    curben-pup: 192-0, 3m
    adguard-annoyance: 59052-4270, 1d.28m
    fanboy-annoyance: 80543-41239, 3m
    fanboy-cookiemonster: 41033-135, 3m
    ublock-annoyances: 4820-4, 1d.29m
    dpollock-0: 11387-482, 3m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33433-68, 1d.23m
    ublock-badware: 4249-0, 1d.22m
    ublock-privacy: 273-0, 9d.1h.52m
    ublock-abuse: 76-0, 9d.1h.52m
    ublock-unbreak: 1860-1, 1d.21m
    ublock-quick-fixes: 449-0, 3m
    easylist: 63850-992, 1d.20m
    easyprivacy: 30573-14524, 1d.19m
    urlhaus-1: 7835-0, 3m
    plowe-0: 3671-3, 9d.1h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3383 ms
  maxAssetCacheWait: 1700 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    analytically.net: 1
    cloudflareinsights.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by hKQwHW** [comment]
This is the filter I use for this:

```
creepy.link/upload/thundertechxyzadsi.jpg$image
creepy.link/upload/KyberAd.jpg$image
plugins/discourse-fingerprint/javascripts/fp.js
assets/plugins/discourse-fingerprint*.js
stylesheets/discourse-fingerprint*.css*
assets/plugins/discourse-adplugin*.js
stylesheets/discourse-adplugin*.css
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Yuki2718** [comment]
@ryanbr @Khrin `/discourse-fingerprint_` only blocks css and misses `https://scammer.info/assets/plugins/discourse-fingerprint-` script.

**Comment by hKQwHW** [comment]
Yes, remove the `_` or use this filter:
```adb
assets/plugins/discourse-fingerprint*.js
stylesheets/discourse-fingerprint*.css*
```

**Comment by Yuki2718** [comment]
In this case `/discourse-fingerprint-` (no much sense in blocking css) or `/discourse-fingerprint` is suffice. Better to avoid unnecessary wildcard as it leads to slower processing. In particular if a wildcard is adjacent to words, it prevents tokenization too: `https://github.com/uBlockOrigin/uBlock-issues/issues/954#issuecomment-602041890`.

**Comment by hKQwHW** [comment]
That makes sense

**Comment by hKQwHW** [comment]
Surprised this has gone unnoticed for so long. This is in my Tor Browser when I disable uBlock:
![Screenshot from 2022-09-16 23-08-12](https://user-images.githubusercontent.com/98493235/190843224-a059d480-6d9b-4841-9463-6471368ca4d2.png)

**Comment by Handoff2901** [comment]
> In this case `/discourse-fingerprint-` (no much sense in blocking css) or `/discourse-fingerprint` is suffice. Better to avoid unnecessary wildcard as it leads to slower processing. In particular if a wildcard is adjacent to words, it prevents tokenization too: `https://github.com/uBlockOrigin/uBlock-issues/issues/954#issuecomment-602041890`.

This is still not addressed.

Also, there is a point in blocking CSS: there is a slight bit of CSS used for the fingerprinting and ad plugins - in the case of the fingerpinter, for the admin dashboard to view fingerprints, and for the ad plugin, to display ads to the end-user.

Blocking the CSS will result in less lasted bandwidth from loading remnants of tracking code.

**Comment by Handoff2901** [comment]
@mapx- should not have been closed due to unaddressed problems.

**Comment by mapx-** [comment]
meaning we should block 
`https://scammer.info/stylesheets/discourse-adplugin_9ce9879d3f8a179efea0102229f6f8eb166424fc.css?__ws=scammer.info`


`/discourse-adplugin`

?

**Comment by Yuki2718** [comment]
`/discourse-fingerprint` or `/discourse-adplugin` can be a part of title of any blog (false positive) so in that case I prefer  `/plugins/discourse-fingerprint`, `/stylesheets/discourse-fingerprint`

**Comment by Handoff2901** [comment]
> `/discourse-fingerprint` can be a part of title of any blog (false positive) so in that case I prefer `/plugins/discourse-fingerprint`, `/stylesheets/discourse-fingerprint`

Good idea
