### ISSUE TITLE
the-voice-of-germany.at: detection

### ISSUE THREAD

**Issue by Paollllo** [uBlockOrigin/uAssets#14863]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.the-voice-of-germany.at/`

### Category

detection

### Describe the issue

black screen, only sound

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 96
filterset (summary): 
  network: 85679
  cosmetic: 44409
  scriptlet: 17894
  html: 747
listset (total-discarded, last updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 33426-33, 1d.23h.11m
    ublock-badware: 4249-1, 22h.23m
    ublock-privacy: 267-0, 11h.15m
    ublock-abuse: 76-0, 2h.55m
    ublock-unbreak: 1863-13, 22h.24m
    easylist: 63850-254, 1d.16h.55m
    easyprivacy: 30574-1729, 1d.23h.12m
    urlhaus-1: 6917-0, 1h.16m
    plowe-0: 3674-344, 2h.54m
    DEU-0: 5938-19, 1h.15m
    ublock-quick-fixes: 441-1, 1h.17m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 19 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 176 ms (selfie)
  maxAssetCacheWait: 70 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    sqrt-5041.de: 1
```
</details>

**Comment by mapx-** [comment]
> black screen, only sound

No such issue on my end

**Comment by Paollllo** [comment]
Screenshot
https://i.postimg.cc/kMfYk49m/Screenshot-2022-09-16-at-12-33-49-The-Voice-of-Germany-Ganze-Folgen.png

**Comment by mapx-** [comment]
The commit above should have fixed the video ads.
Update the filter lists, disable any other blocking addon and test again.

**Comment by Paollllo** [comment]
It seems to be working fine. Thank you for your time
