### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by EmptyAndLost** [uBlockOrigin/uAssets#14861]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.amazon.com/gp/video/detail/amzn1.dv.gti.3501da49-4bf8-47c6-91d9-1e14e17cdf80?ref=imdb_web&autoplay=1&ref_=imdbref_tt_wbr_fdv&tag=imdbtag_tt_wbr_fdv-20`

### Category

ads

### Describe the issue

So whenever I attempt to watch any Freevee shows--in this particular instance, Judy Justice--ads are not blocked at all. I turned off all my custom filters list and everything; the issue still persists. I cannot provide a screenshot as Freevee blocks any attempts to get a screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83463
  cosmetic: 40446
  scriptlet: 17900
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-1, never
    easylist: 63631-52, 9m
    easyprivacy: 30591-1171, 9m
    plowe-0: 3674-860, 9m
    ublock-abuse: 76-0, 9m
    ublock-badware: 4200-105, 9m
    ublock-filters: 32893-110, 9m
    ublock-privacy: 245-1, 9m
    ublock-quick-fixes: 444-227, 9m
    ublock-unbreak: 1852-42, 9m
    urlhaus-1: 6917-0, 9m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 26 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1343 ms
  maxAssetCacheWait: 737 ms
popupPanel: 
  blocked: 176
  no-cosmetic-filtering: true
  blockedDetails: 
    amazon.com: 175
    amazon-adsystem.com: 1
```
</details>

**Comment by mapx-** [comment]
`&deviceAdInsertionTypeOverride=SSAI`

it seems to be SSAI

https://github.com/uBlockOrigin/uAssets/issues/1905
