### ISSUE TITLE
my.hrw.com: breakage

### ISSUE THREAD

**Issue by IMMORTALSCAR17** [uBlockOrigin/uAssets#14866]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.hrw.com/dashboard/home`

### Category

breakage

### Describe the issue

It is the website for which i get my textbook from, whenever i have you ad blocker enabled, it blocks the website from showing anything related to the website on the page,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot-1](https://user-images.githubusercontent.com/78977670/190664728-ada3d590-aada-45fa-b2e8-748af87c37d4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 84441
  cosmetic: 40614
  scriptlet: 17885
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63811-52, 23h.37m
    easyprivacy: 30588-1171, 23h.36m
    plowe-0: 3674-860, 12h.27m
    ublock-abuse: 76-0, 23h.33m
    ublock-badware: 4245-105, 23h.31m
    ublock-filters: 32697-131, 23h.30m
    ublock-privacy: 245-1, 23h.29m
    ublock-quick-fixes: 436-2, 23h.28m
    ublock-unbreak: 1852-41, 23h.27m
    urlhaus-1: 7835-0, 23h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 168 ms (selfie)
  maxAssetCacheWait: 99 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    hrw.com: 1
    adobedtm.com: 1
```
</details>

**Comment by mapx-** [comment]
Don't use any other blocking extension.
if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced

still in trouble:

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
