### ISSUE TITLE
msds.open.ac.uk: breakage

### ISSUE THREAD

**Issue by soapforachange** [uBlockOrigin/uAssets#14865]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://msds.open.ac.uk/signon/SAMS001_CDC.aspx?nsh=2&URL=https://msds.open.ac.uk/signon/SAMS001_CDC.aspx?nsh=2&URL=https://msds.open.ac.uk/signon/SAMS001_CDC.aspx?URL=https://msds.open.ac.uk/students/?ONEML=ac03u&MEDIA=ac03uou_eml495`

### Category

breakage

### Describe the issue

Page not loading properly, and never loads the sign in parts of the screen, so we can never sign in

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 104
filterset (summary): 
  network: 85692
  cosmetic: 44189
  scriptlet: 17891
  html: 747
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33625-33, 23m
    ublock-badware: 4204-1, 22m
    ublock-privacy: 267-0, 21m
    ublock-abuse: 76-0, 20m
    ublock-unbreak: 1863-0, 19m
    easylist: 63692-268, 18m
    easyprivacy: 30592-1199, 17m
    urlhaus-1: 6917-0, 16m
    plowe-0: 3674-863, 15m
    DEU-0: 5938-29, 27m
    ublock-quick-fixes: 449-227, 28m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 272 ms (selfie)
  maxAssetCacheWait: 308 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adobedtm.com: 1
    demdex.net: 2
    googletagmanager.com: 1
    omtrdc.net: 1
    optimizely.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

`@@||assets.adobedtm.com/*-source.min.js$script,domain=msds.open.ac.uk`

**Comment by soapforachange** [comment]
Hello team,

Still not working unfortunately. This is an academic site for a University,
so it isn't clear why there would be problems with Github operating on it.
Still not able to see the login section, so still cannot use the website on
the PC using Github.

Can you please help?

**Comment by soapforachange** [comment]
Thanks very much
I've tried that following the instructions, and the site is still not
working properly, so cannot be used with Github

Could you please take a look?

**Comment by stephenhawk8054** [comment]
I can sign in to the page normally

![image](https://user-images.githubusercontent.com/66517106/191227213-8b9b3ac3-04eb-4a41-997f-b528a7bb5b54.png)

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by soapforachange** [comment]
Thank you for checking, and the pic helps to see what you see Here's a pic
of what I see, and it never changes to offer the login screen, so there's
no way to login:

[image: image.png]

**Comment by soapforachange** [comment]
![image](https://user-images.githubusercontent.com/113689652/191229087-4b507590-d301-406a-b4d0-88f0c1eff632.png)

**Comment by soapforachange** [comment]
Sorry about that Have uploaded it direct in Github

**Comment by stephenhawk8054** [comment]
> Check if you are using any:
> - Custom filters,
> - Other extensions,
> - Browser's built-in blocker,
> - DNS blocking methods,
> - Blocking softwares outside browser,
> - OS' hosts file to block domains.

---

Here's a test account for others (email - pass)

```
SarahCol.ms281.9.89@gmail.com - zxZX12!@
```
