### ISSUE TITLE
ko.strikeout.cc: detection

### ISSUE THREAD

**Issue by billward1** [uBlockOrigin/uAssets#14879]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ko.strikeout.cc/`

### Category

detection

### Describe the issue

The website can now detect uBlock Origin and does allow streams to play.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.gyazo.com/bd9e1e30276a26028c87b7c862e64e9b.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83690
  cosmetic: 40483
  scriptlet: 17913
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63775-52, 17m
    easyprivacy: 30595-1171, 16m
    plowe-0: 3672-861, 15m
    ublock-abuse: 76-0, 13m
    ublock-badware: 4200-105, 11m
    ublock-filters: 32938-104, 10m
    ublock-privacy: 245-1, 9m
    ublock-quick-fixes: 440-227, 8m
    ublock-unbreak: 1854-42, 7m
    urlhaus-1: 7010-0, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 950 ms
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by billward1** [comment]
Why was this closed? The issue has not been fixed

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again? The video appears for me:

![image](https://user-images.githubusercontent.com/66517106/190874523-1f400921-3aa1-4760-8bc8-c476fc196275.png)

**Comment by billward1** [comment]
Oh.. I tried to do that before I made the report but I must not have let it finish updating. It works now.. thank you and my apologies.

**Comment by stephenhawk8054** [comment]
No problem. The issue is fixed in https://github.com/uBlockOrigin/uAssets/commit/79c8a6b921ffbd08a93ef397bb07979452b25623, that's why you need to force update the filter lists again to make it work.
