### ISSUE TITLE
unrealengine.com: breakage

### ISSUE THREAD

**Issue by boristsr** [uBlockOrigin/uAssets#14878]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.unrealengine.com/en-US`

### Category

breakage

### Describe the issue

Can't login or out of the website with ublock enabled.
Looking at the logger it appears it may be related to this URL being blocked:
https://www.unrealengine.com/id/api/analytics

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 88161
  cosmetic: 79403
  scriptlet: 19538
  html: 747
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/google_duckduckgo/global.txt: 4228-7, 19h.56m
    fanboy-cookiemonster: 40943-102, 2d.22h.31m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33609-261, 1d.20h.5m
    ublock-badware: 4249-0, 1d.20h.4m
    ublock-privacy: 267-0, 3d.2h.33m
    ublock-abuse: 76-0, 3d.2h.32m
    ublock-unbreak: 1863-0, 1d.20h.3m
    easylist: 63860-638, 1d.20h.2m
    easyprivacy: 30585-1702, 1d.20h.1m
    urlhaus-1: 6917-0, 19h.54m
    plowe-0: 3674-3, 2d.6h.27m
    ublock-quick-fixes: 449-0, 19h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1001 ms (selfie)
  maxAssetCacheWait: 665 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    unrealengine.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check if adding this works?

```adb
unrealengine.com##+js(no-xhr-if, /api/analytics)
```

**Comment by boristsr** [comment]
I won't be able to check my desktop for a few hours, but I did confirm this resolved the issue on the Firefox mobile version of ublock.
