### ISSUE TITLE
divxfilmeonline.net

### ISSUE THREAD

**Issue by mortyam** [uBlockOrigin/uAssets#14870]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://divxfilmeonline.net/the-brave-ones-sezonul-1-episodul-1/`

### Describe the issue

On the website page, when I click on "play video" button, pop-ups appear and continue to appear randon even if I click on empty spaces.

### uBlock Origin version

1.44.2

### Browser name and version

Firefox 104

### Settings

Default settings

**Comment by ghost** [comment]
I'm also having pop-ups that try to open on 
`https://divxfilmeonline.tv/film/home-alone-1990-online-subtitrat/`

**Comment by playonevideo** [comment]
On `https://divxfilmeonlinehd.net/film/beauty-and-the-beast-1991-online-subtitrat/` click the play button, select "Vidmoly" above the player, then click play again. A popup tries to open:

<img width="924" height="615" alt="Image" src="https://github.com/user-attachments/assets/d1d5fc6a-5a09-4bd7-9d55-c728fd992b95" />
