### ISSUE TITLE
moviesjoy.to: ads

### ISSUE THREAD

**Issue by kingjnl1** [uBlockOrigin/uAssets#14889]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://moviesjoy.to/watch-tv/legacies-39525.5536276`

### Category

ads

### Describe the issue

A Pop-Up opens over the video player whenever you pause a running video. It is flashing pictures of movie covers for me and links too `https://hdtoday.tv/`  
It isn't recognised as a Pop-Up by Firefox.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 104731
  cosmetic: 84976
  scriptlet: 30738
  html: 747
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 69897-5032, 15m
    adguard-mobile: 8122-155, 15m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33602-284, 19h.21m
    ublock-badware: 4249-0, 19h.20m
    ublock-privacy: 267-0, 18h.59m
    ublock-abuse: 76-0, 18h.58m
    ublock-unbreak: 1865-0, 18h.57m
    ublock-quick-fixes: 450-0, 18h.56m
    easylist: 63719-747, 18h.55m
    easyprivacy: 30593-1722, 18h.53m
    urlhaus-1: 6888-0, 18h.52m
    plowe-0: 3672-3, 18h.51m
    DEU-0: 5940-2, 19h.26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 497 ms (selfie)
  maxAssetCacheWait: 517 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    addthis.com: 1
    carvyre.com: 1
    cesurasfratchy.com: 2
    ckwlurries.com: 2
    googletagmanager.com: 2
    jwpltx.com: 1
    mgbid.net: 1
```
</details>

**Comment by mapx-** [comment]
test

```
moviesjoy.to##.premodal.modal
moviesjoy.to##.show.modal-backdrop
```
