### ISSUE TITLE
smog.moja-ostroleka.pl: breakage

### ISSUE THREAD

**Issue by Qrzysio** [uBlockOrigin/uAssets#14891]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://smog.moja-ostroleka.pl/`

### Category

breakage

### Describe the issue

The website fetches a JSON file (https://smog.moja-ostroleka.pl/mapa/sensorsData.json) which is used for displaying some spots on a map. Unfortunately, this extension block it. Checked in Firefox (newest version).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/13356480/190866273-a86e2448-09c0-46b0-bb96-442e8f60bb09.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 84893
  cosmetic: 48048
  scriptlet: 18107
  html: 758
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    POL-0: 7857-25, 20h.41m
    POL-2: 1279-12, 4h.52m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33422-74, 1d.22h.59m
    ublock-badware: 4249-0, 1d.22h.58m
    ublock-privacy: 267-0, 1d.6h.4m
    ublock-abuse: 76-0, 1d.6h.3m
    ublock-unbreak: 1860-0, 1d.22h.56m
    easylist: 63819-642, 1d.22h.55m
    easyprivacy: 30588-1697, 1d.22h.54m
    plowe-0: 3671-3, 10d.18h.59m
    urlhaus-1: 6888-0, 20h.42m
    ublock-quick-fixes: 445-0, 20h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 206 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 599 ms (selfie)
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    moja-ostroleka.pl: 1
    gemius.pl: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by krystian3w** [comment]
@majkiit / @olegwukr

**Comment by Qrzysio** [comment]
Unfortunately, this issue has not been resolved.

**Comment by gwarser** [comment]
https://github.com/easylist/easylist/commit/c706ce748d6b2de6005d9097dfba1b7c2d442110 "cleanup"
