### ISSUE TITLE
historyofyesterday.com (AdBlocker detection)

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#14895]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://historyofyesterday.com/the-ancient-computer-that-shouldnt-exist/`

### Describe the issue

AdBlocker Detected

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29574622/190876739-c3f6a024-5667-4d3d-aa2a-90b143056c2c.png)

### uBlock Origin version

1.44.2

### Browser name and version

Microsoft Edge 105.0.1343.42

### Settings

Default filter + Adguard Annoyance, Adguard Social Media filter

**Comment by sugarfreesweetener** [comment]
Any other blocker (ad blocker, built-in blocker, DNS level blocker, `hosts` file)?

**Comment by SeriousHoax** [comment]
> Any other blocker (including ad blocker, built-in blocker, DNS level blocker, `hosts` file)?

I use NextDNS with Adguard DNS & OISD filter but I also tested on Firefox with Cloudflare DNS and Firefox's tracking protection turned off but still see this.
Can you not reproduce it on your system?

**Comment by sugarfreesweetener** [comment]
I reproduced with AdGuard add-on

https://github.com/AdguardTeam/AdguardFilters/issues/130009#issuecomment-1250143776

**Comment by SeriousHoax** [comment]
> I reproduced with AdGuard add-on
> 
> https://github.com/AdguardTeam/AdguardFilters/issues/130009#issuecomment-1250143776

I see. Maybe some filter issue on my end. I'm not on my PC at the moment. I'll check again tomorrow after purging cache and let you know. 
Keep the issue open for now just in case.

**Comment by stephenhawk8054** [comment]
I can't reproduce it on my end. Are you using any DNS outside browser?

**Comment by SeriousHoax** [comment]
> I can't reproduce it on my end. Are you using any DNS outside browser?
Everything is working fine on my end now. Closing the issue.
