### ISSUE TITLE
wired.com: nuisance

### ISSUE THREAD

**Issue by Lallivaraani** [uBlockOrigin/uAssets#14894]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wired.com/story/uber-hack-mfa-phishing/`

### Category

nuisance

### Describe the issue

Overlay ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.3b7
Chromium Mobile: 96
filterset (summary): 
  network: 333535
  cosmetic: 312877
  scriptlet: 42152
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist-downloads.adblockplus.org/easylist-cookie.txt: 0-0, never
    https://filters.adtidy.org/windows/filters/18.txt: 22097-1530, 1d.2h.22m
    https://filters.adtidy.org/windows/filters/22.txt: 1137-23, 1d.1h.9m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyingBannersAndOverlays.txt: 868-193, 10m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt: 39-13, 10m
    https://raw.githubusercontent.com/LordBadmintonofYorkshire/Overlay-Blocker/master/blocklist.txt: 50-0, 10m
    https://raw.githubusercontent.com/acnapyx/paywall-remover/master/paywall-remover-list.txt: 40-15, never
    https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt: 0-0, never
    https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/annoyances/Finland_annoyances.txt: 181-16, 1d.2h.18m
    https://raw.githubusercontent.com/mistalaba/popover-blocklist/master/blocklist.txt: 26-0, 9m
    https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt: 1260-729, 1d.2h.22m
    https://raw.githubusercontent.com/soteria-nou/domain-list/master/widgets.txt: 405-2, 1d.1h.9m
    https://raw.githubusercontent.com/wiltteri/subscriptions/master/wiltteri-reborn.txt: 169-38, 1d.2h.23m
    https://raw.githubusercontent.com/wiltteri/subscriptions/master/wiltteri.txt: 4188-169, 1d.2h.23m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt: 27193-11, 1d.2h.20m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/generic_filters.txt: 2290-1996, 1d.2h.20m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/modal_filters.txt: 3834-41, 1d.2h.20m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/newsletter_filters.txt: 2024-5, 1d.1h.9m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-35652, 1d.2h.20m
    https://www.eff.org/files/cookieblocklist.txt: 552-0, 1d.2h.22m
    [49 lists not shown]: [too many]
  default: 
    user-filters: 161-27, never
    adguard-mobile: 8124-171, 1d.2h.34m
    easylist: 63719-21431, 1d.2h.31m
    easyprivacy: 30593-14638, 1d.2h.30m
    plowe-0: 3672-1417, 1d.2h.29m
    ublock-abuse: 76-2, 1d.2h.27m
    ublock-badware: 4199-377, 1d.2h.27m
    ublock-filters: 33001-4532, 1d.2h.27m
    ublock-privacy: 245-50, 1d.2h.27m
    ublock-quick-fixes: 422-239, 21m
    ublock-unbreak: 1857-137, 1d.2h.27m
    urlhaus-1: 6809-1, 20m
filterset (user): [array of 162 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5011 ms
  maxAssetCacheWait: 4503 ms
popupPanel: 
  blocked: 19
  no-cosmetic-filtering: true
  no-remote-fonts: true
  blockedDetails: 
    wired.com: 18
    cnevids.com: 1
```
</details>

**Comment by krystian3w** [comment]
No reproduced.

**Comment by sugarfreesweetener** [comment]
> ```yaml
>   no-cosmetic-filtering: true
> ```

![image](https://user-images.githubusercontent.com/113248817/190876046-d0b00f90-ffe4-4694-9e07-a0bcb8ce2607.png)

**Comment by mapx-** [comment]
@Lallivaraani 

if the setting indicated in red is ON just unselect it

![image](https://user-images.githubusercontent.com/10303732/190876646-373e4477-1bd6-463d-a57b-479f3a7b97fe.png)

**Comment by Lallivaraani** [comment]
True, stupid me. Pebcak problem.
