### ISSUE TITLE
crewus.net: detection

### ISSUE THREAD

**Issue by ngibuljago** [uBlockOrigin/uAssets#14892]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crewus.net/adblock.html`

### Category

detection

### Describe the issue

The web page detects uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 103
filterset (summary): 
  network: 99011
  cosmetic: 74828
  scriptlet: 17896
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 8h.34m
    https://filters.adavoid.org/ultimate-ad-filter.txt: 116736-1095, 8h.33m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8h.35m
  default: 
    user-filters: 0-0, never
    easylist: 63692-63639, 1d.6h
    easyprivacy: 30592-1286, 1d.5h.59m
    plowe-0: 3671-870, 10d.2h.33m
    ublock-abuse: 76-0, 10d.2h.31m
    ublock-badware: 4245-335, 1d.5h.58m
    ublock-filters: 32917-1825, 1d.5h.57m
    ublock-privacy: 251-1, 10d.2h.27m
    ublock-quick-fixes: 422-239, 33m
    ublock-unbreak: 1850-80, 1d.5h.56m
    urlhaus-1: 6809-0, 31m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 973 ms (selfie)
  maxAssetCacheWait: 606 ms
popupPanel: 
  blocked: 0
  no-large-media: true
```
</details>

**Comment by mapx-** [comment]
Did you visit directly `https://crewus.net` or did you land there being redirected from another page ?

**Comment by stephenhawk8054** [comment]
It was fixed yesterday: https://github.com/uBlockOrigin/uAssets/commit/a7d082b5cbf33f240b032866202e9a5b748a58d1

Can you force update the filter lists and test again?

**Comment by krystian3w** [comment]
fallback:

`||crewus.net/adblock.html$doc,domain=~your-opened-link-was-inccorect.*`
