### ISSUE TITLE
topcryptoz.net: detection

### ISSUE THREAD

**Issue by paulojk** [uBlockOrigin/uAssets#14908]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://topcryptoz.net/adblock.html`

### Category

detection

### Describe the issue

Detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium Mobile: 105
filterset (summary): 
  network: 86177
  cosmetic: 30236
  scriptlet: 18181
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8123-27, 2d.6h.14m
    easylist: 63674-19466, 2d.6h.11m
    easyprivacy: 30591-1183, 2d.6h.10m
    plowe-0: 3674-946, 2d.6h.9m
    spa-1: 4638-137, 2d.6h.14m
    ublock-abuse: 76-0, 2d.6h.7m
    ublock-badware: 4199-105, 1d.22h.35m
    ublock-filters: 32997-399, 1d.22h.33m
    ublock-privacy: 245-2, 1d.22h.32m
    ublock-quick-fixes: 422-227, 33m
    ublock-unbreak: 1855-44, 1d.22h.30m
    urlhaus-1: 6793-0, 32m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 991 ms (selfie)
  maxAssetCacheWait: 644 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed a few days ago. Can you force update the filter lists and test again?
