### ISSUE TITLE
cse.google.com: ads

### ISSUE THREAD

**Issue by XCongoAlpha** [uBlockOrigin/uAssets#14906]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cse.google.com/cse?cx=ca4c91f63fa53d51c`

### Category

ads

### Describe the issue

I think the ads show up on all Google Custom Search Engines, regardless of who made them. Tried it in different CSE.

```
https://cse.google.com/cse?cx=ca4c91f63fa53d51c
https://cse.google.com/cse?cx=ec7d33ef358ae1b65
https://cse.google.com/cse?cx=acfc904e8a9f72b84
```

Visiting the links I provided above doesn't show up ads. But when you try search for anything in the custom search engines, ads will show up.

### Screenshot(s)

example: tried searching for "PDF"

![Capture](https://user-images.githubusercontent.com/74475734/190898141-64a39a0a-9420-4a78-9d4d-11aebb719ea4.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 297251
  cosmetic: 294122
  scriptlet: 57904
  html: 797
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/basic/: 50317-7127, 37m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30017-530, 37m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 363-0, 37m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 666-8, 37m
    https://raw.githubusercontent.com/Zalexanninev15/NoADS_RU/main/ads_list.txt: 6130-164, 37m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24142-67, 37m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 37m
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 1876-0, 37m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42500-408, 37m
    https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js: 1192-760, 37m
    adguard-generic: 69911-6936, 39m
    adguard-spyware: 27316-1610, 38m
    block-lan: 43-0, 38m
    adguard-annoyance: 59278-4909, 37m
    fanboy-annoyance: 80563-42237, 37m
    fanboy-cookiemonster: 41060-154, 37m
    ublock-annoyances: 4837-42, 37m
    CHN-0: 29226-7598, 37m
    IRN-0: 2315-36, 37m
    RUS-0: 42245-4195, 37m
  default: 
    user-filters: 8-0, never
    ublock-filters: 33688-3366, 39m
    ublock-badware: 4204-0, 39m
    ublock-privacy: 267-1, 39m
    ublock-abuse: 76-4, 39m
    ublock-unbreak: 1870-5, 39m
    ublock-quick-fixes: 428-0, 39m
    easylist: 63507-16114, 38m
    adguard-spyware-url: 756-49, 38m
    easyprivacy: 30596-14814, 37m
    urlhaus-1: 6986-0, 37m
    curben-phishing: 98537-10, 37m
    plowe-0: 3673-5, 37m
    LegitimateURLShortener: 1947-148, 37m
filterset (user): [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 950 ms (selfie)
  maxAssetCacheWait: 500 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 1
    www.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's because of the filters

```adb
@@/^https?:\/\/(www\.)?[^\s]+\/[a-z]{1,15}[-_]?ad[svbxo]?(\.min)?\.js/$script
@@/^https?:\/\/(www\.)?[^\s]+\/[a-z]{1,15}[-_]?ad[vs](er(ve)?t?(ise|ising|isement)?)?(\.min)?\.js/$script
```

in your custom filter list `Fuck Fuckadblock` which are exception filters and let the ads script `​https://cse.google.com/adsense/search/async-ads.js` go through.

**Comment by XCongoAlpha** [comment]
> 

Thanks for finding that out. 
Another question though, how do I block the ads on cse.google.com without disabling `Fuck Fuckadblock`?

**Comment by stephenhawk8054** [comment]
You can try

```adb
||cse.google.com/adsense/search/async-ads.js$important
```

but I won't recommend using too many external/custom filter lists if you don't know how to resolve the issues yourself. Not optimized written lists can result in conflictions and at many times it will lower your defense rather than enhance it.

And please do the prerequisites of what you have ticked on carefully before reporting:

> - [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists

**Comment by krystian3w** [comment]
In regional version ad frame back, maybe possible update regex.
