### ISSUE TITLE
cut-y.net: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#14907]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cut-y.net/Fo8RI`

### Category

detection

### Describe the issue

This site detect uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/190900506-f7c371ca-9cc8-4ae4-8e7e-efe50f91545d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 61238
  cosmetic: 32472
  scriptlet: 17897
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 28-0, never
    IDN-0: 9228-3, 1d.32m
    easylist: 23698-1, 1d.30m
    easyprivacy: 30595-1149, 1d.28m
    plowe-0: 3674-528, 5d.3h.31m
    ublock-abuse: 76-0, 5d.3h.31m
    ublock-badware: 4200-2, 1d.27m
    ublock-filters: 32888-62, 1d.26m
    ublock-privacy: 244-1, 5d.3h.31m
    ublock-quick-fixes: 440-227, 20h.24m
    ublock-unbreak: 1854-31, 1d.25m
    urlhaus-1: 6809-0, 20h.23m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 384 ms (selfie)
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 5
  no-cosmetic-filtering: true
  no-remote-fonts: true
  blockedDetails: 
    cdntechone.com: 1
    egotizeoxgall.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gstatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I cannot reproduce it. Force update the filter lists and test again. Also, are you using Edge's `Tracking Prevention` in Strict mode?
