### ISSUE TITLE
myflixer.to: ads

### ISSUE THREAD

**Issue by SquidBoiSwitch** [uBlockOrigin/uAssets#14902]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://myflixer.to/`

### Category

ads

### Describe the issue

Shows ads when video is paused

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83348
  cosmetic: 40652
  scriptlet: 17896
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.23h.15m
  default: 
    user-filters: 5-0, never
    easylist: 63818-52, 4d.3h.29m
    easyprivacy: 30569-1171, 4d.3h.28m
    plowe-0: 3671-857, 8d.5h.1m
    ublock-abuse: 76-0, 4d.3h.27m
    ublock-badware: 4245-103, 4d.3h.26m
    ublock-filters: 32700-129, 4d.3h.25m
    ublock-privacy: 245-1, 4d.3h.24m
    ublock-quick-fixes: 422-1, 3h.39m
    ublock-unbreak: 1847-40, 4d.3h.23m
    urlhaus-1: 6809-0, 3h.38m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 370 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    addthis.com: 1
    cagothie.net: 2
    googletagmanager.com: 3
    imgur.com: 1
    jwpltx.com: 2
    mgbid.net: 2
    onesignal.com: 1
    rndskittytor.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which movie link and which server did you encounter the issue?
