### ISSUE TITLE
wcostream.net: ads

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#14909]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wcostream.net/one-piece-episode-702-english-dubbed`

### Category

ads

### Describe the issue

Any player on the website has an ad on the right side of it. Pages without players do not show any ads. I have tried deleting my custom filters and reloading the page, still run into an ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 84628
  cosmetic: 40097
  scriptlet: 17802
  html: 749
listset (total-discarded, last updated): 
  added: 
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 4m
  default: 
    user-filters: 63-2, never
    ublock-filters: 33502-123, 6m
    ublock-badware: 4204-0, 6m
    ublock-privacy: 267-0, 6m
    ublock-abuse: 76-0, 6m
    ublock-unbreak: 1870-0, 6m
    easylist: 63572-581, 5m
    easyprivacy: 30603-1706, 4m
    urlhaus-1: 6793-0, 4m
    plowe-0: 3673-1728, 4m
    ublock-quick-fixes: 217-0, 4m
filterset (user): [array of 63 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2285 ms (selfie)
  maxAssetCacheWait: 184 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    addthis.com: 1
    bloxplay.com: 1
    cpmstar.com: 1
    google-analytics.com: 2
    gumgum.com: 1
    vdo.ai: 2
```
</details>

**Comment by mapx-** [comment]
if it's about the image bellow it's self-promotion

![image](https://user-images.githubusercontent.com/10303732/190917413-18493b00-05dd-44b1-b205-57a1f81c0f8c.png)

add in your custom filters ("my filters"

`||wcostream.net/premiumad2.png$image`

**Comment by rmcin329** [comment]
That worked initially, but now it's back and trying to block it with the element picker only works until you refresh the page.
