### ISSUE TITLE
goettinger-tageblatt.de: nuisance

### ISSUE THREAD

**Issue by D3m3rion** [uBlockOrigin/uAssets#14917]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goettinger-tageblatt.de/lokales/goettingen-lk/goettingen/bekommt-goettingen-queere-ampelmenschen-und-regenbogen-zebrastreifen-PYQZGHLI2HNSNRDLSUA5XU62WY.html`

### Category

nuisance

### Describe the issue

A Cookie banner pops up, although the cookie filters are enabled (plus Easy List GER, AdGuard Annoyances, Easy List Cookie, uBlock filters - Annoyances).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
<img width="1440" alt="Screenshot 2022-09-19 at 11 40 53" src="https://user-images.githubusercontent.com/26471657/190990728-557d6301-1e21-41c4-9440-5a6afbd119de.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 105
filterset (summary): 
  network: 92028
  cosmetic: 131341
  scriptlet: 25472
  html: 757
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    adguard-annoyance: 59276-3714, 16m
    fanboy-cookiemonster: 41036-134, 3d.8h.42m
    ublock-annoyances: 4823-4, 3d.8h.42m
    DEU-0: 5940-2, 4m
  default: 
    ublock-filters: 33682-69, 17h.47m
    ublock-badware: 4204-0, 17h.46m
    ublock-privacy: 268-0, 6d.10h.6m
    ublock-abuse: 76-0, 6d.10h.7m
    ublock-unbreak: 1870-0, 17h.48m
    easylist: 63572-626, 17h.45m
    easyprivacy: 30593-1714, 2d.20h.56m
    urlhaus-1: 6793-0, 17h.43m
    plowe-0: 3674-3, 7d.19h.44m
    ublock-quick-fixes: 217-0, 17h.44m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 142 ms (selfie)
  maxAssetCacheWait: 304 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    go-mpulse.net: 4
    iocnt.net: 1
```
</details>

**Comment by mapx-** [comment]
The cookie can be hidden but then the subscription section is broken

**Comment by D3m3rion** [comment]
IMO the cookie banner is more annoying, so I would already be happy if that would be removed. :)

> The cookie can be hidden but then the subscription section is broken

**Comment by mapx-** [comment]
add in "my filters"

```
goettinger-tageblatt.de##[class^="Adstyled__AdWrapper"]
cmp-sp.goettinger-tageblatt.de##.message-safe-area-holder--safe-bottom.message-safe-area-holder
goettinger-tageblatt.de##[id^="sp_message_container"]
goettinger-tageblatt.de##[aria-labelledby][preserveAspectRatio="none"]
```
