### ISSUE TITLE
My site UTM blocked on unblock!

### ISSUE THREAD

**Issue by ilovecrypt0** [uBlockOrigin/uAssets#14913]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ok-ex.io/?utm_medium=email`

### Describe the issue

I think someone has closed our site on purpose.
This is while we use the link internally
our website is p2p crypto exchange platform there is no ads or spam site
Please take care of this

### Screenshot(s)

![image](https://user-images.githubusercontent.com/10582103/190925244-48cdb852-15bf-4753-b075-db0ae01148bc.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83651
  cosmetic: 40050
  scriptlet: 17809
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63572-52, 19m
    easyprivacy: 30603-1171, 19m
    plowe-0: 3673-862, 19m
    ublock-abuse: 76-0, 19m
    ublock-badware: 4200-105, 19m
    ublock-filters: 32778-108, 19m
    ublock-privacy: 245-1, 19m
    ublock-quick-fixes: 218-9, 19m
    ublock-unbreak: 1858-42, 19m
    urlhaus-1: 6793-0, 19m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 92 redacted]
switchRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 725 ms (selfie)
  maxAssetCacheWait: 296 ms
```
</details>

**Comment by mapx-** [comment]
@MasterKia

**Comment by mapx-** [comment]
@ilovecrypt0 see if still broken after adding:

`ok-ex.io#@#:matches-path(/utm_medium=/) html:remove()`

**Comment by mapx-** [comment]
In the end only that page was broken and that page is a tracking one, normally killed by any privacy list.

**Comment by mapx-** [comment]
my bad, I'll revert the commit

**Comment by FlashWins** [comment]
> my bad, I'll revert the commit
@mapx- 
you really should delete all of soft98.ir lines from Quick Fixes list completely because they only breaks soft98.ir site. test it and you'll see after a few seconds the post will get hidden entirely.

**Comment by FlashWins** [comment]
> That message is 11 days old, we updated the lists constantly.
> 
> https://github.com/uBlockOrigin/uAssets/commits/master/filters/quick-fixes.txt

the mention was 3 hours ago in that topic
