### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by TheRobbebas** [uBlockOrigin/uAssets#14912]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/`

### Category

breakage

### Describe the issue

Pictures that feature a "paid partnership" are filtered out by uBlock. These appear as a slim black line in my feed. When trying to open these pictures via someone's profile the page fades to black as it does when opening a picture, but it does not show the picture or comments. I tested this issue on a new Chrome profile with only uBlock installed, the issue remains. This issue did not happen until very recently.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
<img width="343" alt="chrome_Xdy5PMn0Zy" src="https://user-images.githubusercontent.com/66887624/190922406-ed134f76-69da-4ab3-9eef-7a3db8edfb4e.png">
This is how a picture appears in the feed.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83674
  cosmetic: 40272
  scriptlet: 17897
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63629-52, 1d.7h.54m
    easyprivacy: 30595-1171, 1d.7h.50m
    plowe-0: 3672-861, 1d.7h.56m
    ublock-abuse: 76-0, 6d.20h.26m
    ublock-badware: 4200-105, 1d.7h.53m
    ublock-filters: 32883-104, 1d.7h.52m
    ublock-privacy: 245-1, 1d.7h.58m
    ublock-quick-fixes: 422-227, 6h.54m
    ublock-unbreak: 1854-42, 1d.7h.51m
    urlhaus-1: 6986-0, 6h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2915 ms (selfie)
  maxAssetCacheWait: 487 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    instagram.com: 4
```
</details>

**Comment by mapx-** [comment]
> Pictures that feature a "paid partnership" are filtered out by uBlock

Provide such a page with "paid partnership" otherwise we cannot investigate your issue.

**Comment by TheRobbebas** [comment]
> > Pictures that feature a "paid partnership" are filtered out by uBlock
> 
> Provide such a page with "paid partnership" otherwise we cannot investigate your issue.

https://www.instagram.com/p/CbYEn5uqPyV/

**Comment by mapx-** [comment]
@ryanbr
