### ISSUE TITLE
topcryptoz.net: detection

### ISSUE THREAD

**Issue by craticar** [uBlockOrigin/uAssets#14914]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://topcryptoz.net/most-common-seo-mistakes-that-you-need-to-avoid/`

### Category

detection

### Describe the issue

I noticed another report stating it was fixed a few days ago but I think the site owner has it out for people who use scripts and adblockers because the ads were blocked yesterday and now they aren't, it's displaying an unsavory message when it detects ublock. I've updated the filters, reinstalled it, updated it again, use other browsers and the problem is still there. Screenshot provided.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-18 201926](https://user-images.githubusercontent.com/79741887/190935031-54b65713-e642-4415-9d19-00a9aad7c2a5.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 408637
  cosmetic: 161746
  scriptlet: 42268
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, never
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24113-27, never
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt: 247596-0, never
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt: 97609-39, never
    adguard-annoyance: 59262-283, 1m
    fanboy-annoyance: 80559-3767, never
    fanboy-cookiemonster: 41058-41058, never
    ublock-annoyances: 4812-232, never
  default: 
    user-filters: 28-2, never
    easylist: 63580-18613, never
    easyprivacy: 30595-13860, never
    ublock-abuse: 76-3, never
    ublock-badware: 4200-592, never
    ublock-filters: 32975-3564, never
    ublock-privacy: 245-36, never
    ublock-quick-fixes: 218-10, never
    ublock-unbreak: 1855-49, never
    urlhaus-1: 6793-641, never
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 139 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 88 redacted]
hostRuleset: 
  added: [array of 40 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10797 ms (selfie)
  maxAssetCacheWait: 791 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    googletagmanager.com: 1
    pub.network: 1
```
</details>

**Comment by Procyon-b** [comment]
I've tried to replicate but it works fine for me.
I see that you have 30 user filters as well as some rules. Try again with your user filters disabled (in the "Filter lists" tab).

I've a script blocked on `topcryptoz.net`. You don't. This could be the problem.
```
  blockedDetails: 
    topcryptoz.net: 1
    doubleclick.net: 1
```

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/14908#issuecomment-1250325698
