### ISSUE TITLE
shinbhu.net: detection

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#14922]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shinbhu.net/`

### Category

detection

### Describe the issue

```js
<script type="2e8137c83de1f16420016bd0-text/javascript">
--
  | function _0x2700(_0x1218bd,_0x3bc217){var _0xa1f30d=_0xa1f3();
  | return _0x2700=function(_0x270094,_0x2405fa){_0x270094=_0x270094-0x149;
  | var _0x5927ae=_0xa1f30d[_0x270094];
  | return _0x5927ae;},_0x2700(_0x1218bd,_0x3bc217);
  | }(function(_0x1a0a3d,_0x3a6191){var _0x123097=_0x2700,_0x1d462c=_0x1a0a3d();
  | while(!![]){try{var _0x17b7ee=-parseInt(_0x123097(0x154))/0x1*
  | (parseInt(_0x123097(0x14b))/0x2)+-parseInt(_0x123097(0x152))/0x3+-parseInt(_0x123097(0x14f))/0x4+parseInt(_0x123097(0x156))/0x5*
  | (parseInt(_0x123097(0x14c))/0x6)+-parseInt(_0x123097(0x14a))/0x7+-parseInt(_0x123097(0x151))/0x8+-parseInt(_0x123097(0x155))/0x9*
  | (-parseInt(_0x123097(0x150))/0xa);if(_0x17b7ee===_0x3a6191)break;
  | else _0x1d462c['push'](_0x1d462c['shift']());
  | }catch(_0x1d11a9){_0x1d462c['push'](_0x1d462c['shift']());}}}(_0xa1f3,0x8500d),setTimeout(()=>{var _0x351af4=_0x2700;
  | $['ajax']({'type':_0x351af4(0x153),'url':'https://a.pub.network/crewbase-net/pubfig.min.js',
  | 'error':function(_0x2ef1c3,_0x599a09,_0x47d4d3){var _0x41f030=_0x351af4;
  | alert(_0x41f030(0x14d)),location[_0x41f030(0x14e)]=_0x41f030(0x149);}});},0x3e8));
  | function _0xa1f3(){var _0x4e248a=['10zQqSbM','1794RqXkOi','Hey\x20pussy,\x20disable\x20your\x20adblock!',
  | 'href','2403652QJJWdK','29060YrUhjU','8553064bGisMO','1099935tuDuBN','GET','54877RcqsLv','8361RAOMUk','11065IotwgR','/adblock.html',
  | '3538528MeSIjB'];_0xa1f3=function(){return _0x4e248a;};return _0xa1f3();}

```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 102
filterset (summary): 
  network: 83521
  cosmetic: 40235
  scriptlet: 17926
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63580-52, 2d.49m
    easyprivacy: 30595-1171, 2d.47m
    plowe-0: 3673-862, 2d.46m
    ublock-abuse: 76-0, 2d.44m
    ublock-badware: 4200-105, 2d.42m
    ublock-filters: 32963-110, 2d.41m
    ublock-privacy: 245-1, 2d.40m
    ublock-quick-fixes: 212-10, 1d.29m
    ublock-unbreak: 1854-42, 2d.38m
    urlhaus-1: 6793-0, 1d.28m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 967 ms (selfie)
  maxAssetCacheWait: 534 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    shinbhu.net: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    pub.network: 1
    sportslocalmedia.com: 1
```
</details>

**Comment by mapx-** [comment]
provide specific link not the home page

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f75d1c69a4b0236f23ad2e0ad241e64a1690592a
