### ISSUE TITLE
paypal.com: breakage

### ISSUE THREAD

**Issue by WtFKilla** [uBlockOrigin/uAssets#14923]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.paypal.com/`

### Category

breakage

### Describe the issue

Everytime i log in into my paypal account from my computer. **_Every_** Login he need the Authy Code although I click trust this PC. but i cant find an option in ublock to make it possible that he remember my cookie or whatever he needs to safe this information.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 85651
  cosmetic: 43673
  scriptlet: 17806
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5940-0, 1d.54m
    easylist: 63265-57, 1h.10m
    easyprivacy: 30609-1181, 1h.9m
    plowe-0: 3673-863, 1h.12m
    ublock-abuse: 76-0, 10d.2h.25m
    ublock-badware: 4200-105, 1d.1h
    ublock-filters: 32792-122, 1d.59m
    ublock-privacy: 251-1, 10d.2h.24m
    ublock-quick-fixes: 212-10, 1d.57m
    ublock-unbreak: 1857-43, 1d.58m
    urlhaus-1: 6793-0, 1d.56m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 100 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    paypal.com: 2
    qualtrics.com: 1
```
</details>

**Comment by mapx-** [comment]
- disable other blocking extensions or builtin blockers in chromium browsers
- disable the shields if you are using brave browser
-----------------------------
Don't use any other blocking extension.
if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced

**Comment by WtFKilla** [comment]
i disabled "dont care about cookies" but it dont work. i dont have other
blocking extensions. i use google Chrome.

mapx ***@***.***> schrieb am Mo., 19. Sept. 2022, 19:47:
