### ISSUE TITLE
quenotebookcomprar.com.br: breakage

### ISSUE THREAD

**Issue by SimplesmenteMaria** [uBlockOrigin/uAssets#14924]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://quenotebookcomprar.com.br/ofertas/?_sft_product_availability=in-stock&post_types=notebooks&sort_order=_sfm_sale_lowest-price+asc+num&_sfm_spec_cpu_family=Ryzen+7&_sfm_spec_cpu_model=5700U-%2B-5800H-%2B-5800U-%2B-6800H&_sfm_spec_display_panel_type=IPS-%2B-IPS-level-%2B-OLED-%2B-WVA`

### Category

breakage

### Describe the issue

The page never finishes loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://user-images.githubusercontent.com/110785003/191079686-52cdf7d4-5ccc-4060-a406-228db76d6e4c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 83455
  cosmetic: 39919
  scriptlet: 17806
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33496-41, 2m
    ublock-badware: 4204-0, 2m
    ublock-privacy: 267-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1869-0, 2m
    ublock-quick-fixes: 222-0, 2m
    easylist: 63265-606, 1m
    easyprivacy: 30609-1705, 1m
    urlhaus-1: 6762-0, 1m
    plowe-0: 3673-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6260 ms
  maxAssetCacheWait: 886 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
It seems to be a site issue with Firefox.

@SimplesmenteMaria disable completely uBO in Add-ons manager and test again.

**Comment by sugarfreesweetener** [comment]
@mapx- Are you sure you tested without blocking from `Firefox Tracking Protection`?

**Comment by llacb47** [comment]
@sugarfreesweetener it happens for me too, I'm pretty sure there is a race condition when the site runs faster when the ad scripts are blocked in firefox causing this issue.

**Comment by stephenhawk8054** [comment]
I still get the loading screen randomly even when disabling uBO:

![image](https://user-images.githubusercontent.com/66517106/191140459-824ab1a2-2026-4514-b177-7d34075e95b8.png)

It's random. Sometimes it's stuck in loading status, and sometimes it finishes loading (when disabling uBO).
