### ISSUE TITLE
portalcriatividade.com.br

### ISSUE THREAD

**Issue by johnmathew2** [uBlockOrigin/uAssets#14939]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://portalcriatividade.com.br/2022/08/03/video-cachorrinho-que-so-da-a-patinha-para-turistas-que-dao-gorjeta-viraliza-sabe-como-fazer-negocio/`

### Describe the issue

select text and copy protection

### Configuration

default list

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list and force update the filter lists in about 10 minutes.
