### ISSUE TITLE
thewindowsclub.com

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1493]
### URL(s) where the issue occurs

`http://www.thewindowsclub.com/manage-efi-uefi-boot-options-easyuefi`

### Describe the issue
Antiadblock popup by Admiral.

### Screenshot(s)

![screenshot_20180207_162403](https://user-images.githubusercontent.com/19818572/35924571-b05a7d40-0c23-11e8-8a07-8f523c423601.png)

### Versions

- Browser/version: Vivaldi 1.14.1077.41 (based on Chromium 64.0.3282.121)
- Nano Adblocker 1.0.0.29 (based on uBlock Origin 1.15.4)

### Settings

- https://gist.github.com/hawkeye116477/f7576d0eaccc862a609e954520fa1462

**Comment by jspenguin2017** [comment]
This isn't working anymore.
