### ISSUE TITLE
shinbhu.net: detection

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#14933]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://shinbhu.net/backup/w/?get=PtwH

### Category

detection

### Describe the issue

Same condition 
![Screenshot_20220920-051612](https://user-images.githubusercontent.com/108754068/191129410-188c19b8-b6b2-49e7-b65d-823ab9274603.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 84901
  cosmetic: 27385
  scriptlet: 17853
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8123-27, 6h.47m
    easylist: 63265-18944, 6h.42m
    easyprivacy: 30609-1183, 6h.40m
    plowe-0: 3673-948, 6h.39m
    ublock-abuse: 76-0, 6h.37m
    ublock-badware: 4199-105, 6h.34m
    ublock-filters: 32886-359, 6h.33m
    ublock-privacy: 245-2, 6h.31m
    ublock-quick-fixes: 218-9, 6h.30m
    ublock-unbreak: 1861-44, 6h.29m
    urlhaus-1: 6762-0, 6h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 954 ms (selfie)
  maxAssetCacheWait: 337 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14930#issuecomment-1251687224
