### ISSUE TITLE
amcrest.com: nuisance

### ISSUE THREAD

**Issue by revdanielc** [uBlockOrigin/uAssets#14947]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://amcrest.com/`

### Category

nuisance

### Describe the issue

There's a chat popup on the bottom left that pops up on every single page, whether I dismiss it or not.  If I dismiss it, it comes back after 5 seconds with a loud, annoying sound.  I've tried using the Element Zapper, which takes it away, but as soon as I reload the page or go to another page within the site, it shows right back up again and keeps coming back.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://user-images.githubusercontent.com/89028002/191271096-abfd1880-8d9c-4ea0-b9bb-00deb2c210d9.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 106
filterset (summary): 
  network: 83449
  cosmetic: 39915
  scriptlet: 17809
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63265-52, 1d.10m
    easyprivacy: 30609-1171, 1d.9m
    plowe-0: 3673-862, 2d.12h.36m
    ublock-abuse: 76-0, 2d.1h.6m
    ublock-badware: 4200-105, 1d.8m
    ublock-filters: 32778-110, 1d.7m
    ublock-privacy: 245-1, 2d.1h.7m
    ublock-quick-fixes: 218-9, 16h.6m
    ublock-unbreak: 1856-42, 1d.12m
    urlhaus-1: 6762-0, 16h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 269 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    amazon-adsystem.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
or add

`||livechatinc.com^$script,domain=amcrest.com`
