### ISSUE TITLE
Cant view videos on rumble.com

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#14948]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I cant view any videos on rumble unless ublock is disabled, here one video to check:

I tried other videos to be sure it wasnt a problem with the video itself and the problem persists.

### A specific URL where the issue occurs

`https://rumble.com/v1kq92h-nego-ricardo-ventura-petry-monark-talks-78.html`

### Steps to Reproduce

Just try to see any video with ublock enabled.

### Expected behavior

Videos should work.

### Actual behavior

Videos doesnt work.

### uBlock Origin version

1.44

### Browser name and version

Waterfox

### Operating System and version

Win7 x64

**Comment by stephenhawk8054** [comment]
I can play the video normally

![image](https://user-images.githubusercontent.com/66517106/191273862-75e45490-fa5e-4517-84ab-dddc1a9432a1.png)

Can you force update the filter lists ([click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

---

If the issue still persists, can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by mapx-** [comment]
I can reproduce in waterfox / firefox / chrome

working on my side
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=rumble.com`

**Comment by Felipefpl** [comment]
Thanks stephen for the suggestions and mapx for the fix. :) - it works now.

**Comment by stephenhawk8054** [comment]
> So the ima3 shim doesn't work? `https://github.com/uBlockOrigin/uBlock-issues/issues/2158`

Redirect rules do not always work, especially when it's related to video player. We have many similar situations with `google-analytics` or `googletagmanager`. Usually it's for reducing anti adblock cases.
