### ISSUE TITLE
totalcar.hu: breakage

### ISSUE THREAD

**Issue by zone333** [uBlockOrigin/uAssets#14945]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://totalcar.hu/magazin/hirek/2022/09/20/kozel-9-ezer-forintba-fog-kerulni-a-havi-sztradamatrica---megis-hozzanyultak-az-arakhoz/`

### Category

breakage

### Describe the issue

cannot be scrolled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 104
filterset (summary): 
  network: 85317
  cosmetic: 29104
  scriptlet: 17965
  html: 767
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33725-304, 4d.16h.4m
    ublock-badware: 4248-0, 4d.16h.3m
    ublock-privacy: 267-1, 4d.16h.2m
    ublock-abuse: 76-0, 4d.16h
    ublock-unbreak: 1870-0, 4d.15h.59m
    ublock-quick-fixes: 217-0, 1d.25m
    adguard-mobile: 8123-169, 4d.16h.11m
    easylist: 63843-20200, 4d.14h.52m
    easyprivacy: 30590-1723, 4d.14h.51m
    urlhaus-1: 6986-0, 2d.3h.58m
    plowe-0: 3672-3, 3d.17h.27m
    HUN-0: 2179-85, 2d.53m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 309 ms (selfie)
  maxAssetCacheWait: 124 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    totalcar.hu: 1
    adocean.pl: 3
    adverticum.net: 1
    doubleclick.net: 2
    facebook.net: 1
    gemius.pl: 5
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    indapass.hu: 2
    index.hu: 2
    onesignal.com: 2
    quantcast.com: 1
    quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's caused by

```adb
hu###qc-cmp2-container
hu##.qc-cmp2-container
```

in `HUN: hufilter` list.

@scripthunter7 Sorry, can you take a look?
