### ISSUE TITLE
aternos.org anti-adblock

### ISSUE THREAD

**Issue by NocFA** [uBlockOrigin/uAssets#1494]
### URL(s) where the issue occurs

`[https://aternos.org/server/]`

### Describe the issue

[Upon signing up and trying to get to the creation page of a hosted server I get an anti-adblock warning, it allows skipping but every other button or page you load to will pop the warning up again, I had to turn it off.]

### Screenshot(s)

[https://i.imgur.com/IF36i6U.png]

### Versions

- Browser/version: [ Vivaldi 1.14.1077.45 (Stable channel) (32-bit)

- uBlock Origin version: [v1.0.0.29]

### Settings

- [Enabled Nano defender integration]

### Notes

[Tested without other extensions enabled, anti-adblock continues; I'm not a wiz kid so that's about all I got haha]

**Comment by mapx-** [comment]
corrected here: https://github.com/uBlockOrigin/uAssets/commit/fca9007adc93704e938a0d2d9bc0ee3c018c0942

**Comment by smed79** [comment]
An update is needed here.

_@mapx- I PM you a test login credentials at EasyList Forum_.

**Comment by smed79** [comment]
@mahaer-mahmud ? Do you get any breakage if you add
```
aternos.org##+js(abort-on-property-read.js, pbjsChunk)
```

**Comment by mapx-** [comment]
waiting for feedback about the @okiehsch injecting filter above

**Comment by machinesmith42** [comment]
unstable

**Comment by llacb47** [comment]
?

**Comment by machinesmith42** [comment]
it sometimes reverts

**Comment by clayathan** [comment]
I'm using these on Aternos to block the anti-adblock page. There's probably duplicates/unnecessary filters, but for completion's sake. These filters seems to fix the issue for me. (Sorry if the syntax of this is off, I'm new to this site.)
`aternos.org##div[id][style]:has(>div[style*="z"] > div[style*="x"])`
`aternos.org##+js(acis, $, Date)`
`aternos.org##aside:has(.ad)`
`aternos.org##div.ad`
`aternos.org##+js(abort-current-inline-script.js, $, Date)`
`||static.h-bid.com^$script,important,domain=aternos.org`
`aternos.org##script:inject(setTimeout-defuser.js, hasAdblock)`
`aternos.org##div[id]:has(div[style]:has(.fa-frown))`
