### ISSUE TITLE
weather.com: anti-blocker

### ISSUE THREAD

**Issue by vesprz** [uBlockOrigin/uAssets#14953]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://weather.com/weather/today`

### Describe the issue

weather.com's main page loads fine, but its forecast pages (Today, Hourly, 10 Day, etc.) will display an anti-blocker overlay after a few seconds

### Screenshot(s)

![weather_antiblocker](https://user-images.githubusercontent.com/114011174/191315167-bf681202-0b9f-4417-9d83-f9e4005a874a.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 104.0.2

### Settings

Tried enabling 'uBlock filters – Annoyances' filter list, but it didn't help

### Notes

Overlay began appearing today (Sep 20, 2022), site was working fine yesterday

**Comment by mapx-** [comment]
only FF / us ip, chrome is ok

**Comment by vesprz** [comment]
@mapx- Fix works great, thank you!
