### ISSUE TITLE
jetpunk.com: detection

### ISSUE THREAD

**Issue by KyceAbdallah** [uBlockOrigin/uAssets#14950]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jetpunk.com/users/kyceabdallah`

### Category

detection

### Describe the issue

It detects uBlock Origin fix plzzzzzzzzzzzz

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83344
  cosmetic: 40051
  scriptlet: 17819
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63602-52, 1d.14h.52m
    easyprivacy: 30603-1171, 1d.14h.51m
    plowe-0: 3674-861, 4d.16h
    ublock-abuse: 76-0, 6d.1h.11m
    ublock-badware: 4200-105, 1d.14h.50m
    ublock-filters: 32778-108, 1d.14h.49m
    ublock-privacy: 245-1, 1d.14h.48m
    ublock-quick-fixes: 228-9, 1h.47m
    ublock-unbreak: 1858-42, 1d.14h.47m
    urlhaus-1: 6456-0, 1h.46m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1897 ms (selfie)
  maxAssetCacheWait: 986 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    jetpunk.com: 1
    amazon-adsystem.com: 1
    google-analytics.com: 1
    googletagservices.com: 1
```
</details>

**Comment by mapx-** [comment]
Does it happen even without logging in ?

**Comment by KyceAbdallah** [comment]
> Does it happen even without logging in ?

Yes

**Comment by mapx-** [comment]
- if browser edge / brave => disable tracking protection / shields
- reset uBO to default settings, update all lists
- reopen the browser
- disable other blocking extensions
- test again

**Comment by KyceAbdallah** [comment]
> * if browser edge / brave => disable tracking protection / shields
> * reset uBO to default settings, update all lists
> * reopen the browser
> * disable other blocking extensions
> * test again

Just did these and it still detects it. Also I don't know if it matters, but I'm using Google Chrome on a Chromebook running ChromeOS

**Comment by sugarfreesweetener** [comment]
school / work wifi?

**Comment by mapx-** [comment]
if you disable uBO do you still get anti adb message ?

post a screenshot with the anti adb stuff

**Comment by KyceAbdallah** [comment]
> a screenshot **with** the anti adb stuff ?

![Screenshot 2022-09-21 9 21 07 AM](https://user-images.githubusercontent.com/90739617/191515022-f9a85964-06de-42a1-aecc-9cee4ecb2c16.png)

**Comment by mapx-** [comment]
open the logger then refresh the page => go into the logger and post here all the blocked items

**Comment by KyceAbdallah** [comment]
> open the logger then refresh the page => go into the logger and post here all the blocked items

+3256
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3235
##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
www.jetpunk.com
dom
https://www.jetpunk.com/your-account

+3235
##.box-ad-outer
www.jetpunk.com
dom
https://www.jetpunk.com/your-account

+3235
##.box-ad-inner
www.jetpunk.com
dom
https://www.jetpunk.com/your-account

+3235
##.banner-ad-outer
www.jetpunk.com
dom
https://www.jetpunk.com/your-account

+3235
/prebid.$domain=~prebid.org
--
www.jetpunk.com
1
xhr
https://www.jetpunk.com/prebid.js

+3235
google-analytics.com/ga.js
<<
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3235
||google-analytics.com/ga.js$script,redirect-rule=google-analytics.com/ga.js:5
--
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3235
||google-analytics.com^
--
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3235
amazon_apstag.js
<<
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3235
||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js
--
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3235
||amazon-adsystem.com^
--
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3235
googletagservices.com/gpt.js
<<
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3235
||googletagservices.com/tag/js/gpt.js$script,redirect-rule=googletagservices.com/gpt.js:5
--
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3235
||googletagservices.com^
--
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3235
##+js(cookie-remover, PageCount)
www.jetpunk.com
dom
https://www.jetpunk.com/your-account

+3233
https://www.jetpunk.com/your-account

+3230
##[id^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
www.jetpunk.com
dom
https://www.jetpunk.com/

+3230
##.banner-ad-outer
www.jetpunk.com
dom
https://www.jetpunk.com/

+3230
/prebid.$domain=~prebid.org
--
www.jetpunk.com
1
xhr
https://www.jetpunk.com/prebid.js

+3229
google-analytics.com/ga.js
<<
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3229
||google-analytics.com/ga.js$script,redirect-rule=google-analytics.com/ga.js:5
--
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3229
||google-analytics.com^
--
www.jetpunk.com
3
script
https://ssl.google-analytics.com/ga.js

+3229
amazon_apstag.js
<<
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3229
||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js
--
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3229
||amazon-adsystem.com^
--
www.jetpunk.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js

+3229
googletagservices.com/gpt.js
<<
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3229
||googletagservices.com/tag/js/gpt.js$script,redirect-rule=googletagservices.com/gpt.js:5
--
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3229
||googletagservices.com^
--
www.jetpunk.com
3
script
https://www.googletagservices.com/tag/js/gpt.js

+3229
##+js(cookie-remover, PageCount)
www.jetpunk.com
dom
https://www.jetpunk.com/

+3227
https://www.jetpunk.com/

+3226
https://jetpunk.com/

+3223
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3223
||google.com/log?
--
ogs.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3223
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3223
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3223
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3223
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3222
||google.com/log?
--
www.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3222
||google.com/log?
--
www.google.com
1
xhr
https://www.google.com/log?format=json&hasfast=true&authuser=0

+3222
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?atyp=i&ei=tlYrY-zZPNLdptQP8aGisA8&ct=slh&v=t1&m=HV&pv=0.9490725697374911&me=1:1663784631754,V,0,0,1366,665:0,B,2664:0,N,1,tlYrY-zZPNLdptQP8aGisA8:0,R,1,8,24,36,92,33:0,R,1,CAEQAw,230,85,82,44:0,R,1,CAEQBA,314,85,78,44:0,R,1,CAEQBQ,394,85,86,44:0,R,1,CAEQBg,482,85,77,44:0,R,1,CAEQMw,180,182,652,2238:0,R,1,CAMQAA,180,182,600,250:0,R,1,CAMQAQ,180,182,600,250:0,R,1,CAgQAA,180,476,652,228:0,R,1,CBAQAQ,180,513,652,43:0,R,1,CAwQAQ,180,557,652,43:0,R,1,CA4QAQ,180,601,652,43:0,R,1,CA8QAQ,180,645,652,43:718,x:59,T:0,R,1,8,24,36,92,33:0,R,1,CAEQAw,230,85,82,44:0,R,1,CAEQBA,314,85,78,44:0,R,1,CAEQBQ,394,85,86,44:0,R,1,CAEQBg,482,85,77,44:0,R,1,CAEQMw,180,182,652,2238:0,R,1,CAMQAA,180,182,600,250:0,R,1,CAMQAQ,180,182,600,250:0,R,1,CAgQAA,180,476,652,228:0,R,1,CBAQAQ,180,513,652,43:0,R,1,CAwQAQ,180,557,652,43:0,R,1,CA4QAQ,180,601,652,43:0,R,1,CA8QAQ,180,645,652,43:727,e,U&zx=1663784633259

+3222
||google.com/log?
--
www.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3222
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?atyp=i&ei=tlYrY-zZPNLdptQP8aGisA8&vet=12ahUKEwjsjKffwKb6AhXSrokEHfGQCPYQ7zR6BAgDEAs..s&ct=tw&zx=1663784633030

+3222
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?atyp=i&ei=tlYrY-zZPNLdptQP8aGisA8&vet=12ahUKEwjsjKffwKb6AhXSrokEHfGQCPYQ8DR6BAgDEBQ..s&ct=tw&zx=1663784633022

+3222
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?atyp=i&ei=tlYrY-zZPNLdptQP8aGisA8&vet=12ahUKEwjsjKffwKb6AhXSrokEHfGQCPYQv7cBegQIAxAN..s&ct=tw&zx=1663784633018

+3222
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?atyp=i&ei=tlYrY-zZPNLdptQP8aGisA8&dt19=2&zx=1663784632895

+3222
/client_204?$image
--
www.google.com
1
image
https://www.google.com/client_204?&atyp=i&biw=1366&bih=665&dpr=1&ei=tlYrY-zZPNLdptQP8aGisA8

+3221
||google.com/gen_204?
--
www.google.com
1
ping
https://www.google.com/gen_204?s=web&t=aft&atyp=csi&ei=tlYrY-zZPNLdptQP8aGisA8&rt=wsrt.278,aft.615,sct.405&wh=665&imn=24&ima=0&imad=0&aftp=-1&bl=x9VE

+3221
||id.google.com/verify/
--
www.google.com
1
image
https://id.google.com/verify/ANUKpzEFMhS99Sze8gu1vM0fm8HbIJ_e4D07Vh2NHRnJIvtfM-9GVcxnXAu9lQzZa-9BSaL--GmHFAX6gVh-x-YCKdL4GvB2M_3Rl0ciBfsItw

+3220
https://www.google.com/search?q=je&rlz=1CADTIH_enUS1023&oq=je&aqs=chrome..69i57j69i60l3.1615j0j7&sourceid=chrome&ie=UTF-8&safe=active&ssui=on

+3217
||google.com/log?
--
ogs.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3217
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3217
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3217
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3217
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+3201
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+2796
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
/flushimpressions?
--
mail.google.com
1
xhr
https://mail.google.com/mail/u/0/flushimpressions?ui=2&ik=6ec8943776&jsver=lBuZfEb4B7E.en..es5&cbl=gmail.pinto-server_20220909.06_p1&_reqid=3951954&pcd=1&cfact=7056&cfinact=7058%2C7084%2C7082%2C7083%2C7085%2C7086%2C7117%2C7057&mb=0&rt=j

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://www.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+32
||google.com/log?
--
mail.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true

+2
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+2
||google.com/log?
--
ogs.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+2
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+2
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+2
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+0
||google.com/log?
--
ogs.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+0
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+0
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+0
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

+0
||google.com/log?
--
classroom.google.com
1
xhr
https://play.google.com/log?format=json&hasfast=true&authuser=0

**Comment by KyceAbdallah** [comment]
> open the logger then refresh the page => go into the logger and post here all the blocked items

Copied that from the logger

**Comment by mapx-** [comment]
Does this filter work for you ?

`jetpunk.com##+js(no-xhr-if, prebid)`

if doesn't try this 1:
`@@||jetpunk.com/prebid.js$xhr,1p`

**Comment by KyceAbdallah** [comment]
> Does this filter work for you ?
> 
> `jetpunk.com##+js(no-xhr-if, prebid)`
> 
> if doesn't try this 1: `@@||jetpunk.com/prebid.js$xhr,1p`

Yes, the first one worked thanks so much!
