### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by salatest** [uBlockOrigin/uAssets#14958]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://maxstream.video/ehppjikukruj/a2NKUE1tSE9UbGMyeHhUTWVCYlpXUT09`

### Category

detection

### Describe the issue

After few seconds a pop-up messages is showed and you can't use the page anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 88803
  cosmetic: 47245
  scriptlet: 17787
  html: 744
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 33523-41, 2m
    ublock-badware: 4204-0, 2m
    ublock-privacy: 268-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1870-0, 2m
    easylist: 63219-613, 1m
    easyprivacy: 30615-1707, 1m
    urlhaus-1: 6456-0, 1m
    plowe-0: 3673-3, 1m
    ITA-0: 13190-1, 1m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 80 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 383 ms
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    host-cdn.net: 1
    intellipopup.com: 1
    setsdowntown.com: 2
```
</details>

**Comment by salatest** [comment]
![immagine](https://user-images.githubusercontent.com/21248034/191350691-23e46c6c-4cd6-403d-b736-6e8dc80d0952.png)

**Comment by mapx-** [comment]
now the video link above redirects directly to some malicious domain
