### ISSUE TITLE
pc.warface.com: breakage

### ISSUE THREAD

**Issue by Anuj-Yadav-Git** [uBlockOrigin/uAssets#14957]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pc.warface.com/en/inventory/`

### Category

breakage

### Describe the issue

this site doesn't display some of the contents whanever i turn on ublock
with ublock
![Screenshot (1)](https://user-images.githubusercontent.com/104966689/191344619-c0df3821-7318-4190-9932-4a40bd825b82.png)
without ublock
![Screenshot (11)](https://user-images.githubusercontent.com/104966689/191344814-75da8b11-0e50-421e-aea5-00a245941cf7.png)
with ublock
![Screenshot (17)](https://user-images.githubusercontent.com/104966689/191344901-34c91a80-5070-412f-b9b5-fc925ebc5185.png)
without ublock
![Screenshot (18)](https://user-images.githubusercontent.com/104966689/191344981-567a5227-c7c9-4bb8-82fd-9c3888ce3c0a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 104
filterset (summary): 
  network: 236966
  cosmetic: 163276
  scriptlet: 38888
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59277-1653, 2d.20h.6m
    adguard-generic: 69911-881, 2d.20h.5m
    adguard-mobile: 8122-63, 2d.20h.11m
    adguard-social: 18536-1987, 2d.20h.10m
    adguard-spyware: 27316-1559, 2d.20h.9m
    adguard-spyware-url: 756-1, 2d.20h.13m
    block-lan: 43-0, 11d.9h.5m
    curben-phishing: 98887-0, 23h.44m
    curben-pup: 190-1, 23h.45m
    dpollock-0: 11390-248, 8m
    fanboy-annoyance: 80563-37556, 1d.22h.36m
    fanboy-cookiemonster: 41060-41060, 1d.22h.38m
    fanboy-social: 23354-23354, 2d.20h.12m
    fanboy-thirdparty_social: 68-21, 1d.22h.39m
    ublock-annoyances: 4812-244, 2d.20h.14m
  default: 
    user-filters: 0-0, never
    easylist: 63580-20132, 2d.20h.15m
    easyprivacy: 30595-14263, 2d.20h
    plowe-0: 3673-1377, 11d.9h.4m
    ublock-abuse: 76-0, 11d.9h.4m
    ublock-badware: 4200-337, 2d.20h.3m
    ublock-filters: 32975-4220, 2d.20h.2m
    ublock-privacy: 251-48, 11d.9h.4m
    ublock-quick-fixes: 218-21, 23h.43m
    ublock-unbreak: 1854-105, 2d.20h.1m
    urlhaus-1: 6762-1, 23h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2717 ms (selfie)
  maxAssetCacheWait: 2240 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    consentmanager.net: 2
    googletagmanager.com: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
Could you add `@@||consentmanager.net^$script,domain=pc.warface.com` to "My filters"?

@ryanbr

**Comment by mapx-** [comment]
@Anuj-Yadav-Git did you test the filter above ?

Did you test keeping only the default lists ?

**Comment by Anuj-Yadav-Git** [comment]
> Could you add `@@||consentmanager.net^$script,domain=pc.warface.com` to "My filters"?
> 
> @ryanbr @Yuki2718 @Alex-302

did that and it worked thanks
