### ISSUE TITLE
[Admiral] itavisen.no

### ISSUE THREAD

**Issue by Znote** [uBlockOrigin/uAssets#1495]
### URL(s) where the issue occurs

```
http://itavisen.no/
```

### Describe the issue

After aproximate 2 seconds, a div overlay seems to appear below body > footer.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1552144/35930655-cd2d756c-0c32-11e8-89c5-4ed2e9a6bd47.png)

![image](https://user-images.githubusercontent.com/1552144/35930130-67978748-0c31-11e8-9f76-52eaf9bc6723.png)

### Versions

- Browser/version: Versjon 64.0.3282.140 (Offisiell delversjon) (64-bit)
- uBlock Origin version: uBlock Origin v1.14.24

### Settings

```json
{
  "timeStamp": 1518024086442,
  "version": "1.14.24",
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "user-filters",
    "assets.json",
    "public_suffix_list.dat",
    "ublock-resources",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "plowe-0",
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nmoz-extension-scheme\nopera-scheme\notland.net\nvivaldi-scheme",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "",
  "filterLists": {
    "assets/user/filters.txt": {
      "off": false
    },
    "assets.json": {
      "off": false
    },
    "assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat": {
      "off": false
    },
    "assets/ublock/resources.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": false
    },
    "assets/ublock/badware.txt": {
      "off": false
    },
    "assets/ublock/privacy.txt": {
      "off": false
    },
    "ublock-abuse": {
      "off": false
    },
    "assets/ublock/unbreak.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": false
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": false
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": false
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": false
    },
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": false
    },
    "assets/ublock/experimental.txt": {
      "off": true
    }
  }
}
```

```
uBlock filters​​​​​ - 3704 used of 3706​​​​
uBlock filters – Badware risks​​​​​ 7 used of 7​​​​
uBlock filters – Privacy​​​​​ 65 used of 65​​​​
uBlock filters – Resource abuse 189 used of 191​​​​
uBlock filters – Unbreak​​​​​ 270 used of 270​​​​
EasyList​​​​​ 77798 used of 78044​​​​
EasyPrivacy 14046 used of 14205​​​​
Malware Domain List​​​​​ 1130 used of 1146​​​​
Malware domains​​​​​ 16044 used of 16045​​​​
Peter Lowe’s Ad and tracking server list 2581 used of 2585​​​​
AakList (Anti-Adblock Killer)​​​​​ 2118 used of 2179​​​​
```
### Notes

A fix might be to remove any div that ever occurs after body > footer in this website. Removing the div manually through inspector tools effectively negates the block.

**Comment by THEtomaso** [comment]
### URL:
`https://itavisen.no/`

### Problem:

The following rule (found in **uBlock filters**) blocks embeded videos:
`||itavisen.no/cdn-cgi/apps/head/$script`

### Screenshot of unblocked video:

![filterissue-itavisen3](https://user-images.githubusercontent.com/9382674/43734435-437f490a-99a7-11e8-989c-cc56a0d74c72.jpg)

### Possible fix:
Instead of using the rule above, this rule seems to serve the same purpose, and allows the videos to be played:
`||elderlyscissors.com$third-party,domain=itavisen.no`

### Additional thoughts:
If you scroll the page (after having started the video playback), the video will become an annoying "floater".
Perhaps someone could figure out a way to prevent this from happening, and add a potential fix to **uBlock filters - Annoyances**?

**Comment by okiehsch** [comment]
@DandelionSprout can you add 
`||elderlyscissors.com$third-party,domain=itavisen.no`
to your list, we can then remove `||itavisen.no/cdn-cgi/apps/head/$script` from `uBO-filters`

**Comment by DandelionSprout** [comment]
Sounds like a simple and good solution to me. I'll get right to it.

**Comment by okiehsch** [comment]
> If you scroll the page (after having started the video playback), the video will become an annoying "floater".

I am not sure if this an "annoyance" worth fixing to be honest. 
You have to manually start the playback and it will only become a floater if the playback is active, i.e no "floating" if you click pause.

````
itavisen.no##script:inject(addEventListener-defuser.js, scroll, n===L)
````
disables it.

**Comment by THEtomaso** [comment]
> `itavisen.no##script:inject(addEventListener-defuser.js, scroll, n===L)`

Doesn't work anymore.
Now it blocks the entire video!

**Comment by okiehsch** [comment]
What do you mean by blocked?
I can see a 1 hour 16 minutes long video on my end and if I click play it starts.

**Comment by THEtomaso** [comment]
With an empty cache, and using the above annoyance rule, I now get this:

![filterissue-itavisen5](https://user-images.githubusercontent.com/9382674/44198823-a8667300-a142-11e8-8b93-c953f75350b1.jpg)

..and after removing the rule:

![filterissue-itavisen6](https://user-images.githubusercontent.com/9382674/44198839-b4523500-a142-11e8-9f83-3b03aa101c14.jpg)

**Comment by okiehsch** [comment]
Do you have the regional norwegian list enabled?

**Comment by divinity76** [comment]
@okiehsch nope.
here's a list of the activated filters, but pretty sure it's just the default ones:
https://i.imgur.com/6W6tmDV.png

**Comment by okiehsch** [comment]
See my edit above.

**Comment by divinity76** [comment]
hah, activating the `NOR: Dandelion Sprouts norske filtre​​​​​`  fixed it indeed! :+1:

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
try using the novegian list
