### ISSUE TITLE
mobile.hotspot: lan

### ISSUE THREAD

**Issue by s-zeid** [uBlockOrigin/uAssets#14956]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://mobile.hotspot/`

### Describe the issue

This domain is used by certain mobile broadband hotspots to access their admin servers, for example the [Franklin RT410/T10](https://www.t-mobile.com/support/tutorials/device/franklin/t10-hotspot/topic/settings/overview-of-device-settings/2).  It should be blocked in [lan-block.txt](https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt).

### uBlock Origin version

1.44.2

### Browser name and version

Firefox 104.0

### Settings

N/A

**Comment by mapx-** [comment]
@gwarser
