### ISSUE TITLE
hacksnation.com: detection

### ISSUE THREAD

**Issue by nagoffy** [uBlockOrigin/uAssets#14951]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hacksnation.com/`

### Category

detection

### Describe the issue

Hello,
i got blank page with some message "
So, you use an ad blocker. Thats cool. Sometimes we do to But without advertising-income, we cant keep making this site awesome!.
I cant view the page until I disable the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83497
  cosmetic: 40217
  scriptlet: 17899
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 25-3, never
    easylist: 63580-52, 2d.21h.57m
    easyprivacy: 30595-1171, 3d.13h.28m
    plowe-0: 3673-859, 11d.5h.48m
    ublock-abuse: 76-0, 11d.5h.51m
    ublock-badware: 4200-105, 22h.1m
    ublock-filters: 32905-124, 3d.13h.27m
    ublock-privacy: 251-1, 11d.5h.50m
    ublock-quick-fixes: 218-9, 22h
    ublock-unbreak: 1851-42, 3d.13h.26m
    urlhaus-1: 6762-0, 21h.59m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 633 ms (selfie)
  maxAssetCacheWait: 328 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed a few days ago: https://github.com/uBlockOrigin/uAssets/issues/14887. Force update your filter lists and test again
