### ISSUE TITLE
en.wikipedia.org: ads

### ISSUE THREAD

**Issue by danger89** [uBlockOrigin/uAssets#14959]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://en.wikipedia.org/`

### Category

ads

### Describe the issue

Too much sponsor and/or donation ads by Wikipedia itself.

I'm trying to use the following custom filter to block more content, it's just a start to give you an idea:

```
en.wikipedia.org##.frb-country-NL.frb-rml-enabled.frb
en.wikipedia.org##.frb-nag-link
```

I would like to see this getting blocked by default in uBlock Origin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![wiki_ad](https://user-images.githubusercontent.com/628926/191370186-760e45e7-570e-47e8-9943-27d336febe0c.png)

![wiki_ad2](https://user-images.githubusercontent.com/628926/191370191-fed3f303-094e-4b6e-ae76-fa1c72871575.png)

![wiki_ad3](https://user-images.githubusercontent.com/628926/191370206-105844bd-f7d4-41f9-9b23-fa37f1ae7c99.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 82995
  cosmetic: 40389
  scriptlet: 17865
  html: 742
listset (total-discarded, last updated): 
  default: 
    user-filters: 17-1, never
    ublock-filters: 33611-33, 3d.22h.56m
    ublock-badware: 4204-0, 3d.22h.55m
    ublock-privacy: 267-0, 3d.22h.58m
    ublock-abuse: 76-0, 3d.22h.57m
    ublock-unbreak: 1864-0, 3d.22h.54m
    easylist: 63723-599, 3d.22h.53m
    easyprivacy: 30594-1704, 3d.22h.51m
    urlhaus-1: 6456-0, 1h.47m
    plowe-0: 3674-3, 7d.23h.39m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 858 ms (selfie)
  maxAssetCacheWait: 366 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    wikipedia.org: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
![image](https://user-images.githubusercontent.com/113248817/191374136-c1e8b573-4dc3-4a7b-a25d-72efc4b8f87a.png)

**Comment by danger89** [comment]
[Fanboy's Annoyance](https://secure.fanboy.co.nz/fanboy-annoyance.txt) has indeed a good list. Why not make this part of the default uBlock filters? I do think it can be seen as just "ads".

**Comment by sugarfreesweetener** [comment]
> [Fanboy's Annoyance](https://secure.fanboy.co.nz/fanboy-annoyance.txt) has indeed a good list. Why not make this part of the default uBlock filters? I do think it can be seen as just "ads".

- Fanboy's Annoyances includes `EasyList Cookie` and `EasyList Social`, and uBO is not intended to be an anti-cookie-popup by default
- Increased risk of breakage (https://github.com/uBlockOrigin/uAssets/issues/14957 for example)

@Yuki2718 did you say something (in a public discussion) about legal reasons being discussed internaly?
