### ISSUE TITLE
[nsfw] dropmms.com: detection

### ISSUE THREAD

**Issue by homeass571** [uBlockOrigin/uAssets#14965]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dropmms.com/`

### Category

detection

### Describe the issue

site shows a Ad-block detected warning which doesn't goes away despite following all of the above prerequisites. i tried on chrome with default setting as well as on firfox with alot of custom lists, results was the same. i tried using the "element picker mode" to block out the elements one by one but the static white page doesn't get detected by the picker so as a result i cant get access to the site. only thing that works is to stop the page from loading completely or when i turn of java script fro the site using ublock origin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/99623663/191460607-91d9104c-bdc4-4205-8f6c-b71875f64c97.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83843
  cosmetic: 39597
  scriptlet: 17859
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62973-52, 1m
    easyprivacy: 30626-1171, now
    plowe-0: 3673-862, now
    ublock-abuse: 76-0, now
    ublock-badware: 4200-105, now
    ublock-filters: 32849-115, now
    ublock-privacy: 246-1, now
    ublock-quick-fixes: 242-9, now
    ublock-unbreak: 1857-42, now
    urlhaus-1: 7070-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1581 ms
  maxAssetCacheWait: 196 ms

```
</details>

**Comment by okiehsch** [comment]
Site is down in my end.

**Comment by Procyon-b** [comment]
Try this filter:
```
dropmms.com##+js(aeld, load, "undefined")
```
re: https://www.reddit.com/r/uBlockOrigin/comments/xjgx89/ublock_is_detected_on_this_forum_please_help/
