### ISSUE TITLE
allcryptoz.net: detection

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#14964]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://allcryptoz.net/backup/w/?get=4ZNiKTq
https://crewbase.net/backup/w/?get=5MmR
https://crewus.net/backup/w/?get=sUyX
https://shinbhu.net/backup/w/?get=PtwH
https://shinchu.net/backup/w/?get=qRYZtkEH
https://thumb8.net/backup/w/?get=cUAIua
https://thumb9.net/backup/w/?get=VjbNj
https://ultraten.net/backup/w/?get=Em1HsmlJ
https://uniqueten.net/backup/w/?get=7SZIM

### Category

detection

### Describe the issue

looks like they own the website to the 10 links above (allcryptoz,topcryptoz,crewbase,crewus,ultraten,uniquten,thumb8,thumb9,shinbu,shincu) update every day, to fight adblock. today I tried to open the link, and the results were detected again adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20220921-125231](https://user-images.githubusercontent.com/108754068/191426515-ed2381e7-7bf6-4480-abe2-ab08074ae40c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 84654
  cosmetic: 27410
  scriptlet: 17883
  html: 751
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33628-372, 10h.19m
    ublock-badware: 4203-0, 10h.19m
    ublock-privacy: 268-1, 10h.19m
    ublock-abuse: 76-0, 10h.19m
    ublock-unbreak: 1875-0, 10h.19m
    ublock-quick-fixes: 245-0, 10h.19m
    adguard-mobile: 8127-168, 10h.24m
    easylist: 63219-19254, 10h.19m
    easyprivacy: 30615-1731, 10h.18m
    urlhaus-1: 6456-0, 10h.19m
    plowe-0: 3673-3, 10h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 305 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    wpadmngr.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old issue thread, we can see new comments.

**Comment by kaiji05** [comment]
Ok thanks

**Comment by kaiji05** [comment]
This night for 10 link already update, so detection adblock. Please update again for adblock that's link. Thanks

![Screenshot_20220922-022732](https://user-images.githubusercontent.com/108754068/191593333-414dfe23-c2ed-490b-8625-89f9be42e1bb.png)

**Comment by sugarfreesweetener** [comment]
Is there any good country for VPNs in regard to these sites?

**Comment by kaiji05** [comment]
Can't update again?

**Comment by stephenhawk8054** [comment]
Force update the filter lists.
