### ISSUE TITLE
next-episode.net: detection

### ISSUE THREAD

**Issue by Foambrush** [uBlockOrigin/uAssets#14962]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://next-episode.net`

### Category

anti adb

### Describe the issue

Pop up keeps coming back asking to turn off adblocker and stays on page and locks it down until you kill 4 containers? before the site becomes usable but as soon as you move to another page you get same issue again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 253533
  cosmetic: 219157
  scriptlet: 38816
  html: 768
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    http://winhelp2002.mvps.org/hosts.txt: 8730-0, 2d.4h.55m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-2, 2d.4h.55m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-314, 2d.4h.55m
    https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt: 222-0, 1d.1h.48m
    https://winhelp2002.mvps.org/hosts.txt: 8730-8730, 2d.4h.55m
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-11, 2d.4h.55m
    adguard-generic: 69867-5207, 2d.4h.57m
    adguard-mobile: 8122-380, 2d.4h.57m
    adguard-spyware: 27316-2101, 2d.4h.57m
    adguard-spyware-url: 756-3, 2d.4h.57m
    block-lan: 43-0, 2d.4h.57m
    curben-phishing: 98852-17, 1d.1h.50m
    curben-pup: 190-1, 1d.1h.49m
    adguard-annoyance: 59261-571, 2d.4h.56m
    adguard-social: 18538-1941, 2d.4h.56m
    fanboy-thirdparty_social: 68-0, 2d.4h.56m
    fanboy-annoyance: 80563-65072, 2d.4h.56m
    fanboy-cookiemonster: 41060-3108, 2d.4h.56m
    fanboy-social: 23354-50, 2d.4h.56m
    ublock-annoyances: 4841-164, 2d.4h.56m
    [1 lists not shown]: [too many]
  default: 
    ublock-filters: 33488-78, 2d.4h.57m
    ublock-badware: 4204-5, 2d.4h.57m
    ublock-privacy: 267-0, 2d.4h.57m
    ublock-abuse: 76-0, 2d.4h.57m
    ublock-unbreak: 1870-16, 2d.4h.57m
    ublock-quick-fixes: 222-222, 1d.1h.52m
    easylist: 63572-580, 2d.4h.57m
    easyprivacy: 30603-14724, 2d.4h.56m
    urlhaus-1: 6762-0, 1d.1h.51m
    plowe-0: 3673-1960, 2d.4h.55m
filterset (user): [array of 77 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1267 ms (selfie)
  maxAssetCacheWait: 860 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
`about:addons` => any other add-on?

**Comment by Foambrush** [comment]
I have tried the site with and without my VPN on and get the same results, my FF extensions are Ublock and Weather extension

Sean 

    On Tuesday, September 20, 2022 at 07:28:59 PM EDT, sugarfreesweetener ***@***.***> wrote:  
 
 


about:addons => any other add-on?
