### ISSUE TITLE
tamilblasters.trade: ads

### ISSUE THREAD

**Issue by Tetrax-10** [uBlockOrigin/uAssets#14968]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tamilblasters.trade/`

### Category

ads

### Describe the issue

I see ads. i dont know why

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/75513645/191484255-011d10ad-837b-4b02-861a-11ab328432fe.png)

![image](https://user-images.githubusercontent.com/75513645/191484313-4a2d8511-73b8-4a1e-b719-3a02a39c6900.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 51833
  cosmetic: 9317
  scriptlet: 17944
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-1, never
    easylist: 17-1, 3d.6h.52m
    easyprivacy: 30595-1147, 3d.6h.58m
    plowe-0: 3673-529, 5h.52m
    ublock-abuse: 76-0, 15h.21m
    ublock-badware: 4200-2, 3d.6h.56m
    ublock-filters: 32975-30, 3d.6h.55m
    ublock-privacy: 246-1, 15h.20m
    ublock-quick-fixes: 241-6, 5h.51m
    ublock-unbreak: 1855-29, 3d.6h.54m
    urlhaus-1: 7070-0, 5h.50m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 352 ms (selfie)
  maxAssetCacheWait: 117 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    cheeradvise.com: 1
    e2ertt.com: 2
    googletagmanager.com: 1
    pseepsie.com: 1
    rescuephrase.com: 1
    rtmark.net: 8
    shpluteic.com: 2
    topazgrubbed.com: 1
    tzegilo.com: 1
    unphionetor.com: 3
```
</details>

**Comment by Tetrax-10** [comment]
> EasyList

ohh, how do i do that? sry am new to this

**Comment by Tetrax-10** [comment]
Facing this issue again in this same [website](https://tamilblasters.rent/). Tried updating and even clicked "Purge all caches" and then "update now".

![image](https://user-images.githubusercontent.com/75513645/218486226-353b2e91-6298-4d87-887d-f1f9cd8020e2.png)

**Comment by mapx-** [comment]
add

`tamilblasters.rent##li.ipsWidget:has([href="https://www.cricketbook.com/"])`

for such classic ads report directly at [easylist repository](https://github.com/easylist/easylist/issues)

@ryanbr
