### ISSUE TITLE
Subdomain request not being blocked 

### ISSUE THREAD

**Issue by abarragan-adtriba** [uBlockOrigin/uAssets#14969]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.thelocal.de/20220921/key-points-everything-germany-is-doing-to-help-relieve-rising-energy-costs/`

### Describe the issue

When browsing mentioned URL with uBO and Peter Lowe's list enabled the request for the paywall to `experience.piano.io` should be blocked by said list, since filter rule `127.0.0.1 piano.io` is there. However the request is not blocked by uBO and the paywall shows up after some seconds.
I haven't got deep knowledge of the different types of requests done by the websites maybe I'm not aware of a limitation uBO has here in this case.
Thank you.

### uBlock Origin version

1.44.4

### Browser name and version

Brave 1.43.93

### Settings

- Added Peter Lowe's Ad and tracking server list

### Notes

I added to my main browser, Peter Lowe's list (in ABP format, not hosts) and the request is blocked successfully. Same result on Vivaldi browser.
I also manually added the rule to My Filters `|| piano.io^` and the request is still not blocked, unless i put the full hostname in the rule.

**Comment by abarragan-adtriba** [comment]
@MasterKia, i disabled unbreak list and it's blocked perfectly now. I'm sorry for the inconvenience, feel free to close the issue or let me know if i should do it. Thank you

**Comment by mapx-** [comment]
add

```
||experience.piano.io^
||piano.io/xbuilder
```

or only
`||tinypass.com^`

and reenable unbreak list

**Comment by mapx-** [comment]
@MasterKia we don't block paywalls, so no `||piano.io^$3p`

**Comment by abarragan-adtriba** [comment]
@mapx- yeahi know i can block only that subdomain, but since Piano is analytics or related i dont want the unbreak list to not block piano.

**Comment by abarragan-adtriba** [comment]
@MasterKia , will do that, i hope there are no more "surprises" like this in the unbreak list
