### ISSUE TITLE
[nsfw] facebook.com: ads

### ISSUE THREAD

**Issue by ObaidulBGC** [uBlockOrigin/uAssets#14971]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/watch?v=465228768879071`

### Category

ads

### Describe the issue

Adblocker Didn't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 83152
  cosmetic: 39823
  scriptlet: 17820
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33512-41, 1d.5h.53m
    ublock-badware: 4204-0, 1d.5h.52m
    ublock-privacy: 267-0, 1d.5h.54m
    ublock-abuse: 76-0, 5d.21h.19m
    ublock-unbreak: 1869-0, 1d.5h.51m
    ublock-quick-fixes: 222-0, 20h.26m
    easylist: 63168-606, 1d.5h.49m
    easyprivacy: 30610-1705, 1d.5h.48m
    urlhaus-1: 6456-0, 20h.25m
    plowe-0: 3673-3, 1d.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 996 ms (selfie)
  maxAssetCacheWait: 56 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/3367
