### ISSUE TITLE
gturls.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#1497]
### URL(s) where the issue occurs

`http://gturls.com/rWpuOd`

### Describe the issue

Please add timer skipping to this site..

------
Why doesn't it work when I add the following line in 'My Filters'
_gturls.com##script:inject(nano-setTimeout-booster.js)_

**Comment by okiehsch** [comment]
It is the wrong filter.
`gturls.com##script:inject(nano-setInterval-booster.js)`
