### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by galapogos01** [uBlockOrigin/uAssets#14978]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://m.aliexpress.com/account/index.html`

### Category

breakage

### Describe the issue

AliExpress detects unlock and forced the user to a pin validation. This then gets stuck and doesn't return to the site. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 104
filterset (summary): 
  network: 85109
  cosmetic: 27443
  scriptlet: 17964
  html: 751
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 33790-301, 3d.20h.8m
    ublock-badware: 4203-0, 1d.18h.57m
    ublock-privacy: 267-1, 3d.1h.58m
    ublock-abuse: 76-0, 2d.1h.3m
    ublock-unbreak: 1873-0, 3d.20h.7m
    adguard-mobile: 8122-168, 3d.20h.4m
    easylist: 63600-19712, 3d.20h.5m
    easyprivacy: 30610-1711, 1d.19h.21m
    plowe-0: 3673-3, 12d.18h.32m
    urlhaus-1: 6881-0, 4m
    ublock-quick-fixes: 222-0, 15h.53m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3166 ms (selfie)
  maxAssetCacheWait: 1425 ms
popupPanel: 
  blocked: 61
  blockedDetails: 
    alicdn.com: 2
    aliyuncs.com: 16
    mmstat.com: 40
    taobao.com: 3
```
</details>

**Comment by mapx-** [comment]
I'm able to log in, then log out .. and no pin validation on my end

**Comment by galapogos01** [comment]
Did you clear cookies first or try a clean profile? They are doing some kind of browser fingerprinting and UBlock makes it angry.

**Comment by mapx-** [comment]
yeah, cleared the cookies too => normal login
