### ISSUE TITLE
playwire.com: ads

### ISSUE THREAD

**Issue by hKQwHW** [uBlockOrigin/uAssets#14972]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.playwire.com/`

### Category

ads

### Describe the issue

An ad network. This network's config.json and other things still get loaded into `https://bestiefy.com/`, although the ads themselves are blocked. Still, though, I feel like allowing an ad network to load enables browser fingerprinting for ads. So maybe this should be blocked, like how discourse-ads and discourse-fingerprint is blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 222221
  cosmetic: 218818
  scriptlet: 38801
  html: 768
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    adguard-generic: 70040-5097, 21h.41m
    adguard-mobile: 8125-10, 21h.40m
    adguard-spyware: 27415-1698, 21h.39m
    adguard-spyware-url: 763-3, 21h.38m
    block-lan: 43-0, 4d.22h.7m
    curben-phishing: 97633-4, 18h.6m
    curben-pup: 191-0, 18h.5m
    adguard-annoyance: 59392-5128, 9m
    adguard-social: 18611-1066, 9m
    fanboy-thirdparty_social: 69-0, 9m
    fanboy-annoyance: 80583-64610, 9m
    fanboy-cookiemonster: 41055-136, 4d.22h.7m
    fanboy-social: 23360-28, 9m
    ublock-annoyances: 4845-4, 21h.37m
  default: 
    user-filters: 11-0, never
    ublock-filters: 33514-74, 21h.44m
    ublock-badware: 4204-0, 21h.43m
    ublock-privacy: 267-0, 4d.22h.8m
    ublock-abuse: 76-0, 4d.22h.8m
    ublock-unbreak: 1869-1, 21h.42m
    ublock-quick-fixes: 245-0, 18h.8m
    easylist: 63719-513, 4d.22h.7m
    easyprivacy: 30593-13962, 4d.22h.7m
    urlhaus-1: 6456-0, 18h.7m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 421 ms (selfie)
  maxAssetCacheWait: 1330 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    playwire.com: 1
    adroll.com: 1
    googletagmanager.com: 2
    hs-analytics.net: 1
    hs-banner.com: 1
    redditstatic.com: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Not seen, need more details.

**Comment by sugarfreesweetener** [comment]
@ryanbr 
![image](https://user-images.githubusercontent.com/113248817/191730058-aa9a5d38-378c-484c-97dd-50ffed72f73e.png)

**Comment by ryanbr** [comment]
Find another sample site, not helpful

**Comment by sugarfreesweetener** [comment]
Isn't it 3p exposure, and thus already a candidate for blocking via EasyPrivacy?
