### ISSUE TITLE
lacourt.org: breakage

### ISSUE THREAD

**Issue by reportinglorting** [uBlockOrigin/uAssets#14980]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lacourt.org/documentimages/pacommerce/login.aspx?appId=IMG&casetype=CIV`

### Category

breakage

### Describe the issue

Clicking the "Create an Account" button on the right-hand side of the webpage, under "NEW ACCOUNT", results in no action. 

After disabling uBlock Origin and reloading the webpage, clicking the "Create an Account" button takes me to the next webpage to create an account.
 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83582
  cosmetic: 39550
  scriptlet: 17812
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63014-52, 13m
    easyprivacy: 30630-1170, 12m
    plowe-0: 3673-862, 12m
    ublock-abuse: 76-0, 12m
    ublock-badware: 4200-105, 12m
    ublock-filters: 32864-114, 12m
    ublock-privacy: 246-1, 12m
    ublock-unbreak: 1859-42, 12m
    urlhaus-1: 6881-0, 12m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 175 ms (selfie)
  maxAssetCacheWait: 97 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    lacourt.org: 1
    norton.com: 2
```
</details>

**Comment by sugarfreesweetener** [comment]
EasyPrivacy @ryanbr @Khrin
