### ISSUE TITLE
cloudflare.com: breakage

### ISSUE THREAD

**Issue by MartinVonReichenberg** [uBlockOrigin/uAssets#14989]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cloudflare.com/`

### Category

breakage

### CloudFlare.com 
Website's homepage has a purely script-based header.

The following built-in custom filter: **_Fanboy’s Annoyance_** breaks its usability by not showing the overlay when choosing a title.

Cloudflare.com is mentioned 6 times within asset viewing, please take a look . . .

Thank you in advance!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-09-22_11-58-19](https://user-images.githubusercontent.com/110736521/191718028-1c25d6fb-0a17-48d7-934a-720096072126.png)
![Screenshot_2022-09-22_11-59-02](https://user-images.githubusercontent.com/110736521/191718030-29a987f6-c680-4273-9858-6f1243365b81.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 91.13.0-ESR
filterset (summary): 
  network: 92226
  cosmetic: 114953
  scriptlet: 22878
  html: 769
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 5d.21h.8m
    fanboy-annoyance: 80569-64579, 5d.21h.8m
    fanboy-cookiemonster: 41055-136, 5d.21h.8m
    fanboy-social: 23358-28, 1d.18h.36m
    ublock-annoyances: 4841-5, 1d.18h.35m
    CZE-0: 725-0, 2h.48m
    NOR-0: 2804-10, 2h.47m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33514-54, 1d.18h.44m
    ublock-badware: 4204-0, 1d.18h.43m
    ublock-privacy: 267-0, 1d.18h.42m
    ublock-abuse: 76-0, 1d.18h.41m
    ublock-unbreak: 1869-0, 1d.18h.40m
    ublock-quick-fixes: 237-0, 2h.51m
    easylist: 63190-626, 1d.18h.39m
    easyprivacy: 30615-1713, 1d.18h.37m
    urlhaus-1: 7076-0, 2h.49m
    plowe-0: 3672-3, 5d.21h.8m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1744 ms (selfie)
  maxAssetCacheWait: 958 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cloudflare.com: 3
    cloudflareinsights.com: 1
```
</details>

**Comment by okiehsch** [comment]
Does adding
`cloudflare.com#@#.bottom-0.fixed`
to your filter list work for you?

**Comment by MartinVonReichenberg** [comment]
### Yes,
After adding the entry into "My Filters" it works.

Thank you ! 

:-)
