### ISSUE TITLE
likecs.com: ads

### ISSUE THREAD

**Issue by cmmdwl** [uBlockOrigin/uAssets#14981]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.likecs.com/show-714701.html?sc=422`

### Category

ads

### Describe the issue

After clearing the cookies, open the page and click page  the web page will jump to the advertisement page by itself and open himself

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 103
filterset (summary): 
  network: 120114
  cosmetic: 84500
  scriptlet: 30765
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 70017-513, 2m
  default: 
    user-filters: 82-0, never
    CHN-0: 29194-95, 2m
    easylist: 63007-753, 1m
    easyprivacy: 30630-1306, 1m
    plowe-0: 3673-877, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4200-335, 1m
    ublock-filters: 32864-3594, now
    ublock-privacy: 246-1, now
    ublock-quick-fixes: 233-22, now
    ublock-unbreak: 1859-83, now
    urlhaus-1: 7076-0, now
filterset (user): [array of 82 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1008 ms
  maxAssetCacheWait: 684 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Test for breakage

```
likecs.com##+js(set, document.onclick, '')
likecs.com##.contentbef
jd.com##+js(window-close-if, /^/)
```

**Comment by cmmdwl** [comment]
> 破损测试
> 
> ```
> likecs.com##+js(set, document.onclick, '')
> likecs.com##.contentbef
> jd.com##+js(window-close-if, /^/)
> ```

thasks it's work

**Comment by github-h** [comment]
Hi guys，This commit  https://github.com/uBlockOrigin/uAssets/commit/ad82c254d5ec88d617d7ee829ab96ad915807f77 has caused a very serious problem.

It will cause any link on JD's shopping website to be unable to be opened normally. 
When you click the link, the new tab will flash past and then be closed. This seriously affects the normal access behavior, and requests to withdraw this rule. 

`jd.com##+js(window-close-if, /^/)`

Because of the automatic rule synchronization, it will affect many advocates.

**Comment by mapx-** [comment]
removed
