### ISSUE TITLE
discoveryplus.com: ads

### ISSUE THREAD

**Issue by SkateIV** [uBlockOrigin/uAssets#14987]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.discoveryplus.com/it/video/airport-security-europa/stagione-1-episodio-2`

### Category

ads

### Describe the issue

Advertising present at the beginning and during the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 99
filterset (summary): 
  network: 89472
  cosmetic: 47321
  scriptlet: 17839
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33512-32, 1d.19h.27m
    ublock-badware: 4204-0, 1d.19h.26m
    ublock-privacy: 267-0, 1d.19h.25m
    ublock-abuse: 76-0, 1d.19h.24m
    ublock-unbreak: 1869-0, 1d.19h.23m
    ublock-quick-fixes: 246-6, 19h.11m
    easylist: 63188-596, 1d.19h.21m
    easyprivacy: 30615-1723, 1d.19h.19m
    urlhaus-1: 7070-0, 19h.10m
    plowe-0: 3673-3, 1d.19h.17m
    ITA-0: 13190-9, 19h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2796 ms (selfie)
  maxAssetCacheWait: 1202 ms
popupPanel: 
  blocked: 321
  blockedDetails: 
    discoveryplus.com: 6
    adsafeprotected.com: 12
    app.link: 243
    doubleclick.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 6
    moatads.com: 51
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
this filter seems working in chrome, not in FF

`||h264.io/a/x-goog-token=Expires$xhr,redirect=nooptext,domain=discoveryplus.com,important`

**Comment by mapx-** [comment]
However it's SSAI, see https://github.com/uBlockOrigin/uAssets/issues/1905

**Comment by mapx-** [comment]
@AdamWr do you have an idea how to manipulate mpd in this case ?

**Comment by AdamWr** [comment]
If nothing changed, then this still should works - https://github.com/AdguardTeam/AdGuardExtra/issues/297#issuecomment-1172894064
