### ISSUE TITLE
ko.wikipedia.org: ads

### ISSUE THREAD

**Issue by Araboja** [uBlockOrigin/uAssets#14982]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ko.wikipedia.org/wiki/%ED%8C%8C%ED%83%80%EA%B3%A0%EB%8B%88%EC%95%84`

### Category

ads

### Describe the issue

that site show ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 84698
  cosmetic: 42037
  scriptlet: 17924
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33499-40, 1d.15h.16m
    ublock-badware: 4204-0, 1d.15h.15m
    ublock-privacy: 267-0, 1d.15h.14m
    ublock-abuse: 76-0, 1d.15h.13m
    ublock-unbreak: 1869-0, 1d.15h.12m
    ublock-quick-fixes: 246-0, 15h
    easylist: 63188-631, 1d.15h.9m
    easyprivacy: 30615-1713, 1d.15h.8m
    urlhaus-1: 7070-0, 14h.59m
    plowe-0: 3673-3, 1d.15h.6m
    KOR-1: 3277-31, 15h.25m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2027 ms (selfie)
  maxAssetCacheWait: 815 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
If you mean the Sound banner at the top, you can enable `Fanboy’s Annoyance` or `AdGuard Annoyances` or add this filter to ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

```adb
wikipedia.org###siteNotice
```
