### ISSUE TITLE
playsroyal.com: popups

### ISSUE THREAD

**Issue by KatSanger** [uBlockOrigin/uAssets#14983]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://playsroyal.com/stock/902/750768168321941504.html`

### Category

popups

### Describe the issue

Everytime I open my phone the website pop ups keep happening

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 104
filterset (summary): 
  network: 81889
  cosmetic: 27001
  scriptlet: 17690
  html: 727
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33312-397, never
    ublock-badware: 4236-0, never
    ublock-privacy: 247-1, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1876-0, never
    ublock-quick-fixes: 386-0, never
    adguard-mobile: 8132-326, never
    easylist: 69310-24901, never
    easyprivacy: 27312-135, never
    urlhaus-1: 5164-0, never
    plowe-0: 3634-450, never
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2639 ms
  maxAssetCacheWait: 9 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    doubleclick.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> Everytime I open my phone

So the popup appears before you accessing any sites on the browser? I think it's related to the phone's issues, not ublock's.
