### ISSUE TITLE
[nsfw] securly.com: popups

### ISSUE THREAD

**Issue by voidtheunknown** [uBlockOrigin/uAssets#14998]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.securly.com/blocked`

### Category

popups

### Describe the issue

annoying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 102
filterset (summary): 
  network: 83742
  cosmetic: 40056
  scriptlet: 17828
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63572-52, 3d.16h.59m
    easyprivacy: 30603-1171, 3d.16h.58m
    plowe-0: 3674-861, 8d.12m
    ublock-abuse: 76-0, 11d.20h.54m
    ublock-badware: 4200-105, 3d.17h.1m
    ublock-filters: 32778-108, 3d.16h.57m
    ublock-privacy: 245-1, 8d.13m
    ublock-quick-fixes: 242-6, 22h.4m
    ublock-unbreak: 1858-42, 3d.17h.2m
    urlhaus-1: 6881-0, 22h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9986 ms (selfie)
  maxAssetCacheWait: 1214 ms
popupPanel: 
  blocked: 8
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    securly.com: 7
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
It was repeatedly reported but nobody is able to provide the steps to reproduce the issue

https://github.com/uBlockOrigin/uAssets/issues/11552

Account required ?
screenshot with the popup ?
Steps to reproduce ?
