### ISSUE TITLE
freebinance.top: detection

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#14990]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freebinance.top/`

### Category

detection

### Describe the issue

Detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 85293
  cosmetic: 27413
  scriptlet: 17897
  html: 753
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33667-291, 1d.3h.41m
    ublock-badware: 4203-0, 1d.3h.41m
    ublock-privacy: 268-1, 1d.3h.41m
    ublock-abuse: 76-0, 1d.3h.41m
    ublock-unbreak: 1875-0, 1d.3h.41m
    ublock-quick-fixes: 246-0, 1d.3h.41m
    adguard-mobile: 8128-168, 1d.3h.41m
    easylist: 62973-19106, 1d.3h.40m
    easyprivacy: 30619-1715, 1d.3h.40m
    urlhaus-1: 7070-0, 1d.3h.40m
    plowe-0: 3673-3, 1d.3h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 786 ms (selfie)
  maxAssetCacheWait: 375 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
I guess one needs an account to reproduce.

**Comment by kaiji05** [comment]
Username: ***@***.***
Password: sideki05

**Comment by stephenhawk8054** [comment]
Test account (email - pass)

`TerryRicemr1.91996@gmail.com - TerryRicemr1.91996@gmail.com`
