### ISSUE TITLE
developers.google.cn: breakage

### ISSUE THREAD

**Issue by GatoNaranja** [uBlockOrigin/uAssets#14996]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://developers.google.cn/analytics/devguides/collection/analyticsjs/sending-hits`

### Category

breakage

### Describe the issue

Service Unavailable with the uBO on and the site backs to normal with the uBO turns off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/76199161/191774479-be0222f2-d05e-4b94-8cf9-c3b55295ed57.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 102455
  cosmetic: 50048
  scriptlet: 17945
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 24-1, never
    CHN-0: 29169-87, 2d.53m
    easylist: 63187-85, 2d.54m
    easyprivacy: 30595-1195, 4d.21h.53m
    plowe-0: 3671-860, 12d.7h.10m
    ublock-abuse: 76-0, 6d.4h.55m
    ublock-badware: 4200-105, 2d.49m
    ublock-filters: 32802-128, 2d.52m
    ublock-privacy: 245-1, 6d.4h.54m
    ublock-quick-fixes: 218-9, 18h.34m
    ublock-unbreak: 1856-43, 2d.51m
    urlhaus-1: 7076-0, 5h.4m
filterset (user): [array of 24 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 184 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`@@||developers.google.cn/analytics/$xhr,1p`

@ryanbr
