### ISSUE TITLE
vtm.be: detection

### ISSUE THREAD

**Issue by hftjyg** [uBlockOrigin/uAssets#14999]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vtm.be/vtmgo/afspelen/eaa4c11e3-26c8-4a7f-8877-9a456f40c319`

### Category

detection

### Describe the issue

detects ad block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 84323
  cosmetic: 41827
  scriptlet: 17884
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-1, never
    NLD-0: 2437-14, 2d.5h.11m
    easylist: 63580-55, 4d.18h.18m
    easyprivacy: 30595-1172, 4d.18h.17m
    plowe-0: 3674-861, 6d.20h.32m
    ublock-abuse: 76-0, 6d.20h.35m
    ublock-badware: 4205-105, 8h.13m
    ublock-filters: 32865-152, 8h.12m
    ublock-privacy: 245-1, 6d.20h.34m
    ublock-quick-fixes: 241-9, 10m
    ublock-unbreak: 1859-56, 8h.11m
    urlhaus-1: 6832-0, 9m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 428 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    vtm.be: 1
    fwmrm.net: 2
    gemius.pl: 1
    litix.io: 2
    pushengage.com: 1
    spott.ai: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
||fwmrm.net^$important,domain=vtm.be,badfilter
||fwmrm.net/ad/$xhr,domain=vtm.be,redirect-rule=nooptext
```

**Comment by sugarfreesweetener** [comment]
@BPower0036

**Comment by BPower0036** [comment]
@mapx- you also need to remove https://github.com/uBlockOrigin/uAssets/blob/16f167bd37502af2261f553300191275b0449c8e/filters/filters.txt#L4154

**Comment by BPower0036** [comment]
@mapx- the hotfix can also be removed because solution is already applied to regional list
https://github.com/uBlockOrigin/uAssets/blob/2924f480f02527017dba06899ffaaf833ac2a91b/filters/quick-fixes.txt#L219-L221

**Comment by SilverNetiX** [comment]
> ||fwmrm.net^$important,domain=vtm.be,badfilter
> vtm.be##+js(no-fetch-if, csai)

I can confirm this works.

If anyone is wondering how.

1. Open uBlock dashboard
2. copy and paste the above code into the large text field in the dashboard
3. click Apply changes
4. relead vtm video you wnat to watch. It should work without issues now.

**Comment by mapx-** [comment]
You need only to update all the lists. The fix was added to the Dutch list `NLD: EasyDutch`

**Comment by MysticDAssassin** [comment]
It stopped working for me.

**Comment by BPower0036** [comment]
Account required

**Comment by mapx-** [comment]
anti adb again

Test

```
vtm.be#@#+js(no-fetch-if, csai)
@@||v.fwmrm.net/ad/*6&caid$xhr,domain=vtm.be
```

I didn't get video ads

**Comment by MysticDAssassin** [comment]
Thanks, it worked.

**Comment by mapx-** [comment]
@BPower0036

**Comment by mapx-** [comment]
@BPower0036 you have to remove 
`vtm.be##+js(no-fetch-if, csai)`
