### ISSUE TITLE
[nsfw] onscreens.me: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#14992]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.onscreens.me/`

### Category

ads

### Describe the issue

ads showing

### Screenshot(s)

<details>
https://user-images.githubusercontent.com/81616288/191732265-a0791374-2d44-45aa-8c07-c0f165f8ac40.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86050
  cosmetic: 43316
  scriptlet: 17857
  html: 752
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33583-54, 48m
    ublock-badware: 4209-0, 48m
    ublock-privacy: 268-0, 48m
    ublock-abuse: 76-0, 48m
    ublock-unbreak: 1872-0, 48m
    ublock-quick-fixes: 237-0, 48m
    easylist: 62950-613, 48m
    easyprivacy: 30630-1715, 48m
    urlhaus-1: 7076-0, 48m
    plowe-0: 3673-3, 48m
    DEU-0: 5947-2, 48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9445 ms (selfie)
  maxAssetCacheWait: 786 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    realsrv.com: 1
    satiq.net: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`onscreens.me##[href^="//apptjmp.com/"]`

**Comment by mapx-** [comment]
`||ptlwmstc.com^`
