### ISSUE TITLE
caprisun.com: breakage

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uAssets#14997]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.caprisun.com/`

### Category

breakage

### Describe the issue

The website styles appear broken when uBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/110956608/191786796-e32bcb81-7700-45e2-815e-b2b0348bdb0b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 87999
  cosmetic: 77645
  scriptlet: 19934
  html: 754
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1948-0, 16h.47m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 16h.47m
    adguard-spyware-url: 763-110, 16h.47m
    block-lan: 44-0, 16h.47m
    fanboy-cookiemonster: 41071-90, 16h.47m
  default: 
    user-filters: 121-0, never
    ublock-filters: 33578-54, 16h.48m
    ublock-badware: 4204-0, 16h.48m
    ublock-privacy: 268-2, 16h.48m
    ublock-abuse: 76-0, 16h.48m
    ublock-unbreak: 1872-0, 16h.48m
    ublock-quick-fixes: 257-0, 16h.48m
    easylist: 63014-622, 16h.47m
    easyprivacy: 30630-1705, 16h.47m
    urlhaus-1: 6881-0, 16h.47m
    plowe-0: 3673-3, 16h.47m
filterset (user): [array of 61 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 323 ms (selfie)
  maxAssetCacheWait: 244 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    instana.io: 1
    onetrust.com: 2
    yottaa.net: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
Can you send a screenshot of the logger? Particularly, any cosmetic filtering, blocking, if any.

**Comment by wavygecko** [comment]
I did some digging and it looks like the Actually Legitimate URL Shortener list is the culprit here.

@DandelionSprout I think this redirect is breaking things?

`https://www.caprisun.com/skavastream/studio/loadJSModules?campaignid=233`
→
`https://www.caprisun.com/skavastream/studio/loadJSModules`
