### ISSUE TITLE
file-upload.net malicious fake .exe downloads

### ISSUE THREAD

**Issue by mario898** [uBlockOrigin/uAssets#15]
### Describe the issue

German/English filehoster service that tricks the user downloading a malicious .exe file instead of the original file. Very dangerous website, because it's ranked high on Google. No. 1 result if you search for "file uplod".
3-rd party sources:
[Bei file-upload.net richtig downloaden, ohne eine .exe zu bekommen](http://www.keywelt-board.com/index.php?/topic/169550-bei-file-uploadnet-richtig-downloaden-ohne-eine-exe-zu-bekommen) ([en](https://translate.google.de/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=http%3A%2F%2Fwww.keywelt-board.com%2Findex.php%3F%2Ftopic%2F169550-bei-file-uploadnet-richtig-downloaden-ohne-eine-exe-zu-bekommen%2F&edit-text=&act=url))
[dubiose Umleitung bei file-upolad.net link](http://www.trojaner-board.de/153360-dubiose-umleitung-file-upolad-net-link.html) ([en](https://translate.google.de/translate?hl=de&sl=de&tl=en&u=http%3A%2F%2Fwww.trojaner-board.de%2F153360-dubiose-umleitung-file-upolad-net-link.html))

One _could_ fix this by blocking the fake download buttons only, but the idea of file hosters is to upload a file and then send it to someone else who potentially has no adblock, therefore I would suggest to block this site altogether.

### One or more specific URLs where the issue occurs

Example download link to verify my claims: http://www.file-upload.net/download-11474808/ExampleImage.JPG.html (BE AWARE, this might want to download an .exe file instead of a .jpg file)

### Screenshot(s)

http://www.pic-upload.de/view-23726134/fuhilfe.png.html
The red box marks the correct download button. All other buttons are fake/malicious.

### Your settings

- Browser/version: Firefox 45
- uBlock Origin version: 1.6.8

**Comment by gorhill** [comment]
> The red box marks the correct download button. All other buttons are fake/malicious.

Why not create filters for the deceptive ads on the page?

**Comment by gorhill** [comment]
`file-upload.net##iframe` seems to do a good job.

**Comment by mario898** [comment]
This is a bad idea. Imagine someone is looking for a trustworthy file hoster service where he can upload a file and then send it to friends or even business partners. Then he will think file-upload.net is a "clean" website, although it's not. All recipients not using uBO will see this malicious download button then.

**Comment by lewisje** [comment]
By that logic, we'd need to block nearly all file-hosting sites.
