### ISSUE TITLE
streamingcommunity.tech: detection

### ISSUE THREAD

**Issue by gennariarmando** [uBlockOrigin/uAssets#15002]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://streamingcommunity.tech/watch/3009?e=23709`

### Category

detection

### Describe the issue

Adblocker gets detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b0
Chromium: 105
filterset (summary): 
  network: 82097
  cosmetic: 42689
  scriptlet: 17826
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66408-590, never
    easyprivacy: 27446-577, never
    plowe-0: 3634-3, never
    ublock-abuse: 76-0, never
    ublock-badware: 4217-0, never
    ublock-filters: 32538-31, never
    ublock-privacy: 253-0, never
    ublock-quick-fixes: 420-0, never
    ublock-unbreak: 1847-0, never
    urlhaus-1: 7132-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 716 ms
  maxAssetCacheWait: 4 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    d2y8ttytgze7qt.cloudfront.net: 1
    googletagmanager.com: 1
    thaudray.com: 1
```
</details>

**Comment by mapx-** [comment]
update all filter lists
(how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
