### ISSUE TITLE
Brid.tv / index.hr filter not working

### ISSUE THREAD

**Issue by bmatic385** [uBlockOrigin/uAssets#15004]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.index.hr/vijesti/clanak/video-lavrov-zakasnio-sat-i-pol-na-sjednicu-una-ukrajince-usporedio-s-nacistima/2397356.aspx
https://www.index.hr/magazin/clanak/courtney-love-johnny-depp-mi-je-spasio-zivot-kad-sam-se-predozirala/2366389.aspx
```

### Describe the issue

When trying to play video on site index.hr uBlock blocks ad, but can not play video.
When I click on play button on video, video box turn black, and nothing happens.
Videos are embedded from Brid.tv platform.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/20319032/191868782-e72b320d-8f4c-4024-b194-159f76a13ff1.png)

### uBlock Origin version

1.44.5b0

### Browser name and version

Mozilla Firefox for Ubuntu 104.0(64-bit)

### Settings

No changes.

**Comment by Procyon-b** [comment]
It works for me (chrome windows) with the default lists and with the `HUN: hufilter` list added.
