### ISSUE TITLE
netcine.to: breakage

### ISSUE THREAD

**Issue by luisseidel** [uBlockOrigin/uAssets#15003]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://netcine.to/`

### Category

breakage

### Describe the issue

The page load is very slow when uBlock Origin is enabled. About 2min to load it.

The same problem occurs in two different browsers:

My setup:
Manjaro Linux + KDE

Firefox 105.0 (64-bit) - via Snap
Microsoft Edge Version 105.0.1343.42 (Official build) (64-bit)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 83687
  cosmetic: 39535
  scriptlet: 17871
  html: 752
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33588-42, 2m
    ublock-badware: 4209-0, 2m
    ublock-privacy: 268-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1872-0, 2m
    ublock-quick-fixes: 247-0, 2m
    easylist: 62964-608, 2m
    easyprivacy: 30632-1705, 2m
    urlhaus-1: 6832-0, 2m
    plowe-0: 3673-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1380 ms
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    histats.com: 1
    inklinkor.com: 1
    rndskittytor.com: 1
    upgulpinon.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Caused by a filter in "uBlock filters".
Add this:
```
netcine.*#@#+js(abort-on-stack-trace, Math.random, /\st\.[a-zA-Z]*\s/)
```
