### ISSUE TITLE
uk.selfemployed.intuit.com: breakage

### ISSUE THREAD

**Issue by andonevris** [uBlockOrigin/uAssets#15007]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uk.selfemployed.intuit.com/login`

### Category

breakage

### Describe the issue

Cannot login to site when Ublock is activated, after filling credentials and submitting page does not proceed further.

Have tried manually allowing entries from ublock control panel but still cannot login.  

If I disable ublock I can login and once logged in I can re-enable ublock and everything works as expected, only login is the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 100269
  cosmetic: 179420
  scriptlet: 25471
  html: 763
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 4h.51m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt: 0-0, 2d.21h.28m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 4d.5h.48m
    https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt: 2675-9, never
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-37, 4d.5h.47m
    fanboy-thirdparty_social: 68-0, 2d.17h.20m
    fanboy-annoyance: 80577-64622, 2d.17h.19m
    fanboy-social: 23358-31, 20h.57m
    adguard-annoyance: 59343-5088, 2d.21h.29m
    fanboy-cookiemonster: 41066-151, 2d.17h.18m
    ublock-annoyances: 4844-10, 2d.21h.27m
    adguard-social: 18588-1088, 2d.21h.26m
  default: 
    user-filters: 398-3, never
    ublock-filters: 33512-185, 2d.21h.31m
    ublock-badware: 4204-0, 3d.17h.41m
    ublock-privacy: 267-0, 3d.13h.38m
    ublock-unbreak: 1869-4, 2d.21h.30m
    easylist: 63186-598, 2d.21h.23m
    easyprivacy: 30610-1778, 2d.21h.22m
    plowe-0: 3673-1729, 3d.13h.39m
    ublock-abuse: 76-0, 2d.13h.16m
    urlhaus-1: 7369-0, 4h.50m
filterset (user): [array of 398 redacted]
trustedset: 
  added: [array of 174 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 425 ms (selfie)
  maxAssetCacheWait: 603 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    intuit.com: 3
    googletagmanager.com: 1
    intuitcdn.net: 4
    online-metrix.net: 1
    segment.com: 1
    tiqcdn.com: 3
```
</details>

**Comment by mapx-** [comment]
- Reset uBO to default settings
- update all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- don't add any other new list
- test again

**Comment by andonevris** [comment]
Thanks for the reply, I had already tried all that but just did it again to verify, still seeing the same behaviour, page just hangs on "signing in"

**Comment by mapx-** [comment]
Use only the default filter lists and:

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
