### ISSUE TITLE
pay.send.cm - Credit Card input blocked

### ISSUE THREAD

**Issue by ALLNL** [uBlockOrigin/uAssets#15017]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pay.send.cm/subscribe/prices.php`

### Describe the issue

The input to enter the credit card details is blocked.

### Screenshot(s)

![2022-09-23_19h50_31](https://user-images.githubusercontent.com/35146278/192027556-0f81b5ba-6c8a-44a4-a6ed-a18ee626a2b1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83705
  cosmetic: 39539
  scriptlet: 17879
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62993-52, now
    easyprivacy: 30633-1170, now
    plowe-0: 3669-862, now
    ublock-abuse: 76-0, now
    ublock-badware: 4205-105, now
    ublock-filters: 32872-114, now
    ublock-privacy: 246-1, now
    ublock-quick-fixes: 243-9, never
    ublock-unbreak: 1859-42, now
    urlhaus-1: 6838-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1469 ms (selfie)
  maxAssetCacheWait: 358 ms
```
</details>

**Comment by okiehsch** [comment]
Update the uBO-unbreak list, it should work as expected after that.

**Comment by mapx-** [comment]
just remove it - does not serve anymore

**Comment by okiehsch** [comment]
All of them, or only that specific filter?

**Comment by mapx-** [comment]
it seems all of them

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0a1b1fe33e65fc6c4091ac60ecbaf170c4e8ba79

@ALLNL force update all your filter lists, click "Purge all caches" and then "Update now" in your filter lists pane.

**Comment by ghajini** [comment]
Not all of them
```
https://send.cm/d/F5uk
https://send.cm/g7nvcp7f7e83
```
full popups
![Screenshot_20220923-234946-714](https://user-images.githubusercontent.com/20338483/192033880-fb940905-5863-482e-9bb8-01228459c676.png)

**Comment by mapx-** [comment]
only mobile ?

**Comment by ghajini** [comment]
i will check other devices

**Comment by mapx-** [comment]
I get no popup using blueStacks

**Comment by ghajini** [comment]
opera/firefox a , UBO
```
https://send.cm/lkq3rx1e9n3r
https://send.cm/g7nvcp7f7e88
https://send.cm/d/F61F
https://send.cm/d/F5ui
```
filters
https://github.com/uBlockOrigin/uAssets/commit/c40e0636c05cb79198b474c6f7bf1dd69d8c2f20
https://github.com/uBlockOrigin/uAssets/commit/74910e49784a94aaf102fafc73d52dc9c164473c
