### ISSUE TITLE
Can't open any link on the website www.jd.com

### ISSUE THREAD

**Issue by btcoolboy** [uBlockOrigin/uAssets#15016]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Can't open any link on the website www.jd.com, the issue will be restored after disabling the uBlock.

### A specific URL where the issue occurs.

www.jd.com

### Steps to Reproduce

click link on the www.jd.com

### Expected behavior

open the link.

### Actual behavior

can't open any link.

### uBO version

1.44.4

### Browser name and version

firefox 105.0 

### Operating System and version

deepin 20.7

**Comment by mapx-** [comment]
already fixed https://github.com/uBlockOrigin/uAssets/commit/3768a04a2e19c59b724b775f4cc1046e1c74b37d
