### ISSUE TITLE
adshorte.com [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1502]
URL(s) where the issue occurs

`http://adshorte.com/Xau4fP`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
@mapx- fill the Captcha and then continue link    the video shows advertising

**Comment by KiLL4FuNK** [comment]
Pop-up @mapx-

**Comment by KiLL4FuNK** [comment]
@mapx- ?
![](https://i.imgur.com/ProN5Gp.png)

**Comment by mapx-** [comment]
open a new issue for different site

**Comment by KiLL4FuNK** [comment]
adshorte.com

the page died you can remove the filters
