### ISSUE TITLE
clamor.pl: [detection]

### ISSUE THREAD

**Issue by genuinejanbar** [uBlockOrigin/uAssets#15028]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://clamor.pl/2022/03/19/alina-makarczuk-kariera-wiek-partner/`

### Category

[detection]

### Describe the issue

That site just recognized uBlockOriginal and demand it off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 84932
  cosmetic: 47382
  scriptlet: 18069
  html: 768
listset (total-discarded, last updated): 
  added: 
    https://github.com/olegwukr/polish-privacy-filters/blob/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e/adblock-suplement.txt: 0-0, never
    https://github.com/olegwukr/polish-privacy-filters/blob/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e/adblock.txt: 0-0, never
    https://github.com/olegwukr/polish-privacy-filters/blob/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e/anti-adblock-suplement.txt: 0-0, never
    https://github.com/olegwukr/polish-privacy-filters/blob/fc363cd3115ca0c78d8ee60143bf1b8c2a29152e/anti-adblock.txt: 0-0, never
  default: 
    user-filters: 12-1, never
    ublock-filters: 33590-81, 6h.17m
    ublock-badware: 4184-0, 6h.16m
    ublock-privacy: 268-0, 1d.7h.47m
    ublock-abuse: 76-0, 1d.7h.46m
    ublock-unbreak: 1872-0, 6h.15m
    easylist: 63265-623, 4d.19h.50m
    easyprivacy: 30610-1704, 4d.19h.48m
    urlhaus-1: 6838-0, 19h.58m
    plowe-0: 3674-3, 13d.1h.49m
    POL-0: 7857-25, 19h.57m
    POL-2: 1279-12, 6h.14m
    ublock-quick-fixes: 237-0, 19h.59m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 53971 ms (selfie)
  maxAssetCacheWait: 7535 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    dqst.pl: 2
    exs.pl: 2
    google.com: 4
    googlesyndication.com: 10
    googletagmanager.com: 3
    taboola.com: 1
```
</details>

**Comment by Procyon-b** [comment]
I can reproduce.

Try this filter:
```
clamor.pl##+js(no-fetch-if, dqst.pl)
```

if this doesn't work, try this one:
```
*$xhr,redirect-rule=noop.txt,domain=clamor.pl
```
