### ISSUE TITLE
could not load manifest

### ISSUE THREAD

**Issue by bjm234** [uBlockOrigin/uAssets#15024]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Issue posted on Wilders
https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-268#post-3106237
any CNN video:
for example:
https://www.cnn.com/2022/09/23/politics/stephen-breyer-exclusive-interview-cnntv/index.html

### Describe the issue

<img width="599" alt="png_15868" src="https://user-images.githubusercontent.com/25015553/192048872-1026d0be-6cd3-4fe5-ad70-0c31e97324ef.png">

### Screenshot(s)

link to Wilders post
https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-268#post-3106237

### uBlock Origin version

uBlock Origin 1.44.4

### Browser name and version

Edge Version 105.0.1343.50 (Official build) (64-bit)

### Settings

none

### Notes

~ disable Built-in - uBlock filters allows ad to play before video - then video plays

**Comment by sugarfreesweetener** [comment]
Have you updated the filters?

**Comment by mapx-** [comment]
fixed today
https://github.com/uBlockOrigin/uAssets/commit/fded2671526fc0f9e24db92ffe33313bd3744d08

**Comment by bjm234** [comment]
So, we have to see the ad now?
We used to not see the ad.

**Comment by mapx-** [comment]
It was broken, now is fixed. 
The ads are other issue.

**Comment by bjm234** [comment]
Oh okay.  
Thanks

**Comment by mapx-** [comment]
the ads: it's about SSAI (yospace SSAI - [Server-Side Ad Insertion](https://aws.amazon.com/media/tech/what-server-side-ad-insertion-ssai/), the removed filter worked for a while removing a SSAI parameter but obviously they improved the SSAI process.

**Comment by bjm234** [comment]
Switching from EasyList to AdGuard Base helps.
No ad - just video.

**Comment by bjm234** [comment]
Switched back to my Easy filters.  
No ad - just video.
Thanks
