### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by etdasGSD** [uBlockOrigin/uAssets#15030]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/`

### Category

breakage

### Describe the issue

It gets to an ad and hulu just completely stops working, I don't know whats wrong with it or if i even filled out the right category.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 83460
  cosmetic: 39839
  scriptlet: 17830
  html: 749
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33493-37, 3d.22h.54m
    ublock-badware: 4204-0, 3d.22h.53m
    ublock-privacy: 268-0, 3d.19h.30m
    ublock-abuse: 76-0, 3d.19h.29m
    ublock-unbreak: 1869-0, 3d.22h.52m
    easylist: 63219-607, 3d.22h.50m
    easyprivacy: 30615-1705, 3d.22h.48m
    urlhaus-1: 6720-0, 5h.55m
    plowe-0: 3673-3, 3d.19h.28m
    ublock-quick-fixes: 252-0, 5h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 365 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    hulu.com: 11
    ads-twitter.com: 1
    akadns.net: 1
    conviva.com: 4
    demdex.net: 1
    google-analytics.com: 1
    scorecardresearch.com: 1
    yimg.com: 2
```
</details>

**Comment by mapx-** [comment]
Do you still get the breakage disabling the scriptlets ?

add & test
`hulu.com#@#+js()`

**Comment by shaggysnorlax** [comment]
This solution seems to fix the site functionality and block the ad media from loading, but the ad overlay/timer will still load and count down (unskippable)

**Comment by mapx-** [comment]
Could you test again after updating uBO filters list ? (in 5-10 min)
