### ISSUE TITLE
cpu-world.com: detection

### ISSUE THREAD

**Issue by NinjaLooterGeno** [uBlockOrigin/uAssets#15039]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cpu-world.com/index.html`

### Category

detection

### Describe the issue

after looking up 5 or so cpus it started blocking most information and displayed the message.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Annotation 2022-09-25 191746](https://user-images.githubusercontent.com/62000764/192156469-e4f346b1-a2b8-46e8-a429-19dfd23a078e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 85728
  cosmetic: 42922
  scriptlet: 17898
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    DEU-0: 5947-0, 2m
    easylist: 62616-57, 2m
    easyprivacy: 30636-1180, 2m
    plowe-0: 3670-864, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4180-105, 2m
    ublock-filters: 32896-126, 2m
    ublock-privacy: 249-1, 2m
    ublock-quick-fixes: 248-5, 2m
    ublock-unbreak: 1859-43, 2m
    urlhaus-1: 6707-0, 2m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 894 ms
  maxAssetCacheWait: 429 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cpu-world.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. Workaround: Clear the cookies from this site.
