### ISSUE TITLE
careers.manor.ch: breakage

### ISSUE THREAD

**Issue by Lauykk** [uBlockOrigin/uAssets#15038]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://careers.manor.ch/fr/offres-d-emploi/postes-vacants`

### Category

breakage

### Describe the issue

clearing all the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 125872
  cosmetic: 135930
  scriptlet: 36701
  html: 771
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 70067-5397, 1d.17h.30m
    adguard-annoyance: 59498-785, 1d.17h.30m
    ublock-annoyances: 4849-4, 1d.17h.30m
  default: 
    user-filters: 40-8, never
    ublock-filters: 33584-43, 3d.2h.4m
    ublock-badware: 4204-0, 3d.2h.3m
    ublock-privacy: 268-0, 3d.2h.8m
    ublock-abuse: 76-0, 23h.2m
    ublock-unbreak: 1872-0, 3d.2h.2m
    easylist: 62953-1526, 3d.2h
    easyprivacy: 30632-2005, 3d.1h.59m
    urlhaus-1: 6720-0, 22h.59m
    plowe-0: 3670-3, 23h.1m
    FRA-0: 30805-181, 3d.2h.7m
    ublock-quick-fixes: 247-0, 23h
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3048 ms (selfie)
  maxAssetCacheWait: 1636 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
> ```yaml
>     user-filters: 40-8, never
> ```

Could you disable this list temporarily if you haven't already?

**Comment by mapx-** [comment]
@Lauykk you should reset uBO to default settings lists, then update all lists and test again
