### ISSUE TITLE
hulu.com: detection

### ISSUE THREAD

**Issue by mufffffin56** [uBlockOrigin/uAssets#15031]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/watch/f3cee512-c5e1-4537-bedb-180e46f271cf`

### Category

detection

### Describe the issue

site suddenly stops playing at first ad, black screen. I think it detects origin, normally hulu works absolutely fine 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 84206
  cosmetic: 39846
  scriptlet: 17887
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63165-52, 4d.19h.37m
    easyprivacy: 30635-1170, 1h.6m
    plowe-0: 3674-861, 10d.7h.28m
    ublock-abuse: 76-0, 11d.20h.9m
    ublock-badware: 4180-105, 5h.8m
    ublock-filters: 32878-111, 1h.5m
    ublock-privacy: 246-1, 11d.20h.10m
    ublock-quick-fixes: 248-5, 20h.2m
    ublock-unbreak: 1860-42, 1h.4m
    urlhaus-1: 7479-0, 20h.1m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5976 ms (selfie)
  maxAssetCacheWait: 580 ms
popupPanel: 
  blocked: 40
  blockedDetails: 
    hulu.com: 23
    ads-twitter.com: 1
    conviva.com: 2
    demdex.net: 5
    google-analytics.com: 1
    innovid.com: 1
    omtrdc.net: 6
    yimg.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate: https://github.com/uBlockOrigin/uAssets/issues/15030

see this comment and test that filter
https://github.com/uBlockOrigin/uAssets/issues/15030#issuecomment-1257063179

respond in that thread
