### ISSUE TITLE
chitrajyothy.com: breakage

### ISSUE THREAD

**Issue by anilatluri** [uBlockOrigin/uAssets#15035]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chitrajyothy.com/telugunews/vijay-deverakonda-refuses-to-answer-question-related-to-jana-gana-mana-jay-spl-mrgs-chitrajyothy-1822091107115631`

### Category

breakage

### Describe the issue

When I tried to read / text alone / immersive read mode Vivaldi failed to display the text content of the page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 84188
  cosmetic: 39857
  scriptlet: 17887
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63190-52, 4d.18h.42m
    easyprivacy: 30615-1171, 4d.18h.40m
    plowe-0: 3674-861, 10d.19h.4m
    ublock-abuse: 76-0, 10d.19h.7m
    ublock-badware: 4180-105, 18h.12m
    ublock-filters: 32881-111, 18h.11m
    ublock-privacy: 245-1, 10d.19h.6m
    ublock-quick-fixes: 248-5, 1h.17m
    ublock-unbreak: 1859-42, 18h.13m
    urlhaus-1: 7469-0, 1h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10296 ms (selfie)
  maxAssetCacheWait: 827 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
I tested the page using edge immersive reader => all fine on my side

Did you disable vivaldi adblocker ?
