### ISSUE TITLE
wcoforever.net: detection

### ISSUE THREAD

**Issue by Grimmkey** [uBlockOrigin/uAssets#15036]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wcoforever.net/one-piece-episode-1034-english-subbed`

### Category

detection

### Describe the issue

Video is interrupted after a few seconds with or without activation by a red screen showing "AdBlock Detected", believe it is due to a Google_jobrunner timeout.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/114345886/192146781-f7315945-ad1b-4f8c-81ec-d0694bf46a14.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 84235
  cosmetic: 39080
  scriptlet: 17820
  html: 752
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 33601-117, 2h.50m
    ublock-badware: 4184-0, 2h.50m
    ublock-privacy: 268-0, 2h.50m
    ublock-abuse: 76-0, 2h.50m
    ublock-unbreak: 1872-0, 2h.50m
    easylist: 62612-524, 2h.50m
    easyprivacy: 30636-1706, 2h.50m
    urlhaus-1: 7469-0, 2h.50m
    plowe-0: 3670-3, 2h.50m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 163 ms (selfie)
  maxAssetCacheWait: 50 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google.com: 1
```
</details>

**Comment by sugarfreesweetener** [comment]
`wcoforever.net##+js(set, isAdBlockActive, false)`

**Comment by Grimmkey** [comment]
Perfect, thanks for the solve!
