### ISSUE TITLE
shrink-service.it [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1503]
URL(s) where the issue occurs

`http://www.shrink-service.it/s/gSd1CS`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.24

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by SkeletalDemise** [comment]
Hm. This site also has coinhive on it, under this script, `https://shrink-service.it/js/cM.js`.

**Comment by xDarkARG** [comment]
If it is already solved they can close the topic

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Popups, Timer.

**Comment by okiehsch** [comment]
The popup is blocked by `||oclaserver.com^$popup` and I can't disable the trigger without breaking the "skip" button.
