### ISSUE TITLE
nytimes.com: nuisance

### ISSUE THREAD

**Issue by godfatherjohn** [uBlockOrigin/uAssets#15041]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nytimes.com/2022/09/23/us/politics/putin-ukraine.html`

### Category

nuisance

### Describe the issue

The page progressively 'dims/darkens' until it is completely black when scrolling down.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 145519
  cosmetic: 150451
  scriptlet: 22070
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 29204-86, 1d.19h.9m
    FRA-0: 30805-61, 2d.19h.43m
    RUS-0: 42215-222, 6h.40m
    adguard-annoyance: 59499-424, 1d.19h.8m
    adguard-social: 18645-895, 1d.19h.7m
  default: 
    user-filters: 275-2, never
    easylist: 63265-1066, 6d.4h.22m
    easyprivacy: 30609-1652, 6d.4h.21m
    plowe-0: 3673-879, 6d.23h.25m
    ublock-abuse: 76-2, 8d.3h.39m
    ublock-badware: 4205-115, 2d.2h.33m
    ublock-filters: 32870-668, 2d.2h.32m
    ublock-privacy: 245-3, 8d.3h.38m
    ublock-quick-fixes: 233-9, 23h.48m
    ublock-unbreak: 1859-45, 2d.2h.31m
    urlhaus-1: 6720-0, 23h.47m
filterset (user): [array of 275 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 725 ms (selfie)
  maxAssetCacheWait: 629 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    nytimes.com: 7
    googletagmanager.com: 1
    nyt.com: 1
```
</details>

**Comment by gwarser** [comment]
Paywall 
![image](https://user-images.githubusercontent.com/886325/192198436-1655258f-4ed8-40b1-93eb-f68df5fd4cbd.png)

**Comment by dportvine** [comment]
https://github.com/easylist/easylist/commit/213ed83ef482e753b0001542ee721261ad7951e6
