### ISSUE TITLE
community.openstreetmap.org: breakage

### ISSUE THREAD

**Issue by nukeador** [uBlockOrigin/uAssets#15043]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://community.openstreetmap.org/`

### Category

breakage

### Describe the issue

There is a generic filter by EasyList

> openstreetmap.org###banner

That is causing the community forum notice banner to be blocked. This is a default banner element from the Discourse software and it's used to display important announcements to the community.

Also reported here:

https://github.com/easylist/easylist/issues/13517

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

The blue banner is being blocked

![image](https://user-images.githubusercontent.com/531906/192254336-b2c3d7be-36e5-4ae3-83f9-48a7b9e5c086.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 91770
  cosmetic: 97591
  scriptlet: 24117
  html: 779
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59520-772, 45m
    ublock-annoyances: 4853-4, 50m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33640-86, 48m
    ublock-badware: 4184-0, 47m
    ublock-privacy: 273-0, 53m
    ublock-abuse: 76-0, 52m
    ublock-unbreak: 1872-0, 46m
    easylist: 63187-687, 5d.20h.37m
    easyprivacy: 30615-1721, 5d.20h.35m
    urlhaus-1: 7407-0, 44m
    plowe-0: 3670-3, 54m
    ublock-quick-fixes: 252-0, 42m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 24 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2042 ms (selfie)
  maxAssetCacheWait: 1319 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
wait the fix in EL list
