### ISSUE TITLE
startribune.com: ads

### ISSUE THREAD

**Issue by jhnmdahl** [uBlockOrigin/uAssets#15046]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.startribune.com/minnesota-techies-suggest-ways-to-get-more-value-from-your-smartphone/600210137/`

### Category

ads

### Describe the issue

ad pops over displayed content.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 80435
  cosmetic: 45243
  scriptlet: 17647
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33207-138, never
    ublock-badware: 4237-0, never
    ublock-privacy: 247-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1871-0, never
    ublock-quick-fixes: 386-0, never
    easylist: 69310-491, never
    easyprivacy: 27312-594, never
    urlhaus-1: 5164-0, never
    plowe-0: 3634-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 285 ms
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    startribune.com: 5
    amazon-adsystem.com: 1
    bugsnag.com: 7
    chartbeat.com: 2
    clarium.global.ssl.fastly.net: 1
    cloudflareinsights.com: 2
    dc8xl0ndzn2cb.cloudfront.net: 2
    googleoptimize.com: 2
    googletagmanager.com: 2
    ntv.io: 1
    optimizely.com: 2
    outbrain.com: 1
    quantserve.com: 2
    scorecardresearch.com: 1
    zeustechnology.com: 1
```
</details>

**Comment by mapx-** [comment]
I see no ad.

Just for testing (the page has a paywall overlay) I added:

```
startribune.com##.ReactModal__Overlay:has-text(Subscribe)
startribune.com##body:style(overflow: auto !important;)
```
and .. no ad on my end

Provide a screenshot showing the ads

**Comment by jhnmdahl** [comment]
mapx - apologies for not recognizing the distinction between a paywall overlay and other ads - I just read the Washington Post ad v. paywall debate.  With the rules you posted in place, there are no ads/overlays of any type.
