### ISSUE TITLE
nytimes.com: nuisance

### ISSUE THREAD

**Issue by evanxcs** [uBlockOrigin/uAssets#15052]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nytimes.com/2022/09/25/science/nasa-dart-asteroid.html`

### Category

nuisance

### Describe the issue

NYT articles now have a "Thanks for reading the The Times - Create your free account or log in to continue reading" overlay for articles that is evading uBO, at least with how I have it configured and after trying several adjustments, including those listed above in the prerequisites (to the best of my limited abilities).  I tried zapping and using element picker, but, while it removes the overlay, the article remains "dimmed" and scrolling to read the article does not work.

See screenshot below.

Thank you!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Screenshot of the "Thanks for reading the The Times - Create your free account or log in to continue reading" overlay.

![uBlock - NYT nuissance](https://user-images.githubusercontent.com/12414218/192434479-64d66add-ecb1-4b29-b149-3d2db9b94192.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 104
filterset (summary): 
  network: 95029
  cosmetic: 160325
  scriptlet: 25439
  html: 774
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59567-4197, 4m
    fanboy-annoyance: 80650-41307, 4m
    fanboy-cookiemonster: 41121-134, 4m
    ublock-annoyances: 4853-4, 4m
  default: 
    user-filters: 38-6, never
    ublock-filters: 33648-47, 4m
    ublock-badware: 4189-0, 4m
    ublock-privacy: 273-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1872-0, 4m
    easylist: 62449-624, 4m
    easyprivacy: 30639-1708, 4m
    urlhaus-1: 6708-0, 4m
    plowe-0: 3670-3, 4m
filterset (user): [array of 38 redacted]
trustedset: 
  added: [array of 29 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 178 ms (selfie)
  maxAssetCacheWait: 823 ms
  unsuspendAfter: 34 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    nytimes.com: 21
    amazon-adsystem.com: 1
    geoedge.be: 1
    go-mpulse.net: 2
    googletagmanager.com: 1
    nyt.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
If you want to bypass the paywall, test

```adb
||meter-svc.nytimes.com/meter.js$script,xhr,1p
```

**Comment by evanxcs** [comment]
I believe that worked!  Thank you!
