### ISSUE TITLE
pixabay.com: ads

### ISSUE THREAD

**Issue by ZStud** [uBlockOrigin/uAssets#15050]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pixabay.com/images/search/cheese/?manual_search=1`

### Category

ads

### Describe the issue

This whole website has a built in ad/sponsor at the top of the page, ie iStock. Though this only occurs when I search for an image.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 83559
  cosmetic: 39363
  scriptlet: 17894
  html: 757
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33632-38, 22h.19m
    ublock-badware: 4184-0, 22h.18m
    ublock-privacy: 267-0, 8d.13h.31m
    ublock-abuse: 76-0, 8d.13h.30m
    ublock-unbreak: 1872-0, 3h.2m
    ublock-quick-fixes: 252-0, 18h.17m
    easylist: 62787-608, 2d.2h.25m
    easyprivacy: 30635-1705, 2d.2h.23m
    urlhaus-1: 6707-0, 18h.16m
    plowe-0: 3673-3, 8d.13h.28m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2602 ms (selfie)
  maxAssetCacheWait: 1489 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`pixabay.com##.present-gtty-item:has([data-ad-source])`

@ryanbr
