### ISSUE TITLE
[nsfw] dev2411.d2ne88j2zeex7b.amplifyapp.com: popups

### ISSUE THREAD

**Issue by sumshr** [uBlockOrigin/uAssets#15057]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dev2411.d2ne88j2zeex7b.amplifyapp.com/`

### Category

popups

### Describe the issue

Appears automatically

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83593
  cosmetic: 39013
  scriptlet: 17884
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62462-52, 1d.33m
    easyprivacy: 30639-1170, 1d.31m
    plowe-0: 3674-861, 11d.8h.15m
    ublock-abuse: 76-0, 2d.20h.53m
    ublock-badware: 4205-105, 4d.1h.46m
    ublock-filters: 32879-114, 4d.1h.45m
    ublock-privacy: 246-1, 2d.20h.52m
    ublock-quick-fixes: 248-5, 17h.6m
    ublock-unbreak: 1860-42, 4d.1h.44m
    urlhaus-1: 6708-0, 17h.5m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 311 ms (selfie)
  maxAssetCacheWait: 108 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
From which site you got this popup? We need the site which opens the popup not the pupup site itself

**Comment by thecandylane** [comment]
My dad has ran into this same issue, did you find any way to see what it is and disable it ?

**Comment by ghajini** [comment]
Provide feedback about this

https://github.com/uBlockOrigin/uAssets/issues/15057#issuecomment-1259321531
