### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by bendiaz** [uBlockOrigin/uAssets#15068]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/hub/home`

### Category

breakage

### Describe the issue

Players stop working altogether when UBO is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 84187
  cosmetic: 39079
  scriptlet: 17823
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62616-52, 2d.8h.39m
    easyprivacy: 30636-1170, 2d.8h.38m
    plowe-0: 3670-863, 2d.18h.45m
    ublock-abuse: 76-0, 9d.19h.19m
    ublock-badware: 4185-105, 19h.57m
    ublock-filters: 32880-114, 19h.56m
    ublock-privacy: 245-1, 9d.19h.18m
    ublock-unbreak: 1859-42, 19h.55m
    urlhaus-1: 7422-0, 19h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1632 ms (selfie)
  maxAssetCacheWait: 665 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    hulu.com: 12
    ads-twitter.com: 1
    adsrvr.org: 1
    conviva.com: 8
    demdex.net: 1
    facebook.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    krxd.net: 1
    sc-static.net: 1
    scorecardresearch.com: 2
    tealiumiq.com: 1
    tiktok.com: 1
    yimg.com: 1
```
</details>

**Comment by mufffffin56** [comment]
Hulu isn't working for me either I tried your suggestion of the filters. 

Hulu is not working for uorigin please fix it it's been over a week now

**Comment by mufffffin56** [comment]
The second filter you mentioned to add, still makes ads pop up and you have to sit the whole time with a black screen saying ads are blocked. 

U origin is not working on hulu

**Comment by mufffffin56** [comment]
no it doesnt, normally it SKIPS the ads completely. If I'm sitting staring at a blank screen for 2 minutes that;'s not skipping ads it's still adding the time slot for them. Before  hulu was skipping them completely fine it just suddenly stopped a week ago.

**Comment by mapx-** [comment]
@mufffffin56 the issue was about breakage and it's nopt broken anymore, right ?

Now, for the ads we need an account to investigate if there is a chance to block the ads.

**Comment by mufffffin56** [comment]
It is broken.... it didn't fix the issue.

**Comment by mapx-** [comment]
@mufffffin56 

Remove the filters above, open uBO logger, play again a hulu video.

You should check in uBO logger if you see:

`hulu.com##+js(set, Object.prototype.isAdPeriod, falseFunc)`
