### ISSUE TITLE
1.44.5b4 has a problem

### ISSUE THREAD

**Issue by Wolf2024** [uBlockOrigin/uAssets#15067]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://outlook.live.com/
https://smile.amazon.com/
```

### Describe the issue

on 27 September 2022 tried accessing my e-mail accounts (all 4 of them) on outlook  - outlook opened correctly but gave a blank page instead of my e-mails (a white page)  with the `https://outlook.live.com/mail/0` on the address line - never proceeded to the inbox page.  Checked to see if outlook was down (no), reset my router (no fix) cleared my chache (no help) -- only when ublock was turned off did the page load.

At 1430hr tried doing a product search on Amazon - Amazon would load correct, momentarily flash the product I was looking for then the product listing would go blank (the rest of Amazon was visible and active, only the product searches were blocked

### Screenshot(s)

![image](https://user-images.githubusercontent.com/114528783/192628797-e92329da-1d12-4159-befc-dd2980d94d50.png)

### Notes

Reset cache
reset router
turned off other ad blockers

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b4
Chromium: 105
filterset (summary): 
  network: 84285
  cosmetic: 39213
  scriptlet: 17895
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 53-7, never
    easylist: 62616-52, 2d.3h.43m
    easyprivacy: 30636-1170, 2d.3h.41m
    plowe-0: 3672-861, 11d.5h.52m
    ublock-abuse: 76-0, 11d.20h.20m
    ublock-badware: 4185-105, 1d.3h.55m
    ublock-filters: 32882-114, 1d.3h.54m
    ublock-privacy: 245-1, 11d.20h.19m
    ublock-quick-fixes: 260-5, 16h.22m
    ublock-unbreak: 1859-42, 7h.48m
    urlhaus-1: 7422-0, 16h.21m
filterset (user): [array of 53 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 623 ms (selfie)
  maxAssetCacheWait: 103 ms
```
</details>

**Comment by mapx-** [comment]
unfortunately google still didn't review b6, so:

- switch to uBO stable
or
- disable cosmetic filters

**Comment by mapx-** [comment]
just update uBO => 1.44.5b6
