### ISSUE TITLE
blocked.goguardian.com: popups

### ISSUE THREAD

**Issue by GoofyGopherUnoDosTres** [uBlockOrigin/uAssets#15063]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blocked.goguardian.com/teacher/block.html?ctx=b2k9MjIxNzUyOTI0NTQmb3U9aHR0cHMlM0ElMkYlMkZ3d3cuZ29vZ2xlLmNvbSUyRnNlYXJjaCUzRnElM0ROT05PTk9OT05PTk8lMkJtZW1lJTI2cmx6JTNEMUNBRU9FV19lblVTMTAwMiUyNm9xJTNETk9OT05PTk9OT05PJTJCbWVtZSUyNmFxcyUzRGNocm9tZS4uNjlpNTcuMTQ5OTRqMGo3JTI2c291cmNlaWQlM0RjaHJvbWUlMjZpZSUzRFVURi04JTI2c2FmZSUzRGFjdGl2ZSUyNnNzdWklM0RvbiZycz1URUFDSEVSX1NDRU5FJnN0PWNocm9taXVtLW0mdHNpPTEwNTA5OTAmdj0x&sum=73e60365`

### Category

popups

### Describe the issue

Im attempting to open up Google Classroom on google chrome, and I keep getting GoGuardian popups.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-09-27 11 53 24 AM](https://user-images.githubusercontent.com/114506551/192575960-5c0ed6c5-49c1-48bb-9022-1bb02e923ca4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 83432
  cosmetic: 39886
  scriptlet: 17907
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63190-52, 6d.22h.28m
    easyprivacy: 30615-1171, 6d.22h.27m
    plowe-0: 3670-862, 22h.12m
    ublock-abuse: 76-0, 22h.15m
    ublock-badware: 4185-105, 22h.11m
    ublock-filters: 32930-111, 22h.10m
    ublock-privacy: 249-1, 22h.14m
    ublock-quick-fixes: 248-5, 22h.8m
    ublock-unbreak: 1859-42, 22h.9m
    urlhaus-1: 6708-0, 22h.7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4361 ms (selfie)
  maxAssetCacheWait: 2271 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
`Empower teachers with greater classroom control and student monitoring capabilities with GoGuardian Teacher, a classroom management software`

Maybe you navigated some avoided page.
Do you get the same page even disabling uBO ?

**Comment by krystian3w** [comment]
`&ou=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3DNONONONONONO%2Bmeme%26rlz%3D1CAEOEW_enUS1002%26oq%3DNONONONONONO%2Bmeme%26aqs%3Dchrome..69i57.14994j0j7%26sourceid%3Dchrome%26ie%3DUTF-8%26safe%3Dactive%26ssui%3Don&rs=TEACHER_SCENE&`
