### ISSUE TITLE
[nsfw] a.maincaptcha.top: popups

### ISSUE THREAD

**Issue by twodragon** [uBlockOrigin/uAssets#15066]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://a.maincaptcha.top/robot4/?c=c6e6cce1-fe46-45bf-bf16-cd74122c91a7&a=l19070`

### Category

popups

### Describe the issue

plase block this scam site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 213867
  cosmetic: 173517
  scriptlet: 35732
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59509-85, 2d.2m
    adguard-generic: 70072-511, 2d.2m
    adguard-mobile: 8143-45, 2d.2m
    curben-phishing: 92806-0, 22h.43m
    curben-pup: 193-1, 22h.42m
    dpollock-0: 11389-120, 2d.1m
    fanboy-cookiemonster: 41113-3075, 2d.2m
  default: 
    user-filters: 25-0, never
    TUR-0: 9258-14, 2d.2m
    easylist: 62616-1213, 2d.2m
    easyprivacy: 30636-1499, 2d.2m
    plowe-0: 3670-1333, 2d.2m
    ublock-abuse: 76-0, 2d.2m
    ublock-badware: 4180-337, 2d.2m
    ublock-filters: 32899-3998, 2d.2m
    ublock-privacy: 249-1, 2d.2m
    ublock-quick-fixes: 248-17, 22h.45m
    ublock-unbreak: 1859-84, 2d.2m
    urlhaus-1: 6708-1, 22h.44m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 544 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    p-analytics.life: 1
```
</details>

**Comment by twodragon** [comment]
sure > https://pasticceriaromanord.it/139989.html

**Comment by mapx-** [comment]
`https://pasticceriaromanord.it/139989.html` another scam site ?

**Comment by twodragon** [comment]
After searching on google, this domain is at the top with a different title.
example: https://www.google.com/search?q=asphalt+9+direksiyon+seti&sxsrf=ALiCzsaaWDvyXVIQMcEB1qwOvadGqyTXIw:1664302370983&ei=Ij0zY6nOO_O3xc8Prc-g2A8&start=10&sa=N&ved=2ahUKEwip5_u8ybX6AhXzW_EDHa0nCPsQ8tMDegQIAhBA&biw=1536&bih=722&dpr=1.25

**Comment by twodragon** [comment]
first of all thank you for solving my problem. i saw the problem was fixed and ublock blocked it

my screen:
https://i.ibb.co/rcXzp3W/image.png
