### ISSUE TITLE
seznam.cz: ads

### ISSUE THREAD

**Issue by marcelpetran** [uBlockOrigin/uAssets#15060]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Describe the issue

Ads on this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

`https://user-images.githubusercontent.com/55630402/192548942-f213434a-4e2f-47d3-a77f-1b5e579be399.png`

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83530
  cosmetic: 39403
  scriptlet: 18070
  html: 0
listset (total-discarded, last updated): 
  added: 
    CZE-0: 724-0, 6h.35m
  default: 
    user-filters: 1-0, never
    easylist: 62229-54, 44m
    easyprivacy: 30636-1175, 1d.17h.47m
    plowe-0: 3673-862, 4d.19h.1m
    ublock-abuse: 76-0, 8d.19h.26m
    ublock-badware: 4180-105, 17h.39m
    ublock-filters: 32928-116, 17h.38m
    ublock-privacy: 245-1, 8d.19h.23m
    ublock-quick-fixes: 260-5, 43m
    ublock-unbreak: 1859-42, 17h.37m
    urlhaus-1: 6708-0, 21h.40m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 432 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    seznam.cz: 8
    adnxs.com: 1
    gemius.pl: 2
    mathtag.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@addisr

**Comment by mapx-** [comment]
add

```
seznam.cz##[data-dot="gadgetCommercial"]
seznam.cz##[class*="advert"]
```

**Comment by marcelpetran** [comment]
Added and fixed, thank you
