### ISSUE TITLE
blog.insurancegold.in: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15071]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blog.insurancegold.in/detected.html`

### Category

detection

### Describe the issue

Detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 84942
  cosmetic: 27496
  scriptlet: 17941
  html: 758
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33752-294, 1d.14h.14m
    ublock-badware: 4188-0, 1d.14h.13m
    ublock-privacy: 268-1, 5d.15h.22m
    ublock-abuse: 76-0, 5d.15h.22m
    ublock-unbreak: 1877-0, 1d.14h.12m
    ublock-quick-fixes: 220-0, 10h.31m
    adguard-mobile: 8147-168, 1d.14h.11m
    easylist: 62953-19002, 5d.15h.22m
    easyprivacy: 30632-1715, 5d.15h.22m
    urlhaus-1: 6692-0, 10h.30m
    plowe-0: 3673-3, 5d.15h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1204 ms (selfie)
  maxAssetCacheWait: 233 ms
  unsuspendAfter: 888 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    arc.io: 1
    criteo.net: 1
    d3u598arehftfk.cloudfront.net: 2
    darghinruskin.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    quantserve.com: 1
    sentry-cdn.com: 1
    themoneytizer.com: 2
    udmserve.net: 2
    wtg-ads.com: 2
```
</details>

**Comment by mapx-** [comment]
`*$script,redirect-rule=noopjs,domain=insurancegold.in`
