### ISSUE TITLE
weather.com ads

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#15077]
### Discussed in https://github.com/uBlockOrigin/uAssets/discussions/15076

<div type='discussions-op-text'>

<sup>Originally posted by **cmcjsrb** September 28, 2022</sup>
weather.com ads showing again--have done purge of cache--update--they still show--once again can you help?</div>

**Comment by mapx-** [comment]
- Provide info (from dashboard, support tab, Troubleshooting Information)
- What ads ? screenshot + specific page link ?

**Comment by cmcjsrb** [comment]
sorry to say--that didn't help--still does the same thing--any other suggestions I could try

**Comment by mapx-** [comment]
It's fixed, update again all your lists and use default settings / lists

**Comment by cmcjsrb** [comment]
1st   never had a problem before--so I don't know what gives
 running the latest FF--3 different profiles for us--no problem with ublock on any other site except weather.com--and I'm not a novice with computers--did all the suggestions on all 3 profiles--nothing worked until I added this from what I got at reddit ublock

||amazon-adsystem.com^$important,script,redirect-rule=noopjs,domain=weather.com

this got it to work--don't know what to say

**Comment by DUSlider** [comment]
> 1st never had a problem before--so I don't know what gives running the latest FF--3 different profiles for us--no problem with ublock on any other site except weather.com--and I'm not a novice with computers--did all the suggestions on all 3 profiles--nothing worked until I added this from what I got at reddit ublock
> 
> ||amazon-adsystem.com^$important,script,redirect-rule=noopjs,domain=weather.com
> 
> this got it to work--don't know what to say

The line posted above fixed this for me as well. Without the line, ublock doesn't allow videos to play on weather.com even after resetting everything to defaults and updating everything.

**Comment by stephenhawk8054** [comment]
> The line posted above fixed this for me as well. Without the line, ublock doesn't allow videos to play on weather.com even after resetting everything to defaults and updating everything.

Can you give exact sample URL? I click on some videos and they play fine for me

<details>

![image](https://user-images.githubusercontent.com/66517106/193701570-98d48c74-c995-480d-bb5d-067543213dc2.png)

</details>

**Comment by DUSlider** [comment]
> > The line posted above fixed this for me as well. Without the line, ublock doesn't allow videos to play on weather.com even after resetting everything to defaults and updating everything.
> 
> Can you give exact sample URL? I click on some videos and they play fine for me

This one does not work until I put the entry mention above in the Ublock MyFilters section

https://weather.com/storms/hurricane/video/hurricane-ian-changes-appearance-of-gulf-of-mexico

**Comment by stephenhawk8054** [comment]
Sorry I still cannot reproduce the issue. That's the same URL as in the screenshot I posted above. 

Maybe it's geo-related. Which region are you when using the site? Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by DUSlider** [comment]
Verizon FIOS, ISP in Mid-Atlantic region. Also tried VPN for other parts of the country (West, central and south). Weather.com will not play videos, will just display black screen where video should play with video title description overlayed. I've tried Safari, Chrome, Firefox and Edge on Windows 10 and MacOS with latest Ublock Origin extension. I cleared browser cache, removed and reinstalled plugin, forced filter list updates before and after purging all caches. I'm not running any 3rd party AV software or any other adblocker programs. I use Nord VPN on my windows PC, but not Mac. The issue happens whether I'm using the VPN or not. Flushed DNS and changed DNS server IPs to cloudflare and google without any change.

If I enter the following line under My Filters videos will play.

||amazon-adsystem.com^$important,script,redirect-rule=noopjs,domain=weather.com

-=Troubleshooting Information=-
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 89299
  cosmetic: 39082
  scriptlet: 18006
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62322-53, 1h.21m
    easyprivacy: 30685-1170, 1h.21m
    plowe-0: 3670-863, 1h.21m
    ublock-abuse: 76-0, 1h.21m
    ublock-badware: 4342-105, 1h.21m
    ublock-filters: 33052-120, 1h.21m
    ublock-privacy: 249-1, 1h.21m
    ublock-quick-fixes: 266-12, 1h.21m
    ublock-unbreak: 1864-42, 1h.21m
    urlhaus-1: 12383-0, 1h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 780 ms
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    weather.com: 2
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    confiant-integrations.global.ssl.fastly.net: 1
    criteo.net: 1
    crwdcntrl.net: 1
    doubleclick.net: 2
    go-mpulse.net: 2
    indexww.com: 1
    instana.io: 1
    jwpcdn.com: 1
    moatads.com: 3
    rubiconproject.com: 1
    taboola.com: 1
    wfxtriggers.com: 1

**Comment by stephenhawk8054** [comment]
Tks, I can reproduce it now when using VPN to US. This filter works for me:

```adb
@@||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js,domain=weather.com
```

---

@gorhill Sorry, can you take a look? Not sure if it's related to `amazon_apstag.js` redirection filter or not. The video in this URL cannot play after clicking on the video player

`https://weather.com/storms/hurricane/video/hurricane-ian-changes-appearance-of-gulf-of-mexico`

when using VPN to US.

Adding the above filter (add exception to block without redirecting) works for me.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/84d5c6274a60302b49c853c4be649951caae492e

**Comment by Raidware** [comment]
@mapx- 

@stephenhawk8054 
https://weather.com/tr-TR/weather/tenday/l/a496cfcba367ffae60ccfdc94e31bcf3d0a12ac6515336dbd274f381a932abbc?traffic_source=footerNav_Tenday

![Screenshot_20240930_070519](https://github.com/user-attachments/assets/80d58c74-2850-4afe-a699-5acfa16dec02)

**Comment by stephenhawk8054** [comment]
What issue you want to solve?

**Comment by stephenhawk8054** [comment]
I can't reproduce

![image](https://github.com/user-attachments/assets/8c9c3fb6-d2b8-4866-b8c3-fcbc37a09784)

**Comment by Raidware** [comment]
@gorhill @mapx- 
there is no problem in computer view but there is a problem in mobile view. When I open the mobile view, I see this ad residue.
![Screenshot_20240930_175917](https://github.com/user-attachments/assets/db335f50-9be3-49be-952f-839b481cbd6f)
![Screenshot_20240930_175926](https://github.com/user-attachments/assets/f37c3b74-6c82-4648-8540-a25d2890e7ba)

**Comment by gorhill** [comment]
This works for me:

    weather.com##section[aria-label="Sponsored Content"]

I supposed this should go in EasyList.

**Comment by Raidware** [comment]
> This works for me:
> 
> ```
> weather.com##section[aria-label="Sponsored Content"]
> ```
> 
> I supposed this should go in EasyList.

works

**Comment by gorhill** [comment]
@ryanbr

**Comment by TheRealSkywarp** [comment]
ad residue on https://weather.com/fr-BE/temps/aujour/l/BEXX0005:1:BE

ss:
https://github.com/user-attachments/assets/1bb8bedf-2283-4155-ae80-87f7a5997dd9

</details>

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 152
filterset (summary):
 network: 386400
 cosmetic: 274462
 scriptlet: 70090
 html: 3925
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/LegitimateURLShortener.txt: 3009-6, 34m
  ublock-experimental: 20-0, 20m
  adguard-generic: 96587-5825, 34m
  adguard-mobile: 12476-68, 34m
  adguard-spyware-url: 2542-299, 20m
  block-lan: 91-0, 34m
  curben-phishing: 164568-47, 34m
  adguard-cookies: 38860-113, 34m
  ublock-cookies-adguard: 5703-81, 34m
  fanboy-cookiemonster: 57924-14875, 34m
  ublock-cookies-easylist: 5703-5703, 34m
  adguard-social: 26494-45, 34m
  [12 lists not shown]: [too many]
 default:
  user-filters: 81-0, never
  ublock-filters: 52421-70, 21m Δ
  ublock-badware: 10385-28, 21m Δ
  ublock-privacy: 4040-66, 34m
  ublock-unbreak: 2831-1, 34m
  ublock-quick-fixes: 457-13, 34m
  easylist: 88412-1273, 21m Δ
  easyprivacy: 55839-136, 34m
  urlhaus-1: 24190-11, 34m
  plowe-0: 3507-1442, 34m
  FRA-0: 16825-391, 34m
filterset (user): [array of 81 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 985 ms
 maxAssetCacheWait: 653 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  weather.com: 4
  amplitude.com: 6
  ay.delivery: 2
  google.com: 1
  newrelic.com: 2
  taboola.com: 1
  tblcontent.com: 6
  w-x.co: 2
 extended:
  ###credential_picker_container
  ##.bg-gray-100:has-text(Advertisement)
  ##+js(abort-on-property-read, setNptTechAdblockerCookie)
  ##+js(prevent-fetch, securepubads.g.doubleclick.net/pagead/ppub_…
  ##+js(set-constant, adBlockerReady, false)
  ##+js(trusted-set-local-storage-item, userConsents, {"functional…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(abort-current-script, admiral)
  ##+js(remove-node-text, script, `/"v4ac1eiZr0"|""\)\.split\(","\…
```
</details>

**Comment by gothic-bum** [comment]
@TheRealSkywarp 

Please test again after adding the following to "My filters":  
  
    weather.com##section[aria-label="Advertisement"]

**Comment by TheRealSkywarp** [comment]
> [@TheRealSkywarp](https://github.com/TheRealSkywarp)
> 
> Please test again after adding the following to "My filters":
> 
> ```
> weather.com##section[aria-label="Advertisement"]
> ```

It is still there

**Comment by gothic-bum** [comment]
Sorry, try this instead:  

    weather.com##section:has-text(Contenu sponsorisé)

**Comment by TheRealSkywarp** [comment]
Yes, this one fixed it. Sorry for the late response.
