### ISSUE TITLE
Unable to load comments counter on several websites.

### ISSUE THREAD

**Issue by robson-viana** [uBlockOrigin/uAssets#15086]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

<details>
<summary>List of sites</summary>

```
blacklistednews.com
brit.co
canadafreepress.com
cannabisaficionado.com
cheapism.com
crooksandliars.com
dodgersdigest.com
dogtime.com
dreamglossary.com
federalnewsnetwork.com
flagandcross.com
frontpagedetectives.com
graziamagazine.com
hackr.io
hisglorynews.com
horoscope.com
ijr.com
info241.com
ingenio.com
justjared.com
kjas.com
knewz.com
livingmighty.com
morninghoney.com
newsmax.com
nichegamer.com
okmagazine.com
patheos.com
patriotproject.com
playstationlifestyle.net
qthemusic.com
radaronline.com
realitytea.com
rohansalesrep4.com
sherdog.com
slippedisc.com
squeaky.deals
starmagazine.com
steelersnow.com
superherohype.com
tatumreport.com
thefederalistpapers.org
thegatewaypundit.com
thegradcafe.com
theroyalobserver.com
tvguide.co.uk
underthegeorgiasun.com
westernjournal.com
wetalktesla.com
womensgolfjournal.com
wrestlezone.com
wtop.com
wvsportsnow.com
```

</details>

### Describe the issue

Several websites are reporting difficulties loading their comments counter because the path `/loader/counter.js` is blacklisted by uBO.

This file has nothing to do with advertisement and is purely a content product.

### Screenshot(s)

`playstationlifestyle.net`:

![image](https://user-images.githubusercontent.com/81261035/193074951-ad7e189a-ee8c-42c4-a5fb-8e2b61c82af6.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox Developer Edition 106.0b5

### Settings

No settings have been changed.

**Comment by mapx-** [comment]
Are you talking about a specific script => 
`https://soapps.net/live/loader/counter.js`

?

**Comment by mapx-** [comment]
@ryanbr

**Comment by robson-viana** [comment]
@mapx- actually, the path `/loader/counter.js` is blacklisted by the EasyPrivacy list, whatever the domain it is hosted:

![image](https://user-images.githubusercontent.com/81261035/193116190-13b73c3d-8acd-4d3c-a850-d060ec398b8e.png)

**Comment by mapx-** [comment]
I know but I see that specific script on 3-4 pages you listed above

**Comment by robson-viana** [comment]
@mapx- This specific script has been developed by [Insticator Inc.](https://www.insticator.com/) and all those sites are Insticator's clients that use embeddable products on their pages.

**Comment by robson-viana** [comment]
@MasterKia the commenting tool is provided by Insticator Inc. and the clients integrate it with Insticator to show, add, **count** comments, etc, on their pages.

**Comment by mapx-** [comment]
@robson-viana as I said, I saw only this script
`https://soapps.net/live/loader/counter.js`

other pages you listed have no comments (or you should provide specific pages) 

Could you list other similar scripts blocked by `/loader/counter.js` (other than `soapps` one) used by the pages above ?

**Comment by robson-viana** [comment]
@mapx- I only have examples of websites that use `https://soapps.net/live/loader/counter.js`.

Here are a few more:

![image](https://user-images.githubusercontent.com/81261035/193286059-f4238a3a-ee89-45c4-a990-91d401e3f90c.png)

![image](https://user-images.githubusercontent.com/81261035/193286870-e906c757-0c8f-4f0e-a4cc-cc44b638e6c4.png)

![image](https://user-images.githubusercontent.com/81261035/193287264-4c2357cc-4239-4bf6-a2d4-81212c890bae.png)

As we can see, this file has nothing to do with advertisements and is purely a content product embedded on their pages.

**Comment by robson-viana** [comment]
thanks a lot @mapx- I appreciate it!
