### ISSUE TITLE
google.com: nuisance

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#15084]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?client=firefox-b-d&q=%E6%96%B0%E6%99%82%E4%BB%A3`

### Category

nuisance

### Describe the issue

Can't copy lyrics.
uBlock₀ filters – Annoyances
`www.google.*##div[data-song-title] > div:style(user-select: auto !important;)`
`www.google.*##div[data-song-title] [data-lyricid]:style(user-select: auto !important;)`
↓ change filters
`www.google.*##[data-attrid="kc:/music/recording_cluster:lyrics"] [data-lyricid]:style(user-select: auto !important;)`
`www.google.*##div[data-attrid="kc:/music/recording_cluster:lyrics"] > div > div:style(user-select: auto !important;)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot_google](https://user-images.githubusercontent.com/107383950/193037291-4c627d63-097b-4d7a-8634-4dafe9aabb90.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 102
filterset (summary): 
  network: 36859
  cosmetic: 36797
  scriptlet: 22387
  html: 1669
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    JPN-1: null
  added: 
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt: 9680-55, 21m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 50197-10149, 21m
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-social.txt: 2566-0, 21m
    adguard-spyware-url: 766-3, 21m
    ublock-annoyances: 4861-4, 19m
  default: 
    user-filters: 22-0, never
    ublock-filters: 33688-548, 21m
    ublock-badware: 4324-0, 21m
    ublock-privacy: 273-2, 21m
    ublock-abuse: 76-0, 21m
    ublock-unbreak: 1874-1, 21m
    ublock-quick-fixes: 233-0, 21m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2270 ms
  maxAssetCacheWait: 599 ms
popupPanel: 
  blocked: 82
  blockedDetails: 
    google.com: 82
```
</details>

**Comment by mapx-** [comment]
I get no lyrics using your example search

**Comment by chimaha** [comment]
How about this?
https://www.google.com/search?q=New+Genesis+ado+lyrics

**Comment by mapx-** [comment]
The previous filters still working fine on my side (using japan ip)

**Comment by chimaha** [comment]
There is no [data-song-title]
Can you try setting the language to Japanese?
![スクリーンショット 2022-09-30 150426](https://user-images.githubusercontent.com/107383950/193201328-12aea350-1ba2-4421-93c8-3c2cda54e4f5.jpg)

**Comment by mapx-** [comment]
Test this filter

`google.*##[data-lyricid]:style(user-select: text !important;)`

**Comment by chimaha** [comment]
It works fine.
