### ISSUE TITLE
upgrade.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#15087]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.upgrade.com/portal/directory`

### Describe the issue

Cannot perform an external bank transfer. Reverts to home screen. Need to be logged in.

### uBlock Origin version

1.44.2

### Browser name and version

Chrome 105

### Settings

N/A

### Notes

`@@||cdn.optimizely.com/datafiles/*$xhr,domain=upgrade.com`

**Comment by okiehsch** [comment]
Would
`@@||cdn.optimizely.com/datafiles/*.json$xhr,domain=upgrade.com`
work too?
