### ISSUE TITLE
play.hbomax.com: ads

### ISSUE THREAD

**Issue by grliu08** [uBlockOrigin/uAssets#15080]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://play.hbomax.com/`

### Category

ads

### Describe the issue

I just installed the latest Firefox update. Before the update, I was able to use uBO to successfully block ads on HBO Max by blocking the yspsvc-na.net url. However, after the update, the ads reappeared, and when I tried blocking the yspsvc-na.net url like I usually do, HBO Max wouldn't play anything - no ads, no shows, just a black screen. 

Additionally, the refresh button in the uBO panel doesn't go away no matter how many times I click it when the yspsvc-na.net url is blocked, which usually doesn't happen (usually the refresh button disappears once it's clicked because there's no point in refreshing the page when you haven't made any changes - but in this instance once I block the yspsvc-na.net url and make no further changes, the refresh button remains still.) This isn't as important as the ads not being blocked, but I wanted to provide this info in case it ends up being relevant to the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1435" alt="Screen Shot 2022-09-28 at 10 36 31 PM" src="https://user-images.githubusercontent.com/67400658/192925967-0ea3a383-9e0e-4dd7-82aa-7db625c7a1ec.png">
<img width="1438" alt="Screen Shot 2022-09-28 at 10 36 46 PM" src="https://user-images.githubusercontent.com/67400658/192925984-23a32356-aaa9-4536-80fa-9790f88e830d.png">

 

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 84160
  cosmetic: 39203
  scriptlet: 17911
  html: 758
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33709-33, 1d.2h.13m
    ublock-badware: 4324-0, 1d.2h.12m
    ublock-privacy: 267-0, 10d.17h.35m
    ublock-abuse: 76-0, 10d.17h.33m
    ublock-unbreak: 1874-0, 1d.2h.11m
    ublock-quick-fixes: 226-16, 50m
    easylist: 62616-608, 2d.23h.23m
    easyprivacy: 30636-1705, 2d.23h.21m
    urlhaus-1: 7155-0, 49m
    plowe-0: 3673-3, 10d.17h.31m
filterset (user): [empty]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 650 ms (selfie)
  maxAssetCacheWait: 86 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    hbo.com: 1
    yspsvc-na.net: 1
```
</details>

**Comment by mapx-** [comment]
Test

`||hbo.yspsvc-na.net/csm/*&caid=$xhr,removeparam=caid,domain=play.hbomax.com`

**Comment by grliu08** [comment]
It worked for me - thank you so much!
