### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by SkunkSpam** [uBlockOrigin/uAssets#15096]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/search?q=speed+test&rlz=1C1ONGR_enUS992US992&sxsrf=ALiCzsYVcJiV6X7GzMrY2LscVe9wLTBmmw%3A1664499368633&ei=qD42Y4ahJurekPIPzOu3iAQ&ved=0ahUKEwiGleKsp7v6AhVqL0QIHcz1DUEQ4dUDCA4&uact=5&oq=speed+test&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyCggAELEDEIMBEEMyBAgAEEMyCwgAEIAEELEDEIMBMhAIABCABBCHAhCxAxCDARAUMgoIABCABBCxAxAKMgUIABCABDIICAAQgAQQsQMyBQgAEIAEMggIABCABBCxAzoHCCMQsAMQJzoKCAAQRxDWBBCwAzoHCAAQsAMQQzoICC4QsQMQgwE6EQguEIAEELEDEIMBEMcBENEDOggIABCxAxCDAToKCAAQgAQQhwIQFDoHCC4Q1AIQQzoNCC4QsQMQgwEQ1AIQQzoLCAAQgAQQsQMQyQM6BwgjELECECc6CggAELEDEIMBEAo6BwgAELEDEAo6BAgAEAo6BQgAELEDOg4ILhCABBCxAxCDARDUAkoECEEYAEoECEYYAFD8B1iuFWDtFmgEcAF4AIABlAGIAaEKkgEEMC4xMZgBAKABAcgBCsABAQ&sclient=gws-wiz`

### Category

ads

### Describe the issue

The result I want pops in then slides down to make room for random ads
I have adblock installed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 84593
  cosmetic: 39034
  scriptlet: 17897
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62413-52, 2d.23h.55m
    easyprivacy: 30635-1170, 2d.23h.53m
    plowe-0: 3670-863, 4d.23h.50m
    ublock-abuse: 76-0, 12d.17h.29m
    ublock-badware: 4180-105, 3d.20h.14m
    ublock-filters: 32880-115, 3d.20h.13m
    ublock-privacy: 245-1, 12d.17h.28m
    ublock-quick-fixes: 230-5, 7m
    ublock-unbreak: 1859-42, 3d.20h.15m
    urlhaus-1: 7844-0, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 310 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    google.com: 27
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings, don't use any other blocking extension

**Comment by gwarser** [comment]
Opera browser?
