### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by Bhoenix** [uBlockOrigin/uAssets#15093]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/watch/d6a19696-5803-4468-8899-651fc65e19bf`

### Category

breakage

### Describe the issue

wont play any media just says "this video will continue from this point after the break" if you hover/click on the time bar

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83439842/193147202-b8c3ad5e-6d48-49e6-96af-e2e9f4460a59.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 84839
  cosmetic: 39195
  scriptlet: 17904
  html: 758
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33630-33, 2d.21h.6m
    ublock-badware: 4189-0, 2d.21h.8m
    ublock-privacy: 273-0, 1d.22h.37m
    ublock-abuse: 76-0, 1d.22h.36m
    ublock-unbreak: 1872-0, 2d.21h.7m
    easylist: 62616-608, 3d.23h.20m
    easyprivacy: 30636-1706, 3d.23h.18m
    urlhaus-1: 8014-0, 4m
    plowe-0: 3670-3, 1d.22h.35m
    ublock-quick-fixes: 233-5, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 333 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 43
  blockedDetails: 
    hulu.com: 19
    ads-twitter.com: 1
    akadns.net: 1
    conviva.com: 7
    demdex.net: 4
    google-analytics.com: 1
    moatads.com: 1
    omtrdc.net: 6
    scorecardresearch.com: 1
    yimg.com: 2
```
</details>

**Comment by mapx-** [comment]
Update all your lists
(how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

Test again
