### ISSUE TITLE
freedrivemovie.com: detection

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#15090]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freedrivemovie.com/links/duny6wqh1v/`

### Category

detection

### Describe the issue

Detect uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-09-30-01-57-55-593_com kiwibrowser browser](https://user-images.githubusercontent.com/96541364/193138082-df24a8a2-ebf7-40ba-ad8b-303d3dec014e.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 94710
  cosmetic: 59460
  scriptlet: 22824
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    adguard-mobile: null
    urlhaus-1: null
  added: 
    dpollock-0: 11389-0, 9h.7m
    fanboy-annoyance: 80681-34948, 9h.7m
    ublock-annoyances: 4860-69, 9h.7m
  default: 
    easylist: 62205-17963, 9h.9m
    easyprivacy: 30637-1287, 9h.8m
    plowe-0: 3670-1255, 9h.7m
    ublock-abuse: 76-0, 9h.7m
    ublock-badware: 4319-106, 9h.7m
    ublock-filters: 33063-395, 9h.7m
    ublock-privacy: 249-9, 9h.7m
    ublock-quick-fixes: 230-16, 9h.7m
    ublock-unbreak: 1866-46, 9h.7m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
  largeMediaSize: 512
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 999 ms (selfie)
  maxAssetCacheWait: 581 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MayaBi7** [comment]
Thank You for your response

**Comment by mapx-** [comment]
update your filter lists, it was fixed
