### ISSUE TITLE
canvas.ucsc.edu: breakage (requires login)

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#15092]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://canvas.ucsc.edu/courses/47645/external_tools/5477`

### Category

breakage

### Describe the issue

requires login but unable to preview onenote notebook when enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1201" alt="Screen Shot 2022-09-29 at 2 32 22 PM" src="https://user-images.githubusercontent.com/69532417/193146601-c9a98c36-4189-4c16-b835-7a5d40c60204.png">
<img width="1791" alt="Screen Shot 2022-09-29 at 2 34 09 PM" src="https://user-images.githubusercontent.com/69532417/193146603-69d70819-69de-479b-b94c-4dc8dbd85196.png">
<img width="1792" alt="Screen Shot 2022-09-29 at 2 34 17 PM" src="https://user-images.githubusercontent.com/69532417/193146604-f80b048c-e235-40bd-b711-488fef17e464.png">
<img width="1198" alt="Screen Shot 2022-09-29 at 2 34 49 PM" src="https://user-images.githubusercontent.com/69532417/193146606-f9a034a7-6b8c-42df-9e40-3b51973c60ee.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 83773
  cosmetic: 39069
  scriptlet: 17919
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62242-52, 1d.23h.37m
    easyprivacy: 30638-1170, 1d.23h.35m
    plowe-0: 3670-863, 1d.23h.34m
    ublock-abuse: 76-0, 1d.23h.32m
    ublock-badware: 4180-105, 1d.23h.30m
    ublock-filters: 32990-116, 1d.23h.29m
    ublock-privacy: 249-1, 1d.23h.28m
    ublock-quick-fixes: 223-16, 22h.19m
    ublock-unbreak: 1859-42, 1d.23h.26m
    urlhaus-1: 7155-0, 22h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 204 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    insops.net: 1
    microsoft.com: 1
    office.com: 1
    onenote.com: 1
```
</details>

**Comment by mapx-** [comment]
Update all filter lists.

I see in your screenshot a filter which can not find in Easyprivacy list

`||measure.office.com^`

After updating test again and if still there click it and see from what list landed there

**Comment by jimmysofat6864** [comment]
@mapx- 

Updating all the filter lists and clearing cache did not fix the issue. I have some of the lists shown on what is causing it but not sure which it could be. 
![Screen Shot 2022-09-30 at 12 41 18 AM](https://user-images.githubusercontent.com/69532417/193218254-0ee28d8a-eb6b-49f8-be50-e8d767efcedd.png)
![Screen Shot 2022-09-30 at 12 41 35 AM](https://user-images.githubusercontent.com/69532417/193218257-50df58b6-bd68-4eed-9262-e0899c805cae.png)
![Screen Shot 2022-09-30 at 12 41 40 AM](https://user-images.githubusercontent.com/69532417/193218260-7d3a04bb-1141-4351-8fe6-09cfd6c5f91f.png)
![Screen Shot 2022-09-30 at 12 41 48 AM](https://user-images.githubusercontent.com/69532417/193218261-0925a330-680e-43e7-a1ff-3417e686ea3e.png)
![Screen Shot 2022-09-30 at 12 41 55 AM](https://user-images.githubusercontent.com/69532417/193218262-6e0aacb6-b6f5-4f63-8737-5577a53edadb.png)
![Screen Shot 2022-09-30 at 12 42 00 AM](https://user-images.githubusercontent.com/69532417/193218264-18b37578-7f00-42ff-80ef-ff2f0a6c9328.png)

**Comment by mapx-** [comment]
test these filters 1 by 1 and see which one fixes the issue

```
@@||measure.office.com/*json$xhr,domain=onenote.com
@@||browser.events.data.microsoft.com/*json$xhr,domain=onenote.com
@@||onenote.com^$script,1p
```

if does not work test the various 2 combinations
still in trouble => test all 3 together

**Comment by jimmysofat6864** [comment]
@mapx- Last one fixed my issue. It was `@@||onenote.com^$script,1p`

**Comment by mapx-** [comment]
@ryanbr 
EP filter
`/aria-web-telemetry-`
