### ISSUE TITLE
alldevotion.com: breakage

### ISSUE THREAD

**Issue by ThePurpleCrayon** [uBlockOrigin/uAssets#15095]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.alldevotion.com/`

### Category

breakage

### Describe the issue

On the page there is 

> God Wants You to Know
> Daily messages to connect you with God 
along with a message that can be Liked or Shared.
When I choose 'Share', a Facebook pop-up is created but never loads completely.
No pop-up blockers or any other third-party content monitoring add-ons. 
This latest occurrence has lasted about 30 days, while the previous time this has
happened(last year) I was able to track down an entry in one of the filter lists and
was able to remove the entry causing this to happen - the problem is I forgot how
I performed that task.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screen](https://user-images.githubusercontent.com/10244639/193165772-c87b0e33-e5f0-4954-a70f-903bce106b4e.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b6
Chromium: 106
filterset (summary): 
  network: 84821
  cosmetic: 39029
  scriptlet: 17946
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    easylist: 62300-52, 2m
    easyprivacy: 30639-1170, 2m
    plowe-0: 3670-863, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4326-105, 2m
    ublock-filters: 32956-114, 2m
    ublock-privacy: 249-1, 2m
    ublock-quick-fixes: 219-16, 2m
    ublock-unbreak: 1862-42, 2m
    urlhaus-1: 8014-0, 2m
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1036 ms
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
> God wants You to Know is requesting access to: Your name and profile picture and email address.

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by ThePurpleCrayon** [comment]
23:26:37​ ||js-agent.newrelic.com^​ --​ www.alldevotion.com​ 3​ script​ https://js-agent.newrelic.com/nr-spa-1216.min.js
23:28:17​ ||googlesyndication.com^​ --​ www.alldevotion.com<http://www.alldevotion.com> ​3​ script​ https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
23:30:26​ ||googletagmanager.com^​ --​ www.alldevotion.com​ 3 ​script​ https://www.googletagmanager.com/gtag/js?id=UA-196759-21






________________________________

**Comment by mapx-** [comment]
Test

`@@||googletagmanager.com/gtag/js$script,domain=alldevotion.com`

**Comment by ThePurpleCrayon** [comment]
I'll need instructions from you on how to enter this.

@@||googletagmanager.com/gtag/js$script,domain=alldevotion.com


________________________________

**Comment by mapx-** [comment]
right click uBO icon, options, "my filters" tab, add the filter, click "apply changes"

read more https://github.com/gorhill/uBlock/wiki/Dashboard

**Comment by mapx-** [comment]
test
`@@||js-agent.newrelic.com^$script,domain=alldevotion.com`

**Comment by ThePurpleCrayon** [comment]
Still the same result
________________________________

**Comment by mapx-** [comment]
Reset uBO to default settings / lists, update then the lists.
Disable any other extension and test again.
