### ISSUE TITLE
[nsfw] shinchu.net: detection

### ISSUE THREAD

**Issue by oncomdeblo** [uBlockOrigin/uAssets#15099]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shinchu.net/backup/w/?get=JY6Ey`

### Category

detection

### Describe the issue

Cok

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 90501
  cosmetic: 28779
  scriptlet: 17980
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    IDN-0: 9256-3702, 11h.36m
    adguard-mobile: 8150-31, 11h.36m
    easylist: 62233-17915, 11h.32m
    easyprivacy: 30637-1184, 11h.31m
    plowe-0: 3670-949, 11h.30m
    ublock-abuse: 76-0, 11h.28m
    ublock-badware: 4319-105, 11h.26m
    ublock-filters: 33063-399, 11h.25m
    ublock-privacy: 249-2, 11h.24m
    ublock-quick-fixes: 230-16, 11h.23m
    ublock-unbreak: 1867-45, 11h.22m
    urlhaus-1: 8014-0, 11h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1457 ms (selfie)
  maxAssetCacheWait: 629 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
`Chromium Mobile: 105` maybe kiwi browser => not supported. Try FF mobile
