### ISSUE TITLE
bbc.co.uk: ads

### ISSUE THREAD

**Issue by LeCommonMan** [uBlockOrigin/uAssets#15098]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bbc.co.uk/news/technology-63033084.amp`

### Category

ads

### Describe the issue

big block of ads visible all over. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 273994
  cosmetic: 39018
  scriptlet: 17941
  html: 769
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts: 203597-14252, 2m
  default: 
    user-filters: 5-0, never
    ublock-filters: 33700-49, 2m
    ublock-badware: 4330-0, 2m
    ublock-privacy: 273-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1875-0, 2m
    ublock-quick-fixes: 233-0, 2m
    easylist: 62258-609, 2m
    easyprivacy: 30639-1706, 2m
    urlhaus-1: 7844-0, 2m
    plowe-0: 3670-3, 2m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 84 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  largeMediaSize: 3990
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 129 ms (selfie)
  maxAssetCacheWait: 180 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    ampproject.org: 2
```
</details>

**Comment by mapx-** [comment]
add

`bbc.co.uk##[amp-access="toggles.ads.enabled"]`

@ryanbr
