### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by dbntechcoach** [uBlockOrigin/uAssets#15103]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=jfKfPfyJRdk`

### Category

ads

### Describe the issue

Ads now embedded in videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 83695
  cosmetic: 38918
  scriptlet: 17839
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62203-52, 1d.23h.57m
    easyprivacy: 30638-1170, 1d.23h.56m
    plowe-0: 3673-862, 11d.1m
    ublock-abuse: 76-0, 11d.3m
    ublock-badware: 4180-105, 3d.23h.40m
    ublock-filters: 32923-115, 3d.23h.42m
    ublock-privacy: 245-1, 11d.2m
    ublock-unbreak: 1859-42, 3d.23h.41m
    urlhaus-1: 7155-0, 1d.19h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15076 ms (selfie)
  maxAssetCacheWait: 817 ms
popupPanel: 
  blocked: 58
  blockedDetails: 
    doubleclick.net: 3
    google.com: 3
    googlesyndication.com: 7
    youtube.com: 45
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
