### ISSUE TITLE
imgur.com: detection

### ISSUE THREAD

**Issue by Razzlesnaff** [uBlockOrigin/uAssets#15109]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/`

### Category

detection

### Describe the issue

wants me to whitelist ublock to upload images to imgur

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 84649
  cosmetic: 39027
  scriptlet: 17965
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-2, never
    easylist: 62272-52, 2m
    easyprivacy: 30643-1170, 2m
    plowe-0: 3665-860, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4326-105, 2m
    ublock-filters: 33007-118, 2m
    ublock-privacy: 249-1, 2m
    ublock-quick-fixes: 230-16, 2m
    ublock-unbreak: 1863-42, 2m
    urlhaus-1: 7826-0, 2m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 596 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    imgur.com: 4
    alexametrics.com: 3
    assemblyexchange.com: 2
    ccgateway.net: 1
    d3c8j8snkzfr1n.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    media-lab.ai: 1
    quantserve.com: 4
    sascdn.com: 2
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings / lists
- disable any other blocking extension
