### ISSUE TITLE
jobindex.dk: nuisance

### ISSUE THREAD

**Issue by LalleSX** [uBlockOrigin/uAssets#15101]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jobindex.dk/jobsoegning/4600-koege`

### Category

nuisance

### Describe the issue

Sign up to email Pop up 
I have all ready fixed it

The rules are: 
! 2022-09-30 https://www.jobindex.dk
www.jobindex.dk##.show.show-on-load.fade.modal
www.jobindex.dk##.show.fade.modal-backdrop
||www.jobindex.dk/js/dist/jobagent/popup.940a4096212023f299bd.bundle.js$script,domain=www.jobindex.dk

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pic-selected-220930-1315-10](https://user-images.githubusercontent.com/29478339/193258351-d00beeec-e1ec-4f7c-843c-9616002f7001.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 203540
  cosmetic: 193312
  scriptlet: 26108
  html: 778
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/LalleSX/4chan-annoyances/main/4chanannoyances.txt: 26-0, 1d.37m
    https://www.i-dont-care-about-cookies.eu/abp/: 25379-4, 2d.17h.57m
    adguard-spyware: 26705-1391, 1d.13h.58m
    adguard-annoyance: 59675-5603, 1d.13h.56m
    adguard-social: 18571-1068, 9h.37m
    fanboy-annoyance: 80612-64670, 6d.18h.22m
    fanboy-cookiemonster: 41095-9267, 6d.18h.21m
    fanboy-social: 23366-8, 2d.18h.1m
    ublock-annoyances: 4857-5, 1d.13h.55m
    dpollock-0: 11389-483, 9d.1h.59m
    NOR-0: 2804-10, 12h.33m
  default: 
    user-filters: 33-9, never
    ublock-filters: 33702-60, 1d.14h.1m
    ublock-badware: 4324-0, 1d.14h
    ublock-privacy: 268-0, 9d.2h.1m
    ublock-abuse: 76-0, 9d.2h
    ublock-unbreak: 1874-1, 1d.13h.59m
    ublock-quick-fixes: 233-0, 12h.36m
    easylist: 62229-844, 2d.17h.59m
    adguard-spyware-url: 766-3, 1d.13h.57m
    easyprivacy: 30638-14291, 2d.17h.58m
    urlhaus-1: 8014-0, 12h.35m
    curben-phishing: 79480-8, 12h.34m
    plowe-0: 3673-3, 8d.9h.52m
    LegitimateURLShortener: 1953-115, 12h.32m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1584 ms
  maxAssetCacheWait: 550 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    jobindex.dk: 6
    gemius.pl: 1
```
</details>

**Comment by LalleSX** [comment]
The reason the screen shot shows an ad is because the screenshot was taken in my experiment browser, where uBO has no rules active.
Tho it happens in my normal browser

**Comment by mapx-** [comment]
add

```
jobindex.dk###jobmail_popup_block
jobindex.dk##.show.fade.modal-backdrop
```

to be reported at easylist repository or / and adguard repository

@ryanbr
