### ISSUE TITLE
adventuresincre.com: breakage

### ISSUE THREAD

**Issue by jordanmendler** [uBlockOrigin/uAssets#15102]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.adventuresincre.com/events/events/`

### Category

breakage

### Describe the issue

Can't submit 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 86220
  cosmetic: 27432
  scriptlet: 17883
  html: 756
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33760-289, 2d.1h.24m
    ublock-badware: 4324-0, 55m
    ublock-privacy: 273-1, 4d.4h.41m
    ublock-abuse: 76-0, 2d.16h.51m
    ublock-unbreak: 1880-0, 56m
    adguard-mobile: 8151-168, 1d.12h.34m
    easylist: 62462-18460, 4d.4h.38m
    easyprivacy: 30639-1715, 4d.4h.40m
    urlhaus-1: 7844-0, 54m
    plowe-0: 3673-3, 12d.15h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 50 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10124 ms (selfie)
  maxAssetCacheWait: 363 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 1
    licdn.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
> Can't submit

Which are the steps to reproduce the issue ?
