### ISSUE TITLE
 Ads on CNN videos are no longer blocked.

### ISSUE THREAD

**Issue by zsc4** [uBlockOrigin/uAssets#15100]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cnn.com/2022/09/29/europe/annexation-russia-ukraine-analysis-intl/index.html`

### Describe the issue

Whenever any CNN video is played, the ad preceding it is now played.  I first noticed this about a month ago; before then, all video ads on CNN were blocked completely successfully.

### uBlock Origin version

1.16.4.30

### Browser name and version

Pale Moon 31.3.0.1 (current version); also Pale Moon 31.2.0.1

### Settings

None.

**Comment by mapx-** [comment]
Pale Moon is using uBO legacy => a lot of features are not present, so the current filters for cnn are not applied.

Use other browser or find an addon who can strip away params from an URL(in this case `&caid` parameter)

filter used to remove the ads:
`||warnermediacdn.com/csm/*&caid=$xhr,removeparam=caid,domain=cnn.com`

**Comment by zsc4** [comment]
Thanks for your very specific suggestions!  I was able to find an addon in Pale Moon's extension library that did exactly what I needed; it's [Pure URL](https://addons.palemoon.org/addon/pureurl4pm/).  Although it claims compatibility only up to Pale Moon 29.*, It works fine on the current version, which is 31.3.0.1.  After installing this extension, I simply clicked on the dropdown arrow on its icon, chose "Options", and added the string "&caid" to the "Garbage fields list".  After that, my CNN videos played perfectly, and the ads are gone.

I am detailing what I did here so that you can pass this on to other Pale Moon users if the same problem is reported.

**Comment by zsc4** [comment]
Starting today, YouTube ads are back. Nothing seems to get rid of them - not Pure URL, not CleanLinks2. Any help would be greatly appreciated
