### ISSUE TITLE
anime-subthai.net: ads

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#15108]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://anime-subthai.net/2021/07/22/against-the-sky-supreme-%e0%b8%95%e0%b8%ad%e0%b8%99%e0%b8%97%e0%b8%b5%e0%b9%88-1-%e0%b8%8b%e0%b8%b1%e0%b8%9a%e0%b9%84%e0%b8%97%e0%b8%a2/`

### Category

ads

### Describe the issue

could not play video until I clicked the "skip ads" button four times.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 85189
  cosmetic: 39902
  scriptlet: 17985
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 438-27, never
    THA-0: 1033-3, 1h.35m
    easylist: 62272-52, 1h.35m
    easyprivacy: 30643-1170, 1h.35m
    plowe-0: 3665-860, 1h.35m
    ublock-abuse: 76-0, 1h.35m
    ublock-badware: 4326-105, 1h.35m
    ublock-filters: 33007-120, 1h.35m
    ublock-privacy: 249-1, 1h.34m
    ublock-quick-fixes: 230-16, 1h.34m
    ublock-unbreak: 1863-42, 1h.34m
    urlhaus-1: 7826-0, 1h.34m
filterset (user): [array of 428 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 83 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2490 ms (selfie)
  maxAssetCacheWait: 570 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    anime-zutto.com: 5
    google-analytics.com: 1
    googles.video: 1
    googletagmanager.com: 1
    jwpltx.com: 1
    yandex.ru: 1
```
</details>

**Comment by ghajini** [comment]
@gluons (EL thailand)

**Comment by ghajini** [comment]
fixed in regional list => easylist thailand 
update your filter lists
