### ISSUE TITLE
[nsfw] xpicture.ru: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15107]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://xpicture.ru/122/8328/1/`

### Category

detection

### Describe the issue

anti adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 108
filterset (summary): 
  network: 98048
  cosmetic: 119077
  scriptlet: 24522
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 10020-4, 1d.7h.25m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-7, 1d.7h.23m
    adguard-spyware: 26707-1064, 1d.7h.27m
    fanboy-annoyance: 80683-257, 5h.15m
    ublock-annoyances: 4836-75, 1d.7h.21m
  default: 
    user-filters: 14-0, never
    easylist: 62229-110, 3d.4h.27m
    easyprivacy: 30638-13801, 3d.4h.25m
    ublock-abuse: 76-0, 1d.5h.30m
    ublock-badware: 4320-103, 1d.7h.19m
    ublock-filters: 32993-439, 1d.7h.17m
    ublock-privacy: 249-46, 1d.5h.28m
    ublock-quick-fixes: 230-16, 5h.13m
    ublock-unbreak: 1862-59, 1d.7h.15m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 1029 ms (selfie)
  maxAssetCacheWait: 573 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    jads.co: 1
    juicyads.com: 1
    mail.ru: 1
    mfcewkrob.com: 2
    yadro.ru: 1
```
</details>

**Comment by mapx-** [comment]
Already fixed by regional list `RUS: RU AdList` => just enable it

or  add 

`@@||xpicture.ru^$generichide`
