### ISSUE TITLE
geotastic.net

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uAssets#15106]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`geotastic.net`

### Describe the issue

A message appears on a flicking viewport. This message asks you to disable your ad blocker.

### Screenshot(s)

![Screenshot from 2022-09-30 17-14-39](https://user-images.githubusercontent.com/70490301/193312976-8109e4d2-a3a7-4046-9b8f-86b63a8cafd2.png)

### uBlock Origin version

1.44.4

### Browser name and version

Vivaldi snapshot 5.5.2805.3

### Settings

- I added the filter geotastic.net##.ad-hero-teaser . This solved the issue.

### Notes

I added the filter geotastic.net##.ad-hero-teaser . This solved the issue.

**Comment by mapx-** [comment]
Test

`*$script,domain=geotastic.net,redirect-rule=noopjs`

However it's only an annoyance, right ?

**Comment by Matr1x-101** [comment]
The script works. Also, it's only an annoyance.

**Comment by Matr1x-101** [comment]
Accidental closure
