### ISSUE TITLE
sonderborgnyt.dk: ads

### ISSUE THREAD

**Issue by casperghst42** [uBlockOrigin/uAssets#15118]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sonderborgnyt.dk/afskedsfest-i-boernehuset-tangsmose/`

### Category

ads

### Describe the issue

Links with have trackers in them are not being removed "data-trace="

`<a class="gofollow" data-track="MTA3NjgsMjk3LDEsNjA=" href="https://borgenshopping.dk/" target="_blank" rel="nofollow"><img src="https://www.sonderborgnyt.dk/wp-content/uploads/2022/04/Borgen_728x188.jpg"></a>`

They have a nasty small java script which is not being blocked:

/*
Track clicks from special elements
Version: 1.1
Original code: Arnan de Gans
With help from: Fraser Munro
Copyright: See notice in adrotate-pro.php
*/
(function($) {
	$(document).ready(function() {
		$(document).on('click', 'a.gofollow', function(){
			$.post(click_object.ajax_url, {'action':'adrotate_click','track':$(this).attr("data-track")});
		});
	});
}(jQuery));

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="773" alt="image" src="https://user-images.githubusercontent.com/30319603/193403882-542b4a38-9226-43eb-9673-597b82356766.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85296
  cosmetic: 39370
  scriptlet: 17910
  html: 757
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 33662-33, 3d.16h.53m
    ublock-badware: 4194-0, 3d.16h.54m
    ublock-privacy: 268-0, 7d.27m
    ublock-abuse: 76-0, 7d.26m
    ublock-unbreak: 1872-0, 3d.16h.52m
    easylist: 62784-608, 7d.25m
    easyprivacy: 30634-1706, 7d.23m
    plowe-0: 3670-3, 5d.20h.55m
    urlhaus-1: 8464-0, 1h.31m
    ublock-quick-fixes: 233-16, 1h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1429 ms (selfie)
  maxAssetCacheWait: 193 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    sonderborgnyt.dk: 28
    googlesyndication.com: 4
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
The script above is already blocked by `Easylist`
`https://www.sonderborgnyt.dk/wp-content/plugins/adrotate-pro/library/jquery.adrotate.clicktracker.js`
blocked by
`/adrotate-`

This filter should remove `data-track` 

`sonderborgnyt.dk##+js(ra, data-track)`

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
It's supposed to already be blocked by `##.gofollow:not([href*=nyhetsbrev], [href*=radio], html, body)` in Nordic Filters (even if that entry sometimes takes a second to kick in), which the OP doesn't seem to have turned on yet.

Nonetheless, I suppose I can add `sonderborgnyt.dk##+js(ra, data-track)` as well.
