### ISSUE TITLE
minhaconexao.com.br: ads

### ISSUE THREAD

**Issue by aquila0101** [uBlockOrigin/uAssets#15111]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.minhaconexao.com.br/`

### Describe the issue

this site is a speed test And it has ads that it's not blocking

### Screenshot(s)

![Captura de tela 2022-09-30 205636](https://user-images.githubusercontent.com/84749877/193370500-47a2ab94-d764-43c4-acc2-6fcd04a1804b.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85980
  cosmetic: 41971
  scriptlet: 18168
  html: 769
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 33692-165, 23h.54m
    ublock-badware: 4325-0, 23h.53m
    ublock-privacy: 273-0, 23h.52m
    ublock-abuse: 76-0, 23h.51m
    ublock-unbreak: 1875-0, 23h.50m
    ublock-quick-fixes: 226-0, 8h.35m
    easylist: 62219-554, 2d.3h.9m
    easyprivacy: 30638-1733, 2d.3h.8m
    urlhaus-1: 7826-0, 8h.34m
    plowe-0: 3673-3, 9d.4h.53m
    spa-1: 4689-14, 23h.55m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 327 ms (selfie)
  maxAssetCacheWait: 130 ms
```
</details>

**Comment by dportvine** [comment]
Only cookies on my side.

<details>
<summary>Screen</summary>

![2022-10-01_101701](https://user-images.githubusercontent.com/111344219/193398304-1474fb31-314d-42c2-812a-b76126eb0d6f.png)
</details>
