### ISSUE TITLE
serialy.io: detection

### ISSUE THREAD

**Issue by Palciny** [uBlockOrigin/uAssets#15116]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://serialy.io/episode/ncis-namorny-vysetrovaci-urad-s02e13`

### Category

detection

### Describe the issue

There is add for discord Channel and add block detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 97197
  cosmetic: 29141
  scriptlet: 21364
  html: 779
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4887-7, 8m
    dpollock-0: 11389-484, 8m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33767-309, 3d.12h.47m
    ublock-badware: 4183-0, 3d.12h.46m
    ublock-privacy: 268-1, 9d.12h.36m
    ublock-abuse: 76-0, 2d.13h.35m
    ublock-unbreak: 1877-0, 3d.12h.45m
    ublock-quick-fixes: 233-0, 11h.3m
    adguard-mobile: 8148-208, 3d.12h.44m
    easylist: 62787-18966, 6d.13h.50m
    easyprivacy: 30635-1812, 6d.13h.49m
    urlhaus-1: 7826-0, 11h.2m
    plowe-0: 3670-3, 3d.12h.48m
    CZE-0: 725-40, 11h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1240 ms (selfie)
  maxAssetCacheWait: 2138 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    serialy.io: 3
    doubleclick.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
there's missing screenshot for a issue you are describing.

havs you updated your ublock filters as it was fixed a day ago
