### ISSUE TITLE
panhandle.newschannelnebraska.com: detection

### ISSUE THREAD

**Issue by ErueWoad** [uBlockOrigin/uAssets#15112]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://panhandle.newschannelnebraska.com/`

### Category

detection

### Describe the issue

Website detects ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 98454
  cosmetic: 129656
  scriptlet: 25585
  html: 780
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59734-5232, 18m
    adguard-social: 18577-1664, 17m
    fanboy-thirdparty_social: 68-1, 17m
    fanboy-annoyance: 80683-68865, 17m
    fanboy-cookiemonster: 41146-17006, 17m
    fanboy-social: 23366-13711, 17m
    ublock-annoyances: 4887-7, 18m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33816-328, 5h.10m
    ublock-badware: 4329-0, 5h.14m
    ublock-privacy: 267-1, 11d.2h.16m
    ublock-abuse: 76-0, 10d.21h.6m
    ublock-unbreak: 1880-0, 5h.13m
    adguard-mobile: 8154-168, 25m
    easylist: 62787-18792, 6d.8h.12m
    easyprivacy: 30636-1722, 5d.2h.42m
    urlhaus-1: 7826-0, 10h.4m
    plowe-0: 3670-3, 1d.17h.56m
    ublock-quick-fixes: 233-0, 10h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2681 ms (selfie)
  maxAssetCacheWait: 877 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    2mdn.net: 1
    google-analytics.com: 2
    googletagmanager.com: 2
    googletagservices.com: 1
    imasdk.googleapis.com: 3
    univtec.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
||imasdk.googleapis.com^$script,redirect-rule=noopjs,domain=panhandle.newschannelnebraska.com
```

**Comment by ErueWoad** [comment]
> Try this:
> 
> ```
> ||imasdk.googleapis.com^$script,redirect-rule=noopjs,domain=panhandle.newschannelnebraska.com
> ```

This seems to have worked. Thank you!

**Comment by FanOfRootBeer** [comment]
anti-adblock on multiple sites
fresh session (cookies) => newschannelnebraska.com => select a subdomain / site => anti-adb
