### ISSUE TITLE
dzen.ru: ads

### ISSUE THREAD

**Issue by Anweekey** [uBlockOrigin/uAssets#15119]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dzen.ru/video/watch/633837433d1ef66e3674453b`

### Category

ads

### Describe the issue

Ads are not blocked. when watching a video, ads also appear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 98814
  cosmetic: 67578
  scriptlet: 18852
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 42132-199, never
    easylist: 69310-176, never
    easyprivacy: 27312-101, never
    plowe-0: 3634-779, never
    ublock-abuse: 76-0, never
    ublock-badware: 4233-0, never
    ublock-filters: 32512-138, never
    ublock-privacy: 231-1, never
    ublock-quick-fixes: 389-0, never
    ublock-unbreak: 1858-31, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3013 ms
  maxAssetCacheWait: 37 ms
popupPanel: 
  blocked: 71
  blockedDetails: 
    mail.ru: 1
    yandex.ru: 70
```
</details>

**Comment by mapx-** [comment]
I get no video ad, maybe needing a russian ip ?

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is a new Yandex domain. The content on it is still being formed. The final version is expected within two weeks. Currently, ads on this domain are blocked by the [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe). Perhaps in the future, ads will be blocked in the main filter of RU AdList, but this is not certain.

**Comment by mapx-** [comment]
@Anweekey just subscribe Counters list

**Comment by Anweekey** [comment]
Understood. Thanks
