### ISSUE TITLE
csfd.cz: ads before every trailer video

### ISSUE THREAD

**Issue by kubalav** [uBlockOrigin/uAssets#15117]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.csfd.cz/film/278567-blondynka/prehled/`

### Category

ads

### Describe the issue

An advertisement plays before each trailer video.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 90902
  cosmetic: 96027
  scriptlet: 23158
  html: 0
listset (total-discarded, last updated): 
  added: 
    http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/: 25379-4, 3h.47m
    https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 16h.36m
    https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 16h.40m
    https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 1d.3h.7m
    https://raw.github.com/liamja/Prebake/master/obtrusive.txt: 1072-171, 6d.17h.1m
    https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt: 651-0, 4d.16h.45m
    https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt: 1260-612, 1d.3h.6m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 16h.39m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-3, 4d.16h.44m
    fanboy-cookiemonster: 41113-9488, 5d.13h.15m
    ublock-annoyances: 4835-237, 3d.13h.21m
  default: 
    user-filters: 147-2, never
    CZE-0: 724-1, 16h.35m
    easylist: 62229-340, 3d.17h.16m
    easyprivacy: 30638-1233, 3d.17h.15m
    plowe-0: 3670-2388, 5d.15h.54m
    ublock-abuse: 76-0, 11d.3h.53m
    ublock-badware: 4320-105, 3d.13h.20m
    ublock-filters: 33007-160, 26m
    ublock-privacy: 245-1, 11d.3h.52m
    ublock-quick-fixes: 223-16, 16h.37m
    ublock-unbreak: 1859-43, 3d.3h.51m
    urlhaus-1: 7826-0, 16h.38m
filterset (user): [array of 145 redacted]
trustedset: 
  added: [array of 167 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 41 redacted]
hostRuleset: 
  added: [array of 171 redacted]
urlRuleset: 
  added: [array of 30 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 4514 ms (selfie)
  maxAssetCacheWait: 1374 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    csfd.cz: 1
    cpex.cz: 2
    gemius.pl: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    performax.cz: 1
    privacy-center.org: 1
    r2b2.cz: 1
    trackad.cz: 2
```
</details>

**Comment by mapx-** [comment]
Test this filter

`/csfd\.cz\/film\/[0-9]{7}\-.*\/videa/$xhr`

**Comment by kubalav** [comment]
It seems to work!
@mapx- Thank you.
