### ISSUE TITLE
thememypc.net: detection

### ISSUE THREAD

**Issue by IgnoreBox** [uBlockOrigin/uAssets#15129]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://thememypc.net/windows-11-ux-pack/`

### Category

detection

### Describe the issue

adblock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 85509
  cosmetic: 39091
  scriptlet: 17924
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 23-0, never
    easylist: 62304-52, 10h.58m
    easyprivacy: 30671-1170, 10h.57m
    plowe-0: 3670-863, 7d.22h.22m
    ublock-abuse: 76-0, 3d.23h.2m
    ublock-badware: 4320-105, 3d.21h.7m
    ublock-filters: 32984-118, 3d.21h.6m
    ublock-privacy: 249-1, 3d.21h.5m
    ublock-quick-fixes: 240-10, 2h.35m
    ublock-unbreak: 1861-42, 3d.22h.43m
    urlhaus-1: 8642-0, 2h.34m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1833 ms (selfie)
  maxAssetCacheWait: 499 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@IgnoreBox if you use for example brave with the shields ON just disable them for that site, the same for vivaldi with its adblocker enabled

![image](https://user-images.githubusercontent.com/10303732/193461512-a35f6dbf-cba4-4165-9c55-e4c2f7af403c.png)

**Comment by IgnoreBox** [comment]
i use edge.. and only edge with ubo only.. no other ...
well at least i already figure this out
with disable java script.... and all solved

**Comment by dportvine** [comment]
@mapx- 
Not ads or detection, but I can see this domain = `https://qoqnxufwkjl.com/`

<details>
<summary>Screen</summary>

![2022-10-03_111627](https://user-images.githubusercontent.com/111344219/193531845-6a549c61-8a93-4ca5-96fe-c416b011a710.png)
![2022-10-03_111552](https://user-images.githubusercontent.com/111344219/193531855-a6de1d70-91da-48d0-ab53-aab34677e4e3.png)
</details>

**Comment by dportvine** [comment]
@mapx- 
this rule disabled the connection to the ad server

`thememypc.net##+js(aeld, , break;case $.)`
<details>
<summary>Screen</summary>

![2022-10-03_115837](https://user-images.githubusercontent.com/111344219/193539277-87164b88-8924-4876-bc34-ca86dc35ecb1.png)
</details>
