### ISSUE TITLE
 streameast.live ads and security threats 

### ISSUE THREAD

**Issue by jabberman3000** [uBlockOrigin/uAssets#15124]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.streameast.xyz/ufc/ufc-fight-night-dern-vs-yan/`

### Describe the issue

banner ads and my anti virus is picking up websites trying to open up in the background

Obviously the link is for a specific stream, but i had the same issues watching another stream last night on the site.

### Screenshot(s)

https://i.imgur.com/vLgI02m.png

https://i.imgur.com/lZhpjDj.png

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 84689
  cosmetic: 39060
  scriptlet: 17921
  html: 760
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33712-49, 1d.21h.48m
    ublock-badware: 4324-0, 1d.21h.47m
    ublock-privacy: 273-0, 6d.1h.8m
    ublock-abuse: 76-0, 6d.1h.7m
    ublock-unbreak: 1875-0, 1d.21h.46m
    easylist: 62297-611, 3h
    easyprivacy: 30670-1706, 2h.59m
    urlhaus-1: 7826-0, 23h.2m
    plowe-0: 3670-3, 5d.1h.56m
    ublock-quick-fixes: 233-0, 23h.1m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 509 ms (selfie)
  maxAssetCacheWait: 193 ms
```
</details>

**Comment by llacb47** [comment]
`streameast.*###GelismisReklams` gets rid of the banner ad (from AdGuard Base)
Also `https://acscdn.com/script/suv4.js` is blocked, which breaks the stream.
AdGuard Base has `@@/^https:\/\/((?!cloudflareinsights\.com|scorecardresearch\.com|achcdn\.com|asacdn\.com|ashcdn\.com|acdcdn\.com|clksite\.com|googletagmanager\.com|googlevideo\.com|youradexchange\.com).)+$/$script,3p,domain=streameast.*`

@mapx- 

FYI, that sketchy domain is what the stream chunks are being served from (it is a pirate site after all lol)

**Comment by mapx-** [comment]
I get only that ad at the top, the stream is ok, for example
`https://www.streameast.xyz/nba/washington-wizards-golden-state-warriors-2/1`

**Comment by llacb47** [comment]
Stream was broken for me in Firefox, will test again later when I’m back on my computer
