### ISSUE TITLE
page2.jyotishkotha.com: detection

### ISSUE THREAD

**Issue by rzxtxt** [uBlockOrigin/uAssets#15128]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://page2.jyotishkotha.com/`

### Category

detection

### Describe the issue

ublock origin detected, please fix. thank you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 122008
  cosmetic: 150006
  scriptlet: 38339
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  added: 
    IDN-0: 9261-3707, 4m
    adguard-annoyance: 59748-1657, now
    adguard-generic: 70418-930, 1m
    adguard-spyware-url: 766-1, now
    fanboy-annoyance: 80725-37077, now
    fanboy-cookiemonster: 41164-41164, now
    ublock-annoyances: 4869-252, now
  default: 
    adguard-mobile: 8151-67, 7m
    easylist: 62307-18609, 4m
    easyprivacy: 30671-1386, 4m
    plowe-0: 3669-962, 4m
    ublock-abuse: 76-0, 4m
    ublock-badware: 4330-345, 4m
    ublock-filters: 33140-4277, 4m
    ublock-privacy: 249-11, 4m
    ublock-quick-fixes: 249-27, 4m
    ublock-unbreak: 1868-87, 4m
    urlhaus-1: 9454-0, 4m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2278 ms
  maxAssetCacheWait: 1004 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
It's a short link site, which shortlink did you use, meaning how did you arrive at that page?
