### ISSUE TITLE
4pda.to: [unknown]

### ISSUE THREAD

**Issue by VIONICK08** [uBlockOrigin/uAssets#15123]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://4pda.to/`

### Category

[unknown]

### Describe the issue

blah-blah

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85591
  cosmetic: 39189
  scriptlet: 17952
  html: 771
listset (total-discarded, last updated): 
  removed: 
    RUS-0: null
  default: 
    user-filters: 33-1, never
    ublock-filters: 33719-49, 1d.6h.8m
    ublock-badware: 4330-0, 1d.6h.7m
    ublock-privacy: 273-0, 4d.12h.32m
    ublock-abuse: 76-0, 4d.12h.31m
    ublock-unbreak: 1875-0, 1d.6h.6m
    easylist: 62613-608, 6d.10h.6m
    easyprivacy: 30636-1705, 6d.10h.5m
    urlhaus-1: 8571-0, 40m
    plowe-0: 3669-3, 8d.9h.30m
    ublock-quick-fixes: 233-0, 39m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 75 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 170 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    4pda.to: 4
    google-analytics.com: 1
    yadro.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
The rules for this site are contained in [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) (left-click to subscribe).
