### ISSUE TITLE
curvefever.pro

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uAssets#15120]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://curvefever.pro`

### Describe the issue

When you click 'QUICKPLAY', a timer appears asking you to disable your adblocker.

### Screenshot(s)

![Screenshot from 2022-09-30 18-27-15](https://user-images.githubusercontent.com/70490301/193414361-02dc1869-082d-4099-b119-66029565ef48.png)

### uBlock Origin version

1.44.4

### Browser name and version

Vivaldi Snapshot 5.5.2805.3

### Settings

I enabled the uBlock annoyances filter, but I don't think this is relavant.

**Comment by Matr1x-101** [comment]
@mapx-  this didn't solve the issue. I want to stop this timer. I solved this issue with `curvefever.pro##fullscreen-ad-container`. I'm not trying to block adinplay (it's already blocked), but remove the message that asks you to to disable the adblocker. See the screenshot please.

**Comment by mapx-** [comment]
It's working fine on my side: that page does not appear anymore.
Do you see my exception filter in the logger ?
Did you disable vivaldi builtin blocker ?

**Comment by Matr1x-101** [comment]
@mapx-  Yes, the ad in play advertisement is blocked, but my problem is that [this screen](https://imgur.com/a/J0wmHh9) appears when an adblocker is active. You have to wait a bit before you can proceed.

**Comment by Matr1x-101** [comment]
And I did disable the Vivaldi ad blocker

**Comment by mapx-** [comment]
> the ad in play advertisement is blocked

The filter I added is an `exception`, you should see in the logger:

![image](https://user-images.githubusercontent.com/10303732/193419312-66868430-b438-4c29-84b5-b5a16454dd4b.png)

if you don't see that exception you should reset uBO to default settings, disable any other blocking extension in vivaldi

**Comment by mapx-** [comment]
The filter was added in uBO annoyances list, enable it, update it
