### ISSUE TITLE
kledgeb.blogspot.com: breakage

### ISSUE THREAD

**Issue by betiz0** [uBlockOrigin/uAssets#15126]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kledgeb.blogspot.com/`

### Category

breakage

### Describe the issue

My browser dosen't display anything.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86679
  cosmetic: 45546
  scriptlet: 18017
  html: 760
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33711-33, 3d.4m
    ublock-badware: 4324-0, 3d.3m
    ublock-privacy: 273-0, 6m
    ublock-abuse: 76-0, 5m
    ublock-unbreak: 1875-0, 3d.2m
    ublock-quick-fixes: 233-16, 2m
    easylist: 62413-653, 5d.33m
    easyprivacy: 30635-1728, 5d.31m
    urlhaus-1: 8571-0, 1m
    plowe-0: 3665-3, 3m
    JPN-1: 7846-29, 3d.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 539 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    google.com: 7
    googlesyndication.com: 2
    googletagmanager.com: 1
    kledgeb.github.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
kledgeb.blogspot.com##+js(acis, document.getElementById, _0x)
kledgeb.blogspot.com##body > div[style="visibility: hidden;"]:style(visibility: unset !important)
```

@Yuki2718

**Comment by Yuki2718** [comment]
This anti-adb consists of two-parts and `kledgeb.blogspot.com##body > div[style="visibility: hidden;"]:style(visibility: unset !important)` is required only for uBO due to blocking of GFC.

**Comment by stephenhawk8054** [comment]
I see. I'll add it to the main list.

**Comment by Yuki2718** [comment]
`||fundingchoicesmessages.google.com^$script,redirect-rule=noop.js,domain=kledgeb.blogspot.com` works too, maybe add both?

**Comment by stephenhawk8054** [comment]
> `||fundingchoicesmessages.google.com^$script,redirect-rule=noop.js,domain=kledgeb.blogspot.com` works too, maybe add both?

Yeah, I think better be both. Somehow redirection doesn't work on my end

<details>

![image](https://user-images.githubusercontent.com/66517106/193456559-5025f5f6-cbc9-42cf-901c-ca180a637b4e.png)

</details>

**Comment by huyszn** [comment]
Breakage seems to be back. The site is blank and doesn't display anything when uBO is enabled.

**Comment by Yuki2718** [comment]
@huyszn Do you have Japanese filter enabled? @mapx- The rule is still in JPF.

**Comment by huyszn** [comment]
I didn't have the Japanese filter enabled. I didn't notice that it was addressed in the regional list.
