### ISSUE TITLE
https://www.gardeningetc.com/ news letter sign up

### ISSUE THREAD

**Issue by matter-it-does** [uBlockOrigin/uAssets#15134]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.gardeningetc.com/advice/bog-plants`

### Describe the issue

newsletter sign up popup and a shade overlay on the whole screen

### Screenshot(s)

![image](https://user-images.githubusercontent.com/76812421/193518205-631e9aec-6195-4b1d-97e9-0e4d45b82a18.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 95602
  cosmetic: 78227
  scriptlet: 22830
  html: 792
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 1d.17h.48m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt: 252-0, 16h.39m
    fanboy-thirdparty_social: 69-0, 4d.18h.57m
    fanboy-cookiemonster: 41121-147, 6d.12h.45m
    ublock-annoyances: 4863-4, 1d.11h.36m
  default: 
    user-filters: 80-0, never
    ublock-filters: 33738-51, 1d.11h.39m
    ublock-badware: 4330-4, 1d.11h.38m
    ublock-privacy: 273-0, 4d.13h.40m
    ublock-abuse: 76-0, 4d.13h.39m
    ublock-unbreak: 1876-0, 1d.11h.37m
    easylist: 62465-632, 6d.19h.51m
    easyprivacy: 30639-1706, 6d.19h.50m
    urlhaus-1: 9454-0, 16h.38m
    plowe-0: 3670-4, 3d.22h.57m
    ublock-quick-fixes: 247-247, 3h.33m
filterset (user): [array of 80 redacted]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  removed: 
    no-csp-reports: * true
modifiedUserSettings: 
  largeMediaSize: 1024
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1109 ms (selfie)
  maxAssetCacheWait: 581 ms
```
</details>

**Comment by mapx-** [comment]
enable fanboy's annoyances list and add

`gardeningetc.com##.exit-intent__background.exit-intent`

@ryanbr
