### ISSUE TITLE
id.noxinfluencer.com: breakage

### ISSUE THREAD

**Issue by Kixdevs** [uBlockOrigin/uAssets#15133]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://id.noxinfluencer.com/`

### Category

breakage

### Describe the issue

I try to search on YouTube Search button on idnoxinfluencer and nothing happened until i turn off this extension then it's back to normal.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 80432
  cosmetic: 45242
  scriptlet: 17653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69310-51, never
    easyprivacy: 27312-123, never
    plowe-0: 3634-776, never
    ublock-abuse: 76-0, never
    ublock-badware: 4233-92, never
    ublock-filters: 32512-101, never
    ublock-privacy: 231-3, never
    ublock-quick-fixes: 389-37, never
    ublock-unbreak: 1858-43, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 372 ms
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    baidu.com: 1
    facebook.net: 1
    google.com: 5
    googletagmanager.com: 3
    noxgroup.com: 1
```
</details>

**Comment by mapx-** [comment]
working fine on my end => reset uBO to default settings and then update all the lists

for update => how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)

**Comment by dportvine** [comment]
Works for me.
`@@||noxgroup.com/noxinfluencer/sensor_sdk/sa-sdk-javascript-1.23.3/sensorsdata.min.js$script,domain=id.noxinfluencer.com`

`/sensorsdata.$domain=~sensorsdata.cn` ~> **EasyPrivacy**
@ryanbr

**Comment by stephenhawk8054** [comment]
I can reproduce, however the site can be multi-language (I got `vn.noxinfluencer.com`), so maybe

```adb
@@||noxgroup.com/noxinfluencer/sensor_sdk/sa-sdk-javascript-1.23.3/sensorsdata.min.js$script,domain=noxinfluencer.com
```

**Comment by Kixdevs** [comment]
Thanks a lot for helping, Problem Solved!
