### ISSUE TITLE
getlaka.com

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uAssets#15130]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://getlatka.com/companies/`
`https://getlatka.com/saas-companies`

### Describe the issue

If you click on any company in the list, and scroll down a bit, the screen blurs and it asks you to sign up.

### Screenshot(s)

![Screenshot from 2022-10-02 16-56-54](https://user-images.githubusercontent.com/70490301/193463570-c430732b-20e8-41d7-ac3b-50f37a07ced2.png)

### uBlock Origin version

uBlock Origin: 1.44.4

### Browser name and version

Vivaldi Snapshot 5.5.2805.3

### Settings

No significant changes were made.

### Notes

Probably an annoyance

**Comment by canercetin-randomguy** [comment]
By adding these to filters

> ! 2022-10-02 https://getlatka.com
getlatka.com##.css-ekeie0.MuiDialog-scrollPaper.MuiDialog-container
getlatka.com##.css-919eu4.MuiBackdrop-root
getlatka.com##.css-1cvtwh4.MuiModal-root.MuiDialog-root

it is possible to get rid of signup popup but blur is there due to "style="filter: blur(5px);". Someone more intelligeble than me will know how to fix this, till then give a shot for NoScript extension.

**Comment by mapx-** [comment]
You could use

```
getlatka.com##[class^="signup_container"]
getlatka.com##[style^="filter: blur"]:style(filter: none !important)
```

but then the page buttons are still disabled

**Comment by Matr1x-101** [comment]
I can confirm the solution by mapx works!

**Comment by mapx-** [comment]
You have to enable `uBlock filters – Annoyances`
