### ISSUE TITLE
smallseotools.com: ads

### ISSUE THREAD

**Issue by HB-Stratos** [uBlockOrigin/uAssets#15136]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

the submit button forces me to put something here, even though it says leave it alone.
`https://smallseotools.com/online-text-editor/`

### Category

the submit button forces me to put something here, even though it says leave it alone.

### Describe the issue

Was reported before, but is present again. many big grammarly ad gifs all over the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![465465465](https://user-images.githubusercontent.com/56313836/193590538-c7839456-8ffb-4748-bb31-7b1a1b1fdbcb.PNG)

</details>

### Configuration

the submit button forces me to put something here, even though it says leave it alone.

**Comment by mapx-** [comment]
test

```
||smallseotools.com/*.gif$image
smallseotools.com#@#.b
smallseotools.com##.m-auto.text-center:has(.adsbygoogle)
```

**Comment by stephenhawk8054** [comment]
> the submit button forces me to put something here, even though it says leave it alone.

@gorhill I think currently uBO does not autofill the boxes when reporting the issues via github

Screenshot:

<details>

![3](https://user-images.githubusercontent.com/66517106/193719447-27717b74-8c1b-407a-b9bb-6e5ac2ba04c1.png)

</details>
