### ISSUE TITLE
[nsfw] imgxhgh.buzz: ads

### ISSUE THREAD

**Issue by TehDomic** [uBlockOrigin/uAssets#15138]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://imgxhgh.buzz/g5gjb5k`

### Category

ads

### Describe the issue

Ad with text to speech voice in my local language slipped through the cracks (possibly not on the filter lists yet?).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

.

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by TehDomic** [comment]
> Can you force update the filter lists and test again?
Same result sadly.

**Comment by stephenhawk8054** [comment]
I cannot reproduce the ads, can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by TehDomic** [comment]
Manual filtering suggests blocking
`||padsabs.com/gs6h79qcg?adb=y&key=1dd0a4df83a572e07880529bd71bda98`.

`Here is the requested Troubleshooting Info:
uBlock Origin: 1.44.4
Firefox Mobile: 103
filterset (summary): 
  network: 177423
  cosmetic: 99644
  scriptlet: 21205
  html: 791
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 767-3, 8m
    block-lan: 44-0, 8m
    curben-phishing: 79742-2, 4m
    adguard-annoyance: 59798-667, 8m
  default: 
    user-filters: 11-4, never
    ublock-filters: 33889-61, 8m
    ublock-badware: 4345-0, 8m
    ublock-privacy: 273-0, 8m
    ublock-abuse: 76-0, 8m
    ublock-unbreak: 1882-1, 8m
    ublock-quick-fixes: 279-0, 8m
    adguard-mobile: 8160-148, 8m
    easylist: 62322-766, 8m
    easyprivacy: 30685-1719, 8m
    urlhaus-1: 12383-0, 8m
    plowe-0: 3670-3, 8m
    SWE-1: 4271-2, 8m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 939 ms
  maxAssetCacheWait: 553 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    imgxhgh.buzz: 10
    googlesyndication.com: 1
    realsrv.com: 2
`

**Comment by stephenhawk8054** [comment]
Does this filter works for you?

```adb
/^https?:\/\/[0-9a-z]{7,}\.com\/[0-9a-z]{8,}\?(?:adb|key|shu)=[0-9a-z]+/$frame,3p,domain=buzz|xyz
```

**Comment by TehDomic** [comment]
Yes. Thank you. Will it be added to a filter list, and if so, which one?

**Comment by stephenhawk8054** [comment]
> Does this filter works for you?
> 
> ```
> /^https?:\/\/[0-9a-z]{7,}\.com\/[0-9a-z]{8,}\?(?:adb|key|shu)=[0-9a-z]+/$frame,3p,domain=buzz|xyz
> ```

If this one works, I'll update the filter lists.
