### ISSUE TITLE
karaoketexty.cz: ads

### ISSUE THREAD

**Issue by Vojtak42** [uBlockOrigin/uAssets#15143]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.karaoketexty.cz/texty-pisni/kubisova-marta/casy-se-meni-100581`

### Category

ads

### Describe the issue

All ads are not removed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![IMG_20221004_095216](https://user-images.githubusercontent.com/18753137/193764853-586bbf61-5d44-49ff-9337-6b3f5dd868ff.jpg)

### Configuration

`uBlock Origin: 1.44.4
Chromium Mobile: 101
filterset (summary): 
  network: 91272
  cosmetic: 27895
  scriptlet: 18214
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CZE-0: 727-40, 8m
    adguard-mobile: 8160-27, 6m
    easylist: 62322-17922, 8m
    easyprivacy: 30684-1187, 8m
    plowe-0: 3670-949, 8m
    ublock-abuse: 76-0, 6m
    ublock-badware: 4341-105, 8m
    ublock-filters: 33161-379, 8m
    ublock-privacy: 249-2, 8m
    ublock-quick-fixes: 277-12, 8m
    ublock-unbreak: 1870-45, 6m
    urlhaus-1: 12668-0, 8m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 824 ms (selfie)
  maxAssetCacheWait: 357 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    karaoketexty.cz: 5
    dopc.cz: 1
    doubleclick.net: 2
    gemius.pl: 1
    google-analytics.com: 1
    google.com: 6
    imasdk.googleapis.com: 1
    imedia.cz: 2
    m6r.eu: 1
    mookie1.com: 1
    performax.cz: 4
    pubmatic.com: 1
    screechingstove.com: 1
    toplist.cz: 1
    youtube.com: 13
`

**Comment by mapx-** [comment]
> Chromium Mobile

maybe kiwi => not supported

**Comment by Vojtak42** [comment]
It works on all other websites.
