### ISSUE TITLE
knowyourmeme.com: detection

### ISSUE THREAD

**Issue by ljcool2006** [uBlockOrigin/uAssets#15142]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

 For some reason uBO didn't fill this section; new bug?

### Category

 For some reason uBO didn't fill this section; new bug?

### Describe the issue

knowyourmeme.com has recently got a new anti-adblocker popup, completely replacing the old one

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-10-04 Know Your Meme](https://user-images.githubusercontent.com/51834343/193733486-fc462b44-62ef-403e-8b55-009096981014.png)

</details>

### Configuration

 For some reason uBO didn't fill this section; new bug?

**Comment by krystian3w** [comment]
Too huge config maybe cut to 0.

**Comment by ljcool2006** [comment]
Filters created by user on site:
```
knowyourmeme.com##.dgEhJe6g
knowyourmeme.com##.fEy1Z2XT
@@||knowyourmeme.com^$ghide
```

**Comment by krystian3w** [comment]
Random classes maybe very not stable.

**Comment by mapx-** [comment]
fixed as annoyance, enable `uBlock filters – Annoyances`

**Comment by mapx-** [comment]
`||protestcopy.com^`

@pgl @ryanbr  admiral

**Comment by pgl** [comment]
> `||protestcopy.com^`
> 
> @pgl @ryanbr admiral

Added, thanks!
