### ISSUE TITLE
eightyupgrades.com: detection

### ISSUE THREAD

**Issue by ThisIsFineCopium** [uBlockOrigin/uAssets#15145]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eightyupgrades.com/set/spppwKM5GvEMwywXfGiidn`

### Category

detection

### Describe the issue

The page doesn't display when ublock is enabled. I'm unsure if it's a malfunction or a detection.

Disabling ublock makes it work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/8022147/193846086-31e4af7e-69c0-46d1-a79f-239a8f780d3a.png)

Ublock disabled -
![image](https://user-images.githubusercontent.com/8022147/193846171-579b9b1d-5a79-4b78-b422-cb5c077b8536.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 97904
  cosmetic: 113315
  scriptlet: 23022
  html: 792
listset (total-discarded, last updated): 
  added: 
    https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 1d.2h.16m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 14h.8m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 14h.9m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/youtube_wo_tonikaku_filter.txt: 31-0, 18h.13m
    ublock-annoyances: 4869-6, 2m
    fanboy-annoyance: 80751-353, never
  default: 
    user-filters: 57-2, never
    ublock-filters: 33755-159, 2d.3m
    ublock-badware: 4335-0, 2d.2m
    ublock-privacy: 273-0, 22h.15m
    ublock-abuse: 76-0, 22h.14m
    ublock-unbreak: 1876-2, 2d.1m
    easylist: 62322-535, 14h.12m
    easyprivacy: 30685-1725, 14h.10m
    plowe-0: 3672-4, 1h.20m
    urlhaus-1: 12383-0, 14h.7m
    ublock-quick-fixes: 269-0, 14h.6m
filterset (user): [array of 57 redacted]
trustedset: 
  added: [array of 52 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 31 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 172 ms (selfie)
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    amazonaws.com: 4
    google-analytics.com: 1
    nitropay.com: 2
```
</details>

**Comment by mapx-** [comment]
`amazonaws.com: 4`

You should check in the logger what filter (and from what list) is blocking `amazonaws.com`

**Comment by krystian3w** [comment]
Maybe malfromed file.

Enough is cut line to show only `-2` and uBo don't mark filter as bad.
