### ISSUE TITLE
maxroll.gg: ads

### ISSUE THREAD

**Issue by gekkoe** [uBlockOrigin/uAssets#15140]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://maxroll.gg/lost-ark/build-guides/arthetinean-skill-machinist-raid-guide`

### Category

Was not filled in.

### Describe the issue

I've tried both the zapper mode and selecting the element for the following, but it always comes back:

```adb
|assets.maxroll.gg/wp-content/assets/img/adblock/Half%20Page%20300x600.png$image
I've also tried:
|assets.maxroll.gg/wp-content/assets/img/adblock/*$image
and:
|assets.maxroll.gg/wp-content/assets/img/adblock/*g$image
```

with no better luck. As soon as I refresh or try to get rid of the banner on the other side of the page, they just come back.
It works if I disable javascript, but this also drops useful elements.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![maxroll-add-banner](https://user-images.githubusercontent.com/1664675/193718282-6bff9da4-99f7-4718-b0a4-9d6dcf6b4594.png)

</details>

### Configuration

Was not filled in.

**Comment by gekkoe** [comment]
BTW, this only appears if not in full screen mode.

**Comment by stephenhawk8054** [comment]
I can just see the ads placeholders, but can't see the anti-adblock

<details>

![4](https://user-images.githubusercontent.com/66517106/193720065-fc20a2fd-ff4f-4d38-991c-44469329209f.png)

</details>

Can you force update the filter lists and test again?

If the issue still persists, can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by gekkoe** [comment]
It didn't help and I'm including my troubleshooting information below. Just a quick check though, did you try decreasing the horizontal size of your browser window? When I maximize the window the offending images disappear. They only show when I have the browser in windowed mode.

Troubleshooting Info:
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 89606
  cosmetic: 39094
  scriptlet: 18002
  html: 773
listset (total-discarded, last updated): 
  default: 
    user-filters: 21-2, never
    ublock-filters: 33787-46, 2m
    ublock-badware: 4346-0, 2m
    ublock-privacy: 273-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1878-1, 2m
    easylist: 62322-614, 2m
    easyprivacy: 30684-1706, 2m
    urlhaus-1: 12668-0, 2m
    plowe-0: 3670-3, 2m
    ublock-quick-fixes: 280-0, 2m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 95 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 318 ms (selfie)
  maxAssetCacheWait: 224 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    nitropay.com: 2

**Comment by dportvine** [comment]
`maxroll.gg##.adsmanager-ad-container`

`||maxroll.gg/wp-content/assets/img/adblock/$image` **Ctrl+F5** ads placeholders is cached

**Comment by stephenhawk8054** [comment]
Ok I can reproduce it now. I misunderstood your `full screen` is browser's full screen, not maximized. That banner appears even when I turn off uBO

<details>

![image](https://user-images.githubusercontent.com/66517106/193741875-70d2bca3-a8c0-4dff-9994-58ec128e02ea.png)

</details>

Anyway

```adb
||assets.maxroll.gg/wp-content/assets/img/adblock/$image
```

works for me

**Comment by gekkoe** [comment]
@stephenhawk8054 

The ##.adsmanager-ad-container line did the trick. (didn't try the one with $image at the end but no * yet) 

Thanks!
