### ISSUE TITLE
my.appacademy.io: breakage

### ISSUE THREAD

**Issue by barry505** [uBlockOrigin/uAssets#15146]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://my.appacademy.io/lessons/recursion/6d71ca38/practices/debugging-walkthrough/8a5ea5b8`

### Category

breakage

### Describe the issue

After page loads this message appears at the top of the screen:
An error has occurred. This application may no longer respond until reloaded. [Reload]
If I turn off uBlock for the site, the message goes away.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20221004_093037](https://user-images.githubusercontent.com/6907494/193847046-e865c08a-271c-4382-868a-b5e329475003.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85812
  cosmetic: 39053
  scriptlet: 17972
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 62307-52, 1d.10h.34m
    easyprivacy: 30671-1170, 1d.10h.33m
    plowe-0: 3670-863, 9d.16h.4m
    ublock-abuse: 76-0, 10d.12h.9m
    ublock-badware: 4321-105, 3d.8h.13m
    ublock-filters: 32968-117, 3d.8h.12m
    ublock-privacy: 246-1, 10d.12h.8m
    ublock-quick-fixes: 286-11, 35m
    ublock-unbreak: 1863-42, 3d.8h.11m
    urlhaus-1: 8945-0, 34m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 131 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    appacademy.io: 2
    googletagmanager.com: 1
    vimeocdn.com: 5
```
</details>

**Comment by mapx-** [comment]
Test this filter

`@@||my.appacademy.io/_content/Blazor-Analytics/blazor-analytics.js$script,1p`

**Comment by stephenhawk8054** [comment]
> Test this filter
> 
> `@@||my.appacademy.io/_content/Blazor-Analytics/blazor-analytics.js$script,1p`

I can reproduce and confirm this works.

@ryanbr

**Comment by barry505** [comment]
Thanks, that worked.
