### ISSUE TITLE
bold.dk: ads

### ISSUE THREAD

**Issue by Mickey182** [uBlockOrigin/uAssets#15147]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bold.dk/fodbold/stillinger/superligaen/nyheder/randers-frygter-koeb-af-billetter-fra-broendby-fans/`

### Category

ads

### Describe the issue

Bold.dk is showing ads before every video now

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![Screenshot (56)](https://user-images.githubusercontent.com/58091794/193866972-90b2eca3-0551-41af-8f4e-d21a4f6a4839.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 89629
  cosmetic: 39545
  scriptlet: 17906
  html: 753
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33576-33, 3d.15h.46m
    ublock-badware: 4330-0, 3d.15h.45m
    ublock-privacy: 273-0, 3d.3h.37m
    ublock-abuse: 76-0, 3d.3h.36m
    ublock-unbreak: 1876-0, 3d.15h.44m
    ublock-quick-fixes: 280-5, 11h.14m
    easylist: 62964-607, 3d.15h.43m
    easyprivacy: 30632-1703, 3d.15h.41m
    urlhaus-1: 12668-0, 11h.13m
    plowe-0: 3665-3, 3d.15h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 216 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    adnami.io: 2
    doubleclick.net: 1
    fwmrm.net: 2
    gemius.pl: 1
    googletagmanager.com: 3
    keppet.com: 2
    onthe.io: 1
    permutive.com: 1
    sentry.io: 2
    stickyadstv.com: 4
    userreport.com: 1
```
</details>

**Comment by mapx-** [comment]
You didn't enable `NOR, DNK, ISL: Dandelion Sprouts nordiske filtre` list

**Comment by TotoYY07** [comment]
@ghajini, Will you please take a look at this one?

Ads left overs

name: uBlock Origin Lite
version: 2025.1207.2142
browser: Edge 143 (win)
filtering:
 site: complete
 default: complete
permission: all
rulesets:
 +adguard-spyware-url
 +annoyances-cookies
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 -deu-0
 -pgl
 -pol-0
 -rou-1
 -spa-1
 -swe-1
 -tur-0
 -ublock-badware
 -urlhaus-full
 easylist
 easyprivacy
 nor-0
 ublock-filters

<img width="930" height="854" alt="Image" src="https://github.com/user-attachments/assets/11849805-6998-4ffe-9b9c-fd74c11ded5c" />

**Comment by ghajini** [comment]
i could not reproduce ads/leftovers ,i navigated to `https://bold.dk/fodbold/kamp/granada-feminino-vs-real-madrid-femenino-k/2025-12-13/16304999/startopstilling` or links under `https://bold.dk/tv`

i only see top ad placeholder `bold.dk##.bold-ad-top-wallpaper-1`

**Comment by mapx-** [comment]
@TotoYY07 provide exact link where you got it

**Comment by TotoYY07** [comment]
@ghajini, @mapx-, Sorry, I cannot reproduce the exact same ads/leftovers as the above screenshot.

But if you click on 'Livescore' or 'TV' I see a leftover.

https://bold.dk/livescore

https://bold.dk/tv

This leftover is under the section 'Livescore':

<img width="1251" height="699" alt="Image" src="https://github.com/user-attachments/assets/574c2a47-bf76-47b8-9d7a-e71a2f275fe2" />

**Comment by ghajini** [comment]
This will work
```adb
bold.dk##.wrapper-banner
bold.dk##.integration-wrapper
bold.dk##.mobile-ad-wrapper
```
cc @DandelionSprout
