### ISSUE TITLE
animenewsnetwork.com: breakage

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#15149]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.animenewsnetwork.com/encyclopedia/people.php?id=30364`

### Category

breakage

### Describe the issue

Incorrect blocking of uBlock₀ filters
`animenewsnetwork.com##.ad_by:upward(3)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 37017
  cosmetic: 36880
  scriptlet: 22470
  html: 1677
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    JPN-1: null
  added: 
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-annoyances.txt: 9713-586, never
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 50383-2307, never
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-social.txt: 2568-2, never
    adguard-spyware-url: 769-3, now
    ublock-annoyances: 4869-84, never
  default: 
    ublock-filters: 33798-7845, 4h.19m
    ublock-badware: 4345-0, now
    ublock-privacy: 273-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1878-2, now
    ublock-quick-fixes: 287-0, now
filterset (user): [array of 20 redacted]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 825 ms
  maxAssetCacheWait: 490 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    animenewsnetwork.com: 3
    googletagmanager.com: 1
    skimresources.com: 2
```
</details>

**Comment by mapx-** [comment]
enable back:

```
easylist: null
easyprivacy: null
```

**Comment by Yuki2718** [comment]
I can reproduce the issue with default, but not on the provided link but on the top page and only on Chrome.
