### ISSUE TITLE
mathsolver.microsoft.com: ads

### ISSUE THREAD

**Issue by donefool** [uBlockOrigin/uAssets#15148]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mathsolver.microsoft.com/en`

### Category

ads

### Describe the issue

On entering mathsolver.microsoft.com there is an image in the center talking about "Free Back to School Live Math Help"
When you click it, you are taken here:

`https://takelessons.com/live/math?utm_source=msmathsolver&utm_medium=display&utm_campaign=tll_newlp&utm_content=ad1v1b2s`

When you select it in the element picker, it displays this:

`||bingedu.azureedge.net/mathuxjs/image/TL6/Ad%201%20-%20Version%201%20Mobile.png`

Since both links have the word 'Ad' in the name I think this can be considered an ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/109040621/193875036-8e89b2e6-6152-4d06-a6f9-a914ab153bd4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85933
  cosmetic: 39096
  scriptlet: 18014
  html: 775
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33816-46, now
    ublock-badware: 4345-0, now
    ublock-privacy: 273-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1878-1, now
    ublock-quick-fixes: 287-0, now
    easylist: 62369-615, now
    easyprivacy: 30687-1706, now
    urlhaus-1: 8945-0, now
    plowe-0: 3672-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1850 ms
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    microsoft.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`mathsolver.microsoft.com##[aria-label^="Advertisment"]`

@ryanbr
