### ISSUE TITLE
freetron.top: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15157]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freetron.top/adblock.html`

### Category

detection

### Describe the issue

Detection adblock 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 91045
  cosmetic: 27580
  scriptlet: 18044
  html: 775
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33887-304, 1d.21h.55m
    ublock-badware: 4345-0, 1d.21h.54m
    ublock-privacy: 273-1, 1d.21h.54m
    ublock-abuse: 76-0, 1d.21h.54m
    ublock-unbreak: 1881-0, 1d.21h.54m
    ublock-quick-fixes: 280-0, 18h.19m
    adguard-mobile: 8151-167, 1d.21h.54m
    easylist: 62315-18424, 1d.21h.54m
    easyprivacy: 30672-1716, 1d.21h.54m
    urlhaus-1: 12668-0, 18h.18m
    plowe-0: 3669-3, 1d.21h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 677 ms (selfie)
  maxAssetCacheWait: 309 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- provide the steps to reproduce the issue
- provide a test account if necessary

**Comment by mapx-** [comment]
getting  `VPN/ Proxy is not allowed!` even without vpn, someone else should investigate

**Comment by krystian3w** [comment]
On desktop works:

```adb
! https://freetron.top/
$script,domain=freetron.top,redirect-rule=noopjs
$xhr,domain=freetron.top,redirect-rule=noop.txt
$frame,domain=freetron.top,redirect-rule=noop.html
```

Maybe someone rewrite to specific redirect or scriptlet.
