### ISSUE TITLE
ebay.com: breakage

### ISSUE THREAD

**Issue by MerrickZ** [uBlockOrigin/uAssets#15155]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw=zv-1&_sacat=0`

### Category

breakage

### Describe the issue

shopping items are missing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![屏幕截图 2022-10-05 110227](https://user-images.githubusercontent.com/1021332/193971972-1d038639-3f61-4e3c-afde-118b9019b8dd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 104739
  cosmetic: 49224
  scriptlet: 18141
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 29271-86, 4h.44m
    easylist: 62323-85, 1d.12h.43m
    easyprivacy: 30681-1194, 1d.12h.42m
    plowe-0: 3670-865, 8d.12h.52m
    ublock-abuse: 76-0, 3h.49m
    ublock-badware: 4341-105, 3h.48m
    ublock-filters: 33084-137, 3h.47m
    ublock-privacy: 249-1, 3h.45m
    ublock-quick-fixes: 284-12, 4h.43m
    ublock-unbreak: 1865-43, 3h.44m
    urlhaus-1: 8945-0, 4h.42m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 533 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    ebay.com: 2
    ebaystatic.com: 3
    perfdrive.com: 4
```
</details>

**Comment by mapx-** [comment]
> Chromium: 106

is this chrome or other (brave, edge , ...) ?

**Comment by MerrickZ** [comment]
edge, and it's just fine if I disable ublock on this site. weird.
________________________________
发件人: mapx ***@***.***>
发送时间: 2022年10月5日 上午 11:54
收件人: uBlockOrigin/uAssets ***@***.***>
抄送: Merrick Zhang ***@***.***>; Author ***@***.***>
主题: Re: [uBlockOrigin/uAssets] ebay.com: breakage (Issue #15155)


Chromium: 106

is this chrome or other (brave, edge , ...) ?

―
