### ISSUE TITLE
bricodepot.ro

### ISSUE THREAD

**Issue by mortyam** [uBlockOrigin/uAssets#15151]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bricodepot.ro`

### Describe the issue

There is a cookie pop-up on the screen when I open the website.

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 105

### Settings

Default settings+ublock annoyances+adguard annoyances

**Comment by mapx-** [comment]
Enable fanboy's annoyances list

or 

add
`/gdprcookie/*`

or report at adguard annoyances list
