### ISSUE TITLE
donate.fundhero.io: breakage

### ISSUE THREAD

**Issue by milespomeroy** [uBlockOrigin/uAssets#15152]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://donate.fundhero.io/miles-pomeroy-for-utah`

### Category

breakage

### Describe the issue

buttons don't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 105
filterset (summary): 
  network: 85787
  cosmetic: 39036
  scriptlet: 17990
  html: 772
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33738-45, 4d.1h.34m
    ublock-badware: 4325-0, 4d.1h.33m
    ublock-privacy: 273-0, 8d.4h.6m
    ublock-abuse: 76-0, 8d.4h.7m
    ublock-unbreak: 1876-0, 4d.1h.35m
    easylist: 62272-611, 3d.21h.31m
    easyprivacy: 30643-1706, 3d.21h.32m
    plowe-0: 3670-3, 8d.4h.5m
    urlhaus-1: 8945-0, 2h.52m
    ublock-quick-fixes: 289-0, 2h.51m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1853 ms (selfie)
  maxAssetCacheWait: 318 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    amplitude.com: 1
    googletagmanager.com: 1
    sentry-cdn.com: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||browser.sentry-cdn.com/*/bundle.min.js$script,domain=fundhero.io`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0d86d3951b1abdb03f5d58d2a65631fa8d048331
