### ISSUE TITLE
contactpoints.org: breakage

### ISSUE THREAD

**Issue by studentBur12** [uBlockOrigin/uAssets#15153]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://contactpoints.org/`

### Category

breakage

### Describe the issue

Website worked fine, but then scrolling broke. Issue fixed by Allowing Third Party scripts in the advanced/ dynamic filtering, then opening the website in a new tab. (Allowing Third Party scripts then refreshing the page did not fix the issue.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 89152
  cosmetic: 38972
  scriptlet: 17913
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62213-52, 7d.11h.47m
    easyprivacy: 30689-1170, 1h.40m
    plowe-0: 3665-860, 4d.10h.26m
    ublock-abuse: 76-0, 14h.24m
    ublock-badware: 4341-105, 1h.39m
    ublock-filters: 33058-114, 14h.23m
    ublock-privacy: 246-1, 10d.17h.5m
    ublock-unbreak: 1863-42, 1d.19h.32m
    urlhaus-1: 12383-0, 1d.1h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 1636 ms (selfie)
  maxAssetCacheWait: 784 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> easylist: 62213-52, **7d**.11h.47m

Update all your lists, disable other extensions, test again

**Comment by dportvine** [comment]
> @@||googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5,domain=contactpoints.org

@stephenhawk8054 

How did you insert the highlighted code?

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/195108595-0d7d1a2c-d532-45a2-9c60-d36adf26bf6e.png)
