### ISSUE TITLE
1664965710057.dd6ef8.site: ads

### ISSUE THREAD

**Issue by 10bClass-57Litsey** [uBlockOrigin/uAssets#15159]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://1664965710057.dd6ef8.site/`

### Category

ads

### Describe the issue

Redirect to this page for unexpected denial of a public site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 109281
  cosmetic: 49250
  scriptlet: 19188
  html: 778
listset (total-discarded, last updated): 
  added: 
    RUS-0: 42229-1066, 23h.35m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33842-310, 2d.22h.30m
    ublock-badware: 4334-0, 2d.22h.29m
    ublock-privacy: 273-1, 2d.15h.34m
    ublock-abuse: 76-0, 2d.15h.33m
    ublock-unbreak: 1881-0, 2d.22h.27m
    ublock-quick-fixes: 226-0, 23h.34m
    adguard-mobile: 8151-167, 2d.22h.28m
    easylist: 62327-18431, 23h.37m
    easyprivacy: 30687-1716, 23h.38m
    urlhaus-1: 12668-0, 23h.36m
    plowe-0: 3670-3, 23h.39m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 753 ms (selfie)
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> Redirect to this page for unexpected denial of a public site


redirect from .. where ?

**Comment by 10bClass-57Litsey** [comment]
https://hostiq.ua/wiki/phpversion or other Ukrainian site. Request via Russian server

**Comment by 10bClass-57Litsey** [comment]
Ublock may not be able to protect against such redirects.  It's happening at the wrong request level, found out through developer tools.
