### ISSUE TITLE
c.maincaptcha.top: ads

### ISSUE THREAD

**Issue by nicp81** [uBlockOrigin/uAssets#15150]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://c.maincaptcha.top/robot371/`

### Category

ads

### Describe the issue

`https://c.maincaptcha.top/robot371/`  is just an ad that wants you to click on show notifications button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 99997
  cosmetic: 86613
  scriptlet: 30486
  html: 725
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 70812-4826, 1m
    adguard-mobile: 8160-333, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33207-138, 1d.19h.59m
    ublock-badware: 4237-0, 1d.19h.58m
    ublock-privacy: 247-0, 27m
    ublock-abuse: 76-0, 26m
    ublock-unbreak: 1871-0, 1d.19h.57m
    ublock-quick-fixes: 386-0, 13h.42m
    easylist: 69310-505, 25m
    easyprivacy: 27312-133, 24m
    urlhaus-1: 5164-0, 13h.41m
    plowe-0: 3634-450, 9d.20h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 14284 ms (selfie)
  maxAssetCacheWait: 621 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    p-analytics.life: 2
```
</details>

**Comment by mapx-** [comment]
invalid => you have to provide the original page redirecting you to `https://c.maincaptcha.top/robot371/`
