### ISSUE TITLE
techydino.net detected adblock

### ISSUE THREAD

**Issue by natandna** [uBlockOrigin/uAssets#15156]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://techydino.net
https://techydino.net/detected.php?page=https://mdn.lol/blog/best-phones-under-15000-rupees-in-india/
```

### Describe the issue

detected adblock

### Screenshot(s)

https://user-images.githubusercontent.com/112774782/193977503-70e07985-cd39-4ffa-96cd-6b6f65db173d.png

### uBlock Origin version

1.44.5.9

### Browser name and version

chrome Version 106.0.5249.91

### Settings

https://user-images.githubusercontent.com/112774782/193977558-26916e62-9dd1-48dd-8c59-7c6223d5ad47.png

**Comment by mapx-** [comment]
How did you end up at that page?

**Comment by natandna** [comment]
> How did you end up at that page?

this link https://techydino.net/2020/09/14/top-3-logo-maker-apps-for-android/

**Comment by mapx-** [comment]
No: provide `exactly the initial shortlink` and not the landing page

**Comment by natandna** [comment]
> No: provide **exactly the initial shortlink** and not the landing page

clks.pro

**Comment by mapx-** [comment]
How many times have to ask you to provide a working link ? 
Try yourself `clks.pro` in a new tab and you'll get no detection.

**Comment by natandna** [comment]
im click this https://clks.pro/Ojot
its direct to https://techydino.net/2020/09/14/top-3-logo-maker-apps-for-android/
and then to https://techydino.net/detected.php?page=https://mdn.lol/blog/best-phones-under-15000-rupees-in-india/
and then adblock detected

if my answer didnt match just closed, thks for helping

**Comment by mapx-** [comment]
Update all the filter lists

Are you using brave ? => disable the shields for this site
Are you using edge ? => switch from Strict tracking prevention to Balanced

**Comment by mapx-** [comment]
add

`@@||taxedborley.com^$script,domain=blog.mdn.lol`

**Comment by krystian3w** [comment]
It works but allow load crap text ad:

> 64 age old woman with child face! You should try this at night!

maybe safe is:

```adb
##center iframe:not([src])
```
