### ISSUE TITLE
[nsfw] sehuatang.org: ads

### ISSUE THREAD

**Issue by loveqianool** [uBlockOrigin/uAssets#15161]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sehuatang.org/forum.php?mod=viewthread&tid=993822&extra=page%3D1`

### Category

ads

### Describe the issue

[亚博美女赌场]  [澳门新葡京]  [下载领88元] 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![屏幕截图 2022-10-05 200940](https://user-images.githubusercontent.com/739497/194057103-c3af4c25-edd6-4d49-871f-354b3644f569.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 104689
  cosmetic: 49231
  scriptlet: 18114
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 8-0, never
    CHN-0: 29294-87, 2d.20h.10m
    easylist: 62307-85, 2d.20h.11m
    easyprivacy: 30687-1194, 19h.35m
    plowe-0: 3669-864, 11d.19h.48m
    ublock-abuse: 76-0, 2d.20h.5m
    ublock-badware: 4331-105, 2d.20h.6m
    ublock-filters: 33034-137, 2d.20h.7m
    ublock-privacy: 249-1, 7d.7h.11m
    ublock-quick-fixes: 254-11, 15h.33m
    ublock-unbreak: 1863-43, 2d.20h.9m
    urlhaus-1: 8945-0, 15h.34m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 787 ms (selfie)
  maxAssetCacheWait: 417 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    sehuatang.org: 2
```
</details>

**Comment by mapx-** [comment]
add

`sehuatang.org##[class^="show-"]:has(.item.js-appJump),[class^="show-"]:has([target="_blank"])`

@cjx82630

**Comment by cjx82630** [comment]
30分钟后更新 https://github.com/easylist/easylistchina/commit/dea2c7c84249164ae90cc5ddb9527b399a0a72f5
Fixed.Please manually update in 30 minutes.
