### ISSUE TITLE
newyorker.com: breakage

### ISSUE THREAD

**Issue by carstenknoch** [uBlockOrigin/uAssets#15165]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.newyorker.com/culture`

### Category

breakage

### Describe the issue

Page becomes entirely invisible. This cascades "down" into other newyorker.com listing pages. 

Newyorker.com works fine on homepage and article pages (just not article listing/index pages).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 98167
  cosmetic: 176720
  scriptlet: 25622
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59737-87, 7m
    adguard-social: 18583-862, 7m
    fanboy-annoyance: 80759-4759, 7m
    fanboy-cookiemonster: 41184-41184, 7m
    fanboy-social: 23383-23383, 7m
    fanboy-thirdparty_social: 68-21, 7m
    ublock-annoyances: 4848-209, 7m
  default: 
    user-filters: 3-0, never
    easylist: 62307-110, 7m
    easyprivacy: 30689-1259, 7m
    plowe-0: 3672-865, 7m
    ublock-abuse: 76-0, 7m
    ublock-badware: 4341-105, 6m
    ublock-filters: 33093-529, 6m
    ublock-privacy: 249-9, 6m
    ublock-quick-fixes: 304-12, 6m
    ublock-unbreak: 1865-48, 6m
    urlhaus-1: 8947-0, 6m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2013 ms (selfie)
  maxAssetCacheWait: 779 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    newyorker.com: 9
    adobedtm.com: 1
    amazon-adsystem.com: 1
    associates-amazon.com: 1
    bounceexchange.com: 1
    condenastdigital.com: 2
    cookielaw.org: 1
    d1z2jf7jlzjs58.cloudfront.net: 1
    doubleclick.net: 2
    googletagmanager.com: 1
    indexww.com: 1
    keywee.co: 1
    moatads.com: 1
    rlcdn.com: 1
    zqtk.net: 1
```
</details>

**Comment by wertzuz** [comment]
newyorker.com/latest: reinsertion
The subscribe button and the price offer are getting reinserted, when scrolling down the page. Initial blocking by Adguard Ads list but they get reinserted.
right place to report?@mapx-

**Comment by mapx-** [comment]
```adb
newyorker.com##.consumer-marketing-unit
newyorker.com##[href^="https://www.newyorker.com/v2/offers"]
```
