### ISSUE TITLE
kinopoisk.ru: ads

### ISSUE THREAD

**Issue by LeninEnisey** [uBlockOrigin/uAssets#15167]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kinopoisk.ru/film/301/`

### Category

ads

### Describe the issue

Skipped ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://i120.fastpic.org/big/2022/1005/69/ee3a2cca10a8860ae7d8c2051877e869.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 108
filterset (summary): 
  network: 103248
  cosmetic: 60975
  scriptlet: 19248
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    RUS-0: 40655-10, 53m
    easylist: 62307-70, 59m
    easyprivacy: 30689-1288, 58m
    plowe-0: 3670-869, 7d.1h.55m
    ublock-abuse: 76-1, 7d.1h.58m
    ublock-badware: 4341-105, 57m
    ublock-filters: 33093-156, 56m
    ublock-privacy: 249-1, 7d.1h.57m
    ublock-quick-fixes: 304-12, 52m
    ublock-unbreak: 1865-43, 54m
    urlhaus-1: 8947-0, 51m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6719 ms
  maxAssetCacheWait: 670 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    yandex.net: 1
    yandex.ru: 28
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/f937829f867e5defb23b4fb714fb7b686800b007
