### ISSUE TITLE
lernhelfer.de: nuisance

### ISSUE THREAD

**Issue by 10Meisterbaelle** [uBlockOrigin/uAssets#15160]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lernhelfer.de/schuelerlexikon/geschichte/artikel/voelkerwanderung-europa`

### Category

nuisance

### Describe the issue

A popup appears on the page after a while. I have already found a fix, it would be good if it would be implemented into the official filters:
```
www.lernhelfer.de##.underlay
www.lernhelfer.de###bounce-modal
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 ![Screenshot 2022-10-05 at 12-42-35 Völkerwanderung in Europa in Geschichte Schülerlexikon Lernhelfer](https://user-images.githubusercontent.com/45918080/194042884-10ff15f3-c5a6-4e31-9fcd-3bad2fcebd11.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 90087
  cosmetic: 81782
  scriptlet: 22904
  html: 805
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 41184-134, 1h.39m
    ublock-annoyances: 4869-4, 1h.39m
  default: 
    user-filters: 4-0, never
    ublock-filters: 33825-72, 1h.39m
    ublock-badware: 4345-0, 1h.39m
    ublock-privacy: 273-0, 1h.39m
    ublock-abuse: 76-0, 1h.39m
    ublock-unbreak: 1879-1, 1h.39m
    ublock-quick-fixes: 307-0, 1h.39m
    easylist: 62275-636, 1h.39m
    easyprivacy: 30689-1716, 1h.39m
    urlhaus-1: 8957-0, 1h.39m
    plowe-0: 3672-3, 1h.39m
    DEU-0: 5952-2, 1h.38m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 227 ms (selfie)
  maxAssetCacheWait: 193 ms
popupPanel: 
  blocked: 92
  blockedDetails: 
    google-analytics.com: 23
    googletagmanager.com: 23
    googletagservices.com: 23
    yieldlove.com: 23
```
</details>

**Comment by mapx-** [comment]
@ryanbr
