### ISSUE TITLE
UBO does not work with YouTube - Ads appear even when on

### ISSUE THREAD

**Issue by brmonaghan** [uBlockOrigin/uAssets#15166]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I cannot get through YouTube Music or YouTube without ads present.
I tried restarting computer, logging out and in, all to no avail.

### A specific URL where the issue occurs.

https://music.youtube.com/watch?v=N-QcYDP7SDU&list=RDAMVMlhRDUd-J8bM

### Steps to Reproduce

1. Go on YouTube Music or YouTube
2. Play a video
3. Ads appear, even when on.

### Expected behavior

UBO to block these ads even when on.

### Actual behavior

Advertisements are showing in the player.

### uBO version

1.44.4

### Browser name and version

Edge 105

### Operating System and version

Windows 11.0.22621 22H2

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
