### ISSUE TITLE
cbs.com: detection

### ISSUE THREAD

**Issue by Mostafa-Wahied** [uBlockOrigin/uAssets#15168]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cbs.com/shows/video/cKNzWXbM6NrD11kIVHU8EazOh6l2Fvvn/`

### Category

detection

### Describe the issue

after trying the steps to force an update for filter lists it's still detecting ublock and not playing the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 87790
  cosmetic: 39805
  scriptlet: 18036
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 5m
    ara-0: 2601-11, never
  default: 
    user-filters: 0-0, never
    easylist: 62331-53, 5m
    easyprivacy: 30689-1170, 5m
    plowe-0: 3672-863, 5m
    ublock-abuse: 76-0, 5m
    ublock-badware: 4341-105, 5m
    ublock-filters: 33094-123, 5m
    ublock-privacy: 249-1, 5m
    ublock-quick-fixes: 304-12, 5m
    ublock-unbreak: 1865-43, 5m
    urlhaus-1: 8947-0, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 345 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
Still working fine.

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced
