### ISSUE TITLE
ess.barracudanetworks.com: breakage

### ISSUE THREAD

**Issue by ddemick** [uBlockOrigin/uAssets#15172]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ess.barracudanetworks.com/`

### Category

breakage

### Describe the issue

When uBlock Origin is ON all the dashboard text for the website is compressed on top of itself. 

![image](https://user-images.githubusercontent.com/65726854/194376270-1a1bcaa8-7015-4bb8-92d0-2742585afd80.png)

Also, the message log page and other associated pages will not resolve, just spin as "loading" forever.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock origin and Barracuda Networks](https://user-images.githubusercontent.com/65726854/194376505-0ca8a57d-fc64-4569-ad20-45eb34c9f23d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85896
  cosmetic: 38966
  scriptlet: 18037
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62307-53, 1d.3h.31m
    easyprivacy: 30689-1170, 1d.3h.29m
    plowe-0: 3672-863, 2d.3h.34m
    ublock-abuse: 76-0, 3d.3h.42m
    ublock-badware: 4342-105, 3d.3h.41m
    ublock-filters: 33030-120, 3d.3h.40m
    ublock-privacy: 249-1, 3d.3h.39m
    ublock-quick-fixes: 324-11, 3h.26m
    ublock-unbreak: 1859-42, 3d.3h.38m
    urlhaus-1: 8871-0, 3h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 179 ms (selfie)
  maxAssetCacheWait: 57 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    barracudanetworks.com: 1
    google-analytics.com: 1
    mxpnl.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
Could you provide a test account ?

if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
-

**Comment by mapx-** [comment]
Test this filter

`@@||mxpnl.com/libs/mixpanel-*.min.js$domain=barracudanetworks.com`
