### ISSUE TITLE
old.reddit.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#15173]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://old.reddit.com/r/bugs/comments/nax0lu/updates_to_post_requirements/`

### Category

nuisance

### Describe the issue

Internal links are modified to add tracking parameters when you click on them.  

`AdGuard URL Tracking Protection` removes tracking parameters from requests. The problem is that the full links are still added to the user's history. Since there are many internal links on Reddit, it's an annoyance to see so many history entries with `utm`. Please disable this script function for this specific site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/110785003/194397599-99099045-a3a2-4daa-81e1-ec62e16020b2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 91668
  cosmetic: 91969
  scriptlet: 23964
  html: 806
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 781-3, now
    adguard-annoyance: 59631-764, now
    ublock-annoyances: 4869-4, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33827-47, now
    ublock-badware: 4345-0, now
    ublock-privacy: 273-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1879-2, now
    ublock-quick-fixes: 337-0, now
    easylist: 62462-622, now
    easyprivacy: 30694-1706, now
    urlhaus-1: 8871-0, now
    plowe-0: 3672-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4878 ms
  maxAssetCacheWait: 742 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    reddit.com: 2
    redditmedia.com: 1
```
</details>

**Comment by krystian3w** [comment]
Needed investigation how is added (if exist in `view-source:` then needed wait to trusted scriptlet system: https://github.com/uBlockOrigin/uBlock-issues/issues/2229)

Or mapx- again edit own `us.js` file: https://github.com/uBlockOrigin/uAssets/issues/14849#issuecomment-1248962943

**Comment by mapx-** [comment]
I get no params on r/bugs ?!

**Comment by krystian3w** [comment]
How?

`https://old.reddit.com/r/bugs?utm_source=reddit&utm_medium=usertext&utm_name=bugs&utm_content=t3_nax0lu`

**Comment by mapx-** [comment]
Now I see only when clicking r/bugs the params are attached on fly

**Comment by mapx-** [comment]
it seems no filter from `AdGuard URL Tracking Protection` is not triggered in this case, your aeld seems working, I wonder if the similar for click should be added

**Comment by krystian3w** [comment]
The mousedown no cover mobile environment "events".

**Comment by Yuki2718** [comment]
On my end AGURLTP is working fine. utm attached, but on the page transition all removed.

**Comment by Yuki2718** [comment]
So it's annoyance than privacy. I don't think that's worth the risky scriptlet filter (yes, confirmed we can't narrow down that).
