### ISSUE TITLE
app.chroniclebot.com: breakage

### ISSUE THREAD

**Issue by bekriebel** [uBlockOrigin/uAssets#15171]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.chroniclebot.com/notifier/new`

### Category

breakage

### Describe the issue

Chronicle Bot is designed to connect a google calendar to Discord. On first load, uBlock is blocking Google APIs and preventing the linking of a Google account, which is a primary function of the page.

Refreshing the page seems to unblock the APIs and allow logins.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

### First page load:
![image](https://user-images.githubusercontent.com/183779/194354377-63ebe99a-6a8b-4f85-a7ef-48e89cca3d26.png)
![image](https://user-images.githubusercontent.com/183779/194355803-08dabbe0-52a7-438e-a005-5dd5693ad6dd.png)

### After refresh:
![image](https://user-images.githubusercontent.com/183779/194356155-cdc42e64-c1b7-42ba-9b56-ca59debb07ce.png)
![image](https://user-images.githubusercontent.com/183779/194356086-c519feba-8f21-45f3-83d0-1b14e33fb3d1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85825
  cosmetic: 39047
  scriptlet: 18041
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62271-52, 5d.13h.44m
    easyprivacy: 30644-1170, 5d.13h.42m
    plowe-0: 3670-863, 7d.17h.15m
    ublock-abuse: 76-0, 12d.14h.39m
    ublock-badware: 4342-105, 3d.13h.16m
    ublock-filters: 33049-117, 3d.13h.15m
    ublock-privacy: 249-1, 3d.13h.14m
    ublock-quick-fixes: 324-11, 8h.55m
    ublock-unbreak: 1863-42, 3d.13h.13m
    urlhaus-1: 8943-0, 8h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 125 ms (selfie)
  maxAssetCacheWait: 83 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    chroniclebot.com: 4
    sentry.io: 6
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

repeat twice these steps (on the first page load and then on refresh)

**Comment by bekriebel** [comment]
This seems to be resolved with current filter sets.
