### ISSUE TITLE
slickdeals.net: breakage

### ISSUE THREAD

**Issue by Stinking8985** [uBlockOrigin/uAssets#15189]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slickdeals.net/f/16078159-2-pack-hp-m24f-23-8-1080p-ips-led-backlit-monitor-235-free-s-h?page=2`

### Category

breakage

### Describe the issue

The AWIN affiliate links are not clicking through properly when uBlock is turned on.  The new tab opens and then shuts immediately.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85811
  cosmetic: 38986
  scriptlet: 18055
  html: 785
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33827-46, 2d.8h.15m
    ublock-badware: 4345-0, 2d.8h.14m
    ublock-privacy: 273-0, 2d.8h.13m
    ublock-abuse: 76-0, 2d.8h.12m
    ublock-unbreak: 1878-1, 2d.8h.11m
    ublock-quick-fixes: 341-0, 4h.3m
    easylist: 62307-616, 2d.8h.9m
    easyprivacy: 30689-1706, 2d.8h.8m
    urlhaus-1: 8759-0, 4h.2m
    plowe-0: 3672-3, 2d.8h.6m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 651 ms (selfie)
  maxAssetCacheWait: 220 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    slickdeals.net: 1
    ad.gt: 1
    amazon-adsystem.com: 1
    btttag.com: 2
    demdex.net: 1
    doubleclick.net: 1
    facebook.net: 1
    googletagmanager.com: 2
    heapanalytics.com: 1
    hotjar.com: 1
    pinimg.com: 1
    quantserve.com: 1
    videoplayerhub.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
> The AWIN affiliate links

Can you screenshot the positions of those links?

**Comment by mapx-** [comment]
@stephenhawk8054 just click "see deal"

see https://forums.lanik.us/viewtopic.php?p=165058-awin1-com&hilit=zenaps#p165058

**Comment by mapx-** [comment]
However there are cases impossible to deal with:

- go to 
`https://slickdeals.net/f/16071871-select-staples-stores-128gb-11-apple-ipad-pro-space-gray-649-in-store-only?src=rcm_category_h`
- click `See Deal` on the right side
- to reach the target store we should have something like this:

```
@@||dpbolvw.net/click-$document,domain=dpbolvw.net
@@||emjcd.com^$document,domain=emjcd.com
@@||ad.doubleclick.net/ddm/clk/*?storeId=$document,domain=ad.doubleclick.net
```

"killing" filters from EL, EP, Peter's Lowe lists

**Comment by mapx-** [comment]
@Stinking8985 

Just use the filters that @MasterKia has crafted above, we can't fix such "issues" (obviously due to lot of tracking that slickdeals could just avoid using direct store links).

or .. just click "Proceed" when getting strictly blocking stuff

@ryanbr
