### ISSUE TITLE
help.getpocket.com: breakage

### ISSUE THREAD

**Issue by SimplesmenteMaria** [uBlockOrigin/uAssets#15188]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://help.getpocket.com/`

### Category

breakage

### Describe the issue

`AdGuard Annoyances` breaks the `Contact Pocket Support` link. This is the only way to contact Pocket. Closed without a solution for uBlock Origin users: https://github.com/AdguardTeam/AdguardFilters/issues/131632

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 90811
  cosmetic: 92011
  scriptlet: 23980
  html: 806
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59670-765, 2h.17m
    ublock-annoyances: 4869-4, 2h.17m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33843-142, 2h.17m
    ublock-badware: 4350-0, 2h.17m
    ublock-privacy: 274-0, 2h.17m
    ublock-abuse: 76-0, 2h.17m
    ublock-unbreak: 1881-1, 2h.17m
    ublock-quick-fixes: 341-0, 2h.16m
    easylist: 62485-512, 2h.16m
    easyprivacy: 30695-1720, 2h.16m
    urlhaus-1: 8759-0, 2h.16m
    plowe-0: 3671-3, 2h.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1659 ms (selfie)
  maxAssetCacheWait: 840 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    helpscout.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||beacon-v2.helpscout.net^$script,domain=help.getpocket.com`

maybe @Yuki2718 could add the exception in AG list

**Comment by Yuki2718** [comment]
I'm just a collaborator so always follow their decesion, OTOH we, as a principle, fix only issues for default lists and AGA is not default. I commented in the AG issue.
