### ISSUE TITLE
winteriscoming.net: breakage

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#15187]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://winteriscoming.net/2022/10/03/walking-dead-boss-explains-spoiler-spinoff-announcements/`

### Category

breakage

### Describe the issue

some if not all images are not displaying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-10-07 110800](https://user-images.githubusercontent.com/24624945/194622356-24756b9e-15cb-4e59-9d3a-875387d3e6c3.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b13
Firefox: 105
filterset (summary): 
  network: 164393
  cosmetic: 84705
  scriptlet: 21325
  html: 815
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 453-0, 27m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 468-1, 27m
    https://www.i-dont-care-about-cookies.eu/abp/: 25392-4, 27m
    adguard-spyware-url: 782-3, 28m
    block-lan: 44-0, 28m
    curben-phishing: 74664-3, 28m
    curben-pup: 195-0, 28m
    fanboy-social: 23384-9, 27m
    ublock-annoyances: 4863-9, 27m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33826-146, 28m
    ublock-badware: 4350-0, 28m
    ublock-privacy: 274-0, 28m
    ublock-abuse: 76-0, 28m
    ublock-unbreak: 1881-4, 28m
    ublock-quick-fixes: 330-0, 28m
    easylist: 62526-271, 28m
    easyprivacy: 30695-1194, 28m
    urlhaus-1: 8759-0, 28m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  largeMediaSize: 1024
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}} {{url}}
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 115 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    amazon-adsystem.com: 1
    d3ujids68p6xmq.cloudfront.net: 2
    datadoghq.com: 1
    doubleclick.net: 1
    gammamaximum.com: 1
    googletagmanager.com: 1
    onetrust.com: 1
    outbrain.com: 1
    scorecardresearch.com: 1
    sharethrough.com: 2
    spot.im: 9
    wazimo.com: 2
    webcontentassessor.com: 2
```
</details>

**Comment by troysjanda** [comment]
> Disable this option and test again.

not enabled.

**Comment by troysjanda** [comment]
uBlock Origin: 1.44.5b13
Firefox: 105
filterset (summary): 
  network: 164393
  cosmetic: 84705
  scriptlet: 21325
  html: 815
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 453-0, 45m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 468-1, 45m
    https://www.i-dont-care-about-cookies.eu/abp/: 25392-4, 45m
    adguard-spyware-url: 782-3, 46m
    block-lan: 44-0, 46m
    curben-phishing: 74664-3, 46m
    curben-pup: 195-0, 46m
    fanboy-social: 23384-9, 45m
    ublock-annoyances: 4863-9, 45m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33826-146, 46m
    ublock-badware: 4350-0, 46m
    ublock-privacy: 274-0, 46m
    ublock-abuse: 76-0, 46m
    ublock-unbreak: 1881-4, 46m
    ublock-quick-fixes: 330-0, 46m
    easylist: 62526-271, 46m
    easyprivacy: 30695-1194, 46m
    urlhaus-1: 8759-0, 46m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}} {{url}}
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 115 ms

**Comment by troysjanda** [comment]
here is the logger for blocked items using the -- filter
![loggerresults for blocked items](https://user-images.githubusercontent.com/24624945/194626344-57ada917-ac4b-4f11-ac7b-4c6671131a4a.png)

**Comment by mapx-** [comment]
what about the cosmetic filters ? (don't use "--", use "blocked" when hovering upon the search box in the logger )

**Comment by troysjanda** [comment]
Closing without further issue, seems that the network admin enabled pfsense/pfblockerng-dev dnsbl and there was entries for images and geolocation scripts that were the cause using the Stevenblack list. he has since updated and removed that list since it seems to be very restrictive and causing others to have a lot of website breakage.
