### ISSUE TITLE
bestiefy.com: privacy

### ISSUE THREAD

**Issue by Handoff2901** [uBlockOrigin/uAssets#15183]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bestiefy.com/`

### Category

privacy

### Describe the issue

`https://kinesis.us-east-1.amazonaws.com/` is a fingerprinter, caused by the `tyche` problem we've talked about before.

In the request body:

```
{"Records":[{"Data":"(base64 json string redacted for privacy)"}],"StreamName":"apps-production"}
```

I used cyberchef to convert this and it's a fingerprint of me. Here is a redacted version:

```
{"event_type":"page_views","id":"redacted","ramp_session_id":"redacted","sampling_rate":1,"timestamp":"2022-10-07 07:45:07.695","version":"0.8.0","website_id":73547,"publisher_id":1024665,"website_categories":["games_casual","entertainment"],"country_code":"redacted","page_url":"https://bestiefy.com/","page_hostname":"bestiefy.com","referrer_url":"https://bestiefy.com/q?=wAgSj","referrer_hostname":"bestiefy.com","user_agent":"redacted.0","ads_blocked":true,"screen_width":redacted,"screen_height":redacted,"screen_orientation":"redacted","window_width":redacted,"window_height":redacted}
```

This is after creating a quiz. My bogus quiz is at `https://bestiefy.com/q?=s6tHy` if you want to test this.

We likely need to look into how to block everything in tyche besides the `addUnits` function and related things, especially on bestiefy, because it keeps bouncing back with new breakage or fingerprinters.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 206511
  cosmetic: 216141
  scriptlet: 38410
  html: 806
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
  added: 
    adguard-generic: 65948-5195, 7h.25m
    adguard-mobile: 8133-10, 7h.25m
    adguard-spyware: 34340-15851, 7h.25m
    adguard-spyware-url: 781-4, 7h.25m
    block-lan: 43-0, 20d.13h.34m
    curben-phishing: 75462-3, 2h.55m
    curben-pup: 195-0, 2h.54m
    adguard-annoyance: 59798-5154, 3d.10h.23m
    adguard-social: 18585-1067, 3d.10h.24m
    fanboy-thirdparty_social: 68-0, 6d.15h.21m
    fanboy-annoyance: 80683-64708, 6d.15h.20m
    fanboy-cookiemonster: 41181-149, 2d.11h.30m
    fanboy-social: 23366-28, 6d.15h.18m
    ublock-annoyances: 4869-4, 7h.25m
  default: 
    user-filters: 14-2, never
    ublock-filters: 33828-65, 7h.25m
    ublock-badware: 4345-0, 7h.25m
    ublock-privacy: 273-0, 3d.12h.32m
    ublock-abuse: 76-0, 3d.12h.31m
    ublock-unbreak: 1879-1, 7h.25m
    ublock-quick-fixes: 337-0, 2h.57m
    easylist: 62272-522, 6d.12h.54m
    easyprivacy: 30643-1192, 6d.12h.53m
    urlhaus-1: 8841-0, 2h.56m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 563 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    agkn.com: 1
    amazon-adsystem.com: 1
    crwdcntrl.net: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    id5-sync.com: 1
    moatads.com: 2
```
</details>

**Comment by Handoff2901** [comment]
One thing:

It is (partially) effective and doesn't break if you block `https://cdn.intergient.com/ramp.js` for tracking prevention. The fingerprint issue remains though.

**Comment by Handoff2901** [comment]
@mapx- issue still remains with `https://kinesis.us-east-1.amazonaws.com/`

**Comment by mapx-** [comment]
Did you update all your lists ?

**Comment by Handoff2901** [comment]
I will check

**Comment by Handoff2901** [comment]
Fixed now, but one other thing:

These URLs are stupidly long files that were loaded by tracking code, which, while harmless (the closest to doing anything bad is the PageOS code storing fingerprinting data in localstorage), take up loading time/bandwidth because the only purpose is for use in fingerprinting, ads, and tracking.

I blocked them in DevTools. It improves page load time, likely improves privacy (due to the site often adding new fingerprinters in after the individual URLs are blocked), and doesn't break the site:
* `https://config.playwire.com/audience_segments/config.json`
* `https://cdn.intergient.com/pageos/1.8.17/123.99f45c8adac09db92bfc.js`
* `https://cdn.intergient.com/pageos/1.8.17/nielsen.b850d86715bcafaea630.js`
* `https://cdn.intergient.com/pageos/js/libs/aws-sdk-kinesis.min.js.br`
