### ISSUE TITLE
fparf.comdi.com: breakage

### ISSUE THREAD

**Issue by Dfcz2** [uBlockOrigin/uAssets#15184]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fparf.comdi.com/watch/esqh2oco`

### Category

breakage

### Describe the issue

nobody is looking at your issue over your shoulder

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 236879
  cosmetic: 183306
  scriptlet: 39524
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59637-2051, 4h.59m
    adguard-generic: 65948-1018, 4h.58m
    adguard-mobile: 8135-82, 4h.58m
    adguard-social: 18544-1973, 4h.58m
    adguard-spyware: 34341-3782, 4h.58m
    adguard-spyware-url: 781-1, 4h.57m
    block-lan: 44-0, 14d.3h.7m
    curben-phishing: 75626-1, 4h.56m
    curben-pup: 195-1, 4h.56m
    dpollock-0: 11389-295, 4h.59m
    fanboy-annoyance: 80755-37642, 4h.59m
    fanboy-cookiemonster: 41191-41191, 4h.59m
    fanboy-social: 23383-23383, 4h.57m
    fanboy-thirdparty_social: 69-21, 4h.59m
    ublock-annoyances: 4847-243, 4h.57m
  default: 
    user-filters: 1-0, never
    RUS-0: 40664-870, 4h.57m
    easylist: 62463-18688, 4h.58m
    easyprivacy: 30694-14042, 4h.58m
    plowe-0: 3672-1385, 4h.59m
    ublock-abuse: 76-1, 4h.59m
    ublock-badware: 4341-240, 4h.57m
    ublock-filters: 33093-4154, 4h.57m
    ublock-privacy: 249-49, 4h.59m
    ublock-quick-fixes: 324-23, 4h.56m
    ublock-unbreak: 1866-101, 4h.57m
    urlhaus-1: 8841-1, 4h.56m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16644 ms (selfie)
  maxAssetCacheWait: 11335 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> Describe the issue: nobody is looking at your issue over your shoulder

?

If you still want to be helped provide the explanation / (steps to reproduce) of the issue.
Test using ONLY the default lists.

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Authorization required. I think a screenshot of the logger could clarify something. But the uBO settings must be reset to default before that.
