### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by MandL27** [uBlockOrigin/uAssets#15180]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mobile.twitter.com/`

### Category

breakage

### Describe the issue

Retweet button does nothing instead of opening the retweet/QRT menu with uBO enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 102
filterset (summary): 
  network: 134569
  cosmetic: 163415
  scriptlet: 38442
  html: 808
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-44, 1m
    adguard-generic: 65948-5588, 1m
    adguard-spyware: 34341-15937, 1m
    adguard-annoyance: 59636-5357, 1m
    adguard-social: 18544-1688, 1m
    fanboy-thirdparty_social: 69-1, 1m
    fanboy-annoyance: 80755-68948, 1m
    fanboy-cookiemonster: 41191-17011, 1m
    fanboy-social: 23383-13717, 1m
    ublock-annoyances: 4893-10, 1m
  default: 
    user-filters: 18-2, never
    ublock-filters: 33933-367, 2m
    ublock-badware: 4344-0, 2m
    ublock-privacy: 273-1, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1884-1, 2m
    adguard-mobile: 8135-167, 1m
    easylist: 62463-18371, 1m
    easyprivacy: 30694-1764, 1m
    urlhaus-1: 8841-0, 1m
    plowe-0: 3672-4, 1m
    ublock-quick-fixes: 337-0, 1m
filterset (user): [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 904 ms (selfie)
  maxAssetCacheWait: 918 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    twitter.com: 6
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Reset uBO to defaults settings / filter lists then test again without adding other lists

**Comment by MandL27** [comment]
That was it. Thought I had tested without other included lists but I hadn't. Thanks!
