### ISSUE TITLE
dzen.ru: ads

### ISSUE THREAD

**Issue by grashooper** [uBlockOrigin/uAssets#15181]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dzen.ru/video/watch/5f16c53d47ab6233e0a5d7db`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 103079
  cosmetic: 61067
  scriptlet: 19256
  html: 789
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33829-46, 1d.1h.3m
    ublock-badware: 4345-0, 1d.1h.2m
    ublock-privacy: 273-0, 1d.1h.1m
    ublock-abuse: 76-0, 1d.1h
    ublock-unbreak: 1878-1, 1d.58m
    ublock-quick-fixes: 337-0, 12h.31m
    easylist: 62304-610, 5d.3h.28m
    easyprivacy: 30671-1704, 5d.3h.27m
    urlhaus-1: 8871-0, 12h.30m
    plowe-0: 3665-3, 5d.3h.25m
    RUS-0: 40666-185, 1d.57m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1761 ms (selfie)
  maxAssetCacheWait: 751 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    mail.ru: 2
    yandex.net: 1
    yandex.ru: 15
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is a new Yandex domain. Ads on this domain are blocked by the [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe).
