### ISSUE TITLE
link1s.net: detection

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#15196]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://link1s.net/lr1f6ola`

### Category

detection

### Describe the issue

Ublock Detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 101286
  cosmetic: 114869
  scriptlet: 26180
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    adguard-annoyance: 59684-1658, 39m
    adguard-social: 18551-1961, 1h.3m
    adguard-spyware: 34346-3332, 21h.9m
    adguard-spyware-url: 782-1, 1h.5m
    block-lan: 44-0, 45m
    fanboy-cookiemonster: 41193-18573, 1d.1h.2m
    fanboy-thirdparty_social: 68-4, 44m
    ublock-annoyances: 4871-206, 1d.1h.2m
  default: 
    user-filters: 3-0, never
    adguard-mobile: 8135-30, 45m
    easylist: 62491-17901, 21h.9m
    easyprivacy: 30695-13846, 1d.1h
    ublock-abuse: 76-0, 1d.59m
    ublock-badware: 4345-103, 1d.59m
    ublock-filters: 33207-784, 1d.59m
    ublock-privacy: 250-43, 1d.59m
    ublock-quick-fixes: 328-12, 46m
    ublock-unbreak: 1873-65, 1d.59m
filterset (user): [array of 3 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: 
  largeMediaSize: 512
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1568 ms (selfie)
  maxAssetCacheWait: 2599 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    eehuzaih.com: 1
    jotpoolwarren.com: 1
```
</details>

**Comment by ghajini** [comment]
again pls follow instructions if you still want to use kiwi
https://github.com/uBlockOrigin/uAssets/issues/15194#issuecomment-1272343226
