### ISSUE TITLE
westchestermagazine.com: popups

### ISSUE THREAD

**Issue by thornofqueens** [uBlockOrigin/uAssets#15195]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://westchestermagazine.com/food/restaurants-food/vegetarian-plant-based-vegan/`

### Category

popups

### Describe the issue

Page generates a pop-up that is not blocked by the filter. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 87170
  cosmetic: 27659
  scriptlet: 18085
  html: 787
listset (total-discarded, last updated): 
  default: 
    user-filters: 67-0, never
    ublock-filters: 33934-306, 2d.19h.17m
    ublock-badware: 4344-0, 2d.19h.14m
    ublock-privacy: 273-1, 12d.54m
    ublock-abuse: 76-0, 10d.21h.19m
    ublock-unbreak: 1883-0, 2d.19h.16m
    ublock-quick-fixes: 317-1, 19h.18m
    adguard-mobile: 8157-29, 2d.19h.13m
    easylist: 62322-18432, 4d.19h.34m
    easyprivacy: 30685-1716, 4d.19h.32m
    urlhaus-1: 8759-0, 17h.41m
    plowe-0: 3670-142, 10d.21h.17m
filterset (user): [array of 67 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4005 ms (selfie)
  maxAssetCacheWait: 85 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    broadstreetads.com: 2
    google.com: 2
    googletagmanager.com: 1
    hs-analytics.net: 1
    hs-banner.com: 1
    hsleadflows.net: 1
    instagram.com: 40
    taboola.com: 1
```
</details>

**Comment by Yuki2718** [comment]
Addressed by AdGuard Annoyances.

**Comment by Yuki2718** [comment]
As now covered by both of annoyance lists, use either one you like.
