### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by Vektor-537** [uBlockOrigin/uAssets#15200]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vk.com/@lnmanga-preimuschestva-reinkarnacii-40-41-glava`

### Category

breakage

### Describe the issue

не грузить перші 3 фото

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://prnt.sc/VTEKxjsawQIZ

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 103002
  cosmetic: 61186
  scriptlet: 19266
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 3d.5h.2m
  default: 
    user-filters: 84-7, never
    RUS-0: 40704-10, 20h.31m
    easylist: 62308-69, 5d.15h
    easyprivacy: 30671-1288, 5d.14h.59m
    plowe-0: 3672-867, 1d.16h.35m
    ublock-abuse: 76-1, 5d.15h.2m
    ublock-badware: 4342-105, 3d.7h.48m
    ublock-filters: 33089-152, 3d.7h.47m
    ublock-privacy: 249-1, 1d.16h.34m
    ublock-quick-fixes: 328-12, 4h.30m
    ublock-unbreak: 1866-43, 3d.7h.46m
    urlhaus-1: 8724-0, 4h.29m
filterset (user): [array of 84 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 728 ms (selfie)
  maxAssetCacheWait: 559 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    mail.ru: 1
    tns-counter.ru: 1
    userapi.com: 6
```
</details>

**Comment by dimisa-RUAdList** [comment]
**EasyPrivacy**
`/1.gif?`
`/2.gif?`
`/3.gif?`

FA issue @ryanbr
