### ISSUE TITLE
kinogo.zone: breakage

### ISSUE THREAD

**Issue by Bokapoka90165** [uBlockOrigin/uAssets#15208]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kinogo.zone/drama/439-besstyzhie-shameless-hdtv-v1.html`

### Category

breakage

### Describe the issue

when i watch the series, an error pops up that says that you need to disable adblock(the error pops up not immediately,but regulary)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://user-images.githubusercontent.com/108483073/194760170-bff0ee45-53fd-4f5e-9b03-544361fb5b7e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 102951
  cosmetic: 61115
  scriptlet: 19270
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 40704-10, 14h.42m
    easylist: 62307-69, 6d.18h.30m
    easyprivacy: 30671-1288, 6d.18h.28m
    plowe-0: 3665-865, 7d.22h.40m
    ublock-abuse: 76-1, 12d.17h.20m
    ublock-badware: 4359-105, 14h.45m
    ublock-filters: 33107-152, 14h.44m
    ublock-privacy: 249-1, 12d.16h.2m
    ublock-quick-fixes: 328-12, 18h.51m
    ublock-unbreak: 1865-43, 3d.21h.30m
    urlhaus-1: 8724-0, 18h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4777 ms (selfie)
  maxAssetCacheWait: 1821 ms
popupPanel: 
  blocked: 196
  blockedDetails: 
    4251.tech: 14
    aj1907.online: 3
    googletagmanager.com: 1
    myangular.life: 176
    weblion777.github.io: 1
    yadro.ru: 1
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
I can't reproduce either. Perhaps the problem is related to the use vpn or too strict browser privacy settings.
