### ISSUE TITLE
vezifilme.online

### ISSUE THREAD

**Issue by mortyam** [uBlockOrigin/uAssets#15203]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vezifilme.online/shut-in-online-subtitrat/`

### Describe the issue

When I play the video and I try to change the timelapse, a pop-up appear on the video.

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 105

### Settings

Default settings

**Comment by mapx-** [comment]
You already asked time ago, the answer is the same:
https://github.com/uBlockOrigin/uAssets/issues/14016#issuecomment-1184319693

The real site seems to be:
`vezionline.net`

**Comment by mortyam** [comment]
@mapx- Thank you, sorry for double post.
