### ISSUE TITLE
citi.com high resource usage

### ISSUE THREAD

**Issue by scarf** [uBlockOrigin/uAssets#15202]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.citi.com`

### Describe the issue

EasyPrivacy filters `/sendLogs?cid` and `||contents2.00110.citi.com^` are blocking connections to `https://contents1.00110.citi.com/` and `https://contents2.00110.citi.com/`, which in turn are constantly retrying to connect, causing a constant barrage of error messages to be logged to the browser's console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://contents1.00110.citi.com/api/v1/sendLogs?cid=cedric&cdsnum=X-sjnF-Y-Z-W-B-C&csid=D&ds=js&sdkVer=A. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://contents2.00110.citi.com/client/v3.1/web/wup?cid=cedric. (Reason: CORS request did not succeed). Status code: (null).
```

Thus in turn causing a huge usage of CPU (~20% here).

The site otherwise works fine and don't mind having these filters.  Is there perhaps a way to stop the constant retrying of connection to `contents1.00110.citi.com` and `contents2.00110.citi.com` so the blocking and error messages will just stop?  Thanks

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 102
filterset (summary): 
  network: 85852
  cosmetic: 39013
  scriptlet: 17920
  html: 772
listset (total-discarded, last updated): 
  default: 
    user-filters: 48-0, never
    ublock-filters: 33838-34, 1d.2h.25m
    ublock-badware: 4345-0, 1d.2h.24m
    ublock-privacy: 273-0, 11d.2h.7m
    ublock-abuse: 76-0, 11d.2h.6m
    ublock-unbreak: 1879-0, 1d.18h.26m
    easylist: 62491-620, 18h.22m
    easyprivacy: 30695-1706, 18h.21m
    plowe-0: 3672-3, 4d.6h.30m
    urlhaus-1: 8759-0, 22h.23m
filterset (user): [array of 48 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2786 ms (selfie)
  maxAssetCacheWait: 572 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe these?

```adb
@@||contents2.00110.citi.com/client/v3.1/web/wup$xhr,1p
citi.com##+js(no-xhr-if, cls_report?)
```

**Comment by scarf** [comment]
> Maybe these?
> 
> ```
> @@||contents2.00110.citi.com/client/v3.1/web/wup$xhr,1p
> citi.com##+js(no-xhr-if, cls_report?)
> ```

Yeah that helps, although it allows the connection to contents2.00110.citi.com so not sure if that is a good thing or not.   The connection for https://contents1.00110.citi.com/api/v1/sendLogs?cid is still blocked and it doesn't retry now though.

**Comment by mapx-** [comment]
Do you get breakages with these filters ?

```
citi.com##+js(aost, cdApi, core, 2)
citi.com##+js(no-xhr-if, cls_report?)
```

**Comment by scarf** [comment]
> Do you get breakages using these filters ?
> 
> ```
> citi.com##+js(aost, cdApi, core, 2)
> citi.com##+js(no-xhr-if, cls_report?)
> ```

Yeah these seem fine also, don't even see connections to contents1.00110.citi.com and contents2.00110.citi.com even occurring now.  However, still high CPU use (~30%) when the tab is focused and ~15% when unfocused (normally CPU around 5-8%), so not sure what's still causing that now...

**Comment by stephenhawk8054** [comment]
> Yeah these seem fine also, don't even see connections to contents1.00110.citi.com and contents2.00110.citi.com even occurring now. However, still high CPU use (~30%) when the tab is focused and ~15% when unfocused (normally CPU around 5-8%), so not sure what's still causing that now...

Actually I don't get high CPU even when I don't add new filters and the blocking number continues rising, so I don't think the blocking causes high CPU. You might need to investigate yourself what causes high CPU on your machine.

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/66517106/194764432-d483187f-2abf-4f88-be57-54f756622347.png)

</details>

**Comment by scarf** [comment]
Well it is about 10-year old laptop with Intel Core i5-3210M so very well may have high CPU usage compared to other computers.  I tried running the Firefox Profiler (Developer tools > Performance) got these results: https://share.firefox.dev/3rMMDGA

Looks like javascript is causing it?

**Comment by mapx-** [comment]
@stephenhawk8054 I guess your filters could be added, my `aost` is dangerous for a bank

**Comment by scarf** [comment]
What's so bad about it?  Site worked fine to me and could login and see my accounts, etc.  What's it even doing?  I found https://github.com/gorhill/uBlock/wiki/Resources-Library#aostjs- but what is `cdApi` and `core`?

**Comment by scarf** [comment]
What's so bad about it?  Site worked fine to me and could login and see my accounts, etc.  What's it even doing?  I found https://github.com/gorhill/uBlock/wiki/Resources-Library#aostjs- but what is `cdApi` and `core`?

Actually, if I turn off the logging by leaving the last field empty and using `citi.com##+js(aost, cdApi, core,)` my CPU usage goes back down to 5-8%, so that was it!  Was still related to messages/logging being sent to the Console.

**Comment by mapx-** [comment]
> what is cdApi and core?

inside:
`https://www.citi.com/cbol-pre-login-static-assets/cbol-core-assets/cedric/cedric.js`

`cdApi.configurationKeys.wupServerURL]="https://contents2.00110.citi.com/client/v3/web/wup?cid=cedric",n[cdApi.configurationKeys.logServerURL]="https://contents1.00110.citi.com/api/v1/sendLogs"`

maybe could be blocked directly (if no breakage during all normal operations on a bank account)
`||citi.com/cbol-pre-login-static-assets/cbol-core-assets/cedric/cedric.js$script,1p`

**Comment by scarf** [comment]
> maybe this script could be blocked directly (if no breakage during all normal operations on a bank account) `||citi.com/cbol-pre-login-static-assets/cbol-core-assets/cedric/cedric.js$script,1p`

Adding just this rule doesn't seem to break anything, the homepage loaded up ok.  but CPU went back up to 17-20% and I couldn't exactly tell why, didn't see any repeated messages in the Console or uBO Logger.  According to the Profiler it's caused by main.*.js?  https://share.firefox.dev/3ExIH4u

I still like these two rules the most as CPU is only 5-8% when idle, where I'm used to seeing it, and site works fine:
```
citi.com##+js(aost, cdApi, core, )
citi.com##+js(no-xhr-if, cls_report?)
```

**Comment by stephenhawk8054** [comment]
> What's so bad about it? Site worked fine to me and could login and see my accounts, etc. What's it even doing? I found https://github.com/gorhill/uBlock/wiki/Resources-Library#aostjs- but what is `cdApi` and `core`?

Scriptlets have more potentials to break core things on websites, and some (`set`, `aost`...) have more than others. We are more careful with bank sites because we cannot know when or where scriptlets can break underlying security codes (encryption...) even when the sites happen to ignore the errors and continue working normally.
