### ISSUE TITLE
hokej.net: breakage

### ISSUE THREAD

**Issue by krainaGSM** [uBlockOrigin/uAssets#15212]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hokej.net/artykul/lider-lepszy-od-mistrza-dublet-dziubinskiego`

### Category

breakage

### Describe the issue

Gdy włączony jest ublock origin, są niewidoczne komentarze pod artykułami.
When ublock origin is on, comments under articles are not visible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bez tytułu](https://user-images.githubusercontent.com/114491876/194771513-6735c241-d0e3-4ab6-ad64-6800cb790540.jpg)
![Bez tytułu2](https://user-images.githubusercontent.com/114491876/194771517-0d2cfe7a-97be-4e87-8ac8-8c0d4172e50d.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 122826
  cosmetic: 94934
  scriptlet: 31033
  html: 1004
listset (total-discarded, last updated): 
  added: 
    https://www.certyficate.it/adblock/adblock_cookies.txt: 9584-16, 1d.4h.40m
    adguard-generic: 65994-4790, 1d.4h.43m
    adguard-mobile: 8135-148, 1d.4h.44m
    adguard-spyware: 34347-15911, 1d.4h.41m
    adguard-spyware-url: 782-3, 1d.4h.42m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33823-101, 19m
    ublock-badware: 4345-0, 3d.20h.44m
    ublock-privacy: 273-0, 3d.34m
    ublock-abuse: 76-0, 3d.4h.37m
    ublock-unbreak: 1881-2, 20m
    ublock-quick-fixes: 341-0, 17m
    easylist: 62323-1357, 6d.4h.28m
    easyprivacy: 30681-1713, 6d.24m
    urlhaus-1: 8696-0, 16m
    plowe-0: 3665-3, 7d.18h.34m
    POL-0: 7864-26, 18m
    POL-2: 1279-12, 20h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3726 ms (selfie)
  maxAssetCacheWait: 551 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    ads4g.pl: 2
    contentstream.pl: 2
    doubleclick.net: 1
    google-analytics.com: 2
    googletagmanager.com: 2
    protagcdn.com: 2
    quantserve.com: 1
```
</details>

**Comment by krystian3w** [comment]
Fixed in regional possible add schedule to remove form unreak.txt at Wednesday.
