### ISSUE TITLE
kanalsportowy.pl: detection

### ISSUE THREAD

**Issue by szyha** [uBlockOrigin/uAssets#15210]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kanalsportowy.pl/programy,18/wieczorowy-klub-aa-odcinki,42738/sezon-1,S01,42739/odcinek-1,E01,42740`

### Category

detection

### Describe the issue

When the episode is turned on, it displays a message to disable Adblock.

Filter that fixes the bug:
``@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=kanalsportowy.pl``

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without filter:
![firefox_499UgV6mhS](https://user-images.githubusercontent.com/12976368/194764591-4236a99e-1057-42ff-a2f7-411cf2c734d6.png)
With filter:

https://user-images.githubusercontent.com/12976368/194764609-2cf26d37-caf1-4ae9-9bb2-499913b1f0c4.mp4

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 308694
  cosmetic: 207802
  scriptlet: 36778
  html: 1074
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 363-0, now
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1973-2, now
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 176894-174, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 21930-377, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 886-0, now
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 13067-1, now
    adguard-generic: 65986-5159, now
    adguard-spyware-url: 782-122, now
    fanboy-annoyance: 80787-570, now
    ublock-annoyances: 4871-43, now
    RUS-0: 40723-191, now
  default: 
    user-filters: 7-0, never
    ublock-filters: 33830-89, now
    ublock-badware: 4363-0, now
    ublock-privacy: 279-2, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1882-2, now
    ublock-quick-fixes: 350-0, now
    easylist: 62437-642, now
    easyprivacy: 30703-1708, now
    urlhaus-1: 8696-0, now
    plowe-0: 3671-3, now
    POL-0: 7864-26, now
    POL-2: 1279-12, now
filterset (user): [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5573 ms (selfie)
  maxAssetCacheWait: 2669 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adform.net: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    tvp.pl: 2
```
</details>

**Comment by krystian3w** [comment]
How works with ima3 resource defense?

https://github.com/uBlockOrigin/uAssets/commit/eb170401389ccf355d5ca07f592c659900fa93f8

To test may needed use custom path in advance settings or uBo Dev.

**Comment by szyha** [comment]
> How works with ima3 resource defense?
> 
> [eb17040](https://github.com/uBlockOrigin/uAssets/commit/eb170401389ccf355d5ca07f592c659900fa93f8)
> 
> To test may needed use custom path in advance settings or uBo Dev.

Yes, it works on beta version 1.44.5b13 with as well as without ``uBlock filters`` to test if my filter is needed.

With ``uBlock filters``
![firefox_sZdLar34Ir](https://user-images.githubusercontent.com/12976368/194873336-5ac0446d-34ee-4f4d-81ad-92400411a093.png)

Without ``uBlock filters``

![firefox_luERM0fstN](https://user-images.githubusercontent.com/12976368/194873451-99cc4bb5-b0e2-4225-ac06-be85a9f9d1f1.png)

**Comment by krystian3w** [comment]
Generic no longer works: https://github.com/uBlockOrigin/uAssets/commit/1a3871bc904972e6c089668f80f8eef98b3ff2e6
