### ISSUE TITLE
itsfoss.com: ads

### ISSUE THREAD

**Issue by amogusussy** [uBlockOrigin/uAssets#15219]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://itsfoss.com/open-source-alternatives-android/`

### Category

ads

### Describe the issue

There's an ad showing on this site, saying to replace gmail with protonmail.

### Screenshot(s)

<details>
<summary>Screenshot( of the ad.</summary>

![image](https://user-images.githubusercontent.com/83502633/194922087-a9273f90-a83f-4c89-b83b-7b781ea3288b.png)

Also, here's the raw HTML if that helps with blocking the ad:

```
https://pastebin.com/XXZbfw5G
```
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 165239
  cosmetic: 90628
  scriptlet: 20809
  html: 782
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59631-614, 3d.20h.51m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33825-45, 3d.20h.50m
    ublock-badware: 4345-0, 3d.20h.49m
    ublock-privacy: 273-0, 7d.22h.14m
    ublock-abuse: 76-0, 7d.22h.14m
    ublock-unbreak: 1879-0, 3d.20h.48m
    ublock-quick-fixes: 345-1, 1h.57m
    easylist: 62486-651, 2h.1m
    adguard-spyware-url: 781-4, 3d.20h.52m
    easyprivacy: 30703-1706, 2h
    urlhaus-1: 8557-0, 1h.56m
    curben-phishing: 72222-4, 1h.58m
    plowe-0: 3669-3, 7d.22h.14m
    LegitimateURLShortener: 1973-121, 1h.59m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9883 ms (selfie)
  maxAssetCacheWait: 1384 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    apester.com: 3
    chmod777.ltd: 2
    cloudflareinsights.com: 2
    consensu.org: 1
    d3lcz8vpax4lo2.cloudfront.net: 1
    geolocation-db.com: 1
    getlasso.co: 1
    google-analytics.com: 1
    google.com: 7
    googletagmanager.com: 1
    instiengage.com: 1
    omappapi.com: 3
    pub.network: 4
    searchiq.co: 1
    wp.com: 2
    youtube-nocookie.com: 6
```
</details>

**Comment by mapx-** [comment]
add

`||itsfoss.com/wp-content/uploads/2015/07/Replace-Gmail*.png$image`

to be reported at easylist repository
@ryanbr
