### ISSUE TITLE
dev-panel.falixnodes.net: detection

### ISSUE THREAD

**Issue by Skridiotic** [uBlockOrigin/uAssets#15218]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dev-panel.falixnodes.net/`

### Category

detection

### Describe the issue

My friend gave me shared access to his (free plan) Falixnodes server, but trying to acces the server panel with uBlockOrigin on will then clear the dashboard and give a prompt saying "Something is blocking the page! Please disable adblock or equivalent extension or program."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2352" alt="Screenshot 2022-10-10 at 5 28 09 p m" src="https://user-images.githubusercontent.com/98226500/194912755-c6ce0dd9-6e04-4517-887b-c65ae8ce862b.png">
(Shows uBlock's menu open with the filter on, and the Falixnodes panel open with the message.)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85668
  cosmetic: 39075
  scriptlet: 18074
  html: 788
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33796-45, 1h.23m
    ublock-badware: 4363-0, 1h.22m
    ublock-privacy: 273-0, 5d.22h.59m
    ublock-abuse: 76-0, 5d.22h.58m
    ublock-unbreak: 1879-1, 2d.21h.57m
    easylist: 62322-595, 6d.22h.32m
    easyprivacy: 30685-1706, 6d.22h.30m
    urlhaus-1: 8696-0, 21h.28m
    plowe-0: 3672-3, 5d.22h.56m
    ublock-quick-fixes: 350-0, 21h.29m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 89 ms (selfie)
  maxAssetCacheWait: 117 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    snigelweb.com: 1
```
</details>

**Comment by Skridiotic** [comment]
(Sorry my github client is acting up)

**Comment by JobcenterTycoon** [comment]
Its fixed now. Force update the filter lists to get the fix directly
