### ISSUE TITLE
setopati.com: ads

### ISSUE THREAD

**Issue by hurrahay007** [uBlockOrigin/uAssets#15215]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.setopati.com/politics/284198`

### Category

ads

### Describe the issue

Ads are showing in this nepali online news paper website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 101
filterset (summary): 
  network: 81891
  cosmetic: 27002
  scriptlet: 17696
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8138-325, never
    easylist: 69310-24572, never
    easyprivacy: 27312-103, never
    plowe-0: 3634-779, never
    ublock-abuse: 76-0, never
    ublock-badware: 4232-0, never
    ublock-filters: 32615-397, never
    ublock-privacy: 231-2, never
    ublock-quick-fixes: 389-0, never
    ublock-unbreak: 1863-31, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5285 ms
  maxAssetCacheWait: 60 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    facebook.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    sharethis.com: 2
```
</details>

**Comment by mapx-** [comment]
> Chromium Mobile

not supported. Test using firefox mobile.

**Comment by ghajini** [comment]
@hurrahay007 
subscribe to `IND, LKA, NPL: IndianList` under ubo settings=> filter lists=> regions,languages 
this list is a regional list for ads
