### ISSUE TITLE
wco.tv: breakage

### ISSUE THREAD

**Issue by Heisenberg3666** [uBlockOrigin/uAssets#15211]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wco.tv/solar-opposites-season-3-special`

### Category

breakage

### Describe the issue

When loading a page to view videos on this site, it briefly works (as in it is formatted how it is supposed to be) but then the layout changes. Videos can no longer be played and the site looks like it has missing CSS.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/55025217/194766402-084d7d9f-c76e-4a12-8be9-df8be4f25003.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85842
  cosmetic: 39063
  scriptlet: 18058
  html: 786
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33840-141, 15h.9m
    ublock-badware: 4363-0, 33m
    ublock-privacy: 273-0, 3d.18h.16m
    ublock-abuse: 76-0, 3d.18h.15m
    ublock-unbreak: 1881-0, 32m
    ublock-quick-fixes: 341-1, 5h.20m
    easylist: 62463-525, 2d.19h.3m
    easyprivacy: 30690-1706, 2d.19h.2m
    urlhaus-1: 8683-0, 5h.19m
    plowe-0: 3672-3, 3d.18h.14m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 145 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    bloxplay.com: 1
    cpmstar.com: 1
    googletagmanager.com: 1
    piguiqproxy.com: 1
    vdo.ai: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||piguiqproxy.com/api$xhr,domain=wco.tv`
