### ISSUE TITLE
kroger.com: breakage

### ISSUE THREAD

**Issue by bchandler02** [uBlockOrigin/uAssets#15216]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kroger.com/signin?redirectUrl=/mypurchases/?cid=ema.tra.Ocado_D_Confirm&xg=165395640`

### Category

breakage

### Describe the issue

Cannot login to Kroger when ublock is enabled. Gives error "We're having trouble with sign in right now. Please disable any pop up or ad blockers and try again."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 85599
  cosmetic: 39078
  scriptlet: 18076
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62327-53, 6d.1h.21m
    easyprivacy: 30687-1170, 6d.1h.19m
    plowe-0: 3672-863, 5d.2h.31m
    ublock-abuse: 76-0, 5d.2h.33m
    ublock-badware: 4359-105, 2h.59m
    ublock-filters: 33084-117, 2h.58m
    ublock-privacy: 249-1, 5d.2h.32m
    ublock-quick-fixes: 328-12, 2h.55m
    ublock-unbreak: 1871-43, 2h.57m
    urlhaus-1: 8621-0, 2h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 56 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    kroger.com: 2
    adsrvr.org: 1
    bing.com: 1
    demdex.net: 3
    doubleclick.net: 1
    facebook.com: 1
    go-mpulse.net: 2
    googletagmanager.com: 1
    nextdoor.com: 1
    pinimg.com: 1
    snapchat.com: 1
    t.co: 1
    twitter.com: 1
```
</details>

**Comment by llacb47** [comment]
Test `@@||kroger.com/akam/$script,1p`

**Comment by mapx-** [comment]
I get the error even disabling uBO, maybe needing an us ip

**Comment by mapx-** [comment]
tested using a us ip, all fine on my end

**Comment by whyyn0tt** [comment]
This issue has been ongoing but only appears to happen when there's a redirect portion of the URL; https://www.kroger.com/signin?redirectUrl=/mypurchases results in this error:
![image](https://user-images.githubusercontent.com/3478819/201174195-caa2dc29-1d18-440c-b223-36c836a082b6.png)
However, https://www.kroger.com/signin works without issue.
