### ISSUE TITLE
glitched.online: ads

### ISSUE THREAD

**Issue by Symphonic3648** [uBlockOrigin/uAssets#15213]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.glitched.online/`

### Category

ads

### Describe the issue

Shows an NBA ad at the top right of the page. If you go into an article, another pops up too.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/115425978/194775793-78586c3e-cecc-414c-9ff7-d50b74557c9b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85942
  cosmetic: 38956
  scriptlet: 18076
  html: 789
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    ublock-filters: 33833-46, 1m
    ublock-badware: 4368-0, 1m
    ublock-privacy: 280-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1884-1, 1m
    ublock-quick-fixes: 350-0, 1m
    easylist: 62438-623, 1m
    easyprivacy: 30703-1705, 1m
    urlhaus-1: 8696-0, 1m
    plowe-0: 3671-3, 1m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 26 redacted]
hostRuleset: 
  added: [array of 117 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5686 ms (selfie)
  maxAssetCacheWait: 4355 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    glitched.online: 1
    cloudflareinsights.com: 2
    doubleclick.net: 2
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    youtube.com: 3
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`glitched.online##[href^="https://bit.ly/"]`
