### ISSUE TITLE
uBO detected by lookmovie2

### ISSUE THREAD

**Issue by blephmstr** [uBlockOrigin/uAssets#15214]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://lookmovie2.to/`

`https://aphalphawky.monster/movies/play/22179486-cursed-friends-2022?mid=17&sid=a6v8hlanu2qnoraisapq9cc8ca&sec=8707dedfb42dceb2ebf430dfabd3f4a2558c9e42&t=1665346113`

### Describe the issue

The main website is lookmovie2.to but it redirects to a player on a different address (see above), and I can't play the video because it detects uBO (VPN does not help). I am using the latest chrome on the latest MacOS.

### Screenshot(s)

https://imgur.com/O7KUSmz

### uBlock Origin version

1.44.4

### Browser name and version

Chrome 105.0.5195.125

### Settings

- Added ISR: EasyList Hebrew from Regions, Languages list

**Comment by dportvine** [comment]
Site issue
<details>
<summary>Screen</summary>

![2022-10-10_090924](https://user-images.githubusercontent.com/111344219/194808060-cd31ee1a-b3c5-41ea-847a-7222cdea29ef.png)
</details>
