### ISSUE TITLE
i-polls.com: detection

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#15224]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://i-polls.com/car-accident-lawyer-moreno-valley/`

### Category

detection

### Describe the issue

Detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 107
filterset (summary): 
  network: 87306
  cosmetic: 27668
  scriptlet: 18131
  html: 788
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 33910-305, 16h.18m
    ublock-badware: 4367-0, 16h.18m
    ublock-privacy: 281-1, 16h.18m
    ublock-abuse: 76-0, 16h.18m
    ublock-unbreak: 1892-1, 16h.18m
    ublock-quick-fixes: 346-0, 16h.18m
    adguard-mobile: 8141-168, 16h.18m
    easylist: 62495-18205, 16h.18m
    easyprivacy: 30703-1715, 16h.18m
    urlhaus-1: 8557-0, 16h.18m
    plowe-0: 3671-3, 16h.18m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 688 ms (selfie)
  maxAssetCacheWait: 316 ms
  unsuspendAfter: 283 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 2
    ezoic.net: 6
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Is it a redirection from other sites?

**Comment by krystian3w** [comment]
#15232
