### ISSUE TITLE
s2c.mercell.com: breakage

### ISSUE THREAD

**Issue by lars1987** [uBlockOrigin/uAssets#15228]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s2c.mercell.com/`

### Category

breakage

### Describe the issue

Mercell Source-to-Contract uses 3rd party script Whatfix to allow for access to customer service/self-help. UBlock blocks the 3rd party script and customers cannot get access to support as intended.

Disabling uBlock makes the self-help work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1279" alt="Screenshot_108" src="https://user-images.githubusercontent.com/110042285/195107867-a288807b-430d-4d45-ba5b-dbeeed183387.png">
<img width="1279" alt="Screenshot_109" src="https://user-images.githubusercontent.com/110042285/195107872-963377b8-cea7-43c1-bffd-c124dfc079a5.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86745
  cosmetic: 40880
  scriptlet: 18109
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    NOR-0: 2809-7, 1d.56m
    easylist: 62486-55, 1d.56m
    easyprivacy: 30703-1171, 1d.56m
    plowe-0: 3671-863, 1d.56m
    ublock-abuse: 76-0, 1d.56m
    ublock-badware: 4364-106, 1d.56m
    ublock-filters: 33059-104, 1d.56m
    ublock-privacy: 256-1, 1d.56m
    ublock-quick-fixes: 335-11, 1d.56m
    ublock-unbreak: 1871-43, 1d.56m
    urlhaus-1: 8621-0, 1d.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1279 ms
  maxAssetCacheWait: 204 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
Update the `uBO-unbreak` list, support should work as intended after that.
