### ISSUE TITLE
old.reddit.com: ads

### ISSUE THREAD

**Issue by Squantchies** [uBlockOrigin/uAssets#15229]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://old.reddit.com/r/DotA2/`

### Category

ads

### Describe the issue

Ad links are displaying on all subreddits on the old.reddit.com domain.  Image shows advertisement near the bottom.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/31636448/195127898-fc5fa47e-f953-40ee-b7b9-1bef6b30f204.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b9
Chromium: 105
filterset (summary): 
  network: 86455
  cosmetic: 40152
  scriptlet: 21202
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    fanboy-thirdparty_social: 68-0, 6d.11m
    ublock-annoyances: 4843-6, 10m
  default: 
    user-filters: 0-0, never
    easylist: 62307-53, 6d.6m
    easyprivacy: 30689-1170, 6d.4m
    plowe-0: 3672-863, 6d.12m
    ublock-abuse: 76-0, 6d.15m
    ublock-badware: 4364-105, 9m
    ublock-filters: 33044-100, 7m
    ublock-privacy: 249-1, 6d.14m
    ublock-unbreak: 1874-42, 8m
    urlhaus-1: 9118-0, 6m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 629 ms (selfie)
  maxAssetCacheWait: 425 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    reddit.com: 6
    redditmedia.com: 1
```
</details>

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/xx5pew/cosmetic_filtering_could_be_broken_in_1445b9b10/
