### ISSUE TITLE
github.dev: breakage

### ISSUE THREAD

**Issue by hugocaillard** [uBlockOrigin/uAssets#15223]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://github.dev/`

### Category

breakage

### Describe the issue

When trying to install a specific extension, the following request get blocked by uBO:

`https://hirosystems.vscode-unpkg.net/HiroSystems/clarity-lsp/1.0.3/extension/package.json`

#### Reproduce

- Go to [vscode.dev](https://vscode.dev) or [github.dev](https://vscode.dev)
- Go to the extension panel (left menu)
- Search "Clarity" (HiroSystems.clarity-lsp" should be the first result
- Click "install"
- The request gets blocked by uBO

See in screenshots as well

Other extensions work, I can't figure why this one triggers something.

Thanks

### Screenshot(s)

<details>
<summary>Screenshot</summary>

<img width="1266" alt="Screenshot 2022-10-11 at 12 49 54" src="https://user-images.githubusercontent.com/911307/195071130-089102bb-4a3e-4914-9924-c9fcb2c570cd.png">

<img width="1745" alt="Screenshot 2022-10-11 at 13 08 47" src="https://user-images.githubusercontent.com/911307/195075858-e9802d09-2d27-442d-933c-aead9b42f3cc.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85849
  cosmetic: 38954
  scriptlet: 18058
  html: 787
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33838-46, 2d.20h.1m
    ublock-badware: 4363-0, 2d.20h
    ublock-privacy: 280-0, 22h.58m
    ublock-abuse: 76-0, 22h.57m
    ublock-unbreak: 1881-1, 2d.19h.59m
    ublock-quick-fixes: 341-0, 22h.52m
    easylist: 62438-643, 22h.53m
    easyprivacy: 30695-1705, 22h.54m
    urlhaus-1: 8621-0, 22h.51m
    plowe-0: 3671-3, 22h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 799 ms (selfie)
  maxAssetCacheWait: 539 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    vscode-unpkg.net: 1
```
</details>

**Comment by mapx-** [comment]
> When trying to install a specific extension, the following request get blocked by uBO:


provide all the steps, links etc to reproduce the issue

**Comment by okiehsch** [comment]
Does adding
`@@||hirosystems.vscode-unpkg.net/*/clarity-lsp/*$xhr,domain=github.dev|vscode.dev`
fix the issue on your end?
@ryanbr

**Comment by hugocaillard** [comment]
@okiehsch Yes it does

**Comment by okiehsch** [comment]
Thx, it will be fixed in EasyPrivacy-
We will close this issue after the exception has been added.

**Comment by hugocaillard** [comment]
Thanks a lot 👍
That was fast 😃

**Comment by Yuki2718** [comment]
@ryanbr  Isn't the target of `/clarity-*.js` js file? If so just adding `^` i.e. `/clarity-*.js^$domain=~` should fix the issue.

**Comment by hugocaillard** [comment]
Out of curiosity, is there any reason why this URL is blocked in the first place?

Like, is there a keyword (`hirosystem` or `clarity`) that triggers the blockage?
There are more and more extensions for vscode.dev / github.dev so you probably don't want to block any of them in the future.

Some more thoughts, vscode.dev and github.dev are basically 2 websites that host the web version of the VS Code editor. In the future, we can be sure that more domain will host it, and will access the marketplace. So we probably don't want to whitelist theses specific 2 domains 🤔

**Comment by okiehsch** [comment]
EasyPrivacy includes a filter that blocks all requests that include the string `/clarity-*.js ` regardless of the origin.
The `*`  stands for any number of characters.

**Comment by Yuki2718** [comment]
@hugocaillard If I understand correctly, these should work too:
```
@@||hirosystems.vscode-unpkg.net/*/clarity-lsp/$domain=github.dev|vscode.dev,badfilter
/clarity-*.js$domain=~clarity-labs.kaminario.com|~clarity.imply.io|~make.services,badfilter
/clarity-*.js^$domain=~clarity-labs.kaminario.com|~clarity.imply.io|~make.services
```

The first one disables current fix for the issue. The second disables the breaking rule, and the third is IMO more properly targetted rule not to wrongly block requests here.

**Comment by hugocaillard** [comment]
Alright I get it.
So @Yuki2718 makes sens as well. It would be more future proof to only target "JS" file and not "JSON".

To give more context, `clarity` is a programming language ([https://clarity-lang.org/](https://clarity-lang.org/)).
So having a file `clarity-*.json` is very likely.
`clarity-*.js` is a bit less likely in this context

**Comment by hugocaillard** [comment]
@Yuki2718 Yes it might make sense given your explanation (although I'm not qualified to understand the whole filter).

In the end, is there any reason not to whitelist all `vscode-unpkg.net` requests?

**Comment by hugocaillard** [comment]
Yes that sounds good.

If that's ok, I'd be tempted to replace 
`@@||hirosystems.vscode-unpkg.net/*/clarity-lsp/$`

with something like:
`@@||*.vscode-unpkg.net/*/clarity-lsp/$`

"hirosystems.vscode-unpkg" targets one specific organization building tools for the Clarity language but other companies can do so 👌 

Thanks a lot for your prompt and thorough help on this issue

**Comment by hugocaillard** [comment]
Should this issue be re-open until the better fix is done?

**Comment by Yuki2718** [comment]
No, as it's anyway fixed. I pinged EL maintainer and it's their decesion.
