### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by prototype464** [uBlockOrigin/uAssets#15225]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/`

### Category

breakage

### Describe the issue

Using Opera GX, tried the usual troubleshooting steps (purged all caches and updated), Imgur isn't loading content. Was originally trying to view this - https://imgur.com/6Xg1Xrq

I've been having issues with Imgur in general as well as of a few days ago, seems like uBlock Origin is being detected. I love the "Prerequisites" section by the way, haha

### Screenshot(s)

![a](https://user-images.githubusercontent.com/7600449/195085764-11f31994-fc80-486f-8e56-0a6062883469.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 198791
  cosmetic: 123276
  scriptlet: 33433
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59671-87, now
    adguard-generic: 64855-468, now
    adguard-spyware: 35446-2789, now
    adguard-spyware-url: 791-1, now
    curben-phishing: 72122-1, now
  default: 
    user-filters: 0-0, never
    easylist: 62502-759, now
    easyprivacy: 30709-13303, now
    plowe-0: 3671-941, now
    ublock-abuse: 76-0, now
    ublock-badware: 4364-244, now
    ublock-filters: 33060-3812, now
    ublock-privacy: 256-43, now
    ublock-quick-fixes: 336-23, now
    ublock-unbreak: 1874-97, now
    urlhaus-1: 8539-4, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 852 ms (selfie)
  maxAssetCacheWait: 781 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    consensu.org: 1
    google-analytics.com: 1
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/195092162-65ea22b9-1524-47be-9344-348d21fbbcd9.png)

Works fine on my end.

**Comment by prototype464** [comment]
Imgur is refusing to display images.
![image](https://user-images.githubusercontent.com/7600449/196170392-cfe30c59-9117-4c24-807b-4c0189dd9c93.png)

**Comment by mapx-** [comment]
Did you disable opera adblocker / vpn ?

**Comment by gwarser** [comment]
What are your other addons?
