### ISSUE TITLE
foxnews.com: breakage

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#15230]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.foxnews.com/`

### Category

breakage

### Describe the issue

There is a top left had video box that once loaded play the current program on Foxnews however it seems to stop playing after a short time period

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![foxnewsvideo](https://user-images.githubusercontent.com/24624945/195205619-37fdb26c-7539-4378-9c05-5a2fa4c0f648.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b14
Firefox: 106
filterset (summary): 
  network: 161715
  cosmetic: 84615
  scriptlet: 21348
  html: 815
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 444-0, 4m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 468-1, 4m
    https://www.i-dont-care-about-cookies.eu/abp/: 25410-4, 4m
    adguard-spyware-url: 791-3, 5m
    block-lan: 44-0, 5m
    curben-phishing: 71481-6, 5m
    curben-pup: 194-0, 5m
    fanboy-social: 23386-9, 4m
    ublock-annoyances: 4864-9, 4m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33777-49, 5m
    ublock-badware: 4368-0, 5m
    ublock-privacy: 281-0, 5m
    ublock-abuse: 76-0, 5m
    ublock-unbreak: 1888-4, 5m
    ublock-quick-fixes: 335-0, 5m
    easylist: 62562-345, 5m
    easyprivacy: 30709-1194, 5m
    urlhaus-1: 9118-0, 5m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 222 ms (selfie)
  maxAssetCacheWait: 609 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    foxnews.com: 3
    akamaihd.net: 1
    akamaized.net: 2
    amazon-adsystem.com: 3
    bing.com: 1
    chartbeat.com: 2
    criteo.net: 1
    demdex.net: 4
    doubleclick.net: 2
    edgekey.net: 1
    google-analytics.com: 1
    google.com: 5
    googletagmanager.com: 1
    h-cdn.com: 2
    imrworldwide.com: 1
    lytics.io: 1
    newrelic.com: 1
    opecloud.com: 1
    outbrain.com: 3
    pix.pub: 1
    rlcdn.com: 2
    segment.com: 2
    taboola.com: 1
    taplytics.com: 4
    yahoo.com: 2
    yimg.com: 1
```
</details>

**Comment by mapx-** [comment]
Test using only the default setup

**Comment by troysjanda** [comment]
I have tested it on a new profile without any add-ons, new profile with just ubo, tested FF 106/nightly and it seems to only happen on 105.0.3. it's not a big deal closing feel free to mark invalid
