### ISSUE TITLE
mediaexpert.pl: nuisance

### ISSUE THREAD

**Issue by szyha** [uBlockOrigin/uAssets#15233]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mediaexpert.pl/`

### Category

nuisance

### Describe the issue

After accessing the site preferably in a private window, it displays a popup only in the Firefox. With the ``Fanboy's Annoyance`` filter enabled, only a blank box is visible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ``Fanboy's Annoyance``

![firefox_2PpuWMavKj](https://user-images.githubusercontent.com/12976368/195330198-f8303c1b-a785-4060-b48a-057bbe3f1324.png)

Without ``Fanboy's Annoyance``

![firefox_GG0vGCQwmd](https://user-images.githubusercontent.com/12976368/195330039-acb4f951-34af-464f-9bd6-aa3cfa785b7c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 334622
  cosmetic: 271500
  scriptlet: 39805
  html: 1071
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 363-0, 1m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1973-2, 1m
    https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 178554-174, 1m
    https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 21912-377, now
    https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 886-0, now
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 13067-1, now
    adguard-generic: 64364-5548, 1m
    adguard-spyware: 35452-14346, 1m
    adguard-spyware-url: 791-123, 1m
    adguard-annoyance: 59684-5722, 1m
    adguard-social: 18578-104, 1m
    fanboy-annoyance: 80805-1629, 1m
    ublock-annoyances: 4870-43, 1m
    RUS-0: 40644-334, 1m
  default: 
    user-filters: 7-0, never
    ublock-filters: 33791-98, 1m
    ublock-badware: 4368-0, 1m
    ublock-privacy: 281-2, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1886-2, 1m
    ublock-quick-fixes: 349-0, 1m
    easylist: 62539-652, 1m
    easyprivacy: 30711-1710, 1m
    urlhaus-1: 9368-0, 1m
    plowe-0: 3672-3, 1m
    POL-0: 7865-26, 1m
    POL-2: 1279-12, 1m
filterset (user): [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3306 ms (selfie)
  maxAssetCacheWait: 3029 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    mediaexpert.pl: 4
    criteo.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    snrcdn.net: 4
    wp.pl: 1
```
</details>

**Comment by krystian3w** [comment]
I don't know what filter break pop-up.

But possible add:

`##.is-exit-popup`

I can add this to "Polish Annoyance Filters" - maybe today.

**Comment by mapx-** [comment]
add

```adb
mediaexpert.pl##.dynamic-modal
```

@ryanbr

**Comment by krystian3w** [comment]
Filter has been planted:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/0a0ad7d7602df3e53376cc840ff09fd6da28516a
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/575b777121ec7a8aa95777ff8dd4d54725b7a7fd
