### ISSUE TITLE
[nsfw] useast2-www.securly.com: detection

### ISSUE THREAD

**Issue by nrgsvft** [uBlockOrigin/uAssets#15239]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://useast2-www.securly.com/`

### Category

detection

### Describe the issue

 hehj2wiei23

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 86487
  cosmetic: 38970
  scriptlet: 18085
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 4-0, never
    easylist: 62502-54, 1d.51m
    easyprivacy: 30709-1170, 1d.50m
    plowe-0: 3671-862, 1d.56m
    ublock-abuse: 76-0, 1d.59m
    ublock-badware: 4359-105, 1d.55m
    ublock-filters: 33060-105, 1d.54m
    ublock-privacy: 256-1, 1d.58m
    ublock-quick-fixes: 336-12, 8m
    ublock-unbreak: 1871-43, 1d.53m
    urlhaus-1: 9206-0, 9m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3199 ms (selfie)
  maxAssetCacheWait: 1959 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 5
    googletagmanager.com: 1
```
</details>3biex3o h3dpo2121rr43td5

**Comment by okiehsch** [comment]
Maybe an account is needed.

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+securly+is%3Aclosed

- nobody was able to provide indications on how to reproduce the issue
- if you are able to provide an account / indications just respond here
