### ISSUE TITLE
next-episode.net: breakage

### ISSUE THREAD

**Issue by My-Random-Thoughts** [uBlockOrigin/uAssets#15246]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://next-episode.net`

### Describe the issue

Related: #14962
The page `https://next-episode.net/track` no longer works with regard to `[stop tracking]` and `[track]` links for each show listed.
Removing the entire quick-fixes list removes the issue.

With the list in place, the links do nothing.

### Screenshot(s)

N/A

### uBlock Origin version

uBlock Origin 1.44.4

### Browser name and version

Firefox 105.0.3

### Settings
<details>
<summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 232786
  cosmetic: 216824
  scriptlet: 38229
  html: 795
listset (total-discarded, last updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 20h.29m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 1d.30m
    https://winhelp2002.mvps.org/hosts.txt: 8730-317, 1d.31m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-10, 1d.32m
    adguard-generic: 64846-5278, 1d.21h.42m
    adguard-mobile: 8143-220, 1d.21h.46m
    adguard-spyware: 35446-14562, 1d.21h.45m
    adguard-annoyance: 59663-4710, 1d.21h.44m
    adguard-social: 18560-52, 1d.21h.41m
    fanboy-thirdparty_social: 69-0, 8d.10h.23m
    fanboy-annoyance: 80753-42932, 8d.10h.22m
    fanboy-cookiemonster: 41181-148, 8d.10h.21m
    ublock-annoyances: 4871-8, 1d.21h.43m
    dpollock-0: 11389-1747, 2d.20h.50m
    curben-phishing: 70187-8, 17h.35m
    curben-pup: 194-0, 17h.38m
  default: 
    user-filters: 364-2, never
    ublock-filters: 33797-95, 1d.21h.49m
    ublock-badware: 4368-4, 1d.21h.48m
    ublock-privacy: 280-0, 2d.20h.54m
    ublock-abuse: 76-0, 2d.20h.53m
    ublock-unbreak: 1884-0, 1d.21h.47m
    easylist: 62502-1094, 1d.15h.7m
    easyprivacy: 30709-2046, 1d.15h.6m
    urlhaus-1: 9206-0, 17h.36m
    plowe-0: 3671-1793, 2d.20h.51m
filterset (user): [array of 366 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 41 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 485 ms (selfie)
  maxAssetCacheWait: 692 ms
```

</details>

### Notes

Removing and re-adding the quick-fix list toggles the issue.

**Comment by mapx-** [comment]
Are you meaning "add / remove to watchlist" ? otherwise explain how mto get the issue

Did you test using only the default setup ?

**Comment by My-Random-Thoughts** [comment]
With the "Quick-Fixes" list enabled, go to the page `https://next-episode.net/track`.  You will need to be logged in and have shows in your list. 

If you have shows listed, there will be three links for each one: 
`[set tag]`, `[set service]`, `[stop tracking]`:
![image](https://user-images.githubusercontent.com/21334396/195573882-d5940c65-5ec1-4a52-806d-2e6a482a8fd2.png)

The first two work fine, the third `[stop tracking]` does not.  Nothing happens when it's clicked.

Disable just the "Quick-Fixes" list, reload the page and click `[stop tracking]` again.
This time it will work.  The show will be removed from that list and moved to the not tracked section:
![image](https://user-images.githubusercontent.com/21334396/195574059-f2784b5d-4800-4a5c-a142-6b668a6b1f4e.png)

**Comment by mapx-** [comment]
Test

```
next-episode.net#@#+js(aost, document.createElement, inlineScript)
next-episode.net##+js(aost, document.createElement, /(?=^(?!.*(https|stopTracking)))/, 2)
```

**Comment by My-Random-Thoughts** [comment]
That works perfectly, thank you

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d7177cf66f51b86229a3f510f2233021ec6f4096
