### ISSUE TITLE
[nsfw] masahub.net: nuisance

### ISSUE THREAD

**Issue by ragingbullsam** [uBlockOrigin/uAssets#15243]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://masahub.net/`

### Category

nuisance

### Describe the issue

Unwanted popup not seen before in the website.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/115673066/195472589-99885775-952b-415e-a713-06e260cda518.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86519
  cosmetic: 38968
  scriptlet: 18087
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62538-54, 9m
    easyprivacy: 30711-1170, 8m
    plowe-0: 3671-862, 2d.18h.54m
    ublock-abuse: 76-0, 2d.18h.57m
    ublock-badware: 4364-105, 7m
    ublock-filters: 33057-103, 6m
    ublock-privacy: 250-1, 2d.18h.56m
    ublock-quick-fixes: 340-12, 4m
    ublock-unbreak: 1867-43, 5m
    urlhaus-1: 9206-0, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4796 ms
  maxAssetCacheWait: 1905 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    8aaee039a0.com: 1
    a-ads.com: 2
    cloudflare.com: 1
    cloudimagesb.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    kiynew.com: 1
    tracot.com: 1
    wpadmngr.com: 1
```
</details>

**Comment by einstein95** [comment]
This filter works: `zatnoh.com$script,domain=masahub.net`
