### ISSUE TITLE
Cyberpower UPS selector broken

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15242]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cyberpowersystems.com/tools/ups-selector/`

### Describe the issue

The UPS selector does not show up with uBlock Origin enabled. 

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 105
filterset (summary): 
  network: 86575
  cosmetic: 38970
  scriptlet: 18083
  html: 786
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33794-45, now
    ublock-badware: 4373-0, now
    ublock-privacy: 281-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1880-1, now
    ublock-quick-fixes: 350-0, now
    easylist: 62581-600, now
    easyprivacy: 30712-1705, now
    urlhaus-1: 9206-0, now
    plowe-0: 3673-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1593 ms
  maxAssetCacheWait: 182 ms
```
</details>

**Comment by contextnerror** [comment]
I guess I was using 1.44.2? Not sure why it hadn't updated. Did test again on 1.44.4 though, issue persists.

**Comment by okiehsch** [comment]
`@@||cyberpower.advizia.com/CyberPower/adv.asp$frame,domain=cyberpowersystems.com`
@ryanbr

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/cbf1d9aeb5c4a6aac2c0f0c097a74c5fff3321d7

@contextnerror Update `EasyList`, it should work after that.
