### ISSUE TITLE
twitter.com: ads

### ISSUE THREAD

**Issue by herbrich** [uBlockOrigin/uAssets#15241]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://twitter.com/search?q=%23COVID19&src=trend_click&vertical=trends`

### Category

ads

### Describe the issue

Twitter displays SPAM and Prolltrash like CoronaVirus stuff. I try to block that with uBlock Origin but no Option was found.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88735
  cosmetic: 42710
  scriptlet: 18066
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 5957-0, 13h.36m
    easylist: 62404-58, 2d.17h.46m
    easyprivacy: 30695-1180, 2d.17h.45m
    plowe-0: 3671-863, 3d.21h.54m
    ublock-abuse: 76-0, 3d.21h.56m
    ublock-badware: 4359-105, 3d.21h.53m
    ublock-filters: 33107-160, 3d.21h.52m
    ublock-privacy: 250-1, 5d.2h.1m
    ublock-quick-fixes: 336-11, 13h.35m
    ublock-unbreak: 1868-44, 3d.21h.51m
    urlhaus-1: 9368-0, 13h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4521 ms
  maxAssetCacheWait: 255 ms
popupPanel: 
  blocked: 345
  blockedDetails: 
    twitter.com: 344
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
if you want to hide the tweets with hasttag covid19 add:

```
twitter.com##[data-testid="cellInnerDiv"]:has([href="/hashtag/COVID19?src=hashtag_click"])
twitter.com##[data-testid="cellInnerDiv"]:has([href="/hashtag/covid19?src=hashtag_click"])
```
