### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by ThePurpleCrayon** [uBlockOrigin/uAssets#15245]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Describe the issue

This issue lies with cosmetic filters.  72 hours ago all my cosmetic filters started to be ignored, even though My Filters still shows the correct entries.  After verifying the entries were still the same and not changed, I created yet another cosmetic filter for the same item only for the entry to be,ignored.  I went through basic troubleshooting including removing and updating Filter Lists, removing and readding the cosmetic filters again and even removing and reinstalling uBlock....with the same results.  I then removed uBlock and installed AdBlock Plus....and the exact same characteristics occured - all cosmetic filters were being ignored.  So now, I have removed ABP and reinstalled uBlock once again, with all Custom Filters(cosmetic) are being ignored.  The following entries are the only ones within my Custom Filters right now and are an example of all other cosmetic filters that would be added. 

```adb
! 2022-10-12 https://outlook.live.com
outlook.live.com##.AK_my > .pBKjV > .PQ3t8
outlook.live.com##.AK_my > .pBKjV 
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![outlook](https://user-images.githubusercontent.com/10244639/195512933-5c776c49-3a9e-43ab-8ef6-eb888ac34013.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86523
  cosmetic: 38967
  scriptlet: 18087
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 62527-54, 1d.10h.53m
    easyprivacy: 30709-1170, 1d.10h.53m
    plowe-0: 3671-862, 1d.10h.53m
    ublock-abuse: 76-0, 1d.10h.53m
    ublock-badware: 4364-105, 1d.10h.53m
    ublock-filters: 33057-103, 1d.10h.53m
    ublock-privacy: 256-1, 1d.10h.53m
    ublock-quick-fixes: 340-12, 8h.58m
    ublock-unbreak: 1875-43, 1d.10h.53m
    urlhaus-1: 9206-0, 8h.57m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13080 ms (selfie)
  maxAssetCacheWait: 713 ms
popupPanel: 
  blocked: 162
  blockedDetails: 
    live.com: 2
    3lift.com: 3
    adnxs.com: 3
    microsoft.com: 39
    office.net: 112
    taboola.com: 2
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
What Chromium browser are you using ?

**Comment by ThePurpleCrayon** [comment]
Ironically Chrome updated itself about 5 minutes ago
Version 106.0.5249.119 (Official Build) (64-bit)
-and that Outlook cosmetic filter is working
________________________________

**Comment by mapx-** [comment]
> that Outlook cosmetic filter is working

so .. some glitch on your side
