### ISSUE TITLE
ebay-kleinanzeigen.de: infinite and broken redirections

### ISSUE THREAD

**Issue by VetaLioSTV** [uBlockOrigin/uAssets#15257]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [x] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.ebay-kleinanzeigen.de/`

### Describe the issue

I think several months ago for some reason(bug?) started getting infinite redirects from `https://www.ebay-kleinanzeigen.de/` to `ebay.com`. I still do not understand steps of reproduce and why it happens, but usually its a random. Also it has issue that **sometime**(_sometime not_) it brakes navigation and you can't go back on  `https://www.ebay-kleinanzeigen.de/` which is super ultra annoying. 

### uBlock Origin version

1.44.4

### Browser name and version

Chrome 106.0.5249.119

### Settings

No changes, all stuff is default.

### Notes

Usually when it triggers, as first step it goes here
`https://rclick.site/3WjZcP?source=ebay-kleinanzeigen.de&url=https%3A%2F%2Fwww.ebay-kleinanzeigen.de%2`
and then it goes on ebay with that link( a lot of parameters are included and i think they're always the same)
`https://www.ebay.com/?PARM3_ID=GBH_168&PARM3_ID=GBH_168&FF11=GBH_168&kw=6348a39840621700014fa315_14846&FF11=GBH_168&kw=6348a34ec9e1110001b286b9_14846&mkevt=1&mkcid=16&mkrid=711-155609-835623-2&ufes_redirect=true&mkevt=1&mkcid=16&mkrid=711-155609-835623-2&ufes_redirect=true`

Any suggestions? Thanks in advance.

**UPD**: ebay link is the same, but seems to be changes only "kw" parameter. E.g. `https://www.ebay.com/?PARM3_ID=GBH_168&FF11=GBH_168&kw=6348bed0d1baf80001e6312b_14846&mkevt=1&mkcid=16&mkrid=711-155609-835623-2&ufes_redirect=true`

**Comment by mapx-** [comment]
>  getting infinite redirects from https://www.ebay-kleinanzeigen.de/ to ebay.com. I still do not understand steps of reproduce

You could at least provide minimal indications: 
- required account ?
- you get redirections clicking ... what ?
- could be a normal functionality of `ebay-kleinanzeigen.de` sending you on ebay site ?!

**Comment by VetaLioSTV** [comment]
> You could at least provide minimal indications:
> 
> * required account ?
> * you get redirections clicking ... what ?
> * could be a normal functionality of `ebay-kleinanzeigen.de` sending you on ebay site ?!

- No, you can browse it as guest. Just open several tabs(lets say 10 or 20), navigate to different ads\sections of the site and just wait
- its automatic redirections, i'm not clicking anything. Usually its like when you switch to another tab(change focus), previous tab which loses focus with **random** delay can be(and in the same time can't be) automatic redirects to rclick.site -> then on ebay.com with those parameters what i mentioned. Plus sometimes it brakes navigation and you can't go back to ebay-kleinanzeige.de
- I have no idea honestly... Ebay-kleinanzeigen its standalone service which has nothing with ebay (they're actually mention that on their FAQ i think)

UPD: new redirect on another link - 
`https://www.ebay.com/?mkcid=1&mkrid=711-53200-19255-0&siteid=0&campid=5338915856&customid=&toolid=10001&mkevt=1
`

**Comment by VetaLioSTV** [comment]
Hey, fortunenaly i found that i got installed two additional extensions which have reference on `ebay.com` , so i investigated and now i can make conclusion -> [search by image on ebay (extension) ](https://chrome.google.com/webstore/detail/search-by-image-on-ebay/hkcnldoebnmpehljkcklllnjnhdjcncp) did that infinite redirects on `ebay.com` and seems to be its broken completely. 

uBO has nothing with it. @mapx- could you change labels to not confuse people? Thanks in advance. Kind regards.
