### ISSUE TITLE
sanoybonito.club: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15250]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sanoybonito.club/que-sintomas-aparecen-en-caso-de-tumor-cerebral`

### Category

detection

### Describe the issue

Detection adblock 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85856
  cosmetic: 38943
  scriptlet: 18104
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    easylist: 62140-54, 5h.26m
    easyprivacy: 30714-1170, 5h.26m
    plowe-0: 3673-862, 5h.26m
    ublock-abuse: 76-0, 5h.26m
    ublock-badware: 4369-106, 5h.26m
    ublock-filters: 33060-107, 5h.26m
    ublock-privacy: 256-1, 5h.26m
    ublock-quick-fixes: 349-12, 5h.26m
    ublock-unbreak: 1870-43, 5h.26m
    urlhaus-1: 8897-0, 5h.26m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1009 ms (selfie)
  maxAssetCacheWait: 501 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    sanoybonito.club: 1
    arc.io: 1
    cloudflareinsights.com: 1
    doubleclick.net: 2
    google-analytics.com: 1
    googletagmanager.com: 2
    sentry-cdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I found one link redirecting to `sanoybonito.club` but I can just reproduce focus detection and timer

`https://link.rota.cc/kYFS`
