### ISSUE TITLE
tv8.com.tr: ads

### ISSUE THREAD

**Issue by digaxie** [uBlockOrigin/uAssets#15251]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tv8.com.tr/canli-yayin`

### Category

ads

### Describe the issue

> [Turkish] Merhaba, tv8 canlı yayınını izlerken canlı yayın video oynatıcısından sürekli reklam çıkıyor ve bu reklamlar minimum 30 saniye oluyor. 

**[English] Hello, while watching tv8 live broadcast, advertisements are constantly appearing on the live broadcast video player and these advertisements last for a minimum of 30 seconds.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87806
  cosmetic: 45780
  scriptlet: 18758
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 9257-14, 2d.22h.33m
    easylist: 62404-70, 2d.22h.29m
    easyprivacy: 30703-1175, 2d.22h.28m
    plowe-0: 3671-863, 2d.22h.27m
    ublock-abuse: 76-0, 2d.22h.25m
    ublock-badware: 4364-105, 2d.22h.23m
    ublock-filters: 33086-139, 2d.22h.22m
    ublock-privacy: 250-1, 2d.22h.21m
    ublock-quick-fixes: 340-11, 10h.45m
    ublock-unbreak: 1874-43, 2d.22h.19m
    urlhaus-1: 8897-0, 10h.44m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 198 ms (selfie)
  maxAssetCacheWait: 80 ms
popupPanel: 
  blocked: 82
  blockedDetails: 
    adform.net: 1
    adsrvr.org: 6
    doubleclick.net: 24
    doubleverify.com: 9
    gemius.pl: 14
    google-analytics.com: 1
    google.com: 5
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    onesignal.com: 1
    scorecardresearch.com: 1
    serving-sys.com: 6
    spotxchange.com: 11
```
</details>

**Comment by okiehsch** [comment]
I see 
![image](https://user-images.githubusercontent.com/16838044/195684196-a3405e3d-98fc-41a7-9d79-ec34023ccff8.png)

I suppose that means they are in a commerical break and live broadcasting will continue soon.

**Comment by digaxie** [comment]
> I see ![image](https://user-images.githubusercontent.com/16838044/195684196-a3405e3d-98fc-41a7-9d79-ec34023ccff8.png)
> 
> I suppose that means they are in a commerical break and live broadcasting will continue soon.

They are applying different advertisements for web live broadcasts. It is completely different from satellite broadcasting.

**Comment by okiehsch** [comment]
Well, but this appears to be part of their stream, so I don't see how we could "remove" it.

**Comment by mapx-** [comment]
it's live ?!

I can see in some of the m3u8 files the ads (`/ad/`):

`https://tv8-live.daioncdn.net/tv8/ad/9c2e0edb-f371-4d4f-843d-f94114122211/632/632909919183450945_720p_02.ts`

using uBO dev version you could test:

`tv8.com.tr##+js(m3u-prune, tv8-live.daioncdn.net/tv8/ad/, /tv8\.daioncdn\.net\/.*\.m3u8.*/)`

(it's about the normal ads not the "dijital" stuff)

**Comment by okiehsch** [comment]
Yes, it's a live stream, you can jump back to any point in the last 15 minutes.

**Comment by okiehsch** [comment]
Looking through the last 15 minutes, I don't see any "normal ads".

**Comment by mapx-** [comment]
yes, very rare

![image](https://user-images.githubusercontent.com/10303732/195703493-6370d1c2-8b04-4354-ae63-271fb187f49c.png)

**Comment by mapx-** [comment]
@digaxie could you test the filter above ? (first you should install the [dev build of uBO](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii))

keep the stable uBO build disabled (do not remove it)

**Comment by digaxie** [comment]
> @digaxie could you test the filter above ? (first you should install the last [dev build of uBO for chrome](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii))
> 
> keep the stable uBO build disabled (do not remove it)

I tested it but unfortunately, it doesn't work.

**Comment by mapx-** [comment]
using that filter, going back in the stream, I get only these sort of `.ts` requests
(those with `/crea/` are for `dijital` pauses)

![image](https://user-images.githubusercontent.com/10303732/195817212-673824b7-386a-480e-ac32-935d1f1c668d.png)

**Comment by mapx-** [comment]
do you get .ts requests of this type ?

`tv8-live.daioncdn.net/tv8/ad/...`

do you see in the logger the filter 
`tv8.com.tr##+js(m3u-prune, tv8-live.daioncdn.net/tv8/ad/, /tv8\.daioncdn\.net\/.*\.m3u8.*/)`
