### ISSUE TITLE
betanews.com: nuisance

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#15256]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://betanews.com/`

### Category

nuisance, images seem to appear after the page loads

### Describe the issue

Going to betanews.com the page content seems to load and then a few seconds later the images appear. I believe that its a lazy load issue.

`<a href="[https://betanews.com/2022/10/13/microsoft-is-updating-snipping-tool-to-bring-a-proper-screen-recorder-to-windows-11/](view-source:https://betanews.com/2022/10/13/microsoft-is-updating-snipping-tool-to-bring-a-proper-screen-recorder-to-windows-11/)"><img width="350" height="200" src="[https://betanews.com/wp-content/uploads/2022/10/snipping_tool_screen_recorder-350x200.jpg](view-source:https://betanews.com/wp-content/uploads/2022/10/snipping_tool_screen_recorder-350x200.jpg)" class="wp-image-474799 thumb wp-post-image" alt="Snipping Tool Screen Recorder" loading="lazy" /></a>`

last line

### Screenshot(s)

<details>
Screen shot would not depict the issue.
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b14
Firefox: 106
filterset (summary): 
  network: 163753
  cosmetic: 127688
  scriptlet: 23006
  html: 815
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 442-0, 1h.42m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/socialplus.txt: 114-0, 6h.57m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 468-1, 7h.23m
    https://www.i-dont-care-about-cookies.eu/abp/: 25415-4, 7h.23m
    adguard-spyware-url: 791-3, 7h.23m
    block-lan: 44-0, 7h.23m
    curben-phishing: 70847-6, 7h.23m
    fanboy-annoyance: 80942-9488, 7h.23m
    ublock-annoyances: 4867-9, 7h.23m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33786-49, 7h.23m
    ublock-badware: 4373-0, 7h.23m
    ublock-privacy: 281-0, 7h.23m
    ublock-abuse: 76-0, 7h.23m
    ublock-unbreak: 1883-4, 7h.23m
    ublock-quick-fixes: 348-0, 7h.23m
    easylist: 62191-349, 7h.23m
    easyprivacy: 30714-1190, 7h.23m
    urlhaus-1: 8864-0, 7h.23m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 262 ms (selfie)
  maxAssetCacheWait: 319 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    betanews.com: 2
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    linkedin.com: 1
    nsstatic.net: 2
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
test on default settings + fanboy's annoyances (some lazy stuff from FB frames)
