### ISSUE TITLE
Google localservices ads

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15259]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.google.com/localservices/prolist?src=1&slp=UgQIAiAAQAE%3D&scp=Ci94Y2F0OnNlcnZpY2VfYXJlYV9idXNpbmVzc190cmFmZmljX2xhd3llcjplbi1VUxoLVHJhZmZpYyBMYXcqC1RyYWZmaWMgTGF3&q=Traffic%20Law&ved=0CEAQ2MAHahcKEwigoOCK2d76AhUAAAAAHQAAAAAQAg`

`https://www.google.com/localservices/prolist?g2lbs=AL1YbfVry30D9slE_bnJ0YZPjkMw_NA8T5dK37Iw8MW60b3tIypCTpzP9y6KplOsM7UahKuxuzvq2_7A8IcXthEA8bnCUzfPEQ%3D%3D&hl=en-US&gl=us&ssta=1&q=CHICAGO%20CAR%20ACCIDENT%20ATTORNEY&oq=CHICAGO%20CAR%20ACCIDENT%20ATTORNEY&scp=ChtnY2lkOnBlcnNvbmFsX2luanVyeV9sYXd5ZXISTRISCe3L9NA8LA6IEQDAwAmtpuCvGhIJdRNDZqqxD4gRPOAOIwnX2YoiC0NoaWNhZ28sIElMKhQN1WvSGBVTYZXLHY44DBkl_vLUyzAAGhVDQVIgQUNDSURFTlQgQVRUT1JORVkiHUNISUNBR08gQ0FSIEFDQ0lERU5UIEFUVE9STkVZKhhQZXJzb25hbCBpbmp1cnkgYXR0b3JuZXk%3D&slp=MgBSAggCYAByCy9nLzF0czNsc3BfcgsvZy8xdGQxdzBsaHILL2cvMXZ4ZHl3MGZyCy9nLzF0Zjl5X3AxcgsvZy8xdGRtZmdrZnILL2cvMXR0OGN2dnByCy9nLzF0aHA4a3F6cgsvZy8xdGh4MDBmYnILL2cvMXRkbGM5NW5yCy9nLzF3NnI4dzdycgsvZy8xdGpqcHo1a3ILL2cvMXRqOXR4dnhyCy9nLzF2ZDcxeHFwcgsvZy8xdGY0OHIyenILL2cvMXRmODI1Z2hyCy9nLzF0ZjE2Zzhjcg0vZy8xMWNzOXc2Mmgycg0vZy8xMWZzcHZuNm1xcgsvZy8xdGN0ZzY4OHILL2cvMXRjeTlobWg%3D&src=2`

### Describe the issue

Sponsored "google screened" listings at the top of the search

### Screenshot(s)

![Screen Shot 2022-10-13 at 7 53 20 PM](https://user-images.githubusercontent.com/54487525/195751557-8b5178fc-ef6e-404b-a850-87c1843d4a83.png)
![Screen Shot 2022-10-13 at 7 53 40 PM](https://user-images.githubusercontent.com/54487525/195751561-71005e23-ce72-4441-9af9-d69f38cf6456.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85817
  cosmetic: 38928
  scriptlet: 18095
  html: 786
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33802-33, 1m
    ublock-badware: 4373-0, 1m
    ublock-privacy: 281-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1883-1, 1m
    ublock-quick-fixes: 360-12, 1m
    easylist: 62140-604, 1m
    easyprivacy: 30718-1705, 1m
    urlhaus-1: 8836-0, 1m
    plowe-0: 3673-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1654 ms
  maxAssetCacheWait: 731 ms
```
</details>

**Comment by mapx-** [comment]
add

`google.com##[data-profile-url-path^="/localservices"]:has-text(/Ad/):has-text(/google/i)`

@ryanbr
