### ISSUE TITLE
dofuspourlesnoobs.com: ads

### ISSUE THREAD

**Issue by adepierre** [uBlockOrigin/uAssets#15252]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dofuspourlesnoobs.com/le-serment-de-l-ambre.html`

### Category

ads

### Describe the issue

Top and side ad banners

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/24371370/195692003-5357e9d5-510f-4cef-93d1-afb8bd823ea7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 106765
  cosmetic: 48099
  scriptlet: 18142
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 20h.22m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    FRA-0: 30943-23, 2d.22h.30m
    easylist: 62527-1011, 2d.1h.57m
    easyprivacy: 30705-1471, 2d.19h.49m
    plowe-0: 3665-869, 11d.20h.48m
    ublock-abuse: 76-1, 11d.20h.47m
    ublock-badware: 4364-115, 2d.22h.29m
    ublock-filters: 33085-258, 2d.22h.28m
    ublock-privacy: 249-1, 11d.20h.46m
    ublock-quick-fixes: 330-11, 23h.58m
    ublock-unbreak: 1871-43, 2d.22h.27m
    urlhaus-1: 9206-0, 23h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 964 ms
  maxAssetCacheWait: 272 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    dofuspourlesnoobs.com: 1
    google-analytics.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by adepierre** [comment]
I might be wrong but I don't think it solved the issue. I tried to purge all cache and update now the filters to get the newest version and reloaded the page (while clearing cache) and the ad banners are still present.

Maybe I missed a step during the update process?

**Comment by okiehsch** [comment]
Hm, it's fixed now on my end, it was caused by an outdated filter in the `uBO-filters` list, which I removed.

This is what I see now after updating that list.
![image](https://user-images.githubusercontent.com/16838044/195701848-ea140eea-ad25-4516-95ff-0586c9092903.png)

Try updating one more time.

**Comment by adepierre** [comment]
I tried to update one more time and same result. But after taking a closer look, it seems they are gif/png hosted directly on the website domain. So I guess they might be only displayed under some conditions (perhaps language condition to not display french ads for non french speakers). I'll check back in a few days to be sure it's not just that I didn't update properly (which is totally possible).

Thank you very much for your time and the quick responses!

**Comment by mapx-** [comment]
I get the ads:

add

```
dofuspourlesnoobs.com##.dpln-affivis
dofuspourlesnoobs.com##.dpln-affitt
```

**Comment by mapx-** [comment]
@smed79

**Comment by adepierre** [comment]
> add
> 
> ```
> dofuspourlesnoobs.com##.dpln-affivis
> dofuspourlesnoobs.com##.dpln-affitt
> ```

I can confirm this worked on my side. Thanks!
