### ISSUE TITLE
[nsfw] ultrasurfing.com: popups

### ISSUE THREAD

**Issue by verkan2021** [uBlockOrigin/uAssets#15266]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ultrasurfing.com/`

### Category

Popups windows Ultrasurf
Ultrasurf continuously opens tabs leading to its domain, 

### Describe the issue

popups windows.
Ultrasurf continuously opens tabs leading to its domain, 
even if blocked by Hosts file if UBlock Oringin is activated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87743
  cosmetic: 46093
  scriptlet: 17653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 13204-0, 39m
    easylist: 61932-60, 36m
    easyprivacy: 30724-1172, 35m
    plowe-0: 3673-864, 34m
    ublock-abuse: 76-0, 32m
    ublock-badware: 4369-106, 6m
    ublock-filters: 32512-208, never
    ublock-privacy: 231-3, never
    ublock-quick-fixes: 389-37, never
    ublock-unbreak: 1858-42, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1661 ms
  maxAssetCacheWait: 603 ms
popupPanel: 
  blocked: 0
  no-scripting: true
```
</details>

**Comment by mapx-** [comment]
> `no-scripting: true`

I get no popup even disabling uBO

However you modified the default settings, so .. you should reset uBO to the default setup or reinstall it
