### ISSUE TITLE
gadgetbytenepal.com: ads

### ISSUE THREAD

**Issue by maxondm** [uBlockOrigin/uAssets#15263]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gadgetbytenepal.com/`

### Category

ads

### Describe the issue

Most of the image banners showing on this site are not automatically blocked by UB. It's obvious that these ad banners point to facebook pages of different brands.

There are also popup banners throughout the website which are also not picked up by UB.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 86194
  cosmetic: 39039
  scriptlet: 18087
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 199-45, never
    easylist: 62139-54, 22h.17m
    easyprivacy: 30703-1170, 3d.17h.31m
    plowe-0: 3669-863, 10d.21h.12m
    ublock-abuse: 76-0, 10d.21h.14m
    ublock-badware: 4364-106, 1d.21h.36m
    ublock-filters: 33058-106, 1d.21h.37m
    ublock-privacy: 249-1, 10d.21h.15m
    ublock-quick-fixes: 340-12, 1d.13h.25m
    ublock-unbreak: 1873-43, 1d.21h.38m
    urlhaus-1: 9206-0, 1d.13h.26m
filterset (user): [array of 199 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3807 ms (selfie)
  maxAssetCacheWait: 646 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    gadgetbytenepal.com: 1
    google-analytics.com: 1
    onesignal.com: 1
```
</details>

**Comment by mapx-** [comment]
I found these ones:

```
gadgetbytenepal.com##.custom_ad_responsive
gadgetbytenepal.com###darazAd
```

What else still there ?
