### ISSUE TITLE
reddit.com: nuisance

### ISSUE THREAD

**Issue by SWhitefox** [uBlockOrigin/uAssets#15260]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/r/mobileweb/`

### Category

nuisance

### Describe the issue

The page randomly fades to black, blocks the ability to scroll, and asks the user to choose to continue with the browser or the app. It detects the mobile browser useragent and tries to become a nuisance to force you into downloading the app or closing the popup over and over.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_20221014_090753](https://user-images.githubusercontent.com/97804310/195784359-b0ac46e1-3c85-46bc-9a32-0d953872a1d2.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 90124
  cosmetic: 32405
  scriptlet: 18368
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 93-4, never
    ublock-filters: 33896-345, 1d.16h.29m
    ublock-badware: 4367-0, 2d.5h.47m
    ublock-privacy: 274-1, 6d.11h.52m
    ublock-abuse: 76-0, 6d.11h.53m
    ublock-unbreak: 1893-1, 2d.5h.48m
    ublock-quick-fixes: 350-0, 12h.40m
    adguard-mobile: 8145-168, 1d.16h.30m
    easylist: 62491-18339, 5d.5h.7m
    easyprivacy: 30695-1731, 6d.6h.37m
    urlhaus-1: 8897-0, 12h.38m
    plowe-0: 3671-3, 6d.11h.50m
    spa-0: 3304-237, 12h.39m
    spa-1: 4714-189, 1d.16h.28m
filterset (user): [array of 94 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 254 ms (selfie)
  maxAssetCacheWait: 313 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    reddit.com: 8
    amazon-adsystem.com: 1
    googletagservices.com: 1
    redditmedia.com: 8
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances` and test again

**Comment by SWhitefox** [comment]
It seems to do the trick. Thank you!

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/y46aei/reddit_firefix_mobile_app_nag/ ?

**Comment by krystian3w** [comment]
IMO pop-up back on these link:

```
https://www.reddit.com/r/Overwatch/comments/yaap2s/what_happens_to_people_who_buy_this_not_knowing/
```

```adb
! Last modified: Sun, 23 Oct 2022 05:19:30 +0000
```
