### ISSUE TITLE
fox10phoenix.com: Ads

### ISSUE THREAD

**Issue by Arsenal4904** [uBlockOrigin/uAssets#15262]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.fox10phoenix.com`

### Describe the issue

Wait for any of the Fox-company-owned stations (not just 10 Phoenix - it also happens on the other stations’ websites) to go on commercial breaks during live stream and after some 20-30 seconds of commercial break music it goes to ads with “Advertisement, it will end at the break” on top

### uBlock Origin version

1.44.4

### Browser name and version

Google Chrome 106.0.5249.119

### Settings

None

**Comment by okiehsch** [comment]
Can you test
`||dcs-mcdn.mp.lura.live/prod/*$xhr,domain=fox10phoenix.com`
on those stations, it works on my end but I only tested `fox10phoenix.com`.
You add `||dcs-mcdn.mp.lura.live/prod/*$xhr,domain=fox10phoenix.com` to your filter list and replace `fox10phoenix.com`
with whatever station you test.

**Comment by Arsenal4904** [comment]
It works! Thanks!

**Comment by mapx-** [comment]
Did you test all those fox stations ?
Could you provide a list of those sites ?

**Comment by Arsenal4904** [comment]
Los Angeles - `foxla.com` - it works!

New York - `fox5ny.com` - it works!

Chicago - `fox32chicago.com` - yes!

Thank you!

**Comment by liamengland1** [comment]
@okiehsch that domain also serves ad segments on nexstar stations such as `https://www.woodtv.com/live-streaming-video/` and `https://www.wytv.com/live-stream/`. I am pretty confident that the filter can be made generic, I have had that domain blocked for years with no negative effects. 

also `||dcs-mcdn.mp.lura.live/prod/vast_json/` could be added too

![image](https://user-images.githubusercontent.com/16567977/205732212-b02c8b44-cd74-45a7-9b6b-5face2f9ea9b.png)
