### ISSUE TITLE
tron-free.com: detection

### ISSUE THREAD

**Issue by TRONSYE** [uBlockOrigin/uAssets#15265]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tron-free.com/`

### Category

detection

### Describe the issue

Detects the addition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 105
filterset (summary): 
  network: 93737
  cosmetic: 48727
  scriptlet: 30191
  html: 0
listset (total-discarded, last updated): 
  removed: 
    adguard-mobile: null
    easylist: null
  added: 
    adguard-generic: 64366-1138, 2d.15h.57m
  default: 
    user-filters: 2229-62, never
    FRA-0: 31070-3260, 2d.15h.57m
    ara-0: 2601-255, 15h.11m
    easyprivacy: 30709-1536, 2d.15h.57m
    plowe-0: 3671-554, 2d.15h.57m
    ublock-abuse: 76-1, 2d.15h.57m
    ublock-badware: 4363-174, 2d.15h.56m
    ublock-filters: 33160-3695, 2d.15h.56m
    ublock-privacy: 256-2, 2d.15h.56m
    ublock-quick-fixes: 350-23, 15h.10m
    ublock-unbreak: 1880-68, 2d.15h.56m
    urlhaus-1: 8864-0, 15h.8m
filterset (user): [array of 2029 redacted]
trustedset: 
  added: [array of 34 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1415 ms (selfie)
  maxAssetCacheWait: 514 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
I can reproduce anti adblock on the crappy link shortener but not on the site itself
