### ISSUE TITLE
fantasytagtree - context menu blockage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15274]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.fantasytagtree.com/workscontentcate?worksNo=FT31628754`

### Describe the issue

Right-clicking over an image will not work. Right-clicking somewhere else will though.

### Notes

Still happens with AdGuard Chinese enabled. 

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 85757
  cosmetic: 38712
  scriptlet: 18096
  html: 786
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33815-49, now
    ublock-badware: 4373-0, now
    ublock-privacy: 281-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1883-1, now
    ublock-quick-fixes: 366-0, now
    easylist: 61966-606, now
    easyprivacy: 30724-1707, now
    urlhaus-1: 8717-0, now
    plowe-0: 3675-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 944 ms (selfie)
  maxAssetCacheWait: 619 ms
```
</details>

**Comment by stephenhawk8054** [comment]
@contextnerror Can you check if adding this filter causes any breakages?

```adb
fantasytagtree.com##+js(aost, document.getElementById, nouplaod)
```

---

@mapx- I wonder if we have any ways to remove event listeners on the nodes that are not `html` or `body`

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/66517106/195962305-9fb9ac3b-2021-4258-b262-4f0488c123e4.png)

</details>

**Comment by contextnerror** [comment]
Everything seems to still be functional after a quick test.

**Comment by stephenhawk8054** [comment]
@contextnerror Enable `uBlock filters – Annoyances` list and force update your filter lists ([click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) in about 10 minutes.

**Comment by mapx-** [comment]
@stephenhawk8054 

We'd need something like this (waiting for the end of script execution)

```
(function() {
  let timeout;
  timeout = setTimeout(xxx, 2000);
  function xxx() {
    var outerHtmlElm = document.getElementById('contentp');
    if(outerHtmlElm){
      outerHtmlElm.outerHTML=outerHtmlElm.outerHTML;
    };
}
})();
```

**Comment by mapx-** [comment]
However `outerHTML` will kill all the events for that element

**Comment by stephenhawk8054** [comment]
> However `outerHTML` will kill all the events for that element

Yeah right. If the event function has a name, maybe we can use `removeEventListener`?

**Comment by mapx-** [comment]
It seems so, for anonymous  function is complicated, maybe a "wrapper for addEventListener" could help as writen here:
https://stackoverflow.com/questions/4386300/javascript-dom-how-to-remove-all-event-listeners-of-a-dom-object

**Comment by stephenhawk8054** [comment]
> It seems so, for anonymous function is complicated, maybe a "wrapper for addEventListener" could help as writen here: https://stackoverflow.com/questions/4386300/javascript-dom-how-to-remove-all-event-listeners-of-a-dom-object (I'm not a javascript expert :) )

Yeah I'm not either :D I used to try removing the event listeners via userscripts but still failed with anonymous ones. Some answers on that thread looks interesting tho.

**Comment by gwarser** [comment]
Aborting on `HTMLelement.prototype.oncontextmenu` does not work?
