### ISSUE TITLE
Images put to display none on Tweakers.net frontpage

### ISSUE THREAD

**Issue by Eenpersoonscommissie** [uBlockOrigin/uAssets#15271]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tweakers.net/`

### Describe the issue

The feature images of the story's on tweakers.net are put to display: none, while the div in which they are placed are (deliberately) blurred out ( css .ankeiler.large::before, .ankeiler.medium::before {filter: blur(8px) } }. With ublock turned off the images are shown as they should.
I'm not sure why the underlaying bg-images are blurred, but the included images should not be put to display: none, I think.

### Screenshot(s)

![firefox_urimLhIu7i](https://user-images.githubusercontent.com/33956440/195942275-32d56c5e-3df6-4300-bd99-7fa30fa86bbe.png)
Left Chromium without ublock, right fiefox with ublock on.

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 105.0.3 (Windows)

### Settings

Turned ublock off and refreshed the page, no special settings (due to recent reinstall of Windows).

### Notes

I turned off and on every addon, and found that ublock was the source of the added code (by inserting random attributes to the parent div of the image and giving that a display: none).

**Comment by mapx-** [comment]
add

`tweakers.net#@#img[src^="https://tweakers.net/i/"][src*="/1280x400/"]:upward(1)`

@BPower0036

**Comment by BPower0036** [comment]
See https://github.com/EasyDutch-uBO/EasyDutch/commit/32936cabb19601093fd484aaa541f390354aa22d
