### ISSUE TITLE
cia.gov: privacy

### ISSUE THREAD

**Issue by amogusussy** [uBlockOrigin/uAssets#15272]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cia.gov/`

### Category

privacy

### Describe the issue

There's 13 different scripts on this page which is the CENTRAL INTELLIGENCE AGENCY, and for some reason, none of them are blocked. I find it hard to believe that there's absolutely no tracking scripts of the website of an agency that notorious for spying.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 168734
  cosmetic: 90651
  scriptlet: 20838
  html: 785
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59658-613, 3d.13h.19m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33797-45, 3d.13h.18m
    ublock-badware: 4368-0, 3d.13h.17m
    ublock-privacy: 273-0, 12d.2h.27m
    ublock-abuse: 76-0, 12d.2h.27m
    ublock-unbreak: 1887-2, 3d.13h.16m
    ublock-quick-fixes: 360-0, 9h.45m
    easylist: 62486-598, 4d.6h.14m
    adguard-spyware-url: 781-3, 3d.13h.20m
    easyprivacy: 30703-1706, 4d.6h.13m
    urlhaus-1: 8836-0, 9h.44m
    curben-phishing: 75400-6, 9h.46m
    plowe-0: 3669-3, 12d.2h.27m
    LegitimateURLShortener: 1970-121, 22h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 24895 ms (selfie)
  maxAssetCacheWait: 1875 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Discuss it on reddit, this is a non-issue
https://www.reddit.com/r/uBlockOrigin
