### ISSUE TITLE
techydino.net: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15278]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techydino.net/2020/09/11/blueberry-is-launching-a-new-phone-in-2020/`

### Category

detection

### Describe the issue

Detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86009
  cosmetic: 38717
  scriptlet: 18118
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    easylist: 61968-54, now
    easyprivacy: 30725-1170, now
    plowe-0: 3675-865, now
    ublock-abuse: 76-0, now
    ublock-badware: 4369-106, now
    ublock-filters: 33088-106, now
    ublock-privacy: 256-1, now
    ublock-quick-fixes: 356-18, now
    ublock-unbreak: 1872-43, now
    urlhaus-1: 8969-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1754 ms (selfie)
  maxAssetCacheWait: 1696 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    a-ads.com: 1
    darghinruskin.com: 1
    googlesyndication.com: 3
    inbdmaza.com: 1
    thisiswaldo.com: 1
```
</details>

**Comment by hunterkais** [comment]
also blog.mdn.lol (https://blog.mdn.lol/post/forex---how-and-should-you-invest). continued from the link above

**Comment by okiehsch** [comment]
` blog.mdn.lol`
I don't see any detection, is that not already fixed by https://github.com/uBlockOrigin/uAssets/issues/15277

**Comment by hunterkais** [comment]
you can start from this link https://clks.pro/OWmgpc5supk
he have 3 step, first detection adblock, second no detection, third detection adblock.

**Comment by hunterkais** [comment]
![image](https://user-images.githubusercontent.com/114012899/195986641-4469e49b-ace1-40ef-aeed-f4b534a0c3fd.png)

**Comment by stephenhawk8054** [comment]
Please always give original link for these redirection sites. Otherwise we cannot investigate them properly.

**Comment by hunterkais** [comment]
i'm sorry, this original link https://clks.pro/OWmgpc5supk

**Comment by stephenhawk8054** [comment]
The sites are updated here: https://github.com/uBlockOrigin/uAssets/commit/ee4d982877bc61b7f5b7e361432ef786c89d1ebf . You can force update the filter lists and test again
