### ISSUE TITLE
george.sparkasse.at: breakage

### ISSUE THREAD

**Issue by 10Meisterbaelle** [uBlockOrigin/uAssets#15273]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://george.sparkasse.at/index.html?at=c`

### Category

breakage

### Describe the issue

There is a white bar on the site and some part of the payment details is cut off. The weird thing is that uBlock Origin doesn't show that anything was blocked, however it doesn't occur when turning it off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-10-14 at 23-40-25 George](https://user-images.githubusercontent.com/45918080/195948833-cabda069-bb4b-4972-9b38-cfb22de77541.png)

I needed to censor a few things to protect my privacy

 

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 91560
  cosmetic: 97019
  scriptlet: 22974
  html: 806
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 25415-4, 10h.56m
    fanboy-cookiemonster: 41384-9268, 10h.57m
    ublock-annoyances: 4873-4, 13h.43m
  default: 
    user-filters: 4-0, never
    ublock-filters: 33802-57, 15h.39m
    ublock-badware: 4373-0, 13h.47m
    ublock-privacy: 281-0, 13h.46m
    ublock-abuse: 76-0, 13h.45m
    ublock-unbreak: 1883-1, 13h.44m
    ublock-quick-fixes: 360-0, 13h.42m
    easylist: 62563-621, 2d.6h.25m
    easyprivacy: 30712-1718, 2d.6h.23m
    urlhaus-1: 8836-0, 13h.41m
    plowe-0: 3672-3, 9d.11h.7m
    DEU-0: 5963-2, 13h.39m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 721 ms (selfie)
  maxAssetCacheWait: 372 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
It's a bank, no account and nothing blocked in the logger ? => we cannot investigate further.

try resetting uBO to default settings / lists, don't add any other lists, test again

**Comment by 10Meisterbaelle** [comment]
This did fix it, however just disabling the filterlists didn't work.

**Comment by 10Meisterbaelle** [comment]
This issue exists again. It seems to be some sort of bug within uBlock Origin that just randomly happens. The problem is that it can't be reproduced because it's a bank and requires login. I will try to figure out the cause of this issue myself, although I probably won't. I will reopen the issue for now

**Comment by 10Meisterbaelle** [comment]
I have tested it on other devices and it doesn't seem to happen there so it is probably just some weird bug with my computer configuration.
