### ISSUE TITLE
http://stream.nbcolympics.com

### ISSUE THREAD

**Issue by OverlordQ** [uBlockOrigin/uAssets#1527]
### URL(s) where the issue occurs

`http://stream.nbcolympics.com/curling-mixed-doubles-round-robin-sheet-a-tiebreaker-day-2`

### Describe the issue

Give message: 

PLEASE TURN OFF YOUR AD BLOCKER
This video is unavailable if an ad blocker is running. Please disable and reload the page to start the video.

### Screenshot(s)

https://i.imgur.com/Nun2Ydi.png

### Versions

- Browser/version: Chrome 65
- uBlock Origin version: 1.15.4

### Settings

- No Changes

**Comment by okiehsch** [comment]
Video player is broken on my end, won't play even if I disable uBO.

Does
````
@@||hdliveextra-a.akamaihd.net/HD/scripts/V4.17/config/ads.js$script,domain=nbcolympics.com
@@||stream.nbcolympics.com/assets/page/general/ads.js$script,first-party
````
work for you?

**Comment by OverlordQ** [comment]
Seems like that should work, but for some reason it's not overriding entries from EasyList.

https://i.imgur.com/28exoKK.png

**Comment by okiehsch** [comment]
The "PLEASE TURN OFF YOUR AD BLOCKER" is fixed with those filters.
If the video plays fine on your end, I will add the filters, it doesn't for me, even if I whitelist the site, that's why I am asking.

**Comment by OverlordQ** [comment]
Yup works for me, excepting the unrelated issue.
