### ISSUE TITLE
Uniqueten.net detect

### ISSUE THREAD

**Issue by natandna** [uBlockOrigin/uAssets#15286]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://uniqueten.net/
https://uniqueten.net/adblock.html

From shortlink shortfly.me

### Describe the issue

Detect adblock

### Screenshot(s)

>
![Screenshot_2022-10-16-11-03-25-054_com kiwibrowser browser](https://user-images.githubusercontent.com/112774782/196017522-a96dba67-203e-419c-904d-80d92280206d.jpg)

### uBlock Origin version

Latest

### Browser name and version

Chrome

### Settings

Update

### Notes

From shortlink shortsfly.me

**Comment by stephenhawk8054** [comment]
Please do what I told here in your old thread:

https://github.com/uBlockOrigin/uAssets/issues/15170#issuecomment-1270072682
