### ISSUE TITLE
turkanime.co: popups

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#15280]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.turkanime.co/video/boku-no-hero-academia-6th-season-3-bolum`

### Category

popups

### Describe the issue

Click any link to reproduce it.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/196001931-34cfab87-6185-4bd7-b442-78ee70a997a9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 117030
  cosmetic: 147018
  scriptlet: 34076
  html: 786
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 64125-5105, 1m
    adguard-spyware: 35456-14285, now
    adguard-spyware-url: 791-3, now
    adguard-annoyance: 59710-1532, now
    adguard-social: 18550-26, now
  default: 
    user-filters: 69-0, never
    ublock-filters: 33834-69, 1m
    ublock-badware: 4373-0, 1m
    ublock-privacy: 281-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1885-2, 1m
    ublock-quick-fixes: 367-0, 1m
    easylist: 61981-327, now
    easyprivacy: 30725-1190, now
    TUR-0: 9363-10, now
filterset (user): [array of 77 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3292 ms (selfie)
  maxAssetCacheWait: 1722 ms
  unsuspendAfter: 2044 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adnuntius.com: 1
    animeevim.com: 2
    anisage.com: 4
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by 96273** [comment]
turkanime.co is now a parked domain, so the existing filter rules for this site can be safely removed.

**Comment by 96273** [comment]
One rule seems to have been missed: https://github.com/uBlockOrigin/uAssets/blob/d3496d135b532d8f783a761001e3f1fa2c43a0ac/filters/filters-general.txt#L1266
