### ISSUE TITLE
deer.egybest.ist: detection

### ISSUE THREAD

**Issue by YousefYousef0** [uBlockOrigin/uAssets#15284]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://deer.egybest.ist/`

### Category

detection

### Describe the issue

It can detect the addition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86314
  cosmetic: 38955
  scriptlet: 18097
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 62438-53, 6d.6h.5m
    easyprivacy: 30703-1170, 6d.6h.4m
    plowe-0: 3671-862, 5d.11h.41m
    ublock-abuse: 76-0, 5d.11h.43m
    ublock-badware: 4369-105, 3d.3h.28m
    ublock-filters: 33057-102, 3d.3h.27m
    ublock-privacy: 256-1, 5d.11h.44m
    ublock-quick-fixes: 357-12, 3h.40m
    ublock-unbreak: 1873-43, 3d.3h.29m
    urlhaus-1: 9070-0, 3h.41m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 43 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 340 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- at least on my side the anti adb stuff is gone
- if still does not work see this dedicated thread (duplicate)
https://github.com/uBlockOrigin/uAssets/issues/10255
