### ISSUE TITLE
animespank.com: popups

### ISSUE THREAD

**Issue by Lucasfita** [uBlockOrigin/uAssets#15294]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://animespank.com/`

### Category

popups

### Describe the issue

the site keeps popping up when you click on any part of the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87702
  cosmetic: 41965
  scriptlet: 18342
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62476-54, 6d.8h.53m
    easyprivacy: 30703-1170, 6d.8h.52m
    plowe-0: 3669-863, 12d.22h.1m
    spa-1: 4717-70, 3d.2h.31m
    ublock-abuse: 76-0, 15h.44m
    ublock-badware: 4369-105, 3d.2h.30m
    ublock-filters: 33060-134, 3d.2h.29m
    ublock-privacy: 256-1, 15h.43m
    ublock-quick-fixes: 357-13, 23h.46m
    ublock-unbreak: 1869-44, 3d.2h.28m
    urlhaus-1: 9070-0, 23h.45m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 260 ms (selfie)
  maxAssetCacheWait: 1296 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    googletagmanager.com: 1
    lassampy.com: 2
    onesignal.com: 1
    rtmark.net: 4
    tzegilo.com: 1
    waust.at: 1
```
</details>

**Comment by mapx-** [comment]
Test these filters

```
animespank.com#@#+js(abort-current-script, parseInt, break;case $.)
animespank.com##+js(aeld, , break;case $.)
```

(Brazilian ip)
