### ISSUE TITLE
dba.dk: ads

### ISSUE THREAD

**Issue by Nicholaiii** [uBlockOrigin/uAssets#15299]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dba.dk/soeg/side-3/?soeg=bianchi`

### Category

ads

### Describe the issue

Website features ads from `Buycycle` disguised as listings

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/7280931/196126159-d547c999-1fd5-4b19-a3df-67e07a45ea2c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86077
  cosmetic: 38849
  scriptlet: 17974
  html: 776
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33853-33, 20h.50m
    ublock-badware: 4368-0, 20h.51m
    ublock-privacy: 281-0, 5d.14h.34m
    ublock-abuse: 76-0, 5d.14h.33m
    ublock-unbreak: 1882-0, 3d.16h.43m
    easylist: 62124-602, 3d.16h.44m
    easyprivacy: 30712-1705, 3d.16h.45m
    urlhaus-1: 9208-0, 20h.49m
    plowe-0: 3671-3, 5d.14h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 387 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    doubleclick.net: 1
    google.com: 2
    googletagmanager.com: 1
    mainroll.com: 1
    videoplayerhub.com: 2
```
</details>

**Comment by krystian3w** [comment]
Enable Nordic List and try again:

https://filterlists.com/lists/dandelion-sprouts-nordic-filters-for-tidier-websites

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
On paper I could've added `dba.dk#?#.listing:has(span[title="Sælger er forhandler"])`; but then I'd leave myself vulnerable for accusations of inconsistent blocking, if anyone wondered why I'm strongly opposed to blocking retailer listings on its Norwegian equivalent `finn.no`, where retailer listings are pretty important for e.g. hot tubs and some electronics products.

So I'm declining to fix this as the situation currently stands.

**Comment by okiehsch** [comment]
@Nicholaiii add
`dba.dk##.listing:has(span[title="Sælger er forhandler"])`
to your filter list.

**Comment by okiehsch** [comment]
@DandelionSprout don't you think that this site is using sponsored listings in a different manner than `finn.no`?

Example: `https://www.finn.no/car/used/search.html?q=amg&sort=PUBLISHED_DESC` the sponsored listing is at the top and clearly labelled as such.
At `https://www.dba.dk/soeg/side-3/?soeg=bianchi` the sponsored articles are mixed in the "normal" listings and not clearly labelled.

**Comment by krystian3w** [comment]
Maybe upward:

`dba.dk##.listing span[title="Sælger er forhandler"]:upward(.listing)`

**Comment by DandelionSprout** [comment]
While looking further into the matter, I noticed something interesting.

@Nicholaiii Would you consider it practical during regular browsing of DBA to click on the "Private" button next to "Alle annoncer", which'd lead to e.g. `https://www.dba.dk/soeg/?soeg=bianchi&fra=privat` where no such listing-ads are shown at all?

![image](https://user-images.githubusercontent.com/22780683/196401335-07cc718e-a6f7-41da-8784-87c44a76fa68.png)

From what I can tell, that function would do exactly the same as what `dba.dk##.listing:has(span[title="Sælger er forhandler"])` does.

**Comment by krystian3w** [comment]
But uBo no added Point-of-Click and add-param to automate this without use declarative has into Chromium CSS.

**Comment by Nicholaiii** [comment]
> While looking further into the matter, I noticed something interesting.
> 
> @Nicholaiii Would you consider it practical during regular browsing of DBA to click on the "Private" button next to "Alle annoncer", which'd lead to e.g. `https://www.dba.dk/soeg/?soeg=bianchi&fra=privat` where no such listing-ads are shown at all?
> 
> ![image](https://user-images.githubusercontent.com/22780683/196401335-07cc718e-a6f7-41da-8784-87c44a76fa68.png)
> 
> From what I can tell, that function would do exactly the same as what `dba.dk##.listing:has(span[title="Sælger er forhandler"])` does.

This is only available on desktop. On mobile it's at least four interactions to enable the same function

**Comment by okiehsch** [comment]
Hm, ok I did not notice that you can actually sort between private and forhandlere, in that case it's not that much different than the `finn.no`.

**Comment by DandelionSprout** [comment]
I think I got Firefox Nightly Android to show private in 3 presses, but otherwise yes. Ironically I also found indisputable ads for `Pricerunner` in the mobile browser version of the site that I should block right away.
