### ISSUE TITLE
konami.com: breakage

### ISSUE THREAD

**Issue by Lubrsi** [uBlockOrigin/uAssets#15296]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.konami.com/games/silenthill/gate`

### Category

breakage

### Describe the issue

Cannot pass the age gate as you must accept cookies. The cookie prompt is loaded by Google Tag Manager which is blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/25595356/196059259-21e0222c-56b9-47be-872c-9ecf8e153d8d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86444
  cosmetic: 38735
  scriptlet: 18133
  html: 788
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33862-55, now
    ublock-badware: 4383-0, now
    ublock-privacy: 282-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1884-1, now
    easylist: 61991-609, now
    easyprivacy: 30731-1707, now
    urlhaus-1: 9368-0, now
    plowe-0: 3675-3, now
    ublock-quick-fixes: 381-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2896 ms (selfie)
  maxAssetCacheWait: 595 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    typekit.net: 1
```
</details>

**Comment by Yuki2718** [comment]
@ryanbr @Khrin ELC also needs exception.
