### ISSUE TITLE
rakhoi2.com: ads

### ISSUE THREAD

**Issue by elisehs7821** [uBlockOrigin/uAssets#15292]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rakhoi2.com/`

### Category

ads

### Describe the issue

Used to block ads perfectly, but now ads show a lot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/81814567/196043278-29d6657c-bf1a-443e-921e-45f7263d06d0.png)

</details>
![image](https://user-images.githubusercontent.com/81814567/196043278-29d6657c-bf1a-443e-921e-45f7263d06d0.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86721
  cosmetic: 40136
  scriptlet: 18186
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://abpvn.com/filter/abpvn-bN3Aba.txt?ublock: 1984-0, 2d.2h.10m
  default: 
    user-filters: 0-0, never
    easylist: 62502-72, 5d.4h.35m
    easyprivacy: 30709-1175, 5d.4h.37m
    plowe-0: 3671-862, 6d.20h.58m
    ublock-abuse: 76-0, 6d.20h.57m
    ublock-badware: 4369-105, 2d.2h.12m
    ublock-filters: 33058-112, 2d.2h.11m
    ublock-privacy: 250-1, 6d.20h.56m
    ublock-quick-fixes: 371-7, 1h.4m
    ublock-unbreak: 1870-43, 1d.19h.16m
    urlhaus-1: 8717-0, 2d.2h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 177 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add
```
rakhoi2.com##.modelAds
rakhoi2.com##.adHTML2
*.gif$domain=rakhoi2.com,image
```

for VIE list report here: https://github.com/abpvn/abpvn/issues
@hoang-rio

**Comment by okiehsch** [comment]
Basically all tthe filters in abpvn for `rakhoi1.com` are now obsolete because the site redirects to `rakhoi2.com`.
