### ISSUE TITLE
tv8.com.tr: ads

### ISSUE THREAD

**Issue by rebelfa1con** [uBlockOrigin/uAssets#15295]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [x] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tv8.com.tr/canli-yayin`

### Category

ads

### Describe the issue

they changed the video player, now they'r showing us ads while live stream is on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 179988
  cosmetic: 148911
  scriptlet: 21637
  html: 0
listset (total-discarded, last updated): 
  added: 
    ALB-0: 273-1, 12m
    BGR-0: 1091-11, 18h.41m
    CHN-0: 29410-87, 1d.4h.9m
    CZE-0: 730-0, 11m
    DEU-0: 5968-0, 9m
    EST-0: 451-1, 16m
    FIN-0: 2036-1, 1d.4h.8m
    FRA-0: 30562-72, 1d.4h.7m
    GRC-0: 1002-0, 18h.34m
    HUN-0: 2178-1, 8m
    IDN-0: 9163-23, 1d.4h.6m
    IND-0: 11692-0, 7m
    IRN-0: 2377-1, 18h.33m
    ISL-0: 194-1, 18h.39m
    ISR-0: 1653-2, 6m
    ITA-0: 13213-74, 5m
    JPN-1: 7976-16, 1d.4h.5m
    KOR-1: 3512-8, 4m
    LTU-0: 1194-7, 4d.19h.3m
    LVA-0: 392-2, 1d.4h.4m
    [14 lists not shown]: [too many]
  default: 
    user-filters: 83-10, never
    TUR-0: 9354-38, 2d.18h.9m
    easylist: 62495-336, 5d.22h.59m
    easyprivacy: 30703-1720, 5d.22h.57m
    plowe-0: 3675-925, 1d.22h.59m
    ublock-abuse: 76-2, 1d.3h.18m
    ublock-badware: 4369-146, 2d.6h.6m
    ublock-filters: 33068-479, 2d.6h.4m
    ublock-privacy: 256-3, 1d.3h.17m
    ublock-quick-fixes: 371-8, 15m
    ublock-unbreak: 1870-73, 2d.6h.5m
    urlhaus-1: 9368-0, 14m
filterset (user): [array of 83 redacted]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 315 ms
popupPanel: 
  blocked: 424
  blockedDetails: 
    adform.net: 3
    adnsafe.org: 2
    bluekai.com: 2
    doubleclick.net: 229
    doubleverify.com: 18
    gemius.pl: 43
    google-analytics.com: 1
    google.com: 5
    googlesyndication.com: 20
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    onesignal.com: 1
    serving-sys.com: 96
    spotxchange.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/15251
