### ISSUE TITLE
korinthostv.gr: ads

### ISSUE THREAD

**Issue by fanis2022** [uBlockOrigin/uAssets#15290]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://korinthostv.gr/`

### Category

ads

### Describe the issue

difficult to get rid of popup

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 103
filterset (summary): 
  network: 86667
  cosmetic: 0
  scriptlet: 18110
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    GRC-0: 1002-547, 1d.17h.27m
    easylist: 61934-29513, 1d.17h.27m
    easyprivacy: 30724-1172, 1d.17h.27m
    plowe-0: 3675-866, 1d.17h.27m
    ublock-abuse: 76-1, 1d.17h.27m
    ublock-badware: 4369-745, 1d.17h.27m
    ublock-filters: 33077-8353, 1d.17h.27m
    ublock-privacy: 256-11, 1d.17h.27m
    ublock-quick-fixes: 368-130, 28m
    ublock-unbreak: 1870-287, 1d.17h.27m
    urlhaus-1: 9208-0, 28m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 263 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    googletagmanager.com: 1
    onesignal.com: 1
    servedbyadbutler.com: 4
    twitter.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
korinthostv.gr##.banner-promotions-wrapper
korinthostv.gr##.sgpb-popup-dialog-main-div-wrapper
korinthostv.gr##.sgpb-popup-overlay
||korinthostv.gr/*.gif$image
korinthostv.gr##[href="https://korinthianpalace.gr/"]
korinthostv.gr##[href="https://www.oikonomou-shop.gr/"]
korinthostv.gr##[href="https://www.pietris.gr/"]
korinthostv.gr##[href="https://www.facebook.com/alfaproducts/"]
||korinthostv.gr/*BANNER$image
korinthostv.gr##[href="https://keferlis.gr/"]
```

fpr greek sites report directly here: https://github.com/kargig/greek-adblockplus-filter/issues

@kargig
@aldi

**Comment by fanis2022** [comment]
thank you for the solution
