### ISSUE TITLE
bc.vc [ADS]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1529]
URL(s) where the issue occurs

`http://bc.vc/tkGYMj2`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Checks timer server side and redirects to malicious domain if its too early.

**Comment by okiehsch** [comment]
Do you have an example link?
`http://bc.vc/tkGYMj2` does not redirect me to a malicious domain.

**Comment by okiehsch** [comment]
Thx.

**Comment by dumbusernameidk** [comment]
name has changed to `bcvc.live`.

**Comment by llacb47** [comment]
Changed, or is just another domain?

**Comment by ghajini** [comment]
`bcvc.live/X7NwcxA`
Sometimes popups

**Comment by ghajini** [comment]
Blank page
`https://bcvc.live/l5FckjT`

**Comment by mapx-** [comment]
it seems working:
`bcvc.live##+js(aopr, Notification)`

**Comment by bogachenko** [comment]
Fake buttons `http://bc.vc/C74U6RS`

**Comment by okiehsch** [comment]
I don't see any.
![image](https://user-images.githubusercontent.com/16838044/135977709-792f7626-f7f5-4e40-a930-73b3ab1b8e2f.png)

**Comment by bogachenko** [comment]
I had my cosmetic filters disabled, sorry, false alarm.
By the way, it was possible without an image.

**Comment by okiehsch** [comment]
What's the problem of me posting a screenshot?
If you feel somehow belittled by it, that was certainly not my intention.

**Comment by bogachenko** [comment]
Lol, there are no problems, I just can take your word for it and take a double check. Although it's your business, publish, your repository.
