### ISSUE TITLE
avsforum.com: breakage

### ISSUE THREAD

**Issue by J-HS-L** [uBlockOrigin/uAssets#15303]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.avsforum.com/`

### Category

breakage

### Describe the issue

Checked all the prereqs & met them all, unticked 'disable generic cosmetic' (after this config grab), but still no go; 

Alas, this config grab is a bit different from my last few revisions (usual + ~2 others); but I'm pretty sure none of them was any better.
Bit sleep fatigued atm.... eish...

Reset to default settings (I had it uploading to the cloud, but I can't find my config!?) & the issue went away...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/49305869/196182770-e84944ba-94cf-4753-aed3-c1fb63eeb90d.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 215099
  cosmetic: 146133
  scriptlet: 37724
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59738-1659, 2h.50m
    adguard-generic: 64145-849, 2h.55m
    adguard-mobile: 8144-64, 2h.49m
    block-lan: 44-0, 15d.22h.43m
    curben-phishing: 89563-0, 19h.1m
    curben-pup: 194-1, 19h
    dpollock-0: 11389-107, 4d.3h.29m
    fanboy-annoyance: 80847-37102, 4d.3h.28m
    ublock-annoyances: 4852-241, 2h.54m
  default: 
    user-filters: 1-0, never
    easylist: 61981-18295, 6h.57m
    easyprivacy: 30729-1494, 6h.56m
    plowe-0: 3675-1331, 2d.6h.1m
    ublock-abuse: 76-0, 4d.3h.26m
    ublock-badware: 4379-246, 2h.53m
    ublock-filters: 33121-4063, 2h.52m
    ublock-privacy: 256-9, 4d.3h.22m
    ublock-quick-fixes: 371-35, 18h.59m
    ublock-unbreak: 1872-86, 2h.51m
    urlhaus-1: 9368-4, 18h.58m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 39 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  colorBlindFriendly: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5451 ms (selfie)
  maxAssetCacheWait: 989 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  blockedDetails: 
    avsforum.com: 1
    deployads.com: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    speedcurve.com: 1
    threadloom.com: 1
```
</details>

**Comment by J-HS-L** [comment]
oh and made sure I searched first
https://github.com/uBlockOrigin/uAssets/issues?q=avsforum+in%3Abody%2Ccomments%2Ctitle

**Comment by mapx-** [comment]
> the issue went away...

No issue in the end ?!

**Comment by krystian3w** [comment]
Disable one by one:

```yml
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59738-1659, 2h.50m
    adguard-generic: 64145-849, 2h.55m
    adguard-mobile: 8144-64, 2h.49m
    block-lan: 44-0, 15d.22h.43m
    curben-phishing: 89563-0, 19h.1m
    curben-pup: 194-1, 19h
    dpollock-0: 11389-107, 4d.3h.29m
    fanboy-annoyance: 80847-37102, 4d.3h.28m
    ublock-annoyances: 4852-241, 2h.54m
```

**Comment by J-HS-L** [comment]
> > the issue went away...
> 
> No issue in the end ?!

Yeah, I couldn't afford to leave it in that state & troubleshoot further, just wanted it working asap.
