### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by varishtsg** [uBlockOrigin/uAssets#15309]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Describe the issue

Reddit on Firefox Android is broken. When browsing reddit on a mobile browser a pop up is shown asking whether to use the browser or install the app. 

UBO blocks this pop-up. Until the user doesn't make a selection, scrolling doesn't work. Only the page that is loaded is visible. This issue is only seen on the mobile version of the site. old.reddit.com works without issues. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 115064
  cosmetic: 160514
  scriptlet: 34589
  html: 787
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64121-5100, 21h.21m
    adguard-annoyance: 59758-5065, 21h.17m
    adguard-social: 18584-1136, 21h.18m
    fanboy-thirdparty_social: 68-1, 8d.6h.36m
    fanboy-annoyance: 80791-35574, 8d.6h.35m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33927-305, 1d.7h.22m
    ublock-badware: 4382-0, 1d.7h.21m
    ublock-privacy: 273-1, 11d.7h.28m
    ublock-abuse: 76-0, 11d.7h.27m
    ublock-unbreak: 1890-1, 1d.20h.5m
    ublock-quick-fixes: 391-0, 21h.15m
    adguard-mobile: 8142-168, 3d.5h.9m
    easylist: 61966-17946, 2d.2h.21m
    easyprivacy: 30731-1719, 14h.51m
    urlhaus-1: 9402-0, 21h.16m
    plowe-0: 3675-3, 1d.20h.6m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 826 ms (selfie)
  maxAssetCacheWait: 340 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by varishtsg** [comment]
Video of issue: https://imgur.com/a/dH513C0

**Comment by mapx-** [comment]
enable this uBO list
`uBlock filters – Annoyances`

@Yuki2718 
AG annoyances list needs this filter 
`reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)`
