### ISSUE TITLE
9anime.gs: popups

### ISSUE THREAD

**Issue by PKMN23** [uBlockOrigin/uAssets#15308]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://9anime.gs/watch/pokemon-the-series-sun-moon.x6lz/ep-78`

### Category

popups

### Describe the issue

When using the 'Filemoon' server type, clicking on the video occasionally opens new windows in Firefox. It tends to be for things like shopping sites, NSFW sites (which Ublock shows a warning for, thankfully), and even just a google search result page. It gets incredibly annoying and tedious.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86739
  cosmetic: 38985
  scriptlet: 18110
  html: 786
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33822-49, 2d.20h.33m
    ublock-badware: 4373-0, 2d.20h.32m
    ublock-privacy: 281-0, 1d.21h.54m
    ublock-abuse: 76-0, 1d.21h.53m
    ublock-unbreak: 1883-1, 2d.20h.31m
    ublock-quick-fixes: 378-0, 20h.3m
    easylist: 62538-598, 4d.21h.10m
    easyprivacy: 30709-1705, 4d.21h.9m
    urlhaus-1: 9402-0, 20h.2m
    plowe-0: 3672-3, 6d.1h.46m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 986 ms (selfie)
  maxAssetCacheWait: 610 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    9anime.gs: 1
    addthis.com: 1
    amung.us: 1
    arsnivyr.com: 8
    bidgear.com: 4
    filemoon.sx: 8
    pioneersuspectedjury.com: 2
```
</details>

**Comment by mapx-** [comment]
Test this filter

`filemoon.*##+js(aost, Object, /(?=^(?!.*(inlineScript|player|jquery|gstatic)))/, 2)`

**Comment by mapx-** [comment]
However, I was able to reproduce only in firefox sometimes, so I'll add a html filter
`filemoon.*##^script:has-text(/Math.floor|FMPoopS/)`

**Comment by ghajini** [comment]
any reason EL removed `||filemoon.sx/js/dola.js` which was merged over here https://github.com/easylist/easylist/commit/20328b884c1d665037994da84eeac3b0301dcbb3
@ryanbr
