### ISSUE TITLE
asla.egybest.bid: detection

### ISSUE THREAD

**Issue by pkerguy96** [uBlockOrigin/uAssets#15304]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://asla.egybest.bid/`

### Category

detection

### Describe the issue

detects ublock origine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 86661
  cosmetic: 38978
  scriptlet: 18118
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62502-54, 5d.20h.16m
    easyprivacy: 30709-1170, 5d.20h.15m
    plowe-0: 3671-862, 7d.1h.19m
    ublock-abuse: 76-0, 3d.15m
    ublock-badware: 4369-105, 3d.15h.16m
    ublock-filters: 33066-102, 3d.15h.15m
    ublock-privacy: 256-1, 3d.14m
    ublock-quick-fixes: 371-6, 22h.25m
    ublock-unbreak: 1869-43, 3d.15h.14m
    urlhaus-1: 9368-0, 22h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 155 ms (selfie)
  maxAssetCacheWait: 69 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Update all the lists then test again.
