### ISSUE TITLE
[nsfw] mail.google.com: ads

### ISSUE THREAD

**Issue by TlJones66** [uBlockOrigin/uAssets#15319]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/`

### Category

ads

### Describe the issue

They keep showing ads 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 86477
  cosmetic: 38705
  scriptlet: 18146
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61950-54, 1d.2h
    easyprivacy: 30731-1170, 1d.1h.58m
    plowe-0: 3671-862, 8d.2h.23m
    ublock-abuse: 76-0, 8d.2h.25m
    ublock-badware: 4379-106, 1d.3h.6m
    ublock-filters: 33144-109, 1d.3h.5m
    ublock-privacy: 256-1, 8d.2h.26m
    ublock-quick-fixes: 389-22, 6m
    ublock-unbreak: 1872-42, 1d.3h.7m
    urlhaus-1: 9383-0, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4229 ms (selfie)
  maxAssetCacheWait: 2409 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    google.com: 7
```
</details>

**Comment by mapx-** [comment]
Screenshot ?

Did you try reinstalling uBO ?
Did you try disabling all other extensions ?
