### ISSUE TITLE
expresskaszubski.pl: detection

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uAssets#15311]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://expresskaszubski.pl/pl/473_na-sygnale/42241_solectwo-borucino-ostrzega-przed-podejrzanym-mezczyzna-uwazajcie.html`

### Category

detection

### Describe the issue

"questpass"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/886325/196416587-eadc3e6e-323c-4648-9a63-13feae2e17c8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88111
  cosmetic: 46100
  scriptlet: 18351
  html: 0
listset (total-discarded, last updated): 
  added: 
    POL-0: 7860-8, now
    POL-2: 1276-13, now
  default: 
    user-filters: 0-0, never
    easylist: 62032-76, now
    easyprivacy: 30764-1170, now
    plowe-0: 3675-874, now
    ublock-abuse: 76-0, now
    ublock-badware: 4379-106, now
    ublock-filters: 33083-149, now
    ublock-privacy: 257-1, now
    ublock-quick-fixes: 389-23, now
    ublock-unbreak: 1875-43, now
    urlhaus-1: 9520-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 786 ms
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    expresskaszubski.pl: 1
    dqst.pl: 2
    googletagmanager.com: 1
    googletagservices.com: 2
    newrelic.com: 1
    powerad.ai: 1
    s-onetag.com: 1
    yieldbird.com: 1

```
</details>

**Comment by polskimudkip** [comment]
the website detects ublock, note that i disabled ALL other extensions, but it still shows an adblocker detection pop up; i also use the regional filter list
