### ISSUE TITLE
peugeotclub.eu [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1531]
URL(s) where the issue occurs

`http://www.peugeotclub.eu/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by nimasaj** [comment]
Isn't it possible to block it with _script:inject_ like the way you did [here](https://github.com/uBlockOrigin/uAssets/issues/1536)?

The following functions in `http://www.peugeotclub.eu/js/common_js.js?ver=40` are responsible for it. 

```
function f_check_health()
{
	if(!f_is_visible('obalovydiv'))
	{
		document.getElementById('thisPageBody').style.backgroundColor = '#FFFFFF';
		document.getElementById('thisPageBody').innerHTML = '<center>AdBl' + 'ock? S' + 'orry ..</center>';
		f_ajax_do('http://' + window.location.hostname + '/blocked_ad.php', 'thisPageBody', '');
	}
}
```

```
function f_is_visible(as_obj)
{
	var obj = document.getElementById(as_obj);
	var style = window.getComputedStyle(obj);
	return (obj.offsetWidth > 0 && obj.offsetHeight > 0 && !(style.display === 'none'));
}
```

Also, in page source:

```
<BODY
    onLoad=" f_check_health();"
    bgColor="#ADADAD"
    id="thisPageBody"
    style="margin-top: 0px;"
    >
     
    <div id="obalovydiv" class="reklama" style="">
```

**Comment by mapx-** [comment]
It's preferable using a `generichide` filter.

telolet cannot be fixed using only `generichide`.

**Comment by nimasaj** [comment]
Thanks for reply. Is it even possible to block with script inject here?
I can use the following one, but it only blocks redirecting.
`peugeotclub.eu##script:inject(abort-on-property-read.js, f_ajax_do)`

Then, I tried with followings, regarding _function f_is_visible(as_obj)_, but it didn't help as well.
```
peugeotclub.eu##script:inject(set-constant.js, obj.offsetWidth, 1)
peugeotclub.eu##script:inject(set-constant.js, obj.offsetHeight, 1)
peugeotclub.eu##script:inject(set-constant.js, style.display, whatever)
```
