### ISSUE TITLE
zattoo.com: ads

### ISSUE THREAD

**Issue by unikum** [uBlockOrigin/uAssets#15317]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zattoo.com/program/rtlnitro/269827321`
`https://zattoo.com/highlights?channel=rtlnitro&program=269827321`

### Category

ads

### Describe the issue

They started to interdouce "replay-TV ads". If they continue like that i will leave ZATTOO!!

can't be, paying enough each year for looking adds! hope the genius community may solve the problem... 

thanks for any one who pay effort to solve this! hugs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 88790
  cosmetic: 42490
  scriptlet: 18126
  html: 787
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33883-72, 1d
    ublock-badware: 4383-0, 15h.56m
    ublock-privacy: 273-0, 12d.55m
    ublock-abuse: 76-0, 3d.2h.42m
    ublock-unbreak: 1885-0, 19h.58m
    easylist: 61976-613, 1d.2m
    easyprivacy: 30731-1715, 1d.1m
    urlhaus-1: 9526-0, 19h.57m
    plowe-0: 3671-3, 6d.17h.19m
    DEU-0: 5975-2, 15h.55m
    ublock-quick-fixes: 378-1, 23h.59m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 364 ms (selfie)
  maxAssetCacheWait: 143 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    bitmovin.com: 2
    exactag.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gstatic.com: 8
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
@unikum without an account we cannot investigate if there is possible to fix it

**Comment by unikum** [comment]
if i would share my account, i get banned?!

i send this email to ZATTOO.COM
Sobald ich die Pause Taste auslöse, ist es in der Regel um ein Detail im "Film / Serie" zu sehen.
Bin ein Mensch mit Autismus Spektrum Störung. Falls es mir nicht mehr Möglich ist, diese Details zu sehen ohne zusätzliche Werbung die erscheint und das Bild verdeckt, werde iich alles mögliche von Psychologen, Kundendienst, Kundenschutz, Nachrichtenkamäle darüber informieren, dass  ZATTOO dies zu einer VERGEWALTIGUNG des Individums führt das eine Werbefreie Plattform bezahlt!
*CUT OUT OF TEXT*
PS: Falls Sie innerhalb 14 Tage diese Praktiken bei meinem Account nicht beenden, werden diese Informationen an weitere Stellen weiter geleitet werden.

i send this email to a newspaper:
Geschätztes Redaktions Team
Ich bin ein Mensch mit Autismus Spektrum. Nicht zu stark ausgeprägt, dennoch für mich kompliziert.
Seit gestern erscheint bei ZATTOO.CH Werbung trotz Abo .. und vorallem was mich sehr in meinem Lebenskomfort einschränkt, wenn ich eine Sekunde pausiere, ein WERBE Fenster erscheint. Ich pausiere häufig Szenen um mir Details anzuschauen, Hintergrund, Gesichtsmuskeln, Personen, Farben, Objekte.. die in der Aufnahme erscheinen... Sobald ich jedoch WERBUNG sehe, übeRennen mich Stresshormone! Sie können sich nicht vorstellen wie fest ich darunter leide!!
 
Geht das anderen auch so? Können Sie dem auf den Grund gehen? Müssen wir das ohne Einwilligung ertragen? Können wir das Abo kündigen und erhalten das Geld zurück falls diese Institutionen damit weiterfahren??...
 *CUT OUT OF TEXT*
Es würde mich ehren von einer euren Fachperson zu hören.

..hum.. i guess it's hard to find a AdBlock Solution for this? hope the pressure may cause something. If in any kind there is a genius , i may share my account.. even getting in risk to get banned..

**Comment by mapx-** [comment]
So, your issue is when you click pause ?

Try sending your credentials (I hope they are not asking for some verification via phone ..) via pm to this reddit user
https://www.reddit.com/user/ajaxmix

**Comment by mapx-** [comment]
closing (if I receive on reddit the credentials and if I'll find a fix => I will reply here)
