### ISSUE TITLE
eldenring.wiki.fextralife.com: ads

### ISSUE THREAD

**Issue by Sparkane** [uBlockOrigin/uAssets#15315]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eldenring.wiki.fextralife.com/Miriel+Pastor+of+Vows`

### Category

ads

### Describe the issue

There is a persistent, uncloseable twitch stream integration.

I do have adblock plus enabled for this report specifically **BUT** disabling it does not cause uBO to correctly remove this element.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/116094763/196466028-afaa2556-cb95-4fcf-86d0-a33d4809c89c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86609
  cosmetic: 38704
  scriptlet: 18145
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.1h.6m
  default: 
    user-filters: 0-0, never
    easylist: 61950-54, 21h.5m
    easyprivacy: 30731-1170, 21h.4m
    plowe-0: 3675-865, 2d.17h.49m
    ublock-abuse: 76-0, 11d.1h.24m
    ublock-badware: 4379-106, 17h.1m
    ublock-filters: 33145-109, 17h
    ublock-privacy: 249-1, 11d.1h.23m
    ublock-quick-fixes: 377-22, 21h.2m
    ublock-unbreak: 1875-42, 16h.59m
    urlhaus-1: 9526-0, 21h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 156 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    fextralife.com: 2
    addthis.com: 1
    d2v02itv0y9u9t.cloudfront.net: 1
    enthusiastgaming.net: 1
    google.co.uk: 1
    google.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 10
```
</details>

**Comment by mapx-** [comment]
- disable / remove ABP
- add
```
||embed.twitch.tv^$frame
eldenring.wiki.fextralife.com###join-vip-container
eldenring.wiki.fextralife.com##.ad-sidebar
```
