### ISSUE TITLE
caballeromoderno.com: breakage

### ISSUE THREAD

**Issue by lavadrop** [uBlockOrigin/uAssets#15320]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.caballeromoderno.com/`

### Describe the issue

Upper left hamburger button does nothing when blocking is enabled. When disabled, hamburger menu works.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 117981
  cosmetic: 220205
  scriptlet: 37824
  html: 795
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64131-4827, 1d.16h.54m
    adguard-mobile: 8144-149, 1d.16h.48m
    adguard-annoyance: 59710-5045, 1d.16h.55m
    adguard-social: 18550-1068, 1d.16h.56m
    fanboy-thirdparty_social: 68-0, 6h.6m
    fanboy-annoyance: 81374-65362, 6h.5m
    fanboy-cookiemonster: 41775-150, 6h.4m
    fanboy-social: 23395-28, 10h.7m
    ublock-annoyances: 4874-4, 1d.16h.49m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33836-94, 1d.16h.52m
    ublock-badware: 4383-0, 1d.16h.51m
    ublock-privacy: 281-0, 6d.13h.18m
    ublock-abuse: 76-0, 6d.13h.17m
    ublock-unbreak: 1885-0, 1d.16h.50m
    easylist: 61950-817, 22h.12m
    easyprivacy: 30752-1735, 22h.11m
    plowe-0: 3671-3, 10d.21h.43m
    spa-0: 3304-1, 22h.10m
    spa-1: 4720-111, 1d.16h.53m
    urlhaus-1: 9526-0, 22h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2021 ms (selfie)
  maxAssetCacheWait: 1125 ms
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdn.shopify.com/*/instafeed.min.js$script,domain=caballeromoderno.com`

@ryanbr
