### ISSUE TITLE
finviz.com: ads

### ISSUE THREAD

**Issue by JJonssen** [uBlockOrigin/uAssets#15323]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://finviz.com/futures_charts.ashx?t=METALS&p=h1`

### Category

ads

### Describe the issue

Some ads appeared just recently

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/116125513/196560277-b21d4768-17b4-46ab-858c-f2900f17cc93.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86268
  cosmetic: 38839
  scriptlet: 17953
  html: 775
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33814-108, 3d.18h.44m
    ublock-badware: 4373-0, 3d.18h.45m
    ublock-privacy: 281-0, 7d.8h.40m
    ublock-abuse: 76-0, 7d.8h.39m
    ublock-unbreak: 1885-0, 3d.18h.43m
    easylist: 62124-513, 3d.18h.46m
    easyprivacy: 30724-1722, 3d.14h.42m
    urlhaus-1: 9383-0, 6h.36m
    plowe-0: 3675-3, 2d.22h.40m
filterset (user): [array of 1 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 179560 ms (selfie)
  maxAssetCacheWait: 2277 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cloudflareinsights.com: 2
    googletagmanager.com: 1
    investingchannel.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
It's self-promotion

add
`finviz.com##[href^="/elite.ashx"]:has(picture)`

**Comment by JJonssen** [comment]
Doesn't that count then?

**Comment by JJonssen** [comment]
Didn't quite realise it was self-promotion. Assumed it came from an external source as it's where ads would usually be placed. Thanks.
