### ISSUE TITLE
[nsfw] tube8.com: breakage

### ISSUE THREAD

**Issue by Trouble-bubbles** [uBlockOrigin/uAssets#15328]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

[nsfw] `https://www.tube8.com/amateur/sweetsinner-milf-cant-stop-fucking-her-best-friends-husband/81281201/`

### Category

breakage

### Describe the issue

Video is blocked by filter:

https://github.com/easylist/easylist/blob/0bcb87b427314da1642d81e9e61d34f603f740ac/easylist_adult/adult_specific_hide.txt#L692

Please add `:not(video)`

Page use blob to harder download video and re-upload somewhere.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 105
filterset (summary): 
  network: 278129
  cosmetic: 131303
  scriptlet: 21891
  html: 1073
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33930-112, 1d.4h.43m
    ublock-badware: 4382-0, 1d.4h.43m
    ublock-privacy: 282-0, 1d.4h.43m
    ublock-abuse: 76-0, 1d.4h.43m
    ublock-unbreak: 1893-1, 1d.4h.43m
    ublock-quick-fixes: 394-0, 2h.2m
    adguard-mobile: 8145-149, 1d.4h.43m
    easylist: 62001-780, 1d.4h.43m
    easyprivacy: 30765-1722, 1d.4h.43m
    urlhaus-1: 9537-0, 2h.1m
    plowe-0: 3675-3, 1d.4h.42m
    POL-0: 7865-30, 2h
    POL-2: 1279-13, 1d.4h.42m
filterset (user): [array of 72 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: 
  popupPanelLockedSections: 32
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 824 ms (selfie)
  maxAssetCacheWait: 1292 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    tube8.com: 7
    etahub.com: 6
    google-analytics.com: 1
    googletagmanager.com: 1
    trafficjunky.com: 2
    trafficjunky.net: 5
```
</details>

**Comment by Trouble-bubbles** [comment]
https://github.com/easylist/easylist/issues/13826

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3a8cb7aa6c66d8c2336ce4e591b5295aab570282
