### ISSUE TITLE
[nsfw] pornhub.com: detection

### ISSUE THREAD

**Issue by AlreadyThereForOne** [uBlockOrigin/uAssets#15324]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pornhub.com/view_video.php?viewkey=ph632c79b450c5d`

### Category

detection

### Describe the issue

Black overlay over video content, unable to review with element tool.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/LD5Z6XK
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86464
  cosmetic: 38676
  scriptlet: 18124
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61950-54, 21h.44m
    easyprivacy: 30731-1170, 21h.43m
    plowe-0: 3675-865, 1d.20h.59m
    ublock-abuse: 76-0, 4d.19h.5m
    ublock-badware: 4369-106, 3d.21h.49m
    ublock-filters: 33077-109, 3d.21h.48m
    ublock-privacy: 256-1, 4d.19h.4m
    ublock-quick-fixes: 391-10, 2h.36m
    ublock-unbreak: 1870-42, 3d.21h.47m
    urlhaus-1: 9383-0, 2h.37m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 169 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    pornhub.com: 6
    etahub.com: 4
    google-analytics.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    trafficjunky.com: 2
```
</details>

**Comment by InjectOH4** [comment]
Following the prereq fixed it for me. forced an update of my filter lists then click "Update now" and purged cache.

**Comment by krystian3w** [comment]
#15325

**Comment by mapx-** [comment]
update all the lists, maybe it was an easylist issue
