### ISSUE TITLE
[nsfw] fr.pornhub.com: breakage

### ISSUE THREAD

**Issue by Duurzo** [uBlockOrigin/uAssets#15325]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fr.pornhub.com/`
`https://fr.xvideos.com/`

### Category

breakage

### Describe the issue

With the new update. The "Video preview" aren't working on these websites.
Can you fix that ? thank you

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 107831
  cosmetic: 47710
  scriptlet: 18051
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 31182-23, 23h.50m
    easylist: 61950-79, 1d.10h.36m
    easyprivacy: 30731-1471, 19h.49m
    plowe-0: 3671-870, 7d.7h.10m
    ublock-abuse: 76-1, 6d.3h.8m
    ublock-badware: 4379-116, 1d.10h.35m
    ublock-filters: 33145-242, 23h.51m
    ublock-privacy: 256-1, 4d.21h.30m
    ublock-unbreak: 1875-42, 3h.47m
    urlhaus-1: 9383-0, 11h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 540 ms (selfie)
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    pornhub.com: 4
    google-analytics.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    phncdn.com: 1
    trafficjunky.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`xvideos.com#@#video[autoplay]`

for pornhub all fine on my end
@ryanbr

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15324
