### ISSUE TITLE
Add Wikia's featured videos to the 'Annoyances' filter

### ISSUE THREAD

**Issue by jaydenkieran** [uBlockOrigin/uAssets#1532]
### URL(s) where the issue occurs

- http://yugioh.wikia.com/wiki/Yu-Gi-Oh!_VRAINS
- http://runescape.wikia.com/wiki/Money_making_guide

### Describe the issue

Wikia/FANDOM have introduced some pretty annoying autoplaying videos at the top of their wiki articles in order to gain more ad revenue. While uBlock blocks the pre-roll ads already, it is pretty annoying to have these videos start playing on wiki pages, and they continuously cycle to unrelated videos when they finish.

As the videos are injected by Wikia rather than the maintainers of each wiki, the information is usually grossly inaccurate and low-effort, and nobody reading a wiki article wants to see them. There have been numerous complaints about them since their introduction. I propose that a filter for them is added as part of uBlock's 'Annoyances' filter.

### Versions

- Browser/version: Chrome 64.0.3282.140
- uBlock Origin version: 1.15.2

### Notes

This should be easy enough to block by adding a new filter for

```
wikia.com##.featured-video__wrapper
```

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/760
