### ISSUE TITLE
[nsfw] asiaon.top: detection

### ISSUE THREAD

**Issue by LePistole-glitch** [uBlockOrigin/uAssets#15322]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://asiaon.top/`

### Category

detection

### Describe the issue

The page in question detects ublock origin and none of the content can be displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 642199
  cosmetic: 60973
  scriptlet: 19149
  html: 787
listset (total-discarded, last updated): 
  added: 
    https://abp.oisd.nl/: 484355-0, 16h.39m
    https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/adblock.txt: 57407-41863, 22h.27m
    adguard-spyware: 31580-5962, 22h.30m
    adguard-spyware-url: 791-3, 22h.31m
    block-lan: 44-0, 6d.17h.2m
    curben-phishing: 92037-45267, 16h.41m
    curben-pup: 193-106, 16h.40m
    fanboy-thirdparty_social: 69-0, 2d.1h.44m
    dpollock-0: 11389-5258, 6d.23h.45m
    CHN-0: 28888-7682, 22h.32m
    JPN-1: 7991-151, 22h.22m
    spa-0: 3304-4, 16h.43m
    spa-1: 4722-163, 22h.26m
  default: 
    user-filters: 3-1, never
    ublock-filters: 33873-430, 22h.29m
    ublock-badware: 4383-457, 22h.28m
    ublock-privacy: 281-30, 3d.2h.59m
    ublock-abuse: 76-3, 3d.2h.58m
    ublock-unbreak: 1883-2, 3d.20h.37m
    ublock-quick-fixes: 392-0, 16h.38m
    easylist: 62527-16745, 6d.23h.44m
    easyprivacy: 30709-15988, 6d.23h.42m
    urlhaus-1: 9520-3596, 16h.37m
    plowe-0: 3675-3104, 3d.2h.57m
filterset (user): [array of 69 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    asiaon.top: 2
    google.com: 3
    googletagmanager.com: 1
    realsrv.com: 13
    scubaenterdane.com: 2
    tsyndicate.com: 7
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default setup, don't add any other list, disable other blocking addons (or host blocking file)
test again

**Comment by LePistole-glitch** [comment]
The solution worked for me, thank you very much.
