### ISSUE TITLE
hacksnation.com: detection

### ISSUE THREAD

**Issue by venkat2305** [uBlockOrigin/uAssets#15337]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://hacksnation.com/`

### Describe the issue

it detected the ublock and doesnt show the website
![image](https://user-images.githubusercontent.com/55329452/196783966-740d5405-133a-472e-b8c7-8bf9258d1d70.png)

### uBlock Origin version

1.44.4

### Browser name and version

microsoft edge 106.0.1370.47

### Settings

![image](https://user-images.githubusercontent.com/55329452/196784136-ff653ba6-327c-4180-beff-a2c092e0f66a.png)

![image](https://user-images.githubusercontent.com/55329452/196784204-de396576-bc99-4cd0-b0e3-1ac9253af937.png)

**Comment by mapx-** [comment]
It was fixed 6 hours ago.
Update all your lists.

**Comment by venkat2305** [comment]
> It was fixed 6 hours ago. Update all your lists.

it takes too long to browse between pages in the site with ubo on. with ubo off, the browsing between pages is faster. can you do something to fix this.

**Comment by mapx-** [comment]
I get no such behaviour.
Maybe you should keep ON only the default setup + uBlock filters annoyances

**Comment by venkat2305** [comment]
> I get no such behaviour. Maybe you should keep ON only the default setup + uBlock filters annoyances

tried it , but same issue. sometimes its taking way too long resulting in a timeout.

**Comment by venkat2305** [comment]
> I get no such behaviour. Maybe you should keep ON only the default setup + uBlock filters annoyances

can you check in Microsoft edge, it seem fine in firefox

**Comment by gwarser** [comment]
5-10s delay before thread is loaded, but happens with uBO completely disabled.
