### ISSUE TITLE
qrcode-tiger.com: ads

### ISSUE THREAD

**Issue by Vektor-537** [uBlockOrigin/uAssets#15331]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.qrcode-tiger.com/ru/how-to-use-qr-codes-in-your-powerpoint-presentation`

### Category

ads

### Describe the issue

no close ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://prnt.sc/AVp35zG_6wqJ
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 103727
  cosmetic: 60725
  scriptlet: 19355
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-thirdparty_social: 69-0, 4d.14h.47m
  default: 
    user-filters: 97-7, never
    RUS-0: 40490-10, 1d.3h.47m
    easylist: 61981-71, 1d.23h.54m
    easyprivacy: 30729-1288, 1d.23h.53m
    plowe-0: 3672-868, 12d.4h.10m
    ublock-abuse: 76-1, 2d.22h.40m
    ublock-badware: 4379-106, 1d.11h.52m
    ublock-filters: 33145-143, 1d.11h.51m
    ublock-privacy: 256-1, 4d.2h.44m
    ublock-quick-fixes: 389-22, 11h.45m
    ublock-unbreak: 1872-42, 1d.11h.50m
    urlhaus-1: 9383-0, 11h.44m
filterset (user): [array of 97 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 3116 ms (selfie)
  maxAssetCacheWait: 686 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  blockedDetails: 
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
- all those "ads" seem to be self-promotion ones
- @dimisa-RUAdList could confirm .. or not

**Comment by mapx-** [comment]
However, it's an international site.
Closing => self-promotion ads are not blocked.
