### ISSUE TITLE
instamojo.com => navigation bar broken

### ISSUE THREAD

**Issue by sahanabhatm** [uBlockOrigin/uAssets#15330]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.instamojo.com/`

### Describe the issue

Our website is `https://www.instamojo.com/`

Some of our users are reporting issues with interacting with the header navigation of our website. Our entire top navigation along with CTA buttons are being blocked when the extension is activated.

Our website doesn’t show any ads; we are a SaaS business like Shopify.

Can you please add our website to whitelist?

### Screenshot(s)

https://user-images.githubusercontent.com/93378596/196615874-2062fd3f-d980-4868-9e7d-7a5a1fc68a0b.jpg
https://user-images.githubusercontent.com/93378596/196615900-190f5c1f-854a-4e6c-802e-095eeb015252.png

### Notes

Tried adding the Ublock extension on chrome, upon clicking on instamojo.com navigation bar is not visible.

### Configuration

added the extension.

**Comment by mapx-** [comment]
add

`/mixpanel-*.js$badfilter`

@ryanbr

**Comment by okiehsch** [comment]
Or
`@@||instamojo.com/wp-content/*/mixpanel-integration/*$script,1p`
I don't think it is a "badfilter".

**Comment by mapx-** [comment]
maybe not entirely but I think that filter is too broad, however fanboy will review the issue

**Comment by mapx-** [comment]
The "bad" filter was removed, it should work now

**Comment by sahanabhatm** [comment]
Hi,

Still we can see the same issue, upon adding ublock origin extension navigation bar is broken

**Comment by mapx-** [comment]
just update the filter lists

(how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

**Comment by sahanabhatm** [comment]
how we can inform our users, to do all these things?

we need to have some default methods, it should start working

**Comment by mapx-** [comment]
> in 4-5 days the lists will be automatically updated
