### ISSUE TITLE
unilad.com: detection

### ISSUE THREAD

**Issue by robwilkie** [uBlockOrigin/uAssets#15332]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.unilad.com/viral/woman-somehow-makes-her-entire-stomach-disappear-in-baffling-video/?source=facebookstories&fbclid=IwAR2JEuqg9xTHDw1y5nbaFNdxvQRw852by4GzVotmLAU8Rw-HMO9p_1mGHjo`

### Category

detection

### Describe the issue

uBlock detected on the video - "Please turn off your ad blocking software to view this video"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/52244642/196677295-13c5e9e0-95c7-49f2-9783-6dada18977a9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 86657
  cosmetic: 38657
  scriptlet: 18146
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62001-53, 23h.53m
    easyprivacy: 30729-1170, 23h.52m
    plowe-0: 3675-865, 2d.3h.40m
    ublock-abuse: 76-0, 2d.3h.43m
    ublock-badware: 4379-106, 1d.3h.56m
    ublock-filters: 33086-110, 1d.3h.55m
    ublock-privacy: 256-1, 2d.3h.42m
    ublock-quick-fixes: 389-22, 23h.51m
    ublock-unbreak: 1875-42, 1d.3h.54m
    urlhaus-1: 9520-0, 23h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1454 ms (selfie)
  maxAssetCacheWait: 743 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    ay.delivery: 1
    byteoversea.com: 4
    chartbeat.com: 1
    connatix.com: 2
    dotmetrics.net: 1
    doubleclick.net: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    instagram.com: 15
    outbrain.com: 1
    permutive.com: 1
    quantserve.com: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
    tiktok.com: 14
```
</details>

**Comment by mapx-** [comment]
add

```
@@||micro.rubiconproject.com/prebid/dynamic/$script,domain=unilad.com
@@||static.adsafeprotected.com/vans-adapter-google-ima.js$script,domain=unilad.com
```

**Comment by mapx-** [comment]
@ryanbr
