### ISSUE TITLE
corriere.it: nuisance

### ISSUE THREAD

**Issue by xlollomanx** [uBlockOrigin/uAssets#15336]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.corriere.it/`

### Category

nuisance

### Describe the issue

When the site is opened it display a very annoying cookie banner. Thank you

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![immagine](https://user-images.githubusercontent.com/6764804/196725985-3925a984-5506-4f37-a41b-307df116b18f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 281403
  cosmetic: 216872
  scriptlet: 38330
  html: 810
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts: 164491-20171, 22h.15m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 22h.15m
    adguard-generic: 64105-5248, 22h.15m
    adguard-spyware: 31593-13524, 22h.15m
    adguard-annoyance: 59861-5166, 22h.15m
    adguard-social: 18503-28, 22h.15m
    fanboy-thirdparty_social: 69-0, 22h.15m
    fanboy-annoyance: 81376-43039, 22h.15m
    fanboy-cookiemonster: 41777-150, 22h.15m
    ublock-annoyances: 4874-4, 22h.15m
  default: 
    user-filters: 56-0, never
    ublock-filters: 33846-70, 22h.16m
    ublock-badware: 4383-0, 22h.16m
    ublock-privacy: 282-0, 22h.15m
    ublock-abuse: 76-4, 22h.15m
    ublock-unbreak: 1888-0, 22h.15m
    ublock-quick-fixes: 394-0, 22h.15m
    easylist: 62052-668, 22h.15m
    easyprivacy: 30764-2030, 22h.15m
    urlhaus-1: 9383-0, 22h.15m
    plowe-0: 3675-4, 22h.15m
    ITA-0: 13223-1, 22h.15m
filterset (user): [array of 52 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 1107 ms
  maxAssetCacheWait: 681 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    corriere.it: 2
    amazon-adsystem.com: 1
    aswpsdkeu.com: 1
    chartbeat.com: 1
    corriereobjects.it: 3
    doubleclick.net: 1
    imasdk.googleapis.com: 1
    imrworldwide.com: 2
    rcs.it: 2
    rcsobjects.it: 1
    tinypass.com: 1
```
</details>

**Comment by mapx-** [comment]
already fixed using `AdGuard Annoyances`

Try using the default setup + AdGuard Annoyances
