### ISSUE TITLE
atozmath.com: detection

### ISSUE THREAD

**Issue by KyceAbdallah** [uBlockOrigin/uAssets#15338]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://atozmath.com/Functions2.aspx?q=symmetry&q1=3x%5E2%2B12x-4%60%60symmetry&do=1`

### Category

detection

### Describe the issue

It detected ublock Origin 
https://user-images.githubusercontent.com/90739617/196804351-0dbea8d4-c68c-460a-a6b4-eb0adc7756a2.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 87162
  cosmetic: 38668
  scriptlet: 18162
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61938-53, 5h.58m
    easyprivacy: 30774-1170, 5h.57m
    plowe-0: 3675-865, 5h.56m
    ublock-abuse: 76-0, 5h.28m
    ublock-badware: 4380-105, 5h.26m
    ublock-filters: 33123-112, 5h.25m
    ublock-privacy: 257-1, 5h.24m
    ublock-quick-fixes: 391-22, 5h.23m
    ublock-unbreak: 1875-42, 5h.22m
    urlhaus-1: 10031-0, 5h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2899 ms (selfie)
  maxAssetCacheWait: 1091 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    bhavanijewellery.in: 1
    google-analytics.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by okiehsch** [comment]
I can only reproduce if I disable `uBO-filters`.

**Comment by KyceAbdallah** [comment]
> I can't reproduce the issue. Check if you are using any:
> 
> * Custom filters,
> * Other extensions,
> * Browser's built-in blocker,
> * DNS blocking methods,
> * Blocking softwares outside browser,
> * OS' hosts file to block domains.

I'm not using anything custom

**Comment by KyceAbdallah** [comment]
> I can only reproduce if I disable `uBO-filters`.

All I did was go on that site, put in the equation, and then when I hit solve, what was shown in the screenshot appeared

**Comment by mapx-** [comment]
> chromium

if not chrome => did you disable the various shields, builtin blockers, prot4ection tracking (in brave, edge, vivaldi, opera etc) ?

**Comment by KyceAbdallah** [comment]
> > chromium
> 
> if not chrome => did you disable the various shields, builtin blockers, protection tracking (in brave, edge, vivaldi, opera etc) ?

I'm running ChromeOS on a chromebook

**Comment by KyceAbdallah** [comment]
> What browser are you using? Google Chrome?

Yes it's the only one you you can use on ChromeOS

**Comment by mapx-** [comment]
what requests are allowed / blocked => open the logger, select allowed / blocked items, repeat the steps to get the issue, post here a screenshot with such items

my logger:
![image](https://user-images.githubusercontent.com/10303732/196956186-895a237c-32e7-48ae-803f-da175b29ca9e.png)

**Comment by KyceAbdallah** [comment]
> what requests are allowed / blocked => open the logger, select allowed / blocked items, repeat the steps to get the issue, post here a screenshot with such items
> 
> my logger: ![image](https://user-images.githubusercontent.com/10303732/196956186-895a237c-32e7-48ae-803f-da175b29ca9e.png)

Sorry I forgot how to open the logger, how do you do it again?

**Comment by mapx-** [comment]
click uBO icon, then:
![image](https://user-images.githubusercontent.com/10303732/196962983-324a59ec-6a03-426b-80c4-bef9cf000791.png)

**Comment by KyceAbdallah** [comment]
> click uBO icon, then: ![image](https://user-images.githubusercontent.com/10303732/196962983-324a59ec-6a03-426b-80c4-bef9cf000791.png)

Thank you.
Here's a ss
![image](https://user-images.githubusercontent.com/90739617/196964078-5ecc6552-b5eb-45fb-91df-75618703fa31.png)

**Comment by mapx-** [comment]
Did you select only the images ?

**Comment by mapx-** [comment]
maybe you should:
- close / reopen chrome
- reset uBO to default setup
- test again

**Comment by KyceAbdallah** [comment]
> maybe you should:
> 
> * close / reopen chrome
> * reset uBO to default setup
> * test again

Still detects

**Comment by mapx-** [comment]
> Did you select only the images ?

see my screenshot => In yours I see no `+js` filters

**Comment by KyceAbdallah** [comment]
![image](https://user-images.githubusercontent.com/90739617/196977169-2602378f-b4f7-41ff-ab29-80e333ee18f8.png)
There you go. Sry for the mistake I'm still pretty new to GitHub

**Comment by mapx-** [comment]
Same ss, take a look at my ss and you'll see a lot of `+js` filters

for example 

![image](https://user-images.githubusercontent.com/10303732/196978082-4b6cd9ff-59b9-47e2-a29e-e283b5b03cf8.png)

**Comment by KyceAbdallah** [comment]
> Same ss, take a look at my ss and you'll see a lot of `+js` filters
> 
> for example
> 
> ![image](https://user-images.githubusercontent.com/10303732/196978082-4b6cd9ff-59b9-47e2-a29e-e283b5b03cf8.png)

Tbh I'm very confused. Here's the link for you to take a look for yourself
[](https://atozmath.com/Functions2.aspx?q=symmetry&q1=-2x%60%60symmetry&do=1)

**Comment by ghajini** [comment]
i can reproduce
firefox deskto stable, ubo dev

**STR=**
on going atozmath.com
try solving equations=> enter some=> click solve

now go bavk to homepage => try above procedure => solve=> antiadblock comes

may be after 2-3 tries it detects adblock....may be it is detecting cookies

**Comment by KyceAbdallah** [comment]
> i can reproduce firefox desktop stable, ubo dev
> 
> **STR=** on going **atozmath.com** try solving equations=> enter some=> click solve=> no antiadb
> 
> now go back to homepage => try above procedure => solve=> antiadblock comes
> 
> after 2-3 tries it detects adblock....may be it is detecting cookies

That is what happens

**Comment by okiehsch** [comment]
How about simply hiding it?
`atozmath.com###lblAdContent`

**Comment by KyceAbdallah** [comment]
> 

How would I do that? I'm still pretty new to GitHub and recently found out about uBlock Origin a few months ago

**Comment by stephenhawk8054** [comment]
> How about simply hiding it? `atozmath.com###lblAdContent`

Actually if the dectection happens, it means the solution won't be displayed, or it will show wrong solutions.

For example, with the old issue `https://github.com/uBlockOrigin/uAssets/issues/10815`, the solution won't display because of `##+js(no-xhr-if, /^/)`

---

@ghajini @KyceAbdallah Can you test these filters?

```adb
atozmath.com#@#+js(no-xhr-if, /^/)
atozmath.com##+js(no-xhr-if, /prebid|quantumdex|e-planning|criteo|aralego|rubicon|a-mx|id5-sync/)
@@||services.bilsyndication.com/cli/$xhr,domain=atozmath.com
@@||services.bilsyndication.com/vld/$xhr,domain=atozmath.com
@@||services.bilsyndication.com/obj/$xhr,domain=atozmath.com
```

You might need change to other VPNs to test as the site will always show anti-adblock for 24 hours after a few times detected if I remember correctly.

**Comment by ghajini** [comment]
still detects

**Comment by KyceAbdallah** [comment]
> > How about simply hiding it? `atozmath.com###lblAdContent`
> 
> Actually if the dectection happens, it means the solution won't be displayed, or it will show wrong solutions.
> 
> For example, with the old issue `https://github.com/uBlockOrigin/uAssets/issues/10815`, the solution won't display because of `##+js(no-xhr-if, /^/)`
> 
> @ghajini @KyceAbdallah Can you test these filters?
> 
> ```
> atozmath.com#@#+js(no-xhr-if, /^/)
> atozmath.com##+js(no-xhr-if, /prebid|quantumdex|e-planning|criteo|aralego|rubicon|a-mx|id5-sync/)
> @@||services.bilsyndication.com/cli/$xhr,domain=atozmath.com
> @@||services.bilsyndication.com/vld/$xhr,domain=atozmath.com
> @@||services.bilsyndication.com/obj/$xhr,domain=atozmath.com
> ```
> 
> You might need change to other VPNs to test as the site will always show anti-adblock for 24 hours after a few times detected if I remember correctly.

Yeah it still detects

**Comment by gorhill** [comment]
Clear cookies for the site and try:

    atozmath.com##+js(cookie-remover, BAdBlock1)

The warning is shown by the server when the cookie `BAdBlock1` is set to `1`.

**Comment by stephenhawk8054** [comment]
Can anyone else test

```adb
atozmath.com#@#+js(no-xhr-if, /^/)
atozmath.com##+js(no-xhr-if, /prebid|quantumdex|e-planning|criteo|aralego|rubicon|a-mx|id5-sync/)
@@||services.bilsyndication.com/passback/$script,domain=atozmath.com
@@||services.bilsyndication.com/cli/$xhr,domain=atozmath.com
@@||services.bilsyndication.com/obj/$xhr,domain=atozmath.com
@@||services.bilsyndication.com/vld/$xhr,domain=atozmath.com
```
I think the `passback` scripts need to be allowed. I followed the steps by @ghajini and anti-adblock does not appear any more for me.

**Comment by mapx-** [comment]
cookies, server side .. I guess it's not something fixable without massive whitelisting
maybe something on firefox if we'd have some replace scriptlet ?!

```
atozmath.com#@#+js()
@@*$xhr,script,domain=atozmath.com
*$frame,domain=atozmath.com,redirect-rule=noopframe
```

**Comment by KyceAbdallah** [comment]
> cookies, server side .. I guess it's not something fixable without massive whitelisting maybe something on firefox if we'd have some replace scriptlet ?!
> 
> ```
> atozmath.com#@#+js()
> @@*$xhr,script,domain=atozmath.com
> *$frame,domain=atozmath.com,redirect-rule=noopframe
> ```

I'm not using firefox though, I'm using google chrome on ChromeOS

**Comment by mapx-** [comment]
> I'm not using firefox though, I'm using google chrome on ChromeOS

it does not matter: just test those filters

**Comment by ghajini** [comment]
> cookies, server side .. I guess it's not something fixable without massive whitelisting maybe something on firefox if we'd have some replace scriptlet ?!
> 
> ```
> atozmath.com#@#+js()
> @@*$xhr,script,domain=atozmath.com
> *$frame,domain=atozmath.com,redirect-rule=noopframe
> ```

doesn't work,still detected
it's like allowing all ads(`@@*$xhr,script,domain=atozmath.com`)

not worthy,can workaround by clearing cookies

**Comment by ghajini** [comment]
> > can workaround by clearing cookies
> 
> So this works?
> ```adb
> atozmath.com##^responseheader(set-cookie)
> atozmath.com##+js(cookie-remover, /^/)
> ```

No

**Comment by gorhill** [comment]
I wanted to try the below filter yesterday nut I am no longer able to get any content from that site:

    atozmath.com##+js(cookie-remover, /BAdBlock\d+|BAdSvi\d+/)

**Comment by ghajini** [comment]
> but I am no longer able to get any content from that site:
  i didn't get

**Comment by KyceAbdallah** [comment]
> > I'm not using firefox though, I'm using google chrome on ChromeOS
> 
> it does not matter: just test those filters

Yeah it still detects with these filters:
Apply changes
 
Revert
   
Import and append
 
Export

1
atozmath.com#@#+js(no-xhr-if, /^/)
2
atozmath.com##+js(no-xhr-if, /prebid|quantumdex|e-planning|criteo|aralego|rubicon|a-mx|id5-sync/)
3
@@||services.bilsyndication.com/cli/$xhr,domain=atozmath.com
4
@@||services.bilsyndication.com/vld/$xhr,domain=atozmath.com
5
@@||services.bilsyndication.com/obj/$xhr,domain=atozmath.com
6
​
7
​

**Comment by stephenhawk8054** [comment]
> > but I am no longer able to get any content from that site:
> 
> i didn't get what you just said still get detected on 2nd try

I think he's got IP banned from that site (when getting anti adb too many times).

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15338#issuecomment-1285503818

Possible install Firefox Mobile from APK file or Play Store if official latest version have.

Also possible in same way install Opera but not tested install add-on in this creature: https://www.opera.com/pl/browsers/opera-for-chromebook (so have only fancy interface like form tablets).

**Comment by JobcenterTycoon** [comment]
Try

```
atozmath.com#@#+js()
@@||bhavanijewellery.in^$image,domain=atozmath.com
@@||assets.bilsyndication.com/plugins/cmptcf2/cmp-v2.0.1.js$script,domain=atozmath.com
@@||services.bilsyndication.com/passback/?t=$script,domain=atozmath.com
@@||services.bilsyndication.com^$xhr,domain=atozmath.com
atozmath.com###vi-smartbanner
atozmath.com##.adsbyvli:style(opacity: 0 !important; pointer-events: none !important;)
```

**Comment by JobcenterTycoon** [comment]
@mapx- does the solution works for you?

**Comment by mapx-** [comment]
It seems working now .. @ghajini could you test too ?

**Comment by ghajini** [comment]
yes it did worked now

**Comment by JobcenterTycoon** [comment]
Works fine for me. Its important to accept the privacy banner first before clicking on `find` because the script checking if the user accepted the privacy banner.

**Comment by krystian3w** [comment]
@kiboke you have draft of accept mechanism instead hide elements or blocking resources: https://github.com/uBlockOrigin/uAssets/issues/15338#issuecomment-1451835048

![image](https://user-images.githubusercontent.com/35370833/222437061-4adbf3a8-ea51-4d10-a035-b83d1d57f917.png) | specific filter hiding still exist
 --- | ---


I don't know how this works with EasyList Cookie even use Fanboy hosting.

**Comment by kiboke** [comment]
@krystian3w I'm not sure what you're asking :)

**Comment by krystian3w** [comment]
I mean page may need accept top bar "consent frame" by set cookie/local storage or click (instead hide).

Similar accept on page may need modal pop-up loaded by "quantcast.mgr.consensu.org" (instead network block as fast possible).

---

To reproduce whether IDCAC itself is considered enabled ad-blocking may require ordering a dozen calculations in this calculator.

If you decide that it's not worth fixing it, tough.
