### ISSUE TITLE
cut4links.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#1533]
### URL(s) where the issue occurs

`https://cut4links.com/6So8`

### Describe the issue

Please skip the timer..

**Comment by SkeletalDemise** [comment]
This site also has anti-adblock. 
![cut4links com anti-adblock](https://user-images.githubusercontent.com/29117662/36141849-23096028-105b-11e8-833c-fbe015977046.PNG)

**Comment by mapx-** [comment]
well, strange, I cannot reproduce in uBo, however I added a specific filter
(you are using nano, could be some differences..)

**Comment by SkeletalDemise** [comment]
I can't reproduce it much either. It displays it sometimes but a lot of times not.

**Comment by version365** [comment]
I can't see any anti-adblock in Nano either..

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Block ad Block.

**Comment by SMed79** [comment]
@okiehsch https://forums.lanik.us/viewtopic.php?p=135678#p135678

**Comment by IThinkIAmCool** [comment]
Inactive?

**Comment by IThinkIAmCool** [comment]
@mapx- @uBlock-user Is cutlinks.com offline?
