### ISSUE TITLE
v.qq.com: popups

### ISSUE THREAD

**Issue by a604681786** [uBlockOrigin/uAssets#15346]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://v.qq.com/x/cover/mzc002002064ykw/s0044iubpgh.html`

### Category

popups

### Describe the issue

腾讯视频网页，拦截后不能正常显示播放视频！
![ZSI6T6MJH{CRE%ZH{4(J@9J](https://user-images.githubusercontent.com/70795478/196896426-6132b9db-424e-4209-b1f2-0070281f263d.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 105703
  cosmetic: 48836
  scriptlet: 18268
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-1, never
    CHN-0: 28933-86, 3d.2h.31m
    easylist: 62001-91, 1d.3h.16m
    easyprivacy: 30773-1193, 1d.3h.15m
    plowe-0: 3671-864, 9d.6h.29m
    ublock-abuse: 76-0, 9d.22h.20m
    ublock-badware: 4369-106, 3d.2h.30m
    ublock-filters: 33123-128, 3d.2h.29m
    ublock-privacy: 255-1, 9d.22h.19m
    ublock-quick-fixes: 391-22, 7h.14m
    ublock-unbreak: 1872-43, 3d.2h.28m
    urlhaus-1: 10031-0, 7h.13m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 412 ms (selfie)
  maxAssetCacheWait: 247 ms
popupPanel: 
  blocked: 283
  blockedDetails: 
    qq.com: 282
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
很抱歉，由于版权限制，您所在的地区暂时无法播放该视频
(Sorry, this video is temporarily unavailable in your region due to copyright restrictions)

maybe @cjx82630 could help
