### ISSUE TITLE
in.tradingview.com: nuisance

### ISSUE THREAD

**Issue by AtharvaChavan** [uBlockOrigin/uAssets#15342]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://in.tradingview.com/chart/`

### Category

nuisance

### Describe the issue

Able to see 30 days free trial at bottom left of the screen
Req. to block that

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/35627981/196853801-27cac912-6322-4cd8-8868-acd1da94047c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 86614
  cosmetic: 38740
  scriptlet: 18140
  html: 787
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 33853-43, 3d.14h.40m
    ublock-badware: 4373-0, 3d.14h.39m
    ublock-privacy: 282-0, 2d.18h.53m
    ublock-abuse: 76-0, 3d.10h.38m
    ublock-unbreak: 1885-0, 2d.22h.54m
    ublock-quick-fixes: 394-0, 16h.21m
    easylist: 61991-607, 3d.14h.41m
    easyprivacy: 30731-1707, 3d.10h.37m
    urlhaus-1: 9537-0, 17h.17m
    plowe-0: 3675-3, 1d.21h.27m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 35 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 229 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    tradingview.com: 33
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
We do not address self-promotion stuff

add

`in.tradingview.com##[class^="toast"]`
