### ISSUE TITLE
canva.com: ads cookies

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15349]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.canva.com/download/windows/`

### Category

ads

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/196940354-a0088b58-cf74-4e08-973d-0cff1dd91214.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/196940363-7dea0308-1768-4fce-93a1-cf515dabe235.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 108
filterset (summary): 
  network: 103853
  cosmetic: 116575
  scriptlet: 24774
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 8158-3, 4d.4h
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 4h.56m
    adguard-spyware: 33710-1946, 4h.45m
    fanboy-annoyance: 81268-255, 4d.4h.2m
    fanboy-cookiemonster: 41360-41329, 7d.13m
    ublock-annoyances: 4852-75, 4h.54m
  default: 
    user-filters: 14-0, never
    easylist: 62001-93, 21h.55m
    easyprivacy: 30763-12620, 21h.52m
    ublock-abuse: 76-0, 7d.24m
    ublock-badware: 4389-104, 4h.52m
    ublock-filters: 33102-429, 4h.49m
    ublock-privacy: 256-47, 7d.22m
    ublock-quick-fixes: 391-22, 21h.50m
    ublock-unbreak: 1875-59, 4h.47m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 1159 ms (selfie)
  maxAssetCacheWait: 519 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
it's fixed by another cookie list => `AdGuard Annoyances`

enable it or add only these filters:

```
canva.com##div[style="z-index: 1;"] div[aria-live="polite"]:not([role])
canva.com##body:style(overflow: auto !important;)
```

@ryanbr
