### ISSUE TITLE
rocketnews24.com: detection

### ISSUE THREAD

**Issue by micachi** [uBlockOrigin/uAssets#15341]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rocketnews24.com/2022/10/20/1704276/`

### Category

detection

### Describe the issue

If an ad block is detected, the image will not be displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/78028453/196836460-27c2d00c-3946-4b2c-a4ba-94353c639add.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88264
  cosmetic: 45292
  scriptlet: 18244
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    JPN-1: 7976-10, 3d.13h.9m
    easylist: 61938-90, 8h.53m
    easyprivacy: 30711-1195, 6d.18h.40m
    plowe-0: 3675-869, 4d.13h.13m
    ublock-abuse: 76-0, 10d.19h.26m
    ublock-badware: 4369-105, 3d.13h.10m
    ublock-filters: 33115-117, 3d.13h.12m
    ublock-privacy: 250-1, 10d.19h.25m
    ublock-quick-fixes: 391-10, 8h.52m
    ublock-unbreak: 1872-50, 3d.13h.11m
    urlhaus-1: 10031-0, 8h.51m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1298 ms (selfie)
  maxAssetCacheWait: 744 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    rocketnews24.com: 3
    amazon-adsystem.com: 1
    criteo.net: 1
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
    parsely.com: 1
    twitter.com: 2
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
update the regional list JPN, working fine on my end

**Comment by dportvine** [comment]
> If an ad block is detected, the image will not be displayed.

Rule for me:
```adb
||fundingchoicesmessages.google.com^
```

<details>
<summary>Screen</summary>

![2022-10-20_153826](https://user-images.githubusercontent.com/111344219/196957371-63251c74-7268-4988-bffd-3676203e3a58.png)
![2022-10-20_153826](https://user-images.githubusercontent.com/111344219/196952492-680c105f-4764-428a-bb30-0c0d01617fcb.png)
![2022-10-20_154107](https://user-images.githubusercontent.com/111344219/196952514-827c2208-5da1-46c8-9012-7631d2938044.png)
</details>

if i add this exception the image will be displayed
```adb
@@||fundingchoicesmessages.google.com/i/pub-*$script,domain=rocketnews24.com
```

<details>
<summary>Screen</summary>

![2022-10-20_153826](https://user-images.githubusercontent.com/111344219/196954981-e38123af-8289-4321-a4b8-0411dab4a97f.png)
</details>

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 101419
  cosmetic: 132495
  scriptlet: 24524
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31460-27, 10m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1524-24, 10m
    JPN-1: 8048-11, now
    fanboy-cookiemonster: 41865-286, 10m
    ublock-annoyances: 4852-53, 10m
  default: 
    user-filters: 7-0, never
    RUS-0: 40510-147, 11m
    easylist: 62003-123, 10m
    easyprivacy: 30781-1615, 10m
    ublock-abuse: 76-1, 10m
    ublock-badware: 4394-103, 10m
    ublock-filters: 33127-176, 10m
    ublock-privacy: 257-8, 10m
    ublock-quick-fixes: 401-22, 10m
    ublock-unbreak: 1876-53, 10m
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 904 ms (selfie)
  maxAssetCacheWait: 868 ms
```
</details>

**Comment by mapx-** [comment]
hmm, right, for firefox I need also:

`@@||cdn.parsely.com/keys/rocketnews24.com$script,domain=rocketnews24.com`

**Comment by mapx-** [comment]
@Yuki2718

**Comment by mapx-** [comment]
@MasterKia did you enable JPN list ?

**Comment by Yuki2718** [comment]
No need for exception, redirecting to noop.js works fine.

**Comment by micachi** [comment]
Fixed! Thank you!

**Comment by Yuki2718** [comment]
They countered, maybe the start of just another attrition war.
