### ISSUE TITLE
exxen.com: detection

### ISSUE THREAD

**Issue by ErdiCan0** [uBlockOrigin/uAssets#15345]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.exxen.com/tr/watch-serie/`

### Category

detection

### Describe the issue

ad blocker detected
disable to view content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88741
  cosmetic: 45754
  scriptlet: 19019
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 9562-9, 7h.43m
    easylist: 61938-70, 7h.40m
    easyprivacy: 30774-1175, 7h.39m
    plowe-0: 3675-866, 7h.38m
    ublock-abuse: 76-0, 7h.36m
    ublock-badware: 4380-105, 7h.34m
    ublock-filters: 33126-123, 7h.33m
    ublock-privacy: 257-1, 7h.32m
    ublock-quick-fixes: 391-22, 7h.31m
    ublock-unbreak: 1875-42, 7h.30m
    urlhaus-1: 10031-0, 7h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1647 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    criteo.com: 1
    doubleclick.net: 1
    facebook.net: 1
    googletagmanager.com: 1
    tiktok.com: 1
```
</details>

**Comment by mapx-** [comment]
> Sign up now and start watching from exxen.com, Google Play, AppGallery, App Store, Apple TV and Android TV on mobile, tablet, computer, anytime, anywhere.

do we need a paid subscription ?
