### ISSUE TITLE
[nsfw] cloudwise-portal.appspot.com: privacy

### ISSUE THREAD

**Issue by AreYouOkzy** [uBlockOrigin/uAssets#15347]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cloudwise-portal.appspot.com/`

### Category

privacy

### Describe the issue

The admin can watch me, I want my privacy. I tried to block everything on the site but the admin could still watch my screen. I expected that if I would block it that the admin wouldn't have access anymore wich isn't the case.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 88107
  cosmetic: 40344
  scriptlet: 18178
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-1, never
    NLD-0: 2472-12, now
    easylist: 62003-56, now
    easyprivacy: 30781-1171, now
    plowe-0: 3675-865, 2m
    ublock-abuse: 76-0, now
    ublock-badware: 4389-105, now
    ublock-filters: 33127-144, now
    ublock-privacy: 257-1, 1m
    ublock-quick-fixes: 392-22, now
    ublock-unbreak: 1875-56, now
    urlhaus-1: 10162-0, now
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4292 ms (selfie)
  maxAssetCacheWait: 1296 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-scripting: true
  blockedDetails: 
    cloudwise-portal.appspot.com: 1
    fontawesome.com: 1
```
</details>

**Comment by mapx-** [comment]
it seems to be a learning platform, so it's normal the teacher / admin could manage every single (learning) station
