### ISSUE TITLE
baking-forums.com: ad leftovers

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15340]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.baking-forums.com/threads/forum-upgrade.5931/`

### Describe the issue

Blank posts labled "advertisements" remain on the page

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 87205
  cosmetic: 38916
  scriptlet: 18157
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33866-55, now
    ublock-badware: 4393-0, now
    ublock-privacy: 282-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1888-0, now
    ublock-quick-fixes: 394-0, now
    easylist: 62140-604, now
    easyprivacy: 30718-1705, now
    urlhaus-1: 10162-0, now
    plowe-0: 3675-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1663 ms
  maxAssetCacheWait: 162 ms
```
</details>

**Comment by okiehsch** [comment]
`baking-forums.com##div.message--post.message:has-text(Advertisements)`

**Comment by mapx-** [comment]
maintainer notified
