### ISSUE TITLE
nextdoor.com: ads

### ISSUE THREAD

**Issue by svan71** [uBlockOrigin/uAssets#15343]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nextdoor.com/news_feed/`

### Describe the issue

Can not block the ad.  I don't want to share my election day plans and don't want 25% of my screen used to get me to supply it.

### Screenshot(s)

<img width="1514" alt="Screen Shot 2022-10-20 at 12 57 17 AM" src="https://user-images.githubusercontent.com/48870638/196860161-c519c73a-cf29-408a-847a-c5f23d9742be.png">

### uBlock Origin version

uBlock Origin: 1.44.4

### Browser name and version

Firefox: 106

### Settings

none

**Comment by mapx-** [comment]
- is "share your plan" just a "feature" of `nextdoor` site ? => in this case is self-promotion and we don't address such stuff
- use the element picker to block / hide such element
