### ISSUE TITLE
[nsfw] hanime1.me: ads

### ISSUE THREAD

**Issue by loveqianool** [uBlockOrigin/uAssets#15356]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [x] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hanime1.me/watch?v=400589`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![屏幕截图 2022-10-21 031151](https://user-images.githubusercontent.com/739497/197037221-b79f50be-cfcc-42d4-8c48-3addd20bfd8d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 92947
  cosmetic: 48801
  scriptlet: 18284
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://github.com/easylist/easylistchina/raw/master/easylistchina.txt: 26501-6, 1d.4h.3m
  default: 
    user-filters: 0-0, never
    CHN-0: 28919-26547, 1d.4h.2m
    easylist: 61950-92, 3d.14h.48m
    easyprivacy: 30774-1194, 1d.11h.58m
    ublock-abuse: 76-0, 3d.6h.38m
    ublock-badware: 4380-104, 1d.4h.4m
    ublock-filters: 33123-128, 1d.4h.5m
    ublock-privacy: 256-0, 5d.4h.26m
    ublock-quick-fixes: 391-22, 1d.4h.1m
    ublock-unbreak: 1875-43, 1d.4h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 771 ms (selfie)
  maxAssetCacheWait: 298 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    addthis.com: 1
    googletagmanager.com: 1
    impactserving.com: 1
    jads.co: 3
    realsrv.com: 7
```
</details>

**Comment by mapx-** [comment]
Where are the ads ?

Did you try reporting at Easylist China ? https://github.com/easylist/easylistchina/issues

**Comment by gorhill** [comment]
Google Translate translates the text as "Sponsor us (●´∀｀)ノ♡", so it's just self-promotion.
