### ISSUE TITLE
adstream.com / adstream.com.ro

### ISSUE THREAD

**Issue by laurlau** [uBlockOrigin/uAssets#1535]
### URL(s) where the issue occurs

`http://adstream.com/`   
`https://adstream.com.ro`

### Describe the issue

uBlock Origin has prevented the following page from loading:

http://adstream.com/

Because of the following filter

/adstream.

Found in: EasyList

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/36441600/36145686-cb5adb08-10ba-11e8-87e5-96451dd3be55.PNG)

### Versions

- Browser/version: GoogleChrome Version 64.0.3282.140 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.15.2

### Settings

- default

### Notes

-

**Comment by mapx-** [comment]
@ryanbr

**Comment by laurlau** [comment]
hello.
Getting back to you.
same issue on https://ads.adstream.com.ro
Could you please the *.adstream.com.ro to your whitelist?
Thank you,
Laurentiu
![image](https://user-images.githubusercontent.com/36441600/36946322-eafe3780-1fc3-11e8-9250-98359676b611.png)

**Comment by mapx-** [comment]
@ryanbr

**Comment by laurlau** [comment]
hello.
any update on this?

**Comment by gorhill** [comment]
Why not just disable strict blocking for that site? Given the nature of the site, it's preferable than to just add yet another exception in the existing filter -- the uBO's warning page is not a showstopper, it's easy to proceed forward by dismissing the block temporarily or permanently.

**Comment by mapx-** [comment]
You should report the issue with easylist guys (otherwise only the uBo users will be able to use that site)
https://github.com/easylist/easylist/issues

However the last page seems to be a private one (`https://ads.adstream.com.ro/admin/login`) so you could just whitelist it for private use (waiting for easylist guys)

**Comment by laurlau** [comment]
Thanks for the info. I will report the issue to easylist.
As for disable the strict blocking to that site, it's easy for me. But when you work with hundreds of thousand of people who only install an ad block extension and that's it, it's pretty hard to explain to each and every one of them how to do stuff with that extension...

**Comment by gorhill** [comment]
> it's pretty hard to explain to each and every one of them how to do stuff with that extension...

The instructions to disable strict-blocking are right there in the page.
