### ISSUE TITLE
fmovies.to: detection

### ISSUE THREAD

**Issue by narbhar** [uBlockOrigin/uAssets#15358]
> - [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
> - [ ] I did not answer truthfully to **all** the above checkpoints

> I use ghostery and privacy badger in conjunction with ublock but they have been disabled for fmovies with just ublock operating on it. Microsoft Edge built in tracking protection has been disabled for this website as well
>

you need to disable ghostery from  extensions menu,report to them what is happening even if site is whitelisted in ghostery

=> you are advised to only use ublock origin(or only 1 content blocker at a time)

**Comment by ghajini** [comment]
you need to disable ghostery from extensions menu,report to them what is happening even if site is whitelisted in ghostery

=> you are advised to only use ublock origin(or only 1 content blocker at a time)

**Comment by narbhar** [comment]
Thanks, that seems to be the issue. Ghostery is the culprit. Even when the site is set to be trusted it is doing to something to trigger the detection. PSA: this seems to be happening with the new version of Ghostery 8.9.2, whereas an older version of the extension 8.7.6 doesn't seem to be causing the issue, I verified this on firefox
