### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by uzair-patel** [uBlockOrigin/uAssets#15355]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/castro_1021`

### Category

ads

### Describe the issue

ads coming up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87079
  cosmetic: 38699
  scriptlet: 18139
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61938-53, 21h.53m
    easyprivacy: 30715-1170, 6d.22h.1m
    plowe-0: 3671-862, 9d.1h.49m
    ublock-abuse: 76-0, 9d.1h.51m
    ublock-badware: 4389-105, 7h
    ublock-filters: 33100-110, 4d.5h.16m
    ublock-privacy: 257-1, 6h.59m
    ublock-quick-fixes: 377-10, 13h.15m
    ublock-unbreak: 1872-42, 4d.9h.19m
    urlhaus-1: 10031-0, 1d.1h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 335 ms (selfie)
  maxAssetCacheWait: 460 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    twitch.tv: 9
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 15
    doubleverify.com: 2
    imrworldwide.com: 2
    scorecardresearch.com: 2
    sentry.io: 13
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
