### ISSUE TITLE
filepress.online: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#15350]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://filepress.online/file/635123bdc43eb5c89f59a5c7`

### Category

nuisance

### Describe the issue

Click Direct Download>15 Seconds Timer

Boost That+ If Possible Then Appears Download Button It Has A Little Delay Boost That Too

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 108
filterset (summary): 
  network: 88989
  cosmetic: 29806
  scriptlet: 21531
  html: 812
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4898-8, 15h.53m
  default: 
    user-filters: 967-20, never
    ublock-filters: 33971-339, 15h.53m
    ublock-badware: 4383-0, 15h.53m
    ublock-privacy: 282-1, 15h.53m
    ublock-abuse: 76-0, 15h.53m
    ublock-unbreak: 1893-0, 15h.53m
    ublock-quick-fixes: 394-0, 15h.53m
    adguard-mobile: 8149-171, 15h.53m
    easylist: 62002-17941, 15h.53m
    easyprivacy: 30777-1717, 15h.53m
    urlhaus-1: 10031-0, 15h.53m
    plowe-0: 3675-3, 15h.52m
filterset (user): [array of 930 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1447 ms
  maxAssetCacheWait: 407 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
I see nothing we could do here, if you want to try debugging it => 
https://filepress.online/static/js/main.fcc386eb.js

search for time-wrapper or remainingTime

**Comment by mapx-** [comment]
Exactly
