### ISSUE TITLE
exee.app: detection

### ISSUE THREAD

**Issue by lKerriganl** [uBlockOrigin/uAssets#15353]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://exee.app/PVsZGardenWarfare`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89640
  cosmetic: 43541
  scriptlet: 18232
  html: 777
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33842-76, 1d.2h.25m
    ublock-badware: 4384-0, 1d.2h.24m
    ublock-privacy: 274-0, 9d.18h.19m
    ublock-abuse: 76-0, 9d.18h.18m
    ublock-unbreak: 1888-0, 1d.2h.29m
    easylist: 61938-658, 1d.2h.23m
    easyprivacy: 30774-1721, 1d.2h.22m
    urlhaus-1: 10031-0, 1d.2h.27m
    plowe-0: 3671-3, 9d.18h.20m
    spa-0: 3306-1, 1d.2h.28m
    spa-1: 4732-110, 1d.2h.26m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 514 ms (selfie)
  maxAssetCacheWait: 258 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cdntechone.com: 1
    eshouloo.net: 4
    googletagmanager.com: 1
    taghaugh.com: 2
```
</details>

**Comment by lKerriganl** [comment]
detection

**Comment by okiehsch** [comment]
`exee.app##+js(acs, globalThis, break;case)`

**Comment by gorhill** [comment]
The only way I could reproduce detection is by enabling ABP. Given user stated he did not truthfully answer the question, let's assume he did not answer truthfully for _"I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)"_.
