### ISSUE TITLE
nexusmods.com: detection and timer

### ISSUE THREAD

**Issue by frankenzombies** [uBlockOrigin/uAssets#15365]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nexusmods.com/cyberpunk2077`

### Category

detection

### Describe the issue

At the top of the site, it says no one likes ads and pleads for a premium membership to be bought so the message will disappear and ads will be permanently removed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[](https://imgur.com/a/GGeL8z9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 102
filterset (summary): 
  network: 86468
  cosmetic: 38674
  scriptlet: 18149
  html: 789
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33823-54, 3d.2h.48m
    ublock-badware: 4383-0, 3d.2h.49m
    ublock-privacy: 281-0, 4d.5h.39m
    ublock-abuse: 76-0, 4d.8h.32m
    ublock-unbreak: 1888-0, 3d.6h.50m
    easylist: 61962-606, 4d.8h.28m
    easyprivacy: 30731-1705, 4d.8h.29m
    urlhaus-1: 9364-0, 30m
    plowe-0: 3672-3, 9d.7h.49m
    ublock-quick-fixes: 427-0, 1m
filterset (user): [empty]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2639 ms (selfie)
  maxAssetCacheWait: 1694 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    nexusmods.com: 2
    enthusiastgaming.net: 1
    googletagmanager.com: 2
    hotjar.com: 1
    quantserve.com: 1
```
</details>

**Comment by FerdynandRomulus** [comment]
Also I would like to add that when downloading mods this utility allowed to skip through the 5 second timer. Now it doesn't work and you have to wait.

**Comment by FerdynandRomulus** [comment]
I updated the filter lists like it was reccomended in the other thread and the "No one like ads" label on top and the bottom is gone. However, the downloads still progress normally without fast-forwarding through the timer.

**Comment by FerdynandRomulus** [comment]
The "Slow download" is just the only download option non premium nexusmods accounts get. It's capped on 2 mb/s. Like a month ago when I was downloading a bunch of mods the 5 second timer was skipped instantenously in a few miliseconds, it makes a huge difference timewise when your modlist consists of over 1000 mods.

**Comment by FelesNoctis** [comment]
Related to issue #15415 : this seems to have broken the functionality of the site, and [okiehsch](https://github.com/okiehsch)'s attempted correction does not seem to have had any effect on my end.


> Adding that line to My Filters does not seem to fix the issue on my end, and neither did the update you made. Browser cache and cookies were cleared, filters were purged and updated, browser's built-in shields were disabled.
> 
> [uBlock filters as of purge and update](https://i.imgur.com/IECkl4B.png)
> [My Filter](https://i.imgur.com/gJYgXPU.png)
> [Filters Enabled](https://i.imgur.com/0f4HiQl.png)
> [Nexusmods page: still broken](https://i.imgur.com/flhoJNk.png)
> 
> Anything related to overlays or dropdowns is nonfunctional unless the base "uBlock filters" entry is disabled.

**Comment by PixelDew121** [comment]
Sites UI is completely broken with Ublock, the filter doesn't work either. Disabling Ublock allows me to click the download buttons and fixes the Images broken on all pages.

[Ublock origin enabled](https://i.imgur.com/aalWHNV.jpeg)
[Ublock origin disbaled](https://i.imgur.com/ZTwuM7p.jpg)

**Comment by okiehsch** [comment]
Does it work if you add
`nexusmods.com#@#+js(set-constant, areAdsBlocked, false)`

**Comment by FelesNoctis** [comment]
[My Filters updated](https://i.imgur.com/56ZCuEw.png)

That one does seem to have done the trick for me. Spent a few minutes testing as many different page types on the site as I could think of, haven't been able to find any broken elements yet.

Unfortunately I'm unable to test the timer for the "Slow Download" due to being a premium member, and it's against Nexus site policy to make a second account.

**Comment by okiehsch** [comment]
Ok, I removed the filter causing the issue and added another one to deal with the adblock message.
You can remove the exception filter after updating the `uBO-filter` list.
Can you check if the new filter breaks anything - it really shouldn't - on your end.

**Comment by FelesNoctis** [comment]
![My Filters updated](https://i.imgur.com/0Nz2y7z.png)
![uBlock filters after purge + update](https://i.imgur.com/Dnd6l5p.png)

Can't find any breaks in the site so far! When logged out/in private window, ads are still being blocked, and the ad-beg panel is also gone.

Hopefully the others will be able to confirm the status of the download timer.

**Comment by maddawg836** [comment]
> nexusmods.com#@#+js(set-constant, areAdsBlocked, false)

This one worked for me! thanks a bunch okiehsch!!

**Comment by stephenhawk8054** [comment]
The site uses a dedicated function to do the countdown so I don't think we can boost the timer via `nano-stb` or `nano-sib`

**Comment by stephenhawk8054** [comment]
It's a local function so not possible with `set` either.

**Comment by okiehsch** [comment]
The timer can't be fixed by us and the rest works fine as far as I can see, I will close.
