### ISSUE TITLE
gourmetscans.net: detection

### ISSUE THREAD

**Issue by gabigee** [uBlockOrigin/uAssets#15367]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gourmetscans.net/project/time-to-change-the-genre/chapter-55/`

### Category

detection

### Describe the issue

I use Firefox mobile. The website has a blanket banner for detection that rolls down when I try to scroll the content. When I try to enter the element zapper I can delete the content of the banner but not the banner itself, or I can delete everything on the website. If I try to delete the banner/blanket it turns the whole page black. The relevant code that appears in all the elements of the banner is ###ekupqiklo-blanket. I don't know a lot about using the picker tool but I got it to work for parts of the banner so I don't think it's user error

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 87995
  cosmetic: 27667
  scriptlet: 18192
  html: 791
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33932-312, 2d.12h.23m
    ublock-badware: 4383-0, 2d.12h.22m
    ublock-privacy: 281-1, 8d.4h
    ublock-abuse: 76-0, 8d.3h.59m
    ublock-unbreak: 1893-0, 2d.12h.21m
    ublock-quick-fixes: 423-0, 8h.14m
    adguard-mobile: 8149-168, 2d.12h.24m
    easylist: 62001-17934, 2d.20h.12m
    easyprivacy: 30763-1715, 2d.20h.11m
    urlhaus-1: 9364-0, 8h.15m
    plowe-0: 3673-3, 7d.8h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2027 ms (selfie)
  maxAssetCacheWait: 798 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    disq.us: 1
    disqus.com: 2
    google.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 2
    intergient.com: 4
    viglink.com: 2
```
</details>

**Comment by gabigee** [comment]
it's not fixed, the blanket is just a black screen now instead of a banner :(

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

Screenshot
<details>

![image](https://user-images.githubusercontent.com/66517106/197344744-e401cfb7-6195-43d6-9e7e-8f419d636e99.png)

</details>

Have you forced update the filter lists?
