### ISSUE TITLE
devclass.com: breakage

### ISSUE THREAD

**Issue by Paul-Williams** [uBlockOrigin/uAssets#15361]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://devclass.com/2022/10/19/github-fixes-over-broad-token-permissions-with-fine-grained-personal-access-tokens-and-controversial-enforced-expiration/`

### Category

breakage

### Describe the issue

All images are missing, and a blank space is left where they should have been displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87536
  cosmetic: 38661
  scriptlet: 18160
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62052-53, 2d.12h.36m
    easyprivacy: 30763-1170, 2d.12h.35m
    plowe-0: 3675-865, 2d.11h.53m
    ublock-abuse: 76-0, 2d.11h.51m
    ublock-badware: 4379-106, 2d.11h.49m
    ublock-filters: 33114-112, 2d.11h.48m
    ublock-privacy: 257-1, 2d.11h.47m
    ublock-quick-fixes: 391-22, 11h.50m
    ublock-unbreak: 1875-42, 2d.11h.45m
    urlhaus-1: 10304-0, 11h.49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 842 ms (selfie)
  maxAssetCacheWait: 561 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
I can't consistently reproduce.
Does
````
@@||devclass.com/wp-content/plugins/google-analytics-for-wordpress/assets/js/frontend-gtag.min.js$script,1p
@@||googletagmanager.com/gtag/js$script,domain=devclass.com
````
work?

**Comment by Paul-Williams** [comment]
Sorry, but what I am supposed to do with that? Should it be added to My Filters?

**Comment by okiehsch** [comment]
> Should it be added to My Filters?

Yes.

**Comment by Paul-Williams** [comment]
Thanks, that does work. However, just out of interest, does that mean Google tracking no longer fully disabled for that site?

I don’t understand the rule syntax, but it appears to make exeptions for:
google-analytics-for-wordpress and googletagmanager.com

on that site.

**Comment by okiehsch** [comment]
Yes, blocking those two requests results in the breakage you describe and that is a quite common.
We generally [redirect](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect) google-analytics  and googletagmanager to reduce site breakage but in this case the only way to fix it is to add an exception.

**Comment by Yuki2718** [comment]
On my end `@@||googletagmanager.com/gtag/js$script,domain=devclass.com` is not needed but `@@||googletagmanager.com/gtag/js$script,redirect-rule,domain=devclass.com` works.

**Comment by Yuki2718** [comment]
@Paul-Williams Can you test
```
||devclass.com/wp-content/plugins/google-analytics-for-wordpress/assets/js/frontend-gtag.min.js$important
||googletagmanager.com/gtag/js$script,important,domain=devclass.com
@@||googletagmanager.com/gtag/js$script,redirect-rule,domain=devclass.com
```
?

**Comment by okiehsch** [comment]
> `@@||googletagmanager.com/gtag/js$script,redirect-rule,domain=devclass.com` works.

I tested that and it did not work consistently on my end as I mentioned,
