### ISSUE TITLE
[nsfw] zenlytrade.com: privacy

### ISSUE THREAD

**Issue by gonzalolater** [uBlockOrigin/uAssets#15368]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://zenlytrade.com/`

### Category

Exchange

### Describe the issue

SCAM

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 90056
  cosmetic: 43682
  scriptlet: 18407
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 8h.35m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 3-0, never
    easylist: 62001-53, 2d.13h.43m
    easyprivacy: 30745-1170, 4d.5h.50m
    plowe-0: 3673-862, 8d.17h.39m
    spa-0: 3335-11, 22h.26m
    spa-1: 4732-166, 2d.9h.42m
    ublock-abuse: 76-0, 3d.11h.28m
    ublock-badware: 4380-106, 2d.9h.41m
    ublock-filters: 33123-153, 2d.9h.40m
    ublock-privacy: 256-1, 3d.11h.27m
    ublock-quick-fixes: 391-22, 22h.28m
    ublock-unbreak: 1875-44, 2d.9h.39m
    urlhaus-1: 10304-0, 22h.27m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13101 ms (selfie)
  maxAssetCacheWait: 487 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    tradingview.com: 1
```
</details>

**Comment by mapx-** [comment]
https://www.scamadviser.com/check-website/zenlytrade.com
