### ISSUE TITLE
t-mobile.com log-in broken

### ISSUE THREAD

**Issue by SammySezso** [uBlockOrigin/uAssets#15362]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.t-mobile.com/signin?state=eyJpbnRlbnQiOiJMb2dpbiIsImJvb2ttYXJrVXJsIjoiaHR0cHM6Ly93d3cudC1tb2JpbGUuY29tL2FjY291bnQvZGFzaGJvYXJkIn0%3D`

`https://www.t-mobile.com/unsupported_firefox_incognito`

### Describe the issue

When I try to log in to my t-mobile account I get the following message:

```
Logo Corporate
Firefox is no longer supported in private mode

The Firefox browser is no longer supported in private mode on our site. To continue, please take Firefox out of private mode or choose another browser. We recommend Chrome, Safari or Edge.
```

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 87231
  cosmetic: 38709
  scriptlet: 18162
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 33855-33, 2d.13h.3m
    ublock-badware: 4383-0, 2d.13h.2m
    ublock-privacy: 282-0, 1d.19h.22m
    ublock-abuse: 76-0, 1d.19h.21m
    ublock-unbreak: 1888-0, 2d.13h.1m
    ublock-quick-fixes: 423-22, 4h.5m
    easylist: 61932-247, 5d.22h.9m
    easyprivacy: 30725-1199, 5d.22h.8m
    urlhaus-1: 10176-0, 8h.6m
    plowe-0: 3675-868, 19h.18m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 367 ms (selfie)
  maxAssetCacheWait: 403 ms
```
</details>

**Comment by okiehsch** [comment]
> how's that related to ublock origin

It isn't. 😀

**Comment by krystian3w** [comment]
If this is easy test maybe works solutions form 2019/2020:

```adb
t-mobile.com##+js(set-constant.js, window.indexedDB, undefined)

t-mobile.com##+js(set-constant.js, navigator.storage.estimate, undefined)

t-mobile.com##+js(set-constant.js, webkitRequestFileSystem, noopFunc)
```

If all these walls now rejected then maybe pin in Readme.md?

**Comment by krystian3w** [comment]
If I correct tested: addons to spoof user agent no works.

Maybe works URL from bookmarks:

`eaccount.t-mobile.com/singin/v2/`
`es.account.t-mobile.com/singin/v2/`

But I don't have account to test login.
