### ISSUE TITLE
email-link.adtidy.org: breakage

### ISSUE THREAD

**Issue by oliverthedeveloper** [uBlockOrigin/uAssets#15363]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://email-link.adtidy.org/email.html?m=tbm21ev82y&l=pp7iobaftFKAufDHzXUpkuLRjH8QkHQ84vUq8tNQD0PgOrBkI6AL8QNfwnAdjRvBTUjNgKb1BzaSAGEuQiJJ00ySetcRGQjYbXAkw9HRUsF8OgyBoDdqUFvow8Z6YghwcwfTdiZSiNndgD53OXDNuX6axEi2e6IRvj8S4G8x2hvnzIBiqLTBVywjK5rW4tcv8WwLYuCdzGUEOOFfS6d9vaLAdnp76Kb9E6bOw2Eh0u87NDbGKcHK8GyCnzsgTIARNv`

### Category

breakage

### Describe the issue

Trying to reset my AdGuard-DNS password, through my Firefox-browser. My mail is with Proton.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 255668
  cosmetic: 211288
  scriptlet: 38343
  html: 811
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64201-5236, 1d.17h.20m
    adguard-spyware: 33710-13614, 1d.17h.19m
    adguard-spyware-url: 792-4, 1d.17h.18m
    block-lan: 44-0, 5d.19h.41m
    curben-phishing: 110615-9, 12h.57m
    curben-pup: 194-0, 12h.56m
    adguard-annoyance: 59937-5143, 1d.17h.17m
    adguard-social: 18534-1066, 1d.17h.16m
    fanboy-thirdparty_social: 69-0, 5d.19h.41m
    fanboy-annoyance: 81194-65188, 5d.19h.41m
    fanboy-cookiemonster: 41610-137, 5d.19h.41m
    fanboy-social: 23389-28, 5d.19h.41m
    ublock-annoyances: 4874-5, 1d.17h.15m
    dpollock-0: 11389-482, 5d.19h.41m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33857-83, 2d.5h.26m
    ublock-badware: 4384-0, 2d.5h.25m
    ublock-privacy: 281-0, 6d.6h.42m
    ublock-abuse: 76-0, 6d.6h.41m
    ublock-unbreak: 1888-0, 2d.5h.24m
    ublock-quick-fixes: 427-0, now
    easylist: 61932-838, 6d.6h.38m
    easyprivacy: 30724-1804, 6d.6h.37m
    urlhaus-1: 9364-0, now
    plowe-0: 3671-3, now
    NOR-0: 2812-10, now
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1927 ms
  maxAssetCacheWait: 2743 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/197258942-ea8c305d-5b7f-4805-a1bf-353dbb6a0310.png)

Click "Temporarly" or "Permanently".

**Comment by oliverthedeveloper** [comment]
> ![image](https://user-images.githubusercontent.com/16838044/197258942-ea8c305d-5b7f-4805-a1bf-353dbb6a0310.png)
> 
> Click "Temporarily" or "Permanently".

That really helped.
![billede](https://user-images.githubusercontent.com/40898841/197404213-e821eee8-f1f4-46cd-86c9-b486484b69f2.png)

**Comment by oliverthedeveloper** [comment]
Wrong button. Just wanted to comment the photo. No idea, how to reverse it.
