### ISSUE TITLE
zoominfo.com: detection

### ISSUE THREAD

**Issue by j5155** [uBlockOrigin/uAssets#15370]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zoominfo.com/`

### Category

detection

### Describe the issue

Accessing zoominfo.com results in an 'Access denied' page with specific instructions to disable uBlock Origin. See screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2022-10-21 17-01-12](https://user-images.githubusercontent.com/54331556/197309504-795a2115-d4bf-4d18-af0c-8809ac243dc4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 104
filterset (summary): 
  network: 257036
  cosmetic: 215773
  scriptlet: 38342
  html: 810
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64201-5244, 1d.20h.18m
    adguard-mobile: 8149-189, 1d.20h.21m
    adguard-spyware: 33710-13641, 1d.20h.19m
    adguard-spyware-url: 792-3, 1d.20h.22m
    curben-phishing: 110615-9, 23h.36m
    curben-pup: 193-0, 23h.37m
    adguard-annoyance: 59937-5148, 1d.20h.17m
    adguard-social: 18534-1065, 1d.20h.20m
    fanboy-thirdparty_social: 68-0, 5d.5h.22m
    fanboy-annoyance: 81276-65268, 5d.5h.21m
    fanboy-cookiemonster: 41690-150, 5d.5h.20m
    fanboy-social: 23390-28, 23h.39m
    ublock-annoyances: 4874-4, 1d.20h.23m
    dpollock-0: 11389-483, 11d.21h.3m
  default: 
    user-filters: 3-0, never
    ublock-filters: 33866-76, 1d.20h.16m
    ublock-badware: 4384-0, 1d.20h.15m
    ublock-privacy: 281-0, 9d.20h.27m
    ublock-abuse: 76-0, 9d.20h.26m
    ublock-unbreak: 1888-1, 1d.20h.14m
    ublock-quick-fixes: 394-0, 23h.35m
    easylist: 61938-977, 1d.20h.25m
    easyprivacy: 30774-1810, 1d.20h.24m
    urlhaus-1: 10176-0, 23h.38m
    plowe-0: 3671-3, 13d.5h.7m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 20 redacted]
hostRuleset: 
  added: [array of 53 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2266 ms (selfie)
  maxAssetCacheWait: 1100 ms
popupPanel: 
  blocked: 8
  no-remote-fonts: true
  blockedDetails: 
    zoominfo.com: 1
    gstatic.com: 1
    px-client.net: 2
    px-cloud.net: 4
```
</details>

**Comment by Procyon-b** [comment]
What happens when you click and hold the click on the button ? You must hold until the button is completely black.

**Comment by mapx-** [comment]
Test this filter

`*$script,domain=zoominfo.com,redirect-rule=noopjs`

example link => `https://www.zoominfo.com/p/Sergey-Brin/3133965445`

**Comment by gorhill** [comment]
I can't reproduce detection with default filter lists.

**Comment by j5155** [comment]
I can no longer reproduce it with my current configuration either. Interesting. I'll close this issue now.

**Comment by zzColin** [comment]
This seems to be a PerimeterX Human Challenge page. I also intermittently come across this when visiting Mouser Electronics website (www.mouser.com), however without the red text in the screenshot, which might be a custom message set by the website. I'm not sure if it is caused by uBlock Origin or not, but i don't think it to be a deliberate "detection".
