### ISSUE TITLE
mint.intuit.com: ads

### ISSUE THREAD

**Issue by JJrodny** [uBlockOrigin/uAssets#15378]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mint.intuit.com/transactions`

### Category

ads

### Describe the issue

Ads load a second or two after the page loads, probably why it's missing the ads when it tries to block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture22343](https://user-images.githubusercontent.com/130616/197357885-8880dccb-d248-43bd-ba10-9a3bbd410516.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86355
  cosmetic: 38686
  scriptlet: 18167
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33865-137, 2d.18h.48m
    ublock-badware: 4384-0, 2d.18h.47m
    ublock-privacy: 282-0, 46m
    ublock-abuse: 76-0, 45m
    ublock-unbreak: 1888-0, 2d.18h.46m
    easylist: 62008-526, 41m
    easyprivacy: 30797-1707, 42m
    urlhaus-1: 9130-0, 39m
    plowe-0: 3671-3, 43m
    ublock-quick-fixes: 429-0, 40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2228 ms (selfie)
  maxAssetCacheWait: 1329 ms
popupPanel: 
  blocked: 1893
  blockedDetails: 
    intuit.com: 1687
    demdex.net: 1
    digicert.com: 42
    intuitcdn.net: 1
    tealiumiq.com: 1
    truste.com: 161
```
</details>

**Comment by mapx-** [comment]
Use element picker, create your filters (if working post them here), we cannot help you (require4d account, connect account banks / paypal etc)
