### ISSUE TITLE
mangatigre.net: ads

### ISSUE THREAD

**Issue by Abril1030** [uBlockOrigin/uAssets#15379]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.mangatigre.net/manga/hunter-x-hunter/391`

### Category

ads

### Describe the issue

Ads show up in this page, and UBlock Origin doesn't seem to work... it's a pop up and screen blocking ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 77159
  cosmetic: 38712
  scriptlet: 18099
  html: 785
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33822-33, 7d.6h.59m
    ublock-badware: 4373-0, 7d.6h.57m
    ublock-privacy: 273-0, 17d.17h.50m
    ublock-abuse: 76-0, 13d.21h.23m
    ublock-unbreak: 1885-0, 7d.6h.58m
    easylist: 61932-247, 6d.18h.25m
    easyprivacy: 30725-1199, 6d.18h.24m
    urlhaus-1: 8969-0, 7d.6h.56m
    plowe-0: 3671-865, 13d.21h.22m
    ublock-quick-fixes: 366-19, 7d.6h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3610 ms
  maxAssetCacheWait: 2031 ms
popupPanel: 
  blocked: 0
  no-popups: true
```
</details>

**Comment by Yuki2718** [comment]
All I see is broken image even with uBO disabled.

**Comment by gorhill** [comment]
> [x] I did not answer truthfully to all the above checkpoints

and

>     trustedset:
>       added: [array of 1 redacted]

and

>     blocked: 0

Looks like OP disabled uBO on that site and didn't carefully go through prerequisites steps, closing as invalid.
