### ISSUE TITLE
gedichte.ws: ads

### ISSUE THREAD

**Issue by WilliamReed2004** [uBlockOrigin/uAssets#15374]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gedichte.ws/`

### Category

ads

### Describe the issue

Some ads still visible on the right page side

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/29880819/197334439-efff2da0-d12a-4a3a-a60a-f681b91c8d8d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 1985190
  cosmetic: 42466
  scriptlet: 18149
  html: 789
listset (total-discarded, last updated): 
  default: 
    user-filters: 1896734-131, never
    ublock-filters: 33823-141, 3d.15h.30m
    ublock-badware: 4383-0, 3d.15h.29m
    ublock-privacy: 281-0, 7d.16h.1m
    ublock-abuse: 76-0, 7d.16h
    ublock-unbreak: 1888-0, 3d.15h.28m
    easylist: 61932-518, 6d.43m
    easyprivacy: 30725-1732, 6d.42m
    urlhaus-1: 9364-0, 18h.59m
    plowe-0: 3675-3, 7d.15h.58m
    DEU-0: 5973-2, 19h
    ublock-quick-fixes: 427-0, 18h.58m
filterset (user): [array of 1896738 redacted]
trustedset: 
  added: [array of 219 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 67 redacted]
urlRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5508 ms (selfie)
  maxAssetCacheWait: 2560 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    gedichte.ws: 2
    googlesyndication.com: 1
    quantcast.com: 2
    teads.tv: 2
    themoneytizer.com: 12
    yandex.ru: 1
```
</details>

**Comment by okiehsch** [comment]
Update the `uBO-filters` list, the ads should be gone after that.

**Comment by WilliamReed2004** [comment]
> Update the `uBO-filters` list, the ads should be gone after that.
> 

Did so, hasn't worked.
The ad image is served by the server itself, might that be an issue?

**Comment by Yuki2718** [comment]
@WilliamReed2004 Are you sure you have done "Purge cache" => "Update now"?

**Comment by okiehsch** [comment]
> Did so, hasn't worked.
The ad image is served by the server itself, might that be an issue?

It works on my end, the ads are caused by an ad-reinsertion script - `https://www.gedichte.ws/js/t.js`- and they are defused by the filter I added.
