### ISSUE TITLE
nexusmods.com: detection

### ISSUE THREAD

**Issue by honwen123** [uBlockOrigin/uAssets#15371]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nexusmods.com/`

### Category

detection

### Describe the issue

nexusmods detects ublock origin, never had this issue before

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 93685
  cosmetic: 79406
  scriptlet: 24120
  html: 810
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 60042-2358, 1m
    ublock-annoyances: 4902-7, 1m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33930-313, 3d.21h.12m
    ublock-badware: 4402-0, 14m
    ublock-privacy: 282-1, 3d.4h.19m
    ublock-abuse: 76-0, 3d.4h.18m
    ublock-unbreak: 1893-0, 3d.21h.11m
    adguard-mobile: 8163-168, 14m
    easylist: 61966-17946, 5d.21h.11m
    easyprivacy: 30763-1717, 3d.21h.13m
    urlhaus-1: 10176-0, 18h.57m
    plowe-0: 3675-3, 3d.21h.14m
    ublock-quick-fixes: 423-0, 18h.56m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3961 ms
  maxAssetCacheWait: 538 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    nexusmods.com: 2
    enthusiastgaming.net: 1
    googletagmanager.com: 2
    hotjar.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
fixed yesterday, update the filter lists
