### ISSUE TITLE
netspend.com: breakage

### ISSUE THREAD

**Issue by quista940** [uBlockOrigin/uAssets#15377]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.netspend.com/account/recover/handoff/bkBYhVVUSci8G0gQIVDNGw`

### Category

breakage

### Describe the issue

will not let me reset password or login into netspend and im blocked from facebook will not let me sign in new account n i have done nothing but i have been hacked so much hard telling please let me back on these websites n also go2 bank isnt letting me on i went thru identity theft n people had accounts on these three sites n and cards i didnt know about please help me with this especially facebook so i can talk to my daughters n connecgt with my church 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85658
  cosmetic: 38694
  scriptlet: 18185
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62002-53, 19m
    easyprivacy: 30781-1170, 18m
    plowe-0: 3671-865, 17m
    ublock-abuse: 76-0, 1h.34m
    ublock-badware: 4404-105, 26m
    ublock-filters: 33159-112, 24m
    ublock-privacy: 257-1, 23m
    ublock-quick-fixes: 426-32, 7m
    ublock-unbreak: 1875-42, 22m
    urlhaus-1: 8425-1, 21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 232 ms (selfie)
  maxAssetCacheWait: 245 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    netspend.com: 2
    adobedtm.com: 5
    demdex.net: 3
    googletagmanager.com: 2
    iesnare.com: 1
    omtrdc.net: 1
```
</details>

**Comment by okiehsch** [comment]
Does adding
`@@||mpsnare.iesnare.com/snare.js$script,domain=netspend.com`
to your filter list work?

If you urgently need access and think uBO is preventing it why not simply disable it?
