### ISSUE TITLE
nation.foxnews.com: breakage

### ISSUE THREAD

**Issue by nomaddc** [uBlockOrigin/uAssets#15383]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nation.foxnews.com/account/signup-plans/`

### Category

breakage

### Describe the issue

The problem seems to be caused by the EasyPrivacy list - I've verified that it's the only one causing problems there. When on it results in a potentially infinite (or very lengthy) loading of the plan options (I did not manage to get it to load with that filter on).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 171373
  cosmetic: 154669
  scriptlet: 36887
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, now
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, now
    https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt: 15932-0, now
    https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt: 1701-1, now
    JPN-1: 8106-15, now
    adguard-annoyance: 60048-95, now
    adguard-generic: 64193-496, now
    adguard-mobile: 8172-109, now
    adguard-social: 18579-841, now
    adguard-spyware: 33727-2885, now
    adguard-spyware-url: 792-1, now
    block-lan: 44-0, now
    dpollock-0: 11389-1509, now
    fanboy-thirdparty_social: 68-3, now
    ublock-annoyances: 4856-191, now
  default: 
    user-filters: 0-0, never
    easylist: 62008-1318, 2m
    easyprivacy: 30781-12965, now
    plowe-0: 3671-1539, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 4404-250, 2m
    ublock-filters: 33171-3840, 2m
    ublock-privacy: 257-45, 2m
    ublock-quick-fixes: 428-48, now
    ublock-unbreak: 1875-105, 2m
    urlhaus-1: 9130-0, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 38 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 441 ms (selfie)
  maxAssetCacheWait: 354 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    foxnews.com: 1
    a3cloud.net: 1
    akamaihd.net: 1
    bing.com: 2
    browser-intake-datadoghq.com: 4
    demdex.net: 1
    fox.com: 2
    googletagmanager.com: 1
    gumgum.com: 1
    knotch-cdn.com: 1
    moatads.com: 3
    redfastlabs.com: 1
    teads.tv: 1
    trendemon.com: 1
```
</details>

**Comment by gorhill** [comment]
Does this fix the issue on your side?

    @@||analytics.nova.foxnews.com/analytics.js/v1/$1p,script

**Comment by Yuki2718** [comment]
@ryanbr
