### ISSUE TITLE
adshnk.com: breakage

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#15384]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://adshnk.com/vqq6u0`

### Category

breakage

### Describe the issue

unable redirect to final link

### Screenshot(s)

stuck loading and does not redirect

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/197367477-abc15788-672f-4155-9f9f-a002f61a9d6e.png)

</details>

---

Expected behaviour

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/197367629-2e9e8f6a-6436-4050-9978-e787d77434bb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 116289
  cosmetic: 147258
  scriptlet: 34414
  html: 790
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 64127-5119, 2d.2h.39m
    adguard-spyware: 33713-13465, 2d.2h.39m
    adguard-spyware-url: 792-3, 2d.2h.39m
    adguard-annoyance: 59976-1548, 2d.2h.39m
    adguard-social: 18554-25, 2d.2h.39m
  default: 
    user-filters: 69-0, never
    ublock-filters: 33889-86, 1d.23h.38m
    ublock-badware: 4398-0, 2d.2h.39m
    ublock-privacy: 282-0, 2d.2h.39m
    ublock-abuse: 76-0, 2d.2h.39m
    ublock-unbreak: 1889-1, 2d.2h.39m
    ublock-quick-fixes: 431-0, 2h.28m
    easylist: 62104-326, 2d.2h.39m
    easyprivacy: 30781-1190, 2d.2h.39m
    TUR-0: 9569-9, 2d.2h.39m
filterset (user): [array of 77 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4613 ms
  maxAssetCacheWait: 1377 ms
  unsuspendAfter: 2360 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adsco.re: 1
    cookielaw.org: 2
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 1
    quantserve.com: 1
    taboola.com: 1
    trackjs.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I have to allow `fundingchoicemessages` scripts

```adb
@@||adshnk.com^$ghide
@@||fundingchoicesmessages.google.com/i/pub-$script,domain=adshnk.com
@@||fundingchoicesmessages.google.com/f/$script,domain=adshnk.com
```

Anyone has better ideas?

**Comment by gorhill** [comment]
> Anyone has better ideas?

Not really, looks like `fundingchoicesmessages.google.com` is really needed.

**Comment by mapx-** [comment]
> This doesn't work on my end.

- provide a working link
- provide info about your setup (browser, uBO version, filter lists etc)

**Comment by percheperche** [comment]
> * provide a working link

The one sent by OP.

> * provide info about your setup (browser, uBO version, filter lists etc)

I'm on Brave, uBlock Origin 1.45.2 and here are the filters:

![image](https://user-images.githubusercontent.com/44583807/208197840-79f18482-3372-405a-a3f3-54cb47352fa2.png)

**Comment by mapx-** [comment]
> The one sent by OP.

![image](https://user-images.githubusercontent.com/10303732/208229904-e637173f-c5b1-4292-8c52-7a5768f179df.png)

**Comment by percheperche** [comment]
> ![image](https://user-images.githubusercontent.com/10303732/208229904-e637173f-c5b1-4292-8c52-7a5768f179df.png)

Yes, but on my end it shows this: 
![image](https://user-images.githubusercontent.com/44583807/208230425-ea44b161-e918-49aa-8060-a9464d77cbb8.png)

I tried with other links and it's the same.

**Comment by mapx-** [comment]
In your setup I see no uBO filter list. Did you disable them ?

**Comment by percheperche** [comment]
> In your setup I see no uBO filter list. Did you disable them ?

Oh sorry, I put the code here: 
![image](https://user-images.githubusercontent.com/44583807/208230804-06732e2d-a160-4cc4-9744-b85438813fac.png)

**Comment by mapx-** [comment]
No, I mean these lists:

![image](https://user-images.githubusercontent.com/10303732/208230871-f919d9ec-a5ec-43d9-ae7b-81f91e97b8ed.png)

Then disable / remove any custom filter for this site, test using **ONLY** the default setup (don't use FFA list)

Follow these steps:
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by percheperche** [comment]
> Then disable / remove any custom filter for this site, test using **ONLY** the default setup (don't use FFA list)
> 
> Follow these steps:
> 
> * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> * restart the system, reopen the browser, test again.

Hi, thank you. It seems like the problem was the "I don't care about cookies" extension (I don't know why). Is there any alternative to it?

**Comment by mapx-** [comment]
idk if @kiboke still work on this extension (bought by avast)

**Comment by kiboke** [comment]
@mapx- I do :) Btw Avast has merged with Norton in the meantime.
I'll add an exception, it will work again soon. Thanks for letting me know!
