### ISSUE TITLE
 nnmlsrelay-config-production.s3.amazonaws.com: nuisance

### ISSUE THREAD

**Issue by LandseyFrendzee** [uBlockOrigin/uAssets#15385]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://lsrelay-config-production.s3.amazonaws.com/f8db5b5547d93ef167b094ef5c73485f56e752bb4971141abb5cda8ffb88c8ee/block_screen.html`

### Category

nuisance

### Describe the issue

Every time I try to go into Roblox, it goes to a different website like the one I'm reporting right now.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 77125
  cosmetic: 38563
  scriptlet: 17999
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/beaverton-school-district/uBlockAllowList/main/bsdallowlist.txt: 71-0, 22h.23m
  default: 
    user-filters: 2-0, never
    easylist: 62001-53, 4d.8h.12m
    easyprivacy: 30763-1170, 4d.8h.11m
    plowe-0: 3673-862, 10d.2h.40m
    ublock-badware: 4394-106, 2d.4h.23m
    ublock-filters: 33148-109, 2d.4h.22m
    ublock-privacy: 257-1, 2d.8h.36m
    ublock-unbreak: 1875-42, 2d.4h.21m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2929 ms (selfie)
  maxAssetCacheWait: 315 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
```
</details>

**Comment by LandseyFrendzee** [comment]
I sometimes try to go to websites like Roblox, or slither.io(A dead game but I still play it lol)
It just for some reason overlays the screen with a thing saying
"Oops, Website.com has been blocked because it had been categorized as games"
________________________________

**Comment by stephenhawk8054** [comment]
I go to `slither.io` and let it run for a while, but I don't see any overlays appear. That sentence looks like not coming from the websites but from other blocking extensions/apps/softwares.

**Comment by gorhill** [comment]
> Your school network has blocked game sites.

**Comment by py660** [comment]
`lsrelay-config-production.s3.amazonaws.com` is the URL for Lightspeed Filter Agent (formerly Relay), and Lightspeed is a extension that blocks certain websites. 

> > Your school network has blocked game sites.

**Comment by Knight47k** [comment]
how do you get past it

**Comment by gorhill** [comment]
> how do you get past it

This is not the place to ask question about how to go around your school's choice of blocking website. Contact your school administrator or seek help on a forum related to this, this is not a uBO issue.
