### ISSUE TITLE
crazygames.fr: breakage

### ISSUE THREAD

**Issue by oliviercailloux** [uBlockOrigin/uAssets#15382]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.crazygames.fr/jeu/keeper-of-the-grove-2`

### Category

breakage

### Describe the issue

The game never starts with uBlock running. (When disabling uBlock and reloading the page, the game starts.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.0
Firefox: 102
filterset (summary): 
  network: 83602
  cosmetic: 38683
  scriptlet: 18163
  html: 789
listset (total-discarded, last updated): 
  removed: 
    FRA-0: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 33842-54, 3d.10h.31m
    ublock-badware: 4384-0, 3d.10h.29m
    ublock-privacy: 281-0, 9d.2h.46m
    ublock-abuse: 76-0, 9d.2h.45m
    ublock-unbreak: 1888-0, 3d.10h.30m
    easylist: 62008-273, 1d.5h.33m
    easyprivacy: 30781-1176, 1d.5h.32m
    urlhaus-1: 9130-0, 3h.37m
    ublock-quick-fixes: 429-0, 3h.38m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1835 ms (selfie)
  maxAssetCacheWait: 706 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    2mdn.net: 2
    amazon-adsystem.com: 2
    crazygames.com: 1
    crwdcntrl.net: 1
    doubleclick.net: 2
    gamedock.io: 1
    google-analytics.com: 2
    googlesyndication.com: 3
    googletagmanager.com: 2
    imasdk.googleapis.com: 1
    iubenda.com: 1
    jsdelivr.net: 2
```
</details>

**Comment by oliviercailloux** [comment]
Thanks a lot for this very quick fix!

**Comment by stephenhawk8054** [comment]
I can't reproduce the anti-adblock. Are you signing to the site?
