### ISSUE TITLE
digminecraft.com: breakage

### ISSUE THREAD

**Issue by Owehttamy** [uBlockOrigin/uAssets#15392]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.digminecraft.com/`

### Category

breakage

### Describe the issue

Web pages appear blank after one frame of visibility. _Can_ remedy by disabling cosmetic filtering, but something should have different behavior by default.

Also, I don't know if there's any care for removing those empty boxes where advertisements are _supposed_ to be, but they do reappear when cosmetic filtering is disabled. If it doesn't matter if they're around, then disregard this line.

Thanks for your work, have a nice rest of your day, guys! :)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Enabled](https://user-images.githubusercontent.com/47429979/197419525-693d5d0d-5e7b-4811-8bd2-748c67ee634b.PNG)
![Disabled](https://user-images.githubusercontent.com/47429979/197419528-664fdeae-05d8-4155-bac2-288c93d69064.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86315
  cosmetic: 38690
  scriptlet: 18184
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 62002-53, 2d.18h.3m
    easyprivacy: 30781-1170, 2d.18h.2m
    plowe-0: 3675-865, 6d.17h.46m
    ublock-abuse: 76-0, 10d.15h.46m
    ublock-badware: 4399-105, 2d.39m
    ublock-filters: 33151-112, 2d.38m
    ublock-privacy: 256-1, 10d.15h.42m
    ublock-quick-fixes: 426-32, 16h.9m
    ublock-unbreak: 1875-42, 2d.37m
    urlhaus-1: 9083-0, 16h.8m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 353 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  blockedDetails: 
    google.com: 2
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

Your screenshot shows that theere are 3 elements filtered on your page, while I get none on my side. Please verify that your own filters are not causing the issue.

**Comment by stephenhawk8054** [comment]
I can reproduce the issue. On my device, it's caused by the filter

```adb
digminecraft.com##:xpath(//*[contains(text(),"Advertisements")]):upward(1)
```
in `uBlock filters`.

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/197661208-25081dcf-63a8-4090-ad58-2cc9d35662cf.png)

</details>
