### ISSUE TITLE
slopegameunblocked.com: privacy

### ISSUE THREAD

**Issue by github3240987** [uBlockOrigin/uAssets#15399]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slopegameunblocked.com/cgi-sys/suspendedpage.cgi`

### Category

privacy

### Describe the issue

fake account suspention(mabey virus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86030
  cosmetic: 38705
  scriptlet: 18204
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62002-53, 3d.4h.22m
    easyprivacy: 30774-1170, 5d.1h.57m
    plowe-0: 3671-862, 13d.23h.13m
    ublock-abuse: 76-0, 7d.1h.35m
    ublock-badware: 4342-104, 1h.51m
    ublock-filters: 33199-112, 1h.50m
    ublock-privacy: 257-1, 3d.4h.23m
    ublock-quick-fixes: 428-32, 1h.47m
    ublock-unbreak: 1879-42, 1h.49m
    urlhaus-1: 8844-0, 1h.48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1673 ms (selfie)
  maxAssetCacheWait: 659 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google.com: 1
```
</details>

**Comment by ghajini** [comment]
Not a ubo issue(?fake account suspension)
