### ISSUE TITLE
mee6.xyz/terms.html: breakage

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uAssets#15398]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mee6.xyz/terms.html`

### Describe the issue

The website is blank

### uBlock Origin version

1.44.4

### Browser name and version

Vivaldi snapshot (5.6.2829.3 (Official Build) snapshot (64-bit))

### Settings

- Enabled annoyances filter

### Notes

There appears to be an iframe linked to https://www.iubenda.com/terms-and-conditions/61412973, which is being blocked.

**Comment by gorhill** [comment]
Should be fixed in Fanboy Annoyances by adding `mee6.xyz` to the exception filter

    @@||iubenda.com^$script,subdocument,xmlhttprequest,domain=...

**Comment by stephenhawk8054** [comment]
@ryanbr
