### ISSUE TITLE
trustroots.org: breaks uploading profile image

### ISSUE THREAD

**Issue by xeruf** [uBlockOrigin/uAssets#15393]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.trustroots.org/profile/edit/photo`

### Category

breakage

### Describe the issue

When I try to upload a new profile image, the api request to sentry to actually complete it is blocked.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 86716
  cosmetic: 38989
  scriptlet: 18123
  html: 785
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33822-43, 3d.11h.1m
    ublock-badware: 4368-0, 3d.11h.3m
    ublock-privacy: 274-0, 10d.8h.17m
    ublock-abuse: 76-0, 10d.8h.16m
    ublock-unbreak: 1885-0, 3d.11h.2m
    easylist: 62538-598, 6d.3h.30m
    easyprivacy: 30711-1705, 6d.3h.31m
    urlhaus-1: 9383-0, 2h.7m
    plowe-0: 3671-3, 10d.8h.14m
    ublock-quick-fixes: 392-0, 2h.8m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1322 ms (selfie)
  maxAssetCacheWait: 640 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    trustroots.org: 4
    sentry.io: 5
```
</details>

**Comment by ghajini** [comment]
i can upload a profile pic with `sentry` blocked by default settings

![image](https://user-images.githubusercontent.com/20338483/197958708-1edc06db-4a29-4611-8236-917ccf5ed557.png)
![firefox_ZMOnT0KGiz](https://user-images.githubusercontent.com/20338483/197958837-e1337086-5d18-4d0d-adba-a3094b7ba5c7.png)
