### ISSUE TITLE
[NSFW] watchporn.to ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#15390]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://watchporn.to/videos/29723/jackandjill-bff-their-first-3some-together/`

### Describe the issue

Ads on the videoplayer and on the right side.

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106

### Settings

Default settings

**Comment by stephenhawk8054** [comment]
I can't see any ads. Can you force update the filter lists ([click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

If the issue still persists, can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by gemoshi07** [comment]
@stephenhawk8054 thank you, it worked wiith force update option.

**Comment by dportvine** [comment]
I see ads but it happens very randomly.

<details>
<summary>Screen</summary>

![2022-10-24_120506](https://user-images.githubusercontent.com/111344219/197491603-7b6de390-5093-40ba-902c-bb41fd81f60c.png)
![2022-10-24_120544](https://user-images.githubusercontent.com/111344219/197491622-52991cf3-5de5-4fa3-bd2a-73d7561050b4.png)
</details>

Adblocker detected with rule `###ads_iframe` from **RU AdList**

<details>
<summary>Screen</summary>

![2022-10-24_122606](https://user-images.githubusercontent.com/111344219/197494309-14a8a20f-5e6f-44fa-80d7-21f95e7141a0.png)
![2022-10-24_121011](https://user-images.githubusercontent.com/111344219/197492424-78cc4aa7-e782-4aa0-b338-b9f03e33d16f.png)
</details>

I added this rule and it works for me.
```adb
watchporn.to##+js(nostif, offsetWidth)
```
<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 100121
  cosmetic: 125932
  scriptlet: 24467
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31477-27, 1m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1527-24, 1m
    fanboy-cookiemonster: 41908-286, 1m
    ublock-annoyances: 4857-52, 1m
  default: 
    user-filters: 7-0, never
    RUS-0: 40422-147, 1m
    easylist: 62003-81, 1m
    easyprivacy: 30788-1588, 1m
    ublock-abuse: 76-1, 1m
    ublock-badware: 4342-102, 1m
    ublock-filters: 33193-168, 1m
    ublock-privacy: 260-8, 1m
    ublock-quick-fixes: 436-32, 1m
    ublock-unbreak: 1879-45, 1m
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 1053 ms
  maxAssetCacheWait: 783 ms
```
</details>

**Comment by dportvine** [comment]
@stephenhawk8054 

Can you fix it?

> Adblocker detected with rule `###ads_iframe` from **RU AdList**

<details>
<summary>Screen</summary>

![2022-10-24_122606](https://user-images.githubusercontent.com/111344219/197494309-14a8a20f-5e6f-44fa-80d7-21f95e7141a0.png)
![2022-10-24_121011](https://user-images.githubusercontent.com/111344219/197492424-78cc4aa7-e782-4aa0-b338-b9f03e33d16f.png)
</details>
 
>I added this rule and it works for me.
 ```adb
watchporn.to##+js(nostif, offsetWidth)
 ```

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054
> 
> Can you fix it?
> 
> > Adblocker detected with rule `###ads_iframe` from **RU AdList**
> 
> Screen
> 
> > I added this rule and it works for me.
> 
> ```
> watchporn.to##+js(nostif, offsetWidth)
> ```

You should report it to RU AdList

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
As far as I can see, the adblocker is detected even without RU AdList.
It seems better to add: `watchporn.to##+js(set, flashvars.protect_block, '')`

**Comment by dportvine** [comment]
>watchporn.to##+js(set, flashvars.protect_block, '')

Yes, it works for me.
