### ISSUE TITLE
thestar.co.uk [anti-adblock]

### ISSUE THREAD

**Issue by benoliver999** [uBlockOrigin/uAssets#1539]
### URL(s) where the issue occurs

`https://www.thestar.co.uk/`

### Describe the issue

There is an anti-adblock script in place.

### Screenshot(s)

![screenshot-2018-2-14 the star - sheffield news](https://user-images.githubusercontent.com/4549631/36207350-77b6b084-118d-11e8-89f9-accd2ac460bb.png)

### Versions

- Browser/version: Firefox for Arch Linux 58.0.2 (64-bit)
- uBlock Origin version: 1.15.6

### Settings

- Added NanoDefender support, so those filters and

`userResourcesLocation https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

**Comment by benoliver999** [comment]
Hmm sometimes it doesn't happen on the home page. If you click a link the pop up then appears.

`https://www.thestar.co.uk/news/ex-pupil-in-custody-after-car-ploughed-into-sheffield-school-1-9014700`

**Comment by stephenhawk8054** [comment]
Video player in home page and any video player in other articles cannot load.

URL:
`https://www.thestar.co.uk/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/148212803-25c75507-c428-4061-ade1-255966abbf12.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77892
  cosmetic: 40300
  scriptlet: 16366
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30621-30, 2h.54m
    ublock-badware: 3652-1, 2h.54m
    ublock-privacy: 182-0, 2h.54m
    ublock-abuse: 76-0, 2h.54m
    ublock-unbreak: 1721-0, 2h.54m
    easylist: 62630-579, 2h.54m
    easyprivacy: 26597-481, 2h.54m
    urlhaus-1: 7251-0, 2h.53m
    plowe-0: 3683-2, 2h.53m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 660 ms
popupPanel: 
  blocked: 27
```
</details>

Proposed filters:

```
@@||googletagservices.com/tag/js/gpt.js$script,domain=thestar.co.uk
@@||securepubads.g.doubleclick.net/gpt/*$script,domain=thestar.co.uk
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by dportvine** [comment]
Leftovers `blackpoolgazette.co.uk` & other domains.

<details>
<summary>Screen</summary>

![2024-04-11_141747](https://github.com/uBlockOrigin/uAssets/assets/111344219/93457023-5e02-48b8-8afb-bbaab7d0507e)
</details>
