### ISSUE TITLE
jornaleconomico.pt: ads

### ISSUE THREAD

**Issue by rhodin** [uBlockOrigin/uAssets#15405]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://jornaleconomico.pt/`

### Category

ads

### Describe the issue

A large in-page pop-up ad appears when this page is loaded.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 377459
  cosmetic: 260687
  scriptlet: 42106
  html: 881
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64205-6508, 1d.11h.11m
    adguard-mobile: 8173-212, 1d.11h.10m
    adguard-spyware: 33737-13711, 1d.11h.9m
    adguard-spyware-url: 793-3, 1d.11h.8m
    block-lan: 44-0, 7d.13h.14m
    curben-phishing: 139036-10, 28m
    curben-pup: 192-0, 27m
    adguard-annoyance: 60058-5653, 1d.11h.7m
    adguard-social: 18587-1677, 1d.11h.6m
    fanboy-thirdparty_social: 68-1, 7d.13h.14m
    fanboy-annoyance: 81291-69493, 7d.13h.14m
    fanboy-cookiemonster: 41697-17085, 7d.13h.14m
    fanboy-social: 23396-13727, 6d.12h.9m
    ublock-annoyances: 4878-7, 1d.11h.5m
    dpollock-0: 11389-492, 7d.13h.14m
    ALB-0: 273-7, 26m
    ara-0: 2596-241, 25m
    BGR-0: 1091-19, 1d.11h.4m
    CHN-0: 28943-1340, 1d.11h.3m
    CZE-0: 733-40, 24m
    [28 lists not shown]: [too many]
  default: 
    user-filters: 1-0, never
    ublock-filters: 33931-670, 1d.11h.16m
    ublock-badware: 4361-0, 1d.11h.15m
    ublock-privacy: 288-1, 1d.11h.14m
    ublock-abuse: 76-0, 1d.11h.13m
    ublock-unbreak: 1890-1, 1d.11h.12m
    ublock-quick-fixes: 426-0, 30m
    easylist: 62008-18383, 33m
    easyprivacy: 30807-1946, 32m
    urlhaus-1: 9527-0, 29m
    plowe-0: 3675-3, 7d.13h.13m
    spa-1: 4772-201, 1d.10h.54m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2335 ms (selfie)
  maxAssetCacheWait: 2490 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    consensu.org: 1
    doubleclick.net: 6
    gemius.pl: 1
    getclicky.com: 1
    googletagmanager.com: 1
    megafin.pt: 5
    sapo.pt: 1
    wonderpush.com: 2
```
</details>

**Comment by okiehsch** [comment]
`jornaleconomico.pt##+js(acis, jQuery, wow-modal-overlay)`

**Comment by Sergey-Lyapin** [comment]
Hi @okiehsch

Fixed: https://github.com/AdguardTeam/AdguardFilters/commit/c1801c254b1f992f3f39dbe1e7ad69d0335c4c7c
