### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#15402]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/ads/preferences/ad_topics/`

### Category

breakage

### Describe the issue

ad topics frame not showing.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/197693581-3c3ddd01-74b8-401f-8f73-e978303c0898.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 116719
  cosmetic: 147242
  scriptlet: 34478
  html: 796
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 64394-5262, 3h.57m
    adguard-spyware: 35833-15561, 3h.57m
    adguard-spyware-url: 793-3, 3h.56m
    adguard-annoyance: 60126-1548, 3h.56m
    adguard-social: 18615-25, 3h.56m
  default: 
    user-filters: 67-0, never
    ublock-filters: 33848-75, 3h.57m
    ublock-badware: 4356-0, 3h.57m
    ublock-privacy: 288-0, 3h.57m
    ublock-abuse: 76-0, 3h.57m
    ublock-unbreak: 1894-1, 3h.57m
    ublock-quick-fixes: 426-0, 3h.57m
    easylist: 62279-366, 3h.57m
    easyprivacy: 30807-1190, 3h.56m
    TUR-0: 9607-15, 3h.56m
filterset (user): [array of 71 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 670 ms (selfie)
  maxAssetCacheWait: 263 ms
  unsuspendAfter: 116 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    instagram.com: 7
    facebook.net: 1
```
</details>

**Comment by krystian3w** [comment]
I think this can block iframe in settings:

```adb
.com/ads/$subdocument,domain=~developers.google.com|~sabotage-films.com
```

match:
```
https://xweb.instagram.com/ads/preferences/ad_topics/?__coig_login=1&cquick=jsc_ig_0&ctarget=https%3A%2F%2Fwww.instagram.com
                      ^^^^^^^^^
                      |||||||||
```
