### ISSUE TITLE
console.cloud.google.com: breakage

### ISSUE THREAD

**Issue by zfjvergara** [uBlockOrigin/uAssets#15406]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://console.cloud.google.com/bigquery?project=csdataanalysis&ws=!1m5!1m4!4m3!1scsdataanalysis!2sentities!3sentity_web_beacon`

### Category

breakage

### Describe the issue

I'm using BigQuery and everything works fine until we open a table named "entity_web_beacon" and the request gets blocked by uBlock Origin. When I disable uBlock and refresh the page, it works fine, but if I re-enable uBlock and refresh te page, the issue appears again. 

I checked on the network tab, and the request for this table in particular get blocked by the ad blocker. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86099
  cosmetic: 38705
  scriptlet: 18207
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62001-53, 6d.16h.22m
    easyprivacy: 30763-1170, 6d.16h.21m
    plowe-0: 3671-865, 1d.1h.45m
    ublock-abuse: 76-0, 1d.1h.48m
    ublock-badware: 4352-104, 1d.1h.44m
    ublock-filters: 33193-109, 1d.1h.43m
    ublock-privacy: 260-1, 1d.1h.47m
    ublock-quick-fixes: 437-32, 1d.1h.40m
    ublock-unbreak: 1876-42, 1d.1h.42m
    urlhaus-1: 8916-0, 1d.1h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1252 ms (selfie)
  maxAssetCacheWait: 688 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google.com: 1
    google-analytics.com: 7
```
</details>

**Comment by okiehsch** [comment]
> the request for this table in particular get blocked by the ad blocker.

We would need the exact name of that request to fix the issue. 
You can use the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find it.
