### ISSUE TITLE
tirexo.blue: popups

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15407]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tirexo.blue/`

### Category

popups

### Describe the issue

For some time now, this site has been rotten with popups from random domain names... It's hellish. It would be good to clean up and add to the French list.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/197844497-7e5dc557-38b2-48aa-8c34-f97498c92fc9.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 559427
  cosmetic: 149655
  scriptlet: 37099
  html: 0
listset (total-discarded, last updated): 
    RUS-0: 40422-214, 1d.11h.55m
    adguard-generic: 64205-884, 1d.11h.55m
    adguard-mobile: 8174-65, 1d.11h.55m
    adguard-spyware: 33737-2588, 1d.11h.55m
    adguard-spyware-url: 793-126, 1d.11h.55m
    curben-phishing: 120766-0, 8h.9m
    curben-pup: 192-1, 8h.7m
    fanboy-cookiemonster: 41997-114, 1d.11h.55m
    ublock-annoyances: 4857-83, 1d.11h.55m
  default: 
    FRA-0: 31230-58, 1d.11h.55m
    easylist: 62256-1031, 1d.11h.55m
    easyprivacy: 30802-13042, 1d.11h.55m
    plowe-0: 3671-1043, 1d.11h.55m
    ublock-abuse: 76-2, 1d.11h.55m
    ublock-badware: 4357-258, 1d.11h.55m
    ublock-filters: 33193-3621, 1d.11h.55m
    ublock-privacy: 260-45, 1d.11h.55m
    ublock-quick-fixes: 420-32, 8h.3m
    ublock-unbreak: 1877-95, 1d.11h.55m
    urlhaus-1: 9527-7, 8h.1m
filterset (user): [array of 2092 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 10 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 553 ms (selfie)
  maxAssetCacheWait: 394 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    answeredthec.xyz: 3
    appalspowters.com: 1
    rhiospsea.one: 7
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 ping for Adguard

PS: There is also tracking coming from `stats.tirexo.blue`
