### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by 19Gerhard85** [uBlockOrigin/uAssets#15404]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.derstandard.at/`

### Category

detection

### Describe the issue

The website detects uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/1492978/197738534-ee25b351-4826-4d2c-a44e-c4e21b4dacb8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88255
  cosmetic: 42424
  scriptlet: 18203
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33854-76, 20m
    ublock-badware: 4346-0, 19m
    ublock-privacy: 288-0, 23h.18m
    ublock-abuse: 76-0, 23h.17m
    ublock-unbreak: 1894-0, 18m
    ublock-quick-fixes: 441-0, 23h.15m
    easylist: 62002-612, 5d.4h.13m
    easyprivacy: 30774-1717, 5d.4h.12m
    urlhaus-1: 8916-0, 23h.14m
    plowe-0: 3671-3, 19h.12m
    DEU-0: 5983-2, 23h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 858 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    cleverpush.com: 3
    cxense.com: 3
    googletagmanager.com: 3
    iocnt.net: 6
    npttech.com: 3
    piano.io: 2
    staticfiles.at: 6
```
</details>

**Comment by okiehsch** [comment]
Added fix only works with chromium.

**Comment by okiehsch** [comment]
Hm, now it works with Firefox too.
@19Gerhard85 is the issue fixed if you update the `uBO-filters`?

**Comment by 19Gerhard85** [comment]
> Hm, now it works with Firefox too. @19Gerhard85 is the issue fixed if you update the `uBO-filters`?

Works like a charm, thank you very much!

**Comment by paksnuk** [comment]
Chrome and Firefox work for me, but Edge doesn't.

**Comment by Esokrates** [comment]
Could you check whether live articles (https://www.derstandard.at/live, e.g. https://www.derstandard.at/jetzt/livebericht/2000140130935/oevp-korruptions-u-ausschusspolizeidirektor-und-nehammer-vertrauter-im?responsive=false) work for you?
Works for me in Firefox (Ubuntu), however with brave on android they fail to load, see the linked issue above this comment.
It seems brave uses uassets as well (see https://github.com/brave/adblock-resources/blob/master/filter_lists/default.json), so this is the reason I report this here as well.

**Comment by Esokrates** [comment]
@okiehsch On Firefox (Android) with ublock origin, live articles work initially but after some time the wall shows up again (only for live articles though):

![photo_2022-10-27_13-38-58](https://user-images.githubusercontent.com/17780185/198274709-cc6b75a3-075e-424f-bfb7-7a60594f5606.jpg)

After that happens I can't past the wall for live articles except if I delete all app data, reinstall ublock origin and visit the site again. Deleting cookies / browsing history does not seem enough.

**Comment by Esokrates** [comment]
@okiehsch Okay it seems some recent filter update broke the live articles. On Firefox mobile starting from scratch, installing ublock origin everything works fine. As soon as all the filter lists are refreshed, live articles do not work and the wall shows up.

**Comment by okiehsch** [comment]
> Chrome and Firefox work for me, but Edge doesn't.

The filter works with Edge too on my end, I can reproduce the anti adblock message only if I remove it.

>  live articles

I can reproduce the issue on live articles with all browsers.

**Comment by okiehsch** [comment]
Even worse my filter actually breaks site functionality on live articles.

**Comment by okiehsch** [comment]
Can you test adding
````
derstandard.at#@#+js(abort-current-script, document.createElement, Adblocker)
@@||derstandard.at^$ghide
@@||npttech.com/advertising.js$script,domain=derstandard.at
````
on articles, live and not live.

**Comment by Esokrates** [comment]
> Can you test adding
> 
> ```
> derstandard.at#@#+js(acs, document.createElement, Adblocker)
> @@||derstandard.at^$ghide
> @@||npttech.com/advertising.js$script,domain=derstandard.at
> ```
> 
> on articles, live and not live.

At least on Firefox Android I can't even get to normal articles with that.

**Comment by okiehsch** [comment]
>  I can't even get to normal articles with that.

Meaning you get the anti adblock message?

**Comment by Esokrates** [comment]
> > I can't even get to normal articles with that.
> 
> Meaning you get the anti adblock message?

Yes, exactly.

**Comment by Esokrates** [comment]
@okiehsch Those rules work well on a fresh start (meaning deleting all app data and reinstalling ublock origin). As soon as I refresh all filter lists I get the anti adblock message on all articles.

**Comment by Esokrates** [comment]
@okiehsch Also happens, when toggling "Desktop site", so might not be specific to the mobile version.

**Comment by okiehsch** [comment]
> As soon as I refresh all filter lists I get the anti adblock message on all articles.

I can't reproduce that, it still works after updating all lists on my end.
What lists are you using?

My filter lists.
![image](https://user-images.githubusercontent.com/16838044/198292599-9aa64bd2-dedb-4bb0-b7c8-8fafdc2b5c64.png)

**Comment by Esokrates** [comment]
Fresh start on Android  (deleting app data, freshly installing ublock origin):

![photo_2022-10-27_15-10-10](https://user-images.githubusercontent.com/17780185/198293594-9f61f37b-81b2-4b0f-9036-60d711129d36.jpg)

With this everything works out of the box (including live articles, no site breakage anywhere). Adding the 3 lines of code you asked me to test works as well.

Fresh start on Android, but with refreshing all filters:

![photo_2022-10-27_15-12-43](https://user-images.githubusercontent.com/17780185/198293999-ac26fcf3-77df-4089-b5f7-e1de37254502.jpg)

In this state the normal articles work, but the live articles are broken. When adding your 3 lines to the custom filters the anti adblock wall shows up instantly on every article.

**Comment by okiehsch** [comment]
Hm, we pretty much have the same lists with widely different results.
Let's wait for others to chime in.

**Comment by okiehsch** [comment]
> makes the issue worse on Firefox Android.

Ok, that makes much more sense, i.e. it really should work on a desktop.

**Comment by Esokrates** [comment]
@okiehsch Yes, but the outdated filters work on both platforms without any adaptions with the current site. Could you maybe find out which version of the filters they ship and find out the difference?

**Comment by okiehsch** [comment]
Well, as you can see in oru screenshots the only difference is that you use `adguard-mobile`, I looked at that list and it has no derstandard-specific filters in it.

**Comment by okiehsch** [comment]
> the outdated filters work on both platforms 

To be clear on my end I see no difference between outdated and up to date filter lists.

**Comment by Esokrates** [comment]
> Well, as you can see in our screenshots the only difference is that you use `adguard-mobile`, I looked at that list and it has no derstandard-specific filters in it.

Yes I noted that already, tried without that list, did not make any difference.

Now I have found a way to make the site work with the latest filters on mobile (both live and non live articles): Disable uBlock Unbreak filters (how ironic) and add your 3 lines of code to the custom filters.

**Comment by okiehsch** [comment]
> (how ironic)

😁 
I see no derstandard filters in that list.

**Comment by Esokrates** [comment]
> grin I see no derstandard filters in that list.

Toggling the list on with your 3 lines of code, immediately leads to the anti adblock message, toggling off again and every article on the site works fine.
Maybe it's no specific derstandard domain filter, but something the adblock detection script on the site uses to detect the adblocker?

**Comment by okiehsch** [comment]
> Maybe it's no specific derstandard domain filter

Well, yes but the "problem" is that the "unbreak" list does not add blocking filters, it's mostly exceptions and redirections, meaning it basically never adds something to detect.

There is also the fact that it makes no difference on my end, so...

**Comment by Esokrates** [comment]
@okiehsch On Android I had dns.adguard.com set as my DNS resolver. Removing that, makes your 3 lines work together with the uBlock Unbreak filters and your 3 lines of code.

**Comment by okiehsch** [comment]
Ok, I will change the fix.

**Comment by gorhill** [comment]
> I had dns.adguard.com set as my DNS resolver.

Ugh... That's why we ask:

> - [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) **(also mind browser built-in blockers)**

**Comment by Esokrates** [comment]
> > I had dns.adguard.com set as my DNS resolver.
> 
> Ugh... That's why we ask:
> 
> > * [x]  I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) **(also mind browser built-in blockers)**

Yeah, this was a set and forget thing a long time ago, I just figured out that I had changed the dns resolver when trying to figure out the difference between mobile and desktop. Sorry for the noise and thanks guys!

**Comment by Esokrates** [comment]
@gorhill Would you mind adding "mind dns servers" as well to the checklist so that this does not happen again to anyone?
