### ISSUE TITLE
metasrc.com: ads

### ISSUE THREAD

**Issue by NielsVanderstraeten** [uBlockOrigin/uAssets#15400]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.metasrc.com/aram/na/champion/amumu`

### Category

ads

### Describe the issue

Leftover empty elements stating 'Sponsored content' and 'Advertisement' remains. Issue persists on multiple webpages with similar layout, eg:

- Different region (euw instead of na): https://www.metasrc.com/aram/euw/champion/amumu
- Different champion: https://www.metasrc.com/aram/na/champion/varus
- Different mode: https://www.metasrc.com/5v5/champion/akshan/mi

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://user-images.githubusercontent.com/6737818/197635498-733e2880-207f-4798-8bee-5b90ced4f5e0.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 87164
  cosmetic: 39959
  scriptlet: 18047
  html: 0
listset (total-discarded, last updated): 
  added: 
    NLD-0: 2472-12, now
  default: 
    user-filters: 0-0, never
    easylist: 62279-56, now
    easyprivacy: 30807-1171, now
    plowe-0: 3671-865, now
    ublock-abuse: 76-0, now
    ublock-badware: 4342-109, now
    ublock-filters: 33143-179, now
    ublock-privacy: 260-1, now
    ublock-unbreak: 1879-56, now
    urlhaus-1: 8844-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 53 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 369 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    riotgames.com: 1
    vntsm.com: 1
```
</details>

**Comment by gorhill** [comment]
Should be fixed in EasyList:

    metasrc.com###header_wrapper
    metasrc.com###sidebar-wrapper

**Comment by stephenhawk8054** [comment]
@ryanbr
