### ISSUE TITLE
UIkit alerts falsely blocked

### ISSUE THREAD

**Issue by Bloemendaal** [uBlockOrigin/uAssets#1540]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
[UIkit alert](https://getuikit.com/docs/alert)

### Describe the issue
All alerts seem to be blocked, including the uk-alert attribute and uk-alert class.

### Versions

- Browser/version: Chrome 64.0.3282.140 (Official build) (64-bits)
- uBlock Origin version: 1.15.2

### Settings
154.400 networkfilters ＋ 92.217 cosmetic filters from:
uBlock filters​​​​​ 3.987 van 3.987 gebruikt​​​​
uBlock filters – Badware risks​​​​​ 7 van 7 gebruikt​​​​
uBlock filters – Privacy ​​​​​65 van 65 gebruikt​​​​
uBlock filters – Resource abuse ​​​​​194 van 196 gebruikt​​​​
uBlock filters – Unbreak ​​​​​285 van 285 gebruikt​​​​

Advertenties (3)
Adblock Warning Removal List ​​​​​390 van 400 gebruikt​​​​
Adguard Base Filters​​​​​ 13.473 van 14.147 gebruikt​​​​
EasyList ​​​​​79.505 van 80.137 gebruikt​​​​

Privacy (2)
EasyPrivacy​​​​​ 12.941 van 14.224 gebruikt​​​​
Fanboy’s Enhanced Tracking List​​​​​ 2.339 van 2.376 gebruikt​​​​

Malwaredomeinen (5)
Malvertising filter list by Disconnect ​​​​​251 van 4.567 gebruikt​​​​
Malware Domain List​​​​​ 1.129 van 1.146 gebruikt​​​​
Malware domains​​​​​ 15.028 van 15.040 gebruikt​​​​
Malware filter list by Disconnect​​​​​ 169 van 1.831 gebruikt​​​​
Spam 404​​​​​6.312 van 6.312 gebruikt​​​​

Storende elementen (5)
Adguard’s Annoyance List ​​​​​8.562 van 10.388 gebruikt​​​​
Fanboy’s Annoyance List ​​​​​8.851 van 35.119 gebruikt​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​ 68 van 68 gebruikt​​​​
Fanboy’s Cookiemonster List ​​​​​8.462 van 8.468 gebruikt​​​​
Fanboy’s Social Blocking List​​​​​ 17.775 van 17.802 gebruikt​​​​

Multifunctioneel (4)
Dan Pollock’s hosts file​​​​​ 9.540 van 13.278 gebruikt​​​​
hpHosts’ Ad and tracking servers​​​​​ 43.411 van 47.539 gebruikt​​​​
MVPS HOSTS​​​​​ 12.329 van 12.835 gebruikt​​​​
Peter Lowe’s Ad and tracking server list ​​​​​2.578 van 2.583 gebruikt​​​​

**Comment by okiehsch** [comment]
`##.uk-alert` in `Fanboy’s Annoyance List` causes your issue.
`getuikit.com#@#.uk-alert` fixes it, report it here: https://forums.lanik.us/viewforum.php?f=64
