### ISSUE TITLE
mail.google.com: breakage

### ISSUE THREAD

**Issue by GlenMerlin** [uBlockOrigin/uAssets#15408]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

breakage

### Describe the issue

If you start writing a new email and set the subject line to contain `ads` clicking on the message content field of the email will cause the email you're writing to disappear and not reopen

Steps to Reproduce:

- Create a new email
- Set the subject line to "ads"
- Click the content field to start typing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 86030
  cosmetic: 38708
  scriptlet: 18199
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33940-33, 1d.2h.35m
    ublock-badware: 4346-0, 1d.2h.34m
    ublock-privacy: 282-0, 8d.1h.43m
    ublock-abuse: 76-0, 8d.1h.42m
    ublock-unbreak: 1892-0, 1d.2h.33m
    ublock-quick-fixes: 431-32, 1d.2h.32m
    easylist: 62003-592, 20h.51m
    easyprivacy: 30777-1722, 20h.50m
    urlhaus-1: 8844-0, 1d.2h.31m
    plowe-0: 3675-3, 8d.1h.40m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 425 ms (selfie)
  maxAssetCacheWait: 160 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    google.com: 27
```
</details>

**Comment by gwarser** [comment]
I cannot reproduce. Maybe different Gmail configuration.

**Comment by GlenMerlin** [comment]
> I cannot reproduce. Maybe different Gmail configuration.

Can you try with a capital A?

Ads

not ads

only works with the capital for me

**Comment by gwarser** [comment]
Filter
`google.com##div[aria-label="Ads"]`
Filter list
EasyList
