### ISSUE TITLE
nexusmods.com: breakage

### ISSUE THREAD

**Issue by DankRafft** [uBlockOrigin/uAssets#15415]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nexusmods.com/fallout4/mods/edit/?id=65462&game_id=1151&step=details`

### Category

breakage

### Describe the issue

When uBlock's own filter list is active certain elements like buttons and other interactive elements on NexusMods don't work anymore. Those elements are accessed on a mod page's backend where mod authors configure their uploads.

This problem arised a couple of days ago when the filter lists got an update. Loading an older/previous version or disabling them makes the interactive elements appear and work again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 90042
  cosmetic: 42162
  scriptlet: 17972
  html: 795
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33424-64, 2m
    ublock-badware: 4356-0, 4m
    ublock-privacy: 288-0, 4m
    ublock-abuse: 76-0, 4m
    ublock-unbreak: 1885-0, 4m
    easylist: 62335-639, 4m
    easyprivacy: 30811-1732, 4m
    urlhaus-1: 10311-0, 4m
    plowe-0: 3671-3, 4m
    DEU-0: 5990-2, 4m
    ublock-quick-fixes: 424-0, 4m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 282 ms (selfie)
  maxAssetCacheWait: 488 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    nexusmods.com: 2
    googletagmanager.com: 1
    hotjar.com: 1
    quantserve.com: 1
```
</details>

**Comment by okiehsch** [comment]
Does it work if you add
````
nexusmods.com#@#+js(acs, document.getElementById, true)`
````
to your filter list?

**Comment by DankRafft** [comment]
Yes, that fixed it. Thanks.

**Comment by FelesNoctis** [comment]
Adding that line to My Filters does not seem to fix the issue on my end.

[My Filter](https://i.imgur.com/gJYgXPU.png)
[Filters Enabled (purged and reupdated](https://i.imgur.com/0f4HiQl.png)
[Nexusmods page: still broken](https://i.imgur.com/flhoJNk.png)

Anything related to overlays or dropdowns is nonfunctional unless the base "uBlock filters" entry is disabled.
