### ISSUE TITLE
lazada.sg: breakage

### ISSUE THREAD

**Issue by somik123** [uBlockOrigin/uAssets#15414]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lazada.sg/products/konco-12kg-large-food-storage-container-cereal-bean-container-sealed-box-with-measuring-cup-kitchen-rice-box-storage-box-automatic-cereal-dispenser-box-moisture-proof-sealed-cereal-food-box-grain-bin-rice-container-i1189572610-s4753856457.html?clickTrackInfo=query%253A%253Bnid%253A1189572610%253Bsrc%253AlazadaInShopSrp%253Brn%253A053f4c809fb89bcbd652c2182eafd5c7%253Bregion%253Asg%253Bsku%253A1189572610_SGAMZ%253Bprice%253A32.99%253Bclient%253Adesktop%253Bsupplier_id%253A100075620%253Basc_category_id%253A10000631%253Bitem_id%253A1189572610%253Bsku_id%253A4753856457%253Bshop_id%253A87984&freeshipping=0&fs_ab=1&fuse_fs=0&mp=1&spm=a2o42.seller.list.i104.1ae25c59nBmt9X`

### Category

breakage

### Describe the issue

Videos on the listing page does not play.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 93173
  cosmetic: 111109
  scriptlet: 19911
  html: 793
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 81477-65411, 1d.1h.39m
    fanboy-cookiemonster: 41869-92, 1d.1h.40m
    fanboy-social: 23390-8, 5d.5h.42m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33925-67, 2d.13h.51m
    ublock-badware: 4356-0, 2d.13h.50m
    ublock-privacy: 282-0, 2d.17h.53m
    ublock-abuse: 76-0, 2d.17h.52m
    ublock-unbreak: 1889-0, 2d.13h.49m
    ublock-quick-fixes: 426-0, 5h.17m
    easylist: 62001-618, 6d.16h.52m
    easyprivacy: 30774-1709, 6d.16h.51m
    urlhaus-1: 8916-0, 5h.16m
    plowe-0: 3673-3, 12d.23h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 896 ms (selfie)
  maxAssetCacheWait: 175 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    alicdn.com: 3
    aliyuncs.com: 12
    mmstat.com: 9
    taobao.com: 3
    ucweb.com: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Are you blocking audio and video in Firefox settings?

![image](https://user-images.githubusercontent.com/66517106/197947193-f81e6db1-a454-4efd-979d-0226b2a05e3b.png)

**Comment by somik123** [comment]
Hmm, no, but seems like some issue with my NS resolution. Not a plugin issue.
