### ISSUE TITLE
olympusscanlation.com: detection

### ISSUE THREAD

**Issue by konsowsz** [uBlockOrigin/uAssets#15418]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://olympusscanlation.com/manga/el-mejor-disenador-inmobiliario/capitulo-11/`

### Category

detection

### Describe the issue

This page detect this extension(?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 91801
  cosmetic: 32476
  scriptlet: 18480
  html: 795
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34018-354, 3d.10h.11m
    ublock-badware: 4407-0, 3d.7h.24m
    ublock-privacy: 282-1, 3d.7h.27m
    ublock-abuse: 76-0, 3d.7h.26m
    ublock-unbreak: 1894-0, 3d.7h.25m
    ublock-quick-fixes: 427-0, 6h.58m
    adguard-mobile: 8173-168, 3d.10h.12m
    easylist: 62002-17975, 6d.40m
    easyprivacy: 30781-1732, 6d.39m
    urlhaus-1: 10523-0, 6h.57m
    plowe-0: 3675-3, 7d.7h.35m
    spa-0: 3352-237, 6h.56m
    spa-1: 4772-198, 3d.12h.1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4552 ms (selfie)
  maxAssetCacheWait: 262 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adrecover.com: 1
    disq.us: 1
    disqus.com: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
    papayads.net: 6
    runative-syndicate.com: 1
    viglink.com: 2
```
</details>

**Comment by okiehsch** [comment]
`olympusscanlation.com##+js(acs, document.getElementById, 'block')`

**Comment by okiehsch** [comment]
Hm, that filter is no longer valid, I don't see any detection script atm.
I will close.
