### ISSUE TITLE
joyn.de: ads

### ISSUE THREAD

**Issue by palmengladosTV** [uBlockOrigin/uAssets#15410]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.joyn.de/`

### Category

ads

### Describe the issue

Shows ads when streaming shows etc.
If you try to block them manually the screen just goes dark and the player isnt working.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88351
  cosmetic: 42473
  scriptlet: 18190
  html: 796
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33892-65, 3d.22h.44m
    ublock-badware: 4408-0, 3d.5h.42m
    ublock-privacy: 288-0, 1d.6h.41m
    ublock-abuse: 76-0, 1d.10h.47m
    ublock-unbreak: 1888-0, 3d.22h.45m
    ublock-quick-fixes: 426-0, 6h.45m
    easylist: 62008-613, 2h.43m
    easyprivacy: 30807-1717, 2h.42m
    urlhaus-1: 8916-0, 6h.44m
    plowe-0: 3671-3, 1d.10h.45m
    DEU-0: 5990-2, 6h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1086 ms (selfie)
  maxAssetCacheWait: 265 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    braze.eu: 1
    googletagmanager.com: 1
    ioam.de: 1
    iocnt.net: 1
    launchdarkly.com: 8
    myfonts.net: 1
    nmrodam.com: 1
    optimizely.com: 1
    sentry.io: 2
    theadex.com: 1
    usercentrics.eu: 1
    vercel-insights.com: 3
    youborafds01.com: 2
```
</details>

**Comment by okiehsch** [comment]
No ads on the shows that need no account on my end.

**Comment by palmengladosTV** [comment]
I've resetted the addon and it seems like its working now. No idea why it wasnt working before since I didnt change anything.
