### ISSUE TITLE
app.jobnimbus.com: breakage

### ISSUE THREAD

**Issue by austinzuffi** [uBlockOrigin/uAssets#15426]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.jobnimbus.com/board/l9fwyu7re3e9bl1j984wijc`

### Category

breakage

### Describe the issue

some update today (10/26) broke jobnimbus, our crm, from fully loading

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 87456
  cosmetic: 38704
  scriptlet: 18195
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33916-54, 3d.2h.35m
    ublock-badware: 4356-0, 3d.2h.34m
    ublock-privacy: 282-0, 7d.4h.15m
    ublock-abuse: 76-0, 7d.4h.10m
    ublock-unbreak: 1889-0, 3d.2h.33m
    easylist: 62003-607, 1d.4h.34m
    easyprivacy: 30807-1707, 1d.4h.33m
    urlhaus-1: 10252-0, 20h.31m
    plowe-0: 3671-3, 3d.2h.37m
    ublock-quick-fixes: 426-0, 20h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1890 ms (selfie)
  maxAssetCacheWait: 965 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    googletagmanager.com: 1
    hs-analytics.net: 1
    hs-banner.com: 1
    hsleadflows.net: 1
    hubspot.com: 2
    logrocket.io: 2
    lr-ingest.io: 1
    pendo.io: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check if adding these filters works?

```adb
@@||cdn.logrocket.io/LogRocket.min.js$script,domain=webappui.jobnimbus.com
@@||cdn.logrocket.io/logger-1.min.js$script,domain=webappui.jobnimbus.com
```
