### ISSUE TITLE
bitcotasks.com: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15428]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bitcotasks.com/detected.html`

### Category

detection

### Describe the issue

detection adblock if open task in bitcotasks.com, but if not open task no detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 88033
  cosmetic: 38367
  scriptlet: 17870
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 19-0, never
    easylist: 62357-53, now
    easyprivacy: 30816-1170, 19m
    plowe-0: 3671-865, 19m
    ublock-abuse: 76-0, 19m
    ublock-badware: 4352-110, 19m
    ublock-filters: 32463-139, 19m
    ublock-privacy: 260-1, 19m
    ublock-quick-fixes: 419-21, 19m
    ublock-unbreak: 1872-42, 19m
    urlhaus-1: 10523-0, 19m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2221 ms
  maxAssetCacheWait: 1047 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    coinzillatag.com: 2
    doubleclick.net: 2
    googletagmanager.com: 4
    snobdomobeyeo.com: 2
    wtg-ads.com: 2
```
</details>

**Comment by hunterkais** [comment]
if i use in my filter like this, 
techydino.net##+js(nostif, showModal)
mdn.lol##+js(acis, onload, adblock)
mdn.lol##+js(nowoif)
||coinzillatag.com^$script,redirect-rule=noopjs
mdn.lol##input:style(display: block !important)
mdn.lol##.g-recaptcha:upward(div):style(display: block !important)
bitcotasks.com,mdn.lol,techydino.net##[class^="floating-banner"]

bitcotasks.com not detection, but for another website not normal (not detection but still see ads) 
how to fix that?

**Comment by stephenhawk8054** [comment]
> detection adblock if open task in bitcotasks.com

What do you mean by `open task`?

![image](https://user-images.githubusercontent.com/66517106/198234268-38576830-ad33-4586-b106-7450fcfc27f7.png)

**Comment by hunterkais** [comment]
Like this

**Comment by stephenhawk8054** [comment]
Can you upload directly on github? Github has some issues with images via mail.

**Comment by hunterkais** [comment]
if i use in my filter like this,
techydino.net##+js(nostif, showModal)
mdn.lol##+js(acis, onload, adblock)
mdn.lol##+js(nowoif)
||coinzillatag.com^$script,redirect-rule=noopjs
mdn.lol##input:style(display: block !important)
mdn.lol##.g-recaptcha:upward(div):style(display: block !important)
bitcotasks.com,mdn.lol,techydino.net##[class^="floating-banner"]
![no detection](https://user-images.githubusercontent.com/114012899/198238332-e3fe45e5-c20c-403c-bcdf-b1a9773dd501.png)


but if i not use my filter
![detection](https://user-images.githubusercontent.com/114012899/198238383-5f0f33ba-55db-4792-acf8-da409d8b7fe8.png)

**Comment by stephenhawk8054** [comment]
I mean the steps to reproduce the anti-adblock. I go to `https://bitcotasks.com` and it shows the dashboard, but I can't reproduce any anti-adblock on the page.

**Comment by hunterkais** [comment]
of course can't reproduce any anti-adblock on that page. if you open that website.
but if i open bitcotasks.com offerwall in other website. he can detect adblock.
if you want to be clearer, maybe you can go to the hatecoin.me (one of the issues I've made and you have solved, #15289 as completed via e15d841) website there is an offerwall bitcotasks.com, you will find the detection.

**Comment by stephenhawk8054** [comment]
> maybe you can go to the hatecoin.me

Please give the websites and describe the steps to reproduce in details next time.

> of course can't reproduce any anti-adblock on that page. if you open that website.

We can't read minds so we can't know what your `of course` is. Your description of the reproduction steps is what helps us/you solve the issues.

**Comment by stephenhawk8054** [comment]
Can you check if this works?

```adb
*$script,redirect-rule=noopjs,domain=bitcotasks.com
```

**Comment by hunterkais** [comment]
yes, thats works, can you put it in the ublock orgin filter update?
thanks

**Comment by blader-render** [comment]
This issue already detection adblock again, maybe can you fix it? Thanks.

**Comment by blader-render** [comment]
This issue already detection adblock again, maybe can you fix it? Thanks.

**Comment by blader-render** [comment]
> Can you check if this works?
> 
> ```adb
> *$script,redirect-rule=noopjs,domain=bitcotasks.com
> ```

This issue already detection adblock again, maybe can you fix it? Thanks.

**Comment by stephenhawk8054** [comment]
> `https://bitcotasks.com//shortlink/bgzyczaqzva9wy2rwt77fgfxqyg7kz/94483/8pa4rb87mlmdvj4mgfoiovwhxrokrjf1/7213cf2a2b2c57ff6dd05eaa810f46e6f510ad183cb875f8fef1152034864f27`

The link redirects to `https://bitcotasks.com/` without any anti-adblock for me.

**Comment by king-iskan** [comment]
> > `https://bitcotasks.com//shortlink/bgzyczaqzva9wy2rwt77fgfxqyg7kz/94483/8pa4rb87mlmdvj4mgfoiovwhxrokrjf1/7213cf2a2b2c57ff6dd05eaa810f46e6f510ad183cb875f8fef1152034864f27`
> 
> The link redirects to `https://bitcotasks.com/` without any anti-adblock for me.

Yeah, redirect to that site, shouldn't be there.  should be one of the shortlinks.  Because allow adblock, then redirect to bitcotasks

**Comment by stephenhawk8054** [comment]
It redirects to the homepage even when I don't use any extensions. Video: https://user-images.githubusercontent.com/66517106/226821107-bc6a2424-982f-4253-bca3-1699aac64360.mp4

**Comment by king-iskan** [comment]
I think it's difficult to give an example of a link so it can be reproduced, because the link expires token.  so if you want the original link, we must first enter one of the sites that has a bitcotasks.com offerwall, sorry it's a bit difficult to explain.
Maybe this video can be explain
Video first not allow adblock

https://user-images.githubusercontent.com/120553425/226832798-a1e3bc71-6bb7-43e5-a8b9-163599d22363.mp4

Video second allow adblock

https://user-images.githubusercontent.com/120553425/226832881-61f08680-9645-4e8a-a539-56a0f7a06353.mp4

**Comment by king-iskan** [comment]
Try this link 
https://bitcotasks.com//shortlink/lqnozcdw9hbwceqy6h0tjruof9p9r3/7106/ln6br3jumte9rueglbxuycjd1ofh2efp/3d79c8d48fab505f5d5ba821695eb811cac07b1acfffb03cbb85d8924ab535e5

**Comment by Sandor-Helper** [comment]
This link will be more universal:
`https://bitcotasks.com//shortlink/load/141`

**Comment by Sandor-Helper** [comment]
Sometimes it shows this:
![image_2023_03_30T06_10_39_794Z](https://user-images.githubusercontent.com/31479044/228776043-a3bdc9ba-db1b-46e6-a716-b521551c358b.png)
Refreshing the page often helps (if you have time before it redirects to the home page)

Log is here:
`https://www61.zippyshare.com/v/4ucLTV90/file.html`

**Comment by king-iskan** [comment]
> > `https://bitcotasks.com//shortlink/load/141`
> 
> This link just stucks at the end even when I disable uBO.

@stephenhawk8054 
Let me help explain the problem and post a working link,
For problem : sometime yeah, still detect adblock like the screenshot that @Sandor-Helper  sent. Special use in FF android. But in chromium based no have issue.
This link for try reproduce
https://bitcotasks.com//shortlink/u3hegbui27cpoh60oaiq00vjonn1m3/30589/4l9iaoxn7cjgw6rekis5y5zborv1jlgq/1824a7c4b58582dc7f3d6d3cf9fa9b6f9a7f99d04306f9d6c9805ae0d2073ca6

**Comment by mapx-** [comment]
off-topic: @king-iskan when you post links => make them unclickable please.

**Comment by king-iskan** [comment]
> 

Off-topic: @mapx- How to?  I can't

**Comment by krystian3w** [comment]
Or add to new line and preceded by 4 spaces:

   http due punto bara bara allegro punto pl bara blah blah blah punto html
