### ISSUE TITLE
web.de: detection

### ISSUE THREAD

**Issue by rotgruengelb** [uBlockOrigin/uAssets#15422]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://web.de/fairplay/?section=fairplay`

### Category

detection

### Describe the issue

Origin of the issue page: `https://web.de`
Detects uBlock Origin/general AdBlockers when Logging in, Redirects to `https://web.de/fairplay/?section=fairplay`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-10-26 203056](https://user-images.githubusercontent.com/75038404/198107517-acf88779-8d47-457c-bc2f-f2e8e6038132.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88277
  cosmetic: 42478
  scriptlet: 18197
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33914-33, 3d.22h.28m
    ublock-badware: 4356-0, 2h.5m
    ublock-privacy: 282-0, 5d.22h.10m
    ublock-abuse: 76-0, 5d.22h.9m
    ublock-unbreak: 1889-0, 3d.18h.27m
    ublock-quick-fixes: 426-21, 6h.16m
    easylist: 62003-612, 1d.17h.28m
    easyprivacy: 30781-1717, 5d.22h.8m
    urlhaus-1: 8916-0, 6h.15m
    plowe-0: 3671-3, 4d.22h.29m
    DEU-0: 5990-13, 6h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3580 ms (selfie)
  maxAssetCacheWait: 510 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    web.de: 8
    g-ha-1und1.de: 3
    ui-portal.de: 2
    uicdn.com: 3
    uimserv.net: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Try `@@||web.de^$ghide`

**Comment by rotgruengelb** [comment]
Works 👍

**Comment by rotgruengelb** [comment]
Solution: 
add `@@*$ghide,domain=web.de|gmx.*` to the My Filters section.
