### ISSUE TITLE
zone-annuaire.art: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15425]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zone-annuaire.art/`

### Category

nuisance

### Describe the issue

Un bon coup de ménage serait le bienvenu sur ce site. Des popups, des scripts et tout ce qui peut agacer.
Merci d'avance.

### Screenshot(s)

![Uploading image.png…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 584943
  cosmetic: 149697
  scriptlet: 37095
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 30929-58, 15h
    easylist: 62334-1035, 15h
    easyprivacy: 30809-14372, 15h
    plowe-0: 3671-1043, 15h
    ublock-abuse: 76-2, 15h
    ublock-badware: 4352-260, 15h
    ublock-filters: 32958-3610, 15h
    ublock-privacy: 260-45, 15h
    ublock-quick-fixes: 420-32, 15h
    ublock-unbreak: 1881-95, 15h
    urlhaus-1: 10311-6, 15h
filterset (user): [array of 2094 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 809 ms (selfie)
  maxAssetCacheWait: 426 ms
```
</details>

**Comment by okiehsch** [comment]
`||zone-annuaire.art/main.js$script,1p`
@alex-302
