### ISSUE TITLE
rawstory.com: detection

### ISSUE THREAD

**Issue by silat** [uBlockOrigin/uAssets#15427]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rawstory.com/`

### Category

detection

### Describe the issue

Detection advertisement appears within seconds of accessing the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20221026-115418_Firefox](https://user-images.githubusercontent.com/7036902/198130873-d0089ad6-7fb9-4fcf-bd07-2e2ef6cd5fb6.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 89485
  cosmetic: 27691
  scriptlet: 17897
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33304-379, 1h.46m
    ublock-badware: 4355-0, 1h.46m
    ublock-privacy: 288-1, 1h.46m
    ublock-abuse: 76-0, 1h.46m
    ublock-unbreak: 1890-0, 1h.46m
    ublock-quick-fixes: 425-0, 1h.46m
    adguard-mobile: 8195-167, 1h.46m
    easylist: 62357-17592, 1h.46m
    easyprivacy: 30816-1732, 1h.46m
    urlhaus-1: 10523-0, 1h.46m
    plowe-0: 3671-3, 1h.46m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 621 ms (selfie)
  maxAssetCacheWait: 145 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    bounceexchange.com: 1
    chartbeat.com: 3
    connatix.com: 2
    cxense.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    npttech.com: 1
    onesignal.com: 1
    proper.io: 1
    quantserve.com: 1
    rbl.ms: 5
    scorecardresearch.com: 1
```
</details>

**Comment by silat** [comment]
Can you give me a clue as to why you closed it without even helping?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/198140543-2561e81d-81ff-47ef-8320-4f036df385af.png)

If you read this sentence carefully it gives you a clue. 😉 

I close the issue as completed in - "you can click the blue number" - a commit in which I added a new filter dealing with your issue.
If you update your filter lists the detection message should be gone.

By the way we had the same discussion earlier. https://github.com/uBlockOrigin/uAssets/issues/4712
😀

**Comment by silat** [comment]
I appreciate your help. I've been using  Ublock for many years and I'm now
in my seventies and really can't remember how to use it other than to let
it do its job.
As to your reference that we've discussed it before, I don't remember
talking with you in the recent past. Are you referring to some contact
between us many years ago?

Again thank you for contacting me and helping me.

Lew
PDX

PS working class German Shepherd from Germany Apollo says, WOOF!

**Comment by silat** [comment]
Sorry for my confusion. Age and surgery yesterday have made me a little
confused. Anyway I made sure my list was updated. In fact I updated a few
times just to be sure. And I am still seeing the notice on The Raw Story
page. Maybe I'm missing something and you can guide me if you have time.
And I did clean out all cookies etc.

Lew

**Comment by silat** [comment]
Well I guess I'm not over my confusion haha. When I opened the site from a
saved tab, everything's fine. If I click to refresh the page on the words
Raw story at the top the gotcha page appears. If I refresh from the browser
settings the gotcha page appears . If I click on the first story with the
red background the gotcha page appears. If I click on a story further down
the page it does not appear. If I'm reading another story and I hit the
words Raw story at the top of the page to go to the homepage the gotcha
page appears. Why do they make it so hard? 🤣
