### ISSUE TITLE
signal-arnaques.com: detection

### ISSUE THREAD

**Issue by XgLsuLzRMy** [uBlockOrigin/uAssets#15421]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.signal-arnaques.com/scam/view/560273`

### Category

detection

### Describe the issue

A pop-up appears saying it detects add blocker and prevents navigating on the web page.
A script seems to be blocked by EasyList and adding the following rule makes the website usable again :
www.signal-arnaques.com https://www.signal-arnaques.com/js/pubPolicy/ads-prebid.js script allow

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2022-10-26 at 17-50-57 Attention Arnaque  Partagez !](https://user-images.githubusercontent.com/32542170/198100011-be047d0d-cc43-4a17-9e07-abc198096d9d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 137474
  cosmetic: 230772
  scriptlet: 38455
  html: 813
listset (total-discarded, last updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 25452-4, 27m
    adguard-generic: 64200-5253, 3d.5h.41m
    adguard-mobile: 8173-11, 3d.5h.40m
    adguard-spyware: 33727-13541, 3d.5h.38m
    adguard-annoyance: 60056-5644, 3d.5h.46m
    adguard-social: 18579-1070, 3d.5h.37m
    fanboy-annoyance: 81459-65456, 3d.42m
    fanboy-cookiemonster: 41942-9275, 1d.5h.34m
    fanboy-social: 23402-12, 1d.9h.29m
    ublock-annoyances: 4878-4, 3d.5h.39m
    adguard-spyware-url: 793-4, 3d.5h.47m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33917-76, 3d.5h.45m
    ublock-badware: 4408-0, 3d.5h.43m
    ublock-privacy: 282-0, 7d.10h.39m
    ublock-abuse: 76-0, 7d.10h.38m
    ublock-unbreak: 1889-0, 3d.5h.42m
    easylist: 62002-803, 3d.41m
    easyprivacy: 30781-1717, 3d.40m
    urlhaus-1: 10615-0, 26m
    plowe-0: 3675-141, 6d.11h.13m
    ublock-quick-fixes: 426-0, 25m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 67 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1083 ms (selfie)
  maxAssetCacheWait: 900 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    signal-arnaques.com: 1
    cloudflareinsights.com: 2
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
It's fixed in the regional french list.
`signal-arnaques.com##+js(set-constant, moneyAbovePrivacy, true)`
