### ISSUE TITLE
konzolista.cz: ads

### ISSUE THREAD

**Issue by LoneckCZ** [uBlockOrigin/uAssets#15420]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.konzolista.cz/`

### Category

ads

### Describe the issue

Even with custom filters the ads keep appearing on the site. Custom filters were working on this site but it stopped. I dont know when.
![ad](https://user-images.githubusercontent.com/83338397/198095361-c56f3d64-6be1-443c-b529-3aed67aa2b25.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88981
  cosmetic: 38762
  scriptlet: 18014
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 823-37, never
    ublock-filters: 33200-53, 1m
    ublock-badware: 4356-0, 1m
    ublock-privacy: 288-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1885-0, 1m
    easylist: 62357-634, 1m
    easyprivacy: 30816-1712, 1m
    plowe-0: 3671-3, 1m
    CZE-0: 729-0, 1m
    urlhaus-1: 10523-0, 1m
    ublock-quick-fixes: 425-0, 1m
filterset (user): [array of 823 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 209 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cookieyes.com: 1
    googletagmanager.com: 1
    seznam.cz: 2
```
</details>

**Comment by okiehsch** [comment]
````
konzolista.cz##.ad
konzolista.cz##.v-card.mb-6
````

**Comment by stephenhawk8054** [comment]
@LoneckCZ Can you report the issue at https://github.com/tomasko126/easylistczechandslovak ?

**Comment by LoneckCZ** [comment]
> @LoneckCZ Can you report the issue at https://github.com/tomasko126/easylistczechandslovak ?

Yeah, I will report it there. Thanks.
