### ISSUE TITLE
CodeProject.com

### ISSUE THREAD

**Issue by GuardianMajor** [uBlockOrigin/uAssets#1542]
### URL(s) where the issue occurs
_It happens on all the Articles pages but a sample provided below_:

`[ https://www.codeproject.com/Articles/109639/nVLC ]`

### Describe the issue

When accessing the site, there are only two items showing as blocked in the logger for which an exception can be made, as follows:

1. `[ https://ssl.google-analytics.com/ga.js] [script] `
2. `[ https://pubads.g.doubleclick.net/activity...] [image] `

Then there are two items that you can't set an exception for which are:

- `codeproject.com##script:inject(abort-on-property-write.js, _sp_)`
- `codeproject.com##script:inject(abort-on-property-read.js, retrievalService)`

_Both of which identify as being from the_ `uBlock filters`

The problem is that you cannot click the bookmark button because it never finishes rendering. There is a blank SPAN element for it but nothing else. You also get the Follow AND Unfollow buttons at the same time, you should only have one or the other.

### Screenshot(s)

![cpe](https://user-images.githubusercontent.com/5274181/36233470-1194af00-119b-11e8-8367-e3adc2e29181.png)

### Versions

- Browser/version: [ **Firefox / 56.0.2 (64-bit)** ]
- uBlock Origin version: [ **1.15.6** ]

### Settings

_Very minor changes, as seen here_:

![ub0](https://user-images.githubusercontent.com/5274181/36233732-3298500c-119c-11e8-9fa1-ddac5fe0cc3d.png)

### Notes

I have checked the site by trying the following things and found the behavior to suggest somehow it is breaking due to uB0 but it is anecdotal.

- I whitelisted the site and the problem continues to occur, there is no change in outcome.
- I disabled that particular filter and reloaded the site, there is no change in outcome.
- I then disabled uB0 from the extensions page, and force reloaded the page and the problem resolves.

I am at a loss as to why it is happening, hoping someone can provide insight.

**Comment by okiehsch** [comment]
> Then there are two items that you can't set an exception for

You can disable `script:inject` filters the same way you would disable "normal" cosmetic filters.
`example.com#@#whatever`
In this case `codeproject.com#@#script:inject(abort-on-property-write.js, _sp_)`

Having said that, I can't reproduce, the bookmark button renders fine.
![unbenannt](https://user-images.githubusercontent.com/16838044/36234398-12a045bc-11eb-11e8-8eed-63f37ed58ba6.JPG)

**Comment by GuardianMajor** [comment]
That is very bizarre, because that is not my experience with it. Thank you for checking.

As for the two I said can't be exempted, I found no way to do it from the GUI or the logger, like you can with other filters. So to make sure I understand, you are saying I have to manually add the exemption?

What browser did you test this on, because I am trying to see if it may be related to using Fx 56 or something else. Thanks.

**Comment by okiehsch** [comment]
I tested with Chrome 64 and Firefox 58.
I also tested while logged in, with the same result.
![codepr](https://user-images.githubusercontent.com/16838044/36234728-efd2b7f2-11ec-11e8-882e-c2507039de2d.JPG)

> So to make sure I understand, you are saying I have to manually add the exemption?

If you only want to disable one specific `script:inject` filter, yes, just like you can't disable one specific cosmetic filter without manually adding the exception to your filter list.

You can disable **all** `script:inject` filter by setting a local allow rule for the 1st-party domain (codeproject.com in your example), this will prevent all scriptlet injections.

**Comment by GuardianMajor** [comment]
My sincerest apologies and thanks, I believe I found the culprit.

It is a compounding issue when both uB0 and GreaseMonkey are enabled at the same time. Disabling uB0 or GM fixes the issue but not when both are active.

I will take up the matter with their development team, sorry for the trouble and thank you for taking the time, I appreciate it.

PS. I appreciate the explanation for the `script:inject` gotcha, thank you.
