### ISSUE TITLE
twitter.com - existing filters too narrow

### ISSUE THREAD

**Issue by corobin** [uBlockOrigin/uAssets#15430]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://twitter.com/gorhill`

### Describe the issue

`uBlock filters – Annoyances` currently has two filters referring to issue #4987

```
! https://github.com/uBlockOrigin/uAssets/issues/4987
mobile.twitter.com###layers div[dir="auto"] > span:has-text(/在应用上更好|在應用程式上體驗更好的|better on the app|besser in der App|еще больше возможностей в приложении|mejor en la app|melhor no aplicativo|profiterez mieux de Twitter sur l'application|Twitterアプリをおすすめ/):upward(5)
mobile.twitter.com##div[tabindex="0"]:matches-css(position:fixed):has([href="/signup"])
```

1. These two filters only apply to `mobile.twitter.com`. They should be broadened to also include `twitter.com` as the same elements appear on the main domain as well, which is now identical to the `mobile` subdomain on mobile and can be accessed via either domain. Further, the blocking signup popup (second filter) appears on the desktop site too.

2. An additional filter should be added: `twitter.com##html:style(overflow:auto!important)` this will allow the page to not be frozen after the popup (blocked by the second filter above) is triggered.

3. Unrelated to the above, there is also a persistent banner that says "Don’t miss what’s happening". Please see screenshot attached.

Thanks!

### Screenshot(s)

![twitter-dont-miss-happening](https://user-images.githubusercontent.com/15662785/198211934-fa7e12aa-083b-4047-a91a-f81895e9909f.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106.0.2

### Settings

n/a

**Comment by stephenhawk8054** [comment]
3. Enable `Adguard Annoyances` list or add these to `My filters` for `Don’t miss what’s happening`

```adb
twitter.com##html:style(overflow: auto !important; padding-right: 0 !important; overscroll-behavior-y: auto !important;)
twitter.com###layers > div[class] > div[class] > div[class] > div[class]:has(> div[class] > div[class] > div[class] > div[class] > div[class] > div[class] > a[href="/login"])
```

**Comment by corobin** [comment]
Sorry to bug you but I saw this was closed but looking at the current version of the annoyance list it looks like #1 and #2 that I described above are not updated in the list yet?

#1 should be pretty easy to update, just removing the `mobile` subdomain from the two filters, as such:

```
twitter.com###layers div[dir="auto"] > span:has-text(/在应用上更好|在應用程式上體驗更好的|better on the app|besser in der App|еще больше возможностей в приложении|mejor en la app|melhor no aplicativo|profiterez mieux de Twitter sur l'application|Twitterアプリをおすすめ/):upward(5)
twitter.com##div[tabindex="0"]:matches-css(position:fixed):has([href="/signup"])
```

#2 it appears that this already exists in the adguard annoyance filter but since uBlock Annoyances is blocking the overlay, I suggest it should also contain this filter as well so scrolling is not frozen:

`twitter.com##html:style(overflow: auto !important; padding-right: 0 !important; overscroll-behavior-y: auto !important;)`

Thanks again!

**Comment by stephenhawk8054** [comment]
I can reproduce the overlay a few times, not always appear.

These filters work for me

```adb
twitter.com##div[tabindex="0"]:matches-css(position:fixed):has([href="/signup"])
twitter.com##html:style(overflow:auto!important)
```

but I can't see 

```adb
twitter.com###layers div[dir="auto"] > span:has-text(/在应用上更好|在應用程式上體驗更好的|better on the app|besser in der App|еще больше возможностей в приложении|mejor en la app|melhor no aplicativo|profiterez mieux de Twitter sur l'application|Twitterアプリをおすすめ/):upward(5)
```

being activated

**Comment by corobin** [comment]
> but I can't see
> ...
> being activated

That only appears in mobile. but `twitter.com` is now identical to `mobile.twitter.com` on mobile so it does appear on the main domain on mobile too. you can see it too if you use device emulation in developer tools on a desktop browser. thanks again.

**Comment by stephenhawk8054** [comment]
Ah ok I misunderstood the issue. You meant the step is accessing `https://twitter.com/gorhill` on mobile.

**Comment by corobin** [comment]
> Ah ok I misunderstood the issue. You meant the step is accessing `https://twitter.com/gorhill` on mobile.

doh! yes, i did not explain it clearly. I think the mobile filter short circuited my mental model earlier. glad we had that cleared up. thank you very much!

**Comment by AntiAdvert** [comment]
![image](https://user-images.githubusercontent.com/117537631/200136250-3e4db247-e48e-4623-a7de-24dd8ec9953e.png)
Encountered with Netherlands IP address and `uBlock filters - Annoyances` enabled

@Yuki2718 Could you please add a rule from `AdGuard Annoyances Filter`?

**Comment by BlazingRaven495** [comment]
After I cleared my filters to fix the youtube a adblock issue, i had to manually block the "what's happening" side panel on twitter, but now it doesn't work on every page. if i click on someone's profile or another page, it comes back. I know this topic was for mobile but I'm on PC with chrome and the latest version of uBO. I replied here rather than start a new topic.

this is the thread that shows up when i custom pick it like i said it doesn't work on all pages.

twitter.com##div.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.r-1d6w8o1.r-x572qd.css-1dbjc4n:nth-of-type(4)

**Comment by gorhill** [comment]
> manually block the "what's happening" side panel on twitter

See <https://old.reddit.com/r/uBlockOrigin/wiki/solutions/twitter>, look for _Sidebar_ section. Use reddit for such support, I will lock the thread to avoid people from being spuriously notified about a resolved issue.
