### ISSUE TITLE
youtube.videodeck.net: breakage

### ISSUE THREAD

**Issue by Kyzoku** [uBlockOrigin/uAssets#15435]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://youtube.videodeck.net/`

### Category

breakage

### Describe the issue

The page fails to login when ubo is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/C7tYqpY

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88226
  cosmetic: 38649
  scriptlet: 18201
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62002-53, 3d.14h.19m
    easyprivacy: 30781-1170, 3d.14h.18m
    plowe-0: 3675-865, 9d.17h.44m
    ublock-abuse: 76-0, 10d.17h.52m
    ublock-badware: 4342-104, 2d.14h.15m
    ublock-filters: 33143-112, 2d.14h.14m
    ublock-privacy: 257-1, 10d.17h.49m
    ublock-quick-fixes: 419-33, 10h.8m
    ublock-unbreak: 1879-42, 2d.14h.13m
    urlhaus-1: 11039-0, 10h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 477 ms (selfie)
  maxAssetCacheWait: 321 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    google-analytics.com: 1
    youtube.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't sign in even when disabling uBO.

**Comment by okiehsch** [comment]
If that's the case it's a site issue and can be closed.

**Comment by Kyzoku** [comment]
I can sign in just fine when I disable ublock, perhaps stephen has something else running that is blocking it.

**Comment by stephenhawk8054** [comment]
Ok, just checked again and I can sign in if ticking on the 2 boxes below here

![image](https://user-images.githubusercontent.com/66517106/199166956-1e8c59fb-59fc-4f60-962b-8760ea1b3b0e.png)

Please specify the steps to reproduce clearer next time.

**Comment by stephenhawk8054** [comment]
@Kyzoku Does it work if you add this?

```adb
@@||google-analytics.com/analytics.js$script,redirect-rule
```

**Comment by Kyzoku** [comment]
That in fact does fix the issue.  Thank you.

**Comment by stephenhawk8054** [comment]
> That in fact does fix the issue. Thank you.

I forgot the `domain` in the above filter. You should use

```adb
@@||google-analytics.com/analytics.js$script,redirect-rule,domain=youtube.videodeck.net
```

or wait for about 10 minutes and force update the filter list (remember to remove the above filter).
