### ISSUE TITLE
encar.com: breakage

### ISSUE THREAD

**Issue by rog103** [uBlockOrigin/uAssets#15437]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://www.encar.com/dc/dc_carsearchlist.do?carType=kor`

### Category

breakage

### Describe the issue

Main page is showing with white blank when use filter for uBlock 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-10-28 00 12 27](https://user-images.githubusercontent.com/116824890/198328745-7366c0c6-2e93-4925-94c0-bde5da0b39f1.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 115206
  cosmetic: 110650
  scriptlet: 21618
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 60262-96, now
    adguard-social: 18692-839, now
    adguard-spyware: 35856-2852, now
    adguard-spyware-url: 793-1, now
    block-lan: 44-0, now
    fanboy-thirdparty_social: 68-3, now
  default: 
    user-filters: 0-0, never
    KOR-1: 3658-6, 8h.29m
    easylist: 62309-182, 16h.31m
    easyprivacy: 30809-14032, 16h.30m
    plowe-0: 3671-947, 1d.16h.37m
    ublock-abuse: 76-0, 1d.16h.36m
    ublock-badware: 4342-109, 2d.16h.45m
    ublock-filters: 33197-535, 2d.16h.44m
    ublock-privacy: 260-46, 1d.16h.35m
    ublock-quick-fixes: 420-21, 8h.28m
    ublock-unbreak: 1876-59, 2d.16h.43m
    urlhaus-1: 11029-0, 8h.27m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 560 ms (selfie)
  maxAssetCacheWait: 425 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    encar.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
Update the `uBO-unbreak` list, should work as expected after that.
