### ISSUE TITLE
nookipedia.com: nuisance

### ISSUE THREAD

**Issue by PanchamBro** [uBlockOrigin/uAssets#15439]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nookipedia.com/wiki/File:Advertising_Board_iQue_Model.png`

### Category

nuisance

### Describe the issue

An image on Nookipedia is apparently being blocked by uBlock Origins, even though the image in question is merely an item model image meant for a game ([Dòngwù Sēnlín](https://nookipedia.com/wiki/D%C3%B2ngw%C3%B9_S%C4%93nl%C3%ADn))

The image in question: https://dodo.ac/np/images/4/4d/Advertising_Board_iQue_Model.png

I'm not sure how to address this, but if this can be fixed for images that have the word "advertising" but are not really advertisements, I would appreciate it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO on:
![image](https://user-images.githubusercontent.com/5955312/198342481-165316b2-36f0-48b3-82c5-126a027a795d.png)

With uBO off:
![image](https://user-images.githubusercontent.com/5955312/198342543-423e2b3e-5a51-4dce-90b3-dbac5b245f6d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 107
filterset (summary): 
  network: 93059
  cosmetic: 38740
  scriptlet: 18202
  html: 793
listset (total-discarded, last updated): 
  added: 
    https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 8182-0, 159d.19h.39m
  default: 
    user-filters: 29-0, never
    ublock-filters: 33938-33, 2d.5h.14m
    ublock-badware: 4356-0, 2d.5h.13m
    ublock-privacy: 281-0, 12d.5h.48m
    ublock-abuse: 76-0, 12d.5h.47m
    ublock-unbreak: 1892-0, 2d.5h.12m
    easylist: 62002-607, 3d.18h.11m
    easyprivacy: 30781-1707, 3d.18h.10m
    urlhaus-1: 10615-2923, 15h.54m
    plowe-0: 3671-3, 7h.50m
    ublock-quick-fixes: 425-21, 15h.53m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    about-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 237577 ms (selfie)
  maxAssetCacheWait: 612 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    nookipedia.com: 1
    dodo.ac: 2
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||dodo.ac/np/images/thumb/*/Advertising_Board_iQue_Model.png/*$image,domain=nookipedia.com`
