### ISSUE TITLE
empire.goodgamestudios.com: ads

### ISSUE THREAD

**Issue by Yolomic** [uBlockOrigin/uAssets#15431]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://empire.goodgamestudios.com/`

### Category

ads

### Describe the issue

The Website Leaves An Ad placeholder verticall and horizontally on the top and right of the screen limiting your gameplay experience.(DISCLAIMER:No Ads Are Shown But even tho trying to block the placeholders the game still limits your aspect ratio and as mention by some close friends other adb's dont have that problem)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 87567
  cosmetic: 62558
  scriptlet: 18203
  html: 796
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.50m
    https://www.i-dont-care-about-cookies.eu/abp/: 25450-6, 1d.19h.4m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33859-54, 19h.22m
    ublock-badware: 4356-0, 19h.21m
    ublock-privacy: 288-0, 19h.20m
    ublock-abuse: 76-0, 19h.19m
    ublock-unbreak: 1894-0, 19h.18m
    ublock-quick-fixes: 425-0, 1h.52m
    easylist: 61947-619, 4d.20h.49m
    easyprivacy: 30788-1707, 4d.20h.49m
    urlhaus-1: 8916-0, 1h.51m
    plowe-0: 3671-3, 4d.20h.49m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 379 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    goodgamestudios.com: 29
    bugsnag.com: 3
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    jsdelivr.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any ads. Can you force update the filter lists and test again?

**Comment by okiehsch** [comment]
I don't see any placeholders.

**Comment by C0ff33B3an** [comment]
I can supply screenshots in their other game Big Farm.
![BigFarmLogInScreenshot 2022-10-27 173823](https://user-images.githubusercontent.com/116849403/198411417-510d3fc2-e45f-4296-9001-211dec24b4bd.png)
![BigFarmLoggedIn Screenshot 2022-10-27 173948](https://user-images.githubusercontent.com/116849403/198411431-be593ebd-fcdc-41dc-aa25-a0fcacb23e5f.png)

Hope these are helpful.

**Comment by stephenhawk8054** [comment]
Can you check the above issues (issue 14795)?

**Comment by stephenhawk8054** [comment]
@C0ff33B3an Can you check if adding these to ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) works? (click Apply changes, go back to the website and press Ctrl + F5 to reload the page)

```adb
goodgamestudios.com###ad-placeholder-vertical
goodgamestudios.com###ad-placeholder-horizontal
```

**Comment by C0ff33B3an** [comment]
Thanks for the clear steps and instructions.  It didn't change anything.  I also cleared my browser cache and went to the website directly instead of my bookmark, in case that helps too (which may confirm how little tech I know LOL)

**Comment by C0ff33B3an** [comment]
![Screenshot 2022-10-31 091835](https://user-images.githubusercontent.com/116849403/199029779-a4996f24-a07a-406e-8012-402d81cfb5f1.png)

**Comment by C0ff33B3an** [comment]
Thought I'd include the screenshot to confirm if I did the step correctly.

**Comment by stephenhawk8054** [comment]
Sorry, as I cannot reproduce the issue (it might need an old account, or need to let the site run for a long time), I cannot help you more.

**Comment by C0ff33B3an** [comment]
I received the update that this was closed.  
I've re-read thread #14795 and it mentioned the easy list?  Suggested to the person who created the thread to post/report on there?  Is a fix listed somewhere else pertaining to this easy list?  The thread had a label of fixable by @[mapx-](https://github.com/mapx-) mapx- added the [fixable by Easylist / Adguard lists](https://github.com/uBlockOrigin/uAssets/labels/fixable%20by%20Easylist%20%2F%20Adguard%20lists) to be fixed by EasyList / EasyPrivacy / fanboy's annoyances / AdGuard Annoyanceslabel [on Sep 13](https://github.com/uBlockOrigin/uAssets/issues/14795#event-7378977934) 
My copy/paste didn't work right.

I really appreciate your expertise and what you've done regarding this issue so far.  If I have the terms correct, the ad placeholders aren't disappearing?   I'm curious whether it was actually fixed for the poster in the other thread.
