### ISSUE TITLE
adshnk.com: detection

### ISSUE THREAD

**Issue by DegenCode** [uBlockOrigin/uAssets#15434]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://adshnk.com/`

### Category

detection

### Describe the issue

forces you to turn off ublock to see content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 102
filterset (summary): 
  network: 89832
  cosmetic: 38415
  scriptlet: 18194
  html: 790
listset (total-discarded, last updated): 
  added: 
    https://cdn.rawgit.com/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, 3d.13h.21m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33859-65, 21h.9m
    ublock-badware: 4356-0, 21h.8m
    ublock-privacy: 282-0, 6d.16h.15m
    ublock-abuse: 76-0, 6d.16h.14m
    ublock-unbreak: 1885-0, 21h.7m
    easylist: 62316-648, 1d.21h.14m
    easyprivacy: 30807-1707, 1d.21h.13m
    plowe-0: 3671-3, 5d.1h.32m
    ublock-quick-fixes: 429-0, 1h.5m
    urlhaus-1: 11029-0, 1h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1850 ms (selfie)
  maxAssetCacheWait: 686 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adsco.re: 1
    google-analytics.com: 1
    quantserve.com: 1
    taboola.com: 1
    trackjs.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again? Your link gives this

![image](https://user-images.githubusercontent.com/66517106/198270316-7b818028-df46-45b4-ae56-9c9088c5f2c5.png)

**Comment by krystian3w** [comment]
That is link shortener with anti-adblock mechanism.

To reproduce needed origin URL like `adshnk.com/PwgmBv` (but shows even uBo was disabled) - it should opens YouTube safe video/transmission.

**Comment by okiehsch** [comment]
> This site shows anti-adblock banner even when disabling uBO 

Yes, same on my end, nothing to do for us.

**Comment by dportvine** [comment]
Maybe only Firefox?

<details>
<summary>Screen</summary>

![2022-10-27_162504](https://user-images.githubusercontent.com/111344219/198297022-c99b3afb-1b17-4cd8-af94-fde8bb8d6867.png)
</details>

**Comment by okiehsch** [comment]
Yes, it's only a Firefox issue.

**Comment by dportvine** [comment]
@okiehsch 
Can you check again?
```adb
https://adshnk.com/PwgmBv
```

**Comment by stephenhawk8054** [comment]
> `https://adshnk.com/PwgmBv`

It works fine for me on firefox now. No anti-adblock.

For ads and timer:

```adb
adshnk.com##.basic.segment.ui > .item
adshnk.com##.custom-modal
adshnk.com##+js(set, _adshrink.skiptime, 0)
```

**Comment by dportvine** [comment]
>It works fine for me on firefox now. No anti-adblock with uBO on.

Two days ago I contacted the administrator of this site. And I asked him to correct this mistake. 😉
