### ISSUE TITLE
Filter Breaks Homework site: my.hrw.com

### ISSUE THREAD

**Issue by kalebchoi** [uBlockOrigin/uAssets#15447]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

my.hrw.com

### Describe the issue

When loading onto my.hrw.com for homework. Most elements are gone and I am unable to use the site.

### Screenshot(s)

I have censored personal details and details on the course that I am taking

With uBlock Origin On
![image](https://user-images.githubusercontent.com/47734777/198527974-58abec40-47b3-4d52-9943-54cf689c18c5.png)
With uBlock Origin Off
![image](https://user-images.githubusercontent.com/47734777/198528794-157a6de6-cca3-41bf-af9a-b50625617ee9.png)

### Notes

Logger output
https://pastebin.com/sfeQziyH

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88221
  cosmetic: 38524
  scriptlet: 17704
  html: 787
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32956-143, 5h.12m
    ublock-badware: 4356-0, 2d.2h.55m
    ublock-privacy: 282-0, 5d.5h.8m
    ublock-abuse: 76-0, 7d.4h.55m
    ublock-unbreak: 1892-0, 2d.2h.54m
    ublock-quick-fixes: 440-0, 5h.11m
    easylist: 62008-510, 4d.7h.30m
    easyprivacy: 30801-1722, 4d.7h.29m
    urlhaus-1: 11291-0, 5h.10m
    plowe-0: 3671-3, 5d.5h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 683 ms (selfie)
  maxAssetCacheWait: 263 ms
```
</details>

**Comment by okiehsch** [comment]
Does it work if you add
`@@||my.hrw.com/dashboard/js/workbench/utils/analytics.js$script,1p`
to ypur filter lsit?

**Comment by kalebchoi** [comment]
Sorry, I forgot to test it until now. Yes, it does work with this filter.
