### ISSUE TITLE
Problem with openload

### ISSUE THREAD

**Issue by qwer1304** [uBlockOrigin/uAssets#1544]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://cutwin.com/XOjU`

### Describe the issue
After forwarding to openload, I'm getting:
Embed blocked
This error was triggered from Openload's anti abuse mechanism

### Screenshot(s)
![image](https://user-images.githubusercontent.com/2311076/36242498-05955bd4-1225-11e8-9273-147d56cc5442.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome Version 66.0.3347.0 (Official Build) canary (64-bit)
- uBlock Origin version: 1.15.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
Have Nano Defender 13.32 installed
Disabling uBlock Original on the page does NOT resolve the issue

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
broken link, provide another one.

However, when you get again that error, try disabling not uBo but nano defender.

**Comment by qwer1304** [comment]
Update the link.
Disabling Nano Defender doesn't help

**Comment by mapx-** [comment]
I fixed `cutw.me` anti adb, cannot reproduce your `openload` issue

**Comment by qwer1304** [comment]
Thx.
Try this link http://linkshrink.net/7bMao1 to see the problem with openload
(This is the link cutw.me forwards to)

**Comment by mapx-** [comment]
As I said, cannot reproduce the issue (meaning I arrived on that page but no error for me, the torrent file is downloaded for me)

**Comment by qwer1304** [comment]
Are you using Chrome?

**Comment by mapx-** [comment]
yes, you should try chrome stable or beta.

**Comment by qwer1304** [comment]
OK, found it was this extension https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm that was screwing openload
