### ISSUE TITLE
Google.com(uBO=off) prevents adLink play.Google.com reporting filter: ||doubleclick.net^ ( Peter Lowe’s...list )

### ISSUE THREAD

**Issue by prokop74** [uBlockOrigin/uAssets#15440]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Problem indicates not only google, but few other global sites
This:
https://www.google.com/search?q=play+google
shoes up this link: 
https://play.google.com/
but realy links this:
https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwic7Yz97YD7AhWH-FEKHQOnDngYABABGgJ3cw&ohost=www.google.com&cid=CAESbOD2ChT4jwI1wULcFHFDBkveVIEkuehy2dh5ASEAzMZ8oRU7w3Io0PEe5E9hN4iJO90B_61h0oU0oGewifzgOuCojwvSDyghuI2njU2k-ebETMpWSw9uTpQ_dFdJjMXTPHgMGDEvjlSqNhjHMg&sig=AOD64_1AAGThUWBm-LoxoRdcR792rSoUJA&q&adurl&ved=2ahUKEwi0lYX97YD7AhW0S_EDHdHBBEwQ0Qx6BAgMEAE

And we get this(in adress bar):

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html?details=%7B%22url%22%3A%22https%3A%2F%2Fad.doubleclick.net%2Fclk%3B256595225%3B80399023%3Bo%3Bu%3Dds%26sv1%3D7034273608%26sv2%3D3333774984267581%26sv3%3D3062873891196018826%26gclid%3DCjwKCAjw2OiaBhBSEiwAh2ZSP7TqhoIWNl9Am1Dgl4zJ1dvd7Qb8_RobSb3Ez9m_owcsS758CciIsBoCxHwQAvD_BwE%3B%253fhttps%3A%2F%2Fplay.google.com%2Fstore%3Futm_source%3Demea_Med%26utm_medium%3Dhasem%26utm_content%3DOct2020%26utm_campaign%3DEvergreen%26pcampaignid%3DMKT-EDR-emea-cz-1001280-Med-hasem-py-Evergreen-Oct2020-Text_Search_BKWS%257cONSEM_kwid_43700007034273608%26gclid%3DCjwKCAjw2OiaBhBSEiwAh2ZSP7TqhoIWNl9Am1Dgl4zJ1dvd7Qb8_RobSb3Ez9m_owcsS758CciIsBoCxHwQAvD_BwE%26gclsrc%3Daw.ds%22%2C%22hn%22%3A%22ad.doubleclick.net%22%2C%22dn%22%3A%22doubleclick.net%22%2C%22fs%22%3A%22%7C%7Cdoubleclick.net%5E%22%7D

### Describe the issue

Google.com(uBO disabled) adLink play.Google.com uBO prevents  reporting filter: ||doubleclick.net^ ( Peter Lowe’s...list )

### Screenshot(s)

![uBO-google-play1](https://user-images.githubusercontent.com/68331792/198349499-ce046e80-2c5c-45be-9a67-00b545f94e76.JPG)

![uBO-google-play2](https://user-images.githubusercontent.com/68331792/198349521-dfa54575-4bcf-427d-a8ea-4bc38830584b.JPG)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 88459
  cosmetic: 39053
  scriptlet: 18372
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CZE-0: 728-0, 6h.12m
    easylist: 62002-55, 2d.7h.11m
    easyprivacy: 30781-1175, 2d.7h.12m
    plowe-0: 3675-865, 6d.20h.44m
    ublock-abuse: 76-0, 6d.20h.47m
    ublock-badware: 4352-104, 2d.7h.10m
    ublock-filters: 33206-112, 2d.7h.9m
    ublock-privacy: 257-1, 6d.20h.46m
    ublock-quick-fixes: 419-21, 6h.10m
    ublock-unbreak: 1881-42, 2d.7h.8m
    urlhaus-1: 11039-0, 6h.11m
filterset (user): [empty]
trustedset: 
  added: [array of 43 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 812 ms (selfie)
  maxAssetCacheWait: 510 ms
```
</details>

**Comment by okiehsch** [comment]
You have to click "Docasne" or "Trvale".
You get redirected through an adserver and uBlock warns you about it.
It's up to you if you want to proceed or not.
