### ISSUE TITLE
ordertracker.com: ads

### ISSUE THREAD

**Issue by shal0l** [uBlockOrigin/uAssets#15441]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ordertracker.com/`

### Category

ads

### Describe the issue

Ad not blocked.

### Screenshot(s)

![firefox_HiYD0VSRKh](https://user-images.githubusercontent.com/67803583/198374208-3d465e8d-9e70-4c39-b4b5-0fae41e392df.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89054
  cosmetic: 41760
  scriptlet: 18437
  html: 796
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33906-33, 4d.14h.17m
    ublock-badware: 4346-0, 2d.13h.32m
    ublock-privacy: 288-0, 3d.14h.7m
    ublock-abuse: 76-0, 3d.17h.59m
    ublock-unbreak: 1889-0, 2d.13h.31m
    ublock-quick-fixes: 424-21, 19h.14m
    easylist: 62002-651, 3d.17h.58m
    easyprivacy: 30781-1720, 3d.17h.57m
    urlhaus-1: 10523-0, 1d.12h.7m
    plowe-0: 3671-3, 2d.16h.36m
    spa-1: 4775-46, 2d.13h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 235 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`ordertracker.com##.partnerbanner`
