### ISSUE TITLE
waipian8.com: nuisance

### ISSUE THREAD

**Issue by PoseidonYun** [uBlockOrigin/uAssets#15445]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://waipian8.com/play/150729-5-1/`

### Category

nuisance

### Describe the issue

1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 96004
  cosmetic: 48492
  scriptlet: 17984
  html: 0
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
  default: 
    user-filters: 0-0, never
    CHN-0: 29022-88, 1d.2h.7m
    easylist: 62285-91, 3d.4h.32m
    easyprivacy: 30781-1196, 3d.4h.31m
    plowe-0: 3671-867, 4d.4h.36m
    ublock-abuse: 76-0, 2h.50m
    ublock-badware: 4352-109, 1d.2h.6m
    ublock-filters: 32463-148, 1d.2h
    ublock-privacy: 260-1, 2h.48m
    ublock-quick-fixes: 419-21, 16h.23m
    ublock-unbreak: 1872-43, 1d.1h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 165 ms (selfie)
  maxAssetCacheWait: 51 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    baidu.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||waipian8.com^$ghide
||static.yximgs.com/bs2/adcarsku/*.gif$image
```
@cjx82630

**Comment by cjx82630** [comment]
Please add this list https://main.filter-delivery-staging.eyeo.com/v3/full/cjx-annoyance.txt

**Comment by okiehsch** [comment]
So, this issue is an annoyance and won't be fixed in the main list?
If that's the case I will close it.

**Comment by stephenhawk8054** [comment]
Yeah, I think so, looks similar to Ru Adlist case.
