### ISSUE TITLE
droetker.com.tr: cookie notice

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#15446]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.droetker.com.tr/index`

### Category

breakage

### Describe the issue

Enable `AdGuard Annoyances` filter and check all Dr. Oetker websites.
The `oetker.*/static/js/privacy-dialog/` script is filtered by uBO on the following websites and will also appear in the filtering log.

```
https://www.oetker.at/at-de/index
https://www.oetker.be/be-nl/index
https://www.oetker.hr/hr-hr/index
https://www.oetker.com.br/index
https://www.oetker.bg/bg-bg/index
https://www.oetker.ca/ca-en/index
https://www.oetker.hr/hr-hr/index
https://www.oetker.cz/cz-cs/index
https://www.oetker.dk/dk-da/index
https://www.oetker.fi/
https://www.oetker.fr/fr-fr/index
https://www.oetker.de/index
https://www.oetker.gr/gr-el/index
https://www.oetker.hu/hu-hu/index
https://www.oetker.in/in-en/index
https://www.oetker.ie/ie-en/index
https://www.oetker.lt/lt-lt/index
https://www.oetker.com.my/my-en/index
https://www.oetker.com.au/au-en/index
https://www.oetker.no/no-no/index
https://www.oetker.pl/pl-pl/index
https://www.oetker.pt/pt-pt/index
https://www.oetker.ro/ro-ro/homepage
https://www.oetker.se/se-sv/index
https://www.oetker.ch/ch-de/index
https://www.oetker.rs/rs-sr/index
https://www.oetker.sk/sk-sk/index
https://www.oetker.si/si-si/index
https://www.oetker.es/es-es/index
https://www.oetker.co.za/za-en/index
https://www.oetker.nl/nl-nl/index
https://www.droetker.com.tr/index
https://www.oetker.co.uk/
https://www.oetker.us/us-en/index

```

However, script is not filtered on the `https://www.droetker.com.tr/index` website and does not appear in the log.

The problem can also be reproduced with the default filters. It looks like the uBO issue.

### Screenshot(s)

`https://www.oetker.ca/ca-en/index`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/198516383-e1f46540-f10c-471a-a70a-3ab901dc011e.png)

</details>

---

Firefox browser
the script is not filtered.
`https://www.droetker.com.tr/index`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/198516791-a104f96f-42ca-49e3-b127-8c3294584df3.png)

</details>

---

Chrome browser
The `oetker.*/static/js/privacy-dialog/` script does not appear in the uBO filtering log.

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/198517010-11f018d7-c092-47c0-8700-3d3b4d5e1cc4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 116599
  cosmetic: 148776
  scriptlet: 34258
  html: 793
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 64476-4643, 1d.1h.4m
    adguard-spyware: 35853-2791, 1d.1h.4m
    adguard-spyware-url: 793-3, 1d.1h.4m
    adguard-annoyance: 60231-1531, 1d.1h.4m
    adguard-social: 18682-34, 1d.1h.4m
  default: 
    user-filters: 67-0, never
    ublock-filters: 33015-32, 1d.1h.5m
    ublock-badware: 4356-0, 1d.1h.5m
    ublock-privacy: 288-0, 1d.1h.5m
    ublock-abuse: 76-0, 1d.1h.5m
    ublock-unbreak: 1885-1, 1d.1h.5m
    ublock-quick-fixes: 429-21, 7m
    easylist: 62370-943, 1d.1h.4m
    easyprivacy: 30818-13972, 1d.1h.4m
    TUR-0: 11205-19, 1d.1h.4m
filterset (user): [array of 71 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3470 ms (selfie)
  maxAssetCacheWait: 980 ms
  unsuspendAfter: 2454 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    droetker.com.tr: 4
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/198520413-7bee1d19-9496-49f5-8a73-009c67b85b6d.png)

It does appear but only on the first  load, after that you have to load the site bypassong the cache for it to reappear.

**Comment by okiehsch** [comment]
> However, script is not filtered on the https://www.droetker.com.tr/index website and does not appear in the log.

Why should the script be filtered on this website?

**Comment by okiehsch** [comment]
Well, yes but what I meant is why should the filter
`oetker.*/static/js/privacy-dialog/`
block anything on the site
`droetker.com.tr`

I can reproduce the cookie notification but if you want to block it you need the filter
`droetker.*/static/js/privacy-dialog/`

**Comment by krystian3w** [comment]
Maybe regression in enforce network filtering - maybe few pages still don't added prefix `dr` in domain.

to test possible use `$important`

```adb
oetker.*/static/js/privacy-dialog/$important
```

**Comment by okiehsch** [comment]
That does not work.
So you mean
`oetker.*/static/js/privacy-dialog/`
does work on `droetker.com.tr` using Adguard?

**Comment by krystian3w** [comment]
Maybe cname glitch.

**Comment by okiehsch** [comment]
Ok. it is a quite unusual filter and I thought it would be treated like
`||oetker.*/static/js/privacy-dialog` which was the reason that I was not surprised that it was not blocked by `uBO`.

I opened an internal issue about it.

**Comment by okiehsch** [comment]
The issue was first discussed at https://github.com/gorhill/uBlock/issues/1065

**Comment by Yuki2718** [comment]
This is also mentioned in our wiki: https://github.com/gorhill/uBlock/wiki/Syntax-quirks

**Comment by okiehsch** [comment]
I will add
`||droetker.*/static/js/privacy-dialog/`
to our annoyance list, to deal with this unique case.
