### ISSUE TITLE
linkedin.com: nuisance

### ISSUE THREAD

**Issue by freeburd12** [uBlockOrigin/uAssets#15451]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.linkedin.com/feed/`

### Category

nuisance

### Describe the issue

Linkedin News is still visible on the page -- element zapper doesn't keep it away when used on the page, navigating away, and returning to the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88459
  cosmetic: 38711
  scriptlet: 18205
  html: 796
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33915-33, 2d.37m
    ublock-badware: 4356-0, 2d.36m
    ublock-privacy: 288-0, 1d.10h.30m
    ublock-abuse: 76-0, 1d.10h.29m
    ublock-unbreak: 1894-0, 2d.35m
    ublock-quick-fixes: 427-21, 10h.28m
    easylist: 62002-607, 4d.22h.28m
    easyprivacy: 30781-1707, 4d.22h.27m
    urlhaus-1: 11291-0, 10h.27m
    plowe-0: 3671-3, 14h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 78 ms (selfie)
  maxAssetCacheWait: 44 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    linkedin.com: 3
    cedexis.com: 1
    scorecardresearch.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot the `Linkedin News`?

**Comment by freeburd12** [comment]
Sure, here you go
<img width="1309" alt="Screen Shot 2022-10-28 at 8 47 37 AM" src="https://user-images.githubusercontent.com/116889907/198622092-56247738-712c-475c-bff0-8c0d78e989f4.png">

**Comment by stephenhawk8054** [comment]
I can't see that on my account, so sorry can't help you more.
