### ISSUE TITLE
lightnovelpub.com: detection

### ISSUE THREAD

**Issue by EzSkywalker** [uBlockOrigin/uAssets#15453]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lightnovelpub.com/`

### Category

detection

### Describe the issue

The website detects ubo and requests that you disable AdBlock. It will still let you read stories at first with giant red boxes with that message sprinkled in but will eventually stop letting you read if you don't disable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 89612
  cosmetic: 27669
  scriptlet: 17757
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33086-278, 2m
    ublock-badware: 3946-0, 2m
    ublock-privacy: 288-1, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1891-0, 2m
    ublock-quick-fixes: 438-0, 2m
    adguard-mobile: 8203-166, 2m
    easylist: 62416-17706, 2m
    easyprivacy: 30820-1717, 2m
    urlhaus-1: 11029-0, 2m
    plowe-0: 3669-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 757 ms
  maxAssetCacheWait: 332 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googletagmanager.com: 1
    intergient.com: 3
    moatads.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances` and test again
