### ISSUE TITLE
ssbsblg.blogspot.com: detection

### ISSUE THREAD

**Issue by LordKenmou** [uBlockOrigin/uAssets#15455]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ssbsblg.blogspot.com/`

### Category

detection

### Describe the issue

Inline script deletes entire page contens.

```
<div class="widget-content">
<script>
true&&((d=0,o={method:'HEAD',mode:'no-cors'},ag=['/ad?cid=','/ad_parts.','/ad_timer.','/adcast01_','/adContents_','/adgetter.','/adSidebar.','/advalue_','/TextAD1.'],ez=['&action=getads&','&ad_code=','&ad_height=','&ad_ids=','&ad_network_','&ad_slot=','&ad_sub=','&ad_system=','&ad_time=','&ad_type=','&ad_url=','&ad_zones=','&adbannerid=','&adclient=','&adflag=','&adgroupid=','&adlist=','&adnum=','&adpageurl=','&adsafe=','&adserver=','&adslots=','&adsrc=','&adstrade=','&adstype=','&AdType=','&cbrandom=','&displayads='],t=['/aamsz=','/acc_random=','/ad1.','/adframes.','?adid=','/adloader.','/adplayer.','/ads?','/ads2.','/adsense_','/adservice.','/adshow?','/advertise.','?affid=','/googleads.','/prebid1.','/popunder.'],aa=['&dev=r&adb=y'],ub=['/code/native.js?h='],y=['=PencilAd&'],th=['/wisteria.js','/popunder.js','/advs-conversion.js','/blogroll.js','/dfp-ad-','/amp-ad','/_/json/linelive_ranking.json','/adclick.php'],a=[ag,ez,t,y,aa,ub,th].map(v=>'?'+v[Math.floor(Math.random()*v.length)]))=>{setTimeout(async()=>{await Promise.all([fetch(a[0],o),fetch(a[1],o),fetch(a[2],o),fetch(a[3],o),fetch(a[4],o),fetch(a[5],o),fetch(a[6],o)]).then(v=>false).catch(e=>true)&&document.documentElement.remove()},d)})();
</script>
</div>
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration
<details>
<summary>Configuration</summary>

```
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88175
  cosmetic: 38348
  scriptlet: 17714
  html: 795
listset (total-discarded, last updated): 
  removed: 
    JPN-1: null
  default: 
    user-filters: 29-0, never
    ublock-filters: 32982-53, 9m
    ublock-badware: 3947-0, 9m
    ublock-privacy: 288-0, 9m
    ublock-abuse: 76-0, 9m
    ublock-unbreak: 1886-0, 9m
    easylist: 62416-626, 9m
    easyprivacy: 30820-1707, 9m
    urlhaus-1: 11029-0, 9m
    plowe-0: 3669-3, 9m
    ublock-quick-fixes: 438-0, 9m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 50 redacted]
switchRuleset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 1 redacted]
urlRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 164 ms (selfie)
  maxAssetCacheWait: 363 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    ssbsblg.blogspot.com: 3
    googlesyndication.com: 1
```
</details>

**Comment by energizat** [comment]
`*$xhr,redirect-rule=nooptext,domain=ssbsblg.blogspot.com`
@Yuki2718

**Comment by Yuki2718** [comment]
7.9k visitor/month is outside the [AdGuard Filter Policy](https://kb.adguard.com/en/general/adguard-filter-policy). Fix will stay in our lists.
