### ISSUE TITLE
finviz.com: ads

### ISSUE THREAD

**Issue by georgeshemtov** [uBlockOrigin/uAssets#15454]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://finviz.com/screener.ashx?v=111&f=an_recom_buybetter,sh_opt_option,ta_highlow52w_a0to10h,ta_rsi_os40,targetprice_above&ft=4&o=-volume&r=21`

### Category

ads

### Describe the issue

They have banner ads on top and bottom of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86703
  cosmetic: 38525
  scriptlet: 18207
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62411-53, 10h.4m
    easyprivacy: 30818-1170, 10h.2m
    plowe-0: 3671-865, 5d.11h.38m
    ublock-abuse: 76-0, 8d.11h.53m
    ublock-badware: 4352-110, 3d.10h.15m
    ublock-filters: 33197-148, 3d.10h.14m
    ublock-privacy: 257-1, 8d.11h.37m
    ublock-quick-fixes: 423-21, 18h.4m
    ublock-unbreak: 1881-42, 3d.10h.13m
    urlhaus-1: 8916-0, 18h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 402 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
That's self advertisement, we don't block that.

`finviz.com##[href^="/elite.ashx"] > picture`

**Comment by georgeshemtov** [comment]
But how can I use your Zapper tool to PERMANENTLY block an element like this?   
  

  
Because I zap it and then he. I refresh the page everything I have zapped loads again    
  
  
  
  
  
  
  

  
  
>

**Comment by energizat** [comment]
![image](https://user-images.githubusercontent.com/116905165/198696207-fafee7f1-5e78-4ac8-b0b7-1c5fa67b6aab.png)
or
![image](https://user-images.githubusercontent.com/116905165/198696262-1894a655-9e29-4fea-8831-5653b297a04a.png)

**Comment by okiehsch** [comment]
>  use your Zapper tool to PERMANENTLY block an element like this?

You can't the zapper is for a quick temporary removal only.
You have to use the "picker", highlighted in the helpful screenshot above.

**Comment by georgeshemtov** [comment]
Could the picker remove that element permanently?
  

  
Thanks   
  
  
  
  
  
  
  

  
  
>

**Comment by okiehsch** [comment]
Yes, but you can just add 
`finviz.com##[href^="/elite.ashx"] > picture`
to your filter list, that's why I mentioned it in my first post.

**Comment by georgeshemtov** [comment]
Thank you

I wish there was a better help files on such topics

Your app is amazing
