### ISSUE TITLE
[nsfw] sinparty.com: self-promotion, annoyances

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#15452]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sinparty.com/porn-videos/dana-vespoli-meet-s-alex-legend-video5f636c08742c9`

### Category

self-promotion, annoyances

### Describe the issue

Pre-roll ads (self-promotion). Not present in all videos. See also https://github.com/easylist/easylist/issues/13915

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-10-28_151911](https://user-images.githubusercontent.com/111344219/198585611-91d01d86-8022-47c9-b337-258d54576116.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 100053
  cosmetic: 125803
  scriptlet: 23887
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31519-27, 1h.7m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1530-24, 1h.7m
    fanboy-cookiemonster: 42167-283, 1h.7m
    ublock-annoyances: 4716-52, 1h.7m
  default: 
    user-filters: 7-0, never
    RUS-0: 40412-147, 1h.7m
    easylist: 62414-81, 1h.7m
    easyprivacy: 30817-1589, 1h.7m
    ublock-abuse: 76-1, 1h.7m
    ublock-badware: 3938-103, 1h.7m
    ublock-filters: 32237-183, 1h.7m
    ublock-privacy: 260-8, 1h.7m
    ublock-quick-fixes: 435-21, 1h.7m
    ublock-unbreak: 1873-45, 1h.7m
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 414 ms (selfie)
  maxAssetCacheWait: 631 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    sinpartycdn.com: 1
```
</details>

**Comment by okiehsch** [comment]
````
||content.sinpartycdn.com/videos-ads/*$media,redirect=noopmp4-1s,domain=sinparty.com
||content.sinpartycdn.com/*pre-roll-ads/*$media,redirect=noopmp4-1s,domain=sinparty.com
````
does this work?
