### ISSUE TITLE
zone-annuaire.sbs: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15457]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zone-annuaire.sbs/`

### Category

nuisance

### Describe the issue

The site having changed its domain name, the problems came back.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/198691780-67584243-50ef-445d-92e4-ffb1d6106849.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 616513
  cosmetic: 149797
  scriptlet: 36610
  html: 0
listset (total-discarded, last updated): 
  default: 
    FRA-0: 30931-63, 2m
    easylist: 62416-1045, 2m
    easyprivacy: 30820-14383, 2m
    plowe-0: 3669-1041, 2m
    ublock-abuse: 76-2, 2m
    ublock-badware: 3943-250, 2m
    ublock-filters: 32244-3603, 2m
    ublock-privacy: 260-45, 2m
    ublock-quick-fixes: 432-33, 2m
    ublock-unbreak: 1873-96, 2m
    urlhaus-1: 11029-6, 2m
filterset (user): [array of 2093 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 1331 ms (selfie)
  maxAssetCacheWait: 994 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    zone-annuaire.sbs: 1
    herhomeou.xyz: 1
    mailerstalons.com: 1
    onsequentlys.xyz: 1
    pogothere.xyz: 2
    slieemem.xyz: 4
```
</details>

**Comment by okiehsch** [comment]
@alex-302
`||zone-annuaire.sbs/main.js$script,1p`

**Comment by okiehsch** [comment]
No, are there more?

**Comment by okiehsch** [comment]
If there are more, 
`||zone-annuaire.*/main.js$script,1p`
will work for all.

**Comment by okiehsch** [comment]
After you added `||zone-annuaire.*/main.js$script,1p`?
