### ISSUE TITLE
newscon.net: detection

### ISSUE THREAD

**Issue by Trashycount** [uBlockOrigin/uAssets#15450]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.newscon.net/downloader/`

### Category

detection

### Describe the issue

When its detected it doesnt let me type in the text box even after turning on annoyance filters from previous issue posts 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 92598
  cosmetic: 40155
  scriptlet: 37750
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24148-27, 5h.32m
    ublock-annoyances: 4717-43, never
  default: 
    user-filters: 9-0, never
    easylist: 62400-58, 5h.31m
    easyprivacy: 30817-1170, 5h.30m
    plowe-0: 3671-865, 5h.36m
    ublock-abuse: 76-1, 5h.35m
    ublock-badware: 3938-105, 5h.29m
    ublock-filters: 32234-2856, 5h.28m
    ublock-privacy: 260-1, 5h.34m
    ublock-quick-fixes: 423-26, 5h.26m
    ublock-unbreak: 1872-43, 5h.27m
    urlhaus-1: 11291-0, 5h.25m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 427 ms (selfie)
  maxAssetCacheWait: 315 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    btloader.com: 1
    doubleclick.net: 1
    fuseplatform.net: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    sentry-cdn.com: 1
```
</details>

**Comment by okiehsch** [comment]
> When its detected it doesnt let me type in the text box

I can type in the text box without issue.

**Comment by Trashycount** [comment]
did you stay on the page for more than a minute for me when im typing into the box if i type long enough it kicks me off and i cant re click on the text box

**Comment by okiehsch** [comment]
Ok, I see what you mean, after some time the detection kicks in and then I can't type anymore.

**Comment by Trashycount** [comment]
yes that was my issue sorry for not being clearer

**Comment by okiehsch** [comment]
No problem.
Does it work if you add
`newscon.net##+js(nosiif, checkads)`
to your filter list?

**Comment by Trashycount** [comment]
Been using it for a few minutes and it looks like it has thank you!
