### ISSUE TITLE
inf-oge.sdamgia.ru: privacy

### ISSUE THREAD

**Issue by Alluseri** [uBlockOrigin/uAssets#15464]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://inf-oge.sdamgia.ru/`

### Category

privacy

### Describe the issue

This website successfully loads a tracker script w/ adblock detection.
<details>
<summary>Current tracker script URL(might change soon; very long)</summary>
https://sdamgia.naydex.net/1D0sG0199/266f3158uo/D73jjyU-aEEhYR5R92C76tAyLT5oj8KMpS5aqclBQygTgdu2rDVt2VIz3sl75uYSNqSnfV6kwvfaNmyGcMb4lTGnt8YnIntFe3sZHfdovKWHITYFUtefpocWBrHab0EFJt7BgYw4B9RFf9_HT5j6GRClk2JbgcfeyDBfpm7G27I5t6HIbDtTTD5BFTvNSpaQzDclClWauqm2Dzqj83RmMzLj3b6gCALXcHbm1HqwzzUvs4JbdZLK3fYSX7Fy19KXKoCL0UIvUnE2fzk61UqgkuAmGzFnlLmjlzQRs9xyYi0I_tiErzUK0XRfy9JLrcc6ILOPY16x19LjP2mCdOjtsBGpoNJ7H0t1LVAaDdZFgpbgMCUgZri7jIMyIqr7eWMDFeLfvJIRAvhgeMPYTYrQIAS7kENXos3w0ixWrFjG3Yo7l5TIbxlEajRyNBPIbriM2CMhP3WSn4GkHQyj-lpkAinD9KSKOAHqVH3cy1WP_xQxoap3V43e0fQdZ4Br3vWbCKio-GMpUVgFahQ90Hi5g_MrJABOoLSluioCnf9TVC4ex8yeoi0K2G5VxcVLqMAZHoWVe0WY_sT1DXKaTuTpqiW4ved9BHR2OU4tH_tlmqPxPzYOQpyGi4wUEZnxSnUCJuXvhL0XIvV4ZePQfqvfBgGOpVlqj8vv3xhFgFbu8KkJvb73RD1rZTNMER7xab-z5DE0NXqnva2hMxi08WNWIAr63qKLGifeaUDK5l6K8iUnvJhxXarFzuk3daBm-9SMFb2J1WIbdlQfTB8m2VygveoGBhJmtpa0ljIzvsppRTAx_cC6lxcL-UNi4dl2kOUwJrOmRkmN98LKBH6gVMvVjDq7iNRmNGtiBkseFfBXraPHBgIedaSglaItFKPOVFMQPcTYmqQaE9RrWMHGfov_PiCtlV5ssfL1_h5nsHfC6445hYvYaQJXcCZqOCzQa5ux2Rc2G3W0g4eOPCed2VhBMyfY2bCRETT4Z0_DzE2P3ScxhKJlfajF2vAZUIVs_8qSOpixyXICbnIUXRUr70i7guIcFCxJspSmrCojgNpVYyYA7PyUqRkx5FdcxPVWmMICD6aufnKLz-_uIFyqZdnYvhWHv9RBG3tYBUsRF9l4g5POGCQtT7u9qKYCIZDKb1EbJsDGpawMLftmZMPjapfbHi6ek21er_Lb6Q1dgGT1x60Wo4H6SDhWRTFlHzXyW5ahxD0AMW-zv6SWOyWW50NEMgXbxaK3IyX4YGHF9mWi5ScjqIxMdILk3PQZeaVu49ukE5a370UUX0syRjI3zG29s8ARFCB4p4GgoxU6ktFIWAMFwNCnrTUn1WlY98VlrMw1ALCwY3Sp1eTRPkKqTerznRK7rMdtGGx1MmYRMPZ2mZTtPCczb5-OqakpP6r1R0UACOzjjoceDN9jfc_GZpPCJjytrXd2l_rn6SdCqFTd25cdnZ_oXihYaAFGNjL9Z5mA7zkoDmemv6yPETOT31VdMRHe2YGRKAXRRnnc9XGOxCIjhJdnbJfI3MoRVKR2wNOePbmfxlM9fUU-ThoE9FadvuADJClrhIa3pgw2nvNmQgg79viurQwF8HFZ_8xLi9QaNKehUGyL2fH8JmKuRen3tjWjsfFYPn5LB14KJP95orzPGDUAfK-tpoEKJLHoWFwXBevxgZQXAfl4f-3Me73gHRmPhH5NqvLk9T5VsFDqy6YMqorFYChWdRtZHDX5ZpKQzjg3MFWeoLqVPDKC2kl9KDrg0aeWAwb1Unvo6HmS3DQTjKJVSLTv0tomd5Nh_NGsMqqT7Ec8RnY2YgUbzX6ftM8gEApHoqSKpR0Fne9YWhMh1N2FiiM343ZA2spZuvMbPI2rYXyR2NzLEkCFV-bIqDyvndFFH3paAHARBNBjsrLRATsKbL6GuKsOMZzXaVI2IPzghZcYMP50fPT0ZovFHhmKgWZ4vuXz3yJZo1TM6YkFvYzxTwREayBcMwXteaSs5z8QKEC9gaO2Nhs
</details>
This script resides at (what seems to be) one of the CDNs of the website, so blocking the whole naydex.net domain *might* cause content issues. The request to this script is detected by DevTools as an XHR. One of the realistic approaches to block this would be checking the response for keywords such as (not an exhaustive list) "UNKNOWN", "NOT_BLOCKED", "ADBLOCK", "ADBLOCKPLUS", "ADGUARD", "UBLOCK", "GHOSTERY", "UK", "FF_PRIVATE", "KIS", "EXPERIMENT", "BRAVE", "UCBROWSER", "ADBLOCK_BROWSER", "OPERA_BROWSER", "DNS".

I understand that this might not be a filter issue, as filters *from what I know* can't filter past URL schemes, but this doesn't seem relevant to uBO itself.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![XHR](https://cdn.nest.rip/uploads/615a543c-f0e6-4c4c-bb78-b94d14bd3200.png)
![Source](https://cdn.nest.rip/uploads/aaaf7544-c918-40fc-b2bc-5f4216361722.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 102
filterset (summary): 
  network: 111501
  cosmetic: 58267
  scriptlet: 19703
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29201-674, 2d.21h.48m
    RUS-0: 40415-4341, 16h.6m
  default: 
    user-filters: 2-0, never
    easylist: 62002-17341, 7d.51m
    easyprivacy: 30818-1304, 23h.8m
    plowe-0: 3671-872, 7d.55m
    ublock-abuse: 76-1, 7d.48m
    ublock-badware: 4352-104, 2d.21h.47m
    ublock-filters: 32683-362, 2d.21h.45m
    ublock-privacy: 257-2, 7d.46m
    ublock-quick-fixes: 435-21, 9h.5m
    ublock-unbreak: 1881-43, 2d.21h.46m
    urlhaus-1: 8916-0, 23h.7m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 23524 ms (selfie)
  maxAssetCacheWait: 5743 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    mail.ru: 1
    yandex.ru: 4
    yastatic.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see any anti-adblock on the site.

About `naydex.net`, blocking

```adb
||sdamgia.naydex.net^$xhr,domain=inf-oge.sdamgia.ru
```

still makes the site works fine for me, but I'm not sure if there would be any other breakages or not.

@dimisa-RUAdList Sorry, can you check this issue?

**Comment by Alluseri** [comment]
> ```
> ||sdamgia.naydex.net^$xhr,domain=inf-oge.sdamgia.ru
> ```

Ah, the way you blocked it is really clever. As everything else fetched from this CDN are direct href/src tags, this is the only script that gets filtered. The filter works, thank you.
