### ISSUE TITLE
www2.kickassanime.ro: ads

### ISSUE THREAD

**Issue by cloudbogus** [uBlockOrigin/uAssets#15462]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www2.kickassanime.ro/`
![kickassanime ads](https://user-images.githubusercontent.com/116935229/198813916-af0f06ff-2ec7-40bf-84cb-7609fc30f787.jpg)

### Category

ads

### Describe the issue

there is an ads popping at the lower left corner of the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![kickassanime ads](https://user-images.githubusercontent.com/116935229/198813944-1278bfbc-2280-407b-aa36-33828b3e9dee.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 88939
  cosmetic: 38412
  scriptlet: 18204
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62279-53, 4d.6h.7m
    easyprivacy: 30781-1172, 4d.6h.6m
    plowe-0: 3671-865, 20h.59m
    ublock-abuse: 76-0, 2d.5h.58m
    ublock-badware: 4352-109, 3d.6h.3m
    ublock-filters: 33111-148, 3d.6h.2m
    ublock-privacy: 260-1, 2d.5h.57m
    ublock-quick-fixes: 423-21, 20h.57m
    ublock-unbreak: 1879-42, 3d.6h.1m
    urlhaus-1: 11291-0, 20h.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 271 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    cdnativepush.com: 2
    googletagmanager.com: 1
    offerimage.com: 2
    outoctillerytor.com: 1
    pubfuture.com: 4
    tzegilo.com: 1
```
</details>

**Comment by ghajini** [comment]
fixed a days back, update your filters
