### ISSUE TITLE
[nsfw] altblogger.net: detection

### ISSUE THREAD

**Issue by cleuton4k** [uBlockOrigin/uAssets#15468]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://altblogger.net/best-wordpress-malware-scanner-and-vulnerability-scanner-tools/`

### Category

detection

### Describe the issue

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 133446
  cosmetic: 217271
  scriptlet: 34871
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 40419-10, 3m
    adguard-annoyance: 60324-488, 3m
    adguard-generic: 64491-638, 3m
    curben-pup: 192-0, 3m
    fanboy-annoyance: 81987-3849, 3m
    spa-1: 4816-84, 2m
  default: 
    user-filters: 18-0, never
    easylist: 62526-764, 3m
    easyprivacy: 30826-1444, 3m
    plowe-0: 3669-884, 2m
    ublock-abuse: 76-1, 2m
    ublock-badware: 3953-239, 2m
    ublock-filters: 31135-3692, 2m
    ublock-privacy: 260-9, 2m
    ublock-quick-fixes: 433-33, 2m
    ublock-unbreak: 1875-85, 2m
    urlhaus-1: 11029-0, 2m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 72 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 42 redacted]
hostRuleset: 
  added: [array of 141 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  allReadyAfter: 663 ms (selfie)
  maxAssetCacheWait: 688 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    altblogger.net: 1
    googlesyndication.com: 1
    papayads.net: 1
    unpkg.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Is it a redirection from another link?

**Comment by stephenhawk8054** [comment]
Example link from `https://www.reddit.com/r/uBlockOrigin/comments/ygt18i/`

`https://stfly.me/4NgrM`

Fixed in https://github.com/uBlockOrigin/uAssets/commit/23e1783c6a45723494b52e7bb06c85835f3c9cd2

Can you force update the filter lists and test again?
