### ISSUE TITLE
boundingintocomics.com: ads

### ISSUE THREAD

**Issue by jallen1227** [uBlockOrigin/uAssets#15467]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
````
https://boundingintocomics.com/2022/10/21/rumor-marvel-scaling-back-black-panther-wakanda-forever-merch-plans-out-of-concern-that-sequels-lack-of-tchalla-may-alienate-black-male-audiences/
````

### Describe the issue

Can't block the side ads with uBO even when I attempt to block elements (both just the element itself which reposts the exact same image a few seconds later or even if I attempt to use wildcards)

### uBlock Origin version

1.44.4

### Browser name and version

Chrome Version 106.0.5249.119 

### Settings

None

**Comment by okiehsch** [comment]
`||lalerent.site^3p`

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/725de727f5a2436e231960ba90422f8c1fc67405
