### ISSUE TITLE
ios.codevn.net: detection

### ISSUE THREAD

**Issue by BHXMXT** [uBlockOrigin/uAssets#15460]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ios.codevn.net/category/ipa/`

### Category

detection

### Describe the issue

can't access the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 89512
  cosmetic: 39533
  scriptlet: 17935
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 6-0, never
    VIE-1: 2028-0, 15h.49m
    easylist: 62309-72, 2d.23h.53m
    easyprivacy: 30807-1175, 2d.23h.52m
    plowe-0: 3675-865, 12d.7h.45m
    ublock-abuse: 76-0, 4d.2h.2m
    ublock-badware: 4352-109, 1d.15h.53m
    ublock-filters: 32463-140, 1d.15h.52m
    ublock-privacy: 260-1, 4d.2h.1m
    ublock-quick-fixes: 423-21, 10h.13m
    ublock-unbreak: 1872-42, 1d.15h.51m
    urlhaus-1: 11291-0, 15h.48m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 198 ms (selfie)
  maxAssetCacheWait: 191 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    codevn.net: 1
    adskeeper.co.uk: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce it either. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking softwares outside browser,
- OS' hosts file to block domains.

**Comment by nqlp** [comment]
Steps to reproduce: 

1. Go to: `https://ios.codevn.net/`
2. Clear your cookies and site data if you have already visited the website before
3. Click on the search icon
4. Website opens a new tab on: 

```yml
https://pages.lazada.vn/wow/gcp/route/lazada/vn/upr_1000345_lazada/channel/vn/upr-router/vn?at_iframe=1&data_prefetch=true&disable_pull_refresh=true&disable_smb=true&downgrade=redirect&force_ssr_render=true&hide_h5_title=true&hybrid=1&laz_trackid=2%3Amm_198321232_58653076_2017603088%3Aclkgikrap1j782gjtud6p1&lzd_navbar_hidden=true&mkttid=clkgikrap1j782gjtud6p1&prefetch_replace=1&trafficFrom=17449020_303586&wh_pid=%2Flazada%2Fchannel%2Fvn%2Fshopping-guide%2Flazflash&wx_navbar_transparent=true
```

<details>

<img width="1919" height="924" alt="Image" src="https://github.com/user-attachments/assets/44f841d8-529d-4175-b00f-a6265b6f2304" />

</details>

4. Click "X" on the search dialogue: 

<details>

<img width="680" height="199" alt="Image" src="https://github.com/user-attachments/assets/3123e98e-e37f-4953-b23a-4ffe6cbac286" />

</details>

5. It opens a new tab: https://apps.apple.com/us/app/songsnap-ai-music-maker/id6749604701

<details>

<img width="1919" height="929" alt="Image" src="https://github.com/user-attachments/assets/306b285d-4f9b-47c0-9858-656672a13ac6" />

</details>

<details>

```yml
uBlock Origin: 1.66.4
Chromium: 141
filterset (summary):
 network: 182786
 cosmetic: 167771
 scriptlet: 43178
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 88511-353, now
  FRA-0: 19402-34, now
  fanboy-cookiemonster: 46451-3952, now
  fanboy-thirdparty_social: 69-0, now
  ublock-annoyances: 4679-157, now
  adguard-cookies: 35561-35561, now
  ublock-cookies-adguard: 5103-81, now
  ublock-cookies-easylist: 5103-5103, now
  adguard-popup-overlays: 28564-28564, now
  adguard-mobile-app-banners: 6386-6386, now
  adguard-other-annoyances: 15036-15036, now
  easylist-annoyances: 5204-448, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 22-0, never
  easylist: 81225-371, 1h.32m
  easyprivacy: 54680-762, 32m Δ
  plowe-0: 3437-23, now
  ublock-badware: 11012-74, now
  ublock-filters: 41137-476, now
  ublock-privacy: 3515-9, now
  ublock-quick-fixes: 374-1, now
  ublock-unbreak: 2682-39, now
  urlhaus-1: 31750-5, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 207 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  codevn.net: 4
  d3lppnezw695ey.cloudfront.net: 1
  googletagmanager.com: 1
 extended:
  ##+js(prevent-setInterval, offsetHeight)
```

</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPVN List` list and test again.

**Comment by nqlp** [comment]
Sometimes, when I click on the search icon and click outside of the box dialogue, this tab opens: 
https://apps.apple.com/us/app/songsnap-ai-music-maker/id6749604701

**Comment by stephenhawk8054** [comment]
Test

```adb
ios.codevn.net##+js(rmnt, script, /popup/i)
```

**Comment by nqlp** [comment]
> Test
> 
> ios.codevn.net##+js(rmnt, script, /popup/i)

Thanks, it works!
