### ISSUE TITLE
thetimes.co.uk: breakage

### ISSUE THREAD

**Issue by tomhusband** [uBlockOrigin/uAssets#15463]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.thetimes.co.uk/article/james-corden-interview-catlin-moran-late-late-show-v5sf2vnpb`

### Category

breakage

### Describe the issue

Two images attached. One with uBlockOrigin and one without. When it's turned on photos seem to be very low resolution, turn it off and they're clear. This only happens with thetimes.co.uk/ website.
edit: This happens with all the pages on this site not just this link. I hope the screenshots are uploaded, I don't see them.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 87707
  cosmetic: 38586
  scriptlet: 18053
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62002-53, 3d.22h.36m
    easyprivacy: 30807-1170, 3d.22h.35m
    plowe-0: 3675-865, 10d.12h.55m
    ublock-abuse: 76-0, 12d.41m
    ublock-badware: 3938-100, 23h.45m
    ublock-filters: 32731-109, 23h.44m
    ublock-privacy: 256-1, 12d.40m
    ublock-quick-fixes: 423-21, 1d.11h.11m
    ublock-unbreak: 1872-42, 16h.52m
    urlhaus-1: 11084-0, 1d.11h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 19 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1570 ms (selfie)
  maxAssetCacheWait: 513 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    thetimes.co.uk: 3
    google.com: 6
    newrelic.com: 1
    unrulymedia.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I see paywall so the rest of the article is hidden. The first image appears normal for me

![image](https://user-images.githubusercontent.com/66517106/198818890-074dbce7-1816-461f-915a-804387902bf8.png)

Are you signing in with an account, or are you using other extensions?

**Comment by Desmo46** [comment]
This is still an issue that I can reproduce, disabling uBlock does indeed fix the issue

**Comment by stephenhawk8054** [comment]
> This is still an issue that I can reproduce, disabling uBlock does indeed fix the issue

Are you signing in to the page? Which region are you when accessing to the site?

**Comment by Desmo46** [comment]
Yes I am signed in and am accessing from Europe.

Digging in a little deeper it seems disabling EasyAd and EasyPrivacy fixes this issue as well as [https://github.com/uBlockOrigin/uAssets/issues/14655](url)

**Comment by mapx-** [comment]
@Desmo46 
Are you willing to communicate your account credentials to us in order to find a fix ? (I'll indicate how to do this in a private manner)

**Comment by Desmo46** [comment]
Is there an alternative via screenshare or the like?

**Comment by mapx-** [comment]
It would only a long guess process without the possibility to test the changes.

send your account / pass here: `axis.trivia@gmail.com`
