### ISSUE TITLE
goplay.be: detection

### ISSUE THREAD

**Issue by KasperMusca** [uBlockOrigin/uAssets#15476]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goplay.be/video/de-tafel-van-vier/de-tafel-van-vier-s1/de-tafel-van-vier-s1-aflevering-2`

### Category

detection

### Describe the issue

The media player does not work when ublock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 85985
  cosmetic: 38321
  scriptlet: 16585
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.12h.50m
  default: 
    user-filters: 5-0, never
    easylist: 62370-53, 2d.16h.30m
    easyprivacy: 30777-1172, 2d.16h.31m
    plowe-0: 3675-865, 9d.19h.20m
    ublock-abuse: 76-0, 9d.19h.22m
    ublock-badware: 3943-105, 1d.12h.51m
    ublock-filters: 31112-130, 1d.12h.53m
    ublock-privacy: 257-1, 9d.19h.21m
    ublock-quick-fixes: 433-21, 12h.46m
    ublock-unbreak: 1873-42, 1d.12h.52m
    urlhaus-1: 8916-0, 12h.47m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 35 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1273 ms (selfie)
  maxAssetCacheWait: 238 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    goplay.be: 1
    cxense.com: 1
    doubleclick.net: 5
    gemius.pl: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    onthe.io: 1
    scriptcdn.net: 1
    summerhamster.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `NLD: EasyDutch` list and test again?
