### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by Xoce-Montepoc** [uBlockOrigin/uAssets#15471]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vk.com/`

### Category

breakage

### Describe the issue

Any page of the VK social network, with the extension enabled, starts consuming memory without stopping. If the extension is disabled, then the tab consumes no more than 300 MB of memory. When enabled, the value of consumed memory can reach up to 2 GB. To check, I removed all third-party extensions, uBO continues to consume memory.
Below I inserted some technical information that may be useful.

```
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 122064
  cosmetic: 98769
  scriptlet: 30192
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64485-617, 9h.38m
    adguard-mobile: 8206-60, 9h.38m
  default: 
    user-filters: 10-2, never
    RUS-0: 40418-10, 9h.38m
    easylist: 62491-901, 9h.38m
    easyprivacy: 30823-1394, 9h.38m
    plowe-0: 3669-966, 9h.38m
    ublock-abuse: 76-1, 9h.38m
    ublock-badware: 3943-239, 9h.38m
    ublock-filters: 31126-3299, 9h.38m
    ublock-privacy: 260-1, 9h.38m
    ublock-quick-fixes: 433-33, 9h.38m
    ublock-unbreak: 1875-79, 9h.38m
    urlhaus-1: 11029-0, 9h.38m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11069 ms
  maxAssetCacheWait: 1506 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    vk.com: 2
    mail.ru: 4
    tns-counter.ru: 1
    vk-portal.net: 1
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 122064
  cosmetic: 98769
  scriptlet: 30192
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 64485-617, 9h.38m
    adguard-mobile: 8206-60, 9h.38m
  default: 
    user-filters: 10-2, never
    RUS-0: 40418-10, 9h.38m
    easylist: 62491-901, 9h.38m
    easyprivacy: 30823-1394, 9h.38m
    plowe-0: 3669-966, 9h.38m
    ublock-abuse: 76-1, 9h.38m
    ublock-badware: 3943-239, 9h.38m
    ublock-filters: 31126-3299, 9h.38m
    ublock-privacy: 260-1, 9h.38m
    ublock-quick-fixes: 433-33, 9h.38m
    ublock-unbreak: 1875-79, 9h.38m
    urlhaus-1: 11029-0, 9h.38m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11069 ms
  maxAssetCacheWait: 1506 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    vk.com: 2
    mail.ru: 4
    tns-counter.ru: 1
    vk-portal.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The memory looks stable for me

With uBO enabled:
<details>

![3](https://user-images.githubusercontent.com/66517106/198857340-caf0800b-f5ee-4e86-84e5-31cfe527a927.png)

</details>

With uBO disabled:
<details>

![4](https://user-images.githubusercontent.com/66517106/198857357-e607ce64-21ce-406d-adc6-3b6dc8d01afb.png)

</details>

@dimisa-RUAdList Sorry can you reproduce the issue?

---

@gorhill Somehow the timing is quite large

```yaml
supportStats: 
  allReadyAfter: 11069 ms
  maxAssetCacheWait: 1506 ms
```

**Comment by dimisa-RUAdList** [comment]
I don't see anything unusual there when using uBlock Origin with default settings.

**Comment by Xoce-Montepoc** [comment]
I just reset all settings to zero, but the memory is still consumed.

**Comment by Xoce-Montepoc** [comment]
> Can be browser problem or the number of tabs you have opened

Specially closed all tabs except VK, memory is still being consumed.
I must say right away that the Kaspersky Protection extension was removed before creating the topic, without it the problem of memory consumption still persisted.
I tested the same extension in Firefox and there the memory also began to grow, but not as sharply and monotonously as in Chrome.
![2](https://user-images.githubusercontent.com/116981277/198868284-8776a280-2b11-4b55-a399-1d098266c840.png)
![3](https://user-images.githubusercontent.com/116981277/198868789-eaab2964-8f05-4c81-84f9-ccfa557d75b5.png)

**Comment by gwarser** [comment]
Something is repeatedly blocked in the logger? Can you try recording performance profile?

**Comment by Xoce-Montepoc** [comment]
> Can you try recording performance profile?

How to do it?

**Comment by gwarser** [comment]
https://developer.chrome.com/docs/devtools/evaluate-performance/reference/

**Comment by Xoce-Montepoc** [comment]
> https://developer.chrome.com/docs/devtools/evaluate-performance/reference/

Ready. Attached the recording file in the archive.
I opened the problematic tab, clicked record, scrolled through the news feed a bit, returned to the home page, and kept the tab open for a couple of minutes.
[Profile-20221030T133718.zip](https://github.com/uBlockOrigin/uAssets/files/9895626/Profile-20221030T133718.zip)

**Comment by gorhill** [comment]
This is your issue: [Kaspersky Protection](https://chrome.google.com/webstore/detail/kaspersky-protection/ahkjpbeeocnddjkakilopmfdlnjdpcdm).

**Comment by Xoce-Montepoc** [comment]
> This is your issue: [Kaspersky Protection](https://chrome.google.com/webstore/detail/kaspersky-protection/ahkjpbeeocnddjkakilopmfdlnjdpcdm) -- at least it shows being the largest CPU usage, we are talking many seconds here, compared to uBO with below 1-second usage for the whole 200s.

I gave an example above that even if the Kaspersky extension is deleted, memory consumption is still growing. Here then is another performance entry, with the extension removed. The algorithm of actions is the same: i opened the problematic tab, clicked record, scrolled through the news feed a bit, returned to the home page, and kept the tab open for a couple of minutes.
[Profile-20221030T150121.zip](https://github.com/uBlockOrigin/uAssets/files/9895723/Profile-20221030T150121.zip)

**Comment by gorhill** [comment]
I still see huge amount of the Kaspersky stuff in your profile:

![Screenshot from 2022-10-30 08-15-54](https://user-images.githubusercontent.com/585534/198878010-50b543f1-04f3-4c6b-9fb1-cef33f967ced.png)

And worse it seems that each event is taking more and more time.

uBO itself is virtually a noop compared to what I see from Kaspersky.

**Comment by Xoce-Montepoc** [comment]
> I still see huge amount of the Kaspersky stuff in your profile:
> 
> And worse it seems that each event is taking more and more time.
> 
> uBO itself is virtually a noop compared to what I see from Kaspersky.

It's very strange that after removing the extension, it still shows up. But when removing uBO and active expansion from Kaspersky, the memory of the tab does not increase. Now I'll try to record two profiles with the Kaspersky extension removed: disable the antivirus and restart Chrome; restart the system and leave the antivirus enabled. Then I will make an addition to this message with files.

**Comment by stephenhawk8054** [comment]
Antivirus software can interfere with browser's activities even when you don't use their extensions, depending on the configurations you are setting up in their software. You should try testing again in another machine with no antivirus.

**Comment by Xoce-Montepoc** [comment]
The problem was solved, for now temporarily. I left the Kapersky extension enabled, but in its settings I allowed the collection of data on the VK website, now the memory of the tab does not grow, but advertising does not appear either. I chose this path because I didn’t find anything like that in the antivirus settings, everything was set to default values. Thank you all for your help.
