### ISSUE TITLE
[badware] vlc.de

### ISSUE THREAD

**Issue by stonecrusher** [uBlockOrigin/uAssets#1547]
### URL(s) where the issue occurs
`https://www.vlc.de/`

### Describe the issue
This (known) scam for german speaking community exists for years now and still not blocked...
They bundle OpenSource software together with their malware and make it look official (although there already exists an [official german VLC page](https://www.videolan.org/vlc/index.de.html)).
They somehow manage to stay in the top results when searching on google. People like to click `vlc.de` easier than `videolan.org` when trying to get the VLC player.

Mainly scam for VLC Player (obviously), but also [Open Office, PDF-Drucker, Iron Browser, Songbird, Thunderbird, Gimp, Notepad++, 7-Zip, Libre Office](https://www.vlc.de/download/).
```
VLC official build:
vlc-3.0.0-win32.exe   37.1 MB

vlc.de build:
vlc-3.0.0-win32.exe   37.4 MB
```

### Proof
Virustotal only has [one match](https://www.virustotal.com/#/file/5320cbaf8ce2b48cde4fb10af761315a0d19a7d7084db3424dff3ea618b46e3e/detection) for the new VLC 3.0 version, but the [summary for the whole domain](https://www.virustotal.com/#/domain/vlc.de) shows the red line and community reports go back to [2008](https://www.trojaner-board.de/66529-warnung-vlc-player-vlc-de-adware-mehr.html)...

In their own [vlc.de forum](https://www.vlc-forum.de/thread/1723-wieso-vlc-de/) they try to justify by citing their licence and general business terms and stuff... but actually the guy opening the thread is completely right.

Licence:
> Das Installationsprogramm verändert an Ihrem PC die Startseite von verschiedenen Browsern, sowie das Suchfeld. 

Translation:
> The installation program changes the homepage of different browsers as well as the search field on your PC.

[Tons of results for search](https://www.google.de/search?q=site%3Atrojaner-board.de+"vlc.de") on german speaking malware help forum.

**Comment by okiehsch** [comment]
The `7zip`, `notepad++` files etc do not bundle anything, as far as I can see. the only files with different hashes than the original are the `vlc-player` ones, which do have a different digital signature, the site is quite open about what their version of `Videolan` does.

![unbenannt](https://user-images.githubusercontent.com/16838044/36289087-5018e1be-12be-11e8-9ee3-6cb36fe25018.JPG)

The part below the bolded part means that the homepage in your browser will be changed and you can prevent this by disabing that option during the installation process -- it will be enabled by default.
It then links to a

@gorhill what do you think, should this site be added to the badware list?

**Comment by SMed79** [comment]
@okiehsch 
> you can prevent this by disabling that option during the installation process

Not sure if the normal user will read or change something.


@stonecrusher 
**Unchecky** is a recommended software if you are a windows user https://unchecky.com/

**Comment by stonecrusher** [comment]
You're right - I didn't test the other programs by myself, just read about it. Just checked 7-zip which looks ok. However this is not a trustworthy site. It tries to look like an official vlc site very hard.

And I didn't see that by now they put a warning in the text above the download button.

Actually I think that's (unfortunately) normal behaviour for most people:  
Search for vlc, click the most promising and appropiate url (so short! And who even knows vlc is somehow related to "videolan") - cool, there's already the big downloadbutton. Get it!

The directive should be to protect the everyday user.
@SMed79 I don't fall for that but already had to revert it from my relatives' PCs a few times.

**Comment by okiehsch** [comment]
> Not sure if the normal user will read or change something.

I am pretty sure that the "normal" user that downloads any installer double clicks it and then clicks "OK" anytime he/she can. 😉

**Comment by stonecrusher** [comment]
Just documenting in case for the future:

- There is no note on `vlc.de` directly (which also offers the direct download), only on `vlc.de/vlc_download.php`
- People obviously [don't want](https://www.google.de/search?q=site%3Atrojaner-board.de+%22vlc.de%22) the bundled PUPs like `Startfenster`, `VLC Updater`, `GoodGame` or `Qweb`, they want the vlc player
- Page looks official by URL, menu color, favicon, same download name
- It's like a tourist scam - why should we accept this? It's worse than ads!

**Comment by gorhill** [comment]
It does look like a scammy site to me, as per @stonecrusher's arguments. The main purpose of the site, from the domain name to the design, is to deliver a tainted version of VLC.
