### ISSUE TITLE
nexusmods.com: breakage

### ISSUE THREAD

**Issue by tekknen** [uBlockOrigin/uAssets#15477]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nexusmods.com/`

### Category

breakage

### Describe the issue

i can't click on any item @ the bar menu, the drop down sub menu will not show up unless i disable this addon

### Screenshot(s)

<img width="1007" alt="Screenshot 2022-10-30 174508" src="https://user-images.githubusercontent.com/52892649/198884975-2d4e35ab-388d-47db-9ae6-007350918a9e.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 87033
  cosmetic: 38534
  scriptlet: 17734
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33015-32, 3d.11h.18m
    ublock-badware: 4356-0, 3d.11h.19m
    ublock-privacy: 288-0, 1d.11h.44m
    ublock-abuse: 76-0, 1d.11h.43m
    ublock-unbreak: 1885-0, 3d.11h.17m
    easylist: 62002-588, 4d.21h.14m
    easyprivacy: 30807-1722, 4d.21h.13m
    urlhaus-1: 10092-0, 10h.13m
    plowe-0: 3669-3, 1d.11h.41m
    ublock-quick-fixes: 429-21, 10h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 137 ms (selfie)
  maxAssetCacheWait: 65 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    nexusmods.com: 2
    googletagmanager.com: 1
    hotjar.com: 1
    quantserve.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists and test again

**Comment by okiehsch** [comment]
Fixed with https://github.com/uBlockOrigin/uAssets/commit/584065f17c305f9a002078a16fadf8c5c14cef2c three days ago.

**Comment by tekknen** [comment]
fixxed & thx u
