### ISSUE TITLE
Geo.de

### ISSUE THREAD

**Issue by steffanson** [uBlockOrigin/uAssets#1548]
### URL(s) where the issue occurs

`https://www.geo.de/natur/tierwelt/18407-bstr-die-besten-unterwasser-fotografien-des-jahres`

### Describe the issue

When uBo enabled, the website displays an overlay, which asks to disable the blocker.

### Screenshot(s)

![geo_anti_ad](https://user-images.githubusercontent.com/17642285/36263965-c27b1004-126b-11e8-81b4-f97dd24e5f75.png)

### Versions

- Browser/version: FF 57.0.2
- uBlock Origin version: 1.15.6

### Settings

- Default + EasyList Germany + Adblock Warning Removal List

### Notes

There are two these overlays with probably random names:
```
###sp_message_id1518707937267
##.sp_veil1518707937267
```

I guess the following script triggers the overlay:
`https://www.geo.de/sites/all/modules/custom/pier12_general_panel_panes/tracking/detector.min.js`

**Comment by steffanson** [comment]
Thanks @mapx- .

Just as a note for me and probably others:
In order to let this solution work, scripts of `0914.global.ssl.fastly.net` must not be blocked.

**Comment by okiehsch** [comment]
You can add
````
geo.de##script:inject(abort-on-property-read.js, _sp_._networkListenerData)
````
to your filters, then you do not have to worry about something blocking `914.global.ssl.fastly.net` requests on your end.

**Comment by steffanson** [comment]
@okiehsch Thanks, that works fine! What do you think about adding this line to the filter list?

**Comment by okiehsch** [comment]
There are exception filters for `fastly.net` in `EasyList`, which prevent the anti-adblock message.
What filter or configuration blocks those requests on your end?

**Comment by steffanson** [comment]
> What filter or configuration blocks those requests on your end?

Ah, never mind! I forgot to mention that I disallow all third parties scripts by default.

**Comment by Boersenfeger** [comment]
UpDate your Browser!!!
FF 58.0.2 ist uptoDate and in some Days FF 59.0 comes up
See here for Security-Informations:
https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/
https://www.mozilla.org/en-US/firefox/58.0.2/releasenotes/
and above

**Comment by garry-ut99** [comment]
The site is terrorized with ad placeholders all over the site caused by `ghide` from "uBlock filters" : [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/215520392-6525d1e7-3d7c-4484-abac-53731058ee00.gif)
