### ISSUE TITLE
outlook.live.com: breakage

### ISSUE THREAD

**Issue by Taurenpally** [uBlockOrigin/uAssets#15480]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outlook.live.com/`

### Category

breakage

### Describe the issue

<img width="510" alt="image" src="https://user-images.githubusercontent.com/93179068/198920642-32eb96be-100c-460a-b6e1-861d644c1613.png">
the To field is missing now unless turning off cosmic filtering which then shows ads back up again. 

<img width="507" alt="image" src="https://user-images.githubusercontent.com/93179068/198920748-a381ec9f-e247-432a-887f-458ad81700b9.png">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="510" alt="image" src="https://user-images.githubusercontent.com/93179068/198920642-32eb96be-100c-460a-b6e1-861d644c1613.png">
the To field is missing now unless turning off cosmic filtering which then shows ads back up again. 

<img width="507" alt="image" src="https://user-images.githubusercontent.com/93179068/198920748-a381ec9f-e247-432a-887f-458ad81700b9.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88258
  cosmetic: 38230
  scriptlet: 17528
  html: 779
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32969-32, 3d.40m
    ublock-badware: 3942-0, 3d.39m
    ublock-privacy: 288-0, 4h.42m
    ublock-abuse: 76-0, 4h.41m
    ublock-unbreak: 1886-0, 3d.38m
    easylist: 62630-627, 37m
    easyprivacy: 30831-1707, 36m
    plowe-0: 3669-3, 4h.43m
    urlhaus-1: 11029-0, 4h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 44 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 682 ms (selfie)
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 151
  no-cosmetic-filtering: true
  blockedDetails: 
    live.com: 3
    3lift.com: 3
    adnxs.com: 3
    microsoft.com: 53
    office.net: 87
    taboola.com: 2
```
</details>

**Comment by Purfekt** [comment]
Having the same issue as well. Not sure what it is since there's only 3 references to "outlook.live.com" within the "https://github.com/uBlockOrigin/uAssets" "uBlock filters" list. I turned off all over lists + element blocking, and it's for sure coming from that list.

It breaks mentioning the email recipients email. It's an issue if you use aliases within outlook and probably some other stuff as well.

**Comment by okiehsch** [comment]
I don't have an account, so I am just going by  `3 references to "outlook.live.com" within the  "uBlock filters" list`.
I see 2 filters that could cause it, can you try adding
````
outlook.live.com#@#.customScrollBar > div[class] > div[class]:empty
outlook.live.com#@#.customScrollBar > div *:not([draggable]) > div.full:not([aria-label]):not([data-convid]):not([role="option"]):not([tabindex]):not(.disableTextSelection):not([title])
````
to your filter list and check if it fixes the issue.

**Comment by Taurenpally** [comment]
> I don't have an account, so I am just going by `3 references to "outlook.live.com" within the "uBlock filters" list`. I see 2 filters that could cause it, can you try adding
> 
> ```
> outlook.live.com#@#.customScrollBar > div[class] > div[class]:empty
> outlook.live.com#@#.customScrollBar > div *:not([draggable]) > div.full:not([aria-label]):not([data-convid]):not([role="option"]):not([tabindex]):not(.disableTextSelection):not([title])
> ```
> 
> to your filter list and check if it fixes the issue.

yep that fixes it thanks

**Comment by Purfekt** [comment]
> I don't have an account, so I am just going by `3 references to "outlook.live.com" within the "uBlock filters" list`. I see 2 filters that could cause it, can you try adding
> 
> ```
> outlook.live.com#@#.customScrollBar > div[class] > div[class]:empty
> outlook.live.com#@#.customScrollBar > div *:not([draggable]) > div.full:not([aria-label]):not([data-convid]):not([role="option"]):not([tabindex]):not(.disableTextSelection):not([title])
> ```
> 
> to your filter list and check if it fixes the issue.

Thanks! Added that to "My Filters" under "! 2022-10-31 https://outlook.live.com" and all is well now.

**Comment by okiehsch** [comment]
As I can not test can you tell me if both of the filters are needed for the site to work as expected or only one of them?

**Comment by Taurenpally** [comment]
the 2nd line is all that is needed.

outlook.live.com#@#.customScrollBar > div *:not([draggable]) > div.full:not([aria-label]):not([data-convid]):not([role="option"]):not([tabindex]):not(.disableTextSelection):not([title])
