### ISSUE TITLE
xe.com: breakage

### ISSUE THREAD

**Issue by BrendenBourne** [uBlockOrigin/uAssets#15489]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.xe.com/`

### Category

breakage

### Describe the issue

Just a blank page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 86128
  cosmetic: 38358
  scriptlet: 16595
  html: 793
listset (total-discarded, last updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 3h.20m
  default: 
    user-filters: 2-0, never
    ublock-filters: 31863-32, 1d.1h.3m
    ublock-badware: 3957-0, 17h.2m
    ublock-privacy: 288-0, 5d.19h.15m
    ublock-abuse: 76-0, 5d.19h.14m
    ublock-unbreak: 1895-0, 17h.3m
    easylist: 62491-627, 2d.15h.56m
    easyprivacy: 30818-1707, 4d.7h.5m
    urlhaus-1: 8916-0, 1d.1h.2m
    plowe-0: 3671-3, 5d.19h.13m
    ublock-quick-fixes: 445-20, 1d.58m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 135 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    amplitude.com: 1
    googletagmanager.com: 1
    optimizely.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
It's normal for me

![image](https://user-images.githubusercontent.com/66517106/199218309-003048df-1160-4934-804b-ee6e67bc2fc4.png)

Can you force update the filter lists and test again? Also can you copy your custom filters in `My filters` to here?
