### ISSUE TITLE
crewus.net: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#15481]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crewus.net/how-to-develop-your-babys-brain/`

### Category

detection

### Describe the issue

Hi friends, this collection of websites detects uBlock as a shortcut tool to avoid timers on web pages.
If I'm at the end of the page the website displays a message stating I'm using an extension for a shortcut to another page.

- https://www.google.com/url?sa=t&source=web&rct=j&url=https://crewus.net/&ved=2ahUKEwix-I3L1qr3AhWGTWwGHZ9lAfMQFnoECAUQAQ&usg=AOvVaw2LGqaQnaJ3_J09rHVWH43o
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://shinchu.net/&ved=2ahUKEwjvjtzZ-ML2AhVtUWwGHZsBCCMQFnoECAUQAQ&usg=AOvVaw2_TUelhM0c6pWq9BlzORth
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://ultraten.net/&ved=2ahUKEwjGyYDt8sL2AhVdSmwGHVQQASgQFnoECAUQAQ&usg=AOvVaw030_qmMd5q4tWFIRMxDzR6
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://uniqueten.net/&ved=2ahUKEwj64tmfq4T5AhUO7zgGHT7aDFUQFnoECAYQAQ&usg=AOvVaw3VyFHNue2nNbvXPipK7k2C
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://allcryptoz.net/&ved=2ahUKEwjej7649ML2AhXfSWwGHbnsDxMQFnoECAQQAQ&usg=AOvVaw23PKfYFdLKuLMm9Ix-pMuJ
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://thumb8.net/&ved=2ahUKEwj9kdOW-cL2AhWwSGwGHbrFDOMQFnoECAMQAQ&usg=AOvVaw0wMSvG8S09tEdFLU5Td7rB
- https://topcryptoz.net/backup/w/?get=n8bUc&__cf_chl_tk=2vPe4SD8HuiknqG_UY0SoxPbdr4SjX4tdHhVXc3x6kg-1667200355-0-gaNycGzNCP0
- https://www.google.com/url?sa=t&source=web&rct=j&url=https://topcryptoz.net/&ved=2ahUKEwjvzuXY88L2AhU_SGwGHRY1CN0QFnoECAUQAQ&usg=AOvVaw1mkmdZIswS1EJU34D97ca5

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Cuplikan web_31-10-2022_141040_shinchu net](https://user-images.githubusercontent.com/45124799/198953067-a75dd375-e234-4c1d-8d8a-e7c7c96f6e89.jpeg)
![Cuplikan web_21-10-2022_175935_uniqueten net](https://user-images.githubusercontent.com/45124799/198953070-ba73277b-4959-4b6d-8f37-b04f80af2fcf.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92458
  cosmetic: 43250
  scriptlet: 16603
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 28-0, never
    IDN-0: 9184-0, 14h.37m
    easylist: 62400-54, 2d.18h.56m
    easyprivacy: 30831-1172, 14h.38m
    plowe-0: 3671-865, 7d.22h.52m
    ublock-abuse: 76-0, 9d.16h.19m
    ublock-badware: 3953-105, 14h.36m
    ublock-filters: 31148-156, 14h.35m
    ublock-privacy: 257-1, 9d.16h.18m
    ublock-quick-fixes: 433-20, 14h.33m
    ublock-unbreak: 1875-44, 14h.34m
    urlhaus-1: 11029-0, 14h.32m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 26 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 544 ms (selfie)
  maxAssetCacheWait: 360 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    googletagmanager.com: 1
    netpub.media: 7
    thisiswaldo.com: 1
```
</details>

**Comment by okiehsch** [comment]
We need valid shortener links to test.

**Comment by yohanes4dip** [comment]
I don't know a valid link, only that link is in my browser history, every time I click on a link I get forwarded to that link.

**Comment by yohanes4dip** [comment]
Try this link
https://topcryptoz.net/backup/w/?get=n8bUc&__cf_chl_tk=2vPe4SD8HuiknqG_UY0SoxPbdr4SjX4tdHhVXc3x6kg-1667200355-0-gaNycGzNCP0

**Comment by okiehsch** [comment]
I get redirected to
`https://www.youtube.com/watch?v=dQw4w9WgXcQ`

**Comment by stephenhawk8054** [comment]
This thread has example links: https://github.com/uBlockOrigin/uAssets/issues/14929

But no `topcryptoz.net` yet

**Comment by okiehsch** [comment]
> I think we can continue in the old thread, since all these sites are the same.

Sure let's reopen the old one and close this issue.
@okiehsch let's continue it in https://github.com/uBlockOrigin/uAssets/issues/14929
