### ISSUE TITLE
iptvxtreamcodes.com [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#15486]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://iptvxtreamcodes.com/Free/03/11/2022/privacy-policy/privacy-policy-2/`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![iptvxtremecodes](https://user-images.githubusercontent.com/29841633/199145266-d5a4ad04-2241-4332-b6f6-bd047968e387.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106.0.3

### Settings

Default Settings

### Notes

None

**Comment by stephenhawk8054** [comment]
Is it a redirection from another link?

**Comment by Robbie8592** [comment]
Try https://iptvxtreamcodes.com/

**Comment by stephenhawk8054** [comment]
I can't see any anti-adblock

![image](https://user-images.githubusercontent.com/66517106/199164309-4ba93219-1d25-4249-8128-8a01622eb7b1.png)

Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by gorhill** [comment]
The only way I could reproduce is when adding another blocker (ABP). But @Robbie8592 said:

> - [x] uBO is the only extension
> - [x] uBO with default lists/settings

**Comment by gorhill** [comment]
- [x] uBO is the only extension
- [x] uBO with default lists/settings

The only way I could reproduce is after adding another blocker (ABP).
