### ISSUE TITLE
w.acortaz.eu: popups

### ISSUE THREAD

**Issue by pastormorris** [uBlockOrigin/uAssets#15493]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://w.acortaz.eu/`

`https://w.acortaz.eu/#WVVoU01HTklUVFpNZVRsM1dWaE9NRnBZVFhWYVIxWjZXVEpHZVZveVJqQmFXRUpzWWtkc2VreHRUblppVXpndlpHb3hUbE5XVFQwPQ==`

### Category

popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 90302
  cosmetic: 43507
  scriptlet: 17995
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 23-2, never
    easylist: 62622-54, 9h.29m
    easyprivacy: 30831-1170, 9h.28m
    plowe-0: 3671-865, 7d.15h.10m
    spa-0: 3377-11, 19h.55m
    spa-1: 4816-179, 3d.17h.5m
    ublock-abuse: 76-0, 2d.22h.11m
    ublock-badware: 4352-110, 3d.17h.4m
    ublock-filters: 32282-173, 3d.17h.3m
    ublock-privacy: 260-1, 2d.22h.10m
    ublock-quick-fixes: 439-20, 19h.54m
    ublock-unbreak: 1873-44, 3d.17h.2m
    urlhaus-1: 9971-0, 19h.53m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 14 redacted]
hostRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 765 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide all the steps to reproduce the issue (how did you land on acortaz page ? when do you get the popup ? clicking what ?)
