### ISSUE TITLE
heute.at: breakage (images do not load)

### ISSUE THREAD

**Issue by Esokrates** [uBlockOrigin/uAssets#15498]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

heute.at

### Describe the issue

All the articles on the page load fine. Most articles have an image gallery at the bottom of the article. The first image is there, however when clicking the right arrow to view other images only black space can be seen. When deactivating ublock origin, the other images display just fine.

Example url: `https://www.heute.at/s/wienerin-verzweifelt-4300-statt-720-euro-fuer-strom-100236142`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/17780185/199272153-41b8470b-1653-4d62-bf41-40259c9b455c.png)
![image](https://user-images.githubusercontent.com/17780185/199272200-4a00bc01-f68a-4de5-8cce-d4983bad70c2.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106

### Settings

No settings changes, fresh browser profile.

**Comment by okiehsch** [comment]
@ryanbr 
`@@||php.heute.at/onion/ProjectOnion/render/common/js/tracking.js$script,1p`
