### ISSUE TITLE
[NSFW] Video Playback Stopped By AD

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#1549]
**### URL(s) where the issue occurs**

`https://xfreehd.com`

**### Describe the issue**

An "Advertisement" tiny square box appears for all the videos before actually playing them. It is centered, on top of the "play" button, and has a tiny "x" button, which has to be clicked each time so the videos get shown. otherwise, they will be start loading, but only a black screen will be showed up.

### Screenshot(s)

[Will post them if needed]

### Versions

Browser/version: [Firefox v52.6.0 ESR x86]
uBlock Origin version: [1.15.6]

### Settings

No changes but updating the default filters' list.

### Notes

I already tried by hiding the aforementioned ad box with the element picker, but although it hides them, the issue about the black screen will still occur.

Thanks.

**Comment by mapx-** [comment]
add
`xfreehd.com##.nvheader > span:has-text(Advertisement)`

you'll see only a little square you can click to play the video

**Comment by elsy04** [comment]
As you said, the round white button with the "Play" logo will not be shown anymore, but a little white square button instead; but the that "advertisement" crap is gone as well, so it is fine.

Thanks for your time. 👍

**Comment by garry-ut99** [comment]
A big ad placeholder, caused by `ghide` from "uBlock Filters" & "EasyList": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219873164-49905b4f-7374-4c64-81c9-02ec0ed8b17a.png)
on both main page and subpages, I still get AA with `ghide` off.
