### ISSUE TITLE
cointalk.com: ad leftovers

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15494]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.cointalk.com/threads/happy-halloween.400650/`

### Describe the issue

Ad leftovers: "Log in or Sign up to hide this ad." Shows up after the first post in a thread.

### Screenshot(s)

![Screen Shot 2022-11-01 at 7 31 36 AM](https://user-images.githubusercontent.com/54487525/199257933-829cffc3-4e41-4e18-bdf4-878285c3b163.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 88452
  cosmetic: 38405
  scriptlet: 16605
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31859-52, now
    ublock-badware: 3957-0, now
    ublock-privacy: 288-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1898-0, now
    ublock-quick-fixes: 458-0, now
    easylist: 62737-629, now
    easyprivacy: 30835-1707, now
    urlhaus-1: 11029-0, now
    plowe-0: 3669-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1665 ms
  maxAssetCacheWait: 163 ms
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`cointalk.com##li.message:has-text(hide this ad)`
