### ISSUE TITLE
contentos.one: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15497]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://contentos.one/`

### Category

detection

### Describe the issue

Detect after login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 108
filterset (summary): 
  network: 89785
  cosmetic: 27693
  scriptlet: 16647
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 31966-277, 1d.22h.40m
    ublock-badware: 3956-0, 1d.22h.40m
    ublock-privacy: 288-1, 1d.22h.40m
    ublock-abuse: 76-0, 1d.22h.40m
    ublock-unbreak: 1893-0, 1d.22h.40m
    ublock-quick-fixes: 445-0, 21h.13m
    adguard-mobile: 8205-166, 1d.22h.40m
    easylist: 62591-17717, 1d.22h.40m
    easyprivacy: 30831-1717, 1d.22h.40m
    urlhaus-1: 11029-0, 21h.12m
    plowe-0: 3669-3, 1d.22h.40m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1032 ms (selfie)
  maxAssetCacheWait: 482 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    coinad.org: 3
    trikerboughs.com: 1
    wpadmngr.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Added a generic fix for these sites now

**Comment by hunterkais** [comment]
Nice, thanks
