### ISSUE TITLE
diep.io detects ublock origin

### ISSUE THREAD

**Issue by urreport** [uBlockOrigin/uAssets#155]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`diep.io`

### Describe the issue

Adblock is detected.

### Screenshot(s)

https://s16.postimg.org/a82xbi6rp/image.png

### Versions

Chrome Version 53.0.2785.116 m (64-bit)
uBlock origin 1.9.10

### Settings

Using default filter lists, enabled advanced user mode.

### Notes

If it detects adblock, it sets a localstorage key "hadAdblocker" with value "1".

**Comment by IDKwhattoputhere** [comment]
On my side: That small message only pops up for about 5 seconds and then disappears on it's own. Very unobtrusive and in my opinion not worth allowing any dodgy scripts or putting work into more complicated solutions.

**Comment by urreport** [comment]
The message is unobtrusive as of now, but I would prefer ublock origin to be invisible to any sites if possible. Will this be fixed on ublock origin's side?

**Comment by IDKwhattoputhere** [comment]
> invisible to any sites if possible

It still is. The detection is only client side as far as I can see so no one gets to know you're using an adblocker.
> Can this be fixed on ublock origin's side?

It can be fixed but I don't think being tracked by Google through allowing their scripts is preferable to your adblocker being detected locally. Any other solution would require some work which seems like wasted time for the reasons mentioned.

**Comment by gorhill** [comment]
It's not an ad, it's a small, temporary notice -- at most it's a case for Fanboy Annoyance.

**Comment by StarProgamGamer** [comment]
Well it was closing the game for me after a while because it detected my adblocker and i didn't turn it off
