### ISSUE TITLE
mlm.pearson.com: breakage

### ISSUE THREAD

**Issue by arrie78** [uBlockOrigin/uAssets#15502]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mlm.pearson.com/northamerica/`

### Category

breakage

### Describe the issue

clicking the "sign in" button doesn't work; I have to manually enter the hyperlink

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 85885
  cosmetic: 38549
  scriptlet: 16592
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62003-53, 7d.13h.6m
    easyprivacy: 30831-1170, 14h.57m
    plowe-0: 3669-864, 1d.15h.16m
    ublock-abuse: 76-0, 1d.15h.15m
    ublock-badware: 4352-104, 3d.14h.14m
    ublock-filters: 31112-108, 3d.14h.13m
    ublock-privacy: 260-1, 1d.15h.14m
    ublock-quick-fixes: 453-20, 14h.56m
    ublock-unbreak: 1873-42, 3d.14h.12m
    urlhaus-1: 8916-0, 14h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7800 ms (selfie)
  maxAssetCacheWait: 2597 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    pearson.com: 2
    adobedtm.com: 1
    go-mpulse.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||pearson.com/osbrowserchecker/prd/thirdPartyCookie.html$frame,1p`
