### ISSUE TITLE
port.hu: breakage

### ISSUE THREAD

**Issue by prokrusztesz** [uBlockOrigin/uAssets#15504]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://port.hu/`

### Category

breakage

### Describe the issue

Links and menus do not work in this side, as well as neither cookie nor adult content warnings (javascripts?) when uBO is on. Everything works well if uBO switched off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 87373
  cosmetic: 40126
  scriptlet: 16631
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    HUN-0: 2178-0, 22h.55m
    easylist: 62334-53, 6d.2h.30m
    easyprivacy: 30809-1181, 6d.2h.29m
    plowe-0: 3669-868, 2h.54m
    ublock-abuse: 76-0, 2h.53m
    ublock-badware: 3953-105, 23h
    ublock-filters: 31104-132, 22h.59m
    ublock-privacy: 260-1, 2h.52m
    ublock-quick-fixes: 453-20, 22h.57m
    ublock-unbreak: 1882-42, 22h.58m
    urlhaus-1: 9971-0, 22h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 621 ms (selfie)
  maxAssetCacheWait: 312 ms
popupPanel: 
  blocked: 51
  blockedDetails: 
    port.hu: 1
    adocean.pl: 2
    doubleclick.net: 11
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    indapass.hu: 1
    onesignal.com: 1
    quantcast.com: 1
    quantserve.com: 1
    wtg-ads.com: 1
    youtube.com: 29
```
</details>

**Comment by okiehsch** [comment]
Caused by 
````
hu#@##qc-cmp2-container
hu#@#.qc-cmp2-container
````
in the regional list.

**Comment by okiehsch** [comment]
@prokrusztesz update the `uBO-unbreak` list, the site should work fine after that.

**Comment by prokrusztesz** [comment]
THX!

**Comment by krystian3w** [comment]
@scripthunter7 fyi.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15504

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/13729

**Comment by scripthunter7** [comment]
> Caused by
> 
> ```
> hu###qc-cmp2-container
> hu##.qc-cmp2-container
> ```
> 
> in the regional list.

Yes, I temporarily disabled these to prevent further issues:

https://github.com/hufilter/hufilter-dev/commit/f568dbeb099de9a2858b95c6d952642da169fef7
