### ISSUE TITLE
financerites.com: ads

### ISSUE THREAD

**Issue by gQx1** [uBlockOrigin/uAssets#15506]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://financerites.com/what-is-the-metaverse-here-are-some-points-about-the-metaverse-you-need-to-know/`

### Category

ads

### Describe the issue

ads page, clickbait, misleading context etc.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89958
  cosmetic: 46914
  scriptlet: 17666
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11235-10, 1d.21h.49m
    easylist: 62622-73, 2d.1h.50m
    easyprivacy: 30832-1175, 1d.2h.17m
    plowe-0: 3671-866, 9d.2h.31m
    ublock-abuse: 76-0, 10d.34m
    ublock-badware: 3953-105, 1d.21h.48m
    ublock-filters: 31124-139, 1d.21h.47m
    ublock-privacy: 257-1, 10d.17m
    ublock-quick-fixes: 452-20, 14h.47m
    ublock-unbreak: 1875-42, 1d.21h.46m
    urlhaus-1: 11029-0, 14h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 219 ms (selfie)
  maxAssetCacheWait: 115 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    hooliganmedia.com: 1
```
</details>

**Comment by mapx-** [comment]
> ads page, clickbait, misleading context etc.

provide more info
