### ISSUE TITLE
drakescans.com: detection

### ISSUE THREAD

**Issue by Caileor** [uBlockOrigin/uAssets#15508]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://drakescans.com/`

### Category

detection

### Describe the issue

Popup box detects uBO, but can be closed to access website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-02 at 04-43-49 Drake Scans](https://user-images.githubusercontent.com/117278143/199481591-761d5ec7-f0c1-48fe-9142-b04c4fe9a45a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 86156
  cosmetic: 38408
  scriptlet: 16596
  html: 793
listset (total-discarded, last updated): 
  default: 
    user-filters: 64-2, never
    ublock-filters: 31863-153, 2d.8h.4m
    ublock-badware: 3957-0, 2d.8h.3m
    ublock-privacy: 288-0, 3d.8h.9m
    ublock-abuse: 76-0, 3d.8h.8m
    ublock-unbreak: 1888-0, 2d.8h.2m
    easylist: 62491-525, 1d.15h.58m
    easyprivacy: 30832-1707, 1d.15h.57m
    plowe-0: 3669-3, 3d.4h.5m
    urlhaus-1: 8916-0, 5h.50m
    ublock-quick-fixes: 458-0, 5h.51m
filterset (user): [array of 64 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1012 ms (selfie)
  maxAssetCacheWait: 557 ms
popupPanel: 
  blocked: 61
  blockedDetails: 
    360yield.com: 7
    3lift.com: 1
    4dex.io: 3
    a-mo.net: 3
    adform.net: 2
    adkernel.com: 1
    adtelligent.com: 3
    aniview.com: 3
    bidswitch.net: 2
    creativecdn.com: 2
    criteo.com: 1
    criteo.net: 2
    doubleclick.net: 4
    google.com: 1
    googleadservices.com: 1
    googlesyndication.com: 1
    gstatic.com: 2
    media.net: 1
    minutemedia-prebid.com: 1
    mobfox.com: 1
    quantumdex.io: 1
    servenobid.com: 1
    unibots.in: 1
    unrulymedia.com: 2
    yahoo.com: 10
    youtube.com: 3
    zemanta.com: 1
```
</details>

**Comment by MonfGeiger** [comment]
reopening issue ticket, drake scans went offline for a while to do something to their website (maintenance?), came back online, one thing changed was their adblock detection thingy working again, outcome ends up the same as this ticket
![C1](https://github.com/uBlockOrigin/uAssets/assets/28603306/f8bd06b1-dde5-43ee-b528-f323c88d1765)
as for settings changed, ill just post the backup of my ublock origin settings, some of the My Filters settings inside do lead to 
NSFW hosters, so ignore those pls
[my-ublock-backup_2023-06-03_09.27.33.txt](https://github.com/uBlockOrigin/uAssets/files/11643094/my-ublock-backup_2023-06-03_09.27.33.txt)

**Comment by MonfGeiger** [comment]
just updated my ublock origin extension, purged my filter list cache, updated them again, opened drake scans, the adblock warning just stopped showing, thanks :)
