### ISSUE TITLE
chronicle.com: nuisance

### ISSUE THREAD

**Issue by PeterBeckley** [uBlockOrigin/uAssets#15518]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chronicle.com/article/a-controversial-college-takes-shape`

### Category

nuisance

### Describe the issue

The website hides paragraphs 2-n of each article behind a "fog" with text that blames a VPN and/or adblocker. The following filters fix the issue which was kind of addressed with #14883 I guess.

```
chronicle.com##.ArticleFullBleedLeadPage-summary
chronicle.com##[data-content-body]:style(height:initial!important;visibility:initial!important;overflow:initial!important;opacity:initial!important)
chronicle.com##[hidden]:style(display:initial!important)
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 321977
  cosmetic: 212119
  scriptlet: 38033
  html: 814
listset (total-discarded, last updated): 
  added: 
    https://github.com/llacb47/miscfilters/raw/master/antipaywall.txt: 1876-0, 39m
    https://raw.githubusercontent.com/ethan-xd/ethan-xd.github.io/master/fb.txt: 138-0, 39m
    adguard-generic: 79285-5166, 39m
    adguard-spyware: 36581-15862, 39m
    adguard-spyware-url: 794-4, 39m
    block-lan: 44-0, 39m
    curben-phishing: 170777-10, 39m
    curben-pup: 193-0, 39m
    adguard-annoyance: 60472-5215, 39m
    adguard-social: 18812-1075, 39m
    fanboy-thirdparty_social: 68-0, 39m
    fanboy-annoyance: 82217-66177, 39m
    fanboy-cookiemonster: 42531-129, 39m
    fanboy-social: 23419-30, 39m
    ublock-annoyances: 4754-5, 39m
  default: 
    user-filters: 3-0, never
    ublock-filters: 31884-75, 39m
    ublock-badware: 3957-0, 39m
    ublock-privacy: 288-1, 39m
    ublock-abuse: 76-0, 39m
    ublock-unbreak: 1903-0, 39m
    ublock-quick-fixes: 470-0, 39m
    easylist: 62740-688, 39m
    easyprivacy: 30841-1718, 39m
    urlhaus-1: 11522-0, 39m
    plowe-0: 3669-4, 39m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    moz-extension-scheme
hostRuleset: 
  added: [array of 383 redacted]
urlRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 639 ms (selfie)
  maxAssetCacheWait: 848 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    chronicle.com: 3
    adobedtm.com: 2
    brightspotcdn.com: 4
    cloudflare.net: 1
    google-analytics.com: 1
    googletagservices.com: 1
    moatads.com: 1
    parsely.com: 1
```
</details>

**Comment by PeterBeckley** [comment]
If anyone cares, the "fix" targeting c950.chronicle.com/script.js doesn't do crap to address the issue. Unclear what QA verification was accomplished. Perhaps I've misunderstood Git/dynamic rules/static rules entirely, and I shouldn't have submitted the issue.

Anyone reading this can copy/paste the filters I wrote above into their "my filters" section and have it work.

**Comment by stephenhawk8054** [comment]
At first, I thought it is about the paywall (like in newspaper and magazines) and since we do not address bypassing paywall, I added that filter to just bring up the signing up modal. But now after reading it again, as it just requires (unnecessary) free account, your filters can be added to annoyances list.

**Comment by PeterBeckley** [comment]
> At first, I thought it is about the paywall (like in newspaper and magazines) and since we do not address bypassing paywall, I added that filter to just bring up the signing up modal. But now after reading it again, as it just requires (unnecessary) free account, your filters can be added to annoyances list.

and all of that confusion is probably my fault being so new to the whole Git thing. I'll work on being more clear in the future.
