### ISSUE TITLE
digitaltrends.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15519]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.digitaltrends.com/computing/how-to-convert-apple-pages-to-pdf/`

### Category

ads

### Describe the issue

https://user-images.githubusercontent.com/19517680/199641377-a43b28e6-017c-4c75-84ee-a35ac62482dc.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/19517680/199641389-672e4621-cc30-49bb-a12c-35901bfd0b38.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 109
filterset (summary): 
  network: 108070
  cosmetic: 165901
  scriptlet: 25720
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 8142-3, 3d.19h.57m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 3d.19h.55m
    adguard-annoyance: 60324-395, 3d.20h.1m
    adguard-spyware: 35870-2839, 3d.19h.59m
    fanboy-annoyance: 81952-3798, 3d.3h.19m
    fanboy-cookiemonster: 42281-42281, 3d.3h.17m
    ublock-annoyances: 4718-211, 3d.19h.51m
  default: 
    user-filters: 14-0, never
    easylist: 62400-149, 4d.19h.55m
    easyprivacy: 30822-14036, 4d.19h.53m
    ublock-abuse: 76-0, 3d.19h.53m
    ublock-badware: 3953-103, 3d.19h.49m
    ublock-filters: 31146-618, 3d.19h.47m
    ublock-privacy: 260-47, 3d.19h.45m
    ublock-quick-fixes: 452-20, 3h.17m
    ublock-unbreak: 1875-61, 3d.19h.43m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 20 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 4 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 2647 ms (selfie)
  maxAssetCacheWait: 1196 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    digitaltrends.com: 3
    ad.gt: 1
    adapex.io: 1
    adlightning.com: 1
    adsafeprotected.com: 1
    btloader.com: 1
    doubleclick.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    wp.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I cannot reproduce the issue

```yaml
default: 
    user-filters: 14-0, never
```

Can you copy your custom filters to here?

**Comment by 3xploiton3** [comment]
```
* billing.exabytes.co.id * noop
* intercom.io * noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
billing.exabytes.co.id billing.exabytes.co.id * noop
www.niagahoster.co.id intercom.io * noop
```

**Comment by 3xploiton3** [comment]
```
! 2022-01-23 https://www.jagoanssh.com
www.jagoanssh.com##.clearfix
www.jagoanssh.com##.probootstrap-feature-first.probootstrap-section
www.jagoanssh.com##.container > section.probootstrap-section > .container > .row
www.jagoanssh.com##.container > section.probootstrap-section

! 2022-01-23 https://intercelestial.com
intercelestial.com##center:nth-of-type(2)
intercelestial.com##.col-md-8.content-area
intercelestial.com##.col-md-4.widget-area
intercelestial.com###content > center > .soractrl > .klnsora

! 2022-01-24 https://safe.intipanime.com
safe.intipanime.com##.mh-clearfix.mh-wrapper

! 2022-03-08 https://www.tokopedia.com
www.tokopedia.com###pdp_comp-QRCode
www.tokopedia.com###pdp_comp-offerings

tiktok.com##.backdrop-1 .guide-container

! 2022-04-06 https://forex-gold.net
forex-gold.net##.content-column.col-sm-8
forex-gold.net##.sidebar-column-primary.sidebar-column.col-sm-4
```

**Comment by stephenhawk8054** [comment]
Sorry I cannot reproduce the issue. You might wait for others to help you investigate the issue.

**Comment by dportvine** [comment]
> Add In My Filters -
> 
> ```
> www.digitaltrends.com##.is-active.b-adhesion
> www.digitaltrends.com##div.dtads-desktop.dtads-tablet.dtads-mobile.dtads-mobile-hub.dtads-location
> ```

Why?

<details>
<summary>Screen</summary>

![2022-11-03_083941](https://user-images.githubusercontent.com/111344219/199660862-81799a8c-9b8c-4dab-872c-6b64a2fceb66.png)
![2022-11-03_083956](https://user-images.githubusercontent.com/111344219/199660869-3455a790-c76a-4e48-b7a7-1ed9f7de6f04.png)
![2022-11-03_084009](https://user-images.githubusercontent.com/111344219/199660878-17de524b-bafb-4612-abff-dfb69748fcac.png)
</details>

**Comment by mapx-** [comment]
> Chromium: 109

@3xploiton3 are you using canary chrome ?

**Comment by 3xploiton3** [comment]
> > Chromium: 109
> 
> @3xploiton3 are you using canary chrome ?

Chrome dev latest version

**Comment by stephenhawk8054** [comment]
> There Is Black Advertisment Div In FireFox Android For Me...And Adding Those Filters Works @dportvine

It's because on mobile `Ignore generic cosmetic filters` is turned on. Disable it and test again

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters

**Comment by mapx-** [comment]
@3xploiton3 

You should backup your current setup then reset uBO to default without adding / removing lists and test again
