### ISSUE TITLE
[nsfw] login.i-ready.com: [unknown]

### ISSUE THREAD

**Issue by Bcr8da83** [uBlockOrigin/uAssets#15514]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://login.i-ready.com/student/dashboard/home`

### Category

[unknown] BAD

### Describe the issue

BAD

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 86302
  cosmetic: 38400
  scriptlet: 16618
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62662-55, 2d.21m
    easyprivacy: 30832-1170, 2d.20m
    plowe-0: 3671-865, 9d.3h.54m
    ublock-abuse: 76-0, 2d.23m
    ublock-badware: 3953-105, 2h.10m
    ublock-filters: 31143-130, 2h.9m
    ublock-privacy: 260-1, 2d.22m
    ublock-quick-fixes: 463-20, 2h.7m
    ublock-unbreak: 1890-42, 2h.8m
    urlhaus-1: 8916-0, 2h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 954 ms (selfie)
  maxAssetCacheWait: 381 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    trackjs.com: 1
```
</details>

**Comment by mapx-** [comment]
What's BAD ?

**Comment by Jaycen234** [comment]
I think this person is in like, first grade. I chacked out the site and it said K-1 Login so i think this person did this on accident. I will check the site out more but that is my theory for now.
