### ISSUE TITLE
proprofs.com: ads

### ISSUE THREAD

**Issue by Cheespeasa1234** [uBlockOrigin/uAssets#15517]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.proprofs.com/quiz-school/quizshow.php?title=right-way_1&q=8`

### Category

ads

### Describe the issue

Every so often, while filling out quiz, a pop up window (not a separate window, just a box that goes in front and turns everything transparent) suggests other quizzes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 86131
  cosmetic: 38347
  scriptlet: 16601
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31851-52, 1d.15h.11m
    ublock-badware: 3957-0, 1d.15h.10m
    ublock-privacy: 282-0, 13d.25m
    ublock-abuse: 76-0, 13d.24m
    ublock-unbreak: 1888-0, 1d.15h.9m
    ublock-quick-fixes: 458-0, 4h.26m
    easylist: 62491-627, 3d.3h.52m
    easyprivacy: 30823-1707, 3d.3h.51m
    urlhaus-1: 8916-0, 4h.27m
    plowe-0: 3675-3, 13d.22m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 543 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    3lift.com: 2
    connatix.com: 1
    google.com: 5
    googletagmanager.com: 1
    googletagservices.com: 1
    pubmatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
proprofs.com###exit_popup_custom
proprofs.com###over-overlay
```

or 

```adb
proprofs.com##+js(aeld, DOMContentLoaded, exit_popup)
```

@ryanbr For FA
