### ISSUE TITLE
fanseries.online: breakage

### ISSUE THREAD

**Issue by iplotin** [uBlockOrigin/uAssets#15510]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://fanseries.online/57372-andor/1-season/9-episode.html`

### Category

breakage

### Describe the issue

`http://fanseries.online/57372-andor/1-season/9-episode.html`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 104
filterset (summary): 
  network: 105487
  cosmetic: 59794
  scriptlet: 17823
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39919-10, 1d.6h.32m
    easylist: 62548-66, 3d.6h.34m
    easyprivacy: 30832-1286, 3d.6h.34m
    plowe-0: 3669-869, 3d.6h.34m
    ublock-abuse: 76-1, 3d.6h.34m
    ublock-badware: 3953-105, 3d.6h.34m
    ublock-filters: 31146-161, 3d.6h.34m
    ublock-privacy: 260-1, 3d.6h.34m
    ublock-quick-fixes: 452-20, 6h.29m
    ublock-unbreak: 1875-42, 3d.6h.34m
    urlhaus-1: 11107-0, 6h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 23 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 829 ms (selfie)
  maxAssetCacheWait: 353 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    adpone.com: 15
    aj1907.online: 1
    aj2396.online: 4
    doubleclick.net: 1
    gamaads.com: 2
    googletagmanager.com: 1
    jsdelivr.net: 2
    moviead55.ru: 4
    rocketme.top: 2
    vak345.com: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
What's broken ? pèrovide details / steps to reproduce.

The video is playing fine on my end.
