### ISSUE TITLE
affairscloud-com.cdn.ampproject.org: ads

### ISSUE THREAD

**Issue by Beinginhuman** [uBlockOrigin/uAssets#15525]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://affairscloud-com.cdn.ampproject.org/v/s/affairscloud.com/rbi-launches-pilot-project-of-digital-rupee-in-wholesale-segment/?amp=&amp_gsa=1&amp_js_v=a9&usqp=mq331AQIKAGwASCAAgM%3D`

### Category

ads

### Describe the issue

All ads not blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 89782
  cosmetic: 27552
  scriptlet: 17570
  html: 780
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 33060-257, 2d.2h.44m
    ublock-badware: 3956-0, 3d.18h.51m
    ublock-privacy: 288-1, 4d.14h.48m
    ublock-abuse: 76-0, 7d.22h.12m
    ublock-unbreak: 1893-0, 3d.18h.52m
    adguard-mobile: 8205-167, 3d.18h.50m
    easylist: 62692-17726, 2d.2h.45m
    easyprivacy: 30834-1717, 1d.18h.22m
    urlhaus-1: 11029-0, 1d.18h.21m
    plowe-0: 3675-3, 2d.21h.6m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1879 ms (selfie)
  maxAssetCacheWait: 1676 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    ampproject.org: 1
```
</details>

**Comment by mapx-** [comment]
Are you meaning `AffairsCloud app` self-promo ?
