### ISSUE TITLE
learncpp.com: breakage

### ISSUE THREAD

**Issue by JohnnySammour** [uBlockOrigin/uAssets#15526]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.learncpp.com/cpp-tutorial/order-of-construction-of-derived-classes/`

### Category

breakage

### Describe the issue

when uBO is enabled for the site, images do not load and their space is removed (no space for the pictures)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 129483
  cosmetic: 58307
  scriptlet: 16808
  html: 0
listset (total-discarded, last updated): 
  added: 
    CHN-0: 29067-87, 3d.4h.15m
    FRA-0: 30699-46, 3d.4h.18m
    ara-0: 2598-3, 1d.9m
    block-lan: 44-0, 19d.17h.3m
  default: 
    user-filters: 0-0, never
    easylist: 62636-129, 2d.15h.16m
    easyprivacy: 30832-1500, 3d.15h.6m
    plowe-0: 3669-874, 4d.16h.26m
    ublock-abuse: 76-1, 6d.16h.10m
    ublock-badware: 3953-116, 3d.4h.16m
    ublock-filters: 31143-251, 16h.14m
    ublock-privacy: 260-1, 6d.16h.8m
    ublock-quick-fixes: 452-20, 1d.8m
    ublock-unbreak: 1890-43, 16h.13m
    urlhaus-1: 11107-0, 1d.7m
filterset (user): [empty]
trustedset: 
  added: [array of 26 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 686 ms (selfie)
  maxAssetCacheWait: 456 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    learncpp.com: 2
    doubleclick.net: 1
    ezodn.com: 1
    ezojs.com: 1
```
</details>

**Comment by dportvine** [comment]
Is it really that hard to attach a screenshot?
Are you talking about advertising?

**Comment by JohnnySammour** [comment]
as of today i do not have the issue despite having not changed the settings.
the diagrams are now showing when uOB is enabled so i think the issue is resolved.

**Comment by ohusq** [comment]
I do have an issue, I get an empty ad banner on the bottom of the site.
