### ISSUE TITLE
720pizle4.com: ads

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#15521]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://720pizle4.com/izle/dublaj/american-psycho.html`

### Category

ads

### Describe the issue

Ad already blocked by AdGuard extension, but this ad is not blocked when uBO is enabled.

### Screenshot(s)

`https://720pizle4.com/izle/altyazi/american-psycho.html
`
<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/199653179-7e45bf14-9bfd-4bed-9158-76690ea300cf.png)

</details>

---

`https://www.roketdizi.pw/dizi/the-vampire-diaries-turkce-dublaj/sezon-1/bolum-1`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/199653679-c764050f-9041-4fb6-b1ab-7b833cacf216.png)

</details>

---

`https://dizimia3.com/dizi/into-the-night/sezon-1/bolum-3
`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/199653857-7f8d1fc8-4b2c-41ee-a3b7-36fdedac032b.png)

</details>

---

`https://sinefy.io/izle/im-westen-nichts-neues`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/199653975-f7d35824-00d7-427f-942f-162194d2d1a3.png)

</details>

---

`https://dizilla4.com/rick-and-morty-1-sezon-2-bolum/`

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/199660836-46398830-df43-4b51-94c0-a8566b1f980e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 131849
  cosmetic: 149547
  scriptlet: 33517
  html: 794
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 79285-5129, 1m
    adguard-spyware: 36581-15791, now
    adguard-spyware-url: 794-3, now
    adguard-annoyance: 60472-1531, now
    adguard-social: 18812-27, now
  default: 
    user-filters: 67-0, never
    ublock-filters: 31885-72, 1m
    ublock-badware: 3957-0, 1m
    ublock-privacy: 288-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1904-1, 1m
    ublock-quick-fixes: 470-0, 1m
    easylist: 63250-350, 1m
    easyprivacy: 30848-1188, now
    TUR-0: 11250-10, now
filterset (user): [array of 71 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4344 ms
  maxAssetCacheWait: 1843 ms
  unsuspendAfter: 1771 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adform.net: 2
    aj2373.online: 2
    diken.xyz: 2
    googletagmanager.com: 1
    storj.cloud: 1
    twitter.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It says `This video is unvailable` for me

![image](https://user-images.githubusercontent.com/66517106/199657204-32ed6495-0027-43c0-8a4c-3782dc1780fc.png)

Which server did you choose?

**Comment by mapx-** [comment]
needing

`contentx.me##.playerinads`

**Comment by stephenhawk8054** [comment]
I don't see any `##.playerinads` filters in Turkish filter list yet

https://filters.adtidy.org/extension/ublock/filters/13.txt

**Comment by Yuki2718** [comment]
Hmm, strange `contentx.me##.playerinads` is certainly in the Turkish filter but not in the uBO version.
@slavaleleka Can you please check?

**Comment by Yuki2718** [comment]
Added to our list until solved by AG.
