### ISSUE TITLE
freemagazines.top: ads

### ISSUE THREAD

**Issue by cthart** [uBlockOrigin/uAssets#15522]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://freemagazines.top/`

### Category

ads

### Describe the issue

Leftover box with red "X Close".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89038
  cosmetic: 38410
  scriptlet: 16613
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 62737-55, 13h.5m
    easyprivacy: 30836-1170, 13h.4m
    plowe-0: 3671-865, 12d.15h.6m
    ublock-abuse: 76-0, 13h.7m
    ublock-badware: 3953-105, 13h.1m
    ublock-filters: 31143-131, 13h
    ublock-privacy: 260-1, 13h.6m
    ublock-quick-fixes: 452-20, 13h.3m
    ublock-unbreak: 1884-42, 12h.59m
    urlhaus-1: 11595-0, 13h.2m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    google-analytics.com: 1
    google.com: 6
    googlesyndication.com: 1
```
</details>

**Comment by playonevideo** [comment]
Ads leftovers on the homepage:

<img width="1353" height="873" alt="Image" src="https://github.com/user-attachments/assets/1efb33d1-274e-4760-ad57-4993601efc59" />

**Comment by gothic-bum** [comment]
Test again after adding to "My filters":  
  
    freemagazines.top##.widget:has(> .adsbygoogle)

**Comment by playonevideo** [comment]
It worked.
