### ISSUE TITLE
turbobit.net: ads

### ISSUE THREAD

**Issue by cthart** [uBlockOrigin/uAssets#15523]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://turbobit.net/kt61uodx9z3n.html?short_domain=turb.pw`

### Category

ads

### Describe the issue

Displays a halloween promotion ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89476
  cosmetic: 38436
  scriptlet: 16619
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63250-55, 1m
    easyprivacy: 30848-1170, 1m
    plowe-0: 3669-865, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 3953-105, 1m
    ublock-filters: 31145-132, 1m
    ublock-privacy: 260-1, 1m
    ublock-quick-fixes: 464-20, 1m
    ublock-unbreak: 1891-42, 1m
    urlhaus-1: 11522-0, 1m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    turbobit.net: 2
    googletagmanager.com: 1
    jsdelivr.net: 1
    turbocap.net: 1
    yadro.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It looks like a self-promotion.

@ryanbr What do you think?

**Comment by cthart** [comment]
Are self-promotions not considered ads? I'm pretty sure https://github.com/uBlockOrigin/uAssets/issues/11861 was also a self-promotion.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets#uassets
> The rationale on whether to include a specific filter in one of uBO's filter lists is the same as outlined by [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html), also taking into account whether a filter requires uBO's extended filter syntax.

EasyList policy:
> Self-promotion should not be specifically removed by EasyList, although equally should not be allowed if it is blocked.

I cannot reproduce the popup in the old issue (even when disabling the added filters) so I can't say about it. Anyways, it depends on EasyList's decision.

**Comment by okiehsch** [comment]
> I'm pretty sure https://github.com/uBlockOrigin/uAssets/issues/11861 was also a self-promotion.

> Describe the issue
Popup ad from the bottom of the screen for Hustler magazine,

Does not sound like it.

**Comment by ghajini** [comment]
self promotion

**Comment by dportvine** [comment]
Turbobit mirror.

`https://turbobita.net/download/free/zta5z91dzh94`

<details>
<summary>Screenshot(s)</summary>

![2024-02-05_134526](https://github.com/uBlockOrigin/uAssets/assets/111344219/72d09276-f77b-4be4-8690-3b4611673228)
![2024-02-05_134551](https://github.com/uBlockOrigin/uAssets/assets/111344219/9345ef1f-b58a-43ff-b8f6-a5fba59a7aff)
</details>

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116012
 cosmetic: 45394
 scriptlet: 18876
 html: 2072
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37546-218, 4m Δ
  ublock-badware: 7833-10, 4m Δ
  ublock-privacy: 994-0, 4m Δ
  ublock-unbreak: 2250-0, 4m Δ
  ublock-quick-fixes: 163-0, 4m Δ
  easylist: 80324-545, 4m Δ
  easyprivacy: 43336-884, 4m Δ
  urlhaus-1: 7930-0, 4m
  plowe-0: 3784-1, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 336 ms (selfie)
 maxAssetCacheWait: 156 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  generallyrefinelollipop.com: 3
  jsdelivr.net: 1
  system-notify.app: 1
  yadro.ru: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by dportvine** [comment]
I also see analytics scripts. Can this be fixed? Turbobit has many mirrors.

<details>
<summary>Screenshot(s)</summary>

![2024-02-06_175014](https://github.com/uBlockOrigin/uAssets/assets/111344219/1b3a7ce8-e070-4158-9585-e93bbbe6bad9)
<details>
