### ISSUE TITLE
neads.co

### ISSUE THREAD

**Issue by noagencyio** [uBlockOrigin/uAssets#15528]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://neads.co`

### Describe the issue

Hi, 

My domain (neads.co) is banned by "AdGuard Français".
How can i fixed that ?

Thank you guys !

### uBlock Origin version

1.44.4

### Browser name and version

Chome 

### Settings

none

**Comment by okiehsch** [comment]
Open an issue at 
https://github.com/AdguardTeam/AdguardFilters

**Comment by mapx-** [comment]
@smed79
