### ISSUE TITLE
[nsfw] sugardaddyseek.com: ads

### ISSUE THREAD

**Issue by wgthor13** [uBlockOrigin/uAssets#15520]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sugardaddyseek.com/baby-influencers-profiles?ad_source=promp_us_uk_ca_au&ad_campaign=promp4`

### Category

ads

### Describe the issue

A pop up came up on my DESKTOP not even in my browser.  I'm running uBlock, AdGuard, Ghostery through a SurfShark VPN.  I've NEVER seen an add come up on my desktop especially one so explicit.  It also wouldn't let me close it without clicking it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 98407
  cosmetic: 177918
  scriptlet: 24113
  html: 813
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 60331-5076, 3d.7h.34m
    adguard-social: 18727-1080, 3d.7h.34m
    fanboy-thirdparty_social: 68-0, 3d.7h.35m
    fanboy-annoyance: 81987-144, 3d.7h.34m
    fanboy-cookiemonster: 42316-42316, 3d.7h.34m
    fanboy-social: 23418-23415, 3d.7h.34m
    ublock-annoyances: 4740-64, 3d.7h.34m
    ublock-quick-fixes: 469-0, 2h.12m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31863-86, 3d.7h.34m
    ublock-badware: 3957-0, 3d.7h.35m
    ublock-privacy: 288-0, 3d.7h.35m
    ublock-abuse: 76-0, 3d.7h.35m
    ublock-unbreak: 1888-3, 3d.7h.35m
    easylist: 62526-662, 3d.7h.34m
    easyprivacy: 30826-1805, 3d.7h.34m
    urlhaus-1: 8916-0, 1d.1h.59m
    plowe-0: 3669-3, 3d.7h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1258 ms (selfie)
  maxAssetCacheWait: 831 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    sugardaddyseek.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> A pop up came up on my DESKTOP not even in my browser.

You should check your OS' softwares. I don't think it's related to uBO.

**Comment by mapx-** [comment]
Scan online your system:

https://www.f-secure.com/en/home/free-tools/online-scanner
