### ISSUE TITLE
lemonde.fr: nuisance

### ISSUE THREAD

**Issue by RomainBelorgey** [uBlockOrigin/uAssets#15538]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lemonde.fr/`

### Category

nuisance

### Describe the issue

There is a new paywall in place and can't really remove it. It can be removed but impossible to scroll down the pages later.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/628135/200027015-2a7498c5-25bd-4f0d-8978-4d218cd38799.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89297
  cosmetic: 38391
  scriptlet: 16624
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 11-1, never
    ublock-filters: 31908-53, 6h.48m
    ublock-badware: 3957-0, 6h.49m
    ublock-privacy: 288-0, 6h.52m
    ublock-abuse: 76-0, 6h.51m
    ublock-unbreak: 1917-0, 6h.47m
    easylist: 62546-628, 3d.20h.27m
    easyprivacy: 30835-1707, 2d.20h.54m
    urlhaus-1: 11977-0, 6h.46m
    plowe-0: 3671-3, 10d.23h.26m
    ublock-quick-fixes: 472-0, 6h.45m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 19 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3959 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    lemonde.fr: 13
    amplitude.com: 1
```
</details>

**Comment by dportvine** [comment]
Add to my filters or enable **EasyList Cookie** in (Annoyances)
```adb
lemonde.fr##.gdpr-lmd-wall
lemonde.fr##body,html:style(height: auto !important; overflow: auto !important)
```

**Comment by mapx-** [comment]
If the wall is hidden / blocked there will be breakages, for example:

`https://www.lemonde.fr/planete/article/2022/10/23/orages-18-departements-places-en-vigilance-orange_6146988_3244.html`

The embed twitter videos are broken

**Comment by dportvine** [comment]
@ryanbr

**Comment by RomainBelorgey** [comment]
Thanks and sorry in a way, did not know about the annoyances filter list :+1: 
It looks to work fine with `EasyList Cookie`
