### ISSUE TITLE
elcomercio.es: detection

### ISSUE THREAD

**Issue by kikejulia** [uBlockOrigin/uAssets#15532]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.elcomercio.es/`

### Category

detection

### Describe the issue

uBlock detected
It would remain undetected if I disable javascript in this site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_20221103_175438](https://user-images.githubusercontent.com/117369831/199785123-56ac36be-99e0-4325-9928-1bca0abb836f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89732
  cosmetic: 38386
  scriptlet: 16593
  html: 790
listset (total-discarded, last updated): 
  removed: 
    spa-0: null
    spa-1: null
  default: 
    user-filters: 828-4, never
    ublock-filters: 31863-53, 3d.19h.14m
    ublock-badware: 3957-0, 3d.19h.12m
    ublock-privacy: 282-0, 12d.2h.15m
    ublock-abuse: 76-0, 12d.2h.14m
    ublock-unbreak: 1888-0, 3d.19h.13m
    easylist: 62622-629, 3d.19h.16m
    easyprivacy: 30832-1708, 3d.19h.15m
    urlhaus-1: 11595-0, 1d
    plowe-0: 3669-16, 2h.59m
    ublock-quick-fixes: 458-0, 1d.1m
filterset (user): [array of 833 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 319 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    adobedtm.com: 8
    amazon-adsystem.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    insurads.com: 1
    newrelic.com: 3
    sascdn.com: 2
    vocstatic.com: 2
```
</details>

**Comment by mapx-** [comment]
> spa-0: null
> spa-1: null

add back the spanish lists
