### ISSUE TITLE
rockmods.net: detection

### ISSUE THREAD

**Issue by WhiteTree97** [uBlockOrigin/uAssets#15535]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rockmods.net/?m=1`

### Category

detection

### Describe the issue

This site detects the adblocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 107
filterset (summary): 
  network: 87660
  cosmetic: 27686
  scriptlet: 16652
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8209-27, 2d.20h.24m
    easylist: 62546-17194, 4d.14h.55m
    easyprivacy: 30834-1182, 2d.14h.21m
    plowe-0: 3671-951, 9d.18h.13m
    ublock-abuse: 76-0, 9d.18h.14m
    ublock-badware: 3952-105, 2d.1h.4m
    ublock-filters: 31242-355, 1d.11h.48m
    ublock-privacy: 257-2, 12d.12h.13m
    ublock-quick-fixes: 452-20, 13h.28m
    ublock-unbreak: 1880-44, 3d.18h.4m
    urlhaus-1: 8916-0, 1d.44m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 727 ms (selfie)
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps outside browser.

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15535#issuecomment-1302797078

**Comment by ghajini** [comment]
@kiwibrowser
fyi
ublock origin experience is not good on kiwi browser
