### ISSUE TITLE
video.sat1.de: detection

### ISSUE THREAD

**Issue by RealPete** [uBlockOrigin/uAssets#15533]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://video.sat1.de/serien/the-taste/videos/jetzt-wird-kombiniert-experience-taste-mit-daniel-gottschlich`

### Category

detection

### Describe the issue

Video isnt played, instead the user is notified about a dected addblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 91116
  cosmetic: 42178
  scriptlet: 16603
  html: 790
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31848-63, 2d.21h.13m
    ublock-badware: 3957-0, 2d.21h.14m
    ublock-privacy: 282-0, 11d.56m
    ublock-abuse: 76-0, 11d.57m
    ublock-unbreak: 1895-0, 2d.21h.12m
    easylist: 62622-633, 3d.21h.35m
    easyprivacy: 30823-1717, 4d.21h.8m
    urlhaus-1: 11602-0, 10m
    plowe-0: 3671-3, 11d.54m
    DEU-0: 6017-2, 9m
    ublock-quick-fixes: 472-0, 8m
filterset (user): [empty]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: -1842 ms (selfie)
  maxAssetCacheWait: 256 ms
popupPanel: 
  blocked: 69
  blockedDetails: 
    71i.de: 6
    adition.com: 1
    agkn.com: 2
    bitmovin.com: 1
    brandmetrics.com: 1
    browser-intake-datadoghq.eu: 15
    clarity.ms: 1
    dwin1.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    iocnt.net: 2
    meetrics.net: 7
    moatads.com: 6
    mookie1.com: 1
    nice264.com: 1
    nmrodam.com: 1
    outbrain.com: 1
    sc-static.net: 1
    sensic.net: 1
    sqrt-5041.de: 4
    taboola.com: 1
    theadex.com: 2
    tiktok.com: 1
    undefined: 1
    userreport.com: 3
    xplosion.de: 2
    yieldlab.net: 1
    zomap.de: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Try

```
@@||ad.71i.de/somtag/loader/loader.js$script,domain=video.sat1.de
||ad.71i.de/somtag/config/v16/sat1_supernova/default.js$script,redirect-rule=noopjs,domain=sat1.de
||player-feedback.p7s1video.net/pf/
```

**Comment by okiehsch** [comment]
Works fine for me, maybe make the last filter blocking scripts only.
