### ISSUE TITLE
flickr.com: ads

### ISSUE THREAD

**Issue by LBergamot** [uBlockOrigin/uAssets#15536]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.flickr.com/search/?text=sprout&safe_search=1&dimension_search_mode=min&height=640&width=640&content_types=0%2C1%2C2`

### Category

ads

### Describe the issue

Flickr pro ads keep appearing even when I use the element picker.
![Screenshot 2022-11-03 185502](https://user-images.githubusercontent.com/111331709/199868385-57b420f9-3081-44dc-b3d1-3bf8b0131727.jpg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 338054
  cosmetic: 217816
  scriptlet: 37254
  html: 817
listset (total-discarded, last updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-1, 3m
    adguard-generic: 79314-5281, 3m
    adguard-mobile: 8219-207, 3m
    adguard-spyware: 36587-16022, 3m
    adguard-annoyance: 60504-4745, 3m
    adguard-social: 18844-1069, 3m
    fanboy-thirdparty_social: 68-0, 3m
    fanboy-annoyance: 82393-66782, 3m
    fanboy-cookiemonster: 42696-149, 3m
    fanboy-social: 23421-28, 3m
    ublock-annoyances: 4786-4, 3m
    dpollock-0: 11390-1635, 3m
    adguard-spyware-url: 794-4, 3m
    block-lan: 44-0, 3m
    curben-phishing: 167138-11, 3m
    curben-pup: 193-0, 3m
  default: 
    user-filters: 92-0, never
    ublock-filters: 31908-90, 3m
    ublock-badware: 3957-0, 3m
    ublock-privacy: 288-0, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1917-0, 3m
    easylist: 63276-1069, 3m
    easyprivacy: 30849-2010, 3m
    urlhaus-1: 11977-0, 3m
    plowe-0: 3669-343, 3m
    ublock-quick-fixes: 472-0, 3m
filterset (user): [array of 92 redacted]
trustedset: 
  added: [array of 141 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 80 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 587 ms (selfie)
  maxAssetCacheWait: 985 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    flickr.com: 1
    siftscience.com: 1
    staticflickr.com: 1
    trustarc.com: 1
```
</details>

**Comment by mapx-** [comment]
It's self-promotion, we don't fix such "issues"

add in your filters:

`flickr.com##.ad-rail-card`
