### ISSUE TITLE
outred.github.io: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#15534]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outred.github.io/game`

### Category

ads

### Describe the issue

When visiting the site, the provider of the ads still has their banner. The link points to 

`https://publishers.adsterra.com/referral/quq7qA9mKK`

, the image is just a simple hyperlink.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

screenshot of the ad
![image](https://user-images.githubusercontent.com/58097612/199831253-9ff43b59-e267-4491-b261-bb3bee4e034e.png)

html element

![image](https://user-images.githubusercontent.com/58097612/199831491-2261f3d8-f620-4230-ba44-cae3ff806b16.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 321021
  cosmetic: 217597
  scriptlet: 37258
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 60502-94, 3m
    adguard-generic: 79310-476, 2m
    adguard-mobile: 8219-44, 2m
    adguard-social: 18843-842, 3m
    adguard-spyware: 36587-3646, 3m
    adguard-spyware-url: 794-1, 3m
    block-lan: 44-0, 3m
    curben-phishing: 167886-1, 3m
    curben-pup: 193-1, 3m
    fanboy-annoyance: 82232-4913, 2m
    fanboy-cookiemonster: 42543-42543, 2m
    fanboy-social: 23419-23419, 3m
    fanboy-thirdparty_social: 68-21, 3m
    ublock-annoyances: 4763-233, 3m
  default: 
    user-filters: 0-0, never
    easylist: 63250-1003, 3m
    easyprivacy: 30848-14144, 3m
    plowe-0: 3669-1029, 3m
    ublock-abuse: 76-0, 3m
    ublock-badware: 3953-240, 2m
    ublock-filters: 31168-3666, 2m
    ublock-privacy: 260-50, 2m
    ublock-quick-fixes: 466-42, 2m
    ublock-unbreak: 1904-99, 2m
    urlhaus-1: 11602-7, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15229 ms (selfie)
  maxAssetCacheWait: 11255 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googlesyndication.com: 1
```
</details>

**Comment by 3kh0** [comment]
Thank you again for unblock origin ❤️

**Comment by mapx-** [comment]
add

`outred.github.io##.ad`

@ryanbr
