### ISSUE TITLE
forzapalermo.it can't scroll down if annoyances filters are enabled

### ISSUE THREAD

**Issue by All3xJ** [uBlockOrigin/uAssets#15530]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://forzapalermo.it/`

### Describe the issue

Can't scroll down if I enable the annoyances filters

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106.0.3

### Settings

Added all annoyances filters. Removed ads filter.

**Comment by mapx-** [comment]
add

```
forzapalermo.it#@##cc--main > .cc_div
forzapalermo.it#@#.c--anim > #cc_div
forzapalermo.it#@#.c--anim > .cc_div
```

@ryanbr
