### ISSUE TITLE
nolotiro.org: breakage

### ISSUE THREAD

**Issue by kebianizao** [uBlockOrigin/uAssets#15545]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nolotiro.org/es/ad/243778/estamos-de-vuelta-recogemos-libros-en-madrid`

### Category

breakage

### Describe the issue

The main page content is blocked by uBO. If I disable uBO I can see the content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![correct image](https://user-images.githubusercontent.com/80541993/200148077-2ca1cb80-8405-480e-b2d4-7c79657d9065.png)

![incorrect image(uBO enabled)](https://user-images.githubusercontent.com/80541993/200148105-9f120039-f592-4c9e-a523-9b8deb4016f6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 106
filterset (summary): 
  network: 89374
  cosmetic: 43543
  scriptlet: 16877
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31907-110, 1h.26m
    ublock-badware: 3957-0, 1h.24m
    ublock-privacy: 288-0, 8d.1h.31m
    ublock-abuse: 76-0, 4d.4h.8m
    ublock-unbreak: 1917-9, 1h.27m
    easylist: 62730-319, 4d.4h.6m
    easyprivacy: 30834-1191, 4d.4h.5m
    urlhaus-1: 12018-0, 1h.22m
    spa-0: 3387-1, 1h.21m
    spa-1: 4828-123, 1h.25m
    ublock-quick-fixes: 482-0, 1h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 499 ms (selfie)
  maxAssetCacheWait: 335 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
nolotiro.org#@#.ad-hero
```
@ryanbr

**Comment by kebianizao** [comment]
Works great now! Thanks a lot!
