### ISSUE TITLE
diariodenavarra.es: detection

### ISSUE THREAD

**Issue by SpInstaller** [uBlockOrigin/uAssets#15548]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.diariodenavarra.es/

### Category

detection

### Describe the issue

PopUp screen blocks navigation for add blocker detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 92011
  cosmetic: 43533
  scriptlet: 16863
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 16-0, never
    ublock-filters: 31873-32, 3d.20h.58m
    ublock-badware: 3957-0, 1d.19h.41m
    ublock-privacy: 288-0, 5d.21h.3m
    ublock-abuse: 76-0, 5d.21h.2m
    ublock-unbreak: 1904-0, 1d.19h.40m
    easylist: 62662-682, 5d.21h.1m
    easyprivacy: 30834-1722, 5d.1h.39m
    urlhaus-1: 12018-0, 18h.57m
    plowe-0: 3671-3, 11d.13h.23m
    spa-0: 3387-13, 18h.56m
    spa-1: 4828-155, 1d.19h.39m
    ublock-quick-fixes: 477-20, 18h.58m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    diariodenavarra.es: 1
    20m.es: 1
    amazon-adsystem.com: 1
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    scorecardresearch.com: 1
    taboola.com: 1
    tpid.es: 1
```
</details>

**Comment by AntiAdvert** [comment]
If there's any other enabled blocker(ad / tracker blocket for instance), could you disable it?

**Comment by SpInstaller** [comment]
Theres no any other blockers enabled

**Comment by AntiAdvert** [comment]
`diariodenavarra.es##+js(nostif, abRelaxed)`
