### ISSUE TITLE
eaton.com breakage

### ISSUE THREAD

**Issue by Tractix** [uBlockOrigin/uAssets#15546]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://powerquality.eaton.com/emea/support/software-drivers/default.asp`

### Describe the issue

EATON's software and firmware download page doesn't work when using uBlock Origin

The normal behavior when accessing the link mentioned above with uBlock Origin Disabled/Removed for the first time is that, it should first ask from the country you are from (first screenshot) and then based on your selections of products and solutions, it should show you multiple download links (second screenshot).

When uBlock Origin is enabled on the link mentioned above and accessed for the first time, the site does not ask you at all from what country you are from and despite what products or solutions you select, no download links ever show up (third screenshot) since they seem to get removed by uBlock Origin.

### Screenshot(s)

https://user-images.githubusercontent.com/53498442/200151927-c3c0e02f-64d4-46ad-9bc5-b32aea5fd1de.png
https://user-images.githubusercontent.com/53498442/200151936-4fc4e9a1-ece8-438a-b580-cde7bcd2a748.png
https://user-images.githubusercontent.com/53498442/200152205-099f9618-554d-46c2-8828-bb2644dbfa58.png

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106.0.5 (64-bit) on Arch Linux

### Settings

The settings used were the default ones.

### Notes

The site was opened in a brand new Firefox profile with only uBlock Origin installed and no other plugins.

**Comment by mapx-** [comment]
add

`@@||powerquality.eaton.com/include/js/elqScr.js$script,1p`

@ryanbr
