### ISSUE TITLE
stroy-podskazka.ru: breakage

### ISSUE THREAD

**Issue by gotthehot** [uBlockOrigin/uAssets#15547]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://stroy-podskazka.ru/kormushki-i-skvorechniki-dlya-ptic/dlya-sinic-chtoby-ne-klevali-krupnye-pticy/`

### Category

breakage

### Describe the issue

Main articles (div class="article_entry") on this whole site disappear when uBlock Origin turned on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 106362
  cosmetic: 59519
  scriptlet: 17635
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39780-10, 1d.22h.26m
    easylist: 62633-66, 6d.1h.1m
    easyprivacy: 30826-1286, 6d.1h.2m
    plowe-0: 3669-869, 7d.23h
    ublock-abuse: 76-1, 7d.23h.2m
    ublock-badware: 3953-105, 3d.19h.3m
    ublock-filters: 31122-161, 3d.19h.4m
    ublock-privacy: 260-1, 9d.10h.32m
    ublock-unbreak: 1890-42, 3d.19h.2m
    urlhaus-1: 12018-0, 15h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 54 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 537 ms (selfie)
  maxAssetCacheWait: 590 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    stroy-podskazka.ru: 3
    google-analytics.com: 1
    googlesyndication.com: 2
    jsdelivr.net: 1
    nativerent.ru: 1
    nativeroll.tv: 1
    yandex.ru: 4
```
</details>

**Comment by okiehsch** [comment]
I can reproduce the hidden article.

**Comment by okiehsch** [comment]
@dimisa-RUAdList
Caused by
`stroy-podskazka.ru##div:has(> .adsbygoogle)`

**Comment by dimisa-RUAdList** [comment]
When using the Russian IP - the problem does not repeat. And it's a little weird.

Fixed: https://github.com/easylist/ruadlist/commit/8b16f2f94e576791cf4c61d9253a847df551fe1b
