### ISSUE TITLE
jamilacuisine.ro - right-click

### ISSUE THREAD

**Issue by AntiAdvert** [uBlockOrigin/uAssets#15544]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://jamilacuisine.ro/ciorba-radauteana-reteta-video/`

### Describe the issue

right-click doesn't work as expected

### uBlock Origin version

1.44.4

### Browser name and version

Google Chrome Version 107.0.5304.88 (Official Build) (64-bit)

### Settings

- I enabled `uBlock filters - Annoyances`

**Comment by mapx-** [comment]
maybe (if no breakage)

```
jamilacuisine.ro##+js(aost, document.oncontextmenu, , 2)
jamilacuisine.ro##+js(aost, Object,  /(?=^(?!.*(jquery|inlineScript)))/,2)
```
