### ISSUE TITLE
[nsfw] go.shareus.in: popups

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#15549]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://go.shareus.in/?shortid=iA5zyg&link=aHR0cHM6Ly9tZWdhLm56L2ZvbGRlci9rb1ZXbUJSSiNTMzROVTdycWNGbHpORmNWcUhCaFln`

### Category

popups

### Describe the issue

Clicking On Open Link Opens Popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox Mobile: 108
filterset (summary): 
  network: 100176
  cosmetic: 93292
  scriptlet: 22622
  html: 818
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/429ee0ad15b68c7c8507e9a6f81a0511e4386ee5/BaseFilter/sections/antiadblock.txt: 16777-96, 3d.3h.4m
    adguard-annoyance: 60483-2346, 3d.3h.4m
    ublock-annoyances: 4810-11, 3d.3h.4m
  default: 
    user-filters: 948-18, never
    ublock-filters: 32002-544, 3d.3h.5m
    ublock-badware: 3956-0, 3d.3h.5m
    ublock-privacy: 288-1, 3d.3h.5m
    ublock-abuse: 76-0, 3d.3h.5m
    ublock-unbreak: 1909-0, 3d.3h.5m
    ublock-quick-fixes: 470-0, 23h.17m
    adguard-mobile: 8221-169, 3d.3h.5m
    easylist: 63250-17741, 3d.3h.4m
    easyprivacy: 30848-1723, 3d.3h.4m
    urlhaus-1: 12018-0, 23h.16m
    plowe-0: 3669-3, 3d.3h.4m
filterset (user): [array of 907 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 964 ms (selfie)
  maxAssetCacheWait: 611 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Exactly, uBO has no such scriptlet.
