### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by neelpaul26** [uBlockOrigin/uAssets#15554]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

Everytime BINANCE NFT AD comes in the youtube home screen..but after reload it dissapears

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89311
  cosmetic: 38416
  scriptlet: 16624
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31908-53, 2d.5h.25m
    ublock-badware: 3957-0, 2d.5h.24m
    ublock-privacy: 285-0, 1d.17m
    ublock-abuse: 76-0, 12d.14h.2m
    ublock-unbreak: 1917-0, 2d.5h.23m
    ublock-quick-fixes: 482-9, 14h.47m
    easylist: 62730-630, 4d.12h.32m
    easyprivacy: 30834-1707, 4d.12h.31m
    urlhaus-1: 11847-0, 14h.46m
    plowe-0: 3671-3, 12d.14h
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10269 ms (selfie)
  maxAssetCacheWait: 428 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    youtube.com: 27
    doubleclick.net: 2
    google.co.in: 1
    google.com: 1
```
</details>

**Comment by gwarser** [comment]
>  allReadyAfter: 10269 ms (selfie)

uBO on your system is starting very slow.

**Comment by neelpaul26** [comment]
> > allReadyAfter: 10269 ms (selfie)
> 
> uBO on your system is starting very slow.

Is there something i can do?
otherwise there isnt much problem..

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
