### ISSUE TITLE
uprot.net: detection

### ISSUE THREAD

**Issue by corvonero** [uBlockOrigin/uAssets#15556]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uprot.net/msfi/bGltSVNQVmJ0VnpTRWNJcVNkVi9lZz09`

### Category

detection

### Describe the issue

detect uBlock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92548
  cosmetic: 45990
  scriptlet: 16633
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ITA-0: 13254-0, 2h.19m
    easylist: 63276-61, 1d.5h.32m
    easyprivacy: 30779-1172, 1d.5h.31m
    plowe-0: 3667-866, 1d.5h.30m
    ublock-abuse: 76-0, 1d.5h.28m
    ublock-badware: 3953-105, 1d.5h.26m
    ublock-filters: 31170-137, 1d.5h.25m
    ublock-privacy: 260-1, 1d.5h.24m
    ublock-quick-fixes: 487-20, 2h.18m
    ublock-unbreak: 1904-51, 1d.5h.22m
    urlhaus-1: 8916-0, 2h.17m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9370 ms (selfie)
  maxAssetCacheWait: 1094 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    peacto.com: 1
    sdbvveonb1.com: 1
    velocitycdn.com: 1
```
</details>

**Comment by Alessio979** [comment]
https://uprot.net/msf/78wl9mnhrg54
DISABLE YOUR ADBLOCK

**Comment by Alessio979** [comment]
news?
Thanks

**Comment by mapx-** [comment]
no issue on my end

**Comment by Alessio979** [comment]
Hi @mapx- 
Can you view this link correctly?
`https://uprot.net/msf/78wl9mnhrg54`

Thanks

**Comment by mapx-** [comment]
yes, I get "continue" then click play and run the video

**Comment by Alessio979** [comment]
uhmmm... it's very strange

![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/13daa17a-9dcc-4747-bda2-2cb203aaf946)

**Comment by Alessio979** [comment]
i try with SSH connection and it's works regular

**Comment by Alessio979** [comment]
if i disable ublock the continue button appears, can you check this? thanks

**Comment by dexter35a** [comment]
> if i disable ublock the continue button appears, can you check this? `https://uprot.net/msf/likucfwbcaep`
> 
> thanks

Ciao a me sul tuo link lo fa ma su questo no? 
A te funziona su questo?

https://uprot.net/msf/8789p2hrh6vh     

eppure il formato link sembra uguale..

**Comment by ItsProfessional** [comment]
Is this a shortener? I get cloudflare blocked.

**Comment by Alessio979** [comment]
> From which location you are accessing the link?

italy
