### ISSUE TITLE
goplay.be: breakage

### ISSUE THREAD

**Issue by iluvatoq** [uBlockOrigin/uAssets#15551]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goplay.be/video/now-what/now-what-s1/now-what-s1-aflevering-42`

### Category

breakage

### Describe the issue

Video keeps loading, not playing. When turning off video ads start and then video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 80432
  cosmetic: 45242
  scriptlet: 17653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69310-505, never
    easyprivacy: 27312-101, never
    plowe-0: 3634-450, never
    ublock-abuse: 76-0, never
    ublock-badware: 4233-0, never
    ublock-filters: 32512-138, never
    ublock-privacy: 231-1, never
    ublock-quick-fixes: 389-0, never
    ublock-unbreak: 1858-31, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 933 ms
  maxAssetCacheWait: 15 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    goplay.be: 1
    cxense.com: 2
    doubleclick.net: 4
    gemius.pl: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    onthe.io: 1
    summerhamster.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `NLD: EasyDutch` list and test again?

**Comment by iluvatoq** [comment]
Thank you for the response.
Enabled, saved, update. Restarted browser but wheel keeps loading but does not play.

**Comment by iluvatoq** [comment]
Anything else is just standard, nothing was changed on the settings for now just enabled NLD

**Comment by BPower0036** [comment]
@stephenhawk8054 Made an account to see the video, but I cannot confirm either.

**Comment by mapx-** [comment]
> I cannot confirm either

confirm the breakage ? meaning you get & play correctly the video ?

**Comment by BPower0036** [comment]
Yes, the breakage is not confirmed.
So, the video plays correctly, without the wheel keep loading.

**Comment by iluvatoq** [comment]
So the issue is with me then?

**Comment by AntiAdvert** [comment]
![image](https://user-images.githubusercontent.com/117537631/200359998-4ac91c1c-3005-42f4-acd7-936b2290ebf3.png)

**Comment by iluvatoq** [comment]
[De Allerslimste Mens ter Wereld.webm](https://user-images.githubusercontent.com/81825037/200360109-afc6044c-2742-4d5d-a5bf-8ac57476d3ed.webm)

**Comment by iluvatoq** [comment]
I am using chrome btw

**Comment by AntiAdvert** [comment]
- `chrome://extensions/` -> is there any extension other than `Google Docs Offline` and `uBlock Origin`>
- Do you have any modified `hosts` file?
- Do you use any ad / tracker-blocking DNS server? If it is on the computer or the router, you can use a different one in Chrome I think

**Comment by iluvatoq** [comment]
I do have malwarebytes addon installed

**Comment by AntiAdvert** [comment]
> I do have malwarebytes addon installed

Is it an ad blocker?

**Comment by iluvatoq** [comment]
Browser Guard it states

**Comment by AntiAdvert** [comment]
https://chrome.google.com/webstore/detail/malwarebytes-browser-guar/ihcjicgdanjaechkgeegckofjjedodee 
![image](https://user-images.githubusercontent.com/117537631/200365016-3e5aa11a-f58b-4958-bf7c-5dda34477418.png)

**Comment by iluvatoq** [comment]
I disabled the ad tracking thing in malware bytes and it's now working

**Comment by iluvatoq** [comment]
Thanks for the help!

**Comment by AntiAdvert** [comment]
You're welcome
