### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by BiggieNuggz** [uBlockOrigin/uAssets#15557]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/hasanabi`

### Category

ads

### Describe the issue

doesnt block the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 86895
  cosmetic: 38448
  scriptlet: 16641
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63250-55, 2d.20h.11m
    easyprivacy: 30848-1170, 2d.20h.10m
    plowe-0: 3669-865, 8d.20h.29m
    ublock-abuse: 76-0, 17h.18m
    ublock-badware: 3953-105, 17h.17m
    ublock-filters: 31177-103, 17h.16m
    ublock-privacy: 257-1, 17h.15m
    ublock-quick-fixes: 476-34, 19h.29m
    ublock-unbreak: 1904-51, 17h.14m
    urlhaus-1: 8916-0, 19h.27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 407 ms (selfie)
  maxAssetCacheWait: 54 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 2
    scorecardresearch.com: 2
    serving-sys.com: 1
```
</details>

**Comment by AntiAdvert** [comment]
https://github.com/pixeltris/TwitchAdSolutions

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
