### ISSUE TITLE
accounts.o2.co.uk: breakage

### ISSUE THREAD

**Issue by 1Mark** [uBlockOrigin/uAssets#15552]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://accounts.o2.co.uk/resetpassword/otac`

### Category

breakage

### Describe the issue

This text box is missing 
![image](https://user-images.githubusercontent.com/15360245/200183469-aa0cbce1-5456-4498-9b69-03a85eb51c08.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

ublock Enabled 
![image](https://user-images.githubusercontent.com/15360245/200182837-b1d1704a-5d2b-4f5d-8016-455b5c2813aa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89686
  cosmetic: 38443
  scriptlet: 16629
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63276-56, 1d.18h.13m
    easyprivacy: 30779-1170, 20h.44m
    plowe-0: 3667-865, 1d.18h.18m
    ublock-abuse: 76-0, 6d.23h.44m
    ublock-badware: 3953-105, 1d.18h.16m
    ublock-filters: 31183-133, 1d.18h.14m
    ublock-privacy: 260-1, 6d.23h.43m
    ublock-quick-fixes: 476-20, 34m
    ublock-unbreak: 1903-51, 1d.18h.15m
    urlhaus-1: 11742-0, 33m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 802 ms (selfie)
  maxAssetCacheWait: 361 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adobedtm.com: 1
    demdex.net: 3
    googletagmanager.com: 1
    omtrdc.net: 1
    tealiumiq.com: 2
    tiqcdn.com: 1
    yext-pixel.com: 1
```
</details>

**Comment by AntiAdvert** [comment]
`@@||googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5,domain=accounts.o2.co.uk`

**Comment by mapx-** [comment]
@1Mark 

test

```
@@||assets.adobedtm.com/*.js$script,domain=accounts.o2.co.uk
||assets.adobedtm.com/*source.min.js$script,domain=accounts.o2.co.uk,important
```

**Comment by 1Mark** [comment]
`@@||assets.adobedtm.com/*.js$script,domain=accounts.o2.co.uk`
Worked 🥳

**Comment by 1Mark** [comment]
@mapx- how did you know that one - out of all of the blocked ones - was the issue?

**Comment by mapx-** [comment]
no magic .. just some experience with similar issues and then trying

**Comment by AntiAdvert** [comment]
https://github.com/gorhill/ublock/wiki/The-logger and uBO's matrix tend to be handy in attempting to fix breakages
