### ISSUE TITLE
partitionwizard.com: ads

### ISSUE THREAD

**Issue by KawaiiKraken** [uBlockOrigin/uAssets#15559]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.partitionwizard.com/`

### Category

ads

### Describe the issue

banner ad at the bottom, pops up everywhere i could find on the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-06 182118](https://user-images.githubusercontent.com/111396148/200200973-b5b7da4f-3792-41a1-a535-3623a3526de4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89288
  cosmetic: 38479
  scriptlet: 16642
  html: 794
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31901-68, 57m
    ublock-badware: 3962-0, 56m
    ublock-privacy: 288-0, 5d.21h.48m
    ublock-abuse: 76-0, 5d.21h.47m
    ublock-unbreak: 1903-0, 55m
    ublock-quick-fixes: 493-0, 53m
    easylist: 62881-596, 58m
    easyprivacy: 30823-1707, 6d.23h.16m
    urlhaus-1: 11742-0, 54m
    plowe-0: 3667-3, 2d.6h.21m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 215 ms (selfie)
  maxAssetCacheWait: 146 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    duckduckgo.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
The bottom banner seems to be self-promo
Popups ?
