### ISSUE TITLE
quizlet.com: ads

### ISSUE THREAD

**Issue by takemycookies** [uBlockOrigin/uAssets#15555]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://quizlet.com/`

### Category

ads

### Describe the issue

Quizlet (flashcard app) is now showing ads even with adblocker. The image content is gone, but the actual ad leftover is still there (still blocks content). Quizlet did not add a new advertising feature and Ublock has been blocking the quizlet ads for months until now.
Thanks.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 90816
  cosmetic: 38460
  scriptlet: 16628
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64358-52, 3h.56m
    easyprivacy: 30779-1171, 3h.55m
    plowe-0: 3667-867, 23h.58m
    ublock-abuse: 76-0, 1d.15h.21m
    ublock-badware: 3953-109, 2d.16h.57m
    ublock-filters: 31165-146, 2d.16h.56m
    ublock-privacy: 260-1, 1d.15h.20m
    ublock-quick-fixes: 476-20, 16h.52m
    ublock-unbreak: 1898-51, 2d.16h.55m
    urlhaus-1: 11847-0, 15h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 385 ms (selfie)
  maxAssetCacheWait: 73 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    adlightning.com: 1
    amazon-adsystem.com: 1
    btloader.com: 1
    doubleclick.net: 1
    google.com: 9
    googletagmanager.com: 1
    pubmatic.com: 1
    quantserve.com: 1
    rollbar.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
account required, even if creating an account (free way) still **needing example pages where you get ads**

**Comment by takemycookies** [comment]
![image](https://user-images.githubusercontent.com/117595475/200190213-6f9dae9b-7afa-4a02-b03e-d02ad0bea8e9.png)
Ok.

**Comment by mapx-** [comment]
Where's the specific link to reproduce the issue ?

**Comment by takemycookies** [comment]
https://quizlet.com/257412364/flashcards
This was the link I got an ad on, but to my knowledge any flashcard link works. If you full screen the flashcards (bottom right), and repeatedly click the arrow to the right you will probably get one of these screens. But it might take a while or you may need to repeat the process by clicking the left arrow to the beginning.
Thanks.

**Comment by takemycookies** [comment]
Sorry, I closed the issue.

**Comment by liamengland1** [comment]
Skips countdown:
`quizlet.com##+js(nano-stb, /y-1/, 1000)` 
but you still have to click `Skip ad` button :(

**Comment by takemycookies** [comment]
Thanks, this still helps a lot. I appricate it!

**Comment by liamengland1** [comment]
> Skips countdown: `quizlet.com##+js(nano-stb, /y-1/, 1000)` but you still have to click `Skip ad` button :(

@mapx- can you add this to uBo filters or annoyances?

**Comment by mapx-** [comment]
added 2 days ago

**Comment by liamengland1** [comment]
> added 2 days ago

ok thanks, didn't see referenced commit. will check better next time
