### ISSUE TITLE
ppss.kr: breakage

### ISSUE THREAD

**Issue by DavidLee3835** [uBlockOrigin/uAssets#15565]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ppss.kr/`

### Category

breakage

### Describe the issue

A dialog that saying 'Website Loading Failed' appears and website's broken.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/99162643/200310787-5a42a1c8-0571-411c-8dd4-2c09fbdb9d1d.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 80560
  cosmetic: 46887
  scriptlet: 17580
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    KOR-1: 2736-11, 103d.7h.17m
    easylist: 68820-80, 103d.7h.25m
    easyprivacy: 27450-133, 103d.7h.24m
    plowe-0: 3641-786, 103d.7h.23m
    ublock-abuse: 76-0, 103d.7h.22m
    ublock-badware: 4209-92, 103d.7h.21m
    ublock-filters: 32281-117, 103d.7h.20m
    ublock-privacy: 225-5, 103d.7h.19m
    ublock-quick-fixes: 262-1, 103d.7h.16m
    ublock-unbreak: 1836-42, 103d.7h.18m
    urlhaus-1: 4926-0, 103d.7h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 723 ms (selfie)
  maxAssetCacheWait: 423 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    ppss.kr: 3
    ad-shield.io: 5
    doubleclick.net: 3
    facebook.com: 1
    facebook.net: 1
    google-analytics.com: 1
    google.co.kr: 1
    google.com: 1
    googleadservices.com: 1
    googlesyndication.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
The reason is because they use a script called "Ad-Shield" which is a ad script to bring ads for adblock users back and self breaking the website when a adblocker also block the Ad-Shield ads so the user think its our fault.

For the best blocking result you can use microShield, its a special userscript to block Ad-Shield ads without the "breakage"
https://github.com/List-KR/microShield
