### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by corvonero** [uBlockOrigin/uAssets#15566]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://maxstream.video/5sg6vwpajxfo/Y0REYmtlRTBiZjRTYW1sdXJ6Z25Pb2pEZ1VJQmtiZHJENndUSGIrWEdFS2RNdnpkeHZvV2hkMExjeWFja2xKWg==`

### Category

detection

### Describe the issue

detect Ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92548
  cosmetic: 45990
  scriptlet: 16633
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ITA-0: 13254-0, 21h.5m
    easylist: 63276-61, 2d.18m
    easyprivacy: 30779-1172, 2d.17m
    plowe-0: 3667-866, 2d.16m
    ublock-abuse: 76-0, 2d.14m
    ublock-badware: 3953-105, 2d.12m
    ublock-filters: 31170-137, 2d.11m
    ublock-privacy: 260-1, 2d.10m
    ublock-quick-fixes: 487-20, 21h.4m
    ublock-unbreak: 1904-51, 2d.8m
    urlhaus-1: 8916-0, 21h.3m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17514 ms (selfie)
  maxAssetCacheWait: 891 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    host-cdn.net: 1
    intellipopup.com: 1
    setsdowntown.com: 2
```
</details>

**Comment by mapx-** [comment]
working example:
`https://maxstream.video/jihmcfyjxeo0/TmR6OEhvM2lzTnFQUUJ4MisvcGFadz09`

for 2-3 seconds an anti-adb message and then the normal playable video

**Comment by lordmarte** [comment]
not completed

**Comment by stephenhawk8054** [comment]
> not completed

Can you give an example URL?
