### ISSUE TITLE
next-episode.net: detection

### ISSUE THREAD

**Issue by 27chandler** [uBlockOrigin/uAssets#15569]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://next-episode.net/`

### Category

detection

### Describe the issue

When on next episode an overlay prevents usage of the site until you buy premium or you whitelist the site on ublock (I tested whitelisting and it doesn't affect the overlay unfortunately)

Adding the overlay to the filter list using the block element picker doesn't work as the overlay has a different name each time the page is refreshed/a new page is loaded. I've confirmed this happens even when ublock origin is the only add-on installed, and the site no longer detects ublock if its disabled or uninstalled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19729460/200402178-76473df1-e7b9-4519-83bd-4a8db3980a7b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 94802
  cosmetic: 109864
  scriptlet: 22526
  html: 819
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4791-5, 19h.1m
    adguard-annoyance: 60736-1557, 19h.1m
    adguard-social: 18861-32, 19h.1m
  default: 
    user-filters: 58-6, never
    ublock-filters: 31905-69, 19h.1m
    ublock-badware: 3962-0, 19h.1m
    ublock-privacy: 285-0, 19h.1m
    ublock-abuse: 76-0, 19h.1m
    ublock-unbreak: 1903-0, 19h.1m
    easylist: 64358-611, 19h.1m
    easyprivacy: 30783-1708, 19h.1m
    plowe-0: 3668-3, 19h.1m
    urlhaus-1: 10281-0, 19h.1m
    ublock-quick-fixes: 496-0, 19h.1m
filterset (user): [array of 59 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 653 ms
  maxAssetCacheWait: 327 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by rmarghi** [comment]
Note: Site can still detect uBlock as of 12/29/2022
