### ISSUE TITLE
duckduckgo.com: nuisance

### ISSUE THREAD

**Issue by barraIhsan** [uBlockOrigin/uAssets#15562]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://duckduckgo.com/`

### Category

nuisance

### Describe the issue

If you search anything on DuckDuckGo and you dont install the [DuckDuckGo Privacy Essentials](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/) extensions. It will show a popup that telling you to download their extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/57800056/200209577-fd2b641f-21b5-4878-a652-e72dca107ef8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 89247
  cosmetic: 38481
  scriptlet: 16647
  html: 796
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31905-68, now
    ublock-badware: 3962-0, now
    ublock-privacy: 285-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1903-0, now
    ublock-quick-fixes: 496-0, now
    easylist: 64358-607, now
    easyprivacy: 30783-1708, now
    urlhaus-1: 10281-0, now
    plowe-0: 3668-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2678 ms
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    duckduckgo.com: 10
```
</details>

**Comment by mapx-** [comment]
Enable `Fanboy’s Annoyance` list

**Comment by barraIhsan** [comment]
Why requiring 3rd party list if it's better to add to the default annoyance list?

**Comment by stephenhawk8054** [comment]
> Why requiring 3rd party list if it's better to add to the default annoyance list?

https://github.com/uBlockOrigin/uAssets#uassets

> Any resolution of issues without using extended syntax ([scriptlet injection](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection), [redirect](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect), [procedural cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters), etc.) will not occur in uAssets. The preferable way is to fix it in EasyList, if possible.
