### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by deadman616** [uBlockOrigin/uAssets#15563]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Describe the issue

all I see is a empty page when a I open dragontea.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 125599
  cosmetic: 147522
  scriptlet: 31965
  html: 796
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 79338-4648, now
    adguard-mobile: 8227-147, now
    adguard-annoyance: 60736-1415, 1m
    adguard-social: 18861-28, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31905-162, 2m
    ublock-badware: 3962-0, 2m
    ublock-privacy: 285-0, 2m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1903-0, 2m
    ublock-quick-fixes: 496-0, 2m
    easylist: 64358-659, 2m
    easyprivacy: 30783-1731, 2m
    urlhaus-1: 10281-0, 2m
    plowe-0: 3668-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1696 ms
  maxAssetCacheWait: 610 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    amazon-adsystem.com: 1
    doubleclick.net: 2
    googletagmanager.com: 1
    stpd.cloud: 2
```
</details>

**Comment by AntiAdvert** [comment]
```
||z-na.amazon-adsystem.com^$xhr,redirect-rule=nooptext
@@||dragontea.ink^$ghide
```

I think `||z-na.amazon-adsystem.com^$xhr,redirect-rule=nooptext` could be added to the rules for `chp anti-adblock`

**Comment by mapx-** [comment]
add

```
@@||z-na.amazon-adsystem.com/widgets/$xhr,domain=dragontea.ink
@@||stpd.cloud^$script,domain=dragontea.ink
@@||dragontea.ink^$ghide
dragontea.ink##+js(nostif, ads)
```
