### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by tamasys** [uBlockOrigin/uAssets#15561]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.instagram.com/p/CisLCRAL6RL/`

### Category

breakage

### Describe the issue

This specific Instagram post is blocked by uBlock Origin, both in the direct page link and when opened in the lightbox by clicking on the picture from the https://www.instagram.com/dcss_australia Instagram page. Almost all other posts on the page work, just not this one. It reappears if I disable cosmetic filtering in uBlock Origin. I've tested this on multiple computers in both Chrome and Edge.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/2321397/200207766-5f1e6c4f-a062-4733-a037-47590102fb0e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 89251
  cosmetic: 38480
  scriptlet: 16651
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64358-52, 5m
    easyprivacy: 30783-1170, 5m
    plowe-0: 3668-867, 5m
    ublock-abuse: 76-0, 5m
    ublock-badware: 3958-109, 5m
    ublock-filters: 31164-108, 5m
    ublock-privacy: 257-1, 5m
    ublock-quick-fixes: 488-34, 5m
    ublock-unbreak: 1890-42, 5m
    urlhaus-1: 10281-0, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4034 ms (selfie)
  maxAssetCacheWait: 566 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    instagram.com: 17
```
</details>

**Comment by mapx-** [comment]
it's due to
`instagram.com##div[style="max-height: inherit; max-width: inherit;"]:has(span:has-text(Paid partnership with ))`

for `Paid partnership`

tbh it seems to be exagerate => the user will get it as a breakage issue (the dcss_australia page showing it and clicking it does nothing)

@okiehsch what do you think about ?

**Comment by okiehsch** [comment]
See my comment at https://github.com/uBlockOrigin/uAssets/issues/14370#issuecomment-1217583968
If it blocks influencer posts I am against such a filter because it's an integral part of instagram imo,
even if it is - strictly speaking - advertisement.
