### ISSUE TITLE
[nsfw] dragontea.ink: detection

### ISSUE THREAD

**Issue by Taras255** [uBlockOrigin/uAssets#15570]
### Prerequisites

- [x] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Describe the issue

Blocks the use of the website.
Adblock message displayed replacing website. Website not accessible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/117605241/200438602-5e94554d-910d-4163-9fac-0082b97714ea.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 133558
  cosmetic: 195313
  scriptlet: 24461
  html: 0
listset (total-discarded, last updated): 
  added: 
    FRA-0: 30745-18, 2d.1h.43m
    adguard-annoyance: 60736-120, 2d.1h.43m
    adguard-social: 18861-842, 2d.1h.43m
    dpollock-0: 11390-43, 2d.1h.43m
    fanboy-annoyance: 82441-4889, 2d.1h.43m
    fanboy-cookiemonster: 42744-42744, 2d.1h.43m
    fanboy-social: 23421-23421, 2d.1h.43m
    fanboy-thirdparty_social: 69-21, 2d.1h.43m
    ublock-annoyances: 4768-206, 2d.1h.43m
  default: 
    user-filters: 58-7, never
    POL-0: 7858-15, 42m
    POL-2: 1276-13, 1d.4h.48m
    easylist: 64358-1116, 5h.25m
    easyprivacy: 30834-1675, 6d.9h.44m
    plowe-0: 3667-1267, 2d.1h.43m
    ublock-abuse: 76-1, 6d.9h.46m
    ublock-badware: 3953-119, 2d.1h.43m
    ublock-filters: 31165-663, 3d.4h.35m
    ublock-privacy: 260-9, 6d.9h.47m
    ublock-quick-fixes: 505-22, 44m
    ublock-unbreak: 1890-49, 1d.56m
    urlhaus-1: 10281-0, 43m
filterset (user): [array of 58 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2884 ms (selfie)
  maxAssetCacheWait: 2021 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    doubleclick.net: 2
    fonts.googleapis.com: 1
    google-analytics.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by Taras255** [comment]
yes - and it did not help

**Comment by stephenhawk8054** [comment]
Ok, I can reproduce in chromium.
