### ISSUE TITLE
app.molotov.tv: nuisance

### ISSUE THREAD

**Issue by Rudloff** [uBlockOrigin/uAssets#15577]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.molotov.tv/channels/19/program/20652`

### Category

nuisance

### Describe the issue

The video player displays a pop-in asking to disable the adblocker.

(You will need an account to access the app.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/840125/200656235-206b231d-8efa-403b-b650-c0b671de148d.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 117630
  cosmetic: 120669
  scriptlet: 18558
  html: 797
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 82476-314, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 31914-160, now
    ublock-badware: 3962-0, now
    ublock-privacy: 285-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1906-0, now
    easylist: 64372-634, now
    easyprivacy: 30787-1708, now
    urlhaus-1: 10851-0, now
    plowe-0: 3668-3, now
    FRA-0: 30809-433, now
    ublock-quick-fixes: 522-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 338 ms (selfie)
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    molotov.tv: 1
    datadoghq.com: 1
    doubleclick.net: 1
    privacy-center.org: 1
    segment.io: 4
    sentry.io: 2
    youborafds01.com: 4
```
</details>

**Comment by AntiAdvert** [comment]
Is a paid account required?

**Comment by Rudloff** [comment]
No, you can register for a free account.

**Comment by mapx-** [comment]
Needing a french ip otherwise they are requesting a payment.
vpn does not work too.

@Procyon-b could you take a look ?

**Comment by Procyon-b** [comment]
@mapx- doesn't work for me neither. A belgian ip doesn't make the cut.

**Comment by AntiAdvert** [comment]
Does anybody here have a streaming-geared VPN subscription?

**Comment by Rudloff** [comment]
It seems to work, thanks!
