### ISSUE TITLE
WebTorrent peer introduction servers blocked

### ISSUE THREAD

**Issue by feross** [uBlockOrigin/uAssets#1557]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://instant.io/#https://webtorrent.io/torrents/sintel.torrent`
`https://webtorrent.io`

### Describe the issue

WebTorrent is a library that allows a user to use BitTorrent in the web browser. It uses WebRTC to help peers connect to each other. There are a few WebSocket servers that users connect to in order to find peers to download files from. In BitTorrent parlance, these introduction servers are known as "trackers", but they have nothing to do with ad trackers.

It seems that a few rules from the EasyPrivacy list are blocking WebTorrent tracker servers, preventing WebTorrent from working. Specifically, these rules:

```
.xyz^$third-party,websocket
||fastcast.nz^$third-party
||tracker.openwebtorrent.com^$third-party
```

These servers are "BitTorrent trackers" (i.e. peer introduction servers) that help users register their interest in particular torrents and connect to other peers who have the files they are looking for. Blocking them totally breaks WebTorrent.

### Versions

- Browser/version: Chrome 64.0.3282.167 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.15.2

### Settings

- EasyPrivacy list is enabled

### Notes

Can we remove these rules?

**Comment by mapx-** [comment]
You should report here (it's about easyprivacy list)
https://github.com/easylist/easylist/issues

@ryanbr

**Comment by mapx-** [comment]
However, how could someone reproduce / test your issue ?

**Comment by mapx-** [comment]
I'll add a fix (invalidating those filters) but will work only for uBo users (until easylist authors will fix your issue). 

However, if you are (will) using mining stuff => will block your sites again.

**Comment by gorhill** [comment]
Until we understand why these filters exist, maybe we should re-add them as:

    .xyz^$third-party,websocket,domain=~webtorrent.io
    ||fastcast.nz^$third-party,domain=~webtorrent.io
    ||tracker.openwebtorrent.com^$third-party,domain=~webtorrent.io

**Comment by ryanbr** [comment]
NSFW: `https://bitties.tubetitties.com/7tL4HnMDwZA`   why it was added; from the [orginal commit; ](https://github.com/easylist/easylist/commit/62e6fdad54f3e37863ed018a8301b104bc896eed)

**Comment by ryanbr** [comment]
I'm not convinced this a good thing, using a users bandwidth without consent

**Comment by mapx-** [comment]
it's p2p streaming ..

**Comment by feross** [comment]
@mapx- Thanks for the explanation. I opened an issue on EasyList here: https://github.com/easylist/easylist/issues/916

Just FYI: The WebTorrent project doesn't engage in any browser mining or any monetization at all. It's an open source project, info here: https://github.com/webtorrent/webtorrent.

**Comment by feross** [comment]
It sounds like the NSFW site that @ryanbr referenced was doing mining but also used WebTorrent to distribute their content.

> I'm not convinced this a good thing, using a users bandwidth without consent

I understand this perspective, but the user is only (1) sharing content they are already downloading, never hosting random content, and (2) the browser already lets site authors make your browser upload data to a server as much as it wants.

WebTorrent is usually used in a very obvious way. For example, on https://instant.io it is obvious that the user is about to start torrenting. Usually sites show the # of connected peers / upload rate.

Here's an example of a site called PeerTube that uses WebTorrent to implement a P2P YouTube-like site: `https://peertube.cpy.re/videos/watch/f78a97f8-a142-4ce1-a5bd-154bf9386504`

As a uBlock Origin user myself, I understand the desire to block bad actors. But in the wild, I've never seen WebTorrent used to "steal" bandwidth or anything like that. In my experience it's always been pretty obvious to the user that they're doing P2P streaming.
