### ISSUE TITLE
dcinside.com: breakage

### ISSUE THREAD

**Issue by suitzs** [uBlockOrigin/uAssets#15571]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dcinside.com/`

### Category

breakage

### Describe the issue

ERR_TIMED_OUT

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![제목 없음](https://user-images.githubusercontent.com/117702136/200466526-ce086404-cef5-4e5e-a91e-5a97ae1d5b2a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 91338
  cosmetic: 40870
  scriptlet: 16758
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 21-3, never
    KOR-1: 3597-4, 2m
    easylist: 64363-88, 2m
    easyprivacy: 30787-1179, 2m
    plowe-0: 3668-881, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 3958-109, 2m
    ublock-filters: 31172-110, 2m
    ublock-privacy: 257-3, 1m
    ublock-quick-fixes: 510-34, 1m
    ublock-unbreak: 1893-42, 1m
    urlhaus-1: 11275-0, 1m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 36426 ms (selfie)
  maxAssetCacheWait: 743 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
popupPanel: 
  blocked: 0
```
I don't think it's uBO's issue.

**Comment by dportvine** [comment]
Possibly network problems. Github was very slow yesterday.
<details>
<summary>Screen</summary>

![2022-11-08_092249](https://user-images.githubusercontent.com/111344219/200500108-9c65540a-f83d-4a7f-9346-ea17ca33a050.png)
</details>
