### ISSUE TITLE
healdad.com: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#15576]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://healdad.com/t/%D8%A7%D9%84%D8%AD%D8%AC%D8%A7%D9%85%D8%A9-%D9%83%D9%86%D8%B2-%D9%85%D9%86-%D8%A7%D9%84%D8%B3%D9%86%D8%A9-%D8%A7%D9%84%D9%86%D8%A8%D9%88%D9%8A%D8%A9/`

### Category

detection

### Describe the issue

This site detects uBo.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/200555428-25c59ec3-ffec-4af8-bc64-6a26a5db8f58.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 94555
  cosmetic: 43406
  scriptlet: 16654
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist.to/easylist/easylist.txt: 64364-52, 5h.37m
  default: 
    user-filters: 28-0, never
    IDN-0: 9188-1, 1d.19h.30m
    easylist: 64358-64353, 5h.39m
    easyprivacy: 30787-1172, 5h.38m
    plowe-0: 3669-867, 6d.23h.27m
    ublock-abuse: 76-0, 1d.19h.29m
    ublock-badware: 3953-109, 1d.19h.28m
    ublock-filters: 31190-134, 1d.19h.27m
    ublock-privacy: 257-1, 1d.19h.26m
    ublock-quick-fixes: 507-34, 5h.36m
    ublock-unbreak: 1888-44, 1d.19h.25m
    urlhaus-1: 11275-0, 5h.35m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 588 ms (selfie)
  maxAssetCacheWait: 368 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    healdad.com: 1
    demand.supply: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    inklinkor.com: 1
```
</details>

**Comment by liamengland1** [comment]
Original link which took you to that page?

**Comment by yohanes4dip** [comment]
Yes, that link took me to that page.

Pada tanggal Sel, 8 Nov 2022 21.55, Liam England ***@***.***>
menulis:

**Comment by AntiAdvert** [comment]
Is there any way to overcome IP bans (or whatever anti-VPN / anti-proxy stuffmay be found on sites)?

**Comment by AntiAdvert** [comment]
https://user-images.githubusercontent.com/117537631/200640235-28d19443-d410-4d21-8181-6baaa4866c1d.png
