### ISSUE TITLE
sportalkorea.com: breakage

### ISSUE THREAD

**Issue by DavidLee3835** [uBlockOrigin/uAssets#15574]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sportalkorea.com/`

### Category

breakage

### Describe the issue

Related issues: #15572, #15565

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/99162643/200501836-1bea77ba-037f-4f7c-8b3d-6b63dd481f2c.png">
uBO Enabled

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/99162643/200501935-a8c228f4-e104-4298-8f41-862011ff0bf6.png">
uBO Disabled

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 91336
  cosmetic: 40855
  scriptlet: 16758
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    KOR-1: 3597-4, 26m
    easylist: 64364-88, 26m
    easyprivacy: 30787-1179, 26m
    plowe-0: 3668-881, never
    ublock-abuse: 76-0, 25m
    ublock-badware: 3958-109, 25m
    ublock-filters: 31172-110, 25m
    ublock-privacy: 257-3, 25m
    ublock-quick-fixes: 510-34, 25m
    ublock-unbreak: 1893-42, 25m
    urlhaus-1: 11275-0, 25m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 723 ms (selfie)
  maxAssetCacheWait: 423 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ad-shield.io: 4
    feeldmc.com: 5
    google-analytics.com: 1
    interworksmedia.co.kr: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@benjamin3048 Set the site to "Optimal" mode in uBOL and test again.
