### ISSUE TITLE
promobit.com.br: breakage

### ISSUE THREAD

**Issue by tiagotecno** [uBlockOrigin/uAssets#15579]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.promobit.com.br/Redirect/to/1261406/`

### Category

breakage

### Describe the issue

a pagina fecha

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/117776894/200673882-a8965677-a8b1-44f4-9ef5-7bc8b70c4261.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 91245
  cosmetic: 41578
  scriptlet: 16898
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64363-52, 1d.29m
    easyprivacy: 30783-1170, 1d.28m
    plowe-0: 3669-867, 7d.55m
    spa-1: 4828-70, 2d.9h.15m
    ublock-abuse: 76-0, 2d.9h.14m
    ublock-badware: 3953-109, 2d.9h.13m
    ublock-filters: 31177-139, 2d.9h.12m
    ublock-privacy: 260-1, 2d.9h.11m
    ublock-quick-fixes: 510-34, 3h.21m
    ublock-unbreak: 1895-43, 2d.9h.10m
    urlhaus-1: 10851-0, 3h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 411 ms (selfie)
  maxAssetCacheWait: 184 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.net: 1
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

`||zenaps.com^$badfilter`

We cannot add it to our lists (Easylist / easyprivacy denied either) due to privacy issues

**Comment by tiagotecno** [comment]
thanks
