### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by lucaskin** [uBlockOrigin/uAssets#15573]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/tarik`

### Category

ads

### Describe the issue

doesnt block ads on twitch at all

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89268
  cosmetic: 38459
  scriptlet: 16625
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62898-52, 1d.23h.9m
    easyprivacy: 30787-1170, 8h.11m
    plowe-0: 3667-865, 1d.15h.7m
    ublock-abuse: 76-0, 2d.17h.58m
    ublock-badware: 3953-105, 4d.5h.7m
    ublock-filters: 31145-139, 4d.5h.6m
    ublock-privacy: 260-1, 2d.17h.57m
    ublock-quick-fixes: 487-20, 1d.5h.13m
    ublock-unbreak: 1898-51, 4d.5h.5m
    urlhaus-1: 11742-0, 1d.5h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1691 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
see what to do https://github.com/pixeltris/TwitchAdSolutions

duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
