### ISSUE TITLE
myauto.ge: breakage

### ISSUE THREAD

**Issue by datka1** [uBlockOrigin/uAssets#15585]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.myauto.ge/ka/pr/80797789/iyideba-manqanebi-sedani-mercedes-benz-c-200-1997-benzini-tbilisi`

### Category

breakage

### Describe the issue

Main mage is loading. its not loading  cars...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 106538
  cosmetic: 59669
  scriptlet: 17884
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39613-10, 15m
    easylist: 64412-64, 15m
    easyprivacy: 30791-1283, 15m
    plowe-0: 3668-872, 15m
    ublock-abuse: 76-1, 15m
    ublock-badware: 3958-109, 15m
    ublock-filters: 31175-139, 15m
    ublock-privacy: 257-1, 15m
    ublock-quick-fixes: 526-23, 15m
    ublock-unbreak: 1893-42, 15m
    urlhaus-1: 10439-0, 15m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 819 ms (selfie)
  maxAssetCacheWait: 587 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adocean.pl: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    my.ge: 1
    tbcconnect.ge: 2
    top.ge: 1
```
</details>

**Comment by okiehsch** [comment]
> Main page is loading. its not loading cars...

![image](https://user-images.githubusercontent.com/16838044/200801151-70953b84-fc0d-40d8-a2dd-8dd9d19a7fbc.png)
![image](https://user-images.githubusercontent.com/16838044/200801331-1e8a13be-c326-4c16-a66c-788e52d67009.png)

**Comment by datka1** [comment]
Some times it does load. sometimes it just breaks. i know its working with ads when ublock is disabled

**Comment by okiehsch** [comment]
Loads everytime on my end, though the pictures on some pages take a few seconds to appear.
Not much I can do,

**Comment by AntiAdvert** [comment]
> ```yaml
> switchRuleset: 
>   added: [array of 1 redacted]
> ```

Is there any rule in "My rules" that may affect that site in your browser? 
https://user-images.githubusercontent.com/117537631/200917309-5a60cd82-ec9e-41a9-8bad-b3d3282503fa.png

**Comment by datka1** [comment]
> > ```yaml
> > switchRuleset: 
> >   added: [array of 1 redacted]
> > ```
> 
> Is there any rule in "My rules" that may affect that site in your browser? https://user-images.githubusercontent.com/117537631/200917309-5a60cd82-ec9e-41a9-8bad-b3d3282503fa.png

My Rules is empty

**Comment by mapx-** [comment]
Reinstall uBO, update all filter lists, disable all other extensions, test again.
