### ISSUE TITLE
sturls.com - ads

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#15580]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://sturls.com/url/HCmc`

### Describe the issue

A lot of ads appear. They are not getting blocked by uBlockOrigin

### uBlock Origin version

1.44.4

### Browser name and version

107.XX

### Settings

All default settings.

### Notes

Wait till the page is fully loaded (captcha appears). Then you will find a lot of ads on the page.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/200777232-021f6330-3e6c-4176-9867-50052a2086a2.png)

**Comment by AntiAdvert** [comment]
`sturls.com##+js(set, blurred, false)` and maybe a `nano-stb` or `nano-sib` rule be made for non-adlinkfly-using part if there is one

**Comment by stephenhawk8054** [comment]
I can't see any ads

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/200980719-adf53f5a-3d21-49dd-addb-4af45f1605e9.png)

</details>

Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by blazesprings** [comment]
Sorry friends, my uBO was turned off for this particular website because it detected the uBO earlier. I turned it ON and now no ads appear. Thanks to everyone who helped me. Please close this issue.
