### ISSUE TITLE
bardimin.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15584]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bardimin.com/tag/iperf/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/200774967-d2ecff2d-64b2-44ef-83d7-51d88370a1c5.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/200774994-ea9db3c7-a9a1-47f0-ae67-1d10275aaf88.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 109
filterset (summary): 
  network: 110476
  cosmetic: 166864
  scriptlet: 25808
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 8154-3, 1d.22h.42m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 1d.22h.42m
    adguard-annoyance: 60742-394, 1d.22h.42m
    adguard-spyware: 36592-3058, 1d.22h.42m
    fanboy-annoyance: 82433-3844, 1d.22h.42m
    fanboy-cookiemonster: 42733-42733, 1d.22h.42m
    ublock-annoyances: 4768-211, 1d.22h.42m
  default: 
    user-filters: 6-0, never
    easylist: 64359-150, 1d.22h.42m
    easyprivacy: 30787-14012, 1d.22h.42m
    ublock-abuse: 76-0, 1d.22h.42m
    ublock-badware: 3958-107, 1d.22h.42m
    ublock-filters: 31166-596, 1d.22h.42m
    ublock-privacy: 257-47, 1d.22h.42m
    ublock-quick-fixes: 510-34, 9h.20m
    ublock-unbreak: 1891-61, 1d.22h.42m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 4 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 1066 ms (selfie)
  maxAssetCacheWait: 827 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
    media.net: 1
    quantserve.com: 1
```
</details>

**Comment by okiehsch** [comment]
Try with a default setup.

**Comment by 3xploiton3** [comment]
@realodix
