### ISSUE TITLE
apollo.nuxtjs.org: breakage

### ISSUE THREAD

**Issue by mikehaertl** [uBlockOrigin/uAssets#15583]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://apollo.nuxtjs.org/`

### Category

breakage

### Describe the issue

The website gives a 500 error when accessed with uBlock.

The console gives:
```
GET https://apollo.nuxtjs.org/_nuxt/SocialIcons-4cc53d7e.mjs net::ERR_BLOCKED_BY_CLIENT
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/675062/200773720-eb0de861-5a6e-4fa5-ac1a-2c0bf616deae.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 95487
  cosmetic: 58220
  scriptlet: 16566
  html: 0
listset (total-discarded, last updated): 
  removed: 
    DEU-0: null
    ublock-privacy: null
  added: 
    https://mirror1.malwaredomains.com/files/immortal_domains.txt: 3196-0, 695d.23h.4m
    fanboy-social: 23418-6, 6d.23h.49m
  default: 
    user-filters: 0-0, never
    easylist: 62881-54, 2d.54m
    easyprivacy: 30787-1170, 1d.1h
    plowe-0: 3669-867, 6d.23h.51m
    ublock-abuse: 76-0, 6d.23h.50m
    ublock-badware: 3958-105, 19h.55m
    ublock-filters: 31172-103, 19h.54m
    ublock-quick-fixes: 487-34, 1d.58m
    ublock-unbreak: 1891-42, 19h.53m
    urlhaus-1: 11275-0, 1d.59m
filterset (user): [empty]
trustedset: 
  added: [array of 49 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 186 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    nuxtjs.org: 1
```
</details>

**Comment by okiehsch** [comment]
It's caused by `fanboy-social`.
Add
`@@||apollo.nuxtjs.org/_nuxt/*$script,1p`
to your filter list.

**Comment by okiehsch** [comment]
@mikehaertl if you enable a list like `fanboy-social` don't be surprised if it blocks a request that is called
`https://apollo.nuxtjs.org/_nuxt/` **SocialIcons** `-4cc53d7e.mjs net::ERR_BLOCKED_BY_CLIENT`

**Comment by okiehsch** [comment]
It has been fixed in `fanboy-social`.
If you update that list , the site should load without issue.

**Comment by mikehaertl** [comment]
@okiehsch Thanks. I tried to update but the filter is still there. Do I maybe have to wait for another release of fanboy-social first? Or does it always pull from master?

![image](https://user-images.githubusercontent.com/675062/200780557-c46f032b-a67c-4dff-af27-0f2af6cae205.png)

I played around quite a bit: Click the update button (watch icon) on fanboy-social, clicked "Update all" on top, "flush cache", etc.

**Comment by okiehsch** [comment]
Hm, your right seems to take longer for that list to be "live" after a commit has taken place.
With our own lists it usually takes about 5 minutes after a commit.
For now keep the filter I mentioned above
`@@||apollo.nuxtjs.org/_nuxt/*$script,1p`
in your own filter list.

**Comment by mikehaertl** [comment]
Ok, thanks.
