### ISSUE TITLE
duden.de: detection

### ISSUE THREAD

**Issue by 10Meisterbaelle** [uBlockOrigin/uAssets#15589]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.duden.de/rechtschreibung/Shownotes`

### Category

detection

### Describe the issue

The website can detect uBlock Origin, but only on Firefox for some reason. Chrome is not affected. uBlock Origin used to be able to block this adblocker detection. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-09 at 22-07-35 Shownotes](https://user-images.githubusercontent.com/45918080/200942066-a731406e-bae6-4908-af70-5ff6cb90fa4f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91652
  cosmetic: 42290
  scriptlet: 16666
  html: 796
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31900-144, 9h.25m
    ublock-badware: 3962-0, 9h.25m
    ublock-privacy: 285-0, 9h.24m
    ublock-abuse: 76-0, 9h.24m
    ublock-unbreak: 1906-0, 9h.24m
    ublock-quick-fixes: 511-0, 9h.24m
    easylist: 64410-520, 9h.24m
    easyprivacy: 30791-1733, 9h.24m
    urlhaus-1: 10439-0, 9h.24m
    plowe-0: 3668-3, 9h.24m
    DEU-0: 6019-2, 9h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 261 ms (selfie)
  maxAssetCacheWait: 76 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    duden.de: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    yieldlove.com: 2
```
</details>

**Comment by okiehsch** [comment]
> ![image](https://user-images.githubusercontent.com/16838044/200942599-9b89e1ea-c3b9-475d-9865-08405eb4b4f8.png)

Really? If so how did you miss the exact same issue opened 9 hours ago.
https://github.com/uBlockOrigin/uAssets/issues/15586

**Comment by mapx-** [comment]
fixed 8 hours ago

https://github.com/uBlockOrigin/uAssets/commit/a7d2b72284d8a6cbd2c5bb26c8b5b758ad9869a4

update `uBlock filters`

**Comment by okiehsch** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/15586

**Comment by 10Meisterbaelle** [comment]
> > ![image](https://user-images.githubusercontent.com/16838044/200942599-9b89e1ea-c3b9-475d-9865-08405eb4b4f8.png)
> 
> 
> 
> Really? If so how did you miss the exact same issue opened 9 hours ago.
> 
> https://github.com/uBlockOrigin/uAssets/issues/15586
> 
> 

Oh oops :/ sorry it's because I didn't look at the date
