### ISSUE TITLE
mystream.la

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#1558]
### Describe the issue

`mystream.la` redirect me to `pameless.info` with `mystream.la` as an iframe.

**URL** 
* `http://www.mystream.la/external/RKUCNDYRYABS`
* `http://pameless.info/VzhaN1o2WilDZSJKNgoyI0wqEmkWHWhxf2V+LUAteVUjRC4lXTtadDtZfwUcMkAuUig5WTYSaBFqEWIZGXwDZQMWegk`

**HTML** 
https://pastebin.com/raw/ZcNCbafF (mystream)
https://pastebin.com/raw/A7GaNY6p (pameless)

**ss**

- https://i.imgur.com/BTjwpvb.gif

**Versions**

- Chromium: 64
- uBlock Origin version: v1.15.2

**Settings**

default settings

**Note**

`pameless.info` is one of the malvertising campaign domains "[RoughTed](https://blog.malwarebytes.com/cybercrime/2017/05/roughted-the-anti-ad-blocker-malvertiser/)".

**Comment by okiehsch** [comment]
Does
````
mystream.la##script:inject(abort-current-inline-script.js, decodeURI, doSecondPop)
mystream.la##script:inject(abort-on-property-write.js, Fingerprint2)
````
work for you?

**Comment by SMed79** [comment]
Yes, https://i.imgur.com/h5NgZpt.gifv

Thank you.
