### ISSUE TITLE
soft98.ir: ads

### ISSUE THREAD

**Issue by mhfr110** [uBlockOrigin/uAssets#15597]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soft98.ir/security/anti-virus/10-eset-nod32-antivirus.html`

### Category

ads

### Describe the issue

left ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 315970
  cosmetic: 217921
  scriptlet: 34308
  html: 0
listset (total-discarded, last updated): 
  added: 
    IRN-0: 2430-0, 1d.17h.4m
    adguard-annoyance: 60788-96, 2d.15h.6m
    adguard-generic: 79361-478, 2d.15h.5m
    adguard-mobile: 8232-45, 2d.15h.4m
    adguard-social: 18886-842, 2d.15h.3m
    adguard-spyware: 36597-3658, 2d.15h.2m
    adguard-spyware-url: 816-1, 1d.23h.18m
    curben-phishing: 160761-0, 1h.54m
    curben-pup: 193-1, 21h.31m
    fanboy-annoyance: 82419-4948, 1d.23h.20m
    fanboy-social: 23421-23421, 4d.15h.51m
    fanboy-thirdparty_social: 69-21, 1d.23h.19m
  default: 
    user-filters: 11-0, never
    easylist: 64414-1026, 1m
    easyprivacy: 30793-14133, 2m
    plowe-0: 3668-1038, 1h.7m
    ublock-abuse: 76-0, 1h.6m
    ublock-badware: 3958-273, 1d.23h.17m
    ublock-filters: 31172-3650, 1d.23h.15m
    ublock-privacy: 257-50, 1h.8m
    ublock-quick-fixes: 530-46, 1h.55m
    ublock-unbreak: 1893-101, 1d.23h.16m
    urlhaus-1: 11499-8, 1h.56m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2631 ms
  maxAssetCacheWait: 1518 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    kaprila.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Not fixable at the moment, see https://github.com/uBlockOrigin/uAssets/issues/14480

**Comment by JobcenterTycoon** [comment]
@MasterKia i remember you posted a addon against this a while ago. The addon can help here

**Comment by JobcenterTycoon** [comment]
Ok i heard the addon is outdated.

The best i can do at the moment is

<details>
<summary> filter </summary>

```
soft98.ir,~forum.soft98.ir##+js(ra, id, body > header + div)
soft98.ir,~forum.soft98.ir##+js(ra, id, header + div + div + div)
soft98.ir,~forum.soft98.ir##img[src*="file.soft98.ir/afrak2.gif"]:upward(1)
soft98.ir,~forum.soft98.ir##main + aside > div:has(a[href^="https://s0ft98.ir"])
soft98.ir,~forum.soft98.ir##header + div + div + div:style(background: #e8e8e8;)
soft98.ir,~forum.soft98.ir##body > header + div:style(padding: 0px !important;)
```

</details>

When a download link is not working reload one time
