### ISSUE TITLE
multitwitch.live: ads

### ISSUE THREAD

**Issue by supermjh12** [uBlockOrigin/uAssets#15599]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://multitwitch.live/`

### Category

ads

### Describe the issue

Everytime, I would hop on a streamers channel and I would instantly get ads. My biggest problem is that I don't like it because it ruins the content of the stream. If I resubscribe for a Tier 1 then I would be broke in my bank account, I don't want that either. Please help me get rid of the ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 90741
  cosmetic: 38501
  scriptlet: 16670
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64364-52, 1d.17h.32m
    easyprivacy: 30787-1170, 1d.17h.31m
    plowe-0: 3668-867, 1d.17h.30m
    ublock-abuse: 76-0, 1d.17h.28m
    ublock-badware: 3958-109, 1d.17h.26m
    ublock-filters: 31170-107, 1d.17h.24m
    ublock-privacy: 257-1, 1d.17h.23m
    ublock-quick-fixes: 523-23, 10h.22m
    ublock-unbreak: 1893-42, 1d.17h.21m
    urlhaus-1: 11744-0, 10h.21m
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1198 ms (selfie)
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 76
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 3
    fontawesome.com: 21
    gstatic.com: 2
    imrworldwide.com: 2
    scorecardresearch.com: 20
    serving-sys.com: 1
    twitchcdn.net: 22
    wizebot.tv: 2
```
</details>

**Comment by gorhill** [comment]
> - [x] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
> - [x] I did not answer truthfully to all the above checkpoints

> `no-cosmetic-filtering: true`
> `no-large-media: true`
> `no-popups: true`
> `no-remote-fonts: true`
> `no-scripting: true`

That kind of customization is not supported -- issues arising from heavily customized filters/rules are to be solved by the users.
