### ISSUE TITLE
startpage.com: detection

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#15598]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.startpage.com/sp/search?query=test&prfe=f7b1f85a67e00473919e214fd2c8a0fd080a9129ebb64757b255493ec515f65e047ab7c5f584722f4a15b01c8a9062a8be4931bbf42bcf6a4c5d957f243b49eb4e2f95d1de915ea23c512dad8aad272441`

### Category

detection

### Describe the issue

Gives a message to exclude StartPage from you adblocker

Disabling `##.ad.widget` from EasyList solved the problem.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![afbeelding](https://user-images.githubusercontent.com/80090789/201077324-fa2bd36c-59e5-4367-aa5d-75dd805fe226.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 76713
  cosmetic: 40323
  scriptlet: 16473
  html: 780
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    ublock-quick-fixes: null
  default: 
    user-filters: 1234-3, never
    ublock-filters: 31923-140, now
    ublock-privacy: 285-0, now
    ublock-unbreak: 1906-17, now
    easylist: 64465-412, now
    easyprivacy: 30793-1725, now
    plowe-0: 3668-1, now
    NLD-0: 2484-12, now
filterset (user): [array of 736 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    opera-scheme
    vivaldi-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1230 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 19 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 10
  autoUpdateDelayAfterLaunch: 60
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  allReadyAfter: 7284 ms (selfie)
  maxAssetCacheWait: 850 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    startpage.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Its fixed by `uBlock filters – Annoyances` now.
