### ISSUE TITLE
bilibili.com: ads

### ISSUE THREAD

**Issue by Waterkuiiiiii** [uBlockOrigin/uAssets#15592]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

ads

### Describe the issue

Since 1.45.0 version, uBO can't work on bilibili.com.

### Screenshot(s)

Like here I just want to block something, but it doesn't work.
<details>
<summary>Screenshot(s)</summary>

![uBO_bug](https://user-images.githubusercontent.com/82272842/200949494-b836da7b-4c95-43e2-b905-d8c462659540.gif)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Chromium: 107
filterset (summary): 
  network: 90774
  cosmetic: 38739
  scriptlet: 16675
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 298-1, never
    easylist: 64356-52, 2d.8h.56m
    easyprivacy: 30783-1170, 2d.8h.57m
    plowe-0: 3668-867, 1d.13h.42m
    ublock-abuse: 76-0, 47m
    ublock-badware: 3958-109, 9h.47m
    ublock-filters: 31159-106, 9h.46m
    ublock-privacy: 257-1, 48m
    ublock-quick-fixes: 523-23, 1h.7m
    ublock-unbreak: 1895-42, 3d.11h.18m
    urlhaus-1: 11744-0, 1h.6m
filterset (user): [array of 302 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1202 ms (selfie)
  maxAssetCacheWait: 653 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    bilibili.com: 23
    hdslb.com: 1
```
</details>

**Comment by mapx-** [comment]
I didn't understand your issue. Provide the steps  to reproduce it (and the explanation)

**Comment by dportvine** [comment]
This can only happen if you have disabled My Filters.
