### ISSUE TITLE
roblox.com: breakage

### ISSUE THREAD

**Issue by JacksonChen666** [uBlockOrigin/uAssets#15593]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.roblox.com/my/account`

### Category

breakage

### Describe the issue

the social networks section in the "Account info" settings page is hidden with ublock origin active (see figure 2. also, more precisely: a generic cosmetic filter in the fanboy annoyance and social filters).

the section of the settings is important for well, setting the social links on the profile. when that section is hidden, the settings for the profile social links is inaccessible, which could lead to confusion (which i had experienced).

([help page](https://en.help.roblox.com/hc/en-us/articles/203313660-All-About-Profiles-Blurbs-and-Profile-Customization) with image, see "How to add Social Links to an account" section which i couldn't directly link to)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="figure 1" src="https://user-images.githubusercontent.com/50755746/200957806-9b802428-aa68-48ce-b90a-379966b512f0.png">
figure 1

<img width="1680" alt="figure 2" src="https://user-images.githubusercontent.com/50755746/200957828-e131c0a8-f92c-40b4-9dea-ea89bc6c016f.png">
figure 2

<img width="1680" alt="figure 3" src="https://user-images.githubusercontent.com/50755746/200957837-0f323226-3dc5-41a8-ad86-727bc818896b.png">
figure 3

<img width="1680" alt="figure 4" src="https://user-images.githubusercontent.com/50755746/200961658-5a35e119-b131-435b-ab92-8f59f191dcb7.png">
figure 4

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 333982
  cosmetic: 218228
  scriptlet: 37340
  html: 820
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 87665-4061, 6h.33m
    adguard-mobile: 8228-8, 6h.27m
    adguard-spyware: 38381-17050, 6h.25m
    adguard-spyware-url: 817-4, 6h.28m
    adguard-annoyance: 60874-4767, 6h.24m
    adguard-social: 18928-1074, 6h.29m
    fanboy-thirdparty_social: 68-0, 6d.1h.20m
    fanboy-annoyance: 82161-66558, 8d.5h.34m
    fanboy-cookiemonster: 42695-163, 5d.11h.51m
    fanboy-social: 23414-28, 10h.38m
    ublock-annoyances: 4792-4, 6h.30m
    dpollock-0: 11389-521, 10d.19h.24m
    curben-phishing: 162397-9, 10h.35m
    curben-pup: 193-0, 10h.37m
  default: 
    user-filters: 8-0, never
    ublock-filters: 31918-72, 6h.32m
    ublock-badware: 3962-0, 6h.26m
    ublock-privacy: 288-0, 8d.13h.46m
    ublock-abuse: 76-0, 9d.23h.16m
    ublock-unbreak: 1906-2, 6h.31m
    easylist: 62871-1594, 4d.5h.34m
    easyprivacy: 30787-1811, 2h.4m
    urlhaus-1: 10439-0, 10h.34m
    plowe-0: 3668-140, 2d.25m
    ublock-quick-fixes: 522-0, 10h.36m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 153 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 178 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 599 ms (selfie)
  maxAssetCacheWait: 1206 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    roblox.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's caused by the filter

```adb
###social-networks
```

in your added filter lists `Fanboy’s Annoyance` and `Fanboy’s Social`.

Add

```adb
roblox.com#@##social-networks
```

@ryanbr

**Comment by JacksonChen666** [comment]
@stephenhawk8054

added mentioned line to "my filters", twitter section is still missing but the rest is there.

<details><summary>screenshots</summary>

![Screen Shot 2022-11-10 at 2 54 12](https://user-images.githubusercontent.com/50755746/200982180-597d5bef-79bb-429c-9f50-456e2d8398e6.png)

</details>

**Comment by stephenhawk8054** [comment]
It's because of `##.twitter-container` in `Fanboy’s Annoyance` and `Fanboy’s Social` lists. Please report this issue at https://github.com/easylist/easylist/

You are enabling all of the filter lists (even enable `AdGuard Mobile Ads` on desktop?). Test with only default settings and check one by one which list is causing the issue and report at the corresponding maintainers.

**Comment by stephenhawk8054** [comment]
@ryanbr There's still `##.twitter-container` hiding twitter section
