### ISSUE TITLE
cedaron.visualstudio.com: breakage

### ISSUE THREAD

**Issue by jhudsoncedaron** [uBlockOrigin/uAssets#15595]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cedaron.visualstudio.com/CedaronMedical/_git/CardiacCare/pullrequest/XXXXX?_a=files&path=%2Fsrc%2FCedaron.Interface.Declarations%2FTrackingData.cs`

### Category

breakage

### Describe the issue

Apologies you will not be able to open the URL and verify.

This site should have ublockorigin active because of some low-level shenagains; however one of the 6 matching rules is not quite right. It's locking onto "TrackingData.cs" causing malfunction with that single filename in an ajax call. I haven't been able to determine which rule is at fault.

TrackingData.cs has nothing to do with tracking users; it tracks a system-to-system message in RAM as it passes through the layers of the application.

![image](https://user-images.githubusercontent.com/17086870/200973143-47950ded-351e-4490-8ede-da3da68af426.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 106
filterset (summary): 
  network: 90747
  cosmetic: 38481
  scriptlet: 16645
  html: 795
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31913-55, 2d.1h.58m
    ublock-badware: 3962-0, 2d.2h
    ublock-privacy: 288-0, 7d.2h.19m
    ublock-abuse: 76-0, 7d.2h.18m
    ublock-unbreak: 1908-0, 2d.1h.59m
    ublock-quick-fixes: 475-0, 5h.30m
    easylist: 64358-608, 3d.2h.3m
    easyprivacy: 30807-1707, 4d.2h.6m
    urlhaus-1: 11744-0, 5h.29m
    plowe-0: 3669-3, 7d.2h.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1487 ms (selfie)
  maxAssetCacheWait: 117 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    visualstudio.com: 4
    azure.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like it's caused by `/TrackingData.` in EasyPrivacy

Can you check if adding this to ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) works? (click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page)

```adb
@@||cedaron.visualstudio.com/*TrackingData.cs$1p
```

**Comment by jhudsoncedaron** [comment]
Placing that rule was indeed an effective fix.

Sorry about the delay. Yesterday was nutty at work.

**Comment by mapx-** [comment]
add to unbreak list, I'll notify EasyPrivacy maintainer too
