### ISSUE TITLE
discounthero.org: popups

### ISSUE THREAD

**Issue by igorshin** [uBlockOrigin/uAssets#15590]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://discounthero.org/us`

### Category

popups

### Describe the issue

A new Chrome tab showing `discounthero.org` home page is opened "magically" several times a day.  I am using MacOS Monterey v 12.6. I ran Avast, but it did not find any adware. I can't figure out where the popup originates. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89282
  cosmetic: 38465
  scriptlet: 16642
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62871-52, 3d.23h.55m
    easyprivacy: 30779-1170, 3d.23h.56m
    plowe-0: 3667-865, 3d.23h.57m
    ublock-abuse: 76-0, 4d
    ublock-badware: 3953-105, 3d.23h.54m
    ublock-filters: 31167-103, 3d.23h.53m
    ublock-privacy: 257-1, 3d.23h.59m
    ublock-quick-fixes: 510-34, 24m
    ublock-unbreak: 1895-42, 3d.23h.52m
    urlhaus-1: 11744-0, 25m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2207 ms (selfie)
  maxAssetCacheWait: 693 ms
popupPanel: 
  blocked: 1
  no-large-media: true
  no-popups: true
  no-scripting: true
  blockedDetails: 
    discounthero.org: 1
```
</details>

**Comment by mapx-** [comment]
Scan online for virus / malware using:

https://www.trendmicro.com/en_us/forHome/products/housecall.html

**Comment by krystian3w** [comment]
So Sophos no longer help?

https://www.sophos.com/en-us/free-tools/virus-removal-tool

**Comment by okiehsch** [comment]
There is nothing that we can do here.
If you need help with malware removal you should open a thread in a dedicated malware removal forum.
`https://www.bleepingcomputer.com/forums/f/22/virus-trojan-spyware-and-malware-removal-help/`
for example.

**Comment by krystian3w** [comment]
This GitHub repository support clean PC:

https://github.com/dragokas/hijackthis/labels/Cure%20PC
