### ISSUE TITLE
Unsplash+ Imagees

### ISSUE THREAD

**Issue by hofq** [uBlockOrigin/uAssets#15591]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://unsplash.com/`

### Describe the issue

Unsplash+, a paid service by unsplash, images are appearing

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/54744977/200949462-96b123f9-4810-483b-9eb1-c012504327a9.png)
![grafik](https://user-images.githubusercontent.com/54744977/200949506-8813e22c-cf6f-4b93-bf7a-2ca4e2de0484.png)

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 106.0.5

### Settings

- `||plus.unsplash.com/premium_photo-*`
Images get blury, but i can't remove them completely

**Comment by stephenhawk8054** [comment]
This?

```adb
unsplash.com##img[srcset^="https://plus.unsplash.com"]:upward(figure):remove()
```

**Comment by krystian3w** [comment]
This repairs gaps?

**Comment by mapx-** [comment]
Unsplash+ is self-promo, @stephenhawk8054 is working, closing here

**Comment by krystian3w** [comment]
Not working after open free photo and few times click right arrow.
