### ISSUE TITLE
Option for cookie consent to be excluded from block list

### ISSUE THREAD

**Issue by metablaster** [uBlockOrigin/uAssets#15603]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`turnbasedlovers.com`
`www.tenforums.com`

### Describe the issue

Many websites provide a cookie consent dialog where a user can choose which cookies to allow and adjust privacy options per domain.

uBlock static filters work in such a way where those consent dialogs are blocked, on some sites I'm presented with cookie consent but on most sites consent is blocked.

The issue is that those cookie consent dialogs aren't always something which one doesn't want to see, I'm one of those who want to opt in and adjust cookie settings per domain, however that's impossible without disabling almost all static filters which is not an option since that's same as disabling uBlock origin all togethter.

Thus I suggest that uBlock provides an option which would let ignore static filters when it come to blocking cookie consent on domains.
I suppose this has nothing to do with static filters but rather about how uBlock origin uses and applies filters, it certainly doesn't handle cookie consent separately.

### Screenshot(s)

Cookie consent dialog example:

 ![Image](https://i.imgur.com/uEbOhAI.png)

My settings:
![Image](https://i.imgur.com/a5pZbSd.png)

### uBlock Origin version

1.45.0

### Browser name and version

MS-Edge 107.0.1418.35 (Official build) (64-bit)

### Settings

Enabled all AdBlock static filters
Enabled all privacy and malware static filters
Enabled "Peter Lowe’s Ad and tracking server list" static filter

Other settings are displayed in screenshot.

None of the advanced user settings have been modified.

### Notes

`turnbasedlovers.com` site above is one example which you can test.
Default uBlock static filter which will reproduce the problem is called "uBlock filters" under "Built-in" group, if enabled cookie consent will be blocked.

**Comment by metablaster** [comment]
I have just reset uBlock in firefox to default and tested as you said, this works for turnbasedlovers.com site.
However it doesn't work for www.tenforums.com

The culprit is default "uBlock filters" under "Built-in" group as I described.
can you test it to confirm?

**Comment by Yuki2718** [comment]
That is because the site relies on `fundingchoicesmessages.google.com` which is also used to display anti-adblock to show cookie consent. Unblocking this means user will see so-called Google Funding Choice anti-adblock everywhere, obviously not an option.
