### ISSUE TITLE
player.pl: detection

### ISSUE THREAD

**Issue by Naala098** [uBlockOrigin/uAssets#15609]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://player.pl/programy-online/kuba-wojewodzki-odcinki,455/odcinek-7,S05E07,27578`

### Category

detection

### Describe the issue

the site detects the blocker and asks you to disable it, can't watch anything

a few days ago everything worked fine, the site had to be updated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Przechwytywanie](https://user-images.githubusercontent.com/117939042/201175455-53b1bd10-a53a-4ef2-8c18-dd5376352a03.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 92105
  cosmetic: 45947
  scriptlet: 16875
  html: 806
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31900-93, 24m
    ublock-badware: 3972-0, 23m
    ublock-privacy: 286-0, 22m
    ublock-abuse: 76-0, 21m
    ublock-unbreak: 1906-0, 20m
    ublock-quick-fixes: 546-0, 19m
    easylist: 64508-632, 18m
    easyprivacy: 30791-1709, 17m
    urlhaus-1: 11582-0, 16m
    plowe-0: 3670-3, 15m
    POL-0: 7855-25, 29m
    POL-2: 1279-12, 29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2207 ms
  maxAssetCacheWait: 290 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adform.net: 1
    adocean.pl: 3
    adpone.com: 1
    cdntvn.pl: 2
    creativecdn.com: 1
    criteo.com: 1
    criteo.net: 1
    googletagmanager.com: 1
    litix.io: 3
    newrelic.com: 1
    smartadserver.com: 1
```
</details>

**Comment by Naala098** [comment]
everything is up to date.
I think this site does not contain free material anymore

so far there have been no problems with it.

**Comment by mapx-** [comment]
check if your uBO is exactly [1.45.1b1](https://github.com/gorhill/uBlock/releases/tag/1.45.1b1)

**Comment by Naala098** [comment]
yes i have exactly this version
unfortunately the materials are still blocked
ublock shows 265 ads on this page

**Comment by mapx-** [comment]
without an account we cannot investigate further.

**Comment by Naala098** [comment]
how can i give you an account?
private message?

**Comment by AntiAdvert** [comment]
Could you take a screenshot with blocked elements in [uBlock Origin's logger](https://github.com/gorhill/ublock/wiki/The-logger)?
![image](https://user-images.githubusercontent.com/117537631/201189830-0afd2249-d862-46e7-a070-7e7d72b9e41c.png)
![image](https://user-images.githubusercontent.com/117537631/201189994-1408b65a-14cf-4e2c-8e9d-f5f1909f5689.png)

**Comment by AntiAdvert** [comment]
> how can i give you an account? private message?

`https://www.reddit.com/r/ublockorigin` - i think you can message uBO subreddit mods if you have an account

**Comment by mapx-** [comment]
@Naala098 send it to this reddit user
https://www.reddit.com/user/ajaxmix

**Comment by Naala098** [comment]
> Could you take a screenshot with blocked elements in [uBlock Origin's logger](https://github.com/gorhill/ublock/wiki/The-logger)?
> Screenshots:

![Przechwytywanie](https://user-images.githubusercontent.com/117939042/201191276-61b2cb5e-4baa-4f18-807e-4547aad13b00.JPG)

**Comment by mapx-** [comment]
try whitelisting advert + adverts

**Comment by mapx-** [comment]
yeah, the first one has:

`ADBLOCK_DETECTED=false;window.adBlockPresent=false;var ADBL_TRAFFIC=0;`

**Comment by Naala098** [comment]
> @Naala098 send it to this reddit user https://www.reddit.com/user/ajaxmix

unlock the ability to receive messages

**Comment by mapx-** [comment]
did you try the filter above ?

I didn't lock the chat ..

**Comment by Naala098** [comment]
I have information that your chat is blocked

I didn't apply the filter because I can't do it, I don't want to make the situation worse, sorry.

**Comment by Naala098** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/117939042/201195274-e7ef4415-5469-48a6-92f1-f0a84b1f35d7.JPG)

**Comment by mapx-** [comment]
> I can't do it

Why ?! add it to "my filters" and test again

**Comment by Naala098** [comment]
https://s.reddit.com/c/19z6l97amax5h

**Comment by mapx-** [comment]
your name on reddit ?

**Comment by Naala098** [comment]
same as Naala098 here

**Comment by mapx-** [comment]
I already sent a message to you, do you get it ?

**Comment by Naala098** [comment]
:)

**Comment by mapx-** [comment]
test these filters

```
@@||cdntvn.pl^$script,domain=player.pl
player.pl#@#+js(json-prune, movie.advertising.ad_server)
```

**Comment by Naala098** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/117939042/201207949-747bbef8-1d0e-49c6-8a3a-1a57870ee361.JPG)
![Przechwytywanie2](https://user-images.githubusercontent.com/117939042/201207987-bc4b366a-5944-4545-8acd-ceefb373cecf.JPG)

**Comment by swiezaczek** [comment]
still doesnt work

**Comment by mapx-** [comment]
@swiezaczek you didn't enable the 2 POL lists.
Use ONLY the default setup in uBO + 2 POL lists, no other list, no other blocking extension

**Comment by swiezaczek** [comment]
ok. it works with POL lists enabled. Thanks

**Comment by Divine0071** [comment]
Unfortunately uBO is detected by player.pl again since last night. Using default settings + 2 POL lists. Latest b3 version installed. Tested on FF and Chrome; same issue.

**Comment by krystian3w** [comment]
Still exist free content like:

`https://player.pl/seriale-online/skazana-odcinki,31908` with section ads in 1/5 and 4/5 of time:

![obraz](https://user-images.githubusercontent.com/35370833/202563961-86454187-efdd-423c-8b93-1f32ec835ecf.png)
