### ISSUE TITLE
trakt.tv: ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#15607]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://trakt.tv/dashboard`

### Category

ads

### Describe the issue

Banner leftover after latest ubo update

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 260211
  cosmetic: 113100
  scriptlet: 21635
  html: 818
listset (total-discarded, last-updated): 
  added: 
    block-lan: 44-0, 1d.1h.25m
    curben-phishing: 162178-10, 1h.1m
    fanboy-annoyance: 82526-361, 1d.1h.25m
    ublock-annoyances: 4787-7, 1d.1h.25m
  default: 
    user-filters: 14-0, never
    ublock-filters: 31901-33, 1d.1h.25m
    ublock-badware: 3962-0, 1d.1h.25m
    ublock-privacy: 285-0, 1d.1h.25m
    ublock-abuse: 76-0, 1d.1h.25m
    ublock-unbreak: 1906-0, 1d.1h.25m
    ublock-quick-fixes: 546-23, 1h.3m
    easylist: 64411-249, 1d.1h.25m
    easyprivacy: 30791-1723, 1d.1h.25m
    urlhaus-1: 11582-0, 1h.2m
    plowe-0: 3668-346, 1d.1h.25m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4802 ms (selfie)
  maxAssetCacheWait: 2216 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    intergient.com: 1
    stripe.com: 1
```
</details>

**Comment by Morgan-le-Fay** [comment]
https://user-images.githubusercontent.com/104303586/201158801-a4bff418-89da-46be-bbb9-4dcae95a7626.png

**Comment by mapx-** [comment]
- update all filter lists
- if still does not help update uBO to the last release (1.45.1b1)

https://github.com/gorhill/uBlock/releases/tag/1.45.1b1

(Firefox: Click [uBlock0_1.45.1b1.firefox.signed.xpi](https://github.com/gorhill/uBlock/releases/download/1.45.1b1/uBlock0_1.45.1b1.firefox.signed.xpi))
