### ISSUE TITLE
hardmob.com.br: breakage

### ISSUE THREAD

**Issue by andperoty** [uBlockOrigin/uAssets#15600]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hardmob.com.br/threads/794759-RAPIDO-HK-Aura-STUDIO-3-R-104900`

### Category

breakage

### Describe the issue

block links tha go outside the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92039
  cosmetic: 41421
  scriptlet: 16696
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64359-52, 3d.1h.9m
    easyprivacy: 30787-1170, 3d.1h.8m
    plowe-0: 3668-867, 3d.1h.11m
    spa-1: 4828-70, 3d.1h.7m
    ublock-abuse: 76-0, 3d.1h.13m
    ublock-badware: 3958-109, 3d.1h.6m
    ublock-filters: 31190-139, 3d.1h.5m
    ublock-privacy: 257-1, 3d.1h.12m
    ublock-unbreak: 1895-43, 3d.1h.4m
    urlhaus-1: 11744-0, 22h.13m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 35 redacted]
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 270 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 15
  no-popups: true
  blockedDetails: 
    hardmob.com.br: 3
    amazonaws.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gstatic.com: 4
    linksynergy.com: 3
    twitter.com: 1
    zenaps.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||hardmob.com.br/clientscript/init.js$script
```

@Yuki2718 I think it can be fixed in `Adguard Spanish/Portugese`
