### ISSUE TITLE
blocked.syd-1.linewize.net: [unknown]

### ISSUE THREAD

**Issue by BruceNor** [uBlockOrigin/uAssets#15613]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blocked.syd-1.linewize.net/blocked?url=shrekshotel.games&deviceid=PHYS-SMIC-US-0000-1262&user=nordabru000&rule=QWRkaXRpb25hbCBCbG9ja2VkIENhdGVnb3JpZXM=&ruleid=8f600788-4e8b-4cf8-81c5-b87635cf42ad&path=&method=rule_match&cid=bm9yZGFicnUwMDAxNjY4MTA1MDE5NjY0`

### Category

[unknown]

### Describe the issue

let me innnn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 102
filterset (summary): 
  network: 90746
  cosmetic: 38493
  scriptlet: 16657
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    easylist: 64364-52, 1d.22h.25m
    easyprivacy: 30791-1170, 1h.19m
    plowe-0: 3668-867, 1d.22h.26m
    ublock-abuse: 76-0, 1h.21m
    ublock-badware: 3958-109, 2d.19h.28m
    ublock-filters: 31172-108, 2d.19h.29m
    ublock-privacy: 258-1, 1h.20m
    ublock-quick-fixes: 510-34, 1d.6m
    ublock-unbreak: 1893-42, 2d.19h.30m
    urlhaus-1: 11744-0, 1d.9m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 419 ms (selfie)
  maxAssetCacheWait: 423 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    browser-intake-datadoghq.com: 3
```
</details>

**Comment by AntiAdvert** [comment]
`https://www.linewize.com/`
