### ISSUE TITLE
wepc.com: detection

### ISSUE THREAD

**Issue by Betablockr** [uBlockOrigin/uAssets#15619]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wepc.com/news/lg-c1-lg-c2-early-black-friday-deal-2022/`

### Category

detection

### Describe the issue

An ad-blocker detection tool branded Admiral covers about 70% of the screen and asks to disable the ad blocker. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium Mobile: 107
filterset (summary): 
  network: 86043
  cosmetic: 27666
  scriptlet: 17695
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8176-27, 7m
    easylist: 64422-17233, 4m
    easyprivacy: 30793-1182, 3m
    plowe-0: 3670-953, 2m
    ublock-abuse: 76-0, never
    ublock-badware: 4232-113, never
    ublock-filters: 32615-484, never
    ublock-privacy: 231-4, never
    ublock-quick-fixes: 389-37, never
    ublock-unbreak: 1863-44, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 484 ms
  maxAssetCacheWait: 218 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    adsafeprotected.com: 4
    adthrive.com: 2
    advertising.com: 2
    connatix.com: 2
    getnitropack.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    newrelic.com: 1
    videoplayerhub.com: 1
```
</details>

**Comment by mapx-** [comment]
@pgl 

admir.al crap
`||vengefulgrass.com^`

**Comment by pgl** [comment]
@mapx- Added, thanks!
