### ISSUE TITLE
account.scholastic.com: breakage

### ISSUE THREAD

**Issue by boric** [uBlockOrigin/uAssets#15612]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://account.scholastic.com/my-scholastic/profile/create-ewallet.html?sUCN=600167702&fairID=5412598`

### Category

breakage

### Describe the issue

I click on "Create eWallet" and a modal comes up on the page. I enter my username and password and press the button. It just keeps spinning forever. The JavaScript for completing the authentication is broken because resources from other domains were blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 90534
  cosmetic: 38507
  scriptlet: 16664
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64422-52, 16h.18m
    easyprivacy: 30791-1170, 16h.17m
    plowe-0: 3668-867, 16h.16m
    ublock-abuse: 76-0, 16h.14m
    ublock-badware: 3968-109, 16h.12m
    ublock-filters: 31176-108, 16h.11m
    ublock-privacy: 257-1, 16h.10m
    ublock-quick-fixes: 496-34, 16h.9m
    ublock-unbreak: 1893-42, 16h.8m
    urlhaus-1: 11499-0, 16h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 102 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    adobedtm.com: 2
    datadoghq-browser-agent.com: 1
    demdex.net: 1
    mouseflow.com: 1
    newrelic.com: 1
    sas.com: 1
```
</details>

**Comment by mapx-** [comment]
If you can provide an account it would be easier.

If not, open the uBO's logger, reproduce again the issue, go back in the logger and post here all the blocked requests you see there
