### ISSUE TITLE
player.pl: detection

### ISSUE THREAD

**Issue by Divine0071** [uBlockOrigin/uAssets#15618]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://player.pl/`

### Category

detection

### Describe the issue

Since two days uBO has been detected when starting watching any video on the player.pl website. For example: https://player.pl/seriale-online/ukryta-prawda-odcinki,521/odcinek-1412,S16E1412,242802

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 329734
  cosmetic: 172177
  scriptlet: 37656
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-136, 4m
    https://winhelp2002.mvps.org/hosts.txt: 8730-2, 4m
    POL-0: 7860-131, 5m
    POL-2: 1276-18, 5m
    adguard-annoyance: 60917-1670, 5m
    adguard-generic: 65631-1112, 5m
    adguard-mobile: 8176-118, 5m
    adguard-social: 18938-1953, 5m
    adguard-spyware: 38390-4488, 5m
    adguard-spyware-url: 824-1, 5m
    block-lan: 44-0, 5m
    curben-phishing: 162178-1, 5m
    curben-pup: 193-1, 5m
    dpollock-0: 11390-1504, 5m
    fanboy-annoyance: 82526-37986, 5m
    fanboy-cookiemonster: 42835-42835, 4m
    fanboy-social: 23417-23410, 4m
    fanboy-thirdparty_social: 68-21, 4m
    ublock-annoyances: 4779-238, 4m
  default: 
    user-filters: 0-0, never
    easylist: 64510-18319, 5m
    easyprivacy: 30793-14296, 5m
    plowe-0: 3670-1540, 4m
    ublock-abuse: 76-0, 4m
    ublock-badware: 3968-254, 4m
    ublock-filters: 31184-3884, 4m
    ublock-privacy: 258-50, 4m
    ublock-quick-fixes: 539-35, 4m
    ublock-unbreak: 1893-101, 4m
    urlhaus-1: 11582-9, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 638 ms (selfie)
  maxAssetCacheWait: 1213 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    adform.net: 1
    adocean.pl: 1
    adpone.com: 1
    cdntvn.pl: 2
    cookielaw.org: 1
    creativecdn.com: 1
    criteo.com: 1
    criteo.net: 1
    litix.io: 8
    newrelic.com: 1
    smartadserver.com: 1
    tvn.pl: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/15609

update now all filter lists, use uBO default settings / filter lists, test again
