### ISSUE TITLE
samehadaku.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1562]
URL(s) where the issue occurs

`https://www.samehadaku.tv/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
ads
`https://samehadaku.vip/nanatsu-no-taizai-fundo-no-shinpan-episode-1/`
