### ISSUE TITLE
shahid4u.site

### ISSUE THREAD

**Issue by ijy7** [uBlockOrigin/uAssets#15621]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

shahid4u.site
shahed4u.report
shaheed4u.beauty
shahidforu.co

### Describe the issue

Random popups are opened.

### uBlock Origin version

1.44.4

### Browser name and version

Chrome 107

### Settings

No changes.

### Notes

tld is constantly changing.

**Comment by mapx-** [comment]
I get no popup. @ghajini can you reproduce the issue ?

**Comment by ghajini** [comment]
yeah i can't reproduce popup on main site
there are 3p frames
`shahed4u.vip/مسلسل-queen-sugar-الموسم-السابع-الحلقة-10-العاشرة-مترجمة/watch/`

filter
`linkbox.to##+js(aost, document.createElement, computed, 1)`

letme surf others
