### ISSUE TITLE
zcool.com.cn: nuisance

### ISSUE THREAD

**Issue by GatoNaranja** [uBlockOrigin/uAssets#15624]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zcool.com.cn/work/ZNTA2NDY1ODQ=.html`

### Category

nuisance

### Describe the issue

Is there anything I can do to block the overlay? I think it is inside `static.zcool.cn/_next/static/chunks/8984-641df1ca7efa7c14cd15.js`. If I block it, the page, the images gets breakage and the scrollbar disappears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/76199161/201272499-068389f6-144c-4b03-97f7-c6483af777c6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 107788
  cosmetic: 48708
  scriptlet: 16806
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 45-1, never
    CHN-0: 28587-85, 2h.2m
    easylist: 63345-87, 5d.21h.30m
    easyprivacy: 30849-1193, 5d.21h.31m
    plowe-0: 3669-867, 7d.16h.14m
    ublock-abuse: 76-0, 8d.16h.41m
    ublock-badware: 3968-105, 13h.13m
    ublock-filters: 31181-120, 13h.12m
    ublock-privacy: 260-1, 8d.16h.40m
    ublock-quick-fixes: 530-23, 13h.8m
    ublock-unbreak: 1893-43, 13h.10m
    urlhaus-1: 11582-0, 13h.9m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 291 ms (selfie)
  maxAssetCacheWait: 210 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    zcool.com.cn: 4
```
</details>

**Comment by mapx-** [comment]
test

```
zcool.com.cn##.modal__body
zcool.com.cn##.ReactModal__Overlay--after-open.ReactModal__Overlay
zcool.com.cn##html:style(overflow: auto !important;)
```

**Comment by GatoNaranja** [comment]
@mapx- It works. Thank you.
