### ISSUE TITLE
golem.de: breakage

### ISSUE THREAD

**Issue by deeeluxe** [uBlockOrigin/uAssets#15620]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.golem.de/`

### Category

breakage

### Describe the issue

with uBlock enabled www.golem.de won't show most of it's news articles besides the first one and a lot of advertisements 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://u.pcloud.link/publink/show?code=XZmGUBVZObAGPyBizdBaE9gI4e1mlHXxA5OV

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 143816
  cosmetic: 81294
  scriptlet: 29566
  html: 781
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 79354-5167, 3d.9h.54m
    adguard-mobile: 8176-154, 22m
    adguard-spyware: 38390-16237, 23m
    adguard-spyware-url: 824-4, 20m
    block-lan: 44-0, 23d.11h.49m
    DEU-0: 6020-2, 16h.25m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31926-56, 24m
    ublock-badware: 3962-0, 21m
    ublock-privacy: 285-0, 10h.1m
    ublock-abuse: 76-0, 10h
    ublock-unbreak: 1903-0, 3d.13h.55m
    easylist: 62879-778, 4d.4h.58m
    easyprivacy: 30782-1726, 4d.12m
    urlhaus-1: 11499-0, 16h.24m
    plowe-0: 3669-3, 7d.15h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 399 ms (selfie)
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    golem.de: 14
    googlesyndication.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    stroeerdigitalgroup.de: 2
```
</details>

**Comment by mapx-** [comment]
update uBO to the last release

Firefox: Click [uBlock0_1.45.1b1.firefox.signed.xpi](https://github.com/gorhill/uBlock/releases/download/1.45.1b1/uBlock0_1.45.1b1.firefox.signed.xpi)
