### ISSUE TITLE
6play.fr: detection

### ISSUE THREAD

**Issue by gomorrhe** [uBlockOrigin/uAssets#15628]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.6play.fr/`

### Category

detection

### Describe the issue

Can't watch live stream, can't see all the pages (replay and all things)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://www.6play.fr/

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 111319
  cosmetic: 47421
  scriptlet: 16752
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30828-18, 15h.36m
    easylist: 64358-80, 4d.4h.18m
    easyprivacy: 30787-1556, 4d.4h.17m
    plowe-0: 3669-883, 12d.20h.36m
    ublock-abuse: 76-1, 19h.40m
    ublock-badware: 3968-120, 15h.35m
    ublock-filters: 31184-210, 15h.34m
    ublock-privacy: 258-1, 19h.39m
    ublock-quick-fixes: 540-23, 19h.37m
    ublock-unbreak: 1893-43, 15h.33m
    urlhaus-1: 11582-0, 19h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 105 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 49481 ms (selfie)
  maxAssetCacheWait: 909 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    estat.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    m6web.fr: 13
    newrelic.com: 1
    outbrain.com: 1
    sddan.com: 2
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
No issue here: clicking "voir video" => playing correctly.
Some other specific link ?!

**Comment by gomorrhe** [comment]
Issue is not reading video, it is all the others live or replays which are blocked.

here is normal screen of the same page with Ublock disabled : 

https://ibb.co/10dGk0V

**Comment by gomorrhe** [comment]
Same page with Ublock running : https://ibb.co/8df4GtM

**Comment by mapx-** [comment]
test this filter

`@@||partner-api.sddan.com/api/v1/public/partner/$xhr,domain=6play.fr`

**Comment by gomorrhe** [comment]
Filter is working, thx a lot for efficiency ;)
