### ISSUE TITLE
[nsfw] voiranime.com: detection

### ISSUE THREAD

**Issue by alexoss03** [uBlockOrigin/uAssets#15638]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://voiranime.com/anime/boku-no-hero-academia-4-vf/boku-no-hero-academia-saison-4-12-vf/`

### Category

detection

### Describe the issue

The videos load forever so I guess it's because ublock is detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 109220
  cosmetic: 47233
  scriptlet: 16653
  html: 792
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31834-153, never
    ublock-badware: 3947-0, never
    ublock-privacy: 288-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1886-0, never
    ublock-quick-fixes: 430-0, never
    easylist: 62416-169, never
    easyprivacy: 30822-1722, never
    urlhaus-1: 11291-0, never
    plowe-0: 3671-345, never
    FRA-0: 30913-570, never
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1265 ms
  maxAssetCacheWait: 4 ms
popupPanel: 
  blocked: 64
  no-cosmetic-filtering: true
  blockedDetails: 
    voiranime.com: 50
    adschill.com: 2
    adskeeper.co.uk: 1
    bidgear.com: 3
    deformconversionorthodox.com: 1
    exdynsrv.com: 2
    google.com: 3
    googletagmanager.com: 1
    spolecznosci.net: 1
```
</details>

**Comment by okiehsch** [comment]
Caused by 
`*$xhr,3p,domain=voe.sx`
in the regional french list.
Add
`*$xhr,3p,domain=voe.sx,badfilter`
to your filter list.

**Comment by Yuki2718** [comment]
@smed79
