### ISSUE TITLE
"Youtube on TV" (Smart TVs and consoles) => ads

### ISSUE THREAD

**Issue by DexFolf** [uBlockOrigin/uAssets#15632]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://youtube.com/tv`

### Describe the issue

The filters provided don't seem to block ads on "Youtube on TV", the web version of the youtube app you'd find on Smart TVs and consoles. This page used to be accessible and ad-free with uBlock until Google decided to "discontinue" it around late 2019. To access nowadays, you have to set your user agent to a smart TV or console, such as 

`Mozilla/5.0 (X11; Linux x86_64; Xbox; Xbox One)`

Upon accessing the site today, there will be banner ads and sometimes pre-roll ads. It feels like the obscurity of the webapp has caused filters to never be updated and thus ads have returned.

### Screenshot(s)

https://user-images.githubusercontent.com/117560415/201413947-ac8b6af9-7bf5-4720-b726-a7a5653fdf87.png
https://user-images.githubusercontent.com/117560415/201414614-adce2844-cef6-4a7d-9df8-2d9f729b1a9b.png

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91808
  cosmetic: 38572
  scriptlet: 16694
  html: 796
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31948-47, now
    ublock-badware: 3972-0, now
    ublock-privacy: 286-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1908-1, now
    ublock-quick-fixes: 545-0, now
    easylist: 64645-612, now
    easyprivacy: 30795-1709, now
    urlhaus-1: 12558-0, now
    plowe-0: 3670-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2225 ms
  maxAssetCacheWait: 290 ms
```
</details>

**Comment by AntiAdvert** [comment]
i don't know how to access that web page, or if it is possible
<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/117537631/201415868-2e43722e-eeb3-4799-a761-f1a4c906bac3.png)

</details>

**Comment by DexFolf** [comment]
> i don't know how to access that web page, or if it is possible
> screenshot
> 
> ![image](https://user-images.githubusercontent.com/117537631/201415868-2e43722e-eeb3-4799-a761-f1a4c906bac3.png)

Please read the post clearly.

**Comment by mapx-** [comment]
@DexFolf Try installing the last version, force update all filter lists, test again
https://github.com/gorhill/uBlock/releases/tag/1.45.2

**Comment by AntiAdvert** [comment]
@ryanbr @Khrin

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/117537631/201417673-8b751c54-eea0-4133-b32d-4aa7f19eba46.png)

</details>

**Comment by DexFolf** [comment]
@mapx- same issue on latest version with latest filters

**Comment by AntiAdvert** [comment]
`www.youtube.com##[style="width: 22rem; display: inline-block; margin-right: 1.5rem; vertical-align: top;"]:has(.ytlr-metadata-badge-renderer--ad)
`

**Comment by AntiAdvert** [comment]
> but banner ads and (presumably) video ads remain.

maybe there's an issue with the build of uBO
https://github.com/uBlockOrigin/uAssets/issues/15632#issuecomment-1312118475

**Comment by mapx-** [comment]
test

`youtube.com##.ytlr-horizontal-list-renderer__items > .yt-virtual-list__container > .yt-virtual-list__item--visible.yt-virtual-list__item--selected.yt-virtual-list__item:has-text(Ad)`

- if you still see (normal) ads explain where / how to find them
- for video ads see https://github.com/uBlockOrigin/uAssets/issues/7636
