### ISSUE TITLE
ici.tou.tv: breakage

### ISSUE THREAD

**Issue by e46hgbcvbe45** [uBlockOrigin/uAssets#15635]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ici.tou.tv/infoman/S23E01?lectureauto=1`

### Category

breakage

### Describe the issue

video doesn't start, disabled ublock and it started

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91768
  cosmetic: 38571
  scriptlet: 16693
  html: 796
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31946-46, 3h.36m
    ublock-badware: 3972-0, 3h.35m
    ublock-privacy: 286-0, 11h.40m
    ublock-abuse: 76-0, 11h.41m
    ublock-unbreak: 1908-1, 3h.37m
    easylist: 64599-612, 3h.39m
    easyprivacy: 30795-1708, 3h.38m
    plowe-0: 3671-3, 7d.25m
    urlhaus-1: 12558-0, 14m
    ublock-quick-fixes: 548-0, 13m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 143 ms
popupPanel: 
  blocked: 57
  blockedDetails: 
    2o7.net: 2
    casalemedia.com: 2
    demdex.net: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    indexww.com: 2
    omtrdc.net: 29
    radio-canada.ca: 3
    scorecardresearch.com: 15
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check if adding this filter works?

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=ici.tou.tv
```

Add in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click Apply changes, go back to the website and press Ctrl + F5 to reload the page.

**Comment by e46hgbcvbe45** [comment]
yes that worked!

**Comment by stephenhawk8054** [comment]
I think this filter is enough, no need to make exception

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect-rule,domain=ici.tou.tv
```

**Comment by gorhill** [comment]
The generic redirect rule was removed, so I removed the filter filter above. However I noticed the player does not play right away when clicking the play button, one has to click again in the player with the spinning wheel for the video to start. Given this I added an exception filter, as I believe most people are unlikely to understand you have to click again in the player to make it start.
