### ISSUE TITLE
cq.ru: breakage

### ISSUE THREAD

**Issue by volkv** [uBlockOrigin/uAssets#15639]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cq.ru/articles/gaming/a-maloi-to-povzroslel-obzor-god-of-war-ragnarok-luchshego-ekshena-2022-goda`

### Category

breakage

### Describe the issue

Website search, likes, comments and maybe more doesn't work. Chrome console has JS errors

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 108342
  cosmetic: 59755
  scriptlet: 17906
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 39644-10, 21m
  default: 
    user-filters: 0-0, never
    easylist: 64258-66, 21m
    easyprivacy: 30818-1283, 21m
    plowe-0: 3670-874, 21m
    ublock-abuse: 76-1, 21m
    ublock-badware: 3968-108, 21m
    ublock-filters: 31208-143, 21m
    ublock-privacy: 258-1, 21m
    ublock-quick-fixes: 532-14, 21m
    ublock-unbreak: 1897-43, 21m
    urlhaus-1: 12393-0, 21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 939 ms
  maxAssetCacheWait: 252 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by volkv** [comment]
Website login also doesn't work. To to reproduce most of this issues you need to be logged in on cq.ru website

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/b1f02860b51805ec9c03dd62acca1cb50cdaffa7
