### ISSUE TITLE
[nsfw] porntrex.com: ads

### ISSUE THREAD

**Issue by Upheaval2950** [uBlockOrigin/uAssets#15630]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.porntrex.com/video/2125170/nuru-massage-hot-for-teacher2`

### Category

ads

### Describe the issue

Show 5 seconds ad at start of videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 108
filterset (summary): 
  network: 112426
  cosmetic: 38569
  scriptlet: 17140
  html: 792
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware: 38396-16278, never
    adguard-spyware-url: 824-124, never
  default: 
    user-filters: 2001-0, never
    ublock-filters: 31834-52, never
    ublock-badware: 3947-0, never
    ublock-privacy: 288-2, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1886-0, never
    ublock-quick-fixes: 430-0, never
    easylist: 62416-627, never
    easyprivacy: 30822-1707, never
    urlhaus-1: 11291-0, never
    plowe-0: 3671-3, never
filterset (user): [array of 2010 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4636 ms
  maxAssetCacheWait: 449 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    porntrex.com: 1
    awmdelivery.com: 2
    cashewsforlife208.com: 10
    goaserv.com: 1
    googletagmanager.com: 1
    h-cdn.com: 5
    nightfallroad.com: 2
    xxxjmp.com: 2
```
</details>

**Comment by mapx-** [comment]
- update all filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))

- test again

**Comment by okiehsch** [comment]
The existing filter works as expected, the "5 seconds ads" message only shows up for a split second.

**Comment by AntiAdvert** [comment]
visit `about:addons` -> if there is any other content blocker (e.g., ad blocker / tracker blocker etc.), consider disabled it/them

**Comment by ghajini** [comment]
@ryanbr 

`||porndoe.com/sitePreRoll/$xhr,domain=porntrex.com`
