### ISSUE TITLE
AndroidCentral.com

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1564]
### URL(s) where the issue occurs

`https://www.androidcentral.com/usb-c-audio`

### Describe the issue

Images won't be loaded unless uBO turns off.

### Versions

- Browser/version: 64.0.3282.167 (Official Build) (64-bit)
- uBlock Origin version: v1.15.2

### Settings

Tested with default settings

**Comment by okiehsch** [comment]
Actually I just realized that this was fixed in `EasyList` yesterday, https://github.com/easylist/easylist/commit/dfa826984c66edd31d5ac6f89f648058aea75601, so updating your `EasyList` filters will also fix this issue.
