### ISSUE TITLE
vrt.be: breakage

### ISSUE THREAD

**Issue by anthonyvdotbe** [uBlockOrigin/uAssets#15642]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vrt.be/vrtnu/a-z/reizen-waes/7/reizen-waes-s7a7-nairobi/`

### Category

breakage

### Describe the issue

When clicking "play", the video no longer starts and the "loading" icon stays forever.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 89021
  cosmetic: 38504
  scriptlet: 16677
  html: 795
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31926-56, 1d.4h.5m
    ublock-badware: 3972-0, 1d.4h.4m
    ublock-privacy: 285-0, 2d.6h.5m
    ublock-abuse: 76-0, 2d.6h.4m
    ublock-unbreak: 1906-0, 1d.4h.3m
    easylist: 62879-595, 5d.8h.5m
    easyprivacy: 30787-1708, 5d.8h.6m
    urlhaus-1: 11473-0, 23h.33m
    plowe-0: 3669-3, 8d.9h.40m
    ublock-quick-fixes: 546-0, 23h.34m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 709 ms (selfie)
  maxAssetCacheWait: 206 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    a51.be: 6
    adobedtm.com: 5
    demdex.net: 1
    gemius.pl: 1
    imasdk.googleapis.com: 1
    report-uri.com: 1
    sentry-cdn.com: 1
    sentry.io: 5
```
</details>

**Comment by mapx-** [comment]
@BPower0036

add
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect-rule,domain=vrt.be`

@anthonyvdotbe enable this list too:
`NLD: EasyDutch`

**Comment by anthonyvdotbe** [comment]
@mapx- thanks, after enabling that list it works again
