### ISSUE TITLE
vipleague.st: breakage

### ISSUE THREAD

**Issue by KarlG1965** [uBlockOrigin/uAssets#15644]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.vipleague.st/schalke-04-vs-bayern-munich-1-live-streaming`

### Category

breakage

### Describe the issue

The live stream doesn't load if uBlock is activated. If I deactivate it, it comes. It's not just this particular stream, I've tried with other streams as well and all had the same result.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 93503
  cosmetic: 42825
  scriptlet: 16691
  html: 797
listset (total-discarded, last-updated): 
  default: 
    user-filters: 477-12, never
    ublock-filters: 31955-58, 1h.49m
    ublock-badware: 3972-0, 1h.49m
    ublock-privacy: 286-0, 1h.49m
    ublock-abuse: 76-0, 1h.49m
    ublock-unbreak: 1909-1, 1h.49m
    easylist: 64278-617, 1h.49m
    easyprivacy: 30820-1720, 1h.49m
    urlhaus-1: 12388-0, 1h.49m
    plowe-0: 3670-3, 1h.49m
    DEU-0: 6020-2, 1h.49m
    ublock-quick-fixes: 540-0, 1h.49m
filterset (user): [array of 477 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 172 ms (selfie)
  maxAssetCacheWait: 187 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    abbine.com: 1
    celeritascdn.com: 1
    chatango.com: 1
    cloudflare.net: 4
    googlesyndication.com: 1
    googletagmanager.com: 1
    greatdexchange.com: 2
    jams.wiki: 4
    paddlesoothesoloist.com: 2
    superonclick.com: 2
```
</details>

**Comment by okiehsch** [comment]
````
*$script,3p,denyallow=cloudflare.net|fastly.net|jsdelivr.net,domain=nolive.me
*$script,3p,denyallow=fastly.net|jsdelivr.net,domain=nolive.me,badfilter
````
Firefox only issue.
