### ISSUE TITLE
payfit.com: breakage

### ISSUE THREAD

**Issue by rougeaden** [uBlockOrigin/uAssets#15641]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://payfit.com/fr/`

### Category

breakage

### Describe the issue

blank page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 111476
  cosmetic: 47492
  scriptlet: 16755
  html: 795
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31936-147, 1d.4h.57m
    ublock-badware: 3972-0, 1d.4h.57m
    ublock-privacy: 286-0, 1d.19h.32m
    ublock-abuse: 76-0, 1d.19h.31m
    ublock-unbreak: 1907-1, 1d.4h.57m
    ublock-quick-fixes: 540-0, 2h.29m
    easylist: 64667-643, 2h.31m
    easyprivacy: 30818-1709, 2h.30m
    urlhaus-1: 11473-0, 2h.28m
    plowe-0: 3670-3, 1d.19h.34m
    FRA-0: 30828-433, 1d.4h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3115 ms
  maxAssetCacheWait: 914 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    axept.io: 1
    googletagmanager.com: 1
```
</details>

**Comment by AntiAdvert** [comment]
@Yuki2718 @AdamWr `AdGuard French` `payfit.com#@#.publicity`

**Comment by mapx-** [comment]
@smed79
