### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by Farzam003** [uBlockOrigin/uAssets#15648]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Describe the issue

microsoft recognizes that i use adblocker and blocks a bit of the web, its easily solvable tho with elemenet pickers and zappers but then it reapears

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91440
  cosmetic: 38518
  scriptlet: 16674
  html: 795
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31901-42, 3d.3h.16m
    ublock-badware: 3962-0, 3d.3h.15m
    ublock-privacy: 285-0, 4d.2h.57m
    ublock-abuse: 76-0, 4d.2h.56m
    ublock-unbreak: 1906-0, 3d.3h.14m
    ublock-quick-fixes: 549-0, 6h.10m
    easylist: 64417-607, 3d.3h.18m
    easyprivacy: 30791-1708, 3d.3h.17m
    urlhaus-1: 12393-0, 6h.9m
    plowe-0: 3668-3, 4d.2h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 796 ms (selfie)
  maxAssetCacheWait: 70 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    live.com: 3
    3lift.com: 3
    adnxs.com: 3
    microsoft.com: 4
    msn.com: 1
    office.net: 8
    taboola.com: 2
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings, update all filter lists, test again.

If still does not work:

- install the last uBO build:
Firefox: Click [uBlock0_1.45.3b0.firefox.signed.xpi](https://github.com/gorhill/uBlock/releases/download/1.45.3b0/uBlock0_1.45.3b0.firefox.signed.xpi)
- update again all the filter lists
- test again

**Comment by mapx-** [comment]
Another try: 
enable this list too => `uBlock filters – Annoyances`
