### ISSUE TITLE
weadown.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15649]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://weadown.com/gravity-forms-wordpress-plugin-gpl1/`

### Category

detection

### Describe the issue

https://i.imgur.com/okiIckW.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/okiIckW.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 109
filterset (summary): 
  network: 111921
  cosmetic: 167378
  scriptlet: 25961
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7917-3, 2m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 2m
    adguard-annoyance: 60931-393, 2m
    adguard-spyware: 39421-4116, 2m
    fanboy-annoyance: 82783-3864, 2m
    fanboy-cookiemonster: 43100-43064, 2m
    ublock-annoyances: 4780-212, 2m
  default: 
    user-filters: 6-0, never
    easylist: 64282-151, 2m
    easyprivacy: 30822-14060, 2m
    ublock-abuse: 76-0, 2m
    ublock-badware: 3968-106, 2m
    ublock-filters: 31212-600, 2m
    ublock-privacy: 258-47, 2m
    ublock-quick-fixes: 533-14, 2m
    ublock-unbreak: 1898-62, 1m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 4 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  manualUpdateAssetFetchPeriod: 2000
supportStats: 
  allReadyAfter: 1530 ms (selfie)
  maxAssetCacheWait: 861 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googlesyndication.com: 4
    googletagmanager.com: 1
    onesignal.com: 1
```
</details>

**Comment by okiehsch** [comment]
Works fine with a default setup, I can only reproduce if I disable `uBO-filters`.

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/201780889-0c097d56-3a9d-42e9-971b-522a7b430d18.png)

**Comment by mapx-** [comment]
Reset uBO, update all the lists, disable any other extension, disable (if any) the web shields in your antivirus / antimalware software, restart the system, reopen the browser, test again

**Comment by 3xploiton3** [comment]
yeah i do default uBO, using chrome dev latest version, anti-adblock still persist

**Comment by 3xploiton3** [comment]
ok, mode incognito its good, maybe i should disable addon

**Comment by 3xploiton3** [comment]
https://chrome.google.com/webstore/detail/netcraft-extension/bmejphbfclcpmpohkggcjeibfilpamia

this addon make uBO doesn't work
