### ISSUE TITLE
gog.com: breakage

### ISSUE THREAD

**Issue by Marlock1234** [uBlockOrigin/uAssets#15646]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gog.com/forum/general`

### Category

breakage

### Describe the issue

The page simply does not open. All other links on the same forum do.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91287
  cosmetic: 0
  scriptlet: 16690
  html: 796
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 31951-8171, 1h.7m
    ublock-badware: 3972-634, 1h.6m
    ublock-privacy: 286-10, 1h.5m
    ublock-abuse: 76-1, 1h.4m
    ublock-unbreak: 1909-251, 1h.3m
    ublock-quick-fixes: 540-195, 1h.2m
    easylist: 64278-29980, 1h.1m
    easyprivacy: 30818-1712, 1h
    urlhaus-1: 12388-0, 59m
    plowe-0: 3670-3, 58m
filterset (user): [array of 3 redacted]
hostRuleset: 
  added: [array of 22 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 3409 ms (selfie)
  maxAssetCacheWait: 1578 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default settings, update all filter lists, test again.

If still does not work:
- install the last uBO build:
Firefox: Click [uBlock0_1.45.3b0.firefox.signed.xpi](https://github.com/gorhill/uBlock/releases/download/1.45.3b0/uBlock0_1.45.3b0.firefox.signed.xpi)
- update again all the filter lists
- test again

**Comment by Marlock1234** [comment]
Tried all of that, does not work.


ned, 13. stu 2022. u 00:11 mapx ***@***.***> napisao je:

**Comment by mapx-** [comment]
Did you NOW install uBlock0_1.45.3b0 ?

**Comment by Marlock1234** [comment]
No, I could not get the download link. Do you have a download link please?

ned, 13. stu 2022. u 00:17 mapx ***@***.***> napisao je:

**Comment by mapx-** [comment]
- go to https://github.com/gorhill/uBlock/releases
- then install the FF version (Firefox: Click ....)

**Comment by Marlock1234** [comment]
I did that now, thank you.

No changes, this time the page keeps on spinning, but nothing happens.

In console, not I am getting the following: This page is in Almost
Standards Mode. Page layout may be impacted. For Standards Mode use
“<!DOCTYPE html>”.

Not sure if this is relevant.

ned, 13. stu 2022. u 00:29 mapx ***@***.***> napisao je:

**Comment by Marlock1234** [comment]
I also have this error in console:

GET
https://www.gog.com/forum/general
Status
500
Internal Server Error

ned, 13. stu 2022. u 00:36 Lord Marlock ***@***.***> napisao
je:

**Comment by Marlock1234** [comment]
In uBO logger: this pops out first:

Contextwww.gog.com
Partyness(1) gog.com ⇒ gog.com
Typedoc
URLhttps://www.gog.com/forum/general

ned, 13. stu 2022. u 00:37 Lord Marlock ***@***.***> napisao
je:

**Comment by Marlock1234** [comment]
Also this:

Contextbehind-the-scene
Partyness(0,3) behind-the-scene ⇒ [ff00::]
Typexhr
URLhttps://
[ff00::]/nscl/moz-extension://59458ea5-99f5-4d0a-b94a-c4f724b09455/syncMessage?id=4be9f647e7.aa28%2Chttps%3A%2F%
2Fwww.gog.com%2Fforum%2Fgeneral&url=https%3A%2F%2Fwww.gog.com
%2Fforum%2Fgeneral&top=true&msg=%7B%22id%22%3A%22fetchChildPolicy%22%2C%22url%22%3A%22https%3A%2F%
2Fwww.gog.com%2Fforum%2Fgeneral%22%7D

ned, 13. stu 2022. u 00:38 Lord Marlock ***@***.***> napisao
je:

**Comment by Marlock1234** [comment]
This:

Contextwww.gog.com
Partyness(3) gog.com ⇒ akamaiedge.net
Typeimage
URLhttps://e11072.b.akamaiedge.net/ <https://e11072.b.akamaiedge.net/>
CNAMEwww.gog.com ⇒ e11072.b.akamaiedge.net
Original URLhttps://www.gog.com/favicon.ico

ned, 13. stu 2022. u 00:39 Lord Marlock ***@***.***> napisao
je:

**Comment by Marlock1234** [comment]
And this:

Contextwww.gog.com
Partyness(1) gog.com ⇒ gog.com
Typeimage
URLhttps://www.gog.com/favicon.ico



No idea if any of this is relevant?

ned, 13. stu 2022. u 00:39 Lord Marlock ***@***.***> napisao
je:

**Comment by Marlock1234** [comment]
If you think you might be able to help me, I can go up to discord or irc to
make it fasteR?

ned, 13. stu 2022. u 00:40 Lord Marlock ***@***.***> napisao
je:

**Comment by stephenhawk8054** [comment]
Can you screenshot the window? Which add-ons are you using right now?

**Comment by Marlock1234** [comment]
I am using:
Adblock plus
Augmented Steam
Bitwarden
Checker Plus (Gmail and Google Calendar)
Don't track me google
Enhancer for YT
Facebook Container
Javascript Switcher
NoScript
SponsorBlock for YT
Tampermonkey
uBlock Origin

ned, 13. stu 2022. u 00:42 stephenhawk8054 ***@***.***>
napisao je:

**Comment by stephenhawk8054** [comment]
Test again in another Firefox profile with only ublock installed.

**Comment by Marlock1234** [comment]
Not sure how to switch a profile?

ned, 13. stu 2022. u 00:51 stephenhawk8054 ***@***.***>
napisao je:

**Comment by stephenhawk8054** [comment]
Like this:

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

I have added more information in the previous reply, please read it carefully.

**Comment by Marlock1234** [comment]
I have tried to open link in a personal container, and it works. Any idea
why?

ned, 13. stu 2022. u 00:56 stephenhawk8054 ***@***.***>
napisao je:

**Comment by Marlock1234** [comment]
So, when I am signed out, it works. When I am signed in to GoG, it does
not...

ned, 13. stu 2022. u 00:59 Lord Marlock ***@***.***> napisao
je:

**Comment by stephenhawk8054** [comment]
I can sign in normally

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/201499438-61b4fb25-ded9-48cd-8708-b2ac31e2a6ee.png)

</details>

Did you do this yet?

> Test again in another Firefox profile with only ublock newest version installed (the one mapx gave the link above).
>
> Remember to force update the filter lists after installed.

**Comment by Marlock1234** [comment]
Ok, I will try.

Just to be clear, I can sign in normally as well. And everything works fine
EXCEPT that one particular link https://www.gog.com/forum/general

In uBlock, I only have one filter: www.gog.com###t_fav

I will try as you suggest.

ned, 13. stu 2022. u 01:07 stephenhawk8054 ***@***.***>
napisao je:

**Comment by Marlock1234** [comment]
Done everything as instructed. SAME RESULT xD

ned, 13. stu 2022. u 01:08 Lord Marlock ***@***.***> napisao
je:

**Comment by stephenhawk8054** [comment]
Can you turn off ublock and test again?

**Comment by Marlock1234** [comment]
Same result.
But, when I sign out of GoG, I can access the page normally xD


ned, 13. stu 2022. u 01:13 stephenhawk8054 ***@***.***>
napisao je:

**Comment by stephenhawk8054** [comment]
> Same result.

Then it's the site's issue, not a uBO's issue.

**Comment by Marlock1234** [comment]
Ok, thank you for the confirmation.

I am not sure how to get in touch with the GoG admins, but I will do my
best.

Thank you for your time and patience!

LordMarlock is my acc on GoG.

ned, 13. stu 2022. u 01:16 stephenhawk8054 ***@***.***>
napisao je:

**Comment by mapx-** [comment]
not only abp => Javascript Switcher, NoScript too.

**Comment by Marlock1234** [comment]
Hi, I have disabled all of them in order to check whether any of them is
causing the issue.
So please be more careful in the future prior to assigning blame. If you
are unsure, ask first, then judge.

ned, 13. stu 2022. u 04:42 MasterKia ***@***.***> napisao je:
