### ISSUE TITLE
prod.office.ch.locatee.com: breakage

### ISSUE THREAD

**Issue by madridpixel** [uBlockOrigin/uAssets#15643]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://prod.office.ch.locatee.com/auth/login`

### Category

breakage

### Describe the issue

The login button for this site gets blocked by the default lists in ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/12069865/201485167-83701ae6-0afd-4326-926c-877c24e6b505.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 90613
  cosmetic: 38545
  scriptlet: 16691
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64510-52, 1d.4h.17m
    easyprivacy: 30793-1171, 1d.4h.16m
    plowe-0: 3670-868, 6h.39m
    ublock-abuse: 76-0, 6h.38m
    ublock-badware: 3968-109, 20h.36m
    ublock-filters: 31203-112, 20h.35m
    ublock-privacy: 258-1, 6h.37m
    ublock-quick-fixes: 532-13, 6h.36m
    ublock-unbreak: 1894-43, 20h.34m
    urlhaus-1: 11473-0, 6h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 502 ms (selfie)
  maxAssetCacheWait: 78 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    locatee.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||prod.office.ch.locatee.com/internal/api/analytics/v1/systemPropertys$xhr,1p`

@ryanbr
