### ISSUE TITLE
next-episode.net: detection

### ISSUE THREAD

**Issue by 27chandler** [uBlockOrigin/uAssets#15656]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://next-episode.net/`

### Category

detection

### Describe the issue

Next episode detects ublock origin and adds an overlay preventing use of the site when logged in. This overlay appears on the homepage as well as the calendar page:

```
https://next-episode.net/
https://next-episode.net/calendar/
```

I previously reported this in https://github.com/uBlockOrigin/uAssets/issues/15569 and it was fixed when the issue was closed, but after a few days the overlay reappeared. I can't manually block the overlay as its name seems to change every time the page is refreshed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19729460/201522743-3d8cc03a-a143-4a4d-bb54-c18cfa75f780.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 101476
  cosmetic: 179279
  scriptlet: 24250
  html: 820
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4802-5, 1d.11h.45m
    adguard-annoyance: 60934-259, 1d.11h.43m
    adguard-social: 18931-1880, 1d.11h.42m
    fanboy-annoyance: 82433-27322, 5d.14h.41m
    fanboy-social: 23423-8, 5d.14h.41m
  default: 
    user-filters: 85-6, never
    ublock-filters: 31946-406, 1d.11h.49m
    ublock-badware: 3972-0, 1d.11h.48m
    ublock-privacy: 286-0, 1d.11h.47m
    ublock-abuse: 76-0, 1d.11h.46m
    ublock-unbreak: 1908-1, 1d.11h.44m
    easylist: 64361-667, 5d.14h.42m
    easyprivacy: 30787-1800, 5d.14h.42m
    plowe-0: 3668-3, 5d.14h.42m
    urlhaus-1: 10191-0, 23m
    ublock-quick-fixes: 541-0, 22m
filterset (user): [array of 86 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1068 ms (selfie)
  maxAssetCacheWait: 808 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googlesyndication.com: 3
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Try installing the last uBO build 1.45.3b0 - then **update all the filter lists**
https://github.com/gorhill/uBlock/releases/tag/1.45.3b0
(`Firefox Click`..)

**Comment by 27chandler** [comment]
I've installed the uBO build that you linked: 
![image](https://user-images.githubusercontent.com/19729460/201542523-e58aa37c-74d1-4e0d-bf91-de7b45e87a0e.png)

and have also purged and then updated all my filter lists but I am still getting the overlay.

In the overlay it makes note that I've had an account for more than 2 years, could it be that you're unable to reproduce it because your account is too new?

![image](https://user-images.githubusercontent.com/19729460/201542640-6aae1675-718f-4a80-8053-e842c40418bc.png)

**Comment by 27chandler** [comment]
Just to update: I just disabled all addons, re-enabled them all then rebooted my PC and it seems I'm no longer getting the overlay. Maybe the updated version fixed the filter not applying but it needed a reboot to work correctly?

**Comment by mapx-** [comment]
It shouldn't be like that... but the result matters
