### ISSUE TITLE
[nsfw] give-crypto.com: privacy

### ISSUE THREAD

**Issue by gonzalolater** [uBlockOrigin/uAssets#15650]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://give-crypto.com/`

### Category

privacy

### Describe the issue

Scam

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/42863568/201510227-65831aca-8484-47ec-87a0-1c6416bacf8c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 93931
  cosmetic: 43711
  scriptlet: 16922
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 13h.47m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 3-0, never
    easylist: 64358-52, 5d.11h.2m
    easyprivacy: 30794-1170, 1d.7h.35m
    plowe-0: 3668-867, 4d.1h.51m
    spa-0: 3367-11, 11h.11m
    spa-1: 4838-176, 2d.18h.37m
    ublock-abuse: 76-0, 12d.15h.43m
    ublock-badware: 3958-109, 3d.5h.17m
    ublock-filters: 31176-146, 3d.11h.7m
    ublock-privacy: 260-1, 12d.15h.42m
    ublock-quick-fixes: 532-9, 13h.46m
    ublock-unbreak: 1893-44, 3d.11h.6m
    urlhaus-1: 12388-0, 13h.45m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13146 ms (selfie)
  maxAssetCacheWait: 1314 ms
popupPanel: 
  blocked: 0
  no-large-media: true
  no-popups: true
```
</details>

**Comment by gonzalolater** [comment]
Block this page

**Comment by mapx-** [comment]
provide reason, tests, scan using whatever privacy tool etc

**Comment by mapx-** [comment]
maybe `Phishing` ?

from virustotal:
![image](https://user-images.githubusercontent.com/10303732/201513811-ff375832-ba7f-4631-8660-ec12f801659b.png)

**Comment by gonzalolater** [comment]
Yes. Try to y deposit money for extract money.
