### ISSUE TITLE
lego.com: breakage

### ISSUE THREAD

**Issue by YotaMoteuchi** [uBlockOrigin/uAssets#15657]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lego.com/fr-fr/categories/sinterklaas?cmp=emc-c=PROMO-eid=11051-d=11/10/2022-n=202211_W45_NEWSLETTER_CONTROL-jid=105830-s=NEWS-t=MIX-a=ACTIVE-tst=Variant_A_10160&j=105830&sfmc_sub=41597892&l=259_HTML&u=9444037&mid=510004361&jb=5140`

### Category

breakage

### Describe the issue

Lego site shows a message Error: sorry, We encoutered an Error (or a similar message).
And we can't Scroll on the page once it IS totally loaded.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox Mobile: 106
filterset (summary): 
  network: 134295
  cosmetic: 138768
  scriptlet: 24483
  html: 803
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 60943-5344, now
    adguard-social: 18929-1676, now
    fanboy-thirdparty_social: 68-1, now
    fanboy-annoyance: 82829-70850, now
    fanboy-cookiemonster: 43070-17232, now
    fanboy-social: 23418-13723, now
    ublock-annoyances: 4831-7, now
    dpollock-0: 11390-481, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 32053-273, now
    ublock-badware: 4006-0, now
    ublock-privacy: 286-1, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1910-0, now
    ublock-quick-fixes: 551-1, now
    adguard-mobile: 8181-206, now
    easylist: 64330-17980, now
    easyprivacy: 30826-1815, now
    urlhaus-1: 10191-0, now
    plowe-0: 3670-3, now
    FRA-0: 30874-3771, now
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8640 ms (selfie)
  maxAssetCacheWait: 3103 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    lego.com: 6
    force.com: 1
    newrelic.com: 1
    report-uri.com: 3
```
</details>

**Comment by mapx-** [comment]
- even getting that red message I'm able to scroll the page
- The red message is due to a filter in Adguard annoyances list, add this filter and see if fixes your issue

`||service.force.com/embeddedservice/*/esw.min.js$badfilter`



||service.force.com/embeddedservice/*/esw.min.js$badfilter

**Comment by YotaMoteuchi** [comment]
Unfortunately, adding the filter only remove the red message. I'm on Android and the Scroll is impossible with uBlockOrigin. Deactivating it adds many unwanted messages but allows scrolling through the pages of the site.
If you need any more détails on my configuration, don't hésitante.

**Comment by mapx-** [comment]
Can you scroll the page if disable Adguard annoyances list ?

**Comment by acidghost** [comment]
@mapx- I'm having problems logging into lego.com (the modal containing the form does not appear). Disabling Adguard annoyances fixes the issue.

**Comment by mapx-** [comment]
is this enough to fix your issue ?

`lego.com#@#aside[class^="Modalstyles__Container"]`

@Yuki2718
