### ISSUE TITLE
Postype: context menu blockage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15654]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://masatokki.postype.com/post/3660671`

### Describe the issue

Right click/context menu doesn't work

### Notes

Fixed by `postype.com##+js(aeld, contextmenu)`, but I haven't checked if there's a better way to do it.

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91325
  cosmetic: 38591
  scriptlet: 16692
  html: 777
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31941-128, now
    ublock-badware: 4007-0, now
    ublock-privacy: 286-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1909-1, now
    ublock-quick-fixes: 540-0, now
    easylist: 64280-515, now
    easyprivacy: 30822-1726, now
    urlhaus-1: 12389-0, now
    plowe-0: 3670-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1765 ms
  maxAssetCacheWait: 195 ms
```
</details>

**Comment by stephenhawk8054** [comment]
You can enable `uBlock filters – Annoyances` list and force update the filter lists in about 10 minutes.
