### ISSUE TITLE
https://uploadrar.com/

### ISSUE THREAD

**Issue by dimo70** [uBlockOrigin/uAssets#15658]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://uploadrar.com/

### Describe the issue

Problem downloading from site, new rules!

### uBlock Origin version

 1.45.0

### Browser name and version

Firefox 106.0.5 64-бита

### Settings

no changes

**Comment by ghajini** [comment]
a link to test = `https://uploadrar.com/590qngxc9aw5`
download link was hidden
