### ISSUE TITLE
unilad.com: detection ?

### ISSUE THREAD

**Issue by iluvatoq** [uBlockOrigin/uAssets#15652]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.unilad.com/celebrity/taylor-lautner-marries-taylor-lautner-20221113`

### Describe the issue

Video not loading

### Screenshot(s)

https://user-images.githubusercontent.com/81825037/201518676-645b79e3-7118-4ab3-a37e-b5827dd092e5.png

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 91216
  cosmetic: 40196
  scriptlet: 16715
  html: 0
listset (total-discarded, last updated): 
  added: 
    NLD-0: 2476-12, 2d.18h.47m
  default: 
    user-filters: 0-0, never
    easylist: 64361-55, 5d.18h.56m
    easyprivacy: 30787-1171, 5d.18h.56m
    plowe-0: 3668-867, 5d.18h.56m
    ublock-abuse: 76-0, 1d.17h.43m
    ublock-badware: 3968-109, 1d.17h.42m
    ublock-filters: 31202-133, 1d.17h.41m
    ublock-privacy: 258-1, 1d.17h.40m
    ublock-quick-fixes: 541-13, 18h
    ublock-unbreak: 1894-57, 1d.17h.39m
    urlhaus-1: 11473-0, 17h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1026 ms (selfie)
  maxAssetCacheWait: 112 ms
```
</details>

**Comment by mapx-** [comment]
What chromium browser are you using ?

if brave => disable the shields for unilad
if edge => disable protection tracking
if opera / other => disable the builtin blocker

**Comment by iluvatoq** [comment]
I use google chrome. No other blockers active.

**Comment by iluvatoq** [comment]
Also, pretty standard after install (uBlockOrigin)

**Comment by stephenhawk8054** [comment]
Video plays fine for me on chrome. Check if you are using any:

- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by iluvatoq** [comment]
I have malware bytes installed but even when turned off nothing loads ( video)
