### ISSUE TITLE
hackr.io: detection

### ISSUE THREAD

**Issue by Prakash4844** [uBlockOrigin/uAssets#15655]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://hackr.io/`

### Category

detection

### Describe the issue

Ublock Origin Gets Detected as Shown in Screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/81550376/201520447-4acb3a76-a712-456e-a9cc-fb92de81068e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 108
filterset (summary): 
  network: 91295
  cosmetic: 38589
  scriptlet: 16692
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 12-0, never
    easylist: 64280-53, 7h.52m
    easyprivacy: 30822-1171, 2h.20m
    plowe-0: 3668-867, 4d.23h.31m
    ublock-abuse: 76-0, 4d.23h.33m
    ublock-badware: 3968-108, 1d.5h.34m
    ublock-filters: 31205-112, 1d.5h.32m
    ublock-privacy: 257-1, 4d.23h.34m
    ublock-quick-fixes: 533-14, 2h.18m
    ublock-unbreak: 1893-42, 2d.20h.34m
    urlhaus-1: 12389-0, 2h.19m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 30 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 37229 ms (selfie)
  maxAssetCacheWait: 1430 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    hackr.io: 10
    affilimate.io: 1
    doubleclick.net: 1
    ezodn.com: 1
    google-analytics.com: 1
    google.com: 5
    googleoptimize.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    jobbio.com: 2
    quantserve.com: 1
    s-onetag.com: 1
    servenobid.com: 1
    sonobi.com: 1
    stakingsmile.com: 1
    unblockia.com: 1
    wisepops.com: 1
```
</details>

**Comment by Prakash4844** [comment]
Yes, I checked I was using Strict Tracking Prevention 
![image](https://user-images.githubusercontent.com/81550376/201521305-bfed6bcc-57c6-4b16-b9f0-547ac80884c3.png)

After Disabling it, Ublock Origin isn't detected anymore. 

Thanks

**Comment by stephenhawk8054** [comment]
Please check what you have ticked on carefully

> - [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)

**Comment by mapx-** [comment]
Weird, I'm still constantly getting anti adb in chrome

**Comment by stephenhawk8054** [comment]
> Weird, I'm still constantly getting anti adb in chrome (on normal refresh without bypassing the cache)

Ah you're right, refreshing without bypassing cache triggers the anti-adblock again

**Comment by stephenhawk8054** [comment]
This one works for me

```adb
hackr.io##+js(no-fetch-if, googlesyndication)
```

Can anyone else check it?

**Comment by mapx-** [comment]
yes, working

**Comment by stephenhawk8054** [comment]
@mapx- For the anti-adb can be closed by user, should the filter be moved to annoyances or stay in main list? I'm still not sure for the case when it can be closed but comes back after every refresh/new link.

**Comment by mapx-** [comment]
it's ok in the main list. It would be annoyance if after closing it does not appear anymore (at least in the same session)
