### ISSUE TITLE
tripit.com: breakage

### ISSUE THREAD

**Issue by palzkillm** [uBlockOrigin/uAssets#15653]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tripit.com/`

### Category

breakage

### Describe the issue

Website remains blank. With UO disabled, TrustArc Cookie banner appears on a white background.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Unbenannt1](https://user-images.githubusercontent.com/107746723/201519927-a0663953-5b93-46cd-9a79-577eba387df4.PNG)
![Unbenannt](https://user-images.githubusercontent.com/107746723/201519957-2df1f5af-358d-41a8-a1b6-2f7663d26948.PNG)
![Unbenannt](https://user-images.githubusercontent.com/107746723/201519985-2fb61386-fd01-4058-bb54-615448725ad5.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 309228
  cosmetic: 222054
  scriptlet: 37356
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 60917-97, 2d.18h.1m
    adguard-generic: 65630-486, 2d.18h.5m
    adguard-mobile: 8176-51, 2d.13h.55m
    adguard-social: 18938-844, 2d.18h.2m
    adguard-spyware: 38390-4177, 2d.18h.3m
    adguard-spyware-url: 824-1, 2d.18h.4m
    curben-phishing: 165674-0, 20h.7m
    fanboy-annoyance: 82393-4942, 9d.1h.28m
    fanboy-cookiemonster: 42695-42695, 9d.1h.29m
    fanboy-social: 23414-23412, 4d.2h.30m
    fanboy-thirdparty_social: 68-21, 9d.1h.30m
    ublock-annoyances: 4779-233, 2d.18h
  default: 
    user-filters: 7-1, never
    DEU-0: 6018-0, 1d.17h.50m
    easylist: 64361-1028, 6d.2h.8m
    easyprivacy: 30787-14150, 5d.2h.19m
    plowe-0: 3669-1034, 13d.2h.10m
    ublock-abuse: 76-0, 13d.2h.12m
    ublock-badware: 3958-248, 2d.17h.59m
    ublock-filters: 31181-3656, 2d.17h.58m
    ublock-privacy: 258-50, 20h.10m
    ublock-quick-fixes: 532-31, 20h.9m
    ublock-unbreak: 1893-100, 2d.17h.57m
    urlhaus-1: 11473-5, 20h.8m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 32 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 544 ms (selfie)
  maxAssetCacheWait: 412 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
````
||consent.trustarc.com^$3p,domain=~tripit.com
||consent.trustarc.com^$3p,badfilter
````
Caused by `Adguard Annoyances`.
@Yuki2718
