### ISSUE TITLE
mixcloud.com: breakage

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uAssets#15663]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.mixcloud.com/toolroom/stream`

### Describe the issue

redirect-rule to ima3 shim breaks playing a mix on mixcloud when the site wants to play a preroll ad. 

https://user-images.githubusercontent.com/16567977/201554946-438dd3f1-fe6e-4ad0-91ca-ab38e9c7e22a.mp4

### Notes

You might have trouble reproducing as the site doesn't serve a preroll 100% of the time. You can check if it's trying to play an ad by looking at the response for the graphql query `fetchAudioAdsInfoQuery` when you click play. 

![image](https://user-images.githubusercontent.com/16567977/201555057-7a6d0dfd-5012-4c59-946b-4d73d924a849.png)
![image](https://user-images.githubusercontent.com/16567977/201555086-fdd9f6a8-c473-47fb-95d5-c0ec8e807b9e.png)

Fix:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.mixcloud.com`
FYI, the site worked fine with `ima3.js` blocked before the redirect-rule was added.

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 89111
  cosmetic: 38592
  scriptlet: 16696
  html: 796
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31948-47, 1d.19h.37m
    ublock-badware: 3972-0, 1d.19h.37m
    ublock-privacy: 286-0, 1d.19h.37m
    ublock-abuse: 76-0, 1d.19h.37m
    ublock-unbreak: 1909-1, 1d.19h.37m
    ublock-quick-fixes: 566-0, 6m
    easylist: 64258-612, 1d.19h.37m
    easyprivacy: 30815-1710, 1d.19h.37m
    urlhaus-1: 10228-0, 6m
    plowe-0: 3670-3, 1d.19h.37m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1147 ms
  maxAssetCacheWait: 634 ms
```
</details>

**Comment by ghajini** [comment]
can you check now by update of ublock filters?
a generic ima3 redirect rule was removed yesterday only

**Comment by liamengland1** [comment]
Thanks @ghajini , that was it 👍
