### ISSUE TITLE
bip39key.online: privacy

### ISSUE THREAD

**Issue by HHGAG** [uBlockOrigin/uAssets#15662]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bip39key.online/`

### Category

privacy

### Describe the issue

This website sends the values to an botnet that's operated over the telegram api

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92927
  cosmetic: 50973
  scriptlet: 17762
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 5h.58m
    TUR-0: 11289-10, 3d.12h.23m
  default: 
    user-filters: 57-0, never
    DEU-0: 6018-0, 5h.55m
    easylist: 64332-77, 9h.59m
    easyprivacy: 30787-1186, 5d.12h.17m
    plowe-0: 3668-869, 6d.12h.27m
    ublock-abuse: 76-0, 6d.12h.26m
    ublock-badware: 3968-108, 3d.16h.24m
    ublock-filters: 31181-133, 3d.16h.26m
    ublock-privacy: 257-1, 6d.12h.24m
    ublock-quick-fixes: 541-9, 5h.56m
    ublock-unbreak: 1893-43, 3d.16h.25m
    urlhaus-1: 10191-0, 5h.57m
filterset (user): [array of 57 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 249 ms (selfie)
  maxAssetCacheWait: 180 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> This website sends the values to an botnet that's operated over the telegram api

provide more details about your claim
