### ISSUE TITLE
gamingbible.co.uk: detection

### ISSUE THREAD

**Issue by RozvM** [uBlockOrigin/uAssets#15661]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gamingbible.co.uk/`

### Category

detection

### Describe the issue

When the mentioned website contains a video, instead of loading it in, it displays this message:
> **Please turn off your ad blocking software to view this video**

Examples:
```
https://www.gamingbible.co.uk/news/peaky-blinders-openworld-game-concept-trailer-20221111
https://www.gamingbible.co.uk/news/gears-of-war-developer-doesnt-want-chris-pratt-20221111
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/74600479/201536108-1c5cf77d-6233-4119-a4ce-5601f248aa47.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 91777
  cosmetic: 49630
  scriptlet: 16935
  html: 795
listset (total-discarded, last-updated): 
  added: 
    HUN-0: 2201-6, now
    JPN-1: 8221-30, now
    KOR-1: 3609-31, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 31960-57, now
    ublock-badware: 4007-0, now
    ublock-privacy: 286-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1906-0, now
    easylist: 64330-669, now
    easyprivacy: 30826-1753, now
    urlhaus-1: 10191-0, now
    plowe-0: 3670-3, now
    ublock-quick-fixes: 566-1, now
filterset (user): [empty]
trustedset: 
  added: [array of 694 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 265 ms (selfie)
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    gamingbible.co.uk: 3
    adsafeprotected.com: 2
    amazon-adsystem.com: 2
    aniview.com: 1
    ay.delivery: 2
    browsiprod.com: 1
    chartbeat.com: 1
    connatix.com: 1
    dotmetrics.net: 1
    doubleclick.net: 2
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    outbrain.com: 1
    permutive.com: 1
    quantserve.com: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by kodiakhub** [comment]
Ads:

`https://www.gamingbible.com/news/platform/steam/steam-free-store-credit-48-hour-event-855581-20250811`

<details><summary>Screenshot</summary>
<p>

<img width="1920" height="1052" alt="Image" src="https://github.com/user-attachments/assets/05569c29-0025-4e67-8a79-fc8e223c51b8" />

</p>
</details>

```adb
gamingbible.com##div[class^="advert-"]
```

**Comment by stephenhawk8054** [comment]
@ryanbr
