### ISSUE TITLE
fr.aliexpress.com: breakage

### ISSUE THREAD

**Issue by casualkitten1** [uBlockOrigin/uAssets#15660]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fr.aliexpress.com/premium/air-blower.html?d=y&origin=y&catId=0&initiative_id=SB_20221113083755&SearchText=air%20blower`

### Category

breakage

### Describe the issue

It's impossible to see articles when UBo is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading image.png…]()

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 355057
  cosmetic: 232258
  scriptlet: 38805
  html: 823
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 65631-5779, 2d.17h.40m
    adguard-spyware: 38390-16335, 2d.17h.39m
    adguard-spyware-url: 824-3, 2d.17h.38m
    block-lan: 44-0, 10d.4h.19m
    curben-phishing: 165674-8, 20h.46m
    curben-pup: 193-0, 20h.45m
    adguard-annoyance: 60922-4719, 2d.17h.37m
    fanboy-annoyance: 82775-43286, 1d.23h.33m
    fanboy-cookiemonster: 43058-166, 1d.23h.32m
    ublock-annoyances: 4802-5, 2d.17h.36m
    dpollock-0: 11390-483, now
    JPN-1: 8223-43, 2d.17h.34m
    RUS-0: 39662-448, 3h.55m
  default: 
    user-filters: 3-0, never
    ublock-filters: 31923-33, 2d.17h.43m
    ublock-badware: 3972-0, 2d.17h.42m
    ublock-privacy: 285-0, 6d.21h.12m
    ublock-abuse: 76-0, 6d.21h.11m
    ublock-unbreak: 1906-1, 2d.17h.41m
    ublock-quick-fixes: 540-9, 20h.48m
    easylist: 64372-902, 4d.23h.16m
    easyprivacy: 30787-1826, 4d.23h.15m
    urlhaus-1: 12388-0, 20h.47m
    plowe-0: 3670-3, 2d.23h.36m
    FRA-0: 30828-558, 2d.17h.35m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 717 ms (selfie)
  maxAssetCacheWait: 1272 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    aliexpress.com: 3
    alicdn.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    mmstat.com: 11
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/15629

Tell us if you want to share your credentials (in private), it's the only modality to investigate your issue.

However that user added these filters:

```
aliexpress.com#@#a[href*="aliexpress.com/item/"][href*="&aem_p4p_detail="]
aliexpress.com#@#a:has(> div img + span:has-text(/AD|Ann.|Annonce|Anuncio|Anúncio|Anzeige|Reklama|Reklam|מודעה|광고|إعلان/))
```
