### ISSUE TITLE
crast.net: detection

### ISSUE THREAD

**Issue by martijnhopman** [uBlockOrigin/uAssets#15669]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crast.net/nl/199376/black-friday-sale-google-reveals-offers-on-pixel-7-7-pro-and-6a/`

### Category

detection

### Describe the issue

Site detects uBlockOrigin and shows site overlay which can't be deleted.
![image](https://user-images.githubusercontent.com/53086542/201640096-0197d1a3-4a9e-4e86-9e4d-195d1c742771.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/53086542/201640137-a000eb22-9397-4c2a-a071-b2858ba275c4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Chromium: 107
filterset (summary): 
  network: 89945
  cosmetic: 40276
  scriptlet: 16701
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 21-4, never
    NLD-0: 2479-12, 3h.28m
    easylist: 64350-56, 3h.30m
    easyprivacy: 30826-1172, 3h.29m
    plowe-0: 3668-867, 7d.3h.26m
    ublock-abuse: 76-0, 3d.2h.45m
    ublock-badware: 3968-108, 3d.2h.44m
    ublock-filters: 31179-138, 3d.2h.41m
    ublock-privacy: 258-1, 3d.2h.46m
    ublock-quick-fixes: 558-9, 3h.26m
    ublock-unbreak: 1894-57, 3d.2h.43m
    urlhaus-1: 10228-0, 3h.27m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 27 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3751 ms (selfie)
  maxAssetCacheWait: 455 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
I can only reproduce if I disable `uBO-filters`.
