### ISSUE TITLE
Can't block an address

### ISSUE THREAD

**Issue by Rufh** [uBlockOrigin/uAssets#15668]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

moz-extension://e386e5ee-aa9a-4fc0-b086-6e41ead8dd0e/document-blocked.html?details=%7B%22url%22%3A%22https%3A%2F%2Fawledconside.xyz%2FRmpoNDEnCAVA%22%2C%22hn%22%3A%22awledconside.xyz%22%2C%22dn%22%3A%22awledconside.xyz%22%2C%22fs%22%3A%22%7C%7Cawledconside.xyz%5E%22%7D

https://awledconside.xyz/RmpoNDEnCAVA

### Describe the issue

I try to block the website : awledconside.xyz
It is blocked by the list EasyList, and also block with filters that i have added :
in **dynamic filters** : 
```
awledconside.xyz * * block
www.awledconside.xyz * * block
```
in **my filters** :
`||awledconside.xyz^`

When i click on a link that try to open this link i always got this window (in screenshot) but when i click on the "dont tell me anymore for this website" the button close this windows is deactivated.
So i think there is a bug as i add the rules to block the site in ublock configuration but it continues to show me the notification of the blocked site and i cant definitively remove this notification.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/59701385/201623540-317b8090-8369-4b99-8c72-06a4fe80921d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 100
filterset (summary): 
  network: 144464
  cosmetic: 188453
  scriptlet: 24875
  html: 820
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware: 39421-16957, 2d.13h.41m
    adguard-annoyance: 60931-5228, 2d.13h.38m
    adguard-social: 18930-1069, 2d.13h.37m
    fanboy-thirdparty_social: 68-0, 8d.19h.35m
    fanboy-annoyance: 82436-66289, 8d.19h.34m
    fanboy-cookiemonster: 42695-163, 8d.19h.33m
    fanboy-social: 23417-28, 5d.3h
    ublock-annoyances: 4802-4, 2d.13h.39m
    adguard-spyware-url: 824-3, 2d.13h.40m
    block-lan: 44-0, 9d.11h.36m
  default: 
    user-filters: 18-2, never
    ublock-filters: 31946-155, 2d.13h.44m
    ublock-badware: 3972-0, 2d.13h.43m
    ublock-privacy: 286-0, 3d.13h.47m
    ublock-abuse: 76-0, 3d.13h.46m
    ublock-unbreak: 1907-2, 2d.13h.42m
    easylist: 64258-712, 1d.17h.33m
    easyprivacy: 30818-1712, 1d.17h.32m
    urlhaus-1: 10191-0, 10h.13m
    plowe-0: 3667-3, 7d.23h.30m
    FRA-0: 30827-438, 2d.13h.45m
    ublock-quick-fixes: 566-0, 10h.12m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2714 ms (selfie)
  maxAssetCacheWait: 1260 ms
```
</details>

**Comment by Yuki2718** [comment]
Do you under stand what is the "dont tell me anymore for this website"? This is to permanently disable strict-blocking and is effective only if you chose Proceed.
