### ISSUE TITLE
[nsfw] bangbros.com: breakage

### ISSUE THREAD

**Issue by Upheaval2950** [uBlockOrigin/uAssets#15679]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bangbros.com/`

### Category

breakage

### Describe the issue

Search wont work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 129532
  cosmetic: 77801
  scriptlet: 29851
  html: 832
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66078-5302, 2m
    adguard-mobile: 8190-147, 2m
    adguard-spyware: 34239-2612, 12m
    adguard-spyware-url: 831-123, 12m
  default: 
    user-filters: 2002-0, never
    ublock-filters: 32012-63, 10m
    ublock-badware: 4007-0, 4m
    ublock-privacy: 286-2, 3m
    ublock-abuse: 76-0, 2m
    ublock-unbreak: 1908-2, 2m
    ublock-quick-fixes: 559-0, 2m
    easylist: 64408-791, 2m
    easyprivacy: 30846-12850, 2m
    urlhaus-1: 11006-0, 2m
    plowe-0: 3670-3, 2m
filterset (user): [array of 2011 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 932 ms
  maxAssetCacheWait: 569 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    bangbros.com: 1
    bangbrosonline.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||metrics.bangbros.com/tk.js$script,1p`

@ryanbr
