### ISSUE TITLE
ikandy.fun: detection

### ISSUE THREAD

**Issue by Mionx-II** [uBlockOrigin/uAssets#15671]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ikandy.fun/vodplay/103810-1-1/`

### Category

detection

### Describe the issue

can't play

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 108917
  cosmetic: 48745
  scriptlet: 16826
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    CHN-0: 28582-86, 1d.18h.41m
    easylist: 64669-84, 1d.18h.38m
    easyprivacy: 30818-1194, 1d.18h.31m
    plowe-0: 3670-871, 1d.18h.36m
    ublock-abuse: 76-0, 1d.18h.34m
    ublock-badware: 3968-109, 1d.18h.29m
    ublock-filters: 31211-130, 1d.18h.28m
    ublock-privacy: 258-1, 1d.18h.27m
    ublock-quick-fixes: 558-14, 1m
    ublock-unbreak: 1896-44, 1d.18h.25m
    urlhaus-1: 11473-0, 1d.18h.24m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 573 ms
  maxAssetCacheWait: 289 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    baidu.com: 2
    bdstatic.com: 1
    netease.com: 1
    toutiao.com: 1
```
</details>

**Comment by mapx-** [comment]
@cjx82630 could you please help here ?

**Comment by cjx82630** [comment]
Try this `mmiyue.com#@#.google-ad:not(.testAd)`

**Comment by Mionx-II** [comment]
thank u so much

**Comment by mapx-** [comment]
@Yuki2718 could you add the filter above to AG chn list ?

**Comment by Yuki2718** [comment]
Where `##.google-ad:not(.testAd)` came from?
