### ISSUE TITLE
cloud-computing-central.com: detection

### ISSUE THREAD

**Issue by furkantnt** [uBlockOrigin/uAssets#15670]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cloud-computing-central.com/using-big-data-to-engender-loyalty/`

### Category

detection

### Describe the issue

Adblock detected this is so boring.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/115404702/201655706-336bc5f0-7518-4c05-b816-e9a457c94ae6.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 90882
  cosmetic: 47100
  scriptlet: 17754
  html: 795
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31921-53, 3d.6h.19m
    ublock-badware: 3972-0, 3d.6h.18m
    ublock-privacy: 285-0, 3d.6h.17m
    ublock-abuse: 76-0, 3d.5h
    ublock-unbreak: 1906-0, 3d.6h.16m
    ublock-quick-fixes: 540-0, 5m
    easylist: 64417-626, 3d.6h.24m
    easyprivacy: 30793-1714, 3d.6h.23m
    urlhaus-1: 10228-0, 4m
    plowe-0: 3670-3, 1d.5h.15m
    TUR-0: 11291-11, 3d.6h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2172 ms
  maxAssetCacheWait: 792 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflareinsights.com: 2
    yieldmo.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
When you got it from a link shortener please pass us the shortened link. `https://cloud-computing-central.com/using-big-data-to-engender-loyalty/` just redirect to `iplogger.org`
