### ISSUE TITLE
examroom.ai: breakage

### ISSUE THREAD

**Issue by escarlson** [uBlockOrigin/uAssets#15675]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://examroom.ai/systemtest/`

### Category

breakage

### Describe the issue

Click `Run Test`, select video and audio sources, then click`Continue`. The test completes all checks, but the Audio Bitrate, Video Bitrate, and Websockets tests are stuck on "Verifying..." The browser console shows

```
POST https://enterprise-hlg.tokbox.com/prod/logging/ClientEvent net::ERR_BLOCKED_BY_CLIENT
POST https://hlg.tokbox.com/prod/logging/ClientEvent net::ERR_BLOCKED_BY_CLIENT
```
When turning off uBO for the site, those console errors disappear and the tests complete successfully.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-14 at 11 25 38](https://user-images.githubusercontent.com/10640906/201737391-9703ff0d-ea02-4c73-86db-b76b0f0df923.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89533
  cosmetic: 38591
  scriptlet: 16710
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64647-52, 2d.11h.30m
    easyprivacy: 30794-1171, 2d.11h.29m
    plowe-0: 3670-868, 21m
    ublock-abuse: 76-0, 23h.23m
    ublock-badware: 4003-109, 11h.21m
    ublock-filters: 31235-112, 11h.20m
    ublock-privacy: 258-1, 23h.22m
    ublock-quick-fixes: 558-14, 7h.18m
    ublock-unbreak: 1895-43, 11h.19m
    urlhaus-1: 10228-0, 7h.17m
filterset (user): [empty]
modifiedUserSettings: 
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 521 ms
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 45
  blockedDetails: 
    tokbox.com: 45
```
</details>

**Comment by mapx-** [comment]
@ryanbr
