### ISSUE TITLE
nytimes.com: nuisance

### ISSUE THREAD

**Issue by CitizenRacer** [uBlockOrigin/uAssets#15674]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nytimes.com/2022/11/14/technology/amazon-layoffs.html`

### Category

nuisance

### Describe the issue

![Screenshot 2022-11-14 at 8 36 09 AM](https://user-images.githubusercontent.com/14790049/201714978-d5f1a888-591d-48fc-96ae-d4f335a04a6c.jpg)

A picture is worth a thousand words. The login prompt renders oddly and blocks reading the article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2022-11-14 at 8 36 09 AM](https://user-images.githubusercontent.com/14790049/201715051-eae603bc-0082-4357-b199-3dfe6264992e.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 58583
  cosmetic: 163251
  scriptlet: 24366
  html: 875
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
    adguard-annoyance: 60994-4273, 2m
    fanboy-annoyance: 82958-267, 2m
    ublock-annoyances: 4806-4, 2m
  default: 
    user-filters: 6-0, never
    ublock-filters: 32013-48, 3m
    ublock-badware: 4007-0, 3m
    ublock-privacy: 305-0, 3m
    ublock-abuse: 76-0, 3m
    ublock-unbreak: 1908-1, 2m
    easylist: 64357-255, 2m
    ublock-quick-fixes: 554-0, 2m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 168 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1831 ms (selfie)
  maxAssetCacheWait: 534 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    nytimes.com: 5
    amazon-adsystem.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
- install the last uBO build from:

https://github.com/gorhill/uBlock/releases/tag/1.45.3b1
- update ALL your filter lists
- disable any other addon in FF
- test again

**Comment by CitizenRacer** [comment]
Works great, thank you.
