### ISSUE TITLE
gamer.no: ads

### ISSUE THREAD

**Issue by hect0rvector** [uBlockOrigin/uAssets#15672]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gamer.no/`

### Category

ads

### Describe the issue

Despite having uBlock installed, this website is still showing ads.
I tried purging the cache, and i tried reisntalling uBlock, but neither worked.
I also did try manually removing ads, but they just reappeares after i refreshed the window.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 89988
  cosmetic: 40544
  scriptlet: 16728
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 40-0, never
    NOR-0: 2818-7, 22h.38m
    easylist: 64280-54, 22h.43m
    easyprivacy: 30818-1172, 22h.42m
    plowe-0: 3669-868, 11d.22h.10m
    ublock-abuse: 76-0, 12d.19h.9m
    ublock-badware: 4003-109, 22h.41m
    ublock-filters: 31208-114, 22h.40m
    ublock-privacy: 260-1, 12d.19h.8m
    ublock-quick-fixes: 541-14, 22h.37m
    ublock-unbreak: 1898-43, 22h.39m
    urlhaus-1: 10191-0, 22h.36m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 329 ms (selfie)
  maxAssetCacheWait: 170 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    adnuntius.com: 1
    bo3.no: 1
    crazyegg.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    k5a.io: 1
    sentry.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
`gamer.no##div[data-track-visibility]` seems like it would work short-term, so I can add it to Nordic Filters right away.

**Comment by JobcenterTycoon** [comment]
I saw your filter `gamer.no##img[src^="blob:"]` already cover a few ads but the ads doesn’t getting hidden by uBlock Origin.

Based on the filter maybe

```
gamer.no##img[src^="blob:"]:remove()
gamer.no##a[style*="blob:"]
```
will be a long term filter?
