### ISSUE TITLE
[nsfw] chan.sankakucomplex.com: ads

### ISSUE THREAD

**Issue by BruhMomient** [uBlockOrigin/uAssets#15677]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://chan.sankakucomplex.com/post/show/4878029`

### Category

ads

### Describe the issue

Animated ads appearing for Sankaku channel.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

NSFW Warning (https://a.pomf.cat/gfvlml.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 309789
  cosmetic: 116711
  scriptlet: 31305
  html: 782
listset (total-discarded, last-updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8730-0, 2d.6h.51m
    adguard-generic: 66267-5438, 2d.22h.35m
    adguard-mobile: 8179-207, 2d.22h.39m
    adguard-spyware: 39421-17141, 2d.22h.38m
    adguard-spyware-url: 824-3, 2d.22h.37m
    curben-phishing: 161529-7, 3h.8m
    curben-pup: 193-0, 3h.10m
    fanboy-cookiemonster: 42661-104, 7d.8h.22m
    dpollock-0: 11390-1635, 10d.22h.47m
  default: 
    user-filters: 0-0, never
    ublock-filters: 31948-64, 2d.22h.36m
    ublock-badware: 3972-1, 2d.22h.34m
    ublock-privacy: 286-0, 18h.36m
    ublock-abuse: 76-0, 18h.35m
    ublock-unbreak: 1907-1, 2d.22h.40m
    easylist: 64280-1053, 1d.22h.48m
    easyprivacy: 30820-2006, 2d.2h.50m
    urlhaus-1: 10645-0, 3h.9m
    plowe-0: 3667-343, 10d.1h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 888 ms (selfie)
  maxAssetCacheWait: 1177 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    sankakucomplex.com: 4
    juicyads.com: 2
    otaserve.net: 20
```
</details>

**Comment by mapx-** [comment]
Only self-promo stuff.
