### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by mattheo2055** [uBlockOrigin/uAssets#15684]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=2a8PgqWrc_4&list=RDZSPdldxe8W0&index=22`

### Category

ads

### Describe the issue

many ads shows up when i surf yt, no ads was shown previously

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 91600
  cosmetic: 46026
  scriptlet: 16910
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7860-8, 14h.41m
    POL-2: 1276-13, 1h.16m
    easylist: 64510-77, 5d.5h.24m
    easyprivacy: 30791-1171, 5d.5h.23m
    plowe-0: 3670-877, 5d.5h.26m
    ublock-abuse: 76-0, 2d.2h.12m
    ublock-badware: 4003-109, 14h.43m
    ublock-filters: 31249-148, 14h.45m
    ublock-privacy: 258-1, 2d.2h.11m
    ublock-quick-fixes: 557-15, 14h.42m
    ublock-unbreak: 1895-44, 14h.44m
    urlhaus-1: 11018-0, 14h.40m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 889 ms (selfie)
  maxAssetCacheWait: 336 ms
popupPanel: 
  blocked: 1081
  blockedDetails: 
    youtube.com: 962
    doubleclick.net: 14
    google.com: 28
    google.pl: 1
    googleadservices.com: 6
    googlesyndication.com: 60
    googlevideo.com: 10
```
</details>

**Comment by liamengland1** [comment]
`[x] I did not answer truthfully to all the above checkpoints`

**Comment by mapx-** [comment]
Reset uBO, update all the filter lists, don't add any other list, disable any other extension / addon in your browser, disable (if any) the web shields in your antivirus / antimalware software / other blocking software, restart the system, reopen the browser, test again

duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
see see https://github.com/easylist/easylist/wiki/Youtube-Issues
