### ISSUE TITLE
onedrive.live.com: breakage

### ISSUE THREAD

**Issue by privetyaroma** [uBlockOrigin/uAssets#15687]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://onedrive.live.com/`

### Category

breakage

### Describe the issue

File section become empty while using ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ublock:

![image](https://user-images.githubusercontent.com/96735916/202171081-669f1ccb-a39a-4e51-b84c-d483e48eb40c.png)
Without ublock:

![image](https://user-images.githubusercontent.com/96735916/202171125-b8371bdb-1976-42f3-b344-85ba94cd88f8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 121526
  cosmetic: 209105
  scriptlet: 25734
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31560-26, now
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1534-24, now
    adguard-annoyance: 61058-1268, now
    adguard-social: 18974-1803, now
    fanboy-annoyance: 82968-25520, now
    fanboy-cookiemonster: 43070-43023, now
    fanboy-social: 23422-23422, now
    ublock-annoyances: 4783-206, now
  default: 
    user-filters: 0-0, never
    RUS-0: 39669-147, now
    easylist: 64689-140, now
    easyprivacy: 30850-1610, now
    plowe-0: 3673-879, now
    ublock-abuse: 76-1, now
    ublock-badware: 4003-108, now
    ublock-filters: 31258-527, now
    ublock-privacy: 258-9, now
    ublock-quick-fixes: 568-14, now
    ublock-unbreak: 1895-48, now
    urlhaus-1: 11010-0, now
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1187 ms
  maxAssetCacheWait: 592 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    azure.com: 2
    microsoft.com: 6
    sfx.ms: 3
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
already fixed by EasyPrivacy, update all your filter lists

**Comment by PRMyx** [comment]
This issue is happening again. May I know if there is a workaround to this?
