### ISSUE TITLE
news.ycombinator.com: ads

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#15681]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://news.ycombinator.com/`

### Category

ads

### Describe the issue

Advertising lines that do not have authors and comments.

```
news.ycombinator.com##table > tbody > .athing:has(+ tr > .subtext > .age + a)
news.ycombinator.com##table > tbody > .athing + tr:has(> .subtext > .age + a)
news.ycombinator.com##table > tbody > .athing + tr:has(> .subtext > .age + a) + .spacer
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![news hacker](https://user-images.githubusercontent.com/20126984/201985681-b2703e11-e1d8-4c26-9b9e-5d4524ddf647.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b1
Chromium: 107
filterset (summary): 
  network: 107200
  cosmetic: 59797
  scriptlet: 17924
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39665-11, now
    easylist: 64413-67, now
    easyprivacy: 30846-1283, now
    plowe-0: 3671-874, now
    ublock-abuse: 76-1, now
    ublock-badware: 4003-108, now
    ublock-filters: 31240-143, now
    ublock-privacy: 258-1, now
    ublock-quick-fixes: 557-14, now
    ublock-unbreak: 1895-43, now
    urlhaus-1: 11018-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2471 ms
  maxAssetCacheWait: 362 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ryanbr** [comment]
I don't think its a good idea, false positives and likely breakage its not worth the webcompat reports
