### ISSUE TITLE
onlinesaprevodom.net: popups

### ISSUE THREAD

**Issue by Fenivan** [uBlockOrigin/uAssets#15683]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://onlinesaprevodom.net/`

### Category

popups

### Describe the issue

Amost everywhere I click on this website when chosing a tv show or movie to watch it opens up new window which usually loads either crypto ad (just opens random crypto website) or online gambling/casino website.

It looks like new windows are just normal ad popups/redirections and **I have to specify I do use "block all popups on this site" option but it still doesn't work or website somehow bypass that**.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 101655
  cosmetic: 162773
  scriptlet: 24358
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 60935-93, 3d.4h.21m
    fanboy-annoyance: 82475-3816, 7d.4h.40m
    ublock-annoyances: 4778-201, 3d.4h.19m
  default: 
    user-filters: 21-1, never
    easylist: 64280-110, 1d.2h.24m
    easyprivacy: 30822-1259, 1d.2h.23m
    plowe-0: 3668-869, 7d.4h.40m
    ublock-abuse: 76-0, 3d.4h.20m
    ublock-badware: 3968-108, 3d.4h.18m
    ublock-filters: 31212-490, 3d.4h.17m
    ublock-privacy: 258-9, 3d.4h.16m
    ublock-quick-fixes: 557-14, 3h.24m
    ublock-unbreak: 1896-49, 3d.4h.15m
    urlhaus-1: 11018-0, 3h.23m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 852 ms (selfie)
  maxAssetCacheWait: 459 ms
popupPanel: 
  blocked: 34
  no-popups: true
  blockedDetails: 
    addtoany.com: 1
    alleviatepracticableaddicted.com: 3
    betteradsystem.com: 1
    cloudflareinsights.com: 1
    commentsengine.com: 3
    d2kk0o3fr7ed01.cloudfront.net: 1
    googletagmanager.com: 1
    highperformancegate.com: 1
    hqq.to: 3
    profitablegatetocontent.com: 1
    testingmetriksbre.ru: 3
    yadro.ru: 3
    yandex.ru: 3
    zap.buzz: 9
```
</details>

**Comment by liamengland1** [comment]
`onlinesaprevodom.net##+js(aopw, _pop)`
