### ISSUE TITLE
movielab.im: breakage

### ISSUE THREAD

**Issue by kosmosnya** [uBlockOrigin/uAssets#15680]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://movielab.im/`

### Category

breakage

### Describe the issue

The site does not load when the ad blocker is enabled. Disabling the ad blocker solves the problem with page loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 106828
  cosmetic: 59759
  scriptlet: 17916
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39657-10, 19h.34m
    easylist: 64422-64, 5d.6h
    easyprivacy: 30787-1283, 5d.5h.59m
    plowe-0: 3668-872, 5d.6h.1m
    ublock-abuse: 76-1, 6d.21h.32m
    ublock-badware: 4003-109, 19h.36m
    ublock-filters: 31249-139, 19h.35m
    ublock-privacy: 257-1, 5d.6h.3m
    ublock-quick-fixes: 557-14, 19h.32m
    ublock-unbreak: 1895-43, 19h.37m
    urlhaus-1: 10645-0, 19h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 198 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    vb17121coramclean.pw: 11
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList are you able to reproduce the issue ?

**Comment by dimisa-RUAdList** [comment]
The problem with this site was earlier, three weeks ago. Then a fix was added: https://github.com/easylist/ruadlist/commit/e576dabcdeb23a1bcab82052240c9c3a8e651eba

If some new problem has arisen now, then the logger data will help to figure it out.
