### ISSUE TITLE
[nsfw] classroom.google.com: breakage

### ISSUE THREAD

**Issue by cajasd** [uBlockOrigin/uAssets#15693]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://classroom.google.com/h`

### Category

breakage

### Describe the issue

d

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 17748
  cosmetic: 5242
  scriptlet: 267
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easylist: null
    easyprivacy: null
    ublock-abuse: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
  default: 
    user-filters: 3-0, never
    plowe-0: 3673-0, 1h.32m
    spa-0: 3368-0, 1h.37m
    spa-1: 4849-120, 1h.37m
    urlhaus-1: 11484-0, 1h.23m
filterset (user): [array of 3 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6514 ms
  maxAssetCacheWait: 969 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by iam-py-test** [comment]
@cajasd you have heavily modified the uBo settings. Please reset uBo to default settings and test again.
