### ISSUE TITLE
dantoo.net block breaks 

### ISSUE THREAD

**Issue by dann2g** [uBlockOrigin/uAssets#15696]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://stardewids.com/contact
https://commands.gg/vic2/blog/console-help
```

### Describe the issue

Fix #15615 breaks features across other websites that access the `dantoo.net` API.

Example:
Submitting contact form at `https://stardewids.com/contact`
"Report a Problem" button on `https://commands.gg/vic2/blog/console-help`

### uBlock Origin version

1.44.4

### Browser name and version

Chrome 107.0.5304.107

### Settings

uBlock Origin default

### Notes

To fix this, only block `https://api.dantoo.net/v1/site-takeover` (this is where the ads are served from)

**Comment by mapx-** [comment]
test these filters

```
stardewids.com##body:style(background-image:none !important)
stardewids.com##+js(aeld, , document.body)
||dantoo.net^$3p,badfilter
```
