### ISSUE TITLE
welt.de: ads

### ISSUE THREAD

**Issue by Isolator70** [uBlockOrigin/uAssets#15698]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.welt.de/geschichte/article242185907/Geheimdienst-Sie-waren-die-Frauen-mit-der-Lizenz-zum-Toeten.html`

### Category

ads

### Describe the issue

Up to now there was no ads prior the start of a video clip - but now it is.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ksnip_20221117-174750](https://user-images.githubusercontent.com/35434137/202507245-177b54cd-2d96-414f-8b37-d941e26ce462.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 93055
  cosmetic: 42422
  scriptlet: 16711
  html: 851
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32014-55, 1d.3h.54m
    ublock-badware: 4007-0, 1d.3h.53m
    ublock-privacy: 305-0, 7h
    ublock-abuse: 76-0, 6h.59m
    ublock-unbreak: 1909-1, 1d.3h.52m
    easylist: 64689-618, 1d.3h.51m
    easyprivacy: 30850-1721, 1d.3h.50m
    plowe-0: 3673-3, 6h.57m
    DEU-0: 6021-2, 1h.22m
    urlhaus-1: 11492-0, 1h.23m
    ublock-quick-fixes: 565-0, 1h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7913 ms
  maxAssetCacheWait: 2062 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    welt.de: 10
    adnxs.com: 3
    asadcdn.com: 2
    bitmovin.com: 1
    chartbeat.com: 1
    cxense.com: 8
    demdex.net: 1
    doubleclick.net: 1
    facebook.net: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    kameleoon.eu: 4
    nmrodam.com: 2
    outbrain.com: 9
    taboola.com: 5
    vgwort.de: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Test `welt.de##+js(set, CustomEvent, noopFunc)`

**Comment by okiehsch** [comment]
I don't see any breakage.

**Comment by Isolator70** [comment]
Works again - great and many thanks!
