### ISSUE TITLE
[nsfw] blocked.goguardian.com: privacy

### ISSUE THREAD

**Issue by catterpillor** [uBlockOrigin/uAssets#15699]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blocked.goguardian.com/?ctx=YWZpPTE2MjMwMzkmYXBpPTEwNTI0OSZvaT0yNzUyMDk2NzU2NCZvdT1odHRwJTNBJTJGJTJGbW9vbW9vLmlvJTJGJnJzPUFETUlOX1NJVEVfQ0FURUdPUllfRklMVEVSJnNjaT0zJnN0PWNocm9taXVtLW0mdj0x&sum=6b05f599`

### Category

privacy

### Describe the issue

GoGaurdian is a basically a (legal) virus so I'm trying to get rid of it, hence the new adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 88426
  cosmetic: 38317
  scriptlet: 16587
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62416-192, never
    easyprivacy: 30822-1147, never
    plowe-0: 3671-868, never
    ublock-abuse: 76-0, never
    ublock-badware: 3943-0, never
    ublock-filters: 31097-150, never
    ublock-privacy: 260-0, never
    ublock-quick-fixes: 424-0, never
    ublock-unbreak: 1873-29, never
    urlhaus-1: 11291-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1770 ms
  maxAssetCacheWait: 37 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
- duplicate
- however it's a spyware installed by your school and cannot be defeated by an extension

**Comment by krystian3w** [comment]
Try use something like Zenmate VPN if possible install custom addons from Chrome Web Store.

Maybe app no protect proxy settings and Teacher don't see this in real time or in logs after days.
