### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by RailuT** [uBlockOrigin/uAssets#15694]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

I have since a week again advertising on Twitch, only comes a picture with "Commercial break" and the countdown does not count right.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 92720
  cosmetic: 42430
  scriptlet: 16701
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6021-0, 45m
    easylist: 64410-58, 1d.19h.21m
    easyprivacy: 30846-1181, 1d.19h.20m
    plowe-0: 3670-870, 4d.18h.47m
    ublock-abuse: 76-0, 5d.12h.22m
    ublock-badware: 3968-108, 3d.21h.45m
    ublock-filters: 31212-123, 3d.21h.44m
    ublock-privacy: 258-1, 5d.12h.21m
    ublock-quick-fixes: 569-14, 44m
    ublock-unbreak: 1898-46, 3d.21h.43m
    urlhaus-1: 11484-0, 43m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 350 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 6
    sentry.io: 1
    ttvnw.net: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see what to do: https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
