### ISSUE TITLE
dl-protect.net: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15695]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dl-protect.net/13a1a500?fn=VG91cyBJbmNvbm51cyBbV0VCLURMIDcyMHBdIC0gRlJFTkNI&rl=a2`

### Category

breakage

### Describe the issue

The check always fails.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/202432342-a45b9b28-d2ca-4311-9e47-5beb2c532047.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 487565
  cosmetic: 149808
  scriptlet: 36103
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 1980-2, never
    FRA-0: 30908-40, 6h
    easylist: 64282-1033, 4d.6h.1m
    easyprivacy: 30822-12888, 4d.6h.1m
    plowe-0: 3670-1055, 4d.6h.1m
    ublock-abuse: 76-2, 5h.50m
    ublock-badware: 4003-259, 5h.46m
    ublock-filters: 31259-3440, 5h.44m
    ublock-privacy: 258-45, 5h.42m
    ublock-quick-fixes: 569-37, 15h.36m
    ublock-unbreak: 1895-97, 5h.39m
    urlhaus-1: 10899-6, 15h.34m
filterset (user): [array of 2102 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 604 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    dl-protect.net: 1
    d1g4493j0tcwvt.cloudfront.net: 2
    dbriolenproce.xyz: 1
    pogothere.xyz: 2
    redanludb.xyz: 4
```
</details>

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/202439357-328c4290-fc8a-4ebd-a2ee-cfe7a8a2d977.png)

Works fine on my end.

**Comment by krystian3w** [comment]
Backup uBo configuration and reset to stock (malformed trusted list and firewall rules).

Secondly bug is in Adhuard French or daily copied "FR Listé" as base.

**Comment by Yuki2718** [comment]
> ```yaml
> removed: 
>     about-scheme
>     chrome-extension-scheme
>     chrome-scheme
>     edge-scheme
>     moz-extens
> ```

> ```yaml
> switchRuleset: 
>   added: [array of 3 redacted]
>   removed: 
>     no-large-media: behind-the-scene false
> hostRuleset: 
>   removed: 
>     behind-the-scene * * noop
>     behind-the-scene * image noop
>     behind-the-scene * 3p noop
>     behind-the-scene * inline-script noop
>     behind-the-scene * 1p-script noop
>     behind-the-scene * 3p-script noop
>     behind-the-scene * 3p-frame noop
> ```

It looks as if you want to break staff by yourself.

**Comment by krystian3w** [comment]
uBo Dashboard ➡️ Trusted sites (Sites Web fiables) / My rules (Mon filtrate dynamique).

Sometimes enough fast missclick (hard to reproduce later).
