### ISSUE TITLE
skroutz.gr: detection

### ISSUE THREAD

**Issue by pavlaras** [uBlockOrigin/uAssets#15697]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.skroutz.gr/`

### Category

detection

### Describe the issue

skroutz is a marketplace similar to amazon for example. adblock detection blocks the stores from showing up in product search

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 90946
  cosmetic: 39157
  scriptlet: 16711
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    GRC-0: 1002-0, 3h.52m
    easylist: 64332-57, 2d.7h.57m
    easyprivacy: 30826-1171, 3d.8h
    plowe-0: 3668-868, 9d.3h.47m
    ublock-abuse: 76-0, 9d.3h.46m
    ublock-badware: 4003-108, 3d.7h.59m
    ublock-filters: 31235-113, 3d.7h.58m
    ublock-privacy: 257-1, 9d.3h.45m
    ublock-quick-fixes: 569-14, 3h.51m
    ublock-unbreak: 1898-45, 3d.7h.57m
    urlhaus-1: 11484-0, 3h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 329 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    skroutz.gr: 1
    facebook.net: 1
    google-analytics.com: 3
    googletagmanager.com: 1
    hotjar.com: 1
```
</details>

**Comment by mapx-** [comment]
- provide step by step indications
- do I need an account to reproduce the issue ?

**Comment by geoleven** [comment]
I have seen it happen too, not on all products though.
I have an example but the product info is sensitive so I may include one in the future.
I am registered and logged in. 
The whole idea of the site is a price comparison and I would suppose that after some late changes they implemented this specifically to push users not to use ad blockers on the site as they have been trying to show firstly sponsored stores.
When it happens if you reload it happens again and for a split second while loading also shows the correct product (then removes it). This is why I suppose it is made in purpose. It also shows a message that because you are using an ad blocker you may be seeing wrong results (implying the ad blocker makes it not work).

**Comment by mapx-** [comment]
- provide screenshots with those messages
- keep only uBO enabled, disable any other extension
- open the logger, repeat the steps to get the issue
- go back in the logger and post here all the blocked requests (you can select only the blocked requests in the search box of the logger)

**Comment by skagon** [comment]
Still happening here. (No "messages" as a previous user reported) Please re-open.
![skroutz ublock issue 01](https://github.com/uBlockOrigin/uAssets/assets/1195307/44f2b81c-bb06-4d4d-8a0c-63f5680311bc)

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|analytics.skroutz.gr^ | -- | `www.skroutz.gr` | 1 | get | script | `https://analytics.skroutz.gr/analytics.min.js` |
| +1 | \|\|googleapis.com^*/gen_204? | -- | `www.skroutz.gr` | 3 | get | xhr | `https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true` |
</details>

**Comment by mapx-** [comment]
@skagon 

provide step by step how to get your issue

I visited
`https://www.skroutz.gr/s/22565111/Roller-Kappatos-00673-Adjustable-Inox-Base-for-Home-Appliances-with-Wheels-2pcs.html`

what should I see ?

**Comment by skagon** [comment]
Confirmed. Many thanks @MasterKia !
