### ISSUE TITLE
spanishdict.com: detection

### ISSUE THREAD

**Issue by KyceAbdallah** [uBlockOrigin/uAssets#15690]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

[](https://www.spanishdict.com/)

### Category

detection

### Describe the issue

It detects UBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/90739617/202318445-3a10fafa-668b-4f29-919f-75f4a8e24d5f.png

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 89887
  cosmetic: 38610
  scriptlet: 16703
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 5-0, never
    easylist: 64359-53, 1d.21h.20m
    easyprivacy: 30822-1171, 1d.21h.23m
    plowe-0: 3670-869, 1d.21h.24m
    ublock-abuse: 76-0, 5d.9h.2m
    ublock-badware: 3968-108, 3d.6m
    ublock-filters: 31211-112, 3d.5m
    ublock-privacy: 257-1, 5d.9h.1m
    ublock-quick-fixes: 568-14, 4h.59m
    ublock-unbreak: 1895-43, 3d.4m
    urlhaus-1: 10899-0, 4h.58m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2052 ms (selfie)
  maxAssetCacheWait: 1725 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    spanishdict.com: 1
    amazon-adsystem.com: 1
    d1q4kshf6f0axi.cloudfront.net: 2
    d325guje460pxh.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 2
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    mxpnl.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`, see if helps.
If doesn't => provide the steps to get the detection (also if needing an account etc)

**Comment by ghajini** [comment]
needs account (can use google)
![image](https://user-images.githubusercontent.com/20338483/202472882-e82f7d53-d4a4-41e7-83af-19b70fe2bab8.png)
by `https://d1q4kshf6f0axi.cloudfront.net/main/prebid-min-2022.js`

`spanishdict.com##+js(set, sd_adBlockDetector, {})`

is this to be in annoyance sec?

**Comment by okiehsch** [comment]
Can you decline? 
If not it should be in the main list.

**Comment by ghajini** [comment]
can't decline
its bait request
so need to use @@||d1q4kshf6f0axi.cloudfront.net/main/prebid-min-2022.js$script,domain=spanishdict.com

**Comment by okiehsch** [comment]
I don't have an account, allowing that script is fine.
