### ISSUE TITLE
Need a bypass for BlockAdBlock on Business Insider

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#157]
### URL(s) where the issue occurs

http://www.businessinsider.com/electric-car-sales-decline-2016-10

### Describe the issue

When visiting pages on Business Insider with ad blocking enabled, the site detects it and prevents reading the article.

### Screenshot(s)

http://prnt.sc/crsixl

### Versions

- Browser/version: Mozilla Firefox 49.0 and Google Chrome 53.0.2785.143
- uBlock Origin version: 1.9.12 on Firefox, 1.9.10 on Chrome

### Settings

- None. (I was able to reproduce this in a fresh Firefox profile with no settings changes at all.)

### Notes

This is where the adblocker gets detected in the page source (I haven't found what reads the cookie to trigger the message though):
```
    <!-- detect adblock users for Piano and set cookie appropriately -->
    <script> 
    var setAdblockerCookie = function(adblocker) {
        var d = new Date();
        d.setTime(d.getTime() + 60 * 60 * 24 * 30 * 1000);
        document.cookie = "__adblocker=" + (adblocker ? "true" : "false") + "; expires=" + d.toUTCString() + "; path=/";
    }
    var script = document.createElement("script");
    script.setAttribute("async", true);
    script.setAttribute("src", "//www.npttech.com/advertising.js");
    script.setAttribute("onerror", "setAdblockerCookie(true);");
    script.setAttribute("onload", "setAdblockerCookie(false);");
    document.getElementsByTagName("head")[0].appendChild(script);
    </script>
```
This rule appears to make the message stop happening:
```
businessinsider.com##script:inject(setTimeout-defuser)
```
However, this feels like using a bazooka to kill a fly. IMO, something else like a custom inject would be a better way of fixing this.

**Comment by gorhill** [comment]
I got the warning when I first visited, but now I can't get it anymore -- restarting the browser, clearing cookies, etc. to no avail.

Was the warning just removed from the site?

This is not _BlockAdBlock_ by the way.

**Comment by josephcsible** [comment]
I just tried again in Firefox and Chrome (without doing anything special) and I still get it in both. Also, http://www.npttech.com/advertising.js contains the following line, which led me to believe that this was BlockAdBlock:
```
e.prototype._log=function(t,e){console.log("[BlockAdBlock]["+t+"] "+e)}
```

**Comment by gorhill** [comment]
> I still get it in both

Try:

    businessinsider.com##.tp-modal
    businessinsider.com##.tp-backdrop
    businessinsider.com##body:style(overflow: auto !important)

**Comment by gorhill** [comment]
Note that my inability to reproduce occurred right after I forced an update of EasyList. So I see now a network request, `http://www.npttech.com/advertising.js`, which is no longer blocked because of this EasyList filter: `@@||npttech.com/advertising.js$script`.

By the look of the excepted script, it appears to be FuckAdblock. See if this works on your side (remove the cosmetic filters above):

    ||npttech.com/advertising.js$important,script,redirect=fuckadblock.js-3.2.0,domain=businessinsider.com

**Comment by josephcsible** [comment]
Both of those solutions work (tested one at a time, not both at once).

**Comment by gorhill** [comment]
I will go with a modified version of the second solution, blocking network requests to 3rd-party has priority over cosmetic filtering.

**Comment by josephcsible** [comment]
I looked at this again, and since it calls the "no adblock detected" method in the inline onload, it looks like noopjs would work in place of fuckadblock.js-3.2.0. Indeed, the following does also work:
```
||npttech.com/advertising.js$important,script,redirect=noopjs,domain=businessinsider.com
```

**Comment by gorhill** [comment]
Yes but according to this [EasyList commit](https://github.com/easylist/easylist/commit/8f7929b19ecfa92b51ddc698bc0864214528a334#diff-3273f30ed059f45393695f577a121718), not all clients of this script may just test for load error.

**Comment by vebekebuz** [comment]
have you seen this? https://uponit.com/ they are claiming they can [bypass adblock](https://uponit.com/)

**Comment by SMed79** [comment]
@vebekebuz Do you have an example site ?

**Comment by okiehsch** [comment]
#185

**Comment by gorhill** [comment]
`upManager` is related to them? If so, #251 would also be related.

**Comment by okiehsch** [comment]
Yes `upManager` seems to be related. 
For example `calcalist.co.il` and `freewarefiles.com` have `Uponit`  in  their source codes and 
`upManager` is also a part in both.

**Comment by confider** [comment]
I know this issue's closed, but neither of the solution from above works now for businessinsider(dot)com. However, the following works for me. Can anyone else reproduce?

```
businessinsider.com##script:inject(set-constant.js, _PIANO.setAdblockerCookie, noopFunc)
businessinsider.com##script:inject(set-constant.js, setAdblockerCookie, noopFunc)
@@||static.clmbtech.com^$script,domain=businessinsider.in
```
