### ISSUE TITLE
urlcloud.us [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#1570]
URL(s) where the issue occurs

`https://urlcloud.us/FpNR41A4`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
fill the Captcha and then continue link

**Comment by KiLL4FuNK** [comment]
Pop-up fill the Captcha and then continue link  `https://urlcloud.us/SrCi` @mapx-
