### ISSUE TITLE
slovnik.aktuality.sk: ads

### ISSUE THREAD

**Issue by vargzum** [uBlockOrigin/uAssets#15706]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://slovnik.aktuality.sk/synonyma/?q=zabi%C5%A5`

### Category

ads

### Describe the issue

Ads do not appear, but a significant portion of the screen is covered by an empty rectangle that says "Reklama" ("Ad" in Slovak)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![synonymickyslovnik](https://user-images.githubusercontent.com/118548746/202738063-75f5e7f6-438f-495d-affe-7d932f25096b.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92343
  cosmetic: 38942
  scriptlet: 16869
  html: 832
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32012-44, 2d.23h.52m
    ublock-badware: 4007-0, 2d.23h.51m
    ublock-privacy: 288-0, 12d.4h.49m
    ublock-abuse: 76-0, 8d.22h.39m
    ublock-unbreak: 1908-1, 2d.23h.50m
    ublock-quick-fixes: 565-0, 2h.19m
    easylist: 64280-598, 4d.19h.52m
    easyprivacy: 30820-1730, 5d.20h.55m
    urlhaus-1: 13167-0, 2h.18m
    plowe-0: 3670-3, 7d.20h.38m
    CZE-0: 731-0, 2h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 488 ms (selfie)
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    aktuality.sk: 2
    aimg.sk: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    pubmatic.com: 1
```
</details>

**Comment by mapx-** [comment]
`slovnik.aktuality.sk##.desktop-wrapper:has([id^="div-gpt-ad"])`

@addisr

@vargzum did you try reporting here:
https://github.com/tomasko126/easylistczechandslovak/issues
