### ISSUE TITLE
fifa.com: ads

### ISSUE THREAD

**Issue by BrunaPitanga** [uBlockOrigin/uAssets#15704]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fifa.com/fifaplus/en/watch/1PWVyYB9n0irNo8j8ndgTL`

### Category

ads

### Describe the issue

Ads are played before the videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://user-images.githubusercontent.com/115604365/202702090-de4e557e-3062-47cf-b3ee-58c5a903df89.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92608
  cosmetic: 38632
  scriptlet: 16716
  html: 852
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32017-130, 1m
    ublock-badware: 4007-0, 1m
    ublock-privacy: 305-0, 1m
    ublock-abuse: 76-0, 1m
    ublock-unbreak: 1908-1, 1m
    ublock-quick-fixes: 575-0, 1m
    easylist: 64762-532, 1m
    easyprivacy: 30854-1711, 1m
    urlhaus-1: 13167-0, 1m
    plowe-0: 3675-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6438 ms
  maxAssetCacheWait: 409 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    adobedtm.com: 2
    conviva.com: 2
    visualstudio.com: 2
```
</details>

**Comment by mapx-** [comment]
Test

`||uplynk.com/*preplay$removeparam=ad`
