### ISSUE TITLE
player.pl: detection

### ISSUE THREAD

**Issue by briantwg** [uBlockOrigin/uAssets#15702]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://player.pl/`

### Category

detection

### Describe the issue

Ublock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90497
  cosmetic: 38602
  scriptlet: 16710
  html: 832
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32012-44, 2d.12h.7m
    ublock-badware: 4007-0, 2d.12h.6m
    ublock-privacy: 286-0, 3d.9h.7m
    ublock-abuse: 76-0, 3d.9h.6m
    ublock-unbreak: 1908-1, 2d.12h.5m
    ublock-quick-fixes: 565-0, 7h.28m
    easylist: 64330-612, 3d.5h.5m
    easyprivacy: 30826-1708, 4d.1h.55m
    urlhaus-1: 11492-0, 7h.27m
    plowe-0: 3668-3, 10d.13h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 494 ms (selfie)
  maxAssetCacheWait: 64 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    adform.net: 1
    adocean.pl: 5
    adpone.com: 1
    creativecdn.com: 1
    criteo.com: 1
    criteo.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    litix.io: 3
    newrelic.com: 1
    smartadserver.com: 1
```
</details>

**Comment by mapx-** [comment]
polish site, add both polish lists, test again

**Comment by krystian3w** [comment]
Also homepage no have anti-adblock detection.

**Comment by mapx-** [comment]
tested @krystian3w link
`https://player.pl/seriale-online/skazana-odcinki,31908`

still no detection / no video ads

**Comment by krystian3w** [comment]
On my browser anti-adblock back after cleaning cookies for `*.player.pl` domain (paid content and long demo free treaser for logged user).

Also in Mozilla containers possible glitch page by open in many tabs same/different video.

Maybe @lain566 write new json-prune.

Also no longer works aeld to recover right click menu.

**Comment by briantwg** [comment]
it was happening when try to play videos and to replicate the issue need to create a account. thanks

**Comment by mapx-** [comment]
@briantwg did you add the polish lists ?

**Comment by krystian3w** [comment]
On my side started detection with enabled POL-0 and POL-2.

Maybe page need clear data for many domains, then better move this to different profile (`about:profiles`) to avoid lost "remember login" on other portals.

**Comment by briantwg** [comment]
> 

i tried with default settings and POL list ticked. but its still detecting

**Comment by krystian3w** [comment]
For my disable Firefox shield nothing changed (default session and blue "work" container blocked from use).

**Comment by krystian3w** [comment]
But Firefox containers and option to clear data at domains is not built in content blocker - this needs investigate what code detect use containers or detect glitch in cookies/local storage/sessionStorage.
