### ISSUE TITLE
hsbc.co.uk: breakage

### ISSUE THREAD

**Issue by JonnyTech** [uBlockOrigin/uAssets#15708]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hsbc.co.uk/security/`

### Category

breakage

### Describe the issue

Go to `https://www.hsbc.co.uk/online/dashboard/`
Auto redirects to `https://www.hsbc.co.uk/security/auth.auth.external`
Page does not load
The count in the UBO icon leeps going up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92125
  cosmetic: 38600
  scriptlet: 16711
  html: 833
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32017-33, 2h.41m
    ublock-badware: 4007-0, 2h.40m
    ublock-privacy: 286-0, 4d.11h
    ublock-abuse: 76-0, 4d.10h.59m
    ublock-unbreak: 1908-0, 2h.39m
    ublock-quick-fixes: 565-12, 18h.31m
    easylist: 64278-253, 4d.10h.56m
    easyprivacy: 30826-1200, 4d.10h.55m
    urlhaus-1: 13167-0, 18h.30m
    plowe-0: 3670-872, 4d.10h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 366 ms (selfie)
  maxAssetCacheWait: 222 ms
popupPanel: 
  blocked: 192
  blockedDetails: 
    hsbc.co.uk: 104
    ads-twitter.com: 1
    amazon-adsystem.com: 1
    appdynamics.com: 1
    contentsquare.net: 5
    doubleclick.net: 1
    eum-appdynamics.com: 2
    facebook.net: 1
    googletagmanager.com: 1
    linkedin.com: 1
    tealiumiq.com: 1
    tiqcdn.com: 1
    we-stats.com: 72
```
</details>

**Comment by mapx-** [comment]
I guess an account is required.
However test these filters

```
@@||tags.tiqcdn.com/utag/hsbc/uk-rbwm-gsp/prod/utag.sync.js$script,domain=hsbc.co.uk
@@||cdn.appdynamics.com/adrum-ext.$script,domain=hsbc.co.uk
```

**Comment by JonnyTech** [comment]
Thanks @mapx-  I do have an account but cannot get to the login screen.

This is my first time testing, can you explain how to use your commands please?

**Comment by mapx-** [comment]
click uBO icon, click the last icon on the right at the bottom, open the dashboard, go into "my filters" tab, add the filter above, click "apply changes", test it

**Comment by JonnyTech** [comment]
Thank you, the `tiqcdn.com` filer worked perfectly.

**Comment by mapx-** [comment]
@ryanbr
