### ISSUE TITLE
filehippo.*, softonic.*: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#15700]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://filehippo.com/download_rufus/`
`https://microsoft-word.softonic.nl/`
(often prompt Avast)

`https://filehippo.pl/download_rufus/`
(often prompt Opera)

### Describe the issue

Annoyance pop-up stop process to download app, needed remove dom or scriptlet to don't break page.

Other if Opera/Avast possible mark here as self-promo (then recopy to AdGuard Filters).

### Screenshot(s)

<details><summary>Filehippo.com:</summary>

![obraz](https://user-images.githubusercontent.com/35370833/202544505-a5ae98e5-9c97-4b5c-a4cc-a54c5b848e19.png)

</details><details><summary>Filehippo.pl:</summary>

![obraz](https://user-images.githubusercontent.com/35370833/202542650-a5644715-1e15-4426-8cf6-a8b8698932fe.png)

</details><details><summary>Softonic.nl:</summary>

![obraz](https://user-images.githubusercontent.com/35370833/202548175-f2463fd1-4e67-4157-911c-20223f641036.png)

</details>

### uBlock Origin version

1.45.3b4

### Browser name and version

Firefox 108

### Settings

Added:

- POL 0
- POL 2
- uBO: Annoyances

### Notes

```adb
filehippo.*,softonic.*###modal-di-avast:remove()
filehippo.*,softonic.*###modal-di-opera:remove()
```

or scriptlet if not moved to own file (script/xhr request compatible with Adblock Plus).

Similar is defended on Softonic mother page: `https://utorrent.en.softonic.com/` https://github.com/uBlockOrigin/uAssets/issues/13917 (also possible use `##+js(aeld, , [native code])` if page have lack of use "native code").

I don't see any other "self-promo" sponsors to favor `aeld` if someone updated uBO to supported version with `:remove()`.

**Comment by mapx-** [comment]
the filters above don't work for `filehippo`

**Comment by mapx-** [comment]
for filehippo maybe:

`||filehippo.com/revamp.js$script,1p`

**Comment by krystian3w** [comment]
Or maybe:

```adb
filehippo.com,filehippo.de,filehippo.jp##.rv-di-modal:has(img[src*="opera"], img[src*="avast"]):remove()
```

I see only DE, PL, JP have own public suffix.

**Comment by krystian3w** [comment]
@peace2000 Can you look how avoid use `trusted-set-cookie`:

<img width="1215" height="238" alt="Image" src="https://github.com/user-attachments/assets/f4c423a4-ab37-4221-a59e-496545dce067" />

```adb
filehippo.pl##+js(trusted-set-cookie, euconsent-v2, CP2KIMAP2KIMAAHABBENAcEgAAAAAAAAAAiQAAAAAAEEoAMAARBqDQAYAAiDUKgAwABEGopABgACINQ6ADAAEQaiEAGAAIg1BIAMAARBqGQAYAAiDUAA.YAAAAAAAAAAA, 1year, , domain, filehippo.pl)
```

`https://filehippo.pl/download_18513-4-75547775/`

**Comment by peace2000** [comment]
@krystian3w  https://github.com/uBlockOrigin/uAssets/commit/37137aaaace41aa208053f0e264964c954cff0c0
