### ISSUE TITLE
poipiku.com: nuisance 

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15701]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://poipiku.com/1730391/6923507.html`
`https://poipiku.com/MyHomePcV.jsp`
`https://poipiku.com/NewArrivalPcV.jsp` (NSFW possible)
`https://poipiku.com/PopularTagListPcV.jsp` (NSFW possible)
`https://poipiku.com/RandomPickupPcV.jsp` (NSFW possible)
`https://poipiku.com/PopularIllustListPcV.jsp` (NSFW possible)

Last four links have dynamic user content, rating unknown.

### Describe the issue

Context menu, drag and copy are disabled

### Notes

Tested with and without uBlock Annoyances

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90930
  cosmetic: 38627
  scriptlet: 16713
  html: 852
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32021-44, now
    ublock-badware: 4007-0, now
    ublock-privacy: 305-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1908-1, now
    ublock-quick-fixes: 566-0, now
    easylist: 64757-618, now
    easyprivacy: 30854-1711, now
    urlhaus-1: 11492-0, now
    plowe-0: 3674-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1818 ms
  maxAssetCacheWait: 243 ms
```
</details>

**Comment by krystian3w** [comment]
Right, locked:

```html
		<script type="text/javascript">
			$(function(){
				
				$('body, .Wrapper').each(function(index, element){
					$(element).on("contextmenu drag dragstart copy",function(e){return false;});
				});
				
				$("#AnalogicoInfo .AnalogicoInfoSubTitle").html('Garm_ash is posting 165 illustrations&etc. to Poipiku.');
				
				$("#AnalogicoInfo .AnalogicoMoreInfo").html('Register now to see all!');
				

				
			});
		</script>
```
