### ISSUE TITLE
wco.tv: detection

### ISSUE THREAD

**Issue by FloofyTanuki** [uBlockOrigin/uAssets#15703]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wco.tv/monkie-kid-episode-0`

### Category

detection

### Describe the issue

when attempting to view content, the page displays a message stating that adblock has been detected and blocks you from watching the content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/97627429/202607543-bd62c15e-3e8d-4b37-8c8b-ba84abaea2b4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90363
  cosmetic: 38420
  scriptlet: 16490
  html: 818
listset (total-discarded, last-updated): 
  default: 
    user-filters: 31-8, never
    ublock-filters: 32022-33, 1d.2h.38m
    ublock-badware: 4007-0, 1d.2h.37m
    ublock-privacy: 285-0, 9d.3h.18m
    ublock-abuse: 76-0, 9d.3h.17m
    ublock-unbreak: 1908-0, 1d.2h.36m
    easylist: 64330-612, 4d.38m
    easyprivacy: 30794-1709, 5d.4h.19m
    urlhaus-1: 11492-0, 6h.59m
    plowe-0: 3670-3, 6d.7h.25m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1634 ms (selfie)
  maxAssetCacheWait: 375 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    addthis.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    vdo.ai: 2
    watchanimesub.net: 2
```
</details>

**Comment by liamengland1** [comment]
`watchanimesub.net##+js(nostif, isAdBlockActive)`

**Comment by pilis1** [comment]
There is again an adblock detection, and also a big space on the homepage:
![Image](https://github.com/user-attachments/assets/e4f29816-816f-4eb5-8ef9-bcf2a10c48ea)

**Comment by mapx-** [comment]
even disabling uBO I get that warning

**Comment by pilis1** [comment]
Then that doesn't really seem to be an adblock detection anymore.....

Anyways, there are these annoying big spaces:

![Image](https://github.com/user-attachments/assets/0ec13d59-c22d-47db-8ebb-0d8b802b2e77)

![Image](https://github.com/user-attachments/assets/0f41f7dd-7201-436f-8328-43eabc4dfda0)

**Comment by pilis1** [comment]
For the first photo I noticed this filter works:
`wco.tv###sidebar_today > div[style^="float:right;"]`

**Comment by pilis1** [comment]
And for the second photo:
`www.wco.tv##.columns.fourteen > div:nth-of-type(2) > div:nth-of-type(2)`

**Comment by mapx-** [comment]
```adb
wco.tv##[style^="float:right;"]:has([class^="reklam"])
wco.tv###sidebar_today > div[style^="float:right;"]
```

report at easylist

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/8bf7e493-f401-497f-a863-373eec4e5551

Premium subscription banner, on the right part of the page.

**Comment by stephenhawk8054** [comment]
We don't fix self promotion. Report at EasyList to see if they address it in their annoyances lists.

**Comment by ghost** [comment]
I did report two months ago but nothing happened, the issue is still open.

**Comment by stephenhawk8054** [comment]
Then you have to wait for them to address. We don't fix self-promotion.
