### ISSUE TITLE
myhermes.de: breakage

### ISSUE THREAD

**Issue by tegutistgut** [uBlockOrigin/uAssets#15714]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.myhermes.de/paketshop/`

### Category

breakage

### Describe the issue

The Google Maps map doesnt load when ublock origin is active.

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 108
filterset (summary): 
  network: 265620
  cosmetic: 102727
  scriptlet: 32629
  html: 833
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
  added: 
    adguard-generic: 65671-5033, 2d.21h.32m
    adguard-spyware: 34245-13766, 3d.17h.32m
    adguard-spyware-url: 841-4, 21h.33m
    block-lan: 44-0, 25d.18h.33m
    curben-phishing: 161796-17, 1h.43m
    curben-pup: 194-0, 14h.3m
    adguard-annoyance: 61072-2252, 2d.21h.33m
  default: 
    user-filters: 10-0, never
    ublock-filters: 32123-278, 2d.21h.31m
    ublock-badware: 4006-0, 2d.10m
    ublock-privacy: 285-1, 9d.14h.39m
    ublock-abuse: 76-0, 9d.14h.38m
    ublock-unbreak: 1913-0, 1d.23h
    ublock-quick-fixes: 579-1, 13h.11m
    adguard-mobile: 8196-29, 3d.17h.33m
    easyprivacy: 30818-1730, 5d.23h.34m
    urlhaus-1: 14011-0, 13h.47m
    plowe-0: 3670-140, 7d.14h.46m
    DEU-0: 6021-391, 14h.2m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3967 ms (selfie)
  maxAssetCacheWait: 376 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    abtasty.com: 1
    google.com: 1
    usercentrics.eu: 3
    youtube-nocookie.com: 3
```
</details>

**Comment by mapx-** [comment]
add

```
@@||api.usercentrics.eu^
@@||app.usercentrics.eu/browser-sdk
```
