### ISSUE TITLE
math.semester.ru [Anti-Adblock]

### ISSUE THREAD

**Issue by hant0508** [uBlockOrigin/uAssets#1571]
### URL(s) where the issue occurs

`https://math.semestr.ru/gauss/rang.php`

### Describe the issue

The "next" button is inactive and there's a request to disable ad blocker.

### Screenshot(s)

1. Click "Далее" ("next") button
![screenshot_2018-02-19 2](https://user-images.githubusercontent.com/28459131/36386776-f69ce8e6-15a7-11e8-91f8-8fc702d71642.png)
2. On this page "next" button is inactive
![screenshot_2018-02-19 1](https://user-images.githubusercontent.com/28459131/36386781-f8d1a64c-15a7-11e8-8f7e-126b142a60fa.png)

### Versions

- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.7b3

### Settings

Default filters + RUS (Adguard, RU AdList) + All Adguard

### Notes

To make the button active you have to whitelist `https://recreativ.ru/rcode.0cd55aeee1.js` and disable cosmetic filtering (or maybe just some filters). The filter `||recreativ.ru/rcode.*.js$important` from Adguard Russian Filters prevents excluding `https://recreativ.ru/rcode.0cd55aeee1.js` with static filters.

**Comment by mapx-** [comment]
Did you report the issue at adguard filters repository ?

**Comment by hant0508** [comment]
No, I didn't.

**Comment by mapx-** [comment]
report here
https://github.com/AdguardTeam/AdguardFilters/issues

and / or here:
https://forums.lanik.us/viewforum.php?f=102

**Comment by hant0508** [comment]
I've reported an issue at Adguard repository and found bad cosmetic filter: it's `semestr.ru#?#.adsbygoogle:style(max-height: 1px !important)` from RU AdList.

However, if you whitelist this cosmetic filter and the script (using dynamic filtering), you won't solve the problem. The "next" button is repaired, but if you click it, you will be redirected one more time. 

![screenshot_2018-02-19 5](https://user-images.githubusercontent.com/28459131/36392156-fe03def6-15ba-11e8-8d0b-3f173b2379f6.png)

**Comment by mapx-** [comment]
Did they (ruadlist, adguard) fixed your issue ?

**Comment by hant0508** [comment]
RU AdList fixed their part of an issue. Waiting for Adguard.
