### ISSUE TITLE
pricerunner.dk: breakage

### ISSUE THREAD

**Issue by oliverthedeveloper** [uBlockOrigin/uAssets#15710]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.pricerunner.dk/pl/94-5247490/Hoeretelefoner/Motorola-Verveloop-105-Sammenlign-Priser`

### Category

breakage

### Describe the issue

It shows "1 Review" but not the review itself.

Therefor, I cannot edit it.
Everything is up to date - also.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 317633
  cosmetic: 199925
  scriptlet: 37473
  html: 0
listset (total-discarded, last-updated): 
  added: 
    DEU-0: 6021-0, 12h.14m
    adguard-annoyance: 60999-96, 3d.21h.16m
    adguard-generic: 66071-516, 3d.21h.15m
    adguard-spyware: 34235-3124, 3d.21h.18m
    adguard-spyware-url: 824-1, 3d.21h.17m
    block-lan: 44-0, 28d.5h.47m
    curben-phishing: 166071-0, 12h.15m
    curben-pup: 194-1, 12h.16m
    dpollock-0: 11391-198, 3d.17h.11m
    fanboy-annoyance: 83092-3942, 1d.2h.3m
    fanboy-cookiemonster: 43370-43370, 1d.2h.4m
    fanboy-thirdparty_social: 68-20, 1d.2h.5m
    ublock-annoyances: 4782-233, 3d.21h.19m
  default: 
    user-filters: 0-0, never
    easylist: 64687-1104, 2d.1h
    easyprivacy: 30853-12621, 1d.6h.6m
    plowe-0: 3668-1320, 10d.18h.42m
    ublock-abuse: 76-0, 10d.18h.41m
    ublock-badware: 4003-249, 3d.21h.14m
    ublock-filters: 31235-3658, 3d.21h.13m
    ublock-privacy: 257-50, 10d.18h.40m
    ublock-quick-fixes: 560-34, 12h.18m
    ublock-unbreak: 1895-102, 3d.21h.12m
    urlhaus-1: 11492-8, 12h.17m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1182 ms (selfie)
  maxAssetCacheWait: 889 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    pricerunner.dk: 1
    googlesyndication.com: 4
```
</details>

**Comment by oliverthedeveloper** [comment]
Trying to add SS again:
![image](https://user-images.githubusercontent.com/40898841/202821102-d6ae6f72-c934-409a-9d56-e613a4d48aa9.png)

**Comment by mapx-** [comment]
add

`@@||pricerunner.dk/public/social/content/review/$xhr,1p`

FA issue @ryanbr
