### ISSUE TITLE
Target.com: Breakage 

### ISSUE THREAD

**Issue by Woodhead02** [uBlockOrigin/uAssets#15711]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`www.target.com`

### Describe the issue

With uBlock running, logging into Target.com fails due to targetimg1.com/ssx/ssx.mod.js being blocked. Looking at this file it does not contain any highly private information. Allowing this file fixes the site. 

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 1.07

### Settings

No change to settings

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Was removed.

**Comment by Woodhead02** [comment]
@ryanbr is there any way to add this to an allow list for privacy seeing that it breaks the site? Hoping to prevent it from occurring again.

**Comment by Woodhead02** [comment]
Also, thank you for the extremely expedited work!
