### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by camboozle** [uBlockOrigin/uAssets#15718]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://megaup.net/Wqgn/Borderlands.3.Directors.Cut-CODEX.part05.rar`

### Category

detection

### Describe the issue

When using this website, for the first day it worked perfectly, but when u got back on it the next day it game me this message: DISABLE ADBLOCK. Please supporting us by disabling your ad blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![primary](https://user-images.githubusercontent.com/102335295/202869516-b839f507-28a8-4627-a272-5388bb7bb603.png)

![Capture](https://user-images.githubusercontent.com/102335295/202869557-2993abbd-39f9-4b91-863c-730cf63e56df.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 93450
  cosmetic: 38643
  scriptlet: 16714
  html: 852
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32022-45, 1d.49m
    ublock-badware: 4007-0, 1d.48m
    ublock-privacy: 305-0, 1d.47m
    ublock-abuse: 76-0, 1d.46m
    ublock-unbreak: 1908-0, 1d.45m
    ublock-quick-fixes: 579-1, 1d.44m
    easylist: 64767-618, 1d.43m
    easyprivacy: 30854-1710, 1d.42m
    urlhaus-1: 14011-0, 1d.41m
    plowe-0: 3668-3, 1d.40m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 273 ms (selfie)
  maxAssetCacheWait: 183 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    megaup.net: 2
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 3
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
```
</details>

**Comment by Crystal-RainSlide** [comment]
Detection again.

We had more than one page of it already:

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+megaup.net
