### ISSUE TITLE
gloucestershirelive.co.uk: breakage

### ISSUE THREAD

**Issue by Rackmani** [uBlockOrigin/uAssets#15715]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.gloucestershirelive.co.uk/news/gloucester-news/watch-huge-a417-air-balloon-7838871`

### Category

breakage

### Describe the issue

The videos never play on this site (FF) - ok on Safari where I don't have ublock and ok if turn ublock off in FF 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 93365
  cosmetic: 38620
  scriptlet: 16721
  html: 851
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32022-44, 2d.21h.49m
    ublock-badware: 4007-0, 2d.21h.48m
    ublock-privacy: 305-0, 2d.18h.51m
    ublock-abuse: 76-0, 2d.18h.40m
    ublock-unbreak: 1909-1, 2d.21h.47m
    ublock-quick-fixes: 579-1, 3h.10m
    easylist: 64686-614, 2d.10h.20m
    easyprivacy: 30850-1708, 2d.10h.21m
    urlhaus-1: 13986-0, 3h.9m
    plowe-0: 3668-3, 11d.14h.46m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 191 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    gloucestershirelive.co.uk: 2
    adsafeprotected.com: 1
    amazon-adsystem.com: 1
    aswpsdkus.com: 3
    chartbeat.com: 1
    convrse.media: 1
    crwdcntrl.net: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    grapeshot.co.uk: 1
    indexww.com: 1
    jwpcdn.com: 1
    jwpltx.com: 1
    m32.media: 1
    quantserve.com: 1
    tm-awx.com: 4
    viafoura.co: 4
    webcontentassessor.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||gloucestershirelive.co.uk/@trinitymirrordigital/withnail/lib/prebid/prebid.js$script,1p`

@ryanbr

**Comment by okiehsch** [comment]
Hm, 
`@@||gloucestershirelive.co.uk/*/lib/prebid/*$script,1p`
works only if I remove all cookies and only on the first load.

**Comment by mapx-** [comment]
exactly, I cannot find a way .. only allowing all scripts / xhr

**Comment by mapx-** [comment]
there is a prebid xhr request too

**Comment by okiehsch** [comment]
Yes, I tried all prebid requests without success and it's rather hard to debug.

**Comment by Rackmani** [comment]
thx for trying guys - it seems to be an issue with all their videos

**Comment by mapx-** [comment]
Test

```
@@||gloucestershirelive.co.uk^$1p
@@*$script,xhr,domain=gloucestershirelive.co.uk,3p
*$script,xhr,domain=gloucestershirelive.co.uk,important,3p,denyallow=viafoura.net|jwplayer.com|jwpcdn.com|quantcast.com|gstatic.com|googleapis.com|googletagmanager.com|crwdcntrl.net
gloucestershirelive.co.uk##.topbox-cls-placeholder
```

**Comment by mapx-** [comment]
alternative:

```
@@||gloucestershirelive.co.uk^$1p
@@||viafoura.net^$domain=gloucestershirelive.co.uk,xhr,script
@@||jwplayer.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||jwpcdn.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||quantcast.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||gstatic.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||googleapis.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||googletagmanager.com^$domain=gloucestershirelive.co.uk,xhr,script
@@||crwdcntrl.net^$domain=gloucestershirelive.co.uk,xhr,script
@@||fastly.net^$domain=gloucestershirelive.co.uk,xhr,script
gloucestershirelive.co.uk##.topbox-cls-placeholder
```

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15715#issuecomment-1320924946
works for me, but we won't add that, it's a site issue imo.

**Comment by mapx-** [comment]
@Yuki2718 
this filter from AG annoyance should be removed, without clicking the consent form => no video

`gloucestershirelive.co.uk##.qc-cmp2-container`

**Comment by AdamWr** [comment]
If I'm not wrong, something like this:
```adblock
gloucestershirelive.co.uk##+js(set, chameleonVideo.adDisabledRequested, true)
```
should fixes video player and it shouldn't be necessary to accept a cookie notice.
At least it works fine on my end.

**Comment by mapx-** [comment]
wow, great, working fine

**Comment by Rackmani** [comment]
Oh wow...quickly checked after purging all caches and updating filters and now seems to work. Brilliant!  well done you heros!!  Will check further in week
