### ISSUE TITLE
keanu.im: breakage

### ISSUE THREAD

**Issue by mtt59** [uBlockOrigin/uAssets#15712]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://keanu.im/`

### Category

breakage

### Describe the issue

the website seems to generate about 2k "ads" per second, as shown in the image attachment.
this goes on indefinetly, slowing down the browser, probably until it crashes.
closing the tab/window solves the lag across the other webpages after a few seconds.

the screenshot was after 16 seconds of waiting, measured from pressing enter to pressing the screenshot key combo

![Screenshot 2022-11-18 200030](https://user-images.githubusercontent.com/55414564/202833286-bd21d8c6-d082-4a5f-ad61-cc59fc2590da.jpg)

edit:
the problem persists with non-adblocker extentions disabled as well
the problem does not happen with adblock disabled or on another browser
there are no actual ads on the website
disabling javascript does not solve the problem

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 102
filterset (summary): 
  network: 90592
  cosmetic: 38620
  scriptlet: 16705
  html: 833
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    ublock-filters: 32022-47, 6h.24m
    ublock-badware: 4007-0, 6h.23m
    ublock-privacy: 286-0, 4d.9h.47m
    ublock-abuse: 76-0, 4d.9h.48m
    ublock-unbreak: 1908-1, 6h.22m
    ublock-quick-fixes: 564-0, 19h.40m
    easylist: 64413-613, 3d.6h.31m
    easyprivacy: 30835-1710, 3d.6h.30m
    urlhaus-1: 11492-0, 19h.41m
    plowe-0: 3673-3, 1d.20h.38m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 432 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 2834
  blockedDetails: 
    keanu.im: 2834
```
</details>

**Comment by gwarser** [comment]
CSP reports. `?sentry_key=`.

**Comment by mapx-** [comment]
FF issue, chrome seems ok

**Comment by mapx-** [comment]
it should be reported to mozilla
