### ISSUE TITLE
academy.com: breakage

### ISSUE THREAD

**Issue by pickscrape** [uBlockOrigin/uAssets#15716]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.academy.com/`

### Category

breakage

### Describe the issue

Main navigation does not work, searching does not work. It should reproduce pretty easily.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 106
filterset (summary): 
  network: 93552
  cosmetic: 38626
  scriptlet: 16719
  html: 832
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32020-127, 3d.11h.20m
    ublock-badware: 4007-0, 3d.11h.19m
    ublock-privacy: 286-0, 8d.3h.40m
    ublock-abuse: 76-0, 8d.3h.39m
    ublock-unbreak: 1909-1, 3d.11h.18m
    ublock-quick-fixes: 581-0, 3h.8m
    easylist: 64720-516, 1d.11h.13m
    easyprivacy: 30850-1726, 1d.11h.12m
    urlhaus-1: 14144-0, 3h.7m
    plowe-0: 3670-3, 6d.15h.28m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3138 ms
  maxAssetCacheWait: 755 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    academy.com: 2
    googletagmanager.com: 1
    monetate.net: 2
    oraclecloud.com: 14
    paypal.com: 3
    quantummetric.com: 1
    zineone.com: 1
```
</details>

**Comment by mapx-** [comment]
I got only the broken menu shop button (top left side)

add

`@@||googletagmanager.com/gtag/js$script,domain=academy.com`

search working fine on my end

@ryanbr
