### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by xWqNN** [uBlockOrigin/uAssets#15717]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

i always see ads in twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 106
filterset (summary): 
  network: 301113
  cosmetic: 79631
  scriptlet: 30908
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 65694-501, 2d.6h.11m
    adguard-spyware: 34259-2990, 2d.6h.12m
    adguard-spyware-url: 838-1, 2d.6h.14m
    block-lan: 44-0, 6d.7h.28m
    curben-phishing: 159079-0, 2h.10m
    curben-pup: 194-1, 2h.11m
    dpollock-0: 11390-206, 6d.7h.28m
  default: 
    user-filters: 0-0, never
    TUR-0: 11312-10, 2d.6h.13m
    easylist: 64689-1066, 2d.12h.25m
    easyprivacy: 30853-12557, 2d.12h.24m
    plowe-0: 3670-1323, 6d.17m
    ublock-abuse: 76-0, 1d.23h.6m
    ublock-badware: 4003-250, 1d.3h.24m
    ublock-filters: 31272-3298, 1d.3h.23m
    ublock-privacy: 258-43, 1d.23h.7m
    ublock-quick-fixes: 573-33, 2h.13m
    ublock-unbreak: 1895-96, 1d.3h.25m
    urlhaus-1: 14144-11, 2h.12m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 579 ms (selfie)
  maxAssetCacheWait: 451 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    ddacn6pr5v0tl.cloudfront.net: 1
    imrworldwide.com: 2
    scorecardresearch.com: 14
```
</details>

**Comment by mapx-** [comment]
twitch
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
