### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by eqlipt** [uBlockOrigin/uAssets#15725]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yandex.ru/images/search?from=tabbar&text=crater`

### Category

ads

### Describe the issue

Line of ads repeats itself every 20 or so lines of images. Any request text I tried caused this ad, 'crater' is just an example.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ads](https://user-images.githubusercontent.com/7482653/202911915-16299b34-62de-4ae8-8496-c91a49ca652e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 110461
  cosmetic: 59827
  scriptlet: 17956
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39684-11, 18m
  default: 
    user-filters: 3-2, never
    easylist: 64783-66, 18m
    easyprivacy: 30861-1283, 18m
    plowe-0: 3668-874, 18m
    ublock-abuse: 76-1, 18m
    ublock-badware: 4008-109, 18m
    ublock-filters: 31277-148, 18m
    ublock-privacy: 258-1, 18m
    ublock-quick-fixes: 576-12, 18m
    ublock-unbreak: 1896-43, 18m
    urlhaus-1: 13884-0, 18m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1561 ms
  maxAssetCacheWait: 942 ms
popupPanel: 
  blocked: 103
  blockedDetails: 
    yandex.ru: 103
```
</details>

**Comment by mapx-** [comment]
subscribe RU AdList: Counters list
[RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe)

Test again

**Comment by eqlipt** [comment]
> subscribe RU AdList: Counters list [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe)
> 
> Test again

This worked, thanks!
