### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by Scoopage** [uBlockOrigin/uAssets#15723]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.msn.com/en-gb?AR=1`

### Category

ads

### Describe the issue

whole page goes pink when trying to choose an element to block therefore whole page would be blocked if created 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 109
filterset (summary): 
  network: 93580
  cosmetic: 38678
  scriptlet: 16715
  html: 833
listset (total-discarded, last-updated): 
  default: 
    user-filters: 43-0, never
    ublock-filters: 32022-33, 1d.14h.29m
    ublock-badware: 4007-0, 1d.14h.28m
    ublock-privacy: 285-0, 11d.1h.14m
    ublock-abuse: 76-0, 11d.20h.41m
    ublock-unbreak: 1909-1, 1h.9m
    easylist: 64759-618, 2d.41m
    easyprivacy: 30853-1708, 1d.18h
    plowe-0: 3668-3, 11d.20h.42m
    urlhaus-1: 14144-0, 14h.17m
    ublock-quick-fixes: 577-11, 14h.16m
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 92 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    msn.com: 29
    azure.com: 2
    btloader.com: 3
    scorecardresearch.com: 1
    yahoo.com: 2
```
</details>

**Comment by Scoopage** [comment]
whole page goes pink when trying to choose an element to block therefore whole page would be blocked if created

**Comment by Yuki2718** [comment]
Yes, because everything under that (entry-point) are shadow-root. It's not a filter issue.

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2346

**Comment by krystian3w** [comment]
Maybe possible use scriptlets in expert hands to temporary disable load ads protected before simple network filtering (I mean maybe this no need wait to unlock ExtendedCSS aka procedural cosmetic filtering).
