### ISSUE TITLE
dragontea.ink: [unknown]

### ISSUE THREAD

**Issue by Taras255** [uBlockOrigin/uAssets#15727]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/novel/soul-of-burning-steel/`

### Category

detection

### Describe the issue

Ads Blocker Detected! And blocks access to the site. Loading appears and it's over. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://user-images.githubusercontent.com/117605241/202923683-8704b0ad-2bc4-4582-abc8-75953b9a2172.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 118198
  cosmetic: 187532
  scriptlet: 24613
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 61074-97, 3d.21h.8m
    adguard-social: 18959-820, 3d.21h.7m
    dpollock-0: 11391-21, 1d.13h.14m
    fanboy-annoyance: 83092-4943, 3d.5h.14m
    fanboy-cookiemonster: 43057-42998, 3d.9h.15m
    fanboy-social: 23433-23399, 5d.32m
    fanboy-thirdparty_social: 68-21, 3d.13h.28m
    ublock-annoyances: 4783-208, 3d.21h.6m
  default: 
    user-filters: 25-0, never
    POL-0: 7860-8, 13h.7m
    POL-2: 1276-13, 1d.19h.19m
    easylist: 64689-385, 3d.21h.9m
    easyprivacy: 30860-1375, 13h.8m
    plowe-0: 3668-1263, 12d.17h.39m
    ublock-abuse: 76-0, 12d.17h.39m
    ublock-badware: 4003-109, 3d.21h.5m
    ublock-filters: 31258-532, 3d.21h.4m
    ublock-privacy: 257-9, 12d.17h.39m
    ublock-quick-fixes: 587-13, 13h.6m
    ublock-unbreak: 1895-50, 3d.21h.3m
    urlhaus-1: 14460-0, 13h.5m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2608 ms (selfie)
  maxAssetCacheWait: 1488 ms
popupPanel: 
  blocked: 58
  blockedDetails: 
    1rx.io: 3
    4dex.io: 4
    a-mo.net: 3
    adnxs.com: 7
    adxpremium.services: 3
    amazon-adsystem.com: 5
    creativecdn.com: 3
    criteo.com: 5
    criteo.net: 7
    doubleclick.net: 2
    google.com: 1
    google.pl: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    omnitagjs.com: 3
    onetag-sys.com: 4
    setupad.net: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists it got fixed 8 hours ago

**Comment by Taras255** [comment]
Thank you very much. My mistake. I noticed the error yesterday - and yesterday I updated the filters. And now it kind of slipped my mind.
