### ISSUE TITLE
1cloudfile.com: detection

### ISSUE THREAD

**Issue by NVT223** [uBlockOrigin/uAssets#15721]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://1cloudfile.com/4V48`

### Category

detection

### Describe the issue

The creator found a way to block the content is the ads are blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 1359741
  cosmetic: 107850
  scriptlet: 35805
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 51585-339, 7h.5m
    https://go.leminhthanh.me/db/abc.txt: 1128750-23216, 7h.5m
    https://raw.githubusercontent.com/nmtrung/FMSF-2.0/master/fmsf_2.0.txt: 1080-201, 7h.22m
    adguard-annoyance: 61082-1703, 3d.49m
    adguard-generic: 65685-1909, 3d.48m
    adguard-spyware: 34256-6281, 3d.48m
    adguard-spyware-url: 837-1, 3d.48m
    ublock-annoyances: 4784-185, 3d.49m
  default: 
    user-filters: 103773-80, never
    VIE-1: 1945-1193, 7h.5m
    easylist: 64731-40088, 3d.47m
    easyprivacy: 30853-15226, 3d.47m
    plowe-0: 3673-1682, 3d.47m
    ublock-abuse: 76-1, 3d.47m
    ublock-badware: 4003-252, 3d.47m
    ublock-filters: 31245-3878, 3d.47m
    ublock-privacy: 258-46, 3d.47m
    ublock-quick-fixes: 571-33, 7h.24m
    ublock-unbreak: 1895-97, 3d.47m
    urlhaus-1: 14144-5210, 7h.23m
filterset (user): [array of 22990 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2552 ms (selfie)
  maxAssetCacheWait: 2140 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    1cloudfile.com: 2
    d192r5l88wrng7.cloudfront.net: 2
    doubleclick.net: 3
    google.com: 1
    google.com.vn: 1
    googleadservices.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    waust.at: 1
    wirratailage.com: 1
```
</details>

**Comment by ghajini** [comment]
fixed a while ago https://github.com/uBlockOrigin/uAssets/commit/be28ad45d47b83d527fff5fe4115a9a997aa7932

**Comment by krystian3w** [comment]
IMO problem are back into Chrome.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15719 https://github.com/uBlockOrigin/uAssets/issues/15721 https://github.com/uBlockOrigin/uAssets/issues/15719

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15719 https://github.com/uBlockOrigin/uAssets/issues/10408
https://github.com/uBlockOrigin/uAssets/issues/15719
