### ISSUE TITLE
anime2you.de: ads

### ISSUE THREAD

**Issue by TanukiAI** [uBlockOrigin/uAssets#15728]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.anime2you.de/`

### Category

ads

### Describe the issue

Ads are still shown in the browser and marked with red in the screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/46388493/202928016-f6d3aba3-d2c7-485a-8402-67cd52531e42.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 95511
  cosmetic: 42454
  scriptlet: 16726
  html: 833
listset (total-discarded, last-updated): 
  default: 
    user-filters: 28-3, never
    ublock-filters: 32036-56, 1d.1h.29m
    ublock-badware: 4012-0, 1d.1h.28m
    ublock-privacy: 286-0, 6d.4h.39m
    ublock-abuse: 76-0, 6d.4h.38m
    ublock-unbreak: 1909-1, 1d.1h.27m
    easylist: 64736-621, 3d.5h.47m
    easyprivacy: 30853-1720, 3d.5h.46m
    urlhaus-1: 13884-0, 1h.3m
    plowe-0: 3671-3, 5d.2h.43m
    DEU-0: 6021-2, 1h.2m
    ublock-quick-fixes: 582-0, 1h.4m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 209 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cnameUncloakEnabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 579 ms (selfie)
  maxAssetCacheWait: 172 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    anime2you.de: 2
    doubleclick.net: 1
    googletagmanager.com: 1
    r66net.com: 1
    taboola.com: 1
    yieldlove.com: 1
```
</details>

**Comment by okiehsch** [comment]
````

anime2you.de##.ad_platzhalter
anime2you.de###Ad-Content
anime2you.de##.td-fix-index
````
@khrin
