### ISSUE TITLE
sport1.de/tv-video

### ISSUE THREAD

**Issue by Iselgueck** [uBlockOrigin/uAssets#1572]
### URL(s) where the issue occurs

`https://www.notebookcheck.com/`

AND

Anti adblocker: `https://www.sport1.de/tv-video`

### Describe the issue
Advertisements 

AND
Anti Adblocker Message / Videos dont play 

### Versions

- Browser/version: 58.0.2
- uBlock Origin version: 1.15.6

### Settings
-

**Comment by mapx-** [comment]
for notebookcheck update `ublock filters`

don't mix up in the future more sites => distinct posts
