### ISSUE TITLE
egybest.direct: breakage

### ISSUE THREAD

**Issue by anassf** [uBlockOrigin/uAssets#15726]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.egybest.direct/movie/black-adam-2022/`

### Category

breakage

### Describe the issue

Clicking on the "Play" button nothing happens and this is valid for all other pages (movies) in the same domain.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 14282
  cosmetic: 11320
  scriptlet: 19934
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    FRA-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    urlhaus-1: null
  added: 
    ara-0: 2693-0, 1m
    ublock-annoyances: 4787-4, 1m
  default: 
    user-filters: 13-0, never
    ublock-abuse: 76-0, 1m
    ublock-badware: 4008-0, 1m
    ublock-filters: 31278-31, 1m
    ublock-privacy: 258-0, now
    ublock-quick-fixes: 583-12, now
    ublock-unbreak: 1896-1, now
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 55 redacted]
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1341 ms (selfie)
  maxAssetCacheWait: 1059 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/10255
