### ISSUE TITLE
streamlivenow.me: detection

### ISSUE THREAD

**Issue by DesignPixelZ** [uBlockOrigin/uAssets#15720]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://streamlivenow.me/lala/index.php?stream=18?sid=1341963`

### Category

detection

### Describe the issue

the creator found a way to block the content is the ads are blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 188498
  cosmetic: 230336
  scriptlet: 37786
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 1d.21h.36m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 2d.1h.52m
    https://winhelp2002.mvps.org/hosts.txt: 8730-315, 2d.1h.51m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-11, 2d.1h.50m
    CHN-0: 28689-95, 1d.21h.46m
    ROU-1: 1150-19, 1d.43m
    adguard-annoyance: 61123-156, 1d.21h.45m
    adguard-generic: 65729-628, 1d.21h.44m
    adguard-mobile: 8205-241, 1d.21h.43m
    adguard-social: 18968-845, 1d.21h.42m
    adguard-spyware: 34267-3454, 1d.21h.41m
    dpollock-0: 11391-1819, 3d.2h.21m
    fanboy-annoyance: 82776-4982, 4d.22h.21m
    fanboy-cookiemonster: 43058-43058, 4d.22h.20m
    fanboy-social: 23400-23375, 1d.21h.47m
    fanboy-thirdparty_social: 68-21, 4d.22h.19m
    ublock-annoyances: 4786-237, 1d.21h.40m
  default: 
    user-filters: 7-0, never
    easylist: 64767-1559, 20h.40m
    easyprivacy: 30854-12795, 2d.1h.53m
    plowe-0: 3673-2541, 3d.21h.49m
    ublock-abuse: 76-0, 19m
    ublock-badware: 4003-255, 1d.21h.39m
    ublock-filters: 31239-3703, 1d.21h.38m
    ublock-privacy: 258-48, 18m
    ublock-quick-fixes: 576-33, 17m
    ublock-unbreak: 1895-101, 1d.21h.37m
    urlhaus-1: 14460-0, 16m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 145 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4457 ms
  maxAssetCacheWait: 3013 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    addthis.com: 1
    amazon.com: 1
    ardslediana.com: 1
    chatango.com: 1
    footyhunter3.xyz: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    hassarexurbs.com: 1
    nossairt.net: 2
    oaphoace.net: 1
    sportcast.life: 1
```
</details>

**Comment by ghajini** [comment]
> detection
 what do you mean by this

**Comment by mapx-** [comment]
People sometimes confuse page breaking with detection

**Comment by DesignPixelZ** [comment]
> > detection
> 
> what do you mean by this,i don't see anything like that?
> 
> can you update all filters, i added a fix which might fix yours problem

It did fix my problem. Thank you!
