### ISSUE TITLE
neogaf.com: cosmetic filters don't work

### ISSUE THREAD

**Issue by FuzFuz77** [uBlockOrigin/uAssets#15724]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.neogaf.com/forums/gaming-discussion.2/`

### Category

ads

### Describe the issue

Today some sites I regularly use managed to somehow get around my custom cosmetic filters.

Things that I removed for readability or because they're annoyances to me came back in full force, and they even come back when I make another custom filter with the picker (the cookie message on reddit).

I'll attach a few images for clarity, the circled things aren't supposed to be there and I haven't seen them in YEARS.

https://postimg.cc/q6HTnT7F

https://postimg.cc/9rWfNdWn

https://postimg.cc/HVBLGrns

One little detail, I'm on my 100mb optic fiber but my internet is very slow today and some sites I commonly use are a bit unresponsive or just don't load. Maybe some faulty control unit due to recent bad weather, I don't know [postimages gave me quite a number of "502 Bad Gateway" before letting me upload those screenshots]. Not sure if that could be a reason. But anyway, on one of this page load uBlock was enabled (red button) but behaved like it was disabled, disabling and re-enabling it fixed the problem. Sometimes right click on page doesn't show uBlock's "block element" in the contextual menu. Feels like it's doing it everywhere.

Another detail: I have a very old version of chrome (Version 69.0.3497.100) and I suppose my uBlock is an old version too due to that? It's 1.45.2

But anyway, everything worked perfectly up to yesterday. I purged all caches and updated the filters to no avail. My other plugins feel like they're working flawlessly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 69
filterset (summary): 
  network: 209519
  cosmetic: 274581
  scriptlet: 37065
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29285-75, 21h.56m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2040-1, 21h.56m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 21h.56m
    https://raw.githubusercontent.com/ethan-xd/ethan-xd.github.io/master/fb.txt: 132-0, 21h.56m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5608-5, 21h.56m
    https://raw.githubusercontent.com/krisu5/userstyles/master/Twitter%20-%20Clean%202019%20Design%20(Now%20With%20Light%20Blue)/filterlist.txt: 17-0, 21h.56m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-54, 21h.56m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-1, 21h.56m
    https://winhelp2002.mvps.org/hosts.txt: 8730-353, 21h.56m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-21, 21h.56m
    https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt: 2675-40, never
    ITA-0: 13261-41, 21h.55m
    LVA-0: 392-3, 21h.55m
    RUS-0: 39689-3483, 21h.55m
    adguard-annoyance: 61118-581, 21h.55m
    adguard-generic: 65756-876, 21h.55m
    adguard-mobile: 8210-267, 21h.55m
    adguard-social: 18985-857, 21h.55m
    adguard-spyware: 34272-3517, 21h.55m
    ara-0: 2693-17, 21h.56m
    [7 lists not shown]: [too many]
  default: 
    user-filters: 151-10, never
    easylist: 64761-1816, 21h.56m
    easyprivacy: 30860-12854, 21h.56m
    plowe-0: 3668-2534, 21h.56m
    ublock-abuse: 76-56, 21h.56m
    ublock-badware: 4008-260, 20h.46m
    ublock-filters: 31258-3786, 21h.55m
    ublock-privacy: 258-81, 21h.55m
    ublock-quick-fixes: 582-35, 21h.55m
    ublock-unbreak: 1895-104, 21h.55m
    urlhaus-1: 14144-0, 21h.55m
filterset (user): [array of 151 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
  removed: 
    no-large-media: behind-the-scene false
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3458 ms
  maxAssetCacheWait: 2373 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    neogaf.com: 2
    cloudflareinsights.com: 2
    doubleclick.net: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    viglink.com: 1
```
</details>

**Comment by mapx-** [comment]
No real issue, no example links, no custom filters.

Do your tests using ONLY the default setup, no other lists, no modified settings.
Better using a new profile in your browser.

closing for now.
