### ISSUE TITLE
fontspace.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15733]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fontspace.com/popular/fonts`

### Category

ads

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/203052710-8b023c62-ba91-44a1-bbeb-7375454502a5.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/203052735-cf2068df-f360-4440-9c55-9a6ccf218c8d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 109
filterset (summary): 
  network: 110577
  cosmetic: 167742
  scriptlet: 26010
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7927-3, 2d.12h.23m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 2d.12h.21m
    adguard-annoyance: 61112-393, 2d.12h.24m
    adguard-spyware: 34272-2514, 2d.12h.25m
    fanboy-annoyance: 82929-3873, 6d.13h.37m
    fanboy-cookiemonster: 43057-43015, 6d.13h.37m
    ublock-annoyances: 4784-212, 2d.12h.22m
  default: 
    user-filters: 13-0, never
    easylist: 64784-151, 12h.23m
    easyprivacy: 30861-12460, 12h.22m
    ublock-abuse: 76-0, 6d.13h.47m
    ublock-badware: 4003-107, 2d.12h.28m
    ublock-filters: 31258-605, 2d.12h.27m
    ublock-privacy: 258-47, 6d.13h.47m
    ublock-quick-fixes: 587-12, 21m
    ublock-unbreak: 1895-62, 2d.12h.26m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1997 ms (selfie)
  maxAssetCacheWait: 1067 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    google-analytics.com: 1
    proper.io: 1
    quantserve.com: 1
    visualstudio.com: 8
```
</details>

**Comment by mapx-** [comment]
`fontspace.com##.font-container:has(.proper-ad-unit)`

@ryanbr

**Comment by 96273** [comment]
same placeholders are still there, and there is no rule for fontspace.com in easylist

**Comment by stephenhawk8054** [comment]
Report at https://github.com/easylist/easylist/issues/
