### ISSUE TITLE
mentor.duden.de: breakage

### ISSUE THREAD

**Issue by Acursen** [uBlockOrigin/uAssets#15739]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mentor.duden.de/`

### Category

breakage

### Describe the issue

The website is completely white when uBO is enabled. I guess this is caused by the recent filter update #15729

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 94651
  cosmetic: 42436
  scriptlet: 16744
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6024-0, now
    easylist: 64799-58, now
    easyprivacy: 30864-1181, now
    plowe-0: 3669-871, now
    ublock-abuse: 76-0, now
    ublock-badware: 4008-109, now
    ublock-filters: 31282-128, now
    ublock-privacy: 258-1, now
    ublock-quick-fixes: 583-12, now
    ublock-unbreak: 1896-44, now
    urlhaus-1: 12940-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 748 ms
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    duden.de: 1
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Its fixed now. Force update the filter lists to get the fix without waiting

@mapx-

**Comment by mapx-** [comment]
yes, it seems they removed the detection
`https://www.duden.de/modules/custom/duden_ads/js/aab.js`

test link 
https://www.duden.de/rechtschreibung/Shownotes

**Comment by okiehsch** [comment]
We had issues with mentor.duden before. 
https://github.com/uBlockOrigin/uAssets/issues/5807#issuecomment-501016542
I forgot to add an exception for it too, something to keep in mind for the future.
