### ISSUE TITLE
 EasyPrivacy The filter prevents Tencent Video from switching resolution

### ISSUE THREAD

**Issue by sanhu5** [uBlockOrigin/uAssets#15731]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://v.qq.com/x/cover/3kxhegr3qwcfgsx/c0024n2z7vh.html`

### Describe the issue

> 自带的EasyPrivacy 中 `&refer=http$script` 规则导致腾讯视频无法切换清晰度 

`&refer=http$script`
**The filter prevents Tencent Video from switching resolution**

### Screenshot(s)

无

### uBlock Origin version

uBlock Origin 1.45.2

### Browser name and version

Cent Browser 版本 5.0.1002.182（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)

### Settings

无

### Notes

无

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Full url being blocked?

**Comment by iam-py-test** [comment]
> Full url being blocked?

`https://h5vv6.video.qq.com/getvinfo` + a lot of parameters.
On my end, it is fixed by Quick Fixes (https://github.com/uBlockOrigin/uAssets/commit/78bf1ba829f6e1e96b9500ff1b8fba401ca03132)

**Comment by mapx-** [comment]
- ok then, it can be closed.
- @sanhu5 you didn't provide your setup, keep the default filter lists in uBO and test again. Report back (in english)
