### ISSUE TITLE
cutty.app: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#15737]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cutty.app/5tAGOHKF`

### Category

detection

### Describe the issue

This site detect uBo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/203071943-b098c911-fdae-4fc0-9b3e-cc44db60e05d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 97595
  cosmetic: 43560
  scriptlet: 16728
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist.to/easylist/easylist.txt: 64765-53, 2d.23h.43m
  default: 
    user-filters: 28-0, never
    IDN-0: 9190-1, 3d.21h.43m
    easylist: 64759-64758, 2d.23h.45m
    easyprivacy: 30853-1173, 2d.23h.44m
    plowe-0: 3670-869, 9d.9h.13m
    ublock-abuse: 76-0, 9d.9h.13m
    ublock-badware: 4003-109, 3d.21h.42m
    ublock-filters: 31248-140, 3d.21h.41m
    ublock-privacy: 258-1, 9d.9h.13m
    ublock-quick-fixes: 573-11, 23h.40m
    ublock-unbreak: 1895-45, 3d.21h.40m
    urlhaus-1: 13884-0, 23h.39m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 15 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 644 ms (selfie)
  maxAssetCacheWait: 361 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cdntechone.com: 1
    d192r5l88wrng7.cloudfront.net: 1
    googletagmanager.com: 1
    itecoust.com: 1
```
</details>

**Comment by king-iskan** [comment]
@JobcenterTycoon @Yuki2718 
I think this site/link need update, because last I open, adblock detection.
Thanks

**Comment by Yuki2718** [comment]
Yeah, had to update to `#@#ins.adsbygoogle`

**Comment by king-iskan** [comment]
> 

Work better

**Comment by l-eber-a-c-87** [comment]
Same problem, think they changed their detection method.
