### ISSUE TITLE
[nsfw] fr.spankbang.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15738]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fr.spankbang.com/1s5ey-b0cohk/playlist/favs?`

### Category

ads

### Describe the issue

There are ads at the bottom of the page and other little things. This site deserves a good cleaning ^^

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 204210
  cosmetic: 40948
  scriptlet: 18039
  html: 0
listset (total-discarded, last-updated): 
  default: 
    ublock-abuse: 76-2, 2h.43m
    ublock-badware: 4008-13, 2h.43m
    ublock-filters: 31281-205, 2h.43m
    ublock-privacy: 258-0, 2h.43m
    ublock-quick-fixes: 574-12, 2h.43m
    ublock-unbreak: 1896-4, 2h.43m
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  assetFetchTimeout: 60
  autoUpdateAssetFetchPeriod: 300
  extensionUpdateForceReload: true
  filterAuthorMode: true
  manualUpdateAssetFetchPeriod: 1
  popupPanelLockedSections: 39
  selfieAfter: 11
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 603 ms (selfie)
  maxAssetCacheWait: 460 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adtng.com: 1
    bestcontentfood.top: 2
    cloudflareinsights.com: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
Reset uBO to default setup, don't touch the settings, update all filter lists, test again.
In case you still get ads, post screenshots showing them.

**Comment by krystian3w** [comment]
If after reset again will be broken: https://github.com/uBlockOrigin/uAssets/issues/15695#issuecomment-1318771967

then reinstall addon in browser.
