### ISSUE TITLE
nicovideo.jp: breakage

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#15730]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nicovideo.jp/watch/sm40984309`

### Category

breakage

### Describe the issue

When `googletagmanager.com/gtm.js` is blocked, some buttons does not work.

Steps to Reproduce

(Account required)
1. Open the website.
2. Click on the ... symbol just above the video player.
3. Left-click on the second link in the pop-up window that appears.

When uBO is OFF

A new page will open.

When uBO is ON

Page does not open.

Notes

Of the following rules, only the rules that allow tracking have resolved the issue.

`@@||googletagmanager.com/gtm.js$script,domain=www.nicovideo.jp`
`@@||googletagmanager.com/gtm.js$script,redirect-rule,domain=www.nicovideo.jp`
`||googletagmanager.com/gtm.js$script,redirect=noopjs,important,domain=www.nicovideo.jp`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし](https://user-images.githubusercontent.com/86018494/202962942-13830187-7939-4a0f-8d43-cfda4516c33f.png)
![タイトルなし1](https://user-images.githubusercontent.com/86018494/202962948-47f3c50c-b2ca-4e60-bdab-5c9d5febc7e0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 94431
  cosmetic: 45509
  scriptlet: 16846
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    JPN-1: 8265-4, 24m
    easylist: 64783-83, 23m
    easyprivacy: 30861-1197, 37m
    plowe-0: 3668-875, 24m
    ublock-abuse: 76-0, 24m
    ublock-badware: 4008-109, 24m
    ublock-filters: 31278-123, 24m
    ublock-privacy: 258-1, 24m
    ublock-quick-fixes: 583-16, 24m
    ublock-unbreak: 1896-45, 24m
    urlhaus-1: 13725-0, 24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 260 ms
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    nicovideo.jp: 4
    amazon-adsystem.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    im-apps.net: 1
```
</details>

**Comment by stm-x** [comment]
I don't want to allow tracking for this minor issue, any suggestions?
(Yes, I know I can just right click and open a new tab, but that's a bit cumbersome.)

**Comment by stm-x** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
No other way than `@@||googletagmanager.com/gtm.js$script,domain=www.nicovideo.jp` as we can't touch `ClickInterceptor` (`nicovideo.jp##+js(rc, ClickInterceptor, , stay asap)` doesn't work).

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by stm-x** [comment]
> No other way than `@@||googletagmanager.com/gtm.js$script,domain=www.nicovideo.jp` as we can't touch `isInterceptEnabled` (`nicovideo.jp##+js(rc, ClickInterceptor, , stay asap)` doesn't work).

That' s unfortunate.
Thank you for your time.

**Comment by stm-x** [comment]
Good news.
With the renewal of the site, the above features have disappeared, so no more exceptions are needed.

I have blocked Google Tag Manager since yesterday and there seems to be no problem.

This is the best change I know of that Nico Nico has made.

**Comment by Yuki2718** [comment]
As far as I know the service just restarted after the attack, so maybe safer to watch for a while.

**Comment by stm-x** [comment]
> As far as I know the service just restarted after the attack, so maybe safer to watch for a while.

That's right.
Let's see how it goes for a month or so.

**Comment by Yuki2718** [comment]
@stm-x Do you still have GTM blocked and see no problem?

**Comment by stm-x** [comment]
I have blocked it for a long time, seems to be no problem.
FYI, I use the following rule.
`||googletagmanager.com/gtm.js$important,script,redirect=googletagmanager.com/gtm.js:5,domain=www.nicovideo.jp`

**Comment by Yuki2718** [comment]
Can you test for a while without redirect?

**Comment by stm-x** [comment]
> Can you test for a while without redirect?

Okay, This is correct, right?
I'll give it a week or so.
![タイトルなし](https://github.com/user-attachments/assets/e4df9801-a297-425c-a4d7-eb313d33a841)

**Comment by stm-x** [comment]
@Yuki2718 Looks fine to me.
I think the rule can be removed.

**Comment by Yuki2718** [comment]
Thanks, removed the exception.
