### ISSUE TITLE
vtm.be: detection

### ISSUE THREAD

**Issue by deknocky** [uBlockOrigin/uAssets#15734]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://vtm.be/vtmgo/afspelen/e67375eef-3cdc-4ac6-9e6a-db055f1e1f21`

### Category

detection

### Describe the issue

It says "Cannot play video because there is an adblocker active".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 93241
  cosmetic: 38595
  scriptlet: 16729
  html: 853
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32056-33, 29m
    ublock-badware: 4012-0, 28m
    ublock-privacy: 305-0, 27m
    ublock-abuse: 76-0, 26m
    ublock-unbreak: 1909-1, 25m
    ublock-quick-fixes: 579-12, 24m
    easylist: 64768-620, 23m
    easyprivacy: 30860-1710, 22m
    urlhaus-1: 13725-0, 21m
    plowe-0: 3669-3, 20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6273 ms
  maxAssetCacheWait: 2461 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    vtm.be: 1
    fwmrm.net: 1
    gemius.pl: 2
    litix.io: 4
    pushengage.com: 3
```
</details>

**Comment by mapx-** [comment]
Enable `NLD: EasyDutch`, test again, report back
