### ISSUE TITLE
imgur.com: ads

### ISSUE THREAD

**Issue by Zarconite** [uBlockOrigin/uAssets#15735]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://imgur.com/`

### Category

ads

### Describe the issue

Upon refreshing the page, there is an ad that pops in after around 5 seconds with the class "`Ad-SCTU`" and "`Ad sas Smart`", The picker can't seem to select these elements and blocking the element with `##.Ad-SCTU` doesn't seem to work either

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imgurad](https://user-images.githubusercontent.com/36591666/203063744-8edc5aec-354e-4076-9651-3115a77c3905.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 77784
  cosmetic: 38181
  scriptlet: 16326
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 17-0, never
    easylist: 64765-53, 2d.16h.11m
    easyprivacy: 30856-1171, 2d.16h.10m
    plowe-0: 3670-869, 6d.12h.28m
    ublock-abuse: 76-0, 1d.34m
    ublock-badware: 4003-109, 2d.12h.9m
    ublock-filters: 31244-116, 2d.12h.8m
    ublock-privacy: 258-1, 1d.33m
    ublock-quick-fixes: 576-12, 1d.31m
    ublock-unbreak: 1895-43, 2d.12h.7m
    urlhaus-1: 14460-0, 1d.32m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 302 ms
  maxAssetCacheWait: 169 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Zarconite** [comment]
Also visible within posts with the class `"Gallery-Content-AdSense`
<details>
<summary>Screenshot</summary>
![Screenshot_52](https://user-images.githubusercontent.com/36591666/203068851-2da53726-01bc-41c6-9fff-68e66b212249.png)
</details>

**Comment by iam-py-test** [comment]
> ```yml
> popupPanel: 
>  blocked: 0
> ```

Why is your log showing nothing as being blocked? Please make sure that you have uBlock Origin enabled on imgur.com

**Comment by Zarconite** [comment]
It looks to be switched on, but I've noticed that it's no longer blocking ads on other sites.. I'm unsure as to why this is happening though. I've forced an update and have tried disabling/enabling the blocker to no avail. Strange..
<details>
<summary>Screenshot</summary>

![Screenshot_52](https://user-images.githubusercontent.com/36591666/203119644-ecd31fdd-3d90-4736-90c9-3eaad7d9b072.png)


</details>

**Comment by iam-py-test** [comment]
Please reset uBlock Origin to [default settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section) and try again (you can export your configuration if you want)

**Comment by Zarconite** [comment]
Ah, that appears to have done the trick. Thanks!

**Comment by iam-py-test** [comment]
> Ah, that appears to have done the trick. Thanks!

I suspect that it might have been one of your 17 custom filters which was causing the issue, but that's just a guess.

**Comment by iam-py-test** [comment]
Yes, correct. (Although I was talking about their filters in "My filters")
