### ISSUE TITLE
sfchronicle.com: breakage

### ISSUE THREAD

**Issue by spladug** [uBlockOrigin/uAssets#15745]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sfchronicle.com/weather/article/rain-california-drought-17575691.php`

### Category

breakage

### Describe the issue

Article images do not show up. This seems true for most/all articles. Disabling uBlock Origin for the site brings the images back. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://user-images.githubusercontent.com/338853/203208318-a7b48e2a-090c-486f-a45c-b1821dc8ff66.png)
![imagen](https://user-images.githubusercontent.com/338853/203208283-56702f4c-989e-4262-a6a0-2b8b157e0568.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92396
  cosmetic: 38648
  scriptlet: 16731
  html: 834
listset (total-discarded, last-updated): 
  removed: 
    spa-0: null
    spa-1: null
  default: 
    user-filters: 4-0, never
    ublock-filters: 32036-45, 2d.52m
    ublock-badware: 4007-0, 2d.51m
    ublock-privacy: 286-0, 7d.22h.21m
    ublock-abuse: 76-0, 7d.22h.20m
    ublock-unbreak: 1908-1, 2d.50m
    ublock-quick-fixes: 591-0, 5h.48m
    easylist: 64767-618, 2d.9h.13m
    easyprivacy: 30860-1711, 2d.9h.12m
    urlhaus-1: 12940-0, 5h.47m
    plowe-0: 3674-3, 4d.9h.46m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 297 ms (selfie)
  maxAssetCacheWait: 108 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    sfchronicle.com: 4
    hdmtools.com: 2
    hearstnp.com: 2
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||aps.hearstnp.com/Scripts/loadAds.js$script,domain=sfchronicle.com`

@ryanbr
