### ISSUE TITLE
golem.de: ads

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#15740]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.golem.de/`

### Category

ads

### Describe the issue

A black friday ad marked as such with a green category is not filtered out.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/17909/203097410-9760a0bb-e991-408c-92ea-4d13e29e9adf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 109
filterset (summary): 
  network: 503107
  cosmetic: 245517
  scriptlet: 39185
  html: 891
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/no-cmyk/Search-Engine-Spam-Domains-Blocklist/master/blocklist.txt: 320241-3, 1d.6h.8m
    https://raw.githubusercontent.com/paulgb/BarbBlock/master/blacklists/adblock-plus.txt: 550-6, 4h.31m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-12, 1d.6h.7m
    adguard-generic: 65768-5833, 1d.2h.33m
    adguard-mobile: 8210-154, 1d.2h.32m
    adguard-spyware: 34272-2650, 1d.2h.30m
    adguard-spyware-url: 841-4, 1d.2h.31m
    adguard-annoyance: 61125-4323, 1d.2h.29m
    fanboy-thirdparty_social: 68-0, 3d.18h.43m
    fanboy-annoyance: 83092-67449, 3d.18h.42m
    fanboy-cookiemonster: 43370-202, 3d.18h.41m
    fanboy-social: 23433-31, 6d.2h.49m
    ublock-annoyances: 4811-10, 1d.2h.35m
    CHN-0: 28718-122, 1d.2h.34m
    POL-0: 7856-27, 4h.29m
    POL-2: 1279-16, 1d.6h.5m
    RUS-0: 39701-332, 1d.6h.4m
  default: 
    user-filters: 115-10, never
    ublock-filters: 32031-161, 1d.2h.28m
    ublock-badware: 4007-0, 1d.2h.27m
    ublock-privacy: 305-0, 2d.18h.3m
    ublock-abuse: 76-0, 2d.18h.2m
    ublock-unbreak: 1909-0, 1d.2h.26m
    ublock-quick-fixes: 582-1, 18h.25m
    easylist: 64767-888, 1d.19h.5m
    easyprivacy: 30850-12998, 3d.6h.8m
    urlhaus-1: 13725-0, 4h.28m
    plowe-0: 3668-365, 2d.7h.13m
    DEU-0: 6025-4, 4h.30m
filterset (user): [array of 115 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 65 redacted]
  removed: 
    behind-the-scene * * noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15275 ms (selfie)
  maxAssetCacheWait: 2713 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    golem.de: 9
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    stroeerdigitalgroup.de: 2
```
</details>

**Comment by iam-py-test** [comment]
I can reproduce
![image](https://user-images.githubusercontent.com/84232764/203108004-224f3fc3-576c-42a0-a059-d7890e11ec96.png)
@yoshimo please add this filter to your _My filters_ tab:
```adblock
golem.de##.nmoatosgaua
```

**Comment by mapx-** [comment]
that class seems to be random

Test
`golem.de##[data-article-id]:has([class]:matches-css-before(content:/ANZEIGE/))`
