### ISSUE TITLE
shop.critrole.com: breakage

### ISSUE THREAD

**Issue by cam443** [uBlockOrigin/uAssets#15743]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://shop.critrole.com/collections/apparel/products/beauty-of-exandria-the-archives-caleb-widogast-blazer`

### Category

breakage

### Describe the issue

Typically on this site, a Size Guide button will appear below the size buttons. The Size Guide doesn't appear using uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-21 at 10-53-44 Beauty of Exandria – The Archives Caleb Widogast Blazer](https://user-images.githubusercontent.com/49173904/203136662-86e073cc-355e-4f50-be61-3583c90792d7.png)
![Screenshot 2022-11-21 at 10-54-11 Beauty of Exandria – The Archives Caleb Widogast Blazer](https://user-images.githubusercontent.com/49173904/203136668-2b06f95c-22aa-41e4-b327-8b773e87312c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b6
Firefox: 107
filterset (summary): 
  network: 93339
  cosmetic: 38654
  scriptlet: 16735
  html: 834
listset (total-discarded, last-updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.10h.10m
  default: 
    user-filters: 10-1, never
    ublock-filters: 32061-45, 2h.6m
    ublock-badware: 4012-0, 2h.5m
    ublock-privacy: 286-0, 10d.18h.1m
    ublock-abuse: 76-0, 10d.18h
    ublock-unbreak: 1909-1, 2h.4m
    easylist: 64757-618, 3d.10h.18m
    easyprivacy: 30854-1710, 3d.10h.17m
    urlhaus-1: 13884-0, 22h.8m
    plowe-0: 3670-3, 7d.6h.31m
    ublock-quick-fixes: 584-0, 22h.9m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
urlRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    dttrk.com: 1
    facebook.net: 1
    geojs.io: 1
    google-analytics.com: 1
    google.com: 13
    googletagmanager.com: 1
    payments-amazon.com: 1
    pinimg.com: 1
    shopifycloud.com: 14
    shopifysvc.com: 2
```
</details>

**Comment by mapx-** [comment]
add & test

`@@||get.geojs.io/v1/ip/geo.json$xhr,domain=shop.critrole.com`

@ryanbr

**Comment by cam443** [comment]
> add & test
> 
> `@@||get.geojs.io/v1/ip/geo.json$xhr,domain=shop.critrole.com`
> 
> @ryanbr

Yup that worked. Thanks!
