### ISSUE TITLE
novelupdates.com: ads

### ISSUE THREAD

**Issue by learning192** [uBlockOrigin/uAssets#15741]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.novelupdates.com/`

### Category

ads

### Describe the issue

There is a leftover of an ad on the site. I tried updating my filters but it doesn't change anything. I tried to add adguard base filter but nothing changed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20221121_184953](https://user-images.githubusercontent.com/118753911/203098723-fc9a9cb1-71b2-49c2-995b-ec4899373550.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 107
filterset (summary): 
  network: 94707
  cosmetic: 27883
  scriptlet: 16781
  html: 855
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32166-268, 4h.20m
    ublock-badware: 4011-0, 4h.20m
    ublock-privacy: 305-1, 4h.20m
    ublock-abuse: 76-0, 4h.20m
    ublock-unbreak: 1914-1, 4h.20m
    ublock-quick-fixes: 581-0, 4h.20m
    adguard-mobile: 8213-166, 4h.21m
    easylist: 64799-17773, 4h.19m
    easyprivacy: 30864-1720, 4h.19m
    urlhaus-1: 13725-0, 4h.19m
    plowe-0: 3669-3, 4h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2868 ms
  maxAssetCacheWait: 472 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    uniconsent.com: 2
```
</details>

**Comment by ghajini** [comment]
uncheck this setting in ublock settings,that option is enabled by default in mobile environment
![Uploading Screenshot_20221121-214017-873.png…]()

**Comment by ghajini** [comment]
enable
