### ISSUE TITLE
youtube.com: nuisance

### ISSUE THREAD

**Issue by ArashiDragon** [uBlockOrigin/uAssets#15749]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=wIvENFGPBh8`

### Category

nuisance

### Describe the issue

The above address is just one example, but the problem happens on any youtube video I watch. I can eliminate the problem for 1 shot, but I do not know how to correctly format a filter to account for changing data in the offending line.
If I use the element picker and accept the line, it adds this to the filter list:
```
! 2022-11-22 https://www.youtube.com
www.youtube.com##.ls10ef838c2ffr.ls10ef838c2f-block.hidden.ls10ef838c2f-first-block
```
This will work until a refresh or new video starts.

Steps to reproduce the problem:

1. Start video: black (or white, depending on if dark mode or not) box across the bottom of video: If I use uBO Element picker it pulls this:
 `##.lsedf9daa1b0fr.lsedf9daa1b0-block.hidden.lsedf9daa1b0-first-block`
 
2. Refresh same video, new line becomes this:
 `##.ls10ef838c2ffr.ls10ef838c2f-block.hidden.ls10ef838c2f-first-block`

3. Filter just needs to wildcard like so to work: `##.<insert wildcard here>-block.hidden.<insert wildcard here>-first-block` 

As a note, I've done my best to search for similar issues, but wasn't able to find one, I even manually skimmed the first 5 pages to see if something matched.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![youtube_annoying_bar](https://user-images.githubusercontent.com/966771/203258966-2035efbb-395c-4608-94ca-32a9b32b2a71.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 92386
  cosmetic: 38643
  scriptlet: 16723
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.16h.49m
  default: 
    user-filters: 2-0, never
    easylist: 64767-53, 3d.10h.50m
    easyprivacy: 30854-1171, 3d.10h.49m
    plowe-0: 3670-869, 8d.14h.12m
    ublock-abuse: 76-0, 2d.12h.51m
    ublock-badware: 4003-109, 3d.10h.47m
    ublock-filters: 31244-116, 3d.10h.46m
    ublock-privacy: 258-1, 2d.12h.50m
    ublock-quick-fixes: 576-12, 16h.45m
    ublock-unbreak: 1895-43, 3d.10h.48m
    urlhaus-1: 12940-0, 16h.46m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 116 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1046 ms
  maxAssetCacheWait: 476 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    youtube.com: 32
    doubleclick.net: 2
    google.com: 5
    googlevideo.com: 2
    ytimg.com: 1
```
</details>

**Comment by krystian3w** [comment]
> Filter just needs to wildcard like so to work: ##.<insert wildcard here>-block.hidden.<insert wildcard here>-first-block

if problem don't gone after clear all youtube+google data try test:

```adb
www.youtube.com###movie_player [class*="-block"].hidden.[class*="-first-block"]
```

https://www.w3schools.com/css/css_attribute_selectors.asp
