### ISSUE TITLE
omano.de: ads

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#15756]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://www.omano.de/`
`http://www.eberbach-channel.de/`

### Category

ads

### Describe the issue

ads - see screenshot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

`https://user-images.githubusercontent.com/15193811/203343490-cb429afc-17ad-41ac-9d1c-f97e3f8dbafc.jpg`

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 94174
  cosmetic: 43648
  scriptlet: 19937
  html: 878
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4818-4, 29m
    ublock-quick-fixes: 591-0, 29m
  default: 
    user-filters: 2-0, never
    ublock-filters: 32067-58, 29m
    ublock-badware: 4012-0, 29m
    ublock-privacy: 305-0, 29m
    ublock-unbreak: 1911-1, 29m
    easylist: 64739-629, 29m
    easyprivacy: 30869-1720, 29m
    plowe-0: 3669-3, 29m
    DEU-0: 6025-2, 29m
    ublock-abuse: 77-0, 29m
    urlhaus-1: 12135-0, 29m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1097 ms (selfie)
  maxAssetCacheWait: 309 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    omano.de: 2
    doubleclick.net: 2
    github.com: 1
    googlesyndication.com: 3
    youtube.com: 7
```
</details>

**Comment by okiehsch** [comment]
`eberbach-channel.de,omano.de##[src*="AdServer"]`
@khrin
