### ISSUE TITLE
dropbox.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#15751]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dropbox.com/home`

### Category

nuisance

### Describe the issue

Intrusive prompt to upgrade your free Dropbox account. You have to dismiss the offer every time you visit the site. The filter:

dropbox.com##.dig-Modal-overlay.ReactModal__Overlay--after-open.ReactModal__Overlay

blocks the prompt, but it also breaks all useful popups.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-22 at 10-51-06 Files - Dropbox](https://user-images.githubusercontent.com/101707608/203271554-42f98b3f-0d9d-4cb4-939a-3987333de3e6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 339030
  cosmetic: 237539
  scriptlet: 37627
  html: 878
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 35913-595, 19h.11m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 5d.1h.5m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 19h.10m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 33-0, never
    https://www.i-dont-care-about-cookies.eu/abp/: 25517-5, 23h.17m
    adguard-generic: 65778-5533, 23h.24m
    adguard-mobile: 8213-187, 23h.23m
    adguard-spyware: 34274-2762, 23h.22m
    adguard-spyware-url: 841-3, 23h.21m
    block-lan: 44-0, 5d.1h.5m
    curben-phishing: 149814-12, 23h.14m
    curben-pup: 187-0, 23h.13m
    adguard-annoyance: 61138-5402, 23h.20m
    adguard-social: 18992-1106, 23h.19m
    fanboy-thirdparty_social: 68-0, 5d.1h.5m
    fanboy-annoyance: 82792-67164, 5d.1h.5m
    fanboy-cookiemonster: 43070-9305, 5d.1h.5m
    fanboy-social: 23400-31, 5d.1h.5m
    ublock-annoyances: 4811-6, 23h.18m
    dpollock-0: 11391-483, 5d.1h.5m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32056-106, 23h.29m
    ublock-badware: 4012-0, 23h.28m
    ublock-privacy: 305-0, 23h.27m
    ublock-abuse: 76-4, 23h.26m
    ublock-unbreak: 1909-2, 23h.25m
    ublock-quick-fixes: 590-0, 23h.16m
    easylist: 64731-1011, 5d.1h.5m
    easyprivacy: 30853-13208, 5d.1h.5m
    urlhaus-1: 13725-0, 23h.15m
    plowe-0: 3673-5, 5d.1h.5m
    GRC-0: 1004-1, 19h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17636 ms (selfie)
  maxAssetCacheWait: 3689 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    dropbox.com: 37
    127.0.0.1: 3
    google.com: 1
    google.gr: 3
```
</details>

**Comment by krystian3w** [comment]
Your proposition can break whole react modals on page.

**Comment by DimitrisKalaboukas** [comment]
@krystian3w Yeah, this filter works fine, thank you!

**Comment by DimitrisKalaboukas** [comment]
@mapx- @stephenhawk8054 Based on https://github.com/uBlockOrigin/uAssets/discussions/22280 and https://github.com/uBlockOrigin/uAssets/discussions/27090, you could also add:

`||dropbox.com/plans*=link_campaign_format$popup`
`dropbox.com##+js(trusted-click-element, .campaign-format-modal button[data-uxa-log="secondary-cta-button"], , 1000)`
`dropbox.com##+js(trusted-click-element, .ReactModalPortal:has(a[href*="/buy/plus"]):has(a[href*="/try/teams"]) button[data-testid="digModalCloseButton"], , 2000)`
`dropbox.com##+js(trusted-click-element, .ReactModalPortal:has(img[src*="/will/mobile-qr-code"]) button, , 2000)`
`dropbox.com##+js(trusted-set-local-storage-item, dbx_previews_log_out_download_modal, 2147483647000)`

**Comment by DimitrisKalaboukas** [comment]
@mapx- @stephenhawk8054 Based on https://github.com/uBlockOrigin/uAssets/discussions/22280 and https://github.com/uBlockOrigin/uAssets/discussions/27090, you could also add:

```
||bolt.dropbox.com/*/notify/subscribe$xhr
||dropbox.com/*/get_best*campaigns$xhr
||dropbox.com/plans*=link_campaign_format$popup
dropbox.com##+js(set-local-storage-item, mapslitepromosdismissed, 1)
dropbox.com##+js(trusted-click-element, .campaign-format-modal button[data-uxa-log="secondary-cta-button"], , 1000)
dropbox.com##+js(trusted-click-element, .ReactModalPortal:has(a[href*="/buy/plus"]):has(a[href*="/try/teams"]) button[data-testid="digModalCloseButton"], , 2000)
dropbox.com##+js(trusted-click-element, .ReactModalPortal:has(img[src*="/will/mobile-qr-code"]) button, , 2000)
dropbox.com##+js(trusted-set-local-storage-item, dbx_previews_log_out_download_modal, 2147483647000)
```
