### ISSUE TITLE
cimri.com: breakage

### ISSUE THREAD

**Issue by ChelebiTech** [uBlockOrigin/uAssets#15750]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.cimri.com/`

### Category

breakage

### Describe the issue

Web page not showing anything if Ublock is active. if i close ublock webpage seems ok.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Firefox: 107
filterset (summary): 
  network: 93713
  cosmetic: 47225
  scriptlet: 17816
  html: 834
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 46m
  default: 
    user-filters: 5-0, never
    ublock-filters: 32036-54, 1d.20h.51m
    ublock-badware: 3972-0, 3d.1h
    ublock-privacy: 286-0, 11d.1h.23m
    ublock-abuse: 76-0, 11d.10h.44m
    ublock-unbreak: 1908-1, 3d.59m
    easylist: 64757-637, 3d.1h.1m
    easyprivacy: 30855-1714, 3d.1h.2m
    plowe-0: 3669-3, 10d.17h.32m
    TUR-0: 11313-11, 3d.58m
    urlhaus-1: 12699-0, 44m
    ublock-quick-fixes: 593-0, 47m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
- update uBO to the last version 1.45.2
- update ALL filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- test again
