### ISSUE TITLE
4pda.to: ads

### ISSUE THREAD

**Issue by leosher** [uBlockOrigin/uAssets#15758]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://4pda.to/`

### Category

ads

### Describe the issue

Ads is shown. see screenshot  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Безымянный](https://user-images.githubusercontent.com/37189525/203386385-c0f7f202-5bee-468e-bc55-48b5e57e1515.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 106
filterset (summary): 
  network: 108594
  cosmetic: 59772
  scriptlet: 17931
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    RUS-0: 39610-11, 20h.58m
    easylist: 64687-66, 5d.20h.39m
    easyprivacy: 30850-1283, 5d.20h.38m
    plowe-0: 3670-873, 11d.20h.55m
    ublock-abuse: 76-1, 2d.6h.3m
    ublock-badware: 4003-108, 3d.18h.29m
    ublock-filters: 31247-144, 2d.22h.31m
    ublock-privacy: 258-1, 2d.22h.30m
    ublock-quick-fixes: 584-12, 15m
    ublock-unbreak: 1895-43, 2d.22h.29m
    urlhaus-1: 12135-0, 16m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    4pda.to: 3
    google-analytics.com: 1
    yadro.ru: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
The webmasters of this site routinely bypass ad blockers. Therefore, the rules for this site are contained in [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) (left-click to subscribe).
