### ISSUE TITLE
torrentigo.net: privacy

### ISSUE THREAD

**Issue by docHOLO** [uBlockOrigin/uAssets#15765]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://torrentigo.net/`

### Category

privacy

### Describe the issue

Instead of torrents downloading trojan exe files. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 107
filterset (summary): 
  network: 109007
  cosmetic: 59792
  scriptlet: 17935
  html: 839
listset (total-discarded, last updated): 
  default: 
    user-filters: 20-0, never
    ublock-filters: 32051-34, 3d.35m
    ublock-badware: 4012-0, 3d.34m
    ublock-privacy: 286-0, 12d.2h.51m
    ublock-abuse: 76-0, 12d.2h.50m
    ublock-unbreak: 1909-1, 3d.33m
    easylist: 64776-633, 21h.19m
    easyprivacy: 30864-1821, 2h.8m
    urlhaus-1: 12415-0, 2h.5m
    plowe-0: 3669-3, 2h.9m
    RUS-0: 39625-48, 13h.16m
    ublock-quick-fixes: 602-12, 2h.7m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1391 ms (selfie)
  maxAssetCacheWait: 787 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    clairpixum.com: 1
    yadro.ru: 2
```
</details>

**Comment by krystian3w** [comment]
```adb
||torrentigo.net/*.exe$all,important
```

maybe safe lives.

**Comment by okiehsch** [comment]
Steps to reproduce?

**Comment by okiehsch** [comment]
The green download buttons are not working on my end, so I am not sure how to try to download a torrent on the site.

**Comment by docHOLO** [comment]
> The green download buttons are not working on my end, so I am not sure how to download a torrent on the site.

you pick this one?
![изображение](https://user-images.githubusercontent.com/110890858/203522307-94db05f7-f150-45b6-ba68-89ba33bac21a.png)

**Comment by docHOLO** [comment]
Downloaded it and here it is on VT. It says it checked before as "adobe-after-effects-cc-2019"
https://www.virustotal.com/gui/file/f21b040f7c47d8d3d9c1f0ef00f09e69f2c3f0e19d91988efc0ddd4833ced121
![изображение](https://user-images.githubusercontent.com/110890858/203523189-f96d1c7c-f494-40db-8a01-b5dfc2e32d45.png)

**Comment by docHOLO** [comment]
> I am not sure how to download a torrent on the site.

It is downloading not torrent files but exe with virus. Here downloading link. Maybe it will work for you to check this
https://torrentigo.net/index.php?do=go&url=aHR0cHM6Ly9kbXRlY2gwNS5jb20vdFBKdWgwSTRLWGRqNFZMRDhiZnJqM3l1TjRzTTkzMGZ0Yk9nU1BRMy9zLzY3NTQvaC83NTNlM2Ivby8xNDUvc3ViLzA%2FYT0xJmFtcDtmPVdhdGNoJTIwRG9ncyUyMDImYW1wO3U9aHR0cHM6Ly90b3JyZW50aWdvLm5ldC91cGxvYWRzL2ZpbGVzLzIwMTctMDMvMTQ4ODM1NTk2N193YXRjaC1kb2dzLTItZGlnaXRhbC1kZWx1eGUtZWRpdGlvbi50b3JyZW50aHR0cHM6Ly90b3JyZW50aWdvLm5ldC91cGxvYWRzL2ZpbGVzLzIwMTctMDQvMTQ5MTMxNDIyNV9kZWFkLXNwYWNlLWFudGhvbG9neS50b3JyZW50aHR0cHM6Ly90b3JyZW50aWdvLm5ldC91cGxvYWRzL2ZpbGVzLzIwMTctMDQvMTQ5MjA4ODMyOV93YXRjaC1kb2dzLTItZGlnaXRhbC1kZWx1eGUtZWRpdGlvbi50b3JyZW50aHR0cHM6Ly90b3JyZW50aWdvLm5ldC91cGxvYWRzL2ZpbGVzLzIwMTctMDUvMTQ5NTU3OTE2OF93YXRjaC1kb2dzLTItZGlnaXRhbC1kZWx1eGUtZWRpdGlvbi50b3JyZW50

**Comment by okiehsch** [comment]
Ok, I see I tried the wrong button. I can't read russian.

**Comment by okiehsch** [comment]
@dimisa-RUAdList youhave filters for the site in your list, what do you think?

If it's up to me I consider the site a badware risk and would block it, but I would like to hear your opinion.

**Comment by dimisa-RUAdList** [comment]
I block these sites: https://github.com/easylist/ruadlist/commit/d89cf8c8895075647fbdfc19a160957714d2c5d3
