### ISSUE TITLE
argos.co.uk: breakage

### ISSUE THREAD

**Issue by 1Mark** [uBlockOrigin/uAssets#15760]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.argos.co.uk/webapp/wcs/stores/servlet/DoLookupAddress`

### Category

breakage

### Issue
I'm trying to choose a delivery date however when I click on a cell nothing happens.

### Fix
Adding
`@@||www.argos.co.uk/utag/utag.sync.js$script,domain=www.argos.co.uk` 

OR
`www.argos.co.uk https://www.argos.co.uk/utag/utag.sync.js script allow`

Not sure which is prefered 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Each time I choose a cell there is no visual feedback

![image](https://user-images.githubusercontent.com/15360245/203434486-5810fc23-9d02-4cad-902e-c779784651b0.png)

After allowing the js it gave visual feedback after choosing a cell and looked like this 

![image](https://user-images.githubusercontent.com/15360245/203435337-0f5b92c2-ba01-4ee8-b6ec-559f97b583be.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91718
  cosmetic: 38525
  scriptlet: 16743
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 64739-54, 6m
    easyprivacy: 30869-1171, 5m
    plowe-0: 3669-870, 5m
    ublock-abuse: 77-0, 5m
    ublock-badware: 4008-109, 5m
    ublock-filters: 31289-119, 5m
    ublock-privacy: 258-1, 5m
    ublock-quick-fixes: 584-13, 5m
    ublock-unbreak: 1898-43, 5m
    urlhaus-1: 12135-0, 5m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 722 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    argos.co.uk: 1
    ascpqnj-oam.global.ssl.fastly.net: 1
    bing.com: 1
    facebook.net: 1
    foresee.com: 1
    gbqofs.com: 1
    go-mpulse.net: 2
    googletagmanager.com: 4
    ist-track.com: 1
    pinimg.com: 1
    sc-static.net: 1
    tealiumiq.com: 2
    tiktok.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
