### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by MrNice0** [uBlockOrigin/uAssets#15767]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Describe the issue

When the ad block is enabled it gives an infinite loading page but when it is disabled it loads in fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20221123-105927_Firefox](https://user-images.githubusercontent.com/118887706/203506758-d67d8a8b-cf80-425c-aaf1-fb7abae4e7f4.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 106
filterset (summary): 
  network: 93651
  cosmetic: 27883
  scriptlet: 16791
  html: 836
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 32163-268, 1d.14h.54m
    ublock-badware: 4011-0, 1d.14h.53m
    ublock-privacy: 286-1, 9d.19h.36m
    ublock-abuse: 76-0, 9d.19h.35m
    ublock-unbreak: 1914-1, 1d.14h.52m
    ublock-quick-fixes: 591-1, 1d.2h.16m
    adguard-mobile: 8215-166, 1d.14h.55m
    easylist: 64761-17772, 3d.16h.57m
    easyprivacy: 30861-1720, 3d.16h.54m
    urlhaus-1: 12699-0, 1d.2h.12m
    plowe-0: 3670-3, 9d.19h.29m
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 296 ms (selfie)
  maxAssetCacheWait: 428 ms
popupPanel: 
  blocked: 123
  blockedDetails: 
    1rx.io: 7
    4dex.io: 8
    a-mo.net: 7
    adform.net: 7
    adnxs.com: 14
    adxpremium.services: 7
    creativecdn.com: 7
    criteo.com: 9
    criteo.net: 13
    doubleclick.net: 7
    google.com: 1
    google.de: 1
    googlesyndication.com: 8
    googletagmanager.com: 1
    omnitagjs.com: 7
    onetag-sys.com: 7
    setupad.com: 4
    setupad.net: 8
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update the filter lists and try again

**Comment by MrNice0** [comment]
> Force update the filter lists and try again

I tried it didn't work unless I did it wrong

**Comment by JobcenterTycoon** [comment]
Add-ons -> uBlock Origin -> settings -> filterlists -> click on the clock and after this on update

Please note: additional anti tracking addons or the firefox strict tracking protection can trigger the anti adblock too.

**Comment by MrNice0** [comment]
> Add-ons -> uBlock Origin -> settings -> filterlists -> click on the clock and after this on update
> 
> Please note: additional anti tracking addons, adblocker DNS server or the firefox strict tracking protection can trigger the anti adblock too.

Ah Ok I did it right but I'm using Firefox so that may have caused it to go off

**Comment by MrNice0** [comment]
Yea firefox was the culprit, thank you @JobcenterTycoon

**Comment by Rifty888** [comment]
Not working for me.
