### ISSUE TITLE
https://dood.re detects uBO

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#15762]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://dood.re/d/ym2s2npetnox

### Describe the issue

1. Go to https://urlfly.net/view/A8qTOqRc1d
2. Click on the "dood.re" link.
3. It takes us to https://dood.re/d/ym2s2npetnox.
4. Here the uBO is detected and download is disabled. When I disable the uBO, the download is enabled.

### uBlock Origin version

1.44.0

### Browser name and version

Chrome v 104.xx

### Settings

All default settings.

**Comment by blazesprings** [comment]
I have enabled "annoyance" filters and uBO is updated.

**Comment by blazesprings** [comment]
Update : I had enabled "fuckfuckadblock", disabling which now the issue doesn't appear. Closing. Thanks :)

**Comment by krystian3w** [comment]
@bogachenko
