### ISSUE TITLE
la7.it/tagada preview video images missing

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#1576]
`http://www.la7.it/tagada`

### Describe the issue

preview video images missing

### Versions

- FF / chrome last beta versions
- uBlock Origin version: last dev versions

### Settings

normal setup

**Comment by mapx-** [comment]
@Khrin @ryanbr

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/80f2a8b1b15710553a1e57311054945394d29986
