### ISSUE TITLE
diigo.com: breakage

### ISSUE THREAD

**Issue by mysheepb** [uBlockOrigin/uAssets#15768]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.diigo.com/user/mysheepb`

### Category

breakage

### Describe the issue

clicking the "three dots" for more features (from the thrid item onwards) does not result in a manual for selection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 106
filterset (summary): 
  network: 91562
  cosmetic: 38629
  scriptlet: 16739
  html: 854
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32050-45, 1d.1m
    ublock-badware: 4012-0, 1d
    ublock-privacy: 305-0, 5d.2h.12m
    ublock-abuse: 76-0, 5d.2h.11m
    ublock-unbreak: 1909-0, 23h.59m
    easylist: 64720-615, 5d.16h.51m
    easyprivacy: 30850-1711, 5d.16h.50m
    urlhaus-1: 12135-0, 7h.58m
    plowe-0: 3673-3, 6d.4h.2m
    ublock-quick-fixes: 591-1, 7h.57m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 31 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 809 ms (selfie)
  maxAssetCacheWait: 538 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Were are the 3 points ? or is it available only for paid accounts ?

However I noted another breakage (ot the same..) => clicking on "save to my library" was broken

add & test

`@@||google.com/adsense/search/ads.js$script,domain=diigo.com`

**Comment by ghajini** [comment]
where's "save to library" option btw

**Comment by mapx-** [comment]
the icon on the right side of every row / item

![image](https://user-images.githubusercontent.com/10303732/203560302-c7ac733b-da45-47a3-a31c-910d59edbec7.png)
