### ISSUE TITLE
rmweb.co.uk: ads

### ISSUE THREAD

**Issue by TheGitNiall** [uBlockOrigin/uAssets#15775]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rmweb.co.uk/discover/1323/`

### Category

ads

### Describe the issue

Ad still appears at the top of the screen
![Capture](https://user-images.githubusercontent.com/118909554/203569097-b16610d8-8694-41e5-8bfc-74b0ae9ed15b.PNG)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92056
  cosmetic: 38532
  scriptlet: 16733
  html: 854
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32248-230, 19m
    ublock-badware: 4012-0, 19m
    ublock-privacy: 305-0, 19m
    ublock-abuse: 77-0, 19m
    ublock-unbreak: 1912-1, 19m
    easylist: 64772-622, 19m
    easyprivacy: 30872-1710, 19m
    urlhaus-1: 12447-0, 19m
    plowe-0: 3669-3, 19m
    ublock-quick-fixes: 591-0, 19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 63118 ms (selfie)
  maxAssetCacheWait: 2380 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    amazon-adsystem.com: 1
    automatad.com: 2
    connatix.com: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    quantserve.com: 1
```
</details>

**Comment by TheGitNiall** [comment]
Since the fix has been applied, the pictures are no longer rendered on the page.  The pictures can be restored by unticking the "Parse and enforce cosmetic filters" box.  The hope, when originally reporting this problem was to remove purely the box that appeared, in this case containing "That's 52 Magazines a year, etc".  
![With cosmetic filter](https://user-images.githubusercontent.com/118909554/203634215-031a6e31-9d41-4481-90e4-92afeeffd592.PNG)

Obviously, the following page is what is required:

![Without cosmetic filter](https://user-images.githubusercontent.com/118909554/203634254-ea7887be-92fb-4038-9b97-e61e58036daf.PNG)

Maybe, instead of saying that the ad appeared at the top of the screen, I should have pointed out that that ad appears to be a pop-up window, as it has the "X", in the top right-hand corner, to remove it.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3ff32e5cad5998efd02930780c4c04cf4f438d9f
