### ISSUE TITLE
samash.com: breakage

### ISSUE THREAD

**Issue by skstrobel** [uBlockOrigin/uAssets#15771]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.samash.com/checkout/#shipping`

### Describe the issue

After adding an item to the cart, viewing the cart and clicking "Proceed to checkout", the progress indicator spins forever.  This makes it impossible to check out.  Disabling uBlock and reloading the page allows it to work normally.

I am not aware of any advertisements on the samash.com site, other than what is expected (and perhaps desired) when shopping at a music store, so I think uBlock could be disabled for the entire site.

### uBlock Origin version

1.44.4

### Browser name and version

Google Chrome 107.0.5304.107 on Windows 10

### Settings

None

### Notes

I reported the issue to the Sam Ash web developers.

**Comment by mapx-** [comment]
Test this filter

`||samash.com^$script,redirect-rule=noopjs`
