### ISSUE TITLE
blog.cryptowidgets.net: breakage

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15778]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blog.cryptowidgets.net/post/what-is-tezos-xtz--live-price`

### Category

breakage

### Describe the issue

if enable adblock, the button to continue to the next link and the time counter doesn't work. of course not working. may i ask your solution? Thank you

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/114012899/203617832-ceb5063c-8bf4-4e81-8afd-2635bf2844a7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91972
  cosmetic: 38626
  scriptlet: 16756
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-0, never
    easylist: 64799-53, 2d.4h.19m
    easyprivacy: 30864-1171, 2d.4h.19m
    plowe-0: 3669-870, 2d.4h.19m
    ublock-abuse: 76-0, 2d.4h.19m
    ublock-badware: 4008-109, 2d.4h.19m
    ublock-filters: 31282-117, 2d.4h.19m
    ublock-privacy: 258-1, 2d.4h.19m
    ublock-quick-fixes: 584-12, 2h
    ublock-unbreak: 1896-43, 2d.4h.19m
    urlhaus-1: 12447-0, 1h.59m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1045 ms (selfie)
  maxAssetCacheWait: 1008 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    bannertrack.net: 1
    copyrightcontent.org: 1
    d3u598arehftfk.cloudfront.net: 1
    demand.supply: 1
    doubleclick.net: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    vdo.ai: 1
    wtg-ads.com: 1
    www.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
I guess you tested other link and then landed on this page => just provide that first link

**Comment by hunterkais** [comment]
this first link
https://t.co/iZjozik6MR

**Comment by mapx-** [comment]
I guess still the wrong link and you should have some different one not a `t.co` one

**Comment by hunterkais** [comment]
I'm also confused about which link to choose, because the original link is hidden.  but I try to make my own link on the website.  here is the link
http://earnow.online/8e6lQK2

**Comment by mapx-** [comment]
add

```
blog.cryptowidgets.net##+js(ra, disabled, .btn-primary)
blog.cryptowidgets.net##input[type="hidden"]:style(display: block !important;)
```

when you arrive on the page above just click "please wait"

**Comment by hunterkais** [comment]
Thanks, it's work.

**Comment by hunterkais** [comment]
> add
> 
> ```
> blog.cryptowidgets.net##+js(ra, disabled, .btn-primary)
> blog.cryptowidgets.net##input[type="hidden"]:style(display: block !important;)
> ```
> 
> when you arrive on the page above just click "please wait"

Sir, I think must update again, step 4 & 5 now condition same with condition step 3 before. Button not working if not click ads. 
Many thanks
