### ISSUE TITLE
shorttrick.in: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15776]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.shorttrick.in/how-you-can-get-personal-loan-for-cibil-score-less-than-550/`

### Category

detection

### Describe the issue

I can't access the downloads (it might be a good idea to clean up the site :;)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/203572494-99b83567-ffc7-4a37-8e39-82ea3a6b9e2a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 112063
  cosmetic: 47427
  scriptlet: 16808
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30146-28, 2h.12m
    easylist: 64772-82, 2h.12m
    easyprivacy: 30872-1555, 2h.12m
    plowe-0: 3669-895, 2h.12m
    ublock-abuse: 77-1, 2h.12m
    ublock-badware: 4008-126, 2h.12m
    ublock-filters: 31469-232, 2h.12m
    ublock-privacy: 258-1, 2h.12m
    ublock-quick-fixes: 584-193, 2h.12m
    ublock-unbreak: 1899-44, 2h.12m
    urlhaus-1: 12415-0, 2h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 145 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    shorttrick.in: 2
    googlesyndication.com: 2
    highperformancecpmgate.com: 1
    profitabledisplayformat.com: 7
    quantcast.com: 1
    viglink.com: 1
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
I already added a filter for poplinks too
https://github.com/uBlockOrigin/uAssets/commit/62b34e212677630c7b33ddd0edb6304878bdda9a

try updating again, maybe it wasn't updated yet

**Comment by advertblocker** [comment]
```
shorttrick.in##+js(noeval-if, chp_ad)
```
