### ISSUE TITLE
Black Friday Yahoo ad

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#15774]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

www.yahoo.com

### Describe the issue

There is a giant black friday ad on the yahoo homepage that isn't being blocked.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 107.0

### Settings

I use this custom filter https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
I also have a few thing set under "my filters" as well
[my-ublock-static-filters_2022-11-23_05.42.21.txt](https://github.com/uBlockOrigin/uAssets/files/10076008/my-ublock-static-filters_2022-11-23_05.42.21.txt)

### Notes

The ad can be gotten rid of using the element picker, however this leaves giant white bars on the sides of the page and the top as well. I have tried purging ublock origin caches and downloading them again, has no effect.

**Comment by mapx-** [comment]
@ryanbr
