### ISSUE TITLE
free-telecharger.link: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15773]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.free-telecharger.link/films-dvdrip-bdrip/143335-black-adam-hdrip.html`

### Category

Nuisances, residues, false links

### Describe the issue

Nuisances, residues, false links

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/203560085-ace879f2-71e3-4fe7-868e-f7e6949ca8fa.png)

![image](https://user-images.githubusercontent.com/50231020/203560214-f6527b21-5c5d-4b61-b900-1e5bb815739c.png)

![image](https://user-images.githubusercontent.com/50231020/203560260-ec04e751-e3c1-4f4a-ad8d-9cf6a80087c7.png)

![image](https://user-images.githubusercontent.com/50231020/203560361-566df218-7e4c-4b03-92a2-542a59f3e483.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 112063
  cosmetic: 47427
  scriptlet: 16808
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30146-28, 1h.12m
    easylist: 64772-82, 1h.12m
    easyprivacy: 30872-1555, 1h.12m
    plowe-0: 3669-895, 1h.12m
    ublock-abuse: 77-1, 1h.12m
    ublock-badware: 4008-126, 1h.12m
    ublock-filters: 31469-232, 1h.12m
    ublock-privacy: 258-1, 1h.12m
    ublock-quick-fixes: 584-193, 1h.12m
    ublock-unbreak: 1899-44, 1h.12m
    urlhaus-1: 12415-0, 1h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 178 ms (selfie)
  maxAssetCacheWait: 75 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    facebook.net: 1
    google-analytics.com: 1
    pubdirecte.com: 2
    webkdigital.fr: 2
```
</details>

**Comment by mapx-** [comment]
@x-R0b0T-x for the pages which don't need advanced filters (anti adb, popups, ad reinsertion etc) the filters have to be added in the regional list, in this case @smed79 for Liste FR (which is the base for Adguard french list)

@x-R0b0T-x you can report such things directly here:
https://github.com/easylist/listefr/issues

@smed79 a filter from your list 
`*$script,3p,domain=free-telecharger.link`

is wrongly blocking 
`https://connect.facebook.net/fr_FR/all.js#xfbml=1`
