### ISSUE TITLE
wawacity.moe: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15770]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wawacity.moe/?p=film&id=35958-black-adam`

### Category

nuisance, popups

### Describe the issue

This French site is a very good source, but there are some nuisances.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/203535795-699e982f-a448-4594-a3cd-5df56ebf8eda.png)
Fake download button

![image](https://user-images.githubusercontent.com/50231020/203535841-82831a3b-3829-4983-891d-20058741f43d.png)
Fake download links

![image](https://user-images.githubusercontent.com/50231020/203535911-d3df7863-3d57-4df8-a087-bd6d893065c6.png)
Popups

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 112061
  cosmetic: 47425
  scriptlet: 16809
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30146-28, 1h.12m
    easylist: 64772-82, 1h.12m
    easyprivacy: 30872-1555, 1h.12m
    plowe-0: 3669-895, 1h.12m
    ublock-abuse: 77-1, 1h.12m
    ublock-badware: 4008-126, 1h.12m
    ublock-filters: 31466-232, 1h.12m
    ublock-privacy: 258-1, 1h.12m
    ublock-quick-fixes: 584-193, 1h.12m
    ublock-unbreak: 1899-44, 1h.12m
    urlhaus-1: 12415-0, 1h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 185 ms (selfie)
  maxAssetCacheWait: 78 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    wawacity.moe: 1
    awledconside.xyz: 3
    pogothere.xyz: 2
    redanludb.xyz: 6
```
</details>

**Comment by mapx-** [comment]
I get no popup

**Comment by mapx-** [comment]
- provide specific page link
- report at french list for these classic filters

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/f8f1360ccb886be5dc13e5811e78d77095287061
