### ISSUE TITLE
retrofm.ru: ads

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#15772]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://retrofm.ru/online/player.php`

### Category

ads

### Describe the issue

Something I can't seem to find a way to prevent the launch of the prerolls, which starts when switching between radio stations. Classic blocking, redirecting, no-xhr-if and other methods - lead to a breakdown of the player.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![retrofm](https://user-images.githubusercontent.com/20126984/203542360-20251e35-279b-4b8a-a637-124916c54c09.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b7 default + RU AdList
Chromium: 107
```
</details>

**Comment by mapx-** [comment]
The code in 
`https://js.hostingradio.ru/js/hls-player.min.js`

could be (at least partially) something like this:
`https://github.com/mycujoo/clappr-vast-plugin/blob/master/src/main.js`

**Comment by dportvine** [comment]
@gorhill

**Comment by dimisa-RUAdList** [comment]
Embedding this ad is currently inactive, so I will close the issue and reopen the discussion in case of a relapse.
