### ISSUE TITLE
my pc keeps crashing everytimei i open my browser  i can't even disable it

### ISSUE THREAD

**Issue by INNSERTGOODUSERNAMEHERE** [uBlockOrigin/uAssets#15782]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [ ] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

I Do not know what to say at all

### A specific URL where the issue occurs.

`https://r.mtdv.me/videos/VYS8xWO8jqhCFD0ICYWHIYQSwFnkdoZg8`

### Steps to Reproduce

i can not
even
reproduce 
it i had to check them in order to submit it

### Expected behavior

not crash

### Actual behavior

shutdown my whole pc

### uBO version

0.1.12

### Browser name and version

internet  Explorer 12

### Operating System and version

windows 10

**Comment by mapx-** [comment]
uBO 0.1.12 ? what ?
internet Explorer 12 ?

Are you kidding ?

**Comment by krystian3w** [comment]
https://security.snyk.io/package/npm/@gorhill%2Fubo-core/0.1.12

and in `about:flags` on few version of Windows 10 possible change Trident to Spartan (aka EdgeHTML).

However, I still do not see how he uses NodeJS in Internet Explorer to block content better than by TPL / AdBlock Legacy Plugin.
