### ISSUE TITLE
[nsfw] facebook.com: popups

### ISSUE THREAD

**Issue by Tasibul** [uBlockOrigin/uAssets#15789]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.facebook.com/`

### Category

popups , and side ads 

### Describe the issue

side ads are sowing and they are not safe for work! facebook ads are so annoying. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91496
  cosmetic: 38646
  scriptlet: 16742
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 17-1, never
    easylist: 64799-53, 3d.8h.26m
    easyprivacy: 30861-1171, 3d.8h.25m
    plowe-0: 3669-870, 2d.23h.17m
    ublock-abuse: 76-0, 4d.8h.34m
    ublock-badware: 4008-109, 4h.34m
    ublock-filters: 31283-117, 4h.33m
    ublock-privacy: 258-1, 4d.8h.33m
    ublock-quick-fixes: 586-12, 30m
    ublock-unbreak: 1899-43, 4h.32m
    urlhaus-1: 11968-0, 4h.31m
filterset (user): [array of 16 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 534 ms (selfie)
  maxAssetCacheWait: 318 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by Tasibul** [comment]
![image](https://user-images.githubusercontent.com/49052021/203778836-ed7b7603-17b2-4722-a489-78ac62812565.png)

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/3367
