### ISSUE TITLE
OutPutter.io Ads

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#15781]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://outputter.io/generators`

### Describe the issue

Ads appearing on OutPutter.io

### uBlock Origin version

1.45.2

### Browser name and version

103.0.5060.132

### Settings

No changes to default settings

**Comment by SilkArt** [comment]
Why are the ads still there? I've updated my filter lists but the ads still show.

**Comment by mapx-** [comment]
- cloudflare issues I guess.
- waiting the server add the filter above or add manually the filters ryan committed

**Comment by ryanbr** [comment]
Looks fine here, Force an update?

**Comment by SilkArt** [comment]
Ok, working. Thanks!
