### ISSUE TITLE
discordbotlist.com: ads

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#15784]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://discordbotlist.com/bots/dank-memer/upvote/nn`

### Category

ads

### Describe the issue

There's a red block telling to disable ad blocker and next to the upvote frame there is a mysterious empty space that would usually have ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/203664977-c89cb58c-148d-4730-826c-01489f93a0b9.png)
For reference, the site without adblock looks like this: 
![image](https://user-images.githubusercontent.com/11874211/203665224-3d92a0bc-2048-4654-b670-156cadf63371.png)
After the 10 sec countdown ends:
![image](https://user-images.githubusercontent.com/11874211/203665256-25d7d66d-6271-4f57-aa71-acf4ca0b34c6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 92202
  cosmetic: 39971
  scriptlet: 19942
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4794-6, 21h.23m
  default: 
    user-filters: 0-0, never
    easylist: 64765-53, 5d.1h.25m
    easyprivacy: 30869-1171, 21h.24m
    plowe-0: 3670-869, 9d.1h.29m
    ublock-abuse: 77-0, 21h.25m
    ublock-badware: 4008-109, 21h.22m
    ublock-filters: 31289-117, 21h.21m
    ublock-privacy: 258-1, 21h.26m
    ublock-quick-fixes: 586-13, 1h.18m
    ublock-unbreak: 1896-43, 21h.20m
    urlhaus-1: 12447-0, 1h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 765 ms
  maxAssetCacheWait: 311 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    aaxads.com: 3
    adinplay.com: 1
    adnxs.com: 1
    agkn.com: 1
    bkrtx.com: 1
    cloudflareinsights.com: 1
    disqus.com: 9
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    lijit.com: 1
    narrative.io: 1
    network-n.com: 1
    pippio.com: 1
    rezync.com: 1
    viglink.com: 2
```
</details>

**Comment by solomoncyj** [comment]
<img width="1182" height="764" alt="Image" src="https://github.com/user-attachments/assets/c3f0b392-1fc4-485b-b082-2eee84e880cf" />

https://discordbotlist.com/bots/arcane/upvote

**Comment by solomoncyj** [comment]
im afriad just hiding the message still does not upvote the bot. or that UBO is blocking the verification scipr, due to it being privacy invasive
