### ISSUE TITLE
terabox.com: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#15788]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://terabox.com/s/1D1cm92EgRliJbPsHB4sb4Q`

### Category

nuisance

### Describe the issue

Another Link For Example : `https://www.terabox.com/sharing/link?surl=XzOGCbIPi3fheKoy61Kvmw`
There Is A Few Popups,Overlays On Both Download Page And Main Webpage..

If Using Mobile Then It Forces To Download Their App To Actually Download Something From Their Website But If We Use Desktop Mode It Would Download Normally (Can This Be ByPassed ?) Or Maybe Force Desktop Mode On This Website From UBO Side ?🤔

I Am Concerned About Privacy Here Too

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 109
filterset (summary): 
  network: 102372
  cosmetic: 154762
  scriptlet: 22798
  html: 878
listset (total-discarded, last-updated): 
  added: 
    https://cdn.staticaly.com/gh/yourduskquibbles/webannoyances/master/ultralist.txt: 42577-146, 1d.4m
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/429ee0ad15b68c7c8507e9a6f81a0511e4386ee5/BaseFilter/sections/antiadblock.txt: 16777-93, 1d.4m
    adguard-mobile: 8232-150, 1d.5m
    adguard-annoyance: 61206-1084, 1d.4m
    ublock-annoyances: 4818-5, 1d.5m
  default: 
    user-filters: 1001-20, never
    ublock-filters: 32245-500, 1d.6m
    ublock-badware: 4012-0, 1d.6m
    ublock-privacy: 305-0, 1d.6m
    ublock-abuse: 77-0, 1d.6m
    ublock-unbreak: 1912-1, 1d.6m
    ublock-quick-fixes: 591-0, 1d.5m
    easylist: 64772-777, 1d.5m
    easyprivacy: 30872-1723, 1d.5m
    urlhaus-1: 12415-0, 1d.5m
    plowe-0: 3669-3, 1d.5m
filterset (user): [array of 951 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1708 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    terabox.com: 10
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no popup.
Try switching to desktop modality in FF android.

**Comment by krystian3w** [comment]
Maybe that pop-up:

https://user-images.githubusercontent.com/35370833/203863655-230f5a0e-9780-4d35-a05e-00e99d188667.png

For uBo maybe someone wrote working:

```javascript
Object.defineProperty(navigator, 'userAgent', {
    value: 'Mozilla/5.0 (Linux; Android 13;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36'
});
```

as scriptlet and many pages are fool.

**Comment by mapx-** [comment]
> If Using Mobile Then It Forces To Download Their App To Actually Download Something

Even using a desktop I'm forced to download a windows app. Nothing to fix here.

**Comment by krystian3w** [comment]
Why JavaScript is isn't allowed as help issue?
