### ISSUE TITLE
[nsfw] mapmymilf.com: nuisance

### ISSUE THREAD

**Issue by gdjacobs** [uBlockOrigin/uAssets#15783]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mapmymilf.com/advancedsearch`

### Category

nuisance

### Describe the issue

This website is a nuisance dating site frequently used as a triggered popup. As of 2022-11-23, default rules do not trigger on the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91738
  cosmetic: 38531
  scriptlet: 16739
  html: 854
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32068-45, 23h.51m
    ublock-badware: 4012-0, 23h.50m
    ublock-privacy: 305-0, 23h.49m
    ublock-abuse: 77-0, 23h.48m
    ublock-unbreak: 1911-1, 23h.47m
    ublock-quick-fixes: 591-0, 23h.46m
    easylist: 64770-622, 23h.45m
    easyprivacy: 30869-1710, 23h.44m
    urlhaus-1: 12135-0, 23h.43m
    plowe-0: 3669-3, 23h.42m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 486 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    blendedbird.com: 5
    fpapi.io: 1
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Provide the steps to get redirected to this page
