### ISSUE TITLE
cdn.onesignal.com is blocked

### ISSUE THREAD

**Issue by ExcaliburGO** [uBlockOrigin/uAssets#15787]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://banklovers.pl/dostaniesz-200-zl-na-allegro-za-aktywnosci-na-koncie-pko-bp/`
`https://banklovers.pl/`

### Describe the issue

cdn.onecdn.onesignal.com is blocked. It shouldn't, as it's just a push notification plugin. Because of it being blocked, you don't see the bell to enable notifications.

### uBlock Origin version

1.45.2

### Browser name and version

Google Chrome 107.0.5304.107

### Settings

No changes at all

**Comment by krystian3w** [comment]
Tracker/annoying so blocked in EL/FA: https://github.com/easylist/easylist/search?q=onesignal

and PAF: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/search?q=onesignal

**Comment by mapx-** [comment]
add

`@@||onesignal.com^$domain=banklovers.pl`

it should be blocked only as annoyance, but it's blocked by easyprivacy list too. I notified the maintainer, if you want you can report the issue to easylist repository too.

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Its a tracker, should remain blocked. `https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js` The site itself works fine.
