### ISSUE TITLE
tycsports.com: ads

### ISSUE THREAD

**Issue by nnamregg** [uBlockOrigin/uAssets#15794]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tycsports.com/mundial/portugal-vs-ghana-en-vivo-hora-donde-ver-y-formaciones-id478809.html`

### Category

ads

### Describe the issue

Webpage renders 2 containers for ads with no ads.
First one on the top of the page, second one on bottom (this last one is closable).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tycsports_ads](https://user-images.githubusercontent.com/38567429/203849116-d96dfc70-2590-445d-9394-f700e5519393.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91459
  cosmetic: 38667
  scriptlet: 16732
  html: 835
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    ublock-filters: 32241-229, 15h.49m
    ublock-badware: 4039-1, 15h.48m
    ublock-privacy: 286-0, 10d.16h.23m
    ublock-abuse: 76-0, 10d.16h.22m
    ublock-unbreak: 1915-1, 2h.34m
    ublock-quick-fixes: 593-0, 15h.47m
    easylist: 64762-618, 5d.23h.13m
    easyprivacy: 30855-1711, 5d.17h.38m
    urlhaus-1: 11968-0, 15h.46m
    plowe-0: 3675-3, 6d.19h.12m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 256 ms (selfie)
  maxAssetCacheWait: 102 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    d24rtvkqjwgutp.cloudfront.net: 2
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 1
    googletagmanager.com: 1
    newsroom.bi: 1
    scorecardresearch.com: 1
    teads.tv: 2
```
</details>

**Comment by krystian3w** [comment]
```adb
##div[class^="banner"]
##div[id^="banner"]
```

**Comment by mapx-** [comment]
enable the spanish lists
