### ISSUE TITLE
[nsfw] shopee.co.th: breakage

### ISSUE THREAD

**Issue by unkl-sam** [uBlockOrigin/uAssets#15797]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://shopee.co.th`

### Describe the issue

it is not possible to login when uBO is on.
the login request is accepted but the page does not redraw and other open pages on the same site do not update to logged-in.
disabling uBO when the login is accepted, the page refreshes to the home page and the user is shown.

### uBlock Origin version

1.45.2

### Browser name and version

LibreWolf 107.0-1

### Settings

none

**Comment by mapx-** [comment]
Go into options / dashboard, support tab, post here "Troubleshooting Information"

**Comment by Cjrjjaje** [comment]
> ### Prerequisites
> 
>     * [x]  This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
> 
>     * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
> 
>     * [x]  I am running the latest version of uBlock Origin
> 
> 
> ### I tried to reproduce the issue when...
> 
>     * [x]  uBO is the only extension
> 
>     * [x]  uBO with default lists/settings
> 
>     * [x]  using a new, unmodified browser profile
> 
> 
> ### URL(s) where the issue occurs
> 
> `https://shopee.co.th`
> ### Describe the issue
> 
> it is not possible to login when uBO is on. the login request is accepted but the page does not redraw and other open pages on the same site do not update to logged-in. disabling uBO when the login is accepted, the page refreshes to the home page and the user is shown.
> ### Screenshot(s)
> 
> _No response_
> ### uBlock Origin version
> 
> 1.45.2
> ### Browser name and version
> 
> LibreWolf 107.0-1
> ### Settings
> 
> none
> ### Notes
> 
> _No response_
