### ISSUE TITLE
techcyan.com: detection

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#15796]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techcyan.com/machine-learnings-chromatographic/`

### Category

detection

### Describe the issue

ad blocker detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/42665606/203908288-742759b8-00a2-4687-9306-2c1dcc4a4472.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 91602
  cosmetic: 38524
  scriptlet: 16735
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64811-53, 2h.28m
    easyprivacy: 30872-1171, 2h.27m
    plowe-0: 3670-869, 12d.21h.26m
    ublock-abuse: 76-0, 3d.22h.17m
    ublock-badware: 4008-109, 3d.22h.16m
    ublock-filters: 31253-117, 3d.22h.15m
    ublock-privacy: 258-1, 4d.2h.18m
    ublock-quick-fixes: 586-12, 21h.41m
    ublock-unbreak: 1896-43, 3d.22h.14m
    urlhaus-1: 11968-0, 21h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 750 ms (selfie)
  maxAssetCacheWait: 224 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    domain.com: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    ibb.co: 1
    wp.com: 2
```
</details>

**Comment by mapx-** [comment]
update all filter lists, already fixed
