### ISSUE TITLE
fifa.com: detection

### ISSUE THREAD

**Issue by Ajj0** [uBlockOrigin/uAssets#15798]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.fifa.com/fifaplus/en/tournaments/mens/worldcup/qatar2022/qatar-highlights`

### Category

detection

### Describe the issue

uBlock block playing videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91391
  cosmetic: 38863
  scriptlet: 16906
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 32273-326, 6m
    ublock-badware: 4039-1, 6m
    ublock-privacy: 305-0, 6m
    ublock-abuse: 77-0, 6m
    ublock-unbreak: 1916-0, 6m
    ublock-quick-fixes: 612-1, 6m
    easylist: 64782-519, 6m
    easyprivacy: 30881-1731, 6m
    urlhaus-1: 11476-0, 6m
    plowe-0: 3667-3, 6m
    CZE-0: 731-0, 6m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 778 ms (selfie)
  maxAssetCacheWait: 324 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    adobedtm.com: 2
    visualstudio.com: 2
```
</details>

**Comment by mapx-** [comment]
if updating the lists does not work, just add:

`@@||uplynk.com^$xhr,removeparam,domain=fifa.com`

**Comment by mapx-** [comment]
@gorhill you added that exception but updating the lists does not bring that filter alive

**Comment by gorhill** [comment]
GitHub Actions were having [an issue earlier](https://github.com/uBlockOrigin/uAssets/actions/workflows/pages/pages-build-deployment). Should be fine now?

**Comment by mapx-** [comment]
yes, it's ok now
