### ISSUE TITLE
[nsfw] sogatinhas.net: popups

### ISSUE THREAD

**Issue by cleuton4k** [uBlockOrigin/uAssets#15795]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sogatinhas.net/fodendo-com-estranho-dentro-do-carro-na-frente-do-corno-sem-camisinha/`

### Category

popups

### Describe the issue

popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 137723
  cosmetic: 218676
  scriptlet: 35398
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39536-11, 19h.17m
    adguard-annoyance: 61240-497, 19h.17m
    adguard-generic: 65906-675, 19h.17m
    curben-pup: 187-0, 19h.17m
    fanboy-annoyance: 83332-3974, 19h.17m
  default: 
    user-filters: 2-0, never
    easylist: 64810-838, 19h.17m
    easyprivacy: 30874-1436, 19h.17m
    plowe-0: 3669-890, 19h.17m
    spa-1: 4864-85, 19h.17m
    ublock-abuse: 77-1, 19h.17m
    ublock-badware: 4035-255, 19h.17m
    ublock-filters: 31479-3721, 19h.17m
    ublock-privacy: 258-9, 19h.17m
    ublock-quick-fixes: 586-218, 19h.17m
    ublock-unbreak: 1900-87, 19h.17m
    urlhaus-1: 11968-0, 19h.17m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 75 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 45 redacted]
hostRuleset: 
  added: [array of 137 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 12px
supportStats: 
  allReadyAfter: 471 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 15
  no-popups: true
  blockedDetails: 
    sogatinhas.net: 5
    d1f05vr3sjsuy7.cloudfront.net: 1
    googletagmanager.com: 1
    realsrv.com: 4
    sermondirt.com: 2
    tapioni.com: 1
    wpnsrv.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||sogatinhas.net/*.gif$image
sogatinhas.net##[src^="/img/banners"]
sogatinhas.net###ads-foda-fx
```

@Yuki2718 spanish list ?

**Comment by Yuki2718** [comment]
@mapx- I don't see `###ads-foda-fx`, is it for the bottom banner? (Not sure about Amigos das Gatinhas - maybe site's friends sites).

**Comment by cleuton4k** [comment]
I made some changes, better now. thanks

sogatinhas.net##.catfish
sogatinhas.net###ads-foda-fx

**Comment by mapx-** [comment]
@Yuki2718 you don't see it because it's inside a frame, just add that filter

![image](https://user-images.githubusercontent.com/10303732/204033283-61b2f8fa-22dc-4dd0-a7f2-3e64c10dadd4.png)
