### ISSUE TITLE
megafly.in/CB4jvjlbsge: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15799]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://megafly.in/CB4jvjlbsge`

### Category

detection

### Describe the issue

Adblock detection 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 109
filterset (summary): 
  network: 92637
  cosmetic: 27795
  scriptlet: 16795
  html: 859
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32383-467, 1h.56m
    ublock-badware: 4038-1, 1h.56m
    ublock-privacy: 305-1, 1h.56m
    ublock-abuse: 77-0, 1h.56m
    ublock-unbreak: 1922-1, 1h.56m
    ublock-quick-fixes: 617-0, 1h.56m
    adguard-mobile: 8248-166, 1h.56m
    easylist: 64782-17787, 1h.56m
    easyprivacy: 30881-1720, 1h.56m
    urlhaus-1: 11476-0, 1h.56m
    plowe-0: 3667-3, 1h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 18729 ms (selfie)
  maxAssetCacheWait: 329 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    distinctbelieverjustify.com: 2
    doubleclick.net: 1
    exmarketplace.com: 2
    googletagmanager.com: 1
    megaurl.in: 2
    trackpush.com: 1
    unibots.in: 2
    vidcrunch.com: 2
```
</details>

**Comment by mapx-** [comment]
Test

`*$image,domain=azmath.info,redirect-rule=1x1.gif`

**Comment by hunterkais** [comment]
Working, but sometime he doesn't just go to azmath.info, sometimes to app.trangchu.news, sometimes to scratch247.info, maybe that could be added.  thanks

**Comment by krystian3w** [comment]
#15940
