### ISSUE TITLE
sport.cz: ads

### ISSUE THREAD

**Issue by Yota8888** [uBlockOrigin/uAssets#15792]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.sport.cz/clanek/hokej-nhl-hronek-ridil-vyhru-detroitu-fantasticky-vejmelka-ma-nulu-3784572`

### Category

ads

### Describe the issue

![Screenshot_2022-11-24_17-31-09](https://user-images.githubusercontent.com/118998546/203831935-65cfc68e-53f7-4c62-8758-f10cdda53547.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2022-11-24_17-31-09](https://user-images.githubusercontent.com/118998546/203832062-b75f3916-db8d-41b8-a1fd-99a8058586f0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92046
  cosmetic: 38567
  scriptlet: 16739
  html: 854
listset (total-discarded, last-updated): 
  default: 
    user-filters: 76-14, never
    ublock-filters: 32068-46, 1d.19h.19m
    ublock-badware: 4012-0, 1d.19h.19m
    ublock-privacy: 305-0, 1d.19h.19m
    ublock-abuse: 77-0, 1d.19h.19m
    ublock-unbreak: 1911-1, 1d.19h.19m
    easylist: 64739-622, 1d.19h.19m
    easyprivacy: 30869-1710, 1d.19h.19m
    urlhaus-1: 12447-0, 19h.18m
    plowe-0: 3669-3, 1d.19h.18m
    ublock-quick-fixes: 593-0, 19h.17m
filterset (user): [array of 76 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1152 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    sport.cz: 2
    doubleclick.net: 2
    gemius.pl: 1
    google-analytics.com: 1
    im.cz: 1
    seznam.cz: 8
    youtube.com: 7
```
</details>

**Comment by mapx-** [comment]
Test

`sport.cz##[style^="max-width"]`

**Comment by mapx-** [comment]
@addisr
