### ISSUE TITLE
spanishdict.com

### ISSUE THREAD

**Issue by CaptainFrosty** [uBlockOrigin/uAssets#1579]
### URL(s) where the issue occurs

`http://www.spanishdict.com/translate/`

### Describe the issue

Ad blocker popup window and notice on the right side of the page are showing although there is an entry for spanishdict.com in the Adblock Warning Removal List.

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/8523498/36441430-9fd77e60-1640-11e8-9e3a-e1a611b8a970.jpg)
![ss2](https://user-images.githubusercontent.com/8523498/36441438-a86105ec-1640-11e8-8196-9372f10cebee.jpg)

### Versions

- Browser/version: Chrome 64.0.3282.167 (Official Build) (32-bit)
- uBlock Origin version: v1.15.2

### Settings

- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 
- Prevent WebRTC from leaking local IP addresses 
- Block CSP report

**Comment by CaptainFrosty** [comment]
I had that filter on already.

**Comment by CaptainFrosty** [comment]
It appears that the entry on the Annoyances filter no longer works. I can't find an element called `.ad-wrapper` on the page

**Comment by mapx-** [comment]
Still cannot reproduce your issue. Close the new issue you opened and provide useful info: 

- did you test disabling all other extensions ?
- what filter lists are enabled in uBo ?

**Comment by okiehsch** [comment]
> It appears that the entry on the Annoyances filter no longer works. I can't find an element called .ad-wrapper on the page.

Works on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/36620725-bb94d4d4-18f4-11e8-9406-3981dd349693.PNG)

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
