### ISSUE TITLE
theguardian.com: breakage

### ISSUE THREAD

**Issue by schadfield** [uBlockOrigin/uAssets#15804]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.theguardian.com/football/2022/nov/25/australias-arnold-ready-for-war-against-tunisia-side-uniting-a-country`

### Category

breakage

### Describe the issue

For some time the user comments section of The Guardian website has not shown the comments. It may show a small number of specially selected comments at the top of the comments section but the regular nested comments no longer appear. 

- [ ] 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2022-11-26 18-32-49](https://user-images.githubusercontent.com/11432715/204082088-db0825f4-fc7e-4368-9378-b129fa5ef10d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91042
  cosmetic: 38626
  scriptlet: 16751
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32282-231, 4h.20m
    ublock-badware: 4039-1, 4h.19m
    ublock-privacy: 305-0, 4h.18m
    ublock-abuse: 77-0, 4h.17m
    ublock-unbreak: 1916-1, 4h.16m
    ublock-quick-fixes: 601-0, 20h.44m
    easylist: 64774-620, 4d.5h.26m
    easyprivacy: 30866-1710, 4d.5h.25m
    urlhaus-1: 11476-0, 20h.43m
    plowe-0: 3669-3, 4d.5h.23m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 336 ms (selfie)
  maxAssetCacheWait: 123 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    theguardian.com: 15
    ads-twitter.com: 1
    adsafeprotected.com: 1
    amazon-adsystem.com: 1
    brandmetrics.com: 1
    braze.eu: 1
    confiant-integrations.net: 1
    getsentry.com: 1
    google-analytics.com: 1
    googleadservices.com: 1
    googletagservices.com: 1
    guim.co.uk: 1
    permutive.com: 1
    scorecardresearch.com: 1
    youtube-nocookie.com: 2
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/16838044/204082246-5db51c72-1e1a-437d-9c6a-45feef5ac88b.png)

All comments show up after clicking "View More Cooments".

**Comment by mapx-** [comment]
Reset uBO, don't modify any uBO setting, **update all the filter lists**, don't add any other list, disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera / vivaldi/ firefox etc, disable (if any) the web shields in your antivirus / antimalware software / other blocking software, restart the system, reopen the browser, test again.

**Comment by schadfield** [comment]
Apologies.  I had a "picked" custom filter that was removing an annoying banner at the bottom of the page. This was causing the comments to vanish even though this did not happen in the preview. I have fixed the issue by picking the banner then stepping back the range of the filter to the lowest possible level that removes it. This hides the banner without breaking the comments.
