### ISSUE TITLE
planhub.ca: ads

### ISSUE THREAD

**Issue by thephantom1492** [uBlockOrigin/uAssets#15802]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.planhub.ca/quebec/compare-cellphone-plan/unlimitedcalls.20000MB.3G.4G.5G.unlimitedtext.voicemail.2years.2.1-9-2-65-5-8-6-7-4-10`

### Category

ads

### Describe the issue

Where to begin...

Top banner.
Left banner.
Right banner.
Bottom banner.
Mid-page banner.
![Screenshot 2022-11-25 at 19-18-43 BYOD with unlimited calls and 20 GB in Quebec](https://user-images.githubusercontent.com/16235927/204065243-86949ddc-fefb-4711-bc9d-69a4d9c4b754.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 106
filterset (summary): 
  network: 95792
  cosmetic: 91688
  scriptlet: 19551
  html: 854
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61277-602, 21h.57m
  default: 
    user-filters: 14-1, never
    ublock-filters: 32271-231, 22h
    ublock-badware: 4012-0, 21h.59m
    ublock-privacy: 305-0, 3d.14h.10m
    ublock-abuse: 77-0, 3d.14h.9m
    ublock-unbreak: 1915-0, 21h.58m
    easylist: 64728-621, 3d.18h.11m
    easyprivacy: 30864-1710, 2d.22h.6m
    plowe-0: 3670-3, 11d.2h.8m
    urlhaus-1: 11476-0, 1h.55m
    ublock-quick-fixes: 609-1, 1h.56m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 817 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    planhub.ca: 1
    cloudflareinsights.com: 16
    doubleclick.net: 8
    google-analytics.com: 2
    googletagmanager.com: 4
    googletagservices.com: 1
    maps.googleapis.com: 1
    rudderlabs.com: 3
```
</details>

**Comment by okiehsch** [comment]
Most of ot is self advertisement as far as I can see.
Only the "fizz" ad appears to be within EasyList policy.
`planhub.ca##.banner_iframe`
@ryanbr

**Comment by mapx-** [comment]
it's "hidden" anti adb, they are detecting it and add the ads

**Comment by advertblocker** [comment]
`planhub.ca##.h-banner`

**Comment by nqlp** [comment]
I have this cookie banner at the bottom and detection issue: 

<img width="1440" height="650" alt="Image" src="https://github.com/user-attachments/assets/4f502592-4c77-4ed4-9515-50fa6e6ed510" />


Troubleshooting Information:

<details>

```yaml
uBlock Origin: 1.67.0
Chromium: 142
filterset (summary):
 network: 180220
 cosmetic: 166430
 scriptlet: 44080
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 36023-77, 3m
  ublock-cookies-adguard: 5241-76, 3m
  fanboy-cookiemonster: 46574-3945, 3m
  ublock-cookies-easylist: 5241-5241, 3m
  adguard-popup-overlays: 29033-316, 4m
  adguard-mobile-app-banners: 6468-449, 4m
  adguard-other-annoyances: 15208-219, 4m
  easylist-annoyances: 5020-481, 4m
  easylist-notifications: 2426-9, 4m
  ublock-annoyances: 4705-163, 4m
  FRA-0: 19397-269, 4m
  ublock-experimental: 4-0, 4m
 default:
  user-filters: 22-0, never
  ublock-filters: 41834-74, 3m
  ublock-badware: 10532-31, 3m
  ublock-privacy: 3564-4, 3m
  ublock-unbreak: 2706-1, 3m
  ublock-quick-fixes: 391-15, 3m
  easylist: 81011-504, 3m
  easyprivacy: 54851-753, 3m
  urlhaus-1: 30190-5, 3m
  plowe-0: 3476-0, 4m
filterset (user): [array of 22 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2331 ms
 maxAssetCacheWait: 822 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  cloudflareinsights.com: 5
  cookieyes.com: 1
  customer.io: 1
  doubleclick.net: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##.h-banner
```
</details>

**Comment by stephenhawk8054** [comment]
For cookies

```adb
||cdn-cookieyes.com^
```

@ryanbr

**Comment by nqlp** [comment]
I still see the cookies:


<img width="1440" height="657" alt="Image" src="https://github.com/user-attachments/assets/622d2c78-cca1-42d9-b121-32d8340fa2cc" />

Config:

<details>

```yaml
uBlock Origin: 1.67.0
Chromium: 142
filterset (summary):
 network: 183209
 cosmetic: 165457
 scriptlet: 43990
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 36185-75, now
  ublock-cookies-adguard: 5247-69, now
  fanboy-cookiemonster: 44796-3635, now
  ublock-cookies-easylist: 5247-5247, now
  adguard-popup-overlays: 29127-299, now
  adguard-mobile-app-banners: 6493-430, now
  adguard-other-annoyances: 15248-202, now
  easylist-annoyances: 5027-471, now
  easylist-notifications: 2428-9, now
  ublock-annoyances: 4714-149, now
  FRA-0: 19402-280, now
  ublock-experimental: 4-0, now
 default:
  user-filters: 22-0, never
  ublock-filters: 41884-72, now
  ublock-badware: 10574-31, now
  ublock-privacy: 3563-4, now
  ublock-unbreak: 2710-1, now
  ublock-quick-fixes: 410-10, 1h.2m Δ
  easylist: 83370-508, now
  easyprivacy: 54904-745, now
  urlhaus-1: 30620-5, 1h.2m
  plowe-0: 3479-0, now
filterset (user): [array of 22 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1509 ms
 maxAssetCacheWait: 522 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  cdn-cookieyes.com: 1
  cloudflareinsights.com: 1
  cookieyes.com: 1
  customer.io: 1
  doubleclick.net: 1
  google.com: 6
  googletagmanager.com: 1
 extended:
  ###popupAdBlockerDetected
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(prevent-fetch, googlesyndication)
```
</details>
