### ISSUE TITLE
lkz.de: detection

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#15800]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.lkz.de/`

### Category

detection

### Describe the issue

detects adblocker - see screenshot

### Screenshot(s)

![1](https://user-images.githubusercontent.com/15193811/204062151-2dd0066d-f09e-41a9-a730-a17e3a895b77.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 93674
  cosmetic: 43664
  scriptlet: 19953
  html: 882
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4819-4, now
    ublock-quick-fixes: 617-1, now
  default: 
    user-filters: 4-0, never
    ublock-filters: 32282-254, now
    ublock-badware: 4039-1, now
    ublock-privacy: 305-0, now
    ublock-unbreak: 1917-0, now
    easylist: 64823-630, now
    easyprivacy: 30881-1720, now
    plowe-0: 3667-3, now
    DEU-0: 6048-2, now
    ublock-abuse: 77-0, now
    urlhaus-1: 11476-0, now
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1343 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    nativendo.de: 1
    npttech.com: 1
    taboola.com: 1
    yieldscale.com: 2
```
</details>

**Comment by mapx-** [comment]
No issue on my end, DE ip tested too, @okiehsch @JobcenterTycoon are you able to get the anti adb ?

**Comment by okiehsch** [comment]
No, but most articles are behind a paywall maybe the OP sees the detection there.
The free articles have no detection on my end.

**Comment by TonyTough** [comment]
I have tried it again have to say I'm sorry,
it is caused by the Firefox Add-On "Bypass paywalls clean" (also on the mainpage and the free articles).
