### ISSUE TITLE
walmartpetrx.com - breakage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15801]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.walmartpetrx.com/p-5229-nexgard-for-dogs-and-puppies.aspx`

### Describe the issue

Clicking add to cart button hangs with uBlock Origin enabled

### Notes

The 1 redacted `trustedset` is the walmart url

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91208
  cosmetic: 38520
  scriptlet: 16753
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32282-242, 5m
    ublock-badware: 4039-1, 5m
    ublock-privacy: 305-0, 5m
    ublock-abuse: 77-0, 5m
    ublock-unbreak: 1917-1, 5m
    ublock-quick-fixes: 617-0, 5m
    easylist: 64823-623, 5m
    easyprivacy: 30881-1710, 4m
    urlhaus-1: 11476-0, 4m
    plowe-0: 3667-3, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2101 ms
  maxAssetCacheWait: 204 ms
```
</details>

**Comment by mapx-** [comment]
@ryanbr
