### ISSUE TITLE
jiocinema.com: detection

### ISSUE THREAD

**Issue by spdkiran** [uBlockOrigin/uAssets#15809]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.jiocinema.com/sports/football/2022/match/live---france-vs-denmark---english/0f982fb067ef11eda15e238d78f1d69d`

### Category

detection

### Describe the issue

ADBLOCKER DETECTED BY WEBSITE

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91028
  cosmetic: 38618
  scriptlet: 16766
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 19-3, never
    easylist: 64774-53, 4d.23h.27m
    easyprivacy: 30869-1171, 2d.23h.51m
    plowe-0: 3667-870, 6h.24m
    ublock-abuse: 77-0, 2d.23h.53m
    ublock-badware: 4008-109, 2d.23h.48m
    ublock-filters: 31469-121, 2d.23h.50m
    ublock-privacy: 258-1, 2d.23h.52m
    ublock-quick-fixes: 602-173, 1d.4m
    ublock-unbreak: 1899-43, 2d.23h.49m
    urlhaus-1: 11476-0, 16h.8m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 21846 ms
  maxAssetCacheWait: 3562 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    d2r1yp2w7bby2u.cloudfront.net: 2
    facebook.net: 1
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
see if works for you

`@@||jiocinema.com^$ghide`

after defeating the anti adb I get this (even disabling uBO)
![image](https://user-images.githubusercontent.com/10303732/204099577-b5291ce6-e923-4d4f-bd64-3233020b9de1.png)
