### ISSUE TITLE
bilibili.com: ads

### ISSUE THREAD

**Issue by QuantumAlgorithm** [uBlockOrigin/uAssets#15806]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/video/BV13R4y1Z7Rx/`

### Category

ads

### Describe the issue

Ad clears residue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 102
filterset (summary): 
  network: 109005
  cosmetic: 48846
  scriptlet: 16872
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 25-6, never
    ublock-filters: 32282-239, 15m
    ublock-badware: 4039-1, 18m
    ublock-privacy: 305-0, 8d.11h.10m
    ublock-abuse: 76-0, 8d.11h.9m
    ublock-unbreak: 1917-1, 16m
    easylist: 64782-653, 5d.20h.31m
    easyprivacy: 30869-1733, 3d.19m
    urlhaus-1: 11076-0, 14m
    plowe-0: 3668-3, 7d.10h.53m
    CHN-0: 28851-97, 19m
    ublock-quick-fixes: 590-0, 13m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 648 ms (selfie)
  maxAssetCacheWait: 407 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    bilibili.com: 18
    hdslb.com: 5
```
</details>

**Comment by mapx-** [comment]
> Ad clears residue

Where are on page ? screenshot ?

@cjx82630
