### ISSUE TITLE
snapinsta.app: nuisance

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#15803]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://snapinsta.app/`

### Category

nuisance

### Describe the issue

Modal popup.
Test url: `https://www.instagram.com/p/ClYL8hvrYV-/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-11-26_085654](https://user-images.githubusercontent.com/111344219/204076499-751c51d3-c76a-46d6-9589-2053968b6b43.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b7
Chromium: 107
filterset (summary): 
  network: 102642
  cosmetic: 126446
  scriptlet: 23076
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31479-26, now
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1530-24, now
    fanboy-cookiemonster: 43625-345, now
    ublock-annoyances: 4795-53, now
  default: 
    user-filters: 12-0, never
    RUS-0: 39546-145, now
    easylist: 64822-82, now
    easyprivacy: 30885-1586, now
    ublock-abuse: 77-1, now
    ublock-badware: 4035-108, now
    ublock-filters: 31499-178, now
    ublock-privacy: 258-8, now
    ublock-quick-fixes: 603-201, now
    ublock-unbreak: 1904-46, now
filterset (user): [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 1053 ms
  maxAssetCacheWait: 695 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
account required ? maybe you should report it at easylist ?

**Comment by dportvine** [comment]
an account is not required, scrolling is blocked there.
[Gif](https://imgur.com/ZSeRFXT)
https://github.com/easylist/easylist/issues/14232
