### ISSUE TITLE
blog.freeoseocheck.com: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15805]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://t.co/05mUz7Qkj3 original link
`https://blog.freeoseocheck.com/detected.html`

### Category

detection

### Describe the issue

i don't know this is original link "https://t.co/05mUz7Qkj3", because i no see another link. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91172
  cosmetic: 38521
  scriptlet: 16764
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 16-4, never
    easylist: 64782-53, 15h.54m
    easyprivacy: 30881-1171, 15h.54m
    plowe-0: 3667-870, 15h.54m
    ublock-abuse: 77-0, 15h.54m
    ublock-badware: 4035-110, 15h.54m
    ublock-filters: 31494-125, 15h.54m
    ublock-privacy: 258-1, 15h.54m
    ublock-quick-fixes: 607-201, 15h.54m
    ublock-unbreak: 1904-43, 15h.54m
    urlhaus-1: 11476-0, 15h.53m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1005 ms (selfie)
  maxAssetCacheWait: 1322 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 2
    snobdomobeyeo.com: 1
```
</details>

**Comment by mapx-** [comment]
test

`*$script,domain=blog.freeoseocheck.com,redirect-rule=noopjs`

I doubt it's the real link.
If does not work, explain HOW do you get these links.

**Comment by hunterkais** [comment]
It's work, add this URL 
blog.coinscap.info, blog.cookinguide.net
Because that's URL in step 2 and step 3. Thanks
