### ISSUE TITLE
kpkuang.org: popups

### ISSUE THREAD

**Issue by jackedhdhs** [uBlockOrigin/uAssets#15812]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kpkuang.org/voddetail/46213/`

### Category

popups

### Describe the issue

Can't stop this AD from popping up velvettraffic.xyz

### Screenshot(s)

![Screenshot_20221127-004857](https://user-images.githubusercontent.com/119126075/204100522-f7c16456-760e-4902-a755-4599f3b32f7e.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium Mobile: 107
filterset (summary): 
  network: 257604
  cosmetic: 80452
  scriptlet: 29531
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist-downloads.adblockplus.org/easyprivacy.txt: 30885-1149, 7h.24m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt: 1833-25, 7h.24m
    https://www.i-dont-care-about-cookies.eu/abp/: 25532-13606, 7h.24m
    adguard-generic: 65971-1016, 7h.24m
    curben-phishing: 128304-0, 7h.24m
    curben-pup: 187-1, 7h.24m
  default: 
    user-filters: 0-0, never
    CHN-0: 28846-1314, 7h.24m
    adguard-mobile: 8248-93, 7h.24m
    easylist: 64822-17999, 7h.24m
    easyprivacy: 30885-30885, 7h.24m
    plowe-0: 3667-969, 7h.24m
    ublock-abuse: 77-0, 7h.24m
    ublock-badware: 4034-255, 7h.24m
    ublock-filters: 31604-3536, 7h.24m
    ublock-privacy: 258-2, 7h.24m
    ublock-quick-fixes: 603-225, 7h.24m
    ublock-unbreak: 1909-83, 7h.24m
    urlhaus-1: 11292-4, 7h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4345 ms (selfie)
  maxAssetCacheWait: 1962 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    friendshipmale.com: 1
    simplewebanalysis.com: 2
```
</details>

**Comment by mapx-** [comment]
Test

```
kpkuang.org##+js(nostif, _0x)
kpkuang.org###sterra-ad-onmid
||burlydeclined.com
```
