### ISSUE TITLE
goodwillfinds.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#15816]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.goodwillfinds.com/`

### Category

breakage

### Describe the issue

Search bar doesn't work. To reproduce open an incognito tab then click on the search bar. It will not open 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/69532417/204114447-a2654e68-4aac-4aae-9ab2-525b7f4bd754.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 266880
  cosmetic: 202586
  scriptlet: 37612
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61310-94, 20h.29m
    adguard-generic: 65971-512, 20h.24m
    adguard-mobile: 8242-44, 1d.13h.31m
    adguard-spyware: 32908-3860, 20h.25m
    adguard-spyware-url: 850-1, 1d.13h.32m
    block-lan: 44-0, 14d.22h.37m
    curben-phishing: 128304-1, 20h.21m
    curben-pup: 195-1, 20h.22m
    fanboy-annoyance: 83249-3963, 5d.16h.53m
    fanboy-cookiemonster: 43512-43512, 5d.19h.18m
    ublock-annoyances: 4795-233, 1d.13h.30m
  default: 
    user-filters: 0-0, never
    easylist: 64783-1069, 1d.1h.29m
    easyprivacy: 30881-12288, 1d.1h.28m
    plowe-0: 3669-1035, 3d.6h.44m
    ublock-abuse: 76-0, 6d.18h.20m
    ublock-badware: 4035-255, 20h.28m
    ublock-filters: 31499-3691, 20h.27m
    ublock-privacy: 258-50, 6d.18h.19m
    ublock-quick-fixes: 362-39, 4h.16m
    ublock-unbreak: 1904-101, 20h.26m
    urlhaus-1: 11199-5, 20h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 353 ms (selfie)
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    goodwillfinds.com: 2
    cquotient.com: 1
    googletagmanager.com: 1
    igodigital.com: 1
    maxymiser.net: 1
    stripe.com: 1
```
</details>

**Comment by mapx-** [comment]
add
`@@||collect.igodigital.com/collect.js$script,domain=goodwillfinds.com`

`AdGuard Tracking Protection` issue

**Comment by Yuki2718** [comment]
@gorhill The rule is working but is it trivial to add `emptyArr` as an alias of `[]` (and `emptyObj` as `{}`: https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-constant)? 
Or else I will open an issue in FiltersCompiler.
