### ISSUE TITLE
rakuten.tv - Anti Adblocker

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#15819]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://rakuten.tv/es/player/movies/stream/incidencias`

### Category

detection

### Describe the issue

anti adblock in `https://rakuten.tv/`

### Screenshot(s)

![aaa](https://user-images.githubusercontent.com/33556647/204141158-0d183d51-fa85-4726-91aa-776f66907b02.png)

### Configuration

```
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 93622
  cosmetic: 45053
  scriptlet: 20184
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4795-6, 1d.15h.56m
  default: 
    user-filters: 0-0, never
    easylist: 64823-53, 1d.15h.56m
    easyprivacy: 30881-1171, 1d.15h.56m
    plowe-0: 3667-870, 1d.15h.56m
    spa-0: 3410-11, 14h.51m
    spa-1: 4868-183, 1d.15h.56m
    ublock-abuse: 77-0, 1d.15h.56m
    ublock-badware: 4035-110, 1d.15h.56m
    ublock-filters: 31499-165, 1d.15h.56m
    ublock-privacy: 258-1, 1d.15h.56m
    ublock-quick-fixes: 363-15, 14h.50m
    ublock-unbreak: 1904-45, 1d.15h.56m
    urlhaus-1: 11076-0, 14h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 143 ms (selfie)
  maxAssetCacheWait: 161 ms

```

**Comment by JobcenterTycoon** [comment]
Fixed.
