### ISSUE TITLE
crast.net: detection

### ISSUE THREAD

**Issue by dydar** [uBlockOrigin/uAssets#15825]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crast.net/ru/170988/%D1%8D%D1%82%D0%BE-greyky-2-0-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%2C-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9-%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B8%D1%8F-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D1%82-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%B7%D0%BB%D0%BE%D0%BC%D0%B0-%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BE%D0%B2/`

### Category

detection

### Describe the issue

The web page detects ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 107425
  cosmetic: 59578
  scriptlet: 17937
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39544-11, 1h.45m
    easylist: 64848-66, 1h.50m
    easyprivacy: 30889-1284, 1h.49m
    plowe-0: 3669-875, 3d.20h.14m
    ublock-abuse: 77-1, 5d.22h.54m
    ublock-badware: 4040-110, 1h.48m
    ublock-filters: 31508-156, 1h.47m
    ublock-privacy: 258-1, 5d.22h.53m
    ublock-quick-fixes: 363-22, 1h.44m
    ublock-unbreak: 1909-45, 1h.46m
    urlhaus-1: 10585-0, 1h.42m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4448 ms (selfie)
  maxAssetCacheWait: 437 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 2
    histats.com: 1
```
</details>

**Comment by dydar** [comment]
The web page detects ublock origin

**Comment by mapx-** [comment]
Reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list, disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera / vivaldi/ firefox etc, disable (if any) the web shields in your antivirus / antimalware software / other blocking software, restart the system, reopen the browser, test again.
