### ISSUE TITLE
[nsfw] yallo.tv: breakage

### ISSUE THREAD

**Issue by VictorManuel73** [uBlockOrigin/uAssets#15824]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://yallo.tv/`

### Category

breakage

### Describe the issue

Yallo.tv always detects uBO...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 92644
  cosmetic: 42337
  scriptlet: 16731
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32309-67, 21h.9m
    ublock-badware: 4044-1, 20h.51m
    ublock-privacy: 305-0, 8d.11h.23m
    ublock-abuse: 76-0, 9d.8h.10m
    ublock-unbreak: 1919-1, 21h.8m
    ublock-quick-fixes: 373-0, 20h.48m
    easylist: 64862-629, 21h.11m
    easyprivacy: 30885-1720, 21h.10m
    urlhaus-1: 10671-0, 20h.49m
    plowe-0: 3667-3, 21h.12m
    DEU-0: 6048-2, 20h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2406 ms (selfie)
  maxAssetCacheWait: 885 ms
popupPanel: 
  blocked: 6
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    gstatic.com: 4
    imasdk.googleapis.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
No issue if using the site as a guest.

**Comment by VictorManuel73** [comment]
Thank you
That was usefull and it worked. 
I will try it further, because as a registred user i can record movies. 
Just let me some time to try, before closing the Thread completely.

**Comment by mapx-** [comment]
You can still add other comments here
