### ISSUE TITLE
fansided.com

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#1582]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://fansided.com/2018/02/20/updated-olympics-mens-hockey-bracket/`

### Describe the issue

Adblock warning that can be bypassed by clicking on 'Continue without disabling'
### Screenshot(s)

Will post if needed

### Versions

- Browser/version: Chrome 64
- uBlock Origin version: 1.15.7.3 Development Channel

### Settings

- Default

### Notes

Fix should probably be added to annoyances list as there is a link to continue reading without disabling adblocker.

**Comment by okiehsch** [comment]
I can't reproduce. No adblock warning with Chrome or Firefoxx on my end.

**Comment by okiehsch** [comment]
OK, after deleting cookies I can reproduce, will add a fix.

**Comment by mapx-** [comment]
or
`||fansided.com^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: *.zencdn.net *.brightcove.net *.twitter.com *.timeinc.com *.googletagmanager.com *.facebook.net *.fansided.com`
