### ISSUE TITLE
dashboard.getdriven.app: breakage

### ISSUE THREAD

**Issue by dwemel** [uBlockOrigin/uAssets#15827]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dashboard.getdriven.app/`

### Category

breakage

### Describe the issue

De website gets stuck when trying to log-in, when ublock is active. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 90987
  cosmetic: 40288
  scriptlet: 16755
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2482-12, 2h.35m
    easylist: 64774-56, 5d.13h.29m
    easyprivacy: 30867-1172, 5d.13h.27m
    plowe-0: 3671-869, 12d.19h.14m
    ublock-abuse: 77-0, 3d.2h.40m
    ublock-badware: 4040-110, 22h.35m
    ublock-filters: 31526-148, 22h.34m
    ublock-privacy: 258-1, 3d.2h.39m
    ublock-quick-fixes: 362-16, 22h.32m
    ublock-unbreak: 1906-57, 22h.36m
    urlhaus-1: 10671-0, 22h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 263 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    browser-intake-datadoghq.eu: 2
```
</details>

**Comment by mapx-** [comment]
Test this filter

`@@||datadoghq-browser-agent.com/datadog-$script,domain=dashboard.getdriven.app`

**Comment by dwemel** [comment]
That did it! Thanks!

**Comment by mapx-** [comment]
@ryanbr
