### ISSUE TITLE
airbnb.de: nuisance

### ISSUE THREAD

**Issue by palzkillm** [uBlockOrigin/uAssets#15829]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.airbnb.de/`

### Category

nuisance

### Describe the issue

The German airbnb.de shows a video overlay called "Winter Update" on every load of the homepage. I contacted user support and asked how this can be removed/"marked as read", their answer was, that it CAN NOT BE removed permanently.

Thus, I'd like for this thing to be removed via Adblocking lists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/107746723/204275195-4e5bac2d-1f20-4be0-8273-9164d70cacff.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 263544
  cosmetic: 223086
  scriptlet: 37607
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61285-97, 3d.57m
    adguard-generic: 65949-516, 3d.56m
    adguard-mobile: 8248-51, 2d.21h.43m
    adguard-social: 19055-825, 2d.21h.42m
    adguard-spyware: 32896-3865, 2d.21h.41m
    adguard-spyware-url: 850-1, 2d.21h.18m
    curben-phishing: 122856-1, 22h.37m
    fanboy-annoyance: 83281-5020, 5d.18h.12m
    fanboy-cookiemonster: 43554-43554, 5d.18h.11m
    fanboy-social: 23443-23394, 3h.11m
    fanboy-thirdparty_social: 68-21, 5d.18h.10m
    ublock-annoyances: 4795-233, 2d.21h.16m
  default: 
    user-filters: 0-0, never
    DEU-0: 6048-0, 22h.38m
    easylist: 64848-1077, 22h.40m
    easyprivacy: 30897-12295, 22h.39m
    plowe-0: 3667-1036, 1d.22h.14m
    ublock-abuse: 77-0, 2d.21h.17m
    ublock-badware: 4035-255, 2d.21h.15m
    ublock-filters: 31487-3700, 2d.21h.7m
    ublock-privacy: 258-50, 2d.21h.6m
    ublock-quick-fixes: 363-35, 22h.36m
    ublock-unbreak: 1903-102, 2d.2h.20m
    urlhaus-1: 10720-4, 22h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 33 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1252 ms (selfie)
  maxAssetCacheWait: 1095 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    airbnb.de: 15
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
airbnb.de##section:has-text(Winter-Update):upward(1)
airbnb.de##body,html:style(overflow: auto !important;)
```
