### ISSUE TITLE
capecodtimes.com: breakage

### ISSUE THREAD

**Issue by seveno8** [uBlockOrigin/uAssets#15828]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.capecodtimes.com/news/`

### Category

breakage

### Describe the issue

Page freezes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 88426
  cosmetic: 38319
  scriptlet: 16587
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 62416-627, never
    easyprivacy: 30822-1176, never
    plowe-0: 3671-534, never
    ublock-abuse: 76-0, never
    ublock-badware: 3943-0, never
    ublock-filters: 31097-49, never
    ublock-privacy: 260-0, never
    ublock-quick-fixes: 424-0, never
    ublock-unbreak: 1873-0, never
    urlhaus-1: 11291-0, never
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 835 ms
  maxAssetCacheWait: 5 ms
popupPanel: 
  blocked: 1237
  blockedDetails: 
    capecodtimes.com: 3
    adsafeprotected.com: 1212
    adsrvr.org: 1
    amazon-adsystem.com: 1
    aswpsdkus.com: 1
    btloader.com: 1
    confiant-integrations.net: 1
    doubleclick.net: 2
    facebook.net: 1
    gannettinnovation.com: 1
    google-analytics.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
    igodigital.com: 1
    imasdk.googleapis.com: 1
    impactradius-event.com: 1
    krxd.net: 1
    parsely.com: 1
    sc-static.net: 1
    scorecardresearch.com: 1
    taboola.com: 2
    xg4ken.com: 1
```
</details>

**Comment by mapx-** [comment]
Try resetting uBO to default settings, update ALL filter lists, don't modify the settings or add other lists. Test again.
Also, disable other blocking extensions or - if any - builtin blockers in your browser.
