### ISSUE TITLE
Anti adblock on site

### ISSUE THREAD

**Issue by Dragon1998a** [uBlockOrigin/uAssets#15822]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The following site blocks content with u block origin and both the AdGuard Annoyances and uBlock filters – Annoyances active

`https://nov4w.dubznetwork.com/meet/soccer/fifa-world-cup-spain-vs-germany-27nov/`

### A specific URL where the issue occurs.

`https://nov4w.dubznetwork.com/meet/soccer/fifa-world-cup-spain-vs-germany-27nov/`

### Steps to Reproduce

open site
play video

### Expected behavior

no ad block popup

### Actual behavior

can't play video

### Configuration

.

**Comment by mapx-** [comment]
update ALL your filter lists, it was already fixed
