### ISSUE TITLE
codingnepalweb.com: detection

### ISSUE THREAD

**Issue by barraIhsan** [uBlockOrigin/uAssets#15838]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.codingnepalweb.com/qr-code-generator-html-css-javascript/`

### Category

detection

### Describe the issue

The popup only show when you try to highlight a code

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/57800056/204416468-3fddceb2-ed67-4960-acc2-c1af82255a05.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 101841
  cosmetic: 113933
  scriptlet: 21740
  html: 882
listset (total-discarded, last-updated): 
  added: 
    https://api.stopmodreposts.org/minecraft/hosts.txt: 1120-10, 2d.11h.4m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2044-1, 23m
    adguard-spyware-url: 850-123, 2d.11h.4m
    fanboy-annoyance: 83355-409, 2d.11h.4m
    ublock-annoyances: 4819-4, 2d.11h.4m
  default: 
    user-filters: 20-0, never
    ublock-filters: 32292-65, 1d.35m
    ublock-badware: 4044-1, 1d.34m
    ublock-privacy: 307-2, 1d.33m
    ublock-abuse: 77-0, 1d.32m
    ublock-unbreak: 1922-2, 1d.31m
    ublock-quick-fixes: 389-0, 26m
    easylist: 64928-626, 1d.29m
    easyprivacy: 30889-1712, 1d.28m
    urlhaus-1: 10796-0, 25m
    plowe-0: 3667-3, 1d.25m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1803 ms (selfie)
  maxAssetCacheWait: 393 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    doubleclick.net: 2
    google.com: 3
    googlesyndication.com: 11
    googletagmanager.com: 4
    onesignal.com: 2
    youtube.com: 5
```
</details>

**Comment by okiehsch** [comment]
I can only reproduce if I disable `uBO-filters`.

**Comment by okiehsch** [comment]
Works fine with Firefox on my end.
![image](https://user-images.githubusercontent.com/16838044/204477313-a33a757f-319c-4ffe-b112-ed26f3984428.png)

**Comment by barraIhsan** [comment]
Oops, it seems because another blocker. I forgot to use a specific profile to report.
![image](https://user-images.githubusercontent.com/57800056/204496987-3bde9ae1-f3fa-46d0-9092-82d1edf11730.png)

**Comment by imheinrichlunge** [comment]
I tried disabling the Dark Reader extension in Firefox, but that didn't work either.

Here's how it looks in my end:
![Screenshot 2024-05-17 151224](https://github.com/uBlockOrigin/uAssets/assets/79764954/f18e0236-75bb-4a1a-971f-28e7aec85b5b)
![image](https://github.com/uBlockOrigin/uAssets/assets/79764954/7dea0471-1b03-4580-b8a5-5db5ce23588e)
![image](https://github.com/uBlockOrigin/uAssets/assets/79764954/2ffbeb8e-3e64-414e-bece-47cf880279d8)
![image](https://github.com/uBlockOrigin/uAssets/assets/79764954/70d3d067-b8d5-48db-a2d9-e97a3f18127c)

**Comment by stephenhawk8054** [comment]
@imheinrichlunge Test again in a new Firefox profile with only uBO and its default settings
