### ISSUE TITLE
tenies-online.best: nuisance

### ISSUE THREAD

**Issue by maik72** [uBlockOrigin/uAssets#15832]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tenies-online.best/load/17-1-0-38136`

### Category

nuisance

### Describe the issue

An annoying overlay which you have to click twice before it disappears completely. Thank you so much for the wonderful job so far!!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG031143](https://user-images.githubusercontent.com/59983043/204296192-1ea96a43-3667-4ac0-9130-653219906b9c.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 90831
  cosmetic: 39121
  scriptlet: 16743
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 30-0, never
    GRC-0: 1004-0, 11m
    easylist: 64811-57, 2d.20h.44m
    easyprivacy: 30872-1171, 5d.4h.17m
    plowe-0: 3669-871, 5d.15m
    ublock-abuse: 76-0, 8d.16h.36m
    ublock-badware: 4035-110, 1d.22h.59m
    ublock-filters: 31512-125, 1d.22h.58m
    ublock-privacy: 258-1, 8d.16h.35m
    ublock-quick-fixes: 359-15, 14h.39m
    ublock-unbreak: 1906-43, 1d.22h.57m
    urlhaus-1: 10720-0, 14h.40m
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 146 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 18
  no-cosmetic-filtering: true
  blockedDetails: 
    google.com: 3
    googletagmanager.com: 1
    intorterraon.com: 1
    perpetratorsane.com: 1
    yadro.ru: 1
    youtube.com: 11
```
</details>

**Comment by mapx-** [comment]
`no-cosmetic-filtering: true`

You disabled the cosmetic filters

Enable it again, update ALL your filter lists.
