### ISSUE TITLE
twitter.com filter no longer working

### ISSUE THREAD

**Issue by WesleyAC** [uBlockOrigin/uAssets#15835]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://twitter.com/home`
`https://mobile.twitter.com/home`

### Describe the issue

Promoted Tweets are showing up on Twitter.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 105.0.3

### Settings

No changes to defaults

### Notes

See Reddit discussion as well: https://old.reddit.com/r/uBlockOrigin/comments/z73yk9/twitter_promoted_tweets_showing_up/

**Comment by mapx-** [comment]
Test

```
twitter.com##[data-testid="tweet"]:has-text(Promoted)
twitter.com##[data-testid="UserCell"]:has-text(Promoted)
```

**Comment by u-RraaLL** [comment]
> Test
> 
> ```
> twitter.com##[data-testid="tweet"]:has-text(Promoted)
> twitter.com##[data-testid="UserCell"]:has-text(Promoted)
> ```

I'd replace it with:

    twitter.com##[data-testid="tweet"] [d$="10H8.996V8h7v7z"]:upward([data-testid="tweet"])
    twitter.com##[data-testid="UserCell"] [d$="10H8.996V8h7v7z"]:upward([data-testid="UserCell"])

 This is language-neutral.

**Comment by Lazza** [comment]
"Promoted" text only works if you are using English as your browser language. Targeting the path is the way to go, however recently it seems that uBlock Origin does not hide promoted tweets anymore.

I have developed a similar filter that works:

https://gist.github.com/Lazza/50af7eb641a0262931bca910c52fc6c6

**Comment by Yuki2718** [comment]
What's in your rule should already be covered by
```
twitter.com#?#div[data-testid="UserCell"]:-abp-has(path[d$="10H8.996V8h7v7z"])
twitter.com#?#div[data-testid="eventHero"]:-abp-has(path[d$="10H8.996V8h7v7z"])
twitter.com#?#article[data-testid="tweet"]:-abp-has(path[d$="10H8.996V8h7v7z"])
twitter.com#?#div[data-testid="trend"]:-abp-has(path[d$="10H8.996V8h7v7z"])
```
and I see no unblock.

**Comment by Lazza** [comment]
Thank you @Yuki2718 for pointing out those 4 filters (which, as I understand, are slightly different than the ones written above).

However, I am pretty confused. When did those end up in the uBlock filters? Until 2 days ago, I am sure I was seeing ads on Twitter, hence I created my filter rule and posted it on Gist.

Are those four lines a recent addition? Thank you.

**Comment by u-RraaLL** [comment]
They've been in EasyList for months.

If you didn't disable this list, it's possible it didn't update fully (it happened in the past) - force an update of the list and report back.

**Comment by Lazza** [comment]
I don't have an option to force upgrade, anyways yesterday I verified they are now present in my filters.

It is still a mystery on why it was not the case a few days ago. I know at least 5 people who were having the same problem with sponsored tweets and had to include my custom filter.

All is well that ends well, I guess.

**Comment by Yuki2718** [comment]
Maybe this: https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1364644643

**Comment by Lazza** [comment]
Ah, that seems to make sense. I started noticing the issue in the Elon era, so I assumed they changed something on the web UI.

It seems it was just a coincidence in the timing, then.

**Comment by u-RraaLL** [comment]
> don't have an option to force upgrade

https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#update-now

**Comment by Lazza** [comment]
What I meant is that it was greyed out. I see in the docs that I can purge all the entries in order to re-activate it.

Thank you for pointing that out.
