### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by ashrafnaeem1** [uBlockOrigin/uAssets#15831]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.google.com/`

### Category

ads

### Describe the issue

google is showing text add below search bar saying, "New! Meet the Google Pixel 7 and Pixel 7 Pro." [Find out more](https://www.google.com/url?q=https://www.youtube.com/watch%3Fv%3DeRaM2fjRSlU%26utm_source%3DHPP%26utm_medium%3Dyoutubevideo%26utm_campaign%3DPixel_7Pro_launch&source=hpp&id=19032726&ct=3&usg=AOvVaw3Ln6utTyu8i7cfUw7snaQn&sa=X&ved=0ahUKEwjEv5LvgNH7AhWmpVYBHTGpDZQQ8IcBCBM)

its an add so should be included in filterlists (i mean i did not subscribe those updates so why bother me.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Google - Google Chrome 11_28_2022 7_19_09 PM-crop](https://user-images.githubusercontent.com/75166009/204294064-8f74a94d-7dba-4df5-a38a-2bbe775ebdfa.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 120009
  cosmetic: 167419
  scriptlet: 24528
  html: 0
listset (total-discarded, last-updated): 
  added: 
    CHN-0: 28830-94, 3d.1h.10m
    JPN-1: 8298-8, 3d.1h.9m
    adguard-annoyance: 61292-111, 3d.1h.7m
    adguard-social: 19055-821, 2d.23h.44m
    ara-0: 2727-0, 20h.7m
    fanboy-cookiemonster: 43370-3258, 20h.14m
    spa-0: 3410-14, 20h.6m
    ublock-annoyances: 4794-189, 20h.9m
  default: 
    user-filters: 43-3, never
    easylist: 64782-179, 3d.1h.12m
    easyprivacy: 30889-1315, 19h.54m
    plowe-0: 3668-879, 9d.1h.6m
    ublock-abuse: 77-0, 20h.12m
    ublock-badware: 4040-110, 20h.11m
    ublock-filters: 31526-527, 20h.10m
    ublock-privacy: 258-3, 4h.24m
    ublock-unbreak: 1903-49, 3d.1h.8m
    urlhaus-1: 10720-0, 20h.8m
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 924 ms (selfie)
  maxAssetCacheWait: 646 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    google.com: 10
```
</details>

**Comment by mapx-** [comment]
try

google.*##[class$="-slot-promo"]

@ryanbr

**Comment by ashrafnaeem1** [comment]
> google.*##[class$="-slot-promo"]

Thanks, its working for me however it would be better if it is included in easylist, it is an ad literally. (The class itself says that.) Though I would like to thank easylist contributers to be so active. They work real hard!

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
it seems not visible anymore

**Comment by krystian3w** [comment]
Back with anoter trash "how to save energy every day":

![image](https://user-images.githubusercontent.com/35370833/207533649-c8f3a89c-e95b-42e1-bfd4-6dd26eeb8301.png)

**Comment by mapx-** [comment]
@krystian3w you should report it at EL. For me could be self-promo such "ad"
