### ISSUE TITLE
[nsfw] lsrelay-config-production.s3.amazonaws.com: detection

### ISSUE THREAD

**Issue by woolfblood22** [uBlockOrigin/uAssets#15836]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://lsrelay-config-production.s3.amazonaws.com/`

### Category

detection

### Describe the issue

need to fix blocked icon 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 90402
  cosmetic: 38521
  scriptlet: 16743
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64921-53, 3h.59m
    easyprivacy: 30904-1171, 3h.58m
    plowe-0: 3669-870, 6d.16h.30m
    ublock-abuse: 76-0, 6d.16h.28m
    ublock-badware: 4040-110, 19h.8m
    ublock-filters: 31508-127, 19h.7m
    ublock-privacy: 258-1, 6d.16h.24m
    ublock-quick-fixes: 356-22, 19h.5m
    ublock-unbreak: 1909-45, 19h.6m
    urlhaus-1: 10585-0, 19h.4m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1692 ms (selfie)
  maxAssetCacheWait: 805 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google.com: 1
```
</details>

**Comment by mapx-** [comment]
> need to fix blocked icon

provide a decent explanation / steps to reproduce your issue
