### ISSUE TITLE
passion.com: breakage

### ISSUE THREAD

**Issue by NEPOMUCENE1** [uBlockOrigin/uAssets#15834]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://passion.com/p/interested.cgi?dcb=passion.com&pwsid=373320421_53127&active_tab=profile_view`

### Category

breakage

### Describe the issue

> La page ne s'affiche pas normalement, les liens ne fonctionnent pas, les images ne s'affichent pas.

**The page does not display normally, the links do not work, the images do not display.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/119350716/204349979-a1a8cd00-370f-41fb-91d0-ec6f0a9aa741.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 108492
  cosmetic: 47225
  scriptlet: 16657
  html: 792
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31834-159, never
    ublock-badware: 3947-0, never
    ublock-privacy: 288-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1886-0, never
    ublock-quick-fixes: 430-0, never
    easylist: 62416-659, never
    easyprivacy: 30822-1707, never
    urlhaus-1: 11291-0, never
    plowe-0: 3671-3, never
    FRA-0: 30209-454, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 874 ms
  maxAssetCacheWait: 402 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    passion.com: 35
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add and see if works

`||passion.com^$badfilter`

If does not work => what did you click in the left side menu to get that page ?

**Comment by mapx-** [comment]
@smed79 why did you block the site ?
