### ISSUE TITLE
dealabs.com: breakage

### ISSUE THREAD

**Issue by dClauzel** [uBlockOrigin/uAssets#15833]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dealabs.com/`

### Category

breakage

### Describe the issue

The user menu doesn’t appear when the user click on the menu’s icon.

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 167402
  cosmetic: 242841
  scriptlet: 37865
  html: 0
listset (total-discarded, last-updated): 
  added: 
    http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/: 25532-4, 2d.11h.23m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 1d.6h.13m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 2d.7h.7m
    https://www.i-dont-care-about-cookies.eu/abp/: 25532-25532, 2d.11h.22m
    adguard-annoyance: 61277-1678, 3d.8h.44m
    adguard-generic: 65942-785, 3d.8h.43m
    adguard-mobile: 8242-186, 3d.8h.48m
    adguard-social: 19051-827, 3d.8h.45m
    adguard-spyware: 32893-3943, 3d.8h.41m
    adguard-spyware-url: 850-1, 1d.6h.14m
    fanboy-annoyance: 83201-13105, 8d.23m
    fanboy-cookiemonster: 43483-43482, 8d.21m
    fanboy-thirdparty_social: 69-21, 8d.22m
    ublock-annoyances: 4795-233, 3d.8h.47m
  default: 
    user-filters: 144-0, never
    FRA-0: 30148-33, 3d.8h.42m
    easylist: 64761-1285, 3d.38m
    easyprivacy: 30880-12639, 3d.4h.39m
    plowe-0: 3667-2482, 1d.2h.5m
    ublock-abuse: 77-1, 2d.15h.33m
    ublock-badware: 4035-273, 3d.8h.46m
    ublock-filters: 31492-3584, 3d.8h.50m
    ublock-privacy: 260-50, 1d.18h.54m
    ublock-quick-fixes: 363-35, 18h.4m
    ublock-unbreak: 1902-102, 3d.8h.49m
    urlhaus-1: 10585-0, 13h.52m
filterset (user): [array of 144 redacted]
trustedset: 
  added: [array of 216 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9229 ms
  maxAssetCacheWait: 7605 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    dealabs.com: 4
    googletagmanager.com: 1
    pepper.com: 4
```
</details>

**Comment by Yuki2718** [comment]
Maybe due to any of those too many filter lists. Reset to default settings and test again.

**Comment by Yuki2718** [comment]
> * [x]  I did not answer truthfully to **all** the above checkpoints

**Comment by Shasdo** [comment]
Same problem with Firefox Nightly on Android 15 with ublock origin.

Filter block the loading of the cookie prompt and preventing access to account menu

Deactivating the "Easylist/uBO - Cookie notice" list seems to have solved the issue.
