### ISSUE TITLE
modrinth.com: ads

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#15839]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://modrinth.com/mod/no-chat-reports`

### Category

ads

### Describe the issue

shows that there's an ad for a minecraft hosting service

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Copy](https://user-images.githubusercontent.com/104040739/204429262-62e3ff6a-08a5-4a6d-9791-8aad1611835f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90711
  cosmetic: 38534
  scriptlet: 16737
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32302-70, 2m
    ublock-badware: 4044-1, 2m
    ublock-privacy: 307-0, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1923-2, 2m
    ublock-quick-fixes: 395-0, 2m
    easylist: 64992-625, 2m
    easyprivacy: 30904-1712, 2m
    urlhaus-1: 10796-0, 2m
    plowe-0: 3677-3, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3192 ms
  maxAssetCacheWait: 355 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    modrinth.com: 1
    cloudflareinsights.com: 2
```
</details>

**Comment by okiehsch** [comment]
`modrinth.com##[href^="https://bisecthosting.com/"]`
@ryanbr

**Comment by KaspianDev** [comment]
I have a filter ready, let me know in which file does it go.
