### ISSUE TITLE
showtimeanytime.com: movies don't play

### ISSUE THREAD

**Issue by kevinoid** [uBlockOrigin/uAssets#15837]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.showtimeanytime.com/play/3504625`
(or any other movie)

### Describe the issue

The movie does not play.  Pressing the play button has no effect.  Attempting to seek to any position in the movie has no effect.  If there is a pre-movie ad, it will play, but the movie will not play after the ad.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox Nightly 109.0a1 (2022-11-28) (64-bit)

### Settings

Enable either "EasyPrivacy" or "Peter Lowe’s Ad and tracking server list" in "Filter Lists".

### Notes

The issue occurs due to blocking `https://src.litix.io/shakaplayer/5/shakaplayer-mux.js` which I was able to work around with:

    @@||src.litix.io/shakaplayer/5/shakaplayer-mux.js$script,domain=www.showtimeanytime.com

I'm not sure if a more generic rule might be more future-proof.

Also note that xhr requests to other litix.io subdomains (e.g. `https://a3krscrg9223j3877578rth0l.litix.io/` in my test) are still blocked, which does not appear to affect the ability to play movies.

I attempted to report the issue directly to EasyPrivacy, but was unable to register an account on https://forums.lanik.us/

**Comment by mapx-** [comment]
@ryanbr 

@kevinoid just report here (Easylist repository) in the future:
https://github.com/easylist/easylist/issues
