### ISSUE TITLE
diziyou.com: ads

### ISSUE THREAD

**Issue by soyluburkay** [uBlockOrigin/uAssets#15846]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.diziyou.com/modern-family-4-sezon-3-bolum/`

### Category

ads

### Describe the issue

Two ads appear before the video plays.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 91758
  cosmetic: 47284
  scriptlet: 17830
  html: 858
listset (total-discarded, last-updated): 
  added: 
    TUR-0: 11478-11, 1d.1h.57m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32309-65, 2d.3h.54m
    ublock-badware: 4039-1, 2d.3h.55m
    ublock-privacy: 305-0, 6d.7h.58m
    ublock-abuse: 77-0, 6d.7h.59m
    ublock-unbreak: 1919-0, 2d.3h.53m
    easylist: 64810-642, 5d.5h.25m
    easyprivacy: 30874-1715, 5d.5h.24m
    urlhaus-1: 10479-0, 6h.15m
    plowe-0: 3677-3, 6h.16m
    ublock-quick-fixes: 366-1, 6h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 441 ms (selfie)
  maxAssetCacheWait: 318 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    diziyou.com: 5
    adform.net: 2
    diziyoucdn.xyz: 2
    googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment]
`||diskstore.xyz^$media,domain=diziyou.com`

@Yuki2718 for the regional turkish Adguard list.
