### ISSUE TITLE
Broken Shopify WHOIS tool

### ISSUE THREAD

**Issue by TheCowMooooo** [uBlockOrigin/uAssets#15848]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.shopify.com/tools/whois`

### Describe the issue

Searching on the page does not load results, only spins

### Screenshot(s)

![image](https://user-images.githubusercontent.com/58637685/204698651-22a7f49a-0383-4e81-b819-4114ae59a419.png)

### uBlock Origin version

1.45.2

### Browser name and version

Chrome (107.0.5304.108)

### Settings

None, all default

**Comment by mapx-** [comment]
add

`||shopify.com/s/javascripts/tricorder/$script,badfilter`

@ryanbr
