### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by lenroK-code** [uBlockOrigin/uAssets#15847]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Describe the issue

When I want to watch a video, i wait at least 10 seconds to start it. Sometimes my Firefox crashes and I can't use it at all.
Without any adblocker the video opens up in a second.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 106
filterset (summary): 
  network: 62659
  cosmetic: 45975
  scriptlet: 16948
  html: 874
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 32312-106, 1m
    ublock-badware: 4049-1, 1m
    ublock-privacy: 307-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1925-2, 1m
    ublock-quick-fixes: 403-0, 1m
    easylist: 65014-629, 1m
    urlhaus-1: 10479-0, 1m
    plowe-0: 3677-3, 1m
    POL-0: 7859-25, 2m
    POL-2: 1279-12, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 642 ms
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    google.com: 1
    google.pl: 1
```
</details>

**Comment by ContentBlocker** [comment]
Visit `about:addons` - is there any add-on besides uBlock Origin on the browser (profile)?
