### ISSUE TITLE
foxrentacar.com: breakage

### ISSUE THREAD

**Issue by seveno8** [uBlockOrigin/uAssets#15853]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.foxrentacar.com/en/reserve-a-car.html`

### Category

breakage

### Describe the issue

There is a "box" on the right side of the screen that does not show when the app is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
App ON
https://user-images.githubusercontent.com/119309354/204788872-a42013dc-fd23-4a31-b8a1-ae6f09f5912d.png

App OFF
https://user-images.githubusercontent.com/119309354/204789028-2e47c4de-2c13-4a85-86e4-27f0804a3c07.png

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88422
  cosmetic: 38317
  scriptlet: 16582
  html: 792
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31834-153, never
    ublock-badware: 3947-0, never
    ublock-privacy: 288-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1886-0, never
    ublock-quick-fixes: 430-0, never
    easylist: 62416-169, never
    easyprivacy: 30822-1199, never
    urlhaus-1: 11291-0, never
    plowe-0: 3671-868, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1187 ms
  maxAssetCacheWait: 12 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    foxrentacar.com: 12
    bing.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by seveno8** [comment]
![image](https://user-images.githubusercontent.com/119309354/204789401-cfc3de7a-004e-40ad-ad30-c309d6156591.png)

**Comment by okiehsch** [comment]
`@@||foxrentacar.com/etc/designs/dotcom/clientlibs_base/*$script,1p`
@ryanbr

**Comment by seveno8** [comment]
> `@@||foxrentacar.com/etc/designs/dotcom/clientlibs_base/*$script,1p` @ryanbr

Is this a fix for the issue? I don't understand.
And if this is a fix, how will I know if this is not happening on other sites?
How will I know if some important part of the page is missing unless I turn off the app and refresh the page on  every site I visit.

**Comment by okiehsch** [comment]
> Is this a fix for the issue? I don't understand.

Yes. I notified the list maintainer and the issue will be fixed within that list.
Umtil then you can add
`@@||foxrentacar.com/etc/designs/dotcom/clientlibs_base/*$script,1p`
to your personal filter list then reload the site and the "box"  should reappear.

> how will I know if this is not happening on other sites?
How will I know if some important part of the page is missing unless I turn off the app and refresh the page on every site I visit.

The same way you knew that something was missing or not working in `foxrentacar.com`....
You are using a blocking extension, it's in the name, it blocks "stuff" mostly ads and trackers.
It will unintentionally block site content or break site functionality in rare cases, that's unavoidable and we fix these kind of issues as fast as possible.
