### ISSUE TITLE
brotje.fr: breakage

### ISSUE THREAD

**Issue by tbertels** [uBlockOrigin/uAssets#15851]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`http://www.brotje.fr/produits/type/chaudieres-au-sol/25-bgb-e.html`

### Category

breakage

### Describe the issue

The content below "Avantages" is missing.

This seems to be caused by `<span class="adv-title">` being blocked by the [procedural cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-30 at 09-16-16 BGB - Brotje](https://user-images.githubusercontent.com/3265870/204743222-695ec542-5aa2-4a04-870d-a606ea48a0bf.png)

instead of

![Screenshot 2022-11-30 at 09-16-28 BGB - Brotje](https://user-images.githubusercontent.com/3265870/204743321-a22f2b80-fc55-4390-8f57-9d8900a25143.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 78403
  cosmetic: 47495
  scriptlet: 16584
  html: 794
listset (total-discarded, last-updated): 
  removed: 
    ublock-privacy: null
    easyprivacy: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt: 0-0, 1d.11h.6m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 19h.51m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt: 0-0, 11h.28m
  default: 
    user-filters: 263-5, never
    ublock-filters: 32277-38, 3d.20h.14m
    ublock-badware: 4044-1, 23h.56m
    ublock-abuse: 77-0, 7d.40m
    ublock-unbreak: 1923-1, 23h.54m
    easylist: 64783-296, 4d.12h.57m
    FRA-0: 30235-157, 23h.55m
    urlhaus-1: 10796-0, 19h.52m
filterset (user): [array of 263 redacted]
trustedset: 
  added: [array of 207 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 10 redacted]
  removed: 
    no-large-media: behind-the-scene false
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  hyperlinkAuditingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6451 ms (selfie)
  maxAssetCacheWait: 5169 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@smed79 

`#@#.adv-title`

**Comment by smed79** [comment]
removed https://github.com/easylist/listefr/commit/a47470f47f3081071f516c1c6652fe5d269c81d0#diff-ed13803752993344f0a395c14a947fdc07bf1b7fcbe027591005b9425ce7e7fcL20012
