### ISSUE TITLE
heatware.com: breakage

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [uBlockOrigin/uAssets#15858]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.heatware.com/a/3770`

### Category

breakage

### Describe the issue

Album photos break when enabled. This site shouldn't be filtered, it doesn't even have ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[image](https://user-images.githubusercontent.com/3820074/204883089-3f407af6-bb3e-442d-8df8-7ffa9c212fa9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 90315
  cosmetic: 38524
  scriptlet: 16741
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64921-53, 2d.1h.43m
    easyprivacy: 30897-1171, 2d.1h.42m
    plowe-0: 3668-869, 12d.1h.10m
    ublock-abuse: 77-0, 2d.1h.41m
    ublock-badware: 4040-110, 2d.1h.40m
    ublock-filters: 31509-127, 2d.1h.39m
    ublock-privacy: 260-1, 2d.1h.38m
    ublock-quick-fixes: 380-22, 23h.57m
    ublock-unbreak: 1909-45, 2d.1h.37m
    urlhaus-1: 10479-0, 23h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 205 ms (selfie)
  maxAssetCacheWait: 85 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`heatware.com#@#.ads-image`

@ryanbr
