### ISSUE TITLE
omny.fm

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#15860]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://omny.fm/shows/the-inside-story-podcast/whats-behind-the-france-germany-tensions`

### Category

-

### Describe the issue

error at the end of the audio, which persists after disabling adblock.. 

```
00:00 - I start whit uBO off
00:20 - uBO on + refresh page
00:33 - uBO off + refresh page
```

https://user-images.githubusercontent.com/33556647/204927699-5d31eec2-5145-4f70-b7bd-d6ca765563f4.mp4

### Configuration

```
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 92865
  cosmetic: 45113
  scriptlet: 20203
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4796-6, 21h.6m
  default: 
    user-filters: 0-0, never
    easylist: 65014-53, 21h.6m
    easyprivacy: 30911-1171, 21h.6m
    plowe-0: 3677-871, 21h.6m
    spa-0: 3424-11, 21h.6m
    spa-1: 4869-183, 21h.6m
    ublock-abuse: 77-0, 21h.6m
    ublock-badware: 4045-110, 21h.6m
    ublock-filters: 31524-170, 21h.6m
    ublock-privacy: 260-1, 21h.6m
    ublock-quick-fixes: 392-25, 21h.6m
    ublock-unbreak: 1912-48, 21h.6m
    urlhaus-1: 10095-0, 21h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 209 ms (selfie)
  maxAssetCacheWait: 186 ms
```

**Comment by mapx-** [comment]
still ok on my end
