### ISSUE TITLE
dizimom1.com: detection

### ISSUE THREAD

**Issue by hgunduz295** [uBlockOrigin/uAssets#15866]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dizimom1.com/`

### Category

detection

### Describe the issue

![image](https://user-images.githubusercontent.com/36344949/205010416-d360cc34-79e5-43d1-9974-68f7db9bb6bc.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/36344949/205010416-d360cc34-79e5-43d1-9974-68f7db9bb6bc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 106
filterset (summary): 
  network: 91476
  cosmetic: 47262
  scriptlet: 17830
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    TUR-0: 11477-10, 2d.14h.56m
    easylist: 64921-72, 2d.14h.54m
    easyprivacy: 30897-1176, 2d.14h.53m
    plowe-0: 3677-872, 2d.14h.52m
    ublock-abuse: 77-0, 2d.14h.50m
    ublock-badware: 4040-110, 2d.14h.48m
    ublock-filters: 31498-136, 2d.14h.47m
    ublock-privacy: 260-1, 2d.14h.46m
    ublock-quick-fixes: 387-15, 2h.9m
    ublock-unbreak: 1909-45, 2d.14h.44m
    urlhaus-1: 10022-0, 2h.8m
filterset (user): [array of 3 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 462 ms (selfie)
  maxAssetCacheWait: 245 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    dizimom1.com: 1
    google.com: 6
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> dizimom1.com: 1

maybe you added some custom filter ? check "my filters" and disable any filter you added there

**Comment by hgunduz295** [comment]
> 
I add filter for this issue  but its not solve my problem

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera / vivaldi/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by hgunduz295** [comment]
Solved

**Comment by mapx-** [comment]
@hgunduz295 what in your setup was wrong ?

**Comment by hgunduz295** [comment]
> @hgunduz295 what in your setup was wrong ?

I forgot Opera gx adblock is open  when i close opera built in adblock   problem fixed
