### ISSUE TITLE
hotukdeals.com: breakage

### ISSUE THREAD

**Issue by Rob-Skull** [uBlockOrigin/uAssets#15867]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hotukdeals.com/`

### Category

breakage

### Describe the issue

the message and notification buttons no longer work - screenshots attached, including with them working with filter turned off.
<img width="289" alt="Screenshot 2022-12-01 at 09 30 10" src="https://user-images.githubusercontent.com/119583480/205017055-2ed1fb79-275c-48fe-acf9-8a6b3f1ce230.png">
<img width="403" alt="Screenshot 2022-12-01 at 09 30 25" src="https://user-images.githubusercontent.com/119583480/205017064-5ce3bd8f-0c74-498d-a592-2d28a7acc627.png">
<img width="387" alt="Screenshot 2022-12-01 at 09 30 29" src="https://user-images.githubusercontent.com/119583480/205017068-9c7a5962-84a2-49b3-aea0-22eb31da6817.png">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 120382
  cosmetic: 180709
  scriptlet: 24995
  html: 883
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware: 32913-3321, 3d.17h.27m
    adguard-spyware-url: 850-3, 3d.17h.28m
    adguard-annoyance: 61319-5228, 3d.17h.26m
    adguard-social: 19064-1065, 3d.17h.29m
    fanboy-thirdparty_social: 68-0, 3d.17h.33m
    fanboy-annoyance: 83355-67218, 3d.17h.32m
    fanboy-cookiemonster: 43625-204, 3d.17h.34m
    fanboy-social: 23397-28, 4d.12h.51m
    ublock-annoyances: 4821-4, 3d.17h.30m
  default: 
    user-filters: 8-2, never
    ublock-filters: 32309-67, 3d.17h.31m
    ublock-badware: 4044-1, 3d.17h.25m
    ublock-privacy: 305-0, 7d.8h.17m
    ublock-abuse: 77-0, 7d.8h.16m
    ublock-unbreak: 1922-1, 3d.17h.24m
    easylist: 64782-680, 4d.21h.59m
    easyprivacy: 30881-12569, 4d.21h
    urlhaus-1: 9729-0, 14h.34m
    plowe-0: 3667-3, 4d.12h.52m
    ublock-quick-fixes: 398-1, 14h.35m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1618 ms (selfie)
  maxAssetCacheWait: 403 ms
popupPanel: 
  blocked: 45
  blockedDetails: 
    hotukdeals.com: 4
    googletagmanager.com: 1
    pepper.com: 40
```
</details>

**Comment by mapx-** [comment]
finally I was able to reproduce the issue:

add

`hotukdeals.com#@#.vue-portal-target.popover-portal`

@ryanbr FA issue

**Comment by mapx-** [comment]
- it seems the filter was already removed but updating the list is buggy (cloudflare issue)
- for now @Rob-Skull just add the exception above

**Comment by Rob-Skull** [comment]
Thanks for the quick replies, and please forgive me for my absolute ignorance in applying this exception

where precisely do I go in the settings to add this exception?

hotukdeals.com#@#.vue-portal-target.popover-portal
________________________________

**Comment by mapx-** [comment]
Click uBO icon, open the dashboard (last icon on the bottom right), "my filters" tab, add the exception, click "apply changes"
