### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by LaxusiC** [uBlockOrigin/uAssets#15864]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Describe the issue

left over banner ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-12-1 10-12-39](https://user-images.githubusercontent.com/9650215/204957390-ee0ffea1-abff-4150-8998-0487ea21b227.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 86
filterset (summary): 
  network: 130322
  cosmetic: 125389
  scriptlet: 32729
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://abpvn.com/vip/laxusic.txt: 3663-0, 7m
    adguard-annoyance: 61427-97, 1d.20m
    adguard-generic: 65963-686, 1d.19m
    adguard-spyware: 33811-4005, 1d.18m
  default: 
    user-filters: 6-1, never
    easylist: 64783-1169, 5d.22h.44m
    easyprivacy: 30877-12725, 5d.22h.44m
    plowe-0: 3669-974, 5d.22h.44m
    ublock-abuse: 77-1, 1d.17m
    ublock-badware: 4045-260, 1d.16m
    ublock-filters: 31524-3696, 1d.15m
    ublock-privacy: 260-42, 1d.14m
    ublock-quick-fixes: 420-51, 9m
    ublock-unbreak: 1912-102, 1d.13m
    urlhaus-1: 10022-0, 8m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 880 ms (selfie)
  maxAssetCacheWait: 507 ms
popupPanel: 
  blocked: 54
  blockedDetails: 
    youtube.com: 33
    doubleclick.net: 5
    google.com: 6
    google.com.sg: 1
    sentry.io: 8
    ytimg.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1333274332

**Comment by gwarser** [comment]
`Chromium: 86` 

Try dev version?
