### ISSUE TITLE
axa.fr: breakage

### ISSUE THREAD

**Issue by Primokorn** [uBlockOrigin/uAssets#15868]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.axa.fr/compte-bancaire/annexes-axabanque/faq-web-connected.html`

### Category

breakage

### Describe the issue

I can't click on the 3 options available in the Contact category.

### Screenshot(s)

<details>

<summary>Screenshot(s)</summary>

![2022-12-01_11-29](https://user-images.githubusercontent.com/5938828/205029771-9cd6a623-a8eb-4cd2-b70a-1fca39a0c27f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 114457
  cosmetic: 87265
  scriptlet: 18654
  html: 859
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2044-1, 34m
    adguard-spyware-url: 852-124, 36m
    fanboy-cookiemonster: 43625-158, 3d.17h.20m
  default: 
    user-filters: 3-0, never
    ublock-filters: 32309-165, 3d.16h.32m
    ublock-badware: 4045-1, 39m
    ublock-privacy: 305-2, 8d.19h.7m
    ublock-abuse: 77-0, 8d.19h.6m
    ublock-unbreak: 1922-3, 38m
    ublock-quick-fixes: 431-1, 33m
    easylist: 64848-680, 3d.17h.19m
    easyprivacy: 30889-1710, 3d.17h.18m
    urlhaus-1: 10022-0, 32m
    plowe-0: 3667-3, 3d.17h.21m
    FRA-0: 30230-456, 35m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 765 ms (selfie)
  maxAssetCacheWait: 305 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    axa.fr: 1
    aticdn.net: 1
    googletagmanager.com: 2
    iadvize.com: 3
    inbenta.io: 15
    omtrdc.net: 1
    tagcommander.com: 1
    trustcommander.net: 1
```
</details>

**Comment by okiehsch** [comment]
ADd
`@@||api-gce2.inbenta.io/prod/km/v1/tracking/events$xhr,domain=axa.fr`
to your filter list.
@ryanbr
