### ISSUE TITLE
dizipal434.com: ads

### ISSUE THREAD

**Issue by haliliboov** [uBlockOrigin/uAssets#15869]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizipal434.com/dizi/supernatural/sezon-12/bolum-3`

### Category

ads

### Describe the issue

there is still ads on this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim_2022-12-01_153120162](https://user-images.githubusercontent.com/119598029/205053550-79e818ab-c2c3-4f44-9b9f-e1103b615379.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91561
  cosmetic: 47273
  scriptlet: 17829
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11472-10, 3d.19h.5m
    easylist: 64994-72, 1d.21h.40m
    easyprivacy: 30908-1176, 1d.21h.39m
    plowe-0: 3668-870, 12d.22h.7m
    ublock-abuse: 77-0, 1d.21h.38m
    ublock-badware: 4040-110, 3d.19h.4m
    ublock-filters: 31526-137, 3d.19h.3m
    ublock-privacy: 260-1, 1d.21h.37m
    ublock-quick-fixes: 385-15, 20m
    ublock-unbreak: 1909-45, 3d.19h.2m
    urlhaus-1: 10022-0, 21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1753 ms (selfie)
  maxAssetCacheWait: 483 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    dizipal434.com: 16
    diziyoucdn.xyz: 1
    googletagmanager.com: 1
    virusdesslavery.com: 1
```
</details>

**Comment by krystian3w** [comment]
If domain change numbers in fast interval then the best force update TUR-0 if somebody add new domain to list and AdGuard don't drop in favor own regex based on stable `[$domain=/dizipal[0-9]{1,3}\.com/]##...` or mix `[$domain=/[a-z]{5}[0-9]{1,3}\.com/]##...`.

**Comment by mapx-** [comment]
```
dizipal434.com##+js(nano-sib)
dizipal434.com###video1link
```

**Comment by krystian3w** [comment]
@MasterKia https://github.com/AdguardTeam/AdguardFilters/commit/fb6849265b8f08aee268d1dd5521f6d819214bb0
