### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by mufffffin56** [uBlockOrigin/uAssets#15877]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.hulu.com/watch/5c872767-233f-49b7-a39c-f7b967767633`

### Category

ads

### Describe the issue

shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 89889
  cosmetic: 38538
  scriptlet: 16746
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64927-53, 4d.3h.30m
    easyprivacy: 30911-1171, 1d.9h.28m
    plowe-0: 3679-871, 1h.37m
    ublock-abuse: 77-0, 1d.22h.22m
    ublock-badware: 4040-110, 2d.19h.19m
    ublock-filters: 31525-129, 1d.22h.24m
    ublock-privacy: 260-1, 1d.22h.23m
    ublock-quick-fixes: 387-25, 21h.23m
    ublock-unbreak: 1910-44, 1d.9h.27m
    urlhaus-1: 10022-0, 21h.24m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 28 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1266 ms (selfie)
  maxAssetCacheWait: 782 ms
popupPanel: 
  blocked: 3062
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    hulu.com: 1147
    ads-twitter.com: 1
    akamaihd.net: 8
    conviva.com: 392
    demdex.net: 50
    doubleclick.net: 1
    google-analytics.com: 2
    imrworldwide.com: 1
    omtrdc.net: 1098
    scorecardresearch.com: 360
    tealiumiq.com: 1
    yimg.com: 1
```
</details>

**Comment by mapx-** [comment]
same here https://github.com/uBlockOrigin/uAssets/issues/15761
