### ISSUE TITLE
pentest-tools.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15871]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://pentest-tools.com/cms-vulnerability-scanning/wordpress-scanner-online-wpscan`

### Category

breakage

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/205074891-4d1dd634-5fc2-4081-b87b-fd33ed541621.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/205074903-a4701f8b-339e-4095-86dd-faf41fd9458b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 109
filterset (summary): 
  network: 126514
  cosmetic: 189179
  scriptlet: 27240
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7825-2, 2h.9m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 2h.7m
    RUS-0: 39566-48, 10h.1m
    adguard-annoyance: 61556-801, 2h.10m
    adguard-spyware: 33816-3420, 2h.11m
    fanboy-annoyance: 83332-3943, 7d.14h.28m
    fanboy-cookiemonster: 43606-43606, 7d.10h.27m
    ublock-annoyances: 4796-214, 2h.8m
  default: 
    user-filters: 17-1, never
    easylist: 64894-164, 4d.4h.58m
    easyprivacy: 30889-12428, 4d.4h.57m
    ublock-abuse: 77-1, 5d.4h.52m
    ublock-badware: 4041-108, 2h.14m
    ublock-filters: 31537-647, 2h.13m
    ublock-privacy: 258-48, 5d.4h.51m
    ublock-quick-fixes: 387-25, 10h
    ublock-unbreak: 1910-64, 2h.12m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1557 ms (selfie)
  maxAssetCacheWait: 1120 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    pentest-tools.com: 4
    google-analytics.com: 1
    googletagmanager.com: 1
    vercel-analytics.com: 4
```
</details>

**Comment by krystian3w** [comment]
Works fine with Chrome 108 and without:

```yml
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7825-2, 2h.9m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 2h.7m
    RUS-0: 39566-48, 10h.1m
    adguard-annoyance: 61556-801, 2h.10m
    adguard-spyware: 33816-3420, 2h.11m
    fanboy-annoyance: 83332-3943, 7d.14h.28m
    fanboy-cookiemonster: 43606-43606, 7d.10h.27m
    ublock-annoyances: 4796-214, 2h.8m
```

So sus can by hidden in regional or manualy enabled list, or in Dev/Canary of Chromium.

**Comment by mapx-** [comment]
add

`@@||pentest-tools.com/_nuxt/BackToTop.$script,1p`

FA issue @ryanbr
