### ISSUE TITLE
511tactical.com: breakage

### ISSUE THREAD

**Issue by Starfleet42** [uBlockOrigin/uAssets#15876]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.511tactical.com/kingston-jacket.html`

### Category

breakage

### Describe the issue

uBlock causes the page not to load product images, instead page shows a placeholder "image coming soon" image.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-01 182356](https://user-images.githubusercontent.com/111660752/205186977-fe2e6904-5b69-453c-8add-35254d9c2437.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 89989
  cosmetic: 38576
  scriptlet: 16748
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 65079-53, 20h.36m
    easyprivacy: 30889-1171, 4d.18h.46m
    plowe-0: 3668-869, 10d.20h.30m
    ublock-abuse: 77-0, 2d.18h.38m
    ublock-badware: 4040-110, 3d.43m
    ublock-filters: 31508-127, 2d.20h.39m
    ublock-privacy: 260-1, 2d.18h.37m
    ublock-quick-fixes: 420-23, 20h.34m
    ublock-unbreak: 1910-46, 2d.20h.40m
    urlhaus-1: 10022-0, 20h.35m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 724 ms
  maxAssetCacheWait: 451 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    511tactical.com: 1
    affirm.com: 5
    datasteam.io: 1
    dynamicyield.com: 1
    facebook.net: 1
    g792337340.co: 2
    google-analytics.com: 1
    maps.googleapis.com: 1
    newrelic.com: 1
    riskified.com: 1
    scarabresearch.com: 1
    yotpo.com: 7
```
</details>

**Comment by mapx-** [comment]
add

`@@||511tactical.com/*/Magento_GoogleTagManager/js/google-tag-manager.min.js$script,1p`

EP issue @ryanbr
