### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by NakedTurkey** [uBlockOrigin/uAssets#15872]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/watch?v=xdcSFVXd3MU`

### Category

ads

### Describe the issue

An ad appear in the vídeo "5seconds"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91027
  cosmetic: 41646
  scriptlet: 16995
  html: 859
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32292-96, 3d.6h.57m
    ublock-badware: 4044-1, 3d.6h.56m
    ublock-privacy: 305-0, 6d.6h.56m
    ublock-abuse: 77-0, 6d.6h.55m
    ublock-unbreak: 1922-1, 3d.6h.55m
    easylist: 64993-669, 1d.20h.51m
    easyprivacy: 30906-1725, 1d.20h.50m
    urlhaus-1: 9729-0, 19h.25m
    plowe-0: 3667-3, 6d.49m
    spa-1: 4869-14, 3d.6h.58m
    ublock-quick-fixes: 398-0, 18h.48m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 403 ms (selfie)
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    youtube.com: 21
    doubleclick.net: 2
    google.com: 1
    google.com.br: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
