### ISSUE TITLE
app.mealime.com: breakage

### ISSUE THREAD

**Issue by absolutezer093** [uBlockOrigin/uAssets#15875]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.mealime.com/`

### Category

breakage

### Describe the issue

Content is missing from page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 93
filterset (summary): 
  network: 89424
  cosmetic: 38548
  scriptlet: 16744
  html: 864
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32330-70, 1d.6h.19m
    ublock-badware: 4049-1, 1d.6h.18m
    ublock-privacy: 305-0, 6d.7h.59m
    ublock-abuse: 77-0, 6d.7h.58m
    ublock-unbreak: 1924-2, 1d.6h.17m
    ublock-quick-fixes: 414-0, 1d.6h.16m
    easylist: 64784-622, 6d.7h.55m
    easyprivacy: 30874-1710, 6d.7h.54m
    urlhaus-1: 9729-0, 1d.6h.15m
    plowe-0: 3667-3, 6d.7h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1160 ms
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    sentry-cdn.com: 4
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
- update FF
- update uBO + all filter lists

Provide more details, screenshot (do you get a blank page ?) etc

uBO on / off I get the same page:

![image](https://user-images.githubusercontent.com/10303732/205232649-57869848-d4b0-4ea5-9870-50f22e8bd49b.png)
