### ISSUE TITLE
notebookcheck.net: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15878]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.notebookcheck.net/Asus-ROG-Flow-X13-GV301QH.520431.0.html`

### Category

breakage

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/205210340-1feb430b-06ea-46c0-abb8-e8a1ae85eb82.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/205210355-a2dd3390-ad6e-48b4-b3c0-4f74d1f21895.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 109
filterset (summary): 
  network: 126763
  cosmetic: 189341
  scriptlet: 27246
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7799-3, 13h.31m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 13h.31m
    RUS-0: 39579-48, 13h.31m
    adguard-annoyance: 61562-800, 13h.31m
    adguard-spyware: 33817-3420, 13h.31m
    fanboy-annoyance: 83458-3959, 13h.31m
    fanboy-cookiemonster: 43650-43650, 13h.31m
    ublock-annoyances: 4798-214, 13h.31m
  default: 
    user-filters: 17-0, never
    easylist: 65087-164, 13h.31m
    easyprivacy: 30917-12404, 13h.31m
    ublock-abuse: 77-1, 13h.31m
    ublock-badware: 4041-108, 13h.31m
    ublock-filters: 31569-649, 13h.31m
    ublock-privacy: 260-49, 13h.30m
    ublock-quick-fixes: 423-27, 13h.30m
    ublock-unbreak: 1909-64, 13h.30m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1227 ms (selfie)
  maxAssetCacheWait: 907 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    notebookcheck.net: 3
    amazon-adsystem.com: 1
    btloader.com: 1
    google-analytics.com: 2
    googlesyndication.com: 5
    googletagmanager.com: 1
    snigelweb.com: 1
    youtube-nocookie.com: 13
```
</details>

**Comment by mapx-** [comment]
AG issue

add

`notebookcheck.*#@#+js(abort-current-script, document.getElementById, /!document\.getElementById[\s\S]*?innerHTML[\s\S]*?insertBefore/)`
