### ISSUE TITLE
buszhalo.hu: breakage

### ISSUE THREAD

**Issue by Gorcher** [uBlockOrigin/uAssets#15880]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://buszhalo.hu/terkep_idovonal.html`

### Category

breakage

### Describe the issue

Dear uBlock! First, thanks for your work, it's really make the internet a better place. 
My issue is, that I have a small, hungarian website with 6 embedded webmaps. They are from the arcgis online and can't see in the containers of the website, when the ublock is on. I thought it's because the maps is on a third party website, but then I figured that the webmap, or specifically the application created from the webmaps are also blocked on the arcgis website, when I tried to open and edit them.
Can you do something whit that problem? ArcGIS Online is one of the world's biggest GIS companies website, and it's worked fine until last week or so. 
Thank you, if you read this! And I'm hoping in a solution. And sorry for my rusty english writing skills, but I'm not using it too many times.
Best regards, 
Gorcher

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90185
  cosmetic: 40378
  scriptlet: 16778
  html: 880
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32307-40, 1d.16h.2m
    ublock-badware: 4050-1, 1d.16h.1m
    ublock-privacy: 307-0, 1d.16h
    ublock-abuse: 77-0, 1d.15h.59m
    ublock-unbreak: 1924-33, 1d.15h.58m
    ublock-quick-fixes: 434-31, 15h.53m
    easylist: 64996-625, 1d.15h.56m
    easyprivacy: 30908-1148, 1d.15h.55m
    urlhaus-1: 9935-0, 15h.52m
    plowe-0: 3678-537, 1d.15h.53m
    HUN-0: 2201-17, 15h.51m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6249 ms (selfie)
  maxAssetCacheWait: 2586 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    arcgis.com: 1
```
</details>

**Comment by mapx-** [comment]
update unbreak list in 5-10 minutes, then test again

**Comment by Gorcher** [comment]
Thank you, it's working now!
