### ISSUE TITLE
techtnet.com: detection

### ISSUE THREAD

**Issue by ohn0n0n0** [uBlockOrigin/uAssets#15881]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techtnet.com/news/laptops/apple-solves-macbook-pro-2022-throttling-issues-with-the-software-patch-80?goal=2553503`

### Category

detection

### Describe the issue

Browser redirect from `https://techtnet.com/reviews/phones/iphone-x-review-78?goal=2553503`
To `https://techtnet.com/reviews/phones/iphone-x-review-78`.

Then "Please disable your ad blocker and refresh page." show up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/6015976/205258111-fb11f8e2-fbc3-4247-a3ee-15c21f63b594.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 90594
  cosmetic: 39687
  scriptlet: 16826
  html: 0
listset (total-discarded, last-updated): 
  added: 
    VIE-1: 2007-0, 1d.3h.8m
  default: 
    user-filters: 0-0, never
    easylist: 64862-74, 5d.5h.43m
    easyprivacy: 30897-1176, 4d.2h.55m
    plowe-0: 3669-870, 10d.4h.58m
    ublock-abuse: 76-0, 12d.17h.49m
    ublock-badware: 4046-110, 1d.3h.13m
    ublock-filters: 31568-136, 1d.3h.12m
    ublock-privacy: 258-1, 12d.17h.48m
    ublock-quick-fixes: 392-25, 1d.3h.10m
    ublock-unbreak: 1909-44, 1d.3h.11m
    urlhaus-1: 10022-0, 1d.3h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 166 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> blocked: 0

it's something wrong in your setup:

- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by ohn0n0n0** [comment]
> > blocked: 0
> 
> it's something wrong in your setup:
> 
> * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> * restart the system, reopen the browser, test again.

I do everything in list one by one, but the site still detects uBO.

**Comment by mapx-** [comment]
Which is the original page you visited ? if some link shortener post it here

**Comment by ohn0n0n0** [comment]
> Which is the original page you visited ? if some link shortener post it here

The original page:
[v](https://linkneverdie.net/software/minitool-partition-wizard-2331)

![image](https://user-images.githubusercontent.com/6015976/205287711-7d4ca1fa-02da-48e9-a251-48a0994e0479.png)
link shortener:
https://linkneverdie.net/Download/648f8c1b-24de-4309-8c75-460676e0a441
