### ISSUE TITLE
blog.jp issues

### ISSUE THREAD

**Issue by pikesaury** [uBlockOrigin/uAssets#15887]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ryokonyans.blog.jp/`

### Describe the issue

Is it possible to hide the warning that appears below the livedoor blog in uBlock Origin Lite?

### Screenshot(s)

![スクリーンショット 2022-12-03 073825](https://user-images.githubusercontent.com/37852075/205402252-da615f64-8e37-4fb0-bcb9-0764736658e8.png)

### uBlock Origin version

uBlock Origin Lite 0.1.22.11296

### Browser name and version

chrome 108.0.5359.72

### Settings

Default values are used

**Comment by Yuki2718** [comment]
Enable either AdGuard Annoyances or EasyList Cookie list.
