### ISSUE TITLE
etsy.com: breakage

### ISSUE THREAD

**Issue by hlqviet** [uBlockOrigin/uAssets#15885]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.etsy.com/c/electronics-and-accessories`
`https://www.etsy.com/c/art-and-collectibles`
and other category pages

### Describe the issue

The results disappear when `uBlock filters` is enabled

### Screenshot(s)

![image](https://user-images.githubusercontent.com/5486625/205374153-721c10e3-ef1a-4ac8-9dac-8f5ad70c82e9.png)

![image](https://user-images.githubusercontent.com/5486625/205374204-d6eb87bd-5a79-4b0b-8f9f-f259f61ea8e5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 101059
  cosmetic: 143632
  scriptlet: 35655
  html: 887
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2044-1, 6h.17m
    adguard-generic: 66068-4748, 1d.6h.44m
    adguard-annoyance: 61558-692, 1d.6h.43m
    ublock-annoyances: 4821-4, 1d.6h.42m
    CHN-0: 28929-101, 1d.6h.41m
    JPN-1: 8350-8, 1d.6h.40m
    VIE-1: 1964-0, 6h.15m
  default: 
    user-filters: 2-0, never
    ublock-filters: 32396-94, now
    ublock-badware: 4045-1, 1d.6h.46m
    ublock-privacy: 305-2, 12d.23h.30m
    ublock-abuse: 76-0, 12d.23h.29m
    ublock-unbreak: 1924-2, 1d.6h.45m
    ublock-quick-fixes: 389-0, 6h.14m
    easylist: 64862-325, 5d.13h.14m
    urlhaus-1: 9586-0, 6h.16m
filterset (user): [array of 2 redacted]
hostRuleset: 
  added: [array of 45 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 465 ms (selfie)
  maxAssetCacheWait: 885 ms
```
</details>

**Comment by krystian3w** [comment]
@kiboke your list break page - locked scroll...

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by stephenhawk8054** [comment]
Are you signing in to the page?

**Comment by hlqviet** [comment]
Weird. It doesn't happen anymore after I sign out and sign in again. It also doesn't happen with a new private window or another browser.

Previously, this filter hit and caused the issue:
`etsy.com##[data-behat-search-results-lg] > ul > li a.listing-link:not([data-nonce]):upward(li)`

I think the issue can be closed now.
