### ISSUE TITLE
rockpapershotgun.com: nuisance

### ISSUE THREAD

**Issue by Cubsfanryan** [uBlockOrigin/uAssets#15897]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.rockpapershotgun.com/warzone-2-best-guns`

### Category

nuisance

### Describe the issue

There is a cookie popup. I have tried the above things in the checkboxes as well as an incognito browser with no other extensions allowed except uBlock and still had the issue. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cookie](https://user-images.githubusercontent.com/47905983/205464663-ee6c8532-bfa7-4a6e-aa1e-280e095df453.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91158
  cosmetic: 78688
  scriptlet: 18592
  html: 863
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43709-176, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32412-62, 1m
    ublock-badware: 4140-1, 1m
    ublock-privacy: 308-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1924-2, 1m
    ublock-quick-fixes: 396-0, 1m
    easylist: 65202-630, 1m
    easyprivacy: 30936-1739, 1m
    urlhaus-1: 9299-0, 1m
    plowe-0: 3675-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1681 ms
  maxAssetCacheWait: 260 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    amazon-adsystem.com: 1
    bluebillywig.com: 4
    doubleclick.net: 1
    googletagmanager.com: 1
    onetrust.com: 1
    permutive.app: 1
    piwik.pro: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
- the existent filter in the annoyances lists (AG, fanboy's) was whitelisted because some page could be broken

add
`rockpapershotgun.com###onetrust-consent-sdk`

for example in this page "cookies settings" is broken
`https://www.rockpapershotgun.com/mystery-steam-reviews-spiritual-successors`
