### ISSUE TITLE
[nsfw] [voe.sx] Detecting uBlock Origin and preventing playback until it is disabled

### ISSUE THREAD

**Issue by Yami-x3** [uBlockOrigin/uAssets#15894]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://20demidistance9elongations.com`

### Describe the issue

`voe.sx` is blocking the anti-adblock message with a new domain.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/103429699/205441649-5b0695e9-16e4-46ee-8af4-3160bfcdf382.png)

### uBlock Origin version

uBlock Origin 1.45.2

### Browser name and version

LVL 4 (core: 92.0.4561.71)

### Settings

- no changes (only cleared cache and updated)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/864985065ac5b9eb7b713843812cf78f9ec975f5
