### ISSUE TITLE
n-tv.de: ads

### ISSUE THREAD

**Issue by siddy81** [uBlockOrigin/uAssets#15895]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.n-tv.de/`

### Category

ads are not blocked 

### Describe the issue

ads are not blocked 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 91701
  cosmetic: 42369
  scriptlet: 16746
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    DEU-0: 6051-0, 21h.36m
    easylist: 64993-58, 4d.29m
    easyprivacy: 30904-1181, 4d.28m
    plowe-0: 3679-872, 2d.29m
    ublock-abuse: 77-0, 5d.23h.46m
    ublock-badware: 4040-110, 3d.20h.25m
    ublock-filters: 31525-140, 3d.20h.27m
    ublock-privacy: 260-1, 5d.23h.47m
    ublock-quick-fixes: 387-25, 21h.33m
    ublock-unbreak: 1910-47, 3d.20h.26m
    urlhaus-1: 9586-0, 21h.35m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 513 ms (selfie)
  maxAssetCacheWait: 264 ms
popupPanel: 
  blocked: 68
  blockedDetails: 
    n-tv.de: 4
    2mdn.net: 1
    admob.com: 5
    adnxs.com: 2
    chartbeat.com: 2
    criteo.net: 2
    doubleclick.net: 18
    emetriq.de: 1
    google-analytics.com: 1
    google.com: 3
    google.de: 2
    googlesyndication.com: 8
    googletagservices.com: 12
    imrworldwide.com: 1
    indexww.com: 1
    ioam.de: 2
    kameleoon.eu: 1
    outbrain.com: 1
    unpkg.com: 1
```
</details>

**Comment by mapx-** [comment]
> ads are not blocked

normal ads ? video-ads ?

If first ones provide a screenshot showing them and on which specific page did you get them
