### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by hgunduz295** [uBlockOrigin/uAssets#15890]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/mervehatun`

### Category

ads

### Describe the issue

Shows 30 second ads ı dont use any other adblock etc 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/36344949/205432895-33bd63cd-2b5a-4b56-8354-10a4e6ef505b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 106
filterset (summary): 
  network: 185501
  cosmetic: 113999
  scriptlet: 32644
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ALB-0: 301-10, now
    CHN-0: 28339-1285, now
    DEU-0: 6051-383, now
    FRA-0: 30394-3200, now
    JPN-1: 8363-83, now
    RUS-0: 39592-1032, now
    adguard-generic: 66033-1349, now
    adguard-mobile: 8285-124, now
    adguard-spyware: 33829-4113, now
    adguard-spyware-url: 852-1, now
    block-lan: 44-0, now
  default: 
    user-filters: 0-0, never
    TUR-0: 11716-193, 12h.46m
    easylist: 64921-18093, 4d.14h.43m
    easyprivacy: 30897-12842, 4d.14h.42m
    plowe-0: 3677-1075, 4d.14h.41m
    ublock-abuse: 77-2, 4d.14h.39m
    ublock-badware: 4045-274, 12h.45m
    ublock-filters: 31568-3673, 12h.44m
    ublock-privacy: 260-46, 4d.14h.35m
    ublock-quick-fixes: 385-46, 2m
    ublock-unbreak: 1910-107, 12h.43m
    urlhaus-1: 9327-0, 2m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 649 ms (selfie)
  maxAssetCacheWait: 953 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 1
    moatads.com: 4
    scorecardresearch.com: 25
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
