### ISSUE TITLE
[nsfw] serialy.bombuj.si & bombuj.si: popups

### ISSUE THREAD

**Issue by Beji-kun** [uBlockOrigin/uAssets#15898]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://serialy.bombuj.si/serial/willow-2022-1x1`

 `https://www.bombuj.si/`

### Category

popups

### Describe the issue

Site `https://www.bombuj.si/` and `https://serialy.bombuj.si/` open pop up even when it adblocker active.
Device: Windows 11/Edge ver.107.0.1418.62

**Scenario**

1. Open  `https://www.bombuj.si/` or `https://serialy.bombuj.si/` --> 
2. Open serial or film --> 
3. Click on red cross with text label "Zatvarit reklamu" --> 

**Actual result**

4. open new window of link even pop up is enabled and even after click on play open pop-up ads (both video record issue attached)

**Except result**

4. Not open new windows only closed and can only play video

**Video of issue attached**

### Screenshot(s)

https://user-images.githubusercontent.com/63636174/205469169-7d2b6c07-48ff-488b-a7ce-56ad599e3aa1.mp4

https://user-images.githubusercontent.com/63636174/205469172-90b0bd91-4209-4b9e-b196-dd9f3453e2e0.mp4

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 88426
  cosmetic: 38317
  scriptlet: 16587
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62416-627, never
    easyprivacy: 30822-1176, never
    plowe-0: 3671-534, never
    ublock-abuse: 76-0, never
    ublock-badware: 3943-0, never
    ublock-filters: 31097-49, never
    ublock-privacy: 260-0, never
    ublock-quick-fixes: 424-0, never
    ublock-unbreak: 1873-0, never
    urlhaus-1: 11291-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1254 ms
  maxAssetCacheWait: 7 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    commentsengine.com: 1
    sentry.io: 2
    testingmetriksbre.ru: 1
    toplist.sk: 1
    windsattributeron.com: 2
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by Beji-kun** [comment]
Ho do it this ? Can you give me little hint tutor :D ? Thanks

**Comment by mapx-** [comment]
Update all your filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
