### ISSUE TITLE
aura.ge: ads

### ISSUE THREAD

**Issue by avetisovi** [uBlockOrigin/uAssets#15896]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.aura.ge/103-saskolo/11189-davit-guramishvili--davitiani-poema-tavebis-mixedvit.html`

### Category

ads

### Describe the issue

Ads are showing on the both sides of the content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91026
  cosmetic: 78518
  scriptlet: 18573
  html: 863
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43649-157, 3d.1h.11m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32396-70, 13m
    ublock-badware: 4140-1, 12m
    ublock-privacy: 307-0, 3d.1h.13m
    ublock-abuse: 77-0, 3d.1h.12m
    ublock-unbreak: 1923-2, 11m
    ublock-quick-fixes: 402-0, 10m
    easylist: 64957-645, 5d.49m
    easyprivacy: 30904-1710, 5d.48m
    urlhaus-1: 9299-0, 9m
    plowe-0: 3677-3, 5d.50m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 833 ms (selfie)
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    a-ads.com: 4
    adform.net: 12
    consensu.org: 1
    dimlyconfidential.com: 1
    eskimi.com: 1
    facebook.net: 1
    google-analytics.com: 1
    sharethis.com: 1
    top.ge: 2
```
</details>

**Comment by mapx-** [comment]
add

```
aura.ge##[href="https://talizi.ge/ka/"]
aura.ge##[href="https://trinx.ge/"]
```

**Comment by DandelionSprout** [comment]
AdGuard Base Filter probably has a section for Georgian sites.
