### ISSUE TITLE
bleepingcomputer.com/forums/: ad leftovers

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15899]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bleepingcomputer.com/forums/t/124024/a-reminder-to-our-members-regarding-malware-logs/`

### Describe the issue

"BC AdBot" user leaves blank messages when viewing forums

### Screenshot(s)

<details><summary>Screenshot</summary>

![screenshot](https://user-images.githubusercontent.com/54487525/205474870-800b0676-00aa-4570-bbfc-ef4d1b61f52d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 89067
  cosmetic: 38690
  scriptlet: 16772
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32412-62, now
    ublock-badware: 4140-1, now
    ublock-privacy: 308-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1924-2, now
    ublock-quick-fixes: 399-0, now
    easylist: 65205-630, now
    easyprivacy: 30936-1739, now
    urlhaus-1: 8917-0, now
    plowe-0: 3675-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3313 ms
  maxAssetCacheWait: 196 ms
```
</details>

**Comment by mapx-** [comment]
add

`bleepingcomputer.com##.post_wrap:has-text(AdBot)`

@ryanbr
