### ISSUE TITLE
content not showing/hiding

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#159]
Replace the bracketed [...] placeholders with your own information.
@gorhill 
### URL(s) where the issue occurs

`www.loksatta.com`
### Describe the issue
1.go to above site with and without ublock origin

2.with ublock on , site hides content displaying only one story and rest stories below it are hides
3. Also antiadblocker warning on clicking story 
`http://www.loksatta.com/desh-videsh-news/surgical-strikes-i-will-only-share-credit-major-share-goes-to-pm-modi-says-manohar-parrikar-1316998/ `
### Screenshot(s
Content not showing below 1 story with ublock on
![screenshot_2016-10-12-16-38-54](https://cloud.githubusercontent.com/assets/20338483/19307932/bbdbfa8c-909a-11e6-825c-bb1f119d4655.png)

![screenshot_2016-10-12-16-40-13](https://cloud.githubusercontent.com/assets/20338483/19307957/cfd6ebf0-909a-11e6-83e2-a6f3c7e30093.png)
![screenshot_2016-10-12-16-40-21](https://cloud.githubusercontent.com/assets/20338483/19307968/d9e8f296-909a-11e6-8c08-86684cf5b0d7.png)
![screenshot_2016-10-12-16-40-35](https://cloud.githubusercontent.com/assets/20338483/19307975/e777ec46-909a-11e6-9713-64f4c23972d0.png)

### Versions

- Browser/version: firefox for Android 49
- uBlock Origin version: 1.9.12

### Settings

- default settings

### Notes
Anti Adblocker warning
![screenshot_2016-10-12-16-43-52](https://cloud.githubusercontent.com/assets/20338483/19308033/3420e624-909b-11e6-909b-da5111e01316.png)

Without Adblocker all contents/stories are shown of website
![screenshot_2016-10-12-16-46-33](https://cloud.githubusercontent.com/assets/20338483/19308124/a47f87e0-909b-11e6-80ec-325e2517e8d7.png)

**Comment by IDKwhattoputhere** [comment]
Try `@@||expressbpd.com/rsjs/ads.js$script,domain=loksatta.com`
