### ISSUE TITLE
voirseries.pro: ads

### ISSUE THREAD

**Issue by j7j2** [uBlockOrigin/uAssets#15907]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://opynew.com/us-bear-market-deepening-what-it-means-for-you/?rdk=rk4`

### Category

ads

### Describe the issue

Watching Star trek at this address:
`https://wwvv.voirseries.pro/voir-series/science_fiction_s/1573-star-trek-la-nouvelle-generation-CyPqx/1-season/15-episode.html`

Isn't there a way that every blocked click doesnt just get block rather than opening a "uBlock Origin has prevented the following page from loading:"?? that's very annoying as often frame clickable ads gets back within seconds and i'm stuck closing dozen of those uBlock tabs...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 108715
  cosmetic: 47456
  scriptlet: 16753
  html: 863
listset (total-discarded, last-updated): 
  added: 
    FRA-0: 30398-116, now
  default: 
    user-filters: 2-0, never
    ublock-filters: 32262-170, now
    ublock-badware: 4140-1, now
    ublock-privacy: 308-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1925-2, now
    easylist: 65326-715, now
    easyprivacy: 30936-2081, now
    plowe-0: 3675-3, now
    ublock-quick-fixes: 401-0, now
    urlhaus-1: 8153-0, now
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 353 ms (selfie)
  maxAssetCacheWait: 394 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    opynew.com: 1
    demand.supply: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
What server are you using to watch the movie ?

- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by j7j2** [comment]
isn't there a global setting for disabling the " Don't warn me again about this site " without adding a special flag for any website?

**Comment by ghajini** [comment]
follow https://github.com/uBlockOrigin/uAssets/issues/15907#issuecomment-1336798386

you are probably infected with adware, scan your system with antimalware software like malwarebytes or builtin antivirus
UBO is doing its job by preventing those popups

**Comment by mapx-** [comment]
- reset uBO => https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section
- **don't modify any uBO setting**
- update all the filter lists => (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- regional list => you disabled the french list. Keep it (**don't modify any uBO setting**)

If you have a windows system you should have at least the windows antivirus enabled (that antivirus is good enough if you have at least windows 10)
