### ISSUE TITLE
frag-machiavelli.de: breakage

### ISSUE THREAD

**Issue by hrrd** [uBlockOrigin/uAssets#15906]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.frag-machiavelli.de/`

### Category

breakage

### Describe the issue

The consent manager is blocked and the website doesn't allow or can't handle without choosing your cookies, to enter the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 206270
  cosmetic: 131869
  scriptlet: 35406
  html: 887
listset (total-discarded, last-updated): 
  removed: 
    DEU-0: null
  added: 
    adguard-generic: 66031-4867, 2d.1h
    adguard-mobile: 8285-147, 2d.1h.3m
    adguard-annoyance: 61647-760, 2d.1h.2m
    ublock-annoyances: 4822-4, 2d.1h.4m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32412-83, 9h.35m
    ublock-badware: 4140-1, 9h.34m
    ublock-privacy: 307-0, 4d.8h.11m
    ublock-abuse: 77-0, 4d.8h.10m
    ublock-unbreak: 1924-3, 9h.33m
    ublock-quick-fixes: 398-0, 6h.12m
    easylist: 65079-775, 3d.45m
    adguard-spyware-url: 853-3, 9h.36m
    easyprivacy: 30913-1719, 3d.23h.9m
    urlhaus-1: 8604-0, 6h.11m
    curben-phishing: 91929-5, 1d.53m
    plowe-0: 3669-3, 11d.23h.42m
    LegitimateURLShortener: 2045-124, 6h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 250 ms (selfie)
  maxAssetCacheWait: 134 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

```
frag-machiavelli.de##body:style(overflow: auto !important;)
frag-machiavelli.de##.cli-modal-backdrop
```
