### ISSUE TITLE
cmsc777.gnomio.com: detection

### ISSUE THREAD

**Issue by joshagustin** [uBlockOrigin/uAssets#15909]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cmsc777.gnomio.com/`

### Category

detection

### Describe the issue

A pop-up requesting that the user turn off adblocking for the site shows up on each page click. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Pop-up that appears on each page visit.

https://user-images.githubusercontent.com/87127274/205546611-c7c6eef8-c380-4eee-b66a-a56711731fde.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88940
  cosmetic: 38665
  scriptlet: 16772
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32412-61, 1d.1m
    ublock-badware: 4049-1, 1d
    ublock-privacy: 305-0, 12d.23h.11m
    ublock-abuse: 77-0, 12d.23h.10m
    ublock-unbreak: 1924-2, 23h.59m
    ublock-quick-fixes: 399-0, 23h.57m
    easylist: 65152-628, 1d.3m
    easyprivacy: 30935-1740, 1d.2m
    urlhaus-1: 8917-0, 23h.58m
    plowe-0: 3669-3, 12d.15h.55m
filterset (user): [empty]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 182 ms (selfie)
  maxAssetCacheWait: 106 ms
  unsuspendAfter: 55 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    doubleclick.net: 1
    googlesyndication.com: 1
```
</details>

**Comment by ghajini** [comment]
did this help you
`gnomio.com##+js(no-xhr-if, /doubleclick|googlesyndication/)`

**Comment by joshagustin** [comment]
@ghajini It did, thanks!
