### ISSUE TITLE
movoto.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1590]
### URL(s) where the issue occurs

`https://www.movoto.com/blog/novelty-real-estate/patriotic-states-map/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/36458445-dc79a10e-167c-11e8-9f4e-5e5c9a37390d.png)

**Comment by okiehsch** [comment]
What filter lists do you have enabled, you should alway mention lists that are not part of the default setup, saves me the time to "guess" whatever causes the issue on your end.
I can't reproduce with a default setup and looking at the source something blocks some facebook "stuff" at your end.

**Comment by terrorist96** [comment]
Only have the default lists. But since I clicked the X button the first time, I can't get it to show up again so I can test further.

**Comment by okiehsch** [comment]
If I delete cookies, I can reproduce the issue every time, **but** only if I enable
`Fanboy’s Annoyance List`.

![unbenannt](https://user-images.githubusercontent.com/16838044/36460005-befddf16-16b6-11e8-81b2-a3c9f68ede95.JPG)

**Comment by terrorist96** [comment]
Hmm, I don't have that list active though.

**Comment by okiehsch** [comment]
Is something blocking facebook requests if you look at your logger?

Here is my filtered logger output

![unbenannt](https://user-images.githubusercontent.com/16838044/36460180-92f7a892-16b7-11e8-9bfd-0acccf58316f.PNG)


If I allow the `https://apps.facebook.com/favicon.ico` request the issue is fixed.

**Comment by terrorist96** [comment]
No. May have just been a fluke where the site had trouble loading it.

**Comment by okiehsch** [comment]
That is possible, thanks for the feedback.

**Comment by terrorist96** [comment]
No problem. Thanks for investigating. :)
