### ISSUE TITLE
itdog.cn: nuisance

### ISSUE THREAD

**Issue by letuplus** [uBlockOrigin/uAssets#15900]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.itdog.cn/ping/baidu.com`

### Category

nuisance

### Describe the issue

Page results are incorrectly masked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 106895
  cosmetic: 48859
  scriptlet: 16899
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28349-97, 5h.45m
    easylist: 65152-88, 5h.42m
    easyprivacy: 30935-1194, 5h.38m
    plowe-0: 3675-902, 5h.37m
    ublock-abuse: 77-0, 5h.13m
    ublock-badware: 4136-110, 5h.7m
    ublock-filters: 31619-151, 5h.6m
    ublock-privacy: 261-1, 5h.5m
    ublock-quick-fixes: 389-18, 5h.4m
    ublock-unbreak: 1911-45, 4h.57m
    urlhaus-1: 8917-0, 4h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 160 ms (selfie)
  maxAssetCacheWait: 96 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    baidu.com: 2
```
</details>

**Comment by mapx-** [comment]
> Page results are incorrectly masked

give us more details, screenshot with the missing items

**Comment by letuplus** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uBlockOrigin/uAssets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月4日(星期天) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uBlockOrigin/uAssets] itdog.cn: nuisance (Issue #15900)





  
Page results are incorrectly masked
  
give us more details, screenshot with the missing items

**Comment by mapx-** [comment]
I asked you a screenshot / more details.

If you are not able to provide such info report directly here:
https://github.com/cjx82630/cjxlist/issues

@cjx82630
