### ISSUE TITLE
WND.COM Pop-ups NO LONGER BLOCKED

### ISSUE THREAD

**Issue by DAMoran2022** [uBlockOrigin/uAssets#15904]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

No longer functions on WND.COM.

### A specific URL where the issue occurs.

wnd.com

### Steps to Reproduce

Just go to the site

### Expected behavior

Previously UBO blocked ALL pop-ups on this web site.

### Actual behavior

Now it does not.

### Configuration

Win 7E x64, latest security updates, Waterfox G5.1

**Comment by mapx-** [comment]
Are you talking about cookies "pop-up" ?
