### ISSUE TITLE
Block history etc youtube

### ISSUE THREAD

**Issue by nrafaelos** [uBlockOrigin/uAssets#15903]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

nuisance

### Describe the issue

block history library etc in left panel youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Captură](https://user-images.githubusercontent.com/40106539/205498918-fba7ac59-affa-42d3-aef0-69ad3e4a1d4e.JPG)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 130070
  cosmetic: 123846
  scriptlet: 24278
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://fanboy.co.nz/fanboy-cookiemonster.txt: 43649-104, 4d.19m
    https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt: 651-0, 19h.20m
    https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt: 755-0, 19h.20m
    https://www.zoso.ro/pages/rolist.txt: 390-1, 22m
    https://www.zoso.ro/pages/rolist2.txt: 542-7, 2d.1h.40m
    CHN-0: 28308-96, 2d.19h.41m
    KOR-1: 3934-6, 23h.19m
    RUS-0: 39587-31, 17m
    TUR-0: 11530-17, 3d.19h.22m
    ublock-annoyances: 4798-53, 19h.20m
  default: 
    user-filters: 27-0, never
    ROU-1: 1155-47, 2d.1h.41m
    easylist: 65026-369, 3d.23h.52m
    easyprivacy: 30908-1394, 3d.23h.51m
    plowe-0: 3669-910, 11d.3h.20m
    ublock-abuse: 77-1, 10d.21h.19m
    ublock-badware: 4045-110, 2d.19h.39m
    ublock-filters: 31589-205, 2d.19h.38m
    ublock-privacy: 258-3, 10d.21h.20m
    ublock-quick-fixes: 379-18, 23h.17m
    ublock-unbreak: 1910-46, 2d.19h.37m
    urlhaus-1: 8604-0, 17m
filterset (user): [array of 27 redacted]
trustedset: 
  added: [array of 466 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 346 ms (selfie)
  maxAssetCacheWait: 243 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    youtube.com: 20
    doubleclick.net: 4
    google.com: 6
    google.ro: 1
    ytimg.com: 1
```
</details>

**Comment by Yuki2718** [comment]
Not something to be done in public list and IDK what exactly is `history library etc` means. You can hide only history and libraray, or whole left panel.

**Comment by krystian3w** [comment]
Don't offer hide bookmark "watched" in avanced settings.

I think he need network filter to avoid changed this in Google account settings.
