### ISSUE TITLE
replit.com: breakage

### ISSUE THREAD

**Issue by hankertrix** [uBlockOrigin/uAssets#15915]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://replit.com/~`

### Category

breakage

### Describe the issue

The main issue is that the cosmetic filtering blocks a lot of the site's functionality. I'm using Firefox version 107.0.1 (64-bit) on a Windows 10 machine. However, when testing the website on Google Chrome version 108.0.5359.95 (Official Build) (64-bit) with uBlock Origin installed, the site works perfectly so I think this is Firefox-specific. The screenshots labelled "Expected" are the screenshots from Google Chrome and the screenshots labelled "Actual" are the ones from Firefox.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

# Homepage

Expected:
![image](https://user-images.githubusercontent.com/91734413/205674924-566f480e-525f-4392-a140-bb4f3255653f.png)

Actual:
![image](https://user-images.githubusercontent.com/91734413/205675338-7e1f6ffd-80bb-425d-bf38-f1e36635c8dd.png)

<hr>

Expected:
![image](https://user-images.githubusercontent.com/91734413/205675971-ec287519-f9a5-400b-ac20-510758729baf.png)

Actual:
![image](https://user-images.githubusercontent.com/91734413/205675853-db955979-10ab-43ba-a0d0-8bf5f6f39dc7.png)

<hr>

# Code Editor

Expected:
![image](https://user-images.githubusercontent.com/91734413/205676495-b32569f2-7fc8-4b43-8cf0-cf3f1b139a1b.png)

Actual:
![image](https://user-images.githubusercontent.com/91734413/205676292-bad06672-7a81-493e-a1d5-065f832f6f3f.png)

<hr>

Expected:
![image](https://user-images.githubusercontent.com/91734413/205676669-17f1cccb-7d87-4a2e-8020-12cb76cb0b42.png)

Actual:
![image](https://user-images.githubusercontent.com/91734413/205676746-e9e90f5d-543a-4db2-9f45-56395319c43e.png)

<hr>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 87633
  cosmetic: 38539
  scriptlet: 16752
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32325-150, 4d.43m
    ublock-badware: 4050-1, 4d.42m
    ublock-privacy: 307-0, 8d.1h.52m
    ublock-abuse: 77-0, 8d.1h.51m
    ublock-unbreak: 1922-1, 4d.41m
    ublock-quick-fixes: 398-1, 1h.40m
    easylist: 64848-173, 2d.1h.3m
    easyprivacy: 30936-1755, 2d.1h.4m
    urlhaus-1: 7849-0, 1h.39m
    plowe-0: 3667-347, 8d.1h.55m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12708 ms (selfie)
  maxAssetCacheWait: 2874 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    browser-intake-datadoghq.com: 2
    segment.io: 1
    sentry.io: 3
```
</details>

**Comment by mapx-** [comment]
I'm able to see correctly "following", I don't know how to test "code editor", "report a bug".

However:
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
