### ISSUE TITLE
[nsfw] javchill.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#15917]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://javchill.com/englishSub/LATEST/1`

### Category

ads

### Describe the issue

pop up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/98657967/205691898-df81a1f1-b67c-4e69-a75f-c97bfcf1c908.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 109
filterset (summary): 
  network: 87242
  cosmetic: 118127
  scriptlet: 22776
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7703-2, 3h.39m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 3h.38m
    fanboy-annoyance: 83524-310, 3h.41m
    fanboy-cookiemonster: 43708-43708, 3h.42m
    ublock-annoyances: 4796-75, 3h.40m
  default: 
    user-filters: 8-0, never
    easylist: 65202-57, 1d.7h.21m
    easyprivacy: 30936-1171, 1d.7h.19m
    ublock-abuse: 77-0, 9d.10h.52m
    ublock-badware: 4136-108, 3h.37m
    ublock-filters: 31476-434, 3h.36m
    ublock-privacy: 258-8, 9d.10h.52m
    ublock-quick-fixes: 387-25, 3h.34m
    ublock-unbreak: 1911-48, 3h.35m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2551 ms (selfie)
  maxAssetCacheWait: 1204 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
maybe
`javchill.com##+js(ra, href, [onclick^="pop"])`

the video will be opened in a new tab but the first one will be not replaced by ads
(and your filter has to be removed otherwise in this combination will close legit tabs)

**Comment by okiehsch** [comment]
Hm, not sure what is preferable, your filter manipulates the cursor too, there is no indication that it has become clickable after hovering over a link anymore.

**Comment by mapx-** [comment]
yes, there is no cursor but when you see the cursor it's the 2outstandingspread" crap link visible

**Comment by okiehsch** [comment]
Ok, let's use your filter.
I will change it.

**Comment by mapx-** [comment]
to have the cursor add:

`javchill.com##.thumb:style(cursor:pointer !important)`

**Comment by mapx-** [comment]
No issue in android on my end
