### ISSUE TITLE
soltoshindo.com: detection

### ISSUE THREAD

**Issue by hunterkais** [uBlockOrigin/uAssets#15911]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soltoshindo.com/member/dashboard`

### Category

detection

### Describe the issue

Detection after login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 109
filterset (summary): 
  network: 89963
  cosmetic: 27939
  scriptlet: 16725
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32373-288, 38m
    ublock-badware: 4139-1, 38m
    ublock-privacy: 308-1, 38m
    ublock-abuse: 77-0, 38m
    ublock-unbreak: 1930-2, 38m
    ublock-quick-fixes: 401-0, 38m
    adguard-mobile: 8288-166, 38m
    easylist: 65391-17818, 38m
    easyprivacy: 30941-1749, 38m
    urlhaus-1: 8153-0, 38m
    plowe-0: 3675-3, 38m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1110 ms (selfie)
  maxAssetCacheWait: 556 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    a-ads.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
soltoshindo.com##+js(aopr, Swal.fire)
soltoshindo.com##+js(aopr, console.clear)
```

**Comment by mapx-** [comment]
don't open in the future new issues, just use this 1 for the same page (soltoshindo), we are notified for all comments

**Comment by hunterkais** [comment]
> don't open in the future new issues, just use this 1 for the same page (soltoshindo), we are notified for all comments

Ok, sorry. Thanks

**Comment by mapx-** [comment]
When do you interact with HCAPTCHA ? provide steps

**Comment by hunterkais** [comment]
![az_recorder_20221205_161425](https://user-images.githubusercontent.com/114012899/205599258-20f97b7c-5820-4678-ba93-b5c0a64fed39.jpg)
In this claim page, this link 
https://soltoshindo.com/member/claim2

**Comment by hunterkais** [comment]
even when logging in, it's not there, it's hidden.
![Uploading az_recorder_20221205_161659~2.jpg…]()

**Comment by mapx-** [comment]
test adding

```
soltoshindo.com#@#+js(aopr, console.clear)
soltoshindo.com##+js(set, console.clear, noopFunc)
```
