### ISSUE TITLE
file-upload.net: breakage

### ISSUE THREAD

**Issue by jufcar** [uBlockOrigin/uAssets#15914]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.file-upload.net/`
`https://www.file-upload.net/download-15053329/LS22_Anthem_6x4_ModellEdit.zip.html` (in case you need a working downloadable file)

### Category

breakage

### Describe the issue

Site is a one-click hoster, used in my case for game mods.
I tried it with uBO active and inactive, if uBO is active, the site prevents me from seeing/activating the download button. If uBO is inactive, i can use the sites purpose but get multiple adds aswell.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 103232
  cosmetic: 185007
  scriptlet: 24493
  html: 887
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4822-4, 2d.15h.45m
    adguard-annoyance: 61647-5143, 2d.15h.44m
    adguard-social: 19367-1066, 2d.15h.43m
    fanboy-thirdparty_social: 68-0, 3d.23h.58m
    fanboy-annoyance: 83453-67283, 3d.23h.59m
    fanboy-cookiemonster: 43645-191, 4d
    fanboy-social: 23452-28, 3d.23h.57m
  default: 
    user-filters: 17-2, never
    ublock-filters: 32356-92, 2d.15h.41m
    ublock-badware: 4140-1, 1d.4h.24m
    ublock-privacy: 308-0, 2h.23m
    ublock-abuse: 77-0, 2h.24m
    ublock-unbreak: 1923-1, 2d.15h.42m
    easylist: 65072-654, 4d.13h.28m
    easyprivacy: 30911-1726, 4d.13h.27m
    plowe-0: 3669-3, 10d.4h.2m
    DEU-0: 6051-2, 15h.8m
    urlhaus-1: 8604-0, 15h.7m
    ublock-quick-fixes: 400-1, 15h.9m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 680 ms (selfie)
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    file-upload.net: 4
    googlesyndication.com: 1
    trustedcpmrevenue.com: 4
```
</details>

**Comment by pokorocks** [comment]
It's detecting ublock again
