### ISSUE TITLE
bluemediafile.sbs: detection

### ISSUE THREAD

**Issue by samboa86** [uBlockOrigin/uAssets#15919]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=cj94uQhMX74pj7eu5wQcOCkERnNiosyb6vTRV4FCnxwIf3lr8qgLdvAfNw4xULLA0aBmYJXcYMF3XU2JE8xjcg==`

### Category

detection

### Describe the issue

pop up blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 87665
  cosmetic: 38450
  scriptlet: 16615
  html: 848
listset (total-discarded, last-updated): 
  added: 
    https://abp.perimeterx.com/whitelist.txt: 8-0, 40m
    https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 0-0, 12h.42m
  default: 
    user-filters: 21-0, never
    ublock-filters: 32313-40, 2d.16h.50m
    ublock-badware: 4049-1, 2d.16h.49m
    ublock-privacy: 305-0, 11d.5h.39m
    ublock-abuse: 77-0, 11d.5h.38m
    ublock-unbreak: 1924-1, 2d.4h.47m
    easylist: 64993-608, 5d.59m
    easyprivacy: 30913-1727, 5d.58m
    plowe-0: 3669-3, 10d.17h.32m
    urlhaus-1: 7849-0, 41m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 49 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2984 ms (selfie)
  maxAssetCacheWait: 2086 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    bluemediafile.sbs: 3
    adskeeper.com: 4
    ascentcolley.com: 1
    bookljlihooli.com: 1
    choobinoobi.com: 2
    d2er1uyk6qcknh.cloudfront.net: 12
    googletagmanager.com: 1
    pncloudfl.com: 4
    pogothere.xyz: 8
    serving-passthrough.com: 1
```
</details>

**Comment by mapx-** [comment]
it was fixed yesterday, update ALL your lists

**Comment by okiehsch** [comment]
I get ads at the link can you reproduce?

**Comment by mapx-** [comment]
I added https://github.com/uBlockOrigin/uAssets/commit/00c90f39ab383ede1de4924bfe83c677f44f4621
