### ISSUE TITLE
techtnet.com: detection

### ISSUE THREAD

**Issue by Ungic** [uBlockOrigin/uAssets#15912]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://techtnet.com/reviews/laptops/acer-swift-3-review-45`

### Category

detection

### Describe the issue

`https://linkneverdie.net/game/the-dark-pictures-anthology-the-devil-in-me-7889`

When i click download by Google Drive in the above link
After that, the link 
`https://techtnet.com/reviews/laptops/acer-swift-3-review-45` 
is appear, and the capcha in this page is detect the ublock origin. When i reload page, the capcha is disapear

![image](https://user-images.githubusercontent.com/119843310/205582640-ee057763-ba79-4849-ae79-6cd465369fa6.png)
![image](https://user-images.githubusercontent.com/119843310/205582869-04de2494-ec51-40c7-a5f8-b26fb7b9d43b.png)
![image](https://user-images.githubusercontent.com/119843310/205582935-1dfb0655-41a0-429b-b104-20cf7d3ce4d5.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 88914
  cosmetic: 39706
  scriptlet: 16839
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1963-0, 3h.25m
    easylist: 64996-73, 2d.13h.51m
    easyprivacy: 30931-1176, 2d.13h.50m
    plowe-0: 3675-900, 2d.13h.49m
    ublock-abuse: 77-0, 2d.13h.47m
    ublock-badware: 4136-110, 2d.13h.45m
    ublock-filters: 31590-137, 2d.13h.44m
    ublock-privacy: 260-1, 2d.13h.43m
    ublock-quick-fixes: 389-18, 3h.26m
    ublock-unbreak: 1910-44, 2d.13h.41m
    urlhaus-1: 8153-0, 3h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3685 ms (selfie)
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    dooloust.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    linkneverdie.net: 1
    tawpykheda.com: 1
```
</details>

**Comment by mapx-** [comment]
no issue, it was fixed days ago, update all your filter lists
