### ISSUE TITLE
[nsfw] indosubjav.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#15916]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://indosubjav.com/page-jav/1277/FERA-116-Saya-Disetubuhi-Oleh-Anak-Tiri-Kami-Aika-Satozaki.html`

### Category

ads

### Describe the issue

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/98657967/205684050-8e6c2688-05b4-40d5-9083-1a2825235ae7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 109
filterset (summary): 
  network: 87242
  cosmetic: 118127
  scriptlet: 22776
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7703-2, 3h.6m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 3h.5m
    fanboy-annoyance: 83524-310, 3h.8m
    fanboy-cookiemonster: 43708-43708, 3h.9m
    ublock-annoyances: 4796-75, 3h.7m
  default: 
    user-filters: 8-0, never
    easylist: 65202-57, 1d.6h.47m
    easyprivacy: 30936-1171, 1d.6h.46m
    ublock-abuse: 77-0, 9d.10h.19m
    ublock-badware: 4136-108, 3h.4m
    ublock-filters: 31476-434, 3h.3m
    ublock-privacy: 258-8, 9d.10h.19m
    ublock-quick-fixes: 387-25, 3h.1m
    ublock-unbreak: 1911-48, 3h.2m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2551 ms (selfie)
  maxAssetCacheWait: 1204 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    addthis.com: 2
    afcnuchxgo.com: 2
    cjvdfw.com: 2
    d3g5ovfngjw9bw.cloudfront.net: 1
    d3mr7y154d2qg5.cloudfront.net: 2
    google.com: 3
    googletagmanager.com: 4
    jdi5.com: 2
    koopheen.com: 1
    oneegrou.net: 2
    u-on.eu: 2
    wb4.xyz: 2
    yandex.ru: 2
    zap.buzz: 4
    zatnoh.com: 2
```
</details>

**Comment by mapx-** [comment]
I see no ad !?
