### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by SunnyDonut** [uBlockOrigin/uAssets#15925]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/lyrics`

### Category

breakage

### Describe the issue

Songs were playing before even with the adblocker on; now they aren't working. Spotify's buttons on the bottom and play button, along with other functions are disabled. Upon deactivation of the adblocker I'm using, site works like normal. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/45988024/205833928-837612a8-040d-41c2-899e-c1ae234728ff.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 87944
  cosmetic: 38630
  scriptlet: 16776
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65087-53, 4d.21h.57m
    easyprivacy: 30911-1171, 5d.8h.2m
    plowe-0: 3669-870, 11d.9h.17m
    ublock-abuse: 77-0, 11d.9h.15m
    ublock-badware: 4136-110, 2d.10h.2m
    ublock-filters: 31624-130, 2d.10h.3m
    ublock-privacy: 258-1, 11d.9h.11m
    ublock-quick-fixes: 389-18, 1h.23m
    ublock-unbreak: 1909-44, 2d.23h.33m
    urlhaus-1: 7849-0, 7h.36m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 121 ms (selfie)
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google-analytics.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 2
    spotifycdn.com: 1
```
</details>

**Comment by liamengland1** [comment]
Can't reproduce. I use spotify premium with ublock origin often. Try refreshing and clicking a song a couple times, it should fix it.

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by stnert** [comment]
Also having the same problem here.
