### ISSUE TITLE
Andora flag is blocked by adblocker

### ISSUE THREAD

**Issue by DrowningElysium** [uBlockOrigin/uAssets#1592]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
The following url can't be loaded by any other sites
`http://www.geonames.org/flags/x/ad.gif`

### Describe the issue

Because the country Andora is shortened to ad here, the adblocker thinks it should be blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9342313/36470884-c2831eae-16ec-11e8-9890-b9ad612425f1.png)

### Versions

- Browser/version: Firefox 59.0b11 but probably stables too
- uBlock Origin version: 1.15.6

### Settings

Just disabled adblocker

### Notes

Disabling uBlock Origin allows the image to load

**Comment by mapx-** [comment]
testing page:
http://axistrivia.altervista.org/index.html

@ryanbr
