### ISSUE TITLE
top.gg: ads

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#15920]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://top.gg/bot/270904126974590976/vote`

### Category

ads

### Describe the issue

video ads still appear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/205758542-6b5dcc22-3c2b-48a1-b5ef-494cb579af65.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 102
filterset (summary): 
  network: 106764
  cosmetic: 50027
  scriptlet: 20068
  html: 887
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4822-5, 1d.7h.27m
    CHN-0: 28317-118, 1d.7h.31m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32313-40, 1d.7h.30m
    ublock-badware: 4140-1, 1d.7h.29m
    ublock-privacy: 305-0, 11d.20h.23m
    ublock-abuse: 77-0, 11d.20h.23m
    ublock-unbreak: 1924-2, 1d.7h.28m
    ublock-quick-fixes: 398-29, 26m
    easylist: 65025-662, 5d.20h.20m
    easyprivacy: 30911-1734, 5d.20h.19m
    urlhaus-1: 8604-0, 1d.7h.26m
    plowe-0: 3669-3, 11d.20h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 644 ms (selfie)
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    top.gg: 2
    googletagmanager.com: 1
    lngtd.com: 1
```
</details>

**Comment by liamengland1** [comment]
`top.gg###rewarded-video`
