### ISSUE TITLE
searchenginejournal.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#15923]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.searchenginejournal.com/wordpress-vulnerabilities-6-0-3/473114/`

### Category

ads

### Describe the issue

https://user-images.githubusercontent.com/19517680/205819778-090adbe2-9575-4dd9-a4ab-89ba751a3f2f.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium Mobile: 107
filterset (summary): 
  network: 88694
  cosmetic: 124578
  scriptlet: 22924
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7701-2, 1d.17h.38m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 1d.17h.37m
    fanboy-annoyance: 83309-320, 4d.17h.19m
    fanboy-cookiemonster: 43645-43548, 4d.17h.18m
    ublock-annoyances: 4855-82, 1d.17h.43m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8285-14, 1d.17h.39m
    easylist: 65079-255, 4d.15h.52m
    easyprivacy: 30877-1181, 4d.11h.53m
    ublock-abuse: 77-0, 10d.12h.57m
    ublock-badware: 4135-108, 1d.17h.42m
    ublock-filters: 31718-446, 1d.17h.41m
    ublock-privacy: 258-8, 10d.12h.53m
    ublock-quick-fixes: 583-191, 12h.16m
    ublock-unbreak: 1916-50, 1d.17h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 200
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1215 ms (selfie)
  maxAssetCacheWait: 614 ms
popupPanel: 
  blocked: 8
  no-large-media: true
  blockedDetails: 
    searchenginejournal.com: 1
    ads-twitter.com: 1
    facebook.net: 1
    google-analytics.com: 2
    id5-sync.com: 1
    licdn.com: 1
    rlcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
searchenginejournal.com##.sej-hello-bar
searchenginejournal.com##[rel^="sponsored"]
searchenginejournal.com##.sss_sllo
```

@ryanbr
