### ISSUE TITLE
wnd.com: ads

### ISSUE THREAD

**Issue by JP12177** [uBlockOrigin/uAssets#15924]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.wnd.com/`

### Category

ads

### Describe the issue

Powered by Admiral ads popping u
![Capture](https://user-images.githubusercontent.com/119917276/205825441-402e138f-2c9e-477c-a85a-b7ac7991b9ef.JPG)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 101246
  cosmetic: 181300
  scriptlet: 24499
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61729-97, 7h.23m
    adguard-social: 19365-820, 3d.10h.53m
    fanboy-annoyance: 83453-4976, 4d.11h.34m
    fanboy-cookiemonster: 43645-43645, 4d.11h.33m
    fanboy-social: 23443-23443, 6d.11h.53m
    fanboy-thirdparty_social: 68-21, 4d.11h.32m
    ublock-annoyances: 4798-205, 3d.10h.52m
  default: 
    user-filters: 0-0, never
    easylist: 65205-111, 2d.8h.56m
    easyprivacy: 30935-1256, 2d.8h.57m
    plowe-0: 3676-902, 22m
    ublock-abuse: 77-0, 3d.10h.55m
    ublock-badware: 4045-110, 7h.26m
    ublock-filters: 31525-515, 7h.25m
    ublock-privacy: 260-9, 3d.10h.54m
    ublock-quick-fixes: 392-16, 3h.16m
    ublock-unbreak: 1911-51, 7h.24m
    urlhaus-1: 8858-0, 3h.17m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 190 ms (selfie)
  maxAssetCacheWait: 131 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    adsafeprotected.com: 2
    advertising.com: 1
    aj2495.online: 1
    amazon-adsystem.com: 1
    contextweb.com: 1
    d1zxg9iar5y3ur.cloudfront.net: 1
    d3lcz8vpax4lo2.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    instiengage.com: 1
    izooto.com: 1
    lockerdomecdn.com: 1
    mgid.com: 2
    paypal.com: 1
    pubmatic.com: 1
    quantserve.com: 1
    rlcdn.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
