### ISSUE TITLE
bluemediafile.sbs: detection

### ISSUE THREAD

**Issue by camboozle** [uBlockOrigin/uAssets#15934]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+LbhzXSyXf8WzgArdoPqmftaO44jO70lnYvBXsmAldf20VimCKV8HgeDtNWrFa8lXcT1BDFTEESRtLX9xDuZpnI=`

### Category

detection

### Describe the issue

Website gives the error "`Please support us by disabling Adblock and refresh page, thank you.`" 50% of the time.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/102335295/206078731-dc5d5514-ed50-4223-a1ea-5f6a0404f07a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 89256
  cosmetic: 38660
  scriptlet: 16744
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32313-40, 2d.3h.9m
    ublock-badware: 4049-1, 2d.3h.8m
    ublock-privacy: 309-0, 1d.5h.52m
    ublock-abuse: 77-0, 1d.5h.51m
    ublock-unbreak: 1924-2, 2d.3h.7m
    ublock-quick-fixes: 398-29, 1d.1h.50m
    easylist: 65589-634, 3h.21m
    easyprivacy: 30941-1742, 3h.20m
    urlhaus-1: 8858-0, 1d.1h.49m
    plowe-0: 3679-3, 5d.7h.3m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 312 ms (selfie)
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    bluemediafile.sbs: 5
    adskeeper.com: 4
    ascentcolley.com: 1
    bookljlihooli.com: 1
    choobinoobi.com: 2
    ctsjackupspete.com: 13
    googletagmanager.com: 1
    onhadintrepha.info: 11
    pogothere.xyz: 8
```
</details>

**Comment by liamengland1** [comment]
Update your filters.
