### ISSUE TITLE
globaldefensecorp.com: nuisance

### ISSUE THREAD

**Issue by fralumz** [uBlockOrigin/uAssets#15933]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.globaldefensecorp.com/2022/06/22/lithuania-blocks-rail-transit-to-russian-exclave-kaliningrad/`

### Category

nuisance

### Describe the issue

copy paste block
highlight disable
right click disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88893
  cosmetic: 38557
  scriptlet: 16675
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    ublock-filters: 32258-60, 2d.5m
    ublock-badware: 4140-1, 2d.4m
    ublock-privacy: 308-0, 2d.8m
    ublock-abuse: 77-0, 2d.9m
    ublock-unbreak: 1924-2, 2d.3m
    easylist: 64996-624, 2d.10m
    easyprivacy: 30908-1710, 2d.11m
    urlhaus-1: 8858-0, 1d
    plowe-0: 3675-3, 2d.7m
    ublock-quick-fixes: 399-0, 23h.59m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2421 ms
  maxAssetCacheWait: 485 ms
popupPanel: 
  blocked: 40
  no-cosmetic-filtering: true
  no-large-media: true
  no-scripting: true
  blockedDetails: 
    globaldefensecorp.com: 15
    google.com: 4
    googlesyndication.com: 5
    wp.com: 13
    youtube.com: 3
```
</details>

**Comment by mapx-** [comment]
Enable this filter list `uBlock filters – Annoyances`
