### ISSUE TITLE
viefaucet.com detection

### ISSUE THREAD

**Issue by EPICSY** [uBlockOrigin/uAssets#15935]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://viefaucet.com/app/wait
https://viefaucet.com/app/faucet
```

### Describe the issue

uBlockOrigin gets detected by the mentioned site.
You might be able to solve this

### uBlock Origin version

1.45.2

### Browser name and version

kiwi 

### Settings

I didn't change anything

**Comment by mapx-** [comment]
> kiwi

- kiwi has known issues with uBO
- use firefox and test again

**Comment by king-iskan** [comment]
![Screenshot_20230325-034933](https://user-images.githubusercontent.com/120553425/227637444-d6a6fdf0-13f0-471d-93c5-fb0f5b72c479.png)

**Comment by mapx-** [comment]
@king-iskan 

test

```
viefaucet.com#@#+js(aeld, n&&n)
viefaucet.com##+js(aopr, coinzilla_display)
```

**Comment by king-iskan** [comment]
Not work

**Comment by mapx-** [comment]
@king-iskan desktop ? android ?

**Comment by king-iskan** [comment]
> @king-iskan desktop ? android ?

Both

**Comment by mapx-** [comment]
It's working fine on my end

**Comment by king-iskan** [comment]
> It's working fine on my end

PC? Viefaucet/app/faucet

**Comment by mapx-** [comment]
yes, pc, that link. No anti adb message at all.

**Comment by king-iskan** [comment]
> It's working fine on my end

Detection just open this 
viefaucet/app/faucet (detection)
For another yeah already work not detect adblock, example
viefaucet/app/link (not detect)
viefaucet.com/app/offerwall (not detect)

**Comment by king-iskan** [comment]
> yes, pc, that link. No anti adb message at all.

I already try in chrome PC, work smooth. But cannot work in android.
Maybe u can reproduce for Android too... 🙏

**Comment by mapx-** [comment]
working fine in FF android too

**Comment by king-iskan** [comment]
> working fine in FF android too

Are u sure, why my FF not working😭

**Comment by king-iskan** [comment]
> working fine in FF android too

Are u sure, why my FF not working😭

> working fine in FF android too

Just update or put in filter?

**Comment by mapx-** [comment]
test

```
viefaucet.com#@#+js(aopr, coinzilla_display)
@@||coinzillatag.com/lib/display.js$script,domain=viefaucet.com
@@||cointraffic.io/js/$script,domain=viefaucet.com
```

**Comment by king-iskan** [comment]
> 

This work better. Thanks 🙏
