### ISSUE TITLE
gizmodo.com: breakage

### ISSUE THREAD

**Issue by ticktickMOF** [uBlockOrigin/uAssets#15932]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gizmodo.com/black-adam-box-office-flop-dwayne-the-rock-johnson-dcu-1849858829`

### Category

breakage

### Describe the issue

affiliate links are being completely removed, mangling the prose.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/15878714/206063092-1c7c8020-4cfc-467e-b8b5-d4f4d5014ad9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 88848
  cosmetic: 38570
  scriptlet: 16689
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64993-53, 5d.16h.37m
    easyprivacy: 30908-1171, 5d.16h.36m
    plowe-0: 3669-870, 12d.15h.6m
    ublock-abuse: 77-0, 7d.1h.34m
    ublock-badware: 4141-110, 1d.5h.49m
    ublock-filters: 31514-128, 1d.5h.48m
    ublock-privacy: 260-1, 4d.21h.44m
    ublock-quick-fixes: 391-18, 33m
    ublock-unbreak: 1912-44, 1d.5h.50m
    urlhaus-1: 8799-0, 34m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2078 ms
  maxAssetCacheWait: 1445 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    gizmodo.com: 5
    adlightning.com: 1
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    indexww.com: 1
    kinja-static.com: 1
    mgid.com: 1
    speedcurve.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`gizmodo.com#@#a[href^="https://www.amazon."][href*="tag="]`

@ryanbr
