### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Adorerop** [uBlockOrigin/uAssets#15939]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

it shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 88818
  cosmetic: 38553
  scriptlet: 16694
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64993-53, 1d.4h.5m
    easyprivacy: 30908-1171, 1d.4h.4m
    plowe-0: 3667-870, 10d.15h.38m
    ublock-abuse: 77-0, 12d.11h.45m
    ublock-badware: 4141-110, 8h.1m
    ublock-filters: 31500-112, 8h
    ublock-privacy: 258-1, 12d.11h.44m
    ublock-quick-fixes: 356-20, 20h.3m
    ublock-unbreak: 1911-46, 7h.59m
    urlhaus-1: 8799-0, 16h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 200 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 1
    innovid.com: 1
    scorecardresearch.com: 33
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
twitch
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
