### ISSUE TITLE
chiphell.com: breakage

### ISSUE THREAD

**Issue by jesee030** [uBlockOrigin/uAssets#15936]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.chiphell.com/activity/Razer/2020-Q4/index.html`

### Category

breakage

### Describe the issue

block that site 95% context auto,so that i see nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 106756
  cosmetic: 48795
  scriptlet: 16816
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-0, never
    CHN-0: 28336-98, 23h.46m
    easylist: 65093-88, 5d.3m
    easyprivacy: 30920-1194, 5d.2m
    plowe-0: 3679-902, 5d.1m
    ublock-abuse: 77-0, 4d.23h.59m
    ublock-badware: 4141-110, 23h.45m
    ublock-filters: 31514-147, 23h.44m
    ublock-privacy: 260-1, 4d.23h.55m
    ublock-quick-fixes: 389-16, 19h.42m
    ublock-unbreak: 1912-45, 23h.43m
    urlhaus-1: 8799-0, 19h.41m
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1307 ms (selfie)
  maxAssetCacheWait: 327 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    chiphell.com: 44
```
</details>

**Comment by mapx-** [comment]
add

`||chiphell.com/activity/$badfilter`

@cjx82630
