### ISSUE TITLE
badware 

### ISSUE THREAD

**Issue by Ing-Josef-Klotzner** [uBlockOrigin/uAssets#15937]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pixnet.net/pcard/48760601c2544acf73/article/e821f620-8e8e-11eb-903a-eb48eb2a7071`

### Describe the issue

i had bad experience with this site which costed me a few hours to fix computer and used usb sticks. I want to report this to get it into uBlocks filters. the virus leaves _readme.txt files in all directories it can access. Content: "Your files are crypted now. If you want them decrypted pay $ 1000,- to ...."

WARNING: DO NOT download from above link and NEVER EVER install the download  !!!!!!!!!!!!!!!!
(this is a comment for you here reading this - i do not paste the download link itself here, at least to prevent to press it here)

### uBlock Origin version

all versions

### Browser name and version

irrelevant for filters

### Settings

irrelevant

### Notes

i had bad experience with this site which costed me a few hours to fix computer and used usb sticks. I want to report this to get it into uBlocks filters. the virus leaves _readme.txt files in all directories it can access. Content: "Your files are crypted now. If you want them decrypted pay $ 1000,- to ...."

**Comment by JobcenterTycoon** [comment]
The "link shortener" site looks malicious too. Here the points:

- The link shortener site don’t react to my abuse report
- The exact same link (`imgfil.com/1uvv8i`) now redirect to a different malicious domain `arakusus.com`
- I can’t short my own URL, i just get a blank site
- Many Vendors flagging this URL https://www.virustotal.com/gui/url/5ed44da1daabaa0f15b949d87d52094672f9d46c7aea0c1439f803975edec23c?nocache=1
