### ISSUE TITLE
[nsfw] simpcity.su: Residues / elements

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#15938]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://simpcity.su/`

### Category

Residues / elements

### Describe the issue

There are empty inserts (a lot of space monopolized).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/206173144-8864a760-72d5-44ac-94e5-559e624adfc2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 112148
  cosmetic: 87538
  scriptlet: 18596
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43717-163, now
  default: 
    user-filters: 0-0, never
    FRA-0: 30479-28, now
    easylist: 65697-165, now
    easyprivacy: 30950-1556, now
    plowe-0: 3677-925, now
    ublock-abuse: 77-1, now
    ublock-badware: 4141-127, now
    ublock-filters: 31504-236, now
    ublock-privacy: 262-1, now
    ublock-quick-fixes: 402-14, now
    ublock-unbreak: 1914-46, now
    urlhaus-1: 9450-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 167 ms (selfie)
  maxAssetCacheWait: 161 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    adtng.com: 3
```
</details>

**Comment by mapx-** [comment]
test
`||cdn77.aj2526.bid/04842d10.js$script,domain=simpcity.su`

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
Easylist maintainer notified
