### ISSUE TITLE
convergent.es: breakage

### ISSUE THREAD

**Issue by pstch** [uBlockOrigin/uAssets#15945]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.convergent.es/?CartePublique`

### Category

breakage

### Describe the issue

**To reproduce**:
 - click on an item on the map

**Expected behaviour**:
 - seeing a dialog box open with details on the map item

**What happens instead:**
 - the dialog box opens and closes immediately, but the faded grey/transparent background stays there and it's not possible to interact with the page anymore until it is reloaded

This does not happen when uBO is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 91
filterset (summary): 
  network: 89723
  cosmetic: 38683
  scriptlet: 16747
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32313-55, 1d.19h
    ublock-badware: 4145-1, 1d.19h.2m
    ublock-privacy: 305-0, 12d.14h.42m
    ublock-abuse: 77-0, 12d.14h.41m
    ublock-unbreak: 1925-2, 1d.19h.1m
    easylist: 65589-634, 49m
    easyprivacy: 30936-1739, 1d.19h.3m
    urlhaus-1: 9239-0, 47m
    plowe-0: 3677-3, 8d.5h.6m
    ublock-quick-fixes: 408-0, 48m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1775 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
It results broken on my end in FF / chrome even disabling uBO

**Comment by pstch** [comment]
Oh indeed. The bug happens on one page reload, but not on the next one, and then happens again. This tricked me into believing it was caused by uBO. Thanks for your test @mapx-, I'll close the issue.
