### ISSUE TITLE
bluemediafile.sbs: detection

### ISSUE THREAD

**Issue by Meowmer420** [uBlockOrigin/uAssets#15944]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+Eg8Laa+m+CUEf+a+qdGmQcMHO9V+3lVqjTg/uW6ZdTk5LMscJY8/Yjp7XyiTrxPUw==`

### Category

detection

### Describe the issue

website detected ublock. some ads do show.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-07 212311](https://user-images.githubusercontent.com/120033373/206204209-ef52b4b0-207f-4f88-8885-cb84770d98b4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 89723
  cosmetic: 38688
  scriptlet: 16755
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65629-52, 32m
    easyprivacy: 30950-1171, 31m
    plowe-0: 3677-900, 30m
    ublock-abuse: 77-0, 28m
    ublock-badware: 4045-110, 26m
    ublock-filters: 31590-138, 25m
    ublock-privacy: 262-1, 24m
    ublock-quick-fixes: 387-25, 23m
    ublock-unbreak: 1913-44, 22m
    urlhaus-1: 9239-0, 21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 241 ms
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    bluemediafile.sbs: 3
    adskeeper.com: 2
    ascentcolley.com: 1
    bookljlihooli.com: 1
    choobinoobi.com: 2
    ctsjackupspete.com: 12
    googletagmanager.com: 1
    onhadintrepha.info: 11
    pogothere.xyz: 1
```
</details>

**Comment by krystian3w** [comment]
Unable reproduce.

Also you can speed up counter: https://greasyfork.org/pl/scripts/423435-igg-games-bluemediafiles-bypass/code then page don't have enough time to detect anti-adblock if webmaster still have javascript with lag input.

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by Meowmer420** [comment]
thank you, this worked

**Comment by Meowmer420** [comment]
none of the above worked, but bypassing the timer worked. Thank you

**Comment by krystian3w** [comment]
Last step will by unistall uBo and fresh instalation - damaged data of extension.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16055
