### ISSUE TITLE
dev-panel.falixnodes.net: detection

### ISSUE THREAD

**Issue by ItMasterAntoni** [uBlockOrigin/uAssets#15941]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [x] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dev-panel.falixnodes.net/disableadblock.php`

### Category

detection

### Describe the issue

I am very sorry for my English, it is not my first language.

I'm hosting a server on falixnodes.net and today I displayed this message.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-07 at 13-33-34 Adblock detected FalixNodes](https://user-images.githubusercontent.com/79043321/206181673-d9dba0e0-898b-489a-a3a3-8f52785e79bd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 227186
  cosmetic: 174244
  scriptlet: 37865
  html: 899
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66172-6054, 4m
    adguard-mobile: 8347-166, 4m
    adguard-spyware: 33827-3531, 4m
    adguard-spyware-url: 854-3, 4m
    block-lan: 44-0, 4m
    curben-phishing: 76056-6, 4m
    curben-pup: 188-0, 4m
    adguard-annoyance: 61894-5462, 4m
    adguard-social: 19402-1671, 4m
    fanboy-thirdparty_social: 68-1, 4m
    fanboy-annoyance: 83554-71567, 4m
    fanboy-cookiemonster: 43715-17310, 4m
    fanboy-social: 23459-13735, 4m
    ublock-annoyances: 4826-9, 4m
    dpollock-0: 11393-517, 4m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32293-327, 4m
    ublock-badware: 4145-1, 4m
    ublock-privacy: 309-1, 4m
    ublock-abuse: 77-0, 4m
    ublock-unbreak: 1927-3, 4m
    ublock-quick-fixes: 409-0, 4m
    easylist: 65697-18040, 4m
    easyprivacy: 30950-12760, 4m
    urlhaus-1: 9450-0, 4m
    plowe-0: 3677-3, 4m
    POL-0: 7859-157, 4m
    POL-2: 1279-17, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4876 ms
  maxAssetCacheWait: 2617 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
@mapx- without `@@||cdn.snigelweb.com/adengine/falixnodes.net/loader.js$script,domain=dev-panel.falixnodes.net` i get "Something is blocking the page! Please disable adblock or equivalent extension or program." the redirection is blocked but the anti adblock is still here

**Comment by mapx-** [comment]
What page did you test ?

I used `https://client.falixnodes.net/`

**Comment by mapx-** [comment]
Do you have an account on `dev-panel.falixnodes.net` ?

**Comment by JobcenterTycoon** [comment]
Yes. On `dev-panel.falixnodes.net` the anti adblock is a bit different

**Comment by mapx-** [comment]
ok, I see, add the needing filters then
