### ISSUE TITLE
[nsfw] deleterasks.digital: ads

### ISSUE THREAD

**Issue by Declate** [uBlockOrigin/uAssets#15948]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://deleterasks.digital/ed/nTOldoOYl*dkieg1oUiXVFkp3......`

### Category

ads

### Describe the issue

Irritating

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 107
filterset (summary): 
  network: 95614
  cosmetic: 29295
  scriptlet: 16742
  html: 865
listset (total-discarded, last-updated): 
  added: 
    https://sensasihoki.com/glkn/365glkn05aiv.html: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32405-302, 21m
    ublock-badware: 4152-1, 21m
    ublock-privacy: 309-1, 21m
    ublock-abuse: 77-0, 21m
    ublock-unbreak: 1932-2, 21m
    ublock-quick-fixes: 410-0, 21m
    adguard-mobile: 8339-171, 21m
    easylist: 65699-17803, 21m
    easyprivacy: 30950-1751, 21m
    urlhaus-1: 9239-0, 21m
    plowe-0: 3677-3, 21m
    IDN-0: 9218-3693, 21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3043 ms
  maxAssetCacheWait: 1493 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide the original page where if you click on it you will be redirected to that crap
