### ISSUE TITLE
azmath.info: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#15940]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://azmath.info/the-physicalization-of-metamathematics-and-its-implications-for-the-foundations-of-mathematics-stephen-wolfram-writings.html`

### Category

detection

### Describe the issue

This site detect uBo.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/206181419-28983303-384a-4cda-961c-888e433890b9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 94366
  cosmetic: 43658
  scriptlet: 16699
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist.to/easylist/easylist.txt: 65699-52, 2m
  default: 
    user-filters: 28-0, never
    IDN-0: 9218-1, 3m
    easylist: 65697-65696, 3m
    easyprivacy: 30950-1173, 3m
    plowe-0: 3677-900, 2m
    ublock-abuse: 77-0, 2m
    ublock-badware: 4141-110, 2m
    ublock-filters: 31504-141, 2m
    ublock-privacy: 262-1, 2m
    ublock-quick-fixes: 402-14, 2m
    ublock-unbreak: 1914-46, 2m
    urlhaus-1: 9450-0, 2m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 716 ms (selfie)
  maxAssetCacheWait: 432 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    distinctbelieverjustify.com: 1
    doubleclick.net: 3
    exmarketplace.com: 1
    googletagmanager.com: 1
    trackpush.com: 1
    unibots.in: 1
    vdo.ai: 1
    youtube.com: 10
```
</details>

**Comment by krystian3w** [comment]
We need direct url before was opened fool WP blog.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15799

**Comment by lyubomyrhv** [comment]
detectet
