### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by thekcool** [uBlockOrigin/uAssets#15953]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Describe the issue

I'm still getting Inbox ads. I made a [reddit post](https://www.reddit.com/r/uBlockOrigin/comments/ze6kg7/still_getting_ads_in_outlookcom/) and the only reply was to open an issue here. This was after I found and tried the answer from this [post](https://www.reddit.com/r/uBlockOrigin/comments/ykm4xa/how_can_i_block_these_ads_on_outlookcom/iuunfzd/).

The ad only appears when I use "Cozy" as my "Display Setting". The ad is blocked in "Roomy" and "Compact". I have tried to "purge all caches" and "update" but it still shows up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 216616
  cosmetic: 179170
  scriptlet: 37757
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2989-10, 1m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2048-1, 1m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 1m
    https://www.i-dont-care-about-cookies.eu/abp/: 25625-5, 1m
    adguard-annoyance: 62008-1718, 1m
    adguard-generic: 66182-572, 1m
    adguard-spyware: 33833-3859, 1m
    adguard-spyware-url: 854-122, 1m
    block-lan: 44-0, 1m
    curben-phishing: 62134-1, 1m
    curben-pup: 188-1, 1m
    dpollock-0: 11393-182, 1m
    fanboy-cookiemonster: 43764-11391, 1m
    ublock-annoyances: 4802-224, 1m
  default: 
    user-filters: 21-0, never
    easylist: 65840-1215, 1m
    easyprivacy: 30961-12484, 1m
    plowe-0: 3677-1350, 1m
    ublock-abuse: 77-0, 1m
    ublock-badware: 4149-267, 1m
    ublock-filters: 31488-3741, 1m
    ublock-privacy: 255-48, 1m
    ublock-quick-fixes: 411-42, 1m
    ublock-unbreak: 1914-105, now
    urlhaus-1: 9300-2, now
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 14818 ms (selfie)
  maxAssetCacheWait: 4290 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    live.com: 4
    adnxs.com: 1
    bing.com: 1
    microsoft.com: 9
    msn.com: 2
    office.net: 14
    yahoo.com: 1
```
</details>

**Comment by mapx-** [comment]
What ad ? screenshot ?

**Comment by thekcool** [comment]
@mapx- 
![Capture 20221208 0228pm](https://user-images.githubusercontent.com/18403760/206549637-e321202b-0a3d-4770-86e9-e04d00b235d6.JPG)

**Comment by mapx-** [comment]
Test

`outlook.live.com##span[class]:has-text(/Upgrade|OneDrive/)`

**Comment by thekcool** [comment]
Sorry, doesn't work. The ad's still there.

**Comment by mapx-** [comment]
working on my end: I get the ad on the left side at the bottom, first Upgrade and quickly changes in OneDrive ad

![image](https://user-images.githubusercontent.com/10303732/206556683-8abdbf41-ceb9-497c-b147-308f78c18abd.png)

**Comment by liamengland1** [comment]
This works for me, apparently I had this as a custom filter since June and it didn't break anything

`outlook.live.com##[data-app-section="MessageList"]>div>div>div>div>div>div>div:not([id])`

**Comment by mapx-** [comment]
Test

`outlook.live.com##:xpath("//*[contains(text(),'OneDrive') or contains(text(),'Upgrade')]"):upward(1)`

or (if breakage)

`outlook.live.com##:xpath("//*[contains(text(),'OneDrive') or contains(text(),'Upgrade')]")`

**Comment by ghajini** [comment]
@liamengland1 your filter caused this sections
![Screenshot (392)](https://user-images.githubusercontent.com/20338483/206742330-e14dc559-9b81-4fcf-90bb-560f920a1466.png)

 to be hidden

**Comment by mapx-** [comment]
ok ... reproduced 

`outlook.live.com##:xpath("//*[(text()='Ad')]"):upward(3)`

**Comment by liamengland1** [comment]
@ghajini I had that setting disabled, oops

Try `outlook.live.com##[data-app-section="MessageList"]>div[tabindex="-1"]>div>[role="region"]>[role="listbox"]>div>div>div:not([data-convid]):not([role="heading"])`

@mapx- those filters don't work. First filter leaves a placeholder, 2nd filter removes all the messages in the inbox

**Comment by mapx-** [comment]
this 1 ?

`outlook.live.com##span.fbAdCallToAction:upward(5)`

**Comment by liamengland1** [comment]
Leftover ad space...

![image](https://user-images.githubusercontent.com/16567977/206772754-3b841dbf-9ee5-4116-b849-8f70a2b09479.png)

This works well: `outlook.live.com##span.fbAdCallToAction:upward([role="listbox"]>div>div>div)`

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/83c504de9f55fec7b74cc144bfb5c8acce9e4840

**Comment by krystian3w** [comment]
@liamengland1 your filter break "slower" 'layout': 

> https://outlook.live.com/mail/0/options/general/advertisement

![image](https://user-images.githubusercontent.com/35370833/208434053-8e8c8694-fb55-4b93-ba87-77d72c279f17.png)

Second don't match at all (`##[data-app-section="MessageList"]>[tabindex="-1"]>div>[role="region"]>[role="listbox"]>div>div>div:not([data-convid]):not([role="heading"]`).

Approved commit don't match "slower" 'layout':

![image](https://user-images.githubusercontent.com/35370833/208437075-71658959-8cdf-4975-a7ed-222110060a1c.png)


Also upward must be moved to 9 - so can by danger for "faster" aka 'recommended' by MS:

`##span.fbAdCallToAction:upward(9)`

**Comment by tasty0tomato** [comment]
![image](https://user-images.githubusercontent.com/48764449/230806161-c5d0a8e5-c852-4385-b5e9-7dc8eca9be2a.png)
Seems happens again.

**Comment by stephenhawk8054** [comment]
Can you test this?

```adb
outlook.live.com#?#div.customScrollBar > div > div > div > div > div > div:-abp-has(div[class] > div[class] > div[class] > div[class] > i[data-icon-name="Delete"] + div[class]), test
```

**Comment by tasty0tomato** [comment]
Should I add it here? https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
If so, seems not work.

**Comment by krystian3w** [comment]
Recommended/"faster" ad layout are addressed correctly: `https://outlook.live.com/mail/0/options/general/advertisement`

For slower layout you can test:

```adb
! ad at top in 2-nd column
outlook.live.com##div[role="complementary"] > div:has(> * .fbAdCallToAction)
!
! ad at bottom about MS 365 upgrade
outlook.live.com###MainModule .disableTextSelection.customScrollBar + div button
```

![obraz](https://user-images.githubusercontent.com/35370833/230922003-18a34d4b-e2ed-400d-9cc4-95b840f6c28a.png)

**Comment by tasty0tomato** [comment]
I don't know why but there is not advertisement option in my Outlook
![image](https://user-images.githubusercontent.com/48764449/231048911-309d194d-b8e6-4396-9039-661dc70e30be.png)

**Comment by krystian3w** [comment]
On PC/iMac/MacBook you can open: `https://outlook.live.com/mail/0/options/general/advertisement` instead use search.

Link does not working in Firefox Mobile or if you overriding useragent to mobile device.
