### ISSUE TITLE
hqq.tv: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#15954]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www3.animeflv.net/ver/renai-flops-9`

### Category

dev tools

### Describe the issue

1. `https://www3.animeflv.net/ver/renai-flops-9`
2. `OPCIÓN 7`
3. Play video and press F12
4. Video crash

### Screenshot(s)

https://user-images.githubusercontent.com/33556647/206469929-a829283e-f96a-4f60-880d-57828ee36a87.png

### Configuration

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 63750
  cosmetic: 45296
  scriptlet: 20161
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
  added: 
    ublock-annoyances: 4802-6, 5m
  default: 
    user-filters: 4-0, never
    easylist: 65840-53, 5m
    plowe-0: 3677-345, 5m
    spa-0: 3425-9, 5m
    spa-1: 4883-170, 5m
    ublock-abuse: 77-0, 5m
    ublock-badware: 4149-110, 5m
    ublock-filters: 31494-154, 5m
    ublock-privacy: 255-1, 5m
    ublock-quick-fixes: 411-14, 5m
    ublock-unbreak: 1914-17, 5m
    urlhaus-1: 9300-0, 5m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 120 ms (selfie)
  maxAssetCacheWait: 147 ms

```

**Comment by mapx-** [comment]
It seems to work .. but is restarting the video, do you get the same behaviour ?

**Comment by mapx-** [comment]
@PIZZA90 test:

`hqq.*##+js(set, dest, trueFunc)`

**Comment by mapx-** [comment]
on my end:
- working fine on animeflv
- on animeonline I have repeatedly clear cookies and finally started working too
