### ISSUE TITLE
tk.no: breakage

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#15952]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.tk.no/`

### Describe the issue

When I have enabled the uBlock filters – Privacy filter. I am not able to log in to this website and cannot read + articles. If I disable this filter everything works as intended.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 107.0.1

### Settings

- Not made any changes.

**Comment by mapx-** [comment]
- open the uBO's [logger](https://github.com/gorhill/uBlock/wiki/The-logger)
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by mapx-** [comment]
@DandelionSprout can you help here ?

**Comment by DandelionSprout** [comment]
I would normally have been able to help, but I'm very, very tired this afternoon and am not at good health.

**Comment by okiehsch** [comment]
Caused by 
`||no/api/aid/users/self?filter=*itracking$xhr`
we should probably remove it. 
It could lead to the same issue on quite a few websites.

**Comment by mapx-** [comment]
yes, I wanted to be sure it's about that filter.
