### ISSUE TITLE
dizipal438.com: breakage

### ISSUE THREAD

**Issue by KaraKule06** [uBlockOrigin/uAssets#15951]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://dizipal438.com/dizi/konusanlar/sezon-3/bolum-14`

### Category

breakage

### Describe the issue

video penceresi gelmiyor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 243407
  cosmetic: 230014
  scriptlet: 38963
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 1d.4h.39m
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 12-0, 684d.21h.38m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 1d.4h.41m
    https://winhelp2002.mvps.org/hosts.txt: 8730-315, 1d.4h.42m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-11, 1d.4h.40m
    adguard-annoyance: 61653-150, 3d.4h.53m
    adguard-generic: 66043-614, 3d.4h.44m
    adguard-mobile: 8288-220, 3d.4h.52m
    adguard-social: 19368-845, 3d.4h.49m
    adguard-spyware: 33840-4296, 3d.4h.51m
    adguard-spyware-url: 853-1, 2d.28m
    block-lan: 44-0, 6d.22h.22m
    curben-phishing: 76056-1, 1d.36m
    curben-pup: 188-1, 1d.35m
    dpollock-0: 11392-1790, 3d.4h.56m
    fanboy-annoyance: 83453-5049, 6d.22h.19m
    fanboy-cookiemonster: 43645-43645, 6d.22h.21m
    fanboy-social: 23457-23452, 3d.4h.55m
    fanboy-thirdparty_social: 68-21, 6d.22h.20m
    ublock-annoyances: 4798-239, 3d.4h.50m
  default: 
    user-filters: 6-0, never
    TUR-0: 11717-19, 3d.4h.45m
    easylist: 65326-1589, 3d.4h.54m
    easyprivacy: 30943-12649, 1d.4h.43m
    plowe-0: 3667-2556, 12d.12m
    ublock-abuse: 77-0, 6d.56m
    ublock-badware: 4136-268, 3d.4h.48m
    ublock-filters: 31517-3741, 3d.4h.47m
    ublock-privacy: 260-52, 6d.55m
    ublock-quick-fixes: 401-40, 1d.34m
    ublock-unbreak: 1911-109, 3d.4h.46m
    urlhaus-1: 9450-2, 1d.33m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 32 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6243 ms (selfie)
  maxAssetCacheWait: 577 ms
popupPanel: 
  blocked: 38
  blockedDetails: 
    dizipal438.com: 32
    cdn77.monster: 2
    googletagmanager.com: 2
    waust.at: 2
```
</details>

**Comment by mapx-** [comment]
add

`/devtools-detector.$badfilter`

@ryanbr
