### ISSUE TITLE
s.to: ads

### ISSUE THREAD

**Issue by darmstadt40** [uBlockOrigin/uAssets#15965]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.to/serie/stream/die-sopranos/staffel-3/episode-4`

### Category

ads

### Describe the issue

Popups appear when pausing the stream or when changing the full screen mode. And the first time full screen mode, a message appears. Screenshot attached.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20221210-003142](https://user-images.githubusercontent.com/43100020/206812225-e9f06d76-4fa4-4b53-a874-5b72630293fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 107
filterset (summary): 
  network: 93294
  cosmetic: 31458
  scriptlet: 16770
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32375-284, 1d.17h.22m
    ublock-badware: 4152-1, 1d.8h.54m
    ublock-privacy: 302-1, 1d.8h.57m
    ublock-abuse: 77-0, 1d.8h.56m
    ublock-unbreak: 1929-2, 1d.1h.49m
    ublock-quick-fixes: 411-0, 21h.18m
    adguard-mobile: 8339-174, 1d.17h.23m
    easylist: 65784-17825, 1d.22h.20m
    easyprivacy: 30950-1761, 1d.22h.19m
    urlhaus-1: 8929-0, 21h.17m
    plowe-0: 3677-3, 1d.8h.55m
    DEU-0: 6055-385, 21h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 256 ms (selfie)
  maxAssetCacheWait: 128 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    20demidistance9elongations.com: 1
    ads-twitter.com: 1
    imasdk.googleapis.com: 2
    unanimouslyrejectproperly.com: 3
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
I get no popup, @ghajini can you reproduce it ?

**Comment by ghajini** [comment]
i can't reproduce, i already checked

**Comment by mapx-** [comment]
@darmstadt40 reinstall uBO, refresh all your filter lists

**Comment by darmstadt40** [comment]
I reroduced it. It's a video screen record: https://photos.app.goo.gl/zvcPdVBUf1Z1TXW99

This time there are just the popups which open and close by themselves because of clicking on the stream. Before the popups opened and stayed open.

I already updated the filters of ublock. Often the filters don't update automatically.

**Comment by ghajini** [comment]
It's new mirror of `voe.sx` => `telyn610zoanthropy.com` 
they always change
