### ISSUE TITLE
uploadfiles.io [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1596]
URL(s) where the issue occurs

`https://uploadfiles.io/5s3ym`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by ghajini** [comment]
popups
`https://uploadfiles.pw/0eda361024c19dec`
