### ISSUE TITLE
soap2day.to: popups

### ISSUE THREAD

**Issue by Tv1ll** [uBlockOrigin/uAssets#15967]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soap2day.to/MczoyODoiNTcxfHw3Mi42Ni4xOS44MXx8MTY3MDY1MDMwOCI7.html`

### Category

popups

### Describe the issue

Website is getting around the popup blocking from Ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 89368
  cosmetic: 38596
  scriptlet: 16698
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64996-53, 6d.10h.5m
    easyprivacy: 30936-1171, 5d.10h.28m
    plowe-0: 3675-900, 6d.23h.50m
    ublock-abuse: 77-0, 10d.22h.58m
    ublock-badware: 4149-110, 2d.2h.58m
    ublock-filters: 31506-112, 2d.2h.56m
    ublock-privacy: 260-1, 10d.22h.57m
    ublock-quick-fixes: 417-14, 1d.6h.7m
    ublock-unbreak: 1913-44, 2d.2h.57m
    urlhaus-1: 9300-0, 1d.6h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 443 ms (selfie)
  maxAssetCacheWait: 52 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    clksite.com: 1
    d27qffx6rqb3qm.cloudfront.net: 2
    googletagmanager.com: 1
    pogothere.xyz: 2
    s3.us-east-1.amazonaws.com: 1
```
</details>

**Comment by liamengland1** [comment]
Update your filters https://github.com/uBlockOrigin/uAssets/commit/ab0488408dc852fccf8657ef4f840546ae04ca72
