### ISSUE TITLE
primevideo.com: ads

### ISSUE THREAD

**Issue by DooubleTap** [uBlockOrigin/uAssets#15972]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.primevideo.com/`

### Category

ads

### Describe the issue

there is some ads on some shows. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://cdn.discordapp.com/attachments/947418248079634442/1051297122915454976/12-10-22_07.37PM.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 89267
  cosmetic: 38694
  scriptlet: 16765
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65786-52, 2d.1h.22m
    easyprivacy: 30952-1171, 2d.1h.21m
    plowe-0: 3675-900, 6d.18h.34m
    ublock-abuse: 77-0, 8d.2h.52m
    ublock-badware: 4149-110, 2d.1h.20m
    ublock-filters: 31525-138, 2d.1h.19m
    ublock-privacy: 260-1, 8d.2h.51m
    ublock-quick-fixes: 421-14, 18h.11m
    ublock-unbreak: 1911-46, 4d.51m
    urlhaus-1: 8564-0, 18h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 471 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 687
  blockedDetails: 
    primevideo.com: 13
    amazon.com: 674
```
</details>

**Comment by liamengland1** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1905
