### ISSUE TITLE
secure-browse.com: detection

### ISSUE THREAD

**Issue by Itsalifestyle** [uBlockOrigin/uAssets#15971]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://secure-browse.com/cl/403234/71728?s1=ckx0lyoqe00a20102foj3hwmyfsid-6063445-b165f5520d&s5=63950b41df221f58ee629419&source=vc-4838&source_type=offer_api&sh=d16b93bc7bfce99a&sh_timestamp=1670712129`

### Category

detection

### Describe the issue

Website detects ad blocker and will not allow access to requested website without disabling uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 175200
  cosmetic: 71264
  scriptlet: 29916
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66204-494, 4h.27m
    adguard-spyware: 33847-3708, 4h.26m
    adguard-spyware-url: 862-1, 4h.28m
    block-lan: 44-0, 19d.15h.2m
    curben-phishing: 51060-0, 4h.20m
    curben-pup: 187-1, 4h.21m
  default: 
    user-filters: 37-1, never
    easylist: 66153-892, 4h.23m
    easyprivacy: 30976-12335, 4h.22m
    plowe-0: 3675-981, 6d.5h.1m
    ublock-abuse: 77-0, 4h.16m
    ublock-badware: 4149-262, 4h.25m
    ublock-filters: 31505-3342, 4h.24m
    ublock-privacy: 254-46, 4h.15m
    ublock-quick-fixes: 385-39, 4h.19m
    ublock-unbreak: 1915-101, 4h.29m
    urlhaus-1: 7578-1, 4h.14m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8480 ms (selfie)
  maxAssetCacheWait: 3874 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    iesnare.com: 1
```
</details>

**Comment by liamengland1** [comment]
Spam website
