### ISSUE TITLE
imgsky.net [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1597]
URL(s) where the issue occurs

`http://www.imgsky.net/site/v/3942914#170&3942914`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by mapx-** [comment]
imgsky becomes imgvip and - at least with the link above - I get no popup ?!

**Comment by KiLL4FuNK** [comment]
@mapx-
https://github.com/adsbypasser/adsbypasser/issues/1942

**Comment by mapx-** [comment]
use only uBo - standard setup and test again.

**Comment by KiLL4FuNK** [comment]
open the link of the post this @mapx-
https://github.com/adsbypasser/adsbypasser/issues/1942

**Comment by mapx-** [comment]
it's not clear what do you want: now the url is for another site yet
`fortstore.net`
