### ISSUE TITLE
diziyou.com: breakage

### ISSUE THREAD

**Issue by soyluburkay** [uBlockOrigin/uAssets#15979]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.diziyou.com/modern-family-4-sezon-20-bolum/`

### Category

breakage

### Describe the issue

The video on the webpage is blocked alongside with the ads. Video cannot be viewed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/88089518/206899077-2d0bbdd1-d8f1-4be9-bdf0-a325e4215fc7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 89251
  cosmetic: 47643
  scriptlet: 17832
  html: 864
listset (total-discarded, last-updated): 
  added: 
    TUR-0: 11743-12, 3d.18h.53m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32289-63, 1d.4h.7m
    ublock-badware: 4049-1, 1d.13h.10m
    ublock-privacy: 309-0, 4d.20h.42m
    ublock-abuse: 77-0, 4d.20h.43m
    ublock-unbreak: 1928-2, 1d.4h.6m
    easylist: 65589-630, 4d.14h.51m
    easyprivacy: 30908-1716, 4d.14h.50m
    urlhaus-1: 7193-0, 2h.34m
    plowe-0: 3677-3, 11d.19h.51m
    ublock-quick-fixes: 419-0, 2h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 355 ms (selfie)
  maxAssetCacheWait: 124 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    diziyou.com: 3
    adform.net: 2
    diskstore.xyz: 6
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`||diskstore.xyz^$media,domain=play.diziyou.com,redirect-rule=noopmp3-0.1s`

**Comment by soyluburkay** [comment]
Fixed the issue, thank you!
