### ISSUE TITLE
new.abb.com: breakage

### ISSUE THREAD

**Issue by ornago** [uBlockOrigin/uAssets#15977]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://new.abb.com/smartlinks/de/category-search?9AAC180088`

### Category

breakage

### Describe the issue

Category Search on abb.com not working. Shows "Loading ..." all the time
deactivating "EasyPrivacy" does help to load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/12096794/206896639-67597f52-3d39-4ff3-8937-90ea23347680.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 103334
  cosmetic: 167246
  scriptlet: 24374
  html: 887
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 82496-42849, 6d.23h.46m
    adguard-annoyance: 61650-4322, 6d.23h.49m
    fanboy-cookiemonster: 42660-161, 6d.23h.48m
    ublock-annoyances: 4822-5, 6d.23h.50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32313-40, 6d.23h.52m
    ublock-badware: 4049-1, 6d.23h.51m
    ublock-privacy: 307-0, 6d.23h.54m
    ublock-unbreak: 1924-2, 6d.23h.53m
    easylist: 64996-646, 7d.1m
    easyprivacy: 30936-1750, 7d
    plowe-0: 3675-3, 6d.23h.56m
    DEU-0: 6050-13, 3d.22h.56m
    ublock-abuse: 77-0, 6d.23h.55m
    urlhaus-1: 9450-0, 3d.22h.54m
    ublock-quick-fixes: 408-14, 3d.22h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 917 ms (selfie)
  maxAssetCacheWait: 230 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    abb.com: 1
    d3o3d9viu00ouz.cloudfront.net: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||new.abb.com/ruxitagentjs_$xhr,1p`

@ryanbr
