### ISSUE TITLE
world.taobao.com: breakage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#15974]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://world.taobao.com/`

### Category

breakage

### Describe the issue

Cannot change region with uBlock Origin enabled

Tested with and without AdGuard Chinese enabled. Also tested using EasyList China instead, with and without CJX additions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 86880
  cosmetic: 38783
  scriptlet: 16704
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32303-54, 1m
    ublock-badware: 4163-1, 1m
    ublock-privacy: 301-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1928-2, 1m
    ublock-quick-fixes: 417-0, 1m
    easylist: 64770-611, 1m
    easyprivacy: 30976-1740, 1m
    urlhaus-1: 7193-0, 1m
    plowe-0: 3678-3, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2064 ms
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    alicdn.com: 1
    bing.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    mmstat.com: 16
    unpkg.com: 1
```
</details>

**Comment by cjx82630** [comment]
Try this `@@||taobao.com/cookieController/`  (blocked by Easyprivacy)
