### ISSUE TITLE
ipocentral.in: ads

### ISSUE THREAD

**Issue by N0B0dy99** [uBlockOrigin/uAssets#15978]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ipocentral.in/ipo-discussion/`

### Category

ads

### Describe the issue

![image](https://user-images.githubusercontent.com/120306516/206896947-87d20e09-7053-423b-8883-8a715c38c3c5.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 91741
  cosmetic: 38726
  scriptlet: 16694
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 21-0, never
    ublock-filters: 32292-55, 1d.3h.19m
    ublock-badware: 4153-1, 1d.3h.21m
    ublock-privacy: 309-0, 4d.4h.25m
    ublock-abuse: 77-0, 4d.4h.26m
    ublock-unbreak: 1924-1, 1d.3h.20m
    ublock-quick-fixes: 419-1, 21h.51m
    easylist: 65589-611, 3d.23h.30m
    easyprivacy: 30941-1741, 3d.23h.29m
    urlhaus-1: 11199-0, 21h.50m
    plowe-0: 3678-3, 1d.5h.23m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 44 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 14 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 518 ms (selfie)
  maxAssetCacheWait: 215 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    ipocentral.in: 8
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 2
    googletagmanager.com: 1
    onesignal.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
ipocentral.in##.sgpb-popup-dialog-main-div-wrapper
ipocentral.in##.sgpb-theme-3-overlay
ipocentral.in##.mysticky-welcomebar-fixed
ipocentral.in##.td-banner-wrap-full
```

@ryanbr

**Comment by mapx-** [comment]
wait and on the left side / bottom you'll get other ads + overlay

![image](https://user-images.githubusercontent.com/10303732/206898189-d5268f59-6b19-4da5-92e9-9b66dc3a2c08.png)
