### ISSUE TITLE
smgplaza.com: detection

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#15982]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://smgplaza.com/`

### Category

detection

### Describe the issue

Detect uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Uploading Screenshot_2022-12-11-19-48-47-101_us.spotco.fennec_dos.jpg…]()

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 107
filterset (summary): 
  network: 86304
  cosmetic: 120774
  scriptlet: 21740
  html: 889
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 83511-427, 8d.4h.28m
    ublock-annoyances: 4884-4, 21h.52m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32399-72, 21h.56m
    ublock-badware: 4162-1, 21h.54m
    ublock-privacy: 307-0, 8d.23h.34m
    ublock-abuse: 77-0, 8d.23h.34m
    ublock-unbreak: 1928-2, 21h.53m
    ublock-quick-fixes: 419-0, 3h.35m
    adguard-mobile: 8342-11, 21h.57m
    easylist: 64993-472, 2d.9h.48m
    easyprivacy: 30952-1188, 2d.9h.47m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1600 ms (selfie)
  maxAssetCacheWait: 567 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    arc.io: 2
    googlesyndication.com: 7
```
</details>

**Comment by mapx-** [comment]
provide the original shortener link

**Comment by MayaBi7** [comment]
https://www.deadtoons.net/little-krishna-movies-1-3-2009-hindi-dubbed-download-480p-720p-1080p-hd/

**Comment by MayaBi7** [comment]
https://www.deadtoons.net/little-krishna-movies-1-3-2009-hindi-dubbed-download-480p-720p-1080p-hd/

Click on Mega link

**Comment by MayaBi7** [comment]
👍
