### ISSUE TITLE
[nsfw] ua.bongacams10.com: popups

### ISSUE THREAD

**Issue by NOX0GAME** [uBlockOrigin/uAssets#15980]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://ua.bongacams10.com/?bcs=YmVzdDkwOWNlYWNmOThhMmE5ZGVlNjkxYWJjYjFhZTlkYTgzOjoxOTE4MDA6Ojo6OjpFNEQyS0dCMFU6Ojc3MDcxOTo6MDo6MTo6MTo6OjowOjpkZWZhdWx0Ojow`

### Category

popups

### Describe the issue

> порнуху показывает, мне это нахуй не надо

**shows porn, I don't need it**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок экрана (2074)](https://user-images.githubusercontent.com/120309143/206899349-e5925109-b43c-416c-99c7-24c26f9d5dbe.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 104963
  cosmetic: 59812
  scriptlet: 17913
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39564-11, 1d.18h.15m
    easylist: 65840-66, 2d.19h.39m
    easyprivacy: 30952-1281, 2d.19h.40m
    plowe-0: 3678-905, 1d.22h.17m
    ublock-abuse: 77-1, 4d.17h.16m
    ublock-badware: 4045-110, 3d.18h.38m
    ublock-filters: 31503-149, 3d.18h.36m
    ublock-privacy: 262-1, 4d.17h.17m
    ublock-quick-fixes: 421-14, 4h.54m
    ublock-unbreak: 1913-44, 3d.18h.37m
    urlhaus-1: 7193-0, 4h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1272 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    d31qbv1cthcecs.cloudfront.net: 1
    google.com: 2
    googletagmanager.com: 1
    translate.googleapis.com: 4
```
</details>

**Comment by mapx-** [comment]
Maybe you visited other page and you got a redirection to `bongacams10` ? What page did you visit ?

**Comment by gorhill** [comment]
> - [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

Your screenshot shows you are using ABP, AdBlock and other blockers along with uBO. Do not use other blockers along with uBO, this leads to worse results than uBO alone.
