### ISSUE TITLE
telyn610zoanthropy.com: detection

### ISSUE THREAD

**Issue by DonPhillip** [uBlockOrigin/uAssets#15984]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://telyn610zoanthropy.com/e/i7tjv8ccsp9t`

### Describe the issue

Website gets blocked

### Screenshot(s)

![Screenshot 2022-12-11 at 21-42-46 Watch Dragonball Super S01E02 German AAC 720p BluRay x264-Fuuko mp4 - VOE Content Delivery Network (CDN)   Video Cloud](https://user-images.githubusercontent.com/38314830/206927775-b510a6de-15d0-44fb-9271-ae6185f0dac8.png)

### uBlock Origin version

uBlock Origin 1.45.2

### Browser name and version

Firefox 107.0.1 (64-Bit)

### Settings

Original settings

### Notes

Its time per time blocked.

Thanks you for your Idea and your awesome Ublock app. :-)

**Comment by ghajini** [comment]
update filters, it was fixed a day ago
