### ISSUE TITLE
soap2day.to: popups

### ISSUE THREAD

**Issue by Cellgames11** [uBlockOrigin/uAssets#15988]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soap2day.to/EczoyMToiMTkyODE5fHwxNzIuOTEuMTk4Ljc1Ijs.html`

### Category

Unwanted tabs and windows

### Describe the issue

When I click an episode it opens a new tab that hasn't happened ever before.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 87914
  cosmetic: 38719
  scriptlet: 16699
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65786-52, 3d.22h.44m
    easyprivacy: 30950-1171, 3d.22h.45m
    plowe-0: 3678-900, 21h.4m
    ublock-abuse: 77-0, 4d.5h.42m
    ublock-badware: 4149-110, 3d.22h.41m
    ublock-filters: 31502-115, 3d.22h.42m
    ublock-privacy: 262-1, 4d.5h.43m
    ublock-quick-fixes: 413-14, 23h.40m
    ublock-unbreak: 1911-46, 3d.22h.43m
    urlhaus-1: 7175-0, 1m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 428 ms
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    clksite.com: 1
    d27qffx6rqb3qm.cloudfront.net: 2
    pogothere.xyz: 2
    s3.us-east-1.amazonaws.com: 1
```
</details>

**Comment by ghajini** [comment]
your ublock filters are not up to date,update it
