### ISSUE TITLE
rb.gy: blocked by EasyList

### ISSUE THREAD

**Issue by gregg56** [uBlockOrigin/uAssets#15983]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://rb.gy/oul4uq`

### Describe the issue

The site rb.gy appears to be a form of encoding to make a smaller URL.
The particular rb.gy url I am reporting as an issue actually blocked a conservative web site that I wanted to read.
I have marked rb.gy in my browser for easylist to never block, but felt I should report the entry as a possible issue.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 107.0.1

### Settings

just the one to tell easylist to no longer block rb.gy

**Comment by mapx-** [comment]
`||rb.gy^$badfilter`


@ryanbr

**Comment by mapx-** [comment]
fixed here: https://github.com/easylist/easylist/commit/196d24eb7def1e0c36400e89aa3b6794949a9076
