### ISSUE TITLE
arcadepunks.com: detection

### ISSUE THREAD

**Issue by Rafuten** [uBlockOrigin/uAssets#15981]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.arcadepunks.com/`

### Category

detection

### Describe the issue

Show popup and web not work...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 90966
  cosmetic: 43576
  scriptlet: 16846
  html: 792
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31834-91, never
    ublock-badware: 3947-0, never
    ublock-privacy: 288-0, never
    ublock-abuse: 76-0, never
    ublock-unbreak: 1886-0, never
    ublock-quick-fixes: 430-0, never
    easylist: 62416-683, never
    easyprivacy: 30822-1722, never
    urlhaus-1: 11291-0, never
    plowe-0: 3671-3, never
    spa-0: 3425-1, 4m
    spa-1: 4883-127, 4m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 424 ms
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    arcadepunks.com: 2
    facebook.com: 1
    googlesyndication.com: 5
    truepush.com: 2
```
</details>

**Comment by rihaq** [comment]
Can-t reproduce. Working fine

**Comment by mapx-** [comment]
> never 

- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
