### ISSUE TITLE
gamefound.com: breakage

### ISSUE THREAD

**Issue by Frenoss** [uBlockOrigin/uAssets#15996]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gamefound.com/contact?utm_campaign=gamefound&utm_source=contact_page&utm_medium=email`

### Category

breakage

### Describe the issue

Disclaimers to the first two check boxes in submitting this issue: (a) I don't understand what filters do, so I don't fully understand the filter policy. (b) When I clicked the link to verify if this issue exists, the button on the resulting page did nothing. I don't know if that means there is no pre-existing issue report or I did something wrong.

#### Issue Report

My goal was to submit an issue for a project at gamefound.com. I used the "Contact Us" form, selected a project, and chose as a subject "I have a different question". I described my question in the "Your message" edit box.

When I press the submit button with uBO active, the page shows an error pop-up in the bottom left. It says
Server error:
Invalid reCaptcha token

I disabled uBO, reloaded the form, and then submit worked fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-13 115644](https://user-images.githubusercontent.com/6187622/207431635-649ce3dc-575b-4688-85d7-8b3658ab5d99.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 87448
  cosmetic: 38573
  scriptlet: 16719
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64996-53, 4d.22h.59m
    easyprivacy: 30961-1171, 4d.18h.58m
    plowe-0: 3675-900, 10d.4h.22m
    ublock-abuse: 77-0, 11d.2h.11m
    ublock-badware: 4159-110, 2d.4h.43m
    ublock-filters: 31499-112, 2d.8h.45m
    ublock-privacy: 260-1, 11d.2h.10m
    ublock-quick-fixes: 423-14, 15h.13m
    ublock-unbreak: 1911-46, 2d.8h.44m
    urlhaus-1: 7348-0, 15h.12m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    rollbar.com: 1
```
</details>

**Comment by mapx-** [comment]
I'm unable to reproduce the issue, I tried 4 times even using a vpn but no captcha appears

- update all your filter lists (how to do this: [click "Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click "Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- open uBO logger, repeat the steps to get the issue, go back in the logger page and post here all the blocked requests you get there

**Comment by Frenoss** [comment]
Huh, I'm now seeing it work correctly. Even in the same browser session that had repro'd the problem multiple times earlier after previously updating all filter lists. It's baffling. If it repro's again, I'll be sure to grab the logger information. Thank you for your help looking into this.
