### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by yapiyap9** [uBlockOrigin/uAssets#15991]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

u block origin doesn't block twitch ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 89892
  cosmetic: 47719
  scriptlet: 17822
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11751-11, 1d.3h
    easylist: 65956-72, 20h.47m
    easyprivacy: 30965-1176, 20h.46m
    plowe-0: 3678-902, 20h.45m
    ublock-abuse: 77-0, 20h.43m
    ublock-badware: 4176-109, 20h.41m
    ublock-filters: 31505-124, 20h.40m
    ublock-privacy: 254-1, 20h.39m
    ublock-quick-fixes: 411-14, 20h.38m
    ublock-unbreak: 1915-44, 20h.37m
    urlhaus-1: 7360-0, 20h.36m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 633 ms (selfie)
  maxAssetCacheWait: 353 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 6
    scorecardresearch.com: 15
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
