### ISSUE TITLE
rottentomatoes.com: ads

### ISSUE THREAD

**Issue by azuryst** [uBlockOrigin/uAssets#15995]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.rottentomatoes.com/m/avatar_the_way_of_water
https://www.rottentomatoes.com/m/the_banshees_of_inisherin
```

### Describe the issue

15 sec video ads displaying when clicking on trailers.

### Screenshot(s)

![Screenshot 2022-12-13 at 9 36 34 AM](https://user-images.githubusercontent.com/6332446/207405000-d2582d58-1d1c-477f-b46b-e75a43965eee.jpg)

### Notes

happens in Chrome (108.0.5359.98) with only uBlock Origin 1.45.2 installed.

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 97116
  cosmetic: 156437
  scriptlet: 38634
  html: 929
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24231-71, 2m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42576-1317, 2m
    fanboy-annoyance: 83706-67470, 2m
    fanboy-cookiemonster: 43836-233, 2m
    fanboy-social: 23459-8, 2m
    ublock-annoyances: 4829-4, 2m
  default: 
    user-filters: 224-1, never
    ublock-filters: 32284-2780, 2m
    ublock-badware: 4185-0, 2m
    ublock-privacy: 301-0, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1930-2, 2m
    easylist: 63434-639, 2m
    easyprivacy: 30976-1743, 2m
    urlhaus-1: 7371-0, 2m
    plowe-0: 3678-3, 2m
    ublock-quick-fixes: 457-0, 2m
filterset (user): [array of 224 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1111 ms (selfie)
  maxAssetCacheWait: 374 ms
```
</details>

**Comment by liamengland1** [comment]
Test

`||link.theplatform.com/s/*/media*=rotten_tomatoes_video$xhr,removeparam=/^((?!SMIL|formats).)*$/`

**Comment by mapx-** [comment]
or using one of the new scriptlets

`player.theplatform.com##+js(m3u-prune, tvessaiprod.nbcuni.com, /theplatform\.com\/.*?\.m3u8/)`

but is not sync with the normal timing
