### ISSUE TITLE
helidon.io: breakage

### ISSUE THREAD

**Issue by barchetta** [uBlockOrigin/uAssets#15998]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://helidon.io/docs/v3/#/mp/metrics/metrics`

### Describe the issue

This URL is blocked. The Logger reports it being blocked by this filter:

```
       Filter /metrics/metrics$domain=~docs.datadoghq.com|~spatineo.com
 Filter list [EasyPrivacy](moz-extension://509836de-f861-7a41-8af3-ed727b1132ba/asset-viewer.html?url=easyprivacy)
     Context helidon.io
Partyness(1) helidon.io ⇒ helidon.io
        Type xhr
         URL https://helidon.io/docs/v3/pages/mp/metrics/metrics.js

```

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 102.6.0esr (others have reported it on Chrome)

### Settings

None

**Comment by mapx-** [comment]
What is broken and how to reproduce the issue ?

**Comment by barchetta** [comment]
Go to https://helidon.io/docs/v3/#/mp/metrics/metrics and you will get a blank page if uBlock Origin is enabled. This is because the filter blocks the URL listed above. Turn off uBlock Origin and the page displays.

**Comment by mapx-** [comment]
@ryanbr 

`@@||helidon.io/docs/v3/pages/mp/metrics/metrics.js$xhr,1p`

**Comment by barchetta** [comment]
Note this impacts other pages on our site as well. Anything where the URL contains `metrics/metrics`.  I could give you a list to allow, but that seems pretty brittle.

**Comment by mapx-** [comment]
I guess EP maintainer will craft the filter like this:

`/metrics/metrics$domain=~docs.datadoghq.com|~spatineo.com|~helidon.io`

**Comment by mapx-** [comment]
@barchetta test your pages and if still broken provide the specific page

**Comment by barchetta** [comment]
Still broken. Broken pages:
* https://helidon.io/docs/v3/#/mp/metrics/metrics
* https://helidon.io/docs/v3/#/mp/metrics/metrics-capable-components
* https://helidon.io/docs/v3/#/se/metrics/metrics
* https://helidon.io/docs/v3/#/se/metrics/metrics-capable-components

It looks like the fix updated an allow list which seems fragile. Attaching a screenshot of the logger output:

![ublockorigin-easyprivacy-falsepositive](https://user-images.githubusercontent.com/6116667/207647118-8fe88aef-696a-4708-b579-a60bcb6cf9da.png)

**Comment by mapx-** [comment]
@ryanbr

**Comment by barchetta** [comment]
I have verified that with the latest commit this issue is fixed.
