### ISSUE TITLE
miraculous.lol: popups

### ISSUE THREAD

**Issue by rihaq** [uBlockOrigin/uAssets#15994]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://miraculous.lol/`

### Category

popups

### Describe the issue

*Note* :-  I'm using uBlock origin dev build.
My previous issue about `miraculous.to` is probably caused by ublock dev build. Please test the miraculous.to with ublock dev

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b14
Chromium Mobile: 107
filterset (summary): 
  network: 98976
  cosmetic: 35211
  scriptlet: 33690
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24189-212, 2d.13h.40m
    IND-0: 12053-0, 9h
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8342-28, 2d.13h.45m
    easylist: 66153-17305, 2d.13h.45m
    easyprivacy: 30976-1183, 2d.13h.45m
    plowe-0: 3678-985, 2d.13h.45m
    ublock-abuse: 77-1, 2d.13h.45m
    ublock-badware: 4158-111, 2d.13h.45m
    ublock-filters: 31616-3054, 2d.13h.45m
    ublock-privacy: 254-2, 2d.13h.45m
    ublock-quick-fixes: 387-27, 9h.5m
    ublock-unbreak: 1920-47, 2d.13h.45m
    urlhaus-1: 7191-0, 9h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5321 ms
  maxAssetCacheWait: 2983 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cloudflareinsights.com: 1
    d1p7gp5w97u7t7.cloudfront.net: 2
    github.com: 1
    pogothere.xyz: 2
```
</details>

**Comment by rihaq** [comment]
@mapx- fyi miraculous.to and miraculous.lol are two completely different websites

**Comment by rihaq** [comment]
@bogachenko

**Comment by rihaq** [comment]
After updating uBlock dev build I'm getting no error in kiwi browser. I requested volunteer to check my settings which version I use next time thank you. Luckily I donxt need to disable FFA

**Comment by mapx-** [comment]
FFA is completely useless when you use uBO.
