### ISSUE TITLE
Content blocked on edition.cnn.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#160]
Content blocked under the "Featured Sections" tab on _edition.cnn.com_

**Before adblock:** http://i.imgur.com/hqZR1S4.png
**After adblock:** http://i.imgur.com/mCTirAN.png

**Error URL:** http://edition.cnn.com/

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
Sorry, thought I was on uBO's repo.

Did you investigate with the logger to find why this occur?

**Comment by gorhill** [comment]
How about:

    edition.cnn.com##.column:has(.OUTBRAIN)
    edition.cnn.com##.column:has([data-analytics^="Paid Partner Content"])

**Comment by okiehsch** [comment]
This filterset just "deletes" the Featured Sections Sport, Travel etc.

Without filterset
![aufzeichnn](https://cloud.githubusercontent.com/assets/16838044/19325785/079fa86a-90c8-11e6-8fa4-2056c2bd94fc.JPG)

With filterset
![aufzen](https://cloud.githubusercontent.com/assets/16838044/19325813/25b8532e-90c8-11e6-8730-988180eb84e2.JPG)

**Comment by gorhill** [comment]
> This filterset just "deletes" the Featured Sections Sport, Travel etc.

This is Outbrain-driven content, not unlike Taboola. Open the logger and click on a link, it won't directly load what is shown in the status bar -- which is misleading, it goes through `outbrain.com` server first, then comes back to `cnn.com`. Ostensibly, the only purpose of Outbrain-related items in that section is to click-bait people.

**Comment by okiehsch** [comment]
Agreed, seems to be a click-bait section.
So the issue "Content blocked on edition.cnn.com" actually was no issue at all,
but the way it should be and your filterset only improves the blocking.

**Comment by gorhill** [comment]
Well, after browsing the site a bit more and out of prudence, I will go with `cnn.com##.OUTBRAIN`: Outbrain is still foiled, and I rather have empty placeholders in there than unexpectedly create false positives elsewhere on such a large site as CNN. The orphan headers are still useful to visit the respective section of the site.
