### ISSUE TITLE
eu4.paradoxwikis.com: breakage

### ISSUE THREAD

**Issue by jufcar** [uBlockOrigin/uAssets#16007]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eu4.paradoxwikis.com/Europa_Universalis_4_Wiki`

### Category

breakage

### Describe the issue

accessing the site from the EU, the site creates an overlay with the cookie settings etc.
As long as the overlay is active, there is no scrollbar.
uBO blocks the overlay correctly, unfortunatly doing so prevents "loading" the scroll bar or scrolling in general.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 102508
  cosmetic: 186058
  scriptlet: 24475
  html: 888
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4829-4, now
    adguard-annoyance: 62196-4686, now
    adguard-social: 19445-1073, now
    fanboy-thirdparty_social: 68-0, now
    fanboy-annoyance: 83710-67962, now
    fanboy-cookiemonster: 43836-240, now
    fanboy-social: 23460-28, now
  default: 
    user-filters: 17-2, never
    ublock-filters: 32288-70, now
    ublock-badware: 4191-0, now
    ublock-privacy: 301-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1928-1, now
    easylist: 63023-638, now
    easyprivacy: 30982-1756, now
    plowe-0: 3678-3, now
    DEU-0: 6060-2, now
    urlhaus-1: 9993-0, now
    ublock-quick-fixes: 480-1, now
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 539 ms (selfie)
  maxAssetCacheWait: 664 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    appboycdn.com: 1
    googletagmanager.com: 2
    licensebuttons.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`paradoxwikis.com##body:style(overflow: auto !important;)`

@ryanbr 
@Yuki2718  for AG annoyances
