### ISSUE TITLE
z83z9.com: popups

### ISSUE THREAD

**Issue by 0Paradox-dev** [uBlockOrigin/uAssets#16000]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://z83z9.com/titles/4821-siren/stagione-2`

### Category

popups

### Describe the issue

The sites is going to re-charge the tab into a new page.
it will happened every time you are going to open any of the listed image of streaming.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 93225
  cosmetic: 46150
  scriptlet: 16705
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32284-65, 7m
    ublock-badware: 4185-0, 6m
    ublock-privacy: 308-0, 9d.27m
    ublock-abuse: 77-0, 9d.26m
    ublock-unbreak: 1930-2, 8m
    ublock-quick-fixes: 452-0, 3h.5m
    easylist: 64996-614, 3d.3h.13m
    easyprivacy: 30976-1741, 3d.3h.12m
    urlhaus-1: 7371-0, 3h.3m
    plowe-0: 3676-3, 8d.3h.25m
    ITA-0: 13281-1, 3h.6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 919 ms
  maxAssetCacheWait: 348 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    d13vul5n9pqibl.cloudfront.net: 1
    doubleclick.net: 2
    googletagmanager.com: 1
    scws-content.net: 1
    wpadmngr.com: 1
    yadro.ru: 1
    youtube.com: 5
```
</details>

**Comment by mapx-** [comment]
fake movies site ?

**Comment by mapx-** [comment]
@0Paradox-dev 
Did you ever see a movie on this site ?
