### ISSUE TITLE
iumkit.net: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16009]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.iumkit.net/portail/deployment-ium-kit/telechargement-ium/telecharger-deployment-ium-kit/`

### Category

detection

### Describe the issue

The site detects the ad blocker and prevents the software from downloading.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/207656878-44a67b12-2d40-4f41-a164-9ba072e25d2e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 107924
  cosmetic: 87751
  scriptlet: 18602
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43836-200, 23h.20m
  default: 
    user-filters: 0-0, never
    FRA-0: 30666-28, 23h.21m
    easylist: 63434-190, 23h.20m
    easyprivacy: 30976-1557, 23h.20m
    plowe-0: 3678-925, 23h.20m
    ublock-abuse: 77-1, 23h.20m
    ublock-badware: 4181-127, 23h.20m
    ublock-filters: 31494-238, 23h.20m
    ublock-privacy: 254-1, 23h.20m
    ublock-quick-fixes: 451-17, 23h.20m
    ublock-unbreak: 1917-46, 23h.20m
    urlhaus-1: 7371-0, 23h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 211 ms (selfie)
  maxAssetCacheWait: 117 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    iumkit.net: 1
    doubleclick.net: 2
    googlesyndication.com: 2
    translate.googleapis.com: 1
    twitter.com: 1
    youtube.com: 5
```
</details>

**Comment by mapx-** [comment]
> prevents the software from downloading

You have to provide the original link

**Comment by mapx-** [comment]
I'm able to defeat the anti adb with shields ON only adding as custom filter in brave:

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=iumkit.net`

with shields OFF I get no anti adb

**Comment by mapx-** [comment]
in brave you can add a filter going to
brave://settings/shields/filters


then add the filter in the last section `Create custom filters`
then click `Save changes`
