### ISSUE TITLE
deliveroo.co.uk: ads

### ISSUE THREAD

**Issue by dl0096** [uBlockOrigin/uAssets#16008]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://deliveroo.co.uk/orders/1485117356/status`

### Category

ads

### Describe the issue

one ad on the order tracking page
https://imgur.com/a/KwE517h

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://imgur.com/a/KwE517h

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88417
  cosmetic: 38800
  scriptlet: 16716
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32293-54, 3d.19h.31m
    ublock-badware: 4153-1, 3d.19h.14m
    ublock-privacy: 301-0, 1d.8h.17m
    ublock-abuse: 77-0, 1d.8h.16m
    ublock-unbreak: 1924-2, 3d.19h.13m
    ublock-quick-fixes: 452-0, 19h.54m
    easylist: 66153-613, 3d.19h.49m
    easyprivacy: 30976-1742, 3d.19h.50m
    urlhaus-1: 7371-0, 19h.53m
    plowe-0: 3675-3, 12d.49m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 693 ms (selfie)
  maxAssetCacheWait: 101 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    deliveroo.co.uk: 2
    deliveroo.com: 2
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
Use the element picker and try to create a filter
