### ISSUE TITLE
macupload.net [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1600]
URL(s) where the issue occurs

`https://macupload.net/6oi`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
@mapx- Pop-up

**Comment by okiehsch** [comment]
This will not work, the site validates the timer on the server side, you can see for yourself, after you add your filter and click "download" before 15 seconds have passed, the site will simply reload.

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script (soft, 5-10 sec countdown)

![image](https://user-images.githubusercontent.com/24980766/62339379-d48d1800-b4a9-11e9-9a15-520cc0fedafe.png)

**Comment by okiehsch** [comment]
`https://macupload.net/6oi`
I get the message after every reload, so it is more than annoying and will be fixed in `uBO-filters`.
