### ISSUE TITLE
okezone.com: nuisance

### ISSUE THREAD

**Issue by YellowStar11** [uBlockOrigin/uAssets#16015]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bola.okezone.com/read/2022/12/14/51/2726817/5-negara-yang-iri-jika-argentina-juara-piala-dunia-2022-nomor-1-sang-musuh-bebuyutan`

### Describe the issue

Annoying Social media buttons

### Screenshot(s)

https://user-images.githubusercontent.com/98148960/207748831-70809bd1-c416-4590-959c-dde90506be8d.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 107
filterset (summary): 
  network: 99140
  cosmetic: 101059
  scriptlet: 23733
  html: 889
listset (total-discarded, last-updated): 
  removed: 
    IDN-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7713-1866, never
    adguard-spyware-url: 862-3, 1h.15m
    adguard-annoyance: 62213-3268, 1h.15m
    adguard-social: 19447-1139, 1h.15m
    ublock-annoyances: 4886-7, 1h.15m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32377-307, 1h.15m
    ublock-badware: 4190-0, 1h.15m
    ublock-privacy: 301-1, 23h.2m
    ublock-abuse: 77-0, 23h.1m
    ublock-unbreak: 1934-3, 1h.15m
    ublock-quick-fixes: 484-0, 1h.15m
    adguard-mobile: 8353-167, 23h.1m
    easylist: 63823-17801, 1d.19h.32m
    easyprivacy: 30974-1751, 1d.19h.11m
    urlhaus-1: 9993-0, 1h.14m
    plowe-0: 3678-3, 13h.24m
filterset (user): [empty]
modifiedUserSettings: 
  largeMediaSize: 15000
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2238 ms
  maxAssetCacheWait: 1188 ms
```
</details>

**Comment by krystian3w** [comment]
Try AdGuard social media filter or Fanboy Social.

**Comment by YellowStar11** [comment]
> Try AdGuard social media filter or Fanboy's Social.
> 
> ![Screenshot_2022-12-15-04-16-43-292-edit_org mozilla firefox_beta](https://user-images.githubusercontent.com/35370833/207764404-9d49b1c7-0cf3-44de-9d9d-0f1f9e3318c4.jpg)

Adguard social

**Comment by krystian3w** [comment]
@Yuki2718 fyi.

**Comment by mapx-** [comment]
@YellowStar11 the social lists already work.
Be sure you didn't select `Ignore generic cosmetic filters`

If does not work reinstall uBO

**Comment by krystian3w** [comment]
You chcecked AMP layout too?

**Comment by Yuki2718** [comment]
He uses Firefox Mobile so Ignore generic cosmetic filters is off by default. Anyway I see social leftover even on AG, will address.

**Comment by krystian3w** [comment]
I guess not:
```yml
cosmetic: 101059
```

But on my phone is 122 k (someone write 19 k filters in 24h?).
