### ISSUE TITLE
tv8.com.tr: detection

### ISSUE THREAD

**Issue by edizarca** [uBlockOrigin/uAssets#16010]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tv8.com.tr/masterchef-turkiye/masterchef-turkiye-12-aralik-2022-1-part-133357-video.htm`

### Category

detection

### Describe the issue

detects ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88144
  cosmetic: 38737
  scriptlet: 16685
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32285-63, 4d.7h.44m
    ublock-badware: 4049-1, 4d.7h.43m
    ublock-privacy: 301-0, 3d.6h.34m
    ublock-abuse: 77-0, 3d.6h.33m
    ublock-unbreak: 1928-2, 3d.20h.42m
    ublock-quick-fixes: 398-0, 1d.45m
    easylist: 65956-612, 3d.5h.55m
    easyprivacy: 30976-1740, 3d.5h.54m
    urlhaus-1: 7371-0, 1d.44m
    plowe-0: 3678-3, 2d.1h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2242 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
test

`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=tv8.com.tr,redirect-rule=noopjs`

I have no working turkish vpn and I get "unavailable", the anti adb is gone

@Yuki2718 for turkish list

**Comment by mapx-** [comment]
the redirect filter does not work, needing:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=tv8.com.tr`

**Comment by Yuki2718** [comment]
Hmm, on AG `tv8.com.tr#%#//scriptlet("prevent-fab-3.2.0")` is working but on uBO the same rule in Base `
tv8.com.tr##+js(nofab)` causes blank player. @gorhill

**Comment by gorhill** [comment]
I won't be able to investigate this, I don't have a VPN for Turkey.

**Comment by Yuki2718** [comment]
@gwarser Do you?

**Comment by mapx-** [comment]
@gorhill you don't need a vpn

using
`tv8.com.tr##+js(nofab)`

in console I get this error (as a consequence of `nofab`) => breaking the player

![image](https://user-images.githubusercontent.com/10303732/207930367-d31740d0-35b2-4686-a7df-1471b6e2a208.png)

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/207931491-f63795b2-4f78-4b9e-8340-2e03f4143933.png)

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/nofab.js
missing 

```
    Fab.prototype.options = {
        set: noopFunc,
        get: noopFunc,
    };
```

**Comment by gorhill** [comment]
> you don't need a vpn

Ok, I compared [`prevent-fab-3.2.0`](https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/prevent-fab-3.2.0.js) with [`nofab.js`](https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/nofab.js), and it seems `prevent-fab-3.2.0` is based on `nofab.js`, except for [one improvement](https://github.com/AdguardTeam/Scriptlets/commit/3bfb9b39e96b13d9457856d073c3a39088f0f05e) which wasn't contributed back to the original code.

**Comment by mapx-** [comment]
yes, working now
