### ISSUE TITLE
cybersport.metaratings.ru: ads

### ISSUE THREAD

**Issue by NeXProgger** [uBlockOrigin/uAssets#16018]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cybersport.metaratings.ru/cheats/chity-dlya-crusader-kings-3/`

### Category

ads

### Describe the issue

The site displays `фвы` for online casinos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://user-images.githubusercontent.com/86261298/207865190-c6b58bb6-2fab-47e4-9abc-bf37c6bcd723.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 107983
  cosmetic: 59850
  scriptlet: 17994
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 32313-86, 4h.36m
    ublock-badware: 4191-0, 4h.35m
    ublock-privacy: 307-0, 4h.37m
    ublock-abuse: 77-0, 4h.33m
    ublock-unbreak: 1929-2, 4h.32m
    ublock-quick-fixes: 480-0, 23h.9m
    easylist: 65956-648, 4d.7h.3m
    easyprivacy: 30976-1850, 4d.7h.4m
    urlhaus-1: 9993-0, 23h.10m
    plowe-0: 3675-3, 11d.5h.10m
    RUS-0: 39581-18, 4h.34m
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 460 ms (selfie)
  maxAssetCacheWait: 293 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/d6330a1b5ce37207a1c50131b0ef226c55462265
