### ISSUE TITLE
Adblock detection box - motorsport.com

### ISSUE THREAD

**Issue by adamgibbo** [uBlockOrigin/uAssets#16013]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.motorsport.com/f1/news/ford-linked-return-red-bull-2026/10411381/`

### Describe the issue

Big adblock detection box. Appears to be any news article from motorsport.com

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52538290/207721018-ca062454-0c89-4fe1-8e89-5f62297fe3ad.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3rc1
Firefox: 108
filterset (summary): 
  network: 95338
  cosmetic: 114611
  scriptlet: 21704
  html: 888
listset (total-discarded, last-updated): 
  added: 
    block-lan: 44-0, 4h.15m
    fanboy-annoyance: 83752-451, 4h.15m
    ublock-annoyances: 4829-4, 4h.15m
  default: 
    user-filters: 7-0, never
    ublock-filters: 32287-60, 4h.15m
    ublock-badware: 4191-0, 4h.15m
    ublock-privacy: 301-0, 4h.15m
    ublock-abuse: 77-0, 4h.15m
    ublock-unbreak: 1929-2, 4h.15m
    ublock-quick-fixes: 480-0, 4h.15m
    easylist: 63024-610, 4h.15m
    easyprivacy: 30983-1739, 4h.15m
    urlhaus-1: 9993-0, 4h.15m
    plowe-0: 3678-3, 4h.15m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 328 ms (selfie)
  maxAssetCacheWait: 337 ms
```
</details>

**Comment by mapx-** [comment]
it was fixed 1 h ago

https://github.com/uBlockOrigin/uAssets/commit/49644869ffddc3058f0f2d43c030ab3c3c33b1e4

**Comment by Marko-98** [comment]
Recently, I started getting this.

https://github.com/user-attachments/assets/b673d471-9938-48f1-93db-87c5513c9873
