### ISSUE TITLE
kolompc.com: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16017]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://kolompc.com/ratiborus-kms-tools/`

### Category

nuisance

### Describe the issue

Fake download buttons.

### Screenshot(s)

Fake download buttons.

![image](https://user-images.githubusercontent.com/50231020/207841711-cda37716-1fca-4895-9b8a-9eea3c404e98.png)

![image](https://user-images.githubusercontent.com/50231020/207841739-52daa09d-0dc9-4784-80dd-a7388268456c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 110157
  cosmetic: 87591
  scriptlet: 18605
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43834-200, 14h.28m
  default: 
    user-filters: 0-0, never
    FRA-0: 30515-28, 14h.28m
    easylist: 63024-199, 14h.28m
    easyprivacy: 30983-1557, 14h.28m
    plowe-0: 3679-925, 14h.28m
    ublock-abuse: 77-1, 14h.28m
    ublock-badware: 4187-126, 14h.28m
    ublock-filters: 31476-235, 14h.28m
    ublock-privacy: 254-1, 14h.28m
    ublock-quick-fixes: 478-18, 14h.28m
    ublock-unbreak: 1916-46, 14h.28m
    urlhaus-1: 9993-0, 14h.28m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 168 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    wp.com: 1
```
</details>

**Comment by iam-py-test** [comment]
I would **strongly** recommend you stay away from this website:
https://www.virustotal.com/gui/url/b59a0ed32806750b4db8e9a4712a89110b37dbcee6cda7122834d6eb69a46977/detection
https://sitecheck.sucuri.net/results/https/kolompc.com
The download pages look like a typical malware download website and the file downloaded from those download buttons is a RAR containing an exe filled with zeros (with zeros removed).
Clearly, I could be wrong, but either way, this site seems to be a bit suspicious.

**Comment by mapx-** [comment]
add

`kolompc.com##[href="javascript:void(0);"][onclick]`

and be careful to @iam-py-test warning

**Comment by krystian3w** [comment]
AdGuard idea:

https://github.com/AdguardTeam/AdguardFilters/commit/f409d5b83175553ea44fd517dc3e28a76f9af174
https://github.com/AdguardTeam/AdguardFilters/commit/98a3832d9293cca50c49ab4c4a879e30943f7733
https://github.com/AdguardTeam/AdguardFilters/commit/fd80c36e0f82cb94e5793eda438bfc142b8aa65e

**Comment by mapx-** [comment]
@ryanbr

**Comment by iam-py-test** [comment]
@x-R0b0T-x You need to put it into the "My filters tab" ([docs](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)):
![image](https://user-images.githubusercontent.com/84232764/209687456-6f8638a4-51b4-41cb-91d8-05cb7277b755.png)
We need your input to be able to fix this issue. The filter provided shouldn't be problematic (@MasterKia knows what they are doing) and you can delete it once you confirm it does/doesn't fix the issue.

**Comment by mapx-** [comment]
@x-R0b0T-x these simple issues (not anti adblocking, not popups, not extended uBO syntax) have to be reported to easylist
