### ISSUE TITLE
relibrary.com: spam

### ISSUE THREAD

**Issue by firefoxlover** [uBlockOrigin/uAssets#16012]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://www.relibrary.com
https://www.relibrary.com/best-libreboot-laptop/
```

### Describe the issue

The second website is full of crap, so it should be considered spam and be blocked. This is obviously written by a bot, as a M1 Macbook with Libreboot makes no sense at all.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox 108.0

### Settings

installed more filterlists

**Comment by mapx-** [comment]
- I get no obvious threat
- to be or not to be a spam page it's an interpretable matter, we have no dedicated spam list

@ryan what do you think about ?
