### ISSUE TITLE
yallo.tv: detection & ads

### ISSUE THREAD

**Issue by etwasch** [uBlockOrigin/uAssets#16014]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yallo.tv/`

### Describe the issue

when a channel is selected uBlock is detected, popup.
when the popup is removed with the zapper or a filter, channels seem to load but stop immediately.
without uBlock many ads. 

### uBlock Origin version

1.45.2

### Browser name and version

Chrome 108 / Firefox 108

### Settings

none

### Notes

yallo.tv was wilmaa.com (redirects now) and the code and tech seems to be mostly identical.
On wilmaa uBlock worked perfectly.

**Comment by mapx-** [comment]
Test

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=yallo.tv
@@||api.production.k8s.y3o.tv/nevarro/video-ads/cinema-channel/$xhr,domain=yallo.tv
```

**Comment by etwasch** [comment]
> Test
> 
> ```
> @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=yallo.tv
> @@||api.production.k8s.y3o.tv/nevarro/video-ads/cinema-channel/$xhr,domain=yallo.tv
> ```
Still the same popup, unfortunately.

**Comment by mapx-** [comment]
I get no anti adb using the filters above.
Do I need an account ? testing "Live TV" ?

**Comment by etwasch** [comment]
> I get no anti adb using the filters above. Do I need an account ? testing "Live TV" ?

Yes, Live TV. Account should not be required, it's the same with an account except one can reorganize channels.

**Comment by mapx-** [comment]
Use only the default filter lists, disable any other extension, disable builtin blockers (shields in brave for example), tracking protection etc

**Comment by etwasch** [comment]
> Use only the default filter lists, disable any other extension, disable builtin blockers (shields in brave for example), tracking protection etc

vanilla chrome or firefox on new user account on mac, only uBlock installed...

**Comment by mapx-** [comment]
open uBO logger, repeat the steps to get the anti adblock, go back in the logger, post here all the blocked requests you see there
(for firefox did you disable ETP ?)

**Comment by etwasch** [comment]
> open uBO logger, repeat the steps to get the anti adblock, go back in the logger, post here all the blocked requests you see there
<img width="1920" alt="Bildschirmfoto 2022-12-15 um 08 51 30" src="https://user-images.githubusercontent.com/15729562/207803945-e0960358-69f0-4d20-a1e6-64ee2ad7cc51.png">

> (for firefox did you disable ETP ?)
no difference

**Comment by mapx-** [comment]
Does this help ?

`@@||api.production.k8s.y3o.tv/*/video-ads$xhr,domain=yallo.tv`

**Comment by etwasch** [comment]
> @@||api.production.k8s.y3o.tv/*/video-ads$xhr,domain=yallo.tv

you magnificent human, you did it, thank you!

**Comment by etwasch** [comment]
@mapx- 
> Does this help ?
> `@@||api.production.k8s.y3o.tv/*/video-ads$xhr,domain=yallo.tv`

Since a few days this doesn't work anymore.
Here is the new log, can you help again?
<img width="1920" alt="Bildschirmfoto 2023-07-30 um 00 02 12" src="https://github.com/uBlockOrigin/uAssets/assets/15729562/7f3f83f4-e393-484c-ab0f-a892640b5e1c">

**Comment by etwasch** [comment]
I saw the new commit, but I have no idea what it's supposed to do and it doesn't work:
`yallo.tv##+js(no-xhr-if, video-ads/tracking)`

Btw, these two lines are outdated because wilmaa.com doesn't exist anymore:
```
wilmaa.com##+js(set, wlm.adsNotBlocked, true)
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=wilmaa.com
```

**Comment by stephenhawk8054** [comment]
@etwasch Does this filter work?

```adb
||adservice.google.com^$script,redirect-rule=noopjs,domain=yallo.tv
```

**Comment by etwasch** [comment]
> @etwasch Does this filter work?
> 
> ```
> ||adservice.google.com^$script,redirect-rule=noopjs,domain=yallo.tv
> ```
@stephenhawk8054 Yes! Thank you!
I wish I could do this by myself and contribute, too...

**Comment by etwasch** [comment]
It's broken again, "Please deactivate your ad blocker" popup appears.
Here is the Log:
<img width="1920" alt="Bildschirmfoto 2023-09-09 um 16 41 47" src="https://github.com/uBlockOrigin/uAssets/assets/15729562/4d99a014-25c3-4572-92e5-db3aa53012a7">

**Comment by mapx-** [comment]
@etwasch 

test
`@@||ingest.sentry.io/api/$xhr,domain=yallo.tv`

**Comment by etwasch** [comment]
> test
> `@@||ingest.sentry.io/api/$xhr,domain=yallo.tv`

Thanks, but doesn't work

**Comment by mapx-** [comment]
repeat the test and be sure you paste here all the blocked items in the logger (repeat 2-3 times the test keeping the logger opened)

**Comment by etwasch** [comment]
Only repeating entries after that:
<img width="1920" alt="Bildschirmfoto 2023-09-10 um 17 31 28" src="https://github.com/uBlockOrigin/uAssets/assets/15729562/4ad6198c-001b-428b-b4a4-2d431613673c">

**Comment by mapx-** [comment]
there are new requests

Test

`||s0.2mdn.net/instream/video/client.js$script,redirect=noopjs,domain=yallo.tv`

if soes not work

try
`@@||s0.2mdn.net/instream/video/client.js$script,domain=yallo.tv`

**Comment by etwasch** [comment]
> Test
> `||s0.2mdn.net/instream/video/client.js$script,redirect=noopjs,domain=yallo.tv`
> 
> if does not work
> try `@@||s0.2mdn.net/instream/video/client.js$script,domain=yallo.tv`

Both don't work.

**Comment by mapx-** [comment]
test 1 by 1

`*$script,redirect=noopjs,domain=yallo.tv`

`@@||pagead2.googlesyndication.com^$script,domain=yallo.tv`

still does not work => combine with the others above

**Comment by etwasch** [comment]
> `*$script,redirect=noopjs,domain=yallo.tv`

This renders the page non-functional.

> `@@||pagead2.googlesyndication.com^$script,domain=yallo.tv`

Doesn't work.

> still does not work => combine with the others above

@@||ingest.sentry.io/api/$xhr,domain=yallo.tv
||s0.2mdn.net/instream/video/client.js$script,redirect=noopjs,domain=yallo.tv
@@||s0.2mdn.net/instream/video/client.js$script,domain=yallo.tv
@@||pagead2.googlesyndication.com^$script,domain=yallo.tv

No combination of these work.
Log with the 4 rules enabled:

<img width="1920" alt="Bildschirmfoto 2023-09-10 um 18 12 06" src="https://github.com/uBlockOrigin/uAssets/assets/15729562/fad98dd1-5cfa-42ae-9ba3-69d106c9ccd2">

**Comment by mapx-** [comment]
replace the filter above by (it was an error)

`*$script,redirect-rule=noopjs,domain=yallo.tv`

**Comment by etwasch** [comment]
> replace the filter above by (it was an error)
> `*$script,redirect-rule=noopjs,domain=yallo.tv`

Page is usable but ad blocker popup still appears.

**Comment by mapx-** [comment]
follow all these indications, then - if still detection - try again the filters above

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
@@||secure.adnxs.com/ptv$xhr,domain=imasdk.googleapis.com
```

**Comment by jacobgelling** [comment]
I investigated and found this works (allows video playback, no ads and no adblock blocker popup).
```@@||secure.adnxs.com/ptv$xhr,domain=imasdk.googleapis.com```
Would like to know if someone knows how to limit this to only apply on ```yallo.tv```, as I don't know if this has any side effects.

**Comment by mapx-** [comment]
@jacobgelling did you test the filter above too ?
`imasdk.googleapis.com##+js(no-xhr-if, adnxs)`

**Comment by jacobgelling** [comment]
> @jacobgelling did you test the filter above too ? `imasdk.googleapis.com##+js(no-xhr-if, adnxs)`

Yes, it doesn't work  - causes the anti adblocker popup that prevents playback.

**Comment by stephenhawk8054** [comment]
@jacobgelling Does the anti-adb occur if you use these 2 filters?

```adb
@@||secure.adnxs.com/ptv$xhr,domain=imasdk.googleapis.com
imasdk.googleapis.com##+js(xml-prune, VAST, , adnxs)
```

**Comment by jacobgelling** [comment]
That seems to work fine for me.
