### ISSUE TITLE
open.spotify.com: popups

### ISSUE THREAD

**Issue by mmd2722** [uBlockOrigin/uAssets#16021]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://open.spotify.com/`

### Category

popups

### Describe the issue

1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 88427
  cosmetic: 38317
  scriptlet: 16587
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 62416-53, never
    easyprivacy: 30822-1170, never
    plowe-0: 3671-868, never
    ublock-abuse: 76-0, never
    ublock-badware: 3943-103, never
    ublock-filters: 31097-150, never
    ublock-privacy: 260-0, never
    ublock-quick-fixes: 424-0, never
    ublock-unbreak: 1873-42, never
    urlhaus-1: 11291-0, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1518 ms
  maxAssetCacheWait: 23 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    google.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 14
    spotifycdn.com: 1
```
</details>

**Comment by liamengland1** [comment]
Spam issue, there are no popups on spotify, also user did not read the checklist
