### ISSUE TITLE
spcs.news: ads

### ISSUE THREAD

**Issue by ssdhub** [uBlockOrigin/uAssets#16025]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://spcs.news/sz/
https://spcs.news/sz/programmy/?Link_id=609277
https://spcs.news/blogs/channels/

и так далее (etc.)
```

### Describe the issue

> Везде реклама. 
Постоянно меняют домены и постоянно заново реклама 

**There are ads everywhere.
Constantly changing domains and constantly re-advertising**

### Screenshot(s)

https://user-images.githubusercontent.com/74662798/208066502-de847b89-eded-4b10-9607-31e1efbdbcb9.png
https://user-images.githubusercontent.com/74662798/208066514-b82c7998-d041-4f25-b55c-7584ace8b1d8.png
https://user-images.githubusercontent.com/74662798/208066516-021600a4-3b08-43df-af5e-4b591d51b988.png

https://user-images.githubusercontent.com/74662798/208068976-2a89bdf7-f7db-41f6-8121-b92d796658b7.png
https://user-images.githubusercontent.com/74662798/208068980-e95589a2-723e-406d-93cb-bbbfab329b02.png
https://user-images.githubusercontent.com/74662798/208068989-0903c077-7bba-495b-a850-7f39d1f8c910.png

### Notes

> Вручную блокировал, появляется заново.
Много раз блокировал - не блокирует 

**Manually blocked, reappears.
Blocked many times - does not block**

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 80
filterset (summary): 
  network: 105087
  cosmetic: 60014
  scriptlet: 17933
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 229-2, never
    RUS-0: 39567-11, 16h.10m
    easylist: 63124-65, 17h.2m
    easyprivacy: 30908-1284, 17h.3m
    plowe-0: 3678-877, 2d.20h.16m
    ublock-abuse: 77-1, 8d.22h.23m
    ublock-badware: 4181-108, 1d.15h.54m
    ublock-filters: 31498-146, 1d.15h.52m
    ublock-privacy: 260-1, 8d.22h.22m
    ublock-quick-fixes: 474-18, 12h.8m
    ublock-unbreak: 1911-46, 1d.15h.53m
    urlhaus-1: 9864-0, 12h.9m
filterset (user): [array of 229 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1833 ms (selfie)
  maxAssetCacheWait: 695 ms
```
</details>

**Comment by ssdhub** [comment]
Еще добавлю скрины 
![2022-12-16 13-34-27](https://user-images.githubusercontent.com/74662798/208068649-07edbe21-b93c-4ad6-a0a5-64eeea3fd312.png)
![2022-12-16 13-33-29](https://user-images.githubusercontent.com/74662798/208068657-b1b61416-2cf6-4741-8fa4-ee1b23f52ca3.png)
![2022-12-16 13-33-56](https://user-images.githubusercontent.com/74662798/208068658-37055eae-7771-4dcc-86c2-dbc98614c592.png)

**Comment by dimisa-RUAdList** [comment]
This is a new mirror. Ok: https://github.com/easylist/ruadlist/commit/9dd7e206a5ff7ba579c07f93c6a885aed912e04d

**Comment by ssdhub** [comment]
Спасибо. Теперь всё хорошо. Реклама пропала. ( Thank you. It's all good now. The ads are gone. )
