### ISSUE TITLE
eldorado.ua: breakage

### ISSUE THREAD

**Issue by ksufinski** [uBlockOrigin/uAssets#16022]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://eldorado.ua/`

### Category

breakage

### Describe the issue

Recommendation block is not present due to block of `https://statics.esputnik.com/scripts/EA02DD1D633F46AE996E1232F1F04EE5.js`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![eldorado-without-uBlock](https://user-images.githubusercontent.com/11694954/207941445-bd429d69-0751-42e5-be1f-3b8c6b06a801.png)

![eldorado-with-uBlock](https://user-images.githubusercontent.com/11694954/207941468-2fdc5b90-0be0-43bd-9a4f-8a58c71ee1d5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 90128
  cosmetic: 38597
  scriptlet: 16711
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    easylist: 64996-53, 22h.51m
    easyprivacy: 30952-1171, 6d.22h.16m
    plowe-0: 3677-900, 8d.1h.33m
    ublock-abuse: 77-0, 10d.16h.1m
    ublock-badware: 4181-109, 22h.50m
    ublock-filters: 31496-112, 22h.49m
    ublock-privacy: 260-1, 10d.16h
    ublock-quick-fixes: 451-17, 22h.47m
    ublock-unbreak: 1917-44, 22h.48m
    urlhaus-1: 9993-0, 22h.46m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 33 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 90 ms (selfie)
  maxAssetCacheWait: 57 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    esputnik.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
