### ISSUE TITLE
fc-lc.com: detection

### ISSUE THREAD

**Issue by Li-t23** [uBlockOrigin/uAssets#16029]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fc-lc.com/`

### Category

detection

### Describe the issue

Detects UBlock Origen

### Screenshot(s)

<details>
<summary>![image](https://user-images.githubusercontent.com/993146/208216820-ae9f6b87-1411-4f9b-99b0-16baac2f9264.png)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 86145
  cosmetic: 38911
  scriptlet: 16702
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62168-52, 2m
    easyprivacy: 30998-1171, 2m
    plowe-0: 3670-902, 2m
    ublock-abuse: 77-0, 2m
    ublock-badware: 4187-108, 2m
    ublock-filters: 31491-113, 2m
    ublock-privacy: 254-1, 2m
    ublock-quick-fixes: 486-14, 2m
    ublock-unbreak: 1915-44, 2m
    urlhaus-1: 9080-0, 2m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 463 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    fc.lc: 3
    forfrogadiertor.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    gyazo.com: 1
    iclickcdn.com: 1
    nanesbewail.com: 1
    oaphoace.net: 1
```
</details>

**Comment by mapx-** [comment]
You didn't provide a specific test link.

I tested using `https://fc-lc.com/MsZzLq`

No issue on my end.

- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
