### ISSUE TITLE
thevideo.me changes domains to .cc

### ISSUE THREAD

**Issue by AllForNone** [uBlockOrigin/uAssets#1602]
### URL(s) where the issue occurs

`https://thevideo.cc/5yedzglaf3kk`

### Describe the issue

It's another domain change; previously the filters worked for .me and .us but now that they've moved to .cc the overlays are back.

### Versions

- Browser/version: Firefox 58.0.2
- uBlock Origin version: v1.15.10

### Settings

- added additional tracking, cookie warning, Korean ads and anti popads.net lists

### Notes

As far as I know these two filters fix the problem: 
thevideo.cc##.inplayer_signup_link
thevideo.cc##.p-a-0.m-a-0.col-xs-12:nth-of-type(3)

but I guess that all that's needed is to add the new domain to already existing filters since the inplayer_signup one already exists for thevideo.us

**Comment by SMed79** [comment]
```
$csp=child-src 'none';frame-src *;worker-src 'none',domain=thevideo.cc|thevideo.ch|thevideo.io|thevideo.me|thevideo.us|tvad.me|vidup.me
```
