### ISSUE TITLE
swb.de: breakage

### ISSUE THREAD

**Issue by om-hb** [uBlockOrigin/uAssets#16026]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.swb.de/`

### Category

breakage

### Describe the issue

Chatbot / live-chat button in the bottom right corner gets blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO enabled:
![Screenshot 2022-12-16 at 15-25-38 Energie   Telekommunikation für Bremen   umzu swb](https://user-images.githubusercontent.com/49337083/208119813-95653323-4f8b-4a0b-9050-75d5c599e0d4.png)

With uBO disabled:
![Screenshot 2022-12-16 at 15-25-59 Energie   Telekommunikation für Bremen   umzu swb](https://user-images.githubusercontent.com/49337083/208119971-f1148cb9-43b6-4869-8db2-2ea47db78d10.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 86943
  cosmetic: 38903
  scriptlet: 16702
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32280-40, 3m
    ublock-badware: 4191-0, 3m
    ublock-privacy: 301-0, 3m
    ublock-abuse: 77-0, 3m
    ublock-unbreak: 1928-2, 3m
    ublock-quick-fixes: 488-14, 3m
    easylist: 62168-610, 3m
    easyprivacy: 30998-1739, 3m
    urlhaus-1: 9884-0, 3m
    plowe-0: 3670-3, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5176 ms (selfie)
  maxAssetCacheWait: 558 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=swb.de`

@ryanbr
