### ISSUE TITLE
[nsfw] w.egybest.fit: detection

### ISSUE THREAD

**Issue by almakann** [uBlockOrigin/uAssets#16028]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://w.egybest.fit/`

### Category

Detection
And creation label and popup that prevente from running the website in comfortable way

### Describe the issue

Site detect origin adblocker and prevent me from browsing it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium Mobile: 107
filterset (summary): 
  network: 89278
  cosmetic: 28208
  scriptlet: 16756
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    adguard-mobile: 8353-27, 2d.3h.23m
    easylist: 63023-17293, 1d.2h.25m
    easyprivacy: 30983-1184, 1d.2h.24m
    plowe-0: 3677-984, 7d.18h
    ublock-abuse: 77-0, 3d.1h.14m
    ublock-badware: 4186-109, 1d.21h.1m
    ublock-filters: 31603-355, 1d.21h
    ublock-privacy: 254-2, 3d.1h.13m
    ublock-quick-fixes: 477-17, 22h.40m
    ublock-unbreak: 1920-46, 3d.1h.12m
    urlhaus-1: 9864-0, 22h.41m
filterset (user): [array of 4 redacted]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1165 ms
  maxAssetCacheWait: 463 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/10255
