### ISSUE TITLE
nl.motorsport.com: detection

### ISSUE THREAD

**Issue by kjvdven** [uBlockOrigin/uAssets#16024]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://nl.motorsport.com/f1/news/overzicht-starttijden-f1-races-2023-kalender/10394517/`

### Category

detection

### Describe the issue

They won't load the content of the page, but instead show an anoying message.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 96767
  cosmetic: 112286
  scriptlet: 19428
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    NLD-0: 2516-12, 1d.22h.29m
    adguard-annoyance: 62185-100, 2d.3m
    adguard-social: 19439-821, 2d.2m
  default: 
    user-filters: 12-1, never
    easylist: 65955-114, 6d.16h.56m
    easyprivacy: 30964-1257, 6d.16h.57m
    plowe-0: 3678-903, 4d.23h.24m
    ublock-abuse: 77-0, 6d.16h.55m
    ublock-badware: 4045-110, 2d.1m
    ublock-filters: 31496-507, 2d
    ublock-privacy: 254-3, 6d.16h.54m
    ublock-unbreak: 1917-59, 1d.23h.59m
    urlhaus-1: 9993-0, 1d.12h
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 17 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 292 ms (selfie)
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    motorsport.com: 1
    cxense.com: 1
    mmcdn.nl: 1
```
</details>

**Comment by mapx-** [comment]
> ublock-filters: 31496-507, 2d

![image](https://user-images.githubusercontent.com/10303732/208051343-2be301f7-2795-4d71-a4bf-d0bf03c71579.png)

Just do it !
