### ISSUE TITLE
dailytelegraph.com.au: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16033]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [x] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.dailytelegraph.com.au/newslocal/liverpool-leader/aland-settles-303-units-at-the-hoxton-in-liverpool-amid-apartment-shortage/news-story/9bb43cf2e212c154d4ab2a320edc3e06?amp`

### Category

breakage

### Describe the issue

I am using https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean to bypass news paywalls.
In doing so, the pictures are not shown properly on the site.
Can anything be done to fix this issue?
Thanks a lot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![No_Pics](https://user-images.githubusercontent.com/20948631/208235459-a67f4527-ebc5-4c4f-913f-49d935e6678d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 155995
  cosmetic: 215016
  scriptlet: 37735
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
  added: 
    adguard-annoyance: 62275-96, 1h.20m
    adguard-generic: 66336-510, 1h.20m
    adguard-social: 19473-823, 1h.20m
    adguard-spyware: 33784-3734, 1h.19m
    block-lan: 44-0, 1h.20m
    curben-phishing: 22887-1, 1h.20m
    curben-pup: 190-0, 1h.20m
    fanboy-annoyance: 83895-5114, 13m
    fanboy-social: 23465-23461, 13m
    fanboy-thirdparty_social: 68-21, 13m
    ublock-annoyances: 4797-235, 13m
  default: 
    easylist: 62168-934, 1h.21m
    easyprivacy: 30998-12348, 1h.18m
    plowe-0: 3670-983, 1h.20m
    ublock-abuse: 77-0, 1h.19m
    ublock-badware: 4187-269, 1h.19m
    ublock-filters: 31491-3733, 1h.19m
    ublock-privacy: 254-51, 1h.19m
    ublock-quick-fixes: 484-44, 1h.19m
    ublock-unbreak: 1916-105, 1h.19m
    urlhaus-1: 9080-1, 1h.19m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 374 ms
  maxAssetCacheWait: 627 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    dailytelegraph.com.au: 1
    adsafeprotected.com: 2
    ampproject.org: 3
    news.com.au: 3
    tiqcdn.com: 1
    vidora.com: 2
```
</details>

**Comment by mapx-** [comment]
report your issue at https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/issues

We do not remove paywalls
