### ISSUE TITLE
tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by Azure-Fang** [uBlockOrigin/uAssets#16031]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=11885&ItemNamePattern=Recipe%3A+Jagga-Drenched+%22Mud+Ball%22`

### Describe the issue

When performing searches on the site, Tamriel Trade Centre now detects adblock usage and prevents accessing the site further, displaying the following message:

"Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed"

### uBlock Origin version

1.45.2

### Browser name and version

Firefox x64 107.0.1

### Settings

None, default settings

**Comment by mapx-** [comment]
No anti adb on my side, tested in firefox / chrome.

follow these steps:
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by Azure-Fang** [comment]
Done all of the above. Still throwing the adblock message.
![image](https://user-images.githubusercontent.com/30414441/208234900-044e6e04-c8a0-4ca0-aff0-64f0ffe7e253.png)
![image](https://user-images.githubusercontent.com/30414441/208234923-1f933738-03cb-4218-a83c-85c7a0508fc7.png)

**Comment by mapx-** [comment]
repeated the tests logged on / off, same result: no issue on my end

**Comment by Azure-Fang** [comment]
Would've been nice to have been given further guidance on providing feedback before closure. Since the original posting, I have tested on two additional devices across two additional networks: Firefox 108.0.1 with UBO 1.45.2 on another Windows 10 Pro x64 PC on a residential network different from my own, and Android Firefox 108.1.0 with UBO 1.45.2 on a mobile network. Both instances were fresh installations of UBO with default settings, all lists updated prior to test. Same result, the US server side of the site throws detection and prevents access when attempting to search.

**Comment by mapx-** [comment]
You can still comment.

I tested in FF / chrome, us ip, eu ip, same result: no anti adb on my side.

**Comment by Azure-Fang** [comment]
It's also worth noting that I am not the only person having this issue: https://www.reddit.com/r/uBlockOrigin/comments/zp0x7m/antiadblock_on_this_website/

Additionally, a brief search of the subreddit shows that this has cropped up a few times over the past year (though a past filter recommendation applied today has no effect).

**Comment by Azure-Fang** [comment]
Further testing, I had forgotten in past tests to remove strict privacy control from Firefox and have tested that now. Even changing it to block nothing does not change the outcome and only toggling UBO off completely allows access to the site on any searches, though the base site (https://us.tamrieltradecentre.com/pc/Trade) is always accessible.

**Comment by mapx-** [comment]
Your screenshpot shows 20 scripts ("click to disable javascript"). mine 39:

![image](https://user-images.githubusercontent.com/10303732/208319238-c023d9b7-ba3f-4467-9de6-e19596ac1df1.png)

**Comment by mapx-** [comment]
try installing last dev build of uBO
https://github.com/gorhill/uBlock/releases/tag/1.45.3rc5

then force updating all the lists, don't add any other list, test again.

And be sure you finally follow ALL my indications above.

**Comment by whqwert** [comment]
I can reproduce this by adding `tamrieltradecentre.com##.adsbygoogle` to 'My Filters', I'm not sure why it would show the message with default settings.

**Comment by Azure-Fang** [comment]
- 1.45.3rc5 installed
- All settings reset to default again
- No additional filters active
- Cache purged and lists updated
- All other addons disabled
- All Firefox restrictions disabled
- Windows Defender (only installed AV) disabled
- Computer restarted
- My Filters completely empty
- My Rules completely empty

Still blocking.

**Comment by mapx-** [comment]
open uBO's logger, repeat the steps to get the issue, go back into the logger, post all blocked requests

**Comment by Azure-Fang** [comment]
Blocked requests
<details><summary>Logger output</summary>

```
+1
##a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)
us.tamrieltradecentre.com
dom
https://us.tamrieltradecentre.com/pc/Trade/SearchResult?
```
```
+0
google-analytics.com/analytics.js
<<
us.tamrieltradecentre.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5
--
us.tamrieltradecentre.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
*$script,redirect-rule=noopjs,domain=tamrieltradecentre.com
--
us.tamrieltradecentre.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||google-analytics.com^
--
us.tamrieltradecentre.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||paypalobjects.com^*/pixel.gif
--
us.tamrieltradecentre.com
3
image
https://www.paypalobjects.com/en_US/i/scr/pixel.gif
```
```
+0
https://us.tamrieltradecentre.com/pc/Trade/SearchResult?
```
</details>

**Comment by Azure-Fang** [comment]
And resulting screenshot from that instance, for good measure.
![image](https://user-images.githubusercontent.com/30414441/208323012-67e6481b-1d97-4743-b670-50c2e3d1b2bf.png)

**Comment by Azure-Fang** [comment]
Scratch my last rounds, I forgot to disable things on that last test. Been a long day and it's not even half over. _Now_ it's going through when before 3rc5 it was not with everything disabled.
