### ISSUE TITLE
[nsfw] movie066.com: ads

### ISSUE THREAD

**Issue by Azuri001** [uBlockOrigin/uAssets#16030]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.movie066.com/`

### Category

ads

### Describe the issue

The site shows ads, also the video player doesn't work when uBO is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/VZHEFDm

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 261192
  cosmetic: 268795
  scriptlet: 41760
  html: 952
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66336-6707, 2m
    adguard-mobile: 8358-170, 2m
    adguard-spyware: 33784-3553, 1m
    adguard-spyware-url: 861-3, 1m
    block-lan: 44-0, 1m
    curben-phishing: 22887-2, 1m
    curben-pup: 190-0, 1m
    adguard-annoyance: 62275-5829, 1m
    adguard-social: 19473-1680, 1m
    fanboy-thirdparty_social: 68-1, 1m
    fanboy-annoyance: 83874-71905, 1m
    fanboy-cookiemonster: 44004-17391, 1m
    fanboy-social: 23465-13745, 1m
    ublock-annoyances: 4821-37, 1m
    dpollock-0: 11397-525, 1m
    ALB-0: 301-10, 1m
    ara-0: 2737-243, 1m
    BGR-0: 1091-19, 1m
    CHN-0: 28564-25450, 1m
    CZE-0: 731-40, 1m
    [29 lists not shown]: [too many]
  default: 
    user-filters: 26271-1274, never
    ublock-filters: 32281-503, 2m
    ublock-badware: 4191-0, 2m
    ublock-privacy: 301-1, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1928-3, 2m
    ublock-quick-fixes: 492-0, 2m
    easylist: 62168-18244, 1m
    easyprivacy: 30998-12813, 1m
    urlhaus-1: 9080-0, 1m
    plowe-0: 3670-3, 1m
filterset (user): [array of 22436 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 706 ms (selfie)
  maxAssetCacheWait: 1864 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    baidu.com: 1
    bdstatic.com: 1
    xunlei.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||p.qlogo.cn^$3p
*.gif$domain=movie066.com,image
```

The videos are running fine on my end.
You have too many lists. Keep **ONLY** the default setup + CHN list.

Follow the steps here:
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by mapx-** [comment]
@cjx82630

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. https://github.com/easylist/easylistchina/commit/3ea8027538414e3a01a698bd7d8c9ba355a87b5e
